### PR TITLE
Fix TextField bug when the formatter repeatedly format

### LINKED ISSUE #67236: TextField maxLength property is not working correctly.
Sample app:
```
void main() => runApp(App());

class App extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            maxLength: 5,
            maxLengthEnforced: true
          )
        )
      )
    );
  }

}
```
When I enter only letters into the `TextField`, the length is not restricted and I can enter an unlimited amount of characters. When I enter only numbers into the `TextField`, it does not display more than 5 characters (as it should) although pressing backspace is bugged when typing more than 5 numbers. Example: If you type `12345678`, the `TextField` will show `12345` but typing backspace will do nothing 3 times as if the `TextField` contains `12345678` but is only showing `12345`.

`flutter doctor -v`:
```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale en-CA)
    • Flutter version 1.22.0 at C:\Flutter
    • Framework revision d408d302e2 (4 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\Matt\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio Canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio Canary
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\Matt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • ONEPLUS A6013 (mobile) • 9e76e20e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.
```

### LINKED ISSUE #67262: newValue property of formatEditUpdate function into TextInputFormatter class is not as expected
## Steps to Reproduce

1. Run this code or simply try [flutter_gallery](https://gallery.flutter.dev/#/demo/text-field) example.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            child: TextField(
              inputFormatters: [DecimalTextInputFormatter(decimalRange: 2),],
            ),
          ),
        ),
      ),
    );
  }
}

class DecimalTextInputFormatter extends TextInputFormatter {
  DecimalTextInputFormatter({int decimalRange})
      : assert(decimalRange == null || decimalRange >= 0,
            'DecimalTextInputFormatter declaretion error') {
        
    String dp = (decimalRange != null && decimalRange > 0)
        ? "([.][0-9]{0,$decimalRange}){0,1}"
        : "";
    String num = "[0-9]*$dp";

    _exp = new RegExp("^($num){0,1}\$");
  }

  RegExp _exp;

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    print('newValue: $newValue');
    print('oldValue: $newValue');
    
    if (_exp.hasMatch(newValue.text)) {
      return newValue;
    }
    return oldValue;
  }
}
```

2. Type "1.." in TextField
3. The TextField show "1." because "1.." not respect the right pattern 
4. If you try to delete one char nothing happens because the newValue in formatEditUpdate return "1.." and the delete action remove the last point so the user doesn't see any changes. 

### Antoher example

1. Run the code..
2. Type "1.."
3. TextField show "1."
4. Type "."
5. TextField show "1."
6. Type "4"
7. TextField show "1." , it should show "1.4" but newValue of formatEditUpdate has "1..4" and not respect the pattern

**Expected results:** 
newValue of formatEditUpdate should be the last value returned from formatEditUpdate function.

**Actual results:** 
newValue of formatEditUpdate function retain all char inserted so formatEditUpdate process newValue that is different from that TextField is showing.

<details>
  <summary>Flutter Doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.49.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
</details>

### LINKED ISSUE #67828: TextField with maxLength needs multiple delete taps to delete text
b/170458334

This can be repro'ed using the sample at: https://flutter.dev/docs/cookbook/forms/retrieve-input

Add `maxLength: 5` to the `TextField` widget and try entering: "123456789" to the text field. You will need to press backspace 5 times to start deleting the text. My hunch is that we are not storing the inner "cursor position" correctly. The data seems to be correct (pressing the FAB always returns 12345).

I recall this used to work so marking as regression.

### LINKED ISSUE #67895: Text Field backspace does not delete the last character when maxLength is specified
### Note: I ran this in the Dartpad. there's no need to create a new flutter project.
1. Run `flutter create bug`.
2. Update the files as follows: gist.github.com/b6409e10de32b280b8938aa75364fa7b
```dart
///main.dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final TextEditingController _controller = TextEditingController();
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  
  @override
  void dispose(){
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
            decoration: InputDecoration(
            labelText: "Type more than 9 Characters, then try to use the backspace key",
            ),
            controller: _controller,
            onChanged: (value){
              
              print(_controller.text);
            },
            maxLength: 9,
            ),
          ],
        ),
      ),
    );
  }
}

```
3. After entering more than specified maximum length characters in the textfield. the backspace won't delete the last character.

**Expected results:** 
Should Delete the last Character based on the specified `maxLength` property
**Actual results:** 
Did not delete the last character.
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

Fix a regressing bug introduced by https://github.com/flutter/flutter/commit/0d945a1a5643ab9d1091e9bc56aed4b281f05463

The engine was not notified when the formatter repeatedly format.

So sorry to introduced this bug, I added a test case to ensure that no mistake will be made again.

@justinmc @LongCatIsLooong please review, thanks.

## Related Issues

Fixes #67828 
Fixes #67236
Fixes #67262 
Fixes #67895 

## Tests

I added the following tests:

"Send text input state to engine when the input formatter rejects user input" in editable text test.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2212,8 +2212,16 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       _lastFormattedValue = value;
     }
 
-    // Setting _value here ensures the selection and composing region info is passed.
-    _value = value;
+    if (value == _value) {
+      // Please note that the setter will not notify subscribers if set duplicate values.
+      // If the value was modified by the formatter, the remote should be notified to keep in sync,
+      // if not modified, it will short-circuit.
+      _updateRemoteEditingValueIfNeeded();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/editable_text.dart:2219]: This function is manually called only when the value has not changed. In other cases, the controller's notifier will call it.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -4998,6 +4998,98 @@ void main() {
...
+    // setEditingState is called when remote value modified by the formatter.
+    state.updateEditingValue(const TextEditingValue(
+      text: 'I will be modified by the formatter.',
+    ));
+    expect(log.length, 1);
+    MethodCall methodCall = log[0];
+    expect(
+      methodCall,
+      isMethodCall('TextInput.setEditingState', arguments: <String, dynamic>{
+        'text': 'Flutter is the best!',
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/editable_text_test.dart:5062]: nit: if we only care about the text value here we can just say `containsPair('text, 'Flutter is the best!'),`. See https://api.flutter.dev/flutter/package-matcher_matcher/containsPair.html

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by AlexV525 — APPROVED** [review]
LGTM (as per @LongCatIsLooong ). The CI is complaining but it seems related with network. If it continues to failed, please merge new commits from master and try again.

**Review by justinmc — APPROVED** [review]
LGTM, thanks for the quick fix.  It looks like the tests are passing so this can be merged when the build is green.

**Comment by Knupper** [comment]
Will we see this fix as an hotfix in flutter 1.22.3?

**Comment by AlexV525** [comment]
Just added an request in #67828 .
