### PR TITLE
Run pub in interactive mode in flutter packages pub

### LINKED ISSUE #11407: pub publish not working
## Steps to Reproduce

1. Create a package
1. Run `flutter pub pub publish`

=> flutter prints out status and then just hangs just prior to publishing

1. Run `pub publish`

=> Upload succeeds

## Logs

```
   | Nothing output on stderr.
IO  : Spawning "tar --format=ustar --create --gzip --directory /Users/mit/dev/mit-plugins/packages/image_picker/. @/dev/stdin" in /Users/mit/dev/mit-plugins/packages/image_picker/.
FINE: Showing confirm message:
    | Looks great! Are you ready to upload your package

```

### PR DESCRIPTION
**Pull request by mravn-google**
Fixes #11407

### CODE REVIEW

**Review by jakobr-google — APPROVED** [review]
Code LGTM. It does mean that we're overriding a safeguard on publish, and users might end up publishing a package with warnings.

Maybe we should special-case publish, so we do a dry-run and have our own prompt before forcing the publish?

**Comment by Hixie** [comment]
This doesn't seem right. The "pub" subcommand is explicitly just a passthrough. It should probably be interactive, to passthrough properly.

If we want to support "publish" explicitly, we should handle it as a separate subcommand like "get" and "upgrade".

**Comment by Hixie** [comment]
@mravn-google What is your plan with this PR? (No particular rush, I'm just cleaning out the review queue.)

**Comment by mravn-google** [comment]
I plan to have an interactive solution ready for review sometime tomorrow.

**Comment by Hixie** [comment]
ooh, I look forward to it!

**Comment by mravn-google** [comment]
@Hixie PTAL on the approach. I'm working on a test that the interactive mode actually works, addressing the TODO in `packages/flutter_tools/test/commands/packages_test.dart`.

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -166,6 +166,30 @@ Future<int> runCommandAndStreamOutput(List<String> cmd, {
...
+    allowReentrantFlutter: allowReentrantFlutter,
+    environment: environment,
+  );
+  process.stdin.addStream(stdin);
+  final Future<dynamic> stdOutDone = stdout.addStream(process.stdout);
+  final Future<dynamic> stdErrDone = stderr.addStream(process.stderr);
+  // Wait for stdout and stderr to be fully processed, because process.exitCode
+  // may complete first.
+  await stdOutDone;
+  await stdErrDone;
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/base/process.dart]: Probably best to wait for both in a Future.wait in case they're interlocked somehow (not sure how buffering works here).

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 2]
```diff
@@ -129,11 +146,16 @@ class MockProcessManager implements ProcessManager {
 }
 
 class MockProcess implements Process {
+  MockProcess();
```
Comment (Hixie) [inline packages/flutter_tools/test/commands/packages_test.dart]: this constructor shouldn't be necessary?

**Comment by Hixie** [comment]
Seems fine to me. I'll let @cbracken or @tvolkert do a more thorough review.

File: packages/flutter_tools/test/commands/packages_test.dart (hunk 2 above)
Comment (cbracken) [reply packages/flutter_tools/test/commands/packages_test.dart]: Was it meant to be `const`?

**Comment by cbracken** [comment]
lgtm

**Review by cbracken — APPROVED** [review]

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 3]
```diff
@@ -98,18 +101,40 @@ void main() {
...
+    testUsingContext('publish', () async {
+      log.clear();
+      await createTestCommandRunner(new PackagesCommand()).run(<String>['packages', 'pub', 'publish']);
+      expect(log, hasLength(1));
+      expect(log[0], hasLength(2));
+      expect(log[0][0], matches(r'dart-sdk[\\/]bin[\\/]pub'));
+      expect(log[0][1], 'publish');
+    }, overrides: <Type, Generator>{
+      ProcessManager: () {
+        return new MockProcessManager((List<dynamic> command) {
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/packages_test.dart]: As per our offline conversation, this test will end up writing on stdout. It would be nicer if pubInteractively somehow could use an alternative stdout/stderr and write to that. Then the test could also see that the stdout is as expected

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 4]
```diff
@@ -120,20 +145,67 @@ class MockProcessManager implements ProcessManager {
...
   }
 
   @override
   dynamic noSuchMethod(Invocation invocation) => null;
 }
 
+/// Process that prompts the user to proceed, then asynchronously writes
+/// some lines to stdout before it exits.
+class PromptingProcess implements Process {
+  PromptingProcess(String prompt, List<String> outputLines) {
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/packages_test.dart]: To me this seems overly general for a one-off test. Perhaps hardcode the prompt and output lines - I think that would make the test easier to read.

**Review by sigurdm — COMMENTED** [review]
Generally LGTM, but I think it would be much nicer if we could mock the actual stdout. I don't know how hard that would be though. It might require even more context to be introduced.

File: packages/flutter_tools/test/commands/packages_test.dart (hunk 3 above)
Comment (mravn-google) [reply packages/flutter_tools/test/commands/packages_test.dart]: Done.

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 5]
```diff
@@ -120,20 +145,67 @@ class MockProcessManager implements ProcessManager {
...
+    _stdoutController.add(UTF8.encode(prompt));
+    _stdin.future.then((List<int> bytes) async {
```
[the remark this answers is not in the document]
Comment (mravn-google) [reply packages/flutter_tools/test/commands/packages_test.dart]: Done.

File: packages/flutter_tools/test/commands/packages_test.dart (hunk 4 above)
Comment (mravn-google) [reply packages/flutter_tools/test/commands/packages_test.dart]: I didn't do this, since the prompt and the output lines are really part of the test data, so they belong in the test itself. But the code has been restructured to keep test logic and data closer. PTAL.

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 6]
```diff
@@ -120,20 +145,67 @@ class MockProcessManager implements ProcessManager {
...
+      // echo stdin to stdout
+      _stdoutController.add(bytes);
+      if (bytes[0] == UTF8.encode('y')[0]) {
+        for (final String line in outputLines) {
+          await new Future<Null>.delayed(const Duration(), () {
```
[the remark this answers is not in the document]
Comment (mravn-google) [reply packages/flutter_tools/test/commands/packages_test.dart]: Dart experts say use `new Future<Null>(closure)`.
Done.

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 7]
```diff
@@ -120,20 +145,67 @@ class MockProcessManager implements ProcessManager {
...
+            _stdoutController.add(UTF8.encode('$line\n'));
+          });
+        }
+        await new Future<Null>.delayed(const Duration(), () {
```
[the remark this answers is not in the document]
Comment (mravn-google) [reply packages/flutter_tools/test/commands/packages_test.dart]: Done.

File: packages/flutter_tools/test/commands/packages_test.dart [hunk 8]
```diff
@@ -145,32 +147,35 @@ class MockProcessManager implements ProcessManager {
...
 
-/// Process that prompts the user to proceed, then asynchronously writes
+/// A process that prompts the user to proceed, then asynchronously writes
 /// some lines to stdout before it exits.
 class PromptingProcess implements Process {
-  PromptingProcess(String prompt, List<String> outputLines) {
-    _stdoutController.add(UTF8.encode(prompt));
+  Future<Null> showPrompt(String prompt, List<String> outputLines) async {
     _stdin.future.then((List<int> bytes) async {
       // echo stdin to stdout
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/packages_test.dart]: I think it would read better as:
```
_stdoutController.add(UTF8.encode(prompt));
var bytes = await _stdin.future;
if (bytes[0] == UTF8.encode('y')[0]) {
  _stdoutController.add(UTF8.encode('$line\n'));
}
await _stdoutController.close();
```

**Review by sigurdm — APPROVED** [review]
LGTM
