### PR TITLE
Fix overflow in stretching overscroll

### LINKED ISSUE #90197: Stretching overscroll expands beyond it's container
internal b/200130013

When overscrolling, the stretched content can expand beyond the bounds of the container it is in.

You can see it in this demo by overscrolling the contents of the dropdown list.

<details>
<summary> original repro code </summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        androidOverscrollIndicator: AndroidOverscrollIndicator.stretch,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hello Flutter'),
        actions: <Widget>[
          PopupMenuButton<int>(
            onSelected: (result) {},
            itemBuilder: (context) => <PopupMenuEntry<int>>[
              for (var i = 1; i <= 20; i++)
                PopupMenuItem<int>(
                  value: i,
                  child: Text(
                    'Some menu item $i',
                    style: TextStyle(height: 5, fontSize: 10),
                  ),
                ),
            ],
          ),
        ],
      ),
      body: const Center(
        child: Text('Hello World'),
      ),
    );
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/90197
Internal: internal b/200130013

This adds a ClipRect to prevent the stretch effect from overflowing the bounds of its parent container.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/90215

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 1]
```diff
@@ -308,4 +308,58 @@ void main() {
...
+          ],
+        )
+      )
+    ));
+
+    expect(find.text('Index 1'), findsOneWidget);
+    expect(tester.getCenter(find.text('Index 1')).dy, 51.0);
+
+    final TestGesture gesture = await tester.startGesture(tester.getCenter(find.text('Index 1')));
+    // Overscroll the start
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:351]: Nit: Period here.

**Review by justinmc — APPROVED** [review]
LGTM 👍   Are the golden failures expected?

**Review by dkwingsmt — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:351]: Ah thanks! Yes, the goldens are expected. I added an image that would otherwise be overflowing onto the following child. :)

Comment (Piinks) [reply packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:351]:
```suggestion
    // Overscroll the start.
```

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/90215

**Comment by volskaya** [comment]
Could the `ClipRect` please be optional?

**Comment by dkwingsmt** [comment]
@volskaya Can you explain the use case that excluding the ClipRect is useful?

**Comment by volskaya** [comment]
@dkwingsmt In my opinion this is not the correct place to apply the clip to. The popup menu button or any other container, material, card, what ever should handle their own clips as high in the widget tree as they can.

There shouldn't be multiple clips stacking randomly in the widget tree. It's unnecessary and a performance loss.

This clip wouldn't even be valid for fullscreen scrollables. Oh and scrollables have their own clip too.

Also some time ago there was a clean up of a lot of redundant or unnecessary clip operations, so adding a clip here seems like a slight step back.

**Comment by Piinks** [comment]
Hey @volskaya thanks for the feedback! I understand your concerns. I believe this is the right place to apply the clip. I don't think it is intuitive to expect the developer to apply clips based on a widget that is being applied automatically (via the ScrollBehavior).
This leaves open a wide opportunity for folks to experience this bug without understanding why. It would also mean the developer would need to stack clips themselves, which seems to be more inefficient.

> Also some time ago there was a clean up of a lot of redundant or unnecessary clip operations, so adding a clip here seems like a slight step back.

There are many widgets that apply a clip, this seems like an appropriate case as the overscroll is scaling the scrollable. This is also a new widget, it did not have a previous clip that was removed, so I do not see this as a step back.

I am going to see if I can tweak this though to only apply the clip when the overscroll is active, to address your performance concerns. Thanks!

**Comment by Piinks** [comment]
The G testing shard is expected, marking green. Trying to conditionally apply the clip did not solve the internal customer issue, so I am going to leave it as is right now. I have a refactor on another branch to address https://github.com/flutter/flutter/issues/88741 that I will need to merge and validate behavior against this change. 
I am going to merge this to unblock the customer and see about writing some benchmarks to address any concerns about performance. Thanks all!
