### PR TITLE
Relax `OverlayPortal` asserts

### LINKED ISSUE #129025: Tooltip exception: Bad state: Instance of '_OverlayEntryLocation' is already disposed
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the app with the sample code. Tap on the widgets to expand them a few times and close using the Done `IconButton`. After a few times the issue is seen.

### Expected results

No exceptions.

### Actual results

The following `StateError` is thrown:

```
Exception has occurred.
StateError (Bad state: Instance of '_OverlayEntryLocation' is already disposed. Stack trace: #0      _OverlayEntryLocation._dispose.<anonymous closure> (package:flutter/src/widgets/overlay.dart:1739:45)
#1      _OverlayEntryLocation._dispose (package:flutter/src/widgets/overlay.dart:1741:6)
#2      _OverlayPortalState.hide (package:flutter/src/widgets/overlay.dart:1603:21)
#3      OverlayPortalController.hide (package:flutter/src/widgets/overlay.dart:1351:13)
#4      TooltipState._handleStatusChanged (package:flutter/src/material/tooltip.dart:437:30)
#5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)
#7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:831:5)
#8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#10     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1149:11)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1147:17)
#13     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1064:5)
#14     _invoke1 (dart:ui/hooks.dart:186:13)
#15     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:374:5)
#16     _beginFrame (dart:ui/hooks.dart:129:31)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Future<void> _expandHeroWidget(String tag) {
    final Color barrierColor = Theme.of(context).colorScheme.onBackground.withOpacity(0.25);
    final HeroDialogRoute route = HeroDialogRoute(
      barrierColor: barrierColor,
      builder: (BuildContext context) {
        return Center(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: ConstrainedBox(
              constraints: const BoxConstraints(
                maxWidth: 600.0,
                maxHeight: 400.0,
              ),
              child: Hero(
                tag: tag,
                child: Material(
                  type: MaterialType.canvas,
                  color: Colors.amberAccent,
                  child: Row(
                    children: <Widget>[
                      IconButton(
                        onPressed: () {
                          final SnackBar snackBar = SnackBar(content: Text('SnackBar! $tag'));
                          ScaffoldMessenger.of(context).showSnackBar(snackBar);
                        },
                        icon: const Icon(Icons.abc),
                        tooltip: 'Show a snackbar',
                      ),
                      IconButton(
                        onPressed: () => Navigator.of(context).pop(),
                        icon: const Icon(Icons.check),
                        tooltip: 'Done',
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );

    return Navigator.of(context).push(route);
  }

  Widget _buildHeroWidget(String tag) {
    return Hero(
      tag: tag,
      child: Container(
        color: Colors.amber,
        width: 300.0,
        height: 200.0,
        child: Material(
          type: MaterialType.transparency,
          child: InkResponse(
            onTap: () => _expandHeroWidget(tag),
            child: RichText(
              text: const TextSpan(text: 'tap me'),
              overflow: TextOverflow.fade,
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[ 
            _buildHeroWidget('widget1'),
            const SizedBox(height: 10.0),
            _buildHeroWidget('widget2'),
            const SizedBox(height: 10.0),
            _buildHeroWidget('widget3'),
          ],
        ),
      ),
    );
  }
}

class HeroDialogRoute<T> extends PageRoute<T> {
  HeroDialogRoute({this.barrierColor = const Color(0x80000000), required this.builder})
      : super();

  final WidgetBuilder builder;

  @override
  bool get opaque => false;

  @override
  bool get barrierDismissible => true;

  @override
  String? get barrierLabel => null;

  @override
  final Color barrierColor;

  @override
  Duration get transitionDuration => const Duration(milliseconds: 200);

  @override
  bool get maintainState => true;

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    return FadeTransition(
      opacity: CurvedAnimation(parent: animation, curve: Curves.easeOut),
      child: child,
    );
  }

  @override
  Widget buildPage(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
  ) {
    return builder(context);
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel master, 3.12.0-4.0.pre.102, on macOS 13.4 22F66 darwin-arm64, locale en-ES)
    • Flutter version 3.12.0-4.0.pre.102 on channel master at /Users/tgucio/Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dc4541fa05 (15 minutes ago), 2023-06-16 19:00:21 +0100
    • Engine revision fb5fed432e
    • Dart version 3.1.0 (build 3.1.0-213.0.dev)
    • DevTools version 2.24.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/129025

Also 
- simplifies OverlayPortal code a bit and adds an assert.
-  `Tooltip` shouldn't rebuild when hiding/showing the tooltip

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/painting/geometry.dart [hunk 1]
```diff
@@ -48,27 +48,19 @@ Offset positionDependentBox({
   // VERTICAL DIRECTION
   final bool fitsBelow = target.dy + verticalOffset + childSize.height <= size.height - margin;
   final bool fitsAbove = target.dy - verticalOffset - childSize.height >= margin;
-  final bool tooltipBelow = preferBelow ? fitsBelow || !fitsAbove : !(fitsAbove || !fitsBelow);
+  final bool tooltipBelow = fitsAbove == fitsBelow ? preferBelow : fitsBelow;
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/geometry.dart:51]: Are these changes supposed to be in this PR? Just asking, since the PR description didn't mention it.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/painting/geometry.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/geometry.dart:51]: Yeah drive-through changes, should be covered by existing tests.
