### PR TITLE
Fixes metal vec3 uniform padding

### LINKED ISSUE #180873: enable 'FragmentShader shader with array uniforms renders correctly' for impeller
https://github.com/flutter/flutter/blob/82d232df03e35b3937ca3737ba0cf7f12777a2a8/engine/src/flutter/testing/dart/fragment_shader_test.dart#L480 fails on impeller.

It turns out that the `mat2Array` is partially initialized on impeller.  For example mat2Array[0][0][0] is its expected value, but mat2Array[0][1][0] is not, but mat2Array[1][0][0] is.

I've placed a print statement in the FragmentShader constructor for the size of the floats to intialize.  On skia it correctly reports 20, on impeller it reports 40.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/180873

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/compiler/compiler_test.cc [hunk 1]
```diff
@@ -106,6 +106,7 @@ bool CompilerTestBase::CanCompileAndReflect(
       entry_point_name);
 
   Reflector::Options reflector_options;
+  reflector_options.target_platform = GetParam();
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/compiler/compiler_test.cc:109]: This is just a residual change from when gemini was fiddling with the compiler tests.  I kept it since it's a good change.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc [hunk 2]
```diff
@@ -30,29 +30,47 @@ constexpr char kFloatType = 1;
...
-  size_t uniform_byte_index = 0u;
-  for (char byte_type : uniform.struct_layout) {
-    if (byte_type == kPaddingType) {
-      uniform_buffer.push_back(0.f);
-    } else {
-      FML_DCHECK(byte_type == kFloatType);
-      uniform_buffer.push_back(reinterpret_cast<const float*>(
-          input_data->data())[uniform_byte_index++]);
-    }
+  size_t count = uniform.array_elements.value_or(1);
```
Comment (b-luk) [inline engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: Is there a reason `count` is declared up here instead of within the callback? From a readability perspective, it makes sense to declare it right above the for-loop where it is used.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc [hunk 3]
```diff
@@ -30,29 +30,47 @@ constexpr char kFloatType = 1;
...
+  if (count == 0) {
```
Comment (b-luk) [inline engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: In what situation would count be 0?

File: engine/src/flutter/impeller/compiler/reflector.cc [hunk 4]
```diff
@@ -372,6 +372,25 @@ std::shared_ptr<RuntimeStageData::Shader> Reflector::GenerateRuntimeStageData()
...
     uniform_description.array_elements = GetArrayElements(spir_type);
+
+    if (TargetPlatformIsMetal(options_.target_platform) &&
+        uniform_description.type == spirv_cross::SPIRType::BaseType::Float) {
+      // Metal aligns float3 to 16 bytes.
+      // Metal aligns float3x3 COLUMNS to 16 bytes.
+      // For float3: Size 12. Padding 4. Stride 16.
+      // For float3x3: Size 36. Padding 12 (4 per col). Stride 48.
+
+      if (spir_type.vecsize == 3 &&
```
Comment (b-luk) [inline engine/src/flutter/impeller/compiler/reflector.cc:384]: So we need this specifically for vec3 and mat3, but not vec2/vec4/mat2/mat4? And specifically for floats but not ints or other types? Maybe add a comment to explain when it is/isn't needed.

File: engine/src/flutter/impeller/compiler/types.h [hunk 5]
```diff
@@ -55,7 +55,7 @@ struct UniformDescription {
   size_t columns = 0u;
   size_t bit_width = 0u;
   std::optional<size_t> array_elements = std::nullopt;
-  std::vector<uint8_t> struct_layout = {};
+  std::vector<uint8_t> padding_layout = {};
```
Comment (b-luk) [inline engine/src/flutter/impeller/compiler/types.h]: Should we try to use `fb::StructByteType` or some other shared enum as the type everywhere that padding_layout is used?

The 0s and 1s used in most places aren't very explanatory.  `runtime_effect_contents.cc` declares its own constants for 0 and 1 values, which is a little more informative but it's not great that they're siloed file-level constants.

I think it would be better if everything just consistently used the same enum. Ideally directly from the source of truth (`fb::StructByteType`) unless there is some dependency issue or another problem preventing that. If not `fb::StructByteType`, then maybe a shared enum declared in this file.

Comment (b-luk) [inline engine/src/flutter/impeller/compiler/types.h]: I think it's not very intuitive how `padding_layout` is structured and used. An explanatory comment (maybe with examples) would be helpful.

**Review by b-luk — COMMENTED** [review]
I'm not very familiar with this code, so I just have a bunch of nits for you and don't have any higher level thoughts on the overall approach. Maybe walley892 can probably be helpful for that.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: Yes, in c++ it's much more straightforward to capture an integer than a pointer.  We know that the callback is going to be called synchronously but there is no guarantee that will happen.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: Fields that are not arrays have `array_elements` as zero.

File: engine/src/flutter/impeller/compiler/types.h (hunk 5 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/types.h]: Done

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 4 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/reflector.cc:384]: I do have a comment above that explains this case.  I'm letting the combination of integration tests and comments like this document when they are necessary.

File: engine/src/flutter/impeller/compiler/reflector.cc [hunk 6]
```diff
@@ -372,6 +372,25 @@ std::shared_ptr<RuntimeStageData::Shader> Reflector::GenerateRuntimeStageData()
...
+          (spir_type.columns == 1 || spir_type.columns == 3)) {
```
Comment (walley892) [inline engine/src/flutter/impeller/compiler/reflector.cc:385]: This is kind of confusing. It may be more maintainable/readable if we had a function spir->array<uint> and explicitly made the call: `padding_layout = getPaddingLayout(type)` and define `getPaddingLayout` as something like

```{
...
// Vec3s are packed as Vec4
case spir_type.vecsize==3 && spir_type.columns == 1:
    return [1,1,1,0];
// Mat3s are packed as 3 vec4s
case spir_type.vecsize==3 && spir_type.columns == 3:
    return [1,1,1,0,
        1, 1, 1, 0,
        1, 1, 1, 0];
...
}
```
We may need to add more types in the future, or support for more platforms, or change the padding layout if we change spirv to use some different format. it would be ugly but more maintainable IMO.

File: engine/src/flutter/impeller/compiler/types.h (hunk 5 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/types.h]: Yea, I agree.  I was just following what was already here.  I fixed it, we use the shared enum now with flatbuffer when we can and explicitly convert it to the runtime enum.  The fb generated file wasn't available to me in the runtime_types so there is still a conversion, but it's explicit now.

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 6 above)
Comment (walley892) [reply engine/src/flutter/impeller/compiler/reflector.cc:385]: I'm also skeptical about maintaining our own mappings of uniform types to their padding layout. Have you tried to coax this information out of spirv directly?

Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/reflector.cc:385]: Yea, those are good points.  Now that i've moved us to enums from bluks feedback it's not going to be that pretty anymore.  This level of refinement and refactoring will be better to consider after we have a complete test suite that runs.  Otherwise, refactoring may be premature.  I'm not quite sure how this is going to look when we are done.

> I'm also skeptical about maintaining our own mappings of uniform types to their padding layout. Have you tried to coax this information out of spirv directly?

No, it's not bad right now but something we could look into in the future if it makes sense.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 2 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: I don't see why `count` needs to be captured at all. The callback captures `uniform`, which `count` depends on. So can't we just declare `count` as a local variable inside the callback?

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 3 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: I see. I would have expected fields that are not arrays to use the `optional` "no value" case. But ¯\\_(ツ)_/¯

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 4 above)
Comment (b-luk) [reply engine/src/flutter/impeller/compiler/reflector.cc:384]: So just to be clear, ints behave differently from floats, so an `ivec3` doesn't need padding like a `vec3`?

File: engine/src/flutter/impeller/compiler/types.h [hunk 7]
```diff
@@ -55,7 +56,10 @@ struct UniformDescription {
   size_t columns = 0u;
   size_t bit_width = 0u;
   std::optional<size_t> array_elements = std::nullopt;
-  std::vector<uint8_t> struct_layout = {};
+  /// The layout of padding bytes in the uniform buffer.
```
Comment (walley892) [inline engine/src/flutter/impeller/compiler/types.h:59]: Could you add a comment about how this is handled differently for struct and array types (vulkan vs metal). In vulkan, the padding_layout includes padding for the array type fields. For Metal, the padding_layout doesn't, and we rely on the `array_elements`.

It's consistent to think of it this way, but a little confusing at first.

File: engine/src/flutter/impeller/core/runtime_types.cc [hunk 8]
```diff
@@ -13,7 +13,9 @@ size_t RuntimeUniformDescription::GetSize() const {
     // NOLINTNEXTLINE(bugprone-unchecked-optional-access)
     size *= array_elements.value();
   }
-  size += sizeof(float) * struct_layout.size();
+  if (type == kStruct) {
+    size += sizeof(float) * padding_layout.size();
+  }
```
Comment (walley892) [inline engine/src/flutter/impeller/core/runtime_types.cc]: Can you document that `GetSize` has two different meanings?

`myStruct::GetSize` is the total physical size of the thing. I.e, what we send to the GPU including padding

`myArrayUniform::GetSize` is the logical size of the thing, not what we actually send over to the GPU.

File: engine/src/flutter/impeller/core/runtime_types.h [hunk 9]
```diff
@@ -38,6 +38,11 @@ struct RuntimeUniformDimensions {
   size_t cols = 0;
 };
 
+enum class RuntimeStructByteType : uint8_t {
```
Comment (walley892) [inline engine/src/flutter/impeller/core/runtime_types.h]: Nit: `Struct` here is a misnomer, since it describes the byte type (padding or data) for non structs

File: engine/src/flutter/impeller/compiler/types.h [hunk 10]
```diff
@@ -12,6 +12,7 @@
 #include <optional>
 #include <string>
 
+#include "runtime_stage_types_flatbuffers.h"
```
Comment (walley892) [inline engine/src/flutter/impeller/compiler/types.h:15]: Is this import safe? I remember seeing a PR from a while ago about detangling the dependencies between types, runtime_types, and flatbuffers.

File: engine/src/flutter/impeller/runtime_stage/runtime_stage_types.fbs [hunk 11]
```diff
@@ -43,7 +43,7 @@ table UniformDescription {
   rows: uint64;
   columns: uint64;
   array_elements: uint64;
-  struct_layout: [StructByteType];
+  padding_layout: [StructByteType];
```
Comment (walley892) [inline engine/src/flutter/impeller/runtime_stage/runtime_stage_types.fbs]: Same comment about renaming the type from `StructByteType`

File: engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc
Comment (walley892) [inline engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc:1]: There's a `case` right above the one you modified that checks the format on Metal, can you modify that to verify the field you've added?

**Review by walley892 — COMMENTED** [review]
I'm not sure of the overall approach in the long term, but this looks good for now. Could of comments

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 4 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/reflector.cc:384]: I don't know if that's the case.  It may just be a case that we don't have ivec3 tests.  We may not even have ivec3 support.

File: engine/src/flutter/impeller/compiler/types.h (hunk 10 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/types.h:15]: Safe meaning it won't cause runtime errors or build errors?  Yes it's safe and doesn't change the dependency graph at all.

This is an improvement from what we had previously and I'm open to further refactoring if someone has a cohesive idea about what should change.

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 4 above)
Comment (walley892) [reply engine/src/flutter/impeller/compiler/reflector.cc:384]: We don't support integer or boolean vec types

File: engine/src/flutter/impeller/compiler/types.h (hunk 7 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/types.h:59]: I think you are thinking about it a bit off.  padding_layout is agnostic to how its used.  On vulkan we use it to layout struct padding, on metal we use it for array layout.  It means the same thing in both cases though.  Adding comments to something about how it is used is fragile versus documenting what it is.

I've added a comment linking to where it is used.

File: engine/src/flutter/impeller/compiler/types.h (hunk 10 above)
Comment (walley892) [reply engine/src/flutter/impeller/compiler/types.h:15]: https://github.com/flutter/engine/pull/35360

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: This comes from flatbuffers fwiw

File: engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc
Comment (gaaclarke) [reply engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc:1]: done

File: engine/src/flutter/impeller/runtime_stage/runtime_stage_types.fbs (hunk 11 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/runtime_stage/runtime_stage_types.fbs]: done

File: engine/src/flutter/impeller/core/runtime_types.h (hunk 9 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/core/runtime_types.h]: done

File: engine/src/flutter/impeller/core/runtime_types.cc (hunk 8 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/core/runtime_types.cc]: Yea, I'm not a huge fan of this either.   I'll spend some time trying to detangle this.  Unfortunately the docstring is kind of ambiguous.  This is what I'd expect the implementation to be:

```c++
size_t RuntimeUniformDescription::GetSize() const {
  size_t size = 0;
  if (padding_layout.empty()) {
    size = dimensions.rows * dimensions.cols * bit_width / 8u;
  } else {
    size = sizeof(float) * padding_layout.size();
  }
  if (array_elements.value_or(0) > 0) {
    // Covered by check on the line above.
    // NOLINTNEXTLINE(bugprone-unchecked-optional-access)
    size *= array_elements.value();
  }
  return size;
}
```

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc]: Yea, missed we are already grabbing the uniform.  Done.

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 6 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/compiler/reflector.cc:385]: Note to future self: spv::DecorationArrayStride and spv::DecorationMatrixStride might be apropos to trying to tease the info

File: engine/src/flutter/impeller/core/runtime_types.cc (hunk 8 above)
Comment (walley892) [reply engine/src/flutter/impeller/core/runtime_types.cc]: If it works it works for now I guess

**Review by b-luk — APPROVED** [review]
lgtm as long as walley approves

File: engine/src/flutter/impeller/compiler/reflector.cc (hunk 6 above)
Comment (walley892) [reply engine/src/flutter/impeller/compiler/reflector.cc:385]: I tried grabbing `spv::DecorationArrayStride` and `spv::DecorationMatrixStride` locally earlier today, both reported zero :(.

There's a TODO comment in the spirv source about surfacing the physical size of uniforms. Maybe we could follow up on that? [third_party/vulkan-deps/spirv-cross/src/spirv_reflect.cpp::358](https://github.com/KhronosGroup/SPIRV-Cross/blob/main/spirv_reflect.cpp#L358)

**Review by walley892 — APPROVED** [review]
Nice

File: engine/src/flutter/impeller/core/runtime_types.cc (hunk 8 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/core/runtime_types.cc]: Ugh, this is bothering me.  For the vec3array in the test the current GetSize returns 24 bytes, but the proposed one returns 32 bytes.  This causes the test to fail.  This is not working as intended and shouldn't be landed until this is addressed.  My brain is spent for now.  I'll look monday =(

Comment (gaaclarke) [reply engine/src/flutter/impeller/core/runtime_types.cc]: Okay, got it sorted out.  There is a difference between the size a uniform takes up in the float buffer from dart and the size it will take up on the GPU because there is no padding in the dart float buffer.  I've gotten rid of the oddity and split the names apart.  This should clear everything up.  I'm not 100% happy with it but this gives the next person looking at the code an understanding of what is actually going on.

File: engine/src/flutter/impeller/core/runtime_types.cc [hunk 12]
```diff
@@ -4,17 +4,34 @@
 
 #include "impeller/core/runtime_types.h"
 
+#include "flutter/fml/logging.h"
+
 namespace impeller {
 
-size_t RuntimeUniformDescription::GetSize() const {
+size_t RuntimeUniformDescription::GetDartSize() const {
```
Comment (walley892) [inline engine/src/flutter/impeller/core/runtime_types.cc:11]: Instead of calling these `GPU` and `Dart` size, what about `Physical` and `Logical`?

Comment (gaaclarke) [reply engine/src/flutter/impeller/core/runtime_types.cc:11]: I think those are probably equally valid names.  We're going to have to lean into the docstring on this one since there is only so much semantic information you can pack into these names.  Logical vs Physical is sort of loaded with different meanings too already that aren't a 100% match.
