### PR TITLE
Fix a CupertinoScrollbar NNBD issue

### LINKED ISSUE #110625: _CastError at _CupertinoScrollbarState.handleThumbPressStart at package:flutter/src/cupertino/scrollbar.dart
b/244327588

Crash stack trace:

Upload Time: Tue, 30 Aug 2022 21:12:14 GMT

Thread 0 MAIN THREAD_CastError: gesture
at _CupertinoScrollbarState.handleThumbPressStart	(scrollbar.dart:188)
at RawScrollbarState._gestures.<anonymous closure>.<anonymous closure>	(scrollbar.dart:1915)
at LongPressGestureRecognizer._checkLongPressStart.<anonymous closure>	(long_press.dart:722)
at GestureRecognizer.invokeCallback	(recognizer.dart:253)
at LongPressGestureRecognizer._checkLongPressStart	(long_press.dart:722)
at PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent	(long_press.dart:620)
at PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure>	(recognizer.dart:586)
at TickerFuture.whenCompleteOrCancel.thunk	(ticker.dart:420)
at _Timer._runTimers	(timer_impl.dart:398)
at _Timer._handleMessage	(timer_impl.dart:429)
at _Timer._handleMessage	(timer_impl.dart:419)
at _RawReceivePortImpl._handleMessage	(isolate_patch.dart:192)

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/110625
I believe that the issue is an exception in production, I mean there will be assertion errors in debug mode.
I still modified some code because I wanted to be consistent with other places where `getScrollbarDirection` is used.
In fact, it's hard for test cases to test exactly what I've changed because the debug checking will fail the test first.

### CODE REVIEW

File: packages/flutter/test/cupertino/scrollbar_test.dart [hunk 1]
```diff
@@ -1060,6 +1060,50 @@ void main() {
...
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.pumpAndSettle();
+
+    final ScrollPosition position = scrollController.position;
+    scrollController.detach(position);
```
Comment (Piinks) [inline packages/flutter/test/cupertino/scrollbar_test.dart:1089]: 💀  lol

File: packages/flutter/test/cupertino/scrollbar_test.dart [hunk 2]
```diff
@@ -1060,6 +1060,50 @@ void main() {
...
+    FlutterErrorDetails? error;
+    FlutterError.onError = (FlutterErrorDetails details) {
+      error = details;
+    };
+
+    // long press the thumb
+    await tester.startGesture(const Offset(796.0, 50.0));
+    await tester.pump(kLongPressDuration);
+
+    expect(error, isNotNull);
```
Comment (Piinks) [inline packages/flutter/test/cupertino/scrollbar_test.dart:1101]: What is the error message here? The stack trace we got in the issue was not very helpful, does this help the user understand what is happening?

File: packages/flutter/lib/src/cupertino/scrollbar.dart [hunk 3]
```diff
@@ -185,7 +185,10 @@ class _CupertinoScrollbarState extends RawScrollbarState<CupertinoScrollbar> {
   @override
   void handleThumbPressStart(Offset localPosition) {
     super.handleThumbPressStart(localPosition);
-    final Axis direction = getScrollbarDirection()!;
+    final Axis? direction = getScrollbarDirection();
+    if (direction == null) {
```
Comment (Piinks) [inline packages/flutter/lib/src/cupertino/scrollbar.dart:189]: Do we need to add this to all calls to `getScrollbarDirection`?

**Comment by Piinks** [comment]
BTW - thank you for picking this up so quickly. 💙

File: packages/flutter/lib/src/cupertino/scrollbar.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/cupertino/scrollbar.dart:189]: I checked, looks like we do this everywhere else. This was the exception.

File: packages/flutter/test/cupertino/scrollbar_test.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/test/cupertino/scrollbar_test.dart:1101]: I believe that the issue is an exception in production mode, I mean there should be assertion errors before this exception in debug mode.
I still modified some code because I wanted to be consistent with other places where getScrollbarDirection is used.
In fact, it's hard for test cases to test exactly what I've changed because the debug checking will fail the test first.

Comment (Piinks) [reply packages/flutter/test/cupertino/scrollbar_test.dart:1101]: I see. Sounds good, thank you.

**Review by Piinks — APPROVED** [review]
LGTM - thank you again
