### PR TITLE
Force plugin transitive dependencies to an ARC compatible version

### LINKED ISSUE #124340: Upgrading to Xcode 14.3 will not build when plugin transitive dependencies have a low deployment target: File not found: XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
Steps to reproduce 

1. Check out 3.7.10 or be on master to pick up https://github.com/flutter/flutter/issues/123890
2. 
```
$ flutter create test_create
$ cd test_create
```
3. Add a plugin with a lower-than-9 iOS dependency target (I used `flutter_appauth`) as a pubspec dependency.
4.
```
$ flutter build ios
```

Does not build:
```
Error (Xcode): File not found: /Users/m/Applications/Xcode-14-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

On macOS this is `libarclite_macosx.a`

Customers are reporting updating the pod's `IPHONEOS_DEPLOYMENT_TARGET` version fixes it.  https://github.com/flutter/flutter/issues/123890#issuecomment-1499278832

### PR DESCRIPTION
**Pull request by jmagman**
Xcode 14.3 (released March 30, 2023) stopped building automatic reference counted (ARC) code targeting < iOS 9 or < macOS 10.11 by removing a `libarclite_*` library from the toolchain that was needed to link for these older targets.

Flutter was already forcing Flutter plugins to the same minimum version as the app, but wasn't doing so for the plugins's transitive dependencies.  In particular, some Firebase plugins depend on pods targeting lower versions.

Force transitive dependencies to a minimum version of at least iOS 9 or macOS 10.11. 

https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_test_ios/16683
https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_test_macos/3136

Fixes https://github.com/flutter/flutter/issues/124340

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/bin/podhelper.rb [hunk 1]
```diff
@@ -99,12 +105,14 @@ def flutter_additional_ios_build_settings(target)
 def flutter_additional_macos_build_settings(target)
   return unless target.platform_name == :osx
 
-  # Return if it's not a Flutter plugin (transitive dependency).
-  return unless target.dependencies.any? { |dependency| dependency.name == 'FlutterMacOS' }
-
   # [target.deployment_target] is a [String] formatted as "10.8".
   deployment_target_major, deployment_target_minor = target.deployment_target.match(/(\d+).?(\d*)/).captures
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/podhelper.rb:109]: unrelated, but we should escape the `.` here, right? we can do it later if you want to hotfix this.

File: packages/flutter_tools/bin/podhelper.rb [hunk 2]
```diff
@@ -123,6 +131,12 @@ def flutter_additional_macos_build_settings(target)
   end
 
   target.build_configurations.each do |build_configuration|
+    # ARC code targeting macOS 10.10 does not build on Xcode 14.3. Force to at least macOS 10.11.
+    build_configuration.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.11' if force_to_arc_supported_min
+
+    # Skip other updates if it's not a Flutter plugin (transitive dependency).
+    next unless target.dependencies.any? { |dependency| dependency.name == 'FlutterMacOS' }
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/podhelper.rb:138]: what if it has dependencies that have dependencies on FlutterMacOS?

File: packages/flutter_tools/bin/podhelper.rb (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/bin/podhelper.rb:109]: Yes, human regex debugger.  I'll do that in master though as you say since I do want to hotfix this.

File: packages/flutter_tools/bin/podhelper.rb (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/bin/podhelper.rb:138]: They would each be processed separately in this loop.  The ones that depend on Flutter (Flutter plugins) will continue no matter if it's a dependency of something else or not, but the ones that don't (non-Flutter plugin transitive dependencies) won't.

Did I understand the question?

Comment (christopherfujino) [reply packages/flutter_tools/bin/podhelper.rb:138]: Ahh, makes sense!

**Review by christopherfujino — APPROVED** [review]
Lgtm

**Review by vashworth — APPROVED** [review]
LGTM
