### PR TITLE
[a11y] fix table semantics cache for cells 

### LINKED ISSUE #170575: [web] TextField inside TableRow without TableCell wrapper does not accept input on web when semantics are enabled
#### Description

On Flutter Web, when a `TextField` is placed directly inside a `TableRow` (i.e., not wrapped in a `TableCell`), the text field does not accept any input when accessibility semantics are enabled. The text field appears focusable: the caret is visible, and the field gains focus as expected. However, when the user types, no text appears in the field.

#### Steps to Reproduce

1. Create a `Table` with a `TableRow` containing a `TextField` directly (not wrapped in `TableCell`).
2. Enable semantics with `SemanticsBinding.instance.ensureSemantics()`.
3. Attempt to focus and type into the field.

#### Workarounds

- Wrapping the `TextField` in a `TableCell` resolves the issue.

However, the documentation for `TableRow.children` states:

> Children may be wrapped in `TableCell` widgets to provide per-cell configuration to the `Table`, but children are not required to be wrapped in `TableCell` widgets.

This suggests that `TableCell` wrapping should be optional. 

### Expected results

The `TextField` should accept input as normal, regardless of whether it is wrapped in a `TableCell`.

### Actual results

On web, the `TextField` gains focus but does not respond to keyboard input when not wrapped in a `TableCell`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Table(
          children: [
            TableRow(
              children: [
                TableCell(
                  child: TextField(),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-US) [519ms]
    • Flutter version 3.32.3 on channel stable at /Users/user/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c1433509f (2 days ago), 2025-06-11 13:12:24 -0700
    • Engine revision 31c4875c7a
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,837ms]
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4) [1,061ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [30ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [29ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] IntelliJ IDEA Community Edition (version 2024.2.3) [28ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available) [11.4s]
    • iPhone 15 Pro Max (mobile) • 8C684370-7222-4C78-A294-767809F4010E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 137.0.7151.104

[✓] Network resources [663ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by hannah-hyj**
will fix https://github.com/flutter/flutter/issues/170575 
The issue is caused by: 

when caching the cell wrapper semantics nodes in table, it's using cell index to cache them in a map. But the cell index class was not set to immutable and override the `==`, so the cache logic was wrong, they were always creating new semantics nodes for cell wrapper. 

fixing this by fixing the index class to an immutable value type with proper == and hashCode

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/widgets/table_test.dart [hunk 1]
```diff
@@ -1025,4 +1025,41 @@ void main() {
 
     semantics.dispose();
   });
+
+  testWidgets('Table reuse the semantics nodes for cell wrappers', (WidgetTester tester) async {
+    final SemanticsTester semantics = SemanticsTester(tester);
```
Comment (chunhtai) [inline packages/flutter/test/widgets/table_test.dart]: This doesn't seem to be used

**Review by chunhtai — APPROVED** [review]
LGTM, left a comment about the test
