### PR TITLE
handle an exit code from android n

### LINKED ISSUE #3910: flutter daemon fails on device disconnect
when run with the android n adb tools:

```
Exit code 255 from: adb -s 08da19da02e426db shell getprop


package:flutter_tools/src/base/process.dart 142                   _runWithLoggingSync
package:flutter_tools/src/base/process.dart 84                    runCheckedSync
package:flutter_tools/src/android/android_device.dart 58          AndroidDevice._getProperty
package:flutter_tools/src/android/android_device.dart 81          AndroidDevice.platform
package:flutter_tools/src/commands/daemon.dart 381                _deviceToMap
package:flutter_tools/src/commands/daemon.dart 339                DeviceDomain.DeviceDomain.<fn>
```

cc @DaveShuckerow

### PR DESCRIPTION
**Pull request by devoncarew**
- fix an issue with a changed exit code w/ the android n tools (fix https://github.com/flutter/flutter/issues/3910)
- make the flutter daemon more resilient to exceptions thrown while it's running (before, the top level handler in executable would print the error and call `exit`)

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -54,13 +54,19 @@ class AndroidDevice extends Device {
...
-      for (Match m in propertyExp.allMatches(getpropOutput)) {
-        _properties[m.group(1)] = m.group(2);
+
+      try {
+        String getpropOutput = runCheckedSync(adbCommandForDevice(<String>['shell', 'getprop']));
+        RegExp propertyExp = new RegExp(r'\[(.*?)\]: \[(.*?)\]');
+        for (Match m in propertyExp.allMatches(getpropOutput))
+          _properties[m.group(1)] = m.group(2);
+      } catch (error, trace) {
+        printError('Error reteiving device properties: $error');
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/android/android_device.dart]: typo: retrieving

File: packages/flutter_tools/lib/src/base/context.dart [hunk 2]
```diff
@@ -56,7 +58,10 @@ class AppContext {
     }
   }
 
-  dynamic runInZone(dynamic method()) {
-    return runZoned(method, zoneValues: <String, dynamic>{'context': this});
+  dynamic runInZone(dynamic method(), { ErrorHandler onError }) {
+    return runZoned(method,
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/base/context.dart]: Asymmetric braces

**Comment by yjbanov** [comment]
LGTM if LGT Travis
