### PR TITLE
Fix Backbutton is not displayed when there is a endDrawer

### LINKED ISSUE #80256: BackButton is not displayed when there is a endDrawer
in Flutter 2.0 ,my app page has a endDrawer and it can pop.but the backbutton is not show .I found it in app_bar.dart

image

is this a bug or a new feature

### PR DESCRIPTION
**Pull request by chunhtai**
Previously the appbar infer backbutton from navigator.canpop, and Scaffold end drawer. It is hard to maintain. The internal use case is that they also want to backbutton to show up if there is a nested navigator in the route, so we have to provide a API to add appbar on route level as well.

This pr makes it so the ModalRoute.impliesAppBarDismissal is the single source of truth to add back button. There are two ways people can add backbutton.
1. overrides the ModalRoute.impliesAppBarDismissal directly
2. add a localhistory entry with impliesAppBarDismissal=true.

fixes https://github.com/flutter/flutter/issues/80256

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -455,13 +455,17 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
 /// An entry in the history of a [LocalHistoryRoute].
 class LocalHistoryEntry {
   /// Creates an entry in the history of a [LocalHistoryRoute].
-  LocalHistoryEntry({ this.onRemove });
+  LocalHistoryEntry({ this.onRemove, this.impliesAppBarDismissal = true });
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:458]: I think this should default to false, but i made it true for backward compatibility

**Comment by chunhtai** [comment]
This change will require a internal fix, since some of the internal test still relies on willHandlePopInternally to bring up the backbutton

**Comment by chunhtai** [comment]
a friendly bump

**Review by dnfield — APPROVED** [review]
