### PR TITLE
Fix accessibility events not being correctly translated to ATK

### LINKED ISSUE #176360: Screen reader not working on Flutter 3.35.x
### Steps to reproduce

1. Create a basic skeleton app with text buttons
2. Turn on the screen reader
3. Focus a button, and hear no output

### Expected results

The screen reader should read focused elements on screen, like "button".

### Actual results

The screen reader does not read *any* elements on screen.

The screen reader seems to work fine on any version before 3.35.0, like 3.32.7.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            FilledButton(onPressed: () {}, child: Text('My test button')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[  +16 ms] Unable to locate an Android SDK.
[   +1 ms] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +25 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] Skipping pub get: version match.
[  +48 ms] Skipping generating web_plugin_registrant.dart because it is up-to-date.
[  +15 ms] Generating /home/[USERNAME]/Projects/temp/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +2 ms] Skipping generating GeneratedPluginRegistrant.java because it is up-to-date.
[   +2 ms] Skipping generating generated_plugin_registrant.h because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.cc because it is up-to-date.
[   +1 ms] Skipping generating generated_plugins.cmake because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.h because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.cc because it is up-to-date.
[        ] Skipping generating generated_plugins.cmake because it is up-to-date.
[   +1 ms] Skipping generating GeneratedPluginRegistrant.h because it is up-to-date.
[        ] Skipping generating GeneratedPluginRegistrant.m because it is up-to-date.
[        ] Skipping generating GeneratedPluginRegistrant.swift because it is up-to-date.
[  +25 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/[USERNAME]/Projects/temp/example/.dart_tool/package_config.json}
[  +15 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +1 ms] /home/[USERNAME]/fvm/versions/3.35.0/bin/cache/dart-sdk/bin/dartaotruntime /home/[USERNAME]/fvm/versions/3.35.0/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /home/[USERNAME]/fvm/versions/3.35.0/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_VERSION=3.35.0 -DFLUTTER_CHANNEL=stable -DFLUTTER_GIT_URL=https://github.com/flutter/flutter.git -DFLUTTER_FRAMEWORK_REVISION=b896255557 -DFLUTTER_ENGINE_REVISION=1e9a811bf8 -DFLUTTER_DART_VERSION=3.9.0 --output-dill /tmp/flutter_tools.KLBPMI/flutter_tool.DTJXNW/app.dill --packages /home/[USERNAME]/Projects/temp/example/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/f77f32270fb2d1afd0aeffe6d0af0ebe.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +11 ms] Building Linux application...
[   +5 ms] <- compile package:example/main.dart
[   +1 ms] executing: [/home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/[USERNAME]/Projects/temp/example/linux
[  +67 ms] -- Configuring done (0.1s)
[   +4 ms] -- Generating done (0.0s)
[ +106 ms] -- Build files have been written to: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug
[   +4 ms] executing: ninja -C /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug install
[  +59 ms] ninja: Entering directory `/home/[USERNAME]/Projects/temp/example/build/linux/x64/debug'
[+1330 ms] [1/5] Generating /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/[USERNAME]/Projects/temp/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[        ] [  +18 ms] Unable to locate an Android SDK.
[        ] [   +3 ms] executing: uname -m
[        ] [   +3 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +28 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [   +8 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +19 ms] Skipping target: gen_dart_plugin_registrant
[        ] [   +1 ms] Skipping target: dart_build
[        ] [ +586 ms] Skipping target: unpack_linux
[        ] [        ] Skipping target: gen_localizations
[        ] [        ] Skipping target: install_code_assets
[        ] [ +206 ms] Skipping target: kernel_snapshot_program
[        ] [ +144 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [        ] "flutter assemble" took 1,021ms.
[        ] [   +7 ms] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] [1/2] Install the project...
[        ] -- Install configuration: "Debug"
[   +5 ms] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/example
[        ] -- Set non-toolchain portion of runtime path of "/home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/example" to "$ORIGIN/lib"
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/icudtl.dat
[   +2 ms] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +101 ms] -- Up-to-date: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/lib
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/NativeAssetsManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +47 ms] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +2 ms] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/example/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[   +9 ms] Building Linux application... (completed in 1,755ms)
[   +1 ms] ✓ Built build/linux/x64/debug/bundle/example
[ +116 ms] Gdk-Message: 10:04:12.240: Unable to load  from the cursor theme
[  +34 ms] VM Service URL on device: http://127.0.0.1:36665/6HSmY7TLx9k=/
[   +2 ms] Caching compiled dill
[  +38 ms] Connecting to service protocol: http://127.0.0.1:36665/6HSmY7TLx9k=/
[  +62 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:36665/6HSmY7TLx9k=/.
[  +94 ms] Successfully connected to service protocol: http://127.0.0.1:36665/6HSmY7TLx9k=/
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[   +7 ms] DevFS: Created new filesystem on the device (file:///tmp/examplePEFZRT/example/)
[   +1 ms] Updating assets
[  +45 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +1 ms] <- recompile package:example/main.dart 10c2d29c-a643-4364-8253-06f6c578f2b5
[        ] <- 10c2d29c-a643-4364-8253-06f6c578f2b5
[        ] Bundle processing done.
[  +46 ms] Updating files.
[        ] Pending asset builds completed. Writing dirty entries.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 50ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x6457628679b0.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on Linux is available at: http://127.0.0.1:34613/iVxzXHx7a74=/
[ +232 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9105?uri=http://127.0.0.1:34613/iVxzXHx7a74=/
[+16976 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///tmp/examplePEFZRT/example/)
[        ] DevFS: Deleted filesystem on the device (file:///tmp/examplePEFZRT/example/)
[   +1 ms] "flutter run" took 19,650ms.
[   +1 ms] Running 3 shutdown hooks
[  +15 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.0, on Ubuntu 24.04.3 LTS 6.14.0-29-generic, locale en_US.UTF-8) [27ms]
    • Flutter version 3.35.0 on channel stable at /home/[USERNAME]/fvm/versions/3.35.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b896255557 (7 weeks ago), 2025-08-13 17:14:08 -0700
    • Engine revision 1e9a811bf8
    • Dart version 3.9.0
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-lldb-debugging

[✗] Android toolchain - develop for Android devices [18ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome) [7ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop [122ms]
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    ! Unable to access driver information using 'eglinfo'.
      It is likely available from your distribution (e.g.: apt install mesa-utils)

[!] Android Studio (not installed) [5ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] VS Code (version 1.104.1) [5ms]
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.116.0

[✓] Connected device (1 available) [20ms]
    • Linux (desktop) • linux • linux-x64 • Ubuntu 24.04.3 LTS 6.14.0-29-generic

[✓] Network resources [205ms]
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

### PR DESCRIPTION
**Pull request by robert-ancell**
This was a regression introduced in 117c60edcf1f6843e71a8ff8107eb6c3d2af9041 which didn't correctly migrate to the newer tristate a11y API.

Fixes https://github.com/flutter/flutter/issues/176360

### CODE REVIEW

**Comment by robert-ancell** [comment]
We will want to cherry pick this to stable once it lands in main.

File: engine/src/flutter/shell/platform/linux/fl_accessible_node_test.cc [hunk 1]
```diff
@@ -71,31 +76,240 @@ TEST(FlAccessibleNodeTest, SetExtents) {
...
+
+  FlutterSemanticsFlags flags2 = {};
+  flags2.is_text_field = true;
+  EXPECT_CALL(mock_gtk, atk_object_notify_state_change(
+                            ::testing::_, ATK_STATE_EDITABLE, TRUE));
+  fl_accessible_node_set_flags(node, &flags2);
+  AtkStateSet* state2 = atk_object_ref_state_set(ATK_OBJECT(node));
+  EXPECT_TRUE(atk_state_set_contains_state(state2, ATK_STATE_EDITABLE));
+  g_object_unref(state2);
+}
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/linux/fl_accessible_node_test.cc:309]: Nit: I wonder if these tests are a good opportunity to parameterize. Seems like a bunch of similar-ish code. Not blocking though.

**Review by mattkae — APPROVED** [review]
One comment on the test code, but looks good other than that!

**Comment by robert-ancell** [comment]
@loic-sharma are you able to check what is failing in the Google testing?

**Review by loic-sharma — APPROVED** [review]
LGTM! Please feel free to ping me on Discord if you need any help with the cherrypick :)
