### PR TITLE
Fix bug when updating the `divisions` and `value` of the slider at the same time

### LINKED ISSUE #65943: Divisions of Slider widget does not work as expected when setState() max value and current value at the same time
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the `main.dart` as follows:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _currentValue = 0;
  double _maxValue = 10;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo'),
      ),
      body: Center(
        child: Slider(
          min: 0,
          max: _maxValue,
          value: _currentValue,
          divisions: _maxValue.toInt(),
          onChanged: (value) {},
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _maxValue = 15;
            _currentValue = 5;
          });
        },
        child: Icon(Icons.refresh),
      ),
    );
  }
}
```

**Expected results:** 

value of Slider move to right place when I click floatingActionButton once.

**Actual results:** 

value of Slider move to right place when I click floatingActionButton twice.

<details>
  <summary>Logs</summary>

```
owen$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/owen/Flutter/fluttersdk/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/owen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode11.7.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

When updating the `divisions` and `value` of the slider at the same time, the position of the thumb is wrong because the old `divisions` value is used.

## Related Issues

Fixes #65943 

## Tests

See files.

### CODE REVIEW

**Comment by guidezpl** [comment]
Looks good! Could you do the same update for `RangeSlider` as well?

**Comment by xu-baolin** [comment]
> Looks good! Could you do the same update for `RangeSlider` as well?

@guidezpl Nice caught :)

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -2431,4 +2432,99 @@ void main() {
           ..circle(x: 5.0, y: 5.0, radius: 10.0, )
     );
   });
+
+  testWidgets('Update the divisions and value at the same time for Slider', (WidgetTester tester) async {
+    // Regress test for https://github.com/flutter/flutter/issues/65943
+    Widget buildFrame(double  maxValue) {
```
Comment (guidezpl) [inline packages/flutter/test/material/slider_test.dart:2438]: super nit: double space

File: packages/flutter/lib/src/material/slider.dart [hunk 2]
```diff
@@ -837,8 +837,11 @@ class _SliderRenderObjectWidget extends LeafRenderObjectWidget {
   @override
   void updateRenderObject(BuildContext context, _RenderSlider renderObject) {
     renderObject
-      ..value = value
+      // We should update the `divisions` ahead of `value`, because the `value`
```
Comment (guidezpl) [inline packages/flutter/lib/src/material/slider.dart:840]: Since the regression tests link to this issue, this comment and the one in `range_slider.dart`arent' strictly necessary

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

File: packages/flutter/test/material/slider_test.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/test/material/slider_test.dart]: Fixed.

File: packages/flutter/lib/src/material/slider.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/slider.dart:840]: Removed.

File: packages/flutter/test/material/slider_test.dart (hunk 1 above)
Comment (berrylawchingman) [reply packages/flutter/test/material/slider_test.dart]: 👍

**Comment by wenxiangjiang** [comment]
Well done. Thanks.

IMG_7471

**Review by guidezpl — APPROVED** [review]
