### PR TITLE
Fix CupertinoSliverRefreshControl onRefresh callback

### LINKED ISSUE #31382: CupertinoSliverRefreshControl hangs if `onRefresh` completes with error
## Steps to Reproduce

1. Run code below
2. Pull to refresh
3. `RefreshIndicator` completes even if the future returns an exception, while `CupertinoSliverRefreshControl` hangs in `RefreshIndicatorMode.refresh`

I think the reason is `CupertinoSliverRefreshControl` completes future with `widget.onRefresh()..then` while `RefreshIndicator` completes future with `refreshResult.whenComplete`

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/refresh.dart#L457

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/refresh_indicator.dart#L372

Cupertino

Material

### Code

Change `_testCupertino` to `_testMaterial` to check the difference
```dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  MyApp();
}

class MyApp extends StatefulWidget {
  MyApp();

  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  Future<void> onRefresh() {
    Completer completer = Completer();
    Future.delayed(Duration(seconds: 1), () {
      completer.completeError('test error');
    });
    return completer.future;
  }

  CustomScrollView _testCupertino() {
    return CustomScrollView(
      slivers: <Widget>[
        CupertinoSliverRefreshControl(
          onRefresh: onRefresh,
        ),
        SliverList(delegate: SliverChildBuilderDelegate((context, index) {
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text('demo'),
          );
        }))
      ],
    );
  }

  RefreshIndicator _testMaterial() {
    return RefreshIndicator(
      child: CustomScrollView(
        slivers: <Widget>[
          SliverList(delegate: SliverChildBuilderDelegate((context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: Text('demo'),
            );
          }))
        ],
      ),
      onRefresh: onRefresh,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: _testCupertino(),
        ),
      ),
    );
  }
}

```

```
```

`flutter doctor -v` 
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/edward/dev/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/edward/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[!] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone Xs      • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

Replace `CupertinoSliverRefreshControl.onRefresh`'s `then` callback with `whenCompleted` callback, so when `onRefresh` completes with error the sliver refresh control retracts like when it completes with value.

## Related Issues

Fixes #31382

## Tests

I added the following tests:

- refreshing task keeps the sliver expanded forever until completes with error

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/refresh.dart [hunk 1]
```diff
@@ -463,7 +463,8 @@ class _CupertinoSliverRefreshControlState extends State<CupertinoSliverRefreshCo
             // user supplied and we're always here in the middle of the sliver's
             // performLayout.
             SchedulerBinding.instance.addPostFrameCallback((Duration timestamp) {
-              refreshTask = widget.onRefresh()..then((_) {
+              refreshTask = widget.onRefresh()
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/refresh.dart]: I think it fits in the previews line. Otherwise we'd have to reindent everything

File: packages/flutter/test/cupertino/refresh_test.dart [hunk 2]
```diff
@@ -373,6 +374,76 @@ void main() {
...
+          await tester.pump(const Duration(seconds: 1));
+          verify(mockHelper.builder(
+              any,
+              RefreshIndicatorMode.refresh,
+              60.0,
+              100.0, // Default value.
+              60.0, // Default value.
+          ));
+
+          clearInteractions(mockHelper);
```
Comment (xster) [inline packages/flutter/test/cupertino/refresh_test.dart]: This is typically a bit of code smell. What was the error otherwise?

File: packages/flutter/test/cupertino/refresh_test.dart [hunk 3]
```diff
@@ -373,6 +374,76 @@ void main() {
...
+          // Stays in that state forever until future completes with error.
+          await tester.pump(const Duration(seconds: 1000));
+          verifyNoMoreInteractions(mockHelper);
```
Comment (xster) [inline packages/flutter/test/cupertino/refresh_test.dart]: Ah I see. How many unverified things were there left against the mock? It's more idiomatic to just verify them all if there aren't too many

**Review by xster — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/refresh_test.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/refresh_test.dart]: I basically just copied the one test before this and modified a bit. The removed `verify`s are already tested in that test and I felt they were just noises.
