### PR TITLE
give `throwsToolExit` a more useful description

### LINKED ISSUE #136698: the description of the `throwsToolExit` matcher is vague
See title. If you run a test that has a failing `throwsToolExit` matcher, you may see output similar to this:

```
Expected: throws (<Instance of 'ToolExit'> and satisfies function)
  Actual: <Instance of 'Future<void>'>
   Which: threw ToolExit:<Exception: Error parsing assemble command: your generated configuration may be out of date. Try re-running 'flutter build ios' or the appropriate build command.>
          stack package:flutter_tools/src/base/common.dart 10:3                     throwToolExit
                package:flutter_tools/src/commands/assemble.dart 294:7              AssembleCommand.runCommand
...
```

While there is no useful information about the mismatch, this is generally still sufficient--there are only two fields `throwsToolExit` can match on.

However, where this can be confusing when writing tests that involve multiple `throwsToolExit` matchers, because it isn't necessarily easy to figure out in which the mismatch occurred, especially if the stack traces are long enough to get truncated. This is a situation that should ideally be rare, but I've encountered a couple of times now.

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes https://github.com/flutter/flutter/issues/136698.

Alters how `throwToolExit` creates its matcher. This results is an improved description of the matcher.

The mismatch description isn't improved by this, but I writing an entirely custom matcher to fix this isn't ideal either. We can instead mitigate the issue by augmenting the `toString` implementation of `ToolExit` to include the exit code, if it is non-null.

With these changes, the first few lines of output from a test would look like this:

```
Expected: throws <Instance of 'ToolExit'> with `exitCode`: <42> and `message`: contains 'message'
  Actual: <Closure: () => Never>
   Which: threw ToolExit:<Exit code: 41232. Error: message>
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/common.dart [hunk 1]
```diff
@@ -21,5 +21,12 @@ class ToolExit implements Exception {
   final int? exitCode;
 
   @override
-  String toString() => 'Exception: $message'; // TODO(ianh): Really this should say "Error".
+  String toString() {
+    final List<String> parts = <String>[
+      if (exitCode != null) 'Exit code: $exitCode',
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/common.dart:26]: Is this really helpful to the user?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/common.dart:26]: My concern is more that it's a little messier to have: `Exit code: 1. Error: ...`

**Review by christopherfujino — APPROVED** [review]
question about including the exit code, but otherwise LGTM

File: packages/flutter_tools/lib/src/base/common.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/base/common.dart]: Yeah, you ask a fair question. We already print the exit code later in the typical tool exit workflow, so this could result in redundant noise for end-users. It would be nice if we could include it in the matcher's mismatch output; but, as far as I can tell, this would involve writing a bunch of custom matcher code, which I don't want to do. Maybe I will the next time I have troubles with `throwsToolExit` :)

I've reverted this part of the change (I did keep the `"Exception"` to `"Error"` change)
