### PR TITLE
Calculate the system overlay style based on the AppBar background color

### LINKED ISSUE #72562: Status bar text color is wrong after update to 1.26.0-1.0.pre
After updating to the latest `dev` channel preview (https://github.com/flutter/flutter/compare/1.25.0-4.0.pre...1.26.0-1.0.pre) the automatic calculation of the status bar text color seems to be wrong. Previously it was correct (white), now it's black. Tested on Android 10 (API level 29) emulator and One Plus 5T.

## Steps to Reproduce

1. Create a new Flutter example app
2. Change the primary swatch to `primarySwatch: Colors.deepPurple`

**Expected results:** 
The app bar text and icons should be white.

**Actual results:**
The app bar text and icons are black.

<details>
  <summary>Logs</summary>

```
No error messages
```

```
Analyzing flutter_app...
No issues found! (ran in 1.8s)

```

```
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale de-DE)
    • Flutter version 1.26.0-1.0.pre at D:\Code\Flutter\flutter
    • Framework revision 63062a6443 (4 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Code\Android\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Code\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Users\boehr\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\203.5981.155
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.5981.152

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\boehr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.685]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 87.0.664.60

```

</details>

Screenshot_1608245892

### PR DESCRIPTION
**Pull request by miDeb**
[As documented](https://github.com/flutter/flutter/blob/25134a16d128ed22dc0ad8d41d2b931fcad3b014/packages/flutter/lib/src/material/app_bar.dart#L662), the system overlay currently defaults to light for dark themes and dark for light themes. However, the app bar can also be dark in a light theme, which would require a light overlay. This patch reverts the old behavior (before #71184) if `backwardsCompatibility` is set to `true` (using `ThemeData.primaryColorBrightness`) and uses  `ThemeData.estimateBrightnessForColor` to calculate a default overlay style if `backwardsCompatibility` is set to `false`.

Making this change revealed that some tests incorrectly expected that the default theme requires a dark overlay, but as can be seen [here](https://flutter.github.io/assets-for-api-docs/assets/material/Colors.blue.png), the default blue is already considered dark and requires a light overlay.

[Another test](https://github.com/flutter/flutter/blob/25134a16d128ed22dc0ad8d41d2b931fcad3b014/packages/flutter/test/material/app_bar_test.dart#L1907) used `ThemeData.primaryColor`, but the new implementation uses `ThemeData.colorScheme.primaryColor` instead. I changed that one to specify `ThemeData.primarySwatch`, so that `colorScheme.primaryColor` [is set](https://github.com/flutter/flutter/blob/9b2d32b605630f28625709ebd9d78ab3016b2bf6/packages/flutter/lib/src/material/theme_data.dart#L314).

Fixes #72562.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by miDeb** [comment]
@HansMuller may I ask you for a review?

**Comment by HansMuller** [comment]
@miDeb - I'm afraid I missed this when when you [commented a few weeks ago](https://github.com/flutter/flutter/pull/75091#issuecomment-778026991) will take a look shortly.

**Comment by miDeb** [comment]
@HansMuller friendly ping - could you take a look if you have time?

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -659,9 +659,8 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
   /// {@template flutter.material.appbar.systemOverlayStyle}
   /// Specifies the style to use for the system overlays that overlap the AppBar.
   ///
-  /// If this property is null, then [SystemUiOverlayStyle.light] is used if the
-  /// overall theme is dark, [SystemUiOverlayStyle.dark] otherwise. Theme brightness
-  /// is defined by [ColorScheme.brightness] for [ThemeData.colorScheme].
+  /// If this property is null, then the appropriate [SystemUiOverlayStyle] is
+  /// calculated based on the [backgroundColor].
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/app_bar.dart:663]: I suppose it's OK to just say "appropriate" here, since covering the two cases for backwards compatibility would make reading the doc tedious.

**Review by HansMuller — APPROVED** [review]
This looks like a reasonable change, although you'll need to sync the PR up.

Sorry about taking so look to get a review underway.

File: packages/flutter/lib/src/material/app_bar.dart (hunk 1 above)
Comment (miDeb) [reply packages/flutter/lib/src/material/app_bar.dart:663]: I'm not sure if I understood you correctly here, but `systemOverlayStyle` is only used for `backwardsCompatibility` disabled. Since `backwardsCompatibility` is currently still enabled by default I think it makes sense to add that to the doc. Let me know if this is better now.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 2]
```diff
@@ -659,9 +659,11 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
   /// {@template flutter.material.appbar.systemOverlayStyle}
   /// Specifies the style to use for the system overlays that overlap the AppBar.
   ///
-  /// If this property is null, then [SystemUiOverlayStyle.light] is used if the
-  /// overall theme is dark, [SystemUiOverlayStyle.dark] otherwise. Theme brightness
-  /// is defined by [ColorScheme.brightness] for [ThemeData.colorScheme].
+  /// This property is only used if [backwardsCompatibility] is set to false.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/app_bar.dart:662]: Good!

**Comment by HansMuller** [comment]
@miDeb Can you sync with the current master, merge, and push?

File: packages/flutter/lib/src/material/app_bar.dart [hunk 3]
```diff
@@ -197,13 +199,14 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
     this.titleTextStyle,
     this.systemOverlayStyle,
-  }) : assert(automaticallyImplyLeading != null),
-       assert(elevation == null || elevation >= 0.0),
-       assert(primary != null),
-       assert(toolbarOpacity != null),
-       assert(bottomOpacity != null),
-       preferredSize = Size.fromHeight(toolbarHeight ?? kToolbarHeight + (bottom?.preferredSize.height ?? 0.0)),
-       super(key: key);
+  })  : assert(automaticallyImplyLeading != null),
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/app_bar.dart:202]: It looks like a bunch of unnecessary reformatting happened (dartfmt?); need to revert that.

Comment (miDeb) [reply packages/flutter/lib/src/material/app_bar.dart]: Should be fixed now. This accidentally happened while I was resolving conflicts.

Comment (HansMuller) [reply packages/flutter/lib/src/material/app_bar.dart]: Looks good although GitHub thinks that you need to resolve merge conflicts in app_bart.dart

Comment (miDeb) [reply packages/flutter/lib/src/material/app_bar.dart]: Presumably caused by https://github.com/flutter/flutter/pull/80380, will fix

Comment (HansMuller) [reply packages/flutter/lib/src/material/app_bar.dart]: Thanks! Will land this when the build tree is green again.
