### PR TITLE
[web] Changes to web keyboard selection shortcuts for more consistent behavior

### LINKED ISSUE #107707: [Web]: TextField does not scroll with keyboard when SHIFT is pressed
## Steps to Reproduce

1. Create a `TextField` with content taller than its height.
2. Click the last visible line of text.
3. Hold SHIFT key.
4. Press DOWN to select to the line below.

**Expected results:** TextField scrolls down so the newly selected line is visible, and the cursor is visible.

**Actual results:** TextField does not scroll, and the cursor is below the visible TextField area.

DartPad: https://dartpad.dev/9f4981238069b6c927b328e096cc97d1

https://user-images.githubusercontent.com/44893228/179183584-cd5ea85b-464c-4c33-8fcb-431a31424c1d.mp4

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final controller = TextEditingController(text: '1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n');

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          color: Colors.grey,
          child: TextField(
            controller: controller,
            maxLines: 8,
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on Ubuntu 20.04.4 LTS 5.14.0-1045-oem, locale en_US.UTF-8)
    • Flutter version 3.0.4 at /home/alexey/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (2 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/alexey/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/alexey/bin/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.14.0-1045-oem
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by htoor3**
Currently there's an issue in which keyboard shortcuts (shift + arrow keys) don't autoscroll on web inputs and textfields if the selection is out of view (reference issue below).  Allowing the framework to handle selection leads to the expected behavior. 

Part 2 fixes https://github.com/flutter/flutter/issues/107707

Engine changes PR: https://github.com/flutter/engine/pull/37097

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 1]
```diff
@@ -2201,4 +2207,199 @@ void main() {
     }, variant: appleOnly);
 
   }, skip: !kIsWeb);// [intended] specific tests target web.
+
+  group('Web does accept', () {
+    const TargetPlatformVariant allDesktopExceptMacOS = TargetPlatformVariant(
+        <TargetPlatform>{TargetPlatform.linux, TargetPlatform.windows});
+    final TargetPlatformVariant macOSOnly =
+        TargetPlatformVariant.only(TargetPlatform.macOS);
```
Comment (mdebbar) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2215]: Once you combine mac and non-mac groups, you can use this instead:
```dart
variant: TargetPlatformVariant.desktop()
```

**Review by mdebbar — COMMENTED** [review]
I would love to get @chunhtai and @justinmc's opinions here.

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 2]
```diff
@@ -2052,6 +2055,9 @@ void main() {
       await tester.pumpWidget(buildEditableText());
 
       for (final SingleActivator activator in allModifierVariants(LogicalKeyboardKey.arrowDown)) {
+        if (activator.shift) {
+          continue;
+        }
```
[the remark this answers is not in the document]
Comment (htoor3) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2060]: This test loops through a variety of common shortcut activators (shift, alt, meta, etc). I added this line to skip if the current iteration activator is shift, since we're now handling shift + arrow differently

[the remark this answers is not in the document]
Comment (mdebbar) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2060]: Ah ok, this is inside the `Web does not accept` group. That makes sense.

Could you please put this explanation in a comment?

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 3]
```diff
@@ -2201,4 +2207,199 @@ void main() {
...
   }, skip: !kIsWeb);// [intended] specific tests target web.
+
+  group('Web does accept', () {
+    const TargetPlatformVariant allDesktopExceptMacOS = TargetPlatformVariant(
+        <TargetPlatform>{TargetPlatform.linux, TargetPlatform.windows});
+    final TargetPlatformVariant macOSOnly =
+        TargetPlatformVariant.only(TargetPlatform.macOS);
+
+    group('macOS', () {
+      const SingleActivator selectUpstream =
```
[the remark this answers is not in the document]
Comment (htoor3) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart]: Yeah good point, I changed this to `selectUp`/`selectUpAll` as well as the selectDown variants.  Does that work?

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 4]
```diff
@@ -2201,4 +2208,106 @@ void main() {
     }, variant: appleOnly);
 
   }, skip: !kIsWeb);// [intended] specific tests target web.
+
+  group('Web does accept', () {
+    group('desktop platforms', () {
```
Comment (htoor3) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2213]: Does this nesting make sense @mdebbar?
```
-Web does accept
-- desktop platforms
--- select up
--- select down

... etc
```

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 5]
```diff
@@ -402,22 +402,16 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     SingleActivator(LogicalKeyboardKey.arrowLeft, alt: true): DoNothingAndStopPropagationTextIntent(),
     SingleActivator(LogicalKeyboardKey.arrowRight, alt: true): DoNothingAndStopPropagationTextIntent(),
     SingleActivator(LogicalKeyboardKey.arrowUp, alt: true): DoNothingAndStopPropagationTextIntent(),
-    SingleActivator(LogicalKeyboardKey.arrowDown, shift: true, alt: true): DoNothingAndStopPropagationTextIntent(),
```
[the remark this answers is not in the document]
Comment (htoor3) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:405]: I believe you're correct, it does look like this would affect the `_macDisablingTextShortcuts` so we probably want to preserve behavior for `alt + shift + up/down`

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart (hunk 4 above)
Comment (mdebbar) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2213]: Is there a need for having the 2nd group (`desktop platforms`)?

Why not:
```
- Web does accept
-- select up
-- select down
... etc
```

**Comment by mdebbar** [comment]
@chunhtai yes, from the testing @htoor3 and I did, the framework was able to handle these shortcuts well.

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 6]
```diff
@@ -2201,4 +2208,106 @@ void main() {
...
+      const SingleActivator selectUp =
+          SingleActivator(LogicalKeyboardKey.arrowUp, shift: true);
+
+      const SingleActivator selectDown =
+          SingleActivator(LogicalKeyboardKey.arrowDown, shift: true);
```
Comment (mdebbar) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2218]: To be consistent with `selectAllUp`/`selectAllDown`, let's move these inside their respective test.

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 7]
```diff
@@ -2201,4 +2208,106 @@ void main() {
...
+
+        expect(controller.text, testVerticalText);
+        expect(
+          controller.selection,
+          const TextSelection(
+              baseOffset: 5,
+              extentOffset: 3), // selection extends upwards from 5
+          reason: selectUp.toString(),
+        );
+      }, variant: TargetPlatformVariant.desktop());
```
Comment (mdebbar) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2238]: I believe it's possible to set the `variant` on the group so you don't have to do it for each test.

**Review by mdebbar — COMMENTED** [review]
LGTM if LGT @chunhtai. I only have a few minor comments/suggestions.

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart (hunk 7 above)
Comment (htoor3) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2238]: Apparently `variant` is only a param on `testWidgets` helper :(

It looks like you can only skip `group` tests

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 8]
```diff
@@ -2052,6 +2055,10 @@ void main() {
       await tester.pumpWidget(buildEditableText());
 
       for (final SingleActivator activator in allModifierVariants(LogicalKeyboardKey.arrowDown)) {
+        // skip when activator uses a shift shortcut since web accepts that case
```
Comment (chunhtai) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2058]:
```suggestion
        // skip for the shift shortcut since web accepts it
```

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart (hunk 4 above)
Comment (htoor3) [reply packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2213]: Yeah probably not - I initially had the groups split up by MacOS and non-macOS because that's how the existing "Web does not accept" tests were setup.  But given that it greatly simplifies the code to just use the ternary operators you suggested, I can just remove the need for that group entirely

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 9]
```diff
@@ -2052,6 +2055,10 @@ void main() {
       await tester.pumpWidget(buildEditableText());
 
       for (final SingleActivator activator in allModifierVariants(LogicalKeyboardKey.arrowDown)) {
+        // skip for the shift shortcut since web accepts it
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2058]: Nit: Capital letter at the start and period at the end.

**Review by justinmc — APPROVED** [review]
LGTM 👍
