### PR TITLE
Hook up soft keyboard "next" and "previous" buttons so that they move the focus by default

### LINKED ISSUE #63575: TextInputAction.next does not move to the next input field, when pressing next(right-facing arrow button) on Android keyboard
## Steps to Reproduce

1. Run `flutter create input_action_issue`.
2. 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextInputAction Issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'TextInputAction Issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  String email = '';
  String password = '';
  String error = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Container(
        padding: const EdgeInsets.symmetric(horizontal: 50.0, vertical: 0.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: <Widget>[
              const SizedBox(
                height: 20.0,
              ),
              TextFormField(
                validator: (String val) => val.isEmpty ? 'Enter an Email' : null,
                decoration: const InputDecoration(
                  hintText: 'Email',
                ),
                keyboardType: TextInputType.emailAddress,
                textInputAction: TextInputAction.next,
                onChanged: (String val) {
                  setState(() {
                    email = val;
                  });
                },
              ),
              const SizedBox(
                height: 20.0,
              ),
              TextFormField(
                validator: (String val) =>
                    val.length < 6 ? 'Enter a password 6+ char long' : null,
                obscureText: true,
                decoration: const InputDecoration(hintText: 'Password'),
                textInputAction: TextInputAction.done,
                onChanged: (String val) {
                  setState(() {
                    password = val;
                  });
                },
              ),
              const SizedBox(
                height: 20.0,
              ),
              RaisedButton(
                onPressed: () {
                  if (_formKey.currentState.validate()) {
                    print('Email: $email, password: $password');
                    _formKey.currentState.reset();
                  }
                },
                color: Colors.pink[400],
                child: const Text(
                  'Sign in',
                  style: TextStyle(color: Colors.white),
                ),
              ),
              const SizedBox(
                height: 20.0,
              ),
              Text(
                error,
                style: const TextStyle(color: Colors.red, fontSize: 14.0),
              )
            ],
          ),
        ),
      ),
      backgroundColor: Colors.pink[100],
    );
  }
}
```
3. click on email input field , then click on next(right-facing arrow button) button on keyboard in Android device.

**Expected results:** 

when user press next () button on android keyboard while focus is in  current input source and wants to move to the next one, it should change the focus to the next input field.

**Actual results:** 

Noting happens when i clicked the next button on android keyboard.

<details>
  <summary>Logs</summary>

```
[ +122 ms] executing: [/home/saumyakr1232/flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] d9637ed78468ee0e65af509fafb71f792de6d09a
[        ] executing: [/home/saumyakr1232/flutter/] git tag --points-at HEAD
[  +18 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [/home/saumyakr1232/flutter/] git describe --match *.*.*
--first-parent --long --tags
[  +34 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-7.0.pre-176-gd9637ed784
[  +14 ms] executing: [/home/saumyakr1232/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/saumyakr1232/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +59 ms] executing: [/home/saumyakr1232/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +69 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +20 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb devices -l
[  +53 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm
           model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:3
[  +18 ms] /home/saumyakr1232/Android/Sdk/platform-tools/adb -s emulator-5554 shell
getprop
[ +765 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +254 ms] Generating /home/storage/saumya/flutter
projects/input_action_issue/android/app/src/main/java/io/flutter/plugins/GeneratedPl
uginRegistrant.java
[  +40 ms] ro.hardware = ranchu
[  +30 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice
graphics
           artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +45 ms] Starting incremental build...
[   +2 ms] Initializing file store
[  +23 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +5 ms] Launching lib/main.dart on sdk gphone x86 arm in debug mode...
[   +7 ms] /home/saumyakr1232/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/saumyakr1232/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart
.snapshot --sdk-root
/home/saumyakr1232/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tools.OYLITJ/flutter_tool.SIFFFR/app.dill --packages
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-ini
tializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/cache.dill.track.dill
[  +16 ms] executing: /home/saumyakr1232/Android/Sdk/build-tools/30.0.1/aapt dump
xmltree /home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[  +95 ms] Exit code 0 from: /home/saumyakr1232/Android/Sdk/build-tools/30.0.1/aapt
dump xmltree /home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.example.input_action_issue" (Raw:
               "com.example.input_action_issue")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="input_action_issue" (Raw:
                 "input_action_issue")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication"
                 (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComp
                 onentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.input_action_issue.MainActi
                   vity" (Raw: "com.example.input_action_issue.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.NormalTh
                     eme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.SplashSc
                     reenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHER"
                       (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[ +471 ms] Exit code 0 from: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of kernel
           08-12 14:59:45.693 D/logd    (    0): logdr: UID=2000 GID=2000 PID=6777 n
           tail=1 logMask=99 pid=0 start=0ns timeout=0ns
[   +1 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[ +276 ms] Exit code 0 from: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of kernel
           08-12 14:59:46.267 D/logd    (    0): logdr: UID=2000 GID=2000 PID=6780 n
           tail=1 logMask=99 pid=0 start=0ns timeout=0ns
[  +32 ms] <- compile package:input_action_issue/main.dart
[  +24 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb version
[  +11 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as /home/saumyakr1232/Android/Sdk/platform-tools/adb
[   +4 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb start-server
[  +11 ms] Building APK
[  +33 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +7 ms] Using gradle from /home/storage/saumya/flutter
projects/input_action_issue/android/gradlew.
[   +1 ms] /home/storage/saumya/flutter projects/input_action_issue/android/gradlew
mode: 33277 rwxrwxr-x.
[ +277 ms] executing: /home/saumyakr1232/android-studio/jre/bin/java -version
[ +147 ms] Exit code 0 from: /home/saumyakr1232/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +5 ms] executing: [/home/storage/saumya/flutter
projects/input_action_issue/android/] /home/storage/saumya/flutter
projects/input_action_issue/android/gradlew -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=/home/storage/saumya/flutter
projects/input_action_issue/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2212 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +183 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +92 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +1 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +93 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[+4398 ms] > Task :app:packageDebug
[ +365 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 7s
[        ] 31 actionable tasks: 5 executed, 26 up-to-date
[ +334 ms] Running Gradle task 'assembleDebug'... (completed in 8.1s)
[ +368 ms] calculateSha: LocalDirectory: '/home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk'/app.apk
[  +98 ms] calculateSha: reading file took 95us
[ +540 ms] calculateSha: computing sha took 540us
[   +5 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +4 ms] executing: /home/saumyakr1232/Android/Sdk/build-tools/30.0.1/aapt dump
xmltree /home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[   +8 ms] Exit code 0 from: /home/saumyakr1232/Android/Sdk/build-tools/30.0.1/aapt
dump xmltree /home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.example.input_action_issue" (Raw:
               "com.example.input_action_issue")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="input_action_issue" (Raw:
                 "input_action_issue")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication"
                 (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A:
                 android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComp
                 onentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A:
                   android:name(0x01010003)="com.example.input_action_issue.MainActi
                   vity" (Raw: "com.example.input_action_issue.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.NormalTh
                     eme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A:
                     android:name(0x01010003)="io.flutter.embedding.android.SplashSc
                     reenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN"
                       (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A:
                       android:name(0x01010003)="android.intent.category.LAUNCHER"
                       (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw:
                   "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +3 ms] Stopping app 'app.apk' on sdk gphone x86 arm.
[   +1 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell am force-stop com.example.input_action_issue
[+5207 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell pm list packages com.example.input_action_issue
[+1261 ms] package:com.example.input_action_issue
[   +9 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell cat /data/local/tmp/sky.com.example.input_action_issue.sha1
[+1253 ms] 0346e607292389691d02e0b91f4a53ed1a296ec5
[   +2 ms] Installing APK.
[   +8 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb version
[  +20 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as /home/saumyakr1232/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb start-server
[  +22 ms] Installing build/app/outputs/flutter-apk/app.apk...
[   +1 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 install -t -r /home/storage/saumya/flutter
projects/input_action_issue/build/app/outputs/flutter-apk/app.apk
[+24094 ms] Performing Streamed Install
                     Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 24.1s)
[+1183 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell echo -n ef163cc7d301fa66dd8f90265c4065938574e3f6 >
/data/local/tmp/sky.com.example.input_action_issue.sha1
[+4896 ms] sdk gphone x86 arm startApp
[   +8 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true
com.example.input_action_issue/com.example.input_action_issue.MainActivity
[+1443 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.example.input_action_issue/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+16623 ms] Observatory URL on device: http://127.0.0.1:40043/UfT4pMedbwA=/
[   +5 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 forward tcp:0 tcp:40043
[  +21 ms] 34655
[   +1 ms] Forwarded host port 34655 to device port 40043 for Observatory
[  +51 ms] Caching compiled dill
[ +776 ms] Connecting to service protocol: http://127.0.0.1:34655/UfT4pMedbwA=/
[   +5 ms] DDS is currently disabled due to
https://github.com/flutter/flutter/issues/62507
[+9678 ms] Successfully connected to service protocol:
http://127.0.0.1:34655/UfT4pMedbwA=/
[        ] Waiting for sdk gphone x86 arm to report its views...
[  +50 ms] Waiting for sdk gphone x86 arm to report its views... (completed in 38ms)
[ +142 ms] DevFS: Creating new filesystem on the device (null)
[ +376 ms] D/HostConnection( 6921): HostComposition ext
ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3
ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem
ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2
ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object
GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
[  +23 ms] D/EGL_emulation( 6921): eglMakeCurrent: 0xee7e3320: ver 2 0 (tinfo
0xeeb386d0) (first time)
[ +216 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.input_action_issue/code_cache/input_action_issueCZU
PCE/input_action_issue/)
[   +8 ms] Updating assets
[ +904 ms] Syncing files to device sdk gphone x86 arm...
[   +2 ms] Scanning asset files
[  +17 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:input_action_issue/main.dart
90e7abe0-4d5e-4f0c-8a9b-f69b58ac033a
[        ] <- 90e7abe0-4d5e-4f0c-8a9b-f69b58ac033a
[ +850 ms] Updating files
[+1323 ms] DevFS: Sync finished
[        ] Syncing files to device sdk gphone x86 arm... (completed in 2,197ms,
longer than expected)
[   +1 ms] Synced 1.6MB.
[        ] <- accept
[   +7 ms] Connected to _flutterView/0xe83865a0.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on sdk gphone x86 arm is available
at:
           http://127.0.0.1:34655/UfT4pMedbwA=/
[ +494 ms] I/Choreographer( 6921): Skipped 907 frames!  The application may be doing
too much work on its main thread.
[+19874 ms] W/IInputConnectionWrapper( 6921): getTextBeforeCursor on inactive
InputConnection
[  +13 ms] W/IInputConnectionWrapper( 6921): getSelectedText on inactive
InputConnection
[   +8 ms] W/IInputConnectionWrapper( 6921): getTextAfterCursor on inactive
InputConnection
[ +268 ms] W/IInputConnectionWrapper( 6921): beginBatchEdit on inactive
InputConnection
[   +8 ms] W/IInputConnectionWrapper( 6921): endBatchEdit on inactive
InputConnection
[+9080 ms] W/IInputConnectionWrapper( 6921): getTextBeforeCursor on inactive
InputConnection
[        ] W/IInputConnectionWrapper( 6921): getSelectedText on inactive
InputConnection
[        ] W/IInputConnectionWrapper( 6921): getTextAfterCursor on inactive
InputConnection
[ +873 ms] I/ut_action_issu( 6921): Background young concurrent copying GC freed
8847(473KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 1965KB/3769KB, paused
1.297ms total 906.655ms
[+7323 ms] W/IInputConnectionWrapper( 6921): getTextBeforeCursor on inactive
InputConnection
[   +2 ms] W/IInputConnectionWrapper( 6921): getSelectedText on inactive
InputConnection
[   +2 ms] W/IInputConnectionWrapper( 6921): getTextAfterCursor on inactive
InputConnection
[+2456 ms] I/flutter ( 6921): Email: saumya, password: 2343423434
[+16480 ms] Application finished.
[   +2 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 forward --list
[   +7 ms] Exit code 0 from: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 forward --list
[        ] emulator-5554 tcp:35285 tcp:39161
           emulator-5554 tcp:34655 tcp:40043
[   +1 ms] executing: /home/saumyakr1232/Android/Sdk/platform-tools/adb -s
emulator-5554 forward --remove tcp:35285
```

```
Analyzing input_action_issue...                                         
No issues found! (ran in 3.9s)
```

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.176, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-8.0.pre.176 at /home/saumyakr1232/flutter
    • Framework revision d9637ed784 (11 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/saumyakr1232/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/saumyakr1232/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/saumyakr1232/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

Focus will be moved automatically if `onEditingComplete` is not specified, but must
by moved manually if `onEditingComplete` is specified.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/63575

## Tests

- Added tests to make sure that the focus moves, and removed a test that verified that the focus was not lost.

## Breaking Change

- [X] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -1362,8 +1371,51 @@ void main() {
...
+    final Finder textFinder = find.byType(EditableText);
+    await tester.tap(textFinder);
+    await tester.pump();
+
+    assert(focusNode.hasFocus);
+
+    await tester.testTextInput.receiveAction(TextInputAction.previous);
+    await tester.pump();
+
+    // Next node has focus after pressing 'next' button.
```
Comment (HansMuller) [inline packages/flutter/test/widgets/editable_text_test.dart:1415]: Previous node has ... 'previous' button

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -1362,8 +1371,51 @@ void main() {
...
 
-    // Still has focus after pressing "next".
-    expect(focusNode.hasFocus, true);
+    // Next node has focus after pressing 'next' button.
+    expect(focusNode.hasFocus, isFalse);
+    expect(Focus.of(previousKey.currentContext).hasFocus, isFalse);
+    expect(Focus.of(nextKey.currentContext).hasFocus, isTrue);
+  });
+
+  testWidgets('Moves focus to the previous field by default when "previous" action is pressed', (WidgetTester tester) async {
```
Comment (HansMuller) [inline packages/flutter/test/widgets/editable_text_test.dart:1380]: In theory, you could do all of this checking in just one slightly more complicated version of this test.

**Review by HansMuller — APPROVED** [review]
There are many more TextInputActions that have focus implications. Shouldn't we be checking all of them?

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart:1380]: Well, sure, but doesn't that violate the principle of "one behavior => one test"?

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart:1415]: Thanks, fixed.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart]: OK, I modified the tests to test all of the behaviors in separate tests (so they fail separately), but using a new `TestVariant` subclass so that I don't duplicate code when doing so. Let me know what you think.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 3]
```diff
@@ -1336,35 +1336,91 @@ void main() {
     expect(changedValue, clipboardContent);
   });
 
-  testWidgets('Does not lose focus by default when "next" action is pressed', (WidgetTester tester) async {
-    final FocusNode focusNode = FocusNode();
+  // The variants to test in the next test.
+  final ValueVariant<TextInputAction> focusVariants = ValueVariant<TextInputAction>(
+    TextInputAction.values.toSet(),
```
Comment (HansMuller) [inline packages/flutter/test/widgets/editable_text_test.dart:1341]: NICE

**Review by HansMuller — APPROVED** [review]
The test updates LGTM

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 4]
```diff
@@ -1336,35 +1336,91 @@ void main() {
...
-        selectionControls: materialTextSelectionControls,
-        keyboardType: TextInputType.text,
-      ),
-    );
-    await tester.pumpWidget(widget);
+  testWidgets('Handles focus correctly when action is invoked',
+      (WidgetTester tester) async {
+    // The expectations for each of the types of TextInputAction.
+    const Map<TextInputAction, bool> actionShouldLoseFocus =
+    <TextInputAction, bool>{
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:1348]: I feel like this is an analyzer error if it's not indented, but if I'm wrong then no worries.

**Review by justinmc — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 4 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart]: No, it won't fail the analyzer, but it does need to be indented for readabililty. Done.
