### PR TITLE
[Material] Update TabController to support dynamic Tabs

### LINKED ISSUE #15008: When there is only one tab, it's not shown selected
When you have a TabBar with only one Tab, it renders with the indicator in position, but the color is shaded instead of white.

cc @HansMuller

### LINKED ISSUE #18686: Hot reload doesn't recognize change in length in DefaultTabController
When updating the DefaultTabController from the [tutorial](https://flutter.io/cookbook/design/tabs/) to a length of 4 instead of 3 and reloading, Flutter doesn't recognize that the length value has changed. 
This is the code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new HeadacheApp());

class HeadacheApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 4,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
                Tab(icon: Icon(Icons.help)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
              Icon(Icons.help),
            ],
          ),
        ),
      ),
    );
  }
}
```

It gives the following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 112 pos 12: 'value >= 0
flutter: && (value < length || length == 0)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart)
flutter: #3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:164:5)
flutter: #4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:864:17)
flutter: #5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:939:21)
flutter: #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
flutter: #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
flutter: #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
flutter: #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #19     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#8e887(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
flutter:   Offset(329.3, 132.7), sent tap down)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I went into `flutter/src/material/tab_controller.dart` and printed the values of `length` and `value` which were both 3 instead of 3 and 4, which caused the exception to be raised. I was able to fix this by restarting the iPhone simulator and re-uploading the app.

### LINKED ISSUE #20292: DefaultTabController not working with dynamic data
## Steps to Reproduce

1. Add `DefaultTabController` widget 
2. add `length` to a dynamic property lets say `tabCount` from view model (_vm)
3. Load data asynchronously and based on that data generate `TabBarView` and `TabNames`
4. Click on tabs ( Error is thrown) also default active tab is set to index 1
5. If `tabCount` is set to a fixed value and `tabNames` are static values lets say `4` or `3` and `["A", "B"]` it works

## Code

  ```dart
@override
  Widget build(BuildContext context) {
    return new StoreConnector<AppState, _ViewModel>(
      onInit: (Store<AppState> store) => store.dispatch(initSportData(context)),
      converter: _ViewModel.fromStore,
      builder: (BuildContext context, _ViewModel vm) {
        return new DefaultTabController(
            length: vm.tabCount,  // <-------------------------------------------Here
            child: Scaffold(
              appBar: PreferredSize(
                  preferredSize: Size.fromHeight(96.0),
                  child: getAppBar(context, vm.tabNames)), // <--------------------------------------Here
              body: new Container(
                  decoration: new BoxDecoration(
                      image: new DecorationImage(
                    alignment: Alignment.topLeft,
                    image: new AssetImage('images/main-bg.png'),
                    fit: BoxFit.cover,
                  )),
                  child: vm.isLoading
                      ? new Center(
                          child: new CircularProgressIndicator(),
                        )
                      : TabBarView(
                          children: getTabBarView(vm.tabDetails), //<------------------------------Here
                        )),
            ));
      },
    );
  }

```
## Logs

```
 ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7806): The following assertion was thrown while handling a gesture:
I/flutter ( 7806): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 110 pos 12: 'value >= 0
I/flutter ( 7806): && (value < length || length == 0)': is not true.
I/flutter ( 7806): 
I/flutter ( 7806): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7806): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7806): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7806):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7806): 
I/flutter ( 7806): When the exception was thrown, this was the stack:
I/flutter ( 7806): #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart)
I/flutter ( 7806): #3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:162:5)
I/flutter ( 7806): #4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:864:17)
I/flutter ( 7806): #5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:939:21)
I/flutter ( 7806): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter ( 7806): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter ( 7806): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 7806): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter ( 7806): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter ( 7806): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter ( 7806): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter ( 7806): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 7806): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 7806): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 7806): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 7806): #17     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 7806): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 7806): (elided 2 frames from class _AssertionError)
I/flutter ( 7806): 
I/flutter ( 7806): Handler: onTap
I/flutter ( 7806): Recognizer:
I/flutter ( 7806):   TapGestureRec
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.5.1 at /private/var/www/flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rajeev/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/rajeev/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 3 categories.
```

### LINKED ISSUE #28816: Changing the number of tabs in a DefaultTabController doesn't fix the tabController's index if it's now out of range
I have an app with a tab strip, and I remove some tabs, such that the "current" tab index is now beyond the last tab. The tabController doesn't update though.

### PR DESCRIPTION
**Pull request by johnsonmh**
## Description

Because `DefaultTabController` creates its `TabController` once (in `initState`), it is currently impossible to:
1. Modify the number of tabs you have after the first build.
1. Load tabs dynamically/asynchronous.
1. Update a `TabBar` and hot reload the changes.

This change adds an override to `didUpdateWidget` in `DefaultTabController`, it will detect updates to `DefaultTabController.length` and update the `DefaultTabController.controller accordingly`.

After the changes here, we can now do:
giphy

## Related Issues

* Fixes https://github.com/flutter/flutter/issues/20292
* Fixes https://github.com/flutter/flutter/issues/18686
* Fixes https://github.com/flutter/flutter/issues/28816
* Fixes https://github.com/flutter/flutter/issues/15008

## Tests

I added the following tests:

* Build a `TabBar` with three tabs, update it to have two tabs, then one tab, then two tabs again. App should never crash and `DefaultTabController` should be updated accordingly. 
* When there is only one tab in a `TabBar`, it renders with the proper color (regression test for https://github.com/flutter/flutter/issues/15008).

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). 
See: https://groups.google.com/forum/#!topic/flutter-announce/SfLv0x5zDQ0
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by HansMuller** [comment]
This looks like a good change: DefaultTabController.didUpdateWidget.didUpdateWidget definitely should DTRT when rebuilt with a new length.

I'd prefer to not make TabController.copyWith public. It introduces a problem with the lifetime the TabController's AnimationController, since TabController.dispose() will now apply to the original and all copies. Should be easy enough to deal with that in this one case, but I don't think we want to face the general problem (at least not yet).

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 1]
```diff
@@ -83,12 +83,38 @@ class TabController extends ChangeNotifier {
...
       );
 
+  // Private constructor used by `copyWith`. This allows a new TabController to
+  // be created without having to create a new animationController.
+  TabController._({
+    int index,
+    int previousIndex,
+    AnimationController animationController,
+    @required this.length,
+  }) : _index = index, _previousIndex = previousIndex, _animationController = animationController;
```
Comment (clocksmith) [inline packages/flutter/lib/src/material/tab_controller.dart]: Should these be on their own lines?

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 2]
```diff
@@ -83,12 +83,38 @@ class TabController extends ChangeNotifier {
...
       _index = initialIndex,
       _previousIndex = initialIndex,
-      _animationController = length < 2 ? null : AnimationController(
+      _animationController = AnimationController.unbounded(
         value: initialIndex.toDouble(),
-        upperBound: (length - 1).toDouble(),
         vsync: vsync,
       );
 
+  // Private constructor used by `copyWith`. This allows a new TabController to
```
Comment (rami-a) [inline packages/flutter/lib/src/material/tab_controller.dart]: Should be `_copyWith` right?

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/lib/src/material/tab_controller.dart]: Agree with this, move to multiple lines

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 3]
```diff
@@ -83,12 +83,38 @@ class TabController extends ChangeNotifier {
...
+  // be created without having to create a new animationController.
+  TabController._({
+    int index,
+    int previousIndex,
+    AnimationController animationController,
+    @required this.length,
+  }) : _index = index, _previousIndex = previousIndex, _animationController = animationController;
+
+
+  /// Creates a new [TabController] with `index` and `length` if they are
```
Comment (rami-a) [inline packages/flutter/lib/src/material/tab_controller.dart]: Since this is now private, it should use // instead of ///

**Review by rami-a — APPROVED** [review]
LGTM, just small comments

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/tab_controller.dart]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-for-public-quality-private-documentation

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 2 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tab_controller.dart]: Done.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 1 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tab_controller.dart]: Done.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 3 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tab_controller.dart]: OK, I'm going to leave as `///` especially since I can imagine us one day making this method public.

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 4]
```diff
@@ -323,4 +350,18 @@ class _DefaultTabControllerState extends State<DefaultTabController> with Single
...
+
+  @override
+  void didUpdateWidget(DefaultTabController oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    if (oldWidget.length != widget.length) {
+      // If the length is shortened while the last tab is selected, we should
+      // automatically update the index of the controller to be the new last tab.
+      int newIndex;
+      if (_controller.index >= widget.length) {
+        newIndex = widget.length - 1;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tab_controller.dart]: widget.length can be 0, is it safe to create a controller with index  = -1? Might be safer to use max(0, widget.length - 1)

It looks like DefaultTabController's constructor isn't checking its parameters. We should assert that length >=0; initialIndex >=0 && initialIndex < length

File: packages/flutter/lib/src/material/tabs.dart [hunk 5]
```diff
@@ -960,6 +950,15 @@ class _TabBarState extends State<TabBar> {
   @override
   Widget build(BuildContext context) {
     assert(debugCheckHasMaterialLocalizations(context));
+    assert(() {
+      if (_controller.length != widget.tabs.length) {
+        throw FlutterError(
+          'Controller\'s length property (${_controller.length}) does not match the \n'
+          'number of tab elements (${widget.tabs.length}) present in TabBar\'s tabs property.'
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: number of tabs (...) in the TabBar\'s tabs property

**Review by HansMuller — APPROVED** [review]
Looks good with a few cleanup suggestions.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 4 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tab_controller.dart]: Done, added `max(0, widget.length - 1)` here and `assert(length >= 0),
       assert(initialIndex >= 0 && initialIndex < length)` to `DefaultTabController`.

File: packages/flutter/lib/src/material/tabs.dart (hunk 5 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tabs.dart]: Done.

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 6]
```diff
@@ -2,6 +2,8 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+import 'dart:math';
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tab_controller.dart]: This is usually imported "as math"; used with the prefix like `math.max`
```
import 'dart:math' as math;
```

**Review by HansMuller — APPROVED** [review]
LGTM with one small change.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 6 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/tab_controller.dart]: Done.

**Comment by JamalBelilet** [comment]
Can you please merge this to the `dev` branch.

**Comment by wzieba** [comment]
Thanks @johnsonmh for your work on this!

Can we know ETA for releasing this?

**Comment by fellow7000** [comment]
This will be great to have it in the very nearest future, stuck with this problem today :-/

**Comment by johnsonmh** [comment]
Hi all! Glad this work is helpful to people. 

This PR was merged sucessfully into `master` about a month ago. It is now following the regular [release process](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels). Since it's been about a month, it should be on the `beta` channel soon. And, keep in mind, you can start using this feature immediately by switching to the `master` channel.

**Comment by fellow7000** [comment]
@johnsonmh Hi! Thanks for prompt feedback! Just changed to Master but still have some issues. As I'm not really experienced in Flutter (but find it amazing), could you please tell us if we also need to update code somehow to make this change effective? 
Is there any link to your example from above?..

Thanks!

**Comment by johnsonmh** [comment]
@fellow7000 Sorry, I don't know how you would make this work with a regular `TabController`.

If all you need is the index of the currently selected tab, you could do that pretty easily with a `DefaultTabController` by adding a `int _selectedIndex` on your state object, and update it in the `TabBar.onTap` callback.

Something like:

```dart
int _selectedIndex = 0;

...

DefaultTabController(
  length: length,
  child: TabBar(
    tabs: _tabs,
    onTap: (i) => setState(() => _selectedIndex = i),
  ),
),
```
