### PR TITLE
[web] Fix JS crash when FF blocks service workers.

### LINKED ISSUE #103972: [Flutter 3] Web app fails to load in firefox if "Delete cookies and site data when Firefox is closed" is checked in settings
Hello, 

I have a web app deployed with Firebase.
It's work fine with almost all browsers. But with Firefox, it gave me this error: `Failed to load app from service worker`

Capture d’écran 2022-05-17 à 13 36 14

Firefox version: 100.0

Flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale fr-FR)
    • Flutter version 2.10.5 at /Users/appspanel/Documents/development/utils/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/appspanel/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64  • Android 10
      (API 29) (emulator)
    • iPhone 8 (mobile)                    • C0CAAD9F-196D-4329-9089-188F7A95FC53 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome
      101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

Thanks for your help

### PR DESCRIPTION
**Pull request by ditman**
When FF users enable the _"Delete cookies and site data when Firefox is closed"_ browser option, it has the side effect of **blocking service workers.** See [Bugzilla#1429714](https://bugzilla.mozilla.org/show_bug.cgi?id=1429714) ([and](https://bugzilla.mozilla.org/show_bug.cgi?id=1413615) [several](https://bugzilla.mozilla.org/show_bug.cgi?id=1552376) [others](https://bugzilla.mozilla.org/show_bug.cgi?id=1755167)).

When a Flutter app attempts to load in a browser configured like so, first the browser will log an error:

* **`Failed to register/update a ServiceWorker for scope 'https://domain': Storage access is restricted in this context due to user settings or private browsing mode.`**

And then **reject the `register` promise with a `DOMException: The operation is insecure.`** that goes unhandled into our `flutter.js` code.

The unhandled DOMException interrupts the JS bootstrap code, and the application stops loading, resulting in a white screen.

This PR handles this issue by `.catch`ing the rejected Promise from the service worker registration, then falling back to inject a script tag.

* Fixes https://github.com/flutter/flutter/issues/103972

### Testing

* Added an integration test to ensure that a Flutter Web app starts, even when the Service Workers are "blocked" (in the way that FF blocks them)
* Manually tested here with the actual browser: https://dit-bootstrap-tests.web.app

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/bots/service_worker_test.dart [hunk 1]
```diff
@@ -562,3 +568,89 @@ Future<void> runWebServiceWorkerTestWithCachingResources({
...
+    required String cacheControl,
+  }) async {
+    final int serverPort = await findAvailablePort();
+    final int browserDebugPort = await findAvailablePort();
+    server = await AppServer.start(
+      headless: headless,
+      cacheControl: cacheControl,
+      // TODO(yjbanov): use a better port disambiguation strategy than trying
+      //                to guess what ports other tests use.
+      appUrl: 'http://localhost:$serverPort/index.html',
```
Comment (mdebbar) [inline dev/bots/service_worker_test.dart:593]: I know this was copied from somewhere else, but I'm not sure what the comment means. I don't see any port guessing going on. We are just finding a "random" available port and using it.

File: dev/integration_tests/web/web/index_with_blocked_service_workers.html [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+  <link rel="manifest" href="manifest.json">
+
+  <script>
+    // This is to break the serviceWorker registration, and make it throw a DOMException!
+    // Test for issue https://github.com/flutter/flutter/issues/103972
+    window.navigator.serviceWorker.register = (url) => {
+      console.error('Failed to register/update a ServiceWorker for scope ', url,
+          ': Storage access is restricted in this context due to user settings or private browsing mode.');
+      return Promise.reject(new DOMException('The operation is insecure.'));
+    }
```
Comment (mdebbar) [inline dev/integration_tests/web/web/index_with_blocked_service_workers.html:24]: Haha I love JavaScript. PATCH THE PLATFORM!

File: packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart [hunk 3]
```diff
@@ -96,7 +97,7 @@ _flutter.loader = null;
     _waitForServiceWorkerActivation(serviceWorker, entrypointUrl) {
       if (!serviceWorker || serviceWorker.state == "activated") {
         if (!serviceWorker) {
-          console.warn("Cannot activate a null service worker. Falling back to plain <script> tag.");
+          console.warn("Cannot activate a null service worker.");
```
Comment (mdebbar) [inline packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart:100]: Not in scope for this PR, but is it possible to put this JS code in a separate `.js` file then read it from there? It would be significantly better to look at this code with proper syntax highlighting. The IDE would also be able to catch obvious syntax errors, etc.

**Review by mdebbar — APPROVED** [review]
LGTM!

**Comment by ditman** [comment]
Verified new test is running in CI:

* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811241288664232129/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_2_5/test_stdout

(search for `runWebServiceWorkerTestWithBlockedServiceWorkers `)

File: dev/integration_tests/web/web/index_with_blocked_service_workers.html (hunk 2 above)
Comment (ditman) [reply dev/integration_tests/web/web/index_with_blocked_service_workers.html:24]: I wonder what will happen first: the FF issue getting fixed, or Chromium stopping me from writing on the `register` function of the `ServiceWorkerContainer` object :P

File: dev/bots/service_worker_test.dart (hunk 1 above)
Comment (ditman) [reply dev/bots/service_worker_test.dart:593]: Yes, this was copied from a few lines above. I think @yjbanov wants a better way to determine an open port than picking a random number until you find one where the OS lets you start listening!

File: packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart (hunk 3 above)
Comment (ditman) [reply packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart:100]: (PS: Feel free to add into that issue, it's for brainstorming right now)

File: dev/integration_tests/web/web/index_with_blocked_service_workers.html [hunk 4]
```diff
@@ -0,0 +1,48 @@
+<!DOCTYPE HTML>
+<!-- Copyright 2014 The Flutter Authors. All rights reserved.
+Use of this source code is governed by a BSD-style license that can be
+found in the LICENSE file. -->
+<html>
+<head>
+  <meta charset="UTF-8">
+  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
+
+  <title>Web Test</title>
```
Comment (yjbanov) [inline dev/integration_tests/web/web/index_with_blocked_service_workers.html:10]: Might be useful for the page title to reflect what test this is.

File: dev/bots/service_worker_test.dart (hunk 1 above)
Comment (yjbanov) [reply dev/bots/service_worker_test.dart:593]: I have no idea what I wrote there :)

**Review by yjbanov — APPROVED** [review]
lgtm

File: dev/integration_tests/web/web/index_with_blocked_service_workers.html (hunk 4 above)
Comment (ditman) [reply dev/integration_tests/web/web/index_with_blocked_service_workers.html:10]: Yikes, I didn't see this. I'm going to create a bug to improve the integration_tests for web, they're growing quite a bit.
