### PR TITLE
[flutter.js] Wait for reg.update, then activate sw (if not active yet).

### LINKED ISSUE #101459: [web] ServiceWorker "installing" may be null right after calling "update()"
In certain (unknown) cases, a service worker registration object may return a `null` serviceworker in `installing` state, right after calling `update()` on the service worker registration object.

The below initialization code (shared by many flutter web apps) is affected:

* https://github.com/flutter/flutter/blob/b87caba9121c1b938aa989c283bcca7dbf1f4ff0/dev/integration_tests/web/web/index.html#L56-L62

(`reg.installing` is null, when it shouldn't.)

## Steps to Reproduce

@yjbanov managed to get his Chrome browser (v100, gLinux) in this state and immediately reported the issue, but I couldn't repro. The only way we've had to reproduce the issue was to eliminate forking in the code at this point, and force the code through that specific branch.

**Expected results:** An app running

**Actual results:** A variation of this error:

Screen Shot 2022-04-06 at 3 49 58 PM

### PR DESCRIPTION
**Pull request by ditman**
In this PR we handle the `update` case of Flutter Web service worker slightly better, by awaiting on the promise returned by it, instead of using the instance upon which update was called.

Once that's done, we fetch the service worker in the state in which it might be, and pass it to the method that waits for its activation (if needed!).

Fixes #101459

Tests: Added a test that goes through the code path that was failing, but I couldn't reproduce the failure :/

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/flutter_js.dart [hunk 1]
```diff
@@ -82,6 +84,10 @@ _flutter.loader = null;
 
     _waitForServiceWorkerActivation(serviceWorker, entrypointUrl) {
       if (!serviceWorker) return;
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/flutter_js.dart:86]: Is it ever safe to return here? That seems to guarantee a catastrophic result, since returning null results in a null engineInitializer.

File: packages/flutter_tools/lib/src/web/flutter_js.dart [hunk 2]
```diff
@@ -103,19 +109,23 @@ _flutter.loader = null;
...
             if (!reg.active && (reg.installing || reg.waiting)) {
               // No active web worker and we have installed or are installing
               // one for the first time. Simply wait for it to activate.
-              return this._waitForServiceWorkerActivation(reg.installing || reg.waiting, entrypointUrl);
+              let sw = reg.installing || reg.waiting;
+              return this._waitForServiceWorkerActivation(sw, entrypointUrl);
             } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
               // When the app updates the serviceWorkerVersion changes, so we
               // need to ask the service worker to update.
               console.log("New service worker available.");
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/flutter_js.dart:123]: While you are here, maybe switch all `console.log`s to `console.debug`?

File: packages/flutter_tools/lib/src/web/flutter_js.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/flutter_js.dart:86]: Maybe if we reach this case the safest thing to do is drop a plain `<script>` tag, same as the timeout fallback?

**Review by yjbanov — COMMENTED** [review]
Is there a way to test this?

File: packages/flutter_tools/lib/src/web/flutter_js.dart (hunk 1 above)
Comment (ditman) [reply packages/flutter_tools/lib/src/web/flutter_js.dart:86]: > Maybe if we reach this case the safest thing to do is drop a plain <script> tag, same as the timeout fallback?

Yes, that sounds like a better fallback, let's add it.

**Comment by yjbanov** [comment]
Oh, wait, I missed your comment:

> Tests: couldn't test this, because AFAIK we don't have the ability to swap a Flutter Web service worker on the fly in our testing environment :/

What causes the service worker to change to trigger this code path? This test is attempting to do something like that:

https://github.com/flutter/flutter/blob/master/dev/bots/service_worker_test.dart

File: packages/flutter_tools/lib/src/web/flutter_js.dart (hunk 2 above)
Comment (ditman) [reply packages/flutter_tools/lib/src/web/flutter_js.dart]: I used `console.info`, like a fool. But yes, I'm going to switch all of them to `debug`, except for the ones that are "warnings" just to spot anomalous behavior.

**Comment by ditman** [comment]
> What causes the service worker to change to trigger this code path? This test is attempting to do something like that:

I think what we need to do is to have:

* An app running with a given serviceWorkerVersion, so it registers that serviceWorker (v1)
* Rebuild the app with a different serviceWorkerVersion (v2)
* Refresh the app. That should trigger the "serviceWorkerVersion is different, I need to update the SW" branch of the code

(I think, not entirely sure)

File: packages/flutter_tools/lib/src/web/flutter_js.dart (hunk 1 above)
Comment (ditman) [reply packages/flutter_tools/lib/src/web/flutter_js.dart]: I slightly modified a second method to return null/a promise instead of being boolean, so we don't return "null" in one of the branches of the code.

**Comment by ditman** [comment]
I've added a new test to `service_worker_test.dart` that implements what I described above:

1. Load app v1
2. Reload app v1
3. Change app to v2
4. Load app v2

That *does* exercise the code path where the serviceworker IS updated, but it doesn't trigger the issue on my machine :S

Also expanded the service worker test to have 3 different initializations: without flutter js, with flutter js and all the steps, and with flutterJS "short" (calling autoStart directly).

File: dev/bots/service_worker_test.dart [hunk 3]
```diff
@@ -274,7 +362,10 @@ Future<void> runWebServiceWorkerTest({
     expect(reportedVersion, '4');
     reportedVersion = null;
   } finally {
+    File(path.join(_testAppWebDirectory, 'index.html')).deleteSync();
```
Comment (ditman) [inline dev/bots/service_worker_test.dart:365]: Restore the original index file, instead of deleting it here?

Comment (ditman) [reply dev/bots/service_worker_test.dart:365]: Definitely, this index.html is used by other tests later on.

**Review by yjbanov — APPROVED** [review]
lgtm
