### PR TITLE
Expose controller for PaginatedDataTable

### LINKED ISSUE #99547: PaginatedDataTable does not expose the scroll controller of the SingleChildScrollView that wraps its content
## Use case

Hi,

I want to override the scrolling functionality for a `PaginatedDataTable`. I'm using flutter web and currently it is not possible to scroll a table horizontally on desktop devices without a scroll pad. So I was trying to enable horizontal scrolling via the arrow left and arrow right keys using a `RawKeyboardListener` that tells my `ScrollController` to scroll. Unfortunately, one cannot simply wrap the `PaginatedDataTable` in a `SingleChildScrollView`, since it destroys the layout, giving the `PaginatedDataTable` an unbounded width it cannot handle, since it is trying to fill out the space it has available.

The following code throws an error:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox(
          width: 200,
          // A `PaginatedDataTable` cannot be wrapped by a
          // `SingleChildScrollView`, because it provides its child
          // with an unbounded width.
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: PaginatedDataTable(
              columns: <DataColumn>[
                DataColumn(
                  label: Text("1"),
                ),
                DataColumn(
                  label: Text("2"),
                ),
              ],
              source: CustomDataSource(),
            ),
          ),
        ),
      ),
    );
  }
}

class CustomDataSource extends DataTableSource {
  @override
  bool get isRowCountApproximate => false;

  @override
  int get rowCount => 1;

  @override
  int get selectedRowCount => 0;

  @override
  DataRow? getRow(int index) {
    return DataRow(

      cells: <DataCell>[
        DataCell(
          Text(
            "Some very long cell that is wider than 200 logical pixels, the size available to the table",
          ),
        ),
        DataCell(
          Text(
            "Same as the first cell, again some very long cell definetly forcing the table to be wider than 200 logical pixels",
          ),
        ),
      ],
    );
  }
}
```

The error:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite width.
The offending constraints were:
  BoxConstraints(w=Infinity, 0.0<=h<=Infinity)

The relevant error-causing widget was:
  PaginatedDataTable
  PaginatedDataTable:file:///home/masterusr/src/flutter_issues/pdt_horizontal_scrolling/lib/main.dart:21:20
```

## Proposal

The content of a `PaginatedDataTable` is wrapped in a `SingleChildScrollView` (see [here](https://github.com/flutter/flutter/blob/646c22085e52be308e1700650130f5d0940465fd/packages/flutter/lib/src/material/paginated_data_table.dart#L503)).
I propose to add a `ScrollController? scrollController` parameter to the `PaginatedDataTable` constructor that is then provided to the `SingleChildScrollView`. This should allow me and others to override the horizontal scrolling behavior of the contents of a `PaginatedDataTable`.

### PR DESCRIPTION
**Pull request by amanv8060**
Exposes controller for PaginatedDataTable

fixes #99547

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by amanv8060** [comment]
@Piinks I don't think that primary is required, or should I add it as well?
will add tests.
Thanks.

**Review by Piinks — COMMENTED** [review]
Hey @amanv8060! Thanks for the contribution.

I think adding `primary` as well here will be beneficial to the goal the issue is describing. It is the PrimaryScrollController (PSC) that the default keyboard shortcuts check to see if they can activate any scrolling actions, so both `controller` and `primary` sound like reasonable additions here. 

Fun fact, in #99547, the PSC does not kick in automatically because the PSC only automatically attaches to vertical scroll views. 😉 

Let me know if you need guidance for adding tests. Thanks!

**Comment by amanv8060** [comment]
Sure, will try to do it this weekend.

**Comment by amanv8060** [comment]
@Piinks I have added the tests for 
- if psc gets attached 
- if we can scroll the data table through controller

File: packages/flutter/test/material/paginated_data_table_test.dart [hunk 1]
```diff
@@ -1043,4 +1044,83 @@ void main() {
...
+              DataColumn(label: Text('Calories'), numeric: true),
+              DataColumn(label: Text('Generation')),
+            ],
+          ),
+        ),
+      )
+    );
+
+    // PaginatedDataTable has two Scrollable Widgets, First one is for DataTable
+    // while second one is meant for Footer.
```
Comment (amanv8060) [inline packages/flutter/test/material/paginated_data_table_test.dart:1117]: is this line required?

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 2]
```diff
@@ -106,6 +108,11 @@ class PaginatedDataTable extends StatefulWidget {
          return true;
        }()),
        assert(source != null),
+       assert(!(controller != null && (primary ?? false)),
+          'Primary ScrollViews obtain their ScrollController via inheritance from a PrimaryScrollController widget. '
+          'You cannot both set primary to true and pass an explicit controller.',
+       ),
+       primary = primary ?? controller == null,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:115]: Why does it default to being primary? This could cause issues if another scrollview is using the PrimaryScrollController.

File: packages/flutter/test/material/paginated_data_table_test.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/test/material/paginated_data_table_test.dart:1117]: What do you mean?

Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1117]: There are two scrollable in the PaginatedDataTable, so should this comment be there for explanation?

File: packages/flutter/lib/src/material/paginated_data_table.dart (hunk 2 above)
Comment (amanv8060) [reply packages/flutter/lib/src/material/paginated_data_table.dart]: fixed

File: packages/flutter/test/material/paginated_data_table_test.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/test/material/paginated_data_table_test.dart]: Sure! It never hurst to have extra comments explaining things. Future contributors will appreciate it. :)

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 3]
```diff
@@ -86,6 +86,8 @@ class PaginatedDataTable extends StatefulWidget {
     this.arrowHeadColor,
     required this.source,
     this.checkboxHorizontalMargin,
+    this.controller,
+    this.primary=false,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:90]: Apologies for the churn, this should probably be null by default. Eventually SingleChildScrollView makes a default decision on primary if it is not set.

File: packages/flutter/test/material/paginated_data_table_test.dart [hunk 4]
```diff
@@ -1043,4 +1044,81 @@ void main() {
...
+
+    await tester.pumpWidget(MaterialApp(
+      home: buildTable(source),
+    ));
+
+    expect(scrollController.offset, 0.0);
+
+    scrollController.jumpTo(50.0);
+    await tester.pumpAndSettle();
+    expect(scrollController.offset, 50.0);
```
Comment (Piinks) [inline packages/flutter/test/material/paginated_data_table_test.dart:1090]: This does not actually verify which scrollable used the scroll controller, like the other test below.

File: packages/flutter/test/material/paginated_data_table_test.dart [hunk 5]
```diff
@@ -1043,4 +1044,81 @@ void main() {
...
+              DataColumn(label: Text('Generation')),
+            ],
+          ),
+        ),
+      )
+    );
+
+    // DataTable uses primaryScrollController
+    final Scrollable bodyScrollView = tester.widget(find.byType(Scrollable).first);
+    expect(bodyScrollView.controller, primaryScrollController);
```
Comment (Piinks) [inline packages/flutter/test/material/paginated_data_table_test.dart:1118]: Adding an additional check like this above should validate the assigned scroll controller is being used.

File: packages/flutter/test/material/paginated_data_table_test.dart (hunk 4 above)
Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1090]: Since we never pass the controller to the second scrollable(footer), can we safely assume that it is always DataTable that uses the provided ScrollController?

Comment (Piinks) [reply packages/flutter/test/material/paginated_data_table_test.dart:1090]: That is a great question! I imagine it is possible the user may want access to one controller or the other at some point. Does the issue specify which scrollable is needed for access? If so, it may require we have clearer parameters here that indicate which controller this is.

Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1090]: Issue mentions that it needs controller for contents of PaginatedDataTable.  I assume that it is for main content.

Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1090]: Hi @Piinks,  Should I expose both the controllers?

Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1090]: Sure, I did ask and the author only needs the controller for DataTable.

File: packages/flutter/test/material/paginated_data_table_test.dart (hunk 5 above)
Comment (amanv8060) [reply packages/flutter/test/material/paginated_data_table_test.dart:1118]: Added this, But for curiosity, would the following be a good solution for this?
```
    // check with position instead of ScrollController's offset to confirm both
    // offset and that the DataTable used ScrollController
    final ScrollPosition position = tester.state<ScrollableState>(find.byType(Scrollable).first).position;

    expect(position.extentBefore, 50.0);  
```
This way both the things get tested at the same time.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!

**Comment by Piinks** [comment]
This will need a second review, I have sought one out.

**Review by cbracken — APPROVED** [review]
