### PR TITLE
Fix(Material): DateRangePicker ignores DatePickerTheme.dayShape

### LINKED ISSUE #181500: dayShape resolve from theme's dayShape is missing in `_DayItem` used in `DateRangePicker`
Passing dayShape to DatePickerThemeData of Theme has no effect for DateRangePicker. Moreover, even `today` day is also not affected.

`_DayItem` should have almost the same styling as `_Day`: they are semantically the same components:

`_Day` of date picker:

Image

`_DayItem` of date range picker after changes:

Image

Image

So, by copying date picker `_Day` the issue easily resolved 🙂

### Results:
| After | Before |
|--------|--------|
| Image|  Image | 

<details><summary>Reproducible code</summary>
<p>

```dart
void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomeScreen(),
      theme: ThemeData.dark(useMaterial3: true).copyWith(
        dialogTheme: const DialogThemeData(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.zero),
        ),

        datePickerTheme: DatePickerThemeData(
          rangePickerShape: RoundedRectangleBorder(
            borderRadius: BorderRadius.zero,
          ),

          dayShape: WidgetStatePropertyAll<OutlinedBorder>(
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(8.0)),
          ),
          shape: RoundedRectangleBorder(borderRadius: .zero),
        ),
      ),
    ),
  );
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Calendar examples')),
      body: Align(
        child: Column(
          spacing: 6,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                showDateRangePicker(
                  context: context,
                  firstDate: DateTime(2020),
                  lastDate: DateTime(2030),
                  selectableDayPredicate:
                      (day, selectedStartDay, selectedEndDay) {
                        return true;
                      },
                  builder: (context, child) {
                    return Center(
                      child: ConstrainedBox(
                        constraints: const BoxConstraints(
                          maxWidth: 400.0,
                          maxHeight: 600.0,
                        ),
                        child: child,
                      ),
                    );
                  },
                );
              },
              child: Text('Open date range picker'),
            ),
            ElevatedButton(
              onPressed: () {
                showDatePicker(
                  context: context,
                  firstDate: DateTime(2020),
                  lastDate: DateTime(2030),
                  builder: (context, child) {
                    return Center(
                      child: ConstrainedBox(
                        constraints: BoxConstraints(
                          maxWidth: 400.0,
                          maxHeight: 600.0,
                        ),
                        child: child,
                      ),
                    );
                  },
                );
              },
              child: Text('Open date picker'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</p>
</details> 

<details><summary>Flutter doctor</summary>
<p>

```shell
• Flutter version 3.38.3 on channel stable at /Users/me/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19074d12f7 (10 weeks ago), 2025-11-20 17:53:13 -0500
    • Engine revision 13e658725d
    • Dart version 3.10.1
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration
``` 

</p>
</details>

### PR DESCRIPTION
**Pull request by akhil-ge0rge**
This change fixes a problem where `showDateRangePicker` ignored the `dayShape` property in `DatePickerThemeData`, leading to days always rendering as circles regardless of the theme. This was caused by the internal `_DayItem` widget using a hardcoded `BoxDecoration` regardless of the theme configuration.

Fixes #181500

| Before | After |
| :---: | :---: |
|  |  |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/date_picker.dart [hunk 1]
```diff
@@ -2928,10 +2932,11 @@ class _DayItemState extends State<_DayItem> {
       // The current day gets a different text color and a circle stroke
       // border.
```
Comment (komakur) [inline packages/flutter/lib/src/material/date_picker.dart]: This is misleading as well: `circle stroke`

File: packages/flutter/lib/src/material/date_picker.dart [hunk 2]
```diff
@@ -2894,13 +2894,17 @@ class _DayItemState extends State<_DayItem> {
...
 
+    final OutlinedBorder dayShape =
+        resolve<OutlinedBorder?>((DatePickerThemeData? theme) => theme?.dayShape, states) ??
+        const CircleBorder();
+
     _HighlightPainter? highlightPainter;
 
     if (widget.isSelectedDayStart || widget.isSelectedDayEnd) {
       // The selected start and end dates gets a circle background
       // highlight, and a contrasting text color.
```
Comment (komakur) [inline packages/flutter/lib/src/material/date_picker.dart]: This comment is now misleading. Selected start and end dates do not always get a circle background highlight

**Comment by akhil-ge0rge** [comment]
Hi @dkwingsmt just checking in on this!
I've updated the PR to address the splash effect issue and corrected the comments.
I also rebased with master to ensure everything is fresh.

Please let me know if there are any other changes needed. Thanks!

File: packages/flutter/lib/src/material/date_picker.dart [hunk 3]
```diff
@@ -2925,13 +2929,13 @@ class _DayItemState extends State<_DayItem> {
     } else if (widget.isDisabled) {
       itemStyle = itemStyle?.apply(color: colorScheme.onSurface.withOpacity(0.38));
     } else if (widget.isToday) {
-      // The current day gets a different text color and a circle stroke
-      // border.
+      // The current day gets a different text color and a stroke border.
```
Comment (komakur) [inline packages/flutter/lib/src/material/date_picker.dart]:
```suggestion
      // The current day gets a different text color and a custom shape border.
```

File: packages/flutter/lib/src/material/date_picker.dart [hunk 4]
```diff
@@ -2894,13 +2894,17 @@ class _DayItemState extends State<_DayItem> {
...
+        resolve<OutlinedBorder?>((DatePickerThemeData? theme) => theme?.dayShape, states) ??
+        const CircleBorder();
+
     _HighlightPainter? highlightPainter;
 
     if (widget.isSelectedDayStart || widget.isSelectedDayEnd) {
-      // The selected start and end dates gets a circle background
-      // highlight, and a contrasting text color.
+      // The selected start and end dates get a background highlight
+      // matching the day shape, and a contrasting text color.
```
Comment (komakur) [inline packages/flutter/lib/src/material/date_picker.dart]:
```suggestion
      // The selected start and end dates get a custom shaped background
      // highlight, and a contrasting text color.
```

File: packages/flutter/lib/src/material/date_picker.dart [hunk 5]
```diff
@@ -2855,7 +2855,7 @@ class _DayItemState extends State<_DayItem> {
     final TextDirection textDirection = Directionality.of(context);
     final Color highlightColor = widget.highlightColor;
 
-    BoxDecoration? decoration;
+    ShapeDecoration? decoration;
     TextStyle? itemStyle = textTheme.bodyMedium;
```
Comment (komakur) [inline packages/flutter/lib/src/material/date_picker.dart:2859]: @dkwingsmt also worth checking:

On Material 3 `bodyLarge` is used, although in current implementation it's `textTheme.bodyMedium`.

But in date_picker_theme.dart **L1124**:
  ```dart
@override
  TextStyle? get dayStyle => _textTheme.bodySmall;
```

Image

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 6]
```diff
@@ -2025,6 +2025,60 @@ void main() {
...
+
+  testWidgets('DateRangePicker respects DatePickerTheme.dayShape', (WidgetTester tester) async {
+    const OutlinedBorder customShape = BeveledRectangleBorder(
+      borderRadius: BorderRadius.all(Radius.circular(10)),
+    );
+
+    await tester.pumpWidget(
+      MaterialApp(
+        theme: ThemeData(
+          useMaterial3: true,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/date_range_picker_test.dart]: nit: remove this line since `true` is the default value.

File: packages/flutter/lib/src/material/date_picker.dart [hunk 7]
```diff
@@ -2969,7 +2973,8 @@ class _DayItemState extends State<_DayItem> {
       dayWidget = InkResponse(
         focusNode: widget.focusNode,
         onTap: () => widget.onChanged(widget.day),
-        radius: _monthItemRowHeight / 2 + 4,
+        customBorder: dayShape,
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/date_picker.dart:2976]: I noticed a small behavior change. It seems that removing `radius` causes the ink splash to disappear when pressing and holding a day. Initially, there was an ink splash larger than the circle radius (as seen in the demo below). Since I don't see this in the M3 specs, I’ll consider the change expected.

https://github.com/user-attachments/assets/820a56da-a410-4a6f-904e-347ad1031ca3

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks for adding this fix:)

File: packages/flutter/lib/src/material/date_picker.dart (hunk 5 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/date_picker.dart:2859]: Hi @komakur! The code in L1124 in date_picker_theme.dart is for M2 date picker and for M3 date picker, the default bodyLarge is:
https://github.com/flutter/flutter/blob/f5825a22a47969ce9fec303dbefee035eadb1acc/packages/flutter/lib/src/material/date_picker_theme.dart#L1317

**Review by dkwingsmt — APPROVED** [review]
LGTM. Awesome change! Also thank you @komakur for the comments.

**Comment by akhil-ge0rge** [comment]
Hi @dkwingsmt , @QuncCccccc , @komakur ,

Thanks for the reviews and approvals!,
All checks have passed, so please let me know if there are any final steps needed to land this.

**Review by QuncCccccc — APPROVED** [review]
LGTM:)
