### PR TITLE
Force WASM single threading in Chrome extensions.

### LINKED ISSUE #177974: [BUG] Flutter multi-threaded WASM web app cannot run as Chrome Extension
### Steps to reproduce

I created a reproducible example here with all the info inside README:
https://github.com/AlexDochioiu/flutter-wasm-chrome-extension-bug

To fix this, I created (with AI) some patch script. This patch script modifies the `flutter_bootstrap.js` from the **build/web** and forces single-threaded WASM execution:
https://github.com/AlexDochioiu/flutter-wasm-chrome-extension-bug/blob/master/scripts/web/patch_flutter_bootstrap.sh

### Expected results

WASM should work with chrome extensions

### Actual results

SKWASM renderer fails to load with error.

### Code sample

https://github.com/AlexDochioiu/flutter-wasm-chrome-extension-bug

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

### Before my patch script
Image

### After my patch script
Image

</details>

### Logs

<details open><summary>WEB Logs (Chrome Console)</summary>

```console
Installing/Activating first service worker.
flutter_bootstrap.js:31 Exception while loading service worker: Error: prepareServiceWorker took more than 4000ms to resolve. Moving on.
    at flutter_bootstrap.js:1:3542
(anonymous) @ flutter_bootstrap.js:31Understand this warning
a32253ce-571b-4adc-aa21-3002e27ee8ed:12 Loading the script 'chrome-extension://aoagnldgoecncalmmahhgogmgghgahee/canvaskit/skwasm.js' violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback. The action has been blocked.
eventListener @ a32253ce-571b-4adc-aa21-3002e27ee8ed:12Understand this error
a32253ce-571b-4adc-aa21-3002e27ee8ed:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://aoagnldgoecncalmmahhgogmgghgahee/canvaskit/skwasm.js
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜ flutter doctor -v


[✓] Flutter (Channel stable, 3.35.7, on macOS 26.0.1 25A362 darwin-arm64, locale en-US) [1,155ms]
    • Flutter version 3.35.7 on channel stable at /Users/alexandrudochioiu/.asdf/installs/flutter/3.35.7-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adc9010625 (2 weeks ago), 2025-10-21 14:16:03 -0400
    • Engine revision 035316565a
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-lldb-debugging

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [2.1s]
    • Android SDK at /Users/alexandrudochioiu/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/alexandrudochioiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1) [1,959ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A400
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)

[✓] Connected device (4 available) [6.1s]
    • Alexandru’s iPhone 15 (wireless) (mobile) • 00008120-001250E12250A01E • ios            • iOS 26.0.1 23A355
    • iPhone (wireless) (mobile)                • 00008120-001454811A62201E • ios            • iOS 18.1 22B83
    • macOS (desktop)                           • macos                     • darwin-arm64   • macOS 26.0.1 25A362 darwin-arm64
    • Chrome (web)                              • chrome                    • web-javascript • Google Chrome 142.0.7444.60

[✓] Network resources [662ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/177974

### Description
- Forces WASM single-threading when running a web app as a Chrome extension.

| BEFORE | AFTER |
| - | - |
| <video alt="before" src="https://github.com/user-attachments/assets/4b67fce6-4bd7-4646-a0db-dc6ad2ec70aa" /> | <video alt="after" src="https://github.com/user-attachments/assets/3f0df9c5-7524-40db-a631-776777f855f9"/> |

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]
Thanks for fixing this, @ksokolovskyi !

File: engine/src/flutter/lib/web_ui/flutter_js/src/browser_environment.js [hunk 1]
```diff
@@ -72,6 +72,10 @@ const detectWebGLVersion = () => {
   return -1;
 }
 
+const isChromeExtension = () => {
+  return window.chrome && chrome.runtime && chrome.runtime.id;
```
Comment (kevmoo) [inline engine/src/flutter/lib/web_ui/flutter_js/src/browser_environment.js:78]: Could we add a comment here linking to the docs explaining where this API is defined?

File: engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js [hunk 2]
```diff
@@ -16,7 +16,7 @@ export const loadSkwasm = async (deps, config, browserEnvironment, baseUrl) => {
   const wasmInstantiator = createWasmInstantiator(resolveUrlWithSegments(baseUrl, `${fileStem}.wasm`));
   const skwasm = await import(skwasmUrl);
   return await skwasm.default({
-    skwasmSingleThreaded: !browserEnvironment.crossOriginIsolated || config.forceSingleThreadedSkwasm,
+    skwasmSingleThreaded: !browserEnvironment.crossOriginIsolated || browserEnvironment.isChromeExtension || config.forceSingleThreadedSkwasm,
```
Comment (kevmoo) [inline engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js:23]: Could we add a comment here saying WHY we force single-thread for chrome extensions? Good for history!

**Review by kevmoo — CHANGES_REQUESTED** [review]

File: engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js (hunk 2 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js:23]: It's all explained in the linked issue, but I agree, adding comments for future readers does help!

File: engine/src/flutter/lib/web_ui/flutter_js/src/browser_environment.js (hunk 1 above)
Comment (kevmoo) [reply engine/src/flutter/lib/web_ui/flutter_js/src/browser_environment.js:78]: Thank you!

File: engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js (hunk 2 above)
Comment (kevmoo) [reply engine/src/flutter/lib/web_ui/flutter_js/src/skwasm_loader.js:23]: wonderful! thanks!

**Review by kevmoo — APPROVED** [review]
