### PR TITLE
Fix transforms for things with RenderPointerListeners

### LINKED ISSUE #32525: RenderPointerListener breaks transforms.
Due to a change in #32025, `RenderPointerListener` started returning a calculated value for `needsCompositing`, but wasn't calling `markNeedsCompositingBitsUpdate` in all cases.

It needs to be fixed to call `markNeedsCompositingBitsUpdate` whenever the value of `MouseTracker.mouseIsConnected` changes.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This fixes #32525, because it now marks the compositing bits as needing to be recalculated if the mouse tracker changes its idea of whether or not a mouse is attached.

This bug occurred because the test framework was leaking state from one test to the next (the state about whether a mouse pointer was active), and so even though there was a "passing" test when run in order with the other tests in the file, when the test was run individually (or first), it would have failed and caught the bug.

This adds an assert to make sure that after each test there are no simulated mouse pointers connected, and now calls `removePointer` in all of the tests where this was a problem.

## Related Issues

Fixes #32525

## Tests

There was no need to add a test: the relevant test already existed, but was not failing in CI because of the non-hermetic test framework.

### CODE REVIEW

**Comment by gspencergoog** [comment]
cc @goderbauer

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -2639,13 +2649,10 @@ class RenderPointerListener extends RenderProxyBoxWithHitTestBehavior {
...
 
-  bool get _hasActiveAnnotation {
-    return _hoverAnnotation != null
-      && RendererBinding.instance.mouseTracker.mouseIsConnected;
-  }
+  bool get _hasActiveAnnotation => _hoverAnnotation != null && _mouseIsConnected;
 
   @override
-  bool get needsCompositing => _hasActiveAnnotation;
+  bool get needsCompositing =>  _hasActiveAnnotation;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: Is it intended?

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 2]
```diff
@@ -2592,9 +2595,16 @@ class RenderPointerListener extends RenderProxyBoxWithHitTestBehavior {
     }
   }
 
+  bool _mouseIsConnected;
   void _handleMouseTrackerChanged() {
-    if (attached)
-      markNeedsPaint();
+    final bool newState = RendererBinding.instance.mouseTracker.mouseIsConnected;
+    if (attached && newState != _mouseIsConnected) {
+      _mouseIsConnected = newState;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: Can you explain why `_mouseIsConnected` doesn't need changing when `attached` is false? Is it possible to be reattached and find `_mouseIsConnected` desync'ed?

Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: Oh, yes, I think you're right.  Originally, I was avoiding painting when detached, but avoiding it isn't needed, since it can call `markNeedsPaint` when detached, and that won't do anything until it attaches again.

**Review by dkwingsmt — APPROVED** [review]
