### PR TITLE
Don't call `PlatformViewCreatedCallback`s after `AndroidViewController` is disposed

### LINKED ISSUE #84628: [webview] [platform_view] error ( Unhandled Exception: setState() called after dispose(): _PlatformViewLinkState#a7b8e(lifecycle state: defunct, not mounted) )
I got this errros on use webview on tabview child using List.Generator.

Works very well, using any widget on child page.

I got following errors when add the first tab. Second and another pages not fire this errors.

> E/flutter (20419): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)]
> Unhandled Exception: setState() called after dispose():
> _PlatformViewLinkState#a7b8e(lifecycle state: defunct, not mounted) 

>E/flutter (20419): This error happens if you call setState() on a
> State object for a widget that no longer appears in the widget tree
> (e.g., whose parent widget no longer includes the widget in its
> build). This error can occur when code calls setState() from a timer
> or an animation callback. 

> E/flutter (20419): The preferred solution is
> to cancel the timer or stop listening to the animation in the
> dispose() callback. Another solution is to check the "mounted"
> property of this object before calling setState() to ensure the object
> is still in the tree. 

>E/flutter (20419): This error might indicate a
> memory leak if setState() is being called because another object is
> retaining a reference to this State object after it has been removed
> from the tree. To avoid memory leaks, consider breaking the reference
> to this object during dispose().

To reproduce, run this code:

``` 
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'dart:async';
import 'dart:io';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class Home extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<Home> {
  List<Widget> data = [Container()];

  int initPosition = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: CustomTabView(
          initPosition: initPosition,
          itemCount: data.length,
          tabBuilder: (context, index) {
            if (index == 0) {
              return Tab(icon: Icon(Icons.home));
            } else {
              return Tab(text: index.toString());
            }
          },
          pageBuilder: (context, index) {
            if (index == 0) {
              return Center(
                  child: FloatingActionButton(
                      child: Icon(Icons.add),
                      onPressed: () {
                        setState(() {
                          data.add(Page(
                            url: 'https://www.google.com',
                            key: ValueKey('$index'),
                          ));
                        });
                      }));
            } else {
              return Center(child: (data[index]));
            }
          },
          onPositionChange: (index) {
            print('current position: $index');
            initPosition = index;
          },
          onScroll: (position) => print('$position'),
        ),
      ),
    );
  }
}

/// Implementation

class CustomTabView extends StatefulWidget {
  final int? itemCount;
  final IndexedWidgetBuilder? tabBuilder;
  final IndexedWidgetBuilder? pageBuilder;
  final Widget? stub;
  final ValueChanged<int>? onPositionChange;
  final ValueChanged<double>? onScroll;
  final int? initPosition;

  CustomTabView({
    @required this.itemCount,
    @required this.tabBuilder,
    @required this.pageBuilder,
    this.stub,
    this.onPositionChange,
    this.onScroll,
    this.initPosition,
  });

  @override
  _CustomTabsState createState() => _CustomTabsState();
}

class _CustomTabsState extends State<CustomTabView>
    with TickerProviderStateMixin {
  TabController? controller;
  int? _currentCount;
  int? _currentPosition;

  @override
  void initState() {
    _currentPosition = widget.initPosition ?? 0;
    controller = TabController(
      length: widget.itemCount!,
      vsync: this,
      initialIndex: _currentPosition!,
    );
    controller!.addListener(onPositionChange);
    controller!.animation!.addListener(onScroll);
    _currentCount = widget.itemCount;
    super.initState();
  }

  @override
  void didUpdateWidget(CustomTabView oldWidget) {
    print('current position: $_currentPosition');

    if (_currentCount != widget.itemCount) {
      print('_currentCount != widget.itemCount');
      controller!.animation!.removeListener(onScroll);
      controller!.removeListener(onPositionChange);
      controller!.dispose();

      if (widget.initPosition != null) {
        print('widget.initPosition != null');
        _currentPosition = widget.initPosition;
      }

      if (_currentPosition! > widget.itemCount! - 1) {
        print('_currentPosition > widget.itemCount - 1');
        _currentPosition = widget.itemCount! - 1;
        _currentPosition = _currentPosition! < 0 ? 0 : _currentPosition;
        if (widget.onPositionChange is ValueChanged<int>) {
          WidgetsBinding.instance!.addPostFrameCallback((_) {
            if (mounted) {
              widget.onPositionChange!(_currentPosition!);
            }
          });
        }
      }

      _currentCount = widget.itemCount;
      setState(() {
        controller = TabController(
          length: widget.itemCount!,
          vsync: this,
          initialIndex: _currentPosition!,
        );
        controller!.addListener(onPositionChange);
        controller!.animation!.addListener(onScroll);
      });

      controller!.animateTo(widget.itemCount! - 1);
    } else if (widget.initPosition != null) {
      controller!.animateTo(widget.initPosition!);
    }

    super.didUpdateWidget(oldWidget);
  }

  @override
  void dispose() {
    controller!.animation!.removeListener(onScroll);
    controller!.removeListener(onPositionChange);
    controller!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.itemCount! < 1) return widget.stub ?? Container();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Expanded(
          child: TabBarView(
            physics: NeverScrollableScrollPhysics(),
            controller: controller,
            children: List.generate(
              widget.itemCount!,
              (index) => widget.pageBuilder!(context, index),
            ),
          ),
        ),
        Container(
          alignment: Alignment.centerLeft,
          child: TabBar(
            isScrollable: true,
            controller: controller,
            labelColor: Theme.of(context).primaryColor,
            unselectedLabelColor: Theme.of(context).hintColor,
            indicator: BoxDecoration(
              border: Border(
                bottom: BorderSide(
                  color: Theme.of(context).primaryColor,
                  width: 2,
                ),
              ),
            ),
            tabs: List.generate(
              widget.itemCount!,
              (index) => widget.tabBuilder!(context, index),
            ),
          ),
        ),
      ],
    );
  }

  onPositionChange() {
    if (!controller!.indexIsChanging) {
      _currentPosition = controller!.index;
      if (widget.onPositionChange is ValueChanged<int>) {
        widget.onPositionChange!(_currentPosition!);
      }
    }
  }

  onScroll() {
    if (widget.onScroll is ValueChanged<double>) {
      widget.onScroll!(controller!.animation!.value);
    }
  }
}

class Page extends StatefulWidget {
  const Page({key, this.url}) : super(key: key);

  final String? url;

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> with AutomaticKeepAliveClientMixin<Page> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  late final url = widget.url!;

  @override
  bool get wantKeepAlive => true;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return Scaffold(
        body: WebView(
      key: widget.key,
      initialUrl: url,
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        debugPrint("WebView is created");

        _controller.complete(webViewController);
      },
      onProgress: (int progress) {
        debugPrint("WebView is loading (progress : $progress%)");
      },
      onPageStarted: (String url) {
        debugPrint('Page started loading: $url');
      },
      onPageFinished: (String url) {
        debugPrint('Page finished loading: $url');

        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Page finished loading: $url'),
          duration: Duration(seconds: 5),
        ));
      },
    ));
  }
}

```

### LINKED ISSUE #96384: Null check operator used on a null value in PlatformView.
https://github.com/flutter/flutter/blob/7fe3565a9b335b6a3aa71de1698a82b2ff0fadee/packages/flutter/lib/src/widgets/platform_view.dart#L898

setState is called when `element` is null.

Stacktrace received on crashlytics:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
       at State.setState(framework.dart:1108)
       at _PlatformViewLinkState._onPlatformViewCreated(platform_view.dart:889)
       at AndroidViewController.create(platform_views.dart:752)
```

### PR DESCRIPTION
**Pull request by blaugold**
Before this change, it was possible that, if a `AndroidViewController` was disposed before we got the notification that the platform view was created, `PlatformViewCreatedCallback`s were called even after calling `AndroidViewController.dispose`.

Also makes `_PlatformViewLinkState._onPlatformViewCreated` more careful to only call `setState` when mounted.

Closes #84628
Closes #96384

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
@reidbaker Could somebody from the Android team review this one? Thanks.

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 1]
```diff
@@ -927,9 +927,11 @@ class _PlatformViewLinkState extends State<PlatformViewLink> {
   }
 
   void _onPlatformViewCreated(int id) {
-    setState(() {
-      _platformViewCreated = true;
-    });
+    if (mounted) {
```
Comment (reidbaker) [inline packages/flutter/lib/src/widgets/platform_view.dart:930]: This might be a dumb question but when can this be called and not mounted? What side effects are there if setState is not called because this view was not mounted?

File: packages/flutter/test/widgets/platform_view_test.dart [hunk 2]
```diff
@@ -2719,6 +2719,30 @@ void main() {
...
+            hitTestBehavior: PlatformViewHitTestBehavior.opaque,
+          );
+        },
+      );
+
+      await tester.pumpWidget(platformViewLink);
+
+      await tester.pumpWidget(Container());
+
+      creationParams.onPlatformViewCreated(creationParams.id);
```
Comment (reidbaker) [inline packages/flutter/test/widgets/platform_view_test.dart:2743]: Should there be some verification here beyond not crashing?

**Review by reidbaker — COMMENTED** [review]
@GaryQian would you also take a look here

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 1 above)
Comment (blaugold) [reply packages/flutter/lib/src/widgets/platform_view.dart:930]: > This might be a dumb question but when can this be called and not mounted?

While working on the fix, the call to `setState` was the place where I started, since that was causing the exceptions. Guarding the cal with `if (mounted)` resolves the issue, but I asked myself the same question. The root cause is that native platform views are created asynchronously through a `MethodChannel` but the `PlatformViewLink` that triggered the creation of the platform view can be disposed before the platform view has been created. A `PlatformViewLink` disposes its `PlatformViewController` and it would make sense for that to prevent any further callbacks from firing. If that is the case, the call to `setState` should not require a guard. Looking at `AndroidViewController.dispose` I found that that is not guaranteed, so I changed its implementation to synchronously clean up all listeners.

Fixing `AndroidViewController` makes the guard for `setState` unnecessary, but `AndroidViewController` is not the only implementation of `PlatformViewController` so to be defensive I thought it might make sense to leave it in.

File: packages/flutter/test/widgets/platform_view_test.dart (hunk 2 above)
Comment (GaryQian) [reply packages/flutter/test/widgets/platform_view_test.dart:2743]: +1, missing some sort of `expect(...);`

**Comment by GaryQian** [comment]
The fix looks good, just a reminder on the test fix!

**Review by reidbaker — APPROVED** [review]

**Comment by goderbauer** [comment]
(triage) looks like this may need to be rebased with master to trigger the "google testing" check again. @blaugold could you do that please? Thanks!

**Comment by blaugold** [comment]
@goderbauer Thanks for letting me know! I rebased the PR.

**Review by reidbaker — APPROVED** [review]

**Comment by blaugold** [comment]
@reidbaker I think we need an approved review by another member, since I'm not a member.

**Comment by reidbaker** [comment]
@camsim99 can you review this

**Review by camsim99 — APPROVED** [review]
LGTM!

**Comment by dmrickey** [comment]
I have no idea what the process is for this, but I see this is on `master` now but not yet on `stable`. I also see that there's `cherry pick` form to fill out, but I'm not really involved in this so it doesn't seem like I'm the correct person to fill out that form (or the correct person to make a PR for cherry picking this to stable). 

So what needs to happen for this to be on stable? My logs are being filled with "errors" that this resolves so it would be super nice if this could go through whatever process is necessary for it to be officially released.
