### PR TITLE
Work around VS CMake generation bug

### LINKED ISSUE #97086: Fail to launch app in debug mode on windows: "Can't load AOT data" with VS 2022 17.1.0
## Steps to Reproduce

1. Create a new application.
2. run `flutter run -d windows --debug`

**Expected results:** 
The build should success.

**Actual results:** 
Can't load AOT data from C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\Debug\data\app.so; no such file.
Unable to start engine without AOT data.
Failed to create view controller.
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.

<details>
  <summary>Logs</summary>

```
[  +70 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +568 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 31560ca68c4573046c249ace79c2e0e2e83d7da2
[        ] executing: [C:\flutter/] git tag --points-at 31560ca68c4573046c249ace79c2e0e2e83d7da2
[  +45 ms] Exit code 0 from: git tag --points-at 31560ca68c4573046c249ace79c2e0e2e83d7da2
[   +1 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags 31560ca68c4573046c249ace79c2e0e2e83d7da2
[  +73 ms] Exit code 0 from: git describe --match *.*.* --long --tags 31560ca68c4573046c249ace79c2e0e2e83d7da2
[        ] 2.9.0-0.0.pre-459-g31560ca68c
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git://github.com/flutter/flutter.git
[ +260 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] Skipping pub get: version match.
[ +114 ms] Generating C:\Users\nieti\Desktop\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +104 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +9 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Users\nieti\Desktop\flutter_application_1\.dart_tool\package_config_subset}
[  +29 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +6 ms] Launching lib\main.dart on Windows in debug mode...
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\nieti\AppData\Local\Temp\flutter_tools.cf247ee9\flutter_tool.cd87ecc5\app.dill --packages C:\Users\nieti\Desktop\flutter_application_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +27 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +30 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +23 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +24 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "4989712f",
               "installDate": "2022-01-23T05:23:09Z",
               "installationName": "VisualStudioPreview/17.1.0-pre.3.0+32113.165",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
               "installationVersion": "17.1.32113.165",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": true,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.17.Preview",
               "channelUri": "https://aka.ms/vs/17/pre/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelUri": "https://aka.ms/vs/17/pre/channel",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.1.0-pre.3.0",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-01-23T05:23:09.0328153Z",
               "catalog": {
                 "buildBranch": "d17.1",
                 "buildVersion": "17.1.32113.165",
                 "id": "VisualStudioPreview/17.1.0-pre.3.0+32113.165",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudioPreview",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.1.0 Preview 3.0",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "Preview",
                 "productMilestoneIsPreRelease": "True",
                 "productName": "Visual Studio",
                 "productPatchVersion": "0",
                 "productPreReleaseMilestoneSuffix": "3.0",
                 "productSemanticVersion": "17.1.0-pre.3.0+32113.165",
                 "requiredEngineVersion": "3.1.2188.10961"
               },
               "properties": {
                 "campaignId": "283642230.1625114825",
                 "channelManifestId": "VisualStudio.17.Preview/17.1.0-pre.3.0+32113.165",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +1 ms] Building Windows application...
[  +24 ms] <- compile package:flutter_application_1/main.dart
[   +1 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\Users\nieti\Desktop\flutter_application_1\windows -B build\windows -G Visual Studio 17 2022
[  +81 ms] -- Configuring done
[ +260 ms] -- Generating done
[  +18 ms] -- Build files have been written to: C:/Users/nieti/Desktop/flutter_application_1/build/windows
[   +9 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug --target INSTALL --verbose
[ +145 ms] Microsoft (R) Build Engine version 17.1.0-preview-22055-02+797fd829a for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[ +315 ms] Build started 1/23/2022 2:24:13 PM.
[+1481 ms] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\INSTALL.vcxproj" on node 1 (default targets).
[        ] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\INSTALL.vcxproj" (1) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[   +3 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +67 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +47 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[   +6 ms] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ZERO_CHECK.vcxproj" (default targets).
[ +134 ms] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\INSTALL.vcxproj" (1) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
[        ] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj" (4) on node 1 (default targets).
[        ] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj" (4) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_assemble.vcxproj" (5) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +12 ms] CustomBuild:
[        ]   "The build of 'C:\Users\nieti\Desktop\flutter_application_1\build\windows\CMakeFiles\13355dbdb3d7ac1cde89d173fbb8afcd\flutter_assemble.rule' depends on 'C:\USERS\NIETI\DESKTOP\FLUTTER_APPLICATION_1\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of 'C:\Users\nieti\Desktop\flutter_application_1\build\windows\CMakeFiles\e501cfdc272c77749a6fb9de8c22c77a\flutter_windows.dll.rule'. The items cannot be built in parallel."
[  +98 ms]   Generating C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_windows.dll, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_export.h, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_windows.h, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_messenger.h, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_plugin_registrar.h, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/flutter_texture_registrar.h, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc, C:/Users/nieti/Desktop/flutter_application_1/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[+1909 ms]   [  +81 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +533 ms]   [ +555 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ]   [        ] 31560ca68c4573046c249ace79c2e0e2e83d7da2
[        ]   [        ] executing: [C:\flutter/] git tag --points-at 31560ca68c4573046c249ace79c2e0e2e83d7da2
[  +63 ms]   [  +63 ms] Exit code 0 from: git tag --points-at 31560ca68c4573046c249ace79c2e0e2e83d7da2
[   +1 ms]   [   +1 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags 31560ca68c4573046c249ace79c2e0e2e83d7da2
[  +87 ms]   [  +87 ms] Exit code 0 from: git describe --match *.*.* --long --tags 31560ca68c4573046c249ace79c2e0e2e83d7da2
[        ]   [        ] 2.9.0-0.0.pre-459-g31560ca68c
[   +9 ms]   [   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms]   [  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ]   [        ] origin/master
[        ]   [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +37 ms]   [  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ]   [        ] git://github.com/flutter/flutter.git
[ +281 ms]   [ +281 ms] Unable to locate an Android SDK.
[   +3 ms]   [   +3 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +38 ms]   [  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ]   [        ] master
[  +64 ms]   [  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms]   [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms]   [ +103 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +3 ms]   [   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +42 ms]   [  +43 ms] Initializing file store
[  +18 ms]   [  +17 ms] Done initializing file store
[  +60 ms]   [  +61 ms] Skipping target: gen_localizations
[  +12 ms]   [  +11 ms] Skipping target: gen_dart_plugin_registrant
[+2554 ms]   [+2554 ms] Skipping target: unpack_windows
[ +449 ms]   [ +449 ms] Skipping target: kernel_snapshot
[  +22 ms]   [  +23 ms] Skipping target: aot_elf_release
[  +22 ms]   [  +22 ms] Skipping target: windows_aot_bundle
[  +38 ms]   [  +38 ms] Skipping target: release_bundle_windows_assets
[        ]   [        ] Persisting file store
[  +10 ms]   [  +10 ms] Done persisting file store
[   +5 ms]   [   +5 ms] build succeeded.
[   +8 ms]   [   +8 ms] "flutter assemble" took 3,379ms.
[ +262 ms]   [ +261 ms] ensureAnalyticsSent: 258ms
[   +1 ms]   [   +1 ms] Running shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 0
[  +95 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_assemble.vcxproj" (default targets).
[  +23 ms] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj" (4) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_wrapper_app.vcxproj" (6) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_app.dir\Debug\flutter_.6C6B7038.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +2 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +75 ms] ClCompile:
[        ]   All outputs are up-to-date.
[  +36 ms] Lib:
[        ]   All outputs are up-to-date.
[   +4 ms]   flutter_wrapper_app.vcxproj -> C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\Debug\flutter_wrapper_app.lib
[  +19 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_app.dir\Debug\flutter_.6C6B7038.tlog\unsuccessfulbuild".
[        ]   Touching "flutter_wrapper_app.dir\Debug\flutter_.6C6B7038.tlog\flutter_wrapper_app.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_wrapper_app.vcxproj" (default targets).
[  +17 ms] InitializeBuildStatus:
[        ]   Creating "flutter_application_1.dir\Debug\flutter_.637C0DF5.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +2 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +37 ms] ClCompile:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\CL.exe /c /IC:\Users\nieti\Desktop\flutter_application_1\windows /IC:\Users\nieti\Desktop\flutter_application_1\windows\flutter\ephemeral /IC:\Users\nieti\Desktop\flutter_application_1\windows\flutter\ephemeral\cpp_client_wrapper\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"flutter_application_1.dir\Debug\\" /Fd"flutter_application_1.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\nieti\Desktop\flutter_application_1\windows\flutter\generated_plugin_registrant.cc C:\Users\nieti\Desktop\flutter_application_1\windows\runner\flutter_window.cpp
[  +89 ms]   generated_plugin_registrant.cc
[ +453 ms]   flutter_window.cpp
[+1136 ms]   Generating Code...
[  +85 ms] ResourceCompile:
[        ]   All outputs are up-to-date.
[  +46 ms] Link:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\Debug\flutter_application_1.exe" /INCREMENTAL /ILK:"flutter_application_1.dir\Debug\flutter_application_1.ilk" /NOLOGO ..\flutter\Debug\flutter_wrapper_app.lib C:\Users\nieti\Desktop\flutter_application_1\windows\flutter\ephemeral\flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /manifestinput:C:\Users\nieti\Desktop\flutter_application_1\windows\runner\runner.exe.manifest /DEBUG /PDB:"C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/flutter_application_1.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/flutter_application_1.lib" /MACHINE:X64  /machine:x64 flutter_application_1.dir\Debug\Runner.res
[        ]   flutter_application_1.dir\Debug\flutter_window.obj
[        ]   flutter_application_1.dir\Debug\main.obj
[        ]   flutter_application_1.dir\Debug\utils.obj
[        ]   flutter_application_1.dir\Debug\win32_window.obj
[        ]   flutter_application_1.dir\Debug\generated_plugin_registrant.obj
[ +217 ms]   flutter_application_1.vcxproj -> C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\Debug\flutter_application_1.exe
[   +6 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_application_1.dir\Debug\flutter_.637C0DF5.tlog\unsuccessfulbuild".
[        ]   Touching "flutter_application_1.dir\Debug\flutter_.637C0DF5.tlog\flutter_application_1.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj" (default targets).
[  +27 ms] Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (7) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_plugin.dir\Debug\flutter_.FFE93A7F.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[   +7 ms] ClCompile:
[        ]   All outputs are up-to-date.
[   +3 ms] Lib:
[        ]   All outputs are up-to-date.
[        ]   flutter_wrapper_plugin.vcxproj -> C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\Debug\flutter_wrapper_plugin.lib
[   +9 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_plugin.dir\Debug\flutter_.FFE93A7F.tlog\unsuccessfulbuild".
[        ]   Touching "flutter_wrapper_plugin.dir\Debug\flutter_.FFE93A7F.tlog\flutter_wrapper_plugin.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (default targets).
[   +7 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[   +7 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\ALL_BUILD.vcxproj" (default targets).
[   +6 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +58 ms] PostBuildEvent:
[        ]   setlocal
[        ]   "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
[        ]   if %errorlevel% neq 0 goto :cmEnd
[        ]   :cmEnd
[        ]   endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
[        ]   :cmErrorLevel
[        ]   exit /b %1
[        ]   :cmDone
[        ]   if %errorlevel% neq 0 goto :VCEnd
[        ]   :VCEnd
[  +59 ms]   -- Install configuration: "Debug"
[  +30 ms]   -- Up-to-date: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/icudtl.dat
[        ]   -- Up-to-date: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/flutter_windows.dll
[   +3 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets
[        ]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/AssetManifest.json
[   +1 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/FontManifest.json
[   +1 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/fonts
[   +1 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +8 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/NOTICES.Z
[   +1 ms]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/packages
[        ]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons
[        ]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets
[        ]   -- Installing: C:/Users/nieti/Desktop/flutter_application_1/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +13 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
[        ] Done Building Project "C:\Users\nieti\Desktop\flutter_application_1\build\windows\INSTALL.vcxproj" (default targets).
[  +24 ms] Build succeeded.
[        ]     0 Warning(s)
[        ]     0 Error(s)
[        ] Time Elapsed 00:00:11.21
[  +33 ms] Building Windows application... (completed in 12.1s)
[ +117 ms] Can't load AOT data from C:\Users\nieti\Desktop\flutter_application_1\build\windows\runner\Debug\data\app.so; no such file.
[        ] Unable to start engine without AOT data.
[  +18 ms] Failed to create view controller.
[   +5 ms] "flutter run" took 12,906ms.
[  +99 ms] ensureAnalyticsSent: 97ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

```

```
Analyzing flutter_application_1...
No issues found! (ran in 3.7s)
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.459, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.9.0-1.0.pre.459 at C:\flutter
    • Upstream repository git://github.com/flutter/flutter.git
    • Framework revision 31560ca68c (2 hours ago), 2022-01-22 23:35:19 -0500
    • Engine revision 51a54c2b72
    • Dart version 2.17.0 (build 2.17.0-48.0.dev)
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0 Preview 3.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.1.32113.165
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\nieti\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.62

```

</details>

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
Visual Studio 2022 17.1.0 ships a version of CMake whose generator
doesn't handle custom build commands correctly: instead of generating
one command per config that uses the correct `$<CONFIG>` value, it
generates multiple copies per configuration, one with each value of
`$<CONFIG>`, and only one of them is actually used. In practice, due to
the way VS resolves the incorrect duplication, it's always Release for a
flutter project, which causes the call to `assemble` to use the wrong
mode for debug builds, preventing them from launching.

This works around the generation bug, as a temporary measure until a
fixed version of Visual Studio is released, by rewriting the generated
project file to have the correct configuration value in each call.

This limits the workaround to just 17.1.0, as 17.1.1 should contain
a fix.

Fixes https://github.com/flutter/flutter/issues/97086

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 1]
```diff
@@ -74,6 +74,9 @@ Future<void> buildWindows(WindowsProject windowsProject, BuildInfo buildInfo, {
       buildDir: buildDirectory,
       sourceDir: windowsProject.cmakeFile.parent,
     );
+    if (visualStudio.displayVersion?.startsWith('17.1.') == true) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:77]: an imminently merging lint will require this to be written as `?? false` rather than `== true`

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 2]
```diff
@@ -335,3 +338,51 @@ void _writeGeneratedFlutterConfig(
   }
   writeGeneratedCmakeConfig(Cache.flutterRoot!, windowsProject, environment);
 }
+
+// Works around the Visual Studio CMake bug described in
+// https://github.com/flutter/flutter/issues/97086
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:343]: should we also link https://developercommunity.visualstudio.com/t/CMake-vcxproj-regression-in-1710-when/1670541 ?

Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:343]: Since the Flutter issue already links to the VS issue, I figured it was better to keep it simple here.

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 1 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/windows/build_windows.dart]: Thanks, changed.

**Comment by stuartmorgan** [comment]
I've changed the check to exactly 17.1.0, since we now have confirmation that the fix should be in 17.1.1.

@cbracken I'll leave it up to you whether you want to go forward with landing this, or just wait until 17.1.1 ships.

**Review by cbracken — APPROVED** [review]
lgtm for the change. I think we should land it given that it'll take some time for the fix to roll out and some further time for users to all pick this up -- e.g. I can imagine strict corporate update policies in some companies.

We should add a TODO here to strip this back out after some time limit. Maybe when we drop support for VS 2022.

**Comment by stuartmorgan** [comment]
TODO added.

**Comment by fzyzcjy** [comment]
Hi is there any updates?
