### PR TITLE
Use _ScaffoldLayout to position scroll-resizable appbars

### LINKED ISSUE #2923: Material Gallery app: Drawer is broken
The drawer in the gallery app is broken. It seems to pop below the header or something. It should pop over the toolbar.

cc @vlidholt @HansMuller

### PR DESCRIPTION
**Pull request by HansMuller**
Use _ScaffoldLayout to layout the appbar, even if it's going to be resized when the app is scrolled. As a consequence, the drawer is always stacked on top of the appbar.

Fixes https://github.com/flutter/flutter/issues/2923

### CODE REVIEW

**Comment by abarth** [comment]
LGTM
LGTM

File: examples/material_gallery/lib/gallery/home.dart [hunk 1]
```diff
@@ -50,13 +50,15 @@ class GalleryHome extends StatefulWidget {
 }
 
 class GalleryHomeState extends State<GalleryHome> {
-  final Key _scrollableKey = new UniqueKey();
+  final Key _homeKey = new ValueKey("Gallery Home");
+  final Key _listKey = new ValueKey("Gallery List");
```
Comment (Hixie) [inline examples/material_gallery/lib/gallery/home.dart]: `ValueKey<String>`

Comment (Hixie) [inline examples/material_gallery/lib/gallery/home.dart]: ValueKey is a bit dubious here. Shouldn't this just be a couple of static `UniqueKey`s?

**Comment by Hixie** [comment]
LGTM

File: examples/material_gallery/lib/gallery/home.dart (hunk 1 above)
Comment (HansMuller) [inline examples/material_gallery/lib/gallery/home.dart]: It should ValueKey<String>, I'll fix that. And I have a confession: the code inexplicably fails if I used UniqueKey here. I noticed because I was debugging with ValueKey and then reverted to UniqueKey and then things went awry.

I will try and distill a proper test case as a followup to this change.
