### PR TITLE
Remove tool crash git.io link shortener

### LINKED ISSUE #53140: `GitHubTemplateCreator` potentially leaks information to GitHub
The `flutter` tool has a `GitHubTemplateCreator` class that it uses to create a git.io shortened URL that searches GitHub for an error message.

The error message could potentially contain sensitive information (e.g. a `FileSystemException` will contain the path to the offending file).  Constructing a git.io shortened URL will save the original URL (with the embedded error message) to GitHub, and there does not seem to be any way to remove it.

### PR DESCRIPTION
**Pull request by jmagman**
git.io link shortener is dead, service responding 422. [GitHub has removed the service as of January 2022.](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/)

Remove the code that posts a request to have the link shortened.

Fixes https://github.com/flutter/flutter/issues/53140
See also https://github.com/flutter/flutter/issues/99572

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/test/src/fake_http_client.dart [hunk 1]
```diff
@@ -56,26 +56,6 @@ String _toMethodString(HttpMethod method) {
   }
 }
 
-/// Override the creation of all [HttpClient] objects with a zone injection.
-///
-/// This should only be used when the http client cannot be set directly, such as
-/// when testing `package:http` code.
-Future<void> overrideHttpClients(Future<void> Function() callback,  FakeHttpClient httpClient) async {
```
Comment (jmagman) [inline packages/flutter_tools/test/src/fake_http_client.dart:63]: Found dead code.

**Review by christopherfujino — APPROVED** [review]
RIP git.io

File: packages/flutter_tools/test/src/fake_http_client.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/src/fake_http_client.dart:63]: nice

**Review by Jasguerrero — APPROVED** [review]
LGTM
