### PR TITLE
[Engine][iOS] Cancel animation when recieved `UIKeyboardWillHideNotification` with duration 0.0

### LINKED ISSUE #112281: Save password prompt dismiss is pushing UI up and down
## Steps to Reproduce

1. Launch a flutter application with a login form (email/pw).
2. Fill out the form, submit and navigate to another page.
3. On iOS (I observed this on iOS 15+), dismiss the prompt.
** On the machine I ran, it currently has flutter 2 however, when upgraded to flutter 3, the same behavior is present. And appears only to affect iOS.

**Expected results:** The prompt should dismiss from the widget leaving the underlying page unmodified.

**Actual results:** After being dismissed, the contents on the widget is being pushed up and down.

<details>
<summary>Code sample</summary>
Simplified widgets to show the issue:

```
import 'package:exampleapp/widgets/simple_page.dart';
import 'package:flutter/material.dart';

class AutoFillPwWork extends StatefulWidget {
  const AutoFillPwWork({Key? key}) : super(key: key);

  @override
  State<AutoFillPwWork> createState() => _AutoFillPwWorkState();
}

class _AutoFillPwWorkState extends State<AutoFillPwWork> {
  final TextEditingController email = TextEditingController();
  final TextEditingController password = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Save PW iOS'),
        ),
        body: ListView(
          children: <Widget>[
            const Text('Login'),
            AutofillGroup(
              child: Column(
                children: <Widget>[
                  TextField(
                    controller: email,
                    autofillHints: const <String>[AutofillHints.email],
                  ),
                  TextField(
                    controller: password,
                    autofillHints: const <String>[AutofillHints.password],
                  ),
                ],
              ),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const SimplePage()),
                );
              },
              child: const Text('Push SimplePage'),
            ),
          ],
        ));
  }
}

import 'package:flutter/material.dart';

class SimplePage extends StatelessWidget {
  const SimplePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(
        title: const Text('Simple Page'),
      ),
      body: Center(
        child: Container(
          color: Colors.blue,
          child: const Text('Simple Page'),
        ),
      ),
    );
  }
}
```

</details>

<details>
Flutter (Channel unknown, 2.10.1, on macOS 11.6.8 20G730 darwin-x64, locale en-US)
    • Flutter version 2.10.1 at /Users/user/Development/flutter
    • Upstream repository unknown
    • Framework revision db747aa133 (8 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • iPhone (mobile) • ios            • iOS 15.7 19H12
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
</details>

https://user-images.githubusercontent.com/66581623/192004581-06dc62c9-1b97-43ac-9073-c94a578dbb8d.MP4

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/112281

The event log output shows that `UIKeyboardWillHideNotification` occurs immediately after `UIKeyboardWillShowNotification`. However, the animation is not cancelled in response to `UIKeyboardWillHideNotification`.

This PR adds animation cancellation processing in response to `UIKeyboardWillHideNotification` with duration 0.0.

https://github.com/user-attachments/assets/df0dbc6a-504b-476e-97ce-30e7ff40835f

test app: https://github.com/koji-1009/pm_behavior_test

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by vashworth — APPROVED** [review]
This looks good to me!

**Review by luckysmg — APPROVED** [review]
LGTM.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm [hunk 1]
```diff
@@ -779,6 +780,55 @@ - (void)testEnsureBottomInsetIsZeroWhenKeyboardDismissed {
   XCTAssertTrue(viewControllerMock.targetViewInsetBottom == 0);
 }
```
Comment (luckysmg) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm:782]: Maybe better to add one line comment for this test case, the PR link or issue link ^_^

Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm:782]: Thank you! I added by [74722a8](https://github.com/flutter/flutter/pull/164884/commits/74722a8ec1cef7e4cd45b8ea6d5e75034fd2ccec).

**Comment by koji-1009** [comment]
@chinmaygarde @vashworth 
Hello! I would like to know why Google testing is failing, could you please support me?
Due to the history of previous fixes being reverted, I would like to investigate if additional confirmation is required.
https://github.com/flutter/flutter/issues/112281#issuecomment-1952052471

**Comment by koji-1009** [comment]
Thank you!
