### PR TITLE
Fix CarouselView.weighted crashes when initlal viewportDimension is 0.0

### LINKED ISSUE #167621: CarouselView.weighted throws when given zero constraints
### Steps to reproduce

1. Run the code sample (debug or release mode. Without the zeroed SizedBox the issue is reproducible in release mode on Android).
2. Observe the error log.

### Expected results

No exception thrown.

### Actual results

Several exceptions in the error log.

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        // The issue is also reproducible without a zero width SixedBox.
        // In release mode, especially on Android, the initial viewport dimension
        // is usually zero.
        body: SizedBox(
          width: 0,
          child: CarouselView.weighted(
            flexWeights: <int>[1, 2],
            children: <Widget>[FlutterLogo(), FlutterLogo()],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console

════════ Exception caught by rendering library ═════════════════════════════════
The following UnsupportedError was thrown during performLayout():
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was:
    CarouselView CarouselView:file:///Users/bruno/Nevercode/investigationapp/lib/0%20-%20Investigate/Various/flutter_105630/flutter_105630_carousel_flutter_logo.dart:14:31

When the exception was thrown, this was the stack:
#0      double.toInt (dart:core-patch/double.dart)
#1      double.round (dart:core-patch/double.dart:196:34)
double.dart:196
#2      _RenderSliverWeightedCarousel._firstVisibleItemIndex (package:flutter/src/material/carousel.dart:918:69)
carousel.dart:918
#3      _RenderSliverWeightedCarousel.getMinChildIndexForScrollOffset (package:flutter/src/material/carousel.dart:981:21)
carousel.dart:981

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[!] Flutter (Channel master, 3.32.0-1.0.pre.200, on macOS 14.2.1 23C71 darwin-arm64, locale fr-FR)
    ! Upstream repository git@github.com:bleroux/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:bleroux/flutter.git to dismiss
      this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.1)
    ! CocoaPods 1.11.3 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see
      https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.99.3)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `CarouselView.weigthed` crashes due to given constraints being zero (which happen, for instance, when viewportDimension is 0.0).
 
At startup, a warm-up frame can be produced before the Flutter engine has reported the
initial view metrics. As a result, the first frame can be produced with a size of zero. In the context of CarouselView this leads to some problems mainly related to division by zero.

Similar to https://github.com/flutter/flutter/pull/167271 which addressed the same problem for `CarouselView`.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/167621

## Tests

Adds 3 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/carousel.dart [hunk 1]
```diff
@@ -905,6 +905,9 @@ class _RenderSliverWeightedCarousel extends RenderSliverFixedExtentBoxAdaptor {
   // (with weight 7), we leave some space before item 0 assuming there is another
   // item -1 as the first visible item.
   int get _firstVisibleItemIndex {
+    if (constraints.viewportMainAxisExtent == 0.0) {
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/carousel.dart:908]: Can we add a code comment to simply explain why we want to add this check here and below? Something like, If `constraints.viewportMainAxisExtent` is 0,  `firstChildExtent` will be 0 and cause division error.

**Review by QuncCccccc — APPROVED** [review]
NICE fix! LGTM. Thank you!
