### PR TITLE
Remove run in shell and add unit test for chrome launching

### LINKED ISSUE #38537: Enable having chrome launches persist the window locations between runs
We currently create a temporary directory to hold Chrome's user-data-dir each time we launch a web device:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/chrome.dart#L81

This means that the position of the chrome window won't be remembered between sessions.
The user will position it, but when they next launch their app, will need to reposition it.

We may instead want to write the the --user-data-dir to the .dart_tool/ dir in the project, or a persistent dir in their home directory?

cc @jonahwilliams

### LINKED ISSUE #39213: Flutter Web build crashed. Unable to start build daemon
## Steps to Reproduce

1. flutter create --web webby
2. flutter run -d chrome

Here is the gist of my main.dart (lib). [main.dart](https://gist.github.com/Akora-IngDKB/8b26a4db7779c74c547bd85c88b0abfa)

`flutter run -d chrome
Bad state: Unable to start build daemon.                                
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)       
<asynchronous suspension>
#2      BuildDaemonCreator._connectClient
(package:flutter_tools/src/build_runner/web_fs.dart:306:30)
#3      BuildDaemonCreator.startBuildDaemon
(package:flutter_tools/src/build_runner/web_fs.dart:271:46)
<asynchronous suspension>
#4      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:143:8)    
<asynchronous suspension>
#5      ResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:156:34)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:458:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:490:18)
#8      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#22     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)      
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)  
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)        
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)   

Failed to build application for the web.`

## Logs
flutter doctor -v

[√] Flutter (Channel master, v1.9.6-pre.4, on Microsoft Windows [Version 10.0.18362.175],
    locale en-GH)
    • Flutter version 1.9.6-pre.4 at C:\flutter
    • Framework revision 17813975a9 (24 hours ago), 2019-08-24 17:06:36 -0400
    • Engine revision deca2c0da8
    • Dart version 2.5.0
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)  
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.100

• No issues found!

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes chrome launching on windows by removing runInShell. Places the user data directory under .dart_tool and removes code that deletes it on tear down.

Fixes https://github.com/flutter/flutter/issues/39213 
Fixes https://github.com/flutter/flutter/issues/38537

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -76,9 +75,11 @@ class ChromeLauncher {
   ///
   /// `headless` defaults to false, and controls whether we open a headless or
   /// a `headfull` browser.
-  Future<Chrome> launch(String url, { bool headless = false }) async {
+  ///
+  /// `skipCheck` does not attempt to make a devtools connection before returning.
+  Future<Chrome> launch(String url, { bool headless = false, bool skipCheck = false }) async {
     final String chromeExecutable = findChromeExecutable();
-    final Directory dataDir = fs.systemTempDirectory.createTempSync();
+    final Directory dataDir = fs.directory('.dart_tool');
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/chrome.dart]: Should this be something more specific?

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Yeah, it fills up the folder with junk, will fix

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Fixed

**Comment by jonahwilliams** [comment]
Ignoring add2app-macos  which was disabled for repeated failures. Will land once build goes green

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 2]
```diff
@@ -116,36 +121,37 @@ class ChromeLauncher {
...
-    } catch (e) {
-      await chrome.close();
-      throwToolExit(
-          'Unable to connect to Chrome debug port: ${chrome.debugPort}\n $e');
+    if (!skipCheck) {
+      try {
+        await chrome.chromeConnection.getTabs();
+      } catch (e) {
+        await chrome.close();
+        print('here');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/chrome.dart]: stray debug print

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 3]
```diff
@@ -198,19 +201,5 @@ class Chrome {
     chromeConnection.close();
     _process?.kill();
     await _process?.exitCode;
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/chrome.dart]: It doesn't look like stdout is drained anywhere.

File: packages/flutter_tools/test/general.shard/web/chrome_test.dart [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+          utf8.encode('\n\nDevTools listening\n\n')
+        ]),
+      );
+    });
+
+    await chromeLauncher.launch('example_url', skipCheck: true);
+  }));
+}
+
+class MockProcessManager extends Mock implements ProcessManager {}
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/web/chrome_test.dart]: The MockProcessManager defined in mocks.dart looks like it does what you want.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Fixed in https://github.com/flutter/flutter/pull/39751

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart]: I didn't think that I needed to, since I don't listen to it. Shouldn't the conversion to a Future (for stderr) deal with draining?

Comment (zanderso) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Yup, that'll work.
