### PR TITLE
Do not crash when dragging ReorderableListView  with two fingers simultaneously

### LINKED ISSUE #88191: ReorderableListView can't cope with dragging with two fingers simultaneously and breaks the app
## Steps to Reproduce

Using the very basic code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.dark,
      home: Scaffold(
        body: SafeArea(
          child: SampleList(),
        ),
      ),
    );
  }
}

class SampleList extends StatefulWidget {
  @override
  _SampleListState createState() => _SampleListState();
}

class _SampleListState extends State<SampleList> {
  final items = [
    'AAAAA',
    'BBBBB',
    'CCCCC',
  ];

  @override
  Widget build(BuildContext context) {
    return ReorderableListView.builder(
      itemCount: items.length,
      onReorder: (oldIndex, newIndex) {
        final movedItem = items.removeAt(oldIndex);
        final insertionIndex = newIndex > oldIndex ? newIndex - 1 : newIndex;
        items.insert(insertionIndex, movedItem);
        setState(() {});
      },
      itemBuilder: (context, index) {
        final item = items[index];

        return ListTile(
          key: ObjectKey(item),
          title: Text(item),
        );
      },
    );
  }
}
```
0. Reproducible 100% here on Android and iOS devices in release mode.
1. Run it using `flutter run --release` on a device. **This is very important, use the release mode.**
2. Drag and drop any item in the list using just one finger - all works fine.
3. Drag and drop any item in the list using two fingers on the same item - the UI breaks in different weird ways - sometimes items disappear, sometimes the list gets covered with a whitish overlay (easily visible in dark mode hence the sample app uses it), sometimes there is a huge gap between items after dropping, sometimes the app gets completely broken and cannot be used any more. Try a few times.

**Expected results:**

I expect the list not to break. I don't actually need the 'two finger drag' for anything, I just came across this issue by accident and I think it should break the app beyond recovery.

**Actual results:**

The UI breaks in different weird ways - sometimes items disappear, sometimes the list gets covered with a whitish overlay (easily visible in dark mode hence the sample app uses it), sometimes there is a huge gap between items after dropping, sometimes the app gets completely broken and cannot be used any more.

<details>
  <summary>Logs</summary>

When run in release mode on Pixel 3XL (I don't see any errors on iOS in release mode), this gets thrown:
```
I/flutter (22963): Null check operator used on a null value
I/flutter (22963): #0      SliverReorderableListState._dropCompleted (package:flutter/src/widgets/reorderable_list.dart:643)
I/flutter (22963): #1      _DragInfo._dropCompleted (package:flutter/src/widgets/reorderable_list.dart:1163)
I/flutter (22963): #2      _DragInfo.startDrag.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:1134)
I/flutter (22963): #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
I/flutter (22963): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:812)
I/flutter (22963): #5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:828)
I/flutter (22963): #6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238)
I/flutter (22963): #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
I/flutter (22963): #8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058)
I/flutter (22963): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
I/flutter (22963): #10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056)
I/flutter (22963): #11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:977)
I/flutter (22963): #15     _invoke1 (dart:ui/hooks.dart:182)
I/flutter (22963): #16     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:237)
I/flutter (22963): #17     _beginFrame (dart:ui/hooks.dart:114)
I/flutter (22963): (elided 3 frames from dart:async)
```

When run in debug mode on Pixel 3XL or iPhone XS:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/reorderable_list.dart': Failed assertion: line 579 pos 12: '_dragInfo
== null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SliverReorderableListState._dragStart (package:flutter/src/widgets/reorderable_list.dart:579:12)
#3      MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:277:61)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:277:14)
#6      MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:267:48)
#7      _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:496:14)
#8      MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:267:11)
#9      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:264:12)
#10     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:223:9)
#11     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#12     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:69:18)
#13     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:482:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

Handler: "onStart"
Recognizer:
  DelayedMultiDragGestureRecognizer#d4638
════════════════════════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze` output:
```
Analyzing sample_app...                                                    
No issues found! (ran in 5.2s)
```

`flutter doctor` output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #88191

When the two pointers start dragging simultaneously, it will happen that two MultiDragGestureRecognizer wins simultaneously and lead to an assertion(assert(_dragInfo == null);).
Fix solution: If a recognizer is created by another pointer, it will be destroyed before adding the new recognizer.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -579,12 +580,17 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
     setState(() {
       if (_dragInfo != null) {
         cancelReorder();
+      } else if (_recognizer != null && _recognizerPointer != event.pointer) {
+        _recognizer!.dispose();
+        _recognizer = null;
+        _recognizerPointer = null;
```
Comment (darrenaustin) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:586]: If a second gesture comes in here, wouldn't we want to also cancel the previous reorder? If we aren't going to cancel the current drag, then wouldn't it make more sense to ignore the new gesture and wait for the first one to complete instead of reseting the recognizer to the new one? They may be trying to drag different items.

File: packages/flutter/test/material/reorderable_list_test.dart [hunk 2]
```diff
@@ -1471,6 +1471,52 @@ void main() {
     expect(items.take(8), orderedEquals(<int>[0, 1, 2, 3, 4, 5, 6, 7]));
   });
 
+  // Regression test for https://github.com/flutter/flutter/issues/88191
+  testWidgets('Do not crash when dragging with two fingers simultaneously ', (WidgetTester tester) async {
```
Comment (darrenaustin) [inline packages/flutter/test/material/reorderable_list_test.dart:1475]: Looks good and thanks for including a test. However, as this should be in `test/widgets/reorderable_list_test.dart` instead of the material test as this testing the base widget's functionality and isn't specific to the material ReorderableListView.

**Review by darrenaustin — CHANGES_REQUESTED** [review]
@xu-baolin thanks for the fix. Sorry about the delay on the review.

Looks good, but I had a couple of questions and a request below. Thx.

File: packages/flutter/test/material/reorderable_list_test.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/test/material/reorderable_list_test.dart:1475]: You are right!
Will move it.

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/88508

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 1 above)
Comment (darrenaustin) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:586]: Fair enough. I missed that this is only valid for the case where _dragInfo is null. Sounds good. Thx.

**Review by darrenaustin — APPROVED** [review]
LGTM. Thanks!
