### PR TITLE
moving the left handle automatically scrolls EditableText to the right handle, which doesn't happen on native

### LINKED ISSUE #105821: When SelectionEndHandle is hidden and SelectionStartHandle is changed, the view goes to SelectionEndHandle.
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Show text selection
3. hide the handle at end
4. move the handle at start

**Expected results:** 
this is native behavior

https://user-images.githubusercontent.com/52235899/173178972-c2e04b0f-0353-4a23-a611-d33b9c6d0ced.mov

**Actual results:** 
move to the end of the handle automatically. (the opposite is ok)

https://user-images.githubusercontent.com/52235899/173178897-41b5f577-89d9-4038-b62b-50abd2e72ac0.mov

<details>
<summary>Code sample</summary>

```dart

import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final TextEditingController controller = TextEditingController(
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.");
    return MaterialApp(
      home: Directionality(
        textDirection: TextDirection.ltr,
        child: MediaQuery(
          data: const MediaQueryData(size: Size(800.0, 600.0)),
          child: Align(
            alignment: Alignment.bottomCenter,
            child: Material(
              child: Center(
                child: SizedBox(
                  width: 200,
                  child: TextField(
                    style: const TextStyle(fontSize: 32, height: 1),
                    controller: controller,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel upstream/master, 3.1.0-0.0.pre.1211, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1211 at /Users/takashi/fvm/versions/pr
    • Upstream repository remotes
    • Framework revision 9d46e7800f (81 minutes ago), 2022-06-09 23:43:08 -0400
    • Engine revision a4cdb1e232
    • Dart version 2.18.0 (build 2.18.0-174.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/takashi/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/takashi/Library/Android
    • ANDROID_SDK_ROOT = /Users/takashi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • C04AC033-BB4D-46A8-849A-E330D54A1538 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61
    ! Error: TAKASHI is not connected. Xcode will continue when TAKASHI is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by takassh**
fixes https://github.com/flutter/flutter/issues/105821

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by takassh** [comment]
@chunhtai 
@justinmc 
please review!

**Comment by takassh** [comment]
cc @chunhtai

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -538,12 +538,25 @@ class TextSelectionOverlay {
   }
 
   void _handleSelectionHandleChanged(TextSelection newSelection, {required bool isEnd}) {
-    final TextPosition textPosition = isEnd ? newSelection.extent : newSelection.base;
+    final TextPosition bringTextPosition;
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.iOS:
+      case TargetPlatform.macOS:
+        bringTextPosition = newSelection.extent;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:545]: This is because MacOS/iOS always make the dragged handle the extentHandle (https://github.com/flutter/flutter/pull/105069), right?  Maybe add a comment about that.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -538,12 +538,25 @@ class TextSelectionOverlay {
   }
 
   void _handleSelectionHandleChanged(TextSelection newSelection, {required bool isEnd}) {
-    final TextPosition textPosition = isEnd ? newSelection.extent : newSelection.base;
+    final TextPosition bringTextPosition;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:541]: Nit: Maybe `positionToView` or something like that is more clear?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 3]
```diff
@@ -3623,6 +3623,93 @@ void main() {
     );
   });
 
+  testWidgets(
+    'Can drag the left handle while the right handle disappears',
+    (WidgetTester tester) async {
+      // text is longer than textfield width.
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3629]: Capital letter and period for this and all of the comments below.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 4]
```diff
@@ -3623,6 +3623,93 @@ void main() {
     );
   });
 
+  testWidgets(
+    'Can drag the left handle while the right handle disappears',
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3627]: Nit: Maybe this is more clear, but it's up to you: "while the right handle disappears" => "while the right handle remains off-screen"

Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart:3627]: Same thing for the other test with a similar description below.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 5]
```diff
@@ -3623,6 +3623,93 @@ void main() {
...
+          expect(controller.selection.extentOffset, testValue.length);
+          break;
+      }
+
+      // the scroll area of text field should not move.
+      expect(scrollController.offset, beforeScrollOffset);
+    },
+    variant: TargetPlatformVariant.all(),
+  );
+
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3712]: Should you also add a test for the opposite?  The right handle is dragged while the left handle is off-screen.

**Review by justinmc — COMMENTED** [review]
Thanks for fixing this!

My main concern at this point is just that the `isEnd` parameter in methods like `_handleSelectionChanged` isn't very clear at first glance.  It makes sense in `_handleSelectionHandleChanged` to describe which handle changed, but elsewhere it's not clear what it means.

Maybe it's just the naming that needs to change.  You could call it `handleToView` and set it to an enum, either `baseHandle` or `extentHandle`.  Something like that?

CC @antholeole who I think was looking at a somewhat similar issue.

**Comment by antholeole** [comment]
This whole comment assumes that there's no way to drag the right handle without it already being in view. If that's a wrong assumption, then disregard :).

I wonder if this is the correct solution for this problem... The reason why this is not a problem for the second selection handle is that the call to [`selectionDelegate.bringIntoView` in `_handleSelectionHandleChanged`](https://github.com/flutter/flutter/blob/213bf37a4dad872ca0844100c8f926cd2e9989f0/packages/flutter/lib/src/widgets/text_selection.dart#L546) always does nothing since dragging the second selection handle means the end of the selection extent is already in view. It gets called for both left and right handles, but never ever does anything for the right handle. 

if we know that it shouldn't be called when dragging the left handle, and never does anything when dragging the right handle - do we need this call at all? Can't we just delete it and all is well?

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 6]
```diff
@@ -526,7 +526,7 @@ class _SelectableTextState extends State<SelectableText> implements TextSelectio
 
   TextSelection? _lastSeenTextSelection;
 
-  void _handleSelectionChanged(TextSelection selection, SelectionChangedCause? cause) {
+  void _handleSelectionChanged(TextSelection selection, SelectionChangedCause? cause, {bool isEnd = true}) {
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/lib/src/material/selectable_text.dart:529]: This issue is not related to `SelectableText`, but it uses `SelectionChangedCallback` and `editable_text` uses it as well, so I had to add the boolean flag here.
how can I change it?

File: packages/flutter/lib/src/material/text_field.dart [hunk 7]
```diff
@@ -1069,7 +1069,8 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
       case TargetPlatform.fuchsia:
       case TargetPlatform.android:
         if (cause == SelectionChangedCause.drag) {
-          _editableText?.bringIntoView(selection.extent);
+          _editableText
+              ?.bringIntoView(isEnd ? selection.extent : selection.base);
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/lib/src/material/text_field.dart]: I think we can replace `?` with `!` as other codes. fixed it.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 8]
```diff
@@ -3001,7 +3001,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       return;
     }
 
-    _formatAndSetValue(value, cause, userInteraction: true);
+    _formatAndSetValue(value, cause, userInteraction: true, isEnd:isEnd);
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/lib/src/widgets/editable_text.dart]: added

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 9]
```diff
@@ -3623,6 +3623,93 @@ void main() {
...
+          home: Center(
+            child: CupertinoTextField(
+              dragStartBehavior: DragStartBehavior.down,
+              controller: controller,
+              scrollController: scrollController,
+            ),
+          ),
+        ),
+      );
+
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart:3611]: removed.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 3 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: fixed all

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (takassh) [reply packages/flutter/lib/src/widgets/text_selection.dart]: agree

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 5 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart:3752]: sure. added.

**Comment by takassh** [comment]
@justinmc 
thank you for review :) I fixed it based on your review.
but I'm not sure where I should write enum. Where is the most optimal location to write enum?

**Comment by takassh** [comment]
@antholeole 
thank you for your comments!
Why does`bringIntoView` exist there originally? actually, I can remove the line and it passed all tests in my local...

**Comment by justinmc** [comment]
If we go with @antholeole's approach, can we get rid of the idea of `isEnd` altogether?  That would make things really simple.

**Comment by antholeole** [comment]
> @antholeole thank you for your comments! Why does`bringIntoView` exist there originally? actually, I can remove the line and it passed all tests in my local...

@takassh It was an old implementation of edge scrolling, I think. Edge scrolling was moved elsewhere, but this line was overlooked. I think it is the sole culprit of #105821 . When you said "passes all tests" are you including the tests you wrote for this PR? If so, I think it would be best (i.e. smallest footprint) if this PR was just deleting that line, and the tests you wrote.

**Comment by takassh** [comment]
@justinmc @antholeole 
I see. thank you.
yeah, I said we could remove [`selectionDelegate.bringIntoView` in `_handleSelectionHandleChanged`](https://github.com/flutter/flutter/blob/213bf37a4dad872ca0844100c8f926cd2e9989f0/packages/flutter/lib/src/widgets/text_selection.dart#L546).
however, we can't remove other `bringIntoView` to pass tests. e.g. [_editableText?.bringIntoView in _handleSelectionChanged](https://github.com/flutter/flutter/blob/9f4b9bfd494a209f5dc2e0cf3cec6322be4c5b57/packages/flutter/lib/src/material/text_field.dart#L1072).

it seems [`selectionDelegate.userUpdateTextEditingValue` in `_handleSelectionHandleChanged`](https://github.com/flutter/flutter/blob/213bf37a4dad872ca0844100c8f926cd2e9989f0/packages/flutter/lib/src/widgets/text_selection.dart#L542) internally calls other `bringIntoView` also. (in short , as a result, `_handleSelectionHandleChanged` is calling `bringIntoView` two times)
therefore, anyway I think we need some flag like `isEnd` to tell which handle is dragged now.

**Comment by antholeole** [comment]
@takassh So, just to be clear, when you remove the line that I mentioned, https://github.com/flutter/flutter/issues/105821 still happens? I removed that line and this is the behavior I get:

https://user-images.githubusercontent.com/48811365/175373354-d8f78799-61bf-42ee-977a-df2540ea39a1.mov

It looks like it fixes the problem for me, unless I'm testing wrong.

**Comment by antholeole** [comment]
Looks like you're right! The further calls are needed on platforms not iOS / macOS. thanks for this!

**Comment by takassh** [comment]
@antholeole 
> So, just to be clear, when you remove the line that I mentioned, https://github.com/flutter/flutter/issues/105821 still happens?

yes 

@justinmc 
so I think we need the enum. where should I write enum definition?

**Comment by antholeole** [comment]
@justinmc what about changing ‘SelectionChangedCause.drag’ to something like SelectionChangedCause.dragLeftHandle and SelectionChangedCause.dragRightHandle? 

Just a thought!

**Comment by takassh** [comment]
@justinmc
any updates?
Is there anything I can do?

**Comment by antholeole** [comment]
@takassh I'll be taking over the review on this one :) It looks almost done though, good job! I'll look it over right now.

**Review by antholeole — COMMENTED** [review]
Can we replace all instances of "IsEnd" with something like `TextSelectionHandle`? This will make maintinance easier in the long run. `isEnd` unfortunately does not feel verbose enough.

**Comment by antholeole** [comment]
Suggested edit:
```diff
diff --git a/packages/flutter/lib/src/widgets/text_selection.dart b/packages/flutter/lib/src/widgets/text_selection.dart
index 30f96187ba..e59d176fd9 100644
--- a/packages/flutter/lib/src/widgets/text_selection.dart
+++ b/packages/flutter/lib/src/widgets/text_selection.dart
@@ -2286,6 +2286,11 @@ class ClipboardStatusNotifier extends ValueNotifier<ClipboardStatus> with Widget
   }
 }
 
+enum TextSelectionHandleSide {
+  BaseHandle,
+  ExtentHandle
+}
+
 /// An enumeration of the status of the content on the user's clipboard.
 enum ClipboardStatus {
   /// The clipboard content can be pasted, such as a String of nonzero length.

```

**Comment by takassh** [comment]
@antholeole 
thank you for reviewing!
I fixed `bool IsEnd` to `TextSelectionDraggedHandleSide handleSide`.

however, I encountered following CI failure, and it seems not to be my failure, because I didn't touch about `flutter_logo` in this PR.

```
| Warning - golden differed less than .06% (0.006202083333333334%), ignoring failure but producing output
| Golden "golden_widget/flutter_logo.string.color_filter.png": Pixel test failed, 0.62% diff detected.
| Failure feedback can be found at /b/s/w/ir/x/t/flutter_customer_testing.flutter_svg.DAWBDP/tests/test/failures
...
| Warning - golden differed less than .06% (0.008170833333333334%), ignoring failure but producing output
| Golden "golden_widget/flutter_logo.string.color_filter.blendmode_color.png": Pixel test failed, 0.82% diff detected.
| Failure feedback can be found at /b/s/w/ir/x/t/flutter_customer_testing.flutter_svg.DAWBDP/tests/test/failures
```

Could you check the CI failure?

File: packages/flutter/lib/src/services/text_input.dart [hunk 10]
```diff
@@ -1016,6 +1016,16 @@ enum SelectionChangedCause {
   scribble,
 }
 
+/// An enumeration of the status of the dragged handle.
```
Comment (antholeole) [inline packages/flutter/lib/src/services/text_input.dart:1019]: how about: 
"An enum to differentiate between handles.

Used when an action may have different results based on the handle side."

File: packages/flutter/lib/src/services/text_input.dart [hunk 11]
```diff
@@ -1016,6 +1016,16 @@ enum SelectionChangedCause {
...
+/// For iOS and macOS, this status is always `extentHandle` by this change https://github.com/flutter/flutter/pull/105069
+enum TextSelectionDraggedHandleSide {
+  /// The dragged handle is base handle.
```
Comment (antholeole) [inline packages/flutter/lib/src/services/text_input.dart:1022]: remove dragged here and below

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 12]
```diff
@@ -534,16 +534,30 @@ class TextSelectionOverlay {
...
   }
 
-  void _handleSelectionHandleChanged(TextSelection newSelection, {required bool isEnd}) {
-    final TextPosition textPosition = isEnd ? newSelection.extent : newSelection.base;
+  void _handleSelectionHandleChanged(TextSelection newSelection, {required TextSelectionDraggedHandleSide handleSide}) {
+    final TextPosition positionToView;
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.iOS:
+      case TargetPlatform.macOS:
+        // For iOS and macOS, extent always means the dragged handle by this change https://github.com/flutter/flutter/pull/105069
```
Comment (antholeole) [inline packages/flutter/lib/src/widgets/text_selection.dart:545]: Instead of "by this change" perhaps we do something like:
// On iOS and macOS, extent is always the dragged handle
// (PR LINK IN PARENS).

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 13]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+        case TargetPlatform.windows:
+          expect(controller.selection.baseOffset, 25);
+          expect(controller.selection.extentOffset, testValue.length);
+          break;
+      }
+
+      // The scroll area of text field should not move.
+      expect(scrollController.offset, beforeScrollOffset);
+    },
+    variant: TargetPlatformVariant.mobile(),
```
Comment (antholeole) [inline packages/flutter/test/cupertino/text_field_test.dart:3787]: why on mobile only?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 14]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+      final RenderEditable renderEditable = findRenderEditable(tester);
+      final List<TextSelectionPoint> endpoints = globalize(
+        renderEditable.getEndpointsForSelection(selection),
+        renderEditable,
+      );
+      expect(endpoints.length, 2);
+
+      // Left handle should appear.
+      expect(endpoints[0].point.dx, isPositive);
+      // Right handle should remains off-screen.
```
Comment (antholeole) [inline packages/flutter/test/cupertino/text_field_test.dart:3752]: I like this alot! This is smart to expect on, to make sure that our setup is completed properly.

File: packages/flutter/test/material/text_field_test.dart [hunk 15]
```diff
@@ -2217,6 +2217,173 @@ void main() {
...
+        case TargetPlatform.windows:
+          expect(controller.selection.baseOffset, 25);
+          expect(controller.selection.extentOffset, testValue.length);
+          break;
+      }
+
+      // the scroll area of text field should not move.
+      expect(scrollController.offset, beforeScrollOffset);
+    },
+    variant: TargetPlatformVariant.mobile(),
```
Comment (antholeole) [inline packages/flutter/test/material/text_field_test.dart:2306]: Why mobile?

**Review by antholeole — COMMENTED** [review]
Overall, looks good! Thanks for making the changes. @justinmc might have some more nits but after you make my changes you get my approval stamp :)

I re-ran CI, hopefully it passes. I've had the same failure on my PR's, seems the test is flaky.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 13 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: I think the handle is shown on only mobile.
That's why I'm using `TargetPlatformVariant.mobile()`

**Comment by takassh** [comment]
@antholeole 
wow, thank you for quick review!!

Code was changed based on your comment without https://github.com/flutter/flutter/pull/105836#discussion_r925632358

**Review by antholeole — DISMISSED** [review]
LGTM! Thanks for being patient with this one, I know it had a ton of rounds.

I'm going to wait for Justin to sign off on it since he's worked a ton more with this code, but I think this is looking good.

**Comment by antholeole** [comment]
how do we feel about configuration objects? Currently I’m just passing around a raw WidgetBuilder as a loupeBuilder, but there may be additional configuration to the loupe down the line that may be added (for instance, currently it’s hard coded that on android the loupe should see the handles but on iOS it shouldn’t - someone who god forbid wants to build their own loupe may want control over that). TextField already has 54 parameters, spamming it with loupe parameters does not feel ideal. Would it be flutter-y to create a LoupeConfiguration object that, for now, holds a small amount of parameters for a little bit of future proofing? Or does it hurt discoverability too much?

Mostly cc @justinmc but also cc @Renzo-Olivares @LongCatIsLooong

**Review by justinmc — COMMENTED** [review]
It looks like there are some test failures, but I think they aren't related to the changes in this PR...  Could you try merging master into this PR?  If that doesn't work, you may also need to squash all of your commits into one.

I like the `handleSide` approach as opposed to `isEnd`, but I'm still not sure about adding `handleSide` to certain methods.  It makes a lot of sense in things like _handleSelectionHandleChanged, but in other methods it's not clear what it would refer to.  For example userUpdateTextEditingValue and _formatAndSetValue.  Even _handleSelectionChanged, what if the selection changed completely and both handles moved?

Maybe if we rename it to `handleToView` or something like that?

**Comment by takassh** [comment]
Because of combing all commits into one, it seems github requested many reviewers... sorry.

File: packages/flutter/lib/src/services/text_input.dart [hunk 16]
```diff
@@ -1016,6 +1016,16 @@ enum SelectionChangedCause {
   scribble,
 }
 
+/// An enum to differentiate between handles.
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/lib/src/services/text_input.dart]: fixed

File: packages/flutter/lib/src/services/text_input.dart [hunk 17]
```diff
@@ -1016,6 +1016,16 @@ enum SelectionChangedCause {
...
+/// Used when an action may have different results based on the handle side.
```
[the remark this answers is not in the document]
Comment (takassh) [reply packages/flutter/lib/src/services/text_input.dart:1021]: fixed

**Comment by takassh** [comment]
@justinmc 
Thank you for your review!
I fixed code based on your comments. And I combined all commits into one to pass test.

I think, finally, we're ready to merge code.

File: packages/flutter/lib/src/services/text_input.dart [hunk 18]
```diff
@@ -1033,7 +1044,7 @@ mixin TextSelectionDelegate {
   /// * [EditableTextState.userUpdateTextEditingValue]: an implementation that
   ///   applies additional pre-processing to the specified [value], before
   ///   updating the text editing state.
-  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
+  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause, {TextSelectionHandleSide handleToView = TextSelectionHandleSide.extentHandle});
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:1047]: Can you document handleToView in the doc comments here?  And if there's anywhere else that it is exposed publicly.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 19]
```diff
@@ -753,18 +753,33 @@ class TextSelectionOverlay {
...
-  void _handleSelectionHandleChanged(TextSelection newSelection, {required bool isEnd}) {
-    final TextPosition textPosition = isEnd ? newSelection.extent : newSelection.base;
+  void _handleSelectionHandleChanged(TextSelection newSelection, {required TextSelectionHandleSide handleToView}) {
+    final TextPosition positionToView;
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.iOS:
+      case TargetPlatform.macOS:
+        // On iOS and macOS, extent is always the dragged handle.
+        // (https://github.com/flutter/flutter/pull/105069)
+        positionToView = newSelection.extent;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:768]: It seems surprising to me that passing handleToView won't have any effect on iOS and Mac.  Is there any other way to organize this to avoid that?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 20]
```diff
@@ -753,18 +753,33 @@ class TextSelectionOverlay {
...
+        positionToView = handleToView == TextSelectionHandleSide.extentHandle ? newSelection.extent : newSelection.base;
+        break;
+    }
     selectionDelegate.userUpdateTextEditingValue(
       _value.copyWith(selection: newSelection),
       SelectionChangedCause.drag,
+      handleToView: handleToView,
     );
-    selectionDelegate.bringIntoView(textPosition);
+    selectionDelegate.bringIntoView(positionToView);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:782]: It looks like bringIntoView may also be called as a result of userUpdateTextEditingValue.  Would it be possible to avoid calling it twice like that?

I know that we were probably doing that even before your PR...

**Review by justinmc — COMMENTED** [review]
I just wanted to throw out some more ideas here and in the comments below, to see what you think.

Would it be possible to infer the handle to view instead of passing along the parameter everywhere?  Like if you checked if the baseOffset or extentOffset had changed between the old and new selections.

**Comment by takassh** [comment]
@justinmc 
I reviewed my changes from your comments and I found another solution.
Especially, I fixed it to infer the handle, and remove the parameter `handleToView` and `TextSelectionHandleSide` enum.
I think it's well organized.

Please review it again 👀

File: packages/flutter/lib/src/services/text_input.dart (hunk 18 above)
Comment (takassh) [reply packages/flutter/lib/src/services/text_input.dart]: I removed all `handleToView`.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 19 above)
Comment (takassh) [reply packages/flutter/lib/src/widgets/text_selection.dart]: I removed this `switch-case`.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 20 above)
Comment (takassh) [reply packages/flutter/lib/src/widgets/text_selection.dart]: I removed this line.

**Comment by takassh** [comment]
@justinmc
I reviewed my changes from your comments and I found another solution.
Especially, I fixed it to infer the handle and remove the parameter `handleToView` and `TextSelectionHandleSide` enum.
I think it's well organized.

**Comment by takassh** [comment]
@justinmc 
sorry for inconvenience.
if you have time, please take a look.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 21]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+              dragStartBehavior: DragStartBehavior.down,
+              controller: controller,
+              scrollController: scrollController,
+            ),
+          ),
+        ),
+      );
+
+      // Move to the left edge.
+      scrollController.jumpTo(0);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3811]: Nit: Shouldn't it already be scrolled to zero?  Or I could be wrong...

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 22]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+            child: CupertinoTextField(
+              dragStartBehavior: DragStartBehavior.down,
+              controller: controller,
+              scrollController: scrollController,
+            ),
+          ),
+        ),
+      );
+
+      await tester.enterText(find.byType(CupertinoTextField), testValue);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3724]: Nit: The controller already contains the text from `testValue`.  Is this enterText redundant? As well as the two pumps below.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 23]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+      await tester.pump();
+      await tester.pump(const Duration(milliseconds: 200));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3726]: If you do decide to keep enterText and still need to pump, can you consolidate these?  Ideally if you could just use one `pumpAndSettle` that would be best.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 24]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+
+      // Double tap 'b' to show handles.
+      final Offset bPos = textOffsetToPosition(tester, testValue.indexOf('b'));
+      await tester.tapAt(bPos);
+      await tester.pump(const Duration(milliseconds: 50));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3731]: Also here, could you replace this with pumpAndSettle?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 25]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+        ),
+      );
+
+      // Move to the left edge.
+      scrollController.jumpTo(0);
+      await tester.pumpAndSettle();
+
+      await tester.enterText(find.byType(CupertinoTextField), testValue);
+      await tester.pump();
+      await tester.pump(const Duration(milliseconds: 200));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3816]: Same as above: Could these pumps be just pumpAndSettle?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 26]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+
+      // Double tap 'a' to show handles.
+      final Offset aPos = textOffsetToPosition(tester, testValue.indexOf('a'));
+      await tester.tapAt(aPos);
+      await tester.pump(const Duration(milliseconds: 50));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3821]: Same as above: Could this be pumpAndSettle?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 27]
```diff
@@ -3701,6 +3701,167 @@ void main() {
...
+            ),
+          ),
+        ),
+      );
+
+      // Move to the left edge.
+      scrollController.jumpTo(0);
+      await tester.pumpAndSettle();
+
+      await tester.enterText(find.byType(CupertinoTextField), testValue);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:3814]: Same as above: Maybe entering this text is redundant and you don't need it?

File: packages/flutter/test/material/text_field_test.dart [hunk 28]
```diff
@@ -2218,6 +2218,173 @@ void main() {
...
+              ),
+            ),
+          ),
+        ),
+      );
+
+      // Text is longer than textfield width.
+      const String testValue =
+          'aaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbb';
+      await tester.enterText(find.byType(TextField), testValue);
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2245]: In this case, you do need enterText, because testValue isn't set as the `text` in your `controller`.

Or you could potentially get rid of this and put it in the controller, like in your cupertino test above.

File: packages/flutter/test/material/text_field_test.dart [hunk 29]
```diff
@@ -2218,6 +2218,173 @@ void main() {
...
+      await skipPastScrollingAnimation(tester);
+
+      // Double tap 'b' to show handles.
+      final Offset bPos = textOffsetToPosition(tester, testValue.indexOf('b'));
+      await tester.tapAt(bPos);
+      await tester.pump(const Duration(milliseconds: 50));
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2251]: Same as above in the cupertino test: Could this be pumpAndSettle?  Here and elsewhere below where you use a Duration.

File: packages/flutter/test/material/text_field_test.dart [hunk 30]
```diff
@@ -2218,6 +2218,173 @@ void main() {
...
+        case TargetPlatform.android:
+        case TargetPlatform.fuchsia:
+        case TargetPlatform.linux:
+        case TargetPlatform.windows:
+          expect(controller.selection.baseOffset, toOffset);
+          expect(controller.selection.extentOffset, testValue.length);
+          break;
+      }
+
+      // the scroll area of text field should not move.
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2305]: Capital T here.

File: packages/flutter/test/material/text_field_test.dart [hunk 31]
```diff
@@ -2218,6 +2218,173 @@ void main() {
...
+      await tester.pump();
+      await gesture.moveTo(newHandlePos);
+      await tester.pump();
+      await gesture.up();
+      await tester.pump();
+
+      expect(controller.selection.baseOffset, 0);
+      expect(controller.selection.extentOffset, toOffset);
+
+      // the scroll area of text field should not move.
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2383]: Capital T.

**Review by justinmc — COMMENTED** [review]
I think this approach looks great!  As long as the tests pass.  You've greatly simplified the code by removing the isEnd etc. parameters, and by consolidating the bringIntoView calls in one place.

Mostly just some nits about your tests below.  The tests are failing but it might be an infrastructure problem.  I've tried to rerun them.  If they don't pass, could you try pushing a new commit or a merge commit with master?

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 21 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: ah you're right! I removed it!

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 22 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: oh thank you.
I removed `enterText` and used initial text value to `TextEditingController`

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 23 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: Removed!

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 24 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart:3806]: This too little time duration is for double tap so I think I need the duration.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 25 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: Removed

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 26 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart:3888]: Same as above: I think I need the duration.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 27 above)
Comment (takassh) [reply packages/flutter/test/cupertino/text_field_test.dart]: Removed

File: packages/flutter/test/material/text_field_test.dart (hunk 28 above)
Comment (takassh) [reply packages/flutter/test/material/text_field_test.dart]: I used initial text value as cupertino.

File: packages/flutter/test/material/text_field_test.dart (hunk 29 above)
Comment (takassh) [reply packages/flutter/test/material/text_field_test.dart:2389]: Same as above: I think I need the duration.

File: packages/flutter/test/material/text_field_test.dart (hunk 30 above)
Comment (takassh) [reply packages/flutter/test/material/text_field_test.dart]: Fixed

File: packages/flutter/test/material/text_field_test.dart (hunk 31 above)
Comment (takassh) [reply packages/flutter/test/material/text_field_test.dart]: Fixed

**Comment by takassh** [comment]
Thank you! glad to hear!
I fixed them from your comments and merge a commit with master.

**Comment by takassh** [comment]
@justinmc
Thank you! glad to hear!
I fixed them from your comments and merge a commit with master.

**Comment by takassh** [comment]
@justinmc 
Please review again! Thanks

**Comment by justinmc** [comment]
Sorry I lost track of this!  I'm going on leave but I'm adding this to my list to look at when I get back in 2 weeks.

In the meantime you probably need to sync this with master as it's gotten out of date.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 32]
```diff
@@ -2986,6 +2989,30 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     endBatchEdit();
   }
 
+  void _bringIntoViewBySelectionState(TextSelection oldSelection, TextSelection newSelection, SelectionChangedCause? cause){
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2992]: Nit: There should be a space here: `){` => `) {`

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 24 above)
Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart:3806]: Ah I see.  Maybe use `kDoubleTapTimeout ~/ 2` instead?  Not a big deal, though.

**Review by justinmc — APPROVED** [review]
LGTM 👍 with two minor nits.

So sorry again for the delay here.  I think this PR is great now.  The code is even simpler than before and it also fixes the bug.  Thanks for being persistent.

Just needs to be synced with master to fix the merge conflicts.

**Comment by takassh** [comment]
@justinmc 
hi 👋 long time to see you!
I updated from your new comments and my pr was synched with the latest master branch.

**Comment by justinmc** [comment]
Thanks for the quick response, merged!
