### PR TITLE
Make `realAsyncZone` run microtasks and timers in the correct zone.

### LINKED ISSUE #59913: Errors are escaping the error zone when thrown from wrapped register* callbacks.
See https://dartpad.dev/?id=8d902660cb95b6e9eb87343b6bf1f198

I was playing around with "cancelling" async tasks by running them in zones, and wrapping all registered callbacks with a function that throws an exception if the task has been cancelled. Then I want to catch those specific exceptions and not bubble them up outside the zone. I am sure more needs to happen here to deal with edge cases and timers, but I was hoping this could work as a proof of concept.

However, I am unable to handle the errors thrown inside these callbacks, they don't reach the `handleUncaughtError` handler in the zone, even though I can see that I am currently running inside the forked zone (and its also the error zone) right before throwing.

Is this intended behavior? Is it not possible to do what I want here?

### PR DESCRIPTION
**Pull request by lrhn**
Current implementation runs timers and microtask callbacks in the root zone. That assumes that the top-level `scheduleMicrotask` or `Timer` constructors have been used, which have so far wrapped the callback with `runCallbackGuarded` before calling the zone implementation.
That means that doing `zone.scheduleMicrotask` directly would not ensure that the microtask was run in the correct zone. If a `run` handler throws, it wouldn't be caught.

This change makes the `realAsyncZone` do whatever the root zone would do if its `ZoneDelegate` got called with the intended zone and arguments. That should be consistent with the current behavior, and be compatible with incoming bug-fixes to the platform `Zone` behavior.

Prepares Flutter for landing https://dart-review.googlesource.com/c/sdk/+/406961
which is currently blocked (so this indirectly fixes https://github.com/dart-lang/sdk/issues/59913).

There are no new tests, the goal is that all existing tests keep running, and that they keep doing so when the Dart CL lands. Currently that CL only breaks one test, the `dev/automated_tests/test_smoke_test/fail_test_on_exception_after_test.dart` test which threw the error-after-test in the root zone instead of the test zone. This change fixes that.

### CODE REVIEW

File: packages/flutter_test/lib/src/binding.dart [hunk 1]
```diff
@@ -1361,7 +1361,7 @@ class AutomatedTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
     final Zone realAsyncZone = Zone.current.fork(
       specification: ZoneSpecification(
         scheduleMicrotask: (Zone self, ZoneDelegate parent, Zone zone, void Function() f) {
-          Zone.root.scheduleMicrotask(f);
+          _rootDelegate.scheduleMicrotask(zone, f);
```
Comment (lrhn) [inline packages/flutter_test/lib/src/binding.dart:1364]: This could have just done `Zone.root.scheduleMicrotask(zone.bindCallbackGuarded(f))`, but that's not nevessarily the same as what `rootDelegate.scheduleMicrotask(zone, f)` does.
The `bindCallbackGuarded` does an extra `Zone.registerCalback`, and an extra `Zone.run` on top of what the root zone's `scheduleMicrotask` would already do.

Using the root zone's delegate is ensures that it does exactly the same as if `zone` had been a direct child of the root zone, just bypassing the intermediate zones in order to get "real" async operations.

**Comment by lrhn** [comment]
Come to think of it, I should be able to add a test that distinguishes the new behavior from the old if I call the `Zone.createTimer` directly. (Until the Dart CL lands, using the `Timer` constructor will work the same in both cases.)

**Comment by lrhn** [comment]
Rebase on current master, hop it fixes golden file tests.

**Comment by lrhn** [comment]
I'm not sure this actually affects goldens (and the triage link is dead).

What is the next step needed to land this?

**Comment by justinmc** [comment]
Looks like the goldens check is good now? Removing the label.

**Comment by lrhn** [comment]
PTAL. I believe the goldens mark is a false positive.

**Review by justinmc — APPROVED** [review]
LGTM from my point of view but I am not familiar with these async zones in the tests. Looks like the goldens check is passing now though.

**Comment by lrhn** [comment]
Thanks. I'll need someone to land the change too. (If it's someone is familiar with the zones, they can look at it too.)

**Review by jonahwilliams — APPROVED** [review]
LGTM
