### PR TITLE
ScaleGestureRecognizer pointerCount=2 for trackpad gestures

### LINKED ISSUE #140730: GestureDetector.onTap is ignored after scaling activity
### Steps to reproduce

To reproduce using the sample code below _(for scaling, I used MacOS trackpard)_:
1. Tap on the view (should print `onTap`)
2. Zoom in and Zoom out using two fingers multiple times (see screen recording)
3. Tap on the view (it would print `onScale`)
   - if that does not happen, repeat step 2 and zoom in then out to the max.

https://github.com/flutter/flutter/assets/46427323/905087e2-8d02-42f8-8d06-40a544e03506

### Expected results

I expect `GestureDetector.onTap` to be invoked for taps on the widget. 

### Actual results

Tapping on the widget after scaling invokes `onScale...` instead of `GestureDetector.onTap`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ScaleTapIssue(),
        ),
      ),
    ),
  );
}

class ScaleTapIssue extends StatefulWidget {
  const ScaleTapIssue({
    Key? key,
  }) : super(key: key);

  @override
  State<ScaleTapIssue> createState() => _ScaleTapIssueState();
}

class _ScaleTapIssueState extends State<ScaleTapIssue> {
  var scale = 1.0;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        print('onTap');
      },
      onScaleUpdate: (details) {
        // to avoid printing all events
        if (details.scale == 1.0) {
          print('onScale');
        } else {
          final newScale = scale - ((1 - details.scale) * 0.2);
          if (newScale >= 0.1 && newScale <= 4.0) {
            setState(() {
              scale = newScale;
            });
          }
        }
      },
      child: Center(
        child: Container(
          color: Colors.yellow.shade200,
          height: 500,
          width: 500,
          child: ClipRect(
            clipBehavior: Clip.hardEdge,
            child: Transform.scale(
              scale: scale,
              child: Center(
                child: Container(
                  color: Colors.red,
                  height: 50,
                  width: 50,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 12.7 21G816 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

----

Additional Details:
I have previously filed the following issue for `InteractiveViewer`, and I believe this new issue is its root cause or closer to it:
- #136622 

p.s. I would like to mention that `GestureDetector.onScale` has few other unexpected behaviors such as the conflict with `onPan` and the treatment of  "single finger scroll" as a scaling event. Here are some issues that I ran into while working with scaling and other gestures: 
- #115061 
- #13102
- #13101

### PR DESCRIPTION
**Pull request by moffatman**
Now trackpad gestures will count as pointerCount=2 instead of 1. It makes it easier for people who want to have different behaviour for single-finger drag vs two-finger pan/zoom. Also fixed up `scale_test.dart` to verify `pointerCount` in more places.

Related: https://github.com/flutter/flutter/issues/13102
Fixes https://github.com/flutter/flutter/issues/140730

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by feinstein** [comment]
I am not sure if this is valid, we could have a scale gesture with 3 or more pointers at the same time, and this will be limiting the information to only 2.

**Comment by moffatman** [comment]
No information is getting lost here, and no change to pointer count for touch gestures. Just now each "trackpad" in active use will now count as 2 pointers instead of 1.

File: packages/flutter/lib/src/gestures/scale.dart [hunk 1]
```diff
@@ -408,7 +408,10 @@ class ScaleGestureRecognizer extends OneSequenceGestureRecognizer {
   /// Typically this is the number of fingers being used to pan the widget using the gesture
   /// recognizer.
```
Comment (Piinks) [inline packages/flutter/lib/src/gestures/scale.dart:409]: Should the public docs mention anything about this?

**Review by Piinks — COMMENTED** [review]
Hey @moffatman good to see you! :)

> Related: https://github.com/flutter/flutter/issues/13102
Related: https://github.com/flutter/flutter/issues/140730

Is the first resolved by this?
If not, what further needs doing to resolve those issues after this? Just asking so we can update those issues.

File: packages/flutter/lib/src/gestures/scale.dart (hunk 1 above)
Comment (moffatman) [reply packages/flutter/lib/src/gestures/scale.dart:409]: Sure, will mention trackpad gestures here

**Comment by moffatman** [comment]
Hi @Piinks
I don't think the first one can be closed, there is also a general complaint about single-finger scale there. But we could close the second ticket after this is merged I think.

**Review by Piinks — APPROVED** [review]
This LGTM, thank you!

**Comment by osaxma** [comment]
Thank you @moffatman for taking care of this -- much appreciated 🙏🏽
