### PR TITLE
[flutter_tools] Have FlutterValidator fail on non-ideal git config

### LINKED ISSUE #102035: [Tool] Doctor should warn on non-ideal git configuration of the Flutter repo
The Flutter tool does not support the upgrade operation on the following configurations of the user's local Flutter repository:

- The current checkout is on a "Detached HEAD" state.
- The current checkout does not have an upstream.
- The checkout is not tracking an official upstream(aka "[standard remote](https://github.com/flutter/flutter/blob/aa5d7b6972ee5be596c15b83d39f7d3dde6ad939/packages/flutter_tools/lib/src/version.dart#L387-L389)").

However, the doctor output still shows a `✓` for such cases in the Flutter section.

<details>
<summary>An example</summary>
<pre>
$ ./bin/flutter doctor
Building flutter tool...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.13.0-0.0.pre.601, on Artix Linux 5.17.3-artix1-1, locale en_IN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

$ git checkout HEAD^1
Note: switching to 'HEAD^1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
...

$ ./bin/flutter doctor
Building flutter tool...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.13.0-0.0.pre.600, on Artix Linux 5.17.3-artix1-1, locale en_IN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

$ ./bin/flutter upgrade
Unable to upgrade Flutter: Your Flutter checkout is currently not on a release branch.
Use "flutter channel" to switch to an official channel, and retry. Alternatively, re-install Flutter by going to https://flutter.dev/docs/get-started/install.
</pre>
</details>

## Proposal

Highlight that the current install has issues with the git configuration by showing a `!` in those cases.

### PR DESCRIPTION
**Pull request by royarg02**
Fixes #102035.

Makes the version and the upstream repository message display an issue in cases where `flutter upgrade` is not supported.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/doctor.dart [hunk 1]
```diff
@@ -467,20 +467,36 @@ class FlutterValidator extends DoctorValidator {
...
-        frameworkVersion,
-        _flutterRoot(),
-      )));
-      messages.add(ValidationMessage(_userMessages.flutterUpstreamRepositoryUrl(version.repositoryUrl ?? 'unknown')));
-      final String? gitUrl = _platform.environment['FLUTTER_GIT_URL'];
+      repositoryUrl = version.repositoryUrl;
+      upstreamValidationError = VersionUpstreamValidator(version: version, platform: _platform).run();
+
+      final String flutterVersionMessage = _userMessages.flutterVersion(frameworkVersion, versionChannel, _flutterRoot());
+      if (versionChannel == 'unknown' || frameworkVersion == '0.0.0-unknown') {
```
[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/doctor.dart]: I made each statement have its separate function returning `ValidationMessage`. Hope that suffices.

File: packages/flutter_tools/lib/src/doctor.dart [hunk 2]
```diff
@@ -531,6 +530,31 @@ class FlutterValidator extends DoctorValidator {
     );
   }
 
+  ValidationMessage _getFlutterVersionMessage(String frameworkVersion, String versionChannel) {
+    final String flutterVersionMessage = _userMessages.flutterVersion(frameworkVersion, versionChannel, _flutterRoot());
+
+    if (versionChannel == 'unknown' || frameworkVersion == '0.0.0-unknown') {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/doctor.dart:536]: Out of curiosity, when is this value `0.0.0-unknown`? And can you add a comment with the answer so I don't ask you next time :)

File: packages/flutter_tools/lib/src/doctor.dart [hunk 3]
```diff
@@ -531,6 +530,31 @@ class FlutterValidator extends DoctorValidator {
...
+      return ValidationMessage.hint(flutterVersionMessage);
+    }
+    return ValidationMessage(flutterVersionMessage);
+  }
+
+  ValidationMessage _getFlutterUpstreamMessage(FlutterVersion version, String? gitUrl) {
+    final String? repositoryUrl = version.repositoryUrl;
+    final VersionCheckError? upstreamValidationError = VersionUpstreamValidator(version: version, platform: _platform).run();
+
+    if (repositoryUrl == null) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/doctor.dart:546]: I think this can be before run the validator on line 544?

File: packages/flutter_tools/lib/src/doctor.dart [hunk 4]
```diff
@@ -531,6 +530,31 @@ class FlutterValidator extends DoctorValidator {
...
+      return ValidationMessage.hint(_userMessages.flutterUpstreamRepositoryUrl('unknown'));
+    }
+    if (upstreamValidationError != null) {
+      if (gitUrl != null) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/doctor.dart:550]: Rather than doing this check for `gitUrl != null`, can we not re-use the error message of `upstreamValidationError`? If that doesn't make sense, I think we should at least sub-class `VersionCheckError` for the different types of errors, rather than doing a check for the value of `gitUrl` here. It would be better for that implementation detail to be encapsulated inside of the `VersionUpstreamValidator`.

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/doctor.dart:550]: That actually sounds like a good idea.

File: packages/flutter_tools/test/general.shard/flutter_validator_test.dart [hunk 5]
```diff
@@ -153,23 +156,26 @@ void main() {
...
+      statusInfo: 'Channel beta, 1.0.0, on Windows, locale en_US.UTF-8',
       messages: containsAll(const <ValidationMessage>[
         ValidationMessage('Pub download mirror https://example.com/pub'),
         ValidationMessage('Flutter download mirror https://example.com/flutter'),
       ])
     ));
   });
 
-  testWithoutContext('FlutterValidator shows FLUTTER_GIT_URL environment variable when set', () async {
+  testWithoutContext('FlutterValidator shows FLUTTER_GIT_URL when set and fails if upstream is not the same', () async {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/flutter_validator_test.dart:167]: This is great!

File: packages/flutter_tools/test/general.shard/flutter_validator_test.dart [hunk 6]
```diff
@@ -180,17 +186,69 @@ void main() {
...
+      fileSystem: MemoryFileSystem.test(),
+      processManager: FakeProcessManager.any(),
+      operatingSystemUtils: FakeOperatingSystemUtils(name: 'Linux'),
+      flutterRoot: () => 'sdk/flutter',
+    );
+
+    expect(await flutterValidator.validate(), _matchDoctorValidation(
+      validationType: ValidationType.partial,
+      statusInfo: 'Channel beta, 0.0.0-unknown, on Linux, locale en_US.UTF-8',
+      messages: contains(const ValidationMessage.hint('Flutter version 0.0.0-unknown on channel beta at sdk/flutter')),
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/flutter_validator_test.dart:240]: Is the assumption here that `git describe ...` outputted something we can't parse?

File: packages/flutter_tools/test/general.shard/flutter_validator_test.dart [hunk 7]
```diff
@@ -180,17 +186,69 @@ void main() {
...
+      processManager: FakeProcessManager.any(),
+      operatingSystemUtils: FakeOperatingSystemUtils(name: 'Linux'),
+      flutterRoot: () => 'sdk/flutter',
+    );
+
+    expect(await flutterValidator.validate(), _matchDoctorValidation(
+      validationType: ValidationType.partial,
       statusInfo: 'Channel unknown, 1.0.0, on Linux, locale en_US.UTF-8',
-      messages: contains(const ValidationMessage('FLUTTER_GIT_URL = https://githubmirror.com/flutter.git')),
+      messages: contains(const ValidationMessage.hint('Flutter version 1.0.0 on channel unknown at sdk/flutter')),
```
[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:217]: This is because I want to nudge users towards hints that might cause `flutter upgrade` to fail. The tool sets channel `unknown` if the branch doesn't have an upstream.

File: packages/flutter_tools/test/general.shard/flutter_validator_test.dart (hunk 6 above)
Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:240]: Yes.

File: packages/flutter_tools/test/general.shard/flutter_validator_test.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:217]: It doesn't seem like this message gives the user actionable information, though.

[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:217]: Should we recommend the user to reinstall here(and other errors where applicable)?

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:217]: what if the if i'm tracking branch delta from my own mirror? Won't that also resolve to "Unknown"? This seems like a reasonable workflow.

[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/flutter_validator_test.dart:217]: The tool parses the information from this command for the channel:
https://github.com/flutter/flutter/blob/c181e450c8dfa0080626d7572753b9c85727c0a2/packages/flutter_tools/lib/src/version.dart#L113-L114
and sets 'unknown' if the above returns nothing, which shouldn't be possible if the current branch is tracking _something_, be it a remote or a local branch.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by RoyARG02** [comment]
> It doesn't seem like this message gives the user actionable information, though.

This is what I have in mind:
- If upstream repository is a non-standard remote, we show a message to set `FLUTTER_GIT_URL` to the non-standard remote.
- If upstream repository is unknown, we display a message to reinstall Flutter.
- If channel is unknown, we display a message to switch to a release channel using `flutter channel`(to fix detached HEAD), and if that doesn't work, reinstall Flutter.
- If frameworkVersion is unknown, we display a message that the tool was unable to resolve version possibly due to local changes, and if is okay to lose changes, reinstall Flutter.

**Review by Jasguerrero — APPROVED** [review]
LGTM
