### PR TITLE
Fix `NavigationDestination` API doc

### LINKED ISSUE #103032: `NavigationDestination` API doc formatted strangely
https://api.flutter.dev/flutter/material/NavigationDestination-class.html

### PR DESCRIPTION
**Pull request by guidezpl**
Fixes https://github.com/flutter/flutter/issues/103032

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/navigation_bar.dart [hunk 1]
```diff
@@ -217,16 +217,9 @@ enum NavigationDestinationLabelBehavior {
...
-/// The destination this widget creates will look something like this:
-/// =======
-/// |
-/// |  ☆  <-- [icon] (or [selectedIcon])
-/// | text <-- [label]
-/// |
-/// =======
+/// A Material 3 [NavigationBar] destination.
+/// 
+/// Displays a label below an icon. Use with [NavigationBar.destinations].
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/navigation_bar.dart:222]: You could preserve the original diagram by enclosing it in triple backquotes.  Or you could generate a labeled diagram like the one that appears in the AppBar class API doc, using https://flutter.github.io/assets-for-api-docs/

Comment (guidezpl) [reply packages/flutter/lib/src/material/navigation_bar.dart:222]: I don't think it's all that useful, given `NavigationBar` has a runnable code sample. I can add it to a new `See also` section

**Review by HansMuller — APPROVED** [review]

**Comment by guidezpl** [comment]
Thanks!
