### PR TITLE
Interactable ScrollView content when settling a scroll activity

### LINKED ISSUE #145330: `BouncingScrollPhysics` Capturing all input until settled
### Steps to reproduce

1. Overscroll
2. Try to click on the button while the scroll physics is settling

### Expected results

I can tap on the button

### Actual results

I cannot tap on the button

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: ListView(
            physics: const BouncingScrollPhysics(),
            children: [
              for (var i = 0; i < 100; i++)
                ElevatedButton(onPressed: () {}, child: Text('ElevatedButton$i')),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

I have two videos:
A Native iOS Settings app:

https://github.com/flutter/flutter/assets/12874766/e1ae61f8-d59c-40ae-a4c4-ad919f0dc6bf

And a Flutter app:

https://github.com/flutter/flutter/assets/12874766/08c986f0-a758-4b09-895c-fff73788eb8d

Overscrolling a native app and then attempting to tap on an active element makes the element receive input.
Flutter on the other hand consumes all the input and directs it to the scrollable that is settling. Making it impossible to tap on active widgets.

One bad way to avoid it, is by adding `ClampedScrollPhysics` to the scrollable. But that breaks immersion on iOS and I do not consider it a valid solution.

(I am showing it on Android due to the tap indicators)

The issue is also present in other Animated widgets e.g. `TabBarView` with any kind of scrolling. Slivers and others possibly too.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3 23D56 darwin-arm64, locale
    en-CZ)
    • Flutter version 3.19.2 on channel stable at
      /Users/michalhazdra/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michalhazdra/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by Michal-MK**
Currently when the user:
- flings a scrollable 
- overscrolls, and the scrollable is trying to settle
- applies `DrivenScrollActivity`
- swipes from one tab to the next

All inputs are discarded or forwarded directly to the Scrollable widget (scroll activity).

This leads to situations like these:

https://github.com/flutter/flutter/assets/12874766/51b7876f-5a91-4a86-aa21-c72f0b2c4263

https://github.com/flutter/flutter/assets/12874766/2f756a45-5e42-47d7-98a0-12f071d34e7c

https://github.com/flutter/flutter/assets/12874766/5eb998a1-b3b8-42a1-8b04-543f68823c2b

Which leads to poor experience on iOS. The native behavior of iOS is to allow touches while a scrollable is settling:

https://github.com/flutter/flutter/assets/12874766/e1ae61f8-d59c-40ae-a4c4-ad919f0dc6bf

This PR alters the `shouldIgnoreTouches` of `BallisticScrollAvtivity` and `DrivenScrollActivity` to not make the child of the scrollable ignore touches.

Fixes #145330

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

Currently tests that test tap to stop are not working as the taps now register when they should not. Because there is no distinction between flings inside and flings that go out of range.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @Michal-MK it looks like this is still a draft, so I'll wait for your say so when it's ready for review. :)

**Comment by Michal-MK** [comment]
@Piinks Yeah, I am sort of stuck as I reverted all the meaningful changes and the tests are still failing (other than analyze, that one I expect to fail) looking at the output widget_tester_test is something I did not touch so I assume something else is going on? Or the:
E.g. `PathNotFoundException: Cannot open file, path = 'C:\b\s\w\ir\x\w\recipe_cleanup\flutter_logs_dir/fake_result.json' (OS Error: The system cannot find the file specified.`

I'll continue after Easter :)

**Comment by Michal-MK** [comment]
The three failing checks are in the FlutterGallery in the Style->Colors section. The issue there is the use of `Scrollbar`, widget. There are tabs, and as the test swipes through them it, at some point, it tries to render a second `Scrollbar` which then fails, as both are reading the primary scroll controller. I validated this on `master` using trackpad scrolling which is what this PR effectively brings to finger gestures and it fails on `master` as well. The test just does not pick it up as it is not using a trackpad to scroll (`.fling`/`.trackpadFling` and other alternatives). I do not see how to fix this without the `TabBarView` somehow providing a custom `ScrollController` to its children that is somehow connected to the primary one once the transition animation finishes. @Piinks

**Comment by Piinks** [comment]
Interesting, I tried using a trackpad to reproduce this at https://flutter-gallery-archive.web.app/#/demo/colors but did not see an error from the scrollbar. Do you know how this change could have caused it?

I think this can be fixed by making the vertical scroll views in the tab bar view not use the primary scroll controller. This would be unrelated to TabBarView, since the list of colors is separate.

**Comment by Michal-MK** [comment]
It happens on master without any changes, may be limited to MacOS then? Here is a video

https://github.com/flutter/flutter/assets/12874766/5e4ce3d4-b6d7-4d0e-8649-5605a9720ff8

**Comment by Piinks** [comment]
> I am not sure how this can be done without it being a breaking change.

Oh no, I meant to go into the gallery code and fix the issue there, rather than changing the framework. If the gallery is broken on master without this change, we should fix it, which will unblock this change. The code lives in `flutter/dev/integration_tests/flutter_gallery`.

**Review by Piinks — COMMENTED** [review]
Little bit more digging...

I think there are duplicates of this issue:
- https://github.com/flutter/flutter/issues/92119
- https://github.com/flutter/flutter/issues/146401
- and https://github.com/flutter/flutter/issues/145330

And there are currently two different proposals out to resolve them:
- https://github.com/flutter/flutter/pull/145848 (this PR)
- https://github.com/flutter/flutter/pull/146403

**Comment by Michal-MK** [comment]
I'll try altering the Gallery then, I was not sure if that was allowed :) With that I'll see what else needs changing to make this a proper PR.

**Comment by Michal-MK** [comment]
Alright, with the explicit `ScrollController` for the `Scrollbar` in the gallery we are all green.

So I'll do some cleanup and write tests tomorrow. Then I'll change it from a Draft to a normal PR.

**Comment by Michal-MK** [comment]
@Piinks It seems I hit another block, this time customer tests are failing.

```
| 00:07 +201: /Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.qUNvnh/tests/super_editor/test/super_editor/supereditor_scrolling_test.dart: SuperEditor scrolling stops momentum on tap down and doesn't place the caret (on Android)
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: <1194.3136212798695>
|   Actual: <1191.6569144503435>
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure>.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.qUNvnh/tests/super_editor/test/super_editor/supereditor_scrolling_test.dart:501:7)
| <asynchronous suspension>
| #5      testWidgetsOnAndroid.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:235:7)
| <asynchronous suspension>
| #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
| <asynchronous suspension>
| #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
|
| This was caught by the test expectation on the following line:
|   file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.super_editor.qUNvnh/tests/super_editor/test/super_editor/supereditor_scrolling_test.dart line 501
| The test description was:
|   stops momentum on tap down and doesn't place the caret (on Android)
| ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Those are not part of the repository as far as I know.

File: dev/integration_tests/flutter_gallery/lib/demo/colors_demo.dart [hunk 1]
```diff
@@ -78,7 +78,7 @@ class ColorItem extends StatelessWidget {
   }
 }
 
-class PaletteTabView extends StatelessWidget {
+class PaletteTabView extends StatefulWidget {
```
Comment (Piinks) [inline dev/integration_tests/flutter_gallery/lib/demo/colors_demo.dart:81]: Since this is currently broken at head, and not related to this change, this should probably be broken out into a separate PR and validated with a test so it does regress in the future.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 2]
```diff
@@ -2424,7 +2424,8 @@ void main() {
       expect(tester.getCenter(find.text('Item 49')).dy, equals(585.0));
 
       // Overscroll, dragging like this will release with 0 velocity.
-      await tester.drag(find.text('Item 49'), const Offset(0.0, -50.0));
+      // , warnIfMissed: false
+      await tester.drag(find.text('Item 49'), const Offset(0.0, -50.0), warnIfMissed: false);
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:2428]: Are these tests broken?

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 3]
```diff
@@ -323,6 +323,10 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
   // for use when resizing the viewport to non-zero next time.
   double? _cachedPage;
 
+  /// When page view goes ballistic we want to allow interaction with the page
+  @override
+  bool? get preferredBallisticIgnorePointer => false;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/page_view.dart:328]: Why only PageView?

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 4]
```diff
@@ -47,6 +47,16 @@ abstract class ScrollActivityDelegate {
   /// Terminate the current activity and start a ballistic activity with the
   /// given velocity.
   void goBallistic(double velocity);
+
+  /// Some ballistic activities may want to allow input on child widgets.
+  /// This flag takes precedence over [ScrollActivity.shouldIgnorePointer] when
+  /// starting a ballistic activity.
+  bool? get preferredBallisticIgnorePointer;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_activity.dart:54]: What does it mean when this is null? It looks like some scroll positions have an opinion for this and some don't. Is this only relevant with PageView? If so, why?

**Review by Piinks — COMMENTED** [review]
That looks like a legitimate test failure from the customer.
It lives here:
https://github.com/superlistapp/super_editor/blob/661ecb84b4f79bd3f81c1bfd148b36ab7be6993b/super_editor/test/super_editor/supereditor_scrolling_test.dart#L473

When the user taps on a scrolling viewport, the scrolling should halt. This change in behavior would be a breaking change.

I wonder if that is why some of the tests here have changed `warnIfMissed`? That's also something to look at. Why did those tests change?

There are some options here, either 
- the PR can be changed to fix a bug it may have introduced here
- or the PR can be changed to make this behavior an opt-in, so folks relying on the prior behavior can continue to work
- or if the customer test is capturing a bug, that this PR is fixing, we can work with the customer to transition them to the solution without breaking them. (This PR would land after the customer has been fixed)

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 2 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:2428]: I am working on these, even if the drag "misses", the scrollable is dragged as expected which is validated by the `expect` below. I added the `warnIfMissed` early in the PR, so it may not be necessary now.

File: packages/flutter/lib/src/widgets/page_view.dart (hunk 3 above)
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/page_view.dart:328]: The property `preferredBallisticIgnorePointer` is still a proof of concept, right now I am trying to make all tests pass and achieve the behavior I want. Then I'll add tests and refactor it. Here the `false` essentially mimics trackpad scrolling as that evaluates to `false` all the time. So for now I just slapped in a `false` as the preference which makes it behave like a trackpad. But with touch gestures.

**Comment by Michal-MK** [comment]
Thanks for the link, I looked at it and from local testing it seems that my current code pumps one extra frame when tapping on a scrollable. In my sample app tap to stop works so I will have to figure out what it up with that test and why my changes break it.

**Comment by Michal-MK** [comment]
@Piinks I got the customer tests working somehow :D

And I managed to remove the changes to the nested_scroll_view and remove one extra `warnIfMissed` below, as now it will correctly detect hits when the scrollable is over-scrolled.

With that there are a couple of things that need doing:
1) I do not like the type cast `BallisticScrollActivity` but if I move it to the activity delegate it would mean editing a lot of classess again, the `outOfRange` was fine as most of the implementation already defined the field/getter, but nobody defines `updateIgnorePointer` currently. Thoughts on this?

2) There is still a difference between native. That is long presses. Native iOS does not allow long press on over-scrolled views. That would require setting a timeout and after that making the `shouldIgnorePointer` reset to `true`. But by then the interactable widget (e.g. Button) would already be highlighted? I have not touched and I have 0 experience with input handling. But I have a feeling that will not be as simple to implement (timeout sync/cancelling etc...). Should that be part of this PR?

3) Other scrollables besides `PageView`. Here I implemented it because it was annoying as shown in the videos at the top, but I did not actually test the native behavior of either platform. Maybe it "does not work" there either so it is expected. Because if that was the case, the whole `preferredBallisticIgnorePointer` would go away, simplifying this PR quite a bit. So I'll need to hack together a native app and test this still.

**Comment by Michal-MK** [comment]
I hacked together a simple page view using Chat GPT in Kotlin and the same janky behavior is present there as well. So... what now? From a UX point of view it is horrible, but it is consistent with the native behavior.

**Review by Piinks — COMMENTED** [review]
> I hacked together a simple page view using Chat GPT in Kotlin and the same janky behavior is present there as well. So... what now? From a UX point of view it is horrible, but it is consistent with the native behavior.

I am not sure I understand, what is the question? :)

**Comment by Michal-MK** [comment]
https://github.com/flutter/flutter/assets/12874766/dd8fda07-2e68-45d5-aeaf-a29a9dc60b24

That the native world has the same issue, so is it then an issue? Should I bother fixing it here if it may be intended?

**Comment by Michal-MK** [comment]
@Piinks How about I remove the code related to the PageView functionality for now, that way we do not need to care about the Colors Gallery issue and at least get the out of bounds scrolling interactivity merged, since that is what I wrote tests for. I think that this functionality is ready. I will create a separate issue with the PageView with the videos from here and another one for the GalleryApp Colors trackpad bug. So we can track it separately and not clutter this one?

**Comment by Piinks** [comment]
> How about I remove the code related to the PageView functionality for now, that way we do not need to care about the Colors Gallery issue and at least get the out of bounds scrolling interactivity merged, since that is what I wrote tests for. I think that this functionality is ready. I will create a separate issue with the PageView with the videos from here and another one for the GalleryApp Colors trackpad bug. So we can track it separately and not clutter this one?

I am not sure what that would look like? I have not done a thorough review as you've told me a couple times it is not ready or just a proof of concept. The gallery issue is not specific to this change and needs to be fixed anyways. As far as the changes this PR is making, I would rather we sort out the intended behavior before merging any partial fix. We typically do not land partial fixes, or changes where we don't quite know what the behavior should be.

**Comment by Michal-MK** [comment]
@Piinks
"The gallery issue is not specific to this change and needs to be fixed anyways."
Yes that is what we are both saying :D Since you said they are unrelated and should be fixed in a separate PR that is what I repeated.

"As far as the changes this PR is making, I would rather we sort out the intended behavior before merging any partial fix. We typically do not land partial fixes, or changes where we don't quite know what the behavior should be."
I agree with that, that is again why I suggested removing the PageView "fix", since native behaves in the same 
"broken" way, or moving it into a separate issue where we can "figure out what the behavior should be". As for the interactivity when a scrollable is over scrolled, that is working and is consistent with the native behavior on iOS/MacOS. The attached videos show this. So I am not sure if by "partial fix" you meant the PageView, the long press or this PR as a whole?

**Comment by Piinks** [comment]
Hi @Michal-MK, I've reread the comments above a couple of times, and I apologize I do not understand the state of the proposal. It sounds like some of it works, some of it does not and some of it is matching native behavior. Can you help me understand, from your last comment, if you remove the PageView changes, what problem is this PR solving? What I meant by partial fix was that it sounded like this would only apply to some scrollable classes rather than all of them.

**Comment by Michal-MK** [comment]
@Piinks Sure, when we remove the `PageView` change (which currently behaves the way native tabs do in Android) we are left with the change to `BouncingScrollPhysics` not allowing interaction with the contents of the scrollable. When a scrollable with bouncing scroll physics is out of bounds, native iOS allows taps on the scrollable content, however Flutter currently forwards the input to the scrollable and children are "hit test invisible", so now you can only resume the scroll gesture, but not perform a tap on a button in the scrollable.

https://github.com/flutter/flutter/assets/12874766/51b7876f-5a91-4a86-aa21-c72f0b2c4263

https://github.com/flutter/flutter/assets/12874766/5eb998a1-b3b8-42a1-8b04-543f68823c2b

https://github.com/flutter/flutter/assets/12874766/e1ae61f8-d59c-40ae-a4c4-ad919f0dc6bf


These are the relevant videos.

The changes are only in scroll_activty.dart, scroll_position.dart and scroll_position_with_single_context.dart. Then classes that extend/implement these need to now have `outOfRange` boolean getter, and most do already, so I assume most of the scrollable implementations in Flutter should support it without changes to the source code in them directly (I had to modify only nested_scroll_view.dart to make it compile). I will have to check 2D scrollables as I have not used them yet (even in my apps). The other thing that needs to be looked at, is that long press gestures should not happen on overscrolled scrollables, with this change they do. I asked if someone who has more experience in input handling would want to look at this, but I guess I will have to dig in myself and somehow make the long press gesture bail out of the arena when we are overscrolled. Before I start looking at it, i want to reduce the scope of this PR as now it is addressing 3 unrelated issues at once.

**Comment by Piinks** [comment]
Thank you for explaining!

> I want to reduce the scope of this PR as now it is addressing 3 unrelated issues at once.

Yes, I think that may be where I keep getting mixed up. Let's focus on one issue and one change at a time. I really appreciate your contributions to fix these things! What of the 3 issues you mentioned would you like to fix first?

**Comment by Michal-MK** [comment]
Sorry I am just too busy right now; First I want to fix the issue in the video, since that is what I originally reported. Hopefully I will have the changes ready by the end of the week. Then the Gallery, and the PageView last, if we actually decide to change it.

**Comment by Piinks** [comment]
> Sorry I am just too busy right now; First I want to fix the issue in the video, since that is what I originally reported. Hopefully I will have the changes ready by the end of the week. Then the Gallery, and the PageView last, if we actually decide to change it.

No worries at all, I appreciate your work on this, and if you need to come back later when you have time, or if you don't have time at all, that's all ok too.

If you do work further on this, just let me know when you'd like another review,  I'll be happy to take a look and discuss further. :)

**Comment by Michal-MK** [comment]
@Piinks Hi, I created separate issues for the other two parts that were originally here. Now this PR has only the overscroll interactivity fix.

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 5]
```diff
@@ -596,6 +602,12 @@ class BallisticScrollActivity extends ScrollActivity {
   /// and returns true if the overflow was zero.
   @protected
   bool applyMoveTo(double value) {
+    if (delegate.outOfRange) {
+      shouldIgnorePointer = false;
+      if (delegate is ScrollPosition) {
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:607]: Yeah I am not happy with this either, ScrollPosition has the method, I did not want to expose it in the delegate... I'll see where I can move it.

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 6]
```diff
@@ -596,6 +602,12 @@ class BallisticScrollActivity extends ScrollActivity {
   /// and returns true if the overflow was zero.
   @protected
   bool applyMoveTo(double value) {
+    if (delegate.outOfRange) {
+      shouldIgnorePointer = false;
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:606]: I would say no, but I'll check how iOS does it.

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 7]
```diff
@@ -47,6 +48,11 @@ abstract class ScrollActivityDelegate {
   /// Terminate the current activity and start a ballistic activity with the
   /// given velocity.
   void goBallistic(double velocity);
+
+  /// Flag to indicate whether the scroll view is over-scrolled. Meaning the
+  /// user has scrolled beyond the extents of the scrollable. This is possible
+  /// e.g. with [BouncingScrollPhysics].
+  bool get outOfRange;
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:55]: I do no fully understand the abstraction here :D From looking at the code `ScrollActivityDelegate` instances are always `ScrollPositionWithSingleContext` or the private `_NestedScrollCoordinator` but that is private, there are no other implementations currently. The implementations know about the positions so I exposed them though this property in the abstract activity.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 8]
```diff
@@ -374,6 +374,14 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
     return 0.0;
   }
 
+  /// Update ignorePointer for the current context from the currently running activity
+  /// without restarting it.
+  void updateIgnorePointer() {
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_position.dart:379]: There probably was a reason, but I'll check, good point.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 9]
```diff
@@ -2457,7 +2760,7 @@ void main() {
 
       // Tap after releasing the overscroll to trigger secondary inner ballistic
       // scroll activity with 0 velocity.
-      await tester.tap(find.text('Item 49'), warnIfMissed: false);
+      await tester.tap(find.text('Item 49'));
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:2763]: I believe the `warnIfMissed` was here due to the fact that the scrollable absorbed all inputs. So the author of the test just put in `warnIfMissed: false` to get rid of the error they were getting. Now that overscrolled scrollable correctly allow input on children the child is no longer missed and this can be removed. I believe keeping it there is not necessary as no warning will be produced now.

File: packages/flutter/test/widgets/list_view_test.dart [hunk 10]
```diff
@@ -545,6 +545,221 @@ void main() {
...
+    tapped = false;
+
+    await tester.pumpAndSettle();
+
+    await tester.tap(find.text('Item 2'));
+    expect(tapped, isTrue);
+    tapped = false;
+  });
+
+  testWidgets('ListView absorbs touch to stop scrolling when not at the edge, #145330', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/test/widgets/list_view_test.dart:641]: I added this in response to https://github.com/flutter/flutter/pull/145848#pullrequestreview-1998424362 Just so I have a test I can check without going to a third party to validate.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 11]
```diff
@@ -325,6 +325,309 @@ void main() {
...
+    tapped = false;
+
+    await tester.pumpAndSettle();
+
+    await tester.tap(find.text('Item 0'));
+    expect(tapped, isTrue);
+    tapped = false;
+  });
+
+  testWidgets('NestedScrollView absorbs touch to stop scrolling when not at the edge, #145330', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:415]: I added this in response to https://github.com/flutter/flutter/pull/145848#pullrequestreview-1998424362 Just so I have a test I can check without going to a third party to validate.

**Comment by Michal-MK** [comment]
Alright I made some changes (hopefully the tests pass 🙏), and added comments to your review notes, thanks for those. Now, "throws the imaginary ball your way" :D @Piinks

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:57]: I actually added more here (`updateIgnorePointer`) as putting it elsewhere would probably need large changes to the code. But if I am missing something about the implementation let me know. I just do not see a better place for it now.

File: packages/flutter/test/widgets/list_view_test.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/test/widgets/list_view_test.dart:641]: Thanks! That makes sense!

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 12]
```diff
@@ -1408,6 +1427,16 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
 
+  /// Update the [ignorePointer] property of the [ScrollContext].
+  /// This is used to allow interaction with the scrollable's content.
+  /// When a scrollable reaches overscrolled state, e.g. when using [BouncingScrollPhysics],
+  /// the expected behavior is that the user can interact with the content and
+  /// not have to wait for the scroll to settle.
+  @override
+  void updateIgnorePointer(bool ignorePointer) {
+    context.setIgnorePointer(ignorePointer);
+  }
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1438]: Is it not possible to just call position.context.setIgnorePointer? The updateIgnorePointer/setIgnorePointer is a bit confusing

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 6 above)
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:608]: If the ballistic activity continues to a point where we are not out of range, butt he activity is still scrolling, should it then ignore the pointer?

**Comment by Michal-MK** [comment]
"If the ballistic activity continues to a point where we are not out of range, but the activity is still scrolling, should it then ignore the pointer?"

I am trying to imaging this situation. If I understand it correctly ballistic activity happens only on fling gestures or when oversrolling a BouncingScrollPhysics.

The only interesting case is when it is settling and user immediately presses down again. And somehow has enough overscrolled space to start a fling in the direction opposite of the overscroll. (It would have to be really tiny as starting a drag there would disable the input and if we are no longer overscrolled the following ballistic would ignore pointer.) Then the ballistic activity would have ignorePointer set to false. And taps would not interact with the content.

I'll check this one.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 12 above)
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1438]: I'll take a look at it.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 13]
```diff
@@ -363,6 +363,9 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
       final double oldPixels = pixels;
       _pixels = newPixels - overscroll;
       if (_pixels != oldPixels) {
+        if (outOfRange) {
```
Comment (Michal-MK) [inline packages/flutter/lib/src/widgets/scroll_position.dart:366]: @Piinks Surprisingly this is enough, I cannot do `context.setIgnorePointer(!outOfRange)` as that breaks trackpad scrolling and one of the tests. By incorrectly ignoring when we should not be.

**Comment by Michal-MK** [comment]
@Piinks Hi, so I revisited the code and it turns out that the scroll activity does not need to define outOfRange, it was unused since the previous commit. I just did not realize it then.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 14]
```diff
@@ -1416,6 +1420,9 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
     if (simulation == null) {
       return IdleScrollActivity(this);
     }
+    final bool shouldIgnorePointer = !outOfRange
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1423]: I feel like I may have fatigued on this, why would we want to ignore the pointer if we are not out of range?

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 15]
```diff
@@ -613,7 +613,7 @@ class BallisticScrollActivity extends ScrollActivity {
   }
 
   @override
-  final bool shouldIgnorePointer;
+  bool shouldIgnorePointer;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_activity.dart:616]: It does not look like this changes now, can it go back to being final?

**Review by Piinks — COMMENTED** [review]
Thanks for persisting on this! I think it is very close now. I really appreciate the work and patience. 🙏

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 14 above)
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1423]: To allow "tap to stop" the scrollable, otherwise it would stop the scrollable and also register a tap on the inner child, e.g. a button. (If that is what you mean)

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 15 above)
Comment (Michal-MK) [reply packages/flutter/lib/src/widgets/scroll_activity.dart]: Of course, an oversight on my part.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 14 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1422]: Ah ok, thank you, sorry I got mixed up on that. Should `shouldIgnorePointer` this be a getter in the ScrollPosition super class? That way we don't have to repeat `!outOfRange && (activity?.shouldIgnorePointer ?? true)` here and in scroll_position.dart

File: packages/flutter/test/widgets/list_view_test.dart [hunk 16]
```diff
@@ -545,6 +545,221 @@ void main() {
     expect(find.byType(Viewport), paints..clipRect());
   });
 
+  testWidgets('ListView allows touch on children when reaching an edge and over-scrolling / settling, #145330', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/list_view_test.dart:548]:
```suggestion
  testWidgets('ListView allows touch on children when reaching an edge and over-scrolling / settling', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/test/widgets/list_view_test.dart (hunk 10 above)
Comment (Piinks) [inline packages/flutter/test/widgets/list_view_test.dart:641]:
```suggestion
  testWidgets('ListView absorbs touch to stop scrolling when not at the edge', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/test/widgets/list_view_test.dart [hunk 17]
```diff
@@ -545,6 +545,221 @@ void main() {
...
+    await tester.pumpAndSettle();
+    expect(offset, equals(controller.offset));
+
+    // Tapping on an item should register the tap normally, as the scrollable is idle
+    await tester.tap(find.text('Item 2'));
+    expect(tapped, isTrue);
+    tapped = false;
+  });
+
+  testWidgets('Horizontal ListView, when over-scrolled at the end allows touches on children #145330', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/list_view_test.dart:705]:
```suggestion
  testWidgets('Horizontal ListView, when over-scrolled at the end allows touches on children', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 18]
```diff
@@ -325,6 +325,309 @@ void main() {
     expect(inner.offset, 0.0);
   });
 
+  testWidgets('NestedScrollView allows taps on children while over-scrolled to the top #145330', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:328]:
```suggestion
  testWidgets('NestedScrollView allows taps on children while over-scrolled to the top', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 11 above)
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:415]:
```suggestion
  testWidgets('NestedScrollView absorbs touch to stop scrolling when not at the edge', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 19]
```diff
@@ -325,6 +325,309 @@ void main() {
...
+
+    // Ensure the inner Scrollable is not moving
+    expect(innerOffset, equals(inner.offset));
+
+    // Tapping on an item should register the tap normally, as the scrollable is idle
+    await tester.tap(find.text('Item 10'));
+    expect(tapped, isTrue);
+  });
+
+  testWidgets('NestedScrollView when over-scrolled at the end allows touches on children, #145330', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:534]:
```suggestion
  testWidgets('NestedScrollView when over-scrolled at the end allows touches on children', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/145330
```

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 14 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1422]: This `shouldIgnorePointer` getter and the nits in the tests files should be it here and we can land this! Thank you for your work on this. We are extra careful with things like scrolling since it can regress in pretty wild and crazy ways. :)

**Comment by Michal-MK** [comment]
Yeah I understand, no worries :D 3+ months is crazy but for a framework of this size we can't afford it to be half-baked solution.

I am still unsure about the fact that long presses should again ignore touches, but I have no idea how to implement that. (How to determine in the scroll position that a touch input is now not a tap but a long press)

But this alone helps a lot in terms of UX on iOS, no more missed taps because the `ListView` had one more frame of settling and it's content was not interactable as a result :D

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 20]
```diff
@@ -270,6 +270,15 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   bool get haveDimensions => _haveDimensions;
   bool _haveDimensions = false;
 
+  /// Whether scrollables should absorb pointer events at this position.
+  /// This is mainly driven by which [ScrollActivity] is currently active.
+  /// Which determines if touches should stop the scroll or interact with the content.
+  /// Apart from that, we check for when the position is out of bounds.
+  /// This is possible with [BouncingScrollPhysics]. iOS allows propagation of
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:277]: What is possible?

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 21]
```diff
@@ -270,6 +270,15 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   bool get haveDimensions => _haveDimensions;
   bool _haveDimensions = false;
 
+  /// Whether scrollables should absorb pointer events at this position.
+  /// This is mainly driven by which [ScrollActivity] is currently active.
+  /// Which determines if touches should stop the scroll or interact with the content.
+  /// Apart from that, we check for when the position is out of bounds.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:276]:
```suggestion
  ///
  /// This is value relates to the current [ScrollActivity], which determines
  /// if additional touch input should be received by the scroll view or its children.
  /// If the position is overscrolled, as is allowed by [BouncingScrollPhysics],
  /// children of the scroll view will receive pointer events as the scroll view 
  /// settles back from the overscrolled state.
```

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 22]
```diff
@@ -270,6 +270,15 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  /// This is possible with [BouncingScrollPhysics]. iOS allows propagation of
+  /// tap events to the child/children of the scrollable view directly
+  /// when the scroll view is out of bounds and settling.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:279]:
```suggestion
```

**Review by Piinks — COMMENTED** [review]
Trying to tweak the docs here so I don't have to ask for more edits...

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 23]
```diff
@@ -270,6 +270,15 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   bool get haveDimensions => _haveDimensions;
   bool _haveDimensions = false;
 
+  /// Whether scrollables should absorb pointer events at this position.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:273]: @Michal-MK if this doc adjustment LGT-you, let me know and we can land this change.

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by Michal-MK** [comment]
Yep, that looks good. Just removed the trailing space so "Linux analyze" is happy

**Comment by Piinks** [comment]
Ah thank you! I was trying to save you another round of edits!

**Comment by Piinks** [comment]
Ok, so this will just need a second approval. Seeking someone out now.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 24]
```diff
@@ -633,6 +633,10 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
   late _NestedScrollController _outerController;
   late _NestedScrollController _innerController;
 
+  bool get outOfRange {
+    return (_outerPosition?.outOfRange ?? false) || _innerPositions.any((_NestedScrollPosition position) => position.outOfRange);
+  }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:638]: Not a big deal whatsoever, but it would be nice to stay within the [80 characters style guideline](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#prefer-a-maximum-line-length-of-80-characters):

```dart
bool get outOfRange {
  if (_outerPosition?.outOfRange ?? false) {
    return true;
  }
  return _innerPositions.any((_NestedScrollPosition position) => position.outOfRange);
}
```

**Review by nate-thegrate — APPROVED** [review]
LGTM!

Thanks for making this improvement and for the thorough testing.
I made an optional suggestion, but I'd be happy to merge right away 👍

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 24 above)
Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:638]: Honestly, this is very mild, compared to [other things I've seen](https://github.com/flutter/flutter/pull/143812#discussion_r1496810160). I'll go ahead and throw on `autosubmit` :)
