### PR TITLE
Manually stop and continue LLDB breakpoints on Xcode 26.4+

### LINKED ISSUE #184254: Thread DartWorker crash EXC_BAD_ACCESS on macOS/iOS/Xcode 26.4 in debug mode on physical devices
### Steps to reproduce

1. Have macOS 26.4
2. Create a default flutter project (using Android Studio)
3. Run flutter run for an iOS device (26.4)

### Actual results

When I do a flutter run, the DartWorker crashes and I'm unable to execute my flutter app on iOS.

### Logs

<details open>
<summary>Logs</summary>

```console

Running pod install...
Running Xcode build...
Xcode build done.                                           32,2s
Installing and launching...
Process 1125 stopped
* thread #21, name = 'DartWorker', stop reason = EXC_BAD_ACCESS (code=50, address=0x11fc000c4)
    frame #0: 0x000000011fc000c4 
->  0x11fc000c4: ldur   x6, [x24, #0x37]
    0x11fc000c8: ldursw x7, [x6, #0x6f]
    0x11fc000cc: add    x7, x7, #0x1
    0x11fc000d0: stur   w7, [x6, #0x6f]
Target 0: (Runner) stopped.

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.41.6, on macOS 26.4 25E246 darwin-arm64, locale pt-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
When using LLDB to debug on a physical iOS device, we use LLDB breakpoints for JIT. However, it appears that LLDB fails to stop at the breakpoint sometimes. To workaround this, when using Xcode 26.4+, we don't use the LLDB auto-continue feature and instead wait for it to stop and restart it manually using the `continue` command.

Fixes https://github.com/flutter/flutter/issues/184254.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by LouiseHsu — APPROVED** [review]

File: packages/flutter_tools/lib/src/ios/lldb.dart [hunk 1]
```diff
@@ -225,9 +257,12 @@ return False
       _breakpointPattern,
     ).then((value) => value, onError: _handleAsyncError);
 
-    await _lldbProcess?.stdinWriteln(
-      r"breakpoint set --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'",
-    );
+    final Version? xcodeVersion = _xcode.currentVersion;
+    final bool useManualContinue = xcodeVersion != null && (xcodeVersion >= Version(26, 4, 0));
```
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/ios/lldb.dart:261]: since the tradeoff is slower, can we maybe add a tracking issue in the case where apple fixes the bug to ensure we can revert to the `auto-continue` when it is fixed

File: packages/flutter_tools/lib/src/ios/lldb.dart [hunk 2]
```diff
@@ -147,19 +148,50 @@ return False
...
+      final StreamSubscription<String>
+      stdoutSubscription = _lldbProcess!.stdout.transform(utf8LineDecoder).listen((String line) {
+        // Skip all logs between process stop and process resume if the stop was caused by a breakpoint
+        if (line.contains(_lldbProcessStopped)) {
+          processStopLine = line;
+          return;
+        }
+        // If the last log was a proces stop log, check if it was caused by a breakpoint.
+        if (processStopLine != null) {
+          if (line.contains('stop reason = breakpoint')) {
```
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/ios/lldb.dart:175]: instead of manual string matching, should we consider using a regex pattern for `stop reason = breakpoint`

File: packages/flutter_tools/lib/src/ios/lldb.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/lldb.dart:261]: I can file one after. I don't think it needs to be committed in the code since there's no clear TODO

**Review by okorohelijah — APPROVED** [review]
LGTM overall

File: packages/flutter_tools/lib/src/ios/lldb.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/lldb.dart:175]: What benefit would regex give here? To match on inconsistent spacing?

Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/lldb.dart:175]: yup but also to avoid false positives in cases where there might be similar string

File: packages/flutter_tools/lib/src/ios/lldb.dart [hunk 3]
```diff
@@ -225,9 +257,12 @@ return False
...
     ).then((value) => value, onError: _handleAsyncError);
 
-    await _lldbProcess?.stdinWriteln(
-      r"breakpoint set --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'",
-    );
+    final Version? xcodeVersion = _xcode.currentVersion;
+    final bool useManualContinue = xcodeVersion != null && (xcodeVersion >= Version(26, 4, 0));
+    final breakpointSetCommand = useManualContinue
+        ? r"breakpoint set --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'"
+        : r"breakpoint set --auto-continue true --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'";
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/lldb.dart:264]: i may be missing something, but why is it changing behavior for earlier versions (pre-26.4)? 

Before: 
`breakpoint set --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'`

After: 
`breakpoint set --auto-continue true --func-regex '^NOTIFY_DEBUGGER_ABOUT_RX_PAGES$'`
