### PR TITLE
iOS UITextInput autocorrection prompt

### LINKED ISSUE #12920: Autocorrect tooltips don't appear on iOS
## Steps to Reproduce

When using a native iOS app without text prediction enabled, there is a pop-up that indicates when autocorrections are going to occur, and when backspacing on a correction a pop-up appears that gives alternative choices for the word.

In flutter, the autocorrections happen silently and require backspacing into the word to make the correction.  See the gif below for a comparison of the behavior.

Flutter should either integrate with the iOS autocorrection system to provide the popups or emulate them.  This is a pretty big usability concern which makes it more difficult to enter text because the corrections are harder to notice and harder to fix.

text_correction

## Logs

N/A, this is a design issue.

## Flutter Doctor

```
$ flutter doctor
Building flutter tool...
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/jwm/Projects/flutter
    • Framework revision 337150308c (2 days ago), 2017-11-05 19:39:49 -0800
    • Engine revision e059cc0258
    • Tools Dart version 1.25.0-dev.11.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.2
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone 7 Plus • DF665BBF-F7D6-4B75-8FCA-E092AD4AD6DC • ios • iOS 11.0 (simulator)
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

This PR implements iOS UITextInput autocorrection prompt feature where typos get highlighted (surrounded by a prompt rectangle, much like text selection) before they are corrected.

gif

Engine PR: https://github.com/flutter/engine/pull/13959.

## Caveat
The prompt rectangle may flicker if you type really really fast. This is because there's no signal we can get from the iOS side for dismissing the autocorrection prompt,  so we'll have to dismiss the rectangle aggressively every time the text changes.

## Related Issues

Fixes  #12920

## Tests

I added the following tests:

- iOS autocorrection rectangle should appear on demand and dismiss when the text changes or when focus is lost.
- TextInputClient showAutocorrectionPromptRect method is called.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -1113,6 +1118,36 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    if (promptRectColor == newValue)
+      return;
+
+    _promptRectPaint.color = newValue;
+    if (_promptRectRange != null)
+      markNeedsPaint();
+  }
+
+  TextRange _promptRectRange;
+  /// Dismisses the currently shown prompt rectange and displays a new prompt rectangle
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart]: rectange => rectangle

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -1798,6 +1806,16 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     }
   }
 
+  // null if no promptRect should be shown.
+  TextRange _currentPromptRectRange;
+
+  @override
+  void showAutocorrectionPromptRect(int start, int end) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Why did you create this method instead of handling the range as a parameter only?

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 3]
```diff
@@ -863,6 +863,8 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with AutomaticK
       color: enabled ? decorationColor : (decorationColor ?? disabledColor),
     );
 
+    final Color selectionColor = CupertinoTheme.of(context).primaryColor.withOpacity(0.2);
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/text_field.dart]: Is there anywhere you can document what the selection color will be for Material and Cupertino?

**Review by justinmc — COMMENTED** [review]
I want to make sure that the `showAutocorrectionPromptRect` method on EditableText is necessary (commented above), otherwise this looks great.  Sorry for the delay in reviewing this.

I like the pattern of having EditableText fully configurable and TextField and CupertinoTextField just specify their specific color :+1:.

Oh and I just tried running this really quick because I wanted to see the "flickering", but I didn't see the rectangle showing up at all.  I probably did something wrong, I just checked out your branch, ran the gallery, and went to the Cupertino text field page.  Is there anything else I need to do to get it to show up?

**Comment by LongCatIsLooong** [comment]
@justinmc sorry there's an engine PR https://github.com/flutter/engine/pull/13959

**Comment by justinmc** [comment]
Ah of course, thanks.  I tried it now and I do see what you mean about the flickering behavior, but I think it's not very noticeably wrong, at least not in the simulator.  Should be fine, but I'll keep an eye out for issues about it in the future.

One other thing: can this highlight be disabled on native without disabling autocorrection?

**Comment by LongCatIsLooong** [comment]
> One other thing: can this highlight be disabled on native without disabling autocorrection?
Not that I'm aware of.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart]: It's part of the `TextInputClient` interface now.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Oh I see, I didn't realize how that worked.  Thanks.

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -1113,6 +1118,36 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     return enableInteractiveSelection ?? !obscureText;
   }
 
+  /// The color used to paint the prompt rectangle.
+  Color get promptRectColor => _promptRectPaint.color;
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/editable.dart]: Should note that this property only impacts non-web iOS applications. Likewise for promptRectRange. 

Should also note that setting promptRectColor to null indicates that the promptRect shouldn't be drawn at all. There should be tests that cover this

File: packages/flutter/lib/src/rendering/editable.dart [hunk 5]
```diff
@@ -1113,6 +1118,36 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    if (promptRectColor == newValue)
+      return;
+
+    _promptRectPaint.color = newValue;
+    if (_promptRectRange != null)
+      markNeedsPaint();
+  }
+
+  TextRange _promptRectRange;
+  /// Dismisses the currently shown prompt rectangle and displays a new prompt rectangle
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/editable.dart]: shown => displayed

File: packages/flutter/lib/src/rendering/editable.dart [hunk 6]
```diff
@@ -1113,6 +1118,36 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  /// over [newRange] in the given color [promptRectColor].
+  ///
+  /// When set to null, the currently shown prompt rectangle (if any) will be dismissed.
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/editable.dart]: shown => displayed

**Review by HansMuller — APPROVED** [review]
LGTM too
