### PR TITLE
_TabBarViewState should dispose created instances of PageController.

### LINKED ISSUE #133755: Memory Leak: _TabBarViewState creates a new PageController each time didChangeDependencies is called
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

PR that marks the issue: https://github.com/flutter/flutter/pull/133759

`_TabBarViewState` creates a new `PageController` each time `didChangeDependencies` is called. 
The previous instances of the `PageController` isn't disposed.
The latest instance of `PageController` isn't disposed in the `dispose` method as well.

Declaration of the `PageController`:
```dart
class _TabBarViewState extends State<TabBarView> {
   ...
   late PageController _pageController;
   ...
```
https://github.com/flutter/flutter/blob/5e16d2ca757fe26c4b728782cec23ec9b17394b3/packages/flutter/lib/src/material/tabs.dart#L1776-L1776

<br>

Creation of the `PageController` in `didChangeDependencies`:
```dart
...
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _updateTabController();
    _currentIndex = _controller!.index;
    _pageController = PageController(
      initialPage: _currentIndex!,
      viewportFraction: widget.viewportFraction,
    );
  }
...
```
https://github.com/flutter/flutter/blob/5e16d2ca757fe26c4b728782cec23ec9b17394b3/packages/flutter/lib/src/material/tabs.dart#L1839-L1847

<br>

`dispose()` method:
```dart
...
  @override
  void dispose() {
    if (_controllerIsValid) {
      _controller!.animation!.removeListener(_handleTabControllerAnimationTick);
    }
    _controller = null;
    // We don't own the _controller Animation, so it's not disposed here.
    super.dispose();
  }
...
```
https://github.com/flutter/flutter/blob/5e16d2ca757fe26c4b728782cec23ec9b17394b3/packages/flutter/lib/src/material/tabs.dart#L1865-L1872

### Expected results

All the instances of the `PageController` are disposed.

### Actual results

All the instances of the `PageController` aren't disposed.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-12.0.pre.135, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-12.0.pre.135 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 5e16d2ca75 (2 hours ago), 2023-08-31 04:51:40 -0400
    • Engine revision 5156c03344
    • Dart version 3.2.0 (build 3.2.0-122.0.dev)
    • DevTools version 2.26.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/133755

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -1867,6 +1872,9 @@ class _TabBarViewState extends State<TabBarView> {
       _controller!.animation!.removeListener(_handleTabControllerAnimationTick);
     }
     _controller = null;
+    if (_pageControllerCreated) {
+      _pageController.dispose();
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/tabs.dart:1876]: should we set `_pageControllerCreated` back to `false` here?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/tabs.dart:1876]: For my understanding `_pageControllerCreated` is needed because `dispose()` may be called before the controller is created in `didChangeDependencies`?

Comment (chunhtai) [reply packages/flutter/lib/src/material/tabs.dart:1876]: I think this is fine, once it is disposed, it should not be called in didChangeDependencies again.

Comment (chunhtai) [reply packages/flutter/lib/src/material/tabs.dart:1876]: That being said I don't think you need this property, didchangedependencies must be called before dispose is called. you should be able to assume _pageController is not null at this point.

Comment (polina-c) [reply packages/flutter/lib/src/material/tabs.dart:1876]: _pageController is not nullable and late
This means _pageControllerCreated should be set after the controller is created and when it is not disposed yet. 

Renamed to _pageControllerCreatedAndNotDisposed.

Comment (chunhtai) [reply packages/flutter/lib/src/material/tabs.dart:1876]: If this is the case, it defeat the purpose of `late`, it can be null when it is actually used. I think either we assume the State will be used in the expected manner and directly call dispose without any check, or we convert it to nullable (you can have a getter to un-null it)

Comment (polina-c) [reply packages/flutter/lib/src/material/tabs.dart:1876]: didchangedependencies is invoked first time for non initialized value

File: packages/flutter/lib/src/material/tabs.dart [hunk 2]
```diff
@@ -1840,6 +1840,7 @@ class _TabBarViewState extends State<TabBarView> {
     super.didChangeDependencies();
     _updateTabController();
     _currentIndex = _controller!.index;
+    _pageController?.dispose();
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/tabs.dart:1843]: actually this seems like a bug that we are recreating page controller every time. I am not sure why this is needed. My gut feeling told me this should just be `_pageController ??= PageController(...)`.

However, this seems like out of the scope of this pr. Can you add a todo here to remind us to investigate this further?

**Review by chunhtai — APPROVED** [review]
LGTM
