### PR TITLE
Fix `Drawer` examples are missing `dartpad` tag

### LINKED ISSUE #134217: `Drawer` examples are misssing `dartpad` tag
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Go to master API docs for [Drawer](https://master-api.flutter.dev/flutter/material/Drawer-class.html) and find the following are not loading
https://master-api.flutter.dev/flutter/material/Drawer-class.html#material.Drawer.1
https://master-api.flutter.dev/flutter/material/Drawer-class.html#material.Drawer.2

Go to stable API docs for [Drawer](https://api.flutter.dev/flutter/material/Drawer-class.html) and find the following examples are not loading
https://api.flutter.dev/flutter/material/Drawer-class.html#material.Drawer.2

These examples were updated in https://github.com/flutter/flutter/pull/130523 with `api/examples` examples. However, tool tag is still using `snippet` instead of `dartpad`.

### Expected results

Dartpad examples load

### Actual results

Dartpad examples don't load

### Code sample

~

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

~

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [`Drawer` examples are misssing `dartpad` tag]( https://github.com/flutter/flutter/issues/134217)

these examples were updated in https://github.com/flutter/flutter/pull/130523 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -93,10 +93,10 @@ const Duration _kBaseSettleDuration = Duration(milliseconds: 246);
 /// ** See code in examples/api/lib/material/drawer/drawer.0.dart **
 /// {@end-tool}
 ///
-/// {@tool snippet}
+/// {@tool dartpad}
 /// This example shows how to migrate the above [Drawer] to a [NavigationDrawer].
 ///
-/// ** See code in examples/api/lib/material/navigation_drawer/navigation_drawer.1.dart **
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/drawer.dart:99]: Looks like it was renamed in https://github.com/flutter/flutter/pull/130521

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
