### PR TITLE
Fix dragging scrollbar down causes unexpected behavior when scrollable has a negative minScrollExtent

### LINKED ISSUE #170246: Scrollbar unexpectedly jumps to the starting position when dragging down, with CustomScrollView's `center` was set
### Steps to reproduce

1. In a `CustomScrollView` widget, set the `center` property with a `GlobalKey`
2. In the `slivers`, place some sliver widgets, and ensure one of them is set with the same `GlobalKey`
3. Wrap the CustomScrollView with a `RawScrollBar`
4. First scroll the screen to top, then **drag** the scrollbar to move down a small distance.

### Expected results

The scrollbar should move down within a small distance according to the user's gestures.

### Actual results

The scrollbar unexpectedly jumps to the starting position and then scrolls down.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final centerKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text("CustomScrollView demo")),
        body: RawScrollbar(
          thumbVisibility: true,
          thumbColor: Colors.blueAccent,
          thickness: 20,
          child: CustomScrollView(
            center: centerKey,
            slivers: [
              SliverToBoxAdapter(child: Container(height: 600.0, color: Colors.redAccent)),
              SliverToBoxAdapter(key: centerKey, child: Container(height: 600.0)),
              SliverToBoxAdapter(child: Container(height: 600.0, color: Colors.amberAccent)),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/e6fdff82-db9e-4db5-81dc-ba78b3e7e4a1

</details>

### Logs

<details close><summary>Logs</summary>

```console
None
```

</details>

### Flutter Doctor output

<details close><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.2, on macOS 15.2 24C101 darwin-arm64, locale zh-Hans-CN) [532ms]
    • Flutter version 3.32.2 on channel stable at /Users/greyhuiliu/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8defaa71a7 (5 days ago), 2025-06-04 11:02:51 -0700
    • Engine revision 1091508939
    • Dart version 3.8.1
    • DevTools version 2.45.1
    • Pub download mirror https://mirrors.tencent.com/dart-pub/
    • Flutter download mirror https://mirrors.tencent.com/flutter/

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1,585ms]
    • Android SDK at /Users/greyhuiliu/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,207ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [16ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [15ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.99.3) [14ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.112.0

[✓] Proxy Configuration [52ms]
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (3 available) [6.2s]
    • iPhone 16 (mobile) • BB471954-F1E7-4186-A8F7-5528FF926CC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-3 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 137.0.7151.69
    ! Error: Browsing on the local area network for Grey's. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [442ms]
    • All expected network resources are available.

```

</details>

### PR DESCRIPTION
**Pull request by greyovo**
This PR fixed #170246.

In the original method for calculating the thumb position based on the offset, the minimum scroll distance was assumed to be 0 by default, which caused the scrollbar offset fraction to be constrained between 0 and 1. However, when minScrollExtent is negative, this range is incorrect.

Modifications are listed below:
- The valid range has been updated to be between `minScrollExtent / scrollableExtent` and `maxScrollExtent / scrollableExtent`.
- Added corresponding test cases for this change.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 1]
```diff
@@ -2305,9 +2310,44 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
...
+      await dragGesture.up();
+      await tester.pumpAndSettle();
+
+      // The view should have scrolled by the amount dragged.
+      expect(scrollController.offset - minScrollExtent, 1800 * scrollDownAmount / 600);
+      expect(
+        find.byType(RawScrollbar),
+        paints..rect(rect: trackRect)
+          ..rect(
+            rect: thumbRectBefore.shift(const Offset(0.0, scrollDownAmount)),
```
Comment (Piinks) [inline packages/flutter/test/widgets/scrollbar_test.dart:2351]: Oo slick! I don't think I knew about shift - TIL!

**Review by Piinks — APPROVED** [review]
Hey @greyovo welcome! Thanks for contributing.
This change LGTM, but there is an analyzer failure I can't see, probably due to the current GCP outage. I will circle back on that while I find another reviewer.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 2]
```diff
@@ -2277,11 +2277,16 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
         ),
       );
       await tester.pumpAndSettle();
+
+      // Rectangle for the track of scrollbar.
+      // The default thickness of thumb is 6.0, hence topLeft = 800.0 - 6.0 = 794.0
```
Comment (justinmc) [inline packages/flutter/test/widgets/scrollbar_test.dart:2282]: Thank you for explaining the number 👍

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 3]
```diff
@@ -2305,9 +2310,44 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
...
+            color: const Color(0x66BCBCBC),
+          ),
+      );
+
+      // Regression test for issue: https://github.com/flutter/flutter/issues/170246
+      // First scroll to the top, then drag the thumb to scroll down.
+      final double minScrollExtent = scrollController.position.minScrollExtent; // -600
+      await tester.runAsync(() async {
+        scrollController.jumpTo(minScrollExtent);
+      });
```
Comment (justinmc) [inline packages/flutter/test/widgets/scrollbar_test.dart]: Why do you need runAsync here?

**Review by justinmc — APPROVED** [review]
LGTM 👍 . Thank you for filing this issue and then fixing it!

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 4]
```diff
@@ -669,9 +669,11 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
   /// The thumb's corresponding scroll offset in the track.
   double getThumbScrollOffset() {
     final double scrollableExtent = _lastMetrics!.maxScrollExtent - _lastMetrics!.minScrollExtent;
+    final double maxFraction = _lastMetrics!.maxScrollExtent / scrollableExtent;
+    final double minFraction = _lastMetrics!.minScrollExtent / scrollableExtent;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/scrollbar.dart:674]: is is possible for both min/max scroll extent to be negative/positive infinite as well as scrollable Extent?

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scrollbar.dart:674]: At least for one case, when the scroll extent is infinite the scrollbar is disabled.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/scrollbar.dart:674]: gotcha, in that case, I think we should either handle it in code or assert if we are confident that is this method won't be called when it is infinite

**Review by chunhtai — APPROVED** [review]
LGTM, just one nit

File: packages/flutter/test/widgets/scrollbar_test.dart (hunk 3 above)
Comment (greyovo) [reply packages/flutter/test/widgets/scrollbar_test.dart]: Oops, I thought `jumpTo` is an async function. I will remove it. Thanks!

**Comment by greyovo** [comment]
@chunhtai I added an assertion in `getThumbScrollOffset`, please have a look :)

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 4 above)
Comment (greyovo) [reply packages/flutter/lib/src/widgets/scrollbar.dart:674]: > gotcha, in that case, I think we should either handle it in code or assert if we are confident that is this method won't be called when it is infinite

Update: added the assertion

**Comment by chunhtai** [comment]
Looks like there is some formatting issue
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8712195095568406145/+/u/run_test.dart_for_analyze_shard_and_subshard_None/stdout

can you run dart formatter on the files?

**Comment by chunhtai** [comment]
> @chunhtai I added an assertion in `getThumbScrollOffset`, please have a look :)

Thanks, LGTM

**Comment by greyovo** [comment]
I ran `dart format` on the files I modified, but it also formatted some parts that I didn't change. Is this the expected behavior?

**Comment by chunhtai** [comment]
> I ran `dart format` on the files I modified, but it also formatted some parts that I didn't change. Is this the expected behavior?

no It is not, do you have outdated pub? try runing `flutter update-packages`

**Comment by chunhtai** [comment]
looks like you may have longer line limit?

**Comment by Piinks** [comment]
Hmm, another thing might be that it is trying to format with Dart 3.8 instead of 3.7. The framework has not bumped yet. Maybe too try running `flutter clean`?

**Comment by greyovo** [comment]
Thank you all for the kindness help. ❤️ I reverted the wrong commit and updated with a new one.
