### PR TITLE
Adjust padding for Cupertino sheet content

### LINKED ISSUE #162215: FloatingActionButton is out of frame when trying to place it in CupertinoSheetRoute
### Steps to reproduce

I wanted to try out [PR](https://github.com/flutter/flutter/pull/157568#issuecomment-2590955571)'s recently implemented CupertinoSheetRoute, so I ran [sheet.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/sheet.dart) and examples' [cupertino_sheet.0.dart](https://github.com/MitchellGoodwin/flutter/blob/1546d7c8d3c86cbb41a482a131dbef552130b106/examples/api/lib/cupertino/sheet/cupertino_sheet.0.dart).
This works fine.
Next, I wanted to add a FloatingActionButton to this code.
CupertinoPageScaffold does not have a floatingActionButton property, so I changed it to Scaffold and placed a floatingActionButton.
However, this code places the floatingActionButton partially outside the frame.

### Expected results

FloatingActionButton should be displayed in the frame in the Sheet.

### Actual results

FloatingActionButton is displayed out of frame in Sheet

### Code sample

<details open><summary>Code sample</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_engineer_codecheck/sheet.dart';

/// Flutter code sample for [CupertinoSheetRoute].

void main() {
  runApp(const CupertinoSheetApp());
}

class CupertinoSheetApp extends StatelessWidget {
  const CupertinoSheetApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(title: 'Cupertino Sheet', home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Sheet Example'),
        automaticBackgroundVisibility: false,
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoButton.filled(
              onPressed: () {
                Navigator.of(context).push(
                  CupertinoSheetRoute<void>(
                    builder: (BuildContext context) => const _SheetScaffold(),
                  ),
                );
              },
              child: const Text('Open Bottom Sheet'),
            ),
          ],
        ),
      ),
    );
  }
}

class _SheetScaffold extends StatelessWidget {
  const _SheetScaffold();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('CupertinoSheetRoute'),
            CupertinoButton.filled(
              onPressed: () {
                Navigator.of(context).maybePop();
              },
              child: const Text('Go Back'),
            ),
            const Text('You can also close this sheet by dragging downwards'),
            CupertinoButton.filled(
              onPressed: () {
                Navigator.of(context).push(
                  CupertinoSheetRoute<void>(
                    builder: (BuildContext context) => const _SheetScaffold(),
                  ),
                );
              },
              child: const Text('Push Another Sheet'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| iOS | Android |
|----------|----------|
|   |          | 
</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 13.5.2 22G91 darwin-arm64, locale ja-JP)
    • Flutter version 3.27.1 on channel stable at /Users/yamamotohiroto/fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (6 weeks ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/yamamotohiroto/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/yamamotohiroto/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.93.1)
    • VS Code at /Users/yamamotohiroto/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • iPhone (mobile)                 • 00008120-000A5D180E01A01E            • ios            • iOS 17.6.1 21G93
    • iPhone 15 (mobile)              • B02EDDD3-93FB-489F-93B1-A8BFA65FD1C3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.267

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #162215 and partially supports #162181.

The Cupertino sheet had two issues layout: It still had MediaQuery padding at the top of the screen as if there was safe area content to avoid and some of the sheet was permanently offscreen. This caused a FloatingActionButton to be clipped, but if you put a scrolling widget in the sheet with text at the very bottom, it was impossible to scroll the text into view. This PR removes the top padding, and changes the bottom padding to equal the amount offscreen.

Before:
Screenshot 2025-01-30 at 11 21 36 AM

After:
Screenshot 2025-01-30 at 11 19 54 AM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 1]
```diff
@@ -456,9 +461,19 @@ class CupertinoSheetRoute<T> extends PageRoute<T> with _CupertinoSheetRouteTrans
 
   @override
   Widget buildContent(BuildContext context) {
-    return CupertinoUserInterfaceLevel(
-      data: CupertinoUserInterfaceLevelData.elevated,
-      child: _CupertinoSheetScope(child: builder(context)),
+    final double bottomPadding = MediaQuery.sizeOf(context).height * _kTopGapRatio;
+
+    return MediaQuery.removePadding(
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/sheet.dart:466]: I didn't realize MediaQuery.removePadding was a thing, nice.

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 2]
```diff
@@ -11,13 +11,18 @@ import 'interface_level.dart';
 import 'route.dart';
 import 'theme.dart';
 
+// The distance from the top of the open sheet to the top of the screen, as a ratio
+// of the total height of the screen. Found from eyeballing a simulator running
+// iOS 18.0.
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/sheet.dart:16]: Nit: Have you tried this PR out on iPad? If not and you have time maybe give it a shot, just to double check that this proportion still looks ok on the bigger screen.

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 3]
```diff
@@ -638,11 +653,9 @@ class _CupertinoDownGestureDetectorState<T> extends State<_CupertinoDownGestureD
   void _handleDragUpdate(DragUpdateDetails details) {
     assert(mounted);
     assert(_downGestureController != null);
-    final double topGapRatio = (_kBottomUpTween as Tween<Offset>).end?.dy ?? 0.08;
     _downGestureController!.dragUpdate(
-      // Devide by size of the sheet. The gap between the top of the sheet and
-      // top of the screen is 0.08.
-      details.primaryDelta! / (context.size!.height - (context.size!.height * topGapRatio)),
+      // Devide by size of the sheet.
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/sheet.dart:657]: Nit: "Divide"

File: packages/flutter/test/cupertino/sheet_test.dart [hunk 4]
```diff
@@ -649,6 +649,99 @@ void main() {
...
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.tap(find.text('Push Page 2'));
+    await tester.pumpAndSettle();
+
+    expect(tester.getSize(find.byType(Container)).height, 600.0 - (600.0 * 0.08));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/sheet_test.dart:686]: Nit: Maybe declare a _kTopGapRatio variable in the test and use it here, just so it's more obvious where the 0.08 comes from.

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: 

Looks like you have an analyzer failure FYI.

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 2 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/sheet.dart:16]: It looks ok. Natively sheets adapt to a modal type view though. So there's nothing to compare against.
Screenshot 2025-01-31 at 2 15 12 PM

Comment (justinmc) [reply packages/flutter/lib/src/cupertino/sheet.dart:16]: Oh I didn't realize that. Should we consider doing something similar?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/sheet.dart:16]: I'll create an issue for it, but I think it's going to be p3.

**Comment by muttsu-623** [comment]
Hi @MitchellGoodwin !

I've met this issue. I appreciate your work! Thank you so much ❤️

Do you know when this fix will be released 👀 ?

**Comment by MasatoYamamotoo** [comment]
@muttsu-623 
maybe 3.30??

https://github.com/flutter/flutter/issues/161460#issuecomment-2660347291

**Comment by MitchellGoodwin** [comment]
Apologies, I missed this comment. This is currently on the beta build and will be a part of the next stable release. Stable release dates aren't public... But they can be guessed at by looking around 😄
