### PR TITLE
Pasting collapses the selection and puts it after the pasted content

### LINKED ISSUE #98677: Cursor should collapse after a paste
When pasting onto a non-collapsed selection, the selection should collapse.  Confirmed on native Mac, Windows, Android and iOS.  I'd be shocked if Linux isn't the same too.

If you paste with the keyboard while the cursor is offscreen, the cursor should be scrolled into view, but it isn't.

### Steps to reproduce

  1. Run any app with a text field, such as the one below.
  2. Enter some text, like "asdf".
  3. Copy any text.
  4. Make any selection of length > 0.
  5. Paste (using the keyboard or using the toolbar).

Expected: The cursor ends up collapsed at the end of the pasted text.
Actual: The pasted text is selected.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

Related: https://github.com/flutter/flutter/pull/98604#discussion_r809286506

### PR DESCRIPTION
**Pull request by justinmc**
Previously, Flutter kept pasted content selected:

  1. "[foo]"
  2. Paste "bar"
  3. "[bar]"

But native platforms collapse the selection like this:

  1. "[foo]"
  2. Paste "bar"
  3. "bar|"

This PR makes Flutter match this native behavior.

Fixes https://github.com/flutter/flutter/issues/98677

### CODE REVIEW

**Review by Renzo-Olivares — COMMENTED** [review]
LGTM besides the failing linux_web_tests_0. Looks like it's failing when trying to select the text.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -1711,7 +1711,14 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
 
-    _replaceText(ReplaceTextIntent(textEditingValue, data.text!, selection, cause));
+    // After the paste, the cursor should be collapsed and located after the
+    // pasted content.
+    final int lastSelectionIndex = math.max(selection.baseOffset, selection.extentOffset);
+    final TextEditingValue collapsedTextEditingValue = textEditingValue.copyWith(
+      selection: TextSelection.collapsed(offset: lastSelectionIndex),
+    );
+
+    _replaceText(ReplaceTextIntent(collapsedTextEditingValue, data.text!, selection, cause));
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:1721]: the first arg of the `ReplaceTextIntent` constructor should be the current `TextEditingValue` iirc. I feel it would easier to understand if we just call `userUpdateTextEditingValue` here with the updated text editing value.

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:1721]: Agreed, that feels more in the spirit of this stuff.  Will do.
