### PR TITLE
Use correct locale for `CupertinoDatePicker` weekday

### LINKED ISSUE #141875: CupertinoDatePicker - Day of the week always in EN (locale issue)
### Steps to reproduce

I have implemented a picker with **CupertinoDatePicker** to select a day within a reservation process. I need the day of the week to be displayed to help the users in the booking so I have enabled the following parameter:
```dart
showDayOfWeek: true,
```
The issue occurs when combining this **showDayOfWeek: true** and this mode:  
```dart
mode: CupertinoDatePickerMode.date
```
In this case the day of the week always displays in EN. The application supports EN, ES, and CA. One might think it's because the localizations are not properly configured, but the months appear in the correct language according to the device's locale. However, the day of the week does not. Additionally, if the mode is changed to  
```dart
mode: CupertinoDatePickerMode.dateAndTime
```
the day of the week appears in the proper language. I am attaching screenshots.

### Expected results

The day of the week should vary according to the locale, just like the language of the months changes

### Actual results

The day of the week always appears in English

### Code sample

I have this locale configuration in Material App of main.dart
<details open><summary>Code sample</summary>

```dart
 supportedLocales: const [
        Locale('es'), // Spanish
        Locale('ca'), // Catalan
        Locale('en'), // English
      ],
      locale: locale,
      onGenerateRoute: (_) => SplashScreen.route(),
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
```
That's the implementation of CupertinoDatePickerWidget. The error occurs specifically in date mode.
```dart
CupertinoDatePicker(
          mode: CupertinoDatePickerMode.date,
          showDayOfWeek: true,
          minimumDate: DateTime(now.year, now.month, now.day, 0, 0, 0, 0),
          maximumYear: DateTime.now().year + 1,
          minimumYear: DateTime.now().year,
          initialDateTime: widget.dayPicked,
          maximumDate: DateTime.now().add(const Duration(days: 365)),
          onDateTimeChanged: (datePicked) {
            widget.onDateChanged!(datePicked);
          }),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
ca1
es1
ok1
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 12.6.9 21G726 darwin-x64, locale es-ES)
    • Flutter version 3.13.5 on channel stable at /Users/edumolins/Desktop/flutter_313
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (4 months ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/edumolins/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • 2306EPN60G (mobile) • 4P4PNVOZBUM7QOVO • android-arm64  • Android 14 (API 34)
    • macOS (desktop)     • macos            • darwin-x64     • macOS 12.6.9 21G726 darwin-x64
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
#120052 introduces the `showDayOfWeek` flag to `CupertinoDatePicker` for mode `CupertinoDatePickerMode.date`, but the default `en` locale from `DefaultCupertinoLocalizations` is always used for the day of the week:

https://github.com/flutter/flutter/blob/5103d757436124a08e6a8024ebacbf0cf4b2bacf/packages/flutter_localizations/lib/src/cupertino_localizations.dart#L116-L119

This PR introduces a new `intl.DateFormat` `weekdayFormat` to replace the default with the abbreviated weekday for any supported locales.

| Before | After | 
| --- | --- |
|  Screenshot 2024-07-09 at 5 08 43 PM  |  Screenshot 2024-07-09 at 5 08 11 PM |

Fixes #141875

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/localizations.dart [hunk 1]
```diff
@@ -343,7 +343,7 @@ class DefaultCupertinoLocalizations implements CupertinoLocalizations {
   const DefaultCupertinoLocalizations();
 
   /// Short version of days of week.
-  static const List<String> shortWeekdays = <String>[
+  static const List<String> _shortWeekdays = <String>[
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/localizations.dart:346]: Technically, this is a breaking change, but I don't know if this is worth deprecating? I don't know why somebody would be using a static list of english only day names from a localization class, but if they are maybe we let it break their app, and they can just make their own static list.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!
