### PR TITLE
[tool] Install the corresponding APK in `flutter run`

### LINKED ISSUE #111585: [tool] `flutter run` runs only `app.apk`
## Steps to Reproduce

1. Configure flavors for the Android app, such as "inside".
2. `flutter run --flavor=inside`
3. The `Installing xxx.apk` has a different path from `Built xxx.apk`.

`android/app/build.gradle`:
```groovy
//......
android {
    //......
    flavorDimensions "app"
    productFlavors {
        inside {}
        play {}
    }
}
//......
```

image

(`LocalFile` is my additional print.)

```
[!] Flutter (Channel master, 3.4.0-19.0.pre.254, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
    • Flutter version 3.4.0-19.0.pre.254 on channel master at X:\SDK\flutter-master
    ! Upstream repository https://github.com/AlexV525/flutter is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/AlexV525/flutter to dismiss this error.
    • Framework revision 6b1f84fe10 (66 minutes ago), 2022-09-14 09:46:00 -0700
    • Engine revision 179d528f6a
    • Dart version 2.19.0 (build 2.19.0-197.0.dev)
    • DevTools version 2.17.0
```

### LINKED ISSUE #113620: #112768 broke `Mac_android run_release_test`
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20run_release_test/7250

Here is the test failure output:

```
[run_release_test] [STDERR] Task failed: Did not find expected line
[run_release_test] [STDERR] 
[run_release_test] [STDERR] Installing build/app/outputs/flutter-apk/app.apk...
[run_release_test] [STDERR] 
[run_release_test] [STDERR] in flutter run --release stdout
[run_release_test] [STDERR] 
[run_release_test] [STDERR] [Installing build/app/outputs/flutter-apk/app-release.apk...         3.2s, Flutter run key commands., h List all available interactive commands., c Clear the screen, q Quit (terminate the application on the device)., Application finished.]
[run_release_test] [STDERR]   
[run_release_test] [STDERR] 
[run_release_test] [STDERR] Stack trace:
[run_release_test] [STDERR] bin/tasks/run_release_test.dart 153:3                      _findNextMatcherInList
[run_release_test] [STDERR] bin/tasks/run_release_test.dart 115:7                      main.<fn>.<fn>
[run_release_test] [STDERR] ===== asynchronous gap ===========================
[run_release_test] [STDERR] dart:async                                                 _CustomZone.registerBinaryCallback
[run_release_test] [STDERR] package:flutter_devicelab/framework/framework.dart 274:26  _TaskRunner._performTask.<fn>
[run_release_test] [STDERR] package:stack_trace                                        Chain.capture
[run_release_test] [STDERR] package:flutter_devicelab/framework/framework.dart 273:11  _TaskRunner._performTask
[run_release_test] [STDERR] package:flutter_devicelab/framework/framework.dart 166:43  _TaskRunner.run
```

Looks like this should be an easy fix here: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/run_release_test.dart#L117

### PR DESCRIPTION
**Pull request by AlexV525**
Revert #113614. Fix #111585, #113620.

The PR stops copying `app.apk` for `flutter run` and makes the tool installs exactly the generated APK file, which corrects the console's output too. Also, SHA1 will be generated for all generated APKs in the batch.

## Filename comparison (DEBUG Mode)

| Install APK file| Before | After |
|-------|-------------|-----------|
| No flavor | app.apk | app-debug.apk |
| Flavor configured | app.apk | app-flavor-debug.apk |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

File: dev/devicelab/bin/tasks/run_release_test.dart [hunk 1]
```diff
@@ -114,8 +114,8 @@ void main() {
 
       _findNextMatcherInList(
         stdout,
-        (String line) => line.startsWith('Installing build/app/outputs/flutter-apk/app.apk...'),
-        'Installing build/app/outputs/flutter-apk/app.apk...',
+        (String line) => line.startsWith('Installing build/app/outputs/flutter-apk/app-release.apk...'),
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/run_release_test.dart:117]: For posterity, this is the new fix for https://github.com/flutter/flutter/issues/113620 that caused the previous PR to get reverted.
