### PR TITLE
Doc fixes

### LINKED ISSUE #35886: Assets affecting layout of code snippets in API Docs
Code snippets in the API docs that make use of the `Sample in an App` feature have layout issues when an asset has been embedded directly within the snippet. This does not affect running sample apps, as the asset is commented out when the app is generated.
These assets should be moved outside of the snippet for better readability in the API documentation.

Screen Shot 2019-07-10 at 9 08 37 AM

Screen Shot 2019-07-10 at 9 08 43 AM

### LINKED ISSUE #35888: Snippets that make use of 'Sample in an App' templates need validation
The Form `Sample in an App` snippet does not build correctly when run according to the directions specified by the API documentation.
See here: https://master-api.flutter.dev/flutter/widgets/Form-class.html
The error is not one accounted for by the sample code analyzer. 

In the case of the Form snippet, it should make use of the `scaffold` template instead of the `material` template.
Other snippets that make use of this template should be verified for any other issues.

### PR DESCRIPTION
**Pull request by Piinks**
Fixes #35886 - Only animation assets were affecting layout, and there was only one left to be fixed.
Fixes #35888 - All `Sample in an App` templates verified, Form was the only one that was broken.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/painting/text_style.dart [hunk 1]
```diff
@@ -130,14 +130,10 @@ const String _kColorBackgroundWarning = 'Cannot provide both a backgroundColor a
 /// ```
 /// {@end-tool}
 ///
-/// {@tool sample}
```
Comment (Piinks) [inline packages/flutter/lib/src/painting/text_style.dart]: Using the `{@tool sample}` without any code results in an empty code box:
Screen Shot 2019-07-10 at 9 38 06 AM

**Review by goderbauer — APPROVED** [review]
LGTM
