### PR TITLE
InteractiveViewer parameter to return to pre-3.3 trackpad/Magic Mouse behaviour

### LINKED ISSUE #114257: InteractiveViewer scaling/zooming behavior change from 3.0.5 to 3.3.x
My `macos` app uses an `InteractiveViewer`.    

When built with Flutter `3.0.5` I can zoom/scale the viewer content using the mouse scroll wheel.  Using a trackpad I can zoom with a "2-finger vertical-pan" gesture.

When built with a recent Flutter `3.3.x` version I can no longer zoom the content via the mouse.   If I use a trackpad I can zoom using a pinch gesture.

I suspect this change in behavior is related to https://github.com/flutter/flutter/issues/107005, but not sure.   

Are there docs that I'm not finding that describe this change in behavior?

What I want to know is how to zoom the `InteractiveViewer` using the old behavior, on `macos`.   Do I need to do this by capturing the events and programmatically zooming using a `TransformationController`?

## Steps to Reproduce

1. Install Flutter 3.0.5 (`git checkout 3.0.5`, `flutter doctor`)
2. Execute `flutter run` on the code sample 

**Expected and Actual results:** 

Zooming works using the mouse scroll wheel and trackpad 2-finger vertical-pan gesture.

3. Install current Flutter 3.3.x (`flutter channel stable` `flutter upgrade`)
5. Execute `flutter run` on the code sample 

**Expected results:** 

Able to zoom using the mouse scroll wheel and trackpad 2-finger vertical-pan gesture..

**Actual results:** 

Only able to scroll via trackpad pinch gesture.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: InteractiveViewer(
        boundaryMargin: const EdgeInsets.all(double.infinity),
        minScale: 0.1,
        maxScale: 1.6,
        child: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: <Color>[Colors.orange, Colors.red],
              stops: <double>[0.0, 1.0],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by moffatman**
After trackpad gestures rewrite, `InteractiveViewer` behaves differently, panning around instead of zooming when scrolling up/down on trackpad and magic mouse. If the old behaviour is desired, this new parameter `trackpadPanShouldActAsZoom` can allow that.

To reproduce exactly, zooming inertia is added to `InteractiveViewer`, this should also benefit touch usage.

Also fixed a bug where the `ScaleGestureRecognizer` had the wrong `focalPointDelta` on the first update due to not updating the transform, this is now covered by the `InteractiveViewer` test case. 

Fixes #114257

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by moffatman** [comment]
Will write the tests after https://github.com/flutter/flutter/pull/114312 is merged

**Comment by goderbauer** [comment]
fly-by comment: Looks like it's failing some existing tests. Could you take a look at the checks?

File: packages/flutter/test/widgets/interactive_viewer_test.dart [hunk 1]
```diff
@@ -1742,6 +1742,46 @@ void main() {
...
+      await tester.pump();
+      expect(transformationController.value.getMaxScaleOnAxis(), 1.0);
+      await tester.sendEventToBinding(pointer.panZoomUpdate(center, pan: const Offset(0, 81)));
+      await tester.pump();
+      expect(transformationController.value.getMaxScaleOnAxis(), moreOrLessEquals(1.499302500056767));
+
+      // Send a horizontal scroll (should have no effect).
+      await tester.sendEventToBinding(pointer.panZoomUpdate(center, pan: const Offset(81, 81)));
+      await tester.pump();
+      expect(transformationController.value.getMaxScaleOnAxis(), moreOrLessEquals(1.499302500056767));
```
Comment (justinmc) [inline packages/flutter/test/widgets/interactive_viewer_test.dart:1779]: Nit: To avoid worrying about number precision here, another options is:

```dart
const double defaultScale = 1.0;
expect(transformationController.value.getMaxScaleOnAxis(), defaultScale);
await tester.sendEventToBinding(pointer.panZoomUpdate(center, pan: const Offset(0, 81)));
await tester.pump();
final double scale = transformationController.value.getMaxScaleOnAxis();
expect(scale, greaterThan(defaultScale));

// Send a horizontal scroll (should have no effect).
await tester.sendEventToBinding(pointer.panZoomUpdate(center, pan: const Offset(81, 81)));
await tester.pump();
expect(transformationController.value.getMaxScaleOnAxis(), equals(scale));
```

I don't know which is better though, up to you.

File: packages/flutter/lib/src/gestures/scale.dart [hunk 2]
```diff
@@ -331,6 +353,12 @@ class ScaleGestureRecognizer extends OneSequenceGestureRecognizer {
 
   Matrix4? _lastTransform;
 
+  /// Whether scrolling up/down on a trackpad or Magic Mouse should map to
```
Comment (justinmc) [inline packages/flutter/lib/src/gestures/scale.dart:356]: From the style guide, the first paragraph should be a single sentence that briefly describes what the parameter is.

File: packages/flutter/lib/src/gestures/scale.dart [hunk 3]
```diff
@@ -331,6 +353,12 @@ class ScaleGestureRecognizer extends OneSequenceGestureRecognizer {
...
+  /// zooming in/out. Settings this to true will help in reproducing behaviours
+  /// pre-Flutter 3.3 trackpad gestures rewrite.
+  ///
+  /// Defaults to false.
+  bool trackpadPanShouldActAsZoom;
```
Comment (justinmc) [inline packages/flutter/lib/src/gestures/scale.dart:361]: Nit: As usual for me, I feel like there is a better name we could use but I don't know what it is...  Maybe `trackpadScrollCausesScale` or `trackpadScrollScales`?  I can think of two possible problems with the current name:

  1. Readers might not know what a "trackpad pan" gesture is.  I think it could possibly be ambiguous as to whether it uses one or two fingers.  Maybe using "scroll" is more specific, because it's the same gesture you would use to scroll a webpage etc.?
  2. I've tried to make all of the naming around zooming/scaling just use the word "scale" for consistency, so I think this one should use it too.

**Review by justinmc — COMMENTED** [review]
Overall I like this approach, thanks for the PR.  I'm really happy we'll have inertial scaling.

It's a shame that we have to add a flag to the InteractiveViewer parameters.  These things tend to bloat quickly.  I can't think of another approach that would solve this without a major refactor to InteractiveViewer, though.

**Comment by justinmc** [comment]
CC @matthew-carroll, you were talking about alternative architectures for InteractiveViewer.  Any thoughts on how this could be done without bloating the parameter list?  This is more evidence in support of a refactor for InteractiveViewer I think.

File: packages/flutter/lib/src/gestures/scale.dart [hunk 4]
```diff
@@ -36,26 +36,44 @@ enum _ScaleState {
...
+  Offset focalPoint(bool verticalPanShouldActAsZoom) {
+    if (verticalPanShouldActAsZoom) {
+      return _position;
+    }
+    return _position + _pan;
+  }
+
+  double scale(bool verticalPanShouldActAsZoom) {
+    if (verticalPanShouldActAsZoom) {
+      return _scale * math.exp(-_pan.dy / 200);
```
[the remark this answers is not in the document]
Comment (moffatman) [reply packages/flutter/lib/src/gestures/scale.dart:56]: For most configurability this could be an `Offset`, and multiplied by `pan.dy` to define your own custom trackpad behaviour. For example, this snippet would be would be `Offset(0, -200)`, but if you had `Offset(200, 0)`, it could scale when scrolling left-right. Then InteractiveViewer would pass through `Offset(0, -scaleFactor)`. But may be of limited use...

File: packages/flutter/lib/src/gestures/scale.dart (hunk 3 above)
Comment (moffatman) [reply packages/flutter/lib/src/gestures/scale.dart:361]: `trackpadScrollCausesScale` is fine with me.

**Comment by matthew-carroll** [comment]
> Any thoughts on how this could be done without bloating the parameter list?

It looks like the goal of this PR is to recover a previous gesture behavior that was lost. Given that `InteractiveViewer` is operating as a user-facing widget, I think this is a corner that you're boxed into. As long as you want a singular widget to marry layout and gestures, and you want that widget to be broadly applicable, this is what's gonna happen.

The alternative approach is a compositional approach. Pulling from the same ideas that I had in my presentation, if Flutter developers assembled their own version of `InteractiveViewer` then Flutter developers would configure behavior by way of composition, instead of adding more properties. In other words, the reason you have to add a property is because you have to facilitate both gesture behaviors. And you have to facilitate both gesture behaviors because there's no other option in the toolkit to get those jobs done.

The pseudocode from my presentation for a reimplementation of `InteractiveViewer` looked something like this:

```dart
Widget build(BuildContext context) {
  return InfiniteCanvasGestures(
    controller: _orientationController,
    child: RecyclingInfiniteViewport(
      orientation: _orientationController.orientation,
      builder: () {...},
    ),
  );
}
```

As you can see, that structure is so simple that Flutter wouldn't need to ship it. Flutter just needs to ship `InfiniteCanvasGestures` and `RecyclingInfiniteViewport`. App developers can assemble those pieces into what they want. After all, an app is literally the "application" of the Flutter toolkit.

When embracing composition, you can have a variety of those gesture widgets that know how to work with an `OrientationController`. Given that this PR enables two different interactions with a trackpad, I assume that there must be two different use-cases for trackpad interaction, right? Each of those could be captured in their own gesture widget. Worst case scenario for an app developer is that Flutter doesn't have the exact gesture behavior they need, so they copy one of these existing gesture widgets and adjust it to meet their needs. But given that Flutter, itself, would have created multiple gesture widgets, the Flutter framework developer probably made it as easy as possible to create more of them. So it's still no big deal for Flutter app developers.

All of that said, I may release a package with these very tools. If the framework wants to do that, you should let me know ASAP. Otherwise, I'll just have the Flutter Bounty Hunters create the composition tools. If we build a package for this, then I might suggest that you deprecate `InteractiveViewer` and replace it with a widget that just does the viewport layout and recycling. Let developers hook up whatever gestures they want to that thing.

**Comment by moffatman** [comment]
Do you have more detail on your proposal @matthew-carroll, it looks interesting. I have some questions, but maybe I can see if they are answered in the presentation before raising them. I did consider some sort of widget to transform gesture behaviour that could be more generally used, but I don't think we have a good way to dispatch pointer events only to a subtree.

**Comment by matthew-carroll** [comment]
@moffatman - The idea is to identify the axes of change and split responsibility along those lines.

Based on my analysis of `InteractiveViewer`, I found three axes of change: gesture response, orientation control, and viewport construction.

**Viewport Construction**
For viewport construction, you can essentially take `InteractiveViewer` and remove all gesture behavior. The value notifier for `Matrix4` can stay, but the concept of a `TransformController` should be removed. It only confuses the issue. I would turn that property into `orientation` of type `ValueNotifier<Matrix4>`.

```dart
return RecyclingInfiniteCanvas(
  orientation: orientationController.orientationNotifier,
  builder: ...,
);

return InfiniteArtboardCanvas(
  orientation: orientationController.orientationNotifier,
  builder: ...,
);

return IllustrationCanvas(
  orientation: orientationController.orientationNotifier,
  child: ...,
);
```

**Gestures**
There could be many gesture combinations for a panning, zooming, rotating canvas. In my presentation I rattled off a number of UIs that operate this way: Photoshop, Illustrator, Premiere, After Effects, Figma, Sketch, Procreate, Powerpoint, Keynote, Miro for diagrams, Max MSP for audio programming, etc. You can find pretty much any combination of gestures and keyboard shortcuts to control orientation.

What I would recommend is doing a survey of as many app UIs as possible to collect the variations on gestures. You'll probably find two or three gesture modalities that cover the vast majority of use-cases. Flutter can create gesture widgets that respond to those exact gesture combinations.

The following names are overly constrained, but they should communicate the point.
```dart
return InfiniteArtboardGestures(
  controller: orientationController,
  child: SomeViewport(...),
);

return TabletIllustrationGestures(
  controller: orientationController,
  child: SomeViewport(...),
);

return SlideshowGestures(
  child: orientationController,
  child: SomeViewport(...),
);
```

**Orientation Control**
Each of the gesture widgets is given an `OrientationController`. The purpose of an `OrientationController` is to provide all the typical orientation behaviors that a viewport would expect, in a form that's much easier to use than a `Matrix4`. For example:

```dart
abstract class OrientationController {
  ValueNotifier<Matrix4> get orientationNotifier;

  Offset get translation;
  double get zoom;
  double get zoomAsMultipleOfOriginalSize;
  double get rotation;

  void translate(Offset delta);

  void zoom(double percent);

  // This method is here because I ran into a problem when implementing standard
  // zoom controls. Zoom controls often give you set options: 100%, 110%, 120%, 130%. However,
  // if you're always multiplying a scale by the previous scale, you can't hit those numbers. Instead
  // you end up with 100%, 110%, 121%, 133.1%, 146.41%, etc. 
  void zoomToMultipleOfOriginalSize(double percent):

  void rotate(double radians);

  // Maybe more methods for mapping from screen space to orientation space and back

  // Also, maybe undo/redo methods, and/or affine transform breakdowns.
}
```

The purpose of the `OrientationController` is to provide all the reasonable expected behaviors when assembling any experience like the ones listed above. It's not an extension on `Matrix4`, it's a tool for infinite canvas orientation.

It's OK to design this controller specifically for infinite canvas orientation, because it exposes a `Matrix4`, which means you don't need to spread references to `OrientationController` into various viewports. All you need is a viewport that understands `Matrix4`. But the gesture widgets, which are built specifically for infinite canvas gestures, will want the operations that are on this controller.

**Is the Flutter framework the right place for this?**
It will probably feel strange to create all those gesture variations in the framework. And some people might complain about the specificity of the `OrientationController`.

You might be pushed to further generalize the tools that I've introduced here. But, that would defeat the purpose.

So it's worth asking, which parts, if any, should be included in the Flutter framework? Are these foundational toolkit widgets, or are they package widgets? Unfortunately, Flutter's decision to keep Material and Cupertino within the framework has really muddied such analysis. Those packages should be distributed independently. The widgets in those packages aren't fundamental to all Flutter UIs. Are any of these widgets fundamental? I could see an argument for sophisticated infinite recycling in the framework. That's essentially a 2D version of `ListView.builder`, or perhaps `CustomScrollView`. But I'm not sure about the rest.

**Comment by moffatman** [comment]
I see how you can separate the gestural interactions with the resulting transform for an infinite canvas, but InteractiveViewer also handles a finite canvas, limited to the size of the child. I don't think it can be separated in that case, the data flow is not just one-way.

**Comment by matthew-carroll** [comment]
@moffatman can you show an example of what you're describing? I didn't understand the stated issue.

**Comment by moffatman** [comment]
When InteractiveViewer is used with a finite-sized child, it shouldn't be possible to move the viewport outside of the child's bounds (unless specifically desired, for example setting the current parameter `boundaryMargin` to infinity). But in the pattern above, the `Gestures` widget won't be able to limit the `OrientationController` transform without knowing the size of the child, which is only known by the `Viewport` widget. 

```dart
Widget build(BuildContext context) {
  return SizedBox(
    width: 100,
    height: 100,
    child: FiniteCanvasGestures(
      controller: _orientationController,
      child: FiniteCanvasViewport(
        orientation: _orientationController.orientation,
        builder: () {
          return SizedBox(
            width: 500,
            height: 500,
            child: ...
          );
        },
      ),
    ),
  );
}
```

**Comment by matthew-carroll** [comment]
@moffatman in that case, composition to the rescue, again!

Using keys:

```dart
Widget build(BuildContext context) {
  return SizedBox(
    width: 100,
    height: 100,
    child: FiniteCanvasGestures(
      controller: _orientationController,
      viewportKey: _viewportKey,
      child: FiniteCanvasViewport(
        key: _viewportKey,
        orientation: _orientationController.orientation,
        builder: () {
          return SizedBox(
            width: 500,
            height: 500,
            child: ...
          );
        },
      ),
    ),
  );
}
```

Using a special controller:

```dart
Widget build(BuildContext context) {
  return SizedBox(
    width: 100,
    height: 100,
    child: FiniteCanvasGestures(
      controller: _viewportAwareOrientationController,
      child: FiniteCanvasViewport(
        controller: _viewportAwareOrientationController,
        builder: () {
          return SizedBox(
            width: 500,
            height: 500,
            child: ...
          );
        },
      ),
    ),
  );
}
```

There are probably even more compositional solutions beyond those.

I think the motif here is that composition can solve pretty much anything. But a single widget that's trying to do the job of composition will always become an unbounded dumping ground, because the set of desired behaviors is unbounded.

**Comment by matthew-carroll** [comment]
@justinmc @moffatman - Here's a situation I just ran into. I think it might help inform some of these discussions around panning and zooming content.

I have a UI that displays a series of document pages. Up to this point, those pages were displayed at the same width as the screen. So I used a `ListView`. Not a big deal.

Now, I need to add the ability to zoom in and out on that series of pages. Imagine a multi-page Google Doc where you zoom in and out. Same kind of thing.

The problem is, I'm not sure there's any existing way to do that. If I apply a `Transform.scale()` around the `ListView`, then the viewport scales up and down, but when you scale it down, the smaller viewport cuts off any pages that should now become visible above or below the fold. If I apply a `Transform.scale()` to each page within the `ListView`, the pages shrink, but the `ListView` doesn't know they shrank, so the pages become little rectangles inside of big white rectangles. In other words, the pages get smaller, but the list item that holds each page remains full-size.

Maybe `InteractiveViewer` is the theoretical solution to this problem? But I don't want any gesture control from `InteractiveViewer`. I just want a widget layout that's capable of positioning a list of things that might be bigger than the viewport, or smaller than the viewport. I need to control the gestures because in addition to dragging and scaling, I also need to support stylus drawing, and text selection.

I'm going to try to steal all gestures from `InteractiveViewer` and see what happens. I'm hoping that I can at least use the `InteractiveViewer` `builder` to handle effective recycling without implementing a custom `RenderObject`, but I have a feeling that that's what I'm going to have to do.

This situation is similar to others that I've run into. I tend to find that the moment I have content that's more sophisticated than a standalone image, which requires panning and zooming, `InteractiveViewer` just gets in the way. Even if I manage to make it work in my current situation, the first thing I have to do is make sure no gestures are captured by it. If I can't figure that out, then I definitely can't use.

**Comment by justinmc** [comment]
@matthew-carroll That sounds like more reasons for InteractiveViewer to be broken into composable widgets.  It seems like you just want part of its functionality.  You could use a raw Transform widget, but with the caveat that you'd have to work with the Matrix4s directly yourself.

**Comment by goderbauer** [comment]
(triage) @justinmc @moffatman @matthew-carroll: Are there still plans for this PR?

**Review by justinmc — COMMENTED** [review]
I agree we should probably move forward with this if we can.  I'm ok with modifying InteractiveViewer like this, but I'm hesitant to add these parameters to GestureDetector and ScaleGestureRecognizer and want to dig deeper into that first.

I don't see an immediate path forward on doing this the "right way" in InteractiveViewer via composition.  We'll have to save that for the future, so for now, making these changes to it as a stopgap sounds fine to me.

However GestureDetector and ScaleGestureRecognizer make me nervous.  Were they already receiving trackpad input before?  I'm trying to understand this so I can decide if there is another way to achieve the same thing, but I'm not sure if there is or not.

**Comment by moffatman** [comment]
ScaleGestureRecognizer / GestureDetector do already use trackpad input. This new parameter just changes the way they interpret it. This is quite a niche feature so seems strange to be on such popular classes but that is the proper place in my view.

File: packages/flutter/lib/src/gestures/scale.dart [hunk 5]
```diff
@@ -36,26 +41,61 @@ enum _ScaleState {
...
+
+  _PointerPanZoomData.fromUpdateEvent(
+    this.parent,
+    PointerPanZoomUpdateEvent event
+  ) : _position = event.position,
+      _pan = event.pan,
+      _scale = event.scale,
+      _rotation = event.rotation;
+
+  final ScaleGestureRecognizer parent;
```
[the remark this answers is not in the document]
Comment (moffatman) [reply packages/flutter/lib/src/gestures/scale.dart:67]: That class needs to be recreated on each new scroll, so the parent will still need to remember the values

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/gestures/scale.dart:67]: Sounds good.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I think you're right about adding this to ScaleGestureRecognizer etc.  It so happens that these parameters are only used by InteractiveViewer, but it's reasonable that anyone else that is detecting a scale gesture on desktop would want to specify the behavior for trackpads.

Thanks for all of your work on improving InteractiveViewer!
