### PR TITLE
Reland #74722

### LINKED ISSUE #76569: TextField in a PageView with allowImplicitScrolling: true causes pages to scroll improperly
## Steps to Reproduce

(note: bug replicated on a OnePlus 6, bug could not be replicated on an emulated pixl3a)
1. Run an app (on Android) with a `PageView` and two pages, one containing a `TextField`, the other containing an empty `Container`. The `PageView` must have `alloImplicitScrolling` set to true. Code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: MyApp(),
    ),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: PageView(
        allowImplicitScrolling: true,
        children: [
          TextField(
            style: TextStyle(fontSize: 20.0),
          ),
          Container(
            color: Colors.blue.shade50,
          ),
        ],
      ),
    );
  }
}
```
2. Select the text field and type one or more characters
3. Hide the keyboard tray but retain focus on the text field by using the Android swipe-back gesture or Android back button
4. Swipe left across the screen to navigate to the second page

**Expected results:**
I expected to navigate to the second page and remain there.

**Actual results:**
The screen scrolls properly to the second page, and then scrolls immediately back to the first page with the text field without any further user input.

<details>
  <summary>Logs</summary>

```
[  +58 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a29104a69b102a7485cd00d358eaeab219d258ab
[        ] executing: [C:\Users\Waffl\Documents\code\flutter/] git tag --points-at a29104a69b102a7485cd00d358eaeab219d258ab
[  +44 ms] Exit code 0 from: git tag --points-at a29104a69b102a7485cd00d358eaeab219d258ab
[        ] 1.26.0-17.6.pre
[  +30 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\Users\Waffl\Documents\code\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +61 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +36 ms] List of devices attached
           cd7bd98d               device product:OnePlus6 model:ONEPLUS_A6003 device:OnePlus6 transport_id:5
           192.168.1.4:5555       device product:OnePlus6 model:ONEPLUS_A6003 device:OnePlus6 transport_id:3
[   +4 ms] C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell getprop
[ +191 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +64 ms] Skipping pub get: version match.
[ +100 ms] Generating C:\Users\Waffl\Documents\code\sandbox\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +42 ms] ro.hardware = qcom
[  +39 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +4 ms] Launching lib\delayed.dart on ONEPLUS A6003 in debug mode...
[   +4 ms] C:\Users\Waffl\Documents\code\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\Waffl\Documents\code\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\Waffl\Documents\code\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true --output-dill C:\Users\Waffl\AppData\Local\Temp\flutter_tools.d3739421\flutter_tool.5ad5397d\app.dill --packages C:\Users\Waffl\Documents\code\sandbox\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill build\f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill
[   +6 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Waffl\Documents\code\sandbox\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +11 ms] Exit code 0 from: C:\Users\Waffl\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Waffl\Documents\code\sandbox\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.sandbox" (Raw: "com.sandbox")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="sandbox" (Raw: "sandbox")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.sandbox.MainActivity" (Raw: "com.sandbox.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell -x logcat -v time -t 1
[   +9 ms] <- compile package:sandbox/delayed.dart
[ +144 ms] --------- beginning of main
           02-22 15:12:27.275 E/SELinux (  568): avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1303 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
[   +8 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +20 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +20 ms] Building APK
Running Gradle task 'assembleDebug'...
[  +18 ms] Using gradle from C:\Users\Waffl\Documents\code\sandbox\android\gradlew.bat.
[        ] C:\Users\Waffl\Documents\code\sandbox\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +6 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +78 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +1 ms] executing: [C:\Users\Waffl\Documents\code\sandbox\android/] C:\Users\Waffl\Documents\code\sandbox\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=C:\Users\Waffl\Documents\code\sandbox\lib\delayed.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Pdart-defines=flutter.inspector.structuredErrors%3Dtrue assembleDebug
[+2770 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +61 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] a29104a69b102a7485cd00d358eaeab219d258ab
[        ] [        ] executing: [C:\Users\Waffl\Documents\code\flutter/] git tag --points-at a29104a69b102a7485cd00d358eaeab219d258ab
[        ] [  +44 ms] Exit code 0 from: git tag --points-at a29104a69b102a7485cd00d358eaeab219d258ab
[        ] [        ] 1.26.0-17.6.pre
[        ] [  +34 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [C:\Users\Waffl\Documents\code\flutter/] git ls-remote --get-url origin
[        ] [  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +73 ms] executing: [C:\Users\Waffl\Documents\code\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +49 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +45 ms] Initializing file store
[        ] [  +12 ms] Done initializing file store
[        ] [  +28 ms] Skipping target: gen_localizations
[        ] [ +396 ms] Skipping target: kernel_snapshot
[        ] [ +235 ms] Skipping target: debug_android_application
[        ] [        ] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 830ms.
[        ] [   +3 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 0
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +278 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[  +90 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[ +175 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 3s
[        ] 31 actionable tasks: 5 executed, 26 up-to-date
[ +565 ms] calculateSha: LocalDirectory: 'C:\Users\Waffl\Documents\code\sandbox\build\app\outputs\flutter-apk'/app.apk
[  +16 ms] calculateSha: reading file took 16us
[ +472 ms] calculateSha: computing sha took 471us
[   +5 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Waffl\Documents\code\sandbox\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +21 ms] Exit code 0 from: C:\Users\Waffl\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Waffl\Documents\code\sandbox\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.sandbox" (Raw: "com.sandbox")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="sandbox" (Raw: "sandbox")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.sandbox.MainActivity" (Raw: "com.sandbox.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on ONEPLUS A6003.
[        ] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell am force-stop com.sandbox
[ +252 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell pm list packages com.sandbox
[ +128 ms] package:com.sandbox
[   +1 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell cat /data/local/tmp/sky.com.sandbox.sha1
[  +89 ms] 79438a8d1c346be708ae2acdfe79a704ce9d92be
[        ] Latest build already installed.
[        ] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell -x logcat -v time -t 1
[ +197 ms] --------- beginning of main
           02-22 15:12:32.226 D/RegisteredNfcFServicesCache( 3920): Service unchanged, not updating
[   +6 ms] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.sandbox/com.sandbox.MainActivity
[ +122 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.sandbox/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +537 ms] Observatory URL on device: http://127.0.0.1:42965/Djcw1kXqN4w=/
[        ] executing: C:\Users\Waffl\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.4:5555 forward tcp:0 tcp:42965
[  +20 ms] 49468
[        ] Forwarded host port 49468 to device port 42965 for Observatory
[   +4 ms] Caching compiled dill
[  +27 ms] Connecting to service protocol: http://127.0.0.1:49468/Djcw1kXqN4w=/
[ +229 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:49468/Djcw1kXqN4w=/.
[ +209 ms] DDS is listening at http://127.0.0.1:49483/jyCL6j0U58Y=/.
[  +47 ms] Successfully connected to service protocol: http://127.0.0.1:49468/Djcw1kXqN4w=/
[ +320 ms] DevFS: Creating new filesystem on the device (null)
[  +76 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.sandbox/code_cache/sandboxAPOHBZ/sandbox/)
[   +3 ms] Updating assets
Debug service listening on ws://127.0.0.1:49483/jyCL6j0U58Y=/ws
Syncing files to device ONEPLUS A6003...
[  +56 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:sandbox/delayed.dart e566a072-aa73-444b-aece-00e9d0ae26be
[        ] <- e566a072-aa73-444b-aece-00e9d0ae26be
[ +289 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Synced 0.0MB.
[        ] <- accept
[ +548 ms] Connected to _flutterView/0x7551692020.
```

```
$ flutter analyze
Analyzing sandbox...
No issues found! (ran in 1.4s)
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.26.0-17.6.pre at C:\Users\Waffl\Documents\code\flutter
    • Framework revision a29104a69b (6 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Waffl\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Waffl\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2020.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8070

[√] Connected device (4 available)
    • ONEPLUS A6003 (mobile) • cd7bd98d         • android-arm64  • Android 10 (API 29)
    • ONEPLUS A6003 (mobile) • 192.168.1.4:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Reland #74722 with additional changes. Internal tests are passing (saving for a few minor scuba issues).

The original PR failed some internal tests, because when text is changed but the caret location isn't, we didn't clear the `_textChangedSinceLastCaretUpdate` flag at the end of that frame. And the next caret location change will be seen as caused by the text change, triggering `showCaretOnScreen` when it shouldn't.

Original issue: https://github.com/flutter/flutter/issues/74566
Fixes: #76569, #68778, #50713

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
There's one failure that could be related. Coming back to this when the roll catches up.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2154,17 +2170,9 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
-  bool _textChangedSinceLastCaretUpdate = false;
   Rect? _currentCaretRect;
-
   void _handleCaretChanged(Rect caretRect) {
     _currentCaretRect = caretRect;
-    // If the caret location has changed due to an update to the text or
-    // selection, then scroll the caret into view.
-    if (_textChangedSinceLastCaretUpdate) {
-      _textChangedSinceLastCaretUpdate = false;
-      _showCaretOnScreen();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/editable_text.dart:2166]: Remove this will also fix #76569

**Comment by xu-baolin** [comment]
@LongCatIsLooong Hey, 
I just investigated #76569. It seems that this PR can fix this bug.
 I will keep an eye on this and wait to confirm again after landing.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2166]: `_snapToPhysicalPixel` change the caret rectangle during page scrolling and bring the textField up to sight again.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -398,6 +398,18 @@ class ToolbarOptions {
...
+/// {@template flutter.widgets.editableText.showCaretOnScreen}
+/// ## Keep the caret visisble when focused
+///
+/// When focused, this widget will make attempts to keep the text area and its
+/// caret (even when [showCursor] is `false`) visible, on these occasions:
+///
+///  * When the user focuses this text field and it is not [readOnly].
+///  * When the user changes the selection of the text field, or changes the
+///    text when the text field is not [readOnly].
+///  * When the virtual keyboard pops up.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:410]: @goderbauer I saw you added the viewInset-triggered showCaretOnScreen code. Should we do something similar when the phone rotates?

File: packages/flutter/test/widgets/editable_text_show_on_screen_test.dart [hunk 3]
```diff
@@ -489,6 +490,242 @@ void main() {
       // The scroll offset should remain the same.
       expect(controller.offset, 100.0 * 15);
   });
+
+  void testShowCaretOnScreen({ required bool readOnly }) {
+    group('EditableText._showCaretOnScreen, readOnly=$readOnly', () {
+      final TextEditingController textEditingController = TextEditingController();
+      final TextInputFormatter rejectEverythingFormatter = TextInputFormatter.withFunction((TextEditingValue old, TextEditingValue value) => old);
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:497]: Does TextInputFormatter need to be imported?  Looking at the [analyzer](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8854478385424369568/+/steps/prepare_environment/0/steps/Analyze/0/steps/analyze/0/stdout).

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -2173,7 +2181,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
 
   bool _showCaretOnScreenScheduled = false;
 
-  void _showCaretOnScreen() {
+  void _scheduleShowCaretOnScreen() {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2184]: I like the name change 👍

**Review by justinmc — APPROVED** [review]
LGTM if the Google tests are passing 👍

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/editable_text.dart:410]: What do Android and iOS do natively when you rotate the phone? Do they keep the focused textfield in view? If so, we should probably do something similar.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:410]: iOS text fields don't seem to do that. There are no open issues either I guess I'll leave it as is.

File: packages/flutter/test/widgets/editable_text_show_on_screen_test.dart [hunk 5]
```diff
@@ -489,6 +491,242 @@ void main() {
...
+        EditableText.debugDeterministicCursor = false;
+
+        await tester.pumpWidget(
+          buildEditableText(
+            rejectUserInputs: false,
+            scrollController: scrollController,
+            editableScrollController: editableScrollController,
+          ),
+        );
+
```
Comment (xu-baolin) [inline packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:693]: I run this test on the master branch but it passed. It should be failed, right?

It seems like here miss a `await tester.pumpAndSettle();`

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:693]: This is the first build and there's no animation. I don't think we need `pumpAndSettle` here.

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:693]: Oh I see what you are saying.

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:699]: hah had to remove the `ListView`. Not this should fail on `master`. Thanks for catching this!

Comment (xu-baolin) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:699]: Yes, it works.
I also wonder why the list will scroll a little on the first frame? Is it a ballistic scroll?

**Review by xu-baolin — APPROVED** [review]
LGTM, Great job!
I believe this bug has existed for a long time.

File: packages/flutter/test/widgets/editable_text_show_on_screen_test.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:699]: the `ListView` didn't seem to have scrolled (scrolloffset didn't change), but the resulting `caretRect` has a slightly different `top` value (before appending an "a" : `0.0` -> after appending an "a": `-0.0`). Not sure exactly why but could be accumulated rounding errors.

Comment (xu-baolin) [reply packages/flutter/test/widgets/editable_text_show_on_screen_test.dart:699]: I see, the `ScrollController.initialScrollOffset` of 100 pixels has overscrolled.

**Comment by deepak786** [comment]
when this merge will be released?
