### PR TITLE
Selecting spaces on SelectableText (mobile)

### LINKED ISSUE #68226: Selecting a space should select previous word in SelectableText on mobile
Issue https://github.com/flutter/flutter/issues/67634 mentioned this feature for CupertinoTextField, and it was fixed in https://github.com/flutter/flutter/pull/68227 for everything except for SelectableText.  We should add this functionality to SelectableText on mobile.

To reproduce, run an app with SelectableText, such as the example below.  Double tap on the space between the "blah"s.  On mobile, the first blah should be selected, but instead the space is selected.

<details>

<summary>Example app</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SelectableText(' blah blah'),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
## Description
On both native Android and iOS attempting to select a space on an uneditable piece of text, will instead select the previous word.

This PR brings this functionality to Flutter.

## Related Issues

Closes #68226

## Tests

I added the following tests:
* SelectableText
    * Test for selecting spaces on mobile
    * Test for selecting spaces on non-mobile platforms
    * Test for double tapping a space on mobile
              
I had to change the following tests:
* SelectableText
    * long tap still selects after a double tap select
        * I split this test into a macOS and iOS version because they now differ in behavior when selecting a space, and this particular test taps a space.
    * long press drag moves the cursor under the drag and shows toolbar on lift
        * This test was also split into macOS and iOS versions because on iOS when selecting a word and attempting to drag over a whitespace, it will skip over the whitespace to the next word.
## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
@justinmc Hey Justin could you take a look at this when you get a chance. I'm not sure if this would be considered a breaking change since it did break some tests but not the customer ones. I've made a note about the breaking tests in the description.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 1]
```diff
@@ -3015,30 +3015,30 @@ void main() {
       // Cursor move doesn't trigger a toolbar initially.
       expect(find.byType(CupertinoButton), findsNothing);
 
-      await gesture.moveBy(const Offset(50, 0));
+      await gesture.moveBy(const Offset(100, 0));
```
Comment (chunhtai) [inline packages/flutter/test/widgets/selectable_text_test.dart:3018]: why this change?

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 2]
```diff
@@ -3202,14 +3282,58 @@ void main() {
       await tester.pump();
 
       // Selected the "word" where the tap happened, which is the first space.
+      // Because the "word" is a whitespace, the selection will shift to the
+      // previous "word" that is not a whitespace.
       expect(
         controller.selection,
-        const TextSelection(baseOffset: 7, extentOffset: 8),
```
Comment (chunhtai) [inline packages/flutter/test/widgets/selectable_text_test.dart:3207]: This is suprising. I thought we already select previous word for ios before this change? I don't even know why this test passes before

Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:3207]: The PR from before only affected editable text, so this test still passed.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -1943,47 +1943,45 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
     if (obscureText) {
       return TextSelection(baseOffset: 0, extentOffset: _plainText.length);
     // If the word is a space, on iOS try to select the previous word instead.
-    } else if (text?.text != null
+    // If the word is a space, on Android and the text is read only, then select
+    // the previous word instead.
+    } else if ((text?.text != null
         && _isWhitespace(text!.text!.codeUnitAt(position.offset))
-        && position.offset > 0) {
+        && position.offset > 0) || (readOnly && originalText != null
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:1958]: I tried this but it looks like `text` is null when selecting on `SelectableText`, so using the original case would skip this condition. I brought in `originalText` to make up for this.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:3018]: So this test was failing because it attempts to drag the selection onto the white space following a word.

Take 'Atwater Peel Sherbrooke Bonaventure', if we select 'Atwater' and try to drag the selection over the white space following it, then the selection will skip the whitespace and drag onto the next word. I checked this behavior on uneditable text on iOS and it looks like it is consistent. Though I'm not sure if this behavior is what is desired.

Comment (justinmc) [reply packages/flutter/test/widgets/selectable_text_test.dart:3018]: Indeed on master I see that I cannot drag the selection handle after selecting a word to select the space after it, on both a TextField and a SelectableText.  It jumps into the next word.  Maybe we're not detecting the drag gesture soon enough?

On native iOS I am able to select the space, so this seems like something that should be fixed (but not related to this PR).

I don't see how this test was able to pass in the first place, but if it now mimics a test in CupertinoTextField then I guess it's ok for now?

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 4]
```diff
@@ -4252,4 +4376,171 @@ void main() {
...
+    expect(selection!.baseOffset, 5);
+    expect(selection!.extentOffset, 6);
+
+    // Put the cursor at the end of the field.
+    await tester.tapAt(textOffsetToPosition(tester, 10));
+    expect(selection, isNotNull);
+    expect(selection!.baseOffset, 10);
+    expect(selection!.extentOffset, 10);
+
+    // Double tapping the second space selects it.
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:4466]: This is double tapping the first space not the second space, right?

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 5]
```diff
@@ -4252,4 +4376,171 @@ void main() {
...
+
+    expect(selection, isNull);
+
+    // Put the cursor at the end of the field.
+    await tester.tapAt(textOffsetToPosition(tester, 19));
+    expect(selection, isNotNull);
+    expect(selection!.baseOffset, 19);
+    expect(selection!.extentOffset, 19);
+
+    // Double tapping does the same thing
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:4503]: What do you mean by "the same thing"?  Also, period at the end of this sentence.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 6]
```diff
@@ -4252,4 +4376,171 @@ void main() {
...
+    await tester.pumpAndSettle();
+    expect(selection, isNotNull);
+    expect(selection!.baseOffset, 1);
+    expect(selection!.extentOffset, 5);
+
+    // Put the cursor at the end of the field.
+    // await tester.tapAt(textOffsetToPosition(tester, 19));
+    // expect(selection, isNotNull);
+    // expect(selection!.baseOffset, 19);
+    // expect(selection!.extentOffset, 19);
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:4517]: Does moving the cursor to the end of the field first break something?

**Review by justinmc — COMMENTED** [review]
Thanks for fixing this.  Mostly just small comments.  I'm on board with this approach.

I think this shouldn't be considered a breaking change since it's not breaking any customers, and the test changes are really just corrections.  I've submitted this to run the Google tests to make sure none of those break either.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:4503]: I meant double tapping the second space selects the previous word. Updated it to make it more clear.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart]: Correct thanks for catching that.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 7]
```diff
@@ -1943,47 +1943,45 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
-            );
-            startIndex = wordBeforeSpace.start;
-          }
           return TextSelection(
-            baseOffset: startIndex,
+            baseOffset: previousWord!.start,
             extentOffset: position.offset,
           );
         case TargetPlatform.android:
+          if(readOnly){
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart]: Fixed.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 8]
```diff
@@ -1943,47 +1943,45 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
     // When long-pressing past the end of the text, we want a collapsed cursor.
     if (position.offset >= word.end)
       return TextSelection.fromPosition(position);
     // If text is obscured, the entire sentence should be treated as one word.
     if (obscureText) {
       return TextSelection(baseOffset: 0, extentOffset: _plainText.length);
     // If the word is a space, on iOS try to select the previous word instead.
-    } else if (text?.text != null
+    // On Android try to select the previous word instead only if the text is read only
+    // the previous word instead.
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart]: Correct fixed it up.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 6 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:4517]: Yes, for some reason I am unable to put the cursor at the end of the field at this point in the test. I tested a couple of offset positions and came to the conclusion that anything past the value `17` results in the cursor staying at the same previous position, which in this case is `1`. However, just a little later in the same test, I am able to move the cursor to the end of the field. I haven't been able to pinpoint yet what exactly is causing this.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 9]
```diff
@@ -1943,47 +1943,45 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    } else if ((text?.text != null
         && _isWhitespace(text!.text!.codeUnitAt(position.offset))
-        && position.offset > 0) {
+        && position.offset > 0) || (readOnly && originalText != null
+        && _isWhitespace(originalText.codeUnitAt(position.offset))
+        && position.offset > 0)) {
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:1959]: Yes that would work. Updated with changes.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:3018]: Yeah i'm not sure how it still passed. I also checked the behavior on master and came to the same conclusion you did.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 10]
```diff
@@ -1943,47 +1943,43 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
            _textLayoutLastMinWidth == constraints.minWidth,
       'Last width ($_textLayoutLastMinWidth, $_textLayoutLastMaxWidth) not the same as max width constraint (${constraints.minWidth}, ${constraints.maxWidth}).');
     final TextRange word = _textPainter.getWordBoundary(position);
+    final String originalText = textSelectionDelegate.textEditingValue.text;
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:1946]: You can do something like this
```
final String? effectiveText = text?.text ?? readOnly ? textSelectionDelegate.textEditingValue.text : null;
```

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: also add a little bit explanation on why we grab textSelectionDelegate.textEditingValue.text if it is read only

File: packages/flutter/lib/src/rendering/editable.dart [hunk 11]
```diff
@@ -1943,47 +1943,43 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
       return TextSelection.fromPosition(position);
     // If text is obscured, the entire sentence should be treated as one word.
     if (obscureText) {
       return TextSelection(baseOffset: 0, extentOffset: _plainText.length);
     // If the word is a space, on iOS try to select the previous word instead.
-    } else if (text?.text != null
-        && _isWhitespace(text!.text!.codeUnitAt(position.offset))
-        && position.offset > 0) {
+    // On Android try to select the previous word instead only if the text is read only.
+    } else if (position.offset > 0 && ((text?.text != null
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:1955]: if you do the effectiveText, you can keep the same if case but replace text?.text with effectiveText

File: packages/flutter/lib/src/rendering/editable.dart (hunk 10 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: Although i am still confused at why the text?.text would be different  from textSelectionDelegate.textEditingValue.text for selectable text

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: ok so i figure out why text?.text is empty because selectable text uses textspan with children.

instead of grabbing the value from text?.text, it should grab value from text?.toPlainText(). if you use that you don't need to check the text editing value

File: packages/flutter/lib/src/rendering/editable.dart (hunk 11 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1955]: edit: the original else if should just be text?.toPlainText() instead

File: packages/flutter/lib/src/rendering/editable.dart (hunk 10 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: Wow that's awesome! Thanks for finding that. I just tried it out and it works well.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 6 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:4517]: So I tried a similar test on master

```dart
  testWidgets('double tapping a space selects the space on mobile', (WidgetTester tester) async {
    TextSelection? selection;

    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: Center(
            child: SelectableText(
              ' blah blah  \n  blah',
              onSelectionChanged: (TextSelection newSelection, SelectionChangedCause? cause){
                selection = newSelection;
              },
            ),
          ),
        ),
      ),
    );

    expect(selection, isNull);

    // Put the cursor at the end of the field.
    await tester.tapAt(textOffsetToPosition(tester, 19));
    expect(selection, isNotNull);
    expect(selection!.baseOffset, 19);
    expect(selection!.extentOffset, 19);

    // Double tapping the second space selects the space.
    await tester.pump(const Duration(milliseconds: 500));
    await tester.tapAt(textOffsetToPosition(tester, 5));
    await tester.pump(const Duration(milliseconds: 50));
    await tester.tapAt(textOffsetToPosition(tester, 5));
    await tester.pumpAndSettle();
    expect(selection, isNotNull);
    expect(selection!.baseOffset, 5);
    expect(selection!.extentOffset, 6);

    // Put the cursor at the end of the field.
    await tester.tapAt(textOffsetToPosition(tester, 19));
    expect(selection, isNotNull);
    expect(selection!.baseOffset, 19);
    expect(selection!.extentOffset, 19);
    
  }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.android }));
```
The test also fails when trying to do the same behavior (put the cursor at the end of the field)

File: packages/flutter/lib/src/rendering/editable.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart]: The condition has been updated and made more concise.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/test/widgets/selectable_text_test.dart:4517]: Sounds good, thanks for checking.  Remove these commented out lines then?

**Review by justinmc — APPROVED** [review]
LGTM 👍  Thanks for fixing this!

**Review by chunhtai — APPROVED** [review]
LGTM
