### PR TITLE
Some test cleanup for flutter_tools.

### LINKED ISSUE #81486: DevTools doesn't reliably start on Windows
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_4_5/20/overview

```
04:10 +9 ~14: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                      
Test is taking a long time.
Expected state transitions:
    0 NOW WAITING FOR> /^An Observatory debugger and profiler on Flutter test device is available at: /
    1                  /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /
    2                  /^Performing hot reload\.\.\./
    3                  /^Reloaded 0 libraries in [0-9]+ms./
So far nothing has been logged; use debug:true to print all output.
(streaming all logs from this point on...)
stdout: Syncing files to device Flutter test device...                     268ms
stdout: 
stdout: Flutter run key commands.
stdout: r Hot reload. 
stdout: R Hot restart.
stdout: h List all available interactive commands.
stdout: d Detach (terminate "flutter run" but leave application running).
stdout: c Clear the screen
stdout: q Quit (terminate the application on the device).
stdout: 
stdout:  Running with sound null safety 
stdout: 
stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:55963/QeHWO1lBXrI=/
(matched /^An Observatory debugger and profiler on Flutter test device is available at: /)
(taking a long time...)
(process is not quitting, trying to send a "q" just in case that helps)
(a functional test should never reach this point)
stdout: 
stdout: Application finished.
(process terminated with exit code 0)
The subprocess terminated before all the expected transitions had been matched.
The transition that we were hoping to see next but that we never saw was:
    1 NOW WAITING FOR> /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /

04:23 +9 ~14 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link [E]                                                                               
  Missed some expected transitions.
  test\integration.shard\overall_experience_test.dart 275:5  runFlutter
```

### LINKED ISSUE #87924: Test 'flutter run writes and clears pidfile appropriately' doesn't work on windows.
Part of skip test audio: #86396.

The test in overall_experience_test.dart is skipped for windows:

https://github.com/flutter/flutter/blob/d3bdbed4985ca2ab174d65a6f556bd18ac03be5e/packages/flutter_tools/test/integration.shard/overall_experience_test.dart#L329

If this is intentional because windows doesn't support some feature, please mark the skip with an // [intended] comment so that we know it isn't just a temporary skip. Otherwise, use this issue as as tracking bug.

### PR DESCRIPTION
**Pull request by Hixie**
* Re-enable the devtools test on Windows.
* Removing lots of timeouts that are redundant now that we have a
  global timeout of fifteen minutes.
* Add some annotations to intentionally skipped tests and test files
  that intentionally require tests to run in a particular order.

### CODE REVIEW

**Comment by Hixie** [comment]
Closes https://github.com/flutter/flutter/issues/87924.
May close https://github.com/flutter/flutter/issues/81486.

**Comment by Hixie** [comment]
cc @christopherfujino

File: dev/bots/test.dart [hunk 1]
```diff
@@ -295,8 +297,6 @@ Future<void> _runWebToolTests() async {
     path.join(flutterRoot, 'packages', 'flutter_tools'),
     forceSingleCore: true,
     testPaths: <String>[path.join('test', 'web.shard')],
-    enableFlutterToolAsserts: true,
```
Comment (christopherfujino) [inline dev/bots/test.dart:298]: why removing the asserts?

Comment (Hixie) [reply dev/bots/test.dart:298]: it defaults to true

Comment (Hixie) [reply dev/bots/test.dart:298]: i'm actually surprised this didn't get flagged by the analyzer...

Comment (Hixie) [reply dev/bots/test.dart:298]: ah we haven't yet enabled avoid_redundant_argument_values

**Review by christopherfujino — APPROVED** [review]
lgtm
