### PR TITLE
Nested InkWells only show the innermost splash

### LINKED ISSUE #14417: Both ink wells react when they are nested inside each other
Internal: b/151678927

Pictured: two ink wells, one for the card, and one for the smaller rectangular widget at the center of the card. The smaller rectangular widget has been tapped. The current Flutter behavior is on pictured to the left, the ideal behavior is pictured to the right.

In Android, by default, ancestors do not respond/ripple when a descendant responds/ripples i.e. it follows the ideal behavior pictured to the right.

Reasoning: say the descendant is a button, it does not make sense for the ancestor to ripple as tapping the button will not activate the `onTap` for the ancestor.

 

## Steps to Reproduce

Run the sample code below, click the center of the card and two ripples will be generated for both ink response widgets. The ideal situation can be replicated by setting the ancestor `InkWell.onTap` to null, as annotated in the code.

```dart
import "package:flutter/material.dart";

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text("Bug"),
        ),
        body: new Card(
          child: new Container(
            height: 100.0,
            child: new InkWell(
              onTap: () => print("Set this onTap to null for ideal behavior"),
              child: new Center(
                child: new InkWell(
                  onTap: () {},
                  child: new Container(
                    width: 50.0,
                    height: 50.0,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

## Logs

Running flutter run and flutter analyze did not output anything.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NZ, channel unknown)
    • Flutter at /Users/gnawf/flutter
    • Framework revision 6a42ed3f55 (3 weeks ago), 2018-01-12 15:12:26 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /usr/local/opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' to enable developer mode.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • iPhone 8 • 533B1ADF-56E5-4A63-9319-1F704E8845E0 • ios • iOS 11.2 (simulator)
```

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR changes the behavior when `InkWell`s are nested and an inner `InkWell` is pressed. Now only the innermost `InkWell` will show the press splash, instead of all of them.

This is implemented by wrapping `InkWell` in an `InheritedWidget` that passes the parent `_InkResponseState` to the child for notification, and only starts splash when no children `InkResponse`s are displaying splashs.

This PR also removes the generic parameter from `_InkResponseState`, which is likely a historical remnant.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/14417

## Tests

I added the following tests:

- When ink wells are nested, only the inner one is triggered by tap splash
- Parent inkwell does not block child inkwells from splashes
- Parent inkwell can count the number of pressed children to prevent splash
- When ink wells are reparented, the old parent can display splash while the new parent can not
- Ink wells's splash starts before tap is confirmed and disappear after tap is canceled

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/ink_well.dart [hunk 1]
```diff
@@ -563,6 +687,23 @@ class _InkResponseState<T extends InkResponse> extends State<T> with AutomaticKe
 
   bool get highlightsExist => _highlights.values.where((InkHighlight highlight) => highlight != null).isNotEmpty;
 
+  final ObserverList<_ParentInkResponseState> _activeChildren = ObserverList<_ParentInkResponseState>();
+  @override
+  void markChildInkResponsePressed(_ParentInkResponseState childState, bool value) {
+    assert(childState != null);
+    final bool lastAnyPressed = _anyChildInkResponsePressed;
+    if (value) {
+      _activeChildren.add(childState);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_well.dart:696]: It looks like didChangeDependencies() should remove the child from its old list of active children (the way deactivate does) if its _ParentInkResponseState has changed.

**Review by HansMuller — COMMENTED** [review]
This looks good; just want to resolve one potential corner case.

**Review by HansMuller — APPROVED** [review]
LGTM with the additional test you showed to me.
