### PR TITLE
Use the correct Transform in the WidgetInspector overlay (#59566)

### LINKED ISSUE #59566: WidgetInspector overlay is not correct when the parent is a Transform
## Steps to Reproduce

Use the select widget option in DevTools when the `WidgetInspector` derived from a `MaterialApp` is inside a `Transform` that scales down for example.

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform.scale(
      scale: 0.5,
      child: MaterialApp(
        home: MyHomePage(),
      ),
    );
  }
}
```

**Expected results:** 
The widget dimensions overlay should match the `MaterialApp` widget 

**Actual results:** 
The overlay is distortioned so the dimensions do not match.

Is not very common to use a `Transform` widget above a `MaterialApp`, but when using a package such as [device_preview](https://pub.dev/packages/device_preview), where one can test multiple devices at the same time during develop, one can encounter with this issue.

Sample image taken from an issue in the device preview package: [#13](https://github.com/aloisdeniel/flutter_device_preview/issues/13)

image

### PR DESCRIPTION
**Pull request by davidmartos96**
## Description

When placing a Transform that modifies the scale above a Material App, the `WidgetInspector` overlay does not match the new dimensions on the screen. Here is an example with the current behavior and with the PR.

### Old
old

### New
new

This was because the transform used when painting the overlay was obtained as `object.getTransformTo(null)`. When there is a Transform applied above the inspector, that transform will not be correct. What I did was to specify the correct ancestor in the `getTransformTo` method. The ancestor would be the `WidgetInspector` render object itself, which can be obtained via the parent property of the `_RenderInspectorOverlay`.
 
## Related Issues

Fixes #59566

## Tests

I added a test that compares the transform used inside the Widget Inspector with the one placed above the Widget Inspector. I don't know if there is a better way to test this fix, I haven't found tests covering the overlay placement itself. 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### New golden file (inspector.overlay_positioning_with_transform.png)
inspector overlay_positioning_with_transform

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -2140,6 +2140,12 @@ class _WidgetInspectorState extends State<WidgetInspector>
   void initState() {
     super.initState();
 
+    WidgetsBinding.instance.addPostFrameCallback((_) {
+      // Set the root render object so that the inspector
+      // layer can apply the correct transforms
+      selection.rootRenderObject = context.findRenderObject();
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2146]: adding this with a post frame callback concerns me because there may now be a 1 frame lag where the render object is inconsistent for the selection and the inspector overlay. Can we update the root render object earlier to avoid this issue?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 2]
```diff
@@ -2583,6 +2592,9 @@ class _InspectorOverlayLayer extends Layer {
     final ui.PictureRecorder recorder = ui.PictureRecorder();
     final Canvas canvas = Canvas(recorder, state.overlayRect);
     final Size size = state.overlayRect.size;
+    // The overlay rect could have an offset if the widget inspector does
+    // not take all the screen
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2596]: nit: end comment with a period.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 3]
```diff
@@ -512,6 +512,53 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
+            ),
+          ),
+        ),
+      );
+
+      final InspectorSelection selection = getInspectorState().selection as InspectorSelection;
+
+      final RenderObject childRenderObject = childKey.currentContext.findRenderObject();
+
+      // The tranform of the child with respect to the inspector selection render object
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_test.dart:551]: here and elsewhere, prefer to end comments with a period.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 4]
```diff
@@ -512,6 +512,53 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
+      // should be the identity matrix
+      final Matrix4 m1 = childRenderObject.getTransformTo(selection.rootRenderObject);
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_test.dart:553]: give these descriptive variable names instead of m1 and m2 or remove the variables names completely as each variable is only used once.

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 1 above)
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2146]: For example. maybe instead have _RenderInspectorOverlay check what its immediate parent is.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 5]
```diff
@@ -512,6 +512,53 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
+      expect(m1, Matrix4.identity());
+
+      // The tranform of the child with respect to the whole widget should be the sam
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_test.dart:556]: bonus points: add a golden image test or two that renders the selection. just like the screenshots you included with the CL, that makes it really obvious what is going on.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 6]
```diff
@@ -2321,6 +2327,9 @@ class _WidgetInspectorState extends State<WidgetInspector>
 
 /// Mutable selection state of the inspector.
 class InspectorSelection {
+  /// Root render object in the inspector widget tree.
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2330]: this object isn't really related to the selection so it is a bit confusing to have as a public member of the InspectorSelection object. Can you remove it from here and maybe only track it in _RenderInspectorOverlay? That would seem like a great place to be tracking the root render object that we are trying to render relative to.

**Review by jacob314 — COMMENTED** [review]
Thanks for fixing this issue! Some comments and questions.

**Comment by davidmartos96** [comment]
@jacob314 Thanks for the review!
I've committed the suggested changes. 
One thing I added is the ability to handle multiple widget inspectors in the same app. I was thinking on the use case of an storyboard app for web or desktop where multiple `MaterialApp`s can be displayed at the same time. If we don't handle such case, the `getTransform` for a selected object may be called with ancestor that it's not a parent in the render object tree may throw an assert failure in those cases. 

Since I've never used the golden tests, I'll play around with them while the main code can be reviewed.
Thanks!

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 1 above)
Comment (davidmartos96) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: I ended up passing the _RenderInspectorOverlay parent to the layer.

File: packages/flutter/test/widgets/widget_inspector_test.dart (hunk 5 above)
Comment (davidmartos96) [reply packages/flutter/test/widgets/widget_inspector_test.dart:546]: I'll experiment with how to do golden tests, because I've never used them. Thanks for the suggestion!

Comment (davidmartos96) [reply packages/flutter/test/widgets/widget_inspector_test.dart]: @jacob314 I've created a golden image test. The image is attached at the end of the PR description.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 7]
```diff
@@ -2441,15 +2441,16 @@ class _RenderInspectorOverlay extends RenderBox {
     context.addLayer(_InspectorOverlayLayer(
       overlayRect: Rect.fromLTWH(offset.dx, offset.dy, size.width, size.height),
       selection: selection,
+      rootRenderObject: parent as RenderObject,
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2444]: to be defensive, maybe add an is check in case the parent is not a RenderObject.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 8]
```diff
@@ -2695,6 +2709,25 @@ class _InspectorOverlayLayer extends Layer {
...
     return false;
   }
+
+  /// Return whether or not a render object belongs to this inspector widget
+  /// tree.
+  /// The inspector selection is static, so if there are multiple inspector
+  /// overlays in the same app (i.e. an storyboard), a selected or candidate
+  /// render object may not belong to this tree.
+  bool _isInInspectorRenderObjectTree(RenderObject child) {
+    RenderObject inspectorRoot;
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2719]: inspectorRoot seems like it is unused. remove.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 9]
```diff
@@ -2695,6 +2709,25 @@ class _InspectorOverlayLayer extends Layer {
...
+    RenderObject current = child.parent as RenderObject;
+    while (current != null && inspectorRoot == null) {
+      // We found the widget inspector render object.
+      if (current is RenderStack
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2723]: This is adding a tight dependency that the _RenderInspectorOverlay has a parent that is a Stack and is the last child of that parent. That is probably ok but is a little fragile. We should either add a key to the Stack that is the parent of the _RenderInspectorOverlay or document in the code where the Stack is used that we are making assumptions about its child.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 10]
```diff
@@ -512,6 +512,123 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
+
+      InspectorSelectButtonBuilder selectButtonBuilder(Key key) {
+        return (BuildContext context, VoidCallback onPressed) {
+          return Material(child: RaisedButton(onPressed: onPressed, key: key));
+        };
+      }
+
+      // State type is private, hence using dynamic.
+      // The inspector state is static, so it's enough with reading one of them.
+      dynamic getInspectorState() => inspector1Key.currentState;
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_test.dart:583]: https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 11]
```diff
@@ -512,6 +512,123 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
+
+      final InspectorSelection selection = getInspectorState().selection as InspectorSelection;
+      // The selection is static, so it may be initialized from previous tests.
+      selection?.clear();
+
+      await tester.tap(find.text('Child 1'));
+      await tester.pump();
+      expect(paragraphText(selection.current as RenderParagraph), equals('Child 1'));
+
+      await tester.tap(find.text('Child 2'));
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_test.dart:627]: wow I'm surprised this multiple WidgetInspector case works this well :)

**Review by jacob314 — COMMENTED** [review]
very close to lgtm. A couple minor comments.
Thanks for implementing this!

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 8 above)
Comment (davidmartos96) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2719]: Good catch. It was a remain of a different implementation I had for that.

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 9 above)
Comment (davidmartos96) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2723]: I thought about the key, but I wasn't sure about passing it through arguments all the way down. It looked off. Also the key would have the problem of calling findRenderObject in the first frame right?
I'll add a comment to the Stack at the top as you suggest.

File: packages/flutter/test/widgets/widget_inspector_test.dart (hunk 10 above)
Comment (davidmartos96) [reply packages/flutter/test/widgets/widget_inspector_test.dart:583]: Actually, that is a function local to the test. I used the same name convention as the other tests that access the inspector state.
I think we should keep the name for consistency with the rest of the tests. What do you think?

**Comment by davidmartos96** [comment]
@jacob314 I've updated the PR with the previous suggestions.

File: packages/flutter/test/widgets/widget_inspector_test.dart (hunk 11 above)
Comment (davidmartos96) [reply packages/flutter/test/widgets/widget_inspector_test.dart:627]: Very niche use case I would say, but I was surprised as well to see it working perfectly fine in a sample app where I took it to the extreme. Multiple MaterialApps and even nesting between them ^^

File: packages/flutter/test/widgets/widget_inspector_test.dart (hunk 10 above)
Comment (jacob314) [reply packages/flutter/test/widgets/widget_inspector_test.dart:583]: sgtm

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 9 above)
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2725]: as long as it is documented in the build method it is fine as is.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 12]
```diff
@@ -2293,6 +2293,9 @@ class _WidgetInspectorState extends State<WidgetInspector>
 
   @override
   Widget build(BuildContext context) {
+    // Caution changing this Stack widget. The _InspectorOverlayLayer
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2296]: nit: Tweak to 
// Be careful changing this build method.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 13]
```diff
@@ -2293,6 +2293,9 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
+    // assumes the root RenderObject for the WidgetInspector will be
+    // a RenderStack with a _RenderInspectorOverlay as last child.
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2298]: nit: `as last child` -> `as the last child`

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by davidmartos96** [comment]
cc @jacob314
