### PR TITLE
Fixes an issue where TapRegion would consume taps regardless of navigation state

### LINKED ISSUE #169061: TapRegion consumes taps after navigation
### Steps to reproduce

1. Add a `TapRegion` with `consumeOutsideTaps` enabled to a first `Widget`
2. Add a `GestureDetector` to a second `Widget`
3. Navigate from the first `Widget` to the second and you should notice you cannot interact with the `GestureDetector`

### Expected results

`TapRegion` should only consume outside taps within its own navigation state.

### Actual results

`TapRegion` consumes taps regardless of the navigation state.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: PageA(),
    );
  }
}

class PageA extends StatelessWidget {
  const PageA({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TapRegion(
          consumeOutsideTaps: true,
          child: GestureDetector(
            onTap: () {
              Navigator.push(context, MaterialPageRoute(builder: (context) => const PageB()));
            },
            child: Container(
              width: 250.0,
              height: 250.0,
              color: Colors.blue,
            ),
          ),
        ),
      ),
    );
  }
}

class PageB extends StatelessWidget {
  const PageB({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () {
            print('Test');
          },
          child: Container(
            width: 250.0,
            height: 250.0,
            color: Colors.red,
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.5 24F74 darwin-arm64, locale en-US) [458ms]
    • Flutter version 3.29.3 on channel stable at *****
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (5 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [992ms]
    • Android SDK at *****
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [846ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome) [7ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.2) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (3 available) [5.9s]
    • *****

[✓] Network resources [457ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by PrimaelQuemerais**
Fixes #169061
Expands on #155297

This PR fixes the issue where TapRegion with consumeOutsideTaps enabled would consume taps even after navigating to a different page.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 1]
```diff
@@ -480,7 +480,7 @@ class TapRegion extends SingleChildRenderObjectWidget {
     return RenderTapRegion(
       registry: TapRegionRegistry.maybeOf(context),
       enabled: enabled,
-      consumeOutsideTaps: consumeOutsideTaps,
+      consumeOutsideTaps: isCurrent && consumeOutsideTaps,
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/tap_region.dart:483]: @gspencergoog Do you know if this is a reasonable solution to TapRegion listening to taps outside of its route?

**Review by justinmc — COMMENTED** [review]
@PrimaelQuemerais Can you add a test for this?

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 2]
```diff
@@ -1177,4 +1177,69 @@ void main() {
     expect(count1, 1); // tapRegion1 should respond.
     expect(count2, 1); // tapRegion2 should not respond anymore.
   });
+
+  // Regression test for the consumeOutsideTaps issue when navigating between pages
```
Comment (justinmc) [inline packages/flutter/test/widgets/tap_region_test.dart:1181]: Just leave the GitHub URL: "Regression test for https://github.com/flutter/flutter/issues/169061."

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 3]
```diff
@@ -1177,4 +1177,69 @@ void main() {
...
+              ),
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.pumpAndSettle();
+
+    // Navigate to the second page
```
Comment (justinmc) [inline packages/flutter/test/widgets/tap_region_test.dart:1229]: Nit: Period at the end of the sentence here and below.

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 4]
```diff
@@ -1177,4 +1177,69 @@ void main() {
...
+    // this tap would be consumed and buttonTapped would remain false
+    await tester.tap(find.byKey(buttonKey));
+    await tester.pumpAndSettle();
+
+    expect(
+      buttonTapped,
+      true,
+      reason: 'Button tap was not consumed by a TapRegion on a non-current route',
+    );
+  });
```
Comment (justinmc) [inline packages/flutter/test/widgets/tap_region_test.dart:1244]: Confirmed that this test fails on master :+1:

**Review by justinmc — APPROVED** [review]
LGTM as this is along the same lines as https://github.com/flutter/flutter/pull/155297. FYI @chunhtai @Mairramer .

**Review by chunhtai — APPROVED** [review]
LGTM
