### PR TITLE
[flutter_tools] ensure desktop builds can run without flutter_tools' package_config

### LINKED ISSUE #62258: Linux build required manual 'pub get' in flutter_tools
Hello I want to run hello world code that created but it show "Exception: Build process failed" when run "flutter run -d linux"
## flutter --verbose create foo

<details> 
<summary>logs</summary> 

```
[ +524 ms] executing: [/home/atsushi/Documents/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +154 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +4 ms] f25bd9c55c48c139524139b477d04b13e9f36b2c
[   +2 ms] executing: [/home/atsushi/Documents/flutter/] git tag --contains HEAD
[ +489 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.21.0-1.0.pre
           1.21.0-5.0.pre
[  +46 ms] executing: [/home/atsushi/Documents/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[   +1 ms] executing: [/home/atsushi/Documents/flutter/] git ls-remote --get-url
origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +199 ms] executing: [/home/atsushi/Documents/flutter/] git rev-parse
--abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +162 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[  +14 ms] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +9 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[ +347 ms] Creating project foo...
[ +444 ms]   foo/android/app/build.gradle (created)
[ +129 ms]   foo/android/app/src/main/kotlin/com/example/foo/MainActivity.kt
(created)
[  +18 ms]   foo/android/build.gradle (created)
[  +14 ms]   foo/android/foo_android.iml (created)
[  +14 ms]   foo/android/.gitignore (created)
[   +2 ms]   foo/android/gradle/wrapper/gradle-wrapper.properties (created)
[   +8 ms]   foo/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
[   +6 ms]   foo/android/app/src/main/res/values/styles.xml (created)
[   +2 ms]   foo/android/app/src/main/res/drawable/launch_background.xml
(created)
[   +7 ms]   foo/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
[   +9 ms]   foo/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
[   +3 ms]   foo/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
(created)
[  +11 ms]   foo/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
(created)
[  +11 ms]   foo/android/app/src/main/AndroidManifest.xml (created)
[  +39 ms]   foo/android/app/src/debug/AndroidManifest.xml (created)
[   +3 ms]   foo/android/app/src/profile/AndroidManifest.xml (created)
[  +12 ms]   foo/android/gradle.properties (created)
[  +24 ms]   foo/android/settings.gradle (created)
[   +1 ms]   foo/lib/main.dart (created)
[  +54 ms]   foo/ios/.gitignore (created)
[   +2 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
             (created)
[   +9 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
             (created)
[   +5 ms]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
(created)
[   +8 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
             (created)
[   +6 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
             (created)
[  +11 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
             (created)
[  +26 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
             (created)
[   +2 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
             (created)
[   +7 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
             (created)
[  +12 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
             (created)
[  +11 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
             (created)
[   +3 ms] 
foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
             (created)
[   +8 ms]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
(created)
[   +6 ms] 
foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
             (created)
[  +10 ms]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
(created)
[   +2 ms]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
(created)
[   +5 ms]   foo/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
[  +15 ms]   foo/ios/Runner/Base.lproj/Main.storyboard (created)
[   +2 ms]   foo/ios/Runner/Info.plist (created)
[   +3 ms]   foo/ios/Flutter/Debug.xcconfig (created)
[   +2 ms]   foo/ios/Flutter/Release.xcconfig (created)
[  +10 ms]   foo/ios/Flutter/AppFrameworkInfo.plist (created)
[   +1 ms]   foo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
(created)
[   +4 ms] 
foo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xc
             settings (created)
[  +14 ms] 
foo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.p
             list (created)
[   +9 ms] 
foo/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
             (created)
[   +3 ms] 
foo/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
[  +15 ms]   foo/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
(created)
[   +3 ms]   foo/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
[   +2 ms]   foo/pubspec.yaml (created)
[  +17 ms]   foo/README.md (created)
[  +18 ms]   foo/.metadata (created)
[   +6 ms]   foo/foo.iml (created)
[   +3 ms]   foo/.gitignore (created)
[   +3 ms]   foo/.idea/libraries/Dart_SDK.xml (created)
[  +20 ms]   foo/.idea/libraries/KotlinJavaRuntime.xml (created)
[   +3 ms]   foo/.idea/modules.xml (created)
[   +3 ms]   foo/.idea/workspace.xml (created)
[   +2 ms]   foo/.idea/runConfigurations/main_dart.xml (created)
[   +2 ms]   foo/test/widget_test.dart (created)
[  +10 ms]   foo/ios/Runner/Runner-Bridging-Header.h (created)
[  +16 ms]   foo/ios/Runner/AppDelegate.swift (created)
[   +2 ms]   foo/ios/Runner.xcodeproj/project.pbxproj (created)
[  +41 ms]   foo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
(existing - skipped)
[   +1 ms]   foo/linux/my_application.h (created)
[   +2 ms]   foo/linux/.gitignore (created)
[   +1 ms]   foo/linux/CMakeLists.txt (created)
[   +9 ms]   foo/linux/main.cc (created)
[   +1 ms]   foo/linux/flutter/CMakeLists.txt (created)
[   +1 ms]   foo/linux/my_application.cc (created)
[ +195 ms] Running "flutter pub get" in foo...
[  +21 ms] Using /home/atsushi/Documents/flutter/.pub-cache for the pub cache.
[   +5 ms] executing: [/home/atsushi/Desktop/foo/]
/home/atsushi/Documents/flutter/bin/cache/dart-sdk/bin/pub --verbose get
--no-precompile
[ +253 ms] FINE: Pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[ +231 ms] MSG : Resolving dependencies...
[  +60 ms] SLVR: fact: foo is 1.0.0+1
[  +25 ms] SLVR: derived: foo
[ +156 ms] SLVR: fact: foo depends on flutter any from sdk
[   +1 ms] SLVR: fact: foo depends on cupertino_icons ^0.1.3
[  +16 ms] SLVR: fact: foo depends on flutter_test any from sdk
[        ] SLVR:   selecting foo
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: cupertino_icons ^0.1.3
[   +1 ms] SLVR:   derived: flutter any from sdk
[ +115 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/cupertino_icons.
[ +118 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[+1368 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/cupertino_icons
[   +1 ms]     | took 0:00:01.373989
[   +1 ms]     | transfer-encoding: chunked
[   +1 ms]     | date: Sat, 25 Jul 2020 13:01:48 GMT
[   +1 ms]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[   +1 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[   +8 ms]     | x-content-type-options: nosniff
[   +2 ms]     | server: dart:io with Shelf
[ +160 ms] SLVR:   fact: every version of flutter_test from sdk depends on async
2.4.2
[   +3 ms] SLVR:   fact: every version of flutter_test from sdk depends on
boolean_selector 2.0.0
[   +3 ms] SLVR:   fact: every version of flutter_test from sdk depends on
characters 1.1.0-nullsafety
[  +10 ms] SLVR:   fact: every version of flutter_test from sdk depends on
charcode 1.1.3
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on clock
1.0.1
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
collection 1.15.0-nullsafety
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
fake_async 1.1.0
[   +3 ms] SLVR:   fact: every version of flutter_test from sdk depends on
flutter any from sdk
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
matcher 0.12.8
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on meta
1.3.0-nullsafety
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on path
1.7.0
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
source_span 1.7.0
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
stack_trace 1.9.5
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
stream_channel 2.0.0
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
string_scanner 1.0.5
[  +12 ms] SLVR:   fact: every version of flutter_test from sdk depends on
term_glyph 1.1.0
[   +2 ms] SLVR:   fact: every version of flutter_test from sdk depends on
test_api 0.2.17
[   +7 ms] SLVR:   fact: every version of flutter_test from sdk depends on
typed_data 1.3.0-nullsafety
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on
vector_math 2.1.0-nullsafety
[   +1 ms] SLVR:     selecting flutter_test 0.0.0 from sdk
[        ] SLVR:     derived: vector_math 2.1.0-nullsafety
[        ] SLVR:     derived: typed_data 1.3.0-nullsafety
[        ] SLVR:     derived: test_api 0.2.17
[        ] SLVR:     derived: term_glyph 1.1.0
[        ] SLVR:     derived: string_scanner 1.0.5
[        ] SLVR:     derived: stream_channel 2.0.0
[        ] SLVR:     derived: stack_trace 1.9.5
[        ] SLVR:     derived: source_span 1.7.0
[   +6 ms] SLVR:     derived: path 1.7.0
[        ] SLVR:     derived: meta 1.3.0-nullsafety
[        ] SLVR:     derived: matcher 0.12.8
[        ] SLVR:     derived: fake_async 1.1.0
[   +2 ms] SLVR:     derived: collection 1.15.0-nullsafety
[        ] SLVR:     derived: clock 1.0.1
[   +2 ms] SLVR:     derived: charcode 1.1.3
[   +2 ms] SLVR:     derived: characters 1.1.0-nullsafety
[   +5 ms] SLVR:     derived: boolean_selector 2.0.0
[        ] SLVR:     derived: async 2.4.2
[  +29 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/async.
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/boolean_selector.
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/characters.
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/charcode.
[   +1 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/clock.
[  +13 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/collection.
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/fake_async.
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/matcher.
[   +4 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/meta.
[   +1 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/path.
[   +2 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/async
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[   +4 ms]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[   +7 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/boolean_selector
[        ]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: linux
[   +1 ms]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[   +5 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/characters
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[  +15 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[   +1 ms]     | X-Pub-Environment: flutter_cli:create
[  +12 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/charcode
[   +5 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/clock
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/collection
[  +13 ms]     | Accept: application/vnd.pub.v2+json
[   +6 ms]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[   +7 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[   +4 ms]     | X-Pub-Environment: flutter_cli:create
[   +8 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/fake_async
[   +6 ms]     | Accept: application/vnd.pub.v2+json
[   +5 ms]     | X-Pub-OS: linux
[  +13 ms]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[   +6 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/matcher
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/meta
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/path
[   +7 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[ +957 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/async
[   +1 ms]     | took 0:00:01.135604
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:48 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[   +1 ms]     | via: 1.1 google
[   +1 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[   +5 ms]     | x-content-type-options: nosniff
[   +2 ms]     | server: dart:io with Shelf
[ +140 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/source_span.
[   +8 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/source_span
[   +2 ms]     | Accept: application/vnd.pub.v2+json
[   +5 ms]     | X-Pub-OS: linux
[  +10 ms]     | X-Pub-Command: get
[   +8 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[   +2 ms]     | X-Pub-Environment: flutter_cli:create
[   +3 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[ +326 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/source_span
[   +1 ms]     | took 0:00:00.356303
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[   +1 ms]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[   +2 ms]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[   +4 ms]     | server: dart:io with Shelf
[  +35 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/stack_trace.
[  +12 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/stack_trace
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[  +15 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/characters
[   +6 ms]     | took 0:00:01.723651
[   +1 ms]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[   +4 ms]     | x-frame-options: SAMEORIGIN
[   +5 ms]     | x-xss-protection: 1; mode=block
[   +7 ms]     | x-content-type-options: nosniff
[   +1 ms]     | server: dart:io with Shelf
[  +14 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/stream_channel.
[   +7 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/stream_channel
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[   +4 ms]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[   +1 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[  +23 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/clock
[   +1 ms]     | took 0:00:01.793769
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +16 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/string_scanner.
[   +8 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/string_scanner
[   +2 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[  +13 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/matcher
[   +2 ms]     | took 0:00:01.849339
[   +1 ms]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[   +4 ms]     | via: 1.1 google
[   +1 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[   +1 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/boolean_selector
[   +2 ms]     | took 0:00:01.895464
[        ]     | transfer-encoding: chunked
[   +4 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[  +15 ms]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[   +1 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/collection
[   +1 ms]     | took 0:00:01.886531
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[   +5 ms]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[   +4 ms]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[   +1 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/term_glyph.
[   +2 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/term_glyph
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[        ]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[  +12 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/test_api.
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/test_api
[   +8 ms]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: linux
[   +1 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[   +1 ms]     | X-Pub-Environment: flutter_cli:create
[   +9 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +7 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/charcode
[   +1 ms]     | took 0:00:01.973176
[   +3 ms]     | transfer-encoding: chunked
[   +5 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[   +1 ms]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[   +2 ms]     | via: 1.1 google
[   +1 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[  +13 ms]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[   +6 ms]     | server: dart:io with Shelf
[   +3 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/meta
[   +1 ms]     | took 0:00:01.953516
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[   +1 ms]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[   +5 ms]     | content-type: application/json; charset="utf-8"
[   +7 ms]     | x-frame-options: SAMEORIGIN
[   +3 ms]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[   +2 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/typed_data.
[   +4 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/typed_data
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[   +1 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[  +11 ms]     | X-Pub-Environment: flutter_cli:create
[   +1 ms]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[   +3 ms] IO  : Get versions from
https://pub.dartlang.org/api/packages/vector_math.
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/vector_math
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: D0B2435B-3D1F-4EF7-B151-47AEC0996A61
[   +1 ms]     | X-Pub-Environment: flutter_cli:create
[        ]     | user-agent: Dart pub 2.9.0-21.0.dev.flutter-20bf2fcf56
[  +74 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/path
[   +1 ms]     | took 0:00:02.127760
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[   +1 ms]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +14 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/fake_async
[   +3 ms]     | took 0:00:02.178969
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +72 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/stack_trace
[   +2 ms]     | took 0:00:00.583223
[  +18 ms]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[  +13 ms]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[ +121 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/stream_channel
[   +2 ms]     | took 0:00:00.660499
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[   +4 ms]     | content-type: application/json; charset="utf-8"
[   +1 ms]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +32 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/string_scanner
[   +8 ms]     | took 0:00:00.632288
[   +2 ms]     | transfer-encoding: chunked
[   +1 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[   +4 ms]     | via: 1.1 google
[  +12 ms]     | content-type: application/json; charset="utf-8"
[   +3 ms]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[   +8 ms]     | server: dart:io with Shelf
[   +3 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/term_glyph
[   +1 ms]     | took 0:00:00.582840
[        ]     | transfer-encoding: chunked
[        ]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[   +1 ms]     | x-xss-protection: 1; mode=block
[   +2 ms]     | x-content-type-options: nosniff
[   +2 ms]     | server: dart:io with Shelf
[  +23 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/test_api
[   +1 ms]     | took 0:00:00.596254
[   +6 ms]     | transfer-encoding: chunked
[   +1 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[   +2 ms]     | content-encoding: gzip
[  +12 ms]     | vary: Accept-Encoding
[   +2 ms]     | strict-transport-security: max-age=31536000; preload
[   +6 ms]     | via: 1.1 google
[   +4 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[   +2 ms]     | x-xss-protection: 1; mode=block
[   +2 ms]     | x-content-type-options: nosniff
[   +2 ms]     | server: dart:io with Shelf
[   +2 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/typed_data
[   +1 ms]     | took 0:00:00.570511
[  +16 ms]     | transfer-encoding: chunked
[   +4 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[   +3 ms]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[   +6 ms]     | server: dart:io with Shelf
[  +20 ms] IO  : HTTP response 200 OK for GET
https://pub.dartlang.org/api/packages/vector_math
[   +4 ms]     | took 0:00:00.595595
[   +7 ms]     | transfer-encoding: chunked
[   +4 ms]     | date: Sat, 25 Jul 2020 13:01:50 GMT
[   +1 ms]     | content-encoding: gzip
[   +1 ms]     | vary: Accept-Encoding
[   +2 ms]     | strict-transport-security: max-age=31536000; preload
[  +13 ms]     | via: 1.1 google
[   +2 ms]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +65 ms] SLVR:       selecting cupertino_icons 0.1.3
[  +17 ms] SLVR:       fact: every version of flutter from sdk depends on
characters 1.1.0-nullsafety
[   +1 ms] SLVR:       fact: every version of flutter from sdk depends on
collection 1.15.0-nullsafety
[   +1 ms] SLVR:       fact: every version of flutter from sdk depends on meta
1.3.0-nullsafety
[   +1 ms] SLVR:       fact: every version of flutter from sdk depends on
sky_engine any from sdk
[   +1 ms] SLVR:       fact: every version of flutter from sdk depends on
typed_data 1.3.0-nullsafety
[        ] SLVR:       fact: every version of flutter from sdk depends on
vector_math 2.1.0-nullsafety
[        ] SLVR:         selecting flutter 0.0.0 from sdk
[        ] SLVR:         derived: sky_engine any from sdk
[  +27 ms] SLVR:           selecting vector_math 2.1.0-nullsafety
[  +34 ms] SLVR:           fact: typed_data >=1.3.0-nnbd <1.3.0-nullsafety.1
depends on collection >=1.15.0-nnbd <1.15.0
[   +3 ms] SLVR:             selecting typed_data 1.3.0-nullsafety
[  +81 ms] SLVR:             fact: test_api >=0.2.5 depends on async ^2.0.0
[   +3 ms] SLVR:             fact: test_api >=0.2.14 depends on boolean_selector
>=1.0.0 <3.0.0
[   +1 ms] SLVR:             fact: every version of test_api depends on
collection ^1.8.0
[  +22 ms] SLVR:             fact: test_api >=0.2.17 <0.2.18-∞ depends on
matcher >=0.12.6 <0.12.9
[  +21 ms] SLVR:             fact: every version of test_api depends on meta
^1.1.5
[   +1 ms] SLVR:             fact: every version of test_api depends on path
^1.2.0
[   +1 ms] SLVR:             fact: every version of test_api depends on
source_span ^1.4.0
[   +3 ms] SLVR:             fact: every version of test_api depends on
stack_trace ^1.9.0
[   +4 ms] SLVR:             fact: test_api >=0.2.4 depends on stream_channel
>=1.7.0 <3.0.0
[   +7 ms] SLVR:             fact: test_api >=0.2.5 depends on string_scanner
^1.0.0
[   +6 ms] SLVR:             fact: every version of test_api depends on
term_glyph ^1.0.0
[   +1 ms] SLVR:               selecting test_api 0.2.17
[   +2 ms] SLVR:                 selecting term_glyph 1.1.0
[  +49 ms] SLVR:                 fact: string_scanner >=1.0.3 depends on
charcode ^1.1.0
[   +2 ms] SLVR:                 fact: string_scanner >=1.0.4 depends on meta
^1.1.0
[   +4 ms] SLVR:                 fact: string_scanner >=1.0.3 depends on
source_span ^1.4.0
[   +2 ms] SLVR:                   selecting string_scanner 1.0.5
[  +23 ms] SLVR:                   fact: stream_channel >=1.6.8 depends on async
>=1.11.0 <3.0.0
[   +2 ms] SLVR:                     selecting stream_channel 2.0.0
[  +20 ms] SLVR:                     fact: stack_trace >=1.9.3 depends on path
^1.2.0
[   +7 ms] SLVR:                       selecting stack_trace 1.9.5
[  +45 ms] SLVR:                       fact: source_span >=1.4.1 depends on
charcode ^1.0.0
[   +2 ms] SLVR:                       fact: source_span >=1.6.0 depends on
collection ^1.8.0
[   +3 ms] SLVR:                       fact: source_span >=1.6.0 depends on meta
>=0.9.0 <2.0.0
[   +8 ms] SLVR:                       fact: source_span >=1.4.1 depends on path
^1.2.0
[   +1 ms] SLVR:                       fact: source_span >=1.5.0 depends on
term_glyph ^1.0.0
[   +4 ms] SLVR:                         selecting source_span 1.7.0
[   +9 ms] SLVR:                           selecting path 1.7.0
[  +22 ms] SLVR:                             selecting meta 1.3.0-nullsafety
[  +26 ms] SLVR:                             fact: matcher >=0.12.3+1 depends on
stack_trace ^1.2.0
[   +2 ms] SLVR:                               selecting matcher 0.12.8
[  +17 ms] SLVR:                               fact: fake_async >=1.0.1 depends
on clock ^1.0.0
[   +1 ms] SLVR:                               fact: fake_async >=1.0.1 depends
on collection ^1.8.0
[   +1 ms] SLVR:                                 selecting fake_async 1.1.0
[  +26 ms] SLVR:                                   selecting collection
1.15.0-nullsafety
[  +18 ms] SLVR:                                   fact: clock >=1.0.1 depends
on meta >=0.9.0 <2.0.0
[   +2 ms] SLVR:                                     selecting clock 1.0.1
[  +13 ms] SLVR:                                       selecting charcode 1.1.3
[  +13 ms] SLVR:                                         selecting characters
1.1.0-nullsafety
[  +22 ms] SLVR:                                         fact: boolean_selector
>=1.0.4 depends on source_span ^1.0.0
[  +15 ms] SLVR:                                         fact: boolean_selector
>=2.0.0 depends on string_scanner ^1.0.0
[   +2 ms] SLVR:                                           selecting
boolean_selector 2.0.0
[   +6 ms] SLVR:                                           fact: async >=2.0.8
depends on collection ^1.5.0
[   +1 ms] SLVR:                                             selecting async
2.4.2
[   +4 ms] SLVR:                                               selecting
sky_engine 0.0.99 from sdk
[  +17 ms] SLVR: Version solving took 0:00:05.616085 seconds.
[   +1 ms]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (5.662s).
[  +33 ms] MSG : + async 2.4.2
[   +5 ms]     | + boolean_selector 2.0.0
[   +1 ms]     | + characters 1.1.0-nullsafety (1.1.0-nullsafety.2 available)
[  +25 ms]     | + charcode 1.1.3
[   +4 ms]     | + clock 1.0.1
[   +8 ms]     | + collection 1.15.0-nullsafety (1.15.0-nullsafety.2 available)
[   +1 ms]     | + cupertino_icons 0.1.3
[   +5 ms]     | + fake_async 1.1.0
[   +7 ms]     | + flutter 0.0.0 from sdk flutter
[   +7 ms]     | + flutter_test 0.0.0 from sdk flutter
[   +1 ms]     | + matcher 0.12.8 (0.12.9 available)
[   +4 ms]     | + meta 1.3.0-nullsafety (1.3.0-nullsafety.2 available)
[   +3 ms]     | + path 1.7.0
[   +8 ms]     | + sky_engine 0.0.99 from sdk flutter
[        ]     | + source_span 1.7.0
[        ]     | + stack_trace 1.9.5
[        ]     | + stream_channel 2.0.0
[   +1 ms]     | + string_scanner 1.0.5
[   +2 ms]     | + term_glyph 1.1.0
[   +9 ms]     | + test_api 0.2.17 (0.2.18 available)
[   +5 ms]     | + typed_data 1.3.0-nullsafety (1.3.0-nullsafety.2 available)
[  +26 ms]     | + vector_math 2.1.0-nullsafety (2.1.0-nullsafety.2 available)
[ +119 ms] IO  : Writing 3498 characters to text file ./pubspec.lock.
[   +1 ms] FINE: Contents:
[   +4 ms]     | # Generated by pub
[  +14 ms]     | # See https://dart.dev/tools/pub/glossary#lockfile
[        ]     | packages:
[   +5 ms]     |   async:
[   +5 ms]     |     dependency: transitive
[   +1 ms]     |     description:
[        ]     |       name: async
[        ]     |       url: "https://pub.dartlang.org"
[   +7 ms]     |     source: hosted
[   +3 ms]     |     version: "2.4.2"
[        ]     |   boolean_selector:
[   +4 ms]     |     dependency: transitive
[   +1 ms]     |     description:
[   +1 ms]     |       name: boolean_selector
[   +1 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.0.0"
[   +5 ms]     |   characters:
[   +3 ms]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: characters
[   +2 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0-nullsafety"
[        ]     |   charcode:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: charcode
[   +6 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.3"
[        ]     |   clock:
[        ]     |     dependency: transitive
[  +46 ms]     |     description:
[        ]     |       name: clock
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.0.1"
[   +3 ms]     |   collection:
[   +1 ms]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: collection
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.15.0-nullsafety"
[        ]     |   cupertino_icons:
[        ]     |     dependency: "direct main"
[        ]     |     description:
[   +1 ms]     |       name: cupertino_icons
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.1.3"
[   +1 ms]     |   fake_async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: fake_async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   flutter:
[        ]     |     dependency: "direct main"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   flutter_test:
[        ]     |     dependency: "direct dev"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   matcher:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: matcher
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.12.8"
[   +3 ms]     |   meta:
[        ]     |     dependency: transitive
[   +1 ms]     |     description:
[   +1 ms]     |       name: meta
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0-nullsafety"
[        ]     |   path:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: path
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.7.0"
[   +1 ms]     |   sky_engine:
[        ]     |     dependency: transitive
[        ]     |     description: flutter
[        ]     |     source: sdk
[   +1 ms]     |     version: "0.0.99"
[        ]     |   source_span:
[   +1 ms]     |     dependency: transitive
[        ]     |     description:
[   +1 ms]     |       name: source_span
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.7.0"
[        ]     |   stack_trace:
[        ]     |     dependency: transitive
[   +1 ms]     |     description:
[   +7 ms]     |       name: stack_trace
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.9.5"
[        ]     |   stream_channel:
[        ]     |     dependency: transitive
[   +3 ms]     |     description:
[        ]     |       name: stream_channel
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.0.0"
[        ]     |   string_scanner:
[        ]     |     dependency: transitive
[   +1 ms]     |     description:
[        ]     |       name: string_scanner
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.0.5"
[        ]     |   term_glyph:
[        ]     |     dependency: transitive
[   +3 ms]     |     description:
[        ]     |       name: term_glyph
[   +6 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   test_api:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: test_api
[   +1 ms]     |       url: "https://pub.dartlang.org"
[   +2 ms]     |     source: hosted
[        ]     |     version: "0.2.17"
[   +3 ms]     |   typed_data:
[        ]     |     dependency: transitive
[   +3 ms]     |     description:
[   +1 ms]     |       name: typed_data
[   +9 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0-nullsafety"
[   +1 ms]     |   vector_math:
[   +3 ms]     |     dependency: transitive
[        ]     |     description:
[   +3 ms]     |       name: vector_math
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +4 ms]     |     version: "2.1.0-nullsafety"
[        ]     | sdks:
[        ]     |   dart: ">=2.9.0-18.0 <2.9.0"
[  +19 ms] IO  : Writing 2364 characters to text file ./.packages.
[        ] FINE: Contents:
[        ]     | # Generated by pub on 2020-07-25 20:01:52.471167.
[        ]     |
async:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.4.2
/lib/
[   +1 ms]     |
boolean_selector:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/
boolean_selector-2.0.0/lib/
[  +22 ms]     |
characters:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/characte
rs-1.1.0-nullsafety/lib/
[   +2 ms]     |
charcode:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1
.1.3/lib/
[   +1 ms]     |
clock:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/clock-1.0.1/l
ib/
[   +1 ms]     |
collection:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/collecti
on-1.15.0-nullsafety/lib/
[   +7 ms]     |
cupertino_icons:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cup
ertino_icons-0.1.3/lib/
[   +1 ms]     |
fake_async:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fake_asy
nc-1.1.0/lib/
[   +1 ms]     | flutter:file:///home/atsushi/Documents/flutter/packages/flutter/lib/
[   +1 ms]     |
flutter_test:file:///home/atsushi/Documents/flutter/packages/flutter_test/lib/
[   +1 ms]     |
matcher:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/matcher-0.1
2.8/lib/
[   +1 ms]     |
meta:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0-nul
lsafety/lib/
[  +20 ms]     |
path:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.7.0/lib/
[   +1 ms]     |
sky_engine:file:///home/atsushi/Documents/flutter/bin/cache/pkg/sky_engine/lib/
[   +1 ms]     |
source_span:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/source_s
pan-1.7.0/lib/
[   +1 ms]     |
stack_trace:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/stack_tr
ace-1.9.5/lib/
[   +3 ms]     |
stream_channel:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/strea
m_channel-2.0.0/lib/
[   +1 ms]     |
string_scanner:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/strin
g_scanner-1.0.5/lib/
[   +1 ms]     |
term_glyph:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyp
h-1.1.0/lib/
[   +1 ms]     |
test_api:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/test_api-0.
2.17/lib/
[   +1 ms]     |
typed_data:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/typed_dat
a-1.3.0-nullsafety/lib/
[   +1 ms]     |
vector_math:file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vector_m
ath-2.1.0-nullsafety/lib/
[   +1 ms]     | foo:lib/
[   +1 ms] IO  : Writing 4883 characters to text file ./.dart_tool/package_config.json.
[   +1 ms] FINE: Contents:
[   +1 ms]     | {
[        ]     |   "configVersion": 2,
[        ]     |   "packages": [
[        ]     |     {
[        ]     |       "name": "async",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.4.2",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.2"
[   +7 ms]     |     },
[   +3 ms]     |     {
[        ]     |       "name": "boolean_selector",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.
0.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.4"
[        ]     |     },
[        ]     |     {
[   +2 ms]     |       "name": "characters",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0-nu
llsafety",
[   +1 ms]     |       "packageUri": "lib/",
[   +5 ms]     |       "languageVersion": "2.9"
[   +1 ms]     |     },
[        ]     |     {
[  +23 ms]     |       "name": "charcode",
[   +1 ms]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.3",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[  +18 ms]     |     },
[   +9 ms]     |     {
[   +2 ms]     |       "name": "clock",
[   +2 ms]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/clock-1.0.1",
[   +3 ms]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "2.0"
[   +2 ms]     |     },
[   +8 ms]     |     {
[        ]     |       "name": "collection",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0-nulls
afety",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.9"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "cupertino_icons",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.3",
[   +3 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[   +1 ms]     |     },
[   +1 ms]     |     {
[   +3 ms]     |       "name": "fake_async",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fake_async-1.1.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.2"
[        ]     |     },
[        ]     |     {
[   +7 ms]     |       "name": "flutter",
[   +3 ms]     |       "rootUri": "file:///home/atsushi/Documents/flutter/packages/flutter",
[   +1 ms]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "2.9"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter_test",
[   +2 ms]     |       "rootUri": "file:///home/atsushi/Documents/flutter/packages/flutter_test",
[   +1 ms]     |       "packageUri": "lib/",
[   +6 ms]     |       "languageVersion": "2.2"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "matcher",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.8",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.4"
[        ]     |     },
[  +10 ms]     |     {
[        ]     |       "name": "meta",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0-nullsafety",
[  +14 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.9"
[        ]     |     },
[        ]     |     {
[  +12 ms]     |       "name": "path",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.7.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[        ]     |     },
[   +6 ms]     |     {
[   +5 ms]     |       "name": "sky_engine",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/bin/cache/pkg/sky_engine",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "1.11"
[        ]     |     },
[        ]     |     {
[   +1 ms]     |       "name": "source_span",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/source_span-1.7.0",
[   +1 ms]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "2.6"
[        ]     |     },
[        ]     |     {
[   +7 ms]     |       "name": "stack_trace",
[   +1 ms]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.5",
[   +6 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[   +7 ms]     |     },
[   +1 ms]     |     {
[   +4 ms]     |       "name": "stream_channel",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0",
[   +2 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[        ]     |     },
[  +10 ms]     |     {
[   +1 ms]     |       "name": "string_scanner",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.5",
[   +1 ms]     |       "packageUri": "lib/",
[  +10 ms]     |       "languageVersion": "2.0"
[        ]     |     },
[   +2 ms]     |     {
[   +9 ms]     |       "name": "term_glyph",
[   +5 ms]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0",
[   +6 ms]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "1.8"
[   +1 ms]     |     },
[        ]     |     {
[        ]     |       "name": "test_api",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.17",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.7"
[        ]     |     },
[   +3 ms]     |     {
[   +1 ms]     |       "name": "typed_data",
[        ]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0-nullsafe
ty",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.9"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "vector_math",
[   +1 ms]     |       "rootUri":
"file:///home/atsushi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0-nullsaf
ety",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.9"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "foo",
[   +1 ms]     |       "rootUri": "../",
[   +1 ms]     |       "packageUri": "lib/",
[   +5 ms]     |       "languageVersion": "2.7"
[   +7 ms]     |     }
[        ]     |   ],
[        ]     |   "generated": "2020-07-25T13:01:52.690318Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.9.0-21.0.dev.flutter-20bf2fcf56"
[        ]     | }
[   +8 ms] MSG : Changed 22 dependencies!
[  +71 ms] Running "flutter pub get" in foo... (completed in 7.2s)
[ +783 ms] Generating
/home/atsushi/Desktop/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +57 ms] Wrote 77 files.
[        ] 
           All done!
[  +96 ms] executing: [/home/atsushi/Documents/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%ar
[  +21 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 11 days ago
[  +39 ms] executing:
/home/atsushi/Documents/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +19 ms] Exit code 255 from:
/home/atsushi/Documents/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[   +2 ms] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the SDK version.                                                    

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[ +613 ms] executing: /usr/lib/android-sdk/platform-tools/adb devices -l
[  +51 ms] List of devices attached
[  +38 ms] [✓] Flutter: is fully installed. (Channel dev, 1.21.0-1.0.pre, on Linux, locale en_US.UTF-8)
           [!] Android toolchain - develop for Android devices: is partially installed; more components
are
               available. (Android SDK version 27.0.1)
           [✓] Linux toolchain - develop for Linux desktop: is fully installed.
           [!] Android Studio: is not available. (not installed)
           [✓] VS Code: is fully installed. (version 1.47.2)
           [✓] Connected device: is fully installed. (1 available)
           
           Run "flutter doctor" for information about installing additional components.
           
[   +2 ms] In order to run your application, type:
           
             $ cd foo
             $ flutter run
           
           Your application code is in foo/lib/main.dart.
           
[  +10 ms] "flutter create" took 11,010ms.
[ +276 ms] ensureAnalyticsSent: 257ms
[  +13 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 0
```

## flutter run -d linux -v
```
[ +537 ms] executing: [/home/atsushi/Documents/flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[ +136 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] f25bd9c55c48c139524139b477d04b13e9f36b2c
[   +2 ms] executing: [/home/atsushi/Documents/flutter/] git tag --contains HEAD
[ +488 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-1.0.pre
           1.21.0-5.0.pre
[  +42 ms] executing: [/home/atsushi/Documents/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] executing: [/home/atsushi/Documents/flutter/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +201 ms] executing: [/home/atsushi/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +172 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +100 ms] executing: /usr/lib/android-sdk/platform-tools/adb devices -l
[ +206 ms] List of devices attached
[  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[  +10 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[  +15 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +943 ms] Generating
/home/atsushi/Desktop/helloworld/android/app/src/main/java/io/flutter/plugins/GeneratedPl
uginRegistrant.java
[ +375 ms] Starting incremental build...
[  +10 ms] Initializing file store
[  +83 ms] Skipping target: gen_localizations
[  +37 ms] complete
[  +17 ms] Launching lib/main.dart on Linux in debug mode...
[  +24 ms] /home/atsushi/Documents/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/atsushi/Documents/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart
.snapshot --sdk-root
/home/atsushi/Documents/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.OOWCWM/flutter_tool.KRNCGE/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initiali
zers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/cache.dill.track.dill
[  +78 ms] Building Linux application...
[  +61 ms] <- compile package:helloworld/main.dart
[   +9 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
/home/atsushi/Desktop/helloworld/linux
[ +198 ms] -- Configuring done
[  +89 ms] -- Generating done
[  +18 ms] -- Build files have been written to:
/home/atsushi/Desktop/helloworld/build/linux/debug
[  +18 ms] executing: ninja -C build/linux/debug install
[  +35 ms] ninja: Entering directory `build/linux/debug'
[+1561 ms] [1/6] Generating
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_basic_message_c
hannel.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_binary_messenge
r.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_json_message_co
dec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_json_method_cod
ec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_channel.
h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_response
.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_plugin_registra
r.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry
.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_standard_messag
e_codec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_standard_method
_codec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/flutter_linux.h,
_phony_
[  +15 ms] FAILED:
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/libflutter_linux_gtk.so
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_basic_message_c
hannel.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_binary_messenge
r.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_engine.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_json_message_co
dec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_json_method_cod
ec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_call.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_channel.
h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_method_response
.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_plugin_registra
r.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry
.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_standard_messag
e_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_standard_method
_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_value.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/fl_view.h
/home/atsushi/Desktop/helloworld/linux/flutter/ephemeral/flutter_linux/flutter_linux.h
flutter/_phony_
[   +8 ms] cd /home/atsushi/Desktop/helloworld/build/linux/debug/flutter &&
/usr/bin/cmake -E env FLUTTER_ROOT="/home/atsushi/Documents/flutter"
PROJECT_DIR="/home/atsushi/Desktop/helloworld" DART_OBFUSCATION="false"
TRACK_WIDGET_CREATION="true" TREE_SHAKE_ICONS="false" PACKAGE_CONFIG=".packages"
FLUTTER_TARGET="/home/atsushi/Desktop/helloworld/lib/main.dart"
/home/atsushi/Documents/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64
Debug
[   +2 ms]
../../../../../../Documents/flutter/packages/flutter_tools/bin/tool_backend.dart:7:8:
Error: Error when reading
'/b/s/w/ir/k/archive/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.7.0/lib/path.dart'
: No such file or directory
[   +1 ms] import 'package:path/path.dart' as path; // ignore: package_path_import.
[        ]        ^
[        ]
../../../../../../Documents/flutter/packages/flutter_tools/bin/tool_backend.dart:21:8:
Error: Method not found: 'join'.
[   +1 ms]     ?? path.join('lib', 'main.dart');
[        ]        ^^^^
[        ]
../../../../../../Documents/flutter/packages/flutter_tools/bin/tool_backend.dart:46:36:
Error: Method not found: 'join'.
[   +1 ms]   final String flutterExecutable = path.join(
[        ]                                    ^^^^
[        ] ninja: build stopped: subcommand failed.
[  +66 ms] Building Linux application... (completed in 2.0s)
[+27116 ms] Exception: Build process failed
[  +14 ms] "flutter run" took 31,305ms.
[  +44 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:593:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +287 ms] ensureAnalyticsSent: 263ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +18 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1
```
</details> 

## flutter doctor -v
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-1.0.pre at /home/atsushi/Documents/flutter
    • Framework revision f25bd9c55c (11 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[!] Android toolchain - develop for Android devices (Android SDK version 27.0.1)
    • Android SDK at /usr/lib/android-sdk
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/usr/lib/android-sdk/tools/bin/sdkmanager" "platforms;android-28"
        "build-tools;28.0.3"
      or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions.
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/62258

> The are a few scenarios where a valid package_config.json wouldn't exist in the entrypoint script, such as if the precompiled snapshot was downloaded from the website or if the pub cache was modified since the last time the tool snapshot was generated. The correct fix is likely going to be either verifying the pub cache/pub get, snapshotting the script in the entrypoint file, along with the flutter tool, or rewriting without any package dependencies

By removing the package imports, we remove the need for a valid package_config, which massively simplifies running this script. Manually tested by deleting the package config for flutter tools and building a windows app successfully.

### CODE REVIEW

File: packages/flutter_tools/bin/tool_backend.dart [hunk 1]
```diff
@@ -42,9 +48,12 @@ or
...
   }
-
-  final String flutterExecutable = path.join(
-    flutterRoot, 'bin', Platform.isWindows ? 'flutter.bat' : 'flutter');
+  String flutterExecutable;
+  if (Platform.isWindows) {
+    flutterExecutable = '$flutterRoot\\bin\\flutter.bat';
+  } else {
+    flutterExecutable = '$flutterRoot/bin/flutter';
+  }
```
Comment (stuartmorgan) [inline packages/flutter_tools/bin/tool_backend.dart:56]: Maybe we should make a little `join_paths` helper function for this file that does what `path.join` does, so we can keep the simpler inline logic (and don't need to duplicate it more times if we need to add more paths)?

**Review by stuartmorgan-g — APPROVED** [review]
LGTM; one optional comment.

File: packages/flutter_tools/bin/tool_backend.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/bin/tool_backend.dart]: Done

**Comment by jonahwilliams** [comment]
ahh, nice to see our dart-sdk is broken again
