### PR TITLE
[RenderListWheelViewport] Update content dimensions to prevent scroll offset changes

### LINKED ISSUE #90953: ListWheelScrollView doesn't scroll to last item when items are removed
## Steps to Reproduce

1. Have a ListWheelScrollView 
2. Remove some items

**Expected results:** list behaves like a regular ListView

**Actual results:** list stucks until you scroll aggressively

<details>
  <summary>Video</summary>

https://user-images.githubusercontent.com/39104740/135265049-613bdf74-05c3-4d17-a7d6-d454145fec23.mp4
</details>

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyHomePage(),
  ));
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final list = [0, 1, 2, 3, 4, 5];
  final colors = [
    Colors.cyan,
    Colors.indigo,
    Colors.pink,
    Colors.red,
    Colors.blue,
    Colors.yellowAccent
  ];

  @override
  void initState() {
    super.initState();
  }

  Future<void> removeItems() async {
    if (list.length <= 3)
      return;
    list.removeLast();
    list.removeLast();
    list.removeLast();
    setState(() { });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            ElevatedButton(
              child: Text('remove items'),
              onPressed: removeItems,
            ),
          ],
        ),
      ),
      body: ListWheelScrollView(
        itemExtent: 400,
        physics: FixedExtentScrollPhysics(),
        children: [
          for (final index in list)
            SizedBox(
              width: double.infinity,
              child: Container(
                height: 400,
                color: colors[index % 6],
                child: Text(
                  index.toString(),
                  style: TextStyle(
                    fontSize: 30,
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.6.0-12.0.pre.136, on Microsoft Windows [Version 10.0.19041.1237], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.136 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision aaa14b8004 (2 hours ago), 2021-09-29 06:03:04 -0400
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1237]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 94.0.992.31

! Doctor found issues in 1 category.
```
</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #90953

Update content dimensions first when layout to prevent scroll offset changes.

### CODE REVIEW

**Comment by Hixie** [comment]
Calling performLayout from within performLayout is really dubious... are we sure about this?

**Comment by Hixie** [comment]
(cc @Piinks who may have opinions on this code)

**Review by Piinks — COMMENTED** [review]
Hey @xu-baolin, happy new year! 🎉 

I wonder how we handle this in other viewports, isn't there a correction we apply if `!offset.applyContentDimensions`?

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 1]
```diff
@@ -759,27 +762,27 @@ class RenderListWheelViewport
...
+    // 'list_wheel_scroll_view_test.dart'.
     final double minScrollExtent = childManager.childExistsAt(targetFirstIndex - 1)
       ? _minEstimatedScrollExtent
       : indexToScrollOffset(targetFirstIndex);
     final double maxScrollExtent = childManager.childExistsAt(targetLastIndex + 1)
-        ? _maxEstimatedScrollExtent
-        : indexToScrollOffset(targetLastIndex);
+      ? _maxEstimatedScrollExtent
+      : indexToScrollOffset(targetLastIndex);
     offset.applyContentDimensions(minScrollExtent, maxScrollExtent);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:778]: Adjust the content dimensions for there is a special[ test case](https://github.com/doxuanviet1996/flutter/blob/89452a972a5ba3cdb6720a438f43ff5d6082fa69/packages/flutter/test/widgets/list_wheel_scroll_view_test.dart#L159)

Comment (xu-baolin) [reply packages/flutter/lib/src/rendering/list_wheel_viewport.dart:778]: The logic here is difficult to understand, so I linked this test case in the comments.

**Comment by xu-baolin** [comment]
> Calling performLayout from within performLayout is really dubious... are we sure about this?

Yes, it seemed weird to do so, I changed a solution.

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 2]
```diff
@@ -759,27 +762,27 @@ class RenderListWheelViewport
...
 
-    offset.applyViewportDimension(_viewportExtent);
-
     // Applying content dimensions bases on how the childManager builds widgets:
     // if it is available to provide a child just out of target range, then
     // we don't know whether there's a limit yet, and set the dimension to the
     // estimated value. Otherwise, we set the dimension limited to our target
     // range.
+    // Test by 'infinite scrolling child builder with lower and upper limits' at
+    // 'list_wheel_scroll_view_test.dart'.
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:771]: Can you put this comment in the test itself? If a future change breaks the test, it will be helpful to have that context there as well.

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 3]
```diff
@@ -663,12 +663,10 @@ class RenderListWheelViewport
   /// by [childManager].
   @override
   void performLayout() {
-    final BoxConstraints childConstraints =
-      constraints.copyWith(
-        minHeight: _itemExtent,
-        maxHeight: _itemExtent,
-        minWidth: 0.0,
-      );
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:671]: Why move this? It does not seem to change later in the course of laying out.

**Review by Piinks — COMMENTED** [review]
This looks a lot better, thanks for updating!

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/rendering/list_wheel_viewport.dart:671]: Just move to where first use it.

**Review by Piinks — APPROVED** [review]
LGTM, nice!
