### PR TITLE
Fix crash when widgetspan does not produce a semantics node in render…

### LINKED ISSUE #69787: RangeError in RenderParagraph.assembleSemanticsNode
See also: b/172290978

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
        child: Container(
          color: Colors.green,
          child: RichText(
            text: TextSpan(
              children: [
                TextSpan(
                  text: 'Start\n',
                  recognizer: TapGestureRecognizer()..onTap = () { },
                ),
                WidgetSpan(
                  child: ExcludeSemantics(
                    excluding: true,
                    child: Icon(
                      Icons.edit,
                      size: 16,
                      semanticLabel: 'excluded',
                    ),
                  ),
                ),
                WidgetSpan(
                  child: ExcludeSemantics(
                    excluding: false,
                    child: Icon(
                      Icons.edit,
                      size: 16,
                      semanticLabel: 'included',
                    ),
                  ),
                ),
                TextSpan(text: 'End'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

Produces the following error:

```
I/flutter (23037): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23037): The following RangeError was thrown during a scheduler callback:
I/flutter (23037): RangeError (index): Invalid value: Only valid value is 0: 1
I/flutter (23037): 
I/flutter (23037): When the exception was thrown, this was the stack:
I/flutter (23037): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
I/flutter (23037): #1      List.elementAt (dart:core-patch/growable_array.dart:386:16)
I/flutter (23037): #2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:922:52)
I/flutter (23037): #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3717:13)
I/flutter (23037): #4      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3587:16)
I/flutter (23037): #5      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2631:25)
I/flutter (23037): #6      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1081:16)
I/flutter (23037): #7      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:459:21)
I/flutter (23037): #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:895:13)
I/flutter (23037): #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
I/flutter (23037): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (23037): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (23037): #12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (23037): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (23037): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### PR DESCRIPTION
**Pull request by chunhtai**
… paragraph

## Description
The change adds semantics tags to mark the relationship between semantics nodes and their corresponding render object.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/69787

## Tests

I added the following tests:

see files

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chunhtai** [comment]
cc @mehmetf

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -5369,6 +5369,48 @@ class Flow extends MultiChildRenderObjectWidget {
   }
 }
 
+class _SemanticsTagWidget extends SingleChildRenderObjectWidget {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:5372]: Can we just roll this functionality into the Semantics widget? That is, the Semantics widget should have a `tag` property to take a `SemanticsTag`.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/basic.dart:5372]: what is the correct behavior on the setting semantics tags in SemanticsNode? does it add the tag to itself or does it add the tags for the subtree only?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/basic.dart:5372]: What do you mean? We only have the `addTagForChildren` API, no?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/basic.dart:5372]: oh, yes, so the behavior should be adding tag for the semantics subtree except itself if it also introduce a semantics node?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/basic.dart:5372]: Yeah

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 2]
```diff
@@ -956,6 +987,10 @@ class RenderParagraph extends RenderBox
         newChildren.add(newChild);
       }
     }
+    // Makes sure we exhausted the list.
+    assert(childIndex == children.length);
```
Comment (dbrinegar) [inline packages/flutter/lib/src/rendering/paragraph.dart:991]: There seem valid cases where childIndex < children.length.

In my test where this used to crash, I get childIndex: 2, children.length 7, placeholderIndex: 8 at this point, as a reference.

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:991]: That is unexpected, we have to annotate all the semantics children, or they may not have the correct semantics. Do you have a repro example?

Comment (mehmetf) [reply packages/flutter/lib/src/rendering/paragraph.dart:991]: Does my complicated example help? That is pretty close to what customer:money is actually doing. https://github.com/flutter/flutter/issues/69787#issuecomment-722169455

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/paragraph.dart:991]: We may be missing the use case where a WidgetSpan is bubbling up more than one semantic node, something like:

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
        child: Container(
          color: Colors.green,
          child: RichText(
            text: TextSpan(
              children: [
                TextSpan(
                  text: 'Start\n',
                  recognizer: TapGestureRecognizer()..onTap = () { },
                ),
                WidgetSpan(
                  child: Icon(
                    Icons.edit,
                    size: 16,
                  ),
                ),
                WidgetSpan(
                  child: Row(
                    children: [
                      Semantics(
                        container: true,
                        child: Icon(
                          Icons.edit,
                          size: 16,
                          semanticLabel: 'foo',
                        ),
                      ),
                      Semantics(
                        container: true,
                        child: Icon(
                          Icons.edit,
                          size: 16,
                          semanticLabel: 'bar',
                        ),
                      ),
                    ],
                  ),
                ),
                TextSpan(text: 'End'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

@chunhtai can you try this with your change and see if it works? There can probably be more than one semantics node in `children` for a given `placeholderIndex`.

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:991]: yes, this pr missed this use case, I will update it to make sure it works

Comment (dbrinegar) [reply packages/flutter/lib/src/rendering/paragraph.dart:991]: Also feel free to ping me on chat if would be helpful, happy to walk through it or help dig. I don't have a simple setup, but have a snapshot with the above crash.

**Comment by chunhtai** [comment]
Thanks for reviewing ! @@goderbauer @mehmetf @dbrinegar 
Addressed all of the issues, ready for another look

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 3]
```diff
@@ -913,6 +914,12 @@ class SemanticsProperties extends DiagnosticableTree {
   /// on iOS and TalkBack on Android).
   final SemanticsSortKey? sortKey;
 
+  /// Adds additional information onto the semantics subtree.
+  ///
+  /// This property provides a way for rendering objects to annotate their
+  /// semantics children without directly access them.
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:920]: Specifies a set of tags to be applied to the child SemanticsNodes of this widget.

The tag is added to all child SemanticsNodes that pass through the RenderObject corresponding to this widget while looking to be attached to a parent SemanticsNode.

Tags are used to communicate to a parent SemanticsNode that a child SemanticsNode was passed through a particular RenderObject. The parent can use this information to determine the shape of the semantics tree.

See also:

 * [SemanticsConfiguration.addTagForChildren], to which the tags provided here will be passed.

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 4]
```diff
@@ -4072,6 +4074,17 @@ class RenderSemanticsAnnotations extends RenderProxyBox {
     markNeedsSemanticsUpdate();
   }
 
+  /// Adds Semenatics tags to the semantics subtree.
+  Set<SemanticsTag>? get tagsForChildren => _tagsForChildren;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/proxy_box.dart:4078]: I wonder if we should simplify the API here and in the Semantics widget to allow only one tag instead of a set. If you need multiple tags (uncommon) you can still wrap your tree in multiple Semantics widgets.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 5]
```diff
@@ -913,6 +914,12 @@ class SemanticsProperties extends DiagnosticableTree {
...
+  final Set<SemanticsTag>? tagsForChildren;
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:921]: Can you add a test for the semantics widget to ensure that the tags are properly applied to the tree? (Currently we are only indirectly testing this via the RenderParagraph, but if we ever change how RenderParagraph works, this feature would be untested).

**Review by goderbauer — COMMENTED** [review]
LGTM once comments are resolved and @dbrinegar confirmed that this now fixes the crash for the actual use case.

**Comment by chunhtai** [comment]
Thanks @goderbauer, I addressed all the comments

@mehmetf @dbrinegar can you verify if this fixes the issue? I have ran the https://github.com/flutter/flutter/issues/69787#issuecomment-722169455 and it fixes the crash

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
A gentle ping.

**Review by mehmetf — APPROVED** [review]

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 6]
```diff
@@ -956,6 +988,10 @@ class RenderParagraph extends RenderBox
         newChildren.add(newChild);
       }
     }
+    // Makes sure we annotated all of the semantics children.
+    assert(childIndex == children.length);
```
Comment (dbrinegar) [inline packages/flutter/lib/src/rendering/paragraph.dart:992]: I think I've applied the right patch, but it is now asserting on this line for the case where it wasn't crashing before.

For the case that was crashing, childIndex == children.length == 0, which is where it used to have 7 children expecting 8.  Immediately after that case, childIndex comes out == 0 but children.length == 8 and this asserts.

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:992]: will reach out offline

Comment (dbrinegar) [reply packages/flutter/lib/src/rendering/paragraph.dart:992]: update: patch wasn't right.

Confirmed this fixes the crash.
