### PR TITLE
flutter attach should handle non-singular device gracefully

### LINKED ISSUE #18996: `flutter attach` crashes when there is no connected device
On todays master:
```
C:\Users\mit>flutter attach
No connected devices.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: eabec4ed7cf9493b)
Crash report written to C:\Users\mit\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## exception

NoSuchMethodError: NoSuchMethodError: The method 'getLogReader' was called on null.
Receiver: null
Tried calling: getLogReader()

```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:80)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#4      _rootRunUnary (dart:async/zone.dart:1134)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      Future._complete (dart:async/future_impl.dart:472)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## Doctor output:

```
C:\Users\mit>flutter doctor -v
[√] Flutter (Channel master, v0.5.6-pre.117, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.5.6-pre.117 at C:\Users\mit\dev\flutter
    • Framework revision 647076d767 (2 hours ago), 2018-07-02 14:45:42 +0200
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\mit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.1
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[√] VS Code, 32-bit edition (version 1.23.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.14.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by mravn-google**
Fixes #18996

### CODE REVIEW

File: packages/flutter_tools/test/commands/attach_test.dart [hunk 1]
```diff
@@ -68,6 +69,37 @@ void main() {
 
       verify(portForwarder.forward(devicePort)).called(1);
     });
+
+    testUsingContext('exits when no device connected', () async {
+      final AttachCommand command = new AttachCommand();
+      try {
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/attach_test.dart]: I think you can use 
```
expect([...], const throwsA(isInstanceOf<ToolExit>());
```

File: packages/flutter_tools/test/commands/attach_test.dart [hunk 2]
```diff
@@ -68,6 +69,37 @@ void main() {
...
+        when(device.id).thenReturn(id);
+        when(device.isLocalEmulator).thenAnswer((_) async => false);
+        when(device.sdkNameAndVersion).thenAnswer((_) async => 'Android 46');
+        return device;
+      }
+
+      final AttachCommand command = new AttachCommand();
+      testDeviceManager.addDevice(aDeviceWithId('1'));
+      testDeviceManager.addDevice(aDeviceWithId('2'));
+      try {
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/attach_test.dart]: same here

File: packages/flutter_tools/test/commands/attach_test.dart [hunk 3]
```diff
@@ -68,6 +69,37 @@ void main() {
...
       verify(portForwarder.forward(devicePort)).called(1);
     });
+
+    testUsingContext('exits when no device connected', () async {
+      final AttachCommand command = new AttachCommand();
+      try {
+        await createTestCommandRunner(command).run(<String>['attach']);
+        fail('Expect exception');
+      } catch (e) {
+        expect(e, const isInstanceOf<ToolExit>());
```
Comment (sigurdm) [inline packages/flutter_tools/test/commands/attach_test.dart]: Also test for correcct error message?

**Review by sigurdm — COMMENTED** [review]
LGTM

**Review by sigurdm — APPROVED** [review]

**Review by sigurdm — COMMENTED** [review]
LBeautifulTM
