### PR TITLE
iOS tools cleanup

### LINKED ISSUE #1823: `flutter run` installs (but doesn't start) apps on iOS Devices
flutter start (when it succeeds) installs the app on ios, but it doesn't start it -- I have to launch the app manually.

### LINKED ISSUE #3947: flutter install fails for iOS
```
%flutter install                                                                                      [/src/game]
Installing io.flutter.spaceblast to flutter_ipod_touch...
Uploading .generated package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - Error occurred: PackageInspectionFailed
```

`flutter run` works fine.

@chinmaygarde @devoncarew

### PR DESCRIPTION
**Pull request by tvolkert**
1) Fix `flutter install` on both device and simulator to refer to the actual
   bundle and not just the .generated folder
2) Fix `flutter run` on device to actually run vs just installing

Still TODO:
1) Discovered that isAppInstalled on iOS simulator always reports true,
   meaning it'll never actually try to install the app.

Fixes #3947
Fixes #1823

### CODE REVIEW

**Comment by tvolkert** [comment]
@chinmaygarde @devoncarew

File: packages/flutter_tools/lib/src/application_package.dart [hunk 1]
```diff
@@ -92,7 +106,11 @@ class IOSApp extends ApplicationPackage {
       return null;
 
     String projectDir = path.join('ios', '.generated');
-    return new IOSApp(iosProjectDir: projectDir, iosProjectBundleId: value);
+    return new IOSApp(
+      iosProjectDir: projectDir,
+      iosAppPath: path.join(projectDir, 'build', 'Release-iphoneos', 'Runner.app'),
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/application_package.dart]: I need to fix this - this assumes device over simulator

**Comment by eseidelGoogle** [comment]
Thank you so much.  So many basic bugs like this left to fix on the iOS side of things.

**Comment by eseidelGoogle** [comment]
Looks like the analysis step on travis failed (click the bubble above, or here: https://travis-ci.org/flutter/flutter/builds/132661557)

**Comment by tvolkert** [comment]
Yeah - fixing a bug in this, per the note above

**Comment by tvolkert** [comment]
Ok @chinmaygarde, ptal

**Comment by chinmaygarde** [comment]
lgtm
