### PR TITLE
Fix PlatformMenuItems with onSelectedIntent are never enabled

### LINKED ISSUE #121805: PlatformMenuItems with onSelectedIntent are never enabled
## Steps to Reproduce

1. Execute `flutter run -d macos` on the code sample on a macOS machine 
2. Press the `+` button in the app a few times to increment the counter
3. Press `cmd + 0` to demonstrate the counter responds to intents by resetting the counter
4. Press `cmd + =` to attempt to incerment the counter
5. Check the `Edit` menu in the macOS menu bar. Note that only `Reset` is enabled

**Expected results:** 

`PlatformMenuItems` with `.onSelectedIntent` should be enabled and dispatch the specified intent when selected.

**Actual results:** 

`PlatformMenuItems` with `.onSelectedIntent` are stuck in a disbled state and can never be used. 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

enum CounterOp {
  increment,
  reset,
}

class CounterIntent extends Intent {
  const CounterIntent(this.op);
  final CounterOp op;
}

class CounterAction extends Action<CounterIntent> {
  CounterAction({
    required this.increment,
    required this.reset,
  });

  final VoidCallback increment;
  final VoidCallback reset;

  @override
  Object? invoke(CounterIntent intent) {
    switch (intent.op) {
      case CounterOp.increment:
        increment();
        break;
      case CounterOp.reset:
        reset();
        break;
    }
    return null;
  }
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return PlatformMenuBar(
      menus: [
        const PlatformMenu(
          label: '',
          menus: [],
        ),
        PlatformMenu(
          label: 'Edit',
          menus: [
            const PlatformMenuItem(
              label: 'Increment',
              shortcut: SingleActivator(
                LogicalKeyboardKey.equal,
                meta: true,
              ),
              // onSelected: () {
              //   Actions.maybeInvoke(
              //     primaryFocus!.context!,
              //     const CounterIntent(CounterOp.increment),
              //   );
              // },
              onSelectedIntent: CounterIntent(CounterOp.increment)
            ),
            PlatformMenuItem(
              label: 'Reset',
              shortcut: const SingleActivator(
                LogicalKeyboardKey.digit0,
                meta: true,
              ),
              onSelected: () {
                Actions.maybeInvoke(
                  primaryFocus!.context!,
                  const CounterIntent(CounterOp.reset),
                );
              },
            ),
          ],
        ),
      ],
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _increment() {
    setState(() {
      _counter++;
    });
  }

  void _reset() {
    setState(() {
      _counter = 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Actions(
      actions: {
        CounterIntent: CounterAction(
          increment: _increment,
          reset: _reset,
        ),
      },
      child: Focus(
        autofocus: true,
        child: Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _increment,
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Note: XCode build output excluded due to github comment character limits.

```
[ +529 ms] VM Service URL on device: http://127.0.0.1:49924/0ptorkDYu64=/
[   +3 ms] Caching compiled dill
[  +13 ms] Connecting to service protocol: http://127.0.0.1:49924/0ptorkDYu64=/
[  +70 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:49924/0ptorkDYu64=/.
[  +80 ms] DDS is listening at http://127.0.0.1:49927/HJT48nSidt4=/.
[  +24 ms] Successfully connected to service protocol: http://127.0.0.1:49924/0ptorkDYu64=/
[  +13 ms] DevFS: Creating new filesystem on the device (null)
[   +6 ms] DevFS: Created new filesystem on the device (file:///var/folders/4c/fxvr7v8s4q93hmm6lhv31yl00000gn/T/com.example.flutterReproPlatformmenuitem/flutter_repro_platformmenuitems9E3sG/flutter_repro_platformmenuitem/)
[        ] Updating assets
[  +46 ms] Syncing files to device macOS...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_repro_platformmenuitem/main.dart 67945d88-a29d-44a5-b726-1cbc6dc8e387
[        ] <- 67945d88-a29d-44a5-b726-1cbc6dc8e387
[        ] Bundle processing done.
[  +40 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device macOS... (completed in 43ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x138829c20.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on macOS is available at: http://127.0.0.1:49927/HJT48nSidt4=/
[ +187 ms] The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:49927/HJT48nSidt4=/
[+9800 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///var/folders/4c/fxvr7v8s4q93hmm6lhv31yl00000gn/T/com.example.flutterReproPlatformmenuitem/flutter_repro_platformmenuitems9E3sG/flutter_repro_platformmenuitem/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

[   +3 ms] "flutter run" took 21,910ms.
[  +57 ms] ensureAnalyticsSent: 55ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing flutter_repro_platformmenuitem...                     
No issues found! (ran in 3.8s)
```

```
[✓] Flutter (Channel master, 3.9.0-1.0.pre.15, on macOS 13.1 22C65 darwin-arm64, locale en-US)
    • Flutter version 3.9.0-1.0.pre.15 on channel master at /Users/joshuamatthews/.fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59ea58b293 (14 minutes ago), 2023-03-02 11:03:48 -0500
    • Engine revision a3031df023
    • Dart version 3.0.0 (build 3.0.0-287.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/joshuamatthews/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Users/joshuamatthews/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode-14.2.0.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/joshuamatthews/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/joshuamatthews/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Users/joshuamatthews/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8617.56/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

## Video

https://user-images.githubusercontent.com/1316184/222491374-cec10cdc-af72-44c9-9222-59b10bb89113.mov

## Root cause

The cause is almost certainly this line in [`PlatformMenuItem.serialize`][1], which only considers whether `onSelected` has been set to determine whether the item is enabled. Changing the condition to `item.onSelected != null || item.onSelectedIntent != null` fixes the issue. I'm happy to submit a fix as a PR, just working on getting the tests running locally so I can update them first.

[1]: https://github.com/flutter/flutter/blob/59ea58b293dfd7f8823e1f8b84c745ad6e81ef5f/packages/flutter/lib/src/widgets/platform_menu_bar.dart#L808

### PR DESCRIPTION
**Pull request by jmatth**
Fixes #121805.

The fix is pretty simple: the `PlatformMenuItem` serialization logic only considered whether `onSelected` was non-null when determining whether an item should be enabled. With this change it now checks whether `onSelected` or `onSelectedIntent` are non-null.

I'm less confident about my updates to the tests for this change. The existing tests have code in place to record menu item activations, but then that data isn't actually read anywhere. Based on that observation I didn't implement recording intents sent by activated menu items, since doing so would seemingly go against the style guide's advice to `Avoid implementing features you don’t need`.

Based on `git blame`, CC @gspencergoog

### CODE REVIEW

File: packages/flutter/test/widgets/platform_menu_bar_test.dart [hunk 1]
```diff
@@ -288,6 +289,7 @@ const List<String> subMenu2 = <String>[
 
 List<PlatformMenuItem> createTestMenus({
   void Function(String)? onActivate,
+  Intent Function(String)? onActivateIntent,
```
Comment (gspencergoog) [inline packages/flutter/test/widgets/platform_menu_bar_test.dart:292]: This can just pass a nullable Intent.

File: packages/flutter/test/widgets/platform_menu_bar_test.dart [hunk 2]
```diff
@@ -53,6 +53,7 @@ void main() {
             child: PlatformMenuBar(
               menus: createTestMenus(
                 onActivate: onActivate,
+                onActivateIntent: (String item) => TestPlatformMenuBarIntent(item),
```
Comment (gspencergoog) [inline packages/flutter/test/widgets/platform_menu_bar_test.dart:56]: If you change the argument type in `createTestMenus`, this can just be:
```suggestion
                onActivateIntent: TestPlatformMenuBarIntent(subMenu1[0]),
```

File: packages/flutter/test/widgets/platform_menu_bar_test.dart [hunk 3]
```diff
@@ -315,7 +317,7 @@ List<PlatformMenuItem> createTestMenus({
           members: <PlatformMenuItem>[
             PlatformMenuItem(
               label: subMenu1[0],
-              onSelected: onActivate != null ? () => onActivate(subMenu1[0]) : null,
+              onSelectedIntent: onActivateIntent?.call(subMenu1[0]),
```
Comment (gspencergoog) [inline packages/flutter/test/widgets/platform_menu_bar_test.dart:320]: I'm a little surprised this doesn't cause the existing test to fail, but maybe it ends up producing the same thing? I'm surprised, because this change prevents the test from ever testing the `onActivate` case, since it's never used.

Anyhow, I think there need to be two tests: one that tests `onSelected`, and one that tests `onSelectedIntent`.  In this test menu creation function, you can just put back the line you deleted, and send in the nullable intent that came into the function.

While you're at it, can you rename the "onActivate*" arguments to this function to "onSelected*", since it should have been called that anyhow (it got missed in a name change).

File: packages/flutter/test/widgets/platform_menu_bar_test.dart (hunk 2 above)
Comment (gspencergoog) [inline packages/flutter/test/widgets/platform_menu_bar_test.dart:56]: This should be split into two tests, one that tests `onActivate`, and one that tests `onActivateIntent`, since they can't both be specified at the same time.

**Review by gspencergoog — COMMENTED** [review]
Thanks for fixing this!

File: packages/flutter/test/widgets/platform_menu_bar_test.dart (hunk 3 above)
Comment (jmatth) [reply packages/flutter/test/widgets/platform_menu_bar_test.dart:320]: > I'm a little surprised this doesn't cause the existing test to fail, but maybe it ends up producing the same thing?

My understanding is yes, it just produces the same result. Looking at the test, it only has [two calls to `expect`]:

1. Expect that `Menu.setMenus` was called
2. Expect that the serialized version of the menu structure matches a hardcoded expected value

The serialized version of the menu items doesn't contain any information about whether a callback or intent was provided, only whether the item is enabled or disabled, so specifying either one satisfies the test.

>  I'm surprised, because this change prevents the test from ever testing the onActivate case, since it's never used.

As far as I can tell, there are currently no tests that actually test activating menu items. There is code [earlier in the test suite][2] that records which items have their callback invoked, but none of the tests ever actually select a menu item or `expect` that any items were selected. All that `onActivate` recording is just dead code right now.

> Anyhow, I think there need to be two tests: one that tests onSelected, and one that tests onSelectedIntent. In this test menu creation function, you can just put back the line you deleted, and send in the nullable intent that came into the function.
> While you're at it, can you rename the "onActivate*" arguments to this function to "onSelected*", since it should have been called that anyhow (it got missed in a name change).

SGTM and SGTM

[1]: https://github.com/jmatth/flutter/blob/c2aae6d83b8f437ee4cc76f6b7e6e23198ba0dba/packages/flutter/test/widgets/platform_menu_bar_test.dart#L72-L161
[2]: https://github.com/jmatth/flutter/blob/c2aae6d83b8f437ee4cc76f6b7e6e23198ba0dba/packages/flutter/test/widgets/platform_menu_bar_test.dart#L18-L32

Comment (gspencergoog) [reply packages/flutter/test/widgets/platform_menu_bar_test.dart]: Thanks for pointing that out.  I'll have to add some more tests, I can tell.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
Looks like there is an analyzer failure.

**Comment by jmatth** [comment]
Fixed, it should pass analysis now. Sorry about that.

File: packages/flutter/test/widgets/platform_menu_bar_test.dart [hunk 4]
```diff
@@ -233,27 +185,27 @@ void main() {
     testWidgets('character constructor', (WidgetTester tester) async {
       final ShortcutSerialization serialization = ShortcutSerialization.character('?');
       expect(serialization.toChannelRepresentation(), equals(<String, Object?>{
-        'shortcutCharacter': '?',
-        'shortcutModifiers': 0,
-      }));
+            'shortcutCharacter': '?',
+            'shortcutModifiers': 0,
+          }));
```
Comment (justinmc) [inline packages/flutter/test/widgets/platform_menu_bar_test.dart:190]: It's hard to tell on GitHub, but are these indentations intentional?  I thought they looked correct beforehand.

**Review by justinmc — APPROVED** [review]
LGTM :+1:

**Review by cbracken — APPROVED** [review]

**Review by loic-sharma — APPROVED** [review]
LGTM

**Comment by loic-sharma** [comment]
Consider updating the docs for `PlatformMenuItem.onSelected` and `PlatformMenuItem.onSelectedIntent` to say something like:

> If both [onSelected] and [onSelectedIntent] are unset, this menu item will be disabled.

I'd be fine with doing this in a subsequent pull request.

**Comment by jmatth** [comment]
I'd be fine adding the docs change to this PR if you'd prefer. I was thinking it would be nice to add something to the effect of `Only one of this and [onSelected]/[onSelectedIntent] may be non-null` to the docstrings anyway. Currently nothing tells you that those two fields are mutually exclusive until you try setting both and trip an assertion.

File: packages/flutter/test/widgets/platform_menu_bar_test.dart (hunk 4 above)
Comment (jmatth) [reply packages/flutter/test/widgets/platform_menu_bar_test.dart:190]: No, I think VSCode's auto format went rogue. I'll see if I can configure it to match the previous formatting.

**Comment by jmatth** [comment]
@loic-sharma: thoughts on the following for the new docstring? I figure it might be easier to agree on wording in Github comments to cut down on unnecessary CI runs.

```
At most one of [onSelected] and [onSelectedIntent] may be set. If neither field is set, this menu item will be disabled.
```

**Comment by loic-sharma** [comment]
That looks perfect!

**Comment by gspencergoog** [comment]
@jmatth Let me know when you're done, and I'll submit it. (seems like you're done, but I didn't want to submit it if you weren't).

**Comment by jmatth** [comment]
@gspencergoog yeah, I'm done. I think I've addressed everyone's comments.
