### PR TITLE
[web] Arrow keys change selected item in dropdown

### LINKED ISSUE #55320: [Web] DropDownButton focus tests are broken
[Skip Audit]

The tests introduced in #43722 do not work on web. The change corrected focus handling for the DropdownButton's selected item.

Here are the associated tests that are skipped, and the results from a test run. These tests have been notated to reference this issue.

---

https://github.com/flutter/flutter/blob/45c5250825b07d639a30bca39709b81f6b56c12d/packages/flutter/test/material/dropdown_test.dart#L2168

```
03:58 +453 ~8: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Selected element is focused when dropdown is opened                                                                 
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'two'
  Actual: 'one'
   Which: is different.
          Expected: two
            Actual: one
                    ^
           Differ at offset 0
When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49      throw_
package:test_api/src/frontend/expect.dart 154:30                                          fail
package:test_api/src/frontend/expect.dart 148:3                                           _expect
package:test_api/src/frontend/expect.dart 60:3                                            expect$
package:flutter_test/src/widget_tester.dart 348:3                                         expect$
dropdown_test.dart 2216:5                                                                 <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 47:50                onValue
package:dart-sdk/lib/async/zone.dart 1192:38                                              _rootRunUnary
package:dart-sdk/lib/async/zone.dart 1085:19                                              runUnary
package:dart-sdk/lib/async/future_impl.dart 141:18                                        handleValue
package:dart-sdk/lib/async/future_impl.dart 682:44                                        handleValueCallback
package:dart-sdk/lib/async/future_impl.dart 711:32                                        _propagateToListeners
package:dart-sdk/lib/async/future_impl.dart 526:5                                         [_completeWithValue]
package:dart-sdk/lib/async/future_impl.dart 556:7                                         <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 306:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 311:39  dcall
package:quiver/testing/src/async/fake_async.dart 265:32                                   [_drainMicrotasks]
package:quiver/testing/src/async/fake_async.dart 164:5                                    flushMicrotasks
package:flutter_test/src/binding.dart 1099:16                                             <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54                runBody
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12               _async
package:flutter_test/src/binding.dart 1087:35                                             <fn>
package:dart-sdk/lib/async/future.dart 202:37                                             <fn>
package:dart-sdk/lib/async/zone.dart 1180:38                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              <fn>
package:dart-sdk/lib/async/zone.dart 1184:13                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              callback
package:dart-sdk/lib/async/schedule_microtask.dart 43:11                                  _microtaskLoop
package:dart-sdk/lib/async/schedule_microtask.dart 52:5                                   _startMicrotaskLoop
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15               <fn>
(elided 7 frames from package:stack_trace)
The test description was:
  Selected element is focused when dropdown is opened
════════════════════════════════════════════════════════════════════════════════════════════════════
03:58 +453 ~8 -1: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Selected element is focused when dropdown is opened [E]                                                          
  Test failed. See exception logs above.
  The test description was: Selected element is focused when dropdown is opened
```

---

https://github.com/flutter/flutter/blob/45c5250825b07d639a30bca39709b81f6b56c12d/packages/flutter/test/material/dropdown_test.dart#L2228

```
04:01 +453 ~8 -1: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Selected element is correctly focused with dropdown that more items than fit on the screen                       
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <42>
  Actual: <1>
When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49      throw_
package:test_api/src/frontend/expect.dart 154:30                                          fail
package:test_api/src/frontend/expect.dart 148:3                                           _expect
package:test_api/src/frontend/expect.dart 60:3                                            expect$
package:flutter_test/src/widget_tester.dart 348:3                                         expect$
dropdown_test.dart 2279:5                                                                 <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 47:50                onValue
package:dart-sdk/lib/async/zone.dart 1192:38                                              _rootRunUnary
package:dart-sdk/lib/async/zone.dart 1085:19                                              runUnary
package:dart-sdk/lib/async/future_impl.dart 141:18                                        handleValue
package:dart-sdk/lib/async/future_impl.dart 682:44                                        handleValueCallback
package:dart-sdk/lib/async/future_impl.dart 711:32                                        _propagateToListeners
package:dart-sdk/lib/async/future_impl.dart 526:5                                         [_completeWithValue]
package:dart-sdk/lib/async/future_impl.dart 556:7                                         <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 306:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 311:39  dcall
package:quiver/testing/src/async/fake_async.dart 265:32                                   [_drainMicrotasks]
package:quiver/testing/src/async/fake_async.dart 164:5                                    flushMicrotasks
package:flutter_test/src/binding.dart 1099:16                                             <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54                runBody
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12               _async
package:flutter_test/src/binding.dart 1087:35                                             <fn>
package:dart-sdk/lib/async/future.dart 202:37                                             <fn>
package:dart-sdk/lib/async/zone.dart 1180:38                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              <fn>
package:dart-sdk/lib/async/zone.dart 1184:13                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              callback
package:dart-sdk/lib/async/schedule_microtask.dart 43:11                                  _microtaskLoop
package:dart-sdk/lib/async/schedule_microtask.dart 52:5                                   _startMicrotaskLoop
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15               <fn>
(elided 7 frames from package:stack_trace)
The test description was:
  Selected element is correctly focused with dropdown that more items than fit on the screen
════════════════════════════════════════════════════════════════════════════════════════════════════
04:01 +453 ~8 -2: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Selected element is correctly focused with dropdown that more items than fit on the screen [E]                   
  Test failed. See exception logs above.
  The test description was: Selected element is correctly focused with dropdown that more items than fit on the screen
```

---

https://github.com/flutter/flutter/blob/45c5250825b07d639a30bca39709b81f6b56c12d/packages/flutter/test/material/dropdown_test.dart#L2291

```
04:07 +453 ~8 -2: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Having a focused element doesn't interrupt scroll when flung by touch                                            
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element
When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49      throw_
package:dart-sdk/lib/core/iterable.dart 554:63                                            get single
package:flutter_test/src/controller.dart 646:35                                           [_getElementPoint]
package:flutter_test/src/controller.dart 623:12                                           getTopLeft
package:flutter_test/src/controller.dart 664:53                                           getRect
dropdown_test.dart 2346:33                                                                <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 47:50                onValue
package:dart-sdk/lib/async/zone.dart 1192:38                                              _rootRunUnary
package:dart-sdk/lib/async/zone.dart 1085:19                                              runUnary
package:dart-sdk/lib/async/future_impl.dart 141:18                                        handleValue
package:dart-sdk/lib/async/future_impl.dart 682:44                                        handleValueCallback
package:dart-sdk/lib/async/future_impl.dart 711:32                                        _propagateToListeners
package:dart-sdk/lib/async/future_impl.dart 526:5                                         [_completeWithValue]
package:dart-sdk/lib/async/future_impl.dart 556:7                                         <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 306:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 311:39  dcall
package:quiver/testing/src/async/fake_async.dart 265:32                                   [_drainMicrotasks]
package:quiver/testing/src/async/fake_async.dart 164:5                                    flushMicrotasks
package:flutter_test/src/binding.dart 1099:16                                             <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54                runBody
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12               _async
package:flutter_test/src/binding.dart 1087:35                                             <fn>
package:dart-sdk/lib/async/future.dart 202:37                                             <fn>
package:dart-sdk/lib/async/zone.dart 1180:38                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              <fn>
package:dart-sdk/lib/async/zone.dart 1184:13                                              _rootRun
package:dart-sdk/lib/async/zone.dart 1077:19                                              run
package:dart-sdk/lib/async/zone.dart 979:7                                                runGuarded
package:dart-sdk/lib/async/zone.dart 1019:23                                              callback
package:dart-sdk/lib/async/schedule_microtask.dart 43:11                                  _microtaskLoop
package:dart-sdk/lib/async/schedule_microtask.dart 52:5                                   _startMicrotaskLoop
package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15               <fn>
(elided 7 frames from package:stack_trace)
The test description was:
  Having a focused element doesn't interrupt scroll when flung by touch
════════════════════════════════════════════════════════════════════════════════════════════════════
04:07 +453 ~8 -3: /tmp/flutter sdk/packages/flutter/test/material/dropdown_test.dart: Having a focused element doesn't interrupt scroll when flung by touch [E]                                        
  Test failed. See exception logs above.
  The test description was: Having a focused element doesn't interrupt scroll when flung by touch
```

### LINKED ISSUE #75929: [Flutter Web] Dropdown does not respond to navigation key events (up/down arrow).
1. Create a simple dropdown widget. [Dartpad link](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)
2. Run it for web (either canvaskit or htmlkit)
3. Expand dialog button (either click with mouse or focus and hit space)
4. Try navigating through drop down items using keyboard.

**Expected results:** Keyboard navigation works. 🙂

**Actual results:** Keyboard navigation doesn't work. 😔

<details>
flutter doctor -v output:
```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.1.pre at /Users/abelsm/development/flutter
    • Framework revision 8f89f6505b (8 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abelsm/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by mdebbar**
When a dropdown menu is open, arrow keys should move between items.

On other platforms, this works because they have global arrow key shortcuts to move focus. But the web doesn't use arrow keys to move focus, so it doesn't have these global shortcuts.

Fixes https://github.com/flutter/flutter/issues/75929

I was able to unskip all the `dropdown_test.dart` so I think we can close this issue:
Closes https://github.com/flutter/flutter/issues/55320

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -161,7 +161,10 @@ class _DropdownMenuItemButtonState<T> extends State<_DropdownMenuItemButton<T>>
   }
 
   static final Map<LogicalKeySet, Intent> _webShortcuts =<LogicalKeySet, Intent>{
-    LogicalKeySet(LogicalKeyboardKey.enter): const ActivateIntent(),
```
Comment (mdebbar) [inline packages/flutter/lib/src/material/dropdown.dart:164]: @gspencergoog I found out that this isn't necessary since we already have the `ButtonActivateIntent` in here. Let me know if this isn't correct and I'll be happy to put back `LogicalKeyboardKey.enter`.

Comment (gspencergoog) [reply packages/flutter/lib/src/material/dropdown.dart:164]: Yes, I think you're right.

File: packages/flutter/test/material/dropdown_test.dart [hunk 2]
```diff
@@ -2738,7 +2738,66 @@ void main() {
...
+    expect(value, equals('one'));
+
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown); // Focus 'two'.
+    await tester.pump();
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown); // Focus 'three'.
+    await tester.pump();
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowUp); // Back to 'two'.
+    await tester.pump();
+    await tester.sendKeyEvent(LogicalKeyboardKey.enter); // Select 'two'.
+    await tester.pump();
```
Comment (Piinks) [inline packages/flutter/test/material/dropdown_test.dart:2794]: Can we check that each of these comments regarding where the focus is are as expected?

**Review by Piinks — COMMENTED** [review]
This is awesome! And so many unskipped tests!

File: packages/flutter/test/material/dropdown_test.dart (hunk 2 above)
Comment (mdebbar) [reply packages/flutter/test/material/dropdown_test.dart:2794]: I re-checked and they look right. Are you seeing a wrong comment?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/test/material/dropdown_test.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/test/material/dropdown_test.dart:2794]: Not at all, just wondering if it was worth adding those expectations to the test. :)

**Review by Piinks — APPROVED** [review]
LGTM! 🎉
