### PR TITLE
[Android 16] Added Docs to Warn Users that SystemChrome.setPreferredOrientations will Not Work

### LINKED ISSUE #162724: Support Android 16 orientation change behaviors
### Use case

Developers that want to add support for Android 16 features might see a behavioral differences when working with screen orientations.

Apparently there is a change that is scheduled for Android 16: https://developer.android.com/about/versions/16/behavior-changes-16

### Proposal

Audit the required steps to adhere to the API changes in https://developer.android.com/about/versions/16/behavior-changes-16#implementation-details

This will probably affect the https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html API.

One thing that I'm not sure about it how we should handle the following:

```
The Android 16 orientation, resizability, and aspect ratio restrictions don't apply in the following situations:

...

- Screens that are smaller than sw600dp
```

### PR DESCRIPTION
**Pull request by jesswrd**
Added docs to warn users that `SystemChrome.setPreferredOrientations` will not work when Flutter apps target Android 16 (SDK 36). 

Fixes https://github.com/flutter/flutter/issues/162724

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 1]
```diff
@@ -46,18 +46,30 @@ enum DeviceOrientation {
   /// in [portraitUp]. Otherwise, the device shows its boot logo in landscape
   /// and this orientation is obtained by rotating the device 90 degrees
   /// clockwise from its boot orientation.
+  ///
+  /// If your Flutter app is targeting Android 16 (API 36) or later and you are using
+  /// a device with a display width >= 600 dp, then [portraitUp] is ignored.
   portraitUp,
```
Comment (reidbaker) [inline packages/flutter/lib/src/services/system_chrome.dart]: I am not sure the values are the right place to put this documentation.

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 2]
```diff
@@ -489,6 +501,10 @@ abstract final class SystemChrome {
   /// }
   /// ```
   ///
+  /// If your Flutter app is targeting Android 16 (API 36) or later and you are using
```
Comment (reidbaker) [inline packages/flutter/lib/src/services/system_chrome.dart]: I think under a code block will make this hard to find documentation. Why not put this with the other information about limitations on android ?
``` /// ## Limitations
  ///
  /// ### Android
```

**Review by reidbaker — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 1 above)
Comment (jesswrd) [reply packages/flutter/lib/src/services/system_chrome.dart]: I updated the docs for the values in addition to adding them at `setPreferredOrientations` as sort of a precaution. They were included in Android docs [here](https://developer.android.com/about/versions/16/behavior-changes-16#:~:text=The%20following%20values%20for%20screenOrientation%2C%20setRequestedOrientation()%2C%20and%20getRequestedOrientation()%20are%20ignored), and I think I've seen examples where we warn specific values are ignored. 

I realize it's implied that these values are ignored. I can still remove them if preferred.

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 2 above)
Comment (jesswrd) [reply packages/flutter/lib/src/services/system_chrome.dart]: done

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 1 above)
Comment (reidbaker) [reply packages/flutter/lib/src/services/system_chrome.dart]: If we normally document individual enum values then we should indicate that the values can be ignored on android and if they want more information then to read the SystemChrome documentation or link to the android documentation. What I want to avoid is a future where the definition of what is ignored changes and we forget to update these values despite knowing about the change.

Comment (jesswrd) [reply packages/flutter/lib/src/services/system_chrome.dart]: done

Comment (camsim99) [reply packages/flutter/lib/src/services/system_chrome.dart]: To clarify, these values are only ignored for `setPreferredOrientations` right? If so, I lean towards not putting these details in here and keeping it in the docs for that method. But, if you prefer we add a note here, we should at least clarify that they are ignored for `setPreferredOrientations` in the docs because these values are used for other reasons.

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 3]
```diff
@@ -420,6 +436,10 @@ abstract final class SystemChrome {
   ///
   /// ### Android
   ///
+  /// If your Flutter app is targeting Android 16 (API 36) or later and you are using
+  /// a device with a display width >= 600 dp, then you cannot set the device
+  /// orientation. For more details see Android 16 docs [here](https://developer.android.com/about/versions/16/behavior-changes-16#ignore-orientation).
```
Comment (camsim99) [inline packages/flutter/lib/src/services/system_chrome.dart]: Could you note the `setPreferredOrientations` method here for clarity? Something like "...you cannot set the device orientation via `setPreferredOrientations`".

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 1 above)
Comment (jesswrd) [reply packages/flutter/lib/src/services/system_chrome.dart]: ah it's used in camera. I deleted the docs for the enums. done.

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 3 above)
Comment (jesswrd) [reply packages/flutter/lib/src/services/system_chrome.dart]: done

**Review by camsim99 — APPROVED** [review]
LGTM!

**Review by reidbaker — APPROVED** [review]
