### PR TITLE
Fix `TextField` horizontal drag conflicts

### LINKED ISSUE #124421: Draggable + TextField interaction stopped working
## Steps to Reproduce

1. Switch to 90f8ac5b41129a21878fe1607a9fcf57576a840c  on master channel or any commit which comes after 90f8ac5b41129a21878fe1607a9fcf57576a840c Execute `flutter run` on the code sample 

**Expected results:** TextField is horizontally draggable, text inside TextField changes to "Wee.. I'm being dragged"

**Actual results:** TextField is not horizontally draggable, text inside TextField is still "Drag me horizontally"

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

const defaultText = "Drag me horizontally";
const successText = "Wee.. I'm being dragged";
final dismissibleTextEditingController = TextEditingController(text: defaultText);
void main() {
  debugPrintGestureArenaDiagnostics = true;
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Container(
          padding: const EdgeInsets.all(50),
          child: Center(
            child: Dismissible(
              direction: DismissDirection.horizontal,
              onUpdate: (details) {
                dismissibleTextEditingController.text = successText;
                if (details.progress == 0.0) {
                  dismissibleTextEditingController.text = defaultText;
                }
              },
              key: const Key('Dismissible'),
              child: TextField(
                controller: dismissibleTextEditingController,
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

```

</details>

<details>
  <summary>Logs</summary>

Successful Gesture Arena on a690c0485f8afc6200f8d1dc60e483aeed8f01a7.
```
flutter: Gesture arena 3    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 3    ❙ Adding: LongPressGestureRecognizer#6412b(debugOwner: _TextSelectionGestureDetectorState#09cd1, state: ready)
flutter: Gesture arena 3    ❙ Adding: TapAndDragGestureRecognizer#a9a43(debugOwner: _TextSelectionGestureDetectorState#09cd1)
flutter: Gesture arena 3    ❙ Adding: HorizontalDragGestureRecognizer#f173b(debugOwner: GestureDetector, start behavior: start)
flutter: Gesture arena 3    ❙ Closing with 3 members.
flutter: Gesture arena 3    ❙ Rejecting: LongPressGestureRecognizer#6412b(debugOwner: _TextSelectionGestureDetectorState#09cd1, state: possible)
flutter: Gesture arena 3    ❙ Accepting: HorizontalDragGestureRecognizer#f173b(debugOwner: GestureDetector, start behavior: start)
flutter: Gesture arena 3    ❙ Self-declared winner: HorizontalDragGestureRecognizer#f173b(debugOwner: GestureDetector, start behavior: start)
```

Unsuccessful Gesture Arena on commit 90f8ac5b41129a21878fe1607a9fcf57576a840c and subsequent commits 
```
flutter: Gesture arena 1    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 1    ❙ Adding: LongPressGestureRecognizer#fec4e(debugOwner: _TextSelectionGestureDetectorState#1676e, state: ready)
flutter: Gesture arena 1    ❙ Adding: TapAndHorizontalDragGestureRecognizer#dc538(debugOwner: _TextSelectionGestureDetectorState#1676e)
flutter: Gesture arena 1    ❙ Adding: HorizontalDragGestureRecognizer#2bb6b(debugOwner: GestureDetector, start behavior: start)
flutter: Gesture arena 1    ❙ Closing with 3 members.
flutter: Gesture arena 1    ❙ Rejecting: LongPressGestureRecognizer#fec4e(debugOwner: _TextSelectionGestureDetectorState#1676e, state: possible)
flutter: Gesture arena 1    ❙ Accepting: TapAndHorizontalDragGestureRecognizer#dc538(debugOwner: _TextSelectionGestureDetectorState#1676e)
flutter: Gesture arena 1    ❙ Self-declared winner: TapAndHorizontalDragGestureRecognizer#dc538(debugOwner: _TextSelectionGestureDetectorState#1676e)
```

</details>

https://user-images.githubusercontent.com/64651636/230674533-5a53f23b-211c-411d-b2d8-3831cc7db6af.mov

https://user-images.githubusercontent.com/64651636/230674441-dedd85df-1543-4de1-bec5-581c2bc411b6.mov

### LINKED ISSUE #127017: [BUG] Scrollviews no longer work together after 3.10
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter downgrade 3.7.12
2. run application and observe the scroll behaviour
3. flutter upgrade
4. run the application and observe how the scroll views no longer work

### Expected results

Scrollview to behave as they did in 3.7.12

### Actual results

Scrollviews no long work correctly

### Code sample

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller = TextEditingController();

  @override
  void initState() {
    super.initState();

    _controller.text = """Tweak directional focus traversal by @gspencergoog in 116230
[framework] make ImageFiltered a repaint boundary by @jonahwilliams in 116385
[CP] Fix Snackbar TalkBack regression by @esouthren in 116417
Add widget of the week videos by @tvolkert in 116451
Speed up first asset load by encoding asset manifest in binary rather than JSON by @andrewkolos in 113637
Improve Flex layout comment by @loic-sharma in 116004
Do not parse stack traces in _findResponsibleMethod on Web platforms that use a different format by @jason-simmons in 115500
Support theming CupertinoSwitchs by @guidezpl in 116510
Fix MenuAnchor padding by @gspencergoog in 116573
Add ListenableBuilder with examples by @gspencergoog in 116543
Time picker precursors by @gspencergoog in 116450
Date picker special labeling for currentDate with localization and te… by @harperl-lgtm in 116433
Adds API in semanticsconfiguration to decide how to merge child semanticsConfigurations by @chunhtai in 110730
Revert “Speed up first asset load by encoding asset manifest in binary rather than JSON” by @CaseyHillers in 116662
Reland “Use semantics label for backbutton and closebutton for Android” by @chunhtai in 115776
Revert “Use semantics label for backbutton and closebutton for Android” by @chunhtai in 116675
LookupBoundary by @goderbauer in 116429
Reland “Use semantics label for backbutton and closebutton for Android” by @chunhtai in 116676
Fix wrong position of TabBarIndicator when it’s label size and has label padding by @zmtzawqlp in 116398
Add CupertinoSliverNavigationBar large title magnification on over scroll by @ivirtex in 110127
Update text field input width when there are prefix/suffix icons by @hangyujin in 116690
Add Material 3 support for ListTile - Part 1 by @TahaTesser in 116194
MediaQuery as InheritedModel by @moffatman in 114459
Add LookupBoundary to Material by @goderbauer in 116736
Floating cursor cleanup by @moffatman in 116746
Revert “Adds API in semanticsconfiguration to decide how to merge child semanticsConfigurations” by @CaseyHillers in 116839
More gracefully handle license loading failures by @Hixie in 87841
Taboo the word “simply” from our API documentation. by @Hixie in 116061
Fix NavigationBar ripple for non-default NavigationDestinationLabelBehavior by @TahaTesser in 116888
Add LookupBoundary to Overlay by @goderbauer in 116741
[framework] make opacity widget create a repaint boundary by @j""";
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _recomputeLongestLine();
      setState(() {});
    });
  }

  String _longestLine = '';

  void _recomputeLongestLine() {
    _longestLine = '';
    final _lines = _controller.text.split('\n');
    final buf = <String>[];

    for (var k = 0; k < _lines.length; k++) {
      buf.add((k + 1).toString());
    }
    // Find longest line
    _longestLine = '';
    for (var line in _lines) {
      if (line.length > _longestLine.length) _longestLine = line;
    }

    print("Longest: ${_longestLine}");
  }

  Widget _buildLongestLinePlaceHolder(double minWidth) {
    return ConstrainedBox(
      constraints: BoxConstraints(
        maxHeight: 0,
        minWidth: max(minWidth, 0),
      ),
      child: Padding(
        padding: const EdgeInsets.only(right: 16),
        child: Text(_longestLine, style: TextStyle(fontSize: 16)),
      ), // Add extra padding
    );
  }

  Widget _wrapInHorizontalScrollView({required Widget child}) {
    return LayoutBuilder(builder: (context, constraints) {
      return SingleChildScrollView(
        clipBehavior: Clip.none,
        scrollDirection: Axis.horizontal,
        child: IntrinsicWidth(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildLongestLinePlaceHolder(constraints.maxWidth),
              child,
            ],
          ),
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          height: 600,
          width: 600,
          color: Colors.yellowAccent,
          child: SingleChildScrollView(
            physics: const ClampingScrollPhysics(),
            child: _wrapInHorizontalScrollView(
              child: TextField(
                scrollPhysics: const NeverScrollableScrollPhysics(),
                scrollPadding: EdgeInsets.zero,
                controller: _controller,
                keyboardType: TextInputType.multiline,
                decoration: null,
                maxLines: null,
                enabled: true,
                onChanged: (t) {},
                readOnly: false,
                clipBehavior: Clip.none,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (2 available)
[✓] Network resources
```

### LINKED ISSUE #130198: PageView Swipe Functionality Lost After Upgrading to Flutter 3.10 with SelectableText.rich
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Ensure that you have Flutter version 3.10 installed.
2. Create a new Flutter project and replace the existing code in the main.dart file with the provided code.
3. Run the Flutter application on a device or emulator.
4. Observe that the app launches with a SelectableText widget inside a PageView.builder widget.
5. Attempt to swipe left or right on the PageView to switch between pages.
6. Notice that the swipe functionality is not working as expected and the pages are not changing.

### Expected results

When running the Flutter application, the PageView.builder should display multiple pages containing the SelectableText.rich widget. The PageView should retain its swipe functionality, allowing the user to swipe left or right to navigate between the pages. The SelectableText widget should also function as intended, allowing the user to select and copy text within the widget.

### Actual results

After upgrading to Flutter version 3.10 and running the application, the PageView.builder displays multiple pages with the SelectableText.rich widget. However, the swipe functionality of the PageView is disabled. It is not possible to swipe left or right to navigate between the pages. The expected swipe behavior is lost, making it difficult to switch between pages within the PageView.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

const String sampleText = '''
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”
So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.
''';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('SelectableText Sample'),
        ),
        body: PageView.builder(
          itemCount: 3,
          itemBuilder: (BuildContext context, int index) {
            return MyPage(index: index);
          },
        ),
      ),
    );
  }
}

class MyPage extends StatelessWidget {
  final int index;

  const MyPage({super.key, required this.index});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16.0),
      child: const Center(
        child: SelectableText.rich(
          TextSpan(
            text: sampleText,
            style: TextStyle(fontSize: 20.0),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale tr-TR)
    • Flutter version 3.10.5 on channel stable at /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
```

</details>

### LINKED ISSUE #142447: The behavior of Dismissible with TextFormFields is different for Android and iOS
### Steps to reproduce

1. Run the code sample on Android and iOS.
2. Dismiss an item with the red SizedBox and the TextFormField part.

### Expected results

The behavior should be the same on iOS and Android. In my opinion, it should on both platforms be possible to dismiss by sliding the TextFormField.

[If the TextField takes up the entire Dismissible, then it will handle the gesture. ](https://github.com/flutter/flutter/issues/40271#issuecomment-611640232)
This is also not true for iOS.

### Actual results

On Android you can dismiss an item by touching the red SizedBox part but also the TextFormField part.
On iOS you can dismiss an item only by touching the red SizedBox part but not the TextFormField part.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> items = List<int>.generate(10, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
          itemCount: items.length,
          itemBuilder: (_, index) => Dismissible(
              key: ValueKey<int>(items[index]),
              onDismissed: (DismissDirection direction) {
                setState(() {
                  items.removeAt(index);
                });
              },
              child: Row(
                children: [
                  Container(
                    width: 50,
                    height: 30,
                    color: Colors.red,
                  ),
                  SizedBox(
                      width: 200,
                      child: TextFormField(
                        initialValue: items[index].toString(),
                      )),
                  Container(
                    width: 50,
                    height: 30,
                    color: Colors.red,
                  ),
                ],
              ))),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/72440045/f13c2d0b-d510-48a0-8f3a-cbe597ac52cd

https://github.com/flutter/flutter/assets/72440045/2b4c3ae1-8b4c-42c0-9407-3d3ca6e2c95a

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!```

</details>

### LINKED ISSUE #142624: [iOS] Cannot scroll horizontally if swipe over TextField child
### Steps to reproduce

Create a PageView with some children, and in this children place some TextFields.

Example code: https://gist.github.com/dhafinrayhan/a63f94e0bb09ed7a2334c09c79012f14

### Expected results

On iPhone, If I swipe left/right on the TextFields, the PageView should change page like it happens on Android.

### Actual results

The page doesn't change.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [PageView].
void main() => runApp(const PageViewExampleApp());

class PageViewExampleApp extends StatelessWidget {
  const PageViewExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('PageView Sample')),
        body: const PageViewExample(),
      ),
    );
  }
}

class PageViewExample extends StatelessWidget {
  const PageViewExample({super.key});

  @override
  Widget build(BuildContext context) {
    final PageController controller = PageController();
    return PageView(
      /// [PageView.scrollDirection] defaults to [Axis.horizontal].
      /// Use [Axis.vertical] to scroll vertically.
      controller: controller,
      children: const <Widget>[
        Column(
          children: [
            Text('First Page'),
            TextField(),
          ],
        ),
        Column(
          children: [
            Text('Second Page'),
            TextField(),
          ],
        ),
        Column(
          children: [
            Text('Third Page'),
            TextField(),
          ],
        ),
      ],
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
    • Flutter version 3.16.8 on channel stable at /Users/lucagiordano/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lucagiordano/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • CLT L29 (mobile)           • WCR7N18B15009630                     • android-arm64  • Android 10 (API 29)
    • iPhone audimex LG (mobile) • 00008110-000C05E126A8201E            • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro (mobile)     • 595F703B-FAF7-4DF0-A27A-66F2D7722235 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1 23B2073 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 121.0.6167.85
    ! Error: Browsing on the local area network for MHiphone14. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone di Luca. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Currently on iOS `TextField` horizontal drag gestures will have precedence over parent horizontal drag gestures when competing with each other because the default `touchSlop` value used by `TextField` to calculate whether the threshold for a drag has been met is the same as the one used by parent horizontal drag gestures like `PageView`, and other `Scrollable`s. The default value is `18.0`, and because the `TextField` receives the `PointerEvent` first in this scenario, it always declares victory before any parent horizontal drag gestures has the chance to.

Native iOS behavior: The parent horizontal drag gestures will always win unless the drag originated on the cursor (collapsed selection), in that case the TextField cursor drag gestures will win.

This change:
* Introduces `BaseTapAndDragGestureRecognizer.eagerVictoryOnDrag` which can be used to configure the recognizer to declare victory immediately when it detects a drag, or when disabled it will wait until it is the last recognizer in the arena before declaring victory. The default behavior is that it declares victory immediately when the drag is detected.
* Eliminates the iOS cursor drag logic from `TextSelectionGestureDetector`, this logic is now delegated to the selection handle overlay which already had this logic in place.
* Enables iOS cursor to always beat other drag gestures by setting the touch slop lower.
* Disables `eagerVictoryOnDrag` for iOS to allow for parent drag gestures to win and match native behavior.

Fixes #124421, Fixes #130198, Fixes #142624, Fixes #142447, Fixes #127017 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 1]
```diff
@@ -984,14 +997,24 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
       assert(currentUp == null);
       _acceptDrag(_start!);
     }
 
+    // This recognizer will wait until it is the last one in the gesture arena
+    // before accepting a drag when `eagerVictoryOnDrag` is set to `false`.
+    if (_start != null && !eagerVictoryOnDrag) {
+      assert(_dragState == _DragState.possible);
+      assert(currentUp == null);
+      _dragState = _DragState.accepted;
```
Comment (justinmc) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1014]: Why is this not set in the previous `if` too?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -1924,6 +1929,7 @@ class _SelectionHandleOverlayState extends State<_SelectionHandleOverlay> with S
                 (PanGestureRecognizer instance) {
                   instance
                     ..dragStartBehavior = widget.dragStartBehavior
+                    ..gestureSettings = eagerlyAcceptDragWhenCollapsed ? const DeviceGestureSettings(touchSlop: 1.0) : null
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:1932]: Why 1.0? Could it be competing-slop-value minus one, or is 1.0 better? (I know you said you're still thinking about cleaning this up.)

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -2839,16 +2823,6 @@ class TextSelectionGestureDetectorBuilder {
             case PointerDeviceKind.invertedStylus:
             case PointerDeviceKind.touch:
             case PointerDeviceKind.unknown:
-              // For iOS platforms, a touch drag does not initiate unless the
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:2842]: Where is this removed logic covered now? I guess the drag listener on the selection handle?

**Review by justinmc — COMMENTED** [review]
Here's my understanding, tell me if anything is wrong:

For the case where a TextField is inside of a horizontal scrollable on iOS, dragging the selection handle should move the selection handle and not scroll. On other platforms, it should scroll horizontally.

The current behavior is that it always scrolls horizontally. The reason is that the touchSlop on the scrollable is less than the touchSlop on the selection handle. When the drag exceeds the lower touchSlop, that recognizer immediately wins.

<hr />

What would happen if the touchSlops were identical? By having different touchSlops, are we sidestepping the part of the gesture arena where two competing recognizers decide who receives the gesture?

Are the different touchSlops intentional, like we know that native recognizes these drags after different distances?

I want to understand whether this is a canonical Flutter solution to competing gesture detectors, or if not, make sure that this is a compromise that we're willing to make. If so I'm totally on board, this looks like a pretty straightforward change.

**Comment by Renzo-Olivares** [comment]
> For the case where a TextField is inside of a horizontal scrollable on iOS, dragging the selection handle should move the selection handle and not scroll. On other platforms, it should scroll horizontally.
> 
> The current behavior is that it always scrolls horizontally. The reason is that the touchSlop on the scrollable is less than the touchSlop on the selection handle. When the drag exceeds the lower touchSlop, that recognizer immediately wins.

On iOS the current behavior is that the `TextField` will always win horizontal drags. This is because the `touchSlop` of a `Scrollable` defaults to `18.0`, and the `touchSlop` that the `TextField` is using is also `18.0`. Because they are identical the first recognizer to receive the drag will win, and that will be the `TextField`. The desired behavior here is that the parent `Scrollable` will always win drag gestures, unless the gesture began on the cursor.

On Android the current behavior is that the `Scrollable` always wins horizontal drags. This is because the `touchSlop` of a  `Scrollable` on Android provided by the native platform seems to be around `8.0`, and the `touchSlop` on the `TextField` is `18.0`. Because the `Scrollable` has a lower touch slop it will detect the drag first even if the drag is on the `TextField`. This is the expected behavior on Android, but if anyone changes their `touchSlops` i.e. making the `Scrollable`s `touchSlop` higher or identical to the `touchSlop` of the `TextField` (`18.0`) then they will also experience the unexpected behavior that is being observed on iOS.

The changes in this PR only affect iOS at the moment.

> What would happen if the touchSlops were identical? By having different touchSlops, are we sidestepping the part of the gesture arena where two competing recognizers decide who receives the gesture?
> 
> Are the different touchSlops intentional, like we know that native recognizes these drags after different distances?

If `touchSlops` are identical then the recognizer that first receives the `PointerEvent` will declare victory first. I'm not too sure if different `touchSlops` are intentional, Android provides `getScaledTouchSlop` which we utilize to set the default on Android https://developer.android.com/reference/android/view/ViewConfiguration#getScaledTouchSlop() , which is why Android devices aren't experiencing this issue. iOS does not provide such a constant besides some related documentation in the `UILongPressGestureRecognizer` https://developer.apple.com/documentation/uikit/uilongpressgesturerecognizer/1616427-allowablemovement?language=objc (states `10.0`). I think changing the `touchSlop` is sidestepping the arena, but I think it is reasonable in the scenario that it is being used in this PR (to allow the cursor to always win). An alternative would be to add some type of flag to `PanGestureRecognizer` so that it can achieve this behavior, but i'm leaning towards overriding the `touchSlop` versus expanding the API surface.

> I want to understand whether this is a canonical Flutter solution to competing gesture detectors, or if not, make sure that this is a compromise that we're willing to make. If so I'm totally on board, this looks like a pretty straightforward change.

Delaying the drag acceptance until all other recognizers have lost is similar to what we do with `TapGestureRecognizer` so that other recognizers can beat it.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1014]: Because in the case of `eagerVictoryOnDrag == true`, it is set immediately when the drag is detected.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:1932]: I like the idea of competing-slop-value minus one, or maybe minus something higher than 1 to be sure that it always wins.

File: packages/flutter/test/gestures/tap_and_drag_test.dart [hunk 4]
```diff
@@ -653,6 +656,37 @@ void main() {
...
+    // will only win when it is the last recognizer in the arena.
+    tapAndDrag.addPointer(downB);
+    pans.addPointer(downB);
+    tester.closeArena(5);
+    tester.route(downB);
+    tester.route(pointer.move(const Offset(40.0, 45.0)));
+    tester.route(pointer.up());
+    expect(events, <String>[
+      'panstart',
+      'panend']);
```
Comment (justinmc) [inline packages/flutter/test/gestures/tap_and_drag_test.dart:687]: Super nit: I would typically do

```dart
  'panend',
]);
```

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -2506,6 +2506,191 @@ void main() {
...
+
+    expect(dismissed, false);
+    // A horizontal drag directly on the TextField, but not on the current
+    // collapsed selection should allow for the Dismissible to be dismissed.
+    await tester.dragFrom(tester.getRect(find.byType(TextField)).centerRight - const Offset(0.1, 0.0), const Offset(-400.0, 0.0));
+    await tester.pumpAndSettle();
+    expect(dismissed, true);
+  },
+    variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS }),
+  );
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2692]: Nit: Consider also testing the behavior for this on the other platforms (cursor is not dragged).

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: 

Thanks for talking this over with me yesterday and for the clear explanation of the changes in the PR description, it saved me some time in understanding everything.

File: packages/flutter/test/material/text_field_test.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/text_field_test.dart:2692]: I'll add these tests in a follow up PR that changes the Android/Fuchsia behavior.
