### PR TITLE
Fix EditableText misplaces caret when selection is invalid

### LINKED ISSUE #120631: TextField ignores user input, and cursor is rendered wrong in the middle of the text
## Steps to Reproduce

Hello, there is an input problem with ```TextField``` or ```TextFromField``` on my Redmi 6.
When my page rendered, and I click first time on a TextField, it gets focus, and the keyboard coming up, and i type some numbers, but nothing appears in the TextField.

I figured out, it causes the ```keyboardType: TextInputType.number,``` settings, and i noticed visually, that the cursor is blinking first in the right place, but after the xiaomi keyboard coming up, the cursor is moving to the center of the TextField, and in this state, i cannot type anything.

I'm sure the error is caused by the xiaomi numeric keypad. If I configure with normal keyboard, everything is fine.

This wrong state happening only for the first click on the Textfield. If I click after to another, it is ok, and I click again to the first one is also ok.
 
If I have only one TextField, i can only get out of this wrong state, if i click on the right side of the TextField. It is not easy to find where it get's the good focus (cursor).

There are no error messages even with verbose mode.

<details>
<summary>Code sample</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      SizedBox(
          width: 60,
          child: TextField(
            controller: textController,
            expands: false,
            textAlign: TextAlign.center,
            keyboardType: TextInputType.number,
            inputFormatters: <TextInputFormatter>[
              FilteringTextInputFormatter.digitsOnly
            ],
            decoration: const InputDecoration(
              contentPadding: EdgeInsets.all(4),
              isDense: true,
              fillColor: Color(0xff202020),
              border: UnderlineInputBorder(),
            ),
          )),
      Padding(
        padding: const EdgeInsets.only(left: 7.5, right: 7.5),
        child: Text(cikk.me),
      ),
      Container(
        color: blue,
        child: SizedBox(
          width: 80,
          height: 32,
          child: Stack(
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: createIcon(cikk)),
        ),
      ),
    ]);
  }
```

</details>

<details>
  <summary>Logs</summary>

```

```

```
```

```
$ flutter doctor -v
[!] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale en-HU)
    • Flutter version 3.7.3 on channel stable at /Users/myuser/Documents/Programming/install/flutter
    ! The flutter binary is not on your path. Consider adding /Users/myuser/Documents/Programming/install/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/myuser/Documents/Programming/install/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (5 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myuser/Library/Android/sdk/
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Redmi 6 (mobile) • d5b3a88b7d29 • android-arm    • Android 9 (API 28)
    • macOS (desktop)  • macos        • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

When the cursor is in a wrong state:

IMG_E1602

### PR DESCRIPTION
**Pull request by bleroux**
## Description

`EditableTextState._handleFocusChanged` adjusts the selection when a text field is focused. But if the selection becomes invalid (for instance after setting TextController.text) on an already focused field the position won’t be adjusted. The issue can be very visible when `TextField.textAlign` is set to `TextAlign.center` (video using the Android emulator):

https://user-images.githubusercontent.com/840911/228870859-6f6707b6-0b20-4701-9a5a-2eb921dff4f9.mp4

<details><summary>Code sample for the repro</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final TextEditingController textController = TextEditingController();

  MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Row(children: [
            SizedBox(
                width: 60,
                child: TextField(
                  controller: textController,
                  textAlign: TextAlign.center,
                )),
            TextButton(
              child: const Text("Reset text", style: TextStyle(color: Colors.red)),
              onPressed: () {
                textController.text = "0";
              },
            ),
          ]),
        ),
      ),
    );
  }
}

```
</details> 

## Implementation

AFAIK, there are several ways to fix this issue:
1. Not showing the caret when the selection is invalid. This is described in https://github.com/flutter/flutter/issues/79495. Unfortunately a PR for it was reverted (see https://github.com/flutter/flutter/pull/79607) due to a Google internal test failure.

2. Changing the selection to a valid one when TextController selection is invalid and the field is focused. this is the solution implemented in this PR. It breaks several tests which expect that the selection stays invalid.

3. Adding an assert to throw a detailed error message. The impact on existing tests will probably be worth than with solution 2 because for some of these tests It might be difficult to make them complied with this new requirement (for solution 2, tests can be updated by updating some `expect` calls).

## Related Issue

Fixes https://github.com/flutter/flutter/issues/120631

## Tests

Adds 1 test.
Will need to update several existing tests if becoming a real PR.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -15444,6 +15444,64 @@ testWidgets('Floating cursor ending with selection', (WidgetTester tester) async
...
+          ? TextSelection(
+              baseOffset: 0,
+              extentOffset: controller.text.length,
+            )
+          : TextSelection.collapsed(
+              offset: controller.text.length,
+            ),
+      );
+
+      // Update text with an invalid selection.
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:15488]: This comment isn't exactly what you're doing, is it old?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -3727,6 +3727,12 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     _updateRemoteEditingValueIfNeeded();
     _startOrStopCursorTimerIfNeeded();
     _updateOrDisposeSelectionOverlayIfNeeded();
+    if (_hasFocus && !_value.selection.isValid) {
+      // If this field is focused and the selection is invalid, place the cursor at
+      // the end. Does not rely on _handleFocusChanged because it makes selection
+      // handles visible on Android.
+      widget.controller.selection = TextSelection.collapsed(offset: _value.text.length);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3734]: This seems reasonable to me.  There have been some problems with invalid selection.  The engine often will set the selection to `-1, -1`, to mean "no selection" (and elsewhere, sometimes a `null` selection is used to mean no selection).  If the field is focused though, it makes sense to set the cursor to the end of the field as an improvement on those kinds of bugs.

**Review by justinmc — COMMENTED** [review]
Thanks for fixing this!  I say do it and go ahead with updating the failing tests.  It looks like there are only 2 failing in the framework tests check?

I'll also run the Google tests on this.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/widgets/editable_text_test.dart:15488]: I can make this comment more self explanatory, but it was done on purpose because `TextEditingController.test` setter explicitly set the selection offset to -1 (which is the root of the issue addressed in this PR): https://github.com/flutter/flutter/blob/f98499f9bbd186b2007c80898b57b5626be84785/packages/flutter/lib/src/widgets/editable_text.dart#L224-L230

Because `TextEditingController.test` is a public API, I did not focus on trying to change its implementation as it will  probably be a breaking change and also because there might be no simple fix that would work in all cases. What can be done at the `TextEditingController.test` level is probably to enhance its documentation to discourage its use and to recommand using `TextEditingController.value` instead.

While writing this, I wonder if we can add a method to `TextEditingController`, with a String parameter, which will set the text using the given value AND set the selection collapsed at the end of the text?

**Comment by bleroux** [comment]
> Thanks for fixing this! I say do it and go ahead with updating the failing tests. It looks like there are only 2 failing in the framework tests check?
> 

I see a lot more tests failures: 22 test failures locally :sweat_smile: 
I will try to fix them so we can discuss in detail if it makes sense to update these tests.

**Comment by bleroux** [comment]
@justinmc 
I updated failing tests. One choice was to replace most of `TextController.text` setter usage. With this PR, the selection won't be invalid but I think it is better to promote `TextController.value` instead. 
I commented out one test in `editable_text_shortcuts_test.dart`because it would be obsoleted by this PR. I don't know if removing a test is ok?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3706,6 +3706,15 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   }
 
   void _didChangeTextEditingValue() {
+    if (_hasFocus && !_value.selection.isValid) {
+      // If this field is focused and the selection is invalid, place the cursor at
+      // the end. Does not rely on _handleFocusChanged because it makes selection
+      // handles visible on Android.
+      // Unregister as a listener to the text controller while making the change.
+      widget.controller.removeListener(_didChangeTextEditingValue);
+      widget.controller.selection = _adjustedSelectionWhenFocused()!;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3715]: I find it a little strange that _adjustedSelectionWhenFocused returns a nullable value and we use `!` here.  Like you have to have knowledge about the `if` statement above and the internals of _adjustedSelectionWhenFocused in order to use that `!`.

I can't think of a better way to do it though. If nothing jumps out at you as a way to improve that, I say don't worry about it and leave it as-is.

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -6503,8 +6503,8 @@ void main() {
     variant: KeySimulatorTransitModeVariant.all()
   );
 
-  // Regressing test for https://github.com/flutter/flutter/issues/78219
-  testWidgets('Paste does not crash when the section is inValid', (WidgetTester tester) async {
+  // Regression test for https://github.com/flutter/flutter/issues/78219
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:6506]: Good catch 🔎

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 5]
```diff
@@ -90,33 +90,37 @@ void main() {
     );
   }
 
+  // Should we remove this test, because if this PR is approved it won't be possible
+  // to have an invalid selection for the controller if it is attached to a focused
+  // TextField.
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:95]: I think it's fine to delete the whole test!  Making a bug impossible is even better than having a test to catch it.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_test.dart]: Thanks 👍 .  I've shied away from adding new methods to TextEditingController because it's used so widely.  I think we do need a better place to put typical text editing operations, though.

**Review by justinmc — APPROVED** [review]
LGTM after you delete that test 👍

**Comment by justinmc** [comment]
CC @Renzo-Olivares Can you run these Google tests locally and see if they pass?

**Comment by ebadta81** [comment]
Great job guys. I tested this on my test project, it is working fine.
