### PR TITLE
Change GenerateFilledArcStrip to use non-overlapping triangles

### LINKED ISSUE #178839: [Impeller] Filled arcs with transparent colors have incorrect colors on iOS and macOS
### Steps to reproduce

Draw a filled arc with a transparent color on iOS and macOS with Impeller enabled

### Expected results

Image

### Actual results

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math' as math show pi;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: CustomPaint(painter: TestPainter()),
    );
  }
}

class TestPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawArc(
      Rect.fromCircle(center: size.center(Offset.zero), radius: 100),
      0,
      1.5 * math.pi,
      true,
      Paint()
        ..color = Colors.blue.withAlpha(127)
        ..style = PaintingStyle.fill,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

See above

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by b-luk**
Change GenerateFilledArcStrip to use alternating origin and edge vertices instead of using a corrugated triangle fan

Fixes #178839

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by flar — COMMENTED** [review]
The implementation looks good!

File: engine/src/flutter/impeller/tessellator/tessellator_unittests.cc [hunk 1]
```diff
@@ -302,6 +303,82 @@ TEST(TessellatorTest, StrokedCircleTessellationVertices) {
   test(Matrix::MakeScale({0.002, 0.002, 0.0}), {}, 1000.0, 10.0);
 }
 
+TEST(TessellatorTest, FilledArcStripTessellationVertices) {
+  auto tessellator = std::make_shared<Tessellator>();
```
Comment (flar) [inline engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: Usually `Tessellator tessellator;` works fine in unit tests...

File: engine/src/flutter/impeller/tessellator/tessellator_unittests.cc [hunk 2]
```diff
@@ -302,6 +303,82 @@ TEST(TessellatorTest, StrokedCircleTessellationVertices) {
...
+
+  auto test = [&tessellator](const Matrix& transform, const Arc& arc) {
+    auto generator = tessellator->FilledArc(transform, arc,
```
Comment (flar) [inline engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: I think this change is probably best suited for a Playground test. The problem is ensuring that we run it on at least one platform that doesn't support triangle fans. Is that possible?

Comment (flar) [reply engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: Also, we could iterate the triangles and test for overlapping. In this case all we need to test is whether any triangle contains a vertex from the list of vertices and that should prove the point (it would be interesting to run it on the older code that generated overlappy triangles to see if it triggers).

**Review by flar — CHANGES_REQUESTED** [review]

File: engine/src/flutter/impeller/tessellator/tessellator_unittests.cc (hunk 2 above)
Comment (b-luk) [reply engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: This test tests the fidelity of arc vertices in a similar way to all the other tests in this file testing vertices for other geometries. So for consistency I'll keep it here as is.

Based on your suggestion, I added a new playground/golden test for rendering translucent filled arcs. I added it in `aids_dl_basic_unittests` next to other arc rendering tests. I'm not completely sure on our infra and what platforms or devices these tests run in. But I think the Metal version that runs doesn't support triangle fans.

Here are test screenshots for this new test

Before:
before

After:
after

As for testing the triangles for overlapping coverage: as per our discussions, you're working on a PR which will add a new method for testing whether a point is contained inside a triangle. After this method is added, we may want to use it to test for overlapping triangles in this test as well as all the other tessellation unit tests.

File: engine/src/flutter/impeller/tessellator/tessellator_unittests.cc (hunk 1 above)
Comment (b-luk) [reply engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: Done. Changed it to `Tessellator tessellator;`.

I had originally copied this line from the other tests in this file. For consistency, I updated all the other instances in this file too.

File: engine/src/flutter/impeller/tessellator/tessellator_unittests.cc (hunk 2 above)
Comment (flar) [reply engine/src/flutter/impeller/tessellator/tessellator_unittests.cc]: The new filled arc test looks good and would have caught this issue earlier.

**Review by flar — APPROVED** [review]
LGTM
