### PR TITLE
Fix Material 3 Scrollable `TabBar`

### LINKED ISSUE #117722: Material 3 `TabBar` does not take full width when `isScrollable: true`
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

The bottom divider of the `TabBar` taking the full width available

**Actual results:** 

The `TabBar` taking minimum possible width.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with SingleTickerProviderStateMixin {
  late TabController controller;

  final tabs = ['Tab 1', 'Tab 2', 'Tab 3'];

  @override
  void initState() {
    super.initState();
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: controller,
            tabs: tabs.map((name) => Tab(text: name)).toList(),
            isScrollable: true,
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: tabs.map((name) => Center(child: Text(name))).toList(),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/flutter/flutter/files/10313296/logs.txt)

```
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.19043.2075], locale en-US)
    • Flutter version 3.7.0-1.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (8 days ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)  
    • Android SDK at C:\Users\mohamed.haisham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java        
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)     
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community    
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\mohamed.haisham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fix https://github.com/flutter/flutter/issues/117722

### Description
1. Fix the divider doesn't stretch to take all the available width in the scrollable tab bar in M3
2. Add `dividerHeight` property.
3. Update the default tab alignment for the scrollable tab bar to match the specs (this is backward compatible for M2 with the new `tabAlignment` property).

### Bug (default tab alignment)

Screenshot 2023-05-05 at 19 04 40

### Fix (default tab alignment)

Screenshot 2023-05-05 at 19 04 15

### Code sample

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [TabBar].

void main() => runApp(const TabBarApp());

class TabBarApp extends StatelessWidget {
  const TabBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        //  tabBarTheme: const TabBarTheme(tabAlignment: TabAlignment.start),
          useMaterial3: true,
      ),
      home: const TabBarExample(),
    );
  }
}

class TabBarExample extends StatefulWidget {
  const TabBarExample({super.key});

  @override
  State<TabBarExample> createState() => _TabBarExampleState();
}

class _TabBarExampleState extends State<TabBarExample> {
  bool rtl = false;

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      initialIndex: 1,
      length: 3,
      child: Directionality(
        textDirection:  rtl ? TextDirection.rtl : TextDirection.ltr,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('TabBar Sample'),
          ),
          body: const Column(
            children: <Widget>[
              Text('Scrollable-TabAlignment.start'),
              TabBar(
                isScrollable: true,
                tabAlignment: TabAlignment.start,
                tabs: <Widget>[
                  Tab(
                    icon: Icon(Icons.cloud_outlined),
                  ),
                  Tab(
                    icon: Icon(Icons.beach_access_sharp),
                  ),
                  Tab(
                    icon: Icon(Icons.brightness_5_sharp),
                  ),
                ],
              ),
              Text('Scrollable-TabAlignment.startOffset'),
              TabBar(
                isScrollable: true,
                tabAlignment: TabAlignment.startOffset,
                tabs: <Widget>[
                  Tab(
                    icon: Icon(Icons.cloud_outlined),
                  ),
                  Tab(
                    icon: Icon(Icons.beach_access_sharp),
                  ),
                  Tab(
                    icon: Icon(Icons.brightness_5_sharp),
                  ),
                ],
              ),
              Text('Scrollable-TabAlignment.center'),
              TabBar(
                isScrollable: true,
                tabAlignment: TabAlignment.center,
                tabs: <Widget>[
                  Tab(
                    icon: Icon(Icons.cloud_outlined),
                  ),
                  Tab(
                    icon: Icon(Icons.beach_access_sharp),
                  ),
                  Tab(
                    icon: Icon(Icons.brightness_5_sharp),
                  ),
                ],
              ),
              Spacer(),
              Text('Non-scrollable-TabAlignment.fill'),
              TabBar(
                tabAlignment: TabAlignment.fill,
                tabs: <Widget>[
                  Tab(
                    icon: Icon(Icons.cloud_outlined),
                  ),
                  Tab(
                    icon: Icon(Icons.beach_access_sharp),
                  ),
                  Tab(
                    icon: Icon(Icons.brightness_5_sharp),
                  ),
                ],
              ),
              Text('Non-scrollable-TabAlignment.center'),
              TabBar(
                tabAlignment: TabAlignment.center,
                tabs: <Widget>[
                  Tab(
                    icon: Icon(Icons.cloud_outlined),
                  ),
                  Tab(
                    icon: Icon(Icons.beach_access_sharp),
                  ),
                  Tab(
                    icon: Icon(Icons.brightness_5_sharp),
                  ),
                ],
              ),
              Spacer(),
            ],
          ),
          floatingActionButton: FloatingActionButton.extended(
            onPressed: () {
              setState(() {
                rtl = !rtl;
              });
            },
            label: const Text('Switch Direction'),
            icon: const Icon(Icons.swap_horiz),
          ),
        ),
      ),
    );
  }
}
``` 
	
</details>

Screenshot 2023-06-06 at 18 06 12

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Looks like there are a bunch o failing checks currently, is that because it is waiting on https://github.com/flutter/flutter/pull/125883?

**Comment by TahaTesser** [comment]
> Looks like there are a bunch o failing checks currently, is that because it is waiting on #125883?

Yep, this is not expected to be clear until https://github.com/flutter/flutter/pull/125883 is merged. I've split this and tested it locally.

File: packages/flutter/test/material/tabs_test.dart [hunk 1]
```diff
@@ -3301,8 +3300,9 @@ void main() {
               children: <TestSemantics>[
                 TestSemantics(
                     id: 3,
-                    rect: TestSemantics.fullScreen,
+                    rect: const Rect.fromLTRB(0.0, 0.0, 232.0, 48.0),
                     flags: <SemanticsFlag>[SemanticsFlag.hasImplicitScrolling],
+                    transform: Matrix4.translationValues(0.0, 276.0, 0.0),
```
Comment (TahaTesser) [inline packages/flutter/test/material/tabs_test.dart:3305]: This semantic test is expected to be updated because this PR wraps tabs and tab ndicator in a `Stack` widget (divider), which updates the layout to be within the `Stack`.


### Before
| Indicator is aligned with the tab | Inspector view |
| --------------- | --------------- |
|  |  |



| Indicator is aligned with the tab after introducing the `Stack` Widget |  Inspector view |
| --------------- | --------------- |
|  |  |

File: dev/tools/gen_defaults/lib/tabs_template.dart [hunk 2]
```diff
@@ -71,7 +74,7 @@ class _${blockName}PrimaryDefaultsM3 extends TabBarTheme {
   InteractiveInkFeatureFactory? get splashFactory => Theme.of(context).splashFactory;
 
   @override
-  TabAlignment? get tabAlignment => isScrollable ? TabAlignment.start : TabAlignment.fill;
+  TabAlignment? get tabAlignment => isScrollable ? TabAlignment.startOffset : TabAlignment.fill;
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/tabs_template.dart:77]: Use the newly added tab alignment to match the material specs for the scrollable tab bar. 


Screenshot 2023-05-05 at 18 54 00

File: packages/flutter/lib/src/material/tabs.dart [hunk 3]
```diff
@@ -1634,6 +1637,28 @@ class _TabBarState extends State<TabBar> {
       );
     }
 
+    final AlignmentGeometry effectiveAlignment = effectiveTabAlignment == TabAlignment.center
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:1640]: This should be a switch so the analyzer catches this case if TabAlignment ever changes.
Thanks to Dart 3 though, it can be super fun like:

```dart
final AlignmentGeometry effectiveAlignment = switch (effectiveTabAlignment) {
      TabAlignment.center => Alignment.center,
      TabAlignment.start || TabAlignment.startOffset || TabAlignment.fill => AlignmentDirectional.centerStart,
    };
```

File: dev/tools/gen_defaults/lib/tabs_template.dart (hunk 2 above)
Comment (Piinks) [reply dev/tools/gen_defaults/lib/tabs_template.dart:77]: I think we should run some extra testing on this to ensure it isn't reverted later. 👍

**Review by Piinks — APPROVED** [review]
LGTM with the switch statement nit outstanding. I will fire off some extra internal tests, hold off on merging right away. :)

File: packages/flutter/lib/src/material/tabs.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/tabs.dart:1640]: This looks cool

Comment (Piinks) [reply packages/flutter/lib/src/material/tabs.dart]: Right? I like it.

**Comment by Piinks** [comment]
I am working on migrating customers here. For now, can you hold off on pushing any commits? The Google tests throw out the old result when a new commit is pushed. 😋

**Comment by Piinks** [comment]
In the meantime, I think a short migration guide in flutter/website is warranted here. When folks upgrade to this and the tab bar moves, it may not be easy to figure out why or how to restore it.

**Comment by TahaTesser** [comment]
> > In the meantime, I think a short migration guide in flutter/website is warranted here. When folks upgrade to this and the tab bar moves, it may not be easy to figure out why or how to restore it.
> 
> Great idea, I'll work on this.

Filed a PR for migration guide https://github.com/flutter/website/pull/8700

**Comment by Piinks** [comment]
Thanks again for your patience here! I am still working through the customer tests. I found one case where it looks like the indicator and divider are not properly aligned when updated with this PR. I am still looking into why, but wanted to chare in case anything jumped out at you. I'll continue investigating.

I have omitted the labels since it is an internal customer. Ignore the horizontal alignment, the images here are cropped. It is the little bit of vertical spacing that is the issue:

This is the expected behavior:

Screenshot 2023-05-23 at 12 27 39 PM

This PR causes this:

Screenshot 2023-05-23 at 12 27 44 PM

**Comment by Piinks** [comment]
If you are up for it, splitting this up further may help. There are hundreds of image tests and some of them are affected by the divider height change, some by the tab alignment, it makes it more challenging to sort through them all. Just came across another odd case:

Expected:

Screenshot 2023-05-23 at 12 32 15 PM

With this PR:

Screenshot 2023-05-23 at 12 32 20 PM

**Comment by TahaTesser** [comment]
@Piinks 
Thank you for the details, I really appreciate it. The change is small but tricky to verify if it is fixing the problems that you shared. 

Is it possible for you to share the tab bar layout code from [this test](https://github.com/flutter/flutter/pull/125974#issuecomment-1559873470) above so I can test my fix in the same conditions? 
 It will be tremendously helpful for me to test rather than guess what might be going wrong there.

**Comment by Piinks** [comment]
Ok, so for that specific test, it looks like the customer has a custom AppBar and a custom TabBar inside of that.
But, it looks like this might be what you are looking for, the custom TabBar is this:

```dart
Stack(
    alignment: Alignment.bottomCenter,
    children: [
      Divider(height: 0),
      TabBar(
        controller: tabController,
        labelPadding: EdgeInsets.zero,
        tabs: tabs,
        onTap: (tappedTabIndex) {
          //...
        },
      ),
    ],
  );
```

Does this help? If not I can dig further, just let me know! :)

**Comment by Piinks** [comment]
Hmm, still trying to get a reproduction here. The fact that the customer is using a custom app bar and a custom tab bar is making it a bit difficult. Just wanted to let you know I was still looking into this.

**Comment by TahaTesser** [comment]
> Hmm, still trying to get a reproduction here. The fact that the customer is using a custom app bar and a custom tab bar is making it a bit difficult. Just wanted to let you know I was still looking into this.

Appreciate it!

**Comment by TahaTesser** [comment]
Friendly ping

**Comment by Piinks** [comment]
I have tried a bunch of different ways to try to repro the customer case, but have not been successful. I am waiting to hear back from them to see if we can remove the strange extra Divider, because it seems redundant on top of the divider that is already rendered by the TabBar.

@TahaTesser you mentioned you had an alternative solution? We could also try that and see if it resolves the issue.

@HansMuller may also have a recommendation here since we cannot reproduce the customer failure.

**Comment by TahaTesser** [comment]
@Piinks 
First of all, I really appreciate your time on this. 

Based on the screenshots you shared, my best guess for the problem is constrained, so I went to the safest route and updated the current divider to be drawn for the whole width. This way layout is not modified, it's very close to the current behavior on the master. (current tab indicator is also drawn like this, it's not constrained as well)

Looking forward to knowing if this safer approach is breaking customer tests or not.

I also added a complete code sample in the description for anyone running into this PR.

**Comment by Piinks** [comment]
Thank you! I'll run this through and see if it still occurs. Much appreciated as always!

**Comment by Piinks** [comment]
Update - all customers should be migrated now. I am rerunning the tests and will need to go through all the images again just to make sure there are no more unexpected ones.

**Comment by Piinks** [comment]
This is safe to land now, but the google testing shard is stuck. I filed a bug internally. Rebasing to see if that clears it up.

**Review by Piinks — COMMENTED** [review]
Ah no I rebased and now there are some analysis issues, can you take a look?

**Comment by TahaTesser** [comment]
> Ah no I rebased and now there are some analysis issues, can you take a look?

Taking a look.

**Comment by Piinks** [comment]
Hmm looks like we have some new test failures here

**Comment by TahaTesser** [comment]
> Hmm looks like we have some new test failures here

That's weird. I can reproduce this locally too. Pretty sure we had most of it green before, didn't we?
I'll take a closer look in the morning.

**Comment by TahaTesser** [comment]
@Piinks 
Mystery solved! 

https://github.com/flutter/flutter/pull/128725 recently updated the `useMaterial3` flag in the boilerplate code to be nullable in the material library for M2. 
I just had to explicitly enable `theme.useMaterial3`  for the M3 tests in this PR.

**Comment by TahaTesser** [comment]
`Linux flutter_plugins ` is failing on most PRs right now.

```console

[31mThe following packages had errors:[0m
[31m  file_selector/file_selector[0m
[31m  file_selector_linux[0m
[31m  file_selector_macos[0m
[31m  file_selector_windows[0m
[31mSee above for full details.[0m
```

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/tabs.dart [hunk 4]
```diff
@@ -1269,8 +1284,10 @@ class _TabBarState extends State<TabBar> {
       indicatorPadding: widget.indicatorPadding,
       tabKeys: _tabKeys,
       old: _indicatorPainter,
-      dividerColor: theme.useMaterial3 ? widget.dividerColor ?? tabBarTheme.dividerColor ?? _defaults.dividerColor : null,
       labelPaddings: _labelPaddings,
+      dividerColor: theme.useMaterial3 ? widget.dividerColor ?? tabBarTheme.dividerColor ?? _defaults.dividerColor : null,
+      dividerHeight: theme.useMaterial3 ? widget.dividerHeight ?? tabBarTheme.dividerHeight ?? _defaults.dividerHeight : null,
+      width: MediaQuery.sizeOf(context).width,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:1290]: @TahaTesser do you recall why this changed? I do not remember since this PR has had so much back and forth, I am looking though..

Comment (TahaTesser) [reply packages/flutter/lib/src/material/tabs.dart:1290]: You mean the `width`? This what divider painters uses to draw the divider beyond the tabs without changing the layout.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/tabs.dart:1290]: Previously divider was only drawn with in the tabs, this caused this issue. https://github.com/flutter/flutter/issues/117722

Comment (Piinks) [reply packages/flutter/lib/src/material/tabs.dart:1290]: Right right. Thank you for the reference! I could not recall. We're reviewing all of the screenshots one last time and there was a weird one where the customer mocked up a phone outline in the test and the divider extended out beyond it. I think it is an unintended issue of the test, not this change. No worries. :)

Comment (Piinks) [reply packages/flutter/lib/src/material/tabs.dart:1290]: Ok so sad news, I am going to revert this. Unfortunately this is not uncommon when there are over a thousand screenshots. 😢 

I misunderstood what an image was capturing. The width here actually causes an issue when the TabBar is contained within a ConstrainedBox, the divider extends beyond it.

The customer test was not showing a mocked up phone, but rather a floating box with the content it was floating over omitted from the test case.

I've put together a repro here:

Screenshot 2023-06-22 at 5 28 26 PM


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {

  const MyHomePage({ super.key });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTabController(
        length: 2,
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 360),
            child: ColoredBox(
              color: Colors.grey[200]!,
              child: const TabBar.secondary(
                tabAlignment: TabAlignment.start,
                isScrollable: true,
                tabs: [
                  Tab(text: 'Test 1'),
                  Tab(text: 'Test 2'),
                ],
              ),
            )
          ),
        ),
      ),
    );
  }
}
```
