### PR TITLE
RefreshIndicator should not be shown when overscroll occurs due to inertia

### LINKED ISSUE #9690: Provide a way to allow or disallow pull to refresh when the scrollable does not scroll to the top on android
The refresh indicator doesn't show up when scrolling up. In order for the refresh indicator to show, I noticed that the list has to be at the top, before scroll up occurs. I'll be recording the video tonight, and it may or may not show up. I will provide a link to it when finished, with a more complete source writeup. 

## Steps to Reproduce

1. With the refresh indicator wired up this way
```dart
/// place: "/todos"
class TodosPage extends StatefulWidget {
  TodosPage({Key key}) : super(key: key);

  static const String routeName = "/todos";

  @override
  _TodosPageState createState() => new _TodosPageState();
}

class _TodosPageState extends State<TodosPage> {
  final GlobalKey<RefreshIndicatorState> _refreshIndicatorKey = new GlobalKey<
      RefreshIndicatorState>();

  @override
  Widget build(BuildContext context) {
    return new Theme(
      data: _themeData,
      child: new Scaffold(
        appBar: new AppBar(title: new Text("My Todos")),
        body: new RefreshIndicator(
          key: _refreshIndicatorKey,
          child: new ListView.builder(
            itemBuilder: _itemBuilder,
          ),
          onRefresh: _onRefresh,
        ),
      ),
    );
  }

  // simulate a http request
  Future<Null> _onRefresh() {
    Completer<Null> completer = new Completer<Null>();

    new Timer(new Duration(seconds: 3), () {
      print("timer complete");
      completer.complete();
    });

    return completer.future;
  }

  Widget _itemBuilder(BuildContext context, int index) {
    Todo todo = new Todo(false, "Todo $index");
    return new TodoItemWidget(todo: todo);
  }
}
```
2. Scroll down some, then swipe up to activate refresh indicator

- If the list is part way down, the refresh indicator can't be pulled
- If the list is all the way to top, the refresh indicator can be pulled down

Notice the behavior here:
refreshindicatorbug

## Logs

```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision a4ba761bea (19 hours ago), 2017-04-28 16:01:14 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • iPhone SE • 1C15BC7F-DA25-4E71-B479-B601B549CAA0 • ios • iOS 10.3 (simulator)

Process finished with exit code 0

```

### LINKED ISSUE #71936: Regression: Top overflow is not working anymore since #71303
Since #71303 is merged, when you scroll up inside a refreshindicator sub widget, there is no overscroll effect anymore. 
If you scroll up with momentum you should get an overscroll effect, but it does not happen anymore.

The overscroll effect should only be disabled, if you reached the top and continue to swipe.

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

#71303 let the `RefreshIndicator` can be pulled out from the non-zero scroll position no matter the overscroll occurs due to drag or inertia.

This change cancel shows the `RefreshIndicator` when overscroll occurs due to inertia. I think this is intended to make it so that someone who is just scrolling to the top of your list doesn't accidentally start a refresh.

After this change, The indicator will be pulled out in two cases,
    // 1, Begin drag when the scrollable widget at the edge with zero scroll position.
    // 2, Keep drag before overscroll occurs when the scrollable widget has
    //    a non-zero scroll position(do not release finger before overscroll).

This behavior is consistent with the Android native app(Test with Microsoft Outlook APP).

@Hixie suggested that this behavior can opt-in and tracked by #9690 

## Related Issues

Fixes #71936
Fixes #9690

## Tests

I added the following tests:

See files.

### CODE REVIEW

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 1]
```diff
@@ -215,12 +215,21 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
+  bool _shouldStart(ScrollNotification notification) {
+    // The indicator will be pulled out in two cases,
+    // 1, Begin drag when the scrollable widget at the edge with zero scroll position.
+    // 2, Keep drag before overscroll occurs when the scrollable widget has
+    //    a non-zero scroll position(do not release finger before overscroll).
+    return (notification is ScrollStartNotification || (notification is ScrollUpdateNotification && notification.dragDetails != null))
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:223]: Since you have refactor out this check, can you also implement the opt in behavior as well? We can have an widget parameter to control whether it can be pull out if it drag from non zero scroll offset?

Comment (xu-baolin) [reply packages/flutter/lib/src/material/refresh_indicator.dart:223]: OK, BUT I still want to talk to @Hixie  about this behavior. I want to know what he is thinking right now. I don't think the refresh indicator is easily pulled out by misoperation.It must continue to pull down a certain distance before it can be refreshed. What do you think,?

File: packages/flutter/test/material/refresh_indicator_test.dart [hunk 2]
```diff
@@ -501,7 +501,7 @@ void main() {
     );
   });
 
-  testWidgets('Top RefreshIndicator showed when dragging from non-zero scroll position', (WidgetTester tester) async {
+  testWidgets('Top RefreshIndicator be shown when dragging from non-zero scroll position', (WidgetTester tester) async {
```
Comment (Hixie) [inline packages/flutter/test/material/refresh_indicator_test.dart:504]: neither "showed" nor "be shown" are really correct grammar here, I recommend "shows". :-)

Comment (Hixie) [reply packages/flutter/test/material/refresh_indicator_test.dart:504]: (or "is shown")

Comment (Hixie) [reply packages/flutter/test/material/refresh_indicator_test.dart:504]: (or "should be shown")

Comment (xu-baolin) [reply packages/flutter/test/material/refresh_indicator_test.dart]: Done.
@Hixie Hi, so what's your opinion on this https://github.com/flutter/flutter/issues/9690#issuecomment-298246306 now?

Comment (chunhtai) [reply packages/flutter/test/material/refresh_indicator_test.dart]: copied from discord chat
```
looks like the material design spec doesn't say one way or the other... it seems weird to me to allow pull to refresh when you're just scrolling, since pull to refresh can cost money (it does network traffic) and generally be disruptive. I would not expect it to happen when you're just scrolling, it should be specifically when you're at the top already. I don't have an objection to a flag to enable it when you're just scrolling if that's a common request.
```

I think this is a valid argument, and I am also agree we should have flag to toggle it on and off.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 3]
```diff
@@ -47,6 +47,17 @@ enum _RefreshIndicatorMode {
   canceled, // Animating the indicator's fade-out after not arming.
 }
 
+/// Used to configure the [RefreshIndicator] trigger mode.
+enum RefreshIndicatorTriggerMode {
+  /// The indicator can trigger when the child's [Scrollable] descendant overscrolls
+  /// by drag(not inertia), regardless of whether its initial scroll position is on the edge or not.
+  loose,
+
+  /// The indicator can only trigger when the child's [Scrollable] descendant overscrolls
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:56]: suggestion: The indicator can only be triggered if the [Scrollable] is at the edge when the drag starts.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 4]
```diff
@@ -47,6 +47,17 @@ enum _RefreshIndicatorMode {
   canceled, // Animating the indicator's fade-out after not arming.
 }
 
+/// Used to configure the [RefreshIndicator] trigger mode.
+enum RefreshIndicatorTriggerMode {
+  /// The indicator can trigger when the child's [Scrollable] descendant overscrolls
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:52]: suggestion: The indicator can be triggered regardless of the scroll position of the [Scrollable] when the drag starts.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 5]
```diff
@@ -47,6 +47,17 @@ enum _RefreshIndicatorMode {
   canceled, // Animating the indicator's fade-out after not arming.
 }
 
+/// Used to configure the [RefreshIndicator] trigger mode.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:50]: Used to configure how [RefreshIndicator] can be triggered.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 6]
```diff
@@ -47,6 +47,17 @@ enum _RefreshIndicatorMode {
...
+enum RefreshIndicatorTriggerMode {
+  /// The indicator can trigger when the child's [Scrollable] descendant overscrolls
+  /// by drag(not inertia), regardless of whether its initial scroll position is on the edge or not.
+  loose,
+
+  /// The indicator can only trigger when the child's [Scrollable] descendant overscrolls
+  /// by drag and its initial scroll position is on the edge.
+  strict,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:58]: strict sounds too generic. we should be specific.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 7]
```diff
@@ -160,6 +175,11 @@ class RefreshIndicator extends StatefulWidget {
   /// By default, the value of `strokeWidth` is 2.0 pixels.
   final double strokeWidth;
 
+  /// Defines `triggerMode` for `RefreshIndicator`.
+  ///
+  /// By default, the value of `triggerMode` is [RefreshIndicatorTriggerMode.strict].
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:180]: suggestion: Defaults to [RefreshIndicatorTriggerMode.strict]

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 8]
```diff
@@ -160,6 +175,11 @@ class RefreshIndicator extends StatefulWidget {
   /// By default, the value of `strokeWidth` is 2.0 pixels.
   final double strokeWidth;
 
+  /// Defines `triggerMode` for `RefreshIndicator`.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:178]: Defines how this [RefreshIndicator] can be triggered when users overscroll.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 9]
```diff
@@ -215,12 +235,21 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
+  bool _shouldStart(ScrollNotification notification) {
+    // The indicator will be pulled out in two cases depend on [widget.triggerMode],
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:239]: this comment should be put to the doc string of
```
final RefreshIndicatorTriggerMode triggerMode;
```
instead.

File: packages/flutter/lib/src/material/refresh_indicator.dart (hunk 6 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/refresh_indicator.dart:58]: Do you have any suggestions for this name？ ：）

Comment (chunhtai) [reply packages/flutter/lib/src/material/refresh_indicator.dart:58]: I am not an expert on this. here is my suggestion.

strict :`onEdge`, `dragStartsAtScrollableEdge`
loose: `anywhere`, `dragStartsAtAnyWhere`

**Review by chunhtai — APPROVED** [review]
LGTM, modulo nits

File: packages/flutter/test/material/refresh_indicator_test.dart [hunk 10]
```diff
@@ -501,12 +501,13 @@ void main() {
     );
   });
 
-  testWidgets('Top RefreshIndicator showed when dragging from non-zero scroll position', (WidgetTester tester) async {
+  testWidgets('Top RefreshIndicator(loose mode) should be shown when dragging from non-zero scroll position', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/material/refresh_indicator_test.dart:504]: loose mode -> onEdge mode

Comment (chunhtai) [reply packages/flutter/test/material/refresh_indicator_test.dart:504]: here and anywhere

File: packages/flutter/test/material/refresh_indicator_test.dart [hunk 11]
```diff
@@ -569,4 +571,110 @@ void main() {
...
+
+    // Release finger before reach the edge.
+    await tester.fling(find.text('X'), const Offset(0.0, 99.0), 1000.0);
+    await tester.pump();
+    await tester.pump(const Duration(seconds: 1)); // finish the scroll animation
+    await tester.pump(const Duration(seconds: 1)); // finish the indicator settle animation
+    expect(find.byType(RefreshProgressIndicator), findsNothing);
+  });
+
+  testWidgets('Top RefreshIndicator(strict mode) should not be shown when dragging from non-zero scroll position', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/material/refresh_indicator_test.dart:612]: anyWhere
