### PR TITLE
Fix race condition in protocol_discovery.dart

### LINKED ISSUE #10064: Waiting for observatory port to be available timeout exception
Trying to run any of the examples on android emulator results in a timeout exception. The application is successfully installed and it runs as expected. However, the port forwarding needed to access the observatory is never configured. This is only happening while using the emulator. 

I did some quick testing and the problem seems to be inside protocol_discovery.dart:

This exception is being thrown:
```
 /// The [Future] returned by this function will complete when the next service
51    /// Uri is found.                                                            
  1   Future<Uri> nextUri() async {                                                
  2     final Uri deviceUri = await _completer.future.timeout(                     
  3       const Duration(seconds: 60), onTimeout: () {                             
  4         throwToolExit('Timeout while attempting to retrieve Uri for $_serviceName');
  5       }                                                                        
  6     );     
```

The function receives the correct Uri and the assertions are passed, but the completer is being deallocated before informing the listeners. By commenting line 100 out, the issue is resolved.

```
95    void _located(Uri uri) {                                                     
96     assert(_completer != null);                                                
97     assert(!_completer.isCompleted);                                           
98                                                                                
99     _completer.complete(uri);                                                  
100     _completer = new Completer<Uri>();                                         
101   }    
```   
I also tried assigning the new completer in the future's whenComplete() instead, and it also fixed the problem. 

## Logs

```
[            ] Android SDK built for x86 startApp
[            ] /home/afgno/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true io.flutter.examples.hello_world/io.flutter.examples.hello_world.MainActivity
[     +318 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.examples.hello_world/.MainActivity (has extras) }
[            ] Waiting for observatory port to be available...
[   +60006 ms] Error waiting for a debug connection: Exception: Timeout while attempting to retrieve Uri for Observatory
[       +1 ms] Error launching application on Android SDK built for x86.
[       +6 ms] "flutter run" took 62,860ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:327)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#3      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///home/afgno/Code/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[     +252 ms] ensureAnalyticsSent: 250ms
[       +2 ms] exiting with code 2

```

# Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /home/afgno/Code/flutter
    • Framework revision 4b7a1912ee (3 hours ago), 2017-05-12 17:45:17 -0700
    • Engine revision bc8e3b5e72
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/afgno/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

### PR DESCRIPTION
**Pull request by tvolkert**
For some reaosn, when we discovered our URI, we were re-instantiating
the `Completer` instance variable whose future we listen to in `nextUri()`.
This led to a race between a caller calling `nextUri()` and us discovering
the URI. If we happened to discover our URI before a caller called
`nextUri()`, then they would be left waiting on a future from the newly
allocated `Completer` (which would never complete).

Fixes #10064

### CODE REVIEW

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 1]
```diff
@@ -95,8 +95,6 @@ class ProtocolDiscovery {
   void _located(Uri uri) {
     assert(_completer != null);
     assert(!_completer.isCompleted);
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: It's not clear what we want to do here. From digging through the git history, it looks like the create-new-instance-on-complete logic has been around for a while. I suspect it was from before we did a good job of just getting logs from the current session, and we could have multiple matches to service protocol urls. Asserting's probably not the right thing to do now - perhaps just complete the completer if `! isCompleted`, and log if it is?

**Comment by devoncarew** [comment]
lgtm, thought I'm not sure what he right behavior should be if we see a matching uri twice

**Comment by tvolkert** [comment]
I'm actually refactoring this class a lot - would have posted a newer version by now, but I'm wrestling with a very strange test failure that has to do with our use of `runZoned`.  Will ping once this is ready for another look.

**Comment by tvolkert** [comment]
Ok, ready for another look

File: packages/flutter_tools/test/protocol_discovery_test.dart [hunk 2]
```diff
@@ -13,74 +13,113 @@ import 'src/mocks.dart';
...
+        discoverer.cancel();
+        logReader.dispose();
+      });
+
+      testUsingContext('returns non-null uri future', () async {
+        initialize();
+        expect(discoverer.uri, isNotNull);
+      });
+
+      testUsingContext('discovers uri is logs already produced output', () async {
```
Comment (devoncarew) [inline packages/flutter_tools/test/protocol_discovery_test.dart]: sp: if

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 3]
```diff
@@ -84,19 +74,35 @@ class ProtocolDiscovery {
     if (index >= 0) {
       try {
         uri = Uri.parse(line.substring(index + prefix.length));
-      } catch (_) {
-        // Ignore errors.
+      } catch (error) {
+        _stopScrapingLogs();
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: Do we want to throw here or keep looking for a match?

**Comment by devoncarew** [comment]
lgtm

File: packages/flutter_tools/lib/src/protocol_discovery.dart (hunk 3 above)
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: My thought was that if we ever see "Observatory listening on http://" and can't parse the associated URI, it's most likely because something went wrong, and we should throw.

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 4]
```diff
@@ -281,10 +281,10 @@ class IOSDevice extends Device {
       final ProtocolDiscovery diagnosticDiscovery = new ProtocolDiscovery.diagnosticService(
         getLogReader(app: app), portForwarder: portForwarder, hostPort: debuggingOptions.diagnosticPort);
 
-      final Future<Uri> forwardObsUri = observatoryDiscovery.nextUri();
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/ios/devices.dart]: nit for the future (don't worry about fixing this now since you've already landed it): avoid abbreviations like "Obs" in "forwardObsUri".

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 5]
```diff
@@ -9,72 +9,62 @@ import 'base/port_scanner.dart';
 import 'device.dart';
 import 'globals.dart';
 
-/// Discover service protocol on a device
-/// and forward the service protocol device port to the host.
+/// Discovers a specific service protocol on a device, and forward the service
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: grammar nit: tense of "discovers" and "forward" don't match
