### PR TITLE
Fix error message for unbounded viewports

### LINKED ISSUE #78796: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1860 pos 16: 'constraints.hasBoundedHeight': is not true.
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. flutter run

**Expected results:** not sure exactly.

**Actual results:** Framework assertion failed, white screen.

<details>
  <summary>Logs</summary>

```
[ +131 ms] executing: sysctl hw.optional.arm64
[  +27 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[  +21 ms] executing: [/Users/elih/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] executing: [/Users/elih/dev/flutter/] git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[  +31 ms] Exit code 0 from: git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] 2.1.0-12.1.pre
[  +61 ms] executing: [/Users/elih/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/elih/dev/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [/Users/elih/dev/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +11 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H524
[  +73 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] executing: /Users/elih/Library/Android/sdk/platform-tools/adb devices -l
[  +16 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +255 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[   +4 ms] Xcode not found. Run 'flutter doctor' for more information.
[  +44 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] Multiple devices found:
[  +62 ms] macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
[        ] Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
[   +1 ms] [1]: macOS (macos)
[        ] [2]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
<I press '1'>
[+13506 ms] 1
[  +15 ms] Skipping pub get: version match.
[ +153 ms] Generating /Users/elih/dev/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +125 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +7 ms] Launching lib/main.dart on macOS in debug mode...
[   +6 ms] /Users/elih/dev/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/elih/dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/elih/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/T/flutter_tools.3TGGzX/flutter_tool.6D2Q3M/app.dill --packages /Users/elih/dev/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +80 ms] executing: [/Users/elih/dev/bug/macos/] xcrun xcodebuild -list -project Runner.xcodeproj
[  +15 ms] <- compile package:bug/main.dart
[+1408 ms] Information about project "Runner":
               Targets:
                   Runner
                   Flutter Assemble

               Build Configurations:
                   Debug
                   Release
                   Profile

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   Flutter Assemble
                   Runner
[   +3 ms] Building macOS application...
[   +3 ms] executing: /usr/bin/env xcrun xcodebuild -workspace /Users/elih/dev/bug/macos/Runner.xcworkspace -configuration Debug -scheme Runner -derivedDataPath /Users/elih/dev/bug/build/macos OBJROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex SYMROOT=/Users/elih/dev/bug/build/macos/Build/Products VERBOSE_SCRIPT_LOGGING=YES COMPILER_INDEX_STORE_ENABLE=NO
[ +867 ms] User defaults from command line:
[        ]     IDEDerivedDataPathOverride = /Users/elih/dev/bug/build/macos
[        ] Build settings from command line:
[        ]     COMPILER_INDEX_STORE_ENABLE = NO
[        ]     OBJROOT = /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     SYMROOT = /Users/elih/dev/bug/build/macos/Build/Products
[        ]     VERBOSE_SCRIPT_LOGGING = YES
[ +730 ms] note: Using new build system
[   +4 ms] note: Planning build
[  +92 ms] note: Constructing build description
[ +239 ms] WriteAuxiliaryFile /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-59fceedaf283a3e78036ad59e27d2f85-resolved.xcfilelist (in target 'Flutter Assemble' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     write-file /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-59fceedaf283a3e78036ad59e27d2f85-resolved.xcfilelist
[   +1 ms] WriteAuxiliaryFile /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build/OutputFileList-33CC111E2044C6BF0003C045-FlutterOutputs-b60a64e08287cf958c9f489ef2af025c-resolved.xcfilelist (in target 'Flutter Assemble' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     write-file /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build/OutputFileList-33CC111E2044C6BF0003C045-FlutterOutputs-b60a64e08287cf958c9f489ef2af025c-resolved.xcfilelist
[   +3 ms] PhaseScriptExecution Run\ Script /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh (in target 'Flutter Assemble' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     export ACTION=build
[        ]     export AD_HOC_CODE_SIGNING_ALLOWED=YES
[        ]     export ALTERNATE_GROUP=staff
[        ]     export ALTERNATE_MODE=u+w,go-w,a+rX
[        ]     export ALTERNATE_OWNER=elih
[        ]     export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
[        ]     export ALWAYS_SEARCH_USER_PATHS=NO
[        ]     export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
[        ]     export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
[        ]     export APPLE_INTERNAL_DIR=/AppleInternal
[        ]     export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
[        ]     export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
[        ]     export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
[        ]     export APPLICATION_EXTENSION_API_ONLY=NO
[        ]     export APPLY_RULES_IN_COPY_FILES=NO
[        ]     export APPLY_RULES_IN_COPY_HEADERS=NO
[        ]     export ARCHS=x86_64
[        ]     export ARCHS_STANDARD=x86_64
[        ]     export ARCHS_STANDARD_32_64_BIT="x86_64 i386"
[        ]     export ARCHS_STANDARD_32_BIT=i386
[        ]     export ARCHS_STANDARD_64_BIT=x86_64
[        ]     export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
[        ]     export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
[        ]     export BITCODE_GENERATION_MODE=marker
[        ]     export BUILD_ACTIVE_RESOURCES_ONLY=NO
[        ]     export BUILD_COMPONENTS="headers build"
[        ]     export BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export BUILD_LIBRARY_FOR_DISTRIBUTION=NO
[        ]     export BUILD_ROOT=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export BUILD_STYLE=
[        ]     export BUILD_VARIANTS=normal
[        ]     export BUILT_PRODUCTS_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export CACHE_ROOT=/var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
[        ]     export CCHROOT=/var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
[        ]     export CHMOD=/bin/chmod
[        ]     export CHOWN=/usr/sbin/chown
[        ]     export CLANG_ANALYZER_NONNULL=YES
[        ]     export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION=YES_AGGRESSIVE
[        ]     export CLANG_CXX_LANGUAGE_STANDARD=gnu++14
[        ]     export CLANG_CXX_LIBRARY=libc++
[        ]     export CLANG_ENABLE_MODULES=YES
[        ]     export CLANG_ENABLE_OBJC_ARC=YES
[        ]     export CLANG_MODULES_BUILD_SESSION_FILE=/Users/elih/dev/bug/build/macos/ModuleCache.noindex/Session.modulevalidation
[        ]     export CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY=YES
[        ]     export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
[        ]     export CLANG_WARN_BOOL_CONVERSION=YES
[        ]     export CLANG_WARN_COMMA=YES
[        ]     export CLANG_WARN_CONSTANT_CONVERSION=YES
[        ]     export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
[        ]     export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
[        ]     export CLANG_WARN_DOCUMENTATION_COMMENTS=YES
[        ]     export CLANG_WARN_EMPTY_BODY=YES
[        ]     export CLANG_WARN_ENUM_CONVERSION=YES
[        ]     export CLANG_WARN_INFINITE_RECURSION=YES
[        ]     export CLANG_WARN_INT_CONVERSION=YES
[        ]     export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
[        ]     export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
[        ]     export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
[        ]     export CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK=YES
[        ]     export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
[        ]     export CLANG_WARN_PRAGMA_PACK=YES
[        ]     export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
[        ]     export CLANG_WARN_STRICT_PROTOTYPES=YES
[        ]     export CLANG_WARN_SUSPICIOUS_MOVE=YES
[        ]     export CLANG_WARN_UNGUARDED_AVAILABILITY=YES_AGGRESSIVE
[        ]     export CLANG_WARN_UNREACHABLE_CODE=YES
[        ]     export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
[        ]     export CLASS_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/JavaClasses"
[        ]     export CLEAN_PRECOMPS=YES
[        ]     export CLONE_HEADERS=NO
[        ]     export COCOAPODS_PARALLEL_CODE_SIGN=true
[        ]     export CODESIGNING_FOLDER_PATH=/Users/elih/dev/bug/build/macos/Build/Products/Debug/
[        ]     export CODE_SIGNING_ALLOWED=YES
[        ]     export CODE_SIGN_IDENTITY=-
[        ]     export CODE_SIGN_IDENTITY_NO="Apple Development"
[        ]     export CODE_SIGN_IDENTITY_YES=-
[        ]     export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
[        ]     export CODE_SIGN_STYLE=Manual
[        ]     export COLOR_DIAGNOSTICS=NO
[        ]     export COMBINE_HIDPI_IMAGES=NO
[        ]     export COMPILER_INDEX_STORE_ENABLE=NO
[        ]     export COMPOSITE_SDK_DIRS=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/CompositeSDKs
[        ]     export COMPRESS_PNG_FILES=NO
[        ]     export CONFIGURATION=Debug
[        ]     export CONFIGURATION_BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export CONFIGURATION_TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug
[        ]     export COPYING_PRESERVES_HFS_DATA=NO
[        ]     export COPY_HEADERS_RUN_UNIFDEF=NO
[        ]     export COPY_PHASE_STRIP=NO
[        ]     export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
[        ]     export CP=/bin/cp
[        ]     export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
[        ]     export CURRENT_ARCH=undefined_arch
[        ]     export CURRENT_VARIANT=normal
[        ]     export DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
[        ]     export DART_OBFUSCATION=false
[        ]     export DEAD_CODE_STRIPPING=NO
[        ]     export DEBUGGING_SYMBOLS=YES
[        ]     export DEBUG_INFORMATION_FORMAT=dwarf
[        ]     export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
[        ]     export DEFAULT_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
[        ]     export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
[        ]     export DEFINES_MODULE=NO
[        ]     export DEPLOYMENT_LOCATION=NO
[        ]     export DEPLOYMENT_POSTPROCESSING=NO
[        ]     export DEPLOYMENT_TARGET_CLANG_ENV_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mmacosx-version-min
[        ]     export DEPLOYMENT_TARGET_LD_ENV_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_LD_FLAG_NAME=macosx_version_min
[        ]     export DEPLOYMENT_TARGET_SETTING_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_SUGGESTED_VALUES="10.6 10.7 10.8 10.9 10.10 10.11 10.12 10.13 10.14 10.15"
[        ]     export DERIVED_FILES_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/DerivedSources"
[        ]     export DERIVED_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/DerivedSources"
[        ]     export DERIVED_SOURCES_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/DerivedSources"
[        ]     export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export DEVELOPMENT_LANGUAGE=en
[        ]     export DONT_GENERATE_INFOPLIST_FILE=NO
[        ]     export DO_HEADER_SCANNING_IN_JAM=NO
[        ]     export DSTROOT=/tmp/Runner.dst
[        ]     export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export DWARF_DSYM_FILE_NAME=.dSYM
[        ]     export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
[        ]     export DWARF_DSYM_FOLDER_PATH=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
[        ]     export EMBEDDED_PROFILE_NAME=embedded.provisionprofile
[        ]     export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
[        ]     export ENABLE_BITCODE=NO
[        ]     export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
[        ]     export ENABLE_HARDENED_RUNTIME=NO
[        ]     export ENABLE_HEADER_DEPENDENCIES=YES
[        ]     export ENABLE_ON_DEMAND_RESOURCES=NO
[        ]     export ENABLE_PREVIEWS=NO
[        ]     export ENABLE_STRICT_OBJC_MSGSEND=YES
[        ]     export ENABLE_TESTABILITY=YES
[        ]     export EXCLUDED_ARCHS=arm64
[        ]     export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
[        ]     export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
[        ]     export FILE_LIST="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects/LinkFileList"
[        ]     export FIXED_FILES_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/FixedFiles"
[        ]     export FLUTTER_APPLICATION_PATH=/Users/elih/dev/bug
[        ]     export FLUTTER_BUILD_DIR=build
[        ]     export FLUTTER_BUILD_NAME=1.0.0
[        ]     export FLUTTER_BUILD_NUMBER=1
[        ]     export FLUTTER_ROOT=/Users/elih/dev/flutter
[        ]     export FLUTTER_TARGET=/Users/elih/dev/bug/lib/main.dart
[        ]     export FRAMEWORK_VERSION=A
[        ]     export GCC3_VERSION=3.3
[        ]     export GCC_C_LANGUAGE_STANDARD=gnu11
[        ]     export GCC_DYNAMIC_NO_PIC=NO
[        ]     export GCC_NO_COMMON_BLOCKS=YES
[        ]     export GCC_OPTIMIZATION_LEVEL=0
[        ]     export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
[        ]     export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
[        ]     export GCC_TREAT_WARNINGS_AS_ERRORS=NO
[        ]     export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
[        ]     export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
[        ]     export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
[        ]     export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
[        ]     export GCC_WARN_SHADOW=YES
[        ]     export GCC_WARN_STRICT_SELECTOR_MATCH=YES
[        ]     export GCC_WARN_UNDECLARED_SELECTOR=YES
[        ]     export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
[        ]     export GCC_WARN_UNUSED_FUNCTION=YES
[        ]     export GCC_WARN_UNUSED_VARIABLE=YES
[        ]     export GENERATE_MASTER_OBJECT_FILE=NO
[        ]     export GENERATE_PKGINFO_FILE=NO
[        ]     export GENERATE_PROFILING_CODE=NO
[        ]     export GENERATE_TEXT_BASED_STUBS=NO
[        ]     export GID=20
[        ]     export GROUP=staff
[        ]     export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
[        ]     export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
[        ]     export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
[        ]     export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
[        ]     export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
[        ]     export HEADERMAP_USES_VFS=NO
[        ]     export HIDE_BITCODE_SYMBOLS=YES
[   +3 ms]     export HOME=/Users/elih
[        ]     export ICONV=/usr/bin/iconv
[        ]     export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
[        ]     export INFOPLIST_OUTPUT_FORMAT=same-as-input
[        ]     export INFOPLIST_PREPROCESS=NO
[        ]     export INLINE_PRIVATE_FRAMEWORKS=NO
[        ]     export INSTALLHDRS_COPY_PHASE=NO
[        ]     export INSTALLHDRS_SCRIPT_PHASE=NO
[        ]     export INSTALL_DIR=/tmp/Runner.dst
[        ]     export INSTALL_GROUP=staff
[        ]     export INSTALL_MODE_FLAG=u+w,go-w,a+rX
[        ]     export INSTALL_OWNER=elih
[        ]     export INSTALL_ROOT=/tmp/Runner.dst
[        ]     export IOS_UNZIPPERED_TWIN_PREFIX_PATH=/System/iOSSupport
[        ]     export IS_MACCATALYST=NO
[        ]     export IS_UIKITFORMAC=NO
[        ]     export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
[        ]     export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
[        ]     export JAVA_ARCHIVE_CLASSES=YES
[        ]     export JAVA_ARCHIVE_TYPE=JAR
[        ]     export JAVA_COMPILER=/usr/bin/javac
[        ]     export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
[        ]     export JAVA_JAR_FLAGS=cv
[        ]     export JAVA_SOURCE_SUBDIR=.
[        ]     export JAVA_USE_DEPENDENCIES=YES
[        ]     export JAVA_ZIP_FLAGS=-urg
[        ]     export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
[        ]     export KASAN_DEFAULT_CFLAGS="-DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow"
[        ]     export KEEP_PRIVATE_EXTERNS=NO
[        ]     export LD_DEPENDENCY_INFO_FILE="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal/undefined_arch/Flutter Assemble_dependency_info.dat"
[        ]     export LD_GENERATE_MAP_FILE=NO
[        ]     export LD_MAP_FILE_PATH="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Flutter Assemble-LinkMap-normal-undefined_arch.txt"
[        ]     export LD_NO_PIE=NO
[        ]     export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
[        ]     export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
[        ]     export LEX=lex
[        ]     export LIBRARY_DEXT_INSTALL_PATH=/Library/DriverExtensions
[        ]     export LIBRARY_FLAG_NOSPACE=YES
[        ]     export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
[        ]     export LINKER_DISPLAYS_MANGLED_NAMES=NO
[        ]     export LINK_FILE_LIST_normal_x86_64="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal/x86_64/Flutter Assemble.LinkFileList"
[        ]     export LINK_WITH_STANDARD_LIBRARIES=YES
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_NO=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_YES=macos10.15
[        ]     export LLVM_TARGET_TRIPLE_VENDOR=apple
[        ]     export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFCopyLocalizedString"
[        ]     export LOCALIZED_STRING_SWIFTUI_SUPPORT=YES
[        ]     export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
[        ]     export LOCAL_APPS_DIR=/Applications
[        ]     export LOCAL_DEVELOPER_DIR=/Library/Developer
[        ]     export LOCAL_LIBRARY_DIR=/Library
[        ]     export LOCROOT=/Users/elih/dev/bug/macos
[        ]     export LOCSYMROOT=/Users/elih/dev/bug/macos
[        ]     export MACOSX_DEPLOYMENT_TARGET=10.11
[        ]     export MAC_OS_X_PRODUCT_BUILD_VERSION=19H524
[        ]     export MAC_OS_X_VERSION_ACTUAL=101507
[        ]     export MAC_OS_X_VERSION_MAJOR=101500
[        ]     export MAC_OS_X_VERSION_MINOR=1507
[        ]     export METAL_LIBRARY_FILE_BASE=default
[        ]     export METAL_LIBRARY_OUTPUT_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug/
[        ]     export MODULE_CACHE_DIR=/Users/elih/dev/bug/build/macos/ModuleCache.noindex
[        ]     export MTL_ENABLE_DEBUG_INFO=YES
[        ]     export NATIVE_ARCH=i386
[        ]     export NATIVE_ARCH_32_BIT=i386
[        ]     export NATIVE_ARCH_64_BIT=x86_64
[        ]     export NATIVE_ARCH_ACTUAL=x86_64
[        ]     export NO_COMMON=YES
[        ]     export OBJECT_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects"
[        ]     export OBJECT_FILE_DIR_normal="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal"
[        ]     export OBJROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export ONLY_ACTIVE_ARCH=YES
[        ]     export OS=MACOS
[        ]     export OSAC=/usr/bin/osacompile
[        ]     export PACKAGE_CONFIG=/Users/elih/dev/bug/.dart_tool/package_config.json
[        ]     export PASCAL_STRINGS=YES
[        ]     export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[        ]     export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
[        ]     export PER_ARCH_OBJECT_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal/undefined_arch"
[        ]     export PER_VARIANT_OBJECT_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal"
[        ]     export PKGINFO_FILE_PATH="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/PkgInfo"
[        ]     export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
[        ]     export PLATFORM_DISPLAY_NAME=macOS
[        ]     export PLATFORM_NAME=macosx
[        ]     export PLATFORM_PREFERRED_ARCH=x86_64
[        ]     export PLATFORM_PRODUCT_BUILD_VERSION=11C504
[        ]     export PLIST_FILE_OUTPUT_FORMAT=same-as-input
[        ]     export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
[        ]     export PRECOMP_DESTINATION_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/PrefixHeaders"
[        ]     export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
[        ]     export PRODUCT_MODULE_NAME=Flutter_Assemble
[        ]     export PRODUCT_NAME="Flutter Assemble"
[        ]     export PRODUCT_SETTINGS_PATH=
[        ]     export PROFILING_CODE=NO
[        ]     export PROJECT=Runner
[        ]     export PROJECT_DERIVED_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/DerivedSources
[        ]     export PROJECT_DIR=/Users/elih/dev/bug/macos
[        ]     export PROJECT_FILE_PATH=/Users/elih/dev/bug/macos/Runner.xcodeproj
[        ]     export PROJECT_NAME=Runner
[        ]     export PROJECT_TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build
[        ]     export PROJECT_TEMP_ROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
[        ]     export REMOVE_CVS_FROM_RESOURCES=YES
[        ]     export REMOVE_GIT_FROM_RESOURCES=YES
[        ]     export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
[        ]     export REMOVE_HG_FROM_RESOURCES=YES
[        ]     export REMOVE_SVN_FROM_RESOURCES=YES
[        ]     export REZ_COLLECTOR_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/ResourceManagerResources"
[        ]     export REZ_OBJECTS_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/ResourceManagerResources/Objects"
[        ]     export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
[        ]     export SCRIPT_INPUT_FILE_0=/Users/elih/dev/bug/macos/Flutter/ephemeral/tripwire
[        ]     export SCRIPT_INPUT_FILE_COUNT=1
[        ]     export SCRIPT_INPUT_FILE_LIST_0="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-59fceedaf283a3e78036ad59e27d2f85-resolved.xcfilelist"
[        ]     export SCRIPT_INPUT_FILE_LIST_COUNT=1
[        ]     export SCRIPT_OUTPUT_FILE_COUNT=0
[        ]     export SCRIPT_OUTPUT_FILE_LIST_0="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/OutputFileList-33CC111E2044C6BF0003C045-FlutterOutputs-b60a64e08287cf958c9f489ef2af025c-resolved.xcfilelist"
[        ]     export SCRIPT_OUTPUT_FILE_LIST_COUNT=1
[        ]     export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_DIR_macosx10_15=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_NAME=macosx10.15
[        ]     export SDK_NAMES=macosx10.15
[        ]     export SDK_PRODUCT_BUILD_VERSION=19B90
[        ]     export SDK_VERSION=10.15
[        ]     export SDK_VERSION_ACTUAL=101500
[        ]     export SDK_VERSION_MAJOR=101500
[        ]     export SDK_VERSION_MINOR=1500
[        ]     export SED=/usr/bin/sed
[        ]     export SEPARATE_STRIP=NO
[        ]     export SEPARATE_SYMBOL_EDIT=NO
[        ]     export SET_DIR_MODE_OWNER_GROUP=YES
[        ]     export SET_FILE_MODE_OWNER_GROUP=NO
[        ]     export SHALLOW_BUNDLE=NO
[        ]     export SHARED_DERIVED_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug/DerivedSources
[        ]     export SHARED_PRECOMPS_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/PrecompiledHeaders
[        ]     export SKIP_INSTALL=YES
[        ]     export SOURCE_ROOT=/Users/elih/dev/bug/macos
[        ]     export SRCROOT=/Users/elih/dev/bug/macos
[        ]     export STRINGS_FILE_OUTPUT_ENCODING=UTF-16
[        ]     export STRIP_BITCODE_FROM_COPIED_FILES=NO
[        ]     export STRIP_INSTALLED_PRODUCT=YES
[        ]     export STRIP_PNG_TEXT=NO
[        ]     export STRIP_STYLE=all
[        ]     export STRIP_SWIFT_SYMBOLS=YES
[        ]     export SUPPORTED_PLATFORMS=macosx
[        ]     export SUPPORTS_TEXT_BASED_API=NO
[        ]     export SWIFT_ACTIVE_COMPILATION_CONDITIONS=DEBUG
[        ]     export SWIFT_OPTIMIZATION_LEVEL=-Onone
[        ]     export SWIFT_PLATFORM_TARGET_PREFIX=macos
[        ]     export SWIFT_RESPONSE_FILE_PATH_normal_x86_64="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build/Objects-normal/x86_64/Flutter Assemble.SwiftFileList"
[        ]     export SYMROOT=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
[        ]     export SYSTEM_APPS_DIR=/Applications
[        ]     export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
[        ]     export SYSTEM_DEMOS_DIR=/Applications/Extras
[        ]     export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
[        ]     export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
[        ]     export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
[        ]     export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
[        ]     export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
[        ]     export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
[        ]     export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
[        ]     export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
[        ]     export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
[        ]     export SYSTEM_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
[        ]     export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
[        ]     export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
[        ]     export SYSTEM_LIBRARY_DIR=/System/Library
[        ]     export TAPI_VERIFY_MODE=ErrorsOnly
[        ]     export TARGETNAME="Flutter Assemble"
[        ]     export TARGET_BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export TARGET_NAME="Flutter Assemble"
[        ]     export TARGET_TEMP_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build"
[        ]     export TEMP_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build"
[        ]     export TEMP_FILES_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build"
[        ]     export TEMP_FILE_DIR="/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter Assemble.build"
[        ]     export TEMP_ROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
[        ]     export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export TRACK_WIDGET_CREATION=true
[        ]     export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
[        ]     export TREE_SHAKE_ICONS=false
[        ]     export UID=503
[        ]     export UNSTRIPPED_PRODUCT=NO
[        ]     export USER=elih
[        ]     export USER_APPS_DIR=/Users/elih/Applications
[        ]     export USER_LIBRARY_DIR=/Users/elih/Library
[        ]     export USE_DYNAMIC_NO_PIC=YES
[        ]     export USE_HEADERMAP=YES
[        ]     export USE_HEADER_SYMLINKS=NO
[        ]     export USE_LLVM_TARGET_TRIPLES=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_CLANG=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_LD=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_TAPI=YES
[        ]     export VALIDATE_DEVELOPMENT_ASSET_PATHS=YES_ERROR
[        ]     export VALIDATE_PRODUCT=NO
[        ]     export VALIDATE_WORKSPACE=NO
[        ]     export VALID_ARCHS="i386 x86_64"
[        ]     export VERBOSE_PBXCP=NO
[        ]     export VERBOSE_SCRIPT_LOGGING=YES
[        ]     export VERSION_INFO_BUILDER=elih
[        ]     export VERSION_INFO_FILE="Flutter Assemble_vers.c"
[        ]     export VERSION_INFO_STRING=""@(#)PROGRAM:Flutter Assemble  PROJECT:Runner-""
[        ]     export WARNING_CFLAGS="-Wall -Wconditional-uninitialized -Wnullable-to-nonnull-conversion -Wmissing-method-return-type -Woverlength-strings"
[        ]     export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
[        ]     export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
[        ]     export XCODE_PRODUCT_BUILD_VERSION=11C504
[        ]     export XCODE_VERSION_ACTUAL=1130
[        ]     export XCODE_VERSION_MAJOR=1100
[        ]     export XCODE_VERSION_MINOR=1130
[        ]     export XPCSERVICES_FOLDER_PATH=/XPCServices
[        ]     export YACC=yacc
[        ]     export _BOOL_=NO
[        ]     export _BOOL_NO=NO
[        ]     export _BOOL_YES=YES
[        ]     export _DEVELOPMENT_TEAM_IS_EMPTY=YES
[        ]     export _IS_EMPTY_=YES
[        ]     export _MACOSX_DEPLOYMENT_TARGET_IS_EMPTY=NO
[        ]     export arch=undefined_arch
[        ]     export variant=normal
[        ]     /bin/sh -c /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\\\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh
[   +5 ms] ♦ /Users/elih/dev/flutter/bin/flutter --verbose assemble --no-version-check -dTargetPlatform=darwin-x64 -dTargetFile=/Users/elih/dev/bug/lib/main.dart -dBuildMode=debug -dTreeShakeIcons=false -dDartObfuscation=false -dSplitDebugInfo= -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraGenSnapshotOptions= --ExtraFrontEndOptions= --build-inputs=/Users/elih/dev/bug/macos/Flutter/ephemeral/FlutterInputs.xcfilelist --build-outputs=/Users/elih/dev/bug/macos/Flutter/ephemeral/FlutterOutputs.xcfilelist --output=/Users/elih/dev/bug/build/macos/Build/Products/Debug debug_macos_bundle_flutter_assets
[ +514 ms] [ +152 ms] executing: sysctl hw.optional.arm64
[   +7 ms] [  +30 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] [        ] sysctl: unknown oid 'hw.optional.arm64'
[  +19 ms] [  +19 ms] executing: [/Users/elih/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] [   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] [        ] executing: [/Users/elih/dev/flutter/] git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[  +21 ms] [  +21 ms] Exit code 0 from: git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] [        ] 2.1.0-12.1.pre
[  +92 ms] [  +92 ms] executing: [/Users/elih/dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[   +7 ms] [   +7 ms] executing: sw_vers -productName
[  +16 ms] [  +16 ms] Exit code 0 from: sw_vers -productName
[        ] [        ] Mac OS X
[        ] [        ] executing: sw_vers -productVersion
[  +17 ms] [  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] [        ] 10.15.7
[        ] [        ] executing: sw_vers -buildVersion
[  +15 ms] [  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] [        ] 19H524
[  +70 ms] [  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] [  +51 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +146 ms] [ +146 ms] Initializing file store
[  +35 ms] [  +35 ms] Skipping target: gen_localizations
[  +26 ms] [  +27 ms] debug_macos_framework: Starting due to {InvalidatedReason.inputChanged}
[   +9 ms] [   +8 ms] executing: sysctl hw.optional.arm64
[   +7 ms] [   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] [        ] sysctl: unknown oid 'hw.optional.arm64'
[   +2 ms] [   +2 ms] executing: xcrun clang -x c /Users/elih/dev/bug/.dart_tool/flutter_build/849591e0a288d85c9a07defbf597544f/debug_app.cc -arch x86_64 -dynamiclib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -o /Users/elih/dev/bug/.dart_tool/flutter_build/849591e0a288d85c9a07defbf597544f/App.framework/App
[  +10 ms] [  +10 ms] debug_unpack_macos: Starting due to {InvalidatedReason.inputChanged}
[  +23 ms] [  +23 ms] kernel_snapshot: Starting due to {}
[   +4 ms] [   +5 ms] debug_unpack_macos: Complete
[ +380 ms] [ +380 ms] /Users/elih/dev/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/elih/dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/elih/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /Users/elih/dev/bug/.dart_tool/package_config.json --output-dill /Users/elih/dev/bug/.dart_tool/flutter_build/849591e0a288d85c9a07defbf597544f/app.dill --depfile /Users/elih/dev/bug/.dart_tool/flutter_build/849591e0a288d85c9a07defbf597544f/kernel_snapshot.d package:bug/main.dart
[ +182 ms] [ +182 ms] debug_macos_framework: Complete
[+10631 ms] [+10632 ms] kernel_snapshot: Complete
[ +468 ms] [ +468 ms] debug_macos_bundle_flutter_assets: Starting due to {}
[ +258 ms] [ +258 ms] debug_macos_bundle_flutter_assets: Complete
[ +559 ms] [ +559 ms] Persisting file store
[   +7 ms] [   +7 ms] Done persisting file store
[   +6 ms] [   +7 ms] build succeeded.
[  +16 ms] [  +16 ms] "flutter assemble" took 12,863ms.
[  +99 ms] [  +99 ms] ensureAnalyticsSent: 92ms
[   +1 ms] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[  +25 ms] ProcessProductPackaging "" /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug.app.xcent (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ] Entitlements:
[        ] {
[        ]     "com.apple.security.app-sandbox" = 1;
[        ]     "com.apple.security.cs.allow-jit" = 1;
[        ]     "com.apple.security.get-task-allow" = 1;
[        ]     "com.apple.security.network.server" = 1;
[        ] }
[        ]     builtin-productPackagingUtility -entitlements -format xml -o /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug.app.xcent
[   +6 ms] CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name bug -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.SwiftFileList -DDEBUG -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target x86_64-apple-macos10.11 -g -module-cache-path /Users/elih/dev/bug/build/macos/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -swift-version 5 -I /Users/elih/dev/bug/build/macos/Build/Products/Debug -F /Users/elih/dev/bug/build/macos/Build/Products/Debug -c -j8 -output-file-map /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Runner-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.swiftmodule -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-generated-files.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-own-target-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-all-target-headers.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-project-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Products/Debug/include -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug-Swift.h -working-directory /Users/elih/dev/bug/macos
[  +45 ms] CompileSwift normal x86_64 /Users/elih/dev/bug/macos/Flutter/GeneratedPluginRegistrant.swift (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/elih/dev/bug/macos/Runner/MainFlutterWindow.swift /Users/elih/dev/bug/macos/Runner/AppDelegate.swift -primary-file /Users/elih/dev/bug/macos/Flutter/GeneratedPluginRegistrant.swift -emit-module-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant\~partial.swiftmodule -emit-module-doc-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant\~partial.swiftdoc -serialize-diagnostics-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.dia -emit-dependencies-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.d -emit-reference-dependencies-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.swiftdeps -target x86_64-apple-macos10.11 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/elih/dev/bug/build/macos/Build/Products/Debug -F /Users/elih/dev/bug/build/macos/Build/Products/Debug -enable-testing -g -module-cache-path /Users/elih/dev/bug/build/macos/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -serialize-debugging-options -Xcc -working-directory -Xcc /Users/elih/dev/bug/macos -enable-anonymous-context-mangled-names -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-generated-files.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-own-target-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-all-target-headers.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-project-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Products/Debug/include -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc -DDEBUG=1 -module-name bug -o /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o
[ +257 ms] MergeSwiftModule normal x86_64 (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -merge-modules -emit-module /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/MainFlutterWindow\~partial.swiftmodule /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/AppDelegate\~partial.swiftmodule /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant\~partial.swiftmodule -parse-as-library -sil-merge-partial-modules -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-apple-macos10.11 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Users/elih/dev/bug/build/macos/Build/Products/Debug -F /Users/elih/dev/bug/build/macos/Build/Products/Debug -enable-testing -g -module-cache-path /Users/elih/dev/bug/build/macos/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -serialize-debugging-options -Xcc -working-directory -Xcc /Users/elih/dev/bug/macos -enable-anonymous-context-mangled-names -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-generated-files.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-own-target-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-all-target-headers.hmap -Xcc -iquote -Xcc /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-project-headers.hmap -Xcc -I/Users/elih/dev/bug/build/macos/Build/Products/Debug/include -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc -DDEBUG=1 -emit-module-doc-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.swiftdoc -emit-objc-header-path /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug-Swift.h -module-name bug -o /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.swiftmodule
[ +257 ms] PhaseScriptExecution Run\ Script /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-3399D490228B24CF009A79C7.sh (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     export ACTION=build
[        ]     export AD_HOC_CODE_SIGNING_ALLOWED=YES
[        ]     export ALTERNATE_GROUP=staff
[        ]     export ALTERNATE_MODE=u+w,go-w,a+rX
[        ]     export ALTERNATE_OWNER=elih
[        ]     export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
[        ]     export ALWAYS_SEARCH_USER_PATHS=NO
[        ]     export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
[        ]     export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
[        ]     export APPLE_INTERNAL_DIR=/AppleInternal
[        ]     export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
[        ]     export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
[        ]     export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
[        ]     export APPLICATION_EXTENSION_API_ONLY=NO
[        ]     export APPLY_RULES_IN_COPY_FILES=NO
[        ]     export APPLY_RULES_IN_COPY_HEADERS=NO
[        ]     export ARCHS=x86_64
[        ]     export ARCHS_STANDARD=x86_64
[        ]     export ARCHS_STANDARD_32_64_BIT="x86_64 i386"
[        ]     export ARCHS_STANDARD_32_BIT=i386
[        ]     export ARCHS_STANDARD_64_BIT=x86_64
[        ]     export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
[        ]     export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
[        ]     export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
[        ]     export BITCODE_GENERATION_MODE=marker
[        ]     export BUILD_ACTIVE_RESOURCES_ONLY=NO
[        ]     export BUILD_COMPONENTS="headers build"
[        ]     export BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export BUILD_LIBRARY_FOR_DISTRIBUTION=NO
[        ]     export BUILD_ROOT=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export BUILD_STYLE=
[        ]     export BUILD_VARIANTS=normal
[        ]     export BUILT_PRODUCTS_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export CACHE_ROOT=/var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
[        ]     export CCHROOT=/var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
[        ]     export CHMOD=/bin/chmod
[        ]     export CHOWN=/usr/sbin/chown
[        ]     export CLANG_ANALYZER_NONNULL=YES
[        ]     export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION=YES_AGGRESSIVE
[        ]     export CLANG_CXX_LANGUAGE_STANDARD=gnu++14
[        ]     export CLANG_CXX_LIBRARY=libc++
[        ]     export CLANG_ENABLE_MODULES=YES
[        ]     export CLANG_ENABLE_OBJC_ARC=YES
[        ]     export CLANG_MODULES_BUILD_SESSION_FILE=/Users/elih/dev/bug/build/macos/ModuleCache.noindex/Session.modulevalidation
[        ]     export CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY=YES
[        ]     export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
[        ]     export CLANG_WARN_BOOL_CONVERSION=YES
[        ]     export CLANG_WARN_COMMA=YES
[        ]     export CLANG_WARN_CONSTANT_CONVERSION=YES
[        ]     export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
[        ]     export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
[        ]     export CLANG_WARN_DOCUMENTATION_COMMENTS=YES
[        ]     export CLANG_WARN_EMPTY_BODY=YES
[        ]     export CLANG_WARN_ENUM_CONVERSION=YES
[        ]     export CLANG_WARN_INFINITE_RECURSION=YES
[        ]     export CLANG_WARN_INT_CONVERSION=YES
[        ]     export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
[        ]     export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
[        ]     export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
[        ]     export CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK=YES
[        ]     export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
[        ]     export CLANG_WARN_PRAGMA_PACK=YES
[        ]     export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
[        ]     export CLANG_WARN_STRICT_PROTOTYPES=YES
[        ]     export CLANG_WARN_SUSPICIOUS_MOVE=YES
[        ]     export CLANG_WARN_UNGUARDED_AVAILABILITY=YES_AGGRESSIVE
[        ]     export CLANG_WARN_UNREACHABLE_CODE=YES
[        ]     export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
[        ]     export CLASS_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/JavaClasses
[        ]     export CLEAN_PRECOMPS=YES
[        ]     export CLONE_HEADERS=NO
[        ]     export COCOAPODS_PARALLEL_CODE_SIGN=true
[        ]     export CODESIGNING_FOLDER_PATH=/Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app
[        ]     export CODE_SIGNING_ALLOWED=YES
[        ]     export CODE_SIGN_ENTITLEMENTS=Runner/DebugProfile.entitlements
[        ]     export CODE_SIGN_IDENTITY=-
[        ]     export CODE_SIGN_IDENTITY_NO="Apple Development"
[        ]     export CODE_SIGN_IDENTITY_YES=-
[        ]     export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
[        ]     export CODE_SIGN_STYLE=Automatic
[        ]     export COLOR_DIAGNOSTICS=NO
[        ]     export COMBINE_HIDPI_IMAGES=YES
[        ]     export COMPILER_INDEX_STORE_ENABLE=NO
[        ]     export COMPOSITE_SDK_DIRS=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/CompositeSDKs
[        ]     export COMPRESS_PNG_FILES=NO
[        ]     export CONFIGURATION=Debug
[        ]     export CONFIGURATION_BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export CONFIGURATION_TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug
[        ]     export CONTENTS_FOLDER_PATH=bug.app/Contents
[        ]     export CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_NO=bug.app/Contents
[        ]     export CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_YES=bug.app
[        ]     export COPYING_PRESERVES_HFS_DATA=NO
[        ]     export COPY_HEADERS_RUN_UNIFDEF=NO
[        ]     export COPY_PHASE_STRIP=NO
[        ]     export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
[        ]     export CP=/bin/cp
[        ]     export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
[        ]     export CURRENT_ARCH=undefined_arch
[        ]     export CURRENT_VARIANT=normal
[        ]     export DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
[        ]     export DART_OBFUSCATION=false
[        ]     export DEAD_CODE_STRIPPING=NO
[        ]     export DEBUGGING_SYMBOLS=YES
[        ]     export DEBUG_INFORMATION_FORMAT=dwarf
[        ]     export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
[        ]     export DEFAULT_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
[        ]     export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
[        ]     export DEFINES_MODULE=NO
[        ]     export DEPLOYMENT_LOCATION=NO
[        ]     export DEPLOYMENT_POSTPROCESSING=NO
[        ]     export DEPLOYMENT_TARGET_CLANG_ENV_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mmacosx-version-min
[        ]     export DEPLOYMENT_TARGET_LD_ENV_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_LD_FLAG_NAME=macosx_version_min
[        ]     export DEPLOYMENT_TARGET_SETTING_NAME=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_SUGGESTED_VALUES="10.6 10.7 10.8 10.9 10.10 10.11 10.12 10.13 10.14 10.15"
[        ]     export DERIVED_FILES_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources
[        ]     export DERIVED_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources
[        ]     export DERIVED_SOURCES_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources
[        ]     export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export DEVELOPMENT_LANGUAGE=en
[        ]     export DOCUMENTATION_FOLDER_PATH=bug.app/Contents/Resources/en.lproj/Documentation
[        ]     export DONT_GENERATE_INFOPLIST_FILE=NO
[        ]     export DO_HEADER_SCANNING_IN_JAM=NO
[        ]     export DSTROOT=/tmp/Runner.dst
[        ]     export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export DWARF_DSYM_FILE_NAME=bug.app.dSYM
[        ]     export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
[        ]     export DWARF_DSYM_FOLDER_PATH=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
[        ]     export EMBEDDED_PROFILE_NAME=embedded.provisionprofile
[        ]     export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
[        ]     export ENABLE_BITCODE=NO
[        ]     export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
[        ]     export ENABLE_HARDENED_RUNTIME=NO
[        ]     export ENABLE_HEADER_DEPENDENCIES=YES
[        ]     export ENABLE_ON_DEMAND_RESOURCES=NO
[        ]     export ENABLE_PREVIEWS=NO
[        ]     export ENABLE_STRICT_OBJC_MSGSEND=YES
[        ]     export ENABLE_TESTABILITY=YES
[        ]     export EXCLUDED_ARCHS=arm64
[        ]     export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
[        ]     export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
[        ]     export EXECUTABLES_FOLDER_PATH=bug.app/Contents/Executables
[        ]     export EXECUTABLE_FOLDER_PATH=bug.app/Contents/MacOS
[        ]     export EXECUTABLE_FOLDER_PATH_SHALLOW_BUNDLE_NO=bug.app/Contents/MacOS
[        ]     export EXECUTABLE_FOLDER_PATH_SHALLOW_BUNDLE_YES=bug.app/Contents
[        ]     export EXECUTABLE_NAME=bug
[        ]     export EXECUTABLE_PATH=bug.app/Contents/MacOS/bug
[        ]     export EXPANDED_CODE_SIGN_IDENTITY=-
[        ]     export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
[        ]     export FILE_LIST=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects/LinkFileList
[        ]     export FIXED_FILES_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/FixedFiles
[        ]     export FLUTTER_APPLICATION_PATH=/Users/elih/dev/bug
[        ]     export FLUTTER_BUILD_DIR=build
[        ]     export FLUTTER_BUILD_NAME=1.0.0
[        ]     export FLUTTER_BUILD_NUMBER=1
[        ]     export FLUTTER_ROOT=/Users/elih/dev/flutter
[        ]     export FLUTTER_TARGET=/Users/elih/dev/bug/lib/main.dart
[        ]     export FRAMEWORKS_FOLDER_PATH=bug.app/Contents/Frameworks
[        ]     export FRAMEWORK_FLAG_PREFIX=-framework
[        ]     export FRAMEWORK_SEARCH_PATHS="/Users/elih/dev/bug/build/macos/Build/Products/Debug "
[        ]     export FRAMEWORK_VERSION=A
[        ]     export FULL_PRODUCT_NAME=bug.app
[        ]     export GCC3_VERSION=3.3
[        ]     export GCC_C_LANGUAGE_STANDARD=gnu11
[        ]     export GCC_DYNAMIC_NO_PIC=NO
[        ]     export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
[        ]     export GCC_NO_COMMON_BLOCKS=YES
[        ]     export GCC_OPTIMIZATION_LEVEL=0
[        ]     export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
[        ]     export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
[        ]     export GCC_SYMBOLS_PRIVATE_EXTERN=NO
[        ]     export GCC_TREAT_WARNINGS_AS_ERRORS=NO
[        ]     export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
[        ]     export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
[        ]     export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
[        ]     export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
[        ]     export GCC_WARN_SHADOW=YES
[        ]     export GCC_WARN_STRICT_SELECTOR_MATCH=YES
[        ]     export GCC_WARN_UNDECLARED_SELECTOR=YES
[        ]     export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
[        ]     export GCC_WARN_UNUSED_FUNCTION=YES
[        ]     export GCC_WARN_UNUSED_VARIABLE=YES
[        ]     export GENERATE_MASTER_OBJECT_FILE=NO
[        ]     export GENERATE_PKGINFO_FILE=YES
[        ]     export GENERATE_PROFILING_CODE=NO
[        ]     export GENERATE_TEXT_BASED_STUBS=NO
[        ]     export GID=20
[        ]     export GROUP=staff
[        ]     export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
[        ]     export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
[        ]     export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
[        ]     export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
[        ]     export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
[        ]     export HEADERMAP_USES_VFS=NO
[        ]     export HEADER_SEARCH_PATHS="/Users/elih/dev/bug/build/macos/Build/Products/Debug/include "
[        ]     export HIDE_BITCODE_SYMBOLS=YES
[        ]     export HOME=/Users/elih
[        ]     export ICONV=/usr/bin/iconv
[        ]     export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
[        ]     export INFOPLIST_FILE=Runner/Info.plist
[        ]     export INFOPLIST_OUTPUT_FORMAT=same-as-input
[        ]     export INFOPLIST_PATH=bug.app/Contents/Info.plist
[        ]     export INFOPLIST_PREPROCESS=NO
[        ]     export INFOSTRINGS_PATH=bug.app/Contents/Resources/en.lproj/InfoPlist.strings
[        ]     export INLINE_PRIVATE_FRAMEWORKS=NO
[        ]     export INSTALLHDRS_COPY_PHASE=NO
[        ]     export INSTALLHDRS_SCRIPT_PHASE=NO
[        ]     export INSTALL_DIR=/tmp/Runner.dst/Applications
[        ]     export INSTALL_GROUP=staff
[        ]     export INSTALL_MODE_FLAG=u+w,go-w,a+rX
[        ]     export INSTALL_OWNER=elih
[        ]     export INSTALL_PATH=/Applications
[        ]     export INSTALL_ROOT=/tmp/Runner.dst
[        ]     export IOS_UNZIPPERED_TWIN_PREFIX_PATH=/System/iOSSupport
[        ]     export IS_MACCATALYST=NO
[        ]     export IS_UIKITFORMAC=NO
[        ]     export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
[        ]     export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
[        ]     export JAVA_ARCHIVE_CLASSES=YES
[        ]     export JAVA_ARCHIVE_TYPE=JAR
[        ]     export JAVA_COMPILER=/usr/bin/javac
[        ]     export JAVA_FOLDER_PATH=bug.app/Contents/Resources/Java
[        ]     export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
[        ]     export JAVA_JAR_FLAGS=cv
[        ]     export JAVA_SOURCE_SUBDIR=.
[        ]     export JAVA_USE_DEPENDENCIES=YES
[        ]     export JAVA_ZIP_FLAGS=-urg
[        ]     export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
[        ]     export KASAN_DEFAULT_CFLAGS="-DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow"
[        ]     export KEEP_PRIVATE_EXTERNS=NO
[        ]     export LD_DEPENDENCY_INFO_FILE=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/undefined_arch/bug_dependency_info.dat
[        ]     export LD_GENERATE_MAP_FILE=NO
[        ]     export LD_MAP_FILE_PATH=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug-LinkMap-normal-undefined_arch.txt
[        ]     export LD_NO_PIE=NO
[        ]     export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
[        ]     export LD_RUNPATH_SEARCH_PATHS=" @executable_path/../Frameworks"
[        ]     export LD_RUNPATH_SEARCH_PATHS_YES=@loader_path/../Frameworks
[        ]     export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
[        ]     export LEX=lex
[        ]     export LIBRARY_DEXT_INSTALL_PATH=/Library/DriverExtensions
[        ]     export LIBRARY_FLAG_NOSPACE=YES
[        ]     export LIBRARY_FLAG_PREFIX=-l
[        ]     export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
[        ]     export LIBRARY_SEARCH_PATHS="/Users/elih/dev/bug/build/macos/Build/Products/Debug "
[        ]     export LINKER_DISPLAYS_MANGLED_NAMES=NO
[        ]     export LINK_FILE_LIST_normal_x86_64=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.LinkFileList
[        ]     export LINK_WITH_STANDARD_LIBRARIES=YES
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_NO=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_YES=macos10.15
[        ]     export LLVM_TARGET_TRIPLE_VENDOR=apple
[        ]     export LOCALIZED_RESOURCES_FOLDER_PATH=bug.app/Contents/Resources/en.lproj
[        ]     export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFCopyLocalizedString"
[        ]     export LOCALIZED_STRING_SWIFTUI_SUPPORT=YES
[        ]     export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
[        ]     export LOCAL_APPS_DIR=/Applications
[        ]     export LOCAL_DEVELOPER_DIR=/Library/Developer
[        ]     export LOCAL_LIBRARY_DIR=/Library
[        ]     export LOCROOT=/Users/elih/dev/bug/macos
[        ]     export LOCSYMROOT=/Users/elih/dev/bug/macos
[        ]     export MACH_O_TYPE=mh_execute
[        ]     export MACOSX_DEPLOYMENT_TARGET=10.11
[        ]     export MAC_OS_X_PRODUCT_BUILD_VERSION=19H524
[        ]     export MAC_OS_X_VERSION_ACTUAL=101507
[        ]     export MAC_OS_X_VERSION_MAJOR=101500
[        ]     export MAC_OS_X_VERSION_MINOR=1507
[        ]     export METAL_LIBRARY_FILE_BASE=default
[        ]     export METAL_LIBRARY_OUTPUT_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Resources
[        ]     export MODULES_FOLDER_PATH=bug.app/Contents/Modules
[        ]     export MODULE_CACHE_DIR=/Users/elih/dev/bug/build/macos/ModuleCache.noindex
[        ]     export MTL_ENABLE_DEBUG_INFO=YES
[        ]     export NATIVE_ARCH=i386
[        ]     export NATIVE_ARCH_32_BIT=i386
[        ]     export NATIVE_ARCH_64_BIT=x86_64
[        ]     export NATIVE_ARCH_ACTUAL=x86_64
[        ]     export NO_COMMON=YES
[        ]     export OBJECT_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects
[        ]     export OBJECT_FILE_DIR_normal=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal
[        ]     export OBJROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export ONLY_ACTIVE_ARCH=YES
[        ]     export OS=MACOS
[        ]     export OSAC=/usr/bin/osacompile
[        ]     export PACKAGE_CONFIG=/Users/elih/dev/bug/.dart_tool/package_config.json
[        ]     export PACKAGE_TYPE=com.apple.package-type.wrapper.application
[        ]     export PASCAL_STRINGS=YES
[        ]     export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[        ]     export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
[        ]     export PBDEVELOPMENTPLIST_PATH=bug.app/Contents/pbdevelopment.plist
[        ]     export PER_ARCH_OBJECT_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/undefined_arch
[        ]     export PER_VARIANT_OBJECT_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal
[        ]     export PKGINFO_FILE_PATH=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/PkgInfo
[        ]     export PKGINFO_PATH=bug.app/Contents/PkgInfo
[        ]     export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
[        ]     export PLATFORM_DISPLAY_NAME=macOS
[        ]     export PLATFORM_NAME=macosx
[        ]     export PLATFORM_PREFERRED_ARCH=x86_64
[        ]     export PLATFORM_PRODUCT_BUILD_VERSION=11C504
[        ]     export PLIST_FILE_OUTPUT_FORMAT=same-as-input
[        ]     export PLUGINS_FOLDER_PATH=bug.app/Contents/PlugIns
[        ]     export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
[        ]     export PRECOMP_DESTINATION_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/PrefixHeaders
[        ]     export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
[        ]     export PRIVATE_HEADERS_FOLDER_PATH=bug.app/Contents/PrivateHeaders
[        ]     export PRODUCT_BUNDLE_IDENTIFIER=com.example.bug
[        ]     export PRODUCT_BUNDLE_PACKAGE_TYPE=APPL
[        ]     export PRODUCT_COPYRIGHT="Copyright © 2021 com.example. All rights reserved."
[        ]     export PRODUCT_MODULE_NAME=bug
[        ]     export PRODUCT_NAME=bug
[        ]     export PRODUCT_SETTINGS_PATH=/Users/elih/dev/bug/macos/Runner/Info.plist
[        ]     export PRODUCT_TYPE=com.apple.product-type.application
[        ]     export PROFILING_CODE=NO
[        ]     export PROJECT=Runner
[        ]     export PROJECT_DERIVED_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/DerivedSources
[        ]     export PROJECT_DIR=/Users/elih/dev/bug/macos
[        ]     export PROJECT_FILE_PATH=/Users/elih/dev/bug/macos/Runner.xcodeproj
[        ]     export PROJECT_NAME=Runner
[        ]     export PROJECT_TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build
[        ]     export PROJECT_TEMP_ROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export PUBLIC_HEADERS_FOLDER_PATH=bug.app/Contents/Headers
[        ]     export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
[        ]     export REMOVE_CVS_FROM_RESOURCES=YES
[        ]     export REMOVE_GIT_FROM_RESOURCES=YES
[        ]     export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
[        ]     export REMOVE_HG_FROM_RESOURCES=YES
[        ]     export REMOVE_SVN_FROM_RESOURCES=YES
[        ]     export REZ_COLLECTOR_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/ResourceManagerResources
[        ]     export REZ_OBJECTS_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/ResourceManagerResources/Objects
[        ]     export REZ_SEARCH_PATHS="/Users/elih/dev/bug/build/macos/Build/Products/Debug "
[        ]     export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
[        ]     export SCRIPTS_FOLDER_PATH=bug.app/Contents/Resources/Scripts
[        ]     export SCRIPT_INPUT_FILE_COUNT=0
[        ]     export SCRIPT_INPUT_FILE_LIST_COUNT=0
[        ]     export SCRIPT_OUTPUT_FILE_COUNT=0
[        ]     export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
[        ]     export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_DIR_macosx10_15=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     export SDK_NAME=macosx10.15
[        ]     export SDK_NAMES=macosx10.15
[        ]     export SDK_PRODUCT_BUILD_VERSION=19B90
[        ]     export SDK_VERSION=10.15
[        ]     export SDK_VERSION_ACTUAL=101500
[        ]     export SDK_VERSION_MAJOR=101500
[        ]     export SDK_VERSION_MINOR=1500
[        ]     export SED=/usr/bin/sed
[        ]     export SEPARATE_STRIP=NO
[        ]     export SEPARATE_SYMBOL_EDIT=NO
[        ]     export SET_DIR_MODE_OWNER_GROUP=YES
[        ]     export SET_FILE_MODE_OWNER_GROUP=NO
[        ]     export SHALLOW_BUNDLE=NO
[        ]     export SHALLOW_BUNDLE_=YES
[        ]     export SHALLOW_BUNDLE_driverkit=YES
[        ]     export SHALLOW_BUNDLE_ios=NO
[        ]     export SHALLOW_BUNDLE_macos=NO
[        ]     export SHARED_DERIVED_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug/DerivedSources
[        ]     export SHARED_FRAMEWORKS_FOLDER_PATH=bug.app/Contents/SharedFrameworks
[        ]     export SHARED_PRECOMPS_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/PrecompiledHeaders
[        ]     export SHARED_SUPPORT_FOLDER_PATH=bug.app/Contents/SharedSupport
[        ]     export SKIP_INSTALL=NO
[        ]     export SOURCE_ROOT=/Users/elih/dev/bug/macos
[        ]     export SRCROOT=/Users/elih/dev/bug/macos
[        ]     export STRINGS_FILE_OUTPUT_ENCODING=UTF-16
[        ]     export STRIP_BITCODE_FROM_COPIED_FILES=NO
[        ]     export STRIP_INSTALLED_PRODUCT=YES
[        ]     export STRIP_PNG_TEXT=NO
[        ]     export STRIP_STYLE=all
[        ]     export STRIP_SWIFT_SYMBOLS=YES
[        ]     export SUPPORTED_PLATFORMS=macosx
[        ]     export SUPPORTS_TEXT_BASED_API=NO
[        ]     export SWIFT_ACTIVE_COMPILATION_CONDITIONS=DEBUG
[        ]     export SWIFT_OPTIMIZATION_LEVEL=-Onone
[        ]     export SWIFT_PLATFORM_TARGET_PREFIX=macos
[        ]     export SWIFT_RESPONSE_FILE_PATH_normal_x86_64=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/bug.SwiftFileList
[        ]     export SWIFT_VERSION=5.0
[        ]     export SYMROOT=/Users/elih/dev/bug/build/macos/Build/Products
[        ]     export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
[        ]     export SYSTEM_APPS_DIR=/Applications
[        ]     export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
[        ]     export SYSTEM_DEMOS_DIR=/Applications/Extras
[        ]     export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
[        ]     export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
[        ]     export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
[        ]     export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
[        ]     export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
[        ]     export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
[        ]     export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
[        ]     export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
[        ]     export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
[        ]     export SYSTEM_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
[        ]     export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
[        ]     export SYSTEM_EXTENSIONS_FOLDER_PATH=bug.app/Contents/Library/SystemExtensions
[        ]     export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
[        ]     export SYSTEM_LIBRARY_DIR=/System/Library
[        ]     export TAPI_VERIFY_MODE=ErrorsOnly
[        ]     export TARGETNAME=Runner
[        ]     export TARGET_BUILD_DIR=/Users/elih/dev/bug/build/macos/Build/Products/Debug
[        ]     export TARGET_NAME=Runner
[        ]     export TARGET_TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_FILES_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_FILE_DIR=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_ROOT=/Users/elih/dev/bug/build/macos/Build/Intermediates.noindex
[        ]     export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
[        ]     export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export TRACK_WIDGET_CREATION=true
[        ]     export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
[        ]     export TREE_SHAKE_ICONS=false
[        ]     export UID=503
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH=bug.app/Contents/Resources
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_NO=bug.app/Contents/Resources
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_YES=bug.app/Contents
[        ]     export UNSTRIPPED_PRODUCT=NO
[        ]     export USER=elih
[        ]     export USER_APPS_DIR=/Users/elih/Applications
[        ]     export USER_LIBRARY_DIR=/Users/elih/Library
[        ]     export USE_DYNAMIC_NO_PIC=YES
[        ]     export USE_HEADERMAP=YES
[        ]     export USE_HEADER_SYMLINKS=NO
[        ]     export USE_LLVM_TARGET_TRIPLES=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_CLANG=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_LD=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_TAPI=YES
[        ]     export VALIDATE_DEVELOPMENT_ASSET_PATHS=YES_ERROR
[        ]     export VALIDATE_PRODUCT=NO
[        ]     export VALIDATE_WORKSPACE=NO
[        ]     export VALID_ARCHS="i386 x86_64"
[        ]     export VERBOSE_PBXCP=NO
[        ]     export VERBOSE_SCRIPT_LOGGING=YES
[        ]     export VERSIONPLIST_PATH=bug.app/Contents/version.plist
[        ]     export VERSION_INFO_BUILDER=elih
[        ]     export VERSION_INFO_FILE=bug_vers.c
[        ]     export VERSION_INFO_STRING=""@(#)PROGRAM:bug  PROJECT:Runner-""
[        ]     export WARNING_CFLAGS="-Wall -Wconditional-uninitialized -Wnullable-to-nonnull-conversion -Wmissing-method-return-type -Woverlength-strings"
[        ]     export WRAPPER_EXTENSION=app
[        ]     export WRAPPER_NAME=bug.app
[        ]     export WRAPPER_SUFFIX=.app
[        ]     export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
[        ]     export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
[        ]     export XCODE_PRODUCT_BUILD_VERSION=11C504
[        ]     export XCODE_VERSION_ACTUAL=1130
[        ]     export XCODE_VERSION_MAJOR=1100
[        ]     export XCODE_VERSION_MINOR=1130
[        ]     export XPCSERVICES_FOLDER_PATH=bug.app/Contents/XPCServices
[        ]     export YACC=yacc
[        ]     export _BOOL_=NO
[        ]     export _BOOL_NO=NO
[        ]     export _BOOL_YES=YES
[        ]     export _DEVELOPMENT_TEAM_IS_EMPTY=YES
[        ]     export _IS_EMPTY_=YES
[        ]     export _MACOSX_DEPLOYMENT_TARGET_IS_EMPTY=NO
[        ]     export arch=undefined_arch
[        ]     export variant=normal
[        ]     /bin/sh -c /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-3399D490228B24CF009A79C7.sh
[   +2 ms] ♦ mkdir -p -- /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks
[        ] ♦ rsync -av --delete --filter - .DS_Store /Users/elih/dev/bug/build/macos/Build/Products/Debug/App.framework /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks
[        ] building file list ... done
[        ] deleting App.framework/Versions/A/_CodeSignature/CodeResources
[        ] deleting App.framework/Versions/A/_CodeSignature/
[        ] App.framework/Versions/A/
[        ] App.framework/Versions/A/App
[        ] App.framework/Versions/A/Resources/Info.plist
[        ] App.framework/Versions/A/Resources/flutter_assets/AssetManifest.json
[        ] App.framework/Versions/A/Resources/flutter_assets/FontManifest.json
[        ] App.framework/Versions/A/Resources/flutter_assets/NOTICES
[        ] App.framework/Versions/A/Resources/flutter_assets/kernel_blob.bin
[ +204 ms] sent 34886945 bytes  received 158 bytes  69774206.00 bytes/sec
[        ] total size is 40266600  speedup is 1.15
[        ] ♦ rsync -av --delete --filter - .DS_Store --filter - Headers --filter - Modules /Users/elih/dev/bug/build/macos/Build/Products/Debug/FlutterMacOS.framework /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/
[   +6 ms] building file list ... done
[   +5 ms] FlutterMacOS.framework/Versions/A/
[        ] FlutterMacOS.framework/Versions/A/FlutterMacOS
[ +255 ms] FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources
[   +1 ms] sent 40511295 bytes  received 70 bytes  81022730.00 bytes/sec
[        ] total size is 41306343  speedup is 1.02
[        ] ♦ codesign --force --verbose --sign - -- /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/App.framework/App
[ +360 ms] /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/App.framework/App: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter.app]
[   +8 ms] ♦ codesign --force --verbose --sign - -- /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS
[  +48 ms] /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: replacing existing signature
[ +617 ms] /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter-macos]
[   +2 ms] ProcessInfoPlistFile /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Info.plist /Users/elih/dev/bug/macos/Runner/Info.plist (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     builtin-infoPlistUtility /Users/elih/dev/bug/macos/Runner/Info.plist -producttype com.apple.product-type.application -genpkginfo /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/PkgInfo -expandbuildsettings -platform macosx -additionalcontentfile /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Base.lproj/MainMenu-PartialInfo.plist -additionalcontentfile /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/assetcatalog_generated_info.plist -o /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Info.plist
[        ] CodeSign /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
[        ] Signing Identity:     "-"
[        ]     /usr/bin/codesign --force --sign - --entitlements /Users/elih/dev/bug/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/bug.app.xcent --timestamp=none /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app
[   +5 ms] /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app: replacing existing signature
[  +44 ms] Validate /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/elih/dev/bug/macos
[        ]     builtin-validationUtility /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app -no-validate-extension
[   +4 ms] ** BUILD SUCCEEDED **
[  +30 ms] Building macOS application... (completed in 18.0s)
[   +4 ms] executing: /usr/bin/plutil -convert json -o - /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Info.plist
[  +11 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/elih/dev/bug/build/macos/Build/Products/Debug/bug.app/Contents/Info.plist
[        ] {"CFBundleName":"bug","DTXcode":"1130","DTSDKName":"macosx10.15","NSHumanReadableCopyright":"Copyright © 2021 com.example. All rights reserved.","DTSDKBuild":"19B90","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"19H524","NSPrincipalClass":"NSApplication","CFBundleIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"CFBundleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"bug","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"com.example.bug","DTPlatformVersion":"GM","DTXcodeBuild":"11C504","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"11C504"}
[ +777 ms] Observatory URL on device: http://127.0.0.1:58162/e1t_D47c3ss=/
[   +6 ms] Caching compiled dill
[  +91 ms] Connecting to service protocol: http://127.0.0.1:58162/e1t_D47c3ss=/
[ +224 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:58162/e1t_D47c3ss=/.
[ +107 ms] DDS is listening at http://127.0.0.1:58167/WrxNm5KpZu4=/.
[  +94 ms] Successfully connected to service protocol: http://127.0.0.1:58162/e1t_D47c3ss=/
[  +29 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device (file:///var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/T/com.example.bug/bugrferIU/bug/)
[   +3 ms] Updating assets
[ +104 ms] Syncing files to device macOS...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:bug/main.dart 2199194d-2a48-4946-b7a9-b6e5d0887358
[        ] <- 2199194d-2a48-4946-b7a9-b6e5d0887358
[ +115 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device macOS... (completed in 122ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +7 ms] Connected to _flutterView/0x7fe8cb011820.
[   +4 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:58167/WrxNm5KpZu4=/
[  +16 ms] Activating Dart DevTools...
[  +57 ms] 
           ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during performLayout():
           'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1860 pos 16:
           'constraints.hasBoundedHeight': is not true.

           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md

           The relevant error-causing widget was:
             ListView file:///Users/elih/dev/bug/lib/main.dart:9:11

           When the exception was thrown, this was the stack:
           #2      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1860:16)
           #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213:28)
           #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:511:13)
           #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1569:12)
           #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1478:20)
           #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:14)
           #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
           #38     RenderView.performLayout (package:flutter/src/rendering/view.dart:153:14)
           #39     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1641:7)
           #40     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
           #41     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:463:19)
           #42     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
           #43     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
           #44     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
           #45     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
           #46     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
           (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

           The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#6235a relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
             needs compositing
             creator: ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#dba0d] ← Semantics ← Listener ←
               _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#28b70] ←
               Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#364e9] ← Scrollable ← ListView ←
               RepaintBoundary ← ⋯
             parentData: <none> (can use size)
             constraints: BoxConstraints(w=800.0, 0.0<=h<=Infinity)
             size: MISSING
             axisDirection: right
             crossAxisDirection: down
             offset: ScrollPositionWithSingleContext#7c999(offset: 0.0, range: null..null, viewport: null,
               ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#f7bd0,
               ScrollDirection.idle)
           This RenderObject had the following child:
               child 0: RenderSliverList#121ba NEEDS-LAYOUT NEEDS-PAINT
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +10 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#6235a relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +16 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#ed743 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +24 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#70ce3 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +16 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderPointerListener#708a2 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +10 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#5168f relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +12 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderPointerListener#b26a0 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +11 ms] 
           Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#be218 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +14 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#5fbda relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[   +7 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.
[  +16 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +24 ms] 
           Another exception was thrown: Null check operator used on a null value
[+1453 ms] Activating Dart DevTools... (completed in 1,677ms)
[ +813 ms] The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A58167%2FWrxNm5KpZu4%3D%2F
<I press 'q' at this point>
[+17756 ms] DevFS: Deleting filesystem on the device (file:///var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/T/com.example.bug/bugrferIU/bug/)
[   +4 ms] DevFS: Deleted filesystem on the device (file:///var/folders/7z/1wwvrw8n445cwnrjklcfzvrc0000gq/T/com.example.bug/bugrferIU/bug/)
[  +56 ms] Service protocol connection closed.
[        ] Application finished.
[   +5 ms] "flutter run" took 55,896ms.
[  +99 ms] ensureAnalyticsSent: 94ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 0

```

```
Analyzing bug...                                                
No issues found! (ran in 2.0s)

```

```
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.1.0-12.1.pre at /Users/user/dev/flutter
    • Framework revision 8264cb3e8a (12 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 2 categories.

```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
Adds a common debug method for checking that a viewport has bounded constraints. Provides a clean and clear error message everywhere that we check for this. There was already an excellent check and error message written for this in computeDryLayout, so I moved it to be shared.

Fixes https://github.com/flutter/flutter/issues/78796

I did not make this debug method part of the viewport class because it can be used in the 2D viewport as well later. :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/rendering/viewport_test.dart [hunk 1]
```diff
@@ -2188,4 +2188,76 @@ void main() {
     });
     expect(visited, true);
   });
+
+  testWidgets('Shrinkwrapping viewport asserts bounded cross axis', (WidgetTester tester) async {
+    final List<FlutterErrorDetails> errors = <FlutterErrorDetails>[];
+    FlutterError.onError = (FlutterErrorDetails error) => errors.add(error);
```
Comment (Piinks) [inline packages/flutter/test/rendering/viewport_test.dart:2194]: @thkim1011
