### PR TITLE
Use kPreventOverdraw for arcs with overlapping stroke caps

### LINKED ISSUE #178746: [Impeller] Fast arc stroke generator can overdraw when caps intersect
### Steps to reproduce

Draw a circular stroked arc with a transparent color. Use square stroke caps, and use a high sweep angle and stroke width so that the two square caps intersect.

This was an issue discovered and discussed with @flar. The fast arc stroke tessellation introduced in #169402 can draw overlapping geometry. The fast arc stroke tessellation does not take overdraw into account, causing incorrect coloring issues when used with transparent colors. This is similar to #174579.

Currently this overlap can only happen when using square caps. After #169400 is fixed, this will also happen with round caps.

This can be fixed by using `GeometryResult::Mode::kPreventOverdraw`, or by not using the fast arc stroke geometry for arcs with overlapping caps. We may want to performance comparisons for these two approaches in order to decide which one to use.

### Expected results

Overlapping caps should be the same color as the rest of the arc.

Image

### Actual results

Overlapping caps get overdrawn. The color is composited multiple times, causing a color mismatch with the rest of the arc.

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math' as math show pi;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: CustomPaint(painter: TestPainter()),
    );
  }
}

class TestPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawArc(
      Rect.fromCircle(center: size.center(Offset.zero), radius: 50),
      0,
      1.5 * math.pi,
      false,
      Paint()
        ..color = Colors.blue.withAlpha(127)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 80
        ..strokeCap = StrokeCap.square,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

```

</details>

### Screenshots or Video

See screenshots above.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.39.0-1.0.pre-181, on macOS 15.7.1 24G231 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.3)
[✓] Chrome - develop for the web
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by b-luk**
Fixes #178746

Before:
image

After:
image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 1]
```diff
@@ -80,4 +85,45 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+      auto half_width = stroke_width_ / 2.0f;
+      auto inner_radius = radius - half_width;
+      auto inner_arc_end_x =
+          cos(Radians(arc_.GetSweep()).radians) * inner_radius;
+      auto inner_square_cap_end_x =
+          inner_arc_end_x +
+          cos(Radians(arc_.GetSweep() + Degrees(90)).radians) * half_width;
+      return inner_square_cap_end_x > inner_radius;
+    }
+    case Cap::kRound: {
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:118]: Is this easier to compute in the method that has the Arc::Iterations structure?

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 2]
```diff
@@ -80,4 +85,45 @@ bool ArcGeometry::IsAxisAlignedRect() const {
   return false;
 }
 
+bool ArcGeometry::CapsOverlap() const {
+  FML_DCHECK(arc_.GetSweep().degrees >= 0.0f);
+  FML_DCHECK(arc_.GetSweep().degrees <= 360.0f);
+
+  if (stroke_width_ < 0 || cap_ == Cap::kButt ||
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:92]: What if stroke_width is much larger than the size of the arc? Does it overlap just by turning a little?

**Review by flar — CHANGES_REQUESTED** [review]
Some food for thought. I don't know if this can be moved somewhere where we compute the Arc::Iterator or not. It would give you helpful delta vectors to compute where the ends are.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 2 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:92]: Stroke widths up to `2 * radius` behave properly. With these stroke widths, there is overlap only if `sweep_angle > 180`. And we have a check in the next line, line 93, to return "no overlap" when `arc_.GetSweep().degrees <= 180`. 

Example with a stroke width close to 2\*r. (radius is 50, 2\*r is 100). Overlap only occurs when the sweep angle passes 180 degrees.
2r-stroke-width-overlap

For stroke widths greater than `2 * radius`:

I had tested this before (apparently only with Impeller enabled), and thought that we didn't need to handle this case because Impeller doesn't render caps at all for arcs with stroke widths greater than `2 * radius`.

I just tested this case again. This time I also tested the behavior with Impeller disabled, using Skia. Skia does render caps for stroke widths greater than `2 * radius`.

Skia:
big-stroke-width-skia

Impeller:
Note that the when the arc switches to a filled arc, it has a stripey pattern. This is a separate issue tracked by #178839.
big-stroke-width-impeller

Impeller falls back to [this code](https://github.com/flutter/flutter/blob/2c4d19119ec302dea203a7ca5288fa4301735118/engine/src/flutter/impeller/display_list/canvas.cc#L721-L731) and renders the arc as a filled arc. This drops the caps from the arc. I'll file a new issue about this. *Edit: opened https://github.com/flutter/flutter/issues/179369*

So for the current behavior of Impeller, the caps can only overlap when `sweep_angle > 180`. The check in this commit sufficiently handles all cases where caps may overlap.

If we change Impeller so that it renders `stroke_width > 2 * radius` arcs in the same way as Skia, then there could be overlap for smaller sweep angles. If/when we make this change we should make sure the overlap check here is updated to handle these cases.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 1 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:118]: Right now the Arc class and its Iterations helper structure define an arc that consists of bounds, start/sweep angles, and include_center. The ArcGeometry class combines an Arc with a Paint, giving it a stroke width and cap type.

These cap overlap calculations depend on the stroke width and cap type. So I compute them in the ArcGeometry class, rather than for Arc or Arc::Iterations which have no knowledge about these Paint properties.

We could consider moving the Paint properties to be in Arc instead of ArcGeometry. And that way it would make more sense for the calculations to happen in the Arc class. But that would be a larger change, and I don't know if there are intentional reasons why these properties were put in ArcGeometry instead of the Arc class. (Maybe there are other Geometrys or other users of Arcs which don't deal with Paint/caps/strokes, so it this doesn't belong in Arc?)

Looking at the implementations of Arc::Iterations and Arc::ComputeIterations, I don't really see anything there which would help make the caps overlap calculations easier to compute. But I could be missing something.

So based on my current understanding of things, I think these calculations make sense here in ArcGeometry. Let me know if this makes sense or if you think otherwise.

Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:118]: It looks like the Iterations was only computed temporarily in the tessellation functions so it is long gone by the time this code executes.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 3]
```diff
@@ -80,4 +85,45 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+      // https://github.com/flutter/flutter/issues/178746#issuecomment-3554526727
+      auto radius = arc_.GetOvalSize().width / 2.0f;
+      auto half_width = stroke_width_ / 2.0f;
+      auto inner_radius = radius - half_width;
+      auto inner_arc_end_x =
+          cos(Radians(arc_.GetSweep()).radians) * inner_radius;
+      auto inner_square_cap_end_x =
+          inner_arc_end_x +
+          cos(Radians(arc_.GetSweep() + Degrees(90)).radians) * half_width;
+      return inner_square_cap_end_x > inner_radius;
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:116]: This seems odd only calculating the X coordinate. Does it work at all angles? I notice you only test this with 0->330 arcs. You should add tests that cover a wide variety of angle conditions.

**Review by flar — CHANGES_REQUESTED** [review]

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 3 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:116]: The video at https://github.com/flutter/flutter/issues/178746#issuecomment-3554526727 shows that overlap can be determined using only the x coordinate. It should work for any sweep angle between 0 and 360. The video shows the relation between inner_square_cap_end_x (red line) and inner_radius (blue line) as the arc's sweep angle goes through a variety of angles across all 4 quadrants. Overlap occurs iff the red line > the blue line.

The video only shows a start angle of 0. These calculations are entirely independent of start angle, so we can treat any arc as if its start angle is 0 for the purposes of these calculation.

I updated the unit tests to test a lot more sweep angles.

Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:116]: Now I see what my confusion was. I was thinking along the lines of "but what if it starts at 45 degrees or 90 degrees then don't you need to use Y instead or combine the two"?

But, the point I was missing is that the start angle has no bearing on the results (other than to perhaps complicate the test) so the test can be made as if the start angle was 0. And if the start angle is 0, then only the X coordinate is needed.

Please add a comment mentioning that start angle is not relevant and computing as if it starts at 0 only requires a test on the X coordinate...?

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 2 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:92]: OK with the subsequent issue filed...

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 4]
```diff
@@ -47,7 +48,11 @@ GeometryResult ArcGeometry::GetPositionBuffer(const ContentContext& renderer,
     auto generator =
         renderer.GetTessellator().StrokedArc(transform, arc_, cap_, half_width);
 
-    return ComputePositionGeometry(renderer, generator, entity, pass);
+    auto result = ComputePositionGeometry(renderer, generator, entity, pass);
+    if (CapsOverlap()) {
+      result.mode = GeometryResult::Mode::kPreventOverdraw;
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:53]: Perhaps in a follow-on PR, we should consider having the generator specify the overlap type rather than patching it after the fact.

File: engine/src/flutter/impeller/entity/entity_unittests.cc [hunk 5]
```diff
@@ -2313,6 +2313,98 @@ TEST_P(EntityTest, FillPathGeometryGetPositionBufferReturnsExpectedMode) {
...
+  {
+    StrokeParameters stroke = {.width = 50.0f, .cap = Cap::kButt};
+    for (auto sweep = 0; sweep < 360; sweep += 5) {
+      auto geometry = Geometry::MakeStrokedArc(oval_bounds, Degrees(0),
+                                               Degrees(sweep), stroke);
+
+      GeometryResult result =
+          geometry->GetPositionBuffer(*GetContentContext(), {}, mock_pass);
+
+      EXPECT_EQ(result.mode, GeometryResult::Mode::kNormal);
```
Comment (flar) [inline engine/src/flutter/impeller/entity/entity_unittests.cc]: 2 (yeah, that's the right number) suggestions:

- when a test is parameterized, only the line number appears in the output so it is hard to figure out which parameter is failed. This can be solved by using the fact that the EXPECT and ASSERT macros return a stream object so you can append ` << "sweep: " << sweep` to the end of the line and that will print out after a failure (try adding in a test that fails to see this in operation).
- It couldn't hurt to add a for loop for start angles to make sure this works for all start angles as well. (As well as `<< start` stream indicators to the EXPECT macros.)
- (Ignore that this is point #3) I assume that sweeps of 360+ turn into circles so we might not be testing the same tessellation code. One thing that does happen is that if you include the center, it doesn't turn into a circle for stroking because both spokes still need to be drawn.
- (Ignore the count of points, I'm on a roll) Hmmm, does the case of include center stroked arcs that go beyond 360 degrees of sweep need overlap protection?

**Review by flar — CHANGES_REQUESTED** [review]
It all looks good, but I think I might have uncovered some related issues in my evaluation of the unit tests that bears investigation while we are solving the overlap issues.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 3 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:116]: Done. Added a comment. I also changed the round cap test to treat the start angle as 0, because this simplifies that test a bit too.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 4 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:53]: Acknowledged. I'll follow up with this.

File: engine/src/flutter/impeller/entity/entity_unittests.cc (hunk 5 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/entity_unittests.cc]: - Added sweep angle output.
- Added a for loop with start angles and added start angle output.
- Arcs that include the center do not use this tessellation code. [This check](https://github.com/flutter/flutter/blob/26f311ca5e8519f31b10a2fca6f10b6eaa028e04/engine/src/flutter/impeller/display_list/canvas.cc#L733-L740) makes stroked arcs that include the center use the path-based ArcStrokeGeometry code. These arcs will use the overdraw protection that is used by path-based strokes.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 6]
```diff
@@ -80,4 +85,52 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+    return false;
+  }
+
+  switch (cap_) {
+    case Cap::kSquare: {
+      // Square caps overlap if the inner corner of the ending cap extends
+      // inside the inner edge of the start cap. For a visualization of when
+      // this occurs, see
+      // https://github.com/flutter/flutter/issues/178746#issuecomment-3554526727
+      // Note that testing for overlap is completely non-dependent on the arc's
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: independent of

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 7]
```diff
@@ -80,4 +85,52 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+    case Cap::kRound: {
+      // Round caps overlap if the distance between the arc's start and end
+      // points is less than the stroke width.
+      // https://github.com/flutter/flutter/issues/178746#issuecomment-3554526727
+      // Note that testing for overlap is completely non-dependent on the arc's
+      // start angle. To simplify the overlap test, we treat the arc as if its
+      // start angle is 0.
+      auto radius = arc_.GetOvalSize().width / 2.0f;
+      auto start_point = Point(radius, 0);
+      auto sweep_angle = Radians(arc_.GetSweep()).radians;
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: nit: sweep_radians since you've resolved it to radians and not just an angle

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 8]
```diff
@@ -80,4 +85,52 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+      auto end_point = Point(cos(sweep_angle), sin(sweep_angle)) * radius;
+      return (end_point - start_point).GetLength() < stroke_width_;
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: `start_point.GetDistanceSquared(end_point) < stroke_width * stroke_width` to avoid the sqrt

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc [hunk 9]
```diff
@@ -80,4 +85,52 @@ bool ArcGeometry::IsAxisAlignedRect() const {
...
+      // inside the inner edge of the start cap. For a visualization of when
+      // this occurs, see
+      // https://github.com/flutter/flutter/issues/178746#issuecomment-3554526727
+      // Note that testing for overlap is completely non-dependent on the arc's
+      // start angle. To simplify the overlap test, we treat the arc as if its
+      // start angle is 0. This allows the test to only require checking the x
+      // coordinate of the ending cap, rather than needing to calculate overlap
+      // based on both x and y positions of both caps.
+      auto radius = arc_.GetOvalSize().width / 2.0f;
+      auto half_width = stroke_width_ / 2.0f;
```
Comment (flar) [inline engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: `* 0.5f` might be faster than `/ 2.0f` depending on compiler opts.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 3 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc:116]: Good comment. Grammar suggestion...

**Review by flar — CHANGES_REQUESTED** [review]
LGTM, but we should have a golden that also verifies the output but I didn't see any golden changes from existing tests. Maybe a variety of angles and widths with each end cap. I don't think you need to test the non-overlaps (maybe 1 for reference?), just make sure a variety of overlaps don't overdraw. It might require 3 separate tests? Or if you can pack in a reasonably visible set of tests into one image that would be cool too. But we should have had golden changes for this and the fact that we didn't indicates a hole in our testing.

Some minor nits in the comments that would be nice to adopt.

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 6 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: Done

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 7 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: Done

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 8 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: Done

File: engine/src/flutter/impeller/entity/geometry/arc_geometry.cc (hunk 9 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/geometry/arc_geometry.cc]: Done

**Review by flar — APPROVED** [review]
LGTM

**Comment by flar** [comment]
Goldens LGTM
