### PR TITLE
Make initial daemon devices population fast

### LINKED ISSUE #56947: `flutter daemon` takes ~30 seconds to discover first iOS device
From https://buganizer.corp.google.com/issues/156287108

Steps to Reproduce:
1. `$ flutter daemon`
2. stdin `[{"id":1,"method":"device.enable"}]`
3. Wait until a line like this outputs:
```
[{"event":"device.added","params":{"id":"a1b07916f5d38432c3e4dde4a427b14a23ee16ab","name":"First's iPhone","platform":"ios","emulator":false,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":null}}]
```
(platform=ios).

On my machine this takes ~36 seconds.  Regression from https://github.com/flutter/flutter/commit/2f216ceee599ddb31371dbe5da6fec7ec6e68513, before which this took ~6 seconds.

### PR DESCRIPTION
**Pull request by jmagman**
## Description

The first time daemon polling runs, use the default device discovery timeouts.  Use longer timeouts on subsequent calls to populate devices that may take longer than the timeout.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/56947
https://buganizer.corp.google.com/issues/156287108

## Tests

Added PollingDeviceDiscovery test.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/test/src/mocks.dart [hunk 1]
```diff
@@ -482,8 +482,8 @@ class MockStdio extends Stdio {
   List<String> get writtenToStderr => _stderr.writes.map<String>(_stderr.encoding.decode).toList();
 }
 
-class MockPollingDeviceDiscovery extends PollingDeviceDiscovery {
-  MockPollingDeviceDiscovery() : super('mock');
+class FakePollingDeviceDiscovery extends PollingDeviceDiscovery {
```
Comment (jonahwilliams) [inline packages/flutter_tools/test/src/mocks.dart:485]: 👏

File: packages/flutter_tools/test/general.shard/device_test.dart [hunk 2]
```diff
@@ -63,6 +64,23 @@ void main() {
     });
   });
 
+  group('PollingDeviceDiscovery', () {
+    testUsingContext('startPolling', () async {
```
Comment (jonahwilliams) [inline packages/flutter_tools/test/general.shard/device_test.dart:68]: This test could use some comments to explain the scenario it is setting up.

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit
