### PR TITLE
Fixes Intrinsics for RenderParagraph and RenderWrap

### LINKED ISSUE #48679: Incorrect IntrinsicHeight calculation for RichText
Internal: b/147481532

This IntrinsicHeight calculation being incorrect seems to be the underlying issue for a number of things that customer:money is seeing.

I've stripped it back to a simplistic example.

With `IntrinsicHeight` absent, this is what I see:

image

With `IntrinsicHeight` present, this is what I see:

image

**The expectation is that both of these should look the same.**

Full repro code:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IntrinsicHeight',
      theme: ThemeData(primarySwatch: Colors.blue),
      darkTheme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(title: Text('IntrinsicHeight Test')),
        body: Align(
          alignment: Alignment.topLeft,
          child: Container(
            color: Colors.green,
            child: IntrinsicHeight(
              child: RichText(
                text: TextSpan(
                  text: 'Root\n',
                  children: [
                    TextSpan(text: 'Start\n'),
                    WidgetSpan(
                      child: Row(
                        children: [
                          Icon(Icons.edit, size: 16),
                        ],
                      ),
                    ),
                    TextSpan(text: 'End'),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by goderbauer**
For google3 rollers: This change requires https://github.com/dnfield/flutter_svg/pull/450 and cl/343539658.

## Description

Fixes https://github.com/flutter/flutter/issues/48679 by implementing the solution outlined in https://github.com/flutter/flutter/issues/48679#issuecomment-577456960. Going forward, authors of RenderBox subclasses will have to implement a new `computeDryLayout` method, which calculates nondestructively the Size that the RenderBox would like to be under the given set of constraints.

Furthermore, performResize is now implemented by calling the new computeDryLayout method and does not have to be overridden in subclasses anymore.

Last, but not least, this change adds a `computeSizeForNoChild` method to `RenderProxyBoxMixin`, which is called from performLayout and computeDryLayout when the RenderProxy has no child to determine its size based on the current constraints (previously this was done by calling performResize, which was a little odd since performResize is documented to only be called when sizedByParent is true (which it often isn't in these cases)). The default implementation just returns `constraints.smallest` (which is what `performResize` used to set the size as as well).

## Related Issues

Fixes https://github.com/flutter/flutter/issues/48679

## Tests

I added the following tests:

* Added tests for the cases from the bug
* Also: This is self-testing: In every test we check that the size computed by performLayout/performResize matches the size computed by performDryLayout.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a migration guide: https://github.com/flutter/website/pull/5007

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/box.dart [hunk 1]
```diff
@@ -1768,6 +1768,106 @@ abstract class RenderBox extends RenderObject {
...
+  ///
+  /// If this algorithm depends on the size of a child, the size of that child
+  /// should be obtained using its [getDryLayout] method.
+  ///
+  /// ### When the size cannot be known
+  ///
+  /// There are cases where render objects do not have an efficient way to
+  /// compute their size without doing a full layout. For example, the size
+  /// may depend on the baseline of a child, which is not available without
+  /// doing a full layout.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:1823]: also when the layout is lazy, right? e.g. SliverList?

File: packages/flutter/lib/src/rendering/box.dart [hunk 2]
```diff
@@ -1768,6 +1768,106 @@ abstract class RenderBox extends RenderObject {
...
+  /// See also:
+  ///
+  ///  * [computeDryLayout], which lists some reasons why it may not be feasible
+  ///    to compute the dry layout.
+  bool debugDryLayoutNotSupported(String reason, [List<DiagnosticsNode> additionalDiagnostics = const <DiagnosticsNode>[]]) {
+    assert(() {
+      if (!RenderObject.debugCheckingIntrinsics) {
+        throw FlutterError.fromParts(<DiagnosticsNode>[
+          ErrorSummary('The RenderBox "$runtimeType" does not support dry layout.'),
+          ErrorDescription('Reason given: $reason'),
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:1861]: I don't think "Reason given:" really adds anything.

File: packages/flutter/lib/src/rendering/box.dart [hunk 3]
```diff
@@ -1768,6 +1768,106 @@ abstract class RenderBox extends RenderObject {
...
+  ///
+  /// See also:
+  ///
+  ///  * [computeDryLayout], which lists some reasons why it may not be feasible
+  ///    to compute the dry layout.
+  bool debugDryLayoutNotSupported(String reason, [List<DiagnosticsNode> additionalDiagnostics = const <DiagnosticsNode>[]]) {
+    assert(() {
+      if (!RenderObject.debugCheckingIntrinsics) {
+        throw FlutterError.fromParts(<DiagnosticsNode>[
+          ErrorSummary('The RenderBox "$runtimeType" does not support dry layout.'),
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:1860]: objectRuntimeType

Comment (Hixie) [reply packages/flutter/lib/src/rendering/box.dart:1860]: (yes i know this is in an assert but we have a lint now)

Comment (Hixie) [reply packages/flutter/lib/src/rendering/box.dart:1860]: (also affects other places in the pr)

File: packages/flutter/lib/src/rendering/box.dart [hunk 4]
```diff
@@ -1768,6 +1768,106 @@ abstract class RenderBox extends RenderObject {
...
+  /// subclass does not support calculating a dry layout.
+  ///
+  /// When asserts are enabled, this method will throw a [FlutterError] with
+  /// the provided `reason` for not supporting dry layout. Otherwise, it will
+  /// simply return true.
+  ///
+  /// See also:
+  ///
+  ///  * [computeDryLayout], which lists some reasons why it may not be feasible
+  ///    to compute the dry layout.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:1855]: should this mention debugCheckingIntrinsics? It seems to be the real reason this function exists...

File: packages/flutter/lib/src/rendering/box.dart [hunk 5]
```diff
@@ -2147,10 +2277,15 @@ abstract class RenderBox extends RenderObject {
     super.markNeedsLayout();
   }
 
+  /// {@macro flutter.rendering.RenderObject.performResize}
+  ///
+  /// By default this method calls [getDryLayout] with the current
+  /// [constraints]. Instead of overriding this method, consider overriding
+  /// [computeDryLayout] (which is used by [getDryLayout] behind the scenes).
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:2284]: "(which is used by [getDryLayout] behind the scenes)" sounds mysterious, maybe "(the backend implementation of getDryLayout)" or something?

File: packages/flutter/lib/src/rendering/custom_paint.dart [hunk 6]
```diff
@@ -514,9 +514,16 @@ class RenderCustomPaint extends RenderProxyBox {
   }
 
   @override
-  void performResize() {
-    size = constraints.constrain(preferredSize);
-    markNeedsSemanticsUpdate();
+  void performLayout() {
+    super.performLayout();
+    if (child == null) {
+      markNeedsSemanticsUpdate();
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/custom_paint.dart:520]: this is a weird condition

**Comment by Hixie** [comment]
I'm worried about the amount of duplicate code that this involves. Is there any way we can use this to simplify matters? Maybe find places where the intrinsics can defer to the dry layout? Or ways the dry and wet layouts can be implemented as one method?

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 7]
```diff
@@ -585,6 +585,20 @@ class _RenderChildOverflowBox extends RenderAligningShiftedBox {
   @override
   double computeMinIntrinsicHeight(double width) => 0.0;
 
+  @override
+  Size computeDryLayout(BoxConstraints constraints) {
+    final BoxConstraints constraints = this.constraints;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/floating_action_button.dart:590]: if this is correct, it definitely deserves a comment. :-)

File: packages/flutter/lib/src/rendering/layout_helper.dart [hunk 8]
```diff
@@ -0,0 +1,55 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:ui';
+
+import 'box.dart';
+
+/// Signature for a function that takes a [RenderBox] and returns the [Size]
+/// that the [RenderBox] would have if it were layouted with the given
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/layout_helper.dart:10]: layouted -> laid out

File: packages/flutter/lib/src/rendering/layout_helper.dart [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+/// [BoxConstraints].
+///
+/// The methods of [ChildLayoutHelper] adhere to this signature.
+typedef ChildLayouter = Size Function(RenderBox child, BoxConstraints constraints);
+
+/// A collection of static functions to layout a [RenderBox] child with the
+/// given set of [BoxConstraints].
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/layout_helper.dart:17]: might be worth mentioning that these all implement ChildLayouter?

File: packages/flutter/lib/src/rendering/flex.dart [hunk 10]
```diff
@@ -812,75 +830,114 @@ class RenderFlex extends RenderBox with ContainerRenderObjectMixin<RenderBox, Fl
...
+
+  @override
+  void performLayout() {
+    assert(_debugHasNecessaryDirections);
+    final BoxConstraints constraints = this.constraints;
+
+    final _LayoutSizes sizes = _computeSizes(
+      layoutChild: (RenderBox child, BoxConstraints constraints) {
+        child.layout(constraints, parentUsesSize: true);
+        return child.size;
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/flex.dart:895]: can this use ChildLayoutHelper?

File: packages/flutter/lib/src/rendering/flex.dart [hunk 11]
```diff
@@ -650,33 +652,53 @@ class RenderFlex extends RenderBox with ContainerRenderObjectMixin<RenderBox, Fl
...
+  Size computeDryLayout(BoxConstraints constraints) {
+    if (!_canComputeIntrinsics) {
+      assert(debugDryLayoutNotSupported(
+        'Dry layout cannot be computed for CrossAxisAlignment.baseline, which requires a full layout.'
+      ));
+      return const Size(0, 0);
+    }
+    final _LayoutSizes sizes = _computeSizes(
+      layoutChild: (RenderBox child, BoxConstraints constraints) {
+        return child.getDryLayout(constraints);
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/flex.dart:683]: can this use ChildLayoutHelper?

File: packages/flutter/lib/src/rendering/object.dart [hunk 12]
```diff
@@ -1822,17 +1822,19 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
...
   /// Do not call this function directly: call [layout] instead. This function
   /// is called by [layout] when there is actually work to be done by this
   /// render object during layout. The layout constraints provided by your
   /// parent are available via the [constraints] getter.
   ///
+  /// This function is called only if [sizedByParent] is true.
+  /// {@endtemplate}
+  ///
   /// Subclasses that set [sizedByParent] to true should override this method
   /// to compute their size.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart:1837]: might be worth adding something about RenderBox here

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 13]
```diff
@@ -607,10 +613,42 @@ class RenderParagraph extends RenderBox
     }
   }
 
+  bool _canComputeDryLayout() {
+    // Dray layout cannot be calculated without a full layout for
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/paragraph.dart:617]: dry

**Comment by Hixie** [comment]
> I'm worried about the amount of duplicate code that this involves. Is there any way we can use this to simplify matters? Maybe find places where the intrinsics can defer to the dry layout? Or ways the dry and wet layouts can be implemented as one method?

I guess it's not all that bad. You do end up reusing a bunch of code.

Where does the previous intrinsic/layout logic now defer to the new API to solve the bug?

**Comment by goderbauer** [comment]
> Where does the previous intrinsic/layout logic now defer to the new API to solve the bug?

It's used in three places:

* RenderParagraph. _computeChildrenHeightWithMinIntrinsics (https://github.com/flutter/flutter/pull/70656/files#diff-bc57c6a6c8e97b4cade139f2b1030fffc8707ee8e9713fcab3684e2a213542deL435)
* RenderWrap. _computeIntrinsicWidthForHeight (https://github.com/flutter/flutter/pull/70656/files#diff-cebbc90963c6b6d225fcb82d34a027ab6f1fa2815a36a174766bd37b94bd282bL438)
* RenderWrap. _computeIntrinsicHeightForWidth (https://github.com/flutter/flutter/pull/70656/files#diff-cebbc90963c6b6d225fcb82d34a027ab6f1fa2815a36a174766bd37b94bd282bL408)

**Comment by goderbauer** [comment]
I was able to simplify the RenderWrap code a little more by implementing its other intrinsics methods in terms of dryLayout. The new API is still used in three places:

* RenderParagraph. _computeChildrenHeightWithMinIntrinsics (https://github.com/flutter/flutter/pull/70656/files#diff-bc57c6a6c8e97b4cade139f2b1030fffc8707ee8e9713fcab3684e2a213542deL435)
* RenderWrap.computeMinIntrinsicWidth (https://github.com/flutter/flutter/pull/70656/files#diff-cebbc90963c6b6d225fcb82d34a027ab6f1fa2815a36a174766bd37b94bd282bL472)
* RenderWrap.computeMaxIntrinsicWidth (https://github.com/flutter/flutter/pull/70656/files#diff-cebbc90963c6b6d225fcb82d34a027ab6f1fa2815a36a174766bd37b94bd282bL488)

**Comment by Hixie** [comment]
Nice.

**Comment by goderbauer** [comment]
I updated this PR with the drayLayout implementations for the remaining RenderBoxes.

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 14]
```diff
@@ -2417,6 +2484,42 @@ class RenderFittedBox extends RenderProxyBox {
 
   // TODO(ianh): The intrinsic dimensions of this box are wrong.
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/proxy_box.dart:2485]: Can this TODO be removed?

**Review by Piinks — COMMENTED** [review]
Does this have implications for the solution we're exploring in https://github.com/flutter/flutter/pull/70855?

**Comment by goderbauer** [comment]
> Does this have implications for the solution we're exploring in #70855?

I removed the legacy mode from here and closed the other PR since SliverFillRemaining seems to require intrinsics.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 14 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/proxy_box.dart:2485]: The other intrinsics in this file are still incorrect.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

This looks like a good change!  You might want to updated the PR description to include the links to the breaking change information.

File: packages/flutter/lib/src/rendering/box.dart [hunk 15]
```diff
@@ -1768,6 +1768,116 @@ abstract class RenderBox extends RenderObject {
...
+  /// doing a full layout), it may be computed by a callback about which the
+  /// render object cannot reason, or the layout is so complex that it
+  /// is simply impractical to calculate the size in an efficient way.
+  ///
+  /// In such cases, it may be impossible (or at least impractical) to actually
+  /// return a valid answer. In such cases, the function should call
+  /// [debugCannotComputeDryLayout] from within an assert and and return a dummy
+  /// value of `const Size(0, 0)`.
+  @protected
+  Size computeDryLayout(BoxConstraints constraints) {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/rendering/box.dart:1832]: The name feels a little odd: If I was someone seeing it for the first time, I might wonder if there was a wet layout too, and what dry refers to.

Maybe `computeDryRunLayout`? `computeDesiredLayout`? `computeAPrioriLayout`?

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/box.dart:1832]: I am not really happy about any of these names... I added a paragraph to the docs explaining why this is dry and the other layout is wet.

Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/box.dart:1840]: Instead of the paragraph, why not change the name to `computeDryRunLayout`?  Seems more self-documenting.

File: packages/flutter/lib/src/rendering/box.dart [hunk 16]
```diff
@@ -1768,6 +1768,124 @@ abstract class RenderBox extends RenderObject {
...
+      _cachedDryLayoutSizes ??= <BoxConstraints, Size>{};
+      return _cachedDryLayoutSizes!.putIfAbsent(constraints, () => computeDryLayout(constraints));
+    }
+    return computeDryLayout(constraints);
+  }
+
+  /// Computes the value returned by [getDryLayout]. Do not call this
+  /// function directly, instead, call [getDryLayout].
+  ///
+  /// Override in subclasses that implement [performLayout] or [performResize].
```
Comment (tvolkert) [inline packages/flutter/lib/src/rendering/box.dart:1811]: ... or subclasses of `RenderBox` that set `sizedByParent` to true but _didn't_ override `performResize` (see comment below).

File: packages/flutter/lib/src/rendering/box.dart [hunk 17]
```diff
@@ -2147,10 +2293,15 @@ abstract class RenderBox extends RenderObject {
...
+  /// {@macro flutter.rendering.RenderObject.performResize}
+  ///
+  /// By default this method calls [getDryLayout] with the current
+  /// [constraints]. Instead of overriding this method, consider overriding
+  /// [computeDryLayout] (the backend implementation of [getDryLayout]).
   @override
   void performResize() {
     // default behavior for subclasses that have sizedByParent = true
-    size = constraints.smallest;
+    size = computeDryLayout(constraints);
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/box.dart:2304]: In the framework there appear to be a total of 16 RenderObject subclasses that set `sizedByParent` to true. Of those, only 2 used to rely on the default of `performResize` (constraints.smallest) and the remaining 14 had custom implementations. If I recall correctly, there also wasn't any customer_test that relied on the old default of `performResize`. With that, I wouldn't really call this "hugely breaking"...

I considered making the default computeDryLayout return `constraints.smallest` if `sizedByParent` was set, but ultimately decided against making that method more complicated (and harder to reason about) since the impact of the change seemed so low. 

Having said all that, is there something I missed that makes this change more breaking?

[the remark this answers is not in the document]
Comment (tvolkert) [reply packages/flutter/lib/src/rendering/box.dart:2304]: Interesting.  When I ran across this, it's because I hit the error in my app; I had three render objects in which I had overridden `sizedByParent` to return true, and in all three cases, I was relying on the old default `performResize` behavior.

But based on your data, it seems I may be an outlier.

[the remark this answers is not in the document]
Comment (tvolkert) [reply packages/flutter/lib/src/rendering/box.dart:2304]: Side-note: once my app's done (and I write tests), I plan to add them to the customer tests 🙂
