### PR TITLE
Properly lay out and position RenderWebImage

### LINKED ISSUE #163288: The image aspect ratio is distorted when using the webHtmlElementStrategy property.
### Steps to reproduce

The aspect ratio is distorted when using the prefer value for the webHtmlElementStrategy property in Stack > Positioned.fill > Image.network.

Please run the code sample in [DartPad](https://dartpad.dev/?channel=beta).

### Expected results

Images with correct aspect ratio.

### Actual results

Images with distorted aspect ratio.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(title: Text('Broken Images')),
        body: Center(child: BrokenImages()),
      ),
    );
  }
}

class BrokenImages extends StatelessWidget {
  const BrokenImages({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        ...locations
            .map((item) => ImageItem(imageUrl: item.imageUrl, name: item.name))
            .expand((item) => [item, SizedBox(height: 12)]),
      ],
    );
  }
}

class ImageItem extends StatelessWidget {
  const ImageItem({super.key, required this.imageUrl, required this.name});

  final String imageUrl;
  final String name;

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: 9 / 16,
      child: Stack(
        children: [
          Positioned.fill(
            child: Image.network(
              imageUrl,
              fit: BoxFit.cover,
              webHtmlElementStrategy: WebHtmlElementStrategy.prefer,
            ),
          ),
          Positioned(
            left: 16,
            top: 24,
            child: Text(
              style: Theme.of(
                context,
              ).textTheme.headlineMedium?.copyWith(color: Colors.white),
              name,
            ),
          ),
        ],
      ),
    );
  }
}

class Location {
  const Location({
    required this.name,
    required this.place,
    required this.imageUrl,
  });

  final String name;
  final String place;
  final String imageUrl;
}

const urlPrefix =
    'https://docs.flutter.dev/cookbook/img-files/effects/parallax';
const locations = [
  Location(
    name: 'Mount Rushmore',
    place: 'U.S.A',
    imageUrl: '$urlPrefix/01-mount-rushmore.jpg',
  ),
  Location(
    name: 'Gardens By The Bay',
    place: 'Singapore',
    imageUrl: '$urlPrefix/02-singapore.jpg',
  ),
  Location(
    name: 'Machu Picchu',
    place: 'Peru',
    imageUrl: '$urlPrefix/03-machu-picchu.jpg',
  ),
  Location(
    name: 'Vitznau',
    place: 'Switzerland',
    imageUrl: '$urlPrefix/04-vitznau.jpg',
  ),
  Location(
    name: 'Bali',
    place: 'Indonesia',
    imageUrl: '$urlPrefix/05-bali.jpg',
  ),
  Location(
    name: 'Mexico City',
    place: 'Mexico',
    imageUrl: '$urlPrefix/06-mexico-city.jpg',
  ),
  Location(name: 'Cairo', place: 'Egypt', imageUrl: '$urlPrefix/07-cairo.jpg'),
];

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [Flutter__ImgElementImage__] may not be set. Defaulting to `width: 100%`.

Set `style.width` to any appropriate value to stop this message.
Height of Platform View type: [Flutter__ImgElementImage__] may not be set. Defaulting to `height: 100%`.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.2 24C101 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

### LINKED ISSUE #164405: [Web] image is cached with webHtmlElementStrategy
### Steps to reproduce

Create an Image.newtork with WebHtmlElementStrategy.prefer
Add another Image.newtork, with same url as the image before, but with WebHtmlElementStrategy.never

### Expected results

The second image should not use the HTML element

### Actual results

The second image use the HTML element

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('HTML'),
            SizedBox(
              width: 200,
              height: 100,
              child: Image.network(
                'https://docs.flutter.dev/cookbook/img-files/effects/parallax/01-mount-rushmore.jpg',
                webHtmlElementStrategy: WebHtmlElementStrategy.prefer,
              ),
            ),
            const SizedBox(height: 100),
            Text('NOT HTML'),
            const SizedBox(height: 50),
            SizedBox(
              width: 200,
              height: 100,
              child: Image.network(
                'https://docs.flutter.dev/cookbook/img-files/effects/parallax/01-mount-rushmore.jpg',
                webHtmlElementStrategy: WebHtmlElementStrategy.never,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 29a2f674ca2312e34a3ef796701c297dc3be1ae6...
Expanding downloaded archive with PowerShell...
Building flutter tool...
Running pub upgrade...
Resolving dependencies... (1.1s)
Downloading packages...
Got dependencies.
Downloading package sky_engine...                                  979ms
Downloading package flutter_gpu...                                 204ms
Downloading flutter_patched_sdk tools...                           918ms
Downloading flutter_patched_sdk_product tools...                   905ms
Downloading windows-x64 tools...                                    4,1s
Downloading windows-x64/font-subset tools...                       945ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.30.0-0.1.pre, on Microsoft Windows [Versione 10.0.26100.3194], locale it-IT)
[✓] Windows Version (11 Home 64-bit, 24H2, 2009)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.7)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by harryterkelsen**
Fixes https://github.com/flutter/flutter/issues/163288
Fixes https://github.com/flutter/flutter/issues/164405

The previous behavior of `RenderWebImage` for layout and positioning did not work for all values of `BoxFit` and `AlignmentGeometry`. This PR gets `RenderWebImage` to properly lay out and offset its child (the `` element).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/_web_image_web.dart [hunk 1]
```diff
@@ -350,19 +350,90 @@ class RenderWebImage extends RenderShiftedBox {
...
+      // Now that the child has been sized, it must also be offset by an
+      // appropriate amount so that the specified portion of the image is shown
+      // in the destination box. `Alignment.inscribe` gives the sub-rectangle
+      // of source size that will be shown in the destination box. Again, the
+      // source and destination box have the same aspect ratio, so to compute
+      // the offset for the child, first compute the offset that the original
+      // sized image would need to put the sub-rectangle given by
+      // `Alignment.inscribe` at the origin, and then scale that offset by the
+      // same scale computed above to get the offset for the child.
+      final Rect sourceRect = _resolvedAlignment!.inscribe(sourceSize, Offset.zero & inputSize);
```
Comment (mdebbar) [inline packages/flutter/lib/src/widgets/_web_image_web.dart:424]: We are not taking into account `_flipHorizontally` here?

File: packages/flutter/lib/src/widgets/_web_image_web.dart [hunk 2]
```diff
@@ -350,19 +350,90 @@ class RenderWebImage extends RenderShiftedBox {
...
+  @override
+  void paint(PaintingContext context, Offset offset) {
+    if (child == null) {
+      return;
+    }
+    final Size inputSize = Size(image.naturalWidth.toDouble(), image.naturalHeight.toDouble());
+    fit ??= BoxFit.scaleDown;
+    final FittedSizes fittedSizes = applyBoxFit(fit!, inputSize, size);
+    final Rect destinationRect = offset & fittedSizes.destination;
+    context.pushClipRect(needsCompositing, offset, destinationRect, super.paint);
```
Comment (mdebbar) [inline packages/flutter/lib/src/widgets/_web_image_web.dart]: I feel like we are applying the `offset` twice, aren't we?

`pushClipRect` also shifts the rect by the given offset:
https://github.com/flutter/flutter/blob/43657f3baa17bc1df6cc15da8b0fea2290c2c4fd/packages/flutter/lib/src/rendering/object.dart#L566

Comment (harryterkelsen) [reply packages/flutter/lib/src/widgets/_web_image_web.dart]: Good catch! I fixed this.

File: packages/flutter/lib/src/widgets/_web_image_web.dart (hunk 1 above)
Comment (harryterkelsen) [reply packages/flutter/lib/src/widgets/_web_image_web.dart:424]: `matchTextDirection` support isn't implemented yet. I'll file an issue for it

**Comment by harryterkelsen** [comment]
Thanks! I made a more robust example app to work out issues in the implementation. Everything seems to work correctly now:

https://github.com/user-attachments/assets/b029fd8e-d535-4027-9768-e9c7d147edb0

**Comment by harryterkelsen** [comment]
This breaks a customer test which depends on `NetworkImage.toString()`. I updated `NetworkImage.toString()` to show the values for `webHtmlElementStrategy` and `headers` since those are used in `==` so I think they should be in the `toString()`

I have a fix here: https://github.com/flutter/packages/pull/9590

Once it lands I'll update the customer_tests

**Comment by harryterkelsen** [comment]
flutter/packages [PR](https://github.com/flutter/packages/pull/9590) has landed. Now waiting for the flutter/tests [PR](https://github.com/flutter/tests/pull/463) to land so I can update the tests.version

**Review by mdebbar — APPROVED** [review]
LGTM
