### PR TITLE
Space and arrow keys in a text field shouldn't scroll

### LINKED ISSUE #74191: [web] space key scrolls entire page, even if typing in textfield
## Steps to Reproduce
flutter run web  --web-renderer html

1. Run flutter web with html
2. Create a scrollable list (e.g. ListView and a textfield)
3. Type a spacebar in the textfield and the entire page will scroll down

**Expected results:** 
If a textfield is in focus, the page shouldn't scroll.
**Actual results:** 
The page scrolled when the spacebar was hit even though the textfield was in focus
<details>
  <summary>Logs</summary>

```
```

```
```

```
```
[√] Flutter (Channel dev, 1.26.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-8.0.pre at C:\Users\Devan\Downloads\flutter_windows_1.17.5-stable\flutter
    • Framework revision b9d06fffb2 (10 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Devan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

</details>

### PR DESCRIPTION
**Pull request by mdebbar**
Key handling in `RenderEditable` doesn't play well with the shortcuts system. While a text field is focused, certain keys that are consumed by the text field, are still passed all the way up to the `Shortcuts` widget.

On the web, this is causing the space key to add a space to the text field (expected) and at the same time trigger a scroll intent (unexpected).

Once key handling in `RenderEditable` is refactored to use the new shortcut system, this problem will go away. But for now, we need a temporary solution, which is implemented in this PR.

Fixes https://github.com/flutter/flutter/issues/74191

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -53,6 +55,19 @@ const Duration _kCursorBlinkWaitForStart = Duration(milliseconds: 150);
 // is shown in an obscured text field.
 const int _kObscureShowLatestCharCursorTicks = 3;
 
+/// A map used to disable scrolling shortcuts in text fields.
+///
+/// This is a temporary fix for: https://github.com/flutter/flutter/issues/74191
+final Map<LogicalKeySet, Intent> scrollShortcutOverrides = kIsWeb
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/editable_text.dart:61]: It would be nicer if this could be a private value, rather than a public API. Reducing code duplication probably wins out, but here's another case where I wish Dart had package-private values.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (mdebbar) [reply packages/flutter/lib/src/widgets/editable_text.dart:61]: It's possible to hide this map by putting it in a new file that's not exported in `widgets.dart`. But my understanding is that's against Flutter's policy of exporting everything.
