### PR TITLE
Fix update order of SliverAppBar

### LINKED ISSUE #158158: TabBar crash with SliverAppBar
### Steps to reproduce

1. Run example codes.
2. Tap the top button to add a tab.

### Expected results

No crash.

### Actual results

Crashed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  final List<Tab> tabs = <Tab>[];
  runApp(MaterialApp(
    home: StatefulBuilder(
      builder: (BuildContext context, StateSetter setState) {
        return DefaultTabController(
          length: tabs.length,
          child: Scaffold(
            body: CustomScrollView(
              slivers: <Widget>[
                SliverAppBar(
                  actions: <Widget>[
                    TextButton(
                      child: const Text('Add Tab'),
                      onPressed: () {
                        setState(() {
                          tabs.add(Tab(text: 'Tab ${tabs.length + 1}'));
                        });
                      },
                    ),
                  ],
                  bottom: TabBar(tabs: tabs),
                ),
              ],
            ),
          ),
        );
      },
    ),
  ));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TabBar(dirty, dependencies: [InheritedCupertinoTheme, MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#ea041], _TabControllerScope], state: _TabBarState#f6f77):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  Column Column:file:///D:/Flutter/packages/flutter/lib/src/material/app_bar.dart:1101:16
When the exception was thrown, this was the stack: 
#0      List._setIndexed (dart:core-patch/growable_array.dart:274:49)
#1      List.[]= (dart:core-patch/growable_array.dart:269:5)
#2      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1752:21)
#3      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#4      _TabBarState.build (package:flutter/src/material/tabs.dart:1741:38)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5748:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5636:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5799:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#9      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#10     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2753:11)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1176:21)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#17     _invoke (dart:ui/hooks.dart:312:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
#19     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.27.0-1.0.pre.348 • channel [user-branch] • unknown source
Framework • revision 8ce47b6cb1 (20 hours ago) • 2024-11-04 20:26:49 +0800
Engine • revision 05cb5d7f79
Tools • Dart 3.7.0 (build 3.7.0-95.0.dev) • DevTools 2.40.1
```

</details>

### PR DESCRIPTION
**Pull request by hgraceb**
Fixes #158158

Similar to 154484, but addressing more fundamental causes. We should call the child's `didUpdateWidget` before the child's `build` when states change.

1. Remove redundant code but keep the old test because we don't need it after this fix.
2. Add getters of `lastShrinkOffset` and `lastOverlapsContent` that are needed when `SliverAppBar.update`.
3. Add a test with a custom TabBar to avoid breaking when some changes to the default TabBar.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/app_bar_sliver_test.dart [hunk 1]
```diff
@@ -2274,6 +2322,53 @@ void main() {
...
+                        TextButton(
+                          child: const Text('Add Tab'),
+                          onPressed: () {
+                            setState(() {
+                              tabs.add(Tab(text: 'Tab ${tabs.length + 1}'));
+                            });
+                          },
+                        ),
+                      ],
+                      bottom: _TestLifecycleTabBar(tabs: tabs),
```
Comment (nate-thegrate) [inline packages/flutter/test/material/app_bar_sliver_test.dart:2349]: One of our [style guidelines](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#make-each-test-entirely-self-contained) is "make each test entirely self-contained".

It's primarily for preventing accidental shared state between tests, but there are a few other reasons why we might want to factor out the `_TestLifecycleTabBar` class:

- If we can avoid declaring a private class at the top of the file that's only used for one test, it will make this library easier to understand & navigate.
- Tests are easier to debug when the failure is found in an `expect()` call, rather than an `assert` in a widget's build method.
- It'd be nice to test the `TabBar` widget, since that's what will most likely be used in the real world.

<br>

<details> <summary>Here's an idea for how we might restructure this test!</summary>

```dart
  // Regression test for https://github.com/flutter/flutter/issues/158158.
  testWidgets('SliverAppBar should update child before child build', (WidgetTester tester) async {
    List<Tab> tabs = <Tab>[];
    late StateSetter setState;
    late TabController controller;
    bool customTabBar = false;

    PreferredSizeWidget tabBar() {
      if (customTabBar) {
        return PreferredSize(
          preferredSize: const Size.fromHeight(kToolbarHeight),
          child: Builder(
            builder: (BuildContext context) {
              controller = DefaultTabController.of(context);
              return Row(children: tabs);
            },
          ),
        );
      }
      return TabBar(tabs: tabs);
    }

    await tester.pumpWidget(
      MaterialApp(
        home: StatefulBuilder(
          builder: (BuildContext context, StateSetter stateSetter) {
            setState = stateSetter;

            // Reset this widget's state when switching to a different TabBar.
            final Key key = ValueKey<bool>(customTabBar);
            return DefaultTabController(
              key: key,
              length: tabs.length,
              child: Scaffold(
                body: CustomScrollView(
                  slivers: <Widget>[
                    SliverAppBar(
                      actions: <Widget>[
                        TextButton(
                          child: const Text('Add Tab'),
                          onPressed: () {
                            setState(() {
                              tabs.add(Tab(text: 'Tab ${tabs.length + 1}'));
                            });
                          },
                        ),
                      ],
                      bottom: tabBar(),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );

    // Initializes with zero tabs.
    expect(find.text('Tab 1'), findsNothing);
    expect(find.text('Tab 2'), findsNothing);

    await tester.tap(find.text('Add Tab'));
    await tester.pumpAndSettle();

    // No crash after tab is added.
    expect(find.text('Tab 1'), findsOneWidget);
    expect(find.text('Tab 2'), findsNothing);

    setState(() {
      tabs = <Tab>[];
      customTabBar = true;
    });

    await tester.pumpAndSettle();

    // Initializes with zero tabs.
    expect(tester.takeException(), isNull);
    expect(find.text('Tab 1'), findsNothing);
    expect(find.text('Tab 2'), findsNothing);
    expect(controller.length, tabs.length);

    await tester.tap(find.text('Add Tab'));
    await tester.pumpAndSettle();
    
    // No crash after tab is added.
    expect(tester.takeException(), isNull);
    expect(find.text('Tab 1'), findsOneWidget);
    expect(find.text('Tab 2'), findsNothing);
    expect(controller.length, tabs.length);
  });
```

</details>

**Review by nate-thegrate — COMMENTED** [review]
@hgraceb thanks for the contribution!

The bug fix LGTM; I left some feedback on the test.

File: packages/flutter/test/material/app_bar_sliver_test.dart (hunk 1 above)
Comment (hgraceb) [reply packages/flutter/test/material/app_bar_sliver_test.dart:2349]: @nate-thegrate Thanks for your suggestions for the test. I tried it, but I don't know how to improve it continue.

1. Maybe we should take the exception check here.

```diff
 // No crash after tab is added.
 expect(find.text('Tab 1'), findsOneWidget);
 expect(find.text('Tab 2'), findsNothing);
+expect(tester.takeException(), isNull);

 setState(() {
   tabs = <Tab>[];
   customTabBar = true;
 });
```

2. The custom `TabBar` is declared top-level because the core reason for the issue is that `TabBar`'s lifecycle should be changed.  Actually, includes a called `DefaultTabController.of(context)` there are other necessary steps to reproduce it. We should update the tab's count in `didUpdateWidget` otherwise it's always equal.

```dart
expect(tester.takeException(), isNull);
expect(find.text('Tab 1'), findsOneWidget);
expect(find.text('Tab 2'), findsNothing);
expect(controller.length, tabs.length); // Always passed even has not current fix.
```

3. By the way. Should I offer more information on the issue somewhere? I was written some short descriptions in this PR on the top. Maybe like following are better.

Before:

```dart
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.didUpdateWidget: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 1 // Crashed here.
flutter: _TestLifecycleTabBar.didUpdateWidget: _tabs = 1, widget.tabs.length = 1
flutter: _TestLifecycleTabBar.build: _tabs = 1, widget.tabs.length = 1
```

After:

```dart
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.didUpdateWidget: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.build: _tabs = 0, widget.tabs.length = 0
flutter: _TestLifecycleTabBar.didUpdateWidget: _tabs = 1, widget.tabs.length = 1 // Update `_tabs` before `build`.
flutter: _TestLifecycleTabBar.build: _tabs = 1, widget.tabs.length = 1
```

Comment (nate-thegrate) [reply packages/flutter/test/material/app_bar_sliver_test.dart:2349]: Thanks for following up on this—and sorry for the delay, it's been a busy week!

In my personal opinion: it's probably not necessary to compare `controller.length` with `tabs.length`.
But I'm open to hearing other perspectives :)

<br>

> 1. Maybe we should take the exception check here.
> 
> ```diff
>  // No crash after tab is added.
>  expect(find.text('Tab 1'), findsOneWidget);
>  expect(find.text('Tab 2'), findsNothing);
> +expect(tester.takeException(), isNull);
> 
>  setState(() {
>    tabs = <Tab>[];
>    customTabBar = true;
>  });
> ```

Absolutely—I totally missed that, thanks!

Comment (hgraceb) [reply packages/flutter/test/material/app_bar_sliver_test.dart]: @nate-thegrate If unnecessary to compare controller.length with tabs.length, the custom TabBar is also unnecessary. So I removed it and just kept TabBar for the test.

**Review by nate-thegrate — APPROVED** [review]
Flutter_LGTM

Thanks for the fix!

File: packages/flutter/lib/src/widgets/sliver_persistent_header.dart [hunk 2]
```diff
@@ -286,7 +286,8 @@ class _SliverPersistentHeaderElement extends RenderObjectElement {
     final SliverPersistentHeaderDelegate oldDelegate = oldWidget.delegate;
     if (newDelegate != oldDelegate &&
         (newDelegate.runtimeType != oldDelegate.runtimeType || newDelegate.shouldRebuild(oldDelegate))) {
-      renderObject.triggerRebuild();
+      final _RenderSliverPersistentHeaderForWidgetsMixin renderObject = this.renderObject;
+      _updateChild(newDelegate, renderObject.lastShrinkOffset, renderObject.lastOverlapsContent);
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]: This change might be causing some google testing failures with the SliverPersistentHeader having a smaller size/length and thus clipping content. Any ideas as to why/how to fix?

Comment (hgraceb) [reply packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]: @victorsanni Hi, can you provide more information about the error, such as test code, widget code, or something else?

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]: Still investigating on my end. But in the meantime I wonder if there are any edge cases that might have been missed in this refactor.

Comment (hgraceb) [reply packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]: Sorry, but I have no idea. But maybe we should call `markNeedsLayout` when `_SliverPersistentHeaderElement.update` because only there has changed? In fact, I don't understand what content clipping means.

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]:
```suggestion
      final _RenderSliverPersistentHeaderForWidgetsMixin renderObject = this.renderObject;
      _updateChild(newDelegate, renderObject.lastShrinkOffset, renderObject.lastOverlapsContent);
      renderObject.triggerRebuild();
```
This should fix the google testing failures. As you said, we should call `markNeedsLayout` in `_SliverPersistentHeaderElement.update`. I wonder if we can add a test.

Comment (hgraceb) [reply packages/flutter/lib/src/widgets/sliver_persistent_header.dart:290]: I want to add a test but I don't know what situation will need it. And there may be another deeper reason. I'll try to fix it and add a test if there are details.

**Review by victorsanni — APPROVED** [review]
LGTM pending review from someone more knowledgeable about SliverAppBar such as @Piinks.

**Review by Piinks — APPROVED** [review]
LGTM!
