### PR TITLE
Handle case of a connected unpaired iOS device

### LINKED ISSUE #36789: "flutter doctor" crashes if there is an iphone attached that hasn't 'trusted' the computer
Steps to reproduce: 
1) Get a device that hasn't 'trusted' your computer (the popup on new devices that asks if you trust the computer).
2) Run `flutter doctor`, notice the crash

```
aaclarke-macbookpro2:myapp aaclarke$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.2-pre.158, on Mac OS X 10.14.5 18F132, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

⢿ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17
```

### LINKED ISSUE #37000: Cannot run after upgrade
Cannot run the project after upgrage my flutter! getting below error:(

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-MY)
⣻ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -2

### PR DESCRIPTION
**Pull request by tvolkert**
## Description

`ideviceinfo` fails with "ERROR: Could not connect to lockdownd" when the physical device is not paired. This change handles that case.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/36789
Fixes https://github.com/flutter/flutter/issues/37000

https://github.com/flutter/flutter/issues/36524
https://github.com/flutter/flutter/issues/24600

## Tests

I added the following tests:

* A test in `mac_test.dart` to replicate the scenario

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -185,6 +185,8 @@ class IOSDevice extends Device {
       } on IOSDeviceNotFoundError catch (error) {
         // Unable to find device with given udid. Possibly a network device.
         printTrace('Error getting attached iOS device: $error');
+      } on IOSDeviceNotTrustedError catch (error) {
+        printTrace('Error getting attached iOS device information: $error');
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/ios/devices.dart]: @zanderso would we want to send an analytics event here so that if we see a spike in untrusted events, we know something's gone wrong?

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -160,6 +171,8 @@ class IMobileDevice {
       );
       if (result.exitCode == 255 && result.stdout != null && result.stdout.contains('No device found'))
         throw IOSDeviceNotFoundError('ideviceinfo could not find device:\n${result.stdout}');
+      if (result.exitCode == 255 && result.stderr != null && result.stderr.contains('Could not connect to lockdownd'))
+        throw IOSDeviceNotTrustedError('Device info unavailable until the user selects "Trust This Computer" on the device (${result.stderr.trim()})');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/mac.dart]: The problem with this is that there are other cases where ideviceinfo would return "Could not connect to lockdownd" that may require different action...i.e. the error code is not irrelevant. See this long enum: https://github.com/libimobiledevice/libimobiledevice/blob/26373b334889f5ae2e2737ff447eb25b1700fa2f/include/libimobiledevice/lockdown.h#L59

These non-"Trust This Computer" cases seem rare for flutter developers, but I wasn't sure if we should just bucket them ALL together.

Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/mac.dart]: How would a different sort of message sound? Like:
'Device info unavailable. Is the device asking to "Trust this Computer"?'

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 1 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/devices.dart]: Yes, that would be a good signal to generate. Maybe something like `UsageEvent('device', 'ios-trust-failure').send();`

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 3]
```diff
@@ -160,6 +171,8 @@ class IMobileDevice {
       );
       if (result.exitCode == 255 && result.stdout != null && result.stdout.contains('No device found'))
         throw IOSDeviceNotFoundError('ideviceinfo could not find device:\n${result.stdout}');
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart]: I bet the "could not find device" error became more common once iOS 11.4.1 introduced USB restriction mode, which hides the phone as a mux device when it's plugged in but not unlocked.
If you're going to add 'Is the device asking to "Trust this Computer"' you may want to add 'Try unlocking any attached devices.'  I'm also cool adding this change myself in another PR if it's out of scope.

Comment (tvolkert) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Right now, the user only sees the message if they run `flutter -v doctor -v`, and it's buried in a ton of output.  What I'd _really_ like is for us to return a device in their device list that shows as a "not yet ready to use" device, with more info.  Right now, doctor doesn't have that ability.  I think that can be a follow-up change.  In the meantime, I'll update the verbiage of this message.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/mac.dart]: I actually have a draft of that https://github.com/flutter/flutter/pull/36902/files which was getting complicated so I put it on the backburner. I will rebase that on this change. Also, feel free to take this up also, if you feel so inclined.

**Comment by tvolkert** [comment]
Ok, comments addressed.  PTAL

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 4]
```diff
@@ -160,6 +210,20 @@ class IMobileDevice {
...
+      if (result.exitCode == 255 && result.stderr != null && result.stderr.contains('Could not connect to lockdownd')) {
+        if (result.stderr.contains('error code -${LockdownReturnCode.pairingDialogResponsePending.code}')) {
+          throw const IOSDeviceNotTrustedError(
+            'Device info unavailable. Is the device asking to "Trust This Computer?" Try unlocking attached devices.',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Sorry, with "Try unlocking attached devices" comment I meant to put it in the "ideviceinfo could not find device" error message above because the locked attached device's mux doesn't show up (they look like dumb USB devices like a keyboard).

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Hm, or maybe it would show up as LOCKDOWN_E_MUX_ERROR =  -8.  I honestly haven't tested it.
What you had before is fine.

Comment (tvolkert) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated

**Review by jmagman — APPROVED** [review]
thank_you_sparkle
