### PR TITLE
Fix to the tab height (Issue #81500)

### LINKED ISSUE #81500: Make Tab bar height customizable
My Tab widget is overflowing on bigger screens because when i dynamically change the icon and label size they are bigger than the tab max size.

Searching on the flutter files i've found this constant on tabs.dart file:

`const double _kTextAndIconTabHeight = 72.0; `

changing it to 100 solved my problem but like it isn't the best option for all cases i suggest adding another parameter to the Tab class so the dev can replace this constant size (default value could be 72 as it is today).

With the default value:
image

 

The widget with the new 100 value: 
image

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.3.0-1.0.pre.170, on Microsoft Windows [versÃ£o 10.0.19042.928], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by Macacoazul01**
*This PR adds the height parameter to the tab bar, fixing the overflow when the icon + child widgets height (or other combination) is greater than 72*

*This PR fixes #81500*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Macacoazul01** [comment]
This PR it's ready for a review @Hixie.

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -70,6 +69,7 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
     this.text,
     this.icon,
     this.iconMargin = const EdgeInsets.only(bottom: 10.0),
+    this.kTextAndIconTabHeight = 72,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:72]: I am not sure I understand this parameter, what is this to mean? the `k` usually indicates a constant in the framework, so exposing it as a parameter is probably not what we want here.

**Review by Piinks — COMMENTED** [review]
Hi @Macacoazul01 welcome! :tada: And thank you for the contribution!
It looks like a couple of folks are already working on this in https://github.com/flutter/flutter/pull/75460 and https://github.com/flutter/flutter/pull/80237

File: packages/flutter/lib/src/material/tabs.dart (hunk 1 above)
Comment (Macacoazul01) [reply packages/flutter/lib/src/material/tabs.dart]: @Piinks changed both the file and the test

File: packages/flutter/lib/src/material/tabs.dart [hunk 2]
```diff
@@ -24,7 +24,6 @@ import 'tab_indicator.dart';
 import 'theme.dart';
 
 const double _kTabHeight = 46.0;
-const double _kTextAndIconTabHeight = 72.0;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:27]: We should keep this.

File: packages/flutter/lib/src/material/tabs.dart [hunk 3]
```diff
@@ -70,6 +69,7 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
     this.text,
     this.icon,
     this.iconMargin = const EdgeInsets.only(bottom: 10.0),
+    this.TextAndIconTabHeight = 72,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:72]: Is this meant to only work when there is a an icon & text in the tab? What if the user wants a custom height with just Text? Or just an Icon?

File: packages/flutter/test/material/tabs_test.dart [hunk 4]
```diff
@@ -3531,6 +3531,31 @@ void main() {
     final TabBar tabBar = tester.widget(find.widgetWithText(TabBar, 'car'));
 
     expect(tabBar.preferredSize, const Size.fromHeight(48.0));
+  });
+
+	testWidgets('Correct size for tab bar with child', (WidgetTester tester) async {
+    // Build our app and trigger a frame.
```
Comment (Piinks) [inline packages/flutter/test/material/tabs_test.dart:3537]: What is this comment for?

File: packages/flutter/test/material/tabs_test.dart [hunk 5]
```diff
@@ -3531,6 +3531,31 @@ void main() {
     final TabBar tabBar = tester.widget(find.widgetWithText(TabBar, 'car'));
 
     expect(tabBar.preferredSize, const Size.fromHeight(48.0));
+  });
+
+	testWidgets('Correct size for tab bar with child', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/material/tabs_test.dart:3536]: I think there are some formatting issues here. Please check out [the style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) for guidance. :)

File: packages/flutter/lib/src/material/tabs.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/tabs.dart:72]: Parameters should also start with a lowercase letter.

**Comment by Piinks** [comment]
@HansMuller is there a preference here for maintaining MaterialDesign spec over allowing customization of Tab sizing?

File: packages/flutter/lib/src/material/tabs.dart (hunk 3 above)
Comment (Macacoazul01) [reply packages/flutter/lib/src/material/tabs.dart:72]: sorry
i've forgotten to change the "T" to "t" after removed the "k"

**Comment by Macacoazul01** [comment]
@Piinks this windows test error is from the code or the windows tests are still broken?

**Comment by Piinks** [comment]
I think updating your branch with the latest from master should resolve the issue. :)

**Comment by Macacoazul01** [comment]
it worked

File: packages/flutter/lib/src/material/tabs.dart [hunk 6]
```diff
@@ -96,6 +97,11 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
   /// [text] or [child] is non-null.
   final EdgeInsetsGeometry iconMargin;
 
+  /// The widget height when there is an icon and text
+  ///
+  /// Useful when the combination of both overflows the default height
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:102]: Why make this only specific to one use case? If we are going to expose a `height` setting, it should apply for all configurations.

File: packages/flutter/test/material/tabs_test.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/test/material/tabs_test.dart:3537]: This can be removed, although it's common for folks to put a comment like
```dart
// Regression test for <github-issue-link>
```

**Review by Piinks — COMMENTED** [review]
It looks like some of those related changes landed and this will need to be updated to resolve merge conflicts.

**Comment by Macacoazul01** [comment]
@Hixie everything updated to be on pair with the last master

File: packages/flutter/lib/src/material/tabs.dart [hunk 7]
```diff
@@ -145,10 +153,14 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
...
-      return const Size.fromHeight(_kTextAndIconTabHeight);
+    final double tabHeight;
+    if (height != null)
+      tabHeight = height!;
+    else if ((text != null || child != null) && icon != null)
+      tabHeight = _kTextAndIconTabHeight;
     else
-      return const Size.fromHeight(_kTabHeight);
+      tabHeight = _kTabHeight;
+    return Size.fromHeight(tabHeight);
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:163]: You could just make the height != null an early return for simplicity.

File: packages/flutter/lib/src/material/tabs.dart [hunk 8]
```diff
@@ -104,16 +112,16 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
   Widget build(BuildContext context) {
     assert(debugCheckHasMaterial(context));
 
-    final double height;
+    final double tabHeight;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:115]: To remove some redundant code here, you could leave it as is here with a new name
```suggestion
    final double calculatedHeight;
```

File: packages/flutter/lib/src/material/tabs.dart [hunk 9]
```diff
@@ -128,7 +136,7 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
     }
 
     return SizedBox(
-      height: height,
+      height: tabHeight,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:139]: And then just make your check here once.
```suggestion
      height: height ?? calculatedHeight,
```

File: packages/flutter/lib/src/material/tabs.dart [hunk 10]
```diff
@@ -96,6 +97,13 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
   /// [text] or [child] is non-null.
   final EdgeInsetsGeometry iconMargin;
 
+  /// The widget height when the user defines it
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:100]:
```suggestion
  /// The height of the [Tab].
```

File: packages/flutter/lib/src/material/tabs.dart [hunk 11]
```diff
@@ -96,6 +97,13 @@ class Tab extends StatelessWidget implements PreferredSizeWidget{
...
+  ///
+  /// if null it will be used the _kTextAndIconTabHeight constant if there is
+  ///
+  /// an [icon] and [text] or [icon] and [child], or _kTabHeight for other cases.
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:104]:
```suggestion
  /// If null, the height will be calculated based on the content of the [Tab].  When `icon` is not
  /// null along with `child` or `text`, the default height is 72.0 pixels. Without an `icon`, the 
  /// height is 46.0 pixels.
```

File: packages/flutter/lib/src/material/tabs.dart (hunk 7 above)
Comment (Macacoazul01) [reply packages/flutter/lib/src/material/tabs.dart:163]: Done

**Comment by Macacoazul01** [comment]
@Piinks changes and tests added

**Comment by Macacoazul01** [comment]
@HansMuller is anything missing?

**Comment by Macacoazul01** [comment]
1 month anniversary \o/

**Review by Piinks — APPROVED** [review]
LGTM! Thank you for the contribution! 🎉
