### PR TITLE
Hide default bundle id error when xcresult detects an error

### LINKED ISSUE #100723: Xcode build failures are not printed when codesigning is off
https://github.com/flutter/flutter/pull/94747 parsed the xcresult bundle and printed the errors from Xcode when the build fails.  However, that output is not printed when there are other issues detected.

For example, this [test has a build failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818937356027197105/+/u/run_module_test_ios/test_stdout
), but it's not printing the Xcode error because it's falling through here:
https://github.com/flutter/flutter/blob/b53ed9ba4a54ce009571647d258f1395989175aa/packages/flutter_tools/lib/src/ios/mac.dart#L611-L614

Instead, the xcresult errors should be moved to the top of `diagnoseXcodeBuildFailure` so it's always printed.

### PR DESCRIPTION
**Pull request by cyanglaz**
This PR make sure the default bundle id error only shows when xcresult doesn't detect errors.

Fixes https://github.com/flutter/flutter/issues/100723

sample output:

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/8b/jd2fgk_51k3bv218hf4v5cd800l9tg/T/flutter_tools.tIgW0p/flutter_ios_build_temp_dirUl1liT/tem
        porary_xcresult_bundle

    /Users/ychris/tmp/keyboard_inset_tests/ios/Runner/AppDelegate.swift:8:83: error: cannot find type 'Any1' in
    scope
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any1]?
                                                                                      ^~~~
    /Users/ychris/tmp/keyboard_inset_tests/ios/Runner/AppDelegate.swift:6:17: error: method does not override
    any method from its superclass
      override func application(
      ~~~~~~~~      ^
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

    Result bundle written to path:
        /var/folders/8b/jd2fgk_51k3bv218hf4v5cd800l9tg/T/flutter_tools.tIgW0p/flutter_ios_build_temp_dirUl1liT/tem
        porary_xcresult_bundle


Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Cannot find type 'Any1' in scope
/Users/ychris/tmp/keyboard_inset_tests/ios/Runner/AppDelegate.swift:7:82


Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/ychris/tmp/keyboard_inset_tests/ios/Runner/AppDelegate.swift:5:16



Error launching application on iPhone.

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM, thanks!

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -757,6 +747,14 @@ bool _handleIssues(XCResult? xcResult, Logger logger, XcodeBuildExecution? xcode
     logger.printError('');
     logger.printError("Also try selecting 'Product > Build' to fix the problem.");
   }
+
+  if (!issueDetected && _needUpdateSigningIdentifier(xcodeBuildExecution)) {
+    issueDetected = true;
+    logger.printError('');
+    logger.printError('It appears that your application still contains the default signing identifier.');
```
Comment (blasten) [inline packages/flutter_tools/lib/src/ios/mac.dart:754]: could use `logger.printBox` for consistency with Android
