### PR TITLE
[flutter_tools] tool exit after repeated network failure

### LINKED ISSUE #64857: [tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2
## Command
flutter upgrade
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. flutter upgrade

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:333:59)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:651:16)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:795:13)
<asynchronous suspension>
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
<asynchronous suspension>
#13     PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:171:20)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#22     _rootRun (dart:async/zone.dart:1190:13)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Taneesha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: E:\Android St\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\Android St
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taneesha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.


How can this be fixed?

### LINKED ISSUE #64876: [tool_crash] ProcessException: The command failedStdout:Stderr:[/home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip]
```
End-of-central-directory signature not found.  Either this file is not  a zipfile, or it constitutes one disk of a multi-part archive.  In the  latter case the central directory and zipfile comment will be found on  the last disk(s) of this archive.unzip:  cannot find zipfile directory in one of /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip or        /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip.zip, and cannot find /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip.ZIP, period. Command: unzip, OS error code: 9
```
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
[/home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip or
        /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip.zip, and cannot find /home/ujjawal/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/3029dcd93ed4e02379c16c77543915f1b69c16ad/android-arm-profile/linux-x64.zip.ZIP, period

- most recent logs, during Flutter Upgrade via ```flutter updrade --force```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Exit the tool after a repeated network error to download. previously we were returning null and continuing on, leading to a ProcessException when we unzipped a missing file.

Fixes https://github.com/flutter/flutter/issues/64876
Fixes https://github.com/flutter/flutter/issues/64857

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Possibly https://github.com/flutter/flutter/issues/52437#event-3710566736 too

File: packages/flutter_tools/lib/src/base/net.dart [hunk 1]
```diff
@@ -70,7 +70,7 @@ class Net {
 
       if (maxAttempts != null && attempts >= maxAttempts) {
         _logger.printStatus('Download failed -- retry $attempts');
-        return null;
+        throw Exception('Failed to download $url');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/net.dart:73]: `_attempt` could return `null` on success, and the exception object on an error. Then here you can rethrow the most recent error. Then at the callsite, you can catch `IOException`, or something more narrow, since it doesn't look like the text `'Failed to download...'` is used there. The caller also presumably already knows what the url is.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/net.dart]: done?

File: packages/flutter_tools/lib/src/cache.dart [hunk 2]
```diff
@@ -1469,6 +1469,14 @@ class ArtifactUpdater {
       try {
         _ensureExists(tempFile.parent);
         await _net.fetchUrl(url, destFile: tempFile, maxAttempts: 2);
+      } on Exception {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/cache.dart:1472]: Ehhhh. Okay, sorry. Maybe that wasn't the best suggestion. If there's some way to avoid catching `Exception` here that would be good, though, since it's only the `IOExceptions` that probably indicate a network issue on the end-user's side.

File: packages/flutter_tools/lib/src/base/net.dart [hunk 3]
```diff
@@ -131,39 +132,36 @@ class Net {
...
     } on HttpException catch (error) {
       _logger.printTrace('Download error: $error');
-      return false;
+      return error;
     }
     assert(response != null);
 
+    if (response.statusCode != HttpStatus.ok) {
+      _logger.printTrace('Download error: ${response.statusCode} ${response.reasonPhrase}');
+      final Exception exception = Exception(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/net.dart:144]: Where did the `throwTooleExit` go?

File: packages/flutter_tools/lib/src/base/net.dart [hunk 4]
```diff
@@ -120,7 +121,7 @@ class Net {
           exitCode: kNetworkProblemExitCode,);
       }
       _logger.printError(error.toString());
-      rethrow;
+      return error;
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/net.dart:124]: Maybe these should all rethrow, `fetchUrl` can do a `try {} catch on IOException {}` with a `continue` in the `catch` if there are still attempts left? `doesRemoteFileExist` would also need a `try {} catch {}`, too, then I guess.

**Comment by jonahwilliams** [comment]
I think the net logic is quite convoluted actually, which is part of the issue with trying to update it. It's not really clear from the contract what sorts of exceptions it should be handling, and which ones to leave to the callers.

If I were going to spend some time on it, what I would do is more or less replace `Net` with a wrapper that accepted an http client and made the request. The only job would be to turn a non-200 response into an exception so that the caller could handle that in a similar way to other failures.

This would let the artifact updater contain the logic for writing the bytes, which would allow it to handle any IOexceptions from writing.

**Comment by jonahwilliams** [comment]
(also removing the retry logic, to allow the callers to include that if they wanted to)

**Review by zanderso — APPROVED** [review]
Were there any other users of `Net`?

Should the number of retries be wired up to method arguments or command line flags of e.g. precache?

**Comment by jonahwilliams** [comment]
There is some usage in create.dart (for snippet creation), update_packages for downloading coverage (which doesn't need to be that resilient), and then the cache check that artifacts exist.

As a follow up these could be refactored/removed. Likely we'll want to keep the cache check for existence (header only request) and find out how to remove the others.

**Comment by jonahwilliams** [comment]
I could hoist the retry count into a constant for now, and we could make it configurable if there is a feature request to do so
