### PR TITLE
[win32] Replace threadpool timer with custom background thread timer

### LINKED ISSUE #178916: Windows significant performance regression after update from 3.35.7 to 3.38.2
# Workaround

If your Flutter Windows application is affected by this issue, please update your `windows/runner/main.cpp` file:

```diff
  flutter::DartProject project(L"data");

+ // TODO: Remove this.
+ // This forces Flutter to use a separate thread for Dart.
+ // This mode will be removed in a future version of Flutter.
+ project.set_ui_thread_policy(flutter::UIThreadPolicy::RunOnSeparateThread);
```

This is a temporary workaround until we fix this issue. 

# Issue

FPS chart (from MSI Afterburner) shows that release version of the same flutter app works good on previous stable release and bad on new stable release.

https://github.com/user-attachments/assets/80cfe49b-d198-4694-a77b-4cc2110fd136

Old stable release: constant 120fps during animations
New stable release: up to 40fps during animations

Also, the task manager shows that overall GPU usage on new flutter version is x3-4 times lower then on previous stable version (for some reason flutter does not use all gpu power now and limits itself), while cpu usage is very low on both versions.

### flutter run -d windows --profile tests:
3.35.7:
Image

[dart_devtools_2025-11-21_11_59_04.351.json](https://github.com/user-attachments/files/23674190/dart_devtools_2025-11-21_11_59_04.351.json)

3.38.2:
Image

[dart_devtools_2025-11-21_12_07_01.041.json](https://github.com/user-attachments/files/23674328/dart_devtools_2025-11-21_12_07_01.041.json)

Issue is NOT linked to this specific code sample, i can reproduce it with any flutter app, but this is the code that was used to demonstrate regression

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: WindowsPerformanceDemo(),
  ));
}

class WindowsPerformanceDemo extends StatelessWidget {
  const WindowsPerformanceDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF0F2F5),
      body: Center(
        child: SizedBox(
          width: 1000,
          height: 600,
          child: GridView.builder(
            padding: const EdgeInsets.all(20),
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 4,
              crossAxisSpacing: 20,
              mainAxisSpacing: 20,
              childAspectRatio: 16 / 9,
            ),
            itemCount: 8,
            itemBuilder: (context, index) {
              return DesktopHoverCard(index: index);
            },
          ),
        ),
      ),
    );
  }
}

class DesktopHoverCard extends StatefulWidget {
  final int index;
  const DesktopHoverCard({super.key, required this.index});

  @override
  State<DesktopHoverCard> createState() => _DesktopHoverCardState();
}

class _DesktopHoverCardState extends State<DesktopHoverCard> {
  bool _isHovered = false;

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => setState(() => _isHovered = true),
      onExit: (_) => setState(() => _isHovered = false),

      cursor: SystemMouseCursors.click,
      child: AnimatedScale(
        scale: _isHovered ? 1.05 : 1.0,
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeOutCubic,
        child: Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(_isHovered ? 0.2 : 0.1),
                blurRadius: _isHovered ? 20 : 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          clipBehavior: Clip.antiAlias,
          child: Stack(
            fit: StackFit.expand,
            children: [
              Image.network(
                'https://picsum.photos/id/${widget.index + 50}/500/300',
                fit: BoxFit.cover,
              ),
              Container(
                decoration: const BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [Colors.transparent, Colors.black54],
                  ),
                ),
              ),
              Align(
                alignment: Alignment.bottomLeft,
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Text(
                    'Windows Item ${widget.index + 1}',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Doctor v

```dart
[√] Flutter (Channel stable, 3.38.2, on Microsoft Windows [Version 10.0.26100.6899], locale en-US) [359ms]
    • Flutter version 3.38.2 on channel stable at C:\SDKS\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f5a8537f90 (3 days ago), 2025-11-18 09:27:21 -0500
    • Engine revision b5990e5ccc
    • Dart version 3.10.0
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging

[√] Windows Version (Windows 11 or higher, 24H2, 2009) [4.5s]

[X] Android toolchain - develop for Android devices [239ms]
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe) [161ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.14.21 (November 2025)) [158ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.14.36717.8
    • Windows 10 SDK version 10.0.26100.0

[√] Connected device (2 available) [196ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.6899]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 142.0.3595.90

[√] Network resources [380ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/178916

It seems that for some reason the win32 thread pool timer is not precise enough for our use case which causes major frame pacing issues on Windows. This PR replaces it with a simple custom built background thread timer.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc [hunk 1]
```diff
@@ -7,11 +7,85 @@
...
+  // Schedules the callback to be called at specified time point. If there is
+  // already a callback scheduled earlier than the specified time point, does
+  // nothing.
+  void ScheduleAt(
+      std::chrono::time_point<std::chrono::high_resolution_clock> time_point) {
+    {
+      std::lock_guard<std::mutex> lock(mutex_);
+      if (time_point < next_fire_time_) {
+        next_fire_time_ = time_point;
+      }
```
[the remark this answers is not in the document]
Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc]: No. The behavior is on purpose. If anything the name of the function may need to be changed to reflect that.

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc [hunk 2]
```diff
@@ -143,18 +203,7 @@ void TaskRunnerWindow::ProcessTasks() {
...
-        std::chrono::duration_cast<std::chrono::microseconds>(when).count();
-    ULARGE_INTEGER ticks;
-    ticks.QuadPart = -static_cast<LONGLONG>(microseconds * 10);
-    FILETIME ft;
-    ft.dwLowDateTime = ticks.LowPart;
-    ft.dwHighDateTime = ticks.HighPart;
-    SetThreadpoolTimer(timer_, &ft, 0, 0);
-  }
+  timer_thread_->ScheduleAt(std::chrono::high_resolution_clock::now() + when);
 }
```
[the remark this answers is not in the document]
Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:202]: Nice one.

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc]: Added test to ensure this works as expected.

File: engine/src/flutter/shell/platform/windows/task_runner_unittests.cc [hunk 3]
```diff
@@ -2,10 +2,13 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+#include <atomic>
+#include <chrono>
 #include "flutter/shell/platform/windows/task_runner.h"
 
 #include "flutter/fml/macros.h"
 #include "gtest/gtest.h"
+#include "shell/platform/windows/task_runner_window.h"
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/task_runner_unittests.cc]: Nit:

```suggestion
#include "flutter/shell/platform/windows/task_runner.h"

#include <atomic>
#include <chrono>

#include "flutter/fml/macros.h"
#include "flutter/shell/platform/windows/task_runner_window.h"
#include "gtest/gtest.h"
```

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc [hunk 4]
```diff
@@ -7,30 +7,90 @@
...
+    std::chrono::time_point<std::chrono::high_resolution_clock> time_point) {
+  std::lock_guard<std::mutex> lock(mutex_);
+  if (time_point < next_fire_time_) {
+    next_fire_time_ = time_point;
+  }
+  ++schedule_counter_;
+  cv_.notify_all();
+}
+
+void TimerThread::TimerThreadMain() {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/task_runner_window.cc:59]: Should we be setting a thread priority here?

Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:59]: I'm not sure really. I don't know much about windows scheduler, even with the default values I'm getting sub-ms accuracy, but maybe the situation is worse with less CPU cores.

Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:59]: I'm leaning towards yes...

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc [hunk 5]
```diff
@@ -44,18 +104,10 @@ TaskRunnerWindow::TaskRunnerWindow() {
   }
 
   thread_id_ = GetCurrentThreadId();
-
-  // Increase timer precision for this process (the call only affects
-  // current process since Windows 10, version 2004).
-  timeBeginPeriod(1);
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/task_runner_window.cc:50]: Should we also remove the `timeEndPeriod(1)` in the destructor?

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc (hunk 4 above)
Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:59]: We could also use Multimedia Class Scheduler Service for the thread scheduling. This might need some experimenting. But maybe we can do that as a follow-up PR.

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc (hunk 5 above)
Comment (knopp) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:50]: Yes. Done.

File: engine/src/flutter/shell/platform/windows/task_runner_window.cc (hunk 4 above)
Comment (loic-sharma) [reply engine/src/flutter/shell/platform/windows/task_runner_window.cc:59]: We use "above normal" for the UI and raster threads: https://github.com/flutter/engine/pull/31778

I'd be OK with skipping thread priority for now and adding this in later if/when we find cases where this improves things.

**Review by loic-sharma — APPROVED** [review]
Thanks for the excellent fix!

**Comment by Predidit** [comment]
Excuse me, could this fix be cherry-picked to the stable branch?

**Comment by krll-kov** [comment]
> The fix here might have regressed #173843. With the new timer implementation now actually working as expected sometimes the one millisecond delay is not enough to for other windows messages to be processed :-/

So there's no sense in this fix because it does not do anything anymore?

**Comment by knopp** [comment]
No. This PR fixes the framerate. But in some cases 

```dart
Future<void> _startEvilLoop() async {
    // Spam the Dart event loop with tasks.
    // This isn't ideal, but the app should continue to work.
    while (true) {
      await Future.delayed(Duration.zero);
    }
  }
```
Might lock up the application. Not that is a good idea to do this.

The initial workaround for the bug worked because the timer delay was rather big, which causes the framerate issue but at the same time avoided draining dart run loop too fast. Now that the framerate issue is fixed, we drain the dart event loop too fast taking precedence over win32 messages. To fix this with new timer we need better solution.

**Comment by krll-kov** [comment]
> No. This PR fixes the framerate. But in some cases
> 
> ```dart
> Future<void> _startEvilLoop() async {
>     // Spam the Dart event loop with tasks.
>     // This isn't ideal, but the app should continue to work.
>     while (true) {
>       await Future.delayed(Duration.zero);
>     }
>   }
> ```
> 
> Might lock up the application. Not that is a good idea to do this.
> 
> The initial workaround for the bug worked because the timer delay was rather big, which causes the framerate issue but at the same time avoided draining dart run loop too fast. Now that the framerate issue is fixed, we drain the dart event loop too fast taking precedence over win32 messages. To fix this with new timer we need better solution.

That's what I mean, without timer and with it, the outcome is the same , that original issue with app freeze during loops with await of 0ms is still present, so it's presence seems pointless now
