### PR TITLE
fix material selection handle paint with transparent textSelectionHandleColor 

### LINKED ISSUE #49825: Material selection handle paint wrong with transparent color
## Steps to Reproduce

`_MaterialTextSelectionControls` paints handlers wrong when `ThemeData.textSelectionHandleColor` with alpha less than 255

**Expected results:** 
uniform color
**Actual results:** 
color is more intense at the intersection
изображение

### PR DESCRIPTION
**Pull request by 2ZeroSix**
## Description
filter paint at intersection of rect and circle in `_TextSelectionHandlePainter`

before:
before

after:
after

## Related Issues
fixes #49825

## Tests

I didn't add any tests

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/text_selection.dart [hunk 1]
```diff
@@ -119,8 +119,10 @@ class _TextSelectionHandlePainter extends CustomPainter {
   @override
   void paint(Canvas canvas, Size size) {
     final Paint paint = Paint()..color = color;
+    final Paint filterPaint = Paint()..blendMode = BlendMode.dstOut;
     final double radius = size.width/2.0;
     canvas.drawCircle(Offset(radius, radius), radius, paint);
+    canvas.drawRect(Rect.fromLTWH(0.0, 0.0, radius, radius), filterPaint);
     canvas.drawRect(Rect.fromLTWH(0.0, 0.0, radius, radius), paint);
```
Comment (dnfield) [inline packages/flutter/lib/src/material/text_selection.dart]: Do you really need two separate paints here?  Can you just add the blend mode to the existing paint and paint with that?

Comment (dnfield) [reply packages/flutter/lib/src/material/text_selection.dart]: Ah, I see.

I think it would be more efficient to just do this:

```dart
    final Paint paint = Paint()..color = color;
    final double radius = size.width/2.0;
    final Rect circle = Rect.fromCircle(center: Offset(radius, radius), radius: radius);
    final Rect point = Rect.fromLTWH(0.0, 0.0, radius, radius);
    final Path path = Path()..addOval(circle)..addRect(rect);
    canvas.drawPath(path, paint);
```

Then no blending or multiple draw calls.

Comment (dnfield) [reply packages/flutter/lib/src/material/text_selection.dart]: (for example, I think your dstOut blend mode could cause problems if someone removed a saveLayer somewhere)

**Comment by dnfield** [comment]
Here's an example test:

```
    testWidgets('draws transparent handle correctly', (WidgetTester tester) async {
      await tester.pumpWidget(RepaintBoundary(
        child: Theme(
          data: ThemeData(
            textSelectionHandleColor: const Color(0xAA0000AA),
          ),
          isMaterialAppTheme: true,
          child: Builder(
            builder: (BuildContext context) {
              return Container(
                color: Colors.white,
                child: materialTextSelectionControls.buildHandle(context, TextSelectionHandleType.right, 10.0),
              );
            },
          ),
        ),
      ));

      expect(find.byType(RepaintBoundary), matchesGoldenFile('transparent_handle.png'));
    });
```

File: packages/flutter/lib/src/material/text_selection.dart (hunk 1 above)
Comment (2ZeroSix) [reply packages/flutter/lib/src/material/text_selection.dart]: Thanks, I didn't know that I can acvieve this with ui.Path 🙂 
Yeah, `saveLayer` manipulations could crash my initial solution.

**Comment by 2ZeroSix** [comment]
I just found out that there is almost the same issue with cupertino handles 
example

The only difference is that `_TextSelectionHandlePainter` color is `CupertinoTheme.of(context).primaryColor` which is less likely to be transparent.

Related issue about cupertino handle color: #43887

**Review by dnfield — APPROVED** [review]
Lgtm!

We will have to triage the Golden's for this after it lands since it's from a first time contributor - right @Piinks ?

**Review by Piinks — APPROVED** [review]
LGTM! I can triage the results on https://flutter-gold.skia.org/ when they land. Thanks for the contribution! :)

**Comment by 2ZeroSix** [comment]
@Piinks Sorry, I've missed the part about naming of golden files in wiki, should I create another PR with name changed to something appropriate, like `text_selection.handle.transparent.png`?
https://github.com/flutter/flutter/blob/8061894f05417296cdc747e37e4173939e031ff5/packages/flutter/test/material/text_selection_test.dart#L96

**Comment by Piinks** [comment]
I think the name is ok. :)
