### PR TITLE
Fix Menu anchor reduce padding on web and desktop

### LINKED ISSUE #171608: Menu anchor adds extra padding on Android devices
### Steps to reproduce

1. Run the app on the web platform.
2. Run the app on the Android platform.

### Expected results

Maintain the same padding on all platforms

### Actual results

On Android, it adds more vertical padding.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MenuApp());

class MyCascadingMenu extends StatefulWidget {
  const MyCascadingMenu({super.key});

  @override
  State<MyCascadingMenu> createState() => _MyCascadingMenuState();
}

class _MyCascadingMenuState extends State<MyCascadingMenu> {
  @override
  Widget build(BuildContext context) {
    return MenuAnchor(
      style: MenuStyle(
        padding: WidgetStatePropertyAll(
          EdgeInsets.symmetric(vertical: 12, horizontal: 3),
        ),
      ),
      menuChildren: <Widget>[
        DecoratedBox(
          decoration: BoxDecoration(color: Colors.blue),

          child: Text('Text 1'),
        ),
        DecoratedBox(
          decoration: BoxDecoration(color: Colors.blue),
          child: Text('Text 2'),
        ),
      ],
      builder: (
        BuildContext context,
        MenuController controller,
        Widget? child,
      ) {
        return TextButton(
          onPressed: () {
            if (controller.isOpen) {
              controller.close();
            } else {
              controller.open();
            }
          },
          child: const Text('OPEN MENU'),
        );
      },
    );
  }
}

class MenuApp extends StatelessWidget {
  const MenuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: MyCascadingMenu())),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.4, on macOS 15.5 24F74 darwin-arm64, locale en-US) [366ms]
    • Flutter version 3.32.4 on channel stable at /Users/andry/fvm/versions/3.32.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6fba2447e9 (3 weeks ago), 2025-06-12 19:03:56 -0700
    • Engine revision 8cd19e509d
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [11.5s]
    • Android SDK at /Users/andry/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [786ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] VS Code (version 1.101.0) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (3 available) [5.8s]
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 137.0.7151.120

[✓] Network resources [2.4s]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
- Fix https://github.com/flutter/flutter/issues/171608
- Demo before the fix:

| desktop | web |
| --------------- | --------------- |
 | 

- Demo after the fix:

| desktop | web |
| --------------- | --------------- |
 | 

- Description: On desktop/web platforms, VisualDensity.compact is applied by default, which caused the issue as reported. 
Previously, this compressed menus vertically. 

In this PR:
   - Vertical padding affected by visual density is removed to follow [Material Design specs](https://www.figma.com/community/file/1035203688168086460) so that visual density should not affect vertical menu padding anymore. (*)
    - Some of test values (y coordinate/height) are also updated to align with this change and also add a regression test
    - Enhance `MenuAnchor` documentation to prevent user confusion.

<details open>
<summary>(*) Material Design specs inspection from Figma</summary>

https://github.com/user-attachments/assets/3e348a51-3917-4217-ad66-ef8cdff256ba

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -148,6 +148,12 @@ class _MenuAnchorScope extends InheritedWidget {
 ///
 /// ** See code in examples/api/lib/material/menu_anchor/menu_anchor.3.dart **
 /// {@end-tool}
+///
+/// Visual density should not affect menu vertical padding according to
+/// Material Design specs.
+/// Per the Material Design team: don't allow the VisualDensity adjustment to
+/// reduce the width of the left/right padding. If we did, VisualDensity.compact,
+/// the default for desktop/web, would reduce the horizontal padding to zero.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/menu_anchor.dart]: I think this information is a bit too detailed for the `MenuAnchor` class here. Also the format is not in the style of public documentation. I recommend moving it to `style` and rephrase it such as:
```dart
  ///
  /// The [MenuStyle.visualDensity] setting only affects horizontal padding, and it will never make it negative. Vertical padding is not affected at all.
```

**Review by dkwingsmt — COMMENTED** [review]
Generally good. Can you specify more clearly in the PR body where the Material spec said it, for reference in the future?

**Comment by huycozy** [comment]
> Generally good. Can you specify more clearly in the PR body where the Material spec said it, for reference in the future?

Thank you for reviewing this. I mentioned it with a URL here already 😄, let me know if it's visible for reference later on.

Screenshot 2025-08-05 at 11 52 49

**Comment by dkwingsmt** [comment]
Yeah I clicked into it but it's just the general Figma file. I might not be familiar enough with Figma. Can you point me toward where it talked about the menu padding?

**Comment by huycozy** [comment]
@dkwingsmt I've updated the PR description to include a video for `Material Design specs inspection from Figma`. I hope this makes it more visible now.

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 2]
```diff
@@ -3174,10 +3177,9 @@ class _MenuPanelState extends State<_MenuPanel> {
     // adjustment to reduce the width of the left/right padding. If we
     // did, VisualDensity.compact, the default for desktop/web, would
     // reduce the horizontal padding to zero.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/menu_anchor.dart]:
```suggestion
    // reduce the horizontal padding to zero. Vertical padding
    // is not affected at all.
```

**Review by dkwingsmt — APPROVED** [review]
LGTM with a nit, thank you!
