### PR TITLE
[Impeller] Fix crash trying to check for duplicate vertices in shadow_path code

### LINKED ISSUE #180827: [Google3 Bug]: [Crash Report] `anonymous namespace'::PolygonInfo::AppendVertex-dead1d17
### Help us understand the severity of this issue

- [x] causing severe production issues e.g. malfunctions or data loss
- [x] blocking next binary release
- [ ] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

Unable to verify detailed reproduction steps, see [b/475054280](https://b.corp.google.com/issues/475054280) for full crash report

This crash happens when using Impeller on iOS. From crash logs, appears to happen when rendering `DrawRoundRect` with blurred shadow. 

Likely an issue in the `PolygonInfo::AppendVertex` function within [impeller/entity/geometry/shadow_path_geometry.cc](https://github.com/flutter/flutter/blame/master/engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc). This possibly happens because the code attempts to access the .back() element of an empty vector on [line 1362](https://github.com/flutter/flutter/blame/master/engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc#L1362).

### Expected results

The application should render the UI element and its associated shadow correctly without crashing.

### Actual results

The application crashes with an `EXC_BAD_ACCESS` in impeller::PolygonInfo::AppendVertex (See [b/475054280](https://b.corp.google.com/issues/475054280) for full crash report).

### Code sample

<details open><summary>Code sample</summary>

```dart
// shadow_path_geometry.cc:1362
uint16_t PolygonInfo::AppendVertex(const Point& vertex, Scalar gaussian) {
  FML_DCHECK(gaussian >= 0.0f && gaussian <= 1.0f);
  uint16_t index = vertices_.size();
  FML_DCHECK(index == gaussians_.size());
  // ...
  if (gaussian == gaussians_.back() && vertex == vertices_.back()) { // <--- CRASH HERE
    return index - 1;
  }
  // ...
}
```

Potential fix:

```dart
  if (!vertices_.empty() && gaussian == gaussians_.back() && vertex == vertices_.back()) {
```

</details>

### Screenshots or Video

_No response_

### Logs

<details open><summary>Logs</summary>

```console
0x00000001074255cc (Flutter - shadow_path_geometry.cc: 1362)	(anonymous namespace)::PolygonInfo::AppendVertex(impeller::TPoint<float> const&, float)
0x00000001073a8d20 (Flutter - shadow_path_geometry.cc: 1268)	impeller::Canvas::AttemptDrawBlurredPathSource(impeller::PathSource const&, impeller::Paint const&)
0x00000001073a8d20 (Flutter - shadow_path_geometry.cc: 1268)	impeller::Canvas::AttemptDrawBlurredPathSource(impeller::PathSource const&, impeller::Paint const&)
0x00000001073af154 (Flutter - canvas.cc: 623)	impeller::Canvas::DrawRoundRect(impeller::RoundRect const&, impeller::Paint const&)
0x000000010710ce70 (Flutter - display_list.cc: 205)	flutter::DisplayList::Dispatch(flutter::DlOpReceiver&, impeller::TRect<float> const&) const
0x00000001073b4bf0 (Flutter - dl_dispatcher.cc: 825)	impeller::DlDispatcherBase::drawDisplayList(sk_sp<flutter::DisplayList>, float)
0x000000010710ca5c (Flutter - dl_op_records.h: 990)	flutter::DrawDisplayListOp::dispatch(flutter::DlOpReceiver&) const
0x000000010710cdf0 (Flutter - display_list.cc: 185)	flutter::DisplayList::Dispatch(flutter::DlOpReceiver&, impeller::TRect<float> const&) const
0x00000001073ba594 (Flutter - dl_dispatcher.cc: 1328)	impeller::RenderToTarget(impeller::ContentContext&, impeller::RenderTarget, sk_sp<flutter::DisplayList> const&, impeller::TRect<float>, bool, bool)
0x0000000107502168 (Flutter - gpu_surface_metal_impeller.mm: 178)	std::_fl::__function::__func<fml::internal::CopyableLambda<flutter::GPUSurfaceMetalImpeller::AcquireFrameFromCAMetalLayer(impeller::TSize<int> const&)::$_0>, std::_fl::allocator<fml::internal::CopyableLambda<flutter::GPUSurfaceMetalImpeller::AcquireFrameFromCAMetalLayer(impeller::TSize<int> const&)::$_0>>, bool (flutter::SurfaceFrame&, flutter::DlCanvas*)>::operator()(flutter::SurfaceFrame&, flutter::DlCanvas*&&)
0x00000001072fdb20 (Flutter - function.h: 436)	flutter::SurfaceFrame::Submit()
0x000000010703b7a4 (Flutter - FlutterPlatformViewsController.mm: 726)	-[FlutterPlatformViewsController submitFrame:withIosContext:]
0x000000010707ab58 (Flutter - ios_external_view_embedder.mm: 86)	flutter::IOSExternalViewEmbedder::SubmitFlutterView(long long, GrDirectContext*, std::_fl::shared_ptr<impeller::AiksContext> const&, std::_fl::unique_ptr<flutter::SurfaceFrame, std::_fl::default_delete<flutter::SurfaceFrame>>)
0x0000000107449cc8 (Flutter - rasterizer.cc: 807)	flutter::Rasterizer::DrawToSurfacesUnsafe(flutter::FrameTimingsRecorder&, std::_fl::vector<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>, std::_fl::allocator<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>>>)
0x000000010744a0d8 (Flutter - rasterizer.cc: 613)	std::_fl::__function::__func<flutter::Rasterizer::DrawToSurfaces(flutter::FrameTimingsRecorder&, std::_fl::vector<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>, std::_fl::allocator<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>>>)::$_1, std::_fl::allocator<flutter::Rasterizer::DrawToSurfaces(flutter::FrameTimingsRecorder&, std::_fl::vector<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>, std::_fl::allocator<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>>>)::$_1>, void ()>::operator()()
0x00000001070a5da4 (Flutter - function.h: 436)	fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const
0x00000001074494dc (Flutter - rasterizer.cc: 605)	flutter::Rasterizer::DrawToSurfaces(flutter::FrameTimingsRecorder&, std::_fl::vector<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>, std::_fl::allocator<std::_fl::unique_ptr<flutter::LayerTreeTask, std::_fl::default_delete<flutter::LayerTreeTask>>>>)
0x000000010744ae84 (Flutter - rasterizer.cc: 507)	std::_fl::__function::__func<flutter::Rasterizer::Draw(std::_fl::shared_ptr<flutter::Pipeline<flutter::FrameItem>> const&)::$_0, std::_fl::allocator<flutter::Rasterizer::Draw(std::_fl::shared_ptr<flutter::Pipeline<flutter::FrameItem>> const&)::$_0>, void (std::_fl::unique_ptr<flutter::FrameItem, std::_fl::default_delete<flutter::FrameItem>>)>::operator()(std::_fl::unique_ptr<flutter::FrameItem, std::_fl::default_delete<flutter::FrameItem>>&&)
0x000000010744a6f8 (Flutter - function.h: 436)	flutter::Rasterizer::Draw(std::_fl::shared_ptr<flutter::Pipeline<flutter::FrameItem>> const&)
0x0000000107461bb8 (Flutter - shell.cc: 1412)	std::_fl::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::_fl::shared_ptr<flutter::Pipeline<flutter::FrameItem>>)::$_0>, std::_fl::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::_fl::shared_ptr<flutter::Pipeline<flutter::FrameItem>>)::$_0>>, void ()>::operator()()
0x00000001070a41f8 (Flutter - function.h: 436)	fml::MessageLoopImpl::FlushTasks(fml::FlushType)
0x00000001070a810c (Flutter - message_loop_impl.cc: 139)	fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
0x0000000191976bfc (CoreFoundation + 0x0004dbfc)	__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
0x00000001919768bc (CoreFoundation + 0x0004d8bc)	__CFRunLoopDoTimer
0x0000000191976430 (CoreFoundation + 0x0004d430)	__CFRunLoopDoTimers
0x0000000191946ab8 (CoreFoundation + 0x0001dab8)	__CFRunLoopRun
0x0000000191945a68 (CoreFoundation + 0x0001ca68)	_CFRunLoopRunSpecificWithOptions
0x00000001070a81fc (Flutter - message_loop_darwin.mm: 51)	fml::MessageLoopDarwin::Run()
0x00000001070a7850 (Flutter - message_loop_impl.cc: 94)	std::_fl::__function::__func<fml::Thread::Thread(std::_fl::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0, std::_fl::allocator<fml::Thread::Thread(std::_fl::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>, void ()>::operator()()
0x00000001070a755c (Flutter - function.h: 436)	fml::ThreadHandle::ThreadHandle(std::_fl::function<void ()>&&)::$_0::__invoke(void*)
0x00000001ee20f448 (libsystem_pthread.dylib + 0x00004448)	_pthread_start
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
NA
```

</details>

### PR DESCRIPTION
**Pull request by flar**
Fixes https://github.com/flutter/flutter/issues/180827

The new general convex path shadow code was checking for duplicate vertices without actually checking if the vectors contained any vertices. Thus, <vector>.back() was being called on empty vectors, which is bad. This led to a crash in G3 as their code is being run with a vector implementation that protects against this, but apparently we do not have such a vector implementation in our local building and testing.

No tests because this covered by existing test cases and a new FML_DCHECK, however I'm not sure if we have DCHECKs enabled in CI...?

### CODE REVIEW

File: engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc [hunk 1]
```diff
@@ -1359,8 +1359,11 @@ uint16_t PolygonInfo::AppendVertex(const Point& vertex, Scalar gaussian) {
...
   // TODO(jimgraham): Turn this condition into a failure of the tessellation
   FML_DCHECK(index <= std::numeric_limits<uint16_t>::max());
-  if (gaussian == gaussians_.back() && vertex == vertices_.back()) {
-    return index - 1;
+  if (index > 0u) {
+    FML_DCHECK(!gaussians_.empty() && !vertices_.empty());
+    if (gaussian == gaussians_.back() && vertex == vertices_.back()) {
+      return index - 1;
+    }
   }
```
[the remark this answers is not in the document]
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc:1367]: I realize this. It's a check so that tests run with debug_unopt builds will catch any future issues.

Belt-and-suspenders kind of thing and I'm not worried about performance on debug_unopt...

File: engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc [hunk 2]
```diff
@@ -1359,8 +1359,11 @@ uint16_t PolygonInfo::AppendVertex(const Point& vertex, Scalar gaussian) {
   FML_DCHECK(index == gaussians_.size());
   // TODO(jimgraham): Turn this condition into a failure of the tessellation
   FML_DCHECK(index <= std::numeric_limits<uint16_t>::max());
-  if (gaussian == gaussians_.back() && vertex == vertices_.back()) {
-    return index - 1;
+  if (index > 0u) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc:1362]: nit: I think `if (!gaussians_.empty() && !vertices_.empty())` is more clear instead of branching on the derivative.

**Review by gaaclarke — APPROVED** [review]
I wish there was a way we could make this crash in our tests too.  Is there a linter flag for this?  Can we also enable the flags that g3 is using?

**Comment by gaaclarke** [comment]
Maybe it's ASAN?

File: engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc (hunk 2 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc:1362]: The thing is that index is sufficient without making 2 method calls. We've already asserted with DCHECK that the 2 vectors are the same length and index contains the size of the vectors. I only added the DCHECK so tests would fail. I tested the unit tests without the index check and the DCHECK crashed and then I added the index check and they passed just fine.

Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/shadow_path_geometry.cc:1362]: It looks like at least one of our CI runs is on a debug_unopt build and Jason and John confirmed that it does run the impeller tests. I confirmed before I fixed it that the DCHECK fails without the fix and passes with it, so I think this is OK. Though, as a general rule, I'd rather that all CI tasks that run unit tests run them on a debug_unopt build.
