### PR TITLE
Add  MaterialStateProperty `overlayColor` & `mouseCursor` and fix hovering on thumbs behavior

### LINKED ISSUE #116731: Add support for `overlayColor` and `mouseCursor` to `RangeSlider`
`RangeSlider` is missing some key features including support for `overlayColor` & mouse cursor.
https://master-api.flutter.dev/flutter/material/Slider/Slider.html
https://master-api.flutter.dev/flutter/material/RangeSlider/RangeSlider.html

This is important to support the M3 overlay.

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/116731
partial fix for https://github.com/flutter/flutter/issues/62214
Preliminary work for https://github.com/flutter/flutter/issues/53958

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

// const Color hoverColor = Color(0xffff0000);
// const Color draggedColor = Color(0xff0000ff);
// const MouseCursor disabledCursor = SystemMouseCursors.basic;
// const MouseCursor hoveredCursor = SystemMouseCursors.grab;
// const MouseCursor draggedCursor = SystemMouseCursors.move;

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  RangeValues rangeValues = const RangeValues(20, 80);
  double sliderValue = 20;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Slider/RangeSlider Example'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Slider'),
            Slider(
              value: sliderValue,
              max: 100,
              label: sliderValue.round().toString(),
              onChanged: (double value) {
                setState(() {
                  sliderValue = value;
                });
              },
            ),
            const Text('RangeSlider'),
            RangeSlider(
              values: rangeValues,
              max: 100,
              labels: const RangeLabels(
                '20',
                '80',
              ),
              onChangeStart: (RangeValues value) {},
              onChangeEnd: (RangeValues value) {},
              onChanged: (RangeValues values) {
                setState(() {
                  rangeValues = values;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}

``` 
	
</details>

### Before (Hovering on them to show overlay and cursor support are missing)

# After 

### Cursor

https://user-images.githubusercontent.com/48603081/207095086-75aae7c0-cc78-4a98-8e0a-aaa4885d5e95.mov

### Fixed show overlay only when hovering on thumbs to match the `Slider` widget and Material specs.

https://user-images.githubusercontent.com/48603081/207095429-6dbc8ffd-516e-4da7-a7b5-cfec2cb7dfeb.mov

Note:
Future PRs will add `focus` support and keyboard shortcuts, which are missing from this PR. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/debug_test.dart [hunk 1]
```diff
@@ -335,9 +331,6 @@ void main() {
     renderObject = tester.firstRenderObject(find.byType(ShaderMask));
     expect(renderObject.debugLayer?.debugCreator, isNotNull);
 
-    renderObject = tester.firstRenderObject(find.byType(RangeSlider));
```
Comment (TahaTesser) [inline packages/flutter/test/widgets/debug_test.dart:338]: Removed this as `RangeSlider` no longer returns `CompositedTransformTarget`. It now wraps `CompositedTransformTarget` with `FocusableActionDetector` (similar to Slider)

Other Widgets in this test return render objects for which `debugCreator` is tested.

File: packages/flutter/lib/src/material/range_slider.dart [hunk 2]
```diff
@@ -471,14 +497,23 @@ class _RangeSliderState extends State<RangeSlider> with TickerProviderStateMixin
...
     widget.onChangeStart!(_lerpRangeValues(values));
   }
 
   void _handleDragEnd(RangeValues values) {
     assert(widget.onChangeEnd != null);
+    _dragging = false;
     widget.onChangeEnd!(_lerpRangeValues(values));
   }
 
+  bool _hovering = false;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/range_slider.dart:510]: Nit: Can you bump this up higher to be with the _enabled and _dragging?

**Review by Piinks — APPROVED** [review]
This looks excellent, thank you! There are some merge conflicts though that need to be resolved
