### PR TITLE
Fix default minimumSize in dropdownMenu when maximumSize is null

### LINKED ISSUE #170970: Dropdown default minimumSize when maximumSize is null returns a width of 0
### Steps to reproduce

1. Create a Dropdown widget without minimum or maximum width (let it expand to the parent size)
2. open the dropdown and see the items not be expanded to the same size the Dropdown, it should be the same size that the anchor parent

The problem is in dropdown_menu.dart line 969:
```
  if (widget.width != null) {
      effectiveMenuStyle = effectiveMenuStyle.copyWith(
        minimumSize: MaterialStateProperty.resolveWith<Size?>((Set<MaterialState> states) {
          final double? effectiveMaximumWidth =
              effectiveMenuStyle!.maximumSize?.resolve(states)?.width;
          return Size(math.min(widget.width!, effectiveMaximumWidth ?? 0.0), 0.0);
        }),
      );
    } else if (anchorWidth != null) {
      effectiveMenuStyle = effectiveMenuStyle.copyWith(
        minimumSize: MaterialStateProperty.resolveWith<Size?>((Set<MaterialState> states) {
          final double? effectiveMaximumWidth =
              effectiveMenuStyle!.maximumSize?.resolve(states)?.width;
          return Size(math.min(anchorWidth, effectiveMaximumWidth ?? 0.0), 0.0);
        }),
      );
    }
```

When a maximum size is not being applied in the theme or directly in the widget this instructions return a minumim size of `Size(0.0, 0.0)` because when using math.min of `effectiveMaximumWidth (and this is null) ?? 0.0` will always be `<= anchorWidth or widget.width.`

Instead when effectiveMaximumWidth is null this should use the size of the anchor or the one given in width:

```
Size(math.min(anchorWidth, effectiveMaximumWidth ?? anchorWidth)

Size(math.min(widget.width!, effectiveMaximumWidth ?? widget.width)
```

### Expected results

This was the result prior 3.32

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        dropdownMenuTheme: DropdownMenuThemeData(
          textStyle: const TextStyle(fontSize: 14),
          inputDecorationTheme: const InputDecorationTheme(
            border: UnderlineInputBorder(),
          ),
          menuStyle: MenuStyle(
            shape: const WidgetStatePropertyAll(
              RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(8)),
              ),
            ),
            /// This is the only way to make it expand to the same size the 
            /// parent dropdown (if there is no constraint of the anchro to the parent)
            /// but shouldn't be a requirement
            maximumSize: const WidgetStatePropertyAll(Size.infinite),
            padding: const WidgetStatePropertyAll(EdgeInsets.zero),
            visualDensity: const VisualDensity(vertical: -2),
            side: WidgetStatePropertyAll(
              BorderSide(color: Colors.grey.shade200),
            ),
            backgroundColor: WidgetStateColor.fromMap({
              WidgetState.disabled: Colors.grey.shade400,
              WidgetState.selected: Colors.purple.shade600,
              WidgetState.any: Colors.white,
            }),
          ),
        ),
      ),
      home: const Scaffold(
        body: SafeArea(minimum: EdgeInsets.all(16), child: DropdownExample()),
      ),
    );
  }
}

enum Gender { male, female }

class DropdownExample extends StatelessWidget {
  const DropdownExample({super.key});

  @override
  Widget build(BuildContext context) {
    return DropdownMenu(
      dropdownMenuEntries: const [
        DropdownMenuEntry(value: Gender.female, label: 'Female'),
        DropdownMenuEntry(value: Gender.male, label: 'Male'),
      ],
      enableSearch: false,
      expandedInsets: EdgeInsets.zero,
      hintText: 'Select an option',
      selectedTrailingIcon: const Icon(Icons.keyboard_arrow_up, size: 16),
      trailingIcon: const Icon(Icons.keyboard_arrow_down, size: 16),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.32.2, on macOS 15.5 24F74 darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.101.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by EdwynZN**
Previous change in `DropDownMenu` https://github.com/flutter/flutter/pull/162380 forced the menu width to be constrained between the width or anchorWidth and the maximumSize width menuStyle, but giving a minimum of zero when maximumSize was not enforced or null. This prevents width or anchorWidth to be used at all as the minimum will be zero always if maximumSize is null

Now this sets the default value back to width or anchorWidth if maximumSize is null, keeping consistency of the previous configuration while using the fix of maximumSize when provided.

Fixes https://github.com/flutter/flutter/issues/170970

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -986,15 +986,21 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
         minimumSize: MaterialStateProperty.resolveWith<Size?>((Set<MaterialState> states) {
           final double? effectiveMaximumWidth =
               effectiveMenuStyle!.maximumSize?.resolve(states)?.width;
-          return Size(math.min(widget.width!, effectiveMaximumWidth ?? 0.0), 0.0);
+          final double effectiveWidth = effectiveMaximumWidth == null
+            ? widget.width!
+            : math.min(widget.width!, effectiveMaximumWidth);
+          return Size(effectiveWidth, 0.0);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart]: Seems this is same as `Size(math.min(widget.width!, effectiveMaximumWidth ?? widget.width), 0.0);`?

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 2]
```diff
@@ -986,15 +986,21 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
     } else if (anchorWidth != null) {
       effectiveMenuStyle = effectiveMenuStyle.copyWith(
         minimumSize: MaterialStateProperty.resolveWith<Size?>((Set<MaterialState> states) {
           final double? effectiveMaximumWidth =
               effectiveMenuStyle!.maximumSize?.resolve(states)?.width;
-          return Size(math.min(anchorWidth, effectiveMaximumWidth ?? 0.0), 0.0);
+          final double effectiveWidth = effectiveMaximumWidth == null
+            ? anchorWidth
+            : math.min(anchorWidth, effectiveMaximumWidth);
+          return Size(effectiveWidth, 0.0);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart]: And this is the same as `Size(math.min(anchorWidth, effectiveMaximumWidth ?? anchorWidth), 0.0);`

**Review by QuncCccccc — COMMENTED** [review]
Thanks for your contribution. Are there any issue that this PR is fixing? Attaching an issue link would be very helpful to track why we created this PR. Could you also help fix the failed `linux_analyzer` test?

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 1 above)
Comment (EdwynZN) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: Yeah I think it can be reduced to one line

**Review by EdwynZN — COMMENTED** [review]
I have created an issue for this: https://github.com/flutter/flutter/issues/170970

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 3]
```diff
@@ -1017,15 +1017,15 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
+          return Size(math.min(widget.width!, effectiveMaximumWidth ?? widget.width!), 0.0);
         }),
       );
     } else if (anchorWidth != null) {
       effectiveMenuStyle = effectiveMenuStyle.copyWith(
         minimumSize: MaterialStateProperty.resolveWith<Size?>((Set<MaterialState> states) {
           final double? effectiveMaximumWidth =
               effectiveMenuStyle!.maximumSize?.resolve(states)?.width;
-          return Size(math.min(anchorWidth, effectiveMaximumWidth ?? 0.0), 0.0);
+          return Size(math.min(anchorWidth, effectiveMaximumWidth ?? anchorWidth!), 0.0);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart]: Removing `!` after `anchorWidth` should fix one of the linux analyzer failures.
```suggestion
          return Size(math.min(anchorWidth, effectiveMaximumWidth ?? anchorWidth), 0.0);
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 4]
```diff
@@ -4310,6 +4310,27 @@ void main() {
...
+        ),
+      ),
+    );
+
+    await tester.tap(find.byType(TextField));
+    await tester.pumpAndSettle();
+
+    expect(tester.takeException(), isNull);
+    expect(tester.getSize(findMenuItemButton(menuChildren.first.label)).width, 200.0);
+
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: Linux also shows a format error, removing this empty line should fix it.
```suggestion
```

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: I tried this test locally and looks like it can pass without the PR change. It is because it's updating the existing test and previously, the menu hasn't been closed so the width is probably still the value from the code above. Can we create a new test for this part of testing?

**Review by QuncCccccc — COMMENTED** [review]
LGTM! Thanks for your contribution! After fixing the comments below, I'll ask for a second review:)!

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 4 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Any updates here:)?

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 5]
```diff
@@ -4310,6 +4310,26 @@ void main() {
 
     expect(tester.takeException(), isNull);
     expect(tester.getSize(findMenuItemButton(menuChildren.first.label)).width, 150.0);
+
+    // The overwrite of menuStyle is different when a width is provided but maximumSize is not,
+    // So it needs to be tested separately.
+    await tester.pumpWidget(
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:4307]: Seems the [comment](https://github.com/flutter/flutter/pull/169438#discussion_r2164987988) is still not solved. Can we test the behavior in a new unit test instead of adding it here in an existing test:)? Let me know if any help is needed!

Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart:4307]: I added a new unit test below when no maximumSize is specified to ensure that it uses the intrinsic size (width or anchor size). This test should fail without the fix.

I believe the current tests ran successfully in master because the labels are long enough to exceed the minimumSize.width used in the example (200), testing against anchor or a really small label should break it

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 6]
```diff
@@ -4299,6 +4299,79 @@ void main() {
...
+    expect(tester.takeException(), isNull);
+    expect(tester.getSize(findMenuItemButton(menuChildren.first.label)).width, 200.0);
+  });
+
+  testWidgets('ensure items are constrained to intrinsic size of DropdownMenu (width or anchor) when no maximumSize', (
+    WidgetTester tester,
+  ) async {
+    tester.view.physicalSize = const Size(390, 810);
+    tester.view.devicePixelRatio = 1.0;
+    const shortLabel = 'Male';
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]:
```suggestion
    const String shortLabel = 'Male';
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 7]
```diff
@@ -4299,6 +4299,79 @@ void main() {
...
+
+    expect(tester.takeException(), isNull);
+    expect(tester.getSize(findMenuItemButton(menuChildren.first.label)).width, 200.0);
+  });
+
+  testWidgets('ensure items are constrained to intrinsic size of DropdownMenu (width or anchor) when no maximumSize', (
+    WidgetTester tester,
+  ) async {
+    tester.view.physicalSize = const Size(390, 810);
+    tester.view.devicePixelRatio = 1.0;
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: just nit: No need to specify this. The default width should be 800.0

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 8]
```diff
@@ -4299,6 +4299,79 @@ void main() {
...
+    const shortLabel = 'Male';
+    // Specifiying width of 200
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]:
```suggestion
```

**Review by QuncCccccc — APPROVED** [review]
Thank you for your contribution! Sorry I missed your update. Seems the linux_analyzer shows up some format issues:)

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 9]
```diff
@@ -4299,6 +4299,79 @@ void main() {
...
+
+    // Using expandedInsets to anchor the TextField to the same size as the parent,
+    // 390 as the physicalSize width specified
+    await tester.pumpWidget(
+      const MaterialApp(
+        home: Scaffold(
+          body: SizedBox(
+            width: double.infinity,
+            child: DropdownMenu<int>(
+              expandedInsets: EdgeInsets.zero,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: I just noticed that there's an issue when we set the text field to be full-screen width, the children width somehow is a 16 less than the full width. I'll file an issue for that. For now, we can either change the expected number to 784.0 , or set some paddings here like `expandedInsets: EdgeInsets.symmetric(horizontal: 20),`, then the expected number would be 760 (800 - 40)

_EDIT:_ filed a ticket: https://github.com/flutter/flutter/issues/172680

Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart]: 800 is the height, 390 is the width, so you say the expected number is 350?

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: No, I mean if we remove the physical size setup:
```
    tester.view.physicalSize = const Size(390, 810);
    tester.view.devicePixelRatio = 1.0;
```
And add `expandedInsets: EdgeInsets.symmetric(horizontal: 20)`, then, the expected number would be 760.

It's to help fix the failed tests.

**Comment by QuncCccccc** [comment]
There are some [format errors](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8708442322442763633/+/u/run_test.dart_for_analyze_shard_and_subshard_None/stdout#:~:text=Found%202%20Dart%20files%20which%20were%20formatted%20incorrectly.%0ATo%20fix%2C%20run%20%60dart%20format%20packages/flutter/lib/src/material/dropdown_menu.dart%20packages/flutter/test/material/dropdown_menu_test.dart%60%20or%3A) in Linux analyze. We also need to fix it.

**Comment by EdwynZN** [comment]
@QuncCccccc All format errors has been fixed, only waiting for approve and tree fix

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 10]
```diff
@@ -4301,8 +4301,79 @@ void main() {
...
+      );
+
+      await tester.tap(find.byType(TextField));
+      await tester.pumpAndSettle();
+
+      expect(tester.takeException(), isNull);
+      expect(tester.getSize(findMenuItemButton(shortLabel)).width, 200);
+
+      // Using expandedInsets to anchor the TextField to the same size as the parent,
+      // 390 as the physicalSize width specified
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart]:
```suggestion
      // Use expandedInsets to anchor the TextField to the same size as the parent.
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 11]
```diff
@@ -4301,8 +4301,79 @@ void main() {
...
+            ),
+          ),
+        ),
+      );
+
+      await tester.tap(find.byType(TextField));
+      await tester.pumpAndSettle();
+
+      expect(tester.takeException(), isNull);
+      expect(tester.getSize(findMenuItemButton(shortLabel)).width, 760.0);
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:4371]:
```suggestion
      // Default width is 800, so the expected width is 800 - padding (20 + 20).
      expect(tester.getSize(findMenuItemButton(shortLabel)).width, 760.0);
```

**Review by QuncCccccc — APPROVED** [review]
LGTM. Just gave 2 more nits to make the test comments more accurate.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 12]
```diff
@@ -4301,8 +4301,79 @@ void main() {
...
+            menuStyle: const MenuStyle(),
+          ),
+        ),
+      ),
+    );
+
+    await tester.tap(find.byType(TextField));
+    await tester.pumpAndSettle();
+
+    expect(tester.takeException(), isNull);
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: Did this used to fail before this PR? If so maybe add a comment saying that this is a regression test for https://github.com/flutter/flutter/issues/170970.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 13]
```diff
@@ -4301,8 +4301,79 @@ void main() {
...
+              menuStyle: MenuStyle(),
+            ),
+          ),
+        ),
+      );
+
+      await tester.tap(find.byType(TextField));
+      await tester.pumpAndSettle();
+
+      expect(tester.takeException(), isNull);
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: Same question here.

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 12 above)
Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Not failing as this case was not properly tested

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Oh I think we can remove this block of test because the test below is just testing same thing.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 13 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: I think we can remove this line as well since even without this PR, the test will not throw exception.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 12 above)
Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart]: This previous test is different from the one below in that the menu items here are long text whereas the one below use a small label (to show how both try to expand/constraint to the defined size of 200)

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Seems menuChildren only contain entries like "item 0", "item 1" and etc. They seem to have similar width as the `shortLabel` below.

Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Ok so should we delete this or the new test (below)?

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: I think we can remove this here:)

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 13 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Also this line, then we are ready to move on landing it!

Comment (EdwynZN) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Done
