### PR TITLE
[Android] Encode the original pointer count in messages that represent Android touch events

### LINKED ISSUE #176574: Duplicate Multi-touch Events in Android Platform Views
### Steps to reproduce

1. Create a Flutter app with an `AndroidView` inside `GestureDetector` with long press callbacks:
2. In the native Android view, log all `MotionEvent` actions with timestamps and pointer counts
3. Perform a pinch/scale gesture

### Expected results

```console
I/flutter (28829): Flutter: Long press CANCEL
D/NativeView(28829): Action: ACTION_DOWN, Pointers: 1, Time: 580981037
D/NativeView(28829): Action: ACTION_POINTER_DOWN(1), Pointers: 2, Time: 580981037
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981198
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981235
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981251
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981268
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981285
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981301
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981315
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981335
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981351
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981368
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981385
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981401
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981418
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981432
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981468
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981485
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981501
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981518
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981535
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981551
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981557
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981585
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981601
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981618
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981632
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981678
D/NativeView(28829): Action: ACTION_POINTER_UP(0), Pointers: 2, Time: 580981786
```

### Actual results

```console
I/flutter (28829): Flutter: Long press CANCEL
D/NativeView(28829): Action: ACTION_DOWN, Pointers: 1, Time: 580981037
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981198
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981235
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981251
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981268
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981285
D/NativeView(28829): Action: ACTION_POINTER_DOWN(1), Pointers: 2, Time: 580981037
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981198
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981235
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981251
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981268
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981285
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981301
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981315
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981335
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981351
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981368
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981385
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981401
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981418
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981432
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981468
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981485
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981501
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981518
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981535
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981551
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981557
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981585
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981601
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981618
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981632
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981678
D/NativeView(28829): Action: ACTION_POINTER_UP(0), Pointers: 2, Time: 580981786
```

### Code sample

<details open><summary>Code sample</summary>

```dart
```dart
GestureDetector(
    behavior: HitTestBehavior.translucent,
    onLongPressStart: (dt) => _sendLongPressEvent("Long press START"),
    onLongPressCancel: () => _sendLongPressEvent("Long press CANCEL"),
    onLongPressMoveUpdate: (details) => _sendLongPressEvent("Long press UPDATE"),
    onLongPressEnd: (details) => _sendLongPressEvent("Long press END"),
    child: AndroidView(
      viewType: 'native-view',
      layoutDirection: TextDirection.ltr,
    ),
  )
```
```

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console
I/flutter (28829): Flutter: Long press CANCEL
D/NativeView(28829): Action: ACTION_DOWN, Pointers: 1, Time: 580981037
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981198
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981235
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981251
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981268
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981285
D/NativeView(28829): Action: ACTION_POINTER_DOWN(1), Pointers: 2, Time: 580981037
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981198
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981235
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981251
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981268
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981285
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981301
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981315
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981335
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981351
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981368
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981385
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981401
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981418
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981432
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981468
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981485
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981501
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981518
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981535
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981551
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981557
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981585
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981601
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981618
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981632
D/NativeView(28829): Action: ACTION_MOVE, Pointers: 2, Time: 580981678
D/NativeView(28829): Action: ACTION_POINTER_UP(0), Pointers: 2, Time: 580981786
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.5, on macOS 26.0.1 25A362 darwin-arm64, locale en-US) [204ms]
    • Flutter version 3.35.5 on channel stable at /Users/romanlaitarenko/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac4e799d23 (10 days ago), 2025-09-26 12:05:09 -0700
    • Engine revision d3d45dcf25
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-swift-package-manager,
      enable-lldb-debugging

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [759ms]
    • Android SDK at /Users/romanlaitarenko/Library/Android/sdk
    • Emulator version 35.5.10.0 (build_id 13402964) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/romanlaitarenko/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Temurin-17.0.16+8 (build 17.0.16+8)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1) [454ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A400
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [8ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.3) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] Connected device (4 available) [5.9s]
    • sdk gphone16k arm64 (mobile)           • emulator-5554                        • android-arm64 • Android 15 (API 35) (emulator)
    • Roman’s iPhone (2) (wireless) (mobile) • 00008110-00110D1614F9801E            • ios           • iOS 26.0.1 23A355
    • iPhone 16 Pro (mobile)                 • CCF1D21D-4E0C-423A-870B-005E7F4F2EBD • ios           • com.apple.CoreSimulator.SimRuntime.iOS-18-6 (simulator)
    • macOS (desktop)                        • macos                                • darwin-arm64  • macOS 26.0.1 25A362 darwin-arm64

[✓] Network resources [213ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by jason-simmons**
Android touch events include updates to multiple pointers, but each pointer data message sent from the embedder to the framework represents a single pointer.  So the Android embedder will send multiple messages for each touch event, and the framework's AndroidViewController will reassemble the messages and forward the resulting event to the platform view.

The AndroidViewController tracks the number of active pointers in its own local state.  If that state is out of sync with the event handled by the Android embedder, then the AndroidViewController may send duplicate events to the platform view.

This PR encodes the Android touch event's pointer count in the messages sent to the framework.  This allows the AndroidViewController to reliably determine whether it has received all of the pointer messages that originated from an event.

Fixes https://github.com/flutter/flutter/issues/176574

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java [hunk 1]
```diff
@@ -212,7 +215,8 @@ public boolean onTouchEvent(@NonNull MotionEvent event, @NonNull Matrix transfor
       // but it's the responsibility of a later part of the system to
       // ignore 0-deltas if desired.
       for (int p = 0; p < originalPointerCount; p++) {
-        addPointerForIndex(event, p, pointerChange, 0, transformMatrix, packet);
+        int pointerData = POINTER_DATA_FLAG_MULTIPLE | (originalPointerCount << 8);
```
[the remark this answers is not in the document]
Comment (jason-simmons) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java]: done

File: packages/flutter/lib/src/services/platform_views.dart [hunk 2]
```diff
@@ -619,19 +619,28 @@ class _AndroidMotionEventConverter {
...
     // as we get PointerEvents, and only send it to the embedded Android view when
     // we see the last pointer. This way we achieve the same batching as Android.
-    if (event.platformData == kPointerDataFlagBatched ||
-        (isSinglePointerAction(event) && pointerIdx < numPointers - 1)) {
+    final int platformDataFlag = event.platformData & 0xff;
+    if (platformDataFlag == kPointerDataFlagBatched) {
       return null;
     }
+    if (platformDataFlag == kPointerDataFlagMultiple) {
+      final int originalPointerCount = event.platformData >> 8;
```
[the remark this answers is not in the document]
Comment (jason-simmons) [reply packages/flutter/lib/src/services/platform_views.dart]: done

File: packages/flutter/test/services/platform_views_test.dart [hunk 3]
```diff
@@ -439,6 +440,62 @@ void main() {
...
+          timeStamp: const Duration(milliseconds: 2),
+          pointer: i,
+          platformData: kPointerDataFlagMultiple | (pointerCount << 8),
+        );
+        viewController.dispatchPointerEvent(event);
+      }
+
+      // Indexes in the list returned by AndroidMotionEvent._asList
+      const int kAndroidMotionEventListIndexAction = 3;
+      const int kAndroidMotionEventListIndexPointerCount = 4;
```
[the remark this answers is not in the document]
Comment (jason-simmons) [reply packages/flutter/test/services/platform_views_test.dart:486]: Would prefer to avoid exposing these indexes in the `AndroidMotionEvent` public API

File: packages/flutter/lib/src/services/platform_views.dart [hunk 4]
```diff
@@ -697,9 +710,6 @@ class _AndroidMotionEventConverter {
       },
     );
   }
-
-  bool isSinglePointerAction(PointerEvent event) =>
```
Comment (gmackall) [inline packages/flutter/lib/src/services/platform_views.dart:701]: Is this removed because it was a heuristic for determining if the change affected multiple pointers, and we no longer need a heuristic as we explicitly encode that info?

File: packages/flutter/lib/src/services/platform_views.dart [hunk 5]
```diff
@@ -619,19 +619,32 @@ class _AndroidMotionEventConverter {
...
+    final int platformDataFlag = event.platformData & kPointerDataFlagMask;
+    if (platformDataFlag == kPointerDataFlagBatched) {
       return null;
     }
+    if (platformDataFlag == kPointerDataFlagMultiple) {
+      final int originalPointerCount = event.platformData >> kPointerDataMultiplePointerCountShift;
+      if (pointerIdx != originalPointerCount - 1) {
+        return null;
+      }
+    }
```
Comment (gmackall) [inline packages/flutter/lib/src/services/platform_views.dart:647]: Should we also update the logic below this to remove the use of `numPointers`, and then remove that value? I would think we would also want to encode the Android action we send based off the true pointer count of the original touch event, is that not right?

**Review by gmackall — COMMENTED** [review]
Mostly lgtm, just one question about the way we determine the action below this change, and also one question for my own understanding

File: packages/flutter/lib/src/services/platform_views.dart (hunk 4 above)
Comment (jason-simmons) [reply packages/flutter/lib/src/services/platform_views.dart:701]: Yes - with this change the `isSinglePointerAction` function is no longer needed.

Messages from multiple-pointer events will be marked with the `kPointerDataFlagMultiple` flag.

File: packages/flutter/lib/src/services/platform_views.dart (hunk 5 above)
Comment (jason-simmons) [reply packages/flutter/lib/src/services/platform_views.dart:647]: `numPointers` is still being used by another code path that converts pointer data messages into Android pointer up and down events.  Specifically, Android's `MotionEvent` has separate `ACTION_DOWN`/`ACTION_UP` and `ACTION_POINTER_DOWN`/`ACTION_POINTER_UP` codes for primary versus non-primary pointers.  The framework side decides whether to map a message to `ACTION_DOWN` or `ACTION_POINTER_DOWN` based on its local state indicating whether this is the first pointer down (and likewise for the last pointer up).

AFAICT there is no race or potential for duplicate messages there.  Each pointer up/down message will result in exactly one Android pointer up/down event.  The logic will ensure that an `ACTION_DOWN` is sent before any `ACTION_POINTER_DOWN` events (and the reverse for pointer up).

The process of trying to recover the original Android events from Flutter's internal event representation does have complexity and potential for errors.
I suspect that there are more cases where the recovered events do not accurately reflect the original events (for example, it looks like the code in `toAndroidMotionEvent` that calculates `pointerIdx` may not consistently map Flutter's pointer IDs to Android pointer IDs).  But I wanted to keep this PR focused on solving only one specific known issue.

Comment (gmackall) [reply packages/flutter/lib/src/services/platform_views.dart:647]: Sounds good, if this would mean changing additional paths then makes sense to not include it

> The process of trying to recover the original Android events from Flutter's internal event representation does have complexity and potential for errors.
I suspect that there are more cases where the recovered events do not accurately reflect the original events (for example, it looks like the code in toAndroidMotionEvent that calculates pointerIdx may not consistently map Flutter's pointer IDs to Android pointer IDs). But I wanted to keep this PR focused on solving only one specific known issue.

Yeah, I've personally seen mismatches specifically for this case where the reconstructed event is `ACTION_POINTER_DOWN` while the saved (true original) event is `ACTION_DOWN`, when testing https://github.com/flutter/flutter/pull/177572 and printing them both out

**Review by gmackall — APPROVED** [review]

**Review by reidbaker — APPROVED** [review]

File: packages/flutter/lib/src/services/platform_views.dart (hunk 5 above)
Comment (reidbaker) [reply packages/flutter/lib/src/services/platform_views.dart:647]: @gmackall is this an area where we should do a deep technical dive to try to reproduce the types of input you are seeing fail to be reproduced correctly?

Comment (jason-simmons) [reply packages/flutter/lib/src/services/platform_views.dart:647]: I looked into some issues affecting Android platform view pointer up/down events and wrote it up at https://github.com/flutter/flutter/issues/178189
