### PR TITLE
Force plugins to inherit minimum iOS version from Flutter app

### LINKED ISSUE #40109: Plugin target deployments are out of range, causes Xcode warning
Plugins can specify their minimum deployment version, but Xcode outputs a warning if this deployment version is less than the range it supports.   Random example from https://github.com/flutter/flutter/issues/22123:

```
warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'Protobuf')
warning: The iOS deployment target is set to 5.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'GoogleToolboxForMac')
warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'nanopb')
warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'firebase_analytics')
warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'firebase_remote_config')
warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'image_picker')
```

See efforts like https://github.com/flutter/plugins/pull/1483 to keep plugins in the range.

## Steps to Reproduce
1. Add plugin with podspec `s.ios.deployment_target` < 8.0
2. Open Xcode and build workspace.

### LINKED ISSUE #63253: Increase plugin template minimum supported iOS version from 8.0 to 9.0
https://github.com/flutter/flutter/issues/60035 but for plugins.

Flutter apps with minimum versions of 8.0 (so current 1.20 and older) will not be able to use plugins with a higher minimum version.

### PR DESCRIPTION
**Pull request by jmagman**
## Background

Xcode supports specific SDK ranges, and every release they drop the lowest.  For example, Xcode 11 dropped support for iOS 7, and Xcode 12 dropped support for iOS 8.
Xcode emits a warning when build targets support a minimum version lower than the range to indicate it can't validate compilation against the older SDK.
```
warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'firebase_analytics')
warning: The iOS deployment target is set to 6.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'firebase_remote_config')
warning: The iOS deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'image_picker')
```
This warning is benign: if the app supports a minimum of iOS 9.0, it doesn't cause any problems that a plugin framework embedded in the app supports iOS 7.0.  These warnings concern users who think there's something wrong with their app, and there's no way for users to fix it (the plugin author would have to up their minimum supported version).

Flutter's plugin template defaults to a minimum of iOS 8, so when Xcode 12 dropped that version, every plugin started emitting this warning, so this problem became much more visible.

## Description
If the plugin's minimum version is less than iOS 9, remove the version build setting.  This will cause it to inherit from the minimum version set in the Flutter app (currently 9.0).

If the plugin minimum is higher than iOS 9, leave the build setting so if there is a versioning range issue (the plugin supports a minimum iOS 12 but the app needs iOS 9) the correct error (not warning) will be emitted.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40109
Fixes https://github.com/flutter/flutter/issues/63253

See also
https://github.com/CocoaPods/CocoaPods/issues/7314
https://github.com/flutter/flutter/pull/36117

## Tests

Updated plugin_dependencies_test to make sure this warning isn't emitted.  Confirmed it fails on master.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: dev/devicelab/bin/tasks/plugin_dependencies_test.dart [hunk 1]
```diff
@@ -274,13 +274,20 @@ public class DummyPluginAClass {
...
             options: <String>[
               'ios',
               '--no-codesign',
+              '-v',
             ],
           );
+          // This warning is confusing and shouldn't be emitted. Plugins often support lower versions than the
+          // Flutter app, but as long as they support the minimum it will work.
+          // warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'plugin_a' from project 'Pods')
+           if (output.contains('but the range of supported deployment target versions')) {
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/plugin_dependencies_test.dart:288]: indentation here looks funky?

Comment (jmagman) [reply dev/devicelab/bin/tasks/plugin_dependencies_test.dart:288]: Fixed, thanks.

**Comment by jmagman** [comment]
@domesticmouse This should resolve https://github.com/flutter/flutter/issues/66103.

File: dev/devicelab/bin/tasks/plugin_dependencies_test.dart [hunk 2]
```diff
@@ -274,13 +274,20 @@ public class DummyPluginAClass {
...
             options: <String>[
               'ios',
               '--no-codesign',
+              '-v',
             ],
           );
+           // This warning is confusing and shouldn't be emitted. Plugins often support lower versions than the
+           // Flutter app, but as long as they support the minimum it will work.
+           // warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'plugin_a' from project 'Pods')
+           if (output.contains('but the range of supported deployment target versions')) {
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/plugin_dependencies_test.dart:288]: I may be wrong (hard to tell in GitHub), but it looks to me like lines 285-288 are indented 1 col too far, while 289-290 look ok?

File: packages/flutter_tools/bin/podhelper.rb [hunk 3]
```diff
@@ -27,8 +27,17 @@ def flutter_ios_podfile_setup
 # end
 # @param [PBXAggregateTarget] target Pod target.
 def flutter_additional_ios_build_settings(target)
+  return unless target.platform_name == :ios
+
+  # [target.deployment_target] is a [String] formatted as "8.0".
+  inherit_deployment_target = target.deployment_target[/\d+/].to_i < 9
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/podhelper.rb:33]: should we leave a breadcrumb comment at the location in the tool where we define the min version to also update this magic constant?

File: dev/devicelab/bin/tasks/plugin_dependencies_test.dart [hunk 4]
```diff
@@ -274,13 +274,20 @@ public class DummyPluginAClass {
         section('Build plugin A example iOS app');
 
         await inDirectory(exampleApp, () async {
-          await evalFlutter(
+          final String output = await evalFlutter(
```
Comment (xster) [inline dev/devicelab/bin/tasks/plugin_dependencies_test.dart:277]: I'm not sure this is the best place to put it. Since it's a test to check that interdependencies in plugins work correctly rather than checking the project->plugin connection. Should this just be in plugin_tests.dart?

Also how do we know plugins A/B/C/D says iOS 8? Tangentially, do we need to update https://github.com/flutter/flutter/blob/6b049372927f21f3d0de6d08d67545ae130c4a35/packages/flutter_tools/templates/plugin/ios-swift.tmpl/projectName.podspec.tmpl#L18 as well?

**Review by xster — APPROVED** [review]

File: dev/devicelab/bin/tasks/plugin_dependencies_test.dart (hunk 2 above)
Comment (jmagman) [reply dev/devicelab/bin/tasks/plugin_dependencies_test.dart:288]: You're right.  Good eye (again).

File: packages/flutter_tools/bin/podhelper.rb (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/bin/podhelper.rb:33]: Good idea.

File: dev/devicelab/bin/tasks/plugin_dependencies_test.dart (hunk 4 above)
Comment (jmagman) [reply dev/devicelab/bin/tasks/plugin_dependencies_test.dart]: > Should this just be in plugin_tests.dart?

I moved it there, see if you like it better.

> Also how do we know plugins A/B/C/D says iOS 8?

I changed the test to make the plugin version low (7.0) so it would trigger the warning on the devicelab machines running Xcode 11.

> Tangentially, do we need to update https://github.com/flutter/flutter/blob/6b049372927f21f3d0de6d08d67545ae130c4a35/packages/flutter_tools/templates/plugin/ios-swift.tmpl/projectName.podspec.tmpl#L18 as well?

If we updated to `s.platform = :ios, '9.0'` then newly created plugins would not be usable (complication error) in any projects created before https://github.com/flutter/flutter/issues/60035, and we have no migration (yet) to increase this value in already existing apps.

**Comment by xster** [comment]
LGTM!
