### PR TITLE
Suggest GitHub template when flutter tool crashes

### LINKED ISSUE #44126: Tool error output should include a proposed GitHub issue template
## Proposal

Anywhere the tool says "please let us know at https://github.com/flutter/flutter/issues" it could also print a proposed GitHub issue template that includes:
- Proposed title (example: error text, location of crash)
- The actual output of `flutter doctor -v`
- Last x flutter commands run
- First x number of useful lines from the crash stack trace
- Plugins w/ versions
- Useful info from the pubspec.yaml
- Other useful things we can think of

### LINKED ISSUE #45617: flutter build crash not chatty
## Use case

`flutter build ios` only reports that it is crashing and that it is sending a report without giving a reason. `flutter build ios -v` tells what happend.

My Example is:
```
huhus-imac:haha huhu$ flutter build ios
Building com.haxmex.haha for device (ios-release)...

Sending crash report to Google.
Crash report sent (report ID: d4f864c58d167a30)
Oops; flutter has exited unexpectedly.
Crash report written to /Users/huhu/haha/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
huhus-imac:haha huhu$ flutter build ios -v
[  +20 ms] executing: [/Users/huhu/flutter/] git log -n 1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/Users/huhu/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[   +7 ms] executing: [/Users/huhu/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/huhu/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/Users/huhu/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +70 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +70 ms] Found plugin connectivity at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+6/
[   +4 ms] Found plugin firebase_messaging at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.1/
[  +10 ms] Found plugin google_maps_flutter at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+12/
[  +10 ms] Found plugin path_provider at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.5/
[   +5 ms] Found plugin shared_preferences at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+6/
[   +3 ms] Found plugin sqflite at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.7+3/
[   +8 ms] Found plugin url_launcher at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.7/
[  +19 ms] Unable to locate an Android SDK.
[  +12 ms] Found plugin connectivity at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+6/
[   +4 ms] Found plugin firebase_messaging at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.1/
[   +7 ms] Found plugin google_maps_flutter at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+12/
[   +8 ms] Found plugin path_provider at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.5/
[   +3 ms] Found plugin shared_preferences at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+6/
[   +2 ms] Found plugin sqflite at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.7+3/
[   +4 ms] Found plugin url_launcher at /Users/huhu/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.7/
[ +130 ms] executing: /usr/bin/plutil -convert json -o - /Users/huhu/haha/ios/Runner/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/huhu/haha/ios/Runner/Info.plist
[        ]
{"CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)","CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","CFBundleInfoDictionaryVersion":"6.0","UIMainStoryboardFile":"Main","CFB
undleVersion":"$(FLUTTER_BUILD_NUMBER)","UILaunchStoryboardName":"LaunchScreen","CFBundleExecutable":"$(EXECUTABLE_NAME)","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientati
ons":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"CFBundleSig
nature":"????","CFBundlePackageType":"APPL","CFBundleDevelopmentRegion":"$(DEVELOPMENT_LANGUAGE)","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInt
erfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleName":"haha"}
[  +18 ms] Building com.haxmex.haha for device (ios-release)...
[  +36 ms] executing: [/Users/huhu/haha/ios/] /usr/bin/xcodebuild -list
[ +486 ms] xcodebuild: error: The directory /Users/huhu/haha/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project
to use with the -project option.
[  +10 ms] "flutter ios" took 949ms.
```

## Proposal

Is it possible to give a short reason on a crash?

### PR DESCRIPTION
**Pull request by jmagman**
## Description

When the Flutter tool crashes, suggest a GitHub template that contains the command, stacktrace, flutter doctor -v, and some metadata if the working directory is a Flutter project.

I discussed with @InMatrix and he suggested we not show the "Sending crash report to Google." with the report ID by default, because users will think they don't need to report their crash because _something_ was automatically sent, so I moved that line to a trace log.

Also, `usesAndroidX` was crashing if the module section wasn't present, so I fixed that.

The GitHub URL has been shortened with [GitHub's URL shortener API](https://github.blog/2011-11-10-git-io-github-url-shortener/).

## Example
I faked out a crash.
```
$ flutter logs -d d83d5bc53967baa0ee18626ba87b6254b2ab5418

Oops; flutter has exited unexpectedly: "Exception: VersionCheckError: Command exited with code -9: git log -n 1
--pretty=format:%ad --date=iso".
A crash report has been written to /Users/m/Projects/test_create_swift/flutter_08.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JePo1

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JePia
```

And here's what it looks like visually to the user:
Screen Shot 2019-11-25 at 4 34 47 PM

And here's the GitHub template when you click on that big link (try it!):

**Title**
[tool_crash] Exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
===========BODY START===========
## Command
```
flutter logs -d 389148FB-E436-4F8B-B37A-8564AF1627C0
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception: Exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
```
#0      LogsCommand.runCommand (package:flutter_tools/src/commands/logs.dart:46:5)
#1      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:600:18)
<asynchronous suspension>
#2      LogsCommand.verifyThenRunCommand (package:flutter_tools/src/commands/logs.dart:40:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:500:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:490:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
```
```
[✓] Flutter (Channel unknown, v1.12.8-pre.7, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.12.8-pre.7 at /Users/m/Projects/flutter
    • Framework revision a152c2c334 (12 minutes ago), 2019-11-21 13:00:17 -0800
    • Engine revision 7a77e3625d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/m/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Users/m/Applications/Xcode-11_2.app/Contents/Developer
    • Xcode 11.2, Build version 11B41
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.3
    • Dart plugin version 192.7402

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 389148FB-E436-4F8B-B37A-8564AF1627C0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
camera

===========BODY END===========

(The ===========BODY=========== ASCII art isn't in there, it's to try to make this issue-in-PR description easier to see)

## Possible Future Work
1. ~Use URL shortener for that long link (cons: networking while crashing, though we do send that crash report).~ Done!
2. Check GitHub for related issues and actually print the top 3 sorted by reaction (cons: networking while crashing).
3. Work with IDE teams to give a better hook into this, i.e. a popup with button to file the crash.
4. Plugin versions.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44126.
Fixes https://github.com/flutter/flutter/issues/45617.

## Tests

Added a runner test, added new GitHub template tests, fixed up a few others based on the new input.
Added `usesAndroidX` tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/runner.dart [hunk 1]
```diff
@@ -128,18 +132,52 @@ Future<int> _handleToolError(
...
     );
 
-    if (error is String) {
-      stderr.writeln('Oops; flutter has exited unexpectedly: "$error".');
-    } else {
-      stderr.writeln('Oops; flutter has exited unexpectedly.');
-    }
+    final String command = _crashCommand(args);
+
+    final String errorString = error is String ? error : error.toString();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/runner.dart]: nit, since String.toString() returns self, just call `toString()` here

File: packages/flutter_tools/lib/runner.dart [hunk 2]
```diff
@@ -128,18 +132,52 @@ Future<int> _handleToolError(
...
+```
+
+## Flutter Application Metadata
+${_projectMetadataInformation()}
+''';
+      printStatus('https://github.com/flutter/flutter/issues/new?title=${Uri.encodeQueryComponent(title)}'
+        '&body=${Uri.encodeQueryComponent(body)}'
+        '&labels=${Uri.encodeQueryComponent('tool,severe: crash')}\n', wrap: false);
+
+      printStatus('Oops; flutter has exited unexpectedly.', emphasis: true, color: TerminalColor.red);
```
Comment (jmagman) [inline packages/flutter_tools/lib/runner.dart]: I wanted this to be `printError` but when I changed it to that it always printed before some of the above status lines.  I'm guessing stderr has more aggressive flush behavior, and none of the stdout flushes I tried seemed to help.  Open to suggestions.

File: packages/flutter_tools/lib/runner.dart [hunk 3]
```diff
@@ -128,18 +132,52 @@ Future<int> _handleToolError(
...
+
       return _exit(1);
     } catch (error) {
       stderr.writeln(
```
Comment (jmagman) [inline packages/flutter_tools/lib/runner.dart]: Keeping this vanilla and bland: something Bad is happening.

File: packages/flutter_tools/lib/src/doctor.dart [hunk 4]
```diff
@@ -284,18 +284,18 @@ class Doctor {
       DoctorResultEvent(validator: validator, result: result).send();
 
       if (result.statusInfo != null) {
-        printStatus('${result.coloredLeadingBox} ${validator.title} (${result.statusInfo})',
+        printStatus('${showColor ? result.coloredLeadingBox : result.leadingBox} ${validator.title} (${result.statusInfo})',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/doctor.dart]: Avoid printing the terminal color markers in the GitHub template or crash log.

File: packages/flutter_tools/lib/runner.dart [hunk 5]
```diff
@@ -155,6 +193,48 @@ Future<int> _handleToolError(
   }
 }
 
+String _crashCommand(List<String> args) => 'flutter ${args.join(' ')}';
+
+String _projectMetadataInformation() {
+  FlutterProject project;
+  try {
+    project = FlutterProject.current();
+  } catch (_) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/runner.dart]: this should probably `catch Exception`, to avoid catching NoSuchMethodError, TypeError, and friends. It would probably be something like a FormatException or a FileSystemException, right?

**Review by jonahwilliams — COMMENTED** [review]
This is great. Just took a quick look so far

File: packages/flutter_tools/lib/runner.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: Looking through the code I could only see it throwing when the pubspec is malformed, which come to think of it, would be very interesting in an issue report.  Will make this return the exception text

File: packages/flutter_tools/lib/runner.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/runner.dart]: Unfortunately it looks like `dart:io` `stdout.flush()` only flushes any buffering in Dart's memory. It doesn't actually result in a `flush()` call on the underlying fd to the OS.

File: packages/flutter_tools/lib/runner.dart [hunk 6]
```diff
@@ -128,18 +132,52 @@ Future<int> _handleToolError(
...
+    final String errorString = error.toString();
+    printError(errorString);
 
     try {
-      final File file = await _createLocalCrashReport(args, error, stackTrace);
-      stderr.writeln(
-        'Crash report written to ${file.path};\n'
-            'please let us know at https://github.com/flutter/flutter/issues.',
-      );
+      final String doctorText = await _doctorText();
```
Comment (zanderso) [inline packages/flutter_tools/lib/runner.dart]: Hopefully the doctor won't crash, but I think it would be good to guard against it separately and continue with printing the github issue instructions.

File: packages/flutter_tools/lib/runner.dart [hunk 7]
```diff
@@ -128,18 +132,52 @@ Future<int> _handleToolError(
       command: args.join(' '),
     );
 
-    if (error is String) {
-      stderr.writeln('Oops; flutter has exited unexpectedly: "$error".');
-    } else {
-      stderr.writeln('Oops; flutter has exited unexpectedly.');
-    }
+    final String command = _crashCommand(args);
```
Comment (zanderso) [inline packages/flutter_tools/lib/runner.dart]: Consider whether moving some or all of the code under the else on 115 into a separate method would improve readability of `_handleToolError`.

File: packages/flutter_tools/lib/src/doctor.dart (hunk 4 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/doctor.dart]: Consider using a local variable for `showColor ? result.coloredLeadingBox : result.leadingBox`.

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart [hunk 8]
```diff
@@ -19,7 +20,10 @@ import '../../src/context.dart';
 
 void main() {
   group('runner', () {
+    BufferLogger bufferLogger;
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/runner/runner_test.dart]: IIRC `testUsingContext` already injects a `BufferLogger` called `testLogger` or something like that.

**Review by zanderso — COMMENTED** [review]
I love this change.

My biggest concern is that the length of the URL will discourage folks from copying it into their browser.

W.r.t. hitting the network while crashing, we can print a big URL if that fails, for example.

File: packages/flutter_tools/lib/runner.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: I'm okay with an angry-looking red status.

File: packages/flutter_tools/lib/runner.dart (hunk 6 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: doctor exceptions are already caught in `_doctorText`.

File: packages/flutter_tools/lib/runner.dart (hunk 7 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: There was enough complicated try/catch and early returns that I just pulled out the wall-o-text part.  Hopefully that makes it readable enough.

**Comment by jmagman** [comment]
> I love this change.
> 
> My biggest concern is that the length of the URL will discourage folks from copying it into their browser.
> 
> W.r.t. hitting the network while crashing, we can print a big URL if that fails, for example.

Are you cool with that being a future improvement, or do you want the URL shortening in this PR?

**Comment by zanderso** [comment]
> @zanderso Are you cool with that being a future improvement, or do you want the URL shortening in this PR?

If you can do it in this PR that would be great. If splitting it up makes life a lot easier, I would prefer that this not land until after the current release cycle so we don't have the big URLs on stable.

**Comment by jmagman** [comment]
> If you can do it in this PR that would be great. If splitting it up makes life a lot easier, I would prefer that this not land until after the current release cycle so we don't have the big URLs on stable.

@zanderso
I have the git.io shortener working.  Here's what it looks like now:
```
$ flutter logs -d d83d5bc53967baa0ee18626ba87b6254b2ab5418

Oops; flutter has exited unexpectedly: "Exception: VersionCheckError: Command exited with code -9: git log -n 1
--pretty=format:%ad --date=iso".
A crash report has been written to /Users/magder/Projects/test_create_swift/flutter_08.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JePo1

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue. Paste this link into your browser and complete the template. Thank you!
https://git.io/JePia
```
Screen Shot 2019-11-25 at 4 34 47 PM

File: packages/flutter_tools/lib/runner.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: I switched this back to an error at the top since now the output is much smaller and I'm less worried about it getting scrolled out of view.

File: packages/flutter_tools/lib/runner.dart (hunk 7 above)
Comment (jmagman) [reply packages/flutter_tools/lib/runner.dart]: I moved it into its own file.

File: packages/flutter_tools/test/general.shard/github_template_test.dart [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+    });
+
+    testUsingContext('new issue template URL', () async {
+      final GitHubTemplateCreator creator = GitHubTemplateCreator();
+      const String command = 'flutter test';
+      const String errorString = 'this is a 100% error';
+      const String exception = 'failing to succeed!!!';
+      final StackTrace stackTrace = StackTrace.fromString('trace');
+      const String doctorText = ' [✓] Flutter (Channel report';
+
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/github_template_test.dart]: extra newline

File: packages/flutter_tools/test/general.shard/github_template_test.dart [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+const String _kShortURL = 'https://www.example.com/short';
+
+void main() {
+  group('GitHub template creator', () {
+
+    testUsingContext('similar issues URL', () async {
+      final GitHubTemplateCreator creator = GitHubTemplateCreator();
+      expect(
+        await creator.toolCrashSimilarIssuesGitHubURL('this is a 100% error'),
+        _kShortURL);
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/github_template_test.dart]: Formatting nit: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation

```dart
expect(
  await creator.toolCrashSimilarIssuesGitHubURL('this is a 100% error'),
  _kShortURL,
);
```

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart [hunk 11]
```diff
@@ -74,6 +78,58 @@ void main() {
...
+      when(mockGitHubTemplateCreator.toolCrashSimilarIssuesGitHubURL(any))
+        .thenAnswer((_) async => similarURL);
+      const String templateURL = 'https://example.com/2';
+      when(mockGitHubTemplateCreator.toolCrashIssueTemplateGitHubURL(any, any, any, any, any))
+        .thenAnswer((_) async => templateURL);
+      final Completer<void> completer = Completer<void>();
+      // runner.run() asynchronously calls the exit function set above, so we
+      // catch it in a zone.
+      unawaited(runZoned<Future<void>>(
+          () {
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/runner/runner_test.dart]: indentation: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#indent-multi-line-argument-and-parameter-lists-by-2-characters

**Review by zanderso — APPROVED** [review]
lgtm w/ nits

File: packages/flutter_tools/lib/src/reporting/github_template.dart [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+  ///
+  /// See https://github.blog/2011-11-10-git-io-github-url-shortener.
+  Future<String> _shortURL(String fullURL) async {
+    String url;
+    try {
+      printTrace('Attempting git.io shortener: $fullURL');
+      final List<int> bodyBytes = utf8.encode('url=${Uri.encodeQueryComponent(fullURL)}');
+      final HttpClientRequest request = await _client.postUrl(Uri.parse('https://git.io'));
+      request.headers.set(HttpHeaders.contentLengthHeader, bodyBytes.length.toString());
+      request.add(bodyBytes);
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/reporting/github_template.dart:125]: I didn't realize this code existed until just now... surely this is potentially sending PII to GitHub? This seems like a problem.

**Comment by zanderso** [comment]
My recollection is that the information is sanitized to contain only information about tool internals e.g. a sanitized exception message and a stack trace containing only flutter_tool frames, but @jmagman and @christopherfujino should verify.

We should also revisit whether this has improved the quality of filed issues. Maybe @stuartmorgan can help us ask the triagers if issues filed with this template have good signal.

**Comment by zanderso** [comment]
For reference here is an example https://github.com/flutter/flutter/issues/54213

**Comment by stuartmorgan** [comment]
> We should also revisit whether this has improved the quality of filed issues. Maybe @stuartmorgan can help us ask the triagers if issues filed with this template have good signal.

I can ask, but given that the audience for the stack information is primarily the tools team, not first-stage triagers, wouldn't having the tools team audit https://github.com/flutter/flutter/issues?q=is%3Aissue+tool_crash+in%3Atitle for value tell us more about how well the template works?

**Comment by Hixie** [comment]
It includes paths (which can include usernames), device IDs, potentially private plugin names, potentially sensitive arguments...

**Comment by Hixie** [comment]
For the record I've nothing against us filing bugs with this information, it's only the short link creation that's a problem because we don't prompt the user before uploading the information.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/53140 for discussion about removing the URL shortener.

**Comment by stuartmorgan** [comment]
> We should also revisit whether this has improved the quality of filed issues. Maybe @stuartmorgan can help us ask the triagers if issues filed with this template have good signal.

Feedback is the template is providing good signal (ability to effectively dup, avoiding round-trip requests for more information, etc.). So eliminating it completely would definitely not be ideal.
