### PR TITLE
Much work on the documentation

### LINKED ISSUE #9331: API docs need diagrams, screenshots, illustrations
If the Flutter API docs are a primary resource for our developers, then we need to find a way to include diagrams, screenshots, and other illustrations.  We're an API for user interfaces after all.

For example the AppBar doc would really benefit from a diagram of an AppBar that identified the AppBar's elements: leading, title, actions, flexibleSpace, botttom. It would also be helpful to include screenshots that shows how AppBar reflects the current TargetPlatform.

It would be a shame if this was the last word per including images in dart doc:  https://github.com/dart-lang/dartdoc/issues/502

### LINKED ISSUE #9407: Add curated sample code to each Widget class in the dartdocs
Some have it, but many don't.

### LINKED ISSUE #10267: SliverAppBar shadow is not transparent when background color is
## Steps to Reproduce

Create a CustomScrollView with 
```dart 
new SliverAppBar(
                  title: new Text('Bar'),
                  pinned: true,
                  snap: false,
                  floating: false,
                  backgroundColor: new Color.fromRGBO(0, 0, 0, 0.0),
```

screen shot 2017-05-23 at 13 15 22

Thanks.

### LINKED ISSUE #10316: Make "scrollable list" something you can find when searching widgets-library
From someone trying Flutter for the second time:
> Lots of "List" on the API page, but found "ListView" relatively fast. In the gallery they are called "scrollable" list, but searching for "scrollable list" on the widgets-library page doesn't trigger, because it is described as "A scrollable, linear list of widgets".

### LINKED ISSUE #10317: Make "spin" and "busy" keywords you can use to find progress indicator.
From someone trying Flutter for the second time:
> found progress indicators in the gallery. A search for "spin" or "busy" on the dartdocs didn't help me.

### PR DESCRIPTION
**Pull request by Hixie**
Minor fixes throughout, e.g. removing trailing commas from the end of sample code expressions, changing headings to "sample code" more consistently, removing stale todos, fix typos in a private method name, minor grammar fixes, added some clarifications to CircularProgressIndicator, LinearProgressIndicator, CrossAxisAlignment, added some cross-references to various members, made it slightly clearer that layout algorithms are implementation details.

Clarified "elevation" throughout.

Added docs to InkResponse and InkWell.

Added sample code for: SliverAppBar, Card, ListTile, EdgeInsets, Row, Column, CustomScrollView, ListView, SliverFixedExtentList, and SliverGrid.

Fixes #10317.
Fixes #10316.
Fixes #10267. (sort of, see comment therein)
Fixes #9331. (sort of, see comment therein)
Fixes #9407. (sort of, see comment therein)

### CODE REVIEW

File: packages/flutter/lib/src/material/button.dart [hunk 1]
```diff
@@ -195,14 +195,27 @@ class MaterialButton extends StatefulWidget {
...
 
-  /// The z-coordinate at which to place this button.
+  /// The z-coordinate at which to place this button. This controls the size of
+  /// the shadow below the button.
   ///
   /// Defaults to 0.
+  ///
+  /// See also:
+  ///
+  ///  * [FlatButton], a material button specialised for the case where the
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button.dart]: I think specialised is the UK spelling. I think we're going to just live with UK spellings :-)

File: packages/flutter/lib/src/material/list_tile.dart [hunk 2]
```diff
@@ -151,10 +151,38 @@ enum ListTileControlAffinity {
...
+/// which is disabled when the `_act` variable is not 2. When the tile is
+/// tapped, the whole row has an ink splash effect (see [InkWell]).
+///
+/// ```dart
+/// int _act = 1;
+/// // ...
+/// new ListTile(
+///   leading: const Icon(Icons.flight_land),
+///   title: const Text('Trix\'s plane'),
+///   subtitle: _act != 2 ? const Text('The plane is only in Act II.') : null,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: Did you mean 'play'?

File: packages/flutter/lib/src/rendering/flex.dart [hunk 3]
```diff
@@ -91,19 +91,34 @@ enum MainAxisAlignment {
...
+  /// Place the children with their start edge aligned with the start side of
+  /// the cross axis.
+  ///
+  /// For example, in a column (a flex with a vertical axis), this aligns the
+  /// left edge of the children along the left edge of the column.
   start,
 
   /// Place the children as close to the end of the cross axis as possible.
+  ///
+  /// For example, in a column (a flex with a vertical axis), this aligns the
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/flex.dart]: a [Flex] with a vertical axis?

File: packages/flutter/lib/src/rendering/flex.dart [hunk 4]
```diff
@@ -91,19 +91,34 @@ enum MainAxisAlignment {
...
+  /// right edge of the children along the right edge of the column.
   end,
 
-  /// Place the children as close to the middle of the cross axis as possible.
+  /// Place the children so that their center in the middle of the cross axis.
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/flex.dart]: their center aligns with the middle...

File: packages/flutter/lib/src/widgets/basic.dart [hunk 5]
```diff
@@ -2184,6 +2222,15 @@ class Flex extends MultiChildRenderObjectWidget {
...
 ///    space that has not been allocated to children is divided evenly and
 ///    placed between the children.
+///
+/// See also:
+///
+///  * [Column], for a vertical equivalent.
+///  * [Flex], if you don't know in advance if you want a horizontal or vertical
+///    arrangement.
+///  * [Expanded], to indicate children that should take all the remaining room.
+///  * [Flexible], to indicate children that should share the remaining room but
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/basic.dart]: but that may size => but might be sized

File: packages/flutter/lib/src/widgets/basic.dart [hunk 6]
```diff
@@ -2223,8 +2270,52 @@ class Row extends Flex {
...
+/// This example uses a [Column] to arrange three widgets vertically, the last
+/// being made to fill all the remaining space.
+///
+/// ```dart
+/// new Column(
+///   children: <Widget>[
+///     new Text('Deliver features faster'),
+///     new Text('Craft beautiful UIs'),
+///     new Expanded(
+///       child: new FittedBox(
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/basic.dart]: It's not clear why the FittedBox is needed here.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 7]
```diff
@@ -2223,8 +2270,52 @@ class Row extends Flex {
...
+///         child: const FlutterLogo(),
+///       ),
+///     ),
+///   ],
+/// )
+/// ```
+///
+/// In the sample above, the text and the logo are centered on each line. In the
+/// following example, the [crossAxisAlignment] is set to
+/// [CrossAxisAlignment.start], so that the children are left-aligned. The
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/basic.dart]: I wonder if terms like 'left-aligned' are going to haunt us when RTL layouts are supported.

**Comment by HansMuller** [comment]
LGTM

File: packages/flutter/lib/src/material/button.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/material/button.dart]: Please continue to point out UK spellings. I've been using US and UK spellings for so long I never know which is which. Flutter uses the US spelling.

Comment (Hixie) [inline packages/flutter/lib/src/material/button.dart]: fixed

File: packages/flutter/lib/src/material/list_tile.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/material/list_tile.dart]: I'll change it to airplane.

File: packages/flutter/lib/src/rendering/flex.dart (hunk 3 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/flex.dart]: I've added some "see also"s to the enum definition, but I'm reluctant to point to [Flex] too strongly.

File: packages/flutter/lib/src/rendering/flex.dart (hunk 4 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/flex.dart]: fixed.

File: packages/flutter/lib/src/widgets/basic.dart (hunk 6 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: i've added a comment:
```
///         fit: BoxFit.contain, // otherwise the logo will be tiny```

File: packages/flutter/lib/src/widgets/basic.dart (hunk 7 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: that's why i refer specifically to the example (which is in English). I agree we shouldn't say left-aligned in general.

**Comment by Hixie** [comment]
Thanks for the review. Will land on green.
