### PR TITLE
Fix Scrollbar drag behavior

### LINKED ISSUE #178863: CustomScrollView's Scrollbar is not draggable when using a center key for a empty sliverlist with an anchor of 1.0
### Steps to reproduce

1. Create a CustomScrollView.
2. Give it a center key.
3. Assign it a anchor of 1.0.
4. Pass in a normal sliverlist with some children such that the viewport of the application will become scrollable.
5. Pass in a sliverlist with no children present and have that sliverlist hold the center key.

### Expected results

When clicking and dragging the scollbar I should be able to navigate up/down the list.

### Actual results

When clicking and dragging the scollbar via the mouse you are not able to navigate up/down the list (you can however scroll it - as shown in the provided video).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [CustomScrollView].

void main() => runApp(const CustomScrollViewExampleApp());

class CustomScrollViewExampleApp extends StatelessWidget {
  const CustomScrollViewExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: CustomScrollViewExample());
  }
}

class CustomScrollViewExample extends StatefulWidget {
  const CustomScrollViewExample({super.key});

  @override
  State<CustomScrollViewExample> createState() => _CustomScrollViewExampleState();
}

class _CustomScrollViewExampleState extends State<CustomScrollViewExample> {
  @override
  Widget build(BuildContext context) {
    final items = List<int>.generate(100, (index) => index);

    const Key centerKey = ValueKey<String>('bottom-sliver-list');
    return Scaffold(
      appBar: AppBar(
        title: const Text('Bug demo'),
      ),
      body: CustomScrollView(
        center: centerKey,
        anchor: 1.0,
        slivers: <Widget>[
          SliverList.builder(
            itemCount: items.length,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                alignment: Alignment.center,
                color: Colors.blue[200 + items[index] % 4 * 100],
                height: 100 + items[index] % 4 * 20.0,
                child: Text('Item: ${items[index]}'),
              );
            },
          ),
          SliverList.builder(
            key: centerKey,
            itemCount: 0,
            itemBuilder: (BuildContext context, int index) {
              return Text("This is not going to be present");
            },
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/7649a351-1e44-4ad8-b499-200e37240b47

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.4, on macOS 15.6 24G84 darwin-arm64, locale en-GB) [96ms]
    • Flutter version 3.35.4 on channel stable at /opt/homebrew/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d693b4b9db (9 weeks ago), 2025-09-16 14:27:41 +0000
    • Engine revision c298091351
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop,
      enable-android, enable-ios, cli-animations, enable-lldb-debugging

[✗] Android toolchain - develop for Android devices [58ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [303ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed) [4ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] Connected device (3 available) [5.5s]
...

[✓] Network resources [172ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by RamonFarizel**
Updates `_canHandleScrollGestures()` to check if there's an actual scrollable range (`maxScrollExtent > minScrollExtent`) instead of only checking if `maxScrollExtent > 0.0`.

Fixes https://github.com/flutter/flutter/issues/178863

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/scrollbar_test.dart [hunk 1]
```diff
@@ -1766,4 +1766,36 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
     );
     expect(tester.getSize(find.byType(Scrollbar)), Size.zero);
   });
+
+  testWidgets('Scrollbar gestures disabled when maxScrollExtent == minScrollExtent', (
```
Comment (victorsanni) [inline packages/flutter/test/material/scrollbar_test.dart]: This test passes on `master`.

File: packages/flutter/test/material/scrollbar_test.dart [hunk 2]
```diff
@@ -1766,4 +1766,36 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
     );
     expect(tester.getSize(find.byType(Scrollbar)), Size.zero);
   });
+
```
Comment (victorsanni) [inline packages/flutter/test/material/scrollbar_test.dart]: I'm wondering why the test is in `material/scrollbar_test.dart` and not `widgets.scrollbar_test.dart`.

File: packages/flutter/test/material/scrollbar_test.dart (hunk 1 above)
Comment (RamonFarizel) [reply packages/flutter/test/material/scrollbar_test.dart]: Does it require any further action?

File: packages/flutter/test/material/scrollbar_test.dart (hunk 2 above)
Comment (RamonFarizel) [reply packages/flutter/test/material/scrollbar_test.dart]: I see. So I'll move it to the correct file and make the necessary changes.

File: packages/flutter/test/material/scrollbar_test.dart (hunk 1 above)
Comment (victorsanni) [reply packages/flutter/test/material/scrollbar_test.dart]: yes, if the test passes without the changes in this PR then it doesn't sufficiently prevent the changes in this PR from being regressed.

Comment (RamonFarizel) [reply packages/flutter/test/material/scrollbar_test.dart]: I see. I'll try something else. Thanks

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 3]
```diff
@@ -2027,7 +2027,8 @@ class RawScrollbarState<T extends RawScrollbar> extends State<T> with TickerProv
         _effectiveScrollController != null &&
         _effectiveScrollController!.positions.length == 1 &&
         _effectiveScrollController!.position.hasContentDimensions &&
-        _effectiveScrollController!.position.maxScrollExtent > 0.0;
+        _effectiveScrollController!.position.maxScrollExtent >
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/scrollbar.dart]:
```suggestion
        _effectiveScrollController!.position.maxScrollExtent - _effectiveScrollController!.position.minScrollExtent > precisionErrorTolerance
```

**Review by chunhtai — APPROVED** [review]
LGTM
