### PR TITLE
[web:tools] disable search engine choice screen in flutter run

### LINKED ISSUE #153928: Chrome "Choose your search engine" dialog appears on clean run (only EU)
### Steps to reproduce

1. Use Chrome >127 in EU
2. flutter clean
3. flutter run -d chrome

### Expected results

Chrome starts without search engine selector.

A possible solution is add `--disable-search-engine-choice-screen` to Chrome run args here:
https://github.com/flutter/flutter/blob/59e6c8d52f11ca9bd4aedd73a0dc412f7c5c3a21/packages/flutter_tools/lib/src/web/chrome.dart#L200

As described here:
https://stackoverflow.com/questions/78787332/selecting-default-search-engine-is-needed-for-chrome-version-127

### Actual results

Chrome "choose your search engine" dialog appears. 

### Code sample

<details open><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Képernyőfotó 2024-08-22 - 15 53 43

</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale hu-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by yjbanov**
The choice screen is irrelevant when debugging apps locally. `flutter run` creates a separate user profile for testing only. It doesn't touch users' browser settings.

Fixes https://github.com/flutter/flutter/issues/153928

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -214,6 +214,12 @@ class ChromiumLauncher {
       '--no-default-browser-check',
       '--disable-default-apps',
       '--disable-translate',
+
+      // Remove the search engine choice screen. It's irrelevant for app
+      // debugging purposes.
+      // See: https://github.com/flutter/flutter/issues/153928
+      '--disable-search-engine-choice-screen',
```
Comment (navaronbracke) [inline packages/flutter_tools/lib/src/web/chrome.dart:221]: Weren't there other places (i.e. where we have `--no-default-browser-check` as well) that could also benefit from this?
(for example the web benchmarks?)

Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:221]: Good point. I should have checked more carefully. However, now that I did check, it doesn't seem like it's necessary in those other places. The benchmark code is ad hoc for Flutter's own testing, and we use Chromium for that, where I don't think this is an issue. For `flutter drive` we use WebDriver, and I do not expect driver-initialized browser to put anything that would prevent tests from running. We may have to revisit if it comes up though.

**Review by kevmoo — APPROVED** [review]
are we sure this won't crash older chrome versions w/out this flag?

**Review by eyebrowsoffire — COMMENTED** [review]
LGTM

**Comment by navaronbracke** [comment]
> are we sure this won't crash older chrome versions w/out this flag?

IIRC Chrome ignores unrecognised flags?

**Comment by yjbanov** [comment]
Checked with Chrome 117. It happily ignores the flag.
