### PR TITLE
[flutter_tools] ensure track-widget-creation can be disabled on Android

### LINKED ISSUE #56188: --no-track-widget-creation ignored until hot restart
## Steps to Reproduce
This issue is found during investigation of this issue: #56099
1. Run `flutter create bug`.
2. Remove test folder and replace main.dart content with following code:
```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(Builder(builder: (context) {
    final a = const SizedBox();
    final b = const SizedBox();
    print(a == b);
    return Container();
  }));
}
```
3. steps to reproduce

3.1. fast steps to reproduce  until #56099 is fixed
  - `flutter run --no-track-widget-creation`
  - `r` hot reload
  - `R` hot restart
  - `r` hot restart

  **Expected results:** 
  ```
  true
  true
  true
  true
  ```
  **Actual results:** 
  ```
  false
  false
  true
  true
  ```
3.2. steps to reproduce using debugger
  - add `--no-track-widget-creation` flag as additional argument to configuration
  - set breakpoint at `print`
  - run debug
  image

  - hot reload
  image

  - hot restart
  image

  - hot reload
  image

<details>
  <summary>Logs</summary>

```
flutter run --no-track-widget-creation --verbose
[  +60 ms] executing: [/Users/iam/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +158 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/iam/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +65 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +21 ms] executing: [/Users/iam/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/iam/development/flutter/] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +113 ms] executing: [/Users/iam/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +11 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +23 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +24 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +58 ms] executing: /usr/bin/xcode-select --print-path
[  +15 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[+1044 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[ +176 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb devices -l
[  +17 ms] Exit code 0 from: /Users/iam/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           192.168.0.167:5555     device product:WAS-LX1 model:WAS_LX1 device:HWWAS-H transport_id:1
[  +36 ms] executing: /Users/iam/development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +117 ms] /usr/bin/xcrun simctl list --json devices
[ +807 ms] /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell getprop
[ +188 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +295 ms] Generating /Users/iam/Projects/oss/table_error_sample/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +46 ms] ro.hardware = hi6250
[        ] ro.build.characteristics = default
⣽[  +31 ms] executing: [/Users/iam/Projects/oss/table_error_sample/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/iam/Projects/oss/table_error_sample/ios/Runner.xcodeproj -target Runner
-showBuildSettings
[   +5 ms] executing: [/Users/iam/Projects/oss/table_error_sample/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/iam/Projects/oss/table_error_sample/ios/Runner.xcodeproj -target Runner
-showBuildSettings
 
(This is taking an unexpectedly long time.)⡿[+6692 ms] Build settings for action build and target Runner:
                        ACTION = build
                        AD_HOC_CODE_SIGNING_ALLOWED = NO
                        ALTERNATE_GROUP = staff
                        ALTERNATE_MODE = u+w,go-w,a+rX
                        ALTERNATE_OWNER = iam
                        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
                        ALWAYS_SEARCH_USER_PATHS = NO
                        ALWAYS_USE_SEPARATE_HEADERMAPS = NO
                        APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
                        APPLE_INTERNAL_DIR = /AppleInternal
                        APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
                        APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
                        APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
                        APPLICATION_EXTENSION_API_ONLY = NO
                        APPLY_RULES_IN_COPY_FILES = NO
                        APPLY_RULES_IN_COPY_HEADERS = NO
                        ARCHS = armv7 arm64
                        ARCHS_STANDARD = armv7 arm64
                        ARCHS_STANDARD_32_64_BIT = armv7 arm64
                        ARCHS_STANDARD_32_BIT = armv7
                        ARCHS_STANDARD_64_BIT = arm64
                        ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
                        ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
                        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
                        AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
                        BITCODE_GENERATION_MODE = marker
                        BUILD_ACTIVE_RESOURCES_ONLY = NO
                        BUILD_COMPONENTS = headers build
                        BUILD_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios
                        BUILD_LIBRARY_FOR_DISTRIBUTION = NO
                        BUILD_ROOT = /Users/iam/Projects/oss/table_error_sample/build/ios
                        BUILD_STYLE = 
                        BUILD_VARIANTS = normal
                        BUILT_PRODUCTS_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos
                        CACHE_ROOT = /var/folders/lt/g7n3c3h90s99_847ddbqn3f40000gn/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
                        CCHROOT = /var/folders/lt/g7n3c3h90s99_847ddbqn3f40000gn/C/com.apple.DeveloperTools/11.3.1-11C504/Xcode
                        CHMOD = /bin/chmod
                        CHOWN = /usr/sbin/chown
                        CLANG_ANALYZER_NONNULL = YES
                        CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
                        CLANG_CXX_LIBRARY = libc++
                        CLANG_ENABLE_MODULES = YES
                        CLANG_ENABLE_OBJC_ARC = YES
                        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
                        CLANG_WARN_BOOL_CONVERSION = YES
                        CLANG_WARN_COMMA = YES
                        CLANG_WARN_CONSTANT_CONVERSION = YES
                        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
                        CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
                        CLANG_WARN_EMPTY_BODY = YES
                        CLANG_WARN_ENUM_CONVERSION = YES
                        CLANG_WARN_INFINITE_RECURSION = YES
                        CLANG_WARN_INT_CONVERSION = YES
                        CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
                        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
                        CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
                        CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
                        CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
                        CLANG_WARN_STRICT_PROTOTYPES = YES
                        CLANG_WARN_SUSPICIOUS_MOVE = YES
                        CLANG_WARN_UNREACHABLE_CODE = YES
                        CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
                        CLASS_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
                        CLEAN_PRECOMPS = YES
                        CLONE_HEADERS = NO
                        CODESIGNING_FOLDER_PATH = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos/Runner.app
                        CODE_SIGNING_ALLOWED = YES
                        CODE_SIGNING_REQUIRED = YES
                        CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
                        CODE_SIGN_IDENTITY = iPhone Developer
                        CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
                        COLOR_DIAGNOSTICS = NO
                        COMBINE_HIDPI_IMAGES = NO
                        COMPILER_INDEX_STORE_ENABLE = Default
                        COMPOSITE_SDK_DIRS = /Users/iam/Projects/oss/table_error_sample/build/ios/CompositeSDKs
                        COMPRESS_PNG_FILES = YES
                        CONFIGURATION = Release
                        CONFIGURATION_BUILD_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos
                        CONFIGURATION_TEMP_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos
                        CONTENTS_FOLDER_PATH = Runner.app
                        COPYING_PRESERVES_HFS_DATA = NO
                        COPY_HEADERS_RUN_UNIFDEF = NO
                        COPY_PHASE_STRIP = NO
                        COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
                        CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
                        CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
                        CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
                        CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.2
                        CP = /bin/cp
                        CREATE_INFOPLIST_SECTION_IN_BINARY = NO
                        CURRENT_ARCH = arm64
                        CURRENT_PROJECT_VERSION = 1
                        CURRENT_VARIANT = normal
                        DEAD_CODE_STRIPPING = YES
                        DEBUGGING_SYMBOLS = YES
                        DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
                        DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
                        DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
                        DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
                        DEFINES_MODULE = NO
                        DEPLOYMENT_LOCATION = NO
                        DEPLOYMENT_POSTPROCESSING = NO
                        DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
                        DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
                        DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
                        DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2
                        DERIVED_FILES_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
                        DERIVED_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
                        DERIVED_SOURCES_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
                        DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
                        DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
                        DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
                        DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
                        DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
                        DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
                        DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
                        DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
                        DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
                        DEVELOPMENT_LANGUAGE = en
                        DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
                        DONT_GENERATE_INFOPLIST_FILE = NO
                        DO_HEADER_SCANNING_IN_JAM = NO
                        DSTROOT = /tmp/Runner.dst
                        DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                        DWARF_DSYM_FILE_NAME = Runner.app.dSYM
                        DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
                        DWARF_DSYM_FOLDER_PATH = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos
                        EFFECTIVE_PLATFORM_NAME = -iphoneos
                        EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
                        EMBEDDED_PROFILE_NAME = embedded.mobileprovision
                        EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
                        ENABLE_BITCODE = NO
                        ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
                        ENABLE_HARDENED_RUNTIME = NO
                        ENABLE_HEADER_DEPENDENCIES = YES
                        ENABLE_NS_ASSERTIONS = NO
                        ENABLE_ON_DEMAND_RESOURCES = YES
                        ENABLE_STRICT_OBJC_MSGSEND = YES
                        ENABLE_TESTABILITY = NO
                        ENTITLEMENTS_ALLOWED = YES
                        ENTITLEMENTS_DESTINATION = Signature
                        ENTITLEMENTS_REQUIRED = YES
                        EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
                        EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
                        EXECUTABLES_FOLDER_PATH = Runner.app/Executables
                        EXECUTABLE_FOLDER_PATH = Runner.app
                        EXECUTABLE_NAME = Runner
                        EXECUTABLE_PATH = Runner.app/Runner
                        EXPANDED_CODE_SIGN_IDENTITY = 
                        EXPANDED_CODE_SIGN_IDENTITY_NAME = 
                        EXPANDED_PROVISIONING_PROFILE = 
                        FILE_LIST = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
                        FIXED_FILES_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
                        FLUTTER_APPLICATION_PATH = /Users/iam/Projects/oss/table_error_sample
                        FLUTTER_BUILD_DIR = build
                        FLUTTER_BUILD_NAME = 1.0.0
                        FLUTTER_BUILD_NUMBER = 1
                        FLUTTER_FRAMEWORK_DIR = /Users/iam/development/flutter/bin/cache/artifacts/engine/ios
                        FLUTTER_ROOT = /Users/iam/development/flutter
                        FLUTTER_TARGET = lib/main.dart
                        FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
                        FRAMEWORK_FLAG_PREFIX = -framework
                        FRAMEWORK_SEARCH_PATHS =  /Users/iam/Projects/oss/table_error_sample/ios/Flutter
                        FRAMEWORK_VERSION = A
                        FULL_PRODUCT_NAME = Runner.app
                        GCC3_VERSION = 3.3
                        GCC_C_LANGUAGE_STANDARD = gnu99
                        GCC_INLINES_ARE_PRIVATE_EXTERN = YES
                        GCC_NO_COMMON_BLOCKS = YES
                        GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
                        GCC_SYMBOLS_PRIVATE_EXTERN = YES
                        GCC_THUMB_SUPPORT = YES
                        GCC_TREAT_WARNINGS_AS_ERRORS = NO
                        GCC_VERSION = com.apple.compilers.llvm.clang.1_0
                        GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
                        GCC_WARN_64_TO_32_BIT_CONVERSION = YES
                        GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
                        GCC_WARN_UNDECLARED_SELECTOR = YES
                        GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
                        GCC_WARN_UNUSED_FUNCTION = YES
                        GCC_WARN_UNUSED_VARIABLE = YES
                        GENERATE_MASTER_OBJECT_FILE = NO
                        GENERATE_PKGINFO_FILE = YES
                        GENERATE_PROFILING_CODE = NO
                        GENERATE_TEXT_BASED_STUBS = NO
                        GID = 20
                        GROUP = staff
                        HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
                        HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
                        HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
                        HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
                        HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
                        HEADERMAP_USES_VFS = NO
                        HIDE_BITCODE_SYMBOLS = YES
                        HOME = /Users/iam
                        ICONV = /usr/bin/iconv
                        INFOPLIST_EXPAND_BUILD_SETTINGS = YES
                        INFOPLIST_FILE = Runner/Info.plist
                        INFOPLIST_OUTPUT_FORMAT = binary
                        INFOPLIST_PATH = Runner.app/Info.plist
                        INFOPLIST_PREPROCESS = NO
                        INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
                        INLINE_PRIVATE_FRAMEWORKS = NO
                        INSTALLHDRS_COPY_PHASE = NO
                        INSTALLHDRS_SCRIPT_PHASE = NO
                        INSTALL_DIR = /tmp/Runner.dst/Applications
                        INSTALL_GROUP = staff
                        INSTALL_MODE_FLAG = u+w,go-w,a+rX
                        INSTALL_OWNER = iam
                        INSTALL_PATH = /Applications
                        INSTALL_ROOT = /tmp/Runner.dst
                        IPHONEOS_DEPLOYMENT_TARGET = 8.0
                        JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
                        JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
                        JAVA_ARCHIVE_CLASSES = YES
                        JAVA_ARCHIVE_TYPE = JAR
                        JAVA_COMPILER = /usr/bin/javac
                        JAVA_FOLDER_PATH = Runner.app/Java
                        JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
                        JAVA_JAR_FLAGS = cv
                        JAVA_SOURCE_SUBDIR = .
                        JAVA_USE_DEPENDENCIES = YES
                        JAVA_ZIP_FLAGS = -urg
                        JIKES_DEFAULT_FLAGS = +E +OLDCSO
                        KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
                        KEEP_PRIVATE_EXTERNS = NO
                        LD_DEPENDENCY_INFO_FILE = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
                        LD_GENERATE_MAP_FILE = NO
                        LD_MAP_FILE_PATH = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
                        LD_NO_PIE = NO
                        LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
                        LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
                        LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
                        LEX = lex
                        LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
                        LIBRARY_FLAG_NOSPACE = YES
                        LIBRARY_FLAG_PREFIX = -l
                        LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
                        LIBRARY_SEARCH_PATHS =  /Users/iam/Projects/oss/table_error_sample/ios/Flutter
                        LINKER_DISPLAYS_MANGLED_NAMES = NO
                        LINK_FILE_LIST_normal_arm64 = 
                        LINK_FILE_LIST_normal_armv7 = 
                        LINK_WITH_STANDARD_LIBRARIES = YES
                        LLVM_TARGET_TRIPLE_OS_VERSION = ios8.0
                        LLVM_TARGET_TRIPLE_VENDOR = apple
                        LOCALIZABLE_CONTENT_DIR = 
                        LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
                        LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
                        LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
                        LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
                        LOCAL_APPS_DIR = /Applications
                        LOCAL_DEVELOPER_DIR = /Library/Developer
                        LOCAL_LIBRARY_DIR = /Library
                        LOCROOT = 
                        LOCSYMROOT = 
                        MACH_O_TYPE = mh_execute
                        MAC_OS_X_PRODUCT_BUILD_VERSION = 19D76
                        MAC_OS_X_VERSION_ACTUAL = 101503
                        MAC_OS_X_VERSION_MAJOR = 101500
                        MAC_OS_X_VERSION_MINOR = 1503
                        METAL_LIBRARY_FILE_BASE = default
                        METAL_LIBRARY_OUTPUT_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos/Runner.app
                        MODULES_FOLDER_PATH = Runner.app/Modules
                        MODULE_CACHE_DIR = /Users/iam/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
                        MTL_ENABLE_DEBUG_INFO = NO
                        NATIVE_ARCH = armv7
                        NATIVE_ARCH_32_BIT = i386
                        NATIVE_ARCH_64_BIT = x86_64
                        NATIVE_ARCH_ACTUAL = x86_64
                        NO_COMMON = YES
                        OBJECT_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
                        OBJECT_FILE_DIR_normal = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
                        OBJROOT = /Users/iam/Projects/oss/table_error_sample/build/ios
                        ONLY_ACTIVE_ARCH = NO
                        OS = MACOS
                        OSAC = /usr/bin/osacompile
                        PACKAGE_TYPE = com.apple.package-type.wrapper.application
                        PASCAL_STRINGS = YES
                        PATH =
                        /Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/iam/development/flutter/bin:/Users/iam/Library/Android/sdk/platform-tools
                        PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks
                        /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
                        PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
                        PFE_FILE_C_DIALECTS = objective-c
                        PKGINFO_FILE_PATH = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
                        PKGINFO_PATH = Runner.app/PkgInfo
                        PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
                        PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
                        PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
                        PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
                        PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
                        PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
                        PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
                        PLATFORM_DISPLAY_NAME = iOS
                        PLATFORM_NAME = iphoneos
                        PLATFORM_PREFERRED_ARCH = arm64
                        PLATFORM_PRODUCT_BUILD_VERSION = 17B102
                        PLIST_FILE_OUTPUT_FORMAT = binary
                        PLUGINS_FOLDER_PATH = Runner.app/PlugIns
                        PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
                        PRECOMP_DESTINATION_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
                        PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
                        PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
                        PRODUCT_BUNDLE_IDENTIFIER = com.example.tableerrorsample
                        PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
                        PRODUCT_MODULE_NAME = Runner
                        PRODUCT_NAME = Runner
                        PRODUCT_SETTINGS_PATH = /Users/iam/Projects/oss/table_error_sample/ios/Runner/Info.plist
                        PRODUCT_TYPE = com.apple.product-type.application
                        PROFILING_CODE = NO
                        PROJECT = Runner
                        PROJECT_DERIVED_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/DerivedSources
                        PROJECT_DIR = /Users/iam/Projects/oss/table_error_sample/ios
                        PROJECT_FILE_PATH = /Users/iam/Projects/oss/table_error_sample/ios/Runner.xcodeproj
                        PROJECT_NAME = Runner
                        PROJECT_TEMP_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build
                        PROJECT_TEMP_ROOT = /Users/iam/Projects/oss/table_error_sample/build/ios
                        PROVISIONING_PROFILE_REQUIRED = YES
                        PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
                        RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
                        REMOVE_CVS_FROM_RESOURCES = YES
                        REMOVE_GIT_FROM_RESOURCES = YES
                        REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
                        REMOVE_HG_FROM_RESOURCES = YES
                        REMOVE_SVN_FROM_RESOURCES = YES
                        RESOURCE_RULES_REQUIRED = YES
                        REZ_COLLECTOR_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
                        REZ_OBJECTS_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
                        SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
                        SCRIPTS_FOLDER_PATH = Runner.app/Scripts
                        SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
                        SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
                        SDK_DIR_iphoneos13_2 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
                        SDK_NAME = iphoneos13.2
                        SDK_NAMES = iphoneos13.2
                        SDK_PRODUCT_BUILD_VERSION = 17B102
                        SDK_VERSION = 13.2
                        SDK_VERSION_ACTUAL = 130200
                        SDK_VERSION_MAJOR = 130000
                        SDK_VERSION_MINOR = 200
                        SED = /usr/bin/sed
                        SEPARATE_STRIP = NO
                        SEPARATE_SYMBOL_EDIT = NO
                        SET_DIR_MODE_OWNER_GROUP = YES
                        SET_FILE_MODE_OWNER_GROUP = NO
                        SHALLOW_BUNDLE = YES
                        SHARED_DERIVED_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos/DerivedSources
                        SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
                        SHARED_PRECOMPS_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/SharedPrecompiledHeaders
                        SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
                        SKIP_INSTALL = NO
                        SOURCE_ROOT = /Users/iam/Projects/oss/table_error_sample/ios
                        SRCROOT = /Users/iam/Projects/oss/table_error_sample/ios
                        STRINGS_FILE_OUTPUT_ENCODING = binary
                        STRIP_BITCODE_FROM_COPIED_FILES = YES
                        STRIP_INSTALLED_PRODUCT = YES
                        STRIP_STYLE = all
                        STRIP_SWIFT_SYMBOLS = YES
                        SUPPORTED_DEVICE_FAMILIES = 1,2
                        SUPPORTED_PLATFORMS = iphoneos
                        SUPPORTS_MACCATALYST = NO
                        SUPPORTS_TEXT_BASED_API = NO
                        SWIFT_COMPILATION_MODE = wholemodule
                        SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
                        SWIFT_OPTIMIZATION_LEVEL = -O
                        SWIFT_PLATFORM_TARGET_PREFIX = ios
                        SWIFT_VERSION = 5.0
                        SYMROOT = /Users/iam/Projects/oss/table_error_sample/build/ios
                        SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
                        SYSTEM_APPS_DIR = /Applications
                        SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
                        SYSTEM_DEMOS_DIR = /Applications/Extras
                        SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
                        SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
                        SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
                        SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
                        SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
                        SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
                        SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
                        SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
                        SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
                        SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
                        SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
                        SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
                        SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
                        SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
                        SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
                        SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
                        SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
                        SYSTEM_LIBRARY_DIR = /System/Library
                        TAPI_VERIFY_MODE = ErrorsOnly
                        TARGETED_DEVICE_FAMILY = 1,2
                        TARGETNAME = Runner
                        TARGET_BUILD_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Release-iphoneos
                        TARGET_NAME = Runner
                        TARGET_TEMP_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build
                        TEMP_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build
                        TEMP_FILES_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build
                        TEMP_FILE_DIR = /Users/iam/Projects/oss/table_error_sample/build/ios/Runner.build/Release-iphoneos/Runner.build
                        TEMP_ROOT = /Users/iam/Projects/oss/table_error_sample/build/ios
                        TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                        TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
                        UID = 501
                        UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
                        UNSTRIPPED_PRODUCT = NO
                        USER = iam
                        USER_APPS_DIR = /Users/iam/Applications
                        USER_LIBRARY_DIR = /Users/iam/Library
                        USE_DYNAMIC_NO_PIC = YES
                        USE_HEADERMAP = YES
                        USE_HEADER_SYMLINKS = NO
                        USE_LLVM_TARGET_TRIPLES = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
                        VALIDATE_PRODUCT = YES
                        VALIDATE_WORKSPACE = NO
                        VALID_ARCHS = arm64 arm64e armv7 armv7s
                        VERBOSE_PBXCP = NO
                        VERSIONING_SYSTEM = apple-generic
                        VERSIONPLIST_PATH = Runner.app/version.plist
                        VERSION_INFO_BUILDER = iam
                        VERSION_INFO_FILE = Runner_vers.c
                        VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
                        WRAPPER_EXTENSION = app
                        WRAPPER_NAME = Runner.app
                        WRAPPER_SUFFIX = .app
                        WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
                        XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
                        XCODE_PRODUCT_BUILD_VERSION = 11C504
                        XCODE_VERSION_ACTUAL = 1131
                        XCODE_VERSION_MAJOR = 1100
                        XCODE_VERSION_MINOR = 1130
                        XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
                        YACC = yacc
                        arch = arm64
                        variant = normal
[ +115 ms] Launching lib/main.dart on WAS LX1 in debug mode...
[  +20 ms] executing: /Users/iam/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/iam/Projects/oss/table_error_sample/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +25 ms] Exit code 0 from: /Users/iam/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/iam/Projects/oss/table_error_sample/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.tableerrorsample" (Raw: "com.example.tableerrorsample")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="tableerrorsample" (Raw: "tableerrorsample")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.tableerrorsample.MainActivity" (Raw: "com.example.tableerrorsample.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +13 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell -x logcat -v time -t 1
[ +194 ms] Exit code 0 from: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           05-02 16:56:18.032 D/HwWifiStatStore( 1159): handleMessage : 200
[  +11 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb version
[   +1 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 logcat -v time -T 05-02 16:56:18.032
[  +27 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as /Users/iam/Library/Android/sdk/platform-tools/adb
[   +4 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb start-server
[  +13 ms] Building APK
[  +43 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from /Users/iam/Projects/oss/table_error_sample/android/gradlew.
[  +20 ms] executing: /usr/bin/plutil -convert json -o - /Users/iam/Applications/JetBrains Toolbox/Android Studio.app/Contents/Info.plist
[  +29 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/iam/Applications/JetBrains Toolbox/Android Studio.app/Contents/Info.plist
[        ]
{"NSUIElement":false,"LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleInfoDictionaryVersion":"6.0","CFBundleIdentifier":"com.jetbrains.toolbox.linkapp.pcom.jetbrains.toolbox__ndr
oid_tudio_3_6_3","CFBundleVersion":"3.6.3","CFBundleLongVersionString":"3.6.3","CFBundleExecutable":"jetbrains-toolbox-launcher","CFBundleName":"Android Studio
3.6.3","CFBundleGetInfoString":"","NSHighResolutionCapable":true,"CFBundleSignature":"????","LSUIElement":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"icon.icns","JetBrainsToolboxApp":"\/Users\/i
am\/Library\/Application Support\/JetBrains\/Toolbox\/apps\/AndroidStudio\/ch-0\/192.6392135\/Android Studio.app","CFBundleDevelopmentRegion":"English","NSHumanReadableCopyright":"Copyright (c) JetBrains
s.r.o.","CFBundleShortVersionString":"3.6.3"}
[  +16 ms] executing: /usr/bin/plutil -convert json -o - /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/Info.plist
[  +19 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_P
ACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.i
ntellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.6","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsag
eDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.36.6392135","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests
access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFB
undleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.stu
dio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio
requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads
folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network volume.","CFBundleGetInfoString":"Android Studio 3.6, build AI-192.7142.36.36.6392135.
Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a removable volume."}
[  +11 ms] executing: /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +161 ms] Exit code 0 from: /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +3 ms] executing: [/Users/iam/Projects/oss/table_error_sample/android/] /Users/iam/Projects/oss/table_error_sample/android/gradlew -Pverbose=true
-Ptarget=/Users/iam/Projects/oss/table_error_sample/lib/main.dart -Ptrack-widget-creation=false -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+3275 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +275 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +101 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +98 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +96 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 3s
[        ] 30 actionable tasks: 3 executed, 27 up-to-date
[ +410 ms] Running Gradle task 'assembleDebug'... (completed in 4.5s)
[ +200 ms] calculateSha: LocalDirectory: '/Users/iam/Projects/oss/table_error_sample/build/app/outputs/apk'/app.apk
[ +169 ms] calculateSha: reading file took 168us
[+1623 ms] calculateSha: computing sha took 1622us
[  +12 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[  +18 ms] executing: /Users/iam/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/iam/Projects/oss/table_error_sample/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +37 ms] Exit code 0 from: /Users/iam/Library/Android/sdk/build-tools/29.0.2/aapt dump xmltree /Users/iam/Projects/oss/table_error_sample/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.tableerrorsample" (Raw: "com.example.tableerrorsample")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="tableerrorsample" (Raw: "tableerrorsample")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.tableerrorsample.MainActivity" (Raw: "com.example.tableerrorsample.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +12 ms] Stopping app 'app.apk' on WAS LX1.
[   +6 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell am force-stop com.example.tableerrorsample
[ +204 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell pm list packages com.example.tableerrorsample
[ +844 ms] package:com.example.tableerrorsample
[   +4 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell cat /data/local/tmp/sky.com.example.tableerrorsample.sha1
[  +41 ms] 18ee93e0c1662fbb7a652420989419b204156e01
[   +1 ms] Latest build already installed.
[        ] WAS LX1 startApp
[   +4 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.tableerrorsample/com.example.tableerrorsample.MainActivity
[  +96 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.tableerrorsample/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +316 ms] D/FlutterActivity(12992): Using the launch theme as normal theme.
[   +3 ms] D/FlutterActivityAndFragmentDelegate(12992): Setting up FlutterEngine.
[        ] D/FlutterActivityAndFragmentDelegate(12992): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
[ +159 ms] D/FlutterActivityAndFragmentDelegate(12992): Attaching FlutterEngine to the Activity that owns this Fragment.
[  +87 ms] D/FlutterView(12992): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e046996
[  +27 ms] D/FlutterActivityAndFragmentDelegate(12992): Executing Dart entrypoint: main, and sending initial route: /
[ +335 ms] Observatory URL on device: http://127.0.0.1:39643/NUt_NZuXFTc=/
[   +2 ms] executing: /Users/iam/Library/Android/sdk/platform-tools/adb -s 192.168.0.167:5555 forward tcp:0 tcp:39643
[   +9 ms] 56275
[        ] Forwarded host port 56275 to device port 39643 for Observatory
[  +12 ms] Connecting to service protocol: http://127.0.0.1:56275/NUt_NZuXFTc=/
[ +476 ms] I/flutter (12992): false
[  +45 ms] Successfully connected to service protocol: http://127.0.0.1:56275/NUt_NZuXFTc=/
[   +5 ms] Sending to VM service: getVM({})
[  +21 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Unknown, operatingSystem: android, targetCPU: arm64, version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "android_arm64",
_profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 12992, startTime: 15884...
[   +9 ms] Sending to VM service: getIsolate({isolateId: isolates/1405335548734343})
[   +7 ms] Sending to VM service: _flutter.listViews({})
[  +17 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name:
main.dart$main-1405335548734343, number: 1405335548734343}}]}
[   +9 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: table_error_sample})
[  +34 ms] Result: {type: Isolate, id: isolates/1405335548734343, name: main, number: 1405335548734343, _originNumber: 1405335548734343, startTime: 1588413386733, _heaps: {new: {type: HeapSpace, name:
new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +55 ms] Result: {type: FileSystem, name: table_error_sample, uri: file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/)
[   +2 ms] Updating assets
[ +146 ms] Syncing files to device WAS LX1...
[   +2 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +8 ms] /Users/iam/development/flutter/bin/cache/dart-sdk/bin/dart /Users/iam/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/iam/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/lt/g7n3c3h90s99_847ddbqn3f40000gn/T/flutter_tool.Z3Km2I/app.dill --packages /Users/iam/Projects/oss/table_error_sample/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --filesystem-scheme org-dartlang-root
[   +7 ms] <- compile package:tableerrorsample/main.dart
[+5670 ms] Updating files
[ +352 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device WAS LX1... (completed in 6,047ms, longer than expected)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[  +22 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name:
main.dart$main-1405335548734343, number: 1405335548734343}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0x762be53b20.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on WAS LX1 is available at: http://127.0.0.1:56275/NUt_NZuXFTc=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6749 ms] Initializing hot reload...
[   +5 ms] Refreshing active FlutterViews before reloading.
[        ] Sending to VM service: _flutter.listViews({})
[  +20 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name:
main.dart$main-1405335548734343, number: 1405335548734343}}]}
[   +7 ms] Scanned through 292 files in 6ms
[        ] Syncing files to device WAS LX1...
[        ] Scanning asset files
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +6 ms] <- recompile package:tableerrorsample/main.dart 0f9d5f26-6b06-4ac4-8a35-19d8f325a493
[        ] <- 0f9d5f26-6b06-4ac4-8a35-19d8f325a493
[   +7 ms] Updating files
[  +26 ms] DevFS: Sync finished
[        ] Syncing files to device WAS LX1... (completed in 42ms)
[        ] Synced 0.0MB.
[   +2 ms] Sending to VM service: _flutter.setAssetBundlePath({isolateId: isolates/1405335548734343, viewId: _flutterView/0x762be53b20, assetDirectory:
/data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/build/flutter_assets})
[  +18 ms] Result: {type: Success, view: {type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name: main.dart$main-1405335548734343,
number: 1405335548734343}}}
[   +3 ms] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/lib/main.dart.incremental.dill, packagesUri:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/.packages, isolateId: isolates/1405335548734343})
[  +30 ms] Result: {type: ReloadReport, success: true, details: {finalLibraryCount: 333, receivedLibraryCount: 0, receivedLibrariesBytes: 128, receivedClassesCount: 0, receivedProceduresCount: 0,
savedLibraryCount: 333, loadedLibraryCount: 0}}
[   +2 ms] <- accept
[        ] reloaded 0 of 333 libraries
[        ] Sending reload events to WAS LX1
[        ] Sending reload event to "main.dart$main-1405335548734343"
[        ] Sending to VM service: getIsolate({isolateId: isolates/1405335548734343})
[  +49 ms] Result: {type: Isolate, id: isolates/1405335548734343, name: main, number: 1405335548734343, _originNumber: 1405335548734343, startTime: 1588413386734, _heaps: {new: {type: HeapSpace, name:
new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[   +4 ms] Sending to VM service: _flutter.listViews({})
[  +21 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name:
main.dart$main-1405335548734343, number: 1405335548734343}}]}
[        ] Evicting dirty assets
[        ] Reassembling application
[   +1 ms] Sending to VM service: ext.flutter.reassemble({isolateId: isolates/1405335548734343})
[  +83 ms] I/flutter (12992): false
[  +22 ms] Result: {type: _extensionType, method: ext.flutter.reassemble}
[   +2 ms] Initializing hot reload... (completed in 323ms)
[        ] Reloaded 0 of 333 libraries in 324ms.
[+9803 ms] Performing hot restart...
[   +2 ms] Refreshing active FlutterViews before restarting.
[        ] Sending to VM service: _flutter.listViews({})
[  +33 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/1405335548734343, name:
main.dart$main-1405335548734343, number: 1405335548734343}}]}
[  +11 ms] Scanned through 292 files in 9ms
[        ] Syncing files to device WAS LX1...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:tableerrorsample/main.dart 17fa7da4-4469-427c-8400-8b6c2b916c95
[        ] <- 17fa7da4-4469-427c-8400-8b6c2b916c95
[  +40 ms] Updating files
[ +639 ms] DevFS: Sync finished
[        ] Syncing files to device WAS LX1... (completed in 683ms)
[        ] Synced 10.1MB.
[        ] <- accept
[        ] Sending to VM service: getIsolate({isolateId: isolates/1405335548734343})
[  +47 ms] Result: {type: Isolate, id: isolates/1405335548734343, name: main, number: 1405335548734343, _originNumber: 1405335548734343, startTime: 1588413386733, _heaps: {new: {type: HeapSpace, name:
new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[ +108 ms] Sending to VM service: _flutter.runInView({viewId: _flutterView/0x762be53b20, mainScript:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/lib/main.dart.dill, packagesFile:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/.packages, assetDirectory:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/build/flutter_assets})
[ +344 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateStart, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091}, timestamp:
1588413412021}}
[   +1 ms] Sending to VM service: getIsolate({isolateId: isolates/2558680418940091})
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412039, extensionRPC: ext.ui.window.scheduleFrame}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateExit, isolate: {type: @Isolate, id: isolates/1405335548734343, name: main, number: 1405335548734343}, timestamp:
1588413412140}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateRunnable, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091}, timestamp:
1588413412288}}
[   +7 ms] Result: {type: Success, view: {type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/2558680418940091, name: main.dart$main-2558680418940091,
number: 2558680418940091}}}
[   +1 ms] Isolate is runnable.
[        ] Sending to VM service: _flutter.listViews({})
[  +78 ms] Result: {type: Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091, _originNumber: 2558680418940091, startTime: 1588413412002, _heaps: {new: {type: HeapSpace, name:
new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +11 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/2558680418940091, name:
main.dart$main-2558680418940091, number: 2558680418940091}}]}
[   +1 ms] Hot restart performed in 1,299ms.
[   +1 ms] Performing hot restart... (completed in 1,337ms)
[        ] Restarted application in 1,339ms.
[ +152 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412545, extensionRPC: ext.flutter.reassemble}}
[   +3 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412545, extensionRPC: ext.flutter.exit}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412545, extensionRPC: ext.flutter.saveCompilationTrace}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412546, extensionRPC: ext.flutter.platformOverride}}
[   +4 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412548, extensionRPC: ext.flutter.evict}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412549, extensionRPC: ext.flutter.timeDilation}}
[   +4 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugPaint}}
[   +2 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugPaintBaselinesEnabled}}
[  +41 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.repaintRainbow}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugCheckElevationsEnabled}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugDumpLayerTree}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugDumpRenderTree}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugDumpSemanticsTreeInTraversalOrder}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412551, extensionRPC: ext.flutter.debugDumpApp}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412552, extensionRPC: ext.flutter.showPerformanceOverlay}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412552, extensionRPC: ext.flutter.didSendFirstFrameEvent}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412552, extensionRPC: ext.flutter.didSendFirstFrameRasterizedEvent}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412552, extensionRPC: ext.flutter.profileWidgetBuilds}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412557, extensionRPC: ext.flutter.debugAllowBanner}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412557, extensionRPC: ext.flutter.debugWidgetInspector}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412572, extensionRPC: ext.flutter.inspector.structuredErrors}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412572, extensionRPC: ext.flutter.inspector.show}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412574, extensionRPC: ext.flutter.inspector.disposeAllGroups}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412575, extensionRPC: ext.flutter.inspector.disposeGroup}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412575, extensionRPC: ext.flutter.inspector.isWidgetTreeReady}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412576, extensionRPC: ext.flutter.inspector.disposeId}}
[   +4 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412577, extensionRPC: ext.flutter.inspector.setPubRootDirectories}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412577, extensionRPC: ext.flutter.inspector.setSelectionById}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getParentChain}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getProperties}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getChildren}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getChildrenSummaryTree}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getChildrenDetailsSubtree}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412578, extensionRPC: ext.flutter.inspector.getRootWidget}}
[   +2 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412579, extensionRPC: ext.flutter.inspector.getRootRenderObject}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412579, extensionRPC: ext.flutter.inspector.getRootWidgetSummaryTree}}
[   +4 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412579, extensionRPC: ext.flutter.inspector.getDetailsSubtree}}
[   +1 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412579, extensionRPC: ext.flutter.inspector.getSelectedRenderObject}}
[   +3 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412579, extensionRPC: ext.flutter.inspector.getSelectedWidget}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412580, extensionRPC: ext.flutter.inspector.getSelectedSummaryWidget}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412580, extensionRPC: ext.flutter.inspector.isWidgetCreationTracked}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091},
timestamp: 1588413412580, extensionRPC: ext.flutter.inspector.screenshot}}
[   +1 ms] I/flutter (12992): true
[+2612 ms] Performing hot reload...
[        ] Refreshing active FlutterViews before reloading.
[        ] Sending to VM service: _flutter.listViews({})
[  +34 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/2558680418940091, name:
main.dart$main-2558680418940091, number: 2558680418940091}}]}
[  +14 ms] Scanned through 292 files in 12ms
[        ] Syncing files to device WAS LX1...
[        ] Scanning asset files
[   +2 ms] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:tableerrorsample/main.dart 5481a3c1-a3e6-4bdb-b987-2c2c3eab63f7
[        ] <- 5481a3c1-a3e6-4bdb-b987-2c2c3eab63f7
[  +16 ms] Updating files
[  +53 ms] DevFS: Sync finished
[        ] Syncing files to device WAS LX1... (completed in 74ms)
[        ] Synced 0.0MB.
[        ] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/lib/main.dart.incremental.dill, packagesUri:
file:///data/user/0/com.example.tableerrorsample/code_cache/table_error_samplePQFEKG/table_error_sample/.packages, isolateId: isolates/2558680418940091})
[  +24 ms] Result: {type: ReloadReport, success: true, details: {finalLibraryCount: 333, receivedLibraryCount: 0, receivedLibrariesBytes: 128, receivedClassesCount: 0, receivedProceduresCount: 0,
savedLibraryCount: 333, loadedLibraryCount: 0}}
[        ] <- accept
[        ] reloaded 0 of 333 libraries
[        ] Sending reload events to WAS LX1
[        ] Sending reload event to "main.dart$main-2558680418940091"
[        ] Sending to VM service: getIsolate({isolateId: isolates/2558680418940091})
[  +54 ms] Result: {type: Isolate, id: isolates/2558680418940091, name: main, number: 2558680418940091, _originNumber: 2558680418940091, startTime: 1588413412003, _heaps: {new: {type: HeapSpace, name:
new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[   +6 ms] Sending to VM service: _flutter.listViews({})
[  +27 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x762be53b20, isolate: {type: @Isolate, fixedId: true, id: isolates/2558680418940091, name:
main.dart$main-2558680418940091, number: 2558680418940091}}]}
[        ] Evicting dirty assets
[        ] Reassembling application
[        ] Sending to VM service: ext.flutter.reassemble({isolateId: isolates/2558680418940091})
[  +95 ms] I/flutter (12992): true
[  +25 ms] Result: {type: _extensionType, method: ext.flutter.reassemble}
[        ] Hot reload performed in 364ms.
[        ] Performing hot reload... (completed in 365ms)
[        ] Reloaded 0 of 333 libraries in 365ms.

```

```
Analyzing table_error_sample...                                         
No issues found! (ran in 2.3s)
```

```
Analyzing table_error_sample...                                         
No issues found! (ran in 2.3s)
iam@MacBook-Pro-1 table_error_sample % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-RU)
    • Flutter version 1.12.13+hotfix.9 at /Users/iam/development/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.0

[✓] Connected device (1 available)
    • WAS LX1 • 192.168.0.167:5555 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Ensure --no-track-widget-creation is piped through android/macOS. Adds integration testing for iOS/android/macOS

Fixes https://github.com/flutter/flutter/issues/56188

### CODE REVIEW

File: dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+
+import 'package:vm_service/vm_service.dart';
+import 'package:vm_service/vm_service_io.dart';
+import 'package:flutter_devicelab/framework/adb.dart';
+import 'package:path/path.dart' as path;
+import 'package:flutter_devicelab/framework/framework.dart';
+import 'package:flutter_devicelab/framework/utils.dart';
+
+final Directory integrationTestDir = Directory(
+  path.join(flutterDirectory.path, 'dev/integration_tests/ui'));
```
Comment (dnfield) [inline dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart:16]: nit: one line or add a comma

File: dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+      );
+      runProcess.stdout
+        .transform(utf8.decoder)
+        .transform(const LineSplitter())
+        .listen(print);
+      final File file = await waitForFile(path.join(integrationTestDir.path, 'info'));
+      final VmService vmService = await vmServiceConnectUri(file.readAsStringSync());
+      final VM vm = await vmService.getVM();
+      final Response result = await vmService
+        .callMethod('ext.devicelab.test', isolateId: vm.isolates.single.id);
```
Comment (dnfield) [inline dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart:61]: I believe style guide wants this to be one line

File: dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
```
Comment (dnfield) [inline dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart:97]: ditto

File: dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+Future<File> waitForFile(String path) async {
+  for (int i = 0; i < 20; i += 1) {
+    final File file = File(path);
+    print('looking for ${file.path}');
+    if (file.existsSync()) {
+      return file;
+    }
+    await Future<void>.delayed(const Duration(seconds: 20));
+  }
+  throw StateError('Did not find vmservice out file after 400s seconds');
```
Comment (dnfield) [inline dev/devicelab/lib/tasks/track_widget_creation_enabled_task.dart:124]: typo: 400s

File: dev/devicelab/manifest.yaml [hunk 5]
```diff
@@ -797,6 +818,15 @@ tasks:
     stage: devicelab
     required_agent_capabilities: ["linux-vm"]
 
+  # This should stay off until https://github.com/flutter/flutter/issues/56212
```
Comment (dnfield) [inline dev/devicelab/manifest.yaml:821]: TODO for discoverability?

**Review by dnfield — APPROVED** [review]
LGTM modulo some style nits
