### PR TITLE
Further improve error reporting by wrapping messages.

### LINKED ISSUE #2323: When we display exceptions, if it's an AssertionError, we should ask for feedback
If we display an exception that's an AssertionError, we should explicitly say that if the assertion isn't clear, it's totally fine to file a bug asking for more information in the assert. Ideally we would have clear detailed messages for any assertion that a developer could run into.

### PR DESCRIPTION
**Pull request by Hixie**
Also fixes https://github.com/flutter/flutter/issues/2323 (tell people to file bugs for assertions).
Also fixes some minor issues with our current exception reporting, such as missing line breaks, incorrect indenting, and incorrect punctuation on the first line of FlutterError messages, and a major issue I introduced with my last patch: the exception handling code was itself causing an exception when "silent" was null, which it accidentally was more than once, since I forgot to give it a default in the subclasses.

### CODE REVIEW

**Comment by Hixie** [comment]
@abarth

File: packages/flutter/lib/src/services/assertions.dart [hunk 1]
```diff
@@ -124,6 +124,8 @@ class FlutterError extends AssertionError {
 
   static int _errorCount = 0;
 
+  static const int _kWrapWidth = 120;
```
Comment (abarth) [inline packages/flutter/lib/src/services/assertions.dart]: not 80 ?

File: packages/flutter/lib/src/services/print.dart [hunk 2]
```diff
@@ -44,7 +51,80 @@ void _debugPrintTask() {
...
+    yield message;
+    return;
+  }
+  Match prefixMatch = _indentPattern.matchAsPrefix(message);
+  String prefix = ' ' * prefixMatch.group(0).length;
+  int start = 0;
+  int startForLengthCalculations = 0;
+  bool addPrefix = false;
+  int index = prefix.length;
+  int mode = 0;
```
Comment (abarth) [inline packages/flutter/lib/src/services/print.dart]: Should we use an enum here?

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/services/assertions.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/services/assertions.dart]: I tried 80, but it turns out that looks really freaking narrow and a lot of our messages are substantially wider than that. 120 is what I needed to make the header be roughly as wide as the stack trace on my display. (I don't wrap the stack trace because that would make it unreadable.)

File: packages/flutter/lib/src/services/print.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/services/print.dart]: Sure.
