### PR TITLE
Verbose cocoapods output if error or flutter is verbose

### LINKED ISSUE #11001: "flutter run" should print output of "pod install" if it fails
Inspired by questions on Stack Overflow about Flutter and CocoaPods. This would be an ok mitigation for #9993 if we don't want to trigger a repo update automatically.

## Steps to Reproduce

  * `flutter run` on an iOS device
  * Have some CocoaPods problem (e.g. out of date repo, missing dependency)

Output is not that helpful:

```
Running pod install...                                    
Error running pod install: Exit code 1 from: pod install
Error launching application on iPhone 7 Plus.
```

What I'd like to see:
```
               [!] Unable to satisfy the following requirements:
               
               - `Firebase (~> 4.0)` required by `Podfile`
               
               None of your spec sources contain a spec satisfying the dependency: `Firebase (~> 4.0)`.
               
               You have either:
                * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
                * mistyped the name or version.
                * not added the source repo that hosts the Podspec to your Podfile.
               
               Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

We should buffer up stdout and print it if the command fails.

### PR DESCRIPTION
**Pull request by xster**
Fixes #11001

Helps diagnose #10873

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -437,14 +437,23 @@ Future<Null> _runPodInstall(Directory bundle, String engineDirectory) async {
...
+        printStatus('CocoaPods\' output:\n↳');
+        printStatus(result.stdout, indent: 4);
+      }
+      if (result.stderr.isNotEmpty) {
+        printStatus('Error output from CocoaPods:\n↳');
+        printStatus(result.stderr, indent: 4);
+      }
     }
+    if (result.exitCode != 0)
+      throwToolExit('Error running pod install:\n${result.stdout}');
```
Comment (collinjackson) [inline packages/flutter_tools/lib/src/ios/mac.dart]: I feel like this is a place where you want `result.stderr` more than `result.stdout`, since CocoaPods errored out

Comment (xster) [inline packages/flutter_tools/lib/src/ios/mac.dart]: oops, I meant to delete this since it was already printed above.

**Comment by xster** [comment]
Tested with your provided error case. Does print a reasonable output. (the error is still in pod's stdout)

**Review by collinjackson — APPROVED** [review]
