### PR TITLE
fix asset reloading

### LINKED ISSUE #29184: Determine whether it is possible to update asset manifest during hot reload
Currently we require adding and removing assets to be done in a hot restart, while only existing assets can be updated in a hot reload. It's not clear if this is a limitation in how assets are handled or a bug/oversight in hot reload.

### LINKED ISSUE #29186: Changing pubspec.yaml and triggering a hot reload crashes application
It's not clear if this was ever intended to be supported. Currently we either hang on a hot reload or crash. This can be reproduced on master by running the flutter gallery, then adding a new dependency to pubspec.yaml and triggering a hot reload.

Dependencies can be removed from the pubspec, or added with a hot restart.

Its not clear how this could be supported with a build_runner workflow.

```
Performing hot reload...                                                
Reloaded 0 of 578 libraries in 662ms.

Performing hot reload...                                               ⣻ (This is taking an unexpectedly long time.)[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
       ⣾ (This is taking an unexpectedly long time.)Application finished.
jonahwilliams-macbookpro2:flutter_gallery jonahwilliams$ flutter clean
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Edit: Fix might imply broken recently, but from what I can tell it has always worked this way 🤷‍♂️ 

## Description

Currently flutter invalidates _all_ assets whenever the pubspec.yaml file is changed in any way or whenever a hot restart is performed. This isn't necessary, and adds a lot of overhead to hot reloads and hot restarts. For projects with a large number of assets, adding/removing pubspec dependencies has a chance to crash the application during a hot reload. This may have led to the logic of  "always hot restart" for adding assets

The underlying cause is the interfaction between the AssetManifest and `DevFSContent.isModified`. On every change to the pubspec.yaml, we completely recreate the asset bundle, including new instances of `DevFsContent` for each asset. However, the logic of `isModified` states that it is always true when first called regardless of the underling resource. Thus, every time the bundle is updated, we attempt to sync every single asset. To fix this, we can update asset construction to only create new devfs content when necessary

This significantly reduces the hot restart time, which was cut by about a third running on a simulator. On real devices this is less dramatic. This also allows adding new files to the asset manifest and hot reloading them into the application

EDIT: moving pubspec update logic to follow up PR.

## Related Issues

~~Fixes https://github.com/flutter/flutter/issues/29186~~
Fixes https://github.com/flutter/flutter/issues/29184

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter_tools/lib/src/devfs.dart [hunk 1]
```diff
@@ -444,36 +444,33 @@ class DevFS {
...
       bundle.entries.forEach((String archivePath, DevFSContent content) {
         final Uri deviceUri = fs.path.toUri(fs.path.join(assetDirectory, archivePath));
-        _entries[deviceUri] = content;
+        if (deviceUri.path.startsWith(assetBuildDirPrefix)) {
+          archivePath = deviceUri.path.substring(assetBuildDirPrefix.length);
+        }
+        // When doing full restart, copy content so that isModified does not
+        // reset last check timestamp because we want to report all modified
+        // files to incremental compiler next time user does hot reload.
+        if ((_lastUpdate != null && content.isModifiedAfter(_lastUpdate)) || (bundleFirstUpload && archivePath != null)) {
```
Comment (aam) [inline packages/flutter_tools/lib/src/devfs.dart]: this check used to involve `bundleDirty`(which is now unused) and the fact that DevFSContent managed it's `isModified` state. Now it seems we just rely on keeping `_lastUpdate` here and comparing modification date against it. Why this change?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/devfs.dart]: Since _entries previously contained both assets and source files, it was necessary to separate the check to update asset paths. Now that we only ever upload assets + dill, these checks can be combined. In this case, I don't think there is any need for bundleDirty, since we can use the bundle itself as the source of truth.

Actually, having fixed the bundle bug I can probably return this to using isModified instead.

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 2]
```diff
@@ -978,35 +981,45 @@ class ProjectFileInvalidator {
...
       // Hot reloading with an updated package will often times kill a non-trivial
       // appliction. This _might_ work, given certain application size and package
-      // constraints, so instead of exiting we print a warning so that the user has
-      // some hint on what went wrong.
+      // constraints.
       if (newPackagesUpdateTime > _packagesUpdateTime) {
-        printError('Warning: updated dependencies detected. The Flutter application will require a restart to safely use new packages.');
+        final Map<String, Uri> newPackageMap = PackageMap(_packagesPath).map;
+        final Set<String> newPackages = Set<String>.from(newPackageMap.keys);
+        final Set<String> difference = newPackages.difference(_loadedPackages);
```
Comment (aam) [inline packages/flutter_tools/lib/src/run_hot.dart]: Does `_loadedPackages` have to be instance variable or it just a local `Set<String>.from(_packageMap.keys)`?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/run_hot.dart]: I store it as an instance variable before I remove the dev dependencies and pub cache from the packageMap

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: but does _packageMap content changes outside of this function? It looks as if _loadedPackages is just content of the _packageMap before it is updated at line 1010 below in this function.

**Comment by jonahwilliams** [comment]
@aam I'll rebase this change on top of your compiler update when it lands

**Review by aam — APPROVED** [review]
