### PR TITLE
`RenderParagraph` should invalidate its `_SelectableFragment`s cached rects on window size updates

### LINKED ISSUE #120578: [SelectionArea] Once text is pushed to a new line after resizing the window, we can no longer select the text on the second line
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2.  Resize application 
3. Drag or Double click to SelectionText 

**Expected results:**  After resize app SelectionArea can double, drag text .

**Actual results:**  Can't selection text if drag text with newLine wrap.

<details>
<summary>Code sample</summary>

```dart

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const SelectionArea(
        child: Center(
          child: Text(
            'Hi, I am is Beta. Good bye. Hi, I am is Beta. Good bye. Hi, I am is Beta. Good bye. Hi, I am is Beta. Good bye.'
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.10-0.0.pre.5, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.10-0.0.pre.5 on channel stable at /Users/tungle/workspaces/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3778e3c76c (9 weeks ago), 2022-12-14 23:44:46 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tungle/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

https://user-images.githubusercontent.com/46608407/218371777-71526504-c861-4b6c-8657-848c776cfdae.mov

### LINKED ISSUE #155143: paragraph.dart  _cachedRect is not refreshed after the window width changes, which results in limited selection
### Steps to reproduce

After the first rendering, the selected file can be selected. After reducing the window size, some selected areas are limited and cannot be selected

### Expected results

It is expected that after the window width is adjusted, the selection can also be normal, and the area is not limited.

### Actual results

After the first rendering, the selected file can be selected. After reducing the window size, some selected areas are limited and cannot be selected

### Code sample

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Selectable Text with Dynamic Layout'),
        ),
        body: const DynamicLayoutWidget(),
      ),
    );
  }
}

class DynamicLayoutWidget extends StatefulWidget {
  const DynamicLayoutWidget({Key? key}) : super(key: key);

  @override
  _DynamicLayoutWidgetState createState() => _DynamicLayoutWidgetState();
}

class _DynamicLayoutWidgetState extends State<DynamicLayoutWidget> {
  @override
  Widget build(BuildContext context) {
    return const Material(
      color: Colors.transparent,
      child: SelectionArea(
          child: Text(
        'This is a selectable text.Selectable Text with WrapSelectable Text with WrapSelectable Text with WrapSelectable Text with WrapSelectable Text with Wrap',
        style: TextStyle(fontSize: 18),
        selectionColor: Colors.blue,
      )),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/eda9de0a-79e9-47b7-a79f-4a96e20e6e73

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [版本 10.0.22631.4169], locale zh-CN)
    • Flutter version 3.24.1 on channel stable at D:\flutter_windows_3.24.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35004.147
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #155143
Fixes #120578

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -809,6 +809,7 @@ class RenderParagraph extends RenderBox with ContainerRenderObjectMixin<RenderBo
 
   @override
   void performLayout() {
+    _lastSelectableFragments?.forEach((_SelectableFragment element) => element.didChangeParagraphLayout());
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/paragraph.dart:812]: Should this happen at the end of performLayout?

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 2]
```diff
@@ -1261,6 +1261,60 @@ void main() {
...
+
+      // Select to the end.
+      await gesture.moveTo(textOffsetToPosition(paragraph, testString.length));
+      await tester.pump();
+      expect(paragraph.selections[0], const TextSelection(baseOffset: 2, extentOffset: testString.length));
+
+      await gesture.up();
+      await tester.pumpAndSettle();
+    }, variant: TargetPlatformVariant.all(),
+       skip: kIsWeb); // https://github.com/flutter/flutter/issues/125582.
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1316]: Nit: Closing parenthesis on the next line I think?

**Review by justinmc — APPROVED** [review]
LGTM 👍
