### PR TITLE
[flutter_tools] default tree-shake-icons to enabled and improve performance

### LINKED ISSUE #55370: --shrink --tree-shake-icons causes huge system load, causing CI Runners to fail
My setup:

- My CI Gitlab CI, using a Mac Mini as Runner to run the flutter builds
- I want to build release artifacts with `--tree-shake-icons` and `--shrink`

Starting a build with` --tree-shake-icons --shrink` causes a huge load on my system.
If run it on my local workstation, I get load averages like this (from `uptime`): (load averages: `397.06 239.44 116.03` ! ).

On the build machine, I cannot get load averages easily as that my ssh session freezes when the build is running.

The system gets unresponsive during the build because of that.

On the CI, this causes my builds to fail because the CI server thinks that the Runners crashed (My guess is that there is some ping mechanism that fails because of the huge load that the flutter builds cause).

I think it would be nice if there were a build option like `--low-resource-mode`, that would take longer to finish the build, but cause lower strain on the system during the build (e.g. by spawning fewer threads or using a lower priority), making sure the system stays responsive during the build.

```
./flutterw doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/kami/diagnosia/neocortex-mobile/.flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Enable tree-shake-icons by default in profile/release mode. Fix performance by ensuring that only a single instance of const finder runs, and only on ttf fonts

Fixes https://github.com/flutter/flutter/issues/55370

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
(once tests pass)

**Comment by jonahwilliams** [comment]
Running this locally I'm able to repro a large spike in memory pressure and my computer also locked up for a few seconds while running this (it doesn't for normal builds).

**Comment by dnfield** [comment]
Which command?  Const_finder?

**Comment by jonahwilliams** [comment]
just by running `flutter build apk --tree-shake-icons`

**Comment by Zazo032** [comment]
I also experience this when using this flag. For a few seconds, my machine becomes unresponsive with 100% CPU usage and a spike in used memory. Both for APK and appbundle (didn't test iOS or web).

File: packages/flutter_tools/lib/src/build_system/targets/assets.dart [hunk 1]
```diff
@@ -60,8 +62,11 @@ Future<Depfile> copyAssets(Environment environment, Directory outputDirectory) a
         file.parent.createSync(recursive: true);
         final DevFSContent content = entry.value;
         if (content is DevFSFileContent && content.file is File) {
-          inputs.add(globals.fs.file(content.file.path));
-          if (!await iconTreeShaker.subsetFont(
+          inputs.add(content.file as File);
+          // Only tree shake MaterialIcons-Regular.ttf font.
+          final bool isMaterialIcons = globals.fs.path
+            .basename(content.file.path) == kMaterialIconsFontName;
+          if (!isMaterialIcons || !await iconTreeShaker.subsetFont(
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: @dnfield fyi

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: But... Why?  What about Cupertino icons or font awesome icins?

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: The intention of this routine was to only do work if the font file was used by an IconData instance.  Is that not happening?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: As written this was spinning up a const finder instance for every single asset. Does this actually work with arbitrary icon sets? If so we could use something like the mime package to limit it to font files (ttf only?)

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: The other change this would need is to limit the number of instances to 2 or 3, because each one seems to be quite heavy

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: Ahh ok.  Yes, this should work with any font that you refernece a glyph in using `IconData` .. or at least any TTF.

Limiting this to 2 or 3 instances should be fine. And it wasn't meant to run on non-ttf assets.

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: The expectation is that this code https://github.com/flutter/flutter/blob/3f30b6138d4155d91eb8899cc379b6726d4f2fa1/packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart#L166 would return quickly, after the initial run of the const finder here: https://github.com/flutter/flutter/blob/3f30b6138d4155d91eb8899cc379b6726d4f2fa1/packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart#L161

Why is the const finder running more than once? :\

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: I figured it out, getIconData is fairly expensive, and we might be copying multiple assets at the same time. each one that hits this line before the first instance has finished will spawn a new const finder

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart:69]: Ahh, yes.  Ok.  We should just trigger that to happen before the loop.  I'm still a little confused about how multiple places are reaching this code before the first one finishes -are we missing an await somewhere?

File: packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart [hunk 2]
```diff
@@ -150,15 +156,24 @@ class IconTreeShaker {
...
   }) async {
     if (!enabled) {
       return false;
     }
-
-    _iconData ??= await _getIconData(_environment);
+    if (input.lengthSync() < 12) {
+      return false;
+    }
+    final String mimeType = mime.lookupMimeType(
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: How confident are you that this won't cause new problems?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: I'm not confident about anything

**Comment by jonahwilliams** [comment]
I enabled this for web too, but it doesn't actually work since --cfe-only does not do any const evaluation. Instead we'll need to add a dart2js target to the frontend server and produce kernel that way.

File: packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: Maybe we can just move the mime chekc to a separate pr

File: packages/flutter_tools/lib/src/build_system/targets/assets.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/assets.dart]: Because the out loop is a Future.wait, not a for loop

File: packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: We might as well resolve this now if you have concerns :) 

Are there non-ttf fonts that the icon_tree_shaker works with? Or does the hb subset utility have a list of supported formats?

Comment (dnfield) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: I guess this should be fairly safe.  Mime sniffing can get funny, and we could get broken if the mime package changes the spelling of a type

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: I'll add some more tests around this logic

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:169]: More tests added. If the spelling changes there was an existing test that fails, but I also added cases to verify we don't subset invalid fonts or non-ttf mime types

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
One test failure, with a really nice error message too :D
