### PR TITLE
[Hero] toHero flightShuttleBuilder overrides fromHero flightShuttleBuilder

### LINKED ISSUE #77720: Heroes use the wrong flightShuttleBuilder when both the "from" and "to" widgets specify one
The [flightShuttleBuilder API doc](https://api.flutter.dev/flutter/widgets/Hero/flightShuttleBuilder.html) says:

> When both the source and destination Heroes provide a flightShuttleBuilder, the destination's flightShuttleBuilder takes precedence.

In https://github.com/flutter/flutter/pull/72946 this appears to have been accidentally reversed, see https://github.com/flutter/flutter/pull/72946/files#r590560595

We should add a regression test too.

Internal Google issue link: http://b/177462791

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/77720

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/heroes_test.dart [hunk 1]
```diff
@@ -1612,12 +1612,65 @@ Future<void> main() async {
     expect(tester.getTopLeft(find.byKey(firstKey)).dx, x0);
   });
 
-  testWidgets('Can override flight shuttle', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/widgets/heroes_test.dart:1615]: we should keep the test as is unless it is testing the wrong behavior. we should add new test to cover the from hero instead.

**Review by chunhtai — APPROVED** [review]
LGTM, left a comment on the test
