### PR TITLE
Url encode asset lookup key

### LINKED ISSUE #14870: Errors loading assets with spaces in their names
If I have spaces in my asset filenames, they fail to load at runtime (works fine without the spaces):

screen shot 2018-02-25 at 11 55 10

Asset can be seen in the tree on the left, pubspec in the top pane and the error in the bottom pane.

### PR DESCRIPTION
**Pull request by szakarias**
Fixes https://github.com/flutter/flutter/issues/14870 .

### CODE REVIEW

File: packages/flutter/lib/src/services/asset_bundle.dart [hunk 1]
```diff
@@ -223,7 +223,8 @@ abstract class CachingAssetBundle extends AssetBundle {
 class PlatformAssetBundle extends CachingAssetBundle {
   @override
   Future<ByteData> load(String key) async {
-    final Uint8List encoded = UTF8.encoder.convert(key);
+//    final Uint8List encoded = UTF8.encoder.convert(key);
```
Comment (mravn-google) [inline packages/flutter/lib/src/services/asset_bundle.dart]: Remove?

**Review by mravn-google — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/services/asset_bundle.dart (hunk 1 above)
Comment (szakarias) [reply packages/flutter/lib/src/services/asset_bundle.dart]: Of course!
