### PR TITLE
Fix semantics node id overflow issue

### LINKED ISSUE #77036: Semantics crash - !owner._nodes.containsKey(id)': is not true.
## Steps to Reproduce

I was created the custom widget to arrange children based on row and column count and also i was handled the semantics on custom render object. Semantics makes crash while place the custom widget inside the list view.

```

class _CustomContainer extends Stack {
  _CustomContainer({List<Widget> children, this.width, this.height})
      : super(children: children);
  final double width;
  final double height;

  @override
  RenderStack createRenderObject(BuildContext context) {
    final Directionality widget =
        context.dependOnInheritedWidgetOfExactType<Directionality>();
    return _CustomContainerRenderObject(width, height,
        direction: widget != null ? widget.textDirection : null);
  }

  @override
  void updateRenderObject(BuildContext context, RenderStack renderObject) {
    super.updateRenderObject(context, renderObject);
    if (renderObject is _CustomContainerRenderObject) {
      final Directionality widget =
          context.dependOnInheritedWidgetOfExactType<Directionality>();
      renderObject
        ..width = width
        ..height = height
        ..textDirection = widget != null ? widget.textDirection : null;
    }
  }
}

class _CustomContainerRenderObject extends RenderStack {
  _CustomContainerRenderObject(this._width, this._height,
      {TextDirection direction})
      : super(textDirection: direction);

  double get width => _width;

  set width(double value) {
    if (_width == value) {
      return;
    }

    _width = value;
    markNeedsLayout();
  }

  double _width;
  double _height;

  double get height => _height;

  set height(double value) {
    if (_height == value) {
      return;
    }

    _height = value;
    markNeedsLayout();
  }

  @override
  void performLayout() {
    super.performLayout();
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    paintStack(context, offset);
  }

  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.isSemanticBoundary = true;
  }

  @override
  void assembleSemanticsNode(
    SemanticsNode node,
    SemanticsConfiguration config,
    Iterable<SemanticsNode> children,
  ) {
    final List<CustomPainterSemantics> semantics = _semanticsBuilder(size);
    final List<SemanticsNode> semanticsNodes = <SemanticsNode>[];
    for (int i = 0; i < semantics.length; i++) {
      final CustomPainterSemantics currentSemantics = semantics[i];
      final SemanticsNode newChild = SemanticsNode(key: currentSemantics.key);

      final SemanticsProperties properties = currentSemantics.properties;
      final SemanticsConfiguration config = SemanticsConfiguration();
      if (properties.label != null) {
        config.label = properties.label;
      }
      if (properties.textDirection != null) {
        config.textDirection = properties.textDirection;
      }

      newChild.updateWith(
        config: config,
        childrenInInversePaintOrder: const <SemanticsNode>[],
      );

      newChild
        ..rect = currentSemantics.rect
        ..transform = currentSemantics.transform
        ..tags = currentSemantics.tags;

      semanticsNodes.add(newChild);
    }

    final List<SemanticsNode> finalChildren = <SemanticsNode>[];
    finalChildren.addAll(semanticsNodes);
    finalChildren.addAll(children);
    super.assembleSemanticsNode(node, config, finalChildren);
  }

  SemanticsBuilderCallback get _semanticsBuilder {
    final List<CustomPainterSemantics> semanticsBuilder =
        <CustomPainterSemantics>[];
    double left = 0, top = 0;
    final double cellWidth = size.width / 10;
    final double cellHeight = size.height / 10;
    for (int i = 0; i < 100; i++) {
      semanticsBuilder.add(CustomPainterSemantics(
        rect: Rect.fromLTWH(left, top, cellWidth, cellHeight),
        properties: SemanticsProperties(
          label: i.toString(),
          textDirection: TextDirection.ltr,
        ),
      ));

      left += cellWidth;
      if (left + 1 >= size.width) {
        top += cellHeight;
        left = 0;
      }
    }

    return (Size size) {
      return semanticsBuilder;
    };
  }
}

```

**Sample:**

```

@override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return Scaffold(
        appBar: AppBar(),
        body: SafeArea(
            child: ListView(shrinkWrap: true, children: [
          Container(
              child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                Container(
                  child: ListView.builder(
                    itemCount: 100,
                    itemBuilder: (BuildContext context, int index) {
                      List<Widget> children = <Widget>[];
                      double left = 0, top = 20;
                      final double cellWidth = constraints.maxWidth / 10;
                      final double cellHeight = 20;
                      children.add(Positioned(
                          left: 0,
                          top: 0,
                          right: 0,
                          height: cellHeight,
                          child: Text(
                            'Item Header' + index.toString(),
                            style: TextStyle(fontWeight: FontWeight.w700),
                          )));
                      for (int i = 0; i < 100; i++) {
                        children.add(Positioned(
                            left: left,
                            top: top,
                            width: cellWidth,
                            height: cellHeight,
                            child: Text(i.toString())));
                        left += cellWidth;
                        if (left + 1 >= constraints.maxWidth) {
                          top += cellHeight;
                          left = 0;
                        }
                      }

                      return Container(
                          height: 220,
                          child: _CustomContainer(
                            height: 220,
                            width: constraints.maxWidth,
                            children: children,
                          )
                        );
                    },
                  ),
                  height: 600,
                )
              ]))
        ])),
      );
    });
  }

```

1. Run the above added code on sample.
2. Enable accessibility in your android device.
3. Swipe to scroll continuously items from 1 - 50 and again scroll from 50 - 1 and again scroll to 1 -50.
4. Issue was reproduced due to '_maxFrameworkAccessibilityIdentifier' in semantics class because _generateNewId method generate the id value is 0, 1, 2 ... after _maxFrameworkAccessibilityIdentifier value so the nodes containsKey(id) assert return exception.

**Replication Video:**  

https://user-images.githubusercontent.com/44917578/109600989-20031e80-7b44-11eb-9630-6703d1955f25.mov

**Expected results:** 

Run the sample without exception when accessibility enabled.

**Actual results:** 

Sample makes exception when accessibility enabled.

<details>
  <summary>Crash</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1532 pos 12: '!owner._nodes.containsKey(id)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1532:12)
#3      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
#4      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1460:9)
#5      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1891:5)
#6      RenderObject.assembleSemanticsNode (package:flutter/src/rendering/object.dart:2782:10)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
The semantics id may overflow if the app generate too many semantics node.

This PR makes it so we updates semantics id if the id has repeated when it is attached to the semantics owner.

Fixes https://github.com/flutter/flutter/issues/77036

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @goderbauer , can you take a look at this POC?

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -1527,8 +1551,10 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
   @override
   void attach(SemanticsOwner owner) {
     super.attach(owner);
-    assert(!owner._nodes.containsKey(id));
-    owner._nodes[id] = this;
+    assert(_id == null || _id == 0);
+    if (_id == null)
+      _setId(_generateNewId());
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart:1556]: If we want to handle the overflow issue, we have to keep track of currently used ids. Ideally I can keep track of that in constructor and destructor, but that is not supported in dart. I think the best place we can do it will then be in attach and detach.

Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:1556]: An alternative will be just checking the SemanticsNode._nodes in _generateNewId, it is easier and breaks 0 existing tests, but I found it weird to tie them together.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 2]
```diff
@@ -1231,8 +1243,20 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
   /// The unique identifier for this node.
   ///
   /// The root node has an id of zero. Other nodes are given a unique id when
-  /// they are created.
-  final int id;
+  /// they are attached.
+  ///
+  /// null if this node is detached.
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1248]: nit: docs should be complete sentences.

File: packages/flutter/test/semantics/semantics_test.dart [hunk 3]
```diff
@@ -567,6 +569,15 @@ void main() {
     );
   });
 
+  test('Semantics id does not repeat', () {
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_test.dart:572]: Should this test assert anything?

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 4]
```diff
@@ -1231,8 +1243,20 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
   /// The unique identifier for this node.
   ///
   /// The root node has an id of zero. Other nodes are given a unique id when
-  /// they are created.
-  final int id;
+  /// they are attached.
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1246]: I am trying to thing of any issues that could arise from re-attaching a temporarily unattached node under a different ID. Could this cause issues with a11y focus, which is tied to node id?

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 2 above)
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1248]: Alternative: node id is instantiated when node is created, but on attachment in the overflow case it checks whether the ID is still available and switches then if not. That way, it's never null (but only meaningful when attached).

Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart:1248]: It may also increase the change that a temporarily un-attached node can re-attach under its old ID.

**Review by Josegto1 — APPROVED** [review]

**Comment by chunhtai** [comment]
Hi @goderbauer thanks for reviewing, this is ready for another look!

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 5]
```diff
@@ -1542,9 +1552,9 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
 
   @override
   void detach() {
-    assert(owner!._nodes.containsKey(id));
+    assert(owner!._nodes.containsKey(_id));
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1555]: nit: here and below just use the "id" getter?

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 6]
```diff
@@ -1527,8 +1533,12 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
...
   void attach(SemanticsOwner owner) {
     super.attach(owner);
-    assert(!owner._nodes.containsKey(id));
-    owner._nodes[id] = this;
+    while (owner._nodes.containsKey(id)) {
+      // Ids may repeat if the Flutter has generated > 2^16 ids. We need to keep
+      // regenerating the id until we found an id that is not used.
+      _id = _generateNewId();
+    }
+    owner._nodes[_id] = this;
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1541]: same here.

File: packages/flutter/test/semantics/semantics_test.dart [hunk 7]
```diff
@@ -8,6 +8,8 @@ import 'package:flutter_test/flutter_test.dart';
 
 import '../rendering/rendering_tester.dart';
 
+const int kmaxFrameworkAccessibilityIdentifier = (1<<16) - 1;
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_test.dart:11]:
```suggestion
const int kMaxFrameworkAccessibilityIdentifier = (1<<16) - 1;
```

**Review by goderbauer — APPROVED** [review]
LGTM
