### PR TITLE
Fix computeMinIntrinsicHeight in _RenderDecoration

### LINKED ISSUE #87403: When TextField has prefix or suffix and multiline input, the screen layout may be incorrect
## Steps to Reproduce
<details> 
<summary>code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CustomScrollView(
        slivers: [
          SliverFillRemaining(
            hasScrollBody: false,
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: [
                  const Padding(
                    padding: EdgeInsets.symmetric(vertical: 16.0),
                    child: TextField(
                      maxLines: null,
                      decoration: InputDecoration(
                        labelText: 'Field with prefix',
                        prefix: Text('text'),
                        filled: true,
                      ),
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.symmetric(vertical: 16.0),
                    child: TextField(
                      maxLines: null,
                      decoration: InputDecoration(
                        labelText: 'Field with suffix',
                        suffix: Text('text'),
                        filled: true,
                      ),
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.symmetric(vertical: 16.0),
                    child: TextField(
                      maxLines: null,
                      decoration: InputDecoration(
                        labelText: 'Field with prefixIcon',
                        prefixIcon: Icon(Icons.search),
                        filled: true,
                      ),
                    ),
                  ),
                  _buildButton(),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }

  Widget _buildButton() {
    return Expanded(
      child: Align(
        alignment: Alignment.bottomCenter,
        child: MaterialButton(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4.0),
          ),
          height: 48.0,
          minWidth: double.infinity,
          color: Colors.blue,
          onPressed: () {},
          child: const Text(
            'Button',
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    );
  }
```
</details> 

### Actual results
When text fields has multiline input button has incorrect height

Image1             |  Image2
:-------------------------:|:-------------------------:
  |  

###  Expected results
Button has correct height

Image1             |  Image2
:-------------------------:|:-------------------------:
  |

### PR DESCRIPTION
**Pull request by smitsk**
_RenderDecoration should not ignore prefix, suffix or icons which were passed into InputDecoration when it computes min intrinsic height.

Closes:  [#87403 ](https://github.com/flutter/flutter/issues/87403)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Comment by smitsk** [comment]
@justinmc Hello, most likely you could review this. I'm sorry if this is not the case.
Some checks become unsuccessful after adding the tests. Could you please help me with it?

**Comment by smitsk** [comment]
Is there

**Comment by smitsk** [comment]
Is there any chance that you could look at this? @justinmc @goderbauer 
Sorry if I am wrong about ping you here. Thanks!

**Comment by smitsk** [comment]
Is there any chance that you could look at this? @justinmc @goderbauer
Sorry if I am wrong about mention you here. Thanks!

**Comment by smitsk** [comment]
@justinmc @goderbauer 
Could you take a look at this please? Thanks!

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -1265,17 +1265,57 @@ class _RenderDecoration extends RenderBox {
...
+
+    final double prefixHeight = _lineHeight(width, <RenderBox?>[prefix]);
+    final double prefixWidth = _lineWidth(prefixHeight, <RenderBox?>[prefix]);
+
+    final double suffixHeight = _lineHeight(width, <RenderBox?>[suffix]);
+    final double suffixWidth = _lineWidth(suffixHeight, <RenderBox?>[suffix]);
+
+    final double availableInputWidth = math.max(width - prefixWidth - suffixWidth - prefixIconWidth - suffixIconWidth, 0.0);
+    final double inputHeight = _lineHeight(availableInputWidth, <RenderBox?>[input, hint]);
+    final double inputMaxHeight = <double>[inputHeight, prefixHeight, suffixHeight].reduce(math.max);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/input_decorator.dart:1310]: I'm embarrassed that I never thought of using reduce for calculating math.max of more than 2 items. 👍

File: packages/flutter/test/material/input_decorator_test.dart [hunk 2]
```diff
@@ -5019,6 +5019,146 @@ void main() {
     expect(tester.takeException(), isNull);
   });
 
+  testWidgets('min intrinsic height for TextField with prefix icon', (WidgetTester tester) async {
+    // Regression test for: https://github.com/flutter/flutter/issues/87403
+    await tester.pumpWidget(MaterialApp(
+      home: Material(
+        child: Center(
+          child: SizedBox(
+            width: 100,
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:5028]: Nit: 100.0 here and a few others below.

**Review by justinmc — APPROVED** [review]
Sorry I missed this!  LGTM besides the analyzer failure 👍 

Thanks for fixing this, it looks right to me.  Before, I suspected that the calculation in computeMinIntrinsicHeight and what's done in _layout weren't quite the same.  I wish there was a way to share that logic between the two, but I'm not sure how.  I think this gets the calculation right and looks fine otherwise.

I was able to fix one of the failures by rerunning it.  Could you take a look at the analyzer failure?  It seems strange, if you can't track it down then maybe try merging in master and see if it goes away.

File: packages/flutter/test/material/input_decorator_test.dart (hunk 2 above)
Comment (smitsk) [reply packages/flutter/test/material/input_decorator_test.dart]: Fixed

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -1265,17 +1265,57 @@ class _RenderDecoration extends RenderBox {
...
+    final double counterHeight = _lineHeight(width, <RenderBox?>[counter]);
+    final double counterWidth = _lineWidth(counterHeight, <RenderBox?>[counter]);
+
+    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    final double helperErrorHeight = _lineHeight(helperErrorAvailableWidth, <RenderBox?>[helperError]);
+    double subtextHeight = math.max(counterHeight, helperErrorHeight);
     if (subtextHeight > 0.0)
       subtextHeight += subtextGap;
+
+    final double prefixHeight = _lineHeight(width, <RenderBox?>[prefix]);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:1302]: As I understand it, we want the layout logic here to roughly match what's in `performLayout`. For instance in `performLayout`:
https://github.com/flutter/flutter/blob/56c5f13035d3907a8c7586dee287265f35a236a2/packages/flutter/lib/src/material/input_decorator.dart#L974-L978

The `prefix` widget is laid out using the full width instead of the width of the text container. That could generate some layout difference I think. For example if the `prefix` widget is a `Text` widget that allows softwrap, then this `computeMinIntrinsicHeight` may return a larger height than needed.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 4]
```diff
@@ -1265,17 +1265,57 @@ class _RenderDecoration extends RenderBox {
...
+
+    final double prefixIconHeight = _lineHeight(width, <RenderBox?>[prefixIcon]);
+    final double prefixIconWidth = _lineWidth(prefixIconHeight, <RenderBox?>[prefixIcon]);
+
+    final double suffixIconHeight = _lineHeight(width, <RenderBox?>[suffixIcon]);
+    final double suffixIconWidth = _lineWidth(suffixIconHeight, <RenderBox?>[suffixIcon]);
+
+    width = math.max(width - contentPadding.horizontal, 0.0);
+
+    final double counterHeight = _lineHeight(width, <RenderBox?>[counter]);
```
[the remark this answers is not in the document]
Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart:1293]: You are right! It's wrong.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 3 above)
Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart]: It seems a little bit strange that `prefix` `suffix` `prefixIcon` and `suffixIcon`  widgets are laid out using the full width, they are inside the container while icon is outside. For example if we look at field with prefix length greater than the field length:
```
TextField(
  maxLines: null,
  decoration: InputDecoration(
    labelText: 'Field with prefix',
    prefix: Text('PrefixPrefixPrefixPrefixPrefixPrefixPrefixPrefix'),
    icon: Icon(Icons.search),
    filled: true,
  ),
),
```
So the `prefix` goes outside the container:

Probably we should change `_layout` in the part above to something like this:
```
boxToBaseline[icon] = _layoutLineBox(icon, boxConstraints);
final BoxConstraints containerConstraints = boxConstraints.copyWith(maxWidth: boxConstraints.maxWidth -  _boxSize(icon).width);
boxToBaseline[prefixIcon] = _layoutLineBox(prefixIcon, containerConstraints);
boxToBaseline[suffixIcon] = _layoutLineBox(suffixIcon, containerConstraints);
final BoxConstraints contentConstraints = containerConstraints.copyWith(maxWidth: containerConstraints.maxWidth - contentPadding.horizontal);
boxToBaseline[prefix] = _layoutLineBox(prefix, contentConstraints);
boxToBaseline[suffix] = _layoutLineBox(suffix, contentConstraints);
```
Then it's more correct:

Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart]: It seems a little bit strange that `prefix` `suffix` `prefixIcon` and `suffixIcon`  widgets are laid out using the full width, they are inside the container while icon is outside. For example if we look at field with prefix length greater than the field length:
```
TextField(
  maxLines: null,
  decoration: InputDecoration(
    labelText: 'Field with prefix',
    prefix: Text('PrefixPrefixPrefixPrefixPrefixPrefixPrefixPrefix'),
    icon: Icon(Icons.search),
    filled: true,
  ),
),
```
So the `prefix` goes outside the container (and outside the TextField actually):

Probably we should change `_layout` in the part above to something like this:
```
boxToBaseline[icon] = _layoutLineBox(icon, boxConstraints);
final BoxConstraints containerConstraints = boxConstraints.copyWith(maxWidth: boxConstraints.maxWidth -  _boxSize(icon).width);
boxToBaseline[prefixIcon] = _layoutLineBox(prefixIcon, containerConstraints);
boxToBaseline[suffixIcon] = _layoutLineBox(suffixIcon, containerConstraints);
final BoxConstraints contentConstraints = containerConstraints.copyWith(maxWidth: containerConstraints.maxWidth - contentPadding.horizontal);
boxToBaseline[prefix] = _layoutLineBox(prefix, contentConstraints);
boxToBaseline[suffix] = _layoutLineBox(suffix, contentConstraints);
```
Then it looks like this:

And then `_layout` will be the same as `computeMinIntrinsicHeight`.
What do you think about it? @LongCatIsLooong @justinmc

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart]: This seems the Android material_components library is allowing the `prefixText` `suffixText` to grow vertically without imposing any constraints  (I'm not familiar with Android layout primitives so I could be wrong): 
https://github.com/material-components/material-components-android/blob/34740b6fdf164665c438658935653d354a64d72b/lib/java/com/google/android/material/textfield/TextInputLayout.java#L779-L783

The solution you proposed makes sense. I couldn't find anything in the material spec regarding how prefix text and suffix text should be laid out.

Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart]: Can I change it now and this will be approved?

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/input_decorator.dart]: Yup, good catch.

[the remark this answers is not in the document]
Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart]: Can I fix it here?

[the remark this answers is not in the document]
Comment (smitsk) [reply packages/flutter/lib/src/material/input_decorator.dart]: I fixed it.

**Review by LongCatIsLooong — APPROVED** [review]
Thank you for looking into this!

**Comment by LongCatIsLooong** [comment]
The failure seems to indicate there's something wrong with the tip of the tree and probably has nothing to do with this change. I'll let you know when the problem is resolved.

**Comment by LongCatIsLooong** [comment]
Could you try syncing the branch to head and see if the CI failures persist?

**Comment by LongCatIsLooong** [comment]
The one luci failure just means there's something wrong (or the CI hasn't finished running) on `upstream/master`. I've put on the "waiting for tree to go green" tag so this one will get merged as soon as the `upstream/master` tree is back to green (given there's no google testing failure). Thank you for contributing!

**Comment by smitsk** [comment]
Thanks for review! I have synchronized this with the base branch.

**Comment by smitsk** [comment]
Thank you for review!
