### PR TITLE
[android] only release background image readers on Android 14.

### LINKED ISSUE #156488: Simplify `ImageReaderSurfaceProducer`: Do not trim memory for external textures
As of the migration from `SurfaceTexture` to `ImageReader`, we inadvertently broke the ability to run videos in the background, because when the application is backgrounded it typically receives a `TRIM_MEMORY(BACKGROUND)` event, which in turn causes the surface to be released.

For example, [this option is no longer functional](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerOptions/allowBackgroundPlayback.html):

```dart
VideoPlayerOptions({
  bool allowBackgroundPlayback = false,
})
```

@johnmccutchan mentioned that the particular workaround was for Android 14, and it's possible that in other versions (i.e. Android 15 or newer), we could support background playback (by not releasing the texture). However, I want to make sure (a) I understand this correctly, (b) we consider this a problem, and (c) have a plan on how to fix this - for now it's likely I need to just make a note this functionality is unsupported on Android (or folks will need to fallback to an older pre-ImageReader version of the plugin, which is not ideal).

### LINKED ISSUE #156489: `allowBackgroundPlayback` no longer works in `video_player_android`
This is a placeholder issue to track the fact that `allowBackgroundPlayback` is non-functional in `video_player_android`.

We are discussing technical solutions in https://github.com/flutter/flutter/issues/156488, this issue will track actually fixing the plugin.

### LINKED ISSUE #163520: When using PlatformView to create TextureView or SurfaceView on Android, the content on the surface disappears when returning from the background to the foreground
### Steps to reproduce

1. Run sample project on Android
2. Render content on TextureView or SurfaceView in PlatformView
3. Background app
4. Foreground app

### Expected results

The display remains on the PlatformView.

### Actual results

As shown in the video, the display disappears when returning from the background, but reappears when continuing video playback or performing a hot reload in the code

https://github.com/user-attachments/assets/fbd5199d-2e05-4a27-a949-9be86b32d534

### Code sample

https://github.com/Kongdy/miss_img_demo

https://github.com/LiteAVSDK/Player_Flutter

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Tested Flutter versions
3.29.0 ❌ Issue occurs
3.27.4 ❌ Issue occurs
3.27.3 ❌ Issue occurs
3.27.2 ❌ Issue occurs
3.24.5 ❌ Issue occurs
3.22.3 ❌ Issue occurs
3.19.0  ✓ As expected

### Tested Devices
Oppo reno 7 on  Android 13
Xiaomi MIX4 on Android 14

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
~/StudioProject/SuperPlayer/Flutter/example git:[main]
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-AL)
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (7 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.1)

[✓] Connected device (4 available)
[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #163561: `ImageExternalTexture` should fallback to previous image if next image is unavailable
_Blocks https://github.com/flutter/flutter/issues/156488._

---

In https://github.com/flutter/flutter/issues/156488, we wanted to simplify how `ImageReaderSurfaceProducer` works, and, for external texture plugins, stop listening to `TRIM_MEMORY` Android events as a determination to invalidate the surface (and rebuild). A blocker to the approach is some incompatible logic in how the C++ engine works with `ImageReader`.

In a bit more detail, the following stanza conditionally draws the texture image if available:

https://github.com/flutter/flutter/blob/d6a6e95c32f316dbfdd7bfb957740c7f00344045/engine/src/flutter/shell/platform/android/image_external_texture.cc#L39-L50

However, in practice, we see that, if the following occurs:

1. An `ImageReaderSurfaceProducer` is created and drawn to (statically, i.e. not streaming an image from another source)
2. You background the app, triggering [`OnGrContextDestroyed`](https://github.com/flutter/flutter/blob/d6a6e95c32f316dbfdd7bfb957740c7f00344045/engine/src/flutter/common/graphics/texture.cc#L74-L84)
3. You resume the app, we no longer have a `dl_image_`, but nothing will trigger a new image to become available

... we (at HEAD), hit `No DlImage available for ImageExternalTexture to paint`.

This can be observed in [`android_engine_test`](https://github.com/flutter/flutter/tree/master/dev/integration_tests/android_engine_test) with the following patch:

```diff
# engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L447
-  private static final boolean CLEANUP_ON_MEMORY_PRESSURE = true;
+  private static final boolean CLEANUP_ON_MEMORY_PRESSURE = false;
```

... and then run an integration test:

```sh
cd dev/integration_tests/android_engine_test
et run lib/external_texture/surface_producer_smiley_face_main.dart -c android_debug_unopt_arm64
```

... and using the home button on a device (or emulator), switching to another app, and switching back.

A "fix" (that is not proper) is the following:

```diff
diff --git a/engine/src/flutter/shell/platform/android/image_external_texture.cc b/engine/src/flutter/shell/platform/android/image_external_texture.cc
index ed9e7b3c7f9..60bc7d20c9c 100644
--- a/engine/src/flutter/shell/platform/android/image_external_texture.cc
+++ b/engine/src/flutter/shell/platform/android/image_external_texture.cc
@@ -66,7 +66,7 @@ void ImageExternalTexture::OnGrContextCreated() {
 // Implementing flutter::ContextListener.
 void ImageExternalTexture::OnGrContextDestroyed() {
   if (state_ == AttachmentState::kAttached) {
-    dl_image_.reset();
+    // dl_image_.reset();
     image_lru_.Clear();
     Detach();
   }
```

What we _should_ do is instead, is if we fail to acquire the latest image, check the _previous_ image instead:

https://github.com/flutter/flutter/blob/d6a6e95c32f316dbfdd7bfb957740c7f00344045/engine/src/flutter/shell/platform/android/image_external_texture_vk_impeller.cc#L40-L43

https://github.com/flutter/flutter/blob/d6a6e95c32f316dbfdd7bfb957740c7f00344045/engine/src/flutter/shell/platform/android/image_external_texture.cc#L76-L85

Ideally this is done where it impacts _all_ subclasses of `ImageExternalTexture` (this is _not_ specific to Vulkan).

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/163561
Fixes https://github.com/flutter/flutter/issues/156488
Fixes https://github.com/flutter/flutter/issues/156489
Fixes https://github.com/flutter/flutter/issues/163520

Forked from https://github.com/flutter/flutter/pull/163692

Only release background image readers on Android 14. I believe reader disposal is the ultimate cause of https://github.com/flutter/flutter/issues/162147 , where older android devices don't seem to handle backgrounding the same way we expect on newer devices. The result of this is a crash in HWUI, which is unexpected.

Since we only ever did the background release to work around an ANdroid 14 bug, and because it breaks other functionality like background playback - we should remove it for all targets besides 14.

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java [hunk 1]
```diff
@@ -186,37 +186,16 @@ private void clearDeadListeners() {
...
-    // plugins (i.e. end-users) use the Surface instead, letting us "hide" the
-    // consumer-side
-    // of the implementation.
-    //
-    // tl;dr: If ImageTexture is available, we use it, otherwise we use a
-    // SurfaceTexture.
-    // Coincidentally, if ImageTexture is available, we are also on an Android
-    // version that is
-    // running Vulkan, so we don't have to worry about it not being supported.
+  public SurfaceProducer createSurfaceProducer(SurfaceLifecycle lifecycle) {
```
Comment (matanlurey) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java:189]: God I miss default methods and overloads.

**Review by matanlurey — APPROVED** [review]
LGTM pending that you try this on video_player_android/example and when the video is backgrounded, it keeps playing (audio) and resume it is both playing and visible.

You'll also want to do this very quickly, back and forth, and make sure there isn't a weird timing issue (this PR should have removed all timing issues but who knows honestly).

**Comment by jonahwilliams** [comment]
it work!

**Comment by emakar** [comment]
This also fixes https://github.com/flutter/flutter/issues/163520, right?

**Comment by jonahwilliams** [comment]
@emakar right, it should also fix that _except_ on Android 14 - but we can fix it there as the android bug is still present.

**Comment by xudshen** [comment]
can this pr merged into 3.27.x?
