### PR TITLE
Fix `shape` and `collapsedShape` isn't applied to `ExpansionTile`'s splash ink

### LINKED ISSUE #107113: `ExpansionTile.backgroundColor` &  `ExpansionTile.collapsedBackgroundColor` removes splash effect
## Steps to Reproduce

1. Open this demo on DartPad: https://dartpad.dev/bb018c7bfe104bbfe78185a7fc6641e4
2. Run the sample
3. Expand the first `ExpansionTile` widget
4. Attempt to hover over the widget

**Expected results:** The opacity should be changed on hover to reflect the tap affordance of the widget (i.e. it's a button)

**Actual results:** Overriding the `backgroundColor` of the `ExpansionTile` also overrode the hover opacity.

<details>
<summary>Code sample</summary>

See https://dartpad.dev/bb018c7bfe104bbfe78185a7fc6641e4

</details>

Screen Recording:

[flutter-expension-tile-bug.webm](https://user-images.githubusercontent.com/1950680/177402618-541f5176-072a-4f27-8007-a253e3bf9701.webm)

### LINKED ISSUE #125779: ExpansionTile InkSplash doesn't respect Shape's borderRadius
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Similar issue #86603. 

Other failed workaround attempts were to

- Assign `clipBehaviour` to `ExpansionTile`
- Wrapped `InkWell` with `borderRadius`
- Wrapped `ClipRRect` with `borderRadius`

The only workaround that worked is to wrap `ExpansionTile` with `Card` or `Material` suggested in [this SO thread](https://stackoverflow.com/a/70756898/5408464)

The core underlying problem is the `ListTile` under the hood, which has seen many instances of the [same problem.](https://stackoverflow.com/questions/60040972/flutter-listtile-splash-ripple-effect-not-matching-border) Usually the workaround is the wrap the `ListTile` in an `InkWell` however this is not possible with `ExpansionTile`.

1. Run the sample code.
2. Tap on the ListTile to see that the InkSplash doesn't clip the shape's borderRadius

I would like to help to resolve this issue but I am not clear on the proper way to fix this. Is passing the `shape` property to `ListTile` the correct move?

### Expected results

InkSplash should not exceed shape's border

### Actual results

InkSplash exceeds shape's border

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      clipBehavior: Clip.antiAlias,
      borderRadius: BorderRadius.circular(20),
      child: ExpansionTile(
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
          side: const BorderSide(color: Colors.black, width: 3),
          borderRadius: BorderRadius.circular(20),
        ),
        collapsedShape: RoundedRectangleBorder(
          side: const BorderSide(color: Colors.black, width: 3),
          borderRadius: BorderRadius.circular(20),
        ),
        title: const Text("InkSplash not respecting shape's borderRaidus"),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/68549184/235405431-1e752b20-75eb-4c2c-a495-81f8067e91af.mov

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64,
    locale en-MY)
    • Flutter version 3.7.12 on channel stable at /Users/samuel/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.2)
    • Android SDK at /Users/samuel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 112.0.5615.137
    ! Error: Samuel’s iPhone is busy: Waiting to connect and unlock the device.
      Xcode will continue when Samuel’s iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
This updates the previous attempt https://github.com/flutter/flutter/pull/135855 and removes the complications when testing M3 ink sparkle effect. 
Thanks to this [PR](https://github.com/flutter/flutter/pull/138757) by @Piinks 

fixes [ExpansionTile InkSplash doesn't respect Shape's borderRadius](https://github.com/flutter/flutter/issues/125779)
fixes [`ExpansionTile.backgroundColor` &  `ExpansionTile.collapsedBackgroundColor` removes splash effect](https://github.com/flutter/flutter/issues/107113)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
          child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 24.0),
        child: ExpansionTile(
          collapsedBackgroundColor: Color(0x25ff0000),
          backgroundColor: Color(0x250000ff),
          collapsedShape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(30.0)),
            side: BorderSide(color: Colors.black, width: 2.0),
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(30.0)),
            side: BorderSide(color: Colors.black, width: 2.0),
          ),
          clipBehavior: Clip.hardEdge,
          title: Text('Expansion Tile'),
          children: <Widget>[
            FlutterLogo(size: 50),
            FlutterLogo(size: 50),
            FlutterLogo(size: 50),
            FlutterLogo(size: 50),

          ],
        ),
      )),
    );
  }
}
```

</details>

### Before

Screenshot 2024-01-18 at 18 16 15

Screenshot 2024-01-18 at 18 16 44

### After 
Screenshot 2024-01-18 at 18 20 27

Screenshot 2024-01-18 at 18 20 53

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 1]
```diff
@@ -475,6 +475,9 @@ class ExpansionTile extends StatefulWidget {
 
   /// {@macro flutter.material.Material.clipBehavior}
   ///
+  /// If this is not null and a custom collapsed or expanded shape is provided,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/expansion_tile.dart:478]: To prevent a common mistake, why not make the default Clip.antiaAlias when a shape is specified? The developer can always override the default of course.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/expansion_tile.dart:478]: Excellent idea! We will no longer to specify shapes as well as a custom `clipBehavior`.  
```diff
          collapsedShape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(30.0)),
            side: BorderSide(color: Colors.black, width: 2.0),
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(30.0)),
            side: BorderSide(color: Colors.black, width: 2.0),
          ),
--       clipBehavior: Clip.antiAlias,
```

Just pushed a commit with updated default `clipBehavior`, docs and new tests.

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 2]
```diff
@@ -656,11 +659,12 @@ class _ExpansionTileState extends State<ExpansionTile> with SingleTickerProvider
...
+    final Color backgroundColor = _backgroundColor.value ?? expansionTileTheme.backgroundColor ?? Colors.transparent;
     final ShapeBorder expansionTileBorder = _border.value ?? const Border(
-            top: BorderSide(color: Colors.transparent),
-            bottom: BorderSide(color: Colors.transparent),
-          );
-    final Clip clipBehavior = widget.clipBehavior ?? expansionTileTheme.clipBehavior ?? Clip.none;
+      top: BorderSide(color: Colors.transparent),
+      bottom: BorderSide(color: Colors.transparent),
+    );
+    final Clip clipBehavior = widget.clipBehavior ?? expansionTileTheme.clipBehavior ?? Clip.antiAlias;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/expansion_tile.dart:667]: Maybe make the last clause be
```dart
(isShapeProvided ? clip.antiAlias : Clip.none)
```

Since `clip.antiAlias` comes with a cost. And then document the fact the default for clipBehavior depends on whether of not a shape was provided.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/expansion_tile.dart:667]: `clipBehavior` is never used without shape. 

It returns a `DecoratedBox` when no shape is provided for two reasons:
1. We don't need to add` Material` widget when not necessary`.
2. Previously `Container` used the `clipBehavior` but it was effective as the ink splash is actually rendered by the underling `ListTile` widget. 

Screenshot 2024-01-19 at 20 00 39

Comment (HansMuller) [reply packages/flutter/lib/src/material/expansion_tile.dart:667]: I see, looks good then!

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by LucasMatheusDev — COMMENTED** [review]
good job
