### PR TITLE
Fix Image's logical flow which disposes its image too early, causing errors such as "Cannot clone a disposed image"

### LINKED ISSUE #110129: `Image` disposes its image too early, causing errors such as "Cannot clone a disposed image"
## Bug analysis and solution

Summary: Looking at `Image`. When its new image is decoded, it will *immediately* dispose its old image handle. However, this is logically wrong - the old image handle may still be used in the (near) future.

At the first glance, this looks impossible, because when the old image handle is disposed, we will no longer give it to child widget tree. And we all know that, Flutter builds widget tree from ancestors to descendants. Therefore, as long as the ancestor (Image) provides the new image handle to its children (RawImage), its children should not use the old image handle after it is disposed.

However, it is not true and this bug is indeed there. There are some special but very widely used widgets that "breaks" this mental modal, such as the `LayoutBuilder`. When we have something like `WidgetOne(child: LayoutBuilder(builder: WidgetTwo()))`, and `WidgetOne` and `WidgetTwo` both `markNeedsBuild` (such as by `setState`), then the build order is indeed: `WidgetOne - WidgetTwo(with old data) - LayoutBuilder - WidgetTwo(with new data)`. The "WidgetTwo(with old data)" will cause bugs in our case. In our case, the "old data" is equivalent to "the image handle that we *have disposed*", so we are indeed using a disposed image handle.

Reproducible samples are given below to verify the theoretical analysis.

---

## Steps to Reproduce

Run the following self-contained test. (I added a lot of logs so you can see what is happening)

**Expected results:** 
No error

**Actual results:** 
Errors. Please have a look at logs below.

<details>
<summary>Code sample</summary>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  const imageData =
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII=';

  testWidgets('hi', (tester) async {
    final outerListenable = ValueNotifier<int>(0);
    final innerListenable = ValueNotifier<int>(0);

    var frameBuilderCountWithImage = 0;
    var image = MemoryImage(base64Decode(imageData));

    Future<void> runAsyncAndIdle() async {
      for (var i = 0; i < 20; ++i) {
        await tester.runAsync(() => Future<void>.delayed(Duration.zero));
        await tester.idle();
      }
    }

    await tester.pumpWidget(MaterialApp(
      home: Center(
        child: ValueListenableBuilder<void>(
          valueListenable: outerListenable,
          builder: (_, __, ___) {
            debugPrint('build outer-Observer');
            return Image(
              image: image,
              frameBuilder: (_, child, __, ___) {
                final peekChildImage = ((child as Semantics).child! as RawImage).image;
                debugPrint('build Image.frameBuilder peekChildImage=$peekChildImage');

                if (peekChildImage != null) {
                  frameBuilderCountWithImage++;
                }

                return LayoutBuilder(builder: (_, __) {
                  debugPrint('build LayoutBuilder peekChildImage=$peekChildImage');

                  return ValueListenableBuilder(
                    valueListenable: innerListenable,
                    builder: (_, __, ___) {
                      debugPrint('build inner-Observer peekChildImage=$peekChildImage');

                      return KeyedSubtree(
                        key: UniqueKey(),
                        child: child,
                      );
                    },
                  );
                });
              },
            );
          },
        ),
      ),
    ));

    while (frameBuilderCountWithImage == 0) {
      debugPrint('pump to wait for frameBuilderCountWithImage');
      await runAsyncAndIdle();
      await tester.pump();
    }

    debugPrint('--- modify observable ---');
    image = MemoryImage(base64Decode(imageData)); // imagine it is a new image
    outerListenable.value++;
    innerListenable.value++;

    debugPrint('--- pump ---');
    frameBuilderCountWithImage = 0;
    while (frameBuilderCountWithImage == 0) {
      debugPrint('pump to wait for frameBuilderCountWithImage');
      await runAsyncAndIdle();
      innerListenable.value++;
      await tester.pump();
    }
  });
}
```

</details>

<details>
  <summary>Logs</summary>

```
/Users/tom/fvm/default/bin/flutter --no-color test --machine --start-paused test/hello.dart
Testing started at 08:53 ...

build outer-Observer
build Image.frameBuilder peekChildImage=null
build LayoutBuilder peekChildImage=null
build inner-Observer peekChildImage=null
hi RawImage#70162 createRenderObject image=Null#007db
pump to wait for frameBuilderCountWithImage
build Image.frameBuilder peekChildImage=[1×1]
build LayoutBuilder peekChildImage=[1×1]
build inner-Observer peekChildImage=[1×1]
hi RawImage#1016a createRenderObject image=Image#da4a8
--- modify observable ---
--- pump ---
pump to wait for frameBuilderCountWithImage
build outer-Observer
build Image.frameBuilder peekChildImage=null
build inner-Observer peekChildImage=[1×1]
hi RawImage#1016a createRenderObject image=Image#da4a8
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building KeyedSubtree-[#358f6]:
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been
disposed, it can no longer be used to create handles, as the underlying data may have been released.

The relevant error-causing widget was:
  KeyedSubtree-[#358f6]
  KeyedSubtree:file:///Users/tom/Main/yplusplus/frontend/yplusplus_core/test/hello.dart:48:30

When the exception was thrown, this was the stack:
#0      Image.clone (dart:ui/painting.dart:1815:7)
#1      RawImage.createRenderObject (package:flutter/src/widgets/basic.dart:5794:21)
#2      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5662:52)
...     Normal element mounting (10 frames)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1183:19)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1050:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1037:27)
#27     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:608:53)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:608:27)
#32     main.<anonymous closure> (file:///Users/tom/Main/yplusplus/frontend/yplusplus_core/test/hello.dart:79:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
build LayoutBuilder peekChildImage=null
build inner-Observer peekChildImage=null
hi RawImage#6170d createRenderObject image=Null#007db
pump to wait for frameBuilderCountWithImage
build Image.frameBuilder peekChildImage=[1×1]
build inner-Observer peekChildImage=null
hi RawImage#6170d createRenderObject image=Null#007db
build LayoutBuilder peekChildImage=[1×1]
build inner-Observer peekChildImage=[1×1]
hi RawImage#e64b1 createRenderObject image=Image#e025c
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building KeyedSubtree-[#358f6]:
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been
disposed, it can no longer be used to create handles, as the underlying data may have been released.

When the exception was thrown, this was the stack:
#0      Image.clone (dart:ui/painting.dart:1815:7)
#1      RawImage.createRenderObject (package:flutter/src/widgets/basic.dart:5794:21)
#2      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5662:52)
...     Normal element mounting (10 frames)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1183:19)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1050:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1037:27)
#27     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:608:53)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:608:27)
#32     main.<anonymous closure> (file:///Users/tom/Main/yplusplus/frontend/yplusplus_core/test/hello.dart:79:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4186:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4200:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4299:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3051:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:2974:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:2950:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1291:31)
#7      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:3009:105)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1244:63)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1121:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1014:13)
#11     _defaultTestExceptionReporter (package:flutter_test/src/test_exception_reporter.dart:32:16)
#12     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:663:28)
#22     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart)
<asynchronous suspension>
(elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4186:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4200:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4299:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3051:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:2974:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:2950:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1291:31)
#7      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:3009:105)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1244:63)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1121:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1014:13)
#11     _defaultTestExceptionReporter (package:flutter_test/src/test_exception_reporter.dart:32:16)
#12     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:663:28)
#22     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart)
<asynchronous suspension>
(elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4186:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4200:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4299:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3051:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:2974:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:2950:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1291:31)
#7      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:3006:77)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1280:14)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1121:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1014:13)
#11     _defaultTestExceptionReporter (package:flutter_test/src/test_exception_reporter.dart:32:16)
#12     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:663:28)
#22     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart)
<asynchronous suspension>
(elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
The following assertion was thrown:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4186:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4200:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4299:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:3051:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:2974:12)
#5      debugTransformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:2950:21)
#6      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1291:31)
#7      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:3006:77)
#8      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1280:14)
#9      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1121:14)
#10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1014:13)
#11     _defaultTestExceptionReporter (package:flutter_test/src/test_exception_reporter.dart:32:16)
#12     TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:663:28)
#22     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart)
<asynchronous suspension>
(elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)

This exception was caught while trying to describe the user-relevant code of another error.
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: hi
```

```
no error
```

```
latest
```

</details>

---

A shorter reproducible sample, if you are interested:

<details>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('hi', (tester) async {
    const imageData =
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII=';

    final outerListenable = ValueNotifier<int>(0);
    final innerListenable = ValueNotifier<int>(0);

    var imageLoaded = false;
    var image = MemoryImage(base64Decode(imageData));

    Future<void> runAsyncAndIdle() async {
      for (var i = 0; i < 20; ++i) {
        await tester.runAsync(() => Future<void>.delayed(Duration.zero));
        await tester.idle();
      }
    }

    await tester.pumpWidget(ValueListenableBuilder(
      valueListenable: outerListenable,
      builder: (_, __, ___) => Image(
        image: image,
        frameBuilder: (_, child, __, ___) {
          if (((child as Semantics).child! as RawImage).image != null) imageLoaded = true;
          return LayoutBuilder(
            builder: (_, __) => ValueListenableBuilder(
              valueListenable: innerListenable,
              builder: (_, __, ___) => KeyedSubtree(
                key: UniqueKey(),
                child: child,
              ),
            ),
          );
        },
      ),
    ));

    while (!imageLoaded) {
      await runAsyncAndIdle();
      await tester.pump();
    }

    image = MemoryImage(base64Decode(imageData)); // imagine it is a new image
    outerListenable.value++;

    imageLoaded = false;
    while (!imageLoaded) {
      await runAsyncAndIdle();
      innerListenable.value++;
      await tester.pump();
    }
  });
}

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close #110129

Please see the issue for paragraphs about the bug cause and fix etc

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by fzyzcjy** [comment]
The test, without the fix, fails. This verifies the PR is needed.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804990179272978753/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building KeyedSubtree-[#c5088]:
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been
disposed, it can no longer be used to create handles, as the underlying data may have been released.

When the exception was thrown, this was the stack:
#0      Image.clone (dart:ui/painting.dart:1808:7)
#1      RawImage.createRenderObject (package:flutter/src/widgets/basic.dart:5951:21)
#2      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5744:52)
...     Normal element mounting (10 frames)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3883:16)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3606:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4920:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5060:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4617:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2687:19)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1244:19)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:374:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1093:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1079:27)
#27     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:618:53)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:618:27)
#32     main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/image_test.dart:83:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════

02:21 +3329 ~2 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/image_test.dart: Verify Image does not use disposed handles [E]                                                                 
  Test failed. See exception logs above.
  The test description was: Verify Image does not use disposed handles
  
══╡ EXCEPTION CAUGHT BY WIDGET INSPECTOR ╞══════════════════════════════════════════════════════════
```

**Comment by fzyzcjy** [comment]
All tests have passed

image

File: packages/flutter/test/widgets/image_test.dart [hunk 1]
```diff
@@ -35,6 +35,57 @@ void main() {
...
+      ),
+    ));
+
+    while (!imageLoaded) {
+      await runAsyncAndIdle();
+      await tester.pump();
+    }
+
+    image = MemoryImage(Uint8List.fromList(kBlueSquarePng));
+    outerListenable.value++;
```
Comment (dnfield) [inline packages/flutter/test/widgets/image_test.dart:79]: nit: Flutter style says do not use `++` or `--`. 
```suggestion
    outerListenable.value += 1;
```

(And below).

File: packages/flutter/test/widgets/image_test.dart [hunk 2]
```diff
@@ -35,6 +35,57 @@ void main() {
...
+    Future<void> runAsyncAndIdle() async {
+      for (int i = 0; i < 20; ++i) {
+        await tester.runAsync(() => Future<void>.delayed(Duration.zero));
+        await tester.idle();
+      }
+    }
+
+    await tester.pumpWidget(ValueListenableBuilder<int>(
+      valueListenable: outerListenable,
+      builder: (BuildContext _, Object? __, Widget? ___) => Image(
```
Comment (dnfield) [inline packages/flutter/test/widgets/image_test.dart:54]: style nit, here and elsewhere: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-anonymous-parameter-names

File: packages/flutter/test/widgets/image_test.dart [hunk 3]
```diff
@@ -35,6 +35,57 @@ void main() {
...
+        image: image,
+        frameBuilder: (BuildContext _, Widget child, int? __, bool ___) {
+          if (((child as Semantics).child! as RawImage).image != null) {
```
Comment (dnfield) [inline packages/flutter/test/widgets/image_test.dart:57]: This is depending on implementation details that are not actually part of this test.

Instead, you could check if the `int? frameNumber` parameter `== 1`, which indicates the first (and in this case, only) frame of the image is loaded.

Comment (dnfield) [reply packages/flutter/test/widgets/image_test.dart:57]: This should also probably be setting a completer or a stream controller or something, so that it can be waited on without using the while loops below.

File: packages/flutter/test/widgets/image_test.dart [hunk 4]
```diff
@@ -35,6 +35,57 @@ void main() {
...
+
+    bool imageLoaded = false;
+    MemoryImage image = MemoryImage(Uint8List.fromList(kTransparentImage));
+
+    Future<void> runAsyncAndIdle() async {
+      for (int i = 0; i < 20; ++i) {
+        await tester.runAsync(() => Future<void>.delayed(Duration.zero));
+        await tester.idle();
+      }
+    }
```
Comment (dnfield) [inline packages/flutter/test/widgets/image_test.dart:50]: This is a little difficult to reason about and may cause the test to take longer than needed or in fact never terminate (for example, if the image cache manages to get a hold of a completer that was created in the fake async zone, no amount of real async delays will fix that). I suspect we're getting lucky right now and not running into this case, but we could.

I think the easiest option would be to use `_TestImageProvider`s which you can manually complete with real-async images (like the `image10x10` defined above in this test file). Alternatively, you can use a memory image but you have to be more careful to make sure the image cache doesn't get involved and more explicit about what we're waiting for here -and asserting that the thing we're waiting for actually happens.

**Review by dnfield — CHANGES_REQUESTED** [review]
The change makes sense to me and I think it's the right one. Thanks for doing some hard work here!

There are no expectations in the test that actually tell us whether the images ever actually complete, and its currently depending on some implementation details like `RawImage` being wrapped in a `Semantics` or being in the tree for this at all. Someone refactoring that code may easily misunderstand that this test actually is using those details to find the image.

It would be better to have a test that asserts we've done something meaningful as well. For example, someone could introduce a breakage to what you're fixing in the future where the second image never loads or the expected build order does not happen and this test would still pass.

I'd like to see the test _not_ use any `while` loops, and have some more `expect`ations about what's happening. Happy to chat some more about how to do this if it's not clear.

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
LGTM once tests are passing :)

**Comment by fzyzcjy** [comment]
@dnfield Tests are passing :)

image

**Comment by fzyzcjy** [comment]
What should I do now 👀

**Comment by dnfield** [comment]
Sorry, thought I had added the label!

**Comment by fzyzcjy** [comment]
@dnfield That's OK. Oops seems need one more reviewer

**Review by goderbauer — APPROVED** [review]
LGTM
