### PR TITLE
Don't crash on `flutter create .` on Windows

### LINKED ISSUE #9828: flutter create crashed on Windows
Output:

```
C:\Users\eli ladd\Code\myflutterapp>flutter create .

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 41485a7640000000)
Crash report written to C:\Users\eli ladd\Code\myflutterapp\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
C:\Users\eli ladd\Code\myflutterapp>flutter create .

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 41485a7640000000)
Crash report written to C:\Users\eli ladd\Code\myflutterapp\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\Users\eli ladd\Code\myflutterapp>flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 31000ef77e (2 days ago) • 2017-05-02 21:12:28 -0700
Engine • revision da8ebf40bd
Tools • Dart 1.23.0-dev.11.11
```

```
C:\Users\eli ladd\Code\myflutterapp>flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 31000ef77e (2 days ago) • 2017-05-02 21:12:28 -0700
Engine • revision da8ebf40bd
Tools • Dart 1.23.0-dev.11.11

C:\Users\eli ladd\Code\myflutterapp>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at c:\Users\eli ladd\Code\flutter
    • Framework revision 31000ef77e (2 days ago), 2017-05-02 21:12:28 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\eli ladd\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • None
```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes #9828 

Work-around for https://github.com/dart-lang/core/issues/507.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/create.dart [hunk 1]
```diff
@@ -92,7 +92,10 @@ class CreateCommand extends FlutterCommand {
     final bool generatePlugin = argResults['plugin'];
 
     final Directory projectDir = fs.directory(argResults.rest.first);
-    final String dirPath = fs.path.normalize(projectDir.absolute.path);
+    String dirPath = fs.path.normalize(projectDir.absolute.path);
+    // Work-around for: https://github.com/dart-lang/path/issues/24
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/commands/create.dart]: Maybe add a TODO to make finding this greppable.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by tvolkert** [comment]
LGTM modulo Chris' comment
