### PR TITLE
Rationalise all our exception handling.

### LINKED ISSUE #2356: Centralise the exception reporting so that we coalesce widget exceptions also
Rendering exceptions only show the first one, after that they're all coalesced. We should do the same for all exceptions by routing everything through a single exception processing function. This would also help with fixing #2323 and #2220.

### PR DESCRIPTION
**Pull request by Hixie**
- Create a FlutterErrorDetails struct-like class that describes an
  exception along with more details that aren't in the exception, like
  where it was caught and what was going on when it was caught.
- Provide a FlutterError static API for handling these objects:
  - FlutterError.onError which is called whenever Flutter catches an
    error.
  - FlutterError.reportError() which handles an error.
  - FlutterError.dumpErrorToConsole() which is the default behavior
    for onError.
- Removes all the existing exception handler callbacks.
- Replaces all the existing places that described exceptions using
  debugPrint with calls to FlutterError.reportError().
- Extend lockState() to also catch exceptions, so that we catch
  exceptions that happen during finalizers.
- Make the test framework catch errors and treat them as failures.
- Provide a mechanism to override this behavior in the test framework.
- Make the tests that used to depend on the exception handler
  callbacks use this new mechanism.
- Make pump() also support the phase argument.
- Improve some tests using these new features.

Fixes #2356, #2988, #2985, #2220.

### CODE REVIEW

File: packages/flutter/lib/src/services/assertions.dart [hunk 1]
```diff
@@ -17,19 +90,87 @@ class FlutterError extends AssertionError {
...
+  /// In some cases, when a FlutterError is reported to the user, only the first
+  /// line is included. For example, Flutter will typically only fully report
+  /// the first exception at runtime, displaying only the first line of
+  /// subsequent errors.
   ///
   /// All sentences in the error should be correctly punctuated (i.e.,
   /// do end the error message with a period).
   final String message;
-
+
```
Comment (abarth) [inline packages/flutter/lib/src/services/assertions.dart]: Trailing whitespace!

**Comment by abarth** [comment]
LGTM

We might consider using Zones for the error handler in the future.  That way you can have different error handlers installed at once for different parts of your app.  In any case, this change is a massive improvement.

File: packages/flutter/lib/src/services/assertions.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/services/assertions.dart]: oops. fixed.

**Comment by Hixie** [comment]
I've looked at using zones before (in particular to get better async stack traces) but I've not figured out a good way to do it (in part because I can't find good docs for that API). If you file a bug with more detail about what you want I'm happy to implement it.
