### PR TITLE
`ExpansionTile` Unable to remove right padding from title

### LINKED ISSUE #145268: `ExpansionTile` Unable to remove right padding from title
### Steps to reproduce

Run the provided code

### Expected results

The `ExpansionTile`'s `title` spans the available width.

### Actual results

image

The tile is cut short by 32.0 units.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ListTileTheme(
                contentPadding: EdgeInsets.zero,
                horizontalTitleGap: 0,
                minVerticalPadding: 0,
                dense: true,
                child: ExpansionTile(
                  tilePadding: EdgeInsets.zero,
                  title: Container(
                    color: Colors.red,
                    alignment: Alignment.centerLeft,
                    child: Text('Expansion Tile'),
                    height: 50,
                  ),
                  trailing: const SizedBox.shrink(),
                  children: const [
                    ListTile(title: Text('Item 1')),
                    ListTile(title: Text('Item 2')),
                    ListTile(title: Text('Item 3')),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

~~I traced it down to `list_tile.dart`'s `performLayout` where it says:~~

~~Removing the 32.0 from the `adjustedTrailingWidth` computation and putting in 0.0 instead makes the title span the full width as expected.~~

~~I ran tests with the changed value:~~
```
~/Flutter/flutter/packages/flutter > flutter test ./test/material/list_tile_test.dart 
Resolving dependencies... 
  leak_tracker 10.0.0 (10.0.4 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.3 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.12.0 available)
  test_api 0.6.1 (0.7.0 available)
  vm_service 13.0.0 (14.1.0 available)
  web 0.4.0 (0.5.1 available)
Got dependencies!
8 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
00:08 +68: All tests passed!  
```

~~So either there are more and just testing list_tile is not enough or it is not tested. I assume goldens would break.~~

See below comment for better analysis.

What is the reason why the value is 32.0?

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3 23D56 darwin-arm64, locale en-CZ)
    • Flutter version 3.19.2 on channel stable at /Users/michalhazdra/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michalhazdra/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by Michal-MK**
This PR makes it possible to remove the hard-coded 32.0 unit padding coming from ListTile when trailing is not null. Which it always it as `ExpansionTile` always provides a widget there. Currently there is no way to remove it and people have to hack around it: e.g. 
https://stackoverflow.com/questions/54714836/how-to-remove-default-padding-from-expansiontiles-header

The issue is quite old and I came across it today and decided to put together a quick fix.

Fixes #145268

The change should be non-breaking as the default stays the same. But I have no issue with changing something if requested. (naming-wise, functionality-wise etc...)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Ashymz** [comment]
Why this issue ?

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 1]
```diff
@@ -692,6 +700,12 @@ class _ExpansionTileState extends State<ExpansionTile> with SingleTickerProvider
       shape: expansionTileBorder,
     );
 
+    final Widget? trailing = widget.trailing
+      ?? (widget.showTrailingIcon
+        ? _buildTrailingIcon(context)
+        : null
+    );
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/expansion_tile.dart:707]:
```suggestion
    final Widget? trailing = widget.trailing
      ?? (widget.showTrailingIcon ? _buildTrailingIcon(context) : null);
```

**Review by HansMuller — APPROVED** [review]
LGTM

I made one gratuitous formatting change; the logic looks good.

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 2]
```diff
@@ -713,7 +724,7 @@ class _ExpansionTileState extends State<ExpansionTile> with SingleTickerProvider
                 leading: widget.leading ?? _buildLeadingIcon(context),
                 title: widget.title,
                 subtitle: widget.subtitle,
-                trailing: widget.trailing ?? _buildTrailingIcon(context),
+                trailing: trailing,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/expansion_tile.dart:727]: To me it makes more sense to have the `trailing` widget be not shown even if you provide it if `showTrailingIcon` is false:

```suggestion
                trailing: widget.showTrailingIcon ? widget.trailing ?? _buildTrailingIcon(context) : null,
```

Comment (Michal-MK) [reply packages/flutter/lib/src/material/expansion_tile.dart:727]: The assertion in the constructor prevents this scenario. If `widget.showTrailingIcon` is `false` then `widget.trailing` must be `null`. If I were to change it, it would probably need a new name `showTrailingWidget` or something. I'll wait for someone else's input on this.

**Comment by Michal-MK** [comment]
@HansMuller / @gspencergoog can we finish this before merge conflicts show up?

File: packages/flutter/lib/src/material/expansion_tile.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/expansion_tile.dart:745]: I think it could keep the name.  Mainly, I'd be surprised if I set the `trailing` icon, and then used the bool to turn its visibility on and off, only to find it would throw an assertion whenever it was false. I think more intuitive would to be allowed to set or not set the `trailing` icon, and the bool strictly says whether one is shown, and if `trailing` is null, then the default icon gets shown when `showTrailingIcon` is true.

**Comment by Michal-MK** [comment]
@gspencergoog Alright I removed the assert and accepted your modification. The tests should be unaffected. 🙏

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 3]
```diff
@@ -322,6 +323,9 @@ class ExpansionTile extends StatefulWidget {
   /// may replace the rotating expansion arrow icon.
   final Widget? trailing;
 
+  /// Specifies if the [ExpansionTile] should build a default trailing icon if [trailing] is null.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/expansion_tile.dart:326]: The comment should probably focus on the "show/no show" aspect, since that's the name of the parameter.

Maybe something like this instead?

```suggestion
  /// If true, the [ExpansionTile] will show a trailing icon.
  ///
  /// If true and [trailing] is set, [ExpansionTile] will use that trailing icon,
  /// otherwise a default trailing icon will be created.
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Approved, modulo the update of the comment I mentioned above. Thanks for the PR!

**Comment by Tr736** [comment]
Would you be able to let me know when this is going into stable. I was just about to open a PR that does exactly this

File: packages/flutter/lib/src/material/expansion_tile.dart (hunk 3 above)
Comment (ndonkoHenri) [reply packages/flutter/lib/src/material/expansion_tile.dart:326]: This was/is actually a valid change-request.
> "Specifies if the [ExpansionTile] should build a default trailing icon if [trailing] is null."

This current definition is somehow misleading, as this property simply toggles visibility of the trailing icon, be it the user-defined `trailing` or the default.
I personally got confused and had to jump into the source code to better understand what was happening.
