### PR TITLE
Fix RenderStack's documentation

### LINKED ISSUE #12885: Outdated document for location of non-positioned children in RenderStack
> /// The final location of non-positioned children is determined by the alignment
/// parameter. The left of each non-positioned child becomes the
/// difference between the child's width and the stack's width scaled by
/// alignment.x. The top of each non-positioned child is computed
/// similarly and scaled by alignment.y. So if the alignment x and y properties
/// are 0.0 (the default) then the non-positioned children remain in the
/// upper-left corner. If the alignment x and y properties are 0.5 then the
/// non-positioned children are centered within the stack.

The documentation describes alignment for FractionalOffset. Current implementation uses Alignment.

I am not a native English speaker, and feels hard to express the intention.

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
Fixes: #12885
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/stack.dart [hunk 1]
```diff
@@ -340,12 +340,14 @@ enum StackFit {
...
-/// parameter. The left of each non-positioned child becomes the
-/// difference between the child's width and the stack's width scaled by
-/// alignment.x. The top of each non-positioned child is computed
-/// similarly and scaled by alignment.y. So if the alignment x and y properties
-/// are 0.0 (the default) then the non-positioned children remain in the
-/// upper-left corner. If the alignment x and y properties are 0.5 then the
+/// parameter. The left of each non-positioned child becomes the difference
+/// between the stack's width and the child's width multiplied by
+/// (alignment.x + 1.0) / 2.0. The top of each non-positioned child is computed
+/// similarly using alignment.y.
```
[the remark this answers is not in the document]
Comment (AbdeMohlbi) [reply packages/flutter/lib/src/rendering/stack.dart]: done

File: packages/flutter/lib/src/rendering/stack.dart [hunk 2]
```diff
@@ -340,12 +340,14 @@ enum StackFit {
...
-/// are 0.0 (the default) then the non-positioned children remain in the
-/// upper-left corner. If the alignment x and y properties are 0.5 then the
+/// parameter. The left of each non-positioned child becomes the difference
+/// between the stack's width and the child's width multiplied by
+/// (alignment.x + 1.0) / 2.0. The top of each non-positioned child is computed
+/// similarly from the stack's height, the child's height, and `alignment.y`.
+///
+/// So if the alignment x and y properties are -1.0, then the non-positioned
+/// children remain in the upper-left corner (the top-start). If the
+/// alignment x and y properties are 0.0 (the default), then the
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/stack.dart]: Is the default 0.0 or -1.0?

Comment (AbdeMohlbi) [reply packages/flutter/lib/src/rendering/stack.dart]: not sure at this point but that is what the original comment say, ie: 0.0

Comment (AbdeMohlbi) [reply packages/flutter/lib/src/rendering/stack.dart]: after i checked in `AlignmentDirectional.topStart` which is the default i see : 
```dart
static const AlignmentDirectional topStart = AlignmentDirectional(-1.0, -1.0);
```
so the default is -1.0 which means the docs have been wrongs since the start or maybe the default value changed at one point from `AlignmentDirectional.center` to the current `AlignmentDirectional.topStart`, either way i will update the comments to remove the default mention, thanks for catching that!

**Review by victorsanni — APPROVED** [review]
