### PR TITLE
Documents and fixes behavior when clipping background filter fragment shader

### LINKED ISSUE #178798: `BackdropFilter` shader UV sampling is incorrect on beta when using `ClipRect`
This issue might be related to #[170820](https://github.com/flutter/flutter/pull/177687)

### Steps to reproduce

1. Run the code sample on the current beta channel, and on 3.38.0 (stable)
2. They produce different outputs

### Expected results

The UV's of `BackdropFilter` used to stay consistent, even if it was clipped. Output on 3.38.0:

Image

Notice how the top left of the shader's rect is not entirely black, and the purple border isn't visible, because UV (0,0) is the top left of the screen, not of the clip rect.

### Actual results

Output on 3.39.0-0.1.pre:

Image

Notice how the UV now seem to be in the coordinate space of the `ClipRectLayer`

### Code sample

<details open><summary>Code sample</summary>

**assets/shaders/uv.frag:**

```glsl

#version 460 core
precision mediump float;

#include <flutter/runtime_effect.glsl>

uniform vec2 uSize;
uniform sampler2D uTexture;

out vec4 fragColor;

void main() {
    vec2 fragCoord = FlutterFragCoord().xy;

    vec2 screenUV = vec2(fragCoord.x / uSize.x, fragCoord.y / uSize.y);        
    vec4 texColor = texture(uTexture, screenUV);
        
    #ifdef IMPELLER_TARGET_OPENGLES
        screenUV.y = 1.0 - screenUV.y;
    #endif
    
    // Check if we're within 20px of any edge
    float borderWidth = 20.0;
    bool inBorder = fragCoord.x < borderWidth || 
                    fragCoord.x > (uSize.x - borderWidth) ||
                    fragCoord.y < borderWidth || 
                    fragCoord.y > (uSize.y - borderWidth);
    
    if (inBorder) {
        fragColor = vec4(0.5, 0.0, 0.5, 1.0); // Purple border
    } else {
        fragColor = vec4(screenUV, 0.0, 1.0);
        fragColor = mix(fragColor, texColor, .5);
    }
}
```

**pubspec.yaml**
```yaml
name: flutter_sandbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/uv.frag
```

**lib/main.dart:**
```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_shaders/flutter_shaders.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            Positioned.fill(child: GridPaper()),
            Positioned.fill(
              child: ShaderBuilder(
                assetKey: 'assets/shaders/uv.frag',
                (context, shader, child) => MyShaderWidget(shader: shader),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class MyShaderWidget extends SingleChildRenderObjectWidget {
  const MyShaderWidget({super.key, required this.shader, super.child});

  final FragmentShader shader;

  @override
  RenderObject createRenderObject(BuildContext context) {
    return RenderMyShader(shader);
  }
}

class RenderMyShader extends RenderProxyBox {
  RenderMyShader(this.shader);

  final FragmentShader shader;

  final LayerHandle<ClipRectLayer> _clipRectLayer =
      LayerHandle<ClipRectLayer>();

  final LayerHandle<BackdropFilterLayer> _backdropFilterLayer =
      LayerHandle<BackdropFilterLayer>();

  static const inset = EdgeInsets.all(66);

  @override
  void paint(PaintingContext context, Offset offset) {
    final rect = offset & size;
    _clipRectLayer.layer = context.pushClipRect(
      true,
      offset,
      inset.deflateRect(rect),
      (context, offset) {
        final layer = _backdropFilterLayer.layer ??= BackdropFilterLayer();

        layer.filter = ImageFilter.shader(shader);
        context.pushLayer(layer, (context, offset) {}, offset);
      },
      oldLayer: _clipRectLayer.layer,
    );

    super.paint(context, offset);
  }

  @override
  void dispose() {
    _clipRectLayer.layer = null;
    _backdropFilterLayer.layer = null;
    super.dispose();
  }
}

```

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.39.0-0.1.pre, on macOS 15.7.2 24G325 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 26.0)
[✓] Chrome - develop for the web
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/178798

This passes all the golden tests.  It fixes the linked issue by avoiding rasterization which resets the frag coords.  I have a feeling there may be some case where this may fail that we haven't considered in a golden test.  This at moves us forward, documenting the desired behavior without breaking any golden tests.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/entity/contents/texture_contents.h [hunk 1]
```diff
@@ -125,6 +125,11 @@ class TextureContents final : public Contents {
   ///        apply it during rendering.
   void SetDeferApplyingOpacity(bool defer_applying_opacity);
 
+  /// The value on the `Snapshot` that will be returned from `RenderToSnapshot`
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/entity/contents/texture_contents.h]: This comment was hard to parse. Honestly, I'd just leave the at-see and call it a day.

How about, `SnapshotsNeedRasteriazationForRuntimeEffects`. Really give the ObjC writers a run for their money.

File: engine/src/flutter/impeller/entity/contents/texture_contents.h [hunk 2]
```diff
@@ -138,6 +143,7 @@ class TextureContents final : public Contents {
   Scalar opacity_ = 1.0f;
   Scalar inherited_opacity_ = 1.0f;
   bool defer_applying_opacity_ = false;
+  bool needs_rasterization_for_runtime_effects_ = false;
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/entity/contents/texture_contents.h]: Perhaps `snapshots_need_rasterization_for_runtime_effects_`.

**Review by chinmaygarde — APPROVED** [review]
Minor suggestions on naming.

File: engine/src/flutter/impeller/entity/contents/texture_contents.h (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/texture_contents.h]: done

File: engine/src/flutter/impeller/entity/contents/texture_contents.h (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/texture_contents.h]: done

**Comment by gaaclarke** [comment]
I misspoke.  I realized the bug for opengles was in the new shader I took from the bug report.  So it didn't render correctly either before, but that's because it had a flaw.  I've fixed it.
