### PR TITLE
Fix UiKitView which wrongly unconditionally repaints

### LINKED ISSUE #111788: UiKitView has buggy RenderObject
_Copied from PR_

### How the bug is found

This bug is surely not found by human eyes reading each and every line of Flutter code :)

I proposed the idea that a linter can be created (https://github.com/dart-code-checker/dart-code-metrics/issues/997) to validate whether RenderObject field setters have correct early-return code. @incendial implemented it and ran it (https://github.com/dart-code-checker/dart-code-metrics/pull/1003).

Thus, thanks @incendial for implementing the linter and run it through flutter framework code!

### Bug description

As we know, when implementing a setter in RenderObject, we usually early halt if the new value is equal to the old value (such as [this one](https://github.com/flutter/flutter/blob/7fba37848c9f3007795be2d67a3207067b7a0894/packages/flutter/lib/src/rendering/platform_view.dart#L115), indeed almost all fields in RenderObject child classes are examples). This is very necessary, because we are setting fields in `updateRenderObject` *unconditionally*. If we do not early return, we will execute the full logic like markNeedsPaint and so on *unconditionally* on *every* `updateRenderObject`. That will be performance penalty.

The current PR fixes one bug of such case. In more details, the `viewController` field setter lacks such early-return, and thus unconditionally calls markNeedsPaint. The setter is called from `updateRenderObject` as follows:

image

And _UiKitPlatformView is used here:

image

In other words, the controller is not changed in every frame. Instead, in common cases, it should be the same one for many frames. However, it triggers repaint for each and every rebuild.

### PR DESCRIPTION
**Pull request by fzyzcjy**
### How the bug is found

This bug is surely not found by human eyes reading each and every line of Flutter code :)

I proposed the idea that a linter can be created (https://github.com/dart-code-checker/dart-code-metrics/issues/997) to validate whether RenderObject field setters have correct early-return code. @incendial implemented it and ran it (https://github.com/dart-code-checker/dart-code-metrics/pull/1003).

Thus, thanks @incendial for implementing the linter and run it through flutter framework code!

### Bug description

As we know, when implementing a setter in RenderObject, we usually early halt if the new value is equal to the old value (such as [this one](https://github.com/flutter/flutter/blob/7fba37848c9f3007795be2d67a3207067b7a0894/packages/flutter/lib/src/rendering/platform_view.dart#L115), indeed almost all fields in RenderObject child classes are examples). This is very necessary, because we are setting fields in `updateRenderObject` *unconditionally*. If we do not early return, we will execute the full logic like markNeedsPaint and so on *unconditionally* on *every* `updateRenderObject`. That will be performance penalty.

The current PR fixes one bug of such case. In more details, the `viewController` field setter lacks such early-return, and thus unconditionally calls markNeedsPaint. The setter is called from `updateRenderObject` as follows:

image

And _UiKitPlatformView is used here:

image

In other words, the controller is not changed in every frame. Instead, in common cases, it should be the same one for many frames. However, it triggers repaint for each and every rebuild.

Close #111788 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Test passes here.

image

Without the fix, test fails:

image
image

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 1]
```diff
@@ -322,6 +322,9 @@ class RenderUiKitView extends RenderBox {
   UiKitViewController _viewController;
   set viewController(UiKitViewController viewController) {
     assert(viewController != null);
+    if (_viewController == viewController) {
+      return;
+    }
     final bool needsSemanticsUpdate = _viewController.id != viewController.id;
     _viewController = viewController;
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/platform_view.dart:329]: This is confusing code, because the local `viewController` is shadowing the getter `viewController`. Perhaps while you are here you could rename the parameter to something harmless like `value`?

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit

File: packages/flutter/lib/src/rendering/platform_view.dart (hunk 1 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/rendering/platform_view.dart]: Done (in latest commit). 

Btw this seems also commonly seen in flutter framework code (though I agree `value` is neater):

image

**Comment by fzyzcjy** [comment]
Oops is it because need 2 approvals?

**Review by cyanglaz — APPROVED** [review]
LGTM
