### PR TITLE
Avoid caching image load failures that are retriable

### LINKED ISSUE #47270: NetworkImage should evict itself from the cache if it fails to load due to a network error.
I find a bug in NetworkImage/image_cache.  if I load image when network is not available. now, my network is available,setState my widget, image will not work. look the source code,I find the bug in  framework. 
I find the code at image_cache.dart
` try {
      result = loader();
    } catch (error, stackTrace) {
      if (onError != null) {
        onError(error, stackTrace);
        return null;
      } else {
        rethrow;
      }
    }`
call loader() with sync but at _network_image_io.dart the loader() is async, If network is not available, loader() is failed, it can't not match your catch but put the error result to _pendingImages. when my network is available, I refresh my networkImage,it will return me error result from _pendingImages

企业微信截图_b69ed4d4-1d45-4f04-804d-029ead4bcf70

企业微信截图_ae161c5a-f7a0-41df-8cc7-55e6277153c0

### PR DESCRIPTION
**Pull request by dnfield**
## Description

If an image source fails to supply the image in a way that might change on a subsequent call, avoid having the cache hold on to a key for it.

For network images, the network may become available later, or the server will have the image later. Same for asset images, which might be network backed or be changed by hot reload/restart, and for file images, which may have file contents written at a later point in time.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/47270

## Tests

I added the following tests:

Added tests for asset images, updated existing tests for network and file images to check eviction on failure conditions.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

/cc @rogersxiao

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
Seems reasonable. I think we should still cache cases where the image is unlikely to ever succeed, such as a URI parser failure. I don't think that is a Flutter error though

File: packages/flutter/lib/src/painting/_network_image_io.dart [hunk 1]
```diff
@@ -8,6 +8,7 @@ import 'dart:typed_data';
 import 'dart:ui' as ui;
 
 import 'package:flutter/foundation.dart';
+import 'package:flutter/painting.dart';
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/_network_image_io.dart]: Can't import painting from painting.

**Review by goderbauer — APPROVED** [review]
LGTM once cirrus is happy.
