### PR TITLE
Elevation for Stepper(horizontally)

### LINKED ISSUE #62957: Stepper widget, not able to change elevation in horizontal mode.
## Steps to Reproduce

Create a flutter app.
Implement the stepper widget.
Set type to StepperType.horizontal

Result:
No option to to change elevation.

I made a PR where I made it possible to do this.

[#62856](https://github.com/flutter/flutter/pull/62856)

### PR DESCRIPTION
**Pull request by Abhishek01039**
Fixes https://github.com/flutter/flutter/issues/62957

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @HansMuller 
can you please review this PR?
Thasnks

**Comment by HansMuller** [comment]
I've been out for a while. Will take a look soon.

**Comment by Abhishek01039** [comment]
hello @HansMuller 
can you please take a look at this PR?
Thanks

File: packages/flutter/lib/src/material/stepper.dart [hunk 1]
```diff
@@ -280,6 +281,13 @@ class Stepper extends StatefulWidget {
   /// {@end-tool}
   final ControlsWidgetBuilder? controlsBuilder;
 
+  /// The z-coordinate at which to place this stepper relative to its parent.
+  ///
+  /// This determines the elevation of the stepper widget when built horizontally.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/stepper.dart:286]: This sentence can be removed.

File: packages/flutter/test/material/stepper_test.dart [hunk 2]
```diff
@@ -887,4 +887,62 @@ void main() {
...
+               ],
+             ),
+           ),
+         ),
+       ),
+     );
+
+     final Stepper stepper = tester.widget(find.byType(Stepper));
+
+     expect(stepper.elevation, elevation);
```
Comment (HansMuller) [inline packages/flutter/test/material/stepper_test.dart:918]: Please check the elevation of the stepper's Material descendant (here and below).

File: packages/flutter/test/material/stepper_test.dart [hunk 3]
```diff
@@ -887,4 +887,62 @@ void main() {
...
+         home: Material(
+           child: SizedBox(
+             width: 200,
+             height: 75,
+             child: Stepper(
+               type: StepperType.horizontal,
+               steps: const <Step>[
+                 Step(
+                   title: Text('Regular title'),
+                   subtitle: Text('Text subtitle'),
```
Comment (HansMuller) [inline packages/flutter/test/material/stepper_test.dart:934]: The subtitle can be left out.

File: packages/flutter/test/material/stepper_test.dart [hunk 4]
```diff
@@ -887,4 +887,62 @@ void main() {
...
+           child: SizedBox(
+             width: 200,
+             height: 75,
+             child: Stepper(
+               type: StepperType.horizontal,
+               elevation: elevation,
+               steps: const <Step>[
+                 Step(
+                   title: Text('Regular title'),
+                   subtitle: Text('Text subtitle'),
```
Comment (HansMuller) [inline packages/flutter/test/material/stepper_test.dart:906]: The subtitle can be left out

File: packages/flutter/test/material/stepper_test.dart (hunk 3 above)
Comment (Abhishek01039) [reply packages/flutter/test/material/stepper_test.dart:934]: Hello @HansMuller 
what do you mean by "left out"?

File: packages/flutter/test/material/stepper_test.dart (hunk 2 above)
Comment (Abhishek01039) [reply packages/flutter/test/material/stepper_test.dart:918]: you mean `find.descendant`?

Comment (craiglabenz) [reply packages/flutter/test/material/stepper_test.dart:918]: Yep, something like this:

```dart
final Material material = tester.firstWidget<Material>(
  find.descendant(
    of: find.byType(Stepper),
    matching: find.byType(Material),
  ),
);
expect(material.elevation, elevation);
```

File: packages/flutter/test/material/stepper_test.dart (hunk 3 above)
Comment (craiglabenz) [reply packages/flutter/test/material/stepper_test.dart:934]: I _think_ Hans meant that those widgets/steps can be dropped, as extra steps aren't strictly required to verify elevation.

**Comment by craiglabenz** [comment]
This is looking great, @Abhishek01039. If you add those `material.elevation` checks like I suggested in a comment and apply Hans' other docstring tweaks, this should be ready to go.

File: packages/flutter/test/material/stepper_test.dart (hunk 3 above)
Comment (HansMuller) [reply packages/flutter/test/material/stepper_test.dart:934]: Right, the idea is to make the test as simple as possible. In this case I was just suggesting that you remove ` subtitle: Text('Text subtitle')`, since it isn't essential for the test.

**Review by HansMuller — APPROVED** [review]
LGTM
