### PR TITLE
AppBar size can be lost after a Navigator.pop()

### LINKED ISSUE #4591: AppBar size can be lost after a Navigator.pop()
In the example below tapping anywhere pushes a route. Popping the route (back button) restores the list's scroll offset but not the app bar's size. Comments in the code explain what's going on.

This bug cropped up in #4579
```
import 'package:flutter/material.dart';

int scaffoldKeyIndex = 0;

class Home extends StatefulWidget {
  @override
  HomeState createState() => new HomeState();
}

class HomeState extends State<Home> {
  final _kAppBarHeight = 128.0;

  // Watch out! When the route is popped, HomeState (and this key) will
  // be recreated. The new key will cause the heuristic used by PageStorge
  // writeState() see  _computeStorageIdentifier() to essentially fail.
  // It will save the Scaffold's state under and identifier rooted by
  // the old value of _scaffoldKey. The problem can be overcome by making
  // _scaffoldKey a global.
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>(
    debugLabel: '_scaffoldKey: ${scaffoldKeyIndex++}'
  );

  @override
  Widget build(BuildContext context) {
    final double statusBarHeight = MediaQuery.of(context).padding.top;
    return new Scaffold(
      key: _scaffoldKey,
      appBarBehavior: AppBarBehavior.scroll,
      appBar: new AppBar(
        title: new Text('Click anywhere to push a route'),
        expandedHeight: _kAppBarHeight,
        flexibleSpace: new Container(
          decoration: new BoxDecoration(backgroundColor: Colors.purple[400])
        )
      ),
      body: new GestureDetector(
        onTap: () {
          Navigator.push(context, new MaterialPageRoute<Null>(
            builder: (BuildContext context) {
              return new Center(child: new Text('Pushed Route'));
            }
          ));
        },
        child: new Block(
          padding: new EdgeInsets.only(top: _kAppBarHeight + statusBarHeight),
          children: new List<Widget>.generate(50,
            (int index) => new ListItem(title: new Text('Item $index'))
          )
        )
      )
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new Home()));
}
```

### PR DESCRIPTION
**Pull request by HansMuller**
- Make it possible to provide an explicit PageStorage identifier.
- Scaffold uses an explicit identifier to record the flexible appbar's dimensions.

Fixes #4591

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -18,6 +18,7 @@ import 'snack_bar.dart';
 
 const double _kFloatingActionButtonMargin = 16.0; // TODO(hmuller): should be device dependent
 const Duration _kFloatingActionButtonSegue = const Duration(milliseconds: 200);
+const Object _kScaffoldStorageIdentifier = const Object();
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: We shouldn't use a `const Object` because those are deduplicated across your app.  Instead, we need something that's unique to this scaffold, so we should use `static final _kxxx = new Object()`.

**Comment by abarth** [comment]
LGTM but could use a test.

**Comment by abarth** [comment]
Doesn't have to be a test of the full gallery app.  Just a unit test that shows the problem with a parent widget that changes global keys.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart]: Yikes, thanks for that. I would have created another subtle bug.
