### PR TITLE
Only bundle assets and plugins from transitive closure of dependencies

### LINKED ISSUE #4473: Workspaces bundle all assets from all packages
# Environment

- Dart version: 3.6.0
- MacOS
- Are you using the Chinese community mirror or a corporate firewall? NO

# Problem
When using the new pub workspaces, I've found a bug where assets from all packages are bundled in the built app, rather than assets from just the packages that the Flutter app depends on.

This seems to occur when packages in the workspace depend on a common shared package - in this case one called `base`.

### Steps to reproduce

Given a Flutter monorepo that uses pub workspaces in this setup:

* base - a Flutter package with an asset
* included_package - a Flutter package with an asset that depends on base
* excluded_package - a Flutter package with an asset that depends on base
* app - a Flutter app that depends on ONLY included_package

Build the app via `flutter build web` in the `app` package.

### Expected results

A Flutter app is built containing only the assets from `included_package`.

### Actual results

A Flutter app is built containing the assets from all packages.

### Code sample

<details open><summary>Code sample</summary>
See this Github repo for a sample:  https://github.com/josh-burton/flutter_workspace_assets_bug

</details>

Also filed in Flutter repo: https://github.com/flutter/flutter/issues/160142

### LINKED ISSUE #4486: Don't force `uses-material-design: true` for root pubspec
# Environment

- Dart version: 3.6.0

# Problem

When you are using `uses-material-design: true` in any sub package with the new pub workspaces feature it complains that you also have to add this to the root pubspec.
A monorepo can have lots of packages that aren't bound to Flutter, it doesn't seem right that the root pubspec should need to be polluted with Flutter settings just because one of its sub packages uses it?

I'm sure there was a reason for this design decision, but is there no way around it?
And I'm also curious what the reason was?

## Expected behavior

Flutter settings should be contained to their own pubspecs.

## Actual behavior

You get the following error:
```
ERROR: package:example has `uses-material-design: true` set but the primary pubspec contains `uses-material-design: false`. If the application needs material icons, then `uses-material-design`  must be set to true.
```

### LINKED ISSUE #79261: package assets declared under dev_dependency shouldn't be included in release bundle
## Steps to Reproduce

See example project https://github.com/rh-id/example_dev_dependency_fi for the steps

**Expected results:** Flutter should ignore package assets declared under `dev_dependency` on release bundle / version

**Actual results:** Flutter include the package assets declared under `dev_dependency` on release bundle / version

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.2 at /home/rubyh/Flutter/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rubyh/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/rubyh/Android/Sdk
    • ANDROID_SDK_ROOT = /home/rubyh/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.
```
</details>

## Related Issues:
Do not create plugins from dev_dependencies #56591
Don't include dev_dependencies in native build scripts #45714
integration_test embedded in shipping iOS apps when added to pubspec #74274

### LINKED ISSUE #155242: pub workspace mixes plugins between projects
### Steps to reproduce

- Create 2 flutter projects in the same "pub workspace"
- Have these projects uses different Flutter plugins (e.g. project1 uses url_launcher and project2 uses webview_flutter).

### Expected results

The 2 projects should be separated. The plugins used by one project should not leak to the other projects (for binary size reasons?).

### Actual results

After you run `flutter run` (or `flutter test`), you notice that various files from project1 contains pointer to the plugins used by project2 (in files GeneratedPluginRegistrant.swift|java)

Example in `GeneratedPluginRegistrant.swift` in project2:
```
import url_launcher_macos
import webview_flutter_wkwebview

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  UrlLauncherPlugin.register(with: registry.registrar(forPlugin: "UrlLauncherPlugin"))
  FLTWebViewFlutterPlugin.register(with: registry.registrar(forPlugin: "FLTWebViewFlutterPlugin"))
}
```

### Code sample

git clone https://github.com/xvrh/pub_workspace_test

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel main, 3.26.0-1.0.pre.131, on macOS 14.5 23F79 darwin-arm64, locale en-BE)
```

</details>

### LINKED ISSUE #160142: Flutter bundles assets from all packages in a pub workspace
When using the new pub workspaces, I've found a bug where assets from all packages are bundled in the built app, rather than assets from just the packages that the Flutter app depends on.

This seems to occur when packages in the workspace depend on a common shared package - in this case one called `base`.

### Steps to reproduce

Given a Flutter monorepo that uses pub workspaces in this setup:

* base - a Flutter package with an asset
* included_package - a Flutter package with an asset that depends on base
* excluded_package - a Flutter package with an asset that depends on base
* app - a Flutter app that depends on ONLY included_package

Build the app via `flutter build web` in the `app` package.

### Expected results

A Flutter app is built containing only the assets from `included_package`.

### Actual results

A Flutter app is built containing the assets from all packages.

### Code sample

<details open><summary>Code sample</summary>
See this Github repo for a sample:  https://github.com/josh-burton/flutter_workspace_assets_bug

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Ark iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes https://github.com/dart-lang/pub/issues/4486
Fixes https://github.com/dart-lang/pub/issues/4473
Fixes https://github.com/flutter/flutter/issues/79261
Fixes https://github.com/flutter/flutter/issues/160142
Fixes https://github.com/flutter/flutter/issues/155242

Use the new `.dart_tool/package_graph.json` file to compute the dependency graph. Determining 

* which are transitive dependencies of the main app's direct and dev-dependencies,  (not other packages from the workspace)
* which of these are only in the transitive set of the direct dependencies

Bundles assets from dev_dependencies when running `flutter test`, but not otherwise.

### CODE REVIEW

**Comment by sigurdm** [comment]
I think all local tests are passing now. (perhaps we should refactor some tests, so package_config.json doesn't have to be created uniquely for so many tests....)

Not sure what happens in the customer tests, but I think it might be unrelated to this change.

**Review by bkonyi — COMMENTED** [review]
Initial quick review. Wil give this another pass later.

File: packages/flutter_tools/lib/src/asset.dart [hunk 1]
```diff
@@ -332,74 +333,85 @@ class ManifestAssetBundle implements AssetBundle {
       primary: true,
     );
 
-    // Add fonts, assets, and licenses from packages.
+    // Add fonts, assets, and licenses from packages in the project's
+    // dependencies.
+
+    // To Avoid bundling assets from dev_dependencies and other pub workspace
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/asset.dart:339]: Nit: s/Avoid/avoid/

File: packages/flutter_tools/lib/src/asset.dart [hunk 2]
```diff
@@ -332,74 +333,85 @@ class ManifestAssetBundle implements AssetBundle {
...
-        inputFiles.add(_fileSystem.file(packageManifestPath));
-        final FlutterManifest? packageFlutterManifest = FlutterManifest.createFromPath(
-          packageManifestPath,
-          logger: _logger,
-          fileSystem: _fileSystem,
+    for (final String packageName in transitiveDependencies.keys) {
+      final Package? package = packageConfig[packageName];
+      if (package == null) {
+        // This can happen with eg. `flutter run --no-pub`.
+        throwToolExit('Could not locate package:$packageName. Try running `flutter pub get`');
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/asset.dart:351]: Nit: Does this message need a period after it?

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 3]
```diff
@@ -2,126 +2,136 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
-import 'base/logger.dart';
-import 'convert.dart';
-import 'dart/pub.dart';
+import 'package:file/file.dart';
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:5]: I don't think we should be importing `package:file` here. Instead, we should be importing `base/file_system.dart`.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 4]
```diff
@@ -2,126 +2,136 @@
...
+Map<String, Dependency> computeTransitiveDependencies(
+  FlutterProject project,
+  PackageConfig packageConfig,
+  FileSystem fileSystem, {
+  bool followDevDependencies = false,
+}) {
+  final Map<String, Dependency> result = <String, Dependency>{};
+
+  final List<String> packageNamesToVisit = <String>[project.manifest.appName];
+  while (packageNamesToVisit.isNotEmpty) {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:36]: I think this loop can be refactored. It's quite large and has some very large conditional blocks that are hard to follow. Can the logic setting rootUri and pubspec be moved into a helper function that returns a record? Then the operations adding to the `dependencies` list can be handled separately.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 5]
```diff
@@ -2,126 +2,136 @@
...
-  // ```
-  final List<Map<String, Object?>> packages = asListOrFail(jsonResult['packages'], 'packages');
-
-  Map<String, Object?> packageWhere(
-    bool Function(Map<String, Object?>) test, {
-    required String reason,
-  }) {
-    return packages.firstWhere(test, orElse: () => fail(reason));
+    packageNamesToVisit.addAll(dependencies);
+    if (current == project.manifest.appName) {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:85]: This will only happen during the first iteration of the loop, right? If so, can we hoist it out of the loop?

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 6]
```diff
@@ -103,23 +90,28 @@ Future<List<Plugin>> findPlugins(
...
-  }
-  for (final Package package in packageConfig.packages) {
-    final Uri packageRoot = package.packageUriRoot.resolve('..');
+  final Map<String, Dependency> transitiveDependencies = computeTransitiveDependencies(
+    project,
+    packageConfig,
+    fs,
+  );
+  for (final String packageName in transitiveDependencies.keys) {
+    final Dependency dependency = transitiveDependencies[packageName]!;
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:99]: Ubernit: this variable declaration could be moved after the conditional below.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart (hunk 3 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:5]: Thanks!

File: packages/flutter_tools/lib/src/flutter_manifest.dart [hunk 7]
```diff
@@ -143,13 +150,20 @@ class FlutterManifest {
...
   Set<String> get dependencies {
     final YamlMap? dependencies = _descriptor['dependencies'] as YamlMap?;
     return dependencies != null ? <String>{...dependencies.keys.cast<String>()} : <String>{};
   }
 
+  /// Contains the names of the dev_dependencies.
+  /// These are the keys specified in the `dev_dependencies` map.
+  Set<String> get devDependencies {
+    final YamlMap? devDependencies = _descriptor['dev_dependencies'] as YamlMap?;
+    return devDependencies != null ? <String>{...devDependencies.keys.cast<String>()} : <String>{};
```
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/lib/src/flutter_manifest.dart:164]: Yes

File: packages/flutter_tools/lib/src/flutter_plugins.dart (hunk 6 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:99]: Done

**Comment by sigurdm** [comment]
Gentle ping on this one

**Comment by gabrielgarciagava** [comment]
@spydon I know you are one of the melos maintainers. I would suggest you to keep track of this pull request. I would say this is a blocker to release the workspaces support to melos.

**Comment by spydon** [comment]
> @spydon I know you are one of the melos maintainers. I would suggest you to keep track of this pull request. I would say this is a blocker to release the workspaces support to melos.

Thanks, I'm already subscribed to it. I've created one of the issues above. :)

**Review by andrewkolos — APPROVED** [review]
LGTM with nits

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 8]
```diff
@@ -2,126 +2,163 @@
...
-}) async {
-  final Map<String, Object?> jsonResult = await pub.deps(project);
+/// If a pubspec cannot be read, or is malformed, that pubspec is skipped. If
+/// nothing has changed since a succesful `pub get` that should never happen.
+/// In case of `flutter run --no-pub` this will at most ignore new dependencies.
+Map<String, Dependency> computeTransitiveDependencies(
+  FlutterProject project,
+  PackageConfig packageConfig,
+  FileSystem fileSystem, {
+  bool followDevDependencies = false,
```
[the remark this answers is not in the document]
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:31]: On yeah, I forgot about this comment. Let me look into this 😛

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 9]
```diff
@@ -2,126 +2,163 @@
...
+    final List<String> dependencies = <String>[];
+    final Object dependenciesMap = pubspec['dependencies'] as Object? ?? <String, String>{};
+    if (dependenciesMap is! Map) {
+      return null;
+    }
 
-    // Do not traverse packages that themselves are dev dependencies.
-    if (package['kind'] == 'dev') {
-      return;
+    for (final dynamic name in dependenciesMap.keys) {
```
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:128]: Done

File: packages/flutter_tools/test/general.shard/web/compile_web_test.dart [hunk 10]
```diff
@@ -2,6 +2,9 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+import 'dart:convert';
+
+import 'package:file/file.dart';
```
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/web/compile_web_test.dart:7]: Done

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 11]
```diff
@@ -31,394 +28,103 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
-          "name": "package_b",
-          "kind": "transitive",
-          "dependencies": [],
-          "directDependencies": []
-        }
-      ]
-    }''', project: project);
+  Future<void> validateComputeGraph(
+    List<Package> graph,
+    List<String> excusiveDevDependencies,
```
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:63]: Thanks! Done

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 12]
```diff
@@ -31,394 +28,103 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
-      fileSystem: fileSystem,
-      logger: logger,
-      processManager: processManager,
-      usage: TestUsage(),
-      platform: FakePlatform(),
-      botDetector: const FakeBotDetector(false),
-      stdio: FakeStdio(),
-    );
+  void writePackages(List<Package> graph) {
+    final Map<String, dynamic> packageConfigMap = <String, dynamic>{'configVersion': 2};
```
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:38]: Better! Done!

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:31]: I think we can just delete it.

Thanks for spotting!

**Comment by sigurdm** [comment]
Do you think you could help me out with the customer_testing tests?

I cannot understand how my change could cause errors like:
```
 00:11 +8: /b/s/w/ir/x/t/flutter_customer_testing.super_editor.UDMNRS/tests/super_text_layout/test/super_text_test.dart: SuperText RenderSuperTextLayout calculates line count for one line of text
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: <1>
|   Actual: <2>
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/x/t/flutter_customer_testing.super_editor.UDMNRS/tests/super_text_layout/test/super_text_test.dart:203:11)
| <asynchronous suspension>
| #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:193:15)
| <asynchronous suspension>
| #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1064:5)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
```

But also I don't want to land this with red tests I don't understand...

**Comment by andrewkolos** [comment]
> So in general when testing, you might want to use assets from your dev_dependencies, but not when building for deployment I had not really realized that.

Yeah, I was thinking the same. There are probably edge cases where including a font from a dev dependency would _unexpectedly_ cause a test to pass (i.e. the font was meant to be included from a regular dependency or the `assets` section in your pubspec); but I expect such a case would be extremely rare. That is to say, I think it is fine to continue to include assets from dev dependencies in tests—at least for now.

**Comment by bkonyi** [comment]
I think including assets from dev dependencies in tests is fine since I assume our main concern here is reducing bundle size in shipped applications.

File: packages/flutter_tools/lib/src/asset.dart [hunk 13]
```diff
@@ -332,74 +335,80 @@ class ManifestAssetBundle implements AssetBundle {
       primary: true,
     );
 
-    // Add fonts, assets, and licenses from packages.
+    // Add fonts, assets, and licenses from packages in the project's
+    // dependencies.
+
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/asset.dart:340]: Nit: extra whitespace

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 14]
```diff
@@ -2,126 +2,162 @@
...
+/// Returns `null` on failure (malformed pubspec etc.).
+_PackageDetails? _loadPackageDetails(
+  String packageName,
+  PackageConfig packageConfig,
+  FlutterProject project,
+  FileSystem fileSystem,
+) {
+  final Package? package = packageConfig[packageName];
+  if (package == null) {
+    return null;
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:106]: Is it worth adding verbose logging with the reason we failed to load package details where we return null?

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart (hunk 14 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:113]: Yeah - that is a good idea!

Added `printTrace` statements

**Comment by sigurdm** [comment]
Attached g3fix https://critique.corp.google.com/cl/721374511

**Comment by bkonyi** [comment]
Thanks for addressing the comments! LGTM!

**Comment by camsim99** [comment]
> Seems #161826 and #161343 are interferring with this.
> 
> @camsim99 do you know the desired semantics around plugins and assets from dev-dependencies? Should they be included in debug builds but not in release? Or should they be included for testing only (or not at all)?

My understanding is that we are working towards what I think https://github.com/flutter/flutter/issues/79261 proposes, i.e. assets from dev dependencies should be included in debug builds but not release. The changes I made are irrespective to testing I think. cc @matanlurey for input

**Review by matanlurey — CHANGES_REQUESTED** [review]
So the reason this failing is because the feature that @camsim99 and I implemented, which is, to omit plugins specified in `dev_dependencies` from release mode apps, looks like was broken as a result of the refactoring in this PR.

I can try cloning it locally and debug a bit tomorrow morning if you are still stuck, but as a starting point:
- <https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8723951633781029105/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/stdout> "plugins injectPlugins in release mode excludes dev dependencies from MacOS plugin registrant"
- <https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8723951633490693953/+/u/run_android_release_builds_exclude_dev_dependencies_test/stdout> "android_release_builds_exclude_dev_dependencies_test"

Not directly related: It's nice that this code was refactored to be synchronous and read the file system instead of shelling out to `pub deps`, but this was a large refactoring and in the future I should be included as a PR reviewer as someone who has to also maintain and understand these changes.

File: packages/flutter_tools/lib/src/asset.dart [hunk 15]
```diff
@@ -332,74 +335,80 @@ class ManifestAssetBundle implements AssetBundle {
...
-        final FlutterManifest? packageFlutterManifest = FlutterManifest.createFromPath(
-          packageManifestPath,
-          logger: _logger,
-          fileSystem: _fileSystem,
+    for (final String packageName in transitiveDependencies.keys) {
+      final Package? package = packageConfig[packageName];
+      if (package == null) {
+        // This can happen with eg. `flutter run --no-pub`.
+        throwToolExit('Could not locate package:$packageName. Try running `flutter pub get`.');
+      }
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/asset.dart:354]: Can you expand on this comment? From my understand it is because `computeTransitiveDependencies` (as implemented) might return packages listed in `{CURRENT_APP}/pubspec.yaml` that are not resolvable to a package (i.e. because no package config is present or it is out of date).

(If that's not true, let's expand on why).

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart
Comment (matanlurey) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:1]: This is a large change.

I am supportive - but I would have liked and prefer seeing this change made in isolation, i.e. _just_ changing `computeExclusiveDevDependencies` -> `computeTransitiveDependencies` in a PR, and fixing tests as needed, instead of making this refactor _and_ adding new features in a single PR.

For example, there will now be quite of a bit of unused code/technical debt; one example are the instances of [`FakePubWithPrimeDeps`](https://github.com/search?q=repo%3Aflutter%2Fflutter%20%22FakePubWithPrimedDeps%22&type=code) that were created and used the previous code branch that is now unused, and I'd want to see that cleaned up in the same PR that moves this from `pub deps` to walking the file system.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 16]
```diff
@@ -2,126 +2,184 @@
...
+  PackageConfig packageConfig,
+  FileSystem fileSystem,
+  Logger logger,
+) {
+  final Map<String, Dependency> result = <String, Dependency>{};
+  result[project.manifest.appName] = Dependency(
+    project.manifest.toYaml(),
+    project.manifest.dependencies.toList(),
+    project.directory.uri,
+    isExclusiveDevDependency: true,
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:39]: I'm confused here, why is the project itself listed as a dev-dependency of itself?

If it's because *everything* starts as a dev dependency and then is changed, please leave a comment.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 17]
```diff
@@ -2,126 +2,184 @@
...
+    if (details == null) {
+      continue;
+    }
+
+    packageNamesToVisit.addAll(details.dependencies);
+    result[current] = Dependency(
+      details.pubspec,
+      details.dependencies,
+      details.rootUri,
+      isExclusiveDevDependency: true,
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:67]: Ditto above.

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart [hunk 18]
```diff
@@ -2,126 +2,184 @@
...
+    required this.isExclusiveDevDependency,
+  });
 
-    // Remove any listed dependency from dev dependencies; it might have been
-    // a dev dependency for the app (root) package, but it is being used as a
-    // real dependency for a dependent on package, so we would not want to send
-    // a signal that the package can be ignored/removed.
-    devDependencies.removeAll(directDependencies);
+  /// The names of the direct, non-dev dependencies.
+  List<String> dependencies;
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/compute_dev_dependencies.dart:173]: Can this be final as well?

File: packages/flutter_tools/lib/src/flutter_manifest.dart [hunk 19]
```diff
@@ -51,10 +51,17 @@ class FlutterManifest {
...
+      return createFromYaml(loadYaml(manifest), logger);
+    } on FormatException catch (e) {
+      logger.printStatus('Malformed pubspec.yaml:', emphasis: true);
+      logger.printError(e.message);
+      return null;
+    }
   }
 
-  static FlutterManifest? _createFromYaml(Object? yamlDocument, Logger logger) {
+  /// Returns null on missing or invalid manifest.
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/flutter_manifest.dart:63]: Now that this is a public API: please expand on the comment and explain what exactly this does.

In particular, it would also be nice to explain what `yamlDocument` is expected to be as its a spooky `Object?` type (i.e. anything). Is that still necessary?

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 20]
```diff
@@ -103,23 +90,29 @@ Future<List<Plugin>> findPlugins(
...
-  } else {
-    devDependencies = await computeExclusiveDevDependencies(
-      pub,
-      logger: globals.logger,
-      project: project,
-    );
-  }
-  for (final Package package in packageConfig.packages) {
-    final Uri packageRoot = package.packageUriRoot.resolve('..');
+  final Map<String, Dependency> transitiveDependencies = computeTransitiveDependencies(
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:93]: This is a change in behavior: previously unless `determineDevDependencies` we would not do any work.

It might be fine to make this unconditional, but just pointing that out if that was not your intent (the flag that flips on `determineDevDependencies` is _not `true` yet).

File: packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart [hunk 21]
```diff
@@ -638,3 +623,33 @@ flutter:
...
   });
 }
+
+/// Write a `.dart_tool/package_config.json` file at [directory].
+///
+/// It will contain a package entry for [mainLibName] with `rootUri` at
+/// [directory].
+///
+/// [otherLibs] maps other package names to their `rootUri`.
+void writePackageConfigFile(
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:633]: Should this be moved into test/src and used through test instead of hard-coding a small variant of this across other tests?

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 22]
```diff
@@ -36,6 +36,7 @@ void main() {
     file.writeAsStringSync(
       json.encode(<String, dynamic>{
         'packages': <dynamic>[
+          <String, dynamic>{'name': 'my_app', 'rootUri': '../', 'packageUri': 'lib/'},
           ...packages.entries.map((MapEntry<String, String> entry) {
             return <String, dynamic>{
               'name': entry.key,
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/asset_bundle_test.dart:42]: This is a good example, there are so many copy-pastes of this function across the flutter_tools tests.

File: packages/flutter_tools/test/general.shard/asset_test.dart [hunk 23]
```diff
@@ -131,13 +131,187 @@ dependencies:
...
+description: A pubspec that defines a workspace root, but also a font.
+
+environment:
+  sdk: ^3.7.0-0
+
+workspace:
+  - main/
+
+flutter:
+  uses-material-design: true
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/asset_test.dart:280]: Is this true while the main app is false intentionally?

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 24]
```diff
@@ -30,393 +29,110 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
 
-    final Set<String> dependencies = await computeExclusiveDevDependencies(
-      pub(processes),
-      project: project,
-      logger: logger,
+    final Map<String, Dependency> dependencies = computeTransitiveDependencies(
+      project,
+      packageConfig,
+      fileSystem,
+      FakeLogger(),
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:75]: Why was the logger disabled? It's useful for understanding failures.

Instead, I'd:
- Keep BufferLogger
- Add assertions that the logger is free of errors (or warnings or both) in this function.

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 25]
```diff
@@ -30,393 +29,110 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
-ProcessManager _dartPubDepsReturns(String dartPubDepsOutput, {required FlutterProject project}) {
-  return FakeProcessManager.list(<FakeCommand>[
-    FakeCommand(
-      command: const <String>[_dartBin, 'pub', '--suppress-analytics', 'deps', '--json'],
-      stdout: dartPubDepsOutput,
-      workingDirectory: project.directory.path,
-    ),
-  ]);
+/// A fake [Logger] that throws the [Invocation] for any method call.
+class FakeLogger implements Logger {
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:135]: I don't think we should do this (see comment above), but in general this is a better pattern:

```
class FakeLogger extends Fake implements Logger {}
```

It has the behavior you are looking and just dispatches the noral NSM, not requiring an ignore or anything.

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 26]
```diff
@@ -30,393 +29,110 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
-  Pub pub(ProcessManager processManager) {
-    return Pub.test(
-      fileSystem: fileSystem,
-      logger: logger,
-      processManager: processManager,
-      platform: FakePlatform(),
-      botDetector: const FakeBotDetector(false),
-      stdio: FakeStdio(),
-    );
+  void writePackages(List<Package> graph) {
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:38]: Can you leave a short comment for the next person on what exactly this does?

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart [hunk 27]
```diff
@@ -30,393 +29,110 @@ const String _dartBin = 'bin/cache/dart-sdk/bin/dart';
...
-        },
-        {
-          "name": "package_b",
-          "kind": "transitive",
-          "dependencies": [],
-          "directDependencies": []
-        }
-      ]
-    }''', project: project);
+  Future<void> validateComputeGraph(
```
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:62]: Ditto, what is it validating? Can you explain in the comment, thanks!

File: packages/flutter_tools/test/general.shard/plugins_test.dart
Comment (matanlurey) [inline packages/flutter_tools/test/general.shard/plugins_test.dart:1]: In `injectPlugins in release mode` below, you'll find `fakePubWithTestPluginDevDependency = FakePubWithPrimedDeps`. That code branch will need to be updated to simulate a dev dependency using your new approach with reading the file system, it still assumes we're shelling out to `pub deps` which is why it's failing at your PR.

**Review by matanlurey — CHANGES_REQUESTED** [review]
Had a chance to do a longer review. Still needs more work, and I still think it makes sense to break this up into 2+ PRs.

File: packages/flutter_tools/test/commands.shard/hermetic/pub_test.dart
Comment (matanlurey) [inline packages/flutter_tools/test/commands.shard/hermetic/pub_test.dart:1]: If it is no longer used after this PR (or another PR if we split it up), can you also delete the implementation and tests for `Pub.deps` (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/dart/pub_deps_test.dart and usages).

Comment (matanlurey) [reply packages/flutter_tools/test/commands.shard/hermetic/pub_test.dart:1]: Similar, we should remove (3) in the error message here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/throwing_pub.dart

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart (hunk 16 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:39]: Yes exactly! - we build the graph with everything marked as exclusive dev-dependencies, and then re-traverse the non-dev-dependencies part to remove that marker.

I'll add a comment!

File: packages/flutter_tools/lib/src/compute_dev_dependencies.dart
Comment (sigurdm) [reply packages/flutter_tools/lib/src/compute_dev_dependencies.dart:1]: I agree - this grew in scope.

I'll try to split it up!

**Comment by sigurdm** [comment]
> in the future I should be included as a PR reviewer as someone who has to also maintain and understand these changes.

I'll keep you in mind going forward!

**Comment by matanlurey** [comment]
> Thanks for the review - I got through some of it.

Thank you! Let me know if you can use any help, I'm free early AM/late PM if needed.

**Comment by spydon** [comment]
@sigurdm when you split this PR up, can you link the other one here so that we can subscribe to that one too? :)

**Comment by sigurdm** [comment]
@spydon sure!

Will be off next week, so might take a little while :/

**Comment by spydon** [comment]
> @spydon sure!

Thanks!

> Will be off next week, so might take a little while :/

Have a good well deserved vacation (vinterferie I'm guessing)!

File: packages/flutter_tools/test/general.shard/asset_test.dart (hunk 23 above)
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/asset_test.dart:280]: I don't remember - probably a mistake - I'll turn it to true in the main app also.

File: packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart (hunk 27 above)
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart:66]: It should be renamed - I believe at one point I called `computeTransitiveDependencies` `computeTransitiveDependencies`... 
I'll add a comment also

File: packages/flutter_tools/test/general.shard/plugins_test.dart
Comment (sigurdm) [reply packages/flutter_tools/test/general.shard/plugins_test.dart:1]: Fixed - they are now added to the FakeFlutterManifest

**Comment by gabrielgarciagava** [comment]
Hello @sigurdm . What is the status of this PR? Just wondering since the last message was from 1 month ago

**Comment by sigurdm** [comment]
> Hello @sigurdm . What is the status of this PR? Just wondering since the last message was from 1 month ago

Still working on this - sorry it is taking some time

File: packages/flutter_tools/lib/src/dart/package_map.dart [hunk 28]
```diff
@@ -24,8 +24,8 @@ Future<PackageConfig> currentPackageConfig() async {
 // TODO(sigurdm): Only call this once per run - and read in from BuildInfo.
 File? findPackageConfigFile(Directory dir) {
   final FileSystem fileSystem = dir.fileSystem;
+  Directory candidateDir = fileSystem.directory(fileSystem.path.normalize(dir.absolute.path));
```
Comment (sigurdm) [inline packages/flutter_tools/lib/src/dart/package_map.dart:27]: This is extracted in https://github.com/flutter/flutter/pull/165392

**Comment by sigurdm** [comment]
@matanlurey I am fighting the google builder - I have attached a [g3fix](https://critique.corp.google.com/cl/721374511), but it seems to have become out of sync, but I don't seem to be able to delete it. Do you know of a button to push?

**Comment by sigurdm** [comment]
@matanlurey are you ok with landing this in this state?
I'm not sure it is really meaningful to separate the last changes.

**Review by matanlurey — APPROVED** [review]
LGTM, thanks for pushing on this.

**Comment by gabrielgarciagava** [comment]
@sigurdm I suppose this PR could not land on the current flutter stable release, right?
Do you have any idea if this is going to be cherry-picked to the current stable version or will we need to wait for the next stable release? :')

**Comment by davidnwaneri** [comment]
When will it be possible to have this fix on stable

**Comment by spydon** [comment]
> When will it be possible to have this fix on stable

Since it's in beta now I would guess that it will land in stable around the end of August.
