### PR TITLE
`SelectableText.rich`: Fix `TextSpan.style` not merged into default text style

### LINKED ISSUE #94042: SelectableText.rich doesn't correctly apply the `TextStyle` in the `TextSpan`
## Steps to Reproduce
1. Execute `flutter run` on the code sample. I have successfully reproduced this on DartPad and an Android 11 device.
2. Notice that the space between the lines of the `SelectableText.rich` widget is very big, despite line spacing not being overridden.
3. Replace `SelectableText.rich` with the regular `RichText` widget and notice the line spacing returns to normal.

**Expected results:**
Line spacing should not be so large on the `SelectableText.rich` widget.

**Actual results:**
Line spacing is very large on the `SelectableText.rich` widget.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        color: Colors.white,
        child: const SelectableText.rich(
          TextSpan(
            style: TextStyle(
              fontSize: 12.0,
              decoration: TextDecoration.none,
              color: Colors.black,
            ),
            children: [
              TextSpan(
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim leo et ipsum hendrerit tincidunt. Vestibulum mattis, nulla pharetra sagittis porttitor, massa dui faucibus ipsum, a gravida odio ex vitae sapien. Vestibulum tincidunt justo at tortor lacinia pulvinar. Nam venenatis turpis nec velit ullamcorper, eget imperdiet risus tempor. Sed pulvinar scelerisque odio, sed rhoncus massa rutrum at. Nullam eleifend odio vitae velit rutrum molestie. Proin vel nulla et arcu volutpat facilisis. Nam id porta turpis. Aliquam vitae condimentum eros. Morbi venenatis consectetur sagittis.',
              ),
            ],
          ),
          textAlign: TextAlign.center,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +47 ms] executing: [C:\Users\adam\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\Users\adam\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +45 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +6 ms] executing: [C:\Users\adam\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\adam\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [C:\Users\adam\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +57 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +39 ms] List of devices attached
           emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[   +6 ms] C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +37 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Skipping pub get: version match.
[  +70 ms] Generating
C:\Users\adam\OneDrive\Documents\workplace\example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistran
t.java
[  +36 ms] ro.hardware = ranchu
[   +8 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +18 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +4 ms] C:\Users\adam\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\adam\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\adam\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\adam\AppData\Local\Temp\flutter_tools.d5c11440\flutter_tool.3e771caa\app.dill --packages
C:\Users\adam\OneDrive\Documents\workplace\example\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[   +6 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +17 ms] Exit code 0 from: C:\Users\adam\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.example" (Raw: "com.example.example")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="example" (Raw: "example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.example.MainActivity" (Raw:
                   "com.example.example.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[  +12 ms] <- compile package:example/main.dart
[  +64 ms] --------- beginning of main
           11-22 15:58:00.667 W/Binder:207_3(  207): type=1400 audit(0.0:10626): avc: denied { read } for
           name="wakeup35" dev="sysfs" ino=19223 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir
           permissive=0
[  +13 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +22 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +22 ms] Building APK
[  +12 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from C:\Users\adam\OneDrive\Documents\workplace\example\android\gradlew.bat.
[   +7 ms] executing: [C:\Users\adam\OneDrive\Documents\workplace\example\android/]
C:\Users\adam\OneDrive\Documents\workplace\example\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\adam\OneDrive\Documents\workplace\example\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3308 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +55 ms] executing: [C:\Users\adam\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] [        ] executing: [C:\Users\adam\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] [  +50 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] [        ] 2.5.3
[        ] [   +5 ms] executing: [C:\Users\adam\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\Users\adam\flutter/] git ls-remote --get-url origin
[        ] [  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +41 ms] executing: [C:\Users\adam\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +72 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +24 ms] Initializing file store
[        ] [  +10 ms] Done initializing file store
[        ] [  +29 ms] Skipping target: gen_localizations
[        ] [   +8 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +367 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents: C:\Users\adam\OneDrive\Documents\workplace\example\lib\main.dart}
[        ] [   +7 ms] C:\Users\adam\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\adam\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\adam\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
--no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\adam\OneDrive\Documents\workplace\example\.dart_tool\package_config.json --output-dill
C:\Users\adam\OneDrive\Documents\workplace\example\.dart_tool\flutter_build\9898e075f92adf0a7b6f92e93388aaee\app.dill
--depfile
C:\Users\adam\OneDrive\Documents\workplace\example\.dart_tool\flutter_build\9898e075f92adf0a7b6f92e93388aaee\kernel_snap
shot.d package:example/main.dart
[+5577 ms] [+6206 ms] kernel_snapshot: Complete
[ +294 ms] [ +335 ms] debug_android_application: Starting due to {InvalidatedReasonKind.inputChanged: The following
inputs have updated contents:
C:\Users\adam\OneDrive\Documents\workplace\example\.dart_tool\flutter_build\9898e075f92adf0a7b6f92e93388aaee\app.dill,C:
\Users\adam\OneDrive\Documents\workplace\example\build\app\intermediates\flutter\debug\flutter_assets\kernel_blob.bin}
[ +108 ms] [ +102 ms] debug_android_application: Complete
[ +201 ms] [ +169 ms] Persisting file store
[        ] [   +5 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 7,371ms.
[  +92 ms] [  +45 ms] ensureAnalyticsSent: 42ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[  +92 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[ +107 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +199 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +90 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[ +105 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[ +293 ms] > Task :app:compressDebugAssets
[ +402 ms] > Task :app:packageDebug
[ +145 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 10s
[        ] 32 actionable tasks: 7 executed, 25 up-to-date
[ +523 ms] Running Gradle task 'assembleDebug'... (completed in 11.6s)
[  +32 ms] calculateSha: LocalDirectory:
'C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk'/app.apk
[ +388 ms] ✓  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +2 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +22 ms] Exit code 0 from: C:\Users\adam\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.example" (Raw: "com.example.example")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="example" (Raw: "example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.example.MainActivity" (Raw:
                   "com.example.example.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am
force-stop com.example.example
[  +73 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list
packages com.example.example
[  +39 ms] package:com.example.example
[   +1 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat
/data/local/tmp/sky.com.example.example.sha1
[  +29 ms] 32c5cce425fe0502afe5ea83c24573e5eec12a29
[        ] Installing APK.
[        ] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r
C:\Users\adam\OneDrive\Documents\workplace\example\build\app\outputs\flutter-apk\app.apk
[ +560 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 560ms)
[        ] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell echo -n
9f4efc2cf5570cd5d1d1530cae4e6804a9ebb84c > /data/local/tmp/sky.com.example.example.sha1
[  +37 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[  +97 ms] --------- beginning of main
           11-22 15:58:19.069 D/CarrierConfigLoader(  883): mHandler: 9 phoneId: 0
[   +9 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.example.example/com.example.example.MainActivity
[  +68 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.example/.MainActivity (has
extras) }
[        ] Waiting for observatory port to be available...
[ +657 ms] Observatory URL on device: http://127.0.0.1:37223/MVwuqbz5gIk=/
[        ] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0
tcp:37223
[  +13 ms] W/FlutterActivityAndFragmentDelegate(18915): A splash screen was provided to Flutter, but this is deprecated.
See flutter.dev/go/android-splash-migration for migration steps.
[  +14 ms] 58146
[        ] Forwarded host port 58146 to device port 37223 for Observatory
[   +3 ms] Caching compiled dill
[  +22 ms] Connecting to service protocol: http://127.0.0.1:58146/MVwuqbz5gIk=/
[ +370 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:58146/MVwuqbz5gIk=/.
[ +122 ms] DDS is listening at http://127.0.0.1:58149/EOWAtD8l82E=/.
[  +43 ms] Successfully connected to service protocol: http://127.0.0.1:58146/MVwuqbz5gIk=/
[  +39 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.example/code_cache/exampleKMIFAD/example/)
[   +1 ms] Updating assets
[  +49 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:example/main.dart 59d56fb5-c8cc-46e9-b080-363587735808
[        ] <- 59d56fb5-c8cc-46e9-b080-363587735808
[  +64 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 68ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xed987c20.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:58149/EOWAtD8l82E=/
[ +238 ms] DevTools activation throttled until 2021-11-23 03:25:11.799482.
[ +404 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
                    http://127.0.0.1:9103?uri=http://127.0.0.1:58149/EOWAtD8l82E=/
[+36005 ms] Application finished.
```

```
Analyzing example...
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.318], locale en-GB)
    • Flutter version 2.5.3 at C:\Users\adam\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\adam\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\adam\.jdks\adopt-openjdk-11.0.12\bin\java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\adam\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\adam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.318]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/94042

| Before | After |
| --------------- | --------------- |
|  |  |

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const TextStyle textStyle =
        TextStyle(fontSize: 12.0, color: Color(0xff00ff00));

    return const MaterialApp(
      home: SelectableText.rich(
        TextSpan(
          text: 'Abcd',
          style: textStyle,
        ),
      ),
    );
  }
}

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 1]
```diff
@@ -5070,4 +5070,24 @@ void main() {
...
+          TextSpan(
+            text: 'Abcd',
+            style: textStyle,
+          ),
+        ),
+      ),
+    );
+
+    final EditableText editableText = tester.widget(find.byType(EditableText));
+    expect(editableText.style.fontSize, 12.0);
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:5091]: Maybe instead of `12.0` use `textStyle.fontSize` for clarity?

**Review by justinmc — APPROVED** [review]
LGTM, thanks! :+1:

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/test/widgets/selectable_text_test.dart]: Fixed.

**Comment by TahaTesser** [comment]
>  Google testing failed. Please contact a Google developer to investigate.

Trying again.

**Comment by TahaTesser** [comment]
cc: @HansMuller 

Another PR with failed Google testing, similar to the `MaterialStateProperty.lerp` PR. 
Rebased this couple of times, I'm unable to find the cause.

**Comment by justinmc** [comment]
It looks like this broke a few Scubas by changing line height or something like that.  Some text has moved vertically by <20px.  It looks acceptable to me, so I'm setting the Google tests to passing and merging this.

Sorry for the delay @TahaTesser!
