### PR TITLE
Fix `TableRow` with no children throws unnamed assertion

### LINKED ISSUE #119541: Empty List for TableRow throws unnamed assertion
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
A helpful error message, that tells me there are no children in the list.

**Actual results:** 
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/rendering/table.dart': Failed assertion: line 632 pos 16: '_rows == 0': is not
true.

```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
runApp(MaterialApp(
  home: Table(children: [
    TableRow(children: []),
  ]),
));
}
```

</details>

<details>
  <summary>Logs</summary>

```
[+1661 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] The following assertion was thrown building Builder:
[        ] Assertion failed: file:///home/user/.flutter/packages/flutter/lib/src/rendering/table.dart:632:16
[        ] _rows == 0
[        ] is not true
[        ] The relevant error-causing widget was:
[        ]   MaterialApp MaterialApp:file:///tmp/test/lib/main.dart:4:8
[        ] When the exception was thrown, this was the stack:
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
[        ] packages/flutter/src/rendering/table.dart 632:25                              setFlatChildren
[        ] packages/flutter/src/widgets/table.dart 391:18                                [_updateRenderObjectChildren]
[        ] packages/flutter/src/widgets/table.dart 312:5                                 mount
[        ] packages/flutter/src/widgets/framework.dart 3863:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3592:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 6300:14                           mount
[        ] packages/flutter/src/widgets/framework.dart 3863:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3592:18                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4904:16                           performRebuild

...
~1000 Lines of identical StackTrace
...

[        ] packages/flutter/src/widgets/framework.dart 4604:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4859:5                            [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 5041:11                           [_firstBuild]
[        ] packages/flutter/src/widgets/framework.dart 4853:5                            mount
[        ] packages/flutter/src/widgets/framework.dart 3863:15                           inflateWidget
[        ] packages/flutter/src/widgets/framework.dart 3592:18                           updateChild
[        ] packages/flutter/src/widgets/binding.dart 1195:16                             [_rebuild]
[        ] packages/flutter/src/widgets/binding.dart 1164:5                              mount
[        ] packages/flutter/src/widgets/binding.dart 1111:16                             <fn>
[        ] packages/flutter/src/widgets/framework.dart 2605:19                           buildScope
[        ] packages/flutter/src/widgets/binding.dart 1110:12                             attachToRenderTree
[        ] packages/flutter/src/widgets/binding.dart 944:24                              attachRootWidget
[        ] packages/flutter/src/widgets/binding.dart 925:7                               <fn>
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/119541

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/table.dart [hunk 1]
```diff
@@ -147,6 +147,17 @@ class Table extends RenderObjectWidget {
          }
          return true;
        }()),
+       assert(() {
+         if (children.isNotEmpty) {
+           if (children.any((TableRow row) => row.children.isEmpty)) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/table.dart:152]: These two `if`s could be combined to one, I think.

**Review by goderbauer — APPROVED** [review]
LGTM
