### PR TITLE
Fix leak of CurvedAnimations in long-lived ImplicitlyAnimatedWidgets.

### LINKED ISSUE #84730: Long lived ImpicitlyAnimatedWidgets leak CurvedAnimations
Whenever an ImplicitlyAnimatedWidget's State's didUpdateWidget is called, it creates a new CurvedAnimation which in the process add's itself to the State's AnimationController as a AnimationStatusListener.

CurvedAnimation has no way to remove it's listener from the AnimationController until that controller is disposed, so if it never disposes (because the widget and state is long lived) it leaks those CurvedAnimations.

### PR DESCRIPTION
**Pull request by apwilson**
When an ImplicitlyAnimatedWidget gets rebuilt while reusing an existing ImplicitlyAnimatedWidgetState, a new CurvedAnimation is created and added as a status listener to that State's AnimationController.

If the ImplicitlyAnimatedWidgetState is long lived this leads to a leak of CurvedAnimations.

This change adds a dispose to CurvedAnimation which cleans up its status listener from its parent and ImplicitlyAnimatedWidgetState uses this dispose when creating a new CurvedAnimation.

fixes https://github.com/flutter/flutter/issues/84730

### CODE REVIEW

File: packages/flutter/lib/src/widgets/implicit_animations.dart [hunk 1]
```diff
@@ -380,8 +380,10 @@ abstract class ImplicitlyAnimatedWidgetState<T extends ImplicitlyAnimatedWidget>
   @override
   void didUpdateWidget(T oldWidget) {
     super.didUpdateWidget(oldWidget);
-    if (widget.curve != oldWidget.curve)
+    if (widget.curve != oldWidget.curve) {
+      (_animation as CurvedAnimation).dispose();
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/implicit_animations.dart:384]: We should probably add this to `dispose` below too, right?

File: packages/flutter/test/animation/animations_test.dart [hunk 2]
```diff
@@ -302,6 +303,41 @@ FlutterError
...
+      duration: const Duration(milliseconds: 100),
+      reverseDuration: const Duration(milliseconds: 100),
+      vsync: const TestVSync(),
+    );
+    final CurvedAnimation curved = CurvedAnimation(parent: controller, curve: forwardCurve, reverseCurve: reverseCurve);
+
+    expect(forwardCurve.transform(0.5), 1.0);
+    expect(reverseCurve.transform(0.5), 0.0);
+
+    controller.forward(from:0.5);
```
Comment (dnfield) [inline packages/flutter/test/animation/animations_test.dart:320]:
```suggestion
    controller.forward(from: 0.5);
```

File: packages/flutter/test/animation/animations_test.dart [hunk 3]
```diff
@@ -302,6 +303,41 @@ FlutterError
...
+    expect(controller.status, equals(AnimationStatus.forward));
+    expect(curved.value, equals(1.0));
+
+    controller.value = 1.0;
+    expect(controller.status, equals(AnimationStatus.completed));
+
+    controller.reverse(from:0.5);
```
Comment (dnfield) [inline packages/flutter/test/animation/animations_test.dart:327]:
```suggestion
    controller.reverse(from: 0.5);
```

File: packages/flutter/test/animation/animations_test.dart [hunk 4]
```diff
@@ -352,7 +388,7 @@ FlutterError
     tick(const Duration(milliseconds: 160));
     expect(reversed.value, moreOrLessEquals(1.0));
   });
-
+
```
Comment (dnfield) [inline packages/flutter/test/animation/animations_test.dart:391]:
```suggestion

```

File: packages/flutter/lib/src/widgets/implicit_animations.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:384]: Also - can you add a test for the widget as well?

Comment (apwilson) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:384]: I don't think you need to dispose in dispose as it already disposes the controller which cleans up the status listener.

Comment (apwilson) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:384]: I was thinking about it but I have no idea how I can verify that we're calling dispose here.  Do you have a suggestion?

Comment (dnfield) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:384]: Fish out the `animation` from the state before updating the widget, update the widget, and then verify that changing the status on the controller doesn't change the animation.

Comment (dnfield) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:384]: Maybe just adding a comment in dispose about how disposing the parent takes care of the child would be good then to avoid confusion for future us :)

File: packages/flutter/test/widgets/implicit_animations_test.dart [hunk 5]
```diff
@@ -350,6 +350,63 @@ void main() {
     await tester.pump(additionalDelay);
     expect(mockOnEndFunction.called, 1);
   });
+
+  testWidgets('Ensure CurvedAnimations are disposed on widget change',
+      (WidgetTester tester) async {
+    final GlobalKey<ImplicitlyAnimatedWidgetState<AnimatedOpacity>> key =
+        GlobalKey<ImplicitlyAnimatedWidgetState<AnimatedOpacity>>();
+    final ValueNotifier<Curve> curve =
+        ValueNotifier<Curve>(const Interval(0.0, 0.5));
```
Comment (dnfield) [inline packages/flutter/test/widgets/implicit_animations_test.dart:359]: Flutter style says these should be on single lines.

File: packages/flutter/test/widgets/implicit_animations_test.dart [hunk 6]
```diff
@@ -350,6 +350,63 @@ void main() {
...
+            key: key,
+            opacity: 1.0,
+            duration: const Duration(seconds: 1),
+            curve: c,
+            child: Container(color: Colors.green)),
+      ),
+    ));
+
+    final ImplicitlyAnimatedWidgetState<AnimatedOpacity>? firstState =
+        key.currentState;
```
Comment (dnfield) [inline packages/flutter/test/widgets/implicit_animations_test.dart:373]: Ditto

File: packages/flutter/test/widgets/implicit_animations_test.dart [hunk 7]
```diff
@@ -350,6 +350,63 @@ void main() {
...
+    final CurvedAnimation firstCurvedAnimation =
+        firstAnimation as CurvedAnimation;
+
+    expect(firstCurvedAnimation.isDisposed, isFalse);
+
+    curve.value = const Interval(0.0, 0.6);
+    await tester.pumpAndSettle();
+
+    final ImplicitlyAnimatedWidgetState<AnimatedOpacity>? secondState =
+        key.currentState;
```
Comment (dnfield) [inline packages/flutter/test/widgets/implicit_animations_test.dart:387]: Ditto

File: packages/flutter/test/widgets/implicit_animations_test.dart [hunk 8]
```diff
@@ -350,6 +350,63 @@ void main() {
...
+    final Animation<double>? secondAnimation = secondState?.animation;
+    if (secondAnimation == null)
+      fail('animation was null!');
+
+    final CurvedAnimation secondCurvedAnimation =
+        secondAnimation as CurvedAnimation;
```
Comment (dnfield) [inline packages/flutter/test/widgets/implicit_animations_test.dart:393]: Ditto

**Review by dnfield — APPROVED** [review]
LGTM with style nits
