### PR TITLE
Fix the issue with pinned headers in nested SliverMainAxisGroup.

### LINKED ISSUE #178973: SliverMainAxisGroup + pinned headers overlap (no push-off) in 3.38.x, works in 3.35.x
### Summary
  In Flutter 3.38.x, a `SliverMainAxisGroup` containing nested `SliverMainAxisGroup`s with `SliverPersistentHeader(pinned: true)` stops pushing the previous header out of view. The new header “dives under” the
  previous one instead of replacing it. The same layout works correctly on 3.35.x and earlier.

  ### Environment
  - Flutter: 3.38.3 (stable) — bug reproduces
  - Flutter: 3.35.7 (stable) — works as expected
  - Dart: 3.10.1 (3.38), 3.8.x (3.35)
  - Platform tested: iOS Simulator (iPhone 16 Pro)

  ### Minimal reproduction
  DartPad repro: [[paste the DartPad link here]](https://dartpad.dev/bc460238c9a5abd2802f9d3a1daaf4fe)

  Key structure:
  - `CustomScrollView`
  - outer `SliverMainAxisGroup`
    - `SliverPersistentHeader(pinned: true)` for Year A
    - inner `SliverMainAxisGroup`
      - `SliverPersistentHeader(pinned: true)` for Month a1
      - `SliverList`
      - `SliverPersistentHeader(pinned: true)` for Month a2
      - `SliverList`
  - Next year section follows.

  ### Steps to reproduce
  1. Run the DartPad sample on Flutter 3.38.3 (stable).
  2. Scroll so Month A1 content scrolls away and Month A2 header should replace it.
  3. Observe that the incoming header overlaps/slots under the previous header instead of pushing it off.
  4. Repeat on Flutter 3.35.7 — headers push off correctly.

  ### Videos
  - 3.38.3 (bug): 

https://github.com/user-attachments/assets/fba9c507-5447-45c3-9a39-b7ad88703901

  - 3.35.7 (correct): 

https://github.com/user-attachments/assets/c7097610-2d78-4b62-aa49-3e9d865b4485

  ### Additional notes
  - Tried replacing `SliverPersistentHeader` with `PinnedHeaderSliver`; the overlap still occurs on 3.38.x.
  - ScrollOffsetCorrection changes and PinnedHeaderSliver fixes in 3.38 were suspected, since the regression is only between 3.35.x → 3.38.x.

### Expected behavior
  When a new pinned header enters, it should push the previous pinned header off-screen (standard sticky behavior).

### Actual behavior
  On 3.38.x, the new header overlaps/overdraws the previous header; it does not push it away.

### Code sample

https://dartpad.dev/bc460238c9a5abd2802f9d3a1daaf4fe

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes: #178973

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 1]
```diff
@@ -1518,6 +1518,55 @@ void main() {
     expect(semantics.nodesWith(label: 'b'), hasLength(1));
     semantics.dispose();
   });
+
+  testWidgets(
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart:1522]: Can you add a test for the reverse case as well?

**Review by Piinks — COMMENTED** [review]
Thank you for the fast follow up on this regression! 💯 🙏

**Review by Piinks — APPROVED** [review]
LGTM thank you!

**Comment by Piinks** [comment]
Gonna rebase, the autosubmit bot will likely request it.
