### PR TITLE
Fix a rotation gesture recognize bug

### LINKED ISSUE #78941: ScaleUpdateDetails first rotation not detected
flutter version:

```
Flutter 2.1.0-10.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc9b78fc5c (4 weeks ago) • 2021-02-25 13:26:03 -0800
Engine • revision a252ec09b7
Tools • Dart 2.13.0 (build 2.13.0-77.0.dev)

```
## Steps to Reproduce

run this test:

```
testWidgets('rotate test', (tester) async {
  var widget = GestureDetector(
    onScaleUpdate: (d) {
      final degrees = (180 * d.rotation / pi).toStringAsFixed(2);
      tester.printToConsole('rotation: $degrees degrees');
    },
    child: Container(color: Colors.black),
  );
  await tester.pumpWidget(widget);
  var rect = Rect.fromLTRB(0, 0, 200, 200);
  var finger1 = await tester.startGesture(rect.topLeft);

  tester.printToConsole('finger down ${rect.centerRight}');
  var finger2 = await tester.startGesture(rect.centerRight);

  tester.printToConsole('finger move to ${rect.bottomRight}');
  await finger2.moveTo(rect.bottomRight);
  tester.printToConsole('finger move to ${rect.bottomCenter}');
  await finger2.moveTo(rect.bottomCenter);
});
```

**Expected results:** 
after the first `finger2.moveTo` method call, reported `d.rotation` should be != 0

**Actual results:** 
`d.rotation` == 0

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #78941

### CODE REVIEW

File: packages/flutter/lib/src/gestures/scale.dart [hunk 1]
```diff
@@ -441,7 +441,7 @@ class ScaleGestureRecognizer extends OneSequenceGestureRecognizer {
         pointerEndId: _pointerQueue[1],
         pointerEndLocation: _pointerLocations[_pointerQueue[1]]!,
       );
-      _currentLine = null;
+      _currentLine = _initialLine;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/gestures/scale.dart:444]: We need to initialize `_initialLine` and `_currentLine` at the same time when a new rotation coming, otherwise, they will be set to null in the next `_reconfigure` processing, which will cause this bug to occur.

**Comment by pskink** [comment]
thanks a lot @xu-baolin, this one line works, but i have one cosmetic issue: shouldnt be `details.rotation` in range `[0 .. 2π)` ?

**Comment by xu-baolin** [comment]
> thanks a lot @xu-baolin, this one line works, but i have one cosmetic issue: shouldnt be `details.rotation` in range `[0 .. 2π)` ?

The value range of `rotation` should be another topic, which has nothing to do with this PR. Could you file a new issue to discuss it?

**Comment by pskink** [comment]
are you sure that `_currentLine = _initialLine` did not change anything? i am asking since now i see the following: the `case 1` below prints `90, 180, 270, 0, 90` but `case 2` prints `-270, -180, -90, 0, -270`

```
  testWidgets('rotate test', (tester) async {
    final rotations = [];
    final widget = GestureDetector(
      onScaleUpdate: (d) {
        final degrees = (180 * d.rotation / pi).toStringAsFixed(2);
        rotations.add(degrees);
      },
    );
    await tester.pumpWidget(widget);

    final r = Rect.fromLTRB(0, 0, 100, 100);
    await tester.startGesture(r.center);

    // case 1 works ok
    final finger2 = await tester.startGesture(r.bottomCenter);
    final offsets = [r.centerLeft, r.topCenter, r.centerRight, r.bottomCenter, r.centerLeft];

    // case 2 works weird
    // final finger2 = await tester.startGesture(r.centerRight);
    // final offsets = [r.bottomCenter, r.centerLeft, r.topCenter, r.centerRight, r.bottomCenter];

    await Future.forEach<Offset>(offsets, (o) => finger2.moveTo(o));
    print(rotations);
  });

```

**Comment by xu-baolin** [comment]
You mean Different results with or without this change ?

**Comment by xu-baolin** [comment]
This change do not change the radian algorithm, so I suggest new a topic to discuss that:)

**Comment by pskink** [comment]
without your latest fix `case 2` prints `0.00, 90.00, 180.00, 270.00, 0.00` - so basically it does not detect the first rotation but subsequent rotations are reported > 0

**Comment by xu-baolin** [comment]
What's the result of case 1 without my patch?

**Comment by pskink** [comment]
hmmm, its even more strange:

`[0.00, 90.00, 180.00, -90.00, 0.00]`

**Comment by xu-baolin** [comment]
This really has nothing to do with this patch.

**Comment by xu-baolin** [comment]
This probably another bug and I will take a look at this tomorrow. Also cc @dkwingsmt

**Comment by pskink** [comment]
it looks as if `if (rotation < 0) rotation += 2 * pi` would fix it

**Comment by xu-baolin** [comment]
@pskink, hi, I saw that the original author intended to test the arc as a negative value, but I don't understand why.
https://github.com/flutter/flutter/blob/58cda591e8a654960981317ef58f15c5baead6bd/packages/flutter/test/gestures/scale_test.dart#L546

File: packages/flutter/test/gestures/scale_test.dart [hunk 2]
```diff
@@ -572,6 +572,34 @@ void main() {
...
+    double? updatedRotation;
+    scale.onUpdate = (ScaleUpdateDetails details) {
+      updatedRotation = details.rotation;
+    };
+
+    final TestPointer pointer1 = TestPointer(1);
+    final PointerDownEvent down = pointer1.down(Offset.zero);
+    scale.addPointer(down);
+    tester.closeArena(1);
+    tester.route(down);
```
Comment (goderbauer) [inline packages/flutter/test/gestures/scale_test.dart:588]: Why this route? Isn't a `tester.async.flushMicrotasks();` enough here?

File: packages/flutter/test/gestures/scale_test.dart [hunk 3]
```diff
@@ -572,6 +572,34 @@ void main() {
...
+
+    final TestPointer pointer2 = TestPointer(2);
+    final PointerDownEvent down2 = pointer2.down(const Offset(10.0, 10.0));
+    scale.addPointer(down2);
+    tester.closeArena(2);
+    tester.route(down2);
```
Comment (goderbauer) [inline packages/flutter/test/gestures/scale_test.dart:594]: same

**Review by goderbauer — COMMENTED** [review]
Looks good, just one question about the test.

File: packages/flutter/test/gestures/scale_test.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/test/gestures/scale_test.dart:588]: We need to dispatch the pointer down event to the `ScaleGestureRecognizer` by `route` and the `tester.async.flushMicrotasks();` does not dispatch the event.

File: packages/flutter/test/gestures/scale_test.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/test/gestures/scale_test.dart:594]: same too :)

**Review by goderbauer — APPROVED** [review]
LGTM
