### PR TITLE
[iOS] Clarify provisioning profile error instructions

### LINKED ISSUE #167595: [iOS] Improve the error message if code signing config is incorrect
### Use case

If I download a Flutter iOS project that uses code signing config that I don't have access to, I'll get an error like:

```
$ flutter run
Launching lib/main.dart on Loïc’s iPhone 15 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ABCDEF123
Running Xcode build...
Xcode build done.                                           13.4s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): No Account for Team "ABCDEF123". Add a new account in Accounts settings or verify that your accounts
have valid credentials.
/path/to/my/app/ios/Runner.xcodeproj


Error (Xcode): No profiles for 'com.example.app' were found: Xcode couldn't find any iOS App Development
provisioning profiles matching 'com.example.app'.
/path/to/my/app/ios/Runner.xcodeproj



It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.

Error launching application on Loïc’s iPhone 15.
```

### Proposal

Consider the following error message cahnges:

```diff
  $ flutter run
  Launching lib/main.dart on Loïc’s iPhone 15 in debug mode...
  Automatically signing iOS for device deployment using specified development team in Xcode project: ABCDEF123
  Running Xcode build...
  Xcode build done.                                           13.4s
  Failed to build iOS app
- Could not build the precompiled application for the device.
+
+ Error: unable to code sign the application.

  Error (Xcode): No Account for Team "ABCDEF123". Add a new account in Accounts settings or verify that your accounts
  have valid credentials.
  /path/to/my/app/ios/Runner.xcodeproj
  
  
  Error (Xcode): No profiles for 'com.example.app' were found: Xcode couldn't find any iOS App Development
  provisioning profiles matching 'com.example.app'.
  /path/to/my/app/ios/Runner.xcodeproj
  
- It appears that there was a problem signing your application prior to installation on the device.
-  
- Verify that the Bundle Identifier in your project is your signing id in Xcode
-   open ios/Runner.xcworkspace
- 
- Also try selecting 'Product > Build' to fix the problem.
- 
-  Error launching application on Loïc’s iPhone 15.
+ To fix this:
+ 
+ 1. Open the project in Xcode:
+ 
+    open ios/Runner.xcworspace
+    
+ 2. Open Runner target > Signing & Capabilities.
+    Verify that the Bundle Identifier is correct.
+    
+ 3. Open Xcode > Settings > Accounts.
+    Verify that you are signed in to the correct Apple Developer account.
+    
+ 4. Fix any issues reported by Product > Build.
```

### PR DESCRIPTION
**Pull request by mozammal-hossain**
## What is this PR changing or adding, and why?

This PR improves the iOS provisioning profile/code-signing failure message in `flutter_tools` to make the cause and remediation steps clearer.

Previously, the output used generic wording and limited guidance.  
Now, the message explicitly states that code signing failed and provides concrete, ordered steps in Xcode to resolve team/account/bundle-identifier configuration issues. This should reduce confusion and speed up troubleshooting when running on physical iOS devices.

Fixes [#167595](https://github.com/flutter/flutter/issues/167595).

## What changed

- Replaced the generic provisioning-profile failure text with clearer messaging:
  - `Error: could not code sign the application.`
- Added step-by-step remediation guidance:
  1. Open `ios/Runner.xcworkspace`
  2. Check `Runner > Signing & Capabilities` (Team + Bundle Identifier)
  3. Verify Apple account in `Xcode Settings > Accounts`
  4. Run `Product > Build` and fix reported signing issues
- Updated hermetic tests to assert the new error/help text in:
  - `build_ios_test.dart`
  - `build_ipa_test.dart`

## If you had to change anything in the [flutter/tests] repo

No changes were made in the `flutter/tests` repo.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -1120,16 +1120,19 @@ Future<bool> _handleIssues(
...
+    logger.printError('To resolve this issue, try the following steps:');
+    logger.printError('  1. Open the project in Xcode:');
+    logger.printError('     open ios/Runner.xcworkspace');
+    logger.printError('  2. In Runner > Signing & Capabilities, verify:');
     logger.printError(
-      'Verify that the Bundle Identifier in your project is your signing id in Xcode',
+      '     • Team is selected and valid for your Apple Developer account',
     );
-    logger.printError('  open ios/Runner.xcworkspace');
+    logger.printError('     • Bundle Identifier matches your provisioning profile');
```
[the remark this answers is not in the document]
Comment (mozammal-hossain) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated.

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -1120,16 +1120,19 @@ Future<bool> _handleIssues(
...
-    );
+    logger.printError('Error: could not code sign the application.');
     logger.printError('');
+    logger.printError('To resolve this issue, try the following steps:');
+    logger.printError('  1. Open the project in Xcode:');
+    logger.printError('     open ios/Runner.xcworkspace');
+    logger.printError('  2. In Runner > Signing & Capabilities, verify:');
     logger.printError(
-      'Verify that the Bundle Identifier in your project is your signing id in Xcode',
+      '     - Team is selected and valid for your Apple Developer account',
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Nit: "Team" is set to a valid Apple Developer account

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 3]
```diff
@@ -1120,16 +1120,19 @@ Future<bool> _handleIssues(
...
     );
-    logger.printError('  open ios/Runner.xcworkspace');
+    logger.printError('     - Bundle Identifier matches your provisioning profile');
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/mac.dart]: This is a bit unclear. Most people would just use auto managed profile

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 2 above)
Comment (mozammal-hossain) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated as per your suggestion

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 3 above)
Comment (mozammal-hossain) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated this line. Is it ok now?

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 4]
```diff
@@ -1120,16 +1120,22 @@ Future<bool> _handleIssues(
...
+    logger.printError('  2. In Runner > Signing & Capabilities, verify:');
     logger.printError(
-      'It appears that there was a problem signing your application prior to installation on the device.',
+      '     - Team is set to a valid Apple Developer account',
     );
-    logger.printError('');
     logger.printError(
-      'Verify that the Bundle Identifier in your project is your signing id in Xcode',
+      '     - Bundle Identifier is correct for your app (with automatic signing, '
+      'Xcode manages the provisioning profile)',
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/mac.dart]: It's possible that developers don't use automatic signing. Can you mention both cases? (one with automatic signing, and one with manual signing)?

Comment (mozammal-hossain) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated. this time, I've explicitly mentioned, automatic and manual signing.

**Review by hellohuanlin — DISMISSED** [review]

**Review by LouiseHsu — DISMISSED** [review]
lgtm, can you fix the failing analyze test?

**Comment by mozammal-hossain** [comment]
@LouiseHsu would you like to approve this PR, as it has passed all the test caes?

**Comment by mozammal-hossain** [comment]
@hellohuanlin please approve this PR.

**Comment by LouiseHsu** [comment]
> @LouiseHsu would you like to approve this PR, as it has passed all the test caes?

i was going to approve last week but looks like google testing is stuck. let me try again.

**Review by LouiseHsu — APPROVED** [review]

**Comment by mozammal-hossain** [comment]
@hellohuanlin could you please approve it again?

**Review by okorohelijah — APPROVED** [review]
from triage: lg
