### PR TITLE
Fix LayoutExplorer cycle

### LINKED ISSUE #115228: CupertinoTabScaffold causing empty Layout explorer in Dart DevTools in stable and throws `StackOverflowError` on master.
## Steps to Reproduce

1. Execute `flutter create --sample=cupertino.CupertinoTabScaffold.1 mysample`
2. Run application on simulator or device
3. Open Widget Inspector
4. Click any element, Layout Explorer stays empty

**Expected results:** 
Layout Explorer showing details about the active Widget

**Actual results:**
Layout Explorer doesn't show anything

<details>
  <summary>Logs</summary>

```
Analyzing mysample...                                                   
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
    • Flutter version 3.3.8 on channel stable at /Users/simon/development/1developmentTools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (4 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/simon/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 65DEB21C-B2FF-4AFC-8705-518A32D03600 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Screenshot 2022-11-13 at 14 46 50

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/115228

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -2030,101 +2030,110 @@ mixin WidgetInspectorService {
...
+        subtreeDepth: 0,
+        includeProperties: true,
+        service: delegate.service,
+        addAdditionalPropertiesCallback: delegate.addAdditionalPropertiesCallback,
+      );
+
+      final Map<String, Object> additionalJson = <String, Object>{
+        'renderObject' : renderObject.toDiagnosticsNode().toJsonMap(newDelegate),
+      };
+
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2059]: Didn't touch the code below, moved the `addAdditionalPropertiesCallback` code to a named function so I can reference it.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 2]
```diff
@@ -2030,101 +2030,109 @@ mixin WidgetInspectorService {
         'result': result,
       });
     }
+
+    Map<String, Object>? additionalCallback(DiagnosticsNode node, InspectorSerializationDelegate delegate) {
+      final Object? value = node.value;
+      final RenderObject? renderObject = value is Element ? value.renderObject : null;
+      if (renderObject == null) {
+        return null;
```
Comment (kenzieschmoll) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2038]: in the previous state of this callback, we were returning an empty map for the additional json in this case. Is there a reason we switched to null?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 3]
```diff
@@ -2030,101 +2030,109 @@ mixin WidgetInspectorService {
...
+      }
+      assert(delegate.addAdditionalPropertiesCallback == additionalCallback);
+      // The new delegate for collecting properties on `renderObject`.
+      // Setting `subtreeDepth` to 0 to skip child RenderObjects. Also removes
+      // the additional callback from `delegate` since we should only collect
+      // RenderObjects from the element tree.
+      final DiagnosticsSerializationDelegate newDelegate = InspectorSerializationDelegate(
```
Comment (kenzieschmoll) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: why can we no longer use delegate.copyWith?

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2038]: In this case `null` and `const Map<String, Object>{}` has the same meaning I think: the caller will set the map to `const Map<String, Object>{}` if the return value is null: 
https://github.com/flutter/flutter/blob/c38731ea48b80faefc3eadcf05796e683a3ad7e1/packages/flutter/lib/src/widgets/widget_inspector.dart#L3602-L3604

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: reverted to return an empty map.

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: Not sure if it makes sense to add the callback as an argument of `copyWith`. Also I don't think we can use `copyWith` to set something to `null`, since `null` is used to represent "no changes" in `copyWith`.

Comment (kenzieschmoll) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: Can you add the addAdditionalPropertiesCallback parameter with an explicit null here (`addAdditionalPropertiesCallback: null`)? And also add a comment to describe why we are using the InspectorSerializationDelegate constructor instead of `copyWith`?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: The default value is null so there seems to be a lint preventing that (`avoid_redundant_argument_values`).

Comment (kenzieschmoll) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: You should be able to ignore the lint for that line:
```
// We are using the [InspectorSerializationDelegate] constructor instead of
// [InspectorSerializationDelegate.copyWith] so that the [addAdditionalPropertiesCallback]
// property can be set to null.
// ignore: avoid_redundant_argument_values
addAdditionalPropertiesCallback: null
```

If you can't ignore the lint, then just add the comment.

Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2045]: this should use copyWith

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 4]
```diff
@@ -2030,101 +2030,112 @@ mixin WidgetInspectorService {
...
-          final Map<String, Object> additionalJson = <String, Object>{};
-          final Object? value = node.value;
-          if (value is Element) {
-            final RenderObject? renderObject = value.renderObject;
-            if (renderObject != null) {
-              additionalJson['renderObject'] =
-                  renderObject.toDiagnosticsNode().toJsonMap(
-                        delegate.copyWith(
-                          subtreeDepth: 0,
-                          includeProperties: true,
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2050]: I think the simpler fix may be to add
expandProperties: false here
That should avoid the stack overflow without breaking the layout explorer.

**Review by jacob314 — APPROVED** [review]
lgtm
