### PR TITLE
[Material] Fix 20051 FAB tooltip touch target

### LINKED ISSUE #20051: Tooltips do not always show up when long pressing an FAB
## Steps to Reproduce

(Easier to reproduce on an emulator)

1. Generate the example app
2. (Optional)Turn on debug paint for easier reproduction
3. Long click the FAB icon, the tooltip shows up
4. Long click outside of the FAB icon, the tooltip does not show up

[Video of the problem](https://i.imgur.com/PRJZQs9.gifv)

## Logs

```
[√] Flutter (Channel master, v0.5.8-pre.190, on Microsoft Windows [Version 10.0.17134.165], locale en-BE)
    • Flutter version 0.5.8-pre.190 at C:\tools\flutter
    • Framework revision 35b55d51a8 (43 minutes ago), 2018-07-31 14:17:44 -0700
    • Engine revision af855e063a
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.16.0

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.0 (API 24) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by johnsonmh**
FAB tooltip was only appearing when the icon widget inside of the FAB was long pressed, but not when the edge of the button was long pressed.

Fixed by moving tooltip addition to after the RawMaterialButton creation, so that the tooltip wraps the whole button. Had to merge semantics to keep the semantics information.

Added unit test for long press outside of the icon. 

Closes #20051

### CODE REVIEW

**Review by willlarche — COMMENTED** [review]
LGTM. Please get review from A11y and Flutter experts.

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 1]
```diff
@@ -268,6 +258,18 @@ class _FloatingActionButtonState extends State<FloatingActionButton> {
       child: result,
     );
 
+    if (widget.tooltip != null) {
+      final Widget tooltip = MergeSemantics(
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/floating_action_button.dart]: I'm not sure if we actually want a MergeSemantics here, or if we just want to hide the tooltip label entirely using `excludeFromSemantics`. cc @goderbauer

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/floating_action_button.dart]: This will cause the FAB to take on the tooltip label, where previously it did not

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Ahh okay cool, that makes more sense then our behavior

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 2]
```diff
@@ -268,6 +258,18 @@ class _FloatingActionButtonState extends State<FloatingActionButton> {
       child: result,
     );
 
+    if (widget.tooltip != null) {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Use `new` for MergeSemantics

**Review by jonahwilliams — APPROVED** [review]
LGTM modulo nit

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 1 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Yes, I used MergeSemantics to keep the semantics the same as before.

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 2 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/floating_action_button.dart]: I'm new to Flutter, but I know that in general the "new" keyword is [considered deprecated in dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-new). I realize that it still appears elsewhere in the file, I figured I would just not add it in new code and later we can clean up the existing code? WDYT?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/floating_action_button.dart]: We're going to clean up the `new`s all at once when we're happy with the lints and fixes to remove it. In the mean time let's keep it consistent.

Comment (johnsonmh) [reply packages/flutter/lib/src/material/floating_action_button.dart]: SGTM, added `new`s back in.

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 3]
```diff
@@ -268,6 +258,18 @@ class _FloatingActionButtonState extends State<FloatingActionButton> {
...
+      final Widget tooltip = new MergeSemantics(
+        child: new Tooltip(
+          message: widget.tooltip,
+          child: result,
+        ),
+      );
+      // The long-pressable area for the tooltip should always be as big as
+      // the tooltip even if there is no child.
+      result = widget.child != null ? tooltip : new SizedBox.expand(child: tooltip);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/floating_action_button.dart]: This doesn't look right. A childless FAB's size shouldn't depend on the size of the tooltip's message.

Comment (johnsonmh) [reply packages/flutter/lib/src/material/floating_action_button.dart]: I didn't add this behavior, it was added in [pull/16168](https://github.com/flutter/flutter/pull/16168), so I don't have the full context. It's possible that my moving the tooltip wrapper to after the `RawMaterialButton` also fixed this bug. 

I removed this line in a recent commit, since [this test](https://github.com/HansMuller/flutter/blob/da89186cd6dc5496d05c06fcbfada9115702a3d2/packages/flutter/test/material/floating_action_button_test.dart#L72) still passes after the change, do you feel its safe to remove?

Comment (HansMuller) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Put in by me no less (I'd forgotten)!

The problem here is that before the tooltip's size was constrained by the RawMaterialButton, which has a fixed size/shape the case of a FAB. Since the Tooltip now contains the RawMaterialButton, its size isn't constrained anymore.

File: packages/flutter/test/material/floating_action_button_test.dart [hunk 4]
```diff
@@ -50,6 +50,47 @@ void main() {
...
+          ),
+        ),
+      ),
+    );
+
+    expect(find.byType(Text), findsNothing);
+    await tester.longPressAt(_rightEdgeOfFab(tester));
+    await tester.pumpAndSettle();
+
+    expect(find.byType(Text), findsOneWidget);
```
Comment (HansMuller) [inline packages/flutter/test/material/floating_action_button_test.dart]: This is OK, since if there's one Text widget, it's probably the tooltip. However `find.text('Add')` would be a little better (here and below).

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/material/floating_action_button_test.dart (hunk 4 above)
Comment (johnsonmh) [reply packages/flutter/test/material/floating_action_button_test.dart]: Thanks for the tip, done.
