### PR TITLE
TextField terminal the enter and space raw key events by default

### LINKED ISSUE #81233: [desktop] Pressing Spacebar in TextField triggers ListTile's onTap in ListView
This is an issue similar to #78652, but on macOS (11.3 Big Sur on M1 mac). When I hit the spacebar inside a TextFormField I do not get a space, but rather an ink splash. Shift + spacebar works. See animated GIF below.

**To reproduce:**
Clone the code from https://github.com/tiloc/faiadashu . 

launch the app, choose "SDC Demo Scroller" from the main menu and then select the first field "Enter your first name". Start typing letters and hit space. You should see an ink splash, but no space being entered.
Screen Recording 2021-04-09 at 00 58 12

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-arm, locale en-DE)
    • Flutter version 2.0.5 at /Users/tilo/development/flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.3 20E232 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

_Originally posted by @tiloc in https://github.com/flutter/flutter/issues/78652#issuecomment-816285838_

### PR DESCRIPTION
**Pull request by xu-baolin**
// TextField use the `enter` to finish the input or create a new line, and the
    // `space` is a very common input character, so we default to terminal those
    // two keys, otherwise, when its ancestor handles the two keys(such as `ListTile`),
    // the functions of `TextField` will be abnormal.

Fixes #81233

### CODE REVIEW

**Comment by xu-baolin** [comment]
CC @LongCatIsLooong @justinmc @chunhtai

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 1]
```diff
@@ -1067,11 +1067,26 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
+    return KeyEventResult.ignored;
+  }
+
   @override
   Widget build(BuildContext context) {
     super.build(context); // See AutomaticKeepAliveClientMixin.
     assert(debugCheckHasDirectionality(context));
     final TextEditingController controller = _effectiveController;
+    final FocusNode focusNode = _effectiveFocusNode;
+    focusNode.onKey ??= _handleRawKeyEvent;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/text_field.dart:1089]: This worries me.
If `_effectiveFocusNode` came from `widget.focusNode`, it will change its key handler. Additionally, if `focusNode` doesn't have `onKey`, then the developer must remember to add your logic back. 

I think we might as well add another `Focus` for your additional logic, so that it stays on.

**Review by dkwingsmt — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 2]
```diff
@@ -1067,11 +1067,26 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
     );
   }
 
+  KeyEventResult _handleRawKeyEvent(FocusNode node, RawKeyEvent event) {
+    assert(node.hasFocus);
+    // TextField use the `enter` to finish the input or create a new line, and the
+    // `space` is a very common input character, so we default to terminal those
+    // two keys, otherwise, when its ancestor handles the two keys(such as `ListTile`),
+    // the functions of `TextField` will be abnormal.
```
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/text_field.dart:1075]: (Probably also the material one)

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/cupertino/text_field.dart:1089]: You are so right!

**Review by dkwingsmt — APPROVED** [review]
LGTM.

Can you also add the following comment to `focusNode` of text fields? (Feel free to change as you like.)

```dart
  ///
  /// ## Key handling
  ///
  /// By default, [TextField] absorbs key events of Space key and Enter key,
  /// because they are commonly used as both shortcuts and text field inputs.
  /// This means that, if these keys are pressed when [TextField] is the
  /// primary focus, they will not be sent to other widgets (such as triggering
  /// an enclosing [ListTile]).
  ///
  /// If [FocusNode.onKey] is not null, this filter is bypassed. In the likely
  /// case that this filter is still desired, check these keys and return
  /// [KeyEventResult.skipRemainingHandlers].
  ///
  /// ```dart
  /// final FocusNode focusNode = FocusNode(
  ///   onKey: (FocusNode node, RawKeyEvent event) {
  ///     if (event.logicalKey == LogicalKeyboardKey.space
  ///         || event.logicalKey == LogicalKeyboardKey.enter) {
  ///       return KeyEventResult.skipRemainingHandlers;
  ///     }
  ///     // Now process the event as desired.
  ///   },
  /// );
```
