### PR TITLE
Adds fix for NAN value and pressure values outside of device reported min and max

### LINKED ISSUE #26624: gestures/force_press.dart': 'pressure.isNaN ? true : (pressure <= 1.0 && pressure >= 0.0)': is not true.
I'm on Android:
```
I/flutter (13366): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13366): The following assertion was thrown while routing a pointer event:
I/flutter (13366): 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 219 pos 14: 'pressure.isNaN
I/flutter (13366): ? true : (pressure <= 1.0 && pressure >= 0.0)': is not true.
I/flutter (13366): 
I/flutter (13366): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13366): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13366): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13366):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13366): 
I/flutter (13366): When the exception was thrown, this was the stack:
I/flutter (13366): #2      ForcePressGestureRecognizer.handleEvent (package:flutter/src/gestures/force_press.dart:219:14)
I/flutter (13366): #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (13366): #4      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (13366): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (13366): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (13366): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (13366): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (13366): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (13366): #10     _invoke1 (dart:ui/hooks.dart:187:13)
I/flutter (13366): #11     _dispatchPointerDataPacket (dart:ui/hooks.dart:138:5)
I/flutter (13366): (elided 2 frames from class _AssertionError)
I/flutter (13366): 
I/flutter (13366): Event:
I/flutter (13366):   PointerMoveEvent(Offset(211.8, 342.5))
I/flutter (13366): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I was hitting an input field a bunch.

### PR DESCRIPTION
**Pull request by jslavitz**
Fixes #26624, also adds fix for nan values causing update to incorrectly trigger.

### CODE REVIEW

File: packages/flutter/lib/src/gestures/force_press.dart [hunk 1]
```diff
@@ -215,8 +215,18 @@ class ForcePressGestureRecognizer extends OneSequenceGestureRecognizer {
...
+      assert(
+        event.pressureMin < 0.0 ||
+        event.pressureMax > 0.0 ||
+        pressure.isNaN ||
+        (pressure < 1.0 && pressure > 0.0)
+      );
+      // If the device incorrectly reports a pressure outside of pressureMin
+      // and pressureMax, we still want this recognizer to respond normally.
+      if (!pressure.isNaN)
+        pressure = pressure.clamp(0.0, 1.0);
```
Comment (goderbauer) [inline packages/flutter/lib/src/gestures/force_press.dart]: Wouldn't the assert above fire if pressure is not within [0.0, 1.0]? What's the purpose of doing both?

Comment (jslavitz) [reply packages/flutter/lib/src/gestures/force_press.dart]: The assert reports true if the pressure is greater than the device reported max pressure. The clamp fixes this case.

File: packages/flutter/lib/src/gestures/force_press.dart [hunk 2]
```diff
@@ -203,10 +206,16 @@ class ForcePressGestureRecognizer extends OneSequenceGestureRecognizer {
 
   @override
   void addPointer(PointerEvent event) {
-    startTrackingPointer(event.pointer);
-    if (_state == _ForceState.ready) {
-      _state = _ForceState.possible;
-      _lastPosition = event.position;
+    // If the device has a maximum pressure of less than 1, (ie. on a non iOS
+    // device) we want do not want any callbacks to be called.
+    if (!(event is PointerUpEvent) && event.pressureMax <= 1.0) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/force_press.dart]: pressureMax can't be < 1, so this can just be == 1 with an assert >= 1 above.
the comment doesn't match the code

File: packages/flutter/lib/src/gestures/force_press.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/gestures/force_press.dart]: but if the assert fires, we never get here

Comment (Hixie) [reply packages/flutter/lib/src/gestures/force_press.dart]: (i think the assert won't fire, though.)

File: packages/flutter/lib/src/gestures/force_press.dart (hunk 2 above)
Comment (jslavitz) [reply packages/flutter/lib/src/gestures/force_press.dart]: Couldn't it be less than one if that's what the manufacturers set for the max pressure?

Comment (Hixie) [reply packages/flutter/lib/src/gestures/force_press.dart]: we define the minimum maximum pressure as 1.0 and the maximum minimum pressure as 1.0.

Comment (jslavitz) [reply packages/flutter/lib/src/gestures/force_press.dart]: Oh, ok!

File: packages/flutter/lib/src/gestures/force_press.dart [hunk 3]
```diff
@@ -225,6 +235,11 @@ class ForcePressGestureRecognizer extends OneSequenceGestureRecognizer {
       _lastPosition = event.position;
       _lastPressure = pressure;
 
+      // If the device incorrectly reports a pressure outside of pressureMin
+      // and pressureMax, we still want this recognizer to respond normally.
+      if (!pressure.isNaN)
```
Comment (xster) [inline packages/flutter/lib/src/gestures/force_press.dart]: I'd flip the order of all this a bit. 

debugPrint right away if the raw platform event.pressure isn't within event.pressureMin and event.pressureMax. 

The default _inverseLerp can clamp but the user should be allowed to do whatever they want with `interpolation`.

Then, we hard assert the outcomes of `interpolation`. By that point, pressure needs to be between 0 and 1.

File: packages/flutter/test/gestures/force_press_test.dart [hunk 4]
```diff
@@ -109,6 +109,100 @@ void main() {
     expect(ended, 1);
   });
 
+  testGesture('Force presses are not recognized on devices with low maxmium pressure', (GestureTester tester) {
+
```
Comment (xster) [inline packages/flutter/test/gestures/force_press_test.dart]: extra line

File: packages/flutter/test/gestures/force_press_test.dart [hunk 5]
```diff
@@ -449,4 +543,109 @@ void main() {
...
+    // Pressure fed into the test environment simulates the values received directly from the device.
+    tester.route(const PointerMoveEvent(pointer: pointerValue, position: Offset(10.0, 10.0), pressure: 2.5, pressureMin: pressureMin, pressureMax: pressureMax));
+
+    // We have not hit the start pressure, so no events should be true.
+    expect(started, 0);
+    expect(peaked, 0);
+    expect(updated, 0);
+    expect(ended, 0);
+
+    tester.route(const PointerMoveEvent(pointer: pointerValue, position: Offset(10.0, 10.0), pressure: 8.0, pressureMin: pressureMin, pressureMax: pressureMax));
```
Comment (xster) [inline packages/flutter/test/gestures/force_press_test.dart]: Add a comment here saying this would break if not handled properly.

File: packages/flutter/lib/src/gestures/force_press.dart [hunk 6]
```diff
@@ -98,6 +98,9 @@ typedef GestureForceInterpolation = double Function(double pressureMin, double p
 /// force touch functionality, with the exception of the iPhone XR. In addition,
 /// a small handful of Android devices have this functionality as well.
 ///
+/// Devices with faux screen pressure sensors like the Pixel 2 and 3 will not
```
[the remark this answers is not in the document]
Comment (jslavitz) [reply packages/flutter/lib/src/gestures/force_press.dart]: The event's pressure isn't really relative to this comment right? That value isn't public.

File: packages/flutter/lib/src/gestures/force_press.dart (hunk 3 above)
Comment (jslavitz) [reply packages/flutter/lib/src/gestures/force_press.dart]: What about the case when the result of interpolation is NAN? Do you think that should still be clamped to 0?

Comment (xster) [reply packages/flutter/lib/src/gestures/force_press.dart]: ah, the current doc already says NaN is ok. I think that's ok in that case (to skip in interpolation returns NaN).

File: packages/flutter/lib/src/gestures/force_press.dart (hunk 6 above)
[the remark this answers is not in the document]
Comment (xster) [reply packages/flutter/lib/src/gestures/force_press.dart]: I'm not sure I understood the answer. What does a faux screen pressure sensor mean? What makes the Pixel 2 or 3 different vs say Pixel 1? 

In general, try to describe the source data and don't editorialize.

File: packages/flutter/lib/src/gestures/force_press.dart [hunk 7]
```diff
@@ -203,10 +206,17 @@ class ForcePressGestureRecognizer extends OneSequenceGestureRecognizer {
 
   @override
   void addPointer(PointerEvent event) {
-    startTrackingPointer(event.pointer);
-    if (_state == _ForceState.ready) {
-      _state = _ForceState.possible;
-      _lastPosition = event.position;
+    assert(event.pressureMax >= 1.0);
+    // If the device has a maximum pressure of less than or equal to 1, (ie. on
```
Comment (xster) [inline packages/flutter/lib/src/gestures/force_press.dart]: Describe root principles. It's not because it's a non-iOS device that we're not calling callbacks. It's because there is no useful pressure data since every event is a max pressure event on devices with no pressure sensing hardware.

File: packages/flutter/test/widgets/gesture_detector_test.dart [hunk 8]
```diff
@@ -367,9 +367,21 @@ void main() {
         ),
       ),
     );
-
-    final TestGesture gesture = await tester.startGesture(const Offset(400.0, 50.0));
     const int pointerValue = 1;
+    const Offset offset = Offset(400, 50);
```
Comment (xster) [inline packages/flutter/test/widgets/gesture_detector_test.dart]: Perhaps just make a const on top of this file for these initial down events in this file and in the next one.

**Review by xster — APPROVED** [review]
LGTM

File: packages/flutter/test/gestures/force_press_test.dart [hunk 9]
```diff
@@ -109,6 +109,99 @@ void main() {
     expect(ended, 1);
   });
 
+  testGesture('Force presses are not recognized on devices with low maxmium pressure', (GestureTester tester) {
+    // Device specific constants that represent those from the iPhone X
```
Comment (xster) [inline packages/flutter/test/gestures/force_press_test.dart]: This comment isn't right right?

Comment (jslavitz) [reply packages/flutter/test/gestures/force_press_test.dart]: I may have been referring to the .4 and the .85 being the start and peak pressure values as perceived on the iPhone X relative to a pressure max of 1.0. But yah, that is not the clearest comment given there is interpolation happening behind the scenes.

**Comment by ovidiu-anghelina** [comment]
Will this handle Android devices that have no pressure touch features as well? I can see comments about the gesture recognizer only being triggered for devices that have this feature, but my Samsung J7 and OnePlus 6T both report every PointerEvent as having a pressure of 1. This completely breaks CupertinoTextFields on Android as they react to every touch down as if it's a pressure touch, and the widget does not allow disabling or overriding the pressure touch functionality. Sorry if this has been fixed elsewhere already, I'm on the stable branch.
