### PR TITLE
web_ui: avoid crash for showPerformanceOverlay; log 'not supported' once

### LINKED ISSUE #172405: showPerformanceOverlay=true in MaterialApp throws UnimplementedError on web with no clear “not supported” message
### Use case

Hello!

A small proposal

Enabling the performance overlay in a Flutter web app by setting:
```dart
MaterialApp(
  showPerformanceOverlay: true,
  // …
)
```

results in the following UnimplementedError:
```dart
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:3       throw_
errors.dart:266
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39                 addPerformanceOverlay
profile.dart:117
package:flutter/src/rendering/layer.dart 1056:12                                  addToScene
layer.dart:1056
package:flutter/src/rendering/layer.dart 711:5                                    [_addToSceneWithRetainedRendering]
layer.dart:711
package:flutter/src/rendering/layer.dart 1372:12                                  addChildrenToScene
layer.dart:1372
package:flutter/src/rendering/layer.dart 2083:5                                   addToScene
layer.dart:2083
package:flutter/src/rendering/layer.dart 1120:5                                   buildScene
layer.dart:1120
package:flutter/src/rendering/view.dart 358:30                                    compositeFrame
view.dart:358
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
binding.dart:634
package:flutter/src/widgets/binding.dart 1242:13                                  drawFrame
binding.dart:1242
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
binding.dart:495
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 117:77  tear
operations.dart:117
package:flutter/src/scheduler/binding.dart 1438:7                                 [_invokeFrameCallback]
binding.dart:1438
package:flutter/src/scheduler/binding.dart 1351:9                                 handleDrawFrame
binding.dart:1351
package:flutter/src/scheduler/binding.dart 1060:9                                 <fn>
binding.dart:1060
lib/_engine/engine/frame_service.dart 147:9                                       <fn>
frame_service.dart:147
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 47:11           internalCallback
isolate_helper.dart:47
════════════════════════════════════════════════════════════════════════════════════════════════════
128
Another exception was thrown: UnimplementedError
```

The stack trace doesn't indicate that this flag is simply not supported on the web, which makes it time consuming to find the root cause. I forgot that showPerformanceOverlay was enabled in the project😀

### Proposal

When showPerformanceOverlay is enabled on the web platform, the framework should log a clear warning such as:

```
showPerformanceOverlay is not supported on web
```

### PR DESCRIPTION
**Pull request by muradhossin**
Fixes flutter/flutter#172405

On Flutter Web, calling `MaterialApp(showPerformanceOverlay: true)` reaches
`SceneBuilder.addPerformanceOverlay`, which previously threw `UnimplementedError`
and crashed apps. This change makes the method a no-op on Web and logs a one-time
warning:

  "showPerformanceOverlay is not supported on Flutter Web. Use DevTools
   Performance (Timeline) instead."

Rationale: Avoid crashes and guide developers to the supported tooling on Web.

Testing:
- Relied on CI for web_ui builds and tests.
- (Manual reproduction before fix) Enabling `showPerformanceOverlay` on Web produced
  UnimplementedError from `canvaskit/layer_scene_builder.dart`.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart [hunk 1]
```diff
@@ -38,8 +41,15 @@ class LayerSceneBuilder implements ui.SceneBuilder {
...
   @override
   void addPerformanceOverlay(int enabledOptions, ui.Rect bounds) {
-    // We don't plan to implement this on the web.
-    throw UnimplementedError();
+    // Not implemented on Web. Avoid crashing; warn once to guide developers.
+    if (!_webPerfOverlayWarned) {
+      _webPerfOverlayWarned = true;
+      print(
+        'showPerformanceOverlay is not supported on Flutter Web. '
+        'Use DevTools Performance (Timeline) instead.'
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart]: Let's point users towards the documentation for this.
```suggestion
        'showPerformanceOverlay is not supported on Flutter Web. '
        'See: https://docs.flutter.dev/perf/web-performance'
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart [hunk 2]
```diff
@@ -38,8 +41,15 @@ class LayerSceneBuilder implements ui.SceneBuilder {
...
+      );
+    }
+    // No-op on Web.
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart]: This comment is not necessary.
```suggestion
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart [hunk 3]
```diff
@@ -38,8 +41,15 @@ class LayerSceneBuilder implements ui.SceneBuilder {
 
   @override
   void addPerformanceOverlay(int enabledOptions, ui.Rect bounds) {
-    // We don't plan to implement this on the web.
-    throw UnimplementedError();
+    // Not implemented on Web. Avoid crashing; warn once to guide developers.
+    if (!_webPerfOverlayWarned) {
+      _webPerfOverlayWarned = true;
+      print(
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart]: Let's use `printWarning` here:
```suggestion
      printWarning(
```

**Review by mdebbar — COMMENTED** [review]
Looks good, thanks for the contribution!

Would you mind adding a simple test that does something like this:
```dart
final LayerSceneBuilder sb = LayerSceneBuilder();
expect(
  () => sb.addPerformanceOverlay(0, ui.Rect.zero),
  returnsNormally,
);
```

**Comment by mdebbar** [comment]
> Would you mind adding a simple test that does something like this:
> 
> ```dart
> final LayerSceneBuilder sb = LayerSceneBuilder();
> expect(
>   () => sb.addPerformanceOverlay(0, ui.Rect.zero),
>   returnsNormally,
> );
> ```

Bonus points if you also check for the warning message being printed 😃 Here's an example you could copy from:
https://github.com/flutter/flutter/blob/6ddbb81a22cd629f0996cce4ceaee7b082fa7cf5/engine/src/flutter/lib/web_ui/test/engine/profiler_test.dart#L31-L34

File: engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+      // First call may emit 0 (if already warned earlier in another test) or 1 new warning.
+      final int deltaFirst = afterFirstCall - baselineWarnings;
+      expect(deltaFirst == 0 || deltaFirst == 1, isTrue,
+          reason: 'First call should emit at most one warning.');
+      if (deltaFirst == 1) {
+        expect(
+          warnings.last,
+          contains('showPerformanceOverlay is not supported on Flutter Web'),
+        );
+      }
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart]: Simplify:
```suggestion
      final LayerSceneBuilder sb1 = LayerSceneBuilder();
      warnings.clear();
      expect(() => sb1.addPerformanceOverlay(0, ui.Rect.zero), returnsNormally);
      expect(warnings, hasLength(1));
      expect(
        warnings.single,
        contains('showPerformanceOverlay is not supported on Flutter Web'),
      );
```

File: engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+      // Second call (using a new builder instance) should not emit another warning.
+      final LayerSceneBuilder sb2 = LayerSceneBuilder();
+      final int baselineSecond = warnings.length;
+      sb2.addPerformanceOverlay(0, ui.Rect.zero);
+      expect(warnings.length, baselineSecond,
+          reason: 'Second call should not produce additional warnings.');
+    });
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart]:
```suggestion
      
      final LayerSceneBuilder sb2 = LayerSceneBuilder();
      warnings.clear();
      expect(() =>sb2.addPerformanceOverlay(0, ui.Rect.zero), returnsNormally);
      expect(warnings, isEmpty, reason: 'Second call should not produce additional warnings.');
    });
```

File: engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/performance_overlay_test.dart:1]: Could you move this test to the `test/ui/` folder? That way, the test will run for all renderers (CanvasKit and Skwasm).

File: engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart:1]: This file moved to `engine/src/flutter/lib/web_ui/lib/src/engine/layer/layer_scene_builder.dart`

**Comment by mdebbar** [comment]
Sorry for the confusion. I didn't mean that you should move the file. The file has moved in master, so I wanted you to rebase to pick up the file move.

I fixed it and merged latest master into this PR.

**Review by mdebbar — APPROVED** [review]
The change looks good to me!

I think the test may fail until https://github.com/flutter/flutter/pull/174588 lands. Let's wait for that PR to land, and then let's update this PR and submit it.

**Review by harryterkelsen — APPROVED** [review]
LGTM

**Comment by mdebbar** [comment]
Waiting for https://github.com/flutter/flutter/pull/175392/ to land.
