### PR TITLE
Fixed media query issues and added test to prevent it from coming back

### LINKED ISSUE #38465: MediaQuery viewPadding inconsistent
The viewPadding of mediaQuery is currently not consistent, for instance it changes when the keyboard is shown.
This is caused by `removePadding` and `removeViewInsets` having a side effect on the viewPadding, even if all the remove booleans are false.

For instance remove padding has the following code: 
```dart
      viewPadding: viewPadding.copyWith(
        left: math.max(0.0, viewPadding.left - padding.left),
        top: math.max(0.0, viewPadding.top - padding.top),
        right: math.max(0.0, viewPadding.right - padding.right),
        bottom: math.max(0.0, viewPadding.bottom - padding.bottom),
      ),
```

This does not check whether it should remove any padding from any of the sides, so the only case the viewPadding has a value is when the corresponding side of the padding happens to be zero (which happens when the keyboard is shown)

In my opinion`viewPadding` should never be affected by `removePadding` or `removeViewInsets`.

### PR DESCRIPTION
**Pull request by Kavantix**
## Description

Fixed media query issues, removePadding and removeViewInsets removed values that were set to false

## Related Issues

Fixes #38465

## Tests

I added the following tests:

Tests that checks whether only setting some of the properties does not affect the others.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

**Not sure if this is considered a breaking change**
The api does not change but if someone relies of the incorrect behaviour of the current implementation it may break.

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 1]
```diff
@@ -420,10 +422,10 @@ class MediaQueryData {
         bottom: removeBottom ? 0.0 : null,
       ),
       viewPadding: viewPadding.copyWith(
-        left: math.max(0.0, viewPadding.left - padding.left),
-        top: math.max(0.0, viewPadding.top - padding.top),
-        right: math.max(0.0, viewPadding.right - padding.right),
-        bottom: math.max(0.0, viewPadding.bottom - padding.bottom),
+        left: removeLeft ? math.max(0.0, viewPadding.left - padding.left) : null,
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/media_query.dart]: I think rather than null here it should just return the viewPadding.left and so on?

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 2]
```diff
@@ -454,19 +456,20 @@ class MediaQueryData {
...
       devicePixelRatio: devicePixelRatio,
       textScaleFactor: textScaleFactor,
       platformBrightness: platformBrightness,
       padding: padding,
       viewPadding: viewPadding.copyWith(
-        left: math.max(0.0, viewPadding.left - viewInsets.left),
-        top: math.max(0.0, viewPadding.top - viewInsets.top),
-        right: math.max(0.0, viewPadding.right - viewInsets.right),
-        bottom: math.max(0.0, viewPadding.bottom - viewInsets.bottom),
+        left: removeLeft ? math.max(0.0, viewPadding.left - viewInsets.left) : null,
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/media_query.dart]: Same comment here regarding returning null.

**Review by Piinks — COMMENTED** [review]
Hi @Kavantix,
Welcome and thank you for the contribution! 🎉 
Can you please remove the formatting changes that are unrelated to the bug you are fixing? Also, see below regarding replacing viewPadding properties with null.
Thanks!

**Comment by Piinks** [comment]
This page from the API docs may be of some help: https://master-api.flutter.dev/flutter/widgets/MediaQueryData-class.html
It explains in detail how viewPadding, viewInsets and Padding are related to each other.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 1 above)
Comment (Kavantix) [reply packages/flutter/lib/src/widgets/media_query.dart]: Null in copywith just means that the value stays the same

**Comment by Kavantix** [comment]
@Piinks I removed the unrelated formatting

File: packages/flutter/test/widgets/media_query_test.dart [hunk 3]
```diff
@@ -171,7 +171,63 @@ void main() {
     expect(unpadded.boldText, true);
   });
 
-  testWidgets('MediaQuery.removeViewInsets removes specified viewInsets', (WidgetTester tester) async {
+  testWidgets('MediaQuery.removePadding only removes specified padding',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/media_query_test.dart]: Nit: This should be one line.

File: packages/flutter/test/widgets/media_query_test.dart [hunk 4]
```diff
@@ -171,7 +171,63 @@ void main() {
...
+    expect(unpadded.viewInsets, viewInsets);
+    expect(unpadded.alwaysUse24HourFormat, true);
+    expect(unpadded.accessibleNavigation, true);
+    expect(unpadded.invertColors, true);
+    expect(unpadded.disableAnimations, true);
+    expect(unpadded.boldText, true);
+  });
+
+  testWidgets('MediaQuery.removeViewInsets removes specified viewInsets',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/media_query_test.dart]: Nit: same here

File: packages/flutter/test/widgets/media_query_test.dart [hunk 5]
```diff
@@ -228,7 +284,8 @@ void main() {
     expect(unpadded.boldText, true);
   });
 
-  testWidgets('MediaQuery.removeViewPadding removes specified viewPadding', (WidgetTester tester) async {
+  testWidgets('MediaQuery.removeViewInsets removes only specified viewInsets',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/media_query_test.dart]: Nit: and here.

File: packages/flutter/test/widgets/media_query_test.dart [hunk 6]
```diff
@@ -244,7 +301,62 @@ void main() {
...
+    expect(unpadded.viewInsets, viewInsets.copyWith(bottom: 0));
+    expect(unpadded.alwaysUse24HourFormat, true);
+    expect(unpadded.accessibleNavigation, true);
+    expect(unpadded.invertColors, true);
+    expect(unpadded.disableAnimations, true);
+    expect(unpadded.boldText, true);
+  });
+
+  testWidgets('MediaQuery.removeViewPadding removes specified viewPadding',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/media_query_test.dart]: Nit: and here.

File: packages/flutter/test/widgets/media_query_test.dart [hunk 7]
```diff
@@ -285,6 +397,61 @@ void main() {
     expect(unpadded.boldText, true);
   });
 
+  testWidgets('MediaQuery.removeViewPadding removes only specified viewPadding',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/media_query_test.dart]: Nit: and here.

**Review by Piinks — COMMENTED** [review]
Looking good!
There are just a few style nits below. :) Thanks!

**Review by Piinks — APPROVED** [review]
LGTM! 🎉 Thank you again for the contribution!
We'll merge this once the tree is green. 🌲
