### PR TITLE
Fix leak in hardware_keyboard_test.dart

### LINKED ISSUE #134379: KeyboardListener does not dispose FocusNode
### Steps to reproduce

1. Remove leakTrackingTestConfig from packages/flutter/test/services/hardware_keyboard_test.dart at 'Dispatch events to all handlers' test
2. See the test failing

### PR DESCRIPTION
**Pull request by derdilla**
While covering tests with leak protection ( [#134](https://github.com/dart-lang/leak_tracker/issues/134#issue-1870426468)), leak tracking indicated that many FocusNodes were not disposed after the test ended. 

This is because `KeyboardListener` and `RawKeyboardListener` internally use the `Focus` widget, which makes its caller responsible for calling` FocusNode.dispose` on the focus node when it is done with it. This behavior however was not documented in the `KeyboardListener` property, leading to the missing `FocusNode.dispose()` call in the tests.

closes #134379

### CODE REVIEW

File: packages/flutter/lib/src/widgets/keyboard_listener.dart [hunk 1]
```diff
@@ -53,6 +53,9 @@ class KeyboardListener extends StatelessWidget {
   });
 
   /// Controls whether this widget has keyboard focus.
+  ///
+  /// The owner will be responsible for calling [FocusNode.dispose] on the focus
+  /// node when it is done with it.
   final FocusNode focusNode;
```
Comment (polina-c) [inline packages/flutter/lib/src/widgets/keyboard_listener.dart:59]: Why the comment here and below is removed?
It is saying that the owner, i.e the code that created the object, should dispose it, that is correct.

File: packages/flutter/test/services/hardware_keyboard_test.dart [hunk 2]
```diff
@@ -192,7 +193,9 @@ void main() {
       true);
     expect(logs, <int>[3, 2, 1]);
     logs.clear();
-  }, variant: KeySimulatorTransitModeVariant.all());
+
+    focusNode.dispose();
```
Comment (polina-c) [inline packages/flutter/test/services/hardware_keyboard_test.dart:197]: Please, here and in other tests replace `focusNode.dispose();` with 'addTearDown(focusNode.dispose);', so that if test fails in the middle, it still disposes the object and does not fail with memory leak error.

**Review by polina-c — CHANGES_REQUESTED** [review]

File: packages/flutter/test/services/hardware_keyboard_test.dart (hunk 2 above)
Comment (NobodyForNothing) [reply packages/flutter/test/services/hardware_keyboard_test.dart]: Thanks for the info, I put it directly after the focusNode declaration.

File: packages/flutter/lib/src/widgets/keyboard_listener.dart (hunk 1 above)
Comment (NobodyForNothing) [reply packages/flutter/lib/src/widgets/keyboard_listener.dart:59]: I am not sure what you mean by that.
For explanation: I *added* the documentation because the class didn't clarify that the owner is still responsible for object disposal. This lack of documentation made the leak occur in the first place and created the possibility of error.

Comment (polina-c) [reply packages/flutter/lib/src/widgets/keyboard_listener.dart:59]: Got it. Sorry for confusion.

It is a common convention that owner should dispose an object. If object x obtained object y as a method argument, it does not make x owning y, so x is not responsible for the disposal.

This should not be explained, because if we will explain it, this explanation will be needed for every disposable argument.
Makes sense?
So, I think the comment should be removed.

File: packages/flutter/lib/src/widgets/raw_keyboard_listener.dart [hunk 3]
```diff
@@ -50,6 +50,9 @@ class RawKeyboardListener extends StatefulWidget {
   });
 
   /// Controls whether this widget has keyboard focus.
+  ///
+  /// The owner will be responsible for calling [FocusNode.dispose] on the focus
+  /// node when it is done with it.
```
Comment (polina-c) [inline packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:55]: Please, remove comment.

File: packages/flutter/test/services/hardware_keyboard_test.dart [hunk 4]
```diff
@@ -192,7 +194,7 @@ void main() {
       true);
     expect(logs, <int>[3, 2, 1]);
     logs.clear();
-  }, variant: KeySimulatorTransitModeVariant.all());
+  }, variant: KeySimulatorTransitModeVariant.all(),);
```
Comment (polina-c) [inline packages/flutter/test/services/hardware_keyboard_test.dart:198]: Please, remove comma.

**Review by polina-c — CHANGES_REQUESTED** [review]
Couple comments.

**Review by polina-c — APPROVED** [review]
