### PR TITLE
Fix chips delete icon override the default icon size and ignores `IconTheme` from the chip property and `ChipThemeData`

### LINKED ISSUE #146404: Provided delete icon overrides the default delete icon size
### Steps to reproduce

1. Create a `FilterChip` and set an icon for `deleteIcon`
2. Increase the size

### Expected results

It should be possible to support any size icon on FilterChip.
This is more noticable when using a smaller `labelStyle`, but still happens even with the default.
Dialing in some custom padding numbers seems to make it work.
I've left a nice repoduction in the linked dartpad

### Actual results

The icon is painted off center.

I dont't know if this is rude, so please forgive me.
@TahaTesser I'm going to ping you being that you would probably know the most about this.
Thanks!

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=4aa1ad145d994fda54c9e87556f38bd9

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details open><summary>Logs</summary>

```console
No notable logs are printed when rendering this widget
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22621.3296], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (10 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\dicke\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code, 64-bit edition (version 1.86.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.86.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[√] Connected device (4 available)
    • SM G970U (mobile) • R58M230DQHV • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.3296]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 123.0.6312.106
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 123.0.2420.81

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### LINKED ISSUE #146501: Chips delete icon ignores `IconTheme` from `Chip.iconTheme` and `ChipThemeData.iconTheme`
### Steps to reproduce

Run the code sample below

According to docs the `iconTheme` is used for all icons in the chip.
https://github.com/flutter/flutter/blob/4967a94cd907f74b5090e960a3753a2aff4b7d47/packages/flutter/lib/src/material/chip.dart#L223-L230

### Expected results

Screenshot 2024-04-09 at 15 38 26

### Actual results

Screenshot 2024-04-09 at 16 12 40

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        chipTheme: const ChipThemeData(
          iconTheme: IconThemeData(
            color: Colors.amber,
          ),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: FilterChip(
            avatar: const Icon(Icons.favorite),
            onDeleted: () {},
            label: const Text('Filter Chip'),
            onSelected: (value) {},
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [Provided delete icon overrides the default delete icon size](https://github.com/flutter/flutter/issues/146404)
fixes [Chips delete icon ignores `IconTheme` from `Chip.iconTheme` and `ChipThemeData.iconTheme`](https://github.com/flutter/flutter/issues/146501)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        chipTheme: const ChipThemeData(
          iconTheme: IconThemeData(
            color: Colors.red,
          ),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              FilterChip(
                avatar: const Icon(Icons.favorite),
                onDeleted: () {},
                label: const Text('Filter Chip'),
                onSelected: (value) {},
              ),
              const SizedBox(height: 10),
              FilterChip(
                avatar: const Icon(Icons.favorite),
                // ignore: prefer_const_constructors
                deleteIcon: const Icon(Icons.delete),
                onDeleted: () {},
                label: const Text('Filter Chip'),
                onSelected: (value) {},
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Before
Screenshot 2024-04-09 at 16 48 48

### After

Screenshot 2024-04-09 at 16 48 31

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/material/chip.dart [hunk 1]
```diff
@@ -1179,6 +1189,20 @@ class _RawChipState extends State<RawChip> with MaterialStateMixin, TickerProvid
     if (!hasDeleteButton) {
       return null;
     }
+    final IconThemeData iconTheme = widget.iconTheme
+      ?? chipTheme.iconTheme
+      ?? theme.chipTheme.iconTheme
+      ?? const IconThemeData(size: _kDeleteIconSize);
+    final Color? effectiveDeleteIconColor = widget.deleteIconColor
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/chip.dart:1196]: Wow. I get it, but wow.

**Review by HansMuller — APPROVED** [review]
There are some golden image changes to approve (they look OK to me) and this will likely cause some internal golden image tests to fail. Good fix though!

File: packages/flutter/lib/src/material/chip.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/chip.dart:1196]: @HansMuller 
Looks like some tests are definitely failing in `Google Testing`. Could you please take a look?

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/chip.dart:1196]: All the failures are related to the icon size change because now it respects `_kDeleteIconSize` instead of using the fallback size 24.0. I'm creating a fix in G3 to preserve the original change. Once that is merged, we can try to trigger the test here again:)

File: packages/flutter/lib/src/material/chip.dart [hunk 2]
```diff
@@ -1179,6 +1189,20 @@ class _RawChipState extends State<RawChip> with MaterialStateMixin, TickerProvid
     if (!hasDeleteButton) {
       return null;
     }
+    final IconThemeData iconTheme = widget.iconTheme
+      ?? chipTheme.iconTheme
+      ?? theme.chipTheme.iconTheme
+      ?? const IconThemeData(size: _kDeleteIconSize);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/chip.dart:1195]: BTW, just wonder whether we can just use the default icon size from `chipDefaults` instead of this constant? Because I'm thinking if the the token is updated to a different value, then this can be updated automatically.

File: packages/flutter/lib/src/material/chip.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/chip.dart:1196]: Appreciate it!

**Comment by QuncCccccc** [comment]
Sent cl/625413895 for reviews. After merging it, this should good to go.

**Comment by QuncCccccc** [comment]
Just triaged all the golden changes.

File: packages/flutter/lib/src/material/chip.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/chip.dart:1195]: Good idea, let me add this.

**Comment by TahaTesser** [comment]
@QuncCccccc 
Since there are no M2 defaults, delete button uses same delete icon size in both M2 and M3. 
I've the update the default `iconTheme` to explicitly to use M3 defaults.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks!

**Comment by TahaTesser** [comment]
@QuncCccccc 
Thanks for all your help, it was only possible to land because of you.
