### PR TITLE
Print sub process that failed to run in tool

### LINKED ISSUE #120942: Improve the "bad architecture" `flutter` error
Introduced in https://github.com/flutter/flutter/pull/114558

In https://github.com/flutter/flutter/issues/120697 users are hitting the "incorrect architecture" error on an Intel machine:
```
null
This binary was built with the incorrect architecture to run on this machine.
Flutter requires the Rosetta translation environment. If you are on an ARM Mac, try running:
  sudo softwareupdate --install-rosetta --agree-to-license
```
1. Rosetta is only required on an arm Mac, rearrange those sentences.
2. Specify what executable has the wrong architecture.  In the case of https://github.com/flutter/flutter/issues/120697#issuecomment-1433971860 it was `java -version`, but that wasn't clear in the error.
3. Avoid the `null`.

### PR DESCRIPTION
**Pull request by jmagman**
When the tool cannot run an executable, include the command it tried to run in the error message.

Before:
```
null
This binary was built with the incorrect architecture to run on this machine.
Flutter requires the Rosetta translation environment. If you are on an ARM Mac, try running:
  sudo softwareupdate --install-rosetta --agree-to-license
```
After:
```
Flutter failed to run "java -version".
The binary was built with the incorrect architecture to run on this machine.
If you are on an ARM Apple Silicon Mac, Flutter requires the Rosetta translation environment. Try running:
  sudo softwareupdate --install-rosetta --agree-to-license
```
Fixes https://github.com/flutter/flutter/issues/120942

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 1]
```diff
@@ -759,9 +768,11 @@ void _handleMacOSException(Exception e, String? message, int errorCode, String?
   const int ebadarch = 86;
   if (errorCode == ebadarch) {
     final StringBuffer errorBuffer = StringBuffer();
-    errorBuffer.writeln(message);
-    errorBuffer.writeln('This binary was built with the incorrect architecture to run on this machine.');
-    errorBuffer.writeln('Flutter requires the Rosetta translation environment. If you are on an ARM Mac, try running:');
+    if (message != null) {
+      errorBuffer.writeln('$message.');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:772]: are we sure this message never ends in a period?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:772]: this question is an uber-nit

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:772]: nvm, looks like the answer is yes

**Review by christopherfujino — APPROVED** [review]
LGTM
