### PR TITLE
Fix SliverGrid garbage collection issue

### LINKED ISSUE #138749: Crash when using SliverGrid, findChildIndexCallback, a sparsely populated grid and updating the children
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the app I'm working on, we have a custom `SliverGrid` layout. It does a somewhat sparse layout of grid items, with a contiguous series of items and other items interspersed along the way. Some actions performed in the app causes the grid contents to be limited - thus items are removed from the grid.

We also use a `findChildIndexCallback` with `SliverChildBuilderDelegate`. It seems like that combination can lead to places in the grid where removing items leads to a crash.

1. Open https://dartpad.dev/?id=d9f723468f22d4035dfcf90366802151
1. Run app
2. Scroll down until "grid item 7" just scrolls into view in the left column
3. Press the FAB/refresh button in the bottom right

### Expected results

No crashes or issues.

### Actual results

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:508:12
childCount >= leadingGarbage + trailingGarbage
is not true

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

The following RenderObject was being processed when the exception was fired: RenderSliverGrid#255ad relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: SliverGrid ← Viewport ← IgnorePointer-[GlobalKey#e6cb3] ← Semantics ← Listener ←
    _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#04dfe] ←
    Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#8e450] ←
    NotificationListener<ScrollMetricsNotification> ← RepaintBoundary ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 6878.2, remainingPaintExtent: 805.0, crossAxisExtent: 826.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 805.0, remainingCacheExtent: 1305.0, cacheOrigin:
    -250.0)
  geometry: SliverGeometry(scrollExtent: 21000.0, paintExtent: 805.0, maxPaintExtent: 21000.0,
    hasVisualOverflow: true, cacheExtent: 1305.0)
  currently live children: 1 to 6
This RenderObject had the following descendants (showing up to depth 5):
    child with index 1: RenderIndexedSemantics#9f23a
      child: RenderRepaintBoundary#89623 NEEDS-PAINT
        child: _RenderColoredBox#da96c NEEDS-PAINT
          child: RenderPositionedBox#60e7f NEEDS-LAYOUT
            child: RenderParagraph#3e200 relayoutBoundary=up1 NEEDS-LAYOUT
    child with index 2: RenderIndexedSemantics#cd9d3
      child: RenderRepaintBoundary#04b11 NEEDS-PAINT
        child: _RenderColoredBox#d3dc9 NEEDS-PAINT
          child: RenderPositionedBox#d0f81 NEEDS-LAYOUT
            child: RenderParagraph#6065a relayoutBoundary=up1 NEEDS-LAYOUT
    child with index 5: RenderIndexedSemantics#5f68d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#ed0b9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: _RenderColoredBox#b737d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPositionedBox#2daac NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderParagraph#26a3e NEEDS-LAYOUT NEEDS-PAINT
    child with index 6: RenderIndexedSemantics#4b2f1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#93339 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: _RenderColoredBox#10147 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPositionedBox#a9025 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderParagraph#23002 NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Code sample

<details><summary>Code sample</summary>

See https://dartpad.dev/?id=d9f723468f22d4035dfcf90366802151.

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
The code doesn't consider indices of children may not be continuous after rebuild.

fixes https://github.com/flutter/flutter/issues/138749

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_grid.dart [hunk 1]
```diff
@@ -596,14 +596,9 @@ class RenderSliverGrid extends RenderSliverMultiBoxAdaptor {
...
       layout.getMaxChildIndexForScrollOffset(targetEndScrollOffset) : null;
-
     if (firstChild != null) {
-      final int oldFirstIndex = indexOf(firstChild!);
-      final int oldLastIndex = indexOf(lastChild!);
-      final int leadingGarbage = (firstIndex - oldFirstIndex).clamp(0, childCount); // ignore_clamp_double_lint
-      final int trailingGarbage = targetLastIndex == null
-        ? 0
-        : (oldLastIndex - targetLastIndex).clamp(0, childCount); // ignore_clamp_double_lint
+      final int leadingGarbage = _calculateLeadingGarbage(firstIndex);
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver_grid.dart:600]: I copy over the code from RenderSliverFixedExtentBoxAdaptor

**Comment by goderbauer** [comment]
Would you mind reverting some of the dartfmt changes that snuck into this PR?

**Comment by chunhtai** [comment]
> Would you mind reverting some of the dartfmt changes that snuck into this PR?

done.

File: packages/flutter/lib/src/rendering/sliver_grid.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_grid.dart:600]: Could the logic live in a common place (e.g. the RenderSliverMultiBoxAdaptor base class) and be shared between the two instead of duplicating it?

File: packages/flutter/test/widgets/slivers_test.dart [hunk 2]
```diff
@@ -1504,3 +1567,55 @@ class _NullBuildContext implements BuildContext {
...
+    return 200;
+  }
+
+  @override
+  SliverGridGeometry getGeometryForChildIndex(int index) {
+    return SliverGridGeometry(
+        crossAxisOffset: 20.0 + 20 * index,
+        crossAxisExtent: 20,
+        mainAxisExtent: 20,
+        scrollOffset: 0);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/slivers_test.dart:1603]: formatting nit:

```suggestion
      crossAxisOffset: 20.0 + 20 * index,
      crossAxisExtent: 20,
      mainAxisExtent: 20,
      scrollOffset: 0,
    );
```

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/sliver_grid.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_grid.dart:600]: I don't want to expose these method because they are implementation detail. since this are only two instance, I prefer to keep it as is. We can revisit this if there are more use case for these logic
