### PR TITLE
[flutter_tools] null safety mode is used for dill naming

### LINKED ISSUE #68891: The engine -> framework roll is failing
Beginning with https://github.com/flutter/flutter/pull/68821, the engine -> framework roll is failing with an error in the framework tests:
```
00:01 +0: loading /b/s/w/ir/k/flutter/packages/flutter_test/test/bindings_test_failure.dart                                                                                                            Shell: [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: error: Library 'package:vector_math/hash.dart' was compiled with sound null safety (in strong mode) and it requires --sound-null-safety option at runtime
Shell: [ERROR:flutter/runtime/dart_isolate.cc(141)] Could not prepare isolate.
Shell: [ERROR:flutter/runtime/runtime_controller.cc(377)] Could not create root isolate.
Shell: [ERROR:flutter/shell/common/shell.cc(492)] Could not launch engine with configuration.
```

That engine roll contains only rolls from Skia, Fuchsia, and Dart. I am suspicious of the Dart roll: https://github.com/flutter/engine/pull/22058. We should try reverting it locally to see if that helps.

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

A dill compiled in sound/unsound mode cannot be reused in `--initialize-from-dill` for compiling unsound/sound mode. Rename the file if sound mode is detected via command line argument.

This does not work in the case of autodetect.

Fixes https://github.com/flutter/flutter/issues/68891

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Most of this change is plumbing, because the test config does not use buildInfo mostly. I can refactor that to be a bit easier to follow later (will require updating g3).

File: packages/flutter_tools/lib/src/bundle.dart [hunk 1]
```diff
@@ -51,13 +56,21 @@ String getDefaultCachedKernelPath({
...
 
 String getKernelPathForTransformerOptions(
   String path, {
   @required bool trackWidgetCreation,
+  @required NullSafetyMode nullSafetyMode,
 }) {
+  // Temporary work around until --initialize-from-dill accounts for sound mode.
+  // The tool does not know the compilation mode if [NullSafetyMode.autodetect] is
+  // selected.
+  if (nullSafetyMode == NullSafetyMode.sound) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/bundle.dart:71]: This is the actual fix, everything else is plumbing

**Review by jason-simmons — APPROVED** [review]

File: packages/flutter_tools/lib/src/bundle.dart [hunk 2]
```diff
@@ -51,13 +56,21 @@ String getDefaultCachedKernelPath({
...
+    nullSafetyMode: nullSafetyMode,
   );
 }
 
 String getKernelPathForTransformerOptions(
   String path, {
   @required bool trackWidgetCreation,
+  @required NullSafetyMode nullSafetyMode,
 }) {
+  // Temporary work around until --initialize-from-dill accounts for sound mode.
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/bundle.dart:68]: Could you file an issue for this?

File: packages/flutter_tools/lib/src/test/runner.dart [hunk 3]
```diff
@@ -88,6 +89,7 @@ class _FlutterTestRunnerImpl implements FlutterTestRunner {
     String randomSeed,
     @required List<String> extraFrontEndOptions,
     bool nullAssertions = false,
+    BuildInfo buildInfo // TODO(jonahwilliams): make the default argument
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/test/runner.dart:92]: nit: missing comma

**Review by zanderso — APPROVED** [review]

File: packages/flutter_tools/lib/src/bundle.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/bundle.dart:68]: Filled https://github.com/flutter/flutter/issues/68901

File: packages/flutter_tools/lib/src/test/runner.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/test/runner.dart:92]: I'm about to head out, if you want to apply this change and re-run CI that is fine - otherwise I can clean this up next week when I make these required and update g3

Comment (zanderso) [reply packages/flutter_tools/lib/src/test/runner.dart:92]: later is fine.

**Comment by zanderso** [comment]
Landing before presubmits are finished to get rollers unblocked.
