### PR TITLE
fix a Slider theme update bug

### LINKED ISSUE #118955: Slider text label color on theme change is not updated
#91605

The color of the text in valueIndicatorTextStyle is displayed incorrectly when changing the theme before the first drag of the slider. Similar issue with color [here](https://github.com/material-foundation/flutter-packages/issues/303)

https://user-images.githubusercontent.com/102767277/213883762-a640b28d-1a39-40cc-8c78-9d57826461aa.mp4

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/118955

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -2949,6 +2949,49 @@ void main() {
     );
   });
 
+  testWidgets('sliderTheme change should trigger re-layout', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:2952]:
```suggestion
  testWidgets('SliderTheme change should trigger re-layout', (WidgetTester tester) async {
```

File: packages/flutter/test/material/slider_test.dart [hunk 2]
```diff
@@ -2949,6 +2949,49 @@ void main() {
...
+
+    await tester.pumpWidget(buildFrame(ThemeMode.dark));
+    await tester.pump(
+      const Duration(milliseconds: 100), // to let the theme animate
+      EnginePhase.build,
+    );
+
+    expect(renderObject.debugNeedsLayout, true);
+
+    await tester.pumpAndSettle();
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:2992]:
```suggestion

    // Pump the rest of the frames to complete the test.
    await tester.pumpAndSettle();
```

**Review by TahaTesser — APPROVED** [review]
LGTM with some nits.

File: packages/flutter/test/material/slider_test.dart [hunk 3]
```diff
@@ -2949,6 +2949,49 @@ void main() {
...
+                  label: 'label',
+                  onChanged: (double value) => sliderValue = value,
+                ),
+              ),
+            ),
+          ),
+        ),
+      );
+    }
+    await tester.pumpWidget(buildFrame(ThemeMode.light));
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:2978]:
```suggestion
    }

    await tester.pumpWidget(buildFrame(ThemeMode.light));
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Review by TahaTesser — APPROVED** [review]
LGTM again
