### PR TITLE
Make sure all isolates start during flutter driver tests.

### LINKED ISSUE #24703: flutter_driver pauses all isolates at their startup (even ones started from compute()), rather than only pausing initial isolate
Isolates spawned using "compute" don't execute properly while executed in an integration test which in turn results in incorrect app behavior.
How to reproduce:

- use example from https://flutter.io/docs/cookbook/testing/integration
- in lib/main.dart

1. add:
```
import 'package:flutter/foundation.dart';
```

2. add function:
```dart
String _test(String s) {
  return s;
}
```
3. modify _incrementCounter function:
```dart
  void _incrementCounter() async {
    final s = await compute(_test, 'hello');
    print(s);

    setState(() {
      _counter++;
    });
  }
```
The app works properly when executing flutter run, but the integration test fails (flutter drive --target=test_driver/app.dart)

### LINKED ISSUE #30641: flutter_gallery's driver test doesn't show image resources
To reproduce, run `flutter drive --profile -t test_driver/transitions_perf.dart` inside flutter_gallery on iPhone6S. Pay attention to Shrine and Contact inside Studies.

This issue makes our benchmark inaccurate as it doesn't capture the possibly slow image loading jank in https://github.com/flutter/flutter/issues/28113#issuecomment-476530608

Below is a screenshot of Contact when the flutter_gallery is opened by `flutter drive`:
flutter_01

For comparison, here's a screenshot if I open flutter_gallery normally without `flutter_drive`:
flutter_03

### PR DESCRIPTION
**Pull request by speaking-in-code**
## Description

Fixes https://github.com/flutter/flutter/issues/24703.
Fixes #30641
Fixes https://github.com/flutter/flutter/issues/30641

Flutter driver has problems when flutter apps use more than a single isolate. The other isolates don't start, so apps malfunction. This PR fixes the problem by listening for new isolates to become runnable, and automatically starting them.

## Related Issues

https://github.com/flutter/flutter/issues/24703

## Tests

* Manually tested against an app that requires isolates.
* Added checks in flutter_driver_test.dart to verify that all isolates have resume() invoked.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

### CODE REVIEW

**Comment by goderbauer** [comment]
@speaking-in-code Can you rebase this to the latest master to fix the analyzer problems?

@dnfield Would you be up for reviewing this one since you're looking at e2e testing?

**Comment by dnfield** [comment]
I suspect you've tried to do a rebase that has gotten git a bit confused.

Can you either open a new PR with just your changes, or fix up the history on this one?

**Comment by speaking-in-code** [comment]
Fixed this PR, I think.

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 1]
```diff
@@ -130,7 +130,7 @@ class VMServiceFlutterDriver extends FlutterDriver {
     // Attempts to resume the isolate, but does not crash if it fails because
     // the isolate is already resumed. There could be a race with other tools,
     // such as a debugger, any of which could have resumed the isolate.
-    Future<dynamic> resumeLeniently() {
+    Future<dynamic> resumeLeniently(VMIsolate isolate) {
```
Comment (dnfield) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:133]: nit: prefer not shadowing parameter names in the enclosing class, which can get confusing.  I don't have a great idea for a name here.

This does make me wonder if there are other cases we should be explicitly passing the isolate reference around though.

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 2]
```diff
@@ -195,19 +195,26 @@ class VMServiceFlutterDriver extends FlutterDriver {
       });
     }
 
+    // The Dart VM may be running with --pause-isolates-on-start.
+    // Set a listener to unpause new isolates as they are ready to run,
+    // otherwise they'll hang indefinitely.
+    client.onIsolateRunnable.listen((VMIsolateRef isolateRef) async {
+      resumeLeniently(await isolateRef.load());
```
Comment (dnfield) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:202]: Is there a reason we're not just setting the outter `isoalte` to `isolateRef.load()` here?

Should we be asserting `isolate == isolateRef.load()` somehow?

Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/vmservice_driver.dart:202]: Ahh I see, this could be other isolates the application uses that also started paused, right?

**Review by dnfield — APPROVED** [review]
LGTM with nit.

File: packages/flutter_driver/test/flutter_driver_test.dart [hunk 3]
```diff
@@ -45,8 +46,12 @@ void main() {
       mockClient = MockVMServiceClient();
       mockVM = MockVM();
       mockIsolate = MockIsolate();
+      otherIsolate = MockIsolate();
       mockPeer = MockPeer();
       when(mockClient.getVM()).thenAnswer((_) => Future<MockVM>.value(mockVM));
+      when(mockClient.onIsolateRunnable).thenAnswer((Invocation invocation) {
+        return Stream<VMIsolateRef>.fromIterable([otherIsolate]);
```
Comment (dnfield) [inline packages/flutter_driver/test/flutter_driver_test.dart:53]: Analyzer wants a type annotation on this array.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
It looks like the checks are failing here due to a version solving error. Can you try to update your branch with the latest on master?

**Comment by christopherfujino** [comment]
> It looks like the checks are failing here due to a version solving error. Can you try to update your branch with the latest on master?

So upstream linux is actually broken with this version solving problem: https://github.com/flutter/flutter/issues/62146. That will have to be fixed first, then this PR rebased to make CI green.

**Comment by speaking-in-code** [comment]
Looks like this is ready to go except for the flutter-build check. Anything I can do to help resolve that?

**Comment by dnfield** [comment]
Added a label that will land this when those issues get resolved
