### PR TITLE
[iOS] Skip gesture recognizer reset workaround on iOS 26+ 

### LINKED ISSUE #179907: [ios] unit test fail on iOS 26: testFlutterPlatformViewTouchesEndedOrTouchesCancelledEventDoesNotFailTheGestureRecognizer
It was introduced by [this PR](https://github.com/flutter/engine/pull/55958) to address [an Apple bug](https://github.com/flutter/engine/pull/55958/files#diff-a3603de99285b1ddce74dcba8fda9e90de2dbfb449a84bb094e9cd6a537afce1R591-R592) where the recognizer is stuck at `.failed` state (the XCTAssert [here](https://github.com/flutter/flutter/blob/1ff83529dc683bccfa580797b263ebf06252aaed/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm#L3071)). 

When running the test on iOS 26, the state is now `.possible` (hence the test failure). This means that Apple likely fixed the bug on iOS 26.

### PR DESCRIPTION
**Pull request by okorohelijah**
Look at https://github.com/flutter/flutter/issues/179907 for more info

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
Fixes flutter/flutter#179907

confirmed from the build - https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20mac_unopt/5/overview

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm [hunk 1]
```diff
@@ -818,6 +818,12 @@ - (void)touchesCancelled:(NSSet*)touches withEvent:(UIEvent*)event {
 }
 
 - (void)forceResetStateIfNeeded {
+  // Apple fixed the bug where the gesture recognizer gets stuck at "failed" state in iOS 26.
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm:821]: nice!

**Review by hellohuanlin — APPROVED** [review]
