### PR TITLE
Match on process name before killing for SwiftPM

### LINKED ISSUE #185831: SwiftPM prefetch kills wrong process
Despite landing https://github.com/flutter/flutter/pull/184831, this code is still killing processes that don't match the argument list

https://github.com/flutter/flutter/blob/b0e66e6dd81c20dae6a3ce2ee515a165dbbbfb3e/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L420-L438

Related: https://github.com/flutter/flutter/issues/184754

### PR DESCRIPTION
**Pull request by vashworth**
We used `pgrep` to find commands that matches the `xcodebuild` command used to prefetch SwiftPM dependencies. However, it's been matching on partial matches, which was unintended. We want it to only match on exact match. To fix, this PR prints out both the process id and command and we match on the command in Dart rather than relying on `pgrep`.

Fixes https://github.com/flutter/flutter/issues/185831.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

If this change needs to override an active code freeze, provide a comment explaining why. The code freeze workflow can be overridden by code reviewers. See pinned issues for any active code freezes with guidance.

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 1]
```diff
@@ -417,18 +417,27 @@ class XcodeProjectInterpreter {
         '-resolvePackageDependencies',
       ];
       if (_swiftPackageFetchProcess == null) {
+        // Remove the `xcrun` prefixes from the command before comparing because the process name
+        // will resolve to the actual xcodebuild path, such as this:
+        // /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
+        final List<String> commandToMatch = command.sublist(command.indexOf('xcodebuild'));
```
[the remark this answers is not in the document]
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: This was correct. Thanks Gemini

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 2]
```diff
@@ -417,18 +417,27 @@ class XcodeProjectInterpreter {
...
         // Check if process is already running from a previous Flutter command. If it is, kill it
         // so we don't have the process running twice. When this process is run twice, it'll cause
         // one to error. The new process will pick up where the old one left off.
         final RunResult result = await _processUtils.run([
           'pgrep',
           '-n', // Select only the newest
           '-f', // Match against full argument lists
-          ...command,
+          '-l', // Print the process name and process ID
+          ...commandToMatch,
```
[the remark this answers is not in the document]
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: This was correct. Thanks Gemini

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 3]
```diff
@@ -417,18 +417,33 @@ class XcodeProjectInterpreter {
         '-resolvePackageDependencies',
       ];
       if (_swiftPackageFetchProcess == null) {
+        // Remove the `xcrun` prefixes from the command before comparing because the process name
+        // will resolve to the actual xcodebuild path, such as this:
+        // /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
+        final int xcodebuildIndex = command.indexOf('xcodebuild');
+        if (xcodebuildIndex == -1) {
+          // This should never happen. The _xcodebuildProjectCommandArguments always includes
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/xcodeproj.dart:425]: Do we want to throw a `ToolExit` here if this should never happen? Tool exit reasons should be actionable by the user, but we probably want to get some indication in our crash reporting if we're encountering this case. Maybe throw a `StateError`?

**Review by bkonyi — COMMENTED** [review]
LGTM with one question.

**Review by bkonyi — DISMISSED** [review]

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart [hunk 4]
```diff
@@ -2499,13 +2502,11 @@ flutter:
...
-            'xcodebuild',
-            '-clonedSourcePackagesDirPath',
-            '/${buildDirectory.path}/SourcePackages',
-            '-resolvePackageDependencies',
+            '-l',
+            'xcodebuild -clonedSourcePackagesDirPath /${buildDirectory.path}/SourcePackages -resolvePackageDependencies',
           ],
-          stdout: '12345',
+          stdout:
+              '12345 xcodebuild -clonedSourcePackagesDirPath /${buildDirectory.path}/SourcePackages -resolvePackageDependencies',
```
Comment (hellohuanlin) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart]: should it be `12345 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -clonedSourcePackagesDirPath /${buildDirectory.path}/SourcePackages -resolvePackageDependencies'`?

Comment (vashworth) [reply packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart]: Yeah that's more aligned with what it returns. I updated.

**Review by hellohuanlin — APPROVED** [review]
