### PR TITLE
Fix a multiple pointers bug

### LINKED ISSUE #68373: Gestures stop working sometimes in lists with multiple touch points
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

`lib/main.dart`:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _s1 = true;
  bool _s2 = true;
  bool _s3 = true;
  bool _s4 = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView(
          children: <Widget>[
            SizedBox(
              height: 32,
            ),
            SwitchListTile(
              title: const Text('Switch'),
              value: _s1,
              onChanged: (value) {
                setState(() {
                  _s1 = value;
                });
              },
            ),
            SwitchListTile(
              title: const Text('Switch'),
              value: _s2,
              onChanged: (value) {
                setState(() {
                  _s2 = value;
                });
              },
            ),
            SizedBox(
              height: 32,
            ),
            SwitchListTile(
              title: const Text('Switch'),
              value: _s3,
              onChanged: (value) {
                setState(() {
                  _s3 = value;
                });

                showAboutDialog(context: context);
              },
            ),
            SwitchListTile(
              title: const Text('Switch'),
              value: _s4,
              onChanged: (value) {
                setState(() {
                  _s4 = value;
                });
                showLicensePage(context: context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

3. Touch and hold multiple (3 or 4) tiles in the list, and then release them all at the same time. Randomly delay the release of one of the fingers slightly until after the popup opens.

4. Close any popups that appear after releasing the list tiles.

5. Repeat until the list tiles stop responding to touch events.

**Expected results:** list tiles continue to respond to touch

**Actual results:** list tiles stop working

<details>
  <summary>Logs</summary>

```
[+17377 ms] E/flutter (23379): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter (23379): #0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
[        ] E/flutter (23379): #1      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:251:25)
[        ] E/flutter (23379): #2      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:232:31)
[        ] E/flutter (23379): #3      _rootRun (dart:async/zone.dart:1182:47)
[        ] E/flutter (23379): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter (23379): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] E/flutter (23379): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] E/flutter (23379): #7      _rootRun (dart:async/zone.dart:1190:13)
[        ] E/flutter (23379): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter (23379): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] E/flutter (23379): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] E/flutter (23379): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] E/flutter (23379): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ] E/flutter (23379): 
[+1953 ms] I/flutter (23379): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (23379): The following assertion was thrown while routing a pointer event:
[        ] I/flutter (23379): 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons ==
[        ] I/flutter (23379): kPrimaryButton': is not true.
[        ] I/flutter (23379): 
[        ] I/flutter (23379): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (23379): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (23379): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (23379):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (23379): 
[        ] I/flutter (23379): When the exception was thrown, this was the stack:
[        ] I/flutter (23379): #2      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:435:12)
[        ] I/flutter (23379): #3      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:376:9)
[        ] I/flutter (23379): #4      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:342:9)
[        ] I/flutter (23379): #5      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:385:5)
[        ] I/flutter (23379): #6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:282:9)
[        ] I/flutter (23379): #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[        ] I/flutter (23379): #8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] I/flutter (23379): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] I/flutter (23379): #10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] I/flutter (23379): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] I/flutter (23379): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
[        ] I/flutter (23379): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] I/flutter (23379): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] I/flutter (23379): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] I/flutter (23379): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] I/flutter (23379): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] I/flutter (23379): #21     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] I/flutter (23379): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] I/flutter (23379): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter (23379): 
[        ] I/flutter (23379): router: Instance of 'PointerRouter'
[        ] I/flutter (23379): route: Closure: (PointerEvent) => void from Function 'handleEvent':.
[        ] I/flutter (23379): event: PointerMoveEvent#649ab(position: Offset(259.1, 330.0))
[        ] I/flutter (23379): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +135 ms] I/flutter (23379): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[+6261 ms] I/chatty  (23379): uid=10203(dev.kdrag0n.bug_repro) 1.ui identical 33 lines
[        ] I/flutter (23379): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[+1321 ms] I/flutter (23379): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[+2460 ms] I/chatty  (23379): uid=10203(dev.kdrag0n.bug_repro) 1.ui identical 5 lines
[   +3 ms] I/flutter (23379): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
```

```
Analyzing bug_repro...                                                  
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel stable, 1.22.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.1 at /home/dragon/code/flutter/sdk
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/dragon/code/android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/dragon/code/android/sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_242-release"
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version openjdk version "1.8.0_242-release"

[✓] Connected device (1 available)
    • Pixel 2 XL (mobile) • [REDACTED] • android-arm64 • Android 11 (API 30)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

This bug can be reproduced with a high probability by #68373 

The scenario where the bug occurs is:

1. Pointer 1 down and add two Recognize(`TapGestureRecognizer` & `VerticalDragGestureRecognizer#5efda`)
2. Pointer 2 down and add two Recognize(`TapGestureRecognizer` & `VerticalDragGestureRecognizer#5efda`)
3. Pointer 3 down and add two Recognize(`TapGestureRecognizer` & `VerticalDragGestureRecognizer#5efda`)
4. Pointer 4 down and add only one Recognize(`VerticalDragGestureRecognizer#5efda`)

Because there is only one gesture in Arena 4, the `VerticalDragGestureRecognizer#5efda` will win by default, and `acceptGesture`. Therefore, this gesture can no longer be accepted by another arena, otherwise, there will be the assertion information mentioned in the #68373.

5. Then release one of the fingers slightly before release all at the other fingers.

## Why the issue happen?
From the log we can catch that:
1. When process the last finger event `_TransformedPointerCancelEvent`，What we expect is `stopTrackingPointer` and then reject this gesture, as the following code show:
```dart
  void _giveUpPointer(int pointer, {bool reject = true}) {
    stopTrackingPointer(pointer);
    if (reject) {
      if (_velocityTrackers.containsKey(pointer)) {
        _velocityTrackers.remove(pointer);
        resolvePointer(pointer, GestureDisposition.rejected);
      }
    }
  }
```
2. But when stop tracking the last pointer will call `didStopTrackingLastPointer` and clear the `_velocityTrackers`, This leads to the `resolvePointer` method cannot be called.  This gesture becomes the last member and wins via sweeping incorrectly.

## Related PR
**This change is an improvement of #39017, @dkwingsmt Please review, thanks. :)**

## Log
```dart
Launching lib\main.dart on PDCM00 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for PDCM00 to report its views...
Debug service listening on ws://127.0.0.1:59993/0X88-HsbOEM=/ws
Syncing files to device PDCM00...
I/flutter ( 5750): Gesture arena 1    ❙ ★ Opening new gesture arena.
I/flutter ( 5750): Gesture arena 1    ❙ Adding: TapGestureRecognizer#93267(debugOwner: GestureDetector, state: ready, button: 1)
I/flutter ( 5750): addAllowedPointer this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.ready]
I/flutter ( 5750): Gesture arena 1    ❙ Adding: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]event[_TransformedPointerDownEvent#da02f(position: Offset(37.7, 134.0))][1]
I/flutter ( 5750): Gesture arena 1    ❙ Closing with 2 members.
I/flutter ( 5750): Gesture arena 2    ❙ ★ Opening new gesture arena.
I/flutter ( 5750): Gesture arena 2    ❙ Adding: TapGestureRecognizer#d4edf(debugOwner: GestureDetector, state: ready, button: 1)
I/flutter ( 5750): addAllowedPointer this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]
I/flutter ( 5750): Gesture arena 2    ❙ Adding: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]event[_TransformedPointerDownEvent#ed1ae(position: Offset(48.7, 335.3))][2]
I/flutter ( 5750): Gesture arena 2    ❙ Closing with 2 members.
I/flutter ( 5750): Gesture arena 3    ❙ ★ Opening new gesture arena.
I/flutter ( 5750): Gesture arena 3    ❙ Adding: TapGestureRecognizer#3379a(debugOwner: GestureDetector, state: ready, button: 1)
I/flutter ( 5750): addAllowedPointer this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]
I/flutter ( 5750): Gesture arena 3    ❙ Adding: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]event[_TransformedPointerDownEvent#68437(position: Offset(65.0, 192.3))][3]
I/flutter ( 5750): Gesture arena 3    ❙ Closing with 2 members.
I/flutter ( 5750): addAllowedPointer this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]
I/flutter ( 5750): Gesture arena 4    ❙ ★ Opening new gesture arena.
I/flutter ( 5750): Gesture arena 4    ❙ Adding: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.possible]event[_TransformedPointerDownEvent#1675a(position: Offset(63.7, 263.7))][4]
I/flutter ( 5750): Gesture arena 4    ❙ Closing with 1 member.
I/flutter ( 5750): Gesture arena 4    ❙ Default winner: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): acceptGesture pointer[4][VerticalDragGestureRecognizer#aac43(start behavior: start)]state[_DragState.possible]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#f3c66(position: Offset(37.7, 134.0))][1]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.504000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#778c6(position: Offset(48.7, 335.3))][2]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.504000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#6c668(position: Offset(65.0, 192.3))][3]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.504000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#2ca47(position: Offset(63.7, 263.7))][4]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.504000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#a0143(position: Offset(37.7, 134.0))][1]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.538000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#355eb(position: Offset(48.7, 335.3))][2]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.538000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#660c6(position: Offset(65.0, 192.3))][3]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.538000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#09744(position: Offset(63.7, 263.7))][4]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:53.538000]
...
start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#aeb42(position: Offset(36.0, 131.0))][1]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.442000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#e482e(position: Offset(48.7, 335.3))][2]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.442000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#059bd(position: Offset(64.0, 193.3))][3]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.442000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#91b4a(position: Offset(62.0, 267.0))][4]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.442000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#64629(position: Offset(35.7, 131.0))][1]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.449000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#cc7c2(position: Offset(64.0, 193.0))][3]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.449000]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerMoveEvent#4e474(position: Offset(62.0, 267.0))][4]
I/flutter ( 5750): handleEvent 2 this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]ts[745:29:54.449000]
I/flutter ( 5750): stopTrackingPointer pointer[2]_trackedPointers[{2}]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerUpEvent#42107(position: Offset(48.7, 335.3))][2]
I/flutter ( 5750): _giveUpPointer [0] [2]reject[false]_velocityTrackers[{1: Instance of 'VelocityTracker', 2: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[2]_trackedPointers[{1, 2, 3, 4}]
I/flutter ( 5750): _giveUpPointer [1] [2]reject[false]_velocityTrackers[{1: Instance of 'VelocityTracker', 2: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): Gesture arena 2    ❙ Sweeping with 2 members.
I/flutter ( 5750): Gesture arena 2    ❙ Winner: TapGestureRecognizer#d4edf(debugOwner: GestureDetector, state: ready, finalPosition: Offset(48.7, 335.3), finalLocalPosition: Offset(48.7, 15.3), button: 1, sent tap down)
I/flutter ( 5750): _giveUpPointer [0] [2]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 2: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[2]_trackedPointers[{1, 3, 4}]
I/flutter ( 5750): _giveUpPointer [1] [2]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 2: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): resolvePointer [2]disposition[GestureDisposition.rejected]_entries[{1: Instance of 'GestureArenaEntry', 2: Instance of 'GestureArenaEntry', 3: Instance of 'GestureArenaEntry', 4: Instance of 'GestureArenaEntry'}]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerCancelEvent#8b921(position: Offset(0.0, 0.0))][4]
I/flutter ( 5750): _giveUpPointer [0] [4]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[4]_trackedPointers[{1, 3, 4}]
I/flutter ( 5750): _giveUpPointer [1] [4]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker', 4: Instance of 'VelocityTracker'}]
I/flutter ( 5750): resolvePointer [4]disposition[GestureDisposition.rejected]_entries[{1: Instance of 'GestureArenaEntry', 3: Instance of 'GestureArenaEntry', 4: Instance of 'GestureArenaEntry'}]
I/flutter ( 5750): Gesture arena 3    ❙ Rejecting: TapGestureRecognizer#3379a(debugOwner: GestureDetector, state: possible, button: 1, sent tap down)
I/flutter ( 5750): stopTrackingPointer pointer[3]_trackedPointers[{3}]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerCancelEvent#cb079(position: Offset(0.0, 0.0))][3]
I/flutter ( 5750): _giveUpPointer [0] [3]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[3]_trackedPointers[{1, 3}]
I/flutter ( 5750): _giveUpPointer [1] [3]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker', 3: Instance of 'VelocityTracker'}]
I/flutter ( 5750): resolvePointer [3]disposition[GestureDisposition.rejected]_entries[{1: Instance of 'GestureArenaEntry', 3: Instance of 'GestureArenaEntry'}]
I/flutter ( 5750): Gesture arena 3    ❙ Rejecting: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): _giveUpPointer [0] [3]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[3]_trackedPointers[{1}]
I/flutter ( 5750): _giveUpPointer [1] [3]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker'}]
I/flutter ( 5750): Gesture arena 3    ❙ Arena empty.
I/flutter ( 5750): Gesture arena 1    ❙ Rejecting: TapGestureRecognizer#93267(debugOwner: GestureDetector, state: possible, button: 1, sent tap down)
I/flutter ( 5750): stopTrackingPointer pointer[1]_trackedPointers[{1}]
I/flutter ( 5750): handleEvent this[VerticalDragGestureRecognizer#aac43(start behavior: start)]_state[_DragState.accepted]event[_TransformedPointerCancelEvent#7e63e(position: Offset(0.0, 0.0))][1]
I/flutter ( 5750): _giveUpPointer [0] [1]reject[true]_velocityTrackers[{1: Instance of 'VelocityTracker'}]
I/flutter ( 5750): stopTrackingPointer pointer[1]_trackedPointers[{1}]
I/flutter ( 5750): _giveUpPointer [1] [1]reject[true]_velocityTrackers[{}]
I/flutter ( 5750): Gesture arena 1    ❙ Default winner: VerticalDragGestureRecognizer#aac43(start behavior: start)
I/flutter ( 5750): acceptGesture pointer[1][VerticalDragGestureRecognizer#aac43(start behavior: start)]state[_DragState.ready]
E/flutter ( 5750): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5750): #0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:328:60)
E/flutter ( 5750): #1      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:251:25)
E/flutter ( 5750): #2      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:232:31)
E/flutter ( 5750): #3      _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 5750): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5750): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5750): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 5750): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5750): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5750): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5750): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 5750): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5750): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 5750): 
```

## Related Issues

Fixes #68373 

## Tests

See files.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
Thank you so much for the investigation and the writeup! Can you come up with a unit test so that we don't accidentally regress it?

**Comment by xu-baolin** [comment]
> Thank you so much for the investigation and the writeup! Can you come up with a unit test so that we don't accidentally regress it?

Coming soon.

**Comment by xu-baolin** [comment]
> Thank you so much for the investigation and the writeup! Can you come up with a unit test so that we don't accidentally regress it?

Done.

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 1]
```diff
@@ -266,10 +266,11 @@ abstract class OneSequenceGestureRecognizer extends GestureRecognizer {
   @protected
   @mustCallSuper
   void resolvePointer(int pointer, GestureDisposition disposition) {
-    final GestureArenaEntry? entry = _entries[pointer];
+    final Map<int, GestureArenaEntry> localEntries = Map<int, GestureArenaEntry>.from(_entries);
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/gestures/recognizer.dart:269]: Why is this clone needed?

**Review by dkwingsmt — APPROVED** [review]
LGTM except for one comment. Thank you for the PR!

File: packages/flutter/lib/src/gestures/recognizer.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/gestures/recognizer.dart:269]: entry. resolve() will trigger nested
calls to this function, so we should remove the entry first as following do.

Comment (xu-baolin) [reply packages/flutter/lib/src/gestures/recognizer.dart:269]: The entry in the map is a reference type here,  I think we can use it after removing it from the map without clone, I will double check:)

Comment (xu-baolin) [reply packages/flutter/lib/src/gestures/recognizer.dart]: I have removed the unnecessary map clone.

**Comment by xu-baolin** [comment]
@dkwingsmt I think it is ready for landing now. : )

**Comment by yitong12580** [comment]
你好 这边已经是最新版本 master 分支
但是还是会出现这个问题。
重现方式：
tabbarview 左右切换的时候 双指 同时多次点击屏幕

**Comment by xu-baolin** [comment]
> 你好 这边已经是最新版本 master 分支
> 但是还是会出现这个问题。
> 重现方式：
> tabbarview 左右切换的时候 双指 同时多次点击屏幕

抱歉这个修正昨天被回退了#68841 ，请确认你验证的版本，如果包含了这个修正还是有问题，请帮忙提供版本信息，和一个最小范围内可以直接运行的复现问题的用例，谢谢。 我会尽快调查影响然后重新合入这个修正。

Sorry, this fix was revert yesterday #68841 . Please confirm the version you verified. If there is still a problem with the change, please provide the version information and a minimal sample code that can be run directly. Thank you. I'll look into the impact as soon as possible and then reland this PR.

**Comment by xu-baolin** [comment]
@dkwingsmt 
I am so sorry for breaking something.
From this error log #68841 , it seems that it has nothing to do with our change, also waiting for your opinions. I have no right see all the logs. Can you help me downlload all the failed logs?
