### PR TITLE
Fix DraggableScrollableSheet rebuilding during drag

### LINKED ISSUE #67219: DraggableScrollableSheet is rebuilding the screen while dragging
## Steps to Reproduce

DraggableScrollableSheet is rebuilding the screen while dragging the sheet and it is causing unnecessary flickers.

```dart
class MyPopUpSheet extends StatelessWidget {
  ScrollController _scrollController; //Needed for

  @override
  Widget build(BuildContext context) {
    return Material(
      child: DraggableScrollableSheet(
        initialChildSize: 0.4,
        minChildSize: 0.4,
        builder: (ctx, scrollController) {
          
         print('Rebuilding...');

          return CustomScrollView(
            controller: scrollController,
            slivers: [
              SliverToBoxAdapter(child: Container(Colors.deepOrange)),
              SliverToBoxAdapter(child: Container(Colors.red)),
              SliverToBoxAdapter(child: Container(Colors.green)),
            ],
          );
        },
      ),
    );
  }

```

**Expected results:** 
It shouldn't rebuild the widget while dragging the sheet.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.20.4 at /Users/username/Library/Application Support/fvm/versions/1.20.4
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 
[✓] Connected device (1 available)            
    • ONEPLUS A6000 (mobile) • 431e5315 • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

cc/ @TahaTesser

### PR DESCRIPTION
**Pull request by moffatman**
`DraggableScrollableSheet` was rebuilding every time the size of the child changed, which meant every frame during a drag. Now it will only rebuild when it gets changed parameters from the parent widget. 

Also inadvertent fix to an exception thrown while rebuilding `DraggableScrollableSheet` with a new controller.

Fixes #67219

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by bugrevealingbme** [comment]
I need this.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 1]
```diff
@@ -683,53 +674,50 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
...
       initialSize: widget.initialChildSize,
-      onSizeChanged: _setExtent,
     );
     // Modify the existing scroll controller instead of replacing it so that
     // developers listening to the controller do not have to rebuild their listeners.
     _scrollController.extent = _extent;
     // If an external facing controller was provided, let it know that the
     // extent has been replaced.
-    widget.controller?._onExtentReplaced(previousExtent);
+    if (widget.controller?.isAttached ?? false) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:718]: I'm curious why the new controller doesn't attached now?

Comment (moffatman) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:718]: Actually, I realized that new controller is still not handled properly (_attach is only called in initState, never if we have a new controller). This isn't really related to my change, I found it while writing the test, where I wanted to show that builder was still called when we have a new controller. Going to update the changeset with proper change for giving a new controller.

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:718]: So this maybe another issue we should fix, right?
Maybe we should fix it in a separate file instead of temporarily circumventing it.

**Comment by kamami** [comment]
Any updates on this fix?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 1 above)
Comment (moffatman) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: I moved it to #111445

**Review by xu-baolin — APPROVED** [review]
LGTM
