### PR TITLE
Better support for wireless devices in IDEs

### LINKED ISSUE #118113: iOS network device not selected when running/debugging in VSCode
## Steps to Reproduce
Requires this PR https://github.com/flutter/flutter/pull/118104.

1. Setup network device (see https://github.com/flutter/flutter/pull/118104 for instructions)
2. Open any flutter app in VSCode
3. VSCode > Run > Start Debugging or VSCode > Run > Run Without Debugging

**Expected results:** 
Expect it to run flutter on network device.

**Actual results:** 
Runs flutter in a mac application.

### PR DESCRIPTION
**Pull request by vashworth**
Updates polling for iOS devices to use a combination of the following commands to determine if a device is connected:
* `xcdevice list`
* `xcdevice observe --wifi`
* `xcdevice observe --usb`

A device is considered connected if it does not have any `observe` events and was found as connected in `xcdevice list` or it had `observe` events that indicate it's connected via one or more interfaces.

Fixes https://github.com/flutter/flutter/issues/118113.

Part 5 in breakdown of https://github.com/flutter/flutter/pull/121262.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -59,7 +59,25 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+  /// false for the device to be considered disconnected.
+  ///
+  /// Example:
+  /// {
+  ///   device-id: {
+  ///     usb: false,
+  ///     wifi: false,
+  ///   },
+  /// }
+  final Map<String, Map<XCDeviceEventInterface, bool>> _observedConnectionsForDevice =
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/devices.dart:79]: nit: "by" tends to indicate what the key is representing, in this case the device identifier
```suggestion
  final Map<String, Map<XCDeviceEventInterface, bool>> _observedConnectionsByDeviceId =
```

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 2]
```diff
@@ -98,34 +113,91 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+      if (device is! IOSDevice) {
+        continue;
+      }
+      _cachedPolledDevices[device.id] = device;
     }
   }
 
+  /// Updates notifier with devices found in the cache that are determined
+  /// to be connected.
+  void _updateNotifierFromCache() {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/devices.dart:176]: I'm not clear on why we need two caches: one as this map and the other in `ItemListNotifier.items`.  Can we directly update the `ItemListNotifier` instead of having an intermediate cache?  Seems like it would be easy for them to get out of sync?

File: packages/flutter_tools/lib/src/macos/xcdevice.dart [hunk 3]
```diff
@@ -198,51 +212,101 @@ class XCDevice {
...
+        unawaited(wifiStderrSubscription.cancel());
       });
-      unawaited(_deviceObservationProcess?.exitCode.then((int status) {
-        _logger.printTrace('xcdevice exited with code $exitCode');
-        unawaited(stdoutSubscription.cancel());
-        unawaited(stderrSubscription.cancel());
-      }).whenComplete(() async {
-        if (_deviceIdentifierByEvent?.hasListener ?? false) {
+
+      unawaited(Future.wait(<Future<void>>[
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/xcdevice.dart:266]: What if only one dies?

File: packages/flutter_tools/lib/src/macos/xcdevice.dart [hunk 4]
```diff
@@ -183,13 +197,13 @@ class XCDevice {
...
     try {
-      if (_deviceObservationProcess != null) {
+      if (_usbDeviceObserveProcess != null || _wifiDeviceObserveProcess != null) {
         throw Exception('xcdevice observe restart failed');
       }
 
       // Run in interactive mode (via script) to convince
       // xcdevice it has a terminal attached in order to redirect stdout.
-      _deviceObservationProcess = await _processUtils.start(
+      _usbDeviceObserveProcess = await _processUtils.start(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/xcdevice.dart:206]: I think swapping to `_processUtils.start` with trace:true and setting up a `mapFunction` to process the `XCDeviceEventNotification` would give you the stdout/stderr behavior you want here, and would be cleaner. 

It does most of what you need, but unfortunately returns a future to the exitCode and not the streaming process, so you won't be able to `kill` it as-written.  You could add a `streamProcess` method  to `ProcessUtils` that takes the same params, move all the `stream` logic into that, and return the process.  Then make `stream` call `streamProcess` and return `process.exitCode`.

Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:206]: So I tried out  `_processUtils.stream` (assuming that's what you meant), but it's a bit problematic because it waits for the `stdout`/`stderr` to be fully processed and then cancels the subscriptions. 

https://github.com/flutter/flutter/blob/2144a1b05ebdb8ccbe0a41441c478fba5c06669d/packages/flutter_tools/lib/src/base/process.dart#L488-L501

I can't think of any great workarounds that maintain the current usage of `ProcessUtils.stream` and also work for my use case. Perhaps I could make a customized version of `ProcessUtils.stream` in `xcdevice.dart` and use that function?

Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:206]: > it's a bit problematic because it waits for the `stdout`/`stderr` to be fully processed and then cancels the subscriptions.

Has "fully processed" means the process has already exited though?

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart:176]: Can you add a comment to `_cachedPolledDevices` declaration explaining this?

File: packages/flutter_tools/lib/src/macos/xcdevice.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:206]: From what I can tell by testing it yet, it waits for it to exit

File: packages/flutter_tools/lib/src/macos/xcdevice.dart (hunk 3 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:266]: When one dies, it also kills the other
https://github.com/flutter/flutter/blob/55f5d058e6c62ea136ced09b74c5e07585b5fad0/packages/flutter_tools/lib/src/macos/xcdevice.dart#L250-L253

File: packages/flutter_tools/lib/src/macos/xcdevice.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart]: > From what I can tell by testing it yet, it waits for it to exit

Isn't that what you want then? I don't think you want those subscriptions to continue after the process is done.  Your code is doing the same thing in `_streamXCDeviceEventCommand`.

```dart
    unawaited(process.exitCode.whenComplete(() {
      stdoutSubscription.cancel();
      stderrSubscription.cancel();
    }));
```

**Review by jmagman — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/macos/xcdevice.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart]: You're right that we don't want those subscriptions to continue after the process is done, which is why I have the unawaited you quoted. The difference, though, is that `_streamXCDeviceEventCommand` does not wait for the process to exit.

Here's a breakdown of the problem with `_processUtils.stream`:

So `_processUtils.stream` waits for the process to exit before returning:

https://github.com/flutter/flutter/blob/2144a1b05ebdb8ccbe0a41441c478fba5c06669d/packages/flutter_tools/lib/src/base/process.dart#L488-L493

So let's say I created `_processUtils.streamProcess` which returns the `Process`:
```dart
  Future<Process> streamProcess(
    args,
  }) async {
    final Process process = await start(
      args,
    );
    final StreamSubscription<String> stdoutSubscription = process.stdout
      [removed to shorten...]
    final StreamSubscription<String> stderrSubscription = process.stderr
      [removed to shorten...]

    // this is the problem-maker, it will get stuck waiting here
    await Future.wait<void>(<Future<void>>[
      stdoutSubscription.asFuture<void>(),
      stderrSubscription.asFuture<void>(),
    ]);

    unawaited(stdoutSubscription.cancel());
    unawaited(stderrSubscription.cancel());

    return process;
  }
```

Then, let's say I changed this to use `_processUtils.streamProcess`
```dart
_usbDeviceObserveProcess = await _processUtils.streamProcess( 
   args,
 ); 
  
  // This will not be reached until `_usbDeviceObserveProcess` is exited
 _wifiDeviceObserveProcess = await _processUtils.streamProcess( 
   args,
 ); 
 ```
 
In the above, `_wifiDeviceObserveProcess` will not be set until the `_usbDeviceObserveProcess` is exited, which isn't what we want. We want them to run simultaneously. Plus, hypothetically, these processes should run forever and never exit so it prevents it from listening for wifi connections because it's stuck there. Using unawaited to workaround it would also be problematic because `_usbDeviceObserveProcess` and `_wifiDeviceObserveProcess` are not actually set until they complete, which means they can't be killed

Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart]: > So `_processUtils.stream` waits for the process to exit before returning:

Ah, I get it.  Thanks for explaining, I'm sure it's really obvious when you're stepping though it 🙂

**Comment by jmagman** [comment]
Unfortunately you're hitting https://github.com/flutter/flutter/issues/124128
```
 06:24 +45 ~3 -2: test/integration.shard/debug_adapter/flutter_adapter_test.dart: launch can run and terminate a Flutter app in noDebug mode [E]                                                        
   Expected: [
               'Launching lib/main.dart on Flutter test device in debug mode...',
               'topLevelFunction',
               'Application finished.',
               '',
               <a string starting with 'Exited'>
             ]
     Actual: [
               'material_color_utilities 0.2.0 (0.3.0 available)',
               'Got dependencies!',
               'Launching lib/main.dart on Flutter test device in debug mode...',
               'topLevelFunction',
               'Application finished.',
               '',
               'Exited.'
             ]
      Which: at location [0] is 'material_color_utilities 0.2.0 (0.3.0 available)' instead of 'Launching lib/main.dart on Flutter test device in debug mode...'
   
   package:matcher                                                       expect
   test/integration.shard/debug_adapter/test_support.dart 49:5           expectLines
   test/integration.shard/debug_adapter/flutter_adapter_test.dart 128:7  main.<fn>.<fn>
```

**Comment by vashworth** [comment]
> Unfortunately you're hitting #124128
Oof, I'll try re-running it
