### PR TITLE
✏️ Correct test description for a non-draggable item

### LINKED ISSUE #94166: Wrong test descriptions for the non draggable items in `reorderable_list_test.dart`
## Use case

In the file [`flutter/packages/flutter/test/widgets/reorderable_list_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/reorderable_list_test.dart) . There are 2 typos in the test group `'ReorderableDragStartListener'` and `'ReorderableDelayedDragStartListener'`.

The test description at the line `644`:
https://github.com/flutter/flutter/blob/6c1455a23ae53ec3a92be8f50a798d6c789b471f/packages/flutter/test/widgets/reorderable_list_test.dart#L644
should be `"It should not allow the item to be dragged when enabled is false"`.

and 
 
The test description at the line `740`:
https://github.com/flutter/flutter/blob/6c1455a23ae53ec3a92be8f50a798d6c789b471f/packages/flutter/test/widgets/reorderable_list_test.dart#L740
should be `"It should not allow the item to be dragged when enabled is false"`.

Those typos were introduced in https://github.com/flutter/flutter/pull/81396.

## Proposal

The test descriptions should be renamed `"It should not allow the item to be dragged when enabled is false"`.

---

PS: I wasn't too sure which issue template I should have used, what was the correct one?

### PR DESCRIPTION
**Pull request by ValentinVignal**
This PR fixes the incorrect tests description about the `enabled = false` parameter of the `ReorderableDragStartListener` and `ReorderableDelayedDragStartListener`.

Fixes https://github.com/flutter/flutter/issues/94166.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -679,7 +679,7 @@ void main() {
       await tester.pump(kLongPressTimeout);
 
       // Drag enough to move down the first item
-      await drag.moveBy(const Offset(0, 150));
+      await drag.moveBy(const Offset(0, 50));
```
Comment (ValentinVignal) [inline packages/flutter/test/widgets/reorderable_list_test.dart:682]: This is to match the value at the line `635`
https://github.com/flutter/flutter/blob/6c1455a23ae53ec3a92be8f50a798d6c789b471f/packages/flutter/test/widgets/reorderable_list_test.dart#L635

It was first `150` in both tests because of a bug discussed in https://github.com/flutter/flutter/pull/81396 and solved in https://github.com/flutter/flutter/pull/82296. However, this value was not updated during https://github.com/flutter/flutter/pull/82296 to match its related test.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@darrenaustin Can you do a secondary review on this one?

**Review by Piinks — APPROVED** [review]
This LGTM, thanks for updating this! Can you update your branch with the latets from master to resolve the CI issue? Thanks!

**Comment by ValentinVignal** [comment]
@Piinks I merged the latest `master` in https://github.com/flutter/flutter/pull/94167/commits/c9a6c934a122bb7efea52edb2001197e62d50b3f
