### PR TITLE
Fix semantics compiler for offstage children

### LINKED ISSUE #20313: NPE during rendering - width accessed on a null reference
I saw this happen when clicking around in our app. It seems like it happened during a screen transition when we popped a route. Unfortunately I've not been able to repro. Thought I'd file this anyways in case you've seen anything similar in the past. Feel free to close if it's not helpful.

```
08-07 16:42:20.020 15663 15681 I flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
08-07 16:42:20.021 15663 15681 I flutter : The following NoSuchMethodError was thrown during a scheduler callback:
08-07 16:42:20.021 15663 15681 I flutter : The getter 'width' was called on null.
08-07 16:42:20.021 15663 15681 I flutter : Receiver: null
08-07 16:42:20.021 15663 15681 I flutter : Tried calling: width
08-07 16:42:20.021 15663 15681 I flutter : 
08-07 16:42:20.021 15663 15681 I flutter : When the exception was thrown, this was the stack:
08-07 16:42:20.022 15663 15681 I flutter : #0      Offset.& (dart:ui/geometry.dart:290)
08-07 16:42:20.022 15663 15681 I flutter : #1      RenderBox.get:semanticBounds (package:flutter/src/rendering/box.dart:1620)
08-07 16:42:20.022 15663 15681 I flutter : #2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:3401)
08-07 16:42:20.022 15663 15681 I flutter : #3      new _SemanticsGeometry. (package:flutter/src/rendering/object.dart:3359)
08-07 16:42:20.022 15663 15681 I flutter : #4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3272)
08-07 16:42:20.022 15663 15681 I flutter : #5      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
08-07 16:42:20.022 15663 15681 I flutter : #6      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:144)
08-07 16:42:20.022 15663 15681 I flutter : #7      _GrowableList.addAll (dart:core/runtime/libgrowable_array.dart:194)
08-07 16:42:20.022 15663 15681 I flutter : #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3298)
08-07 16:42:20.022 15663 15681 I flutter : #9      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
08-07 16:42:20.022 15663 15681 I flutter : #10     Iterable.get:single (dart:core/iterable.dart:552)
08-07 16:42:20.022 15663 15681 I flutter : #11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2334)
08-07 16:42:20.022 15663 15681 I flutter : #12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887)
08-07 16:42:20.022 15663 15681 I flutter : #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274)
08-07 16:42:20.022 15663 15681 I flutter : #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627)
08-07 16:42:20.022 15663 15681 I flutter : #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
08-07 16:42:20.022 15663 15681 I flutter : #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
08-07 16:42:20.022 15663 15681 I flutter : #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
08-07 16:42:20.023 15663 15681 I flutter : #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
08-07 16:42:20.023 15663 15681 I flutter : #19     CoreActivityZoneImpl._run.<anonymous closure> (package:ads.acx2.tracking.activity.core.zone/zone.dart:200)
08-07 16:42:20.023 15663 15681 I flutter : #22     CoreActivityZoneImpl._run (package:ads.acx2.tracking.activity.core.zone/zone.dart:197)
08-07 16:42:20.023 15663 15681 I flutter : #25     _invoke (dart:ui/hooks.dart:127)
08-07 16:42:20.023 15663 15681 I flutter : #26     _drawFrame (dart:ui/hooks.dart:114)
08-07 16:42:20.023 15663 15681 I flutter : (elided 4 frames from package dart:async)
08-07 16:42:20.023 15663 15681 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/20313.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/object.dart [hunk 1]
```diff
@@ -2387,6 +2387,11 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   /// Updates the semantic information of the render object.
   void _updateSemantics() {
     assert(_semanticsConfiguration.isSemanticBoundary || parent is! RenderObject);
+    if (_needsLayout) {
+      // There's not enough information in this subtree to compute semantics.
+      // The subtree is probably currently offstage.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: offstage is the wrong word here, because the Offstage widget turns off painting but actually maintains layout.
Maybe "being kept alive by a viewport but not laid out" or something.

File: packages/flutter/lib/src/rendering/object.dart [hunk 2]
```diff
@@ -2414,10 +2420,24 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
     final Set<_InterestingSemanticsFragment> toBeMarkedExplicit = Set<_InterestingSemanticsFragment>();
     final bool childrenMergeIntoParent = mergeIntoParent || config.isMergingSemanticsOfDescendants;
 
+    // When set to true there's currently not enough information in this subtree
+    // to compute semantics. In this case the walk needs to be aborted and no
+    // SemanticsNodes in the subtree should be updated.
+    // This will be true for subtrees that are currently offstage.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: ditto

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -3109,6 +3133,17 @@ abstract class _SemanticsFragment {
   /// Returns [_InterestingSemanticsFragment] describing the actual semantic
   /// information that this fragment wants to add to the parent.
   Iterable<_InterestingSemanticsFragment> get interestingFragments;
+
+  /// Whether this fragment wants to abort the semantics walk because the
+  /// information in the tree aer not sufficient to calculate semantics.
+  ///
+  /// This happens for subtrees that are offstage and don't have updated layout
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: ditto

File: packages/flutter/lib/src/rendering/object.dart [hunk 4]
```diff
@@ -3392,6 +3427,40 @@ class _SwitchableSemanticsFragment extends _InterestingSemanticsFragment {
   bool get _needsGeometryUpdate => _ancestorChain.length > 1;
 }
 
+
+/// [_SemanticsFragment] used to indicate that the current information in this
+/// subtree are not sufficient to update semantics.
+///
+/// Anybody processing this [_SemanticsFragment] should abort the walk of the
+/// current subtree without updating any [SemanticsNode]s as there are no semantic
+/// information to compute. As a result, this fragment also doesn't cary any
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: cary -> carry

File: packages/flutter/lib/src/rendering/object.dart [hunk 5]
```diff
@@ -3392,6 +3427,40 @@ class _SwitchableSemanticsFragment extends _InterestingSemanticsFragment {
...
+/// semantics information either.
+class _AbortingSemanticsFragment extends _InterestingSemanticsFragment {
+
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: extraneous blank line

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/rendering/object.dart [hunk 6]
```diff
@@ -3109,6 +3134,17 @@ abstract class _SemanticsFragment {
   /// Returns [_InterestingSemanticsFragment] describing the actual semantic
   /// information that this fragment wants to add to the parent.
   Iterable<_InterestingSemanticsFragment> get interestingFragments;
+
+  /// Whether this fragment wants to abort the semantics walk because the
+  /// information in the tree aer not sufficient to calculate semantics.
```
Comment (tvolkert) [inline packages/flutter/lib/src/rendering/object.dart]: s/aer/is/

File: packages/flutter/lib/src/rendering/object.dart [hunk 7]
```diff
@@ -3109,6 +3134,17 @@ abstract class _SemanticsFragment {
...
+  ///
+  /// This happens for subtrees that are currently kept alive by a viewport but
+  /// not laid out.
+  ///
+  /// See alo:
```
Comment (tvolkert) [inline packages/flutter/lib/src/rendering/object.dart]: also

File: packages/flutter/lib/src/rendering/object.dart [hunk 8]
```diff
@@ -3392,6 +3428,39 @@ class _SwitchableSemanticsFragment extends _InterestingSemanticsFragment {
   bool get _needsGeometryUpdate => _ancestorChain.length > 1;
 }
 
+
+/// [_SemanticsFragment] used to indicate that the current information in this
+/// subtree are not sufficient to update semantics.
```
Comment (tvolkert) [inline packages/flutter/lib/src/rendering/object.dart]: s/are/is/

File: packages/flutter/lib/src/rendering/object.dart [hunk 9]
```diff
@@ -3392,6 +3428,39 @@ class _SwitchableSemanticsFragment extends _InterestingSemanticsFragment {
...
+///
+/// Anybody processing this [_SemanticsFragment] should abort the walk of the
+/// current subtree without updating any [SemanticsNode]s as there are no semantic
```
Comment (tvolkert) [inline packages/flutter/lib/src/rendering/object.dart]: s/are/is/

File: packages/flutter/test/rendering/object_test.dart [hunk 10]
```diff
@@ -15,6 +15,7 @@ void main() {
     });
     owner.ensureSemantics();
     renderObject.attach(owner);
+    renderObject.layout(const BoxConstraints.tightForFinite());  // semantics are only calculated if layout information are upto date.
```
Comment (tvolkert) [inline packages/flutter/test/rendering/object_test.dart]: s/upto/up to/

**Review by tvolkert — APPROVED** [review]
