### PR TITLE
Fix doc samples in ridgets/routes.dart

### LINKED ISSUE #85031: An annotation error in /widgets/routes.dart
location : [widgets/routes.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/routes.dart#L1060)  line `1060` ，and `1065`

`SlideTransition's` position should be a type of `Tween<Offset>`，not  `AlignmentTween ` or `TweenOffset `。
 
image

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/85031.

Turn them into snippets so they are analyzed and hopefully never break again.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -1393,34 +1420,48 @@ abstract class ModalRoute<T> extends TransitionRoute<T> with LocalHistoryRoute<T
...
+  ///   @override
+  ///   void didChangeDependencies() {
+  ///    super.didChangeDependencies();
+  ///    _route?.removeScopedWillPopCallback(askTheUserIfTheyAreSure);
+  ///    _route = ModalRoute.of(context);
+  ///    _route?.addScopedWillPopCallback(askTheUserIfTheyAreSure);
+  ///   }
   /// }
   /// ```
+  /// {@end-toll}
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart:1442]:
```suggestion
  /// {@end-tool}
```

**Review by chunhtai — APPROVED** [review]
LGTM
