### PR TITLE
[flutter_tools] Make flutter upgrade --verify-only display framework version differences instead of commit hashes

### LINKED ISSUE #69417: [flutter_tools] flutter upgrade --verify-only shows commit hashes instead of framework version
As per #68866, running `flutter upgrade --verify-only` should show the differences in the framework versions between any update and the one installed in the user's system.

However, it shows the commit hashes instead.

## Steps to Reproduce

Run `flutter upgrade --verify-only` when having an update available in the `master` channel.

**Expected results:** 
Running the above command shows the framework versions.
<pre>
A new version of Flutter is available on channel &lt;user channel&gt;

<b>The latest revision: &lt;update version&gt;</b>
Your current version: &lt;user installed version&gt;

To upgrade now, run "flutter upgrade".
</pre>

**Actual results:** 
Running the command shows the commit hashes.
<pre>
A new version of Flutter is available on channel master

<b>The latest revision: 18341efa2fb8c3570ca32e71d1a9da74e8b2cbf5</b>
Your current version: 8b9e9680d24ffd4b3dbfa216f5f64a0490088f45

To upgrade now, run "flutter upgrade".
</pre>
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.117, on Linux, locale en_IN.utf8)
    • Flutter version 1.24.0-4.0.pre.117 at /home/anurag/flutter_master
    • Framework revision 8b9e9680d2 (2 days ago), 2020-10-28 11:40:39 -0700
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/anurag/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/anurag/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-11-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.1
    • cmake version 3.18.3
    • ninja version 1.10.1
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Chromium 86.0.4240.111 Arch Linux

! Doctor found issues in 1 category.
```
</details>

### PR DESCRIPTION
**Pull request by royarg02**
## Description
This PR changes the display message when one runs `flutter upgrade --verify-only`, having an available update; namely, replacing the commit hashes with the framework versions.

## Related Issues
Fixes #69417.

## Tests
I modified:
 - Most tests in `upgrade_test.dart` which use `fetchLatestVersion`.
 - Some tests in `version_test.dart` that run `git tag --points-at` and `git describe...`
 - A test in `flutter_command_runner_test.dart` to check whether Flutter toJson o/p reports the flutter framework version.

## Checklist
Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
Did any tests fail when you ran them? Please read [Handling breaking changes].
- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by christopherfujino — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -115,8 +115,8 @@ class UpgradeCommandRunner {
     } else if (verifyOnly) {
       globals.printStatus('A new version of Flutter is available on channel ${flutterVersion.channel}\n');
       // TODO(fujino): use a [FlutterVersion] once that class supports arbitrary revisions.
-      globals.printStatus('The latest revision: $upstreamRevision', emphasis: true);
-      globals.printStatus('Your current version: ${flutterVersion.frameworkRevision}\n');
+      globals.printStatus('The latest version: ${gitTagVersion.frameworkVersionFor(upstreamRevision)}', emphasis: true);
```
[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:117]: So something like `git describe --tags --abbrev=0` would suffice? Seems working to me running in my cloned repo.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:117]: > So something like `git describe --tags --abbrev=0` would suffice? Seems working to me running in my cloned repo.

Unfortunately, if the commit in question is not a tagged commit, that will report the **nearest** tag. However, if a commit is 7 commits past version 1.2.3, it is not accurate to report that it as 1.2.3. What we need is to support constructing a `GitTagVersion` for a revision other than `HEAD`. Then I would update the function `Future<String> fetchRemoteRevision()` to instead be `Future<FlutterVersion> fetchLatestVersion()`.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:117]: The problem is that `GitTagVersion.determine()` has this line:

```
    final List<String> tags = _runGit(
      'git tag --points-at HEAD', processUtils, workingDirectory).trim().split('\n');
```

which hard-codes `HEAD`.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:117]: And then also the fallback at the end implicitly checks HEAD:

```
    // If we're not currently on a tag, use git describe to find the most
    // recent tag and number of commits past.
    return parse(
      _runGit(
        'git describe --match *.*.* --first-parent --long --tags',
        processUtils,
        workingDirectory,
      )
    );
```

[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:117]: >What we need is to support constructing a GitTagVersion for a revision other than HEAD.

Changing that would break most of the tests in `version_test.dart`.

>Then I would update the function Future<String> fetchRemoteRevision() to instead be Future<FlutterVersion> fetchLatestVersion().

Changing this would break tests at `upgrade_test.dart` as well.

I think this PR might be a breaking change.

**Comment by RoyARG02** [comment]
@christopherfujino I've changed `GitTagVersion` to be able to construct from a given revision, and likewise updated `Future<String> fetchRemoteRevision()` to `Future<FlutterVersion> fetchLatestVersion()`.

I've not updated the tests for now, which is why they are failing. Let me know your thoughts about the approach and then we can discuss on the tests.

**Comment by christopherfujino** [comment]
> @christopherfujino I've changed `GitTagVersion` to be able to construct from a given revision, and likewise updated `Future<String> fetchRemoteRevision()` to `Future<FlutterVersion> fetchLatestVersion()`.
> 
> I've not updated the tests for now, which is why they are failing. Let me know your thoughts about the approach and then we can discuss on the tests.

Sorry, I missed this. Taking a look now!

File: packages/flutter_tools/lib/src/version.dart [hunk 2]
```diff
@@ -67,13 +67,14 @@ class FlutterVersion {
   ///
   /// Call [fetchTagsAndUpdate] to update the version based on the latest tags
   /// available upstream.
-  FlutterVersion([this._clock = const SystemClock(), this._workingDirectory]) {
-    _frameworkRevision = _runGit(
+  FlutterVersion([this._clock = const SystemClock(), this._workingDirectory, this._frameworkRevision]) {
+    // If _frameworkRevision is null, assume HEAD
+    _frameworkRevision = _frameworkRevision ?? _runGit(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/version.dart:72]: You can use the `??=` operator here, like: `_frameworkRevision ??= _runGit(`

File: packages/flutter_tools/lib/src/version.dart [hunk 3]
```diff
@@ -748,7 +749,7 @@ class GitTagVersion {
   /// The git tag that is this version's closest ancestor.
   final String gitTag;
 
-  static GitTagVersion determine(ProcessUtils processUtils, {String workingDirectory, bool fetchTags = false}) {
+  static GitTagVersion determine(ProcessUtils processUtils, {String workingDirectory, bool fetchTags = false, String commitHash}) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/version.dart:752]: Can I recommend you name this argument `String gitRef`, so as to be more general, if in the future we want to pass something other than a hash.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/version.dart:752]: And if you set the default value to be `'HEAD'`, then you don't have to do all the fallbacks in the rest of this function.

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 4]
```diff
@@ -107,16 +107,15 @@ class UpgradeCommandRunner {
...
+    if (flutterVersion.frameworkRevision == upstreamVersion.frameworkRevision) {
       globals.printStatus('Flutter is already up to date on channel ${flutterVersion.channel}');
       globals.printStatus('$flutterVersion');
       return;
     } else if (verifyOnly) {
       globals.printStatus('A new version of Flutter is available on channel ${flutterVersion.channel}\n');
-      // TODO(fujino): use a [FlutterVersion] once that class supports arbitrary revisions.
-      globals.printStatus('The latest revision: $upstreamRevision', emphasis: true);
-      globals.printStatus('Your current version: ${flutterVersion.frameworkRevision}\n');
+      globals.printStatus('The latest version: ${upstreamVersion.frameworkVersion}(revision ${upstreamVersion.frameworkRevisionShort})', emphasis: true);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/upgrade.dart:117]: Please add a space between the version and the parentheses here and on the next line. This currently looks like:

```
The latest version: 1.24.0-8.0.pre.5(revision 1f15046b93)
Your current version: 1.24.0-8.0.pre.6(revision bf0fc66cbf)
```

We should also ensure that in the unit tests we're asserting that this is formatted correctly.

**Review by christopherfujino — CHANGES_REQUESTED** [review]

**Comment by christopherfujino** [comment]
Also it looks like this branch has a merge conflict with upstream.

File: packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart [hunk 5]
```diff
@@ -113,8 +115,8 @@ void main() {
       );
       expect(await result, FlutterCommandResult.success());
       expect(testLogger.statusText, contains('A new version of Flutter is available'));
-      expect(testLogger.statusText, contains(fakeCommandRunner.remoteRevision));
-      expect(testLogger.statusText, contains(revision));
+      expect(testLogger.statusText, contains('The latest version: ${gitTagVersion.frameworkVersionFor(fakeCommandRunner.remoteRevision)}'));
```
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:118]: Everything here looks good, I think we just need to address this comment. I think the expectation text here should be raw strings, and not calling the methods. That way if someone inadvertently changes the behavior of these methods, the test will fail, signaling the change.

[the remark this answers is not in the document]
Comment (RoyARG02) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:118]: We're not using any defined `GitTagVersion` here, so the tests are showing the "version" as **`null`**.
```
The latest version: null (revision def456)
Your current version: null (revision abc123)
```
Although the file has this `GitTagVersion` instance, it is only used as an argument to `fakeCommandRunner.runCommand`:
https://github.com/flutter/flutter/blob/e4d94f7ccd3a0b93ae51e278ddc8b6b37ca33175/packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart#L29
The revision can be shown if we use `when(MockFlutterVersion().frameworkRevisionShort).thenReturn(revision)` either in the test or directly in `MockFlutterVersion`'s constructor:
```
class MockFlutterVersion extends Mock implements FlutterVersion {
  MockFlutterVersion({bool isStable = false, String revision}) : _isStable = isStable {
    //This is only for other tests which depend on FakeUpgradeCommandRunner.remoteRevision
    when(frameworkRevision).thenReturn(revision);
    when(frameworkRevisionShort).thenReturn(revision);
  }
```

**Comment by karamage** [comment]
I saw this PR and understood it.
I think your suggestion looks good.
Amend your suggestion to #68421.
Should I wait until this PR is merged?

**Comment by RoyARG02** [comment]
> Should I wait until this PR is merged?

@karamage I think it would be better if you do.

File: packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart [hunk 6]
```diff
@@ -113,15 +116,15 @@ void main() {
       );
       expect(await result, FlutterCommandResult.success());
       expect(testLogger.statusText, contains('A new version of Flutter is available'));
-      expect(testLogger.statusText, contains(fakeCommandRunner.remoteRevision));
-      expect(testLogger.statusText, contains(revision));
+      expect(testLogger.statusText, contains('The latest version: null (revision def456)'));
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:119]: Can you change this from `null` to an actual version tag? Your update to FakeUpgradeCommandRunner.fetchLatestVersion is constructing a new `MockFlutterVersion` on the fly, which is returning `null` when `.frameworkVersion` is invoked.

Comment (RoyARG02) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:119]: > Probably the easiest way to fix this is to set a new property on `FakeUpgradeCommandRunner` called `FlutterVersion frameworkVersion;` that can be optionally set in the constructor.

Could you elaborate how this would solve the problem? My understanding is that `MockFlutterVersion.frameworkVersion` is returning null as it is not assigned, and can be fixed by the `when`-`thenReturn` construct just like `frameworkRevision`.

Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:119]: In the tool code, we explicitly set mock return values in the test code, so that the mocked behavior is obvious when reading the test. It will make updating the test easier if, for example, the behavior of `fetchLatestVersion()` were to change in a future test.

Something like this:

```
class FakeUpgradeCommandRunner extends UpgradeCommandRunner {
  bool willHaveUncommittedChanges = false;
  bool alreadyUpToDate = false;

  String remoteRevision;
  FlutterVersion remoteVersion;

  @override
  Future<FlutterVersion> fetchLatestVersion() async => remoteVersion;
}
```

Comment (RoyARG02) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:119]: > In the tool code, we explicitly set mock return values in the test code

This snippet alongwith snippets in my previous comment show how that can be done:
```dart
const String revision = 'abc123';
const String upstreamRevision = 'def456';
const String version = '1.2.3';
const String upstreamVersion = '4.5.6';
when(flutterVersion.frameworkRevision).thenReturn(revision);
when(flutterVersion.frameworkRevisionShort).thenReturn(revision);
fakeCommandRunner.remoteVersion = upstreamVersion;
fakeCommandRunner.remoteRevision = upstreamRevision;
```
Also I have some issues with the snippet you've provided:
```dart
String remoteRevision;
FlutterVersion remoteVersion;

@override
Future<FlutterVersion> fetchLatestVersion() async => remoteVersion;
```
 - Making this change would require all tests to explicitly define `FakeUpgradeCommandRunner.remoteVersion`.
 - What do we assign to `FakeUpgradeCommandRunner.remoteVersion` in the tests, `MockFlutterVersion` or `FlutterVersion`?
 - If we assign `MockFlutterVersion`, we can just simply, for example, do:
```dart
MockFlutterVersion latestVersion = MockFlutterVersion();
when(latestVersion.frameworkRevision).thenReturn(upstreamRevision);
when(latestVersion.frameworkRevisionShort).thenReturn(upstreamRevision);
when(latestVersion.frameworkVersion).thenReturn(upstreamVersion);
fakeCommandRunner.remoteVersion = latestVersion;
```
or
```dart
fakeCommandRunner.remoteVersion = MockFlutterVersion(revision: remoteRevision, version: remoteVersion);
```
Having `FakeUpgradeCommandRunner.remoteRevision` will be redundant in either case.
- If we assign `FlutterVersion`, `processManager` would have additional instructions, and the expectation will fail. If we assign `MockFlutterVersion`, it will not have a "version" tagged by default unless we explicitly provide one using either of the two above.

I'm sorry that I cannot follow your approach, but could you provide me an example on how `FakeUpgradeCommandRunner.remoteRevision` would be used in the tests?

Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:119]: > > In the tool code, we explicitly set mock return values in the test code
> 
> This snippet alongwith snippets in my previous comment show how that can be done:
> 
> ```dart
> const String revision = 'abc123';
> const String upstreamRevision = 'def456';
> const String version = '1.2.3';
> const String upstreamVersion = '4.5.6';
> when(flutterVersion.frameworkRevision).thenReturn(revision);
> when(flutterVersion.frameworkRevisionShort).thenReturn(revision);
> fakeCommandRunner.remoteVersion = upstreamVersion;
> fakeCommandRunner.remoteRevision = upstreamRevision;
> ```
> 
> Also I have some issues with the snippet you've provided:
> 
> ```dart
> String remoteRevision;
> FlutterVersion remoteVersion;
> 
> @override
> Future<FlutterVersion> fetchLatestVersion() async => remoteVersion;
> ```
> 
> * Making this change would require all tests to explicitly define `FakeUpgradeCommandRunner.remoteVersion`.

If `runner.remoteVersion` isn't read in the test, it does not need to be set, right? We can leave it null. If it IS read during the test, we should force the test author to explicitly set the property with a mock object, to ensure that we don't get false positives for new tests. Where possibly, we try to write our tests so that behavior that isn't explicitly set will fail the test, so that the author gets signal that they need to mock a certain behavior.

> * What do we assign to `FakeUpgradeCommandRunner.remoteVersion` in the tests, `MockFlutterVersion` or `FlutterVersion`?
> * If we assign `MockFlutterVersion`, we can just simply, for example, do:
> 
> ```dart
> MockFlutterVersion latestVersion = MockFlutterVersion();
> when(latestVersion.frameworkRevision).thenReturn(upstreamRevision);
> when(latestVersion.frameworkRevisionShort).thenReturn(upstreamRevision);
> when(latestVersion.frameworkVersion).thenReturn(upstreamVersion);
> fakeCommandRunner.remoteVersion = latestVersion;
> ```
> 
> or
> 
> ```dart
> fakeCommandRunner.remoteVersion = MockFlutterVersion(revision: remoteRevision, version: remoteVersion);
> ```

Yes, the former is more verbose. We favor longer tests with explicit mocked behavior. The former example is easier for a contributor to read and know exactly what is mocked test behavior. Consider, for example, a future test wants to ensure that a `frameworkRevisionShort` is a subset of `frameworkRevision`. It will be clear in the former implementation that both values are manually mocked, and how to update the test.

> * If we assign `FlutterVersion`, `processManager` would have additional instructions, and the expectation will fail. If we assign `MockFlutterVersion`, it will not have a "version" tagged by default unless we explicitly provide one using either of the two above.

This is a good point. You can go either way, but passing a `MockFlutterVersion` and mocking the return value of `frameworkVersion` would be easier. This would still ensure that we're reading the version label and interpolating it into stdout. If you want to pass a real `FlutterVersion`, you would need to update `FakeProcessManager`, with the method `processManager.addCommands()`.

**Comment by RoyARG02** [comment]
@christopherfujino I've updated the tests, PTAL when you have time.

**Comment by christopherfujino** [comment]
> @christopherfujino I've updated the tests, PTAL when you have time.

it looks like they're failing on CI: 
Screen Shot 2020-11-18 at 9 19 17 AM

**Comment by RoyARG02** [comment]
> it looks like they're failing on CI

Could you point out what is causing this problem? Or anything I should do in my fork?

**Comment by christopherfujino** [comment]
> Could you point out what is causing this problem? Or anything I should do in my fork?

I know the CI build logs are not exactly intuitive. This issue has more details about investigating test logs: https://github.com/flutter/flutter/issues/64208. Please try to investigate and resolve yourself. If you are still stuck, I will try to make time for this next week.

**Comment by jmagman** [comment]
> Could you point out what is causing this problem? Or anything I should do in my fork?

@RoyARG02 The CI logs are hard to navigate.  Your test failure is:
```
03:02 +425 ~4 -1: test/general.shard/runner/flutter_command_runner_test.dart: FlutterCommandRunner run version checks that Flutter toJson output reports the flutter framework version [E]             
  NoSuchMethodError: The getter 'exitCode' was called on null.
  Receiver: null
  Tried calling: exitCode
  dart:core                                                          Object.noSuchMethod
  package:flutter_tools/src/base/process.dart 153:37                 RunResult.exitCode
  package:flutter_tools/src/base/process.dart 429:47                 _DefaultProcessUtils.runSync
  package:flutter_tools/src/version.dart 656:23                      _runGit
  package:flutter_tools/src/version.dart 746:31                      GitTagVersion.determine
  package:flutter_tools/src/version.dart 70:36                       new FlutterVersion
  test/general.shard/runner/flutter_command_runner_test.dart         new FakeFlutterVersion
  test/general.shard/runner/flutter_command_runner_test.dart 136:44  main.<fn>.<fn>.<fn>.<fn>
  test/general.shard/runner/flutter_command_runner_test.dart 114:99  main.<fn>.<fn>.<fn>.<fn>
  test/src/context.dart 151:42                                       testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  test/src/context.dart 145:23                                       testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 150:29                 AppContext.run.<fn>
  package:flutter_tools/src/base/context.dart 150:7                  AppContext.run.<fn>
  dart:async                                                         runZoned
  package:flutter_tools/src/base/context.dart 149:18                 AppContext.run
  test/src/context.dart 140:30                                       testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                                         runZoned
  test/src/context.dart 138:18                                       testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 150:29                 AppContext.run.<fn>
  package:flutter_tools/src/base/context.dart 150:7                  AppContext.run.<fn>
  dart:async                                                         runZoned
  package:flutter_tools/src/base/context.dart 149:18                 AppContext.run
  test/src/context.dart 105:22                                       testUsingContext.<fn>.<fn>
  package:flutter_tools/src/context_runner.dart 67:18                runInContext.runnerWrapper
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncErrorWrapperHelper
  test/src/context.dart 140:30                                       testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                                         runZoned
  test/src/context.dart 138:18                                       testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 150:29                 AppContext.run.<fn>
  package:flutter_tools/src/base/context.dart 150:7                  AppContext.run.<fn>
  dart:async                                                         runZoned
  package:flutter_tools/src/base/context.dart 149:18                 AppContext.run
  test/src/context.dart 105:22                                       testUsingContext.<fn>.<fn>
  package:flutter_tools/src/context_runner.dart 67:18                runInContext.runnerWrapper
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  package:flutter_tools/src/context_runner.dart                      runInContext.runnerWrapper
  package:flutter_tools/src/base/context.dart 150:29                 AppContext.run.<fn>
  package:flutter_tools/src/base/context.dart 150:7                  AppContext.run.<fn>
  dart:async                                                         runZoned
  package:flutter_tools/src/base/context.dart 149:18                 AppContext.run
  package:flutter_tools/src/context_runner.dart 70:24                runInContext
  test/src/context.dart 104:11                                       testUsingContext.<fn>
  test/src/context.dart 103:21                                       testUsingContext.<fn>
  test/src/common.dart 192:18                                        test.<fn>
  test/src/common.dart 188:5                                         test.<fn>
```

You should be able to reproduce locally:
```
cd packages/flutter_tools 
flutter test test/general.shard
```

`The getter 'exitCode' was called on null.` usually means a process call was changed, but a testing mock wasn't updated.

File: packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart [hunk 7]
```diff
@@ -44,10 +44,15 @@ void main() {
       fakePlatform = FakePlatform()..environment = Map<String, String>.unmodifiable(<String, String>{
         'ENV1': 'irrelevant',
         'ENV2': 'irrelevant',
-      });
+      })..version = '1.2.3-dev-4.5';
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart:47]: I don't think this is necessary? The tests pass without it. And I'm not familiar the `version` property of `Platform`.

Comment (RoyARG02) [reply packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart]: Yes, it isn't. Probably a leftover I overlooked. I removed it.

**Review by christopherfujino — APPROVED** [review]
LGTM! Thanks so much for making this change, I know it wasn't easy to wrangle the tests.

**Comment by RoyARG02** [comment]
Thanks @christopherfujino for assisting me in landing this PR.
