### PR TITLE
fix mouse wheel scroll miscontrol of ScrollPosition.

### LINKED ISSUE #55362: Unexpected behaviour of SliverAppBar in NestedScrollView on Mouse Scroll
I'm attempting to build a webpage using `NestedScrollView`. But I'm encountering various issues when scrolling by mouse wheel:
- SliverAppBar instantly collapses (`pinned: true`) or disappears (`floating: true`) on single mouse scroll tick.
- `floating: true` does not "float" the SliverAppBar, even after setting `snap: true`, unlike #17518.
- Keeping SliverOverlapAbsorber/SliverOverlapInjector never collapses SliverAppBar when `pinned` and `floating` are both set to `true` (Removing it fixes this issue).

Except for the last issue and #17518, the above-mentioned issues are not exhibited when mouse hold-and-drag is used to scroll the NestedScrollView.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update **main.dart** as follows: ... 
```dart
import 'dart:math' as math;

import 'package:flutter/material.dart';

var rnd = math.Random(602);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (context, isInnerBoxScrolled) {
          return [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverAppBar(
                pinned: true,
                // floating: true,
                // snap: true,
                expandedHeight: 500.0,
                flexibleSpace: FlexibleSpaceBar(
                  title: Text(widget.title),
                ),
              ),
            ),
          ];
        },
        body: Builder(
          builder: (context) {
            return CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverFixedExtentList(
                  delegate: SliverChildBuilderDelegate(
                    (context, index) {
                      return Container(
                        color: Colors
                            .primaries[rnd.nextInt(Colors.primaries.length)],
                        alignment: Alignment.center,
                        child: Text('Element $index'),
                      );
                    },
                    childCount: 40,
                  ),
                  itemExtent: 200.0,
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
[  +25 ms] executing: [/home/anurag/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +80 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f35b673f2b7ea7800c97d9ec096153fcca6091f2
[   +1 ms] executing: [/home/anurag/flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +35 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-dev.5.0-82-gf35b673f2
[  +33 ms] executing: [/home/anurag/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/anurag/flutter_master/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +122 ms] executing: [/home/anurag/flutter_master/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +156 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: /home/anurag/Android/Sdk/platform-tools/adb devices -l
[ +154 ms] List of devices attached
                    192.168.31.70:5555     device product:aosp_tissot model:Mi_A1 device:tissot transport_id:1
[  +19 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +504 ms] Generating
/media/D/AndroidStudioProjects/snap_on_scroll/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistran
t.java
[ +328 ms] Launching lib/main.dart on Chrome in debug mode...
[ +201 ms] Updating assets
[ +210 ms] Syncing files to device Chrome...
[ +141 ms] Generating
/media/D/AndroidStudioProjects/snap_on_scroll/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistran
t.java
[ +105 ms] <- reset
[  +20 ms] /home/anurag/flutter_master/bin/cache/dart-sdk/bin/dart
/home/anurag/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/anurag/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.RSGRGE/app.dill --libraries-spec
file:///home/anurag/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages
/media/D/AndroidStudioProjects/snap_on_scroll/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code
,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
/tmp/flutter_tools.REABWD --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill --platform
file:///home/anurag/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +19 ms] <- compile org-dartlang-app:///web_entrypoint.dart
[+27336 ms] Syncing files to device Chrome... (completed in 27,602ms, longer than expected)
[   +2 ms] Synced 21.6MB.
[   +1 ms] <- accept
[ +508 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:38443/devtools/browser/80ca58d1-ecf2-4800-ab22-6679a6d28d3d
[+5565 ms] Debug service listening on ws://127.0.0.1:42357/YvfFBa7bUgE=

[+1537 ms] Debug service listening on ws://127.0.0.1:42357/YvfFBa7bUgE=
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +3 ms] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press
"R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".

```

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.82, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-6.0.pre.82 at /home/anurag/flutter_master
    • Framework revision f35b673f2b (3 days ago), 2020-04-19 02:45:01 +0530
    • Engine revision a5e0b2f2f2
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/anurag/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/anurag/Android/Sdk
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/brave.com/brave/brave

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (4 available)            
    • Mi A1      • 192.168.31.70:5555 • android-arm64  • Android 10 (API 29)
    • Linux      • Linux              • linux-x64      • Linux
    • Chrome     • chrome             • web-javascript • Brave Browser 81.1.7.98 unknown
    • Web Server • web-server         • web-javascript • Flutter Tools

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by YeungKC**
## Description

Trying to solve #55362 and #64266.

The handling of `PointerSignalEvent` in `Scrollable` is directly derived from the current `ScrollPosition.pixels` + delta, while `NestedScrollView` contains multiple `ScrollPosition`s, and `NestedScrollView` contains multiple `ScrollPosition`. It doesn't make sense to calculate the target value alone.
So I've changed it to pass the delta directly to `ScrollPosition` and let `ScrollPosition` handle it internally.

About #64266, The original `PointerSignalEvent` was handled by call `ScrollPosition.jumpTo` which did not update `ScrollDirection.forward` or `ScrollDirection.reverse`, now it is handled by call `ScrollPosition.jumpTo` which does not update `ScrollDirection.forward` or `ScrollDirection.reverse`. call `beginActivity`, now it will update `ScrollDirection.forward` normally.

Related Discord: https://discordapp.com/channels/608014603317936148/608018585025118217/755515518294687844

## Related Issues

Fixes #55362
#64266

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

- scrollable_test.dart
  - Holding scroll and Scroll pointer signal will update ScrollDirection.forward / ScrollDirection.reverse
- nested_scroll_view_test.dart
  - Holding scroll and Scroll pointer signal will update ScrollDirection.forward / ScrollDirection.reverse
  - Scroll Pointer signals should not cause overscroll

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
It looks like @dkwingsmt may be more familiar with the failing pointer tests here. 

Regarding writing a test for this, this test checks the pointer scroll event, we can modify this test to use a NestedScrollView and validate the behavior: https://github.com/flutter/flutter/blob/4299dd7843c197d110b69b2172b384701e7b0557/packages/flutter/test/widgets/scrollable_test.dart#L287

**Comment by Piinks** [comment]
> It doesn't make sense to calculate the target value alone.

Can you clarify? I am wondering if what we may need here is to deploy some of the `unnesting` methods in the NestedScrollView to calculate the 'true' position. I am not sure if that would work, but it may be a simpler approach that isn't breaking.

**Comment by YeungKC** [comment]
@Piinks 

Do you mean to leave `Scrollable` unchanged and have `_NestedScrollPosition` return 'true' pixels?

I think this may be difficult.
1. because `ScrollPosition.pixels` involves more code.
2. if we go to `Scrollable` and additionally determine `Position as _NestedScrollPosition`, this may not be very elegant.
3. Originally `Scrollable` used `Position.jumpTo`, which caused #64266 to occur.

**Comment by Piinks** [comment]
Ah ok. Do you think it is possible to separate this out into two pull requests? This appears to be trying to solve two different issues.

**Comment by YeungKC** [comment]
I don't think so, as `pointerScroll` instead of `jumpTo` is now the core code for the solution to both issues.

**Comment by Piinks** [comment]
> I don't think so, as `pointerScroll` instead of `jumpTo` is now the core code for the solution to both issues.

Is it possible you could add `pointerScroll` in one change, and then implement it additional changes to solve each issue? This will be much easier to review if it is only trying to solve one problem.

**Comment by YeungKC** [comment]
I don't think so, I don't think there's any other way, after adding `pointerScroll`, it actually solves two problems...

**Comment by YeungKC** [comment]
I may not have described it clearly before, but now I'll explain why not.

1. added `pointerScroll` to fix #55362 calculation error `pixels`, and now it's handled internally by `position`.
2. having also given it to internal handling, it also solves #64266, otherwise I would need to change the `jumpTo` code to add `updateUserScrollDirection`, as changing the `jumpTo` code would affect the expected effect of calling `jumpTo` properly.

So it can't be split into two PR. I hope I've made it clear to you this time.

cc @Piinks

**Comment by dkwingsmt** [comment]
I'm pretty sure the test failure is because of the design that relies on `scheduleMicrotask` in the constructor. The test does not clear microtasks, therefore the jump is not executed.

I'm not an expert in scrollables but I don't think it's a good design. I suppose `ScrollActivity` is designed to be passive, only triggers side effects when certain events come, instead of during constructor and starting its own microtask.

**Comment by YeungKC** [comment]
Thanks for the review, but regarding the `scheduleMicrotask` not executing, I debug 'Scroll pointer signals are handled on Fuchsia' test and adding the `scheduleMicrotask.callback` breakpoint, which I'm pretty sure has already been executed.

I may have a different opinion about `ScrollActivity`, because there is `BallisticScrollActivity`, `DrivenScrollActivity`, and also the callback to init async in the constructor, which shows that `ScrollActivity` It's not necessary or recommended to do it passively.

But I agree that `scheduleMicrotask` is probably not the best way to go.

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 1]
```diff
@@ -671,3 +671,45 @@ class DrivenScrollActivity extends ScrollActivity {
...
+  /// The offset of the scroll.
+  /// It will also act as [velocity].
+  final double delta;
+
+  //
+  bool _isScrolling = true;
+
+  @override
+  void dispatchOverscrollNotification(ScrollMetrics metrics, BuildContext context, double overscroll) {
+    OverscrollNotification(metrics: metrics, context: context, overscroll: overscroll, velocity: delta).dispatch(context);
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/scroll_activity.dart:704]: This seems wrong. A pointer scroll does not have a velocity, and should not trigger overscroll.

If you're trying to solve the problem that trackpad scroll gestures don't overscroll, this is not the way to do it; the reason for that is that OS-sourced gesture support (trackpad scroll, pinch, etc.) hasn't been implemented yet. The fact that trackpad scrolls currently send pointer events is a workaround for that currently-missing functionality, not the long-term solution.

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 2]
```diff
@@ -671,3 +671,45 @@ class DrivenScrollActivity extends ScrollActivity {
     return '${describeIdentity(this)}($_controller)';
   }
 }
+
+//// An activity that a scroll view based on delta
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/scroll_activity.dart:675]: IIRC there was logic in the scroll system that would cancel scroll activities when starting new ones; am I misremembering? If that's the case, won't a steady stream of small scroll events cause a bunch of cancellations of previous scroll events?

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 1 above)
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:704]: Understood, I'm ignoring the difference between the mouse wheel and the touchpad. I will make the changes.

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 2 above)
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/scroll_activity.dart:675]: I added log to observe and did not find what you are concerned about, scheduleMicrotask will execute before the next event arrives.

But this part needs to be redesigned because of the overscroll issue, and perhaps not using ScrollActivity would be a better option to avoid the overscroll issue with applyUserOffset.

**Comment by YeungKC** [comment]
Now it' s been updated and improved for testing.
I apologize for the delay of a few days.

**Comment by Piinks** [comment]
> Now it' s been updated and improved for testing.
> I apologize for the delay of a few days.

No worries! Thank you for continuing to work on this. Looking forward to checking it out!

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -1073,6 +1073,43 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+  void pointerScroll(double delta) {
+    assert(delta != 0.0);
+
+    delta = -delta;
+
+    goIdle();
+    updateUserScrollDirection(
+        delta > 0.0 ? ScrollDirection.forward : ScrollDirection.reverse);
+    if (_innerPositions.isEmpty) {
+      _outerPosition!.applyClampedDragUpdate(delta);
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1085]: A pointer scroll is not a drag event, and should not be implemented using drag logic.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 4]
```diff
@@ -761,6 +761,25 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  /// If this method changes the scroll position, a sequence of start/update/end
+  /// scroll notifications will be dispatched.
+  ///
+  /// [pointerScroll] is very similar to [jumpTo], but [pointerScroll] will
+  /// update [ScrollDirection.forward] / [ScrollDirection.reverse].
+  ///
+  /// This is usually used in processing pointer signals, where delta is given
+  /// to [ScrollPosition] to calculate target value sliding.
+  // TODO(YeungKC): On macOS, a distinction should be made between mouse wheel
+  //  events and touchpad events, which can trigger an overscroll.
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/scroll_position.dart:780]: TODOs related to trackpad scroll can refer to https://github.com/flutter/flutter/issues/23604

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 5]
```diff
@@ -761,6 +761,25 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  /// Any active animation is canceled. If the user is currently scrolling, that
+  /// action is canceled.
+  ///
+  /// If this method changes the scroll position, a sequence of start/update/end
+  /// scroll notifications will be dispatched.
+  ///
+  /// [pointerScroll] is very similar to [jumpTo], but [pointerScroll] will
+  /// update [ScrollDirection.forward] / [ScrollDirection.reverse].
+  ///
+  /// This is usually used in processing pointer signals, where delta is given
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/scroll_position.dart:777]: Why "usually"? In what circumstances would something specifically named `pointerScroll` be used other than for pointer scrolling?

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 6]
```diff
@@ -624,8 +623,8 @@ class ScrollableState extends State<Scrollable> with TickerProviderStateMixin, R
 
   // SCROLL WHEEL
 
-  // Returns the offset that should result from applying [event] to the current
-  // position, taking min/max scroll extent into account.
+  // Returns the offset that should result from applying [event] with axis and
+  // direction taken into account.
   double _targetScrollOffsetForPointerScroll(PointerScrollEvent event) {
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/scrollable.dart:628]: You've changed this from computing the target scroll offset to returning a modified delta; the name and description should be updated accordingly.

**Review by stuartmorgan-g — DISMISSED** [review]

**Comment by YeungKC** [comment]
Thanks, I'm still on holiday and will probably take some time out in a day or two to deal with it.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1085]: This might be ok, `applyClampedDragUpdate` just may not be an appropriate name anymore, maybe `applyClampedPositionUpdate`?
It follows the same conventions of calculating the target pixels and updating the scroll position just with extra logic to reconcile between the two positions. I don't see that it has any drag-specific behavior, nor is it much different from the implementation of `ScrollPositionWithSingleContext.pointerScroll` below.

Comment (YeungKC) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart]: I thought about changing the name, but [applyClampedDragUpdate] considered [ScrollPhysics], and I ended up creating an [applyClampedPointerSignalUpdate] to fix it.

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 6 above)
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/scrollable.dart]: I've changed it, but for some reason it's not marked Outdated.

**Review by Piinks — COMMENTED** [review]
Hi @YeungKC thanks for continuing to work on this! Can you update your pull request? It looks like there is a merge conflict currently.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 7]
```diff
@@ -370,6 +429,36 @@ void main() {
...
+    controller.addListener(() {
+      if(controller.position.userScrollDirection != ScrollDirection.idle)
+        lastUserScrollingDirection = controller.position.userScrollDirection;
+    });
+
+    await tester.drag(find.byType(NestedScrollView), const Offset(0.0, -20.0), touchSlopY: 0.0);
+
+    expect(lastUserScrollingDirection, ScrollDirection.reverse);
+
+    await tester.sendEventToBinding(testPointer.scroll(const Offset(0.0, 20.0)));
```
[the remark this answers is not in the document]
Comment (YeungKC) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:452]: Because I want to make sure that the mouse wheel logic doesn't have a different effect than the other sliding logic (except for acceleration and overscroll)

Now that doesn't seem like a very good practice, I will rewrite the correct test.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 8]
```diff
@@ -1070,6 +1070,43 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+        double outerDelta = delta > 0.0 ? 0 : innerDelta;
+        for (final _NestedScrollPosition position in _innerPositions) {
+            final double potentialOuterDelta =
+                position.applyClampedPointerSignalUpdate(innerDelta);
+            outerDelta = math.max(outerDelta, potentialOuterDelta);
+        }
+
+        // Scroll "down", Apply the maximum delta of innerPositions to
+        // outerPosition.
+        if (delta > 0.0 && outerDelta != 0.0)
```
[the remark this answers is not in the document]
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1103]: I will modify this section to include -delta logic.

About -delta since the delta of the mouse wheel is equal to the -delta of darg, -delta would ensure that the applyUserOffset and pointerScroll logics are structured the same and might be easier to understand, not sure what you think?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 9]
```diff
@@ -1079,29 +1079,29 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
     updateUserScrollDirection(
         delta > 0.0 ? ScrollDirection.forward : ScrollDirection.reverse);
     if (_innerPositions.isEmpty) {
-      _outerPosition!.applyClampedDragUpdate(delta);
```
Comment (mutza974-cmd) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: Thanks

**Review by mutza974-cmd — APPROVED** [review]
Thanks

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 10]
```diff
@@ -1491,7 +1491,6 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
 
   @override
   void pointerScroll(double delta) {
-    print('delta $delta');
```
Comment (mutza974-cmd) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: Thanks

**Review by mutza974-cmd — APPROVED** [review]
Thanks for all

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 10 above)
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart]: I plan to update the pr tonight, so please pause the review.

I'm sorry I accidentally submitted the debug code.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 11]
```diff
@@ -1384,6 +1441,32 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
     return 0.0;
   }
 
+
+  // Returns the amount of delta that was not used.
+  //
+  // Negative delta means going down (exposing stuff above), positive delta
+  // going up (exposing stuff below).
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1448]: This is a bit confusing, since the AxisDirection and GrowthDirection are also part of determining 'up' and 'down'. We can simplify this by saying a negative delta represents a forward ScrollDirection, while the positive would be a reverse ScrollDirection.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 12]
```diff
@@ -761,6 +761,24 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   @override
   void jumpTo(double value);
 
+  /// Jumps the scrolling position from current value to delta without animation
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:764]: Nit: This could be confused with the `jumpTo` method.
```suggestion
  /// Changes the scrolling position based on a pointer signal from current value to delta without animation
```

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 13]
```diff
@@ -761,6 +761,24 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  /// and without checking if new value is in range, taking min/max scroll
+  /// extent into account.
+  ///
+  /// Any active animation is canceled. If the user is currently scrolling, that
+  /// action is canceled.
+  ///
+  /// If this method changes the scroll position, a sequence of start/update/end
+  /// scroll notifications will be dispatched.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:772]: When would this not change the position? It says above that it will.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 14]
```diff
@@ -761,6 +761,24 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  ///
+  /// [pointerScroll] is very similar to [jumpTo], but [pointerScroll] will
+  /// update [ScrollDirection.forward] / [ScrollDirection.reverse].
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:775]:
```suggestion
  /// This method is very similar to [jumpTo], but [pointerScroll] will
  /// update the [ScrollDirection].
```

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 15]
```diff
@@ -761,6 +761,24 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+  ///
+  /// The method is used to process the pointer signal, where delta given
+  /// [ScrollPosition] the calculated target value to slide.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:778]: This appears to be covered above.
```suggestion
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 16]
```diff
@@ -1430,6 +1432,131 @@ void main() {
...
+    testWidgets('float with pointer signal', (WidgetTester tester) async {
+      final GlobalKey appBarKey = GlobalKey();
+      await tester.pumpWidget(buildFloatTest(
+        floating: true,
+        nestedFloat: true,
+        appBarKey: appBarKey,
+      ));
+
+      final Offset scrollEventLocation =
+      tester.getCenter(find.byType(NestedScrollView));
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:1444]: Nit:
```suggestion
      final Offset scrollEventLocation = tester.getCenter(find.byType(NestedScrollView));
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 17]
```diff
@@ -1430,6 +1432,131 @@ void main() {
...
+        tester.renderObject<RenderBox>(find.byType(AppBar)).size.height,
+        56.0,
+      );
+      verifyGeometry(key: appBarKey, paintExtent: 56.0, visible: true);
+
+      // Scroll away the outer scroll view and some of the inner scroll view.
+      // We will not scroll back the same amount to indicate that we are
+      // floating in before reaching the top of the inner scrollable.
+      await tester
+          .sendEventToBinding(testPointer.scroll(const Offset(0.0, 300.0)));
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:1462]: Nit:
```suggestion
      await tester.sendEventToBinding(testPointer.scroll(const Offset(0.0, 300.0)));
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 18]
```diff
@@ -1430,6 +1432,131 @@ void main() {
...
+      await tester.pump();
+      expect(find.text('Test Title'), findsNothing);
+      expect(find.text('Item 1'), findsNothing);
+      expect(find.text('Item 5'), findsOneWidget);
+      verifyGeometry(key: appBarKey, paintExtent: 0.0, visible: false);
+
+      // The outer scrollable should float back in, inner should not change
+      await tester
+          .sendEventToBinding(testPointer.scroll(const Offset(0.0, -50.0)));
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:1471]: Nit:
```suggestion
      await tester.sendEventToBinding(testPointer.scroll(const Offset(0.0, -50.0)));
```

Comment (Piinks) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:1471]: Also for the same ones below.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 19]
```diff
@@ -1906,6 +2165,115 @@ void main() {
...
+
+    await tester.tap(find.text('DD'));
+    await tester.pumpAndSettle();
+
+    await tester
+        .sendEventToBinding(testPointer.scroll(const Offset(0.0, 1000000.0)));
+    expect(find.text('ddd1'), findsOneWidget);
+  });
+
+  testWidgets('Scroll pointer signal', (WidgetTester tester) async{
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:2196]: What is this testing?

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 20]
```diff
@@ -1906,6 +2165,115 @@ void main() {
...
+    expect(find.text('bbb1'), findsNothing);
+    await tester.pump(const Duration(milliseconds: 250));
+    expect(
+      tester.renderObject<RenderBox>(find.byType(AppBar)).size.height,
+      200.0,
+    );
+
+    final TestPointer testPointer = TestPointer(1, ui.PointerDeviceKind.mouse);
+    // The offset is the responsibility of innerPosition.
+    // Related to https://github.com/flutter/flutter/issues/55362
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:2209]: We usually just add a single comment right at the top of the test
```suggestion
    // Regression test for https://github.com/flutter/flutter/issues/55362
```

**Review by Piinks — COMMENTED** [review]
This is looking really really great! Very close to being ready.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 21]
```diff
@@ -1072,6 +1072,63 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+    if (_innerPositions.isEmpty) {
+      // Does not enter overscroll.
+      _outerPosition!.applyClampedPointerSignalUpdate(delta);
+    } else if (delta > 0.0) {
+      // Dragging "up" - delta is positive
+      // Prioritize getting rid of any inner overscroll, and then the outer
+      // view, so that the app bar will scroll out of the way asap.
+      double outerDelta = delta;
+      for (final _NestedScrollPosition position in _innerPositions) {
+        if (position.pixels < 0.0) { // This inner position is in overscroll.
```
[the remark this answers is not in the document]
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1092]: But there are special circumstances that might still trigger it? Like the iPad touch screen and mouse wheel at the same time... (I know it's weird.)

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 11 above)
Comment (YeungKC) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1448]: Thank you for the suggestion.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 21 above)
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1092]: I see what you mean, nice catch!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
This LGTM! Thank you for your contribution! This is a really great change.

There are some merge conflicts that will need to be resolved before we can merge it in.

**Comment by Piinks** [comment]
Hey @YeungKC can you check your branch? It looks like there was an issue when you rebased.

**Comment by Piinks** [comment]
Hey @YeungKC I'm sorry to ask again, but can you update once more? It looks like your last update picked up a broken build that was fixed in https://github.com/flutter/flutter/pull/69426

**Comment by YeungKC** [comment]
It seems like I had already noticed it at the time, but at the time I wasn't sure if I was the only one experiencing the problem.

https://discord.com/channels/608014603317936148/613398423093116959/771433253529059438

It's updated now. I'm watching ci work.

**Comment by YeungKC** [comment]
There were still some problems before, but now it can be merged.

cc @Piinks
