### PR TITLE
[Material] Create a FloatingActionButton ThemeData and honor it within the FloatingActionButton

### LINKED ISSUE #28138: FloatingActionButton backgroundColor defaults to accentColor, foregroundColor also to accentColor.
## Steps to Reproduce

I don´t know if it´s my inability to understand all those "primary,accent,swatch,normal,..." color configurations, but i will try to explain what my problem is. I personally think it´s more like a bug or a missing feature than a question for stackoverflow.

Try this code:
https://gist.github.com/erikkubica/45fc8acdce1f8a25cd5258e8b3a0e1f3

Or:
1. Create an app where you will use primary red color (appbar, button bg, card), yellow for accent (icons, appbar title), black for general text, white/light grey for backgrounds like scaffold body.
2. Set AppBar BG color to red using using theme (primaryColor)
3. Set AppBar title color to yellow using theme (accentColor)
4. Set color of icons to same color as accentColor, since if primary color is used they will be invisible in AppBar
5. Create a floatingActionButton with an icon.
6. Icon in floatingActionButton is not visible because backgroundColor for the widget uses the ThemeData.accentColor, which is yellow, instead of the ThemeData.primaryColor

Both foreground and background defaults to accentColor. 

 ```
  /// The color to use when filling the button.
  ///
  /// Defaults to **[ThemeData.accentColor**] for the current theme.
  final Color backgroundColor;
```

I found similar issue with FlatButton in Dialog, by default color of text is accent color, which is yellow (on white background), if i override it to primary, it´s red, but I don´t want to have it red since the delete button next to it is red. So I need to set it to normal, so it´s black which is correct, but:

flat_button.dart:127
```dart
 textStyle: theme.textTheme.button.copyWith(color: buttonTheme.getTextColor(this)),
```

My theme:
```dart
buttonTheme: ButtonThemeData(
            textTheme: ButtonTextTheme.normal,
            buttonColor: primary, // Red
          ),

textTheme: TextTheme(
           ...
            button: TextStyle(color: black), // Black
          ),

new FlatButton(
              //textTheme: ButtonTextTheme.normal,
              child: new Text("Ponechať"),
              onPressed: () {
                Navigator.of(context).pop();
                onKeep();
              },
            )
```

In theory my FlatButton in the popup dialog should be black and or red. But it´s yellow the accent color. 

```
Analyzing [censored]...

   info - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) - lib\widgets\general\[censored]AppBar.dart:4:7 - must_be_immutable

1 issue found. (ran in 9.7s)

```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale sk-SK)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\erikk\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\erikk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • SM G950F • 988a163739344f4956 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

Thank you, so far I am loving Flutter

### LINKED ISSUE #28738: FloatingActionButton should be independently theme-able at the Theme or ThemeData level

### PR DESCRIPTION
**Pull request by clocksmith**
## Description

Adding a FloatingActionButtonThemeData so that FABs can be themed at the Theme level and independently. The properties that are now on the theme must be defaulted at the build level, in order to respect any contributing theme properties. Because of this, some tests had to be modified to look at properties after they are built. Also, since default behaviors are now tested in the FAB Theme test, some default tests in the FAB test no longer applied and were removed.

The themable properties are:
-backgroundColor
-foregroundColor
-elevation
-disabledElevation
-highlightElevation
-shape

## Related Issues

closes #28138
closes #28738

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

* This changes when the FloatingActionButton gets its default values from at construction time to at build time. I do not think this breaks anything beyond the tests that are updated.

### CODE REVIEW

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 1]
```diff
@@ -73,23 +74,21 @@ class FloatingActionButton extends StatelessWidget {
...
     @required this.onPressed,
     this.mini = false,
-    this.shape = const CircleBorder(),
+    this.shape,
     this.clipBehavior = Clip.none,
     this.materialTapTargetSize,
     this.isExtended = false,
-  }) : assert(elevation != null && elevation >= 0.0),
-       assert(highlightElevation != null && highlightElevation >= 0.0),
+  }) : assert(elevation == null || elevation >= 0.0),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Update the documentation above now that these 2 may be null

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 2]
```diff
@@ -105,24 +104,22 @@ class FloatingActionButton extends StatelessWidget {
...
-    this.shape = const StadiumBorder(),
+    this.shape,
     this.isExtended = true,
     this.materialTapTargetSize,
     this.clipBehavior = Clip.none,
     Widget icon,
     @required Widget label,
-  }) : assert(elevation != null && elevation >= 0.0),
-       assert(highlightElevation != null && highlightElevation >= 0.0),
+  }) : assert(elevation == null || elevation >= 0.0),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Same thing here, update the documentation above

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 3]
```diff
@@ -284,17 +292,28 @@ class FloatingActionButton extends StatelessWidget {
 
     result = RawMaterialButton(
       onPressed: onPressed,
-      elevation: elevation,
-      highlightElevation: highlightElevation,
-      disabledElevation: disabledElevation,
+      elevation: elevation
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button.dart]: I recommend pulling each of these pieces out into a variable like the `foregroundColor`, makes it easier to follow

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 4]
```diff
@@ -284,17 +292,28 @@ class FloatingActionButton extends StatelessWidget {
...
+        ?? floatingActionButtonTheme.elevation
+        ?? _defaultElevation,
+      highlightElevation: highlightElevation
+        ?? floatingActionButtonTheme.highlightElevation
+        ?? _defaultHighlightElevation,
+      disabledElevation: disabledElevation
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button.dart]: If you pull these into variables like I mentioned above, then this one can be simplified to just `disabledElevation ?? elevation`

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+
+/// Defines default property values for descendant [FloatingActionButton]
+/// widgets.
+///
+/// Descendant widgets obtain the current [FloatingActionButtonThemeData] object
+/// using `FloatingActionButtonThemeData.of(context)`. Instances of
+/// [FloatingActionButtonThemeData] can be customized with
+/// [FloatingActionButtonThemeData.copyWith].
+///
+/// Typically an [FloatingActionButtonThemeData] is specified as part of the
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: `a` instead of `an`

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+
+  /// Color to be used for the unselected, enabled floating action buttons's
+  /// background.
+  final Color backgroundColor;
+
+  /// Color to be used for the unselected, enabled floating action buttons's
+  /// foreground.
+  final Color foregroundColor;
+
+  /// The z-coordinate to be used for the unselected, enabled floating action \
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: The comment looks incorrect here, extra / and the word foreground.

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+  /// buttons's elevation foreground. .
+  final double elevation;
+
+  /// The z-coordinate to be used for the selected, enabled floating action
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: The comment looks incorrect here, extra / and the word foreground.

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 8]
```diff
@@ -0,0 +1,131 @@
...
+      return null;
+    return FloatingActionButtonThemeData(
+      backgroundColor: Color.lerp(a?.backgroundColor, b?.backgroundColor, t),
+      foregroundColor: Color.lerp(a?.foregroundColor, b?.foregroundColor, t),
+      elevation: lerpDouble(a?.elevation, b?.elevation, t),
+      highlightElevation: lerpDouble(a?.highlightElevation, b?.highlightElevation, t),
+      shape: ShapeBorder.lerp(a?.shape, b?.shape, t),
+    );
+  }
+  @override
```
Comment (rami-a) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: new line above

**Review by rami-a — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 1 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 2 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 3 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 4 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 5 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 7 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 8 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/material.dart [hunk 9]
```diff
@@ -55,6 +55,7 @@ export 'src/material/feedback.dart';
 export 'src/material/flat_button.dart';
 export 'src/material/flexible_space_bar.dart';
 export 'src/material/floating_action_button.dart';
+export 'src/material/floating_action_button_theme.dart';
```
Comment (willlarche) [inline packages/flutter/lib/material.dart]: Alphabetize below 'location'

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 10]
```diff
@@ -6,6 +6,7 @@ import 'dart:math' as math;
 
 import 'package:flutter/painting.dart';
 import 'package:flutter/rendering.dart';
+import 'package:flutter/src/material/floating_action_button_theme.dart';
```
Comment (willlarche) [inline packages/flutter/lib/src/material/floating_action_button.dart]: I wonder if we should have an umbrella header for themes. Or if material should be exporting them.

**Review by willlarche — COMMENTED** [review]
Not done with review yet.

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 10 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Would it be a breaking change if we tried to separate them?

File: packages/flutter/lib/material.dart (hunk 9 above)
Comment (clocksmith) [reply packages/flutter/lib/material.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 11]
```diff
@@ -319,10 +314,40 @@ class FloatingActionButton extends StatelessWidget {
...
+    final double elevation = this.elevation
+      ?? floatingActionButtonTheme.elevation
+      ?? _defaultElevation;
+    final double highlighElevation = this.highlightElevation
+      ?? floatingActionButtonTheme.highlightElevation
+      ?? _defaultHighlightElevation;
+    final double disabledElevation = this.disabledElevation ?? elevation;
+    final MaterialTapTargetSize materialTapTargetSize = this.materialTapTargetSize
+      ?? theme.materialTapTargetSize;
+    final TextStyle textStyle = theme.accentTextTheme.button.copyWith(
```
Comment (willlarche) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Is there no way to customize the textStyle on the widget?

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 7 above)
Comment (willlarche) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Why add 'foreground'?

File: packages/flutter/lib/src/material/theme_data.dart [hunk 12]
```diff
@@ -726,6 +736,7 @@ class ThemeData extends Diagnosticable {
     PageTransitionsTheme pageTransitionsTheme,
     AppBarTheme appBarTheme,
     BottomAppBarTheme bottomAppBarTheme,
+    FloatingActionButtonThemeData floatingActionButtonTheme,
```
Comment (willlarche) [inline packages/flutter/lib/src/material/theme_data.dart]: Put this under `buttonColor` or under `dialogTheme` so it's kinda alphabetical.

File: packages/flutter/test/material/floating_action_button_test.dart [hunk 13]
```diff
@@ -360,7 +391,7 @@ void main() {
     );
 
     expect(getFabWidget().isExtended, true);
-    expect(getFabWidget().shape, const StadiumBorder());
+    expect(getRawMaterialButtonWidget().shape, const StadiumBorder());
```
Comment (willlarche) [inline packages/flutter/test/material/floating_action_button_test.dart]: Add a test with a custom border shape.

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 14]
```diff
@@ -319,10 +314,40 @@ class FloatingActionButton extends StatelessWidget {
...
+  static const double _defaultElevation = 6;
+  static const double _defaultHighlightElevation = 12;
+  static const ShapeBorder _defaultShape = CircleBorder();
+  static const ShapeBorder _defaultExtendedShape = StadiumBorder();
+
   @override
   Widget build(BuildContext context) {
     final ThemeData theme = Theme.of(context);
-    final Color foregroundColor = this.foregroundColor ?? theme.accentIconTheme.color;
+    final FloatingActionButtonThemeData floatingActionButtonTheme = theme.floatingActionButtonTheme;
```
Comment (johnsonmh) [inline packages/flutter/lib/src/material/floating_action_button.dart]: I think you should use the `FloatingActionButtonThemeData.of(context)` constructor here.

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 15]
```diff
@@ -0,0 +1,136 @@
...
+  /// [ThemeData.floatingActionButtonTheme].
+  const FloatingActionButtonThemeData({
+    this.backgroundColor,
+    this.foregroundColor,
+    this.elevation,
+    this.highlightElevation,
+    this.shape,
+  });
+
+  /// Color to be used for the unselected, enabled floating action buttons's
```
Comment (johnsonmh) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: Probably good place to use brackets:

`[FloatingActionButton]s`

here and below

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 16]
```diff
@@ -0,0 +1,136 @@
...
+      foregroundColor,
+      elevation,
+      highlightElevation,
+      shape,
+    );
+  }
+
+  @override
+  bool operator ==(Object other) {
+    if (identical(this, other)) {
```
Comment (johnsonmh) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: I don't think these if's should have brackets

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#common-boilerplates-for-operator--and-hashcode

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#separate-the-if-expression-from-its-statement

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 17]
```diff
@@ -0,0 +1,140 @@
...
+  testWidgets('FloatingActionButton values take priority over FloatingActionButtonThemeData values when both properties are specified', (WidgetTester tester) async {
+    final Color backgroundColor = Color(0xBEEFBEEF);
+    final Color foregroundColor = Color(0xFACEFACE);
+    final double elevation = 7;
+    final double highlightElevation = 13;
+    final ShapeBorder shape = StadiumBorder();
+
+    await tester.pumpWidget(MaterialApp(
+      theme: ThemeData.fallback().copyWith(
+          floatingActionButtonTheme: FloatingActionButtonThemeData(
```
Comment (johnsonmh) [inline packages/flutter/test/material/floating_action_button_theme_test.dart]: nit: this should be 2 spaces indented.

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 18]
```diff
@@ -0,0 +1,136 @@
...
+///  * [ThemeData], which describes the overall theme information for the
+///    application.
+class FloatingActionButtonThemeData extends Diagnosticable {
+  /// Creates a theme that can be used for
+  /// [ThemeData.floatingActionButtonTheme].
+  const FloatingActionButtonThemeData({
+    this.backgroundColor,
+    this.foregroundColor,
+    this.elevation,
+    this.highlightElevation,
```
Comment (johnsonmh) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: It seems not that crazy to also include `disabledElevation` since the other two elevation params are theme-able?

**Review by johnsonmh — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 11 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: not currently

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 7 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: It is what its called in the FloatingActionButton constructor

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 14 above)
Comment (willlarche) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Why?

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 11 above)
Comment (willlarche) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Could you add a TODO for that?

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 18 above)
Comment (willlarche) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Agreed

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 7 above)
Comment (willlarche) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: I wonder if that's a typo. Makes no sense to me unless the shadows are multi-layered themselves. I know they are but not to the end developer.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 12 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/theme_data.dart]: Done

File: packages/flutter/test/material/floating_action_button_test.dart (hunk 13 above)
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_test.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 14 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: I think it was for consistency. Although, I do not think the .of(context) methods are even necessary for non-inherited widgets. But the other non-inherited widget FooTheme classes are already doing it.

File: packages/flutter/test/material/floating_action_button_theme_test.dart (hunk 17 above)
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 18 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 7 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: I also agree that color and backgroundColor would be the expected names, but I also do not think it should have different names between the Widget and the WidgetTheme(Data)

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 11 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: I could add a GH issue

Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: #29371

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 19]
```diff
@@ -114,67 +115,61 @@ class _DefaultHeroTag {
...
 
   /// Creates a wider [StadiumBorder]-shaped floating action button with
   /// an optional [icon] and a [label].
   ///
-  /// The [label], [elevation], [highlightElevation], [clipBehavior] and
-  /// [shape] arguments must not be null. Additionally, [elevation]
-  /// [highlightElevation], and [disabledElevation] (if specified) must be
-  /// non-negative.
+  /// The [label] and [clipBehavior] arguments must non-null. Additionally,
+  /// [elevation] [highlightElevation], and [disabledElevation] (if specified)
```
Comment (anticafe) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Hmm, I wonder if there should be a `,` between 2 words of `[elevation] [highlightElevation]` here?

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 20]
```diff
@@ -337,15 +364,12 @@ class FloatingActionButton extends StatelessWidget {
     result = RawMaterialButton(
       onPressed: onPressed,
       elevation: elevation,
-      highlightElevation: highlightElevation,
+      highlightElevation: highlighElevation,
```
Comment (anticafe) [inline packages/flutter/lib/src/material/floating_action_button.dart]: Oops, should it be `highlightElevation: highlightElevation` (with `t` at the end of `highligh`)?

Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: thanks!

File: packages/flutter/lib/src/material/floating_action_button.dart (hunk 19 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: thanks!

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 21]
```diff
@@ -0,0 +1,162 @@
+// Copyright 2019 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/material.dart';
+import 'package:flutter/rendering.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
```
Comment (HansMuller) [inline packages/flutter/test/material/floating_action_button_theme_test.dart]: Please add tests for the debugFillProperties method like:
https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/material_test.dart#L61
https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/material_test.dart#L73

**Review by HansMuller — COMMENTED** [review]
This looks pretty good, just some small stuff.

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 22]
```diff
@@ -0,0 +1,145 @@
...
+
+  /// The z-coordinate to be used for the selected, enabled
+  /// [FloatingActionButton]'s elevation foreground.
+  final double highlightElevation;
+
+  /// The shape to be used for the floating action button's [Material].
+  final ShapeBorder shape;
+
+  /// The [ThemeData.floatingActionButtonTheme] property of the ambient [Theme].
+  static FloatingActionButtonThemeData of(BuildContext context) {
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Wouldn't that mean creating a FloatingActionButtonTheme class with just this method in it? How would that class explain itself in doc comments?

How about dropping this method and just calling Theme.of(context).floatingActionButtonTheme directly, since its not actually an inherited widget (or even pretending to be one)?

File: packages/flutter/test/material/floating_action_button_test.dart [hunk 23]
```diff
@@ -153,9 +148,33 @@ void main() {
...
+        home: Scaffold(
+          floatingActionButton: FloatingActionButton(
+            onPressed: null,
+            disabledElevation: 0,
+          ),
+        ),
+      ),
+    );
+
+    expect(tester.widget<RawMaterialButton>(find.byType(RawMaterialButton)).disabledElevation, 0.0);
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_test.dart]: This one is for disabled elevation. The physical shape only carries one elevation, while the raw material button has both elevation and disabledElevation

[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_test.dart]: That being said, the physical shape should carry the correct disabled elevation since the onPressed is set to null. Updated

File: packages/flutter/test/material/floating_action_button_theme_test.dart (hunk 21 above)
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 24]
```diff
@@ -0,0 +1,162 @@
...
+  testWidgets('FloatingActionButton values take priority over FloatingActionButtonThemeData values when both properties are specified', (WidgetTester tester) async {
+    const Color backgroundColor = Color(0xBEEFBEEF);
+    const Color foregroundColor = Color(0xFACEFACE);
+    const double elevation = 7;
+    const double disabledElevation = 1;
+    const double highlightElevation = 13;
+    const ShapeBorder shape = StadiumBorder();
+
+    await tester.pumpWidget(MaterialApp(
+      theme: ThemeData.fallback().copyWith(
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 25]
```diff
@@ -0,0 +1,162 @@
...
+          ),
+          child: FloatingActionButton(
+            onPressed: () { },
+            child: const Icon(Icons.add),
+          ),
+        ),
+      ),
+    ));
+
+    expect(_getIconTheme(tester).data.color, const Color(0xFACEFACE));
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 26]
```diff
@@ -0,0 +1,162 @@
...
+          elevation: elevation,
+          disabledElevation: disabledElevation,
+          highlightElevation: highlightElevation,
+          shape: shape,
+        ),
+      ),
+    ));
+
+    expect(_getRawMaterialButton(tester).fillColor, backgroundColor);
+    expect(_getIconTheme(tester).data.color, foregroundColor);
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 27]
```diff
@@ -0,0 +1,162 @@
...
+      home: Scaffold(
+        floatingActionButton: FloatingActionButton(
+          onPressed: () { },
+          child: const Icon(Icons.add),
+        ),
+      ),
+    ));
+
+    expect(_getRawMaterialButton(tester).fillColor, backgroundColor);
+    expect(_getIconTheme(tester).data.color, foregroundColor);
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 28]
```diff
@@ -0,0 +1,162 @@
...
+          onPressed: () { },
+          child: const Icon(Icons.add),
+        ),
+      ),
+    ));
+
+    // The color scheme values are guaranteed to be non null since the default
+    // [ThemeData] creates it with [ColorScheme.fromSwatch].
+    expect(_getRawMaterialButton(tester).fillColor, ThemeData().colorScheme.secondary);
+    expect(_getIconTheme(tester).data.color, ThemeData().colorScheme.onSecondary);
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/test/material/floating_action_button_theme_test.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 29]
```diff
@@ -0,0 +1,145 @@
...
+        && otherData.elevation == elevation
+        && otherData.disabledElevation == disabledElevation
+        && otherData.highlightElevation == highlightElevation
+        && otherData.shape == shape;
+  }
+
+  @override
+  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
+    super.debugFillProperties(properties);
+    final FloatingActionButtonThemeData defaultData = FloatingActionButtonThemeData();
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 30]
```diff
@@ -0,0 +1,145 @@
...
+      backgroundColor: backgroundColor ?? this.backgroundColor,
+      foregroundColor: foregroundColor ?? this.foregroundColor,
+      elevation: elevation ?? this.elevation,
+      disabledElevation: disabledElevation ?? this.disabledElevation,
+      highlightElevation: highlightElevation ?? this.highlightElevation,
+      shape: shape ?? this.shape,
+    );
+  }
+
+  static FloatingActionButtonThemeData lerp(FloatingActionButtonThemeData a, FloatingActionButtonThemeData b, double t) {
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 31]
```diff
@@ -0,0 +1,145 @@
...
+
+  /// The shape to be used for the floating action button's [Material].
+  final ShapeBorder shape;
+
+  /// The [ThemeData.floatingActionButtonTheme] property of the ambient [Theme].
+  static FloatingActionButtonThemeData of(BuildContext context) {
+    return Theme.of(context).floatingActionButtonTheme;
+  }
+
+  /// Creates a copy of this object but with the given fields replaced with the
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 32]
```diff
@@ -0,0 +1,145 @@
+// Copyright 2019 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:ui' show lerpDouble;
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter/material.dart';
+import 'package:flutter/widgets.dart';
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button.dart [hunk 33]
```diff
@@ -319,10 +314,42 @@ class FloatingActionButton extends StatelessWidget {
...
+      ?? theme.colorScheme.secondary;
+    final Color foregroundColor = this.foregroundColor
+      ?? floatingActionButtonTheme.foregroundColor
+      ?? theme.accentIconTheme.color
+      ?? theme.colorScheme.onSecondary;
+    final double elevation = this.elevation
+      ?? floatingActionButtonTheme.elevation
+      ?? _defaultElevation;
+    final double disabledElevation = this.disabledElevation
+        ?? floatingActionButtonTheme.disabledElevation
```
[the remark this answers is not in the document]
Comment (clocksmith) [reply packages/flutter/lib/src/material/floating_action_button.dart]: Done

File: packages/flutter/lib/src/material/floating_action_button_theme.dart (hunk 22 above)
[the remark this answers is not in the document]
Comment (HansMuller) [reply packages/flutter/lib/src/material/floating_action_button_theme.dart]: Calling Theme.of(context).floatingActionButtonTheme directly would be much better, yes!

File: packages/flutter/lib/src/material/floating_action_button_theme.dart [hunk 34]
```diff
@@ -0,0 +1,142 @@
...
+import 'dart:ui' show lerpDouble;
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter/rendering.dart';
+
+/// Defines default property values for descendant [FloatingActionButton]
+/// widgets.
+///
+/// Descendant widgets obtain the current [FloatingActionButtonThemeData] object
+/// using `FloatingActionButtonThemeData.of(context)`. Instances of
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/floating_action_button_theme.dart]: Theme.of(context).floatingActionButtonTheme

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 35]
```diff
@@ -0,0 +1,200 @@
...
+
+    expect(_getRawMaterialButton(tester).shape, customShape);
+  });
+
+  testWidgets('default FloatingActionButton debugFillProperties', (WidgetTester tester) async {
+    final DiagnosticPropertiesBuilder builder = DiagnosticPropertiesBuilder();
+    const FloatingActionButtonThemeData ().debugFillProperties(builder);
+
+    final List<String> description = builder.properties
+        .where((DiagnosticsNode node) => !node.isFiltered(DiagnosticLevel.info))
```
Comment (HansMuller) [inline packages/flutter/test/material/floating_action_button_theme_test.dart]: two space indent

File: packages/flutter/test/material/floating_action_button_theme_test.dart [hunk 36]
```diff
@@ -0,0 +1,200 @@
...
+      backgroundColor: Color(0xCAFECAFE),
+      foregroundColor: Color(0xFEEDFEED),
+      elevation: 23,
+      disabledElevation: 11,
+      highlightElevation: 43,
+      shape: BeveledRectangleBorder(),
+    ).debugFillProperties(builder);
+
+    final List<String> description = builder.properties
+        .where((DiagnosticsNode node) => !node.isFiltered(DiagnosticLevel.info))
```
Comment (HansMuller) [inline packages/flutter/test/material/floating_action_button_theme_test.dart]: two space indent

**Review by HansMuller — APPROVED** [review]
LGTM, please make the last 3 fixes before landing.
