### PR TITLE
Fix `paints..something` and `paints..everything` succeeding when they should fail

### LINKED ISSUE #95981: Testing via `paints..something()` cannot fail unless the predicate throws
The `_SomethingPaintPredicate`, which verifies that a custom painter draws at least one thing that matches a given predicate, is used in widget testing like this:

```dart
    expect(
      tester.renderObject(find.byType(CustomPaint)),
      paints..something((Symbol method, List<dynamic> arguments) {
        // return a bool based on whether the call matches expectations
      }),
    );
```

The description of the `something` method in the docs is as follows:

```dart
  /// ...
  /// If the predicate returns false, then the call is considered uninteresting
  /// and the predicate will be called again for the next [Canvas] call that was
  /// made by the [RenderObject] under test. If this was the last call, then the
  /// [paints] [Matcher] is considered to have failed.
  /// ...
  void something(PaintPatternPredicate predicate);
```

This would suggest that if the predicate were to, for example, always return `false`, then the expectation should fail, but the opposite happens—this test seems to always succeed unless the predicate throws. When I revert the change that was made to the `something` implementation in #90531, the test fails, which leads me to believe that that PR introduced some regression to how `_SomethingPaintPredicate` is supposed to work. (Edit: I think that PR did add a regression, but I think the implementation was also already not behaving the way the docs imply.)

## Steps to Reproduce

I've written below a code sample that, based on my understanding of how the `something` method works (and feel free to correct me if I'm just misreading the docs, in which case, this issue is that the docs are incorrect/unclear), should always fail, because the predicate always returns `false`.

1. Add the following test code sample in a new test file under `test/rendering/mock_canvas_test.dart`
2. Run `flutter test test/rendering/mock_canvas_test.dart`

**Expected results:** The test should fail

**Actual results:** The test succeeds

<details>
<summary>Code sample</summary>

```dart

// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

import 'mock_canvas.dart';

class MyPainter extends CustomPainter {
  const MyPainter({required this.color});

  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawColor(color, BlendMode.color);
  }

  @override
  bool shouldRepaint(MyPainter oldDelegate) {
    return true;
  }
}

@immutable
class MethodAndArguments {
  const MethodAndArguments(this.method, this.arguments);

  final Symbol method;
  final List<dynamic> arguments;

  @override
  bool operator ==(Object other) {
    if (!(other is MethodAndArguments && other.method == method)) {
      return false;
    }
    for (int i = 0; i < arguments.length; i++) {
      if (arguments[i] != other.arguments[i]) {
        return false;
      }
    }
    return true;
  }

  @override
  int get hashCode => method.hashCode;

  @override
  String toString() => '$method, $arguments';
}

void main() {
  testWidgets('I expect this test to fail', (WidgetTester tester) async {
    await tester.pumpWidget(
      const CustomPaint(
        painter: MyPainter(color: Colors.transparent),
        child: SizedBox(width: 50, height: 50),
      ),
    );

    final List<MethodAndArguments> methodsAndArguments = <MethodAndArguments>[];

    // I expect this to fail because the predicate always returns false
    expect(
      tester.renderObject(find.byType(CustomPaint)),
      paints..something((Symbol method, List<dynamic> arguments) {
        methodsAndArguments.add(MethodAndArguments(method, arguments));
        return false;
      }),
    );

    // The above step didn't fail, and this is verifying that the predicate
    // actually evaluated the following calls:
    expect(
      methodsAndArguments,
      <MethodAndArguments>[
        const MethodAndArguments(#save, <dynamic>[]),
        const MethodAndArguments(#drawColor, <dynamic>[Colors.transparent, BlendMode.color]),
      ],
    );
  });
}
```

</details>

<details>
  <summary>Logs</summary>
There is no app to run here, since this is a problem with tests. I ran the above test on the master branch with the following logs:

```
Will-Lockwood:flutter willlockwood$ flutter test test/rendering/mock_canvas_test.dart
00:03 +1: All tests passed! 
```

No analysis errors.

doctor:
```
[✓] Flutter (Channel unknown, 2.9.0-1.0.pre.129, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.129 at /Users/willlockwood/src/flutter
    • Upstream repository unknown
    • Framework revision 6ba2f526a4 (13 days ago), 2021-12-17 18:09:14 -0800
    • Engine revision 1db3b8333f
    • Dart version 2.16.0 (build 2.16.0-120.0.dev)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/willlockwood/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

### PR DESCRIPTION
**Pull request by willlockwood**
This PR fixes https://github.com/flutter/flutter/issues/95981

The current implementations of `paints..everything` and `paints..something` look incorrect when compared to how they're described in the docs. In short, my understanding is that these methods are supposed to behave as follows:

- `everything`: tests all calls until one returns false or throws, and only succeeds if all calls succeed
- `something`: tests all calls until one returns true or throws, and only fails if all calls fail

As of right now, this isn't what happens. Main differences:
1. `everything` skips the first call
2. `something` doesn't fail if all calls fail, but only if a call throws
3. `everything` doesn't fail if all calls fail, but only if a call throws

This is a WIP until I figure out the test failure I'm getting on `editable_text_test`. I think this test either always should've been failing, or regressed silently because of the errant `everything` implementation.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/rendering/mock_canvas.dart [hunk 1]
```diff
@@ -831,7 +835,11 @@ class _TestRecordingCanvasPatternMatcher extends _TestRecordingCanvasMatcher imp
       return false;
     } on String catch (s) {
       description.writeln(s);
-      description.write('The stack of the offending call was:\n${call.current.stackToString(indent: "  ")}\n');
+      try {
+        description.write('The stack of the offending call was:\n${call.current.stackToString(indent: "  ")}\n');
```
Comment (willlockwood) [inline packages/flutter/test/rendering/mock_canvas.dart:839]: `call.current` will throw if called after all calls have been evaluated

File: packages/flutter/test/rendering/mock_canvas.dart [hunk 2]
```diff
@@ -1422,23 +1435,29 @@ class _EverythingPaintPredicate extends _PaintPredicate {
...
-    assert(predicate != null);
-    while (call.moveNext()) {
+    do {
       final RecordedInvocation currentCall = call.current;
       if (!currentCall.invocation.isMethod)
         throw 'It called $currentCall, which was not a method, when the paint pattern expected a method call';
       if (!_runPredicate(currentCall.invocation.memberName, currentCall.invocation.positionalArguments))
         return;
-    }
+    } while (call.moveNext());
```
Comment (willlockwood) [inline packages/flutter/test/rendering/mock_canvas.dart:1444]: This fixes the fact that `everything` currently skips the first call

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 3]
```diff
@@ -2146,6 +2146,9 @@ void main() {
       // Text changed, prompt rect goes away.
       controller.text = '12345';
       await tester.pump();
+      // TODO: I think this test has been silently broken for a long time, because
+      // previously, paints..everything() was accidentally skipping every one if its
+      // first calls, and here, the first call fails the expectation
       verifyAutocorrectionRectVisibility(expectVisible: false);
```
Comment (willlockwood) [inline packages/flutter/test/widgets/editable_text_test.dart:2152]: @LongCatIsLooong any chance you could help give me some input on this? I see you wrote this test originally, and given the complexity of `EditableText`, I'm having a bit of trouble verifying that this is currently not working as expected. Basically, the issue is that here, by changing the text value on the controller, we're expecting there to be no drawn autocorrect prompt rect, but when you step through the painter calls here, we do see that this is painting a rect with the promptRectColor

Comment (willlockwood) [reply packages/flutter/test/widgets/editable_text_test.dart]: OK I think I got it, so feel free to give the test a look just to make sure the changes to the test make sense to you (and that they still test what it was testing before), but otherwise, I think this should be good 👍🏻

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_test.dart]: `EditableText` handles programmatically text changes (as in, `controller.text = '12345';`) slightly differently from user-initiated text changes (`await tester.enterText(find.byType(EditableText), '12345');`). Does the test still pass if you change this back to `controller.text = '12345';`?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 3 above)
Comment (willlockwood) [reply packages/flutter/test/widgets/editable_text_test.dart]: Right so that was the only way I was able to get it to pass—I just tried again and when I run it with `controller.text = '12345';` it fails, saying that the `RenderEditable` painted another rect (`Rect.fromLTRB(0.0, 0.0, 14.0,
14.0)`, which is the same shape of the autocorrect rects that are being drawn).

I did a bunch of stepping through breakpoints to see why it would happen when controlling the text directly vs based on users entering text, but ended up unable to figure it out. Just seemed like, for some reason, there was an extra build/paint happening

Comment (willlockwood) [reply packages/flutter/test/widgets/editable_text_test.dart]: And by the way, there is reason to think that this may have just been silently incorrect the whole time. This particular part of the test that was failing is using the `everything` method to test the painter, and up until I made these changes, the `everything` method was always skipping the first paint method. 

So it could very easily be the case that `EditableText` has always drawn the rect one more time before hiding it—the previous implementation of `everything` would have just been covering up that extra build/paint

**Review by Piinks — APPROVED** [review]
Nice! This LGTM as well! Thank you!

File: packages/flutter/test/rendering/mock_canvas.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/test/rendering/mock_canvas.dart:839]: Is there a way we can catch this without relying on catching a `TypeError`? Catching that would hide other errors we might introduce later...
