### PR TITLE
[CupertinoAlertDialog] Add tap-slide gesture

### LINKED ISSUE #19786: Implement correct iOS button press dynamics
I noticed a certain behavior in iOS alert dialogs when buttons are pressed. This behavior might be generic to iOS, or it might be specific to alert dialogs. Either way, the following behavior should be implemented.

**Dragging between buttons while pressed:**
Consider an alert dialog with an "OK" button and "Cancel" button sitting next to each other.  The user presses on the "OK" button causing that button to appear pressed. Then, while pressing on the "OK" button, the user drags over to the "Cancel" button. On iOS this causes the "OK" button to go back to the normal state, and causes the "Cancel" button to now appear pressed.  Moreover, if the user releases the "Cancel" button then the "Cancel" button receives the tap event.

The above tap/drag behavior is also true for vertical lists of buttons in an alert dialog.

**What about scrollable lists of buttons?**
If the buttons overflow and are scrollable then the behavior is different. When the user presses down on a button it causes the expected effect.  When the user starts dragging beyond the "slop" then the button press disappears and vertical scrolling begins.  This is a typical and expected behavior. I believe this is the behavior we have today. We need to make sure that this aspect of our behavior remains unchanged.

**What happens when the user presses multiple buttons with multiple fingers?**
TODO: I need to verify this on a physical device. Will update when I try it.

CC @Hixie @xster

### LINKED ISSUE #107371: CupertinoDialogAction is tappable even if onPressed is null
The code to reproduce is:

```dart
    showCupertinoDialog(
      context: context,
      useRootNavigator: true,
      builder: (_) => CupertinoAlertDialog(
        title: const Text('Delete account'),
        content: const Text('Are you sure you want to delete the account?'),
        actions: [
          CupertinoDialogAction(
            isDestructiveAction: true,
            child: const Text('Delete'),
          ),
          CupertinoDialogAction(
            isDefaultAction: true,
            child: const Text('Cancel'),
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(),
          ),
        ],
      ),
    );
```

Note the Delete button gets highlighted when tapping it, though it must be disabled completely.

<details>
  <summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-RU)
    • Flutter version 3.0.4 at /Users/andrey/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/andrey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 168FC36F-6574-46D2-B438-7737DE540BCB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 103.0.5060.114
    ! Error: Apple TV (3139) is not connected. Xcode will continue when Apple TV (3139) is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR adds "sliding tap" to `CupertinoAlertDialog` and fixes https://github.com/flutter/flutter/issues/19786. 

Much of the needed infrastructure has been implemented in https://github.com/flutter/flutter/pull/150219, but this time with a new challenge to support disabled buttons, i.e. the button should not show tap highlight when pressed (https://github.com/flutter/flutter/issues/107371).
* Why? Because whether a button is disabled is assigned to `CupertinoDialogAction`, while the background is rendered by a private class that wraps the action widget and built by the dialog body. We need a way to pass the boolean "enabled" from the child to the parent when the action is pressed. After much experimentation, I think the best way is to propagate this boolean using the custom gesture callback.
* An alternative way is to make the wrapper widget use an inherited widget, which allows the child `CupertinoDialogAction` to place a `ValueGetter<bool> getEnabled` to the parent as soon as it's mounted. However, this is pretty ugly...

This PR also fixes https://github.com/flutter/flutter/issues/107371, i.e. disabled `CupertinoDialogAction` no longer triggers the pressing highlight. However, while legacy buttons (custom button classes that are implemented by `GestureDetector.onTap`) still functions (their `onPressed` continues to work), disabled legacy buttons will still show pressing highlight, and there's no plan (actually, no way) to fix it. 

All tests related to sliding taps in `CupertinoActionSheet` has been copied to `CupertinoAlertDialog`, with additional tests for disabled buttons.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 1]
```diff
@@ -2026,37 +2041,60 @@ class _AlertDialogButtonBackground extends StatelessWidget {
...
+    }
   }
 
-  void onTapUp(TapUpDetails details) {
-    onPressStateChange?.call(false);
+  // |_SlideTarget|
+  @override
+  bool didEnter({required bool fromPointerDown, required bool innerEnabled}) {
+    widget.onPressStateChange?.call(innerEnabled);
+    if (innerEnabled) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/dialog.dart:2067]: nit: maybe && over nested ifs?

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 2]
```diff
@@ -2116,10 +2154,31 @@ class CupertinoDialogAction extends StatelessWidget {
...
 
-  /// Whether the button is enabled or disabled. Buttons are disabled by
-  /// default. To enable a button, set its [onPressed] property to a non-null
-  /// value.
-  bool get enabled => onPressed != null;
+  @override
+  State<CupertinoDialogAction> createState() => _CupertinoDialogActionState();
+}
+
+class _CupertinoDialogActionState extends State<CupertinoDialogAction>
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/dialog.dart:2161]: Is this going to be a leaf `_SlideTarget`? Since this is a public widget that takes a `Key`, I think it's possible for the `if (_currentTargets.firstOrNull != foundTargets.firstOrNull) ` check in `_updateDrag` to be false if a `CupertinoDialogAction` gets reparented while a "sliding" gesture is in progress?

Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/dialog.dart:2161]: Yeah it's technically possible. In fact, if the action buttons somehow moves (for example, if a button at the top expands by itself so that the highlighted button is moved out of the pointer position), the dialog will not re-perform hit tests without a pointer event and will not update.

However, in reality I can't imagine when this would happen. Completely solving this require the same logic as `MouseTracker`, which additionally performs a hit test per frame. I agree that it'd be a good idea to re-use the code from `MouseTracker` (or, better put, to conditionally enable hovering for touch events). However that's a really rare edge case and I suggest we leave to a future PR, such as as part of https://github.com/flutter/flutter/issues/19786. What do you think?

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/dialog.dart:2161]: Maybe add a "TODO"? 

>  which additionally performs a hit test per frame

I thought we are already doing that in the current implementation (in `_updateDrag`)? We are just not comparing the hit-testing paths in a per-entry fashion.

Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/dialog.dart:2161]: > Maybe add a "TODO"?

Sure!

> I thought we are already doing that in the current implementation

`_updateDrag` is only triggered every time the pointer moves. But if the app is updated without while the pointer stays still, then the pointer won't hit test the new layout. Really tricky situation.
