### PR TITLE
Fix experimental incremental web compiler for Windows

### LINKED ISSUE #45179: --enable-web-incremental-compiler is broken on Windows
StackTrace:

```
FileSystemException(uri=flutter%5Cbin%5Ccache%5Cflutter_web_sdk%5Ckernel%5Cflutter_ddc_sdk.dill; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      ProcessedOptions.loadSdkSummaryBytes (package:front_end/src/base/processed_options.dart:146:43)
#2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:175:52)
<asynchronous suspension>
#3      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#11     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:151:20)
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#13     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:428:59)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/45179

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 1]
```diff
@@ -79,11 +80,17 @@ class WebAssetServer {
       await response.close();
       return;
     }
+    // TODO(jonahwilliams): better path normalization in frontend_server to remove
+    // this workaround.
+    String requestPath = request.uri.path;
+    if (requestPath.startsWith('/C:/')) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: So, it won't work for '/D:/'? At home my C drive is full, so I mostly use D and E :smiley:

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Ahh, RegExp my old friend....
