### PR TITLE
[flutter_conductor] Re-enable codesign integration test

### LINKED ISSUE #83448: codesign_integration_test.dart failing after pub roll
on this PR: https://github.com/flutter/flutter/pull/83367

https://ci.chromium.org/p/flutter/builders/try/Mac%20framework_tests_misc/3196?

This test will likely need to be re-written.

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes: https://github.com/flutter/flutter/issues/83448

### CODE REVIEW

File: dev/conductor/lib/codesign.dart [hunk 1]
```diff
@@ -284,7 +284,7 @@ class CodesignCommand extends Command<void> {
     // First print all deviations from expectations
     if (unsignedBinaries.isNotEmpty) {
       stdio.printError('Found ${unsignedBinaries.length} unsigned binaries:');
-      unsignedBinaries.forEach(print);
```
Comment (christopherfujino) [inline dev/conductor/lib/codesign.dart:287]: this was leading to prints in test output

File: dev/conductor/lib/globals.dart [hunk 2]
```diff
@@ -50,23 +50,7 @@ Directory get localFlutterRoot {
   const FileSystem fileSystem = LocalFileSystem();
   const Platform platform = LocalPlatform();
 
-  // If a test
-  if (platform.script.scheme == 'data') {
```
Comment (christopherfujino) [inline dev/conductor/lib/globals.dart:54]: this code was broken by a pub rolling package:platform

**Review by jmagman — APPROVED** [review]
LGTM
