### PR TITLE
[flutter_tools] only try to take a screenshot from flutter drive if the --screenshot flag is passed

### LINKED ISSUE #123621: `flutter drive` crashes when taking a screenshot after a signal
```
Thread 0 main threadArgumentError: Invalid argument(s): Invalid type for "path": null
at FileSystem.getPath(file_system.dart:160)
at LocalFileSystem.directory(local_file_system.dart:23)
at ErrorHandlingFileSystem.directory(error_handling_io.dart:130)
at DriveCommand._takeScreenshot(drive.dart:446)
at DriveCommand._registerScreenshotCallbacks.<anonymous closure>(drive.dart:369)
at LocalSignals._handleSignal.<anonymous closure>(signals.dart:136)
at asyncGuard.<anonymous closure>(async_guard.dart:111)
at _rootRun(zone.dart:1398)
at _CustomZone.run(zone.dart:1300)
at _runZoned(zone.dart:1803)
at runZonedGuarded(zone.dart:1791)
at runZoned(zone.dart:1743)
at asyncGuard(async_guard.dart:109)
at LocalSignals._handleSignal(signals.dart:136)
at <asynchronous gap>(async)
```

It seems like there might be a race w.r.t. the order that signal handlers are run?

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/123621

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/drive.dart [hunk 1]
```diff
@@ -315,8 +315,10 @@ class DriveCommand extends RunCommandBase {
         profileMemory: stringArg('profile-memory'),
       );
 
-      // If the test is sent a signal or times out, take a screenshot
-      _registerScreenshotCallbacks(device);
+      if (screenshot != null) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/drive.dart:318]: This was the bug

**Review by Hixie — APPROVED** [review]
LGTM

I think the code would be clearer if the `screenshot` variable was called `screenshotDirectory` or something like that.
