### PR TITLE
Fix PageSelector, page selector gallery demo

### LINKED ISSUE #9432: Flutter gallery page selector demo does not work correctly
Pressing the demo's left/right arrows can easily get the PageSelector out of sync with the displayed page.

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes: https://github.com/flutter/flutter/issues/9432

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -877,25 +904,32 @@ class TabPageSelector extends StatelessWidget {
   ) {
     Color background;
     if (tabController.indexIsChanging) {
+      final double t = 1.0 - _indexChangeProgress(tabController);
       // The selection's animation is animating from previousValue to value.
-      if (tabController.index == tabIndex)
-        background = selectedColor.lerp(_indexChangeProgress(tabController));
+      if (tabController.index == tabIndex) {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: nit: braces

**Comment by Hixie** [comment]
LGTM

Why the indirection through the new widget?

Also, eventually we'll have to animate this as per the material spec's idea of [pagination circles](
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B1PhAWhtrRTrY1R3dldQWW5UNk0/patterns_usereducation_03_rotate_carousel.webm).

**Comment by HansMuller** [comment]
I mostly added the new widget to make it easier to write the tests.

I think writing a  pagination circles version of this would be fun.
