### PR TITLE
Detect exact device ID matches quickly

### LINKED ISSUE #44898: "flutter run -d chrome" error: Could not connect to lockdownd, error code -17, targeting iOS device instead of chrome
## Steps to Reproduce

1. `flutter run -d chrome`
2. `ideviceinfo`

I have also enabled my user_id's read&write in `/var/db/lockdown`. And I have also tried running the following command to fix the issue, but doesn't work.
```
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
brew install ideviceinstaller
```

## Logs
```
$ ideviceinfo
ERROR: Could not connect to lockdownd: Password protected (-17)
$ flutter run -d Chrome
$ flutter run -d Chrome
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17
```

```
$ flutter --verbose run -d Chrome
[  +30 ms] executing: [/Applications/Flutter/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 856a90e67c9284124d44d2be6c785bacd3a1c772
[        ] executing: [/Applications/Flutter/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.11.0-0-g856a90e
[  +11 ms] executing: [/Applications/Flutter/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Applications/Flutter/flutter/] git ls-remote --get-url
origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +60 ms] executing: [/Applications/Flutter/flutter/] git rev-parse
--abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +12 ms] executing: sw_vers -productName
[  +21 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +37 ms] executing: /usr/bin/xcode-select --print-path
[  +11 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[   +1 ms] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[ +375 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.2
           Build version 11B52
[  +70 ms] executing: /Users/*****/Library/Android/sdk/platform-tools/adb
devices -l
[  +17 ms] Exit code 0 from:
/Users/*****/Library/Android/sdk/platform-tools/adb devices -l
[   +1 ms] List of devices attached
[  +18 ms] executing:
/Applications/Flutter/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +253 ms] "flutter run" took 873ms.
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17
```

```
#0      IMobileDevice.getInfoForDevice
(package:flutter_tools/src/ios/mac.dart:224:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices
(package:flutter_tools/src/ios/devices.dart:190:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices
(package:flutter_tools/src/ios/devices.dart:115:57)
#3      PollingDeviceDiscovery.devices
(package:flutter_tools/src/device.dart:285:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices
(package:flutter_tools/src/device.dart:140:46)
<asynchronous suspension>
#5      DeviceManager.getDevicesById
(package:flutter_tools/src/device.dart:104:40)
<asynchronous suspension>
#6      DeviceManager.getDevices (package:flutter_tools/src/device.dart:129:11)
#7      DeviceManager.findTargetDevices
(package:flutter_tools/src/device.dart:173:34)
<asynchronous suspension>
#8      FlutterCommand.findAllTargetDevices
(package:flutter_tools/src/runner/flutter_command.dart:581:48)
<asynchronous suspension>
#9      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:286:21)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:531:11)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#18     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:446:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:222:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#32     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1500:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#44     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#47     main
(file:///Applications/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.d
art:8:3)
#48     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:303:32)
#49     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:12)
```

## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.11.0, on Mac OS X 10.15.1 19B88, locale en)
 
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/*****/Library/Android/sdk/tools/bin/sdkmanager"
        "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[!] Xcode - develop for iOS and macOS (Xcode 11.2)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.37.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17
```

### LINKED ISSUE #61466: Device discovery takes a long time, even when the targeted device is found immediately (flutter_tester, chrome, macos, linux, etc)
Currently all the device discovers are awaited, even if the targeted device is found immediately.
https://github.com/flutter/flutter/blob/f8135add8eb8d36a83616be17f5c55dcae70e698/packages/flutter_tools/lib/src/device.dart#L105-L106

https://github.com/flutter/flutter/blob/f8135add8eb8d36a83616be17f5c55dcae70e698/packages/flutter_tools/lib/src/device.dart#L137-L141

### PR DESCRIPTION
**Pull request by jmagman**
## Description

When a command is run with `--device` all relevant platform device discoverers gather all devices, which are then checked if the identifier or name exactly matches the specified device ID, then if they match the prefix of the specified device ID.  Some device discoverers with hard-coded return very quickly (`flutter-tester`, `chrome`, `macos`, `linux`), and others that shell out to underlying tools (Android, iOS, Fuschia) take much longer.

Instead of gathering all devices first, process them as they are discovered, and return quickly if an exact match is found.

Here are discovery times for exact matches on top of tree vs this PR (note these times include the overhead of calling a command I hacked the timing into, it's not how long this function took):
|   |master | PR   |
|---|---|---|
|flutter-tester   |1.49s |0.58s   |
|chrome   |1.51s |0.61s   |
|macos   |1.48s |0.59s   |
|iOS device identifier   |1.48s |1.27s   |

Before this change, all times were about the same, because it waited for all platform discoveries to be complete before matching.  After this change, the time takes as long as the relevant discoverer can return.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/61466
Fixes https://github.com/flutter/flutter/issues/44898
Relevant for https://github.com/flutter/flutter/issues/15072 increasing discovery times when an exact networking iOS ID is specified without regressing other platforms.

## Tests
`getDeviceById exact matcher` uses new `LongPollingDeviceDiscovery` that never finishes polling. Exact matches are still returned quickly. This test runs forever on master.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/device.dart [hunk 1]
```diff
@@ -112,14 +112,48 @@ abstract class DeviceManager {
...
+    // found quickly, we don't wait for all the discoverers to complete.
+    final List<Device> prefixMatches = <Device>[];
+    final Completer<Device> exactMatchCompleter = Completer<Device>();
+    final List<StreamSubscription<List<Device>>> futureDevices = <StreamSubscription<List<Device>>>[];
+    for (final DeviceDiscovery discoverer in _platformDiscoverers) {
+      futureDevices.add(
+        discoverer
+        .devices
+        .asStream()
+        .listen((List<Device> devices) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/device.dart:127]: I'd suggest investigating whether it makes sense to pass an `onError` callback to this `listen()`. If there is an error added to a `discoverer` stream, you probably don't want it to propagate asynchronously to the containing zone.

**Comment by jonahwilliams** [comment]
Very nice! I think you could construct a new test case that will now pass that would have failed. Consider two device discoverers, one returns instantly and one never returns.

File: packages/flutter_tools/lib/src/device.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/device.dart:127]: `discoverer.devices` is a `Future<List<Device>>`, I'm making it into a stream with `.asStream()`.  Are there cases there could be errors on that stream?  Streams give me heartburn.

Comment (jmagman) [reply packages/flutter_tools/lib/src/device.dart:127]: I just realized this doesn't need to be a stream at all.

**Comment by jmagman** [comment]
> Very nice! I think you could construct a new test case that will now pass that would have failed. Consider two device discoverers, one returns instantly and one never returns.

Done.

File: packages/flutter_tools/lib/src/device.dart [hunk 2]
```diff
@@ -112,14 +111,40 @@ abstract class DeviceManager {
...
+            if (startsWithDeviceId(device)) {
+              prefixMatches.add(device);
+            }
+          }
+          return null;
+        })
+    ];
+
+    // Wait for an exact match, or for all discoverers to return results.
+    await Future.any<dynamic>(<Future<dynamic>>[
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/device.dart:139]: The edge case Zach mentioned is a bit more obvious when streams aren't used. In this case, after  `Future.any` completes or on the first future, the second future may still complete w/error. That would cause an unhandled exception to be thrown into the zone.

You could simulate this a similar 2 discoverer setup where one throws an error after another turn.

Comment (jmagman) [reply packages/flutter_tools/lib/src/device.dart:142]: Done, added test for this as well.

File: packages/flutter_tools/lib/src/device.dart [hunk 3]
```diff
@@ -103,23 +103,51 @@ abstract class DeviceManager {
...
+              return null;
+            }
+            if (startsWithDeviceId(device)) {
+              prefixMatches.add(device);
+            }
+          }
+          return null;
+        }, onError: (dynamic error, StackTrace stackTrace) {
+          // Return matches from other discoverers even if one fails.
+          globals.printTrace('Ignored error discovering $deviceId: $error');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/device.dart:137]: I think this is almost the behavior we want, thought it's not quite the same as before. Previously if a discoverer crashed, we would surface that and go straight to crash logging. Especially if we don't match an exact device, knowing that some discovery has crashed is probably important, but I don't think that it should stop users from running on unrelated devices.

Unsure what the right solution is.

Comment (zanderso) [reply packages/flutter_tools/lib/src/device.dart:137]: Maybe if there is any error, and the target device isn't found, print an error directing the user to `flutter devices` or `flutter doctor --verbose`.

Comment (jmagman) [reply packages/flutter_tools/lib/src/device.dart:137]: I was happy with the old crashing behavior so we'd at least see it, but I'm still missing something related to why it matters why it's thrown into the zone.

> That would cause an unhandled exception to be thrown into the zone.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/device.dart:137]: I was actually wrong about this. Future.any will explicitly discard errors thrown by future's other than the first. I think what you have here is good

**Review by jonahwilliams — APPROVED** [review]
LGTM
