### PR TITLE
[flutter_tools] provide correct sources and metadata for different base hrefs

### LINKED ISSUE #69964: [tool_crash] StateError: Bad state: No element
## Command
```
flutter run -d chrome --verbose
```

## Steps to Reproduce
1. Create a new flutter web project with flutter beta
2. Change the base href in index.html from "/" to "/bo/" 
3. Run flutter run -d chrome
4. Flutter opens localhost:<randomport> but fails to load anything because of the wrong href
5. Append /bo/ to the URL in chrome and reload
6. Crash

Note: the same flutter web project works flawlessly with the default "/" base href.

## Logs
StateError: Bad state: No element
```
#0      List.last (dart:core-patch/growable_array.dart:255:5)
#1      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:95:35)
<asynchronous suspension>
#2      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#3      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#4      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#5      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#6      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:184:25)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /home/akos/bin/flutter_beta
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/akos/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin//java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 2 XL (mobile) • 803KPQJ1660092 • android-arm64  • Android 11 (API 30)
    • Web Server (web)    • web-server     • web-javascript • Flutter Tools
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 86.0.4240.183

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/69964

When the base href is not `/`, dwds forwards requests for these resources with the base href attached, for example `foo/sources`. The tool needs to remove the leading href similar to the other resource handlers

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 1]
```diff
@@ -561,18 +562,20 @@ class WebAssetServer implements AssetReader {
...
   Future<String> metadataContents(String serverPath) async {
+    serverPath = _stripBasePath(serverPath, basePath);
     if (serverPath == 'main_module.ddc_merged_metadata') {
       return _webMemoryFS.mergedMetadata;
     }
     if (_webMemoryFS.metadataFiles.containsKey(serverPath)) {
       return utf8.decode(_webMemoryFS.metadataFiles[serverPath]);
     }
-    return null;
+    throw Exception('Could not find metadata contents for $serverPath');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart:578]: I made this throw since in this case it would be a fatal error anyway.

**Review by zanderso — APPROVED** [review]
