### PR TITLE
Catch file system exception while looking for Android Studio on macOS.

### LINKED ISSUE #8395: Flutter doctor crashes if directory listing fails with permissions errors
Stack trace below.

The suspect dir has the following perms:

    ls -l /Applications/Utilities | grep monome
    drwx------  4 501   wheel  136 Jan  9  2016 monome

## command

flutter doctor

## exception

FileSystemException: Directory listing failed, path = '/Applications/Utilities/monome/' (OS Error: Permission denied, errno = 13)

```
dart:io                                                             _Directory.listSync
package:file/src/forwarding/forwarding_directory.dart 43            _LocalFileSystemEntity&ForwardingDirectory.listSync
package:flutter_tools/src/android/android_studio.dart 144           AndroidStudio._allMacOS._checkForStudio
package:flutter_tools/src/android/android_studio.dart 150           AndroidStudio._allMacOS._checkForStudio
package:flutter_tools/src/android/android_studio.dart 150           AndroidStudio._allMacOS._checkForStudio
package:flutter_tools/src/android/android_studio.dart 155           AndroidStudio._allMacOS
package:flutter_tools/src/android/android_studio.dart 134           AndroidStudio.allInstalled
package:flutter_tools/src/android/android_studio_validator.dart 23  AndroidStudioValidator.allValidators
package:flutter_tools/src/doctor.dart 63                            Doctor.validators
package:flutter_tools/src/doctor.dart 121                           Doctor.diagnose
package:flutter_tools/src/commands/doctor.dart 19                   DoctorCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148           FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119           FlutterCommand.run
package:args/command_runner.dart 194                                CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 224    FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                CommandRunner.run.<fn>
dart:async                                                          Future.Future.sync
package:args/command_runner.dart 109                                CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 151    FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                           main.<fn>.<fn>
package:stack_trace                                                 Chain.capture
package:flutter_tools/executable.dart 127                           main.<fn>
package:flutter_tools/src/base/context.dart 76                      AppContext._run
package:flutter_tools/src/base/context.dart 66                      AppContext.runInZone.<fn>
dart:async                                                          runZoned
package:flutter_tools/src/base/context.dart 65                      AppContext.runInZone
package:flutter_tools/executable.dart 98                            main
packages/flutter_tools/bin/flutter_tools.dart 8                     main
===== asynchronous gap ===========================
dart:async                                                          _Completer.completeError
package:flutter_tools/src/doctor.dart 149                           Doctor.diagnose
===== asynchronous gap ===========================
dart:async                                                          Future.Future.microtask
package:flutter_tools/src/doctor.dart                               Doctor.diagnose
package:flutter_tools/src/commands/doctor.dart 19                   DoctorCommand.runCommand
===== asynchronous gap ===========================
dart:async                                                          Future.Future.microtask
package:flutter_tools/src/commands/doctor.dart                      DoctorCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148           FlutterCommand.verifyThenRunCommand
===== asynchronous gap ===========================
dart:async                                                          _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart               FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119           FlutterCommand.run
package:args/command_runner.dart 194                                CommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                          Future.Future.microtask
package:args/command_runner.dart                                    CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 224    FlutterCommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                          _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart        FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                CommandRunner.run.<fn>
dart:async                                                          Future.Future.sync
package:args/command_runner.dart 109                                CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 151    FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                           main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                          Future.Future.microtask
package:flutter_tools/executable.dart                               main.<fn>.<fn>
package:stack_trace                                                 Chain.capture
package:flutter_tools/executable.dart 127                           main.<fn>
```

## flutter doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/pquitslund/src/git/clones/flutter
    • Framework revision eb839755b7 (45 minutes ago), 2017-02-24 08:11:08
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/pquitslund/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    ✗ ios-deploy not installed: 1.9.0 is required.
      Install via 'brew install ios-deploy'.
```

### PR DESCRIPTION
**Pull request by jakobr-google**
Fixes #8395.

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 1]
```diff
@@ -139,16 +139,20 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
+            .where((FileSystemEntity e) => e is Directory);
+        for (Directory directory in directories) {
+          if (directory.basename == 'Android Studio.app') {
+            candidatePaths.add(directory);
+          } else if (!directory.path.endsWith('.app')) {
+            _checkForStudio(directory.path);
+          }
         }
+      } catch (e) {
+        printTrace('Exception while looking for Android Studio: $e');
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: Maybe include the path we are in?

**Review by mravn-google — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 1 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: The exception does:
```
[  +51 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Users/jakobr/Applications/fisker/' (OS Error: Permission denied, errno = 13)
```
