### PR TITLE
prevent VsCode from crashing on malformed packages.json file

### LINKED ISSUE #45753: flutter has exited unexpectedly.
When i install flutter in windows and run flutter doctor command it sending crash report that flutter has exited unexpectedly i tried with flutter upgrade command also but same error occurs . please give a clear solution for this to install in windows.
flutterissue

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

If packages.json was malformed, flutter doctor could crash due to an uncaught FormatException. Catch the error and fallback to an unknown version

Fixes https://github.com/flutter/flutter/issues/45753

### CODE REVIEW

**Review by DanTup — APPROVED** [review]

File: packages/flutter_tools/lib/src/vscode/vscode.dart [hunk 1]
```diff
@@ -224,8 +224,12 @@ class VsCode {
       return null;
     }
     final String jsonString = fs.file(packageJsonPath).readAsStringSync();
-    final Map<String, dynamic> jsonObject = castStringKeyedMap(json.decode(jsonString));
-    return jsonObject['version'] as String;
+    try {
+      final Map<String, dynamic> jsonObject = castStringKeyedMap(json.decode(jsonString));
+      return jsonObject['version'] as String;
+    } on FormatException {
+      return null;
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/vscode/vscode.dart]: Consider putting a `printTrace()` here.
