### PR TITLE
Convert iOS simulator log reader to simctl, use unified logging filters

### LINKED ISSUE #18409: Reading iOS logs requires sudo access: "log: Must be admin to run 'stream' command"
*@csterritt commented on Jun 12, 2018, 12:07 AM UTC:*

## Steps to Reproduce

Ran `flutter create first_try`, cd'd into that directory. `flutter run` works, comes up fine in the iOS emulator. I can run in IntelliJ with the "Run" command (green triangle), but no hot-reload.

If I run with "Debug" command (green bug), I get the empty white screen on the iOS emulator, and the following output:

```
Launching lib/main.dart on iPhone X in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Starting Xcode build...
Xcode build done.

```

## Version info
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-US)
• Flutter version 0.4.4 at /Volumes/Second/Chris/hacks/flutter/flutter
• Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
• Engine revision 06afdfe54e
• Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
• Android SDK at /Users/chris/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.0
• Java binary at: /Users/chris/hacks/flutter/jdk-10.0.1.jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 10.0.1+10)
✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.4, Build version 9F1027a
• ios-deploy 1.9.2
• CocoaPods version 1.5.3

[✗] Android Studio (not installed)
• Android Studio not found; download from [https://developer.android.com/studio/index.html](https://developer.android.com/studio/index.html)
(or visit [https://flutter.io/setup/#android-setup](https://flutter.io/setup/#android-setup) for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
• IntelliJ at /Users/chris/Applications/IntelliJ IDEA CE.app
• Flutter plugin version 25.0.2
• Dart plugin version 181.4892.1

[!] VS Code (version 1.24.0)
• VS Code at /Users/chris/Applications/Visual Studio Code.app/Contents
• Dart Code extension not installed; install from
[https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code)

[✓] Connected devices (1 available)
• iPhone X • D34D5096-B3F9-4930-822B-48D3BD71B83D • ios • iOS 11.4 (simulator)

! Doctor found issues in 3 categories.
```
*This issue was moved by [devoncarew](https://github.com/devoncarew) from flutter/flutter-intellij/issues/2360.*

### PR DESCRIPTION
**Pull request by jmagman**
## Description

1. Change `log stream` call to `simctl spawn ... log stream` which doesn't require admin access.
2. Move predicates from dart into the logging predicate, don't process every line in memory, let the `log` command leverage its db for queries.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/18409
https://github.com/flutter/flutter/issues/49314

## Tests

simulators_tests
No new Blaze failures.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 1]
```diff
@@ -580,20 +580,35 @@ class IOSSimulator extends Device {
...
+Future<Process> launchDeviceSystemLogTool(IOSSimulator device) async {
+  return processUtils.start(<String>['tail', '-n', '0', '-F', device.logFilePath]);
+}
+
+/// Launches the device log reader process on the host and parses unified logging.
+@visibleForTesting
+Future<Process> launchDeviceUnifiedLogging (IOSSimulator device, String appName) async {
+  final StringBuffer predicate = StringBuffer('eventType = logEvent AND ');
+
+  // Either from Flutter or Swift (maybe assertion or fatal error) or from the app itself.
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/simulators.dart:594]: How about something like:

```dart
String orP(List<String> clauses) => '(${clauses.join(" OR ")})';
String andP(List<String> clauses) => '(${clauses.join(" AND ")})';
String notP(String clause) => 'NOT($clause)';

final String predicate = andP(<String>[
  orP(<String>[
    'senderImagePath ENDSWITH "/Flutter"',
    'senderImagePath ENDSWITH "/libswiftCore.dylib"',
    'processImageUUID == senderImageUUID',
  ]),
  if (appName != null) 'processImagePath ENDSWITH "$appName"',
  notP('eventMessage CONTAINS ": could not find icon for representation -> com.apple."'),
  notP(andP(<String>[
    'eventMessage BEGINSWITH "assertion failed: "',
    'eventMessage CONTAINS " libxpc.dylib "',
  ])),
]);
```

or anything with a bit more structure to it, really. How could it be easier to add new clauses in the future?

**Review by zanderso — APPROVED** [review]
