### PR TITLE
Fix SliverPersistentHeader interactions with SliverCrossAxisGroup

### LINKED ISSUE #126957: SliverCrossAxisGroup does not work with pinned SliverPersistentHeader
Putting a SliverPinnedPersistentHeader inside of SliverCrossAxisGroup has some weird behavior.
As the group scrolls out of view, the pinned header remains, overlapping content until the full extent of the group is scrolled away, after which point it disappears suddenly.

https://github.com/flutter/flutter/assets/16964204/86e600d1-1a5c-418b-bee5-e8309e695117

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverCrossAxisGroup(
              slivers: <Widget>[
                SliverPersistentHeader(
                  pinned: true,
                  delegate: SimpleDelegate(Colors.pink)
                ),
                SliverList.builder(
                  itemCount: 20,
                  itemBuilder: (BuildContext context, int index) => Text('Item $index'),
                ),
              ],
            ),
            SliverPersistentHeader(
              delegate: SimpleDelegate(Colors.blue),
            ),
            SliverList.builder(
              itemCount: 100,
              itemBuilder: (BuildContext context, int index) => Text('Item $index'),
            ),
          ],
        ),
      )
    );
  }
}

class SimpleDelegate extends SliverPersistentHeaderDelegate {
  SimpleDelegate(this.color);

  final Color color;
  
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(color: color, child: const Center(child: Text(
      'Header',
      style: TextStyle(color: Colors.white),
    )));
  }

  @override
  double get maxExtent => 60;

  @override
  double get minExtent => maxExtent;

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) => true;
}
```

<details>

<summary>Flutter doctor</summary>

[✓] Flutter (Channel master, 3.11.0-6.0.pre.53, on macOS 13.3.1 22E772610a darwin-x64, locale en)
    • Flutter version 3.11.0-6.0.pre.53 on channel master at /Users/katelovett/_github/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision d132b724c5 (23 hours ago), 2023-05-15 17:49:52 -0500
    • Engine revision c784d6d413
    • Dart version 3.1.0 (build 3.1.0-102.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.5-9884540)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Users/katelovett/Library/Application
      Support/JetBrains/IntelliJUE_Base2022.3/IntelliJ IDEA.app
    • Flutter plugin version 73.0.3
    • Dart plugin version 223.8888

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

</details>

### LINKED ISSUE #126958: SliverCrossAxisGroup does not work with floating SliverPersistentHeader
Related: https://github.com/flutter/flutter/issues/126957
(Filed separately since pinned, floating and pinned+floating all boil down to different render objects)

Putting a SliverPinnedPersistentHeader inside of SliverCrossAxisGroup has some weird behavior.
As the group is scrolled back up to reveal the floating header at the edge of the group, it suddenly appears overlapping the content that follows the group.

https://github.com/flutter/flutter/assets/16964204/835cbbe9-af53-4c6b-8fe4-ffaa51ec578c

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverCrossAxisGroup(
              slivers: <Widget>[
                SliverPersistentHeader(
                  floating: true,
                  delegate: SimpleDelegate(Colors.pink)
                ),
                SliverList.builder(
                  itemCount: 20,
                  itemBuilder: (BuildContext context, int index) => Text('Item $index'),
                ),
              ],
            ),
            SliverPersistentHeader(
              delegate: SimpleDelegate(Colors.blue),
            ),
            SliverList.builder(
              itemCount: 100,
              itemBuilder: (BuildContext context, int index) => Text('Item $index'),
            ),
          ],
        ),
      )
    );
  }
}

class SimpleDelegate extends SliverPersistentHeaderDelegate {
  SimpleDelegate(this.color);

  final Color color;
  
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(color: color, child: const Center(child: Text(
      'Header',
      style: TextStyle(color: Colors.white),
    )));
  }

  @override
  double get maxExtent => 60;

  @override
  double get minExtent => maxExtent;

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) => true;
}
```

<details>

<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 3.11.0-6.0.pre.53, on macOS 13.3.1 22E772610a darwin-x64, locale en)
    • Flutter version 3.11.0-6.0.pre.53 on channel master at /Users/katelovett/_github/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision d132b724c5 (23 hours ago), 2023-05-15 17:49:52 -0500
    • Engine revision c784d6d413
    • Dart version 3.1.0 (build 3.1.0-102.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.5-9884540)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Users/katelovett/Library/Application
      Support/JetBrains/IntelliJUE_Base2022.3/IntelliJ IDEA.app
    • Flutter plugin version 73.0.3
    • Dart plugin version 223.8888

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by thkim1011**
This PR fixes `SliverCrossAxisGroup` so that once we calculate the total `scrollExtent` of the `SliverCrossAxisGroup`, we ensure that any child sliver is not painted outside of the "scroll extent" of the sliver group.

https://github.com/flutter/flutter/assets/2004742/670dc6f9-a3c6-4bcc-85d3-576cf7f33c6a

https://github.com/flutter/flutter/assets/2004742/0c9cd951-c133-4a8b-9e5e-89d0a69a4f59

Fixes #126958.
Fixes #126957.
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart [hunk 1]
```diff
@@ -562,9 +617,27 @@ Widget _buildSliverCrossAxisGroup({
...
       ),
     ),
   );
 }
+
+class TestDelegate extends SliverPersistentHeaderDelegate {
+  TestDelegate();
+
+  @override
+  double get maxExtent => 60.0;
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:631]: Can you add tests where the delegate maxExtent != minExtent?

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart [hunk 2]
```diff
@@ -511,6 +511,60 @@ void main() {
     expect(first.localToGlobal(Offset.zero), Offset.zero);
     expect(second.localToGlobal(Offset.zero), const Offset(VIEWPORT_WIDTH / 2, 0));
   });
+
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:514]: There are a lot of configurations of SliverPersistentHeader we should test here. SliverAppBar is a SliverPersistentHeader with some extra features. That should be tested too.

Here floating: true (rest false) and pinned:true (rest false) are covered, but can you also add tests for:

- floating: false, pinned: false, snap: false
- floating: true, pinned: false, snap: true
- floating: true, pinned: true, snap: false
- floating: true, pinned: true, snap: true

(snap can only be true when floating is true, so that combination is irrelevant)

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:631]: For each case listed above. :)
In the case of SliverAppBar, the expandedHeight is what creates the same effect as minExtent < maxExtent.

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart [hunk 3]
```diff
@@ -511,6 +511,60 @@ void main() {
...
+  testWidgets('SliverFloatingPersistentHeader is painted within bounds of SliverCrossAxisGroup', (WidgetTester tester) async {
+    final ScrollController controller = ScrollController();
+    await tester.pumpWidget(_buildSliverCrossAxisGroup(
+      controller: controller,
+      slivers: <Widget>[
+        const SliverToBoxAdapter(child: SizedBox(height: 600)),
+        SliverPersistentHeader(
+          delegate: TestDelegate(),
+          floating: true,
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:546]: Wasn't there a test earlier that validated the position after a jumpTo? Was that removed?

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart (hunk 1 above)
Comment (thkim1011) [reply packages/flutter/test/widgets/sliver_cross_axis_group_test.dart]: Sure, I added some, and did it for SliverAppBar as well.

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart (hunk 2 above)
Comment (thkim1011) [reply packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:514]: Done! For the floating: true, pinned: true, snap: false, I used SliverPersistentHeader(floating: true, pinned: true) instead since I think this is the same cas.e

File: packages/flutter/test/widgets/sliver_cross_axis_group_test.dart (hunk 3 above)
Comment (thkim1011) [reply packages/flutter/test/widgets/sliver_cross_axis_group_test.dart:548]: Added it back in.

File: packages/flutter/lib/src/rendering/sliver_persistent_header.dart [hunk 4]
```diff
@@ -367,10 +367,13 @@ abstract class RenderSliverScrollingPersistentHeader extends RenderSliverPersist
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_persistent_header.dart:367]: Looks like the whitespace changes here are leftover? Can you remove them?

**Review by Piinks — COMMENTED** [review]
LGTM with just one nit

File: packages/flutter/lib/src/rendering/sliver_persistent_header.dart (hunk 4 above)
Comment (thkim1011) [reply packages/flutter/lib/src/rendering/sliver_persistent_header.dart]: Done!

**Review by Piinks — APPROVED** [review]
