### PR TITLE
Fix Inherited bugs

### LINKED ISSUE #3120: Inherited widgets should notify their descendants when they are added, if there was no previous ancestor of this type

### LINKED ISSUE #3493: Inherited doesn't rebuild Builder when the dependee goes away
```
  test('Update inherited when removing node', () {
    testWidgets((WidgetTester tester) {

      final List<int> log = <int>[];

      Widget child = new Builder(
        key: new GlobalKey(),
        builder: (BuildContext context) {
          ValueInherited v = context.inheritFromWidgetOfExactType(ValueInherited);
          log.add(v.value);
          return new Text('');
        }
      );

      tester.pumpWidget(
        new ValueInherited(
          value: 2,
          child: new FlipWidget(
            left: new ValueInherited(
              value: 3,
              child: child
            ),
            right: child
          )
        )
      );

      expect(log, equals(<int>[3]));
      log.clear();

      tester.pump();

      expect(log, equals(<int>[]));
      log.clear();

      flipStatefulWidget(tester);
      tester.pump();

      expect(log, equals(<int>[2])); // fails here
      log.clear();

      flipStatefulWidget(tester);
      tester.pump();

      expect(log, equals(<int>[3]));
      log.clear();
    });
  });
```

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/3493
- rebuild stateless widgets that have dependencies when their ancestors change but they don't

Fixes https://github.com/flutter/flutter/issues/3120
- rebuild widgets that tried to inherit from a widget that didn't exist, when the widget is added

This adds a bool to Element. The implementation for both these widgets is to be a bit aggressive in marking widgets dirty, so that we don't have to carefully track exactly what depends on what. This trades a few more build functions for the avoidance of expensive and often futile work during builds.

It also rearranges the travis bot script to put the most-likely-to-fail-usefully bits at the top.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -1168,6 +1169,7 @@ abstract class Element implements BuildContext {
 
   Map<Type, InheritedElement> _inheritedWidgets;
   Set<InheritedElement> _dependencies;
+  Set<Type> _unsatisfiedDependencies;
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: Why not use _inheritedWidgets with type mapped to null to represent unsatisfied dependencies?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -1419,6 +1422,24 @@ abstract class BuildableElement extends Element {
     markNeedsBuild();
   }
 
+  bool _hadDependenciesWhenDeactivated = false;
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: Can we use the _dirty bool to represent this information?  Basically, have the deactivated elements who need a build when reactivated marked as dirty?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 3]
```diff
@@ -1752,7 +1773,20 @@ class InheritedElement extends _ProxyElement {
...
+    final Type widgetType = widget.runtimeType;
+    if (_child != null && !_inheritedWidgets.containsKey(widgetType)) {
+      ElementVisitor visitor;
+      visitor = (Element child) {
+        if (child.runtimeType == widgetType)
+          return; // no point going further down this tree, they have one already
+        if (child._unsatisfiedDependencies != null &&
+            child._unsatisfiedDependencies.contains(widgetType))
+          child.dependenciesChanged(widgetType);
+        child.visitChildren(visitor);
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: I suspect there's a better approach here.  _updateInheritance is called in a downward walk and you're generating a nested downward walk, which often will end up being n^2.  Instead, you should try passing information down the activate walk (e.g., in a function argument) that lets each element update its unsatisfied dependencies when we visit them during the normal course of the activate walk.  That will avoid the n^2.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: _inheritedWidgets is shared across large parts of the tree. If we used it for this, we'd be rebuilding many parts of the tree when a new inherited widget came in.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: That's tricky. The problem is that we have to keep track of whether we were added to the dirty list, and that's what _dirty usually tracks. So if we also use it to track whether we need to be marked dirty when we are reactivated, we stomp on the bit that tracks whether we're on the list already. (Also, _dirty's lifecycle is already pretty complicated.)

If we're worried about memory usage, we could use a BitField for storing the bits (active, dirty, this one, and a debug bit).

File: packages/flutter/lib/src/widgets/framework.dart (hunk 3 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: good call. I hadn't noticed that.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: Gotcha.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 2 above)
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: I was just thinking we could follow the pattern in RenderObject.attach which uses the render tree dirty bits in this way already.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: Looks like the rendering library just doesn't check if things have been inserted twice. I could do that in widgets too if you like. It's probably fine.

**Comment by Hixie** [comment]
PTAL.

So far I've only change the O(N²) issue. I haven't done the _dirty trick, happy to do it if you think that's better (either here or in another PR).

**Comment by Hixie** [comment]
cc @devoncarew on the changes to the travis script which I made because it's useful for travis to fail fast and fail usefully, so things like the analysis benchmark really should come last.

**Comment by devoncarew** [comment]
sgtm re: the travis script.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 4]
```diff
@@ -1108,49 +1108,74 @@ abstract class Element implements BuildContext {
...
     assert(widget != null);
     assert(depth != null);
     assert(_active);
-    if (_dependencies != null) {
+    if (_dependencies != null && _dependencies.length > 0) {
       for (InheritedElement dependency in _dependencies)
         dependency._dependents.remove(this);
       _dependencies.clear();
     }
+    _unsatisfiedDependencies?.clear();
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: Here you clear out `_unsatisfiedDependencies`, which means it will always be empty on line 1146.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: odd, I wonder why my test passed...

**Comment by Hixie** [comment]
PTYAL. Third time's the charm? :-)

File: packages/flutter/lib/src/material/ink_well.dart [hunk 5]
```diff
@@ -197,14 +197,10 @@ class _InkResponseState<T extends InkResponse> extends State<T> {
...
-  void dependenciesChanged(Type affectedWidgetType) {
-    if (affectedWidgetType == Theme && _lastHighlight != null)
-      _lastHighlight.color = Theme.of(context).highlightColor;
-  }
-
-  @override
   Widget build(BuildContext context) {
     assert(config.debugCheckContext(context));
+    if (_lastHighlight != null)
+      _lastHighlight.color = Theme.of(context).highlightColor;
```
Comment (abarth) [inline packages/flutter/lib/src/material/ink_well.dart]: I think you can write this as:

`_lastHighlight?.color = Theme.of(context).highlightColor`

File: packages/flutter/lib/src/widgets/framework.dart [hunk 6]
```diff
@@ -1411,22 +1437,28 @@ abstract class BuildableElement extends Element {
...
   @override
-  void dependenciesChanged(Type affectedWidgetType) {
+  void dependenciesChanged() {
+    assert(_active);
     markNeedsBuild();
   }
 
   @override
+  void activate() {
+    bool rebuild = ((_dependencies != null && _dependencies.length > 0) || _hadUnsatisfiedDependencies);
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: final

File: travis/test.sh [hunk 7]
```diff
@@ -27,3 +23,9 @@ dart dev/tools/mega_gallery.dart
 (cd examples/layers; flutter test)
 (cd examples/material_gallery; flutter test)
 (cd examples/stocks; flutter test)
+
+# end of section that needs to be in sync with the infra bots
```
Comment (abarth) [inline travis/test.sh]: The infra bots shell out to this file now.  Maybe remove these comments about keeping things in sync?

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/material/ink_well.dart (hunk 5 above)
Comment (Hixie) [inline packages/flutter/lib/src/material/ink_well.dart]: Yup, this works. (I tested that this doesn't call the RHS if the LHS evaluates to null.)
Done.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 6 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: Done. Also renamed the variable to shouldRebuild to avoid stomping on the rebuild method.

File: travis/test.sh (hunk 7 above)
Comment (Hixie) [inline travis/test.sh]: Sweet! Done.

**Comment by Hixie** [comment]
Thanks! Will check in when bot turns green.
