### PR TITLE
refactor; fix apk warning

### LINKED ISSUE #2805: "Cannot locate Resources: Directory: 'android/res', ignoring."
I tried to run one of our layers/ examples and the message I got was:

```
Cannot locate Resources: Directory: 'android/res', ignoring.
```

...which has dubious punctuation.

### PR DESCRIPTION
**Pull request by devoncarew**
- use android/res if it exists and no resource path was specified; else, validate an explictly passed in resource path (fix https://github.com/flutter/flutter/issues/2805)
- rename `Compiler` to `SnapshotCompiler` for a bit more clarity into what it does
- analyze one more dir in `analyze --watch`
- misc updates

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

File: packages/flutter_tools/lib/src/commands/analyze.dart [hunk 1]
```diff
@@ -449,10 +444,13 @@ class AnalyzeCommand extends FlutterCommand {
...
-    if (isFlutterRepo) {
+    if (argResults['flutter-repo']) {
+      String root = path.absolute(ArtifactStore.flutterRoot);
+
       directories = <String>[];
-      directories.addAll(_gatherProjectPaths(path.absolute('examples')));
-      directories.addAll(_gatherProjectPaths(path.absolute('packages')));
+      directories.addAll(_gatherProjectPaths(path.join(root, 'examples')));
+      directories.addAll(_gatherProjectPaths(path.join(root, 'packages')));
+      directories.addAll(_gatherProjectPaths(path.join(root, 'dev')));
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/analyze.dart]: this doesn't exactly match the logic in the single-shot case (e.g. that takes into account manual-tests and layers and so on). any chance we can move these to use more common code to determine the paths? Or is the analyzer server doing things very differently than regular analyzer?

File: packages/flutter_tools/lib/src/commands/build_apk.dart [hunk 2]
```diff
@@ -237,21 +235,15 @@ Future<_ApkComponents> _findApkComponents(
...
   await parseServiceConfigs(components.services, jars: components.jars);
 
-  if (!components.resources.existsSync()) {
-    // TODO(eseidel): This level should be higher when path is manually set.
-    printStatus('Cannot locate Resources: ${components.resources}, ignoring.');
-    components.resources = null;
-  }
-
-  for (File f in [
+  for (File file in [
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/build_apk.dart]: `<File>[...]`

File: packages/flutter_tools/lib/src/commands/analyze.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/analyze.dart]: Those files should be analyzed by --watch w/o us having to special case them. @pq has a change into the command-line analyzer that should allow it to analyze directories; that will help us unify our logic here.

It may be good to have a discussion about where we want to end up, in terms of what parts do what in this script, and what the user experience looks like from `dartanalyzer` / `flutter analyze` / Atom + analysis server based tools...

File: packages/flutter_tools/lib/src/commands/build_apk.dart (hunk 2 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/build_apk.dart]: done (in another PR)
