### PR TITLE
Fix token usages on Regular Chip and Action Chip

### LINKED ISSUE #141288: Material 3 - Regular chip and Action chip templates using invalid tokens
### Steps to reproduce

To reproduce run the `gen_defaults` tool (https://github.com/flutter/flutter/pull/140872 improves some false positives and the output)
Here is the result:

image

Filter chip and input chip token usages are being fixed in https://github.com/flutter/flutter/pull/140573
The assist-chip token (called ActionChip in Flutter) is being referenced in both the chip_template and the action_chip_template files.

More specifically, the token is referenced for the `checkmarkColor` and `deleteIconColor` values. Since the gen tool was reading non existing tokens, the resulting value is a null color.

https://github.com/flutter/flutter/blob/eff2e7dbb180964f47606dd9b2b46c566de5c6c6/dev/tools/gen_defaults/lib/action_chip_template.dart#L63

https://github.com/flutter/flutter/blob/eff2e7dbb180964f47606dd9b2b46c566de5c6c6/dev/tools/gen_defaults/lib/chip_template.dart#L44

---

## Action Chip

To fix the action chip template I propose the following:
### **deleteIconColor**
Action chips don't have an onDeleted callback in the Flutter API, so we could leave the value explicitly as null

### **checkmarkColor**
We could do the same here, because action chips in the Flutter API cannot be selected and they don't have a `showCheckmark` parameter. Alternatively we can use the same tokens as the leading icon. Any of the solutions would result in the same output, as there is an iconTheme above the leading icon, which takes the correct token already.

---

## (Regular) Chip

The regular Chip template is taking the token values from the assist-chip specification. This can fall short when we try to pick values from the assist-chip spec for the delete and the checkmark icons.

https://github.com/flutter/flutter/blob/eff2e7dbb180964f47606dd9b2b46c566de5c6c6/dev/tools/gen_defaults/lib/chip_template.dart#L13

To fix the chip template I propose the following:

### **deleteIconColor**
For this type of chip, Flutter provides an onDeleted callback, so we need to find an appropiate token. The problem is that assist-chip doesn't contemplate having a trailing icon, only a leading icon with the primary color. So if we would use assist-chip icon color, it would turn the delete icon purple/pink instead of dark grey (default Material 3 theme). I propose that we change the chip template to read from filter-chip instead, which is more general, contemplating the possibility of a leading icon and a trailing icon (delete/dropdown) with appropriate colors.
Changing the base of the chip template with filter-chip doesn't really have much changes visually. The delete icon color would go from black to (onSurfaceVariant) dark grey in a light theme. The leading icon color stays the same, as well as the chip borders.

### **checkmarkColor**
Same as the Action Chip proposed changes.

---

## Common changes

Same as https://github.com/flutter/flutter/pull/140573 we can update the label color with the correct token. The color token for the label is not currently being used.

---

## Regular chip visual differences

A regular Chip would change as follows. Essentially, black -> dark grey (onSurfaceVariant) for both the label and the delete icon.

### Before

image

### After (picture from the M3 spec)
Ignore the icon difference. Flutter picks a different delete icon for the regular Chip.

image

### PR DESCRIPTION
**Pull request by davidmartos96**
The regular chip and the action chip templates were referencing non existent M3 design tokens.

Fixes https://github.com/flutter/flutter/issues/141288

The `ActionChip` doesn't have any visual difference. Even though the template and file changes, the default `labelStyle` color already uses `onSurface`.
For the reviewer, I've changed the `action_chip_test` to expect a color from the colorScheme so that it is more explicit that the color might not be the same as the labelLarge default in the global textTheme, even if for this case the color is the same.

The regular `Chip` does have visual differences, in particular, the label and trailing icon colors, which were not following the specification. In order to fix this, the regular chip now is based from the `filter-chip` spec as described in the linked issue.

## Before

image

## After

image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/tools/gen_defaults/lib/action_chip_template.dart [hunk 1]
```diff
@@ -60,10 +64,10 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
   Color? get surfaceTintColor => ${colorOrTransparent("$tokenGroup.container.surface-tint-layer.color")};
 
   @override
-  Color? get checkmarkColor => ${color("$tokenGroup.with-icon.selected.icon.color")};
+  Color? get checkmarkColor => null;
```
Comment (QuncCccccc) [inline dev/tools/gen_defaults/lib/action_chip_template.dart:67]: Should we here use "$tokenGroup.with-icon.icon.color"?

File: dev/tools/gen_defaults/lib/action_chip_template.dart [hunk 2]
```diff
@@ -60,10 +64,10 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
...
 
   @override
-  Color? get deleteIconColor => ${color("$tokenGroup.with-icon.selected.icon.color")};
+  Color? get deleteIconColor => null;
```
Comment (QuncCccccc) [inline dev/tools/gen_defaults/lib/action_chip_template.dart:70]: Same here

File: dev/tools/gen_defaults/lib/chip_template.dart [hunk 3]
```diff
@@ -10,7 +10,7 @@ class ChipTemplate extends TokenTemplate {
     super.textThemePrefix = '_textTheme.'
   });
 
-  static const String tokenGroup = 'md.comp.assist-chip';
+  static const String tokenGroup = 'md.comp.filter-chip';
```
Comment (QuncCccccc) [inline dev/tools/gen_defaults/lib/chip_template.dart:13]: Based on the comment in the original issue, this change makes sense to me. Maybe @TahaTesser has more context about this:)

File: dev/tools/gen_defaults/lib/chip_template.dart [hunk 4]
```diff
@@ -41,21 +45,23 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
   Color? get surfaceTintColor => ${colorOrTransparent("$tokenGroup.container.surface-tint-layer.color")};
 
   @override
-  Color? get checkmarkColor => ${color("$tokenGroup.with-icon.selected.icon.color")};
+  Color? get checkmarkColor => null;
```
Comment (QuncCccccc) [inline dev/tools/gen_defaults/lib/chip_template.dart:48]: If we change tokenGroup to filterChip, should we here use `with-leading-icon.selected.leading-icon.color`?

**Review by QuncCccccc — COMMENTED** [review]
Thanks so much for the contribution! Just left some questions below:)

**Comment by davidmartos96** [comment]
@QuncCccccc Thanks for reviewing! I'll try to answer the comments here, as all of them are related.

I've purposely set those as null for a couple reasons. Described in the linked issue, but I'll try to summarize.

1. The checkmark and delete icons are not part of the ActionChip API, so I think it would only add confusion if we assign a token. `null` is giving some meaning saying there is not a token defined for those colors, as it is not in the spec.
2. There is already an `iconTheme` which applies to the leading icon.
3. If we were to give a color to the ActionChip delete icon, imagining it did have the API for such icon, it would be colored with the primary color (i.e. purple in the default M3 theme), instead of the the label color.

But it would be great to read some other opinion :smile:

File: dev/tools/gen_defaults/lib/chip_template.dart (hunk 3 above)
Comment (TahaTesser) [reply dev/tools/gen_defaults/lib/chip_template.dart:13]: Since `chip_template` is for generic chip, using filter chip tokens to get most tokens available makes sense.

File: dev/tools/gen_defaults/lib/action_chip_template.dart (hunk 1 above)
Comment (davidmartos96) [reply dev/tools/gen_defaults/lib/action_chip_template.dart:67]: @QuncCccccc  I've written my thoughts on this in the main thread: https://github.com/flutter/flutter/pull/141701#issuecomment-1901332557
Let me know what you think

**Review by QuncCccccc — APPROVED** [review]
LGTM

**Review by TahaTesser — APPROVED** [review]

**Comment by QuncCccccc** [comment]
Same here. Doing a local test for G3 before we merge this in master.

**Comment by QuncCccccc** [comment]
Could you help solve the conflicts:)?
