### PR TITLE
Fix RangeSlider dragged cursor handling.

### LINKED ISSUE #179987: RangeSlider dragged cursor is not visible if onChangeStart and onChangeEnd are not set.
### Steps to reproduce

1. Run the sample app from this issue
2. Try to drag any handle and observe that the dragged cursor is not visible
3. Uncomment `onChangeStart` and `onChangeEnd` callbacks
4. Try to drag any handle again. The dragged cursor is now visible

### Expected results

The dragged cursor appears no matter whether `onChangeStart` and `onChangeEnd` are set to be consistent with the `Slider` implementation.

https://github.com/user-attachments/assets/5bd37714-740d-4056-ac7d-b57773a89e62

### Actual results

The dragged cursor does not appear if `onChangeStart` and `onChangeEnd` are not set.

https://github.com/user-attachments/assets/756b01e0-e52b-4280-af5e-ef02a6081855

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: _Slider(),
        ),
      ),
    );
  }
}

class _Slider extends StatefulWidget {
  const _Slider();

  @override
  State<_Slider> createState() => __SliderState();
}

class __SliderState extends State<_Slider> {
  var _values = RangeValues(0.25, 0.75);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 500,
      height: 100,
      child: Center(
        child: SliderTheme(
          data: SliderThemeData(
            valueIndicatorColor: Colors.red,
            showValueIndicator: ShowValueIndicator.alwaysVisible,
          ),
          child: RangeSlider(
            values: _values,
            onChanged: (values) {
              print('Slider values changed: $values');
              setState(() {
                _values = values;
              });
            },
            // Uncomment those two callbacks to make the dragged cursor visible.
            // onChangeStart: (_) {},
            // onChangeEnd: (_) {},
            mouseCursor: WidgetStateMouseCursor.resolveWith((states) {
              if (states.contains(WidgetState.dragged)) {
                return SystemMouseCursors.grabbing;
              }
              return SystemMouseCursors.click;
            }),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.40.0-1.0.pre-225, on macOS 15.6.1 24G90 darwin-arm64, locale en-US) [2.2s]
    • Flutter version 3.40.0-1.0.pre-225 on channel master at /Users/ksokolovskyi/development/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 109b65f0b8 (3 hours ago), 2025-12-17 02:36:19 -0500
    • Engine revision 109b65f0b8
    • Dart version 3.11.0 (build 3.11.0-253.0.dev)
    • DevTools version 2.53.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [2.1s]
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [990ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [9.0s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.6.1 24G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 143.0.7499.110

[✓] Network resources [1,560ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes #179987

### Description
- Fixes dragged cursor handling in `RangeSlider`
- Replaces `MaterialState` occurrences with `WidgetState`
- Updates tests to ensure that all cases are covered

| Before | After |
| - | - |
| <video src="https://github.com/user-attachments/assets/756b01e0-e52b-4280-af5e-ef02a6081855" /> | <video src="https://github.com/user-attachments/assets/5bd37714-740d-4056-ac7d-b57773a89e62" /> |

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/range_slider_test.dart [hunk 1]
```diff
@@ -1532,7 +1532,7 @@ void main() {
         );
       }
 
-      await tester.pumpWidget(buildApp(divisions: 3));
```
Comment (QuncCccccc) [inline packages/flutter/test/material/range_slider_test.dart:1535]: The code change above makes sense to me, but why the test will fail when the divisions stays 3?

**Review by dkwingsmt — APPROVED** [review]
LGTM except for Qun's question.

**Review by QuncCccccc — APPROVED** [review]
Thanks for the detailed explanation! LGTM:)

**Comment by ksokolovskyi** [comment]
@QuncCccccc thanks a lot for your review!
