### PR TITLE
Keep last character obscured when toggling obscureText

### LINKED ISSUE #184483: Toggling TextField.obscureText can show the last character
### Steps to reproduce

1. Run the sample app **on a mobile device**
2. Type some text in the password field and immediately press the `Show Text` button twice

### Expected results

When `TextField.obscureText` is toggled quickly from true → false → true, all characters should be obscured.

### Actual results

When `TextField.obscureText` is toggled quickly from true → false → true, the most recently entered character is briefly visible.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: .all(20.0),
            child: PasswordToggleField(),
          ),
        ),
      ),
    );
  }
}

class PasswordToggleField extends StatefulWidget {
  const PasswordToggleField({super.key});

  @override
  State<PasswordToggleField> createState() => _PasswordToggleFieldState();
}

class _PasswordToggleFieldState extends State<PasswordToggleField> {
  bool _isObscured = true;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: .min,
      spacing: 20,
      children: [
        TextField(
          obscureText: _isObscured,
          decoration: const InputDecoration(
            border: OutlineInputBorder(),
            labelText: 'Password',
          ),
        ),
        ElevatedButton(
          onPressed: () {
            // 3. Toggle the state and rebuild the UI
            setState(() {
              _isObscured = !_isObscured;
            });
          },
          child: Text(_isObscured ? 'Show Text' : 'Hide Text'),
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/992e0473-059c-4c7a-a1b1-8ca6bf222538

</details>

### Logs

N/A

### Flutter Doctor output

N/A

### PR DESCRIPTION
**Pull request by TrangLeQuynh**
…perty toggle on or off

### Summary
When `obscureText` is toggled quickly from true → false → true, the most recently entered character is shown in an obscured text field.

Fixes https://github.com/flutter/flutter/issues/184483

### Steps to restore

1. Create a TextField with `obscureText = true`.

2. Quickly type some text.

3. Toggle `obscureText` to **false**.

4. Immediately toggle it back to **true**.

5. Observe the displayed text.

> Note: This behavior occurs when the operations are performed quickly (≤ ~1500 ms), due to defaults:
>
> ```dart
> // The time it takes for the cursor to fade from fully opaque to fully
>// transparent and vice versa. A full cursor blink, from transparent to opaque
>// to transparent, is twice this duration.
>const Duration _kCursorBlinkHalfPeriod = Duration(milliseconds: 500);
>
>// Number of cursor ticks during which the most recently entered character
>// is shown in an obscured text field.
>const int _kObscureShowLatestCharCursorTicks = 3;
> ```

### Actual Result

The most recently entered character may still be visible briefly after `obscureText` is set back to true

https://github.com/user-attachments/assets/94d2ba56-c551-4385-8f88-3dd746c8dc09

### Expect result

When `obscureText` is updated to true, all characters should be immediately obscured, regardless of previously revealed characters.

https://github.com/user-attachments/assets/992e0473-059c-4c7a-a1b1-8ca6bf222538

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
@TrangLeQuynh thank you for the contribution! Before moving forward with this PR you will need to sign the CLA and write a test to verify that the expected behavior works after the change.

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+    focusNode = FocusNode(debugLabel: 'EditableText Node');
+  });
+
+  tearDown(() {
+    controller.dispose();
+    focusNode.dispose();
+  });
+
+  testWidgets(
+    'Prevent the last character in obscure text when the obscureText option is toggled',
```
Comment (Renzo-Olivares) [inline packages/flutter/test_fixes/widgets/editable_text_fix.dart]: This test would be more appropriate living in `editable_text_test.dart`.

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+    (WidgetTester tester) async {
+      bool obscureText = true;
+      late StateSetter setState;
+
+      await tester.pumpWidget(
+        MaterialApp(
```
Comment (Renzo-Olivares) [inline packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Prefer using `TestWidgetsApp` in the Widgets library tests and not importing material.

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+
+      /// set obscureText = true
+      setState(() {
+        obscureText = true;
+      });
+      await tester.pump();
+      expect((findRenderEditable(tester).text! as TextSpan).text, '•••');
+    },
+    variant: const TargetPlatformVariant(<TargetPlatform>{
+      TargetPlatform.iOS,
```
Comment (Renzo-Olivares) [inline packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Is there a reason we specify the variant for tests here, why not just the default?

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+      await tester.pump(const Duration(milliseconds: 500));
+      await tester.pump(const Duration(milliseconds: 500));
+      expect((findRenderEditable(tester).text! as TextSpan).text, '••');
+
+      await tester.enterText(find.byType(EditableText), 'HHH');
+      await tester.pump();
+
+      expect((findRenderEditable(tester).text! as TextSpan).text, '••H');
+
+      /// set obscureText = false
```
Comment (Renzo-Olivares) [inline packages/flutter/test_fixes/widgets/editable_text_fix.dart]: super nit: use `//` for comments and `///` for documentation, here and elsewhere in this file..

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+    variant: const TargetPlatformVariant(<TargetPlatform>{
+      TargetPlatform.iOS,
+      TargetPlatform.android,
+      TargetPlatform.fuchsia,
+    }),
+  );
+}
+
+// Returns the RenderEditable at the given index, or the first if not given.
+RenderEditable findRenderEditable(WidgetTester tester, {int index = 0}) {
```
Comment (Renzo-Olivares) [inline packages/flutter/test_fixes/widgets/editable_text_fix.dart]: If this moves to `editable_text_test.dart` we won't need this convenience method anymore.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -3406,6 +3406,8 @@ class EditableTextState extends State<EditableText>
     if (_hasInputConnection) {
       if (oldWidget.obscureText != widget.obscureText ||
           oldWidget.keyboardType != widget.keyboardType) {
+        //reset to prevent the last character in obscure text
+        _obscureShowCharTicksPending = 0;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart]: We should probably also reset `_obscureLatestCharIndex`.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -3406,6 +3406,8 @@ class EditableTextState extends State<EditableText>
     if (_hasInputConnection) {
       if (oldWidget.obscureText != widget.obscureText ||
           oldWidget.keyboardType != widget.keyboardType) {
+        //reset to prevent the last character in obscure text
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Maybe similar to gemini's suggestion:

```
// When obscureText is toggled, we should reset its state to prevent the last character from being visible between state changes.
```

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Also end comment with a period `.`

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 8]
```diff
@@ -3406,6 +3406,8 @@ class EditableTextState extends State<EditableText>
     if (_hasInputConnection) {
       if (oldWidget.obscureText != widget.obscureText ||
           oldWidget.keyboardType != widget.keyboardType) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart]: I think it sounds reasonable to reset this last obscure character when the keyboard type changes but curious to hear others thoughts. In triage we discussed only resetting when `obscureText` changes.

**Review by Renzo-Olivares — COMMENTED** [review]
Hi @TrangLeQuynh, thank you for the contribution! Left a few comments.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 9]
```diff
@@ -17909,6 +17909,71 @@ void main() {
...
+      expect((findRenderEditable(tester).text! as TextSpan).text, 'HHH');
+
+      // set obscureText = true.
+      setState(() {
+        obscureText = true;
+      });
+      await tester.pump();
+      expect((findRenderEditable(tester).text! as TextSpan).text, '•••');
+    },
+    variant: const TargetPlatformVariant(<TargetPlatform>{
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_test.dart:18352]: I would add a comment about why we only target these platforms and not others.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 10]
```diff
@@ -3404,8 +3404,12 @@ class EditableTextState extends State<EditableText>
     }
 
     if (_hasInputConnection) {
-      if (oldWidget.obscureText != widget.obscureText ||
-          oldWidget.keyboardType != widget.keyboardType) {
+      if (oldWidget.obscureText != widget.obscureText) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart]: I think an else if here prevents the `keyboardType` case from being reached if obscureText changed as well.

I suggest the logic below.

```dart
if (_hasInputConnection) {
  final bool obscureTextChanged = oldWidget.obscureText != widget.obscureText;
  if (obscureTextChanged || oldWidget.keyboardType != widget.keyboardType) {
    if (obscureTextChanged) {
      _obscureShowCharTicksPending = 0;
      _obscureLatestCharIndex = null;
    }
    _textInputConnection!.updateConfig(_effectiveAutofillClient.textInputConfiguration);
  }
}
```

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 11]
```diff
@@ -17909,6 +17909,72 @@ void main() {
     controller.selection = const TextSelection.collapsed(offset: 0);
     await tester.pump();
   });
+
+  testWidgets(
+    'Prevent the last character in obscure text when the obscureText option is toggled on mobile',
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_test.dart]: super nit: `Prevent last character visibility in obscure text when obscureText is toggled on mobile`

**Review by Renzo-Olivares — COMMENTED** [review]
LGTM pending my last nit

**Review by Renzo-Olivares — DISMISSED** [review]
LGTM, thank you for the contribution @TrangLeQuynh!

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 1 above)
Comment (loic-sharma) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Looks like this was resolved, please feel free to reopen if needed!

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 2 above)
Comment (loic-sharma) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: @TrangLeQuynh Is looks like this comment hasn't been addressed yet

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 3 above)
Comment (loic-sharma) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Closing as it looks like this was resolved, please feel free to reopen if needed!

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 4 above)
Comment (loic-sharma) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Closing as it looks like this was resolved, please feel free to reopen if needed!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
Comment (loic-sharma) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Closing as it looks like this was resolved, please feel free to reopen if needed!

File: packages/flutter/test_fixes/widgets/editable_text_fix.dart (hunk 5 above)
Comment (loic-sharma) [reply packages/flutter/test_fixes/widgets/editable_text_fix.dart]: Closing as it looks like this was resolved, please feel free to reopen if needed!

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 12]
```diff
@@ -18173,6 +18174,72 @@ void main() {
     controller.selection = const TextSelection.collapsed(offset: 0);
     await tester.pump();
   });
+
+  testWidgets(
+    'Prevent last character visibility in obscure text when obscureText is toggled on mobile',
+    (WidgetTester tester) async {
+      var obscureText = true;
```
Comment (loic-sharma) [inline packages/flutter/test/widgets/editable_text_test.dart:18296]: Could you add this comment? 5 years from now, it'll help us understand the context behind this test :)

```suggestion
      // Regression test for https://github.com/flutter/flutter/issues/184483.
      var obscureText = true;
```

**Review by loic-sharma — DISMISSED** [review]
Thanks for the wonderful contribution!

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 13]
```diff
@@ -18173,6 +18174,73 @@ void main() {
...
+      late StateSetter setState;
+
+      await tester.pumpWidget(
+        TestWidgetsApp(
+          home: StatefulBuilder(
+            builder: (BuildContext context, StateSetter stateSetter) {
+              setState = stateSetter;
+              return EditableText(
+                controller: controller,
+                backgroundCursorColor: Colors.grey,
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/editable_text_test.dart]: Can you use plain color equivalents instead of the Colors.xyz ?

This is to reduce the reliance on Material in flutter/widgets tests.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 14]
```diff
@@ -18173,6 +18174,73 @@ void main() {
...
+      await tester.showKeyboard(find.byType(EditableText));
+      await tester.idle();
+
+      await tester.enterText(find.byType(EditableText), 'H');
+      await tester.pump();
+      await tester.enterText(find.byType(EditableText), 'HH');
+      await tester.pump();
+
+      expect((findRenderEditable(tester).text! as TextSpan).text, '•H');
+      await tester.pump(const Duration(milliseconds: 500));
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/editable_text_test.dart:18327]: Is it really needed for 3 frames of 500ms ?

**Review by navaronbracke — CHANGES_REQUESTED** [review]

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 14 above)
Comment (TrangLeQuynh) [reply packages/flutter/test/widgets/editable_text_test.dart:18327]: The last character is not displayed after 3 × 500 ms. I split them to better illustrate the default configuration.

Default:
```dart
// The time it takes for the cursor to fade from fully opaque to fully
// transparent and vice versa. A full cursor blink, from transparent to opaque
// to transparent, is twice this duration.
const Duration _kCursorBlinkHalfPeriod = Duration(milliseconds: 500);

// Number of cursor ticks during which the most recently entered character
// is shown in an obscured text field.
const int _kObscureShowLatestCharCursorTicks = 3;
```

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 15]
```diff
@@ -18230,6 +18231,73 @@ void main() {
...
+      late StateSetter setState;
+
+      await tester.pumpWidget(
+        TestWidgetsApp(
+          home: StatefulBuilder(
+            builder: (BuildContext context, StateSetter stateSetter) {
+              setState = stateSetter;
+              return EditableText(
+                controller: controller,
+                backgroundCursorColor: const Color(0xFFF7F7F8),
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/editable_text_test.dart]: Should this be 0xFFF7F7F7 ? (then it is three channels which is recognisable as grey)

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 13 above)
Comment (loic-sharma) [reply packages/flutter/test/widgets/editable_text_test.dart]: Thanks for catching this!

**Review by loic-sharma — APPROVED** [review]
Re-LGTM!

**Review by navaronbracke — APPROVED** [review]
