### PR TITLE
Fix path name to discover debug apk on add2app builds

### LINKED ISSUE #117570: [tool][add-2-app] Can not run Flutter module - the output apk does not exist
I updated to Channel master( 3.7.0-13.0.pre.23) to solve  #117050 ,but there is a new problem, the debug apk path seems to have problems.
image
image

### PR DESCRIPTION
**Pull request by GaryQian**
Fixes https://github.com/flutter/flutter/issues/117570

This issue was introduced by https://github.com/flutter/flutter/pull/113622

Android Add2app builds output the debug APK in `build/host/outputs/apk/debug/app-debug.apk` but we were searching in the directory without `/debug/`

This doesn't occur with the other build modes (profile, release)

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/application_package.dart [hunk 1]
```diff
@@ -116,7 +116,11 @@ class AndroidApk extends ApplicationPackage implements PrebuiltApplicationPackag
     }
 
     if (androidProject.isUsingGradle && androidProject.isSupportedVersion) {
-      apkFile = getApkDirectory(androidProject.parent).childFile(filename);
+      Directory apkDirectory = getApkDirectory(androidProject.parent);
+      if (androidProject.parent.isModule && buildInfo?.mode == BuildMode.debug) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/application_package.dart:120]: What was the PR that changed this? And can you explain why we only do this extra namespace for debug modules?

**Comment by christopherfujino** [comment]
@GaryQian you still working on this one?

**Comment by GaryQian** [comment]
Yeah, still working on it 😀

**Comment by christopherfujino** [comment]
> Yeah, still working on it grinning

awesome

File: packages/flutter_tools/lib/src/android/application_package.dart (hunk 1 above)
Comment (GaryQian) [reply packages/flutter_tools/lib/src/android/application_package.dart]: This issue was caused by https://github.com/flutter/flutter/pull/113622, which stopped copying the generated apk to a fixed file name. Module/add2app projects were always outputting the apk in a buildmode subdirectory, eg `<buildmode>/app-<buildmode>.apk`. Previously, the copy to app.apk masked this `<buildmode>/app-<buildmode>.apk` output by placing the apk in `app.apk` without the subdir. When the copy was removed, the search path is now missing a `<buildmode>` subdir only for module projects.

Full flutter apps don't experience this issue due to the output dir not including the buildmode subdir.

We should also do this for the other buildmodes.

**Comment by GaryQian** [comment]
cc @reidbaker

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by reidbaker — APPROVED** [review]

**Comment by christopherfujino** [comment]
Merging on yellow FRoB because of an ongoing issue

**Comment by AlexV525** [comment]
@GaryQian Can't we unify different behaviors about copying built artifacts?
