### PR TITLE
Fix `Slider` thumb doesn't align with divisions, thumb padding, and rounded corners

### LINKED ISSUE #62567: [Slider] Thumb's center doesn't align with division's center
I'm trying to create a custom slider like the one below :

photo6109691975172205113

For that, I created 2 custom classes from SliderComponentShape and SliderTickMarkShape for the Slider's Thumb and the Slider divisions. In both the class, I was just fiddling around the paint object and radius to create the custom shape for my division and my thumb, and there is nothing fancy. 
But the problem is, except the center position in the slider, the thumb doesn't get aligned to any other division's center.
I've posted this problem in the StackOverflow [here](https://stackoverflow.com/questions/63051155/custom-discreet-slider-problem-in-aligning-the-thumb-to-the-divisions-center) and explained this very clearly with all the needed codes.

The question is: Shouldn't the thumb's center get naturally aligned to the division's center in all its positions? Or am I missing something?

### LINKED ISSUE #149589: `RoundedRectSliderTrackShape` corners are not rendered correctly
### Steps to reproduce

 `RoundedRectSliderTrackShape` corners are not rendered correctly. Specifically, when the slider thumb is moved to the start or at the end of track, the rounded corners of the track break, resulting in a visual inconsistency.

### Expected results

The corners of the slider track should remain smoothly rounded regardless of the thumb position.

### Thumb at the start of the track

https://github.com/flutter/flutter/assets/48603081/7047e4c3-07db-4abd-80d7-1b886bacc2c8

### Thumb at the end of the track

https://github.com/flutter/flutter/assets/48603081/70e0fe32-ac6a-4064-a459-3d7b98049454

### Actual results

When the thumb is positioned near the start or end of the track, the corners break and lose their rounded appearance.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double _value = 0.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        sliderTheme: const SliderThemeData(
          trackHeight: 32,
          thumbColor: Colors.green,
          // thumbColor: Colors.green.withOpacity(0.5),
          // activeTrackColor: Colors.red.withOpacity(0.5),
          inactiveTrackColor: Colors.amber,
          trackShape: RoundedRectSliderTrackShape(),
        ),
      ),
      home: Scaffold(
        body: Slider(
          value: _value,
          // divisions: 5,
          // label: _value.toStringAsFixed(2),
          // ignore: avoid_redundant_argument_values
          min: 0,
          max: 10,
          onChanged: (double value) {
            setState(() {
              _value = value;
            });
          },
        ),
      ),
    );
  }
}



```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### LINKED ISSUE #149591: Slider thumb doesn't respect round slider track shape
### Steps to reproduce

Slider Thumb and round track shape has bunch of issues.

1. When dragging the thumb to the start or end of the track in a rounded track shape, the thumb exists the rounded slider track shape and doesn't maintain rounded corners.

### Actual results

| Start | End |
| --------------- | --------------- |
|  |  |

### Expected results

| Start | End |
| --------------- | --------------- |
|  |  |

2. Active track doesn't be show be drawn if the thumb is at the start of the rounded track shape and it's radius lower than track radius. Likewise, inactive track shouldn't be drawn if the thumb is at the end of the rounded track shape.

### Actual results

| Start | End |
| --------------- | --------------- |
|  |  |

### Expected results

| Start | End |
| --------------- | --------------- |
|  |  |

3.  All corners in active and inactive tracks segments should be rounded in a rounded track shape.

#### Active track corners

Screenshot 2024-06-03 at 16 02 45

#### Inactive track corners

Screenshot 2024-06-03 at 16 02 59

#### Active track corners
Screenshot 2024-06-03 at 16 03 18

#### Inactive track corner
Screenshot 2024-06-03 at 16 03 10

### Expected results

~

### Actual results

~

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double _value = 0.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        sliderTheme: const SliderThemeData(
          trackHeight: 32,
          thumbColor: Colors.green,
          // thumbColor: Colors.green.withOpacity(0.5),
          // activeTrackColor: Colors.red.withOpacity(0.5),
          inactiveTrackColor: Colors.amber,
          trackShape: RoundedRectSliderTrackShape(),
        ),
      ),
      home: Scaffold(
        body: Slider(
          value: _value,
          // divisions: 5,
          // label: _value.toStringAsFixed(2),
          // ignore: avoid_redundant_argument_values
          min: 0,
          max: 10,
          onChanged: (double value) {
            setState(() {
              _value = value;
            });
          },
        ),
      ),
    );
  }
}



```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [[Slider] Thumb's center doesn't align with division's center](https://github.com/flutter/flutter/issues/62567)
fixes [Slider thumb doesn't respect round slider track shape](https://github.com/flutter/flutter/issues/149591)
fixes [`RoundedRectSliderTrackShape` corners are not rendered correctly](https://github.com/flutter/flutter/issues/149589)

(Verified these behaviors with Android components implementation)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double _value = 5.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        sliderTheme: const SliderThemeData(
          trackHeight: 32,
          thumbColor: Colors.green,
          activeTrackColor: Colors.deepPurple,
          inactiveTrackColor: Colors.amber,
        ),
      ),
      home: Scaffold(
        body: Slider(
          value: _value,
          // divisions: 10,
          // ignore: avoid_redundant_argument_values
          min: 0,
          max: 10,
          onChanged: (double value) {
            setState(() {
              _value = value;
            });
          },
        ),
      ),
    );
  }
}
```

</details>

### Description
This PR fixes several core `Sliders` issues which are apparent in https://github.com/flutter/flutter/pull/147783. As a result, fixing the these bugs will unblock it.

### 1. Fixes the thumb doesn't align with `Slider` divisions.

Group 8

Group 9

### 2.  Fixes `RoundedRectSliderTrackShape` corners are not rendered correctly.

Group 10

 
### 3.  Fixes round track shape corners when the thumb is at the start or end of the round track shape.

Group 4

Group 3

Group 7

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by Piinks** [comment]
Pinging to my inbox so it's in my queue. 👍

File: packages/flutter/lib/src/material/slider.dart [hunk 1]
```diff
@@ -1650,7 +1650,22 @@ class _RenderSlider extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
       sliderTheme: _sliderTheme,
       isDiscrete: isDiscrete,
     );
-    final Offset thumbCenter = Offset(trackRect.left + visualPosition * trackRect.width, trackRect.center.dy);
+    final double padding = isDiscrete || _sliderTheme.trackShape is RoundedRectSliderTrackShape ? trackRect.height : 0.0;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/slider.dart:1653]: Do we use `is` a lot in the slider code like this?

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 2]
```diff
@@ -1715,28 +1715,34 @@ class RoundedRectSliderTrackShape extends SliderTrackShape with BaseSliderTrackS
...
-      ),
-      rightTrackPaint,
-    );
+    final bool drawInactiveTrack = thumbCenter.dx < (trackRect.right - (sliderTheme.trackHeight! / 2));
+    if (drawInactiveTrack) {
+      // Draw the inactive track segment.
+      context.canvas.drawRRect(
+        RRect.fromLTRBR(
+          thumbCenter.dx - (sliderTheme.trackHeight! / 2),
+          (textDirection == TextDirection.rtl) ? trackRect.top - (additionalActiveTrackHeight / 2) : trackRect.top,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/slider_theme.dart:1724]: Since this is repeated, can you just store textDirection == TextDirection.rtl in a bool?

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 3]
```diff
@@ -1715,28 +1715,34 @@ class RoundedRectSliderTrackShape extends SliderTrackShape with BaseSliderTrackS
...
+        rightTrackPaint,
+      );
+    }
+    final bool drawActiveTrack = thumbCenter.dx > (trackRect.left + (sliderTheme.trackHeight! / 2));
+    if (drawActiveTrack) {
+      // Draw the active track segment.
+      context.canvas.drawRRect(
+        RRect.fromLTRBR(
+          trackRect.left,
+          (textDirection == TextDirection.ltr) ? trackRect.top - (additionalActiveTrackHeight / 2): trackRect.top,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/slider_theme.dart:1738]: Same here re: textDirection == TextDirection.ltr

File: packages/flutter/lib/src/material/slider.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/slider.dart:1653]: Maybe instead of `is`, `RoundedRectSliderTrackShape` and others can contains a getter for this?

File: packages/flutter/lib/src/material/slider_theme.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/slider_theme.dart]: Sure! Added `isLTR` and `isRTL`.

File: packages/flutter/lib/src/material/slider.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/slider.dart]: Excellent idea! Added `isRounded` getter. Please let me know what do you think.

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 4]
```diff
@@ -1117,6 +1117,9 @@ abstract class SliderTrackShape {
     bool isDiscrete,
     required TextDirection textDirection,
   });
+
+  /// Whether the track shape is rounded.
+  bool get isRounded;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/slider_theme.dart:1122]:
```suggestion
  ///
  /// This is used to determine the correct position of the thumb in relation to the track.
  bool get isRounded;
```

**Review by Piinks — APPROVED** [review]
LGTM! Thanks for your patience @TahaTesser 🙏

**Comment by TahaTesser** [comment]
@Piinks 
Rebased and even pushed empty commit, it seems Google testing is failing.

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 5]
```diff
@@ -1117,6 +1117,11 @@ abstract class SliderTrackShape {
     bool isDiscrete,
     required TextDirection textDirection,
   });
+
+  /// Whether the track shape is rounded.
+  ///
+  /// This is used to determine the correct position of the thumb in relation to the track.
+  bool get isRounded;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/slider_theme.dart:1124]: Is is possible to give a default value here? This will break anyone that `extends` SliderTrackShape.

**Review by justinmc — COMMENTED** [review]
The goldens changes look like they're only due to slight changes in the rounded corners of the track (seems expected).

In the Google  tests I see a bunch of visual diff tests related to the position of the thumb and sometimes its label (seems expected), but also I see breakages of classes that `extends` SliderTrackShape.

File: packages/flutter/lib/src/material/slider_theme.dart (hunk 5 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/slider_theme.dart]: Thank you!

**Comment by justinmc** [comment]
It looks like there are still breakages of classes that use `implements` with SliderTrackShape because they don't have an implementation of `isRounded`. I always have to refresh myself on this in Dart, so to be specific:

```dart
abstract class Foo {
  bool get isRounded => false;
}

// Error, missing implementation of isRounded (even though Foo has an implementation).
class Bar implements Foo {
}

// No error.
class Baz extends Foo {
}
```

Some options to move forward here:

 1. Modify this PR so that it does not cause a breakage. It looks doable but I don't know if it would make the code ugly, what do you think?
 2. Keep the PR as-is and migrate all of the broken users, and follow the [breaking changes policy](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes). There are 200+ breakages in the Google tests due to this, though I'm guessing the number of places I'd have to add `isRounded` is not that many. The code change should be straightforward. I think this is doable is we decide to do it.
 3. Keep isRounded, but also make changes to mitigate this kind of breakage in the future. Maybe SliderTrackShape should have been an `abstract base class` to prevent users from using `implements` with it ([docs on Dart's newish class modifiers](https://dart.dev/language/class-modifiers))? Maybe we could deprecate SliderTrackShape and move to a new base class without causing an immediate hard breaking change?  We would still have to do all of the work from option 2, but this might be better for broken users and better for the long term maintainability of this code.

**Comment by Piinks** [comment]
Hmm, maybe we can add a g3 fix in frob to add the getter for folks that have `implements`? I've also in the past changed the customer's code toe `extends` temporarily, or permanently if they agree, to unblock changes like these.

**Comment by TahaTesser** [comment]
Thanks @justinmc!

> Modify this PR so that it does not cause a breakage. It looks doable but I don't know if it would make the code ugly, what do you think?

I noticed `RoundedRectSliderTrackShape` and `RectangularSliderTrackShape` doesn't override the `getPreferredRect` from the `SliderTrackShape`, yet they don't throw an error. This is due to all track shapes using `BaseSliderTrackShape` `mixin` with returns a default `getPreferredRect`. 

| updated the PR to return default `isRounded` in the `BaseSliderTrackShape`, since the current track shapes are using this `mixin`, it could be expected the customer's code should be using it too? This solution makes sense since `getPreferredRect` is already handled this way, and `isRounded` is just another addition.

**Comment by justinmc** [comment]
I think that sounds reasonable. I've added the mixin in google3 and am currently running the tests to confirm that it works (Google cl/646532027).

**Comment by justinmc** [comment]
Mixing in BaseSliderTrackShape seems to have fixed the Google tests, except for expected image diff tests, which I've marked for approval. @TahaTesser If the gold tests don't rerun, can you push a merge commit?

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

I've accepted the Golden changes, not sure why it still says "pending". @TahaTesser if it doesn't go green soon, can you push another merge commit?

**Comment by Piinks** [comment]
It cleared. It can take a few minutes to update, no need to push another commit

**Comment by TahaTesser** [comment]
> It cleared. It can take a few minutes to update, no need to push another commit

Oops sorry. i read this comment after pushing empty commit.

**Comment by justinmc** [comment]
Google tests are still just expected image diff failures, approved :+1:

**Comment by hauvudinh24** [comment]
Hi,
Excuse sir, will we fix it in the next version release?
Thank you.

**Comment by TahaTesser** [comment]
@hauvudinh24! 
This seems to be still on the master channel. It should be eventually make it to the next MAJOR stable release.
