### PR TITLE
Fix Status Bar Icon Brightness

### LINKED ISSUE #160305: [android 15] Status bar text not legible with edge to edge and light theme
### Steps to reproduce

1. `flutter create -e flutter_bug`
2. `cd flutter_bug && flutter run`

I am able to reproduce this bug on a Pixel 7a (android 15) both on the latest stable and master channels.

### Expected results

Clearly legible text on the status bar

### Actual results

The status bar text is legible only if the theme of the app is dark

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.28.0-1.0.pre.122, on EndeavourOS 6.12.4-arch1-1, locale
    en_US.UTF-8)
    • Flutter version 3.28.0-1.0.pre.122 on channel master at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7877a076a6 (11 hours ago), 2024-12-13 22:46:08 -0500
    • Engine revision a9f7fa8ca6
    • Dart version 3.7.0 (build 3.7.0-243.0.dev)
    • DevTools version 2.41.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/damiano/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /usr/lib/jvm/java-17-openjdk/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.13+11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE =
      /var/lib/flatpak/app/com.google.Chrome/current/active/files/extra/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.31.2
    • ninja version 1.12.1
    • pkg-config version 2.3.0

[✓] Android Studio (version 2024.2)
    • Android Studio at /opt/android-studio/
    • Flutter plugin version 83.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[!] Android Studio (version unknown)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (3 available)
    • Pixel 7a (mobile) • 37281JEHN00912 • android-arm64  • Android 15 (API 35)
    • Linux (desktop)   • linux          • linux-x64      • EndeavourOS 6.12.4-arch1-1
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jesswrd**
On Android devices, the statusBar is now by default transparent starting android API 35 [here](https://developer.android.com/develop/ui/views/layout/edge-to-edge#:~:text=system%20bars%20transparent) (due to automatic opt-in to edge to edge mode [here](https://developer.android.com/develop/ui/views/layout/edge-to-edge#:~:text=Important%3A%20Edge%2Dto%2Dedge%20is%20enforced%20on%20Android%2015%20(API%20level%2035)%20and%20higher%20once%20your%20app%20targets%20SDK%2035.%20If%20your%20app%20is%20not%20already%20edge%2Dto%2Dedge%2C%20portions%20of%20your%20app%20may%20be%20obscured%20and%20you%20must%20handle%20insets.%20Depending%20on%20the%20app%2C%20this%20work%20may%20or%20may%20not%20be%20significant.)), which is making the statusBar icons difficult to see. We decided to make the change in Cupertino/Material layer as opposed to the embedder layer becasue we cannot make assumptions on the defaults when we don't know what kind of Widgets the Flutter dev will be using.

In MaterialApp, the `statusBarIconBrightness` is made to be dark because the system's brightness (dark mode or light mode) **does not affect** the brightness of the default app. This means when I turn on dark mode on my phone, the app does not use a dark theme—it uses the same light theme.

In CupertinoApp, the `statusBarIconBrightness` is made to be opposite of the system's brightness (dark mode or light mode) because the system **does affect** the brightness of the default app. The system and the default app have the same brightness. This means when I turn on dark mode on my phone, the app also uses a dark theme.

Fixes #160305 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/material_test.dart [hunk 1]
```diff
@@ -284,6 +285,15 @@ void main() {
     expect(pressed, isTrue);
   });
 
+  testWidgets('The status bar icons are dark by default', (WidgetTester tester) async {
```
Comment (reidbaker) [inline packages/flutter/test/material/material_test.dart:288]: Should this test be "the status bar icons are the opposite brightness of the system? 

(related to me not following how ThemeMode works in relation to brightness)

File: packages/flutter/lib/src/material/app.dart [hunk 2]
```diff
@@ -997,6 +997,7 @@ class _MaterialAppState extends State<MaterialApp> {
     // Resolve which theme to use based on brightness and high contrast.
     final ThemeMode mode = widget.themeMode ?? ThemeMode.system;
     final Brightness platformBrightness = MediaQuery.platformBrightnessOf(context);
+
     final bool useDarkTheme =
         mode == ThemeMode.dark ||
         (mode == ThemeMode.system && platformBrightness == ui.Brightness.dark);
```
Comment (reidbaker) [inline packages/flutter/lib/src/material/app.dart:1003]: I am trying to square this code with the review description. I think the default [ThemeMode is system](https://api.flutter.dev/flutter/material/MaterialApp/themeMode.html). Which means that material should also have the ternary logic about brightness. 

That said I trust your evaluation so where am I misunderstanding the code?

File: packages/flutter/test/material/material_test.dart (hunk 1 above)
Comment (jesswrd) [reply packages/flutter/test/material/material_test.dart:288]: In Material app, I don't use the brightness of the system at all to determine the brightness of the icon. This is because the default app's brightness (from `flutter create` or `flutter create -e`) does not change when the system is in dark mode or light mode.

File: packages/flutter/lib/src/material/app.dart (hunk 2 above)
Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1003]: In Material, the system's brightness does not reflect the brightness of the Flutter default app. This means when I turn the phone to dark mode, my app does not use a dark theme—it stays the same. I realize this code block has logic for using the dark theme. It's not triggering when I set the system to dark mode.

If I add ternary logic (similar to my CupertinoApp changes), I see the same bug from the issue where you cannot see the status bar icons.

Also, I updated my description above. Instead of default I just put "made to be." I meant to the user, it looks like the default.

Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1003]: Also that line is there by accident from a previous commit. Deleting that now.

Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart]: [Uploading darkMode_bug.webm…]()

Comment (reidbaker) [reply packages/flutter/lib/src/material/app.dart]: Does this mean that the bug is that material does not respect the phones brightness by default and that it should. That is what the documentation I linked seems to imply. 

@Piinks who on your team might know the history of brightness and its default relationship with system brightness?

File: packages/flutter/lib/src/cupertino/app.dart [hunk 3]
```diff
@@ -12,6 +12,7 @@ library;
 import 'package:flutter/gestures.dart';
 import 'package:flutter/widgets.dart';
 
+import '../../services.dart';
```
Comment (Piinks) [inline packages/flutter/lib/src/cupertino/app.dart:15]: This should be imported as a flutter package, like gestures and widgets above it, rather than a local import.

File: packages/flutter/lib/src/cupertino/app.dart [hunk 4]
```diff
@@ -651,6 +652,13 @@ class _CupertinoAppState extends State<CupertinoApp> {
   Widget build(BuildContext context) {
     final CupertinoThemeData effectiveThemeData = (widget.theme ?? const CupertinoThemeData())
```
Comment (Piinks) [inline packages/flutter/lib/src/cupertino/app.dart:653]: Similar to @reidbaker's comment, should CupertinoThemeData.brightness be considered? Here if the user provides their own theme, they could have the brightness configured to be one way or the other.

File: packages/flutter/lib/src/material/app.dart [hunk 5]
```diff
@@ -1009,6 +1009,11 @@ class _MaterialAppState extends State<MaterialApp> {
       theme = widget.highContrastTheme;
     }
     theme ??= widget.theme ?? ThemeData.light();
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app.dart:1011]: Here too, theme.brightness might be relevant.

File: packages/flutter/test/cupertino/app_test.dart [hunk 6]
```diff
@@ -481,6 +481,39 @@ void main() {
...
+    await tester.pumpWidget(const CupertinoApp(home: CupertinoPageScaffold(child: Text('Hello'))));
+
+    expect(
+      SystemChrome.latestStyle,
+      const SystemUiOverlayStyle(statusBarIconBrightness: Brightness.dark),
+    );
+  });
+
+  testWidgets(
+    'CupertinoApp has the correct default status bar icon brightness when the system is set to dark theme',
```
Comment (Piinks) [inline packages/flutter/test/cupertino/app_test.dart:496]:
```suggestion
    'CupertinoApp has the correct default status bar icon brightness when the system is set to dark',
```

Just a nit suggestion to avoid confusion with device brightness and Theme (from Flutter) brightness. :)

File: packages/flutter/lib/src/material/app.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/app.dart]: I am less familiar with ThemeMode, cc @QuncCccccc for material and @MitchellGoodwin for cupertino. They may have some thoughts.

File: packages/flutter/lib/src/cupertino/app.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/cupertino/app.dart:653]: I think this might be why when you toggle the device light/dark mode, it is not reflected because these *ThemeData classes set the color palette of the app.

Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart:653]: I think for the purposes of addressing the original bug from the issue, we only care about the default Flutter app (what the user sees on `flutter create` or `flutter create -e`). Outside of adding code, I think the user can only change/affect the theme via the system settings. 

Also, if the user provides their own theme (with a brightness), can we assume the user wants to be able to see the status bar icons?

@reidbaker Feel free to weigh in.

Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart:653]: I did try using `CupertinoThemeData.brightness`, but I ran into basically the same bug on dark mode where I could not see the status bar icons because the icons and the color palette of the app were dark.

File: packages/flutter/lib/src/cupertino/app.dart (hunk 3 above)
Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart]: done

File: packages/flutter/test/cupertino/app_test.dart (hunk 6 above)
Comment (jesswrd) [reply packages/flutter/test/cupertino/app_test.dart]: done

File: packages/flutter/lib/src/cupertino/app.dart (hunk 4 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/app.dart:653]: You should use CupertinoThemeData.brightness if available, then fallback MediaQuery.platformBrightness if not. Otherwise I think this might be a breaking change in some cases.

File: packages/flutter/lib/src/cupertino/app.dart [hunk 7]
```diff
@@ -651,6 +652,13 @@ class _CupertinoAppState extends State<CupertinoApp> {
...
         .resolveFrom(context);
+    final Brightness brightness = MediaQuery.platformBrightnessOf(context);
+
+    SystemChrome.setSystemUIOverlayStyle(
+      SystemUiOverlayStyle(
+        statusBarIconBrightness: brightness == Brightness.dark ? Brightness.light : Brightness.dark,
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/app.dart:659]: Rather than just setting the icon brightness, it's probably better to use SystemUiOverlayStyle.light or SystemUiOverlayStyle.dark so it also sets the contrasting colors as well.

File: packages/flutter/lib/src/cupertino/app.dart (hunk 4 above)
Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart:653]: done

File: packages/flutter/lib/src/material/app.dart (hunk 5 above)
Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1011]: done

File: packages/flutter/lib/src/cupertino/app.dart (hunk 7 above)
Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart]: done

File: packages/flutter/lib/src/material/app.dart [hunk 8]
```diff
@@ -1009,6 +1009,10 @@ class _MaterialAppState extends State<MaterialApp> {
...
+    SystemChrome.setSystemUIOverlayStyle(
+      theme.brightness == Brightness.dark ? SystemUiOverlayStyle.light : SystemUiOverlayStyle.dark,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app.dart:1013]: Should this behave like cupertino above? Check the theme, if not fallback to MediaQuery.platformBrightness?

Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1013]: I actually have that change stashed and ready. I think it makes sense for material to fallback to MediaQuery.platformBrightness (set from system settings), but I checked the default android app and it doesn't look like the system settings affects the app palette theme. 

If we do decide we want to fallback to MediaQuery.platformBrightness, I was thinking of splitting this specific change into a different PR because it addresses a different (potential) bug where the system dark mode does not reflect in the default Flutter app (where no other theme is set). Let me know what you think?

Also @reidbaker want your thoughts too

Comment (reidbaker) [reply packages/flutter/lib/src/material/app.dart:1013]: Can you give me a more specific think you want thoughts on? Going over the high level that we have discussed before. 

We could fix this specific bug at the example app level, at the theme level (cupertino/material) or at the embedder level. We chose the theme level because we thought it would help the most users without being wrong. What @Piinks is suggesting is aligned with that goal (assuming it works).

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/app.dart:1013]: > I checked the default android app and it doesn't look like the system settings affects the app palette theme.

Do you mean the starter counter app? I believe that one is locked to light theme. If you add a darkTheme to it, it should switch between the two with this code as is, since platform brightness is checked above. @QuncCccccc does that sound right?

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/app.dart:1013]: Yes. Adding a `darkTheme: ThemeData(brightness: Brightness.dark)` should make the app be able to switch between light and dark:)

File: packages/flutter/test/material/material_test.dart [hunk 9]
```diff
@@ -284,6 +285,30 @@ void main() {
     expect(pressed, isTrue);
   });
 
+  testWidgets('Material uses the dark SystemUIOverlayStyle when the background is light', (
+    WidgetTester tester,
+  ) async {
+    final ThemeData lightTheme = ThemeData(useMaterial3: true);
```
Comment (QuncCccccc) [inline packages/flutter/test/material/material_test.dart:291]: super nit: `useMaterial3` defaults to true:) 
```suggestion
    final ThemeData lightTheme = ThemeData();
```

File: packages/flutter/test/material/material_test.dart [hunk 10]
```diff
@@ -284,6 +285,30 @@ void main() {
...
+    );
+
+    expect(lightTheme.colorScheme.brightness, Brightness.light);
+    expect(SystemChrome.latestStyle, SystemUiOverlayStyle.dark);
+  });
+
+  testWidgets('Material uses the light SystemUIOverlayStyle when the background is dark', (
+    WidgetTester tester,
+  ) async {
+    final ThemeData darkTheme = ThemeData.dark(useMaterial3: true);
```
Comment (QuncCccccc) [inline packages/flutter/test/material/material_test.dart:303]: same nit here:)

**Review by QuncCccccc — APPROVED** [review]
LGTM:)

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Looks like the analyzer is unhappy about the sample code in system_chrome.dart.

File: packages/flutter/lib/src/material/app.dart (hunk 8 above)
Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1013]: @QuncCccccc Yeah, I think it's a litte strange one has to use `darkTheme` **AND** set the system setting to `Dark Theme` to see dark theme reflected in the Flutter app. I'm drafting up a doc right now. I'm trying to investigate if that's a bug or not.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/app.dart:1013]: I don't think it's a bug. We want people to be able to set their app to either a light or dark theme, and ignore the system brightness if they wish. It's just confusing, especially because Cupertino and Material both handle it differently.

File: packages/flutter/test/material/material_test.dart (hunk 9 above)
Comment (jesswrd) [reply packages/flutter/test/material/material_test.dart]: done

File: packages/flutter/test/material/material_test.dart (hunk 10 above)
Comment (jesswrd) [reply packages/flutter/test/material/material_test.dart]: done

**Comment by QuncCccccc** [comment]
To fix the analyzer complaint, we can add
```
// Examples can assume:
// late BuildContext context;
...
```
on top of the file (below imports).

File: packages/flutter/lib/src/cupertino/app.dart [hunk 11]
```diff
@@ -651,6 +652,12 @@ class _CupertinoAppState extends State<CupertinoApp> {
   Widget build(BuildContext context) {
     final CupertinoThemeData effectiveThemeData = (widget.theme ?? const CupertinoThemeData())
         .resolveFrom(context);
+    final Brightness brightness =
```
Comment (reidbaker) [inline packages/flutter/lib/src/cupertino/app.dart:655]: A comment here similar to what Mitchell said in https://github.com/flutter/flutter/pull/162297/files#r1938130383 could help understandability. 

```suggestion
    // Prefer theme brightness if set, otherwise check system brightness. 
    final Brightness brightness =
```

**Review by reidbaker — APPROVED** [review]

File: packages/flutter/lib/src/material/app.dart (hunk 8 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/app.dart:1013]: The material `theme.brightness` won't be null, so I think checking `theme.brightness` only makes sense. 

I think the logic here is to check media query first(line 999) to see whether we want to use dark theme (whether `useDarkTheme` is true), then, we check whether we have a dark theme. If both yes, then theme.brightness is dark; if yes, then no, we still default theme to light theme, so we should still have `SystemUiOverlayStyle.dark` to  make sure the enough contrast:)

Comment (jesswrd) [reply packages/flutter/lib/src/material/app.dart:1013]: @reidbaker I think the conclusion is to keep it as is (only check theme brightness and not fall back to media query). It's the existing and intended behavior.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/app.dart:1013]: The conclusion is that this is correct.

The check for media query brightness happened already at line 999. By the time the code gets to this the `theme` can be trusted have the correct brightness based on the combination of media query data and theme settings available.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/app.dart:1013]: 🤣 the rare triple simultaneous response

Comment (reidbaker) [reply packages/flutter/lib/src/material/app.dart:1013]: thank you all

File: packages/flutter/lib/src/cupertino/app.dart (hunk 11 above)
Comment (jesswrd) [reply packages/flutter/lib/src/cupertino/app.dart:657]: done

File: packages/flutter/lib/src/material/app.dart
Comment (LailaiMaster) [inline packages/flutter/lib/src/material/app.dart:1]: I strongly oppose this PR because the changes have completely broken existing configuration methods. For example, the following code no longer works as intended:
`void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle(
      statusBarIconBrightness:
          WidgetsBinding.instance!.platformDispatcher.platformBrightness ==
                  Brightness.light
              ? Brightness.dark
              : Brightness.light,
    ),
  );
  runApp(const MainApp());
}`
This modification has caused regression in functionality that was previously working correctly.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/app.dart:1]: Please direct comments towards the open issue around this behavior. Merged PRs are difficult to track discussion on.
