### PR TITLE
PageView resize from zero-size viewport should not lose state

### LINKED ISSUE #55262: [windows] PagView shows page one when window is minimized
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
//visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: new PageView(
      children: [
        new Container(
          child: new Center(child: new Text("0")),
        ),
        new Container(
          child: new Center(child: new Text("1")),
        ),
        new Container(
          child: new Center(child: new Text("2")),
        ),
      ],
    ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}

```

PageView控件****************
The above code works fine on the phone
but On Windows
When the PageView slides to the second page, it is minimized and then opened. The PageView shows the first page

### LINKED ISSUE #64718: TabBarView always change to the first one after minimize the application window in flutter for windows
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the lib/main.dart as follows: ... 

```
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}

```
3. flutter run -d windows
switch tab to second or third tab, minimize application and reopen it.

**Expected results:** 
TabBarView should be synced with tabbar.
**Actual results:** 
First TabBarView is shown. See the picture:
Capturer_gif_20200827_215419_317

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.93, on Microsoft Windows [Version 10.0.18363.1016], locale zh-CN)
    • Flutter version 1.22.0-2.0.pre.93 at F:\flutter
    • Framework revision f35a8b7470 (9 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\Android_SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = F:\Android_SDK
    X Android SDK file not found: F:\Android_SDK\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at F:\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\zouji\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.18363.1016]

! Doctor found issues in 1 category.
```

</details>
BTW, I cannot reproduce this in flutter for macos.

### LINKED ISSUE #88956: PageView resize from zero-size viewport will lose state
### Simple Code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(A());
}

class A extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _AState();
  }

}

class _AState extends State<A> {
  double size = 100.0;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              setState(() {
                if (size == 100) {
                  size = 0;
                } else {
                  size = 100;
                }
              });
            },
          ),
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: SizedBox(
            width: size,
            height: size,
            child: TabBarView(
              children: [
                Icon(Icons.directions_car),
                Icon(Icons.directions_transit),
                Icon(Icons.directions_bike),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

### Repro Step
1, switch tab to second or third tab
2, click the floatingActionButton to change the size to zero
3, click it again and TabBarView lose state (switch to the first page)

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

PageView resize from zero-size viewport should not lose state, otherwise will cause `TabBar` and `TabBarView` mismatch, see #64718 

In `_PagePosition.applyViewportDimension`, If the viewport has a zero-size, the `page` can not be got by `getPageFromPixels`, so we need to cache the page for use when resizing the viewport to non-zero next time.

## Related Issues

I have filed a new issue to reproduce this bug.
Fixes #88956 

The following issues behaviors can not reproduce because the windows platform change some behaviors. 
Fixes #64718 
Fixes #55262 

## Tests

I added the following tests:

See files.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 1]
```diff
@@ -431,13 +431,17 @@ class RangeMaintainingScrollPhysics extends ScrollPhysics {
...
-    if (oldPosition.pixels < oldPosition.minScrollExtent) {
-      final double oldDelta = oldPosition.minScrollExtent - oldPosition.pixels;
-      return newPosition.minScrollExtent - oldDelta;
-    }
-    if (oldPosition.pixels > oldPosition.maxScrollExtent) {
-      final double oldDelta = oldPosition.pixels - oldPosition.maxScrollExtent;
-      return newPosition.maxScrollExtent + oldDelta;
+    // If resize from zero, recover position from cache, so don't try to
+    // maintain the relative overscroll.
+    if (oldPosition.minScrollExtent != 0.0 || oldPosition.maxScrollExtent != 0.0) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/scroll_physics.dart:436]: @Hixie Hi, Please review here, in this case, the _PagePosition.applyViewportDimension will correct the pixels due to resizing from zero, (such as oldPosithon is (pixels: 800, minScrollExtent : 0.0, maxScrollExtent: 0.0)) and it will cause `RangeMaintainingScrollPhysics.adjustPositionForNewDimensions` mistake maintain the relative overscroll.
In addition, if the #63146 reland, we can remove this check and it works well.

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 2]
```diff
@@ -414,9 +417,23 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
...
+      page = getPageFromPixels(oldPixels, oldViewportDimensions);
+    }
+
     final double newPixels = getPixelsFromPage(page);
 
+    // Cache the page when resize the viewport to zero.
+    // For use when resize the viewport to non-zero next time.
+    _cachePage = (viewportDimension == 0.0) ? page : null;
+
     if (newPixels != oldPixels) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/page_view.dart:437]: Maybe here need to use `nearEqual`, I am not sure.

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 3]
```diff
@@ -414,9 +417,23 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
...
+      page = _cachePage;
+    } else {
+      page = getPageFromPixels(oldPixels, oldViewportDimensions);
+    }
+
     final double newPixels = getPixelsFromPage(page);
 
+    // Cache the page when resize the viewport to zero.
+    // For use when resize the viewport to non-zero next time.
+    _cachePage = (viewportDimension == 0.0) ? page : null;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/page_view.dart:435]: In another extreme case, assuming that the viewport is very small, only 1 pixel, I ignore the processing of this kind of scene.

File: packages/flutter/lib/src/widgets/scroll_physics.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/scroll_physics.dart:436]: I'll try to land the old PR again to make this moot.

Comment (Hixie) [reply packages/flutter/lib/src/widgets/scroll_physics.dart:436]: (but with && -> ||)

**Comment by Hixie** [comment]
This seems reasonable, though I get this niggling feeling that it really means our whole design here is wrong, and that we should be deriving the pixel position from the page and not the other way around.

Let's wait until the RangeMaintainingScrollPhysics fix relands before landing this though, just to keep things simple...

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/65135 is the new fix for RangeMaintainingScrollPhysics.

**Comment by xu-baolin** [comment]
> This seems reasonable, though I get this niggling feeling that it really means our whole design here is wrong, and that we should be deriving the pixel position from the page and not the other way around.
> 
> Let's wait until the RangeMaintainingScrollPhysics fix relands before landing this though, just to keep things simple...

So you suggest that we should record the page in real-time, as long as the pixels change, and deprecate `getPageFromPixels`, right?

**Comment by Hixie** [comment]
I'm imagining a world where the "pixels" getter returns a value derived from the "page" field. But I don't know if the design even makes that possible. You definitely don't need to try to implement that if you don't want to. It might be somewhat involved.

**Comment by Hixie** [comment]
BTW the RangeMaintainingScrollPhysics has landed again, hopefully it sticks this time...

**Comment by xu-baolin** [comment]
> I'm imagining a world where the "pixels" getter returns a value derived from the "page" field. But I don't know if the design even makes that possible. You definitely don't need to try to implement that if you don't want to. It might be somewhat involved.

How about open a new topic to discuss how to refactor it？I totally agree that this will be a bit complicated :)
 The PR looks very strong this time!

**Comment by xu-baolin** [comment]
@Hixie Hi,
Review requested by manually : )

**Comment by iskakaushik** [comment]
cc: @iskakaushik for looking at pausing the animator on 0 size window update.

**Comment by xu-baolin** [comment]
@dnfield Hi,
Would you like to take a look at this? Thanks :)

**Comment by dnfield** [comment]
@iskakaushik - are you saying that if we paused the animator in this case (which it seems like we should), we'd avoid this bug? 

I'm not clear on how the viewport metrics are getting updated on Windows in the minimize case. It seems like we should be resolving that before doing anything else with this bug. IOW, it seems to me that getting a zero sized viewport shouldn't be happening when you minimize the window - but the animator should be paused.

**Comment by iskakaushik** [comment]
@dnfield Yup. I will try to take a look at this sometime this week. IMO app minimization should be treated as application resigning from being active, we should re-use the last drawn frame and show it when the app becomes active again. I need to look at what macOS / Windows provide for us to achieve this behavior. I think the fix will be in the engine and not require us to handle 0 size window metrics events.

**Comment by dnfield** [comment]
When we get the WM_SIZE message we should be checking whether the wparam is SIZE_MINIMIZED https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size?redirectedfrom=MSDN for Windows

**Comment by xu-baolin** [comment]
Actually, this is not a platform-related patch, setting the size to 0 will also trigger this bug in all the platforms.

**Comment by Piinks** [comment]
@xu-baolin, can you update this PR if you would like to proceed with the change? I'd be happy to take a look if you would still like to land it. Thank you!

**Comment by xu-baolin** [comment]
> @xu-baolin, can you update this PR if you would like to proceed with the change? I'd be happy to take a look if you would still like to land it. Thank you!

OK

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 4]
```diff
@@ -431,9 +435,22 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
...
+      // If resize from zero, we should use the _cachedPage to recover the state.
+      assert(_cachedPage != null);
+      page = _cachedPage!;
+    } else {
+      page = getPageFromPixels(oldPixels, oldViewportDimensions!);
+    }
     final double newPixels = getPixelsFromPage(page);
 
+    // Cache the page when resize the viewport to zero.
+    // For use when resizing the viewport to non-zero next time.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/page_view.dart:451]:
```suggestion
    // If the viewportDimension is zero, cache the page
    // in case the viewport is resized to be non-zero.
```

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 5]
```diff
@@ -325,6 +325,10 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
 
   final int initialPage;
   double _pageToUseOnStartup;
+  // When the viewport has a zero-size, the `page` can not
+  // be got by `getPageFromPixels`, so we need to cache the page
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/page_view.dart:329]:
```suggestion
  // be retrieved by `getPageFromPixels`, so we need to cache the page
```

**Review by Piinks — APPROVED** [review]
I think this is a good change. It is not addressing a platform specific bug as mentioned above, and it is very easy to reproduce this bug just by resizing the window on Mac to be very small. Thank you for another contribution @xu-baolin, and for updating it after so much time. :)

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 6]
```diff
@@ -370,7 +384,8 @@ class _PagePosition extends ScrollPositionWithSingleContext implements PageMetri
   double get _initialPageOffset => math.max(0, viewportDimension * (viewportFraction - 1) / 2);
 
   double getPageFromPixels(double pixels, double viewportDimension) {
-    final double actual = math.max(0.0, pixels - _initialPageOffset) / math.max(1.0, viewportDimension * viewportFraction);
+    assert(viewportDimension > 0.0);
+    final double actual = math.max(0.0, pixels - _initialPageOffset) / (viewportDimension * viewportFraction);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/page_view.dart:388]: `math.max(1.0, viewportDimension * viewportFraction)` -> `(viewportDimension * viewportFraction)`

This fixes the issue when the viewport is less than 1.0 although it is not common.

**Comment by xu-baolin** [comment]
@Piinks hi, I have added more changes to make sure that all work well when the viewport's size is zero.

**Review by Piinks — APPROVED** [review]
Thanks for the updates @xu-baolin! LGTM
