### PR TITLE
Remove abi key from local golden file testing

### LINKED ISSUE #149435: Golden file tests don't work locally
### Steps to reproduce

Run `flutter test` in `packages/flutter`

### Expected results

Golden file tests should have some functionality.

### Actual results

I get the message: 

```
No expectations provided by Skia Gold for test: cupertino.switch.tap.off.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org.
```

Equivalent of #144496.

### Code sample

None

### Screenshots or Video

None

### Logs

```
flutter test /Users/victorsanni/development/flutter/packages/flutter/test/cupertino/switch_test.dart
```

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.22.0-14.0.pre.48, on macOS 14.5 23F79 darwin-arm64, locale en)
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/149435

CI does not comprehensively cover all of the possible abi keys, so some folks can't test locally if their machine's abi does not match CI. This just removes it from the local testing look up. The right image will be summoned, and in CI we can still keep track of it.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter_goldens/lib/skia_client.dart [hunk 1]
```diff
@@ -579,7 +579,11 @@ class SkiaGoldClient {
     final Map<String, Object?> parameters = <String, Object?>{
       if (_isBrowserTest)
         'Browser' : _browserKey,
-      'Abi': '$abi',
+      // This method is only used in local testing to look up the given image.
+      // CI is not comprehensive in possible abi keys, so false negatives can
+      // be produced if we include it in local testing, for example CI uses
```
Comment (victorsanni) [inline packages/flutter_goldens/lib/skia_client.dart:584]: Small comment nits: `testing, for` -> `testing. For` and `but a contributor could have macos_arm64` -> `but a contributor could have macos_arm64.`

**Review by victorsanni — APPROVED** [review]
LGTM!
