### PR TITLE
flutter_tools: Copy vendored frameworks from plugin podspecs in ios/macos-framework builds

### LINKED ISSUE #125530: flutter build ios-framework ignore plugin vendored_frameworks
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

download attach demo,  run  `flutter build ios-framework --no-debug --no-release` .

in `fair` plugin, it uses `FairDynamicFlutter.framework`.

`fair.podspec` as following:

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint fair.podspec' to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'fair'
  s.version          = '0.0.1'
  s.summary          = 'A new Flutter plugin.'
  s.description      = <<-DESC
A new Flutter plugin.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'

  # s.preserve_paths = 'FairDynamicFlutter/Products/FairDynamicFlutter.framework'
  s.vendored_frameworks = 'FairDynamicFlutter/Products/FairDynamicFlutter.framework'
  s.xcconfig = { 
    'OTHER_LDFLAGS' => '-ObjC'
  }
  s.pod_target_xcconfig = { 'VALID_ARCHS' => 'x86_64 armv7 arm64 arm64e armv7s' }
  s.requires_arc = true
  s.static_framework      = true

end
```

### Expected results

`FairDynamicFlutter.framework` is in build/release folder.

### Actual results

`FairDynamicFlutter.framework` is not in build/release folder.

### Code sample

 
[flutter_module.zip](https://github.com/flutter/flutter/files/11328538/flutter_module.zip)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/zmtzawqlp/Documents/flutter/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zmtzawqlp/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/zmtzawqlp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by MohammedTarigg**
Fixes #125530

When running `flutter build ios-framework` or `flutter build macos-framework`, vendored frameworks declared in plugin podspecs (via `s.vendored_frameworks`) were not being copied to the output directory.

This PR adds support for parsing plugin podspecs to find vendored_frameworks entries and copying them to the output directory. Single .framework files are wrapped into xcframeworks to match the output format.

Changes:
- Added `copyVendoredFrameworks` method to `BuildFrameworkCommand` base class
- Added `parseVendoredFrameworks` function to parse podspec Ruby files
- Called from both iOS and macOS framework build commands
- Added unit tests for the podspec parser

I'm happy to adjust the approach if there's a better way to handle this - particularly around the regex-based podspec parsing. Let me know if this looks reasonable or if you'd prefer a different strategy.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 1]
```diff
@@ -180,6 +181,140 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+        processedFrameworks.add(binaryName);
+
+        // Check if it's already an xcframework
+        if (frameworkName.endsWith('.xcframework')) {
+          // Copy the xcframework directly
+          final source = frameworkEntity as Directory;
+          final Directory destination = modeDirectory.childDirectory(frameworkName);
+          if (!destination.existsSync()) {
+            globals.logger.printTrace('Copying vendored xcframework: $frameworkName');
+            copyDirectory(source, destination);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: @vashworth do you have concerns this will cause unintended consequences when a plugin supports both CoocaPods and Swift Package Manager?

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 2]
```diff
@@ -180,6 +181,140 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+/// In Ruby, the last assignment wins, so if there are multiple assignments,
+/// only the last one is used.
+///
+/// Returns an empty list if no vendored_frameworks are found.
+List<String> parseVendoredFrameworks(String podspecContents) {
+  // This regex finds all assignments to `vendored_frameworks`.
+  // It captures either a single quoted string or an array literal.
+  // Group 1: single string content, Group 2: array content
+  final pattern = RegExp(
+    r'''^\s*[a-zA-Z_]+\.vendored_frameworks\s*=\s*(?:["']([^"']+)["']|\[([^\]]*)\])''',
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: This does not take into account when a vendored_framework is per platform, such as
```
spec.ios.vendored_frameworks = 'Frameworks/MyFramework.framework'
```

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 3]
```diff
@@ -180,6 +181,140 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+
+  // Group 1 is single string content, group 2 is array content.
+  final String? singleValue = lastMatch.group(1);
+  final String? arrayContent = lastMatch.group(2);
+
+  if (singleValue != null) {
+    if (singleValue.isNotEmpty) {
+      results.add(singleValue);
+    }
+  } else if (arrayContent != null) {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]:
```suggestion
  if (singleValue != null && singleValue.isNotEmpty) {
    results.add(singleValue);
  } else if (arrayContent != null) {
```

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: I'm planning on introducing a new command when we do add SwiftPM support for add to app. So this will need to be adjusted (to limit it to CocoaPods-only plugins) and added to the new command, but I don't see any major conflicts

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 4]
```diff
@@ -180,6 +181,140 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+    // Extract individual paths from the array content.
+    final pathPattern = RegExp(r'''["']([^"']+)["']''');
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Podspec syntax allows wildcard patterns such as:

```
s.vendored_frameworks = '**/*.xcframework'
```

https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns

Comment (vashworth) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Trying to match all the patterns seems overcomplicated. We could just try to match the most basic and accept it as a limitation for now since this would still be an improvement to what is.

I wonder if perhaps instead of parsing the podspec, the `ios/Pods/Pods.xcodeproj/project.pbxproj` could be parsed (using `PlistParser`) to find any children found in PBXGroups called "Frameworks".

File: packages/flutter_tools/test/commands.shard/hermetic/build_darwin_framework_test.dart
Comment (vashworth) [inline packages/flutter_tools/test/commands.shard/hermetic/build_darwin_framework_test.dart:1]: There should be unit tests for `copyVendoredFrameworks` too

**Comment by vashworth** [comment]
Overall, I think this looks good, but we still need unit tests for `copyVendoredFrameworks`

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 5]
```diff
@@ -180,6 +182,184 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+          frameworkPath.contains('Flutter.xcframework') ||
+          frameworkPath.contains('App.framework') ||
+          frameworkPath.contains('App.xcframework')) {
+        continue;
+      }
+
+      // Framework path is relative to the Pods directory
+      final String absolutePath = globals.fs.path.normalize(
+        globals.fs.path.join(podsRoot.path, frameworkPath),
+      );
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:333]:
```suggestion
      final String absolutePath = globals.fs.path.normalize(
        // CocoaPods uses virtual groups, which don't have actual directory locations. This offsets
        // the relative path incorrectly. Remove the first 3 paths to account for the virtual
        // groups "Development Pods/[plugin_name]/Frameworks".
        globals.fs.path.join(podsRoot.path, frameworkPath.replaceFirst('../../../', '')),
      );
```

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 6]
```diff
@@ -180,6 +182,184 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+
+    final processedFrameworks = <String>{};
+    final Directory podsRoot = hostAppRoot.childDirectory('Pods');
+
+    for (final frameworkPath in frameworkPaths) {
+      // Skip Flutter's own frameworks
+      if (frameworkPath.contains('Flutter.framework') ||
+          frameworkPath.contains('Flutter.xcframework') ||
+          frameworkPath.contains('App.framework') ||
+          frameworkPath.contains('App.xcframework')) {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: This was incorrectly matching when Flutter was at the end of the framework name such as `FairDynamicFlutter.framework`

```suggestion
      if (frameworkPath.contains('/Flutter.framework') ||
          frameworkPath.contains('/Flutter.xcframework') ||
          frameworkPath.contains('/App.framework') ||
          frameworkPath.contains('/App.xcframework')) {
```

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 7]
```diff
@@ -180,6 +182,184 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+        if (!destination.existsSync()) {
+          globals.logger.printTrace('Copying vendored xcframework: $frameworkName');
+          copyDirectory(frameworkEntity, destination);
+        }
+      } else if (frameworkName.endsWith('.framework')) {
+        // Create an xcframework from the single framework
+        final Directory xcframeworkOutput = modeDirectory.childDirectory('$binaryName.xcframework');
+        if (!xcframeworkOutput.existsSync()) {
+          globals.logger.printTrace('Creating xcframework from vendored framework: $frameworkName');
+          await BuildFrameworkCommand.produceXCFramework(
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: This failed with an error `binaries with multiple platforms are not supported`... I'm not sure if that's fixable. Looks at what CocoaPods does, it appears that they just copy and embed the framework as is. They don't wrap it in an xcframework. We should probably do the same. So instead, just copy it to the `modeDirectory`

**Review by vashworth — COMMENTED** [review]
I checked this out locally and tested it with the `fair` plugin and found a few bugs. See comments

**Review by vashworth — APPROVED** [review]
LGTM! @MohammedTarigg Thanks for working through this with me!

**Review by okorohelijah — APPROVED** [review]
there is a merge conflict but LGTM

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 8]
```diff
@@ -276,6 +277,179 @@ abstract class BuildFrameworkCommand extends BuildSubCommand {
...
+        if (!destination.existsSync()) {
+          globals.logger.printTrace('Copying vendored xcframework: $frameworkName');
+          copyDirectory(frameworkEntity, destination);
+        }
+      } else if (frameworkName.endsWith('.framework')) {
+        final Directory destination = modeDirectory.childDirectory(frameworkName);
+        if (!destination.existsSync()) {
+          globals.logger.printTrace('Copying vendored framework: $frameworkName');
+          copyDirectory(frameworkEntity, destination);
+        }
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: these 2 seems identical?

Comment (MohammedTarigg) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: > these 2 seems identical?

Yep, you’re right. I missed that these two blocks ended up identical (other than the trace text). I’ll follow up with a small refactor to dedupe them without changing behavior.
