### PR TITLE
fixes sliver list child layout offset calculation

### LINKED ISSUE #42142: Incorrect index when prepending widget in listview
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<int> items = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]; //init list of items
  void _addItem({bool append}) {
    var now = DateTime.now().millisecondsSinceEpoch;
    if (append) {
      items.add(now);
    } else {
      items.insert(0, now);
    }
    setState(() {
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.custom(
          reverse: false,
          childrenDelegate: SliverChildListDelegate(
            List<Widget>.from(items.map((item) => _buildItem(item, items.indexOf(item))))
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: () => _addItem(append: true),
              child: Text('Append item'),
            ),
            FlatButton(
              onPressed: () => _addItem(append: false),
              child: Text('Prepend item'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItem(int data, int index) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text("index: $index . . . $data"),
        ),
      ),
    );
  }
}

class TestProxy extends StatefulWidget {
  final Widget child;

  const TestProxy({Key key, this.child}) : super(key: key);

  @override
  _TestProxyState createState() => _TestProxyState();
}

class _TestProxyState extends State<TestProxy> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  void initState(){
    super.initState();
    print("");
    //print("Rebuild for ${widget.key.toString()}");
    print("");
  }

  @override
  Widget build(BuildContext context){
    super.build(context);
    return widget.child;
  }
}
```

1. scroll all the way to the end of list
2. click prepend item
3. scroll back to beginning, the item that prepended is not visible, which it should

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

Sliver list layout rely on the first child layout offset is accurate in order to adjust scroll offset and layout offset of remaining children.

If the first child layout offset is inaccurate there are two things that can happens.

1, if first child has layout offset of zero, it will prevent scrollable to scroll back if there is more children above it.

2, the scroll offset will jump after correction.
For example
scroll offset is 1000 and visible children have layout offsets of 1000, 1200, 1400
If the first child layout offset become 0 after reordering. it will update the children layout offsets to 0, 200, 400 with max scroll extent of only 400. This will cause it to overscroll and fire a ballistic scroll animation from 1000 to 400 which result in a jump.

To fix these two issues, I make the default value of layout offset to be null. When a reordering happens, the children that get moved around will have their layout offsets set to null again to indicate the layout offset is inaccurate.

During the layout of sliver_list, it will first check if the first child has null layout offset, and recalculate if needed.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/42142

## Tests

I added the following tests:

'SliverList should recalculate inaccurate layout offset'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_list.dart [hunk 1]
```diff
@@ -90,8 +90,20 @@ class RenderSliverList extends RenderSliverMultiBoxAdaptor {
...
     RenderBox leadingChildWithLayout, trailingChildWithLayout;
 
-    // Find the last child that is at or before the scrollOffset.
     RenderBox earliestUsefulChild = firstChild;
+    // We rely on firstChild to have accurate layout offset. Otherwise, we
+    // have to recalculate layout offset from the start.
+    if (childScrollOffset(firstChild) == null) {
+      while (earliestUsefulChild != null) {
+        assert(firstChild == earliestUsefulChild);
+        earliestUsefulChild = insertAndLayoutLeadingChild(childConstraints, parentUsesSize: true);
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_list.dart]: Re-layouting the entire list seems like a lot of work and the list may be very long.

In the performRebuild of the SliverMultiBoxAdapterElement when we move a keyed element from one slot to another, could we just remember its layout offset for the slot the element was moved from and then re-use that layout offset for the new element we inflate in that slot?

https://github.com/flutter/flutter/blob/357d02c87b75d74382db212812e85a5d7d93dd7f/packages/flutter/lib/src/widgets/sliver.dart#L1162

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: This might create a different behavior when prepend a new item.
Think about this case


```
scroll offset is 1000 and assume all item has 100 paintExtent
-----viewport-----
item10 layoutoffset 1000 paintExtent 100
item11  layoutoffset 1100 paintExtent 100
item12  layoutoffset 1200 paintExtent 100
-------------------


Later on we prepend a bigger item with paintExtent of 500.
If we always inherit layoutoffset of slot, every element will be shifted by 100 pixels
-----viewport-----
item9 layoutoffset 1000 paintExtent 100
item10  layoutoffset 1100 paintExtent 100
item11  layoutoffset 1200 paintExtent 100
-------------------

If we set it to null and recalculate, every element should be shifted by 500 pixels
-----viewport-----
item6 layoutoffset 1000 paintExtent 100
item7  layoutoffset 1100 paintExtent 100
item8  layoutoffset 1200 paintExtent 100
-------------------
```
This difference will become more obvious when the item are more diverse.

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: That would get corrected as you scroll up, though, right? Just like it currently does if you use unkeyed children?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: This might not be to big of a problem. On the other hand, I am also wondering how often this will happen

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: Yes, it will be corrected

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: I think the current behavior is acceptable, it may even be the desired behavior since the promise is that the SliverList is lazy and as long as something is not on screen we don't know how big it is per design.

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: fixed, but I still have to keep this logic here since there is still some cases we won't know the layout offset.

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: What case still requires this code path?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: The test 'SliverList should recalculate inaccurate layout offset case 2' will requires this code path.
If you have
```
-----viewport-----
item10 layoutoffset 1000
item11  layoutoffset 1100
item12  layoutoffset 1200
-------------------
```
and you reorder item 12 to item3 which is not in the viewport. It will not know the current layout offset.

```
-----viewport-----
item12(index 3) layoutoffset ?
item10 layoutoffset 1000
item11  layoutoffset 1100
-------------------

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 2]
```diff
@@ -1157,9 +1157,20 @@ class SliverMultiBoxAdaptorElement extends RenderObjectElement implements Render
...
+          // destination
+          if (_childElements[newIndex] != null) {
+            final SliverMultiBoxAdaptorParentData newParentData = _childElements[newIndex]?.renderObject?.parentData;
+            if (childParentData != newParentData && childParentData != null && newParentData != null) {
+              childParentData.layoutOffset = newParentData.layoutOffset;
+            }
+          }
           newChildren[newIndex] = _childElements[index];
-          // We need to make sure the original index gets processed.
-          newChildren.putIfAbsent(index, () => null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/sliver.dart]: Another important change is it no longer forces the the child in the old index to be repopulate. It will create a child with null layout offset. The old index will be repopulate in performlayout if it is needed.

File: packages/flutter/lib/src/rendering/sliver_list.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: This is unfortunate. I wish we had a way around walking the full list. Especially since (as shown by your test) all this work is essentially thrown away anyways. 

I wonder if we could collect the renderobjects/elements that get moved to indexes before the current start index as garbage so they get removed from the tree for now and we are guaranteed to start with a child that does have a valid layoutOffset.

File: packages/flutter/lib/src/widgets/sliver.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/sliver.dart]: There will be no unintended scrolling.
If this index suppose to be first child and is now missing, perform layout will try to recreate and relayout this child from other existing child, and eventually it will figure out  there is no need to correct scroll offset.

But now i think of it, I might be able to refactor a little bit to make it work. It will just make the algorithm slightly more complicated.

File: packages/flutter/lib/src/rendering/sliver_list.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: There definitely will be case I have to rewalk the tree. However, there are one thing i can do to avoid doing that as much as possible.

try to locate the first child with (layout offset != null && layout offset <= scroll offset + cacheExtent), and use it to find the early useful child, and do a early garbage collect right after that. I think that is a good idea. I will implement that

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: What are the cases where you'll still have to walk the entire tree? The children located at indexes that had children before will always have a valid layout offset, no?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: no you are right. We won't have that as long as I made the change suggested in https://github.com/flutter/flutter/pull/42703/files/9e0777c4e0be3c5f57260d58e9e0d8ad9b6c7229#r341749263

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 3]
```diff
@@ -1146,17 +1147,30 @@ class SliverMultiBoxAdaptorElement extends RenderObjectElement implements Render
         if (newChild != null) {
           _childElements[index] = newChild;
           final SliverMultiBoxAdaptorParentData parentData = newChild.renderObject.parentData;
+          if (index == 0) {
+            parentData.layoutOffset = 0.0;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/sliver.dart]: In the case of underflow, it is possible that the child list only has one child with null layoutoffset. It can only happen when added an element into an empty sliver list. In this case, the child should be in index 0.

File: packages/flutter/lib/src/rendering/sliver_list.dart [hunk 4]
```diff
@@ -90,8 +90,28 @@ class RenderSliverList extends RenderSliverMultiBoxAdaptor {
...
+    // A firstChild with null layout offset is likely a result of children
+    // reordering.
+    //
+    // We rely on firstChild to have accurate layout offset. In the case of null
+    // layout offset, we have to find the first child that has valid layout
+    // offset.
+    if (childScrollOffset(firstChild) == null) {
+      int leadingChildrenWithoutLayoutOffset = 0;
+      while (childScrollOffset(earliestUsefulChild) == null) {
+        earliestUsefulChild = childAfter(firstChild);
```
Comment (boyan01) [inline packages/flutter/lib/src/rendering/sliver_list.dart]: There is a small problem here： If I add multiple elements to the front at the same time, it may cause an endless loop.

```suggestion
        earliestUsefulChild = childAfter(earliestUsefulChild);
```

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart]: oops, nice catch!, will fix it. thanks

**Comment by chunhtai** [comment]
@goderbauer can you take another look at this pr?

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 5]
```diff
@@ -1157,9 +1157,20 @@ class SliverMultiBoxAdaptorElement extends RenderObjectElement implements Render
         final Key key = _childElements[index].widget.key;
         final int newIndex = key == null ? null : widget.delegate.findIndexByKey(key);
         if (newIndex != null && newIndex != index) {
+          // The layout offset of the child being moved is no longer accurate.
+          final SliverMultiBoxAdaptorParentData childParentData = _childElements[index].renderObject?.parentData;
+          if (childParentData != null)
+            childParentData.layoutOffset = null;
```
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/lib/src/widgets/sliver.dart]: @chunhtai and I walked this scenario through, the layoutOffset is being kept track of with indexToLayoutOffset

**Review by Piinks — APPROVED** [review]
This LGTM. :)
