### PR TITLE
Fix concurrent modification error

### LINKED ISSUE #48896: Concurrent modification error in iOS device discovery
From crash logging:

```
ConcurrentModificationError: Concurrent modification during iteration: Instance(length:0) of '_GrowableList'
  | at ListIterator.moveNext | (iterable.dart:340 )
  | at _IOSSimulatorDevicePortForwarder.dispose | (simulators.dart:812 )
  | at <asynchronous gap> | (async )
  | at IOSSimulator.dispose | (simulators.dart:545 )
  | at HotRunner.cleanupAtFinish | (run_hot.dart:1109 )
  | at ResidentRunner.waitForAppToFinish | (resident_runner.dart:991 )
  | at <asynchronous gap> | (async )
  | at HotRunner.attach | (run_hot.dart:309 )
  | at <asynchronous gap> | (async )
  | at AttachCommand._attachToDevice | (attach.dart:317 )
  | at <asynchronous gap> | (async )
  | at AttachCommand.runCommand.<anonymous closure> | (attach.dart:176 )
  | at AppContext.run.<anonymous closure> | (context.dart:150 )
  | at _rootRun | (zone.dart:1126 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _runZoned | (zone.dart:1518 )
  | at runZoned | (zone.dart:1465 )
  | at AppContext.run | (context.dart:149 )
  | at AttachCommand.runCommand | (attach.dart:175 )
  | at <asynchronous gap> | (async )
  | at FlutterCommand.verifyThenRunCommand | (flutter_command.dart:637 )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:75 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:556 )
  | at _rootRun | (zone.dart:1126 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _CustomZone.runGuarded | (zone.dart:925 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:965 )
  | at _microtaskLoop | (schedule_microtask.dart:43 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:52 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:118 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:175 )
```

/cc @christopherfujino

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Fixed concurrent modification error from removing items from a list inside of a for loop iterating through the list.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/48896

## Tests

I added the following tests:

Added an initially failing test that calls `.dispose()` on an `_IOSSimulatorDevicePortForwarder` and confirmed that the test now succeeds.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 1]
```diff
@@ -809,8 +809,6 @@ class _IOSSimulatorDevicePortForwarder extends DevicePortForwarder {
 
   @override
   Future<void> dispose() async {
-    for (final ForwardedPort port in _ports) {
-      await unforward(port);
-    }
+    _ports.clear();
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: I'd add a comment here that this only works because `unforward` is trivial. If `unforward` had to do some work, then `dispose` would have to call `unforward` on each port.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/simulators.dart]: iterated through a copy instead, PTAL.

File: packages/flutter_tools/test/general.shard/ios/simulators_test.dart [hunk 2]
```diff
@@ -44,6 +44,25 @@ void main() {
...
+      final IOSSimulator simulator = IOSSimulator('123');
+      final DevicePortForwarder portFowarder = simulator.portForwarder;
+      portFowarder.forward(123);
+      portFowarder.forward(124);
+      expect(portFowarder.forwardedPorts.length, 2);
+      try {
+        portFowarder.dispose();
+      } catch (e) {
+        // This should not throw an exception
+        expect(true, false);
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/ios/simulators_test.dart]: use `fail('error message')` instead.

**Review by zanderso — APPROVED** [review]
lgtm w/ small fix.

File: packages/flutter_tools/test/general.shard/ios/simulators_test.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/ios/simulators_test.dart]: done
