### PR TITLE
Fix SegmentedButton border doesn't reflect states

### LINKED ISSUE #159884: `SegmentedButton` does not set its MaterialState for side
### Steps to reproduce

Launch the app and interact with `SegmentedButton` (press, hover etc.). `SegmentedButton` does not trigger `MaterialState` for side

### Expected results

Border color should change

### Actual results

Border color does not change

### Code sample

<details open><summary>Code sample</summary>

```dart
ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        visualDensity: VisualDensity.standard,
        segmentedButtonTheme: SegmentedButtonThemeData(
          style: ButtonStyle(
            // SegmentedButton does not trigger side
            side: WidgetStateProperty.resolveWith((states) {
              debugPrint('Button states: $states');
              if (states.contains(WidgetState.disabled)) {
                return BorderSide(color: Colors.grey);
              }
              if (states.contains(WidgetState.hovered) || states.contains(WidgetState.focused)) {
                return BorderSide(color: Colors.green);
              }
              if (states.contains(WidgetState.selected)) {
                return BorderSide(color: Colors.purple);
              }
              if (states.contains(WidgetState.pressed)) {
                return BorderSide(color: Colors.blue);
              }
              return BorderSide(color: Colors.red);
            }),
          ),
        ),
      )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 15.0 24A335 darwin-arm64, locale en-PL)
    • Flutter version 3.22.2 on channel stable at /Users/bartosz.gasztych/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/bartosz.gasztych/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `SegmentedButton` border side not depending on the current state.

It's based on one @TahaTesser 's great PR: see https://github.com/flutter/flutter/pull/161942. 🙏 
I updated some logic related to disabled border which led to Taha’s PR failing internal Google tests.
I also added a test to verify the disabled border.

<details><summary>Code sample for screenshots</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const SegmentedButtonApp());
}

enum Calendar { day, week, month, year }

class SegmentedButtonApp extends StatefulWidget {
  const SegmentedButtonApp({super.key});

  @override
  State<SegmentedButtonApp> createState() => _SegmentedButtonAppState();
}

class _SegmentedButtonAppState extends State<SegmentedButtonApp> {
  Calendar? calendarView;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        segmentedButtonTheme: SegmentedButtonThemeData(
          style: ButtonStyle(
            side: WidgetStateProperty.fromMap(<WidgetStatesConstraint, BorderSide?>{
              WidgetState.disabled: const BorderSide(color: Colors.grey, width: 2),
              WidgetState.selected & WidgetState.hovered: const BorderSide(
                color: Colors.blue,
                width: 2,
              ),
              WidgetState.selected & WidgetState.focused: const BorderSide(
                color: Colors.pinkAccent,
                width: 2,
              ),
              WidgetState.hovered: const BorderSide(color: Colors.green, width: 2),
              WidgetState.focused: const BorderSide(color: Colors.purple, width: 2),
              WidgetState.any: const BorderSide(color: Colors.amber, width: 2),
            }),
          ),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: SegmentedButton<Calendar>(
            segments: const <ButtonSegment<Calendar>>[
              ButtonSegment<Calendar>(
                value: Calendar.day,
                label: Text('Day'),
                icon: Icon(Icons.calendar_view_day),
                enabled: false,
              ),
              ButtonSegment<Calendar>(
                value: Calendar.week,
                label: Text('Week'),
                icon: Icon(Icons.calendar_view_week),
              ),
              ButtonSegment<Calendar>(
                value: Calendar.month,
                label: Text('Month'),
                icon: Icon(Icons.calendar_view_month),
              ),
              ButtonSegment<Calendar>(
                value: Calendar.year,
                label: Text('Year'),
                icon: Icon(Icons.calendar_today),
              ),
            ],
            selected: <Calendar>{?calendarView},
            emptySelectionAllowed: true,
            onSelectionChanged: (Set<Calendar> newSelection) {
              setState(() {
                calendarView = newSelection.isEmpty ? null : newSelection.first;
              });
            },
          ),
        ),
        floatingActionButton: FloatingActionButton(onPressed: () {}, child: const Icon(Icons.add)),
      ),
    );
  }
}

``` 

</details> 

# Before

https://github.com/user-attachments/assets/1581f431-f87a-4af3-8ef6-f1f0d170e54a

# After

https://github.com/user-attachments/assets/156a8a64-3d9f-4323-9a1d-60624f5ac5d4

## Related Issue

Fixes [SegmentedButton does not set its MaterialState for side ](https://github.com/flutter/flutter/issues/159884)

## Tests

Adds 2 tests.

### CODE REVIEW

**Comment by bleroux** [comment]
@QuncCccccc @victorsanni As you reviewed the initial PR (https://github.com/flutter/flutter/pull/172754), can you please review this one?

File: packages/flutter/test/material/segmented_button_test.dart [hunk 1]
```diff
@@ -1225,6 +1225,175 @@ void main() {
...
+        }),
+        selected: <int>{1},
+      ),
+    );
+    await tester.pumpAndSettle();
+
+    expect(find.byType(SegmentedButton<int>), paints..rrect(color: selectedColor));
+  });
+
+  testWidgets('SegmentedButton border sides respect disabled state', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/material/segmented_button_test.dart:1358]: This test passes on `master`, is this intended?

Comment (bleroux) [reply packages/flutter/test/material/segmented_button_test.dart:1358]: Yes, this test was added to catch future regression such as the one https://github.com/flutter/flutter/pull/172754 encountered. In the case of https://github.com/flutter/flutter/pull/172754, the regression was caught thanks to Google tests failures.
In summary, it is a missing test that should have been there since the creation of SegmentedButton.

**Review by victorsanni — APPROVED** [review]

**Comment by bleroux** [comment]
@victorsanni Thanks for the review 🙏 
Do you have a way to trigger the Google tests? (Usually it runs automatically after the approval, looks like it does not in this case). As the previous PR was failing Google tests, I think it would be better to see if this one passes those tests before adding autosubmit label.

File: packages/flutter/test/material/segmented_button_test.dart [hunk 2]
```diff
@@ -1225,6 +1225,175 @@ void main() {
...
+                side:
+                    WidgetStateProperty<BorderSide?>.fromMap(<WidgetStatesConstraint, BorderSide?>{
+                      WidgetState.disabled: BorderSide(color: disabledColor),
+                      WidgetState.any: BorderSide(color: enabledColor),
+                    }),
+              ),
+              // First segment is enabled, second is disabled.
+              segments: const <ButtonSegment<int>>[
+                ButtonSegment<int>(value: 0, label: Text('0')),
+                ButtonSegment<int>(value: 1, label: Text('1'), enabled: false),
```
Comment (QuncCccccc) [inline packages/flutter/test/material/segmented_button_test.dart:1377]: Nice test!

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thank you for continuing to finish this PR!
