### PR TITLE
`OverlayPortal.overlayChild` contributes semantics to `OverlayPortal` instead of `Overlay`

### LINKED ISSUE #134456: `OverlayPortal` doesn't interleave overlay in the widget semantics
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This is toward making non-modal floating widgets accessible. Use-cases:
1. A widget opens a tooltip with focusable content within it. I'd like screen reader navigation to end up within the content.
2. A math widget opens a custom floating on-screen keyboard. I'd like the screen reader's virtual cursor to navigate directly from the widget onto this on-screen keyboard.

For both of these, the `SemanticsNode` tree needs to interleave the overlay right after the widget on which it's anchored.

`OverlayPortal` seems perfect for this and _does_ automatically set the focus traversal order correctly, but it seems to not order the semantics tree to match. Here's a [repro on DartPad](https://dartpad.dev/?id=6d2c070bd7321ce52c697d6085a32365) (see Console for semantics output).

**Expected semantics order:** "button1", "floating-pause", "button2"

**Observed semantics order:** "floating-pause", "button1", "button2"

### Expected results

See above.

### Actual results

See above.

### Code sample

<details><summary>Code sample</summary>

https://dartpad.dev/?id=6d2c070bd7321ce52c697d6085a32365

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() async {
  runApp(
    MaterialApp(
      theme: ThemeData(useMaterial3: true),
      title: 'Test',
      home: const Scaffold(
        body: MyWidget(),
      ),
    ),
  );

  SemanticsBinding.instance.ensureSemantics();
  WidgetsBinding.instance.addPostFrameCallback((_) {
    debugDumpSemanticsTree();
  });
}

class MyWidget extends StatefulWidget {
  const MyWidget();

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final OverlayPortalController _controller = OverlayPortalController();

  @override
  Widget build(BuildContext context) {
    _controller.show();
    return FocusTraversalGroup(
      // Necessary to ensure that floating-pause is between button1 and button2
      // in the focus traversal order. Does not help semantics order one bit.
      policy: WidgetOrderTraversalPolicy(),
      child: Row(
        children: [
          OverlayPortal(
            controller: _controller,
            overlayChildBuilder: (context) => Positioned(
                left: 100,
                top: 20,
                child: button(Icons.pause, "floating-pause")),
            child: button(Icons.play_arrow, "button1"),
          ),
          button(Icons.stop, "button2"),
        ],
      ),
    );
  }
}

Widget button(IconData icon, String label, [VoidCallback? onPressed]) {
  return IconButton(
    icon: Semantics(
      label: label,
      child: Icon(icon),
    ),
    onPressed: onPressed ?? () {},
  );
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

N/A. See DartPad.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/134456

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like google testing is unhappy.

**Comment by LongCatIsLooong** [comment]
Looks like an infra thing I'll squash the commits.

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 1]
```diff
@@ -1197,7 +1197,6 @@ class _RenderTheater extends RenderBox with ContainerRenderObjectMixin<RenderBox
     while (child != null) {
       visitor(child);
       final _TheaterParentData childParentData = child.parentData! as _TheaterParentData;
-      childParentData.visitChildrenOfOverlayEntry(visitor);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/overlay.dart:1200]: It took me awhile to understand this only traverse child added from overlayportal. Can you add some doc to `visitChildrenOfOverlayEntry` or maybe rename it to something like `visitOverlayPortalChildren`?

File: packages/flutter/lib/src/rendering/object.dart [hunk 2]
```diff
@@ -5072,24 +5059,45 @@ class _SemanticsGeometry {
...
+        // The easier and more common case: semanticsParent is directly
+        // responsible for painting (and potentially clipping) the semanticsChild
+        // RenderObject.
+        _computeClipRect(semanticsParent, semanticsChild, _semanticsClipRect, _paintClipRect);
       } else {
-        _semanticsClipRect = _intersectRects(_semanticsClipRect, parent.describeApproximatePaintClip(child));
+        // Otherwise we have to find the closest ancestor RenderObject that
+        // has up-to-date semantics geometry and compute the clip rects from there.
+        //
+        // Currently it can only happen when the subtree contains an OverlayPortal.
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/object.dart:5077]: I thought it would still come to this case if there are rendering object that creates _ContainerSemanticsFragment inbetween `semanticsChild` and `semanticsParent` ?

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -5072,24 +5059,45 @@ class _SemanticsGeometry {
...
+        final List<RenderObject> clipPath = <RenderObject>[semanticsChild];
+
+        RenderObject? ancestor = semanticsChild.parent;
+        while (ancestor != null && ancestor._semantics == null) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/object.dart:5081]: what happen if this loop past `semanticsParent`?

File: packages/flutter/lib/src/rendering/object.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/object.dart:5077]: I ran existing tests with a print statement and it seems that isn't happening in tests. In `_getSemanticsForParent`, every fragment in the sibling merge/merge up groups calls `addAncestor(this)`.

File: packages/flutter/lib/src/rendering/object.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/object.dart:5081]: At least in the case of `OverlayPortal`, the final `ancestor` will be an ancestor of `semanticsParent`. Unfortunately we don't cache the clipping results from `semanticsParent` and `semanticsChild`'s common ancestor so we can't just the previously computed clipping rects.

File: packages/flutter/lib/src/rendering/object.dart [hunk 4]
```diff
@@ -5119,36 +5118,90 @@ class _SemanticsGeometry {
...
+  // Computes the paint transform from `semanticsChild` to `semanticsParent` and
+  // applies the paint transform to `transform` in place.
   //
-  // It will mutate both transform and clipRectTransform.
+  // The `semanticsParent` and `semanticsChild` [RenderObject]s must be in the
+  // same render tree (so they have a common ancestor).
   static void _applyIntermediatePaintTransforms(
-    RenderObject ancestor,
-    RenderObject child,
+    RenderObject semanticsParent,
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/object.dart:5127]: I think even if a render object generated a `ContainerFragment` it is still going to be in this list.

File: packages/flutter/lib/src/rendering/object.dart [hunk 5]
```diff
@@ -5117,36 +5116,90 @@ class _SemanticsGeometry {
...
+  // stored in it will be overwritten unpredictably by subsequent reuses.
+  static final Matrix4 _temporaryTransformHolder = Matrix4.zero();
+
+  // Computes the semantics and painting clip rects for the given child and
+  // assigns the rects to _semanticsClipRect and _paintClipRect respectively.
+  //
+  // The caller must guarantee that child.parent == parent. The resulting rects
+  // are in `child`'s coordinate system.
+  void _computeClipRect(
+    RenderObject parent, RenderObject child,
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/object.dart:5175]: nits: format

File: packages/flutter/lib/src/rendering/object.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/object.dart:5079]: yes I understood the logic now, makes sense

File: packages/flutter/lib/src/rendering/object.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/object.dart:5125]: what about parentInSemanticsFragmentOrder and childInSemanticsFragmentOrder

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 6]
```diff
@@ -919,12 +919,26 @@ class _TheaterParentData extends StackParentData {
...
+  /// right order.
+
   // _overlayStateMounted is set to null in _OverlayEntryWidgetState's dispose
   // method. This property is only accessed during layout, paint and hit-test so
   // the `value!` should be safe.
   Iterator<RenderBox>? get paintOrderIterator => overlayEntry?._overlayEntryStateNotifier?.value!._paintOrderIterable.iterator;
   Iterator<RenderBox>? get hitTestOrderIterator => overlayEntry?._overlayEntryStateNotifier?.value!._hitTestOrderIterable.iterator;
-  void visitChildrenOfOverlayEntry(RenderObjectVisitor visitor) => overlayEntry?._overlayEntryStateNotifier?.value!._paintOrderIterable.forEach(visitor);
+
+  // A convenience method for accessing `paintOrderIterator` using a
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/overlay.dart:939]:
```suggestion
  // A convenience method for accessing `paintOrderIterator` with a
```

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this!

File: packages/flutter/lib/src/rendering/object.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/object.dart]: renamed to parent/childFragmentOwner

**Comment by LongCatIsLooong** [comment]
Added a `Semantics(container: true)` to the tooltip on the overlay to prevent the semantics of tooltip's text from merging with that of `Tooltip.child`.

**Comment by LongCatIsLooong** [comment]
<table>
<tr><td> BEFORE </td><td> AFTER </td></tr>
<td>
<pre>
| SemanticsNode#0
 │ Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
 │
 └─SemanticsNode#1
   │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0) scaled by 3.0x
   │ textDirection: ltr
   │
   ├─SemanticsNode#2
   │ │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
   │ │ sortKey: OrdinalSortKey#8299f(order: 0.0)
   │ │
   │ └─SemanticsNode#3
   │   │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
   │   │ flags: scopesRoute
   │   │
   │   └─SemanticsNode#4
   │     │ merge boundary ⛔️
   │     │ Rect.fromLTRB(356.0, 276.0, 444.0, 324.0)
   │     │ flags: hasExpandedState, isExpanded
   │     │
   │     └─SemanticsNode#5
   │         merged up ⬆️
   │         Rect.fromLTRB(0.0, 0.0, 88.0, 48.0)
   │         actions: tap
   │         flags: isFocused, hasEnabledState, isEnabled, isFocusable
   │         label: "ABC"
   │         textDirection: ltr
   │
   └─SemanticsNode#6
     │ Rect.fromLTRB(356.0, 316.0, 476.0, 380.0)
     │ thickness: 3.0
     │
     └─SemanticsNode#7
       │ Rect.fromLTRB(0.0, 8.0, 120.0, 56.0)
       │ flags: hasImplicitScrolling
       │ scrollExtentMin: 0.0
       │ scrollPosition: 0.0
       │ scrollExtentMax: 0.0
       │ elevation: 3.0
       │
       └─SemanticsNode#8
         │ merge boundary ⛔️
         │ Rect.fromLTRB(0.0, 0.0, 120.0, 48.0)
         │
         └─SemanticsNode#9
             merged up ⬆️
             Rect.fromLTRB(0.0, 0.0, 120.0, 48.0)
             actions: tap
             flags: hasEnabledState, isEnabled, isFocusable
             label: "Item 0"
             textDirection: ltr
</pre>
</td>
<td>
<pre>
SemanticsNode#0
 │ Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
 │
 └─SemanticsNode#1
   │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0) scaled by 3.0x
   │ textDirection: ltr
   │
   └─SemanticsNode#2
     │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
     │ sortKey: OrdinalSortKey#bfee0(order: 0.0)
     │
     └─SemanticsNode#3
       │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
       │ flags: scopesRoute
       │
       ├─SemanticsNode#4
       │ │ merge boundary ⛔️
       │ │ Rect.fromLTRB(356.0, 276.0, 444.0, 324.0)
       │ │ flags: hasExpandedState, isExpanded
       │ │
       │ └─SemanticsNode#5
       │     merged up ⬆️
       │     Rect.fromLTRB(0.0, 0.0, 88.0, 48.0)
       │     actions: tap
       │     flags: isFocused, hasEnabledState, isEnabled, isFocusable
       │     label: "ABC"
       │     textDirection: ltr
       │
       └─SemanticsNode#6
         │ Rect.fromLTRB(356.0, 316.0, 476.0, 380.0)
         │ thickness: 3.0
         │
         └─SemanticsNode#7
           │ Rect.fromLTRB(0.0, 8.0, 120.0, 56.0)
           │ flags: hasImplicitScrolling
           │ scrollExtentMin: 0.0
           │ scrollPosition: 0.0
           │ scrollExtentMax: 0.0
           │ elevation: 3.0
           │
           └─SemanticsNode#8
             │ merge boundary ⛔️
             │ Rect.fromLTRB(0.0, 0.0, 120.0, 48.0)
             │
             └─SemanticsNode#9
                 merged up ⬆️
                 Rect.fromLTRB(0.0, 0.0, 120.0, 48.0)
                 actions: tap
                 flags: hasEnabledState, isEnabled, isFocusable
                 label: "Item 0"
                 textDirection: ltr

</pre>
</td>
</table>

**Comment by gspencergoog** [comment]
Honestly, I don't see any difference in those two trees.

**Comment by LongCatIsLooong** [comment]
> Honestly, I don't see any difference in those two trees.

Oops sorry copied the wrong tree. Basically node #6 is grafted to #3 and becomes a sibling of #4. I'll fix the comment in a bit.

**Comment by gspencergoog** [comment]
Okay, if I understand that correctly, it sounds OK to me.
