### PR TITLE
Text editing shift + tap + drag interaction

### LINKED ISSUE #91979: TextField: issues with selection using shift+mouse click on the web
## Steps to Reproduce

1. Execute the code sample 
2. Enter text to the text field (e.g. copy paste code sample to it)
3. Move cursor to the start of the TextField
4. Hold shift and click on to the end of the word

**Expected results:** 

The word should be selected

**Actual results:** 

The cursor just moved to the new place without selecting the text

<details>
<summary>Code sample</summary>

```dart
TextField(
      maxLines: 8,
      decoration: InputDecoration.collapsed(hintText: "Enter your text here"),
    );
```

Gist - https://dartpad.dev/?id=f47ec8a65b32abbd7646831d65311724&null_safety=true

</details>

<details>
  <summary>Logs</summary>

```
```

```
 info • Use key in widget constructors • lib/main.dart:9:7 • use_key_in_widget_constructors
 info • Use key in widget constructors • lib/main.dart:26:7 • use_key_in_widget_constructors
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.5.2 at /Users/aydar/Documents/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/aydar/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • ANDROID_HOME = /Users/aydar/Library/Android/sdk
    • Java binary at: /Users/aydar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/aydar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/aydar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!

```

</details>

https://user-images.githubusercontent.com/6143095/137683710-7c9d5d78-472a-46a1-b65d-527f5a6b1d41.mov

### PR DESCRIPTION
**Pull request by justinmc**
After https://github.com/flutter/flutter/pull/93835 added support for shift + tap to expand text selection in an input, this PR will add support for shift + tap and then dragging to move the extent.

Fixes https://github.com/flutter/flutter/issues/91979

Mac has some non-trivial behavior that made this PR more complex than I thought it would be.  When the selection is inverted, it restores the original selection from the time of tapdown.  See this video, which shows this PR duplicating Mac's behavior.

https://user-images.githubusercontent.com/389558/146077181-0150ada3-16f6-47a0-964b-d0a9ae668a47.mov

### CODE REVIEW

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 1]
```diff
@@ -4963,4 +4963,352 @@ void main() {
...
+    expect(controller.selection.extentOffset, 9);
+
+    // Continuing to select in this direction selects just like it did
+    // originally.
+    await gesture.moveTo(textOffsetToPosition(tester, 24));
+    await tester.pumpAndSettle();
+    expect(controller.selection.baseOffset, 8);
+    expect(controller.selection.extentOffset, 24);
+
+    await tester.sendKeyUpEvent(LogicalKeyboardKey.shift);
```
Comment (dkwingsmt) [inline packages/flutter/test/cupertino/text_field_test.dart:5049]: Maybe extend the test with more mouse movements after releasing the shift key, which, according to my test, continues the extended selection.

**Comment by dkwingsmt** [comment]
Another behavior we might be interested in testing is shift-tapping a text field when it is not focused. On macOS this is equivalent to having the base offset as 0 (i.e. selecting the range from 0 to the mouse position).

**Comment by dkwingsmt** [comment]
_Another_ behavior is shift-tapping multiple times, instead of dragging.
- On Windows it is simple: the base offset is never changed.
- On macOS it has a complicated behavior: if the tapped position is closer to the start of the range, then the start is changed; otherwise the end is changed. Tapping at the exact mid-point changes the start.

**Review by dkwingsmt — APPROVED** [review]
I see no problem in this PR, but I suggest adding one extra step as commented above.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart:5140]: Added.  Thanks for catching that, I didn't think to try it.

**Comment by justinmc** [comment]
@dkwingsmt Thanks for thinking about all of these other behaviors.  There are so many edge cases when it comes to stuff like this.

  * Shift + tap unfocused: The current behavior of Flutter seems to be the same as Windows.  I've opened a separate issue for getting this right on Mac and will open a new PR soon: https://github.com/flutter/flutter/issues/97534
  * Shift tapping multiple times: I think we've got this working correctly, but tell me if you can break it.  The complicated Mac logic is [here](https://github.com/flutter/flutter/blob/29b44f79d98ce1daa4ec28791233ffad5ab8d192/packages/flutter/lib/src/widgets/text_selection.dart#L958).

I'll go ahead and merge this PR when/if it goes green.

**Comment by justinmc** [comment]
Here's the PR for shift-tapping on an unfocused field: https://github.com/flutter/flutter/pull/97543

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -1026,9 +1026,23 @@ class TextSelectionGestureDetectorBuilder {
...
+      }.contains);
+  }
+
   // True iff a tap + shift has been detected but the tap has not yet come up.
   bool _isShiftTapping = false;
 
+  // For a shift + tap + drag gesture, the TextSelection at the point of the
+  // tap. Mac uses this value to reset to the original selection when an
+  // inversion of the base and offset happens.
+  TextSelection? _shiftTapDragSelection;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:1044]: is it true that `_shiftTapDragSelection != null` if and only if `_isShiftTapping` is true? If so then you need only one variable to track the state?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -1288,10 +1297,27 @@ class TextSelectionGestureDetectorBuilder {
...
+          _expandSelection(details.globalPosition, SelectionChangedCause.drag);
+          break;
+        case TargetPlatform.android:
+        case TargetPlatform.fuchsia:
+        case TargetPlatform.linux:
+        case TargetPlatform.windows:
+          _extendSelection(details.globalPosition, SelectionChangedCause.drag);
+          break;
+      }
+      _shiftTapDragSelection = renderEditable.selection;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:1314]: nit: What if `renderEditable.selection` is invalid at this point?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1044]: It's not true unfortunately.  _isShiftTapping will be true when just shift tapping (not dragging) while _shiftTapDragSelection will be null.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1314]: I think I intended to prevent that with the if above, I'll update it so it can't be null here.
