### PR TITLE
simulatedAccessibilityTraversal account for force merging

### LINKED ISSUE #135144: `simulatedAccessibilityTraversal` doesn't account for explicit/force-merging (via `MergeSemantics`)
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use `MergeSemantics` to wrap one or more multiple widgets that emit `Semantics(container: true)` to consolidate the semantics tree.
2. Test the semantics of the consolidated widget using `tester.semantics.simulatedAccessibilityTraversal()`.

See code further below.

### Expected results

Per @goderbauer, `simulatedAccessibilityTraversal()` should account for the force-merging to enable unit testing of `MergeSemantics`-based code. Effectively, it should be testing a `SemanticsData` tree to capture the platform accessibility tree that will be generated from the semantics tree.

### Actual results

`simulatedAccessibilityTraversal()` enumerates the semantics tree as-is, including all `SemanticsNode`s that are merged upward. It does not use the `SemanticsData` due to force-merging.

Maybe this is inherent to the API? Should it be deprecated in favor of a new API that emits `SemanticsData` (and also exposes the number of children so that we can assert when something should be a leaf node)? Is it possible to test the structure of the platform accessibility that will be generated?

### Code sample

https://dartpad.dev/?id=06937c78a65c3c3daf75eb81648b1783

<details><summary>Code sample</summary>

```dart
await tester.pumpWidget(
  MaterialApp(
    home: MergeSemantics(
      child: Semantics(
        container: true,
        label: 'Container',
        child: Semantics(
          button: true,
          container: true,
          label: 'Foo',
          child: const SizedBox(width: 10, height: 10),
        ),
      ),
    ),
  ),
);

// Fails since `simulatedAccessibilityTraversal` doesn't account
// for force-merging.
expect(
  tester.semantics.simulatedAccessibilityTraversal(),
  [containsSemantics(label: 'Container\nFoo', isButton: true)],
);
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/135144

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_test/lib/src/controller.dart [hunk 1]
```diff
@@ -228,9 +228,12 @@ class SemanticsController {
...
 
-    final List<SemanticsNode> children = node.debugListChildrenInOrder(DebugSemanticsDumpOrder.traversalOrder);
-    for (final SemanticsNode child in children) {
-      _traverse(child, traversal);
+    if (!node.mergeAllDescendantsIntoThisNode) {
+      final List<SemanticsNode> children = node.debugListChildrenInOrder(
+          DebugSemanticsDumpOrder.traversalOrder);
+      for (final SemanticsNode child in children) {
+        _traverse(child, traversal);
+      }
```
Comment (pdblasi-google) [inline packages/flutter_test/lib/src/controller.dart:236]: If a node has `mergeAllDescendantsIntoThisNode`, will all of the children have `isMergedIntoParent = true`?

I ask because in #132598, I have this `_traverse` method being a more generic "traverse the entire tree" method instead of a "traverse like an accessibility service" method. If we can have a `isMergedIntoParent` check in `_isImportantForAccessibility` instead, this PR and #132598 will conflict less.

File: packages/flutter_test/lib/src/controller.dart [hunk 2]
```diff
@@ -242,23 +245,25 @@ class SemanticsController {
   /// * [flutter/engine/AccessibilityBridge.java#SemanticsNode.isFocusable()](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L2641)
   /// * [flutter/engine/SemanticsObject.mm#SemanticsObject.isAccessibilityElement](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L449)
   bool _isImportantForAccessibility(SemanticsNode node) {
+    assert(!node.isMergedIntoParent);
```
Comment (pdblasi-google) [inline packages/flutter_test/lib/src/controller.dart:248]: Are there any cases where `isMergedIntoParent` will be true and the parent's `mergeAllDescendantsIntoThisNode` be false? Something where you want to merge descendants, but you can exclude something by wrapping it in a container of some sort?

If so, this should just be a check that returns false instead of an assert that throws. I'd argue (in combination with the comment above) that it should just be a check either way.

File: packages/flutter_test/lib/src/controller.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter_test/lib/src/controller.dart:236]: > If a node has mergeAllDescendantsIntoThisNode, will all of the children have isMergedIntoParent = true?

Yes, otherwise it is a bug in framework.

> I have this _traverse method being a more generic "traverse the entire tree"

I see, so it become a filter method pass into traversal. Do we know what should happen when the action is perform on semantics node that are merged upward? In a real world example, this should never happen because the embedding only sees the merged node.

File: packages/flutter_test/lib/src/controller.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter_test/lib/src/controller.dart:248]: Yes we can do that, but are there any use case where we want to traverse the merging node at all?

File: packages/flutter_test/lib/src/controller.dart (hunk 1 above)
Comment (pdblasi-google) [reply packages/flutter_test/lib/src/controller.dart:236]: The intent of the change to the `_traversal` method was to have it be a generic traversal of the tree that could be used for multiple different needs in `SemanticsController`. Backwards compatible with this "get all important nodes for accessibilty" traversal, but also usable for searching for nodes with specific actions, flags, etc. On a re-read though, that change may not be needed anymore since we introduced the semantics finders.

I'm not sure what would happen if you attempted an action on a child of a merged node, tbh. Along those lines, if we want _all_ traversals of the semantics tree to exclude merged children, we'll need to update the traversal logic in `tree_traversal.dart#_DepthFirstSemanticsTreeIterator` as well.

File: packages/flutter_test/lib/src/controller.dart (hunk 2 above)
Comment (pdblasi-google) [reply packages/flutter_test/lib/src/controller.dart:248]: The point being that if we have a parent with `mergeAllDescendantsIntoThisNode` as false, the short circuit above that prevents traversing its child (which _can_ have `isMergedIntoParent` as true) would cause an assertion rather than just excluding the child from the results.

File: packages/flutter_test/lib/src/controller.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter_test/lib/src/controller.dart:236]: hmmm you are right, I think we need to figure out whether the find semantics API or basically any semantics testing API is testing what send to engine, or the tree stored in semantics owner.

It looks most of the semantics test API is testing the tree stored in semantics owner. if we want to change it, not only all the traverse method need to be guard behind `mergeAllDescendantsIntoThisNode`, they also need to check `SemanticsData` instead of the `SemanticsNode` directly.

**Comment by chunhtai** [comment]
I guard it in the `_isImportantForAccessibility` instead.

File: packages/flutter_test/lib/src/controller.dart [hunk 3]
```diff
@@ -242,23 +242,27 @@ class SemanticsController {
   /// * [flutter/engine/AccessibilityBridge.java#SemanticsNode.isFocusable()](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L2641)
   /// * [flutter/engine/SemanticsObject.mm#SemanticsObject.isAccessibilityElement](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L449)
   bool _isImportantForAccessibility(SemanticsNode node) {
+    if (node.isMergedIntoParent) {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:245]: Maybe just leave a quick comment here for context that if the node is merged, all its information are present on an ancestor node.

**Review by goderbauer — APPROVED** [review]
LGTM, if @pdblasi-google's concerns are resolved now.

File: packages/flutter_test/lib/src/controller.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter_test/lib/src/controller.dart]: updated to shortcircuit instead of assert

File: packages/flutter_test/lib/src/controller.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter_test/lib/src/controller.dart:245]: done
