### PR TITLE
fix the issue that can't set app bar traversal order for flexible space

### LINKED ISSUE #98570: AppBar accessibility traversal order
Hello, 

When we use a SliverAppBar, we notice that the semantic order is defined in this way: Leading -> Title -> Actions -> Bottom -> FlexingSpace.
https://github.com/flutter/flutter/blob/ee0bbf4789fac99576c0bd249466a20a305af606/packages/flutter/lib/src/material/app_bar.dart#L1027
I think it could be useful to be able to modify this order, for example the Bottom at the end

Thanks for your help :)

### PR DESCRIPTION
**Pull request by hannah-hyj**
fix https://github.com/flutter/flutter/issues/98570 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -744,6 +745,18 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
+  /// Whether to customize the sort key behavior of the app bar.
+  ///
+  /// If this is set to false, the app bar will use the default sort key behavior,
+  /// which means the flexible space will appear after the main content in the semantics tree.
+  ///
+  /// Set this to true if you want to customize the semantics sort keys of the app bar.
+  ///
+  /// Defaults to false.
+  /// {@endtemplate}
+  final bool customizeSemanticsSortKeys;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/app_bar.dart:758]: This needs a better name. maybe called `useDefaultSemanticsOrder` and doc should also comment what the default semantics order and how they can change it (by assigning the sortkey in the input widget).

and also should add a `See also` that points to semanticsSortKey doc

File: packages/flutter/lib/src/material/app_bar.dart [hunk 2]
```diff
@@ -745,17 +745,21 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
 
-  /// {@template flutter.material.appbar.customizeSemanticsSortKeys}
-  /// Whether to customize the sort key behavior of the app bar.
+  /// {@template flutter.material.appbar.useDefaultSemanticsOrder}
+  /// Whether to use the default semantic ordering for the app bar's children.
   ///
-  /// If this is set to false, the app bar will use the default sort key behavior,
-  /// which means the flexible space will appear after the main content in the semantics tree.
+  /// If this is set to true, the app bar will use the default semantic ordering,
+  /// which places the flexible space after the main content in the semantics tree.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/app_bar.dart:752]: some where in the doc should mention this is for accessibility traversal order.

**Review by chunhtai — APPROVED** [review]
LGTM
