### PR TITLE
Make tool coverage collection resilient to sentinel coverage data

### LINKED ISSUE #35120: flutter test --coverage throws Exception since flutter 1.5.4
Running Flutter test with coverage leads to an  _NoSuchMethodError: The getter 'iterator' was called on null_ Error in _coverage_collector.dart_

## Steps to Reproduce

I can not tell what is required to Reproduce this issue.
After a Flutter Version from flutter 1.2.1 to flutter 1.5.4-hotfix.2 Update it appeared.

After some tryouts I found out that the issue does not occur when all usages of Image.asset() are removed.
But creating a new Project and adding an Image.asset() call did not cause the issue.

By adding log output to the coverage_collector.dart I found out that the response of an RPC is not as expected.

The response for
```
final Map<String, dynamic> scriptList = await isolateRef.invokeRpcRaw('getScripts', params: <String, dynamic>{'isolateId': isolateRef.id});
```
is
```
{type: Sentinel, kind: Collected, valueAsString: <collected>}
```
But the expected type would be ScriptList here. (That can also be seen in the log output short before the Exception occurs)
Do the attempt to use script list like that
```
for (Map<String, dynamic> script in scriptList['scripts']) {
```

leads to a
```
NoSuchMethodError: The getter 'iterator' was called on null
```

## Logs

The call:
```
flutter test --coverage --verbose test/unit/screen/home/home_test.dart
```
generated the output.
```[  +28 ms] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/usr/local/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +12 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD zeigt auf keinen Branch
[  +30 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[ +684 ms] running test package with arguments: [--no-color, -r, compact, --concurrency=6, --, /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart]

00:00 +0: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart                                                                                                       [ +220 ms] test 0: starting test /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart
[  +24 ms] test 0: starting shell process
[   +3 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/sp/Documents/development/diego-app
[   +3 ms] Compiler will use the following file as its incremental dill file: /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_compiler.KfeOcB/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_listener.L4z9qL/listener.dart
[  +14 ms] /usr/local/flutter/bin/cache/dart-sdk/bin/dart /usr/local/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /usr/local/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_compiler.KfeOcB/output.dill --packages /Users/sp/Documents/development/diego-app/.packages --initialize-from-dill /Users/sp/Documents/development/diego-app/build/testfile.dill
[  +15 ms] <- compile /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_listener.L4z9qL/listener.dart
[ +112 ms] -> result d5f09957-fa38-41ca-904f-f149303b5914

00:01 +0: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart                                                                                                       
00:02 +0: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart                                                                                                       
00:03 +0: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart                                                                                                       [+2931 ms] -> d5f09957-fa38-41ca-904f-f149303b5914
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/async.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/async_cache.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/async_memoizer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/byte_collector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/cancelable_operation.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/event_sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/future.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/stream.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/stream_consumer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/stream_sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/delegate/stream_subscription.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/future_group.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/lazy_stream.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/null_stream_sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/restartable_timer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/capture_sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/capture_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/error.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/future.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/release_sink.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/release_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/result.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/result/value.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/single_subscription_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_completer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_group.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_queue.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_sink_completer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_sink_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_sink_transformer/handler_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_sink_transformer/stream_transformer_wrapper.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_sink_transformer/typed.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_splitter.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_subscription_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/stream_zip.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/subscription_stream.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/typed/stream_subscription.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/typed_stream_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/async-2.1.0/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/boolean_selector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/all.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/ast.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/evaluator.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/impl.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/intersection_selector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/none.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/parser.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/token.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/union_selector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/validator.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/src/visitor.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.2/lib/ascii.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.2/lib/charcode.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.2/lib/html_entity.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/collection.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/algorithms.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/canonicalized_map.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_iterable.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_list.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_map.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/comparators.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/empty_unmodifiable_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/wrappers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality_map.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/functions.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/iterable_zip.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/priority_queue.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/queue_list.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/union_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/unmodifiable_wrappers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/union_set_controller.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+2/lib/connectivity.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/http.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_client.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_request.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_response.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/boundary_characters.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/byte_stream.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/client.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/io_client.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_file.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_file_io.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/multipart_request.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/request.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/response.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/streamed_request.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/streamed_response.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/http_parser.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/authentication_challenge.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/case_insensitive_map.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/chunked_coding.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/chunked_coding/decoder.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/chunked_coding/encoder.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/http_date.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/media_type.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/scan.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/date_symbol_data_custom.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/date_symbols.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/number_format.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/compact_number_format.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/date_format.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/date_format_field.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/date_format_helpers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/number_symbols.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/number_symbols_data.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/date_format_internal.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl_helpers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/plural_rules.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/core_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/custom_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/description.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/equals_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/error_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/feature_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/having_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/type_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/interfaces.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/iterable_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/map_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/numeric_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/operator_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/order_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/pretty_print.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/string_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.5/lib/src/util.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/meta-1.1.6/lib/meta.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/mockito-4.0.0/lib/mockito.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/mockito-4.0.0/lib/src/call_pair.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/mockito-4.0.0/lib/src/invocation_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/mockito-4.0.0/lib/src/mock.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/path.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/characters.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/context.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/internal_style.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/parsed_path.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/path_exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/path_map.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/path_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/style.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/style/posix.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/style/url.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/style/windows.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/path_provider-1.1.0/lib/path_provider.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/pedantic-1.5.0/lib/pedantic.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/testing/async.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/testing/src/async/fake_async.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/time.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/src/time/clock.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/src/time/duration_unit_constants.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2/lib/src/time/util.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.2/lib/shared_preferences.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/source_span.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/colors.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/file.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/span_with_context.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/highlighter.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/location.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/location_mixin.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/span.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/span_exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/span_mixin.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/chain.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/frame.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/lazy_chain.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/lazy_trace.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/stack_zone_specification.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/trace.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/unparsed_frame.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/src/vm_trace.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/stack_trace.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/close_guarantee_channel.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/delegating_stream_channel.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/disconnector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/stream_channel_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/guarantee_channel.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/json_document_transformer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/multi_channel.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/stream_channel_completer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/src/stream_channel_controller.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.0.0/lib/stream_channel.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/eager_span_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/line_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/relative_span_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/span_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/string_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/string_scanner.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/ascii_glyph_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/glyph_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/top_level.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/unicode_glyph_set.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/term_glyph.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/closed_exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/declarer.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/group.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/group_entry.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/invoker.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/live_test.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/live_test_controller.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/message.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/metadata.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/operating_system.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/outstanding_callback_counter.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/platform_selector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/runtime.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/stack_trace_formatter.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/state.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/suite.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/suite_platform.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/backend/test.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/async_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/expect.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/expect_async.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/format_stack_trace.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/future_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/never_called.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/on_platform.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/prints_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/retry.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/skip.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/spawn_hybrid.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/stream_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/stream_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/tags.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/test_on.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/throws_matcher.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/throws_matchers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/timeout.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/frontend/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/remote_listener.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/suite_channel_manager.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/util/placeholder.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/util/remote_exception.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/util/stack_trace_mapper.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/util/test.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/src/utils.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.4/lib/test_api.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/typed_buffers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/typed_data.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/hash.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/vector_math_64.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/aabb2.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/aabb3.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/colors.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/frustum.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/intersection_result.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix2.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix3.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix4.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/obb3.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/plane.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/quad.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/quaternion.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/ray.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/sphere.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/third_party/noise.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/triangle.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector2.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector3.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector4.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/constants.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/error_helpers.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/opengl.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/utilities.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/config/endpoint_config.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/exceptions/NoVinException.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/car_data.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/connectors/ConnectorLogEntry.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/asam_file.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/dtc_entry.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/ecu_node_address_list.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/possible_vehicle_project.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/vehicle_project_table.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/vehicle_root_table.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/vin.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/vpt_data.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vrt_vpt/vrt_vpt.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/confirm_state.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/settings/locale_settings.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/settings/settings.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/settings/vci_manager_settings.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/util/event_emitter.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/util/fetcher.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/communication_parameters.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/ecu_can_address.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/pdu.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/pdu_multi_request.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/pdu_protocol.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/pdu_request.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/pdu/pdu_response.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/requests/pdu_response_interpreter.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/helper/vci_manager_settings_mock.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/animation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/foundation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/gestures.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/painting.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/physics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/rendering.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/scheduler.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/semantics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/services.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/animation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/animation_controller.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/listener_helpers.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/animations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/curves.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/tween.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/animation/tween_sequence.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/action_sheet.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/object.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/box.dart
[   +1 ms] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/activity_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/ticker_provider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/bottom_tab_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/colors.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/date_picker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/dialog.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/icons.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/diagnostics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/picker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/refresh.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/scrollbar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/segmented_control.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/slider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/switch.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/tab_scaffold.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/text_field.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/automatic_keep_alive.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/text_selection.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/text_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/thumb_painter.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/annotations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/assertions.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/basic_types.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/bitfield.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/change_notifier.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/collections.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/consolidate_response.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/constants.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/isolates.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/key.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/licenses.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/node.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/observer_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/platform.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/print.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/profile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/serialization.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/synchronous_future.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/foundation/unicode.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/arena.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/constants.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/converter.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/drag.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/drag_details.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/eager.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/events.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/force_press.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/hit_test.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/long_press.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/lsq_solver.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/monodrag.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/mouse_tracking.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/multidrag.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/multitap.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/pointer_router.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/pointer_signal_resolver.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/recognizer.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/scale.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/tap.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/team.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/animated_icons.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/animated_icons_data.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/add_event.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/arrow_menu.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/close_menu.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/ellipsis_search.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/event_add.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/home_menu.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/list_view.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/menu_arrow.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/menu_close.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/menu_home.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/pause_play.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/play_pause.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/search_ellipsis.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/animated_icons/data/view_list.g.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/arc.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/colors.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/constants.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/floating_action_button_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/flutter_logo.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/grid_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/icons.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/input_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/shadows.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/tab_controller.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/tab_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/text_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/toggleable.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/typography.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/alignment.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/basic_types.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/beveled_rectangle_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/border_radius.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/borders.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/box_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/box_decoration.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/box_fit.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/box_shadow.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/circle_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/clip.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/colors.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/continuous_rectangle_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/decoration.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/decoration_image.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/edge_insets.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/flutter_logo.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/fractional_offset.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/geometry.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/gradient.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/image_cache.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/image_decoder.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/image_provider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/image_resolution.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/image_stream.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/matrix_utils.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/notched_shapes.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/paint_utilities.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/rounded_rectangle_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/shader_warm_up.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/shape_decoration.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/stadium_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/strut_style.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/text_painter.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/text_span.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/painting/text_style.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/clamped_simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/friction_simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/gravity_simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/spring_simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/tolerance.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/physics/utils.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/animated_size.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/scheduler/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/semantics/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/custom_layout.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/custom_paint.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/debug_overflow_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/editable.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/error.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/flex.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/flow.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/image.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/layer.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/list_body.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/list_wheel_viewport.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/paragraph.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/platform_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/proxy_box.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/rotated_box.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/shifted_box.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_fill.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_grid.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_padding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/sliver_persistent_header.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/stack.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/table.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/table_border.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/texture.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/tweens.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/viewport.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/viewport_offset.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/rendering/wrap.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/scheduler/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/scheduler/priority.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/scheduler/ticker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/semantics/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/semantics/semantics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/semantics/semantics_event.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/semantics/semantics_service.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/asset_bundle.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/clipboard.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/font_loader.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/haptic_feedback.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/keyboard_key.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/keyboard_maps.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/message_codec.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/message_codecs.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/platform_channel.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/platform_messages.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/platform_views.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/raw_keyboard.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/raw_keyboard_android.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/raw_keyboard_fuchsia.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/raw_keyboard_linux.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/raw_keyboard_macos.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/system_channels.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/system_chrome.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/system_navigator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/system_sound.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/text_editing.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/text_formatter.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/services/text_input.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/animated_cross_fade.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/animated_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/animated_size.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/animated_switcher.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/annotated_region.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/app.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/async.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/banner.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/basic.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/container.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/dismissible.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/drag_target.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/editable_text.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/fade_in_image.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/focus_manager.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/focus_scope.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/form.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/framework.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/gesture_detector.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/grid_paper.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/heroes.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/icon.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/icon_data.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/icon_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/icon_theme_data.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/image.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/image_icon.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/implicit_animations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/inherited_model.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/inherited_notifier.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/layout_builder.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/media_query.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/modal_barrier.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/navigation_toolbar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/navigator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/nested_scroll_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/notification_listener.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/orientation_builder.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/overlay.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/overscroll_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_notification.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/page_storage.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/page_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/pages.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/performance_overlay.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/placeholder.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/platform_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/preferred_size.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/primary_scroll_controller.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/routes.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/safe_area.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_activity.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_configuration.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_context.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_physics.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_position.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_simulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scroll_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scrollable.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/scrollbar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/semantics_debugger.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/single_child_scroll_view.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/size_changed_layout_notifier.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/sliver.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/sliver_persistent_header.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/sliver_prototype_extent_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/spacer.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/status_transitions.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/table.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/text.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/text_selection.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/texture.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/title.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/transitions.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/unique_widget.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/value_listenable_builder.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/viewport.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/visibility.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/widgets/will_pop_scope.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/widgets.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/src/l10n/generated_date_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/src/utils/date_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/src/widgets_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/all_elements.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/goldens.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/nonconst.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/stack_manipulation.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_async_utils.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_compat.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_exception_reporter.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_pointer.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_vsync.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/window.dart
[        ] -> +file:///var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_listener.L4z9qL/listener.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/flutter_test.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/accessibility.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/binding.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/controller.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/finders.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/matchers.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/test_text_input.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_test/lib/src/widget_tester.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/connection_model.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/screen/home/home.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/helper/app_wrapper.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/helper/connection_model_mock.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/helper/connectivity_model_mock.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/test/helper/vci_manager_mock.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/material.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/cupertino.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vci_device.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vci_manager.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/vehicle.dart
[        ] -> +file:///Users/sp/.pub-cache/hosted/pub.dartlang.org/scoped_model-1.0.1/lib/scoped_model.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/widget/main_layout.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/localization/imprint_localization_delegate.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/car_model.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/connectivity_model.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/ecu_model.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/scoped_models/localization_model.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/flutter_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/about.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/app.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/app_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/app_bar_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/back_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/bottom_app_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/bottom_navigation_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/bottom_sheet.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/button_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/button_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/card.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/card_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/checkbox.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/checkbox_list_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/chip.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/chip_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/circle_avatar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/color_scheme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/data_table.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/data_table_source.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/date_picker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/debug.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/dialog.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/dialog_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/divider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/drawer.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/drawer_header.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/dropdown.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/expand_icon.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/expansion_panel.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/expansion_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/feedback.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/flat_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/flexible_space_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/floating_action_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/floating_action_button_location.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/grid_tile_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/icon_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/ink_decoration.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/ink_highlight.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/ink_ripple.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/ink_splash.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/ink_well.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/input_decorator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/list_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/material.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/material_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/material_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/mergeable_material.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/outline_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/page.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/page_transitions_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/paginated_data_table.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/popup_menu.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/progress_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/radio.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/radio_list_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/raised_button.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/refresh_indicator.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/reorderable_list.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/scaffold.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/scrollbar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/search.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/slider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/slider_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/snack_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/stepper.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/switch.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/switch_list_tile.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/tabs.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/text_field.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/text_form_field.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/text_selection.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/theme.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/theme_data.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/time.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/time_picker.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/tooltip.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/material/user_accounts_drawer_header.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/app.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/route.dart
[        ] -> +file:///usr/local/flutter/packages/flutter/lib/src/cupertino/tab_view.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/connectors/vehicle_connector.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/vci_requests.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/ecus.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/screen/statusbar/connection_status_item.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/screen/statusbar/connectivity_status_item.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/widget/navigation_bar.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/localization/imprint_localization.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/ecu_data.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/provider/localization_provider.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart
[        ] -> +file:///usr/local/flutter/packages/flutter_localizations/lib/src/material_localizations.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/requests/ecu_pdu_requests.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/vcirequests/requests/functional_obd_requests.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/model/ecu/ecu_tree_walker.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/provider/ecu_data_provider.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/util/named_navigator.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/widget/navigation_bar_item.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/util/cached_fetcher.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/util/direct_fetcher.dart
[        ] -> +file:///Users/sp/Documents/development/diego-app/lib/config/app_config.dart
[        ] -> d5f09957-fa38-41ca-904f-f149303b5914 /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_compiler.KfeOcB/output.dill 0
[  +64 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_listener.L4z9qL/listener.dart took 3212ms
[   +1 ms] /usr/local/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --enable-checked-mode --verify-entry-points --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/sp/Documents/development/diego-app/.packages /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_listener.L4z9qL/listener.dart.dill
[        ] Using this directory for fonts configuration: /var/folders/8j/t1p7_98x60s866sxc8_s1rwr0000gn/T/flutter_test_fonts.tbPbfT
[   +6 ms] test 0: awaiting initial result for pid 78536
[ +260 ms] Shell: Observatory listening on http://127.0.0.1:58125/-5rrf3WH-tw=/
[        ] test 0: using observatory uri http://127.0.0.1:58125/-5rrf3WH-tw=/ from pid 78536
[        ] Connecting to service protocol: http://127.0.0.1:58125/-5rrf3WH-tw=/
[ +171 ms] Successfully connected to service protocol: http://127.0.0.1:58125/-5rrf3WH-tw=/
[ +261 ms] test 0: process with pid 78536 connected to test harness
[        ] test 0: awaiting test result for pid 78536

00:04 +0: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart                                                                                                       
00:04 +0: initialization initializes without error                                                                                                                                                     
00:04 +1: initialization initializes without error                                                                                                                                                     [ +768 ms] test 0: process with pid 78536 no longer needed by test harness
[        ] test 0: collecting coverage
[        ] pid 78536: collecting coverage data from http://127.0.0.1:58125/-5rrf3WH-tw=/...
[   +8 ms] Sending to VM service: getVM({})
[   +3 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: x64, hostCPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64", _profilerMode: Dart, _nativeZoneMemoryUsage: ...
[   +6 ms] Sending to VM service: getIsolate({isolateId: isolates/1014886971})
[   +1 ms] Sending to VM service: getIsolate({isolateId: isolates/862545787})
[   +4 ms] Sending to VM service: getVM({})
[  +31 ms] Result: {type: Isolate, fixedId: true, id: isolates/862545787, name: main, number: 862545787, _originNumber: 862545787, startTime: 1561547471602, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 5, avgCollectionPeriodMillis: 279....
[  +13 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: x64, hostCPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64", _profilerMode: Dart, _nativeZoneMemoryUsage: ...
[  +18 ms] Result: {type: Isolate, fixedId: true, id: isolates/1014886971, name: _spawn, number: 1014886971, _originNumber: 862545787, startTime: 1561547472936, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: ...
[   +9 ms] Sending to VM service: getScripts({isolateId: isolates/862545787})
[  +18 ms] Result: {type: ScriptList, scripts: [{type: @Script, fixedId: true, id: libraries/@0150898/scripts/dart%3Acore%2Ferrors.dart/0, uri: dart:core/errors.dart, _kind: kernel}, {type: @Script, fixedId: true, id: libraries/@0150898/scripts/dart%3Acore%2Furi.dar...
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@5320332/scripts/dart%3Anativewrappers/0, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@5320332/scripts/dart%3Anativewrappers/0})
[   +1 ms] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@57122940/scripts/package%3Aasync%2Fsrc%2Fstream_sink_transformer%2Fstream_transformer_wrapper.dart/16b937b7b9d, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@57122940/scripts/package%3Aasync%2Fsrc%2Fstream_sink_transformer%2Fstream_transformer_wrapper.dart/16b937b7b9d})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@79326211/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_iterable.dart/16b937b7b9f, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@79326211/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_iterable.dart/16b937b7b9f})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@80256243/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_list.dart/16b937b7b9f, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@80256243/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_list.dart/16b937b7b9f})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@81346360/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_map.dart/16b937b7b9f, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@81346360/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_map.dart/16b937b7b9f})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@92278439/scripts/package%3Acollection%2Fsrc%2Funmodifiable_wrappers.dart/16b937b7ba1, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@92278439/scripts/package%3Acollection%2Fsrc%2Funmodifiable_wrappers.dart/16b937b7ba1})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@93184915/scripts/package%3Acollection%2Fsrc%2Fwrappers.dart/16b937b7ba0, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@93184915/scripts/package%3Acollection%2Fsrc%2Fwrappers.dart/16b937b7ba0})
[   +1 ms] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@245432746/scripts/package%3Atest_api%2Fsrc%2Futil%2Fstack_trace_mapper.dart/16b937b7bb2, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@245432746/scripts/package%3Atest_api%2Fsrc%2Futil%2Fstack_trace_mapper.dart/16b937b7bb2})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@269117159/scripts/package%3Aapp%2Fconfig%2Fapp_config.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@269117159/scripts/package%3Aapp%2Fconfig%2Fapp_config.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@270279597/scripts/package%3Aapp%2Fconfig%2Fendpoint_config.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@270279597/scripts/package%3Aapp%2Fconfig%2Fendpoint_config.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@271306893/scripts/package%3Aapp%2Fexceptions%2FNoVinException.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@271306893/scripts/package%3Aapp%2Fexceptions%2FNoVinException.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@272207269/scripts/package%3Aapp%2Flocalization%2Fimprint_localization.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@272207269/scripts/package%3Aapp%2Flocalization%2Fimprint_localization.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@273279061/scripts/package%3Aapp%2Flocalization%2Fimprint_localization_delegate.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@273279061/scripts/package%3Aapp%2Flocalization%2Fimprint_localization_delegate.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@276370066/scripts/package%3Aapp%2Fmodel%2Fcar_data.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@276370066/scripts/package%3Aapp%2Fmodel%2Fcar_data.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@277244641/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fpossible_vehicle_project.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@277244641/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fpossible_vehicle_project.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@278303410/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvrt_vpt.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@278303410/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvrt_vpt.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@279392152/scripts/package%3Aapp%2Futil%2Fevent_emitter.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@279392152/scripts/package%3Aapp%2Futil%2Fevent_emitter.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@280456728/scripts/package%3Aapp%2Fmodel%2Fconnectors%2FConnectorLogEntry.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@280456728/scripts/package%3Aapp%2Fmodel%2Fconnectors%2FConnectorLogEntry.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@281003109/scripts/package%3Aapp%2Fmodel%2Fconnectors%2Fvehicle_connector.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@281003109/scripts/package%3Aapp%2Fmodel%2Fconnectors%2Fvehicle_connector.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@282051334/scripts/package%3Aapp%2Fmodel%2Fvci_device.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@282051334/scripts/package%3Aapp%2Fmodel%2Fvci_device.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@283176589/scripts/package%3Aapp%2Fsettings%2Fvci_manager_settings.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@283176589/scripts/package%3Aapp%2Fsettings%2Fvci_manager_settings.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@284113806/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@284113806/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@285171355/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_multi_request.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@285171355/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_multi_request.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@286300058/scripts/package%3Aapp%2Fmodel%2Fecu%2Fasam_file.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@286300058/scripts/package%3Aapp%2Fmodel%2Fecu%2Fasam_file.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@287437958/scripts/package%3Aapp%2Fmodel%2Fecu%2Fdtc_entry.dart/16b937b7bcb, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@287437958/scripts/package%3Aapp%2Fmodel%2Fecu%2Fdtc_entry.dart/16b937b7bcb})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@288023500/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_data.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@288023500/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_data.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@289250585/scripts/package%3Aapp%2Fprovider%2Fecu_data_provider.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@289250585/scripts/package%3Aapp%2Fprovider%2Fecu_data_provider.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@290458886/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_node_address_list.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@290458886/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_node_address_list.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@291486901/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_tree_walker.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@291486901/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_tree_walker.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@292353440/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecus.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@292353440/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecus.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@293447458/scripts/package%3Aapp%2Fmodel%2Fvehicle.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@293447458/scripts/package%3Aapp%2Fmodel%2Fvehicle.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@294289881/scripts/package%3Aapp%2Fvcirequests%2Fvci_requests.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@294289881/scripts/package%3Aapp%2Fvcirequests%2Fvci_requests.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@295341038/scripts/package%3Aapp%2Fmodel%2Fvci_manager.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@295341038/scripts/package%3Aapp%2Fmodel%2Fvci_manager.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@296345520/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_project_table.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@296345520/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_project_table.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@297439106/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvpt_data.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@297439106/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvpt_data.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@298147442/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_root_table.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@298147442/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_root_table.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@299150884/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvin.dart/16b937b7bcc, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@299150884/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvin.dart/16b937b7bcc})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@300403009/scripts/package%3Aapp%2Futil%2Fcached_fetcher.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@300403009/scripts/package%3Aapp%2Futil%2Fcached_fetcher.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@301084784/scripts/package%3Aapp%2Futil%2Fdirect_fetcher.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@301084784/scripts/package%3Aapp%2Futil%2Fdirect_fetcher.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@302202644/scripts/package%3Aapp%2Futil%2Ffetcher.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@302202644/scripts/package%3Aapp%2Futil%2Ffetcher.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@303208119/scripts/package%3Aapp%2Fprovider%2Flocalization_provider.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@303208119/scripts/package%3Aapp%2Fprovider%2Flocalization_provider.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@304380758/scripts/package%3Aapp%2Fscoped_models%2Fcar_model.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@304380758/scripts/package%3Aapp%2Fscoped_models%2Fcar_model.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@305287030/scripts/package%3Aapp%2Fscoped_models%2Fconfirm_state.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@305287030/scripts/package%3Aapp%2Fscoped_models%2Fconfirm_state.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@306090328/scripts/package%3Aapp%2Fscoped_models%2Fconnection_model.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@306090328/scripts/package%3Aapp%2Fscoped_models%2Fconnection_model.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@307080183/scripts/package%3Aapp%2Fscoped_models%2Fconnectivity_model.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@307080183/scripts/package%3Aapp%2Fscoped_models%2Fconnectivity_model.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@308035069/scripts/package%3Aapp%2Fscoped_models%2Fecu_model.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@308035069/scripts/package%3Aapp%2Fscoped_models%2Fecu_model.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@309342557/scripts/package%3Aapp%2Fscoped_models%2Flocalization_model.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@309342557/scripts/package%3Aapp%2Fscoped_models%2Flocalization_model.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@310400745/scripts/package%3Aapp%2Fsettings%2Flocale_settings.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@310400745/scripts/package%3Aapp%2Fsettings%2Flocale_settings.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@311076907/scripts/package%3Aapp%2Fscreen%2Fhome%2Fhome.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@311076907/scripts/package%3Aapp%2Fscreen%2Fhome%2Fhome.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@312209416/scripts/package%3Aapp%2Fwidget%2Fmain_layout.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@312209416/scripts/package%3Aapp%2Fwidget%2Fmain_layout.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@313512202/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnection_status_item.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@313512202/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnection_status_item.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@314188411/scripts/package%3Aapp%2Futil%2Fnamed_navigator.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@314188411/scripts/package%3Aapp%2Futil%2Fnamed_navigator.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@315007184/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnectivity_status_item.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@315007184/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnectivity_status_item.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@316424667/scripts/package%3Aapp%2Fsettings%2Fsettings.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@316424667/scripts/package%3Aapp%2Fsettings%2Fsettings.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@317520766/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fcommunication_parameters.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@317520766/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fcommunication_parameters.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@318381013/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fecu_can_address.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@318381013/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fecu_can_address.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@319271042/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_protocol.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@319271042/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_protocol.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@320031812/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_request.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@320031812/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_request.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@321394108/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_response.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@321394108/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_response.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@322081247/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fecu_pdu_requests.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@322081247/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fecu_pdu_requests.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@323190649/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fpdu_response_interpreter.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@323190649/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fpdu_response_interpreter.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@324002755/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Ffunctional_obd_requests.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@324002755/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Ffunctional_obd_requests.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@325196656/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@325196656/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@326362725/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar_item.dart/16b937b7bcd, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@326362725/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar_item.dart/16b937b7bcd})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@327419891/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fapp_wrapper.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@327419891/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fapp_wrapper.dart/16b937b7bce})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@330181450/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnection_model_mock.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@330181450/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnection_model_mock.dart/16b937b7bce})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@331354344/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnectivity_model_mock.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@331354344/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnectivity_model_mock.dart/16b937b7bce})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@332356996/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_mock.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@332356996/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_mock.dart/16b937b7bce})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@333176270/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_settings_mock.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@333176270/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_settings_mock.dart/16b937b7bce})
[   +1 ms] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@334521489/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Funit%2Fscreen%2Fhome%2Fhome_test.dart/16b937b7bce, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@334521489/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Funit%2Fscreen%2Fhome%2Fhome_test.dart/16b937b7bce})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@346034880/scripts/package%3Aflutter%2Fsrc%2Fcupertino%2Fapp.dart/16b937b7bd5, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@346034880/scripts/package%3Aflutter%2Fsrc%2Fcupertino%2Fapp.dart/16b937b7bd5})
[   +1 ms] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@418125171/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp.dart/16b937b7c04, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@418125171/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp.dart/16b937b7c04})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@419187611/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar.dart/16b937b7c05, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@419187611/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar.dart/16b937b7c05})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@420092148/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar_theme.dart/16b937b7c05, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@420092148/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar_theme.dart/16b937b7c05})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@423408488/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar.dart/16b937b7c05, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@423408488/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar.dart/16b937b7c05})
[        ] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@424337866/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar_theme.dart/16b937b7c05, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@424337866/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar_theme.dart/16b937b7c05})
[   +1 ms] Sending to VM service: getSourceReport({forceCompile: true, scriptId: libraries/@658236006/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fapp.dart/16b937b7c60, isolateId: isolates/862545787, reports: [Coverage]})
[        ] Sending to VM service: getObject({isolateId: isolates/862545787, objectId: libraries/@658236006/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fapp.dart/16b937b7c60})
[   +9 ms] Result: {type: SourceReport, ranges: [], scripts: []}
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@5320332/scripts/dart%3Anativewrappers/0, uri: dart:nativewrappers, _kind: kernel, _loadTime: 0, library: {type: @Library, f...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1128, endPos: 1603, compiled: true, coverage: {hits: [], misses: [1128, 1221, 1233, 1249, 1281, 1288, 1295, 1309, 1316]}}, {scriptIndex: 0, startPos: 1093, endPos: 1123, compiled: true, cove...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@57122940/scripts/package%3Aasync%2Fsrc%2Fstream_sink_transformer%2Fstream_transformer_wrapper.dart/16b937b7b9d, uri: packag...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 839, endPos: 882, compiled: true, coverage: {hits: [], misses: [839]}}, {scriptIndex: 0, startPos: 887, endPos: 989, compiled: true, coverage: {hits: [], misses: [887, 925, 946, 957, 980]}},...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@79326211/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_iterable.dart/16b937b7b9f, uri: package:collecti...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1072, endPos: 1101, compiled: true, coverage: {hits: [], misses: [1072]}}, {scriptIndex: 0, startPos: 863, endPos: 958, compiled: true, coverage: {hits: [], misses: [863, 900]}}, {scriptInde...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@80256243/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_list.dart/16b937b7b9f, uri: package:collection/s...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1184, endPos: 1211, compiled: true, coverage: {hits: [], misses: [1184]}}, {scriptIndex: 0, startPos: 1216, endPos: 1460, compiled: true, coverage: {hits: [], misses: [1216, 1264, 1271, 1345...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@81346360/scripts/package%3Acollection%2Fsrc%2Fcombined_wrappers%2Fcombined_map.dart/16b937b7b9f, uri: package:collection/sr...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 4054, endPos: 4148, compiled: true, coverage: {hits: [], misses: [4054, 4091]}}, {scriptIndex: 0, startPos: 4242, endPos: 4271, compiled: true, coverage: {hits: [], misses: [4242, 4263]}}, {...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@92278439/scripts/package%3Acollection%2Fsrc%2Funmodifiable_wrappers.dart/16b937b7ba1, uri: package:collection/src/unmodifia...
[   +8 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 7554, endPos: 7600, compiled: true, coverage: {hits: [7554, 7589], misses: []}}, {scriptIndex: 0, startPos: 8173, endPos: 8265, compiled: true, coverage: {hits: [], misses: [8173, 8256]}}, {...
[   +5 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@93184915/scripts/package%3Acollection%2Fsrc%2Fwrappers.dart/16b937b7ba0, uri: package:collection/src/wrappers.dart, _kind: ...
[        ] Result: {type: SourceReport, ranges: [], scripts: []}
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@245432746/scripts/package%3Atest_api%2Fsrc%2Futil%2Fstack_trace_mapper.dart/16b937b7bb2, uri: package:test_api/src/util/sta...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 247, endPos: 273, compiled: true, coverage: {hits: [], misses: [247]}}, {scriptIndex: 0, startPos: 330, endPos: 343, compiled: true, coverage: {hits: [], misses: [330]}}, {scriptIndex: 0, st...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@269117159/scripts/package%3Aapp%2Fconfig%2Fapp_config.dart/16b937b7bcb, uri: package:app/config/app_config.dart, _kind: ker...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 141, endPos: 229, compiled: true, coverage: {hits: [], misses: [141]}}, {scriptIndex: 0, startPos: 234, endPos: 344, compiled: true, coverage: {hits: [], misses: [234, 281, 306, 315, 321, 33...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@270279597/scripts/package%3Aapp%2Fconfig%2Fendpoint_config.dart/16b937b7bcb, uri: package:app/config/endpoint_config.dart, ...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 46, endPos: 83, compiled: true, coverage: {hits: [], misses: [46]}}], scripts: [{type: @Script, fixedId: true, id: libraries/@271306893/scripts/package%3Aapp%2Fexceptions%2FNoVinException.da...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@271306893/scripts/package%3Aapp%2Fexceptions%2FNoVinException.dart/16b937b7bcb, uri: package:app/exceptions/NoVinException....
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 202, endPos: 264, compiled: true, coverage: {hits: [202, 242, 253], misses: []}}, {scriptIndex: 0, startPos: 269, endPos: 405, compiled: true, coverage: {hits: [], misses: [269, 348]}}, {scr...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@272207269/scripts/package%3Aapp%2Flocalization%2Fimprint_localization.dart/16b937b7bcb, uri: package:app/localization/impri...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 257, endPos: 671, compiled: true, coverage: {hits: [257], misses: []}}, {scriptIndex: 0, startPos: 676, endPos: 711, compiled: true, coverage: {hits: [676], misses: []}}, {scriptIndex: 0, st...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@273279061/scripts/package%3Aapp%2Flocalization%2Fimprint_localization_delegate.dart/16b937b7bcb, uri: package:app/localizat...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1148, endPos: 1211, compiled: true, coverage: {hits: [], misses: [1148, 1197]}}, {scriptIndex: 0, startPos: 375, endPos: 511, compiled: true, coverage: {hits: [], misses: [375, 428, 471, 485...
[   +1 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@276370066/scripts/package%3Aapp%2Fmodel%2Fcar_data.dart/16b937b7bcb, uri: package:app/model/car_data.dart, _kind: kernel, _...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 89, endPos: 152, compiled: true, coverage: {hits: [], misses: [89]}}], scripts: [{type: @Script, fixedId: true, id: libraries/@277244641/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fpossible_ve...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@277244641/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fpossible_vehicle_project.dart/16b937b7bcc, uri: package:app/model/vrt_v...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 574, endPos: 622, compiled: true, coverage: {hits: [], misses: [574]}}, {scriptIndex: 0, startPos: 1129, endPos: 1280, compiled: true, coverage: {hits: [], misses: [1129, 1200, 1212, 1219, 1...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@278303410/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvrt_vpt.dart/16b937b7bcd, uri: package:app/model/vrt_vpt/vrt_vpt.dart, ...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 259, endPos: 293, compiled: true, coverage: {hits: [], misses: [259, 288]}}, {scriptIndex: 0, startPos: 298, endPos: 370, compiled: true, coverage: {hits: [], misses: [298, 341, 351]}}, {scr...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@279392152/scripts/package%3Aapp%2Futil%2Fevent_emitter.dart/16b937b7bcd, uri: package:app/util/event_emitter.dart, _kind: k...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 148, endPos: 261, compiled: true, coverage: {hits: [], misses: [148]}}], scripts: [{type: @Script, fixedId: true, id: libraries/@280456728/scripts/package%3Aapp%2Fmodel%2Fconnectors%2FConnec...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@280456728/scripts/package%3Aapp%2Fmodel%2Fconnectors%2FConnectorLogEntry.dart/16b937b7bcb, uri: package:app/model/connector...

00:05 +1: initialization initializes without error                                                                                                                                                     [   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 445, endPos: 499, compiled: true, coverage: {hits: [], misses: [445]}}, {scriptIndex: 0, startPos: 1523, endPos: 2128, compiled: true, coverage: {hits: [], misses: [1523, 1599, 1615, 1624, 1...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@281003109/scripts/package%3Aapp%2Fmodel%2Fconnectors%2Fvehicle_connector.dart/16b937b7bcb, uri: package:app/model/connector...
[   +6 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 3161, endPos: 3881, compiled: true, coverage: {hits: [], misses: [3161, 3530, 3537, 3545, 3558, 3566, 3582, 3602, 3620, 3640, 3654, 3683, 3726, 3749, 3788, 3803, 3834, 3858]}}, {scriptIndex:...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@282051334/scripts/package%3Aapp%2Fmodel%2Fvci_device.dart/16b937b7bcc, uri: package:app/model/vci_device.dart, _kind: kerne...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 154, endPos: 491, compiled: true, coverage: {hits: [], misses: [154, 185, 205, 241, 469, 485]}}, {scriptIndex: 0, startPos: 673, endPos: 735, compiled: true, coverage: {hits: [], misses: [67...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@283176589/scripts/package%3Aapp%2Fsettings%2Fvci_manager_settings.dart/16b937b7bcd, uri: package:app/settings/vci_manager_s...
[        ] Result: {type: SourceReport, ranges: [], scripts: []}
[   +2 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@284113806/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/pdu.dart, _kin...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 446, endPos: 634, compiled: true, coverage: {hits: [], misses: [446, 597, 610]}}, {scriptIndex: 0, startPos: 639, endPos: 833, compiled: true, coverage: {hits: [], misses: [639, 717, 769, 81...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@285171355/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_multi_request.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 70, endPos: 183, compiled: true, coverage: {hits: [], misses: [70, 140, 172]}}, {scriptIndex: 0, startPos: 188, endPos: 229, compiled: true, coverage: {hits: [], misses: [188]}}], scripts: [...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@286300058/scripts/package%3Aapp%2Fmodel%2Fecu%2Fasam_file.dart/16b937b7bcb, uri: package:app/model/ecu/asam_file.dart, _kin...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 39, endPos: 39, compiled: true, coverage: {hits: [], misses: [39]}}, {scriptIndex: 0, startPos: 59, endPos: 59, compiled: true, coverage: {hits: [], misses: [59]}}, {scriptIndex: 0, startPos...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@287437958/scripts/package%3Aapp%2Fmodel%2Fecu%2Fdtc_entry.dart/16b937b7bcb, uri: package:app/model/ecu/dtc_entry.dart, _kin...
[  +11 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 277, endPos: 277, compiled: true, coverage: {hits: [], misses: [277]}}, {scriptIndex: 0, startPos: 296, endPos: 296, compiled: true, coverage: {hits: [], misses: [296]}}, {scriptIndex: 0, st...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@288023500/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_data.dart/16b937b7bcc, uri: package:app/model/ecu/ecu_data.dart, _kind:...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 360, endPos: 401, compiled: true, coverage: {hits: [], misses: [360, 396]}}, {scriptIndex: 0, startPos: 1054, endPos: 1246, compiled: true, coverage: {hits: [], misses: [1054, 1113, 1124, 11...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@289250585/scripts/package%3Aapp%2Fprovider%2Fecu_data_provider.dart/16b937b7bcd, uri: package:app/provider/ecu_data_provide...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 55, endPos: 85, compiled: true, coverage: {hits: [], misses: [55]}}, {scriptIndex: 0, startPos: 90, endPos: 433, compiled: true, coverage: {hits: [], misses: [90, 169, 218]}}, {scriptIndex: ...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@290458886/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_node_address_list.dart/16b937b7bcc, uri: package:app/model/ecu/ecu_node...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 494, endPos: 542, compiled: true, coverage: {hits: [], misses: [494]}}, {scriptIndex: 0, startPos: 560, endPos: 1812, compiled: true, coverage: {hits: [], misses: [560, 822, 828, 844, 968, 1...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@291486901/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecu_tree_walker.dart/16b937b7bcc, uri: package:app/model/ecu/ecu_tree_walke...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1115, endPos: 1359, compiled: true, coverage: {hits: [], misses: [1115, 1194, 1202, 1210, 1226, 1246, 1266, 1286, 1313, 1338]}}, {scriptIndex: 0, startPos: 454, endPos: 606, compiled: true, ...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@292353440/scripts/package%3Aapp%2Fmodel%2Fecu%2Fecus.dart/16b937b7bcc, uri: package:app/model/ecu/ecus.dart, _kind: kernel,...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 343, endPos: 429, compiled: true, coverage: {hits: [], misses: [343, 415]}}, {scriptIndex: 0, startPos: 956, endPos: 1006, compiled: true, coverage: {hits: [], misses: [956, 990]}}, {scriptI...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@293447458/scripts/package%3Aapp%2Fmodel%2Fvehicle.dart/16b937b7bcc, uri: package:app/model/vehicle.dart, _kind: kernel, _lo...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 506, endPos: 708, compiled: true, coverage: {hits: [], misses: [506]}}, {scriptIndex: 0, startPos: 713, endPos: 871, compiled: true, coverage: {hits: [], misses: [713, 788, 832]}}, {scriptIn...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@294289881/scripts/package%3Aapp%2Fvcirequests%2Fvci_requests.dart/16b937b7bcd, uri: package:app/vcirequests/vci_requests.da...
[   +5 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1478, endPos: 1707, compiled: true, coverage: {hits: [], misses: [1478, 1512, 1533, 1553, 1577, 1597, 1623, 1643, 1657, 1665, 1676, 1684]}}, {scriptIndex: 0, startPos: 1100, endPos: 1188, co...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@295341038/scripts/package%3Aapp%2Fmodel%2Fvci_manager.dart/16b937b7bcc, uri: package:app/model/vci_manager.dart, _kind: ker...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 175, endPos: 248, compiled: true, coverage: {hits: [], misses: [175]}}, {scriptIndex: 0, startPos: 253, endPos: 643, compiled: true, coverage: {hits: [], misses: [253, 347, 353, 406, 428, 52...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@296345520/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_project_table.dart/16b937b7bcc, uri: package:app/model/vrt_vpt/...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 73, endPos: 133, compiled: true, coverage: {hits: [], misses: [73]}}, {scriptIndex: 0, startPos: 138, endPos: 258, compiled: true, coverage: {hits: [], misses: [138, 207, 219, 240]}}], scrip...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@297439106/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvpt_data.dart/16b937b7bcc, uri: package:app/model/vrt_vpt/vpt_data.dart...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 198, endPos: 262, compiled: true, coverage: {hits: [], misses: [198]}}, {scriptIndex: 0, startPos: 267, endPos: 839, compiled: true, coverage: {hits: [], misses: [267, 366, 475, 480, 526, 54...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@298147442/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvehicle_root_table.dart/16b937b7bcc, uri: package:app/model/vrt_vpt/veh...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 35, endPos: 48, compiled: true, coverage: {hits: [], misses: [35]}}, {scriptIndex: 0, startPos: 53, endPos: 110, compiled: true, coverage: {hits: [], misses: [53, 87, 91]}}, {scriptIndex: 0,...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@299150884/scripts/package%3Aapp%2Fmodel%2Fvrt_vpt%2Fvin.dart/16b937b7bcc, uri: package:app/model/vrt_vpt/vin.dart, _kind: k...
[   +8 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 3717, endPos: 3766, compiled: true, coverage: {hits: [], misses: [3717]}}, {scriptIndex: 0, startPos: 3581, endPos: 3642, compiled: true, coverage: {hits: [], misses: [3581]}}, {scriptIndex:...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@300403009/scripts/package%3Aapp%2Futil%2Fcached_fetcher.dart/16b937b7bcd, uri: package:app/util/cached_fetcher.dart, _kind:...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 409, endPos: 520, compiled: true, coverage: {hits: [], misses: [409]}}, {scriptIndex: 0, startPos: 525, endPos: 651, compiled: true, coverage: {hits: [], misses: [525, 609, 615]}}, {scriptIn...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@301084784/scripts/package%3Aapp%2Futil%2Fdirect_fetcher.dart/16b937b7bcd, uri: package:app/util/direct_fetcher.dart, _kind:...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 151, endPos: 189, compiled: true, coverage: {hits: [], misses: [151]}}, {scriptIndex: 0, startPos: 206, endPos: 236, compiled: true, coverage: {hits: [], misses: [206]}}], scripts: [{type: @...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@302202644/scripts/package%3Aapp%2Futil%2Ffetcher.dart/16b937b7bcd, uri: package:app/util/fetcher.dart, _kind: kernel, _load...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 286, endPos: 335, compiled: true, coverage: {hits: [], misses: [286, 333]}}, {scriptIndex: 0, startPos: 1436, endPos: 1515, compiled: true, coverage: {hits: [], misses: [1436, 1488, 1493]}},...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@303208119/scripts/package%3Aapp%2Fprovider%2Flocalization_provider.dart/16b937b7bcd, uri: package:app/provider/localization...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 289, endPos: 784, compiled: true, coverage: {hits: [], misses: [289, 338, 361]}}, {scriptIndex: 0, startPos: 789, endPos: 884, compiled: true, coverage: {hits: [], misses: [789, 823, 857, 87...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@304380758/scripts/package%3Aapp%2Fscoped_models%2Fcar_model.dart/16b937b7bcd, uri: package:app/scoped_models/car_model.dart...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 5, endPos: 5, compiled: true, coverage: {hits: [], misses: [5]}}, {scriptIndex: 0, startPos: 22, endPos: 22, compiled: true, coverage: {hits: [], misses: [22]}}, {scriptIndex: 0, startPos: 3...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@305287030/scripts/package%3Aapp%2Fscoped_models%2Fconfirm_state.dart/16b937b7bcd, uri: package:app/scoped_models/confirm_st...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 687, endPos: 1652, compiled: true, coverage: {hits: [], misses: [687, 726, 773, 784, 809, 1315, 1326, 1349]}}, {scriptIndex: 0, startPos: 428, endPos: 479, compiled: true, coverage: {hits: [...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@306090328/scripts/package%3Aapp%2Fscoped_models%2Fconnection_model.dart/16b937b7bcd, uri: package:app/scoped_models/connect...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 267, endPos: 534, compiled: true, coverage: {hits: [], misses: [267, 310, 353, 366, 388]}}, {scriptIndex: 0, startPos: 539, endPos: 610, compiled: true, coverage: {hits: [], misses: [539, 56...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@307080183/scripts/package%3Aapp%2Fscoped_models%2Fconnectivity_model.dart/16b937b7bcd, uri: package:app/scoped_models/conne...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 335, endPos: 840, compiled: true, coverage: {hits: [], misses: [335, 384, 407]}}, {scriptIndex: 0, startPos: 845, endPos: 931, compiled: true, coverage: {hits: [], misses: [845, 873, 907, 92...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@308035069/scripts/package%3Aapp%2Fscoped_models%2Fecu_model.dart/16b937b7bcd, uri: package:app/scoped_models/ecu_model.dart...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 419, endPos: 508, compiled: true, coverage: {hits: [], misses: [419, 502]}}, {scriptIndex: 0, startPos: 1156, endPos: 1221, compiled: true, coverage: {hits: [], misses: [1156, 1194, 1203]}},...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@309342557/scripts/package%3Aapp%2Fscoped_models%2Flocalization_model.dart/16b937b7bcd, uri: package:app/scoped_models/local...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 88, endPos: 180, compiled: true, coverage: {hits: [], misses: [88, 115, 131]}}, {scriptIndex: 0, startPos: 326, endPos: 403, compiled: true, coverage: {hits: [], misses: [326, 370]}}, {scrip...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@310400745/scripts/package%3Aapp%2Fsettings%2Flocale_settings.dart/16b937b7bcd, uri: package:app/settings/locale_settings.da...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 126, endPos: 434, compiled: true, coverage: {hits: [126, 186, 241], misses: []}}], scripts: [{type: @Script, fixedId: true, id: libraries/@311076907/scripts/package%3Aapp%2Fscreen%2Fhome%2Fh...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@311076907/scripts/package%3Aapp%2Fscreen%2Fhome%2Fhome.dart/16b937b7bcd, uri: package:app/screen/home/home.dart, _kind: ker...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 408, endPos: 589, compiled: true, coverage: {hits: [408], misses: []}}, {scriptIndex: 0, startPos: 594, endPos: 1458, compiled: true, coverage: {hits: [594, 664, 699, 780, 790, 805, 850, 866...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@312209416/scripts/package%3Aapp%2Fwidget%2Fmain_layout.dart/16b937b7bcd, uri: package:app/widget/main_layout.dart, _kind: k...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 220, endPos: 252, compiled: true, coverage: {hits: [220], misses: []}}, {scriptIndex: 0, startPos: 257, endPos: 641, compiled: true, coverage: {hits: [257, 525, 608, 620], misses: []}}, {scr...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@313512202/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnection_status_item.dart/16b937b7bcd, uri: package:app/screen/sta...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 101, endPos: 175, compiled: true, coverage: {hits: [], misses: [101, 164]}}, {scriptIndex: 0, startPos: 180, endPos: 254, compiled: true, coverage: {hits: [], misses: [180, 240]}}, {scriptIn...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@314188411/scripts/package%3Aapp%2Futil%2Fnamed_navigator.dart/16b937b7bcd, uri: package:app/util/named_navigator.dart, _kin...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 234, endPos: 268, compiled: true, coverage: {hits: [234], misses: []}}, {scriptIndex: 0, startPos: 273, endPos: 608, compiled: true, coverage: {hits: [273, 377, 456], misses: [502, 545, 557,...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@315007184/scripts/package%3Aapp%2Fscreen%2Fstatusbar%2Fconnectivity_status_item.dart/16b937b7bcd, uri: package:app/screen/s...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 580, endPos: 748, compiled: true, coverage: {hits: [], misses: [580, 653, 677, 712, 730]}}, {scriptIndex: 0, startPos: 859, endPos: 932, compiled: true, coverage: {hits: [], misses: [859, 91...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@316424667/scripts/package%3Aapp%2Fsettings%2Fsettings.dart/16b937b7bcd, uri: package:app/settings/settings.dart, _kind: ker...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 124, endPos: 172, compiled: true, coverage: {hits: [], misses: [124]}}, {scriptIndex: 0, startPos: 189, endPos: 237, compiled: true, coverage: {hits: [], misses: [189]}}, {scriptIndex: 0, st...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@317520766/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fcommunication_parameters.dart/16b937b7bcd, uri: package:app/vcireques...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 44, endPos: 75, compiled: true, coverage: {hits: [], misses: [44]}}, {scriptIndex: 0, startPos: 80, endPos: 493, compiled: true, coverage: {hits: [], misses: [80, 145, 157, 173, 185, 222, 22...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@318381013/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fecu_can_address.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/ec...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 35, endPos: 65, compiled: true, coverage: {hits: [], misses: [35]}}, {scriptIndex: 0, startPos: 82, endPos: 112, compiled: true, coverage: {hits: [], misses: [82]}}, {scriptIndex: 0, startPo...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@319271042/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_protocol.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/pdu_p...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 380, endPos: 558, compiled: true, coverage: {hits: [], misses: [380, 515, 534]}}, {scriptIndex: 0, startPos: 563, endPos: 1119, compiled: true, coverage: {hits: [], misses: [563, 666, 699, 7...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@320031812/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_request.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/pdu_re...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 539, endPos: 733, compiled: true, coverage: {hits: [], misses: [539]}}, {scriptIndex: 0, startPos: 342, endPos: 534, compiled: true, coverage: {hits: [], misses: [342, 374, 384, 391, 411, 44...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@321394108/scripts/package%3Aapp%2Fvcirequests%2Fpdu%2Fpdu_response.dart/16b937b7bcd, uri: package:app/vcirequests/pdu/pdu_r...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 3503, endPos: 3594, compiled: true, coverage: {hits: [], misses: [3503]}}, {scriptIndex: 0, startPos: 323, endPos: 323, compiled: true, coverage: {hits: [], misses: [323]}}, {scriptIndex: 0,...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@322081247/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fecu_pdu_requests.dart/16b937b7bcd, uri: package:app/vcirequests/...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1092, endPos: 1136, compiled: true, coverage: {hits: [], misses: [1092]}}, {scriptIndex: 0, startPos: 84, endPos: 181, compiled: true, coverage: {hits: [], misses: [84, 135, 155]}}, {scriptI...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@323190649/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Fpdu_response_interpreter.dart/16b937b7bcd, uri: package:app/vcir...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@324002755/scripts/package%3Aapp%2Fvcirequests%2Frequests%2Ffunctional_obd_requests.dart/16b937b7bcd, uri: package:app/vcire...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 345, endPos: 1303, compiled: true, coverage: {hits: [], misses: [345]}}, {scriptIndex: 0, startPos: 246, endPos: 302, compiled: true, coverage: {hits: [246], misses: []}}, {scriptIndex: 0, s...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@325196656/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar.dart/16b937b7bcd, uri: package:app/widget/navigation_bar.dart, _k...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 565, endPos: 721, compiled: true, coverage: {hits: [], misses: [565]}}, {scriptIndex: 0, startPos: 726, endPos: 902, compiled: true, coverage: {hits: [], misses: [726, 760, 781, 786, 832, 85...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@326362725/scripts/package%3Aapp%2Fwidget%2Fnavigation_bar_item.dart/16b937b7bcd, uri: package:app/widget/navigation_bar_ite...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 630, endPos: 668, compiled: true, coverage: {hits: [630], misses: []}}, {scriptIndex: 0, startPos: 676, endPos: 713, compiled: true, coverage: {hits: [], misses: [676]}}, {scriptIndex: 0, st...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@327419891/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fapp_wrapper.dart/16b93...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 169, endPos: 593, compiled: true, coverage: {hits: [169, 268, 294, 298, 319, 331, 361, 365, 386, 404, 425, 429, 450, 463, 484, 488, 509, 543], misses: []}}], scripts: [{type: @Script, fixedI...
[   +4 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@330181450/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnection_model_mock....
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 175, endPos: 468, compiled: true, coverage: {hits: [175, 255, 283, 287, 310, 323, 343, 347, 370, 416], misses: []}}], scripts: [{type: @Script, fixedId: true, id: libraries/@331354344/script...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@331354344/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fconnectivity_model_moc...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 203, endPos: 396, compiled: true, coverage: {hits: [203, 293, 314, 318, 334, 344], misses: []}}], scripts: [{type: @Script, fixedId: true, id: libraries/@332356996/scripts/file%3A%2F%2F%2FUs...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@332356996/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_mock.dart/...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 174, endPos: 519, compiled: true, coverage: {hits: [174, 247, 276, 280, 294, 311, 332, 336, 350, 363, 384, 388, 402, 417, 438, 442, 456, 476], misses: []}}], scripts: [{type: @Script, fixedI...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@333176270/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Fhelper%2Fvci_manager_settings_m...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 448, endPos: 1285, compiled: true, coverage: {hits: [448, 459], misses: []}}, {scriptIndex: 0, startPos: 483, endPos: 1282, compiled: true, coverage: {hits: [483, 492], misses: []}}, {script...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@334521489/scripts/file%3A%2F%2F%2FUsers%2Fsp%2FDocuments%2Fdevelopment%2Fdiego-app%2Ftest%2Funit%2Fscreen%2Fhome%2Fhome_tes...
[  +10 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 7423, endPos: 7600, compiled: true, coverage: {hits: [], misses: [7423]}}, {scriptIndex: 0, startPos: 7605, endPos: 7716, compiled: true, coverage: {hits: [], misses: [7605]}}, {scriptIndex:...
[        ] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@346034880/scripts/package%3Aflutter%2Fsrc%2Fcupertino%2Fapp.dart/16b937b7bd5, uri: package:flutter/src/cupertino/app.dart, ...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 14708, endPos: 14861, compiled: true, coverage: {hits: [14708, 14749, 14766, 14784, 14816, 14839], misses: []}}, {scriptIndex: 0, startPos: 14866, endPos: 15395, compiled: true, coverage: {h...
[   +2 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@418125171/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp.dart/16b937b7c04, uri: package:flutter/src/material/app.dart, _k...
[   +4 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 32061, endPos: 32971, compiled: true, coverage: {hits: [], misses: [32061, 32616, 32666, 32704, 32736, 32773, 32806, 32837, 32866, 32956]}}, {scriptIndex: 0, startPos: 42637, endPos: 42705, ...
[   +6 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@419187611/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar.dart/16b937b7c05, uri: package:flutter/src/material/app_bar....
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1112, endPos: 1260, compiled: true, coverage: {hits: [1112], misses: []}}, {scriptIndex: 0, startPos: 2199, endPos: 2706, compiled: true, coverage: {hits: [], misses: [2199, 2396, 2446, 2485...
[   +2 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@420092148/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fapp_bar_theme.dart/16b937b7c05, uri: package:flutter/src/material/ap...
[   +1 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 3621, endPos: 3756, compiled: true, coverage: {hits: [], misses: [3621, 3674, 3703, 3733, 3744]}}, {scriptIndex: 0, startPos: 3761, endPos: 4655, compiled: true, coverage: {hits: [], misses:...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@423408488/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar.dart/16b937b7c05, uri: package:flutter/src/material/b...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1082, endPos: 1164, compiled: true, coverage: {hits: [1082], misses: []}}, {scriptIndex: 0, startPos: 1559, endPos: 1811, compiled: true, coverage: {hits: [], misses: [1559, 1669, 1715, 1757...
[   +3 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@424337866/scripts/package%3Aflutter%2Fsrc%2Fmaterial%2Fbottom_app_bar_theme.dart/16b937b7c05, uri: package:flutter/src/mate...
[   +2 ms] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 32997, endPos: 33220, compiled: true, coverage: {hits: [32997, 33038, 33055, 33079, 33089, 33120, 33129, 33136, 33145, 33152, 33190, 33199], misses: []}}, {scriptIndex: 0, startPos: 33225, e...
[   +6 ms] Result: {type: Script, class: {type: @Class, fixedId: true, id: classes/13, name: Script}, size: 112, fixedId: true, id: libraries/@658236006/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fapp.dart/16b937b7c60, uri: package:flutter/src/widgets/app.dart, _kin...
[        ] Result: {type: SourceReport, ranges: [{scriptIndex: 0, startPos: 1274, endPos: 1403, compiled: true, coverage: {hits: [], misses: [1274]}}, {scriptIndex: 0, startPos: 264, endPos: 264, compiled: true, coverage: {hits: [], misses: [264]}}, {scriptIndex: 0,...
[   +4 ms] Sending to VM service: getScripts({isolateId: isolates/1014886971})
[   +2 ms] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[   +5 ms] test 0: error caught during test; reporting to console
[   +2 ms] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[  +20 ms] test 0: deleting temporary directory
[   +2 ms] test 0: shutting down test harness socket server
[   +3 ms] test 0: finished with out-of-band failure

00:05 +1 -1: loading /Users/sp/Documents/development/diego-app/test/unit/screen/home/home_test.dart [E]                                                                                                
  NoSuchMethodError: The getter 'iterator' was called on null.
  Receiver: null
  Tried calling: iterator
  dart:core-patch/object_patch.dart 50:5                         Object.noSuchMethod
  package:flutter_tools/src/test/coverage_collector.dart 181:51  _getAllCoverage
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                              _Completer.completeError
  dart:async-patch/async_patch.dart 40:18                        _AsyncAwaitCompleter.completeError
  package:flutter_tools/src/test/coverage_collector.dart         _getAllCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                        _asyncThenWrapperHelper
  package:flutter_tools/src/test/coverage_collector.dart         _getAllCoverage
  package:flutter_tools/src/test/coverage_collector.dart 165:10  collect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                        _asyncThenWrapperHelper
  package:flutter_tools/src/test/coverage_collector.dart         collect
  package:flutter_tools/src/test/coverage_collector.dart 61:45   CoverageCollector.collectCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                        _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart           _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 491:36    _FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 446:46    _FlutterPlatform.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23                        _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                       Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 98:31             new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                    _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                    new Timer
  dart:async/timer.dart 87:9                                     Timer.run
  dart:async/future.dart 174:11                                  new Future
  package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
  


```
After that the execution the process did *not* exit until it is killed.

```
flutter doctor -v
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at /usr/local/flutter
    • Framework revision 7a4c33425d (vor 8 Wochen), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[!] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPad (5th generation)   • E5CFFBE3-580D-4644-9F02-46B0B8B68B98     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Sometimes coverage collection will return more than we asked for, it must be filtered out

Fixes https://github.com/flutter/flutter/issues/35120

### CODE REVIEW

File: packages/flutter_tools/lib/src/test/coverage_collector.dart [hunk 1]
```diff
@@ -203,6 +206,13 @@ Future<Map<String, dynamic>> _getAllCoverage(VMService service, bool Function(St
     final Map<String, Map<String, dynamic>> sourceReports = <String, Map<String, dynamic>>{};
     // For each ScriptRef loaded into the VM, load the corresponding Script and
     // SourceReport object.
+
+    // We may receive such objects as
+    // {type: Sentinel, kind: Collected, valueAsString: <collected>}
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/test/coverage_collector.dart]: @bkonyi why does the getScripts vmservice rpc return this?

File: packages/flutter_tools/lib/src/test/coverage_collector.dart [hunk 2]
```diff
@@ -184,13 +184,16 @@ class CoverageCollector extends TestWatcher {
   }
 }
 
-Future<Map<String, dynamic>> collect(Uri serviceUri, bool Function(String) libraryPredicate) async {
-  final VMService vmService = await VMService.connect(serviceUri, compression: CompressionOptions.compressionOff);
+Future<VMService> _defaultConnect(Uri serviceUri) {
+  return VMService.connect(serviceUri, compression: CompressionOptions.compressionOff);
+}
+
+Future<Map<String, dynamic>> collect(Uri serviceUri, bool Function(String) libraryPredicate, [Future<VMService> Function(Uri) connector = _defaultConnect]) async {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/test/coverage_collector.dart]: nit: This line is getting a bit long.

**Review by zanderso — APPROVED** [review]
lgtm w/ nit.

File: packages/flutter_tools/lib/src/test/coverage_collector.dart (hunk 1 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/test/coverage_collector.dart]: As far as I can tell it should never return anything but a `ScriptList`. I can't imagine a situation where a sentinel would ever be returned (see implementation [here](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service.cc#L1404)).

Comment (zanderso) [reply packages/flutter_tools/lib/src/test/coverage_collector.dart]: Maybe the request is referring to an object that was garbage collected, and that is caught before the implementation is invoked? Is there any way to know which argument was collected? @jonahwilliams is it possible the getScripts call could be referring to something stale?

Comment (bkonyi) [reply packages/flutter_tools/lib/src/test/coverage_collector.dart]: `getScripts` only takes an isolate ID as a parameter, so maybe an isolate had been shutdown? I'm not sure what the service does for isolate specific requests when the isolate has already shutdown, but returning a sentinel seems possible in that case.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/test/coverage_collector.dart]: I'm not really sure how that would happen, or how it hasn't happened yet when we run coverage. The repro project in #35120 fairly trivial though

**Comment by stefanpieck** [comment]
I Would suggest to handle to expect Sentinel messages for all RPC calls.

When I started to look deeper into https://github.com/flutter/flutter/issues/35120 I saw the same Error in line 222.
I also found this comment on another Ticket showing an error on this line
https://github.com/flutter/flutter/issues/31196#issuecomment-496946484
And the comment also refers to the version switch from 1.5.3 to 1.5.4

In this line (which is now 258) the result of the RPC call 
getSourceReport is used in the same way
    for (Map<String, dynamic> range in sourceReport['ranges']) {

In the case a Sentinel is returned here, ranges is null on sourceReport


And at last one consideration regarding the fix.
When getScripts returns a Sentinel for an isolate, then the isolate is ignored and with that the coverage data of the isolate. Is that not leading to incomplete Coverage reports?
Another interesting question from my point of view is why the sentinel is returned reproducable dependent on the assets since version 1.5.4
