### PR TITLE
Detect Android SDK 28/28.0.3

### LINKED ISSUE #26909: android licencing and gradle issue
hello. I'm new to flutter and there is something wrong with initilizing the hello_world app and I can't figure it out. I'm using genymotion as Amulator and got Android studio 3.1.2 and gradle 5.1 installed and ready (and use VSCODE as IDE on windows 10) but when I run` flutter run` it shows this in the output. 
 
```
Launching lib/main.dart on Samsung Galaxy S7, 6 0 0, API 23, 1440x2560 in debug mode...
Initializing gradle...                                       2.0s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\gradlew.bat" exited abnormally:

> Configure project :app
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\BEHRAD\AppData\Local\Android\Sdk\licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to install the following Android SDK packages as some licences have not been accepted.
        build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
     Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

     Using Android SDK: C:\Users\BEHRAD\AppData\Local\Android\Sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\BEHRAD\Desktop\learning-flutter\salamemanbetoyareghadimi\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
```

what is the problem and how can I fix this thing?

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/26909

We now require that you have Android SDK 28 and buildtoold 28.0.3.  This makes Flutter Doctor check for that and tell you how to fix it.  Example output with SDK < 28 or BuildTools < 28.0.3:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.152, on Mac OS X 10.14.2 18C54, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /Users/username/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] VS Code (version 1.30.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

The path to SDK manager will be the actual path - if it's missing, other errors are printed.

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_sdk.dart [hunk 1]
```diff
@@ -41,7 +41,7 @@ final RegExp _numberedAndroidPlatformRe = RegExp(r'^android-([0-9]+)$');
 final RegExp _sdkVersionRe = RegExp(r'^ro.build.version.sdk=([0-9]+)$');
 
 /// The minimum Android SDK version we support.
-const int minimumAndroidSdkVersion = 25;
+const int minimumAndroidSdkVersion = 28;
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/android/android_sdk.dart]: This line doesn't actually seem to cause problems - I'll leave it for a separate PR in case it actually would break anything.  Looks like it just controls what gets written to the AndroidManifest.xml

**Review by jonahwilliams — APPROVED** [review]
LGTM

We should probably give people a heads up on the mailing list

**Comment by dnfield** [comment]
One thing I'm not sure of here - if you attempt to run the `sdkmanager` or `sdkmanager.bat` script with Java > 1.8, you can get other errors.

Should we try to capture the work around for that in the doctor message here?
