### PR TITLE
Gold Pre-submit flow for contributors without permissions

### LINKED ISSUE #46687: Gold tryjobs cannot be executed by first-time contributors
Pre-submit tryjobs rely on being able to decrypt the service account on Cirrus. For first time contributors, this becomes an issue when pre-submit checks attempt to run since they have not yet attained write permission to the repository. This is needed in order to decrypt the service account.
Tryjobs cannot execute without authenticating, so another solution must be implemented for this edge case.

Early ideas:
- `goldctl imgtest check` is a new feature from gold to check image results against baselines without authenticating.
  - tests will run, will need triage after merging
  - Will need a way to flag a failing test as permissible so a change can land (see old implementation below) OR
  - we could decide that first time contributors cannot change existing golden files on their first pull request
- The previous, manual implementation of pre-submit checks
  - tests ran, needed triage after merging
  - subject to breaking changes from Gold if the api changes

### LINKED ISSUE #47898: The output when there's a Skia Gold error is inscrutable
One error I got said:
```
The following NonZeroExitCode was thrown while running async test code:
Exit code 1: Skia Gold tryjobAdd failure.
stdout: Given image with hash 382fa8b67631fa1fb565a14393c90dbb for test
cupertino.date_picker_test.datetime.initial
Expectation for test: 6799e6f0fc81d60d1fe72afab17eddd5 (positive)
Expectation for test: 68b87a3d1557212339b24f7023c42b19 (positive)
Expectation for test: 6ee9fed2051d189bfaebcf461ae0e82c (positive)
Expectation for test: 87599f3dec5b56dc110f1b63dc747182 (positive)
Expectation for test: 0eeb47eef65dca3d8a64fb6e65f2ca4d (positive)
Expectation for test: 47fc581696de17734c8d65d0d58336f8 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.datetime.initial&digest=382fa8b67631fa1fb565a14393c90dbb&issue=47875
stderr: ERROR: logging before flag.Parse: I1227 11:30:32.855240   23375 auth.go:364] auth.go:364
Read from file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
ERROR: logging before flag.Parse: I1227 11:30:32.967221   23375 auth.go:364] auth.go:364 Read from
file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
Test: cupertino.date_picker_test.datetime.initial FAIL
```

Another said:
```
The following NonZeroExitCode was thrown while running async test code:
Exit code 1: Skia Gold tryjobAdd failure.
stdout: Given image with hash 24d0b1b915250fc26be3aca836f44bc5 for test
cupertino.date_picker_test.datetime.drag
Expectation for test: 7d04fc1ef547a8e092495dab4294b4cd (positive)
Expectation for test: aa748136c70cefdda646df5be0ae189d (positive)
Expectation for test: c3312ad1479f50caf3754b42a42740c5 (positive)
Expectation for test: f0a6cea41931cb63d141a7eb67b7f8ca (positive)
Expectation for test: 007c679a276885ad84777935ac0b63ce (positive)
Expectation for test: 0b9795b218a8e367b552dcea55c8d589 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.datetime.drag&digest=24d0b1b915250fc26be3aca836f44bc5&issue=47875
stderr: ERROR: logging before flag.Parse: I1227 11:30:34.748231   23505 auth.go:364] auth.go:364
Read from file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
ERROR: logging before flag.Parse: I1227 11:30:34.857654   23505 auth.go:364] auth.go:364 Read from
file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
Test: cupertino.date_picker_test.datetime.drag FAIL
```

Yet another said:
```
The following NonZeroExitCode was thrown while running async test code:
Exit code 1: Skia Gold tryjobAdd failure.
stdout: Given image with hash 5ddf1e33c70bfc68c2353f229a3f7871 for test
cupertino.timer_picker_test.datetime.drag
Expectation for test: 511a4cea88085911d1aa5c4db9686998 (positive)
Expectation for test: 981d20adfaeebfcd139ae761336a3202 (positive)
Expectation for test: 9d01038ff6dc288eeb14b084b4649421 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=cupertino.timer_picker_test.datetime.drag&digest=5ddf1e33c70bfc68c2353f229a3f7871&issue=47875
stderr: ERROR: logging before flag.Parse: I1227 11:30:36.974149   23674 auth.go:364] auth.go:364
Read from file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
ERROR: logging before flag.Parse: I1227 11:30:37.118697   23674 auth.go:364] auth.go:364 Read from
file /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7583/packages/flutter/test/cupertino/serviceAccount.json
Test: cupertino.timer_picker_test.datetime.drag FAIL
```

These are unactionable and intimidating error messages. We should replace them with something that is clear, actionable, and friendly.

cc @Piinks

### PR DESCRIPTION
**Pull request by Piinks**
## Description

There is currently a workaround in place to un-block first time/un-privileged contributors that cannot execute pre-submit tryjobs, but it does not allow these contributors to land new or updated golden file changes.
This is a more complete solution that removes that work around and provides a workflow for these contributors.

For permission-prohibited contributors, the presubmit comparator will instead use the `goldctl imgtest check` feature to lookup image hashes to confirm results. If a check fails, it will retrieve and use the raw expectations to confirm if it is a new test, allowing it to pass through, or if it is an expected change via Gold's ignore feature. 

This very similar to the pre-tryjob implementation, without requesting images and manually comparing, and without the need to access Gold's details API. 

Better error messages have been included in this change to provide more informative and actionable messaging in all of these use cases.

## Related Issues

Fixes #46687
Fixes #47898

## Tests

As an authorized contributor in this case, I reversed the logic on an earlier commit (and since reverted) to ensure that the presubmit checks completed correctly for the unauthorized use case.

- Restores all ignore tests from before tryjobs so that first-time contributors can make use of the feature
- The presubmit comparator makes the correct choice for authorized and unauthorized test cases
- The unauthorized comparator uses ignores to allow for expected changes and new tests

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 1]
```diff
@@ -248,7 +248,8 @@ class AnimationController extends Animation<double>
     _internalSetValue(value ?? lowerBound);
   }
 
-  /// Creates an animation controller with no upper or lower bound for its value.
+  /// Creates an animation controller with no upper or lower bound for its
```
Comment (Piinks) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Trivial framework change to trigger the appropriate test shards.

File: packages/flutter_goldens_client/lib/skia_client.dart [hunk 2]
```diff
@@ -297,12 +340,70 @@ class SkiaGoldClient {
...
     if (result.exitCode != 0) {
-      final StringBuffer buf = StringBuffer()
-        ..writeln('Skia Gold tryjobAdd failure.')
-        ..writeln('stdout: ${result.stdout}')
-        ..writeln('stderr: ${result.stderr}\n');
-      throw NonZeroExitCode(1, buf.toString());
+      // This branch may just be out of date, this is useful when someone has
+      // landed a golden file change elsewhere.
+      if (await imgtestCheck(testName, goldenFile))
+        return true;
```
Comment (Piinks) [inline packages/flutter_goldens_client/lib/skia_client.dart]: @kjlubick Will this work like I think it will? 
I want to be able to check all known expectations if the tryjob fails, since the tryjob only checks against head.

Comment (kjlubick) [reply packages/flutter_goldens_client/lib/skia_client.dart]: imgtest check takes the --changelist and --crs flags, so if you provide those, I believe it will properly check against the master expectations with the expectations specific to the given CL applied.

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: In that case, should I use `check` before generating a tryjob? That way only failing checks move forward with a tryjob?

File: packages/flutter_goldens/lib/flutter_goldens.dart [hunk 3]
```diff
@@ -299,41 +295,138 @@ class FlutterPreSubmitFileComparator extends FlutterGoldenFileComparator {
...
   @override
   Future<bool> compare(Uint8List imageBytes, Uri golden) async {
-    golden = _addPrefix(golden);
-    await update(golden, imageBytes);
-    final File goldenFile = getGoldenFile(golden);
-
-    return skiaClient.tryjobAdd(golden.path, goldenFile);
+    assert(
+      false,
+      'The FlutterPreSubmitComparator has been used to execute a golden '
```
Comment (Piinks) [inline packages/flutter_goldens/lib/flutter_goldens.dart]:
```suggestion
      'The FlutterPreSubmitFileComparator has been used to execute a golden '
```

File: packages/flutter_goldens/lib/flutter_goldens.dart [hunk 4]
```diff
@@ -299,41 +295,138 @@ class FlutterPreSubmitFileComparator extends FlutterGoldenFileComparator {
...
+    golden = _addPrefix(golden);
+    await update(golden, imageBytes);
+    final File goldenFile = getGoldenFile(golden);
+
+    // This branch may just be out of date, this is useful when someone has
+    // landed a golden file change elsewhere.
+    if (await skiaClient.imgtestCheck(golden.path, goldenFile))
+      return true;
+
+    return skiaClient.tryjobAdd(golden.path, goldenFile);
```
Comment (Piinks) [inline packages/flutter_goldens/lib/flutter_goldens.dart]: Moved check here to preempt running a tryjob

File: packages/flutter_goldens_client/lib/skia_client.dart (hunk 2 above)
Comment (kjlubick) [reply packages/flutter_goldens_client/lib/skia_client.dart]: I'm a little confused as to when this check happens. My thought was that this presubmit logic happens as follows
A: user works on branch locally
B: user uploads branch to GitHub.
C: user makes PR from branch
D: <PRESUBMIT HAPPENS>
E: user (or flutter owner) triages expected new things.
F: (optional) user uploads more commits
G: pr is approved
H: <PRESUBMIT HAPPENS> (??only if D failed or F happened??)
I: commit lands in repo

If this is the case, then you'll want to add those two flags to your invocation of `imgtest check` so that the new expectations from E are applied when H runs. Otherwise, H will fail just like D would have.

If I'm misunderstanding when this PRESUBMIT happens (for example, as a condition to B), then a PR doesn't exist, therefore expectations not on master can't exist, which means you don't need to provide the --changelist and --crs flag to your invocation.

File: packages/flutter_goldens/lib/flutter_goldens.dart (hunk 4 above)
Comment (kjlubick) [reply packages/flutter_goldens/lib/flutter_goldens.dart]: I'd recommend *not* doing this - the tryjobAdd is basically free and it lets you "audit" all of the output of a tryjob, not just the goldens that are untriaged.

Comment (Piinks) [reply packages/flutter_goldens/lib/flutter_goldens.dart]: Right right right. I think I've gotten a little turned around on this. I'll revert this change.

File: packages/flutter_goldens_client/lib/skia_client.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: Ah! I think I see now. Thank you for explaining. 
That all sounds right, I will add the arguments.

The other case I was trying to cover is when that change lands in the repo, it seems that all other branches fail tryjobs since they do not have the change. It seems that tryjobs do not check all expectations (past and present) like the previous manual implementation did. 

I am not 100% sure it is exactly what is happening. It could be that this is the triage race condition that was fixed last week masquerading as something else. Updates to golden files aren't updated very often so it's been hard to pin down.

Comment (kjlubick) [reply packages/flutter_goldens_client/lib/skia_client.dart]: I wonder if the CL's expectations aren't being merged into master fast enough?

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: Hm. How about this, I will revert adding a check in conjunction with a tryjob and monitor this a while longer to better diagnose the potential edge case. :) WDYT?

Comment (kjlubick) [reply packages/flutter_goldens_client/lib/skia_client.dart]: sgtm

**Comment by Piinks** [comment]
This is ready for review. @dnfield, this is the full solution for users without the proper permissions on Cirrus, and replaces the workaround I put in place before the holiday.

File: packages/flutter_goldens/lib/flutter_goldens.dart [hunk 5]
```diff
@@ -299,41 +295,133 @@ class FlutterPreSubmitFileComparator extends FlutterGoldenFileComparator {
...
+    if (!baseDirectory.existsSync())
+      baseDirectory.createSync(recursive: true);
 
     goldens ??= SkiaGoldClient(baseDirectory);
-    await goldens.auth();
-    await goldens.tryjobInit();
-    return FlutterPreSubmitFileComparator(baseDirectory.uri, goldens);
+
+    final bool hasWritePermission = platform.environment['CIRRUS_USER_PERMISSION'] == 'admin'
+      || platform.environment['CIRRUS_USER_PERMISSION'] == 'write';
```
Comment (dnfield) [inline packages/flutter_goldens/lib/flutter_goldens.dart]: Is this how we check elsewhere?

I think it would be better if we check the actual env variable that has the service account key and see if it starts with `ENCRYPTED[` or something like that.  That's what we really care about, right?

Comment (Piinks) [reply packages/flutter_goldens/lib/flutter_goldens.dart]: Will do! :)

**Review by dnfield — APPROVED** [review]
LGTM
