### PR TITLE
Fix padding for ScrollableList

### LINKED ISSUE #1808: Left padding is missing with ScrollableList
new ScrollableList(
      padding: const EdgeDims.all(24.0),
      itemExtent: 48.0,
      children: [ ... ]
    )

image

### PR DESCRIPTION
**Pull request by abarth**
Previously we had totally wrong behavior. Now we have more correct behavior and
testing.

Fixes #1808

### CODE REVIEW

File: packages/flutter/test/widget/scrollable_list_hit_testing_test.dart [hunk 1]
```diff
@@ -85,11 +84,80 @@ void main() {
       expect(tester.findText('3'), isNotNull);
       expect(tester.findText('4'), isNull);
       expect(tester.findText('5'), isNull);
-      expect(tapped, equals([2]));
+      expect(tapped, equals([]));
```
Comment (Hixie) [inline packages/flutter/test/widget/scrollable_list_hit_testing_test.dart]: mumble mumble types on array literals

**Comment by Hixie** [comment]
lgtm
