### PR TITLE
Use strut box heights to calculate selection rectangles in order to ensure that they remain within visible bounds

### LINKED ISSUE #40633: Selection cursors vanishing
When creating a `TextField` with a `TextStyle` which `height` property is 1, the selection cursors won't pop up when selecting a text.

## Steps to Reproduce

Just create a `TextField` as previously described:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: TextField(
          style: TextStyle(height: 1),
        ),
      ),
    );
  }
}
```

### Default `TextStyle`:

Screenshot_1568676553

### `TextStyle` with `height` 1:

Screenshot_1568676532

## Logs

```
[√] Flutter (Channel unknown, v1.9.1+hotfix.2, on Microsoft Windows [versÃ£o 10.0.18362.356], locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (10 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\hugoc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

@justinmc Perhaps you have some ideas on this. Thanks.

### PR DESCRIPTION
**Pull request by jason-simmons**
Also change StrutStyle.disabled to use a height of 1.0 so its results will
match the default tight bounds.

Fixes https://github.com/flutter/flutter/issues/40633

### CODE REVIEW

File: packages/flutter/lib/src/painting/strut_style.dart [hunk 1]
```diff
@@ -362,7 +362,7 @@ class StrutStyle extends Diagnosticable {
   /// Equivalent to having no strut at all. All lines will be laid out according to
   /// the properties defined in [TextStyle].
   static const StrutStyle disabled = StrutStyle(
-    height: 0.0,
+    height: 1.0,
```
Comment (GaryQian) [inline packages/flutter/lib/src/painting/strut_style.dart]: `null` may be the better choice here, as 1.0 is indicating it should be exactly the fontSize height, ignoring the font provided height

**Comment by GaryQian** [comment]
I believe this is a breaking change, I would make sure it goes through the breaking change policy. I suspect this should go through without any issues.

File: packages/flutter/lib/src/painting/strut_style.dart (hunk 1 above)
Comment (GaryQian) [reply packages/flutter/lib/src/painting/strut_style.dart]: Actually, 0.0 is correct, since Strut is meant as a minimum line height. Disabled strut with 1.0 would prevent text from being smaller than the fontSize, which would defeat the purpose of a "disabled" strut, which is meant to have the effect of there being no strut on the paragraph.

Comment (GaryQian) [reply packages/flutter/lib/src/painting/strut_style.dart]: The 1.0 strut would probably be better under a separately named static constant, maybe `regular` or something.

**Review by GaryQian — CHANGES_REQUESTED** [review]
See above

**Comment by jason-simmons** [comment]
Removed the change to `StrutStyle.disabled` and updated the uses of `StrutStyle.disabled` in the framework and tests.  PTAL.

**Review by GaryQian — APPROVED** [review]
LGTM, pending announcement of change.

**Review by vishna — COMMENTED** [review]
Please make caret height customizable

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 2]
```diff
@@ -4074,7 +4075,8 @@ void main() {
 
     await tester.longPressAt(textfieldStart + const Offset(50.0, 2.0));
     await tester.pump(const Duration(milliseconds: 150));
-    await tester.tapAt(textfieldStart + const Offset(20.0, 146.0));
+    // Tap the Select All button.
+    await tester.tapAt(textfieldStart + const Offset(20.0, 100.0));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart]: Why did these y coordinates need to change?

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 2 above)
Comment (jason-simmons) [reply packages/flutter/test/cupertino/text_field_test.dart]: The position of various text editor UI elements such as the selection handles is related to the caret position, and apparently the Cupertino "select all" button is affected.  I don't know exactly how that position is calculated though.

Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart]: Ah of course.  Thanks for the explanation.

**Comment by goderbauer** [comment]
(triage) Looks like the breaking change was announced 8 days ago: https://groups.google.com/g/flutter-announce/c/hVP699NQ7PQ

Is this one ready to land?

**Comment by jason-simmons** [comment]
This is ready to land, but I'd like to wait until the various rolls in progress stabilize.
