### PR TITLE
Fix `DropdownMenu` with `expandedInsets` always aligned on top

### LINKED ISSUE #155581: DropdownMenu can not be center aligned when using `expandedInsets`
### Steps to reproduce

1. Put a dropdown in a `Center` widget and put that inside an `Expanded` widget 
2. Use `expandedInsets`

### Expected results

The dropdown should be centered

### Actual results

The dropdown sticks to the top

### Code sample

<details open><summary>Code sample</summary>

```dart
Row(
  mainAxisAlignment: MainAxisAlignment.center,
  children: <Widget>[
    Expanded(
      child: Center(
        child: DropdownMenu<int>(
          inputDecorationTheme: const InputDecorationTheme(
            helperMaxLines: 5,
            border: OutlineInputBorder()
          ),
          expandedInsets: const EdgeInsets.symmetric(horizontal: 40),
          helperText: "Some long helper text.",
          initialSelection: 1,
          label: const Text("A number"),
          onSelected: (final int? num) {
          },
          dropdownMenuEntries:
            [1, 2, 3].map<DropdownMenuEntry<int>>(
              (final int num) {
                return DropdownMenuEntry<int>(
                  value: num,
                  label: "$num"
                );
              }
            ).toList(),
        ),
      ),
    ),
    Expanded(
      child: Center(
        child: DropdownMenu<double>(
          inputDecorationTheme: const InputDecorationTheme(
            helperMaxLines: 5,
            border: OutlineInputBorder()
          ),
          expandedInsets: const EdgeInsets.symmetric(horizontal: 40),
          helperText: "Long text.",
          initialSelection: 1.0,
          label: const Text("Another"),
          onSelected: (final double? num) {
          },
          dropdownMenuEntries:
            [1.0, 2.0, 3.0].map<DropdownMenuEntry<double>>(
              (final double num) {
                return DropdownMenuEntry<double>(
                  value: num,
                  label: "$num"
                );
              }
            ).toList(),
        ),
      ),
    ),
  ]
),
```

https://github.com/flutter/flutter/blob/aef2758716b806ec2d567b519dba0bf0643d9031/packages/flutter/lib/src/material/dropdown_menu.dart#L951-L970

</details>
The second code block above seems to be the issue.

### Screenshots or Video

<details open>
<summary>Dropdowns stuck to the top</summary>
image

<summary>Remove `expandedInsets` and it comes down to the center but we lose the full width</summary>
image

</details>

### Logs

NA

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 12.7.6 21H1320 darwin-x64, locale en-GB)
    • Flutter version 3.24.1 on channel stable at /Users/<user>/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (5 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/<user>/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • 1C6417FB-1C3E-4088-B3BD-8BD3E816ADD5 • ios        •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64 • macOS 12.7.6 21H1320 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
Fixes [DropdownMenu can not be center aligned when using expandedInsets
](https://github.com/flutter/flutter/issues/155581)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final List<DropdownMenuEntry<ShortMenu>> shortMenuItems =
        <DropdownMenuEntry<ShortMenu>>[];
    for (final ShortMenu value in ShortMenu.values) {
      final DropdownMenuEntry<ShortMenu> entry =
          DropdownMenuEntry<ShortMenu>(value: value, label: value.label);
      shortMenuItems.add(entry);
    }

    return MaterialApp(
      home: Scaffold(
        body: Row(
          children: <Widget>[
            Expanded(
              child: Center(
                child: DropdownMenu<ShortMenu>(
                  expandedInsets: const EdgeInsets.all(16),
                  initialSelection: ShortMenu.item0,
                  dropdownMenuEntries: shortMenuItems,
                  label: const Text('With expandedInsets'),
                ),
              ),
            ),
            Expanded(
              child: Center(
                child: DropdownMenu<ShortMenu>(
                  initialSelection: ShortMenu.item0,
                  dropdownMenuEntries: shortMenuItems,
                  label: const Text('Without expandedInsets'),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

enum ShortMenu {
  item0('Menu 0'),
  item1('Menu 1'),
  item2('Menu 2');

  const ShortMenu(this.label);
  final String label;
}
```

</details>

### Before 
(`DropdownMenu` without `expandedInsets` cannot be centered)
Screenshot 2024-10-04 at 14 13 58

### After
(`DropdownMenu` with `expandedInsets` be centered)

Screenshot 2024-10-04 at 14 13 49

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by TahaTesser** [comment]
@QuncCccccc 
It looks like you added alignment for safety in https://github.com/flutter/flutter/pull/129753. I removed it in this PR so the user can align the dropdown menu however they like. If it fails any internal tests, please do let me know. :)

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -3415,6 +3415,48 @@ void main() {
...
+        home: Scaffold(
+          body: Row(
+            children: <Widget>[
+              Expanded(
+                child: Align(
+                  alignment: alignment,
+                  child: DropdownMenu<ShortMenu>(
+                    expandedInsets: const EdgeInsets.all(16),
+                    dropdownMenuEntries: shortMenuItems,
+                  ),
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:3436]:
```suggestion
                  child: DropdownMenu<TestMenu>(
                    expandedInsets: const EdgeInsets.all(16),
                    dropdownMenuEntries: menuChildren,
                  ),
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -3415,6 +3415,48 @@ void main() {
       tester.getRect(find.byType(TextField).first).bottom,
     );
   });
+
+  testWidgets('DropdownMenu with expandedInsets can be aligned', (WidgetTester tester) async {
+    final List<DropdownMenuEntry<ShortMenu>> shortMenuItems = <DropdownMenuEntry<ShortMenu>>[];
+    for (final ShortMenu value in ShortMenu.values) {
+      final DropdownMenuEntry<ShortMenu> entry = DropdownMenuEntry<ShortMenu>(value: value, label: value.label);
+      shortMenuItems.add(entry);
+    }
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:3424]:
```suggestion
```

Simplify the test by using TestMenu entries instead of ShortMenu entries.

**Review by bleroux — APPROVED** [review]
LGTM!
See my comments to make the test shorter.
