### PR TITLE
fix the DropdownButtonFormField's label display bug when the `hint` is non-null

### LINKED ISSUE #87102: The position of  `DropdownButtonFormField labelText` is wrong when the `hint` is non-null
### Code Demo
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int? value;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Form(
        onChanged: () {},
        child: Center(
          child: DropdownButtonFormField<int?>(
            decoration: const InputDecoration(
              labelText: 'labelText',
            ),
            value: value,
            hint: const Text('Hint'),
            onChanged: (int? newValue) {
              value = newValue;
            },
            items: const <DropdownMenuItem<int?>>[
              DropdownMenuItem<int?>(
                value: 1,
                child: Text('One'),
              ),
              DropdownMenuItem<int?>(
                value: 2,
                child: Text('Two'),
              ),
              DropdownMenuItem<int?>(
                value: 3,
                child: Text('Three'),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

### Screenshot
image

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #87102 
The position of `DropdownButtonFormField`'s label should move above when the `hint` is non-null.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 1]
```diff
@@ -149,6 +149,58 @@ void verifyPaintedShadow(Finder customPaint, int elevation) {
...
+                child: Text('One'),
+              ),
+              DropdownMenuItem<int?>(
+                value: 2,
+                child: Text('Two'),
+              ),
+              DropdownMenuItem<int?>(
+                value: 3,
+                child: Text('Three'),
+              )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/dropdown_form_field_test.dart:181]: Nit: add a trailing comma.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -1650,6 +1650,9 @@ class DropdownButtonFormField<T> extends FormField<T> {
            final InputDecoration effectiveDecoration = decorationArg.applyDefaults(
              Theme.of(field.context).inputDecorationTheme,
            );
+           final bool _isEmpty =
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/dropdown.dart:1653]: Nit: avoid using `_`.

**Review by Renzo-Olivares — CHANGES_REQUESTED** [review]
Just a few comments. Thank you for fixing this regression @xu-baolin!

File: packages/flutter/lib/src/material/dropdown.dart [hunk 3]
```diff
@@ -1650,6 +1650,14 @@ class DropdownButtonFormField<T> extends FormField<T> {
            final InputDecoration effectiveDecoration = decorationArg.applyDefaults(
              Theme.of(field.context).inputDecorationTheme,
            );
+
+           final bool showSelectedItem = !(items == null || items.where((DropdownMenuItem<T> item) => item.value == state.value).isEmpty);
+           final bool showHintOrDisabledHint =
+             (onChanged != null)
+             ? hint != null && !showSelectedItem
+             : (hint != null || disabledHint != null) && !showSelectedItem;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/dropdown.dart:1658]: We should also consider the `disabledHint` shown when the menu is disabled.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/dropdown.dart]: done

**Comment by xu-baolin** [comment]
/// A preferred placeholder widget that is displayed when the dropdown is disabled.
  ///
  /// If [value] is null, the dropdown is disabled ([items] or [onChanged] is null),
  /// this widget is displayed as a placeholder for the dropdown button's value.
  final Widget? disabledHint;

bool get _enabled => widget.items != null && widget.items!.isNotEmpty && widget.onChanged != null;

We should also consider the `disabledHint` shown cases.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/dropdown.dart]: Good catch!

File: packages/flutter/lib/src/material/dropdown.dart [hunk 4]
```diff
@@ -1650,6 +1650,19 @@ class DropdownButtonFormField<T> extends FormField<T> {
...
+           final bool showHintOrDisabledHint = () {
+             if (onChanged == null) {
+               return (hint != null || disabledHint != null) && !showSelectedItem;
+             } else if (items == null || items.isEmpty) {
+               return hint != null || disabledHint != null;
+             } else {
+               return hint != null && !showSelectedItem;
+             }
+           }();
+           final bool isEmpty = !showSelectedItem && !showHintOrDisabledHint;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/dropdown.dart:1664]:
```suggestion
           final bool showSelectedItem = items != null && items.where((DropdownMenuItem<T> item) => item.value == state.value).isNotEmpty;
           bool showHintOrDisabledHint() {
             final bool isDropdownDisabled = onChanged == null || (items == null || items.isEmpty);
             if (isDropdownDisabled) {
               return hint != null || disabledHint != null;
             } else {
               return hint != null;
             }
           };
           final bool isEmpty = !showSelectedItem && !showHintOrDisabledHint();
```

What do you think about this logic? I think since we "and" `!showSelectedItem` when setting `isEmpty` we can move it out of `showHintOrDisabledHint`.

**Review by Renzo-Olivares — COMMENTED** [review]
Thank you for making the requested changed! I just had one more suggestion regarding `showHintOrDisabledHint`.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/dropdown.dart:1664]: If `onChange != null && hint != null && diabledHint == null && item == null`, the `isEmpty` should be true.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/dropdown.dart:1664]: If we wanna remove the `!showSelectedItem` logic, we should also change the variable name I think.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/dropdown.dart:1664]: @Renzo-Olivares you are right we can merge some logic together , how about change the method name to `showHintOrDisabledHintWhenNoSelectedItem`?

**Review by Renzo-Olivares — APPROVED** [review]
LGTM thank you @xu-baolin!
