### PR TITLE
Sanitize error message sent to GitHub crash reporter

### LINKED ISSUE #50986: Show more than 20 lines of the backtrace in the tool crash GitHub report
20 isn't always enough.

See https://github.com/flutter/flutter/issues/50860

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Sanitize error message that gets sent to GitHub creation template, and thus the shortener service.
Audited for top errors types and stripped message for personally identifiable information.  Thrown strings show the number of characters in the message.  Fall back to just runtimeType.

## Related Issues

Next part of https://github.com/flutter/flutter/issues/53140
Fixes https://github.com/flutter/flutter/issues/50986

## Tests

github_template_tests

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Comment by jmagman** [comment]
\cc @jamesderlin

File: packages/flutter_tools/lib/src/reporting/github_template.dart [hunk 1]
```diff
@@ -36,16 +41,52 @@ class GitHubTemplateCreator {
     return 'https://github.com/flutter/flutter/issues?q=is%3Aissue+${Uri.encodeQueryComponent(errorString)}';
   }
 
+  /// Sanitize personally identifiable information (PII) from error string before
+  /// sending to GitHub URL shortener service.
+  static String sanitizedCrashException(dynamic error) {
+    if (error is ProcessException) {
+      // Suppress args.
+      return 'ProcessException: ${error.message} Command: ${error.executable}, OS error code: ${error.errorCode}';
```
[the remark this answers is not in the document]
Comment (jmagman) [reply packages/flutter_tools/lib/src/reporting/github_template.dart:49]: I checked, `executable` is just `cd` or `unzip` or whatever, it's not to a path.
https://github.com/flutter/flutter/issues/52437
```
ProcessException: The command failed
Command: unzip -o -q /Users/sagidamti/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/c4229bfbbae455ad69c967be19aee3fadd6486e1/sky_engine.zip -d /Users/sagidamti/flutter/bin/cache/pkg
```
Is generated from
```
"ProcessException: $msg\n  Command: $executable $args";
```

File: packages/flutter_tools/lib/src/reporting/github_template.dart [hunk 2]
```diff
@@ -36,16 +41,52 @@ class GitHubTemplateCreator {
...
+    } else if (error is FileSystemException) {
+      // Suppress path.
```
[the remark this answers is not in the document]
Comment (jmagman) [reply packages/flutter_tools/lib/src/reporting/github_template.dart:51]: Could be the project directory with the app name.

**Review by zanderso — APPROVED** [review]

File: packages/flutter_tools/test/general.shard/github_template_test.dart [hunk 3]
```diff
@@ -195,3 +310,10 @@ class SuccessShortenURLFakeHttpClient extends FakeHttpClient {
     return SuccessFakeHttpClientRequest();
   }
 }
+
+class FakeError implements Error {
+  @override
+  StackTrace get stackTrace => StackTrace.fromString('''
+#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
+#1      _rootRunUnary (dart:async/zone.dart:1141:38)''');
+}
```
Comment (Hixie) [inline packages/flutter_tools/test/general.shard/github_template_test.dart:319]: would be good to have a test that pretends to have sensitive information in an unknown exception class (like FakeError with a toString that contains fake PII), and verifies that none of that information leaks out.

File: packages/flutter_tools/lib/src/reporting/github_template.dart [hunk 4]
```diff
@@ -36,16 +41,51 @@ class GitHubTemplateCreator {
...
   /// GitHub URL to present to the user containing encoded suggested template.
   ///
   /// Shorten the URL, if possible.
   Future<String> toolCrashIssueTemplateGitHubURL(
       String command,
-      String errorString,
-      String exception,
+      dynamic error,
       StackTrace stackTrace,
       String doctorText
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/reporting/github_template.dart:86]: the doctor text can also include lots of potentially sensitive information (device IDs, paths, etc).

File: packages/flutter_tools/test/general.shard/github_template_test.dart (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/github_template_test.dart:319]: Added in https://github.com/flutter/flutter/pull/96250/files#diff-c35c1425f1f396a35eca11a3edfae52343a312256d6df2cea65d238867cc97ffR313.

File: packages/flutter_tools/lib/src/reporting/github_template.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/reporting/github_template.dart:86]: Tracking in https://github.com/flutter/flutter/issues/53140.
