### PR TITLE
Have Material widgets in a Cupertino App partially use Cupertino theme

### LINKED ISSUE #138621: Flutter 3.16 CupertinoApp and Material Widgets
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just ran the app as usual

### Expected results

So I have an App that since upgraded to Flutter 3.16.0 has suffered some changes on colors and text.

I have attached below some pictures of the screen rendered using both Flutter 3.13.9 and 3.16.0 and also the Color Measure tool results on each screen.

What I expected was that the colors remained the same, since I haven't found anything on the changelogs saying anything about changes on that matter.

Also looking at AppBar title, it changed to black with default font, and it was white before with my font.

### Actual results

Different colors:

On v3.13.9 those buttons where white (255, 255, 255) and on v3.16.0 became "purple-ish" (246, 240, 248)

Also, AppBar title became black and with different font.

### Code sample

This is my CupertinoApp (unchanged from each version)

```dart
    final CupertinoApp iosApp = CupertinoApp(
      title: _title,
      debugShowCheckedModeBanner: false,
      theme: const CupertinoThemeData(
        primaryColor: FortmobileColors.purple,
        barBackgroundColor: FortmobileColors.purple,
        scaffoldBackgroundColor: FortmobileColors.purple,
        textTheme: CupertinoTextThemeData(
          textStyle: TextStyle(fontFamily: 'Inter'),
          actionTextStyle: TextStyle(fontFamily: 'Inter'),
          navActionTextStyle: TextStyle(fontFamily: 'Inter'),
          dateTimePickerTextStyle: TextStyle(fontFamily: 'Inter'),
          pickerTextStyle: TextStyle(fontFamily: 'Inter'),
          tabLabelTextStyle: TextStyle(fontFamily: 'Inter'),
          navTitleTextStyle: TextStyle(fontFamily: 'Inter'),
          navLargeTitleTextStyle: TextStyle(fontFamily: 'Inter'),
        ),
        brightness: Brightness.light,
      ),
      initialRoute: '/',
      routes: Routes.getRoutes(context),
      navigatorObservers: <NavigatorObserver>[FirebaseAnalyticsObserver(analytics: Requests.analytics)],
      navigatorKey: NavigationService.navigatorKey,
      color: FortmobileColors.purple,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [Locale('pt', 'BR')],
    );
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

### Flutter 3.13.9:

Simulator Screenshot - iPhone 14 Pro - 2023-11-17 at 10 44 54

## COLOR:

Captura de Tela 2023-11-17 às 11 30 48

### Flutter 3.16.0:

Simulator Screenshot - iPhone 14 Pro - 2023-11-17 at 11 26 48

## COLOR
Captura de Tela 2023-11-17 às 11 30 28

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1 23B74 darwin-arm64, locale pt-BR)
    • Flutter version 3.16.0 on channel stable at /Users/fernandorocha/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fernandorocha/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • FD97ADA4-9B37-4F8B-87EB-60EB9796CC71 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 119.0.6045.159
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Fernando Rocha. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #138621

Fixes and issue where if a Material widget is used in a Cupertino App, then some parts of it's default Material 3 theming would show up as purplish. This could be fixed by wrapping your app with a Material theme, but that's a little awkward.

Material and Cupertino themes interact with each other a little oddly. If a theme of either is searched for but does not exist, then a default one is generated. So if a Material widget is in a Cupertino app that does not already have a Material theme, then a fallback Material theme will be created. This PR makes it so that, in this case when that Material theme is created, it's default colors will be based on the Cupertino theme.

Another oddity is that a Material theme always wraps itself with a Cupertino theme that's values are based on the Material theme. So before this change, a Material widget would theoretically add a new Material based Cupertino theme to the tree. So I added logic that would have the Material theme check to see if a Cupertino theme exists, before it overwrites it.

Before:
image

After:
Screenshot 2023-11-29 at 10 37 09 AM

Update:
I changed it to not rely on the Material 3 flag. Instead, if a Material theme is searched for and there is already a Cupertino theme in the tree, then it will use that Cupertino theme instead of generating a new. Also, if a Material theme is searched for, and it does not find one already in the tree, but does find a Cupertino theme, then it will generate one with a color palette based off of that Cupertino theme's colors.

After with this change:
Screenshot 2024-05-09 at 10 16 22 AM

We should still probably suggest for developers to include a Material theme in their Cupertino app if they wish to use widgets from both packages.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
CC @QuncCccccc @HansMuller this is a fairly simple fix, but feels like a bandaid on a larger issue. Theoretically this should make it so that if `Theme.of` is used inside a `MaterialApp` it should use Material 3 for Material widgets, but otherwise it will not. Let me know if there's a case I missed.

But this does put a bandaid on a larger issue. I was surprised to find that a Material theme will wrap itself with a Cupertino theme. So Material widgets in a Cupertino app with no Material theme ancestor will create their own Cupertino theme, regardless of there already being one, which feels gross. I did try and wrap a basic Material theme around the Cupertino app widget to copy the solution from the Material side, but that created a dependency loop. Which was almost a relief because that was ugly too. I think it is important to fix this issue with something simple like this, but ideally the two themes would be aware of each other, if not unified in some way.

**Comment by QuncCccccc** [comment]
I think this fix is smart! But not sure if this change will cause any confusion because we just made material 3 be default and then in this PR, we change the fallback to false?

**Comment by MitchellGoodwin** [comment]
> I think this fix is smart! But not sure if this change will cause any confusion because we just made material 3 be default and then in this PR, we change the fallback to false?

My intention was to have Cupertino apps default to having the material 3 flag be false. And as far as I can tell, that fallback is only used when there is no theme in the tree. So it should not be used when either a `MaterialApp` or `Theme` are provided, as `MaterialApp` always generates a theme. Is there a case I'm missing?

**Comment by QuncCccccc** [comment]
Ah some unit tests might just build a widget without using `MaterialApp` or `Theme`, for example this one: https://github.com/flutter/flutter/pull/139145/files#diff-15ce4cd7a95566046eb6b57655b02d175a8297d14b033a5dc15fd5aa5aa866fbR209

But other than this, I also don't see any other use cases:)

**Comment by goderbauer** [comment]
I spoke to @MitchellGoodwin and he said this is still on his radar.

**Comment by MitchellGoodwin** [comment]
Converting this to a draft, as if the `useMaterial3` flag gets removed in the future, then this will break. Keeping this around as a draft for the purpose of discussion.

**Comment by MitchellGoodwin** [comment]
@HansMuller this it the draft for having the themes get along. I'll add documentation recommending that developers add a Material theme to their Cupertino apps.

**Review by QuncCccccc — APPROVED** [review]
This solution makes sense to me! LGTM:) The new classes might need some more documentation.

File: packages/flutter/lib/src/material/theme_data.dart [hunk 1]
```diff
@@ -2210,6 +2210,34 @@ class MaterialBasedCupertinoThemeData extends CupertinoThemeData {
...
+/// colors from a [CupertinoThemeData]. This is intended to be used only in the
+/// case when a Material widget is unable to find a Material theme in the tree,
+/// but is able to find a Cupertino theme. Most often this will occur when a
+/// Material widget is used inside of a [CupertinoApp].
+///
+/// Besides the colors, this theme will use all the defaults from Material's
+/// [ThemeData], so if further customization is needed, it is best to manually
+/// add a Material [Theme] above the [CupertinoApp].
+class CupertinoBasedMaterialThemeData {
+
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/theme_data.dart:2223]:
```suggestion
```

**Review by QuncCccccc — APPROVED** [review]
LGTM：）
