### PR TITLE
Fix a [_ViewportElement] RenderObjectChild update bug

### LINKED ISSUE #25861: StreamBuilders cannot be the first child of CustomScrollView
Hello,

I found a bug where if a StreamBuilder is the first child of a CustomScrollView it will throw these two errors randomly.

```
flutter: Another exception was thrown: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1213 pos 12: 'center.parent == this': is not true.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

It does not matter if the StreamBuilder is returning a sliver or not.

What's worse is it's not consistent. Out of 10 tries it will happen maybe 6 times and in seemingly random order. Possible race condition?

The workaround is to place a `SliverToBoxAdapter()` as the first child, then the problem goes away.

### LINKED ISSUE #55170: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1568 pos 12: 'center.parent == this': is not true.  viewport.dart assertion fail when changing the first Sliver of a CustomScrollView
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

<details><summary>Code & pubspec.yaml</summary>

**main.dart**
```dart
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => BlocProvider(
        create: (_) => SomeBloc(),
        child: MaterialApp(
          title: 'Bug',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: SomeWidget(),
        ),
      );
}

class SomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (context, innerBoxScrolled) => [
            SliverAppBar(
              title: Text('bug'),
              pinned: true,
              actions: <Widget>[
                IconButton(
                  icon: Icon(Icons.add),
                  onPressed: () =>
                      BlocProvider.of<SomeBloc>(context).add(SomeEvent()),
                )
              ],
            )
          ],
          body: CustomScrollView(
            slivers: <Widget>[
              BlocBuilder<SomeBloc, SomeBaseBlocState>(
                builder: (context, state) {
                  if (state is InitState) {
                    return const SliverToBoxAdapter(
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    );
                  } else if (state is SomeOtherState) {
                    return const SliverPadding(
                      padding: EdgeInsets.all(20),
                      sliver: SliverToBoxAdapter(
                        child: Center(
                          child: Text('It breaks before rendering this'),
                        ),
                      ),
                    );
                  }

                  throw Exception('Should never get here');
                },
              ),
            ],
          ),
        ),
      );
}

abstract class SomeBaseBlocState extends Equatable {
  const SomeBaseBlocState();

  @override
  List<Object> get props => [];
}

class InitState extends SomeBaseBlocState {
  const InitState();
}

class SomeOtherState extends SomeBaseBlocState {
  const SomeOtherState();
}

class SomeEvent extends Equatable {
  const SomeEvent();

  @override
  List<Object> get props => [];
}

class SomeBloc extends Bloc<SomeEvent, SomeBaseBlocState> {
  SomeBloc();

  @override
  SomeBaseBlocState get initialState => const InitState();

  @override
  Stream<SomeBaseBlocState> mapEventToState(SomeEvent event) async* {
    if (event is SomeEvent) {
      yield SomeOtherState();
    }
  }
}
```

**pubspec.yaml**
```
name: bug
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: 1.1.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
</details>

3. Run the app and after it loads press the "+" button

**Expected results:** The "Hello world" should be rendered

**Actual results:** The app breaks

<details>
  <summary>Logs</summary>

```
[  +23 ms] executing: [/home/andres/lib/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/home/andres/lib/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +6 ms] executing: [/home/andres/lib/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/andres/lib/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/home/andres/lib/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +84 ms] executing: /home/andres/Android/Sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /home/andres/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +35 ms] /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +51 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +183 ms] Generating /home/andres/dev/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +26 ms] ro.hardware = ranchu
[  +72 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +6 ms] executing: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +22 ms] Exit code 0 from: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           04-19 18:20:29.390 E/GnssHAL_GnssInterface( 1759): gnssSvStatusCb: b: input svInfo.flags is 8
[   +9 ms] executing: /home/andres/Android/Sdk/platform-tools/adb version
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -T 04-19 18:20:29.390
[  +21 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/andres/Android/Sdk/platform-tools/adb
[   +3 ms] executing: /home/andres/Android/Sdk/platform-tools/adb start-server
[  +20 ms] Building APK
Running Gradle task 'assembleDebug'...
[  +21 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /home/andres/dev/bug/android/gradlew.
[  +13 ms] executing: /home/andres/bin/android-studio/jre/bin/java -version
[  +89 ms] Exit code 0 from: /home/andres/bin/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +6 ms] executing: [/home/andres/dev/bug/android/] /home/andres/dev/bug/android/gradlew -q -Ptarget=/home/andres/dev/bug/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+11241 ms] calculateSha: LocalDirectory: '/home/andres/dev/bug/build/app/outputs/apk'/app.apk
[  +54 ms] calculateSha: reading file took 53us
[ +443 ms] calculateSha: computing sha took 443us
[   +3 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +3 ms] executing: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.bug
[ +123 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.bug
[ +257 ms] package:com.example.bug
[   +4 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +51 ms] 5055ca90d6ed89db5598509e4fe74d9f13cf7652
[        ] Installing APK.
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb version
[  +17 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/andres/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb start-server
Installing build/app/outputs/apk/app.apk...
[  +19 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r /home/andres/dev/bug/build/app/outputs/apk/app.apk
[+1094 ms] Performing Streamed Install
           Success
[   +2 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo -n 4f74e697acc785d7b92994e6481fb53ce06f7426 > /data/local/tmp/sky.com.example.bug.sha1
[  +57 ms] Android SDK built for x86 startApp
[   +3 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.bug/com.example.bug.MainActivity
[ +427 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +349 ms] D/FlutterActivity( 4818): Using the launch theme as normal theme.
[   +2 ms] D/FlutterActivityAndFragmentDelegate( 4818): Setting up FlutterEngine.
[        ] D/FlutterActivityAndFragmentDelegate( 4818): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
[ +756 ms] D/FlutterActivityAndFragmentDelegate( 4818): Attaching FlutterEngine to the Activity that owns this Fragment.
[  +27 ms] D/FlutterView( 4818): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@5c7e42c
[  +18 ms] D/FlutterActivityAndFragmentDelegate( 4818): Executing Dart entrypoint: main, and sending initial route: /
[ +277 ms] Observatory URL on device: http://127.0.0.1:44951/8jbidXBZDbs=/
[   +2 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:44951
[  +21 ms] 35431
[        ] Forwarded host port 35431 to device port 44951 for Observatory
[  +12 ms] Connecting to service protocol: http://127.0.0.1:35431/8jbidXBZDbs=/
[ +292 ms] Successfully connected to service protocol: http://127.0.0.1:35431/8jbidXBZDbs=/
[   +2 ms] Sending to VM service: getVM({})
[  +48 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: Android virtual processor, operatingSystem: android, targetCPU: ia32, version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 4818, s...
[   +3 ms] Sending to VM service: getIsolate({isolateId: isolates/4388325196780623})
[   +4 ms] Sending to VM service: _flutter.listViews({})
[  +82 ms] Result: {type: Isolate, id: isolates/4388325196780623, name: main, number: 4388325196780623, _originNumber: 4388325196780623, startTime: 1587331244660, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 2, avgCollectionPeriodMillis...
[  +11 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe8932210, isolate: {type: @Isolate, fixedId: true, id: isolates/4388325196780623, name: main.dart$main-4388325196780623, number: 4388325196780623}}]}
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: bug})
[  +28 ms] Result: {type: FileSystem, name: bug, uri: file:///data/user/0/com.example.bug/code_cache/bugPZHTLW/bug/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugPZHTLW/bug/)
[   +1 ms] Updating assets
Debug service listening on ws://127.0.0.1:35431/8jbidXBZDbs=/ws
Syncing files to device Android SDK built for x86...
[  +93 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[  +10 ms] /home/andres/lib/flutter/bin/cache/dart-sdk/bin/dart /home/andres/lib/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/andres/lib/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.PAVRYI/app.dill --packages /home/andres/dev/bug/.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
[  +15 ms] <- compile package:bug/main.dart
[+6017 ms] Updating files
[ +110 ms] DevFS: Sync finished
[   +1 ms] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +3 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe8932210, isolate: {type: @Isolate, fixedId: true, id: isolates/4388325196780623, name: main.dart$main-4388325196780623, number: 4388325196780623}}]}
[   +2 ms] <- accept
[        ] Connected to _flutterView/0xe8932210.
[ +900 ms] D/EGL_emulation( 4818): eglMakeCurrent: 0xd571a3c0: ver 2 0 (tinfo 0xd210e6e0)
[   +4 ms] D/eglCodecCommon( 4818): setVertexArrayObject: set vao to 0 (0) 1 0
[+2650 ms] Sending to VM service: ext.flutter.platformOverride({isolateId: isolates/4388325196780623})
[   +6 ms] Sending to VM service: ext.flutter.timeDilation({isolateId: isolates/4388325196780623})
[   +2 ms] Sending to VM service: ext.flutter.debugPaint({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.debugPaintBaselinesEnabled({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.repaintRainbow({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.showPerformanceOverlay({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.debugAllowBanner({isolateId: isolates/4388325196780623})
[   +2 ms] Sending to VM service: ext.flutter.inspector.structuredErrors({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.inspector.show({isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.inspector.structuredErrors({enabled: true, isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.inspector.trackRebuildDirtyWidgets({enabled: false, isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.inspector.trackRebuildDirtyWidgets({isolateId: isolates/4388325196780623})
[   +4 ms] Sending to VM service: ext.flutter.inspector.trackRepaintWidgets({enabled: false, isolateId: isolates/4388325196780623})
[        ] Sending to VM service: ext.flutter.inspector.trackRepaintWidgets({isolateId: isolates/4388325196780623})
[   +7 ms] Result: {value: android, type: _extensionType, method: ext.flutter.platformOverride}
[   +9 ms] Result: {timeDilation: 1.0, type: _extensionType, method: ext.flutter.timeDilation}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.debugPaint}
[  +43 ms] Result: {enabled: false, type: _extensionType, method: ext.flutter.debugPaintBaselinesEnabled}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.repaintRainbow}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.showPerformanceOverlay}
[        ] Result: {enabled: true, type: _extensionType, method: ext.flutter.debugAllowBanner}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.structuredErrors}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.show}
[        ] Result: {enabled: true, type: _extensionType, method: ext.flutter.inspector.structuredErrors}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.trackRebuildDirtyWidgets}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.trackRebuildDirtyWidgets}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.trackRepaintWidgets}
[        ] Result: {enabled: false, type: _extensionType, method: ext.flutter.inspector.trackRepaintWidgets}

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1491 pos 12: 'center.parent == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1491:12)
#3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:794:17)
#4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2946:20)
#5      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1543:30)
#6      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1605:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/box.dart': Failed assertion: line 1698 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1698:18)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1704:6)
#4      RenderBox.paintBounds (package:flutter/src/rendering/box.dart:2281:41)
#5      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:134:58)
#6      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing bug...
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/andres/lib/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/andres/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/andres/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.5)
    • Android Studio at /home/andres/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/andres/bin/idea-IU-193.6015.39
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

### LINKED ISSUE #96024: Using StreamBuilder to build sliver widgets inside CustomScrollView causes `'center!.parent == this': is not true.` exception.
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            StreamBuilder<int>(
              stream: Stream.fromIterable([1, 2, 3, 4, 5]),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  return SliverGrid(
                    gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                      maxCrossAxisExtent: 200.0,
                      mainAxisSpacing: 10.0,
                      crossAxisSpacing: 10.0,
                      childAspectRatio: 4.0,
                    ),
                    delegate: SliverChildBuilderDelegate(
                      (BuildContext context, int index) => Container(
                        alignment: Alignment.center,
                        color: Colors.teal[100 * (index % 9)],
                        child: Text('grid item $index'),
                      ),
                      childCount: 20,
                    ),
                  );
                }
                return SliverToBoxAdapter(
                  child: Container(
                    color: Colors.red,
                  ),
                );
              },
            )
          ],
        ),
      ),
    );
  }
}


```

**Expected results:** 
No exception occurred.

**Actual results:** 
Exception caught.

<details>
  <summary>Logs</summary>

```
[  +62 ms] executing: [V:\Env\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +216 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [V:\Env\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +57 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[   +7 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [V:\Env\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +102 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref HEAD
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +63 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +49 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +50 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Multiple devices found:
[  +36 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.57
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[   +8 ms] "flutter run" took 7,242ms.
[  +19 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:292:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:280:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1326:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:463:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1248:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +272 ms] ensureAnalyticsSent: 265ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS V:\01_Work\bug_testing_projects\flutter\streambuilder\bug> flutter run --verbose
[  +68 ms] executing: [V:\Env\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +218 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [V:\Env\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +45 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[   +7 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [V:\Env\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +100 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +55 ms] List of devices attached
           eb916ab1               device product:violet model:Redmi_Note_7_Pro device:violet transport_id:7
[   +6 ms] C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell getprop
[  +74 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +92 ms] Skipping pub get: version match.
[ +102 ms] Generating V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +67 ms] ro.hardware = qcom
[  +32 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[  +11 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\package_config_subset}
[  +31 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] Skipping target: _composite
[   +2 ms] complete
[   +9 ms] Launching lib\main.dart on Redmi Note 7 Pro in debug mode...
[   +4 ms] V:\Env\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev V:\Env\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
V:\Env\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true    
--output-dill C:\Users\Admin\AppData\Local\Temp\flutter_tools.7e93c952\flutter_tool.fbb4be7c\app.dill --packages
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +13 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell -x logcat -v time -t 1
[  +15 ms] <- compile package:bug/main.dart
[ +172 ms] --------- beginning of main
                    01-02 13:42:09.611 I/CNSS    ( 3903): Failed to send nl message
[   +8 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +19 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\android\gradlew.bat.
[  +16 ms] executing: V:\02_Apps\AndroidStudio\jre\bin\java -version
[ +145 ms] Exit code 0 from: V:\02_Apps\AndroidStudio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\android/] V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\lib\main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug        
[+3843 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+16206 ms] File C:\Users\Admin\.android\repositories.cfg could not be loaded.
[+1096 ms] Checking the license for package Android SDK Platform 31 in C:\Users\Admin\AppData\Local\Android\sdk\licenses
[        ] License for package Android SDK Platform 31 accepted.
[        ] Preparing "Install Android SDK Platform 31 (revision: 1)".
[+12695 ms] "Install Android SDK Platform 31 (revision: 1)" ready.
[        ] Installing Android SDK Platform 31 in C:\Users\Admin\AppData\Local\Android\sdk\platforms\android-31
[        ] "Install Android SDK Platform 31 (revision: 1)" complete.
[ +199 ms] "Install Android SDK Platform 31 (revision: 1)" finished.
[+2296 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +61 ms] executing: [V:\Env\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [ +227 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [        ] executing: [V:\Env\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [  +44 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [        ] 2.8.1
[        ] [   +6 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [V:\Env\flutter/] git ls-remote --get-url origin
[        ] [  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +55 ms] executing: [V:\Env\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +81 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +30 ms] Initializing file store
[        ] [  +18 ms] Skipping target: gen_localizations
[        ] [  +12 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\package_config_subset}
[   +1 ms] [  +32 ms] gen_dart_plugin_registrant: Complete
[        ] [   +2 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [   +9 ms] V:\Env\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev V:\Env\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
V:\Env\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\package_config.json
--output-dill V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\flutter_build\16519f09078bcbaa2a104da24f03f74e\app.dill --depfile
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\.dart_tool\flutter_build\16519f09078bcbaa2a104da24f03f74e\kernel_snapshot.d package:bug/main.dart
[+6864 ms] [+7431 ms] kernel_snapshot: Complete
[ +403 ms] [ +391 ms] debug_android_application: Starting due to {}
[ +201 ms] [ +266 ms] debug_android_application: Complete
[ +496 ms] [ +446 ms] Persisting file store
[        ] [   +7 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [  +11 ms] "flutter assemble" took 8,769ms.
[ +200 ms] [ +224 ms] ensureAnalyticsSent: 220ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +308 ms] > Task :app:packLibsflutterBuildDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig
[+3496 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata
[        ] > Task :app:mergeDebugShaders
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +89 ms] > Task :app:mergeDebugAssets
[ +402 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[ +604 ms] > Task :app:createDebugCompatibleScreenManifests
[   +1 ms] > Task :app:extractDeepLinksDebug
[ +291 ms] > Task :app:processDebugMainManifest
[ +294 ms] > Task :app:processDebugManifest
[ +109 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:javaPreCompileDebug
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[ +706 ms] > Task :app:mergeDebugResources
[   +4 ms] > Task :app:compressDebugAssets
[+2078 ms] > Task :app:checkDebugDuplicateClasses
[ +914 ms] > Task :app:mergeDebugJniLibFolders
[ +187 ms] > Task :app:validateSigningDebug
[   +1 ms] > Task :app:processDebugManifestForPackage
[ +403 ms] > Task :app:desugarDebugFileDependencies
[ +308 ms] > Task :app:processDebugResources
[+2587 ms] > Task :app:mergeDebugNativeLibs
[+2511 ms] > Task :app:compileDebugKotlin
[+1393 ms] > Task :app:compileDebugJavaWithJavac
[        ] > Task :app:compileDebugSources
[+1005 ms] > Task :app:dexBuilderDebug
[ +500 ms] > Task :app:mergeDebugJavaResource
[+5697 ms] > Task :app:mergeExtDexDebug
[ +295 ms] > Task :app:stripDebugDebugSymbols
[        ] Unable to strip the following libraries, packaging them as they are: libflutter.so.
[ +602 ms] > Task :app:mergeDexDebug
[+2091 ms] > Task :app:packageDebug
[ +310 ms] > Task :app:assembleDebug
[  +93 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 1m 11s
[        ] 32 actionable tasks: 31 executed, 1 up-to-date
[ +535 ms] Running Gradle task 'assembleDebug'... (completed in 72.5s)
[ +187 ms] calculateSha: LocalDirectory: 'V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\build\app\outputs\flutter-apk'/app.apk
[ +511 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +34 ms] Exit code 0 from: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] Stopping app 'app.apk' on Redmi Note 7 Pro.
[        ] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell am force-stop com.example.bug
[  +60 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell pm list packages com.example.bug
[  +64 ms] Installing APK.
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 install -t -r
V:\01_Work\bug_testing_projects\flutter\streambuilder\bug\build\app\outputs\flutter-apk\app.apk
[+5774 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 5.8s)
[   +2 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell echo -n 540659f09cce532e93e0d61a5181ae470a361b1c >
/data/local/tmp/sky.com.example.bug.sha1
[  +78 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell -x logcat -v time -t 1
[  +97 ms] --------- beginning of main
           01-02 13:43:29.913 D/Zygote  (  623): Forked child process 22215
[   +5 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation
true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[ +139 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1319 ms] Observatory URL on device: http://127.0.0.1:38803/n7i_C9VD5d8=/
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.exe -s eb916ab1 forward tcp:0 tcp:38803
[  +16 ms] 58845
[        ] Forwarded host port 58845 to device port 38803 for Observatory
[   +5 ms] Caching compiled dill
[ +106 ms] Connecting to service protocol: http://127.0.0.1:58845/n7i_C9VD5d8=/
[ +238 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:58845/n7i_C9VD5d8=/.
[ +184 ms] DDS is listening at http://127.0.0.1:58848/95UEGVgLghE=/.
[  +44 ms] Successfully connected to service protocol: http://127.0.0.1:58845/n7i_C9VD5d8=/
[  +79 ms] DevFS: Creating new filesystem on the device (null)
[  +85 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugEPLVIT/bug/)
[   +2 ms] Updating assets
[  +62 ms] Syncing files to device Redmi Note 7 Pro...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:bug/main.dart 2e9c0259-d210-45a9-9f21-f73cafdf6526
[        ] <- 2e9c0259-d210-45a9-9f21-f73cafdf6526
[ +114 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Redmi Note 7 Pro... (completed in 119ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +11 ms] Connected to _flutterView/0x78544be020.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on Redmi Note 7 Pro is available at: http://127.0.0.1:58848/95UEGVgLghE=/
[ +900 ms] 
                    ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown during performLayout():
                    'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1702 pos 12: 'center!.parent
                    == this': is not true.

                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md

                    The relevant error-causing widget was:
                      CustomScrollView
                      CustomScrollView:file:///V:/01_Work/bug_testing_projects/flutter/streambuilder/bug/lib/main.dart:14:15

                    When the exception was thrown, this was the stack:
                    #2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1702:12)
                    #3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:974:17)
                    #4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2999:48)
                    #5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1562:32)
                    #6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1627:19)
                    #8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #11     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #12     new List.of (dart:core-patch/array_patch.dart:51:28)
                    #13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1628:8)
                    #15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1596:23)
                    #16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #17     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1627:19)
                    #18     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #19     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #20     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #21     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #22     new List.of (dart:core-patch/array_patch.dart:51:28)
                    #23     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #24     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1628:8)
                    #25     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1596:23)
                    #26     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #27     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1627:19)
                    #28     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #29     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #30     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #31     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #32     new List.of (dart:core-patch/array_patch.dart:51:28)
                    #33     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #34     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1628:8)
                    #35     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1596:23)
                    #36     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #37     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1627:19)
                    #38     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #39     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #40     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #41     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #42     new List.of (dart:core-patch/array_patch.dart:51:28)
                    #43     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #44     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1628:8)
                    #45     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1596:23)
                    #46     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #47     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1627:19)
                    #48     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #49     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #50     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #51     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #52     new List.of (dart:core-patch/array_patch.dart:51:28)
                    #53     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #54     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1628:8)
                    #55     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1590:25)
                    #56     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1603:6)
                    #57     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1513:18)
                    #58     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:922:44)
                    #59     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1137:14)
                    #60     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1367:18)
                    #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1859:7)
                    #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #69     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
                    #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #73     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
                    #74     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
                    #75     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
                    #76     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
                    #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #81     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
                    #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #100    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3428:13)
                    #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #104    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
                    #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #113    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
                    #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
                    #123    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
                    #124    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
                    #125    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
                    #126    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
                    #127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
                    #128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
                    #129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
                    #130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #131    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
                    (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

                    The following RenderObject was being processed when the exception was fired: RenderPointerListener#83556 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE:
                      creator: Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#b64d8] ←
                        NotificationListener<ScrollMetricsNotification> ← RepaintBoundary ← CustomPaint ← RepaintBoundary
                        ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ← Scrollable ←
                        PrimaryScrollController ← CustomScrollView ← ⋯
                      parentData: <none> (can use size)
                      constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=803.6)
                      size: MISSING
                      behavior: deferToChild
                      listeners: signal
                    This RenderObject had the following descendants (showing up to depth 5):
                        child: RenderSemanticsGestureHandler#b1d90 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                          child: RenderPointerListener#7cc8b relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                            child: RenderSemanticsAnnotations#b3569 relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                              child: RenderIgnorePointer#700bd relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                                child: RenderViewport#52f30 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +25 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderPointerListener#83556 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +11 ms]
           Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#5547d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +22 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#bbc25 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +18 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#c4df1 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +34 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#afcd1 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[  +77 ms] 
           Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#afcd1 relayoutBoundary=up1 NEEDS-PAINT
[  +91 ms] W/Gralloc3(22272): mapper 3.x is not supported
[  +32 ms] The Flutter DevTools debugger and profiler on Redmi Note 7 Pro is available at: http://127.0.0.1:58851?uri=http://127.0.0.1:58848/95UEGVgLghE=/
[ +158 ms] I/com.example.bu(22272): ProcessProfilingInfo new_methods=452 is saved saved_to_disk=1 resolve_classes_delay=8000
```

```
Analyzing bug...                                                        
No issues found! (ran in 3.0s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.1 at V:\Env\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: V:\02_Apps\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at V:\02_Apps\Visual Studio\Visual Studio Community 2019
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at V:\02_Apps\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (4 available)
    • Redmi Note 7 Pro (mobile) • eb916ab1 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)         • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)                • edge     • web-javascript • Microsoft Edge 96.0.1054.57

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #96024 
Fixes #55170
 Fixes #25861

The `RenderViewport` keep a child RO by 'center', it will be updated in [_ViewportElement.mount] or [Update].
But sometimes the child RO will be changed without [_ViewportElement] change when only the subtree of `Viewport` is dirty.
In that case, we should also update the center RO.

Similar to the root cause of [this issue](https://github.com/flutter/flutter/pull/78081), it has a similar solution.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/viewport.dart [hunk 1]
```diff
@@ -219,26 +222,64 @@ class _ViewportElement extends MultiChildRenderObjectElement {
...
+    // Once [mount]/[update] are done, the `renderObject.center` will be updated
+    // in [_updateCenter].
+    if (!_doingMountOrUpdate) {
+      if (slot.index == _centerSlotIndex) {
+        renderObject.center = child as RenderSliver?;
+      }
+    }
+  }
+
+  // `moveRenderObjectChild` only happens during [update] stage.
```
Comment (AlexV525) [inline packages/flutter/lib/src/widgets/viewport.dart:274]: Seems an invalid comment that's indicating the wrong method and didn't start with `///`?

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/viewport.dart:274]: Just comment that why not override `moveRenderObjectChild`

Comment (nt4f04uNd) [reply packages/flutter/lib/src/widgets/viewport.dart:274]: Could it say it? It wasn't immediately clear for me either
For example

```
// We don't override `moveRenderObjectChild` here, because it only happens
// during [update] stage.
```

File: packages/flutter/lib/src/widgets/viewport.dart [hunk 2]
```diff
@@ -219,26 +222,64 @@ class _ViewportElement extends MultiChildRenderObjectElement {
...
   }
 
   void _updateCenter() {
     // TODO(ianh): cache the keys to make this faster
     if (widget.center != null) {
-      renderObject.center = children.singleWhere(
-        (Element element) => element.widget.key == widget.center,
-      ).renderObject as RenderSliver?;
+      for (int i = 0; i < children.length; i++) {
+        if (children.elementAt(i).widget.key == widget.center) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/viewport.dart:247]: elementAt on an Iterable is fairly inefficient as it internally iterates over the collection until it has arrived at the desired index (see implementation at: https://master-api.flutter.dev/flutter/dart-core/Iterable/elementAt.html). We should probably make this a little more efficient here by having the for loop iterate over the children and keeping a separate count variable that we increase with each iteration.

File: packages/flutter/lib/src/widgets/viewport.dart [hunk 3]
```diff
@@ -219,26 +222,64 @@ class _ViewportElement extends MultiChildRenderObjectElement {
...
+    }
+  }
+
+  @override
+  void insertRenderObjectChild(RenderObject child, IndexedSlot<Element?> slot) {
+    super.insertRenderObjectChild(child, slot);
+    // Once [mount]/[update] are done, the `renderObject.center` will be updated
+    // in [_updateCenter].
+    if (!_doingMountOrUpdate) {
+      if (slot.index == _centerSlotIndex) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/viewport.dart:268]: these could be combined in one `if` with `&&`.

File: packages/flutter/lib/src/widgets/viewport.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/viewport.dart:274]: Or: Do override moveRenderObjectChild, which just calls super and has an assert that _doingMountOrUpdate is true to show & proof that the comment is true.

File: packages/flutter/lib/src/widgets/viewport.dart [hunk 4]
```diff
@@ -219,26 +222,64 @@ class _ViewportElement extends MultiChildRenderObjectElement {
...
+    }
+  }
+
+  // `moveRenderObjectChild` only happens during [update] stage.
+
+  @override
+  void removeRenderObjectChild(RenderObject child, Object? slot) {
+    super.removeRenderObjectChild(child, slot);
+    if (!_doingMountOrUpdate) {
+      if (renderObject.center == child) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/viewport.dart:280]: combine these?

File: packages/flutter/lib/src/widgets/viewport.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/viewport.dart]: done

File: packages/flutter/lib/src/widgets/viewport.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/viewport.dart]: done

File: packages/flutter/lib/src/widgets/viewport.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/viewport.dart]: > Or: Do override moveRenderObjectChild, which just calls super and has an assert that _doingMountOrUpdate is true to show & proof that the comment is true.

Done and add a test to test it.

**Review by goderbauer — APPROVED** [review]
LGTM
