### PR TITLE
Fix issue for iOS to build any app and run on simulator #19618

### LINKED ISSUE #19618: Error when launching on iPhone X simulator and physical iPhone.
## Steps to Reproduce

1. $ flutter run -d xxxx  

the same issue with a real device.

the app runs but then the debugging disconnects 

## Logs

```
$ flutter run -d 1090A2E8-ACEE-448E-9B0C-8481E4BCB678  // This is iPhone X Simulator
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.8s
 └─Compiling, linking and signing...                  8.2s
Xcode build done.                                           11.5s
Error waiting for a debug connection: FormatException: Invalid character (at character 25)
http://127.0.0.1:64741/
                        ^

Error launching application on iPhone X.
```

```
[✓] Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.14 wi4hb3, locale en-SA)
    • Flutter version 0.5.8-pre.79 at /Users/xsjh/flutter
    • Framework revision bb338ef2c6 (30 hours ago), 2018-07-19 07:24:06 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/had1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (3 available)
```

### PR DESCRIPTION
**Pull request by matteocrippa**
A different approach to get the url from the string and avoid any interference by extra chars not allowed in url

### CODE REVIEW

**Comment by matteocrippa** [comment]
cc @cbracken @tvolkert look if it's ok for you, it should fix the iOS issue with simulator

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 1]
```diff
@@ -17,8 +17,8 @@ class ProtocolDiscovery {
     this.portForwarder,
     this.hostPort,
     this.ipv6,
-  }) : assert(logReader != null),
-       _prefix = '$serviceName listening on ' {
+  })  : assert(logReader != null),
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: Nit: revert the spacing changes here

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 2]
```diff
@@ -60,10 +61,14 @@ class ProtocolDiscovery {
 
   void _handleLine(String line) {
     Uri uri;
+
+    final RegExp regExp = new RegExp(r'[a-z]+:\/\/[^ \n]*');
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: I don't think you need to escape the slashes, and you should require something after them.  Also, it shouldn't be necessary to use the regexp _and_ the `indexOf()`, so let's combine them.  That would yield a regexp of:

`r'http://[^ \n]+'`

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 3]
```diff
@@ -83,8 +88,10 @@ class ProtocolDiscovery {
 
     if (portForwarder != null) {
       final int actualDevicePort = deviceUri.port;
-      final int actualHostPort = await portForwarder.forward(actualDevicePort, hostPort: hostPort);
-      printTrace('Forwarded host port $actualHostPort to device port $actualDevicePort for $serviceName');
+      final int actualHostPort =
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: Nit: undo these newline changes -- we don't wrap at 80 chars

**Review by tvolkert — COMMENTED** [review]
Thanks for the contribution!

Can you also add a test that shows that the bug has been fixed?

File: packages/flutter_tools/lib/src/protocol_discovery.dart (hunk 2 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/protocol_discovery.dart]: Note that this also means you can nuke the `_prefix` instance variable now too.

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 4]
```diff
@@ -60,10 +59,13 @@ class ProtocolDiscovery {
...
-    final int index = line.indexOf(_prefix + 'http://');
-    if (index >= 0) {
+
+    final RegExp _regexp = new RegExp('${RegExp.escape(serviceName)} (http://[^ \n]+)');
+    final Match _match = _regexp.firstMatch(line);
+
+    if (_match != null) {
       try {
-        uri = Uri.parse(line.substring(index + _prefix.length));
+        uri = Uri.parse(_match[0]);
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: This should be `match[1]` since you want to extract the group that contains the URL

**Comment by matteocrippa** [comment]
@tvolkert it should work fine now

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 5]
```diff
@@ -60,10 +59,14 @@ class ProtocolDiscovery {
 
   void _handleLine(String line) {
     Uri uri;
-    final int index = line.indexOf(_prefix + 'http://');
-    if (index >= 0) {
+
+    final RegExp r =
+        new RegExp('${RegExp.escape(serviceName)} (.*) (http://[^ \n]+)');
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: Why `(.*)` instead of `listening on `?

Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: Nit: no need to wrap - we don't wrap at 80 chars

File: packages/flutter_tools/lib/src/protocol_discovery.dart (hunk 3 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/protocol_discovery.dart]: /bump

File: packages/flutter_tools/lib/src/protocol_discovery.dart (hunk 5 above)
Comment (matteocrippa) [reply packages/flutter_tools/lib/src/protocol_discovery.dart]: I preferred to be more wide in the search, so whatever jumps there (even if in the future something changes), btw we can force to listening on without particular issue

Comment (matteocrippa) [reply packages/flutter_tools/lib/src/protocol_discovery.dart]: Yep, I was switching to VSCode instead of vim, fault of mine

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 6]
```diff
@@ -60,10 +59,13 @@ class ProtocolDiscovery {
...
-    final int index = line.indexOf(_prefix + 'http://');
-    if (index >= 0) {
+
+    final RegExp r = new RegExp('${RegExp.escape(serviceName)} listening on (http://[^ \n]+)');
+    final Match match = r.firstMatch(line);
+
+    if (match != null) {
       try {
-        uri = Uri.parse(line.substring(index + _prefix.length));
+        uri = Uri.parse(match[2]);
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/protocol_discovery.dart]: This needs to be `match[1]` again now 😄

Comment (matteocrippa) [reply packages/flutter_tools/lib/src/protocol_discovery.dart]: argh, that's true, I should stop code in the iPad, fix and commit

**Review by tvolkert — APPROVED** [review]
LGTM. I'll merge on green.

Thanks again!

**Comment by matteocrippa** [comment]
@tvolkert seems windows failed for timeout

**Comment by sidealice** [comment]
I ran flutter upgrade:
8dd06a119..8c02b8f88  master     -> origin/master


Still not work:
Error waiting for a debug connection: FormatException: Invalid character (at character 25)
http://127.0.0.1:50442/

flutter --version:
Framework • revision 66091f9696 (4 weeks ago) • 2018-07-09 12:52:41 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

**Comment by matteocrippa** [comment]
@sidealice try doing

```bash
flutter upgrade
```

**Comment by bqoli** [comment]
@matteocrippa Problem also persists in my case - I am still getting after:

`flutter run`

Error waiting for a debug connection: FormatException: Invalid character (at character 25)
http://127.0.0.1:63443/


Even after:

`flutter upgrade`

Upgrading Flutter from /Applications/flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.8-pre.241 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8c02b8f889 (2 days ago) • 2018-08-04 21:06:56 +0200
Engine • revision 4893b0760d
Tools • Dart 2.0.0-dev.69.5.flutter-8bad5c7b29

**Comment by matteocrippa** [comment]
@bqoli I see it's an issue with the _regex_

let's check here: #20262

**Comment by bqoli** [comment]
@matteocrippa Works perfectly fine now. Thanks a bunch for your efforts!

**Comment by sidealice** [comment]
@matteocrippa after today's upgrade, it fixed! thanks
