### PR TITLE
Fix reselection issue after the text is cleared

### LINKED ISSUE #182927: [AutoComplete] Once an option has been selected (including using Enter), it can no longer be selected again (Regression)
### Steps to reproduce

Enter text into the AutoComplete field.
Select one of the suggested items.
Press Enter to trigger textEditingController.clear().
Select the same item again from the suggestions.
Press Enter.

### Expected results

After selecting an item and clearing the field with textEditingController.clear(), selecting the same item again should still work.

### Actual results

After selecting an item, clearing the field with textEditingController.clear(), and selecting the same item again, it no longer works.

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'testing', home: ErrorAutocomplete());
  }
}

class ErrorAutocomplete extends StatefulWidget {
  const ErrorAutocomplete({super.key});

  @override
  State<ErrorAutocomplete> createState() => _ErrorAutocompleteState();
}

class _ErrorAutocompleteState extends State<ErrorAutocomplete> {
  final textCtrl = TextEditingController();
  final textFocus = FocusNode();
  final listItem = <String>['test', 'abc', 'dexter'];

  @override
  void dispose() {
    textCtrl.dispose();
    textFocus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('testing')),
      body: Row(
        spacing: 10,
        children: [
          Expanded(
            child: Autocomplete(
              textEditingController: textCtrl,
              focusNode: textFocus,
              optionsBuilder: (textEditingValue) {
                return listItem.where(
                  (e) => e.toLowerCase().contains(
                    textEditingValue.text.toLowerCase(),
                  ),
                );
              },
            ),
          ),
          IconButton(
            onPressed: () {
              textCtrl.clear();
            },
            icon: Icon(Icons.add),
          ),
        ],
      ),
    );
  }
}

```

### Screenshots or Video

https://github.com/user-attachments/assets/7181c9b5-3154-4121-bf9a-9472c3093df6

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.41.1, on Ubuntu 24.04.4 LTS 6.17.0-14-generic, locale id_ID.UTF-8) [162ms]
    • Flutter version 3.41.1 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 582a0e7c55 (13 hari yang lalu), 2026-02-12 17:12:32 -0800
    • Engine revision 3452d735bd
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging,
      enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [7,5s]
    • Android SDK at /home/unknown/Android/Sdk
    • Emulator version 35.5.10.0 (build_id 13402964) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [57ms]
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop [2,1s]
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    • OpenGL core renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
    • OpenGL core version: 4.6 (Core Profile) Mesa 25.2.8-0ubuntu0.24.04.1
    • OpenGL core shading language version: 4.60
    • OpenGL ES renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
    • OpenGL ES version: OpenGL ES 3.2 Mesa 25.2.8-0ubuntu0.24.04.1
    • OpenGL ES shading language version: OpenGL ES GLSL ES 3.20
    • GL_EXT_framebuffer_blit: yes
    • GL_EXT_texture_format_BGRA8888: yes

[✓] Connected device (2 available) [519ms]
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.4 LTS 6.17.0-14-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 145.0.7632.109

[✓] Network resources [820ms]
    • All expected network resources are available.

• No issues found!

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes https://github.com/flutter/flutter/issues/182927

This PR is to fix a Autocomplete re-selection issue when an option is cleared up and re-selected again. When `_select()` is called, `_selecting` is set to `true` and the `_textEditingController` is updated which caused `_onChangedField()` be called but returned early. In this case, we should update `_lastFieldText` to the `newSelection`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 1]
```diff
@@ -3829,4 +3829,69 @@ void main() {
...
+    addTearDown(textFocus.dispose);
+    final listItem = <String>['test', 'abc', 'dexter'];
+
+    await tester.pumpWidget(
+      MaterialApp(
+        home: Scaffold(
+          body: Row(
+            children: <Widget>[
+              Expanded(
+                child: Autocomplete<String>(
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart]: Should this be `RawAutocomplete`? `Autocomplete` is the  `Material` version.

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 2]
```diff
@@ -3829,4 +3829,69 @@ void main() {
...
+    WidgetTester tester,
+  ) async {
+    final textCtrl = TextEditingController();
+    addTearDown(textCtrl.dispose);
+    final textFocus = FocusNode();
+    addTearDown(textFocus.dispose);
+    final listItem = <String>['test', 'abc', 'dexter'];
+
+    await tester.pumpWidget(
+      MaterialApp(
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart]: Would be nice if we could test this without Material widgets.

Comment (QuncCccccc) [reply packages/flutter/test/widgets/autocomplete_test.dart]: Thanks for catching this! I moved this unit test to test/material/ and created a similar one for RawAutocomplete in test/widgets/

**Review by victorsanni — APPROVED** [review]
LGTM, the test duplication is a little weird to me but I don't immediately see any cons and it might be useful in case someday Autocomplete no longer depends on RawAutocomplete.
