### PR TITLE
Ignore macOS Cocoapods linting failure on DT_TOOLCHAIN_DIR error

### LINKED ISSUE #132980: `plugin_lint_mac` test fails in CI with Xcode 15
Fails with error:
```
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'App' from project 'App')
```

https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/vashworth_google.com/0938fe37a3a7af101300d33d74f3ca3d09f48fba594a6b49877ada9564fc8dbb/+/build.proto

This issue was fixed for normal Flutter user flow in https://github.com/flutter/flutter/pull/132803.

The fix doesn't apply to this test, though, because we're using `pod lib lint`, which doesn't use the Flutter tooling.

### PR DESCRIPTION
**Pull request by vashworth**
Xcode 15 introduced an [error](https://github.com/flutter/flutter/issues/132755) into Cocoapods when building macOS apps. 

When `pod lib lint` runs, it under the covers is building the app with `xcodebuild`, which is why this error occurs when linting.

A fix has been made in Cocoapods, but is not in an official release so we can't upgrade Cocoapods yet. This is to temporarily ignore lint failure due to that error.

Fixes https://github.com/flutter/flutter/issues/132980.

Tracking issue to upgrade Cocoapods when fix is in a release: https://github.com/flutter/flutter/issues/133584

Since Xcode 15 isn't in CI, I tested it in a one-off led test:
* [Pre-fix failure](https://chromium-swarm.appspot.com/task?id=6431f228ecf98e10)
* [Post-fix success](https://chromium-swarm.appspot.com/task?id=645ba7ebdab97210)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by cbracken** [comment]
Related https://github.com/flutter/flutter/issues/131527.

File: dev/devicelab/bin/tasks/plugin_lint_mac.dart [hunk 1]
```diff
@@ -533,3 +533,22 @@ void _validateMacOSPodfile(String appPath) {
...
+      executable,
+      arguments,
+      stdout: lintStdout,
+    );
+  } on BuildFailedError {
+    // Temporarily ignore errors due to DT_TOOLCHAIN_DIR. This error was
+    // introduced with Xcode 15. Fix was made in Cocoapods, but is not in an
+    // official release yet.
+    // TODO(vashworth): Stop ignoring when https://github.com/flutter/flutter/issues/133584 is complete.
+    if (!lintStdout.toString().contains('error: DT_TOOLCHAIN_DIR cannot be used to evaluate')) {
```
Comment (stuartmorgan) [inline dev/devicelab/bin/tasks/plugin_lint_mac.dart:550]: Isn't this going to ignore *all* failures with Xcode 15, because every failure will contain this as one of the lines, regardless of any other failures?

Comment (vashworth) [reply dev/devicelab/bin/tasks/plugin_lint_mac.dart:550]: Pretty much. Basically `pod lib lint` won't work for macOS until the Cocoapods fix is in an official release and we update our CI to use it. 

We could alternatively check for the Xcode version first and skip linting if it's Xcode 15+.

Comment (vashworth) [reply dev/devicelab/bin/tasks/plugin_lint_mac.dart]: Just made a slight improvement so if there's more errors than just the `DT_TOOLCHAIN_DIR` error, it'll still throw it

File: dev/devicelab/lib/framework/utils.dart [hunk 2]
```diff
@@ -430,11 +430,12 @@ Future<String> eval(
   Map<String, String>? environment,
   bool canFail = false, // as in, whether failures are ok. False means that they are fatal.
   String? workingDirectory,
+  StringBuffer? stdout,
```
Comment (stuartmorgan) [inline dev/devicelab/lib/framework/utils.dart:433]: Why do we need this change instead of using the return value?

**Review by stuartmorgan-g — COMMENTED** [review]
Thanks, the more targeted version seems like a much safer workaround.

File: dev/devicelab/lib/framework/utils.dart (hunk 2 above)
Comment (vashworth) [reply dev/devicelab/lib/framework/utils.dart:433]: Because it throws an error on the `_execute` command and therefore never hits line 450 where it returns

Comment (stuartmorgan) [reply dev/devicelab/lib/framework/utils.dart:433]: Ah, I see. Let's put the same comment here as from the line below, for consistency. (Unfortunate that this error output gets logged to stdout rather than stderr.)

File: dev/devicelab/bin/tasks/plugin_lint_mac.dart [hunk 3]
```diff
@@ -533,3 +533,24 @@ void _validateMacOSPodfile(String appPath) {
     'macos',
   ));
 }
+
+Future<void> _tryMacOSLint(String executable, List<String> arguments) async {
```
Comment (stuartmorgan) [inline dev/devicelab/bin/tasks/plugin_lint_mac.dart:537]: We should move the executable and the first few arguments into this method, and make `arguments` into `podspecPath` + `extraArguments`. Right now, despite the name it can actually run any command, but then it's looking for `pod lint`-specific output.

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]

File: dev/devicelab/bin/tasks/plugin_lint_mac.dart (hunk 3 above)
Comment (vashworth) [reply dev/devicelab/bin/tasks/plugin_lint_mac.dart]: Good idea. Done!

**Review by stuartmorgan-g — APPROVED** [review]
LGTM!
