### PR TITLE
[flutter_tools] fix recursive asset variant issue

### LINKED ISSUE #45075: Wrong platform assets being copied to flutter_assets, macOS assets showing up in iOS flutter_assets
## Steps to Reproduce

1. Setup macos support in an existing project with Android and iOS support. `flutter config --enable-macos-desktop` and then `flutter create --macos .` (or whatever you need to do)
2. Build the release version of the Mac part `flutter build macos`
3. Build the release version of the iOS part `flutter build ios`

Maybe try a few more times in that order if everything works fine the first time. 

**Target Platform: Mac and iOS**
**Target OS version/browser: Mac OS 10.15.1 and iOS 13**

## Logs

```
 === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    2019-11-17 15:05:59.049 defaults[4938:4863527]
    The domain/default pair of
    (/Users/afzal/Dev/projects/Flutter/mailgun_routes/build/ios/Release-iphoneos/Ma
    ilgun
    Routes.app/Frameworks/App.framework/flutter_assets/macos/Flutter/ephemeral/App.
    framework/Info.plist, CFBundleExecutable) does not exist
    fatal error: lipo: can't map input file:
    /Users/afzal/Dev/projects/Flutter/mailgun_routes/build/ios/Release-iphoneos/Mai
    lgun
    Routes.app/Frameworks/App.framework/flutter_assets/macos/Flutter/ephemeral/App.
    framework/ (Invalid argument)
    fatal error: lipo: can't map input file:
    /Users/afzal/Dev/projects/Flutter/mailgun_routes/build/ios/Release-iphoneos/Mai
    lgun
    Routes.app/Frameworks/App.framework/flutter_assets/macos/Flutter/ephemeral/App.
    framework/ (Invalid argument)
    Failed to extract armv7 for
    /Users/afzal/Dev/projects/Flutter/mailgun_routes/build/ios/Release-iphoneos/Mai
    lgun
    Routes.app/Frameworks/App.framework/flutter_assets/macos/Flutter/ephemeral/App.
    framework/. Running lipo -info:
    fatal error: lipo: can't map input file:
    /Users/afzal/Dev/projects/Flutter/mailgun_routes/build/ios/Release-iphoneos/Mai
    lgun
    Routes.app/Frameworks/App.framework/flutter_assets/macos/Flutter/ephemeral/App.
    framework/ (Invalid argument)
```

For some reason, the **macos** folder gets created in `ios/Flutter/App.Framework/flutter_assets` when building the iOS version after the Mac version.

This also continues happening if you add the web part to this project. The `build/web/assets` folder will contain `ios` and `macos` folders with `Flutter/App.Framework` inside them (and flutter_assets) inside those. I think something in the build cache might be causing this.

Note: I am importing a json asset in pubspec.yaml called "secrets.json"
This is the project:
https://github.com/AfzalivE/mailgun_routes

## Workaround

https://github.com/flutter/flutter/issues/45075#issuecomment-554811637

### LINKED ISSUE #57210: iOS build error: The domain/default pair of (/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not exist
Since updating to flutter 1.19.0-1.0.pre I'am seeing problems with iOS build. Every time I initiate a new build, I have to do `flutter -clean`  to make the the build is successful. Tried on real device and simulator.

**Expected results:** A successful build without running `flutter -clean` every time

**Actual results:** 

```
Running Xcode build...
Xcode build done.                                           36,7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    warning: RUN SCRIPT in ACTION
    Development Google plist copied
    building file list ... done
    deleting App.framework/_CodeSignature/CodeResources
    deleting App.framework/_CodeSignature/
    App.framework/
    App.framework/App

    sent 51354 bytes  received 48 bytes  102804.00 bytes/sec
    total size is 43216302  speedup is 840.75
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 97999321 bytes  received 120 bytes  195998882.00 bytes/sec
    total size is 97986963  speedup is 1.00
    /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
    /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
    /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
    2020-05-14 15:09:10.893 defaults[45444:9847515] 
    The domain/default pair of (/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not exist
    fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    Failed to extract arm64 for /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
    fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on iPhone 7.
```

<details>
  <summary>Logs</summary>

```
```

```
```

[  +19 ms] executing: [/Users/***myUserName***/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 456d80b9ddd74b4b5ca3b77bbfb70ab0e05d3fa8
[        ] executing: [/Users/***myUserName***/Development/flutter/] git tag --contains HEAD
[ +402 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.19.0-1.0.pre
[  +11 ms] executing: [/Users/***myUserName***/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/***myUserName***/Development/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [/Users/***myUserName***/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +6 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] executing: /Users/***myUserName***/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] executing: /usr/bin/xcode-select --print-path
[   +9 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[+1022 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.4.1
           Build version 11E503a
[   +2 ms] executing: xcrun --find xcdevice
[   +9 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +95 ms] List of devices attached
[ +140 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.iOS-13-2" : [
                 ... shortened due to the limitation of the length of github comments ...
                 }
               ]
             }
           }
[+3916 ms] [
             ... shortened due to the limitation of the length of github comments ...
             }
           ]
[  +11 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Found plugin app_review at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/app_review-1.1.0+1/
[   +5 ms] Found plugin apple_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/
[  +17 ms] Found plugin cloud_firestore at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/
[   +6 ms] Found plugin cloud_firestore_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +7 ms] Found plugin device_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+4/
[  +11 ms] Found plugin firebase_analytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.11/
[   +2 ms] Found plugin firebase_auth at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.16.0/
[   +3 ms] Found plugin firebase_auth_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +1 ms] Found plugin firebase_core at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/
[   +3 ms] Found plugin firebase_core_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +2 ms] Found plugin firebase_crashlytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.1.3+3/
[   +1 ms] Found plugin firebase_dynamic_links at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.0+11/
[   +1 ms] Found plugin firebase_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.5/
[   +6 ms] Found plugin flutter_email_sender at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-3.0.1/
[   +2 ms] Found plugin flutter_facebook_login at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[   +6 ms] Found plugin flutter_secure_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.3/
[   +8 ms] Found plugin google_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.4.6/
[   +4 ms] Found plugin google_sign_in_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1/
[  +21 ms] Found plugin package_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+18/
[   +6 ms] Found plugin path_provider at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.8/
[   +1 ms] Found plugin path_provider_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+1/
[  +19 ms] Found plugin shared_preferences at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +2 ms] Found plugin shared_preferences_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+7/
[   +2 ms] Found plugin shared_preferences_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+4/
[   +4 ms] Found plugin sqflite at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.0+1/
[  +12 ms] Found plugin url_launcher at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.7/
[   +1 ms] Found plugin url_launcher_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+5/
[   +2 ms] Found plugin url_launcher_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+2/
[  +53 ms] Found plugin app_review at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/app_review-1.1.0+1/
[        ] Found plugin apple_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/
[   +9 ms] Found plugin cloud_firestore at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/
[   +1 ms] Found plugin cloud_firestore_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +4 ms] Found plugin device_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+4/
[   +6 ms] Found plugin firebase_analytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.11/
[   +2 ms] Found plugin firebase_auth at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.16.0/
[   +2 ms] Found plugin firebase_auth_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +1 ms] Found plugin firebase_core at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/
[   +2 ms] Found plugin firebase_core_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +1 ms] Found plugin firebase_crashlytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.1.3+3/
[   +1 ms] Found plugin firebase_dynamic_links at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.0+11/
[   +2 ms] Found plugin firebase_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.5/
[   +4 ms] Found plugin flutter_email_sender at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-3.0.1/
[   +1 ms] Found plugin flutter_facebook_login at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[   +2 ms] Found plugin flutter_secure_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.3/
[   +4 ms] Found plugin google_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.4.6/
[   +1 ms] Found plugin google_sign_in_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1/
[  +12 ms] Found plugin package_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+18/
[   +2 ms] Found plugin path_provider at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.8/
[   +1 ms] Found plugin path_provider_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+1/
[   +8 ms] Found plugin shared_preferences at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[        ] Found plugin shared_preferences_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+7/
[   +1 ms] Found plugin shared_preferences_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+4/
[   +2 ms] Found plugin sqflite at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.0+1/
[   +4 ms] Found plugin url_launcher at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.7/
[   +1 ms] Found plugin url_launcher_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+5/
[   +1 ms] Found plugin url_launcher_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+2/
[  +96 ms] Generating /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +206 ms] Launching lib/main.dart on iPhone 7 in debug mode...
[   +9 ms] /Users/***myUserName***/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/***myUserName***/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/***myUserName***/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/0h/5z5qty5x5hbgjmcbzg0yn0nr0000gn/T/flutter_tool.eD6FGO/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill build/cache.dill.track.dill
[   +8 ms] executing: /usr/bin/plutil -convert json -o - /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
[  +10 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
[        ] {"CFBundleName":"$(APP_NAME)","UILaunchStoryboardName":"LaunchScreen","LSApplicationQueriesSchemes":["fbapi","fbapi20130214","fbapi20130410","fbapi20130702","fbapi20131010","fbapi20131219","fbapi20140410","fbapi20140116","fbapi20150313","fbapi20150629","fbapi20160328","fbauth","fbauth2","fbshareextension"],"CFBundleDevelopmentRegion":"$(DEVELOPMENT_LANGUAGE)","CFBundleVersion":"$(FLUTTER_BUILD_NUMBER)","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)","FacebookAppID":"$(FB_APP_ID)","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"$(EXECUTABLE_NAME)","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"FacebookDisplayName":"$(FB_APP_DN)","UIViewControllerBasedStatusBarAppearance":false,"CFBundleIdentifier":"$(APP_BUNDLE_ID)","CFBundleURLTypes":[{"CFBundleURLSchemes":["$(FB_URL_SHM)"]},{"CFBundleTypeRole":"Editor","CFBundleURLSchemes":["$(FIR_URL_SHM)"]}],"CFBundleSignature":"????","Flavor":"${PRODUCT_FLAVOR}","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait"]}
[   +4 ms] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj -target Runner -showBuildSettings
[        ] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj -target Runner -showBuildSettings
[  +12 ms] <- compile package:myProjectName/main.dart
[+4554 ms] Command line invocation:
               /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj -target Runner -showBuildSettings

           Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = ***myUserName***
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               APPLY_RULES_IN_COPY_HEADERS = NO
               ARCHS = arm64
               ARCHS_STANDARD = arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               BUILD_LIBRARY_FOR_DISTRIBUTION = NO
               BUILD_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos
               BUNDLE_CONTENTS_FOLDER_PATH_deep = Contents/
               BUNDLE_EXECUTABLE_FOLDER_NAME_deep = MacOS
               BUNDLE_FORMAT = shallow
               BUNDLE_FRAMEWORKS_FOLDER_PATH = Frameworks
               BUNDLE_PLUGINS_FOLDER_PATH = PlugIns
               BUNDLE_PRIVATE_HEADERS_FOLDER_PATH = PrivateHeaders
               BUNDLE_PUBLIC_HEADERS_FOLDER_PATH = Headers
               CACHE_ROOT = /var/folders/0h/5z5qty5x5hbgjmcbzg0yn0nr0000gn/C/com.apple.DeveloperTools/11.4.1-11E503a/Xcode
               CCHROOT = /var/folders/0h/5z5qty5x5hbgjmcbzg0yn0nr0000gn/C/com.apple.DeveloperTools/11.4.1-11E503a/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Release
               CONFIGURATION_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.4
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 10802
               CURRENT_VARIANT = normal
               DART_OBFUSCATION = false
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2 13.3 13.4
               DERIVED_FILES_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DEVELOPMENT_TEAM = 8AGG8C9QNR
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DONT_GENERATE_INFOPLIST_FILE = NO
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HARDENED_RUNTIME = NO
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_NS_ASSERTIONS = NO
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = NO
               ENABLE_TESTING_SEARCH_PATHS = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_DESTINATION = Signature
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.2.0
               FLUTTER_BUILD_NUMBER = 112002
               FLUTTER_FRAMEWORK_DIR = /Users/***myUserName***/Development/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/***myUserName***/Development/flutter
               FLUTTER_TARGET = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/AppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/BoringSSL-GRPC" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FBSDKCoreKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FBSDKLoginKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FMDB" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseCore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseCoreDiagnostics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseDynamicLinks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseFirestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseInstanceID" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseStorage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GTMAppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GTMSessionFetcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleDataTransport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleDataTransportCCTSupport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleUtilities" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/abseil" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/app_review" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/apple_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/cloud_firestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/device_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_analytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_auth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_crashlytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_dynamic_links" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_email_sender" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_facebook_login" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_secure_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/gRPC-C++" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/gRPC-Core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/google_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/leveldb-library" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/nanopb" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/package_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/path_provider" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/shared_preferences" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/sqflite" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/url_launcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/../Flutter" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Crashlytics/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Fabric/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/FirebaseAnalytics/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleAppMeasurement/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleSignIn/Frameworks" /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS =  COCOAPODS=1  FBSDKCOCOAPODS=1  PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1
               GCC_SYMBOLS_PRIVATE_EXTERN = YES
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HEADER_SEARCH_PATHS =  "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/AppAuth/AppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/BoringSSL-GRPC/openssl_grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FMDB/FMDB.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseAuth/FirebaseAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseCore/FirebaseCore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseDynamicLinks/FirebaseDynamicLinks.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseFirestore/FirebaseFirestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseInstanceID/FirebaseInstanceID.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/FirebaseStorage/FirebaseStorage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GTMAppAuth/GTMAppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/abseil/absl.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/app_review/app_review.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/apple_sign_in/apple_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/cloud_firestore/cloud_firestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/device_info/device_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_analytics/firebase_analytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_auth/firebase_auth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_core/firebase_core.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_crashlytics/firebase_crashlytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_dynamic_links/firebase_dynamic_links.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/firebase_storage/firebase_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_email_sender/flutter_email_sender.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_facebook_login/flutter_facebook_login.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/flutter_secure_storage/flutter_secure_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/gRPC-C++/grpcpp.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/gRPC-Core/grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/google_sign_in/google_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/leveldb-library/leveldb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/nanopb/nanopb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/package_info/package_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/path_provider/path_provider.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/shared_preferences/shared_preferences.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/sqflite/sqflite.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/url_launcher/url_launcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/Firebase" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAnalyticsInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAuthInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop"  /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Firebase/CoreOnly/Sources
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/***myUserName***
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = ***myUserName***
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 12.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_OS_VERSION = ios12.0
               LLVM_TARGET_TRIPLE_VENDOR = apple
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
               LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 19E287
               MAC_OS_X_VERSION_ACTUAL = 101504
               MAC_OS_X_VERSION_MAJOR = 101500
               MAC_OS_X_VERSION_MINOR = 1504
               MARKETING_VERSION = 1.0.0
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/Runner.app
               MODULES_FOLDER_PATH = Runner.app/Modules
               MODULE_CACHE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = NO
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               ONLY_ACTIVE_ARCH = NO
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -framework Flutter
               OTHER_SWIFT_FLAGS =  -D COCOAPODS
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/opt/openssl/bin:/Users/***myUserName***/Development/flutter/bin:/Users/***myUserName***/anaconda3/bin:/Users/***myUserName***/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 17E8258
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PODS_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               PODS_CONFIGURATION_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos
               PODS_PODFILE_DIR_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/.
               PODS_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.arconia.myProjectName
               PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/DerivedSources
               PROJECT_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               PROJECT_FILE_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build
               PROJECT_TEMP_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_DIR_iphoneos13_4 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_NAME = iphoneos13.4
               SDK_NAMES = iphoneos13.4
               SDK_PRODUCT_BUILD_VERSION = 17E8258
               SDK_VERSION = 13.4
               SDK_VERSION_ACTUAL = 130400
               SDK_VERSION_MAJOR = 130000
               SDK_VERSION_MINOR = 400
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/SharedPrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               SRCROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphoneos
               SUPPORTS_MACCATALYST = NO
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_COMPILATION_MODE = wholemodule
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -O
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_VERSION = 5.0
               SYMROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Release-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               TEST_FRAMEWORK_SEARCH_PATHS =  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks
               TEST_LIBRARY_SEARCH_PATHS =  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TRACK_WIDGET_CREATION = true
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               TREE_SHAKE_ICONS = false
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = ***myUserName***
               USER_APPS_DIR = /Users/***myUserName***/Applications
               USER_LIBRARY_DIR = /Users/***myUserName***/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               USE_LLVM_TARGET_TRIPLES = YES
               USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
               USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
               USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
               USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES
               VALIDATE_PRODUCT = YES
               VALIDATE_WORKSPACE = NO
               VALID_ARCHS = arm64 arm64e armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = ***myUserName***
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-10802"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 11E503a
               XCODE_VERSION_ACTUAL = 1141
               XCODE_VERSION_MAJOR = 1100
               XCODE_VERSION_MINOR = 1140
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal

           2020-05-14 14:59:50.713 xcodebuild[44154:9831003]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
           2020-05-14 14:59:50.813 xcodebuild[44154:9831009]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
[  +15 ms] Building Runner.app for 846c7068c4b73e49341722e3abcb3cecdf4998c1
[  +29 ms] Xcode workspace settings not found, skipping build system migration
[  +50 ms] executing: xattr -r -d com.apple.FinderInfo /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
[ +967 ms] Failed to remove xattr com.apple.FinderInfo from /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
[   +1 ms] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/] /usr/bin/xcodebuild -list
[+1779 ms] Command line invocation:
               /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

           Information about project "Runner":
               Targets:
                   Runner

               Build Configurations:
                   Debug
                   Debug-dev
                   Debug-prod
                   Debug-stag
                   Release
                   Release-dev
                   Release-prod
                   Release-stag
                   Profile

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   dev
                   prod
                   Runner
                   stag

           2020-05-14 14:59:54.115 xcodebuild[44176:9831291]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
           2020-05-14 14:59:54.212 xcodebuild[44176:9831286]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
[  +15 ms] Automatically signing iOS for device deployment using specified development team in Xcode project: 8AGG8C9QNR
[  +30 ms] Found plugin app_review at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/app_review-1.1.0+1/
[   +1 ms] Found plugin apple_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/
[   +4 ms] Found plugin cloud_firestore at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/
[   +3 ms] Found plugin cloud_firestore_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +2 ms] Found plugin device_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+4/
[   +2 ms] Found plugin firebase_analytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.11/
[        ] Found plugin firebase_auth at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.16.0/
[   +1 ms] Found plugin firebase_auth_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/
[   +1 ms] Found plugin firebase_core_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_crashlytics at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.1.3+3/
[        ] Found plugin firebase_dynamic_links at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.0+11/
[        ] Found plugin firebase_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.5/
[   +2 ms] Found plugin flutter_email_sender at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-3.0.1/
[        ] Found plugin flutter_facebook_login at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[   +3 ms] Found plugin flutter_secure_storage at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.3/
[   +3 ms] Found plugin google_sign_in at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.4.6/
[   +1 ms] Found plugin google_sign_in_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1/
[   +6 ms] Found plugin package_info at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+18/
[   +1 ms] Found plugin path_provider at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.8/
[        ] Found plugin path_provider_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+1/
[   +4 ms] Found plugin shared_preferences at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +1 ms] Found plugin shared_preferences_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+7/
[   +1 ms] Found plugin shared_preferences_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+4/
[   +1 ms] Found plugin sqflite at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.0+1/
[   +4 ms] Found plugin url_launcher at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.7/
[        ] Found plugin url_launcher_macos at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+5/
[        ] Found plugin url_launcher_web at /Users/***myUserName***/Development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+2/
[  +38 ms] executing: /usr/bin/plutil -convert json -o - /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
[        ] {"CFBundleName":"$(APP_NAME)","UILaunchStoryboardName":"LaunchScreen","LSApplicationQueriesSchemes":["fbapi","fbapi20130214","fbapi20130410","fbapi20130702","fbapi20131010","fbapi20131219","fbapi20140410","fbapi20140116","fbapi20150313","fbapi20150629","fbapi20160328","fbauth","fbauth2","fbshareextension"],"CFBundleDevelopmentRegion":"$(DEVELOPMENT_LANGUAGE)","CFBundleVersion":"$(FLUTTER_BUILD_NUMBER)","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)","FacebookAppID":"$(FB_APP_ID)","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"$(EXECUTABLE_NAME)","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"FacebookDisplayName":"$(FB_APP_DN)","UIViewControllerBasedStatusBarAppearance":false,"CFBundleIdentifier":"$(APP_BUNDLE_ID)","CFBundleURLTypes":[{"CFBundleURLSchemes":["$(FB_URL_SHM)"]},{"CFBundleTypeRole":"Editor","CFBundleURLSchemes":["$(FIR_URL_SHM)"]}],"CFBundleSignature":"????","Flavor":"${PRODUCT_FLAVOR}","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait"]}
Running Xcode build...
[   +2 ms] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug-dev -quiet -workspace Runner.xcworkspace -scheme dev BUILD_DIR=/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO
[+31604 ms] warning: RUN SCRIPT in ACTION
            Development Google plist copied
            building file list ... done
            deleting App.framework/_CodeSignature/CodeResources
            deleting App.framework/_CodeSignature/
            App.framework/
            App.framework/App

            sent 51354 bytes  received 48 bytes  102804.00 bytes/sec
            total size is 43216302  speedup is 840.75
            building file list ... done
            Flutter.framework/
            Flutter.framework/Flutter
            Flutter.framework/Info.plist
            Flutter.framework/icudtl.dat
            Flutter.framework/_CodeSignature/
            Flutter.framework/_CodeSignature/CodeResources

            sent 97999333 bytes  received 120 bytes  65332968.67 bytes/sec
            total size is 97986963  speedup is 1.00
            /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
            /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
            /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
            2020-05-14 15:00:26.131 defaults[44403:9832953] 
            The domain/default pair of (/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not exist
            fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
            fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
            Failed to extract arm64 for /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
            fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
            Command PhaseScriptExecution failed with a nonzero exit code
            note: Using new build system
            note: Building targets in parallel
            note: Planning build
            note: Constructing build description

            ** BUILD FAILED **
[  +14 ms] Xcode build done.                                           31,6s
[   +1 ms] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug-dev -quiet -workspace Runner.xcworkspace -scheme dev BUILD_DIR=/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[        ] executing: [/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug-dev -quiet -workspace Runner.xcworkspace -scheme dev BUILD_DIR=/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[+5469 ms] Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = ***myUserName***
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               APPLY_RULES_IN_COPY_HEADERS = NO
               APP_BUNDLE_ID = com.arconia.myProjectName.dev
               APP_ENV = dev
               APP_NAME = MyProjectName & Implikationen Development
               ARCHS = arm64
               ARCHS_STANDARD = arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               BUILD_LIBRARY_FOR_DISTRIBUTION = NO
               BUILD_ROOT = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Products
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos
               BUNDLE_CONTENTS_FOLDER_PATH_deep = Contents/
               BUNDLE_EXECUTABLE_FOLDER_NAME_deep = MacOS
               BUNDLE_FORMAT = shallow
               BUNDLE_FRAMEWORKS_FOLDER_PATH = Frameworks
               BUNDLE_PLUGINS_FOLDER_PATH = PlugIns
               BUNDLE_PRIVATE_HEADERS_FOLDER_PATH = PrivateHeaders
               BUNDLE_PUBLIC_HEADERS_FOLDER_PATH = Headers
               CACHE_ROOT = /var/folders/0h/5z5qty5x5hbgjmcbzg0yn0nr0000gn/C/com.apple.DeveloperTools/11.4.1-11E503a/Xcode
               CCHROOT = /var/folders/0h/5z5qty5x5hbgjmcbzg0yn0nr0000gn/C/com.apple.DeveloperTools/11.4.1-11E503a/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = NO
               COMPOSITE_SDK_DIRS = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Debug-dev
               CONFIGURATION_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.4
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 10802
               CURRENT_VARIANT = normal
               DART_OBFUSCATION = false
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2 13.3 13.4
               DERIVED_FILES_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DEVELOPMENT_TEAM = 8AGG8C9QNR
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DONT_GENERATE_INFOPLIST_FILE = NO
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HARDENED_RUNTIME = NO
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = YES
               ENABLE_TESTING_SEARCH_PATHS = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_DESTINATION = Signature
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FB_APP_DN = MyProjectName Dev
               FB_APP_ID = 1451299728383842
               FB_URL_SHM = fb1451299728383842
               FILE_LIST = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Objects/LinkFileList
               FIR_URL_SHM = com.googleusercontent.apps.51403281107-h9pbrof046b0379dr7lg25k4p0fta3vp
               FIXED_FILES_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.2.0
               FLUTTER_BUILD_NUMBER = 112002
               FLUTTER_FRAMEWORK_DIR = /Users/***myUserName***/Development/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/***myUserName***/Development/flutter
               FLUTTER_SUPPRESS_ANALYTICS = true
               FLUTTER_TARGET = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/AppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/BoringSSL-GRPC" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKCoreKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKLoginKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FMDB" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCoreDiagnostics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseDynamicLinks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseFirestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseInstanceID" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseStorage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMAppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMSessionFetcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransportCCTSupport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleUtilities" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/abseil" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/app_review" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/apple_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/cloud_firestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/device_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_analytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_auth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_crashlytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_dynamic_links" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_email_sender" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_facebook_login" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_secure_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-C++" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-Core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/google_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/leveldb-library" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/nanopb" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/package_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/path_provider" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/shared_preferences" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/sqflite" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/url_launcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/../Flutter" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Crashlytics/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Fabric/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/FirebaseAnalytics/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleAppMeasurement/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleSignIn/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/AppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/BoringSSL-GRPC" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKCoreKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKLoginKit" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FMDB" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCoreDiagnostics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseDynamicLinks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseFirestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseInstanceID" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseStorage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMAppAuth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMSessionFetcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransportCCTSupport" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleUtilities" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/abseil" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/app_review" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/apple_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/cloud_firestore" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/device_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_analytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_auth" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_crashlytics" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_dynamic_links" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_email_sender" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_facebook_login" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_secure_storage" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-C++" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-Core" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/google_sign_in" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/leveldb-library" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/nanopb" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/package_info" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/path_provider" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/shared_preferences" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/sqflite" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/url_launcher" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/../Flutter" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Crashlytics/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Fabric/iOS" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/FirebaseAnalytics/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleAppMeasurement/Frameworks" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/GoogleSignIn/Frameworks" /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_DYNAMIC_NO_PIC = NO
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_OPTIMIZATION_LEVEL = 0
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1  COCOAPODS=1  FBSDKCOCOAPODS=1  PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1 COCOAPODS=1 DEBUG=1  COCOAPODS=1  FBSDKCOCOAPODS=1  PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1 FBSDKCOCOAPODS=1 DEBUG=1  COCOAPODS=1  FBSDKCOCOAPODS=1  PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1 PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1
               GCC_SYMBOLS_PRIVATE_EXTERN = NO
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HEADER_SEARCH_PATHS =  "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/AppAuth/AppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/BoringSSL-GRPC/openssl_grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FMDB/FMDB.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseAuth/FirebaseAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCore/FirebaseCore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseDynamicLinks/FirebaseDynamicLinks.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseFirestore/FirebaseFirestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseInstanceID/FirebaseInstanceID.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseStorage/FirebaseStorage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMAppAuth/GTMAppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/abseil/absl.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/app_review/app_review.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/apple_sign_in/apple_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/cloud_firestore/cloud_firestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/device_info/device_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_analytics/firebase_analytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_auth/firebase_auth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_core/firebase_core.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_crashlytics/firebase_crashlytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_dynamic_links/firebase_dynamic_links.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_storage/firebase_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_email_sender/flutter_email_sender.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_facebook_login/flutter_facebook_login.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_secure_storage/flutter_secure_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-C++/grpcpp.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-Core/grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/google_sign_in/google_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/leveldb-library/leveldb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/nanopb/nanopb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/package_info/package_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/path_provider/path_provider.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/shared_preferences/shared_preferences.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/sqflite/sqflite.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/url_launcher/url_launcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/Firebase" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAnalyticsInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAuthInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop"  /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Firebase/CoreOnly/Sources "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/AppAuth/AppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/BoringSSL-GRPC/openssl_grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FMDB/FMDB.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseAuth/FirebaseAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCore/FirebaseCore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseDynamicLinks/FirebaseDynamicLinks.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseFirestore/FirebaseFirestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseInstanceID/FirebaseInstanceID.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseStorage/FirebaseStorage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMAppAuth/GTMAppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/abseil/absl.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/app_review/app_review.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/apple_sign_in/apple_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/cloud_firestore/cloud_firestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/device_info/device_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_analytics/firebase_analytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_auth/firebase_auth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_core/firebase_core.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_crashlytics/firebase_crashlytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_dynamic_links/firebase_dynamic_links.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_storage/firebase_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_email_sender/flutter_email_sender.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_facebook_login/flutter_facebook_login.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_secure_storage/flutter_secure_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-C++/grpcpp.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-Core/grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/google_sign_in/google_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/leveldb-library/leveldb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/nanopb/nanopb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/package_info/package_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/path_provider/path_provider.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/shared_preferences/shared_preferences.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/sqflite/sqflite.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/url_launcher/url_launcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/Firebase" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAnalyticsInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAuthInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop"  "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/AppAuth/AppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/BoringSSL-GRPC/openssl_grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FMDB/FMDB.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseAuth/FirebaseAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCore/FirebaseCore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseDynamicLinks/FirebaseDynamicLinks.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseFirestore/FirebaseFirestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseInstanceID/FirebaseInstanceID.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/FirebaseStorage/FirebaseStorage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMAppAuth/GTMAppAuth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/abseil/absl.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/app_review/app_review.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/apple_sign_in/apple_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/cloud_firestore/cloud_firestore.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/device_info/device_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_analytics/firebase_analytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_auth/firebase_auth.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_core/firebase_core.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_crashlytics/firebase_crashlytics.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_dynamic_links/firebase_dynamic_links.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/firebase_storage/firebase_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_email_sender/flutter_email_sender.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_facebook_login/flutter_facebook_login.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/flutter_secure_storage/flutter_secure_storage.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-C++/grpcpp.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/gRPC-Core/grpc.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/google_sign_in/google_sign_in.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/leveldb-library/leveldb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/nanopb/nanopb.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/package_info/package_info.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/path_provider/path_provider.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/shared_preferences/shared_preferences.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/sqflite/sqflite.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/url_launcher/url_launcher.framework/Headers" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/Firebase" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAnalyticsInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseAuthInterop" "/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop"  /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Firebase/CoreOnly/Sources /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods/Firebase/CoreOnly/Sources
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/***myUserName***
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = ***myUserName***
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 12.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  '@executable_path/Frameworks' '@loader_path/Frameworks' '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_OS_VERSION = ios12.0
               LLVM_TARGET_TRIPLE_VENDOR = apple
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
               LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 19E287
               MAC_OS_X_VERSION_ACTUAL = 101504
               MAC_OS_X_VERSION_MAJOR = 101500
               MAC_OS_X_VERSION_MINOR = 1504
               MARKETING_VERSION = 1.0.0
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app
               MODULES_FOLDER_PATH = Runner.app/Modules
               MODULE_CACHE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = YES
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex
               ONLY_ACTIVE_ARCH = YES
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -framework Flutter -framework Flutter
               OTHER_SWIFT_FLAGS =  -D COCOAPODS -D COCOAPODS
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/opt/openssl/bin:/Users/***myUserName***/Development/flutter/bin:/Users/***myUserName***/anaconda3/bin:/Users/***myUserName***/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 17E8258
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PODS_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios
               PODS_CONFIGURATION_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos
               PODS_PODFILE_DIR_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/.
               PODS_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Pods
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.arconia.myProjectName.dev
               PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
               PRODUCT_FLAVOR = dev
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/DerivedSources
               PROJECT_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               PROJECT_FILE_PATH = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build
               PROJECT_TEMP_ROOT = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_DIR_iphoneos13_4 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
               SDK_NAME = iphoneos13.4
               SDK_NAMES = iphoneos13.4
               SDK_PRODUCT_BUILD_VERSION = 17E8258
               SDK_VERSION = 13.4
               SDK_VERSION_ACTUAL = 130400
               SDK_VERSION_MAJOR = 130000
               SDK_VERSION_MINOR = 400
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/PrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               SRCROOT = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_MACCATALYST = NO
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -Onone
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_VERSION = 5.0
               SYMROOT = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Products
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build
               TEMP_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex/Runner.build/Debug-dev-iphoneos/Runner.build
               TEMP_ROOT = /Users/***myUserName***/Library/Developer/Xcode/DerivedData/Runner-ggxxobkjnbaeuwfzknrwoxpodiih/Build/Intermediates.noindex
               TEST_FRAMEWORK_SEARCH_PATHS =  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks
               TEST_LIBRARY_SEARCH_PATHS =  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TRACK_WIDGET_CREATION = true
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               TREE_SHAKE_ICONS = false
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = ***myUserName***
               USER_APPS_DIR = /Users/***myUserName***/Applications
               USER_LIBRARY_DIR = /Users/***myUserName***/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               USE_LLVM_TARGET_TRIPLES = YES
               USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
               USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
               USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
               USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES
               VALIDATE_PRODUCT = NO
               VALIDATE_WORKSPACE = NO
               VALID_ARCHS = arm64 arm64e armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = ***myUserName***
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-10802"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 11E503a
               XCODE_VERSION_ACTUAL = 1141
               XCODE_VERSION_MAJOR = 1100
               XCODE_VERSION_MINOR = 1140
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal

           2020-05-14 15:00:29.281 xcodebuild[44407:9833208]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
           2020-05-14 15:00:29.371 xcodebuild[44407:9833208]  DTDeviceKit: deviceType from 846c7068c4b73e49341722e3abcb3cecdf4998c1 was NULL
[   +7 ms] Failed to build iOS app
[   +1 ms] Error output from Xcode build:
           ↳
[        ]     ** BUILD FAILED **

[        ] Xcode's output:
           ↳
[        ]     warning: RUN SCRIPT in ACTION
               Development Google plist copied
               building file list ... done
               deleting App.framework/_CodeSignature/CodeResources
               deleting App.framework/_CodeSignature/
               App.framework/
               App.framework/App

               sent 51354 bytes  received 48 bytes  102804.00 bytes/sec
               total size is 43216302  speedup is 840.75
               building file list ... done
               Flutter.framework/
               Flutter.framework/Flutter
               Flutter.framework/Info.plist
               Flutter.framework/icudtl.dat
               Flutter.framework/_CodeSignature/
               Flutter.framework/_CodeSignature/CodeResources

               sent 97999333 bytes  received 120 bytes  65332968.67 bytes/sec
               total size is 97986963  speedup is 1.00
               /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
               /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
               /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
               2020-05-14 15:00:26.131 defaults[44403:9832953] 
               The domain/default pair of (/Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/Info.plist, CFBundleExecutable) does not exist
               fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
               fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
               Failed to extract arm64 for /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
               fatal error: lipo: can't map input file: /Users/***myUserName***/Development/project/MyProjectName/app/myProjectName/build/ios/Debug-dev-iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
               Command PhaseScriptExecution failed with a nonzero exit code
               note: Using new build system
               note: Building targets in parallel
               note: Planning build
               note: Constructing build description

[   +4 ms] Could not build the precompiled application for the device.
[   +8 ms] Error launching application on iPhone 7.

```
```

</details>

```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale de-DE)
    • Flutter version 1.19.0-1.0.pre at /Users/***myUserName***/Development/flutter
    • Framework revision 456d80b9dd (3 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/***myUserName***/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone 7 • 846c7068c4b73e49341722e3abcb3cecdf4998c1 • ios        • iOS 13.4.1
    • iPhone 8 • C0F33D6A-82FB-4B7E-9E65-4D673FD475D4     • ios        • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS    • macOS                                    • darwin-x64 • Mac OS X 10.15.4 19E287
```

Note: The IntelliJ plugins are fully installed and running. Flutter doctor is giving a false result here.

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/45075
Fixes https://github.com/flutter/flutter/issues/57210

If an asset was included directly from the project root directory, then the same asset when copied to various output or ephemeral directories would also be picked up as an asset variant. This could cause assets to be recursively copied into asset/build/ephemeral directories, as each time it would run it would pick up all of the previous "variants".

The solution is to include project ephemeral directories, in addition to the build directory.

### CODE REVIEW

File: packages/flutter_tools/lib/src/asset.dart [hunk 1]
```diff
@@ -613,7 +622,9 @@ class _AssetDirectoryCache {
       final List<String> paths = <String>[];
       for (final FileSystemEntity entity in globals.fs.directory(directory).listSync(recursive: true)) {
         final String path = entity.path;
-        if (globals.fs.isFileSync(path) && !_excluded.any((String exclude) => path.startsWith(exclude))) {
+        if (globals.fs.isFileSync(path)
+          && assetPath != path
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/asset.dart:626]: need to check the assetPath != path, otherwise the tool recognizes `assets: - foo.txt` as its own asset variant.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
```
info • Unused import: 'package:flutter_tools/src/project.dart' • packages/flutter_tools/test/general.shard/asset_bundle_test.dart:16:8 • unused_import
```

File: packages/flutter_tools/lib/src/device.dart [hunk 2]
```diff
@@ -67,46 +67,11 @@ class PlatformType {
 }
 
 /// A class to get all available devices.
-class DeviceManager {
+abstract class DeviceManager {
 
   /// Constructing DeviceManagers is cheap; they only do expensive work if some
   /// of their methods are called.
-  List<DeviceDiscovery> get deviceDiscoverers => _deviceDiscoverers;
-  final List<DeviceDiscovery> _deviceDiscoverers = List<DeviceDiscovery>.unmodifiable(<DeviceDiscovery>[
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/device.dart:75]: This was getting hit in devices_test and failing if it grabbed the wrong context, I did some minor cleanup but it needs to be fixed later so that there is no accidental caching
