### PR TITLE
Revert "Eliminate CocoaPods install step (#8694)"

### LINKED ISSUE #8526: Flutter build/run should run 'pod install'
It would be nice if the flutter tool would run `pod install` as part of the build process for iOS apps with pod dependencies.

Note, that some README.md files in the example apps should be updated once we have this.

### LINKED ISSUE #8657: Flutter run should fail with a useful error message if CocoaPods not installed
## Steps to Reproduce

On a Mac without CocoaPods installed:
1. flutter create testapp
1. cd testapp
1. flutter run

### Expected
CocoaPods is required when a Podfile is present. On invocation of iOS flutter tool commands, should check for a valid install of required iOS toolchain components similar to the pub validation we do when `usesPubOption` is applied and fail immediately with a useful error message.

### Actual
```
% flutter run -d iP
Launching lib/main.dart on iPhone 7 in debug mode...
Exception from flutter run: Invalid argument(s): Cannot find executable for pod.
package:process/src/interface/local_process_manager.dart 115            _getExecutable
package:process/src/interface/local_process_manager.dart 86             LocalProcessManager.runSync
package:flutter_tools/src/base/process.dart 267                         _runWithLoggingSync
package:flutter_tools/src/base/process.dart 216                         runCheckedSync
package:flutter_tools/src/ios/mac.dart 322                              _installCocoaPods
package:flutter_tools/src/ios/mac.dart 129                              buildXcodeProject
package:flutter_tools/src/ios/simulators.dart 518                       IOSSimulator._buildAndInstallApplicationBundle
package:flutter_tools/src/ios/simulators.dart 512                       IOSSimulator._setupUpdatedApplicationBundle
package:flutter_tools/src/ios/simulators.dart 433                       IOSSimulator.startApp
package:flutter_tools/src/run_hot.dart 157                              HotRunner._run
package:flutter_tools/src/run_hot.dart 78                               HotRunner.run.<fn>
package:stack_trace                                                     Chain.capture
package:flutter_tools/src/run_hot.dart 77                               HotRunner.run
package:flutter_tools/src/commands/run.dart 284                         RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148               FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 199                         RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119               FlutterCommand.run
package:args/command_runner.dart 194                                    CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 261        FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                    CommandRunner.run.<fn>
dart:async                                                              Future.Future.sync
package:args/command_runner.dart 109                                    CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 157        FlutterCommandRunner.run
package:flutter_tools/executable.dart 145                               run.<fn>.<fn>
package:stack_trace                                                     Chain.capture
package:flutter_tools/executable.dart 144                               run.<fn>
package:flutter_tools/src/base/context.dart 76                          AppContext._run
package:flutter_tools/src/base/context.dart 66                          AppContext.runInZone.<fn>
dart:async                                                              runZoned
package:flutter_tools/src/base/context.dart 65                          AppContext.runInZone
package:flutter_tools/executable.dart 114                               run
package:flutter_tools/executable.dart 68                                main
../src/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart 8  main
===== asynchronous gap ===========================
dart:async                                                              _Completer.completeError
package:flutter_tools/src/ios/mac.dart 206                              buildXcodeProject
===== asynchronous gap ===========================
dart:async                                                              _asyncThenWrapperHelper
package:flutter_tools/src/ios/mac.dart                                  buildXcodeProject
package:flutter_tools/src/ios/simulators.dart 518                       IOSSimulator._buildAndInstallApplicationBundle
===== asynchronous gap ===========================
dart:async                                                              Future.Future.microtask
package:flutter_tools/src/ios/simulators.dart                           IOSSimulator._buildAndInstallApplicationBundle
package:flutter_tools/src/ios/simulators.dart 512                       IOSSimulator._setupUpdatedApplicationBundle
===== asynchronous gap ===========================
dart:async                                                              _asyncThenWrapperHelper
package:flutter_tools/src/ios/simulators.dart                           IOSSimulator._setupUpdatedApplicationBundle
package:flutter_tools/src/ios/simulators.dart 433                       IOSSimulator.startApp
===== asynchronous gap ===========================
dart:async                                                              Future.Future.microtask
package:flutter_tools/src/ios/simulators.dart                           IOSSimulator.startApp
package:flutter_tools/src/run_hot.dart 157                              HotRunner._run
===== asynchronous gap ===========================
dart:async                                                              _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                                  HotRunner._run
package:flutter_tools/src/run_hot.dart 78                               HotRunner.run.<fn>
package:stack_trace                                                     Chain.capture
package:flutter_tools/src/run_hot.dart 77                               HotRunner.run
package:flutter_tools/src/commands/run.dart 284                         RunCommand.runCommand

^C
````

### LINKED ISSUE #8685: CocoaPods version incompatibility results in stack trace
## Steps to Reproduce

If an incompatible version of CocoaPods is installed, the `pod install` step in iOS build/run errors out with a stack trace rather than a clean exit (or warning that `pod install` wasn't successful).

From @collinjackson:

```
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.0.1) is higher than the version of the current executable (0.35.0). Incompatibility issues may arise.
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.35.0)
Exception from flutter run: Exit code 1 from: pod install
Update CocoaPods, or checkout the appropriate tag in the repo.
package:flutter_tools/src/base/process.dart 294                   _runWithLoggingSync
package:flutter_tools/src/base/process.dart 216                   runCheckedSync
package:flutter_tools/src/ios/mac.dart 332                        _installCocoaPods
package:flutter_tools/src/ios/mac.dart 129                        buildXcodeProject
package:flutter_tools/src/ios/simulators.dart 518                 IOSSimulator._buildAndInstallApplicationBundle
package:flutter_tools/src/ios/simulators.dart 512                 IOSSimulator._setupUpdatedApplicationBundle
package:flutter_tools/src/ios/simulators.dart 433                 IOSSimulator.startApp
package:flutter_tools/src/run_hot.dart 157                        HotRunner._run
package:flutter_tools/src/run_hot.dart 78                         HotRunner.run.<fn>
package:stack_trace/src/chain.dart 93                             Chain.capture.<fn>
dart:async/zone.dart 1150                                         _rootRun
dart:async/zone.dart 1026                                         _CustomZone.run
dart:async/zone.dart 1503                                         runZoned
package:stack_trace/src/chain.dart 91                             Chain.capture
package:flutter_tools/src/run_hot.dart 77                         HotRunner.run
package:flutter_tools/src/commands/daemon.dart 406                AppDomain.startApp.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async/zone.dart 1150                                         _rootRun
dart:async/zone.dart 1026                                         _CustomZone.run
dart:async/zone.dart 1503                                         runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 732                AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 404                AppDomain.startApp
package:flutter_tools/src/commands/run.dart 216                   RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148         FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 199                   RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119         FlutterCommand.run
package:args/command_runner.dart 194                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 261  FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async/future.dart 208                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 157  FlutterCommandRunner.run
package:flutter_tools/executable.dart 145                         run.<fn>.<fn>
package:stack_trace/src/chain.dart 93                             Chain.capture.<fn>
dart:async/zone.dart 1150                                         _rootRun
dart:async/zone.dart 1026                                         _CustomZone.run
dart:async/zone.dart 1503                                         runZoned
package:stack_trace/src/chain.dart 91                             Chain.capture
package:flutter_tools/executable.dart 144                         run.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run
package:flutter_tools/src/base/context.dart 66                    AppContext.runInZone.<fn>
dart:async/zone.dart 1150                                         _rootRun
dart:async/zone.dart 1026                                         _CustomZone.run
dart:async/zone.dart 1503                                         runZoned
package:flutter_tools/src/base/context.dart 65                    AppContext.runInZone
package:flutter_tools/executable.dart 114                         run
package:flutter_tools/executable.dart 68                          main
../../flutter/packages/flutter_tools/bin/flutter_tools.dart 8     main
dart:isolate-patch/isolate_patch.dart 259                         _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 148                         _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/future_impl.dart 22                                    _Completer.completeError
package:flutter_tools/src/ios/mac.dart 206                        buildXcodeProject
===== asynchronous gap ===========================
dart:async/zone.dart 1073                                         _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 30                              _asyncThenWrapperHelper
package:flutter_tools/src/ios/mac.dart                            buildXcodeProject
package:flutter_tools/src/ios/simulators.dart 518                 IOSSimulator._buildAndInstallApplicationBundle
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                         _CustomZone.registerCallback
dart:async/zone.dart 949                                          _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                            scheduleMicrotask
dart:async/future.dart 182                                        Future.Future.microtask
package:flutter_tools/src/ios/simulators.dart                     IOSSimulator._buildAndInstallApplicationBundle
package:flutter_tools/src/ios/simulators.dart 512                 IOSSimulator._setupUpdatedApplicationBundle
===== asynchronous gap ===========================
dart:async/zone.dart 1073                                         _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 30                              _asyncThenWrapperHelper
package:flutter_tools/src/ios/simulators.dart                     IOSSimulator._setupUpdatedApplicationBundle
package:flutter_tools/src/ios/simulators.dart 433                 IOSSimulator.startApp
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                         _CustomZone.registerCallback
dart:async/zone.dart 949                                          _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                            scheduleMicrotask
dart:async/future.dart 182                                        Future.Future.microtask
package:flutter_tools/src/ios/simulators.dart                     IOSSimulator.startApp
package:flutter_tools/src/run_hot.dart 157                        HotRunner._run
===== asynchronous gap ===========================
dart:async/zone.dart 1073                                         _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 30                              _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                            HotRunner._run
package:flutter_tools/src/run_hot.dart 78                         HotRunner.run.<fn>
package:stack_trace/src/chain.dart 93                             Chain.capture.<fn>
dart:async/zone.dart 1150                                         _rootRun
dart:async/zone.dart 1026                                         _CustomZone.run
dart:async/zone.dart 1503                                         runZoned
package:stack_trace/src/chain.dart 91                             Chain.capture
package:flutter_tools/src/run_hot.dart 77                         HotRunner.run
package:flutter_tools/src/commands/daemon.dart 406                AppDomain.startApp.<fn>
```

/cc @jakobr-google

### PR DESCRIPTION
**Pull request by jakobr-google**
This reverts commit f4a13bc72b0d0a6f08592a24a61cc92f86e62061.

If the developer is relying on CocoaPods and hasn't done a pod install, we will do it for them. This is needed for a smooth native plugin experience, similar to what Gradle is doing on the Android side.

There's no hard dependency on CocoaPods. We only run pod install if the project uses CocoaPods, so developers are still free to use alternatives if they prefer (and if they don't want to use native plugins).

Fixes #8685 
Fixes #8657 
Fixes #8526

### CODE REVIEW

**Review by szakarias — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/ios/ios_workflow.dart [hunk 1]
```diff
@@ -41,6 +41,12 @@ class IOSWorkflow extends DoctorValidator implements Workflow {
 
   bool get hasPythonSixModule => exitsHappy(<String>['python', '-c', 'import six']);
 
+  bool get hasCocoaPods => exitsHappy(<String>['pod', '--version']);
+
+  String get cocoaPodsMinimumVersion => '1.0.0';
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/ios/ios_workflow.dart]: [nit] Perhaps more expressive to let this getter return a Version.

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -315,6 +318,30 @@ bool _checkXcodeVersion() {
   return true;
 }
 
+bool _checkCocoaPodsInstalled() {
+  if (!platform.isMacOS)
+    return false;
+  return exitsHappy(<String>['pod', '--version']);
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Duplicated line 44 of ios_workflow.dart

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 3]
```diff
@@ -315,6 +318,30 @@ bool _checkXcodeVersion() {
...
+}
+
+void _installCocoaPods(Directory bundle, String engineDirectory)  {
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/ios/mac.dart]: [nit] Ambiguous name: are we installing the cocoapods tool or a particular cocoa pod?

**Review by mravn-google — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 2 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Yep, and we won't get here at all if (!platform.isMacOS), so we don't really need to check that.

File: packages/flutter_tools/lib/src/ios/ios_workflow.dart (hunk 1 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/ios/ios_workflow.dart]: I considered it, but decided to follow the pattern from ios-deploy.

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 3 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/ios/mac.dart]: True. We're installing the pods required by the app. I'll change the name.

**Comment by jakobr-google** [comment]
@cbracken @collinjackson
