### PR TITLE
Provide monitor list, display size, refresh rate, and more for Windows

### LINKED ISSUE #160660: WidgetsBinding.instance.platformDispatcher.displays.first.size returns Size(0.0, 0.0) zero on Windows
### Steps to reproduce

Open a new Flutter project (default increment counter example)

Add the following code:
```
      Size _screenSize = WidgetsBinding.instance.platformDispatcher.displays.first.size;
      print("display: ${_screenSize}");
```

Run the project on Windows 11.

### Expected results

`display: Size(3440.0, 1440.0)`
Output on Chrome

### Actual results

`display: Size(0.0, 0.0)`
Output on Windows 11
Version 10.0.22631 Build 22631

### Code sample

```
  void _incrementCounter() {
    setState(() {
      _counter++;

      Size _screenSize = WidgetsBinding.instance.platformDispatcher.displays.first.size;
      print("display: ${_screenSize}");
    });
  }
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Additional logs printed by:
```
      Size _screenSize = WidgetsBinding.instance.platformDispatcher.displays.first.size;
      print("display: ${_screenSize}");
      print("display: ${WidgetsBinding.instance.platformDispatcher.displays}");
      print("display: ${WidgetsBinding.instance.platformDispatcher.displays.first}");
```

```
flutter: display: Size(0.0, 0.0)
flutter: display: (Display(id: 0, size: Size(0.0, 0.0), devicePixelRatio: 0.0, refreshRate: 99.9750062484379))
flutter: display: Display(id: 0, size: Size(0.0, 0.0), devicePixelRatio: 0.0, refreshRate: 99.9750062484379)
```

actual refresh rate of the monitor is 100Hz

### Flutter Doctor output

```
> flutter doctor -v
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.4602], locale en-DE)
    • Flutter version 3.22.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (5 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.207
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### PR DESCRIPTION
**Pull request by 9AZX**
This PR enhances the Windows implementation by adding support for retrieving display properties, available displays, refresh rate, dpi, size, and more.

Fixes: #160660, #125939

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    case WM_DISPLAYCHANGE:
+    case WM_DPICHANGED:
+      UpdateDisplays();
+      return true;
+    default:
+      return false;
+  }
+}
+
+}  // namespace flutter
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc:101]: Please add a new line at the end of the file :)

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+    // Skip displays that are not attached to the desktop
+    if ((display_device.StateFlags & DISPLAY_DEVICE_ATTACHED_TO_DESKTOP) == 0) {
+      continue;
+    }
+
+    DEVMODE device_mode = {0};
+    device_mode.dmSize = sizeof(DEVMODE);
+
+    if (windows_proc_table_->EnumDisplaySettings(
+            display_device.DeviceName, ENUM_CURRENT_SETTINGS, &device_mode)) {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc:42]: Nit: could you `continue` if `EnumDisplaySettings` returns `false`?

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor_unittests.cc [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+using ::testing::AllOf;
+using ::testing::AtLeast;
+using ::testing::DoAll;
+using ::testing::Field;
+using ::testing::NiceMock;
+using ::testing::Return;
+using ::testing::SetArgPointee;
+using ::testing::StrEq;
+
+MockWindowsProcTable* g_windows_proc_table = nullptr;
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor_unittests.cc:31]: Can this line be removed?

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine.h [hunk 4]
```diff
@@ -158,6 +159,14 @@ class FlutterWindowsEngine {
     return message_dispatcher_.get();
   }
 
+  FlutterWindowsDisplayMonitor* display_monitor() {
+    return display_monitor_.get();
+  }
+
+  // Notifies the engine about a display update.
+  void UpdateDisplay(const FlutterEngineDisplay* displays,
+                     size_t displays_length);
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_engine.h:168]: Ideally `FlutterWindowsEngine` should be a high-level C++ API. Could we make this accept a vector and have the implementation convert the vector into a pointer + size?

File: engine/src/flutter/ci/licenses_golden/licenses_flutter [hunk 5]
```diff
@@ -56444,6 +56446,8 @@ FILE: ../../../flutter/shell/platform/windows/flutter_project_bundle.h
 FILE: ../../../flutter/shell/platform/windows/flutter_window.cc
 FILE: ../../../flutter/shell/platform/windows/flutter_window.h
 FILE: ../../../flutter/shell/platform/windows/flutter_windows.cc
+FILE: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.h
+FiLE: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.cc
```
Comment (loic-sharma) [inline engine/src/flutter/ci/licenses_golden/licenses_flutter:56450]:
```suggestion
FILE: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.cc
FILE: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.h
```

File: engine/src/flutter/ci/licenses_golden/licenses_flutter [hunk 6]
```diff
@@ -53427,6 +53427,8 @@ ORIGIN: ../../../flutter/shell/platform/windows/flutter_project_bundle.h + ../..
 ORIGIN: ../../../flutter/shell/platform/windows/flutter_window.cc + ../../../flutter/LICENSE
 ORIGIN: ../../../flutter/shell/platform/windows/flutter_window.h + ../../../flutter/LICENSE
 ORIGIN: ../../../flutter/shell/platform/windows/flutter_windows.cc + ../../../flutter/LICENSE
+ORIGIN: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.h + ../../../flutter/LICENSE
+ORIGIN: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.cc + ../../../flutter/LICENSE
```
Comment (loic-sharma) [inline engine/src/flutter/ci/licenses_golden/licenses_flutter:53431]:
```suggestion
ORIGIN: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.cc + ../../../flutter/LICENSE
ORIGIN: ../../../flutter/shell/platform/windows/flutter_windows_display_monitor.h + ../../../flutter/LICENSE
```

**Comment by loic-sharma** [comment]
Apologies for the long response time, this is looking great! I left some minor nitpicks. Feel free to tag me when this is ready for another review.

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+
+      // Calculate device pixel ratio
+      UINT dpi = GetDpiForMonitor(monitor);
+      display.device_pixel_ratio = static_cast<double>(dpi) / kDefaultDpi;
+
+      displays.push_back(display);
+    }
+  }
+
+  if (!displays.empty()) {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc:81]: Could you explain why you skip `UpdateDisplay` if there are no displays?

Comment (loic-sharma) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc:81]: FYI, you have a test failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8718619884078032065/+/u/test:_Host_Tests_for_host_debug_test/stdout

```
Note: Google Test filter = FlutterWindowsEngineTest.RunDoesExpectedInitialization
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from FlutterWindowsEngineTest
[ RUN      ] FlutterWindowsEngineTest.RunDoesExpectedInitialization
../../../flutter/shell/platform/windows/flutter_windows_engine_unittests.cc(165): error: Value of: notify_display_update_called
  Actual: false
Expected: true
```

The test verifies that update display is called at startup:

https://github.com/flutter/flutter/blob/2ca6284ce3375248fa5571795108dfc3faef3970/engine/src/flutter/shell/platform/windows/flutter_windows_engine_unittests.cc#L142-L163

You will likely need to pass in a windows proc table that provides a display.

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc (hunk 2 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc:46]: done

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine.h (hunk 4 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_engine.h]: Agreed !

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc (hunk 7 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: I initially thought skipping `UpdateDisplay` when there’s no display would prevent propagating invalid or incomplete info to the engine. I checked the macOS and Linux implementation and indeed it does not skip, so this can be removed :)

**Comment by loic-sharma** [comment]
FYI you have the some test failures: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8716084517876313281/+/u/test:_test:_Host_Tests_for_host_debug_unopt/stdout

```
[151/610] FlutterWindowsEngineTest.RunHeadless (943 ms)
[INFO:flutter/testing/test_timeout_listener.cc(75)] Test timeout of 300 seconds per test case will be enforced.
Note: Google Test filter = FlutterWindowsEngineTest.RunHeadless
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from FlutterWindowsEngineTest
[ RUN      ] FlutterWindowsEngineTest.RunHeadless
WARN: Renderer11.cpp:972 (initializeD3DDevice): Failed creating Debug D3D11 device - falling back to release runtime.
WARN: Renderer11.cpp:972 (initializeD3DDevice): Failed creating Debug D3D11 device - falling back to release runtime.
[FATAL:flutter/shell/common/display_manager.cc(27)] Check failed: !displays.empty().
[151/610] FlutterWindowsEngineTest.RunHeadless returned/aborted with exit code 3 (943 ms)
[152/610] FlutterWindowsEngineTest.PlatformMessageRespondOnDifferentThread (882 ms)
[INFO:flutter/testing/test_timeout_listener.cc(75)] Test timeout of 300 seconds per test case will be enforced.
Note: Google Test filter = FlutterWindowsEngineTest.PlatformMessageRespondOnDifferentThread
```

FYI, you can run these tests locally on your machine by running `out/flutter_windows_unittests.exe`.

**Comment by 9AZX** [comment]
> FYI, you can run these tests locally on your machine by running `out/flutter_windows_unittests.exe`.

I was doing that, but i think the test runs headless only on the CI. I'm not getting any errors locally :(

**Comment by loic-sharma** [comment]
@mattkae @knopp Would y'all be able to review this as well? I suspect this will be useful for multi-window :)

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+#ifndef FLUTTER_SHELL_PLATFORM_WINDOWS_FLUTTER_WINDOWS_DISPLAY_MONITOR_H_
+#define FLUTTER_SHELL_PLATFORM_WINDOWS_FLUTTER_WINDOWS_DISPLAY_MONITOR_H_
+
+#include <windows.h>
+#include "shell/platform/windows/windows_proc_table.h"
+
+namespace flutter {
+
+class FlutterWindowsEngine;
+class FlutterWindowsDisplayMonitor {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h]: Can we call this just `DisplayMonitor`?

(The `FlutterWindows` prefix is a legacy naming convention when we used to have both UWP and win32 support, but we're moving away from it)

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+  bool HandleWindowMessage(HWND hwnd,
+                           UINT message,
+                           WPARAM wparam,
+                           LPARAM lparam,
+                           LRESULT* result);
+
+ private:
+  FlutterWindowsEngine* engine_;
+
+  std::shared_ptr<WindowsProcTable> windows_proc_table_;
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h]: Let's call this just `win32_` to make the code more succinct:

```suggestion
  std::shared_ptr<WindowsProcTable> win32_;
```

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+bool FlutterWindowsDisplayMonitor::HandleWindowMessage(HWND hwnd,
+                                                       UINT message,
+                                                       WPARAM wparam,
+                                                       LPARAM lparam,
+                                                       LRESULT* result) {
+  switch (message) {
+    case WM_DISPLAYCHANGE:
+    case WM_DPICHANGED:
+      UpdateDisplays();
+      return true;
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: Just curious, is consuming this message the right thing to do? Would it be better if we let the message flow to other window procedures that might also process it?

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine_unittests.cc [hunk 11]
```diff
@@ -66,6 +66,69 @@ TEST_F(FlutterWindowsEngineTest, RunDoesExpectedInitialization) {
   builder.AddDartEntrypointArgument("arg1");
   builder.AddDartEntrypointArgument("arg2");
 
+  auto windows_proc_table = std::make_shared<MockWindowsProcTable>();
+
+  EXPECT_CALL(*windows_proc_table, GetSystemMetrics(::testing::_))
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/flutter_windows_engine_unittests.cc]: Could you add a `using ::testing::_;` up above?

**Comment by loic-sharma** [comment]
@9AZX This is looking good! I left some nitpicks. Once you address those, I'll test manually on my machine and get this landed.

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h (hunk 8 above)
Comment (mattkae) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h]: +1 for this :)

File: engine/src/flutter/shell/common/display_manager.cc [hunk 12]
```diff
@@ -24,7 +24,6 @@ double DisplayManager::GetMainDisplayRefreshRate() const {
 
 void DisplayManager::HandleDisplayUpdates(
     std::vector<std::unique_ptr<Display>> displays) {
-  FML_DCHECK(!displays.empty());
```
Comment (mattkae) [inline engine/src/flutter/shell/common/display_manager.cc:27]: Is this an intended change?

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 13]
```diff
@@ -0,0 +1,105 @@
...
+#include <vector>
+
+#include "flutter/shell/platform/windows/dpi_utils.h"
+#include "flutter/shell/platform/windows/flutter_windows_engine.h"
+
+namespace flutter {
+
+FlutterWindowsDisplayMonitor::FlutterWindowsDisplayMonitor(
+    FlutterWindowsEngine* engine,
+    std::shared_ptr<WindowsProcTable> windows_proc_table)
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: Would this be better off passed as a `const&` so that we can avoid the `std::move`?

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+
+namespace flutter {
+
+class FlutterWindowsEngine;
+class FlutterWindowsDisplayMonitor {
+ public:
+  FlutterWindowsDisplayMonitor(
+      FlutterWindowsEngine* engine,
+      std::shared_ptr<WindowsProcTable> windows_proc_table);
+  virtual ~FlutterWindowsDisplayMonitor();
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.h]: Nit: Why is this `virtual`? Is this class meant to be extended?

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc [hunk 15]
```diff
@@ -0,0 +1,105 @@
...
+            {0, 0}, MONITOR_DEFAULTTOPRIMARY);
+      }
+
+      // Calculate device pixel ratio
+      UINT dpi = GetDpiForMonitor(monitor);
+      display.device_pixel_ratio = static_cast<double>(dpi) / kDefaultDpi;
+
+      displays.push_back(display);
+    } else {
+      continue;
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: This `continue` is unnecessary, right?

**Review by mattkae — APPROVED** [review]
Some minor nits, but I won't block on any of them. Looks good :)

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc (hunk 10 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: Apologies if I'm mistaken, but I don't think the message is actually consumed here. It seems like the engine still retains it and passes it on to the display monitor

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc (hunk 15 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: You're right, it's technically unnecessary, but I added it to address the earlier suggestion from Loïc :)
> Nit: could you `continue` if `EnumDisplaySettings` returns `false`?

**Review by knopp — CHANGES_REQUESTED** [review]
I am wondering why not simply use `EnumDisplayMonitors` for this? There is still going to be the awkward part of going through devices to determine refresh rate but it seems that it would still be simpler?

Also I'm not sure using the index as identifier is the best we can do, maybe cast the HMONITOR value instead so that it is possible to use it in native code should the application need something more that current API exposes? 

TBH, In current iteration the display API is quite limited, for example it doesn't expose display rect and usable area, which is something we could definitely use in multiwindow. But also is the annoying part of these units being physical pixels on some platforms (windows) and logical on others (macOS, Linux). So there's some thinking that'd need to go into this.

**Comment by loic-sharma** [comment]
> Also I'm not sure using the index as identifier is the best we can do, maybe cast the HMONITOR value instead so that it is possible to use it in native code should the application need something more that current API exposes?
> ...
> TBH, In current iteration the display API is quite limited, for example it doesn't expose display rect and usable area, which is something we could definitely use in multiwindow.

@knopp, Do you think we could address these concerns in one or more follow-up PRs? @9AZX is a community contributor, I don't want to sign them up for more work (unless of course they're willing to keep contributing!) unless these improvements are necessary to land this.

> But also is the annoying part of these units being physical pixels on some platforms (windows) and logical on others (macOS, Linux). So there's some thinking that'd need to go into this.

Both the embedder API's `FlutterEngineDisplay` docs ([here](https://github.com/flutter/flutter/blob/9ba6aafb94a6bb7ea7b81fddfb0cceef0e0a0357/engine/src/flutter/shell/platform/embedder/embedder.h#L2286-L2290)) and dart:ui's `Display.size` docs ([here](https://api.flutter.dev/flutter/dart-ui/Display/size.html)) state this should be the physical size. Any concerns with making macOS and Linux convert to physical sizes?

(In hindsight, we should've called these `FlutterEngineDisplay.physical_width`, `FlutterEngineDisplay.physical_height`, and `Display.physicalSize`... Whoops)

**Comment by knopp** [comment]
I think exposing additional properties for displays is definitely out of scope here. 

But I don't think `EnumDisplayDevices` is the correct thing to do. The need for `DISPLAY_DEVICE_ATTACHED_TO_DESKTOP` and having to get monitor from position might be the indication that the API has different purpose. I think what we really want here is `EnumDisplayMonitors`  which will give you `HMONITOR`s that make current desktop.

Then if you want to get refresh rate for a `HMONITOR`, you get the device name through `GetMonitorInfo` and then `EnumDisplaySettings` to get the refresh rate. The result should simpler and shorter code than what the current iteration.

File: engine/src/flutter/shell/platform/windows/display_monitor.cc [hunk 16]
```diff
@@ -0,0 +1,103 @@
...
+
+void DisplayMonitor::UpdateDisplays() {
+  std::vector<FlutterEngineDisplay> displays;
+
+  int display_count = win32_->GetSystemMetrics(SM_CMONITORS);
+
+  DISPLAY_DEVICE display_device = {0};
+  display_device.cb = sizeof(DISPLAY_DEVICE);
+
+  for (int i = 0; win32_->EnumDisplayDevices(nullptr, i, &display_device, 0);
```
Comment (knopp) [inline engine/src/flutter/shell/platform/windows/display_monitor.cc]: I think instead of `EnumDisplayDevices` we should do `EnumDisplayMonitors` instead. That gives you a list of `HMONITORS` directly, instead of having to filter the devices and using `MonitorFromPoint`.

File: engine/src/flutter/shell/platform/windows/display_monitor.cc [hunk 17]
```diff
@@ -0,0 +1,103 @@
...
+      display.height = device_mode.dmPelsHeight;
+
+      // Get the corresponding monitor handle by using a point in the middle of
+      // the display
+      POINT center_point = {static_cast<LONG>(device_mode.dmPosition.x +
+                                              (device_mode.dmPelsWidth / 2)),
+                            static_cast<LONG>(device_mode.dmPosition.y +
+                                              (device_mode.dmPelsHeight / 2))};
+      HMONITOR monitor =
+          win32_->MonitorFromPoint(center_point, MONITOR_DEFAULTTONULL);
```
Comment (knopp) [inline engine/src/flutter/shell/platform/windows/display_monitor.cc]: This should not be necessary if you just enumerate the monitors  through `EnumDisplayMonitors`. And getting the device info from monitor (to get refresh rate) seems less awkward than trying to get the monitor from device.

**Comment by knopp** [comment]
> Both the embedder API's `FlutterEngineDisplay` docs ([here](https://github.com/flutter/flutter/blob/9ba6aafb94a6bb7ea7b81fddfb0cceef0e0a0357/engine/src/flutter/shell/platform/embedder/embedder.h#L2286-L2290)) and dart:ui's `Display.size` docs ([here](https://api.flutter.dev/flutter/dart-ui/Display/size.html)) state this should be the physical size. Any concerns with making macOS and Linux convert to physical sizes?

The window position and dimension on macOS is in logical pixels. But on macOS it is also in y-flipped coordinates, which makes things even better.

TBH I never quite understood the purpose the displays API in its current iteration, since it's missing rather vital information (visible and usable rectangle for each display), and we don't have any windowing API anyway... Maybe if the purpose is cleaner we can determine how much we want to reconcile the behavior between platforms (i.e. once we have visible / usable rectangle, should we y-flip it on macOS?)

**Comment by loic-sharma** [comment]
> TBH I never quite understood the purpose the displays API in its current iteration

I believe the current display API was added to support foldable phones and make Flutter react properly when you switch between the small screen when fully folded, big screen when fully opened, and split screen when partially opened. Desktop wasn't the primary motivation at the time, though we were hoping the API would mostly work.

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine_unittests.cc (hunk 11 above)
Comment (loic-sharma) [reply engine/src/flutter/shell/platform/windows/flutter_windows_engine_unittests.cc]: @9AZX Sorry, I wasn't clear, but the reason I asked to add the `using ::testing::_;` above was so that all these `::testing::_` here and below can become just `_`. Could you update that as well?

File: engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc (hunk 10 above)
Comment (loic-sharma) [reply engine/src/flutter/shell/platform/windows/flutter_windows_display_monitor.cc]: The message is consumed here because this handler returns `true`. We should only do this if it's important for these messages to not be delivered to subsequent procedures.

If we want subsequent procedures to be notified of these messages, we should return `false` instead.

----

For more information on how the returned boolean is used, see:

https://github.com/flutter/flutter/blob/bb784b983b6e0e5f9391080ff159aa2381266376/engine/src/flutter/shell/platform/windows/window_proc_delegate_manager.cc#L45-L49

https://github.com/flutter/flutter/blob/bb784b983b6e0e5f9391080ff159aa2381266376/engine/src/flutter/shell/platform/windows/public/flutter_windows.h#L268-L270

For example, the `WindowsLifecycleManager` class also handles Windows messages but lets them propagate to subsequent procedures by returning `false`:

https://github.com/flutter/flutter/blob/bb784b983b6e0e5f9391080ff159aa2381266376/engine/src/flutter/shell/platform/windows/windows_lifecycle_manager.cc#L65-L104

**Comment by 9AZX** [comment]
Hi everyone,

Thanks for the reviews! I’ll update the code to use `EnumDisplayMonitors` instead of `EnumDisplayDevices`. I really appreciate the insight, as I’m not very experienced with the Win32 API. I’ll also address the nits.

I agree that adding more properties is out of scope for this PR, so I’ll focus on wrapping this up and getting it landed. Ideally this happens before the multi-window merge begins. Some of the current info is still useful for certain use cases, including ours at @Betclic.

If you're okay with it, I’ll send over a design doc on Discord and here in the next few days for the proposed new properties.

File: engine/src/flutter/shell/platform/windows/display_monitor.cc (hunk 16 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/display_monitor.cc]: Okay nice, I didn't know about EnumDisplayMonitors. I found it a bit awkward but thought that was just the norm with win32 😆

**Comment by knopp** [comment]
> > TBH I never quite understood the purpose the displays API in its current iteration
> 
> I believe the current display API was added to support foldable phones and make Flutter react properly when you switch between the small screen when fully folded, big screen when fully opened, and split screen when partially opened. Desktop wasn't the primary motivation at the time, though we were hoping the API would mostly work.

That makes sense. For this API to be useful on desktop we need display geometry (the display position within overall screen configuration) and the usable subrect, and to standardize the units across platforms (i.e. decide or logical / physical units and coordinate spaces). I don't think it would be too much work to add.

I do think having the coordinates in logical space is nicer, but the conversion from physical units to logical for a display configuration is not all that trivial. I have an attempt for it [here](https://github.com/nativeshell/nativeshell/blob/cd1d9c9aa590cfcc72d8c6068d0f6c63a4f68e6e/nativeshell/src/shell/platform/win32/display.rs#L358), i think it works quite well, but I'm not sure I'd want to introduce that in the windows embedder.

File: engine/src/flutter/shell/platform/windows/display_monitor.cc (hunk 17 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/display_monitor.cc]: Normally it's fixed and indeed it's way better

File: engine/src/flutter/shell/platform/windows/display_monitor.h [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+#include <windows.h>
+#include "shell/platform/windows/windows_proc_table.h"
+
+namespace flutter {
+
+class FlutterWindowsEngine;
+class DisplayMonitor {
+ public:
+  DisplayMonitor(FlutterWindowsEngine* engine,
+                 std::shared_ptr<WindowsProcTable> windows_proc_table);
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/display_monitor.h]:
```suggestion
                 std::shared_ptr<WindowsProcTable> win32);
```

File: engine/src/flutter/shell/platform/windows/display_monitor.cc [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+  DisplayMonitor* display_monitor;
+  std::vector<FlutterEngineDisplay>* displays;
+};
+
+}  // namespace
+
+DisplayMonitor::DisplayMonitor(
+    FlutterWindowsEngine* engine,
+    std::shared_ptr<WindowsProcTable> windows_proc_table)
+    : engine_(engine), win32_(std::move(windows_proc_table)) {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/windows/display_monitor.cc]:
```suggestion
    std::shared_ptr<WindowsProcTable> win32)
    : engine_(engine), win32_(std::move(win32)) {
```

Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/display_monitor.cc]: Indeed ! Thanks :)

**Comment by mattkae** [comment]
@9AZX Do you have a status on this? I accidentally opened up https://github.com/flutter/flutter/pull/173301 and was wondering if you were still planning on merging this one too :)

**Comment by 9AZX** [comment]
Hello, yes i was still planning to land this one but was waiting for reviews...

**Comment by mattkae** [comment]
> Hello, yes i was still planning to land this one but was waiting for reviews...

I will review today! Sorry I had forgotten about it.

File: engine/src/flutter/shell/platform/windows/display_monitor.h [hunk 20]
```diff
@@ -0,0 +1,43 @@
...
+#ifndef FLUTTER_SHELL_PLATFORM_WINDOWS_DISPLAY_MONITOR_H_
+#define FLUTTER_SHELL_PLATFORM_WINDOWS_DISPLAY_MONITOR_H_
+
+#include <windows.h>
+#include "shell/platform/windows/windows_proc_table.h"
+
+namespace flutter {
+
+class FlutterWindowsEngine;
+class DisplayMonitor {
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/display_monitor.h:18]: Could we add a method to manually get the list of displays? I have a requirement for this for the `Fullscreen` method on windows, so that they can decide which monitor to be fullscreened on?

File: engine/src/flutter/shell/platform/windows/display_monitor.cc [hunk 21]
```diff
@@ -0,0 +1,104 @@
...
+    // Returning FALSE would stop the entire enumeration process,
+    // potentially missing other valid monitors.
+    return TRUE;
+  }
+
+  UINT dpi = GetDpiForMonitor(monitor);
+
+  FlutterEngineDisplay display = {};
+  display.struct_size = sizeof(FlutterEngineDisplay);
+  display.display_id = displays->size() + 1;
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/display_monitor.cc]: This might not be a unique display_id if windows come online and offline. Can we use `reinterpret_cast<FlutterEngineDisplayId>(monitor)` instead?

File: engine/src/flutter/shell/platform/windows/display_monitor.cc [hunk 22]
```diff
@@ -0,0 +1,104 @@
...
+  std::vector<FlutterEngineDisplay>* displays;
+};
+
+}  // namespace
+
+DisplayMonitor::DisplayMonitor(FlutterWindowsEngine* engine,
+                               std::shared_ptr<WindowsProcTable> win32)
+    : engine_(engine), win32_(std::move(win32)) {
+  if (win32_ == nullptr) {
+    win32_ = std::make_shared<WindowsProcTable>();
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/display_monitor.cc]: Nit: Can't we just get this from the `engine` instead?

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine.cc [hunk 23]
```diff
@@ -707,6 +707,15 @@ void FlutterWindowsEngine::AddPluginRegistrarDestructionCallback(
   plugin_registrar_destruction_callbacks_[callback] = registrar;
 }
 
+void FlutterWindowsEngine::UpdateDisplay(
+    const std::vector<FlutterEngineDisplay>& displays) {
+  if (engine_) {
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/windows/flutter_windows_engine.cc:712]: Should we just check `running()` instead?

**Review by mattkae — CHANGES_REQUESTED** [review]
A few small things, but mostly in line with what I had in mind too :)

File: engine/src/flutter/shell/platform/windows/flutter_windows_engine.cc (hunk 23 above)
Comment (9AZX) [reply engine/src/flutter/shell/platform/windows/flutter_windows_engine.cc:712]: Hmm, I think we should leave it like this, other calls in the API don't use it

**Review by mattkae — APPROVED** [review]
This looks good to me :tada:

**Review by knopp — APPROVED** [review]
