### PR TITLE
[flutter_tools] fix calling debugToggleBrightness on release mode

### LINKED ISSUE #65477: Exception NoSuchMethodError: The method 'callMethod' was called on null, callMethod("_flutter.listViews") in FlutterVmService.getFlutterViews
Flutter crashed while building and I found this crash report in my code. I'm on the beta channel

----
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --release -d iphone

## exception

NoSuchMethodError: NoSuchMethodError: The method 'callMethod' was called on null.
Receiver: null
Tried calling: callMethod("_flutter.listViews")

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:770:50)
#2      FlutterDevice.toggleBrightness (package:flutter_tools/src/resident_runner.dart:449:53)
#3      ResidentRunner.debugToggleBrightness (package:flutter_tools/src/resident_runner.dart:1019:62)
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1427:30)
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#24     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:256:17)
#25     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:242:5)
#26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#34     _StreamController._add (dart:async/stream_controller.dart:682:7)
#35     _StreamController.add (dart:async/stream_controller.dart:624:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#37     _rootRunUnary (dart:async/zone.dart:1206:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.20.0-7.4.pre, on Mac OS X 10.15.6 19G73, locale nl-NL)
    • Flutter version 1.20.0-7.4.pre at /Users/wouter/Library/flutter
    • Framework revision 916c3ac648 (9 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Touwer (mobile)    • 00008020-001A2C183A60802E            • ios            • iOS 13.6
    • iPhone 11 (mobile) • A60126EC-021E-4E7A-BFE1-2860A264F766 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

ensure that the terminal handler checks if the service protocol is enabled before calling debug toggle brightness. Also removes globals from TerminalHander and test cases.

Fixes https://github.com/flutter/flutter/issues/65477

### CODE REVIEW

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 1]
```diff
@@ -1431,25 +1442,28 @@ class TerminalHandler {
...
         if (residentRunner.supportsServiceProtocol) {
           await residentRunner.debugToggleProfileWidgetBuilds();
           return true;
         }
         return false;
       case 'b':
-        await residentRunner.debugToggleBrightness();
-        return true;
+        if (residentRunner.supportsServiceProtocol) {
+          await residentRunner.debugToggleBrightness();
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/resident_runner.dart:1463]: Can we push the `supportsServiceProtocol` check into `debugToggleBrightness` and return a bool if it's handled, it it's a requirement?  Otherwise every caller has to know to check it.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/resident_runner.dart:1463]: Some of the methods have meaningful return values, so that would help but it would not necessarily be 100% consistent.

Comment (jmagman) [reply packages/flutter_tools/lib/src/resident_runner.dart:1463]: More defensive programming would be good in the tool code, we have so many spots where the caller needs to understand the guts and requirements of a method to call it, or things need to be called in a certain order to work...

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/resident_runner.dart:1463]: I disagree in general, defensive programming is bad because it makes it harder to track down the cause of crashes. And using crash reporting is just the natural life cycle of a large project that is impossible to completely test.

Though I do agree we should adopt a safer pattern here, and making the invoked function responsible seems like a good adjustment

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/resident_runner.dart:1463]: Oh, and as I say that - of course the FlutterDevice class that defines these methods cannot check that 🤦

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/resident_runner.dart]: ahh nvm I was being silly

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 2]
```diff
@@ -294,87 +318,115 @@ abstract class ResidentWebRunner extends ResidentRunner {
...
-      return;
+      // do nothing.
     }
+    return true;
   }
 
   @override
-  Future<void> debugToggleWidgetInspector() async {
+  Future<bool> debugToggleWidgetInspector() async {
+    if (!supportsServiceProtocol) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:386]: Does web need the debug check?

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 3]
```diff
@@ -294,87 +318,115 @@ abstract class ResidentWebRunner extends ResidentRunner {
...
     } on vmservice.RPCError {
-      return;
+      // do nothing.
     }
+    return true;
   }
 
   @override
-  Future<void> debugToggleInvertOversizedImages() async {
+  Future<bool> debugToggleInvertOversizedImages() async {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:401]: Same.

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 4]
```diff
@@ -294,87 +318,115 @@ abstract class ResidentWebRunner extends ResidentRunner {
...
-      return;
+      // do nothing.
     }
+    return true;
   }
 
   @override
-  Future<void> debugToggleDebugPaintSizeEnabled() async {
+  Future<bool> debugToggleDebugPaintSizeEnabled() async {
+    if (!supportsServiceProtocol) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:338]: Same.

File: packages/flutter_tools/test/general.shard/terminal_handler_test.dart [hunk 5]
```diff
@@ -4,225 +4,172 @@
...
+        mockResidentRunner,
+        logger: testLogger,
+        signals: signals,
+        terminal: terminal,
+      );
       when(mockResidentRunner.supportsServiceProtocol).thenReturn(true);
     });
 
-    testUsingContext('a, can handle trailing newlines', () async {
+    testWithoutContext('a, can handle trailing newlines', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/terminal_handler_test.dart:71]: Woo!

File: packages/flutter_tools/test/general.shard/terminal_handler_test.dart [hunk 6]
```diff
@@ -4,225 +4,172 @@
...
 
-    testUsingContext('a - debugToggleProfileWidgetBuilds with service protocol', () async {
+    testWithoutContext('a - debugToggleProfileWidgetBuilds with service protocol', () async {
       await terminalHandler.processTerminalInput('a');
 
       verify(mockResidentRunner.debugToggleProfileWidgetBuilds()).called(1);
     });
 
-    testUsingContext('a - debugToggleProfileWidgetBuilds without service protocol', () async {
-      when(mockResidentRunner.supportsServiceProtocol).thenReturn(false);
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/terminal_handler_test.dart:83]: Shame we lost the negative case logic.  Can you add it back to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/resident_runner_test.dart#L1653?

Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/terminal_handler_test.dart:83]: yeah - I need to take another pass on this and see where we lost test coverage (I think some of these are covered, but definitely not all of them).

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:386]: The web does not need the debug check, because there is no real "profile" mode with a debug connection but release perf.

**Comment by jonahwilliams** [comment]
Tests kind of added

**Comment by jonahwilliams** [comment]
I really wish I could get branch coverage, otherwise ... uh this is probably about 80% of it

**Review by jmagman — APPROVED** [review]
LGTM, thanks for indulging me 😄
