### PR TITLE
Use RenderSliverPadding to inset SliverFillViewport 

### LINKED ISSUE #23873: PageView with viewportFraction < 1.0 - GestureDetector is not working properly
Hey, looks like there is a bug preventing gesture detection on right side of the widget inside page view with only one element and viewport fraction smaller than 1.0.

This is how my widget tree looks like:
```
column
  - page view
    - gesture detector
      - green container
    - gesture detector
      - blue container
  - page view
    - gesture detector
      - red container
```

screenshot from 2018-11-02 16-14-59

Top gesture detectors (green&blue widgets) work fine, I can click anywhere and I can see debug logs in console.
Bottom gesture detector (red widget) works fine only for left half of the widget. When I click on the right half then onTap callback is not fired. Looks like something is preventing gesture detector from getting input.

flutter doctor output:
```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (1 available)
```

Source code to reproduce bug:
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Column(children: <Widget>[
        Expanded(
          child: ColorPages(
            colors: <Color>[
              Colors.green,
              Colors.blue,
            ],
          ),
        ),
        Expanded(
          child: ColorPages(
            colors: <Color>[
              Colors.red,
            ],
          ),
        ),
      ]),
    );
  }
}

class ColorPages extends StatefulWidget {
  final List<Color> colors;

  const ColorPages({Key key, this.colors}) : super(key: key);

  @override
  ColorPagesState createState() {
    return new ColorPagesState();
  }
}

class ColorPagesState extends State<ColorPages> {
  PageController _pageController;

  @override
  void initState() {
    super.initState();

    _pageController = new PageController(
      viewportFraction: 0.5,
    );
  }

  @override
  Widget build(BuildContext context) {
    return PageView.builder(
      controller: _pageController,
      itemBuilder: (context, index) {
        return GestureDetector(
          onTap: () {
            print(DateTime.now().toIso8601String() + " " + widget.colors[index].toString());
          },
          child: Container(
            color: widget.colors[index],
          ),
        );
      },
      itemCount: widget.colors.length,
    );
  }
}
```

### LINKED ISSUE #27744: PageView doesn't do hit testing right with padding (SliverFillViewport hit test issue?)
`InkWell` will not work if `_file.length` is 1;
but it will work if length is greater than or equal to 2; 
```dart
  Container(
    height: 200,
    child: PageView.builder(
      itemCount: _file.length,
      controller: PageController(viewportFraction: 0.4),
      itemBuilder: (context, index) {
        return Card(
          child: InkWell(
            onTap: () => _picImage(),
            child: Center(
              child: Icon(
                Icons.add,
                size: 40,
              ),
            ),
          ),
        );
      },
    ),
  )
```

```
flutter doctor -v

[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17758.1], locale en-AS)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Suraj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
```

PS: Using Android Studio Not Intellij for Flutter

### LINKED ISSUE #45096: [master, v1.12.3-pre.49] PageView's last page no longer snaps when viewportFraction is set to less than 1
## Steps to Reproduce

PageController's viewportFraction property is set to less than 1, and there is a bounce when switching pages.

https://gist.github.com/januwA/8bfdbcfe3436231c48f437a3e72729e6

flutter-bug

```
λ flutter doctor -v
[√] Flutter (Channel master, v1.12.3-pre.49, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.12.3-pre.49 at D:\my-tools\flutter
    • Framework revision 21e6fe1ddf (8 hours ago), 2019-11-17 23:39:51 -0500
    • Engine revision 3261324fab
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\my-tools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\my-tools\Android\Sdk
    • Java binary at: D:\my-tools\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup
      for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\my-tools\Android\AndroidStudio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • SM G8750   • c5976a52   • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

This PR reimplements `SliverFillViewport` in a similar vein to the reverted PR https://github.com/flutter/flutter/pull/37024.

## Related Issues

Fixes #23873
Fixes #27744
Fixes #45096

## Tests

I added the following tests:

- All visible pages are able to receive touch events
- PageView large viewportFraction can scroll to the last page

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 1]
```diff
@@ -1067,6 +1102,61 @@ class SliverFillViewport extends SliverMultiBoxAdaptorWidget {
...
+class _RenderSliverFractionalPadding extends RenderSliverPadding {
+  _RenderSliverFractionalPadding({
+    double viewportFraction = 0,
+  }) : assert(viewportFraction != null),
+       assert(viewportFraction <= 0.5),
+       assert(viewportFraction >= 0),
+       _viewportFraction = viewportFraction,
+       super(padding: EdgeInsets.zero);
+
+  double _viewportFraction;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: Use getter/setters for this?

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 2]
```diff
@@ -1067,6 +1102,61 @@ class SliverFillViewport extends SliverMultiBoxAdaptorWidget {
...
+    assert(newValue != null);
+    if (_viewportFraction == newValue)
+      return;
+    _viewportFraction = newValue;
+    // Update the padding using the setter. The setter calls marksNeedsLayout internally.
+    padding = padding;
+  }
+
+  @override
+  EdgeInsetsGeometry get padding {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: It seems odd to override the getter for padding like this. Could this just be a private method that gets called whenever we need to set the padding to obtain the value for the padding?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/sliver.dart]: Ended up exposing `resolvedPadding` instead of `markNeedsResolution`

File: packages/flutter/lib/src/rendering/sliver_padding.dart [hunk 3]
```diff
@@ -346,6 +297,82 @@ class RenderSliverPadding extends RenderSliver with RenderObjectWithChildMixin<R
...
   }
+}
+
+/// Insets a [RenderSliver], applying padding on each side.
+///
+/// A [RenderSliverPadding] object wraps the [SliverGeometry.layoutExtent] of
+/// its child. Any incoming [SliverConstraints.overlap] is ignored and not
+/// passed on to the child.
+///
+/// Applying padding to anything but the most mundane sliver is likely to have
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_padding.dart]: Maybe use a macro here since it's the same block of text?

File: packages/flutter/lib/src/rendering/sliver_padding.dart [hunk 4]
```diff
@@ -346,6 +297,82 @@ class RenderSliverPadding extends RenderSliver with RenderObjectWithChildMixin<R
...
+    RenderSliver child,
+  }) : assert(padding != null),
+       assert(padding.isNonNegative),
+       _padding = padding,
+       _textDirection = textDirection {
+    this.child = child;
+  }
+
+  @override
+  EdgeInsets resolvedPadding;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_padding.dart]: Can you turn this into a private variable with a public getter to ensure that the value cannot be changed from the outside?

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 5]
```diff
@@ -1055,6 +1055,41 @@ class SliverFillViewport extends SliverMultiBoxAdaptorWidget {
   /// the viewport in the main axis.
   final double viewportFraction;
 
+  /// The delegate that provides the children for this widget.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: Maybe use a macro instead of repeating this text from SliverMultiBoxAdaptorWidget?

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 6]
```diff
@@ -1067,6 +1102,60 @@ class SliverFillViewport extends SliverMultiBoxAdaptorWidget {
...
+    final double paddingValue = constraints.viewportMainAxisExtent * viewportFraction;
+    switch (constraints.axis) {
+      case Axis.horizontal:
+        return EdgeInsets.symmetric(horizontal: paddingValue);
+      case Axis.vertical:
+        return EdgeInsets.symmetric(vertical: paddingValue);
+    }
+
+    assert(false, 'Unreachable');
+    return EdgeInsets.symmetric(vertical: paddingValue);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: return EdgeInsets.zero?

File: packages/flutter/test/widgets/page_view_test.dart [hunk 7]
```diff
@@ -601,6 +600,88 @@ void main() {
       expect(tester.getTopLeft(find.text('Hawaii')), const Offset(-(4 - 1) * 800 / 2, 0));
   });
 
+  // Regression test for https://github.com/flutter/flutter/issues/45096.
```
Comment (goderbauer) [inline packages/flutter/test/widgets/page_view_test.dart]: nit: I believe our style is to make this the first line inside the test body.

File: packages/flutter/test/widgets/page_view_test.dart [hunk 8]
```diff
@@ -601,6 +600,88 @@ void main() {
...
+  testWidgets(
+    'PageView large viewportFraction can scroll and to the last page and snap',
```
Comment (goderbauer) [inline packages/flutter/test/widgets/page_view_test.dart]: nit: there seems to be an extra "and" in this sentence?

File: packages/flutter/test/widgets/page_view_test.dart [hunk 9]
```diff
@@ -601,6 +600,88 @@ void main() {
...
+      expect(tester.getCenter(find.text('0')), const Offset(400, 300));
+
+      controller.jumpToPage(2);
+      await tester.pump();
+      await tester.pumpAndSettle();
+
+      expect(tester.getCenter(find.text('2')), const Offset(400, 300));
+  });
+
+  testWidgets(
```
Comment (goderbauer) [inline packages/flutter/test/widgets/page_view_test.dart]: Is there an issue that you could mention here for which this is the regression test?

**Review by goderbauer — APPROVED** [review]
LGTM after comments are resolved.

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 10]
```diff
@@ -1067,6 +1102,60 @@ class SliverFillViewport extends SliverMultiBoxAdaptorWidget {
...
+  set viewportFraction(double newValue) {
+    assert(newValue != null);
+    if (_viewportFraction == newValue)
+      return;
+    _viewportFraction = newValue;
+    markNeedsLayout();
+  }
+
+  @override
+  EdgeInsets get resolvedPadding {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: I wonder if its beneficial to performance to cache the value like we do in RenderSliverPadding?

File: packages/flutter/lib/src/widgets/sliver.dart (hunk 6 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/sliver.dart]: The change is no longer necessary because the logic is moved to `_resolve`. But I wonder what the benefits of returning `EdgeInsets.zero` are?
