### PR TITLE
Fix DraggableScrollableSheet crash when switching out scrollables

### LINKED ISSUE #105469: DraggableScrollableSheet.snap throws for multiple ScrollPositions attached
Internal bug: b/234838047

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on button

**Expected results:** 

The views animate from one to the other.

**Actual results:** 

An assertion is thrown.

`ScrollController attached to multiple scroll views.`

This is because during the animation, the DraggableScrollableSheet tries to access the ScrollPosition through the ScrollController - but more than one position is attached. This appears to be caused by a post frame callback that is triggered by `snap` being true.

https://github.com/flutter/flutter/blob/c181e450c8dfa0080626d7572753b9c85727c0a2/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L696

It may be that there is a condition we are not accounting for when initiating the snap.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Draggable Bug'),
    );
  }
}

class View1 extends StatelessWidget {
  View1({required this.next});
  final void Function() next;

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        ElevatedButton(
          onPressed: next,
          child: Text('switch to View2'),
        ),
        Container(
          height: 400,
          color: Colors.blue,
        ),
      ],
    );
  }
}

class View2 extends StatelessWidget {
  View2({required this.next});
  final void Function() next;
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        ElevatedButton(
          onPressed: next,
          child: Text('switch to View1'),
        ),
        Container(
          height: 400,
          color: Colors.red,
        ),
      ],
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var s = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: DraggableScrollableSheet(
            initialChildSize: 0.25,
            minChildSize: 0.25,
            snap: true,
            snapSizes: const [0.25, 0.5, 1.0],
            builder: (context, scrollController) {
              return PrimaryScrollController(
                controller: scrollController,
                child: AnimatedSwitcher(
                  duration: const Duration(milliseconds: 500),
                  child: (s % 2 == 0)
                      ? View1(
                          next: () {
                            setState(() {
                              ++s;
                            });
                          },
                        )
                      : View2(
                          next: () {
                            setState(() {
                              ++s;
                            });
                          },
                        ),
                ),
              );
            },
          ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1119, on macOS 12.4 21F79 darwin-x64, locale en)
    • Flutter version 3.1.0-0.0.pre.1119 at /Users/katelovett/_github/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 1b2ee411aa (6 hours ago), 2022-06-06 07:55:09 -0700
    • Engine revision 4e42059e16
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio with
      Blaze.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ UE (stable).app
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7371

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • Piinks Pro (mobile)                 • 00008110-000444E03C2A801E            • ios
      • iOS 15.5 19F77
    • iPhone SE (3rd generation) (mobile) • 4E826BB1-B283-403A-8E94-8574FD7DA7D2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64
      • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript
      • Google Chrome 102.0.5005.61
    ! Error: Piinks Pro is busy: Fetching debug symbols for Piinks Pro. Xcode will continue when
      Piinks Pro is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

I am not sure what the expected behavior is here regarding snap in this case where more than one position is attached
- should all positions snap?
- should none?
- should we throw a more informative error message, and if so how should the user resolve this?

This snap logic was added in #90354 by @caseycrogers 
@dnfield and @xu-baolin may also know what the expected behavior here is.

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/105469

This accounts for when there is more than one position is attached to the scroll controller, and only triggers a snap when appropriate.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 1]
```diff
@@ -631,7 +631,24 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
...
+      // this runs-we can't use the previous extent's available pixels as it may
+      // have changed when the widget was updated.
+      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
+        for (int index = 0; index < _scrollController.positions.length; index++) {
+          final _DraggableScrollableSheetScrollPosition position =
+            _scrollController.positions.elementAt(index) as _DraggableScrollableSheetScrollPosition;
+          position.goBallistic(0);
+        }
+      });
+    }
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:651]: nit: _replacedExtent is only used here. I think it'd make sense to either inline the function here or to keep all this logic in the function.

**Comment by Piinks** [comment]
I am still working with the customer on this to ensure their issue is resolved, marking WIP for now

**Comment by Piinks** [comment]
@dnfield I've cleaned this up and confirmed with the customer that this does resolve their issue. Can you PTAL when you have a chance? Thanks!

**Review by dnfield — APPROVED** [review]

**Review by xu-baolin — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
> * The status or check suite [tree status luci-flutter](https://flutter-dashboard.appspot.com/#/build) has failed. Please fix the issues identified (or deflake) before re-applying this label.

@keyonghan this is a bug. The auto submit bot should not be removing the label for this check.
