### PR TITLE
[a11y][android] Set new CheckState APIs for android API 36 

### LINKED ISSUE #181321: [a11y][Android] Checkbox and Switch state changes are not announced on Android 16 (SDK 36)
### Steps to reproduce

1. Build an app that features checkboxes and/or switches
2. Run it on a device running Android 16 (SDK 36)
3. Enable TalkBack
4. Observe the behavior of toggling checkboxes and switches

### Expected results

Checkboxes should announce "checked" or "unchecked" when toggled. Switches should announce "on" or "off" when toggled.

### Actual results

Nothing is announced. On Android 15 (SDK 35) and older versions, announcements work correctly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _checked = false;
  bool _toggled = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: ListView(
        children: [
          Text('Checkbox is ${_checked ? 'checked' : 'unchecked'}.'),
          CheckboxListTile(
            title: Text('Checkbox'),
            value: _checked,
            onChanged: (value) {
              if (value == null) return;
              setState(() {
                _checked = value;
              });
            },
          ),
          Text('Switch is ${_toggled ? 'toggled' : 'untoggled'}.'),
          SwitchListTile(
            title: Text('Switch'),
            value: _toggled,
            onChanged: (value) {
              setState(() {
                _toggled = value;
              });
            },
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

* Video on an older version of Android: https://github.com/user-attachments/assets/3c77478e-dd53-4b7f-8633-2a7cebc2bed9
* Video on Android 36: https://github.com/user-attachments/assets/437893c4-f9b2-4ecd-a6bd-2a10c22ff122

</details>

### Logs

N/A

### Flutter Doctor output

N/A, google internal client

### PR DESCRIPTION
**Pull request by hannah-hyj**
android API 36 has some new API for Check state
https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#setChecked(boolean) 

https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#setChecked(int) 

 we need to set them so it will announce the states correctly.
fix https://github.com/flutter/flutter/issues/181321 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 1]
```diff
@@ -1121,6 +1121,20 @@ public AccessibilityNodeInfo createAccessibilityNodeInfo(int virtualViewId) {
...
+            semanticsNode.hasFlag(Flag.IS_CHECKED)
+                ? AccessibilityNodeInfo.CHECKED_STATE_TRUE
+                : AccessibilityNodeInfo.CHECKED_STATE_FALSE);
+      } else if (hasToggledState) {
+        result.setChecked(
+            semanticsNode.hasFlag(Flag.IS_TOGGLED)
+                ? AccessibilityNodeInfo.CHECKED_STATE_TRUE
+                : AccessibilityNodeInfo.CHECKED_STATE_FALSE);
+      }
+    }
```
[the remark this answers is not in the document]
Comment (hannah-hyj) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: nice catch

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 2]
```diff
@@ -1121,6 +1121,20 @@ public AccessibilityNodeInfo createAccessibilityNodeInfo(int virtualViewId) {
     }
     result.setSelected(semanticsNode.hasFlag(Flag.IS_SELECTED));
 
+    // Starting on API level 36. setChecked takes int instead.
```
Comment (chunhtai) [inline engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: do we need to set them to true false if api < 36?

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 3]
```diff
@@ -1121,6 +1121,20 @@ public AccessibilityNodeInfo createAccessibilityNodeInfo(int virtualViewId) {
...
+    if (Build.VERSION.SDK_INT >= API_LEVELS.API_36) {
+      if (hasCheckedState) {
+        result.setChecked(
+            semanticsNode.hasFlag(Flag.IS_CHECKED)
+                ? AccessibilityNodeInfo.CHECKED_STATE_TRUE
```
Comment (chunhtai) [inline engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: looking at the new api, there is also CHECKED_STATE_PARTIAL, which i think also translate to https://api.flutter.dev/flutter/semantics/SemanticsProperties/mixed.html

I think we should also consider setting this state

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java [hunk 4]
```diff
@@ -2426,6 +2426,54 @@ public void itAddsCollectionItemInfoAPI33() {
...
+  @Test
+  public void itSetsCheckedStateBasedOnFlagsCorrectly() {
+    AccessibilityBridge accessibilityBridge = setUpBridge();
+
+    TestSemanticsNode node = new TestSemanticsNode();
+    TestSemanticsUpdate testSemanticsUpdate = node.toUpdate();
+    testSemanticsUpdate.sendUpdateToBridge(accessibilityBridge);
+
+    AccessibilityNodeInfo nodeInfo = accessibilityBridge.createAccessibilityNodeInfo(0);
+    assertEquals(AccessibilityNodeInfo.CHECKED_STATE_UNDEFINED, nodeInfo.getChecked());
```
Comment (chunhtai) [inline engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]: I can't find CHECKED_STATE_UNDEFINED in the android doc, do you know where this is documented?

Comment (hannah-hyj) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]: i generated the test using AI and it's an illusion 😅

Comment (hannah-hyj) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]: removed

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java (hunk 3 above)
Comment (hannah-hyj) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: added

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java (hunk 2 above)
Comment (hannah-hyj) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: yeah i think so

**Review by chunhtai — APPROVED** [review]
LGTM
