### PR TITLE
Exclude arm64 from iOS app archs if unsupported by plugins

### LINKED ISSUE #85713: When plugins do not support ARM iOS simulators, the app fails to build
Plugin tree closed.
https://cirrus-ci.com/task/6631197179641856
```
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    ld: building for iOS Simulator, but linking in object file built for iOS, file '/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/packages/google_maps_flutter/google_maps_flutter/example/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework/GoogleMapsBase' for architecture arm64
```
Likely related to https://github.com/flutter/flutter/pull/85642

### PR DESCRIPTION
**Pull request by jmagman**
If any plugins declare they do not support arm64 simulators, also mark the entire iOS app as not supporting arm64 simulators to avoid compilation failures.  This will cause the app to run in x64 Rosetta translation mode.

Parse the output of
```
xcrun xcodebuild -alltargets -sdk iphonesimulator -project ios/Pods/Pods.xcodeproj -showBuildSettings
```

Plugins will be expected to add this to their podspec:

```ruby
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```
google_maps_flutter: https://github.com/flutter/flutter/issues/87242
google_sign_in: https://github.com/flutter/flutter/issues/87243

Fixes https://github.com/flutter/flutter/issues/85713

### CODE REVIEW

**Comment by orestesgaolin** [comment]
Will fix https://github.com/flutter/flutter/issues/87201 as well

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 1]
```diff
@@ -146,6 +146,25 @@ class IosProject extends FlutterProjectPlatform implements XcodeBasedProject {
   /// Xcode workspace shared workspace settings file for the host app.
   File get xcodeWorkspaceSharedSettings => xcodeWorkspaceSharedData.childFile('WorkspaceSettings.xcsettings');
 
+  /// Do all plugins support arm64 simulators to run natively on an ARM Mac?
+  bool get pluginsSupportArmSimulator {
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/xcode_project.dart:150]: Optional nit: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#getters-feel-faster-than-methods
Parsing a file from disk is probably on the heavy side for a getter

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 2]
```diff
@@ -146,6 +146,25 @@ class IosProject extends FlutterProjectPlatform implements XcodeBasedProject {
...
+        .childFile('project.pbxproj');
+    if (!podProject.existsSync()) {
+      // No plugins.
+      return true;
+    }
+    final String podProjectContents = podProject.readAsStringSync();
+    // Quick and dirty way to see if any plugins or their dependencies exclude arm64 simulators
+    // as a valid architecture, usually because a binary is missing that slice.
+    // Example: "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 i386";
+    // NOT: "EXCLUDED_ARCHS[sdk=iphoneos*]" = "arm64 i386";
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/xcode_project.dart:163]: This one (sdk=iphoneos) is probably worth having an explicit test (making sure it doesn't match).

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/xcode_project.dart:163]: Done.

**Comment by jmagman** [comment]
Ugh, this isn't going to work, the plugin build settings from the podspec are generated into an `xcconfig`, not the Pods project (I was testing this incorrectly).

**Comment by jmagman** [comment]
I rewrote this to call `xcodebuild` instead of parsing the Xcode project.

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart [hunk 3]
```diff
@@ -676,10 +678,189 @@ Information about project "Runner":
...
+    group('arm simulator', () {
+      FakeProcessManager fakeProcessManager;
+      XcodeProjectInterpreter xcodeProjectInterpreter;
+
+      setUp(() {
+        fakeProcessManager = FakeProcessManager.empty();
+        xcodeProjectInterpreter = XcodeProjectInterpreter.test(processManager: fakeProcessManager);
+      });
+
+      testUsingContext('does not arm64 simulator when supported by all plugins', () async {
```
Comment (stuartmorgan) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:690]: This test title accidentally the verb :)

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart [hunk 4]
```diff
@@ -676,10 +678,189 @@ Information about project "Runner":
...
+                '-arm64e',
+                'xcrun',
+                'xcodebuild',
+                '-alltargets',
+                '-sdk',
+                'iphonesimulator',
+                '-project',
+                podXcodeProject.path,
+                '-showBuildSettings',
+              ],
```
Comment (stuartmorgan) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:825]: Optional: you've got a lot of copies of this very long command; it might be helpful to have a little utility method that takes output (and an optional exit code) and builds the `FakeCommand`, to make the tests a bit less verbose and easier to update if the argument list needs to be changed slightly in the future.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM with typo fix

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:811]: I put the `hw.optional.arm64: 1` command into a constant which cleaned it up a bit.  Generally I prefer seeing the "important" command inline in the test to keeping tests DRY.  That's just preference though. Fortunately the test will start failing if the arguments ever change, so it's usually really easy to update even in a few places.

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart]: Eagle eye.

**Comment by jmagman** [comment]
The tree is green, not sure why the `luci-flutter` has been red so long.  Merging...
