### PR TITLE
Fixes IgnorePointer and AbsorbPointer to only block user interactions…

### LINKED ISSUE #37162: a11y: disabled textfield not announced as textfield
```dart
TextField(
   enabled: false,
),
```

On Android with TalkBack enabled this should be announced as a disabled editbox. It is currently not announced at all. (It looks like the TextField flag is missing from the semantics tree when the TextField is disabled).

I haven't tested on iOS (and I am not 100% of what the native behavior is there), but I assume it's also broken there.

/cc @dnfield for a11y
/cc @chunhtai @justinmc for TextFields

### LINKED ISSUE #59402: TextField semantics are gone when being disabled
b/158725443
b/239596152

This might be WAI but it is inconsistent.

Dropdown buttons still have a Semantic widget associated with them when they are disabled but it seems we remove the Semantic widget when TextField is disabled.

### PR DESCRIPTION
**Pull request by chunhtai**
… in a11y

Fixes https://github.com/flutter/flutter/issues/59402
Fixes https://github.com/flutter/flutter/issues/37162

migration guide: https://github.com/flutter/website/pull/8312 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -1800,6 +1805,22 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
     _markDirty();
   }
 
+  /// Whether this user can interact with this node in assistive technologies.
+  ///
+  /// This node can still be receive accessibility focus even if this is true.
+  /// Setting this true prevents user from activating pointer related
+  /// [SemanticsAction]s, such as [SemanticsAction.tap] or
+  /// [SemanticsAction.longPress].
+  bool get isUserInteractionsBlocked => _isUserInteractionsBlocked;
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart:1814]: was curious if there is a better name

File: packages/flutter/lib/src/widgets/basic.dart [hunk 2]
```diff
@@ -6643,27 +6642,28 @@ class RepaintBoundary extends SingleChildRenderObjectWidget {
...
   /// Creates a widget that is invisible to hit testing.
   ///
-  /// The [ignoring] argument must not be null. If [ignoringSemantics] is null,
-  /// this render object will be ignored for semantics if [ignoring] is true.
+  /// The [ignoring] and [ignoringSemantics] arguments must not be null.
   const IgnorePointer({
     super.key,
     this.ignoring = true,
-    this.ignoringSemantics,
+    this.ignoringSemantics = false,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/basic.dart:6649]: I think the `ignoringSemantics` was a workaround to provide people a way to get the semanitcs back if ignoring = true, but I am not sure.

If so,  should we deprecate this and just ask developer to use ExcludeSemantics?

**Comment by goderbauer** [comment]
Looks like this is failing a lot of checks.

**Comment by chunhtai** [comment]
Sorry for the test failure. I fixed the test, this is ready for review

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -3238,13 +3239,15 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
...
     required bool mergeIntoParent,
+    required bool blockUserInteractions,
   }) {
     assert(!_needsLayout, 'Updated layout information required for $this to calculate semantics.');
 
     final SemanticsConfiguration config = _semanticsConfiguration;
     bool dropSemanticsOfPreviousSiblings = config.isBlockingSemanticsOfPreviouslyPaintedNodes;
 
     final bool producesForkingFragment = !config.hasBeenAnnotated && !config.isSemanticBoundary;
+    final bool childrenBlockUserInteractions = blockUserInteractions || config.isBlockingUserInteractions;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:3250]: nit: I believe this is kinda the other way around, right? If this is true, interactions of children will be blocked. Maybe rename to `blockChildInteractions`?

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart:1814]: Maybe: `blocksUserActions` or `blocksSemanticsActions` (in general, maybe we should stick with the "actions" terminology throughout this PR to make it clear that this relates to SemanticsActions)?

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 4]
```diff
@@ -3337,6 +3373,13 @@ class SemanticsConfiguration {
     _isSemanticBoundary = value;
   }
 
+  /// Whether to block user interactions for the semantics subtree.
+  ///
+  /// Setting this true prevents user from activating pointer related
+  /// [SemanticsAction]s, such as [SemanticsAction.tap] or
+  /// [SemanticsAction.longPress].
+  bool isBlockingUserInteractions = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3381]: Random thought: Is there ever a use case for only blocking certain actions? I wonder if this should just take a list of blocked actions (that we internally translate to a bitMask right away) and provide a const value containing all block-able actions that the use cases in this PR would use. Would be a little more flexible, but not sure how useful that is...

**Review by goderbauer — COMMENTED** [review]
Thanks for looking into this long-standing issue!

File: packages/flutter/lib/src/widgets/basic.dart [hunk 5]
```diff
@@ -6636,15 +6632,31 @@ class RepaintBoundary extends SingleChildRenderObjectWidget {
...
 ///
+/// ## Semantics
+///
+/// Using this widget may also affect how semantics subtree underneath this
+/// widget is collected.
+///
+/// {@template flutter.widgets.IgnorePointer.Semantics}
+/// If [ignoringSemantics] is true, the semantics subtree is dropped.
+///
+/// If [ignoringSemantics] is false, the semantics subtree is collected as
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/basic.dart:6643]: Yes, the SemanticsDebugger want to covert all pointer action into semantics action and dispatch it to the subtree. It does this by adding its own gesture recognizer and add the ignore pointer to the subtree. Since it needs to send the semantics action to the subtree, so it don't want those semantics action to be blocked.

Thus it needs
IgnorePointer(
ignoringSemantics: false
)

I think WidgetInspector has the same use case, it want to block pointer event to the subtree but still display the full semantics tree when user inspecting the widget.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 6]
```diff
@@ -1800,6 +1805,22 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
     _markDirty();
   }
 
+  /// Whether this user can interact with this node in assistive technologies.
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:1808]: If SemanticsConfiguration.isblockingUserInteraction is true. All semantics nodes below the subtree will have this field set to true. Thus the documentation here is valid that this boolean doesn't have to represent the behavior for other semantics node.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 7]
```diff
@@ -68,6 +68,11 @@ typedef SemanticsUpdateCallback = void Function(ui.SemanticsUpdate update);
 /// value.
 typedef ChildSemanticsConfigurationsDelegate = ChildSemanticsConfigurationsResult Function(List<SemanticsConfiguration>);
 
+final int _kSystemInteractions = SemanticsAction.didGainAccessibilityFocus.index
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:71]: how about _kUnblockedUserActions? I think the name should also make sense of what kind of action it is blocking.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 8]
```diff
@@ -68,6 +68,11 @@ typedef SemanticsUpdateCallback = void Function(ui.SemanticsUpdate update);
...
+  | SemanticsAction.didLoseAccessibilityFocus.index
+  | SemanticsAction.customAction.index;
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:73]: I think custom actions are usually non pointer related action

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 9]
```diff
@@ -2749,7 +2785,7 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
       properties.add(DiagnosticsProperty<Rect>('rect', rect, description: description, showName: false));
     }
     properties.add(IterableProperty<String>('tags', tags?.map((SemanticsTag tag) => tag.name), defaultValue: null));
-    final List<String> actions = _actions.keys.map<String>((SemanticsAction action) => describeEnum(action)).toList()..sort();
+    final List<String> actions = _actions.keys.map<String>((SemanticsAction action) => '${describeEnum(action)}${_debugIsActionBlocked(action) ? '(BLOCKED)' : ''}').toList()..sort();
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:2788]: no, will add

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 10]
```diff
@@ -4586,7 +4630,7 @@ class SemanticsConfiguration {
     if (other == null || !other.hasBeenAnnotated || !hasBeenAnnotated) {
       return true;
     }
-    if (_actionsAsBits & other._actionsAsBits != 0) {
+    if (_effectiveActionsAsBits & other._effectiveActionsAsBits != 0) {
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:4633]: yeah. I think I may be overfitting the merging logic. It makes sense that we don't try to merge nodes based on effective actions. will fix

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 11]
```diff
@@ -4624,10 +4668,17 @@ class SemanticsConfiguration {
...
+    if (child.isBlockingUserInteractions) {
+      child._actions.forEach((SemanticsAction key, SemanticsActionHandler value) {
+        if (_kSystemInteractions & key.index > 0) {
+          _actions[key] = value;
+        }
+      });
+    } else {
+      _actions.addAll(child._actions);
+    }
+    _actionsAsBits |= child._effectiveActionsAsBits;
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:4680]: I don't think so. If a parent merge a child that blocks userinteraction for its subtree, that doesn't mean the parent want to block its own userinteraction

For example

Semantics(
  ontap: () {},
  child: IgnorePointer(...)
)

the ontap should still be valid.

Let me know if I miss something

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:3381]: I haven't found use cases other than blocking pointer related action. We can add a new api to block a list instead of just hardcoded actions in the future if we have more use cases, and then we can reimplment this boolean to use that API under the hood.

I was suspecting this may be an one-off case, that is why I go with hardcoded actions.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 12]
```diff
@@ -4624,10 +4668,17 @@ class SemanticsConfiguration {
...
-    _actions.addAll(child._actions);
+    if (child.isBlockingUserInteractions) {
+      child._actions.forEach((SemanticsAction key, SemanticsActionHandler value) {
+        if (_kSystemInteractions & key.index > 0) {
+          _actions[key] = value;
+        }
+      });
+    } else {
+      _actions.addAll(child._actions);
+    }
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:4679]: I added this filtering because I was trying to support use case where merging child that has same action but blocked. I guess that is no longer the case.

Even without that requirement, why do we want to add a action to the map that will be blocked anyway?

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:1814]: I agree to change this to "Actions". but I may keep it past tense since it is already a done deal in SemanticsNode level. Present tense kinda implies it will do something that it hasn't done.

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart:73]: I forget how custom actions are exposed in TalkBack and VoiceOver. How do users trigger these? It seems odd that they are still allowed, though? Would probably be good to look at some use cases of custom action and decide based on that whether it would make more sense to allow or disallow these. (If it is unclear whether they should be blocked in all cases maybe we need to make it configurable after all which actions are blocked, at least on the SemanticsConfiguration level).

[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart:73]: Actually, I thought these expose actions that non-a11y-users would usually trigger via pointers. For example to delete an entry in a list, etc.

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 12 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart]: It's fine to do that. I was just thinking if we don't have to do it what's the point of implementing all this extra logic?

File: packages/flutter/lib/src/rendering/object.dart [hunk 13]
```diff
@@ -3220,6 +3220,7 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
     }
     final _SemanticsFragment fragment = _getSemanticsForParent(
       mergeIntoParent: _semantics?.parent?.isPartOfNodeMerging ?? false,
+      blockUserInteractions: _semantics?.isUserActionsBlocked ?? false,
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:3223]: UserActions are plural, so it would be `areUserActionsBlocked`.

Also, can we standardize on either UserActions or UserInteractions?

File: packages/flutter/lib/src/rendering/object.dart [hunk 14]
```diff
@@ -4361,13 +4366,14 @@ class _IncompleteSemanticsFragment extends _InterestingSemanticsFragment {
 class _SwitchableSemanticsFragment extends _InterestingSemanticsFragment {
   _SwitchableSemanticsFragment({
     required bool mergeIntoParent,
+    required bool blockUserInteractions,
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:4369]: nit: it is a little odd that this constructor takes blockUserInteractions as a param and then just turns around to modify another param. Should we just edit the config before it is passed here>

File: packages/flutter/lib/src/widgets/basic.dart [hunk 15]
```diff
@@ -7030,12 +7090,29 @@ class Semantics extends SingleChildRenderObjectWidget {
   /// an [ExcludeSemantics] widget and then another [Semantics] widget.
   final bool excludeSemantics;
 
+  /// Whether to block user interactions for the rendering subtree.
+  ///
+  /// Setting this to true will prevent user from interacting with this
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7095]: user -> users

File: packages/flutter/lib/src/widgets/basic.dart [hunk 16]
```diff
@@ -7030,12 +7090,29 @@ class Semantics extends SingleChildRenderObjectWidget {
...
+  /// rendering object and its subtree through pointer-related
+  /// [SemanticsAction]s in assistive technologies.
+  ///
+  /// This [SemanticsNode] created from this rendering object is still focusable
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7099]: This [SemanticsNode] -> The [SemanticsNode]

Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7099]: Also, this doc is on a widget, not rendering object.

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/basic.dart:7099]: Also below, where rendering object is mentioned again.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 17]
```diff
@@ -7030,12 +7090,29 @@ class Semantics extends SingleChildRenderObjectWidget {
...
+  /// by assistive technologies. Only pointer-related [SemanticsAction]s, such as
+  /// [SemanticsAction.tap] or its friends, are blocked.
+  ///
+  /// If this rendering object is merged into a parent semantics node, only the
+  /// [SemanticsAction]s originated from this rendering object and below
+  /// are blocked. [SemanticsAction]s in the parent semantics node originated
+  /// from other sources are still allowed.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7106]: what does "originated from other sources" mean?

File: packages/flutter/lib/src/widgets/basic.dart [hunk 18]
```diff
@@ -7030,12 +7090,29 @@ class Semantics extends SingleChildRenderObjectWidget {
...
+  ///
+  /// Setting this to true will prevent user from interacting with this
+  /// rendering object and its subtree through pointer-related
+  /// [SemanticsAction]s in assistive technologies.
+  ///
+  /// This [SemanticsNode] created from this rendering object is still focusable
+  /// by assistive technologies. Only pointer-related [SemanticsAction]s, such as
+  /// [SemanticsAction.tap] or its friends, are blocked.
+  ///
+  /// If this rendering object is merged into a parent semantics node, only the
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7103]: I am actually not 100% clear on how merging works here. If I have a parent SemanticsConfig with a tap handler and there are two child semantics configs: One of them has a longpress handler and the other one sets blockUserInteractions. These will all get implicitly merged into a single node, right? What actions are now allowed on that node?

Also, if I force merge (using MergeSemantics) a SemanticsNode with blockUserInteractions set into another node with an action handler, will the resulting node have its action blocked or not?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/basic.dart:7103]: > If I have a parent SemanticsConfig with a tap handler and there are two child semantics configs: One of them has a longpress handler and the other one sets blockUserInteractions. These will all get implicitly merged into a single node, right? What actions are now allowed on that node?

Only the action in blockUserInteractions child will be block and drop from the merging. Soe the onTap on parent and the onLongPress on the child will still be merged into the resulting node.

> if I force merge (using MergeSemantics) a SemanticsNode with blockUserInteractions set into another node with an action handler, will the resulting node have its action blocked or not?

The resulting node will not have its actions blocked, the actions in the node with blockUserInteractions will be dropped.

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/basic.dart:7103]: Okay, both behave the same here, that's good. Thanks for the clarification!

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/basic.dart:7103]: (I can't remember, do you have tests in place for both of these scenarios to make sure that this doesn't break?)

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/basic.dart]: yes, the test in `flutter/packages/flutter/test/widgets/semantics_test.dart`

**Comment by goderbauer** [comment]
Looks like some tests are still failing?

File: packages/flutter/lib/src/widgets/basic.dart [hunk 19]
```diff
@@ -6706,6 +6735,22 @@ class IgnorePointer extends SingleChildRenderObjectWidget {
 /// ** See code in examples/api/lib/widgets/basic/absorb_pointer.0.dart **
 /// {@end-tool}
 ///
+/// ## Semantics
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:6738]: nit: blank line after this heading.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 20]
```diff
@@ -7030,12 +7090,48 @@ class Semantics extends SingleChildRenderObjectWidget {
   /// an [ExcludeSemantics] widget and then another [Semantics] widget.
   final bool excludeSemantics;
 
+  /// Whether to block user interactions for the rendering subtree.
+  ///
+  /// Setting this to true will prevent users from interacting with this
+  /// rendering object and its subtree through pointer-related
+  /// [SemanticsAction]s in assistive technologies.
+  ///
+  /// This [SemanticsNode] created from this widget is still focusable
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7099]:
```suggestion
  /// The [SemanticsNode] created from this widget is still focusable
```

File: packages/flutter/lib/src/widgets/basic.dart [hunk 21]
```diff
@@ -7030,12 +7090,48 @@ class Semantics extends SingleChildRenderObjectWidget {
...
+  ///       blockUserActions: true,
+  ///       onLongPress: _myLongPress,
+  ///       child: const Text('label'),
+  ///     ),
+  ///   );
+  /// }
+  /// ```
+  ///
+  /// The result semantics node will still have `_myTap`, but the `_myLongPress`
+  /// will be blocked.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7125]: Thanks for adding the example!

File: packages/flutter/lib/src/widgets/basic.dart [hunk 22]
```diff
@@ -7030,12 +7090,48 @@ class Semantics extends SingleChildRenderObjectWidget {
   /// an [ExcludeSemantics] widget and then another [Semantics] widget.
   final bool excludeSemantics;
 
+  /// Whether to block user interactions for the rendering subtree.
+  ///
+  /// Setting this to true will prevent users from interacting with this
+  /// rendering object and its subtree through pointer-related
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:7096]: "this rendering object": This is not a rendering object. Maybe say "the rendering object configured by this widget"

File: packages/flutter/lib/src/widgets/basic.dart [hunk 23]
```diff
@@ -6636,18 +6632,39 @@ class RepaintBoundary extends SingleChildRenderObjectWidget {
 /// ** See code in examples/api/lib/widgets/basic/ignore_pointer.0.dart **
 /// {@end-tool}
 ///
+/// ## Semantics
+///
+/// Using this widget may also affect how semantics subtree underneath this
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:6637]:
```suggestion
/// Using this widget may also affect how the semantics subtree underneath this
```

**Comment by chunhtai** [comment]
ah that is the semantics handle dispose issue, will fix

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 24]
```diff
@@ -3337,6 +3372,21 @@ class SemanticsConfiguration {
     _isSemanticBoundary = value;
   }
 
+  /// Whether to block pointer related user actions for the rendering subtree.
+  ///
+  /// Setting this to true will prevent users from interacting with this
+  /// rendering object and its subtree through pointer-related
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3378]: nit: this is not a rendering object. Maybe say "with the rendering object that produces this semantics configuration"

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 25]
```diff
@@ -3337,6 +3372,21 @@ class SemanticsConfiguration {
...
+  /// [SemanticsAction]s in assistive technologies.
+  ///
+  /// The [SemanticsNode] created from this rendering object is still focusable
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3381]: same: this is not a rendering object

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 26]
```diff
@@ -3337,6 +3372,21 @@ class SemanticsConfiguration {
...
+  /// by assistive technologies. Only pointer-related [SemanticsAction]s, such as
+  /// [SemanticsAction.tap] or its friends, are blocked.
+  ///
+  /// If this rendering object is merged into a parent semantics node, only the
+  /// [SemanticsAction]s from this rendering object and the rendering objects in
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3386]: same

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 27]
```diff
@@ -1800,6 +1804,22 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
     _markDirty();
   }
 
+  /// Whether this user can interact with this node in assistive technologies.
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1807]:
```suggestion
  /// Whether the user can interact with this node via assistive technologies.
```

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 28]
```diff
@@ -1800,6 +1804,22 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
...
+  ///
+  /// This node can still be receive accessibility focus even if this is true.
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1809]:
```suggestion
  /// This node can still receive accessibility focus even if this is true.
```

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 29]
```diff
@@ -1800,6 +1804,22 @@ class SemanticsNode extends AbstractNode with DiagnosticableTreeMixin {
...
+  /// Setting this true prevents user from activating pointer related
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:1810]:
```suggestion
  /// Setting this true prevents the user from activating pointer related
```

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart:73]: This is the only remaining open question on the PR. For me, if I have an interface where I can delete a ListItem by swiping right/left on it and I expose this action as a custom action for a11y users, I would expect it gets blocked when I use an IgnorePointer. Everything else would be surprising. I can't think of a use case where I would still want custom actions to be allowed. Do you have one? If so, we may need to make this configurable if it can go both ways.

**Review by goderbauer — COMMENTED** [review]
I believe the only thing left to figure out on this PR are the custom actions.

**Comment by chunhtai** [comment]
I included custom actions to the blocked actions

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
There are ~100 internal test failures most of them are due to the workaround to add label to disabled textfield, will need to working on g3fix

**Comment by chunhtai** [comment]
some more updates, still working on resolving internal test failures

**Comment by chunhtai** [comment]
some of the test failures are due to https://github.com/flutter/engine/pull/40146, waiting for it to merge

**Comment by Hixie** [comment]
I just ran into this deprecation in the documentation for `SliverIgnorePointer`, and it was quite confusing, because there's no context as to why I would have wanted to use this feature, why it's deprecated, or what it means to "Create a custom sliver ignore pointer widget instead" or why that would be better than having this feature. Since three quarters of the widget's documentation appears to be about this feature, it feels like the feature was quite important, and so its removal is surprising to the reader.

The migration guide doesn't really illuminate the reader, either. It doesn't provide any background regarding what the feature was, why it was normally used, or why you might no longer need it, other than "this workaround is no longer needed". However, if the workaround is no longer needed, one would assume the migration is just to remove the use of the property, whereas the migration guide says "consider using ExcludeSemantics instead" and "Consider creating your own custom widget", but there's no explanation as to why one would do either of these things.

It would be great if we could provide significantly more context in the dartdocs and the migration guide for this removal.

cc @chunhtai @goderbauer @sfshaza2

**Comment by Hixie** [comment]
Well presumably we added this feature for a reason. :-)
That's what I would try to include in the explanations.

**Comment by Hixie** [comment]
Stop-gap solution for what problem? That's what we should describe. That problem. And the better solution. :-)

**Comment by chunhtai** [comment]
yes I can definitely explain this in the doc. I will create a pr.
