### PR TITLE
Fix: Assertion failure in RawScrollbarState with dynamic controller assignment

### LINKED ISSUE #172614: Assertion failure in RawScrollbarState when dynamically assigning a controller and setting interactive: true
### Steps to reproduce

1. A stateful widget builds a `Scrollbar`, wrapping its child. This child is expected to contain a `SingleChildScrollView`. Initially, the widget has no scroll controller, so its `Scrollbar` is built with `controller: null`, `thumbVisibility: false` and `interactive: false`.
2. In a next frame, a scroll controller becomes available, so `Scrollbar` is rebuilt with a non-null `controller`, `thumbVisibility: true` and `interactive: true`. The controller is not yet attached at this point, as the descendant `SingleChildScrollView` still has to be rebuilt with the new controller, too.

### Expected results

The scrollbar is now working interactively (i.e. can be used to change the current scroll offset through the provided controller).

### Actual results

The scrollbar is made interactive, as expected, but first an assertion failure is triggered in the `RawScrollbarState` underlying the `Scrollbar` widget:
```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞══════════════════════
The following assertion was thrown while notifying status
listeners for AnimationController:
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController.
This ScrollController should be associated with the ScrollView
that the Scrollbar is being applied to.
When providing your own ScrollController, ensure both the
Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack

The AnimationController notifying status listeners was:
  AnimationController#ab7ae(▶ 0.000)
═════════════════════════════════════════════════════════════════
```
This assertion is checked synchronously at build time, in `RawScrollbarState._debugCheckHasValidScrollPosition`, called from `RawScrollbarState._validateInteractions`, which is a status listener of `RawScrollbarState._fadeOutAnimationController`. This animation controller is started at build time, in `RawScrollbarState.didUpdateWidget`, causing the assertion check to be performed at build time as well. 

There is another assertion to verify the same thing, but that is scheduled as a post-frame-callback (in `RawScrollbarState._debugScheduleCheckHasValidScrollPosition`), when you can more reasonably assume that a controller will have been attached.

On a side note, I'm not sure whether this claim that "A Scrollbar cannot be painted without a ScrollPosition." is true. Painting the scrollbar seems to be based on information from `Scroll(Metrics)Notification`. Maybe complaining about an unattached `ScrollController` could be delayed up to the point where one is really needed: actual scrollbar interaction?

### Code sample

See https://dartpad.dev/d564e246c3fccfe638a7b9b5e0ec9ced. Perform step 2 (the assignment of a scroll controller, `thumbVisibility: true` and `interactive: true`) by flipping the switch at the top.

### Screenshots or Video

_No response_

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.27.3, on macOS 15.5 24F74 darwin-arm64, locale en-US)
    ! Flutter version 3.27.3 on channel [user-branch] at /Users/heinrich.janzing/source/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision c519ee916e (6 months ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    • Android SDK at /Users/heinrich.janzing/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 16.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.101.0)
    • VS Code at /Users/heinrich.janzing/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 138.0.7204.101

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Assertion failure in RawScrollbarState with dynamic controller assignment
fixes: #172614 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 1]
```diff
@@ -1453,11 +1453,11 @@ class RawScrollbarState<T extends RawScrollbar> extends State<T> with TickerProv
       assert(_fadeoutOpacityAnimation.value == 0.0);
       // We do not check for a valid scroll position if the scrollbar is not
       // visible, because it cannot be interacted with.
-    } else if (_effectiveScrollController != null && enableGestures) {
-      // Interactive scrollbars need to be properly configured. If it is visible
-      // for interaction, ensure we are set up properly.
-      assert(_debugCheckHasValidScrollPosition());
     }
+    // Validation is performed only when the user interacts with the scrollbar,
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: I am not sure the method here makes sense then, `_validateInteractions`. Should there be more updates here?

**Review by Piinks — COMMENTED** [review]
Hey @rkishan516 it looks like there are many tests failing currently. Can you take a look?

**Comment by rkishan516** [comment]
> Hey @rkishan516 it looks like there are many tests failing currently. Can you take a look?

Sure, I will fix.

Edit: Will try to pickup by friday or weekend.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Logically, It can be removed.

**Review by Piinks — APPROVED** [review]
LGTM thank you

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 2]
```diff
@@ -1456,6 +1456,14 @@ class RawScrollbarState<T extends RawScrollbar> extends State<T> with TickerProv
     } else if (_effectiveScrollController != null && enableGestures) {
       // Interactive scrollbars need to be properly configured. If it is visible
       // for interaction, ensure we are set up properly.
+      // Don't assert immediately if we're in the middle of updating the widget
+      // as the controller may not be attached yet in that frame
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: super nit: Add a period at the end of this comment.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 3]
```diff
@@ -1456,6 +1456,14 @@ class RawScrollbarState<T extends RawScrollbar> extends State<T> with TickerProv
...
+      if (_fadeoutAnimationController.status == AnimationStatus.forward &&
+          (widget.thumbVisibility ?? false)) {
+        // When thumbVisibility is true and we're animating forward,
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/scrollbar.dart:1463]: super nit: Add a period at the end of this comment.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 4]
```diff
@@ -3635,4 +3635,79 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
...
+
+      await tester.tap(find.text('Enable Scrollbar'));
+      await tester.pumpAndSettle();
+
+      // Verify scrollbar is now working properly and doesn't throw an assertion.
+      final Finder scrollbarFinder = find.byType(RawScrollbar);
+      expect(scrollbarFinder, findsOneWidget);
+      expect(scrollController.offset, 0.0);
+
+      // Test that scrolling works without assertions
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/scrollbar_test.dart]: nit: add period at the end of this comment and the comment below.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 5]
```diff
@@ -3635,4 +3635,79 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
...
+            return Directionality(
+              textDirection: TextDirection.ltr,
+              child: MediaQuery(
+                data: const MediaQueryData(),
+                child: Column(
+                  children: <Widget>[
+                    ElevatedButton(
+                      onPressed: () {
+                        setState(() {
+                          // This reproduces the exact scenario from the issue:
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/scrollbar_test.dart]: nit: maybe this can be:

```
// This reproduces the exact scenario from the linked issue:
// Initially the controller is null, thumbVisibility is false, and interactive is false.
// Then, in the next frame, the controller is non-null, thumbVisibility is true, and interactive is true.
```

**Comment by rkishan516** [comment]
@Renzo-Olivares I have addressed all the comments.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 6]
```diff
@@ -3635,4 +3635,79 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
...
+      // Verify scrollbar is now working properly and doesn't throw an assertion.
+      final Finder scrollbarFinder = find.byType(RawScrollbar);
+      expect(scrollbarFinder, findsOneWidget);
+      expect(scrollController.offset, 0.0);
+
+      // Test that scrolling works without assertions.
+      await tester.drag(find.byType(SingleChildScrollView), const Offset(0.0, -100.0));
+      await tester.pumpAndSettle();
+
+      // Verify the scroll happened
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/scrollbar_test.dart]: nit: period at the end of this comment.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM pending one last comment. Thank you for the contribution!
