### PR TITLE
Fix date picker flickering

### LINKED ISSUE #140311: DatePickerDialog text input causes keyboard to open and close on a 480p Android emulator.
### Steps to reproduce

1. Create an Android emulator with WVGA (480x800hdpi),
2. In system settings, set font size to mini,

Screenshot_1702891450

3. In basic MaterialApp widget, call `showDatePicker`,
4. Switch to input mode.

This issue can be reproduced on iOS too.

### Expected results

A date picker dialog with focused textfield and keyboard displayed.

Screenshot_1702890661

### Actual results

A date picker dialog without textfield and keyboard.

Flutter 3.16.4 :
Screenshot_1702891112

Fluter 3.13.8 :
Screenshot_1702899256

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    const datepickerDemo = 'Date Picker Demo';
    final now = DateTime.now();

    return MaterialApp(
      title: datepickerDemo,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text(datepickerDemo),
        ),
        body: Center(
          child: Builder(
              builder: (context) => ElevatedButton(
                    onPressed: () {
                      showDatePicker(
                        context: context,
                        initialDate: now,
                        firstDate: now,
                        lastDate: now.add(const Duration(days: 365)),
                      );
                    },
                    child: const Text('Show date picker'),
                  )),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

datepicker

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.1.2 23B92 darwin-arm64, locale fr-FR)
    • Flutter version 3.16.4 on channel stable at /Users/manu/fvm/versions/3.16.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (7 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/manu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 120.0.6099.109
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes a `DatePicker` flickering issue observed on some devices with a small display.

### Before

When the date picker input dialog is shown the virtual keyboard opens and reduces the available height. The current logic reacts by removing the picker `TextField`. Because there is no more `TextField` the virtual keyboard is hidden and the available height increases, at that moment the `TextField` is shown again. Due to autofocus the virtual keyboard opens which leads to the removal of the `TextField` and so on.

https://github.com/user-attachments/assets/deb70f2e-1c8b-47a9-9db6-47bc521e4eb7

### After

When there is not enough vertical space for the input date picker dialog, the header is hidden instead of hiding the `TextField`.

https://github.com/user-attachments/assets/14051ee9-3b9a-4467-a4a0-4ee91b4979ea

## Related Issue

Fixes [DatePickerDialog text input causes keyboard to open and close on a 480p Android emulator](https://github.com/flutter/flutter/issues/140311). 

## Tests

Adds 2 tests.

### CODE REVIEW

File: packages/flutter/test/material/date_picker_test.dart [hunk 1]
```diff
@@ -1662,6 +1662,24 @@ void main() {
...
+      tester.view.devicePixelRatio = 1.0;
+
+      // Simulate the portait mode on a device with a small display when the virtual
+      // keyboard is visible.
+      tester.view.viewInsets = const FakeViewPadding(bottom: 1000);
+
+      initialEntryMode = DatePickerEntryMode.input;
+      await prepareDatePicker(tester, (Future<DateTime?> date) async {
+        expect(find.byType(TextField), findsOneWidget);
+      });
```
Comment (TahaTesser) [inline packages/flutter/test/material/date_picker_test.dart:1680]: Could we also please add a check if header is indeed hidden in this scenario?

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 2]
```diff
@@ -1243,6 +1243,24 @@ void main() {
...
+      tester.view.physicalSize = const Size(720, 1280);
+      tester.view.devicePixelRatio = 1.0;
+
+      // Simulate the portait mode on a device with a small display when the virtual
+      // keyboard is visible.
+      tester.view.viewInsets = const FakeViewPadding(bottom: 1000);
+
+      initialEntryMode = DatePickerEntryMode.input;
+      await preparePicker(tester, (Future<DateTimeRange?> range) async {
+        expect(find.byType(TextField), findsNWidgets(2));
```
Comment (TahaTesser) [inline packages/flutter/test/material/date_range_picker_test.dart:1261]: Similarly, if the header is also hidden here.

File: engine/src/out [hunk 3]
```diff
@@ -0,0 +1 @@
+/media/oldhome/engine/out
```
Comment (TahaTesser) [inline engine/src/out:1]: Looks like an unintentional change

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: engine/src/out (hunk 3 above)
Comment (bleroux) [reply engine/src/out]: Exactly, this a change specific to my engine setup that should not be commited.

**Review by TahaTesser — APPROVED** [review]
LGTM!
