### PR TITLE
[flutter_tools] remove non-null check from AndroidValidator

### LINKED ISSUE #90042: Flutter Doctor Dart null check error in Android Toolchain check
## Steps to Reproduce

1. Updated to flutter 2.5
2. Re-installed cmdline-tools from Android Studio

## Logs

<details>
<summary>Logs</summary>

```
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Null check operator used on a null value
    • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
      #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #13     _rootRun (dart:async/zone.dart:1428:13)
      #14     _CustomZone.run (dart:async/zone.dart:1328:19)
      #15     _runZoned (dart:async/zone.dart:1863:10)
      #16     runZonedGuarded (dart:async/zone.dart:1851:12)
      #17     runZoned (dart:async/zone.dart:1782:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.10.0-1045-oem, locale en_AU.UTF-8)
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Null check operator used on a null value
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] VS Code
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/90042

The bang to `_androidSdk!.sdkManagerPath` was added in https://github.com/flutter/flutter/pull/82560/files#diff-c245d623bd123a206f90dc458d73520304e81ff8d1eac06a38e2c5221a859bfaR206

However this getter intentionally returns `null` if it cannot determine the path: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L397

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 1]
```diff
@@ -117,7 +117,7 @@ class UserMessages {
       'Android sdkmanager tool was found, but failed to run ($sdkManagerPath): "$error".\n'
       'Try re-installing or updating your Android SDK,\n'
       'visit ${_androidSdkInstallUrl(platform)} for detailed instructions.';
-  String androidSdkBuildToolsOutdated(String managerPath, int sdkMinVersion, String buildToolsMinVersion, Platform platform) =>
+  String androidSdkBuildToolsOutdated(String? managerPath, int sdkMinVersion, String buildToolsMinVersion, Platform platform) =>
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/user_messages.dart:120]: `managerPath` isn't even used in this string, it was removed in #65426. Is it needed for g3?  If not you can just remove it.

**Review by jmagman — COMMENTED** [review]
There's a few more `sdkManagerPath!` in android_workflow, it would maybe just crash a little later?

**Comment by christopherfujino** [comment]
> There's a few more `sdkManagerPath!` in android_workflow, it would maybe just crash a little later?

I removed another bang and provided a fallback string for a toolexit, and the other two are safeguarded by a check to `_canRunSdkManager()` so I think they're fine. PTAL @jmagman

File: packages/flutter_tools/test/general.shard/android/android_workflow_test.dart [hunk 2]
```diff
@@ -338,6 +338,30 @@ Review licenses that have not been accepted (y/N)?
     expect(licenseValidator.runLicenseManager(), throwsToolExit());
   });
 
+  testWithoutContext('AndroidValidator handles a null Android sdkManagerPath', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/android/android_workflow_test.dart:341]: I don't think this is testing anything now that `validate` doesn't use `sdkManagerPath` anywhere (unless I'm missing it).

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/android/android_workflow_test.dart:341]: sorry, didn't push yet...

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/android/android_workflow_test.dart:341]: hmm, even after a push I still see this test on github, but not locally

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/android/android_workflow_test.dart]: nvm, fixed

**Review by jmagman — APPROVED** [review]
LGTM
