### PR TITLE
Remove remaining "## Sample code" segments, and fix the snippet generator.

### LINKED ISSUE #26398: Insufficient contrast in dart docs samples
The contrast between the light blue and white ([currently 2.86](https://contrast-ratio.com/#white-on-rgb%2860%2C%20160%2C%20228%29)) and the light blue and dark blue ([currently 1.83](https://contrast-ratio.com/#RGB%2831%2C%20105%2C%20208-on-rgb%2860%2C%20160%2C%20228%29)) in the sample boxes ([see example below](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html)) is too low for a11y. Should be at least 4.5.

screen shot 2019-01-10 at 4 08 42 pm

### LINKED ISSUE #27411: HTML tabbed view for class doc with two snippets fails
The current IconButton docs includes two snippets. If I generate the docs with (cd dev/bots; ./docs.sh) the generated code lands in dev/docs/doc/snippets  but only the second IconButton snippet is there. Both generated snippets show up in the doc (HTML) page, but the second one's "sample app" tab operates the first snippet's tabbed view.

### PR DESCRIPTION
**Pull request by gspencergoog**
This converts all remaining "## Sample code" segments into snippets, and fixes the snippet generator to handle multiple snippets in the same dartdoc block properly.

I also generated, compiled, and ran each of the existing application samples, and fixed them up to be more useful and/or just run without errors.

This PR fixes these problems with examples:
1) Switching tabs in a snippet now works if there is more than one snippet in a single dartdoc block.
2) Generation of snippet code now works if there is more than one snippet.
3) Contrast of text and links in the code sample block has been improved to recommended levels.
4) Added five new snippet templates, including a "freeform" template to make it possible to show examples that need to change the app instantiation.
5) Fixed several examples to run properly, a couple by adding the "Scaffold" widget to the template, a couple by just fixing their code.
6) Fixed visual look of some of the samples when they run by placing many samples inside of a Scaffold.
7) In order to make it easier to run locally, changed the sample analyzer to remove the contents of the supplied temp directory before running, since having files that hang around is problematic (only a problem when running locally with the `--temp` argument).
8) Added a `SampleCheckerException` class, and handle sample checking exceptions more gracefully.
9) Deprecated the old "## Sample code" designation, and added enforcement for the deprecation.
10) Removed unnecessary `new` from templates (although they never appeared in the samples thanks to dartfmt, but still).

Fixes #26398 
Fixes #27411

### CODE REVIEW

File: dev/bots/analyze-sample-code.dart [hunk 1]
```diff
@@ -90,9 +90,35 @@ void main(List<String> arguments) {
...
+    } else {
+      tempDirectory.deleteSync(recursive: true);
+      tempDirectory.createSync(recursive: true);
+    }
+  }
+  try {
+    exitCode = SampleChecker(flutterPackage, tempDirectory: tempDirectory).checkSamples();
+  } on SampleCheckerException catch (e) {
+    stderr.write(e);
+    exit(1);
```
Comment (HansMuller) [inline dev/bots/analyze-sample-code.dart]: `exit(await exitCode)` ?

File: dev/snippets/config/templates/stateful_widget.tmpl [hunk 2]
```diff
@@ -10,12 +10,13 @@ class MyApp extends StatelessWidget {
   // This widget is the root of your application.
   @override
   Widget build(BuildContext context) {
-    return new MaterialApp(
+    return MaterialApp(
       title: 'Flutter Code Sample for {{id}}',
-      theme: new ThemeData(
+      theme: ThemeData(
```
Comment (HansMuller) [inline dev/snippets/config/templates/stateful_widget.tmpl]: There's no need to specify the default theme here. I assume that we include it in `flutter create` because we're trying remind developers that it's an option and that changing the primary color is easy. In this case, the goal is to highlight the snippet, so it doesn't seem necessary.

File: dev/snippets/config/templates/stateful_widget.tmpl [hunk 3]
```diff
@@ -10,12 +10,13 @@ class MyApp extends StatelessWidget {
...
         primarySwatch: Colors.blue,
       ),
-      home: new MyStatefulWidget(),
+      home: Material(child: MyStatefulWidget()),
+      color: Colors.white,
```
Comment (HansMuller) [inline dev/snippets/config/templates/stateful_widget.tmpl]: It would help to explain why we're specifying this. If the app includes a Scaffold it's not needed.

File: dev/snippets/config/templates/stateless_widget.tmpl [hunk 4]
```diff
@@ -10,12 +10,13 @@ class MyApp extends StatelessWidget {
   // This widget is the root of your application.
   @override
   Widget build(BuildContext context) {
-    return new MaterialApp(
+    return MaterialApp(
       title: 'Flutter Code Sample for {{id}}',
-      theme: new ThemeData(
+      theme: ThemeData(
```
Comment (HansMuller) [inline dev/snippets/config/templates/stateless_widget.tmpl]: Same comments as earlier about the theme and color parameters.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 5]
```diff
@@ -78,50 +77,42 @@ enum BottomNavigationBarType {
 /// the [Scaffold].
 ///
 /// ```dart
-/// class MyHomePage extends StatefulWidget {
-///   MyHomePage({Key key}) : super(key: key);
+/// int _selectedIndex = 1;
+/// final List<Widget> _widgetOptions = <Widget>[
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart]: could be const List<Widget>...

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 6]
```diff
@@ -78,50 +77,42 @@ enum BottomNavigationBarType {
...
-///     );
-///   }
-///
-///   void _onItemTapped(int index) {
-///     setState(() {
-///       _selectedIndex = index;
-///     });
-///   }
+/// @override
+/// Widget build(BuildContext context) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart]: It's both understandable and a little confusing that the Stateless template includes an implicit build method and return statement, but the Stateful template does not. 

Do we check for a build method when parsing the Stateful template and for the lack of one for the Stateless template? People are going to get this wrong. I have gotten this wrong.

File: dev/snippets/lib/main.dart [hunk 7]
```diff
@@ -75,6 +76,11 @@ void main(List<String> argList) {
     defaultsTo: environment['ELEMENT_NAME'],
     help: 'The name of the element that this snippet belongs to.',
   );
+  parser.addOption(
+    _kSerialOption,
+    defaultsTo: environment['INVOCATION_INDEX'],
+    help: 'A unique serial number for the snippet invocation.',
```
Comment (HansMuller) [inline dev/snippets/lib/main.dart]: Not sure what this is. We're not "invoking" the snippet?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 8]
```diff
@@ -311,15 +311,15 @@ class SystemChrome {
...
   ///
-  /// ## Sample Code
-  ///
+  /// {@tool sample}
   /// ```dart
   /// @override
   /// Widget build(BuildContext context) {
   ///   SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
-  ///   return /* ... */;
+  ///   return Placeholder();
```
Comment (HansMuller) [inline packages/flutter/lib/src/services/system_chrome.dart]: NICE

**Review by HansMuller — APPROVED** [review]
LGTM

File: dev/snippets/config/templates/stateless_widget.tmpl (hunk 4 above)
Comment (gspencergoog) [reply dev/snippets/config/templates/stateless_widget.tmpl]: Same fix. :-)

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 5 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Made it `static const List...`
