### PR TITLE
driver: forward device logs to local console

### LINKED ISSUE #4261: when a flutter drive test fails, you get an enormously long stack trace
I'm not sure if this is an artifact of how we're using `test`, or if we're printing this stack trace ourselves.

Here's an example:

```
00:06 +0 -1: end-to-end test tap on the floating action button; verify counter                     
  DriverError: Failed to fulfill WaitFor due to remote error
  Original error: JSON-RPC error -32000: Server error
  Original stack trace:
  package:json_rpc_2/src/client.dart 96:56                      Client.sendRequest
  package:json_rpc_2/src/peer.dart 69:15                        Peer.sendRequest
  package:vm_service_client/src/scope.dart 51:23                Scope.sendRequest.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:vm_service_client/src/scope.dart                      Scope.sendRequest
  package:vm_service_client/src/isolate.dart 344:19             VMIsolateRef.invokeExtension
  package:flutter_driver/src/driver.dart 196:32                 FlutterDriver._sendCommand.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:flutter_driver/src/driver.dart                        FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 219:11                 FlutterDriver.waitFor.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:flutter_driver/src/driver.dart                        FlutterDriver.waitFor
  test_driver/main_test.dart 35:20                              main.<fn>.<fn>.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 52                                _SyncCompleter.complete
  package:flutter_driver/src/driver.dart 214:5                  FlutterDriver.tap.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 52                                _SyncCompleter.complete
  package:flutter_driver/src/driver.dart 196:7                  FlutterDriver._sendCommand.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 52                                _SyncCompleter.complete
  package:vm_service_client/src/scope.dart 51:5                 Scope.sendRequest.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 52                                _SyncCompleter.complete
  package:json_rpc_2/src/client.dart 175:25                     Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7                      Client._handleResponse
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36                        Peer.listen.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_pipe.dart 144                               _ForwardingStreamSubscription._add
  dart:async/stream_pipe.dart 244                               _MapStream._handleData
  dart:async/stream_pipe.dart 176                               _ForwardingStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_pipe.dart 144                               _ForwardingStreamSubscription._add
  dart:async/stream_pipe.dart 244                               _MapStream._handleData
  dart:async/stream_pipe.dart 176                               _ForwardingStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_pipe.dart 144                               _ForwardingStreamSubscription._add
  dart:async/stream_pipe.dart 108                               _ForwardingStream._handleData
  dart:async/stream_pipe.dart 176                               _ForwardingStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:io/websocket_impl.dart 1105                              _WebSocketImpl._WebSocketImpl._fromSocket.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 67                        _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 14                        _EventSinkWrapper.add
  dart:io/websocket_impl.dart 328                               _WebSocketProtocolTransformer._messageFrameEnd
  dart:io/websocket_impl.dart 223                               _WebSocketProtocolTransformer.add
  dart:async/stream_transformers.dart 119                       _SinkTransformerStreamSubscription._handleData
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:io-patch/socket_patch.dart 1659                          _Socket._onData
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 962                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:io-patch/socket_patch.dart 1226                          _RawSocket._RawSocket.<fn>
  dart:io-patch/socket_patch.dart 760                           _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 873                                      _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper
  test_driver/main_test.dart                                    main.<fn>.<fn>
  package:test/src/backend/declarer.dart 88:19                  Declarer.test.<fn>.<async>.<fn>.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future_impl.dart 52                                _SyncCompleter.complete
  package:test/src/backend/declarer.dart 167:3                  Declarer._runSetUps.<async>
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 467                               _Future._complete
  dart:async/future.dart 390                                    Future.doWhile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/zone.dart 761                                      _CustomZone.bindUnaryCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 135:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 135:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/future_impl.dart 131                               _FutureListener.handleValue
  dart:async/future_impl.dart 637                               _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 667                               _Future._propagateToListeners
  dart:async/future_impl.dart 477                               _Future._completeWithValue
  dart:async/future_impl.dart 528                               _Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 394                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 873                                      _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 27                          _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart                        Declarer.test.<fn>.<async>.<fn>
  package:test/src/backend/invoker.dart 185:17                  Invoker.waitForOutstandingCallbacks.<fn>.<fn>.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 394                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:test/src/backend/invoker.dart                         Invoker.waitForOutstandingCallbacks.<fn>.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 1301                                     runZoned
  package:test/src/backend/invoker.dart 182:7                   Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 1303                                     runZoned
  package:test/src/backend/invoker.dart 181:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 86:29                  Declarer.test.<fn>.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 394                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:test/src/backend/declarer.dart                        Declarer.test.<fn>
  dart:async/future.dart 118                                    Future.Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 16                          Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 385                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 414                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 148                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/timer.dart 53                                      Timer.Timer
  dart:async/timer.dart 92                                      Timer.run
  dart:async/future.dart 116                                    Future.Future
  package:test/src/backend/invoker.dart 285:13                  Invoker._onRun.<fn>.<fn>.<async>
  dart:async/future.dart 144                                    Future.Future.microtask.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 946                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 125:48  StackZoneSpecification.registerCallback.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 751                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 861                                      _CustomZone.registerCallback
  dart:async/zone.dart 749                                      _CustomZone.bindCallback
  dart:async/schedule_microtask.dart 148                        scheduleMicrotask
  dart:async/future.dart 142                                    Future.Future.microtask
  package:test/src/backend/invoker.dart                         Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 724                                      _CustomZone.runGuarded
  dart:async/zone.dart 1301                                     runZoned
  package:test/src/utils.dart 232:12                            runZonedWithValues.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 1303                                     runZoned
  package:test/src/utils.dart 231:10                            runZonedWithValues
  package:test/src/backend/invoker.dart 272:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 88:24                      Chain.capture.<fn>
  dart:async/zone.dart 950                                      _rootRun
  dart:async/zone.dart 826                                      _CustomZone.run
  dart:async/zone.dart 1303                                     runZoned
  package:stack_trace/src/chain.dart 86:12                      Chain.capture
  package:test/src/backend/invoker.dart 271:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 187:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 39:31      _LiveTest.run
  package:test/src/runner/remote_listener.dart 189:14           RemoteListener._runLiveTest
  package:test/src/runner/remote_listener.dart 148:7            RemoteListener._serializeTest.<fn>
  dart:async/zone.dart 958                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/zone.dart 962                                      _rootRunUnary
  dart:async/zone.dart 837                                      _CustomZone.runUnary
  dart:async/zone.dart 732                                      _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/stream_controller.dart 868                         _StreamSinkWrapper.add
  package:stream_channel/src/guarantee_channel.dart 120:12      _GuaranteeSink.add
  package:stream_channel/src/multi_channel.dart 137:31          _MultiChannel._MultiChannel.<fn>
  dart:async/zone.dart 1138                                     _RootZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/zone.dart 1138                                     _RootZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/stream_controller.dart 868                         _StreamSinkWrapper.add
  dart:async/zone.dart 1138                                     _RootZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/zone.dart 1138                                     _RootZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:async/stream_controller.dart 868                         _StreamSinkWrapper.add
  dart:async/zone.dart 1138                                     _RootZone.runUnaryGuarded
  dart:async/stream_impl.dart 334                               _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 261                               _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 768                         _StreamController&&_SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 635                         _StreamController._add
  dart:async/stream_controller.dart 581                         _StreamController.add
  dart:isolate-patch/isolate_patch.dart 148                     _RawReceivePortImpl._handleMessage


  package:flutter_driver/src/driver.dart 198:7   FlutterDriver._sendCommand.<async>
  dart:async                                     _Completer.completeError
  package:vm_service_client/src/scope.dart 58:3  Scope.sendRequest.<async>
  dart:async                                     _Completer.completeError
  package:json_rpc_2/src/client.dart 177:25      Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7       Client._handleResponse
  dart:async                                     _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36         Peer.listen.<fn>
  ===== asynchronous gap ===========================
  dart:async                                     _Completer.completeError
  package:flutter_driver/src/driver.dart 207:3   FlutterDriver._sendCommand.<async>
  dart:async                                     _Completer.completeError
  package:vm_service_client/src/scope.dart 58:3  Scope.sendRequest.<async>
  dart:async                                     _Completer.completeError
  package:json_rpc_2/src/client.dart 177:25      Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7       Client._handleResponse
  dart:async                                     _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36         Peer.listen.<fn>
  ===== asynchronous gap ===========================
  dart:async                                     _asyncErrorWrapperHelper
  package:flutter_driver/src/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 219:11  FlutterDriver.waitFor.<async>
  ===== asynchronous gap ===========================
  dart:async                                     Future.Future.microtask
  package:flutter_driver/src/driver.dart         FlutterDriver.waitFor
  test_driver/main_test.dart 35:20               main.<fn>.<fn>.<async>
  dart:async                                     _SyncCompleter.complete
  package:flutter_driver/src/driver.dart 214:5   FlutterDriver.tap.<async>
  dart:async                                     _SyncCompleter.complete
  package:flutter_driver/src/driver.dart 196:7   FlutterDriver._sendCommand.<async>
  dart:async                                     _SyncCompleter.complete
  package:vm_service_client/src/scope.dart 51:5  Scope.sendRequest.<async>
  dart:async                                     _SyncCompleter.complete
  package:json_rpc_2/src/client.dart 175:25      Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7       Client._handleResponse
  dart:async                                     _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36         Peer.listen.<fn>
  ===== asynchronous gap ===========================
  dart:async                                     _asyncThenWrapperHelper
  test_driver/main_test.dart                     main.<fn>.<fn>
```

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes #4261 

/cc @devoncarew @danrubel

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm

> [lint] Cancel instances of dart.async.StreamSubscription. (packages/flutter_tools/lib/src/commands/drive.dart, line 87, col 30)

Looks like there's an issue w/ a lint - it's not able to determine that the subscription is cancelled.

File: packages/flutter_tools/lib/src/commands/drive.dart [hunk 1]
```diff
@@ -306,6 +309,10 @@ Future<int> startApp(DriveCommand command) async {
     platformArgs['trace-startup'] = command.traceStartup;
 
   printTrace('Starting application.');
+
+  // Forward device log messages to the terminal window running the "drive" command.
+  command._deviceLogSubscription = command.device.logReader.logLines.listen(printStatus);
+
```
Comment (danrubel) [inline packages/flutter_tools/lib/src/commands/drive.dart]: cancel subscription if `result.started` (see code below) is `false` ?

**Review by danrubel — APPROVED** [review]
LGTM once lint has been addressed.

**Comment by yjbanov** [comment]
> Looks like there's an issue w/ a lint

I'm not a fan of this lint. There's no way to make it reliable. I've seen many projects legitimately use subscription tracking utilities (often referred to as "disposers") to close them based on some life-cycle event, which the linter won't be able to figure out.

File: packages/flutter_tools/lib/src/commands/drive.dart (hunk 1 above)
Comment (yjbanov) [inline packages/flutter_tools/lib/src/commands/drive.dart]: Good catch! Done.

**Comment by yjbanov** [comment]
@devoncarew I added a "ignore: cancel_subscriptions" for now and will log a bug against the linter shortly.
