### PR TITLE
PopupMenuButton menus inherit the button theme

### LINKED ISSUE #5572: Pesto in dark theme: menu text has wrong color
pesto dark bug

/cc @sethladd @HansMuller

### PR DESCRIPTION
**Pull request by HansMuller**
If the theme inherited by a PopupMenuButton shadows the material app's theme then the menu itself will be wrapped with the shadow theme. In the common case, where only the app creates a theme widget, the menu inherits the app's theme as usual.

Likewise for dialogs, modal bottom sheets, and drop down menus.

Fixes #5572

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -374,13 +374,15 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
     this.position,
     this.items,
     this.initialValue,
-    this.elevation
+    this.elevation,
+    this.theme
```
Comment (Hixie) [inline packages/flutter/lib/src/material/popup_menu.dart]: when you add code like this, add trailing commas :-)

File: packages/flutter/lib/src/material/theme.dart [hunk 2]
```diff
@@ -18,13 +18,15 @@ const Duration kThemeAnimationDuration = const Duration(milliseconds: 200);
...
 ///  * [ThemeData]
+///  * [MaterialApp]
 class Theme extends InheritedWidget {
   /// Applies the given theme [data] to [child].
   ///
   /// The [data] and [child] arguments must not be null.
   Theme({
     Key key,
     @required this.data,
+    this.isShadowTheme: true,
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme.dart]: boolean arguments should when possible default to false (because `foo: false` looks like something that could be safely removed without effect). Maybe `isPrimaryTheme` with the reverse semantics? Or `isMainTheme`? `isMaterialAppTheme`?

File: packages/flutter/lib/src/material/theme.dart [hunk 3]
```diff
@@ -34,14 +36,22 @@ class Theme extends InheritedWidget {
   /// Specifies the color and typography values for descendant widgets.
   final ThemeData data;
 
+  /// True if this theme shadows the one created by the [MaterialApp].
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme.dart]: you should add some color here saying why you would set this (or rather, that you wouldn't), how it's used, etc.

File: packages/flutter/lib/src/material/theme.dart [hunk 4]
```diff
@@ -34,14 +36,22 @@ class Theme extends InheritedWidget {
...
   ///
   /// Defaults to the fallback theme data if none exists.
-  static ThemeData of(BuildContext context) {
-    Theme theme = context.inheritFromWidgetOfExactType(Theme);
-    return theme?.data ?? _kFallbackTheme;
+  ///
+  /// If [shadowTheme] is true and the closest Theme ancestor was installed by
+  /// the [MaterialApp] - in other words if the closest Theme ancestor does not
+  /// shadow the app's theme - then return null.
+  static ThemeData of(BuildContext context, { bool shadowTheme: false }) {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme.dart]: maybe shadowThemeOnly? Or `secondaryThemeOnly` if you call the other argument `isPrimaryTheme`?

File: packages/flutter/lib/src/material/theme.dart [hunk 5]
```diff
@@ -34,14 +36,22 @@ class Theme extends InheritedWidget {
...
   /// The data from the closest instance of this class that encloses the given context.
   ///
   /// Defaults to the fallback theme data if none exists.
-  static ThemeData of(BuildContext context) {
-    Theme theme = context.inheritFromWidgetOfExactType(Theme);
-    return theme?.data ?? _kFallbackTheme;
+  ///
+  /// If [shadowTheme] is true and the closest Theme ancestor was installed by
+  /// the [MaterialApp] - in other words if the closest Theme ancestor does not
+  /// shadow the app's theme - then return null.
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme.dart]: add another paragraph talking about why you would use this argument.

**Comment by Hixie** [comment]
As discussed, I suspect the other ones need it too because they probably have Material widgets and so forth.

LGTM.

File: packages/flutter/lib/src/material/theme.dart (hunk 2 above)
Comment (abarth) [inline packages/flutter/lib/src/material/theme.dart]: isAppTheme?

File: packages/flutter/lib/src/material/app.dart [hunk 6]
```diff
@@ -246,6 +246,7 @@ class _MaterialAppState extends State<MaterialApp> {
     ThemeData theme = config.theme ?? new ThemeData.fallback();
     Widget result = new AnimatedTheme(
       data: theme,
+      isShadowTheme: false,
```
Comment (dragostis) [inline packages/flutter/lib/src/material/app.dart]: Maybe `isShadowingTheme` would be more explicit?

File: packages/flutter/lib/src/material/theme.dart (hunk 2 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/theme.dart]: I went with isMaterialAppTheme since that's part and parcel of the definition.

File: packages/flutter/lib/src/material/theme.dart (hunk 4 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/theme.dart]: I used shadowThemeOnly. Thankfully this parameter will rarely be used.
