### PR TITLE
Fix memory leak in RenderAnimatedSize

### LINKED ISSUE #133903: Memory Leak: RenderAnimatedSize doesn't dispose AnimationController and CurvedAnimation
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`RenderAnimatedSize` creates `AnimationController` and  `CurvedAnimation` but doesn't dispose them, which leads to a memory leak.

Creation of the `AnimationController` and `CurvedAnimation`:
https://github.com/flutter/flutter/blob/248645a2b2c9baac4603626d34193a5d0d712c51/packages/flutter/lib/src/rendering/animated_size.dart#L76-L100
 
<br>

`dispose()` method:
https://github.com/flutter/flutter/blob/248645a2b2c9baac4603626d34193a5d0d712c51/packages/flutter/lib/src/rendering/animated_size.dart#L351-L356

<br>

### Expected results

The `_controller` and `_animation` are disposed in the `dispose()` method.

### Actual results

The `_controller` and `_animation` aren't disposed in the `dispose()` method.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-12.0.pre.107, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-12.0.pre.197 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 42014a309b (23 seconds ago), 2023-09-02 12:02:02 +0200
    • Engine revision d00b69a438
    • Dart version 3.2.0 (build 3.2.0-128.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
`AnimationController` and `CurvedAnimation` objects were not disposed in `RenderAnimatedSize`.

### Description
- Fixes https://github.com/flutter/flutter/issues/133903;
- Adds the missing `dispose()` calls for `AnimationController` and `CurvedAnimation` in `RenderAnimatedSize`.

### Tests
- Updates `animated_size_test.dart` to test that `AnimationController` and `CurvedAnimation` are disposed after `RenderSize` disposal.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @ksokolovskyi thanks for contributing! Is there an open issue this PR would resolve? Also, the bot comment provides instructions for seeking test exemption.

**Comment by ksokolovskyi** [comment]
Hi @Piinks, thank you for the review!

1) I don't have a specific issue for this PR. I've found out that there is a memory leak in the RenderAnimatedSize and made a PR with a fix. Do I need to create an issue?
2) Asked for a test exemption in #hackers chat.

**Comment by Hixie** [comment]
test-exempt: will be tested later when we can catch these leaks

File: packages/flutter/lib/src/rendering/animated_size.dart [hunk 1]
```diff
@@ -351,6 +351,8 @@ class RenderAnimatedSize extends RenderAligningShiftedBox {
   @override
   void dispose() {
     _clipRectLayer.layer = null;
+    _controller.dispose();
```
[the remark this answers is not in the document]
Comment (xu-baolin) [reply packages/flutter/lib/src/rendering/animated_size.dart:364]: This change looks good to me, thanks for your nice job.
Could you file a new issue to track this problem and link it to this?

[the remark this answers is not in the document]
Comment (ksokolovskyi) [reply packages/flutter/lib/src/rendering/animated_size.dart:364]: Yes, of course, I will create a new issue.

**Comment by ksokolovskyi** [comment]
@xu-baolin Here is the issue: https://github.com/flutter/flutter/issues/133903

File: packages/flutter/lib/src/rendering/animated_size.dart [hunk 2]
```diff
@@ -99,8 +99,18 @@ class RenderAnimatedSize extends RenderAligningShiftedBox {
     );
   }
 
+  /// The animation controller that is used to drive the resizing.
+  ///
+  /// The animation itself is exposed by the [animation] property.
+  @visibleForTesting
+  AnimationController get controller => _controller;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/rendering/animated_size.dart:106]: This is a public API not only for testing, right?

We can refer to the implementation of `DragGestureRecognizer.debugLastPendingEventTimestamp` and document that it is only available for testing.

Comment (ksokolovskyi) [reply packages/flutter/lib/src/rendering/animated_size.dart:106]: Previously `_controller` and `_animation` were private because `AnimatedSize` is a kind of implicit animation, so users don't need to have access to the animation controller. 
Are you sure that we need to expose them to the users and create additional getters for testing only?

Comment (ksokolovskyi) [reply packages/flutter/lib/src/rendering/animated_size.dart]: I got your point, thanks. 
Could you please review the latest commit?

Comment (xu-baolin) [reply packages/flutter/lib/src/rendering/animated_size.dart]: There is a problem with the CI infra, let's wait for it to be fixed.

**Review by xu-baolin — APPROVED** [review]
LGTM, Thanks for finding and fixing this bug.
@Piinks Hi, could you take a second review on this : )

**Comment by XilaiZhang** [comment]
hopefully people wouldn't mind me test some Google Testing logic on this PR (only involves a few extra clicks on "update branch" button) while Kate is OOO. choosing this PR since it is from an external contributor and has gotten approval from a flutter hacker member.

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for contributing @ksokolovskyi!

**Comment by XilaiZhang** [comment]
Umm quick question, there seems to be 1k+ failures reported in Google Testing in previous runs from the commits, are those failures considered to be unrelated to this PR? thank you!

**Comment by Piinks** [comment]
> are those failures considered to be unrelated to this PR?

I think so

**Comment by Piinks** [comment]
When I checked, the 1k+ failures looked like infra failures. Like the tests failed to build and run, which would not be due to this change.

**Comment by XilaiZhang** [comment]
ah cool, thanks for verifying!

**Comment by Piinks** [comment]
Looks like it merged without running Google testing this time @XilaiZhang

**Comment by XilaiZhang** [comment]
yeah sorry i was testing out a few things on this PR today and temporarily made it disappear (sent cl/564489978 as fix)

last time i checked this PR it created cl/564478862 and the results at test/564478862 was green so I merged it.

**Comment by ksokolovskyi** [comment]
@xu-baolin @Piinks @XilaiZhang thanks for the review!
