### PR TITLE
Hide EditableString implementation details

### LINKED ISSUE #208: show software keyboard and push delete key, then crash application
<a href="https://github.com/kyorohiro"></img></a> **Issue by [kyorohiro](https://github.com/kyorohiro)**
_Sunday Oct 18, 2015 at 04:42 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1662_

----

show software keyboard and push delete key, then crash application

**[source]**
```
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';

main() async {
  EditableString st= new EditableString(text: "test:", onUpdated: () {});
  keyboard.show(st.stub, KeyboardType.TEXT);
}
```

**[senario]**
1. run applicatioon on nexus7
  https://github.com/kyorohiro/hello_skyengine/tree/master/edit_text_2
--> show software keyboard
2. push delete key

### LINKED ISSUE #209: EditableString throw unexpected error!! when do no commit text, do  input text and delete key.
<a href="https://github.com/kyorohiro"></img></a> **Issue by [kyorohiro](https://github.com/kyorohiro)**
_Sunday Oct 18, 2015 at 05:15 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1663_

----

EditableString throw unexpected error!! when do no commit text, do  input text and delete key.

**[senario]**
0 . run application
 https://github.com/kyorohiro/hello_skyengine/tree/master/edit_text
1.  show software keyboard
2.  input composing text
3.  push delete key
4.  push delete key
5.  input composing text
--> then unexpected error

**[source for reproduction]**

```
//
// https://github.com/kyorohiro/hello_skyengine/tree/master/edit_text_3
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';
import 'dart:async';

main() async {
  EditableString st = new EditableString(text: "test:", onUpdated: () {});
  KeyboardHandle handle = keyboard.show(st.stub, KeyboardType.TEXT);
  await new Future.delayed(new Duration(seconds: 3));
  for (int i = 0; i < 3; i++) {
    print("----");
    st.setComposingText("a", 1);
    await new Future.delayed(new Duration(seconds: 1));
    st.setComposingText("", 0);
    await new Future.delayed(new Duration(seconds: 1));
    st.deleteSurroundingText(1, 0);
  }
}

```

### PR DESCRIPTION
**Pull request by abarth**
Previously, EditableString had many public members because it needed to
implement the KeyboardClient interface. However, that's confusing
because these methods cannot be called directly.

Now EditableString holds a private implementation of the KeyboardClient,
which hides the implementation details.

Fixes #208
Fixes #209

### CODE REVIEW

**Comment by abarth** [comment]
@jason-simmons

File: packages/flutter/lib/src/widgets/editable.dart [hunk 1]
```diff
@@ -43,11 +39,29 @@ class TextRange {
 
   /// Whether this range is empty (but still potentially placed inside the text).
   bool get isCollapsed => start == end;
+
+  /// The text before this range.
+  String textBefore(String text) {
+    return text.substring(0, start);
```
Comment (a14n) [inline packages/flutter/lib/src/widgets/editable.dart]: I don't know if this is intended but depending on `TextRange` and `text` this can lead to `RangeError` (for instance with `TextRange.empty`, with `TextRange(start: 3, end: 5)` and  `text="aa"`)

Comment (abarth) [inline packages/flutter/lib/src/widgets/editable.dart]: That is an error condition.  I guess we could return null or truncate, but it seems reasonable to have the same error handling as `substring`.
