### PR TITLE
Fix handling of null body2 text style for chip and slider

### LINKED ISSUE #17251: labelStyle != null assertion Fails in flutter/src/material/chip_theme.dart
I am using Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.5 17F45c, locale en-IN)
I am getting an assertion failed on the following file.

'package:flutter/src/material/chip_theme.dart': Failed assertion: line 218 pos 12: 'labelStyle != null': is not true.

When the exception was thrown, this was the stack:
I/flutter (27821): #2      new ChipThemeData.fromDefaults (package:flutter/src/material/chip_theme.dart)
I/flutter (27821): #3      new ThemeData (package:flutter/src/material/theme_data.dart:173:23)
I/flutter (27821): #4      MyApp.build (file:///Users/vineshraju/Development/Melaan/melaan/lib/main.dart:25:18)
I/flutter (27821): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3687:28)
I/flutter (27821): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter (27821): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (27821): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (27821): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (27821): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (27821): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (27821): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (27821): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (27821): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (27821): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
I/flutter (27821): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (27821): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (27821): #18     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (27821): #19     main (file:///Users/vineshraju/Development/Melaan/melaan/lib/main.dart:11:3)
I/flutter (27821): #20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (27821): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (27821): (elided 2 frames from class _AssertionError)

### PR DESCRIPTION
**Pull request by gspencergoog**
Before this change, if you specified a non-null `textTheme`, but the theme you specified didn't have a `body2` defined, then creating a `ChipTheme` would assert (which means creating a `ThemeData` would fail).

This adds handling for this corner case to default to reasonable values in that case. The slider had the same problem, but for `accentTextTheme`, so I fixed that too.

While I had the patient open, Hans and I noticed that TextTheme.merge wasn't doing the right thing in the case where some members were null either, so I fixed that, and added some examples, since merge/copyWith are common operations that are not always well understood.

Fixes https://github.com/flutter/flutter/issues/17251

### CODE REVIEW

File: packages/flutter/lib/src/material/typography.dart [hunk 1]
```diff
@@ -103,6 +103,39 @@ class TextTheme extends Diagnosticable {
...
+  /// class TitleColorThemeCopy extends StatelessWidget {
+  ///   TitleColorThemeCopy({Key key, this.child, this.titleColor}) : super(key: key);
+  /// 
+  ///   final Color titleColor;
+  ///   final Widget child;
+  /// 
+  ///   @override
+  ///   Widget build(BuildContext context) {
+  ///     ThemeData theme = Theme.of(context);
+  ///     theme = theme.copyWith(
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/typography.dart]: Rather than reusing the theme var, maybe make it final and 
```
return new Theme(
  child: child,
  data: theme.copyWith(
    ...
```

File: packages/flutter/lib/src/material/typography.dart [hunk 2]
```diff
@@ -139,24 +172,62 @@ class TextTheme extends Diagnosticable {
...
+  /// class TitleColorTheme extends StatelessWidget {
+  ///   TitleColorTheme({Key key, this.child, this.titleColor}) : super(key: key);
+  /// 
+  ///   final Color titleColor;
+  ///   final Widget child;
+  /// 
+  ///   @override
+  ///   Widget build(BuildContext context) {
+  ///     ThemeData theme = Theme.of(context);
+  ///     // This partialTheme is incomplete: just replacing theme.textTheme with
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/typography.dart]: I think it would help to qualify "incomplete", like: is incomplete because it only specifies one text style. Because it is incomplete, just replacing ...

File: packages/flutter/lib/src/material/typography.dart [hunk 3]
```diff
@@ -103,6 +103,39 @@ class TextTheme extends Diagnosticable {
...
+  ///           color: titleColor,
+  ///         ),
+  ///       ),
+  ///     );
+  ///     return new Theme(data: theme, child: child);
+  ///   }
+  /// }
+  /// ```
+  ///
+  /// Using [merge] instead can make more sense in some situations.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/typography.dart]: This statement isn't as helpful as it should be.  Since we have both copyWith and merge, we should provide some rule of thumb here.  The see also comment appears to be headed in the right direction...

File: packages/flutter/lib/src/material/typography.dart [hunk 4]
```diff
@@ -139,24 +172,62 @@ class TextTheme extends Diagnosticable {
...
+  ///     // This partialTheme is incomplete: just replacing theme.textTheme with
+  ///     // partialTheme wouldn't do the right thing, so merge it with the existing theme.
+  ///     TextTheme partialTheme = new TextTheme(title: new TextStyle(color: titleColor));
+  ///     theme = theme.copyWith(textTheme: theme.textTheme.merge(partialTheme));
+  ///     return new Theme(data: theme, child: child);
+  ///   }
+  /// }
+  /// ```
+  ///
+  /// Using [copyWith] instead can make more sense in some situations.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/typography.dart]: Same comment as the one about "Using [merge]"

**Review by HansMuller — APPROVED** [review]
Just a few requests to improve the docs

File: packages/flutter/lib/src/material/typography.dart (hunk 3 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/typography.dart]: OK, I reworked those both into descriptive See Also entries.

File: packages/flutter/lib/src/material/typography.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/typography.dart]: Done.

File: packages/flutter/lib/src/material/typography.dart (hunk 4 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/typography.dart]: Done.
