### PR TITLE
Set AA flag for painting images

### LINKED ISSUE #30710: No anti-aliasing on rotated images
Image anti-aliasing does not work as expected when a rotation transform is applied.

## Steps to Reproduce

I have a widget which is defined as follows:

```dart
Transform.rotate(
  angle: rotation,
  child: Material(
    elevation: 2,
    color: Colors.white,
    child:Container(
      padding: EdgeInsets.fromLTRB(
        width / 100.0 * 5,
        height / 100.0 * 7,
        width / 100.0 * 5,
        height / 100.0 * 35,),
      child: Container(
        width: width,
        height: height,
        child: Image.file(
          imageFile,
          filterQuality: FilterQuality.medium,
          fit: BoxFit.cover,
        ),
      ),
    )
  )
)
```

When looking at the rendered edges of the image inside the rotated material, you see that no anti-aliasing takes place, resulting in very rough edges.
Example:
Screenshot from 2019-04-08 19-10-36

## Logs

```
Analyzing photobooth...                                                 
No issues found! (ran in 0.9s)
```

```
[ +102 ms] [✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
[        ]     • Flutter version 1.2.1 at /home/rob/Projects/Flutter/flutter
[        ]     • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
[        ]     • Engine revision 3757390fa4
[        ]     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
⣽[   +1 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +8 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +38 ms] List of devices attached
[  +14 ms] executing: /opt/android-sdk/tools/bin/sdkmanager --licenses
[+1350 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[        ]     • Android SDK at /opt/android-sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-28, build-tools 28.0.3
[        ]     • ANDROID_HOME = /opt/android-sdk
[        ]     • Java binary at: /home/rob/opt/android-studio/jre/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
[        ]     • All Android licenses accepted.
[        ] [!] Android Studio (version 3.0)
[        ]     • Android Studio at /opt/android-studio
[        ]     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[        ]     ✗ Dart plugin not installed; this adds Dart specific functionality.
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
[        ] [✓] Android Studio (version 3.3)
[        ]     • Android Studio at /home/rob/opt/android-studio
[        ]     • Flutter plugin version 32.0.1
[        ]     • Dart plugin version 182.5124
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
[        ] [!] IntelliJ IDEA Ultimate Edition (version 2018.2)
[        ]     • IntelliJ at /opt/intellij-idea-ultimate-edition
[        ]     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[        ]     • Dart plugin version 143.1247
[        ]     • For information about installing plugins, see
[        ]       https://flutter.io/intellij-setup/#installing-the-plugins
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 3 categories.
```

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/30710

Test:
- I'm expecting to see some golden image differences to verify the change

### CODE REVIEW

**Comment by liyuqian** [comment]
@Piinks : I'm expecting to see some golden image differences for this change. If somehow there's no golden test that covers a rotated image, can you please create a PR that adds such a golden test? https://github.com/flutter/flutter/issues/30710#issue-430572836 has a sample code.

**Comment by Piinks** [comment]
First glance: I don't think we have any golden file tests that render actual images. Is that pertinent to the test you are looking for?

**Comment by goderbauer** [comment]
Are there any negative implications from always setting this to true? Should it be configurable?

**Comment by liyuqian** [comment]
@Piinks : an dummy image (e.g., all blue pixels) would be sufficient to test the AA behavior.

@goderbauer : I'd expect the performance impact to be similar to drawing a rect with or without AA. Most of our widgets (e.g., `Container`) would draw something (paths, rects, rrects...) in AA by default without any configurable switches. So I don't think adding an AA switch here is critical. Of course, making it configurable would be better if we ignore the API maintenance cost (which I don't think there's much). CC @Hixie to see if we'd like to expose the AA switch on an `Image` widget.

**Review by goderbauer — APPROVED** [review]
Sounds good to me.

LGTM

**Comment by Piinks** [comment]
> @Piinks : an dummy image (e.g., all blue pixels) would be sufficient to test the AA behavior.

Ok, are you wanting to have a test land on master first so you can verify there is a change? Otherwise, you can add the test as part of this change.

**Comment by Piinks** [comment]
>  you can add the test as part of this change.

 Actually that may be best to include in this change, rather than checking in a test that may or may not be affected by this.

**Comment by liyuqian** [comment]
@Piinks : yes, it would be nice if you can land a PR before this PR gets merged so we'll see the difference!

**Comment by Piinks** [comment]
> @Piinks : yes, it would be nice if you can land a PR before this PR gets merged so we'll see the difference!

And if it doesn't make a difference? I would recommend adding the test as part of this change. You can test locally that the bug is reproduced and see the visual diff with your patch applied to confirm. That seems inline with [write test fix bug](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#write-test-find-bug) ?

**Comment by liyuqian** [comment]
@Piinks : sure, I'll do that. That probably would take a few days as I also need to clear some other tasks in the queue first. Meanwhile, I think a separate PR may also make sense as the test should reveal an aliased rectangle (or it shouldn't be merged), and this PR should fix that aliasing in presubmits (or this PR shouldn't be merged).

**Comment by dnfield** [comment]
It would probably be worth checking if this impacts some golden test in Google.

If so, this is a breaking change, and I believe we'd have to expose a flag for it so it can be rolled into Google without manual intervention.

**Comment by liyuqian** [comment]
Thank you @dnfield for the remind! I'm curious what the current procedure is for those AA changes. For example, if a Skia roll changes AA and require golden image updates from Google, does that constitute a breaking change, and how do we roll it automatically? My old experience (which might be obsolete now) is to just approve those golden changes along the Google roll, and not file any breaking change announcements...

**Comment by dnfield** [comment]
@hixie would know but I believe we treat skia breakages differently.

I think this change is definitely worth making to be clear

**Comment by Hixie** [comment]
For some reason it looks like the public copy of the breaking change policy (https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes) doesn't actually mention this, but the intent is that upstream dependencies (and PRs that roll those dependencies) aren't beholden to our breaking change policy currently.

**Comment by linxuebin1990** [comment]
@liyuqian  I have an idea. This https://github.com/flutter/flutter/issues/30710  problem only occurs when we rotate (or skew) the image， not translate or scale. We can check the matrix of the canvas first, and turn on anti-aliasing only when there is a rotation (or skew) operation. The same can be applied to rectangle decoration, also can fix https://github.com/flutter/flutter/issues/14288.

I find code in SkMatrix.h , as follows
```
enum TypeMask {
        kIdentity_Mask    = 0,    //!< identity SkMatrix; all bits clear
        kTranslate_Mask   = 0x01, //!< translation SkMatrix
        kScale_Mask       = 0x02, //!< scale SkMatrix
        kAffine_Mask      = 0x04, //!< skew or rotate SkMatrix
        kPerspective_Mask = 0x08, //!< perspective SkMatrix
    };
// ...
 bool isTranslate() const { return !(this->getType() & ~(kTranslate_Mask)); }
```

We can add a function as follows:
```
bool isSkewOrRotate() const {return this->getType() & kAffine_Mask;}
```

**Comment by liyuqian** [comment]
@linxuebin1990 : thank you for the suggestion! Unfortunately, even if we only enable AA with rotation, it's might still be a breaking change according to our current policy.

Nevertheless, I think the `SkMatrix::isSkewOrRotate` might be helpful regardless of how we handle the PR here. Please feel free to propose that to https://groups.google.com/g/skia-discuss.

**Comment by goderbauer** [comment]
@liyuqian Did you have a chance to add a golden test for this?

**Comment by liyuqian** [comment]
@goderbauer @Piinks : I'm having some troubles with `Image` golden test. Please see the newest commit. I can see a nonempty golden image if `ui.Image` is used, but not when `Image.memory` is used, although they use the same bytes.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 2.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

File: packages/flutter/test/widgets/image_test.dart [hunk 1]
```diff
@@ -1568,6 +1568,75 @@ void main() {
...
+      );
+      await completer.future;
+    });
+
+    // Double check that our bytes are valid.
+    ui.Image uiImage;
+    await tester.runAsync(() async {
+      final Completer<void> completer = Completer<void>();
+      ui.decodeImageFromList(bytes, (ui.Image image) {
+        uiImage = image;
```
Comment (dnfield) [inline packages/flutter/test/widgets/image_test.dart]: This works because it supports raw image data.  Image.memory only supports encoder data.

Comment (liyuqian) [reply packages/flutter/test/widgets/image_test.dart]: @dnfield : `Image.memory(bytes)` is using the PNG encoded `bytes`: https://github.com/flutter/flutter/pull/51656/files#diff-1f9334e95055c237f00b72bb642684d4R1588

Comment (liyuqian) [reply packages/flutter/test/widgets/image_test.dart]: Also, a raw image data will trigger exception in `Image.memory`. In my case, there's no exception, just empty drawing result.

Comment (dnfield) [reply packages/flutter/test/widgets/image_test.dart]: Ahh ok.

**Comment by Piinks** [comment]
> @goderbauer @Piinks : I'm having some troubles with `Image` golden test. Please see the newest commit. I can see a nonempty golden image if `ui.Image` is used, but not when `Image.memory` is used, although they use the same bytes.

IIRC I've seen people design golden file tests with images by preaching them, let me find an example.

**Comment by Piinks** [comment]
Here is an example: https://github.com/flutter/flutter/pull/41137/files

**Comment by liyuqian** [comment]
@Piinks : thanks! `precacheImage` solved the problem. Please review the updated test and `isAntiAlias` flag.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 2.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

**Comment by liyuqian** [comment]
@yjbanov : my rotated image golden test consistently times out on web. Do you have any idea what might go wrong?

File: packages/flutter/lib/src/painting/decoration_image.dart [hunk 2]
```diff
@@ -376,6 +376,7 @@ void paintImage({
   bool flipHorizontally = false,
   bool invertColors = false,
   FilterQuality filterQuality = FilterQuality.low,
+  bool isAntiAlias = false,
```
Comment (Piinks) [inline packages/flutter/lib/src/painting/decoration_image.dart]: Should we assert this isn't `null`? Here and below.

Comment (liyuqian) [reply packages/flutter/lib/src/painting/decoration_image.dart]: Done.

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 3.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 3.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

**Comment by liyuqian** [comment]
@hterkelsen : this test always times out on Flutter web. My guess is that Flutter web probably skipped `ui.decodeImageFromPixels` call so the completer inside is never completed. What's your thought and how should I fix it?

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 4.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

**Comment by liyuqian** [comment]
@hterkelsen : I've directly written the PNG bytes into a constant int list as you suggested. However, the web test would still timeout if `await precacheImage` is called. Is that expected?

**Comment by liyuqian** [comment]
Discussed with @hterkelsen offline. We agreed that we shall proceed with merging this PR, and maybe come back later once he figured out why `precacheImage` failed on web.

File: packages/flutter/test/widgets/image_test.dart [hunk 3]
```diff
@@ -1633,14 +1633,16 @@ void main() {
     ));
 
     // precacheImage is needed, or the image in the golden file will be empty.
-    final Finder allImages = find.byType(Image);
-    for (final Element e in allImages.evaluate()) {
-      await tester.runAsync(() async {
-        final Image image = e.widget as Image;
-        await precacheImage(image.image, e);
-      });
+    if (!kIsWeb) {
```
Comment (Piinks) [inline packages/flutter/test/widgets/image_test.dart:1636]: Can you instead just skip the test for the browser with `skip: isBrowser` below? It should also have a comment referencing why the test is skipped so we remember to come back and turn it on when the issue is resolved.

**Review by Piinks — COMMENTED** [review]
Can you file an issue for the web exception and put a skip in place?

File: packages/flutter/test/widgets/image_test.dart (hunk 3 above)
Comment (liyuqian) [reply packages/flutter/test/widgets/image_test.dart:1636]: I do still want the most of this test to run on web to see how it behaves. The `precacheImage` is fixing the empty image issue probably caused by the non-web image cache (CC @dnfield for confirmation). Since I didn't see Skia gold to report any strange golden images on web, I think the web is fine with this test for now?

Comment (Piinks) [reply packages/flutter/test/widgets/image_test.dart:1636]: Ok! Can we still reference an issue here for the `precacheImage` with a TODO so we know why this is is not happening on web and can enable it when it is fixed?

Comment (liyuqian) [reply packages/flutter/test/widgets/image_test.dart:1639]: Done.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 6.
Please triage them at https://flutter-gold.skia.org/search?issue=51656.

**Comment by liyuqian** [comment]
It seems that the golden test on web is flaky as sometimes [it generated empty images][1]. Hence I'm going to disable the test on web instead of just skipping `precacheImage`.

[1]: https://flutter-gold.skia.org/search?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&issue=51656&limit=50&master=false&match=name&metric=combined&neg=false&new_clstore=true&offset=0&pos=false&query=source_type%3Dflutter&sort=desc&unt=true
