### PR TITLE
Fix `flutter stop` to stop the right Android activity.

### LINKED ISSUE #1651: `flutter stop` no longer stops apps running on android
Doing a `flutter start` and a `flutter stop` does not stop the app on android. `stop` is sending in:

```
adb shell am force-stop org.domokit.sky.shell
```

Using adb to find the running activities, and instead passing in:

```
adb shell am force-stop com.example.flutter_sunflower
```

does shut down the app. Perhaps `start` is pulling the activity name from AndroidManifest.xml, and `stop` is not?

### PR DESCRIPTION
**Pull request by mpcomplete**
Previously we'd always stop org.domokit.sky.shell. If an
AndroidManifest.xml exists, we'll use the activity specified in there
instead.

Fixes https://github.com/flutter/flutter/issues/1651

### CODE REVIEW

File: packages/flutter_tools/lib/src/application_package.dart [hunk 1]
```diff
@@ -44,6 +48,36 @@ class AndroidApk extends ApplicationPackage {
...
+  }) {
+    if (!FileSystemEntity.isFileSync(manifest))
+      return null;
+    String manifestString = new File(manifest).readAsStringSync();
+    xml.XmlDocument document = xml.parse(manifestString);
+
+    Iterable<xml.XmlElement> manifests = document.findElements('manifest');
+    if (manifests.isEmpty)
+      return null;
+    String id = manifests.toList()[0].getAttribute('package');
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/application_package.dart]: Instead of `manifests.toList()[0]`, you could use `manifests.first` here.

**Comment by eseidelGoogle** [comment]
Eventually we should probably remove these defaults all together?

File: packages/flutter_tools/lib/src/application_package.dart [hunk 2]
```diff
@@ -44,6 +48,36 @@ class AndroidApk extends ApplicationPackage {
   }) : super(localPath: localPath, id: id) {
     assert(launchActivity != null);
   }
+
+  // Creates a new ApplicationPackage from the Android manifest.
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/application_package.dart]: nit: you can use `///` (dartdoc) here as it's api documentation

**Comment by devoncarew** [comment]
lgtm

File: packages/flutter_tools/lib/src/application_package.dart (hunk 1 above)
Comment (mpcomplete) [inline packages/flutter_tools/lib/src/application_package.dart]: Thanks! Done
