### PR TITLE
Don't crash on narrow window widths

### LINKED ISSUE #70521: `wrapText` throws if `text` has more leading whitespace than `columnWidth` on some line.
packages/flutter_tools/lib/src/base/utils.dart:
`wrapText` throws if `text` has more leading whitespace than `columnWidth` on some line.

### PR DESCRIPTION
**Pull request by Hixie**
I really don't remember how I ran into this, but, well, here's a fix.

Fixes https://github.com/flutter/flutter/issues/70521.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I clicked re-run on the tests, will take a look in a bit

**Comment by Hixie** [comment]
FWIW, tests are green.

File: packages/flutter_tools/lib/src/base/utils.dart [hunk 1]
```diff
@@ -274,6 +278,9 @@ class _AnsiRun {
 /// terminal window by default. If the stdout is not a terminal window, then the
 /// default will be [outputPreferences.wrapColumn].
 ///
+/// If [columnWidth] is clamped to [kMinColumnWidth] at minimum (so passing negative
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/base/utils.dart:281]: uber nit, confusing sentence. Should the `if` be removed since column width is always clamped to kMinColumnWidth

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/base/utils.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/base/utils.dart:281]: ah yeah that is the result of some bad editing. Good catch. Will fix.

**Comment by Hixie** [comment]
will land on green
