### PR TITLE
[web] fix hot restart in entrypoint generated by `flutter create`

### LINKED ISSUE #109093: Hot Restart broken on Flutter Web  with `--web-renderer html`
So I Updated my Flutter today. 

I can run my Flutter Web with 

> flutter run -d chrome --web-renderer html

without a problem. But when I want to hot restart it I just get a white screen. 

These are all of the versions of flutter, dart etc. that Im using

> Flutter 3.1.0-0.0.pre.2127 • channel master •
> https://github.com/flutter/flutter.git
> Framework • revision 792a5829e9 (2 hours ago) • 2022-08-06 13:20:08
> -0400
> Engine • revision a195b6b6f3
> Tools • Dart 2.19.0 (build 2.19.0-72.0.dev) • DevTools 2.16.0

I even created a whole new flutter web project with:

> flutter create testigo
> cd testigo
> flutter run -d chrome --web-renderer html

 and the problem persisted. So I saw the default starting screen of any new flutter project but it was not responsive. I couldn't click the increment button after hot restart

I ran flutter doctor and everything seems good as well:

> 
> [✓] Flutter (Channel master, 3.1.0-0.0.pre.2127, on macOS 12.5 21G72 darwin-x64,
>     locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
> [!] Xcode - develop for iOS and macOS
>     ✗ Xcode installation is incomplete; a full installation is necessary for iOS
>       development.
>       Download at: https://developer.apple.com/xcode/download/
>       Or install Xcode via the App Store.
>       Once installed, run:
>         sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
>         sudo xcodebuild -runFirstLaunch
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.1)
> [✓] VS Code (version 1.70.0)
> [✓] Connected device (2 available)
> [✓] HTTP Host Availability
>

### PR DESCRIPTION
**Pull request by yjbanov**
Fix entrypoint generated by `flutter create` to support hot restart. https://github.com/flutter/flutter/pull/108776 fixed hot restart, but it requires an update to `index.html`. So `flutter create` should have been updated.

Fixes https://github.com/flutter/flutter/issues/109093

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/bots/service_worker_test.dart [hunk 1]
```diff
@@ -42,13 +48,42 @@ Future<void> main() async {
...
+// Tests the entrypoint that's generated by `flutter create`.
+Future<void> runWebServiceWorkerTestWithGeneratedEntrypoint({
+  required bool headless,
+}) async {
+  await _generateEntrypoint();
+  await runWebServiceWorkerTestWithCachingResources(headless: headless, testType: ServiceWorkerTestType.generatedEntrypoint);
+}
+
+Future<void> _generateEntrypoint() async {
+  final Directory tempDirectory = Directory.systemTemp.createTempSync('flutter_web_generated_entrypoint.');
```
Comment (mdebbar) [inline dev/bots/service_worker_test.dart:71]: Is the trailing `.` in the directory name intended or a typo?

File: dev/integration_tests/web/web/.gitignore [hunk 2]
```diff
@@ -0,0 +1,2 @@
+# This file is generated by a test. It should not be committed to source control.
+generated_entrypoint.html
```
Comment (mdebbar) [inline dev/integration_tests/web/web/.gitignore:2]: Why not git-ignore the entire directory `flutter_web_generated_entrypoint/`?

File: packages/flutter_tools/templates/app_shared/web/index.html.tmpl [hunk 3]
```diff
@@ -46,11 +46,12 @@
       _flutter.loader.loadEntrypoint({
         serviceWorker: {
           serviceWorkerVersion: serviceWorkerVersion,
+        },
+        onEntrypointLoaded: function(engineInitializer) {
+          engineInitializer.initializeEngine().then(function(appRunner) {
+            appRunner.runApp();
+          });
```
Comment (mdebbar) [inline packages/flutter_tools/templates/app_shared/web/index.html.tmpl:53]: This is a potential race condition. I would suggest adding a global counter then doing:
```suggestion
        onEntrypointLoaded: function(engineInitializer) {
          currentCounter++;
          final int storedCounter = currentCounter;
          engineInitializer.initializeEngine().then(function(appRunner) {
            // Make sure this is not a stale promise.
            if (storedCounter == currentCounter) {
              appRunner.runApp();
            }
          });
```

File: dev/bots/service_worker_test.dart (hunk 1 above)
Comment (yjbanov) [reply dev/bots/service_worker_test.dart:71]: It's intended. I stole it from another test from `test.dart`. I'm now considering it a "convention" :)

File: dev/integration_tests/web/web/.gitignore (hunk 2 above)
Comment (yjbanov) [reply dev/integration_tests/web/web/.gitignore:2]: `flutter_web_generated_entrypoint` is a temp directory outside the source tree that's created then deleted (see `Directory.systemTemp.createTempSync`). It's only used as a temporary space to dump an entire project. The test actually only needs the `index.html`. It doesn't need the "counter app" Dart code.

File: packages/flutter_tools/templates/app_shared/web/index.html.tmpl (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/templates/app_shared/web/index.html.tmpl:53]: I'd like to understand more about the race condition. What is racing against what? I think if there is one, we should definitely handle it. However, I think we should avoid relying on user code to fix it (this code is generated once then it can be edited by the app developer), and instead fix the race in `flutter.js` itself.

Comment (mdebbar) [reply packages/flutter_tools/templates/app_shared/web/index.html.tmpl:53]: I was thinking of the case when `onEntrypointLoaded` is invoked again before the previous engine initialization was resolved. I don't know if this case is possible or not. Maybe if the user hot-reloads multiple times in a row?

File: dev/bots/service_worker_test.dart (hunk 1 above)
Comment (christopherfujino) [reply dev/bots/service_worker_test.dart:71]: yeah, i think a hash gets appended, so the trailing `.` looks cleaner

File: packages/flutter_tools/templates/app_shared/web/index.html.tmpl (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/templates/app_shared/web/index.html.tmpl:53]: Ah, yeah, that's a legitimate concern. However, I think it should be addressed at the `flutter.js` level, if it isn't already. `flutter.js` should be aware of which phase the loading process the app is in. For example, if `onEntrypointLoaded` has been called, `engineInitializer.initializeEngine()` has been called, but the promise hasn't resolved yet, and the user hot-restarts now, then the `Promise` from `initializeEngine` should not be resolved (or perhaps it should be rejected).

OTOH, something tells me that if our initialization process is interrupted by hot restart, then all bets are off. We have so much intricate async initialization logic - root DOM nodes, fonts, CanvasKit, service worker - that there are many places that would be easily corrupted by such interruption. Perhaps what we need is some collaboration between the framework and the tool, where the tool first sends an "intent" to hot restart, and the framework sends back a signal when it's safe to do so. I'm not sure it's practical for us to try and support hot restarts at completely random points in time.

Comment (mdebbar) [reply packages/flutter_tools/templates/app_shared/web/index.html.tmpl:53]: That's fair. If possible, we should at least print a warning (in `flutter.js`) when this race condition is detected, and ask the user to refresh the page instead.

That said, I think this race condition has existed for a while (and nobody complained) so it's probably not as important as I thought it was.

**Review by mdebbar — APPROVED** [review]
