### PR TITLE
Choose higher-res image variants on low-DPR screens

### LINKED ISSUE #44108: Images from Image.asset() pixelated on android tablets
## Steps to Reproduce

Use Image.asset() to load a image from assets (also add a 2.0x and 3.0x version according to flutter doc) like this:

```
assets/foo.png
assets/2.0x/foo.png
assets/3.0x/foo.png
```

On Android tablets (for e.g. Samsung Galaxy Tab A) this image will be pixelated. On the other hand it works perfectly fine on every iPad.

**Target Platform: Android**
**Target OS version/browser: Android 9**
**Devices: Galaxy Tab A**

I'm using mac mojave with latest flutter hotfix. My flutter doctor output is the following:

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.9.1+hotfix.6 at /Users/ikazhdan/flutter
    • Framework revision 68587a0916 (vor 7 Wochen), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ikazhdan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.5
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM T515 • R52M404D33A • android-arm • Android 9 (API 28)
```

### LINKED ISSUE #63122: Flutter Web icons look pixelated on PixelBook screen (but not external monitor)
Viewing Rive 2, I see that when I load it on my external monitor (attached to pixel book) it looks fine, but on the built in screen icons look pixelated.  @ferhatb asked me to file.

On main screen normal (100%) browser zoom:
Screenshot 2020-08-06 at 11 19 47 AM

On external monitor, normal (100%) browser zoom:
Screenshot 2020-08-06 at 11 21 02 AM

Main screen at 200% browser zoom:
Screenshot 2020-08-06 at 12 52 06 PM

External Monitor 200% browser zoom:
Screenshot 2020-08-06 at 12 52 22 PM

I believe Rive2 uses the CanvasKit backend?

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Choose higher-res image variants on low device-pixel ratio screens.

Entry-level and mid-range laptops, desktop monitors, and some entry-level tablets, have screens with low device-pixel ratios (<2.0). Choosing a lower resolution image results in visible scaling artifacts (https://github.com/flutter/flutter/issues/63122). This PR changes the logic such that we choose higher-res image variants on low device-pixel ratio screens.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/63122
Fixes https://github.com/flutter/flutter/issues/44108

## Tests

Updated `image_resolution_test.dart`.

### CODE REVIEW

File: packages/flutter/lib/src/painting/image_resolution.dart [hunk 1]
```diff
@@ -34,18 +38,52 @@ const String _kAssetManifestFileName = 'AssetManifest.json';
...
+///
+/// For example, for a screen with device pixel ratio 1.25 the image chosen
+/// would be 2.0x/heart.png, even though heart.png (i.e. 1.0) is closer. This
+/// is because the screen is considered low-resolution. For a screen with
+/// device pixel ratio of 2.25 the image chosen would also be 2.0x/heart.png.
+/// This is because the screen is considered to be a high-resolution screen,
+/// and therefore upscaling a 2.0x image to 2.25 won't result in visible
+/// upscaling artifacts. However, for a screen with device-pixel ratio 3.25 the
+/// image chosen would be 4.0x/heart.png because it's closer to 4.0 than it is
+/// to 2.0.
```
Comment (mdebbar) [inline packages/flutter/lib/src/painting/image_resolution.dart:74]: Doesn't this depend on how much upscaling is happening? Like upscaling from 1.0 to 1.25 is a 25% increase, but 2.0 to 2.25 is only a 12.5% increase.

I'm just throwing an idea out there in case it makes sense to you: what if, instead of having a 2.0 DPR limit, we check the upscaling factor and decide based on that. i.e. set a 20% upscale limit.

**Review by jonahwilliams — APPROVED** [review]
LGTM - this is the heuristic we decided to go with for now. but we also need an issue tracking improvements to this solution.

File: packages/flutter/lib/src/painting/image_resolution.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter/lib/src/painting/image_resolution.dart:74]: It's not very predictable. Even a 5% upscale can visibly degrade the image depending on the upscale algorithm, because no matter how big or small the scale all pixels are affected.

Comment (mdebbar) [reply packages/flutter/lib/src/painting/image_resolution.dart:74]: Okay then this looks good to me.

**Review by mdebbar — APPROVED** [review]

**Comment by yjbanov** [comment]
I don't have the exact device to test it, but I'm assuming this is also fixing https://github.com/flutter/flutter/issues/44108.

File: packages/flutter/lib/src/painting/image_resolution.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/painting/image_resolution.dart:74]: I would kind of prefer not documenting the vagaries of how we determine this in this way - maybe just as a `//` comment instead of a doc comment.

The concern being that I really think this method is not going to stand up to the test of time, and it'll be "more" breaking since we documented all these implementation details.

**Review by dnfield — APPROVED** [review]
LGTM with concern about being overly-specific in documentation.

As we discussed offline - this seems like an improvement for some cases that are really bad right now, but I still am not 100% convinced this is going to be a good long term solution.

File: packages/flutter/lib/src/painting/image_resolution.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter/lib/src/painting/image_resolution.dart:74]: This is more observable by the developer and their users than a typical implementation detail. Developers are the ones supplying the asset variants and without knowing how we choose them won't know which ones to provide (e.g. https://github.com/flutter/flutter/issues/44108#issuecomment-583292205). I'd prefer not hiding these docs.

> this method is not going to stand up to the test of time

That's fine, we'll just update the docs. I expect we will expand the functionality (e.g. improve physical pixel density detection, support scaled images), but I don't expect much will change otherwise as far as the developer is concerned. Provided there is no extra image scaling, this method should be pretty close to ideal (just like, provided that speeds are small enough and objects big enough, Newtonian physics is close to ideal).

**Review by goderbauer — APPROVED** [review]
LGTM
