### PR TITLE
MediaQuery picks up view data changes

### LINKED ISSUE #165519: Can't update root MediaQuery.fromView when view values change
In a test, I want to set a value that comes in from the FlutterView and is looked up on MediaQuery, but it doesn't seem to be possible without a hack. I'm wondering if this is a bug or working as intended.

The tl;dr is that _MediaQueryFromViewState does not update its data when values on the view change.

https://github.com/flutter/flutter/blob/bf3826d2ce928dc8ed0d66c0aeb4c8c3a86705ab/packages/flutter/lib/src/widgets/media_query.dart#L1885-L1887

Instead of just checking if the entire view changed, should it check if any data on the view changed?

```dart
    final MediaQueryData newData = MediaQueryData.fromView(widget.view, platformData: _parentData);
    if (_data == null || oldWidget.view != widget.view || newData != _data) {
      _updateData();
    }
```

### Repro case

This test fails.

```dart
testWidgets('Cannot update root MediaQuery.fromView', (WidgetTester tester) async {
  late final BuildContext context1;
  await tester.pumpWidget(
    MaterialApp(
      home: Material(
        child: Builder(
          builder: (BuildContext context) {
            context1 = context;
            return const SizedBox.shrink();
          },
        ),
      ),
    ),
  );

  final bool isSupported1 = MediaQuery.maybeSupportsShowingSystemContextMenu(context1) ?? false;

  expect(isSupported1, isFalse);

  TestWidgetsFlutterBinding.instance.platformDispatcher.supportsShowingSystemContextMenu = true;
  addTearDown(() async {
    TestWidgetsFlutterBinding.instance.platformDispatcher
        .resetSupportsShowingSystemContextMenu();
  });

  late final BuildContext context2;
  // _MediaQueryFromViewState.didUpdateWidget is called, but it doesn't update its data.
  await tester.pumpWidget(
    MaterialApp(
      home: Material(
        child: Builder(
          builder: (BuildContext context) {
            context2 = context;
            return const SizedBox.shrink();
          },
        ),
      ),
    ),
  );

  final bool isSupported2 = MediaQuery.maybeSupportsShowingSystemContextMenu(context2) ?? false;

  // This fails.
  expect(isSupported2, isTrue);
});
```

<details>

<summary>Workaround to hack the test so it works</summary>

After modifying the view, call didChangeMetrics to force the _MediaQueryFromViewState to update its data.

```dart
  expect(find.byType(MediaQuery), findsOneWidget);
  final WidgetsBindingObserver widgetsBindingObserver =
      tester.state(
            find.ancestor(
              of: find.byType(MediaQuery),
              matching: find.byWidgetPredicate(
                (Widget w) => '${w.runtimeType}' == '_MediaQueryFromView',
              ),
            ),
          )
          as WidgetsBindingObserver;
  widgetsBindingObserver.didChangeMetrics();
```

</details>

This bug was discovered in https://github.com/flutter/flutter/pull/165354#discussion_r1999849170.

### PR DESCRIPTION
**Pull request by justinmc**
This fixes a bug in MediaQuery's update logic and removes some now-unnecessary workaround code.

Fixes https://github.com/flutter/flutter/issues/165519

Discovered in https://github.com/flutter/flutter/pull/165354#discussion_r1999849170

### CODE REVIEW

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 1]
```diff
@@ -1882,7 +1882,9 @@ class _MediaQueryFromViewState extends State<_MediaQueryFromView> with WidgetsBi
     if (widget.ignoreParentData != oldWidget.ignoreParentData) {
       _updateParentData();
     }
-    if (_data == null || oldWidget.view != widget.view) {
+    if (_data == null ||
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/media_query.dart:1885]: A pattern I notice in this file is `didChange*()` which updates the `MediaQueryData`. These notifications are sent from the embedder. I wonder if that's the pattern we should be following here, what do you think?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/media_query.dart:1885]: Ah you're saying that I could add a WidgetsBindingObserver.didChangeViewData and call that instead of didChangeMetrics? In this case I only need the method for tests, so I worry about bloating the  WidgetsBindingObserver API just for my that. And anyway I'd still have to use my hacky _updateMediaQueryFromView method in the tests.

I looked into seeing if there's a better way to send these kinds of messages from the embedder to trigger didChangeMetrics instead of directly calling it on the  WidgetsBindingObserver instance, but I found other tests were doing the same thing as me, e.g. https://github.com/flutter/flutter/blob/2615ab6c1932e44e6802aaba8dc715b387ff155f/packages/flutter/test/widgets/editable_text_test.dart#L15928

It seems to me like this should be checking if the data has changed anyway.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/media_query.dart:1887]: After talking to @Renzo-Olivares offline, I'm now trying to directly trigger _updateData when supportsShowingContextMenu changes. Inspired by https://github.com/flutter/flutter/pull/166836.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/media_query.dart]: @Renzo-Olivares I've set this up so that I can trigger the change through the PlatformDispatcher, similar to changes to the theme brightness etc. Let me know what you think.

File: packages/flutter/test/widgets/media_query_test.dart [hunk 2]
```diff
@@ -262,6 +262,57 @@ void main() {
     },
   );
 
+  testWidgets('MediaQueryData.fromView picks up new view data when rebuilding', (
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/media_query_test.dart:265]: nit: should we rename this test to mention support showing system context menu.

File: packages/flutter/test/widgets/media_query_test.dart [hunk 3]
```diff
@@ -262,6 +262,57 @@ void main() {
...
+        ),
+      ),
+    );
+
+    expect(datas1, hasLength(1));
+    expect(datas1.first.supportsShowingSystemContextMenu, isFalse);
+
+    tester.platformDispatcher.supportsShowingSystemContextMenu = true;
+    tester.binding.handleSupportsShowingSystemContextMenuChanged();
+    addTearDown(() {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/media_query_test.dart:291]: Can these be added to the `addTearDown` at the top of this test?

File: packages/flutter/test/widgets/media_query_test.dart [hunk 4]
```diff
@@ -262,6 +262,57 @@ void main() {
...
+          },
+        ),
+      ),
+    );
+
+    expect(datas1, hasLength(1));
+    expect(datas1.first.supportsShowingSystemContextMenu, isFalse);
+
+    tester.platformDispatcher.supportsShowingSystemContextMenu = true;
+    tester.binding.handleSupportsShowingSystemContextMenuChanged();
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/media_query_test.dart:290]: Does this have to be explicitly called?

File: packages/flutter/test/widgets/media_query_test.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/test/widgets/media_query_test.dart:291]: Yes good call.

File: packages/flutter/test/widgets/media_query_test.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/media_query_test.dart]: Yeah it looks like your current implementation is in line with the pattern we use for other APIs in `platformDispatcher`.

File: engine/src/flutter/lib/ui/platform_dispatcher.dart [hunk 5]
```diff
@@ -1142,6 +1142,17 @@ class PlatformDispatcher {
...
 
+  /// A callback that is invoked whenever [supportsShowingSystemContextMenu]
+  /// changes.
+  VoidCallback? get onSupportsShowingSystemContextMenuChanged =>
+      _onSupportsShowingSystemContextMenuChanged;
+  VoidCallback? _onSupportsShowingSystemContextMenuChanged;
+  Zone _onSupportsShowingSystemContextMenuChangedZone = Zone.root;
+  set onSupportsShowingSystemContextMenuChanged(VoidCallback? callback) {
+    _onSupportsShowingSystemContextMenuChanged = callback;
+    _onSupportsShowingSystemContextMenuChangedZone = Zone.current;
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/ui/platform_dispatcher.dart:1153]: Why was the analyzer complaining about the `Zone` related code removed from the `web_ui/lib/src/engine/platform_dispatcher.dart`?

File: packages/flutter/test/widgets/media_query_test.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/test/widgets/media_query_test.dart]: That test confuses me because it sets the brightness to `light`, then expects that it's still `dark`...

But this is my understanding of the situation as I've been working on this PR. Each time you test a file with `flutter test`, a single top-level View gets created. When you run `pumpWidgets`, those widgets get put into this View, and the View has [its own top-level MediaQuery](https://github.com/flutter/flutter/blob/6b6f49e74923fa872e246895b548496403867d0c/packages/flutter/lib/src/widgets/view.dart#L275) widget. So even though you might call `pumpWidgets` with a whole new MaterialApp, you still have the same old top level MediaQuery widget.

When I change the view data with something like:

```dart
tester.platformDispatcher.supportsShowingSystemContextMenu = true;
```

That MediaQuery widget does not automatically update. It still has its old view data until you call [_updateData](https://github.com/flutter/flutter/blob/e841350bfc86a3d3e0377cddb8974594e752fc15/packages/flutter/lib/src/widgets/media_query.dart#L1896) one way or another. In my case, I've set up handleSupportsShowingSystemContextMenuChanged to call _updateData.

Note that this situation doesn't matter when running a single test. If you set tester.platformDispatcher.supportsShowingSystemContextMenu in the initial `setup` before that top-level MedaiQuery.fromView gets instantiated, then it will pick up your value when it does get created.

File: engine/src/flutter/lib/ui/platform_dispatcher.dart (hunk 5 above)
Comment (justinmc) [reply engine/src/flutter/lib/ui/platform_dispatcher.dart:1153]: It complained that it was unused. I had just copied it from the similar code for textScaler or something.

**Comment by justinmc** [comment]
@Renzo-Olivares Ready for re-review. Thanks for the suggestion here. Your approach worked, but I had to also add an extra pumpWidget in the teardown in order to reset the value for subsequent tests.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 6]
```diff
@@ -8839,18 +8839,29 @@ void main() {
...
-          TestWidgetsFlutterBinding.instance.platformDispatcher
-              .resetSupportsShowingSystemContextMenu();
-          _updateMediaQueryFromView(tester);
+        tester.platformDispatcher.supportsShowingSystemContextMenu = true;
+        addTearDown(() async {
+          tester.platformDispatcher.resetSupportsShowingSystemContextMenu();
+          // Pump one more root view to replace it with one that reads the
+          // updated reset value of supportsShowingSystemContextMenu for
+          // subsequent tests..
+          await tester.pumpWidget(
```
Comment (Renzo-Olivares) [inline packages/flutter/test/cupertino/text_field_test.dart:8848]: I think we can use `tester.view.reset()` instead of pumping another root view. Found that here https://github.com/flutter/flutter/blob/5da19ccfbc17643fdd7e00615a369070d43e2055/packages/flutter/test/widgets/media_query_test.dart#L407

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
Thanks @Renzo-Olivares for all the help making this PR clean!
