### PR TITLE
Change how navigator prevents redundant operations

### LINKED ISSUE #4716: Navigator.push does not work within a PopupMenuButton
## Steps to Reproduce

I made a demo app that has various buttons triggering Navigator.pushState. When called from a PopupMenuButton the MaterialPageRoute builder never gets called.

The normal buttons in the actionbar and body work fine.

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primarySwatch: Colors.blue),
      home: new FlutterDemo()));
}

class FlutterDemo extends StatelessWidget {
  FlutterDemo({Key key}) : super(key: key);

  void push(BuildContext context) {
    Navigator.push(context,
        new MaterialPageRoute(builder: (BuildContext context) {
      return new OtherRoute();
    }));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text("Demo"), actions: [
          new FlatButton(
              child: new Text("push"), onPressed: () => push(context)),
          new PopupMenuButton(onSelected: (String item) {
            push(context);
          }, itemBuilder: (BuildContext context) {
            return [
              new PopupMenuItem(value: "push", child: new Text("push route"))
            ];
          })
        ]),
        body: new Column(children: [
          new RaisedButton(
              child: new Text("push route"), onPressed: () => push(context)),
          new PopupMenuButton(onSelected: (String item) {
            push(context);
          }, itemBuilder: (BuildContext context) {
            return [
              new PopupMenuItem(value: "push", child: new Text("push route"))
            ];
          })
        ]));
  }
}

class OtherRoute extends StatelessWidget {
  OtherRoute({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text("other route")),
        body: new Center(child: new Text("push route")));
  }
}
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 4f133a6775 (15 hours ago), engine revision 161496dff3

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

```

## Logs and Crash Reports

No logs are generated. If you add a print to the builder of the route it won't get output.

### PR DESCRIPTION
**Pull request by abarth**
Instead of requiring transactions, we now cancel all active pointers that
are interacting with the navigator and absorb future pointers until we get
a chance to build. This approach isn't perfect (e.g., events that trigger
off the cancelled pointers could still interact with the navigator), but it
should be better than the current transaction-based approach.

Fixes #4716

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -501,25 +478,24 @@ class NavigatorState extends State<Navigator> {
...
+  }
+
+  void _cancelActivePointers() {
+    BuildContext overlayContext = _overlayKey.currentContext;
+    if (overlayContext != null) {
+      RenderAbsorbPointer absorber = overlayContext.ancestorRenderObjectOfType(const TypeMatcher<RenderAbsorbPointer>());
+      absorber?.absorbing = true;
+    }
+    for (int pointer in _activePointers.toList())
+      WidgetsBinding.instance.cancelPointer(pointer);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: This will also cancel gesture recognisers dealing with those pointers outside the navigator.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: (add this to our "we still need to fix this for real" bug)

File: packages/flutter/lib/src/widgets/basic.dart [hunk 2]
```diff
@@ -2616,6 +2616,41 @@ class IgnorePointer extends SingleChildRenderObjectWidget {
   }
 }
 
+/// A widget that absorbs pointers during hit testing.
+///
+/// When [absorbing] is `true`, this widget prevents its subtree from receiving
+/// pointer events by terminating hit testing at itself. It still consumes space
+/// during layout and paints its child as usual. It just prevents its children
+/// from being the target of located events, because it returns `true` from
+/// [hitTest].
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: it doesn't return true from hitTest, its render object does

File: packages/flutter/lib/src/widgets/basic.dart [hunk 3]
```diff
@@ -2616,6 +2616,41 @@ class IgnorePointer extends SingleChildRenderObjectWidget {
...
+class AbsorbPointer extends SingleChildRenderObjectWidget {
+  /// Creates a widget that absorbs pointers during hit testing.
+  ///
+  /// The [absorbing] argument must not be null
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: missing period

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 4]
```diff
@@ -489,6 +489,8 @@ class HeroController extends NavigatorObserver {
   }
 
   void _updateQuest(Duration timeStamp) {
+    if (navigator == null)
+      return;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: add a comment explaining that this can be true if the navigator is disposed between the time we received didPush/didPop, and the end of the next frame, since _updateQuest is scheduled to run on a post-frame callback.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 5]
```diff
@@ -210,12 +210,8 @@ class Navigator extends StatefulWidget {
   /// The route name will be passed to that navigator's [onGenerateRoute]
   /// callback. The returned route will be pushed into the navigator. The set of
   /// most valuable keys will be used to construct an appropriate [Hero] transition.
-  ///
-  /// Uses [openTransaction()]. Only one transaction will be executed per frame.
   static void pushNamed(BuildContext context, String routeName, { Set<Key> mostValuableKeys }) {
-    openTransaction(context, (NavigatorTransaction transaction) {
-      transaction.pushNamed(routeName, mostValuableKeys: mostValuableKeys);
-    });
+    of(context).pushNamed(routeName, mostValuableKeys: mostValuableKeys);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: for clarity and for copy-paste sanity, always refer to `Navigator.of` even within `Navigator`.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 6]
```diff
@@ -501,25 +478,21 @@ class NavigatorState extends State<Navigator> {
...
+  void _handlePointerDown(PointerDownEvent event) {
+    _activePointers.add(event.pointer);
+  }
+
+  void _handlePointerUpOrCancel(PointerEvent event) {
+    _activePointers.remove(event.pointer);
+  }
+
+  void _cancelActivePointers() {
+    RenderAbsorbPointer absorber = _overlayKey.currentContext?.ancestorRenderObjectOfType(const TypeMatcher<RenderAbsorbPointer>());
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: just put a global key on the AbsordPointer widget

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 7]
```diff
@@ -501,25 +478,21 @@ class NavigatorState extends State<Navigator> {
...
+    absorber?.absorbing = true;
+    for (int pointer in _activePointers.toList())
+      WidgetsBinding.instance.cancelPointer(pointer);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: add a TODO pointing to https://github.com/flutter/flutter/issues/4770

File: packages/flutter/test/widget/navigator_test.dart [hunk 8]
```diff
@@ -124,4 +124,70 @@ void main() {
...
+    await tester.tap(find.text('left'));
+    expect(log, equals(<String>['left']));
+    await tester.tap(find.text('right'));
+    expect(log, equals(<String>['left']));
+  });
+
+  // This test doesn't work because the testing framework uses a fake version of
+  // the pointer event dispatch loop.
+  //
+  // TODO(abarth): Test more of the real code and enable this test.
```
Comment (Hixie) [inline packages/flutter/test/widget/navigator_test.dart]: file a bug for this or we'll forget it forever...

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/test/widget/navigator_test.dart (hunk 8 above)
Comment (abarth) [inline packages/flutter/test/widget/navigator_test.dart]: Done. https://github.com/flutter/flutter/issues/4771
