### PR TITLE
[tool] makes listing a shader also as an asset a build failure

### LINKED ISSUE #126829: FragmentProgram.fromAsset throws misleading exception
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter app with a shader. For example, https://github.com/flutter/samples/tree/main/simple_shader.
2. Edit `pubspec.yaml` so that the path to the shader is _also_ included in the `assets` record:

```yaml
...

flutter:
  # Add this.
  assets:
    - shaders/

  shaders:
    - shaders/simple.frag
```

Note that this can easily happen if one wants to have shaders next to related pictures, for example. In my case, I had a folder called `assets/patterns/` which included pattern PNGs as well as a fragment shader for simple cross hatch patterns.

3. Try running the program.

### Expected results

Program runs. Or it fails at compile time, telling me something like "shader cannot be compiled since it's already included in the asset bundle".

### Actual results

Program fails at runtime. 

    Exception: Asset 'shaders/simple.frag' does not contain valid shader data.

It looks like having the shader (even unintentionally) in `assets` prevents the mechanism behind shader support from firing. 

The resulting error is a red herring. I spent an hour trying to "fix" the fragment shader.

### Code sample

https://github.com/flutter/samples/blob/main/simple_shader/ + changes above

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Asset 'shaders/diagonal_crosshatch.frag' does not contain valid shader data.
#0      new FragmentProgram._fromAsset (dart:ui/painting.dart:4328:7)
#1      FragmentProgram.fromAsset.<anonymous closure> (dart:ui/painting.dart:4355:55)
#2      new Future.microtask.<anonymous closure> (dart:async/future.dart:280:37)
#3      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/filiph/fvm/versions/beta
    ! Warning: `flutter` on your path resolves to /Users/filiph/fvm/versions/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/filiph/fvm/versions/beta. Consider adding /Users/filiph/fvm/versions/beta/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/filiph/fvm/versions/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/filiph/fvm/versions/beta. Consider adding /Users/filiph/fvm/versions/beta/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/126829

Turns listing an asset as a `shader` and an `asset` a build error.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/asset.dart [hunk 1]
```diff
@@ -1070,6 +1070,22 @@ class ManifestAssetBundle implements AssetBundle {
     });
 
     for (final Uri shaderUri in flutterManifest.shaders) {
+      for (final AssetsEntry assetEntry in flutterManifest.assets) {
+        final String assetPath = assetEntry.uri.path;
+        final String shaderPath = shaderUri.path;
+        if (assetPath == shaderPath) {
+          _logger.printError(
+            'Error: Shader "$shaderPath" is also defined as an asset. Shaders should only be defined in the "shaders" section of the pubspec.yaml, not in the "assets" section.',
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/asset.dart]: Nit: can we split these log messages across multiple lines to keep them below 100 characters?

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/asset.dart (hunk 1 above)
Comment (gaaclarke) [reply packages/flutter_tools/lib/src/asset.dart]: done
