### PR TITLE
Dispose ImmutableBuffer at web_ui.instantiateImageCodecFromBuffer and web_ui.instantiateImageCodecWithSize

### LINKED ISSUE #150016: instantiateImageCodecWithSize leaks buffer on web
### Steps to reproduce

The [documentation](https://api.flutter.dev/flutter/dart-ui/instantiateImageCodecWithSize.html) for this method states:
`The buffer will be disposed by this method once the codec has been created, so the caller must relinquish ownership of the buffer when they call this method.`

While this is true on non-web platforms as shown below:
[dart:ui](https://github.com/flutter/engine/blob/7a06574d5bcf48c88e17cae888749c2ba8b52adb/lib/ui/painting.dart#L2301)

On web, you can see that only the codec is disposed but not the buffer, and the buffer isn't cleared in any of the called functions since it passes the underlying `.list` and not the buffer itself:
[web:ui](https://github.com/flutter/engine/blob/7a06574d5bcf48c88e17cae888749c2ba8b52adb/lib/web_ui/lib/painting.dart#L516)

This is different from my previously filed [issue](https://github.com/flutter/flutter/issues/147066) since that describes a leaking image, not a leaking buffer.

### Expected results

All platforms should dispose the provided buffer.

### Actual results

The web platform doesn't dispose the buffer, so to prevent a double disposal, one must special case the disposal for web so it is properly cleaned up on web/non-web platforms.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19044.4291], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.5)
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/150016

Fixed `instantiateImageCodecFromBuffer` and `instantiateImageCodecWithSize` and added tests.

doc

> The buffer will be disposed by this method once the codec has been created, so the caller must relinquish ownership of the buffer when they call this method.

* https://api.flutter.dev/flutter/dart-ui/instantiateImageCodecFromBuffer.html
* https://api.flutter.dev/flutter/dart-ui/instantiateImageCodecWithSize.html

ui

https://github.com/flutter/flutter/blob/bd1ebf2e1498bd022808f8b237654ce42ae537be/engine/src/flutter/lib/ui/painting.dart#L2484-L2504
https://github.com/flutter/flutter/blob/bd1ebf2e1498bd022808f8b237654ce42ae537be/engine/src/flutter/lib/ui/painting.dart#L2541-L2558

web_ui

https://github.com/flutter/flutter/blob/bd1ebf2e1498bd022808f8b237654ce42ae537be/engine/src/flutter/lib/web_ui/lib/painting.dart#L640-L679

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/painting.dart [hunk 1]
```diff
@@ -642,39 +642,49 @@ Future<Codec> instantiateImageCodecFromBuffer(
...
+}) {
+  try {
+    return engine.renderer.instantiateImageCodec(
+      buffer._list!,
+      targetWidth: targetWidth,
+      targetHeight: targetHeight,
+      allowUpscaling: allowUpscaling,
+    );
+  } finally {
+    buffer.dispose();
```
Comment (polina-c) [inline engine/src/flutter/lib/web_ui/lib/painting.dart:654]: This look wrong for me. An object is expected to be disposed by its creator. And buffer is not created here.

Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/painting.dart:654]: I fixed it according to the issue and dartdoc, but it looks good to me too that "An object is expected to be disposed by its creator.".

**Comment by kevmoo** [comment]
@koji-1009 – looks like we need a rebase

File: packages/flutter/lib/src/painting/image_decoder.dart [hunk 2]
```diff
@@ -24,7 +24,16 @@ import 'binding.dart';
...
 Future<ui.Image> decodeImageFromList(Uint8List bytes) async {
   final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(bytes);
-  final ui.Codec codec = await PaintingBinding.instance.instantiateImageCodecWithSize(buffer);
-  final ui.FrameInfo frameInfo = await codec.getNextFrame();
-  return frameInfo.image;
+  try {
+    final ui.Codec codec = await PaintingBinding.instance.instantiateImageCodecWithSize(buffer);
+    final ui.FrameInfo frameInfo;
+    try {
+      frameInfo = await codec.getNextFrame();
```
Comment (kevmoo) [inline packages/flutter/lib/src/painting/image_decoder.dart:31]: Could you just put `return await codec.getNextFrame();` here?

File: engine/src/flutter/lib/web_ui/lib/painting.dart (hunk 1 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/painting.dart]: I have added a fix. Perhaps adding a mechanism to track `ImmutableBuffer` and `ImageDescriptor` leaks would make it easier to find them.

This fix conflicts with https://github.com/flutter/flutter/pull/159945 and I will rebase later 👍

File: packages/flutter/lib/src/painting/image_decoder.dart (hunk 2 above)
Comment (koji-1009) [reply packages/flutter/lib/src/painting/image_decoder.dart]: Thank you. [9a63a86](https://github.com/flutter/flutter/pull/161488/commits/9a63a8693ad796171006b0b1cd8dc7a34f6d6f08)

**Review by polina-c — DISMISSED** [review]

**Review by matanlurey — CHANGES_REQUESTED** [review]
The PR says "[fixes] instantiateImageCodecWithSize leaks buffer on web", but the files you changed in this PR are specific to the native engine (the web engine is at `engine/src/flutter/lib/web_ui/lib/painting.dart`).

Can you clarify what this PR is or is not doing?

I'll also add @jonahwilliams from the native engine side.

**Comment by koji-1009** [comment]
@matanlurey 
Thanks for the review.

In this PR, the issue was finally fixed in `packages/flutter/lib/src/painting/image_decoder.dart` and `packages/flutter/lib/src/painting/image_provider.dart`. 

---

The PR had modified the web implementation in the first two commits.

* [d0fc7c9](https://github.com/flutter/flutter/pull/161488/commits/d0fc7c903ae269cb8ba0ccbe34901c6fb13bf1ad)
* [09975ec](https://github.com/flutter/flutter/pull/161488/commits/09975ecd5414480938e088105dac6ab5a6a50659)

Then, I received a review comment from @polina-c. https://github.com/flutter/flutter/pull/161488#discussion_r1926223549

> An object is expected to be disposed by its creator. And buffer is not created here. The same applies for other parts.

After checking the code again, it looked like it would be a good idea to dispose the buffer in the function that generated it. Therefore, the process was changed to dispose of the buffer using try-finally at [02c9342](https://github.com/flutter/flutter/pull/161488/commits/02c9342c72ce408c50600121eb710a8a1a8478be).

This is the web leakage problem that the PR resolves; it is the reason why the non-web code is being modified.

File: engine/src/flutter/lib/ui/painting.dart [hunk 3]
```diff
@@ -2551,17 +2551,13 @@ Future<Codec> instantiateImageCodecWithSize(
...
-  try {
-    final TargetImageSize targetSize = getTargetSize(descriptor.width, descriptor.height);
-    assert(targetSize.width == null || targetSize.width! > 0);
-    assert(targetSize.height == null || targetSize.height! > 0);
-    return descriptor.instantiateCodec(
-      targetWidth: targetSize.width,
-      targetHeight: targetSize.height,
-    );
-  } finally {
-    buffer.dispose();
```
Comment (matanlurey) [inline engine/src/flutter/lib/ui/painting.dart:2563]: Why was this moved from `instantiateImageCodecWithSize`?

`instantiateImageCodecWithSize` is still a public API, so now we've introduced a breaking change (memory leak) where previously calls to `instantiateImageCodecWithSize` used to dispose the buffer (in fact the documentation above) still states it:

```dart
/// The [buffer] will be disposed by this method once the codec has been created.
```

... and now it won't.

File: packages/flutter/lib/src/painting/image_decoder.dart [hunk 4]
```diff
@@ -24,12 +24,15 @@ import 'binding.dart';
 /// in tests.
 Future<ui.Image> decodeImageFromList(Uint8List bytes) async {
   final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(bytes);
-  final ui.Codec codec = await PaintingBinding.instance.instantiateImageCodecWithSize(buffer);
-  final ui.FrameInfo frameInfo;
   try {
-    frameInfo = await codec.getNextFrame();
+    final ui.Codec codec = await PaintingBinding.instance.instantiateImageCodecWithSize(buffer);
```
Comment (matanlurey) [inline packages/flutter/lib/src/painting/image_decoder.dart:28]: If `instantiateImageCodecWithSize` ends up restoring the dispose, then there is no reason to dispose here.

File: engine/src/flutter/lib/ui/painting.dart [hunk 5]
```diff
@@ -2460,10 +2464,6 @@ Future<Codec> instantiateImageCodec(
 /// The data can be for either static or animated images. The following image
 /// formats are supported: {@macro dart.ui.imageFormats}
 ///
-/// The [buffer] will be disposed by this method once the codec has been created,
```
Comment (matanlurey) [inline engine/src/flutter/lib/ui/painting.dart:2463]: If `instantiateImageCodecWithSize` is restored, then this comment should not be removed.

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 6]
```diff
@@ -1618,9 +1618,15 @@ class FileImage extends ImageProvider<FileImage> {
...
     }
-    return (file.runtimeType == File)
-        ? decode(await ui.ImmutableBuffer.fromFilePath(file.path))
-        : decode(await ui.ImmutableBuffer.fromUint8List(await file.readAsBytes()));
+    final ui.ImmutableBuffer buffer =
+        (file.runtimeType == File)
+            ? await ui.ImmutableBuffer.fromFilePath(file.path)
+            : await ui.ImmutableBuffer.fromUint8List(await file.readAsBytes());
+    try {
+      return await decode(buffer);
```
Comment (matanlurey) [inline packages/flutter/lib/src/painting/image_provider.dart:1626]: @jonahwilliams is it always safe to assume that `decode` will not take ownership of the buffer?

(If so, we should update the documentation on ImageProvider)

**Review by matanlurey — CHANGES_REQUESTED** [review]
I'll admit I still don't really understand this change, or how it makes things better, but left some questions to continue to clarify.

File: engine/src/flutter/lib/ui/painting.dart (hunk 3 above)
Comment (koji-1009) [reply engine/src/flutter/lib/ui/painting.dart:2563]: It would be better to revert this change so as not to create breaking change.
And it would be good to have the first PR and the fix that calls `ImageDescriptor.dispose` reviewed again.

I considered it necessary to make this change as the review had stopped after I submitted my PR. However, it appears to be unnecessary. My aim is to fix https://github.com/flutter/flutter/issues/150016 and avoid the leak by calling `ImageDescriptor.dispose`. For this reason, I have no objection to revert [02c9342](https://github.com/flutter/flutter/pull/161488/commits/02c9342c72ce408c50600121eb710a8a1a8478be).

File: engine/src/flutter/lib/web_ui/lib/painting.dart [hunk 7]
```diff
@@ -642,39 +642,49 @@ Future<Codec> instantiateImageCodecFromBuffer(
...
   ImmutableBuffer buffer, {
   TargetImageSizeCallback? getTargetSize,
 }) async {
-  if (getTargetSize == null) {
-    return engine.renderer.instantiateImageCodec(buffer._list!);
-  } else {
-    final Codec codec = await engine.renderer.instantiateImageCodec(buffer._list!);
-    try {
-      final FrameInfo info = await codec.getNextFrame();
+  try {
```
Comment (jonahwilliams) [inline engine/src/flutter/lib/web_ui/lib/painting.dart:662]: Rather than 3 nested try-finallys, you can let all of the disposable types be nullable, declare them once, and then in a single finally block do a `?.dispose()`

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by matanlurey — APPROVED** [review]

**Comment by polina-c** [comment]
I trust other reviewers here. Thanks for taking my concerns into account.

**Comment by kevmoo** [comment]
Are we okay to flip `auto-sumbmit` here Dashers?

**Review by mdebbar — APPROVED** [review]
LGTM

**Comment by kevmoo** [comment]
@mdebbar – `autosubmit`?

**Comment by mdebbar** [comment]
> @mdebbar – `autosubmit`?

This hasn't been rebased in a while. Let's rebase first.
