### PR TITLE
Prevent disabled cupertino textfield from being edited with voiceover/talkback

### LINKED ISSUE #40384: Disabled Cupertino text field is editable with Talkback
To reproduce, visit the gallery text field demo and enable TalkBack. Focus the reading club text field. Note that the keyboard can be used to enter text. This text is removed when focus is lost.

### PR DESCRIPTION
**Pull request by rami-a**
## Description

Currently, you can edit disabled `CupertinoTextField`s when voiceover/talkback is on. This change prevents that.

## Related Issues

Closes #40384

## Tests

I added the following tests:

* Tests to check the semantics of the textfield when either enabled or disabled

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by JoseAlba — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 1]
```diff
@@ -3944,4 +3944,69 @@ void main() {
     await tester.pump();
     expect(focusNode3.hasPrimaryFocus, isTrue);
   });
+
+  testWidgets('Cupertino text field semantics', (WidgetTester tester) async {
+    final SemanticsHandle handle = tester.ensureSemantics();
```
Comment (johnsonmh) [inline packages/flutter/test/cupertino/text_field_test.dart]: I don't think you need to create and dispose this handle. I'm pretty sure semantics are enabled by default in all widget tests.

https://api.flutter.dev/flutter/flutter_test/testWidgets.html

**Review by johnsonmh — APPROVED** [review]
```
██╗      ██████╗ ████████╗███╗   ███╗
██║     ██╔════╝ ╚══██╔══╝████╗ ████║
██║     ██║  ███╗   ██║   ██╔████╔██║
██║     ██║   ██║   ██║   ██║╚██╔╝██║
███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝
```

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/test/cupertino/text_field_test.dart]: you're right, done

**Review by HansMuller — APPROVED** [review]
LGTM
