### PR TITLE
Fix the "Missing ExternalProject for :" error

### LINKED ISSUE #168296: "Missing ExternalProject for :"
### Steps to reproduce

1. Create an empty project e.g. via `flutter create demo`
2. Open the android directory in Android Studio

### Expected results

The Gradle project could be opened on Windows 

### Actual results

You get a strange Gradle error:

    Missing ExternalProject for :

### Code sample

<details open><summary>Code sample</summary>

Fix idea:
https://github.com/rekire/flutter-fork/pull/1/commits/335484eccbe774987e8a09cbf7016b784aa19de9

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by rekire**
Fix the "Missing ExternalProject for :" error

This fixes #168296

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/file_system.dart [hunk 1]
```diff
@@ -63,7 +63,20 @@ class FileSystemUtils {
   ///
   /// On Windows it replaces all '\' with '\\'. On other platforms, it returns the
   /// path unchanged.
-  String escapePath(String path) => _platform.isWindows ? path.replaceAll(r'\', r'\\') : path;
+  String escapePath(String path) {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/base/file_system.dart:66]: This can be simplified:

```dart
String escapePath(String path) {
  if (_platform.isWindows) {
    path = path.replaceAll(r'\', r'\\');
    if (path.startsWith(RegExp('[a-z]:')) {
      // ensure that the drive letter is upper case see
      // https://youtrack.jetbrains.com/issue/IDEA-329756/Importing-symlinked-Gradle-included-build-fails#focus=Comments-27-11721320.0-0
      path = path[0].toUpperCase() + path.substring(1);
    }
  }
  return path;
}
```

**Review by bkonyi — COMMENTED** [review]
Thanks for the PR! Just a couple of comments.

**Comment by rekire** [comment]
Thank you @bkonyi for your review. I applied your suggestions.

**Review by reidbaker — APPROVED** [review]

**Comment by rekire** [comment]
@reidbaker I reformatted my code, but this seems this break the Google Testing. Could you be so kind to tell me what's going on at Borg?

**Comment by jmagman** [comment]
> @reidbaker I reformatted my code, but this seems this break the Google Testing. Could you be so kind to tell me what's going on at Borg?

Apologies, we're experiencing infrastructure issues. I marked it manually as passing.

**Comment by rekire** [comment]
@jmagman thank you for fixing that

@reidbaker @bkonyi is there anything else I should do before this can get merged?

**Comment by reidbaker** [comment]
Just @bkonyi to approve and add autosubmit.

File: packages/flutter_tools/lib/src/base/file_system.dart [hunk 2]
```diff
@@ -63,7 +63,23 @@ class FileSystemUtils {
...
+    if (_platform.isWindows) {
+      path = path
+          .replaceAll(r'\', r'\\')
+          .split(';')
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/base/file_system.dart:70]: Why are we splitting on `;`? This API is only mean to handle individual paths, not the contents of the `PATH` variable.

File: packages/flutter_tools/test/general.shard/base/file_system_test.dart [hunk 3]
```diff
@@ -316,6 +316,10 @@ void main() {
       expect(fsUtils.escapePath(r'C:\foo\bar\cool.dart'), r'C:\\foo\\bar\\cool.dart');
       expect(fsUtils.escapePath(r'foo\bar\cool.dart'), r'foo\\bar\\cool.dart');
       expect(fsUtils.escapePath('C:/foo/bar/cool.dart'), 'C:/foo/bar/cool.dart');
+      expect(fsUtils.escapePath('c:/foo/bar/cool.dart'), 'C:/foo/bar/cool.dart');
+      expect(fsUtils.escapePath('x:/foo/bar/cool.dart'), 'X:/foo/bar/cool.dart');
+      expect(fsUtils.escapePath('a:/foo;b:/bar'), 'A:/foo;B:/bar');
```
Comment (bkonyi) [inline packages/flutter_tools/test/general.shard/base/file_system_test.dart:321]: These last two use cases shouldn't be supported.

File: packages/flutter_tools/test/general.shard/base/file_system_test.dart [hunk 4]
```diff
@@ -316,6 +316,8 @@ void main() {
       expect(fsUtils.escapePath(r'C:\foo\bar\cool.dart'), r'C:\\foo\\bar\\cool.dart');
       expect(fsUtils.escapePath(r'foo\bar\cool.dart'), r'foo\\bar\\cool.dart');
       expect(fsUtils.escapePath('C:/foo/bar/cool.dart'), 'C:/foo/bar/cool.dart');
+      expect(fsUtils.escapePath('c:/foo/bar/cool.dart'), 'C:/foo/bar/cool.dart');
```
[the remark this answers is not in the document]
Comment (bkonyi) [reply packages/flutter_tools/test/general.shard/base/file_system_test.dart:319]: I meant that we should be testing paths like `c:\foo\bar\cool.dart` and checking that `escapePath` returns `C:\\foo\\bar\\cool.dart`.

**Review by bkonyi — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/test/general.shard/base/file_system_test.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (rekire) [reply packages/flutter_tools/test/general.shard/base/file_system_test.dart:319]: Should be done now.

**Review by reidbaker — APPROVED** [review]

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/test/general.shard/base/file_system_test.dart (hunk 3 above)
Comment (bkonyi) [reply packages/flutter_tools/test/general.shard/base/file_system_test.dart]: Yeah, not a problem!
