### PR TITLE
[flutter_tools] Remove `Version.unknown`

### LINKED ISSUE #124756: [flutter_tools] `Version.unknown` is equivalent to `Version(0,0,0)` under `compareTo`, which can result in surprising behavior
Directly related to https://github.com/flutter/flutter/issues/121468.

Filing this as a sub-issue to be fixed with its own PR (this also affects non Android Studio-related code).

## Context
[`Version`](https://github.com/flutter/flutter/blob/2383400fe0c49b32dbb9e01869e2eed160c7767f/packages/flutter_tools/lib/src/base/version.dart#L9) is a class that is used to represent a version of multiple pieces of software used throughout the tool, including Android Studio, IntelliJ, Visual Studio Code, and Cocoapods.

## Issue
`Version` has a null-object[^*] instantiation, [`Version.unknown`](https://github.com/flutter/flutter/blob/2383400fe0c49b32dbb9e01869e2eed160c7767f/packages/flutter_tools/lib/src/base/version.dart#L71), which is used in a few places to represent the flutter tool being unable to detect the version of some software. Because[ `Version` also implements `Comparable`](https://github.com/flutter/flutter/blob/2383400fe0c49b32dbb9e01869e2eed160c7767f/packages/flutter_tools/lib/src/base/version.dart#L109-L118), it is easy to write logic that compares a more typical version object (e.g. `Version(1, 2, 3)`) to `Version.unknown`, which doesn't semantically make sense. For a specific example, consider `Version(0,0,0) == Version.unknown`, which resolves to `true`.

Because of this, branching logic based on Version comparison is prone to error if `Version.unknown` is used. If someone uses `Version.unknown` and they compare Verison objects, they must remember to explicitly check for `Version.unknown` in addition to those comparisons. Otherwise, they are at risk of treating `Version.unknown` as a legitimate version (0.0.0). Again, see #121468. 

## Possible fixes

1. Remove `Version.unknown` entirely. The drawback is that tool code has to use something else to represent the inability to find/detect a version within a software installation. `null` is the easiest choice, but the meaning of `null` is not as clear as `Version.unknown`, and it results in slightly less readable code.
2. Make the `compareTo` function of `Version` aware of `Version.unknown` (which should be made into a `static const`). Specifically, comparison with `Version.undefined` should result in an exception being thrown. While arguably better than the current behavior, users still need to remember to check for `Version.unknown` before making comparisons.

I suggest option 1.

[^*]: I'm abusing terminology here, since this object doesn't have any null/default behavior, but it still accomplishes something a null-object is typically used to do—avoiding references to `null`.

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #124756 by removing the concept of `Version.unknown`.

`Version` fields that needed the ability to represent an unknown version have been made nullable. Assigning `null` to them represents an unknown version.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 1]
```diff
@@ -438,7 +452,7 @@ class AndroidStudio implements Comparable<AndroidStudio> {
     return keyMatcher.stringMatch(plistValue)?.split('=').last.trim().replaceAll('"', '');
   }
 
-  void _init({Version? version}) {
+  void _init() {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:455]: can this be moved into the constructor?

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 2]
```diff
@@ -163,8 +169,12 @@ class AndroidStudio implements Comparable<AndroidStudio> {
     if (presetPluginsPath != null) {
       return presetPluginsPath!;
     }
-    final int major = version.major;
-    final int minor = version.minor;
+
+    // TODO(andrewkolos): This is a bug. We shouldn't treat an unknown
+    // version as the same 0.0.
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:174]:
```suggestion
    // version the same as 0.0.
```

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 3]
```diff
@@ -245,7 +246,17 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
     AndroidStudio? newest;
     for (final AndroidStudio studio in studios.where((AndroidStudio s) => s.isValid)) {
-      if (newest == null || studio.compareTo(newest) > 0) {
+      newest ??= studio;
+
+      if (studio.version != null && newest.version == null) {
+        newest = studio;
+      }
+      else if (studio.version == null && newest.version == null &&
+            studio.directory.compareTo(newest.directory) > 0 ) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:255]: nit. I think you can directly compare these directories with `>`

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 4]
```diff
@@ -245,7 +246,17 @@ class AndroidStudio implements Comparable<AndroidStudio> {
     }
     AndroidStudio? newest;
     for (final AndroidStudio studio in studios.where((AndroidStudio s) => s.isValid)) {
-      if (newest == null || studio.compareTo(newest) > 0) {
+      newest ??= studio;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:249]:
```suggestion
      if (newest == null) {
        newest = studio;
        continue;
      }
```

Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:249]: Is this functionality unit tested?

**Review by christopherfujino — COMMENTED** [review]
Overall LGTM, please just add unit tests of comparing versions

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart:255]: These are instances of `String`, which don't implement the `>` operator.

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: It could be; but, given how heavy the initialization logic is, I decided to instead just rename the method with a slightly more descriptive name.

There's definitely potential here to refactor the class to not have a half-initialized state (pre-constructor time), but it would result in a pretty big diff. I think I'll leave that out of scope for this change.

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 4 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: Added some tests

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 5]
```diff
@@ -245,7 +250,18 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
-      if (newest == null || studio.compareTo(newest) > 0) {
+      if (newest == null) {
+        newest = studio;
+        continue;
+      }
+
+      if (studio.version != null && newest.version == null) {
+        newest = studio;
+      } else if (studio.version == null && newest.version == null &&
+            studio.directory.compareTo(newest.directory) > 0) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:261]:
```suggestion
            studio.directory > newest.directory) {
```

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart:261]: Actually, yeesh, so we're just alphabetically comparing these strings?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart:261]: And I see even though string has a `compareTo`, it doesn't implement comparable

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart:261]: Let me file a tracking issue about investigating whether we should really be doing this.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 6]
```diff
@@ -217,25 +227,20 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
-        configuredStudioPath = globals.fs.path.join(configuredStudioPath, 'Contents');
+    final String? configuredStudioPath = globals.config.getValue('android-studio-dir') as String?;
+    if (configuredStudioPath != null) {
+      String correctedConfiguredStudioPath = configuredStudioPath;
+      if (globals.platform.isMacOS && !correctedConfiguredStudioPath.endsWith('Contents')) {
+        correctedConfiguredStudioPath = globals.fs.path.join(correctedConfiguredStudioPath, 'Contents');
       }
-      return AndroidStudio(configuredStudioPath,
-          configured: configuredStudio);
+      return AndroidStudio(correctedConfiguredStudioPath,
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:242]: I know we used to do this, but should we not toolexit in the case where `correctedConfiguredStudioPath` does not exist on disk? This most likely means they either made a mistake setting their config value, or forgot they set that and then deleted Android Studio.

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart:261]: Can you add a TODO with a link to https://github.com/flutter/flutter/issues/124880

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart:261]: > Actually, yeesh, so we're just alphabetically comparing these strings?

Only if 1) both installations have equivalent versions or 2) neither installation have known versions. I wonder what the original inspiration for this was...perhaps it was just a way keep ordering consistent even if the discovery logic changed.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 7]
```diff
@@ -39,15 +39,16 @@ final RegExp _dotHomeStudioVersionMatcher =
 // See https://github.com/flutter/flutter/issues/124252.
 String? get javaPath => globals.androidStudio?.javaPath;
 
-class AndroidStudio implements Comparable<AndroidStudio> {
+class AndroidStudio {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_studio.dart:42]: Why did you move the comparison logic out of `AndroidStudio.compareTo`?

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 5 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: Actually, I might be slightly incorrect here. Let me re-examine the original code.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: Actually, reading this more, I can see this is a last-resort fallback.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: I think I have the logic right. I added another test

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 6 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart:254]: Added this and a test

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 7 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_studio.dart:43]: My instinct is to never implement `Comparable` unless the semantics of comparison are immediately obvious (i.e. do not require reading documentation or code). This makes sense for things like numbers and dates. It makes less sense for things like software installs where the version (or lack of it) and the directory name are involved.

I would consider consider the implementation if we had a need to compare AndroidStudio installs in multiple places in code, but we are only doing it in one place now.

I don't mind either way

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_studio.dart:43]: Ahh ok, if we were only comparing this once, this makes sense.

**Review by christopherfujino — APPROVED** [review]
LGTM
