### PR TITLE
Fix SliverList scrollOffsetCorrection 0 case

### LINKED ISSUE #62198: SliverList throws Exception when first item is SizedBox.shrink()
## Steps to Reproduce

Run this snippet:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: CustomScrollView(
        physics: AlwaysScrollableScrollPhysics(),
        slivers: [
          SliverList(
            delegate: SliverChildListDelegate(
                [const SizedBox.shrink(), Text("item"), Text("item 2")]),
          ),
        ],
      )),
    );
  }
}
```

On the current master, dev or beta branch (the previous beta branch, 1.19.0-4.3.pre, works, but 1.20.0-7.2.pre crashes.) 
**Then fling the screen up a bit, the exception only happens when there is significant overscroll happening**.
See  https://streamable.com/i7eqce 

**Expected results:** 

I want the use case, that the first item of a SliverList is SizedBox.shrink(), be supported.

(Actually, my use case is more complex, I have a Widget that either renders something or returns SizedBox.shrink() if there is nothing to display. I don't want this logic to be in my SliverList, though).

**Actual results:** 

On the latest Flutter versions, this is not supported, and an exception gets thrown:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15:
flutter: 'scrollOffsetCorrection != 0.0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   SliverList file:///Users/kami/development/scroll_bug/lib/main.dart:17:11
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
flutter: #3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
flutter: #5      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #6      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1466:12)
flutter: #7      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1375:20)
flutter: #8      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1639:7)
flutter: #9      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
flutter: #10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
flutter: #12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
flutter: #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1053:9)
flutter: #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:969:5)
flutter: #19     _invoke (dart:ui/hooks.dart:253:10)
flutter: #20     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderSliverList#12304 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: SliverList ← Viewport ← IgnorePointer-[GlobalKey#77b5f] ← Semantics ← _PointerListener ←
flutter:     Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#6713c] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#fde3c] ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse,
flutter:     scrollOffset: 240.4, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 1157.4, cacheOrigin:
flutter:     -240.4)
flutter:   geometry: SliverGeometry(scrollExtent: 17.0, hidden, maxPaintExtent: 17.0)
flutter:   currently live children: 0 to 1
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child with index 0: RenderIndexedSemantics#78dd3 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderRepaintBoundary#358a5 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderConstrainedBox#6cefd relayoutBoundary=up4 NEEDS-PAINT
flutter:     child with index 1: RenderIndexedSemantics#870ee relayoutBoundary=up2
flutter:       child: RenderRepaintBoundary#1f7bf relayoutBoundary=up3
flutter:         child: RenderParagraph#951c2 relayoutBoundary=up4
flutter:           text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.
```

```
flutter analyze
Analyzing scroll_bug...
No issues found! (ran in 2.9s)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.1)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This fixes the offset correction in the performLayout of SliverList to account for 0. In the use cases where the calculated correction is 0, it crashes since SliverGeometry asserts the correction should never be 0. This opportunity presents itself more readily on iOS and Mac platforms due to over scroll.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/62198

## Tests

Regression test for 0 scrollOffsetCorrection
## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_list.dart [hunk 1]
```diff
@@ -178,7 +178,7 @@ class RenderSliverList extends RenderSliverMultiBoxAdaptor {
         assert(earliestUsefulChild != null);
         final double firstChildScrollOffset = earliestScrollOffset - paintExtentOf(firstChild);
         geometry = SliverGeometry(
-          scrollOffsetCorrection: -firstChildScrollOffset,
+          scrollOffsetCorrection: firstChildScrollOffset == 0 ? null : -firstChildScrollOffset,
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver_list.dart:181]: We should do a while loop on `indexOf(firstChild) > 0)` and only return on line 185 if firstChildScrollOffset < -precisionErrorTolerance, other wise we should continue downward to finish the layout.

If we set it to null here and return on line 185, the rendering binding will think the layout is finished and proceed to painting.

File: packages/flutter/test/widgets/slivers_test.dart [hunk 2]
```diff
@@ -814,6 +814,30 @@ void main() {
...
+                  Text('index 2'),
+                ]
+              ),
+            ),
+          ],
+        )
+      ),
+    ));
+    await tester.fling(find.byType(Scrollable), const Offset(0.0, -500.0), 10000.0);
+    await tester.pumpAndSettle();
```
Comment (chunhtai) [inline packages/flutter/test/widgets/slivers_test.dart:839]: lets add a expect(tester.takeException(), isNull)

File: packages/flutter/lib/src/rendering/sliver_list.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver_list.dart:181]: For example this may cause a problem if the children after the firstChild change their size in this perform layout.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_list.dart:181]: Ah, I think I see what you mean now. I'll update. Thanks!

File: packages/flutter/lib/src/rendering/sliver_list.dart [hunk 3]
```diff
@@ -169,20 +169,22 @@ class RenderSliverList extends RenderSliverMultiBoxAdaptor {
...
     if (scrollOffset < precisionErrorTolerance) {
-      if (indexOf(firstChild) > 0) {
+      while (indexOf(firstChild) > 0) {
         final double earliestScrollOffset = childScrollOffset(firstChild);
-        // We correct one child at a time. If there are more children before
-        // the earliestUsefulChild, we will correct it once the scroll offset
-        // reach zero again.
-        earliestUsefulChild = insertAndLayoutLeadingChild(childConstraints, parentUsesSize: true);
-        assert(earliestUsefulChild != null);
         final double firstChildScrollOffset = earliestScrollOffset - paintExtentOf(firstChild);
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver_list.dart:174]: This does not look right, the `earliestScrollOffset` is a the beginning of the first child already, we want to take `earliestScrollOffset` and minus the paint extent of child before the first child. I think one thing that is confusing of the original code is that line 177 ` earliestUsefulChild = insertAndLayoutLeadingChild(childConstraints, parentUsesSize: true);` will actually update the firstChild. So the firstChild in line 173 and line 179 are actually different.

File: packages/flutter/lib/src/rendering/sliver_list.dart [hunk 4]
```diff
@@ -169,20 +169,22 @@ class RenderSliverList extends RenderSliverMultiBoxAdaptor {
...
         earliestUsefulChild = insertAndLayoutLeadingChild(childConstraints, parentUsesSize: true);
         assert(earliestUsefulChild != null);
         final double firstChildScrollOffset = earliestScrollOffset - paintExtentOf(firstChild);
-        geometry = SliverGeometry(
-          scrollOffsetCorrection: -firstChildScrollOffset,
-        );
         final SliverMultiBoxAdaptorParentData childParentData = firstChild.parentData as SliverMultiBoxAdaptorParentData;
         childParentData.layoutOffset = 0.0;
-        return;
+        if (firstChildScrollOffset < -precisionErrorTolerance) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver_list.dart:182]: Can you add a comment to explain why we need to do this check and why we use the while loop? (something about the paint extent can be zero)

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/sliver_list.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_list.dart:182]: Sure!

**Comment by pcsosinski** [comment]
moving cp label to the issue (https://github.com/flutter/flutter/issues/62198) for discussion
