### PR TITLE
Mouse drag should not show selection handles

### LINKED ISSUE #69001: SelectableText sometimes show selection handles on Flutter Web
## Before you read
This "should" be an issue of the gesture detector. But a satisfying demo for GestureDetector takes too long time to write, I just use a `SelectableText` for the demo purpose.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: SelectableText('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', style: TextStyle(fontSize: 50)),
        ),
      ),
    );
```

Try this demo on DartPad (Flutter 1.23.0-18.1.pre Dart SDK 2.10.2. Chrome): https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

1. Select any text by dragging IMMEDIATELY and AS FAST AS POSSIBLE after press down the mouse button
2. If you are not doing it fast enough, refresh the window.

**Expected results:** 
No selection handles on web.

**Actual results:** 
If you drag fast enough, selection handles will appear.

The following demos the action: fast selection -> fast selection -> slow selection -> fast selection -> fast selection

chrome-capture

### Cause of this bug
Appearance of the selection handles is controlled by https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L895

This variable should be set to false in the tapdown handler.
https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L916-L927

Gesture detector promised to trigger `onTapDown` even if this is a long press.
https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L1180-L1183

But in my debugging experience, if you drag fast enough, `onTapDown` will not be triggered. So `showSelectionHandle` will not be set to false.

I suspect the longpress gesture recognizer declared the victory way too fast.

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

Fix a bug that SelectableText sometimes shows selection handles on Flutter Web.
Currently, we control handles by `_shouldShowSelectionToolbar`, but we only write the value at `onTapDown` and `onForcePressStart`, I think we should also do that at `onDragSelectionStart`.

Reproduce steps please see #69001 

## Related Issues

Fixes #69001 

## Tests

I added the following tests:

See files.

### CODE REVIEW

**Comment by xu-baolin** [comment]
@justinmc @chunhtai please review :)

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -1077,6 +1077,11 @@ class TextSelectionGestureDetectorBuilder {
   ///    this callback.
   @protected
   void onDragSelectionStart(DragStartDetails details) {
+    final PointerDeviceKind? kind = details.kind;
+    _shouldShowSelectionToolbar = kind == null
+      || kind == PointerDeviceKind.touch
+      || kind == PointerDeviceKind.stylus;
+
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/text_selection.dart:1084]: This code comes from `onTapDown`

Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1084]: Issue: https://github.com/flutter/flutter/issues/69127

File: packages/flutter/lib/src/gestures/drag_details.dart [hunk 2]
```diff
@@ -71,6 +71,7 @@ class DragStartDetails {
     this.sourceTimeStamp,
     this.globalPosition = Offset.zero,
     Offset? localPosition,
+    this.kind,
```
Comment (justinmc) [inline packages/flutter/lib/src/gestures/drag_details.dart:74]: I usually worry about adding parameters like this, but I think it's ok in this case for DragStartDetails since TapDownDetails also has it 👍

**Review by justinmc — APPROVED** [review]
LGTM, just an extra newline to fix.  Thank you for fixing this bug!

**Comment by justinmc** [comment]
The Google testing failure seems like an infrastructure problem to me, I'm rerunning it.
