### PR TITLE
Fix M3 text field height + initial step for input decorator M3 test migration [prod-leak-fix]

### LINKED ISSUE #142972: Text field height is not compliant with M3 specification
### Steps to reproduce

Run the code sample on Android.

### Expected results

The TextField height is 56.

Capture d’écran du 2024-02-06 08-13-35

(From https://m3.material.io/components/text-fields/specs#8c032848-e442-46df-b25d-28f1315f234b)

### Actual results

The TextField height is 64.

Capture d’écran du 2024-02-06 08-06-13

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: TextEditingController(text: 'Material3'),
              decoration: const InputDecoration(
                labelText: 'label',
                filled: true,
              ),
            ),
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.19.0-3.0.pre.496, on Ubuntu 23.04
    6.2.0-39-generic, locale fr_FR.UTF-8)
    • Flutter version 3.19.0-3.0.pre.496 on channel master at
      /home/bruno/Nevercode/flutter
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 0b5cd5073a (il y a 26 heures), 2024-02-05 06:16:23
      +0100
    • Engine revision f34c658b96
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /media/oldhome/Android/Sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /media/oldhome/Android/Sdk
    • Java binary at: /media/oldhome/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /media/oldhome/Produits/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.86.0)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu
      23.04 6.2.0-39-generic
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR main purpose is to make progress on the M3 test migration for `InputDecorator` (see https://github.com/flutter/flutter/issues/139076).

Before this PR more than 80 of the 156 tests defined in `input_decorator_test.dart` fail on M3.
Migrating all those tests in one shot is not easy at all because many failures are related to wrong positionning due to M3 typography changes. Another reason is that several M3 specific changes are required in order to get a proper M3 compliant text field, for instance:
- https://github.com/flutter/flutter/issues/142972
- https://github.com/flutter/flutter/issues/141354

Most of the tests were relying on an helper function (`buildInputDecorator`) which had a `useMaterial3` parameter. Unfortunately when `useMaterial3: true `was passed to this function it forced `useMaterial3: false` at the top level but overrided it at a lower level, which was very misleading because people could assume that the tests are ok with M3 (but in fact they were run using M2 typography but have some M3 logic in use).
I considered various way to make this change and I finally decided to run all existing tests only on M2 for the moment. Next step will be to move most of those tests to M3. In this PR, I migrated two of these existing tests for illustration.

Because many of the existing tests are checking input decorator height, I think it would also make sense to fix https://github.com/flutter/flutter/issues/142972 first. That's why I choosed to include a fix to https://github.com/flutter/flutter/issues/142972 in this PR.

A M3 filled `TextField` on Android:

| Before this PR | After this PR |
|--------|--------|
| image | image | 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/142972
Related to https://github.com/flutter/flutter/issues/139076

## Tests

Updates many existing tests 
+ adds 2 tests related to the fix for https://github.com/flutter/flutter/issues/142972
+ adds 1 tests for the M3 migration
+ move 1 tests related to M3

### CODE REVIEW

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -16,7 +16,7 @@ import 'package:flutter/rendering.dart';
 import 'package:flutter_test/flutter_test.dart';
 import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';
 
-Widget buildInputDecorator({
+Widget buildInputDecoratorM2({
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:19]: Maybe add a TODO here and point to https://github.com/flutter/flutter/issues/139076? Just to make sure that it's clear that we still intend to migrate these tests to M3. Or maybe down where `runAllM2Tests` is called.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 2]
```diff
@@ -164,19 +219,97 @@ TextStyle? getIconStyle(WidgetTester tester, IconData icon) {
...
+    expect(tester.getSize(find.byType(InputDecorator)), const Size(800.0, 56.0));
+    expect(tester.getTopLeft(find.text('label')).dy, 8.0);
+    expect(tester.getBottomLeft(find.text('label')).dy, 20.0);
+    expect(tester.getTopLeft(find.text('text')).dy, 24.0);
+    expect(tester.getBottomLeft(find.text('text')).dy, 48.0);
+    expect(getBorderBottom(tester), 56.0);
+    expect(getBorderWeight(tester), 1.0);
+  });
+
+  testWidgets('Material3 - Floating label is aligned with prefixIcon by default', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:286]: Will these be moved inside of runAllTests after you've migrated them all to M3?

**Review by justinmc — APPROVED** [review]
LGTM 👍  (but we should see if the Google tests pass)

Good catch with the `buildInputDecorator` thing. I've started the Google tests in case this breaks any visual diff tests. At least it looks like it's passing the customer tests.

File: packages/flutter/test/material/input_decorator_test.dart (hunk 2 above)
Comment (bleroux) [reply packages/flutter/test/material/input_decorator_test.dart:286]: `runAllTests` was introduced because it had a `useMaterial3` parameter.
After this PR, it won't be needed so my plan is to put the migrated tests in `main`(similarly to most of the other test files) and to keep `runAllM2Tests` for the M2 tests.

I also wonder if we should consider moving all M2 tests to another file? (for instance input_decorator_m2_test.dart)

Comment (justinmc) [reply packages/flutter/test/material/input_decorator_test.dart]: Got it, thanks for the explanation. I like the idea of a separate m2 test file.
