### PR TITLE
Fix: Update PopupMenu position when layout changes

### LINKED ISSUE #152475: PopupMenuButton retains wrong position on layout change
### Steps to reproduce

1. Run the attached minimal sample on any platform
2. Tap an overflow icon button to reveal the overflow menu
3. Rotate the screen from portrait to landscape or vice versa

### Expected results

The overflow menu hides after rotation or recalculates its right position based on its anchor

### Actual results

The overflow menu is still visible, but in the wrong position

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PopupMenuButton position',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePageView(),
    );
  }
}

class HomePageView extends StatefulWidget {
  const HomePageView({super.key});

  @override
  State<HomePageView> createState() => _HomePageViewState();
}

class _HomePageViewState extends State<HomePageView> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('PopupMenuButton position')),
      body: OrientationBuilder(builder: (context, orientation) {
        int tileCount = orientation == Orientation.portrait ? 2 : 5;
        return Padding(
          padding: const EdgeInsets.all(8),
          child: GridView.count(
            crossAxisCount: tileCount,
            crossAxisSpacing: 8,
            mainAxisSpacing: 8,
            childAspectRatio: 1,
            children: List.generate(17, (index) {
              return GridTile(
                footer: GridTileBar(
                  title: Text(
                    'Item $index',
                    style: TextStyle(
                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                    ),
                  ),
                  trailing: PopupMenuButton(
                    itemBuilder: (context) {
                      return [
                        const PopupMenuItem(
                          child: Text('Archive'),
                        ),
                        const PopupMenuItem(
                          child: Text('Edit'),
                        ),
                        const PopupMenuItem(
                          child: Text('Delete'),
                        )
                      ];
                    },
                  ),
                ),
                child: Ink(
                  decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.primaryContainer,
                    borderRadius: const BorderRadius.all(
                      Radius.circular(8),
                    ),
                  ),
                  width: 175,
                  height: 250,
                ),
              );
            }),
          ),
        );
      }),
    );
  }
}

```

</details>

### Screenshots or Video

_No response_

### Logs

<details open><summary>Logs</summary>

```console
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
D/FlutterFileDialogPlugin(24349): onAttachedToEngine - IN
D/FlutterFileDialogPlugin(24349): doOnAttachedToEngine - IN
D/FlutterFileDialogPlugin(24349): doOnAttachedToEngine - OUT
D/FlutterFileDialogPlugin(24349): onAttachedToEngine - OUT
D/FlutterFileDialogPlugin(24349): onAttachedToActivity
D/FlutterFileDialogPlugin(24349): doOnAttachedToActivity - IN
D/FlutterFileDialogPlugin(24349): doOnAttachedToActivity - OUT
Debug service listening on ws://127.0.0.1:56853/L-wxvMvU6kE=/ws
Syncing files to device Pixel Fold...
D/ProfileInstaller(24349): Installing profile for it.returntrue.novelist
D/VRI[MainActivity](24349): visibilityChanged oldVisibility=true newVisibility=false
I/ImeTracker(24349): it.returntrue.novelist:2c275c54: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
D/InputMethodManager(24349): showSoftInput() view=io.flutter.embedding.android.FlutterView{113df2b VFE...... .F....ID 0,0-2208,1756 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputConnectionAdaptor(24349): The input method toggled cursor monitoring on
D/InsetsController(24349): show(ime(), fromIme=true)
W/InteractionJankMonitor(24349): Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=it.returntrue.novelist
I/ImeTracker(24349): it.returntrue.novelist:2c275c54: onShown
D/InputConnectionAdaptor(24349): The input method toggled cursor monitoring off
D/InsetsController(24349): hide(ime(), fromIme=true)
W/WindowOnBackDispatcher(24349): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@70107678 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@935dc34
I/ImeTracker(24349): it.returntrue.novelist:42f354f: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_ON_ANIMATION_STATE_CHANGED fromUser false
I/ImeTracker(24349): com.google.android.inputmethod.latin:8f8da5d4: onHidden
I/ImeTracker(24349): it.returntrue.novelist:d8a3be57: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
D/VRI[MainActivity](24349): visibilityChanged oldVisibility=true newVisibility=false
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Versione 10.0.19045.4651], locale it-IT)
    • Flutter version 3.22.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (12 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Alessandro\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Alessandro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (4 available)
    • Pixel Fold (mobile) • 35181FDHS00206 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows        • windows-x64    • Microsoft Windows [Versione 10.0.19045.4651]
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 126.0.6478.185
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by YeungKC**
This PR fixes an issue where PopupMenu doesn't update its position when the screen layout changes (e.g. during rotation or window resizing).

## Changes
- Introduces `positionBuilder` instead of directly using position
- Calls positionBuilder after layout changes to get the updated position
- Adds tests to verify position updates correctly

## Related Issues
Fixes #152475 - PopupMenu retains wrong position on layout change

## Implementation Notes
This implementation uses a builder pattern to dynamically calculate positions. This approach may be applicable to other popup widgets (like DropdownButton mentioned in #156980) that have similar positioning requirements.

<br>
<br>
<br>
<br>
<br>

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -1064,6 +1094,8 @@ Future<T?> showMenu<T>({
 }) {
   assert(items.isNotEmpty);
   assert(debugCheckHasMaterialLocalizations(context));
+  assert(position != null || positionBuilder != null,
+  'Either position or positionBuilder must be provided.');
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:1098]: I wonder if we can be more strict on it, and only allow one of them,

```
assert((position != null) != (positionBuilder != null),
```

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 2]
```diff
@@ -982,10 +986,35 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
...
+typedef PopupMenuPositionBuilder = RelativeRect Function();
+
+/// Shows a popup menu that contains the `items` at `position`.
 ///
 /// The `items` parameter must not be empty.
 ///
+/// Either [position] or [positionBuilder] must be provided. If both are specified,
+/// [position] takes precedence. The [positionBuilder] is called at the time the
+/// menu is shown to compute its position, which is useful when the position needs
+/// to be determined at runtime based on the current layout.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:1016]: Is this more correct?
```suggestion
/// [position] takes precedence. The [positionBuilder] is called at the time the
/// menu is shown to compute its position and every time the layout is updated,
/// which is useful when the position needs
/// to be determined at runtime based on the current layout.
```

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 3]
```diff
@@ -953,11 +957,11 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
...
       removeLeft: true,
       removeRight: true,
-      child: Builder(
-        builder: (BuildContext context) {
+      child: LayoutBuilder(
+        builder: (BuildContext context, BoxConstraints constraints) {
           return CustomSingleChildLayout(
             delegate: _PopupMenuRouteLayout(
-              position,
+              positionBuilder?.call() ?? position!,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:964]: Do we really need the `positionBuilder` parameter to fix this issue? It seems to me that with `LayoutBuilder` handling the rebuild, `position` is enough. The `positionBuilder` might be a useful feature for other uses, but unless we have explicit use case in mind (or brought up by an issue) it's unnecessary.

Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart:964]: I think the `positionBuilder` is necessary, When screen dimensions change (e.g. during rotation or window resizing), even with `LayoutBuilder`, the original position value remains static and may become incorrect relative to the new screen dimensions. The `positionBuilder` allows us to dynamically recalculate the position whenever the layout changes.

I think all about popup widget should need a positionBuilder replace position.

Comment (dkwingsmt) [reply packages/flutter/lib/src/material/popup_menu.dart:965]: I see. It is presented by `showMenu`, and therefore won't receive contextual updates any more.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Actually, why are the other 2 comments resolved without any changes?

**Review by Piinks — CHANGES_REQUESTED** [review]
Marking as changes requested to block merging as there are outstanding comments. Thanks!

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 2 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart:1017]: done

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 1 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart:1099]: done

**Comment by YeungKC** [comment]
I forgot to reply to the comments… but actually, those two comments are already resolved.

@Piinks

**Comment by dkwingsmt** [comment]
But they're not fixed either. For example, the `assert` condition is still the old one.

**Comment by YeungKC** [comment]
Sorry...I'm not sure how I missed it, now is all resolved.

**Review by Piinks — APPROVED** [review]
LGTM! Thanks for resolving those! :)

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 4]
```diff
@@ -869,12 +870,15 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
     super.settings,
     super.requestFocus,
     this.popUpAnimationStyle,
-  }) : itemSizes = List<Size?>.filled(items.length, null),
+  }) : assert(position != null || positionBuilder != null,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:873]: The assert here should be changed as well.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 5]
```diff
@@ -983,10 +987,35 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
...
+///    one representing the size of the popup menu and one representing the size
+///    of the overlay.
+typedef PopupMenuPositionBuilder = RelativeRect Function();
+
+/// Shows a popup menu that contains the `items` at `position`.
 ///
 /// The `items` parameter must not be empty.
 ///
+/// Either [position] or [positionBuilder] must be provided. If both are specified,
+/// [position] takes precedence. The [positionBuilder] is called at the time the
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:1015]:
```suggestion
/// Only one of [position] or [positionBuilder] should be provided. Providing both 
/// throws an assertion error. The [positionBuilder] is called at the time the
```

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/popup_menu.dart:1017]: Is this applied at all? I mean you can change based on my suggestion, but it seems to me that this isn't changed at all.

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 4 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart]: done

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 5 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart]: It seems like I failed to push....

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 6]
```diff
@@ -954,11 +958,11 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
...
       removeLeft: true,
       removeRight: true,
-      child: Builder(
-        builder: (BuildContext context) {
+      child: LayoutBuilder(
+        builder: (BuildContext context, BoxConstraints constraints) {
           return CustomSingleChildLayout(
             delegate: _PopupMenuRouteLayout(
-              position,
+              positionBuilder?.call() ?? position!,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:965]: I think we need to pass the `context` to the `positionBuilder` here. Probably the `constraints` as well, although I'm not exactly sure whose contraints they are and whether they're meaningful. Otherwise the callback can not effectively do much.

Comment (YeungKC) [reply packages/flutter/lib/src/material/popup_menu.dart:965]: The context you're suggesting to add would be the route's context, not the PopupMenuButton's context. The route's context isn't useful for positioning since we already have access to the button's context through PopupMenuButtonState. The current implementation with `RelativeRect Function()` is sufficient.

Comment (dkwingsmt) [reply packages/flutter/lib/src/material/popup_menu.dart:966]: But what about the caller of `showMenu`? In the simplest case we'd like any `context` to get the screen parameters, but even this is not available if a stateless widget is to call `showMenu`.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 7]
```diff
@@ -984,10 +988,37 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
   }
 }
 
-/// Show a popup menu that contains the `items` at `position`.
+/// A builder that creates a [RelativeRect] to position a popup menu.
+///
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:992]: Can you add explanation on whose `context` and `constraints` are provided here?

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you!
