### PR TITLE
Fix SegmentedButton focus issue

### LINKED ISSUE #161922: SegmentedButton keyboard navigation incorrectly moves focus on click
### Steps to reproduce

1. Navigate to the first SegmentedButton doc example: https://api.flutter.dev/flutter/material/SegmentedButton-class.html.
2. Focus one of "Multiple choice" buttons.
3. Click to interact with the button.
4. Observe that focus is moved to another button, instead of staying on the interacted button.

### Expected results

The focus should remain on the current button when clicked.

### Actual results

The focus moves when button is clicked.

### Code sample

See SegmentedButton doc example: https://api.flutter.dev/flutter/material/SegmentedButton-class.html.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/ca1a8629-a30c-4fde-b89f-774558a5d8a3

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>
N/A
</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes SegmentedButton focus traversal.

# Before

When a focused segment (with no icon) is selected or unselected, the focus moves to another segment.

[Capture vidéo du 2025-08-11 15-28-03.webm](https://github.com/user-attachments/assets/11c29194-6b96-4ea4-9245-dcbd36dc424f)

In this recording, tab key is used to set the focus on 'Month' segment, then enter is used to select the segment. The focus move unexpectedly to 'Week' segment.

# After

When a focused segment (with no icon) is selected or unselected, the focus stays on this same segment and the InkWell animations are correctly painted.

[Capture vidéo du 2025-08-11 15-27-30.webm](https://github.com/user-attachments/assets/e09056d0-b572-462b-8ad8-c23eddcc4bfd)

<details><summary>Code sample for recordings</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SegmentedButton].

void main() {
  runApp(const SegmentedButtonApp());
}

class SegmentedButtonApp extends StatelessWidget {
  const SegmentedButtonApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: SingleChoice())),
    );
  }
}

enum Calendar { day, week, month, year }

class SingleChoice extends StatefulWidget {
  const SingleChoice({super.key});

  @override
  State<SingleChoice> createState() => _SingleChoiceState();
}

class _SingleChoiceState extends State<SingleChoice> {
  Calendar calendarView = Calendar.day;

  @override
  Widget build(BuildContext context) {
    return SegmentedButton<Calendar>(
      segments: const <ButtonSegment<Calendar>>[
        ButtonSegment<Calendar>(value: Calendar.day, label: Text('Day')),
        ButtonSegment<Calendar>(value: Calendar.week, label: Text('Week')),
        ButtonSegment<Calendar>(value: Calendar.month, label: Text('Month')),
        ButtonSegment<Calendar>(value: Calendar.year, label: Text('Year')),
      ],
      selected: <Calendar>{calendarView},
      onSelectionChanged: (Set<Calendar> newSelection) {
        setState(() {
          // By default there is only a single segment that can be
          // selected at one time, so its value is always the first
          // item in the selected set.
          calendarView = newSelection.first;
        });
      },
    );
  }
}

``` 
</details> 

## Related Issue

Fixes [SegmentedButton keyboard navigation incorrectly moves focus on click](https://github.com/flutter/flutter/issues/161922)

## Implementation choice

The root of this issue is TextButton.icon which creates a different widget tree depending on the icon.
See https://github.com/flutter/flutter/issues/173944 for more context.

The proposed solution is to maintain the same widget tree when possible.
To do TextButton.icon is not used. This PR uses on TextButton and build a child containing both the icon (when present) and the label.
In order to keep the same rendering as before, some internal logic from TextButton.icon is duplicated.

## Tests

Adds 1 test.
Updates 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/material/segmented_button.dart [hunk 1]
```diff
@@ -570,44 +571,59 @@ class SegmentedButtonState<T> extends State<SegmentedButton<T>> {
...
+            MediaQuery.textScalerOf(context).scale(defaultFontSize) / 14.0;
+        final EdgeInsetsGeometry scaledPadding = ButtonStyleButton.scaledPadding(
+          useMaterial3
+              ? const EdgeInsetsDirectional.fromSTEB(12, 8, 16, 8)
+              : const EdgeInsets.all(8),
+          const EdgeInsets.symmetric(horizontal: 4),
+          const EdgeInsets.symmetric(horizontal: 4),
+          effectiveTextScale,
+        );
+        effectiveSegmentStyle = segmentStyle.copyWith(
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/segmented_button.dart:593]: Oh nice, I didn't notice we need to check M2 and M3 text button style:)

**Review by QuncCccccc — APPROVED** [review]
LGTM!
