### PR TITLE
[framework] fix slider regression due to touch slop changes

### LINKED ISSUE #103566: Slider in Drawer Doesn't Slide
After upgrading to Flutter 3 I am unable to manually slide a `Slider` placed inside a `Drawer` in Android. I can click anywhere along the slider and it will change value, but not slide. Instead it slides the Drawer. On macOS this works as expected. I am using a Pixel 6 with Android 12. This worked fine with the most recent Flutter 2 version.

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      drawer: Drawer(
        elevation: 0,
        child: Column(children: [
          const SizedBox(height: 100.0),
          Slider(
            min: 0,
            max: 100,
            divisions: 100,
            value: _counter.toDouble(),
            onChanged: (value) {
              setState(() {
                _counter = value.toInt();
                debugPrint("Slider: $value");
              });
            },
          ),
        ]),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/103566

Due to changes in https://github.com/flutter/flutter/pull/97971

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@xu-baolin I'll trade you 😄

File: packages/flutter/lib/src/material/slider.dart [hunk 1]
```diff
@@ -925,6 +927,7 @@ class _RenderSlider extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     required TextDirection textDirection,
     required bool hasFocus,
     required bool hovering,
+    required DeviceGestureSettings gestureSettings,
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/slider.dart:930]: Should not `this.gestureSettings`?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/slider.dart:930]: Since the only thing I do with `gestureSettings` is pass it to the gesture detectors below, we don't necessarily need a field to store the settings on this render object. The gesture detectors themselves are `late` and so aren't re-created outside of the constructor

Comment (xu-baolin) [reply packages/flutter/lib/src/material/slider.dart:930]: oh, you are right, : )

**Review by xu-baolin — APPROVED** [review]
LGTM

Further, we may need to troubleshoot all related gestures and add gesture settings for them, what do you think?
image

**Comment by jonahwilliams** [comment]
yes, an audit is in order. We might be able to speed things up by adding an assert if a gesture is received and gesture settings hasn't been set. I could also look into a breaking change process to make it required to prevent this from happening again.

**Comment by xu-baolin** [comment]
> 

👍 Glad to review!

**Comment by hicnar** [comment]
When will that fix be released to the stable channel?

**Comment by hicnar** [comment]
@jonahwilliams When will that fix make its way to a stable release?
