### PR TITLE
Widgets that depend on Material should assert that

### LINKED ISSUE #243: Using a RaisedButton in a non-material app doesn't hint as to what is wrong
<a href="https://github.com/sethladd"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Thursday Oct 29, 2015 at 22:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1878_

----

Consider this code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Column([
      new Center(child: new Text("first")),
      new Center(child: new Text("second")),
      new Center(child: new RaisedButton(child: new Text("third")))
    ], justifyContent: FlexJustifyContent.spaceAround);
  }
}
```

There are no warnings or errors. It launches correctly on the phone (from what I can tell)

Expected: the button is displayed, or some error telling me why this isn't allowed
Actual: I see "first", and "second", but not a button for "third"

If this is not valid code, could we error out with a message, or provide some feedback somehow (even on the screen) that lets the developer know what's wrong?

Thanks!

### PR DESCRIPTION
**Pull request by abarth**
After this patch, if you try to use a widget that depends on being enclosed in
a material, you now get an assert and a debugPrint if you're not inside a
material.

Fixes #243

### CODE REVIEW

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -102,11 +103,15 @@ void debugDumpApp() {
...
-    : container = container, super(key: new GlobalObjectKey(container));
+  RenderObjectToWidgetAdapter({
+    this.child,
+    RenderObjectWithChildMixin<T> container,
+    this.shortDescription
+  }) : container = container, super(key: new GlobalObjectKey(container));
 
   final Widget child;
   final RenderObjectWithChildMixin<T> container;
+  final String shortDescription;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/binding.dart]: debugShortDescription?

**Comment by Hixie** [comment]
LGTM. I didn't check if there were widgets that should get this that you didn't put it in.
