### PR TITLE
Fix divider width in scrollable `TabBar` for  Material 3 and add `dividerHeight` parameter

### LINKED ISSUE #117722: Material 3 `TabBar` does not take full width when `isScrollable: true`
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

The bottom divider of the `TabBar` taking the full width available

**Actual results:** 

The `TabBar` taking minimum possible width.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with SingleTickerProviderStateMixin {
  late TabController controller;

  final tabs = ['Tab 1', 'Tab 2', 'Tab 3'];

  @override
  void initState() {
    super.initState();
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: controller,
            tabs: tabs.map((name) => Tab(text: name)).toList(),
            isScrollable: true,
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: tabs.map((name) => Center(child: Text(name))).toList(),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/flutter/flutter/files/10313296/logs.txt)

```
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.19043.2075], locale en-US)
    • Flutter version 3.7.0-1.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (8 days ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)  
    • Android SDK at C:\Users\mohamed.haisham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java        
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)     
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community    
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\mohamed.haisham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
~~Blocked on https://github.com/flutter/flutter/pull/122756~~

---

fixes https://github.com/flutter/flutter/issues/117722

### Description
1. This PR makes the tab bar take the full width for the divider by putting in a `Stack`. (This will produce golden changes)
2. Add `dividerHeight` default and parameter.

### Before
Group 11

### After

Group 10

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -1993,6 +2013,9 @@ class _TabsDefaultsM3 extends TabBarTheme {
   late final ColorScheme _colors = Theme.of(context).colorScheme;
   late final TextTheme _textTheme = Theme.of(context).textTheme;
 
+  @override
+  double? get dividerHeight => 1.0;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:2017]: Just for follow up after https://github.com/flutter/flutter/pull/122756, I assume this will need to be updated the for M3 defaults for primary & secondary.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/tabs.dart:2017]: Yes, I will update this PR immediately once https://github.com/flutter/flutter/pull/122756  land. As tthere will be conflict in the defaults text and as you pointed out, I will add dividerHeight in secondary defaults as well.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/tabs.dart:2103]: - Resolved conflicts,
- updated default tests
- modified an existing duplicate test for the secondary tab bar golden
- Updated underline indicator to shift so I can align with the divider.

**Review by Piinks — APPROVED** [review]
LGTM - approved goldens. 👍
