### PR TITLE
[Slider] Remove value indicator painter when animation is dismissed

### LINKED ISSUE #180767: Slider Value Indicator remains visible when using SliderThemeData.ShowValueIndicator.onDrag
### Steps to reproduce

1. Run the below official code sample with a SliderTheme
2. Notice when you stop the drag (Touch not in contact with screen) the value indicator is still visible

### Expected results

The Value Indicator should be hidden if the touch is not in contact with screen or when not dragging.

https://github.com/user-attachments/assets/58b61d9d-884d-44ff-94d8-2032a99eae1c

### Actual results

The Value Indicator is always shown which is same behavior as

```dart
showValueIndicator: ShowValueIndicator.alwaysVisible
```

but as per docs of [ShowValueIndicator.onDrag](https://api.flutter.dev/flutter/material/ShowValueIndicator.html)

> The value indicator is shown while dragging.

### Code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Slider].

void main() => runApp(const SliderApp());

class SliderApp extends StatelessWidget {
  const SliderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: SliderExample());
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double _currentSliderPrimaryValue = 0.2;
  double _currentSliderSecondaryValue = 0.5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Slider')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          SliderTheme(
            data: SliderTheme.of(context).copyWith(
              valueIndicatorShape: IV4RoundValueIndicator(),
              showValueIndicator: ShowValueIndicator.onDrag,
              trackHeight: 1,
            ),
            child: Slider(
              value: _currentSliderSecondaryValue,
              label: _currentSliderSecondaryValue.round().toString(),
              onChanged: (double value) {
                setState(() {
                  _currentSliderSecondaryValue = value;
                });
              },
            ),
          ),
        ],
      ),
    );
  }
}

class IV4RoundValueIndicator extends SliderComponentShape {
  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) {
    return Size(40, 40); // Size of the value indicator
  }

  @override
  void paint(
    PaintingContext context,
    Offset center, {
    required Animation<double> activationAnimation,
    required Animation<double> enableAnimation,
    required bool isDiscrete,
    required TextPainter labelPainter,
    required RenderBox parentBox,
    required SliderThemeData sliderTheme,
    required TextDirection textDirection,
    required double value,
    required double textScaleFactor,
    required Size sizeWithOverflow,
  }) {
    final canvas = context.canvas;

    // Define the circle indicator parameters
    const double circleDiameter = 44.0;
    final Offset circleCenter = Offset(
      center.dx,
      center.dy - circleDiameter - 10,
    );

    final paint = Paint()
      ..color = sliderTheme.valueIndicatorColor ?? Colors.purple
      ..style = PaintingStyle.fill;

    // Draw the circle
    canvas.drawCircle(circleCenter, circleDiameter / 2, paint);

    // Draw the text centered in the circle
    final textOffset = Offset(
      circleCenter.dx - (labelPainter.width / 2),
      circleCenter.dy - (labelPainter.height / 2),
    );
    labelPainter.paint(canvas, textOffset);
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

I found this on latest flutter stable but I believe this reproduces on latest master too.

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.38.5, on macOS 26.2 25C56 darwin-arm64, locale en-US) [979ms]
    • Flutter version 3.38.5 on channel stable at /Users/maheshjamdade/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f6ff1529fd (4 weeks ago), 2025-12-11 11:50:07 -0500
    • Engine revision 1527ae0ec5
    • Dart version 3.10.4
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging
```

</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
With this PR, `Slider` stops painting the value indicator when `activationAnimation` is dismissed.

Fixes https://github.com/flutter/flutter/issues/180767.

This change has no effect on default value indicator shapes, which animates with `activationAnimation` and do not paint anything when the animation is dismissed. However, for custom value indicator shapes that do not animate, this allows value indicators to be properly hidden after the animation duration.

For testing, this PR refactors an existing test case, since I consider the new test case a superset of the previous one and improves its capability.
* Previously the test case only verifies the status before dragging and during dragging. Now it also verifies that after dragging.
* Previously the test case uses the default value indicator shapes. Now it uses a custom one that does not animate.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -2870,9 +2870,13 @@ void main() {
     skip: kIsWeb, // [intended] the web traversal order by using ARIA-OWNS.
   );
 
-  testWidgets('Value indicator appears when it should', (WidgetTester tester) async {
+  // Regression test for https://github.com/flutter/flutter/issues/180767
+  testWidgets('Value indicator appears and disappears when it should', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/slider_test.dart]: For reviewer: If the change here is too confusing, I'm happy to split the refactor part into a separate PR.

File: packages/flutter/lib/src/material/slider.dart [hunk 2]
```diff
@@ -1856,32 +1856,34 @@ class _RenderSlider extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
-          }
-        };
-      }
+    if (isInteractive &&
+        label != null &&
+        ((shouldShowValueIndicatorWhenDragged && !_valueIndicatorAnimation.isDismissed) ||
+            shouldAlwaysShowValueIndicator)) {
+      _state.paintValueIndicator = (PaintingContext context, Offset offset) {
+        if (attached && _labelPainter.text != null) {
+          _sliderTheme.valueIndicatorShape!.paint(
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/slider.dart]: Just in case?

```suggestion
          _sliderTheme.valueIndicatorShape?.paint(
```

File: packages/flutter/lib/src/material/slider.dart [hunk 3]
```diff
@@ -1856,32 +1856,34 @@ class _RenderSlider extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+            context,
+            offset + thumbCenter,
+            activationAnimation: shouldAlwaysShowValueIndicator
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/slider.dart:1868]: Should we also manage the `const AlwaysStoppedAnimation<double>(1)` so that these are detached and disposed? I'm not sure if these participate in leak tracking?

File: packages/flutter/test/material/slider_test.dart [hunk 4]
```diff
@@ -2900,124 +2904,155 @@ void main() {
     }
 
     Future<void> expectValueIndicator({
-      required bool isVisible,
+      required bool visibleDragged,
```
Comment (navaronbracke) [inline packages/flutter/test/material/slider_test.dart]: `visibleWhenDragged` & `visibleWhenReleased` ?

File: packages/flutter/test/material/slider_test.dart [hunk 5]
```diff
@@ -5530,3 +5565,59 @@ void main() {
...
+    required TextPainter labelPainter,
+    required RenderBox parentBox,
+    required SliderThemeData sliderTheme,
+    required TextDirection textDirection,
+    required double value,
+    required double textScaleFactor,
+    required Size sizeWithOverflow,
+  }) {
+    final Canvas canvas = context.canvas;
+    const circleDiameter = 44.0;
```
Comment (navaronbracke) [inline packages/flutter/test/material/slider_test.dart]: The diameter is bigger than the preferred size?

**Review by navaronbracke — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/slider_test.dart (hunk 5 above)
Comment (dkwingsmt) [reply packages/flutter/test/material/slider_test.dart]: I've changed it to 40 (and also simplified the implementation).

File: packages/flutter/test/material/slider_test.dart (hunk 4 above)
Comment (dkwingsmt) [reply packages/flutter/test/material/slider_test.dart]: Done.

File: packages/flutter/lib/src/material/slider.dart (hunk 3 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/slider.dart:1868]: I think it's fine until the leak tracker complains. Theoretically, the objects are const so they are created at compile time and are not mutable. Therefore they have nothing to dispose and can't be deallocated either.

File: packages/flutter/lib/src/material/slider.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/slider.dart]: Done

File: packages/flutter/lib/src/material/slider.dart (hunk 3 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/material/slider.dart:1868]: I had a look and I don't immediately see Animation call into the leak tracker tooling for the memory events, so this should be fine yes.

**Review by navaronbracke — DISMISSED** [review]

**Comment by dkwingsmt** [comment]
Thank you for reviewing!

File: packages/flutter/test/material/slider_test.dart (hunk 1 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/slider_test.dart]: Super nit: separating it into 2 tests might be a bit better. But I'm also fine with the current test:)!

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks!

File: packages/flutter/test/material/slider_test.dart [hunk 6]
```diff
@@ -2900,124 +2904,155 @@ void main() {
...
     await expectValueIndicator(
-      isVisible: true,
+      visibleWhenDragged: true,
+      visibleWhenReleased: true,
       theme: theme,
       divisions: 3,
+    );
+    await expectValueIndicator(
+      visibleWhenDragged: true,
+      visibleWhenReleased: true,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/slider_test.dart]:
```suggestion
      visibleWhenDragged: false,
      visibleWhenReleased: false,
```

File: packages/flutter/test/material/slider_test.dart [hunk 7]
```diff
@@ -2900,124 +2904,155 @@ void main() {
...
+      theme: theme,
+      divisions: 3,
+      enabled: false,
+    );
+    await expectValueIndicator(visibleWhenDragged: true, visibleWhenReleased: true, theme: theme);
+    await expectValueIndicator(
+      visibleWhenDragged: true,
+      visibleWhenReleased: true,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/slider_test.dart]:
```suggestion
      visibleWhenDragged: false,
      visibleWhenReleased: false,
```
These should be false when slider is disabled. I think this can fix the failed test!

**Review by QuncCccccc — DISMISSED** [review]

File: packages/flutter/test/material/slider_test.dart [hunk 8]
```diff
@@ -5620,3 +5624,48 @@ void main() {
     expect(tester.getSize(find.byType(Slider)), Size.zero);
   });
 }
+
+// A slider value indicator that's a circle with a fixed size and
+// does not animate at all.
+//
+// This allows us to test whether `Slider` removes the value indicator painter
```
Comment (navaronbracke) [inline packages/flutter/test/material/slider_test.dart]: Shouldn't we avoid "us/we" per the style guide?

File: packages/flutter/test/material/slider_test.dart [hunk 9]
```diff
@@ -5620,3 +5624,48 @@ void main() {
...
+// when animation is dismissed (a more strict requirement than "painting
+// nothing"). The default value indicator shapes is not suitable for this job
```
Comment (navaronbracke) [inline packages/flutter/test/material/slider_test.dart]: "shape" not "shapes" ?

File: packages/flutter/test/material/slider_test.dart [hunk 10]
```diff
@@ -5620,3 +5624,48 @@ void main() {
...
+// since they do not paint anything when animation is dismissed.
```
Comment (navaronbracke) [inline packages/flutter/test/material/slider_test.dart]: "it does not paint", per the change above

**Review by navaronbracke — DISMISSED** [review]
LGTM, with doc nits

**Review by navaronbracke — APPROVED** [review]
