### PR TITLE
[flutter_tools] Replace android v2 embedding broken doc link

### LINKED ISSUE #107437: [tool] Android embedding v2 migration warning points to a dead link
I'm trying to help someone fix a broken flutter project, and they're seeing the following error message:

```
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `wakelock` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
```

I still haven't gotten to the bottom of what's going wrong with my friend's flutter project, but what's particularly troublesome to me is that if I click on the second of these two links (https://flutter.dev/go/android-project-migration), I get a 404 error.  It seems to me that regardless of what's wrong with any given flutter project, Flutter should not be issuing an error message containing a broken link.

Is it possible that a "go" link on the Flutter website got inadvertently deleted?  If so, is it possible to restore it?

### PR DESCRIPTION
**Pull request by royarg02**
Replaces the now broken, removed go link for migrating to android v2
embedding with the link hosted at the Flutter wiki.

Fixes https://github.com/flutter/flutter/issues/107437
https://github.com/flutter/website/issues/7337 for additional context.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 1]
```diff
@@ -436,7 +436,7 @@ Future<void> _writeAndroidPluginRegistrant(FlutterProject project, List<Plugin>
         if (!supportsEmbeddingV1 && supportsEmbeddingV2) {
           throwToolExit(
             'The plugin `${plugin['name']}` requires your app to be migrated to '
-            'the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration '
+            'the Android embedding v2. Follow the steps on the migration doc above '
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:439]: If this message is displayed, the tool should also display the embedding warning, which already includes the doc link.

**Review by christopherfujino — APPROVED** [review]
Thanks LGTM

**Review by Jasguerrero — APPROVED** [review]
LGTM
