### PR TITLE
Call onPopInvoked when pages API is used

### LINKED ISSUE #141189: onPopInvoked not called when using Navigator.pages
### Steps to reproduce

1. Run the app below, which uses Navigator.pages for routing and has a page with a PopScope widget.
2. Navigate to the PopScope page and press the back button or perform a back gesture.

### Expected results

onPopInvoked should have been called.

### Actual results

onPopInvoked is not called. The back navigation does correctly happen, but the callback isn't called.

It does get called if popping is blocked, but not when it's successful.

In comparison try the other page, which uses WillPopScope. onWillPop is called in both situations.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

enum _Page {
  home,
  two,
  three,
}

void main() {
  runApp(const _MyApp());
}

class _MyApp extends StatefulWidget {
  const _MyApp();
  
  @override
  State<_MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<_MyApp> {
  final List<_Page> _pages = <_Page>[_Page.home];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Navigator(
        onPopPage: (Route<void> route, void result) {
          if (!route.didPop(null)) {
            return false;
          }
          setState(() {
            _pages.removeLast();
          });
          return true;
        },
        pages: _pages.map((_Page page) {
          switch (page) {
            case _Page.home:
              return MaterialPage(
                child: Scaffold(
                  backgroundColor: darkBlue,
                  body: Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        const Text('Home'),
                        TextButton(
                          onPressed: () {
                            setState(() {
                              _pages.add(_Page.two);
                            });
                          },
                          child: const Text('Go to PopScope page'),
                        ),
                        TextButton(
                          onPressed: () {
                            setState(() {
                              _pages.add(_Page.three);
                            });
                          },
                          child: const Text('Go to WillPopScope page'),
                        ),
                      ],
                    ),
                  ),
                ),
              );
            case _Page.two:
              return MaterialPage(
                child: _MyPopScopePage(),
              );
            case _Page.three:
              return MaterialPage(
                child: _MyWillPopScopePage(),
              );
          }
        }).toList(),
      ),
    );
  }
}

class _MyPopScopePage extends StatefulWidget {
  @override
  State<_MyPopScopePage> createState() => _MyPopScopePageState();
}

class _MyPopScopePageState extends State<_MyPopScopePage> {
  var canPop = true;

  @override
  Widget build(BuildContext context) => PopScope(
    canPop: canPop,
    onPopInvoked: (didPop) {
      print('PopScope onPopInvoked called. didPop=$didPop');
    },
    child: Scaffold(
      body: Column(
        children: [
          const ListTile(title: Text('You Are Next')),
          ListTile(
            onTap: () => Navigator.maybePop(context),
            title: const Text('Go Back'),
          ),
          CheckboxListTile(
            value: canPop,
            onChanged: (value) => setState(() {
              canPop = value!;
            }),
            title: const Text('Toggle canPop'),
          ),
        ],
      ),
    ),
  );
}


class _MyWillPopScopePage extends StatefulWidget {
  @override
  State<_MyWillPopScopePage> createState() => _MyWillPopScopePageState();
}

class _MyWillPopScopePageState extends State<_MyWillPopScopePage> {
  var canPop = true;

  @override
  Widget build(BuildContext context) => WillPopScope(
    onWillPop: () async {
      print('WillPopScope onWillPop called.');
      return canPop;
    },
    child: Scaffold(
      body: Column(
        children: [
          const ListTile(title: Text('You Are Next - WillPopScope page')),
          ListTile(
            onTap: () => Navigator.maybePop(context),
            title: const Text('Go Back'),
          ),
          CheckboxListTile(
            value: canPop,
            onChanged: (value) => setState(() {
              canPop = value!;
            }),
            title: const Text('Toggle canPop'),
          ),
        ],
      ),
    ),
  );
}
```

</details>

### References

Google: b/309771402

### PR DESCRIPTION
**Pull request by justinmc**
When using PopScope with the [Navigator.pages](https://main-api.flutter.dev/flutter/widgets/Navigator/pages.html) API, [PopScope.onPopInvoked](https://main-api.flutter.dev/flutter/widgets/PopScope/onPopInvoked.html) is only called when the pop is blocked and not when it's allowed. This PR fixes it by adding a call along that codepath.

Fixes https://github.com/flutter/flutter/issues/141189
Fixes Google b/309771402

### CODE REVIEW

File: packages/flutter/test/widgets/navigator_test.dart [hunk 1]
```diff
@@ -5099,6 +5099,140 @@ void main() {
         variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.android }),
         skip: isBrowser, // [intended] only non-web Android supports predictive back.
       );
+
+      testWidgets('popping a page with canPop true still calls onPopInvoked', (WidgetTester tester) async {
+        final List<_PageWithYesPop> pages = <_PageWithYesPop>[_PageWithYesPop.home];
+        bool canPop() => pages.length <= 1;
+        bool onPopInvokedWasCalled = false;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_test.dart:5106]: Maybe turn this into a count, so we can be sure it is only invoked once and not multiple times via different code paths?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/navigator_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/widgets/navigator_test.dart]: That's a much better idea, thanks.
