### PR TITLE
Make `CupertinoTextField` respect decoration color when disabled

### LINKED ISSUE #83531: CupertinoTextField overriding decoration when disabled.
## Steps to Reproduce

1. Run `flutter create bug`.
2. Change content of lib/main.dart to:

```
import 'package:flutter/cupertino.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      theme: CupertinoThemeData(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            children: [
              CupertinoTextField(
                enabled: true,
                decoration: BoxDecoration(color: Color(0xFFFF0000)),
              ),
              CupertinoTextField(
                enabled: false,
                decoration: BoxDecoration(color: Color(0xFFFF0000)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
3. Notice how the disabled field has a gray background

**Expected results:** The background of both text fields are red. I expected the background color to be respected, just like it was before #78058

**Actual results:** The background of the disabled text field is gray.

<details>
  <summary>Logs</summary>

```
```

```
bug % flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 4.3s)
```

```
bug % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.2.0 at /Users/gabroyer/Development/flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/Caskroom/android-platform-tools/30.0.0
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    ✗ No valid Android SDK platforms found in /usr/local/Caskroom/android-platform-tools/30.0.0/platforms. Directory
      was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile)      • 78D85886-701C-4254-9175-45343C35C6F5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone 12 mini (mobile) • 3E837647-6228-43E1-BD9D-A642E83A922D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
#83531 contains complaints that this default disabled color can no longer be overridden by setting a color of the `decoration` property. This regression was introduced by #78058, which was itself made to fix an issue where the color of the decoration was always used even when disabled.

Currently, when the text field is disabled, its color is set to a default disabled color. This PR makes it so that if a decoration is set when the text field is disabled, its color is used instead of the default disabled color.

Uses the sentinel value `_kDefaultRoundedBorderDecoration` to set the disabled color only if the user does not pass in a decoration.

Fixes https://github.com/flutter/flutter/issues/83531

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 1]
```diff
@@ -1338,9 +1344,21 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
 
-    final BoxDecoration? effectiveDecoration = widget.decoration?.copyWith(
-      border: resolvedBorder,
-      color: enabled ? decorationColor : disabledColor,
+    // If the text field should have a border, set the background color to the
+    // disabled color only if a color for the box decoration was not set.
+    final BoxDecoration? effectiveDecoration = (widget._textFieldType == _TextFieldType.bordered
+      ? widget.decoration?.copyWith(
+          border: resolvedBorder,
+          color: enabled ? decorationColor
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/text_field.dart:1352]: Maybe we should check if this color is a `WidgetStateColor` similar to how we've done elsewhere for `MaterialStateColor` in the past: https://api.flutter.dev/flutter/material/TimePickerThemeData/dayPeriodColor.html.

Then they could customize it for all states easier. It'd need to be called out in the documentation.

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/text_field.dart]: From what I can find, `CupertinoTextField` only has a state for when it is enabled or disabled. I can't find information on any other states (hovering, pressed, focused, etc). So would this be relevant in this case?

It might be worthwhile to create another PR to introduce widget states to `CupertinoTextField`, at which point this might be more relevant.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 2]
```diff
@@ -1338,10 +1338,17 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
         );
     }
 
-    final BoxDecoration? effectiveDecoration = widget.decoration?.copyWith(
-      border: resolvedBorder,
-      color: enabled ? decorationColor : disabledColor,
-    );
+    // Set the background color to the disabled color only if a color for the
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:1341]: nit 2: the expression below is a bit difficult to read. Maybe introduce an `effectiveDisabledColor = widget.decoration == _kDefaultRoundedBorderDecoration ? ....`

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart]: The cupertino library uses `CupertinoDynamicColor` which is a similar system but with potentially different input (resolveWith parameters).

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!
