### PR TITLE
skip interactive keyboard tests

### LINKED ISSUE #183407: FlutterTextInputPluginTest crashes with "closure argument passed as @noescape to Objective-C has escaped"
testInteractiveKeyboardAfterUserScrollToTopOfKeyboardWillTakeScreenshot crashes on iOS 26.2. The test calls -[FlutterTextInputPlugin takeKeyboardScreenshotAndDisplay], which calls [UIScreen snapshotViewAfterScreenUpdates:YES]. On iOS 26, this UIKit API seems to violate a `@noescape` block contract, crashing the process with:

```
 closure argument passed as @noescape to Objective-C has escaped: file , line 19, column 162
```

The crash kills the test process mid-run. XCTest restarts and the remaining tests pass  but the process crash causes xcodebuild to exit with code 65 (TEST FAILED). 

build: https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20mac_unopt/9/overview
log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8688125810590247857/+/u/test:_Tests_for_ios_debug_unopt_sim/stdout?format=raw

### PR DESCRIPTION
**Pull request by okorohelijah**
Skip Interactive keyboard tests that no longer apply to iOS 26+

Fixes #183407 

Tracking https://github.com/flutter/flutter/issues/183473 for full logic refactoring

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm [hunk 1]
```diff
@@ -3560,6 +3461,10 @@ - (void)testEditMenu_shouldPresentEditMenuWithCorectItemsForMoreAdditionalItems
 }
 
 - (void)testInteractiveKeyboardAfterUserScrollWillResignFirstResponder {
+  if (@available(iOS 26.0, *)) {
+    XCTSkip(@"Interactive keyboard tests broken on iOS 26+ due to SDK bugs. See: "
+             "https://github.com/flutter/flutter/issues/183473");
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:3565]: Let's remove it for iOS 17+ (as explained in the link above)

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:3487]: why is this removed instead of skipped? (like in the other tests)

**Review by hellohuanlin — APPROVED** [review]
> For the purpose of upgrading xcode #179810, we could skip and then follow up with a pr for the entire logic clean up. wdyt?

I suspect deleting the logic wouldn't be much more work, but totally up to you.

**Review by vashworth — APPROVED** [review]
