### PR TITLE
fix: Dropdown menu trying to access highlight element which doesn't exist when search and filters both are enabled

### LINKED ISSUE #151878: DropdownMenu throws RangeError when both filter and search are enabled in latest beta and master.
### Steps to reproduce

1. Create a DropdownMenu and set both enableFilter and enableSearch to true.
2. Start typing in the TextFiled, and **make sure one of the remaining filtered items is highlighted**. (Enter "b" for code sample)
3. Once the item is highlighted, enter anything that would cause all remaining entries to be filtered. (Enter "a" for code sample)

### Expected results

No errors or exceptions are thrown.

### Actual results

 DropdownMenu throws a RangeError.

Seems to be caused by https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown_menu.dart#L607 when entries is empty.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

// DropdownMenuEntry labels and values for the first dropdown menu.
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  ColorLabel? selectedColor;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: DropdownMenu<ColorLabel>(
            enableFilter: true,
            enableSearch: true,
            controller: colorController,
            requestFocusOnTap: true,
            label: const Text('Color'),
            onSelected: (ColorLabel? color) {
              setState(() {
                selectedColor = color;
              });
            },
            dropdownMenuEntries: ColorLabel.values
                .map<DropdownMenuEntry<ColorLabel>>((ColorLabel color) {
              return DropdownMenuEntry<ColorLabel>(
                value: color,
                label: color.label,
                enabled: color.label != 'Grey',
                style: MenuItemButton.styleFrom(
                  foregroundColor: color.color,
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/fccdfac2-a5bf-445f-aae8-2d6e507527c8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Microsoft Windows [版本 10.0.22631.3880], locale zh-TW)
    • Flutter version 3.23.0-0.1.pre on channel beta at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (6 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\rd1-9\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\rd1-9\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at C:\Users\rd1-9\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
DropdownMenu throws RangeError when both filter and search are enabled because when we search for elements, we have some highlighted element, but if there is no element to highlight it tries to access 0th element is the filtered entries, but entries are empty.

Fixes #151878 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -601,7 +601,7 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
 
   int? search(List<DropdownMenuEntry<T>> entries, TextEditingController textEditingController) {
     final String searchText = textEditingController.value.text.toLowerCase();
-    if (searchText.isEmpty) {
+    if (searchText.isEmpty || entries.isEmpty) {
       return null;
     }
     if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
```
Comment (PurplePolyhedron) [inline packages/flutter/lib/src/material/dropdown_menu.dart:607]: It is still possible to have out of range error when `entries` reduce in size but still non-empty.
For example, by highlighting the second item, then enter a search that only matches a single item would still cause out of range error in `entries[currentHighlight!]`.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -2432,6 +2432,29 @@ void main() {
     final TextField textField = tester.widget(find.byType(TextField));
     expect(textField.keyboardType, TextInputType.text);
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/151878
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:2436]:
```suggestion
  // Regression test for https://github.com/flutter/flutter/issues/151878.
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -2432,6 +2432,29 @@ void main() {
...
+      theme: themeData,
+      home: Scaffold(
+        body: DropdownMenu<TestMenu>(
+          enableFilter: true,
+          dropdownMenuEntries: menuChildren,
+        ),
+      ),
+    ));
+
+    // Open the menu
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:2449]:
```suggestion
    // Open the menu.
```

**Review by bleroux — COMMENTED** [review]
Thanks for the contribution.

Moving the new test just after the last one introduced in https://github.com/flutter/flutter/pull/147294/ would make sense.

**Comment by PurplePolyhedron** [comment]
Sorry for the inconvenience. I think I've made a mistake in https://github.com/flutter/flutter/pull/147294. The checking of current selection should not be put in `search`.

After some further reading of the original code, I think `search` was intended to be `static` and agnostic about the _DropdownMenuState. So the logic regarding `currentHighlight` should not be put in `search`. Furthermore it doesn't fix the issues it intended to fix (https://github.com/flutter/flutter/issues/147253, https://github.com/flutter/flutter/issues/147516) if a custom `searchCallback` is provided, since it doesn't have easy access of the current highlight.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 4]
```diff
@@ -751,10 +760,13 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
     }
 
     if (widget.enableSearch) {
-      if (widget.searchCallback != null) {
-        currentHighlight = widget.searchCallback!.call(filteredEntries, _localTextEditingController!.text);
-      } else {
-        currentHighlight = search(filteredEntries, _localTextEditingController!);
+      final bool shouldUpdateCurrentHighlight = _shouldUpdateCurrentHighlight(filteredEntries, _localTextEditingController!);
+      if(shouldUpdateCurrentHighlight){
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:764]:
```suggestion
      if (shouldUpdateCurrentHighlight){
```

**Review by QuncCccccc — COMMENTED** [review]
Thanks a lot for the contribution! Seems there are still some test failures. Could you help take a look:)?

**Comment by bleroux** [comment]
@PurplePolyhedron Does this PR conflict with your work on https://github.com/flutter/flutter/pull/152378?

**Comment by PurplePolyhedron** [comment]
> @PurplePolyhedron Does this PR conflict with your work on #152378?

Yes, there are some conflicts, #152378 removed the `currentHighlight` checking in search, because `currentHighlight` checks cannot be used for custom search, where we don't know the match conditions.

**Comment by rkishan516** [comment]
> @rkishan516 has the conflict with #152378 been resolved? Asking if this is ready for another review. :)

No, @Piinks, I am waiting for https://github.com/flutter/flutter/pull/152378 to merged and based on that I will do required changes.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 5]
```diff
@@ -751,10 +760,13 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
     }
 
     if (widget.enableSearch) {
-      if (widget.searchCallback != null) {
-        currentHighlight = widget.searchCallback!(filteredEntries, _localTextEditingController!.text);
-      } else {
-        currentHighlight = search(filteredEntries, _localTextEditingController!);
+      final bool shouldUpdateCurrentHighlight = _shouldUpdateCurrentHighlight(filteredEntries, _localTextEditingController!);
```
Comment (PurplePolyhedron) [inline packages/flutter/lib/src/material/dropdown_menu.dart:763]: We shouldn't use `shouldUpdateCurrentHighlight` when a `searchCallback` is provided, since we don't know its match condition.

**Review by PurplePolyhedron — COMMENTED** [review]
I decided to no longer change the search function in https://github.com/flutter/flutter/pull/152378 (Pending review). There shouldn't be conflict any more.

Apologies for troubles.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 6]
```diff
@@ -613,14 +613,23 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
+    }
+    return true;
+  }
+
   int? search(List<DropdownMenuEntry<T>> entries, TextEditingController textEditingController) {
     final String searchText = textEditingController.value.text.toLowerCase();
     if (searchText.isEmpty) {
       return null;
     }
-    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:621]: Sorry for the late response! Seems just adding `currentHighlight < entries.length` in this if statement can fix the problem right?

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 7]
```diff
@@ -922,6 +922,29 @@ void main() {
 
   }, variant: TargetPlatformVariant.desktop());
 
+    // Regression test for https://github.com/flutter/flutter/issues/151878.
+  testWidgets('Searching for non matching item does not crash', (WidgetTester tester) async {
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:926]:
```suggestion
  // Regression test for https://github.com/flutter/flutter/issues/151878.
  testWidgets('Searching for non matching item does not crash', (WidgetTester tester) async {
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 8]
```diff
@@ -922,6 +922,29 @@ void main() {
...
+    final ThemeData themeData = ThemeData();
+    await tester.pumpWidget(MaterialApp(
+      theme: themeData,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:929]: nit:
```suggestion
    await tester.pumpWidget(MaterialApp(
```

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 6 above)
Comment (rkishan516) [reply packages/flutter/lib/src/material/dropdown_menu.dart:621]: Yes, but we are also separating the logic for `highlight` visibility with current change, WDYT should we just add `currentHighlight < entries.length` instead of separation of logic ?

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 9]
```diff
@@ -766,7 +775,10 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       if (widget.searchCallback != null) {
         currentHighlight = widget.searchCallback!(filteredEntries, _localTextEditingController!.text);
       } else {
-        currentHighlight = search(filteredEntries, _localTextEditingController!);
+        final bool shouldUpdateCurrentHighlight = _shouldUpdateCurrentHighlight(filteredEntries, _localTextEditingController!);
+        if(shouldUpdateCurrentHighlight){
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:779]: To fix the linux analyze test:
```suggestion
        if (shouldUpdateCurrentHighlight) {
```

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 10]
```diff
@@ -613,14 +613,23 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
   }
 
+  bool _shouldUpdateCurrentHighlight(List<DropdownMenuEntry<T>> entries, TextEditingController textEditingController) {
+    final String searchText = textEditingController.value.text.toLowerCase();
+    if (searchText.isEmpty) {
+      return true;
+    }
+    if (currentHighlight != null && currentHighlight! < entries.length && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
+      return false;
+    }
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:623]: Do you think whether we can further separate this part of logic from
```
    if (currentHighlight != null && currentHighlight! < entries.length && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
      return false;
    }
```

to 

```dart
// When `entries` are filtered by filter algorithm, currentHighlight may exceed the valid range of `entries` and should be updated.
if (currentHighlight == null || currentHighlight! >= entries.length) {
  return true;
}
if (entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
  return false;
}
```

Just wanted to find a way to make it easier to understand and add some comments:) What do you think?

Comment (rkishan516) [reply packages/flutter/lib/src/material/dropdown_menu.dart:623]: Yup, make sense.

**Comment by PurplePolyhedron** [comment]
The Linux customer_testing failure seems like a flake, maybe you can try pushing an empty commit to re-run the tests?

**Comment by Piinks** [comment]
Rebase should resolve the flake. 👍

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 11]
```diff
@@ -2201,6 +2222,7 @@ void main() {
     await tester.enterText(find.byType(TextField), 'read');
     await tester.pump();
     checkExpectedHighlight(searchResult: 'Unread', otherItems: <String>['All', 'Read']); // Because "Unread" contains "read".
+    await tester.enterText(find.byType(TextField), '');
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:2225]: Why do we add this line here?

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 12]
```diff
@@ -922,6 +922,27 @@ void main() {
...
+
+    // Open the menu.
+    await tester.tap(find.byType(DropdownMenu<TestMenu>));
+    await tester.pump();
+    await tester.enterText(find.byType(TextField).first, 'Me');
+    await tester.pumpAndSettle();
+    await tester.enterText(find.byType(TextField).first, 'Meu');
+    await tester.pumpAndSettle();
+    expect(tester.takeException(), isNull);
+  }, variant: TargetPlatformVariant.desktop());
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:944]: We can remove this variant and set `requestFocusOnTap` to true

**Review by QuncCccccc — APPROVED** [review]
Thanks a lot for the fix! LGTM with nits:)

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 11 above)
Comment (rkishan516) [reply packages/flutter/test/material/dropdown_menu_test.dart:2226]: If we don't do this, for some weird reason, in newer drop down we still see `read` as input text first

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 12 above)
Comment (rkishan516) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Have done the change, please have a look.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 11 above)
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart:2226]: I haven't look, but having to update an existing test for a weird reason is usually related to a bug in the logic change introduced by the PR.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 13]
```diff
@@ -766,7 +782,10 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       if (widget.searchCallback != null) {
         currentHighlight = widget.searchCallback!(filteredEntries, _localTextEditingController!.text);
       } else {
-        currentHighlight = search(filteredEntries, _localTextEditingController!);
+        final bool shouldUpdateCurrentHighlight = _shouldUpdateCurrentHighlight(filteredEntries, _localTextEditingController!);
```
Comment (bleroux) [inline packages/flutter/lib/src/material/dropdown_menu.dart:785]: Any reason for passing _localTextEditingController as a parameter? It is an instance variable so it is visible.

Comment (rkishan516) [reply packages/flutter/lib/src/material/dropdown_menu.dart:785]: Sure, let me do the change

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 11 above)
Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart:2226]: I think the issue was in a previous version. The current version doesn't change custom search behaviour, and the test would still pass if I delete this line.

**Comment by QuncCccccc** [comment]
Please let me know once this is ready to review:) Once the PR comments above are addressed and get the second approval, we are good to go!

**Comment by rkishan516** [comment]
> Please let me know once this is ready to review:) Once the PR comments above are addressed and get the second approval, we are good to go!

I have changed things other than the test bit.
If I don't add ```await tester.enterText(find.byType(TextField), '');```, its still reading older value, even though just after that I am pumping new app.

**Comment by PurplePolyhedron** [comment]
> > Please let me know once this is ready to review:) Once the PR comments above are addressed and get the second approval, we are good to go!
> 
> I have changed things other than the test bit. If I don't add `await tester.enterText(find.byType(TextField), '');`, its still reading older value, even though just after that I am pumping new app.

Have you tried to run the test on the newest version without `await tester.enterText(find.byType(TextField), '')`?  I couldn't reproduce the issue, perhaps the issue was in a early version and has been resolved.

**Comment by bleroux** [comment]
@rkishan516 Looking at the new diff, it looks like you applied autoformat to `dropdown_menu_test.dart`. Can you update the PR without this formatting change which leads to a huge diff.

**Comment by rkishan516** [comment]
> @rkishan516 Looking at the new diff, it looks like you applied autoformat to `dropdown_menu_test.dart`. Can you update the PR without this formatting change which leads to a huge diff.

Hey @bleroux, Sorry for that. I have fixed and pushed the change.

**Comment by bleroux** [comment]
> Hey @bleroux, Sorry for that. I have fixed and pushed the change.

No worry, every contributor hit this at one point 😅

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the contribution! Once we have the second approval, we are good to go!

**Review by bleroux — APPROVED** [review]
LGTM!
