### PR TITLE
Warn when build number and version can't be parsed on iOS

### LINKED ISSUE #38610: Crash on compiling iPhone when missing pubspec.yaml version: xcrun exited abnormally
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d iphone

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
  Command: /usr/bin/xcrun simctl install 58EC574B-DF41-477A-BC0A-0BC6B51AEB56 /Users/timsneath/git/flutter_flip_view/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:437:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.8.5-pre.167, on Mac OS X 10.14.6 18G87, locale en-US)
    [32m•[39m Flutter version 1.8.5-pre.167 at /Users/timsneath/flutter
    [32m•[39m Framework revision 8cf40e90b0 (35 minutes ago), 2019-08-15 02:32:36 -0400
    [32m•[39m Engine revision 426ea8dba6
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.2.0 e35e8833ee)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    [32m•[39m Android SDK at /Users/timsneath/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 37.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.37.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.3.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m iPhone Xʀ • 58EC574B-DF41-477A-BC0A-0BC6B51AEB56 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    [32m•[39m Chrome    • chrome                               • web-javascript • Google Chrome 76.0.3809.100 


[32m•[39m No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Build number and build version are required on iOS.  Fall back to default values if one can't be parsed from the pubspec version, but warn that they need to set one before submitting to the App Store.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/38610.
See also https://github.com/flutter/flutter/pull/37036.

## Tests

Updated xcodeproj_test.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 1]
```diff
@@ -159,20 +159,53 @@ List<String> _xcodeBuildSettingsLines({
...
+  if (buildNumberIsMissing) {
+    buildNumber = defaultBuildNumber;
+  } else {
+    buildNumber = validatedBuildNumberForPlatform(TargetPlatform.ios, buildNumberToParse);
+    // Drop back to parsing build name if build number is not present. Build number is optional in the manifest, but
+    // FLUTTER_BUILD_NUMBER is required as the backing value for the required CFBundleVersion.
+    buildNumber ??= validatedBuildNumberForPlatform(TargetPlatform.ios, buildNameToParse);
+  }
+
+  if (buildNameIsMissing && buildNumberIsMissing) {
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/ios/xcodeproj.dart]: Is is useful to handle this separately? It seems like making the below non-`else` `if`s and just having two lines of output would be as easy to understand, and less code.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM; one optional nit.

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: I had that at first because it was much easier to write, but I decided to combine it to give a nicer message.  Here's the difference in output.  Current code:
```shell
Signing iOS app for device deployment using developer identity: "..."
Warning: Missing build name (CFBundleShortVersionString), defaulting to 1.0.0.
Missing build number (CFBundleVersion), defaulting to 1.
Set a build name and number in the pubspec.yaml version before submitting to the App Store.
```
Screen Shot 2019-09-16 at 5 20 52 PM

vs your suggestion:
```
Signing iOS app for device deployment using developer identity: "..."
Warning: Missing build name (CFBundleShortVersionString), defaulting to 1.0.0.
Set a build name in the pubspec.yaml version before submitting to the App Store.
Warning: Missing build number (CFBundleVersion), defaulting to 1.
Set a build number in the pubspec.yaml version before submitting to the App Store.
```
Screen Shot 2019-09-16 at 5 25 28 PM

What do you think?

Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: I actually prefer the second; I think it makes it clearer that there are two distinct issues that need to be resolved. It's clearly subjective though, so your call.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: @zanderso Do you have a preference?

Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: How about:
```dart
if (buildNameIsMissing) {
  printError('Warning: Missing build name (CFBundleShortVersionString), defaulting to $defaultBuildName.');
}
if (buildNumberIsMissing) {
  printError('Warning: Missing build number (CFBundleVersion), defaulting to $defaultBuildNumber.\n');
}
if (buildNameIsMissing || buildNumberIsMissing) {
  printError('Action Required: You must set a build name and number in the pubspec.yaml '
             'file before submitting to the App Store.');
}
```

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: Sounds good.  I added "version field" just so they knew how to add the name and number:
```
    printError('Action Required: You must set a build name and number in the pubspec.yaml '
               'file version field before submitting to the App Store.');
```
