### PR TITLE
Disableable ContextMenuButtonItems

### LINKED ISSUE #124247: It should be possible to create disabled buttons with ContextMenuButtonItem
For example, native iOS shows a disabled button when it finds no spell check suggestion for a word:

Screenshot 2023-04-05 at 9 26 16 AM

Flutter creates a button that looks tappable but nothing happens if you do tap it:

Screenshot 2023-04-05 at 11 18 01 AM

All of Flutter's buttons allow this kind of disabled button by passing `null` for `onPressed`.  Only ContextMenuButton doesn't support this (its `onPressed` is uniquely non-nullable):

https://github.com/flutter/flutter/blob/a32f0bb7a001853038e828d2731e08b1582fd9a9/packages/flutter/lib/src/widgets/context_menu_button_item.dart#L50

I propose we make it nullable so that it can be used to create disabled buttons.

### Steps to reproduce

  1. Run an app on iOS with spell check enabled, such as the one below.
  2. Type a bunch of crazy text (so that it has no spell check suggestions). Longer is better.
  3. Tap the misspelled word.

Expected: The "No replacements found" button looks disabled, like native.
Actual: It is tappable but does nothing.

<details>

<summary>Example app</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoTextField(
              maxLines: 4,
              spellCheckConfiguration: SpellCheckConfiguration(
                spellCheckService: DefaultSpellCheckService(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
Fixes https://github.com/flutter/flutter/issues/124247

| Native | Flutter before | Flutter after |
| --- | --- | --- |
| Screenshot 2023-04-05 at 9 26 16 AM | Screenshot 2023-04-05 at 11 18 01 AM | Screenshot 2023-04-05 at 11 17 36 AM |

Also, it's now possible for anyone to create disabled buttons like this by setting ContextMenuButtonItem.onPressed to `null`.

### CODE REVIEW

File: packages/flutter/test/cupertino/spell_check_suggestions_toolbar_test.dart [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+import 'package:flutter/cupertino.dart';
+import 'package:flutter/services.dart';
+
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
+  TestWidgetsFlutterBinding.ensureInitialized();
+
+  testWidgets('buildButtonItems builds a "No Replacements Found" button when no suggestions', (WidgetTester tester) async {
```
Comment (camsim99) [inline packages/flutter/test/cupertino/spell_check_suggestions_toolbar_test.dart:13]: Thanks for this test!

**Review by camsim99 — APPROVED** [review]
LGTM!
