### PR TITLE
[flutter_tools] Skip version freshness check for non-standard remotes

### LINKED ISSUE #14120: Flutter upgrade should refuse to run or run properly on a branch that comes from a fork.
I recently tried to run flutter upgrade because I was prompted to:
```/usr/local/google/home/gspencer/code/flutter/bin/flutter --no-color packages get
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 45 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter packages get" in catalog...
(code/flutter:traversal) -- flutter > flutter upgrade
Unable to upgrade Flutter: no upstream repository configured.
(code/flutter:traversal) -- flutter > git remote -v
origin	git@github.com:gspencergoog/flutter.git (fetch)
origin	git@github.com:gspencergoog/flutter.git (push)
upstream	git@github.com:flutter/flutter.git (fetch)
upstream	git@github.com:flutter/flutter.git (push)
```

And because my branch wasn't branched from flutter/flutter.git, but rather from gspencergoog/flutter.git, `flutter upgrade` errored out without telling me anything about what I should do, how I could fix it, or why it failed. This seems like a case specific to people who work on the flutter project, but really anyone who forks flutter for any reason will encounter it eventually.

We should:
1) Not warn about stale installs for forked repos
1) Fail to run `flutter upgrade` in a forked repo branch, or, alternatively
1) Make `flutter upgrade` do something useful in a forked repo branch and not error out.
1) At the very least, change the error message so that it is truthful (I *did* have an upstream repo configured, it just didn't match with the origin).

### PR DESCRIPTION
**Pull request by royarg02**
This PR makes the tool skip checking for version freshness if the remote being tracked by the current channel/branch is "not-standard". 

A standard remote is either `https://github.com/flutter/flutter.git`/`git@github.com:flutter/flutter.git` or the one set in the environment variable `FLUTTER_GIT_URL`. 

This makes the tool check for freshness from the same repo it will fetch the updates when running the `upgrade` sub-command. Another added bonus, it prevents the unnecessary check for freshness from a user's forked repo, however the user can still configure `FLUTTER_GIT_URL` for freshness check anyway in that case.

Fixes #14120.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/version.dart [hunk 1]
```diff
@@ -405,6 +408,85 @@ class FlutterVersion {
...
+        'tracked by the SDK.'
+      );
+    }
+
+    // Strip `.git` suffix before comparing the remotes
+    final String trackingUrl = stripDotGit(repositoryUrl);
+    final String flutterGitUrl = stripDotGit(globals.flutterGit);
+
+    // Exempt the official flutter git SSH remote from this check
+    if (trackingUrl == 'git@github.com:flutter/flutter') {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/version.dart:448]: rather than hard-coding here, could you also store this in `globals`, next to `flutterGit`?

File: packages/flutter_tools/test/general.shard/version_test.dart [hunk 2]
```diff
@@ -376,19 +382,19 @@ void main() {
...
           repositoryUrl: flutterNonStandardUrlDotGit,
         );
-        expect(() => VersionUpstreamValidator(version: flutterVersion).run(), returnsNormally);
+        final FakePlatform platform = createTestPlatform(flutterGitUrl: flutterNonStandardUrlDotGit);
+        expect(() => VersionUpstreamValidator(version: flutterVersion, platform: platform).run(), returnsNormally);
       }, overrides: <Type, Generator> {
-        Platform: () => FakePlatform(environment: <String, String> {
-          'FLUTTER_GIT_URL': flutterNonStandardUrlDotGit,
-        }),
+        Platform: () => createTestPlatform(flutterGitUrl: flutterNonStandardUrlDotGit),
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/version_test.dart:388]: this context platform never gets called in the test, right?

File: packages/flutter_tools/test/general.shard/version_test.dart [hunk 3]
```diff
@@ -331,12 +331,18 @@ void main() {
...
+        );
+      }
+
       testUsingContext('throws if repository url is null', () async {
         final FlutterVersion flutterVersion = FakeFlutterVersion(
           // repositoryUrl is null by default
         );
         try {
-          VersionUpstreamValidator(version: flutterVersion).run();
+          VersionUpstreamValidator(version: flutterVersion, platform: FakePlatform()).run();
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/version_test.dart:345]: I can see that before we were injecting the platform, we were accidentally leaking the real system platform into the test suite, which is a huge cause of flakiness in our tool test suite. For the tests that only depend on a created instance of `VersionUpstreamValidator`, can you use `testWithoutContext()` instead of `testUsingContext()`? With `testWithoutContext()`, any test that tries to call `context.get()` via the `globals.` or any other method will throw. This way we know exactly what our the code depends on, and we don't get tests accidentally passing because the system they were running on had the correct platform setup. I imagine you will have to also inject `flutterGitSshUrl` via the constructor.

Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/version_test.dart:345]: We would also need to provide `globals.flutterGit` too if that's the case.

Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/version_test.dart:345]: ...which adds two parameters which similar semantics?
```dart
VersionUpstreamValidator({
  required this.version,
  required this.platform,
  required this.flutterGitUrl,
  required this.flutterGitSshUrl,
});
```
Can't think of a better name to give to these parameters.

File: packages/flutter_tools/test/general.shard/version_test.dart (hunk 2 above)
Comment (RoyARG02) [reply packages/flutter_tools/test/general.shard/version_test.dart:388]: Unless the test doesn't call `globals.flutterGit`, which it definitely does :)

File: packages/flutter_tools/test/general.shard/version_test.dart (hunk 3 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/version_test.dart]: Yeah, that feels bad. However, the only other way I can think of would be to define a class for `GitHubRemote`, that takes in an org and project name, and has two getters for `httpsUrl` and `sshUrl`, but that seems like overkill?

File: packages/flutter_tools/lib/src/version.dart (hunk 1 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/version.dart]: Getting back to this, why does this need to be in `globals`? This and `flutterGit` would be only used in `version.dart`. We could probably remove them from `globals` and instead pass `globals.platform` around.

File: packages/flutter_tools/lib/src/version.dart [hunk 4]
```diff
@@ -405,6 +414,92 @@ class FlutterVersion {
   }
 }
 
+/// Checks if the provided [version] is tracking a standard remote.
+///
+/// A "standard remote" is one having the same url as [flutterGitUrl] or
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/version.dart:419]: TODO(RoyARG02): Explicitly specify that we support **only** the HTTPS & SSH urls as provided by GitHub to be standard remotes.

**Comment by RoyARG02** [comment]
Adding to my comment [here](https://github.com/flutter/flutter/pull/97202#discussion_r810451633) and my inference of the usage of `globals.dart`:

`globals.flutterGit` is only used twice in `version.dart`(it is also used in `upgrade.dart`, which this PR removes):

 https://github.com/flutter/flutter/blob/cddd5524d46b38447094353d1ecf3e9757d57e7c/packages/flutter_tools/lib/src/version.dart#L274-L283
This will be redundant once this PR lands(and can be removed).
***
 https://github.com/flutter/flutter/blob/cddd5524d46b38447094353d1ecf3e9757d57e7c/packages/flutter_tools/lib/src/version.dart#L634-L641
From what I can see, this is used for version resolution, before which the tool fetches in the newer tags. An interesting consequence of using `FLUTTER_GIT_URL` here that if the custom remote does not have the newer tags (which is the case for forks updated through `git pull upstream master && git push origin master`, and the wrong version is calculated(#15529).

I confirmed this by running `FLUTTER_GIT_URL='https://github.com/RoyARG02/flutter/flutter.git' ./bin/flutter --version --verbose` on a fresh clone of my fork which does not have the newer tags, and the tool gives me a version of ` 1.24.0-0.0.pre.7043` 😱 

Not sure if allowing `FLUTTER_GIT_URL` here would be considered a bug or feature, but we should remove `globals.flutterGit` here as well if it's the former.

**Comment by christopherfujino** [comment]
> Adding to my comment [here](https://github.com/flutter/flutter/pull/97202#discussion_r810451633) and my inference of the usage of `globals.dart`:
> 
> `globals.flutterGit` is only used twice in `version.dart`(it is also used in `upgrade.dart`, which this PR removes):
> 
> https://github.com/flutter/flutter/blob/cddd5524d46b38447094353d1ecf3e9757d57e7c/packages/flutter_tools/lib/src/version.dart#L274-L283
> 
> 
> This will be redundant once this PR lands(and can be removed).
> https://github.com/flutter/flutter/blob/cddd5524d46b38447094353d1ecf3e9757d57e7c/packages/flutter_tools/lib/src/version.dart#L634-L641
> 
> 
> From what I can see, this is used for version resolution, before which the tool fetches in the newer tags. An interesting consequence of using `FLUTTER_GIT_URL` here that if the custom remote does not have the newer tags (which is the case for forks updated through `git pull upstream master && git push origin master`), a wrong version is calculated(#15529).
> I confirmed this by running `FLUTTER_GIT_URL='https://github.com/RoyARG02/flutter/flutter.git' ./bin/flutter --version --verbose` on a fresh clone of my fork which does not have the newer tags, and the tool gives me a version of ` 1.24.0-0.0.pre.7043` 😱

Yeah, I don't think there's much we can do about this, other than deprecating the use of git tags for version resolution, which I would like to do but don't really have time for.

**Comment by RoyARG02** [comment]
@christopherfujino to solve the issue you mentioned at https://github.com/flutter/flutter/pull/97202#discussion_r810218286, can we instead do https://github.com/flutter/flutter/pull/97202#discussion_r810451633 and using a different `_flutterGit` in `VersionUpstreamValidator`? So that would look like the following:

```diff
   VersionUpstreamValidator({
     required this.version,
     required this.platform,
-    required this.flutterGitSshUrl,
-    required this.flutterGitUrl,
-  });
+  }) : _flutterGit = platform.environment['FLUTTER_GIT_URL'] ?? 'https://github.com/flutter/flutter.git';
```

A similar change can be made(in a future PR) where `FLUTTER_GIT_URL` is used:
```diff
-  static GitTagVersion determine(ProcessUtils processUtils, {String? workingDirectory, bool fetchTags = false, String gitRef = 'HEAD'}) {
+  static GitTagVersion determine(
+    ProcessUtils processUtils,
+    Platform platform, {
+      String? workingDirectory,
+      bool fetchTags = false,
+      String gitRef = 'HEAD'
+    }) {
     if (fetchTags) {
       final String channel = _runGit('git rev-parse --abbrev-ref HEAD', processUtils, workingDirectory);
       if (channel == 'dev' || channel == 'beta' || channel == 'stable') {
         globals.printTrace('Skipping request to fetchTags - on well known channel $channel.');
       } else {
-        _runGit('git fetch ${globals.flutterGit} --tags -f', processUtils, workingDirectory);
+        final String flutterGit = platform.environment['FLUTTER_GIT_URL'] ?? 'https://github.com/flutter/flutter.git';
+        _runGit('git fetch $flutterGit --tags -f', processUtils, workingDirectory);
```

File: packages/flutter_tools/lib/src/version.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/version.dart]: SGTM

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 5]
```diff
@@ -337,7 +269,18 @@ class UpgradeCommandRunner {
         throwToolExit(errorString);
       }
     }
-    verifyStandardRemote(localVersion);
+    // At this point the current checkout should be on HEAD of a branch having
+    // an upstream. Check whether this upstream is "standard".
+    try {
+      VersionUpstreamValidator(version: localVersion, platform: globals.platform).run();
+    } on VersionCheckError catch (error) {
+      throwToolExit(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/upgrade.dart:277]: I think it's a little unusual for the API of this method to be `void` while it is the responsibility of the caller to catch a `VersionCheckError`. Could you instead have this method return `VersionCheckError?`

**Review by christopherfujino — COMMENTED** [review]
This overall LGTM, with the nit about the validator.run returning a nullable error rather than throwing.

File: packages/flutter_tools/lib/src/commands/upgrade.dart (hunk 5 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:276]: Done.

**Review by christopherfujino — APPROVED** [review]
LGTM, thanks!

**Comment by christopherfujino** [comment]
@Jasguerrero can you take a look too?

**Review by Jasguerrero — APPROVED** [review]
LGTM
