### PR TITLE
Fix text selection edge scrolling when inside a horizontal scrollable

### LINKED ISSUE #129590: `SelectableText` does not maintain start position when scrolled out of view
I am using a `SelectableText.rich` widget here. Half of this widget is in view, and the other half is out of view but inside the parent scrollable. Selecting the text scrolls the scroll view over to the right but does not preserve the start position of the selection.

broken-selectable-text

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #129590

* Consider `AxisDirection` when calculating scroll offset used in determining TextSelection during a drag/long press drag. Previously it seems that we were assuming the direction was always vertical https://github.com/flutter/flutter/blob/30cc83198544582b858e48c7bb9d761ecdb3d944/packages/flutter/lib/src/widgets/text_selection.dart#L2842-L2844 .
* SelectableText now considers RenderEditable offset changes and Scrollable offset changes when calculating the TextSelection during a long press drag.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 1]
```diff
@@ -72,15 +97,37 @@ class _SelectableTextSelectionGestureDetectorBuilder extends TextSelectionGestur
     // Not required.
   }
 
+  @override
+  void onSingleLongTapStart(LongPressStartDetails details) {
+    if (!delegate.selectionEnabled) {
+      return;
+    }
+    renderEditable.selectWord(cause: SelectionChangedCause.longPress);
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/selectable_text.dart:105]: A way we can avoid having these overrides in `selectable_text.dart` so we can use the logic already in `text_selection.dart` is to use `editableText.readOnly` to differentiate between `SelectableText` and `EditableText` at the `TextSelectionGestureDetector` level. Not sure if we want to do this since maybe a user of `TextField/EditableText` might set `readOnly` to `true` and question why their gestures are behaving differently.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 2]
```diff
@@ -3689,30 +3689,202 @@ void main() {
...
           ),
         ),
       ),
     );
 
+    final Offset selectableTextStart = tester.getTopLeft(find.byType(SelectableText));
+
+    final TestGesture gesture =
+        await tester.startGesture(selectableTextStart + const Offset(200.0, 0.0));
+    await tester.pump(const Duration(milliseconds: 500));
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:3717]: Nit: Maybe use kLongPressTimeout.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Still debating your question in https://github.com/flutter/flutter/pull/140250/files#r1446817469 but I think it's fine either way.

File: packages/flutter/lib/src/material/selectable_text.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/selectable_text.dart:105]: The main difference is that on iOS a long press on static text select word-by-word, and on editable text it moves the collapsed cursor to the position.

On all other platforms (Android) a long press selects word-by-word.

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 3]
```diff
@@ -72,15 +97,37 @@ class _SelectableTextSelectionGestureDetectorBuilder extends TextSelectionGestur
...
-      );
+    if (!delegate.selectionEnabled) {
+      return;
     }
+    // Adjust the drag start offset for possible viewport offset changes.
+    final Offset editableOffset = renderEditable.maxLines == 1
+        ? Offset(renderEditable.offset.pixels - _dragStartViewportOffset, 0.0)
+        : Offset(0.0, renderEditable.offset.pixels - _dragStartViewportOffset);
+    final double effectiveScrollPosition = _scrollPosition - _dragStartScrollOffset;
+    final bool scrollingOnVerticalAxis = _scrollDirection == AxisDirection.up || _scrollDirection == AxisDirection.down;
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/selectable_text.dart:121]: I think a `switch` would work but might be a little verbose for this specific case. I think the logical comparison is clear and concise enough for this case. 

```dart
final bool scrollingOnVerticalAxis = switch (_scrollDirection) {
  AxisDirection.up => true,
  AxisDirection.down => true,
  AxisDirection.right => false,
  AxisDirection.left => false,
};
```
