### PR TITLE
RefreshIndicator dismiss transition, remain visible during refresh, etc

### LINKED ISSUE #4829: RefreshIndicator does not work if content does not overflow
## Steps to Reproduce

1. Update _items in OverscrollDemoState within overscroll_demo.dart of flutter_gallery to only have 2 items. This prevents the content from overflowing.
2. flutter run
3. Components -> Overscroll
4. Attempt to trigger the refresh by scrolling up (move finger down)
5. Observe the refresh indicator does not appear.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision e0f37027ab (5 days ago), engine revision 71ce354a44

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

## Logs and Crash Reports

No useful logs/crash reports

### LINKED ISSUE #4831: RefreshIndicator should animate out vertically if no refresh is triggered
## Steps to Reproduce

Pull down to get the RefreshIndicator to show, but not enough to trigger the refresh(). Now let go. The refresh indicator animates out using scale instead of leaving the viewport from the top. This makes it unclear if the refresh occured or not.

See how gmail on android for how it should work.

### LINKED ISSUE #4834: RefreshIndicator should stay visible while scrolling during refresh()
## Steps to Reproduce

Trigger a refresh() of the RefreshIndicator and then scroll down (drag your finger up). The refresh indicator goes away even though the Future from refresh() has not complete. The indicator should stay visible: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B1PhAWhtrRTrUlM4NHN1ei1DS2s/patterns-swipetorefresh-behavior_do_xhdpi_009.webm

### PR DESCRIPTION
**Pull request by HansMuller**
- The refresh indicator now slides out of view if it wasn't dragged far enough to trigger the refresh callback.
- Once a refresh is underway, the indicator stays put, even if the underlying scrollable is scrolled.
- The implementation now keeps track of the overscroll distance (_dragOffset) itself. The refresh indicator will appear even if overscrolling isn't possible.

Fixes #4829
Fixes #4831
Fixes #4834

### CODE REVIEW

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 1]
```diff
@@ -169,68 +171,85 @@ class _RefreshIndicatorState extends State<RefreshIndicator> {
...
-    setState(() {
-      _mode = _RefreshIndicatorMode.drag;
-    });
+  bool _isScrolledToLimit(ScrollableState scrollable) {
+    final double minScrollOffset = scrollable.scrollBehavior.minScrollOffset;
+    final double maxScrollOffset = scrollable.scrollBehavior.maxScrollOffset;
+    final double scrollOffset = scrollable.scrollOffset;
+    switch (config.location) {
+      case RefreshIndicatorLocation.top:
+        return  scrollOffset <= minScrollOffset;
```
Comment (abarth) [inline packages/flutter/lib/src/material/refresh_indicator.dart]: extra space :)

**Comment by abarth** [comment]
LGTM
