### PR TITLE
Fix RawAutocomplete crash when options are hidden

### LINKED ISSUE #182267: RawAutocomplete._updateOptionsViewVisibility() x  _zOrderIndex != null
### Steps to reproduce

1. Create a widget using RawAutocomplete like https://gist.github.com/jpohhhh/a4162216e663e5f009604934a342d631
2. Write a widget test like https://gist.github.com/jpohhhh/84f52cb84290f572eb32adf65d6feae1
3. Upgrade to Flutter 3.41.

### Expected results

Test passes after upgrade, like before upgrade.

### Actual results

Test fails.

### Code sample

[Widget gist](https://gist.github.com/jpohhhh/a4162216e663e5f009604934a342d631)
[Test gist](https://gist.github.com/jpohhhh/84f52cb84290f572eb32adf65d6feae1)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.41.0, on macOS 15.7.1 24G231 darwin-arm64, locale en-US) [181ms]
    • Flutter version 3.41.0 on channel stable at /Users/jpo/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 44a626f4f0 (30 hours ago), 2026-02-10 10:16:12 -0800
    • Engine revision 3452d735bd
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [742ms]
    • Android SDK at /Users/jpo/Library/Android/sdk
    • Emulator version 35.5.10.0 (build_id 13402964) (CL:N/A)
    ✗ Flutter requires Android SDK 36 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/to/macos-android-setup for detailed instructions.
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1) [432ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A400
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [3ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [5.6s]
    • James’s iPhone (wireless) (mobile) • 00008150-001A31C43EC0401C • ios            • iOS 26.2.1 23C71
    • macOS (desktop)                    • macos                     • darwin-arm64   • macOS 15.7.1 24G231 darwin-arm64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 144.0.7559.111

[✓] Network resources [329ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by mbcorona**
## Description
This PR fixes an assertion crash in `RawAutocomplete` that occurs when the widget is recreated and attempts to hide an overlay that was never shown.

This is a regression introduced by flutter/flutter@caa84ba097f92430d86f6446187af1d511922033 which modified the `_canShowOptionsView` getter (removing the `_selection == null` check).

The fix ensures `hide()` is only called if the options view is actually visible by using `else if (_optionsViewController.isShowing)`.

## Related Issues
Fixes #182267

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 1]
```diff
@@ -3783,4 +3783,45 @@ void main() {
     // The options view has shrunk to the available height.
     expect(tester.getSize(find.byType(Placeholder)).height, closeTo(initialSize - padding, 0.1));
   });
+
+  testWidgets('RawAutocomplete does not crash when recreated and options are hidden', (
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart]: This test passes on `master`.

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 2]
```diff
@@ -3783,4 +3783,45 @@ void main() {
...
+  ) async {
+    final focusNode = FocusNode();
+    addTearDown(focusNode.dispose);
+
+    final controller = TextEditingController();
+    addTearDown(controller.dispose);
+
+    Widget buildAutocomplete(bool toggleKey) {
+      return MaterialApp(
+        home: Material(
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart]: Nit: Can we use `TestWidgetsApp` here? To reduce our `Material` imports in this file.

Comment (mbcorona) [reply packages/flutter/test/widgets/autocomplete_test.dart]: Sure, test is using TestWidgetsApp now :D

File: packages/flutter/test/widgets/autocomplete_test.dart (hunk 1 above)
Comment (victorsanni) [reply packages/flutter/test/widgets/autocomplete_test.dart]: This test should fail on `master`, but pass with the changes in this PR, so should prevent regressing this PR's changes.

```dart
testWidgets('RawAutocomplete does not crash when hiding non-displayed overlay', (
    WidgetTester tester,
  ) async {
    final controller = TextEditingController();
    final focusNode = FocusNode();

    await tester.pumpWidget(
      TestWidgetsApp(
        home: RawAutocomplete<String>(
          key: const ValueKey('initial'),
          textEditingController: controller,
          focusNode: focusNode,
          optionsBuilder: (TextEditingValue value) => [],
          fieldViewBuilder: (context, ctrl, node, onFieldSubmitted) {
            return TestTextField(controller: ctrl, focusNode: node);
          },
          optionsViewBuilder: (context, onSelected, options) => const SizedBox(),
        ),
      ),
    );

    // Change the key to force the RawAutocomplete to dispose and re-initialize.
    await tester.pumpWidget(
      TestWidgetsApp(
        home: RawAutocomplete<String>(
          key: const ValueKey('new-key'),
          textEditingController: controller,
          focusNode: focusNode,
          optionsBuilder: (TextEditingValue value) => [],
          fieldViewBuilder: (context, ctrl, node, onFieldSubmitted) {
            return TestTextField(controller: ctrl, focusNode: node);
          },
          optionsViewBuilder: (context, onSelected, options) => const SizedBox(),
        ),
      ),
    );

    await tester.enterText(find.byType(TestTextField), 'trigger');
    await tester.pump();

    expect(tester.takeException(), isNull);
  });

```

**Review by victorsanni — CHANGES_REQUESTED** [review]

File: packages/flutter/test/widgets/autocomplete_test.dart (hunk 1 above)
Comment (mbcorona) [reply packages/flutter/test/widgets/autocomplete_test.dart]: Thanks for the feedback Victor. I've updated the test to force a widget rebuild using a Key swap while maintaining the focus and controller. This successfully reproduces the crash (the test now fails on master but passes with this PR's isShowing check).

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 3]
```diff
@@ -3783,4 +3783,47 @@ void main() {
     // The options view has shrunk to the available height.
     expect(tester.getSize(find.byType(Placeholder)).height, closeTo(initialSize - padding, 0.1));
   });
+
+  testWidgets('RawAutocomplete does not crash when hiding non-displayed overlay', (
+    WidgetTester tester,
+  ) async {
+    final controller = TextEditingController();
+    final focusNode = FocusNode();
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart:3791]: These will need to be disposed.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/widgets/autocomplete_test.dart (hunk 3 above)
Comment (mbcorona) [reply packages/flutter/test/widgets/autocomplete_test.dart:3791]: Thanks for the feedback, and good catch, I just added the dispose for both.
