### PR TITLE
Fix out-of-bounds and reversed TextBox queries in computing caret metrics

### LINKED ISSUE #50563: Cursor always at the front when first typing some emojis
## Steps to Reproduce

The cursor often is stuck at the beginning of the TextField when first typing some emojis 

Repro:

Open any flutter TextField 
Type emoji characters, preferably ones with zero-width-joiners such as 👩‍🚀
Cursor is stuck at front, and tapping in the text works (new text shows up correctly, backspacing works) but the cursor does not appear in the right spot.

this is familiar with the issue #24266 but not the same at all, such as he says the nation flags will cause this problem, but i can't reproduce it.

I have tried many emojis to reproduce, and I found that these emojis would cause the problem,and I printed out the code units to look for the law.

👩‍🚀,[55357, 56425, 8205, 55357, 56960] runes:3,length:5

👩‍❤️‍💋‍👩,[55357, 56425, 8205, 10084, 65039, 8205, 55357, 56459, 8205, 55357, 56425] runes:8,length:11

👨‍👩‍👦‍👦,[55357, 56424, 8205, 55357, 56425, 8205, 55357, 56422, 8205, 55357, 56422] runes:7,length:11
👨🏾‍🤝‍👨🏻,[55357, 56424, 55356, 57342, 8205, 55358, 56605, 8205, 55357, 56424, 55356, 57339] runes:7,length:12

👨‍👦,[55357, 56424, 8205, 55357, 56422] runes:3,length:5

👩‍👦,[55357, 56425, 8205, 55357, 56422] runes:3,length:5

it seems that the emojis which make use of zero width joiners,(code 8205),will easily cause the problem,but not all. I also found that these emojis wont cause the problem,such as:

👩‍❤️‍👨,[55357, 56425, 8205, 10084, 65039, 8205, 55357, 56424] runes:6,length:8
🏌🏿‍♀️,[55356, 57292, 55356, 57343, 8205, 9792, 65039] runes:5,length:7
🏊‍♀️,[55356, 57290, 8205, 9792, 65039] runes:4,length:5
🏄🏻‍♂️,[55356, 57284, 55356, 57339, 8205, 9794, 65039] runes:5,length:7
🇨🇳,[55356, 56808, 55356, 56819] runes:2,length:4

so, what kind of emojis will cause it and why these problem occurs？
**Expected results:** 
expect the cursor can stay at the correct position.
**Actual results:** 
image

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### LINKED ISSUE #98516: Incorrect horizontal caret movement with Unicode combining characters
## Steps to Reproduce

1. Execute `flutter run` on the code sample (just a text field)

2. Paste "Zalgo" unicode combining characters abuse string to the text field: Zalgo

**Expected results:** Can move the caret between all character using keyboard left/right arrows

**Actual results:** Caret is stuck before the first character on first right arrow keypress, then jumps over two characters.

Interestingly when selecting text using Shift + right arrow the issue isn't there.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() { _counter++; });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            const Expanded(
              child: TextField(maxLines: null),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
 flutter doctor -v
[√] Flutter (Channel master, 2.11.0-0.0.pre.562, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.11.0-0.0.pre.562 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2a2f973120 (2 hours ago), 2022-02-15 07:33:57 -0800
    • Engine revision e683e0cd3b
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

### LINKED ISSUE #118403: Incorrect caret position with complex scripts
caret

## Steps to Reproduce

1. Execute `flutter run` on the code sample on a platform with HW keyboard
2. Traverse the text using arrow left/right keys

**Expected results:** Caret advances correctly

**Actual results:** Caret jumps back and forth

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const TextStyle style = TextStyle(fontSize: 16.0);
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          children: <Widget>[
            const SizedBox(height: 100.0),
            TextField(controller: TextEditingController(text: 'प्राप्त वर्णन प्रव्रुति')),
            const SizedBox(height: 100.0),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
% flutter --version
Flutter 3.7.0-20.0.pre.6 • channel master • https://github.com/flutter/flutter.git
Framework • revision f8628b5cb1 (15 hours ago) • 2023-01-11 18:48:03 -0800
Engine • revision 4a8d6866a1
Tools • Dart 3.0.0 (build 3.0.0-112.0.dev) • DevTools 2.20.0
```

</details>

### LINKED ISSUE #122477: Caret misplaced for emoji plus text
If you type some text and then a complex emoji, the caret will stay at the start of the emoji rather than move to the end.

This resembles #50563, #98516, and #118403, but the symptoms are subtly different, and the fix is unrelated although it's in a nearby part of the code. (I'll be sending a PR with both fixes soon.)

## Steps to Reproduce

1. Go to any ordinary text input field in a Flutter app, such as the code sample below. Use a device where you can easily input emoji.
2. Type the letters "abc", then a complex emoji like "👩‍🚀". (A simple emoji like "👍" won't show the issue; details below.)
3. Type some more text.

**Expected results:**

The cursor (aka caret) moves to the end of each character you type.

All the text you type is shown in the order you typed it.

**Actual results:**

On typing the emoji, the cursor stays at the start of the emoji.

On typing more text, the cursor jumps back to the end. All the text you type is correctly shown in the order you typed it. So this shows that the underlying text input state knows the cursor should be at the end, and we're just painting it in the wrong place.

## Repro details

In order to trigger the issue, the emoji's length in UTF-16 code units has to not be a power of 2: it has to be something other than 1, 2, 4, 8, etc. The simplest emoji are 1 or 2 code units long and don't trigger the issue. Most emoji that have a gender or skin-color modifier, or show a family or make other use of the zero-width joiner code point, do trigger the issue.

The repro may depend on the fonts you have on the device. I observe it on a Pixel 5 running Android 13, and on an iPhone 7 running iOS 15.

If you type "a👩‍🚀" or "ab👩‍🚀" instead of "abc👩‍🚀", then when you type the emoji, the behavior is still wrong but with a different symptom: the cursor will jump backward to the beginning, instead of staying at the start of the emoji. This symptom is caused by #50563.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(DemoApp());
}

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: "Demo app", home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Demo app")),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          TextField(maxLines: null),
          ElevatedButton(
              onPressed: () => FocusScope.of(context).unfocus(),
              child: Text('Unfocus'),
          ),
        ],
      ),
    );
  }
}
```

</details>

Video:

<video src="https://user-images.githubusercontent.com/28173/224517547-de5f179f-f2f0-4082-adf8-49b2343886ea.mp4">

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #50563.
Fixes #98516.
Fixes #118403.
Fixes #122477.

It turns out that `Paragraph.getBoxesForRange` will not accept a negative index for the start of the range; if you pass one, it will return an empty list.  We'd been doing that in `TextPainter._getRectFromUpstream`; this was causing #50563, #98516, and #118403.  (Arguably this makes them duplicates of each other, but they looked quite distinct until being debugged: they involve complex emoji, zalgo text, and Indic script respectively.)

Fix that by clamping the start to zero, because what we really intended here in that case is the whole text up to the given end offset.

Then it turns out that we were sometimes reaching this line with a negative end index too (when the selection is empty on reaching `RenderEditable._updateSelectionExtentsVisibility`.)  That was giving an empty list of boxes, but if we clamp the start but not the end, we'd get back boxes for the whole text instead.  Avoid that by short-circuiting that case at the top of the function, like we do when the offset is out of bounds in the other direction.

Finally, when we get back more than one box from `getBoxesForRange`, we were looking at the wrong end of the list: if we're looking upstream, we want the end of the *last* preceding box, not the first one.  Similarly when looking downstream we want the start of the first following box, not the last one.  This was causing #122477, which I discovered while studying this code to diagnose #50563. Fix that too.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gnprice** [comment]
There are also several issues in the tracker that sound potentially related to the issues this fixes but involve RTL text:
* #78660
* #110416
* #118566
* #120049
* #120604

or WidgetSpans:
* #107432

I haven't yet investigated whether this fixes any of those issues.

**Comment by gnprice** [comment]
Resolved conflicts after #120834.

**Review by LongCatIsLooong — COMMENTED** [review]
Thanks for looking into this! LGTM overall but I think it might be worth looking at the callers of `getBoxesForRange` and fixing them as well. 

On the other hand currently we do expose `getBoxesForRange` as a public API (also there're some other APIs that provide similar functionalities) but it's not clear to me how they should behave when given an OOB index. I'll create an issue for that.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -1047,7 +1047,7 @@ class TextPainter {
   // character upstream from the given string offset.
   _CaretMetrics? _getMetricsFromUpstream(int offset) {
     final int plainTextLength = plainText.length;
-    if (plainTextLength == 0 || offset > plainTextLength) {
+    if (plainTextLength == 0 || offset > plainTextLength || offset < 0) {
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/painting/text_painter.dart:1050]: Sure, I can take a look at doing that. I think it was only after I wrote this PR that I found https://github.com/flutter/flutter/issues/95978#issuecomment-1006997846 and #79615 and understood the context of that `-1` better.

**Comment by gnprice** [comment]
Revised. Thanks for the review!

I took the liberty of adding a couple of TODO comments referring to you (@LongCatIsLooong). They come about because I ran into this existing TODO comment:
```dart
    // TODO(LongCatIsLooong): skip painting the caret when the selection is
    // (-1, -1).
    if (selection == null || !selection.isCollapsed) {
      return;
```

From the Git history, I see that's from https://github.com/flutter/flutter/issues/79495 , for which a previous fix was reverted because fixing it was a breaking change.

**Comment by exaby73** [comment]
cc: @exaby73 for later reference https://github.com/flutter/flutter/issues/120049#issuecomment-1476910624

File: packages/flutter/test/painting/text_painter_test.dart [hunk 2]
```diff
@@ -12,11 +12,105 @@ const bool isCanvasKit =
...
+    checkCaretOffsetsLtrAt(buffer.toString(), boundaries);
+  }
+
+  List<double> caretOffsetsForTextSpan(TextSpan text) {
+    final TextPainter painter = TextPainter()
+      ..textDirection = TextDirection.ltr
+      ..text = text
+      ..layout(maxWidth: 10000);
+    final int length = text.toPlainText().length;
+    final List<double> result =
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:97]: should be on the same line?

File: packages/flutter/test/painting/text_painter_test.dart [hunk 3]
```diff
@@ -12,11 +12,105 @@ const bool isCanvasKit =
...
+    expect(boundaries.last, text.length);
+
+    final TextPainter painter = TextPainter()
+      ..textDirection = TextDirection.ltr;
+
+    // Lay out the string up to each boundary, and record the width.
+    final List<double> prefixWidths = <double>[];
+    for (final int boundary in boundaries) {
+      painter.text = TextSpan(text: text.substring(0, boundary));
+      painter.layout(maxWidth: 10000);
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:26]: nit: I think you could just omit `maxWidth` here? The default value is infinity iirc.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

File: packages/flutter/test/painting/text_painter_test.dart (hunk 3 above)
Comment (gnprice) [reply packages/flutter/test/painting/text_painter_test.dart:26]: Ah indeed, thanks for the catch.

File: packages/flutter/test/painting/text_painter_test.dart [hunk 4]
```diff
@@ -12,11 +12,105 @@ const bool isCanvasKit =
     bool.fromEnvironment('FLUTTER_WEB_USE_SKIA');
 
 void main() {
+  void checkCaretOffsetsLtrAt(String text, List<int> boundaries) {
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/test/painting/text_painter_test.dart]: Sure. Moved them out of the scope of `main`, and then also took the occasion to expand on the docs a bit more.

**Comment by gnprice** [comment]
Thanks for the review! Pushed a version with those tweaks to the tests.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 5]
```diff
@@ -1079,7 +1080,7 @@ class TextPainter {
         graphemeClusterLength *= 2;
         continue;
       }
-      final TextBox box = boxes.first;
+      final TextBox box = boxes.last;
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/painting/text_painter.dart:1083]: Interesting question. I'd be surprised if that was the behavior, but I can't immediately rule it out — in particular the dartdoc on getBoxesForRange doesn't say anything about the order of the boxes in the list.

... OK, and I wrote a test for this, and indeed the boxes seem to be in display order! Thanks for the catch.

I'll revise so that the change doesn't break anything that was working before. I expect it still won't work reliably in the presence of bidi, but fixing that may require bigger changes to this code.

[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/painting/text_painter.dart]: Done; PTAL.

I also filed #123424 to track that this logic doesn't seem like it can work in the bidi case. That's an issue this PR doesn't fix, and I think is best left out of scope because it will probably require bigger changes.

**Review by tgucio — APPROVED** [review]
LGTM

File: packages/flutter/test/painting/text_painter_test.dart [hunk 6]
```diff
@@ -11,12 +11,121 @@ import 'package:flutter_test/flutter_test.dart';
...
+///
+/// This lays out the given text as a single line with the given [textDirection]
+/// and returns a full list of caret offsets, one at each code unit boundary.
+///
+/// This also checks that the offset at the very start or very end, if the text
+/// direction is RTL or LTR respectively, equals the line's width.
+///
+/// If you have a [String] instead of a nontrivial [TextSpan],
+/// consider using [checkCaretOffsetsLtr] instead.
+List<double> caretOffsetsForTextSpan(TextDirection textDirection, TextSpan text) {
```
Comment (justinmc) [inline packages/flutter/test/painting/text_painter_test.dart:103]: Nit: Should these functions be private or do you expect them to be used elsewhere?

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

I think this can merge, but there's a simple merge conflict in the test.

File: packages/flutter/test/painting/text_painter_test.dart (hunk 6 above)
Comment (gnprice) [reply packages/flutter/test/painting/text_painter_test.dart:103]: Because this file has a `main` function and will never be imported from, the private/public distinction doesn't mean as much as usual. I think the convention I've mostly seen in test files is to leave off the `_` prefix, even for test fixtures that are firmly private in intention.

Searching, it's a bit more mixed than my impression had been, but I think still more without the `_` prefix than with it: `git grep -P '^(?!import\b|library\b|void main\b|//)\w.*' 'test/*_test.dart'`

Given that and because these read a bit better to me without the `_` prefix, I'm inclined to leave it off.

**Review by gnprice — COMMENTED** [review]
Thanks for the review! Merged (i.e. resolved conflicts) and fixed nits.

File: packages/flutter/test/painting/text_painter_test.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/test/painting/text_painter_test.dart:100]: Sounds good, I've also seen both in other tests.

**Comment by RomanIvn** [comment]
[√] Flutter (Channel main, 3.9.0-20.0.pre.91, on Microsoft Windows [Version 10.0.19044.2728], locale he-IL)
    • Flutter version 3.9.0-20.0.pre.91 on channel main at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a1a47c243 (22 minutes ago), 2023-04-03 05:51:18 -0400
    • Engine revision 0ed4b5ecbc
    • Dart version 3.0.0 (build 3.0.0-401.0.dev)
    • DevTools version 2.22.2
 
`
TextEditingController tec = TextEditingController(text: "בדיקה בדיקה בדיקהבדיקה בדיקה בדיקה
שדגשבדיקה בדיקה בדיקהבדיקה בדיקה בדיקה
שדגש");

TextField(
             controller: tec,
              keyboardType: TextInputType.multiline,
              maxLines: null,
              textDirection: TextDirection.rtl,
              textAlign: TextAlign.right,
            )
`

Issue persists with simple textfield and hebrew text within when using **multilines**.
Keyboard arrows are reversed and cursor jumps to the one before last latter when double-clicking a word (web)

**Comment by RomanIvn** [comment]
Issues persist when using multiline text

TextField(
              keyboardType: TextInputType.multiline,
              maxLines: null,
              textDirection: TextDirection.rtl,
              textAlign: TextAlign.right,
            )

**Comment by gnprice** [comment]
@RomanIvn Please file a new issue for the problem you're seeing. That will be a more effective place to address it than in a merged PR's thread. Do include all the information in the issue template, including details of what behavior you expected and what behavior you see instead.

Since you mention `TextDirection.rtl`, take a look also at these still-open issues and see if one of them describes what you're seeing:

> There are also several issues in the tracker that sound potentially related to the issues this fixes but involve RTL text:
> 
> * [Arrow keys in RTL move the wrong way #78660](https://github.com/flutter/flutter/issues/78660)
> * [Incorrect cursor position in RTL TextField when moving between letters #110416](https://github.com/flutter/flutter/issues/110416)
> * [Text field cursor position in RTL goes to the penultimate character #118566](https://github.com/flutter/flutter/issues/118566)
> * [RTL textField Cursor movement has a problem with the last position and Emojies and text selection #120049](https://github.com/flutter/flutter/issues/120049)
> * [TextField cursor stands in a wrong position while using persian words #120604](https://github.com/flutter/flutter/issues/120604)
> 
> or WidgetSpans:
> 
> * [WidgetSpan wrong caret position #107432](https://github.com/flutter/flutter/issues/107432)
> 
> I haven't yet investigated whether this fixes any of those issues.
