### PR TITLE
when setting up the log reader for a device during `flutter run`, discard any `RPCError` thrown due to the device being disconnected

### LINKED ISSUE #154903: RPCError: getVM: (-32000) Service connection disposed
Parent issue: https://github.com/flutter/flutter/issues/153471.

Thrown by a `VMService.getVM` call from `FlutterDevice.initLogReader`.

## Stack traces (from version 3.24.2)

```
RPCError: getVM: (-32000) Service connection disposed
at VmService._call(vm_service.dart:1769)
at VmService.getVM(vm_service.dart:1245)
at FlutterDevice.initLogReader(resident_runner.dart:428)
at HotRunner.attach(run_hot.dart:266)
at <asynchronous gap>(async)
at RunCommand.runCommand(run.dart:867)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1408)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:420)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:364)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:130)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at main(executable.dart:93)
at <asynchronous gap>(async)
```

```
RPCError: getVM: (-32000) Service connection disposed
at new _OutstandingRequest(vm_service.dart:261)
at VmService._call.<anonymous closure>(vm_service.dart:1778)
at VmService._call(vm_service.dart:1790)
at VmService.getVM(vm_service.dart:1245)
at FlutterDevice.initLogReader(resident_runner.dart:428)
at HotRunner.attach(run_hot.dart:266)
at <asynchronous gap>(async)
at RunCommand.runCommand(run.dart:867)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1408)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:420)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:364)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:130)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at main(executable.dart:93)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes https://github.com/flutter/flutter/issues/154903

This PR contains some refactoring. To make the actual change easier to figure out, I've tried to separate parts of the change into multiple commits for easier reviewing 🙂.

**I plan on cherry-picking this change to stable.**

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 1]
```diff
@@ -491,6 +491,22 @@ class FlutterVmService {
...
 
+  /// Calls [service.getVM]. However, in the case that an [vm_service.RPCError]
+  /// is thrown due to the service being disconnected, the error is discarded
+  /// and null is returned.
+  Future<vm_service.VM?> getVmGuarded() async {
+    try {
+      return await service.getVM();
+    } on vm_service.RPCError catch (err) {
+      if (err.code == RPCErrorCodes.kServiceDisappeared ||
+          err.message.contains('Service connection disposed')) {
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/vmservice.dart:502]: I'm aware of https://github.com/dart-lang/sdk/commit/e099a00ee263460a745f3bad9e51535d98d87ff7, but I don't think the new error code is exposed anywhere yet.

Comment (bkonyi) [reply packages/flutter_tools/lib/src/vmservice.dart:502]: Yeah, it looks like we'll need to publish a new version of `package:vm_service`, but if we're going to be CP'ing this change this is probably sufficient for now.

**Review by bkonyi — APPROVED** [review]

**Comment by andrewkolos** [comment]
Holding off on the cherry-pick.

I chatted with @jonahwilliams and did some quick experiments and figured out `FlutterDevice.tryInitLogReader` (formerly `initLogReader`) doesn't do what I thought it does. All it does is set the `appPid` field on the device's `DeviceLogReader`. The only reference of this I could find of `appPid` is

https://github.com/flutter/flutter/blob/7292c94bac6875e6e178fcdefd8313998746e745/packages/flutter_tools/lib/src/android/android_device.dart#L1192-L1199

For context (though I'm no expert here): To get logs from Android, we need to use `adb logcat`; but gives us more than just the logs from the Flutter app. That's why we need this extra logic to filter out all of the noise.

**Why this matters.** For users not running apps on Android, the error message I introduced would be pointless and confusing noise.

I'll see if there is a way to relocate this `tryInitLogReader` away from the general `ResidentRunner` workflow and over to the Android side of things. If that fails, I can at least update the error message to be less confusing (as-is, the message implies that logging won't work, but in reality it still will—though the Android workflow might become unstable if the device is running other apps...hmm, maybe we should `throwToolExit` in that case...).
