### PR TITLE
[Impeller] Commands that don't specify their own viewports get the viewport of the render pass.

### LINKED ISSUE #176945: [Impeller] OpenGL commands may use the incorrect viewport.
Regression introduced in https://github.com/flutter/engine/pull/56902.

One of the aims of the linked patch was to remove redundant calls to `Viewport` and `DepthRange`. It did this by moving the primary call to `Viewport` outside of the loop that iterated over the commands and only updating the viewport for commands that explicitly specified a viewport.

But this introduced a subtle bug where commands after one that specified a viewport that also did not specify their own viewport would get the viewport of a previous command (instead of one that covered the entire extent of the render pass).

This is an OpenGL specific regression.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/176945

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc [hunk 1]
```diff
@@ -303,24 +335,7 @@ void RenderPassGLES::ResetGLState(const ProcTableGLES& gl) {
...
-  );
-  if (pass_data.depth_attachment) {
-    if (gl.DepthRangef.IsAvailable()) {
-      gl.DepthRangef(viewport.depth_range.z_near, viewport.depth_range.z_far);
-    } else {
-      gl.DepthRange(viewport.depth_range.z_near, viewport.depth_range.z_far);
-    }
-  }
-
+  std::optional<Viewport> current_viewport;
```
Comment (jtmcdole) [inline engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: Is it just me, or is `current_viewport` never set anywhere?

Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: It's set in EncodeViewport, it's passed by reference.

Comment (jtmcdole) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: Then I feel it should moved to just above 390. That said, it's still not used. It gets passed in and checked - those checks will never be true, then its set to new_viewport and.. never used again.

Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: Yea, you're right.  It seems this PR isn't quite as ready to go as was suspected.

**Review by gaaclarke — CHANGES_REQUESTED** [review]
There is a variable that is passed in as what appears to be a cache or some sort but it is on the stack.  It looks like the idea of the PR isn't fully implemented.

Plus it needs tests.

File: engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: This function is big, you can't see it but this is in a loop.  That's how it's supposed to work.

Comment (jtmcdole) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles.cc:339]: If github wasn't down today, I would have reviewed from vscode. Thanks

**Review by gaaclarke — DISMISSED** [review]
I added 2 tests, one that makes sure we coalesce duplicate viewports and one for reverting to the render pass viewport.

File: engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc [hunk 2]
```diff
@@ -114,5 +116,137 @@ INSTANTIATE_TEST_SUITE_P(
...
+  render_pass->SetElementCount(1);
+  render_pass->SetIndexBuffer({}, IndexType::kNone);
+  render_pass->SetViewport(
+      Viewport{Rect::MakeXYWH(0, 0, 50, 50), DepthRange{0.0f, 1.0f}});
+  EXPECT_TRUE(render_pass->Draw().ok());
+
+  // Viewport should only be called twice. Once for the fallback, once for the
+  // first override. We set a catch-all to 0 to ensure no other calls occur.
+  EXPECT_CALL(mock_gl_impl_ref, Viewport(_, _, _, _)).Times(0);
+  EXPECT_CALL(mock_gl_impl_ref, Viewport(0, 0, 100, 100)).Times(1);
```
Comment (jtmcdole) [inline engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc:313]: took me a second to realize this was the first render_pass call and it was falling back to the created render pass 100,100.  The expectation is far enough away, is it worth noting on 189 "// uses default viewport"

**Review by jtmcdole — DISMISSED** [review]

File: engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc (hunk 2 above)
Comment (jtmcdole) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc:313]: this is a nit comment and can be resolved if you don't agree.

**Comment by zanderso** [comment]
If @chinmaygarde would like, @gaaclarke you can sponsor adding him back to flutter-hackers on Discord.

File: engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/gles/render_pass_gles_unittests.cc:313]: Yea, it's kind of a bummer.  I think there an alternative way to assert which is more like sequential versus how many times something is called.  It would probably be more clear but I didn't think it was worth complicating.

**Review by gaaclarke — APPROVED** [review]

**Comment by gaaclarke** [comment]
@jtmcdole I had to rebase this because autosubmit failed and it got stale, can I get a reapproval?

**Review by jason-simmons — APPROVED** [review]

**Review by jtmcdole — APPROVED** [review]
