### PR TITLE
Remove network images from cache on any exception during loading

### LINKED ISSUE #47270: NetworkImage should evict itself from the cache if it fails to load due to a network error.
I find a bug in NetworkImage/image_cache.  if I load image when network is not available. now, my network is available,setState my widget, image will not work. look the source code,I find the bug in  framework. 
I find the code at image_cache.dart
` try {
      result = loader();
    } catch (error, stackTrace) {
      if (onError != null) {
        onError(error, stackTrace);
        return null;
      } else {
        rethrow;
      }
    }`
call loader() with sync but at _network_image_io.dart the loader() is async, If network is not available, loader() is failed, it can't not match your catch but put the error result to _pendingImages. when my network is available, I refresh my networkImage,it will return me error result from _pendingImages

企业微信截图_b69ed4d4-1d45-4f04-804d-029ead4bcf70

企业微信截图_ae161c5a-f7a0-41df-8cc7-55e6277153c0

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Makes network image resolution evict from the cache on any exception - previously, we'd miss various things like socket exceptions during an http request and get stuck with a bad image in the cache.

This means that we'd also refuse to keep a 0 length image in the cache even if everything else succeeds, which seems fine to me - it seems likely that is either a network error or a cheap thing to retry, and we still report the error.

## Related Issues

Fixes #47270 again

## Tests

I added the following tests:

Test covering eviction of the image from the cache on a socket exception

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/painting/_network_image_io.dart [hunk 1]
```diff
@@ -108,6 +109,15 @@ class NetworkImage extends image_provider.ImageProvider<image_provider.NetworkIm
         throw Exception('NetworkImage is an empty file: $resolved');
 
       return decode(bytes);
+    } catch (e) {
+      // Depending on where the exception was thrown, the image cache may not
+      // have had a chance to track the key in the cache at all.
+      // Schedule a microtask to give the cache a chance to add the key.
+      scheduleMicrotask(() {
+        final bool removed = PaintingBinding.instance.imageCache.evict(key);
+        assert(removed);
```
Comment (ds84182) [inline packages/flutter/lib/src/painting/_network_image_io.dart:118]: This assert may fail if some other code evicts the entry from the image cache before the microtask runs.

For example, if another part of an app does a manual eviction on the network image in a microtask scheduled before this one.

**Review by ds84182 — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/painting/_network_image_io.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/painting/_network_image_io.dart]: My first thought was that that would never be a valid thing to do - I still think that would be pretty unusual - but we have another test that happens to exercise the provider without using the cache at all, which is also definitely valid, and this assert fails there.  Removed.

File: packages/flutter/lib/src/painting/_network_image_io.dart [hunk 2]
```diff
@@ -108,6 +109,14 @@ class NetworkImage extends image_provider.ImageProvider<image_provider.NetworkIm
...
 
       return decode(bytes);
+    } catch (e) {
+      // Depending on where the exception was thrown, the image cache may not
+      // have had a chance to track the key in the cache at all.
+      // Schedule a microtask to give the cache a chance to add the key.
+      scheduleMicrotask(() {
+        PaintingBinding.instance.imageCache.evict(key);
+      });
+      rethrow;
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/_network_image_io.dart:119]: Is it possible that the re-thrown exception is caught and the exception handler puts a replacement image synchronously in the cache that would then unintentionally get removed in the next microtask?

Comment (dnfield) [reply packages/flutter/lib/src/painting/_network_image_io.dart:119]: Depending on where the exception got thrown, the ImageCache could end up overwriting it with the failing image anyway assuming the user code used the same key.  But in general that would be a bad idea - if your image key caused an exception, you shouldn't be caching anything related to that key, because if the exceptional circumstances change later you'll always get back the "exception" image instead of the good one.

Comment (dnfield) [reply packages/flutter/lib/src/painting/_network_image_io.dart:119]: So I think the answer to your question is: there's probably some weird way to make that happen, but it would be a bad idea anyway.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by yuvidevp** [comment]
why every time rethrow when handle 404 image url error, can anyone guide me how to solve this issue...
