### PR TITLE
BottomAppBar: Fix doubled layers of color and shadow

### LINKED ISSUE #122667: BottomAppBar: Material 3 makes the color too opaque
## Steps to Reproduce

1. Copy code sample below to `main.dart` in a new `flutter create` app
2. Look at the color of the `AppBar` at the top and the `BottomAppBar` at the bottom

**Expected results:** They should be the same color, since the code sets the `AppBar`'s `backgroundColor` and the `BottomAppBar`'s `color` to the same value, `Colors.black45`.

**Actual results:** The `BottomAppBar` appears more opaque than the `AppBar`.

main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    Color color = Colors.black45;

    return MaterialApp(
      theme: Theme.of(context).copyWith(useMaterial3: true),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: color,
        ),
        bottomNavigationBar: BottomAppBar(
          color: color
        ),
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

(No errors expected or observed in the logs.)

```
$ flutter analyze
Analyzing scratch...                                                    
No issues found! (ran in 1.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.9.0-7.0.pre.32, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.9.0-7.0.pre.32 on channel main at /Users/chrisbobbe/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e2e313ecf6 (2 hours ago), 2023-03-14 19:13:21 -0700
    • Engine revision e80266b78e
    • Dart version 3.0.0 (build 3.0.0-322.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chrisbobbe/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/chrisbobbe/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Chris’s iPhone (mobile) • 00008110-000924383632801E            • ios            • iOS 16.1 20B82
    • iPhone 14 Pro (mobile)  • B10DA4B8-480B-4FE1-A651-4DFBE39ABF71 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 111.0.5563.64
    ! Error: Chris’s Apple Watch needs to connect to determine its availability. Check the connection between the
      device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to
      be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

image

It looks like the `color` is being applied at two layers, making the element more opaque than it would if the `color` were applied at just one layer.

See these lines in `bottom_app_bar.dart`; I've annotated two lines in my quote below:

https://github.com/flutter/flutter/blob/e2e313ecf/packages/flutter/lib/src/material/bottom_app_bar.dart#L202-L219
```dart
    final Material material = Material(
      key: materialKey,
      type: isMaterial3 ? MaterialType.canvas : MaterialType.transparency,
      elevation: elevation,
      color: isMaterial3 ? effectiveColor : null, // <---------- here, and…
      surfaceTintColor: surfaceTintColor,
      shadowColor: shadowColor,
      child: SafeArea(child: child),
    );

    final PhysicalShape physicalShape = PhysicalShape(
      clipper: clipper,
      elevation: elevation,
      shadowColor: shadowColor,
      color: effectiveColor, // <---------- …here
      clipBehavior: widget.clipBehavior,
      child: material,
     );
```

### LINKED ISSUE #123283: BottomAppBar: "Notch" shape silently broken in Material 3
In Material 3, if you use `BottomAppBar`'s [`shape` param](https://api.flutter.dev/flutter/material/BottomAppBar/shape.html) to ask for a "notched" shape for the FAB, it won't say anything, but the result is visually broken.

Probably the right answer here is to use an assert to disallow this, because [Material 3 removed the notch shape](https://m3.material.io/components/bottom-app-bar/specs) in the spec.

I plan to send a PR soon with that assert, along with fixes for #123064 and #122667.

## Steps to Reproduce

1. Copy code sample below to `main.dart` in a new `flutter create` app.
   
   The code sample configures `BottomAppBar` to have a "notch", by setting `shape` and by putting a docked FAB in the Scaffold. It also sets `useMaterial3: true` and an opaque color for the app bar.
  
2. Look at the bottom app bar, where the "notch" is supposed to be.
3. Pass a translucent `color` to the `BottomAppBar`, like `Colors.black45`
4. Look at the bottom app bar again

## Actual results

In step 2, with an opaque `color`, no notch is visible.

In step 4, with a translucent `color`, there's a broken sort-of-notch: a more opaque shape forms a notch, but the notch is painted through by a less opaque shape. (Also the shape doesn't fit the FAB; that's just because there isn't an out-of-the-box `NotchedShape` that would fit the Material 3 default FAB shape.)

| Material 2 (for comparison) | Material 3, opaque `color` (notch missing) | Material 3, translucent `color` (notch broken) | 
| --- | --- | --- |
| image | image | image |

## Expected results

Arguably, it could show the notch.

But the notch isn't in the Material 3 [spec](https://m3.material.io/components/bottom-app-bar/specs), so probably the best answer is that `BottomAppBar` should not accept a `shape` in Material 3.

What it definitely shouldn't do is cheerfully accept `shape` and have it not work.

## Code sample:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: Theme.of(context).copyWith(useMaterial3: true),
      home: Scaffold(
        floatingActionButton: FloatingActionButton(onPressed: () {}),
        floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
        bottomNavigationBar: BottomAppBar(
          color: const Color.fromRGBO(0, 100, 0, 1),
          // color: const Color.fromRGBO(0, 100, 0, 0.5), // <-- Try a translucent `color`
          shape: const CircularNotchedRectangle(),
          child: Row(children: [IconButton(onPressed: () {}, icon: const Icon(Icons.menu))])
        ),
      ),
    );
  }
}
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

No errors observed in the logs.

```
$ flutter analyze
Analyzing scratch...                                                    
No issues found! (ran in 1.2s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.9.0-13.0.pre.39, on macOS 13.0 22A380 darwin-x64, locale
    en-US)
    • Flutter version 3.9.0-13.0.pre.39 on channel main at
      /Users/chrisbobbe/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3fe5740153 (2 hours ago), 2023-03-22 11:58:57 -0700
    • Engine revision 5775c6b05f
    • Dart version 3.0.0 (build 3.0.0-348.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chrisbobbe/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/chrisbobbe/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • B10DA4B8-480B-4FE1-A651-4DFBE39ABF71 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     •
      macOS 13.0 22A380 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript •
      Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes #123283.
Fixes #122667.
Fixes #123064.

(EDITED for the current revision, following https://github.com/flutter/flutter/issues/123283#issuecomment-1481637735.)

The `BottomAppBar` implementation uses both a `Material` and a `PhysicalShape` because it needs them both in order to support the "notch" for a FAB in Material 2.

In the current version of the Material 3 support, it ends up putting a color and shadow on both of these, so that there are two color layers and two shadows. This gives wrong results when the color is translucent: #122667, #123064.

Also in Material 3, it doesn't work right if you ask for a notch, because the `Material` paints through the notch: #123283. (The Material 3 [spec](https://m3.material.io/components/bottom-app-bar/specs) doesn't allow for a notch in the bottom app bar, but we plan to support one anyway: https://github.com/flutter/flutter/issues/123283#issuecomment-1481637735.)

So, fix these bugs by making the `Material` transparent (and without overlay or shadow, using `MaterialType.transparency`), like we do in Material 2.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 1]
```diff
@@ -191,34 +208,38 @@ class _BottomAppBarState extends State<BottomAppBar> {
...
+      child = PhysicalShape(
+        clipper: clipper,
+        elevation: elevation,
+        shadowColor: shadowColor,
+        color: ElevationOverlay.applyOverlay(context, color, elevation),
+        clipBehavior: widget.clipBehavior,
+        child: Material(
+          key: materialKey,
+          type: MaterialType.transparency,
+          child: SafeArea(child: child),
```
Comment (chrisbobbe) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:237]: This is exactly like how this code was before Material 3 support was first added in #106525, except for the customizations added for padding in #115175 and for shadow color in #121406.

File: packages/flutter/test/material/bottom_app_bar_test.dart [hunk 2]
```diff
@@ -11,7 +11,88 @@ import 'package:flutter/material.dart';
 import 'package:flutter/rendering.dart';
 import 'package:flutter_test/flutter_test.dart';
 
+import '../rendering/mock_canvas.dart';
+
 void main() {
+  // Regression test for https://github.com/flutter/flutter/issues/123283
+  testWidgets('throws if `shape` requested in Material 3', (WidgetTester tester) async {
```
Comment (gnprice) [inline packages/flutter/test/material/bottom_app_bar_test.dart:18]: nit:
```suggestion
  testWidgets('throws if `shape` requested in Material 3', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/123283
```

and similarly below

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 3]
```diff
@@ -174,6 +189,8 @@ class _BottomAppBarState extends State<BottomAppBar> {
   Widget build(BuildContext context) {
     final ThemeData theme = Theme.of(context);
     final bool isMaterial3 = theme.useMaterial3;
+    assert(!isMaterial3 || widget.shape == null); // `shape` not accepted in Material 3
```
Comment (gnprice) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:192]: The information in the comment should go in an assertion message instead, so the developer sees it when they hit the assertion. For example:

```suggestion
    assert(!isMaterial3 || widget.shape == null,
      'The [BottomAppBar.shape] field is not permitted in Material 3.');
```

(Could also throw a `FlutterError` for a fancier error message, but this might be enough.)

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 4]
```diff
@@ -114,17 +117,29 @@ class BottomAppBar extends StatefulWidget {
...
   final NotchedShape? shape;
 
   /// {@macro flutter.material.Material.clipBehavior}
   ///
   /// Defaults to [Clip.none], and must not be null.
+  ///
+  /// Ignored if the ambient [ThemeData.useMaterial3] is true; the Material 3
+  /// spec defines the shape without a notch:
+  ///   https://m3.material.io/components/bottom-app-bar/specs#9d91e4a4-a6d9-4ad5-afad-430267ebb4e9
   final Clip clipBehavior;
```
Comment (gnprice) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:133]: Can this be simplified like so?

```suggestion
  ///
  /// Has no effect if there is no notch; see [shape].
  final Clip clipBehavior;
```

Similarly for [notchMargin].

(And if so, then that seems like a good docs improvement even before this PR's changes to the behavior of the code.)

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 5]
```diff
@@ -114,17 +117,29 @@ class BottomAppBar extends StatefulWidget {
   /// If this property is null then [BottomAppBarTheme.shape] of
   /// [ThemeData.bottomAppBarTheme] is used. If that's null then the shape will
   /// be rectangular with no notch.
+  ///
+  /// Ignored if the ambient [ThemeData.useMaterial3] is true; the Material 3
+  /// spec defines the shape without a notch:
+  ///   https://m3.material.io/components/bottom-app-bar/specs#9d91e4a4-a6d9-4ad5-afad-430267ebb4e9
   final NotchedShape? shape;
```
Comment (gnprice) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:124]: This isn't just ignored in that case, but rather not permitted, right? So for example:

```suggestion
  /// If the ambient [ThemeData.useMaterial3] is true,
  /// then there is never a notch, and this property must be null.
  /// (The Material 3 spec does not provide for a notch:
  /// <https://m3.material.io/components/bottom-app-bar/specs#9d91e4a4-a6d9-4ad5-afad-430267ebb4e9>.)
  final NotchedShape? shape;
```

**Review by gnprice — COMMENTED** [review]
Thanks for the fix! Generally this looks good.

File: packages/flutter/lib/src/material/bottom_app_bar.dart (hunk 3 above)
Comment (chrisbobbe) [reply packages/flutter/lib/src/material/bottom_app_bar.dart:192]: If throwing a `FlutterError`, would we want to do that in production too? AIUI [`assert`s only run in debug mode](https://docs.flutter.dev/testing/debugging#debug-mode-assertions).

**Comment by chrisbobbe** [comment]
Thanks for the review, @gnprice! Changes pushed; PTAL. 🙂

File: packages/flutter/test/material/bottom_app_bar_test.dart [hunk 6]
```diff
@@ -29,8 +29,8 @@ void main() {
     expect(tester.takeException(), isAssertionError);
   });
 
-  // Regression test for https://github.com/flutter/flutter/issues/123064
   testWidgets('shadow effect is not doubled', (WidgetTester tester) async {
+  // Regression test for https://github.com/flutter/flutter/issues/123064
```
Comment (gnprice) [inline packages/flutter/test/material/bottom_app_bar_test.dart]: nit: indentation (here and below)
```suggestion
  testWidgets('shadow effect is not doubled', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/123064
```

**Review by gnprice — APPROVED** [review]
LGTM! One nit.

File: packages/flutter/lib/src/material/bottom_app_bar.dart (hunk 3 above)
Comment (gnprice) [reply packages/flutter/lib/src/material/bottom_app_bar.dart]: No, the check and the throw would both go inside an `assert`. For example, here's [State.context]:
```dart
  BuildContext get context {
    assert(() {
      if (_element == null) {
        throw FlutterError(
          'This widget has been unmounted, so the State no longer has a context (and should be considered defunct). \n'
          'Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.',
        );
      }
      return true;
    }());
    return _element!;
  }
```

**Comment by chrisbobbe** [comment]
Thanks for the review! Fixed pushed.

**Comment by chrisbobbe** [comment]
I'm reworking this following @HansMuller's comment at https://github.com/flutter/flutter/issues/123283#issuecomment-1481637735:

> [T]he notch should still work with `useMaterial3: true`.

**Comment by justinmc** [comment]
Sounds good, I'm happy to give a secondary review when this is back out of draft mode.

File: packages/flutter/test/material/bottom_app_bar_test.dart [hunk 7]
```diff
@@ -218,19 +284,18 @@ void main() {
                 ),
                 bottomNavigationBar: BottomAppBar(
                   color: Color(0xff0000ff),
+                  surfaceTintColor: Colors.transparent,
```
Comment (chrisbobbe) [inline packages/flutter/test/material/bottom_app_bar_test.dart:287]: I add this `surfaceTintColor: Colors.transparent` in a few tests of the `BottomAppBar`'s base color, when the by-default surface tint color would make that more complicated.

<details>

<summary>The doc on `surfaceTintColor` seems wrong:</summary>

https://api.flutter.dev/flutter/material/BottomAppBar/surfaceTintColor.html
> If this is null, no overlay will be applied.

https://github.com/flutter/flutter/blob/5054b6e51/packages/flutter/lib/src/material/bottom_app_bar.dart#L193
```dart
final Color surfaceTintColor = widget.surfaceTintColor ?? babTheme.surfaceTintColor ?? defaults.surfaceTintColor!;
```

If it's null, then an overlay _will_ apply: one from the ambient `BottomAppBarTheme`, else from a hard-coded default for M2 or M3.

</details>

**Comment by chrisbobbe** [comment]
This is ready for another review; I've added commits following @HansMuller's comment at https://github.com/flutter/flutter/issues/123283#issuecomment-1481637735:

> [T]he notch should still work with `useMaterial3: true`.

The notch now does work in Material 3 (🎉), except that the default FAB shape doesn't have a `NotchedShape` written for it yet. That would be good to do.

| Before (`color` doubled; notch only in one layer) | After (`color` correct) |
| --- | --- |
| image | image |

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 8]
```diff
@@ -201,11 +203,7 @@ class _BottomAppBarState extends State<BottomAppBar> {
 
     final Material material = Material(
       key: materialKey,
-      type: isMaterial3 ? MaterialType.canvas : MaterialType.transparency,
-      elevation: elevation,
-      color: isMaterial3 ? effectiveColor : null,
-      surfaceTintColor: surfaceTintColor,
-      shadowColor: shadowColor,
+      type: MaterialType.transparency,
       child: SafeArea(child: child),
```
Comment (gnprice) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:207]: I like how much simpler this gets!

**Review by gnprice — APPROVED** [review]
Cool, thanks for the revision. The new version LGTM.

**Comment by gnprice** [comment]
Looks like you'll need to rebase:
image

(I think a merge would probably also do it.)

**Comment by chrisbobbe** [comment]
Thanks for the review!

> (I think a merge would probably also do it.)

Done.

**Comment by gnprice** [comment]
Google testing failed. This is likely the same failures @justinmc mentioned above:

> By the way, the Google testing failures look like there's a small pixel difference at the right edge of the BottomAppBar in some image diff tests. Likely it's intended, but I'll take another look after the PR is updated.

Customer testing also failed, in a way unrelated to this PR: #123385

**Comment by justinmc** [comment]
@chrisbobbe Can you merge master into this PR?  That will fix the customer tests and update the Google tests so I can take a look.

**Comment by chrisbobbe** [comment]
Sure! Done.

**Comment by justinmc** [comment]
Thanks, looks like the customer tests are fixed.  I'll check on the Google tests next week.

**Comment by justinmc** [comment]
The Google test failure looks unrelated... Can you try pushing another merge commit?  Sorry for all the headache with this.

**Comment by chrisbobbe** [comment]
Sure, no problem! Done.

**Comment by chrisbobbe** [comment]
Hmm, Google testing is still showing as "pending" after 7+ hours. Could be #123289?

This time I'm going to try and see if I can update the branch without leaving GitHub's UI. There's a helpful-looking "Update branch" button that I'm going to click now. (If that does something wrong, I can always reset the branch back to b084982, my merge commit from earlier today.)

**Comment by HansMuller** [comment]
@XilaiZhang - apparently this PR has failed "Google Testng" however the details link doesn't reveal anything: "There is no unmerged PR.". I tried the "Test a PR" button to start another test and that failed with:

Screenshot 2023-04-04 at 8 47 48 AM

How can we move the process along?

**Comment by XilaiZhang** [comment]
temp workaround: the test failures are at test/521647510 and the cl is cl/521647510

Thanks for reporting the issue! will keep track of it in b/260764527

**Comment by HansMuller** [comment]
The Google testing failures don't appear to have anything to do with this PR. Will try updating the branch...

File: packages/flutter/test/material/bottom_app_bar_test.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/test/material/bottom_app_bar_test.dart:288]: Could you file a new issue about the docs being wrong?

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I think that Google testing is broken right now, so we'll have to try pushing another merge commit in a day or so when it's fixed.

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 9]
```diff
@@ -33,7 +33,8 @@ import 'theme.dart';
 /// {@end-tool}
 ///
 /// {@tool dartpad}
-/// This example shows the [BottomAppBar], which can be configured to have a notch using the
+/// This example shows the [BottomAppBar], which (in Material 2)
```
[the remark this answers is not in the document]
Comment (chrisbobbe) [reply packages/flutter/lib/src/material/bottom_app_bar.dart]: Ah, this is already addressed in this revision (I suspect your review-draft crossed with my sending that new revision). I've updated the PR description to match this revision. 🙂

File: packages/flutter/test/material/bottom_app_bar_test.dart (hunk 7 above)
Comment (chrisbobbe) [reply packages/flutter/test/material/bottom_app_bar_test.dart:288]: Sure, I'll aim to do that today.

File: packages/flutter/lib/src/material/bottom_app_bar.dart (hunk 9 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/bottom_app_bar.dart]: Thanks, yeah this review was messed up somehow...

File: packages/flutter/test/material/bottom_app_bar_test.dart (hunk 7 above)
Comment (chrisbobbe) [reply packages/flutter/test/material/bottom_app_bar_test.dart:288]: #124535

**Comment by chrisbobbe** [comment]
Thanks for the review!

> I think that Google testing is broken right now, so we'll have to try pushing another merge commit in a day or so when it's fixed.

Sure, I'll try that now.

**Comment by justinmc** [comment]
Thanks for pushing the merge commit.  It looks like there are real Google test failures, but they are just nearly invisible image diffs due to the changes here.  I've accepted the changes and should be able to merge this soon.

**Comment by gnprice** [comment]
Thanks @justinmc and everyone for your help in taking care of Google testing!

**Comment by chrisbobbe** [comment]
Yeah, thanks all! 🎉
