### PR TITLE
Fix an animation issue when dragging the first item of a reversed list onto the starting position.

### LINKED ISSUE #84625: ReorderableListView reverse bug
I have to align the listview from right to left, but the reverse feature of the ReorderableListView looks not that right?

code:
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {

  late List<Widget> items;

  @override
  void initState() {
    items = List.generate(3, (index) => Container(
      key: UniqueKey(),
      margin: EdgeInsets.all(10),
      padding: EdgeInsets.all(20),
      color: Colors.lightBlue,
      child: Text((index + 1).toString()),
    ));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Align(
          alignment: Alignment.centerRight,
          child: SizedBox(
             height: 80,
            child: ReorderableListView(
              reverse: true,
              physics: AlwaysScrollableScrollPhysics( parent: BouncingScrollPhysics() ),
              children: items.reversed.toList(),
              scrollDirection: Axis.horizontal,
              onReorder: (oldIndex, newIndex) {
                setState(() {
                  oldIndex = items.length - oldIndex - 1;
                  newIndex = items.length - newIndex;
                  items.insert(newIndex - (oldIndex < newIndex ? 1 : 0), items.removeAt(oldIndex));
                });
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

If I just reorder it normally, it looks fine.
fine

but if I put that object back to the same place, the animation will look weird...
bug

### PR DESCRIPTION
**Pull request by darrenaustin**
Fixes #84625

The problem here is that if the list is reversed and the first item is dragged off the edge of the screen it would animation from one list position greater than it should have leading to a weird jumping animation. This PR fixes this edge case so it should animate properly.

I added a test case to ensure this doesn't break again in the future.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -587,37 +630,34 @@ void main() {
   });
 }
 
-class TestList extends StatefulWidget {
+class TestList extends StatelessWidget {
```
Comment (HansMuller) [inline packages/flutter/test/widgets/reorderable_list_test.dart:633]: Making TestList stateless because it was never needed in the first place?

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/reorderable_list_test.dart (hunk 1 above)
Comment (darrenaustin) [reply packages/flutter/test/widgets/reorderable_list_test.dart:633]: As near as I could tell, it wasn't. There was no internal state kept and all the tests passed after making it stateless so I thought it would be better to just keep it simpler.

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 2]
```diff
@@ -673,7 +673,11 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
     setState(() {
       if (_insertIndex! < widget.itemCount - 1) {
         // Find the location of the item we want to insert before
-        _finalDropPosition = _itemOffsetAt(_insertIndex!);
+        if (_reverse) {
```
[the remark this answers is not in the document]
Comment (darrenaustin) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: Good idea. I usually go for conciseness, so I am not sure how I missed that. Thanks.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
