### PR TITLE
Fix initial scroll of TabBar in release mode

### LINKED ISSUE #10531: TabBars animate in in --release builds but not --debug builds
@Hixie says this is because we size a 0x0 in release builds, but not --debug builds.

This is causing bad behavior in Posse's latest app.  FYI @HansMuller

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/10531.

In release mode the app is often asked to layout before the engine has initialized to the point where the size of the screen is known. In that case the app is built and laid out with 0x0 constraints and then later with the screen's actual size. This causes the Viewport around a scrollable TaBBar to change dimension from 0.0 to the actual dimension with known screen size. The current `ScrollPosition` of the Viewport is adjusted to react to the dimension change by calling `ScrollPosition.applyViewportDimension`, which is followed by a call to `ScrollPosition.applyContentDimensions` as per API contract. The latter does the heavy lifting here and calls `applyNewDimension` on the current scroll activity (in this case an IdleScrollActivity), which responds by going ballistic to adjust the scroll position for the new dimensions. This is what people have been seeing as strange scroll activity when they launch their app.

Turns out, we already had a special case in the `_TabBarScrollPosition` to not trigger a ballistic scroll when the viewport dimension is set for the very first time. This PR extends this to also prevent ballistic behavior if the viewport dimensions change from zero to non-zero for the first time to fix the bug.

### CODE REVIEW

**Comment by goderbauer** [comment]
Tests for this are WIP.

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -476,10 +476,21 @@ class _TabBarScrollPosition extends ScrollPositionWithSingleContext {
 
   final _TabBarState tabBar;
 
+  bool _hadNonZeroDimension = false;
+
   @override
   bool applyContentDimensions(double minScrollExtent, double maxScrollExtent) {
     bool result = true;
-    if (pixels == null) {
+    if (!_hadNonZeroDimension) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: This is good. I found it slightly difficult to read because the initial value of _hadNonZeroDimension seemed to guess the future and `!_hadNonZeroDimension` required some unpacking. 

Here's another way to encode this:
```
  bool _initialViewportDimensionWasZero;

  if (_initialViewportDimensionWasZero != true) {
      // If the viewport never had a non-zero dimension, we just want to jump
      // ...
      assert(viewportDimension != null);
      _initialViewportDimensionWasZero = viewportDimension == 0.0;
      ...
  }
```

If you don't find this clearer, I have no problem with leaving the code as it is. Just a thought.

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/tabs.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/tabs.dart]: Changed it as per your suggestion.
