### PR TITLE
[ios][pv]fully revert the UIScreen.main deprecated API change

### LINKED ISSUE #165648: [Google3 Bug]: Fatal Exception: CALayer position contains NaN: [nan inf]. Layer: <CALayer:0x#; position = CGPoint (# #)…-ad8a0f16
### Help us understand the severity of this issue

- [x] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [ ] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

We are observing high crash rates ~12000+ in GPay app IOS.
Couldn't reproduce the actual steps but from the stack trace most likely culprit for this is https://github.com/flutter/flutter/pull/162785

Related bug b/404894149

### Expected results

Crash should not be there

### Actual results

Crashes happening

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
0x000000019aaa65fc (CoreFoundation + 0x0002d5fc)	__exceptionPreprocess
0x0000000198021240 (libobjc.A.dylib + 0x00031240)	objc_exception_throw
0x000000019abf36dc (CoreFoundation + 0x0017a6dc)	+[NSException raise:format:]
0x000000019c56ab68 (QuartzCore + 0x00019b68)	CA::Layer::set_position(CA::Vec2<double> const&, bool)
0x000000019c56aaa0 (QuartzCore + 0x00019aa0)	-[CALayer setPosition:]
0x000000019c56a684 (QuartzCore + 0x00019684)	-[CALayer setFrame:]
0x000000019d2b4318 (UIKitCore + 0x00018318)	-[UIView _backing_setFrame:]
0x000000019d2b3040 (UIKitCore + 0x00017040)	-[UIView(Geometry) setFrame:]
0x0000000103e4d09c (Flutter - FlutterPlatformViewsController.mm: 659)	-[FlutterPlatformViewsController compositeView:withParams:]
0x0000000103e5021c (Flutter - FlutterPlatformViewsController.mm: 857)	-[FlutterPlatformViewsController performSubmit:currentCompositionParams:viewsToRecomposite:compositionOrder:unusedLayers:surfaceFrames:]
0x0000000103eaa370 (Flutter - function.h: 512)	fml::MessageLoopImpl::FlushTasks(fml::FlushType)
0x0000000103ead8ec (Flutter - message_loop_impl.cc: 139)	fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
0x000000019ab69298 (CoreFoundation + 0x000f0298)	__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
0x000000019ab68f3c (CoreFoundation + 0x000eff3c)	__CFRunLoopDoTimer
0x000000019ab68a90 (CoreFoundation + 0x000efa90)	__CFRunLoopDoTimers
0x000000019aaef130 (CoreFoundation + 0x00076130)	__CFRunLoopRun
0x000000019ab41280 (CoreFoundation + 0x000c8280)	CFRunLoopRunSpecific
0x00000001e7db14bc (GraphicsServices + 0x000014bc)	GSEventRunModal
0x000000019d68a670 (UIKitCore + 0x003ee670)	-[UIApplication _run]
0x000000019d2b0e84 (UIKitCore + 0x00014e84)	UIApplicationMain
0x0000000100009580 (ios_prod_global - main.m: 82)	main
0x00000001c0d9dde4 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by hellohuanlin**
This PR fully reverts https://github.com/flutter/flutter/pull/162785

Due to crash from an internal customer

Fixes https://github.com/flutter/flutter/issues/165648

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/overlay_layer_pool.mm [hunk 1]
```diff
@@ -78,8 +69,6 @@
   std::unique_ptr<IOSSurface> ios_surface = IOSSurface::Create(ios_context, ca_layer);
   std::unique_ptr<Surface> surface = ios_surface->CreateGPUSurface();
 
-  layer = std::make_shared<OverlayLayer>(overlay_view, overlay_view_wrapper, std::move(ios_surface),
-                                         std::move(surface));
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/overlay_layer_pool.mm:82]: oops reverting

**Review by jmagman — APPROVED** [review]

**Comment by jmagman** [comment]
cc @dkyurtov
