### PR TITLE
[flutter] Allow hot reload replacements of Stateless/Stateful Widget

### LINKED ISSUE #9811: Detect changes to StatelessWidget/StatefulWidget base class in hot reload
## Steps to Reproduce

Make a class that extends `StatelessWidget`.
flutter run
Change your class to extend `StatefulWidget`
Hot-reload

Result: Assertion failure in `StatelessElement.widget` (or `StatefulElement.update` if you're going the other direction). Hot-restarting fixes the issue.

Suggestion: We should detect this case and show a helpful error message that suggests hot-restarting, or ideally just rebuild the parts of the app that need to be rebuilt.

/cc @Hixie @jason-simmons @sethladd 
Related bugs: #9771 #9761

## Logs

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _ModalScopeStatus(active):
type 'MyHomePage' is not a subtype of type 'StatelessWidget' of 'function result' where
The following assertion was thrown building _ModalScopeStatus(active):
  MyHomePage is from
type 'MyHomePage' is not a subtype of type 'StatelessWidget' of 'function result' where
  /Users/jackson/Library/Developer/CoreSimulator/Devices/5F90A4C3-6F80-446A-88CB-5394635BF8EF/data/Containers/Data/Application/03A8AB58-F47E-454A-8742-818E868A855D/tmp/scope_exampleCOE3SC/scope_example/lib/main.dart
  MyHomePage is from
  StatelessWidget is from package:flutter/src/widgets/framework.dart
  /Users/jackson/Library/Developer/CoreSimulator/Devices/5F90A4C3-6F80-446A-88CB-5394635BF8EF/data/Containers/Data/Application/03A8AB58-F47E-454A-8742-818E868A855D/tmp/scope_exampleCOE3SC/scope_example/lib/main.dart
  StatelessWidget is from package:flutter/src/widgets/framework.dart
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
  https://github.com/flutter/flutter/issues/new
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      StatelessElement.widget (package:flutter/src/widgets/framework.dart:3196:39)
#1      Element.updateChild (package:flutter/src/widgets/framework.dart:2290:17)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#4      ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#32     StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#32     StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#50     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3818:32)
#50     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#57     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4200:17)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#59     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3818:32)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#57     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4200:17)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#59     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#89     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#97     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#89     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#107    StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#97     ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4092:14)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#123    ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#127    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#107    StatelessElement.update (package:flutter/src/widgets/framework.dart:3206:5)
#131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1898:33)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#132    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:360:20)
#133    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#134    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685:15)
#135    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633:9)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#136    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:247:20)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#138    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#139    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#140    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
(elided one frame from package dart:async-patch)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
════════════════════════════════════════════════════════════════════════════════════════════════════
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#123    ProxyElement.update (package:flutter/src/widgets/framework.dart:3392:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#127    StatefulElement.update (package:flutter/src/widgets/framework.dart:3281:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2298:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
#131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1898:33)
#132    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:360:20)
#133    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
#134    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685:15)
#135    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633:9)
#136    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:247:20)
#138    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#139    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#140    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
(elided one frame from package dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: type 'MyHomePage' is not a subtype of type 'StatelessWidget' of 'function result' where
Another exception was thrown: type 'MyHomePage' is not a subtype of type 'StatelessWidget' of 'function result' where
Another exception was thrown: type 'MyHomePage' is not a subtype of type 'StatelessWidget' of 'function result' where
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4112 pos 12: 'renderObject.child == child': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1896 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
Reloaded 1 of 427 libraries in 788ms.
```

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 1d726bbeb5 (2 days ago), 2017-05-02 12:53:03 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    ✗ libimobiledevice is incompatible with the installed Xcode version. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    •               • 14710ae2e8497590643751c5532d907ed1ff2eed • ios • iOS  ()
    • iPhone 7 Plus • 5F90A4C3-6F80-446A-88CB-5394635BF8EF     • ios • iOS 10.3 (simulator)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/9811

When the type of a widget is changed between Stateful and Stateless via hot reload, the element tree will end up in a partially invalid state. That is, if the widget was a StatefulWidget and is now a StatelessWidget, then the element tree currently contains a StatefulElement that is incorrectly referencing a StatelessWidget (and likewise with StatelessElement).

To avoid crashing due to type errors, we need to gently guide the invalid element out of the tree. To do so, we ensure that the `canUpdate` condition returns false which prevents us from trying to update the existing element incorrectly.

For the case where the widget becomes Stateful, we also need to avoid accessing `StatelessElement.widget` as the cast on the getter will cause a type error to be thrown. Here we avoid that by short-circuiting  the `Widget.canUpdate` check once `canUpdate` is false. There are three additional places where `Element.widget` is accessed that may throw a CastError. These are avoided by `_debugSafeVerifyNonNullWidget` and `_safeRetrieveWidgetKey`.

This can be tested via a devicelab test that performs these reload transformations and verifies that they keep working.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Friendly ping @goderbauer

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -2729,6 +2729,42 @@ class BuildOwner {
...
+// If a StatelessWidget has been transformed into a stateful one, then accessing
+// `StatelessElement.widget` will throw a `CastError`. Instead, we access the
+// private member `Element._widget`. For a subclass of Element this field will
+// be defined and properly calling the element lifecycle methods will populate
+// it as normal. For implementations of Element, the assertion will never be
+// called.
+
+// Verify that an Element's widget is non-null.
+bool _debugSafeVerifyNonNullWidget(Element element) {
+  if (element is StatelessElement) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: Why special-casing StatelessElement? Any reason not to always use _widget?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/framework.dart]: Same below.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -2729,6 +2729,42 @@ class BuildOwner {
...
+    }
+    return true;
+  }());
+  if (kDebugMode) {
+    return key;
+  }
+  return element.widget.key;
+}
+
+///
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: ?

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/framework.dart]: If we can just use _widget, we also wouldn't need these helpers keeping the code slightly simpler?

File: packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart [hunk 3]
```diff
@@ -0,0 +1,54 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:async';
+import 'dart:io' as io; // ignore: dart_io_import
```
Comment (goderbauer) [inline packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart]: nit: ignores need a comment explaining why this is ignored, see style guide.

File: packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+    // switch to stateless.
+    _project.toggleState();
+    await _flutter.hotReload();
+
+    final String logs = stdout.toString();
+
+    expect(logs, contains('STATELESS'));
+    expect(logs, contains('STATEFUL'));
+    await subscription.cancel();
+  }, skip: io.Platform.isWindows);
```
Comment (goderbauer) [inline packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart]: why doesn't it work on Windows?

File: packages/flutter_tools/test/integration.shard/test_data/stateless_stateful_project.dart [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+    @override
+    Widget build(BuildContext context) {
+      print('STATEFUL');
+      return Container();
+    }
+  }
+  ''';
+
+  void toggleState() {
+    final String main = globals.fs.file(globals.fs.path.join(dir.path, 'lib', 'main.dart')).readAsStringSync();
```
Comment (goderbauer) [inline packages/flutter_tools/test/integration.shard/test_data/stateless_stateful_project.dart]: I think this test would be easier to read and reason about if there was a getCode(bool stateful) method and depending on the bool it would return code with a stateless or stateful child. toggleState would then call this method with inverted stateful value and write that thing out instead of doing this crazy replacement.

**Review by goderbauer — COMMENTED** [review]
Some initial comments. I do want to play with this a little after my meeting to see how it behaves in practice and if I can make it break :P

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: I created the methods to centralize documentation, but I could inline them all

File: packages/flutter/lib/src/widgets/framework.dart [hunk 6]
```diff
@@ -2729,6 +2729,42 @@ class BuildOwner {
   }
 }
 
+// Methods to handle hot reloads replacements of Stateless/Stateful Widget types.
+
+// If a StatelessWidget has been transformed into a stateful one, then accessing
+// `StatelessElement.widget` will throw a `CastError`. Instead, we access the
+// private member `Element._widget`. For a subclass of Element this field will
+// be defined and properly calling the element lifecycle methods will populate
+// it as normal. For implementations of Element, the assertion will never be
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: With the removal of the specific methods, I've removed this comment as well

File: packages/flutter/lib/src/widgets/framework.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: Removed

File: packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart]: I'm going to try to fix the window issue

File: packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/integration.shard/stateless_stateful_hot_reload_test.dart]: Lack of resolution of the filesystem timestamps

File: packages/flutter_tools/test/integration.shard/test_data/stateless_stateful_project.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/integration.shard/test_data/stateless_stateful_project.dart]: Updated

File: packages/flutter/lib/src/widgets/framework.dart [hunk 7]
```diff
@@ -3462,12 +3483,19 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
   @mustCallSuper
   void unmount() {
     assert(_debugLifecycleState == _ElementLifecycle.inactive);
-    assert(widget != null);
+    assert(_widget != null); // Use the private property to avoid a CastError during hot reload.
     assert(depth != null);
     assert(!_active);
-    final Key key = widget.key;
+    Key key;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: Can this just be:

```dart
final Key key = _widget.key;
```

Any reason we would want to go through the regular getter here?

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: I suppose the only thing we're doing for is checking for global keys so it seems safe.

**Comment by goderbauer** [comment]
I played around a little bit in Flutter Gallery with this and couldn't get it to break. Seems like a nice way to remove one of the limitations that developers often run into with hot reload.

@Hixie What do you think about this?

**Comment by Hixie** [comment]
Seems reasonable. There's other transitions that will still break (e.g. RenderObjectWidget to StatelessWidget, etc), so I can imagine doing this in a more general way, but stateless to stateful is probably the most common case.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 8]
```diff
@@ -3070,12 +3070,33 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
...
+      // element out of the tree. To do so, we ensure that the `canUpdate` condition
+      // returns false which prevents us from trying to update the existing element
+      // incorrectly.
+      //
+      // For the case where the widget becomes Stateful, we also need to avoid
+      // accessing `StatelessElement.widget` as the cast on the getter will
+      // cause a type error to be thrown. Here we avoid that by short-circuiting
+      // the `Widget.canUpdate` check once `canUpdate` is false.
+      assert(() {
+        canUpdate = !((child is StatelessElement && newWidget is StatefulWidget) ||
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: let's call this "hasSameSuperclass" or something, so we don't confuse it with the Widget.canUpdate method.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 9]
```diff
@@ -3070,12 +3070,33 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
...
+                      (child is StatefulElement && newWidget is StatelessWidget));
+        return true;
+      }());
+      if (canUpdate && child.widget == newWidget) {
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: maybe wrap both if statements in a single if statement that checks this? rather than having the condition in both?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 10]
```diff
@@ -3070,12 +3070,33 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
...
+      // returns false which prevents us from trying to update the existing element
+      // incorrectly.
+      //
+      // For the case where the widget becomes Stateful, we also need to avoid
+      // accessing `StatelessElement.widget` as the cast on the getter will
+      // cause a type error to be thrown. Here we avoid that by short-circuiting
+      // the `Widget.canUpdate` check once `canUpdate` is false.
+      assert(() {
+        canUpdate = !((child is StatelessElement && newWidget is StatefulWidget) ||
+                      (child is StatefulElement && newWidget is StatelessWidget));
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: since all the interesting logic is in debug-mode only code, you could just go crazy and do something like:

```dart
int oldWidgetClass = child is StatelessElement ? 1 :
                     child is StatefulElement ? 2 :
                     child is SingleChildRenderObjectElement ? 3 :
                     child is InheritedElement ? 4 :
                     0;
int newWidgetClass = newWidget is StatelessElement ? 1 :
                     newWidget is StatefulElement ? 2 :
                     newWidget is SingleChildRenderObjectElement ? 3 :
                     newWidget is InheritedElement ? 4 :
                     0;
hasSameSuperlass = oldWidgetClass == newWidgetClass;
```

(but with all the relevant subclasses. And maybe put that common superclass-identifying logic in a private method on Widget or something.)

File: packages/flutter/lib/src/widgets/framework.dart [hunk 11]
```diff
@@ -3070,12 +3070,33 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
       return null;
     }
     if (child != null) {
-      if (child.widget == newWidget) {
+      bool canUpdate = true;
+      // When the type of a widget is changed between Stateful and Stateless via
+      // hot reload, the element tree will end up in a partially invalid state.
+      // That is, if the widget was a StatefulWidget and is now a StatelessWidget,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/framework.dart]: Does that mean when a class change its superclass, the runtimeType is still the same? That feels like a compiler bug?

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: A class can only change its type like this via hot reload. It isn't that the runtimeType is still the same, its that they're both different

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: ... differently the same

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/framework.dart]: I see, thanks for explaining.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 10 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: I refactored both into static helpers on the Widget and Element subclasses. It would be nice if we had a generic sort of mapping between an Element subtype and the particular Widget subtype it contains, but that doesn't seem possible based on the fairly open-ended nature of the APIs today.

Given that we've only ever had this reported as an error for stateless/stateful, I've only included those and the suggestion addition of SingleChild/Inherited

File: packages/flutter/lib/src/widgets/framework.dart (hunk 9 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: Done

File: packages/flutter/lib/src/widgets/framework.dart (hunk 8 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: Done

File: packages/flutter/lib/src/widgets/framework.dart [hunk 12]
```diff
@@ -473,6 +473,18 @@ abstract class Widget extends DiagnosticableTree {
...
+  // Return a numeric encoding of the specific `Widget` concrete subtype.
+  // This is used to determine if a hot reload modified the type hierarchy of
+  // a mounted element. The encoding of each `Widget` must match the corresponding
+  // `Element` encoding in `Element._debugConcreteSubtype`.
+  static int _debugConcreteSubtype(Widget widget) {
+    return widget is StatelessWidget ? 1 :
+           widget is StatefulWidget ? 2 :
+           widget is SingleChildRenderObjectWidget ? 3 :
+           widget is InheritedWidget? 4 :
+           0;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: we should just add all the common subclasses, sorry that wasn't clear in my earlier comment. These:
StatefulElement, StatelessElement, InheritedModelElement, InheritedElement, ParentDataElement, ProxyElement, LeafRenderObjectElement, RootRenderObjectElement, SingleChildRenderObjectElement, MultiChildRenderObjectElement, RenderObjectElement. (In that order, since some are superclasses of each other.)

File: packages/flutter_tools/test/integration.shard/test_utils.dart [hunk 13]
```diff
@@ -22,7 +22,8 @@ Directory createResolvedTempDirectorySync(String prefix) {
 void writeFile(String path, String content) {
   globals.fs.file(path)
     ..createSync(recursive: true)
-    ..writeAsStringSync(content);
+    ..writeAsStringSync(content)
+    ..setLastModifiedSync(DateTime.now().add(const Duration(seconds: 10)));
```
Comment (Hixie) [inline packages/flutter_tools/test/integration.shard/test_utils.dart]: avoid `DateTime.now()` in tests, it's a source of flakes. The memory file system has its own clock.

Comment (jonahwilliams) [reply packages/flutter_tools/test/integration.shard/test_utils.dart]: These tests run on the flutter_tester and require the real filesystem. Unfortunately all of them are slightly flaky on Windows, and my current theory is that we don't have enough timestamp resolution there.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 12 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: I've updated with the types here, save for RootRenderObjectElement which uses a regular RenderObjectWidget as its configuration

File: packages/flutter/lib/src/widgets/framework.dart [hunk 14]
```diff
@@ -473,6 +474,24 @@ abstract class Widget extends DiagnosticableTree {
     return oldWidget.runtimeType == newWidget.runtimeType
         && oldWidget.key == newWidget.key;
   }
+
+  // Return a numeric encoding of the specific `Widget` concrete subtype.
+  // This is used to determine if a hot reload modified the type hierarchy of
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: nit: this is used in [Element.updateChild] to determine...

File: packages/flutter/lib/src/widgets/framework.dart [hunk 15]
```diff
@@ -2838,6 +2857,24 @@ abstract class Element extends DiagnosticableTree implements BuildContext {
     return 0;
   }
 
+  // Return a numeric encoding of the specific `Element` concrete subtype.
+  // This is used to determine if a hot reload modified the type hierarchy of
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: nit: this is used in [Element.updateChild] to determine...

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
When you submit this can you also have the website updated to no longer claim that this is a limitation of hot reload.

**Comment by jonahwilliams** [comment]
Yes, we'll likely need to announce something and leave some hints for older versions like "If you're using Flutter pre X.Y.Z then...."

File: packages/flutter/lib/src/widgets/framework.dart (hunk 14 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: Done, but i used backticks since this isn't a dartdoc

File: packages/flutter/lib/src/widgets/framework.dart (hunk 15 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/framework.dart]: Done
