### PR TITLE
Fix gen-l10n format: true so that it applies to when it gets called via build target

### LINKED ISSUE #120530: [l10n] `flutter run` breaks formatting on localization files
## Steps to Reproduce

Having `format: true` in `l10n.yaml`:

1. `flutter gen-l10n`
2. `flutter run -d chrome`

**Expected results:** Localization files not modified after running `flutter run`

**Actual results:**
```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   lib/core/l10n/app_localizations.dart
	modified:   lib/core/l10n/app_localizations_es.dart
```

<details>
  <summary>Logs</summary>

```
$ fvm flutter doctor -v                        
[!] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-x64, locale en-UY)
    • Flutter version 3.7.3 on channel stable at /Users/demoda/fvm/versions/3.7.3
    ! Warning: `dart` on your path resolves to /Users/demoda/homebrew/Cellar/dart/2.18.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/demoda/fvm/versions/3.7.3. Consider adding /Users/demoda/fvm/versions/3.7.3/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (3 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/demoda/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Users/demoda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/demoda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/demoda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by thkim1011**
This PR fixes `generateLocalizations` so that it formats even when run via `flutter run`. It does so by moving the code for formatting into `generateLocalizations` which is called in multiple places including the `gen-l10n` command and the `GenerateLocalizationsTarget` build target.

Fixes https://github.com/flutter/flutter/issues/120530.

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 1]
```diff
@@ -71,6 +75,28 @@ LocalizationsGenerator generateLocalizations({
...
+      formatFileList.remove(untranslatedMessagesFile.absolute.path);
+    }
+    if (formatFileList.isEmpty) {
+      return generator;
+    }
+    final String dartBinary = artifacts.getArtifactPath(Artifact.engineDartBinary);
+    final List<String> command = <String>[dartBinary, 'format', ...formatFileList];
+    final ProcessResult result = await processManager.run(command);
+    if (result.exitCode != 0) {
+      throwToolExit('Formatting failed: $result', exitCode: result.exitCode);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:96]: how about showing the stdout and stderr of the `ProcessResult`?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart:96]: If formatting fails, is this expected to be user error or a tool bug? Because `throwToolExit` is generally reserved for the former--if this is the latter, we should throw a `ProcessException` or some such.

File: packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart [hunk 2]
```diff
@@ -324,6 +326,53 @@ untranslated-messages-file: lib/l10n/untranslated.json
...
+    await buildTarget.build(environment);
+
+    final Directory outputDirectory = fileSystem.directory(fileSystem.path.join('.dart_tool', 'flutter_gen', 'gen_l10n'));
+    expect(outputDirectory.existsSync(), true);
+    expect(outputDirectory.childFile('app_localizations_en.dart').existsSync(), true);
+    expect(outputDirectory.childFile('app_localizations.dart').existsSync(), true);
+    expect(processManager, hasNoRemainingExpectations);
+  }, overrides: <Type, Generator>{
+    FileSystem: () => fileSystem,
+    ProcessManager: () => FakeProcessManager.any(),
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart:373]: does this ever get used? I'm guessing not? Can this whole test actually be called with `testWithoutContext()`?

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart (hunk 1 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart]: yeah, assuming that the `generateLocalizations` generates the files properly, `dart format` should run properly so this isn't a user error. I've changed it to a `ProcessException`. Let me know if you're ok with the format I used for the message.

File: packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart (hunk 2 above)
Comment (thkim1011) [reply packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart]: Nope, I switched it to a `testWithoutContext`.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 3]
```diff
@@ -71,6 +75,36 @@ LocalizationsGenerator generateLocalizations({
...
+    final List<String> command = <String>[dartBinary, 'format', ...formatFileList];
+    final ProcessResult result = await processManager.run(command);
+    if (result.exitCode != 0) {
+      throw ProcessException(
+        dartBinary,
+        command,
+        '''
+Dart format failed to run.
+${result.stdout}
+${result.stderr}''',
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:102]:
```suggestion
`dart format` failed with exit code ${result.exitCode}

stdout:\n${result.stdout}\n
stderr:\n${result.stderr}''',
```

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart]: made some minor textual suggestions, but otherwise lgtm

**Review by christopherfujino — APPROVED** [review]
LGTM with a nit suggestion about the exception message
