### PR TITLE
Call bringIntoView after RenderEditable updates on paste

### LINKED ISSUE #96658: Invalid TextField scroll offset change on paste from toolbar
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Copy the text from the first line and paste it at the end of the second line using toolbar

**Expected results:** TextField doesn't scroll as caret is already visible

**Actual results:** TextField scrolls

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'bringIntoView test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Copy & paste stuff below:'),
            Expanded(
              child: TextField(
                focusNode: FocusNode(),
                controller: TextEditingController(
                  text: 'Copy this whoooooollleeeeee line\nPaste it here using toolbar: \n' + ('.\n' * 50),
                ),
                maxLines: null,
                style: const TextStyle(fontSize: 36.0, color: Colors.black),
                cursorColor: Colors.grey,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
 % flutter doctor -v
[✓] Flutter (Channel master, 2.9.0-1.0.pre.363, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.363 at /Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e9a728667 (11 hours ago), 2022-01-14 09:40:11 +0800
    • Engine revision f121c1fe68
    • Dart version 2.17.0 (build 2.17.0-11.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jsmith/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by tgucio**
This PR ensures EditableText.bringIntoView() is called after the RenderEditable is updated with the new text value. This avoids incorrect scroll offset changes on paste.

Fixes #96658.

All relevants tests are passing:
```
% ../../bin/flutter test \
  test/widgets/editable_text_cursor_test.dart \
  test/widgets/editable_text_show_on_screen_test.dart \
  test/widgets/editable_text_shortcuts_tests.dart \
  test/widgets/editable_text_test.dart \
  test/cupertino/text_field_restoration_test.dart \
  test/cupertino/text_field_test.dart \
  test/cupertino/text_form_field_row_test.dart \
  test/cupertino/text_selection_test.dart \
  test/cupertino/text_selection_toolbar_button_test.dart \
  test/cupertino/text_selection_toolbar_test.dart \
  test/material/text_field_focus_test.dart \
  test/material/text_field_helper_text_test.dart \
  test/material/text_field_restoration_test.dart \
  test/material/text_field_splash_test.dart \
  test/material/text_field_test.dart \
  test/material/text_form_field_restoration_test.dart \
  test/material/text_form_field_test.dart \
  test/material/text_selection_test.dart \
  test/material/text_selection_toolbar_test.dart \
  test/material/text_selection_toolbar_text_button_test.dart \
  test/rendering/editable_gesture_test.dart \
  test/rendering/editable_test.dart \
  test/widgets/text_selection_test.dart \
  test/widgets/text_selection_toolbar_layout_delegate_test.dart

02:41 +1431: All tests passed!                 
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -10948,12 +10948,12 @@ void main() {
...
     // Paste
     await resetSelectionAndScrollOffset();
-    textSelectionDelegate.pasteText(SelectionChangedCause.keyboard);
+    await textSelectionDelegate.pasteText(SelectionChangedCause.keyboard);
     await tester.pump();
     expect(scrollController.offset, maxScrollExtent);
 
     await resetSelectionAndScrollOffset();
-    textSelectionDelegate.pasteText(SelectionChangedCause.toolbar);
+    await textSelectionDelegate.pasteText(SelectionChangedCause.toolbar);
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:10956]: Good call, these awaits probably should have been here.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -1688,7 +1688,10 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     Clipboard.setData(ClipboardData(text: selection.textInside(text)));
     _replaceText(ReplaceTextIntent(textEditingValue, '', selection, cause));
     if (cause == SelectionChangedCause.toolbar) {
-      bringIntoView(textEditingValue.selection.extent);
+      // Schedule a call to bringIntoView() after renderEditable updates.
+      SchedulerBinding.instance.addPostFrameCallback((_) {
+        bringIntoView(textEditingValue.selection.extent);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1693]: This problem where RenderEditable is out of date is a recurring problem.  I think using an addPostFrameCallback is the best option for now.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3083,10 +3089,20 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    final TextEditingValue newValue = intent.currentTextEditingValue.replaced(
+      intent.replacementRange,
+      intent.replacementText,
     );
+    userUpdateTextEditingValue(newValue, intent.cause);
+
+    // If there's no change in text and selection (e.g. when selecting and
+    // pasting identical text), the widget won't be rebuilt on value update.
+    // Handle this by calling _didChangeTextEditingValue() so caret and scroll
+    // updates can happen.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3102]: What corner case is this handling exactly?  Maybe consider adding a test that covers this (unless I misunderstand and the existing test does cover it).

**Review by justinmc — COMMENTED** [review]
One question about the `_didChangeTextEditingValue` case, but this approach looks good overall.  Thanks for fixing this!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (tgucio) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: Imagine you type "Lorem ipsum", select "ipsum", copy it and paste it into the same selection. Theoretically this is user input so you'd like to scroll, reset the caret animation, update selection/toolbar overlays etc. But 
`_didChangeTextEditingValue` won't be called because:
- it's a listener on `TextEditingController` which is a `ValueNotifier<TextEditingValue>`
- `TextEditingValue` equality operator will see the same value (text, selection, composing)
- `ValueNotifier`'s value setter won't call `notifyListeners()`

The interesting thing is that the "Selection will be scrolled into view with SelectionChangedCause" test in `editable_text_test.dart` already caught that although perhaps it wasn't intentional. What it does is to set a (0, 1) selection on each call to resetSelectionAndScrollOffset() and then do 2x cut and 2x paste. So you always end up pasting the same character that's already there.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (tgucio) [reply packages/flutter/lib/src/widgets/editable_text.dart:1693]: Indeed, it is a bit prone to more bugs. For `bringIntoView()` itself, I can see it's called from:
- text_selection.dart: `handleSelectAll()`, `_handleSelectionHandleChanged()`
- [material|cupertino] text_field.dart: `_handleSelectionChanged()`
-  selectable_text: `_handleSelectionChanged()`
- editable_text: `copySelection()`, `cutSelection()`, `pasteText()`, `selectAll()`, `_scrollToDocumentBoundary()`, `_updateSelection()`, `_expandSelection()`

The only two calls that may modify text contents/layout are cut and paste, handled by this PR.

BTW, another question (unrelated to this PR) is whether only calling `bringIntoView()` on SelectionChangedCause.toolbar is desired behaviour. This means that if one cuts/pastes in an area outside the viewport, we don't scroll there so the user doesn't see what's been done to the text.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: In the example you gave, wouldn't there be a selection change?

  1. "Lorem [ipsum]"
  2. Paste "ipsum"
  3. "Lorem ipsum|"

Comment (tgucio) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: Just tried in a TextField - no selection change on paste. In MS Word though, selection changes to collapsed on pasted text end.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:1693]: Glad that this PR will handle the problem here at least.

About scrolling on paste, I think you're right that it's incorrect.  I've created an issue: https://github.com/flutter/flutter/issues/98675.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Thanks for fixing this!  I'm looking into the collapse-after-paste thing.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: https://github.com/flutter/flutter/issues/98677

Comment (tgucio) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: Great, thanks for submitting the two issues!

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: Does it make sense to move this to the `pasteText` method?

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3102]: My intention was to avoid bundling side effects that are sometimes unexpected (such as this one) into generic operations like replacing text. It's a bit cleaner that way IMO especially when you are reading the code in `pasteText`, and you'll know immediately this is going to bring the new selection into view, instead of having to trace to `_replaceText` and find the "bring into view" logic there. But it's just a nit.
