### PR TITLE
Remove canTransitionFrom override from Material/CupertinoPageRoute

### LINKED ISSUE #44864: PageTransition is incorrect when first push a CupertinoPageRoute
When you push a CupertinoPageRoute for the first time, the page transition animation will lack the shrink animation. This problem only occurs when using CupertinoPageRoute.
     

Look carefully at the top text and you will find that the animation is a bit different.

You can reproduce this problem with this code.

``` dart
class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Title'),
        ),
        body: Center(
          child: FlatButton(
              onPressed: () {
                Navigator.of(context)
                    .push(CupertinoPageRoute(builder: (context) => Home()));
              },
              child: Text('push')),
        ));
  }
}

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.0)
[!] Connected device
    ! No devices available
```

### PR DESCRIPTION
**Pull request by Vadaski**
Overriding this method will cause the route transition animation to be lost, so remove this method

## Description
On iOS, a MaterialPageRoute should slide out with CupertinoPageTransition when a compatible PageRoute is pushed on top of it.  Overriding `canTransitionFrom` method will cause the route transition animation to be lost when a `CupertinoPageRoute` push on another route. So I remove this method from material/pages.dart and cupertino/pages.dart.

## Related Issues

Fixes #44864

## Tests

I added the following tests:

/packages/flutter/test/material/page_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by Vadaski** [comment]
Thanks @AlexVincent525 and @LongCatIsLooong for helping me complete my test case！

**Comment by Vadaski** [comment]
@googlebot I signed it!

**Comment by Vadaski** [comment]
@LongCatIsLooong /cc

File: packages/flutter/test/material/page_test.dart [hunk 1]
```diff
@@ -785,4 +786,34 @@ void main() {
     expect(homeTapCount, 2);
     expect(pageTapCount, 1);
   });
+
+  testWidgets(
+      'On iOS, a MaterialPageRoute should slide out with CupertinoPageTransition'
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/page_test.dart]: The indentation seems off, we use 2 spaces instead of 4. See: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#indent-multi-line-argument-and-parameter-lists-by-2-characters

**Review by LongCatIsLooong — APPROVED** [review]
LGTM with nits. Thank you very much for reporting and fixing this issue!

File: packages/flutter/test/material/page_test.dart (hunk 1 above)
Comment (Vadaski) [reply packages/flutter/test/material/page_test.dart]: fixed!

**Review by LongCatIsLooong — APPROVED** [review]
