### PR TITLE
Fix `Stepper` connector not being properly displayed

### LINKED ISSUE #160156: Vertical stepper line is interrupted by its content
### Steps to reproduce

1. Run code example from https://api.flutter.dev/flutter/material/Stepper-class.html on 3.27.0
2. Observe interrupted line

### Expected results

The line between the first and the second step is continuous

### Actual results

The line between the first and the second step is interrupted

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Stepper].

void main() => runApp(const StepperExampleApp());

class StepperExampleApp extends StatelessWidget {
  const StepperExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Stepper Sample')),
        body: const Center(
          child: StepperExample(),
        ),
      ),
    );
  }
}

class StepperExample extends StatefulWidget {
  const StepperExample({super.key});

  @override
  State<StepperExample> createState() => _StepperExampleState();
}

class _StepperExampleState extends State<StepperExample> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return Stepper(
      currentStep: _index,
      onStepCancel: () {
        if (_index > 0) {
          setState(() {
            _index -= 1;
          });
        }
      },
      onStepContinue: () {
        if (_index <= 0) {
          setState(() {
            _index += 1;
          });
        }
      },
      onStepTapped: (int index) {
        setState(() {
          _index = index;
        });
      },
      steps: <Step>[
        Step(
          title: const Text('Step 1 title'),
          content: Container(
            alignment: Alignment.centerLeft,
            child: const Text('Content for Step 1'),
          ),
        ),
        const Step(
          title: Text('Step 2 title'),
          content: Text('Content for Step 2'),
        ),
      ],
    );
  }
}

```

</details>

The code is a copy from the example at https://api.flutter.dev/flutter/material/Stepper-class.html

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Expected (Using 3.24.5):
image

Actual (Using 3.27.0):
image

</details>

### Logs

<details open><summary>Logs</summary>

```console
Not relevant
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22621.4460], locale de-DE)
    • Flutter version 3.27.0 on channel stable at C:\Users\pascalpex\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\pascalpex\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\pascalpex\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35527.113
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Users\pascalpex\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] IntelliJ IDEA Community Edition (version 2024.3)
    • IntelliJ at C:\Users\pascalpex\AppData\Local\Programs\IntelliJ IDEA Community Edition
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\pascalpex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.4460]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.86

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by nate-thegrate**
@ayyoub-coder gave a fantastic summary of the problem in #160177: if a `Container` doesn't have a child or unbounded constraints, it will expand to fill its parent, whereas a `ColoredBox` defaults to zero size.

I also noticed that in the main branch, the `PositionedDirectional` widget has an unused `width` parameter, and instead builds a `SizedBox` child for it.

This pull request cleans up the `Stepper` subtree a bit and allows the connector to display properly.

fixes #160156

### CODE REVIEW

File: packages/flutter/test/material/stepper_test.dart [hunk 1]
```diff
@@ -1815,6 +1815,82 @@ testWidgets('Stepper custom indexed controls test', (WidgetTester tester) async
...
+    final Duration duration = Duration(
+      microseconds: kThemeAnimationDuration.inMicroseconds ~/ (checkCount+1),
+    );
+
+    for (int i = 0; i < checkCount; i++) {
+      await tester.pump(duration);
+      verifyConnector();
+    }
+  });
+
```
Comment (TahaTesser) [inline packages/flutter/test/material/stepper_test.dart:1893]:
```suggestion
    }
  });
```

File: packages/flutter/test/material/stepper_test.dart [hunk 2]
```diff
@@ -1815,6 +1815,82 @@ testWidgets('Stepper custom indexed controls test', (WidgetTester tester) async
...
+                    ),
+                  ],
+                );
+              }
+            ),
+          ),
+        ),
+      ),
+    );
+    await tester.pumpAndSettle();
```
Comment (TahaTesser) [inline packages/flutter/test/material/stepper_test.dart:1854]: Is this required after `pumpWidget`?

**Review by TahaTesser — APPROVED** [review]
LGTM with nits

File: packages/flutter/test/material/stepper_test.dart (hunk 2 above)
Comment (nate-thegrate) [reply packages/flutter/test/material/stepper_test.dart]: It's not, thanks for catching this!

File: packages/flutter/test/material/stepper_test.dart (hunk 1 above)
Comment (nate-thegrate) [reply packages/flutter/test/material/stepper_test.dart]: It's weird—GitHub isn't showing that any suggestion is being made, despite how the comment is attached to a blank line.

invalid

(should be fixed in https://github.com/flutter/flutter/pull/160193/commits/d70a6b5f552222336cb6e7ee42b76e33fd2b24c8)
