### PR TITLE
Fix `CalendarDatePicker` day selection shape and overlay

### LINKED ISSUE #141350: `DatePickerDialog` date entry hover background and ink splash have different radius
### Steps to reproduce

1. Have a `DatePickerDialog` in your app and have M3 enabled
2. Run the app (I tried macOS, CanvasKit, and skwasm)
3. Open the date picker if necessary
4. Try hovering over a non-active date
5. Press down and let ripple spread

### Expected results

I expect the ink ripple won't leave the boundaries of the hover background, but it expands beyond that. 

### Actual results

When pressing down on a non-active date, the ink ripple expands beyond the hover circle and even overlaps with other dates.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: DatePickerDialog(
            firstDate: DateTime.utc(2010),
            lastDate: DateTime.utc(2030),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Video

<details open>
<summary>Video demonstration</summary>

Video showcasing behavior:

https://github.com/flutter/flutter/assets/18372958/91da1115-0082-4e55-9680-e3e7165cbb68

</details>

### Flutter version

<details><summary>Version info</summary>

```console
Flutter 3.19.0-3.0.pre.43 • channel main • https://github.com/flutter/flutter
Framework • revision f961fdf2ba (4 hours ago) • 2024-01-10 17:37:07 -0500
Engine • revision a045134c91
Tools • Dart 3.4.0 (build 3.4.0-14.0.dev) • DevTools 2.31.0
```

</details>

### LINKED ISSUE #144220: Ability to customize DatePicker day selection background and overlay shape
### Use case

Currently, you can only customize the date picker dialog shape but not the day selection background and overlay shape.

Screenshot 2024-02-27 at 12 34 38

### Proposal

Date picker day selection background and overlay shape should be customizable and be consistent with the dialog shape.

Screenshot 2024-02-27 at 12 32 04

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [`DatePickerDialog` date entry hover background and ink splash have different radius](https://github.com/flutter/flutter/issues/141350)
fixes [Ability to customize DatePicker day selection background and overlay shape](https://github.com/flutter/flutter/issues/144220)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return FilledButton(
              onPressed: () {
                showDatePicker(
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime.utc(2010),
                  lastDate: DateTime.utc(2030),
                );
              },
              child: const Text('Show Date picker'),
            );
          }),
        ),
      ),
    );
  }
}
```

</details>

### Material DatePicker states specs

overlay_specs

### Day selection overlay

| Before | After |
| --------------- | --------------- |
|  |  |

### Hover, pressed, highlight preview

| Before | After |
| --------------- | --------------- |
| <video src="https://github.com/flutter/flutter/assets/48603081/8edde82a-7f39-4482-afab-183e1bce5991" /> | <video src="https://github.com/flutter/flutter/assets/48603081/04e1502e-67a4-4b33-973d-463067d70151" /> |

### Using `DatePickerThemeData.dayShape` to customize day selection background and overlay shape

| Before | After |
| --------------- | --------------- |
|   |  | 

### Example preview

Screenshot 2024-02-29 at 15 07 50

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/material/date_picker_theme.dart [hunk 1]
```diff
@@ -163,6 +164,10 @@ class DatePickerThemeData with Diagnosticable {
   /// indicate that a day in the grid is focused, hovered, or pressed.
   final MaterialStateProperty<Color?>? dayOverlayColor;
 
+  /// Overrides the default shape used to paint the shape decoration of the
+  /// day labels in the grid of the date picker.
+  final MaterialStateProperty<OutlinedBorder?>? dayShape;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/date_picker_theme.dart:169]: Since this property only appears in the theme (which is OK) you should explain how it interacts with `todayBorder` and `todayForegroundColor`

**Review by HansMuller — APPROVED** [review]
LGTM with one small request for additional doc and maybe an example.
