### PR TITLE
fix: Update time picker dialog input size

### LINKED ISSUE #162796: Material showTimePicker (input mode) actions overflow when using longer confirm and cancel text
### Steps to reproduce

1. Use the `showTimePicker` function with longer `cancelText` and/or `confirmText`
2. Switch to `TimePickerEntryMode.input` mode
3. Actions don't fit on a single line, get stacked vertically, and overflow

For localisation reasons we use different texts for the confirm and cancel button. Since most languages are longer than english, this is causing the actions to no longer fit on a single line.

Doesn't become an issue as quickly on devices using a 12h time format since it provides more width to the dialog, though with enough length it still does eventually.

The size of the dialog seems to be decided by `_kTimePickerInputSize` in `time_picker.dart` line 2237

### Expected results

Time picker dialog adjusts size and/or becomes scrollable to prevent the overflow of actions

### Actual results

Time picker dialog remains the same size and the actions overflow when they become to wide to fit horizontally.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Builder(
            builder: (context) {
              return FilledButton(
                onPressed: () => showTimePicker(
                  context: context,
                  initialTime: TimeOfDay.now(),
                  cancelText: 'Long cancel',
                  confirmText: 'Long confirm',
                  initialEntryMode: TimePickerEntryMode.input,
                ),
                child: Text('Show time picker'),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#cd626 relayoutBoundary=up1 OVERFLOWING:
  needs compositing
  creator: Column ← _TimePickerModel ← _TimePicker ← _FormScope ← WillPopScope ←
    Form-[LabeledGlobalKey<FormState>#de586] ← Expanded ← Column ← ConstrainedBox ← Container ←
    AnimatedContainer ← _SingleChildViewport ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight (can use size)
  constraints: BoxConstraints(0.0<=w<=248.0, h=120.0)
  size: Size(248.0, 120.0)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: min
  crossAxisAlignment: center
  verticalDirection: down
  spacing: 0.0
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by 20 pixels on the bottom.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.3 24D60 darwin-arm64, locale en-NL)
    • Flutter version 3.27.3 on channel stable at /Users/MyUser/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (2 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/MyUser/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/MyUser/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/MyUser/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.96.4)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34)
      (emulator)
    • iPhone 16 Pro Max (mobile)      • 16510E30-C714-4E22-B587-64BFEA7B4182 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3 24D60
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3 24D60
      darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome
      133.0.6943.53
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
fix: Update time picker dialog input size
Fixes: #162796 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for making this PR. My main concern was accessibility, and the text being scaled up. But there are clamping on the text scaling and specifically in the input mode we have room to increase the height a little, so this should be fine. Due to box constraints, this only affects the max size and will not affect input dialogs that do not need the extra space.

**Review by justinmc — APPROVED** [review]
LGTM assuming Google tests pass 👍 . I didn't realized this height would be hardcoded but I guess so.

**Comment by MitchellGoodwin** [comment]
> LGTM assuming Google tests pass 👍 . I didn't realized this height would be hardcoded but I guess so.

The material date pickers have hard coded maxes due to containing text scaling. The calendar view in particular has to watch out for a lot of text being scaled up and filling the screen. There's wiggle room with the input picker though, which has less text.

**Comment by MitchellGoodwin** [comment]
I was wrong, Google testing is showing that the pickers are expanding when they don't need to. It doesn't look great. I'm not sure what the best solution is.

**Comment by rkishan516** [comment]
> I was wrong, Google testing is showing that the pickers are expanding when they don't need to. It doesn't look great. I'm not sure what the best solution is.

I will see, what other solution I can come up with.

**Comment by rkishan516** [comment]
@MitchellGoodwin Few solutions
We can make actions horizontally or vertically scrollable.
or
We can change dialog size dynamically with content size.

**Comment by MitchellGoodwin** [comment]
> @MitchellGoodwin Few solutions We can make actions horizontally or vertically scrollable. or We can change dialog size dynamically with content size. (As you said text scaling will be an issue).

Making them scrollable is nice because it will avoid errors, but would lead to bad UI, in my opinion. We could do that as a last resort.

Changing the dialog size dynamically would be preferable. For the input time picker there's a lot of room to grow. All the careful constraints are target towards the calendar date picker, which fills up much more space. I'd have to double check but I believe font size can only increase by 10%. When I looked at the code, dynamically increasing the size does seem difficult, however, with the expanded widgets involved.

**Comment by rkishan516** [comment]
> > @MitchellGoodwin Few solutions We can make actions horizontally or vertically scrollable. or We can change dialog size dynamically with content size. (As you said text scaling will be an issue).
> 
> Making them scrollable is nice because it will avoid errors, but would lead to bad UI, in my opinion. We could do that as a last resort.
> 
> Changing the dialog size dynamically would be preferable. For the input time picker there's a lot of room to grow. All the careful constraints are target towards the calendar date picker, which fills up much more space. I'd have to double check but I believe font size can only increase by 10%. When I looked at the code, dynamically increasing the size does seem difficult, however, with the expanded widgets involved.

Yaa, I have converted `Expanded` into `Flexible` and given a top padding for actions same as dialog's bottom padding, such that it looks symmetrical. And since dial mode needs some height, so I have added maxHeight constraints. So, its dynamic till a point.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 1]
```diff
@@ -2507,7 +2507,10 @@ class _TimePickerDialogState extends State<TimePickerDialog> with RestorationMix
     final MaterialLocalizations localizations = MaterialLocalizations.of(context);
 
     final Widget actions = Padding(
-      padding: EdgeInsetsDirectional.only(start: theme.useMaterial3 ? 0 : 4),
+      padding: EdgeInsetsDirectional.only(
+        start: theme.useMaterial3 ? 0 : 4,
+        top: (pickerTheme.padding ?? defaultTheme.padding).vertical / 2,
```
[the remark this answers is not in the document]
Comment (rkishan516) [reply packages/flutter/lib/src/material/time_picker.dart:2512]: I think adding `Flexible` for spacing will start taking entire allowed height and which is not what we want. I wanted spacing around actions symmertical. So, I will change documentation in picker theme.

[the remark this answers is not in the document]
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/time_picker.dart:2512]: I think a flexible spacing widget could be added if a sub `Column` was added as well, setting the priority of how widgets grow.

Some of the checks are failing for overflow errors, so I imagine that since this space is static and cannot shrink it is lowering the amount of open space for the rest of the widgets.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 2]
```diff
@@ -2606,13 +2606,15 @@ class _TimePickerDialogState extends State<TimePickerDialog> with RestorationMix
                 restorationId: 'time_picker_scroll_view_vertical',
                 child: AnimatedContainer(
                   width: allowedSize.width,
-                  height: allowedSize.height,
                   duration: _kDialogSizeAnimationDuration,
                   curve: Curves.easeIn,
+                  constraints: BoxConstraints(maxHeight: allowedSize.height),
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/time_picker.dart:2611]: Apologies for letting this sit, I needed to find time to look into it. It still looks like it's expanding a bit too much when it doesn't need to.

What if we added a minHeight to this with the original minimum height `216`, then added a mainAxisAlignment of `spaceBetween` to the Column and removed the spacer and flex from the Flexible.

We want to: have a small space between the form and actions if possible. If the form expands, then we want the space to go away first until it's gone completely, _then_ start growing the dialog box.

Theoretically this combo would work. What do you think?

Comment (rkishan516) [reply packages/flutter/lib/src/material/time_picker.dart:2611]: Yup, I think this should work. Since we are doing spaceBetween so first that will shrink the space and then it will change dialog height.

Comment (rkishan516) [reply packages/flutter/lib/src/material/time_picker.dart]: @MitchellGoodwin I have pushed the change, Just one change from your suggestion i.e. keeping it limited to input and inputOnly mode.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 3]
```diff
@@ -2606,33 +2606,45 @@ class _TimePickerDialogState extends State<TimePickerDialog> with RestorationMix
...
-                            minuteLabelText: widget.minuteLabelText,
-                            restorationId: 'time_picker',
-                            entryMode: _entryMode.value,
-                            orientation: widget.orientation,
-                            onEntryModeChanged: _handleEntryModeChanged,
-                            switchToInputEntryModeIcon: widget.switchToInputEntryModeIcon,
-                            switchToTimerEntryModeIcon: widget.switchToTimerEntryModeIcon,
-                          ),
-                        ),
+                      Builder(
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/time_picker.dart:2620]: What's the benefit of using a Builder? To be able to do the _entryMode check below in less lines?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 4]
```diff
@@ -2606,33 +2606,45 @@ class _TimePickerDialogState extends State<TimePickerDialog> with RestorationMix
                 restorationId: 'time_picker_scroll_view_vertical',
                 child: AnimatedContainer(
                   width: allowedSize.width,
-                  height: allowedSize.height,
                   duration: _kDialogSizeAnimationDuration,
                   curve: Curves.easeIn,
+                  constraints: BoxConstraints(
+                    minHeight: _kTimePickerMinInputSize.height,
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/time_picker.dart:2612]: This should be the original value. So above we'd want:
```dart
static const Size _kTimePickerInputSize = Size(312, 252);
static const double _kTimePickerInputMinimumHeight = 216;
```

then here it would be:
```dart
constraints: BoxConstraints(
  minHeight: _kTimePickerInputMinimumHeight,
  maxHeight: allowedSize.height,
),
```
This keeps dialogs that do not need to expand to not be bigger than they were before.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 3 above)
Comment (rkishan516) [reply packages/flutter/lib/src/material/time_picker.dart:2620]: Yes, @MitchellGoodwin.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 4 above)
Comment (rkishan516) [reply packages/flutter/lib/src/material/time_picker.dart]: Sorry, My bad I didn't checked value of _kTimePickerMinInputSize and thought it will be 216. I have pushed required change.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the follow up fixes.
