### PR TITLE
Fix not disposed items in Cupertino app and route.

### LINKED ISSUE #134057: Apply the leak fix to CuppertinoApp
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

-

### Proposal

-

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/134057

### CODE REVIEW

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/app_test.dart [hunk 1]
```diff
@@ -406,7 +410,7 @@ void main() {
                 backgroundCursorColor: DefaultSelectionStyle.of(context).selectionColor!,
                 cursorColor: DefaultSelectionStyle.of(context).cursorColor!,
                 controller: TextEditingController(),
```
Comment (navaronbracke) [inline packages/flutter/test/cupertino/app_test.dart:412]: You should also dispose the text editing controller here.
