### PR TITLE
Catch FormatException parsing XCDevice._getAllDevices

### LINKED ISSUE #90913: [flutter_tools] FormatException parsing XCDevice._getAllDevices
On stable/2.5.1

In `daemon` command.

```
Thread 0 main threadFormatException: FormatException: Missing expected digit (at character 3)[-[SimLaunchHostConnection _onQueue_launchInstanceUnload:]_block_invoke:302...  ^
at _ChunkedJsonParser.fail(convert_patch.dart:1405)
at _ChunkedJsonParser.parseNumber(convert_patch.dart:1269)
at _ChunkedJsonParser.parse(convert_patch.dart:937)
at _parseJson(convert_patch.dart:40)
at JsonDecoder.convert(json.dart:506)
at JsonCodec.decode(json.dart:157)
at XCDevice._getAllDevices(xcdevice.dart:115)
at <asynchronous gap>(async)
at XCDevice.getAvailableIOSDevices(xcdevice.dart:227)
at <asynchronous gap>(async)
at IOSDevices._onDeviceEvent(devices.dart:103)
at <asynchronous gap>(async)
```

Another stacktrace:
```
Thread 0 main threadFormatException: FormatException: Unexpected character (at character 2)[+[SimLaunchHostClient launchHostClientForRuntime:error:]:82] ERROR : Faile... ^
at _ChunkedJsonParser.fail(convert_patch.dart:1405)
at _ChunkedJsonParser.parseNumber(convert_patch.dart:1272)
at _ChunkedJsonParser.parse(convert_patch.dart:937)
at _parseJson(convert_patch.dart:40)
at JsonDecoder.convert(json.dart:506)
at JsonCodec.decode(json.dart:157)
at XCDevice._getAllDevices(xcdevice.dart:115)
at <asynchronous gap>(async)
at XCDevice.getAvailableIOSDevices(xcdevice.dart:227)
at <asynchronous gap>(async)
at IOSDevices._onDeviceEvent(devices.dart:103)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by jmagman**
`xcdevice` sometimes logs a stack trace to `stdout` with a 0 exit code.  Handle the malformed json and continue so as not to block additional platform device discovery.

Fixes https://github.com/flutter/flutter/issues/90913

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/xcdevice.dart [hunk 1]
```diff
@@ -112,8 +112,15 @@ class XCDevice {
...
-        final List<dynamic> listResults = json.decode(result.stdout) as List<dynamic>;
-        _cachedListResults = listResults;
+        List<dynamic> listResults = <dynamic>[];
+        final String listOutput = result.stdout;
+        try {
+          listResults = json.decode(listOutput) as List<dynamic>;
+          _cachedListResults = listResults;
+        } on FormatException {
+          // xcdevice logs errors and crashes to stdout.
+          _logger.printError('xcdevice returned non-JSON response: $listOutput');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/macos/xcdevice.dart:122]: should we return null here, as we do below if `result.exitCode != 0`?

Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:122]: Good idea.

Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcdevice.dart:122]: Done.

**Review by christopherfujino — APPROVED** [review]
LGTM
