### PR TITLE
[flutter_tools] port bash script to use sysctl not uname on macOS

### LINKED ISSUE #101243: Apple silicon machine on latest master shows x64 cached Dart version
## Steps to Reproduce

See log: https://gist.github.com/timsneath/0340a7ef006dfda3a981fe4073a13670

I was expecting to see ARM here -- am I misled, @jmagman?

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/101243

For context, a similar Flutter tool change was made in https://github.com/flutter/flutter/pull/67970/files

To test the bash logic, you can update line 66:

To test `sysctl` returning exit code 1 on x64 and newer macOS: `QUERY="false"`

It should log: `Downloading Darwin x64 Dart SDK from Flutter engine $ENGINE_VERSION...`

To test `sysctl` returning exit code 0 (success) but printing 0 (arm64 not present) on x64 and older macOS: `QUERY="echo 0"`

It should log: `Downloading Darwin x64 Dart SDK from Flutter engine $ENGINE_VERSION...`

To test `sysctl` returning exit code 0 (success) and printing 1 (arm64 present) on arm64: `QUERY="echo 1"`

It should log: `Downloading Darwin arm64 Dart SDK from Flutter engine $ENGINE_VERSION...`

### CODE REVIEW

**Comment by jmagman** [comment]
This works on x64 machine:
```
$ flutter
Downloading Darwin x64 Dart SDK from Flutter engine 801d8c530fc5b0c102d13d5913dbd98376b99c93...
```

File: bin/internal/update_dart_sdk.sh [hunk 1]
```diff
@@ -56,20 +56,29 @@ if [ ! -f "$ENGINE_STAMP" ] || [ "$ENGINE_VERSION" != `cat "$ENGINE_STAMP"` ]; t
...
 
-  # On x64 stdout is "uname -m: x86_64"
-  # On arm64 stdout is "uname -m: aarch64, arm64_v8a"
-  case "$(uname -m)" in
-    x86_64)
+  OS="$(uname -s)"
+  # `uname -m` may be running in Rosetta mode, instead query sysctl
+  if [ "$OS" = 'Darwin' ]; then
+    ARCH="arm64"
+    # This will exit 1 if the CPU arch is not ARM64
```
Comment (jmagman) [inline bin/internal/update_dart_sdk.sh:64]: On x64 it will either exit with a failure code, or it will exit successfully and print `0` (I actually don't see that anymore, but I did see that working on https://github.com/flutter/flutter/pull/67970, though it may have been a beta version of macOS):
```
$ sysctl hw.optional.arm64
sysctl: unknown oid 'hw.optional.arm64'
$ echo $?
1
```
On arm64 it will print `1` and exit successfully.

Comment (christopherfujino) [reply bin/internal/update_dart_sdk.sh:64]: argh, we need to parse the output then?

Comment (christopherfujino) [reply bin/internal/update_dart_sdk.sh:64]: at least it looks like we can do `sysctl -n hw.optional.arm64` https://github.com/pytorch/pytorch/blob/e7ca62be08f96b07efc1271baf9b02d4e7be226a/cmake/Modules/FindARM.cmake#L44

It's annoying we have to ALSO check the exit value though

Comment (jmagman) [reply bin/internal/update_dart_sdk.sh:64]: If I recall the last time I looked at this on old versions of macOS it exited 1, on new versions of macOS on x64 it exited successfully and printed `0`, and on arm64 it printed `1`.  However on latest macOS on my x64 machine it's exiting failure with `sysctl: unknown oid 'hw.optional.arm64'`.  So maybe that's not the behavior anymore.

Comment (christopherfujino) [reply bin/internal/update_dart_sdk.sh]: Updated this to mirror the logic of https://github.com/flutter/flutter/pull/67970

File: bin/internal/update_dart_sdk.sh [hunk 2]
```diff
@@ -56,20 +56,44 @@ if [ ! -f "$ENGINE_STAMP" ] || [ "$ENGINE_VERSION" != `cat "$ENGINE_STAMP"` ]; t
...
-  # On arm64 stdout is "uname -m: aarch64, arm64_v8a"
-  case "$(uname -m)" in
-    x86_64)
-      ARCH="x64"
-      ;;
-    *)
-      ARCH="arm64"
-      ;;
-  esac
+  OS="$(uname -s)"
```
Comment (zanderso) [inline bin/internal/update_dart_sdk.sh:60]: `uname -s` is already called up on line 28. Consider hoisting both calls up.

File: bin/internal/update_dart_sdk.sh [hunk 3]
```diff
@@ -56,20 +56,44 @@ if [ ! -f "$ENGINE_STAMP" ] || [ "$ENGINE_VERSION" != `cat "$ENGINE_STAMP"` ]; t
...
+    if [ $? -eq 1 ]; then
+      # If this command fails, we're certainly not on ARM
+      ARCH='x64'
+    elif [ "$QUERY_RESULT" = '0' ]; then
+      # If this returns 0, we are also not on ARM
+      ARCH='x64'
+    elif [ "$QUERY_RESULT" = '1' ]; then
+      ARCH='arm64'
+    else
+      >&2 echo "$QUERY returned unexpected output: $QUERY_RESULT"
```
Comment (zanderso) [inline bin/internal/update_dart_sdk.sh:79]: Consider single quotes around `$QUERY` and `$QUERY_RESULT`.

**Review by zanderso — APPROVED** [review]
lgtm. This will need manual testing on both x64 and arm64 macs.

**Comment by christopherfujino** [comment]
I have tested this works on x64 mac.

File: bin/internal/update_dart_sdk.sh (hunk 3 above)
Comment (christopherfujino) [reply bin/internal/update_dart_sdk.sh]: done

File: bin/internal/update_dart_sdk.sh (hunk 2 above)
Comment (christopherfujino) [reply bin/internal/update_dart_sdk.sh]: good call, done.

**Comment by jmagman** [comment]
Confirmed 20f64ac works on x64 (downloads x64), arm64 (downloads arm64), arm64 w/ Rosetta (downloads arm64).

**Comment by jmagman** [comment]
To test, consider an integration test that validates 
```
$ file bin/cache/dart-sdk/bin/dart
bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable x86_64

**Comment by christopherfujino** [comment]
> To test, consider an integration test that validates
> 
> ```
> $ file bin/cache/dart-sdk/bin/dart
> bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable x86_64
> ```
> 
> similar to
> 
> https://github.com/flutter/flutter/blob/6ab00756a8e30f71f0dc30b1f12333479e7f2757/packages/flutter_tools/test/integration.shard/ios_content_validation_test.dart#L259-L263
> 
> We won't get arm64 test coverage until #87508 is done.

Good idea, writing this test now

**Comment by christopherfujino** [comment]
Added an integration test, @jmagman PTAL

File: packages/flutter_tools/test/integration.shard/bash_entrypoint_test.dart [hunk 4]
```diff
@@ -14,14 +14,19 @@ import 'test_utils.dart';
 final String flutterRootPath = getFlutterRoot();
 final Directory flutterRoot = fileSystem.directory(flutterRootPath);
 
+enum MacArches {
```
Comment (jmagman) [inline packages/flutter_tools/test/integration.shard/bash_entrypoint_test.dart:17]: nit: there's probably a better name than `bash_entrypoint_test` for this test file since it's doing more now.

**Review by jmagman — APPROVED** [review]
LGTM

File: packages/flutter_tools/test/integration.shard/bash_entrypoint_test.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/integration.shard/bash_entrypoint_test.dart:17]: It's technically testing the entrypoint, since the entrypoint is responsible for caching the dart SDK, but I'm open to suggestions.

Comment (jmagman) [reply packages/flutter_tools/test/integration.shard/bash_entrypoint_test.dart:17]: It's fine as-is.
