### PR TITLE
[tool] fix android studio preview's version parsing

### LINKED ISSUE #121925: Tool can't parse version of Android Studio Preview on macOS
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using the Android Studio Giraffe Canary 7 and the latest master channel flutter

### Actual results

Flutter doctor is still saying unable to find bundled java

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel master, 3.9.0-1.0.pre.48, on macOS 13.3 22E7752300f
    darwin-arm64, locale en-US)
    • Flutter version 3.9.0-1.0.pre.48 on channel master at /Users/ti4n/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f2f80059ff (23 minutes ago), 2023-03-03 23:39:38 -0500
    • Engine revision de724e2632
    • Dart version 3.0.0 (build 3.0.0-290.0.dev)
    • DevTools version 2.22.2

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

```

</details>

### PR DESCRIPTION
**Pull request by Sameri11**
This PR willing to fix issue when `flutter doctor` validator can't determine version of Android Studio EAP.

These are before/after outputs of `flutter doctor -v` showcasing change in behaviour of validator. Each output has 3 `Android Studio` sections, 1 for stable and 2 for different EAP versions. 

<details>
<summary>before, (stable, 3.24.3), 2 issues related to versions of Android Studio</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.7 23H124 darwin-arm64, locale en-RU)
    • Flutter version 3.24.3 on channel stable at /Users/samer/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/samer/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Users/samer/Library/Java/JavaVirtualMachines/jbr-17.0.7/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment JBR-17.0.7+7-964.1-nomod (build 17.0.7+7-b964.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-16.0.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/samer/Applications/Android Studio Koala Feature Drop 2024.1.2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[!] Android Studio (version unknown)
    • Android Studio at /Users/samer/Applications/Android Studio Ladybug Feature Drop 2024.2.2 Canary 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[!] Android Studio (version unknown)
    • Android Studio at /Users/samer/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-243.12818.47)
    • IntelliJ at /Users/samer/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • iPhone (Михаил) (mobile)        • 00008020-001254DA1E39002E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.7 23H124 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.90
    ! Error: Browsing on the local area network for Михаил Новосельцев’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>after,  no issues regarding Android Studio</summary>

```console
[!] Flutter (Channel [user-branch], 3.26.0-1.0.pre.383, on macOS 14.7 23H124 darwin-arm64, locale en-RU)
    ! Flutter version 3.26.0-1.0.pre.383 on channel [user-branch] at /Users/samer/projects/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    • Upstream repository git@github.com:Sameri11/flutter.git
    • FLUTTER_GIT_URL = git@github.com:Sameri11/flutter.git
    • Framework revision 852508425d (20 minutes ago), 2024-10-07 21:22:45 +0500
    • Engine revision 683a14c1f1
    • Dart version 3.6.0 (build 3.6.0-326.0.dev)
    • DevTools version 2.40.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/samer/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Users/samer/Library/Java/JavaVirtualMachines/jbr-17.0.7/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment JBR-17.0.7+7-964.1-nomod (build 17.0.7+7-b964.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-16.0.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/samer/Applications/Android Studio Koala Feature Drop 2024.1.2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2024.2.2)
    • Android Studio at /Users/samer/Applications/Android Studio Ladybug Feature Drop 2024.2.2 Canary 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Android Studio (version 2024.2.1)
    • Android Studio at /Users/samer/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-243.12818.47)
    • IntelliJ at /Users/samer/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • iPhone (Михаил) (mobile)        • 00008020-001254DA1E39002E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.7 23H124 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.90
    ! Error: Browsing on the local area network for Михаил Новосельцев’s iPad. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Logic behind these changes explained in https://github.com/flutter/flutter/issues/121925#issuecomment-2352826925 

fixes #121925

**Tests**: updated existing tests by adding version checking, but I don't mind writing new ones if necessary – please tell me if so.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 1]
```diff
@@ -565,6 +565,38 @@ the configured path by running this command: flutter config --android-studio-dir
...
+    if (matched == null || matched.length != 4) {
+      return null;
+    }
+
+    Version? result;
+    try {
+      final int major = int.parse('20${matched[0]}${matched[1]}');
+      final int minor = int.parse(matched[2]);
+      final int patch = int.parse(matched[3]);
+      result = Version(major, minor, patch);
```
Comment (navaronbracke) [inline packages/flutter_tools/lib/src/android/android_studio.dart:592]:
```suggestion
      return Version(major, minor, patch);
```

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 2]
```diff
@@ -565,6 +565,35 @@ the configured path by running this command: flutter config --android-studio-dir
...
+    if (matched == null || matched.length != 4) {
+      return null;
+    }
+
+    final int? major = int.tryParse('20${matched[0]}${matched[1]}');
+    final int? minor = int.tryParse(matched[2]);
+    final int? patch = int.tryParse(matched[3]);
+    if (major == null || minor == null || patch == null) {
+      return null;
+    } else {
```
Comment (navaronbracke) [inline packages/flutter_tools/lib/src/android/android_studio.dart:592]: The else is redundant here

```suggestion
if (major == null || minor == null || patch == null) {
  return null;
}

return Version(major, minor, patch);
```

Comment (Sameri11) [reply packages/flutter_tools/lib/src/android/android_studio.dart:592]: Certainly! Thanks

**Comment by andrewkolos** [comment]
Verified that this works with Ladybug Feature Drop 2024.2.2 Canary 5 installed via JetBrains Toolbox (the PR description includes verification, but I figured it would be nice to test this on another machine):

Before:
```
[!] Android Studio (version unknown)
    • Android Studio at /Users/andrewkolos/Applications/Android Studio Ladybug
      Feature Drop 2024.2.2 Canary 5.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
```

After:

```
[✓] Android Studio (version 2024.2.2)
    • Android Studio at /Users/andrewkolos/Applications/Android Studio Ladybug
      Feature Drop 2024.2.2 Canary 5.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
```

I'll be reviewing the diff shortly.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 3]
```diff
@@ -565,6 +565,34 @@ the configured path by running this command: flutter config --android-studio-dir
...
+    // Example string fort EAP: EAP AI-242.21829.142.2422.12358220
+    // We try to capture 2422 here.
+    final RegExp intellijPattern = RegExp(r'EAP\s+[A-Z]{2}-\d+\.\d+\.\d+\.(\d+)\.\d+');
+    match = intellijPattern.firstMatch(text ?? '');
+
+    if (match == null) {
+      return Version.parse(text);
+    }
+
+    final String? matched = match.group(1);
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/android/android_studio.dart:579]: I have a couple of notes here:

* I don't see a benefit in declaring `match` before it's needed. The name of the function (`_parseVersion`) and existence of a regex pattern already provide a good hint that we are going to be doing some regex-parsing here.
* I am not sure how accurate `intellijPattern` is as a variable name. Also, I think `matched` could be named to something more descriptive.

Consider:

```dart
    // Matches the version string for Preview builds on macOS.
    // Example match: EAP AI-242.21829.142.2422.12358220
    // We try to capture "2422" here, which can be translated to a
    // more human-friendly "24.2.2".
    final RegExp eapVersionPattern = RegExp(
      r'EAP\s+[A-Z]{2}-\d+\.\d+\.\d+\.(\d+)\.\d+',
    );

    final Match? eapVersionMatch = eapVersionPattern.firstMatch(text);

    if (eapVersionMatch == null) {
      return Version.parse(text);
    }

    // This would be "2422" in the earlier example.
    final String? normalVersionPart = eapVersionMatch.group(1);
```

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 4]
```diff
@@ -565,6 +565,34 @@ the configured path by running this command: flutter config --android-studio-dir
...
+    if (matched == null || matched.length != 4) {
+      return null;
+    }
+
+    final int? major = int.tryParse('20${matched[0]}${matched[1]}');
+    final int? minor = int.tryParse(matched[2]);
+    final int? patch = int.tryParse(matched[3]);
+    if (major == null || minor == null || patch == null) {
+      return null;
+    }
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/android/android_studio.dart:592]: This wouldn't work in any version where the minor or patch number is greater than 9. However, looking at the release history for Android Studio, this probably won't be a problem unless things change. LGTM.

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Thanks for well-written PR description and informative comment on the parent issue!

The approach looks good to me, especially when considering https://github.com/flutter/flutter/issues/121925#issuecomment-2352826925.

I agree that relying on a un-documented version pattern isn't ideal, but the ideal fix of getting Android Studio to use legal values for `CFBundleVersion` is unlikely to happen, pragmatically speaking (context/prior effort: https://github.com/flutter/flutter/issues/121925#issuecomment-1492671097).

With this being said, I do think we should have at least one test that verifies that this parsing works when something like `EAP AI-242.21829.142.2422.12358220` is encountered.

**Comment by Sameri11** [comment]
> With this being said, I do think we should have at least one test that verifies that this parsing works when something like `EAP AI-242.21829.142.2422.12358220` is encountered.

Thanks for review @andrewkolos ! Totally agree with the need of test, but isn't it tested [here](https://github.com/flutter/flutter/pull/156293/files#diff-8e81af6ef0cf42456edb4f2a80de60c93d8222d4b36ee01d1b9bb869d8cda223R262) in `discovers Android Studio EAP location` test? Just to be clear, this is `Info.plist` used for this test, and `CFBundleShortVersionString` is in that exact format there:
https://github.com/flutter/flutter/blob/2629eb0d216f7566333cd4d005b9969c147ccd0a/packages/flutter_tools/test/general.shard/android/android_studio_test.dart#L76-L87

As I said, I do not mind to add another test for these changes, but I just want our understanding of necessity to be in sync.

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 3 above)
Comment (Sameri11) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: Thanks! Played a little with naming here. And eliminated separate declaration of `match` – it's agree that there's no benefit.

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 4 above)
Comment (Sameri11) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: Agree, but introducing two-digits versioning will completely break this format, so I'm not sure that studio's team will allow that. But, from the other side, this is undocumented behaviour, so they are kinda free to do that :( But yeah, I do not think that it's possible and even justified here to take that possibility in account, because of code will become too cumbersome

**Comment by andrewkolos** [comment]
Ah, I failed to realize that we already have a test for detecting EAP versions. Since you added an `expect` against the version on that test, we're good here. Thanks for letting me know so patiently 🙂

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 5]
```diff
@@ -565,6 +565,33 @@ the configured path by running this command: flutter config --android-studio-dir
     }
   }
 
+  static Version? _parseVersion(String text) {
+    // Example string fort EAP: EAP AI-242.21829.142.2422.12358220
+    // We try to capture 2422 here.
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/android/android_studio.dart:570]: From my earlier suggestion in https://github.com/flutter/flutter/pull/156293#discussion_r1797427098:

```suggestion
    // Matches the version string for Preview builds on macOS.
    // Example match: EAP AI-242.21829.142.2422.12358220
    // We try to capture "2422" here, which can be translated to a
    // more human-friendly "24.2.2".
```

**Review by andrewkolos — APPROVED** [review]
LGTM with a nitpick

Thanks again for the well-written PR

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 5 above)
Comment (Sameri11) [reply packages/flutter_tools/lib/src/android/android_studio.dart:570]: Yep, missed that, thanks.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 6]
```diff
@@ -565,6 +565,35 @@ the configured path by running this command: flutter config --android-studio-dir
...
+
+    final String? rawVersionMatch = eapVersionMatch.group(1);
+
+    // length of 4 is because that how version is encrypted: first two digits
+    // for year (part of major version), third for minor version, fourth for patch.
+    if (rawVersionMatch == null || rawVersionMatch.length != 4) {
+      return null;
+    }
+
+    final int? major = int.tryParse('20${rawVersionMatch[0]}${rawVersionMatch[1]}');
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/android/android_studio.dart:588]: This will break in 2100 😉

**Review by bkonyi — APPROVED** [review]
LGTM!

**Comment by Sameri11** [comment]
@andrewkolos @bkonyi thanks for your reviews guys, appreciate it! Now, when PR has 2 LGTMs, it is ready to merge as per [tree hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#getting-a-code-review). right? If so, would you be so kind to provide "autosubmit" label here, please? :)

**Comment by bkonyi** [comment]
> @andrewkolos @bkonyi thanks for your reviews guys, appreciate it! Now, when PR has 2 LGTMs, it is ready to merge as per [tree hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#getting-a-code-review), right? If so, would you be so kind to provide "autosubmit" label here, please? :)

Yep! Just need to rerun that failing check. Hopefully it'll pass and should land on its own :)
