### PR TITLE
Check to see if previous page is laid out before starting hero flight

### LINKED ISSUE #168267: Crash during Cupertino swipe-back gesture: HeroController accesses un-laid-out RenderBox for offstage route
### Steps to reproduce

1.  Create a Flutter application using `CupertinoApp`.
2.  Use the `builder` parameter of `CupertinoApp` to provide a `Navigator` whose page stack is managed declaratively (e.g., using `Navigator.pages` backed by a `StatefulWidget`'s state).
3.  Define at least three distinct screens/pages using `CupertinoPage`: `HomeScreen`, `IntermediateScreen`, `DeepScreen`.
4.  Implement a mechanism (e.g., a button press in `HomeScreen`) that updates the `Navigator.pages` list directly from `[HomeScreen]` to `[HomeScreen, IntermediateScreen, DeepScreen]`. This simulates navigating directly to a deep link while ensuring the intermediate route exists in the final stack.
5.  Run the application.
6.  Trigger the navigation from `HomeScreen` to `DeepScreen` (step 4).
7.  Initiate a swipe-back gesture from the left edge of the screen.

### Expected results

The swipe-back gesture should initiate smoothly without any crashes, allowing the user to navigate back to the `IntermediateScreen`.

### Actual results

The application crashes immediately upon starting the swipe-back gesture from `DeepScreen`. Two assertion failures are observed:

1.  **`'package:flutter/src/widgets/heroes.dart': Failed assertion: line 479 pos 12: 'box.hasSize && box.size.isFinite': is not true.`**
2.  **`'package:flutter/src/cupertino/route.dart': Failed assertion: line 754 pos 12: '_backGestureController != null': is not true.`**

The crash occurs because the swipe-back gesture mechanism in `CupertinoPageRoute` notifies the default `HeroController`. The `HeroController` then attempts to prepare for a potential transition by calculating the layout bounds of the previous route (`IntermediateScreen`). However, because the navigation stack was just updated declaratively, the `IntermediateScreen` was pushed directly into an offstage state. When the swipe gesture starts after this navigation, the `RenderBox` for the offstage `IntermediateScreen` may not have been laid out yet, causing the `box.hasSize && box.size.isFinite` assertion to fail. The second assertion is a consequence of the first failure.

This minimal reproduction code, using the standard `Navigator` API, simulates the core navigation flow (declarative multi-page stack update followed by a swipe-back gesture) that originally caused this crash when using routing packages like `go_router`. This strongly suggests the issue lies within the Flutter framework's handling of page transitions, offstage widget layout timing, and the Hero animation system.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

// --- Navigator Key ---
final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

// --- Main App Setup ---

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    const BuppyApp(),
  );
}

class BuppyApp extends StatefulWidget {
  const BuppyApp({super.key});

  @override
  State<BuppyApp> createState() => _BuppyAppState();
}

class _BuppyAppState extends State<BuppyApp> {
  // Declare _pages, initialize in initState
  late List<Page<dynamic>> _pages;

  @override
  void initState() {
    super.initState();
    // Initialize _pages here where _goToDeepScreen is accessible
    _pages = <Page<dynamic>>[
      CupertinoPage(
        key: const ValueKey('home'),
        name: '/',
        child: HomeScreen(goToDeepScreen: _goToDeepScreen),
      ),
    ];
  }

  // Method to update pages state and trigger rebuild
  void _goToDeepScreen() {
    setState(() {
      _pages = <Page<dynamic>>[
        CupertinoPage(
          key: const ValueKey('home'),
          name: '/',
          child: HomeScreen(goToDeepScreen: _goToDeepScreen),
        ),
        const CupertinoPage(
          key: ValueKey('intermediate'),
          name: '/intermediate',
          child: IntermediateScreen(),
        ),
        const CupertinoPage(
          key: ValueKey('deep-id'),
          name: '/intermediate/deep-id',
          child: DeepScreen(id: 'test-id'),
        ),
      ];
    });
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      builder: (context, child) {
        // We pass the Navigator built below as the child here
        return Navigator(
          key: _navigatorKey, // Use the stable GlobalKey
          pages: _pages, // Use local state _pages
          // Handle pop event (e.g., swipe back gesture)
          onPopPage: (Route<dynamic> route, dynamic result) {
            if (!route.didPop(result)) {
              return false;
            }
            // Update the pages state when a page is popped
            // Update pages state directly using setState
            if (_pages.length > 1) {
              setState(() {
                _pages = List<Page<dynamic>>.from(_pages)..removeLast();
              });
            }
            return true;
          },
        );
      },
    );
  }
}

// --- Screen Widgets ---

class HomeScreen extends StatelessWidget {
  final VoidCallback goToDeepScreen;
  const HomeScreen({super.key, required this.goToDeepScreen});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Home'),
      ),
      child: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Home Screen'),
              const SizedBox(height: 20),
              CupertinoButton.filled(
                onPressed: goToDeepScreen,
                child: const Text(
                    'Trigger Bug Scenario (Go Deep)'), // Call the passed callback
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class IntermediateScreen extends StatelessWidget {
  const IntermediateScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Intermediate'),
      ),
      child: SafeArea(
        child: Center(
          child: Text('Intermediate Screen (e.g., Chatrooms)'),
        ),
      ),
    );
  }
}

class DeepScreen extends StatelessWidget {
  final String id;

  const DeepScreen({super.key, required this.id});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Deep Screen #$id'),
      ),
      child: const SafeArea(
        child: Center(
          child: Text('Deep Screen Content'),
        ),
      ),
    );
  }
}
```

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/99f63a4d-3adf-45bd-b605-a7f03eb6935a

</details>


### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 479 pos 12: 'box.hasSize &&
box.size.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

When the exception was thrown, this was the stack:
#2      _HeroFlightManifest._boundingBoxFor (package:flutter/src/widgets/heroes.dart:479:12)
#3      _HeroFlightManifest.toHeroLocation (package:flutter/src/widgets/heroes.dart:495:36)
#4      _HeroFlightManifest.toHeroLocation (package:flutter/src/widgets/heroes.dart)
#5      _HeroFlightManifest.isValid (package:flutter/src/widgets/heroes.dart:504:29)
#6      _HeroFlightManifest.isValid (package:flutter/src/widgets/heroes.dart)
#7      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:1020:40)
#8      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:926:7)
#9      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:850:5)
#10     NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:5777:18)
#11     new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:835:15)
#12     CupertinoRouteTransitionMixin._startPopGesture (package:flutter/src/cupertino/route.dart:205:12)
#13     CupertinoRouteTransitionMixin.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:254:36)
#14     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:749:54)
#15     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:849:53)
#16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:345:24)
#17     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:849:7)
#18     DragGestureRecognizer._checkDrag (package:flutter/src/gestures/monodrag.dart:815:5)
#19     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:743:7)
#20     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:275:25)
#21     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:255:31)
... (omitted frames) ...

Handler: "onStart"
Recognizer:
  HorizontalDragGestureRecognizer#xxxxx
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/cupertino/route.dart': Failed assertion: line 754 pos 12:
'_backGestureController != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

When the exception was thrown, this was the stack:
#2      _CupertinoBackGestureDetectorState._handleDragUpdate (package:flutter/src/cupertino/route.dart:754:12)
#3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:868:55)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:345:24)
#5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:868:7)
#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:714:11)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:97:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#9      _LinkedHashMapMixin.forEach (dart:_compact_hash:764:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:131:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:530:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:499:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:473:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:437:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:394:5)
... (omitted frames) ...

Handler: "onUpdate"
Recognizer:
  HorizontalDragGestureRecognizer#xxxxx
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.32.0-0.3.pre, on macOS 15.4.1 24E263 darwin-x64, locale en) [2.0s]                                                                                               
    • Flutter version 3.32.0-0.3.pre on channel beta at /Users/ywkim/development/flutter                                                                                                      
    • Upstream repository https://github.com/flutter/flutter.git                                                                                                                              
    • Framework revision 3bd718ee44 (3 days ago), 2025-04-30 10:11:08 -0700                                                                                                                   
    • Engine revision 453dd7174c                                                                                                                                                              
    • Dart version 3.8.0 (build 3.8.0-278.2.beta)                                                                                                                                             
    • DevTools version 2.45.1                                     
                                                                                                                                                                                              
[✗] Android toolchain - develop for Android devices [504ms]                                                                                                                                   
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS (Xcode 16.3) [2.5s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [54ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed) [52ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.96.4) [52ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources [1,523ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #168267

When going back to a page that never rendered with a hero transition, the app was hanging. This adds a check to see if a page needs to layout before starting the hero flight, and if so, adding a frame delay.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 1]
```diff
@@ -923,8 +927,13 @@ class HeroController extends NavigatorObserver {
 
     // For pop transitions driven by a user gesture: if the "to" page has
     // maintainState = true, then the hero's final dimensions can be measured
-    // immediately because their page's layout is still valid.
-    if (isUserGestureTransition && flightType == HeroFlightDirection.pop && toRoute.maintainState) {
+    // immediately because their page's layout is still valid. Unless due to directly
+    // adding routes to the pages stack causing the route to never get laid out.
+    final bool needsLayout = toRoute.subtreeContext?.findRenderObject()?.debugNeedsLayout ?? true;
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/widgets/heroes.dart:932]: @chunhtai do you happen to know if this check would still work in prod apps, or if there's a better way to check for if a route has done it's layout logic yet?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 2]
```diff
@@ -677,11 +677,15 @@ class _HeroFlight {
...
       switch (type) {
         case HeroFlightDirection.pop:
-          return initial.value == 1.0 && initialManifest.isUserGestureTransition
+          return initialManifest.isUserGestureTransition
               // During user gesture transitions, the animation controller isn't
-              // driving the reverse transition, but should still be in a previously
-              // completed stage with the initial value at 1.0.
-              ? initial.status == AnimationStatus.completed
+              // driving the reverse transition, but should have a starting value
+              // approaching 1.0. In cases where the toRoute begane offstage, there
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart:683]:
```suggestion
              // approaching 1.0. In cases where the toRoute became offstage, there
```

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/heroes.dart:932]: no the getter is wrapped in an assert and will crash in release mode, and any method with debug keyword should only be called in assert anyway

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/heroes.dart:932]: As far as I know there is no direct way to know whether a renderobject is layout dirty or not. Can you do something like RenderBox.hasSize?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 3]
```diff
@@ -677,11 +677,15 @@ class _HeroFlight {
...
+              // is a slight delay while the toRoute laysout before the hero's
+              // flight begins, so the animation may not begin completed.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart:685]:
```suggestion
              // flight begins, so the animation may begin in completed status
```

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 4]
```diff
@@ -677,11 +677,15 @@ class _HeroFlight {
...
+              ? initial.value == 1.0
+                  ? initial.status == AnimationStatus.completed
+                  : initial.status == AnimationStatus.forward
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart:688]: I can't wrap my head around this. Do you know what is the situation that makes this a forward?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/heroes.dart:688]: ah gotcha, yeah in this case I think status is not important, we should just return true.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 5]
```diff
@@ -923,8 +922,15 @@ class HeroController extends NavigatorObserver {
 
     // For pop transitions driven by a user gesture: if the "to" page has
     // maintainState = true, then the hero's final dimensions can be measured
-    // immediately because their page's layout is still valid.
-    if (isUserGestureTransition && flightType == HeroFlightDirection.pop && toRoute.maintainState) {
+    // immediately because their page's layout is still valid. Unless due to directly
+    // adding routes to the pages stack causing the route to never get laid out.
+    final RenderBox? fromRouteRenderBox = toRoute.subtreeContext?.findRenderObject() as RenderBox?;
+    final bool hasLayout =
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart]:
```suggestion
    final bool hasValidSize =
```

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by DyNamite-TNT-1** [comment]
Hi @MitchellGoodwin, I tried this PR on master branch. Yes, it helps to prevent app from crashing.
But "reverse animation state" of CupertinoNavigationBar does not happen when pop a page.

**Comment by MitchellGoodwin** [comment]
> Hi @MitchellGoodwin, I tried this PR on master branch. Yes, it helps to prevent app from crashing. But "reverse animation state" of CupertinoNavigationBar does not happen when pop a page.

Would you be able to take a screen recording and file an issue? I'd like to look into that.

**Comment by DyNamite-TNT-1** [comment]
I use the exact code sample of this [#168267](https://github.com/flutter/flutter/issues/168267) with DartPad. If using stable channel, the app hangs as described in the issue. And I use main or beta channel (which has this PR).

What you can see in the video is that **the first time** the back gesture (swipe to pop) is triggered after pushing more than 1 page, the "reverse animation" does not happen (you can see it clearly in the BackChevron of `CupertinoNavigationBar`). But on the next try, the animation reverses.

Everything is fine for pop page with BackChevron.

https://github.com/user-attachments/assets/bf2df562-0e9a-45ea-bbbd-b665a4e291d0

**Comment by MitchellGoodwin** [comment]
Thank you for the reply, I filed a new issue with your report. #171974

Lets move any discussion over to there.
