### PR TITLE
Re-land fix for not disposed TabController [prod-leak-fix]

### LINKED ISSUE #144910: _DefaultTabControllerState should dispose TabContoller instances.
Re-land the revert https://github.com/flutter/flutter/pull/144579

- [x] Test cover functionality that was broken by dispose: https://github.com/flutter/flutter/pull/144627
- [x] Instrument TabController: https://github.com/flutter/flutter/pull/144912
- [ ] Re-land leak cleanup: https://github.com/flutter/flutter/pull/146745

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/144910

### CODE REVIEW

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 1]
```diff
@@ -843,6 +843,10 @@ class AnimationController extends Animation<double>
   }
 
   void _tick(Duration elapsed) {
+    if (_ticker == null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/animation/animation_controller.dart:846]: This looks fishy. Why is `_tick` still being called when the associated ticker has been disposed?

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 2]
```diff
@@ -276,7 +281,9 @@ class TabController extends ChangeNotifier {
 
   @override
   void dispose() {
-    _animationController?.dispose();
+    if (_disposeAnimationController) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/tab_controller.dart:284]: This is also a strange pattern. Either the TabController owns the AnimationController (then it needs to be disposed here) or it doesn't own it and should never dispose it.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 1 above)
Comment (polina-c) [reply packages/flutter/lib/src/animation/animation_controller.dart:846]: Because ticker uses `SchedulerBinding.instance.scheduleFrameCallback` to invoke tick.
There is number of cases of usage after disposal in Flutter, as it is validated only for small subset. It is not in scope of current cleanup to fix all these cases.
Current clean up makes sure to dispose all disposables, even when usage after disposal happens.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 2 above)
Comment (polina-c) [reply packages/flutter/lib/src/material/tab_controller.dart:284]: Added doc comment. Does it help?

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/animation/animation_controller.dart:846]: Yeah, but it is unscheduled when the ticker is disposed. So, if _tick is still called after dispose there is something else that is not working as intended and - on the surface - this just seems to paper over that problem.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/tab_controller.dart:287]: The pattern is still strange. How about: copyWith will move the animationController to the new TabController and null out _animationController on the old one (this should be added to the documentation of _copyWith). Then, instead of doing an internal `dispose` call in `_copyWith` whoever calls `_copyWith` should follow up with a dispose call if they no longer need the old controller.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 1 above)
Comment (polina-c) [reply packages/flutter/lib/src/animation/animation_controller.dart]: I could not repro the problem I was trying to solve with this. Removed.

File: packages/flutter/lib/src/material/tab_controller.dart (hunk 2 above)
Comment (polina-c) [reply packages/flutter/lib/src/material/tab_controller.dart]: I removed the flag and nulled controller.

It is strange for me though to declare that whoever called _copyWith must call dispose. It is easy to miss. If it is always this way, why copyWith cannot do it?

**Review by goderbauer — APPROVED** [review]
LGTM
