### PR TITLE
#154792 - CupertinoActionSheetAction cursor doesn't change to clickable on desktop

### LINKED ISSUE #154792: `CupertinoActionSheetAction` cursor doesn't change to clickable on desktop.
### Steps to reproduce

Run the `CupertinoActionSheetAction`  code sample below.

### Expected results

Expected a way to change cursor on desktop 

### Actual results

No cursor change 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: const CupertinoThemeData(
        brightness: Brightness.light,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: Builder(builder: (BuildContext context) {
            return CupertinoButton(
              onPressed: () {
                showCupertinoModalPopup<void>(
                  context: context,
                  builder: (BuildContext context) {
                    return CupertinoActionSheet(
                      title: const Text('The title'),
                      message: const Text('Message'),
                      actions: <Widget>[
                        CupertinoActionSheetAction(
                          child: const Text('One'),
                          onPressed: () {},
                        ),
                      ],
                    );
                  },
                );
              },
              child: const Text('Go'),
            );
          }),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel main, 3.25.0-1.0.pre.283, on macOS 15.0 24A5327a
    darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.283 on channel main at
      /Users/tahatesser/Code/flutter
    ! Upstream repository git@github.com:TahaTesser/flutter.git is not the same
      as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:TahaTesser/flutter.gitexport
    • Framework revision aea84342eb (3 days ago), 2024-09-05 16:46:22 -0700
    • Engine revision 015f3b1dec
    • Dart version 3.6.0 (build 3.6.0-216.0.dev)
    • DevTools version 2.39.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5230g
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile)          • 00008120-001C559034DB401E • ios
      • iOS 18.0 22A5350a
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 15.0 24A5327a darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 15.0 24A5327a darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by srivats22**
This PR is for issue #154792 
The Video recording shows the before and after
The first button with the text "Go" uses the default cursor
The second button with the text "With Cursor" uses a custom cursor that has been passed in the parameters
https://github.com/user-attachments/assets/e82ecd42-42b1-42c9-aa30-a6f3daddb436

Here is the code for the second button
```dart
CupertinoButton(
    onPressed: () {
        showCupertinoModalPopup<void>(
            context: context,
            builder: (BuildContext context) {
                return CupertinoActionSheet(
                    title: const Text('The title'),
                    message: const Text('Message'),
                    actions: <Widget>[
                        CupertinoActionSheetAction(
                            cursor: SystemMouseCursors.forbidden,
                            child: const Text('One'),
                            onPressed: () {},
                        ),
                    ],
                );
            },
        );
    },
    child: const Text('With Cursor'),
),
```

Fixes https://github.com/flutter/flutter/issues/154792
Part of https://github.com/flutter/flutter/issues/58192

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 1]
```diff
@@ -1215,6 +1215,7 @@ class CupertinoActionSheetAction extends StatefulWidget {
     required this.onPressed,
     this.isDefaultAction = false,
     this.isDestructiveAction = false,
+    this.cursor = MouseCursor.defer,
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1218]: Wondering if we can use `mouseCursor` instead of `cursor` to be consistent with other material/cupertino APIs that offer a configurable mouse cursor. For example, refer to uses of [mouseCursor](https://github.com/search?q=repo%3Aflutter%2Fflutter%20this.mouseCursor&type=code) vs. that of [cursor](https://github.com/search?q=repo%3Aflutter%2Fflutter+this.cursor&type=code).

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 2]
```diff
@@ -1312,7 +1318,7 @@ class _CupertinoActionSheetActionState extends State<CupertinoActionSheetAction>
         + fontSize * _kActionSheetButtonVerticalPaddingFactor;
 
     return MouseRegion(
-      cursor: kIsWeb ? SystemMouseCursors.click : MouseCursor.defer,
+      cursor: kIsWeb ? SystemMouseCursors.click : widget.cursor,
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1321]: Can the cursor be configured to accept `WidgetStateMouseCursor`s? It would be nice to have that functionality added right off the bat.

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 3]
```diff
@@ -1234,6 +1235,11 @@ class CupertinoActionSheetAction extends StatefulWidget {
   /// Destructive buttons have red text.
   final bool isDestructiveAction;
 
+  /// The cursor that will be shown when hovering over the button.
+  ///
+  /// If not passed will default to [MouseCursor.defer] and on web will default to [SystemMouseCursors.click].
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1240]:
```suggestion
  /// Defaults to [MouseCursor.defer], except on web, where this defaults to [SystemMouseCursors.click].
```
'Default' makes 'If not passed' redundant.

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 1 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1218]: sure I can update it to use mouseCursor instead of cursor for consistency

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 2 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: would like some help with this... not sure how to exactly approach it

would it be similar to this pr: https://github.com/flutter/flutter/pull/151788/files

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: Is this better:
```dart
final WidgetStateProperty<MouseCursor> effectiveMouseCursor =
    WidgetStateProperty.resolveWith<MouseCursor>((Set<WidgetState> states) {
      return WidgetStateProperty.resolveAs<MouseCursor?>(widget.mouseCursor, states)
          ?? (kIsWeb && !states.contains(WidgetState.disabled)
              ? SystemMouseCursors.click
              : SystemMouseCursors.basic
          );
    });

    return MouseRegion(
      cursor: effectiveMouseCursor.resolve(<WidgetState>{}),
      child: MetaData(
        metaData: this,
        behavior: HitTestBehavior.opaque,
        child: ConstrainedBox(
          constraints: const BoxConstraints(
            minHeight: _kActionSheetButtonMinHeight,
          ),
          child: Semantics(
            button: true,
            onTap: widget.onPressed,
            child: Padding(
              padding: EdgeInsets.fromLTRB(
                _kActionSheetButtonHorizontalPadding,
                verticalPadding,
                _kActionSheetButtonHorizontalPadding,
                verticalPadding,
              ),
              child: DefaultTextStyle(
                style: style,
                textAlign: TextAlign.center,
                child: Center(child: widget.child),
              ),
            ),
          ),
        ),
      ),
    );

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: Only the `resolveAs` block is needed. The wrapping with `resolveWith` was done in the other PR because the  `buildToggleable` method required its mouse cursor to be a `WidgetStateProperty<MouseCursor>` instead of just a `MouseCursor`. But that is not the case here with `MouseRegion`.

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]:
```dart
final MouseCursor effectiveMouseCursor =
        WidgetStateProperty.resolveAs<MouseCursor?>(widget.mouseCursor, states)
            ?? (kIsWeb && !states.contains(WidgetState.disabled)
            ? SystemMouseCursors.click
            : SystemMouseCursors.basic
        );

    return MouseRegion(
      cursor: effectiveMouseCursor,
```
just a snippet of the code since everything else is pretty much the same

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: I'm not sure CupertinoActionSheetAction has a `states` getter. So checking that an action is not disabled instead should be sufficient.

I recommend playing around with it locally and writing tests until they pass. It's easier to review commits vs comment snippets here and I personally find that playing with a system on my own vastly improves my understanding of it.

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: makes sense, let me play around more and see what best way to do it and will update the pr accordingly.

Thanks

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 1 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart]: making as resolved taken care in most recent PR

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 2 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart]: marking as resolved taken care in recent pr

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 3 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart]: marking as resolved taken care in most recent PR

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 4]
```diff
@@ -1311,8 +1332,19 @@ class _CupertinoActionSheetActionState extends State<CupertinoActionSheetAction>
     final double verticalPadding = _kActionSheetButtonVerticalPaddingBase
         + fontSize * _kActionSheetButtonVerticalPaddingFactor;
 
+    final Set<WidgetState> states = <WidgetState>{
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1335]: Detecting when a `WidgetState` is active is our responsibility. Typically it's done by having different flags that are activated depending on some metric. For example, if we want to track the `scrolledUnder` state, we would have to get the ScrollMetrics of the scroll view and do the math to calculate when the widget has been scrolled under (and when it has, add `WidgetState.scrolledUnder` to `states`.

It's more complex logic than anticipated, so it's okay to leave it out of this PR and handle it subsequently on a case-by-case basis (for each relevant state).

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1335]: oh ok, so do you want me to rollback to the original pr?

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1320]: marking as resolved taken care in recent commit

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 5]
```diff
@@ -1311,8 +1317,12 @@ class _CupertinoActionSheetActionState extends State<CupertinoActionSheetAction>
...
+      WidgetState.hovered
+    };
+
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1323]:
```suggestion
```

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 6]
```diff
@@ -1311,8 +1317,12 @@ class _CupertinoActionSheetActionState extends State<CupertinoActionSheetAction>
...
     return MouseRegion(
-      cursor: kIsWeb ? SystemMouseCursors.click : MouseCursor.defer,
+      cursor: kIsWeb ? SystemMouseCursors.click : widget.mouseCursor,
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1325]: What if a user wants to configure a mouse cursor on web (instead of just click)? The user provided property should always take priority.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 7]
```diff
@@ -1956,6 +1956,41 @@ void main() {
     );
   });
 
+  testWidgets('Hovering over Cupertino action sheet action updates to the passed cursor on desktop', (WidgetTester tester) async {
+    const SystemMouseCursor customCursor = SystemMouseCursors.click;
+
+    await tester.pumpWidget(
+        createAppWithButtonThatLaunchesActionSheet(
+            CupertinoActionSheet(
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1964]: Outdent by two spaces.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 8]
```diff
@@ -1956,6 +1956,41 @@ void main() {
...
+              message: const Text('Message'),
+              actions: <Widget>[
+                CupertinoActionSheetAction(
+                  onPressed: () { },
+                  mouseCursor: customCursor,
+                  child: const Text('One'),
+                ),
+              ],
+            )
+        )
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1975]: Use trailing commas.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 9]
```diff
@@ -1956,6 +1956,41 @@ void main() {
     );
   });
 
+  testWidgets('Hovering over Cupertino action sheet action updates to the passed cursor on desktop', (WidgetTester tester) async {
+    const SystemMouseCursor customCursor = SystemMouseCursors.click;
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1960]: Consider using another cursor to make the logic in the test independent of the "clickable on web" behavior.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 10]
```diff
@@ -1956,6 +1956,41 @@ void main() {
...
+    final TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse, pointer: 1);
+    await gesture.addPointer(location: const Offset(10, 10));
+    await tester.pumpAndSettle();
+
+    final Offset actionSheetAction = tester.getCenter(find.text('One'));
+    await gesture.moveTo(actionSheetAction);
+    await tester.pumpAndSettle();
+    expect(
+      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
+      kIsWeb ? SystemMouseCursors.click : customCursor,
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1990]: If the test is checking that the mouse cursor provided is always respected, then it shouldn't differ in behavior on web vs on other platforms.

Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1990]: will change it so ensure the mouseCursor is always respected instead of checking platform

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 6 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: want a suggestion if I can do the following:
`final MouseCursor webCursor = (kIsWeb && widget.mouseCursor != MouseCursor.defer) ? 
    widget.mouseCursor : SystemMouseCursors.click;`

Since mouseCursor is defaulted to MouseCursor.defer when its web and the mouseCursor is not equal to MouseCursor.defer then we use the cursor passed by the user else we default to SystemMouseCursor.click

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: Instead of making `mouseCursor` default to `MouseCursor.defer` in the constructor, you can make it nullable. Then when setting the `MouseRegion`s cursor, have `mouseCursor` null coalesce to either `.click` on web or `.defer` otherwise.

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 11]
```diff
@@ -1234,6 +1235,14 @@ class CupertinoActionSheetAction extends StatefulWidget {
   /// Destructive buttons have red text.
   final bool isDestructiveAction;
 
+  /// The cursor that will be shown when hovering over the button.
+  ///
+  /// if `null`, cursor will default to:
+  /// - `MouseCursor.click` on web platforms
+  /// - `MouseCursor.defer` on other platforms
+  /// else will use value provided
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1243]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#use-correct-grammar

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 12]
```diff
@@ -1956,6 +1956,41 @@ void main() {
...
+            title: const Text('The title'),
+            message: const Text('Message'),
+            actions: <Widget>[
+              CupertinoActionSheetAction(
+                mouseCursor: customCursor,
+                onPressed: () { },
+                child: const Text('One'),
+              ),
+            ],
+          )
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1974]: Missing a trailing comma.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 13]
```diff
@@ -1956,6 +1956,41 @@ void main() {
     );
   });
 
+  testWidgets('Hovering over Cupertino action sheet action updates cursor to passed cursor on any platform', (WidgetTester tester) async {
+    const SystemMouseCursor customCursor = SystemMouseCursors.click;
+
+    await tester.pumpWidget(
+      createAppWithButtonThatLaunchesActionSheet(
+          CupertinoActionSheet(
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1964]: Outdent entire block by two spaces.

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 14]
```diff
@@ -1956,6 +1956,41 @@ void main() {
...
+    await gesture.addPointer(location: const Offset(10, 10));
+    await tester.pumpAndSettle();
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), SystemMouseCursors.basic);
+
+    final Offset actionSheetAction = tester.getCenter(find.text('One'));
+    await gesture.moveTo(actionSheetAction);
+    await tester.pumpAndSettle();
+    expect(
+      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
+      customCursor
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1990]: Missing a trailing comma.

File: packages/flutter/test/cupertino/action_sheet_test.dart (hunk 9 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: Still uses `.click`.

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 11 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1243]: On a smaller note I'm wondering if there is any need for this comment change compared to the previous comment. Maybe the `if null` prefix?

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1243]: reason I changed the comment was mostly cause we are making the mouse cursor null. But I will rever to the below:

/// The cursor that will be shown when hovering over the button.
///
/// If not passed will default to [MouseCursor.defer] and on web will default to [SystemMouseCursors.click].

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1243]: 'if not passed' and 'defaults' mean the same thing, so it would be redundant to have the 'if not passed' prefix. However, one can imagine a situation where a user passes `null` as the `mouseCursor`. So technically, in that case, something has been passed. But since we are null coalescing, the rest of the statement would apply.

Maybe a better comment would be `If null, defaults to...` Because that would cover the case where a mouse cursor is not passed and thus there is a default and the case where a null mouse cursor is passed.

File: packages/flutter/test/cupertino/action_sheet_test.dart (hunk 13 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1964]: Screenshot 2024-11-07 at 6 11 04 PM
is this indentation ok? On my machine it seems to be indented properly

Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1964]: Screenshot 2024-11-12 at 4 01 16 PM
does this indentation look proper?

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 11 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/dialog.dart:1243]: It seems like a subtle distinction, but it can make a huge difference for a developer trying to debug why a potentially null mouse cursor passed into this widget from somewhere else doesn't change the default to their expected cursor, because in reading the documentation they saw that the defaults are respected only if no mouse cursor is passed in.

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1243]: understood thank you for the comments I have modified it to the following:
/// The cursor that will be shown when hovering over the button.
///
/// if null defaults to [SystemMouseCursors.click] on web else [MouseCursor.defer].

File: packages/flutter/test/cupertino/action_sheet_test.dart (hunk 9 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: This change, although small, is important because if this PR is regressed, and this test is run on web, it would still pass.

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 15]
```diff
@@ -1234,6 +1235,11 @@ class CupertinoActionSheetAction extends StatefulWidget {
   /// Destructive buttons have red text.
   final bool isDestructiveAction;
 
+  /// The cursor that will be shown when hovering over the button.
+  ///
+  /// if null defaults to [SystemMouseCursors.click] on web else [MouseCursor.defer].
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1240]:
```suggestion
  /// If null, defaults to [SystemMouseCursors.click] on web and [MouseCursor.defer] on other platforms.
```
https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#use-correct-grammar

File: packages/flutter/test/cupertino/action_sheet_test.dart (hunk 9 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: oh so for web use a different one like maybe grab and for non web use something like click or forbidden?

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 16]
```diff
@@ -1312,7 +1318,7 @@ class _CupertinoActionSheetActionState extends State<CupertinoActionSheetAction>
         + fontSize * _kActionSheetButtonVerticalPaddingFactor;
 
     return MouseRegion(
-      cursor: kIsWeb ? SystemMouseCursors.click : MouseCursor.defer,
+      cursor: widget.mouseCursor ?? (kIsWeb ? SystemMouseCursors.click : MouseCursor.defer),
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/dialog.dart:1321]: If a CupertinoActionSheetAction is disabled, shouldn't it not become clickable on web?

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/dialog.dart:1321]: I don't think it can be disabled because onClick is defined as required. So passing null or disabling isn't an option. I tried the same and it didn't work

File: packages/flutter/test/cupertino/action_sheet_test.dart (hunk 9 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: There doesn't need to be different cursors per platform. Just one cursor that is definitely not a default.

Correction: The test wouldn't pass either way because we're adding a property to a public API. It would only pass if the changes are regressed in a way that the property is no longer respected.

Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: understood.

So how would I handle it? Still not able to figure that portion out

Comment (victorsanni) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: Replace `.click` with `.grab` or `.forbidden` etc.

Comment (srivats22) [reply packages/flutter/test/cupertino/action_sheet_test.dart:1960]: oh ok will update with that... 

apart from this change, others all look good or any changes still required?

**Comment by victorsanni** [comment]
Fixes https://github.com/flutter/flutter/issues/154792

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 17]
```diff
@@ -1234,6 +1235,11 @@ class CupertinoActionSheetAction extends StatefulWidget {
   /// Destructive buttons have red text.
   final bool isDestructiveAction;
 
+  /// The cursor that will be shown when hovering over the button.
+  ///
+  /// If null, defaults to [SystemMouseCursors.click] on web and [MouseCursor.defer] on other platforms.
```
Comment (TahaTesser) [inline packages/flutter/lib/src/cupertino/dialog.dart:1240]:
```suggestion
  /// If null, defaults to [SystemMouseCursors.click] on web and
  /// [MouseCursor.defer] on other platforms.
```

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 18]
```diff
@@ -1956,6 +1956,41 @@ void main() {
     );
   });
 
+  testWidgets('Hovering over Cupertino action sheet action updates cursor to passed cursor on any platform', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1959]:
```suggestion
  testWidgets('CupertinoActionSheet action cursor behavior', (WidgetTester tester) async {
```

File: packages/flutter/test/cupertino/action_sheet_test.dart [hunk 19]
```diff
@@ -1956,6 +1956,41 @@ void main() {
...
+        ),
+      ),
+    );
+    await tester.tap(find.text('Go'));
+    await tester.pump();
+
+    final TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse, pointer: 1);
+    await gesture.addPointer(location: const Offset(10, 10));
+    await tester.pumpAndSettle();
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), SystemMouseCursors.basic);
```
Comment (TahaTesser) [inline packages/flutter/test/cupertino/action_sheet_test.dart:1983]:
```suggestion
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.basic,
   );
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for the contribution!

**Review by TahaTesser — APPROVED** [review]
LGTM
