### PR TITLE
Fix `PopupMenuButton`'s `IconButton` not inheriting `IconTheme` size

### LINKED ISSUE #100105: PopupMenuButton icon doesn't use icon size from the theme
When setting the iconTheme of the app and then using a PopupMenuButton the PopupMenuButton will display using the themes color but not size.
I expect both the color and size from the theme to be applied unless I specify the iconSize specifically on the PopupMenuButton.

In my case I was using the PopupMenuButton in an AppBar which sets the icon size based on the theme but even with [this fix (#94777)](https://github.com/flutter/flutter/issues/94777) it was showing at the wrong size.

Testing on flutter version 2.10.3

<details>
<summary>Code sample</summary>

I've created an example using dartpad

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
      theme: ThemeData(
        iconTheme: const IconThemeData(
          size: 50,
          color: Colors.blue,
        ),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        iconTheme: const IconThemeData(
          size: 50,
          color: Colors.white,
        ),
        actionsIconTheme: const IconThemeData(
          size: 50,
          color: Colors.red,
        ),
        title: const Text('Material App Bar'),
        actions: <Widget>[
          IconButton(
            icon: const Icon(Icons.help_outline),
            onPressed: () {},
          ),
          PopupMenuButton(
              icon: const Icon(Icons.help_outline),
              itemBuilder: (context) => [
                    const PopupMenuItem(
                      child: Text("First"),
                      value: 1,
                    ),
                    const PopupMenuItem(
                      child: Text("Second"),
                      value: 2,
                    )
                  ]),
          PopupMenuButton(
              icon: const Icon(Icons.help_outline),
              iconSize: 50,
              itemBuilder: (context) => [
                    const PopupMenuItem(
                      child: Text("First"),
                      value: 1,
                    ),
                    const PopupMenuItem(
                      child: Text("Second"),
                      value: 2,
                    )
                  ]),
        ],
      ),
      body: Center(
        child: PopupMenuButton(
            icon: const Icon(Icons.help_outline),
            itemBuilder: (context) => [
                  const PopupMenuItem(
                    child: Text("First"),
                    value: 1,
                  ),
                  const PopupMenuItem(
                    child: Text("Second"),
                    value: 2,
                  )
                ]),
      ),
    );
  }
}
```

With the above code I would expect all the app bar icons to be the same size (50). 
The icon in the middle of the screen should also be the size of the large app bar icons. You can see the blue color from the theme is applied but not the size.
image

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/100105

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -1212,7 +1215,7 @@ class PopupMenuButtonState<T> extends State<PopupMenuButton<T>> {
       icon: widget.icon ?? Icon(Icons.adaptive.more),
       padding: widget.padding,
       splashRadius: widget.splashRadius,
-      iconSize: widget.iconSize ?? 24.0,
+      iconSize: widget.iconSize ?? iconTheme.size ?? 24.0,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/popup_menu.dart:1218]: Can we make the "24.0" into a private constant at the top of this file?  e.g. `_kDefaultIconSize`

File: packages/flutter/test/material/popup_menu_test.dart [hunk 2]
```diff
@@ -2698,6 +2698,33 @@ void main() {
 
     expect(tester.getTopLeft(find.byWidgetPredicate((Widget w) => '${w.runtimeType}' == '_PopupMenu<int?>')), const Offset(8.0, 90.0));
   });
+
+  testWidgets("PopupMenuButton icon inherits IconTheme's size", (WidgetTester tester) async {
```
Comment (gspencergoog) [inline packages/flutter/test/material/popup_menu_test.dart:2702]: It would also be good to test explicitly setting the icons size in the widget, and the 24 pixel fallback.

**Review by gspencergoog — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart]: Updated test to check default icon size, theme icon size, and icon size parameter, also added comments in the test.

File: packages/flutter/test/material/popup_menu_test.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/test/material/popup_menu_test.dart:2702]: Done)

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
