### PR TITLE
Validate style in TextField

### LINKED ISSUE #8728: App crashes if I set a textStyle without fontSize to a Textfield
I was trying to set a style to a Textfield, and app crashed. The simplest example  to reproduce : 

## Steps to Reproduce

```dart
runApp(new MaterialApp(
      home: new Material(
          child: new Stack(children: [
    new Center(
        child: new TextField(
            key: new UniqueKey(),
            labelText: "test",
            style: new TextStyle(color: Colors.green[400])))
  ]))));
```

I found that if you set the fontSize in this example, it works. 

```dart
runApp(new MaterialApp(
      home: new Material(
          child: new Stack(children: [
    new Center(
        child: new TextField(
            key: new UniqueKey(),
            labelText: "test",
            style: new TextStyle(color: Colors.green[400], fontSize:20.0)))
  ]))));
```

## Logs

```
Launching lib/main.dart on A3 A40 in debug mode...
Built app-debug.apk (22.0MB).
Uninstalling old version...
I/flutter (26901): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (26901): The following NoSuchMethodError was thrown building InputContainer(dirty; state:
I/flutter (26901): _InputContainerState#598055191()):
I/flutter (26901): The method 'toDouble' was called on null.
I/flutter (26901): Receiver: null
I/flutter (26901): Tried calling: toDouble()
I/flutter (26901): When the exception was thrown, this was the stack:
I/flutter (26901): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter (26901): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter (26901): #2      double.+ (dart:core-patch/double.dart:16)
I/flutter (26901): #3      _InputContainerState.build (package:flutter/src/material/input.dart:290)
I/flutter (26901): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3185)
I/flutter (26901): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3098)
I/flutter (26901): #6      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #13     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #25     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #32     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #38     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #45     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #53     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4139)
I/flutter (26901): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #57     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #63     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #73     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #82     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #91     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #97     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #104    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #111    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #113    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #117    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #118    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #119    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #122    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #129    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #131    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #136    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #145    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #149    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #151    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #154    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #158    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #160    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #165    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #167    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #172    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #174    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #177    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4139)
I/flutter (26901): #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #180    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:491)
I/flutter (26901): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #184    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #191    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #196    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #200    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #202    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #203    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #204    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #206    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #209    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #213    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #215    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #218    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #220    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #226    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #228    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #230    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #232    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #233    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #238    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #239    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #240    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #241    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #242    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #243    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4036)
I/flutter (26901): #244    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #245    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #247    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #248    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #249    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #250    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #251    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #253    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #254    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #255    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #256    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #257    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #259    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #260    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #261    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #262    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #263    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #264    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #266    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #267    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #268    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #269    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #270    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #272    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #273    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #274    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #275    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #276    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #277    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #279    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #280    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #281    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #282    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #283    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #284    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3110)
I/flutter (26901): #285    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:3000)
I/flutter (26901): #286    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3078)
I/flutter (26901): #287    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3213)
I/flutter (26901): #288    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3073)
I/flutter (26901): #289    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2464)
I/flutter (26901): #290    Element.updateChild (package:flutter/src/widgets/framework.dart:2267)
I/flutter (26901): #291    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:555)
I/flutter (26901): #292    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:526)
I/flutter (26901): #293    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:472)
I/flutter (26901): #294    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1834)
I/flutter (26901): #295    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:471)
I/flutter (26901): #296    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:372)
I/flutter (26901): #297    runApp (package:flutter/src/widgets/binding.dart:404)
I/flutter (26901): #298    main (file:///Users/rxlabz/projects/YTBX017/dev/protos/ytx017-flutter-client-proto/lib/main.dart:22)
I/flutter (26901): #299    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
I/flutter (26901): #300    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
I/flutter (26901): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
/Users/rxlabz/dev/tools/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 60c0c3d323 (3 days ago), 2017-03-10 13:43:57
    • Engine revision 6e54f5e31f
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.5)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[-] IntelliJ IDEA Ultimate Edition (version 2017.1 EAP)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] WebStorm (version 2017.1 Beta)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • A3 A40 • 622004271815 • android-arm • Android 6.0 (API 23)
```

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/8728
Related to https://github.com/flutter/flutter/issues/23994

This improves the error message as discussed in https://github.com/flutter/flutter/pull/24449

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -569,6 +569,11 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     assert(debugCheckHasDirectionality(context));
     final ThemeData themeData = Theme.of(context);
     final TextStyle style = widget.style ?? themeData.textTheme.subhead;
+
+    if (style.inherit == false && (style.fontSize == null || style.textBaseline == null)) {
+      throw FlutterError('Style must supply fontSize and textBaseline when inherit is false.');
+    }
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart]: @HansMuller Is this a good place to do this validation? It seemed like I couldn't do it in the constructor since it's const, is that right?

**Comment by justinmc** [comment]
Some problems with making commits from my laptop instead of my desktop :)

File: packages/flutter/lib/src/material/text_field.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/text_field.dart]: I think this check could be a TextField constructor assert. Something like:
```
assert(style == null || style.inherit || (style.fontSize != null && style.textBaseline != null), 'style must supply ...')
```

Comment (justinmc) [reply packages/flutter/lib/src/material/text_field.dart]: I get errors when I try to access `style.something` in the initializers list, since TextField is a const constructor.  I also can't give the constructor a body for the same reason.  I don't fully understand the limitations on const constructors though, I'll play around with it and see if I can get something to work.

Comment (HansMuller) [reply packages/flutter/lib/src/material/text_field.dart]: Right, my bad. Method calls can't be "const evaluated". This assert will need to happen at build time.

File: packages/flutter/lib/src/material/text_field.dart [hunk 2]
```diff
@@ -569,6 +569,11 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     assert(debugCheckHasDirectionality(context));
     final ThemeData themeData = Theme.of(context);
     final TextStyle style = widget.style ?? themeData.textTheme.subhead;
+
+    if (style.inherit == false && (style.fontSize == null || style.textBaseline == null)) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_field.dart]: This should be an assert and it would be OK to assume that textTheme.subhead is fully specified. That way, if the assert fails, it's clear that it's about the style value provided to the TextField

**Comment by justinmc** [comment]
@HansMuller updated to be an assert.

File: packages/flutter/lib/src/material/text_field.dart [hunk 3]
```diff
@@ -567,6 +567,12 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     // TODO(jonahwilliams): uncomment out this check once we have migrated tests.
     // assert(debugCheckHasMaterialLocalizations(context));
     assert(debugCheckHasDirectionality(context));
+    final bool styleNotInherited = widget.style != null && widget.style.inherit == false;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_field.dart]: This might be a little clearer as one expression (we usually don't introduce variables that are only referred to in an assert). Also, the message should mention that it depends on `inherit false`.
```
assert(
  !(widget.style != null && widget.style.inherit == false &&
     (widget.style.fontSize == null || widget.style.textBaseline == null)),
  'inherit false style must supply fontSize and textBaseline',
);
```

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -3382,4 +3382,35 @@ void main() {
...
+      return MaterialApp(
+        home: Material(
+          child: TextField(
+            style: style,
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildFrame(const TextStyle(
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart]: I think what you want here is:
````
expect(buildFrame(...), throwsAssertionError);
```

Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Talked to Hans and it seems we can't do it this way because `build` will never be called.

**Comment by justinmc** [comment]
@HansMuller Fixed the assertion and ready for another review.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
Ready for merge after the code freeze.
