### PR TITLE
Dismiss Modal Barrier on `handleTapCancel` 

### LINKED ISSUE #90223: [PopUpMenuButton] When the menu is open, scroll gesture doesn't dismiss the modal barrier
## Steps to Reproduce

This is the minimal code required to reproduce it, open the popup menu from the AppBar and attempt to scroll the ListView behind it. Only possible actions are either tap anywhere outside the popup menu to dismiss it or select an item. Scrolling the background ListView should be possible. Optionally, we should be able to set the behaviour for this, we could have this default behavior (only possible actions are to tap to close or select item), close on any action (not just tap, any gesture, like drag) or pass through the gesture (let the gesture be passed down if not captured by the pop-up menu).

``` dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Example'),
        actions: [
          PopupMenuButton<int>(
            icon: const Icon(Icons.view_list_rounded),
            onSelected: (_) {},
            itemBuilder: (context) => List.generate(
              100,
              (i) => PopupMenuItem(
                child: Text('Pop Up Menu Item $i'),
                value: i,
              ),
            ),
          ),
        ],
      ),
      body: ListView(
        children: List.generate(
          100,
          (i) => ListTile(
            title: Text('Sample item $i'),
          ),
        ),
      ),
    );
  }
}
```

<details>
  <summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1237],
    locale en-CA)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700        
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = D:\Android
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\nosmi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version      
      10.0.19043.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.47      

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
Fixes https://github.com/flutter/flutter/issues/90223

This PR adds dismiss callback to onTapCancel modal barrier.

### Native

https://user-images.githubusercontent.com/48603081/153480378-b26ef604-555c-485e-97c4-389b7b1f20dd.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/modal_barrier.dart [hunk 1]
```diff
@@ -228,12 +229,16 @@ class _AnyTapGestureRecognizer extends BaseTapGestureRecognizer {
     : super(debugOwner: debugOwner);
 
   VoidCallback? onAnyTapUp;
+  VoidCallback? onAnyTapCancel;
 
   @protected
   @override
   bool isPointerAllowed(PointerDownEvent event) {
-    if (onAnyTapUp == null)
+    if (onAnyTapUp == null) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/modal_barrier.dart:237]: This can be merged into one

File: packages/flutter/lib/src/widgets/modal_barrier.dart [hunk 2]
```diff
@@ -228,12 +229,16 @@ class _AnyTapGestureRecognizer extends BaseTapGestureRecognizer {
...
       return false;
+    } else if (onAnyTapCancel == null) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/modal_barrier.dart:239]: The current logic return false if one of onAnyTapUp and onAnyTapCancel is null, maybe they should be &&?

File: packages/flutter/lib/src/widgets/modal_barrier.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/widgets/modal_barrier.dart]: Just merged the conditions

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
This change does not causes a regression.
repro:
https://gist.github.com/chunhtai/db68a074f63f96fe2b997597599ebbbb
1. tap show dialog
2. tap and hold one finger on modal barrier without lifting it.
3. use other finger to tap `ok`

expect: alert dialog is dismissed and page stays at /abc
actual: alert dialog is dismissed, page /abc is popped

Preparing for revert.

**Comment by nosmirck** [comment]
Since the original issue #90233 is locked, I'm adding a few things.

If I'm not mistaken, the last time I saw the code for the popup it's using a ModalBarrier which is used on other types of popups (like dialogues). I believe it should have its own barrier, one that closes as soon as an interaction outside the popu menu is done.

Take for example the Gmail App on Android.

Here is an example of the drawer menu:


If you hold the barrier or drag up/down it stays open. It closes by a right to left gesture (even initiated from the barrier) or a single tap on the barrier.



This pop up to switch accounts. Stats open with hold or drags on the barrier but a single tap closes it.



Finally this pop-up menu that opens when tapping the meatballs menu on the top right of the email. Any gesture outside of it closes it, as soon as the screen is touched (tap down) it closes immediately. There's no way to keep it open when interacting with anything outside of the menu.

Now, the main reason I opened this issue is because I have had users complain that the app is frozen on a screen and sent me screenshots of a screen very similar to the last screenshot, where they open a pop-up menu that allows them to have multiple selections while open and then they try to scroll the screen behind it, the popup doesn't close and the screen behind doesn't scroll, which gives them the feeling that the app is frozen. Also, it's unbelievable the amount of people that think that to close a popup menu like the one in the third screenshot they have to "swipe up" instead of just a tap.

I have had reports of people trying to get back to the screen for several minutes before filing the support ticket and even sent recorded videos of them picking options from the menu (which doesn't close since it's just picking on/off options) and then swiping outside the menu several times, fast and slow, in every direction but never tapping the screen with a single tap, believing somehow that the app is frozen and only the menu is interactive until they have to force close the app and reopen.

My issue is temporarily resolved because I implemented a custom popup menu that closes as soon as a gesture is detected on the custom barrier, but it's a mess of a code, only works with my data.

Then I tried the same thing on web and it's even worse.

You'd expect that when you have a popup menu open and scroll with the mousewheel, that at least the content behind scrolls freely, but no. (Like it does here in GitHub if you click the meatballs menu on the top right of this comment and then scroll up/down). On some pages, this behaves differently. Some retain the menu in place relative to the initial position where it opened, others keep it attached to the button that originated the menu and others close it immediately. O have a couple of examples, like using Google docs and opening one of the context menu options (file, edit) then scrolling the page below, or clicking the options menu in chrome and scrolling the page while open (it closes).

I believe that the Material Design guidelines states that a popup menu should close with any gesture, but dialogs can remain open unless dismissable with a tap on the barrier, but I'm not sure about this, it's just the behaviour I've see on apps like Google Play Store and Gmail, while other apps have alight modifications (like the steam app, where some popup menus on the screen remain open and attached to the button that originated it while allowing for scrolling of the whole content).

In any case, the current implementation doesn't allow anything but the same behavior than dialogs, which is dismiss with a tap where it should, at least, provide a few options (like close any gesture or passthrough, maybe with options to remain open relative to screen or attached to the button that opened it).

**Comment by chunhtai** [comment]
I didn't mean the current behavior is correct. The reason the change is reverted is that it introduced a different issue. We should find a find a fix that does not cause other regression.
