### PR TITLE
[web] fix text selection offset in multi-line fields

### LINKED ISSUE #162698: [Web] Click-and-drag to select text in TextField is offset until ending gesture
### Steps to reproduce

1. Run code sample on a browser
2. Paste a long text in the TextField
3. Click-and-drag to select text (portrait aspect ratio is more noticeable)

### Expected results

Text is selected exactly where the mouse is.

### Actual results

Selection is offset on the Y axis depending on the height/width of the viewport. When the mouse drag ends, the selection is fixed automatically.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(maxLines: null),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/ad6b476d-3860-4bd0-87e7-5bb1bfdd8314

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.3, on Microsoft Windows [Version 10.0.26100.2894], locale en-150)
    • Flutter version 3.27.3 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (2 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\dev\AndroidSDK\
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome Beta\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35527.113
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code, 64-bit edition (version 1.96.4)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.104.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.2894]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 132.0.2957.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/162698

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/input_type.dart [hunk 1]
```diff
@@ -184,5 +184,12 @@ class MultilineInputType extends EngineInputType {
   String? get inputmodeAttribute => null;
 
   @override
-  DomHTMLElement createDomElement() => createDomHTMLTextAreaElement();
+  DomHTMLElement createDomElement() => createMultilineTextArea();
+}
+
+DomHTMLTextAreaElement createMultilineTextArea() {
+  final element = createDomHTMLTextAreaElement();
+  // Scrollbar width affects text layout. This zeros out the scrollbar width.
```
Comment (loic-sharma) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/input_type.dart:192]: Most pedantic nit in the world, I'm sorry: 😂 

```suggestion
  // Scrollbar width affects text layout. This zeroes out the scrollbar width.
```

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 2]
```diff
@@ -840,6 +840,45 @@ Future<void> testMain() async {
...
+
+        // Should contain one <input type="text"> and one <input type="submit">
+        expect(formElement.children, hasLength(2));
+
+        final inputElement = formElement.children.first;
+        expect(inputElement.style.alignContent, isEmpty);
+
+        final submitElement = formElement.children.last;
+        expect(submitElement.style.alignContent, isEmpty);
+      }
```
Comment (justinmc) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:873]: I like this use of blocks to isolate variables, I might start doing this in tests...

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

So the text in the underlying HTML input was not in the same position as Flutter's text because the HTML input had scrollbars and was aligned differently? Makes sense assuming this fixes the bug in the issue.

I guess it's not possible to write a test that reproduces the actual bug in the issue since the problem was with the engine.

The Google test failures seem to be an infrastructure problem of some sort.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/input_type.dart (hunk 1 above)
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/input_type.dart]: Done

**Comment by yjbanov** [comment]
> So the text in the underlying HTML input was not in the same position as Flutter's text because the HTML input had scrollbars and was aligned differently? Makes sense assuming this fixes the bug in the issue.

It fixes the issue in my local testing. However, if you ask why it fixes it, I don't have a good explanation. My best guess is that the misalignment of the start of the text (top-left corner in LTR, and top-right in RTL) confuses the browser about start-end selection regions vs pointer events.

> I guess it's not possible to write a test that reproduces the actual bug in the issue since the problem was with the engine.

The challenge is that we're not able to dispatch pointer events in a way that would reproduce text selection in a way it happens in reality. There's some gnarly interaction between Flutter's `EditableText` and the underlying `<input>` element. I'm not aware of a way to synthesize events that would interact the same way.

> The Google test failures seem to be an infrastructure problem of some sort.

Yeah, I'm guessing we still don't know how to test engine code changes in the monorepo world.
