### PR TITLE
Fix text selection handles showing outside the visible text region

### LINKED ISSUE #24214: Text selection handles display outside visible text region
This can be reproduced by selecting a word and scrolling so that the word is outside the visible area of the screen. These two screenshots demonstrate:

before
after

On Android, the behavior is that the handles disappear (atomically) when the position they point to leaves view, and reappear (atomically) when the position re-enters view. The following screenshots demonstrate how that would look instead:

left_hidden
right_hidden
both_hidden

In the last example, the right handle is completely invisible, even though it points to just after then "n" in "brown", which is barely off the screen. This illustrates the Android behavior that the handles are either completely visible or completely invisible (never clipped).

@GaryQian

### PR DESCRIPTION
**Pull request by sjindel-google**
This follows the Android behavior that the text selection handles fade in and out when they enter/leave the viewport of the text, remaining clamped within the viewport and not drawing outside of it.

This also fixes an issue with gestures being incorrectly shifted after scrolling.

fixes #24214

### CODE REVIEW

**Review by justinmc — DISMISSED** [review]
Just a few small comments here, but someone else more knowledgeable should take a look at the overall approach to `PaintVisibility` etc.

I wanted to point out some slight difference in behavior from native Android as well.  This PR continues to show the context menu even when both handles are hidden, but natively the context menu disappears in that case.

screen shot 2019-01-04 at 4 53 24 pm

Also, natively there is a fade animation when a handle disappears/reappears that we might want to consider adding to this PR.

handles

I mentioned this in the related issue, ~~but iOS also might be a concern for this bug.  Natively it's not possible to cause a selection to not be visible, but in our implementation in iOS it looks like it is.~~ iOS is a concern for this bug as well.  It's possible to scroll the handles off screen in a native iOS app.

I'm not sure how accurate we want to be in this PR or if we want to put off minor details like those to future PRs.

**Comment by GaryQian** [comment]
cc @Hixie for potential API additions

**Comment by tvolkert** [comment]
Also +cc @goderbauer

**Review by goderbauer — COMMENTED** [review]
Thinking out loud: Why can we not just use a regular setState to change the visibility of a `Visibility` widget to hide the selectors when the textfield determines that they will not be visible anymore? Sure, we may be a frame late, but since the fade-out is supposed to be animated anyways it may not be noticeable?

**Comment by goderbauer** [comment]
@sjindel-google I know this PR is pretty old and I apologize for the delay in reviewing it. Is this still something you plan to work on? Or should we close it for now? I would like to remove stale PRs from our backlog so we can get to new ones quicker in the future.

**Comment by sjindel-google** [comment]
> @sjindel-google I know this PR is pretty old and I apologize for the delay in reviewing it. Is this still something you plan to work on? Or should we close it for now? I would like to remove stale PRs from our backlog so we can get to new ones quicker in the future.

I will work on it. Sorry that I haven't been able to respond to your comments yet, but I'm back from vacation/offsite on Monday and will pick it up around then.

**Comment by sjindel-google** [comment]
> Thinking out loud: Why can we not just use a regular setState to change the visibility of a `Visibility` widget to hide the selectors when the textfield determines that they will not be visible anymore? Sure, we may be a frame late, but since the fade-out is supposed to be animated anyways it may not be noticeable?

I tried this approach first, but I hit an assert in `_handleBuildScheduled()`:

```dart
    assert(() {
      if (debugBuildingDirtyElements) {
        throw FlutterError(
          'Build scheduled during frame.\n'
          'While the widget tree was being built, laid out, and painted, '
          'a new frame was scheduled to rebuild the widget tree. '
          'This might be because setState() was called from a layout or '
          'paint callback. '
          'If a change is needed to the widget tree, it should be applied '
          'as the tree is being built. Scheduling a change for the subsequent '
          'frame instead results in an interface that lags behind by one frame. '
          'If this was done to make your build dependent on a size measured at '
          'layout time, consider using a LayoutBuilder, CustomSingleChildLayout, '
          'or CustomMultiChildLayout. If, on the other hand, the one frame delay '
          'is the desired effect, for example because this is an '
          'animation, consider scheduling the frame in a post-frame callback '
          'using SchedulerBinding.addPostFrameCallback or '
          'using an AnimationController to trigger the animation.'
        );
      }
      return true;
    }());
```

**Comment by goderbauer** [comment]
Looking at @justinmc's earlier comment, isn't the AnimationController mentioned in that assert exactly what you want to get around that limitation to fade the controls in/out over the next couple of frames?

**Comment by sjindel-google** [comment]
> Looking at @justinmc's earlier comment, isn't the AnimationController mentioned in that assert exactly what you want to get around that limitation to fade the controls in/out over the next couple of frames?

I'll give that approach a shot.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -60,6 +60,11 @@ enum SelectionChangedCause {
 /// Used by [RenderEditable.onCaretChanged].
 typedef CaretChangedHandler = void Function(Rect caretRect);
 
+/// Signature for the callback that reports when the visibility of either extent
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -227,6 +233,41 @@ class RenderEditable extends RenderBox {
 
   Rect _lastCaretRect;
 
+  bool _startSelectionExtentVisible = true;
+  bool _endSelectionExtentVisible = true;
+
+  /// Invoked whenever the visbility of the start or end of the selection
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 3]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+/// whenever the visibility might change.
+///
+/// This is used for example to hide an overlay which points to an object when
+/// the object is scrolled out of view.
+class PaintVisibility extends SingleChildRenderObjectWidget {
+  /// Creates a widget whose child's visibility can be controlled during the
+  /// paint phase. The [visibility] argument must not be null.
+  const PaintVisibility({
+    Key key,
+    @required
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility` and `RenderVisibility`.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 1 above)
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 4]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+/// This allows the visibility of a child to be determined at paint time, which
+/// cannot be achieved with [Visibility] because the paint phase happens after
+/// the build and layout phases. Make sure that this widget will be repained
+/// whenever the visibility might change.
+///
+/// This is used for example to hide an overlay which points to an object when
+/// the object is scrolled out of view.
+class PaintVisibility extends SingleChildRenderObjectWidget {
+  /// Creates a widget whose child's visibility can be controlled during the
+  /// paint phase. The [visibility] argument must not be null.
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility`.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 5]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+
+class _RenderVisibility extends RenderProxyBox {
+  _RenderVisibility({
+    @required this.visibility,
+    RenderBox child,
+  }) : super(child);
+
+  ValueListenable<bool> visibility = ValueNotifier<bool>(true);
+
+  @override void paint(PaintingContext context, Offset offset) {
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility`.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 6]
```diff
@@ -221,6 +222,9 @@ class TextSelectionOverlay {
   /// Creates an object that manages overly entries for selection handles.
   ///
   /// The [context] must not be null and must have an [Overlay] as an ancestor.
+  ///
+  /// 'selectionStartInView' and 'selectionEndInView' are optional and can be
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: I noticed that the `_TextSelectionHandleOverlayState` has direct access to the `RenderEditable`, so I've removed these callbacks and typedefs since it's not needed to thread this through `EditableTextState` and `TextSelectionOverlay`.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 7]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+  /// paint phase. The [visibility] argument must not be null.
+  const PaintVisibility({
+    Key key,
+    @required
+    this.visibility,
+    Widget child,
+  }) : super(key: key, child: child);
+
+  /// Controls whether the child is visible.
+  final ValueListenable<bool> visibility;
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: Fixed, now the AnimationController will be triggered by it (in another file).

File: packages/flutter/lib/src/widgets/basic.dart [hunk 8]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
   Widget build(BuildContext context) => widget.builder(context, setState);
 }
+
+/// Control the visibility of a child during the paint phase.
+///
+/// In most cases [Visibility] is a better choice than this widget.
+///
+/// This allows the visibility of a child to be determined at paint time, which
+/// cannot be achieved with [Visibility] because the paint phase happens after
+/// the build and layout phases. Make sure that this widget will be repained
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility` so this is not a concern anymore.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 9]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+/// whenever the visibility might change.
+///
+/// This is used for example to hide an overlay which points to an object when
+/// the object is scrolled out of view.
+class PaintVisibility extends SingleChildRenderObjectWidget {
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility` so this is not a concern anymore.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 10]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+  }
+
+  @override
+  void updateRenderObject(BuildContext context, _RenderVisibility renderObject) {
+    renderObject
+      ..visibility = visibility;
+  }
+}
+
+class _RenderVisibility extends RenderProxyBox {
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility` so this is not a concern anymore.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 11]
```diff
@@ -5835,3 +5835,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+///
+/// This allows the visibility of a child to be determined at paint time, which
+/// cannot be achieved with [Visibility] because the paint phase happens after
+/// the build and layout phases. Make sure that this widget will be repained
+/// whenever the visibility might change.
+///
+/// This is used for example to hide an overlay which points to an object when
+/// the object is scrolled out of view.
+class PaintVisibility extends SingleChildRenderObjectWidget {
+  /// Creates a widget whose child's visibility can be controlled during the
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/basic.dart]: I've removed `PaintVisibility` so this is not a concern anymore.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 12]
```diff
@@ -1979,6 +1979,81 @@ testWidgets(
     ));
     expect(called, 2);
   });
+
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/test/widgets/editable_text_test.dart]: I've removed `PaintVisibility`.

**Comment by sjindel-google** [comment]
I've removed `PaintVisibility` in favor of the `AnimationController` solution, and implemented animation.
I've also merged it with the animation for fading in the handles when they first appear.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 13]
```diff
@@ -10,6 +10,7 @@ import 'package:flutter/services.dart';
 import 'package:flutter/scheduler.dart';
 import 'package:flutter/gestures.dart' show DragStartBehavior;
 
+import '../foundation/change_notifier.dart';
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_selection.dart]: import should be :`package:flutter/foundation.dart`

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 14]
```diff
@@ -372,33 +372,29 @@ class TextSelectionOverlay {
...
+    return _TextSelectionHandleOverlay(
+      onSelectionHandleChanged: (TextSelection newSelection) { _handleSelectionHandleChanged(newSelection, position); },
+      onSelectionHandleTapped: _handleSelectionHandleTapped,
+      layerLink: layerLink,
+      renderObject: renderObject,
+      selection: _selection,
+      selectionControls: selectionControls,
+      position: position,
+      dragStartBehavior: dragStartBehavior,
+      vsync: Overlay.of(context),
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_selection.dart]: Can you not just get this with `Overlay.of` from within the _TextSelectionHandleOverlay?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 15]
```diff
@@ -546,31 +585,36 @@ class _TextSelectionHandleOverlayState extends State<_TextSelectionHandleOverlay
         break;
     }
 
+    point = widget.renderObject.clampToViewport(point);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_selection.dart]: For my own understanding: Why is this necessary?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 16]
```diff
@@ -249,6 +249,41 @@ class RenderEditable extends RenderBox {
...
+  /// will become 'true'.
+  final ValueNotifier<bool> selectionStartInView = ValueNotifier<bool>(true);
+
+  /// Track the visbility of the end of the selected text.
+  ///
+  /// For example, if the text contains "Hello World", and the user selects
+  /// "World", then scrolls so only "Hello" is visible, this will become
+  /// 'false'. If the user scrolls back so that the "d" is visible again, this
+  /// will become 'true'.
+  final ValueNotifier<bool> selectionEndInView = ValueNotifier<bool>(true);
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: we should probably add a paragraph to these two defining "visibility" as meaning "scrolled so that the selection is within the text field viewport", as opposed to being literally visible on the screen.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 17]
```diff
@@ -249,6 +249,41 @@ class RenderEditable extends RenderBox {
...
+    final bool startExtentVisible = visibleRegion.contains(
+        _textPainter.getOffsetForCaret(
+            TextPosition(offset: _selection.start, affinity: _selection.affinity),
+            Rect.zero) +
+        effectiveOffset);
+
+    final bool endExtentVisible = visibleRegion.contains(
+        _textPainter.getOffsetForCaret(
+            TextPosition(offset: _selection.end, affinity: _selection.affinity),
+            Rect.zero) +
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: nit: flutter style; see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 6 above)
[the remark this answers is not in the document]
Comment (Hixie) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Looks like the documentation wasn't removed at the same time

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 18]
```diff
@@ -487,6 +485,47 @@ class _TextSelectionHandleOverlay extends StatefulWidget {
...
+        return widget.renderObject.selectionEndInView;
+    }
+    return null;
+  }
+
+  @override
+  void initState() {
+    super.initState();
+
+    _controller = AnimationController(duration: _fadeDuration, vsync: widget.vsync)..value = 0.0;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/text_selection.dart]: value should start at 0.0, no need to set it

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 19]
```diff
@@ -468,6 +464,7 @@ class _TextSelectionHandleOverlay extends StatefulWidget {
     @required this.onSelectionHandleChanged,
     @required this.onSelectionHandleTapped,
     @required this.selectionControls,
+    @required this.vsync,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/text_selection.dart]: rather than taking a vsync, use TickerProviderSingleStateMixin

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 20]
```diff
@@ -1998,6 +1998,65 @@ void main() {
...
+    // Drag the text all the way to the left so the first word is not visible at
+    // all (and the second word is fully visible). Both handles should be
+    // invisible now.
+    await tester.drag(find.byKey(editableTextKey), const Offset(-400, 0));
+    await tester.pump();
+    verifyVisibility(false, false);
+
+    // TODO(sjindel): Test dragging in the other direction (blocked by
+    // https://github.com/flutter/flutter/issues/27948).
```
Comment (Hixie) [inline packages/flutter/test/widgets/editable_text_test.dart]: please embrace the yak shave and fix that bug too, so that you can write the test

File: packages/flutter/lib/src/rendering/editable.dart [hunk 21]
```diff
@@ -1029,6 +1064,26 @@ class RenderEditable extends RenderBox {
...
+          return Offset(point.dx.clamp(0.0, _viewportExtent), point.dy);
+        break;
+      case Axis.vertical:
+        final double dy = point.dy.clamp(0.0, _viewportExtent);
+        if (dy != point.dy)
+          return Offset(point.dy, point.dy.clamp(0.0, _viewportExtent));
+        break;
+    }
+    return point;
+  }
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: you should test this logic works.
for example, have a test that:
1. selects a word, verifies that opacity is 0.0, waits a second, verifies that opacity is 1.0.
2. scrolls the text field, keeping the handle in the text field, verifies that opacity is 1.0 and in the right place.
3. scrolls the text field, move the handle out. verify that opacity is 1.0 and in the right place (not outside field)
4. waits a tiny bit, verifies that opacity is 0.5 and still in the same place
5. scroll the handle back in, check that opacity is 0.5 but it's no longer stuck on the edge
6. etc

File: packages/flutter/lib/src/rendering/editable.dart [hunk 22]
```diff
@@ -249,6 +249,41 @@ class RenderEditable extends RenderBox {
 
   Rect _lastCaretRect;
 
+  /// Track the visbility of the start of the selected text.
+  ///
+  /// For example, if the text contains "Hello World", and the user selects
+  /// "Hello", then scrolls so only "World" is visible, this will become
+  /// 'false'. If the user scrolls back so that the "H" is visible again, this
+  /// will become 'true'.
+  final ValueNotifier<bool> selectionStartInView = ValueNotifier<bool>(true);
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: you should expose a `ValueListenable<bool>` and have the `ValueNotifier` be private. Otherwise other code can affect the value.

**Review by goderbauer — COMMENTED** [review]
I like this better :)

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 20 above)
Comment (sjindel-google) [reply packages/flutter/test/widgets/editable_text_test.dart]: Done.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 16 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 18 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Done.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 17 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 19 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Done. For my own enlightenment, why is this better? I was previously just using the same ticker provider as the existing fade-in animation.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 22 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Given Hixie's remark above, and the new explanation in the comment, I think this name more precise. I've changed "InView" to "InViewport" to be even more clear.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 23]
```diff
@@ -249,6 +249,41 @@ class RenderEditable extends RenderBox {
...
+  /// "World", then scrolls so only "Hello" is visible, this will become
+  /// 'false'. If the user scrolls back so that the "d" is visible again, this
+  /// will become 'true'.
+  final ValueNotifier<bool> selectionEndInView = ValueNotifier<bool>(true);
+
+  void _updateSelectionExtentsVisibility(Offset effectiveOffset) {
+    final Rect visibleRegion = Offset.zero & size;
+
+    final bool startExtentVisible = visibleRegion.contains(
+        _textPainter.getOffsetForCaret(
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 24]
```diff
@@ -1029,6 +1064,26 @@ class RenderEditable extends RenderBox {
     return null;
   }
 
+  /// Clamps a local coordinate within the viewport.
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 25]
```diff
@@ -1029,6 +1064,26 @@ class RenderEditable extends RenderBox {
...
+  ///
+  /// This is used for example to prevent the text selection handles from
+  /// displaying outside the viewport while fading out.
+  Offset clampToViewport(Offset point) {
+    switch (_viewportAxis) {
+      case Axis.horizontal:
+        final double dx = point.dx.clamp(0.0, _viewportExtent);
+        if (dx != point.dx)
+          return Offset(point.dx.clamp(0.0, _viewportExtent), point.dy);
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: As far as I understand, this isn't possible currently if the input coordinate is coming from `RenderEditable.getEndpointsForSelection`, because the text only scrolls in one direction (either vertically or horizontally, but not both), and therefore a handle can only be outside the viewport along one axis.

However, I realized that the code is simpler is I just use `size.contains` from the enclosing `RenderEditable`, so I've just removed this function altogether.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 26]
```diff
@@ -222,6 +223,9 @@ class TextSelectionOverlay {
   /// Creates an object that manages overly entries for selection handles.
   ///
   /// The [context] must not be null and must have an [Overlay] as an ancestor.
+  ///
+  /// 'selectionStartInView' and 'selectionEndInView' are optional and can be
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Removed.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 13 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Done.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 14 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Removed since using `SingleTickerProviderStateMixin`.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 15 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: This prevents the handles from drawing outside the box while they're fading out:

before

Instead we get:

after

The second is more similar to the native behavior on Android, and I think it looks better than the first.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 21 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: I've updated the current test to do check the positioning and animations.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 27]
```diff
@@ -1191,7 +1235,7 @@ class RenderEditable extends RenderBox {
   /// When [ignorePointer] is true, an ancestor widget must respond to tap
   /// down events by calling this method.
   void handleTapDown(TapDownDetails details) {
-    _lastTapDownPosition = details.globalPosition - _paintOffset;
+    _lastTapDownPosition = details.globalPosition;
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: I'm surprised that this change doesn't have a corresponding number of other changes doing the opposite. What's the story here?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 28]
```diff
@@ -484,9 +478,50 @@ class _TextSelectionHandleOverlay extends StatefulWidget {
...
+  @override
+  void initState() {
+    super.initState();
+
+    _controller = AnimationController(duration: TextSelectionOverlay.fadeDuration, vsync: this);
+
+    if (_visibility.value) {
+      _controller.forward();
+    }
+    _visibility.addListener(_handleVisibilityChanged);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/text_selection.dart]: you don't handle the case of `widget.position` changing.

You probably want a didUpdateWidget that unsubscribes from the old one and subscribes to the new one if it changed.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 29]
```diff
@@ -546,31 +581,42 @@ class _TextSelectionHandleOverlayState extends State<_TextSelectionHandleOverlay
         break;
     }
 
+    final Size viewport = widget.renderObject.size;
+    if (!viewport.contains(point)) {
+      point = Offset(
+        point.dx.clamp(0.0, viewport.width),
+        point.dy.clamp(0.0, viewport.height),
+      );
+    }
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/text_selection.dart]: Seems like it'd be cheaper to just always clamp?

File: packages/flutter/lib/src/rendering/editable.dart (hunk 27 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: I thought it was not tested because the selection when scrolling was completely broken, but when I dug further I discovered that it was broken in commit 892c8919c7, where the correct behavior was implemented in `selectWordEdge()`, which is used on iOS, but broken for Android, which uses `selectPositionAt()` and `selectWordsInRange()`.

The `_paintOffset` is already subtracted in `selectPositionAt()` and `selectWordsInRange()`, but was not subtracted in `selectWordEdge()`. So I've updated `selectWordEdge()`. All the uses now correct subtract `_paintOffset` exactly once.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 28 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: For my own enlightenment, how can this happen? When the selection handles are built, either none are built, only the left handle, or both handles. I don't see how it can happen that the left handle switches to use state from the right handle or vice versa.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 29 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: I considered that, but I imagined that the "common case" is where both handles are visible, in which case the clamping doesn't change the input offset. It seemed better to me to avoid unnecessary allocation in this case.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 27 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/editable.dart]: Can you add some specific test cases that cover this (outside of their use in the selection handle test cases) to ensure that we never break this again?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 28 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/text_selection.dart]: At the end of the day _TextSelectionHandleOverlay is just another regular widget and it should conform to the widget protocol, which allows that a state object can be attached to an arbitrary new configuration (e.i. Widget). This new Widget may have a different position.

Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Thanks for the explanation. Done.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 27 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Working on this. I wrote a test which uncovered a strange issue with taps not being received when they should be.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 29 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/text_selection.dart]: It would also be easier to read if we always clamp and allocations are supposed to be cheap in dart... If you have a benchmark showing that this is better, we can keep it. Otherwise I'd suggest changing it to the simplified version.

**Review by goderbauer — COMMENTED** [review]
I think this looks good once the last two open comments are resolved.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 29 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Done.

**Comment by sjindel-google** [comment]
It looks like #27948 was already fixed in #28242.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 27 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: It looks the original issue I was solving here (#27948) was already fixed in (#28242).
The "issue" I ran into in the test was just a "user-error" caused by the xster's refactoring of the gesture logic.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 30]
```diff
@@ -562,31 +603,41 @@ class _TextSelectionHandleOverlayState extends State<_TextSelectionHandleOverlay
         break;
     }
 
+    final Size viewport = widget.renderObject.size;
+    point = Offset(
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_selection.dart]: nit: flutter style would be to add a trailing comma and indent by just two spaces:

```dart
point = Offset(
  point.dx.clamp(0.0, viewport.width),
  point.dy.clamp(0.0, viewport.height),
);
```

**Review by goderbauer — APPROVED** [review]
LGTM

Thanks for your patience and sticking with this PR

File: packages/flutter/lib/src/rendering/editable.dart [hunk 31]
```diff
@@ -255,6 +255,50 @@ class RenderEditable extends RenderBox {
 
   Rect _lastCaretRect;
 
+  /// Track whether position of the start of the selected text is within the viewport.
+  ///
+  /// For example, if the text contains "Hello World", and the user selects
+  /// "Hello", then scrolls so only "World" is visible, this will become
+  /// 'false'. If the user scrolls back so that the "H" is visible again, this
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 30 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Done.

**Comment by sjindel-google** [comment]
> LGTM
> 
> Thanks for your patience and sticking with this PR

No, thank *you* and @Hixie for *your* patience!
