### PR TITLE
[flutter_tool] Change the startup message for the "flutter daemon" command

### LINKED ISSUE #143625: Flutter daemon stuck at starting on VSCode
### Steps to reproduce

1, Install flutter following guide in: https://docs.flutter.dev/get-started/install/windows/desktop?tab=vscode#install-the-flutter-sdk
2, Create new project
3, Check VSCode flutter extension

### Actual results

VS code daemon stuck at starting
image

There is no devices in sidebar of flutter extension
image

### Logs

<details open>
<summary>Logs</summary>

```console

!! ⚠️ PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!
Dart Code extension: 3.82.0
Flutter extension: 3.83.20240201 (not activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.86.2


Logging Categories:
    FlutterDaemon

Sat Feb 17 2024 [10:12:47 GMT+0700 (Indochina Time)] Log file started
[10:12:47 AM] [FlutterDaemon] [Info] Spawning E:\works\flutter\bin\flutter.bat with args ["daemon"]
[10:12:47 AM] [FlutterDaemon] [Info] ..  in E:\works\flutter
[10:12:47 AM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code","FLUTTER_ROOT":"E:\\works\\flutter"}}
[10:12:47 AM] [FlutterDaemon] [Info]     PID: 20352
[10:12:47 AM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":3244}}]
[10:12:47 AM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"device.enable"}]
[10:12:47 AM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
[10:12:47 AM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\works\\dp2\\rxapp\\frontend\\app"}}]
[10:12:47 AM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[10:15:29 AM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\works\\dp2\\rxapp\\frontend\\app"}}]

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22621.3155], locale vi-VN)
    • Flutter version 3.19.0 on channel stable at E:\works\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\namka\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34301.259
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\namka\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.83.20240201

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.106

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by DanTup**
There have been some reports of the Flutter daemon not starting up properly (for ex. https://github.com/flutter/flutter/issues/143625), but it turns out that when starting successfully, it just prints "Starting device daemon..." and then nothing more. This is confusing and can lead users to think other issues are because the daemon hasn't started properly.

There's not a great hook to print that this "finished" starting up (because it does async polling in the background), so I just updated the message of the text and moved it to after the creation of the daemon.

Fixes https://github.com/flutter/flutter/issues/143625

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [N/A] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 1]
```diff
@@ -85,14 +85,14 @@ class DaemonCommand extends FlutterCommand {
...
     }
-    globals.printStatus('Starting device daemon...');
     final Daemon daemon = Daemon(
       DaemonConnection(
         daemonStreams: DaemonStreams.fromStdio(globals.stdio, logger: globals.logger),
         logger: globals.logger,
       ),
       notifyingLogger: asLogger<NotifyingLogger>(globals.logger),
     );
+    globals.printStatus('Device daemon started');
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/commands/daemon.dart:95]: Uber nit: I'd prefer for this to end with a period.
```suggestion
    globals.printStatus('Device daemon started.');
```

**Review by andrewkolos — APPROVED** [review]
LGTM

File: packages/flutter_tools/test/integration.shard/daemon_mode_test.dart [hunk 2]
```diff
@@ -27,6 +27,39 @@ void main() {
...
+
+    final StreamController<String> stdout = StreamController<String>.broadcast();
+    transformToLines(daemonProcess.stdout).listen((String line) => stdout.add(line));
+    final Stream<Map<String, Object?>> stream = stdout
+      .stream
+      .map<Map<String, Object?>?>(parseFlutterResponse)
+      .where((Map<String, Object?>? value) => value != null)
+      .cast<Map<String, Object?>>();
+
+    final [Map<String, Object?> connectedEvent, Map<String, Object?> logMessage] = await Future.wait(<Future<Map<String, Object?>>>[
```
Comment (bkonyi) [inline packages/flutter_tools/test/integration.shard/daemon_mode_test.dart:48]: I can't believe I can finally say this, but we're going to need to run the formatter on this.

Comment (bkonyi) [reply packages/flutter_tools/test/integration.shard/daemon_mode_test.dart:48]: ... I think we will, anyway? This line seems super long, but none of the checks are failing yet.

Comment (DanTup) [reply packages/flutter_tools/test/integration.shard/daemon_mode_test.dart]: Ah, I formatted this but noticed the rest of the file was not formatted. I last rebased this _before_ the formatter was enabled.

However, I can't currently sync with master because of https://github.com/flutter/flutter/issues/160704 (I can't run Flutter at all locally), so I'll rebase and fix this up once that is resolved.

Comment (DanTup) [reply packages/flutter_tools/test/integration.shard/daemon_mode_test.dart]: Looks like I didn't need to do this myself, as this passed here (because formatting wasn't enforced), and then the merge queue applied it to latest code and it passed there anyway :-)
