### PR TITLE
Fix for endless recursion for getLayoutExplorerNode on a Tooltip

### LINKED ISSUE #5946: getLayoutExplorerNode stack overflow when clicking on the inspected button
- run `flutter create some_bare_app`
- `cd some_bare_app`
- `flutter run -d macos`
- open up the devtools link
- start widget inspection
- click on the plus button
- click on the plus button again.
- You will now get the following error:
```
A Dart VM Service on macOS is available at: http://127.0.0.1:60374/bj__zCuNnVg=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:60374/bj__zCuNnVg=/

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following StackOverflowError was thrown during a service extension callback for
"ext.flutter.inspector.getLayoutExplorerNode":
Stack Overflow

When the exception was thrown, this was the stack:
#1      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart)
#2      _LinkedHashMapMixin._set (dart:collection-patch/compact_hash.dart:519:7)
#3      _LinkedHashMapMixin._init (dart:collection-patch/compact_hash.dart:440:15)
#4      _LinkedHashMapMixin._rehash (dart:collection-patch/compact_hash.dart:408:7)
#5      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart:464:7)
#6      _LinkedHashMapMixin._set (dart:collection-patch/compact_hash.dart:519:7)
#7      MapBase.addAll.<anonymous closure> (dart:collection/maps.dart:41:11)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#9      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#10     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#11     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2618:45)
#12     FlagProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2120:45)
#13     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#14     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#15     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#16     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1637:25)
#17     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#18     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2058:62)
#19     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#20     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#21     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#22     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#23     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#24     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#25     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#26     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#27     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#28     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#29     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#30     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#31     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#32     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#33     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#34     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#35     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#36     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#37     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#38     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#39     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#40     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#41     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#42     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#43     WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
...
...
#3350   DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#3351   DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#3352   _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#3353   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#3354   InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#3355   DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#3356   DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#3357   _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#3358   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#3359   InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#3360   DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#3361   DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#3362   _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#3363   WidgetInspectorService._getLayoutExplorerNode.<anonymous closure>
(package:flutter/src/widgets/widget_inspector.dart:2066:61)
#3364   InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3628:53)
#3365   DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1635:21)
#3366   DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#3367   _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#3368   DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1675:19)
#3369   ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3370   new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#3371   new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#3372   new List.of (dart:core-patch/array_patch.dart:47:28)
#3373   ListIterable.toList (dart:_internal/iterable.dart:214:7)
#3374   DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1676:8)
#3375   DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1643:23)
#3376   DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1650:6)
#3377   _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5052:45)
#3378   WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1644:18)
#3379   WidgetInspectorService._getLayoutExplorerNode (package:flutter/src/widgets/widget_inspector.dart:2038:14)
#3380   BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:958:32)
#3390   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 10 frames from class _AssertionError, class _Timer, dart:async, and dart:async-patch)
```

### PR DESCRIPTION
**Pull request by CoderDake**
Fixes https://github.com/flutter/devtools/issues/5946

While preparing DevTools for the Multi View changes, I noticed that
inspecting a Tooltip causes an stack overflow.
This PR addresses that issue by fixing the scope of the subtreeDepth variable and adding some other idiomatic fixes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -2109,24 +2109,33 @@ mixin WidgetInspectorService {
...
-          final DiagnosticsSerializationDelegate renderObjectSerializationDelegate = delegate.copyWith(
+          final DiagnosticsSerializationDelegate
+              renderObjectSerializationDelegate = delegate.copyWith(
             subtreeDepth: 0,
             includeProperties: true,
             expandPropertyValues: false,
           );
           final Map<String, Object> additionalJson = <String, Object>{
-            'renderObject': renderObject.toDiagnosticsNode().toJsonMap(renderObjectSerializationDelegate),
+            // Doesn't make sense to add another renderObject to a renderObject
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2128]: just realized it would be cleaner to write
// Only include renderObject properties separately if this value is not already the renderObject.
// Only include if we are expanding property values to mitigate the risk of infinite loops if
// RenderObjects have properties that are Element objects.
if (value != renderObject && delegate.expandPropertyValues) {

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 2]
```diff
@@ -2109,24 +2109,33 @@ mixin WidgetInspectorService {
...
+            if (value is! RenderObject && delegate.expandPropertyValues)
+              'renderObject': renderObject
+                  .toDiagnosticsNode()
+                  .toJsonMap(renderObjectSerializationDelegate),
           };
 
           final RenderObject? renderParent = renderObject.parent;
-          if (renderParent is RenderObject && subtreeDepth > 0) {
+          if (renderParent is RenderObject &&
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2136]: not your bug but there was another non-idiomatic check here.
Rather than writing 
parent is RenderObject
we should just write
renderParent != null

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by Piinks** [comment]
(triage) Is this PR ready to land? :)
