### PR TITLE
fix: MaterialColor Swatch Map comparison

### LINKED ISSUE #61888: MaterialColor Swatch Map comparison always false
I am using a Dropdown of type myObject.

myObject contains a MaterialColor parameter. For the comparison of these objects, I am using the Equatable library.

At some point in the comparison, the code jumps into the [colors.dart file at the following line](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/painting/colors.dart#L454):

The error occurs since  `_swatch` is a **Map** and the comparison `other._swatch == _swatch;` will always return false if the Maps have different hashCodes.

The  `==` should probably get replaced by `MapEquality().equals(other._swatch,_swatch)`

### PR DESCRIPTION
**Pull request by ayaankhan98**
## Description
fixed the map comparison bug.
since ` _swatch` is a Map and the comparison `other._swatch == _swatch;` will always return false if the Maps have different hashCodes.

therefore the `==` is replaced by `MapEquality().equals(other._swatch,_swatch)`

## Related Issues

Fixes #61888

## Tests
This is the bug reproducible code
```
import 'package:flutter/material.dart';

void main() {
 var map = {0:Colors.lightBlue,1:Colors.deepOrange,2:Colors.blueGrey};
 var first = new MaterialColor(0, map);
 var second = new MaterialColor(0, map);
 var third = new MaterialColor(0, {0:Colors.lightBlue,1:Colors.deepOrange,2:Colors.blueGrey});
 print("Comparison of the same map object in MaterialColor constructor: " + (first == second).toString());
 print("Comparison of different map objects with same values in MaterialColor constructor: " + (first == third).toString());
}
```
before changing the `==` by `MapEquality().equals(other._swatch,_swatch)`
the output was
```
I/flutter (17640): Comparison of the same map object in MaterialColor constructor: true
I/flutter (17640): Comparison of different map objects with same values in MaterialColor constructor: false
```
after implementing changes the output is as expected
```
I/flutter (17640): Comparison of the same map object in MaterialColor constructor: true
I/flutter (17640): Comparison of different map objects with same values in MaterialColor constructor: true
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @ayaankhan98 welcome! And thank you for the contribution!

Can you revert the unrelated formatting changes here? You can refer to the [Flutter Style Guide here](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo).
The analyzer also appears to have caught some exceptions here: 
```
info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:207:33 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:208:20 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:209:20 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:220:33 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:390:33 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:391:20 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:392:20 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:403:33 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:447:33 • always_put_control_body_on_new_line
   info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:448:43 • always_put_control_body_on_new_line
   info • Prefer const with constant constructors • packages/flutter/lib/src/painting/colors.dart:451:9 • prefer_const_constructors
   info • Specify type annotations • packages/flutter/lib/src/painting/colors.dart:451:9 • always_specify_types
  error • Missing type arguments for generic type 'MapEquality<dynamic, dynamic>' • packages/flutter/lib/src/painting/colors.dart:451:9 • implicit_dynamic_type
```

Lastly, this should also have a test. That will make sure this works as intended, and more importantly it will ensure it is not undone later by another change.

**Comment by ayaankhan98** [comment]
> Hi @ayaankhan98 welcome! And thank you for the contribution!
> 
> Can you revert the unrelated formatting changes here? You can refer to the [Flutter Style Guide here](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo).
> The analyzer also appears to have caught some exceptions here:
> 
> ```
> info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:207:33 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:208:20 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:209:20 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:220:33 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:390:33 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:391:20 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:392:20 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:403:33 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:447:33 • always_put_control_body_on_new_line
>    info • Separate the control structure expression from its statement • packages/flutter/lib/src/painting/colors.dart:448:43 • always_put_control_body_on_new_line
>    info • Prefer const with constant constructors • packages/flutter/lib/src/painting/colors.dart:451:9 • prefer_const_constructors
>    info • Specify type annotations • packages/flutter/lib/src/painting/colors.dart:451:9 • always_specify_types
>   error • Missing type arguments for generic type 'MapEquality<dynamic, dynamic>' • packages/flutter/lib/src/painting/colors.dart:451:9 • implicit_dynamic_type
> ```
> 
> Lastly, this should also have a test. That will make sure this works as intended, and more importantly it will ensure it is not undone later by another change.

okay Thanks @Piinks i will fix these issues soon.

**Comment by ayaankhan98** [comment]
> Lastly, this should also have a test. That will make sure this works as intended, and more importantly it will ensure it is not undone later by another change.

@Piinks where should i place test for this, in `flutter/packages/flutter/test/material/colors_test.dart` or in `flutter/packages/flutter/test/painting/colors_test.dart`

**Comment by Piinks** [comment]
> @Piinks where should i place test for this, in `flutter/packages/flutter/test/material/colors_test.dart` or in `flutter/packages/flutter/test/painting/colors_test.dart`

✅  `flutter/packages/flutter/test/painting/colors_test.dart` - that should be a good place! Thanks! :)

File: packages/flutter/lib/src/painting/colors.dart [hunk 1]
```diff
@@ -451,7 +451,7 @@ class ColorSwatch<T> extends Color {
       return false;
     return super == other
         && other is ColorSwatch<T>
-        && other._swatch == _swatch;
+        && MapEquality<T, Color>().equals(other._swatch, _swatch);
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/colors.dart:454]: Please use https://master-api.flutter.dev/flutter/foundation/mapEquals.html from the foundation library instead of importing package:collection

Comment (ayaankhan98) [reply packages/flutter/lib/src/painting/colors.dart]: Okay thanks for telling. :)

File: packages/flutter/lib/src/painting/colors.dart [hunk 2]
```diff
@@ -6,7 +6,6 @@
 
 import 'dart:math' as math;
 import 'dart:ui' show Color, lerpDouble, hashValues;
-
```
Comment (Piinks) [inline packages/flutter/lib/src/painting/colors.dart:9]: Nit: There should be a line break here.

File: packages/flutter/test/painting/colors_test.dart [hunk 3]
```diff
@@ -440,4 +441,13 @@ void main() {
     final Map<String, Object> json = property.toJsonMap(const DiagnosticsSerializationDelegate());
     expect(json.containsKey('valueProperties'), isFalse);
   });
+
+  test('MaterialColor swatch comparison', () {
+    const Map<int, MaterialColor> sampleMap = <int, MaterialColor>{0: Colors.lightBlue, 1: Colors.deepOrange, 2: Colors.blueGrey};
```
Comment (Piinks) [inline packages/flutter/test/painting/colors_test.dart:446]: Style nit, here and below:
```suggestion
    const Map<int, MaterialColor> sampleMap = <int, MaterialColor>{
      0: Colors.lightBlue,
      1: Colors.deepOrange,
      2: Colors.blueGrey,
    };
```

**Review by Piinks — COMMENTED** [review]
Thanks for updating this! Just a few nits. :)

File: packages/flutter/lib/src/painting/colors.dart (hunk 2 above)
Comment (ayaankhan98) [reply packages/flutter/lib/src/painting/colors.dart]: Done!

File: packages/flutter/test/painting/colors_test.dart (hunk 3 above)
Comment (ayaankhan98) [reply packages/flutter/test/painting/colors_test.dart]: okay :)

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!

The failing checks are not related to this change. Upstream is actually broken right now with this version solving problem: #62146. That will have to be fixed first, then this PR rebased for the checks to pass.

**Comment by ayaankhan98** [comment]
> The failing checks are not related to this change. Upstream is actually broken right now with this version solving problem: #62146. That will have to be fixed first, then this PR rebased for the checks to pass.

Okay, Thanks for help :)

**Comment by goderbauer** [comment]
@ayaankhan98 The issue has been fixed. Can you please rebase this change to make all the checks pass? Thanks.

**Comment by ayaankhan98** [comment]
> @ayaankhan98 The issue has been fixed. Can you please rebase this change to make all the checks pass? Thanks.

@goderbauer and @Piinks , i am facing some issue with my machine therefore i am unable to rebase the commits now. see if anyone of you can run the checks manually.

**Comment by goderbauer** [comment]
@ayaankhan98 Is your machine working again? Can you try rebasing it again?
