### PR TITLE
[FloatingActionButtonLocation] Avoid docked FAB to be clipped by the software keyboard

### LINKED ISSUE #26100: Docked FAB gets clipped when keyboard is shown
## Steps to Reproduce

1. run app ( `main.dart` below )
2. open keyboard ( fab onPressed will do it )

Actual: FAB clipped ( See end of issue for snippet to make it work )
clipped-docked-fab
Expected: FAB not clipped
non-clipped-docked-fab

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void showKeyboard () => SystemChannels.textInput.invokeMethod('TextInput.show');
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: FabExample (),
    );
  }
}
class FabExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('FAB Test'),
      ),
      body: Center(),
      // FAB floats properly above the keyboard ( including suggestions )
//      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      // FAB docked above the keyboard, not taking into account the full height
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: FloatingActionButton(
        onPressed: showKeyboard,
        child: Icon(Icons.keyboard),
      ),
    );
  }
}
```
## Logs

[flutter-run-verbose.log](https://github.com/flutter/flutter/files/2728979/flutter-run-verbose.log)

```
flutter-analyze
Analyzing docker_fab_example...
No issues found! (ran in 2.0s)
```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at d:\Work\SDK\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Work\SDK\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.3
    • ANDROID_HOME = D:\Work\SDK\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

### What made it work

Although am not entirely sure that's the correct solution, I was able to make it work by removing the division by `2` that happens on `fabY` in `_DockedFloatingActionButtonLocation` in `floating_action_button_location.dart`

```dart
import 'dart:math';

class FixedCenterDockedFabLocation extends FloatingActionButtonLocation {
  const FixedCenterDockedFabLocation();

  @protected
  double getDockedY(ScaffoldPrelayoutGeometry scaffoldGeometry) {
    final double contentBottom = scaffoldGeometry.contentBottom;
    final double bottomSheetHeight = scaffoldGeometry.bottomSheetSize.height;
    final double fabHeight = scaffoldGeometry.floatingActionButtonSize.height;
    final double snackBarHeight = scaffoldGeometry.snackBarSize.height;

    // In _DockedFloatingActionButtonLocation this value is
    // double fabY = contentBottom - fabHeight / 2.0;
    // ----------------------------------
    // VVVVVVVVVVVVVVVVVVVVVV
    double fabY = contentBottom - fabHeight;

    // The FAB should sit with a margin between it and the snack bar.
    if (snackBarHeight > 0.0)
      fabY = min(fabY, contentBottom - snackBarHeight - fabHeight - kFloatingActionButtonMargin);
    // The FAB should sit with its center in front of the top of the bottom sheet.
    if (bottomSheetHeight > 0.0)
      fabY = min(fabY, contentBottom - bottomSheetHeight - fabHeight / 2.0);

    final double maxFabY = scaffoldGeometry.scaffoldSize.height - fabHeight;
    return min(maxFabY, fabY);
  }
  @override
  Offset getOffset(ScaffoldPrelayoutGeometry scaffoldGeometry) {
    final double fabX = (scaffoldGeometry.scaffoldSize.width - scaffoldGeometry.floatingActionButtonSize.width) / 2.0;
    return Offset(fabX, getDockedY(scaffoldGeometry));
  }
}
```

### PR DESCRIPTION
**Pull request by royarg02**
This PR adjusts the margin applied to a docked `FloatingActionButton` to avoid the software keyboard when invoked.

The docked FAB would detach from `Scaffold.bottomNavigationBar` and behave like a floating FAB placed above the keyboard with a margin of `kFloatingActionButtonMargin`.

|Before|After|
|-------|------|
|before|after|

## Related Issues

Fixes #26100.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/floating_action_button_location.dart [hunk 1]
```diff
@@ -584,7 +584,13 @@ mixin FabDockedOffsetY on StandardFabLocation {
...
     final double fabHeight = scaffoldGeometry.floatingActionButtonSize.height;
     final double snackBarHeight = scaffoldGeometry.snackBarSize.height;
-    final double safeMargin = bottomViewPadding > contentMargin ? bottomViewPadding : 0.0;
+    final double bottomMinInset = scaffoldGeometry.minInsets.bottom;
+
+    final double safeMargin = bottomMinInset + fabHeight / 2.0 < contentMargin
+        ? 0.0
+        : bottomMinInset == 0.0
+            ? bottomViewPadding
+            : fabHeight / 2.0 + kFloatingActionButtonMargin;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/floating_action_button_location.dart:593]: This is a bit hard to read and understand the decision path here. Can you break this out and add comments to explain what's going on?

Comment (RoyARG02) [reply packages/flutter/lib/src/material/floating_action_button_location.dart:593]: The code tries to apply the proper `safeMargin` according to the following criteria:

```txt
if contentMargin > bottomMinInset + fabHeight / 2   (Scaffold.bottomNavigationBar is bigger in height than
                                                 the keyboard, there is ample space to display a docked FAB)
  then safeMargin = 0.0
else if keyboard is closed
  then safeMargin = bottomViewPadding       (= 34.0px in iOS, 0.0 in Android)
else
  safeMargin = fabHeight / 2 + kFloatingActionButtonMargin  (this makes the docked FAB to behave like a 
                                                            floating FAB above the keyboard)
```

Additional context is at https://github.com/flutter/flutter/issues/26100#issuecomment-792810196

The usage of the conditional operator probably makes it a bit less readable. Would it be better to add comments or convert the code to an if-else statement here?

Comment (RoyARG02) [reply packages/flutter/lib/src/material/floating_action_button_location.dart:593]: Are the following comments sufficient?

```dart
    final double safeMargin =
      // Check whether bottomMinInset is lower than contentMargin, just enough
      // to display a docked FAB
      // bottomMinInset is typically represented by the software keyboard
      bottomMinInset + fabHeight / 2.0 < contentMargin
        // If low enough, don't provide a margin(don't move the docked FAB)
        ? 0.0
        // If not low enough, check whether bottomMinInset is zero(the software
        // keyboard is closed)
        : bottomMinInset == 0.0
            // If bottomMinInset is zero, provide bottomViewPadding as margin
            ? bottomViewPadding
            // If bottomMinInset isn't zero, provide a margin that would shift
            // the docked FAB enough so that it would stay away from the keyboard
            : fabHeight / 2.0 + kFloatingActionButtonMargin;
```

Comment (Piinks) [reply packages/flutter/lib/src/material/floating_action_button_location.dart:593]: > ```dart
>     double safeMargin;
> 
>     if (contentMargin > bottomMinInset + fabHeight / 2.0) {
>       // If contentMargin is higher than bottomMinInset enough to display a
>       // docked FAB without clipping, don't provide a margin
>       safeMargin = 0.0;
>     } else if (bottomMinInset == 0.0) {
>       // If bottomMinInset is zero(the software keyboard is not on the screen)
>       // provide bottomViewPadding as margin
>       safeMargin = bottomViewPadding;
>     } else {
>       // Provide a margin that would shift the docked FAB enough so that it
>       // stays away from the keyboard
>       safeMargin = fabHeight / 2.0 + kFloatingActionButtonMargin;
>     }
> ```

This LGTM, while the other is pretty trim and streamlined, which I appreciate, this is easiest to read and follow along with.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you for the contribution!

**Comment by Piinks** [comment]
Checking the Google failures now to see what's up. :)

**Comment by RoyARG02** [comment]
@Piinks looks like the tests are still failing, even after I added an empty commit to re-check.

The other PR I created is also failing, I pinged you there.

**Comment by Piinks** [comment]
Oh, an empty commit? Did you get the latest changes from master?

**Comment by RoyARG02** [comment]
> Oh, an empty commit? Did you get the latest changes from master?

I rebased and force-pushed both of the PRs.
