### PR TITLE
[Framework] Support for Android Fullscreen Modes

### LINKED ISSUE #35748: Support for translucent + transparent Android's SystemNavigationBar
It would be nice to be able to make the system navigation bar transparent. Right now when i try 
```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(

    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,

  ));
```
The status bar becomes transparent but not the systemNavigationBar

image
image

### GOAL 
image

### WHAT I TRIED AND FAILED
I have tried doing it with Kotlin and Android following [this answer in stackoverflow](https://stackoverflow.com/a/31596735/8096916) but the  SafeArea widgets stops working and a navigation bar looks like this 

Captura de pantalla 2019-07-08 a las 19 06 46

### LINKED ISSUE #40974: [Android 10] Unable to set transparent navigation bar
## Steps to Reproduce

Run the provided code on an Android 10 device. Tested on a physical Pixel 3 XL running latest Android 10 stable release.

Expected: The blue background pushes until the bottom of the screen, while the gestures bar stays floating over the app.

Result: The navigation bar is still black, the app doesn't draw until the bottom.

### Sample code

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        backgroundColor: Colors.blue,
        body: Center(
          child: Text('Test'),
        ),
      ),
    );
  }
}
```

### Flutter doctor output
```
[√] Flutter (Channel master, v1.10.6-pre.20, on Microsoft Windows [Version 10.0.18362.356], locale es-ES)
    • Flutter version 1.10.6-pre.20 at C:\src\flutter
    • Framework revision c238045a96 (35 minutes ago), 2019-09-20 07:58:53 -0700
    • Engine revision 70f21b0edb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

Related to https://github.com/flutter/flutter/issues/34678

cc/ @shihaohong

### LINKED ISSUE #44033: Bottom gap on Pixel 4
## Steps to Reproduce

1. Install an app with white background on Pixel 4
2. The app doesn't extend to the bottom of the screen, but showing a black stripe instead.

image

**Target Platform:**
Android
**Target OS version/browser:**
Latest
**Devices:**
Pixel 4

## Logs

```
Analyzing mobile...                                                     
No issues found! (ran in 7.4s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.382, on Mac OS X 10.15 19A583, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
```

### LINKED ISSUE #63761: Android 10 incorrect insets when navigation bar is translucent
First of all thanks for the great Flutter toolkit if you'll have some follow up questions to the issue, I'll be glad to answer.

## Steps to Reproduce

The example app is available here: https://github.com/jacek-marchwicki/flutter-insets-bug

Changes to the example project that are necessary to reproduce the issue: https://github.com/jacek-marchwicki/flutter-insets-bug/commit/f23e6d89da417a7ee28dc4f745ddb32d7eec103a
<details>
  <summary>Diff</summary>

```patch
Index: lib/main.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/main.dart	(revision d3362aabdefa74cc479fc50b8994f00b57b230a8)
+++ lib/main.dart	(date 1597401415000)
@@ -72,6 +72,25 @@
     // fast, so that you can just rebuild anything that needs updating rather
     // than having to individually change instances of widgets.
     return Scaffold(
+      bottomNavigationBar: BottomNavigationBar(
+        items: const <BottomNavigationBarItem>[
+          BottomNavigationBarItem(
+            icon: Icon(Icons.home),
+            title: Text('Home'),
+          ),
+          BottomNavigationBarItem(
+            icon: Icon(Icons.business),
+            title: Text('Business'),
+          ),
+          BottomNavigationBarItem(
+            icon: Icon(Icons.school),
+            title: Text('School'),
+          ),
+        ],
+        currentIndex: 0,
+        selectedItemColor: Colors.amber[800],
+        onTap: (_) {},
+      ),
       appBar: AppBar(
         // Here we take the value from the MyHomePage object that was created by
         // the App.build method, and use it to set our appbar title.
Index: android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(revision d3362aabdefa74cc479fc50b8994f00b57b230a8)
+++ android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(date 1597397196000)
@@ -1,7 +1,17 @@
 package com.example.insetstest
 
+import android.graphics.Color
+import android.os.Build
+import android.view.View
 import io.flutter.embedding.android.FlutterActivity
 
-class MainActivity : FlutterActivity() {
-
+class MainActivity: FlutterActivity() {
+    override fun onWindowFocusChanged(hasFocus: Boolean) {
+        super.onWindowFocusChanged(hasFocus)
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
+            window.navigationBarColor = Color.TRANSPARENT
+            window.statusBarColor = Color.TRANSPARENT
+        }
+    }
 }

```

</details>

   1. We need to enable transparent navigation bar. According to (the Android documentation: https://developer.android.com/training/gestures/gesturenav) we need to set:
       ```kotlin
            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            window.navigationBarColor = Color.TRANSPARENT
            window.statusBarColor = Color.TRANSPARENT
       ```
      
  2. We need to check if insets are updated correctly, In the example I'm using BottomNavigationBar but we could also use SafeArea to reproduce the same issue.

| **Expected results** | **Actual results** | **Actual results** | **On iOS** |
|---|---|---|---|
| We should see the BottomNavigationBar displayed right above system navigation bar. | We see system navigation bar displayed on BottomNavigationBar. | On Android, we can observe the same results when gestures navigation is disabled and standard 3 buttons navigation is set. | The same code works perfectly fine on iOS |
| android-with-fix | android | android-no-gestures | ios |

# Findings

After debugging I found out that Android sets `Window.viewInsets.bottom` to the height of the navigation bar. 
The different is on iOS where `Window.viewInsets.bottom` is set to 0, but the height of the navigation bar is set in `Window.padding.bottom` and `Window.padding.viewPadding`. By looking through the [window documentation](https://api.flutter.dev/flutter/dart-ui/Window-class.html) and the following [video](https://flutter.github.io/assets-for-api-docs/assets/widgets/window_padding.mp4) looks like the iOS implementation is correct.

# Workaround

I've created a widget that does workaround the issue: https://github.com/jacek-marchwicki/flutter-insets-bug/commit/f5eb07af06e9cfee2124d97e33aa2e4189e728f9#diff-fe53fad46868a294b309fc85ed138997R143-R168
With the fix, the app looks correctly:

| Gesture navigation | standard 3 buttons navigation |
|---|---|
| android-with-fix | android-with-fix-no-gestures |

# Logs
<details>
  <summary>Logs</summary>

### `flutter run --verbose` results:
[logs.txt](https://github.com/flutter/flutter/files/5074061/logs.txt)

### `flutter analyze` results:
```
Analyzing insets_test...                                                
No issues found! (ran in 6.6s)
```

### `flutter doctor -v` results:
[doctor-result.txt](https://github.com/flutter/flutter/files/5074037/doctor-result.txt)

</details>

# Related tickets: 
* https://github.com/flutter/flutter/issues/34678
* https://github.com/flutter/flutter/issues/40974
* https://github.com/flutter/flutter/issues/39061

### LINKED ISSUE #69999: Flutter still doesn't support modern Android Q-style render-behind-navbar styling
## Use case

As introduced back in 2019, Android Q brought new gesture navigation to Android. This involves a new way of rendering the bottom navigation UI. Instead of rendering the bottom nav as a separate opaque element (that could be fullscreened/hidden, depending on the app's needs), the new gesture nav element is draw _**on top of the app**_, with a dynamic contrast effect to make sure the gesture nav bar is always visible.

Please see this blog post for details: https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

As far as I can tell, in Nov 2020, more than a year after this behavior was standardized in Android, it is still not possible to have this modern Android Q-style navigation rendering. In several issues, it has been stated that the Flutter engine is incapable of rendering behind the navbar (aside from when the navbar has been made transparent for fullscreen apps).

Some previous issues that saw no resolution:

https://github.com/flutter/flutter/issues/34678
https://github.com/flutter/flutter/issues/35748
https://github.com/flutter/flutter/issues/40974

image

image

There is a PR that was recently merged here, https://github.com/flutter/engine/pull/21730, that seems to reference these issues; however, I've tested `master` on a modern Android device and it is still not possible to use a fully transparent, permanent gesture nav bar.

Most notable, Flutter Gallery itself does not even implement this behavior, with an outstanding issue that has been open since August 2019! https://github.com/flutter/flutter/issues/39061

## Proposal

This is what modern Android 11 with a native app can do with the gesture nav, vs what Flutter does right now:

image

Here is the modern Android clock app:

You can clearly see how the nav bar is draw on top of the app, with the app drawing across the entire screen.

Given the huge number of comments on all of the issues related to this problem, it is really surprising to me that not only do the official Flutter demos, examples, and galleries not implement this type of navbar (which has been officially recommended for over a year), but that it seems to be actually impossible to implement in Flutter.

### PR DESCRIPTION
**Pull request by Piinks**
This adds support for varying Android fullscreen modes, which affect the visibility of system ui overlays like the status and bottom navigation bars.

- **lean back** - a fullscreen mode that brings system overlays into view by tapping anywhere on the screen
  - this tap is not received by the application
- **immersive** - a fullscreen mode that brings system overlays into view by swiping at the edge of the screen
  - this swipe is not received by the framework
- **immersive sticky** - a fullscreen mode that brings system overlays into view by swiping at the edge of the screen
  - this swipe is received by the framework
- **edge to edge** - this makes the application take up the fullscreen, with the overlays hovering on top

For the first three modes, there is also a new callback exposed so developers can be notified when the system overlays change, and what state they are in.

Finally, this change also updates the SystemChromeStyle, adding the ability to override the translucent scrim that is automatically added in Android to ensure proper contrast with system overlays.

Engine side: https://github.com/flutter/engine/pull/25785

Related Issues:
- Fixes https://github.com/flutter/flutter/issues/35748
- flutter/gallery#643 will need follow up to implement
-  Fixes https://github.com/flutter/flutter/issues/40974
-  Fixes https://github.com/flutter/flutter/issues/44033
-  Fixes https://github.com/flutter/flutter/issues/63761
-  Fixes https://github.com/flutter/flutter/issues/69999

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 1]
```diff
@@ -282,13 +379,61 @@ class SystemChrome {
   /// after a delay of 1 second. This can be achieved through [restoreSystemUIOverlays]
   /// or calling this again. Otherwise, the original UI overlay settings will be
   /// automatically restored only when the application loses and regains focus.
+  @Deprecated(
+      'Migrate to setEnabledSystemUIMode. '
+      'This feature was deprecated after v2.2.0-11.0.pre.'
+  )
   static Future<void> setEnabledSystemUIOverlays(List<SystemUiOverlay> overlays) async {
```
Comment (Piinks) [inline packages/flutter/lib/src/services/system_chrome.dart:386]: TODO(Piinks): Add a dart fix for this

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 2]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+  /// Fullscreen display without status or navigation bars.
+  ///
+  /// Available starting at SDK 16 or Android J. Tapping on the screen displays
+  /// overlays, this gesture is not received by the application.
+  ///
+  /// See also:
+  ///
+  ///   * [SystemUiChangeCallback], used to listen and respond to the change in
+  ///     system overlays.
+  lean_back,
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:102]: I believe the style for naming these is camelCase, e.g. leanBack

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 3]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+/// Used by [SystemChrome.setEnabledSystemUIMode].
+typedef SystemUiChangeCallback = void Function(bool systemOverlaysAreVisible);
+
+/// Specifies Android fullscreen mode.
+///
+/// Used by [SystemChrome.setEnabledSystemUIMode].
+enum SystemUiMode {
+  /// Fullscreen display without status or navigation bars.
+  ///
+  /// Available starting at SDK 16 or Android J. Tapping on the screen displays
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:95]: What happens if you specify this on devices running an older version of Android (or don't run android at all, e.g. iOS)?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 4]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+  /// Available starting at SDK 19 or Android K. Swiping from the edge of the
+  /// screen displays overlays, this gesture is not received by the application.
+  ///
+  /// See also:
+  ///
+  ///   * [SystemUiChangeCallback], used to listen and respond to the change in
+  ///     system overlays.
+  immersive,
+
+  /// Fullscreen display without status or navigation bars.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:115]: What's the difference to "immersive"?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 5]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+/// Signature for listening to changes in the [SystemUiMode].
+///
+/// Used by [SystemChrome.setEnabledSystemUIMode].
+typedef SystemUiChangeCallback = void Function(bool systemOverlaysAreVisible);
+
+/// Specifies Android fullscreen mode.
+///
+/// Used by [SystemChrome.setEnabledSystemUIMode].
+enum SystemUiMode {
+  /// Fullscreen display without status or navigation bars.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:93]: It may be more useful if the first line summary already hints at how the modes are different (right now  the first three modes share the same summary)

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 6]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+  ///
+  ///   * [SystemUiChangeCallback], used to listen and respond to the change in
+  ///     system overlays.
+  immersive_sticky,
+
+  /// Fullscreen display with status and navigation elements rendered over the
+  /// application.
+  ///
+  /// Available starting at SDK 16 or Android J. The system overlays will not
+  /// disappear or reappear in this mode.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:130]: will not disappear or reappear because they are permanently displayed?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 7]
```diff
@@ -81,6 +81,67 @@ enum SystemUiOverlay {
...
+  /// See also:
+  ///
+  ///   * [SystemUiOverlayStyle], can be used to set transparent status and
+  ///     navigation bars for an enhanced effect.
+  edge_to_edge,
+
+  /// Declares manually configured [SystemUiOverlay]s.
+  ///
+  /// When using this mode with [SystemChrome.setEnabledSystemUIMode], the
+  /// preferred overlays must be set by the developer.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:141]: How do you do this?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 8]
```diff
@@ -113,6 +176,18 @@ class SystemUiOverlayStyle {
   /// When set to [Brightness.dark], the system navigation bar icons are dark.
   final Brightness? systemNavigationBarIconBrightness;
 
+  /// Overrides the contrast enforcement when setting a transparent navigation
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:179]: Does this only have an effect if systemNavigationBarColor is set to transparent? Maybe link the two properties in the docs?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 9]
```diff
@@ -128,6 +203,18 @@ class SystemUiOverlayStyle {
   /// Only honored in Android version M and greater.
   final Brightness? statusBarIconBrightness;
 
+  /// Overrides the contrast enforcement when setting a transparent status
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:206]: Same as above

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 10]
```diff
@@ -155,10 +242,12 @@ class SystemUiOverlayStyle {
     return <String, dynamic>{
       'systemNavigationBarColor': systemNavigationBarColor?.value,
       'systemNavigationBarDividerColor': systemNavigationBarDividerColor?.value,
+      'systemStatusBarContrastEnforced' : systemStatusBarContrastEnforced?.toString(),
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:245]: Why transfer the bools as String? They should be transferable as bool, no?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 11]
```diff
@@ -155,10 +242,12 @@ class SystemUiOverlayStyle {
...
       'statusBarColor': statusBarColor?.value,
       'statusBarBrightness': statusBarBrightness?.toString(),
       'statusBarIconBrightness': statusBarIconBrightness?.toString(),
       'systemNavigationBarIconBrightness': systemNavigationBarIconBrightness?.toString(),
+      'systemNavigationBarContrastEnforced' : systemNavigationBarContrastEnforced?.toString(),
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:250]: same

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 12]
```diff
@@ -282,13 +379,61 @@ class SystemChrome {
...
+  /// Android will not restore the previous UI visibility settings, and the UI
+  /// visibility cannot be changed until 1 second after the keyboard is closed to
+  /// prevent malware locking users from navigation buttons.
+  ///
+  /// To regain "fullscreen" after text entry, the UI overlays can be set again
+  /// after a delay of at least 1 second through [restoreSystemUIOverlays] or
+  /// calling this again. Otherwise, the original UI overlay settings will be
+  /// automatically restored only when the application loses and regains focus.
+  ///
+  /// Alternatively, a [SystemUiChangeCallback] can be provided to respond to
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:413]: How do I unset the callback if I am no longer interested?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 13]
```diff
@@ -282,13 +379,61 @@ class SystemChrome {
...
+  /// changes in the System UI. This will be called for example when in
+  /// [SystemUiMode.lean_back] and the user taps the screen to bring up the
+  /// system overlays. The callback provides a boolean to represent if the
+  /// application is currently in a fullscreen mode or not, so that the
+  /// application can respond to these changes.
+  static Future<void> setEnabledSystemUIMode(SystemUiMode mode, { List<SystemUiOverlay>? overlays, SystemUiChangeCallback? callback }) async {
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:419]: nit: document the "overlays" parameter?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 14]
```diff
@@ -282,13 +379,61 @@ class SystemChrome {
   /// after a delay of 1 second. This can be achieved through [restoreSystemUIOverlays]
   /// or calling this again. Otherwise, the original UI overlay settings will be
   /// automatically restored only when the application loses and regains focus.
+  @Deprecated(
+      'Migrate to setEnabledSystemUIMode. '
+      'This feature was deprecated after v2.2.0-11.0.pre.'
+  )
   static Future<void> setEnabledSystemUIOverlays(List<SystemUiOverlay> overlays) async {
     await SystemChannels.platform.invokeMethod<void>(
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_chrome.dart:387]: nit: this could call through to the new method.

**Comment by Kotlinovsky** [comment]
Any update on this PR?

**Comment by Piinks** [comment]
> Any update on this PR?

Yes! Thanks @Kotlinovsky! I've been away for a bit, but expect to push updates by tomorrow. :D

**Comment by Piinks** [comment]
@goderbauer, I think this is ready for another look, I am just curious about what you think of the callback. I put it in the ServicesBinding.. which I think is ok? Wanted to know what you think before I fix up all the documentation and add the last few tests here.

File: packages/flutter/test/services/system_chrome_test.dart [hunk 15]
```diff
@@ -89,16 +89,64 @@ void main() {
...
+    await SystemChrome.setEnabledSystemUIMode(SystemUiMode.leanBack);
+
+    expect(log, hasLength(1));
+    expect(log.single, isMethodCall(
+      'SystemChrome.setEnabledSystemUIMode',
+      arguments: 'SystemUiMode.leanBack',
+    ));
+  });
+
+  test('setEnabledSystemUIMode asserts for overlays in manual configuration', () async {
```
Comment (shihaohong) [inline packages/flutter/test/services/system_chrome_test.dart:108]: Maybe also add a control test for using manual configuration and correctly passing in a set of overlays

**Review by shihaohong — APPROVED** [review]
Little nits here and there, but looks good to me!

**Comment by OliverRhyme** [comment]
Any updates with this PR?

**Comment by Piinks** [comment]
Engine changes have landed, just waiting on the engine roll and this should be good to go! :)

**Comment by Piinks** [comment]
Waiting a bit further for the engine change to roll to dev, there are some affected customers internally that are affected by the lower level java changes. Working on migrating them now.

**Comment by Piinks** [comment]
Update: Still waiting on the roll. 🙂  🤞

**Comment by Piinks** [comment]
The engine change is being reverted, so this is on hold again.

**Comment by Piinks** [comment]
https://github.com/flutter/engine/pull/27018 is the updated engine change

**Comment by Kotlinovsky** [comment]
Updates?

**Comment by Piinks** [comment]
The cirrus customer shard here is experiencing merge conflicts, which is odd. I am going to revert the dart fixes (which are causing the conflicts) and see if it resolves the failure. I can add them back after or in a follow up change.

**Comment by Piinks** [comment]
That did not seem to make a difference, putting them back.

**Comment by Zee2** [comment]
Hallelujah. Holy **** I have been waiting so long for this to be fixed. Thank you. Phew.

**Comment by OliverRhyme** [comment]
What flutter version we could expect for this fix to be shipped?

**Comment by wiradikusuma** [comment]
Thank you! 

Equally important: Since this issue has been around for ages, and many people have done workarounds, would be great if there's documentation explaining the canonical way of handling this. Not to mention, in Android, users can change the navigation mode to "classic" or "gesture" anytime.
