### PR TITLE
Look for APKs at the path used by Android Gradle plugin 3.0

### LINKED ISSUE #10630: Flutter doesn't understand filesystem paths used by gradle plugin 3.0.0
I'm using Android Studio 3 preview 3 and updated my gradle plugin version to 3.0.0-alpha3 and when running flutter run in terminal I get a FileSystemException. The path does exist on my machine so I'm unsure why the error is being generated. I also filed an issue related to running flutter build apk (link below).

https://github.com/flutter/flutter/issues/10629

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d FA71A0302167

## exception

FileSystemException: FileSystemException: Cannot copy file to 'build/app/outputs/apk/app.apk', path = 'build/app/outputs/apk/app-debug.apk' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.copySync (dart:io/file_impl.dart:321)
#2      _LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:25)
#3      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:250)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#5      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:354)
<asynchronous suspension>
#7      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:233)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:329)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#11     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:217)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:206)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#28     main (file:///Users/albertlardizabal/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 0f277fcc8a (6 days ago), 2017-06-06 17:19:27 +0200
    • Engine revision 8686a45810
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Pixel        • FA71A0302167                             • android-arm • Android 7.1.2 (API 25)
    •              • c0e109b7e55a826627aa0f3e79af8931534f3554 • ios         • iOS  ()
    • Posse iPhone • ac24c3de3cbe39efed542095769ce83fc89630f7 • ios         • iOS 10.3.1 (14E304)
    • iPhone 6     • 97A6FC25-AE09-4302-A8B3-565058389FE7     • ios         • iOS 10.3 (simulator)

```

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/10630

### CODE REVIEW

**Comment by jason-simmons** [comment]
@tvolkert

**Review by tvolkert — COMMENTED** [review]
Can you add a test?

**Comment by jason-simmons** [comment]
Added a test.

**Review by tvolkert — APPROVED** [review]

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 1]
```diff
@@ -211,6 +211,17 @@ Future<Null> buildGradleProjectV1(String gradle) async {
   printStatus('Built $gradleAppOutV1 (${getSizeAsMB(apkFile.lengthSync())}).');
 }
 
+File findApkFile(String buildDirectory, String buildModeName) {
+  final String apkFilename = 'app-$buildModeName.apk';
+  File apkFile = fs.file('$buildDirectory/$apkFilename');
+  if (apkFile.existsSync())
+    return apkFile;
```
Comment (skybrian) [inline packages/flutter_tools/lib/src/android/gradle.dart]: I don't think this will handle upgrades properly. When the user upgrades to the new Gradle plugin, the old apk might still be there. Since this code checks that location first, it will keep using the old apk (from before the upgrade) forever.

The workaround is to do a clean build (clearing the build directory), but this could be frustrating for the user to diagnose; it will just look like it doesn't work.

So, better to detect which Gradle plugin we're actually using and only look at its output location. Or maybe clear both locations before doing the build?
