### PR TITLE
made SelectionArea alignment consistent between web and other platform

### LINKED ISSUE #121053: SelectionArea causes inconsistent layout between web and other platforms
`SelectionArea` shrinks to the child size on the web while it expands to the parent size on other platforms. It lacks consistency. Tiny differences would be acceptable, but this bug causes a much bigger difference as shown below.

I see the issue regardless of the renderer type on the web.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App();

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SizedBox.square(
          dimension: 200,
          child: SelectionArea(
            child: Text('text'),
          ),
        ),
      ),
    );
  }
}
```
</details>

| Windows | Web |
|:-:|:-:|
|  |  |

**Another example:**

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox.expand(
          child: SelectionArea(
            child: Scrollbar(
              thumbVisibility: true,
              trackVisibility: true,
              child: SingleChildScrollView(
                primary: true,
                padding: const EdgeInsets.all(16.0),
                child: Text('text\n' * 100),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

| Windows | Web |
|:-:|:-:|
|  |  |

## Steps to Reproduce

Just run each sample above on web and other platforms.

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22000.1574], locale ja-JP)
    • Flutter version 3.7.3 on channel stable at D:\xxxxx\flutter\sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (10 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\xxxxx\android\sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = D:\xxxxx\android\sdk
    • Java binary at: C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3\jbr\bin\java
    • Java version OpenJDK Runtime Environment JBR-17.0.5+1-653.25-jcef (build 17.0.5+1-b653.25)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\xxxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1574]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.49

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

### LINKED ISSUE #148934: Unexpected Aligment in SelectionArea on Flutter Web
### Steps to reproduce

1. Create Flutter Web Project using Flutter version:  3.16.6 or above.
2. Create a basic screen and as its child add a couple of Text Widgets in a Column with crossAxisAligment as CrossAxisAligment.stretch.
4. Wrap any of the Text Widgets with SelectionArea.
5. Run the app on the Web.

### Expected results

Text alignment shouldn't be changed for only the text widget wrapped in SelectionArea.

### Actual results

Text alignment is center for only the text widget wrapped in SelectionArea.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() => runApp(const SelectionAreaExampleApp());

class SelectionAreaExampleApp extends StatelessWidget {
  const SelectionAreaExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('SelectionArea Sample')),
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            SelectionArea(child: Text('Row 1')),
            Text('Row 2'),
            Text('Row 3'),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
    • Flutter version 3.16.6 on channel stable at /Users/yash.dhrangdhar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (4 months ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yash.dhrangdhar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### LINKED ISSUE #149426: TabBarView with SelectionArea should not edge scroll with unsupported dragDevices
### Steps to reproduce

1. Drag the mouse to attempt to select both texts. "First tab" text first, and "Sidesheet" text second.
a. Notice the tab-view slowly start to transition to the next tab, then bounce back.
b. Also notice the "Sidesheet" text won't get selected.
2. Next, click the green column. This seems to reset the focus scope? 
3. Now click somewhere on the yellow sidesheet.
a. Notice the same tab-transitioning behaviour.

Hopefully the video makes sense if this doesn't ^

### Expected results

I'm not entirely sure if this behaviour is intentional, but I would not expect the tab view to begin its transition.

### Actual results

Tab view transition begins.

### Code sample

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: _Body(),
      ),
    );
  }
}

class _Body extends StatelessWidget {
  const _Body();

  @override
  Widget build(BuildContext context) {
    const tabs = [_Tab1(), _Tab2()];

    return SelectionArea(
      child: DefaultTabController(
        length: tabs.length,
        child: Row(
          children: [
            //* Space
            Container(
              color: Colors.green,
              width: 100,
              height: double.infinity,
            ),

            //* Tab bar + view
            const Expanded(
              child: Column(
                children: [
                  TabBar(
                    tabs: [
                      Tab(child: Text('Tab 1')),
                      Tab(child: Text('Tab 2')),
                    ],
                  ),
                  Expanded(
                    child: TabBarView(children: tabs),
                  ),
                ],
              ),
            ),

            //* Sidesheet
            Container(
              color: Colors.amber,
              width: 300,
              height: double.infinity,
              child: const Center(child: Text('Sidesheet')),
            ),
          ],
        ),
      ),
    );
  }
}

class _Tab1 extends StatelessWidget {
  const _Tab1();

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('First tab'));
  }
}

class _Tab2 extends StatelessWidget {
  const _Tab2();

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Second tab'));
  }
}

```

[Dart pad minimal reproducible example](https://dartpad.dev/?id=831ae54ab3083c47950404514782dcc8)

### Screenshots or Video

<details open>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/43067479/8298df8c-44ae-4352-8494-168dfd76c258

</details>

### Logs

_No response_

### Flutter Doctor output

N/A

### PR DESCRIPTION
**Pull request by LimaneGaya**
Currently, when text is placed inside a SelectionArea widget that's nested within a Column widget, it results in misalignment, causing the text to appear centered instead of aligned as intended.

This was originally #149552 but had issues with my branch.

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*
Fixes #148934 
Fixes #121053 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by LimaneGaya** [comment]
@Renzo-Olivares thank you for the review in #149552, i made all changes you suggested.

**Comment by kaboc** [comment]
Can you also have a look at #121053, please? I think this would likely fix it too.

**Comment by LimaneGaya** [comment]
@kaboc thanks, i tried your sample code and indeed, this seems to be fixing your issue too.

**Comment by kaboc** [comment]
Great! Thank you, too.

**Comment by kaboc** [comment]
@LimaneGaya FYI, a word like "Fixes" is necessary in front of each issue number to auto-close those issues when the changes in this PR is merged. The linked issues should be displayed in the "Development" section in the right column of this page.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 1]
```diff
@@ -3594,6 +3594,20 @@ void main() {
     skip: kIsWeb, // [intended] Web uses its native context menu.
   );
 
+  testWidgets('Ensure consistent layout of SelectionArea children between platforms', (WidgetTester tester) async {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3597]: This test should probably test that a SelectionArea wrapping a Text widget does not differ in alignment from a Text widget without a SelectionArea.

Something like below

```dart
Column(
    children: <Widget>[
        SelectionArea(child: Text()),
        Text(),
    ],
)
```

Both text widgets should begin at the same position on the x-axis.

Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3597]: nit: Add a comment at the top of this test similar to below

```
// Regression test for https://github.com/flutter/flutter/issues/#####.
```

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 2]
```diff
@@ -3594,6 +3594,20 @@ void main() {
...
+      const MaterialApp(
+        home: SelectionArea(
+          child: Text('Row 1'),
+        ),
+      ),
+    );
+    await tester.pumpAndSettle();
+    final Offset offset = tester.getTopLeft(find.byType(Text));
+    expect(offset, Offset.zero);
+  },
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3608]: nit: I think its okay to place these last two lines together on one line without a comma like below

```dart
});
```

File: packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart [hunk 3]
```diff
@@ -135,6 +135,9 @@ class PlatformSelectableRegionContextMenu extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     return Stack(
+      // Setting fit to StackFit.passthrough will prevent the child from
+      // misaligning on web and be consistent with other platforms.
+      fit: StackFit.passthrough,
       alignment: Alignment.center,
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:141]: I don't have a particular reason. I think I copied the code from pointerinterceptor or somwhere

**Comment by LimaneGaya** [comment]
Since there is no particular reason for alignment should it just be removed along with fit?

File: packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:141]: I think we should remove this alignment then instead of adding an explicit `Stack.fit`. I did some digging to see where this alignment originated in `pointer_interceptor` but didn't find a reason besides this commit when it was added [flutter/packages@`6adde6f` (#256)](https://github.com/flutter/packages/pull/256/commits/6adde6fe71ccf556cebd5bd22a2d003e4ca103d0) . Also talked to @ditman and removing the alignment didn't seem to have any adverse effects in our tests. The alignment is only affecting the position of the child widget since the `HTMLElementView` is wrapped with a `Positioned`.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 4]
```diff
@@ -3594,6 +3594,25 @@ void main() {
     skip: kIsWeb, // [intended] Web uses its native context menu.
   );
 
+  // Regression test for https://github.com/flutter/flutter/issues/148934
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3597]: #121053 seems to be the original issue. I think we should probably close #148934 as a duplicate.

Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3597]: nit: period at the end of this comment.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 5]
```diff
@@ -3594,6 +3594,25 @@ void main() {
...
+              Text('row 2'),
+            ],
+        ),
+      ),
+    );
+    await tester.pumpAndSettle();
+    final double xOffset1 = tester.getTopLeft(find.text('row 1')).dx;
+    final double xOffset2 = tester.getTopLeft(find.text('row 2')).dx;
+    expect(xOffset1, xOffset2);
+  });
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:3614]: I think we should probably run this test on all platforms with `variant: TargetPlatformVariant.all()`.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM, thank you for the contribution @LimaneGaya. This change will still need a secondary approval before being merged.

**Review by chunhtai — APPROVED** [review]
LGTM
