### PR TITLE
Fix color of icons in drawers in dark theme.

### LINKED ISSUE #1357: Stocks no longer uses white icons in dark theme

### PR DESCRIPTION
**Pull request by Hixie**
This makes it match the material spec more.
https://www.google.com/design/spec/style/icons.html

Fixes https://github.com/flutter/flutter/issues/1357

### CODE REVIEW

**Comment by Hixie** [comment]
cc @collinjackson this will probably conflict with you, sorry about that.

**Comment by Hixie** [comment]
I want to add some tests before I check this in.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
My fix is blossoming into something that also fixes https://github.com/flutter/flutter/issues/1507.

**Comment by Hixie** [comment]
This got out of hand. PTAL.

File: examples/stocks/test/icon_color_test.dart [hunk 1]
```diff
@@ -0,0 +1,105 @@
+import 'dart:ui' as ui show window;
```
Comment (abarth) [inline examples/stocks/test/icon_color_test.dart]: Copyright block?

File: examples/stocks/test/icon_color_test.dart [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  bool walker(Element ancestor) {
+    if (ancestor.widget.runtimeType == targetType)
+      result = ancestor;
+    return result == null;
+  }
+  node.visitAncestorElements(walker);
+  return result;
+}
+
+final RegExp materialIconAssetNameColorExtractor = new RegExp(r'[^/]+/ic_.+_(white|black)_[0-9]+dp\.png');
```
Comment (abarth) [inline examples/stocks/test/icon_color_test.dart]: Fragile...

File: examples/stocks/test/icon_color_test.dart [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+  // regardless of how the menu item is represented, so this is a good
+  // way to find the menu item. I hope.
+  Element semantics = findElementOfExactWidgetTypeGoingUp(tester.findText(label), MergeSemantics);
+  expect(semantics, isNotNull);
+  Element asset = findElementOfExactWidgetTypeGoingDown(semantics, AssetImage);
+  RenderImage imageBox = asset.findRenderObject();
+  Match match = materialIconAssetNameColorExtractor.firstMatch(asset.widget.name);
+  expect(match, isNotNull);
+  if (color == const Color(0xFFFFFFFF)) {
+    expect(match[1], equals('white'));
```
Comment (abarth) [inline examples/stocks/test/icon_color_test.dart]: We should probably just get rid of the white variants and colorize the black ones instead.

File: packages/flutter/lib/src/rendering/object.dart [hunk 4]
```diff
@@ -1712,6 +1712,22 @@ abstract class RenderObject extends AbstractNode implements HitTestTarget {
     return result;
   }
 
+  /// Returns a one-line detailed description of the render object.
+  ///
+  /// This includes the same information for this RenderOBject as given by
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/object.dart]: `RenderOBject`

File: packages/flutter/lib/src/rendering/object.dart [hunk 5]
```diff
@@ -1712,6 +1712,22 @@ abstract class RenderObject extends AbstractNode implements HitTestTarget {
...
+  /// [toStringDeep()], but does not recurse to any children.
+  String toStringDetail() {
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/object.dart]: Maybe `toStringShallow` ?

**Comment by abarth** [comment]
LGTM but travis is mad

**Comment by abarth** [comment]
Looks like that flaky canvas test.  Would you be willing to disable it again?

**Comment by Hixie** [comment]
Yeah. See https://github.com/flutter/flutter/issues/1854

File: examples/stocks/test/icon_color_test.dart (hunk 1 above)
Comment (Hixie) [inline examples/stocks/test/icon_color_test.dart]: added to this and locale_test

File: examples/stocks/test/icon_color_test.dart (hunk 2 above)
Comment (Hixie) [inline examples/stocks/test/icon_color_test.dart]: Yeah. I dunno how else to do this, short of your suggestion below.

File: examples/stocks/test/icon_color_test.dart (hunk 3 above)
Comment (Hixie) [inline examples/stocks/test/icon_color_test.dart]: White icons are common (more so than black ones, it seems). Colourising every icon seems not great for perf. I dunno though. It's causing other problems too -- e.g. we can't lerp between icon colours easily since they're sometimes colourised and sometimes not.

Comment (Hixie) [inline examples/stocks/test/icon_color_test.dart]: see also https://github.com/flutter/flutter/issues/1857

File: packages/flutter/lib/src/rendering/object.dart (hunk 4 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: fixed

File: packages/flutter/lib/src/rendering/object.dart (hunk 5 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: done

**Comment by Hixie** [comment]
Since you're adding ui.Image.toString, I've changed this patch to use that instead of inlining the [width x height] stuff.
