### PR TITLE
fix `SliverReorderableList` not work on Android platform bug

### LINKED ISSUE #103404: `SliverReorderableList` can not reorder on Android platform
### Code
```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  debugPrintGestureArenaDiagnostics = true;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> _items = List<int>.generate(5, (int index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverReorderableList(
            itemCount: _items.length,
            itemBuilder: (context, index) {
              print(index);

              return ReorderableDragStartListener(
                index: index,
                key: Key('$index'),
                child: Container(
                  color: Colors.red,
                  padding: const EdgeInsets.all(40.0),
                  child: Text(_items[index].toString()),
                ),
              );
            },
            onReorder: (int oldIndex, int newIndex) {
              setState(() {
                if (oldIndex < newIndex) {
                  newIndex -= 1;
                }

                final int item = _items.removeAt(oldIndex);
                _items.insert(newIndex, item);
              });
            },
          ),
        ],
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/103404

Was introduced by https://github.com/flutter/flutter/pull/97971

### CODE REVIEW

**Comment by xu-baolin** [comment]
This should release with #97971 CC @jonahwilliams

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -7,6 +7,65 @@ import 'package:flutter/material.dart';
 import 'package:flutter_test/flutter_test.dart';
 
 void main() {
+  testWidgets('SliverReorderableList works well when having gestureSettings', (WidgetTester tester) async {
```
Comment (jonahwilliams) [inline packages/flutter/test/widgets/reorderable_list_test.dart:10]: How does this catch the regression? The tester will have the same default touch slop value since it is not run on android - you'd need to override the platform config on the test window to provide a touch slop value that is different than the default value.

Comment (xu-baolin) [reply packages/flutter/test/widgets/reorderable_list_test.dart:10]: I have overridden the `MediaQueryData` of the pump widget.

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 2]
```diff
@@ -7,6 +7,65 @@ import 'package:flutter/material.dart';
...
+    // Regression test for https://github.com/flutter/flutter/issues/103404
+    debugPrintGestureArenaDiagnostics = true;
```
[the remark this answers is not in the document]
Comment (xu-baolin) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: done

**Review by jonahwilliams — APPROVED** [review]
Ahh got it. LGTM

**Comment by jonahwilliams** [comment]
Thanks @xu-baolin !
