### PR TITLE
Fixes InputDecorator to work with textScaleFactor, fixes Material Design differences.

### LINKED ISSUE #12485: Hint text on TextField isn't positioned correctly when textScaleFactor is large
When the textScaleFactor is large, the hint text appears in the middle of the field underline decoration, so either the underline location is not calculated correctly, or the hint position isn't.

screenshot_20171010-104453

### PR DESCRIPTION
**Pull request by gspencergoog**
There were a number of differences with the Material Design spec, including
several different padding values and underline thickness.  This corrects
that so that the decorator is in line with the Material Design spec now.

Also, the decorator properly handles changes to the textScaleFactor, where
before it would not re-layout when needed, painting the cursor and
underline incorrectly.

The decorator also now properly animates helper, error, and hint text when
the textScaleFactor or input decoration properties change.

Helper text is now properly displayed in dense mode, as the spec shows.
Before this change, it was never displayed in dense mode.

Fixes #12485

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -368,9 +368,13 @@ class InputDecorator extends StatelessWidget {
   /// Defaults to false.
   final bool isEmpty;
 
-  /// The widget below this widget in the tree.
+  /// The widget below this widget in the tree.  Typically, this is an [EditableText] widget.
```
Comment (Hixie) [inline packages/flutter/lib/src/material/input_decorator.dart]: I don't think that's true. In fact, of the two (non-test) cases where we create an InputDecorator in our code base, neither uses EditableText here. One uses a RepaintBoundary that contains an EditableText, and the other uses a Row to do fancy stuff.

I think most people using this directly will be doing so because they want to create a widget that matches a text field but isn't one.

Comment (gspencergoog) [reply packages/flutter/lib/src/material/input_decorator.dart]: OK, reverted.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -534,33 +535,43 @@ class InputDecorator extends StatelessWidget {
...
-      stackChildren.add(new Positioned(
-        left: 0.0,
-        right: 0.0,
-        bottom: 0.0,
-        child: new Text(
-          errorText ?? helperText,
-          style: subtextStyle,
-          textAlign: textAlign,
-          overflow: TextOverflow.ellipsis,
+      final double linePadding = _kBottomBorderHeight + (isDense ? _kDensePadding : _kNormalPadding) - 4.0;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/input_decorator.dart]: Same nit about -4.0 as above here.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -534,33 +535,43 @@ class InputDecorator extends StatelessWidget {
...
+      columnChildren.add(
+        new AnimatedContainer(
+          padding: new EdgeInsets.only(top: linePadding),
+          duration: _kTransitionDuration,
+          curve: _kTransitionCurve,
+          child: new Text(
+            errorText ?? helperText,
+            style: subtextStyle,
+            textAlign: textAlign,
+            overflow: TextOverflow.ellipsis,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/input_decorator.dart]: NICE

File: packages/flutter/test/material/input_decorator_test.dart [hunk 4]
```diff
@@ -52,4 +53,190 @@ void main() {
 
     expect(tester.element(find.byKey(key)).size, equals(const Size(800.0, 60.0)));
   });
+
```
Comment (HansMuller) [inline packages/flutter/test/material/input_decorator_test.dart]: Shouldn't we have a test that verifies that the divider (the text underline) appears when it's supposed and that it appears in the correct place?

**Review by HansMuller — COMMENTED** [review]
This looks good, just a few minor comments.

**Comment by HansMuller** [comment]
LGTM
