### PR TITLE
[gen_l10n] Handle single, double quotes, and dollar signs in strings

### LINKED ISSUE #54184: [gen_l10n] Localizations fail to generate with apostrophes or quotes in plural strings
## Steps to Reproduce

1. Create a plural string with quotes: `{count,plural, =1{Flutter's amazing, times 1!} other{Flutter's amazing, times {count}!}}`
2. Run the gen_l10n script
3. The generated output is not valid dart code

<details>
  <summary>Logs</summary>

<!--

```
[✓] Flutter (Channel master, v1.18.1-pre.5, on Mac OS X 10.15.4 19E266, locale en-DE)
    • Flutter version 1.18.1-pre.5 at /Users/perc/development/flutter
    • Framework revision ae497dca0a (3 minutes ago), 2020-04-07 12:33:25 +0200
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/perc/Library/Android/sdk
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 81158E5C-C27D-49D1-9FD9-55EE1011FEBF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.149
    • Web Server        • web-server                           • web-javascript • Flutter Tools

```

</details>

### LINKED ISSUE #54203: [gen_l10n] Cannot use dollar sign in ARB messages
Currently, the gen_l10n tool relies on '$' to interpolate variables when performing message lookup. However, this prevents using the dollar sign in any ARB messages.

cc/ @HansMuller @perclasson

### PR DESCRIPTION
**Pull request by perclasson**
## Description

Handle single quotes, double quotes and dollar signs in strings for gen_l10n script.

## Related Issues

Closes https://github.com/flutter/flutter/issues/54184
Closes https://github.com/flutter/flutter/issues/54203

## Tests

I updated the following tests:

- generated l10n classes produce expected localized strings

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]

File: dev/tools/localization/gen_l10n.dart [hunk 1]
```diff
@@ -131,7 +131,7 @@ String generatePluralMethod(Message message, AppResourceBundle bundle) {
           argValue = argValue.replaceAll('#${placeholder.name}#', '\${${placeholder.name}}');
         }
       }
-      pluralLogicArgs.add("      ${pluralIds[pluralKey]}: '$argValue'");
+      pluralLogicArgs.add('      ${pluralIds[pluralKey]}: ${generateString(argValue, escapeDollar: false)}');
```
Comment (HansMuller) [inline dev/tools/localization/gen_l10n.dart:134]: I realize that this is intended to behave mostly the way the existing code behaved. Are we missing another error here? What about a plural that contains dollar signs?

```
"singleQuotePlural": "{count,plural, $ =1{Flutter's amazing $, times 1!} other{Flutter's amazing $, times {count}!}}",
```

Comment (shihaohong) [reply dev/tools/localization/gen_l10n.dart:134]: @HansMuller Did you mean something like:
```
"dollarSignPlural": "{count,plural, =1{Flutter's amazing $, times {count}!} other{Flutter's amazing $, times {count}!}}",
```

I think the current way `generateString` works, it doesn't properly account for `$` correctly because we use `$` in the generated strings to interpolate variables into the messages. I'll file a separate issue for this, but we should unblock having this work for the other special JSON characters like quotes, return carriage, etc for now.

Comment (perclasson) [reply dev/tools/localization/gen_l10n.dart:134]: You're right, let me update the code and add a test for this.

**Review by shihaohong — APPROVED** [review]

File: dev/tools/localization/gen_l10n.dart (hunk 1 above)
Comment (perclasson) [reply dev/tools/localization/gen_l10n.dart:134]: I think by moving up the generateString function to before we do the interpolation of the variables, we can fix this. But it's probably best to handle it in a separate issue and add the extra test coverage that is needed.

Comment (shihaohong) [reply dev/tools/localization/gen_l10n.dart]: Created the issue here: https://github.com/flutter/flutter/issues/54203, had a discussion with @perclasson via DM -- We can solve the issue and add test coverage for it in the same PR. We would probably want to change the PR title and description to reflect the fixes this would address

**Review by shihaohong — APPROVED** [review]
LGTM. Thanks for figuring this one out!
