### PR TITLE
Fix CupertinoSliverNavigationBar's alwaysShowMiddle not working properly during page transition

### LINKED ISSUE #119522: CupertinoSliverNavigationBar's alwaysShowMiddle now working during page transition
## Steps to Reproduce
When I use a `CupertinoSliverNavigationBar` that transitions to a `CupertinoPageScaffold` containing a `CupertinoNavigationBar`, the hero transition looks all right, but the `middle` which should show only when the `CupertinoSliverNavigationBar` is scrolled is showing as well for a brief moment, both when pushing and popping the view.
I suppose this is the correct animation in case there's both a `largeTitle` and a `middle` visible, but it shouldn't be the case in case the `alwaysShowMiddle` property is set to false.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Actual results:** 

https://user-images.githubusercontent.com/73545081/215542280-39db1728-06ad-4087-bce7-6ec11cc03c8a.mov

<details>
<summary>Code sample</summary>

Here is some code to reproduce the issue

Page one:

```dart
CupertinoPageScaffold(
      child: CustomScrollView(
        slivers: [
          CupertinoSliverNavigationBar(
            largeTitle: Text('Test large Title'),
            middle: Text('Test middle'),
            alwaysShowMiddle: false,
            automaticallyImplyLeading: false,
            backgroundColor:
                CupertinoTheme.of(context).scaffoldBackgroundColor.withOpacity(0.7),
            stretch: true,
            border: null,
          ),
        ],
      ),
    );
```

Page two

```dart
CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Aggiungi'),
      ),
      child: Container(),
);
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by DavideDessi319**
This change fixes the CupertinoSliverNavigationBar's `middle` Widget showing for an instant during a page transition when the nav bar is not collapsed and `alwaysShowMiddle` is set to false. The PR adds a check on the transition's `hasUserMiddle` property based on the `alwaysShowMiddle` and the collapsed/expanded state of the nav bar.

Fixes #119522 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
@DavideDessi319 there's been some infrastructure issues with the tests. Could you please rebase onto the latest master branch?

**Comment by DavideDessi319** [comment]
> @DavideDessi319 there's been some infrastructure issues with the tests. Could you please rebase onto the latest master branch?

@MitchellGoodwin apologies for the delay on the rebase, it should be done now!
Thank you for the check 🙂

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for taking the time to fix this.

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart [hunk 1]
```diff
@@ -625,6 +625,75 @@ void main() {
     expect(flying(tester, find.byWidget(userMiddle)), findsOneWidget);
   });
 
+  testWidgets(
+      'Middle is not shown if alwaysShowMiddle is false and the nav bar is expanded',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/cupertino/nav_bar_transition_test.dart:630]:
```suggestion
  testWidgets('Middle is not shown if alwaysShowMiddle is false and the nav bar is expanded', (WidgetTester tester) async {
```

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart [hunk 2]
```diff
@@ -625,6 +625,75 @@ void main() {
...
+    );
+
+    await tester.pump(const Duration(milliseconds: 50));
+
+    expect(flying(tester, find.byWidget(userMiddle)), findsNothing);
+  });
+
+  testWidgets(
+      'Middle is shown if alwaysShowMiddle is false but the nav bar is collapsed',
+      (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/cupertino/nav_bar_transition_test.dart:649]:
```suggestion
  testWidgets('Middle is shown if alwaysShowMiddle is false but the nav bar is collapsed', (WidgetTester tester) async {
```

**Review by Piinks — APPROVED** [review]
LGTM with a few style guide nits!
