### PR TITLE
Fix asset transformation in the presence of resolution-aware asset variants

### LINKED ISSUE #151813: Asset transformers overwrite the asset for pixel-density variants and fail
```
Target web_release_bundle failed: Error: User-defined transformation of asset "/Users/albert/Projects/Playground/asset_transformers_bug/assets/image.jpg" failed.
Asset transformer transformer did not produce an output file.
Input file provided to transformer: "/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Eh410U/image.jpg-transformOutput0.jpg"
Expected output file at: "/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Eh410U/image.jpg-transformOutput1.jpg"
Full command: /Users/albert/fvm/versions/3.22.2/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Eh410U/image.jpg-transformOutput0.jpg
  --output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Eh410U/image.jpg-transformOutput1.jpg
```

### Steps to reproduce

1. Prepare the project like in the **Code sample** section.
2. Clean the project so there's no asset transformer cache `flutter clean`.
3. Run `flutter build web --verbose.

Whether it fails or not depends on how fast the asset transformer finishes its work. I put a delay with `Random()` between 1 and 0 seconds delay, so if the build succeeded, please retry `flutter clean` and `flutter build web --verbose` until it fails.

### Expected results

The build succeeds.

### Actual results

Asset transformer fails as seen in the **Logs** section.

Asset transformers operate on the assets in some temporary directory, but in case of pixel-density variants (the `image.jpg`, `2.0x/image.jpg`, etc.) the assets are moved to the same path, ignoring the `2.0x/` directories in their paths. As a result, for such three assets, the asset transformer works on only one path and very often fails because of that (or it may also lead to unwanted results). Below is the key fragment of logs:

```
[   +2 ms] Transforming asset using command '/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg
--output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg'
[        ] Transforming asset using command '/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg
--output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg'
```

Here's what I think is happening:

1. Flutter CLI runs asset transformer for `assets/image.jpg` (input path X, output path Y)
2. Flutter CLI runs asset transformer for `assets/2.0x/image.jpg` (input path X, output path Y - **same as the previous one!**)
3. Transforming of `assets/image.jpg` is done.
4. Transforming of `assets/2.0x/image.jpg` is done.
5. Flutter CLI copies the output of `assets/image.jpg` transformation from file in path Y and cleans it afterward (file in path Y is removed)
6. Flutter CLI copies the output of `assets/2.0x/image.jpg` transformation from file in path Y... **it does not exist!**

### Code sample

<details open><summary>Code sample</summary>

1. Create a project with `flutter create --platforms web asset_transformers_bug`
2. Enter that dir `cd asset_transformers_bug`
3. Create new project for the asset transformer itself `dart create -tcli transformer`
4. Paste the following code in the following files

```yaml
# asset_transformers_bug/pubspec.yaml

name: asset_transformers_bug

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  transformer:
    path: transformer

flutter:
  uses-material-design: true
  assets:
    - path: assets/image.jpg
      transformers:
        - package: transformer

```

```dart
// asset_transformers_bug/lib/main.dart

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: Image.asset('assets/image.jpg'),
        ),
      ),
    ),
  );
}

```

```dart
// asset_transformers_bug/transformer/bin/transformer.dart

import 'dart:io';
import 'dart:math';

import 'package:args/args.dart';

ArgParser buildParser() {
  return ArgParser()
    ..addOption('input')
    ..addOption('output');
}

void main(List<String> arguments) async {
  final argParser = buildParser();
  try {
    final results = argParser.parse(arguments);

    final input = results.option('input')!;
    final output = results.option('output')!;

    await Process.run('cp', [input, output]);

    final delay = Random().nextInt(2) == 1 ? 1 : 0;
    await Future.delayed(Duration(seconds: delay));
  } on FormatException catch (e) {
    // Print usage information if an invalid argument was provided.
    print(e.message);
    print('');
  }
}

```

Put any image (for example [this](https://images.pexels.com/photos/6000789/pexels-photo-6000789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)) into `asset_transformers_bug/assets/image.jpg` and `asset_transformers_bug/assets/2.0x/image.jpg`.

</details>

### Screenshots or Video

_No response_

### Logs

I've created this code example on Flutter `3.24.0-0.0.pre` because I wanted to have the asset transformers traces #146374, but I first found it out on Flutter 3.22.2.

<details open><summary>Logs</summary>

```console
(...)
[+6877 ms] Compiled 42,555,800 input bytes (8,573,281 characters source) to 1,277,550 characters JavaScript in 6.73 seconds using 594.438 MB of memory
[  +18 ms] dart2js: Complete
[ +243 ms] web_release_bundle: Starting due to {}
[  +60 ms] shaderc command: [/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/artifacts/engine/darwin-x64/impellerc, --sksl, --iplr, --json, --sl=build/web/assets/shaders/ink_sparkle.frag, --spirv=build/web/assets/shaders/ink_sparkle.frag.spirv,
--input=/Users/albert/fvm/versions/3.24.0-0.0.pre/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --include=/Users/albert/fvm/versions/3.24.0-0.0.pre/packages/flutter/lib/src/material/shaders,
--include=/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/artifacts/engine/darwin-x64/shader_lib]
[   +2 ms] Transforming asset using command '/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg
--output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg'
[        ] Transforming asset using command '/Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg
--output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg'
[  +15 ms] Running command: /Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/artifacts/engine/darwin-x64/const_finder.dart.snapshot --kernel-file
/Users/albert/Projects/Playground/asset_transformers_bug/.dart_tool/flutter_build/676642b58d55dac85560580d77372536/app.dill --class-library-uri package:flutter/src/widgets/icon_data.dart --class-name IconData --annotation-class-name _StaticIconProvider
--annotation-class-library-uri package:flutter/src/widgets/icon_data.dart
[ +456 ms] Finished transforming asset at path '/Users/albert/Projects/Playground/asset_transformers_bug/assets/2.0x/image.jpg' (473ms)
[ +311 ms] Expected to find fontFamily for constant IconData with codepoint: 9658.0, but found fontFamily: null. This usually means you are relying on the system font. Alternatively, font families in an IconData class can be provided in the assets section of your pubspec.yaml, or
you are missing "uses-material-design: true".
[   +1 ms] Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the
package
           that would include them, or are missing "uses-material-design: true".
[        ] Running font-subset: /Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/artifacts/engine/darwin-x64/font-subset build/web/assets/fonts/MaterialIcons-Regular.otf /Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf,
using codepoints 57490 62832 57706 58332 58727 57496 57694 57695 57657 57882 57504 61453 57634 57498 57926 57704 57491 61061 61060 62834 62833 59283 59282 57499 57500 61069 61068 62842 62841 59291 59290 58011 58012 61575 61576 63348 63349 59797 59798 58372 58370 61930 61927 63708
63705 60157 60154 58771 58189 62328 61752 983402 63526 60555 59975 57502 58814 58813 57846 57862 57686 61764 57402 optional:32
[  +15 ms] Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7692 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
[ +688 ms] Persisting file store
[   +5 ms] Done persisting file store
[   +4 ms] Target web_release_bundle failed: Error: User-defined transformation of asset "/Users/albert/Projects/Playground/asset_transformers_bug/assets/image.jpg" failed.
           Asset transformer transformer did not produce an output file.
           Input file provided to transformer: "/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg"
           Expected output file at: "/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg"
           Full command: /Users/albert/fvm/versions/3.24.0-0.0.pre/bin/cache/dart-sdk/bin/dart run transformer --input=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput0.jpg
           --output=/var/folders/mh/n8gr4_w94sndpqg3619xhxxh0000gn/T/flutter_tools.Us7XSm/image.jpg-transformOutput1.jpg
           stdout:
           
           stderr:
           
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:157:19)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
           <asynchronous suspension>
           #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:128:3)
           <asynchronous suspension>
           #4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:448:29)
           <asynchronous suspension>
           #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
           <asynchronous suspension>
           #6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
           <asynchronous suspension>
           #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
           <asynchronous suspension>
           #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
           <asynchronous suspension>
           #9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
           <asynchronous suspension>
           #10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:227:5)
           <asynchronous suspension>
           #11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[   +8 ms] Compiling lib/main.dart for the Web... (completed in 15.0s)
[        ] "flutter web" took 15,453ms.
[   +2 ms] Error: Failed to compile application for the Web.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.24.0-0.0.pre, on macOS 14.5 23F79 darwin-arm64, locale en-PL)
    ! Flutter version 3.24.0-0.0.pre on channel [user-branch] at /Users/albert/fvm/versions/3.24.0-0.0.pre
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 84b3f0ab79 (13 days ago), 2024-07-03 07:01:05 -0400
    • Engine revision 8274f54f11
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

</details>

### PR DESCRIPTION
**Pull request by andrewkolos**
For the necessary background knowledge, see the flutter.dev content on [Resolution-aware image assets](https://docs.flutter.dev/ui/assets/assets-and-images#resolution-aware) and [Conditional bundling of assets based on app flavor](https://docs.flutter.dev/ui/assets/assets-and-images#conditional-bundling-of-assets-based-on-app-flavor) if you don't have a basic understanding of these features.

Fixes https://github.com/flutter/flutter/issues/151813 by using unique temporary directories, per asset file, for transformations. Currently, only a single directory is used and the name of the temporary files was based only on the basename of files. This means that `assets/image.png` and `assets/2x/image.png` would share an output path (`<temp dir path>/image.png`), causing a race. If this quick and rough explanation is a bit confusing, the original issue—#151813—provides a full repro and correct identification of the exact cause of the failure that can occur in the asset transformation process.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart [hunk 1]
```diff
@@ -55,15 +55,18 @@ final class AssetTransformer {
...
-    String getTempFilePath(int transformStep) {
+    final Directory tempDirectory = _fileSystem.systemTempDirectory.createTempSync();
+
+    File newTempFile(int transformStep) {
       final String basename = _fileSystem.path.basename(asset.path);
       final String ext = _fileSystem.path.extension(asset.path);
-      return '$basename-transformOutput$transformStep$ext';
+
+      return tempDirectory.childFile('$basename-transformOutput$transformStep$ext');
     }
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart:65]: Consider an app with `assets/image.png` and `assets/2x/image.png`.

One drawback with this approach is that the temporary file paths can't be mapped back to the original file, which can be useful while troubleshooting asset transformations. Consider this output from verbose logs:

```
[        ] Transforming asset using command '/Users/andrewkolos/Documents/GitHub/flutter/bin/cache/dart-sdk/bin/dart run grayscale_transformer --input=/var/folders/qh/m_ckdxls0xvfc7ccjj13yjjw010s5h/T/flutter_tools.9R9Ku0/paKIvd/image.png-transformOutput0.png --output=/var/folders/qh/m_ckdxls0xvfc7ccjj13yjjw010s5h/T/flutter_tools.9R9Ku0/paKIvd/image.png-transformOutput1.png'
[        ] Transforming asset using command '/Users/andrewkolos/Documents/GitHub/flutter/bin/cache/dart-sdk/bin/dart run grayscale_transformer --input=/var/folders/qh/m_ckdxls0xvfc7ccjj13yjjw010s5h/T/flutter_tools.9R9Ku0/ns1fB4/image.png-transformOutput0.png --output=/var/folders/qh/m_ckdxls0xvfc7ccjj13yjjw010s5h/T/flutter_tools.9R9Ku0/ns1fB4/image.png-transformOutput1.png'
```

It's not possible to tell which of these corresponds to `assets/image.png` and which corresponds to `assets/2x/image.png`.

One alternative, more intuitive, solution would be to include the path of the asset (relative to the project directory) into the temp file path. However, I don't believe anything restricts assets to being within the project directory (IIRC there are known "bugs" that occur with such assets depending on target platform). While such a thing might be worth breaking, I want this fix to be cherry-pickable, so I avoided doing this in this PR.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart:65]: > One alternative, more intuitive, solution would be to include the path of the asset (relative to the project directory) into the temp file path

Would it be possible to have the tool store (in memory) the mapping from source input to temp path, solely for the use of surfacing in these kind of trace logs?

In any case, leaving this potential work for later, in a non-CP change SGTM.

File: packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart [hunk 2]
```diff
@@ -55,15 +55,18 @@ final class AssetTransformer {
     required Logger logger,
   }) async {
 
-    String getTempFilePath(int transformStep) {
+    final Directory tempDirectory = _fileSystem.systemTempDirectory.createTempSync();
+
+    File newTempFile(int transformStep) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart:60]: maybe if we change this it should be in another change, but the dependence on the caller keeping track of unique steps seems error prone. Would it be reasonable for this function to keep track of its invocations itself, to ensure even across refactors or new or removed invocations this int monotonically increases?

File: packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart [hunk 3]
```diff
@@ -90,15 +90,14 @@ final class AssetTransformer {
           await tempOutputFile.copy(outputPath);
         } else {
           tempInputFile = tempOutputFile;
-          tempOutputFile = _fileSystem.systemTempDirectory.childFile(getTempFilePath(i+2));
+          tempOutputFile = newTempFile(i+2);
           ErrorHandlingFileSystem.deleteIfExists(tempOutputFile);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart:94]: is this needed, given the `finally` delete at line 100?

File: packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart [hunk 4]
```diff
@@ -316,6 +317,92 @@ flutter:
     ),
   });
 
+  {
+    final List<String> inputFilePaths = <String>[];
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: I think this should be late and initialized for every test run in a `setUp` function--or just inlined in the one test we have here. Otherwise we'll leak the mutable state of these lists between tests, right?

File: packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart]: One of the requirements of an asset transformer is that it must produce an output file. The only (reliable and easy) way to be sure that a transformer did produce an output file is to make sure it didn't already exist before the transformer was called. This is why we have this preparatory delete call (and the one on [L70](https://github.com/flutter/flutter/blob/747d76dd1acc59c31766da6c8193dfd27d7fcb4a/packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart#L70)).

Regardless, your question identifies that this isn't as clear as it should be. I've pushed a new commit, [move preparatory deleting of output file closer to the transformation…](https://github.com/flutter/flutter/pull/151932/commits/07439e25f5c06f0a31a05d5c5af047ec65bc8056), that hopefully improves this. Let me know what you think.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/build_system/tools/asset_transformer.dart]: :+1:

File: packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart (hunk 4 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: These are housed within a block scope that only contains one test. Are you afraid that tests will be added to this block in the future?
If the block construct is a bit too subtle, would you prefer a `group` to be used instead (with an empty `test` description)?

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: To put it another way, IMO this is mutating global state and an antipattern:

```dart
{
  final list = <Object>[];
  test("only one test...for now", () {
    list.add(0);
    expect(list.length, 1);
  });
}
```

But this is (more or less) hermetic:

```dart
group("_", () {
  late List<Object> list;
  setUp(() {
    list = <Object>[];
  });
  test("only one test...for now", () {
    list.add(0);
    expect(list.length, 1);
  });
});
```

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: The issue is not the unnamed block, but the mutable state initialized once in the block.

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: Since our style guide forbids `setUp` (https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#make-each-test-entirely-self-contained) you can do:

```
group("_", () {
  List<Object> init() => <Object>[];
  test("only one test...for now", () {
    final List<Object> = init();
    list.add(0);
    expect(list.length, 1);
  });
});
```

Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: Thanks for clarifying. I don't think your pattern can be directly applied here. The `ProcessManager` is provided as a `Context`-housed global, and the lists need to be accessed by the `FakeCommand`. Therefore, the lists would still need to be initialized outside of the test body.

However, we don't need to provide a `ProcessManager` as a global[^*] since `Environment` accepts one in its constructor, so I declared a `FakeProcessManager` within the test body and used that instead. See commit [avoid mutable objects scoped outside of test body](https://github.com/flutter/flutter/pull/151932/commits/db927b511e246d14d447df8028a68edbf3117b5d).

[^*]: We actually still do because IIRC `testUsingContext` requires providing one if a `FileSystem` is provided, but I think it's okay to provide a second one via `FakeProcessManager.empty()` here.

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart:321]: LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM
