### PR TITLE
Fix single ToggleButton border painting bugs

### LINKED ISSUE #73725: ToggleButtons widget does not apply border radius when there is only one child
Screen Shot 2021-01-11 at 12 05 12 PM

In this screenshot the "Slow Animations" button is a `ToggleButtons` widget with a single child. The "DebugPaint" and "Paint Baselines" group is also a `ToggleButtons` widget, but with two children. Both have `ToggleButtons.borderRadius` set to `const BorderRadius.all(Radius.circular(4.0))`, but the radius is only applied to the group with multiple children.

### PR DESCRIPTION
**Pull request by xu-baolin**
This patch fixes two bugs:
### Expected: 
image
   ### Actual:
image

## 2, Border-radius paint incorrect when `Radius.x` or `Radius.y` equal 0.0
```dart
  borderRadius: BorderRadius.only(
    topRight: Radius.elliptical(10, 0),
    topLeft: Radius.elliptical(0, 10),
    bottomRight: Radius.elliptical(0, 10),
    bottomLeft: Radius.elliptical(10, 0),
  ),
```
   ### Expected: 
image
  ### Actual:
image

## Related Issues
Fixes #73725

### CODE REVIEW

File: packages/flutter/lib/src/material/toggle_buttons.dart [hunk 1]
```diff
@@ -1269,11 +1278,12 @@ class _SelectToggleButtonRenderObject extends RenderShiftedBox {
...
     final RRect rrect = RRect.fromRectAndCorners(
       center,
-      topLeft: borderRadius.topLeft,
-      topRight: borderRadius.topRight,
-      bottomLeft: borderRadius.bottomLeft,
-      bottomRight: borderRadius.bottomRight,
+      topLeft: (borderRadius.topLeft.x * borderRadius.topLeft.y != 0.0) ? borderRadius.topLeft : Radius.zero,
+      topRight: (borderRadius.topRight.x * borderRadius.topRight.y != 0.0) ? borderRadius.topRight : Radius.zero,
+      bottomLeft: (borderRadius.bottomLeft.x * borderRadius.bottomLeft.y != 0.0) ? borderRadius.bottomLeft : Radius.zero,
+      bottomRight: (borderRadius.bottomRight.x * borderRadius.bottomRight.y != 0.0) ? borderRadius.bottomRight : Radius.zero,
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/toggle_buttons.dart:1284]: This change fixes the #2 bug.

File: packages/flutter/lib/src/material/toggle_buttons.dart [hunk 2]
```diff
@@ -1299,8 +1309,25 @@ class _SelectToggleButtonRenderObject extends RenderShiftedBox {
       rrect.brRadiusY * 2,
     );
 
+    final Paint leadingPaint = leadingBorderSide.toPaint();
+    // Only one button.
+    if (isFirstButton && isLastButton) {
+      final Path leadingPath = Path();
+      final double startX = (rrect.brRadiusX == 0.0) ? outer.right : rrect.right - rrect.brRadiusX;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/toggle_buttons.dart:1316]: If the radius is zero, we should paint a little more to connect the start and stop ends.
Otherwise, there will be a gap like below:

**Comment by skia-gold** [comment]
Gold has detected about 9 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/73780

File: packages/flutter/test/material/toggle_buttons_test.dart [hunk 3]
```diff
@@ -891,13 +891,6 @@ void main() {
       expect(
         toggleButtonRenderObject,
         paints
-          // trailing side
```
Comment (xu-baolin) [inline packages/flutter/test/material/toggle_buttons_test.dart:894]: If only one button, we can paint the border with one path now.

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/73780

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/73780

File: packages/flutter/lib/src/material/toggle_buttons.dart (hunk 1 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/toggle_buttons.dart:1284]: My first instinct was that some kind of elliptical rounded corner to be drawn anyway instead of having none at all. Is this because of the `drawArc` API that we're using? For now, this looks good.

File: packages/flutter/lib/src/material/toggle_buttons.dart (hunk 2 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/toggle_buttons.dart:1316]: Nice, good catch here

File: packages/flutter/test/material/toggle_buttons_test.dart [hunk 4]
```diff
@@ -1510,6 +1468,80 @@ void main() {
...
+          color: theme.colorScheme.onSurface.withOpacity(0.12),
+          strokeWidth: _defaultBorderWidth,
+        ),
+    );
+
+    await expectLater(
+      find.byType(RepaintBoundary),
+      matchesGoldenFile('toggle_buttons.oneButton.boardsPaint.png'),
+    );
+  },);
```
Comment (shihaohong) [inline packages/flutter/test/material/toggle_buttons_test.dart:1514]: nit:
```suggestion
  });
```

File: packages/flutter/test/material/toggle_buttons_test.dart [hunk 5]
```diff
@@ -1510,6 +1468,80 @@ void main() {
...
+          ),
+        ),
+      ),
+    );
+
+    await expectLater(
+      find.byType(RepaintBoundary),
+      matchesGoldenFile('toggle_buttons.oneButton.boardsPaint2.png'),
+    );
+  },);
```
Comment (shihaohong) [inline packages/flutter/test/material/toggle_buttons_test.dart:1543]: nit:
```suggestion
  });
```

**Review by shihaohong — APPROVED** [review]
LGTM with a small nit. Thanks for the fix!

**Comment by xu-baolin** [comment]
Thanks for the review.
Could you[ triage the golden files](https://github.com/flutter/flutter/pull/73780#issuecomment-758623646) for me additional? There seems to be something wrong with my permissions.

File: packages/flutter/lib/src/material/toggle_buttons.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/toggle_buttons.dart:1284]: Exactly correct.

**Comment by skia-gold** [comment]
Gold has detected about 9 untriaged digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/73780

**Comment by shihaohong** [comment]
Just approved the gold triage 👍
