### PR TITLE
[flutter_tools] prevent hot reload/restart if device has not finished devFS initialization

### LINKED ISSUE #72702: [tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:429:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:494:5)
<asynchronous suspension>
#3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Users\Keyur's\flutter
    • Framework revision 022b333a08 (5 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Keyur's\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Keyur's\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Keyur's\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • SM A505F (mobile) • 192.168.1.129:5555 • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 022b333a089afb81c471ec43d1f1f4f26305d876

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

If a hot restart is called before setupDevFS, the tool will hit an NPE looking up asset paths to evict on the non-existent devFS. For a quick fix, check if any are null and return a message the initialization is not complete.

A better long term fix would probably avoid making the service extensions available until after all initialization is complete

Fixes https://github.com/flutter/flutter/issues/72702

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I'm not quite sure this is the best fix, but it will keep the rest of the resident runner code from running while in a bad state so I think it is a strict improvement.

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 1]
```diff
@@ -592,6 +589,9 @@ class HotRunner extends ResidentRunner {
     bool silent = false,
     bool pause = false,
   }) async {
+    if (flutterDevices.every((FlutterDevice device) => device.devFS == null)) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/run_hot.dart:592]: Should this be `any`?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/run_hot.dart:592]: d'oh, yeah

**Review by zanderso — APPROVED** [review]
