### PR TITLE
Wait for CONFIGURATION_BUILD_DIR to update when debugging with Xcode

### LINKED ISSUE #135442: Xcode 15 launch failure with iOS 17 "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data."
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This doesn't happen to me consistently, but there are various reports of this issue:
https://github.com/flutter/flutter/issues/134667#issuecomment-1730978188
https://github.com/flutter/flutter/issues/134667#issuecomment-1732321539
https://github.com/flutter/flutter/issues/135208#issuecomment-1729735614

 The only way I've been able to relatively consistently recreate is

1. Create a flutter project
2. Do `flutter run`
3. Do `flutter clean`
4. Do `flutter run --profile` on an iOS 17 device

### Actual results

Xcode has this error: Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.

Screenshot 2023-09-25 at 11 47 46 AM

<details>
<summary>Show Details</summary>

```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-25 16:47:36 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///xxx/Library/Developer/Xcode/DerivedData/Runner-cvrsbfztnjtwapghkyzoauztkppf/Build/Products/Debug-iphoneos/Runner.app";
}
--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPad14,3";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 5;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.5.2 (Build 22G91)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-25T11:47:36-05:00
```
</details>

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
So there appears to be a race situation between the flutter CLI and Xcode. In the CLI, we update the `CONFIGURATION_BUILD_DIR` in the Xcode build settings and then tell Xcode to install, launch, and debug the app. When Xcode installs the app, it should use the `CONFIGURATION_BUILD_DIR` to find the bundle. However, it appears that sometimes Xcode hasn't processed the change to the build settings before the install happens, which causes it to not be able to find the bundle.

Fixes https://github.com/flutter/flutter/issues/135442

--- 

Since it's a timing issue, there's not really a consistent way to test it.

I was able to confirm that it works, though, by using the following steps:
1. Create a flutter project
2. Open the project in Xcode
3. `flutter clean`
4. `flutter run --profile -v`

If I saw a print line `stderr: CONFIGURATION_BUILD_DIR: build/Debug-iphoneos`, that means it first found the old and incorrect `CONFIGURATION_BUILD_DIR` before updating to the the new, so I was able to confirm that it would wait until it updated.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -723,6 +723,18 @@ class IOSDevice extends Device {
...
+        // When debugging via Xcode, after the app launches, reset the Generated
+        // settings to not include the custom configuration build directory.
+        // This is to prevent confusion if the project is later ran via Xcode
+        // rather than the Flutter CLI.
+        await updateGeneratedXcodeProperties(
+          project: FlutterProject.current(),
+          buildInfo: debuggingOptions.buildInfo,
+          targetOverride: mainPath,
+        );
+      }
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/ios/devices.dart:737]: This is just moved so that it resets the settings after the Dart VM url has been found, rather than directly after starting the Xcode debug process. 

There wasn't any reason to indicate that this was the cause of the issue, but it doesn't hurt to do it a little later, so just to be safe I moved it.

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart [hunk 2]
```diff
@@ -310,6 +317,7 @@ class XcodeDebug {
           _xcode.xcodeAppPath,
           '-g', // Do not bring the application to the foreground.
           '-j', // Launches the app hidden.
+          '-F', // Open "fresh", without resorting windows.
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/ios/xcode_debug.dart:320]: This is not actually related to the fix, but just a same improvement. I noticed sometimes when opening Xcode, it will open the project as well as other previously opened Xcode windows. This prevents that and just opens the targeted project.

File: .ci.yaml [hunk 3]
```diff
@@ -4143,7 +4138,6 @@ targets:
         {
           "sdk_version": "14c18"
         }
-    bringup: true
 
   - name: Mac_ios native_assets_ios_simulator
```
Comment (vashworth) [inline .ci.yaml:4142]: Temporarily moved Xcode debug tests to presubmit, so I could confirm they still pass. Will move back around PR is reviewed

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 4]
```diff
@@ -723,6 +723,18 @@ class IOSDevice extends Device {
       return LaunchResult.failed();
     } finally {
       startAppStatus.stop();
+
+      if ((isCoreDevice || forceXcodeDebugWorkflow) && debuggingOptions.debuggingEnabled && package is BuildableIOSApp) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/devices.dart:727]: for my own knowledge, what determines the value of `debuggingOptions.debuggingEnabled`? Is it just the build mode, are there more complicated rules?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/devices.dart:727]: Also, in what situations would we reach this far and `package is! BuildableIOSApp`?

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/devices.dart:727]: For your first question: `debuggingOptions.debuggingEnabled` is only determined by the build mode. Release mode would be `false` and debug and profile mode would be true.

https://github.com/flutter/flutter/blob/cb4b4d4ac93981d9f22aa17ce5e10b22346b4700/packages/flutter_tools/lib/src/commands/run.dart#L236-L309

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/devices.dart:727]: For your second question: it will reach this far always regardless of if it's `BuildableIOSApp` or `PrebuiltIOSApp`. We check if it's a `BuildableIOSApp` because we only alter the build settings in the first place if it's a `BuildableIOSApp`
https://github.com/flutter/flutter/blob/cb4b4d4ac93981d9f22aa17ce5e10b22346b4700/packages/flutter_tools/lib/src/ios/devices.dart#L838-L850

File: packages/flutter_tools/bin/xcode_debug.js [hunk 5]
```diff
@@ -529,3 +573,91 @@ function stopApp(xcode, args) {
...
+ * @param {!CommandArguments} args
+ * @returns {!FunctionResult} Always returns null as the `result`.
+ */
+function waitForConfigurationBuildDirToUpdate(targetWorkspace, args) {
+  // Get the project
+  let project;
+  try {
+    project = targetWorkspace.projects().find(x => x.name() == args.projectName);
+  } catch (e) {
+    return new FunctionResult(null, `Failed to find project ${args.projectName}: ${e}`);
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/xcode_debug.js:593]: Does this fail the build?

File: packages/flutter_tools/bin/xcode_debug.js [hunk 6]
```diff
@@ -529,3 +573,91 @@ function stopApp(xcode, args) {
...
+    // Wait up to 2 minutes for the CONFIGURATION_BUILD_DIR to update to the
+    // expected value.
+    const checkFrequencyInSeconds = 0.5;
+    const maxWaitInSeconds = 2 * 60; // 2 minutes
+    const verboseLogInterval = 10 * (1 / checkFrequencyInSeconds);
+    const iterations = maxWaitInSeconds * (1 / checkFrequencyInSeconds);
+    for (let i = 0; i < iterations; i++) {
+      const verbose = args.verbose && i % verboseLogInterval === 0;
+
+      const configurationBuildDir = configurationBuildDirSettings.value();
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/xcode_debug.js:650]: what does this do? Is this calling an Xcode API?

Comment (vashworth) [reply packages/flutter_tools/bin/xcode_debug.js:650]: Yes, it calls an Xcode API that gets the value of the setting

File: packages/flutter_tools/bin/xcode_debug.js (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/bin/xcode_debug.js:593]: :+1:

File: packages/flutter_tools/bin/xcode_debug.js [hunk 7]
```diff
@@ -529,3 +573,91 @@ function stopApp(xcode, args) {
...
+      if (verbose) {
+        console.log(`CONFIGURATION_BUILD_DIR: ${configurationBuildDir}`);
+      }
+      if (configurationBuildDir === args.expectedConfigurationBuildDir) {
+        return new FunctionResult(null, null);
+      }
```
Comment (christopherfujino) [inline packages/flutter_tools/bin/xcode_debug.js:656]: suggestion, fleshing the logs out a little bit more so at a glance it's clear we're still polling. something like:

```suggestion
      if (configurationBuildDir === args.expectedConfigurationBuildDir) {
        console.log(`CONFIGURATION_BUILD_DIR: ${configurationBuildDir}`);
        return new FunctionResult(null, null);
      }
      if (verbose) {
        console.log(`Current CONFIGURATION_BUILD_DIR: ${configurationBuildDir} while expecting ${args.expectedConfigurationBuildDir}`);
      }
```

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/devices.dart:727]: ahh, thanks.

**Review by christopherfujino — APPROVED** [review]
nit about the log message, but LGTM
