### PR TITLE
Replace ideviceinfo and idevice_id with xcdevice

### LINKED ISSUE #36524: ideviceinfo could not connect to lockdownd, error code -7
## Steps to Reproduce

When trying to run the application on an emulator or real device on Android studio or VS code the error is thrown "ideviceinfo could not connect to lockdownd, error code -7".

The program runs off Xcode only.

The problem seems to have started after the last mac iOS update.

## Logs

Run with `flutter run --verbose`
```
[  +39 ms] executing: [/Users/earyzhe/dev/SDKs/flutter/] git log -n 1 --pretty=format:%H
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b712a172f9694745f50505c93340883493b505e5
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.7.8+hotfix.3-0-gb712a172f
[  +13 ms] executing: [/Users/earyzhe/dev/SDKs/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/Users/earyzhe/dev/SDKs/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +226 ms] executing: /Users/earyzhe/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/earyzhe/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +11 ms] executing: idevice_id -h
[+30080 ms] "flutter run" took 30,314ms.
[        ] "flutter run" took 30,314ms.
[  +59 ms] executing: [/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project
/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Runner.xcodeproj -target Runner -showBuildSettings
[+1585 ms] Exit code 0 from: /usr/bin/xcodebuild -project /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Runner.xcodeproj -target Runner -showBuildSettings
[        ] Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = earyzhe
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               ARCHS = armv7 arm64
               ARCHS_STANDARD = armv7 arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               BUILD_ROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos
               CACHE_ROOT = /var/folders/2d/jjks8mqd6wj1vm8dxd7jbnl80000gn/C/com.apple.DeveloperTools/10.2.1-10E1001/Xcode
               CCHROOT = /var/folders/2d/jjks8mqd6wj1vm8dxd7jbnl80000gn/C/com.apple.DeveloperTools/10.2.1-10E1001/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Release
               CONFIGURATION_BUILD_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator12.2
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2
               DERIVED_FILES_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = English
               DEVELOPMENT_TEAM = V97H765GZ8
               DOCUMENTATION_FOLDER_PATH = Runner.app/English.lproj/Documentation
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_NS_ASSERTIONS = NO
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_DESTINATION = Signature
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.0.0
               FLUTTER_BUILD_NUMBER = 1
               FLUTTER_FRAMEWORK_DIR = /Users/earyzhe/dev/SDKs/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/earyzhe/dev/SDKs/flutter
               FLUTTER_TARGET = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/../.symlinks/flutter/ios"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/../.symlinks/flutter/ios" /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS =  COCOAPODS=1 COCOAPODS=1
               GCC_SYMBOLS_PRIVATE_EXTERN = YES
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HEADER_SEARCH_PATHS =  "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/FMDB"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/Reachability"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/connectivity"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/fluttertoast"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/path_provider"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/sqflite" "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/FMDB"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/Reachability"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/connectivity"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/fluttertoast"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/path_provider"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods/Headers/Public/sqflite"
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/earyzhe
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/English.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = earyzhe
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE =
               /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  '@executable_path/Frameworks' '@loader_path/Frameworks' '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/FMDB"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/Reachability"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/connectivity"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/fluttertoast"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/path_provider"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/sqflite"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/FMDB"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/Reachability"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/connectivity"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/fluttertoast"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/path_provider"
               "/Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/sqflite" /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 = 
               LINK_FILE_LIST_normal_armv7 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/English.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFLocalizedString
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 18F132
               MAC_OS_X_VERSION_ACTUAL = 101405
               MAC_OS_X_VERSION_MAJOR = 101400
               MAC_OS_X_VERSION_MINOR = 1405
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/Runner.app
               MODULE_CACHE_DIR = /Users/earyzhe/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = NO
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               ONLY_ACTIVE_ARCH = NO
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -ObjC -l"FMDB" -l"Reachability" -l"connectivity" -l"fluttertoast" -l"path_provider" -l"sqflite" -l"sqlite3" -framework "Flutter" -framework
               "SystemConfiguration" -ObjC -l"FMDB" -l"Reachability" -l"connectivity" -l"fluttertoast" -l"path_provider" -l"sqflite" -l"sqlite3" -framework "Flutter" -framework
               "SystemConfiguration"
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/anaconda3/bin:/Applications/Android
               Studio.app/Contents/jre/jdk/Contents/Home/bin:/Applications/Android
               Studio.app/Contents/jre/jdk/Contents/Home/bin/java:/usr/local/Cellar/dart/2.3.1/bin:/Users/earyzhe/.pub-cache/bin:/Users/earyzhe/dev/SDKs/flutter/bin:/Users/earyzhe/dev/SDK
               s/flutter/.pub-cache/bin:/Users/earyzhe/dev/SDKs/flutter/bin/cache/dart-sdk/bin:/Users/earyzhe/Desktop/salt-code/bin:/Users/earyzhe/dev/bash:/Applications/Postgres.app/Cont
               ents/Versions/11/bin:/Users/earyzhe/redis-4.0.11/src:/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin:/Applications/Android
               Studio.app/Contents/jre/jdk/Contents/Home/bin/java:/usr/local/Cellar/dart/2.3.1/bin:/Users/earyzhe/.pub-cache/bin:/Users/earyzhe/dev/SDKs/flutter/bin:/Users/earyzhe/dev/SDK
               s/flutter/.pub-cache/bin:/Users/earyzhe/dev/SDKs/flutter/bin/cache/dart-sdk/bin:/Users/earyzhe/Desktop/salt-code/bin:/Users/earyzhe/dev/bash:/Applications/Postgres.app/Cont
               ents/Versions/11/bin:/Users/earyzhe/redis-4.0.11/src
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks
               /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 16E226
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PODS_BUILD_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               PODS_CONFIGURATION_BUILD_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos
               PODS_PODFILE_DIR_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/.
               PODS_ROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Pods
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.example.shutterstockScroll
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/DerivedSources
               PROJECT_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios
               PROJECT_FILE_PATH = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build
               PROJECT_TEMP_ROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk
               SDK_DIR_iphoneos12_2 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk
               SDK_NAME = iphoneos12.2
               SDK_NAMES = iphoneos12.2
               SDK_PRODUCT_BUILD_VERSION = 16E226
               SDK_VERSION = 12.2
               SDK_VERSION_ACTUAL = 120200
               SDK_VERSION_MAJOR = 120000
               SDK_VERSION_MINOR = 200
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/SharedPrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios
               SRCROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SYMROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Release-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_ROOT = /Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/build/ios
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TRACK_WIDGET_CREATION = true
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = earyzhe
               USER_APPS_DIR = /Users/earyzhe/Applications
               USER_LIBRARY_DIR = /Users/earyzhe/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               VALIDATE_PRODUCT = YES
               VALID_ARCHS = arm64 arm64e armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = earyzhe
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 10E1001
               XCODE_VERSION_ACTUAL = 1021
               XCODE_VERSION_MAJOR = 1000
               XCODE_VERSION_MINOR = 1020
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -7



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:88:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:162:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:111:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#5      DeviceManager.getDevices (package:flutter_tools/src/device.dart:141:11)
#6      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:506:48)
<asynchronous suspension>
#7      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:282:21)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:462:11)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#45     main (file:///Users/earyzhe/dev/SDKs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

Run `flutter analyze`
```
earyzhe@MacBook-Pro-2:~/dev/FlutterProjects/shutterstock_scroll$ flutter analyze
Analyzing shutterstock_scroll...                                        
No issues found! (ran in 3.0s)
earyzhe@MacBook-Pro-2:~/dev/FlutterProjects/shutterstock_scroll$ 
```

Run`flutter doctor -v`
```
earyzhe@MacBook-Pro-2:~/dev/FlutterProjects/shutterstock_scroll$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.7.8+hotfix.3 at /Users/earyzhe/dev/SDKs/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/earyzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 6                  • A31AF8E8-34ED-43D0-9FF5-F3D1ACD4CB01 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

### LINKED ISSUE #43398: Cannot find executable for ideviceinfo
From URL: https://www.flutterchina.club/get-started/install.md

### LINKED ISSUE #47727: I am getting ideviceinfo returned an error:                 ERROR: Could not connect to lockdownd, error code -8
image

### LINKED ISSUE #48057: [FlutterDaemon] [Error] Unable to retrieve device list!
```
Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (activated)
VS Code: 1.41.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jan 01 2020 [22:38:21 GMT-0800 (Pacific Standard Time)] Log file started
[10:38:21 PM] [General] [Info] Searching for SDKs...
[10:38:21 PM] [General] [Info] Environment PATH:
[10:38:21 PM] [General] [Info]     /usr/local/bin
[10:38:21 PM] [General] [Info]     /usr/bin
[10:38:21 PM] [General] [Info]     /bin
[10:38:21 PM] [General] [Info]     /usr/sbin
[10:38:21 PM] [General] [Info]     /sbin
[10:38:21 PM] [General] [Info]     /usr/local/go/bin
[10:38:21 PM] [General] [Info]     /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info] Done!
[10:38:21 PM] [General] [Info] Found Flutter project at /Users/elias/Documents/GitHub/isontic-Education:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[10:38:21 PM] [General] [Info] Searching for flutter
[10:38:21 PM] [General] [Info]     Looking for flutter in:
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/.flutter
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/.flutter/bin
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/vendor/flutter
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/vendor/flutter/bin
[10:38:21 PM] [General] [Info]         /usr/local/bin
[10:38:21 PM] [General] [Info]         /usr/bin
[10:38:21 PM] [General] [Info]         /bin
[10:38:21 PM] [General] [Info]         /usr/sbin
[10:38:21 PM] [General] [Info]         /sbin
[10:38:21 PM] [General] [Info]         /usr/local/go/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]     Found at:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]     Candidate paths to be post-filtered:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter
[10:38:21 PM] [General] [Info]         /Users/elias/flutter
[10:38:21 PM] [General] [Info]     Found at /Users/elias/flutter
[10:38:21 PM] [General] [Info]     Returning SDK path /Users/elias/flutter for flutter
[10:38:21 PM] [General] [Info] Searching for dart
[10:38:21 PM] [General] [Info]     Looking for dart in:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]         /usr/local/bin
[10:38:21 PM] [General] [Info]         /usr/bin
[10:38:21 PM] [General] [Info]         /bin
[10:38:21 PM] [General] [Info]         /usr/sbin
[10:38:21 PM] [General] [Info]         /sbin
[10:38:21 PM] [General] [Info]         /usr/local/go/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]     Found at:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]     Candidate paths to be post-filtered:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]     Found at /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]     Returning SDK path /Users/elias/flutter/bin/cache/dart-sdk for dart
[10:38:21 PM] [General] [Info] Activating Flutter extension for Dart, Flutter project...
[10:38:21 PM] [General] [Info] Extension:Startup timing: 48ms
[10:38:21 PM] [General] [Info] Analyzer:Startup timing: 366ms
[10:38:26 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[10:38:26 PM] [General] [Info] Checking 2 projects for supported platforms
[10:38:26 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[10:38:26 PM] [General] [Info] Supported platforms for the workspace are ios, android, web
[10:38:26 PM] [FlutterDaemon] [Error] idevice_id returned an error:
ERROR: Unable to retrieve device list!
[10:38:28 PM] [General] [Info] Analyzer:FirstAnalysis timing: 4737ms
```

flutter doctor

```
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.5 at /Users/elias/flutter
    • Framework revision 41a911099b (13 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/elias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: idevice_id returned an error:
      ERROR: Unable to retrieve device list!

    • #0      IMobileDevice.getAvailableDeviceIDs (package:flutter_tools/src/ios/mac.dart:184:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:183:44)
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:860:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:58:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:44:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 2 categories.
```

### LINKED ISSUE #49375: Give user better errors message for lockdown errors like "Could not connect to lockdownd, error code -123"
Users get errors like:
```
ERROR: Could not connect to lockdownd, error code -18
```
when the tools can't connect to iOS devices, specifically various lockdown services.

Flutter tool checks for a -19 and -21 to make recovery suggestions:
https://github.com/flutter/flutter/blob/52e0d980cb1cc8c533411d70a9e76105e534290b/packages/flutter_tools/lib/src/ios/mac.dart#L81-L89

Some of the ones not checked for have obvious recovery suggestions, but it would be useful to give better error messages for all lockdown errors instead of just the error code, even when there are no obvious recovery suggestions.

```
typedef enum {
	/* custom */
	LOCKDOWN_E_SUCCESS                                 =   0,
	LOCKDOWN_E_INVALID_ARG                             =  -1,
	LOCKDOWN_E_INVALID_CONF                            =  -2,
	LOCKDOWN_E_PLIST_ERROR                             =  -3,
	LOCKDOWN_E_PAIRING_FAILED                          =  -4,
	LOCKDOWN_E_SSL_ERROR                               =  -5,
	LOCKDOWN_E_DICT_ERROR                              =  -6,
	LOCKDOWN_E_RECEIVE_TIMEOUT                         =  -7,
	LOCKDOWN_E_MUX_ERROR                               =  -8,
	LOCKDOWN_E_NO_RUNNING_SESSION                      =  -9,
	/* native */
	LOCKDOWN_E_INVALID_RESPONSE                        = -10,
	LOCKDOWN_E_MISSING_KEY                             = -11,
	LOCKDOWN_E_MISSING_VALUE                           = -12,
	LOCKDOWN_E_GET_PROHIBITED                          = -13,
	LOCKDOWN_E_SET_PROHIBITED                          = -14,
	LOCKDOWN_E_REMOVE_PROHIBITED                       = -15,
	LOCKDOWN_E_IMMUTABLE_VALUE                         = -16,
	LOCKDOWN_E_PASSWORD_PROTECTED                      = -17,
	LOCKDOWN_E_USER_DENIED_PAIRING                     = -18,
	LOCKDOWN_E_PAIRING_DIALOG_RESPONSE_PENDING         = -19,
	LOCKDOWN_E_MISSING_HOST_ID                         = -20,
	LOCKDOWN_E_INVALID_HOST_ID                         = -21,
	LOCKDOWN_E_SESSION_ACTIVE                          = -22,
	LOCKDOWN_E_SESSION_INACTIVE                        = -23,
	LOCKDOWN_E_MISSING_SESSION_ID                      = -24,
	LOCKDOWN_E_INVALID_SESSION_ID                      = -25,
	LOCKDOWN_E_MISSING_SERVICE                         = -26,
	LOCKDOWN_E_INVALID_SERVICE                         = -27,
	LOCKDOWN_E_SERVICE_LIMIT                           = -28,
	LOCKDOWN_E_MISSING_PAIR_RECORD                     = -29,
	LOCKDOWN_E_SAVE_PAIR_RECORD_FAILED                 = -30,
	LOCKDOWN_E_INVALID_PAIR_RECORD                     = -31,
	LOCKDOWN_E_INVALID_ACTIVATION_RECORD               = -32,
	LOCKDOWN_E_MISSING_ACTIVATION_RECORD               = -33,
	LOCKDOWN_E_SERVICE_PROHIBITED                      = -34,
	LOCKDOWN_E_ESCROW_LOCKED                           = -35,
	LOCKDOWN_E_PAIRING_PROHIBITED_OVER_THIS_CONNECTION = -36,
	LOCKDOWN_E_FMIP_PROTECTED                          = -37,
	LOCKDOWN_E_MC_PROTECTED                            = -38,
	LOCKDOWN_E_MC_CHALLENGE_REQUIRED                   = -39,
	LOCKDOWN_E_UNKNOWN_ERROR                           = -256
} lockdownd_error_t;
```
https://github.com/libimobiledevice/libimobiledevice/blob/master/include/libimobiledevice/lockdown.h

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Xcode ships with a command line tool called `xcdevice` that produces a json array of all available devices, including iOS devices that can be deployed via Xcode over the network (Connect via network checkbox).  This PR filters out these network devices, but it's relevant to someday fixing https://github.com/flutter/flutter/issues/15072.

Screen Shot 2020-01-30 at 6 57 46 PM

I checked to make sure `xcdevice` is available in Xcode 10.2 (minimum Xcode required by Flutter) and later.

Example output:
```json
{
  "simulator" : false,
  "operatingSystemVersion" : "13.3 (17C54)",
  "interface" : "usb",
  "available" : true,
  "platform" : "com.apple.platform.iphoneos",
  "modelCode" : "iPhone8,1",
  "identifier" : "d83d5bc53967baa0ee18626ba87b6254b2ab5418",
  "architecture" : "arm64",
  "modelName" : "iPhone 6s",
  "name" : "iPhone"
}
```
Since this provides the identifier, name, operating system, and architecture, we can get rid of all usages of `idevice_id` and `ideviceinfo` (cleanup happening in the next PR since this one was already getting too big).

Also, show any connection errors in doctor instead of crashing.  Example:
```
[!] Connected device                          
    • Error: iPhone is not paired with your computer. To use iPhone with Xcode, unlock it and choose to trust this computer when prompted. (code -9)
```

- Remove 2 libimobiledevice dependencies.
- Remove all codepaths that resulted in cryptic lockdown errors and instead return Xcode's nice errors and recovery suggestions, like "To use iPhone with Xcode, unlock it and choose to trust this computer when prompted."

## Related Issues
Part of https://github.com/flutter/flutter/issues/6118
Precursor to https://github.com/flutter/flutter/issues/15072 (will make networked devices discoverable when we stop filtering "network" interfaces).

Fixes https://github.com/flutter/flutter/issues/49375
Fixes https://github.com/flutter/flutter/issues/36524
Fixes https://github.com/flutter/flutter/issues/47727
Fixes https://github.com/flutter/flutter/issues/43398
Fixes https://github.com/flutter/flutter/issues/48057

Supersedes https://github.com/flutter/flutter/pull/49626
Supersedes https://github.com/flutter/flutter/pull/45657
Supersedes part of https://github.com/flutter/flutter/pull/36902?

## Tests

xcode_test, devices_test

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/doctor.dart [hunk 1]
```diff
@@ -868,6 +871,9 @@ class IntelliJValidatorOnMac extends IntelliJValidator {
 class DeviceValidator extends DoctorValidator {
   DeviceValidator() : super('Connected device');
 
+  @override
+  Duration get expectedApproximateDuration => const Duration(seconds: 10);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/doctor.dart]: It was more like 5 seconds in my tests, but let's be conservative...

File: packages/flutter_tools/lib/src/doctor.dart [hunk 2]
```diff
@@ -868,6 +871,9 @@ class IntelliJValidatorOnMac extends IntelliJValidator {
 class DeviceValidator extends DoctorValidator {
   DeviceValidator() : super('Connected device');
 
+  @override
+  Duration get approximateDuration => const Duration(seconds: 10);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/doctor.dart]: It was more like 5 seconds in my tests, but let's be conservative...

File: packages/flutter_tools/lib/src/doctor.dart [hunk 3]
```diff
@@ -380,6 +380,9 @@ abstract class DoctorValidator {
   /// This is displayed in the CLI.
   final String title;
 
+  /// The expected time the validator will take, after with the slow warning will be displayed.
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/doctor.dart]: sp: "after with" -> "after which"

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 4]
```diff
@@ -185,3 +190,274 @@ class Xcode {
...
+    } on ProcessException {
+      _logger.printTrace('Failed to invoke xcdevice');
+    }
+
+    return null;
+  }
+
+  /// List of devices USB tethered or paired over the network.
+  /// See Xcode > Window > Devices and Simulators > Connect via network
+  Stream<IOSDevice> getAvailableIOSDevices() async* {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Why is this a `Stream`?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 5]
```diff
@@ -185,3 +190,274 @@ class Xcode {
...
+    if (error.containsKey('code') && error['code'] is int) {
+      final int code = error['code'] as int;
+      errorMessage.write(' (code $code)');
+    }
+
+    return errorMessage.toString();
+  }
+
+  /// List of all devices reporting errors.
+  Stream<String> getDiagnostics() async* {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Why is this a stream?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 6]
```diff
@@ -185,3 +190,274 @@ class Xcode {
...
+      return null;
+    }
+    try {
+      // USB-tethered devices should always be found.
+      // Finding networked devices takes longer than the default timeout. Try a 5-second timeout.
+      final RunResult result = await _processUtils.run(
+        <String>[
+          xcdevicePath,
+          'list',
+          '--timeout',
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Can we pass a smaller timeout if we know the user doesn't care about wireless debugging?

Said another way, if wireless device discovery was under a flag, could this number be smaller?

**Review by christopherfujino — COMMENTED** [review]
A few questions, but overall this is great!

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 7]
```diff
@@ -185,3 +190,274 @@ class Xcode {
...
+    return _xcdevicePath;
+  }
+
+  Future<List<dynamic>> _getAllDevices() async {
+    if (!isInstalled) {
+      return null;
+    }
+    try {
+      // USB-tethered devices should always be found.
+      // Finding networked devices takes longer than the default timeout. Try a 5-second timeout.
```
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: NVM, just read "cons" above. adding 5 seconds to the doctor seems costly, I wonder if we should make the extended timeout opt-in at first? Not sure how many users would be interested in this feature.

**Comment by christopherfujino** [comment]
Should we warn the user that connecting to the observatory is not supported at this time?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 8]
```diff
@@ -4,6 +4,7 @@
 
 import 'dart:async';
 
+import 'package:flutter_tools/src/build_info.dart';
```
[the remark this answers is not in the document]
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Dang I thought I fixed that. Android Studio loves automatically importing `package:flutter_tools`.

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: `async*` / `yield` requires this to be a stream.  I can change it to `async` and to just return a `List`, if we prefer that pattern...

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Same, `async*`.

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 4 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: This could return a `Stream` if we're actually getting results bit-by-bit from `xcdevice`, or if this is implementing an interface that requires it to be a `Stream`, but otherwise we should probably prefer `Future<List>`, or `Future<Iterable>`.

(`async*` `Stream`s also can have some surprising behavior. IIRC they don't interact well with `FakeAsync` for tests.)

**Comment by jonahwilliams** [comment]
I would actually suggest not listing network devices until we have a way to connect to them

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 6 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: If the user doesn't care about networked devices and this is changed to `--timeout 1` (faster than the default) , this returns the USB-tethered devices and none of the networked devices.  

There's an `xcdevice wait [--usb|--wifi|--both] [--timeout=sec] <udid>` which will return as soon as the device is found but waits until the timeout if not, which would be fast for USB-tethered devices.  That would make sense for `flutter run -d <udid>` `hasSpecifiedDeviceId` situations, though it would require `PollingDeviceDiscovery` to get refactored to take a "hint" identifier or something like that.

Maybe it would be okay for `flutter doctor` and `flutter devices` to take the full 5 seconds since we can then surface that it's networked and that they need to pass in `-d <udid>` to  `flutter run` (`attach`, `logs`, `screenshot`, etc) on the device.  And users would only be running those command infrequently, and they probably would prefer an accurate listing than for them to be fast.

Proposal:
1. Switch to `xcdevice wait --both --timeout=5` for any command using `-d <udid>` (`run`, `attach`, `logs`, `screenshot`) to return fast if possible, but wait if needed.
1. When there's no `-d <udid>` or `-d all` assume USB-only (common case) and use the fastest timeout possible.
1. Keep the long timeout for `flutter doctor` and `flutter devices` and for "network" interface show a warning like "This device is available over the network and must be specified with `-d {}

**Comment by jmagman** [comment]
> Should we warn the user that connecting to the observatory is not supported at this time?

@christopherfujino This is a good idea, and detectible since we know it's a "network" interface.

> I would actually suggest not listing network devices until we have a way to connect to them

@jonahwilliams  That's what we do now, we just ignore them.  I think it's better to at least let the user at least launch the app, even if they can't connect to the observatory, than to not ever be able to launch it at all.  What about @christopherfujino's suggestion to print a message that networked devices don't support hot reload and just exit instead of crashing?

**Comment by jmagman** [comment]
I'm going to repurpose this issue to replace `idevice_id` and `ideviceinfo` with `xcdevice` for USB only, which is still a good direction, and address network devices discovery and port forwarding in future PRs instead of trying to do everything at once.  I'll change this to purposely return fast and skip interfaces that aren't "usb".

**Comment by zanderso** [comment]
> I'm going to repurpose this issue to replace `idevice_id` and `ideviceinfo` with `xcdevice` for USB only, ...

sgtm

**Comment by jonahwilliams** [comment]
I guess if we can still launch the app, that is definitely useful

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 9]
```diff
@@ -170,34 +180,20 @@ class IOSDevice extends Device {
...
-        devices.add(IOSDevice(id, name: deviceName, sdkVersion: sdkVersion));
-      } on IOSDeviceNotFoundError catch (error) {
-        // Unable to find device with given udid. Possibly a network device.
-        globals.printTrace('Error getting attached iOS device: $error');
-      } on IOSDeviceNotTrustedError catch (error) {
-        globals.printTrace('Error getting attached iOS device information: $error');
-        UsageEvent('device', 'ios-trust-failure').send();
-      }
+  static Future<List<String>> getDiagnostics(Platform platform, XCDevice xcdevice) async {
+    if (!platform.isMacOS) {
```
[the remark this answers is not in the document]
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart]: I changed it to:
```
return const <String>['Control of iOS devices or simulators only supported on Mac OS.'];
```
since that's the relevant diagnostic info. We don't really need to crash about gathering diagnostics.

**Comment by jmagman** [comment]
> I'm going to repurpose this issue to replace `idevice_id` and `ideviceinfo` with `xcdevice` for USB only, which is still a good direction, and address network devices discovery and port forwarding in future PRs instead of trying to do everything at once. I'll change this to purposely return fast and skip interfaces that aren't "usb".

Done.  PTAL!

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 10]
```diff
@@ -185,3 +189,280 @@ class Xcode {
...
+      }
+
+      // Only support USB devices, skip "network" interface (Xcode > Window > Devices and Simulators > Connect via network).
+      if (deviceProperties.containsKey('interface') && (deviceProperties['interface'] as String) != 'usb') {
+        continue;
+      }
+
+      String sdkVersion;
+      if (deviceProperties.containsKey('operatingSystemVersion')) {
+        final RegExp operatingSystemRegex = RegExp(r'(.*) \(.*\)$');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Best practice is to hoist `RegExp` construction out of the loop.

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 6 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Can the `--timeout` value be smaller than 1?

**Comment by jmagman** [comment]
Diagnostic messages I've seen while testing:
```
• Error: Jenn’s iPhone is busy: Preparing debugger support for iPhone Xcode will continue when Jenn’s iPhone is finished. (code -10)
```
```
• Error: Jenn’s iPhone has recently restarted Xcode will continue when Jenn’s iPhone is unlocked. (code -14)
```

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 6 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: > Can the `--timeout` value be smaller than 1?

1 seems to be the minimum allowed.  0 reverts to the longer default timeout.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 11]
```diff
@@ -185,3 +189,280 @@ class Xcode {
...
+    //    "operatingSystemVersion" : "6.1.1 (17S445)",
+    //    "available" : true,
+    //    "platform" : "com.apple.platform.watchsimulator",
+    //    "modelCode" : "Watch5,4",
+    //    "identifier" : "2D74FB11-88A0-44D0-B81E-C0C142B1C94A",
+    //    "architecture" : "i386",
+    //    "modelName" : "Apple Watch Series 5 - 44mm",
+    //    "name" : "Apple Watch Series 5 - 44mm"
+    //  },
+    // ...
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: This method is pretty long -- could a few smaller methods be factored out to break out? Something like some {sub,super,}set of:
* fetch blob o' json (already done: `_getAllDevices()`)
* `isIPhoneOSDevice(deviceProperties)`
* error message check (already done: `_parseErrorMessage`)
* `_isAvailable(...)` 
* `_isUSBDevice(...)` (or alternatively `_getConnectionType(...) == _DeviceConnectionType.usb`)
* get SDK version
* get cpu arch

**Review by cbracken — COMMENTED** [review]
Overall looks pretty great -- I had no idea `xcdevice` existed!

Two quick questions:
* do all versions of XCode we support include this tool? (if we only support 11, then we're set)
* do they all emit compatible output?

**Comment by jmagman** [comment]
> Overall looks pretty great -- I had no idea `xcdevice` existed!
> 
> Two quick questions:
> 
> * do all versions of XCode we support include this tool? (if we only support 11, then we're set)
> * do they all emit compatible output?

I tested on Xcode 10.1 and the output looked the same, though the error message text was sometimes different.  I'll try on Xcode 10.2, which is our current minimum required version.

Of course there's nothing stopping Xcode from completely changing or even removing this tool in the next release...

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 11 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Good idea, done!

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 12]
```diff
@@ -185,3 +189,303 @@ class Xcode {
...
+      try {
+        _xcdevicePath = _processUtils.runSync(
+          <String>[
+            'xcrun',
+            '--find',
+            'xcdevice'
+          ],
+        ).stdout.trim();
+      } on ProcessException {
+        // Ignored, return null below.
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Consider printing a trace message with the exception object so we can get some additional info from a `--verbose` run.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 13]
```diff
@@ -185,3 +189,303 @@ class Xcode {
...
+      } on ArgumentError {
+        // Ignored, return null below.
+      }
+    }
+    return _xcdevicePath;
+  }
+
+  Future<List<dynamic>> _getAllDevices() async {
+    if (!isInstalled) {
+      return null;
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: Should this fail more loudly if the reason we can't find devices is that the tool isn't installed like we expect?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 14]
```diff
@@ -185,3 +189,303 @@ class Xcode {
...
+      final int code = error['code'] as int;
+      errorMessage.write(' (code $code)');
+    }
+
+    return errorMessage.toString();
+  }
+
+  /// List of all devices reporting errors.
+  Future<List<String>> getDiagnostics() async {
+    final List<dynamic> allAvailableDevices = await _getAllDevices();
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: It looks like this is called shortly after an empty return from `getAllConnectedDevices()`. Would it make sense to cache the result of `_getAllDevices()` to avoid shelling out to `xcdevice` again?

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 13 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: I've seen GitHub issues where people are trying to run `-d chrome` or for a particular Android device, and they are getting crashes because their personal phone is plugged in but isn't set up for development.  I don't think we should make people have Xcode installed if they aren't doing iOS development, and we can't really tell what their intentions are at the point we're trying to find a particular device identifier.

Comment (zanderso) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Ah, okay, yeah that makes sense.

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 12 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: It looks like you may also want to pass `throwOnError: true` to `runSync()`. That will make `runSync()` throw a `ProcessException` if the `xcrun` exit code is non-zero.

**Comment by jmagman** [comment]
Ready for re-review.

**Review by zanderso — APPROVED** [review]
lgtm

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 15]
```diff
@@ -185,3 +189,318 @@ class Xcode {
...
+        return listResults;
+      }
+      _logger.printTrace('xcdevice returned an error:\n${result.stderr}');
+    } on ProcessException catch (exception) {
+      _logger.printTrace('Process exception running xcdevice list:\n$exception');
+    } on ArgumentError catch (exception) {
+      _logger.printTrace('Argument exception running xcdevice list:\n$exception');
+    } on FormatException catch (exception) {
+      // Failed to parse the xcdevice output, or it returned junk.
+      _logger.printError('xcdevice returned non-JSON response:\n$exception');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/macos/xcode.dart]: might this happen legitimately for reasons other than the format was changed? i'm wondering if this should be an exception and so we can surface this.

**Review by christopherfujino — APPROVED** [review]
LGTM with one nit about if we should throw on `FormatException`.

**Comment by christopherfujino** [comment]
weird error on `customer_testing` tests:

```
Cloning into 'bin/cache/pkg/tests'...
dart --enable-asserts dev/customer_testing/run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test
ERROR: Could not parse: ./bin/cache/pkg/tests/registry/flutter_packages.test
First "fetch" directive does not match expected pattern (expected "git clone https://github.com/USERNAME/REPOSITORY.git tests").
```

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 15 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart]: Yeah that makes sense, we should see the crashes if this happens.

**Comment by jmagman** [comment]
> weird error on `customer_testing` tests:
> 
> ```
> Cloning into 'bin/cache/pkg/tests'...
> dart --enable-asserts dev/customer_testing/run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test
> ERROR: Could not parse: ./bin/cache/pkg/tests/registry/flutter_packages.test
> First "fetch" directive does not match expected pattern (expected "git clone https://github.com/USERNAME/REPOSITORY.git tests").
> ```

Rebased onto master to resolve.
