### PR TITLE
Reland #179643, only scroll hit-testable primary scroll views on status bar tap

### LINKED ISSUE #175606: [iPadOS 26] Clicking the top edge of the screen is recognized twice
### Steps to reproduce

1. Run any Flutter app on iPad (iOS 26). (I couldn't reproduce on iPhone)
2. Change SystemUiMode to `immersive` by running `SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);`.
3. You might need to rotate the screen to apply `immersive` mode due to this issue.
#175520
4. Click the top edge of the screen, and you can notice that the click is recognized twice.

### Expected results

A single click should be recognized once.

### Actual results

A single click is recognized twice.

https://github.com/user-attachments/assets/fb48a0b0-ce38-419f-8894-d466c1f955b2

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _count = 0;

  @override
  void initState() {
    super.initState();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: GestureDetector(
          onTap: () {
            setState(() {
              _count++;
            });
          },
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: Colors.grey,
            alignment: Alignment.topCenter,
            child: Text(
              '$_count',
              style: const TextStyle(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.4, on macOS 26.0 25A354 darwin-arm64, locale en-KR) [243ms]
    • Flutter version 3.35.4 on channel stable at /Users/seunghyun/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d693b4b9db (2 days ago), 2025-09-16 14:27:41 +0000
    • Engine revision c298091351
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, no-enable-linux-desktop, no-enable-macos-desktop, no-enable-windows-desktop,
      enable-android, enable-ios, cli-animations, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [997ms]
    • Android SDK at /Users/seunghyun/Library/Android/Sdk
    • Emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/seunghyun/Library/Android/Sdk
    • Java binary at: /Users/seunghyun/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [625ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A324
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [18ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [18ms]
    • Android Studio at /Users/seunghyun/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.2) [17ms]
    • IntelliJ at /Users/seunghyun/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.101.1) [5ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.112.0

[✓] Connected device (5 available) [5.8s]
    • Seunghyun’s iPad (wireless) (mobile)         • 00008020-001B59413A83002E            • ios            • iOS 18.6.2
      22G100
    • iPhone 14 Pro (mobile)                       • 3794BC81-1DEA-4AF4-B5FA-3DA2FCF87C6F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-26-0 (simulator)
    • iPad Pro (11-inch) (4th generation) (mobile) • 36564CCB-3F65-4FBF-8956-495C518CA3DE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-26-0 (simulator)
    • iPad Pro (11-inch) (4th generation) (mobile) • 1E2A25BD-1080-47CF-82C6-831C4928805A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-6 (simulator)
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome
      140.0.7339.185

[✓] Network resources [352ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #177992: Overlays close immediately after opening on iPadOS 26.1
### Steps to reproduce

1. Launch the sample app below on an iPad device or simulator running iPadOS 26.1 (update Xcode to v26.1 to get the latest simulators).
2. Tap the hamburger icon to open the end drawer.
3. Observe that it closes immediately. Occasionally it will behave correctly and not close by itself.

### Expected results

The end drawer should remain open until the user actively dismisses it.

### Actual results

On iPadOS 26.1, the end drawer closes by itself just after opening.

On older iPadOS versions, including 26.0, it behaves correctly and stays open until dismissed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Scaffold.endDrawer].

void main() => runApp(const EndDrawerExampleApp());

class EndDrawerExampleApp extends StatelessWidget {
  const EndDrawerExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: EndDrawerExample());
  }
}

class EndDrawerExample extends StatefulWidget {
  const EndDrawerExample({super.key});

  @override
  State<EndDrawerExample> createState() => _EndDrawerExampleState();
}

class _EndDrawerExampleState extends State<EndDrawerExample> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  void _closeEndDrawer() {
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: const Text('Drawer Demo'),
      ),
      body: Center(
        child: Text('iOS 26.1 Drawer bug. Tap the hamburger icon to trigger'),
      ),
      endDrawer: Drawer(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('This is the Drawer'),
              ElevatedButton(
                onPressed: _closeEndDrawer,
                child: const Text('Close Drawer'),
              ),
            ],
          ),
        ),
      ),
      // Disable opening the end drawer with a swipe gesture.
      endDrawerEnableOpenDragGesture: false,
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPad Air 11-inch (M3) in debug mode...
Running Xcode build...
Xcode build done.                                           11.6s
Syncing files to device iPad Air 11-inch (M3)...                    32ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPad Air 11-inch (M3) is available at: http://127.0.0.1:51132/VZCG7b-IIPk=/
The Flutter DevTools debugger and profiler on iPad Air 11-inch (M3) is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51132/VZCG7b-IIPk=/

Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.7, on macOS 15.6.1 24G90 darwin-arm64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] VS Code (version 1.105.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

### LINKED ISSUE #182233: `ScrollController.animateTo` crashes when status bar is tapped on iOS
internal [b/482565401](b/482565401)

No repros yet. It looks like `ScrollPosition.applyContentDimensions` was never called.

Stacktrack:
```
_TypeError at ScrollPosition.minScrollExtent at package:flutter/src/widgets/scroll_position.dart-a68024a0

Thread 0 main thread_TypeError: Null check operator used on a null value
at ScrollPosition.minScrollExtent(scroll_position.dart:235)
at ScrollMetrics.outOfRange(scroll_metrics.dart:117)
at BouncingScrollPhysics.createBallisticSimulation(scroll_physics.dart:756)
at ScrollPhysics.createBallisticSimulation(scroll_physics.dart:408)
at ScrollPositionWithSingleContext.goBallistic(scroll_position_with_single_context.dart:151)
at ScrollPositionWithSingleContext.jumpTo(scroll_position_with_single_context.dart:206)
at ScrollPositionWithSingleContext.animateTo(scroll_position_with_single_context.dart:180)
at ScrollController.animateTo(scroll_controller.dart:214)
at ScaffoldState.handleStatusBarTap(scaffold.dart:2750)
at WidgetsBinding._handleStatusBarActions(binding.dart:1010)
at MethodChannel._handleAsMethodCall(platform_channel.dart:607)
at MethodChannel.setMethodCallHandler.<anonymous closure>(platform_channel.dart:597)
at _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>(binding.dart:663)
at _invoke2.<anonymous closure>(hooks.dart:458)
at CoreActivityZoneImpl._run.<anonymous closure>(zone.dart:220)
at _rootRun(zone_root.dart:35)
at _ZoneDelegate.run(zone_delegate.dart:84)
at CoreActivityZoneImpl._run(zone.dart:217)
at _CustomZone.run(zone.dart:726)
at _CustomZone.runGuarded(zone.dart:625)
at _invoke2(hooks.dart:457)
at _ChannelCallbackRecord.invoke(channel_buffers.dart:45)
at _Channel.push(channel_buffers.dart:136)
at ChannelBuffers.push(channel_buffers.dart:344)
at PlatformDispatcher._dispatchPlatformMessage(platform_dispatcher.dart:822)
at _dispatchPlatformMessage(hooks.dart:369)
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Reland #179643, with [changes](https://github.com/flutter/flutter/pull/182391/changes/3f7d3452d8957e185d3b3ef36210f090122c2af1) to fix  https://github.com/flutter/flutter/issues/182233. The reland closes https://github.com/flutter/flutter/issues/177992, closes https://github.com/flutter/flutter/issues/175606.

The crash happened because `Scaffold.handleStatusBar` (and subsequently `ScrollController.animateTo`) is called on a scaffold that [has never been laid out](https://github.com/flutter/flutter/issues/182233#issuecomment-3887993163). Before #179643, the iOS embedder sends a fake touch down pointer event at `(0, 0)` to the framework, followed by a touch up pointer event at the same location. That ensured only the foreground `Scaffold` could claim the tap gesture and handle the status bar tap.

The fix tries to restore the previous behavior (where the iOS behavior sends fake touches instead of platform messages) by performing a hit-test at `(0, 0)` before trying to scroll the primary controller of a `Scaffold` to the top, this should make sure that only the foreground scaffold (in theory it's still possible for more than one Scaffold to receive the hittest and handle the status bar tap event, but the foreground scaffold should block the hit-test on background ones instead of relying on gesture disambiguation).

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -3150,32 +3187,24 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
-        );
-      case TargetPlatform.android:
-      case TargetPlatform.fuchsia:
-      case TargetPlatform.linux:
-      case TargetPlatform.windows:
-        break;
-    }
+    final Widget? statusBar = switch (themeData.platform) {
+      TargetPlatform.iOS ||
+      TargetPlatform.macOS => widget.primary ? _HitTestableAtOrigin(_statusBarKey) : null,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/scaffold.dart:3196]: Ideally this should be for iOS only, as on macOS the `_HitTestableAtOrigin` widget will never be used.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -3150,32 +3187,24 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
-          removeRightPadding: false,
-          removeBottomPadding: true,
-        );
-      case TargetPlatform.android:
-      case TargetPlatform.fuchsia:
-      case TargetPlatform.linux:
-      case TargetPlatform.windows:
-        break;
-    }
+    final Widget? statusBar = switch (themeData.platform) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/scaffold.dart:3194]: The change here (and in cupertino page scaffold) only replaces the tap gesture recognizer with `_HitTestableAtOrigin`.

File: packages/flutter/lib/src/widgets/binding.dart [hunk 3]
```diff
@@ -152,6 +152,22 @@ abstract mixin class WidgetsBindingObserver {
...
+  /// suitable scroll view for handling this event.
+  ///
+  /// This callback is only called on iOS. The default implementation provided by
+  /// [WidgetsBindingObserver] does nothing.
+  ///
+  /// See also:
+  ///
+  ///  * [Scaffold] and [CupertinoPageScaffold] which use this callback to implement
+  ///    iOS scroll-to-top.
+  void handleStatusBarTap() {}
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/binding.dart:169]: If this need to have the prevent bubble up , this should return bool similar to handleStartBackGesture

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -2743,12 +2746,22 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
     final ScrollController? primaryScrollController = PrimaryScrollController.maybeOf(context);
-    if (primaryScrollController != null && primaryScrollController.hasClients) {
+    if (primaryScrollController != null &&
+        primaryScrollController.hasClients &&
+        // TODO(LongCatIsLooong): the iOS embedder used to send status bar tap
+        // evets as fake touches at Offset.zero. The hit-test here makes sure
+        // the status bar tap is handled by the same Scaffolds as before.
+        // Switch to a better solution when available:
+        // https://github.com/flutter/flutter/issues/182403
+        _HitTestableAtOrigin.hitTestableAtOrigin(_statusBarKey)) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/scaffold.dart:2768]: can you talk more about this extra check? what is a counter example if we don't have this check?

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/binding.dart:169]: You mean we stop delivering a status bar tap event to the remaining listeners, as soon as one of the callbacks returned true? Unfortunately we deliver status bar tap events to listeners in registration order, and since the registration will most likely happen in `initState` / `activate`, I don't think we can guarantee that States with higher precedence for handling status bar taps will be mounted before low precedence ones (especially when there're LayoutBuilders in the app). Also there could be use cases that two scrollables should handle a single status bar tap simultaneously.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/scaffold.dart:2768]: I put the relevant code comment at the declaration site of the `hitTestableAtOrigin` (because there's already a TODO here). Do you prefer moving that comment up to the call site?

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart:169]: looking at the code, the _HitTestableAtOrigin.hitTestableAtOrigin decided whether it should scroll to the top for a scaffold? can that be used to determine  whether to return true or false?

> Also there could be use cases that two scrollables should handle a single status bar tap simultaneously.

Can you talk more about this? does that mean there are two scaffold that has overlapping hittest origin?

File: packages/flutter/lib/src/cupertino/page_scaffold.dart [hunk 5]
```diff
@@ -89,11 +89,39 @@ class CupertinoPageScaffold extends StatefulWidget {
...
+  void handleStatusBarTap() {
+    super.handleStatusBarTap();
     final ScrollController? primaryScrollController = PrimaryScrollController.maybeOf(context);
-    // Only act on the scroll controller if it has any attached scroll positions.
-    if (primaryScrollController != null && primaryScrollController.hasClients) {
+    if (primaryScrollController != null &&
+        primaryScrollController.hasClients &&
+        // TODO(LongCatIsLooong): the iOS embedder used to send status bar tap
+        // evets as fake touches at Offset.zero. The hit-test here makes sure
+        // the status bar tap is handled by the same Scaffolds as before.
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/page_scaffold.dart]: What does the as before mean?

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/binding.dart:169]: > Also there could be use cases that two scrollables should handle a single status bar tap simultaneously.

The case I have in mind is that there are two scrollables placed next to each other and the app developer decided that both of them should respond to the same status bar tap (maybe for something like text diff UI). This is the WidgetsBindingObserver API so it's possible for app developers to add their own observers that unconditionally handle status bar taps, not just Scaffolds.

File: packages/flutter/lib/src/cupertino/page_scaffold.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/page_scaffold.dart]: rephrased the todo to make it clear that hit test is to keep the legacy behavior.

Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/page_scaffold.dart]: this is not help either, reader won't know what legacy behavior is, we should just state what the behavior is

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart:169]: In that case, why just do this when its top is align with view's top? is this the existing behavior before the change?

other than that I think using void is fine.

File: packages/flutter/lib/src/cupertino/page_scaffold.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/page_scaffold.dart]: The comment goes like this:
```
        // TODO(LongCatIsLooong): the iOS embedder used to send status bar tap
        // evets as fake touches at Offset.zero, such that at most one Scaffold
        // (usually the foreground primary Scaffold) can handle the status bar
        // tap event, thanks to hit-testing and gesture disambiguation.
        // To keep that behavior, this widget performs an additional hit-test here
        // to make sure the status bar tap is only handled if the scaffold is
        // hit-testable (thus in the foreground)
        // Switch to a better solution when available:
        // https://github.com/flutter/flutter/issues/182403
```

**Review by chunhtai — COMMENTED** [review]
LGTM, given we have plan to migrate to dart:ui https://github.com/flutter/flutter/issues/182509

**Review by chunhtai — APPROVED** [review]

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/binding.dart:169]: Yeah the `Offset.zero` hit-test is from the old implementation (fake pointer down + up events at the origin).
