### PR TITLE
Fixes `RangeError` bug when length of `TabBar.tabs` is changed

### LINKED ISSUE #94504: DefaultTabController does not support dynamic tab insertion
I have some static tabs and I'd like to be able to insert new tabs, according to a network response (so an async response). I'm using `DefaultTabController`:  the first `build` (with static tabs) works well but when the incoming network response is retrieved and the `setState` is called then I've got some exceptions.

## Steps to Reproduce

Here is the minimal code to reproduce this issue.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Widget> _tabs = [];

  @override
  void initState() {
    super.initState();
    List.generate(3, (index) => _addTab());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Default Tab Controller"),
      ),
      body: DefaultTabController(
        length: _tabs.length,
        child: TabBar(tabs: _tabs),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _addTab(),
        child: const Icon(Icons.add),
      ),
    );
  }

  void _addTab() {
    setState(() {
      _tabs.add(Text("Tab ${_tabs.length}", style: const TextStyle(color: Colors.black)));
    });
  }
}
```

**Expected results:** 

A tab is added to my `TabBar` and also a corresponding child is added to the `TabBarView`.

**Actual results:** 

An exception is thrown (see the logs)

<details>
  <summary>Logs</summary>

```. 
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TabBar(dirty, dependencies: [_InheritedTheme, _TabControllerScope, _LocalizationsScope-[GlobalKey#e35dd]], state: _TabBarState#a4e2d):
RangeError (index): Invalid value: Not in inclusive range 0..2: 3

The relevant error-causing widget was: 
  TabBar TabBar:file:///Users/Eric/Development/perso/default_tab_controller/lib/main.dart:46:13
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1229:26)
#2      new _GrowableList.generate (dart:core-patch/growable_array.dart:133:28)
#3      _TabBarState.build (package:flutter/src/material/tabs.dart:1208:38)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```. 
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/Eric/Development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (il y a 7 semaines), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Eric/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/Eric/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • AOSP on IA Emulator (mobile)       • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```
</details>

### PR DESCRIPTION
**Pull request by werainkhatri**
When `TabBar.tabs` is passed a `List`'s reference, and when the reference is updated, `TabBar` throws a RangeError because when widget is updated, `TabBar.didUpdateWidget` compares `widget.tabs.length` with `oldWidget.tabs.length`. Since they are referencing the same list, their lengths are also same and `TabBar._tabKeys` is not updated.

~This PR also removes a test, which was a regression test for #20292. This is because the test changes the list's reference by attaching a new list when pumping a new state, but the issue used the same list reference.~

Fixes #94504 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -982,11 +982,11 @@ class _TabBarState extends State<TabBar> {
       _initIndicatorPainter();
     }
 
-    if (widget.tabs.length > oldWidget.tabs.length) {
-      final int delta = widget.tabs.length - oldWidget.tabs.length;
+    if (widget.tabs.length > _tabKeys.length) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:985]: Can we not consider both cases here?
The test you deleted is a valid use case that we fixed in the past. Folks expecting that behavior will be broken by this change.

Comment (werainkhatri) [reply packages/flutter/lib/src/material/tabs.dart:985]: The test I deleted passes even after my change. If it may cause an issue later, I'll add it back in.

Comment (Piinks) [reply packages/flutter/lib/src/material/tabs.dart:985]: YEs, please do add it back in. We want to make sure we don't regress. More tests are never a bad thing. :)

File: packages/flutter/test/material/tabs_test.dart [hunk 2]
```diff
@@ -3418,56 +3419,52 @@ void main() {
     expect(find.text('Tab2'), findsOneWidget);
   });
 
-  testWidgets('DefaultTabController should allow for a length of zero', (WidgetTester tester) async {
+  testWidgets('DefaultTabController should allow dynamic length of tabs', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/tabs_test.dart:3422]: Was @Piinks saying that the original test (for length zero) should remain unmodified, and the dynamic length test should be a new separate test? That would make sense to me.

Comment (werainkhatri) [reply packages/flutter/test/material/tabs_test.dart:3422]: She was referring to the one I had deleted (added back in the last commit). I have tested for zero tabs as a part of dynamic, which I suppose is fine. If you think otherwise, I don't mind separating them.

Comment (Piinks) [reply packages/flutter/test/material/tabs_test.dart:3422]: I think separating them is a good idea. The original test is already a regression test, we should preserve the original test case and add a new test. Thanks!

Comment (werainkhatri) [reply packages/flutter/test/material/tabs_test.dart]: Sorry for so much back-and-forth. Will make sure not to modify regression tests in the future.

Comment (Piinks) [reply packages/flutter/test/material/tabs_test.dart]: No worries at all! Thanks for the updates!

**Review by Piinks — APPROVED** [review]
This LGTM
