### PR TITLE
Flexible AppBar with a TabBar

### LINKED ISSUE #1546: Gallery App has Tabs
From https://www.google.com/design/spec/components/tabs.html

- [ ] Fixed
- [x] Scrollable

### LINKED ISSUE #1806: Tab names don't fit on ios in material gallery
Steps to reproduce:

1) Launch material gallery in ios
2) Navigate to Components > Buttons > Floating
3) Tap the floating action button

Expected behavior

The names in the "FAB per tab" screen should fit without the text wrapping.

Actual behavior.
tab-labels-wrapping

@HansMuller

### LINKED ISSUE #2627: Not possible to use tabs with a collapsing toolbar
@HansMuller mentioned he'd fix this soon.  One of our customers needs these combined.

### PR DESCRIPTION
**Pull request by HansMuller**
Added support for the `scroll` and `under` AppBarBehaviors for AppBars that have TabBars.

There's a new gallery "Tabs" demo that shows how this can work.

Sadly, this not the AppBar finale. Among the problems that still need to be addressed:
- Setting up a flexible AppBar is too complicated. Currently one must identify the scrollable that drives the AppBar resize with a key, specify the same key as the value of the Scaffold's scrollableKey, specify a Scaffold appBarBehavior, and pad the top of the Scrollable to match the AppBar's "extended" height - including the status bar's height.
- The Scaffold should compute the size the AppBar at layout time, rather than at build time.
- Exactly how best to handle a flexible TabBar with scrollable TabViews is still an open question. The current Tabs demo is isn't really an answer.
- When the selected tab changes, if it's necessary to scroll a TabView to sync its flexible AppBar up with its (saved) scroll offset, the scroll animation should be be driven by the tab change animation.

Fixes https://github.com/flutter/flutter/issues/2627
Fixes https://github.com/flutter/flutter/issues/1546
Fixes https://github.com/flutter/flutter/issues/1806

### CODE REVIEW

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -34,11 +43,15 @@ class AppBar extends StatelessWidget {
...
-  final Widget tabBar;
+  final TabBar tabBar;
   final int elevation;
   final Color backgroundColor;
   final TextTheme textTheme;
   final EdgeInsets padding;
+  final double _expandedHeight;
+  final double _collapsedHeight;
+  final double _minimumHeight;
+  final double _actualHeight;
```
Comment (abarth) [inline packages/flutter/lib/src/material/app_bar.dart]: Why private?  Usually we make all the constructor arguments publiv.

Comment (abarth) [inline packages/flutter/lib/src/material/app_bar.dart]: Ah, I see.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 2]
```diff
@@ -112,59 +147,72 @@ class AppBar extends StatelessWidget {
...
+      child: new IconTheme(
+        data: iconTheme,
+        child: new DefaultTextStyle(
+          style: sideStyle,
+          child: new Row(children: toolBarRow)
+        )
+      )
+    );
+
+    final tabBarOpacity = _tabBarOpacity(statusBarHeight);
```
Comment (abarth) [inline packages/flutter/lib/src/material/app_bar.dart]: Type pls

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Be wary, for some reason travis didn't trigger on this PR.
