### PR TITLE
[Material] Fix showDialog crasher caused by old contexts

### LINKED ISSUE #28505: ShowDialog is using the wrong context
Hello there,

The issues I addressed is in this line: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dialog.dart#L705

When the `showDialog` pageBuilder is trying to get the theme it is using the context from `showDialog` and not the context from the `pageBuilder`. The issue is that the context from `showDialog` can be invalid ex. when the application waked from a suspended state.

My suggestion to fix it, is to change: 
```
final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
```
to
```
final ThemeData theme = Theme.of(buildContext, shadowThemeOnly: true);
```

## Steps to Reproduce

1. Call Show dialog, with a textfield as child
2. Suspend the entire application
3. Wake up the application
4. Go to landscape mode and see the application will crash

### PR DESCRIPTION
**Pull request by johnsonmh**
## Description

* The `showDialog` function takes a `context` parameter. That parameter is used to get the current `Theme.of(context)` when `showDialog` is called. The [showDialog dart docs](https://github.com/flutter/flutter/blob/387f885481cd8441237680de0cfcd0802c0af48c/packages/flutter/lib/src/material/dialog.dart#L667) say that after `showDialog` is called, its widget can safely be removed from the tree, since `context` is only used when the method is called. This was not actually true, since the `Theme.of(context)` call was happening *inside* the `pageBuilder`, even though the context being used was from the original function call. This meant that it was possible for `Theme.of(context)` to be called with an already deactivated build context, throwing an error.  
 
## Related Issues

* fixes https://github.com/flutter/flutter/issues/28505

## Tests

I added the following tests:

```dart
// Regression test for https://github.com/flutter/flutter/issues/28505.
testWidgets('showDialog only gets Theme from context on the first call', (WidgetTester tester) async {
  Widget buildFrame(Key builderKey) {
    return MaterialApp(
      home: Material(
        child: Center(
          child: Builder(
            key: builderKey,
            builder: (BuildContext outerContext) {
              return RaisedButton(
                onPressed: () {
                  showDialog<void>(
                    context: outerContext,
                    builder: (BuildContext innerContext) {
                      return const AlertDialog(title: Text('Title'));
                    },
                  );
                },
                child: const Text('Show Dialog'),
              );
            },
          ),
        ),
      ),
    );
  }

  // First time build.
  await tester.pumpWidget(buildFrame(UniqueKey()));

  // Open the dialog.
  await tester.tap(find.byType(RaisedButton));
  await tester.pumpAndSettle();

  // Second time build.
  await tester.pumpWidget(buildFrame(UniqueKey()));

  // App crashes when we try to open the dialog, because it tries to get the
  // Theme from the old context.
  await tester.tap(find.byType(RaisedButton));
});
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM with one small comment

File: packages/flutter/test/material/dialog_test.dart [hunk 1]
```diff
@@ -607,4 +607,46 @@ void main() {
...
+        home: Material(
+          child: Center(
+            child: Builder(
+              key: builderKey,
+              builder: (BuildContext outerContext) {
+                return RaisedButton(
+                  onPressed: () {
+                    showDialog<void>(
+                      context: outerContext,
+                      builder: (BuildContext innerContext) {
```
Comment (clocksmith) [inline packages/flutter/test/material/dialog_test.dart]: could be => ?

File: packages/flutter/test/material/dialog_test.dart [hunk 2]
```diff
@@ -607,4 +607,46 @@ void main() {
...
+    await tester.pumpWidget(buildFrame(UniqueKey()));
+
+    // Open the dialog.
+    await tester.tap(find.byType(RaisedButton));
+    await tester.pumpAndSettle();
+
+    // Second time build.
+    await tester.pumpWidget(buildFrame(UniqueKey()));
+
+    // App crashes when we try to open the dialog, because it tries to get the
```
Comment (clocksmith) [inline packages/flutter/test/material/dialog_test.dart]: Is this comment right?

File: packages/flutter/test/material/dialog_test.dart (hunk 1 above)
Comment (johnsonmh) [reply packages/flutter/test/material/dialog_test.dart]: This could be, but since `const AlertDialog(title: Text('Title'));` would have to be on it's own line anyways, I think its better to leave with `{ ... }`.

File: packages/flutter/test/material/dialog_test.dart (hunk 2 above)
Comment (johnsonmh) [reply packages/flutter/test/material/dialog_test.dart]: It was misleading, I clarified it to specifically say, before the fix, the app would have crashed here.

File: packages/flutter/test/material/dialog_test.dart [hunk 3]
```diff
@@ -607,4 +607,46 @@ void main() {
     expect(find.text('0'), findsNothing);
     expect(find.text('1'), findsNothing);
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/28505.
+  testWidgets('showDialog only gets Theme from context on the first call', (WidgetTester tester) async {
+    Widget buildFrame(Key builderKey) {
+      return MaterialApp(
+        home: Material(
```
[the remark this answers is not in the document]
Comment (johnsonmh) [reply packages/flutter/test/material/dialog_test.dart]: Nope, removed.

**Review by willlarche — APPROVED** [review]

File: packages/flutter/test/material/dialog_test.dart [hunk 4]
```diff
@@ -607,4 +607,43 @@ void main() {
...
+                },
+                child: const Text('Show Dialog'),
+              );
+            },
+          ),
+        ),
+      );
+    }
+
+    // First time build.
```
Comment (HansMuller) [inline packages/flutter/test/material/dialog_test.dart]: This goes without saying

File: packages/flutter/test/material/dialog_test.dart [hunk 5]
```diff
@@ -607,4 +607,43 @@ void main() {
...
+    await tester.pumpWidget(buildFrame(UniqueKey()));
+
+    // Open the dialog.
+    await tester.tap(find.byType(RaisedButton));
+    await tester.pumpAndSettle();
+
+    // Second time build (deactivate old context).
```
Comment (HansMuller) [inline packages/flutter/test/material/dialog_test.dart]: It would be useful to say: 
Force the Builder to be recreated (new key) which causes outerContext to be deactivated. If showDialog()'s  implementation were to refer to outerContext again, it would crash.

File: packages/flutter/test/material/dialog_test.dart [hunk 6]
```diff
@@ -607,4 +607,43 @@ void main() {
...
+    await tester.pumpWidget(buildFrame(UniqueKey()));
+
+    // Before the fix, app crashes when we try to open the dialog again.
```
Comment (HansMuller) [inline packages/flutter/test/material/dialog_test.dart]: I don't think this is quite right.  The previous step will cause the button's onPressed closure to be recreated, it will refer to the new outerContext value.

The failure mode occurred when the already-visible dialog was rebuilt, because that caused it to refer to the old deactivated context.  Is it enough to just pump one frame here?

File: packages/flutter/test/material/dialog_test.dart (hunk 5 above)
Comment (johnsonmh) [reply packages/flutter/test/material/dialog_test.dart]: Done.

File: packages/flutter/test/material/dialog_test.dart (hunk 6 above)
Comment (johnsonmh) [reply packages/flutter/test/material/dialog_test.dart]: You're totally right, it just took another `tester.pump` to get the crash.  Fixed.

**Review by HansMuller — APPROVED** [review]
LGTM
