### PR TITLE
[flutter_test] Change KeyEventSimulator default transit mode

### LINKED ISSUE #143845: [flutter_test] Default transit mode for key events simulation is not the same as framework
### Steps to reproduce

Run the test provided in code sample.

### Expected results

The test succeeds without forcing `debugKeyEventSimulatorTransitModeOverride` or relying on  `KeySimulationModeVariant`.

### Actual results

The test fails because the transit mode defaults to `KeyDataTransitMode.rawKeyData` whose modifiers logic can not distinguish modifier keys side (and generates both a control left and control right down event when asked to simulate a control left down event).

### Code sample

<details open><summary>Code sample</summary>

```dart
testWidgets('Press control left once', (WidgetTester tester) async {
  final List<KeyEvent> events = <KeyEvent>[];
  final FocusNode focusNode = FocusNode();
  addTearDown(focusNode.dispose);

  await tester.pumpWidget(
    Focus(
      focusNode: focusNode,
      autofocus: true,
      onKeyEvent: (_, KeyEvent event) {
        events.add(event);
        return KeyEventResult.handled;
      },
      child: Container(),
    ),
  );

  await simulateKeyDownEvent(LogicalKeyboardKey.controlLeft);

  // This will fail when transit mode is KeyDataTransitMode.rawKeyData
  // because, in addition of the control left key down event, a down event
  // for control right is synthesized
  expect(events.length, 1);
});

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <1>
  Actual: <2>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
console
[!] Flutter (Channel [user-branch], 3.19.0-3.0.pre.776, on Ubuntu 23.10
    6.5.0-17-generic, locale fr_FR.UTF-8)
    ! Flutter version 3.19.0-3.0.pre.776 on channel [user-branch] at
      /home/bruno/Nevercode/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 3a6384ec61 (il y a 2 heures), 2024-02-21 12:21:09 +0100
    • Engine revision ed49634486
    • Dart version 3.4.0 (build 3.4.0-157.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /media/oldhome/Android/Sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /media/oldhome/Android/Sdk
    • Java binary at: /media/oldhome/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /media/oldhome/Produits/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.86.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-17-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PRs changes the default value transit mode for key event simulation.

The default transit mode for key event simulation is currently `KeyDataTransitMode.rawKeyData` while on the framework side `KeyDataTransitMode.keyDataThenRawKeyData` is the preferred transit mode.

`KeyDataTransitMode.keyDataThenRawKeyData` is more accurate and can help detect issues.

For instance the following test will fail with `KeyDataTransitMode.rawKeyData` because raw keyboard logic for modifier keys is less accurate:

```dart
  testWidgets('Press control left once', (WidgetTester tester) async {
    debugKeyEventSimulatorTransitModeOverride = KeyDataTransitMode.keyDataThenRawKeyData;

    final List<KeyEvent> events = <KeyEvent>[];
    final FocusNode focusNode = FocusNode();
    addTearDown(focusNode.dispose);

    await tester.pumpWidget(
      Focus(
        focusNode: focusNode,
        autofocus: true,
        onKeyEvent: (_, KeyEvent event) {
          events.add(event);
          return KeyEventResult.handled;
        },
        child: Container(),
      ),
    );

    await simulateKeyDownEvent(LogicalKeyboardKey.controlLeft);

    // This will fail when transit mode is KeyDataTransitMode.rawKeyData
    // because a down event for controlRight is synthesized.
    expect(events.length, 1);

    debugKeyEventSimulatorTransitModeOverride = null;
  });
```

And the following this test is ok with `KeyDataTransitMode.rawKeyData` but rightly fails with `KeyDataTransitMode.keyDataThenRawKeyData`:

```dart
  testWidgets('Simulates consecutive key down events', (WidgetTester tester) async {
    debugKeyEventSimulatorTransitModeOverride = KeyDataTransitMode.rawKeyData;

    // Simulating several key down events without key up in between is tolerated
    // when transit mode is KeyDataTransitMode.rawKeyData, it will trigger an
    // assert on KeyDataTransitMode.keyDataThenRawKeyData.
    await simulateKeyDownEvent(LogicalKeyboardKey.arrowDown);
    await simulateKeyDownEvent(LogicalKeyboardKey.arrowDown);

    debugKeyEventSimulatorTransitModeOverride = null;
  });
```

## Related Issue

Fixes https://github.com/flutter/flutter/issues/143845

## Tests

Adds two tests.

### CODE REVIEW

**Comment by bleroux** [comment]
@gspencergoog This will unblock https://github.com/flutter/flutter/pull/143579

This PR also updates some existing tests, because they triggered some asserts when the transit mode is `KeyDataTransitMode.keyDataThenRawKeyData` (they did not when the transit mode was KeyDataTransitMode.rawKeyData). Some were sending several key down events without key up events in between. 

I also added `KeySimulatorTransitModeVariant.rawKeyData() `because some tests require this mode (especially the ones for `RawKeyboard`).

**Comment by bleroux** [comment]
This PR surfaced some wrong key sequences in customer test.
See https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/25.

File: packages/flutter_test/test/event_simulation_test.dart [hunk 1]
```diff
@@ -37,12 +37,25 @@ Future<void> _shouldThrow<T extends Error>(AsyncValueGetter<void> func) async {
...
 
 void main() {
+  testWidgets('default transit mode is keyDataThenRawKeyData', (WidgetTester tester) async {
+    expect(KeyEventSimulator.transitMode, KeyDataTransitMode.keyDataThenRawKeyData);
+  });
+
+  testWidgets('debugKeyEventSimulatorTransitModeOverride overrides default transit mode', (WidgetTester tester) async {
+    debugKeyEventSimulatorTransitModeOverride = KeyDataTransitMode.rawKeyData;
+    expect(KeyEventSimulator.transitMode, KeyDataTransitMode.rawKeyData);
+    // Unsetting debugKeyEventSimulatorTransitModeOverride can't be call in a
```
Comment (gspencergoog) [inline packages/flutter_test/test/event_simulation_test.dart:47]:
```suggestion
    // Unsetting debugKeyEventSimulatorTransitModeOverride can't be called in a
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks, this is a good thing to do, I had forgotten to set that default when I deprecated the `RawKeyEvent` stuff.

**Comment by gspencergoog** [comment]
> This PR surfaced some wrong key sequences in customer test. See [Flutter-Bounty-Hunters/flutter_test_robots#25](https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/25) and [superlistapp/super_editor#1853](https://github.com/superlistapp/super_editor/pull/1853).

These will have to be fixed before we can commit this PR, since they're in customer tests.

**Comment by bleroux** [comment]
> This PR surfaced some wrong key sequences in customer test. See [Flutter-Bounty-Hunters/flutter_test_robots#25](https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/25) and [superlistapp/super_editor#1853](https://github.com/superlistapp/super_editor/pull/1853).

cc @matthew-carroll @angelosilvestre I'm not sure of the process on your side, if my PRs are not compliant with your process thank you for making those changes.

**Comment by matthew-carroll** [comment]
@bleroux we'll need someone to open a PR in the super_editor repo with the appropriate fix, as mentioned in the policies for customer tests and breaking changes.

**Comment by bleroux** [comment]
> @bleroux we'll need someone to open a PR in the super_editor repo with the appropriate fix, as mentioned in the policies for customer tests and breaking changes.

@matthew-carroll 
I filed two PRS:
- https://github.com/superlistapp/super_editor/pull/1853 for super_editor
- https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/25 on flutter_test_robots because it is a dependance use by super_editor.

**Comment by bleroux** [comment]
@matthew-carroll The PRs on `super_editor` and `flutter_test_robots` are merged, thanks. Unfortunately the super editor customer tests are still failing because `super_editor` depends on `flutter_test_robots v0.22` which does not contain my fix. Do you plan to release a new version for `flutter_test_robots`?

@gspencergoog The Google testing step is failing, it is probably related to some internal tests simulating wrong key sequences. Can you have a look to those failures?

**Comment by matthew-carroll** [comment]
@bleroux for now you can put up a super_editor PR that adds a dependency override to use the GitHub version of flutter_test_robots.

**Comment by bleroux** [comment]
@gspencergoog Customer tests are ok now, unfortunately Google testing step is failing, are they many internal test failures or just a few of them?

**Comment by gspencergoog** [comment]
It's just one.  I'll see if I can fix it.

**Comment by gspencergoog** [comment]
Okay, I fixed it, but the change needs to be reviewed and submitted.  I'll restart the check here once it has been submitted internally.

**Comment by gspencergoog** [comment]
(it's a trivial fix, but it'll probably be a day before approval because of the time zone the reviewers are in)

**Comment by gspencergoog** [comment]
Okay, Google tests fixed.

**Comment by itsjustkevin** [comment]
Reverting due to issues reported in b/328788027.

**Comment by itsjustkevin** [comment]
@gspencergoog this PR does not revert can you take a look?
