### PR TITLE
[flutter_tools] tool exit from flutter create when provided just a drive letter

### LINKED ISSUE #104544: [flutter_tools] FileSystemException Exists failed, path = 'D:\D:\android\app'
On `stable/3.0.1`

`flutter --no-color create --template app --description A new Flutter project. --org com.example --platforms android,ios --project-name project_name D:`

```
FileSystemException: Exists failed, path = 'D:\D:\android\app' (OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123)
at _Directory.existsSync(directory_impl.dart:94)
at ForwardingFileSystemEntity.existsSync(forwarding_file_system_entity.dart:43)
at ErrorHandlingDirectory.existsSync.<anonymous closure>(error_handling_io.dart:497)
at _runSync(error_handling_io.dart:597)
at ErrorHandlingDirectory.existsSync(error_handling_io.dart:496)
at CreateBase.determineTemplateType.exists(create_base.dart:230)
at CreateBase.determineTemplateType(create_base.dart:236)
at CreateCommand._getProjectType(create.dart:170)
at CreateCommand.runCommand(create.dart:210)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1342)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1183)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:281)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:94)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/104544

As described on the bug, the core problem is that `dart:io` does not consider `D:` an absolute path and thus treats it like a relative path and prepends it with the current working directory: https://github.com/dart-lang/sdk/blob/main/sdk/lib/io/file_system_entity.dart#L571.

Creating an app at the root of a drive is probably a user error anyway (they probably want it contained in a folder), so we tool exit with instructions on how to create it in a folder at the top level of the drive, or alternatively to specify `D:\` if they really want it at the root of the drive.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/create_base.dart [hunk 1]
```diff
@@ -132,9 +132,26 @@ abstract class CreateBase extends FlutterCommand {
     );
   }
 
+  /// Pattern for a Windows file system drive (e.g. "D:").
+  ///
+  /// `dart:io` does not recognize strings matching this pattern as absolute
+  /// paths, as they have no top level back-slash; however, users often specify
+  /// this
+  static final RegExp _kWindowsDrivePattern = RegExp(r'^[A-Z]:$');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/commands/create_base.dart:140]: Is there anything helpful in `package:path` instead of potentially duplicating this logic?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:140]: I see [`rootPattern`](https://github.com/dart-lang/path/blob/master/lib/src/style/windows.dart#L29), but that is a superset of what we want here, including a trailing slash (this is the same pattern that dart:io uses).

However, from looking at that, I can see that this regex should include lower-case letters.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:140]: oh wait, never mind, this helper looks like it does the trick: https://github.com/dart-lang/path/blob/master/lib/src/utils.dart#L18

Comment (zanderso) [reply packages/flutter_tools/lib/src/commands/create_base.dart:140]: I saw that, but couldn't tell if it was public.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:140]: Shucks, it isn't exported

**Review by loic-sharma — APPROVED** [review]

**Review by zanderso — APPROVED** [review]
