### PR TITLE
Fix search view position

### LINKED ISSUE #123975: `SearchAnchor` doesn't respect window edge
### Steps to reproduce
1. Open SearchAnchor https://github.com/flutter/flutter/blob/master/examples/api/lib/material/search_anchor/search_anchor.2.dart
2. Add `crossAxisAlignment: CrossAxisAlignment.end,` to the `Column` to move `SearchAnchor` to the edge.
3. Run the app and click the `SearchAnchor` button on a desktop platform. 

https://user-images.githubusercontent.com/48603081/229375250-fdfeb82e-8e37-49e3-bf1d-445b66b479ac.mov

### PR DESCRIPTION
**Pull request by QuncCccccc**
This PR is to fix the position of the search view to make sure it respects the window edge. If the search view goes off the screen, we move the view to the opposite direction so that it will not be clipped by the screen edges. If the screen size is smaller than the search view size that it should be, then the search view should be resized to fit the screen.

Fixes: #123975

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SearchBarApp());

class SearchBarApp extends StatefulWidget {
  const SearchBarApp({super.key});

  @override
  State<SearchBarApp> createState() => _SearchBarAppState();
}

class _SearchBarAppState extends State<SearchBarApp> {
  final SearchController controller = SearchController();

  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = ThemeData(useMaterial3: true);

    return MaterialApp(
      theme: themeData,
      home: Scaffold(
        appBar: AppBar(title: const Text('Search Anchor Sample')),
        body: Align(
          alignment: Alignment.bottomRight,
          child: SearchAnchor(
            searchController: controller,
              builder: (BuildContext context, SearchController controller) {
                return IconButton(
                  icon: const Icon(Icons.search),
                  onPressed: () {
                    controller.openView();
                  },
                );
              },
              suggestionsBuilder: (BuildContext context, SearchController controller) {
                return List<ListTile>.generate(5, (int index) {
                  final String item = 'item $index';
                  return ListTile(
                    title: Text(item),
                    onTap: () {
                      setState(() {
                        controller.closeView(item);
                      });
                    },
                  );
                });
              }
            ),
        ),
      ),
    );
  }
}
```

</details>

The code sample just uses the example in examples/api/lib/material/search_anchor/search_anchor.2.dart file but it changes the alignment to be `Alignment.bottomRight` to test both height and width.

https://user-images.githubusercontent.com/36861262/229943897-2788ce4e-68ab-4780-b1fe-2a71d5c1f2f3.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 1]
```diff
@@ -477,24 +483,44 @@ class _SearchViewRoute extends PopupRoute<_SearchViewRoute> {
...
     final Rect anchorRect = getRect() ?? Rect.zero;
 
-    // Check if the search view goes off the screen.
     final BoxConstraints effectiveConstraints = viewConstraints ?? viewTheme.constraints ?? viewDefaults.constraints!;
-    final double verticalDistanceToEdge = screenSize.height - anchorRect.top;
-    final double endHeight = math.max(effectiveConstraints.minHeight, math.min(screenSize.height * 2 / 3, verticalDistanceToEdge));
     _rectTween.begin = anchorRect;
 
+    double viewWidth = anchorRect.width;
+    viewWidth = clampDouble(viewWidth, effectiveConstraints.minWidth, effectiveConstraints.maxWidth);
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/search_anchor.dart:490]: Is this for readability? Couldn't we make this one line? 
```suggestion
    double viewWidth = anchorRect.width;
    viewWidth = clampDouble(viewWidth, effectiveConstraints.minWidth, effectiveConstraints.maxWidth);
```

Comment (TahaTesser) [reply packages/flutter/lib/src/material/search_anchor.dart:490]: Same for `viewWidth` in other places.

**Review by TahaTesser — APPROVED** [review]
LGTM! (with one comment)

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 2]
```diff
@@ -477,24 +483,44 @@ class _SearchViewRoute extends PopupRoute<_SearchViewRoute> {
     final Size screenSize = MediaQuery.of(context).size;
     final Rect anchorRect = getRect() ?? Rect.zero;
 
-    // Check if the search view goes off the screen.
     final BoxConstraints effectiveConstraints = viewConstraints ?? viewTheme.constraints ?? viewDefaults.constraints!;
-    final double verticalDistanceToEdge = screenSize.height - anchorRect.top;
-    final double endHeight = math.max(effectiveConstraints.minHeight, math.min(screenSize.height * 2 / 3, verticalDistanceToEdge));
     _rectTween.begin = anchorRect;
 
+    double viewWidth = anchorRect.width;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/search_anchor.dart:489]: It looks like much of the code here and in didChangeDependencies is at least very similar. In a future PR, factoring out a utility method that adjust the search view's bounds to fit, might be a good idea.

**Review by HansMuller — APPROVED** [review]
LGTM.

File: packages/flutter/lib/src/material/search_anchor.dart (hunk 1 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/search_anchor.dart]: Just fixed! Thanks:) !

File: packages/flutter/lib/src/material/search_anchor.dart (hunk 2 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/search_anchor.dart]: I see. Will create a refactor PR to fix this and another [comment](https://github.com/flutter/flutter/pull/123256#discussion_r1148113121) in the previous PR. Thanks!
