### PR TITLE
Editable text should call onSelectionChanged when selection changes a…

### LINKED ISSUE #71963: SelectableText is not firing onSelectionChanged in all cases
## Steps to Reproduce

1. Use SelectableText widget in a working app
```
SelectableText.rich(
      TextSpan(
        text: 'Hello world',
      ),
      toolbarOptions: ToolbarOptions(copy: false, cut: false, paste: false, selectAll: true),
      onSelectionChanged: (TextSelection selection, cause) {
        print(selection);
      },
      enableInteractiveSelection: true,
    )
```
2. Run the app and press and hold to select "Hello"
3. Note the `onSelectionChanged` is fired as expected. You can do the same to "World"
4. But then again select "Hello" and move the handle manually to cover world as well.
5. `onSelectionChanged` is not fired in this case
6. Now use "Select All" control. `onSelectionChanged` is not fired in this case either.

**Expected results:** 
`onSelectionChanged` has to be fired in all 3 cases i.e.
1. press and hold to select
2. press and hold and then extending the selection manually using handles
3. using selectAll control

**Actual results:**
`onSelectionChanged` is only fired in 1st case mentioned above

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.25.0-5.0.pre.90, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
…re caused by selection overlay

## Related Issues

Fixes https://github.com/flutter/flutter/issues/71963

## Tests

I added the following tests:

see files

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2236,6 +2235,20 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       }
     }
 
+    if (_value.selection != value.selection) {
+      try {
+        widget.onSelectionChanged?.call(value.selection, null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:2240]: We don't seem to have a selection change cause when it is caused by selection overlay, I passing null instead. Should we create a new cause? This method will be called when user drag selection handles or tap on tool bar select all. I don't think we have a way to distinguish them.

**Comment by chunhtai** [comment]
cc @pedromassango

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -2236,6 +2235,20 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       }
     }
 
+    if (_value.selection != value.selection) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:2238]: I believe `RenderEditable` also calls `_handleSelectionChanged` when handling raw keyboard events (i.e. in `RenderEditable._handleMovement`), after calling `_formatAndSave`. Sounds like `widget.onSelectionChanged` is going to be called twice in this scenario?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart:2238]: It looks like we should call handleSelectionChange first and then sets textEditingValue in renderEditable, I am quite curious though, why do we need to set textEditingValue in the first place?
For _handleShortcuts, LogicalKeyboardKey.keyA only calls _handleselectionchange but not setting the textEditingValue

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:2240]: Would it be possible to call onSelectionChanged somewhere higher up in the call stack where you can distinguish drag/select-all?  That might also help work around the duplicate call to onSelectionChanged that @LongCatIsLooong mentioned above.

Comment (pedromassango) [reply packages/flutter/lib/src/widgets/editable_text.dart:2240]: I think we should create an issue to track the new cause creation, add implement it if lots of people are interested in it.

LGTM, once you update the docs of `onSelectionChanged` to make it clear in which cases the `cause` will be null.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart:2240]: The only place we can tell what causes the selection change is in the selection overlay because it just set textEditingValue for all the changes happens in selection overlay. I am struggling to find a clean API to be able to move the logic into selection overlay.

The problem that @LongCatIsLooong  mentioned is a bug in render editable i think.

So handleMovement does two thing in this order
1. set textEditingValue
2. call onSelectionChange

This is wrong because the selection would have been updated in step 1, so step 2 is calling selection change with the same selection.

The correct order should be as following
1. call onSelectionChange
2. set textEditingValue

I am not sure whether 2 is even needed.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2238]: Traced it to https://github.com/flutter/flutter/pull/44130 where the `textSelectionDelegate.textEditingValue = textSelectionDelegate.textEditingValue.copyWith(selection: newSelection);` was first added. It looks like we want to send the selection change to the engine.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I didnt see any code path that will send the change to the enigne. Do you know where does that happen?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart]: The `_value = value` line does it (in one of the listeners).

https://github.com/flutter/flutter/blob/8cd03a2e3649d9fc92442f2ea04417fcf30ebb70/packages/flutter/lib/src/widgets/editable_text.dart#L2225-L2237

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart:2241]: So I decide to leave at the same place. If we want to move it higher up, we will have to add API to TextSelectionDelegate to update the selection, and makes selection overlay to call both set textEditingValue and  the new update selection API which is quite ugly. I am still open to suggestion though.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart]: ah i thought _value was just a variable, that make sense, but should we also apply this to handle shortcut as well?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Maybe we should change it to `widget.controller.value = value` so this line doesn't get overlooked. 

You mean this part?
https://github.com/flutter/flutter/blob/be1325f18b5e557641fa48e0e40fa694fae131e1/packages/flutter/lib/src/rendering/editable.dart#L805-L814

Yeah looks like it needs to call the `textEditingValue` setter here too. It feels the callbacks in `RenderEditable` are getting a bit out of hand.  I think we're moving the keyboard events handling out of the `RenderEditable` class? /cc @justinmc

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 3]
```diff
@@ -4253,7 +4253,7 @@ void main() {
       selection,
       equals(
         const TextSelection(
-          baseOffset: 10,
```
Comment (chunhtai) [inline packages/flutter/test/widgets/editable_text_test.dart:4256]: We were testing the wrong behavior, the refactoring exposes this bug

**Comment by chunhtai** [comment]
Hi This is ready for another look, cc @gspencergoog since I touched some of the raw key event code

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:2241]: That sounds good to me.  I think getting this right will require a bigger refactor, which hopefully is upcoming.  No need to hack something now.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_test.dart:4256]: Nice, these were clearly wrong in retrospect.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: That's the plan.  This PR is reminding me how important it is.  These sorts of changes shouldn't be so confusing.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -778,39 +778,44 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
             offset: math.min(selection.start, selection.end) + data.text!.length,
           ),
         );
       }
-      return;
-    }
-    if (key == LogicalKeyboardKey.keyA) {
-      _handleSelectionChange(
-        selection.copyWith(
+    } else if (key == LogicalKeyboardKey.keyA) {
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:802]: Any idea why these were `if`s instead of `else if`s before?  It doesn't look to me like any of them should be possible to happen at the same time.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/rendering/editable.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:802]: We used return to short circuit the rest ifs

**Comment by cjayawickrema** [comment]
hey guys, around when can we expect this to merge?

**Comment by chunhtai** [comment]
@LongCatIsLooong I updated the short circuit code, let me know what you think.

**Comment by gspencergoog** [comment]
Looks like there are still some issues with surrogate pairs in the tests.

**Comment by chunhtai** [comment]
we still need to set the texteditingvalue, because it is not guarantee RenderEditable.onSelectionChanged will update the selection in texteditngvalue.

**Review by LongCatIsLooong — APPROVED** [review]
