### PR TITLE
[ios26]Do not report error for Info.plist key not found

### LINKED ISSUE #172627: [Xcode 26 beta 4] Xcode reports `Could not extract value, error: No value at that key path or invalid key path` for some keys when running on iOS
### Steps to reproduce

1. Use Xcode 26 beta 4
2. Create a new flutter app on either stable, beta or master
3. Run the app on iOS

### Expected results

Xcode doesn't report missing keys in the logs

### Actual results

Xcode reports missing keys in the logs. The app still launches, however, sometimes I cannot debug the app. After the application launches, the app just closes with this message. 

```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:64581/WJVUsMFhG58=/
HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:64581/WJVUsMFhG58=/ws
```

I tested on iOS 18.6 and iOS 26 and on both devices, I see the message in the logs section below. (Error added below for brevity). 

The error goes away when I add the respective entitlements. I tested with this by adding the  `NSLocalNetworkUsageDescription` key and the error went away. I didn't test `NSBonjourServices` (this I believe is an array, and I wasn't sure which options would apply in our case). However, I believe when we add the right options for the `NSBonjourServices`, the error should go away . This does not happen with Xcode 26 beta 3. 

When running on the stable channel, the error is not surfaced in `flutter run`. It is surfaced when you run `flutter run -v`. 

```
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSBonjourServices
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription
```

### Code sample

The counter app should suffice for this (added below)

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

N/A

### Logs

[ios26.log](https://github.com/user-attachments/files/21384437/ios26.log)

[ios18_6.log](https://github.com/user-attachments/files/21384440/ios18_6.log)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.7, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [824ms]
    • Flutter version 3.32.7 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7b523b356 (7 days ago), 2025-07-15 17:03:46 -0700
    • Engine revision 39d6d6e699
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.5s]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [1,523ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [13ms]
    • Android Studio at /Users/deanli/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.102.1) [11ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (4 available) [12.6s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [2.2s]
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.33.0-1.0.pre-1078, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [3.3s]
    • Flutter version 3.33.0-1.0.pre-1078 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision afba7d75b3 (7 hours ago), 2025-07-23 14:04:50 +1200
    • Engine revision afba7d75b3
    • Dart version 3.10.0 (build 3.10.0-15.0.dev)
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [1,462ms]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Emulator version 36.1.8.0 (build_id 13784423) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [980ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [5ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6.2s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [831ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by hellohuanlin**
In xcode_backend's `runSync` function, there's a flag parameter `allowFail`. The purpose of this flag is that, when enabled, even if command fails, we should not fail Xcode. 

However, the current implementation has a bug, that even when `allowFail = true`, we still prefix `"error:"` string to `stderr`, which causes Xcode compilation error. 

Before macOS 26, plutil used `stdout` rather than `stderr`, so the bug was not surfaced. On macOS 26, pltuil uses `stderr` instead (which makes sense), so the bug is surfaced now. 

Note: even if plutil doesn't change behavior on macOS 26, if I randomly come across this code, I'd still fix the logic error. 

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

Fixes https://github.com/flutter/flutter/issues/172627

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 1]
```diff
@@ -122,7 +122,7 @@ class Context {
     final String resultStderr = result.stderr.toString().trim();
     if (resultStderr.isNotEmpty) {
       final errorOutput = StringBuffer();
-      if (result.exitCode != 0) {
+      if (result.exitCode != 0 && !allowFail) {
         // "error:" prefix makes this show up as an Xcode compilation error.
```
Comment (hellohuanlin) [inline packages/flutter_tools/bin/xcode_backend.dart:129]: > // "error:" prefix makes this show up as an Xcode compilation error.
Comment

This feels so fragile. Wondering if it's documented somewhere?

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 2]
```diff
@@ -122,7 +122,7 @@ class Context {
     final String resultStderr = result.stderr.toString().trim();
     if (resultStderr.isNotEmpty) {
       final errorOutput = StringBuffer();
-      if (result.exitCode != 0) {
+      if (result.exitCode != 0 && !allowFail) {
```
[the remark this answers is not in the document]
Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart]: > While this change correctly uses allowFail to suppress the error prefix, the allowFail flag is a bit broad. 

Bad Gemini. If we want Xcode compile to fail, we should set `allowFail = false`; if we want Xcode compile to continue, then set `allowFail = true`.

File: packages/flutter_tools/bin/xcode_backend.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: You know it ain't (that I'm aware of).

**Review by jmagman — COMMENTED** [review]
Why isn't it found though? `NSBonjourServices` etc needs to be there for the port to be published. A race condition?

**Comment by jmagman** [comment]
> Why isn't it found though? `NSBonjourServices` etc needs to be there for the port to be published. A race condition?

Victoria explained it to me, the key is supposed to be missing, the new behavior is that it errors during the check.

**Comment by hellohuanlin** [comment]
> Why isn't it found though? `NSBonjourServices` etc needs to be there for the port to be published. A race condition?

@jmagman Sorry just saw this. I did more testing today - it turns out that it's because the change in `plutil` on macOS 26: 

On old macOS, plutil uses `stdout` for "key not found", and since we only check `stderr`, so we don't trigger Xcode failure. 

But on macOS 26, plutil uses `stderr` now (which makes more sense so I can't complain), hence the Xcode failure.

File: packages/flutter_tools/test/integration.shard/xcode_backend_test.dart [hunk 3]
```diff
@@ -196,6 +197,8 @@ void main() {
 </dict>
 </plist>
 ''');
+
+        expect(result.stderr, isNot(startsWith("error:")));
```
Comment (hellohuanlin) [inline packages/flutter_tools/test/integration.shard/xcode_backend_test.dart]: Without the fix, this would fail on macOS 26. I manually tested it since our CI doesn't run macOS 26 yet.

File: packages/flutter_tools/bin/xcode_backend.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: Can you add a comment explaining this is needed to prevent the build from failing?

Can you also add a unit test to `general.shard/xcode_backend_test.dart` to ensure it doesn't stream the error logs when `allowFail` is true?

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: Sure I can add some comment. 

Just to clarify, this is to fix the logic error, which **happens** to be surfaced by macOS 26. In another word, even without this incident, if I randomly come across this code, I would fix it too. 

So strictly speaking, it's more like "this is needed, so that the code is doing what it's intended to do, i.e., don't cause Xcode failure if allowFail=true". That being said, I can refer to this incident as an example.

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: Re the streaming part - the streaming logic doesn't seem to be related to allowFail: 

```
      if (!verbose && exitCode == 0) {
        streamOutput(errorOutput.toString());
      }
```

I will leave it there.

**Comment by hellohuanlin** [comment]
friendly ping @vashworth @jmagman (as the github refresh button is gone for some reason)

File: packages/flutter_tools/bin/xcode_backend.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: > Re the streaming part - the streaming logic doesn't seem to be related to allowFail:

The `errorOutput` differs depending on `allowFail`, though. I suppose you could also use `echoError` from line 133 to unit test it. Either will work to validate that `error:` is not added to `errorOutput`.

With only an integration test, if `plutil` changes again, we'll no longer be validating this logic -- which is why I think it'd be good to also have a unit test.

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: > The errorOutput differs depending on allowFail. I suppose you could also use echoError from line 133 to unit test it.

Isn't it covered by the test I added in integration.shard? The test is checking what's passed into `echoError` in line 133.

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: Are you suggesting to write the same test again, but in unit test with mock commands?

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: Alright, I took a look at the whole xcode_backend.dart file and its tests. Looks like there's a design issue. Let me file a ticket which should clear things up.

Comment (vashworth) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: > Are you suggesting to write the same test again, but in unit test with mock commands?

Yes, see my comment above:

"With only an integration test, if `plutil` changes again, we'll no longer be validating this logic -- which is why I think it'd be good to also have a unit test."

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: > With only an integration test, if plutil changes again, we'll no longer be validating this logic 

To clarify, if `plutil` changes again, the best tests to catch any breakage would be the integration test, not the unit test. This is because integration test runs the actual command, while unit test runs fake command. 

> which is why I think it'd be good to also have a unit test.

That being said, I fully agree we should also have a unit test, which provides another level of confidence. The unit test can either directly test `runSync`, or better, test another function that calls `runSync` function. 

However, I think there's a design flaw in our setup that needs to be addressed before being able to do so - `runSync` itself is currently not testable - our unit test does not run this code at all since it's stubbed out (more details here https://github.com/flutter/flutter/issues/173133).  

I am OK with either: 
(1) land this PR first, and fix the design flaw as a follow up; or
(2) fix the design flaw first (at least the "short term fix" section), and then rebase this PR. I can do this when I come back next Wednesday.

Comment (jmagman) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: I had to read the `addVmServiceBonjourService` function to figure out what this change is doing and why.
@hellohuanlin can you update the PR description to explain in particular what `allowFail` has to do with the fix.

Remember we need to be able to read these commits and understand what they mean years from now 🙂

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:129]: @jmagman updated description! let me know if it's not clear

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 4]
```diff
@@ -144,6 +147,17 @@ class Context {
...
 
+  // TODO(hellohuanlin): Instead of using inheritance to stub the function in
+  // the subclass, we should favor composition by injecting the dependencies.
+  // See: https://github.com/flutter/flutter/issues/173133
+  ProcessResult runSyncProcess(
+    String bin,
+    List<String> args, {
+    String? workingDirectory,
+  }) {
+    return Process.runSync(bin, args, workingDirectory: workingDirectory);
```
Comment (hellohuanlin) [inline packages/flutter_tools/bin/xcode_backend.dart:154]: @vashworth @jmagman This is the short term workaround to make bonjour unit testable. It follows the existing design pattern (inheritance). I will just go with it first since it's a quick fix and we are fire fighting. 

Before the change, the whole implementation of `runSync` is stubbed out, which defeats the purpose of unit tests. For unit test, we should stub out the dependencies of the test subject, not the implementation of test subject itself.

In the long term, however, i'd like to fix the design flaw (inheritance -> composition) for better testability and maintainability. See also: https://github.com/flutter/flutter/issues/173133 and  https://github.com/flutter/flutter/issues/173138

File: packages/flutter_tools/test/general.shard/xcode_backend_test.dart [hunk 5]
```diff
@@ -389,6 +389,122 @@ void main() {
         ),
       );
     });
+
+    test('Missing NSBonjourServices key in Info.plist should not fail Xcode compilation', () {
```
Comment (vashworth) [inline packages/flutter_tools/test/general.shard/xcode_backend_test.dart:393]: nit: While these tests technically covers the expected behavior, we could make them even more specific by calling `runSync` directly. This would better confirm that `error:` is not added when `allowFail` is true and would also allow us to add a test case for when `allowFail` is false. This isn't a blocking issue, but it would improve the test coverage.

File: packages/flutter_tools/bin/xcode_backend.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/bin/xcode_backend.dart:154]: This makes sense to me, thanks for figuring it out!

**Review by vashworth — APPROVED** [review]
LGTM

File: packages/flutter_tools/test/general.shard/xcode_backend_test.dart (hunk 5 above)
Comment (hellohuanlin) [reply packages/flutter_tools/test/general.shard/xcode_backend_test.dart:393]: `runSync` is our private helper function which is the implementation details though. Unit tests should verify the *behavior*, not the *implementation*. 

that being said, in the future if `runSync` is used elsewhere, I don't object refactoring it into a separate component, then it would become the API of it, which should be unit tested

**Comment by vashworth** [comment]
@hellohuanlin You have analyze errors:

To fix, run 
```
dart format packages/flutter_tools/bin/xcode_backend.dart packages/flutter_tools/test/general.shard/xcode_backend_test.dart
```
