### PR TITLE
Ensure that DropDownMenus are always onscreen

### LINKED ISSUE #3720: Dropdown extends off the top of the screen
## Steps to Reproduce

1. Have a dropdown at or near the top of your screen with >4 items in it
2. Select an item from near the bottom of the list.
3. Open the dropdown again.  The first item(s) will be unselectable.

### PR DESCRIPTION
**Pull request by abarth**
This patch sizes the menu such that it is always on screen, but doesn't scroll
the menu to ensure that the currently selected item is always visible and on
top of the button. That will need to wait for a later patch.

Also, teach CustomPaint how to repaint animations more efficiently.

Fixes #3720

### CODE REVIEW

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -1382,12 +1383,18 @@ class RenderFractionalTranslation extends RenderProxyBox {
...
+/// this animation and repaint whenever the animation ticks, avoiding both the
+/// build and layout phases of the pipeline.
+///
 /// The [hitTest] method is invoked when the user interacts with the underlying
 /// render object, to determine if the user hit the object or missed it.
 abstract class CustomPainter {
-  /// Abstract const constructor. This constructor enables subclasses to provide
-  /// const constructors so that they can be used in const expressions.
-  const CustomPainter();
+  /// The painter will repaint whenever the [repaint] animation ticks.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: `Creates a CustomPainter.` ...

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 2]
```diff
@@ -1537,6 +1544,24 @@ class RenderCustomPaint extends RenderProxyBox {
         newPainter.shouldRepaint(oldPainter)) {
       markNeedsPaint();
     }
+    if (attached) {
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: _checkForRepaint sounds like it would be idempotent. Maybe rename this function now that it's a change handler?

File: packages/flutter/test/material/drop_down_test.dart [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    tester.tap(find.text('4'));
+    tester.pump();
+    tester.pump(const Duration(seconds: 1)); // finish the menu animation
+
+    tester.tap(find.byConfig(button));
+
+    // Ideally this would be 4 because the menu would be overscrolled to the
+    // correct position, but currently we just reposition the menu so that it
+    // is visible on screen.
+    expect(value, equals(0));
```
Comment (Hixie) [inline packages/flutter/test/material/drop_down_test.dart]: turns out (i just learnt today) you don't need the "equals" if the argument is a simple value. Just `expect(value, 0)`, it's neater.

File: packages/flutter/test/material/drop_down_test.dart [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+
+    tester.pump();
+    tester.pump(const Duration(seconds: 1)); // finish the menu animation
```
Comment (Hixie) [inline packages/flutter/test/material/drop_down_test.dart]: you shouldn't need to have any trailing pumps.

File: packages/flutter/lib/src/material/drop_down.dart [hunk 5]
```diff
@@ -164,20 +158,35 @@ class _DropDownMenuRouteLayout extends SingleChildLayoutDelegate {
...
 
   @override
   Offset getPositionForChild(Size size, Size childSize) {
-    return new Offset(
-      buttonRect.left,
-      buttonRect.top - selectedIndex * buttonRect.height - _kMenuVerticalPadding.top
-    );
+    double top = buttonRect.top - selectedIndex * buttonRect.height - _kMenuVerticalPadding.top;
+    double topPreferredLimit = buttonRect.height;
+    if (top < topPreferredLimit) {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/drop_down.dart]: nit: no need for braces

**Comment by Hixie** [comment]
LGTM
