### PR TITLE
[flutter_tools] dont require a device for screenshot type skia/rasterizer

### LINKED ISSUE #80149: "flutter screenshot" requires a project and gets really confused without one
`flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:45117/sFw78QMClFY=/` run in some random directory (not one with a Flutter project) crashes with confusing output:

```
ianh@burmese:~$ flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:45117/sFw78QMClFY=/
No supported devices connected.
The following devices were found, but are not supported by this project:
Lenovo TB 8504F (mobile) • HGAFGRP2 • android-arm64  • Android 7.1.1 (API 25)
Linux (desktop)          • linux    • linux-x64      • Linux
Chrome (web)             • chrome   • web-javascript • Google Chrome 89.0.4389.90
If you would like your app to run on android or linux or web, consider running `flutter create .` to generate projects for these platforms.


Oops; flutter has exited unexpectedly: "_flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.".
Unable to generate crash report due to secondary error: Null check operator used on a null value
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "_flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.".
Unable to generate crash report due to secondary error: Null check operator used on a null value
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:172:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>
ianh@burmese:~$ 
```

### LINKED ISSUE #80151: "flutter screenshot --type=device --observatory-uri=..." should warn that it's ignoring the Observatory URI
I tried to take a screenshot from an app running on `flutter-tester` using `flutter screenshot --type=device --observatory-uri=...` (`--type=device` is the default, fwiw), and it worked. Except it didn't actually work, what happened is it ignored the Observatory URL provided and just grabbed the image from the connected Android device.

It would have been nice if it said that the Observatory URL was being ignored, or maybe just flat out failed saying those two options can't be used together like that.

### PR DESCRIPTION
**Pull request by jonahwilliams**
flutter screenshot does not require a device for rasterizer/skia. Move device lookup so that it only happens when the device type is selected. update unit tests to run more of the command logic.

Fixes https://github.com/flutter/flutter/issues/80149
Fixes https://github.com/flutter/flutter/issues/80151

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/screenshot.dart [hunk 1]
```diff
@@ -87,8 +88,7 @@ class ScreenshotCommand extends FlutterCommand {
 
   @override
   Future<FlutterCommandResult> verifyThenRunCommand(String commandPath) async {
-    device = await findTargetDevice();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/screenshot.dart:90]: this was the problem line

File: packages/flutter_tools/lib/src/commands/screenshot.dart [hunk 2]
```diff
@@ -65,9 +65,10 @@ class ScreenshotCommand extends FlutterCommand {
...
   Device device;
 
-  static void validateOptions(String screenshotType, Device device, String observatoryUri) {
+  Future<void> _validateOptions(String screenshotType, String observatoryUri) async {
     switch (screenshotType) {
       case _kDeviceType:
+        device = await findTargetDevice();
         if (device == null) {
           throwToolExit('Must have a connected device for screenshot type $screenshotType');
         }
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/screenshot.dart:74]: while you're at it you could throw if observatoryUri is non-null (see https://github.com/flutter/flutter/issues/80151)

File: packages/flutter_tools/test/commands.shard/hermetic/screenshot_command_test.dart [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+  group('Validate screenshot options', () {
+    testUsingContext('rasterizer and skia screenshots do not require a device', () async {
+      openChannelForTesting = (String url, {CompressionOptions compression, Logger logger}) async {
+        expect(url, 'ws://localhost:8181/ws');
+        throw Exception('dummy');
+      };
+
+      await expectLater(() => createTestCommandRunner(ScreenshotCommand())
+        .run(<String>['screenshot', '--type=skia', '--observatory-uri=http://localhost:8181']),
+        throwsException,
```
Comment (Hixie) [inline packages/flutter_tools/test/commands.shard/hermetic/screenshot_command_test.dart:31]: should we be checking what exception is thrown exactly? it seems like if this regressed, it would still actually throw an exception...

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Thanks for fixing this. Didn't mean to nerd-snipe you. :-)

File: packages/flutter_tools/test/commands.shard/hermetic/screenshot_command_test.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/commands.shard/hermetic/screenshot_command_test.dart]: Done

File: packages/flutter_tools/lib/src/commands/screenshot.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/screenshot.dart:77]: Done

**Comment by jonahwilliams** [comment]
No worries :)

I'm just happy to know what this command is supposed to be used for

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by linhzz999** [comment]
Ok

**Review by linhzz999 — COMMENTED** [review]
Ok

**Review by linhzz999 — COMMENTED** [review]
Ok

**Review by linhzz999 — COMMENTED** [review]
Ok
