### PR TITLE
Make structuredErrors to not mess up with onError

### LINKED ISSUE #48972: FlutterError.onError not catching exceptions produced in the app, as part of the SDK
## Steps to Reproduce

1. Setup your app inside `runZoned`
2. Setup `FlutterError.onError`
3. Throw an exception from a button tap

**Expected**: exception would be captured by `FlutterError.onError`
**Actual**: exception is printed on console, but not captured by `FlutterError.onError`

### Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!
```

### Sample

```main.dart
import 'dart:async';
import 'package:flutter/material.dart';

Future<void> main() async {
  FlutterError.onError = (FlutterErrorDetails errorDetails) {
    print('This is an error on the Flutter SDK');
    print(errorDetails.exception);
    print('-----');
    print(errorDetails.stack);
  };
  runZoned(() {
    runApp(App());
  }, onError: (error, stackTrace) {
    print('This is a pure Dart error');
    print(error);
    print('-----');
    print(stackTrace);
  });
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text('Throw'),
            onPressed: () {
              throw Exception('my error');
            },
          ),
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by nt4f04uNd**
Fixes https://github.com/flutter/flutter/issues/48972

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -877,6 +877,11 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
   ///
   /// Do not call [onError] directly, instead, call [reportError], which
   /// forwards to [onError] if it is not null.
+  ///
+  /// See also:
+  ///
+  ///  * <https://flutter.dev/docs/testing/errors>, more information about error
+  ///    handling in Flutter.
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/foundation/assertions.dart:884]: This is linked above in the `FlutterError` doc comment, but I think this can be also a useful place to have this link

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart [hunk 2]
```diff
@@ -13,82 +13,35 @@ void main() {
...
-    return json.decode(json.encode(await extensions[name]!(arguments)))['enabled'] as String;
-  }
-
-
   static void runTests() {
     final StructureErrorTestWidgetInspectorService service = StructureErrorTestWidgetInspectorService();
     WidgetInspectorService.instance = service;
 
-    test('ext.flutter.inspector.structuredErrors reports error to _structuredExceptionHandler on error', () async {
+    test('ext.flutter.inspector.structuredErrors - FlutterError.onError is called', () async {
```
Comment (nt4f04uNd) [inline packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:21]: Removed stuff that was moved into `widget_inspector_test_utils.dart` and changed the test to test the proper behavior

File: packages/flutter/test/widgets/widget_inspector_init_with_structured_error_test.dart [hunk 3]
```diff
@@ -1,61 +0,0 @@
...
-import 'package:flutter/widgets.dart';
-import 'package:flutter_test/flutter_test.dart';
-
-import 'widget_inspector_test_utils.dart';
-
-void main() {
-  StructuredErrorTestService.runTests();
-}
-
-class StructuredErrorTestService extends TestWidgetInspectorService {
```
Comment (nt4f04uNd) [inline packages/flutter/test/widgets/widget_inspector_init_with_structured_error_test.dart:16]: All of this has been moved to `widget_inspector_test_utils.dart` and `widget_inspector_test.dart`, so just removed this file

**Comment by nt4f04uNd** [comment]
See also https://github.com/flutter/website/issues/6164

**Review by kenzieschmoll — COMMENTED** [review]
Does this PR affect whether structured errors are thrown by default? Have you verified that a structured error still shows up in the DevTools logging view when, for example, a RenderFlex Overflow error occurs? Or that a notification shows up in the IDEs when this happens?

**Comment by nt4f04uNd** [comment]
> Does this PR affect whether structured errors are thrown by default?

It disables logs in case `onError` was set to some callback, unless developer calles `presentError` in their custom callback

> Have you verified that a structured error still shows up in the DevTools logging view when, for example, a RenderFlex Overflow error occurs? Or that a notification shows up in the IDEs when this happens?

Same as above

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 4]
```diff
@@ -867,7 +867,8 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
   /// The default behavior is to call [presentError].
   ///
   /// You can set this to your own function to override this default behavior.
-  /// For example, you could report all errors to your server.
+  /// For example, you could report all errors to your server. It's recommended
+  /// to call the [presentError] to be able to see the logs in the console.
```
[the remark this answers is not in the document]
Comment (nt4f04uNd) [reply packages/flutter/lib/src/foundation/assertions.dart:871]: What's the reason to not recommend it?

**Comment by kenzieschmoll** [comment]
> >Does this PR affect whether structured errors are thrown by default?

> It disables logs in case onError was set to some callback, unless developer calles presentError in their custom callback

Ah okay. So unless a user specifies `onError` themselves, the behavior of `onError` using structured errors by default is unchanged, is that correct? And a user can add a call to `presentError` to have both their error handler and the structured errors error handler?

**Comment by nt4f04uNd** [comment]
Correct

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (kenzieschmoll) [reply packages/flutter/lib/src/foundation/assertions.dart:871]: Is there a way we can make presentError be called no matter what if structured errors are supposed to be enabled (default behavior)? Something like:

```
if user specified onError handler
 onError = () {
   presentError();
   onError();
 }
```

[the remark this answers is not in the document]
Comment (nt4f04uNd) [reply packages/flutter/lib/src/foundation/assertions.dart:871]: I've considered that, but.. how do we avoid duplication in case structured errors enabled, then disabled, and then enabled here?https://github.com/flutter/flutter/blob/d2b5e312a2e2f3cfd6dc6ea070cdf7335e16586f/packages/flutter/lib/src/widgets/widget_inspector.dart#L996-L1003

Or what if in onError they already call `presentError`? Or how do we event disabled it then ...

[the remark this answers is not in the document]
Comment (nt4f04uNd) [reply packages/flutter/lib/src/foundation/assertions.dart:871]: And even with that approach, after the errors are enabled on service connection, developer still might set onError to some callback and it will stop working

[the remark this answers is not in the document]
Comment (kenzieschmoll) [reply packages/flutter/lib/src/foundation/assertions.dart:871]: cc @jacob314 if you have any opinion on structured errors

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart [hunk 5]
```diff
@@ -13,82 +10,35 @@ void main() {
...
+      // Regression test for https://github.com/flutter/flutter/issues/41540
+
       final FlutterExceptionHandler? oldHandler = FlutterError.onError;
 
-      bool usingNewHandler = false;
-      // Creates a spy onError. This spy needs to be set before widgets binding
-      // initializes.
+      // Set callback.
+      bool onErrorCalled = false;
       FlutterError.onError = (FlutterErrorDetails details) {
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:25]: add a test case that shows a callback that calls 
presentError()
and verify that the structured error is still sent in that case.
The getEventsDispatched() method you removed can be verified that structured errors are displayed in that case but not in the case where presentError is omitted.

**Comment by jacob314** [comment]
Overall I like this solution a lot. I've added a comment about how the tests for the inspector need to be changed to verify the expected behavior that overriding onError while calling present error causes the errors to be shown but overriding onError without calling presenteError does not.

**Comment by nt4f04uNd** [comment]
Changed the test and the doc according to @goderbauer's review

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart (hunk 5 above)
Comment (nt4f04uNd) [reply packages/flutter/test/widgets/widget_inspector_structure_error_test.dart]: done

**Comment by nt4f04uNd** [comment]
Good catch, added a test for this, PTAL

I bundled all of this into one test, because otherwise I wound need to create another file to isolate the binding instantiation to test the `Flutter.presentError`

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart [hunk 6]
```diff
@@ -2,93 +2,85 @@
...
-        FlutterError.reportError(expectedError);
-
-        // For non-web apps, this validates the new handler did not receive an
-        // error because `FlutterError.onError` was set to
-        // `WidgetInspectorService._structuredExceptionHandler` when service
-        // extensions were initialized. For web apps, the new handler should
-        // have received an error because structured errors are disabled by
-        // default on the web.
-        expect(usingNewHandler, equals(kIsWeb));
+        expect(FlutterError.presentError, equals(oldHandler));
```
Comment (nt4f04uNd) [inline packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:83]: I just noticed that this part of the test doesn't fail on web. Should `isStructuredErrorsEnabled` be used to prevent this?

Comment (goderbauer) [reply packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:83]: /cc @kenzieschmoll Is the comment about this not working on the web still accurate?

**Review by goderbauer — COMMENTED** [review]
LGTM from my side, but @kenzieschmoll or @jacob314 should also LGTM the inspector code.

**Review by goderbauer — COMMENTED** [review]
(This PR likely also needs to be rebased to master to make the checks happy)

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart (hunk 6 above)
Comment (jacob314) [reply packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:83]: It will prevent this but not with the test binding you are using which always returns true.
Here is the relevant line that disables it on the web.
https://github.com/flutter/flutter/blob/975fcc1f2fc6f4dc237363cd0b82e0a3ea6cc14f/packages/flutter/lib/src/widgets/widget_inspector.dart#L970
you could duplicate that logic in the test binding used by this case to reproduce it.

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart [hunk 7]
```diff
@@ -2,93 +2,85 @@
...
+import 'widget_inspector_test_utils.dart';
+
 void main() {
   StructureErrorTestWidgetInspectorService.runTests();
 }
 
-typedef InspectorServiceExtensionCallback = FutureOr<Map<String, Object?>> Function(Map<String, String> parameters);
+class StructureErrorTestWidgetInspectorService extends TestWidgetInspectorService {
+  static void runTests() {
+    final StructureErrorTestWidgetInspectorService service = StructureErrorTestWidgetInspectorService();
```
Comment (jacob314) [inline packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:17]: this test version of the service is always enabling structured errors as far as I can tell regardless of whether you are on web.

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart (hunk 6 above)
Comment (nt4f04uNd) [reply packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:83]: However [this line](https://github.com/flutter/flutter/blob/bd4a376e009dfaf934648c66b19d836fd15dedf3/packages/flutter/test/widgets/widget_inspector_structure_error_test.dart#L67) from above fails on when run on web. Sorry I probably just wasn't clear, what I meant is should the `isStructuredErrorsEnabled` be used [here](https://github.com/flutter/flutter/blob/bd4a376e009dfaf934648c66b19d836fd15dedf3/packages/flutter/lib/src/widgets/widget_inspector.dart#L1000) as well as [here](https://github.com/flutter/flutter/blob/bd4a376e009dfaf934648c66b19d836fd15dedf3/packages/flutter/lib/src/widgets/widget_inspector.dart#L984)?

**Comment by cedvdb** [comment]
I don't think this fix the original issue and the issue is closed so it's not possible to comment there. Could you reopen ?

**Comment by goderbauer** [comment]
@cedvdb Can you open a new issues that describes what's still missing?
