### PR TITLE
Fix SliverMainAxisGroup scrollOffsetCorrection

### LINKED ISSUE #174368: SliverMainAxisGroup does not handle scrollOffsetCorrection
### Steps to reproduce

1. Display a `SliverList` in `SliverMainAxisGroup`.
2. Scroll to middle/end of list.
3. Press an item to unhide elements
4. Scroll up, list breaks, doesn't show all elements

The example issue is similar to [#59819](https://github.com/flutter/flutter/issues/59819) but on `SliverMainAxisGroup`.

### Expected results

The items display is consistent during the scroll.

### Actual results

The scroll position is not consistent.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Sliver Example'), backgroundColor: Colors.blue),
        body: const _MyAnomalyWidget(),
      ),
    ),
  );
}

class _MyAnomalyWidget extends StatefulWidget {
  const _MyAnomalyWidget();

  @override
  State<_MyAnomalyWidget> createState() => __MyAnomalyWidgetState();
}

class __MyAnomalyWidgetState extends State<_MyAnomalyWidget> {
  bool skip = true;

  @override
  Widget build(BuildContext context) {
    Widget buildItem(BuildContext context, int index) {
      return !skip || index.isEven
          ? InkWell(
              onTap: () => setState(() => skip = !skip),
              child: Card(
                child: ListTile(title: Text('item$index', style: const TextStyle(fontSize: 80))),
              ),
            )
          : Container();
    }

    return CustomScrollView(
      slivers: <Widget>[
        SliverMainAxisGroup(
          slivers: <Widget>[
            SliverList(delegate: SliverChildBuilderDelegate(buildItem, childCount: 30)),
          ],
        ),
      ],
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/9f10bcb5-1fad-4296-8c63-0aa50f33bb46

</details>

### Logs

<details open><summary>Logs</summary>

```console
Restarted application in 668ms.
D/EGL_emulation(15514): app_time_stats: avg=726.62ms min=0.77ms max=2903.44ms count=4
D/EGL_emulation(15514): app_time_stats: avg=11344.32ms min=11344.32ms max=11344.32ms count=1
D/EGL_emulation(15514): app_time_stats: avg=7.33ms min=1.01ms max=30.22ms count=58
D/EGL_emulation(15514): app_time_stats: avg=12.83ms min=0.91ms max=28.78ms count=58
D/EGL_emulation(15514): app_time_stats: avg=64.03ms min=9.10ms max=1124.57ms count=24
D/EGL_emulation(15514): app_time_stats: avg=89.59ms min=11.72ms max=1535.21ms count=24
D/EGL_emulation(15514): app_time_stats: avg=16.25ms min=7.17ms max=25.81ms count=61
D/EGL_emulation(15514): app_time_stats: avg=14.22ms min=1.27ms max=32.84ms count=58
D/EGL_emulation(15514): app_time_stats: avg=8.02ms min=0.97ms max=178.13ms count=48
D/EGL_emulation(15514): app_time_stats: avg=45.39ms min=1.08ms max=1236.98ms count=39
D/EGL_emulation(15514): app_time_stats: avg=9.85ms min=0.98ms max=25.00ms count=60
D/EGL_emulation(15514): app_time_stats: avg=2.16ms min=0.89ms max=9.06ms count=61
D/EGL_emulation(15514): app_time_stats: avg=17.63ms min=0.88ms max=544.41ms count=48
D/EGL_emulation(15514): app_time_stats: avg=21.86ms min=10.32ms max=119.29ms count=47
D/EGL_emulation(15514): app_time_stats: avg=163.83ms min=17.87ms max=882.79ms count=7
D/EGL_emulation(15514): app_time_stats: avg=69.51ms min=7.27ms max=1348.90ms count=25
D/EGL_emulation(15514): app_time_stats: avg=16.26ms min=7.27ms max=25.79ms count=61
D/EGL_emulation(15514): app_time_stats: avg=15.92ms min=9.89ms max=22.39ms count=61
D/EGL_emulation(15514): app_time_stats: avg=16.64ms min=4.30ms max=36.11ms count=58
D/EGL_emulation(15514): app_time_stats: avg=35.44ms min=6.49ms max=615.66ms count=33
D/EGL_emulation(15514): app_time_stats: avg=13.20ms min=1.13ms max=51.64ms count=56
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.33.0-1.0.pre-1252, on macOS 15.6 24G84 darwin-arm64, locale fr-FR) [2,3s]
    • Flutter version 3.33.0-1.0.pre-1252 on channel master at /Users/emmanuel_lefebvre/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc28781423 (3 weeks ago), 2025-08-03 10:36:42 -0400
    • Engine revision fc28781423
    • Dart version 3.10.0 (build 3.10.0-59.0.dev)
    • DevTools version 2.48.0
    • Pub download mirror https://artifact.socrate.vsct.fr/artifactory/api/pub/all-pub
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1 689ms]
    • Android SDK at /Users/emmanuel_lefebvre/Library/Android/sdk
    • Emulator version 35.5.10.0 (build_id 13402964) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [1 405ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [6,8s]
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 15.6 24G84 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 139.0.7258.139
    ! Error: Browsing on the local area network for iPhone XS. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [266ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by manu-sncf**
Fixes : [#174368](https://github.com/flutter/flutter/issues/174368)

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by justinmc** [comment]
@Piinks Tagged you for review since this is about Slivers. I also plan to take a look.

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 1]
```diff
@@ -1197,6 +1197,103 @@ void main() {
...
+                ),
+              ],
+            ),
+          ),
+        ),
+      );
+      // Only even items 0~12 are on the screen.
+      expect(find.text('item0'), findsOneWidget);
+      expect(find.text('item12'), findsOneWidget);
+      expect(find.text('item14'), findsNothing);
```
Comment (justinmc) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: Nit: You could loop through 0-12 if you think it would be valuable to check everything.

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 2]
```diff
@@ -1197,6 +1197,103 @@ void main() {
...
+      await tester.pump();
+      await tester.drag(find.byType(CustomScrollView), const Offset(0.0, 250.0));
+      await tester.pump();
+
+      // Only items 0~6 are on the screen.
+      expect(find.text('item0'), findsOneWidget);
+      expect(find.text('item6'), findsOneWidget);
+      expect(find.text('item7'), findsNothing);
+    },
+  );
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: That's not a bad point. Are the two pumpWidgets sections of the test self contained too? Maybe you could split it into two separate tests.

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 3]
```diff
@@ -1197,6 +1197,103 @@ void main() {
       expect(tester.getBottomRight(find.byKey(key)), offset - const Offset(0.0, 20.0));
     },
   );
+
+  testWidgets(
+    'With SliverList can handle inaccurate scroll offset due to changes in children list',
```
Comment (justinmc) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart:1335]: I confirmed that this test fails on master.

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 4]
```diff
@@ -325,7 +325,18 @@ class RenderSliverMainAxisGroup extends RenderSliver
         ),
         parentUsesSize: true,
       );
+
       final SliverGeometry childLayoutGeometry = child.geometry!;
+
+      if (childLayoutGeometry case SliverGeometry(
+        :final double scrollOffsetCorrection,
+      ) when scrollOffsetCorrection != 0) {
+        geometry = SliverGeometry(scrollOffsetCorrection: scrollOffsetCorrection);
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/sliver_group.dart:334]: I'll defer to @Piinks on whether this is the right way to solve this.

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 1 above)
Comment (manu-sncf) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: Hi @justinmc, thanks for your review. FYI, this test is a duplicate of "slivers_test.dart" -> "SliverList can handle inaccurate scroll offset due to changes in children list".

I modified the test with a loop, as you suggested.

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (manu-sncf) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: Both calls of `tester.pumpWidget` in same test are necessary to update the widgets tree with `skip=true/false` that trigger a SliverGeometry.scrollOffsetCorrection and thus reproduce the issue.

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 5]
```diff
@@ -325,7 +325,18 @@ class RenderSliverMainAxisGroup extends RenderSliver
         ),
         parentUsesSize: true,
       );
+
       final SliverGeometry childLayoutGeometry = child.geometry!;
+
+      if (childLayoutGeometry case SliverGeometry(
+        :final double scrollOffsetCorrection,
+      ) when scrollOffsetCorrection != 0) {
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_group.dart]: Can you write this differently? We have not adopted this pattern in the framework because it can be hard for readability in some cases.

**Review by Piinks — COMMENTED** [review]
@yiiim may also be interested in this, they have made a lot of changes here recently.

**Review by yiiim — APPROVED** [review]
LGTM for the Sliver changes. For tests and formatting issues, I will follow the guidance of @justinmc  and @Piinks

File: packages/flutter/lib/src/rendering/sliver_group.dart (hunk 5 above)
Comment (manu-sncf) [reply packages/flutter/lib/src/rendering/sliver_group.dart]: Done !

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 1 above)
Comment (manu-sncf) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: Is it ok for you @justinmc  ?

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (manu-sncf) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart]: @justinmc, , can I resolve this ? As mentioned before, both calls to `tester.pumpWidget` are necessary in this test. The second call uses the skip variable to modify the `SliverList` state, which is precisely what triggers the `SliverGeometry.scrollOffsetCorrection` we need to verify.

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for the contribution!

**Comment by Piinks** [comment]
There are some merge conflicts that need to be resolved here, and then this should be good to go!
