### PR TITLE
modify toggle mode style with DatePickerTheme

### LINKED ISSUE #160591: [DatePickerThemeData] doesn't allor
### Steps to reproduce

1. Create a Flutter app with a DatePicker widget (the fastest way is to copy-paste the code from the docs [https://api.flutter.dev/flutter/material/showDatePicker.html])
2. Style your DatePicker using DatePickerThemeData in the MaterialApp theme
3. There's no way to change the sub-header color

### Expected results

I should be able to change the sub-header color from a DatePickerThemeData attribute.

### Actual results

The only way to change the sub-header attribute is from the colorScheme section, specifying the desired color in the onSurface parameter (in the example, set to orange).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const DatePickerApp());

class DatePickerApp extends StatelessWidget {
  const DatePickerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      restorationScopeId: 'app',
      home: DatePickerExample(restorationId: 'main'),
      theme: ThemeData(
        colorScheme: ColorScheme.light(onSurface: Colors.orange),
        datePickerTheme: DatePickerThemeData(
          backgroundColor: Colors.white,
          // Add button style to set text color to black
          cancelButtonStyle: ButtonStyle(
            foregroundColor: WidgetStatePropertyAll(Colors.black),
          ),
          confirmButtonStyle: ButtonStyle(
            backgroundColor: WidgetStatePropertyAll(Colors.blue),
            foregroundColor: WidgetStatePropertyAll(Colors.white),
          ),
          dayBackgroundColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return Colors.blue;
            }
            return Colors.transparent;
          }),
          dayForegroundColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return Colors.white;
            }
            return Colors.black;
          }),
          headerBackgroundColor: Colors.blue,
          headerForegroundColor: Colors.white,
          inputDecorationTheme: InputDecorationTheme(
            labelStyle: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontWeight: FontWeight.w500,
            ),
            isDense: true,
            floatingLabelBehavior: FloatingLabelBehavior.auto,
            border: OutlineInputBorder(),
          ),
          todayBackgroundColor: WidgetStateProperty.resolveWith(
            (states) {
              if (states.contains(WidgetState.selected)) {
                return Colors.blue;
              }
              return Colors.transparent;
            },
          ),
          todayForegroundColor: WidgetStateProperty.resolveWith(
            (states) {
              if (states.contains(WidgetState.selected)) {
                return Colors.white;
              }
              return Colors.blue;
            },
          ),

          weekdayStyle: const TextStyle(color: Colors.black),
          yearBackgroundColor: WidgetStateProperty.resolveWith(
            (states) {
              if (states.contains(WidgetState.selected)) {
                return Colors.blue;
              }
              return Colors.transparent;
            },
          ),
          yearForegroundColor: WidgetStateProperty.resolveWith(
            (states) {
              if (states.contains(WidgetState.selected)) {
                return Colors.white;
              }
              return Colors.black;
            },
          ),
          yearOverlayColor: WidgetStatePropertyAll(Colors.blue),
        ),
      ),
    );
  }
}

class DatePickerExample extends StatefulWidget {
  const DatePickerExample({super.key, this.restorationId});

  final String? restorationId;

  @override
  State<DatePickerExample> createState() => _DatePickerExampleState();
}

/// RestorationProperty objects can be used because of RestorationMixin.
class _DatePickerExampleState extends State<DatePickerExample>
    with RestorationMixin {
  // In this example, the restoration ID for the mixin is passed in through
  // the [StatefulWidget]'s constructor.
  @override
  String? get restorationId => widget.restorationId;

  final RestorableDateTime _selectedDate =
      RestorableDateTime(DateTime(2021, 7, 25));
  late final RestorableRouteFuture<DateTime?> _restorableDatePickerRouteFuture =
      RestorableRouteFuture<DateTime?>(
    onComplete: _selectDate,
    onPresent: (NavigatorState navigator, Object? arguments) {
      return navigator.restorablePush(
        _datePickerRoute,
        arguments: _selectedDate.value.millisecondsSinceEpoch,
      );
    },
  );

  @pragma('vm:entry-point')
  static Route<DateTime> _datePickerRoute(
    BuildContext context,
    Object? arguments,
  ) {
    return DialogRoute<DateTime>(
      context: context,
      builder: (BuildContext context) {
        return DatePickerDialog(
          restorationId: 'date_picker_dialog',
          initialEntryMode: DatePickerEntryMode.calendarOnly,
          initialDate: DateTime.fromMillisecondsSinceEpoch(arguments! as int),
          firstDate: DateTime(2021),
          lastDate: DateTime(2022),
        );
      },
    );
  }

  @override
  void restoreState(RestorationBucket? oldBucket, bool initialRestore) {
    registerForRestoration(_selectedDate, 'selected_date');
    registerForRestoration(
        _restorableDatePickerRouteFuture, 'date_picker_route_future');
  }

  void _selectDate(DateTime? newSelectedDate) {
    if (newSelectedDate != null) {
      setState(() {
        _selectedDate.value = newSelectedDate;
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(
              'Selected: ${_selectedDate.value.day}/${_selectedDate.value.month}/${_selectedDate.value.year}'),
        ));
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlinedButton(
          onPressed: () {
            _restorableDatePickerRouteFuture.present();
          },
          child: const Text('Open Date Picker'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by MaironLucas**
- Add properties to DatePickerThemeData:
    - `toggleModeStyle` allow customization on _DatePickerModeToggleButton TextStyle;
    - `toggleModeForegroundColor` allow changing the color of both button and Icon with consistency;
- Compatible with existing code by the use of defaults;
- Adjust test to cover new properties

How to customize toggle mode style before:

```dart
  showDatePicker(
    context: context,
    firstDate: DateTime(2025),
    lastDate: DateTime(2026),
    builder:
        (context, child) => Theme(
          data: ThemeData.light().copyWith(
            textTheme: TextTheme(titleSmall: TextStyle(fontSize: 16)),
            datePickerTheme: DatePickerThemeData(
              dayStyle: TextStyle(fontSize: 12),
            ),
          ),
          child: child!,
        ),
  );
```

Now:

```dart
  showDatePicker(
    context: context,
    firstDate: DateTime(2025),
    lastDate: DateTime(2026),
    builder:
        (context, child) => DatePickerTheme(
          data: DatePickerThemeData(
            toggleModeStyle: TextStyle(fontSize: 16),
            dayStyle: TextStyle(fontSize: 12),
          ),
          child: child!,
        ),
  );
```

Ref #163866
Ref #160591

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by MaironLucas** [comment]
I implemented this new feature before seeing that issue #160591 requested a similar feature. That issue already has a linked PR (#161458), but that PR doesn't seem to have received updates since January 24, so I think it's fair to keep my PR as a valid implementation for both issues. 
Also, I took into account the comments and reviews of that PR.

File: packages/flutter/lib/src/material/date_picker_theme.dart [hunk 1]
```diff
@@ -360,6 +362,17 @@ class DatePickerThemeData with Diagnosticable {
   /// picker. It defaults to the ambient locale provided by [Localizations].
   final Locale? locale;
 
+  /// Overrides the default text style used for the text of toggle mode button
+  ///
+  /// The [TextStyle.color] of [toggleModeStyle] is not used, [toggleModeForegroundColor]
+  /// is used instead.
+  final TextStyle? toggleModeStyle;
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/date_picker_theme.dart:369]: Do you think if `toggleButtonTextStyle` would be more straightforward to understand? :)

File: packages/flutter/lib/src/material/date_picker_theme.dart [hunk 2]
```diff
@@ -360,6 +362,17 @@ class DatePickerThemeData with Diagnosticable {
...
+
+  /// Overrides the default color used for text labels and icons of toggle mode button.
+  ///
+  /// This is used instead of the [TextStyle.color] property of [toggleModeStyle].
+  final Color? toggleModeForegroundColor;
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/date_picker_theme.dart:374]: To fix https://github.com/flutter/flutter/issues/160591, I think we'd better also apply this color to the month pick button. As for naming, I think `subHeaderForegroundColor` would be more straightforward to understand.

**Review by QuncCccccc — COMMENTED** [review]
Thank you for your contribution! Overall this looks good to me! Just left some comments below.

File: packages/flutter/lib/src/material/date_picker_theme.dart (hunk 1 above)
Comment (MaironLucas) [reply packages/flutter/lib/src/material/date_picker_theme.dart]: Done

File: packages/flutter/lib/src/material/date_picker_theme.dart (hunk 2 above)
Comment (MaironLucas) [reply packages/flutter/lib/src/material/date_picker_theme.dart]: Done

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 3]
```diff
@@ -458,12 +459,12 @@ class _DatePickerModeToggleButtonState extends State<_DatePickerModeToggleButton
                             child: Text(
                               widget.title,
                               overflow: TextOverflow.ellipsis,
-                              style: textTheme.titleSmall?.copyWith(color: controlColor),
+                              style: buttonTextStyle?.apply(color: toggleModeForegroundColor),
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:462]: If we provide a `toggleButtonTextStyle ` with a custom text color in date picker theme, but **don't** provide a `subHeaderForegroundColor` in the date picker theme, this change will cause that the customized text color is not respected, and the text color always defaults to the default `subHeaderForegroundColor `.

For the text color here, ideally, I think we want to firstly check whether theme's toggleButtonTextStyle's color is empty, if not empty, we respect the color value; but if empty, then check whether theme's subheaderForegroundColor is empty, if not empty, text color should respect it; if empty, we should go to defaults.toggleButtonTextStyle, if still empty, we should check `defaults.subHeaderForegroundColor`. Does this make sense?

**Review by QuncCccccc — COMMENTED** [review]
Thanks for the update! Left some comments below. Please let me know if there's any questions:)

File: dev/tools/gen_defaults/lib/date_picker_template.dart [hunk 4]
```diff
@@ -62,6 +62,14 @@ class _${blockName}DefaultsM3 extends DatePickerThemeData {
   @override
   Color? get backgroundColor => ${componentColor("md.comp.date-picker.modal.container")};
 
+  @override
+  Color? get subHeaderForegroundColor => ${componentColor("md.comp.date-picker.modal.sub.header.foreground")}.withOpacity(0.60);
```
[the remark this answers is not in the document]
Comment (MaironLucas) [reply dev/tools/gen_defaults/lib/date_picker_template.dart:66]: Okay, that makes sense. This part was a bit confusing to me. So I should use something like `md.comp.date-picker.modal.weekdays.label-text` for `subHeaderForegroundColor` and `md.comp.date-picker.modal.range-selection.month.subhead` for `toggleButtonTextStyle`? Thats it?

File: packages/flutter/lib/src/material/calendar_date_picker.dart (hunk 3 above)
Comment (MaironLucas) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:462]: Yeahh, it makes sense. I'm gonna implement it!

File: dev/tools/gen_defaults/data/date_picker_modal.json [hunk 5]
```diff
@@ -72,5 +71,7 @@
   "md.comp.date-picker.modal.year-selection.year.unselected.focus.state-layer.color": "onSurfaceVariant",
   "md.comp.date-picker.modal.year-selection.year.unselected.hover.state-layer.color": "onSurfaceVariant",
   "md.comp.date-picker.modal.year-selection.year.unselected.label-text.color": "onSurfaceVariant",
-  "md.comp.date-picker.modal.year-selection.year.unselected.pressed.state-layer.color": "onSurfaceVariant"
+  "md.comp.date-picker.modal.year-selection.year.unselected.pressed.state-layer.color": "onSurfaceVariant",
```
[the remark this answers is not in the document]
Comment (MaironLucas) [reply dev/tools/gen_defaults/data/date_picker_modal.json]: Done!

File: dev/tools/gen_defaults/lib/date_picker_template.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (MaironLucas) [reply dev/tools/gen_defaults/lib/date_picker_template.dart]: Done!

File: packages/flutter/lib/src/material/calendar_date_picker.dart (hunk 3 above)
Comment (MaironLucas) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: Done!  I think the check on defaults.subHeaderForegroundColor is redundant because defaults.toggleButtonTextStyle already gets it.

File: dev/tools/gen_defaults/lib/date_picker_template.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (QuncCccccc) [reply dev/tools/gen_defaults/lib/date_picker_template.dart]: Sorry for the late reply. Yes, these tokens are exported from google internal token generator, we should just pick tokens instead of creating new ones ourselves:)

**Review by QuncCccccc — COMMENTED** [review]
This looks great to me! Can we add one more test to verify the `datePickerTheme.toggleButtonTextStyle` can override `datePickerTheme.subHeaderForeground` when they both have some custom color values:)

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 6]
```diff
@@ -450,9 +448,16 @@ class _DatePickerModeToggleButtonState extends State<_DatePickerModeToggleButton
...
   @override
   Widget build(BuildContext context) {
-    final ColorScheme colorScheme = Theme.of(context).colorScheme;
-    final TextTheme textTheme = Theme.of(context).textTheme;
-    final Color controlColor = colorScheme.onSurface.withOpacity(0.60);
+    final DatePickerThemeData datePickerTheme = DatePickerTheme.of(context);
+    final DatePickerThemeData defaults = DatePickerTheme.defaults(context);
+    final TextStyle? buttonTextStyle =
+        datePickerTheme.toggleButtonTextStyle ?? defaults.toggleButtonTextStyle;
+    final Color? toggleModeForegroundColor =
```
[the remark this answers is not in the document]
Comment (MaironLucas) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:455]: @QuncCccccc About the test, I think I don't know exactly how to make it. Should I write a new test at `date_picker_theme_test` or edit one that already exists to verify this override?

[the remark this answers is not in the document]
Comment (MaironLucas) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: Hi, @QuncCccccc. How is it going? I pushed the commit with two tests, verifying if the color of toggleButtonTextStyle is respected over subHeaderForegroundColor and also a test verifying if subHeaderForeground is used when toggleButtonTextStyle.color is not defined.

[the remark this answers is not in the document]
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: The tests look good to me! Could you help fix the conflict and the failures, then we are good to go!

[the remark this answers is not in the document]
Comment (MaironLucas) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: Hi, nice!!
Well, the conflict is fixed. But about the failures, I am unsure of what to do to fix them. Could you help me? @QuncCccccc

File: packages/flutter/lib/src/material/date_picker_theme.dart [hunk 7]
```diff
@@ -373,6 +375,16 @@ class DatePickerThemeData with Diagnosticable {
   /// picker. It defaults to the ambient locale provided by [Localizations].
   final Locale? locale;
 
+  /// Overrides the default text style used for the text of toggle mode button
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/date_picker_theme.dart:378]: nit: 
```suggestion
  /// Overrides the default text style used for the text of toggle mode button.
```

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thank you for your contribution!

File: packages/flutter/test/material/date_picker_theme_test.dart [hunk 8]
```diff
@@ -591,6 +607,13 @@ void main() {
     );
     expect(day24Shape.side.width, datePickerTheme.todayBorder?.width);
 
+    // Test the toggle mode button
```
Comment (justinmc) [inline packages/flutter/test/material/date_picker_theme_test.dart:610]: Nit: Period at the end.

**Review by justinmc — APPROVED** [review]
LGTM :+1:. Thanks for jumping in to add this!
