### PR TITLE
Fix a `DataTable` crash and improve some docs

### LINKED ISSUE #100633: Flutter DataTable sample overflows if column heading is made a little longer
## Steps to Reproduce

1. Open DataTable documentation and look at sample [https://api.flutter.dev/flutter/material/DataTable-class.html](https://api.flutter.dev/flutter/material/DataTable-class.html)
2. Change 'Age' column on row 37 to 'Age longer'
3. Reduce browser width to see overflow on column header

**Expected results:**
With column headings shorter than row content, there is no overflow error no matter how small you squeeze the table.  Expect no overflow with longer headings too.

**Actual results:**
Overflow error with longer headings

This happens on the current Dart/Flutter versions deployed on the api.flutter.dev site.

Here are some videos illustrating the problem.  The first video shows the sample unmodified:

https://user-images.githubusercontent.com/4357286/159750385-c905ebab-812e-4d4a-b3c6-38519d2feaa8.mov

The second video shows the overflow when you change 'Age' to 'Age longer'.

https://user-images.githubusercontent.com/4357286/159750550-4e374c88-b183-498b-9ecc-55bbd25ec9b8.mov

### LINKED ISSUE #100952: `DataTable` with borders crashes when paint in a narrow space
### Steps
1, Run the code on the desktop platform.
2, Resize the size of the window to be very small that can only show one colum.
3, Framework crashes appear.

### Code
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DataTable(
      border: TableBorder.all(),
      columns: const <DataColumn>[
        DataColumn(
          label: Text(
            'Name',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Age',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Role',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
      ],
      rows: const <DataRow>[
        DataRow(
          cells: <DataCell>[
            DataCell(Text('Sarah')),
            DataCell(Text('19')),
            DataCell(Text('Student')),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(Text('Janine')),
            DataCell(Text('43')),
            DataCell(Text('Professor')),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(Text('William')),
            DataCell(Text('27')),
            DataCell(Text('Associate Professor')),
          ],
        ),
      ],
    );
  }
}
```

### Logs
```dart
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/rendering/table_border.dart': Failed assertion: line 220 pos 12: 'columns.isEmpty || (columns.first >= 0.0 && columns.last <= rect.width)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  DataTable DataTable:file:///D:/My%20Documents/Desktop/untitled/lib/main.dart:27:12
When the exception was thrown, this was the stack: 
#2      TableBorder.paint (package:flutter/src/rendering/table_border.dart:220:12)
#3      RenderTable.paint (package:flutter/src/rendering/table.dart:1222:15)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#7      _RenderInkFeatures.paint (package:flutter/src/material/material.dart:595:11)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:608:11)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#14     RenderClipPath.paint (package:flutter/src/rendering/proxy_box.dart:1725:17)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#17     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#18     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#22     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:595:11)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#26     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#27     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#35     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#36     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#37     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#43     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#47     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#48     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#49     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#53     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#57     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#58     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#59     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#62     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7510:15)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#66     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#70     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#71     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#72     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#75     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#76     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#80     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#81     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#82     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#85     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7510:15)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#90     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#91     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#92     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#100    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#101    RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3475:11)
#102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#104    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#107    _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:786:15)
#108    _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:804:7)
#109    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#110    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#111    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#112    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#113    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#114    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#115    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#116    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#117    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#118    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#119    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#120    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#121    RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:608:11)
#122    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#124    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#126    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#127    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#128    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#130    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#131    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#132    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#133    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#134    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#135    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#136    RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#137    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#138    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#139    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#140    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#141    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:503:19)
#142    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#143    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:367:5)
#144    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#145    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#146    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#150    _invoke (dart:ui/hooks.dart:151:10)
#151    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#152    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderTable#cbe1e relayoutBoundary=up4
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=177.0, 0.0<=h<=316.0)
...  size: Size(177.0, 200.0)
...  border: TableBorder(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderRadius.zero)
...  specified column widths: {0: IntrinsicColumnWidth(flex: null), 1: IntrinsicColumnWidth(flex: null), 2: IntrinsicColumnWidth(flex: null)}
...  default column width: FlexColumnWidth(1.0)
...  table size: 3×4
...  column offsets: 0.0, 98.0, 179.0
...  row offsets: 0.0, 56.0, 104.0, 152.0, 200.0
RenderObject: RenderTable#cbe1e relayoutBoundary=up4
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=177.0, 0.0<=h<=316.0)
  size: Size(177.0, 200.0)
  border: TableBorder(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderSide(Color(0xff000000), 1.0, BorderStyle.solid), BorderRadius.zero)
  specified column widths: {0: IntrinsicColumnWidth(flex: null), 1: IntrinsicColumnWidth(flex: null), 2: IntrinsicColumnWidth(flex: null)}
  default column width: FlexColumnWidth(1.0)
  table size: 3×4
  column offsets: 0.0, 98.0, 179.0
  row offsets: 0.0, 56.0, 104.0, 152.0, 200.0
...  child (0, 0): RenderSemanticsAnnotations#4ee33 relayoutBoundary=up5
...    parentData: offset=Offset(0.0, 0.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...    size: Size(98.0, 56.0)
...    child: RenderMouseRegion#7f1e9 relayoutBoundary=up6
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...      size: Size(98.0, 56.0)
...      behavior: opaque
...      listeners: enter, exit
...      cursor: SystemMouseCursor(basic)
...      child: RenderSemanticsAnnotations#95d91 relayoutBoundary=up7
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...        size: Size(98.0, 56.0)
...        child: RenderPointerListener#1ad8c relayoutBoundary=up8
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...          size: Size(98.0, 56.0)
...          behavior: opaque
...          listeners: down
...  child (1, 0): RenderSemanticsAnnotations#e47c7 relayoutBoundary=up5
...    parentData: offset=Offset(98.0, 0.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...    size: Size(81.0, 56.0)
...    child: RenderMouseRegion#82982 relayoutBoundary=up6
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...      size: Size(81.0, 56.0)
...      behavior: opaque
...      listeners: enter, exit
...      cursor: SystemMouseCursor(basic)
...      child: RenderSemanticsAnnotations#51f77 relayoutBoundary=up7
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...        size: Size(81.0, 56.0)
...        child: RenderPointerListener#480f4 relayoutBoundary=up8
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...          size: Size(81.0, 56.0)
...          behavior: opaque
...          listeners: down
...  child (2, 0): RenderSemanticsAnnotations#1def6 relayoutBoundary=up5
...    parentData: offset=Offset(179.0, 0.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...    size: Size(111.0, 56.0)
...    child: RenderMouseRegion#bbe3b relayoutBoundary=up6
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...      size: Size(111.0, 56.0)
...      behavior: opaque
...      listeners: enter, exit
...      cursor: SystemMouseCursor(basic)
...      child: RenderSemanticsAnnotations#d65fe relayoutBoundary=up7
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...        size: Size(111.0, 56.0)
...        child: RenderPointerListener#21673 relayoutBoundary=up8
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...          size: Size(111.0, 56.0)
...          behavior: opaque
...          listeners: down
...  child (0, 1): RenderConstrainedBox#41658 relayoutBoundary=up5
...    parentData: offset=Offset(0.0, 56.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...    size: Size(98.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#243b3
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=98.0, h=48.0)
...      size: Size(98.0, 48.0)
...      padding: EdgeInsetsDirectional(24.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#57182
...        parentData: offset=Offset(24.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=46.0, h=48.0)
...        size: Size(46.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#4a255 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=46.0, 0.0<=h<=48.0)
...          size: Size(35.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (1, 1): RenderConstrainedBox#cee78 relayoutBoundary=up5
...    parentData: offset=Offset(98.0, 56.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...    size: Size(81.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#e5e37
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=81.0, h=48.0)
...      size: Size(81.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#6e5ce
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=25.0, h=48.0)
...        size: Size(25.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#5125f relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=25.0, 0.0<=h<=48.0)
...          size: Size(16.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (2, 1): RenderConstrainedBox#eb3c3 relayoutBoundary=up5
...    parentData: offset=Offset(179.0, 56.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...    size: Size(111.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#3bdc7
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=111.0, h=48.0)
...      size: Size(111.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 24.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#9535c
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=59.0, h=48.0)
...        size: Size(59.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#82222 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=59.0, 0.0<=h<=48.0)
...          size: Size(48.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (0, 2): RenderConstrainedBox#28708 relayoutBoundary=up5
...    parentData: offset=Offset(0.0, 104.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...    size: Size(98.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#f8987
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=98.0, h=48.0)
...      size: Size(98.0, 48.0)
...      padding: EdgeInsetsDirectional(24.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#1c751
...        parentData: offset=Offset(24.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=46.0, h=48.0)
...        size: Size(46.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#202f0 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=46.0, 0.0<=h<=48.0)
...          size: Size(39.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (1, 2): RenderConstrainedBox#5f12d relayoutBoundary=up5
...    parentData: offset=Offset(98.0, 104.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...    size: Size(81.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#e5938
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=81.0, h=48.0)
...      size: Size(81.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#af62b
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=25.0, h=48.0)
...        size: Size(25.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#5a41d relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=25.0, 0.0<=h<=48.0)
...          size: Size(16.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (2, 2): RenderConstrainedBox#cc8f5 relayoutBoundary=up5
...    parentData: offset=Offset(179.0, 104.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...    size: Size(111.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#23627
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=111.0, h=48.0)
...      size: Size(111.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 24.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#254dc
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=59.0, h=48.0)
...        size: Size(59.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#95417 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=59.0, 0.0<=h<=48.0)
...          size: Size(58.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (0, 3): RenderConstrainedBox#a2f0c relayoutBoundary=up5
...    parentData: offset=Offset(0.0, 152.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=98.0, 0.0<=h<=Infinity)
...    size: Size(98.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#16c0a
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=98.0, h=48.0)
...      size: Size(98.0, 48.0)
...      padding: EdgeInsetsDirectional(24.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#49204
...        parentData: offset=Offset(24.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=46.0, h=48.0)
...        size: Size(46.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#95efd relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=46.0, 0.0<=h<=48.0)
...          size: Size(46.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (1, 3): RenderConstrainedBox#d90e5 relayoutBoundary=up5
...    parentData: offset=Offset(98.0, 152.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=81.0, 0.0<=h<=Infinity)
...    size: Size(81.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#484ae
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=81.0, h=48.0)
...      size: Size(81.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 28.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#3f911
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=25.0, h=48.0)
...        size: Size(25.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#b2b29 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 14.5) (can use size)
...          constraints: BoxConstraints(0.0<=w<=25.0, 0.0<=h<=48.0)
...          size: Size(16.0, 19.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
...  child (2, 3): RenderConstrainedBox#0c897 relayoutBoundary=up5
...    parentData: offset=Offset(179.0, 152.0); default vertical alignment (can use size)
...    constraints: BoxConstraints(w=111.0, 0.0<=h<=Infinity)
...    size: Size(111.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=48.0)
...    child: RenderPadding#3934e
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=111.0, h=48.0)
...      size: Size(111.0, 48.0)
...      padding: EdgeInsetsDirectional(28.0, 0.0, 24.0, 0.0)
...      textDirection: ltr
...      child: RenderPositionedBox#4b35f
...        parentData: offset=Offset(28.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=59.0, h=48.0)
...        size: Size(59.0, 48.0)
...        alignment: AlignmentDirectional.centerStart
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderParagraph#09db4 relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 5.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=59.0, 0.0<=h<=48.0)
...          size: Size(59.0, 38.0)
...          textAlign: start
...          textDirection: ltr
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: en_US
...          maxLines: unlimited
====================================================================================================
```

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/100952
Fixes https://github.com/flutter/flutter/issues/100633

### CODE REVIEW

File: packages/flutter/lib/src/material/data_table.dart [hunk 1]
```diff
@@ -47,9 +47,14 @@ class DataColumn {
...
   /// some text.
   ///
-  /// By default, this widget will only occupy the minimal space. If you want
-  /// it to take the entire remaining space, e.g. when you want to use [Center],
-  /// you can wrap it with an [Expanded].
+  /// This widget and the sort indicator (if visible) will wrap with a [Row],
+  /// by default, this widget will only occupy minimal space. It is
+  /// recommended to wrap this with an [Expanded] or [Flexible] to control how
+  /// it flexes. Otherwise, an exception will occur when the the available space
+  /// is insufficient.
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/data_table.dart:54]: fixes #100633

**Comment by xu-baolin** [comment]
@dkwingsmt Hi, would you like take a look at this patch : )

**Comment by dkwingsmt** [comment]
(I'm sorry for failing to notice this!)
Ok the code looks good, and the doc change is awesome. But I'm wondering, does it feel the developer will _always_ want to wrap it with an `Extended`? Should we just make it extended by default?

File: packages/flutter/lib/src/material/data_table.dart [hunk 2]
```diff
@@ -47,9 +47,14 @@ class DataColumn {
   /// [Icon] (typically using size 18), or a [Row] with an icon and
   /// some text.
   ///
-  /// By default, this widget will only occupy the minimal space. If you want
-  /// it to take the entire remaining space, e.g. when you want to use [Center],
-  /// you can wrap it with an [Expanded].
+  /// This widget and the sort indicator (if visible) will wrap with a [Row],
+  /// by default, this widget will only occupy minimal space. It is
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/data_table.dart:51]: The first sentence doesn't make much sense. Depending on what you mean, maybe

> This widget and the sort indicator are placed within a [Row], and by default, this widget will only occupy minimal space.

File: packages/flutter/lib/src/material/data_table.dart [hunk 3]
```diff
@@ -47,9 +47,14 @@ class DataColumn {
...
+  /// recommended to wrap this with an [Expanded] or [Flexible] to control how
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/data_table.dart:52]: > It is recommended to place the label content in a [Expanded] or [Flexible] to control how the content flexes.

File: packages/flutter/lib/src/material/data_table.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/data_table.dart:51]: As you have said [here](https://github.com/flutter/flutter/pull/51667#discussion_r391898431), this may break something.
In addition, folks may already wrap it under `Expanded`, and redundant `Expanded` will throw.

File: packages/flutter/lib/src/rendering/table.dart [hunk 4]
```diff
@@ -1050,26 +1051,26 @@ class RenderTable extends RenderBox {
     if (rows * columns == 0) {
       // TODO(ianh): if columns is zero, this should be zero width
       // TODO(ianh): if columns is not zero, this should be based on the column width specifications
+      _tableWidth = 0.0;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/rendering/table.dart:1054]: Does this resolve the TODOs?

**Comment by xu-baolin** [comment]
> (I'm sorry for failing to notice this!) Ok the code looks good, and the doc change is awesome. But I'm wondering, does it feel the developer will _always_ want to wrap it with an `Expanded`? Should we just make it extended by default?

As you have said [here](https://github.com/flutter/flutter/pull/51667#discussion_r391898431), this may break something.
In addition, folks may already wrap it under `Expanded`, and redundant `Expanded` will throw.

File: packages/flutter/lib/src/material/data_table.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/data_table.dart:51]: It's astonishing how little I remember having said that at all.

File: packages/flutter/lib/src/rendering/table.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/rendering/table.dart:1054]: I am not quite understood what the todos mean, but I think maybe they can be removed.

File: packages/flutter/lib/src/material/data_table.dart [hunk 5]
```diff
@@ -47,11 +47,11 @@ class DataColumn {
...
-  /// This widget and the sort indicator (if visible) will wrap with a [Row],
-  /// by default, this widget will only occupy minimal space. It is
-  /// recommended to wrap this with an [Expanded] or [Flexible] to control how
-  /// it flexes. Otherwise, an exception will occur when the the available space
-  /// is insufficient.
+  /// The [label] is placed within a [Row] along with the
+  /// sort indicator (if applicable). By default, [label] only occupy minimal
+  /// space. It is recommended to place the label content in an [Expanded] or
+  /// [Flexible] as [label] to control how the content flexes. Otherwise,
+  /// an exception will occur when the the available space is insufficient.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/data_table.dart:54]:
```suggestion
  /// an exception will occur when the available space is insufficient.
```

**Review by dkwingsmt — APPROVED** [review]
LGTM except for nit
