### PR TITLE
Fix: Range slider show overlay for both thumbs on hovering one

### LINKED ISSUE #165281: `RangeSlider` shows an overlay for both thumbs when hovering over only one of them
### Steps to reproduce

1. Before clicking anything, try hovering over one of the thumbs and then the other.
2. Grab and let go of one of the thumbs and then repeat the experiment from step 1.

### Expected results

The overlay should only appear behind the thumb over which the mouse is currently hovering.

### Actual results

An overlay is displayed for both thumbs, even though the mouse is hovering above only one of them.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [RangeSlider].

void main() => runApp(const RangeSliderExampleApp());

class RangeSliderExampleApp extends StatelessWidget {
  const RangeSliderExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('RangeSlider Sample')),
        body: const RangeSliderExample(),
      ),
    );
  }
}

class RangeSliderExample extends StatefulWidget {
  const RangeSliderExample({super.key});

  @override
  State<RangeSliderExample> createState() => _RangeSliderExampleState();
}

class _RangeSliderExampleState extends State<RangeSliderExample> {
  RangeValues _currentRangeValues = const RangeValues(40, 80);

  @override
  Widget build(BuildContext context) {
    return RangeSlider(
      values: _currentRangeValues,
      max: 100,
      divisions: 5,
      labels: RangeLabels(
        _currentRangeValues.start.round().toString(),
        _currentRangeValues.end.round().toString(),
      ),
      onChanged: (RangeValues values) {
        setState(() {
          _currentRangeValues = values;
        });
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on Fedora Linux 41 (Workstation Edition) 6.12.11-200.fc41.x86_64, locale
    en_US.UTF-8) [236ms]
    • Flutter version 3.29.2 on channel stable at /home/kamil/.local/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.2s]
    • Android SDK at /home/kamil/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/kamil/.local/apps/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [141ms]
    • CHROME_EXECUTABLE = /usr/bin/brave-browser-stable

[✓] Linux toolchain - develop for Linux desktop [302ms]
    • clang version 19.1.7 (Fedora 19.1.7-2.fc41)
    • cmake version 3.30.7
    • ninja version 1.12.1
    • pkg-config version 2.3.0

[✓] Android Studio (version 2024.2) [140ms]
    • Android Studio at /home/kamil/.local/apps/android-studio
    • Flutter plugin version 83.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.97.1) [16ms]
    • VS Code at /usr/share/code
    • Flutter extension version 3.106.0

[✓] Connected device (2 available) [147ms]
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 41 (Workstation Edition) 6.12.11-200.fc41.x86_64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 133.1.75.175

[✓] Network resources [397ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Range slider show overlay for both thumbs on hovering one
fixes: #165281 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by rkishan516** [comment]
@TahaTesser Would you mind reviewing this ?

File: packages/flutter/lib/src/material/range_slider.dart [hunk 1]
```diff
@@ -1517,8 +1517,8 @@ class _RenderRangeSlider extends RenderBox with RelayoutWhenSystemFontsChangeMix
       isEnabled: isEnabled,
     );
 
-    final bool startThumbSelected = _lastThumbSelection == Thumb.start;
-    final bool endThumbSelected = _lastThumbSelection == Thumb.end;
+    final bool startThumbSelected = _lastThumbSelection == Thumb.start && !hoveringEndThumb;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/range_slider.dart:1520]: I see that `startThumbSelected` and `endThumbSelected` are also used in later code, deciding whether the thumb paint shows `isPressed` variant. I suspect that we don't want to change that. (Though there's no unit test to verify this...)

Anyway, unless it's intentional by you, I suggest moving these extra conditions to L1525 and L1541.

Comment (rkishan516) [reply packages/flutter/lib/src/material/range_slider.dart:1520]: @dkwingsmt If we paint `thumbShape` with previous condition, then shadow and other decoration effect will still be shown which is not intentional.

Comment (rkishan516) [reply packages/flutter/lib/src/material/range_slider.dart:1520]: So, I think current update is as expected. if you want i can update current test to verify that.

Comment (dkwingsmt) [reply packages/flutter/lib/src/material/range_slider.dart:1520]: @rkishan516 That would be awesome! Yeah can you add that?

Comment (rkishan516) [reply packages/flutter/lib/src/material/range_slider.dart:1520]: Sure

Comment (rkishan516) [reply packages/flutter/lib/src/material/range_slider.dart:1520]: I have updated test.

**Review by dkwingsmt — APPROVED** [review]
LGTM, thanks!

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the fix
