### PR TITLE
Fix Gold flake from gsutil fallback

### LINKED ISSUE #49917: Gold flake: user does not have permission to list objects
```
02:51 +1116 ~1: /tmp/flutter sdk/packages/flutter/test/material/radio_test.dart: Radio ink ripple is displayed correctly                                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test material.radio.ink_ripple.png failed for
a reason unrelated to pixel comparison.

Debug information for Gold:
stdout: Given image with hash 2887f99f7ebb5fda0580e7a4afa32f21 for test material.radio.ink_ripple
Expectation for test: 2887f99f7ebb5fda0580e7a4afa32f21 (positive)
Expectation for test: e0700bcc1503b6e84be54f433dea6ae9 (positive)

stderr: ERROR: logging before flag.Parse: I0131 21:03:52.169569    7736 exec.go:221] exec.go:221
Executing 'gsutil cp /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7708/packages/flutter/test/material/temp/dm.json
gs://skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json'
(where gsutil is /usr/bin/gsutil)
Error running command: ''Error uploading JSON file to GCS path
skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json:
running gsutil. Got output
AccessDeniedException: 403 527266040592-compute@developer.gserviceaccount.com does not have
storage.objects.list access to skia-gold-flutter.

: Command exited with exit status 1: gsutil cp /tmp/flutter
sdk/bin/cache/pkg/skia_goldens7708/packages/flutter/test/material/temp/dm.json
gs://skia-gold-flutter/trybot/dm-json-v1/2020/01/31/21/f202972e4b8e923e0c9b938943bb8545c2cc54b9/6530858593026048/1580504632/dm-1580504632169051403.json.
At gcs.go:101 gcs.go:77 gcs.go:66 goldclient.go:422 goldclient.go:346 errgroup.go:57
asm_amd64.s:1357. At goldclient.go:423 goldclient.go:346 errgroup.go:57 asm_amd64.s:1357''

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:371:9)
<asynchronous suspension>
#1      _AuthorizedFlutterPreSubmitComparator.compare (package:flutter_goldens/flutter_goldens.dart:374:23)
<asynchronous suspension>
#2      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:82:57)
<asynchronous suspension>
#3      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:924:22)
#6      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:922:26)
#7      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#9      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:52:28)
#10     _expect (package:test_api/src/frontend/expect.dart:116:26)
#11     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#12     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#13     main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/material/radio_test.dart:281:11)
#26     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#28     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 31 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

02:51 +1116 ~1 -1: /tmp/flutter sdk/packages/flutter/test/material/popup_menu_test.dart: PopupMenu positioning                                                                                         
02:51 +1116 ~1 -1: /tmp/flutter sdk/packages/flutter/test/material/radio_test.dart: Radio ink ripple is displayed correctly [E]                                                                        
  Test failed. See exception logs above.
  The test description was: Radio ink ripple is displayed correctly
  ```

https://cirrus-ci.com/task/6530858593026048

/cc @Piinks

### LINKED ISSUE #50148: Gold artifacts are being cached on Cirrus that shouldn't be
Investigating #49917 found that temporary gold-related files generated on Cirrus during tests are being cached and affecting future test runs. A larger refactoring is underway to enable luci testing (#49837 and #49749), but also cleaning up these artifacts will need some re-working in flutter_goldens.

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This fixes the flake in #49917 
The flake is caused by the fact that, for some PRs, an empty auth method is used in presubmit testing for contributors that cannot decrypt the service account. This empty auth method still creates an authorization file, although it is empty. This file was cached after the fact in a randomly generated folder. Later on, another PR may randomly choose the same directory and need authentication for tryjobs, but thinks it's already authenticated. 💣 💥 

Additional re-factoring is already scheduled here to support Luci testing, with the eventual goal of removing the need for a service account at all. That work is being tracked by #49837 and #49749. 

## Related Issues

Fixes #49917
Fixes #50148

## Tests

Client will re-authorize if gsutil is enabled

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 1]
```diff
@@ -341,7 +341,8 @@ class AnimationController extends Animation<double>
   /// Stops the animation controller and sets the current value of the
   /// animation.
   ///
-  /// The new value is clamped to the range set by [lowerBound] and [upperBound].
+  /// The new value is clamped to the range set by [lowerBound] and
```
Comment (Piinks) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Trivial >80 character change to trigger framework tests.

File: packages/flutter_goldens/test/flutter_goldens_test.dart [hunk 2]
```diff
@@ -81,6 +82,16 @@ void main() {
       ));
     });
 
+    test('gsuti is checked when authorization file is present', () async {
```
Comment (Piinks) [inline packages/flutter_goldens/test/flutter_goldens_test.dart]:
```suggestion
    test('gsutil is checked when authorization file is present', () async {
```

File: packages/flutter_goldens_client/lib/skia_client.dart [hunk 3]
```diff
@@ -604,12 +604,18 @@ class SkiaGoldClient {
...
   /// for multiple tests.
-  bool _clientIsAuthorized() {
+  Future<bool> clientIsAuthorized() async {
     final File authFile = workDirectory?.childFile(fs.path.join(
       'temp',
       'auth_opt.json',
     ));
-    return authFile.existsSync();
+
+    if(await authFile.exists()) {
```
Comment (dnfield) [inline packages/flutter_goldens_client/lib/skia_client.dart]: Can we just avoid writing this file to a location that gets cached between CI runs?

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: I would like to do that, I filed #50148 to keep up with it and hopefully just incorporate it into the refactoring I'm doing for #49837 and #49749. I think I am going to have to change where all of the files are being managed, json/images/etc, not just this file, which will take a bit more doing. I wanted to unblock others in the meantime.

Comment (dnfield) [reply packages/flutter_goldens_client/lib/skia_client.dart]: Can we add a TODO with a link to those bugs/PRs then?

**Review by dnfield — APPROVED** [review]
LGTM with TODO

File: packages/flutter_goldens_client/lib/skia_client.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: Unless, do you think just using the CIRRUS_WORKING_DIR as the skia client's work directory would do it? I don't know yet where Cirrus draws the line on caching. I thought it wasn't caching these originally. 😅

Comment (dnfield) [reply packages/flutter_goldens_client/lib/skia_client.dart]: On macs we don't do any caching.  You can find out which directories are caching by looking for task names postfixed with _cache.

...although now that I look at it, it seems like the directory this is in doesn't get cached.  Which directory is it again?

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: That's what I thought.. here's one:
```
Authentication set up in directory
/tmp/flutter sdk/bin/cache/pkg/skia_goldens1880/packages/flutter/test/widgets/temp
```

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: ah..
from .cirrus.yml for linux shards:
```
flutter_pkg_cache:
    folder: bin/cache/pkg
    fingerprint_script: echo $OS; cat bin/internal/*.version
```

Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: I might be able to get away with just using Directory.systemTemp for when we are on Cirrus. That should clean up after itself. I don't want to hide golden files when folks are using them elsewhere.

Comment (dnfield) [reply packages/flutter_goldens_client/lib/skia_client.dart]: Yeah, we're caching the pkg directory for sure.

File: packages/flutter_goldens/lib/flutter_goldens.dart [hunk 4]
```diff
@@ -221,6 +233,7 @@ class FlutterSkiaGoldFileComparator extends FlutterGoldenFileComparator {
       defaultComparator,
       platform,
       suffix: '${math.Random().nextInt(10000)}',
+      onCirrus: platform.environment.containsKey('CIRRUS_CI'),
```
Comment (dnfield) [inline packages/flutter_goldens/lib/flutter_goldens.dart]: This should work but we could run into similar problems on LUCI if we're caching anything there - we're not right now but we might in the future.

Should we just make it opt in to put it in the pkg folder so that local users can do that?

File: packages/flutter_goldens_client/lib/skia_client.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter_goldens_client/lib/skia_client.dart]: The goldens repo used to invalidate the cache since it had a version file.

**Comment by Piinks** [comment]
Ok, I think using the `Directory.systemTemp` for Cirrus will keep files out of the cache, PTAL. 

Is there a way that I can invalidate the current pkg cache so it will take out the trash? Or will it eventually clean itself out?

**Comment by dnfield** [comment]
@fkorotkov may know how to kill a cache - I'm not aware of a way.

**Comment by fkorotkov** [comment]
Cirrus re-uploads cache if it changes. BTW if you want different caches for collaborators vs no you can add `echo $CIRRUS_USER_COLLABORATOR` to the `fingerprint_script`.

**Comment by dnfield** [comment]
@fkorotkov - we've unintentionally introduced files into our caches that we don't want.  Can we just clobber them all?

**Comment by fkorotkov** [comment]
I can kill `flutter_pkg-b9000965872fccdeaecb549276f69fd8bbec04bc863f0ee4700f6d10b5b0b510` manually. There is no UI to invalidate caches (https://github.com/cirruslabs/cirrus-ci-docs/issues/379) at the moment unfortunately.

**Comment by dnfield** [comment]
Thanks!

**Comment by Piinks** [comment]
> I can kill `flutter_pkg-b9000965872fccdeaecb549276f69fd8bbec04bc863f0ee4700f6d10b5b0b510` manually. There is no UI to invalidate caches ([cirruslabs/cirrus-ci-docs#379](https://github.com/cirruslabs/cirrus-ci-docs/issues/379)) at the moment unfortunately.

Thank you!
We should wait to nuke it until this is fixed. Otherwise it will just continue to fill up and we'll have to nuke it again.

**Comment by dnfield** [comment]
We could also just update the fingerprint script (e.g. just add some string to the end of the output) in this pull so that future pulls will use a different cache.

**Comment by fkorotkov** [comment]
nuked it 🙌

File: packages/flutter_goldens/lib/flutter_goldens.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter_goldens/lib/flutter_goldens.dart]: Oh this will, be different when I refactor for Luci. Do you mean we should default to using systemTempDirectory and set the flag for the other way around, to use the pkg folder if we are local?

Comment (dnfield) [reply packages/flutter_goldens/lib/flutter_goldens.dart]: Yeah, although if we have to change this anyway for LUCI it's probably not a big deal either way.

File: packages/flutter_goldens_client/lib/skia_client.dart [hunk 5]
```diff
@@ -604,12 +604,18 @@ class SkiaGoldClient {
...
+      final String contents = await authFile.readAsString();
+      final Map<String, dynamic> decoded = json.decode(contents) as Map<String, dynamic>;
+      return !(decoded['GSUtil'] as bool);
```
Comment (Piinks) [inline packages/flutter_goldens_client/lib/skia_client.dart]: I'm inclined to leave this here as a back up, we can make sure we aren't caching anything, but if for some reason Gold tries to fallback on gsutil again it should catch it.

Comment (dnfield) [reply packages/flutter_goldens_client/lib/skia_client.dart]: SG

**Comment by Piinks** [comment]
I made a few teaks @dnfield, should be ready to go now. :)
