### PR TITLE
ThemeData: optimize by removing polymorphism and caching; fix merging

### LINKED ISSUE #12247: stock_build_iteration benchmark regressed with typography i18n
https://github.com/flutter/flutter/pull/11829 regressed `stock_build_iteration` slightly.

screen shot 2017-09-25 at 12 47 43 pm

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/12247

This fixes the regression by trading the lazy evaluated `_LocalizedThemeData` wrapper, which introduces a level of indirection and makes the `ThemeData` type polymorphic (its methods cannot be inlined or statically dispatched), for an eagerly evaluated `ThemeData` copy, which is memoized and is monomorphic.

/cc @Hixie

### CODE REVIEW

File: packages/flutter/lib/src/material/theme_data.dart [hunk 1]
```diff
@@ -418,50 +418,76 @@ class ThemeData {
...
+    // WARNING: this method memoizes the result based on the previously seen
+    // baseTheme and localTextGeometry. Memoization is safe because all inputs
+    // and outputs of this function are deeply immutable, and the computations
+    // are referentially transparent. It only short-circuits the computation if
+    // the new inputs are identical() to the previous ones. It does not use the
+    // == operator, which performs a costly deep comparison. This memoization
+    // saves us ~6% on the stock_build_iteration benchmark.
+    //
+    // When changing this method, make sure the memoization logic is correct. Do
+    // not forget about the two hardest things in computer science:
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: to avoid broken links, i recommend inlining the advice you want to reference here.

File: packages/flutter/lib/src/material/theme_data.dart [hunk 2]
```diff
@@ -418,50 +418,76 @@ class ThemeData {
     IconThemeData accentIconTheme,
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: you can add the @immutable back to Theme

File: packages/flutter/lib/src/material/theme_data.dart [hunk 3]
```diff
@@ -418,50 +418,76 @@ class ThemeData {
...
+      iconTheme: iconTheme ?? this.iconTheme,
+      primaryIconTheme: primaryIconTheme ?? this.primaryIconTheme,
+      accentIconTheme: accentIconTheme ?? this.accentIconTheme,
+      platform: platform ?? this.platform,
     );
   }
 
+  static ThemeData _lastBaseTheme;
+  static TextTheme _lastLocalTextGeometry;
+  static ThemeData _memoizedLocalizeResult;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: this is going to be trivial to defeat by just having two themes in the app, which will be pretty common, no?

Did you check if the memoization is actually helpful vs just the aggressive merging?

Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: > this is going to be trivial to defeat by just having two themes in the app, which will be pretty common, no?

This optimizes for the case when the number of calls to `Theme.of` is >> the number of `Theme` and `Localizations` widgets. The number of times a theme changes during the build phase of a single frame should be proportional to the number of `Theme`/`Localizations` widgets in the tree. As we build a frame, we do a depth-first traversal (needs citation). `Theme`/`Localizations` applies to a whole sub-tree of widgets. Therefore, while building the sub-tree under a `Theme`/`Localizations` (whichever is the nearest ancestor) we should see a 100% cache hit rate. Only when the build phase moves on to the part of the tree with a different `Theme`/`Localizations`, do we need to re-merge the theme.

> Did you check if the memoization is actually helpful vs just the aggressive merging?

I checked the following options:

- No wrapper, no memoization. Result: even worse that the current regression.
- Keep the wrapper, add memoization: Result: almost no improvement (within the noise).
- No wrapper, add memoization, use `==` instead of `identical`. Result: only gets us halfway back to the original numbers.
- No wrapper, add memoization (this PR): Result: back to the original numbers.

My experiments were not at all scientific. I just ran the benchmark 3 times and eyeballed the numbers.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Done.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/theme_data.dart]: We guarantee that we won't do a node that's a descendant before a node that's an ancestor, but that's as far as we go in terms of guaranteeing an order. We don't generally do depth first except for when the next dirty node happens to be a direct child and there's no layout builders.

I was assuming the optimisation was intended to last across multiple frames, but I guess even if it doesn't it's still a good optimisation in this case. My concern is that this is basically a hidden performance cliff, which we've so far worked really really hard to avoid.

I don't have a better suggestion though...

Comment (Hixie) [reply packages/flutter/lib/src/material/theme_data.dart]: How about an MRU cache of the last N pairs of objects or some such? At least the cliff would be less serious...

**Comment by yjbanov** [comment]
New changes: https://github.com/flutter/flutter/pull/12249/commits/a5c8779587f6cd9cfb951d870facf84927a4c937

File: packages/flutter/lib/src/material/theme_data.dart (hunk 3 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Added a cache.

File: packages/flutter/lib/src/material/theme_data.dart [hunk 4]
```diff
@@ -614,245 +639,105 @@ class ThemeData {
...
-  @override
-  Color get selectedRowColor => delegate.selectedRowColor;
-
-  @override
-  Color get splashColor => delegate.splashColor;
-
-  @override
-  Color get textSelectionColor => delegate.textSelectionColor;
+  bool operator ==(Object other) {
+    final _IdentityThemeDataCacheKey otherKey = other;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: assert that `other is _IdentityThemeDataCacheKey` and document that this object doesn't support being compared to other types (which normally would be a violation of `==` semantics)

**Comment by Hixie** [comment]
LGTM if the performance is back to what it was before.

**Comment by yjbanov** [comment]
Settled on a FIFO cache, which has a 100μs (1.8%) advantage over the RLU cache.

File: packages/flutter/lib/src/material/theme_data.dart [hunk 5]
```diff
@@ -418,50 +419,81 @@ class ThemeData {
...
   /// The [TextStyle.inherit] field in the text styles provided by
   /// [localTextGeometry] must be set to true.
   static ThemeData localize(ThemeData baseTheme, TextTheme localTextGeometry) {
+    // WARNING: this method memoizes the result in a cache based on the
+    // previously seen baseTheme and localTextGeometry. Memoization is safe
+    // because all inputs and outputs of this function are deeply immutable, and
+    // the computations are referentially transparent. It only short-circuits
+    // the computation if the new inputs are identical() to the previous ones.
+    // It does not use the == operator, which performs a costly deep comparison.
+    // This memoization saves us ~4% on the stock_build_iteration benchmark.
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: this comment is out of date now

File: packages/flutter/lib/src/material/theme_data.dart [hunk 6]
```diff
@@ -614,245 +646,54 @@ class ThemeData {
...
-
-  @override
-  Color get secondaryHeaderColor => delegate.secondaryHeaderColor;
-
-  @override
-  Color get selectedRowColor => delegate.selectedRowColor;
-
-  @override
-  Color get splashColor => delegate.splashColor;
+  int get hashCode => identityHashCode(baseTheme) ^ identityHashCode(localTextGeometry);
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: maybe add a comment here that this hash code function must be fast

File: packages/flutter/lib/src/material/theme_data.dart [hunk 7]
```diff
@@ -614,245 +646,54 @@ class ThemeData {
...
-      textTheme: textTheme,
-      primaryTextTheme: primaryTextTheme,
-      accentTextTheme: accentTextTheme,
-      iconTheme: iconTheme,
-      primaryIconTheme: primaryIconTheme,
-      accentIconTheme: accentIconTheme,
-      platform: platform,
-    );
+  bool operator ==(Object other) {
+    final _IdentityThemeDataCacheKey otherKey = other;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: and a comment that we are explicitly ignoring the possibility that the types might not match in the interests of speed

File: packages/flutter/lib/src/material/theme_data.dart [hunk 8]
```diff
@@ -418,50 +419,81 @@ class ThemeData {
...
+      primaryIconTheme: primaryIconTheme ?? this.primaryIconTheme,
+      accentIconTheme: accentIconTheme ?? this.accentIconTheme,
+      platform: platform ?? this.platform,
     );
   }
 
+  // The number 5 was chosen without any real science or research behind it. It
+  // just seemed like a number that's not too big (we should be able to fit 5
+  // copies of ThemeData in memory comfortably) and not too small (most apps
+  // shouldn't have more than 5 themes).
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: 5 theme/localization pairs.

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/material/theme_data.dart (hunk 5 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Removed (although, we're still saving something comparing to just not caching; still the number isn't interesting without qualifying exactly what it is we're comparing with)

File: packages/flutter/lib/src/material/theme_data.dart (hunk 8 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Done.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 6 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Done.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 7 above)
Comment (yjbanov) [reply packages/flutter/lib/src/material/theme_data.dart]: Done.

**Comment by tvolkert** [comment]
FYI, this broke tests inside Google - is it safe to revert and roll forward with a fix?

**Comment by yjbanov** [comment]
I'm willing to look into what broke so we don't have to rollback. My gut feeling is we should just fix those tests, they are likely making wrong assumptions about `ThemeData`.
