### PR TITLE
Ensure attaching to an application with an existing DDS instance is not treated as a fatal error

### LINKED ISSUE #2936: Attaching to flutter tests no longer works
- Run `flutter test --start-paused test/widget_test.dart`
- Try to attach using the following:
  ```
  {
	"name": "Dart: Attach to Test",
	"type": "dart",
	"request": "attach",
	"vmServiceUri": "${command:dart.promptForVmService}",
  },
  ```

It'll fail and quit. We essentially run ` flutter attach --machine -d macos --debug-uri http://127.0.0.1:52407/HASY0oHZsH0=/` which will fail in the same way from the terminal.

It seems to be because we're using `flutter attach`. I suspect either that's changed, or in the past we would use the VM directly for attaching to tests.

As a workaround, you can use `cwd` to prevent detecting it's a Flutter project and attaching with Dart:

```
  "cwd": "test",
```

### PR DESCRIPTION
**Pull request by bkonyi**
@DanTup, this should fix https://github.com/Dart-Code/Dart-Code/issues/2936.

Re-upload of #70792 since I apparently don't know how to Git.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by DanTup** [comment]
I tried merging these changes locally for testing, though I still see this issue (it prints it as a warning, but then also as an error and quits):

Screenshot 2020-11-30 at 11 59 35

If I reproduce using just the terminal, the process doesn't quit (it's probably VS Code doing that when it gets the `app.stop` event) but you still see the error and the `stop` message:

```
danny@Dannys-MBP asdassdadsasda % flutter attach --machine -d macos --debug-uri http://127.0.0.1:51289/OVnnaegeXoQ=/   
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":4710}}]
[{"event":"app.start","params":{"appId":"a35caf97-ca20-42a7-8fa3-c7f7fa8f62b0","deviceId":"macos","directory":null,"supportsRestart":true,"launchMode":"attach"}}]
Error connecting to the service protocol: failed to connect to http://127.0.0.1:51289/OVnnaegeXoQ=/
[{"event":"app.stop","params":{"appId":"a35caf97-ca20-42a7-8fa3-c7f7fa8f62b0"}}]
```

**Comment by jonahwilliams** [comment]
FYI @bkonyi I'll be OOO if you get time to come back to this.

**Comment by bkonyi** [comment]
Confirmed the behavior you're seeing @DanTup. I'll take a look today.

File: packages/flutter_tools/lib/src/base/dds.dart [hunk 1]
```diff
@@ -57,6 +58,11 @@ class DartDevelopmentService {
       logger.printTrace('DDS is listening at ${_ddsInstance.uri}.');
     } on dds.DartDevelopmentServiceException catch (e) {
       logger.printTrace('Warning: Failed to start DDS: ${e.message}');
+      if (e.errorCode == dds.DartDevelopmentServiceException.existingDdsInstanceError) {
+        _existingDdsUri = Uri.parse(
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/base/dds.dart:62]: As a cleanup it would be nice to provide this as an optional field on the DartDevelopmentServiceException

**Review by jonahwilliams — APPROVED** [review]
Still LGTM

**Comment by DanTup** [comment]
Works now, thanks!
