### PR TITLE
Ensure snapshot rebuild logic takes main path into account

### LINKED ISSUE #11400: `flutter run lib/foo.dart` always runs the first thing built
## Steps to Reproduce

1) Create a sample using `flutter create`
1) Rename `lib/main.dart` to `lib/blue.dart`
1) Copy `lib/blue.dart` to `lib/red.dart`
1) Edit `lib/red.dart` so that the theme color is red.
1) Execute `flutter run lib/blue.dart`
1) Notice that the theme is blue.
1) Execute `flutter run lib/red.dart`
1) Notice that the theme is _still_ blue.
1) Execute `flutter build clean`
1) Execute `flutter run lib/red.dart`
1) Notice that the theme is now red.

Basically, once you build an app, no amount of changing the arguments will let you run a different program until you do "flutter build clean" (or remove the build/ directory).

## Logs

```
Launching lib/red.dart on Pixel in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                             0.9s
Running 'gradlew assembleDebug'...                    3.2s
Built build/app/outputs/apk/app-debug.apk (21.2MB).
Installing build/app/outputs/apk/app.apk...           7.2s
Syncing files to device Pixel...                      2.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel is available at: http://127.0.0.1:8112/
For a more detailed help message, press "h". To quit, press "q".

Application finished.
```

```
Analyzing /Users/gspencer/code/run_bug/lib/red.dart...
No issues found!
Ran in 3.9s
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/gspencer/code/flutter
    • Framework revision 41d5ad411d (4 minutes ago), 2017-07-25 15:59:41 -0700
    • Engine revision 3a12bc092d
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 15.2
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • Pixel • FA6AS0303682 • android-arm • Android 7.1.2 (API 25)

### PR DESCRIPTION
**Pull request by mravn-google**
Fixes #11400 

This is a retake of #11730 which was intercepted by #11820. The latter partially fixes #11400.

* Fixes the remaining part of #11400. Switch of main entry point would still be ignored, with no new snapshot built, if we happen to switch between two main entry points that are both snapshot dependencies independently of whether they are selected as main entry point. This happens e.g. if the two main entry points import each other. This is fixed by including the main entry point path along with build mode and target platform in the checksum file.
* Refactors `Checksum` into `Fingerprint` to reflect that the class no longer just handles file checksums, but also build properties.
* Separates the general notion of a build `Fingerprint` from the `Snapshotter`'s knowledge of actual build properties to save.
* Prevents the creation of a `SnapshotType` with `null` build mode, to avoid having to check for this situation down-stream.

### CODE REVIEW

**Comment by Hixie** [comment]
Do you include the identity of the engine as part of this? One thing I've noticed in the past is that if I switch between using --local-engine and not using it, we don't rebuild. Or if I use --local-engine then rebuild the engine, we don't rebuild.

**Comment by mravn-google** [comment]
Intercepted by #11913. I'll stop this race.

**Comment by cbracken** [comment]
Sorry about that! Only spotted #11730 on Friday when Hixie CC'ed me on it, but by that time the merge conflicts were pretty nasty-looking. Should have CC'ed you on #11913 when I sent it out on Friday, but it slipped mind -- sorry about that!

I really like the idea of renaming Checksum -> Fingerprint and using a map for the additional properties. Probably worth sending that bit out if nothing else. I'm also happy to pick up that bit of cleanup if you've got other things on your plate.

**Comment by mravn-google** [comment]
@cbracken No worries, I just didn't want to keep racing :-). If you are done working on this, I can do the refactoring and address Ian's comment about the engine too. Just let me know.

**Comment by cbracken** [comment]
I'm done for the time being. Refactor + local engine handling would be fantastic. I'm going to be working on disentangling all the AOT variants from build_aot.dart and slowly swinging them over out of the one big build method + adding tests.

File: packages/flutter_tools/lib/src/base/build.dart [hunk 1]
```diff
@@ -55,84 +57,70 @@ class GenSnapshot {
...
   }
 
-  String _mainPath;
-  String _buildMode;
-  String _targetPlatform;
   Map<String, String> _checksums;
+  Map<String, String> _properties;
 
-  String toJson() => JSON.encode(<String, dynamic>{
+  String  toJson() => JSON.encode(<String, dynamic>{
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/base/build.dart]: nit: looks like an extra space slipped in after the return type.

File: packages/flutter_tools/lib/src/base/build.dart [hunk 2]
```diff
@@ -21,7 +21,9 @@ GenSnapshot get genSnapshot => context.putIfAbsent(GenSnapshot, () => const GenS
 
 /// A snapshot build configuration.
 class SnapshotType {
-  const SnapshotType(this.platform, this.mode);
+  SnapshotType(this.platform, this.mode) {
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/base/build.dart]: Any reason to not keep the const? (and if not, `s/new/const/` in `buildScriptSnapshot`)

File: packages/flutter_tools/test/base/build_test.dart [hunk 3]
```diff
@@ -494,5 +489,46 @@ void main() {
...
+          new SnapshotType(TargetPlatform.android_x64, BuildMode.release),
+          'a.dart',
+          <String>['a.dart', 'b.dart'],
+        );
+        expect(fingerprint, new Fingerprint.fromBuildInputs(<String, String>{
+          'buildMode': 'BuildMode.release',
+          'targetPlatform': 'TargetPlatform.android_x64',
+          'entryPoint': 'a.dart',
+        }, <String>['a.dart', 'b.dart']));
+      }, overrides: <Type, Generator>{ FileSystem: () => fs});
```
Comment (cbracken) [inline packages/flutter_tools/test/base/build_test.dart]: nit: `s/fs}/fs }/` at the end

File: packages/flutter_tools/test/base/build_test.dart [hunk 4]
```diff
@@ -434,10 +423,13 @@ void main() {
       await fs.file('other.dart').writeAsString('import "main.dart";\nvoid main() {}');
       await fs.file('output.snapshot').create();
       await fs.file('output.snapshot.d').writeAsString('output.snapshot : main.dart');
-      await fs.file('output.snapshot.d.checksums').writeAsString(JSON.encode(<String, dynamic>{
-        'version': '$kVersion',
```
Comment (cbracken) [inline packages/flutter_tools/test/base/build_test.dart]: Oops! Thanks for fixing!

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

Thanks!

**Review by mravn-google — COMMENTED** [review]
Thanks for the review!

File: packages/flutter_tools/lib/src/base/build.dart (hunk 2 above)
Comment (cbracken) [reply packages/flutter_tools/lib/src/base/build.dart]: Ah yep - not sure how many times that's bit me now! The engine is compiled with that flag set, but we don't run the tool that way. Thanks.

**Comment by cbracken** [comment]
Thanks again!

File: packages/flutter_tools/lib/src/base/build.dart (hunk 2 above)
Comment (aam) [reply packages/flutter_tools/lib/src/base/build.dart]: Not sure about `const`, but simple fix for asserts support in `pub run test` is to set `DART_VM_OPTIONS=--assert-initializer` for `pub run test` invocation.

**Comment by Hixie** [comment]
We control the VM entrypoint (it's in the bash script) so it should be a trivial thing to just pass the flag to enable const asserts and anything else we want.
