### PR TITLE
TwoLevelList fails to restore sublist expanded state

### LINKED ISSUE #2845: TwoLevelList doesn't correctly remember which items are expanded
If another page is pushed on top of a page containing a TwoLevelList, when returning to the TwoLevelList all sublists are expanded. The expected behavior is that only the sublists that were expanded when leaving the first page should be expanded.

### PR DESCRIPTION
**Pull request by HansMuller**
Each TwoLevelList item needs a unique key to ensure that it ends up with its own expanded state.

Added a TwoLevelList scrollableKey parameter so that its Block can be used to drive the AppBar.

Fixes https://github.com/flutter/flutter/issues/2845

### CODE REVIEW

File: packages/flutter/lib/src/material/two_level_list.dart [hunk 1]
```diff
@@ -154,11 +154,23 @@ class _TwoLevelSublistState extends State<TwoLevelSublist> {
...
   final MaterialListType type;
+  final Key scrollableKey;
 
   @override
-  Widget build(BuildContext context) => new Block(children: items);
+  Widget build(BuildContext context) {
+    int itemIndex = 0;
+    List<Widget> itemsWithUniqueKeys = items?.map((Widget item) {
+      return new KeyedSubtree(
+        key: item.key != null ? new ValueKey<Key>(item.key) : new ValueKey<int>(itemIndex++),
```
Comment (abarth) [inline packages/flutter/lib/src/material/two_level_list.dart]: You probably want to increment itemIndex every trip through the loop, regardless of whether the item.key is null.

I wonder if we want to break this out into a helper function (maybe a static on KeyedSubtree) now that we've got this pattern in two places.  KeyedSubtree.ensureKeysForList(...) ?

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/material/two_level_list.dart (hunk 1 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/two_level_list.dart]: Sure, will do that.
