### PR TITLE
Fix `DropdownMenu` keyboard navigation

### LINKED ISSUE #147253: DropdownMenu keyboard navigation is broken
### Steps to reproduce

1. Run sample code on  Windows platform
2. Press tab until the handle of the DropdownMenu is focused
3. Press enter to open the menu
4. Press the down key to navigate

### Expected results

The menu opens with the first option selected and when pressing the Down key the options should cycle downwards.

### Actual results

The menu opens with the `second` option selected and when pressing the down key cycles until the option `g` (which is the initial selection).

If I instead try to cycle upwards using the Up key, the cycle completes and restart from the end once the start of the list is reached. However, the initially selected option is skipped.

There are also other glitches like the text not being in sync with the selected menu option, as shown on the screenshot below.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

enum Units {
  unit,
  kg,
  g,
  l,
  cc;
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Units? _unit = Units.g;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: DropdownMenu<Units>(
          initialSelection: _unit,
          dropdownMenuEntries: Units.values
              .map((unit) => DropdownMenuEntry(
                    value: unit,
                    label: unit.name,
                  ))
              .toList(),
          onSelected: (value) {
            setState(() {
              _unit = value;
            });
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details closed><summary>Screenshots</summary>

Mismatched text and menu option when cycling upwards:
image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
> flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Versi¢n 10.0.22631.3447], locale es-AR)
    • Flutter version 3.19.5 on channel stable at D:\diego\PROGRAMACION\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\diego\PROGRAMACION\SDKs\Android
    • Platform android-34, build-tools 33.0.1
    • Java binary at: D:\diego\PROGRAMACION\Tools\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at D:\diego\PROGRAMACION\Tools\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.88.0)
    • VS Code at C:\Users\diego\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.22631.3447]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.61
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #147516: DropdownMenu does not highlight correct selected item
### Steps to reproduce

With the following code, when item with label `test` is selected the item with label `my test` is selected instead, Although the object has different uuid. if I select `bla` or `test 1` then it works as expected.

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Custom Dropdown Menu',
      home: DropdownMenuExample(),
    );
  }
}

class DropdownMenuExample extends StatefulWidget {
  @override
  _DropdownMenuExampleState createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  MyObject? selectedValue;

  @override
  Widget build(BuildContext context) {
    List<MyObject> items = [
    MyObject(
      name: 'my test',
      uuid: '3fa85f64-5617-4562-b3fc-2c963f66afa6',
    ),
    MyObject(
      name: "bla",
      uuid: "4fa85f64-5717-4562-b3fc-2c963f66afa6",

    ),
    MyObject(
      name: "test",
      uuid: "3fa85f64-5717-4562-b3fc-2c963f68afa6",
    ),
    MyObject(
      name: "test 2",
      uuid: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    ),


  ];
    return Scaffold(
      appBar: AppBar(
        title: Text('Custom Dropdown Menu'),
      ),
      body: Center(
        child: DropdownMenu<MyObject>(
          initialSelection: selectedValue,
    
          onSelected: (MyObject? newValue) {
            setState(() {
              selectedValue = newValue;
            });
          },
          dropdownMenuEntries: items.map<DropdownMenuEntry<MyObject>>((MyObject scope) {
            return DropdownMenuEntry<MyObject>(
              value: scope,
              label: scope.name,
            );
          }).toList(),
        ),
      ),
    );
  }
}


class MyObject {
  final String name;
  final String uuid;

  MyObject({
    required this.name,
    required this.uuid,
  });
}
```

### Expected results

if I select `test` then `test` should be highlighted the next time the menu is opened. 

### Actual results

With the following code, when item with label `test` is selected the item with label `my test` is selected instead, Although the object has different uuid. if I select `bla` or `test 1` then it works as expected.

### Code sample

<details open><summary>Code sample</summary>

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Custom Dropdown Menu',
      home: DropdownMenuExample(),
    );
  }
}

class DropdownMenuExample extends StatefulWidget {
  @override
  _DropdownMenuExampleState createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  MyObject? selectedValue;

  @override
  Widget build(BuildContext context) {
    List<MyObject> items = [
    MyObject(
      name: 'my test',
      uuid: '3fa85f64-5617-4562-b3fc-2c963f66afa6',
    ),
    MyObject(
      name: "bla",
      uuid: "4fa85f64-5717-4562-b3fc-2c963f66afa6",

    ),
    MyObject(
      name: "test",
      uuid: "3fa85f64-5717-4562-b3fc-2c963f68afa6",
    ),
    MyObject(
      name: "test 2",
      uuid: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    ),


  ];
    return Scaffold(
      appBar: AppBar(
        title: Text('Custom Dropdown Menu'),
      ),
      body: Center(
        child: DropdownMenu<MyObject>(
          initialSelection: selectedValue,
    
          onSelected: (MyObject? newValue) {
            setState(() {
              selectedValue = newValue;
            });
          },
          dropdownMenuEntries: items.map<DropdownMenuEntry<MyObject>>((MyObject scope) {
            return DropdownMenuEntry<MyObject>(
              value: scope,
              label: scope.name,
            );
          }).toList(),
        ),
      ),
    );
  }
}


class MyObject {
  final String name;
  final String uuid;

  MyObject({
    required this.name,
    required this.uuid,
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.22.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.87.2)```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
Fix https://github.com/flutter/flutter/issues/147253
Fix https://github.com/flutter/flutter/issues/147516

Resubmitted https://github.com/flutter/flutter/pull/147285 because I accidentally added reviewer as contributor in a commit by using Github "add suggestion to batch". Which causing CLA check to fail and I cannot revert it.

I use exact match of label instead of contains to minimise possible change in actual user search.
I added the new test after the original keyboard navigation test to avoid merge conflict with another incoming PR.
Let me know if I need to make any changes.

Sorry for the inconvenience, I am new to the process.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by PurplePolyhedron** [comment]
> cc @QuncCccccc who has a great knowledge of this widget.

as suggested in the original PR.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -550,6 +550,9 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
     if (searchText.isEmpty) {
       return null;
     }
+    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase() == searchText) {
+      return currentHighlight;
+    }
     final int index = entries.indexWhere((DropdownMenuEntry<T> entry) => entry.label.toLowerCase().contains(searchText));
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/dropdown_menu.dart:556]: Great job here—I'm glad we aren't searching through all the `entries` to find `currentHighlight` when it was already set in the keyboard event callback.

**Review by nate-thegrate — APPROVED** [review]
Flutter_LGTM

Thanks for this contribution!

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 2]
```diff
@@ -550,6 +550,9 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
     if (searchText.isEmpty) {
       return null;
     }
+    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase() == searchText) {
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:553]: nit: The default search algorithm is just to search an item that contains the queried text. Do you think if we should just use `contains(...)` instead of exact matching? :)

**Review by QuncCccccc — COMMENTED** [review]
Thanks for the contribution and this looks great! Just left one question below:)

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 2 above)
Comment (nate-thegrate) [reply packages/flutter/lib/src/material/dropdown_menu.dart:553]: I believe this check is meant for when `currentHighlight` is set using the up/down arrow keys, which means there's always an exact match.

But using `contains(...)` here would let us skip the loop in other situations too, so that sounds great!

```suggestion
    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
```

Comment (PurplePolyhedron) [reply packages/flutter/lib/src/material/dropdown_menu.dart:553]: As a side effect of using `contains(...)` searching would prioritises the current highlight. This should be better unless it breaks something.

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the fix!

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -764,6 +764,116 @@ void main() {
     expect(item5material.color, Colors.transparent); // the previous item should not be highlighted.
   }, variant: TargetPlatformVariant.desktop());
 
+  // Regression test for https://github.com/flutter/flutter/issues/147253.
+  testWidgets('Down key and up key can navigate on desktop platforms '
+      'when a label text contains another label text', (WidgetTester tester) async {
+    final ThemeData themeData = ThemeData();
+    await tester.pumpWidget(MaterialApp(
+      theme: themeData,
```
[the remark this answers is not in the document]
Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart:772]: The theme is used as reference to check which item is highlighted. Other highlight tests in `dropdown_menu_test.dart` are done in the same way.

```
expect(item1Material.color, themeData.colorScheme.onSurface.withOpacity(0.12));
```

[the remark this answers is not in the document]
Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart:772]: Oh that's right! Sorry I missed that!

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks for the contribution!
