### PR TITLE
Fix DataTable example not being scrollable

### LINKED ISSUE #112755: Cannot scroll in DataTable documentation example
The example has 10 rows, but you can't scroll to the rows out of view. Scrolling isn't the point of the example, but there are rows out of view and showing scrolling would be helpful for less experienced users.

https://api.flutter.dev/flutter/material/DataTable-class.html#material.DataTable.2

### PR DESCRIPTION
**Pull request by Chinmay-KB**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
- Fixes the DataTable example not being scrollable in the docs
- Added test for ensuring the DataTable is scrollable
- Added the performance considerations when DataTable is wrapped in a SingleChildScrollView in docs.

Fixes #112755 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Chinmay-KB** [comment]
The existing example has 10 items in DataTable, as all of them are already visible on the screen, writing a test for checking scrollability doesn't work, hence the items length was increased to 20. Does that work or should I do `tester.binding.setSurfaceSize` to a small enough size instead? @TahaTesser

File: packages/flutter/lib/src/material/data_table.dart [hunk 1]
```diff
@@ -357,6 +358,11 @@ class DataCell {
 /// [PaginatedDataTable] which automatically splits the data into
 /// multiple pages.
 ///
+/// ## Performance considerations when wrapping [DataTable] with [SingleChildScrollView]
+///
+/// Wrapping a [DataTable] with [SingleChildScrollView] is expensive as [SingleChildScrollView]
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/data_table.dart:363]: When https://github.com/flutter/packages/pull/4536 lands, this could point to using `TableView` instead?

cc @Piinks

File: examples/api/test/material/data_table/data_table.1_test.dart [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+      const example.DataTableExampleApp(),
+    );
+
+    expect(find.text('Row 0').hitTestable(), findsOneWidget);
+    expect(find.text('Row 19').hitTestable(), findsNothing);
+
+    await tester.ensureVisible(find.text('Row 19'));
+
+    expect(find.text('Row 0').hitTestable(), findsNothing);
+    expect(find.text('Row 19').hitTestable(), findsOneWidget);
```
Comment (TahaTesser) [inline examples/api/test/material/data_table/data_table.1_test.dart:20]:
```suggestion
    expect(find.byType(SingleChildScrollView), findsOneWidget);

    expect(tester.getTopLeft(find.text('Row 5')), const Offset(66.0, 366.0));

    await tester.drag(find.byType(SingleChildScrollView), const Offset(0.0, -200.0));
    await tester.pumpAndSettle();

    expect(tester.getTopLeft(find.text('Row 5')), const Offset(66.0, 186.0));
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Comment by TahaTesser** [comment]
> The existing example has 10 items in DataTable, as all of them are already visible on the screen, writing a test for checking scrollability doesn't work, hence the items length was increased to 20. Does that work or should I do `tester.binding.setSurfaceSize` to a small enough size instead? @TahaTesser
 
20 items sound good to me. 👍

File: packages/flutter/lib/src/material/data_table.dart [hunk 3]
```diff
@@ -4,6 +4,7 @@
 
 import 'dart:math' as math;
 
+import 'package:flutter/material.dart';
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/data_table.dart:7]:
```suggestion
```

The material class shouldn't import material library.

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: examples/api/test/material/data_table/data_table.1_test.dart (hunk 2 above)
Comment (TahaTesser) [reply examples/api/test/material/data_table/data_table.1_test.dart]: @Chinmay-KB 
I have updated the test to test `SingleChildScrollView` scrolls the `DataTable`.

The previous test didn't exactly test the changes made to the code sample.

**Comment by Chinmay-KB** [comment]
Anything else I need to do to ready this PR @TahaTesser

File: examples/api/test/material/data_table/data_table.1_test.dart [hunk 4]
```diff
@@ -0,0 +1,23 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter_api_samples/material/data_table/data_table.1.dart' as example;
+import 'package:flutter_test/flutter_test.dart';
```
Comment (TahaTesser) [inline examples/api/test/material/data_table/data_table.1_test.dart:6]:
```suggestion
import 'package:flutter/material.dart';
import 'package:flutter_api_samples/material/data_table/data_table.1.dart' as example;
import 'package:flutter_test/flutter_test.dart';
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Comment by TahaTesser** [comment]
@Chinmay-KB 

The class string for this newly added test class needs to be removed `_knownMissingTests` set in `dev/bots/check_code_samples.dart`

https://github.com/flutter/flutter/blob/bd64bf5f923fa79635f2971531d9dfd717046963/dev/bots/check_code_samples.dart#L295

File: packages/flutter/lib/src/material/data_table.dart [hunk 5]
```diff
@@ -357,6 +357,11 @@ class DataCell {
 /// [PaginatedDataTable] which automatically splits the data into
 /// multiple pages.
 ///
+/// ## Performance considerations when wrapping [DataTable] with [SingleChildScrollView]
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/data_table.dart:360]: @Piinks Do you have any suggestions for this section?

File: packages/flutter/lib/src/material/data_table.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/data_table.dart:362]: Yeah probably. :)

I would recommend adding some reference here to other options, not including TableView since that has not landed yet. If someone should not use a SingleChildScrollView because the table is very large, we should recommend PaginatedDataTable to split it up, or using a CustomScrollView.

TableView may not be relevant if someone only cares about scrolling in one direction, but we can add a reference to it when it is available.

File: packages/flutter/lib/src/material/data_table.dart (hunk 5 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/data_table.dart:360]: Just the comment below, we should provide an alternative recommendation. :)

Comment (Chinmay-KB) [reply packages/flutter/lib/src/material/data_table.dart:360]: So, suggest using `PaginatedDataTable` wherever possible?
Or is there a better alternative

**Comment by Anianonymous** [comment]
I want to work on this issue. Can you please assign me?

File: packages/flutter/lib/src/material/data_table.dart (hunk 5 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/data_table.dart:360]: > we should recommend PaginatedDataTable to split it up, or using a CustomScrollView.

I think those two would be the best recommendation for now. :)

Comment (Chinmay-KB) [reply packages/flutter/lib/src/material/data_table.dart:360]: Now that TableRow is merged to master, should that be added as a recommendation?

Comment (Piinks) [reply packages/flutter/lib/src/material/data_table.dart:360]: Let's just add the previously mentioned recommendations for now so we can land this PR. We'll likely do a sweep overall to see where we should be mentioning the TableView.

File: packages/flutter/lib/src/material/data_table.dart [hunk 6]
```diff
@@ -1364,10 +1422,12 @@ class _NullTableColumnWidth extends TableColumnWidth {
...
 
   @override
-  double maxIntrinsicWidth(Iterable<RenderBox> cells, double containerWidth) => throw UnimplementedError();
+  double maxIntrinsicWidth(Iterable<RenderBox> cells, double containerWidth) =>
+      throw UnimplementedError();
 
   @override
-  double minIntrinsicWidth(Iterable<RenderBox> cells, double containerWidth) => throw UnimplementedError();
+  double minIntrinsicWidth(Iterable<RenderBox> cells, double containerWidth) =>
+      throw UnimplementedError();
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/data_table.dart:1430]: Looks like you've made some unintended format changes. 

Please read https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting


Please revert the format changes

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/data_table.dart (hunk 6 above)
Comment (Chinmay-KB) [reply packages/flutter/lib/src/material/data_table.dart]: Fixed this

File: examples/api/lib/material/data_table/data_table.1.dart [hunk 7]
```diff
@@ -46,7 +45,8 @@ class _DataTableExampleState extends State<DataTableExample> {
         rows: List<DataRow>.generate(
           numItems,
           (int index) => DataRow(
-            color: MaterialStateProperty.resolveWith<Color?>((Set<MaterialState> states) {
+            color: MaterialStateProperty.resolveWith<Color?>(
+                (Set<MaterialState> states) {
```
Comment (TahaTesser) [inline examples/api/lib/material/data_table/data_table.1.dart:49]:
```suggestion
            color: MaterialStateProperty.resolveWith<Color?>((Set<MaterialState> states) {
```

Comment (TahaTesser) [reply examples/api/lib/material/data_table/data_table.1.dart:49]: Restoring this change

**Review by TahaTesser — DISMISSED** [review]

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!

**Comment by Piinks** [comment]
The autosubmit bot is wrong here, filed https://github.com/flutter/flutter/issues/134477
Merging manually.
