### PR TITLE
Correct max height calculation to fade and animate insets on scroll in CupertinoSearchTextField

### LINKED ISSUE #165152: CupertinoSliverNavigationBar.search does not fade or animate insets if search view scrolled in automatic mode
### Steps to reproduce

1. In CupertinoSliverNavigationBar.search, in automatic mode, tap to open the search view.
2. Scroll the search view.
3. Without scrolling back up, exit the search view.
4. Then, try to collapse the search field in the inactive search view.

### Expected results

When the inactive search view is scrolled, the search field should fade and animate its insets.

### Actual results

When the inactive search view is scrolled, the search field does not fade or animate its insets.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const NavBarBlueApp());

class NavBarBlueApp extends StatelessWidget {
  const NavBarBlueApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: CupertinoThemeData(),
      home: FirstPage(),
    );
  }
}

class FirstPage extends StatefulWidget {
  const FirstPage({super.key});

  @override
  State<FirstPage> createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: CustomScrollView(
        slivers: [
          CupertinoSliverNavigationBar.search(
            stretch: true,
            searchField: CupertinoSearchTextField(
                suffixMode: OverlayVisibilityMode.always,
                suffixIcon: Icon(
                  CupertinoIcons.mic_solid,
                )),
            largeTitle: Text('First Page'),
            automaticallyImplyLeading: true,
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return CupertinoListTile(
                  title: Text('Item $index'),
                );
              },
              childCount: 20,
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/6e4302eb-ee28-4fc1-8a33-e92408b16e2d

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.30.0-1.0.pre.588, on macOS 15.3.1 24D70 darwin-arm64, locale en)
    ! Flutter version 3.30.0-1.0.pre.588 on channel [user-branch] at /Users/victorsanni/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository git@github.com:victorsanni/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:victorsanni/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Victor’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Fixes [CupertinoSliverNavigationBar.search does not fade or animate insets if search view scrolled in automatic mode](https://github.com/flutter/flutter/issues/165152) 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/search_field.dart [hunk 1]
```diff
@@ -439,12 +440,13 @@ class _CupertinoSearchTextFieldState extends State<CupertinoSearchTextField> wit
...
-    if (_maxHeight == null) {
-      _maxHeight ??= context.size?.height;
-    } else if (notification is ScrollUpdateNotification) {
+    if (notification is ScrollUpdateNotification) {
       final double currentHeight = context.size?.height ?? 0.0;
       setState(() {
-        _fadeExtent = _calculateScrollOpacity(currentHeight, _maxHeight!);
+        _fadeExtent = _calculateScrollOpacity(
+          currentHeight,
+          widget.itemSize + math.max(widget.prefixInsets.vertical, widget.suffixInsets.vertical),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/search_field.dart:448]: Doesn't look like the calculation is accurate, the documentation says the itemSize can be scaled by the system a11y text scale factor

File: packages/flutter/test/cupertino/search_field_test.dart [hunk 2]
```diff
@@ -749,4 +749,67 @@ void main() {
...
+
+    // The prefix icon has faded.
+    expect(prefixIconFinder, findsOneWidget);
+    expect(
+      tester
+          .widget<Opacity>(find.ancestor(of: prefixIconFinder, matching: find.byType(Opacity)))
+          .opacity,
+      lessThan(1.0),
+    );
+  });
```
Comment (justinmc) [inline packages/flutter/test/cupertino/search_field_test.dart:814]: Nit: Would it be useful to duplicate this test but this time set the text scale to something huge?

**Review by justinmc — APPROVED** [review]
LGTM with a nit about possibly adding another test. :+1:

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!

File: packages/flutter/test/cupertino/search_field_test.dart (hunk 2 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/search_field_test.dart:814]: Actually in the process of writing a test I found that the widget is currently not respecting the accessibility text scale (and there is currently no test for that as well). So replacing

```
_scaledIconSize = MediaQuery.textScalerOf(context).scale(widget.itemSize);
```

with 

```
_scaledIconSize = widget.itemSize;
```

changes nothing currently. Maybe we should file an issue for this and fix in a separate PR.

Comment (victorsanni) [reply packages/flutter/test/cupertino/search_field_test.dart:814]: To confirm this, I changed the accessibility text scale in the settings app on the simulator. I noticed the text on the page scaled, but the search field contents did not.

what do you think @LongCatIsLooong @justinmc?
