### PR TITLE
Blocks exynos9820 chip from vulkan

### LINKED ISSUE #171992: [3.32.0][Android][Impeller][Regression] Vulkan Rendering to SurfaceProducer Fails on Samsung S10 (SM-G973N) with Flutter 3.32.0+ (after #164201)
Reopen of #170775 (closed due to inactivity; however, the issue still persists and I was unable to follow up earlier)

### Steps to reproduce

1. Obtain a Samsung Galaxy S10 (SM-G973N) running Android 12 (Build Number: SP1A.210812.016).
2. Clone [the repository](https://github.com/bc-lee/test-flutter-android-texture) and build the app. I tested with Flutter 3.32.0+ as well as the master branch (commit: 72017e1a06b3d224f0a24575b50d9c3b510e29f9).
3. Run the app on the device and tap the Start button to begin rendering the triangle.

### Expected results

The app should render a red triangle on the screen without any issues.

### Actual results

The triangle is almost not visible due to almost white color.

### Code sample

See the repository above mentioned in the steps to reproduce.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Default:

https://github.com/user-attachments/assets/41bfac49-7762-4d6d-b916-7fb7f9dd0beb

If Impeller is disabled, or if ImpellerBackend is explicitly set to OpenGL (by uncommenting the line `io.flutter.embedding.android.ImpellerBackend` in `AndroidManifest.xml`):

https://github.com/user-attachments/assets/b407e5bc-9ea8-434b-b0cf-f0156a8fe432

</details>

### Logs

<details open><summary>Logs</summary>

```console
---------------------------- PROCESS STARTED (13527) for package com.example.testapp ----------------------------
10:58:21.313 13527-13527 ActivityThread          com.example.testapp      D  handleBindApplication()++ app=com.example.testapp
10:58:21.314 13527-13527 Compatibil...geReporter com.example.testapp      D  Compat change id reported: 171979766; UID 10288; state: ENABLED
10:58:21.439 13527-13527 GraphicsEnvironment     com.example.testapp      V  ANGLE Developer option for 'com.example.testapp' set to: 'default'
10:58:21.439 13527-13527 GraphicsEnvironment     com.example.testapp      V  The updatable driver is turned off on this device.
10:58:21.443 13527-13527 LoadedApk               com.example.testapp      D  LoadedApk::makeApplication() appContext.mOpPackageName=com.example.testapp appContext.mBasePackageName=com.example.testapp
10:58:21.444 13527-13527 NetworkSecurityConfig   com.example.testapp      D  No Network Security Config specified, using platform default
10:58:21.480 13527-13527 NetworkSecurityConfig   com.example.testapp      D  No Network Security Config specified, using platform default
10:58:21.497 13527-13527 ActivityThread          com.example.testapp      D  handleBindApplication() --
10:58:21.508 13527-13527 libEGL                  com.example.testapp      I  EGL_ANDROID_blob_cache_path advertised, but unable to get eglSetBlobCachePathANDROID
10:58:21.508 13527-13527 EglBase14Impl           com.example.testapp      I  Using OpenGL ES version 2
10:58:21.518 13527-13564 OpenGLRenderer          com.example.testapp      D  RenderThread::requireGlContext()
10:58:21.525 13527-13564 OpenGLRenderer          com.example.testapp      D  RenderThread::setGrContext()
10:58:21.544 13527-13566 FlutterJNI              com.example.testapp      D  Beginning load of flutter...
10:58:21.545 13527-13567 ResourceExtractor       com.example.testapp      I  Found extracted resources res_timestamp-1-1752199071285
10:58:21.545 13527-13567 ResourceExtractor       com.example.testapp      I  Resource version mismatch res_timestamp-1-1752199100482
10:58:21.552 13527-13566 FlutterJNI              com.example.testapp      D  flutter (null) was loaded normally!
10:58:21.765 13527-13567 ResourceExtractor       com.example.testapp      I  Extracted baseline resource assets/flutter_assets/kernel_blob.bin
10:58:21.766 13527-13567 ResourceExtractor       com.example.testapp      I  Extracted baseline resource assets/flutter_assets/vm_snapshot_data
10:58:21.817 13527-13567 ResourceExtractor       com.example.testapp      I  Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
10:58:21.828   521-521   audit                   auditd                   E  type=1327 audit(1752199101.825:3042): proctitle="com.example.testapp"
10:58:21.837 13527-13569 vulkan                  com.example.testapp      D  searching for layers in '/data/app/~~hfjKnrFzw4WyheXCSpZmlQ==/com.example.testapp-YuAPEikxclEr897TMB53Sw==/lib/arm64'
10:58:21.837 13527-13569 vulkan                  com.example.testapp      D  searching for layers in '/data/app/~~hfjKnrFzw4WyheXCSpZmlQ==/com.example.testapp-YuAPEikxclEr897TMB53Sw==/base.apk!/lib/arm64-v8a'
10:58:21.845 13527-13569 vulkan                  com.example.testapp      D  added global layer 'VK_LAYER_KHRONOS_validation' from library '/data/app/~~hfjKnrFzw4WyheXCSpZmlQ==/com.example.testapp-YuAPEikxclEr897TMB53Sw==/base.apk!/lib/arm64-v8a/libVkLayer_khronos_validation.so'
10:58:21.883 13527-13569 flutter                 com.example.testapp      I  [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(62)] Using the Impeller rendering backend (Vulkan).
10:58:21.984 13527-13590 flutter                 com.example.testapp      I  The Dart VM service is listening on http://127.0.0.1:38673/Y4SvyQP-SRU=/
10:58:22.067 13527-13594 EglBase14Impl           com.example.testapp      I  Using OpenGL ES version 2
10:58:22.088 13527-13527 example.testap          com.example.testapp      W  Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
10:58:22.088 13527-13527 example.testap          com.example.testapp      W  Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
10:58:22.088 13527-13527 example.testap          com.example.testapp      W  Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
10:58:22.088 13527-13527 example.testap          com.example.testapp      W  Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
10:58:22.103 13527-13527 DecorView               com.example.testapp      I  [INFO] isPopOver=false, config=true
10:58:22.103 13527-13527 DecorView               com.example.testapp      I  updateCaptionType >> DecorView@250e7a[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
10:58:22.103 13527-13527 DecorView               com.example.testapp      D  setCaptionType = 0, this = DecorView@250e7a[]
10:58:22.105 13527-13527 DecorView               com.example.testapp      I  getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
10:58:22.118 13527-13527 DecorView               com.example.testapp      I  notifyKeepScreenOnChanged: keepScreenOn=false
10:58:22.123 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  setView = com.android.internal.policy.DecorView@250e7a TM=true
10:58:23.089 13527-13527 Choreographer           com.example.testapp      I  Skipped 57 frames!  The application may be doing too much work on its main thread.
10:58:23.099 13527-13527 SurfaceView@77453b3     com.example.testapp      I  onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{77453b3 V.E...... ......I. 0,0-0,0} of ViewRootImpl@de59846[MainActivity]
10:58:23.107 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=5 res=0x7 s={true 520108826352} ch=true fn=-1
10:58:23.111 13527-13564 hw-ProcessState         com.example.testapp      D  Binder ioctl to enable oneway spam detection failed: Invalid argument
10:58:23.111 13527-13564 OpenGLRenderer          com.example.testapp      D  eglCreateWindowSurface
10:58:23.127 13527-13527 SurfaceView@77453b3     com.example.testapp      I  windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{77453b3 V.E...... ......ID 0,0-1080,2154} of ViewRootImpl@de59846[MainActivity]
10:58:23.127 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11420 android.view.ViewRootImpl.performTraversals:4193 android.view.ViewRootImpl.doTraversal:2919
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  pST: sr = Rect(0, 0 - 1080, 2154) sw = 1080 sh = 2154
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@3e551da
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  updateSurface: mVisible = true mSurface.isValid() = true
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
10:58:23.129 13527-13527 SurfaceView@77453b3     com.example.testapp      I  surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{77453b3 V.E...... ......ID 0,0-1080,2154}
10:58:23.130 13527-13569 BufferQueueProducer     com.example.testapp      I  [SurfaceView - com.example.testapp/com.example.testapp.MainActivity@77453b3@0#1(BLAST Consumer)1](id:34d700000002,api:1,p:13527,c:13527) FrameBooster: VULKAN surface was catched
10:58:23.130 13527-13569 example.testap          com.example.testapp      D  FrameBooster: InterpolationGui: UID 10288 detected as using Vulkan
10:58:23.131 13527-13569 Gralloc4                com.example.testapp      I  mapper 4.x is not supported
10:58:23.132 13527-13569 Gralloc3                com.example.testapp      W  mapper 3.x is not supported
10:58:23.133 13527-13569 gralloc                 com.example.testapp      I  Arm Module v1.0
10:58:23.134 13527-13569 Gralloc4                com.example.testapp      W  allocator 4.x is not supported
10:58:23.134 13527-13569 Gralloc3                com.example.testapp      W  allocator 3.x is not supported
10:58:23.189 13527-13527 SurfaceView@77453b3     com.example.testapp      I  surfaceChanged (1080,2154) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{77453b3 V.E...... ......ID 0,0-1080,2154}
10:58:23.190 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  [DP] dp(2) 1 android.view.SurfaceView.updateSurface:1375 android.view.SurfaceView.lambda$new$1$SurfaceView:254 android.view.SurfaceView$$ExternalSyntheticLambda2.onPreDraw:2
10:58:23.190 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  [DP] pdf(1) 1 android.view.SurfaceView.notifyDrawFinished:599 android.view.SurfaceView.performDrawFinished:586 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0
10:58:23.302 13527-13527 VideoRenderer           com.example.testapp      D  createTexture with width: 1280, height: 720
10:58:23.305 13527-13596 EglBase14Impl           com.example.testapp      I  Using OpenGL ES version 2
10:58:23.307 13527-13527 EglRenderer             com.example.testapp      I  VideoRenderer-0Initializing EglRenderer
10:58:23.307 13527-13527 VideoRendererManager    com.example.testapp      D  Created texture with id: 0, resolution: 1280x720
10:58:23.318 13527-13527 flutter                 com.example.testapp      I  VideoRenderer initialized with textureId: 0
10:58:23.320 13527-13527 PhoneWindow             com.example.testapp      D  forceLight changed to false [com.example.testapp/com.example.testapp.MainActivity] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4319 com.android.internal.policy.PhoneWindow.setNavigationBarColor:4011 io.flutter.plugin.platform.PlatformPlugin.setSystemChromeSystemUIOverlayStyle:503 io.flutter.plugin.platform.PlatformPlugin.access$700:36 io.flutter.plugin.platform.PlatformPlugin$1.setSystemUiOverlayStyle:123
10:58:23.320 13527-13527 DecorView               com.example.testapp      I  notifyKeepScreenOnChanged: keepScreenOn=false
10:58:23.328 13527-13527 DecorView               com.example.testapp      I  notifyKeepScreenOnChanged: keepScreenOn=false
10:58:23.336 13527-13527 InsetsSourceConsumer    com.example.testapp      D  ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.example.testapp/com.example.testapp.MainActivity
10:58:23.337 13527-13527 InsetsSourceConsumer    com.example.testapp      D  ensureControlAlpha: for ITYPE_STATUS_BAR on com.example.testapp/com.example.testapp.MainActivity
10:58:23.337 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=7 res=0x3 s={true 520108826352} ch=false fn=1
10:58:23.346 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  updateBoundsLayer: t = android.view.SurfaceControl$Transaction@30760b sc = Surface(name=Bounds for - com.example.testapp/com.example.testapp.MainActivity@0)/@0x1bcce8 frame = 1
10:58:23.346 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  mWNT: t = android.view.SurfaceControl$Transaction@30760b fN = 1 android.view.ViewRootImpl.prepareSurfaces:2778 android.view.ViewRootImpl.performTraversals:4024 android.view.ViewRootImpl.doTraversal:2919
10:58:23.346 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  mWNT: merge t to BBQ
10:58:23.380 13527-13598 SurfaceView@77453b3     com.example.testapp      I  uSP: rtp = Rect(0, 0 - 1080, 2154) rtsw = 1080 rtsh = 2154
10:58:23.380 13527-13598 SurfaceView@77453b3     com.example.testapp      I  onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
10:58:23.380 13527-13598 SurfaceView@77453b3     com.example.testapp      I  aOrMT: uB = true t = android.view.SurfaceControl$Transaction@356b1a6 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319
10:58:23.380 13527-13598 SurfaceView@77453b3     com.example.testapp      I  aOrMT: vR.mWNT, vR = ViewRootImpl@de59846[MainActivity]
10:58:23.380 13527-13598 ViewRootIm...nActivity] com.example.testapp      I  mWNT: t = android.view.SurfaceControl$Transaction@356b1a6 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728
10:58:23.380 13527-13598 ViewRootIm...nActivity] com.example.testapp      I  mWNT: merge t to BBQ
10:58:23.445 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4995 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938
10:58:23.445 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  [DP] rdf()
10:58:23.445 13527-13527 ViewRootIm...nActivity] com.example.testapp      D  reportDrawFinished (fn: 1)
10:58:23.459 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  MSG_WINDOW_FOCUS_CHANGED 1 1
10:58:23.460 13527-13527 InputMethodManager      com.example.testapp      D  startInputInner - Id : 0
10:58:23.460 13527-13527 InputMethodManager      com.example.testapp      I  startInputInner - mService.startInputOrWindowGainedFocus
10:58:23.465 13527-13527 InputMethodManager      com.example.testapp      D  startInputInner - Id : 0
10:58:23.575   987-1034  WindowManager           system_server            E  win=Window{5714f7e u0 Splash Screen com.example.testapp EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5841 com.android.server.wm.ActivityRecord.destroySurfaces:5822 com.android.server.wm.WindowState.onExitAnimationDone:5965 com.android.server.wm.WindowStateAnimator.onAnimationFinished:242 com.android.server.wm.WindowState.onAnimationFinished:6218 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda0.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:113
10:58:27.321 13527-13596 EglRenderer             com.example.testapp      I  VideoRenderer-0Duration: 4012 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
10:58:27.781 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  ViewPostIme pointer 0
10:58:27.894 13527-13527 ViewRootIm...nActivity] com.example.testapp      I  ViewPostIme pointer 1
10:58:27.929 13527-13527 flutter                 com.example.testapp      I  VideoRenderer initialized with textureId: 0
10:58:27.938 13527-13527 RenderManager           com.example.testapp      D  startRender called for textureId: 0
10:58:27.939 13527-13594 RenderManager           com.example.testapp      D  ===== System Info =====
10:58:27.939 13527-13594 RenderManager           com.example.testapp      D  Manufacturer: samsung
10:58:27.939 13527-13594 RenderManager           com.example.testapp      D  Model: SM-G973N
10:58:27.939 13527-13594 RenderManager           com.example.testapp      D  Device Name (codename): beyond1
10:58:27.939 13527-13594 RenderManager           com.example.testapp      D  Android Version: 12 (API 31)
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  First released API: 28
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  Build ID: SP1A.210812.016
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  ===== OpenGL ES Info =====
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  OpenGL ES Version: OpenGL ES 3.2 v1.r32p1-01bet2-mbs2v39_0.131801e953429f661ecce1d5e1d2b3ef
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  OpenGL ES Vendor: ARM
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  OpenGL ES Renderer: Mali-G76
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  OpenGL ES Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_unpack_subimage GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_ARM_texture_unnormalized_coordinates GL_EXT_shader_framebuffer_fetch
10:58:27.941 13527-13594 RenderManager           com.example.testapp      D  ===== Vulkan Info =====
10:58:27.943 13527-13594 RenderManager           com.example.testapp      D  Vulkan Hardware Level: 1
10:58:27.943 13527-13594 RenderManager           com.example.testapp      D  Vulkan Hardware Version: 0x401000
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I  ===== Vulkan Info (Native) =====
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I  Vulkan Instance Extensions:
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_surface (spec version: 25)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_android_surface (spec version: 6)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_EXT_swapchain_colorspace (spec version: 4)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_get_surface_capabilities2 (spec version: 1)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_EXT_debug_report (spec version: 9)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_device_group_creation (spec version: 1)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_external_fence_capabilities (spec version: 1)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_external_memory_capabilities (spec version: 1)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_external_semaphore_capabilities (spec version: 1)
10:58:27.943 13527-13594 SystemInfo              com.example.testapp      I    VK_KHR_get_physical_device_properties2 (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I  Device Name: Mali-G76
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I    API Version: 1.1.177
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I    Driver Version: 134221824
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I    Vendor ID: 0x13b5
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I    Device ID: 0x72110000
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I    Device Extensions:
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_incremental_present (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_hdr_metadata (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shared_presentable_image (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_GOOGLE_display_timing (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_16bit_storage (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_8bit_storage (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_bind_memory2 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_buffer_device_address (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_create_renderpass2 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_dedicated_allocation (spec version: 3)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_depth_stencil_resolve (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_descriptor_update_template (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_device_group (spec version: 4)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_driver_properties (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_fence (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_fence_fd (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_memory (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_memory_fd (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_semaphore (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_external_semaphore_fd (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_get_memory_requirements2 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_image_format_list (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_imageless_framebuffer (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_maintenance1 (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_maintenance2 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_maintenance3 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_multiview (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_relaxed_block_layout (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_sampler_mirror_clamp_to_edge (spec version: 3)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_sampler_ycbcr_conversion (spec version: 14)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_separate_depth_stencil_layouts (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shader_draw_parameters (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shader_float16_int8 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shader_float_controls (spec version: 4)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shader_non_semantic_info (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_shader_subgroup_extended_types (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_spirv_1_4 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_storage_buffer_storage_class (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_timeline_semaphore (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_uniform_buffer_standard_layout (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_variable_pointers (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_vulkan_memory_model (spec version: 3)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_astc_decode_mode (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_calibrated_timestamps (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_global_priority (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_host_query_reset (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_image_robustness (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_index_type_uint8 (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_inline_uniform_block (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_line_rasterization (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_provoking_vertex (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_queue_family_foreign (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_device_memory_report (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_scalar_block_layout (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_separate_stencil_usage (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_subgroup_size_control (spec version: 2)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_texture_compression_astc_hdr (spec version: 1)
10:58:27.964 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_shader_subgroup_ballot (spec version: 1)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_shader_subgroup_vote (spec version: 1)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_transform_feedback (spec version: 1)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_external_memory_dma_buf (spec version: 1)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_image_drm_format_modifier (spec version: 1)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_custom_border_color (spec version: 12)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_ANDROID_external_memory_android_hardware_buffer (spec version: 3)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_KHR_swapchain (spec version: 70)
10:58:27.965 13527-13594 SystemInfo              com.example.testapp      I      VK_EXT_4444_formats (spec version: 1)
10:58:27.966 13527-13594 RenderManager           com.example.testapp      D  Triangle rendering started successfully
10:58:28.068 13527-13569 ImageReade...ceProducer com.example.testapp      D  ImageTextureEntry can't wait on the fence on Android < 33
10:58:28.570 13527-13610 ProfileInstaller        com.example.testapp      D  Installing profile for com.example.testapp
10:58:31.333 13527-13596 EglRenderer             com.example.testapp      I  VideoRenderer-0Duration: 4011 ms. Frames received: 197. Dropped: 0. Rendered: 196. Render fps: 48.9. Average render time: 1499 us. Average swapBuffer time: 1006 us.
10:58:33.853 13527-13527 ImageReader_JNI         com.example.testapp      W  Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
10:58:35.343 13527-13596 EglRenderer             com.example.testapp      I  VideoRenderer-0Duration: 4007 ms. Frames received: 239. Dropped: 0. Rendered: 240. Render fps: 59.9. Average render time: 1444 us. Average swapBuffer time: 1087 us.
10:58:39.351 13527-13596 EglRenderer             com.example.testapp      I  VideoRenderer-0Duration: 4010 ms. Frames received: 240. Dropped: 0. Rendered: 240. Render fps: 59.8. Average render time: 1497 us. Average swapBuffer time: 1082 us.
10:58:39.942 13527-13527 ImageReader_JNI         com.example.testapp      W  Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
10:58:41.533 13527-13527 ImageReader_JNI         com.example.testapp      W  Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
10:58:43.359 13527-13596 EglRenderer             com.example.testapp      I  VideoRenderer-0Duration: 4007 ms. Frames received: 240. Dropped: 0. Rendered: 239. Render fps: 59.6. Average render time: 1455 us. Average swapBuffer time: 1060 us.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.5 24F74 darwin-arm64, locale en-KR) [2.9s]
    • Flutter version 3.32.0 on channel stable at /Users/redacted/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (7 weeks ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.9s]
    • Android SDK at /Users/redacted/Library/android-sdk
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/redacted/Library/android-sdk
    • Java binary at: /Users/redacted/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [4.4s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [105ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [104ms]
    • Android Studio at /Users/redacted/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.3) [102ms]
    • IntelliJ at /Users/redacted/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 86.0.2
    • Dart plugin version 251.26927.39

[✓] VS Code (version 1.102.0) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (3 available) [7.6s]
    • SM G973N (mobile) • R39M601C0TV • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 138.0.7204.101
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [456ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/171992

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
fyi @bc-lee

**Comment by bc-lee** [comment]
Thanks. It works as expected on the Galaxy S10 5G (SM-G977N, Exynos 9820).

**Comment by jonahwilliams** [comment]
Just an FYI: https://github.com/flutter/flutter/blob/bf4cf11a754fcbe1bd6941e1cdfc1d3763978e8e/engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc#L21

**Comment by gaaclarke** [comment]
> Just an FYI:

Thanks.  I didn't know about that class.  I wasn't sure if it was part of the regular initialization workflow.

File: engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc [hunk 1]
```diff
@@ -31,7 +31,8 @@ static constexpr const char* kBLC[] = {
     "exynos9609",  //
     "exynos9610",  //
     "exynos9611",  //
-    "exynos9810"   //
+    "exynos9810",  //
+    "exynos9820"   // https://github.com/flutter/flutter/issues/171992.
```
Comment (chinmaygarde) [inline engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc]: Trying to come up with a story behind this list, it looks like [most Mongoose (at SARC) and Pre-Mongoose SOCs](https://en.wikipedia.org/wiki/Exynos#2016%E2%80%932020:_Mongoose_Era) have trouble importing AHBs.

Can we just say we are going to block all Samsung SoC with the Mongoose and Pre-Mongoose generation? Post Mongoose, till XClipse on Vulkan 1.3, will also use OpenGL because of that other gate we talked about. XClipse after Vulkan 1.3 is all Vulkan. This gives us a consistent story we can reason about.

So, instead of just this mysterious list, we can say `IsMongooseOrOlder()` and qualify it as a bad driver for AHB imports.

exynos9825 seems to be the last Mongoose SoC that is not on this list. How much do you want to bet that is also problematic but we haven't heard a report for it?

**Review by chinmaygarde — APPROVED** [review]
lgtm because it fixes the linked issue. But I'd be more comfortable gating all Mongoose or older exynos SoCs from Samsung. There are so many variants that I don't want to test all. The list is in the Wiki.

File: engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc]: The last mongoose was actually the 990.  After this PR here's the state:

Name | GPU | Blocked
-- | -- | --
Exynos 8 Octa 8890 | Mali-T880 MP10 (Lite) @650 MHzMali-T880 MP12 @650 MHz | ✅
Exynos 9 Octa 8895 | Mali-G71 MP20 @ 546 MHz[99][100] | ✅
Exynos 7 Series 9609 | Mali-G72 MP3 | ✅
Exynos 7 Series 9610 | Mali-G72 MP3 @ 1053 MHz[101] | ✅
Exynos 7 Series 9611 | Mali-G72 MP3 @ 850 MHz | ✅
Exynos 9 Series 9810 | Mali-G72 MP18 @ 572 MHz[102] | ✅
Exynos 9 Series 9820 | Mali-G76 MP12 @ 702 MHz | ✅
Exynos 9 Series 9825 | Mali-G76 MP12 @ 754 MHz | ❌
Exynos 9 Series 980 | Mali-G76 MP5 @ 728 MHz | ❌
Exynos 9 Series 990 | Mali-G77 MP11 @ 832 MHz | ❌

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc]: Considering the 9825 has the same gpu, it's almost a sure thing it's borked.

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/android/android_context_dynamic_impeller.cc]: Added 9825, I held off adding 980 and 990.

**Comment by chinmaygarde** [comment]
Okie dokie. We can keep an eye out for reports of a 980 or 990.

**Comment by bc-lee** [comment]
I agree that banning the Exynos 9825 makes sense, as the 9820 (e.g., Galaxy S10) and 9825 (e.g., Galaxy Note 10) share the same CPU and GPU configuration, with the only major difference being the manufacturing process node. The Exynos 990, however, was released a year later with a different GPU. I’m not sure if the same applies to that SoC.
