### PR TITLE
Fix Dialog and PopupMenu completion logic

### LINKED ISSUE #337: closing the menu in stocks throws an exception
cc @HansMuller

### PR DESCRIPTION
**Pull request by HansMuller**
It's now (just) in TransitionRoute.

Added smoke tests for showMenu() and showDialog().

Fixes https://github.com/flutter/flutter/issues/337

### CODE REVIEW

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -92,10 +92,14 @@ abstract class TransitionRoute extends OverlayRoute {
 
   void didPop(dynamic result) {
     _result = result;
-    if (completer != null)
-      _performance.reverse().then((_) { completer.complete(_result); });
+    void finish() {
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/routes.dart]: I think this would be clearer without this nested function.

Its body can just be `completer?.complete(result);`.

That can probably just be inlined in the two places you call it.

Also, if I'm reading the code right, you don't need to explicitly do the reverse().then(finish) logic, because the `_handleStatusChanged` method already does that. No?

**Comment by Hixie** [comment]
LGTM, modulo the didPop() function
