### PR TITLE
Reland "Dismiss text selection toolbar with ESC"

### LINKED ISSUE #98163: The escape key should close the right click menu on desktop
When the right click menu is open, pressing the escape key should close it.  I confirmed that this is the native behavior on Mac and Windows.  I assume Linux is the same but I haven't tried.

### Steps to reproduce

 1. Run any Flutter app with a text field on a desktop platform (example given below).
 2. Right click on the text field.  The context menu shows.
 3. Press the escape key.

Expected: The context menu closes.
Actual: Nothing happens and the context menu remains on the screen.

### Solution
We could add a text editing shortcut for this and it should work for now, but if we allow context menus outside of EditableText (as mentioned in https://github.com/flutter/flutter/issues/90563), then the Shortcuts widget won't receive the escape when nothing is focused and it won't always work.

@gspencergoog Is it possible to receive a Shortcut when nothing is focused?

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Relands https://github.com/flutter/flutter/pull/98511

Currently still broken but looking for some hints on how to fix this.

<details>
 <summary>Demo</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: Center(
          child: Column(
            children: [
              AutocompleteBasicExample(),
              TextField()
            ],
          ),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}
```
</details>

Fixes https://github.com/flutter/flutter/issues/98163

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by markusaksli-nc** [comment]
@justinmc do you know why this doesn't work? I'm not sure how else to disable the action so it doesn't interfere with other ESC to dismiss behavior.

**Comment by justinmc** [comment]
Sorry, I think I was mistaken with the advice I gave in https://github.com/flutter/flutter/pull/98600#issuecomment-1042427902.

Instead of using isEnabled and consumesKey, I think you should check toolbarIsVisible in _hideToolbarAction's onInvoke.  If it is, hide it.  If not, reinvoke DismissIntent using [Actions.invoke](https://master-api.flutter.dev/flutter/widgets/Actions/invoke.html).

It seems like isEnabled and consumesKey don't actually allow an Intent to pass through.  See the example below and let me know if this doesn't make sense.

CC @gspencergoog Am I right that a disabled Action will not let its Intent pass through to a higher Actions, and the correct way to do that is to reinvoke Actions.invoke, not to use isEnabled?  See the example below.

<details>

<summary>Example of reinvoking an Action. isEnabled/consumesKey don't work.</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  final FocusNode _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Demo'),
      ),
      body: Center(
        child: Shortcuts(
          shortcuts: const <ShortcutActivator, Intent>{
            SingleActivator(LogicalKeyboardKey.escape): _MyIntent(),
          },
          child: Actions(
            actions: <Type, Action<Intent>>{
              _MyIntent: CallbackAction<_MyIntent>(onInvoke: (_) {
                print('Outer Actions called for _MyIntent');
              }),
            },
            child: Builder(
              builder: (BuildContext context) {
                return Actions(
                  actions: <Type, Action<Intent>>{
                    _MyIntent: CallbackAction<_MyIntent>(onInvoke: (_MyIntent intent) {
                      print('Inner Actions called for _MyIntent');
                      return Actions.invoke(context, intent);
                    }),
                    // The below will not work. I believe it passes the key
                    // through, but not the _MyIntent.
                    /*
                    _MyIntent: _TransparentCallbackAction<_MyIntent>(onInvoke: (_) {
                      print('justin _TransparentCallbackAction invoked?');
                    }),
                    */
                  },
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [            
                      const TextField(
                        decoration: InputDecoration(
                          hintText: 'Tap to focus the field, then press escape.',
                        ),
                      ),
                      TextButton(
                        focusNode: _focusNode,
                        onPressed: () {
                          _focusNode.requestFocus();
                        },
                        child: const Text('Or tap to focus the button before pressing escape.'),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

class _MyIntent extends Intent {
  const _MyIntent();
}

// An attempt at creating an Action that passes its Intent through, but it
// doesn't work.  I believe isEnabled and consumesKey are operating on the key
// itself, which is handled by Shortcuts, and no the Intent.
/*
class _TransparentCallbackAction<T extends Intent> extends CallbackAction<T> {
  _TransparentCallbackAction({
    required OnInvokeCallback<T> onInvoke,
  }) : super(onInvoke: onInvoke);

  @override
  bool isEnabled(covariant T intent) => false;

  @override
  bool consumesKey(covariant T intent) => false;
}
*/
```

</details>

**Comment by markusaksli-nc** [comment]
Thanks for the advice. I was coming at this from the wrong angle thinking about the key event being consumed but rather the issue was that the `DismissIntent` fired from the app was being consumed at the first depth and without being re-invoked it would obviously not do anything further down the tree.

This got rid of the issues I was having, let me know if there is anything that should be changed about the added method. I was wondering if this could also cause issues down the line in the autocomplete dismiss PR since it doesn't re-invoke?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -1318,6 +1318,41 @@ void main() {
...
+          focusNode: focusNode,
+          style: textStyle,
+          cursorColor: cursorColor,
+          selectionControls: materialTextSelectionControls,
+        ),
+      ),
+    );
+
+    final EditableTextState state =
+    tester.state<EditableTextState>(find.byType(EditableText));
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:1336]: Nit: indent this.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I think you're right, your autocomplete dismiss PR should reinvoke the intent like this.  Good catch.  Do you want to open a quick PR for that?  I can do it if you don't have time.
