### PR TITLE
[flutter_tools] detect ipv6 in fuchsia server url

### LINKED ISSUE #55592: [fuchsia] Flutter driver test failing due to pm server
The failure manifests itself as an infra failure but it's masking:

```[   +4 ms] Error running Fuchsia pm tool "serve" command
[ +683 ms] executing: /b/s/w/ir/flutter/bin/cache/artifacts/fuchsia/tools/pm publish -a -r build/fuchsia/.pkg-repo -f /b/s/w/ir/flutter/bin/cache/artifacts/flutter_runner/flutter/x64/debug/jit/flutter_jit_runner-0.far
[ +722 ms] executing: ssh -F /b/s/w/ir/fuchsia_ssh_config 192.168.42.104 amber_ctl add_repo_cfg -n flutter_tool -f http://fe80::ec4:7aff:fecc:ea8f%eno2:40017/config.json
[  +49 ms] 2020/04/24 17:01:48 error adding repo: failed to open file: open http://fe80::ec4:7aff:fecc:ea8f%eno2:40017/config.json: ErrNotFound: http:/fe80::ec4:7aff:fecc:ea8f%eno2:40017/config.json
[        ] Failed to teach amber about the package server
[        ] Shutting down the tool's package server.```


Full logs are at: https://chromium-swarm.appspot.com/task?id=4bc5ee3eac3e1b10

cc: @godofredoc

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

We were not correctly formatting ipv6 urls in `FuchsiaPackageServer`. Parse the InternetAddress to determine if its an ipv6 type and format with braces 

Fixes https://github.com/flutter/flutter/issues/55592

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_pm.dart [hunk 1]
```diff
@@ -180,19 +180,22 @@ class FuchsiaPM {
...
   final String _repo;
   final String _host;
   final int _port;
+  final bool _ipv6;
 
   Process _process;
 
   /// The URL that can be used by the device to access this package server.
-  String get url => 'http://$_host:$_port';
+  String get url => _ipv6
```
Comment (natebosch) [inline packages/flutter_tools/lib/src/fuchsia/fuchsia_pm.dart:196]: Is this performance critical? My personal preference would be to not require a correct ipv6 determination ahead of time.

```dart
String get url => '${Uri(scheme: 'http', host: _host, port: _port)}';
```

One slight difference in behavior, if `_port` is `80` you won't get the `:80` on this String. That's probably an improvement.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/fuchsia/fuchsia_pm.dart:196]: Oh, thats a lot nicer - thanks @natebosch

**Review by natebosch — APPROVED** [review]

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_pm.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/fuchsia/fuchsia_pm.dart]: Done

**Comment by jonahwilliams** [comment]
Landing on red to fix build
