### PR TITLE
Modernize selection menu appearance

### LINKED ISSUE #55049: Material TextSelectionToolbar does not match modern Android UI
Hi,

Flutter is great! But one weakness I have found is text input controls don't match the native user experience in Android. I can see how this is going to be hard to handle because the material style has changed over time. But, I wanted to report it so it can be tracked and hopefully enhanced in a future release of Flutter.

## Steps to Reproduce

1. Add a TextField widget to a simple app.
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(),
      ),
    );
  }
```
2. Select some text and look at the style of the controls:
Screen Shot 2020-04-17 at 12 38 59 PM

3. Compare this to the actual system UI in Android 29, notice the square vs rounded corners:
Screen Shot 2020-04-17 at 12 37 14 PM

<details>
  <summary>(No logs needed)</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/andrewcoutts/Projects/flutter
    • Framework revision d3ed9ec945 (11 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrewcoutts/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/andrewcoutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • Pixel 4                      • 9A311FFAZ00C03                           • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 64 • emulator-5554                            • android-x64   • Android 10 (API 29) (emulator)
    • xFF0C 8                      • d7cab5675167dcdab847995b631648e5c309e1d3 • ios           • iOS 13.3.1
    • iPhone 11 Pro Max            • 75ADC4C9-577F-468A-B5D9-66C1E8634C7A     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
## Description

[Design doc](https://docs.google.com/document/d/1Or32nViSjym0Sk29HccxEzcEITj2oWdielOaeR5cmiY/edit?usp=sharing)

This PR will update the appearance of the Android text selection menu.  Currently, it looks like an older version of Android.

| Flutter before this PR | Native Android |
| --------------------   | --------------- |
| Screen Shot 2020-06-09 at 5 20 02 PM | Screen Shot 2020-06-09 at 5 20 08 PM |

## Flutter after this PR

Screenshot_20200610-120633
Screenshot_20200610-120642

## Related Issues

Closes: https://github.com/flutter/flutter/issues/55049

## Tests

I'll update the existing golden tests.

## Breaking Change

Yes, this will break goldens tests that include the selection menu. Those tests will need to be updated.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 7 untriaged digest(s) on patchset 3.
Please triage them at https://flutter-gold.skia.org/cl/github/59115

**Comment by skia-gold** [comment]
Gold has detected about 10 untriaged digest(s) on patchset 10.
Please triage them at https://flutter-gold.skia.org/cl/github/59115

File: packages/flutter/lib/src/material/material_localizations.dart [hunk 1]
```diff
@@ -870,19 +870,19 @@ class DefaultMaterialLocalizations implements MaterialLocalizations {
...
   @override
   String get okButtonLabel => 'OK';
 
   @override
-  String get pasteButtonLabel => 'PASTE';
+  String get pasteButtonLabel => 'Paste';
 
   @override
-  String get selectAllButtonLabel => 'SELECT ALL';
+  String get selectAllButtonLabel => 'Select all';
```
Comment (justinmc) [inline packages/flutter/lib/src/material/material_localizations.dart:885]: How do I indicate that these strings have been changed and need to have their translations updated?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 2]
```diff
@@ -200,7 +236,10 @@ class _TextSelectionToolbarState extends State<_TextSelectionToolbar> with Ticke
                       : localizations.moreButtonTooltip,
                 ),
               ),
-              ...items,
+              ...itemDatas.map((_ItemData itemData) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/text_selection.dart:239]: nit: a collection for statement that loops from 0 to `itemDatas.length` seems a better fit here? Having side effects like `itemIndex++` is a bit weird in map.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 3]
```diff
@@ -63,11 +78,25 @@ class _TextSelectionToolbarState extends State<_TextSelectionToolbar> with Ticke
...
+      data: ButtonTheme.of(context).copyWith(
+        height: kMinInteractiveDimension,
+        minWidth: kMinInteractiveDimension,
+      ),
+      child: FlatButton(
+        onPressed: itemData.onPressed,
+        padding: EdgeInsets.only(
+          // These values were eyeballed to match the native text selection menu
+          // on a Pixel 2 running Android 10.
+          left: 9.5 + (isFirst ? 5.0 : 0.0),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/text_selection.dart:94]: With `RTL` text direction the extra horizontal padding (5.0) is going to face inward I think. Maybe use `EdgeInsetsDirectional` instead?

File: packages/flutter/lib/src/material/material_localizations.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/material_localizations.dart:885]: Sounds like a @shihaohong or @HansMuller question? I'm interested in knowing the answer too.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 4]
```diff
@@ -173,7 +173,7 @@ void main() {
 
   setUp(() async {
     EditableText.debugDeterministicCursor = false;
-    // Fill the clipboard so that the PASTE option is available in the text
+    // Fill the clipboard so that the Paste option is available in the text
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/text_field_test.dart:176]: nit: the cupertino localization file is not updated so this is probably not needed?

File: packages/flutter/lib/src/material/material_localizations.dart (hunk 1 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/material_localizations.dart:885]: The instructions for adding the strings is a comment at the top of this file. I think there's a script that automatically does that in google3, so long as the default is modified here and in [material_en.arb](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/material_en.arb). 

We should probably update those instructions to include a guide for how to modify existing strings.

Comment (shihaohong) [reply packages/flutter/lib/src/material/material_localizations.dart:885]: I did a quick investigation and whenever Flutter is rolled into google3, material_en.arb is the template that determines what new strings are added or if any existing strings were modified, so make sure to update those as well!

Comment (justinmc) [reply packages/flutter/lib/src/material/material_localizations.dart:885]: Thanks for the help!  I just created a separate PR to add instructions for doing this based on my understanding.  More code review welcome :) https://github.com/flutter/flutter/pull/59273

File: packages/flutter/lib/src/material/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart:239]: Yes that is much better, thanks.  I forgot about the fanciness with for loops in an array.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart:94]: I played around with this in DartPad and it seems that EdgeInsetsDirectional start is what will face inward when the text direction is RTL, so it should be correct as-is.  Let me know if I'm not thinking about this right though. https://dartpad.dartlang.org/98d77d79c6664a4f64968b899836419f

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart:176]: Good point.  I'm going to keep it as Paste for consistency, and because the iOS text selection menu isn't all caps either. It probably should have been Paste before this PR.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_selection.dart:94]: If the direction is `RTL` then in the column the first item in the list will be placed at the right edge with extra padding on its left I think?

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart:94]: In the dartpad if I do `crossAxisAlignment: CrossAxisAlignment.start` on the column and set the text direction to RTL for the column, then the buttons do align right.  In selection menu though, the position of the buttons isn't affected by text direction.  It also seems like when the menu is overflowing and some buttons end up in an overflow menu in a column, they are always aligned left.  Does that make sense or am I missing the case where it doesn't work?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_selection.dart:94]: Oh sorry I thought the buttons will be put in a text direction aware container like a `Row`. Looks like `_TextSelectionToolbarContainer` doesn't care about the text direction. It appears if I turn "force RTL" on in a native android application the menu will flip. I'll file a bug if there isn't one

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart:94]: Thanks!  I didn't realize the menu order flipped on native.

**Comment by Zazo032** [comment]
After this PR, it's looking like this:
Screenshot_20200615-205519

As per the PR description, the selection menu buttons shouldn't be all-caps and text should look a bit bolder. Am I missing something? `Flutter version 1.20.0-1.0.pre.54`, tested on a Pixel 3 XL running Android 11.

Native version, for reference:
Screenshot_20200615-205919

**Comment by justinmc** [comment]
@Zazo032 Thanks for reporting this so quick.  The capitalization won't update right away for non-English locales, unfortunately.  I've deferred that to our usual translation process, just in case there's anything tricky in certain locales. I am double checking that that process is underway so that this problem doesn't make its way to stable or beta.

About the font weight problem, would you be able to open a separate issue with a side by side comparison and the info for the device you're using? Or a PR if you think you can figure out the correct font details. When I was developing this, I used a physical Pixel 2 running Android 10.  I took a screenshot of native and Flutter and then zoomed in and compared side by side until I got something that looked like it matched.  Maybe it looks slightly different based on pixel density of the device, or maybe I just didn't get it perfect.  I admit I don't have the keenest eye for those sorts of things.

**Comment by Zazo032** [comment]
@justinmc thanks for answering, I will try to figure out with a few different devices on recent Android versions and try to open a PR with what I can work out

**Comment by justinmc** [comment]
Thanks, I really appreciate you taking a look!  Let me know if I can help and definitely tag me when you open it.
