### PR TITLE
Fix `SearchAnchor`'s search view isn't updated when the theme changes & widgets inside the search view do not inherit local themes

### LINKED ISSUE #131835: SearchAnchor (search view) UI glitch on platform brightness changes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code sample on Android.
2. Click on SearchBar so that search view and suggestions shows.
3. Switch between dark / light theme.
4. See UI glitch.

### Expected results

Native Flutter widgets should be able to react to platform brightness changes and update accordingly without glitches.

### Actual results

SearchAnchor related widgets doesn't react to platform brightness changes creating a theme mess.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
        ),
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      themeMode: ThemeMode.system,
      home: Scaffold(
        body: SafeArea(
          child: SearchAnchor.bar(
            suggestionsBuilder: (_, __) => [
              Card(
                child: Column(children: [
                  for (var i = 0; i < 50; i++) Text('Hello world'),
                ]),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Screenshot_1691055397

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #132741: Search view widgets cannot inherit local themes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Wrap a `SearchAnchor` or `SearchAnchor.bar` (to open a search view) with a local `Theme`

Run the code sample below.

### Expected results

Widgets in the search view support local themes
Screenshot 2023-08-17 at 15 55 15

### Actual results

Widgets in the search view do not support local themes

Screenshot 2023-08-17 at 15 54 02

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: ThemeMode.system,
      theme: ThemeData(
        brightness: Brightness.light,
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Theme(
          data: ThemeData(
            colorSchemeSeed: Colors.green,
            iconButtonTheme: IconButtonThemeData(
              style: IconButton.styleFrom(
                backgroundColor: Colors.blue,
              ),
            ),
            cardTheme: const CardTheme(
              color: Colors.amber,
            ),
          ),
          child: Align(
            alignment: Alignment.topCenter,
            child: SafeArea(
              child: SearchAnchor.bar(
                suggestionsBuilder: (_, __) => [
                  Card(
                    child: Column(children: [
                      for (var i = 0; i < 50; i++) const Text('Hello world'),
                    ]),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-6.0.pre.27, on macOS 13.5 22G74
    darwin-arm64, locale en-EE)
    • Flutter version 3.14.0-6.0.pre.27 on channel master at
      /Users/tahatesser/Code/flutter
    • Upstream repository git@github.com:TahaTesser/flutter.git
    • FLUTTER_GIT_URL = git@github.com:TahaTesser/flutter.git
    • Framework revision b7046b32db (9 hours ago), 2023-08-17 01:04:23 -0300
    • Engine revision 533670269c
    • Dart version 3.2.0 (build 3.2.0-78.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [SearchAnchor (search view) UI glitch on platform brightness changes](https://github.com/flutter/flutter/issues/131835)
fixes [Search view widgets cannot inherit local themes](https://github.com/flutter/flutter/issues/132741) 

### Description

- This fixes an issue where the `SearchAnchor`'s search view isn't updated when the platform brightness changes.
- Fixes an issue where widgets inside the search view cannot use local themes

### Actual Results

`SearchAnchor` currently passed both global and local themes on the search view popup pushing and it uses anchor. button's context to look up the theme.

search_view drawio (1)

As a result, when the platform changes and the search view is rebuilt, it cannot use the updated theme.

https://github.com/flutter/flutter/assets/48603081/2f1ebe74-e7d5-4ef3-b97c-a741c3d68964

### Expected Results

Similar to `PopupMenuButton`, the theme should be located in the search view so that when the platform brightness is updated and the search view is rebuilt it can use the updated theme.

search_view drawio

https://github.com/flutter/flutter/assets/48603081/d8d85982-c661-4cac-83e8-0488b1d93daf

However, the search view's context cannot access local themes so I added support for `InheritedTheme`, which fixes the local. theme issue for both the search view and widgets inside the search view.

### Before

Screenshot 2023-08-17 at 15 54 02

### After
Screenshot 2023-08-17 at 15 55 15

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/search_anchor_test.dart [hunk 1]
```diff
@@ -2054,6 +2054,117 @@ void main() {
...
+    // Open the search view.
+    await tester.tap(find.byType(SearchBar));
+    await tester.pumpAndSettle();
+
+    // Test the search view background color.
+    final Material searchViewMaterial = getSearchViewMaterial(tester);
+    expect(searchViewMaterial.color, localTheme.colorScheme.surface);
+
+    // Test the search view icons background color.
+     final Material iconButtonMaterial = tester.widget<Material>(find.descendant(
```
Comment (QuncCccccc) [inline packages/flutter/test/material/search_anchor_test.dart:2154]:
```suggestion
    final Material iconButtonMaterial = tester.widget<Material>(find.descendant(
```

File: packages/flutter/test/material/search_anchor_test.dart [hunk 2]
```diff
@@ -2054,6 +2054,117 @@ void main() {
...
+    // Test the search view background color.
+    material = getSearchViewMaterial(tester);
+    expect(material.color, theme.colorScheme.surface);
+  });
+
+  testWidgets('Search view widgets can inherit local themes', (WidgetTester tester) async {
+    final ThemeData globalTheme = ThemeData(colorSchemeSeed: Colors.red);
+    final ThemeData localTheme = ThemeData(
+      colorSchemeSeed: Colors.green,
+        iconButtonTheme: IconButtonThemeData(
```
Comment (QuncCccccc) [inline packages/flutter/test/material/search_anchor_test.dart:2107]:
```suggestion
      iconButtonTheme: IconButtonThemeData(
```

**Review by QuncCccccc — APPROVED** [review]
LGTM! Sorry for the late response as I was on vacation before. I didn't know `InheritedTheme` until this PR. Learned a lot, Thanks! :)

**Comment by QuncCccccc** [comment]
Seems we need to rebase master to fix Google testing:)

**Comment by TahaTesser** [comment]
@QuncCccccc 
Thanks for the review! Sorry for the delay I was on vacation. 
It looks like Google Testing is failing for some reason.

**Comment by QuncCccccc** [comment]
> @QuncCccccc Thanks for the review! Sorry for the delay I was on vacation. It looks like Google Testing is failing for some reason.

No worries at all. I also just came back several days ago from vacation. Can we have another try to rebase master. Not very sure what the problem is.

**Comment by QuncCccccc** [comment]
Hi @TahaTesser! I think @CaseyHillers will help us to fix the Google testing issue:)

**Comment by TahaTesser** [comment]
> Hi @TahaTesser! I think @CaseyHillers will help us to fix the Google testing issue:)

Thank you!

**Comment by CaseyHillers** [comment]
FYI I'm overriding this status. This widget isn't used internally.
