### PR TITLE
[Web][Engine] Update MediaQuery in response to semanticsEnabled

### LINKED ISSUE #134980: [a11y][Web] MediaQuery.accessibleNavigation is not updating when a11y is enabled
Internal bug: b/300777172

[MediaQueryData.accessibleNavigation](https://api.flutter.dev/flutter/widgets/MediaQueryData/accessibleNavigation.html) should update if the accessibility state changes.

This is working on Android/iOS but seems to not work on Web, despite https://github.com/flutter/flutter/issues/67571 being closed.

### Minimal Repro

For this, a button is provided for enabling a11y easily, but the normal user flow would be to use a screen reader to activate the hidden "Enable accessibility" button on a Flutter webpage)

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() => runApp(const MaterialApp(home: MyHomePage()));

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final accessibleNavigation = MediaQuery.of(context).accessibleNavigation;
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                SemanticsBinding.instance.ensureSemantics();
              },
              child: const Text('Enable a11y'),
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: const Text('Should stay visible'),
                    action: SnackBarAction(label: 'Action', onPressed: () {}),
                  ),
                );
              },
              child: const Text('Show snackbar'),
            ),
            const SizedBox(height: 24),
            Text('accessibleNavigation: $accessibleNavigation'),
          ],
        ),
      ),
    );
  }
}
```

</details>

Expected behavior: after enabling a11y, snackbars w/ actions should [no longer auto-dismiss](https://github.com/flutter/flutter/blob/a9183f696c8e12617d05a26b0b5e80035e515f2a/packages/flutter/lib/src/material/scaffold.dart#L579-L583)

Actual behavior: `MediaQueryData.accessibleNavigation` was still false, so the snackbar auto-dismisses. However, resizing the viewport, for whatever reason, does cause the `MediaQueryData.accessibleNavigation` value to update to `true`, and then the correct SnackBar behavior is observed afterward.

Video: [accessible navigation.webm](https://github.com/flutter/flutter/assets/7111741/e136ba47-3cb1-492f-a6d3-c99323432b98)

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/134980

Calling `EnginePlatformDispatcher.instance.invokeOnAccessibilityFeaturesChanged();` after `EnginePlatformDispatcher.instance.configuration = newConfiguration` to notify update configuration event to `MediaQuery`.

before

https://github.com/user-attachments/assets/89969cc7-f9fa-4ac0-8ce0-d026d5676f27

after

https://github.com/user-attachments/assets/8a284d42-e344-4039-8569-8567956326b7

<details>

<summary>Example Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  runApp(const MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                SemanticsBinding.instance.ensureSemantics();
              },
              child: const Text('Enable a11y'),
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: const Text('Should stay visible'),
                    action: SnackBarAction(label: 'Action', onPressed: () {}),
                  ),
                );
              },
              child: const Text('Show snackbar'),
            ),
            const SizedBox(height: 24),
            Text(
              'MediaQuery.accessibleNavigationOf(context): ${MediaQuery.accessibleNavigationOf(context)}',
            ),
            Text(
              'SemanticsBinding.instance.semanticsEnabled: ${SemanticsBinding.instance.semanticsEnabled}',
            ),
            Text(
              'SemanticsBinding.instance.platformDispatcher.semanticsEnabled: ${SemanticsBinding.instance.platformDispatcher.semanticsEnabled}',
            ),
            Text(
              'SemanticsBinding.instance.accessibilityFeatures: ${SemanticsBinding.instance.accessibilityFeatures}',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart [hunk 1]
```diff
@@ -2485,6 +2485,10 @@ class EngineSemantics {
     final PlatformConfiguration newConfiguration = EnginePlatformDispatcher.instance.configuration
         .copyWith(accessibilityFeatures: original.copyWith(accessibleNavigation: value));
     EnginePlatformDispatcher.instance.configuration = newConfiguration;
+    Future.microtask(() {
+      // Avoid executing MediaQuery._updateData during build time
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2489]: This should be done in `MediaQuery` since web engine doesn't know (also shouldn't care ) about the build phase.

Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart]: I fixed code [322d936](https://github.com/flutter/flutter/pull/166836/commits/322d9368ff1776bf7859de04697a981c94e51db7), and update test cases [44d3b5b](https://github.com/flutter/flutter/pull/166836/commits/44d3b5b94c4e31a70e82b4ebd5754b812f62e0de)!

File: packages/flutter/lib/src/semantics/binding.dart [hunk 2]
```diff
@@ -26,7 +26,12 @@ mixin SemanticsBinding on BindingBase {
     platformDispatcher
       ..onSemanticsEnabledChanged = _handleSemanticsEnabledChanged
       ..onSemanticsActionEvent = _handleSemanticsActionEvent
-      ..onAccessibilityFeaturesChanged = handleAccessibilityFeaturesChanged;
+      ..onAccessibilityFeaturesChanged = () {
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/binding.dart:29]: We should do this in Widget MediaQuery, not all the listener here care about build phase.

Also when mediaQuery handles it, it should use postframecallback

```
    if (SchedulerBinding.instance.schedulerPhase == SchedulerPhase.persistentCallbacks) {
      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
        // do the thing.
      }, debugLabel: 'some meaningful label');
    } else {
      // do the thing
    }
```

Comment (koji-1009) [reply packages/flutter/lib/src/semantics/binding.dart:29]: I think shuld all listeners be guarded from the build phase.

If we handle to do this on the MediaQuery side, we would call addPostFrameCallback in the `didChangeAccessibilityFeatures`.
https://github.com/flutter/flutter/blob/3.29.3/packages/flutter/lib/src/widgets/media_query.dart#L1905-L1914

`didChangeAccessibilityFeatures` is public API, so app developers can use this. Therefore, all code that uses `didChangeAccessibilityFeatures` will need to be modified.
https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAccessibilityFeatures.html

If we do the build phase for listeners, there will be no breaking change to the public api. Since this breaking change affects only the web, it is difficult to notice and to understand why it is necessary.

Comment (koji-1009) [reply packages/flutter/lib/src/semantics/binding.dart:29]: The problem occurred with the example code. I don't have that much experience with accessibility implementations, so let me ask: is calling the `ensureSemantics` method `onTap` on a Button a non-recommended implementation?

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  runApp(const MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                SemanticsBinding.instance.ensureSemantics();
              },
              child: const Text('Enable a11y'),
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: const Text('Should stay visible'),
                    action: SnackBarAction(label: 'Action', onPressed: () {}),
                  ),
                );
              },
              child: const Text('Show snackbar'),
            ),
            const SizedBox(height: 24),
            Text(
              'MediaQuery.accessibleNavigationOf(context): ${MediaQuery.accessibleNavigationOf(context)}',
            ),
            Text(
              'SemanticsBinding.instance.semanticsEnabled: ${SemanticsBinding.instance.semanticsEnabled}',
            ),
            Text(
              'SemanticsBinding.instance.platformDispatcher.semanticsEnabled: ${SemanticsBinding.instance.platformDispatcher.semanticsEnabled}',
            ),
            Text(
              'SemanticsBinding.instance.accessibilityFeatures: ${SemanticsBinding.instance.accessibilityFeatures}',
            ),
          ],
        ),
      ),
    );
  }
}
```

Comment (chunhtai) [reply packages/flutter/lib/src/semantics/binding.dart:29]: ok i see the issue now, this is mostly a web issue that it enable the semantics in updatesemantics instead of synchronously when ensureSemanitcs is called.

Can you convert the microtask here to check schedule phase and postframe callback, and add a todo to link to this issue https://github.com/flutter/flutter/issues/158399

That way we can clean it up later when i fix the web engine

Comment (koji-1009) [reply packages/flutter/lib/src/semantics/binding.dart:29]: OK, I'll do it. Thanks for the review.

**Review by chunhtai — APPROVED** [review]
LGTM

File: engine/src/flutter/lib/web_ui/test/engine/window_test.dart [hunk 3]
```diff
@@ -334,6 +334,19 @@ Future<void> testMain() async {
...
+    final Completer<void> completer = Completer<void>();
+    myWindow.onAccessibilityFeaturesChanged = () {
+      completer.complete();
+    };
+
+    expect(EngineSemantics.instance.semanticsEnabled, isFalse);
+    EngineSemantics.instance.semanticsEnabled = true;
+
+    expect(EngineSemantics.instance.semanticsEnabled, isTrue);
+    expect(completer.future.timeout(const Duration(milliseconds: 100)), completes);
```
[the remark this answers is not in the document]
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/test/engine/window_test.dart:347]: I see, thank you.

**Comment by kevmoo** [comment]
Should we flag this `auto-submit`?

**Review by mdebbar — APPROVED** [review]

**Comment by Piinks** [comment]
@pedromassango did you mean to send this for a cherry pick?

**Comment by pedromassango** [comment]
Yes, however, the label was being auto-removed

**Comment by Piinks** [comment]
Ok. I don't know that we are going to do this cherry pick since the change is almost to stable. Usually if an issue is severe enough, cherry picking will be discussed as part of the code review process.

**Comment by Piinks** [comment]
In the future, please confirm the cherry pick before applying the label and triggering the workflow.
