### PR TITLE
Handle dollar signs properly when generating localizations

### LINKED ISSUE #125461: [gen-l10n] Invalid dart file is generated by gen-l10n when (there are no "regular" characters in front of a dollar sign) and (there is a select clause in a message)
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 1. Clone repository https://github.com/mshurkaeu-public/flutter-bugs-I-found-or-reported.git
 2. Switch into branch main.
 3. Navigate to folder 03-gen-l10n-dollar-sign+select-clause.
 4. Run command
 ```bash
 flutter gen-l10n
```
5. Check resulting file .dart_tool/flutter_gen/gen_l10n/app_localizations_en.dart. Methods helloBugManifistation1 and helloBugManifistation2 are generated incorrectly. And thus the whole generated file is invalid.

### Expected results

The generated app_localizations_en.dart file contains correctly escaped dollar sign:

```dart
  @override
  String helloBugManifistation1(String selectPlaceholder) {
    String _temp0 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': 'message',
        'other': 'messageOther',
      },
    );
    return '\$nice_bug\nHello Bug! Manifistation #1 $_temp0';
  }

  @override
  String helloBugManifistation2(String selectPlaceholder) {
    String _temp0 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': '',
        'other': '',
      },
    );
    String _temp1 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': 'message',
        'other': 'messageOther',
      },
    );
    return '${_temp0}\$nice_bug\nHello Bug! Manifistation #2 $_temp1';
  }
```

### Actual results

The generated app_localizations_en.dart file is invalid:

```dart
  @override
  String helloBugManifistation1(String selectPlaceholder) {
    String _temp0 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': 'message',
        'other': 'messageOther',
      },
    );
    return '${nice_bug
Hello Bug! Manifistation #1 }$_temp0';
  }

  @override
  String helloBugManifistation2(String selectPlaceholder) {
    String _temp0 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': '',
        'other': '',
      },
    );
    String _temp1 = intl.Intl.selectLogic(
      selectPlaceholder,
      {
        'case': 'message',
        'other': 'messageOther',
      },
    );
    return '$_temp0${nice_bug
Hello Bug! Manifistation #2 }$_temp1';
  }
```

### Code sample

<details><summary>Full code of the example is available in repository https://github.com/mshurkaeu-public/flutter-bugs-I-found-or-reported.git. Branch main. Folder 03-gen-l10n-dollar-sign+select-clause.</summary>

```json
{
  "helloBugManifistation1": "$nice_bug\nHello Bug! Manifistation #1 {selectPlaceholder, select, case{message} other{messageOther}}",
  "@helloBugManifistation1": {
    "description": "This is a demo #1 of the bug",
    "placeholders": {
      "selectPlaceholder": {
        "type": "String"
      }
    }
  },
  "helloBugManifistation2": "{selectPlaceholder, select, case{} other{}}$nice_bug\nHello Bug! Manifistation #2 {selectPlaceholder, select, case{message} other{messageOther}}",
  "@helloBugManifistation2": {
    "description": "This is a demo #2 of the bug",
    "placeholders": {
      "selectPlaceholder": {
        "type": "String"
      }
    }
  },
  "workaroundTheBug": "\u200B$nice_bug\nHello Bug! A workaround... {selectPlaceholder, select, case{message} other{messageOther}}",
  "@helloBug1": {
    "description": "This is a demo of a workaround for the bug",
    "placeholders": {
      "selectPlaceholder": {
        "type": "String"
      }
    }
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console
flutter --verbose gen-l10n
[  +13 ms] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/home/vboxuser/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] executing: [/home/vboxuser/snap/flutter/common/flutter/] git tag --points-at 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[  +15 ms] Exit code 0 from: git tag --points-at 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
[        ] 3.7.12
[   +9 ms] executing: [/home/vboxuser/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/vboxuser/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +21 ms] executing: [/home/vboxuser/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +14 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +53 ms] Because l10n.yaml exists, the options defined there will be used instead.
           To use the command line arguments, delete the l10n.yaml file in the Flutter project.
           
           
[ +145 ms] "flutter gen-l10n" took 264ms.
[   +1 ms] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on Ubuntu 22.10 5.19.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/vboxuser/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (7 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/vboxuser/Android/Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-40-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by thkim1011**
Currently, the code doesn't properly handle strings which contain dollar signs. The return expression for the generated localization function is computed by `generateReturnExpr` which concatenates several strings, which are either interpolated placeholders, interpolated function calls, or normal strings, but we didn't properly escape dollar signs before sending normal strings to `generateReturnExpr`.

Fixes #125461.

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart [hunk 1]
```diff
@@ -294,7 +294,14 @@ String generateString(String value) {
 /// Given a list of strings, placeholders, or helper function calls, concatenate
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/localizations_utils.dart:294]: Can `expressions` really include "helper function calls"?

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart [hunk 2]
```diff
@@ -294,7 +294,14 @@ String generateString(String value) {
...
 /// them into one expression to be returned.
 ///
-/// If `isSingleStringVar` is passed, then we want to convert "'$expr'" to "expr".
+/// Each of the strings in [expressions] should be a raw string, which, if it were to be added to a dart file,
+/// would be a properly formatted dart string with escapes and/or interpolation. The purpose of this function is to
+/// concatenate these dart strings into a single dart string which can be returned.
+///
+/// The following rules describe all the cases which needs to be handled:
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/localizations_utils.dart:301]:
```suggestion
/// The following rules describe the kinds of string expressions that can be handled: 
```

**Review by christopherfujino — APPROVED** [review]
LGTM thanks for the quick fix!

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart [hunk 3]
```diff
@@ -294,7 +294,14 @@ String generateString(String value) {
...
+/// 1. String with only a single interpolated variable is converted to the variable itself e.g. ["'$expr'"] -> "expr".
+/// 2. If one string ends in an interpolation and the next begins with an alphanumeric character, then the former should
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/localizations_utils.dart:303]: Shouldn't the rules mention an empty string and the reverse of `#2`: 
```dart
["'another string'", "'$expr1'"] -> "'another string'${expr1}".
```

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart (hunk 1 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/localizations_utils.dart:294]: Ah you're right, I think that was an outdated comment from when I used to directly embed helper functions to generate some expressions.

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart (hunk 3 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/localizations_utils.dart:303]: It is acceptable to not put braces in the reverse case since `"'another string$expr1'"` is a valid Dart string. But I'll add a mention of what happens when `expressions` is empty.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by tomassasovsky** [comment]
This broke our use case:

```
    "onboardingDescription": "{count, plural, =0{$onboardingFirstDescription} =1{$onboardingSecondDescription} =2{$onboardingThirdDescription} other{ERROR: onboardingDescription for this index not found}}",
    "@onboardingDescription": {
        "placeholders": {
            "count": {
                "type": "int"
            }
        }
    },
    "onboardingFirstDescription": "View your upcoming and past games. Select a game and record it by pressing the red button.",
    "onboardingSecondDescription": "To record a game follow the set-up instructions. Once finished recording, save and upload later to get it analyzed.",
    "onboardingThirdDescription": "Upload your game's videos in My Recordings.",
```

Used to generate:

  @override
  String onboardingDescription(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'ERROR: onboardingDescription for this index not found',
      two: '$onboardingThirdDescription',
      one: '$onboardingSecondDescription',
      zero: '$onboardingFirstDescription',
    );
    return '$_temp0';
  }
  
  And now generates:
  
    @override
  String onboardingDescription(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'ERROR: onboardingDescription for this index not found',
      two: '\$onboardingThirdDescription',
      one: '\$onboardingSecondDescription',
      zero: '\$onboardingFirstDescription',
    );
    return '$_temp0';
  }
