### PR TITLE
[Material] Add focus, highlight, and keyboard shortcuts to Slider

### LINKED ISSUE #48905: Slider is not focusable when navigating with a keyboard
@goderbauer
@gspencergoog
@lorenzOliveto

Steps to reproduce:
- Create a simple app with a Slider in the center
- Try to navigate the app with a physical keyboard

You can find an example in this repository, https://github.com/lorenzOliveto/flutter_keyboard_navigation_issues (slider_example.dart)

### PR DESCRIPTION
**Pull request by clocksmith**
## Description

* Make the slider focusable and hoverable.
* Create keyboard shortcuts to move the slider

## Related Issues

closes https://github.com/flutter/flutter/issues/48905

## Tests

I added the following tests:

slider.dart:
* focus test
* hover test
* keyboard test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -1210,22 +1211,35 @@ void main() {
       ),
     ));
 
+    await tester.pumpAndSettle();
+
+    debugDumpSemanticsTree(DebugSemanticsDumpOrder.traversalOrder);
```
Comment (goderbauer) [inline packages/flutter/test/material/slider_test.dart:1216]: You're dumping the semantics tree at the wrong place. The test fails in line 1258. You should dump the semantics just before that and from that it seems like line 1258 needs to be changed to something like this:

```
    expect(
        semantics,
        hasSemantics(
          TestSemantics.root(
            children: <TestSemantics>[
              TestSemantics(
                id: 3,
              ),
            ],
          ),
          ignoreRect: true,
          ignoreTransform: true,
        ));
```

Comment (clocksmith) [reply packages/flutter/test/material/slider_test.dart]: Thanks, did not realize there were 2 expects here

File: packages/flutter/lib/src/material/slider.dart [hunk 2]
```diff
@@ -434,6 +454,15 @@ class _SliderState extends State<Slider> with TickerProviderStateMixin {
     );
     enableController.value = widget.onChanged != null ? 1.0 : 0.0;
     positionController.value = _unlerp(widget.value);
+    _shortcutMap = <LogicalKeySet, Intent>{
+      LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowUp): const _AdjustSliderIntent.increment(),
+      LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowDown): const _AdjustSliderIntent.decrement(),
+      LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowLeft): const _AdjustSliderIntent.decrement(),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/slider.dart:460]: Should L/R arrow keys behave oppositely in RTL locales? not sure if there is a standard for this or not.

Actually does the slider itself get mirrored in RTL?

File: packages/flutter/test/material/slider_theme_test.dart [hunk 3]
```diff
@@ -102,10 +102,10 @@ void main() {
     final SliderThemeData sliderTheme = theme.sliderTheme;
 
     await tester.pumpWidget(_buildApp(sliderTheme, value: 0.5, enabled: false));
-    final RenderBox sliderBox = tester.firstRenderObject<RenderBox>(find.byType(Slider));
+    final MaterialInkController material = Material.of(tester.element(find.byType(Slider)));
```
Comment (rami-a) [inline packages/flutter/test/material/slider_theme_test.dart:105]: What is the reason for all these tests to change?

File: packages/flutter/test/material/slider_test.dart [hunk 4]
```diff
@@ -622,104 +623,104 @@ void main() {
 
     await tester.pumpWidget(buildApp());
 
-    final RenderBox sliderBox = tester.firstRenderObject<RenderBox>(find.byType(Slider));
+    final MaterialInkController material = Material.of(tester.element(find.byType(Slider)));
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:626]: Why do the tests check the `MaterialInkController` instead of the `RenderBox` now?

File: packages/flutter/test/material/slider_test.dart [hunk 5]
```diff
@@ -1315,24 +1343,239 @@ void main() {
...
+    await tester.pumpWidget(buildApp(enabled: false));
+    await tester.pumpAndSettle();
+    expect(focusNode.hasPrimaryFocus, isFalse);
+    expect(
+      Material.of(tester.element(find.byType(Slider))),
+      isNot(paints..circle(color: Colors.orange[500])),
+    );
+  });
+
+  testWidgets('Switch can be hovered and has correct hover color', (WidgetTester tester) async {
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:1423]: Slider can be hovered

File: packages/flutter/test/material/slider_test.dart [hunk 6]
```diff
@@ -1315,24 +1343,239 @@ void main() {
...
+    expect(value, 0.55);
+
+    await tester.sendKeyDownEvent(LogicalKeyboardKey.shift);
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
+    await tester.sendKeyUpEvent(LogicalKeyboardKey.shift);
+    await tester.pumpAndSettle();
+    expect(value, 0.5);
+  }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.android,  TargetPlatform.fuchsia, TargetPlatform.linux, TargetPlatform.windows }));
+
+  testWidgets('Slider can be incremented and decremented by keyboard shortcuts', (WidgetTester tester) async {
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:1530]: This test has the same name as the one above, it also looks very similar, is it supposed to be different?

File: packages/flutter/lib/src/material/slider.dart [hunk 7]
```diff
@@ -124,6 +125,8 @@ class Slider extends StatefulWidget {
     this.activeColor,
     this.inactiveColor,
     this.semanticFormatterCallback,
+    this.focusNode,
```
Comment (rami-a) [inline packages/flutter/lib/src/material/slider.dart:128]: Is RangeSlider going to also get this treatment after?

**Review by rami-a — APPROVED** [review]
LGTM with some questions/comments

File: packages/flutter/test/material/slider_theme_test.dart (hunk 3 above)
Comment (clocksmith) [reply packages/flutter/test/material/slider_theme_test.dart:105]: The FocusableActionDetector that wraps the Slider inserts new semantics related render objects so it is more difficult to find the _RenderSlider, but the MaterialInkController can be used to test the same paint methods (This is how Switch does it)

File: packages/flutter/lib/src/material/slider.dart (hunk 2 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/slider.dart:460]: Yes RTL left should be increment and right should be decrement, Updated these controls

File: packages/flutter/test/material/slider_test.dart (hunk 4 above)
Comment (clocksmith) [reply packages/flutter/test/material/slider_test.dart:626]: answered above

File: packages/flutter/test/material/slider_test.dart (hunk 6 above)
Comment (clocksmith) [reply packages/flutter/test/material/slider_test.dart:1530]: It is the same but with different variants. The first is Android, Linux, Fuchsia, Windows) the second is iOS and MacOS

File: packages/flutter/lib/src/material/slider.dart (hunk 7 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/slider.dart:128]: Yes, but I think it will be a little more tricky: https://github.com/flutter/flutter/issues/53958

Comment (gspencergoog) [inline packages/flutter/lib/src/material/slider.dart:128]: Are you also planning on adding the focusColor and hoverColor attributes that are common on other components? It might not be appropriate here, but seems like it could be.

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 8]
```diff
@@ -482,7 +482,8 @@ class SliderThemeData with Diagnosticable {
   /// [Slider] is disabled.
   final Color disabledThumbColor;
 
-  /// The color of the overlay drawn around the slider thumb when it is pressed.
+  /// The color of the overlay drawn around the slider thumb when it is
+  /// pressed, focused, or hovered.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/slider_theme.dart:486]: Most material design elements have different colors for hover and focus, since you want to be able to see the hover when it's already focused, otherwise there's no visible feedback.

File: packages/flutter/lib/src/material/slider.dart (hunk 7 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/slider.dart:128]: Not immediately, the design for the hover and focus was to basically just use the overlay

File: packages/flutter/lib/src/material/slider_theme.dart (hunk 8 above)
Comment (clocksmith) [reply packages/flutter/lib/src/material/slider_theme.dart:486]: This is the material spec from https://material.io/components/sliders/
unnamed

File: packages/flutter/test/material/slider_test.dart [hunk 9]
```diff
@@ -2208,4 +2525,4 @@ testWidgets('Slider Semantics', (WidgetTester tester) async {
       'useV1Slider',
     ]);
   });
-}
+}
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:2528]: Seems like the new line got removed

**Review by rami-a — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/slider_theme.dart (hunk 8 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/slider_theme.dart:509]: OK, I guess if that's the spec.  `¯\_(ツ)_/¯`

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by andraskende** [comment]
I am trying to use slider in a video player on Android TV app, testing on Nvidia Shield TV
just upgraded master, with this change i can now use the slider with remote d-pad, but there is an issue:
slider once focused cant unfocus to other buttons on screen...
d-pad left and bottom rewinds, right and top forwards..... should be left: rewind, right forward,
top and bottom moves to other widgets...
here is my code:
https://github.com/andraskende/apptv1/blob/master/lib/videoplayer.dart#L202-L211
Thanks !!

**Comment by gspencergoog** [comment]
For text fields, we had to add the ignoreTextFields option to the DirectionalFocusIntent to make text fields allow DPAD movement vertically.

Perhaps what we really need is a UI mode that indicates that an app wants to use DPAD navigation instead of normal navigation modes.

**Comment by gspencergoog** [comment]
Actually, after discussing it with @goderbauer, I think I'm going to try and implement an `InheritedWidget` that sets the navigation mode for a subtree (much like `Directionality` does), as he suggested. Then we can use that to determine how to interpret arrow keys differently in cases where the navigation mode is DPAD-based.

**Comment by clocksmith** [comment]
@gspencergoog That sounds like a good idea. Do we have an idea of which components would need to update (and consume this InheritedWidget)?

@andraskende Can you open a separate ticket for adding proper DPAD support for the Slider?

**Comment by gspencergoog** [comment]
For various different reasons, I think this is the list:

 - Slider (for obvious reasons)
 - TextField to handle turning off of up/down cursor movement, similar to slider.
 - All focusable controls that can be disabled, for allowing focus while disabled (see https://github.com/flutter/flutter/issues/54877).

**Comment by gmoraja** [comment]
@gspencergoog on a mobile device, the slider can be correctly navigated with an external keyboard now, but it doesn't receive focus with TalkBack yet.
