### PR TITLE
Fix some intrinsic constraints contract violations.

### LINKED ISSUE #1210: Resizing the space available for an intrinsic width down to almost nothing causes assertions.
### TODO:

- [x] make sure `RenderBlock` honours the constraints contract in its get*Intrinsic* methods.
- [x] add the asserts that `RenderIntrinsicWidth` has to as many other proxying get*Intrinsic* methods as we can, so that we catch the problem much closer to the source next time.

-@Hixie

----

### Original comment
```
-- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
The following exception was raised during performLayout():
'packages/flutter/src/rendering/proxy_box.dart': Failed assertion: line 404: 'width == constraints.constrainWidth(width)' is not true.

The following RenderObject was being processed when the exception was fired:

RenderIntrinsicWidth relayoutSubtreeRoot=up1
That RenderObject had the following owner:
IntrinsicWidth ← Center ← Positioned ← Stack ← ⋯
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      RenderIntrinsicWidth._getInnerConstraints (packages/flutter/src/rendering/proxy_box.dart:404)
#2      RenderIntrinsicWidth.performLayout (packages/flutter/src/rendering/proxy_box.dart:439)
#3      RenderObject.layout (packages/flutter/src/rendering/object.dart:725)

#4      RenderPositionedBox.performLayout (packages/flutter/src/rendering/shifted_box.dart:237)
#5      RenderObject.layout (packages/flutter/src/rendering/object.dart:725)
#6      RenderStackBase.performLayout (packages/flutter/src/rendering/stack.dart:345)
#7      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:632)
#8      RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:610)
#9      BindingBase&Scheduler&Gesturer&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:71)
#10     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:92)
#11     BindingBase&Scheduler&Gesturer&Renderer._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:65)
#12     BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:269)

#13     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:246)
#14     _beginFrame (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
```

### PR DESCRIPTION
**Pull request by Hixie**
RenderBlock wasn't constraining the results.
RenderPadding wasn't constraining the results (which matters
especially when the constraints can't fit the padding in the first
place).
RenderViewport wasn't constraining the results.

Add a test for the block case.

To catch this kind of thing in the future, add some asserts to
debugDoesMeetConstraints() that all four intrinsic functions return
values that are within the constraints.

RenderBlockViewport doesn't support returning intrinsics, so turn off
the "no intrinsic support" asserts (and return zero) when we're doing
this new assert.

This new assert screwed up the custom layout classes' tests, so adjust
those tests to ignore the callbacks invoked from these asserts.

Add to the _debugReportException() method a short summary of the
descendants of this node. It's important to have this information when
debugging errors like these intrinsic constraints contract violations
because often nodes just pass the values through to their child so you
have to go several steps down to find the actual problem.

Fixes https://github.com/flutter/flutter/issues/1210

### CODE REVIEW

File: packages/flutter/test/widget/custom_multi_child_layout_test.dart [hunk 1]
```diff
@@ -11,7 +11,8 @@ class TestMultiChildLayoutDelegate extends MultiChildLayoutDelegate {
   BoxConstraints getSizeConstraints;
 
   Size getSize(BoxConstraints constraints) {
-    getSizeConstraints = constraints;
+    if (!RenderObject.debugInDebugDoesMeetConstraints)
```
Comment (abarth) [inline packages/flutter/test/widget/custom_multi_child_layout_test.dart]: This seems slightly dangerous in that end-developers could easily write code that worked very differently in checked and non-checked mode....  Maybe we should put a note in the exception printout if debugInDebugDoesMeetConstraints is true?  Some sort of hint to help developers figure out what's happening....

**Comment by abarth** [comment]
LGTM

File: packages/flutter/test/widget/custom_multi_child_layout_test.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/test/widget/custom_multi_child_layout_test.dart]: Will do.

Comment (Hixie) [inline packages/flutter/test/widget/custom_multi_child_layout_test.dart]: I added this. What do you think? I'm not sure how to make it more useful.
```dart
        assert(() {
          if (debugInDebugDoesMeetConstraints) {
            debugPrint('This exception was thrown while debugDoesMeetConstraints() was running.');
            debugPrint('debugDoesMeetConstraints() verifies that some invariants are not being');
            debugPrint('violated. For example, it verifies that RenderBox objects are sized in');
            debugPrint('a manner consistent with the constraints provided, and, in addition, that');
            debugPrint('the getMinIntrinsicWidth(), getMaxIntrinsicWidth(), etc, functions all');
            debugPrint('return consistent values within the same constraints.');
          }
          return true;
        });
```

Comment (abarth) [inline packages/flutter/test/widget/custom_multi_child_layout_test.dart]: LGTM
