### PR TITLE
Slider paint incorrectly when the track shape is rectangular

### LINKED ISSUE #64696: Slider paint incorrectly when the track shape is rectangular
## DEMO Screenshot
There are two paint issues:
1. The left side of the active track is less paint.
2. There a gap between the active track and inactive track.

## Sample Code
```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  debugPaintLayerBordersEnabled = true;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(sliderTheme: SliderThemeData(
        trackShape: RectangularSliderTrackShape(),
        trackHeight: 100
      )),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double value = 0.5;
  _onChange(newValue) {
    setState(() {
      print('$newValue');
      value = newValue;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
        child: RepaintBoundary(
          child: SizedBox(
            width: 500,
            height: 200,
            child: Slider(
              value: value,
              onChanged: _onChange,
            ),
          ),
        ),
      ),
    ));
  }
}
```

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

1. The Slider paint incorrectly when the track shape is rectangular, it has a wrong offset.
2. There have a gap between the active track and inactive track, If you increase the height, you can clearly see the gap.
image

This gap was added intended, see #31564, but this process is different from `RoundedRectSliderTrackShape`, so I think we should remove it.

## Related Issues

Fixes #64696

## Tests

I added the following tests:

See files.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -2359,4 +2359,40 @@ void main() {
...
     ]);
   });
+
+  testWidgets('Slider paint correctly when the track shape is rectangular', (WidgetTester tester) async {
+    await tester.pumpWidget(
+      MaterialApp(
+        theme: ThemeData(
+            sliderTheme: const SliderThemeData(
+              trackShape: RectangularSliderTrackShape(),
+            )),
```
Comment (xu-baolin) [inline packages/flutter/test/material/slider_test.dart:2369]: the second `)` should at a new line

**Comment by xu-baolin** [comment]
@HansMuller Hi, please review this change at your convenience, thanks very much!

**Comment by xu-baolin** [comment]
The `RangeSlider` also have a gap when the track shape is Rectangular, I fixed at #64627

**Comment by HansMuller** [comment]
CC @clocksmith @JoseAlba

**Review by JoseAlba — APPROVED** [review]
```
██╗      ██████╗ ████████╗███╗   ███╗
██║     ██╔════╝ ╚══██╔══╝████╗ ████║
██║     ██║  ███╗   ██║   ██╔████╔██║
██║     ██║   ██║   ██║   ██║╚██╔╝██║
███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝
```

File: packages/flutter/test/material/slider_test.dart [hunk 2]
```diff
@@ -2359,4 +2359,41 @@ void main() {
       'inactiveColor: MaterialColor(primary value: Color(0xff9e9e9e))',
     ]);
   });
+
+  testWidgets('Slider paint correctly when the track shape is rectangular', (WidgetTester tester) async {
```
Comment (clocksmith) [inline packages/flutter/test/material/slider_test.dart:2363]: replace with: Slider track paints correctly when the shape is rectangular

File: packages/flutter/test/material/slider_test.dart [hunk 3]
```diff
@@ -2359,4 +2359,41 @@ void main() {
...
+    await tester.pumpWidget(
+      MaterialApp(
+        theme: ThemeData(
+            sliderTheme: const SliderThemeData(
+              trackShape: RectangularSliderTrackShape(),
+            )
```
Comment (HansMuller) [inline packages/flutter/test/material/slider_test.dart:2369]: trailing comma here

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 4]
```diff
@@ -1560,12 +1560,10 @@ class RectangularSliderTrackShape extends SliderTrackShape with BaseSliderTrackS
       isDiscrete: isDiscrete,
     );
 
-    final Size thumbSize = sliderTheme.thumbShape.getPreferredSize(isEnabled, isDiscrete);
-
-    final Rect leftTrackSegment = Rect.fromLTRB(trackRect.left + trackRect.height / 2, trackRect.top, thumbCenter.dx - thumbSize.width / 2, trackRect.bottom);
+    final Rect leftTrackSegment = Rect.fromLTRB(trackRect.left, trackRect.top, thumbCenter.dx, trackRect.bottom);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/slider_theme.dart:1563]: NICE. This is all much more obvious.

**Review by HansMuller — APPROVED** [review]
LGTM
