### PR TITLE
fix DropdownMenu keyboard navigation is broken when expandedInsets is set

### LINKED ISSUE #156712: DropdownMenu keyboard navigation is broken when expandedInsets is set
### Steps to reproduce

1. Run the code sample.
2. Tap on the dropdown in order to open the menu.
3. Press down key.

### Expected results

The first menu entry (labeled 'foo') is highlighted.

### Actual results

No menu entries are highlighted.

If `DropdownMenu.expandedInsets` is not used the keyboard navigation works.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final List<DropdownMenuEntry<String>> menuEntries =
      ["foo", "bar", "green", "yellow"].map((t) => DropdownMenuEntry<String>(label: t, value: t)).toList();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: DropdownMenu<String>(
            expandedInsets: EdgeInsets.zero,
            requestFocusOnTap: true,
            dropdownMenuEntries: menuEntries,
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.24.0-1.0.pre.1340, on Ubuntu 24.04.1 LTS 6.8.0-45-generic, locale fr_FR.UTF-8)
    ! Flutter version 3.24.0-1.0.pre.1340 on channel [user-branch] at /home/bruno/Nevercode/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes keyboard navigation when `DropdownMenu.expandedInsets` is used.
Before this PR the Shortcuts widget defining the navigation intents was only added when `DropdownMenu.expandedInsets` was null.
After this PR, the Shortcuts widget is always added.

## Related Issue

Fixes [DropdownMenu keyboard navigation is broken when expandedInsets is set](https://github.com/flutter/flutter/issues/156712).

## Tests

Adds 2 tests.
Replaces several unneeded 'pumpAndSettle'.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -1159,12 +1159,12 @@ void main() {
     await tester.pump();
 
     await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
-    await tester.pumpAndSettle();
+    await tester.pump();
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_test.dart:1162]: Nice.

**Review by justinmc — APPROVED** [review]
LGTM :+1:
