### PR TITLE
Fix RenderPointerListener needsCompositing propagation from child widgets.

### LINKED ISSUE #32525: RenderPointerListener breaks transforms.
Due to a change in #32025, `RenderPointerListener` started returning a calculated value for `needsCompositing`, but wasn't calling `markNeedsCompositingBitsUpdate` in all cases.

It needs to be fixed to call `markNeedsCompositingBitsUpdate` whenever the value of `MouseTracker.mouseIsConnected` changes.

### PR DESCRIPTION
**Pull request by gspencergoog**
This fixes propagation of `needsCompositing` from child widgets.

When `needsCompositing` is turned on by a child widget, it necessarily sets the `needsCompositing` bit of its parent widget, but `RenderPointerListener` was ignoring that piece of information and only turning on compositing if it thought it needed it for itself.

This corrects that, and adds a test for the condition, and updates a test that was affected by the change.

Fixes #32525 (again)

### CODE REVIEW

File: packages/flutter/test/widgets/keep_alive_test.dart [hunk 1]
```diff
@@ -202,7 +202,7 @@ void main() {
     // The important lines below are the ones marked with "<----"
     expect(tester.binding.renderView.toStringDeep(minLevel: DiagnosticLevel.info), equalsIgnoringHashCodes(
       'RenderView#00000\n'
-      ' │ debug mode enabled - ${Platform.operatingSystem}\n'
+      ' │ debug mode enabled - linux\n'
```
Comment (dkwingsmt) [inline packages/flutter/test/widgets/keep_alive_test.dart]: Can you explain the cause of this change? Was it wrong to not having broken before?

Comment (gspencergoog) [reply packages/flutter/test/widgets/keep_alive_test.dart]: No, it's just a cut/paste error when updating the golden string here.  Fixed.

**Review by dkwingsmt — APPROVED** [review]
