### PR TITLE
[Android] remove obsolete gradle api in FGP

### LINKED ISSUE #170791: Flutter tool throws `Unresolved reference 'fileMode'.` and `'fun String.toLowerCase(): String' is deprecated. Use lowercase() instead.` while running on Android Studio Narwhal Canary and RC versions.
### Steps to reproduce

Error：e: file:///D:/flutter/Android/flutter-sdk/flutter-sdk-beta/packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:717:21 Unresolved reference 'fileMode'.

UpGradle Android Studio Narwhal Feature Drop | 2025.1.2 Canary 5 & flutter sdk to Flutter 3.33.0-0.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 1db45f7408 (3 weeks ago) • 2025-05-29 10:05:06 -0700
Engine • revision 308a517184 (4 weeks ago) • 2025-05-23 15:32:17 -0700
Tools • Dart 3.9.0 (build 3.9.0-100.2.beta) • DevTools 2.46.0

### Expected results

no error

### Actual results

Error：e: file:///D:/flutter/Android/flutter-sdk/flutter-sdk-beta/packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:717:21 Unresolved reference 'fileMode'.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.33.0-0.2.pre, on Microsoft Windows [版本 10.0.26100.4202], locale zh-CN)
[√] Windows Version (Windows 11 or higher, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.7)
[√] Android Studio (version 2025.1.1)
[√] Android Studio (version 2025.1.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by Sameri11**
fixes #170791 

This PR replaces the deprecated (and removed in 9.0) Gradle fileMode API in favor of filePermissions. 
This change finally unlocks builds with gradle 9 (confirmed in smoke tests, 9.0.0-rc.2 is the latest prerelease version to the date).

**Testing strategy**

There's an attempt to add a Kotlin unit test that confirms that `filePermissions` were called during plugin application. I failed to find a more precise way to check if the new code works as intended (such as testing that permissions were really changed or something like that), but on the other hand, it should not be required since it will transform the test in a way that it will start to test Gradle APIs and their behavior, and I believe it's a bit out of scope: Gradle APIs are tested in Gradle tests :)

Anyway, this new test is a bit cumbersome because it's required to mock all the behaviours related to variants configuration and capturing calls – If it is not desired im not hesitant to remove it.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt [hunk 1]
```diff
@@ -755,10 +755,12 @@ class FlutterPlugin : Plugin<Project> {
                 ) {
                     dependsOn(compileTask)
                     with(compileTask.assets)
-                    // TODO(gmackall): Replace with filePermissions.user.read/write = true once
-                    //   minimum supported Gradle version is 8.3.
-                    @Suppress("DEPRECATION")
-                    fileMode = 420 // corresponds to unix 0644 in base 8
+                    filePermissions {
+                        user {
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:759]: Is this actually needed? 
"FILE: read &write for OWNER, read for GROUP, read for OTHER (0644, rw-r--r--)" 
https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.file/-file-permissions/index.html

**Review by reidbaker — APPROVED** [review]

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt (hunk 1 above)
Comment (Sameri11) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:759]: Interesting question, because in Copy task docs:
"If the property has no value set, that means that existing permissions are preserved." https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html

I don't know how exactly these 2 parts corresponds to each other, best guess is that your link describes behavior out of context of Copy task?

Comment (reidbaker) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:759]: That is Weird. LGTM Thank you for expanding test coverage.

**Review by gmackall — APPROVED** [review]
