### PR TITLE
Fix: Added `margin` parameter for `MaterialBanner` class

### LINKED ISSUE #118704: Proposal to add `margin` to MaterialBanner constructor
## Use case

I would like to put an outer margin on the material banner.

```
Line 296 - 297:
    Widget materialBanner = Container(
      margin: EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0),

For example:
 const MaterialBanner({
    super.key,
    required this.content,
    this.contentTextStyle,
    required this.actions,
    this.elevation,
--> this.margin
```

## Proposal
The goal is to get the Material banner with outer margin to get the design like this:
Screenshot 2023-01-18 at 17 01 19

### PR DESCRIPTION
**Pull request by hasnentai**
This PR adds a `margin` parameter in the `MaterialBanner` class since there was no direct way to get a margin around the `MaterialBanner`. The margin was hardcoded previously, and now it's parameterised.

Fixes #118704 

Code Sample 
```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const MaterialBanner(
        elevation: 40,
        margin: EdgeInsets.fromLTRB(20, 30, 10, 50), // new add margin param
        content: Text("Hello"),
        actions: [
          TextButton(
            onPressed: null,
            child: Text("Ok"),
          )
        ],
      ),
    );
  }
```

ScreenShot of `MaterialBanner` with `margin`
Screenshot 2023-01-23 at 4 51 22 PM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/banner.dart [hunk 1]
```diff
@@ -188,6 +189,9 @@ class MaterialBanner extends StatefulWidget {
   /// `EdgeInsetsDirectional.only(start: 16.0, top: 2.0)`.
   final EdgeInsetsGeometry? padding;
 
+  /// Empty space to surround the [MaterialBanner].
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/banner.dart:192]: Please add a blank line and then explain what the default is.

File: packages/flutter/test/material/banner_test.dart [hunk 2]
```diff
@@ -1105,6 +1105,27 @@ void main() {
...
+            TextButton(
+              child: const Text('Action'),
+              onPressed: () { },
+            ),
+          ],
+        ),
+      ),
+    );
+
+  final Container materialContainer = tester.widget<Container>(find.descendant(of: find.byType(MaterialBanner), matching: find.byType(Container)).first);
```
Comment (HansMuller) [inline packages/flutter/test/material/banner_test.dart:1126]: This is OK but makes the test unnecessarily depend on an implementation detail (that margin is implemented with a Container). It would be better to verify that the bounds of the banner are what's expected when the banner is displayed.

**Review by HansMuller — COMMENTED** [review]
This looks pretty good, just needs some tweaks.

File: packages/flutter/lib/src/material/banner.dart (hunk 1 above)
Comment (hasnentai) [reply packages/flutter/lib/src/material/banner.dart:192]: Hello Hans Muller,
I have added a blank line along with a comment of default value

File: packages/flutter/test/material/banner_test.dart (hunk 2 above)
Comment (hasnentai) [reply packages/flutter/test/material/banner_test.dart]: I have used the same approach that other tests are using in `banner_test.dart`
I have written a test which finds the material and then gets the bounds of the material.

File: packages/flutter/lib/src/material/banner.dart [hunk 3]
```diff
@@ -185,6 +186,12 @@ class MaterialBanner extends StatefulWidget {
...
+  ///
+  /// If the [margin] is null then this defaults to
+  /// `EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0)`.
```
Comment (hasnentai) [inline packages/flutter/lib/src/material/banner.dart:192]: Added a comment here

File: packages/flutter/test/material/banner_test.dart [hunk 4]
```diff
@@ -1105,6 +1105,27 @@ void main() {
...
+            TextButton(
+              child: const Text('Action'),
+              onPressed: () { },
+            ),
+          ],
+        ),
+      ),
+    );
+
+    final Offset topLeft = tester.getTopLeft(find.descendant(of: find.byType(MaterialBanner), matching: find.byType(Material)).first);
```
Comment (hasnentai) [inline packages/flutter/test/material/banner_test.dart:1126]: I have used the same approach that other tests are using in `banner_test.dart`, Getting Material from the banner and checking the offset of the material.

File: packages/flutter/lib/src/material/banner.dart (hunk 3 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/banner.dart:192]:
```suggestion
 0 if the banner's [elevation] is 0, 10 otherwise.
```

**Review by HansMuller — COMMENTED** [review]
This looks good, just one more tiny tweak and I think we can land it.

File: packages/flutter/lib/src/material/banner.dart (hunk 3 above)
Comment (hasnentai) [reply packages/flutter/lib/src/material/banner.dart:192]: Sure 
Thanks for the edit

Comment (hasnentai) [reply packages/flutter/lib/src/material/banner.dart]: Added and pushed

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/banner.dart [hunk 5]
```diff
@@ -318,6 +326,7 @@ class _MaterialBannerState extends State<MaterialBanner> {
     );
 
     final double elevation = widget.elevation ?? bannerTheme.elevation ?? 0.0;
+    final EdgeInsetsGeometry margin = widget.margin ?? EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/banner.dart:329]: I think it would be more clear to use `EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0)` as the default value for `widget.margin` in the constructor, and to document it as such.  That way users know what they're getting if they don't set this, or if they want to change it slightly.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM, but see my comment.  I think that should be done if you agree.

File: packages/flutter/lib/src/material/banner.dart (hunk 5 above)
Comment (hasnentai) [reply packages/flutter/lib/src/material/banner.dart:329]: Hi @justinmc Thanks for your valuable input. Shall I go ahead and mak the changes?

Comment (justinmc) [reply packages/flutter/lib/src/material/banner.dart:329]: Yes please!

Comment (HansMuller) [reply packages/flutter/lib/src/material/banner.dart:329]: We make the constructor parameters null by default to allow themes to specify an override for the default value. Although there's no MaterialBannerTheme now, if we added one in the future, this default parameter would get in the way. For now having the constructor parameters be null by default is still useful, since it makes them consistent with the rest of the Material library's components.

Comment (justinmc) [reply packages/flutter/lib/src/material/banner.dart:329]: My mistake, that's right!  I think this is fine as-is then.

Comment (hasnentai) [reply packages/flutter/lib/src/material/banner.dart:329]: Having all constructors consistent in Material Library's components makes a lot of sense.  It might help a lot in future adaptability as @HansMuller mentioned.
@justinmc I  will keep the implementation the same as before and not make the changes for now.
@HansMuller Let me know if I should make the changes from the null value in the constructor to the default value of `margin` to `EdgeInsets.only(bottom: elevation > 0 ? 10.0: 0.0)`
