### PR TITLE
Fix monodrag gestures for #112403 and b/249091367

### LINKED ISSUE #112403: DragGestureRecognizer.acceptGesture null check operator used on a null value
Framework crash from internal [b/249091367](https://b.corp.google.com/249091367)

```
UnknownError: Null check operator used on a null value
at DragGestureRecognizer.acceptGesture(monodrag.dart:334)
at GestureArenaManager._resolveByDefault(arena.dart:251)
at GestureArenaManager._tryToResolveArena.<anonymous closure>(arena.dart:232)
at _rootRun(zone.dart:1418)
at _rootRun(zone.dart:1417)
at _CustomZone.run(zone.dart:1328)
at _CustomZone.runGuarded(zone.dart:1236)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1276)
at _rootRun(zone.dart:1426)
at _rootRun(zone.dart:1417)
at _CustomZone.run(zone.dart:1328)
at _CustomZone.runGuarded(zone.dart:1236)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1276)
at _microtaskLoop(schedule_microtask.dart:40)
at _startMicrotaskLoop(schedule_microtask.dart:49)
at _startMicrotaskLoop(schedule_microtask.dart:44)
```

Although the line numbers are different (I'm not sure the exact framework version used in the app this stacktrace is from), I'm pretty sure it's this line: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/monodrag.dart#L367

```dart
      final Duration timestamp = _lastPendingEventTimestamp!;
```

It's difficult to reason about how we got into this state, but maybe the easiest fix would be to just let `_checkStart(timestamp, pointer)` be a no-op when `timestamp == null`, WDYT @dkwingsmt?

### PR DESCRIPTION
**Pull request by dnfield**
Re-attempts #121553, which itself was another attempt at https://github.com/flutter/flutter/pull/117551

Fixes https://github.com/flutter/flutter/issues/112403 and b/249091367

I am not super familiar with our gesture recognizer API, so I tried to tag some people here who are probably more familiar and can help me out if my unit test is doing something super weird. My main  goal here was just to have _a_ test that covers the bad behavior. Unfortunately, reporters of this bug don't have clear repros, they just have bug reports from the field about null checks going wrong.

@reidbaker FYI - this is a slightly different take on the PR you opened yesterday.
@jmagman FYI as well since youc ommented on the PR yesterday.

### CODE REVIEW

File: packages/flutter/test/gestures/monodrag_test.dart [hunk 1]
```diff
@@ -10,6 +10,31 @@ import 'gesture_tester.dart';
 void main() {
   TestWidgetsFlutterBinding.ensureInitialized();
 
+  test('acceptGesture tolerates a null lastPendingEventTimestamp', () {
+    // Regression test for https://github.com/flutter/flutter/issues/112403
+    // and b/249091367
+    final DragGestureRecognizer recognizer = VerticalDragGestureRecognizer();
+    const PointerDownEvent event = PointerDownEvent(timeStamp: Duration(days: 10));
+
+    expect(recognizer.debugLastPendingEventTimestamp, null);
```
Comment (goderbauer) [inline packages/flutter/test/gestures/monodrag_test.dart:19]: In theory, this test would work without exposing (and checking) debugLastPendingEventTimestamp. If the bug were to be re-introduced, it would still crash on line 34, no?

I think I would prefer that over exposing the debug field.

File: packages/flutter/test/gestures/monodrag_test.dart [hunk 2]
```diff
@@ -10,6 +10,31 @@ import 'gesture_tester.dart';
...
+    // Normal case: acceptGesture called and we have a last timestamp set.
+    recognizer.acceptGesture(event.pointer);
+    expect(recognizer.debugLastPendingEventTimestamp, null);
+
+    // Reject the gesture to reset state and allow accepting it again.
+    recognizer.rejectGesture(event.pointer);
+    expect(recognizer.debugLastPendingEventTimestamp, null);
+
+    // Not entirely clear how this can happen, but the bugs mentioned above show
+    // we can end up in this state empircally.
```
Comment (goderbauer) [inline packages/flutter/test/gestures/monodrag_test.dart:33]: This would really be interesting to figure out... Wondering if that's a bug somewhere in the framework in how we use the gesture detector, or in user code, or do the embedders send bogus events??

(Not actionable for this PR)

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/gestures/monodrag_test.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/test/gestures/monodrag_test.dart:19]: It would crash, but it wouldn't actually be asserting anything besides that methods can be called.

My main concern over not exposing the field is that someone would be able to easily refactor the internals of the class and the test would still pass but they'd re-introduce the failure case. This actually asserts that `acceptGesture` can tolerate that field being null.

File: packages/flutter/test/gestures/monodrag_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/gestures/monodrag_test.dart:33]: Yes, I suspect there's something off here but I don't know that subsystem well enough to know. I'm half hoping one of the people I tagged on this PR will know :)
