### PR TITLE
Increases the eyeballed value of auto scroll velocity scalar

### LINKED ISSUE #121603: ReorderableListView scroll while dragging is too slow
After upgrading from flutter 3.3.10 to the latest stable I noticed that the behavior of `ReorderableListView` has changed: while dragging and holding an item close to the edge of the screen the scroll velocity is much slower than it used to be.

## Steps to Reproduce

Just use the [example](https://api.flutter.dev/flutter/material/ReorderableListView-class.html#material.ReorderableListView.1) from the documentation:

`flutter create --sample=material.ReorderableListView.1 mysample`

I have tested using the latest `master`

### **Expected results:** (pixel 3)

https://user-images.githubusercontent.com/13722041/221864749-8466b3d5-3ac3-4e98-a1ca-a3006b33732e.mp4

### **Actual results:** (pixel 3)

https://user-images.githubusercontent.com/13722041/221864793-8e95fa4b-89fe-4360-bc69-def0716fc863.mp4

<details>
<summary>flutter --doctor</summary>

```

[!] Flutter (Channel master, 3.8.0-17.0.pre.43, on macOS 12.6 21G115 darwin-arm64, locale en)
    • Flutter version 3.8.0-17.0.pre.43 on channel master at /Users/gcalbi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/gcalbi/fvm/versions/3.3.10/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/gcalbi/fvm/versions/master. Consider adding
      /Users/gcalbi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/gcalbi/fvm/versions/3.3.10/bin/dart, which is not inside your current Flutter SDK checkout at /Users/gcalbi/fvm/versions/master. Consider adding
      /Users/gcalbi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f032a4d648 (3 hours ago), 2023-02-28 05:29:29 -0500
    • Engine revision c6b5322404
    • Dart version 3.0.0 (build 3.0.0-277.0.dev)
    • DevTools version 2.22.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/gcalbi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/gcalbi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 69.0.3
    • Dart plugin version 213.7371

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/222.3345.118/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/212.4746.92/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Pixel 3 (mobile)            • 192.168.1.70:41685                   • android-arm64 • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 13 (API 33) (emulator)
    • iPhone 14 (mobile)          • 72AD79DC-83CE-4992-B982-47A95074BAEE • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
A previous pr fixed an bug in the autoscalar's speed calculation. The calculation would produce much lower speed after the fix. This pr raised the default scalar value for reorderable list.

fixes https://github.com/flutter/flutter/issues/121603

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -450,13 +452,17 @@ class SliverReorderableList extends StatefulWidget {
...
+    double? autoScrollerVelocityScalar,
+  }) : autoScrollerVelocityScalar = autoScrollerVelocityScalar ?? _kDefaultAutoScrollVelocityScalar,
+       assert(itemCount >= 0),
        assert(
          itemExtent == null || prototypeItem == null,
          'You can only pass itemExtent or prototypeItem, not both',
        );
 
+  // An eyeballed value for a smooth scrolling experience.
+  static const double _kDefaultAutoScrollVelocityScalar = 50;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:464]: Woo! Wicked fast now!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
