### PR TITLE
[flutter_tools] Fix type error in ChromiumDevice.startApp

### LINKED ISSUE #111877: [tool_crash] _TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))
```
#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart)
#1      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:305:31)
<asynchronous suspension>
#2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.337, on Microsoft Windows [Version 10.0.22000.978], locale en-ID)
    • Flutter version 3.4.0-19.0.pre.337 on channel master at F:\Programming Project\Flutter SDK\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 085a187e04 (10 hours ago), 2022-09-18 21:11:34 -0400
    • Engine revision b22a795011
    • Dart version 2.19.0 (build 2.19.0-214.0.dev)
    • DevTools version 2.17.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at F:\Android_SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = F:/Android_SDK
    • ANDROID_SDK_ROOT = F:\Android_SDK\commandlinetools-win-8512546_latest\cmdline-tools\bin
    • Java binary at: F:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at F:\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at E:\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 105.0.1343.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 069f5042973dc4aafbf76a44ca14af7c0e2c2ca1

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/111877

The issue was that the method declaration in the super class (`Device.startApp`) specifies `covariant ApplicationPackage?`, while the sub-class (`ChromiumDevice.startApp`) declares it `covariant WebApplicationPackage`, which is non-nullable. However, because of https://github.com/flutter/flutter/pull/55531, it is possible to run a Flutter app on a browser device even if the project does not specify a web target; thus, package could legitimately be null. However, `ChromiumDevice.startApp` specifies a non-nullable parameter, it is a runtime error. This was likely introduced during a null-safety migration, so this restores this functionality by making the parameter nullable (note that `ChromiumDevice.startApp` does not even reference the argument).

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/web_device.dart [hunk 1]
```diff
@@ -118,7 +118,7 @@ abstract class ChromiumDevice extends Device {
 
   @override
   Future<LaunchResult> startApp(
-    covariant WebApplicationPackage package, {
+    WebApplicationPackage? package, {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/web/web_device.dart:121]: not directly relevant to the fix, but this type doesn't need to be covariant, as sub-classes will use the exact same type

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/web/web_device.dart:121]: Is this true? Or is it because it has been labeled `covariant` in the base class definition here: https://github.com/flutter/flutter/blob/b70ff4f280ebe0819a9af79e8412a40eb643f5ae/packages/flutter_tools/lib/src/device.dart#L591-L604

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/web/web_device.dart:121]: Is what true? That the type doesn't need to be covariant? Or that it's not relevant to the fix?

**Comment by eliasyishak** [comment]
LGTM

**Review by eliasyishak — APPROVED** [review]

File: packages/flutter_tools/lib/src/web/web_device.dart (hunk 1 above)
Comment (eliasyishak) [reply packages/flutter_tools/lib/src/web/web_device.dart:121]: Is it true that a subtyped class can be passed as a valid parameter to a method.

Meaning I don't think because `WebApplicationPackage` is a subtype of `ApplicationPackage` that we can pass it as a valid type to the `startApp` method. But it works because we marked the type on super class a `covariant`

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/web/web_device.dart:121]: We sync'd offline. To clarify my original statement, I can remove the `covariant` from the `ChromiumDevice.startApp` implementation because the super class has it marked `covariant`. TIL that covariant can be placed in either the superclass or subclass: https://dart.dev/guides/language/sound-problems#the-covariant-keyword
