### PR TITLE
Make RawKeyboard assert when no keys are in keysPressed when sending a key down event.

### LINKED ISSUE #63353: Exception in shortcuts while using the widget inspector
Not sure how to repro, unfortunately, but hopefully the stack trace is helpful...

## Stack trace

```
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:77:16)
#3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
#4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:181:63)
#5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:309:63)
#6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
...
```

## Other info

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.120, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-8.0.pre.120 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 4500a451dc (26 hours ago), 2020-08-08 18:21:45 -0700
    • Engine revision d7c98913ed
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0aa5b0f019)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode_11.2.1.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

/cc @gspencergoog

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This adds an assert in `RawKeyboard` that catches the case where it tries to send a key down event, but (after synchronizing modifiers) there are no keys in `keysPressed`.  This state can occur if the modifier flags are not set properly for the platform.

Also prevents shortcuts attempting to handle a key down when no keys are pressed at the moment (which was causing a crash in release mode).

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/63353

## Tests

- Added a test that checks this case.

## Breaking Change

- [X] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
The code looks fine, but why would this happen in the first place? Patching it here seems dangerous to me, especially to a case that we don't know how to repro.

File: packages/flutter/lib/src/widgets/shortcuts.dart [hunk 1]
```diff
@@ -306,7 +306,18 @@ class ShortcutManager extends ChangeNotifier with Diagnosticable {
       return false;
     }
     assert(context != null);
-    final LogicalKeySet keySet = keysPressed ?? LogicalKeySet.fromSet(RawKeyboard.instance.keysPressed);
+    LogicalKeySet keySet = keysPressed;
+    if (keySet == null) {
+      if (RawKeyboard.instance.keysPressed.isNotEmpty) {
+        keySet = LogicalKeySet.fromSet(RawKeyboard.instance.keysPressed);
+      } else {
+        // Somehow we received a key down event when no keys were down.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/shortcuts.dart:314]: a fly by comment, shouldn't we assert in this case to indicate whoever simulating the keys event are doing it wrong?

**Comment by gspencergoog** [comment]
One repro is the one I mentioned above (I added a test for that), where something is setting incorrect modifier flags.

It can also happen with "unknown" keys that are modifier keys.  For instance, [in this case](https://github.com/flutter/flutter/issues/60922#issuecomment-666873325) the Gtk implementation doesn't set the caps lock modifier flag properly yet, so it removes the caps lock from the list of pressed keys when it synchronizes the modifiers, resulting in a key down where no keys are pressed.

I could go the route of making it an assert, but maybe it should be earlier, checking to see if no keys are pressed when a key down event is being propagated, and then dumping a bunch of info about that state when it asserts.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
I guess this is the only approach available under  the current structure, but I'm worried all these will have to be rewritten into the respective engine once we move to the platform specific API, and all these tests will be invalidated.

**Comment by chunhtai** [comment]
> One repro is the one I mentioned above (I added a test for that), where something is setting incorrect modifier flags.
> 
> It can also happen with "unknown" keys that are modifier keys. For instance, [in this case](https://github.com/flutter/flutter/issues/60922#issuecomment-666873325) the Gtk implementation doesn't set the caps lock modifier flag properly yet, so it removes the caps lock from the list of pressed keys when it synchronizes the modifiers, resulting in a key down where no keys are pressed.
> 
> I could go the route of making it an assert, but maybe it should be earlier, checking to see if no keys are pressed when a key down event is being propagated, and then dumping a bunch of info about that state when it asserts.

If there is indeed a use case where this is unavoidable, this approach looks good.

**Comment by gspencergoog** [comment]
OK, how about this version: it will assert in debug, but not crash in release.

And I agree, this isn't ideal. The best thing would be to catch this much earlier in the engine and do something intelligent.  Doing the right thing should be easier once the platform side is the one deciding what to put into the (platform-independent) key down event.

File: packages/flutter/lib/src/widgets/shortcuts.dart [hunk 2]
```diff
@@ -306,7 +306,19 @@ class ShortcutManager extends ChangeNotifier with Diagnosticable {
...
     assert(context != null);
-    final LogicalKeySet keySet = keysPressed ?? LogicalKeySet.fromSet(RawKeyboard.instance.keysPressed);
+    LogicalKeySet keySet = keysPressed;
+    if (keySet == null) {
+      assert(RawKeyboard.instance.keysPressed.isNotEmpty,
+        'Received a key down event when no keys are in keysPressed. '
+        "This state can occur if the key event being sent doesn't properly "
+        'set its modifier flags. This was the event: $event and its data: '
+        '${event.data}');
+      if (RawKeyboard.instance.keysPressed.isNotEmpty) {
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/shortcuts.dart:316]: Do you mean this should crash in debug mode but pass in release mode? I kind of get the intention, but still why would anyone release a piece of code that crashes in debug mode?

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/shortcuts.dart:316]: The reason is that unless they press the key that causes the problem during their testing, they won't know that it crashes in debug mode.

And I don't think an invalid key sequence should crash the app in release mode: it can be ignored if it gets that far.

Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/shortcuts.dart:316]: Sounds good :)

Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/shortcuts.dart:316]: Maybe you can add this to the comment. Your explanation is pretty helpful.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/shortcuts.dart:318]: OK, sounds good, added a comment.
