### PR TITLE
Make sure Opacity widgets/layers do not drop the offset

### LINKED ISSUE #71008: RenderAnimatedOpacityMixin causes child pixel snapping when fully opaque
`RenderAnimatedOpacityMixin` has the following paint method, which avoids painting both the child widget and the opacity later when fully transparent. When fully opaque, the opacity layer is elided while the child is painted. Unfortunately this last optimization causes obvious pixel snapping on low DPR screens. 

`RenderAnimatedOpacityMixin.paint`
```dart
 @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      if (_alpha == 0) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        return;
      }
      if (_alpha == 255) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        context.paintChild(child!, offset);
        return;
      }
      assert(needsCompositing);
      layer = context.pushOpacity(offset, _alpha!, super.paint, oldLayer: layer as OpacityLayer?);
    }
  }
```

This can be seen fairly easily when a mouse hover first reveals a tooltip, such as in the "example app" section of the flutter gallery. The last frame visible shifts - fairly dramatically compared to the previous animation. Though the video below uses 10x time dilation to make it more obvious, it is still hard to see in the low res/low framerate GIF. 

ezgif-6-2fad4fb28e3e (1)

Keeping the opacity layer even when at fully opaque removes this jump.

### LINKED ISSUE #89255: OpacityLayer should be a subclass of OffsetLayer
They both contain offsets, and have duplicated code for calculating transforms.

We also have a bug where debug disabling opacity places the child in the wrong part of the screen, because really we should be pushing an offset layer instead of an opacity layer in that case.

Fixing this could help resolve https://github.com/flutter/flutter/issues/71008

### PR DESCRIPTION
**Pull request by dnfield**
fixes https://github.com/flutter/flutter/issues/89255 
fixes https://github.com/flutter/flutter/issues/71008

Now, instead of dropping the opacity layer when it is either disabled or the value is opaque, it uses an OffsetLayer instead. This avoids _some_ of the memory regression from https://github.com/flutter/flutter/pull/83145, because the engine special cases `OpacityLayers` to always raster cache them, but does not do quite the same with `OffsetLayers`.

I did see some regression on mean/median on the internal benchmark, but overall the values are still within the range of the change without this PR.

/cc @xster

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/89264

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/89264

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89264

File: packages/flutter/lib/src/rendering/layer.dart [hunk 1]
```diff
@@ -1795,24 +1781,32 @@ class OpacityLayer extends ContainerLayer {
       return true;
     }());
 
-    if (enabled)
+    final int realizedAlpha = alpha!;
+    // The type assertions work because the [alpha] setter nulls out the
+    // engineLayer if it would ahve changed type (i.e. changed to or from 255).
```
Comment (xu-baolin) [inline packages/flutter/lib/src/rendering/layer.dart:1786]: `ahve` -> have

File: packages/flutter/test/rendering/debug_test.dart [hunk 2]
```diff
@@ -208,4 +208,30 @@ void main() {
     expect(error, isNull);
     debugPaintSizeEnabled = false;
   });
+
+  test('debugDisableOpacity keeps things in the right spot', () {
```
Comment (xu-baolin) [inline packages/flutter/test/rendering/debug_test.dart:212]: Without this patch, this test can pass also, right?

Comment (dnfield) [reply packages/flutter/test/rendering/debug_test.dart:212]: The container gets rendered in the wrong location without this patch

Comment (dnfield) [reply packages/flutter/test/rendering/debug_test.dart:212]: Err, sorry - without this change, there'd be no `OpacityLayer`, the `PictureLayer` would be the `firstChild` of `rootLayer`.

Comment (xu-baolin) [reply packages/flutter/test/rendering/debug_test.dart:212]: It passes with the latest master branch.

Comment (dnfield) [reply packages/flutter/test/rendering/debug_test.dart:212]: Ahh you are right. This would need to test that the add to scene does the right thing. But the golden test does that without getting into such implementation details. I'll remove this test.

Comment (xu-baolin) [reply packages/flutter/test/rendering/debug_test.dart:212]: It isn't bad to remain this ^^

Comment (Piinks) [reply packages/flutter/test/rendering/debug_test.dart:212]: I agree, it's not bad to keep this test, even if it passes without this change and has coverage in a golden file test. I think it's never bad to have another test. :)

**Review by Piinks — APPROVED** [review]
LGTM with typo @xu-baolin spotted

File: packages/flutter/lib/src/rendering/layer.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart]: Ahh thanks, fixed. I also noticed in the setter above I was accessing the gettr instead of the instance var. Changed that too.

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/89264

File: packages/flutter/test/rendering/debug_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/rendering/debug_test.dart:212]: Left it in :)

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/89264

**Comment by dnfield** [comment]
This changes some internal goldens in an expected manner, since there's no longer the pixel snapping going on at the end of an opacity animation. /cc @renyou @angjieli - this looks like it affected about 170 golden files internally in a smoke test. I assume it will be more in a full TGP.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 3]
```diff
@@ -1764,28 +1764,14 @@ class OpacityLayer extends ContainerLayer {
   set alpha(int? value) {
     assert(value != null);
     if (value != _alpha) {
+      if (value == 255 || _alpha == 255) {
+        engineLayer = null;
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1768]: The type of the engineLayer is specific to the implementation of the addToScene method. Rather than null it here where the reason for the nullification isn't immediately obvious, deal with the wrong type down in addToScene.

Basically in addToScene, only pass along the oldLayer if it is of the right type and it will get replaced naturally.

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 4]
```diff
@@ -843,7 +843,7 @@ class RenderOpacity extends RenderProxyBox {
        super(child);
 
   @override
-  bool get alwaysNeedsCompositing => child != null && (_alpha != 0 && _alpha != 255);
+  bool get alwaysNeedsCompositing => child != null && (_alpha != 0);
```
Comment (flar) [inline packages/flutter/lib/src/rendering/proxy_box.dart:846]: While we're here, should this be `> 0`? Some places that check alpha use an inequality and other places use equality tests (see RenderAnimatedOpacityMixin below).

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 5]
```diff
@@ -993,7 +987,7 @@ mixin RenderAnimatedOpacityMixin<T extends RenderObject> on RenderObjectWithChil
     _alpha = ui.Color.getAlphaFromOpacity(opacity.value);
     if (oldAlpha != _alpha) {
       final bool? didNeedCompositing = _currentlyNeedsCompositing;
-      _currentlyNeedsCompositing = _alpha! > 0 && _alpha! < 255;
+      _currentlyNeedsCompositing = _alpha! > 0;
```
Comment (flar) [inline packages/flutter/lib/src/rendering/proxy_box.dart:990]: Here we use inequality for alpha test, other places use equality testing. Perhaps all tests on alpha should use tests that are safe in the presence of out-of-range values like this?

Comment (flar) [reply packages/flutter/lib/src/rendering/proxy_box.dart:990]: Also, there are range asserts sprinkled around, but it is hard to tell from a PR diff if they are consistently protecting every line of code.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 6]
```diff
@@ -1795,24 +1781,32 @@ class OpacityLayer extends ContainerLayer {
       return true;
     }());
 
-    if (enabled)
+    final int realizedAlpha = alpha!;
+    // The type assertions work because the [alpha] setter nulls out the
+    // engineLayer if it would have changed type (i.e. changed to or from 255).
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1786]: Inter-method dependencies for correctness are weaker than just having this method deal with the wrong layer type that it knows happens because it is the method that causes it.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 4 above)
Comment (flar) [reply packages/flutter/lib/src/rendering/proxy_box.dart:846]: I see that there are some asserts in here, but not sure if they protect every value test or not.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 7]
```diff
@@ -1795,24 +1781,32 @@ class OpacityLayer extends ContainerLayer {
...
-        offset: offset! + layerOffset,
+        realizedAlpha,
+        offset: offset + layerOffset,
         oldLayer: _engineLayer as ui.OpacityEngineLayer?,
       );
-    else
-      engineLayer = null;
+    } else {
+      assert(_engineLayer is ui.OffsetEngineLayer?);
+      engineLayer = builder.pushOffset(
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1796]: What is the value of subclassing OffsetLayer if we push our own?

File: packages/flutter/lib/src/rendering/layer.dart [hunk 8]
```diff
@@ -1764,28 +1764,14 @@ class OpacityLayer extends ContainerLayer {
   set alpha(int? value) {
     assert(value != null);
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1765]: No range assert here.

**Review by flar — COMMENTED** [review]
Some concerns over mixing of state correctness between methods and whether opacity/alpha values are always range protected vs. using inequality in tests, but otherwise no blockers...

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1768]: Because addToScene is on a hot path, and will require type checks every time that hot path gets hit, whereas we know what the type will be based ont he value of the opacity.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 8 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1765]: That should be addressed in a separate PR.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1786]: The asserts in here guard against this getting broken, and there is test coverage that would trigger them should it break. I did this becuase it's on a hot path.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1796]: Eliminates duplicated code with regard to setting the transform, and both layers provide an `offset` property.

Users of this API don't really deal directly with scene builder - but in some of my explorations around trying to optimize layer usage, it can be helpful to know whether a layer has an offset or not.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 4 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/proxy_box.dart:846]: Fair, I'll fix this. Previously we couldn't use that because 255 was also special cased :)

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/proxy_box.dart:990]: We use the following code from dart:ui to calculate alpha

```
  static int getAlphaFromOpacity(double opacity) {
    assert(opacity != null);
    return (opacity.clamp(0.0, 1.0) * 255).round();
  }
```

It's guarnateed to not go out of bounds.

**Comment by dnfield** [comment]
@flar - I'm not quite clear if you want to discuss the checks further. For some of the range asserts, I think we should just file a new bug and address it separately in case this gets reverted. They're not a bad idea, but there's not a great reason IMHO to include them here where they were already absent.

I'd prefer to avoid the type checks in `addToScene` simply because that code path gets hit very frequently, including after the alpha has settled on whatever value the animation ends/stops/pauses at.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (flar) [reply packages/flutter/lib/src/rendering/layer.dart:1768]: A single `is` is going to completely derail our performance?
Compared to the improved maintainability by not having multiple functions have to deal with an implementation detail of one of them?

addToScene has to do an `as` anyway which implicitly includes an `is`, but throws if it fails rather than just substituting null which is the logical reaction to the type being wrong. Note that with the `is` you likely don't even need the `as` because the runtime is smart enough to elide them.
You are already paying the price of type checking the parameter in addToScene, why complicate it?

Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1768]: So I figured I don't have a benchmark to back this up and I can just make this change. However, there's another complication here. What I really want is it to be an error to call `addToScene` with an incorrect engineLayer, because you cannot mutate the `engineLayer` during addToScene, and if we got called `addToScene` without nulling out the no-longer-needed engineLayer, we've made a mistake that wastes memory.

I'm happy to update the documentation on this if it's not already updated, but I think the asserts and mutations are correct this way, and we'd risk recurisvely calling `addToScene` if we start trying to mutate the engineLayer there.

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/89264

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/89264

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (flar) [reply packages/flutter/lib/src/rendering/layer.dart:1768]: How is "this object wants to decide on the fly which type of engine layer to use when it adds to the scene" compatible with "addToScene is not allowed to mutate the engineLayer and we will make that an error"?

Philosophically those two concepts are at odds with each other. You can't justify one without pointing out that the other is or has an invalid assumption.

Adding code to prevent a conflict between them is a workaround and points out that the design decisions had some cases they didn't really address.

You are basically nulling out the field to destroy the evidence that the engine layer is actually dynamic here.

And if there is a reason for it to be dynamic here, then what is the value of a globally enforced assertion that it isn't.

Comment (flar) [reply packages/flutter/lib/src/rendering/layer.dart:1768]: (None of this is blocking, btw, I'm just a little skeptical over the design constraints that led to this implementation...)

**Comment by flar** [comment]
> @flar - I'm not quite clear if you want to discuss the checks further. For some of the range asserts, I think we should just file a new bug and address it separately in case this gets reverted. They're not a bad idea, but there's not a great reason IMHO to include them here where they were already absent.

Handling that separately sounds good.

> I'd prefer to avoid the type checks in `addToScene` simply because that code path gets hit very frequently, including after the alpha has settled on whatever value the animation ends/stops/pauses at.

None of that is a blocking comment, but I'm still not clear why you think that it is saving anything for frequently hit code. The code already has an `as` operator which is `(A is B) ? A : throw` and that has the same cost as `(A is B ? A : null)` with the language not requiring the `as` in that case.

(I'd love to see the language have an `as?` operator that was literally "or null" rather than "or throw".)

**Comment by dnfield** [comment]
The performance concerns are really secondary. The real problem is that if you got all the way to `addToScene` with the wrong kind of engineLayer, you made a mistake along the way and potentially retained an entire layer tree (and any images it had) longer than necessary. Once you know the alpha is changing the layer should let the engine know to release resources.

**Comment by dnfield** [comment]
Landing this on red because the scuba changes are expected.

@flar - happy to discuss further and see if we can continue to improve on this, but again my main concern is around not holding native resources any longer than absolutely necessary.
