### PR TITLE
[tool] Support `--flavor` option for `flutter install`.

### LINKED ISSUE #99607: flutter install demands unsupported `--flavor` option
## Steps to Reproduce

See steps in #98151 .

Here are my steps:

```
$ flutter build ios -t lib/main_staging.dart --flavor=staging --release
...

$ flutter install --device-id=nnn
The Xcode project defines schemes: local, prod, staging
You must specify a --flavor option to select one of the available schemes.

$ flutter install --device-id=nnn --flavor=staging
Could not find an option named "flavor".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

### PR DESCRIPTION
**Pull request by a-wallen**
`flutter install` previously forced users to specify the `--flavor` option if flavors were configured for a flutter project, but didn't provide the option, to begin with ( see https://github.com/flutter/flutter/issues/99607 ). We could solve this by either:
1. Not throwing a tool exit when running `flutter install` on a project with flavors configured. Users will have to use install the application binary with the `--use-application-binary` flag.
2. Adding `--flavor` as an option - search for that flavor's binary and install it.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
Suggest also adding `flutter install --flavor` and `flutter install --uninstall-only --flavor` to the end of https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flavors_test.dart

**Comment by jmagman** [comment]
You added Chris as me as reviewers, mark this ready for review when it's actually ready for review 🙂

**Comment by jmagman** [comment]
I didn't test this, but here's a possible way to test install in the devicelab
```dart
    await inDirectory('${flutterDirectory.path}/dev/integration_tests/flavors', () async {
      await flutter(
        'install',
        options: <String>['--flavor', 'paid'],
      );
      await flutter(
        'install',
        options: <String>['--flavor', 'paid', '--uninstall-only'],
      );
      final StringBuffer stderr = StringBuffer();
      await evalFlutter(
        'install',
        canFail: true,
        stderr: stderr,
        options: <String>['--flavor', 'bogus'],
      );

      final String stderrString = stderr.toString();
      if (!stderrString.contains('install failed, bogus flavor not found')) {
        print(stderrString);
        return TaskResult.failure('Should not succeed with bogus flavor');
      }
    });
```

File: dev/devicelab/bin/tasks/flavors_test.dart [hunk 1]
```diff
@@ -5,13 +5,38 @@
...
+      final StringBuffer stderr = StringBuffer();
+      await evalFlutter(
+        'install',
+        canFail: true,
+        stderr: stderr,
+        options: <String>['--flavor', 'bogus'],
+      );
+
+      final String stderrString = stderr.toString();
+      if (!stderrString.contains('install failed, bogus flavor not found')) {
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/flavors_test.dart:35]: This isn't the correct error message I'm sure, you'll have to run it.

File: dev/devicelab/bin/tasks/flavors_test_win.dart [hunk 2]
```diff
@@ -5,13 +5,38 @@
 import 'package:flutter_devicelab/framework/devices.dart';
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/flavors_test_win.dart:5]: This file is identical to `flavors_test.dart`.

Can you delete this file and change 
https://github.com/flutter/flutter/blob/44ecbbcc54c1029eed51662dc7f123607384b564/.ci.yaml#L4544
to 
```
       task_name: flavors_test
```
I _think_ that should work?

File: packages/flutter_tools/test/commands.shard/hermetic/install_test.dart [hunk 3]
```diff
@@ -103,16 +103,41 @@ void main() {
...
 class FakeApplicationPackageFactory extends Fake implements ApplicationPackageFactory {
-  FakeApplicationPackageFactory(this.app);
+  FakeApplicationPackageFactory(this.app, { this.getPackageForPlatformInterceptor });
 
   final ApplicationPackage app;
+  final void Function(TargetPlatform platform, {BuildInfo? buildInfo, File? applicationBinary})? getPackageForPlatformInterceptor;
 
   @override
   Future<ApplicationPackage> getPackageForPlatform(TargetPlatform platform, {BuildInfo? buildInfo, File? applicationBinary}) async {
+    if(getPackageForPlatformInterceptor != null) {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/hermetic/install_test.dart:138]:
```suggestion
    if (getPackageForPlatformInterceptor != null) {
```

File: packages/flutter_tools/test/commands.shard/hermetic/install_test.dart [hunk 4]
```diff
@@ -103,16 +103,41 @@ void main() {
...
+    });
   });
 }
 
 class FakeApplicationPackageFactory extends Fake implements ApplicationPackageFactory {
-  FakeApplicationPackageFactory(this.app);
+  FakeApplicationPackageFactory(this.app, { this.getPackageForPlatformInterceptor });
 
   final ApplicationPackage app;
+  final void Function(TargetPlatform platform, {BuildInfo? buildInfo, File? applicationBinary})? getPackageForPlatformInterceptor;
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/hermetic/install_test.dart:134]: A different way to do this would be to create a writable `BuildInfo` property that gets set in `getPackageForPlatform`, then you can check the `FakeApplicationPackageFactory`'s `buildInfo.flavor` at the end.

File: dev/devicelab/bin/tasks/flavors_test_win.dart (hunk 2 above)
Comment (a-wallen) [reply dev/devicelab/bin/tasks/flavors_test_win.dart]: It worked :)

File: packages/flutter_tools/test/commands.shard/hermetic/install_test.dart (hunk 4 above)
Comment (a-wallen) [reply packages/flutter_tools/test/commands.shard/hermetic/install_test.dart]: Yeah, that looks much cleaner 👌

File: dev/devicelab/bin/tasks/flavors_test_ios.dart [hunk 5]
```diff
@@ -5,13 +5,38 @@
...
 import 'package:flutter_devicelab/framework/task_result.dart';
+import 'package:flutter_devicelab/framework/utils.dart';
 import 'package:flutter_devicelab/tasks/integration_tests.dart';
 
 Future<void> main() async {
   deviceOperatingSystem = DeviceOperatingSystem.ios;
   await task(() async {
     await createFlavorsTest().call();
     await createIntegrationTestFlavorsTest().call();
+    // test install and uninstall of flavors app
```
Comment (keyonghan) [inline dev/devicelab/bin/tasks/flavors_test_ios.dart:16]: Does the `flavors_test_ios` change much? If yes, you may want to add `bringup: true` to `Mac_ios flavors_test_ios` for validation.

Comment (a-wallen) [reply dev/devicelab/bin/tasks/flavors_test_ios.dart:16]: SGTM

Comment (a-wallen) [reply dev/devicelab/bin/tasks/flavors_test_ios.dart:16]: Thanks for the friendly reminder @keyonghan, I didn't realize that there were other test targets that were affected by this task change.

File: .ci.yaml [hunk 6]
```diff
@@ -1690,6 +1690,7 @@ targets:
       task_name: fast_scroll_large_images__memory
 
   - name: Linux_android flavors_test
+    bringup: true
```
Comment (jmagman) [inline .ci.yaml:1693]: If the intention of this was to test in this PR, then you also need to remove `presubmit: false`

**Review by jmagman — COMMENTED** [review]
This LGTM once you're done testing and the .ci.yaml `bringup` changes are reverted (though if you want to keep it for the Windows one, that makes sense).

File: .ci.yaml (hunk 6 above)
Comment (christopherfujino) [reply .ci.yaml:1693]: Can we even run devicelab tests presubmit?

Comment (jmagman) [reply .ci.yaml:1693]: We run `Mac_ios hot_mode_dev_cycle_macos_target__benchmark` and `Linux_android hot_mode_dev_cycle_linux__benchmark` so there's capacity.  

But what I said doesn't make any sense, adding `bringup` wouldn't make it run in this PR, _removing_ bringup would do that.

@keyonghan suggested @a-wallen do this, but I didn't see that since their conversation was resolved and hidden.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
This caused `Windows_android flavors_test_win` to start failing: https://github.com/flutter/flutter/issues/115121
