### PR TITLE
Fix `DataTable` `_SortArrow` changing orientation when state is updated

### LINKED ISSUE #43724: [DataTable] SortArrow animates when unrelated setState or hot reload.
## Steps to Reproduce

1. Run this main.dart https://gist.github.com/miajimyu/9aaa53ad313810feb23787ba876740af#file-main-dart
2. Hot reload or setState by clicking heart icon.
3. SortArrow animates.

**Target Platform:** Android
**Target OS version/browser:** Platform android-29
**Devices:** any

## Logs

```
Please look below gist.
Step to Reproduce is only hot reload.
```
https://gist.github.com/miajimyu/9aaa53ad313810feb23787ba876740af#file-log

```
flutter analyze  
Analyzing data_table...                                                 
No issues found! (ran in 1.6s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A603, locale en-JP)
    • Flutter version 1.9.1+hotfix.6 at /Users/miajimyu/Desktop/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/miajimyu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by markusaksli-nc**
The SortArrow should not change orientation when `_up` is null. This led to the arrow changing orientation just because the state was updated (but not the sorting direction). The test shows this in action.

Fixes https://github.com/flutter/flutter/issues/43724

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/data_table_test.dart [hunk 1]
```diff
@@ -486,6 +486,103 @@ void main() {
...
+        }).toList(),
+      );
+    }
+
+    // Check for ascending list
+    await tester.pumpWidget(MaterialApp(
+      home: Material(child: buildTable()),
+    ));
+    // The `tester.widget` ensures that there is exactly one upward arrow.
+    Transform transformOfArrow = tester.widget<Transform>(find.widgetWithIcon(Transform, Icons.arrow_upward));
```
Comment (Piinks) [inline packages/flutter/test/material/data_table_test.dart:518]: Nit: These should be split instead of one-lined per the style guide

File: packages/flutter/lib/src/material/data_table.dart [hunk 2]
```diff
@@ -1194,7 +1195,7 @@ class _SortArrowState extends State<_SortArrow> with TickerProviderStateMixin {
         _opacityController.reverse();
       }
     }
-    if ((_up != newUp) && !skipArrow) {
+    if ((_up != null) && (_up != newUp) && !skipArrow) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table.dart:1198]: This addition does not appear to be necessary according to the tests. :)

**Review by Piinks — COMMENTED** [review]
Hey @markusaksli-nc, happy new year 🎉  
Thanks for the contribution!

**Comment by markusaksli-nc** [comment]
Thanks for the feedback and happy new year!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Thank you for the contribution!
