### PR TITLE
Fix a slider layout bug when the overlay size is smaller than the thumb size

### LINKED ISSUE #74503: Slider with no overlayShape shifts to the left
I don't know if other people had the same issue (I looked online but found nothing). I was working on a custom thumb shape and noticed that whenever I set the _overlayShape_ to _**SliderComponentShape.noOverlay**_ my slider shifted to the left within its intrinsic boundaries. No errors or warnings were shown in the console.
###  Here's the preview of a sample app featuring the issue

**Expected results:** 

expected

**Actual results:** 

actual

#### Here's the code that produced the screenshots above (in the expected result I just commented out  the line 45, the one with the _overlayShape_ parameter) :
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({this.title});

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  double sliderValue = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: Align(
          alignment: Alignment.topCenter,
          child: UnconstrainedBox(
            constrainedAxis: Axis.horizontal,
            child: SliderTheme(
              data: SliderThemeData(
                  overlayShape: SliderComponentShape.noOverlay,
                  thumbShape: RoundSliderThumbShape(
                    enabledThumbRadius: 20.0,
                  )),
              child: Slider(
                onChanged: (double value) {
                  setState(() {
                    sliderValue = value;
                  });
                },
                value: sliderValue,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

In my research to the problem I found out what might be the cause of it (but I'm not sure since I didn't make any adjustments to the source code to see if it actually works). The thing that appeared odd to me is one particular line of the **slider_theme.dart** file where only the overlay width is taken into account for calculating the left boundary of the track rect.
This is the line from the source:
https://github.com/flutter/flutter/blob/46b0797b580b772d0302a6feb1d7fb88ad02a8cf/packages/flutter/lib/src/material/slider_theme.dart#L1454)

Perhaps it should be:
```dart
final double trackLeft = offset.dx + math.max(thumbWidth, overlayWidth) / 2;
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
As title.

Fixes #74503

### CODE REVIEW

File: packages/flutter/test/material/slider_theme_test.dart [hunk 1]
```diff
@@ -852,6 +852,28 @@ void main() {
...
 
+  // Regression test for https://github.com/flutter/flutter/issues/74503
+  testWidgets('The slider track layout correctly when the overlay size is smaller than the thumb size', (WidgetTester tester) async {
+    final SliderThemeData sliderTheme = ThemeData().sliderTheme.copyWith(
+      overlayShape: SliderComponentShape.noOverlay,
+    );
+
+    await tester.pumpWidget(_buildApp(sliderTheme, value: 0.5));
+
+    final MaterialInkController material = Material.of(tester.element(find.byType(Slider)))!;
```
Comment (shihaohong) [inline packages/flutter/test/material/slider_theme_test.dart:863]: nit:
```suggestion
    final MaterialInkController material = Material.of(
      tester.element(find.byType(Slider)),
    )!;
```

File: packages/flutter/test/material/slider_theme_test.dart [hunk 2]
```diff
@@ -852,6 +852,28 @@ void main() {
...
+    // The track rectangle begins at 10 pixels and ends at 790 pixels which position at the center of the screen(width: 800.0)
+    expect(material,
+      paints
+        // active track RRect
+        ..rrect(rrect: RRect.fromLTRBAndCorners(10.0, 297.0, 400.0, 303.0, topLeft: const Radius.circular(3.0), bottomLeft: const Radius.circular(3.0)))
+        // inactive track RRect
+        ..rrect(rrect: RRect.fromLTRBAndCorners(400.0, 298.0, 790.0, 302.0, topRight: const Radius.circular(2.0), bottomRight: const Radius.circular(2.0)))
+        // thumb
+        ..circle(x: 400.0, y: 300.0, radius: 10.0, )
+    );
```
Comment (shihaohong) [inline packages/flutter/test/material/slider_theme_test.dart:874]: Just add some comments and some code styling that I thought helped me better read this section. Otherwise, the test looks great! 
```suggestion
    // The track rectangle begins at 10 pixels from the left of the screen and ends 10 pixels from the right 
    // (790 pixels from the left). The main check here it that the track itself should be centered on 
    // the 800 pixel-wide screen.
    expect(
      material,
      paints
          // active track RRect. Starts 10 pixels from left of screen.
        ..rrect(rrect: RRect.fromLTRBAndCorners(
            10.0, 
            297.0, 
            400.0, 
            303.0, 
            topLeft: const Radius.circular(3.0), 
            bottomLeft: const Radius.circular(3.0),
          ))
          // inactive track RRect. Ends 10 pixels from right of screen.
        ..rrect(rrect: RRect.fromLTRBAndCorners(
            400.0,
            298.0,
            790.0,
            302.0,
            topRight: const Radius.circular(2.0),
            bottomRight: const Radius.circular(2.0),
          ))
        // thumb
        ..circle(x: 400.0, y: 300.0, radius: 10.0)
    );
```

**Review by shihaohong — APPROVED** [review]
LGTM. Just some code styling and inline comments suggestions to help readers understand the test better.

**Comment by xu-baolin** [comment]
Thanks for such quick feedback! 👍

**Comment by shihaohong** [comment]
Looks like the analyzer is unhappy about trailing whitespace
