### PR TITLE
[flutter_tools] Fix null check in parsing web plugin from pubspec.yaml

### LINKED ISSUE #117926: [flutter_tools] _CastError in WebPlugin.fromYaml
on `beta/3.7.0-1.2.pre`

```
_CastError: type 'Null' is not a subtype of type 'String' in type cast
at new WebPlugin.fromYaml(platform_plugins.dart:548)
at new Plugin._fromMultiPlatformYaml(plugins.dart:142)
at new Plugin.fromYaml(plugins.dart:78)
at _pluginFromPackage(flutter_plugins.dart:63)
at findPlugins(flutter_plugins.dart:88)
at <asynchronous gap>(async)
at refreshPluginsList(flutter_plugins.dart:1080)
at <asynchronous gap>(async)
at FlutterProject.ensureReadyForPlatformSpecificTooling(project.dart:357)
at <asynchronous gap>(async)
at PackagesGetCommand.runCommand(packages.dart:179)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1257)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:283)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:64)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:91)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/117926

### CODE REVIEW

**Comment by christopherfujino** [comment]
@Jasguerrero friendly ping

File: packages/flutter_tools/lib/src/platform_plugins.dart [hunk 1]
```diff
@@ -541,21 +541,19 @@ class WebPlugin extends PluginPlatform {
   });
 
   factory WebPlugin.fromYaml(String name, YamlMap yaml) {
-    assert(validate(yaml));
+    if (yaml['pluginClass'] is! String) {
```
Comment (Jasguerrero) [inline packages/flutter_tools/lib/src/platform_plugins.dart:544]: Cool didn't know is! was a thing

File: packages/flutter_tools/test/general.shard/plugin_parsing_test.dart [hunk 2]
```diff
@@ -290,6 +290,29 @@ void main() {
...
+    expect(
+      () => Plugin.fromYaml(
+        _kTestPluginName,
+        _kTestPluginPath,
+        pluginYaml,
+        null,
+        const <String>[],
+        fileSystem: fileSystem,
+      ),
+      throwsToolExit(
```
Comment (Jasguerrero) [inline packages/flutter_tools/test/general.shard/plugin_parsing_test.dart:310]: Should there be an additional test for this case? `throwToolExit('The plugin `$name` is missing the required field `pluginClass` in pubspec.yaml');`

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/plugin_parsing_test.dart:310]: If I simply exlude that field, we actually don't even reach this method, because of previous parsing. I left this toolexit though in case there's some other weird case in which we CAN reach this method (I got confused tracing the previous logic)

Comment (Jasguerrero) [reply packages/flutter_tools/test/general.shard/plugin_parsing_test.dart:310]: Fair enough

**Review by Jasguerrero — APPROVED** [review]
LGTM
