### PR TITLE
Fix the padding and space for FlatButton and RaisedButton

### LINKED ISSUE #1843: Material button layout can be difficult
MaterialButton's  padding and size constraints makes it difficult to do layouts like the yellow share/explore flat-buttons in this example from the MD spec:

button_layout

To layout the panel below the "Top 10 Beaches.." image, the natural thing to do is just to add a padded column that ends with the button row.

```
new Padding(
  padding: const EdgeDims.all(16.0)
  child: new Column(
    children: <Widget>[
      descriptionLine0,
      descriptionLine1,
      descriptionLine2,
      new Row(justifyContent: FlexJustifyContent.start, children: shareAndExploreButtons)
    ]
  )
)
```
The buttons' padding and minWidth cause them to be inset from the padded left edge. It would be easier if FlatButtons didn't bother with the minWidth and padding at all.

### LINKED ISSUE #3184: External padding incorrect for raised and flat buttons
When putting RaisedButton or FlatButton in a Row, the spacing between the buttons are incorrect. Also the internal padding to the text may be too small horizontally.

Test case in: /examples/material_gallery/lib/demo/buttons_demo.dart

flutter_01

Correct spacing (from the material design spec):

screen shot 2016-04-07 at 2 03 08 pm

### PR DESCRIPTION
**Pull request by abarth**
Instead of incorporating the margin into the button, introduce a ButtonBar
widget that supplies the proper spacing between the buttons. Also, make these
buttons more configurable via ButtonTheme so that dialogs can change the
minWidth and padding of the buttons as required by the spec.

Fixes #1843
Fixes #3184

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller

**Comment by HansMuller** [comment]
LGTM

ButtonBar should work nicely as a MD "BottomBar" - https://www.google.com/design/spec/components/bottom-navigation.html

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -1667,9 +1667,16 @@ class Flex extends MultiChildRenderObjectWidget {
...
+  /// The direction to use as the main axis.
   final FlexDirection direction;
+
+  /// How the children should be placed along the main axis.
   final MainAxisAlignment mainAxisAlignment;
+
+  /// How the children should be placed along the cross axis.
   final CrossAxisAlignment crossAxisAlignment;
+
+  /// If using aligning items according to their baseline, which baseline to use.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: ~using~

**Comment by Hixie** [comment]
LGTM
