### PR TITLE
Fix/ValueListenableBuilder rebuilds

### LINKED ISSUE #72002: ValueListenableBuilder with an Animation<> rebuilds even when the value didn't change
You can see this running at https://codepen.io/ravenblack/pen/OJRROgm

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: MyWidget(),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _Bloop(),
      ),
    );
  }
}

class _Bloop extends StatefulWidget {
  @override
  State<_Bloop> createState() => _BloopState();
}

class _BloopState extends State<_Bloop> with SingleTickerProviderStateMixin {
  int i = 0;
  AnimationController _controller;
  Animation<double> _animation;
  @override
  void initState() {
    _controller =
        AnimationController(vsync: this, duration: Duration(seconds: 1));
    _animation = _controller.drive(TweenSequence([
      TweenSequenceItem(tween: ConstantTween(0.0), weight: 1.0),
      TweenSequenceItem(tween: ConstantTween(1.0), weight: 1.0),
    ]));
    _controller.repeat();
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<double>(
        valueListenable: _animation,
        builder: (_, value, ___) {
          return Text(
            '$value ${i++}',
            style: Theme.of(context).textTheme.headline4,
          );
        });
  }
}
```

Expected behavior: the value of 'i' ticks up once each time 'value' changes.
Actual behavior: the value of 'i' ticks up every frame, while 'value' changes only every 15 frames.

I think the underlying issue is that the an `Animation<double>` notifies whenever its associated controller notifies, but since it's nominally a `ValueListenable` it should really not trigger that notification if its output value didn't change.

### PR DESCRIPTION
**Pull request by 2ZeroSix**
## Description
check if value really changed in ValueListenableBuilder

## Related Issues

fixes #72002

## Tests

I added the following tests:
- "Widget does not rebuilds if value is the same" in `packages/flutter/test/widgets/value_listenable_builder_test.dart`

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/value_listenable_builder.dart [hunk 1]
```diff
@@ -179,7 +179,9 @@ class _ValueListenableBuilderState<T> extends State<ValueListenableBuilder<T>> {
   }
 
   void _valueChanged() {
-    setState(() { value = widget.valueListenable.value; });
+    if (value !=  widget.valueListenable.value) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/value_listenable_builder.dart:182]: nit: remove one space after `!=`

File: packages/flutter/test/widgets/value_listenable_builder_test.dart [hunk 2]
```diff
@@ -18,6 +19,8 @@ void main() {
       child: ValueListenableBuilder<String?>(
         valueListenable: valueListenable,
         builder: (BuildContext context, String? value, Widget? child) {
+          ++rebuildCount;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/value_listenable_builder_test.dart:22]: use `+= 1` here over `++`, see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer--over-

**Comment by goderbauer** [comment]
@2ZeroSix Do you have plans to follow up on the feedback given above soon-ish? Thanks.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by 2ZeroSix** [comment]
@goderbauer shouldn't there be `waiting for tree to go green ` tag for automatic merge?
