### PR TITLE
Make iOS Flutter framework extension-safe

### LINKED ISSUE #142531: "Сontains disallowed nested bundles" and "Contains disallowed file 'Frameworks'" Flutter with IOS share extension when deploy to TestFlight
### Type of Request

bug

### Infrastructure Environment

TestFlight

### What is happening?

I'm implementing the "Share" widget in a Flutter application using this guide (https://docs.flutter.dev/platform-integration/ios/app-extensions). To achieve this, it's necessary to embed the Flutter framework (Flutter.xcframework from extension_safe directory) into the extension. 

Снимок экрана 2024-01-30 в 19 00 03

I have no build issues, but when I try to submit to TestFlight, I encounter the following errors.

Asset validation failed Invalid Bundle. The bundle at 'Runner.app/Plugins/ share_extension.appex' contains disallowed nested bundles. (ID: 25eb4da5-3868-40ab-bb64-d83b73d238c)

Asset validation failed Invalid Bundle. The bundle at 'Runner.app/Plugins/share_extension.appex' contains disallowed file 'Frameworks'. (ID: e94a1815-1314-48f6-9b45-b6917b1fe627)

telegram-cloud-photo-size-2-5316621067055387349-x

The only thing that allowed deployment was setting the framework to "Do not embed" but this option is not suitable because it causes the share widget to stop appearing.

### Steps to reproduce

Step 1: Add Target to project "Share Extension"

Step 2: Add project and extension to the same App Group

Step 3: Drag and drop the Flutter.xcframework file (From <path_to_flutter_sdk>/bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframework) into your share extension’s frameworks and libraries list

Step 4: Open the Flutter app project settings in Xcode to share build configurations. For each of these configurations, make sure the value in the Based on configuration file drop-down menu for your extension matches the one selected for the normal app target.

Step 5: Archive project

Stap 6: Try upload it to TestFlight

### Expected results

App uploaded to TestFlight and flutter will be shown in the "Share" widget

### PR DESCRIPTION
**Pull request by vashworth**
Our current [adoption/documentation](https://docs.flutter.dev/platform-integration/ios/app-extensions) for iOS Extensions does not currently work because it's disallowed to nest bundles (see https://github.com/flutter/flutter/issues/142531). 

As of [Xcode 13](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes/#:~:text=Linking%20Swift%20packages%20from%20application%20extension%20targets%20or%20watchOS%20applications%20no%20longer%20emits%20unresolvable%20warnings%20about%20linking%20to%20libraries%20not%20safe%20for%20use%20in%20application%20extensions%2E), linking to frameworks that contain non-extension-safe code no longer gives warnings (or blocks from App Store it seems). Therefore, it has become a runtime issue to ensure non-extension-safe code is not used.

Previously, we were building and shipping 2 separate Flutter.xcframeworks. One that was extension-safe and one that was not.

This PR removes the "extension_safe" framework and instead makes the entire framework extension-safe by annotating non-extension-safe code with `NS_EXTENSION_UNAVAILABLE_IOS` and ensuring that code is not used at runtime if the bundle is for an app extension.

This PR also disables wide gamut for app extensions to decrease the chances of crashes (see https://github.com/flutter/flutter/issues/165086).

Fixes https://github.com/flutter/flutter/issues/142531.
 
 ---
 
For reference:

App extensions were first evaluated in https://flutter.dev/go/app-extensions. Here is the reasoning why neither method described there is opportune. 

Option 1 -
I did look into splitting the framework into 2 frameworks (one with all extension-safe code and one with the non-extension-safe code). However, the original idea was to use objc Categories/Extensions - this doesn’t quite fit our needs. Categories/Extensions only allow you to add new methods/properties, not override existing ones. We could hypothetically add new methods, but that would require the user to change their code to use the new methods.

I also looked into subclasses which does allow overrides, but it would also require the user to change their code to use the new class. 

We could do method swizzling, but opinion of that on the internet is that it's not very safe.

I’m of the opinion that anything that requires the user to change code isn’t super feasible due to plugins.

Option 2 -
We could still do the 2 frameworks but rename one to `FlutterExtentionSafe`. This works without users needing to change any code (including imports like `@import Flutter` / `#import <Flutter/Flutter.h>`). I believe the reason this works is because at compile time, it finds the `Flutter` framework on the framework search path and it imports in the headers. Then at link time, `FlutterExtentionSafe` is explicitly linked so it uses that framework first when checking for symbols and since it finds all the symbols in `FlutterExtentionSafe`, it doesn’t need/try to auto-link the `Flutter` framework (despite `Flutter` being the framework imported). 

This seems precarious to me since we’re relying on Xcode to not auto-link the `Flutter` framework. If for some reason `Flutter` framework did get auto-linked (such as the user using a symbol that’s not in the `FlutterExtensionSafe` framework but is in the `Flutter` framework - this is unlikely though), we’d get name collision issues

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: dev/bots/suite_runners/run_verify_binaries_codesigned_tests.dart [hunk 1]
```diff
@@ -89,16 +89,10 @@ List<String> binariesWithoutEntitlements(String flutterRoot) {
     'artifacts/engine/darwin-x64/libtessellator.dylib',
     'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
     'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
-    'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
-    'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
```
Comment (jmagman) [inline dev/bots/suite_runners/run_verify_binaries_codesigned_tests.dart:93]: Sooo nice we can make this change atomically with the engine now.

File: engine/src/flutter/ci/builders/mac_ios_engine.json [hunk 2]
```diff
@@ -248,253 +248,6 @@
                     "sdk_version": "16c5032a"
                 }
             }
-        },
```
Comment (jmagman) [inline engine/src/flutter/ci/builders/mac_ios_engine.json:251]: I wonder if we should keep building these artifacts for a release (even though it doesn't really work) in case someone is using it, and then put the deprecation in the tech blog with instructions for migrating? I bet people have prototypes that "work" locally and I don't want them to be mysteriously busted.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm [hunk 3]
```diff
@@ -227,15 +228,15 @@ - (instancetype)initWithName:(NSString*)labelPrefix
                  name:UIApplicationDidReceiveMemoryWarningNotification
                object:nil];
 
-#if APPLICATION_EXTENSION_API_ONLY
-  if (@available(iOS 13.0, *)) {
-    [self setUpSceneLifecycleNotifications:center];
-  } else {
+  if ([FlutterSharedApplication isAvailable]) {
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:231]: Dot notation for properties, including class properties.
```suggestion
  if (FlutterSharedApplication.isAvailable) {
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm [hunk 4]
```diff
@@ -227,15 +228,15 @@ - (instancetype)initWithName:(NSString*)labelPrefix
...
     [self setUpApplicationLifecycleNotifications:center];
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:232]: Instead of the caller (in two places) needing to understand the extension and API limitations of this call, can the logic be pushed down into one `setUpLifecycleNotifications:` method?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+#define FLUTTER_SHELL_PLATFORM_DARWIN_IOS_FRAMEWORK_SOURCE_FLUTTERSHAREDAPPLICATION_H_
+
+#import <UIKit/UIKit.h>
+
+@interface FlutterSharedApplication : NSObject
+
+/**
+ * Check whether the main bundle is an iOS App Extension.
+ */
++ (BOOL)isAppExtension;
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h:15]: This should be a readonly class property.
```suggestion
@property(class, nonatomic, readonly) BOOL isAppExtension;
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+
+/**
+ * Check whether the UIApplication is available. UIApplication is not available for App Extensions.
+ */
++ (BOOL)isAvailable;
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h:20]: Same.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+
+/**
+ * Returns the `UIApplication.sharedApplication` is available. Otherwise returns nil.
+ */
++ (UIApplication*)uiApplication;
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h:25]: `uiApplication` with the prefix is kind of odd looking, how about `sharedApplication` or just `application`?
Also a class property.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+#include "flutter/fml/logging.h"
+#import "flutter/shell/platform/darwin/common/framework/Headers/FlutterMacros.h"
+
+FLUTTER_ASSERT_ARC
+
+@interface FlutterSharedApplication ()
+
++ (UIApplication*)sharedApplication;
+
+@end
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm:15]: Why is this category necessary?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+
+@implementation FlutterSharedApplication
+
++ (BOOL)isAppExtension {
+  NSDictionary* nsExtension = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSExtension"];
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm:20]:
```suggestion
  NSDictionary* nsExtension = [NSBundle.mainBundle objectForInfoDictionaryKey:@"NSExtension"];
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterView.mm [hunk 10]
```diff
@@ -53,6 +54,12 @@ - (MTLPixelFormat)pixelFormat {
 - (BOOL)isWideGamutSupported {
   FML_DCHECK(self.screen);
 
+  // Wide Gamut is not supported for iOS Extensions due to memory limitations
+  // (see https://github.com/flutter/flutter/issues/165086).
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterView.mm:58]: Good catch figuring out that would help with memory.

**Review by jmagman — COMMENTED** [review]
Mostly minor nits except for the comment about keeping the old artifact for a release cycle, even if it's identical to Flutter.framework.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm [hunk 11]
```diff
@@ -417,9 +415,55 @@ - (void)testStatusBarHiddenUpdate {
...
+
+  // Update to hidden.
+  FlutterPlatformPlugin* plugin = [engine platformPlugin];
+
+  XCTestExpectation* enableSystemUIOverlaysCalled =
+      [self expectationWithDescription:@"setEnabledSystemUIOverlays"];
+  FlutterResult resultSet = ^(id result) {
+    [enableSystemUIOverlaysCalled fulfill];
+  };
+  FlutterMethodCall* methodCallSet =
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm:450]: Readability: maybe `systemOverlaysBottomExpectation`, `systemOverlaysBottomResult` and `setSystemOverlaysBottomCall`.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm [hunk 12]
```diff
@@ -417,9 +415,55 @@ - (void)testStatusBarHiddenUpdate {
...
+  [plugin handleMethodCall:methodCallSet result:resultSet];
+  [self waitForExpectationsWithTimeout:1 handler:nil];
+
+  // Update to shown.
+  XCTestExpectation* enableSystemUIOverlaysCalled2 =
+      [self expectationWithDescription:@"setEnabledSystemUIOverlays"];
+  FlutterResult resultSet2 = ^(id result) {
+    [enableSystemUIOverlaysCalled2 fulfill];
+  };
+  FlutterMethodCall* methodCallSet2 =
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm:462]: Readability: maybe `systemOverlaysTopExpectation`, `systemOverlaysTopResult` and `setSystemOverlaysTopCall`.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm [hunk 13]
```diff
@@ -452,9 +496,42 @@ - (void)testStatusBarStyle {
...
+  XCTAssertFalse(flutterViewController.prefersStatusBarHidden);
+
+  FlutterPlatformPlugin* plugin = [engine platformPlugin];
+
+  XCTestExpectation* enableSystemUIModeCalled =
+      [self expectationWithDescription:@"setSystemUIOverlayStyle"];
+  FlutterResult resultSet = ^(id result) {
+    [enableSystemUIModeCalled fulfill];
+  };
+  FlutterMethodCall* methodCallSet =
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm:530]: Similar variable name suggestions as above.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm [hunk 14]
```diff
@@ -0,0 +1,42 @@
+// Copyright 2013 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h"
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.mm:5]: Style: leave a blank line between include groups:

1. associated header
2. C headers
3. C++ headers
4. Other headers

The google style guid breaks group 4 into other headers, our headers, but I think the ship has sailed on that one for Flutter. :)

Ref: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
```suggestion
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h"

```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 15]
```diff
@@ -2657,7 +2658,14 @@ - (void)setKeyboardContainerHeight:(CGFloat)pointerY {
...
 - (void)hideKeyboardWithoutAnimationAndAvoidCursorDismissUpdate {
   [UIView setAnimationsEnabled:NO];
-  _cachedFirstResponder = UIApplication.sharedApplication.keyWindow.flutterFirstResponder;
+  UIApplication* flutterApplication = [FlutterSharedApplication uiApplication];
+  if (flutterApplication != nil) {
+    _cachedFirstResponder = flutterApplication.keyWindow.flutterFirstResponder;
+  } else {
+    _cachedFirstResponder =
+        [_viewController flutterWindowSceneIfViewLoaded].keyWindow.flutterFirstResponder;
+  }
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2667]: Optional: maybe a bit more idiomatic:
```objc
  if (flutterApplication != nil) {
    _cachedFirstResponder = flutterApplication
      ? flutterApplication.keyWindow.flutterFirstResponder
      : self.viewController.flutterWindowSceneIfViewLoaded.keyWindow.flutterFirstResponder;
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 16]
```diff
@@ -2674,8 +2682,14 @@ - (void)takeKeyboardScreenshotAndDisplay {
...
-    [UIApplication.sharedApplication.delegate.window.rootViewController.view
-        addSubview:_keyboardViewContainer];
+    UIApplication* flutterApplication = [FlutterSharedApplication uiApplication];
+    if (flutterApplication != nil) {
+      [flutterApplication.delegate.window.rootViewController.view
+          addSubview:_keyboardViewContainer];
+    } else {
+      [_viewController.viewIfLoaded.window.rootViewController.view
+          addSubview:_keyboardViewContainer];
+    }
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2692]: Similarly:
```objc
  UIView* rootView = flutterApplication
    ? flutterApplication.delegate.window.rootViewController.view
    : self.viewController.viewIfLoaded.window.rootViewController.view;
  [rootView addSubview:_keyboardViewContainer];
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm [hunk 17]
```diff
@@ -849,14 +850,16 @@ - (void)viewDidAppear:(BOOL)animated {
...
-      stateIsActive = self.flutterWindowSceneIfViewLoaded.activationState ==
-                      UISceneActivationStateForegroundActive;
+
+    UIApplication* flutterApplication = [FlutterSharedApplication uiApplication];
+    if (flutterApplication != nil) {
+      stateIsActive = flutterApplication.applicationState == UIApplicationStateActive;
+    } else {
+      if (@available(iOS 13.0, *)) {
+        stateIsActive = self.flutterWindowSceneIfViewLoaded.activationState ==
+                        UISceneActivationStateForegroundActive;
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:860]: Since these are enums, we should use `switch` statements for coverage checking in the lints in the unlikely case future states are ever added. Similar to the background check we do in `FlutterEngine.mm` above, this has the nice side effect of nudging us to extract this check to a method (in the internal API), which improves readability.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm [hunk 18]
```diff
@@ -1386,15 +1389,15 @@ - (void)viewDidLayoutSubviews {
...
-    applicationOrSceneIsActive = self.flutterWindowSceneIfViewLoaded.activationState ==
-                                 UISceneActivationStateForegroundActive;
+  UIApplication* flutterApplication = [FlutterSharedApplication uiApplication];
+  if (flutterApplication != nil) {
+    applicationOrSceneIsActive = flutterApplication.applicationState == UIApplicationStateActive;
+  } else {
+    if (@available(iOS 13.0, *)) {
+      applicationOrSceneIsActive = self.flutterWindowSceneIfViewLoaded.activationState ==
+                                   UISceneActivationStateForegroundActive;
+    }
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:1399]: Similar comment.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm [hunk 19]
```diff
@@ -2003,18 +2006,19 @@ - (void)performOrientationUpdate:(UIInterfaceOrientationMask)new_preferences {
...
-              : [NSSet set];
-#else
-          [UIApplication.sharedApplication.connectedScenes
-              filteredSetUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(
-                                                         id scene, NSDictionary* bindings) {
-                return [scene isKindOfClass:[UIWindowScene class]];
-              }]];
-#endif
+      UIApplication* flutterApplication = [FlutterSharedApplication uiApplication];
+      NSSet<UIScene*>* scenes;
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:2010]: Suggestion to guarantee we never hand a nil `scenes` to `requestGeometryUpdateForWindowScenes:`:
```suggestion
      NSSet<UIScene*>* scenes = [NSSet set];
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm [hunk 20]
```diff
@@ -2003,18 +2006,19 @@ - (void)performOrientationUpdate:(UIInterfaceOrientationMask)new_preferences {
...
+      if (flutterApplication != nil) {
+        scenes = [flutterApplication.connectedScenes
+            filteredSetUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(
+                                                       id scene, NSDictionary* bindings) {
+              return [scene isKindOfClass:[UIWindowScene class]];
+            }]];
+      } else {
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:2017]:
```suggestion
      } else if (self.flutterWindowSceneIfViewLoaded) {
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm [hunk 21]
```diff
@@ -2003,18 +2006,19 @@ - (void)performOrientationUpdate:(UIInterfaceOrientationMask)new_preferences {
...
+        scenes = self.flutterWindowSceneIfViewLoaded
+                     ? [NSSet setWithObject:self.flutterWindowSceneIfViewLoaded]
+                     : [NSSet set];
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:2020]:
```suggestion
        scenes = [NSSet setWithObject:self.flutterWindowSceneIfViewLoaded];
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm [hunk 22]
```diff
@@ -1944,7 +1939,45 @@ - (void)testLifeCycleNotificationBecameActive {
...
+  [flutterViewController viewDidLayoutSubviews];
+  NSNotification* sceneNotification =
+      [NSNotification notificationWithName:UISceneDidActivateNotification object:nil userInfo:nil];
+  NSNotification* applicationNotification =
+      [NSNotification notificationWithName:UIApplicationDidBecomeActiveNotification
+                                    object:nil
+                                  userInfo:nil];
+  id mockVC = OCMPartialMock(flutterViewController);
+  [[NSNotificationCenter defaultCenter] postNotification:sceneNotification];
+  [[NSNotificationCenter defaultCenter] postNotification:applicationNotification];
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm:1963]: Here and below: `NSNotificationCenter.defaultCenter`

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplicationTest.mm [hunk 23]
```diff
@@ -0,0 +1,66 @@
...
+@end
+
+@implementation FlutterSharedApplicationTest
+
+- (void)testWhenNSExtensionInBundle {
+  id mockBundle = OCMPartialMock([NSBundle mainBundle]);
+  OCMStub([mockBundle objectForInfoDictionaryKey:@"NSExtension"]).andReturn(@{
+    @"NSExtensionPointIdentifier" : @"com.apple.share-services"
+  });
+  XCTAssertTrue([FlutterSharedApplication isAppExtension]);
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplicationTest.mm:24]: Here and below: dot notation.

**Review by cbracken — COMMENTED** [review]
This is exciting! Overall looks good!

File: dev/bots/suite_runners/run_verify_binaries_codesigned_tests.dart [hunk 24]
```diff
@@ -89,16 +89,10 @@ List<String> binariesWithoutEntitlements(String flutterRoot) {
     'artifacts/engine/darwin-x64/libtessellator.dylib',
     'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
     'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
-    'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
```
Comment (jmagman) [inline dev/bots/suite_runners/run_verify_binaries_codesigned_tests.dart:92]: You'll need to re-add this until `extension_safe` is removed after a release or so.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm [hunk 25]
```diff
@@ -45,21 +44,23 @@
 using namespace flutter;
 
 static void SetStatusBarHiddenForSharedApplication(BOOL hidden) {
-#if not APPLICATION_EXTENSION_API_ONLY
-  [UIApplication sharedApplication].statusBarHidden = hidden;
-#else
-  FML_LOG(WARNING) << "Application based status bar styling is not available in app extension.";
-#endif
```
Comment (cbracken) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm:52]: So nice to not have preprocessor conditionals in the code anymore!

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Review by jmagman — APPROVED** [review]
