### PR TITLE
Selecting spaces

### LINKED ISSUE #67634: Double tap on CupertinoTextField selects empty string instead of word
Code example:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() = runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp((
      title: 'Cupertino App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final controller = TextEditingController();

    return Scaffold(
      body: Center(
        child: CupertinoTextField(controller: controller),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

How to reproduce:
1. Type something like "123 456 789". Double tap between 123 and 456

**Expected results:** 
123 or 456 should be selected

**Actual results:** 
Empty space is selected

2. Double tap at the beginning or at the end of text field

**Expected results:** 
123 should be selected at the beginning and 789 at the end

**Actual results:** 
Nothing is selected.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.6 19G2021, locale ru-RU)
    • Flutter version 1.22.0 at /Users/nastya/Work/iOS/flutter
    • Framework revision d408d302e2 (9 дней назад), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nastya/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
## Description

On both native Android and native iOS, trying to select a space will instead select the previous word.  This PR brings this functionality to Flutter.  Desktop continues to select the space.

This PR does not address the problem for SelectableText, which is being tracked in https://github.com/flutter/flutter/issues/68226.

## Related Issues

Closes https://github.com/flutter/flutter/issues/67634

## Tests

I tested all combinations I could think of for the following cases:

  * Long pressing
  * Double tapping
  * Desktop and mobile
  * EditableText, TextField, and CupertinoTextField

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -1912,6 +1912,32 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     // If text is obscured, the entire sentence should be treated as one word.
     if (obscureText) {
       return TextSelection(baseOffset: 0, extentOffset: _plainText.length);
+    // If the word is a space, on mobile try to select the previous word
+    // instead.
+    } else if (text?.text != null && word.textInside(text!.text!) == ' '
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:1917]: This should also apply if there's more than one space I think? And there're other types of whitespace characters.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1917]: Tried on iOS, if there's a newline character in between the new spaces it gets included in the selection. I think we insert LRM/RLM between spaces when the text contains both RTL and LTR directions, so that should probably count too.

Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart]: I updated this to use _isWhitespace instead of checking for a hardcoded space character. I also implemented a while loop to look backwards until a non-whitespace character is found.

Also, playing around on Android I realized that Android does not do this behavior, it just selects the space like desktop!  Only selectable non-editable text has this behavior on Android, which I will handle later in my SelectableText issue.  So I updated the code to only do the previous word selection on iOS.

**Comment by justinmc** [comment]
@LongCatIsLooong Could you re-review this when you get a chance?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -1912,6 +1912,38 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
       return TextSelection(baseOffset: 0, extentOffset: _plainText.length);
+    // If the word is a space, on iOS try to select the previous word instead.
+    } else if (text?.text != null
+        && _isWhitespace(text!.text!.codeUnitAt(position.offset))
+        && position.offset > 0) {
+      assert(defaultTargetPlatform != null);
+      switch (defaultTargetPlatform) {
+        case TargetPlatform.iOS:
+          int startIndex = position.offset - 1;
+          while (startIndex > 0 && _isWhitespace(text!.text!.codeUnitAt(startIndex))) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:1923]: nit: it should skip line breaks and `\u200e` `\u200f` as well

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart]: 👍  Added \u200e and \u200f.

It seems to work currently for skipping over lines, is there a specific line break character you mean that is not covered in _isWhitespace?

**Review by LongCatIsLooong — APPROVED** [review]

**Review by gspencergoog — APPROVED** [review]
