### PR TITLE
[Windows] Use dark title bar on dark system theme

### LINKED ISSUE #107926: Dark theme in Windows 10 has a light title bar
## Steps to Reproduce

1. Change Windows theme to Dark Mode.
2. Create a new Flutter project.
3. Use the demo app but change one line to use Dark Mode:
`theme: ThemeData.dark(),`
4. Start the demo app and notice that the title bar is light:
image

Shouldn't the title bar also be dark, since the Windows theme is in dark mode? Microsoft has written about this here https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications but I am wondering if this is something Flutter can do?

**Expected results:** 
Title bar is expected to be dark.

**Actual results:** 
Title bar is light.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by loic-sharma**
Ideally, the app should follow the system theme:

1. **App is aware of the system theme** - The app and its window frame should be able to detect whether the system theme is in dark mode
1. **React to system changes** - If you switch your system theme to dark mode, the app and its window frame should also be able to switch

This change makes Flutter apps have a dark title bar if Windows's theme is set to dark mode. This does nothing on older versions of Windows - like Windows 7 - that don't support dark mode.

Making the app's content follow the system theme will be fixed in subsequent changes and is tracked by https://github.com/flutter/flutter/issues/110700

Fixes https://github.com/flutter/flutter/issues/107926

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/benchmarks/complex_layout/windows/runner/win32_window.cpp [hunk 1]
```diff
@@ -4,12 +4,17 @@
...
+#include <dwmapi.h>
 #include <flutter_windows.h>
 
 #include "resource.h"
 
 namespace {
 
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
```
Comment (loic-sharma) [inline dev/benchmarks/complex_layout/windows/runner/win32_window.cpp:16]: This was added in Windows 11 Build 22000 ([link](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute)). Developers that haven't updated to the latest Windows SDK may not have these defined in their version of `dwmapi.h`. These manual defines prevent these kinds of issues, recommended by: https://docs.microsoft.com/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications

**Comment by tgucio** [comment]
Just tried this and there's a problem in that the window bar will be dark if the system is using dark mode, regardless of whether the Flutter app actually uses dark theme or not (many apps typically allow to override the system setting).

There's a fair question [here](https://github.com/flutter/flutter/issues/107926#issuecomment-1197488690).
Another interesting bit is that Windows 10 has two separate settings under Personalization -> Colors:
* Choose your default Windows mode
* Choose your default app mode
With the changes from this PR, with the 1st set to dark and the 2nd set to light, I was still getting a dark window bar in the Flutter app.

File: packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp [hunk 2]
```diff
@@ -126,6 +131,9 @@ bool Win32Window::Create(const std::wstring& title,
     return false;
   }
 
+  BOOL honorDarkMode = TRUE;
+  DwmSetWindowAttribute(window, DWMWA_USE_IMMERSIVE_DARK_MODE, &honorDarkMode, sizeof(honorDarkMode));
```
Comment (yaakovschectman) [inline packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp:135]: Does setting this window attribute allow the Flutter app context to use the specified dark mode theme instead of its default if provided, or does it affect only the part of the window outside of the Flutter app content?

Comment (loic-sharma) [reply packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp:135]: Good questions! I added more details to the pull request's description to clarify.

> does it affect only the part of the window outside of the Flutter app content?

Yup, that's correct.

> Does setting this window attribute allow the Flutter app context to use the specified dark mode theme instead

This will be done in a future change. We'll need to respond to Windows settings change message in the top-level message handler.

**Comment by loic-sharma** [comment]
> Just tried this and there's a problem in that the window bar will be dark if the system is using dark mode, regardless of whether the Flutter app actually uses dark theme or not (many apps typically allow to override the system setting).

That's correct. Flutter doesn't have the concept of an app theme that's shared between the Dart code and the underlying native code. This is likely something we'll want to add in the future, but it's out-of-scope for this pull request. Apps that don't want to follow the system theme will need to remove this code.

> With the changes from this PR, with the 1st set to dark and the 2nd set to light, I was still getting a dark window bar in the Flutter app.

Thanks for the heads up! I'll mark this PR as a draft while investigate this.

File: dev/benchmarks/complex_layout/windows/runner/win32_window.cpp (hunk 1 above)
Comment (cbracken) [reply dev/benchmarks/complex_layout/windows/runner/win32_window.cpp]: Add a TODO to remove this define when we bump our Windows SDK on the bots.

**Comment by cbracken** [comment]
Thoughts on testing? :)

File: dev/benchmarks/complex_layout/windows/runner/win32_window.cpp (hunk 1 above)
Comment (cbracken) [reply dev/benchmarks/complex_layout/windows/runner/win32_window.cpp]: Sorry since this is code that lives on the developer's machine, this is going to be dependent on which SDK they have installed. This is probably fine as-is, but add a comment about why we're defining it here.

File: dev/integration_tests/windows_startup_test/lib/main.dart [hunk 3]
```diff
@@ -38,14 +41,22 @@ void main() async {
...
-    final bool? visible = await methodChannel.invokeMethod('isWindowVisible');
+    final bool? honorsDarkMode = await methodChannel.invokeMethod<bool?>(
+      'getWindowAttributeBool',
+      <String, dynamic>{'attribute': kUseImmersiveDarkModeAttribute},
+    );
+    if (honorsDarkMode == null || honorsDarkMode == false) {
+      throw 'Window should honor dark mode';
+    }
+
+    final bool? visible = await methodChannel.invokeMethod<bool?>('isWindowVisible');
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/lib/main.dart:52]: I know it's only one line, but consider sticking this in a private method `Future<bool> _isWindowVisible()` for a small improvement in readability.

File: dev/integration_tests/windows_startup_test/lib/main.dart [hunk 4]
```diff
@@ -38,14 +41,22 @@ void main() async {
     const MethodChannel methodChannel =
         MethodChannel('tests.flutter.dev/windows_startup_test');
 
-    final bool? visible = await methodChannel.invokeMethod('isWindowVisible');
+    final bool? honorsDarkMode = await methodChannel.invokeMethod<bool?>(
+      'getWindowAttributeBool',
+      <String, dynamic>{'attribute': kUseImmersiveDarkModeAttribute},
+    );
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/lib/main.dart:47]: Consider sticking this in a private method `Future<bool> _honorsDarkMode` method.

File: dev/integration_tests/windows_startup_test/lib/main.dart [hunk 5]
```diff
@@ -8,6 +8,9 @@ import 'dart:ui' as ui;
 import 'package:flutter/services.dart';
 import 'package:flutter_driver/driver_extension.dart';
 
+// https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/lib/main.dart:11]: Add a bit more detail and use a doc comment.

```dart
/// Window attribute that specifies whether a window supports
/// drawing its window decorations in dark mode colors when the
/// dark mode system setting is enabled.
///
/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
```

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp [hunk 6]
```diff
@@ -50,11 +65,29 @@ bool FlutterWindow::OnCreate() {
...
-    [](const flutter::MethodCall<>& call,
+    [&](const flutter::MethodCall<>& call,
        std::unique_ptr<flutter::MethodResult<>> result) {
       std::scoped_lock lock(visible_mutex);
-      if (call.method_name() == "isWindowVisible") {
+      std::string method = call.method_name();
+
+      if (method == "isWindowVisible") {
         result->Success(visible);
+      } else if (method == "getWindowAttributeBool") {
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp:75]: Given how specific this test is to dark mode, I'd just call this method `supportsDarkMode` and not bother passing the window attribute enum value across as a parameter but just hardcode it here. We're unlikely to ever expose the enum value to actual Dart code, no not something we probably need to explicitly test from the Dart side of the test.

File: dev/integration_tests/windows_startup_test/lib/main.dart (hunk 3 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/main.dart]: Done!

File: dev/integration_tests/windows_startup_test/lib/main.dart (hunk 4 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/main.dart]: Done!

File: dev/integration_tests/windows_startup_test/lib/main.dart (hunk 5 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/main.dart]: This was deleted since all Windows logic was moved to C++

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp (hunk 6 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp]: Done! I moved all Windows logic from the Dart layer down to the C++ layer.

(FWIW, I wrote it this way as eventually I'd like this to use FFI instead of method channels. The code was meant to be close to what the FFI version would be. Until then, it makes sense to keep things simple!)

File: dev/benchmarks/complex_layout/windows/runner/win32_window.cpp (hunk 1 above)
Comment (loic-sharma) [reply dev/benchmarks/complex_layout/windows/runner/win32_window.cpp]: Added a comment!

**Comment by loic-sharma** [comment]
@tgucio @yaakovschectman @cbracken Please take another look! :)

**Review by yaakovschectman — APPROVED** [review]

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

File: dev/integration_tests/windows_startup_test/lib/windows.dart [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+/// Check whether the app's dark mode is enabled.
+Future<bool> isAppDarkModeEnabled() async {
+  final bool? enabled = await _kMethodChannel.invokeMethod<bool?>('isAppDarkModeEnabled');
+  if (enabled == null) {
+    throw 'Method channel unavailable';
+  }
+
+  return enabled;
+}
+
```
[the remark this answers is not in the document]
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/windows.dart:29]: Whoops, missed this one. Fixed!

File: dev/integration_tests/windows_startup_test/lib/windows.dart [hunk 8]
```diff
@@ -0,0 +1,37 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/services.dart';
+
+const MethodChannel _kMethodChannel =
+  MethodChannel('tests.flutter.dev/windows_startup_test');
+
+/// Check that the application's window is visible.
```
[the remark this answers is not in the document]
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/windows.dart]: Fixed!

File: dev/integration_tests/windows_startup_test/lib/windows.dart [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+Future<bool> isWindowVisible() async {
+  final bool? visible = await _kMethodChannel.invokeMethod<bool?>('isWindowVisible');
+  if (visible == null) {
+    throw 'Method channel unavailable';
+  }
+
+  return visible;
+}
+
+/// Check whether the app's dark mode is enabled.
```
[the remark this answers is not in the document]
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/lib/windows.dart]: Fixed!

**Review by cbracken — APPROVED** [review]

**Comment by jmagman** [comment]
This was reverted in https://github.com/flutter/flutter/pull/110890
