### PR TITLE
Fix Material 3 `Dialog` default background color

### LINKED ISSUE #148849: [Material 3] Wrong `Dialog` background color from ColorScheme
### Steps to reproduce

1. Define a theme in your MaterialApp
2. Set surface to Colors.black and surfaceContainerHigh to Colors.red
3. call showAboutDialog

### Expected results

The dialog should have the backgroundColor set to the value of surfaceContainerHigh

### Actual results

backgroundColor is set to Theme.of(context).dialogBackgroundColor (old M2 implementation)

### Code sample

<details open><summary>Code sample</summary>

```dart
// in build method of Dialog widget

color: backgroundColor ?? dialogTheme.backgroundColor ?? Theme.of(context).dialogBackgroundColor,

// should be

color: backgroundColor ?? dialogTheme.backgroundColor ?? defaults.backgroundColor,
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [[Material 3] Wrong `Dialog` background color from ColorScheme](https://github.com/flutter/flutter/issues/148849
)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [showDialog].

void main() => runApp(const ShowDialogExampleApp());

class ShowDialogExampleApp extends StatelessWidget {
  const ShowDialogExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const DialogExample(),
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          surfaceContainerHigh: Colors.amber,
        ),
      ),
    );
  }
}

class DialogExample extends StatelessWidget {
  const DialogExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('showDialog Sample')),
      body: Center(
        child: OutlinedButton(
          onPressed: () => _dialogBuilder(context),
          child: const Text('Open Dialog'),
        ),
      ),
    );
  }

  Future<void> _dialogBuilder(BuildContext context) {
    return showDialog<void>(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Basic dialog title'),
          content: const Text(
            'A dialog is a type of modal window that\n'
            'appears in front of app content to\n'
            'provide critical information, or prompt\n'
            'for a decision to be made.',
          ),
          actions: <Widget>[
            TextButton(
              style: TextButton.styleFrom(
                textStyle: Theme.of(context).textTheme.labelLarge,
              ),
              child: const Text('Disable'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            TextButton(
              style: TextButton.styleFrom(
                textStyle: Theme.of(context).textTheme.labelLarge,
              ),
              child: const Text('Enable'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }
}
```

</details>

### Before

Screenshot 2024-07-08 at 14 26 39

### After

Screenshot 2024-07-08 at 14 26 28

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/dialog_test.dart [hunk 1]
```diff
@@ -130,7 +130,7 @@ void main() {
     await tester.pumpAndSettle();
 
     final Material materialWidget = _getMaterialFromDialog(tester);
-    expect(materialWidget.color, theme.colorScheme.surface);
+    expect(materialWidget.color, theme.colorScheme.surfaceContainerHigh);
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dialog_test.dart:133]: Can we also correct the test message to "M3 Dialog background defaults to ColorScheme.surfaceContainerHigh"? Probably can also update the `colorScheme` part:)

File: packages/flutter/lib/src/material/dialog.dart [hunk 2]
```diff
@@ -86,6 +86,7 @@ class Dialog extends StatelessWidget {
   /// This sets the [Material.color] on this [Dialog]'s [Material].
   ///
   /// If `null`, [ColorScheme.surfaceContainerHigh] is used in Material 3.
+  /// Otherwise, defaults to [ThemeData.dialogBackgroundColor].
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dialog.dart:89]: We probably can also mention, in fullscreen dialog, the default background color is `ColorScheme.surface`.

**Review by QuncCccccc — APPROVED** [review]
Thanks for the fix! LGTM:)

File: packages/flutter/test/material/dialog_test.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dialog_test.dart:133]: I updated the title and color scheme but "M3" isn't necessary since we no longer label M3 tests, it's default.

File: packages/flutter/lib/src/material/dialog.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dialog.dart:89]: Great idea!

**Comment by QuncCccccc** [comment]
This breaks some tests in Google testing. I'm creating a g3fix:)

**Comment by TahaTesser** [comment]
> This breaks some tests in Google testing. I'm creating a g3fix:)

You're the best!

**Comment by QuncCccccc** [comment]
Got approval from internal team, so I just marked this as expected:)
