### PR TITLE
[Impeller] For Android hardware buffers on Vulkan, use an alpha value of 1 if the buffer format always has opaque alpha

### LINKED ISSUE #182825: [Impeller/Android/Vulkan] issues rendering video with Impeller/Vulkan
### Steps to reproduce

I'm trying to show a (local) video using [Livekit](https://github.com/livekit/client-sdk-flutter/), which internally uses [Flutter WebRTC](https://github.com/flutter-webrtc/flutter-webrtc).

### Expected results

See lokal video, same as when using Impeller/OpenGLES or Skia

### Actual results

With standard settings (i.e. Impeller with Vulkan), depending on the phone, I see the local video, but with transparency, i.e. widgets behind the video shine through (see screenshots below)

Broken phone: Samsung Galaxy A14 (SM-A145R/DSN)
Working phone: Fairphone 5 5G

### Code sample

Unfortunately, I could not reproduce it with the official video player example. Here's a fork of Livekits Flutter Components with red video background to better see effect:

https://github.com/livekit/components-flutter/compare/main...holzgeist:components-flutter:debug-impeller-render-issue

### Screenshots or Video

<details><summary>Impeller/Vulkan</summary>

Image

</details>

<details><summary>Impeller/OpenGLES</summary>

Image

</details>

<details><summary>Skia</summary>

Image

</details>

### Logs

[impeller-vulkan.log](https://github.com/user-attachments/files/25519676/impeller-vulkan.log)

[impeller-opengles.log](https://github.com/user-attachments/files/25519680/impeller-opengles.log)

[skia.log](https://github.com/user-attachments/files/25519682/skia.log)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.41.2, on Arch Linux 6.18.9-arch1-2, locale en_US.UTF-8) [34ms]
    • Flutter version 3.41.2 on channel stable at /home/tobias/src/3rdparty/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 90673a4eef (6 days ago), 2026-02-18 13:54:59 -0800
    • Engine revision 6c0baaebf7
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets,
      omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [1,945ms]
    • Android SDK at /home/tobias/Android/Sdk
    • Emulator version 36.3.10.0 (build_id 14472402) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /home/tobias/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.9+-14649483-b1163.86)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [6ms]
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop [526ms]
    • clang version 21.1.8
    • cmake version 4.2.3
    • ninja version 1.13.2
    • pkg-config version 2.5.1
    • OpenGL core renderer: AMD Radeon 740M Graphics (radeonsi, phoenix, LLVM 21.1.6, DRM 3.64, 6.18.9-arch1-2)
    • OpenGL core version: 4.6 (Core Profile) Mesa 25.3.5-arch1.1
    • OpenGL core shading language version: 4.60
    • OpenGL ES renderer: AMD Radeon 740M Graphics (radeonsi, phoenix, LLVM 21.1.6, DRM 3.64, 6.18.9-arch1-2)
    • OpenGL ES version: OpenGL ES 3.2 Mesa 25.3.5-arch1.1
    • OpenGL ES shading language version: OpenGL ES GLSL ES 3.20
    • GL_EXT_framebuffer_blit: yes
    • GL_EXT_texture_format_BGRA8888: yes

[✓] Connected device (3 available) [461ms]
    • SM A145R (mobile) • 172.16.60.78:46423 • android-arm64  • Android 15 (API 35)
    • Linux (desktop)   • linux              • linux-x64      • Arch Linux 6.18.9-arch1-2
    • Chrome (web)      • chrome             • web-javascript • Chromium 145.0.7632.109 Arch Linux

[✓] Network resources [241ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by jason-simmons**
The AHARDWAREBUFFER_FORMAT_R8G8B8X8_UNORM format specifies that the alpha value should be ignored and should always be treated as opaque.  For this format, configure the VkComponentMapping to set alpha to VK_COMPONENT_SWIZZLE_ONE.

Fixes https://github.com/flutter/flutter/issues/182825

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc [hunk 1]
```diff
@@ -28,85 +28,12 @@ bool RequiresYCBCRConversion(vk::Format format) {
...
-
-  auto image = device.createImageUnique(image_chain.get());
-  if (image.result != vk::Result::eSuccess) {
-    VALIDATION_LOG << "Could not create image for external buffer: "
-                   << vk::to_string(image.result);
-    return {};
-  }
-
-  return std::move(image.value);
+bool HardwareBufferFormatHasOpaqueAlpha(AHardwareBuffer_Format format) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc]:
```suggestion
bool IsOpaque(AHardwareBuffer_Format format) {
```

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc [hunk 2]
```diff
@@ -28,85 +28,12 @@ bool RequiresYCBCRConversion(vk::Format format) {
...
+  return format == AHARDWAREBUFFER_FORMAT_R8G8B8X8_UNORM;
 }
 
+using AHBProperties = AHBTextureSourceVK::AHBProperties;
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc]: nit: put at the beginning of the scope

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc [hunk 3]
```diff
@@ -440,4 +322,117 @@ const android::HardwareBuffer* AHBTextureSourceVK::GetBackingStore() const {
...
+  }
+
+  auto image = device.createImageUnique(image_chain.get());
+  if (image.result != vk::Result::eSuccess) {
+    VALIDATION_LOG << "Could not create image for external buffer: "
+                   << vk::to_string(image.result);
+    return {};
+  }
+
+  return std::move(image.value);
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc:399]: I don't think you want to move in the return statement, that subverts copy elision.

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.h [hunk 4]
```diff
@@ -61,6 +61,27 @@ class AHBTextureSourceVK final : public TextureSourceVK {
...
+  static vk::UniqueImage CreateVKImageWrapperForAndroidHarwareBuffer(
+      const vk::Device& device,
+      const AHBProperties& ahb_props,
+      const AHardwareBuffer_Desc& ahb_desc);
+
+  static ImageViewInfo CreateImageViewInfo(
+      const vk::Image& image,
+      const std::shared_ptr<YUVConversionVK>& yuv_conversion_wrapper,
+      const AHBProperties& ahb_props,
+      const AHardwareBuffer_Desc& ahb_desc);
```
[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.h:86]: +1

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc [hunk 5]
```diff
@@ -94,4 +94,46 @@ TEST(AndroidVulkanTest, CanImportWithYUB) {
...
+  desc.rfu0 = 0;
+  desc.rfu1 = 0;
+  desc.usage = AHARDWAREBUFFER_USAGE_GPU_SAMPLED_IMAGE |
+               AHARDWAREBUFFER_USAGE_CPU_WRITE_MASK |
+               AHARDWAREBUFFER_USAGE_CPU_READ_MASK;
+
+  EXPECT_EQ(AHardwareBuffer_isSupported(&desc), 1);
+
+  AHardwareBuffer* buffer = nullptr;
+  ASSERT_EQ(AHardwareBuffer_allocate(&desc, &buffer), 0);
```
[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc]: +1

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc [hunk 6]
```diff
@@ -94,4 +94,46 @@ TEST(AndroidVulkanTest, CanImportWithYUB) {
...
+            vk::Result::eSuccess);
+
+  auto image = AHBTextureSourceVK::CreateVKImageWrapperForAndroidHarwareBuffer(
+      context_vk->GetDevice(), ahb_props, desc);
+  ASSERT_TRUE(image);
+
+  auto image_info = AHBTextureSourceVK::CreateImageViewInfo(
+      image.get(), nullptr, ahb_props, desc);
+
+  ASSERT_EQ(image_info.get().components.a, vk::ComponentSwizzle::eOne);
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc]:
```suggestion
  EXPECT_EQ(image_info.get().components.a, vk::ComponentSwizzle::eOne);
```

**Review by gaaclarke — COMMENTED** [review]
Looks good for the most part, just some minor notes.  Thanks jason.

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc]: done

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.h:86]: done

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc (hunk 1 above)
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc]: done

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc (hunk 2 above)
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc]: done

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc (hunk 3 above)
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc:399]: `std::move` is necessary because `vk::UniqueImage` does not have a copy constructor

File: engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc (hunk 6 above)
Comment (jason-simmons) [reply engine/src/flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk_unittests.cc]: done

**Review by gaaclarke — APPROVED** [review]
thanks jason!
