### PR TITLE
fix platform environment

### LINKED ISSUE #40694: flutter upgrade crash report
## Steps to Reproduce

1. flutter channel master
2. flutter upgrade

## command

flutter upgrade

## exception

UnsupportedError: Unsupported operation: Cannot modify unmodifiable map

```
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:262:5)
#1      _DefaultProcessUtils._environment (package:flutter_tools/src/base/process.dart:516:20)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:415:20)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:430:35)
<asynchronous suspension>
#4      UpgradeCommandRunner.flutterUpgradeContinue (package:flutter_tools/src/commands/upgrade.dart:125:41)
<asynchronous suspension>
#5      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:121:11)
<asynchronous suspension>
#6      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:76:13)
<asynchronous suspension>
#7      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:56:32)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:519:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.3-pre.70, on Linux, locale en_CA.UTF-8)
    [32m•[39m Flutter version 1.10.3-pre.70 at /home/mmelvin/dev/flutter
    [32m•[39m Framework revision a50eda8f5a (6 minutes ago), 2019-09-17 19:22:28 +0200
    [32m•[39m Engine revision 63873d9f42
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 7799f424f4)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/mmelvin/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /home/mmelvin/dev/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/mmelvin/dev/android-studio
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.4.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

This is an unmodifiable map, need to clone

Fixes https://github.com/flutter/flutter/issues/40694

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -131,7 +131,7 @@ class UpgradeCommandRunner {
       ],
       workingDirectory: Cache.flutterRoot,
       allowReentrantFlutter: true,
-      environment: platform.environment,
+      environment: Map<String, String>.of(platform.environment),
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/commands/upgrade.dart]: We can check this fix by making the environment from the fake platform in the upgrade tests unmodifiable:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/commands/upgrade_test.dart#L49

**Review by zanderso — APPROVED** [review]

**Review by christopherfujino — APPROVED** [review]
Nice catch, LGTM
