### PR TITLE
Fix issue #156954: Wrong dateHelpText in MaterialLocalizationIt

### LINKED ISSUE #156954: Wrong dateHelpText in MaterialLocalizationIt - flutter_localizations
### Steps to reproduce

The current value for `dataHelpText` used in `MaterialLocalizationIt` is `"mm/gg/aaaa"` but it should be `"gg/mm/aaaa"`, as the standard order for dates in Italian is day/month/year (giorno/mese/anno in Italian)

### Expected results

`String get dateHelpText => `gg/mm/aaaa';`

### Actual results

`String get dateHelpText => 'mm/gg/aaaa';`

### Code sample

Permalink to the line of code: https://github.com/flutter/flutter/blob/2430f00a01a72c6d80085e1afdf179374e06355f/packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart#L21192

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Not applicable

### PR DESCRIPTION
**Pull request by Paulik8**
Fix #156954
- Changed current value `dataHelpText` used in `MaterialLocalizationIt` from "mm/gg/aaaa" to "gg/mm/aaaa"
- Wrote test

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by Paulik8** [comment]
By the way, for some reason, after signing the agreement in the welcome channel on your Discord server, I get kicked out after a few minutes. However, I can rejoin using the invite link, but the same thing happens again and again. I couldn’t find information in the documentation on who to contact about this, but since you’re the observer of Issue#156954 and also a team member, Kate, I decided to tag you.

Perhaps you could also take a look at my pull request? :) 
I would greatly appreciate your help! 

cc @Piinks

File: packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart [hunk 1]
```diff
@@ -21192,7 +21192,7 @@ class MaterialLocalizationIt extends GlobalMaterialLocalizations {
   String get cutButtonLabel => 'Taglia';
 
   @override
-  String get dateHelpText => 'mm/gg/aaaa';
+  String get dateHelpText => 'gg/mm/aaaa';
```
Comment (victorsanni) [inline packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart:21195]: At the top of this file:
```
// This file has been automatically generated. Please do not edit it manually.
```

Comment (victorsanni) [reply packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart:21195]: Was this change added manually, or by regenerating this file?

Comment (Paulik8) [reply packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart:21195]: Yes, I generated it by `dart dev/tools/localization/bin/gen_localizations.dart --overwrite` as it described in [this chapter](https://github.com/flutter/flutter/blob/56bf5fc624c60b0ffb4c6faf75e1ff920f7b00e1/packages/flutter_localizations/lib/src/l10n/README.md#generated__localizationsdart-all-of-the-localizations)

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the fix!

**Review by victorsanni — APPROVED** [review]

**Comment by Piinks** [comment]
Rebased to resolve an unrelated flaky golden file test. This should be able to land now.
