### PR TITLE
[framework] ensure ink sparkle is disposed

### LINKED ISSUE #104229: Severe jank observed when enabling useMaterial3 in Flutter 3
Turning on `useMaterial3` flag in Flutter 3 caused app to slow down with very severe jank after a while of use. This issue is observed in both my test devices: Xiaomi Mi A2 (Android 10) and Oppo R9s (Android 6.0.1). Probably has to do with the shader-use implementation in Material 3?

## Steps to Reproduce

1. Create an app with `flutter create`.
2. Add `useMaterial3: true` to `ThemeData`.
3. Run app in Profile mode on Android device.
4. Launch **DevTools** > **Open Performance Page**.
5. Tap '+' button repeatedly and observe DevTools performance chart.

Repeat steps by omitting useMaterial3 or setting the flag to false and compare performance results.

**Expected results:**

Consistent near-60 FPS throughout.

**Actual results:** 

useMaterial3 == true: 
Decreasing FPS with repeated taps on '+' button. After 200 taps, framerate dropped to 28 FPS on Xiaomi Mi A2 and 16 FPS on Oppo R9s.

useMaterial3 == false: 
Results are as expected.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      // drawer: Drawer(
      //   child: Container(),
      // ),
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1706], locale en-MY)
    • Flutter version 3.0.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (10 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Jason\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = C:\Users\Jason\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29215.179
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++"
      workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.67.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • Mi A2 (mobile)    • 2adfa93 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**useMaterial3: true (after 200 taps)**

Screenshot 2022-05-20 113115

**useMaterial3: false (after 200 taps)**

Screenshot 2022-05-20 113658

### LINKED ISSUE #104545: Repeatedly triggering material 3 ink sparkle leads to permanent raster slowdown
## Details

When i use material 3 is true and press to icon button many times in list all view get lagged and drop frame happened to 28hz

https://user-images.githubusercontent.com/30121703/170135403-3c6b312c-77c0-44ef-a8df-69f242fe1043.mp4

**ِAndroid:**
**Android 12:**
**Tested on mi9t and samsung A22:**

```
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.5.2 20G95 darwin-x64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.67.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

```
```

**Tested Code**
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> _list = [
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: ListView.builder(
                itemCount: _list.length,
                itemBuilder: (context, index) => ItemLine(),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class ItemLine extends StatelessWidget {
  const ItemLine({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text("TEST"),
                    Row(
                      children: [
                        IconButton(
                          onPressed: () {},
                          icon: const Icon(
                            Icons.remove_circle_outline,
                          ),
                        ),
                        Text("1"),
                        IconButton(
                          onPressed: () {},
                          icon: const Icon(
                            Icons.add_circle,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
        const Divider()
      ],
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/104545
Fixes https://github.com/flutter/flutter/issues/104229

The ink sparkle is never disposed, leading to a massive saveLayer buildup

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Tests updated

File: packages/flutter/test/material/ink_sparkle_test.dart [hunk 1]
```diff
@@ -48,16 +48,15 @@ void main() {
     final Finder buttonFinder = find.text('Sparkle!');
     await tester.tap(buttonFinder);
     await tester.pump();
-    await tester.pumpAndSettle();
```
Comment (jonahwilliams) [inline packages/flutter/test/material/ink_sparkle_test.dart:51]: Im not really sure why this worked before. I think pumpAndSettling past the animation duration still worked since we would continue painting it forever

File: packages/flutter/lib/src/material/ink_sparkle.dart [hunk 2]
```diff
@@ -209,6 +211,11 @@ class InkSparkle extends InteractiveInkFeature {
     _turbulenceSeed = turbulenceSeed ?? math.Random().nextDouble() * 1000.0;
   }
 
+  void _handleStatusChanged(AnimationStatus status) {
+    if (status == AnimationStatus.completed)
+      dispose();
```
Comment (dnfield) [inline packages/flutter/lib/src/material/ink_sparkle.dart:216]: can we test this?

For example, add some kind of `debugHasFeature` API on `MaterialInkController` and assert in a test that once the animation is done the controller doesn't contain this feature anymore?

**Comment by dnfield** [comment]
This should get cherry-picked into stable when it lands.

File: packages/flutter/lib/src/material/ink_sparkle.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/ink_sparkle.dart:216]: MaterialInkController is often implemented, so adding `debugHasFeature ` may be breaking

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/ink_sparkle.dart:216]: behold

Comment (dnfield) [reply packages/flutter/lib/src/material/ink_sparkle.dart:216]: Thanks I hate it

**Review by dnfield — APPROVED** [review]
LGTM
