### PR TITLE
fix:: elevation and scrollUnderElevation depends on scrolling drawers on issue #120083

### LINKED ISSUE #120083: Elevation and scrollUnderElevation depends on scrolling in NavigationDrawer
#91605

https://user-images.githubusercontent.com/102767277/216998500-414e2bbf-d0ad-4c86-88ab-bb9333f6f885.mp4

```
import 'package:flutter/material.dart';
import 'package:dynamic_color/dynamic_color.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return DynamicColorBuilder(
      builder: (lightDynamic, darkDynamic) {
        return MaterialApp(
          title: 'Test AppBar',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            useMaterial3: true,
            brightness: Brightness.light,
            colorScheme: lightDynamic,
          ),
          darkTheme: ThemeData(
            useMaterial3: true,
            brightness: Brightness.dark,
            colorScheme: darkDynamic,
          ),
          home: IterableList(),
        );
      },
    );
  }
}

class IterableList extends StatelessWidget {
  const IterableList({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Small TopAppBar'),
        actions: [
          IconButton(onPressed: () {}, icon: Icon(Icons.favorite)),
          IconButton(onPressed: () {}, icon: Icon(Icons.favorite)),
        ],
        shape: Border.all(color: Colors.transparent),
        toolbarHeight: 64,
      ),
      drawer: MyNavigationDrawer(),
      body: ListView.builder(
        itemCount: 76,
        itemBuilder: (context, index) {
          return Padding(
            padding: EdgeInsets.only(left: 15, bottom: 6),
            child: Text(index.toString(), style: TextStyle(fontSize: 16)),
          );
        },
      ),
      floatingActionButton: FloatingActionButton.large(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}

class MyNavigationDrawer extends StatefulWidget {
  const MyNavigationDrawer({super.key});

  @override
  State<MyNavigationDrawer> createState() => _MyNavigationDrawerState();
}

class _MyNavigationDrawerState extends State<MyNavigationDrawer> {
  int selectedIndex = 0;

  void onDestinationSelected(int index) {
    setState(() {
      selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return NavigationDrawer(
      selectedIndex: selectedIndex,
      onDestinationSelected: onDestinationSelected,
      children: [
        /*Padding(
          padding: EdgeInsets.fromLTRB(28, 16, 16, 10),
          child: Text('Mail', style: Theme.of(context).textTheme.titleSmall),
        ),*/
        Padding(
          padding: EdgeInsets.only(left: 28),
          child: Text(
            'Navigation Drawer',
             style: GoogleFonts.manrope(
               fontWeight: FontWeight.w500,
               textStyle: Theme.of(context).textTheme.titleLarge,
               height: 3,
            ),
          ),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.token_outlined),
          selectedIcon: Icon(Icons.token),
          label: Text('Inbox'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.mail_outline),
          selectedIcon: Icon(Icons.mail),
          label: Text('OutBox'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.favorite_border_outlined),
          selectedIcon: Icon(Icons.favorite),
          label: Text('Favorites'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.delete_outline),
          selectedIcon: Icon(Icons.delete),
          label: Text('Trash'),
        ),
        Divider(indent: 28, endIndent: 28),
        Padding(
          padding: EdgeInsets.fromLTRB(28, 16, 16, 10),
          child: Text('Labels', style: Theme.of(context).textTheme.titleSmall),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.circle_outlined),
          label: Text('Label circle'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.change_history),
          label: Text('Label triagle'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.square_outlined),
          label: Text('Label square'),
        ),
        Divider(indent: 28, endIndent: 28),
        Center(
          child: TextButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: OutlinedButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: ElevatedButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton.tonal(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton.tonalIcon(
            onPressed: () {},
            icon: Icon(Icons.replay_circle_filled_outlined),
            label: Text('Cards screen'),
          ),
        ),
      ],
    );
  }
}
```

### PR DESCRIPTION
**Pull request by Mairramer**
fixes https://github.com/flutter/flutter/issues/120083

Description
This PR addresses the following issues:
- Resolves the unexpected scrolledUnderElevation trigger that occurs when scrolling within the Drawer and NavigationDrawer.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -760,12 +760,18 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
   void didChangeDependencies() {
     super.didChangeDependencies();
+    if (Scaffold.maybeOf(context)?.isDrawerOpen ?? false) {
+      _scrollNotificationObserver?.removeListener(_handleScrollNotification);
+      _scrollNotificationObserver = null;
+      return;
+    }
     _scrollNotificationObserver?.removeListener(_handleScrollNotification);
     _scrollNotificationObserver = ScrollNotificationObserver.maybeOf(context);
     _scrollNotificationObserver?.addListener(_handleScrollNotification);
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:777]: This could just be: 
```suggestion
    _scrollNotificationObserver?.removeListener(_handleScrollNotification);
    if (!Scaffold.maybeOf(context)?.isDrawerOpen ?? true) {
      _scrollNotificationObserver = ScrollNotificationObserver.maybeOf(context);
      _scrollNotificationObserver?.addListener(_handleScrollNotification);
    }
```

File: packages/flutter/lib/src/material/app_bar.dart [hunk 2]
```diff
@@ -777,11 +783,25 @@ class _AppBarState extends State<AppBar> {
       _scrollNotificationObserver!.removeListener(_handleScrollNotification);
       _scrollNotificationObserver = null;
     }
+    _notificationListenerStates.clear();
     super.dispose();
   }
 
   void _handleScrollNotification(ScrollNotification notification) {
     if (notification is ScrollUpdateNotification && widget.notificationPredicate(notification)) {
+      final RawGestureDetector? rawGestureDetector = notification.context?.widget as RawGestureDetector?;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:792]: Why do we need the gesture detector?

File: packages/flutter/test/material/app_bar_test.dart [hunk 3]
```diff
@@ -2563,6 +2563,217 @@ void main() {
       expect(getAppBarBackgroundColor(tester), defaultColor);
       expect(tester.getSize(findAppBarMaterial()).height, kToolbarHeight);
     });
+
+    testWidgets('Material3 - scrolledUnderElevation should be maintained when drawer is opened', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:2567]: Can you add to this test to verify that after the drawer is closed the app bar responds to scrolling again as expected?

File: packages/flutter/test/material/app_bar_test.dart [hunk 4]
```diff
@@ -2563,6 +2563,217 @@ void main() {
...
+                  : defaultColor;
+              }),
+              title: const Text('AppBar'),
+              notificationPredicate: (ScrollNotification notification) {
+                // Represents both scroll views below being treated as a
+                // single viewport.
+                return notification.depth <= 1;
+              },
+            ),
+            drawer: const Drawer(),
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:2585]: Shouldn't the Drawer contain something that scrolls to validate the bug does not reproduce anymore?

File: packages/flutter/test/material/app_bar_test.dart [hunk 5]
```diff
@@ -2563,6 +2563,217 @@ void main() {
...
+              backgroundColor: MaterialStateColor.resolveWith((Set<MaterialState> states) {
+                return states.contains(MaterialState.scrolledUnder)
+                  ? scrolledColor
+                  : defaultColor;
+              }),
+              title: const Text('AppBar'),
+              notificationPredicate: (ScrollNotification notification) {
+                // Represents both scroll views below being treated as a
+                // single viewport.
+                return notification.depth <= 1;
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:2582]: Why is this necessary?

File: packages/flutter/test/material/app_bar_test.dart [hunk 6]
```diff
@@ -2563,6 +2563,217 @@ void main() {
...
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:2644]: Same here, I am not sure why this is needed.

File: packages/flutter/test/material/app_bar_test.dart [hunk 7]
```diff
@@ -2563,6 +2563,217 @@ void main() {
...
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:2720]: And here. The depth would not be increased in this case. Each should have a depth of 0.

File: packages/flutter/lib/src/material/app_bar.dart (hunk 2 above)
Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:792]: When we have two lists side by side, when scrolling through both and then returning one of the two to the top, the `scrolledUnderElevation` does not remain. However, since each list has its own `RawGestureDetector`, we can track each list individually to see if we can disable our `scrolledUnderElevation`.

Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart:792]: Hmm, it feels kind of brittle. ScrollPositions dispatch scroll notifications, it is possible that there is no RawGestureDetector if there is no Scrollable. Some folks have their own custom Scrollable classes. Is there another way we can differentiate multiple scrollables?

File: packages/flutter/lib/src/material/app_bar.dart [hunk 8]
```diff
@@ -777,11 +782,26 @@ class _AppBarState extends State<AppBar> {
...
     if (notification is ScrollUpdateNotification && widget.notificationPredicate(notification)) {
+      // Each RawGestureDetector has its own scroll offset, so we need to keep track of them separately.
+      final RawGestureDetector? rawGestureDetector = notification.context?.widget as RawGestureDetector?;
+
+      if (rawGestureDetector != null) {
+        _notificationListenerStates[rawGestureDetector] = notification.metrics.axisDirection == AxisDirection.down
+        ? notification.metrics.extentBefore
+        : notification.metrics.extentAfter;
+
+        // If any of the scroll offsets are greater than 0, then the MaterialState.scrolledUnder
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:799]: This isn't true if they are horizontal is it?

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: A dubious message in the code. 🤫

File: packages/flutter/lib/src/material/app_bar.dart (hunk 2 above)
Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:792]: I'm trying to look at this more clearly. From what I could tell, everything led me to RawGestureDetector as being what was behind it all. I tested several in one app and it worked very well.
But I agree that it feels kind of brittle.

Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart:792]: > RawGestureDetector as being what was behind it all

Do you mean the cause of the issue?

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:792]: I'm sorry, I expressed myself poorly. I'm talking more about interactions with the list and any scrollable widget.
There is always a RawGestureDetector that interacts with the widgets, so I decided to use it to observe the changes.

Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart:792]: Ok, no worries! Thank you for clarifying. :)

I don't think this is a reliable way to catch this. Would you like to consider a different approach?

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: I made a small change, but it's still not ideal. I need to analyze and see if there really is a better way with what we have today or create something new.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: I made a change to observe the `ScrollableState` instead of the `Widget`(RawGestureDetector).

File: packages/flutter/lib/src/material/app_bar.dart [hunk 9]
```diff
@@ -777,11 +782,28 @@ class _AppBarState extends State<AppBar> {
...
+      // The notification context of a ScrollNotification points to the RawGestureDetector
+      // of the Scrollable. We get the ScrollableState associated with this notification
+      // by looking up the tree.
+      final ScrollableState? notificationScrollableState = notification.context?.findAncestorStateOfType<ScrollableState>();
+
+      if (notificationScrollableState != null) {
+        final double newPixels = notification.metrics.pixels;
+        _notificationListenerStates[notificationScrollableState] = newPixels;
+
+        // Check if any scroll positions on the vertical axis are greater than 0
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:800]: Where did we check that they were vertical?

**Review by Piinks — COMMENTED** [review]
Thank you for the update, I am still not sure this is the best way to resolve this issue. I think I recall @TahaTesser looking at this before. @TahaTesser do you have any thoughts on this? Or insight on your past investigation here?

File: packages/flutter/lib/src/material/app_bar.dart [hunk 10]
```diff
@@ -777,11 +782,28 @@ class _AppBarState extends State<AppBar> {
...
   void _handleScrollNotification(ScrollNotification notification) {
     if (notification is ScrollUpdateNotification && widget.notificationPredicate(notification)) {
+      // The notification context of a ScrollNotification points to the RawGestureDetector
+      // of the Scrollable. We get the ScrollableState associated with this notification
+      // by looking up the tree.
+      final ScrollableState? notificationScrollableState = notification.context?.findAncestorStateOfType<ScrollableState>();
+
+      // Check if any scroll positions on the vertical axis have been updated.
+      // If so, update the scroll position for the associated ScrollableState.
+      if (notificationScrollableState is ScrollableState && notification.metrics.axis == Axis.vertical) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:798]: Using `is` is not permitted by the style guide: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-interleaving-multiple-concepts-together

**Comment by TahaTesser** [comment]
> Thank you for the update, I am still not sure this is the best way to resolve this issue. I think I recall @TahaTesser looking at this before. @TahaTesser do you have any thoughts on this? Or insight on your past investigation here?

That's right, I attempted to this in https://github.com/flutter/flutter/pull/122600/files  but we had to revert it|
 
 Calling `Scaffold.maybeOf` to detect drawer and  calling `findAncestorStateOfType`  in the scroll notification is too expensive. Not a good idea to look up tree dozens of times as the user scrolls, if i remember correctly.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 11]
```diff
@@ -760,13 +760,18 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
 class _AppBarState extends State<AppBar> {
+  final Map<String?, double> _scrollPositions = <String?, double>{};
   ScrollNotificationObserverState? _scrollNotificationObserver;
   bool _scrolledUnder = false;
 
   @override
   void didChangeDependencies() {
     super.didChangeDependencies();
     _scrollNotificationObserver?.removeListener(_handleScrollNotification);
+    if (Scaffold.maybeOf(context)?.isDrawerOpen ?? false) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:771]: > Calling Scaffold.maybeOf to detect drawer and calling findAncestorStateOfType in the scroll notification is too expensive. Not a good idea to look up tree dozens of times as the user scrolls, if i remember correctly.

Thank you for remembering this @TahaTesser! 

@Mairramer I don't think we can do this then. since we tried it and had to revert it in the past.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:771]: In fact, I believe we can. Because the solution implemented in the PR https://github.com/flutter/flutter/pull/122600/files put directly in the scroll notification. The path I chose was to place it inside didChangeDependencies.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:771]: I made a change to avoid use findAncestorStateOfType too.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/app_bar.dart:771]: @Mairramer This looks a lot better now. Good job.

File: packages/flutter/test/material/app_bar_test.dart [hunk 12]
```diff
@@ -2563,6 +2563,223 @@ void main() {
       expect(getAppBarBackgroundColor(tester), defaultColor);
       expect(tester.getSize(findAppBarMaterial()).height, kToolbarHeight);
     });
+
+    testWidgets('Material3 - scrolledUnderElevation should be maintained when drawer is opened', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/app_bar_test.dart:2567]:
```suggestion
    testWidgets('scrolledUnderElevation should be maintained when drawer is opened', (WidgetTester tester) async {
```

Material 3 is default now

File: packages/flutter/test/material/app_bar_test.dart [hunk 13]
```diff
@@ -2563,6 +2563,223 @@ void main() {
...
+
+      // Scroll the list view back to the top.
+      await tester.drag(find.byKey(bodyListKey), const Offset(0, 300));
+      await tester.pumpAndSettle();
+
+      // The AppBar should be back to the default color.
+      expect(getAppBarBackgroundColor(tester), defaultColor);
+    });
+
+    testWidgets('Material3 - scrolledUnderElevation should be applied when scrolled under with multiple list views', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/app_bar_test.dart:2642]:
```suggestion
    testWidgets('scrolledUnderElevation should be applied when scrolled under with multiple list views', (WidgetTester tester) async {
```

Material 3 is default now.

File: packages/flutter/test/material/app_bar_test.dart [hunk 14]
```diff
@@ -2563,6 +2563,223 @@ void main() {
...
+
+      // Scroll back to the top.
+      await tester.drag(find.byKey(list2Key), const Offset(0, 300));
+      await tester.pumpAndSettle();
+
+      // The AppBar should be back to the default color.
+      expect(getAppBarBackgroundColor(tester), defaultColor);
+    });
+
+    testWidgets('Material3 - scrolledUnderElevation should be applied when scrolled under with multiple list views with list scrolled', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/app_bar_test.dart:2713]:
```suggestion
    testWidgets('scrolledUnderElevation should be applied when scrolled under with multiple list views with list scrolled', (WidgetTester tester) async {
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/app_bar_test.dart [hunk 15]
```diff
@@ -2563,6 +2563,223 @@ void main() {
...
+
+      await tester.pumpWidget(
+        MaterialApp(
+          home: Scaffold(
+            appBar: AppBar(
+              elevation: 0,
+              backgroundColor: MaterialStateColor.resolveWith((Set<MaterialState> states) {
+                return states.contains(MaterialState.scrolledUnder)
+                  ? scrolledColor
+                  : defaultColor;
```
Comment (TahaTesser) [inline packages/flutter/test/material/app_bar_test.dart:2654]:
```suggestion
              return states.contains(MaterialState.scrolledUnder) ? scrolledColor : defaultColor;
```

**Review by TahaTesser — APPROVED** [review]
LGTM with minor format fix

File: packages/flutter/lib/src/material/app_bar.dart (hunk 11 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart:771]: Scaffold.maybeOf uses findAncestorStateOfType

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart:779]: Oh yes, but I believe that within didChangeDependencies we will avoid continuous checking, unlike a listener which would really be very expensive.

**Review by Piinks — CHANGES_REQUESTED** [review]
This currently breaks an existing case in the google testing shard that shows it incorrectly triggers the scrolled under color. I am trying to get a reproduction, but it looks like a case where multiple scroll positions are involved, and no drawer.

File: packages/flutter/lib/src/material/app_bar.dart (hunk 11 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart:779]: Also, this does not seem to account for the end drawer? Although, it also looks like this ends up triggering scrolledUnder when it isn't. There is a google testing failure that shows an unexpected change, where where the app bar should not be the scrolled under color, but now it is.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: Oh, I forgot about him.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 16]
```diff
@@ -768,13 +768,25 @@ class AppBar extends StatefulWidget implements PreferredSizeWidget {
...
     super.didChangeDependencies();
     _scrollNotificationObserver?.removeListener(_handleScrollNotification);
+    final ScaffoldState? scaffoldState = Scaffold.maybeOf(context);
+
+    if (scaffoldState != null) {
+      final bool isDrawerOpen = scaffoldState.isDrawerOpen;
+      final bool isEndDrawerOpen = scaffoldState.hasEndDrawer && scaffoldState.isEndDrawerOpen;
+
+      if (isDrawerOpen || isEndDrawerOpen) {
+        _scrollNotificationObserver = null;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/app_bar.dart:786]: Maybe this is what is causing the Google test failures. If the notifier is null, then maybe we are not updating the scrolled under state anymore in some scenarios where we should be?

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: Unfortunately that is not the problem.

Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart]: Ah I see. Hm, unfortunately I don't think we can land this change since it appears to be breaking something that we have not been able to identify.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: After commenting on the section below, the Google testing passed normally. There is probably some behavior with multiple scrolls that this code breaks or is not expected.
```
if (_scrollPositions.isNotEmpty && notification.metrics.axis == Axis.vertical) {
    if (_scrollPositions.values.toList().any((double element) => element > 0) && _scrolledUnder) {
       return;
     }
}
```

Comment (Piinks) [reply packages/flutter/lib/src/material/app_bar.dart]: The Google testing shard is a random sampling of tests, so it is possible it did not pick up the test in question.
It looks like the framework tests are failing now though.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: I commented out the code in question, I'll revert it. If it's better, I'll leave the issue of multiple scrolls for another PR.

Comment (Mairramer) [reply packages/flutter/lib/src/material/app_bar.dart]: I removed the check for multiple scrolls in this PR. I'll create another one so it doesn't block the main fix.

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for continuing to work on this to find a solution!
