### PR TITLE
Fix/issue 68182: Fix rounding issue in getMaxChildIndexForScrollOffset

### LINKED ISSUE #68182: PageView adds 2 widget elements instead of 1 in the 5th slide, only in Android.
Using a Pageview with some widgets to run as a Carousel, when it reaches the 5th element it also includes the 6th element, and this only happens in Android devices.

Here is the example app:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = PageController(initialPage: 0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: PageView(
          controller: controller,
          onPageChanged: (page) => {print(page.toString())},
          pageSnapping: true,
          scrollDirection: Axis.horizontal,
          children: <Widget>[
            Container(
                color: Colors.pink,
                child: Center(
                    child: Text('This is Widget 1',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.green,
                child: Center(
                    child: Text('This is Widget - 2',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.lightBlue,
                child: Center(
                    child: Text('This is Widget - 3',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.pink,
                child: Center(
                    child: Text('This is Widget 4',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.green,
                child: Center(
                    child: Text('This is Widget - 5',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.lightBlue,
                child: Center(
                    child: Text('This is Widget - 6',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
            Container(
                color: Colors.pink,
                child: Center(
                    child: Text('This is Widget 7',
                        style: TextStyle(fontSize: 25, color: Colors.white)))),
          ],
        ),
      ),
    );
  }
}

```
Screenshot 2020-10-15 at 09 37 31

Screenshot 2020-10-15 at 09 49 44

Digging inside the code I could find, I think, the route cause of this issue:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L87
`getMaxChildIndexForScrollOffset` method:
When running in Android the values are in the 5th slide:
```
scrollOffset = 2468.571428571429
itemExtent = 411.42857142857144
```

So, if we do these calculations:
```
scrollOffset / itemExtent = 6.000000000000001
Then:
(scrollOffset / itemExtent).ceil() = 7
When this should be 6. That's the reason it includes the following widget.
```

If we check these values in iOS:
```
scrollOffset = 2484.0
itemExtent = 414.0

scrollOffset / itemExtent = 6.0
(scrollOffset / itemExtent).ceil() = 6
```

### PR DESCRIPTION
**Pull request by daviddgl**
## Description

We're trying to fix a rounding issue describe in here #68182

## Related Issues

Fixes #68182

## Tests

I added the following tests:

Added parameterized tests to check that previous and current behaviour are still working in `sliver_fixed_extent_layout_test.dart` file

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by tsimbalar** [comment]
@googlebot I fixed it. 

(was missing for my e-mail address)

**Comment by daviddgl** [comment]
@googlebot I consent.

**Comment by daviddgl** [comment]
@googlebot I consent.

**Comment by daviddgl** [comment]
@googlebot I fixed it.

**Comment by tsimbalar** [comment]
@googlebot I consent.

**Comment by daviddgl** [comment]
Hi @Piinks 
this PR is ready to review, not sure how to remove the `work in progress` label :(
Thanks

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart [hunk 1]
```diff
@@ -41,6 +41,42 @@ void main() {
     expect(children[1].attached, false);
     expect(children[2].attached, true);
   });
+
+  group('getMaxChildIndexForScrollOffset', () {
+    const double itemExtent = 600.0;
+    testValidationRounding(1234, 0, 0, 'When item extent is 0');
```
Comment (Piinks) [inline packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:47]: These tests are a bit difficult to understand, can you refactor them into separate tests that use a common method? Or one large test that breaks down each case?

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart [hunk 2]
```diff
@@ -41,6 +41,42 @@ void main() {
...
+        'Second index when offset is greater than item extent');
+    testValidationRounding(itemExtent + 0.0000001, itemExtent, 1,
+        'Second index when offset is slightly greater than item extent');
+    testValidationRounding(
+        itemExtent * 4.5, itemExtent, 4, 'Moving to the 4 index');
+
+    testValidationRounding(
+        2468.571428571429, 411.42857142857144, 5, 'Edge case for Android');
+    testValidationRounding(
+        2484.0, 414.0, 5, 'Same Android edge case but for iOS');
```
Comment (Piinks) [inline packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:61]: I do not understand how these tests are testing different Android and iOS behavior. How is the platform factored into this?

**Review by Piinks — COMMENTED** [review]
Hi @daviddgl welcome! Thank you for the contribution. 🎉 

It looks like this change may be using dart format. The flutter repository has its own style guide. Can you format to match the guide in the wiki? https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart (hunk 2 above)
Comment (daviddgl) [reply packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:61]: Actually, it's not because of the platform, it's because of the screen size, the itemExtent property. I'll change the description

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart (hunk 1 above)
Comment (daviddgl) [reply packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart]: I create a test per case. Thanks

**Comment by daviddgl** [comment]
> Hi @daviddgl welcome! Thank you for the contribution. 🎉
> 
> It looks like this change may be using dart format. The flutter repository has its own style guide. Can you format to match the guide in the wiki? https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

I think I applied the style as the guideline says.
Thanks :)

**Comment by daviddgl** [comment]
Hi @Piinks 
Could you re-review this PR, please?

Thanks!

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart [hunk 3]
```diff
@@ -41,6 +41,75 @@ void main() {
...
+        genericItemExtent + extraValueToHaveRoundingIssues, genericItemExtent);
+      expect(actual, 0);
+    });
+  });
+}
+
+int testGetMaxChildIndexForScrollOffset(
+    double scrollOffset, double itemExtent) {
+  final TestRenderSliverFixedExtentBoxAdaptor sut =
+      TestRenderSliverFixedExtentBoxAdaptor();
```
Comment (Piinks) [inline packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:110]: What does 'sut' stand for? We usually avoid abbreviations.
```suggestion
int testGetMaxChildIndexForScrollOffset(double scrollOffset, double itemExtent) {
  final TestRenderSliverFixedExtentBoxAdaptor sut = TestRenderSliverFixedExtentBoxAdaptor();
```

**Review by Piinks — COMMENTED** [review]
This is looking good @daviddgl. Thanks for the update. Just a few nits, and it looks like the analyzer is failing due to some trailing white space.

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart (hunk 3 above)
Comment (daviddgl) [reply packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:110]: `sut` means System Under Test
https://en.wikipedia.org/wiki/System_under_test

I'll rename it if you don't use this convention.

**Comment by daviddgl** [comment]
@googlebot I fixed it.

**Comment by daviddgl** [comment]
@googlebot I fixed it.

**Review by Piinks — APPROVED** [review]
This LGTM, although the analyzer is currently failing. Can you check and resolve that trailing white space?

File: packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart [hunk 4]
```diff
@@ -103,3 +171,17 @@ class TestRenderSliverBoxChildManager extends RenderSliverBoxChildManager {
   @override
   void setDidUnderflow(bool value) { }
 }
+
+class TestRenderSliverFixedExtentBoxAdaptor extends RenderSliverFixedExtentBoxAdaptor {
+  TestRenderSliverFixedExtentBoxAdaptor()
```
Comment (tsimbalar) [inline packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:176]: I think the analyzer is complaining about 

```suggestion
  TestRenderSliverFixedExtentBoxAdaptor()
```

Comment (tsimbalar) [reply packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart:176]: cf https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865114836733794336/+/steps/prepare_environment/0/steps/Analyze/0/steps/analyze/0/stdout

Comment (daviddgl) [reply packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart]: Thanks, it's fixed.
