### PR TITLE
[Gallery] Fix text contrast ratio on homepage and contacts demo

### LINKED ISSUE #14474: Gallery: Color contrast too low
An a11y review found the following contract issues:
- [ ] Contrast of text in drawer should possibly be increased from 2.99 to 4.50 for smaller text or 3.00 for larger text
- [ ] Contrast of Hamburger menu icon in main Flutter Gallery home page should be increased from 1.11 to 3.00 or higher
- [ ] Upper left hand arrow back button contrast  in Contacts Profile should be increased from 1.94 to 3.0 or higher (issue also found in other sections of app as well)

### PR DESCRIPTION
**Pull request by johnsonmh**
## Description

* Updated the options menu on the homepage of the flutter gallery to have larger, bold headings, rather than light blue headings so that the text contrast ratio is more readable. 
* Made gradient darker on the image in the contacts demo to improve the contrast ratio with the app bar buttons.
* Wrapped "Platform Mechanics" header in an `ExcludeSemantics` widget to remove redundant repetition on screen readers.

|| Before      | After |
|--| ----------- | ----------- |
Homepage| 1gC1UcC11Ns | ATPp6d3rnHN|
Contacts Demo|ue2PTdc2tX7|E5WDFi8HymJ|

## Related Issues

* closes https://github.com/flutter/flutter/issues/14474.

## Tests

I added the following tests:

* Contrast ratio test for the options menu on the home page of the gallery.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by JoseAlba — APPROVED** [review]
```
██╗      ██████╗ ████████╗███╗   ███╗
██║     ██╔════╝ ╚══██╔══╝████╗ ████║
██║     ██║  ███╗   ██║   ██╔████╔██║
██║     ██║   ██║   ██║   ██║╚██╔╝██║
███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝
```

**Review by rami-a — APPROVED** [review]

File: examples/flutter_gallery/lib/gallery/options.dart [hunk 1]
```diff
@@ -194,9 +194,10 @@ class _Heading extends StatelessWidget {
     final ThemeData theme = Theme.of(context);
     return _OptionsItem(
       child: DefaultTextStyle(
-        style: theme.textTheme.body1.copyWith(
+        style: theme.textTheme.title.copyWith(
           fontFamily: 'GoogleSans',
-          color: theme.accentColor,
+          color: theme.colorScheme.onPrimary,
```
Comment (HansMuller) [inline examples/flutter_gallery/lib/gallery/options.dart]: NICE

**Review by HansMuller — APPROVED** [review]
LGTM.

It looks like the a11y changes would not be affected by dark mode, however it wouldn't hurt to make the new test also check dark mode.
