### PR TITLE
Encode source file patches as UTF-8 in the code formatter script

### LINKED ISSUE #183464: engine's format script fails to apply fix to format
### Steps to reproduce

1. Try it on this commit: https://github.com/flutter/flutter/commit/ee1e22b3f6c6cf6e06655969ee43be394fe603d0
2. CD to engine directory: e.g.`/Users/huanlin/Desktop/flutter/flutter/engine/src/flutter`
3. Run `./ci/format.sh --fix`
4. Observe the error: 
```
Fixing any Dart format problems
Fixing Dart formatting...
All dart files formatted correctly.                                                                         
Fixing any GN format problems
Fixing GN formatting...
Fixed 1 GN file which was formatted incorrectly.                                                          
Fixing any Java format problems
Fixing Java formatting...
Checking Java formatting...
No Java files with changes, skipping Java format check.
Fixing any Python format problems
Fixing Python formatting...
All python files formatted correctly.                                                                         
Fixing any Trailing whitespace format problems
Checking for trailing whitespace on 33 source files...
No trailing whitespace found.                                                                              
Fixing any Header guards format problems
Fixing any C++/ObjC/Shader format problems
Fixing C++/ObjC/Shader formatting...
Checking C++/ObjC/Shader formatting...
Fixing 1 C++/ObjC/Shader file which was formatted incorrectly.                                               
ERROR: 1 patch failed to apply.completed,  0 in progress,   0 pending,   1 failed.                    
error: patch failed: engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h:256
error: engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h: patch does not apply
```

### Workaround: 

1. run `./ci/format.sh` instead (without `--fix`)
2. This patch will get print out. Copy it and then replace `git apply <<DONE` with `git apply <<'DONE'` (add quote). It should work after adding quote. 
```
git apply <<DONE
diff --git a/engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h b/engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h
index 5916d9f5910..00000000000 100644
--- a/engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h
+++ b/engine/src/flutter/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h
@@ -256,13 +256,14 @@ typedef enum {
    * Flutter blocks all the UIGestureRecognizers on the platform view as soon as it
    * decides they should be blocked.
    *
-   * This policy employs a dual blocking strategy: synchronous blocking via hitTest results and asynchronous blocking managed through the framework’s gesture arena.
-   * With this policy, only the `touchesBegan` method for all the UIGestureRecognizers is guaranteed
-   * to be called.
+   * This policy employs a dual blocking strategy: synchronous blocking via hitTest results and
+   * asynchronous blocking managed through the framework’s gesture arena. With this policy, only the
+   * `touchesBegan` method for all the UIGestureRecognizers is guaranteed to be called.
    */
   FlutterPlatformViewGestureRecognizersBlockingPolicyEager,
   /**
-   * Flutter blocks all the UIGestureRecognizers on the platform view only after touchesEnded was invoked.
+   * Flutter blocks all the UIGestureRecognizers on the platform view only after touchesEnded was
+   * invoked.
    *
    * This results in the platform view's UIGestureRecognizers seeing the entire touch sequence,
    * but never recognizing the gesture (and never invoking actions).
@@ -271,8 +272,10 @@ typedef enum {
   /**
    * Flutter blocks all the UIGestureRecognizers on the platform view based on results from hitTest.
    *
-   * Unlike FlutterPlatformViewGestureRecognizersBlockingPolicyEager, this policy does not rely on Flutter's gesture arena. This is a workaround to address a few bugs related to platform view's gesture recognizers being stuck in a stale state.
-   * See: https://github.com/flutter/flutter/issues/175099.
+   * Unlike FlutterPlatformViewGestureRecognizersBlockingPolicyEager, this policy does not rely on
+   * Flutter's gesture arena. This is a workaround to address a few bugs related to platform view's
+   * gesture recognizers being stuck in a stale state. See:
+   * https://github.com/flutter/flutter/issues/175099.
    */
   FlutterPlatformViewGestureRecognizersBlockingPolicyDoNotBlockGesture,
   // NOLINTEND(readability-identifier-naming)
DONE
```

### Expected results

Should not fail to format

### Actual results

Fail to format

### Code sample

NA

### Screenshots or Video

NA

### Logs

NA

### Flutter Doctor output

NA

### PR DESCRIPTION
**Pull request by jason-simmons**
Flutter engine source files can contain non-ASCII characters and are encoded in UTF-8.  Patches generated by diffing against formatted sources should be given to "git apply" as UTF-8.

Fixes https://github.com/flutter/flutter/issues/183464

### CODE REVIEW

**Comment by jason-simmons** [comment]
Added a test.

**Review by jtmcdole — DISMISSED** [review]

**Comment by jtmcdole** [comment]
```
   info - ci/bin/format.dart:235:17 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_constructors
   info - ci/test/format_test.dart:329:11 - Omit the type annotation on a local variable when the type is obvious. Try removing the type annotation. - omit_obvious_local_variable_types

```

**Comment by jason-simmons** [comment]
Fixed the analyzer warnings - PTAL

File: engine/src/flutter/ci/test/format_test.dart [hunk 1]
```diff
@@ -324,4 +324,27 @@ void main() {
...
+    final ccNonAsciiContentPair = FileContentPair(
+      'int main\u221E(){return 0;}\n',
+      'int main\u221E() {\n  return 0;\n}\n',
+    );
+    final fixture = TestFileFixture(target.FormatCheck.clang);
+    final ccFile = io.File('${repoDir.path}/non_ascii_test.cc');
+    ccFile.writeAsStringSync(ccNonAsciiContentPair.original);
+    fixture.files.add(ccFile);
+    try {
+      fixture.gitAdd();
```
Comment (gaaclarke) [inline engine/src/flutter/ci/test/format_test.dart:338]: nit: should gitAdd be outside the try block?  seems like if gitAdd failed you wouldn't wan to call gitRemove

**Review by gaaclarke — APPROVED** [review]
lgtm, thanks jason

File: engine/src/flutter/ci/test/format_test.dart (hunk 1 above)
Comment (jason-simmons) [reply engine/src/flutter/ci/test/format_test.dart:338]: This was done for consistency with the other tests in this file.  `gitRemove` is safe to call at any time.  It does a `git rm -f` of the files in `fixture.files`, and that will do nothing if the file was not added to the index by `git add`.
