### PR TITLE
Deprecate onReorder callback

### LINKED ISSUE #127901: The index paramater for ReorderableListView's onReorderCallback is confusing.
The value of the onReorderCallback's newIndex and oldIndex parameters are non-intuitive due to some now-historical flawed API engineering.  They're explained here: https://api.flutter.dev/flutter/widgets/ReorderCallback.html, but not  in https://api.flutter.dev/flutter/material/ReorderableListView-class.html or in https://api.flutter.dev/flutter/material/ReorderableListView/onReorder.html. 

We decided not to fix the problem because there wasn't a way to automatically update old apps: https://github.com/flutter/flutter/pull/93146#issuecomment-1032082749 which many developers were unhappy about. 

The documentation for the [ReorderableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) and for [ReorderableListView.onReorder](https://api.flutter.dev/flutter/material/ReorderableListView/onReorder.htm) should explain this quirk.

### LINKED ISSUE #169878: SliverReorderableList newIndex arg off by one on drag down list
### Steps to reproduce

1 - Create new project using flutter create command
2 - Replace code w/ sample code and run
3 - Drag list tiles using the drag icon up and down
4 - Observe index values 

### Expected results

Dragging from position x to y should return value y as new index
Dragging from position y to x should return value x as new index

### Actual results

Dragging from position x to y returns y+1 as new index (INCORRECT RESULT)
Dragging from position y to x returns x as new index (EXPECTED RESULT)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Reorderable List Index Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int newestIndex = 0;
  int expectedIndex = 0;
  final ScrollController c = ScrollController();

  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    final padding = MediaQuery.of(context).viewPadding;
    final height = (size.height - padding.top - kToolbarHeight) / 2;
    final items = Iterable.generate(10, (index) => 'Draggable Tile');

    final list = SliverReorderableList(
      proxyDecorator: _proxyDecorator,
      itemBuilder: (context, index) {
        final item = items.elementAt(index);

        return Container(
          key: Key('$item-$index'),

          decoration: BoxDecoration(border: Border.all(color: Colors.blue)),
          padding: EdgeInsets.only(bottom: 20),
          margin: EdgeInsets.only(bottom: 5),
          child: ListTile(
            title: Text(item),
            leading: ReorderableDragStartListener(
              enabled: true,
              index: index,
              child: Icon(Icons.reorder),
            ),
          ),
        );
      },

      itemCount: items.length,
      onReorder: (oldIndex, newIndex) {
        setState(() {
          //BUG HERE
          //Dragging down an object shows newest index as 1 greater than expected
          newestIndex = newIndex;
          expectedIndex = oldIndex > newIndex ? newIndex: newIndex - 1 ;
        });
      },
    );

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Newest index:'),
            Text(
              '$newestIndex',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const Text('Expected index:'),
            Text(
              '$expectedIndex',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            SizedBox(
              height: height,
              child: RawScrollbar(
                controller: c,
                child: CustomScrollView(
                  controller: c,
                  scrollDirection: Axis.vertical,
                  shrinkWrap: true,
                  slivers: [list],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

Widget _proxyDecorator(Widget child, int index, Animation<double> animation) {
  return AnimatedBuilder(
    animation: animation,
    builder: (BuildContext context, Widget? child) {
      final double animValue = Curves.easeInOut.transform(animation.value);
      final double elevation = lerpDouble(0, 6, animValue)!;
      return Material(elevation: elevation, child: child);
    },
    child: child,
  );
}

```

</details>

### Screenshots or Video
https://github.com/user-attachments/assets/4caaf8be-60c8-4b2b-a9e8-64cb617de27e

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.0, on Debian GNU/Linux 12 (bookworm)
    6.1.0-34-amd64, locale en_US.UTF-8) [220ms]
    • Flutter version 3.32.0 on channel stable at /home/k/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (2 weeks ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    [1,701ms]
    • Android SDK at /home/k/Android/Sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at:
      /home/k/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [133ms]
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop [558ms]
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    • GL_EXT_framebuffer_blit: no
    • GL_EXT_texture_format_BGRA8888: no

[✓] Android Studio (version 2024.3.2) [131ms]
    • Android Studio at
      /home/k/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 85.3.1
    • Dart plugin version 243.26753.1
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3) [10ms]
    • IntelliJ at
      /home/k/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version unknown) [10ms]
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available) [106ms]
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 16
      (API 36) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Debian
      GNU/Linux 12 (bookworm) 6.1.0-34-amd64
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 136.0.7103.92

[✓] Network resources [616ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by navaronbracke**
This pull request deprecates the old `onReorder` callback of `ReorderableList` / `SliverReorderableList` / `ReorderableListView`, in favor of a new callback, `onReorderItem`, that does the index correction as mentioned in the docs at https://api.flutter.dev/flutter/widgets/ReorderCallback.html

I added tests to ensure that the old callback is preferred when both are provided and tests that assert that the new callback does the index correction correctly. I also noticed that some tests used empty callbacks for `onReorder`, those have been updated to use wildcards in a consistent manner.

I did not opt into making a design doc, since the change itself is very small, that will also be apparent in the migration guide that I am going to write.

Fixes https://github.com/flutter/flutter/issues/127901
Fixes https://github.com/flutter/flutter/issues/169878

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

Migration guide: https://github.com/flutter/website/pull/13012

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -151,7 +143,13 @@ class ReorderableList extends StatefulWidget {
...
     required this.itemBuilder,
     required this.itemCount,
-    required this.onReorder,
+    @Deprecated(
+      'Use the onReorderItem callback instead. '
+      'The onReorderItem callback adjusts the newIndex parameter for a removed item at the oldIndex. '
+      'This feature was deprecated after v3.38.0-0.2.pre.',
+    )
+    this.onReorder,
+    required this.onReorderItem,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/reorderable_list.dart]: Marking it as required forbids existing apps from running. Maybe don't mark it as required, and instead allow either and asserts one (and only one) of them is provided. Also leave a comment to add the required back when the deprecation is removed.

File: packages/flutter/test/material/reorderable_list_test.dart [hunk 2]
```diff
@@ -2032,6 +2023,274 @@ void main() {
     expect(endIndex, equals(0));
   });
 
+  testWidgets(
+    'ReorderableListView prefers old onReorder callback if provided along with onReorderItem callback',
```
Comment (dkwingsmt) [inline packages/flutter/test/material/reorderable_list_test.dart]: If we check that only one callback is provided, then the preference tests are not needed.

**Review by dkwingsmt — COMMENTED** [review]
Generally looking good. Thank you!

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 1 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: Yes!  I forgot to rectify this. I'll update the behavior once I resynced with upstream (this PR was from before the flutter_lints merge)

File: packages/flutter/test/material/reorderable_list_test.dart (hunk 2 above)
Comment (navaronbracke) [reply packages/flutter/test/material/reorderable_list_test.dart]: I will add a different test, that verifies the assert instead.

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 3]
```diff
@@ -887,11 +916,22 @@ class SliverReorderableListState extends State<SliverReorderableList>
...
+        widget.onReorder?.call(oldIndex, newIndex);
+      }
+    } else {
+      // Removing an item at the old index shortens the list by one.
+      if (newIndex > oldIndex) {
+        newIndex -= 1;
+      }
+
+      widget.onReorderItem.call(oldIndex, newIndex);
     }
```
[the remark this answers is not in the document]
Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: Using `?.` is safer to do.

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 4]
```diff
@@ -1050,9 +1090,18 @@ class SliverReorderableListState extends State<SliverReorderableList>
...
+          widget.onReorder?.call(oldIndex, newIndex);
+        }
+      } else {
+        // Removing an item at the old index shortens the list by one.
+        if (newIndex > oldIndex) {
+          newIndex -= 1;
+        }
+
+        widget.onReorderItem.call(oldIndex, newIndex);
       }
```
[the remark this answers is not in the document]
Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: Fixed.

**Comment by navaronbracke** [comment]
I updated the PR, so that the new parameter is nullable. I also added new tests for the assert and repurposed the old tests that I wrote, for testing if the old callback still works (if a user were to provide it).

Also cleaned up one of Gemini's suggestions, because some code was duplicated.

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 5]
```diff
@@ -207,8 +210,24 @@ class ReorderableList extends StatefulWidget {
   /// A callback used by the list to report that a list item has been dragged
   /// to a new location in the list and the application should update the order
   /// of the items.
+  ///
+  /// If `oldIndex` is before `newIndex`, removing the item at `oldIndex` from the
+  /// list will reduce the list's length by one. Implementations will need to
+  /// account for this when inserting before `newIndex`.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:217]: I find that it's not immediately obvious how existing code should be migrated, which is especially inappropriate for an essential method like this. I propose the following addition. Feel free to change as you see fit.
```suggestion
  /// account for this when inserting before `newIndex`.
  ///
  /// This callback has been deprecated in favor of [onReorderItem], which
  /// simplifies the reordering logic by automatically handling index
  /// adjustments. To migrate, remove the manual adjustment of `newIndex` when
  /// items are moved downward in the list. For example, replace:
  /// ```dart
  /// onReorder: (oldIndex, newIndex) {
  ///   if (newIndex > oldIndex) {
  ///     newIndex -= 1;
  ///   }
  ///   // Handle reordering...
  /// }
  /// ```
  ///
  /// With:
  /// ```dart
  /// onReorderItem: (oldIndex, newIndex) {
  ///   // Handle reordering...
  /// }
  /// ```
```

**Review by dkwingsmt — APPROVED** [review]
LGTM with one doc suggestion.

Sorry for the late review!

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 5 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:217]: I was going to add a migration guide on the website, after this PR was approved but not yet landed (per the deprecation policy), but I agree that we can add that here as well.

File: packages/flutter/lib/src/material/reorderable_list.dart [hunk 6]
```diff
@@ -114,6 +120,11 @@ class ReorderableListView extends StatefulWidget {
          children.every((Widget w) => w.key != null),
          'All children of this widget must have a key.',
        ),
+       assert(
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/reorderable_list.dart:123]: This assert basically requires `onReorderItem` for new instances of this class, but that's not reflected in the API contract. Do we need to steer developers to always provide `onReorderItem` through the class API docs (or assert message)? I know requiring `onReorderItem` will be a breaking change, but I'm thinking of a future where the deprecated property gets removed and a developer finds out the hard way that a property which isn't marked as required actually is.

Maybe there is prior art for this?

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 6 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/material/reorderable_list.dart:123]: Yes, this is what https://github.com/flutter/flutter/pull/178242#discussion_r2692534620 was also about.
I'm going to add a migration guide on the website (still TBD) and add a doc comment about it.

I can update the assert message to nudge towards the replacement.
The idea is that when the deprecated property is removed, the new callback becomes nonnull and required. (in the same change that removes the old callback)

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 5 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:217]: Done. It looks like this in the VSCode docs tooltip now:
Screenshot 2026-01-17 at 12 05 49

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 6 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/material/reorderable_list.dart:123]: Updated the assert message to nudge users of the API.

**Review by dkwingsmt — APPROVED** [review]
Thank you!
