### PR TITLE
[flutter_conductor] catch and warn when pushing working branch to mirror

### LINKED ISSUE #94479: [flutter_conductor] tool should support a previous working branch name already existing on mirror
If a release PR on a specific release branch is merged but the feature branch (the branch starting `'cherrypicks-'`) is NOT deleted, if that user tries to create a follow-up hotfix release on that same branch, the conductor will try to push to the same feature branch on the user's mirror, but it will fail because the previous commits got squashed to a single commit when they were merged, and thus the two versions of the feature branch have different histories.

We should support `--force` in this situation, and also catch the crash and warn the user about what happened and how to correct.

```
To github.com:godofredoc/engine.git
 ! [rejected]            HEAD -> cherrypicks-flutter-2.8-candidate.3 (non-fast-forward)
error: failed to push some refs to 'github.com:godofredoc/engine.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

#0      Git._reportFailureAndExit (package:conductor_core/src/git.dart:77:5)
#1      Git.run (package:conductor_core/src/git.dart:43:7)
<asynchronous suspension>
#2      Repository.pushRef (package:conductor_core/src/repository.dart:399:7)
<asynchronous suspension>
#3      NextContext.run (package:conductor_core/src/next.dart:155:9)
<asynchronous suspension>
#4      NextCommand.run (package:conductor_core/src/next.dart:58:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///Users/godofredoc/flutter_checkouts/flutter/dev/conductor/core/bin/cli.dart:78:5)
<asynchronous suspension>
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Catch and warn when git pushing working branch to mirror is rejected because the remote branch already exists with different commits. Also, pipe through `--force` flag to allow git pushing past this.

Fixes https://github.com/flutter/flutter/issues/94479

### CODE REVIEW

**Comment by christopherfujino** [comment]
friendly ping @godofredoc

File: dev/conductor/core/lib/src/git.dart [hunk 1]
```diff
@@ -74,15 +74,55 @@ class Git {
...
+    if (_pushRejectedPattern.hasMatch(message)) {
+      type = GitExceptionType.PushRejected;
+    } else {
+      // because type is late final, it must be explicitly set before it is
+      // accessed.
+      type = null;
+    }
+  }
+
+  static final RegExp _pushRejectedPattern = RegExp(
```
Comment (godofredoc) [inline dev/conductor/core/lib/src/git.dart:118]: Is there a way to detect this error by exit code instead of message? using something like exit code can make this code more deterministic.

**Review by godofredoc — APPROVED** [review]
LGTM with one question.

File: dev/conductor/core/lib/src/git.dart (hunk 1 above)
Comment (christopherfujino) [reply dev/conductor/core/lib/src/git.dart:118]: Unfortunately not. This particular error is exit 1, as are almost all errors, per: https://stackoverflow.com/questions/4917871/does-git-return-specific-return-error-codes
