### PR TITLE
Make module tests pass on Xcode 14

### LINKED ISSUE #110553: `build_ios_framework_module_test` fails on Xcode 14
`Reachability.xcframework/ios-arm64_armv7` does not exist.  Xcode 14 has updated `ARCHS_STANDARD` from `armv7 arm64` to `arm64`, which means that `ios-arm64_armv7` is no longer output.  The updated path should be `Reachability.xcframework/ios-arm64`
```
[build_ios_framework_module_test] [STDOUT] Executing "otool -l -arch arm64 /opt/s/w/ir/x/t/flutter_module_test.y4y16l/hello_module/flutter-frameworks/Debug/Reachability.xcframework/ios-arm64_armv7/Reachability.framework/Reachability" in "/opt/s/w/ir/x/t/flutter_module_test.y4y16l" with environment {BOT: true, LANG: en_US.UTF-8}
[build_ios_framework_module_test] [STDOUT] stderr: error: /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /opt/s/w/ir/x/t/flutter_module_test.y4y16l/hello_module/flutter-frameworks/Debug/Reachability.xcframework/ios-arm64_armv7/Reachability.framework/Reachability (No such file or directory)
[build_ios_framework_module_test] [STDOUT] Checking for reboot
```
https://github.com/flutter/flutter/blob/7122a0095cfb2f51f0cf7fceca4257ed802c59dc/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L296-L298

Additionally, frameworks built by Xcode no longer contain bitcode due to https://github.com/flutter/flutter/issues/107887.  Remove checks.
```
  "reason": "/var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/flutter_module_test.JRrrOy/hello_module/flutter-frameworks/Release/connectivity.xcframework/ios-arm64/connectivity.framework/connectivity does not contain bitcode"
```

https://github.com/flutter/flutter/issues/108566

### LINKED ISSUE #110555: `module_test_ios` fails on Xcode 14
The frameworks embedded into the host app no longer contain bitcode due to https://github.com/flutter/flutter/issues/107887. Remove checks.
```
  "reason": "Expected bitcode in /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/flutter_module_test.7ULPbr/build-objc-archive.xcarchive/Products/Applications/Host.app/Frameworks/Flutter.framework/Flutter"
```

### PR DESCRIPTION
**Pull request by jmagman**
Remove `arm64_armv7` directories and bitcode checks for built/embedded frameworks.  Leave the bitcode checks for Flutter.framework and App.framework, to be removed later as part of https://github.com/flutter/flutter/issues/107887.

Tested locally on Xcode 14 beta 5.  

Fixes https://github.com/flutter/flutter/issues/110555
Fixes https://github.com/flutter/flutter/issues/110553
Reverts the unnecessary armv7 checks from #101592 post-https://github.com/flutter/flutter/issues/97327.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/build_ios_framework_module_test.dart [hunk 1]
```diff
@@ -346,14 +333,6 @@ Future<void> _testBuildIosFramework(Directory projectDir, { bool isModule = fals
     checkFileExists(simulatorFrameworkHeaderPath);
   }
 
-  checkDirectoryExists(path.join(
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:349]: `BCSymbolMaps` is a bitcode thing, and is no longer generated in Xcode 14.

**Review by cyanglaz — APPROVED** [review]
LGTM
