### PR TITLE
fix overlay entry remove to remove itself from the overlay first if i…

### LINKED ISSUE #64941: Removing pages from Navigator.pages causes animation glitch
## Steps to Reproduce

The main goal was to remove pages from stack [HomePage, SecondLevelPage, ThirdLevelPage] to achieve [ThirdLevelPage] with usage of new Pages api from Navigator 2.0 #45938

1. Run following DartPad example https://dartpad.dartlang.org/3155332097b7c691e2b9cdaa1ac620a0
2. Press `Remove Second Level Page`
3. Observe animation glitch (compare screenshot in slow motion)
4. Press `Remove Home Page`
5. Observe animation glitch (compare screenshot in slow motion)

**Expected results:** 

I would expect the pages below current page to be removed without glitch/black screen

**Actual results:** 

Removal of pages below current page (`HomePage`, `SecondLevelPage`) causes animation glitch.

CleanShot 2020-08-31 at 10 25 16

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale pl-PL)
    • Flutter version 1.22.0-1.0.pre at /Users/dominik/fvm/versions/dev
    • Framework revision ce40de69b7 (11 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • iPhone (Dominik) (mobile) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 13.6.1
    • macOS (desktop)           • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)          • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
…t is called in build stage

## Description

The overlayentry.remove will delay the removal to the next frame when it is called during build time. The navigator update pages will first call remove on the removed route and call rearrange to update its overlay. Since the removed route will not be removed until next frame, the overlay.rearrange is called when to-be-removed overlay entry still present in the overlay. This cause those to-be-removed entries to be move to the top of the overlay for one frame because they won't be removed until the next.

The PR fixes the overlayentry.remove to remove it self from overlay first and only dirty the overlay at the post frame call back

## Related Issues

Fixes https://github.com/flutter/flutter/issues/64941

## Tests

I added the following tests:

see files

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 15 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/65126

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 1]
```diff
@@ -123,23 +123,24 @@ class OverlayEntry {
...
-  /// [SchedulerPhase.persistentCallbacks], i.e. during the build, layout, or
-  /// paint phases (see [WidgetsBinding.drawFrame]), then the removal is
-  /// delayed until the post-frame callbacks phase. Otherwise the removal is
-  /// done synchronously. This means that it is safe to call during builds, but
-  /// also that if you do call this during a build, the UI will not update until
-  /// the next frame (i.e. many milliseconds later).
+  /// This method removes this overlay entry from the overlay immediately. The
+  /// UI will be updated in the same frame if this method is called before the
+  /// overlay rebuild in this frame; otherwise, the UI will be updated in the
+  /// next frame.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/overlay.dart:129]: Keep the information that it is safe to call this during build?

**Review by goderbauer — APPROVED** [review]
LGTM
