### PR TITLE
Include debug symbol in xcframework when building iOS-framework

### LINKED ISSUE #80063: Missing dSYM and bcsymbolmap in xcframework from `flutter build ios-framework`
`flutter build ios-framework` doesn't produce dSYM and bcsymbolmap, so it is impossible to symbolicate crash logs.

### PR DESCRIPTION
**Pull request by HelloCore**
Fix #80063 #64730

Adding `dSYM` and `bcsymbolmap` to xcframework using `-debug-symbols` flag.

after_dsym

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 1]
```diff
@@ -83,6 +83,10 @@ class BuildIOSFrameworkCommand extends BuildSubCommand {
         defaultsTo: true,
         hide: !verboseHelp,
       )
+      ..addFlag('include-dsym',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:86]: Is there any reason to not include it?  I'd rather just include it instead of an undiscoverable flag and let Xcode filter it as needed on the embedding side.

**Review by jmagman — CHANGES_REQUESTED** [review]
This needs tests.  Unfortunately this file is essentially un-unit tested, but pretty easy to add to the integration test https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart (hunk 1 above)
Comment (HelloCore) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Actually, I'm not sure if Flutter team intended to exclude dSYM or not, so I added flag just in case, I'm going to remove it.

**Comment by linhzz999** [comment]
Ok

**Comment by HelloCore** [comment]
@jmagman I have added more check to the integration test.

For `BCSymbolMaps`, I'm not sure how to test, because Xcode generated UUID as a file name, for example, `BCSymbolMaps/B2F12025-2869-3357-886A-209E722F2B02.bcsymbolmap`.

So, I tested by checking if directory `BCSymbolMaps` exists instead.

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 2]
```diff
@@ -525,7 +525,15 @@ end
...
-        framework.path
+        framework.path,
+        ...framework.parent
+            .listSync()
+            .where((FileSystemEntity entity) =>
+                entity.basename.endsWith('bcsymbolmap') ||
+                entity.basename.endsWith('dSYM'))
+            .map((FileSystemEntity entity) =>
+                <String>['-debug-symbols', entity.path])
+            .expand((i) => i)
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:536]:
```suggestion
            .expand<String>((List<String> parameter) => parameter)
```
You have an analyzer warning here:
```
 info • Specify type annotations • packages/flutter_tools/lib/src/commands/build_ios_framework.dart:536:22 • always_specify_types
```

File: dev/devicelab/bin/tasks/build_ios_framework_module_test.dart [hunk 3]
```diff
@@ -333,6 +344,14 @@ Future<void> _testBuildIosFramework(Directory projectDir, { bool isModule = fals
     checkFileExists(simulatorFrameworkHeaderPath);
   }
 
+  checkDirectoryExists(path.join(
+    outputPath,
+    'Release',
+    'device_info.xcframework',
+    localXcodeArmDirectoryName,
+    'BCSymbolMaps'
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:352]: Trailing comma
```suggestion
    'BCSymbolMaps',
```

File: dev/devicelab/bin/tasks/build_ios_framework_module_test.dart [hunk 4]
```diff
@@ -310,6 +310,17 @@ Future<void> _testBuildIosFramework(Directory projectDir, { bool isModule = fals
       'DeviceInfoPlugin.h',
     ));
 
+    if(mode != 'Debug') {
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:313]: Missing space
```suggestion
    if (mode != 'Debug') {
```

**Review by jmagman — COMMENTED** [review]
I commented about a few minor nits, and the analyzer warning.

Once those are fixed, this looks good!  Thank you for working on it!

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by itlwy** [comment]
Hello,
I used these commits of this issue to modify my local flutter_tools (version of 2.0.4) ,but it has no effect.
I found that there are no dSYM and bcsymbolmap in the xcframework directory during the compilation process.

Looking forward to reply，thank you.
@HelloCore 

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.57.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by HelloCore** [comment]
@itlwy 
If you modify the file locally, you might use `dart` to call that file directly.

I'm using this command.
```bash
$ dart .fvm/flutter_sdk/packages/flutter_tools/bin/flutter_tools.dart build ios-framework --no-debug --no-profile --cocoapods
```

**Comment by itlwy** [comment]
I think it’s not for this reason.
I have deleted `/path/to/flutter_sdk/bin/cache/flutter_tools.stamp` and rebuilt.
Please see the picture below:
QQ20210617-141642

@HelloCore
