### PR TITLE
fix semantics to only send relevant node update

### LINKED ISSUE #60701: A11y focus is lost when using TextField's helperText in combination with specific semantic structure
b/160293585

It looks like the accessibility focus is getting lost when using TextField's helperText in combination with certain semantics structure. The example below is synthetic just to demonstrate the bug. There are real reason why the application needs to use MergeSemantics etc.

Recording (internal) https://drive.google.com/file/d/17yA2-y51K2vf-hCnSEz6DHWOojV_vyBg/view

```dart
    Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Column(
        children: [
          MergeSemantics(
            child: Semantics(
              value: 'test 1',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 1'),
              ),
            ),
          ),
          MergeSemantics(
            child: Semantics(
              value: 'test 2',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 2'),
              ),
            ),
          ),
          MergeSemantics(
            child: Semantics(
              value: 'test 3',
              textField: true,
              child: TextField(
                decoration: InputDecoration(helperText: 'test 3'),
              ),
            ),
          ),
        ],
      ), 
    )
```

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

The change is fairly simple, remove any merged semantics node from semantics update. However, I couldn't think of a good way to test it beside driver test. The problem is that I couldn't find a way to inspect the result in SemanticsUpdate. I would like to see if there is any other way to write the test before i proceed to write the integration test.

My current attempt can be found here https://gist.github.com/chunhtai/83bf6c000d2619ea75e5e9af165dfc7e

## Related Issues

Fixes https://github.com/flutter/flutter/issues/60701

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by goderbauer — COMMENTED** [review]
Fix looks good.

For testability, can we make the `SemanticsUpdateBuilder` injectable, so you can inject a mock in tests and assert on that mock that the right nodes got added?

File: packages/flutter/lib/src/semantics/binding.dart [hunk 1]
```diff
@@ -34,6 +34,16 @@ mixin SemanticsBinding on BindingBase {
     _accessibilityFeatures = window.accessibilityFeatures;
   }
 
+  /// Generates an empty semantics update builder.
+  ///
+  /// The caller is responsible for filling out the semantics node updates.
+  ///
+  /// This method is used by the [SemanticsOwner] to generate builder for all
+  /// its semantics updates.
+  ui.SemanticsUpdateBuilder generateSemanticsUpdateBuilder() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/binding.dart:43]: nit: replace generate with create?

(in the code and doc comment above too)

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+// found in the LICENSE file.
+
+import 'dart:typed_data';
+import 'dart:ui' as ui;
+
+import 'package:flutter/material.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
+  test('Semantics update', () async {
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:12]: Any reasons this cannot be a regular `testWidgets` test? You should be able to just instantiate the custom binding in the main before all `testWidgets` methods.

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+                  child: const Text('test 3'),
+                ),
+              ),
+            ),
+          ),
+        ),
+      );
+      SemanticsUpdateBuilderSpy.observations.clear();
+      binding.scheduleFrame();
+      await binding.pump(null, EnginePhase.sendSemanticsUpdate);
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:36]: Aren't those arguments the default for pump? If so, let's remove them.

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+    final SemanticsUpdateTestBinding binding = SemanticsUpdateTestBinding();
+    binding.pipelineOwner.ensureSemantics();
+    await binding.runTest(() async {
+      binding.attachRootWidget(
+        MaterialApp(
+          home: MergeSemantics(
+            child: Semantics(
+              value: 'test 1',
+              textField: true,
+              // This semantics b
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:22]: What does this comment mean?

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 5]
```diff
@@ -0,0 +1,188 @@
...
+        ),
+      );
+      SemanticsUpdateBuilderSpy.observations.clear();
+      binding.scheduleFrame();
+      await binding.pump(null, EnginePhase.sendSemanticsUpdate);
+
+      // Checks all nodes are connected.
+      // Starts with root node.
+      int currentNode = 0;
+      while(SemanticsUpdateBuilderSpy.observations.containsKey(currentNode)) {
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:41]: nit: space after `while`

Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:41]: Does this while loop actually run? I would have expected that `SemanticsUpdateBuilderSpy.observations` is empty because you cleared it above and then pumped a frame that didn't change any semantics?

Comment (goderbauer) [reply packages/flutter/test/semantics/semantics_update_test.dart:41]: Can you add an expect before the while loop to check that `SemanticsUpdateBuilderSpy.observations` actually contains the expected number of nodes?

Comment (goderbauer) [reply packages/flutter/test/semantics/semantics_update_test.dart:41]: Instead of doing the while loop I'd also have more confidence in the test if it would just check individually that all expected nodes are in `observations`.

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 6]
```diff
@@ -0,0 +1,188 @@
...
+        final SemanticsNodeUpdateObservation observation =  SemanticsUpdateBuilderSpy.observations.remove(currentNode)!;
+        if (observation.childrenInTraversalOrder.isEmpty)
+          break;
+        expect(observation.childrenInTraversalOrder.length, 1);
+        currentNode = observation.childrenInTraversalOrder[0];
+      }
+      // We should have looped through the all the observations.
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:48]:
```suggestion
      // We should have looped through all the observations.
```

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 7]
```diff
@@ -0,0 +1,188 @@
...
+      expect(SemanticsUpdateBuilderSpy.observations.isEmpty, isTrue);
+    }, () { });
+
+    SemanticsUpdateBuilderSpy.observations.clear();
+  });
+
+}
+
+typedef UpdateSemantics = void Function(ui.SemanticsUpdate);
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:57]: What's this typedef for?

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+    binding.pipelineOwner.ensureSemantics();
+    await binding.runTest(() async {
+      binding.attachRootWidget(
+        MaterialApp(
+          home: MergeSemantics(
+            child: Semantics(
+              value: 'test 1',
+              textField: true,
+              // This semantics b
+              child: MergeSemantics(
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:23]: Why this second MergeSemantics?

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+        expect(observation.childrenInTraversalOrder.length, 1);
+        currentNode = observation.childrenInTraversalOrder[0];
+      }
+      // We should have looped through the all the observations.
+      expect(SemanticsUpdateBuilderSpy.observations.isEmpty, isTrue);
+    }, () { });
+
+    SemanticsUpdateBuilderSpy.observations.clear();
+  });
+
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:54]: nit: remove extra blank line.

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+}
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:55]: There should also be a test where we modify the semantics of a node that gets merged into another node and ensure that only the (updated) merged node is send over.

**Comment by chunhtai** [comment]
@goderbauer Thanks for reviewing, I rewrote the entire test which should address all the comments.

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 11]
```diff
@@ -0,0 +1,227 @@
...
+    expect(SemanticsUpdateBuilderSpy.observations[1]!.childrenInTraversalOrder.length, 1);
+    expect(SemanticsUpdateBuilderSpy.observations[1]!.childrenInTraversalOrder[0], 2);
+
+    expect(SemanticsUpdateBuilderSpy.observations.containsKey(2), isTrue);
+    expect(SemanticsUpdateBuilderSpy.observations[2]!.childrenInTraversalOrder.length, 1);
+    expect(SemanticsUpdateBuilderSpy.observations[2]!.childrenInTraversalOrder[0], 3);
+
+    expect(SemanticsUpdateBuilderSpy.observations.containsKey(3), isTrue);
+    expect(SemanticsUpdateBuilderSpy.observations[3]!.childrenInTraversalOrder.length, 1);
+    expect(SemanticsUpdateBuilderSpy.observations[3]!.childrenInTraversalOrder[0], 4);
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:60]: I am surprised that it sends this many semantics nodes. I would have expected 2: the root node and the merged node. Is that because of the `MaterialApp` used in the test? Can we remove it (and replace it with the individual widget we need, e.g. a Directionality widget) to make this test more targeted? Otherwise we will have to update it whenever the semantics of MaterialApp change...

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+  });
+}
+
+class SemanticsUpdateTestBinding extends AutomatedTestWidgetsFlutterBinding {
+  @override
+  ui.SemanticsUpdateBuilder createSemanticsUpdateBuilder() {
+    return SemanticsUpdateBuilderSpy();
+  }
+}
+
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:104]: remove extra blank line

File: packages/flutter/test/semantics/semantics_update_test.dart [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+    final SemanticsHandle handle = tester.ensureSemantics();
+    await tester.pumpWidget(
+      MaterialApp(
+        home: MergeSemantics(
+          child: Semantics(
+            label: 'outer',
+            textField: true,
+            // This merge semantics node should not be part of the semantics
+            // update because it is under another merge semantics.
+            child: MergeSemantics(
```
Comment (goderbauer) [inline packages/flutter/test/semantics/semantics_update_test.dart:24]: Can you achieve the same effect by removing this MergeSemantics and setting `container: true` on the semantics node below? Seems slightly simpler then the nested merging...

**Comment by chunhtai** [comment]
addressed all comments.

**Review by goderbauer — APPROVED** [review]
LGTM
