### PR TITLE
Fixes TreeSliver collapsing not working

### LINKED ISSUE #153418: TreeSliver - collapsing not working on web
### Steps to reproduce

1. Go to https://api.flutter.dev/flutter/widgets/TreeSliver-class.html
2. Run any of the two examples on the page.
3. Expand any node and try to collapse it

Collapsing doesn't work neither on online example, nor local web build.

### Expected results

Tree node collapses

### Actual results

Tree node does not collapse

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [TreeSliver].

void main() => runApp(const TreeSliverExampleApp());

class TreeSliverExampleApp extends StatelessWidget {
  const TreeSliverExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TreeSliverExample(),
    );
  }
}

class TreeSliverExample extends StatefulWidget {
  const TreeSliverExample({super.key});

  @override
  State<TreeSliverExample> createState() => _TreeSliverExampleState();
}

class _TreeSliverExampleState extends State<TreeSliverExample> {
  TreeSliverNode<String>? _selectedNode;
  final TreeSliverController controller = TreeSliverController();
  final List<TreeSliverNode<String>> _tree = <TreeSliverNode<String>>[
    TreeSliverNode<String>('First'),
    TreeSliverNode<String>(
      'Second',
      children: <TreeSliverNode<String>>[
        TreeSliverNode<String>(
          'alpha',
          children: <TreeSliverNode<String>>[
            TreeSliverNode<String>('uno'),
            TreeSliverNode<String>('dos'),
            TreeSliverNode<String>('tres'),
          ],
        ),
        TreeSliverNode<String>('beta'),
        TreeSliverNode<String>('kappa'),
      ],
    ),
    TreeSliverNode<String>(
      'Third',
      expanded: true,
      children: <TreeSliverNode<String>>[
        TreeSliverNode<String>('gamma'),
        TreeSliverNode<String>('delta'),
        TreeSliverNode<String>('epsilon'),
      ],
    ),
    TreeSliverNode<String>('Fourth'),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('TreeSliver Demo'),
      ),
      body: CustomScrollView(
        slivers: <Widget>[
          TreeSliver<String>(
            tree: _tree,
            controller: controller,
            treeNodeBuilder: (
              BuildContext context,
              TreeSliverNode<Object?> node,
              AnimationStyle animationStyle,
            ) {
              Widget child = GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () {
                  setState(() {
                    controller.toggleNode(node);
                    _selectedNode = node as TreeSliverNode<String>;
                  });
                },
                child: TreeSliver.defaultTreeNodeBuilder(
                  context,
                  node,
                  animationStyle,
                ),
              );
              if (_selectedNode == node as TreeSliverNode<String>) {
                child = ColoredBox(
                  color: Colors.purple[100]!,
                  child: child,
                );
              }
              return child;
            },
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/bdc6a551-89cd-4851-89ab-7f2185f33060

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale pl-PL)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\artur\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\artur\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.92.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
This change addresses bug #153418 by ensuring that nodes are handled correctly when closing their children.

Fixes #153418

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Mairramer** [comment]
@Piinks

**Review by Piinks — COMMENTED** [review]
Hi @Mairramer thanks for sending another PR!
It looks like this is trying to fix two issues. Would you be willing to separate them into two PRs? That way if one introduces a regression and we need to revert it, we won;t end up reverting the other fix as well.

**Comment by Piinks** [comment]
We should also follow up on the TreeView side, the code is almost identical so we should make the same fix there.

**Comment by Mairramer** [comment]
> We should also follow up on the TreeView side, the code is almost identical so we should make the same fix there.

Ok, I'll check.

**Comment by Mairramer** [comment]
Splited PR https://github.com/flutter/flutter/pull/153890

File: packages/flutter/test/widgets/sliver_tree_test.dart [hunk 1]
```diff
@@ -650,6 +650,103 @@ void main() {
     expect(style!.duration, const Duration(milliseconds: 200));
   });
 
+  testWidgets('TreeSliverNode should close all children when collapsed when animation is completed', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_tree_test.dart:653]: This test passes without the change above. It should fail without the changes to verify they fix the bug.

**Review by Piinks — CHANGES_REQUESTED** [review]

File: packages/flutter/test/widgets/sliver_tree_test.dart (hunk 1 above)
Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_tree_test.dart:653]: I am trying to make this into test.

Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_tree_test.dart]: I tried but I couldn't reproduce the error in the tests.

**Review by Piinks — CHANGES_REQUESTED** [review]
Unfortunately, we won't be able to merge this without test coverage.

**Comment by Mairramer** [comment]
@Piinks I tested it in several ways, and the problem turned out to be purely visual. The node is indeed collapsed, and the children are inactive, but when used in an app, they still appear on the screen despite not being able to interact with them.

Would it be possible to write a golden test for this?

**Comment by Piinks** [comment]
> Can I be exempt from testing in this PR? 

No, this is not something that would be test exempt. Perhaps you can check that the render object paints the children as expected?

File: packages/flutter/test/widgets/sliver_tree_test.dart (hunk 1 above)
Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_tree_test.dart]: I managed to write the test. I don't think I'm that dumb lol.

File: packages/flutter/test/widgets/sliver_tree_test.dart [hunk 2]
```diff
@@ -883,4 +883,82 @@ void main() {
...
+
+    await tester.pumpWidget(buildTreeSliver(controller));
+
+    expect(find.text('alpha'), findsOneWidget);
+    expect(find.text('uno'), findsOneWidget);
+    expect(find.text('dos'), findsOneWidget);
+    expect(find.text('tres'), findsOneWidget);
+
+    // Using runAsync to handle collapse and animations properly.
+    await tester.runAsync(() async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/sliver_tree_test.dart:955]: Thanks for the update here as well, can you share why runAsync is needed?

Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_tree_test.dart:955]: The reason I needed to use `runAsync` is that when using `pump` or `pumpAndSettle`, the code was being executed synchronously. That's why I couldn't simulate the real behavior in the test before.
Using `runAsync`, the execution happens asynchronously, reflecting the behavior of a real application.
I don't know if this can be seen as bad practice but it was one of the ways that worked for me. The same applies for https://github.com/flutter/packages/pull/7474#discussion_r1801852257

Comment (Piinks) [reply packages/flutter/test/widgets/sliver_tree_test.dart:955]: I was mostly curious, thank you!

**Review by Piinks — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM :+1:
