### PR TITLE
[flutter_tools] handle windows holding file lock in web build directory

### LINKED ISSUE #69109: [tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32
## Command
```
flutter build web
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:389:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:486:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:388:12)
#6      buildWeb (package:flutter_tools/src/web/compile.dart:41:21)
<asynchronous suspension>
#7      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:91:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.23.0-18.0.pre at C:\flutter
    • Framework revision 37ebe3d82a (2 weeks ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Qursana\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\Qursana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • LG K430 (mobile)  • LGK430YLDAW8QG • android-arm    • Android 6.0 (API 23)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Web Server (web)  • web-server     • web-javascript • Flutter Tools
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 86.0.622.38

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 37ebe3d82a9d5faeda7d3c1a6ad193030210a2cc

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/69109

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/compile.dart [hunk 1]
```diff
@@ -36,10 +37,16 @@ Future<void> buildWeb(
   final bool hasWebPlugins = (await findPlugins(flutterProject))
     .any((Plugin p) => p.platforms.containsKey(WebPlugin.kConfigKey));
   final Directory outputDirectory = globals.fs.directory(getWebBuildDirectory());
-  if (outputDirectory.existsSync()) {
-    outputDirectory.deleteSync(recursive: true);
+  try {
+    ErrorHandlingFileSystem.deleteIfExists(outputDirectory, recursive: true);
     outputDirectory.createSync(recursive: true);
+  } on FileSystemException catch (err) {
+    globals.logger.printError(
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/compile.dart:44]: I think I'd rather crash than keep on trucking. The latter could lead to even harder to debug situations.

Since this function is async, can we print the issue and wait until the directory is unlocked? Pseudo-code:

```dart
bool deleted = false;
bool warningPrinted = false;

while (!deleted) {
  try {
    delete();
    deleted = true;
  } on FileSystemException {
    if (!warningPrinted) {
      globals.logger.printError('Directory $outputDirectory is locked by another program. Waiting for the directory to be unlocked.');
      warningPrinted = true;
      await Future.delayed(Duration(milliseconds: 50));
    }
  }
}

if (warningPrinted) {
  globals.logger.printInfo('Directory $outputDirectory was unlocked and deleted. Continuing.');
}
```

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/compile.dart:44]: This could definitely work, I was leaning towards the "quick fix" angle :)

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/compile.dart:44]: though I think the problem with this is that we will probably delete most of the files successfully, so that leaves a partially invalid state

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/compile.dart:44]: actually ... lets do a partial revert for now. this is causing crashes and I don't quite have the time I need for a long term solution

**Review by yjbanov — APPROVED** [review]
lgtm
