### PR TITLE
disable hit testing if the CompositedTransformFollower is hidden when…

### LINKED ISSUE #21320: CompositedTransformFollower responds to taps even when showWhenUnlinked is false
Internal: b/153942448 

## Steps to Reproduce

If we have a `CompositedTransformFollower` that follows a `CompositedTransformTarget`, and we scroll the target out of the screen, the layer link between them gets broken. This results in the follower showing at the top left of the screen. 

We can hide the follower by setting `showWhenUnlinked` to false, but it still responds to taps of the user.

To reproduce this, I created this small app:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage();

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  LayerLink _layerLink = LayerLink();
  FocusNode _focusNode = FocusNode();

  @override
  void initState() {
    super.initState();

    _focusNode.addListener(() {
      if (_focusNode.hasFocus) {
        Overlay.of(context).insert(OverlayEntry(
          builder: (context) =>
            Positioned(
              width: 200.0,
              child: CompositedTransformFollower(
                link: this._layerLink,
                child: Material(
                  elevation: 4.0,
                  child: RaisedButton(
                      onPressed: () {
                        print('I was pressed');
                      }
                  ),
                ),
              ),
            )
        ));
      }
    });
  }

  @override
  Widget build(BuildContext context) {
     return new Scaffold(
       body: ListView(
         padding: EdgeInsets.all(20.0),
         children: <Widget>[
           SizedBox(height: 200.0,),
           CompositedTransformTarget(
             link: this._layerLink,
             child: TextField(
               focusNode: this._focusNode,
             ),
           ),
           SizedBox(height: 700.0,)
         ],
       )
    );
  }
}
```
If you focus the `TextField`, the button shows, then if you scroll the `TextField` out of the screen, you can see the button stays at the top left of the screen. If you tap the button, it prints to the console "I was pressed".

Now, set the `showWhenUnlinked` to false and repeat the procedure. Even though the button won't be showing anymore, it will still respond to taps.

## Logs

```
[✓] Flutter (Channel beta, v0.6.0, on Linux, locale en_US.UTF-8)
    • Flutter version 0.6.0 at /home/aalhamali/flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/aalhamali/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

```

### PR DESCRIPTION
**Pull request by chunhtai**
… there is no leader layer

## Description

This PR disable hit test when there is no leader layer and showWhenUnlinked is false.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/21320

## Tests

I added the following tests:

see file change

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -4962,6 +4962,9 @@ class RenderFollowerLayer extends RenderProxyBox {
 
   @override
   bool hitTest(BoxHitTestResult result, { Offset position }) {
+    // Disables the hit testing if this render object is hidden.
+    if (link.leader == null && !showWhenUnlinked)
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/proxy_box.dart:4966]: Can you also update the documentation on showWhenUnlinked to indicate that it also affects hit testing.

**Review by goderbauer — APPROVED** [review]
LGTM
