### PR TITLE
[Web] Fix IME and selection by syncing more text styles

### LINKED ISSUE #161592: Incorrect position of Japanese predictive conversion popup in TextFormField using maxLines on the Web
### Steps to reproduce

1. Prepare a Mac with macOS Sequoia 15.2 (Japanese).
2. Paste the code sample into [dartpad.dev](https://dartpad.dev/) and run it.
3. Type Japanese in TextFormField and display the predictive conversion popup.

### Expected results

The predictive conversion popup will appear without any redundant space under the text.

### Actual results

The predictive conversion popup is appeared with redundant space under the text.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextFormField(
        maxLines: 10,
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

None.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

None. (Run on dartpad.dev with Based on Dart SDK 3.6.0 and Flutter SDK 3.27.1.)

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/161592

The current implementation does not fully reflect [letter-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/letter-spacing), [word-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/word-spacing), and [line-height](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/line-height) in the DOM. 0bc99f8c4f70973a1877c88ca35804e9bc5fabcf
And the current implementation generates an DomHTMLTextAreaElement every time the `enabled`. Therefore, it reapplies the [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) value that the Element had been holding internally. 726491298d2b1f17681cab421c7c9276dde19ee6

https://github.com/user-attachments/assets/6f575366-12a0-4246-b2ab-eb2a0e85cfa5

https://github.com/user-attachments/assets/ec660d4c-5166-450c-be38-77b90fcfce76

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MainApp());

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MainPage());
  }
}

class MainPage extends StatelessWidget {
  const MainPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Selection position')),
      body: SingleChildScrollView(
        padding: const .all(16),
        child: Column(
          children: [
            const Text('height=null'),
            TextField(maxLines: 5, style: TextStyle(height: null)),
            const Text('height=1.0'),
            TextField(maxLines: 5, style: TextStyle(height: 1.0)),
            const Text('height=2.0'),
            TextField(maxLines: 5, style: TextStyle(height: 2.0)),
          ],
        ),
      ),
    );
  }
}
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 1]
```diff
@@ -1450,6 +1455,11 @@ abstract class DefaultTextEditingStrategy
   @override
   void disable() {
     assert(isEnabled);
+    // Preserve the internal scroll position.
+    if (geometry != null && lastEditingState != null) {
+      final key = '${geometry!.hashCode}_${lastEditingState!.text.hashCode}';
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1464]: I'm somewhat concerned about this `key`, it doesn't seem like a robust solution. But I don't have any better ideas at the moment.

File: packages/flutter/lib/src/services/text_input.dart [hunk 2]
```diff
@@ -1655,16 +1655,18 @@ class TextInputConnection {
   /// This information is used by the Flutter Web Engine to change the style
   /// of the hidden native input's content. Hence, the content size will match
   /// to the size of the editable widget's content.
+  @Deprecated(
+    'Use setStyleWithMetrics instead. '
+    'This feature was deprecated after v3.40.0-0.2.pre.',
+  )
```
Comment (mdebbar) [inline packages/flutter/lib/src/services/text_input.dart:1769]: @loic-sharma any thoughts on doing this vs adding the parameters to the existing `setStyle(...)` method without deprecating it? The latter may be considered a breaking change if users are expected to extend/implement `TextInputConnection`?

Comment (loic-sharma) [reply packages/flutter/lib/src/services/text_input.dart:1769]: It looks like people do implement `TextInputConnection` ([1](https://github.com/Flutter-Bounty-Hunters/super_editor/blob/77e8d306a5bb689706f87b9dd269249323af470c/super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart#L22), [2](https://github.com/Flutter-Bounty-Hunters/super_editor/blob/77e8d306a5bb689706f87b9dd269249323af470c/super_editor/lib/src/default_editor/document_ime/ime_decoration.dart#L8)).

The current approach does avoid a breaking change, but it prevents users from overriding `setStyleWithMetrics`. I don't think we should do this approach since people do override `setStyle` ([example](https://github.com/Flutter-Bounty-Hunters/super_editor/blob/77e8d306a5bb689706f87b9dd269249323af470c/super_editor/lib/src/default_editor/document_ime/ime_decoration.dart#L37-L49)).

What do y'all think of this idea:

1. Introduce a new `TextInputStyle` class, similar to the existing [`TextInputConfiguration`](https://api.flutter.dev/flutter/services/TextInputConfiguration-class.html):

   Something like:
  
   ```dart
   final class TextInputStyle {
     const TextInputStyle(
        ...
     );
   
     final String? fontFamily;
     final double? fontSize;
     final FontWeight? fontWeight;
     final TextDirection textDirection;
     final TextAlign textAlign;
     final double? letterSpacing;
     final double? wordSpacing;
     final double? lineHeight;
   }
   ```

   _Notice `TextInputStyle` is [`final`](https://dart.dev/language/class-modifiers#final)._

2. Add a new `TextInputConnection.updateStyle(TextInputStyle style)` method that  calls `TextInput._instance._setStyle`.
3. Deprecate `TextInputConnection.setStyle`.
4. Do all the stuff in https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes

This is still a breaking change - if your package implements `TextInputConnection`, you'll need to add a new `updateStyle` method.

However, this is a one-time breaking change. In the future, we'll be able to add more members to `TextInputStyle` without it being a breaking change.

What do y'all think?

Comment (loic-sharma) [reply packages/flutter/lib/src/services/text_input.dart:1769]: cc @Renzo-Olivares too, would love your thoughts as well

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3409,12 +3409,15 @@ class EditableTextState extends State<EditableText>
...
-        _textInputConnection!.setStyle(
+        _textInputConnection!.setStyleWithMetrics(
           fontFamily: _style.fontFamily,
           fontSize: _style.fontSize,
           fontWeight: _style.fontWeight,
           textDirection: _textDirection,
           textAlign: widget.textAlign,
+          letterSpacing: _style.letterSpacing,
+          wordSpacing: _style.wordSpacing,
+          lineHeight: renderEditable.preferredLineHeight,
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart]: I suspect this value can be stale. I believe `RenderEditable.preferredLineHeight` isn't updated until `_Editable` rebuilds, which happens after `EditableTextState.didUpdateWidget` is called.

Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Just like these take the `MediaQuery.boldTextOf` account, these likely need to take the following into account:

1. `MediaQuery.maybeLineHeightScaleFactorOverrideOf(context);`
2. `MediaQuery.maybeLetterSpacingOverrideOf(context);`
3. `MediaQuery.maybeWordSpacingOverrideOf(context);`

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart (hunk 1 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1464]: Yes, this key approach has edge cases.

I wanted to keep this PR scope small first. So I made this solution closed within the flutter engine side.

Syncing scrollTop from flutter framework when scroll occurs would solve this problem better. But that would add another breaking change discussion.

If the team prefers the more robust approach, I can work on a follow-up PR 👍

File: packages/flutter/lib/src/services/text_input.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/services/text_input.dart:1769]: Chatted offline but I agree with the `TextInputStyle` approach!

**Comment by koji-1009** [comment]
Thanks for the heads up! I'll make the PR ready once I've fixed it and it passes tests excluding customer testing.

File: packages/flutter/lib/src/services/text_input.dart [hunk 4]
```diff
@@ -2557,12 +2663,28 @@ class _PlatformTextInputControl with TextInputControl {
...
-      'textAlignIndex': textAlign.index,
-      'textDirectionIndex': textDirection.index,
+      'fontFamily': style.fontFamily,
+      'fontSize': style.fontSize,
+      'fontWeightIndex': style.fontWeight?.index,
+      'textAlignIndex': style.textAlign.index,
+      'textDirectionIndex': style.textDirection.index,
+      'letterSpacing': style.letterSpacing,
+      'wordSpacing': style.wordSpacing,
+      'lineHeight': style.lineHeight,
```
Comment (loic-sharma) [inline packages/flutter/lib/src/services/text_input.dart]: Could you move this logic to `TextStyle.toJson`, similar to `TextInputConfiguration.toJson`?

File: packages/flutter/test/services/text_input_test.dart [hunk 5]
```diff
@@ -1612,6 +1608,11 @@ class FakeTextInputControl with TextInputControl {
     methodCalls.add('setStyle');
   }
 
+  @override
+  void updateStyle(TextInputStyle style) {
+    methodCalls.add('updateStyle');
+  }
```
Comment (loic-sharma) [inline packages/flutter/test/services/text_input_test.dart:1699]: Could we unit test the `equals`, `hashCode`, and `toJson` methods, similar to `TextInputConfiguration`'s unit tests? See:

https://github.com/flutter/flutter/blob/dfd92b7732198de288d9fb7453e8ef52b8979ec2/packages/flutter/test/services/text_input_test.dart#L319-L541

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -3409,13 +3409,29 @@ class EditableTextState extends State<EditableText>
...
+              textDirection: _textDirection,
+              textAlign: widget.textAlign,
+              letterSpacing: letterSpacingOverride ?? _style.letterSpacing,
+              wordSpacing: wordSpacingOverride ?? _style.wordSpacing,
+              // preferredLineHeight already includes lineHeightScaleFactor from
+              // _OverridingTextStyleTextSpanUtils.applyTextSpacingOverrides.
+              lineHeight: renderEditable.preferredLineHeight,
+            ),
+          );
+        }, debugLabel: 'EditableText.updateStyle');
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart:3427]: I believe we also need to update `didChangeDependencies` so that when `MediaQuery.maybeLetterSpacingOverrideOf(context)` / `MediaQuery.maybeWordSpacingOverrideOf(context)` /  `MediaQuery.maybeLineHeightScaleFactorOverrideOf(context)` change, we update the connection's style as well.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -3409,13 +3409,29 @@ class EditableTextState extends State<EditableText>
...
+              fontWeight: _style.fontWeight,
+              textDirection: _textDirection,
+              textAlign: widget.textAlign,
+              letterSpacing: letterSpacingOverride ?? _style.letterSpacing,
+              wordSpacing: wordSpacingOverride ?? _style.wordSpacing,
+              // preferredLineHeight already includes lineHeightScaleFactor from
+              // _OverridingTextStyleTextSpanUtils.applyTextSpacingOverrides.
+              lineHeight: renderEditable.preferredLineHeight,
+            ),
+          );
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Can we avoid using a post-frame callback here? A post-frame callback means we'll render a frame with a potentially incorrect text input style, and then fix it up in the next frame. That could lead to weird jumps and other unexpected behaviors.

A couple options:

* **Option 1 - Punt**: Land this PR without syncing line height text metrics. Adding a `TextInputStyle` and fixing letter/word spacing is a great improvement already. We should also fix line height metrics, but I suspect this requires non-trivial refactoring of `EditableText` to do properly.
* **Option 2 - Refactor EditableText**. Currently, the value for `RenderEditable.text` is updated in `EditableTextState.build` through `_Editable.inlineSpan`, so `renderEditable.lineHeight` is stale until after `EditableTextState.build` completes.
   
   To fix this, we update `EditableTextState.didUpdateWidget` and `EditableTextState.didChangeDependencies` such that it updates all the underlying `RenderEditable` properties needed to get the latest `RenderEditable.preferredLineHeight`. This would likely require updating `RenderEditable.text`, `RenderEditable.textScaler`, etc...

   I'm not sure if this is a good idea. I'll discuss this matter with @justinmc, @LongCatIsLooong, and @Renzo-Olivares at our next text input sync this Thursday.

Comment (loic-sharma) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Actually, please ignore this comment! @Renzo-Olivares pointed out that we already use post-frame callbacks to update the style [here](https://github.com/flutter/flutter/blob/d93e2d4b82ba2cc1b730948a81f823d52374d5dc/packages/flutter/lib/src/widgets/editable_text.dart#L3382-L3390), and @LongCatIsLooong pointed out that since style updates go through a platform channel, the style update isn't applied immediately in the frame anyways. I'll close this off!

**Comment by koji-1009** [comment]
[Linux linux_host_engine_test](https://github.com/flutter/flutter/pull/180436/checks?check_run_id=61714585024) is failed.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8691441949929312513/+/u/test:_Host_Tests_for_host_release/stdout?format=raw

```
[ERROR:flutter/shell/testing/tester_main.cc(612)] Unhandled exception
Exception: Bad state: Can't call test() once tests have begun running.
When running a test as an executable directly (not as a suite by the test runner), tests must be declared in a synchronous block.
If async work is required before any tests are run use a `setUpAll` callback.
If async work cannot be avoided before declaring tests, all async events must be complete before declaring the first test.
Stack trace: #0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:418:5)
#1      Declarer.test (package:test_api/src/backend/declarer.dart:210:5)
#2      test (package:test_core/src/scaffolding.dart:157:13)
#3      main (file:///b/s/w/ir/cache/builder/engine/src/flutter/testing/dart/fragment_shader_test.dart:650:5)
<asynchronous suspension>
```

https://github.com/flutter/flutter/blob/e435edfbcd26c0107eccce443756b589febb7987/engine/src/flutter/testing/dart/fragment_shader_test.dart#L643-L667

This failure seems to be caused by the order in which the test code is written. Placing `final ImageComparer comparer = await ImageComparer.create();` just after the `main()` or inside the `test()` should resolve it.

File: packages/flutter/lib/src/services/text_input.dart (hunk 4 above)
Comment (koji-1009) [reply packages/flutter/lib/src/services/text_input.dart]: I fixed by [82c5465](https://github.com/flutter/flutter/pull/180436/commits/82c546553a593a13de191817323c4944df0f65ed).

File: packages/flutter/test/services/text_input_test.dart (hunk 5 above)
Comment (koji-1009) [reply packages/flutter/test/services/text_input_test.dart:1699]: I fixed by [82c5465](https://github.com/flutter/flutter/pull/180436/commits/82c546553a593a13de191817323c4944df0f65ed).

**Comment by loic-sharma** [comment]
> [Linux linux_host_engine_test](https://github.com/flutter/flutter/pull/180436/checks?check_run_id=61714585024) is failed.

That doesn't seem related to your changes. This _might_ be a flake or that _might_ be an issue with the commit you branched off of. Usually when I get an unrelated error like this, I rebase off the latest `master` commit :)

File: packages/flutter/test/widgets/editable_text_styles_test.dart [hunk 8]
```diff
@@ -0,0 +1,274 @@
...
+    focusNode.dispose();
+  });
+
+  testWidgets('EditableText updates style when boldText changes', (WidgetTester tester) async {
+    await tester.pumpWidget(
+      MediaQuery(
+        data: const MediaQueryData(),
+        child: Directionality(
+          textDirection: TextDirection.ltr,
+          child: EditableText(
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_styles_test.dart:93]: @loic-sharma @justinmc would this be a good place to use `TestTextField`? Is there a certain type of test where we would recommend the more verbose `EditableText` approach vs using `TestTextField` and vice versa. My thought is that tests that rely on gestures should probably use `TestTextField` but outside of that the main difference is verbosity.

File: packages/flutter/test/widgets/editable_text_styles_test.dart [hunk 9]
```diff
@@ -0,0 +1,274 @@
...
+      ),
+    );
+
+    await tester.tap(find.byType(EditableText));
+    await tester.pump();
+
+    expect(control.lastStyle?.letterSpacing, 1.0);
+    control.lastStyle = null;
+
+    // Update letterSpacingOverride
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_styles_test.dart]: super nit: period after comments here and elsewhere.

File: packages/flutter/test/widgets/editable_text_styles_test.dart (hunk 8 above)
Comment (loic-sharma) [reply packages/flutter/test/widgets/editable_text_styles_test.dart:93]: @Renzo-Olivares Excellent question. My intuition would be to:

* Prefer `EditableText` for tests specific to `EditableText` (e.g. `EditableText.rendererIgnoresPointer`)
* Prefer `TestTextField` if the test needs a fully functioning text field (e.g. gesture support)
* Prefer `TestTextFIeld` if using `EditableText` would result in large amounts of boilerplate
* Otherwise if none of the guidelines apply, prefer `EditableText`.

----

A drawback of using `TestTextField` for _all_ tests is that it would reduce our visibility on the usability of the `EditableText`'s API. Ideally, `EditableText` would be easy to use (per your recommendations in https://flutter.dev/go/decoupling-design-from-text). If we introduce additional bloat to `EditableText`'s API, using `TestTextField` _everywhere_ might "hide" the usability impact. If we use `EditableText` in _some_ of our tests, we'll have better sense of the usability impact of `EditableText` API changes.

(However, a benefit of using `TestTextField` for _all_ tests is that it would make it easier for us to migrate to `EditableTextField2` if/when we introduce that)

----

What do you think of this reasoning? Is there anything you disagree with, or other cases you'd add?

Assuming y'all agree with this reasoning, I'd _slightly_ lean towards using `EditableText` for these tests: the behavior isn't specific to `EditableText`, however, the boilerplate if you use `EditableText` is very reasonable.

Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/editable_text_styles_test.dart:93]: I agree with the reasoning above! Definitely see the concern of reducing visibility over `EditableText`.

I'd also lean towards `EditableText` for these tests since there is logic that is being added to `EditableText` specifically and it does not rely on gestures.

File: packages/flutter/test/services/text_input_test.dart (hunk 5 above)
Comment (loic-sharma) [reply packages/flutter/test/services/text_input_test.dart:1699]: Thanks!

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 10]
```diff
@@ -5783,6 +5789,9 @@ void main() {
           'fontWeightIndex': 6,
           'textAlignIndex': 4,
           'textDirectionIndex': 1,
+          'letterSpacing': null,
+          'wordSpacing': null,
```
Comment (loic-sharma) [inline packages/flutter/test/widgets/editable_text_test.dart]: For this test, could we add letter spacing and word spacing to `textStyle2` so these values are non-null?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 11]
```diff
@@ -3438,6 +3447,24 @@ class EditableTextState extends State<EditableText>
     }
   }
 
+  TextInputStyle _getTextInputStyle() {
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Instead of using the `State.context` property, I'd consider making this method accept a `BuildContext` argument. That would make it clearer from the call site that this method requires the widget is mounted.

I don't feel strongly about this though, feel free to skip.

**Review by loic-sharma — APPROVED** [review]
This looks good to me, but before landing this please also get an approval from @mdebbar for the Flutter Web side.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 10 above)
Comment (koji-1009) [reply packages/flutter/test/widgets/editable_text_test.dart]: I've fixed it in [4624815](https://github.com/flutter/flutter/pull/180436/commits/46248156d766ada2b71a6ec0c3f33db30840d905). Thank you.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Agreed! I've confirmed other classes follow this pattern too, so I've updated the code accordingly. Thanks for the suggestion! [552d627](https://github.com/flutter/flutter/pull/180436/commits/552d627d9b81674f3ce1a40226bf021d3c818368)

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 10 above)
Comment (loic-sharma) [reply packages/flutter/test/widgets/editable_text_test.dart]: Sweet, thanks!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (loic-sharma) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Sounds good, thanks!

File: packages/flutter/lib/src/services/text_input.dart [hunk 12]
```diff
@@ -1518,6 +1518,114 @@ mixin DeltaTextInputClient implements TextInputClient {
...
+      'textAlignIndex': textAlign.index,
+      'textDirectionIndex': textDirection.index,
+      'letterSpacing': letterSpacing,
+      'wordSpacing': wordSpacing,
+      'lineHeight': lineHeight,
+    };
+  }
+
+  @override
+  String toString() {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/services/text_input.dart]: Consider mixing in `Diagnosticable` and using `debugFillProperties` here. https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#override-tostring

**Review by Renzo-Olivares — COMMENTED** [review]
framework LGTM w/ one small comment

File: packages/flutter/lib/src/services/text_input.dart (hunk 12 above)
Comment (koji-1009) [reply packages/flutter/lib/src/services/text_input.dart]: I've added `Diagnosticable` mixin to `TextInputStyle` and replaced `toString` with `debugFillProperties`. [632d088](https://github.com/flutter/flutter/pull/180436/commits/632d08861678f25750aa16df4e827bd3890f04d2)

Note: I kept this change scoped to the new `TextInputStyle` class only, as modifying existing classes like `TextInputConfiguration` would expand the scope of this PR.

**Review by mdebbar — APPROVED** [review]
LGTM!
