### PR TITLE
fix: outline appearing over child

### LINKED ISSUE #167431: Badge with IconButton.outlined behind outline
### Steps to reproduce

1. Run the example
2. You can see that the Badge with IconButton.outlined is behind the outline, with all other IconButton variants everything is fine

### Expected results

Badge with IconButton.outlined in front of outline

### Actual results

Badge with IconButton.outlined behind outline

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Badge Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Badge Example'),
        actions: [
          IconButton.outlined(
            iconSize: 40,
            isSelected: false,
            onPressed: () {},
            icon: Badge(
              backgroundColor: Theme.of(context).colorScheme.primary,
              label: Text('3', style: TextStyle(fontSize: 18)),
              child: Icon(Icons.lightbulb_rounded),
            ),
          ),
        ],
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            IconButton.outlined(
              iconSize: 40,
              isSelected: false,
              onPressed: () {},
              icon: Badge(
                backgroundColor: Theme.of(context).colorScheme.primary,
                label: Text('3', style: TextStyle(fontSize: 18)),
                child: Icon(Icons.lightbulb_rounded),
              ),
            ),
            IconButton.outlined(
              iconSize: 40,
              isSelected: true,
              onPressed: () {},
              icon: Badge(
                backgroundColor: Theme.of(context).colorScheme.primary,
                label: Text('3', style: TextStyle(fontSize: 18)),
                child: Icon(Icons.lightbulb_rounded),
              ),
            ),
            IconButton.outlined(
              iconSize: 40,
              isSelected: false,
              onPressed: () {},
              icon: Badge(
                backgroundColor: Theme.of(context).colorScheme.primary,
                label: Text('Ad', style: TextStyle(fontSize: 18)),
                child: Icon(Icons.lightbulb_rounded),
              ),
            ),
            IconButton.filled(
              iconSize: 40,
              isSelected: false,
              onPressed: () {},
              icon: Badge(
                backgroundColor: Theme.of(context).colorScheme.primary,
                label: Text('Ad', style: TextStyle(fontSize: 18)),
                child: Icon(Icons.lightbulb_rounded),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4 24E248 darwin-arm64, locale
    ru-RU) [1 510ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/denis/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (7 days ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [6,0s]
    • Android SDK at /Users/denis/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [2,4s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [16ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [16ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.99.3) [14ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (5 available) [7,2s]
    • Pixel 6 (mobile)                 • 26101FDF60002Q            • android-arm64  • Android
      15 (API 35)
    • iPad (Денис) (wireless) (mobile) • 00008030-001600623E22202E • ios            • iOS
      18.4 22E240
    • macOS (desktop)                  • macos                     • darwin-arm64   • macOS
      15.4 24E248 darwin-arm64
    • Mac Designed for iPad (desktop)  • mac-designed-for-ipad     • darwin         • macOS
      15.4 24E248 darwin-arm64
    • Chrome (web)                     • chrome                    • web-javascript • Google
      Chrome 135.0.7049.96
    ! Error: Browsing on the local area network for iPhone (Денис). Ensure the device is
      unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1 032ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by iamdipanshusingh**
This PR exposes `borderOnForeground` from the `Material` class to `ButtonStyle` and `OutlinedButton` class, letting the developer decide whether to show the border on foreground or background.

Screenshot before this PR:
before

Screenshot after this PR:
after

fixes #167431 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by iamdipanshusingh** [comment]
here's the code sample to make the border appear behind the child

```dart
Column(
  mainAxisSize: MainAxisSize.min,
  children: [
    IconButton.outlined(
      iconSize: 40,
      isSelected: false,
      onPressed: () {},
      borderOnForeground: false,
      icon: Badge(
        backgroundColor: Theme.of(context).colorScheme.primary,
        label: Text('Ad', style: TextStyle(fontSize: 18)),
        child: Icon(Icons.lightbulb_rounded),
      ),
    ),
    const SizedBox(height: 20),
    SizedBox(
      height: 30,
      child: OutlinedButton(
        onPressed: () {},
        style: ButtonStyle(
          borderOnForeground: false,
        ),
        child: Badge(
          backgroundColor: Theme.of(context).colorScheme.primary,
          label: Text('Ad', style: TextStyle(fontSize: 18)),
          child: Icon(Icons.lightbulb_rounded),
        ),
      ),
    ),
  ],
),
```

**Comment by dkwingsmt** [comment]
Instead of making it an option, shall we treat this as a bug and make border-on-background the only behavior? The filled button's filling is always behind the child, and therefore it makes sense for the border of outlined buttons to always be as well.

**Comment by iamdipanshusingh** [comment]
makes sense, I'll make the chsnges

**Comment by iamdipanshusingh** [comment]
@dkwingsmt I've made the changes, `borderOnForeground` now defaults to false in `ButtonStyleButton`.

**Comment by iamdipanshusingh** [comment]
also @dkwingsmt what am I doing wrong here? why are so much tests are failing?

**Comment by dkwingsmt** [comment]
```
09:04 +935 ~359: test/material/outlined_button_test.dart: OutlinedButton, OutlinedButton.icon defaults
```

This test seems to also need a fix.
`packages/flutter/test/material/outlined_button_test.dart` L44


Also can you add another test to verify the appearance of a outlined button with a badge as a regression test? Either a `paint` verifier or a golden test would be ok.

**Comment by iamdipanshusingh** [comment]
@dkwingsmt I've added the golden tests as requested, attaching the screenshots below.
I also noticed that other buttons' default tests were failing, and I've fixed that as well.

material icon_button badge outline
material outlined_button badge outline

---

Let me know if any further changes are required

File: packages/flutter/test/material/icon_button_test.dart [hunk 1]
```diff
@@ -3375,6 +3381,34 @@ void main() {
     expect(FocusManager.instance.highlightMode, equals(FocusHighlightMode.traditional));
     expect(inkFeatures, paints..rect(color: focusColor));
   }, skip: !isBrowser); // [intended] tests web-specific behavior.
+
+  testWidgets('IconButton golden test', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/icon_button_test.dart:3385]:
```suggestion
  testWidgets('IconButton with a badge', (WidgetTester tester) async {
```

**Comment by dkwingsmt** [comment]
Also the analyzer is failing due to format errors, which can be fixed by running `dart fix .` under `packages/flutter`.

**Review by dkwingsmt — APPROVED** [review]
LGTM otherwise! Great change, thank you!

**Comment by iamdipanshusingh** [comment]
> Also the analyzer is failing due to format errors, which can be fixed by running `dart fix .` under `packages/flutter`.

it says nothing to fix(in `packages/flutter`) 

Screenshot 2025-04-28 at 12 35 40 PM

---

but proposed 313 fixes in the root folder, which I think is out of scope of this PR 😅 

Screenshot 2025-04-28 at 12 39 33 PM

---

@dkwingsmt  can we merge this PR without it?

File: packages/flutter/test/material/icon_button_test.dart (hunk 1 above)
Comment (iamdipanshusingh) [reply packages/flutter/test/material/icon_button_test.dart:3385]: @dkwingsmt is it a typo here? `Outlined button's outline` shouldn't this be `IconButton's outline`?

Comment (iamdipanshusingh) [reply packages/flutter/test/material/icon_button_test.dart]: @dkwingsmt BTW renamed the test, and added the link to the issue

**Comment by dkwingsmt** [comment]
We have to make the formatter happy though... not sure why it doesn't work, but can you manually fix the format as indicated?
```

                                                                                                    
Found 1 Dart file which was formatted incorrectly.
To fix, run `dart format packages/flutter/test/material/icon_button_test.dart` or:

git apply <<DONE
diff --git a/packages/flutter/test/material/icon_button_test.dart b/packages/flutter/test/material/icon_button_test.dart
index 4f9abbe975..0000000000 100644
--- a/packages/flutter/test/material/icon_button_test.dart
+++ b/packages/flutter/test/material/icon_button_test.dart
@@ -7,7 +7,6 @@
 @Tags(<String>['reduced-test-set'])
 library;
 
-
 import 'dart:ui';
 
 import 'package:flutter/foundation.dart';
@@ -3405,10 +3404,7 @@ void main() {
     );
 
     await tester.pumpAndSettle();
-    await expectLater(
-      find.byType(IconButton),
-      matchesGoldenFile('icon_button.badge.outline.png'),
-    );
+    await expectLater(find.byType(IconButton), matchesGoldenFile('icon_button.badge.outline.png'));
   });
 }
 
@@ -3480,3 +3476,4 @@ TextStyle? _iconStyle(WidgetTester tester, IconData icon) {
   );
   return iconRichText.text.style;
 }
DONE
```

**Comment by iamdipanshusingh** [comment]
@dkwingsmt can you check now? I've formatted the file.
But the tree status is failing. I also updated the branch (merge commit), but it's still not fixed. Let me know how I can fix that.

File: packages/flutter/test/material/outlined_button_test.dart [hunk 2]
```diff
@@ -2954,4 +2961,33 @@ void main() {
...
+                  child: Icon(Icons.lightbulb_rounded),
+                ),
+              ),
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.pumpAndSettle();
```
Comment (justinmc) [inline packages/flutter/test/material/outlined_button_test.dart:2987]: Same question about this pumpAndSettle.

**Review by justinmc — APPROVED** [review]
LGTM with a nit about possible overuse of pumpAndSettle :+1: 

Thank you for jumping in and fixing this!

File: packages/flutter/test/material/icon_button_test.dart [hunk 3]
```diff
@@ -3375,6 +3380,32 @@ void main() {
...
+                  child: Icon(Icons.lightbulb_rounded),
+                ),
+              ),
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.pumpAndSettle();
```
[the remark this answers is not in the document]
Comment (iamdipanshusingh) [reply packages/flutter/test/material/icon_button_test.dart:3406]: yeah, seems like it 😅 removing it

**Comment by iamdipanshusingh** [comment]
@justinmc removed unnecessary `pumpAndSettle`
Let me know if anything else is required 😄

**Comment by dkwingsmt** [comment]
I've checked Google testing failures and all of them are caused by swapping the order between the content and the outline of buttons. They're expected and in my opinion negligible and acceptable.
