### PR TITLE
Restore the WidgetTester's original surface size after testing setSurfaceSize

### LINKED ISSUE #87194: widget_tester_live_device_test.dart: Should print message on pointer events Failing consistently
Starting on the Engine roll here https://github.com/flutter/flutter/pull/87159

However that Engine roll only contained Skia commits that couldn't have affected Flutter due to containing only changes related to Skia infrastructure.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_misc/1685/overview

```
The following TestFailure object was thrown running a test:
  Expected: <400.0>
  Actual: <1000.0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter_test/test/widget_tester_live_device_test.dart:44:5)
```

/cc @HansMuller @goderbauer

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/87194

### CODE REVIEW

File: packages/flutter_test/test/widget_tester_live_device_test.dart [hunk 1]
```diff
@@ -107,6 +108,8 @@ Some possible finders for the widgets at Offset(1000.0, 900.0):
     expect(printedMessages, equals('''
 No widgets found at Offset(1.0, 1.0).
 '''.trim().split('\n')));
+
+    await tester.binding.setSurfaceSize(originalSize);
```
Comment (zanderso) [inline packages/flutter_test/test/widget_tester_live_device_test.dart:112]: Should this go in a `finally` block?

Comment (jason-simmons) [reply packages/flutter_test/test/widget_tester_live_device_test.dart]: done

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
Landing on red to help green the tree.

File: packages/flutter_test/test/widget_tester_live_device_test.dart [hunk 2]
```diff
@@ -82,31 +82,36 @@ No widgets found at Offset(1.0, 1.0).
       ),
     );
 
+    final Size originalSize = tester.binding.createViewConfiguration().size;
```
Comment (flar) [inline packages/flutter_test/test/widget_tester_live_device_test.dart:85]: Why not have this call take a surface size and return a new binding to use for the rest of this test? That way there is no state stored based on size.

Comment (jason-simmons) [reply packages/flutter_test/test/widget_tester_live_device_test.dart:85]: The binding with the new surface size needs to be attached to the WidgetTester so that methods like `tester.pump()` will see the updated binding's state.

You could create a new binding instance and set `tester.binding` to that object.  But you would still need to revert the WidgetTester to the old binding before any other test uses it.
