### PR TITLE
Do not try to load main/default asset image if only higher-res variants exist

### LINKED ISSUE #127090: Unable to load image asset on low-res devices if only high-resolution variants exist
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

## Description:
After upgrading to Flutter 3.10.1, I've noticed that low resolution devices are unable to correctly utilize high resolution image assets. Within my image resources directory, I have a 3.0x folder that contains the icon_apps.png image.

In Flutter 3.7.12, when I utilized image_resolution on a 2x device, candidateVariants would correctly return assets/images/3.0x/icon_apps.png. However, in Flutter 3.10.1, I observed that a 2x device would return two candidateVariants: assets/images/icon_apps.png and assets/images/3.0x/icon_apps.png.

Below is the related source code from Flutter 3.10.1 SDK for image selection:

```dart
AssetManifest.loadFromAssetBundle(chosenBundle)
      .then((AssetManifest manifest) {
        final Iterable<AssetMetadata>? candidateVariants = manifest.getAssetVariants(keyName);
        final AssetMetadata chosenVariant = _chooseVariant(
          keyName,
          configuration,
          candidateVariants,
        );
      });
```

### Steps to reproduce

- Create a project in Flutter 3.10.1, and within the assets/images/ directory, create a 3.0x/ directory, and place the icon_apps.png image in this directory.
- Declare the image assets in the pubspec.yaml file.
```yaml
flutter:
  assets:
    - assets/images/icon_apps.png
```
- On a 2x device, load the icon_apps.png image :`Image.asset("asset/images/icon_apps.png"),`.

### Expected results

On low resolution devices, even if the device resolution is lower than the image asset resolution, it should still be able to correctly utilize high resolution image assets.

### Actual results

On low resolution devices, it's not possible to utilize high resolution image assets because image_resolution returns incorrect candidateVariants and chooses the wrong variant.

### Code sample

asset dir files:
```
assets
    - images
        - 3.0x
            - icon_apps.png 
```
pubsepc.yaml
```yaml
flutter:
  assets:
    - assets/images/icon_apps.png
```

```dart
Image.asset("asset/images/icon_apps.png"),
```

</details>

### Screenshots or Video

_No response_

### Logs

Exception: Asset not found
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:369:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:811:18)
<asynchronous suspension>

### Flutter Doctor output

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
(base)

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes https://github.com/flutter/flutter/issues/127090.

https://github.com/flutter/flutter/pull/122505 did a few things to speed up the first asset load that a flutter app performs. One of those things was to not include the main asset in its own list of variants in the asset manifest. The idea was that we know that the main asset always exists, so including it in its list of variants is a waste of storage space and loading time (even if the cost was tiny).

However, the assumption that the main asset always exists is wrong. From [Declaring resolution-aware image assets](https://docs.flutter.dev/ui/assets-and-images#resolution-aware), which predates https://github.com/flutter/flutter/pull/122505:

> Each entry in the asset section of the pubspec.yaml should correspond to a real file, with the exception of the main asset entry. If the main asset entry doesn’t correspond to a real file, then the asset with the lowest resolution is used as the fallback for devices with device pixel ratios below that resolution. The entry should still be included in the pubspec.yaml manifest, however.

For example, it's valid to declare `assets/image.png` as an asset even if only `assets/3x/image.png` exists on disk.

This fix restores older behavior of including a main asset as a variant of itself in the manifest if it exists.

This fix also includes a non-user-visible behavior change:
* `"dpr"` is no longer a required field in the asset manifest's underlying structure. For the main asset entry, we do not include `"dpr"`. It makes less sense for the tool to decide what the default target dpr for an image should be. This should be left to the framework.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by andrewkolos** [comment]
Google testing is failing because g3 generates its own asset manifest, so that code is still out-of-date.

File: packages/flutter/lib/src/services/asset_manifest.dart [hunk 1]
```diff
@@ -73,22 +73,21 @@ class _AssetManifestBin implements AssetManifest {
...
-        .map((Map<Object?, Object?> data) => AssetMetadata(
+        .map((Map<Object?, Object?> data) {
+          final String asset = data['asset']! as String;
+          final Object? dpr = data['dpr'];
+          return AssetMetadata(
             key: data['asset']! as String,
-            targetDevicePixelRatio: data['dpr']! as double,
-            main: false,
-        ))
+            targetDevicePixelRatio: dpr == null ? null : dpr as double,
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/services/asset_manifest.dart:81]:
```suggestion
            targetDevicePixelRatio: dpr as double?,
```

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit
