### PR TITLE
Fix CheckedPopupMenuItem semantics to use menuItemCheckbox role with checked state

### LINKED ISSUE #171463: [Google3 Bug][A11Y]:
### Help us understand the severity of this issue

- [ ] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [x] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

Use `CheckedPopupMenuButton` within a `PopupMenu`

### Expected results

When using a screenreader, I expect a `CheckedPopupMenuButton` with `checked=true` to read as "selected" or "checked" 

### Actual results

`CheckedPopupMenuButton` items with `checked=true` are indistinguishable from those that aren't checked/selected.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(body: Center(child: PopupMenuExample())),
    );
  }
}

class PopupMenuExample extends StatefulWidget {
  const PopupMenuExample({super.key});

  @override
  State<StatefulWidget> createState() => PopupMenuExampleState();
}

class PopupMenuExampleState extends State<PopupMenuExample> {
  String selectedString = "OMG";
  final possibleSelections = ["OMG", "LOL", "ROFL", "WOW"];
  @override
  Widget build(BuildContext context) {
    return Container(
      child: PopupMenuButton<String>(
        key: ValueKey<String>('layerDropdown'),
        initialValue: selectedString,
        onSelected: (selection) {
          setState(() => selectedString = selection);
        },
        itemBuilder: (context) => [
          for (final stringVal in possibleSelections)
            CheckedPopupMenuItem(
              value: stringVal,
              checked: stringVal == selectedString,
              child: Text(stringVal),
            ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/user-attachments/assets/a403a8da-2e77-4fbb-ad9e-7f4d88a1ad3b

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Description
This PR fixes an accessibility issue where CheckedPopupMenuItem was not properly announcing its checked state to screen readers. 

Before
https://github.com/user-attachments/assets/b1785522-eea4-4fc3-9a9a-1872615838c0

After
Demo app: https://checked-0707.web.app/
https://github.com/user-attachments/assets/a8083c0b-11c8-4e93-bd71-842dfe5fa344

Issues Fixed
This PR fixes https://github.com/flutter/flutter/issues/171463. 

Breaking Changes
None.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -607,6 +607,29 @@ class _CheckedPopupMenuItemState<T> extends PopupMenuItemState<T, CheckedPopupMe
...
+  Widget build(BuildContext context) {
+    final Widget parentWidget = super.build(context);
+
+    assert(parentWidget is MergeSemantics, 'Expected MergeSemantics from parent build method');
+    final MergeSemantics mergeSemantics = parentWidget as MergeSemantics;
+
+    assert(mergeSemantics.child is Semantics, 'Expected Semantics as child of MergeSemantics');
+    final Semantics parentSemantics = mergeSemantics.child! as Semantics;
+
+    final Widget innerContent = parentSemantics.child!;
```
Comment (mdebbar) [inline packages/flutter/lib/src/material/popup_menu.dart]: This feels a bit hacky. What do you think about doing it like this: https://github.com/flutter/flutter/commit/389f17c17b54ba8810a06cff598e12690765203d

Comment (flutter-zl) [reply packages/flutter/lib/src/material/popup_menu.dart]: Great suggestion. I created a new PR: https://github.com/flutter/flutter/pull/171994.

File: packages/flutter/test/material/popup_menu_test.dart [hunk 2]
```diff
@@ -1604,6 +1604,56 @@ void main() {
...
+        )
+        .toList();
+    expect(menuItemNodes, hasLength(2));
+
+    // Verify that the checked item has the isChecked flag
+    final SemanticsNode checkedNode = menuItemNodes.firstWhere(
+      (SemanticsNode node) => node.getSemanticsData().hasFlag(SemanticsFlag.isChecked),
+    );
+    expect(checkedNode.getSemanticsData().hasFlag(SemanticsFlag.hasCheckedState), isTrue);
+    expect(checkedNode.getSemanticsData().hasFlag(SemanticsFlag.isChecked), isTrue);
```
Comment (mdebbar) [inline packages/flutter/test/material/popup_menu_test.dart]: We are already filtering the nodes by `SemanticsFlag.isChecked`, so there's no reason to check again for it.

File: packages/flutter/test/material/popup_menu_test.dart [hunk 3]
```diff
@@ -1604,6 +1604,56 @@ void main() {
...
+          (SemanticsNode node) => node.getSemanticsData().role == SemanticsRole.menuItemCheckbox,
+        )
+        .toList();
+    expect(menuItemNodes, hasLength(2));
+
+    // Verify that the checked item has the isChecked flag
+    final SemanticsNode checkedNode = menuItemNodes.firstWhere(
+      (SemanticsNode node) => node.getSemanticsData().hasFlag(SemanticsFlag.isChecked),
+    );
+    expect(checkedNode.getSemanticsData().hasFlag(SemanticsFlag.hasCheckedState), isTrue);
```
Comment (mdebbar) [inline packages/flutter/test/material/popup_menu_test.dart]: Check for role and button too?

**Review by mdebbar — APPROVED** [review]
LGTM with some suggestions for tests.
