### PR TITLE
Fix DevFS to understand missing files in _stat()

### LINKED ISSUE #22451: devfs doesn't handle missing files properly.
There is a bug in [`flutter_tools/lib/src/devfs.dart`](https://github.com/flutter/flutter/blob/54c10f44b209f6f056ae6c5fa63ee239a9f1e2d2/packages/flutter_tools/lib/src/devfs.dart#L89) when handling files that don't exist: it just crashes.

The root of the bug is that the stat() function just doesn't check for the file not being found.

This is usually not a problem unless a file is removed while the process is running (e.g. while hot reloading), but causes problems on more ephemeral filesystems.

### PR DESCRIPTION
**Pull request by gspencergoog**
Fixes #22451

### CODE REVIEW

File: packages/flutter_tools/lib/src/devfs.dart [hunk 1]
```diff
@@ -83,20 +83,34 @@ class DevFSFileContent extends DevFSContent {
...
+      } else {
+        _fileStat = fileStat;
+        return;
+      }
     }
-    _fileStat = file.statSync();
-    if (_fileStat.type == FileSystemEntityType.link) {
+    final FileStat fileStat = file.statSync();
+    _fileStat = fileStat.type == FileSystemEntityType.notFound
+      ? _fileStat = null
```
Comment (aam) [inline packages/flutter_tools/lib/src/devfs.dart]: did you mean `? null : fileStat;`

Comment (gspencergoog) [reply packages/flutter_tools/lib/src/devfs.dart]: LOL.  Yes.

**Review by aam — APPROVED** [review]
