### PR TITLE
Document additional cases 

### LINKED ISSUE #136885: Under multiple engines, destroying the page will not trigger dispose
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter (Channel stable, 3.13.1）

Under multiple engines, destroying the page will not trigger dispose

It can be reproduced in the official 'multiple_flutters' demo.

### Proposal

I found that when using multiple engines, if the FlutterViewController is destroyed, it will directly destroy the engine and channel, and the dispose in the Flutter page will not be triggered. Is there any way to change this problem? Because if dispose is not triggered, we will have a lot of inconvenience.

### LINKED ISSUE #137924: The dispose method is not called after closing FlutterViewController
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run OCProject project
2. Click blank page to push flutter vc
3. Click Back button

This repo: https://github.com/LinXunFeng/flutter_hybrid_bug

### Expected results

The `dispose` method should be called.

### Actual results

The `dispose` method is not called.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/19367531/685fb5ca-1496-4ff5-9c55-d6176b7a6c33

</details>

### Logs

<details><summary>Logs</summary>

```console
2023-11-06 10:35:47.755561+0800 OCProject[82086:21786375] flutter: flutter initState
2023-11-06 10:35:52.030731+0800 OCProject[82086:21770626] dealloc -- LXFFlutterViewController
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.13.4 on channel stable at /Users/lxf/fvm/versions/3.13.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (7 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lxf/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/lxf/Library/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /Applications/
    ✗ Android Studio not found at /Applications/Contents
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • lxf的iPhone (mobile) • 00008120-XXXXXXXXXX            • ios            • iOS 16.4.1 20E252
    • iPhone 14 (mobile)  • 20A73B49-7689-4FAA-BE22-XXXXXXXXXX • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64 (Rosetta)
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/137924
Fixes https://github.com/flutter/flutter/issues/136885

The framework defaults to keeping the widget tree alive and ready to render regardless of application lifecycle events such as showing or hiding a view controller.

Add-to-app developers may be surprised by this, and tend to file bugs asking why `dispose` isn't called when the view is dismissed (or why memory usage is higher than expected after dismissing Flutter UI).

Adds documentation to explain the limitation and what to do instead.

/cc @zanderso @chinmaygarde @jonahwilliams @jason-simmons since we were discussing this in triage.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -1184,6 +1184,21 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
...
+/// An application may have both Flutter and non-Flutter UI in it. If the
+/// application calls non-Flutter methods to remove Flutter based UI such as
+/// platform native API to manipulate the platform native navigation stack,
+/// the framework does not know if the developer intends to eagerly free
+/// resources or not. The widget tree remains mounted and ready to render
+/// as soon as it is displayed again.
+///
+/// To release resources more eagerly, establish a [platform channel](https://flutter.dev/platform-channels/)
+/// and use it call [runApp] with a widget such as [SizedBox.shrink] when
+/// the framework should dispose of the active widget tree.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/binding.dart:1199]: Something is missing in this sentence, maybe a "to" between "it" and "call"?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -1303,13 +1303,17 @@ abstract class State<T extends StatefulWidget> with Diagnosticable {
...
-  /// ## Application shutdown
+  /// ## Caveats
   ///
-  /// This method is _not_ invoked when the application shuts down, because
-  /// there is no way to predict when that will happen. For example, a user's
-  /// battery could catch fire, or the user could drop the device into a
-  /// swimming pool, or the operating system could unilaterally terminate the
-  /// application process due to memory pressure.
+  /// This method is _not_ invoked at times where a developer might otherwise
+  /// expect it.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart:1309]: This seems like an overly broad statement. Can we specify what these cases are where one might expect this to be called, but it isn't?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/framework.dart:1309]: Maybe this just needs to verbally link to the next two sections to indicate that they talk about two common cases of this?

File: packages/flutter/lib/src/widgets/binding.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/binding.dart:1199]: Yes, done

File: packages/flutter/lib/src/widgets/framework.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/framework.dart]: Added another clause here, wdyt?

**Review by goderbauer — APPROVED** [review]
LGTM
