### PR TITLE
Don't show legacy welcome message when analytics are disabled

### LINKED ISSUE #139737: First run message should be printed to stderr
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

We (at pub.dev) have scripts that parse `flutter --version --machine`
Recently the welcome message started printing at the end of the output making the parsing fail causing: https://github.com/dart-lang/pub-dev/issues/7264

### Proposal

In general it would be easier to handle the output of the flutter tool in a reliable manner if this message was output to stderr instead of stdout.

### PR DESCRIPTION
**Pull request by sigurdm**
The legacy welcome message would be printed even if `CI=true` confusing parsers of the output.

This fixes: https://github.com/flutter/flutter/issues/139737

### CODE REVIEW

**Comment by sigurdm** [comment]
Not sure how to best test this.

**Comment by christopherfujino** [comment]
Sorry for missing this, I was toying with my github notifications last week and basically didn't get any.

**Comment by christopherfujino** [comment]
Adding Elias as a reviewer, as this is tricky and he has the most context

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -614,19 +614,18 @@ class _DefaultProcessUtils implements ProcessUtils {
...
-  // before invoking the print welcome method because the print welcome method
-  // will set `messenger.shouldDisplayLicenseTerms()` to false
-  final FirstRunMessenger messenger =
-      FirstRunMessenger(persistentToolState: globals.persistentToolState!);
-  final bool legacyAnalyticsMessageShown =
-      messenger.shouldDisplayLicenseTerms();
-
-  // Prints the welcome message if needed for legacy analytics.
-  globals.flutterUsage.printWelcome();
-
```
Comment (eliasyishak) [inline packages/flutter_tools/lib/src/base/process.dart:627]: Apologies on the delayed review, slipped through the cracks

But couldn't we just check if we are on a bot before invoking the print statement for the welcome message? The `globals.analytics.shouldShowMessage` is not a good indicator for first run, it can return `true` if we had to change something within `package:unified_analytics` that would require us to show the consent message again

```dart
Future<int> exitWithHooks(int code, {required ShutdownHooks shutdownHooks}) async {
  // Need to get the boolean returned from `messenger.shouldDisplayLicenseTerms()`
  // before invoking the print welcome method because the print welcome method
  // will set `messenger.shouldDisplayLicenseTerms()` to false
  final FirstRunMessenger messenger =
      FirstRunMessenger(persistentToolState: globals.persistentToolState!);
  final bool legacyAnalyticsMessageShown =
      messenger.shouldDisplayLicenseTerms();

  // Prints the welcome message if needed for legacy analytics.
  // globals.flutterUsage.printWelcome();
  if (!(await globals.isRunningOnBot)) { // <--- Added
    globals.flutterUsage.printWelcome();
  }
```

Comment (sigurdm) [reply packages/flutter_tools/lib/src/base/process.dart:627]: > You can test if this fix works by:

I was more wondering about the best way to **write** a test for it.

Comment (sigurdm) [reply packages/flutter_tools/lib/src/base/process.dart]: > But couldn't we just check if we are on a bot before invoking the print statement for the welcome message?

That works for me - updated

**Review by eliasyishak — APPROVED** [review]
LGTM if all presubmits pass!
