### PR TITLE
[Fix]: showDateRangePicker with "large" helpText cutoffs the save button

### LINKED ISSUE #146039: showDateRangePicker with "large" helpText cutoffs the save button
### Steps to reproduce

1. Create a date range picker with `showDateRangePicker`
2. Ensure it has a `helpText` that is a bit large.

Using a physical iPhone Pro 13, but smaller screens can get worse.

### Expected results

The label must grow on the vertical axis and not over the save button leading to impossible tap action.

### Actual results

The help text is over the button and you can't click it.

### Code sample

<details open><summary>Code sample</summary>

```dart
showDateRangePicker(
      context: context,
      firstDate: firstOfCurrentMonth,
      lastDate: lastOfCurrentMonth,
      helpText: 'Selecciona la fecha de corte y limite de pago',
      fieldStartLabelText: 'Fecha de corte',
      fieldStartHintText: 'Fecha de corte',
      fieldEndLabelText: 'Fecha limite de pago',
      fieldEndHintText: 'Fecha limite de pago',
    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

IMG_8552
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel master, 3.21.0-13.0.pre.20, on macOS 14.4.1 23E224 darwin-arm64, locale es-419)
    • Flutter version 3.21.0-13.0.pre.20 on channel master at /Users/misterquestions/bin/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision 085dbd85f9 (8 days ago), 2024-03-22 21:43:20 -0400
    • Engine revision 8a51e124fb
    • Dart version 3.4.0 (build 3.4.0-262.0.dev)
    • DevTools version 2.34.0-dev.12

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/misterquestions/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/misterquestions/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/misterquestions/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
    • IntelliJ at /Users/misterquestions/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.14888

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)            
    • iPhone de Fernando (mobile)     • 00008110-00144D9E0E3A801E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by zeqinjie**
Fix https://github.com/flutter/flutter/issues/146039

Pre-launch Checklist
- [x] I read the [Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), including [Features we expect every widget to implement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement).
- [x] I signed the [CLA](https://cla.developers.google.com/).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with ///).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

### CODE REVIEW

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 1]
```diff
@@ -260,7 +260,7 @@ void main() {
   });
 
   testWidgets('Save and help text is used', (WidgetTester tester) async {
-    helpText = 'help';
+    helpText = 'help select a date range please, make it so ,thanks!';
```
Comment (nate-thegrate) [inline packages/flutter/test/material/date_range_picker_test.dart:263]: Last month, I put in a [pull request for a tiny change](https://github.com/flutter/flutter/pull/143675) and edited one of the tests to cover it.

But then @goderbauer reviewed it and recommended creating a new test instead:

> My preference would be to add a new test for this specific case so it is clear what we want to test. The test could be named "ensure that merging listenables works with non-lists" or something like that.

I think the same concept applies here: instead of modifying the `'Save and help text is used'` test, you could duplicate the test, and maybe change the name to something like `"long helpText string doesn't cut off the 'save' button"`.

**Review by nate-thegrate — COMMENTED** [review]
Sorry for my poor explanation earlier—I think it'd be best to keep the existing test as-is, and add another test to cover this bugfix.

```dart
// existing test, unchanged
testWidgets('Save and help text is used', (WidgetTester tester) async {
  helpText = 'help';
  saveText = 'make it so';
  await preparePicker(tester, (Future<DateTimeRange?> range) async {
    expect(find.text(helpText!), findsOneWidget);
    expect(find.text(saveText!), findsOneWidget);
  });
});

// we should add a test like this
testWidgets("long helpText string doesn't cut off the 'save' button", (WidgetTester tester) async {
  helpText = 'long string' * 20;
  saveText = 'make it so';
  await preparePicker(tester, (Future<DateTimeRange?> range) async {
    expect(find.text(helpText!), findsOneWidget);
    expect(find.text(saveText!), findsOneWidget);
  });
});
```

<br>

_P.S. I don't have write access in this repository, so you'll need an approval from @MitchellGoodwin and 1 other person :)_

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for putting this together!

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 2]
```diff
@@ -268,6 +268,15 @@ void main() {
     });
   });
 
+  testWidgets('Long helpText cant not cutoffs the save button', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/date_range_picker_test.dart:271]: 'Long helpText does not cutoff the save button'

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 3]
```diff
@@ -268,6 +268,15 @@ void main() {
...
+    helpText = 'long helpText' * 100;
+    saveText = 'make it so';
+    await preparePicker(tester, (Future<DateTimeRange?> range) async {
+      expect(find.text(helpText!), findsOneWidget);
+      expect(find.text(saveText!), findsOneWidget);
```
Comment (justinmc) [inline packages/flutter/test/material/date_range_picker_test.dart:276]: It looks like this test will fail on master due to layout overflow, not due to these expectations. So I would add this line here: `expect(tester.takeException(), null);`

**Review by justinmc — COMMENTED** [review]
LGTM with nits, and assuming that the Google tests pass. This could break image diff tests I think.

**Review by justinmc — APPROVED** [review]
Sorry, forgot to check "approve".

File: packages/flutter/test/material/date_range_picker_test.dart (hunk 3 above)
Comment (zeqinjie) [reply packages/flutter/test/material/date_range_picker_test.dart]: @justinmc Thanks for your review, I have updated the test.

File: packages/flutter/test/material/date_range_picker_test.dart (hunk 2 above)
Comment (zeqinjie) [reply packages/flutter/test/material/date_range_picker_test.dart]: @justinmc Thanks for your review, I have updated the test.

**Comment by zeqinjie** [comment]
> Sorry, forgot to check "approve".

@justinmc Thank you , can your review again

File: packages/flutter/test/material/date_range_picker_test.dart [hunk 4]
```diff
@@ -268,12 +268,10 @@ void main() {
...
   });
 
-  testWidgets('Long helpText cant not cutoffs the save button', (WidgetTester tester) async {
+  testWidgets('Long helpText does not cutoff the save button', (WidgetTester tester) async {
     helpText = 'long helpText' * 100;
-    saveText = 'make it so';
     await preparePicker(tester, (Future<DateTimeRange?> range) async {
-      expect(find.text(helpText!), findsOneWidget);
-      expect(find.text(saveText!), findsOneWidget);
+      expect(tester.takeException(), null);
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/date_range_picker_test.dart:274]: I think it would be better to have the check you had before and this one. So both this `.takeException()` and the check for `helpText` and `saveText`.

Comment (nate-thegrate) [reply packages/flutter/test/material/date_range_picker_test.dart:274]: I believe the check for `helpText` and `saveText` is already there; the most recent commit reverts the change and adds a new test.

Here's what the branch looks like currently:

https://github.com/flutter/flutter/blob/3c26c7d2aa29917c901bec291a21755d43214195/packages/flutter/test/material/date_range_picker_test.dart#L261-L277

Comment (nate-thegrate) [reply packages/flutter/test/material/date_range_picker_test.dart:274]: Oh, that makes sense! 
```suggestion
      expect(tester.takeException(), null);
      expect(find.text(helpText!), findsOneWidget); 
      expect(find.text(saveText!), findsOneWidget); 
```

Comment (zeqinjie) [reply packages/flutter/test/material/date_range_picker_test.dart:277]: @MitchellGoodwin Thank you for the review, sorry for my misunderstanding, I have changed the test.
