### PR TITLE
fixes crash when invisible semantics nodes dropped from semantics tree

### LINKED ISSUE #184036: [Google3 Bug] _TypeError crash in _RenderObjectSemantics._buildSemanticsSubtree
### Help us understand the severity of this issue

- [x] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [ ] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

Unclear

### Expected results

App does not crash

### Actual results

~1000 crashes per day in production with the following stack trace:

```
_TypeError
at _RenderObjectSemantics._buildSemanticsSubtree	(object.dart:6235)
at PipelineOwner.flushSemantics	(object.dart:1625)
at PipelineOwner.flushSemantics	(object.dart:1642)
at RendererBinding.drawFrame	(binding.dart:636)
at WidgetsBinding.drawFrame	(binding.dart:1564)
at RendererBinding._handlePersistentFrameCallback	(binding.dart:495)
at RendererBinding._handlePersistentFrameCallback	(binding.dart:494)
at SchedulerBinding._invokeFrameCallback	(binding.dart:1430)
at SchedulerBinding.handleDrawFrame	(binding.dart:1345)
at SchedulerBinding._handleDrawFrame	(binding.dart:1198)
at SchedulerBinding._handleDrawFrame	(binding.dart:1180)
at _rootRun	(zone_root.dart:35)
at _rootRun	(zone_root.dart:26)
at _CustomZone.run	(zone.dart:726)
at _CustomZone.runGuarded	(zone.dart:625)
at _invoke	(hooks.dart:425)
at PlatformDispatcher._drawFrame	(platform_dispatcher.dart:447)
at _drawFrame	(hooks.dart:395)
at _drawFrame	(hooks.dart:393)
```

I believe the root cause is the `geometry!` invocation from https://github.com/flutter/flutter/pull/180375/changes#diff-4c298197a8aa7831a26eece096c8b8b07773ba1f5376d848ea4ef2924b606e9fR6235

### Code sample

None

### Screenshots or Video

None

### Logs

N/A, google3 internal

### Flutter Doctor output

N/A, google3 internal

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/184036

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/rendering/semantics_layout_sized_test.dart [hunk 1]
```diff
@@ -123,6 +123,55 @@ void main() {
...
+    // Adding a new child to grandParent makes it the new `lastChild`.
+    // Because grandParent only visits `lastChild` in `visitChildrenForSemantics`,
+    // the original `parent` and `child` will be dropped from the semantics tree
+    // without their parentDataDirty flags being cleared during the update phase.
+    final newChild = RenderTestLayoutSemanticsBoundary();
+    newChild.isSemanticBoundary = true;
+    grandParent.add(newChild);
+
+    // Flushing semantics now will run through flushSemantics.
+    // firstAncestorNodeWithCleanGeometry will be null at line 1618.
```
Comment (chunhtai) [inline packages/flutter/test/rendering/semantics_layout_sized_test.dart]:
```suggestion
```

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

File: packages/flutter/test/rendering/semantics_layout_sized_test.dart [hunk 2]
```diff
@@ -123,6 +123,53 @@ void main() {
...
+    layout(grandParent, phase: EnginePhase.flushSemantics);
+
+    // Initial state: grandParent visits parent (because parent is the last child).
+    // parent visits child. Thus all nodes are in the semantics tree.
+    expect(grandParent.debugSemantics!.childrenCount, 1);
+
+    // To trigger the scenario, we need grandParent to drop parent,
+    // explicitly marking parent and child as needing semantics update.
+    parent.markNeedsLayout();
+    child.markNeedsLayout();
```
Comment (LongCatIsLooong) [inline packages/flutter/test/rendering/semantics_layout_sized_test.dart:149]: for posterities: `child.geometry` is set to null here but will be re-computed in the next semantics flush (but the parent won't have geometry) so it will non-null.

Comment (LongCatIsLooong) [reply packages/flutter/test/rendering/semantics_layout_sized_test.dart:149]: from our offline convo: `child` needs to be updated in case at some point it needs to be re-added to the semantics tree.

So if the `parent` subtree is going to stay detached (as in, not being part of the geometry tree), it will continue being updated. I feel that could be a lot of extra work if the tree is going to stay detached for a couple frames, and tracking detached nodes and skipping updating them would be easier to maintain and sometimes more performant?
