### PR TITLE
[flutter_tools] allow adb to fail to un forward without crashing

### LINKED ISSUE #55810: Quitting (q) flutter attach to an android device while the original run instance is still going crashes.
Likely caused by trying to unforward the port twice.

```
Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally:
adb: error: listener 'tcp:63088' not found
  Command: /Users/jonahwilliams/Library/Android/sdk/platform-tools/adb -s 9B071FFAZ004TT forward --remove tcp:63088".
```

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      _AndroidDevicePortForwarder.unforward (package:flutter_tools/src/android/android_device.dart:1198:24)
#3      _AndroidDevicePortForwarder.dispose (package:flutter_tools/src/android/android_device.dart:1207:13)
#4      AndroidDevice.dispose (package:flutter_tools/src/android/android_device.dart:743:27)
#5      HotRunner.cleanupAtFinish (package:flutter_tools/src/run_hot.dart:1170:34)
#6      ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1160:11)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:334:22)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#16     ResidentRunner.refreshViews (package:flutter_tools/src/resident_runner.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#32     FlutterDevice.refreshViews (package:flutter_tools/src/resident_runner.dart)
#33     _rootRunUnary (dart:async/zone.dart:1192:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#39     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#40     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#41     FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart)
#42     _rootRunUnary (dart:async/zone.dart:1192:38)
#43     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#46     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#47     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#48     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#49     _rootRun (dart:async/zone.dart:1184:13)
#50     _CustomZone.run (dart:async/zone.dart:1077:19)
#51     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#52     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Currently the tool will crash if  adb fails to unforward a port. This should not be treated as an error condition though, because there are a variety of circumstances where it cannot be helped. One example is given in https://github.com/flutter/flutter/issues/55810 . 

Refactors the class so that it does not use the global ProcessUtils and instead accepts a ProcessManager and Logger. Remove the dependency on the entire AndroidDevice by passing the adb path and device id needed to run adb.

Fixes #55810

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -214,7 +214,7 @@ class AndroidDevice extends Device {
 
   AdbLogReader _logReader;
   AdbLogReader _pastLogReader;
-  _AndroidDevicePortForwarder _portForwarder;
+  AndroidDevicePortForwarder _portForwarder;
 
   List<String> adbCommandForDevice(List<String> args) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/android/android_device.dart:219]: I think there's only one more usage of this left, if you want to kill it.

**Review by jmagman — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/android_device.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/android_device.dart:219]: Theres a few more...
