### PR TITLE
Shared state to support multi screen inspection 

### LINKED ISSUE #5931: Widget inspection Magnifying glass experience broken in Multi View app
Magnifying glasses should be showing up on each seperate view when in Widget Inspection mode on a Multi View app

### PR DESCRIPTION
**Pull request by CoderDake**
Fixes https://github.com/flutter/devtools/issues/5931

With Multi View applications on the way, we need to be able to manage the state of multiple Inspector widgets in a consistent way.

Previously each Widget inspector would manage the state of it's own inspection. This made for a confusing and inconsistent experience when clicking on the widget inspector of different views.

This PR changes the state management to the WidgetInspectorService static instance so that all widget inspectors can share that state.

# Demo

https://github.com/flutter/flutter/assets/1386322/70fd18dc-5827-4dcd-8cb7-ef20e6221291

### CODE REVIEW

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -2829,18 +2836,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
         onPanUpdate: _handlePanUpdate,
         behavior: HitTestBehavior.opaque,
         excludeFromSemantics: true,
-        child: IgnorePointer(
-          ignoring: isSelectMode,
-          key: _ignorePointerKey,
-          child: widget.child,
+        child: ValueListenableBuilder<bool>(
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2839]: Repeating the value listenable builder with the same key is a bit of a code smell. Some options: move the ValueListenableBuilder to the root of the build method (the couple extra widgets that rebuild won't be a perf issue) or achieve the same effect by listening for changes to the valueListenable by registering a listener in initState and removing it in dispose.
You should also check whether this whole stateful widget can now be made stateless.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 2]
```diff
@@ -747,6 +748,18 @@ mixin WidgetInspectorService {
   /// The current [WidgetInspectorService].
   static WidgetInspectorService get instance => _instance;
   static WidgetInspectorService _instance = _WidgetInspectorService();
+
+  final ValueNotifier<bool> _isSelectMode = ValueNotifier<bool>(true);
```
[the remark this answers is not in the document]
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:752]: this is a good refactor. A similar refactor is needed for _selectionChangedCallback and the selection object. Right now, only one of the screens is going to update on selection changed because there is a single listener instead of a value notifier.

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 1 above)
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2839]: unless there is a way to remove the lastPointerLocation field, this is probably not feasible so I would instead switch to adding listeners in initState and disposing them in dispose.

**Review by jacob314 — COMMENTED** [review]
Overall looks like it is on the right track.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 3]
```diff
@@ -2795,29 +2801,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
       WidgetInspectorService.instance._sendInspectEvent(selection.current);
     }
-    setState(() {
-      // Only exit select mode if there is a button to return to select mode.
+
+  setState(() {
+    // Only exit select mode if there is a button to return to select mode.
       if (widget.selectButtonBuilder != null) {
-        isSelectMode = false;
+          WidgetInspectorService.instance.selectMode = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2815]: nit: unindent this by two

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 4]
```diff
@@ -2795,29 +2801,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
       return;
     }
     if (_lastPointerLocation != null) {
       _inspectAt(_lastPointerLocation!);
       WidgetInspectorService.instance._sendInspectEvent(selection.current);
     }
-    setState(() {
-      // Only exit select mode if there is a button to return to select mode.
+
+  setState(() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2812]: nit: indent this by two more

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 5]
```diff
@@ -2795,29 +2801,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
-    setState(() {
-      isSelectMode = true;
+    setState((){
+      WidgetInspectorService.instance.selectMode = true;
     });
   }
 
   @override
-  Widget build(BuildContext context) {
+    Widget build(BuildContext context) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2827]: nit: revert the indentation change?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 6]
```diff
@@ -2795,29 +2801,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
+          WidgetInspectorService.instance.selectMode = false;
       }
     });
   }
 
   void _handleEnableSelect() {
-    setState(() {
-      isSelectMode = true;
+    setState((){
+      WidgetInspectorService.instance.selectMode = true;
```
[the remark this answers is not in the document]
Comment (CoderDake) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2822]: This is something I was curious about so I'm happy you noticed it too :D

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 7]
```diff
@@ -2829,18 +2836,30 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
+            if (!isSelectMode && widget.selectButtonBuilder != null) {
+              return Positioned(
+                left: _kInspectButtonMargin,
+                bottom: _kInspectButtonMargin,
+                child:
+                    widget.selectButtonBuilder!(context, _handleEnableSelect),
+              );
+            }
+            return const SizedBox.shrink();
+          }),
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2862]: nit: unindent by two

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 8]
```diff
@@ -747,6 +748,18 @@ mixin WidgetInspectorService {
...
+
+  final ValueNotifier<bool> _isSelectMode = ValueNotifier<bool>(true);
+
+  /// Whether the inspector is in select mode.
+  ///
+  /// In select mode, pointer interactions trigger widget selection instead of
+  /// normal interactions. Otherwise the previously selected widget is
+  /// highlighted but the application can be interacted with normally.
+  ValueListenable<bool> get isSelectMode => _isSelectMode;
+  set selectMode(bool value) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:760]: I am somewhat surprised that this doesn't trigger the `avoid_setters_without_getters` lint since this setter doesn't have a getter by the same name.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 9]
```diff
@@ -747,6 +748,18 @@ mixin WidgetInspectorService {
...
   static WidgetInspectorService _instance = _WidgetInspectorService();
+
+  final ValueNotifier<bool> _isSelectMode = ValueNotifier<bool>(true);
+
+  /// Whether the inspector is in select mode.
+  ///
+  /// In select mode, pointer interactions trigger widget selection instead of
+  /// normal interactions. Otherwise the previously selected widget is
+  /// highlighted but the application can be interacted with normally.
+  ValueListenable<bool> get isSelectMode => _isSelectMode;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:759]: Does this `ValueListenable` have to be public? Would it be enough to just have a public getter/setter for _isSelectMode.value?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:759]: Actually, do we even need public setter/getters for this? Who would be calling this outside of this file? Looks like it is just a test? Should the setter even be marked as `@visibleForTesting`?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 10]
```diff
@@ -2643,41 +2654,27 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
   void dispose() {
-    if (WidgetInspectorService.instance.selectionChangedCallback == _selectionChangedCallback) {
-      WidgetInspectorService.instance.selectionChangedCallback = null;
-    }
+    WidgetInspectorService.instance._selectionChanged.removeListener(_setState);
+    WidgetInspectorService.instance.isSelectMode.removeListener(_setState);
     super.dispose();
   }
-
+  void _setState() => setState((){});
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2677]: nit: its good practice to leave a comment inside the empty set describing why its empty (e.g. because WidgetInspectorService.instance.isSelectMode.value has changed and it is used in the built method we have to rebuild - or something like that.

**Comment by wanjm** [comment]
where can i get the multi window example in the above video;

**Comment by CoderDake** [comment]
@wanjm It can be found here:
https://github.com/goderbauer/mvp

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 11]
```diff
@@ -747,6 +747,28 @@ mixin WidgetInspectorService {
...
+  ///
+  /// In select mode, pointer interactions trigger widget selection instead of
+  /// normal interactions. Otherwise the previously selected widget is
+  /// highlighted but the application can be interacted with normally.
+  @visibleForTesting
+  final ValueNotifier<bool> isSelectMode = ValueNotifier<bool>(true);
+
+  /// For use by [WidgetInspector] widgets so they can be notified when the
+  /// selection has changed.
+  ValueListenable<int> get _selectionChanged => _selectionChangeCount;
```
[the remark this answers is not in the document]
Comment (CoderDake) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:761]: There is no specific need for the count, we are just leveraging the ability to trigger the listeners each time the count changes.

If there are more direct ways to do this I'd be open to them. The other methods I found seemed move convoluted though.

[the remark this answers is not in the document]
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:761]: It would require some slight refactoring but the most idiomatic would be to use the InspectorSelection object as the value. You would need to tweak it so it is immutable changing the methods that mutate it to return a new InspectorSelectionObject. That would also make it harder to introduce bugs in the future due to the selection change becoming out of sync with calls to _notifiySelectionChanged.

[the remark this answers is not in the document]
Comment (CoderDake) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: @jacob314 I've added these changes to try to simplify the callback triggering cycle.

Since the WidgetInspectorService is a mixing I wasn't able to set the listener directly there, so in the tests I had to duplicate it. I'm not too excited about it, do you know of a better way that listener could come into existence?

[the remark this answers is not in the document]
Comment (CoderDake) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: Oops looks like I didn't post the link, here you go:
https://github.com/flutter/flutter/pull/129452/commits/7748464ceabf1bf486c9308f6d45e018562ec33b

**Comment by CoderDake** [comment]
Fixes https://github.com/flutter/devtools/issues/5935

**Comment by CoderDake** [comment]
Fixes https://github.com/flutter/devtools/issues/5931

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 12]
```diff
@@ -716,7 +716,15 @@ class InspectorReferenceData {
 }
 
 // Production implementation of [WidgetInspectorService].
-class _WidgetInspectorService = Object with WidgetInspectorService;
+class _WidgetInspectorService with WidgetInspectorService {
+  _WidgetInspectorService() {
+    selection.addListener(() {
+      if (selectionChangedCallback != null) {
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:722]: nit: use pattern
`final selectionChangedCallback = this.selectionChangedCallback;`
to avoid dupe null check due to limitations of Dart type inference.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 13]
```diff
@@ -2675,47 +2681,47 @@ class WidgetInspector extends StatefulWidget {
...
-    }
+    WidgetInspectorService.instance.selection
+        .removeListener(_selectionInformationChanged);
+    WidgetInspectorService.instance.isSelectMode
+        .removeListener(_selectionInformationChanged);
     super.dispose();
   }
 
+  void _selectionInformationChanged() => setState((){
+    // Triggers a rebuild of the WidgetInspector. For use when dependant
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2721]: nit: more idiomatic: load the current value of the selection into local fields here.
e.g.
selection = instance.selection.value;
selectMode = instance.isSelectMode.value
that way you don't need a comment. Downside is you will need to sync the initial value in initState.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 14]
```diff
@@ -2675,47 +2681,47 @@ class WidgetInspector extends StatefulWidget {
...
 
-  /// Whether the inspector is in select mode.
-  ///
-  /// In select mode, pointer interactions trigger widget selection instead of
-  /// normal interactions. Otherwise the previously selected widget is
-  /// highlighted but the application can be interacted with normally.
-  bool isSelectMode = true;
+  bool get isSelectMode =>
+      WidgetInspectorService.instance.isSelectMode.value;
+  set isSelectMode(bool value) =>
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2693]: this is a bit of an overly picky style issue and perhaps just my preference.
I would avoid adding getters and setters that obfuscate what is going on. Code written like this makes it look like you have a stateful widget where you are not calling setState while modifying the state. Instead return just a getter that returns WidgetInspectorService.instance.isSelectMode
or inline the full lines.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 15]
```diff
@@ -2840,18 +2842,15 @@ class _WidgetInspectorState extends State<WidgetInspector>
...
-    setState(() {
-      // Only exit select mode if there is a button to return to select mode.
-      if (widget.selectButtonBuilder != null) {
-        isSelectMode = false;
-      }
-    });
+
+    // Only exit select mode if there is a button to return to select mode.
+    if (widget.selectButtonBuilder != null) {
+      isSelectMode = false;
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2848]: this line will be clearer written as 
isSelectMode.value = true;

as that doesn't make it look like you are missing a setState call.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 16]
```diff
@@ -3234,7 +3238,10 @@ class _InspectorOverlayLayer extends Layer {
     Rect targetRect,
   ) {
     canvas.save();
-    final double maxWidth = size.width - 2 * (_kScreenEdgeMargin + _kTooltipPadding);
+    final double maxWidth = math.max(
+      size.width - 2 * (_kScreenEdgeMargin + _kTooltipPadding),
+      0,
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:3243]: good catch! should we just short circuit and not try to draw anything is maxWidth <= 0?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 17]
```diff
@@ -2885,7 +2884,7 @@ class _WidgetInspectorState extends State<WidgetInspector>
 }
 
 /// Mutable selection state of the inspector.
-class InspectorSelection {
+class InspectorSelection with ChangeNotifier {
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2887]: clever. this is a simpler change than making InspectorSelection immutable.

Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2887]: it is probably worth adding a test to verify that you are notifying of changes for all the methods that should.

**Review by jacob314 — COMMENTED** [review]
LGTM once these small nits are resolved.

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 16 above)
Comment (CoderDake) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:3243]: Perhaps we could but I don't know enough about these cases to know if we always want to.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 18]
```diff
@@ -394,16 +395,19 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
         ),
       );
 
-      expect(getInspectorState().selection.current, isNull); // ignore: avoid_dynamic_calls
+      expect(WidgetInspectorService.instance.selection.current, isNull); // ignore: avoid_dynamic_calls
```
Comment (goderbauer) [inline packages/flutter/test/widgets/widget_inspector_test.dart:398]: Can we remove the ` // ignore:` here now? This should no longer be a dynamic call.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 19]
```diff
@@ -394,16 +395,19 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
       await tester.pump();
       // Tap intercepted by the inspector
       expect(log, equals(<String>[]));
       // ignore: avoid_dynamic_calls
-      final InspectorSelection selection = getInspectorState().selection as InspectorSelection;
-      expect(paragraphText(selection.current! as RenderParagraph), equals('TOP'));
+      expect(
+          paragraphText(WidgetInspectorService.instance.selection.current!
+              as RenderParagraph),
+          equals('TOP'));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/widget_inspector_test.dart:407]: formatting nit:

```suggestion
      expect(
        paragraphText(WidgetInspectorService.instance.selection.current! as RenderParagraph),
        equals('TOP'),
      );
```

Comment (goderbauer) [reply packages/flutter/test/widgets/widget_inspector_test.dart:407]: Same elsewhere in this file.

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 20]
```diff
@@ -394,16 +395,19 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
...
       final RenderObject topButton = find.byKey(topButtonKey).evaluate().first.renderObject!;
-      expect(selection.candidates, contains(topButton));
+      expect(WidgetInspectorService.instance.selection.candidates,
+          contains(topButton));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/widget_inspector_test.dart:410]: I'd probably just leave this on one line (or format it multi line as shown in my example above).

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 21]
```diff
@@ -498,7 +506,7 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
 
       await tester.tap(find.byType(ListView), warnIfMissed: false);
       await tester.pump();
-      expect(getInspectorState().selection.current, isNotNull); // ignore: avoid_dynamic_calls
+      expect(WidgetInspectorService.instance.selection.current, isNotNull); // ignore: avoid_dynamic_calls
```
Comment (goderbauer) [inline packages/flutter/test/widgets/widget_inspector_test.dart:509]: remove `ignore`?

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by jacob314 — APPROVED** [review]
lgtm
