### PR TITLE
Make desktop stopApp only apply to processes Flutter started

### LINKED ISSUE #41454: NoSuchMethodError while running driver test on macos. I am receiving similar errors on any device other than android/ios
## command

flutter drive --target=test_driver/app.dart

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'index' was called on null.
Receiver: null
Tried calling: index

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      getNameForBuildMode (package:flutter_tools/src/build_info.dart:130:33)
#2      BuildableMacOSApp.applicationBundle (package:flutter_tools/src/macos/application_package.dart:135:21)
#3      BuildableMacOSApp.executable (package:flutter_tools/src/macos/application_package.dart:141:30)
#4      MacOSDevice.stopApp (package:flutter_tools/src/macos/macos_device.dart:126:28)
<asynchronous suspension>
#5      _stopApp (package:flutter_tools/src/commands/drive.dart:329:45)
<asynchronous suspension>
#6      _startApp (package:flutter_tools/src/commands/drive.dart:242:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:124:51)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:535:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.7-pre.25, on Mac OS X 10.14.6 18G95, locale en-US)
    [32m•[39m Flutter version 1.10.7-pre.25 at /Users/donatkajtazi/Development/Flutter-SDK/flutter
    [32m•[39m Framework revision e47a1dc216 (18 hours ago), 2019-09-26 07:18:25 -0700
    [32m•[39m Engine revision 9fd35df9bb
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 dd65f97118)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/donatkajtazi/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.0, Build version 11A420a
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS  • macOS  • darwin-x64     • Mac OS X 10.14.6 18G95
    [32m•[39m Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    [32m•[39m Server • web    • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
## Description

Currently, the logic for stopping processes in the `*Device` classes for desktop is inconsistent and only works in some cases. Since desktop allows multiple copies of an app, the constraints on `stopApp` aren't the same as mobile. This is already reflected in `startApp` not calling `stopApp`, but there are other codepaths that still try, and can fail, even crashing the tool in some cases.

Rather than trying to do something platform-specific, this make `startApp` on desktop keep track of process it has started and are currently running, and implements `stopApp` by terminating exactly those processes.

To support this without duplicating even more logic across the three classes, this also extracts a new `DesktopDevices` base class, which now contains most of the functionality that was previously in the macOS, Windows, and Linux versions.

## Related Issues

Fixes #41454

## Tests

I added the following tests:
- desktop_device_test.dart
- new tests in macos/windows/linux_device_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Added tests for `DesktopDevice` and cleaned up the per-platform tests (removed things testing the old kill logic, and that are core to `DesktopDevice` now; the later we could potentially add back for future-proofing, but my vote would be to do that later if something diverges instead of having four copies of tests now).

Still needs test coverage of the new platform-specific methods that implement the DesktopDevice abstract methods, so still WIP for now.

**Comment by stuartmorgan** [comment]
This is ready for review now. There are tests covering the changed logic, and most of the moved code.

There is no testing of `buildForDevice`, but that logic wasn't tested before either, so this patch is a no-op from that standpoint, despite the refactoring. The right way to test those would be to move the underlying logic into something mockable, since they are just calling through to build functions that should be tested elsewhere, but that was out of scope for this change.

File: packages/flutter_tools/lib/src/macos/macos_device.dart [hunk 1]
```diff
@@ -2,145 +2,67 @@
...
-
-  @override
-  bool isSupportedForProject(FlutterProject flutterProject) {
-    return flutterProject.macos.existsSync();
+  void onAttached(covariant MacOSApp package, BuildMode buildMode, Process process) {
+    // Bring app to foreground. Ideally this would be done post-launch rather
+    // than post-attach, since this won't run for release builds, but there's
+    // no general-purpose way of knowing when a process is far enoug along in
+    // the launch process for 'open' to foreground it.
+    processManager.run(<String>[
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/macos_device.dart]: Should this be awaited in some way?

**Review by jonahwilliams — COMMENTED** [review]
This is a really nice cleanup, thank you!

I'm almost done reviewing, just a small comment

File: packages/flutter_tools/lib/src/macos/macos_device.dart (hunk 1 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/macos/macos_device.dart]: I can wire it up as async/await if you think it's clearer. I don't think it actually matters though (unless I'm forgetting something) since nothing in the tool cares whether it's foreground or background.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/macos/macos_device.dart]: Yeah, I don't think we necessarily need to block anything on this - but we might want to stick a `.then` to handle failures

File: packages/flutter_tools/lib/src/desktop_device.dart [hunk 2]
```diff
@@ -0,0 +1,173 @@
+// Copyright 2019 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:async';
+import 'dart:io';
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/desktop_device.dart]: Instead import base/io.dart to make the tests happy

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 2 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/desktop_device.dart]: Someday I'll figure out how to stop having this done automagically for me by VS Code :P

**Comment by maxim-smotrov** [comment]
Hi @stuartmorgan! Sorry to bother you, is it possible to fix the tests and merge this soon?

**Comment by jonahwilliams** [comment]
I can take a look at finishing this one up next week too

File: packages/flutter_tools/lib/src/macos/macos_device.dart (hunk 1 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/macos/macos_device.dart]: Added error logging in a `then`. Feel free to alter if you had something else in mind since I'm not sure when I'll next have a chance to iterate on it.

**Comment by gspencergoog** [comment]
@jonahwilliams, are you OK with taking this one over now that Stuart is out?

**Comment by jonahwilliams** [comment]
Looks like it should be good to go, modulo the tree redness
