### PR TITLE
Make positionInlineChildren assert much clearer

### LINKED ISSUE #182090: Misleading error message in positionInlineChildren assert
When incorrectly implementing a custom InlineSpan, I encountered an assert inside the `positionInlineChildren` function with the following message:

> The length of boxes (5) should be greater than childCount (1)

Looking only at this message, I would think my implementation is correct (5 is indeed greater than 1). However, the logic in the `positionInlineChildren` function expects the opposite: the number of boxes must NOT exceed the number of children (childCount).
```dart
  @protected
  void positionInlineChildren(List<ui.TextBox> boxes) {
    RenderBox? child = firstChild;
    for (final box in boxes) {
      if (child == null) {
        assert(
          false,
          'The length of boxes (${boxes.length}) should be greater than childCount ($childCount)',
        );
        return;
      }
      final textParentData = child.parentData! as TextParentData;
      textParentData._offset = Offset(box.left, box.top);
      child = childAfter(child);
    }
    while (child != null) {
      final textParentData = child.parentData! as TextParentData;
      textParentData._offset = null;
      child = childAfter(child);
    }
  }
```
The current message is logically incorrect and misleading for debugging.

### PR DESCRIPTION
**Pull request by BrainLUX**
fixes [flutter/flutter#182090](https://github.com/flutter/flutter/issues/182090)

The assertion message should clearly state the actual requirement of the code to help developers understand and fix the error.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -219,8 +219,8 @@ mixin RenderInlineChildrenContainerDefaults
     for (final box in boxes) {
       if (child == null) {
         assert(
-          false,
-          'The length of boxes (${boxes.length}) should be greater than childCount ($childCount)',
+          boxes.length <= childCount,
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/paragraph.dart]: I'm assuming the fact that we are in this if-block means there is an additional box not accounted for.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 1 above)
Comment (BrainLUX) [reply packages/flutter/lib/src/rendering/paragraph.dart]: In fact, yes, that's true.
But explicitly specifying the condition will make debugging easier for developers.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM but I think this may need a test, since you already have an implementation that would trigger the assert.

**Comment by justinmc** [comment]
@BrainLUX Would you be able to add a test here that catches the logical change of when the error occurs?

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/paragraph.dart]: I think I initially wrote the assert under the assumption that it wasn't going to be an app developer facing error message (so the error message was only useful for framework developers), but it looks like this is not the case. Was it because you didn't push placeholders in the custom InlineSpan in `InlineSpan.build`? In any case it might be helpful to expand the error message a little more to include the most probable cause (e.g. did you forget to push placeholders if you are using a custom InlineSpan subclass?)

**Comment by LongCatIsLooong** [comment]
still LGTM, but maybe this should be expanded to a more detailed message, like the one over here: https://github.com/flutter/flutter/blob/1e97fd38cf89f94f5159f4e9d0b598a0871103ab/packages/flutter/lib/src/rendering/object.dart#L2224-L2241

so people ran into the same problem don't have to figure out what could have caused the assert to fire.

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 2]
```diff
@@ -218,10 +218,28 @@ mixin RenderInlineChildrenContainerDefaults
     RenderBox? child = firstChild;
     for (final box in boxes) {
       if (child == null) {
-        assert(
-          false,
-          'The length of boxes (${boxes.length}) should be greater than childCount ($childCount)',
-        );
+        assert(() {
+          if (boxes.length > childCount) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/paragraph.dart]: nit: I feel this is no longer needed since there is now a detailed message.

**Review by LongCatIsLooong — APPROVED** [review]
Still LGTM, thank you for adding the detailed error message!

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 2 above)
Comment (BrainLUX) [reply packages/flutter/lib/src/rendering/paragraph.dart]: Agreed.

**Review by victorsanni — APPROVED** [review]
