### PR TITLE
Correct notch geometry when MediaQuery padding.top is non-zero

### LINKED ISSUE #90024: Flutter 2.5 floatingActionButton centerDocked notch problem
Hello. When floatingActionButton is centerDocked in BottomNavigationBar with CircularNotchedRectangle on a widget with SafeArea the notch is wrong.

If you remove SafeArea widget works fine. The problem is with Flutter 2.5

Sample code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(child: Home()),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        //Floating action button on Scaffold
        onPressed: () {
          //code to execute on button press
        },
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.directions,
              color: Colors.white,
            ),
            Text(
              'Viaje',
              style: TextStyle(
                fontSize: 10.0,
                color: Colors.white,
              ),
            ),
          ],
        ), //icon inside button
      ),

      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      //floating action button position to center
      bottomNavigationBar: BottomAppBar(
        //bottom navigation bar on scaffold
        color: Colors.redAccent,
        shape: CircularNotchedRectangle(), //shape of notch
        notchMargin: 5, //notche margin between floating button and bottom appbar
        child: Row(
          //children inside bottom appbar
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            IconButton(
              icon: Icon(
                Icons.menu,
                color: Colors.white,
              ),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(
                Icons.search,
                color: Colors.white,
              ),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(
                Icons.print,
                color: Colors.white,
              ),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(
                Icons.people,
                color: Colors.white,
              ),
              onPressed: () {},
            ),
          ],
        ),
      ),
    );
  }
}
```
Result:
Screenshot_1631588469

Removing SafeArea result is fine:
Screenshot_1631588517

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1165], locale es-CO)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.55.2)
[√] Connected device (3 available)

• No issues found!

### LINKED ISSUE #90276: CircularNotchedRectangle in BottomAppBar in BottomSheet not working as expected
My BottomSheet: (Notch doesn't work here)
```
class MyBottomSheet extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Bottom Sheet App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        notchMargin: 6,
        shape: CircularNotchedRectangle(),
        clipBehavior: Clip.antiAlias, // I have tried this with and without this line
        child: Container(
          height: 60,
        ),
      ),
      body: Center(
        child: Text('I am the Body'),
      ),
    ),
  }
}
```

My class calling the BottomSheet: (Notch works here)
```
class MyParentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Parent App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        notchMargin: 6,
        shape: CircularNotchedRectangle(),
        clipBehavior: Clip.antiAlias, // I have tried this with and without this line
        child: Container(
          height: 60,
        ),
      ),
      body: Center(
        child: ElevatedButton(
          child: const Text('Open Bottom Sheet'),
            onPressed: openBottomSheet,
          ),
        ),
      ),
    ),
  }
}
```

Prior to Flutter 2.5.0 CircularNotchedRectangle in a BottomAppBar in BottomSheet worked as expected once I updated it stopped working.

**Expected results:**  BottomAppBar to have a notch in MyBottomSheet

**Actual results:** BottomAppBar did not have a notch in MyBottomSheet

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.0 at /Users/craighowell/Documents/flutter_workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/craighowell/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/craighowell/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/90024
Fixes https://github.com/flutter/flutter/issues/90276

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_app_bar.dart [hunk 1]
```diff
@@ -174,7 +174,14 @@ class _BottomAppBarClipper extends CustomClipper<Path> {
   final double notchMargin;
 
   // Returns the top of the BottomAppBar in global coordinates.
+  //
+  // If the Scaffold's bottomNavigationBar was specified, then we can use its
+  // geometry value, otherwise we compute the location base on the AppBar's
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/material/bottom_app_bar.dart:179]: based

Comment (HansMuller) [reply packages/flutter/lib/src/material/bottom_app_bar.dart]: Good catch; done

**Review by Piinks — APPROVED** [review]
LGTM 🎉
