### PR TITLE
Fix vertical SegmentedButton not filling available width under bounded constraints

### LINKED ISSUE #178901: Segmented Button tap target size and selected background color not expanded
### Steps to reproduce

1. Create a `SegmentedButton` with multiple segments.
2. Wrap it inside a `SizedBox(width: double.infinity)` to force full-width layout.
3. Apply `SegmentedButton.styleFrom` with `fixedSize`, `minimumSize`, and `maximumSize` all set to `Size(double.infinity, ...)`.
4. Run the app and observe the layout and tap behavior.

### Expected results

- Each segment should expand to fill the full available width.
- The selected segment’s background should span the full width of its segment.
- Tap targets should be full-width and match the visual bounds of each segment

### Actual results

- The SegmentedButton expands horizontally, but individual segments do not stretch to fill the width.
- The selected segment’s background remains narrow and does not span the full width.
- Tap targets are smaller than expected, making the UI feel misaligned and harder to interact with.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: double.infinity,
            child: SegmentedButton<String>(
              direction: Axis.vertical,
              emptySelectionAllowed: false,
              multiSelectionEnabled: false,
              showSelectedIcon: false,
              style: SegmentedButton.styleFrom(
                fixedSize: const Size(double.infinity, 300),
                minimumSize: const Size(double.infinity, 300),
                maximumSize: const Size(double.infinity, double.infinity),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(5),
                  side: const BorderSide(),
                ),
              ),
              segments: const [
                ButtonSegment(value: 'All', label: Text('All')),
                ButtonSegment(value: 'Top free', label: Text('Top free')),
                ButtonSegment(value: 'Top paid', label: Text('Top paid')),
              ],
              selected: const {'All'},
              onSelectionChanged: (newSelection) {
                // dummy test; nothing needed
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.35.4, on Microsoft Windows [Version 10.0.26200.7171], locale en-US)
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[√] Windows Version (Windows 11 or higher, 25H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.14.8)
[√] Android Studio (version 2025.1.1)
[√] VS Code, 64-bit edition (version 1.103.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes an issue where vertical segments used intrinsic width instead of expanding to fill the parent's bounded width, resulting in narrow tap targets.

Fixes [#178901](https://github.com/flutter/flutter/issues/178901)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/segmented_button_test.dart
Comment (Mairramer) [inline packages/flutter/test/material/segmented_button_test.dart:1267]: The layout change causes the vertical `SegmentedButton` to consume the full parent width. This is an intentional fix for the reported issue, but it results in a mismatch with current golden files which captured the previous intrinsic-width behavior.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/material/segmented_button.dart [hunk 1]
```diff
@@ -998,6 +998,14 @@ class _RenderSegmentedButton<T> extends RenderBox
       maxWidth = math.max(maxWidth, boxWidth);
       child = childAfter(child);
     }
+
+    // When the parent enforces a bounded width, ensure each child
```
Comment (huycozy) [inline packages/flutter/lib/src/material/segmented_button.dart]: is this added to [_calculateVerticalChildSize](https://github.com/flutter/flutter/blob/d7965e1e136a3f8b7889f556a75a078c986a0ed7/packages/flutter/lib/src/material/segmented_button.dart#L981). I think this should be added to [_calculateHorizontalChildSize](https://github.com/flutter/flutter/blob/d7965e1e136a3f8b7889f556a75a078c986a0ed7/packages/flutter/lib/src/material/segmented_button.dart#L958), correct?

File: packages/flutter/test/material/segmented_button_test.dart [hunk 2]
```diff
@@ -1587,6 +1587,65 @@ void main() {
     );
     expect(tester.getSize(find.byType(SegmentedButton<String>)), Size.zero);
   });
+
+  testWidgets('SegmentedButton should expand to fill the full width', (WidgetTester tester) async {
+    tester.view
+      ..physicalSize = const Size(800, 1200)
+      ..devicePixelRatio = 1.0;
+    addTearDown(tester.view.resetPhysicalSize);
```
Comment (huycozy) [inline packages/flutter/test/material/segmented_button_test.dart]: looks like it's missing reset `devicePixelRatio` here. Is it good(the test is passed) if using this instead? `addTearDown(tester.view.reset);` (similar to other tests)

File: packages/flutter/lib/src/material/segmented_button.dart (hunk 1 above)
Comment (Mairramer) [reply packages/flutter/lib/src/material/segmented_button.dart]: No, it should actually be in [_calculateVerticalChildSize](https://github.com/flutter/flutter/blob/d7965e1e136a3f8b7889f556a75a078c986a0ed7/packages/flutter/lib/src/material/segmented_button.dart#L981), because that’s where the width is determined for rendering. In contrast, [_calculateHorizontalChildSize](https://github.com/flutter/flutter/blob/d7965e1e136a3f8b7889f556a75a078c986a0ed7/packages/flutter/lib/src/material/segmented_button.dart#L958) handles the main axis (width) sizing, so cross-axis width adjustments are not needed there.

File: packages/flutter/lib/src/material/segmented_button.dart [hunk 3]
```diff
@@ -998,6 +998,14 @@ class _RenderSegmentedButton<T> extends RenderBox
...
+    // occupies the full available width, preventing segments from
+    // shrinking to their intrinsic content size.
+    if (constraints.hasBoundedWidth) {
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/segmented_button.dart]: Hmmm this change seems will break the existing behavior. Originally the size of the segmented button will only be the size that children needed (see the `while` loop above). But with this change, the button width will equal to parent width. Let me know if I misunderstood anything:)

Before:

Image

After applying the change here:

Image

Comment (Mairramer) [reply packages/flutter/lib/src/material/segmented_button.dart]: It will indeed break the current behavior, but I’ll adjust it to avoid that.

File: packages/flutter/test/material/segmented_button_test.dart
Comment (Mairramer) [reply packages/flutter/test/material/segmented_button_test.dart:1267]: It's not going to change.

**Review by QuncCccccc — APPROVED** [review]
LGTM with one nit:) Thank you!

File: packages/flutter/test/material/segmented_button_test.dart [hunk 4]
```diff
@@ -1587,6 +1587,65 @@ void main() {
...
+                showSelectedIcon: false,
+                style: SegmentedButton.styleFrom(
+                  fixedSize: const Size(double.infinity, 300),
+                  minimumSize: const Size(double.infinity, 500),
+                  maximumSize: Size.infinite,
+                  shape: RoundedRectangleBorder(
+                    borderRadius: BorderRadius.circular(5),
+                    side: const BorderSide(),
+                  ),
+                ),
```
Comment (QuncCccccc) [inline packages/flutter/test/material/segmented_button_test.dart]: I think these style configurations are redundant. Maybe we can remove them to keep the unit test simple.
