### PR TITLE
Fix/decoration equality

### LINKED ISSUE #61549: BoxDecoration.hashCode crash devtools
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

remove `test/widget_test.dart`

<details>
  <summary>

`main.dart`

  </summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        tabBarTheme: TabBarTheme(
          indicator: BoxDecoration(
            boxShadow: [BoxShadow()],
          ),
        ),
      ),
      home: SizedBox(),
    ),
  );
}
```

</details>

3. open devtools, try to use flutter inspector or hotreload.

**Expected results:** 

Everything works fine.

**Actual results:** 

Most of the features of devtools aren't working, flutter inspector pointer looping through some random widgets and the following exception occurs:

<details>
  <summary>StackTrace</summary>

```
════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":
'dart:ui/hash_codes.dart': Failed assertion: line 17: '<optimized out>': is not true.

When the exception was thrown, this was the stack: 
#2      _Jenkins.combine (dart:ui/hash_codes.dart:17:12)
#3      hashValues (dart:ui/hash_codes.dart:60:27)
#4      BoxDecoration.hashCode (package:flutter/src/painting/box_decoration.dart:331:12)
#5      _Jenkins.combine (dart:ui/hash_codes.dart:18:35)
#6      hashValues (dart:ui/hash_codes.dart:53:21)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for
"ext.flutter.inspector.getDetailsSubtree":
'dart:ui/hash_codes.dart': Failed assertion: line 17: '<optimized out>': is not true.

When the exception was thrown, this was the stack:
#2      _Jenkins.combine (dart:ui/hash_codes.dart:17:12)
#3      hashValues (dart:ui/hash_codes.dart:60:27)
#4      BoxDecoration.hashCode (package:flutter/src/painting/box_decoration.dart:331:12)
#5      _Jenkins.combine (dart:ui/hash_codes.dart:18:35)
#6      hashValues (dart:ui/hash_codes.dart:53:21)
#7      TabBarTheme.hashCode (package:flutter/src/material/tab_bar_theme.dart:111:12)
#8      _Jenkins.combine (dart:ui/hash_codes.dart:18:35)
#9      hashList (dart:ui/hash_codes.dart:120:25)
#10     ThemeData.hashCode (package:flutter/src/material/theme_data.dart:1561:12)
#11     shortHash (package:flutter/src/foundation/diagnostics.dart:3003:17)
#12     describeIdentity (package:flutter/src/foundation/diagnostics.dart:3015:94)
#13     Diagnosticable.toStringShort (package:flutter/src/foundation/diagnostics.dart:3104:29)
#14     DiagnosticableNode.toDescription.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2972:22)
#15     DiagnosticableNode.toDescription (package:flutter/src/foundation/diagnostics.dart:2974:6)
#16     TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1195:31)
#17     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1128:14)
#18     DiagnosticsNode.toStringDeep.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1748:9)
#19     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1755:6)
#20     DiagnosticsNode.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1661:18)
#21     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1676:6)
#22     Diagnosticable.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3110:78)
#23     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:3112:6)
#24     _StringBase._interpolate (dart:core-patch/string_patch.dart:848:19)
#25     Tween.toString (package:flutter/src/animation/tween.dart:266:86)
#26     DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:61)
#27     DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2754:21)
#28     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1569:24)
#29     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#30     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2694:44)
#31     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#32     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#33     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#34     new List.from (dart:core-patch/array_patch.dart:38:29)
#35     new List.of (dart:core-patch/array_patch.dart:68:17)
#36     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#37     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#38     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2688:36)
#39     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#40     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#41     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#42     new List.from (dart:core-patch/array_patch.dart:38:29)
#43     new List.of (dart:core-patch/array_patch.dart:68:17)
#44     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#45     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#46     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1595:25)
#47     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#48     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#49     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#50     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#51     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#52     new List.from (dart:core-patch/array_patch.dart:38:29)
#53     new List.of (dart:core-patch/array_patch.dart:68:17)
#54     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#55     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#56     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#57     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#58     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#59     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#60     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#61     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#62     new List.from (dart:core-patch/array_patch.dart:38:29)
#63     new List.of (dart:core-patch/array_patch.dart:68:17)
#64     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#65     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#66     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#67     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#68     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#69     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#70     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#71     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#72     new List.from (dart:core-patch/array_patch.dart:38:29)
#73     new List.of (dart:core-patch/array_patch.dart:68:17)
#74     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#75     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#76     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#77     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#78     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#79     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#80     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#81     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#82     new List.from (dart:core-patch/array_patch.dart:38:29)
#83     new List.of (dart:core-patch/array_patch.dart:68:17)
#84     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#85     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#86     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#87     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#88     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#89     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#90     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#91     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#92     new List.from (dart:core-patch/array_patch.dart:38:29)
#93     new List.of (dart:core-patch/array_patch.dart:68:17)
#94     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#95     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#96     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#97     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#98     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#99     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#100    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#101    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#102    new List.from (dart:core-patch/array_patch.dart:38:29)
#103    new List.of (dart:core-patch/array_patch.dart:68:17)
#104    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#105    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#106    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#107    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#108    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#109    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#110    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#111    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#112    new List.from (dart:core-patch/array_patch.dart:38:29)
#113    new List.of (dart:core-patch/array_patch.dart:68:17)
#114    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#115    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#116    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#117    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#118    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#119    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#120    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#121    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#122    new List.from (dart:core-patch/array_patch.dart:38:29)
#123    new List.of (dart:core-patch/array_patch.dart:68:17)
#124    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#125    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#126    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#127    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#128    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#129    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#130    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#131    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#132    new List.from (dart:core-patch/array_patch.dart:38:29)
#133    new List.of (dart:core-patch/array_patch.dart:68:17)
#134    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#135    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#136    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#137    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#138    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#139    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#140    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#141    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#142    new List.from (dart:core-patch/array_patch.dart:38:29)
#143    new List.of (dart:core-patch/array_patch.dart:68:17)
#144    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#145    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#146    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#147    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#148    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#149    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#150    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#151    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#152    new List.from (dart:core-patch/array_patch.dart:38:29)
#153    new List.of (dart:core-patch/array_patch.dart:68:17)
#154    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#155    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#156    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#157    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#158    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#159    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#160    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#161    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#162    new List.from (dart:core-patch/array_patch.dart:38:29)
#163    new List.of (dart:core-patch/array_patch.dart:68:17)
#164    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#165    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#166    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#167    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#168    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#169    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#170    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#171    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#172    new List.from (dart:core-patch/array_patch.dart:38:29)
#173    new List.of (dart:core-patch/array_patch.dart:68:17)
#174    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#175    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#176    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#177    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#178    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#179    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#180    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#181    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#182    new List.from (dart:core-patch/array_patch.dart:38:29)
#183    new List.of (dart:core-patch/array_patch.dart:68:17)
#184    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#185    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#186    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#187    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#188    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#189    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#190    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#191    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#192    new List.from (dart:core-patch/array_patch.dart:38:29)
#193    new List.of (dart:core-patch/array_patch.dart:68:17)
#194    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#195    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#196    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#197    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#198    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#199    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#200    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#201    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#202    new List.from (dart:core-patch/array_patch.dart:38:29)
#203    new List.of (dart:core-patch/array_patch.dart:68:17)
#204    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#205    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#206    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#207    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#208    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#209    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#210    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#211    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#212    new List.from (dart:core-patch/array_patch.dart:38:29)
#213    new List.of (dart:core-patch/array_patch.dart:68:17)
#214    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#215    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#216    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#217    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#218    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#219    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#220    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#221    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#222    new List.from (dart:core-patch/array_patch.dart:38:29)
#223    new List.of (dart:core-patch/array_patch.dart:68:17)
#224    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#225    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#226    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#227    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#228    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#229    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#230    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#231    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#232    new List.from (dart:core-patch/array_patch.dart:38:29)
#233    new List.of (dart:core-patch/array_patch.dart:68:17)
#234    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#235    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#236    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#237    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#238    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#239    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#240    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#241    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#242    new List.from (dart:core-patch/array_patch.dart:38:29)
#243    new List.of (dart:core-patch/array_patch.dart:68:17)
#244    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#245    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#246    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#247    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#248    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#249    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#250    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#251    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#252    new List.from (dart:core-patch/array_patch.dart:38:29)
#253    new List.of (dart:core-patch/array_patch.dart:68:17)
#254    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#255    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#256    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#257    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#258    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#259    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#260    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#261    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#262    new List.from (dart:core-patch/array_patch.dart:38:29)
#263    new List.of (dart:core-patch/array_patch.dart:68:17)
#264    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#265    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#266    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#267    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#268    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#269    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#270    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#271    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#272    new List.from (dart:core-patch/array_patch.dart:38:29)
#273    new List.of (dart:core-patch/array_patch.dart:68:17)
#274    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#275    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#276    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#277    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#278    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#279    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#280    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#281    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#282    new List.from (dart:core-patch/array_patch.dart:38:29)
#283    new List.of (dart:core-patch/array_patch.dart:68:17)
#284    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#285    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#286    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#287    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#288    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#289    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#290    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#291    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#292    new List.from (dart:core-patch/array_patch.dart:38:29)
#293    new List.of (dart:core-patch/array_patch.dart:68:17)
#294    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#295    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#296    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#297    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#298    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#299    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#300    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#301    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#302    new List.from (dart:core-patch/array_patch.dart:38:29)
#303    new List.of (dart:core-patch/array_patch.dart:68:17)
#304    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#305    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#306    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#307    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#308    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#309    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#310    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#311    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#312    new List.from (dart:core-patch/array_patch.dart:38:29)
#313    new List.of (dart:core-patch/array_patch.dart:68:17)
#314    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#315    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#316    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#317    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#318    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#319    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#320    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#321    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#322    new List.from (dart:core-patch/array_patch.dart:38:29)
#323    new List.of (dart:core-patch/array_patch.dart:68:17)
#324    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#325    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#326    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#327    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#328    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#329    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#330    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#331    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#332    new List.from (dart:core-patch/array_patch.dart:38:29)
#333    new List.of (dart:core-patch/array_patch.dart:68:17)
#334    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#335    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#336    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#337    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#338    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#339    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#340    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#341    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#342    new List.from (dart:core-patch/array_patch.dart:38:29)
#343    new List.of (dart:core-patch/array_patch.dart:68:17)
#344    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#345    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#346    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#347    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#348    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#349    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#350    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#351    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#352    new List.from (dart:core-patch/array_patch.dart:38:29)
#353    new List.of (dart:core-patch/array_patch.dart:68:17)
#354    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#355    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#356    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#357    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#358    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#359    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#360    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#361    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#362    new List.from (dart:core-patch/array_patch.dart:38:29)
#363    new List.of (dart:core-patch/array_patch.dart:68:17)
#364    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#365    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#366    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#367    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#368    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#369    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#370    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#371    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#372    new List.from (dart:core-patch/array_patch.dart:38:29)
#373    new List.of (dart:core-patch/array_patch.dart:68:17)
#374    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#375    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#376    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#377    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#378    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#379    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#380    MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#381    ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#382    new List.from (dart:core-patch/array_patch.dart:38:29)
#383    new List.of (dart:core-patch/array_patch.dart:68:17)
#384    ListIterable.toList (dart:_internal/iterable.dart:211:44)
#385    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#386    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1601:23)
#387    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#388    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4303:44)
#389    WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1440:18)
#390    WidgetInspectorService._getDetailsSubtree (package:flutter/src/widgets/widget_inspector.dart:1670:12)
#391    WidgetInspectorService.initServiceExtensions.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1125:21)
#392    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:549:32)
<asynchronous suspension>
#393    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)
#394    _runExtension (dart:developer-patch/developer.dart:84:23)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>
<details>
  <summary>Logs</summary>

```
Analyzing boxdecoration_hashcode_error...                               
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.104, on Mac OS X 10.15.3 19D76, locale en-RU)
    • Flutter version 1.20.0-8.0.pre.104 at /Users/iam/Projects/flutter
    • Framework revision 26a5f5c3d6 (2 hours ago), 2020-07-15 18:16:03 +0530
    • Engine revision 7b1515ed29
    • Dart version 2.9.0 (build 2.9.0-21.0.dev cfeb1d647a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/iam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (4 available)            
    • WAS LX1 (mobile) • 192.168.0.167:5555 • android-arm64  • Android 8.0.0 (API 26)
    • macOS (desktop)  • macos              • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server         • web-javascript • Flutter Tools
    • Chrome (web)     • chrome             • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by 2ZeroSix**
## Description

fix shadows hashCode and equality in BoxDecoration and ShapeDecoration

## Related Issues

closes #61549

## Tests

I added the following tests:
- `Decoration equality`
- `ShapeDecoration equality`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by 2ZeroSix** [comment]
Probably this should be cherrypicked into stable, as this often makes devtools unusable if you add decorations with non-null shadows array in ThemeData?

File: packages/flutter/test/painting/decoration_test.dart [hunk 1]
```diff
@@ -126,6 +126,17 @@ void main() {
     expect(c.color, equals(b.color));
   });
 
+  test('Decoration equality', () {
+    // ignore: prefer_const_constructors, prefer_const_literals_to_create_immutables
+    final BoxDecoration a = BoxDecoration(color: Color(0xFFFFFFFF), boxShadow: <BoxShadow>[BoxShadow()]);
```
Comment (2ZeroSix) [inline packages/flutter/test/painting/decoration_test.dart:131]: I forced non-const constructors here because I'm not sure if `operator ==` is called on equal const objects. Am I wrong?

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Note: this will land whenever the tree is green, thank you for the fix @2ZeroSix
