### PR TITLE
[iOS] Infer autocorrect value from autofillHints

### LINKED ISSUE #134723: Password bar in the keyboard is flashing when using `TextField` with `AutofillHints.password` on iOS 17
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use an iOS 17 device
2. Add a `TextField` with `AutofillHints.password`
3. Start typing

### Expected results

No flashing.

### Actual results

The password bar of the keyboard flashes but sometimes also the `TextField` (see video).

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            autofillHints: [AutofillHints.password],
          ),
        ),
      ),
    ),
  );
}
```

https://github.com/nilsreichardt/flutter-ios17-textfield-bug

### Screenshots or Video

https://github.com/flutter/flutter/assets/24459435/4f872d72-93ae-459c-ab7b-b0f71798505e

### Logs

<details><summary>Logs</summary>

```console
2023-09-14 13:44:46.470430+0200 Runner[1447:88815] Metal API Validation Enabled
2023-09-14 13:44:46.567930+0200 Runner[1447:88815] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
2023-09-14 13:44:46.680337+0200 Runner[1447:89203] flutter: The Dart VM service is listening on http://127.0.0.1:62669/HKQ_5uMac8k=/
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.82.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

### Additional context

* Used iPhone 13 with iOS 17.0
* Appears with Flutter v3.13.4 (latest stable version) and Flutter v3.14.0-14.0.pre.290 (latest master version)

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/134723

If autofillHints contains password-related hints, set autocorrect to `false`.

https://github.com/user-attachments/assets/aeb95f74-cabc-40ff-8829-c49bce466a6d

I checked the behaviour in UIKit and it is necessary to set correction and spell check to `No` if username or password is set to "Content Type". The following video shows the combination of `TextField` and option in UIKit.

https://github.com/user-attachments/assets/6c442a87-042a-4b34-b88f-7a438fefdbb3

code: https://github.com/koji-1009/pm_behavior_test/tree/native

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by jmagman** [comment]
@LongCatIsLooong says this should probably be handled on the framework side, which already has heuristics for this.

**Comment by koji-1009** [comment]
Thanks for the comment.
I have updated the PR to fix it in the framework, not the engine.

**Review by LongCatIsLooong — COMMENTED** [review]
Thanks for the PR and the attached video, this is amazing!

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -3747,6 +3747,84 @@ void main() {
...
+              focusNode: focusNode,
+              style: textStyle,
+              cursorColor: cursorColor,
+              autofillHints: const <String>[AutofillHints.newPassword],
+            ),
+          ),
+        ),
+      );
+
+      EditableText editableText = tester.firstWidget(find.byType(EditableText));
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/editable_text_test.dart:3822]: missing `final`

File: packages/flutter/lib/src/cupertino/search_field.dart [hunk 2]
```diff
@@ -274,7 +274,9 @@ class CupertinoSearchTextField extends StatefulWidget {
   /// {@macro flutter.material.textfield.onTap}
   final VoidCallback? onTap;
 
-  /// {@macro flutter.widgets.editableText.autocorrect}
+  /// Whether to enable autocorrection.
+  ///
+  /// Defaults to true.
```
Comment (koji-1009) [inline packages/flutter/lib/src/cupertino/search_field.dart:279]: CupertinoSearchTextField does not have autofillHints, so default is always true.

File: packages/flutter/lib/src/material/search.dart [hunk 3]
```diff
@@ -370,7 +370,9 @@ abstract class SearchDelegate<T> {
   /// Defaults to the default value specified in [TextField].
   final TextInputType? keyboardType;
 
-  /// {@macro flutter.widgets.editableText.autocorrect}
+  /// Whether to enable autocorrection.
+  ///
+  /// Defaults to true.
```
Comment (koji-1009) [inline packages/flutter/lib/src/material/search.dart:375]: SearchDelegate does not have autofillHints, so default is always true.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 1 above)
Comment (koji-1009) [reply packages/flutter/test/widgets/editable_text_test.dart]: Sorry, I fixed. [4e02e4b](https://github.com/flutter/flutter/pull/165637/commits/4e02e4bb65cad9220e2b6115de45c5b3ace141d1)

File: packages/flutter/lib/src/material/search.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/search.dart:375]: Yeah makes sense that it's less likely that someone wants to autofill a search field

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by koji-1009** [comment]
Thanks for the review!

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -826,7 +826,7 @@ class EditableText extends StatefulWidget {
     this.readOnly = false,
     this.obscuringCharacter = '•',
     this.obscureText = false,
-    this.autocorrect = true,
+    bool? autocorrect,
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart:829]: Do we need to update this line as well?

https://github.com/flutter/flutter/blob/c29c67ae4ce4ac5ac217e59dc09c20b967195b1f/packages/flutter/lib/src/widgets/editable_text.dart#L2296

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -1050,7 +1051,7 @@ class EditableText extends StatefulWidget {
   /// {@template flutter.widgets.editableText.autocorrect}
   /// Whether to enable autocorrection.
   ///
-  /// Defaults to true.
+  /// Defaults to true, false on iOS if [autofillHints] contains password related hints.
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/editable_text.dart:1054]: What do you think of this? I don't feel strongly, feel free to keep as-is.

```suggestion
  /// False on iOS if [autofillHints] contains password-related hints, otherwise true.
```

**Review by loic-sharma — APPROVED** [review]
Looks great, thanks for the excellent contribution! :)

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart:829]: Thanks for pointing that out! I think `null` is the right choice, as well as `keyboardType`.

https://github.com/flutter/flutter/blob/c29c67ae4ce4ac5ac217e59dc09c20b967195b1f/packages/flutter/lib/src/widgets/editable_text.dart#L2324

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Thank you!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart:829]: [90e9a5c](https://github.com/flutter/flutter/pull/165637/commits/90e9a5c059c6ba0e266e5763a058ca1f19b1a754)

**Comment by loic-sharma** [comment]
Thanks for the update!
