### PR TITLE
SearchBar should listen to changes to the SearchController and update suggestions on change

### LINKED ISSUE #132161: SearchAnchor.bar setting controller.value doesn't trigger suggestionsBuilder rebuild
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code sample.
2. Open search view by clicking on the bar.
3. Click on the arrow of a suggestions to update controller value.

### Expected results

`suggestionsBuilder` should now rebuild as controller value was updated.

### Actual results

`suggestionsBuilder` doesn't rebuild and forces user to make additional updates to controller value with keyboard, submit the new controller value by clicking return on the keyboard, or open and close the search view if you run Flutter Web (official example have the exact same flaw: https://api.flutter.dev/flutter/material/SearchAnchor/SearchAnchor.bar.html).

For an illustration of a working example try Chrome or YouTube or practically any other app with search suggestions implemented. When you fill the text field from a suggestion in any of these apps the suggestion view will update accordingly.

As setState won't trigger a rebuild, the only way around this is to stop using the widget as it was intended and implement your own state management solution around this, e.g. using a single widget that controls a deeper array of widgets based on state changes. And I really don't think this was the idea when designing this from the beginning.

Either make `suggestionsBuilder` rebuild on controller value changes or give developers some sort of manual control over rebuilds. As it stands, developers have no control over it whatsoever, which seems very weird and I cannot believe it being a design choice.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final data = ['foo', 'bar', 'baz'];
final history = ['fo', 'az'];

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
        ),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: SafeArea(
          child: SearchAnchor.bar(
            suggestionsBuilder: (_, controller) {
              if (controller.text.isNotEmpty) {
                final results = [
                  for (var dataEntity in data)
                    if (dataEntity.contains(controller.text)) dataEntity,
                ];

                if (results.isNotEmpty) {
                  return [
                    for (var result in results)
                      ListTile(
                        title: Text(
                          result,
                        ),
                      ),
                  ];
                }
              }

              return [
                for (var historyEntry in history)
                  ListTile(
                    title: Text(
                      historyEntry,
                    ),
                    trailing: IconButton(
                      onPressed: () => controller.text = historyEntry,
                      icon: Transform.flip(
                        flipX: true,
                        child: const Icon(
                          Icons.arrow_outward,
                        ),
                      ),
                    ),
                  ),
              ];
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[searchanchor_issue.webm](https://github.com/flutter/flutter/assets/8590720/f921457a-4935-4bfb-afd1-0d4199932ebf)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.13.0-0.2.pre on channel beta at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac71592bc6 (3 weeks ago), 2023-07-18 14:53:57 -0600
    • Engine revision e14db68a86
    • Dart version 3.1.0 (build 3.1.0-262.2.beta)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bryanoli**
This PR is adding a listener to the `SearchController`, so that the `suggestionBuilder` can be updated when the `SearchController` changes. 

Another method we can possibly do is  have an update method on `SearchController`, so that the user can manually update the suggestions instead of us doing it automatically.

Fixes #132161

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 1]
```diff
@@ -682,11 +682,19 @@ class _ViewContentState extends State<_ViewContent> {
     super.initState();
     _viewRect = widget.viewRect;
     _controller = widget.searchController;
+    _controller.addListener(updateSuggestions);
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/search_anchor.dart:685]: I think the `updateSuggestions` call can be removed from `defaultTrailing` and `defaultLeading` in the `onPressed` since this change will call `updateSuggestions` when the controller changes its value.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM with one comment. Thanks for the contribution @bryanoli! I think I'm leaning towards the method used in this PR vs an `update` method added to `SearchController`. I think its reasonable to have this functionality by default, and internal `defaultTrailing` and `defaultLeading` already `updateSuggestions` by default.  

cc @QuncCccccc for any insights/thoughts on this issue.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks a lot for your contribution:)
