### PR TITLE
Provide a default IconTheme in CupertinoTheme

### LINKED ISSUE #29099: Icon widget should appear white applying CupertinoTheme with dark brightness
- SDK version: Channel beta, v1.2.1.
- How to reproduce it:
1) Create a new CupertinoApp
2) Apply CupertinoTheme with dark brightness
3) Insert an Icon somewhere in the tree

Example:

```dart
class FCEApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'FCE App',
      theme: CupertinoThemeData(
        brightness: Brightness.dark,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              const Icon(CupertinoIcons.profile_circled, size: 36),
              const SizedBox(width: 12),
              Expanded(
                child: Text('John Doe'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Result:

Screen Shot 2019-03-09 at 16 25 21

=> The txt color becomes white but the icon's color remains black and that seems inconsistent.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

- Inserted an `IconTheme` widget under `CupertinoTheme` to provide a default icon color when using `CupertinoTheme`.
- Changed `CupertinoTheme` to a `StatelessWidget`, to match the implementation of `Theme`
- Changed the nesting order of `Theme`'s sub widgets, to let `Theme.iconTheme` take precedence, so that `Theme`'s behavior is kept as is.

## Related Issues

fixes #29099

## Tests

I added the following tests:

- CupertinoTheme has default IconThemeData, which is derived from the theme's primary color
- IconTheme.of creates a dependency on iconTheme 
- CupertinoTheme's IconTheme is ignored when using a material theme

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/theme.dart [hunk 1]
```diff
@@ -24,38 +24,69 @@ const Color _kDefaultBarDarkBackgroundColor = Color(0xB7212121);
...
   }
+
+  /// The widget below this widget in the tree.
+  ///
+  /// {@macro flutter.widgets.child}
+  final Widget child;
+
+  @override
+  Widget build(BuildContext context) {
+    final IconThemeData iconTheme = IconTheme.of(context) ?? const IconThemeData();
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/theme.dart]: Seems like Material doesn't bring anything from the tree above it. I think it makes sense here too where if you insert a *App into the tree, everything's fresh.

File: packages/flutter/test/cupertino/theme_test.dart [hunk 2]
```diff
@@ -123,4 +135,24 @@ void main() {
       expect(theme.scaffoldBackgroundColor, CupertinoColors.black);
     },
   );
+
+  testWidgets('Theme has default IconThemeData, which is derived from the theme\'s primary color', (WidgetTester tester) async {
```
Comment (xster) [inline packages/flutter/test/cupertino/theme_test.dart]: nit, don't escape stuff. If there's single quotes in the text, just use double quotes for the string literal.

File: packages/flutter/test/cupertino/theme_test.dart [hunk 3]
```diff
@@ -123,4 +135,24 @@ void main() {
...
+  testWidgets('IconTheme.of creates a dependency on iconTheme', (WidgetTester tester) async {
+      IconThemeData iconTheme = await testIconTheme(tester, const CupertinoThemeData(primaryColor: CupertinoColors.destructiveRed));
+
+      expect(buildCount, 1);
+      expect(iconTheme.color, CupertinoColors.destructiveRed);
+
+      iconTheme = await testIconTheme(tester, const CupertinoThemeData(primaryColor: CupertinoColors.activeOrange));
+      expect(buildCount, 2);
+      expect(iconTheme.color, CupertinoColors.activeOrange);
+  });
```
Comment (xster) [inline packages/flutter/test/cupertino/theme_test.dart]: Add a test in material to check that given a material theme with color A and a cupertino override theme with color B, the icons under that material theme still has color A.

**Review by xster — COMMENTED** [review]
LGTM

**Comment by xster** [comment]
LGTM
