### PR TITLE
Ensure Xcode project is setup to start debugger

### LINKED ISSUE #136197: Xcode 15 launch failure with iOS 17 physical device in debug mode "Could not call ptrace(PT_TRACE_ME): Operation not permitted. Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode."
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- flutter channel master
- flutter upgrade
- ios -> pod install --repo-update
- flutter clean
- flutter pub get
- flutter run (--debug)

### Actual results

**After updating iOS 17 and xCode 15, I can’t launch debug mode on a physical Apple device.**

- flutter channel master (Flutter 3.16.0-6.0.pre.45 • channel master)
- flutter upgrade
- ios -> pod install --repo-update
- flutter clean
- flutter pub get
- flutter run (--debug)

and im running debug from vs code command-line and xcode

image
image
image
image

and sometime i got this notification
image

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

nikitamihajlov@Mac-mini-Nikita ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.16.0-6.0.pre.45, on macOS 14.0 23A344 darwin-arm64)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
Some users have their Xcode settings set to not debug (see example here https://github.com/flutter/flutter/issues/136197#issuecomment-1766834195). This will cause the [engine check for a debugger](https://github.com/flutter/engine/blob/22ce5c6a45e2898b4ce348c514b5fa42ca25bc88/runtime/ptrace_check.cc#L56-L71) to fail, which will cause an error and cause the app to crash.

This PR parses the scheme file to ensure the scheme is set to start a debugger and warn the user if it's not.

Fixes https://github.com/flutter/flutter/issues/136197.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart [hunk 1]
```diff
@@ -411,6 +413,49 @@ class XcodeDebug {
...
   }
+
+  /// Ensure the Xcode project is set up to launch an LLDB debugger. If these
+  /// settings are not set, the launch will fail with a "Cannot create a
+  /// FlutterEngine instance in debug mode without Flutter tooling or Xcode."
+  /// error message. These settings should be correct by default, but some users
+  /// reported them not being so after upgrading to Xcode 15.
+  void ensureXcodeDebuggerLaunchAction(File schemeFile) {
+    if (!schemeFile.existsSync()) {
+      _logger.printError('Failed to find ${schemeFile.path}');
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/ios/xcode_debug.dart:424]: I've purposely set this error and some of the ones below to be non-breaking and just print out the error. It only throws if it successfully finds the scheme file and parse it and finds the settings are incorrect.

Reason for this is I plan to CP this into stable and although I'm pretty confident that none of these should error, there may be cases I'm unaware of. And by default, most projects should have these settings be correct. I don't want to prevent a valid project from running.

Let me know if you think I'm being too cautious 😅

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart [hunk 2]
```diff
@@ -411,6 +413,49 @@ class XcodeDebug {
       verboseLogging: verboseLogging,
     );
   }
+
+  /// Ensure the Xcode project is set up to launch an LLDB debugger. If these
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/xcode_debug.dart:417]: does this check only need to be done when we're initiating debugging via the Xcode GUI?

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/xcode_debug.dart:424]: do you plan to mark it a failure AFTER the CP? or would you like it to be printError indefinitely?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/xcode_debug.dart:424]: in terms of cherry-picking, I would say this is an appropriate level of caution :)

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcode_debug.dart:417]: Yes. Also, only need to be done for `BuildableIOSApp` (so not prebuilt) since prebuilt uses a Xcode project we generate on the fly.

**Comment by vashworth** [comment]
@eliasyishak since @christopherfujino is OOO, could you review?

**Review by eliasyishak — APPROVED** [review]
LGTM!
