### PR TITLE
Tweaked TabBar to provide uniform padding to all tabs in cases where only few tabs contain both icon and text

### LINKED ISSUE #80112: [TabBar] Incorrect active region having `Tab`s with/without icon or text and having unequal height
## Steps to Reproduce
<details>
  <summary>Reproducible code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final List<Widget> pages = [
    PageOne(),
    PageTwo(),
    PageThree(),
  ];

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late final _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Region outside the overlay isn\'t interactive'),
        bottom: TabBar(
          overlayColor: MaterialStateColor.resolveWith((states) => (Colors.deepPurple)),
          tabs: [
            Tab(icon: Icon(Icons.add),text: 'Icon & text'),
            Tab(text: 'Text'),
            Tab(icon: Icon(Icons.undo)),
          ],
          controller: _tabController,
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: widget.pages,
      ),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Page one'),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Page two'),
    );
  }
}

class PageThree extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Page three'),
    );
  }
}

```

</details>

Dartpad demo: https://dartpad.dev/c7bcd2cf9bc1aa450def9d804db4f3af?null_safety=true

**Actual results:** 
tabbar_bug

**Expected results:**
Tabs should have uniform active region regardless of their configuration; preferably the maximum height among the tabs.

<details>
  <summary>Logs</summary>

```
$ flutter run -d linux -v
[ +122 ms] executing: uname -m
[  +66 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +12 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cf27be38a990d7f5a053167dcb8c876ff19e27cb
[   +2 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git tag --points-at cf27be38a990d7f5a053167dcb8c876ff19e27cb
[  +29 ms] Exit code 0 from: git tag --points-at cf27be38a990d7f5a053167dcb8c876ff19e27cb
[   +4 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git describe --match *.*.* --long --tags cf27be38a990d7f5a053167dcb8c876ff19e27cb
[  +82 ms] Exit code 0 from: git describe --match *.*.* --long --tags cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] 2.1.0-12.0.pre-555-gcf27be38a9
[  +13 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/anurag/.local/src/flutter_sdk_master/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +174 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +109 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] executing: /home/anurag/.local/src/android_sdk/platform-tools/adb devices -l
[  +37 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +138 ms] executing: /home/anurag/.local/src/android_sdk/platform-tools/adb devices -l
[  +30 ms] Skipping pub get: version match.
[ +243 ms] Generating /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +151 ms] Initializing file store
[  +18 ms] Skipping target: gen_localizations
[  +13 ms] complete
[   +9 ms] Launching lib/main.dart on Linux in debug mode...
[  +10 ms] /home/anurag/.local/src/flutter_sdk_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/anurag/.local/src/flutter_sdk_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/anurag/.local/src/flutter_sdk_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.FUKQIO/flutter_tool.MUDPEX/app.dill --packages
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +53 ms] Building Linux application...
[  +49 ms] <- compile package:incorrect_tab_active_region/main.dart
[   +6 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux
[  +22 ms] List of devices attached
[   +6 ms] List of devices attached
[  +75 ms] -- Configuring done
[  +66 ms] -- Generating done
[+1566 ms] -- Build files have been written to: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug
[  +15 ms] executing: ninja -C build/linux/x64/debug install
[  +30 ms] ninja: Entering directory `build/linux/x64/debug'
[+28658 ms] [1/5] Generating /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +7 ms] [ +145 ms] executing: uname -m
[        ] [  +80 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +15 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] [   +1 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git tag --points-at cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] [  +25 ms] Exit code 0 from: git tag --points-at cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] [   +2 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git describe --match *.*.* --long --tags cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] [  +76 ms] Exit code 0 from: git describe --match *.*.* --long --tags cf27be38a990d7f5a053167dcb8c876ff19e27cb
[        ] [        ] 2.1.0-12.0.pre-555-gcf27be38a9
[        ] [  +18 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/anurag/.local/src/flutter_sdk_master/] git ls-remote --get-url origin
[        ] [   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +158 ms] executing: [/home/anurag/.local/src/flutter_sdk_master/] git rev-parse --abbrev-ref HEAD
[        ] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +170 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +43 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[        ] [  +65 ms] Skipping target: gen_localizations
[        ] [+3638 ms] Skipping target: unpack_linux
[        ] [ +819 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/lib/main.dart}
[   +6 ms] [  +17 ms] /home/anurag/.local/src/flutter_sdk_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/anurag/.local/src/flutter_sdk_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/anurag/.local/src/flutter_sdk_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/.dart_tool/package_config.json
--output-dill /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/.dart_tool/flutter_build/1a0783d076d847240c8dfd43812b1295/app.dill --depfile
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/.dart_tool/flutter_build/1a0783d076d847240c8dfd43812b1295/kernel_snapshot.d package:incorrect_tab_active_region/main.dart
[   +3 ms] [+18977 ms] kernel_snapshot: Complete
[        ] [+1627 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/.dart_tool/flutter_build/1a0783d076d847240c8dfd43812b1295/app.dill}
[   +1 ms] [ +848 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +546 ms] Persisting file store
[        ] [  +14 ms] Done persisting file store
[        ] [  +11 ms] build succeeded.
[        ] [  +16 ms] "flutter assemble" took 26,856ms.
[        ] [   +7 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[+1299 ms] [2/5] Building CXX object CMakeFiles/incorrect_tab_active_region.dir/flutter/generated_plugin_registrant.cc.o
[ +143 ms] [3/5] Building CXX object CMakeFiles/incorrect_tab_active_region.dir/my_application.cc.o
[ +520 ms] [4/5] Linking CXX executable intermediates_do_not_run/incorrect_tab_active_region
[   +1 ms] [4/5] Install the project...
[  +33 ms] -- Install configuration: "Debug"
[  +97 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/incorrect_tab_active_region
[  +19 ms] -- Set runtime path of "/mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/incorrect_tab_active_region" to "$ORIGIN/lib"
[  +18 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/icudtl.dat
[  +68 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[+3599 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets
[   +3 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[   +7 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[   +9 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[   +3 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[  +42 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[ +789 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[  +27 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/packages
[   +4 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[   +5 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[   +5 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +17 ms] -- Installing: /mnt/D/AndroidStudioProjects/incorrect_tab_active_region/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +31 ms] Building Linux application... (completed in 37.3s)
[  +84 ms] (incorrect_tab_active_region:18354): Gtk-WARNING **: 17:04:26.040: Locale not supported by C library.
[        ]      Using the fallback 'C' locale.
[ +757 ms] Observatory URL on device: http://127.0.0.1:36581/GhbCwLV_Tqs=/
[  +16 ms] Caching compiled dill
[ +505 ms] Connecting to service protocol: http://127.0.0.1:36581/GhbCwLV_Tqs=/
[ +322 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:36581/GhbCwLV_Tqs=/.
[ +119 ms] DDS is listening at http://127.0.0.1:38033/3RWGyGbtpQg=/.
[ +107 ms] Successfully connected to service protocol: http://127.0.0.1:36581/GhbCwLV_Tqs=/
[  +45 ms] DevFS: Creating new filesystem on the device (null)
[  +28 ms] DevFS: Created new filesystem on the device (file:///tmp/incorrect_tab_active_regionFQXJDX/incorrect_tab_active_region/)
[   +4 ms] Updating assets
[ +153 ms] Syncing files to device Linux...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:incorrect_tab_active_region/main.dart eaf159fe-3028-4425-b15a-43d0515c61b1
[        ] <- eaf159fe-3028-4425-b15a-43d0515c61b1
[ +178 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device Linux... (completed in 186ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[  +32 ms] Connected to _flutterView/0x559343648220.
[   +6 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:38033/3RWGyGbtpQg=/
[+1386 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A38033%2F3RWGyGbtpQg%3D%2F
[+6144 ms] DevFS: Deleting filesystem on the device (file:///tmp/incorrect_tab_active_regionFQXJDX/incorrect_tab_active_region/)
[  +14 ms] DevFS: Deleted filesystem on the device (file:///tmp/incorrect_tab_active_regionFQXJDX/incorrect_tab_active_region/)
[ +153 ms] Service protocol connection closed.
[        ] Application finished.
[   +7 ms] "flutter run" took 48,251ms.
[   +7 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +3 ms] exiting with code 0
```
</details>

<details>
  <summary>flutter analyze</summary>

```
Analyzing incorrect_tab_active_region...                                
No issues found! (ran in 3.1s)
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.555, on Linux, locale en_IN)
    • Flutter version 2.1.0-13.0.pre.555 at /home/anurag/.local/src/flutter_sdk_master
    • Framework revision cf27be38a9 (8 hours ago), 2021-04-08 21:04:02 -0700
    • Engine revision a9f4883dc8
    • Dart version 2.13.0 (build 2.13.0-219.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/anurag/.local/src/android_sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/anurag/.local/src/android_sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 55.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.90 Arch Linux

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by chinmoy12c**
Tabs should have uniform active regions regardless of their configuration.

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes: #80112 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -901,6 +901,22 @@ class TabBar extends StatefulWidget implements PreferredSizeWidget {
...
   }
 
+  /// Returns whether the [TabBar] contains a [Tab] with both text and icon.
+  ///
+  /// [TabBar] uses this to give uniform padding to all tabs in cases where
+  /// there are some tabs with both text and icon and some which contain only
+  /// text or icon.
+  bool get tabHasTextAndIcon {
+    for (final Widget item in tabs) {
+      if (item is Tab) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/tabs.dart:911]: This hard codes specific knowledge of another widget into TabBar, which means the TabBar will behave differently depending on its tabs.  
This is something that is discussed in the style guide here: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo/b91c3c62d96814e8fbf7119be65ddeb5a9746f82#avoid-interleaving-multiple-concepts-together

Comment (chinmoy12c) [reply packages/flutter/lib/src/material/tabs.dart:911]: Hmm, this is true. Although, preferredSize seems to use the same kind of code here: https://github.com/flutter/flutter/blob/f789acae4191f585f799be3c4542b16d089224a8/packages/flutter/lib/src/material/tabs.dart#L893 So I figured it would be okay to treat tabs differently to handle tabs in this special case? :thinking:

Also, this irregularity arises because the `Tabs` are treated(sized) differently within a `TabBar` in the first place.
https://github.com/flutter/flutter/blob/f789acae4191f585f799be3c4542b16d089224a8/packages/flutter/lib/src/material/tabs.dart#L106

**Review by Piinks — COMMENTED** [review]
It looks like in the linked bug there is a solution to the problem by sizing the Tabs such that they are uniform, I am not sure if that may be a better solution than pressing the style guide further here - but let me see if I can get some more opinions on this.

Also, I did notice [you pointed out in the bug that Material Design has an opinion about this](https://github.com/flutter/flutter/issues/80112#issuecomment-817326249), so maybe this is intentional.

**Comment by chinmoy12c** [comment]
> It looks like in the linked bug there is a solution to the problem by sizing the Tabs such that they are uniform, I am not sure if that may be a better solution than pressing the style guide further here - but let me see if I can get some more opinions on this.
> 
> Also, I did notice [you pointed out in the bug that Material Design has an opinion about this](https://github.com/flutter/flutter/issues/80112#issuecomment-817326249), so maybe this is intentional.

Actually I did try sizing the tabs itself earlier but that proved to be cumbersome. The problem is that for the tabs to resize themselves they would have to know:
1) whether they are child of a TabBar(which is not always the case)
2) Whether there are only few tabs in the parent TabBar with both icon and text.

Both of these requires a child widget to know the properties of the parent, which I guess is not possible?🤔

**Review by Piinks — COMMENTED** [review]
Chatted with @Hixie about this, available here: https://discord.com/channels/608014603317936148/608021234516754444/832710552404230204

> (it's ok to check is PreferredSizeWidget since that's an interface)

Per that discussion we should see about changing the TabBar.preferredSize to actually check for the PreferredSize widget, and wrap the Tab in one. 

I have filed https://github.com/flutter/flutter/issues/80596 for tracking that. 
We should investigate using a similar solution here as well since TabBar shouldn't have knowledge of Tabs.

**Comment by chinmoy12c** [comment]
> Chatted with @Hixie about this, available here: https://discord.com/channels/608014603317936148/608021234516754444/832710552404230204
> 
> > (it's ok to check is PreferredSizeWidget since that's an interface)
> 
> Per that discussion we should see about changing the TabBar.preferredSize to actually check for the PreferredSize widget, and wrap the Tab in one.
> 
> I have filed #80596 for tracking that.
> We should investigate using a similar solution here as well since TabBar shouldn't have knowledge of Tabs.

Hey @Piinks, I've updated the PR since #80792 has landed. Please have a look :).

**Review by Piinks — COMMENTED** [review]
This is great, thank you for embracing the yak shave! Only one nit below.

File: packages/flutter/lib/src/material/tabs.dart [hunk 2]
```diff
@@ -1168,19 +1183,33 @@ class _TabBarState extends State<TabBar> {
...
-              child: widget.tabs[i],
-            ),
+    final List<Widget> wrappedTabs = List<Widget>.generate(widget.tabs.length, (int index) {
+      const double verticalAdjustment = (_kTextAndIconTabHeight - _kTabHeight)/2.0;
+      EdgeInsetsGeometry? adjustedPadding;
+
+      if (widget.tabs[index] is PreferredSizeWidget) {
+        final PreferredSizeWidget tab = widget.tabs[index] as PreferredSizeWidget;
+        if (widget.tabHasTextAndIcon && tab.preferredSize.height == _kTabHeight) {
+          if (widget.labelPadding != null || tabBarTheme.labelPadding != null) {
```
[the remark this answers is not in the document]
Comment (chinmoy12c) [reply packages/flutter/lib/src/material/tabs.dart:1197]: Done :)

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

🎉
