### PR TITLE
Fix DropdownMenu default width does not take label into account

### LINKED ISSUE #136678: DropdownMenu default width does not take label into account.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

<details>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [DropdownMenu]s. The first dropdown menu has an outlined border.

void main() => runApp(const DropdownMenuExample());

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  ColorLabel? selectedColor;

  @override
  Widget build(BuildContext context) {
    final List<DropdownMenuEntry<ColorLabel>> colorEntries =
        <DropdownMenuEntry<ColorLabel>>[];
    for (final ColorLabel color in ColorLabel.values) {
      colorEntries.add(
        DropdownMenuEntry<ColorLabel>(
            value: color, label: color.label, enabled: color.label != 'Grey'),
      );
    }

    final List<DropdownMenuEntry<IconLabel>> iconEntries =
        <DropdownMenuEntry<IconLabel>>[];
    for (final IconLabel icon in IconLabel.values) {
      iconEntries
          .add(DropdownMenuEntry<IconLabel>(value: icon, label: icon.label));
    }

    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownMenu<ColorLabel>(
                      controller: colorController,
                      label: const Text('A long label'),
                      dropdownMenuEntries: colorEntries,
                      onSelected: (ColorLabel? color) {
                        setState(() {
                          selectedColor = color;
                        });
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Yellow', Colors.yellow),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

enum IconLabel {
  smile('Smile', Icons.sentiment_satisfied_outlined),
  cloud(
    'Cloud',
    Icons.cloud_outlined,
  ),
  brush('Brush', Icons.brush_outlined),
  heart('Heart', Icons.favorite);

  const IconLabel(this.label, this.icon);
  final String label;
  final IconData icon;
}

```

</details>

run the app and the label gets split into two lines which is by default a bit ugly.
image

Not sure if this is by design or should the default width calculate by not only the longest item but also take label into account

### Actual results

The dropdown should have the same length as the label.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `DropdownMenu`  default width when a long label is provided.

Before:

The width is based on the longest menu item (which can be smaller than the label):

image

After:

The width also depends on the label width when it is longer than the menu items.

image

## Related Issue

Fixes [DropdownMenu default width does not take label into account](https://github.com/flutter/flutter/issues/136678)

## Tests

Adds 2 tests.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -960,7 +1019,7 @@ void main() {
     // Default text field (without leading icon).
     await tester.pumpWidget(buildTest(themeData, menuChildren, label: const Text('label')));
 
-    final Finder label = find.text('label');
+    final Finder label = find.text('label').first;
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:1022]: Why do we add `.first` here? Did we add another label?

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -983,7 +1042,7 @@ void main() {
 
     final Finder leadingIcon = find.widgetWithIcon(SizedBox, Icons.search).last;
     final double iconWidth = tester.getSize(leadingIcon).width;
-    final Finder updatedLabel = find.text('label');
+    final Finder updatedLabel = find.text('label').first;
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:1045]: Same here and below:)

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart:1022]: Yes this PR duplicates the label for width computation.
It adds it to `DropdownMenuBody` children list, similarly to the menu items, the text field and the leading/trailing buttons which are already duplicated.
It might require updating existing tests (in Google testing for instance).

Comment (QuncCccccc) [reply packages/flutter/test/material/dropdown_menu_test.dart:1022]: Ah! That makes sense. Thanks for the explanation! I hope Google testing won't break, but let's see=)

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -716,6 +716,65 @@ void main() {
...
+
+    final double width = tester.getSize(find.byType(DropdownMenu<int>)).width;
+    const double menuEntryPadding = 24.0; // See _kDefaultHorizontalPadding.
+    const double leadingWidth = 16.0;
+    const double trailingWidth = 56.0;
+
+    expect(width, entryLabelWidth + leadingWidth + trailingWidth + menuEntryPadding);
+  });
+
+  // Regression test for https://github.com/flutter/flutter/issues/136678.
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:746]: I personally think this change is just a new feature to respect the label width. So probably we don't need this comment? but it's just a nit:)

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks for the improvement:) Let's see whether there's any luck on Google testing🤞

**Comment by bleroux** [comment]
@QuncCccccc Unfortunately some Google tests are failing, thanks in advance for checking how many tests are failing and if they can be updated.

**Comment by QuncCccccc** [comment]
There is a a11y test breaking in Google testing. Will fix it today. Thank you for your patience!

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 4]
```diff
@@ -1044,11 +1044,22 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
+                  // and leadingButton.
+                  //
+                  // See _RenderDropdownMenuBody layout logic.
                   children: <Widget>[
                     textField,
                     ..._initialMenu!.map(
                       (Widget item) => ExcludeFocus(excluding: !controller.isOpen, child: item),
                     ),
+                    if (widget.label != null)
+                      Padding(
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:1058]: Can we add `ExcludeSemantics` here? I think this can fix the failure.
