### PR TITLE
fix: `ExpansionTileTheme.shape` assignment in `ExpansionTile`

### LINKED ISSUE #129785: `shape` property from `ExpansionTileTheme` is not use
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the code snippet as it has 2 ExpansionTile

a. ExpansionTile 1 which takes `shape` from `ExpansionTileTheme`
b. ExpansionTile 2 where `shape` is passed directly

### Expected results

Both the `ExpansionTile` on expanded should have red outline.

### Actual results

ExpansionTile 1 border color is default color (should have taken shape from `ExpansionTileTheme`)
ExpansionTile 2 border color is red (which is correct)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ExpansionTile].

void main() => runApp(const ExpansionTileApp());

class ExpansionTileApp extends StatelessWidget {
  const ExpansionTileApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        appBar: AppBar(title: const Text('ExpansionTile Sample')),
        body: const ExpansionTileExample(),
      ),
    );
  }
}

class ExpansionTileExample extends StatelessWidget {
  const ExpansionTileExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        ExpansionTileTheme(
          data: ExpansionTileThemeData(
            shape: Border.all(color: Colors.red),
          ),
          child: const ExpansionTile(
            title: Text('ExpansionTile 1'),
            initiallyExpanded: true,
            children: <Widget>[
              ListTile(title: Text('This is tile number 1')),
            ],
          ),
        ),
        ExpansionTile(
          title: const Text('ExpansionTile 2'),
          shape: Border.all(color: Colors.red),
          initiallyExpanded: true,
          children: const <Widget>[
            ListTile(title: Text('This is tile number 2')),
          ],
        ),
      ],
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
image
</details>

### Logs

_No response_

### Flutter Doctor output

Ran it on dartpad.dev

### PR DESCRIPTION
**Pull request by SirusCodes**
The ExpansionTile was not following `shape` from ExpansionTileTheme as it was assigning wrong parameter to the tween.

fixes #129785

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
@SirusCodes 
Can you please link an issue this fixes? If doesn't exist please file an issue.
Also looks like there are some failures in this PR.

**Comment by SirusCodes** [comment]
> Can you please link an issue this fixes? If doesn't exist please file an issue.

There were no issues related to this when I opened this PR but I guess I can file an issue for it if you say so.

> Also looks like there are some failures in this PR.

There is a test failing which was also flawed (I guess) because of the wrong assignment and some extra space character which I mistakenly added.

**Comment by TahaTesser** [comment]
> There were no issues related to this when I opened this PR but I guess I can file an issue for it if you say so.

Please do.

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for fixing this. 

Since this is a theme value issue, I took a quick look at the expansion tile theme tests.

It looks like both `ExpansionTileTheme - expanded` & `ExpansionTileTheme - collapsed` are testing the shape from the decoration but it's the same shape in both tests. This is the reason this issue wasn't caught earlier.

https://github.com/flutter/flutter/blob/7b8595629b11113516a8f63a80a31064eb03c723/packages/flutter/test/material/expansion_tile_theme_test.dart#L293

https://github.com/flutter/flutter/blob/7b8595629b11113516a8f63a80a31064eb03c723/packages/flutter/test/material/expansion_tile_theme_test.dart#L211


and you updated the theme tests, it is great.

File: packages/flutter/test/material/expansion_tile_test.dart [hunk 1]
```diff
@@ -638,6 +638,55 @@ void main() {
     expect(expandedContainerDecoration.shape, shape);
   });
 
+  testWidgets('ExpansionTile shape from ExpansionTileTheme', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/expansion_tile_test.dart:641]: Is your goal here to test the local `ExpansionTileTheme` for the shape? 

If yes, this can should be the same as other expanded and collapsed tests in the theme class but using a local theme, which also tests other theme values.

Theme test doesn't belong in `expansion_tile_test.dart` but theme class.

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/expansion_tile_test.dart (hunk 1 above)
Comment (SirusCodes) [reply packages/flutter/test/material/expansion_tile_test.dart:641]: Ohh yeah.. I will move it to `expansion_tile_test.dart`

**Comment by SirusCodes** [comment]
Hey @TahaTesser reverted the commit that added the test to `expansion_tile_test.dart` as it was not helping and we don't need to add any test in `expansion_tile_theme_test.dart` as it already has test for `shape` which I fixed.

**Review by TahaTesser — APPROVED** [review]
LGTM

**Comment by TahaTesser** [comment]
This will need a second review from @HansMuller before we land.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by SirusCodes** [comment]
@HansMuller @TahaTesser I cannot understand what is failing in these?

**Comment by HansMuller** [comment]
The customer tests that were failing in the analyzer don't appear to have anything to do with your changes. I've resync'd your PR, hopefully the problem will disappear.

```
| Analyzing flutter_reactive_ble...
|
|   error • The named parameter 'connectable' is required, but there's no corresponding argument • test/device_connector_test.dart:96:32 • missing_required_argument
|   error • The named parameter 'connectable' is required, but there's no corresponding argument • test/device_scanner_test.dart:24:18 • missing_required_argument
|   error • The named parameter 'connectable' is required, but there's no corresponding argument • test/device_scanner_test.dart:32:18 • missing_required_argument
|   error • The named parameter 'connectable' is required, but there's no corresponding argument • test/reactive_ble_test.dart:234:22 • missing_required_argument
|
| 4 issues found. (ran in 3.6s)
ERROR: One or more tests from flutter_reactive_ble failed.
```

**Comment by SirusCodes** [comment]
@HansMuller @TahaTesser this test is taking unusually very long to run👀

**Comment by SirusCodes** [comment]
@TahaTesser can you merge it 😅👀
