### PR TITLE
Fix infinite loop in CupertinoSliverNavigationBar collapse animation by adding bounds check for target scroll position

### LINKED ISSUE #164458: CupertinoSliverNavigationBar's  expanded/collapsed animation can get stuck in an infinite loop
### Steps to reproduce

1. Create a Cupertino app with a `CupertinoSliverNavigationBar` where the scrollable content extends past the viewport only if `CupertinoSliverNavigationBar` is expanded, but fits within the viewport if `CupertinoSliverNavigationBar` is collapsed.

2. Scroll down to the bottom.

### Expected results

The `CupertinoSliverNavigationBar` should collapse and stay collapsed.

### Actual results

The `CupertinoSliverNavigationBar` loops between its collapsed and expanded mode forever.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(
    CupertinoApp(
      home: CupertinoPageScaffold(
        child: CustomScrollView(
          slivers: [
            CupertinoSliverNavigationBar(
              largeTitle: Text('Hello World!'),
            ),
            SliverList.builder(
              // TODO: Edit the item count such that the list
              // extends past the viewport when the navigation
              // bar is expanded, but fits in the viewport when
              // the navigation bar is collapsed
              itemCount: 14,
              itemBuilder: (context, index) {
                return CupertinoListTile(
                  title: Text('Item $index'),
                );
              },
            ),
          ],
        ),
      ),
    ),
  );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.29.0-1.0.pre.184, on Microsoft Windows [Version 10.0.26100.3194], locale en-US) [1,986ms]
    • Flutter version 3.29.0-1.0.pre.184 on channel master at C:\Code\f\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d8585d936 (4 weeks ago), 2025-01-30 15:30:45 -0800
    • Engine revision 4d8585d936
    • Dart version 3.8.0 (build 3.8.0-24.0.dev)
    • DevTools version 2.42.0

[✓] Windows Version (11 Pro 64-bit, 24H2, 2009) [1,839ms]

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1) [1,298ms]
    • Android SDK at C:\Users\sharm\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [73ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2) [72ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34018.315
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2021.2) [17ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.97.2) [15ms]
    • VS Code at C:\Users\sharm\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.104.0

[✓] Connected device (3 available) [169ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.3194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 130.0.6723.70
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 133.0.3065.92

[✓] Network resources [516ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by techouse**
This pull request includes a fix to the `CupertinoSliverNavigationBarState` class in the `nav_bar.dart` file. The change ensures that the `animateTo` method is only called when the `target` is within the valid scroll extent range, i.e. `target <= position.maxScrollExtent`.

Fixes https://github.com/flutter/flutter/issues/164458

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by techouse** [comment]
@victorsanni, could you please take a look at this once you have a chance? 🙏

I'm not really sure why the Mac_arm64 and Mac_x64 "tool_test_commands" tests are failing. 🤷

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 1]
```diff
@@ -3069,6 +3069,77 @@ void main() {
     expect(find.text(largeTitle), findsOneWidget);
     expect(find.byType(CupertinoSearchTextField), findsOneWidget);
   });
+
+  testWidgets(
+    'CupertinoSliverNavigationBar does not enter infinite animation loop when target exceeds maxScrollExtent and prevents buttons from being tapped',
+    (WidgetTester tester) async {
+      setWindowToPortrait(tester);
+
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]:
```suggestion
```

Since it's set later on

**Review by victorsanni — APPROVED** [review]
LGTM with a nit. Thanks for the fix.

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 1 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Ha, how did I miss that 😅 Thanx ❤️

**Comment by techouse** [comment]
@MitchellGoodwin @victorsanni how likely is it for this fix to make it into a CP?

**Comment by victorsanni** [comment]
> @MitchellGoodwin @victorsanni how likely is it for this fix to make it into a CP?

Very unlikely. While it's not a new feature, it's also not a crash or something that severely breaks customers.

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 2]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+                ),
+              ),
+            ],
+          ),
+        ),
+      );
+
+      await tester.pumpAndSettle();
+
+      // Verify the button is present
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]: Really small grammar nit (and below), would be nicer to read and for consistency if the comments end in a period.

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 3]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+      expect(find.widgetWithText(CupertinoButton, 'Press me!'), findsOneWidget);
+
+      // Tap the button
+      await tester.tap(find.widgetWithText(CupertinoButton, 'Press me!'));
+      await tester.pump(); // Process the tap
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]: Nit: not sure this comment is needed. Pumps process/activate the actions preceding them.

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 4]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+        tester.getCenter(find.byType(Scrollable)),
+      );
+      await scrollGesture.moveBy(const Offset(0.0, -(largeTitleHeight / 2) - 1));
+      await scrollGesture.up();
+      // This should not time out or throw an error.
+      await tester.pumpAndSettle();
+
+      // Tap the button
+      await tester.tap(find.widgetWithText(CupertinoButton, 'Press me!'));
+      await tester.pump(); // Process the tap
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]: Here as well.

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 5]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+
+      // Check if the counter has increased
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]:
```suggestion
      // Check if the counter has increased.
```

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 6]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+      await tester.pumpAndSettle();
+
+      // Verify the button is present
+      expect(find.widgetWithText(CupertinoButton, 'Press me!'), findsOneWidget);
+
+      // Tap the button
+      await tester.tap(find.widgetWithText(CupertinoButton, 'Press me!'));
+      await tester.pump(); // Process the tap
+
+      // Check if the counter has increased
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]:
```suggestion
      // Check if the counter has increased.
```

File: packages/flutter/test/cupertino/nav_bar_test.dart [hunk 7]
```diff
@@ -3069,6 +3069,75 @@ void main() {
...
+          ),
+        ),
+      );
+
+      await tester.pumpAndSettle();
+
+      // Verify the button is present
+      expect(find.widgetWithText(CupertinoButton, 'Press me!'), findsOneWidget);
+
+      // Tap the button
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]:
```suggestion
      // Tap the button.
```

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 2 above)
Comment (victorsanni) [inline packages/flutter/test/cupertino/nav_bar_test.dart]:
```suggestion
      // Verify the button is present.
```

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 4 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Done

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 5 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Done

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 6 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Done

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 7 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Done

File: packages/flutter/test/cupertino/nav_bar_test.dart (hunk 2 above)
Comment (techouse) [reply packages/flutter/test/cupertino/nav_bar_test.dart]: Done

**Comment by techouse** [comment]
> Very unlikely. While it's not a new feature, it's also not a crash or something that severely breaks customers.

I see. I was under the impression that https://github.com/flutter/flutter/issues/164458 was labelled as a **P2** because it has a particularly severe impact on Android.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the fix.

**Comment by MitchellGoodwin** [comment]
> I see. I was under the impression that https://github.com/flutter/flutter/issues/164458 was labelled as a P2 because it has a particularly severe impact on Android.

P2 in our repo is not a critical priority. It's official description is "Important issues not at the top of the work list". Most issues are P2.
