### PR TITLE
Fixes initial validation with AutovalidateMode.always on first build

### LINKED ISSUE #142701: AutovalidateMode.always on Form not working as expected
### Steps to reproduce

Display the following widget:
```
Form(
  autovalidateMode: AutovalidateMode.always,
  child: TextFormField(
    validator: (value) => value?.isEmpty == true ? 'Empty' : null,
  ),
),
```

### Expected results

We would expect the error message "Empty", to be displayed under the `TextFormField`, because the `Form` has `AutovalidateMode.always` and the value of the field is empty.

### Actual results

The error message is not displayed when the `Form` is rendered. Only when a change happens on the `TextFormField`, for example adding and removing text, the error is displayed.

### Workaround

When the `TextFormField` has `AutovalidateMode.always`, the validation does happen immediately and the error message is displayed.

Looking into the source code, `Form` runs the `_validate` function in the beginning of its `build` method, before its `_fields` have registered. The `_validate` method goes over an empty Set of fields.

The `FormField` on the other hand sets its own `_errorText` before calling the builder is called, causing the actual builder of `TextFormField` to have the correct `errorText` available at the first time it builds.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Form(
            autovalidateMode: AutovalidateMode.always,
            child: TextFormField(
              validator: (value) => value?.isEmpty == true ? 'Empty' : null,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-BE)
    • Flutter version 3.16.9 on channel stable at /Users/fre/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (7 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fre/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/fre/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone SE (mobile) • 00008110-000E7901349B801E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes #142701
This PR fixes an issue where on the first build `AutovalidateMode.always` was not called.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/form.dart [hunk 1]
```diff
@@ -11,6 +11,7 @@ import 'dart:async';
 import 'package:flutter/foundation.dart';
 import 'package:flutter/rendering.dart';
 
+import '../scheduler/binding.dart';
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:14]: I think the convention is to do relative imports for files within the same directory, and package imports otherwise.

A couple of options:

```dart
// package import
import 'package:flutter/scheduler.dart';


// using WidgetsBinding wouldn't require the scheduler import
WidgetsBinding.instance.addPostFrameCallback(...)
```

File: packages/flutter/lib/src/widgets/form.dart [hunk 2]
```diff
@@ -586,6 +587,8 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
   /// false when [reset] is called.
   bool get hasInteractedByUser => _hasInteractedByUser.value;
 
+  bool _buildScheduled = false;
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:590]: ooh, this looks like it was inspired by `BuildScope`!

File: packages/flutter/lib/src/widgets/form.dart [hunk 3]
```diff
@@ -697,6 +700,20 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
...
+    if (Form.maybeOf(context)?.widget.autovalidateMode == AutovalidateMode.always) {
+      if (!_buildScheduled) {
+        _buildScheduled = true;
+        SchedulerBinding.instance.addPostFrameCallback((_) {
+          _buildScheduled = false;
+          validate();
+        });
+      }
+    }
+  }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:715]: Looks like a super effective solution, especially after seeing the test you added!

<br>

I noticed that the FormState's `_register()` method currently violates a style guideline:

```dart
  void _register(FormFieldState<dynamic> field) {
    _fields.add(field);
    if (widget.autovalidateMode == AutovalidateMode.onUnfocus) {
      field._focusNode.addListener(() => _updateField(field));
    }
  }
```

I'm wondering… maybe turning this into a switch statement and adding logic for `AutovalidateMode.always` could allow solving this issue without any post-frame callbacks.

Let me know what you think 🙂

File: packages/flutter/lib/src/widgets/form.dart [hunk 4]
```diff
@@ -742,7 +759,6 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
 
     return widget.builder(this);
   }
-
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:745]: This is satisfying, thank you 😌👌

File: packages/flutter/test/widgets/form_test.dart [hunk 5]
```diff
@@ -1457,4 +1457,47 @@ void main() {
 
     expect(focusNode2.hasFocus, isTrue);
   });
+
+  testWidgets('AutovalidateMode.always should validate on first build', (WidgetTester tester) async {
+    final GlobalKey<FormState> formKey = GlobalKey<FormState>();
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/form_test.dart:1462]: We could probably get rid of the `formKey` here since it's not being used:

```suggestion
```

**Review by nate-thegrate — COMMENTED** [review]
Thanks for making this fix!

File: packages/flutter/lib/src/widgets/form.dart (hunk 3 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart:715]: The switch statement worked beautifully and also made the code cleaner and more straightforward. Which guideline is `_register()` violating, those that were recently added? I'll take the opportunity to apply that improvement as well.

Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: There is one issue: the Material 2 time picker is not working as expected. I'm trying to figure out the issue, even with adding WidgetsBinding.instance.addPostFrameCallback(...) it still doesn't work. 😔😔

Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/form.dart]: Dang, unfortunate to hear.

<br>

As far as the style guideline, I was going to link to it but forgot, my bad!

https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-using-if-chains-or--or--with-enum-values

> ### Avoid using `if` chains or `?:` or `==` with enum values
> Use `switch` with no `default` case if you are examining an enum, since the analyzer will warn you if you missed any of the values when you use `switch`. The `default` case should be avoided so that the analyzer will complain if a value is missing. Unused values can be grouped together with a single `break` or `return` as appropriate.

Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: I found the problem, for example in the tests [time_picker_theme_test](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/time_picker_theme_test.dart#L862-L896) the `await tester.pumpAndSettle();` causes the problem of multiple builds. If I remove them, it works normally.

My code looks like this:
```
void _register(FormFieldState<dynamic> field) {
    _fields.add(field);
    switch (widget.autovalidateMode) {
      case AutovalidateMode.always:
        if (field.widget.enabled) {
          field.validate();
        }
      case AutovalidateMode.onUnfocus:
        field._focusNode.addListener(() => _updateField(field));
      case AutovalidateMode.onUserInteraction:
      case AutovalidateMode.disabled:
        break;
    }
  }
```
And if I add:

```
WidgetsBinding.instance.addPostFrameCallback((_) {
  if (field.widget.enabled) {
    field.validate();
  }
});
```
It causes a memory leak, because of `await tester.pumpAndSettle()`;

File: packages/flutter/lib/src/material/time_picker.dart [hunk 6]
```diff
@@ -1738,9 +1738,7 @@ class _TimePickerInputState extends State<_TimePickerInput> with RestorationMixi
 
   String? _validateHour(String? value) {
     final int? newHour = _parseHour(value);
-    setState(() {
-      hourHasError.value = newHour == null;
-    });
+    hourHasError.value = newHour == null;
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/time_picker.dart:1741]: This looks like a clear improvement: [`FormState.validate`](https://main-api.flutter.dev/flutter/widgets/FormState/validate.html) guarantees a rebuild, so I don't believe this `setState` is necessary.

<br>

However: I'm a bit worried about the implications here.

There might be a bunch Flutter projects outside of this codebase that build a `Form` with a similar structure; sadly, migrating the code here isn't going to help them out.

(I personally feel that many different aspects of the `Form` widget could be improved, but they'd require significant time investment and would definitely qualify as "breaking changes". I've also found that it's not very hard to just ignore `Form` entirely by using a state management package like provider or riverpod.)

<br>

Assuming we go through with this change: much like how theme data has [`useMaterial3`](https://main-api.flutter.dev/flutter/material/ThemeData/useMaterial3.html), it'd be nice if `Form` had something that allowed for a migration period.

File: packages/flutter/test/widgets/form_test.dart [hunk 7]
```diff
@@ -1457,4 +1457,45 @@ void main() {
...
+    String? errorText(String? value) => '$value/error';
+
+    Widget builder() {
+      return MaterialApp(
+        theme: ThemeData(),
+        home: MediaQuery(
+          data: const MediaQueryData(),
+          child: Directionality(
+            textDirection: TextDirection.ltr,
+            child: Center(
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/form_test.dart:1471]: I bet we could remove one or more of these widgets from the tree and the test would still run just fine :)

File: packages/flutter/test/widgets/form_test.dart [hunk 8]
```diff
@@ -1457,4 +1457,45 @@ void main() {
 
     expect(focusNode2.hasFocus, isTrue);
   });
+
+  testWidgets('AutovalidateMode.always should validate on first build', (WidgetTester tester) async {
+    String? errorText(String? value) => '$value/error';
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/form_test.dart:1462]: Making the return type non-nullable would remove the need for null checks further down!

```suggestion
    String errorText(String? value) => '$value/error';
```

**Review by nate-thegrate — COMMENTED** [review]
I'm a huge fan of this change—I feel that the current fix is an effective solution for #142701 and is probably better than a fix that involves using a post-frame callback.

As far as how to approach a breaking change that gives an overall improvement, there are several different paths we could take, so it'd be good to get another reviewer's input here (which might take up to 2 weeks, so thanks in advance for your patience).

File: packages/flutter/lib/src/widgets/form.dart [hunk 9]
```diff
@@ -250,8 +250,16 @@ class FormState extends State<Form> {
 
   void _register(FormFieldState<dynamic> field) {
     _fields.add(field);
-    if (widget.autovalidateMode == AutovalidateMode.onUnfocus) {
-      field._focusNode.addListener(() => _updateField(field));
+    switch (widget.autovalidateMode) {
+      case AutovalidateMode.always:
+        if (field.widget.enabled) {
+          field.validate();
+        }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:257]: One possible idea… maybe we _could_ do a post-frame callback here. Unlike [the previous fix](https://github.com/flutter/flutter/pull/156708#discussion_r1801554680), this wouldn't need a boolean flag to track the callback's status.

It wouldn't be quite as nice as the current setup, but it also might be less breaking.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 10]
```diff
@@ -1749,9 +1747,7 @@ class _TimePickerInputState extends State<_TimePickerInput> with RestorationMixi
 
   String? _validateMinute(String? value) {
     final int? newMinute = _parseMinute(value);
-    setState(() {
-      minuteHasError.value = newMinute == null;
-    });
+    minuteHasError.value = newMinute == null;
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/time_picker.dart:1750]: I think the ideal scenario would be to revert the change here if possible—just to show that fixing this bug doesn't require migrating existing code.

Or if migrating _is_ required, we would need to [handle the breaking change](https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes).

File: packages/flutter/lib/src/widgets/form.dart [hunk 11]
```diff
@@ -250,8 +250,17 @@ class FormState extends State<Form> {
 
   void _register(FormFieldState<dynamic> field) {
     _fields.add(field);
-    if (widget.autovalidateMode == AutovalidateMode.onUnfocus) {
-      field._focusNode.addListener(() => _updateField(field));
+    switch (widget.autovalidateMode) {
+      case AutovalidateMode.always:
+        // If the field has already been validated or has no errors, we can skip the if statement to avoid an infinite loop.
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:255]: What's the meaning of "infinite loop" here? Is it possible for the same field to be registered multiple times?

File: packages/flutter/test/widgets/form_test.dart [hunk 12]
```diff
@@ -1457,4 +1457,39 @@ void main() {
...
     expect(focusNode2.hasFocus, isTrue);
   });
+
+  testWidgets('AutovalidateMode.always should validate on first build', (WidgetTester tester) async {
+    String errorText(String? value) => '$value/error';
+
+    Widget builder() {
+      return MaterialApp(
+        theme: ThemeData(),
+        home: Center(
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/form_test.dart:1467]: Looking great!

I noticed a couple of other small things:
- Setting theme data probably isn't necessary here.
- We could probably just call `pumpWidget` here, since this function isn't being referenced in multiple places.

```suggestion
    await tester.pumpWidget(
      MaterialApp(
        home: Center(
```
(ending punctuation would need to be adjusted as well.)

**Review by nate-thegrate — COMMENTED** [review]
Thanks very much for the updates!

In my opinion, this change is worth it regardless of whether it qualifies as "breaking", but hopefully we can do it in a non-breaking way :)

File: packages/flutter/lib/src/material/time_picker.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/time_picker.dart:1741]: I've been eyeing Form for a rewrite for a long time. I wish I could just write a whole new class with a new name, but the name "Form" is so good I think we'd have to do something like userMaterial3.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/time_picker.dart:1750]: +1, the setStates could be removed in a followup PR.

File: packages/flutter/test/widgets/form_test.dart [hunk 13]
```diff
@@ -1457,4 +1457,39 @@ void main() {
...
+                ],
+              ),
+            ),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(builder());
+    await tester.pumpAndSettle();
```
Comment (justinmc) [inline packages/flutter/test/widgets/form_test.dart:1490]: I guess this pumpAndSettle is necessary because it takes 2 frames to get the error to show up? If so, I wonder if there's a way to do it in 1 frame.

**Review by justinmc — COMMENTED** [review]
Thanks for the PR! Still some questions but I think we should definitely fix this bug.

File: packages/flutter/lib/src/widgets/form.dart (hunk 9 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: I tried to address the issues, but some tests are still failing. I'm considering reverting to this implementation with `didChangeDependencies` and documenting the technical debt needed to resolve the problems with the` Form`. I will attempt to write documentation or outline the technical debt for this.

File: packages/flutter/lib/src/widgets/form.dart (hunk 3 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: I resolved the issue by simply moving the logic from inside the `Form` to within the `FormField`.

File: packages/flutter/lib/src/widgets/form.dart (hunk 11 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: Since the build method is always triggered when interacting with a field, or in this case, on the first build, it was causing recursive calls, leading to a memory overflow.

File: packages/flutter/test/widgets/form_test.dart (hunk 13 above)
Comment (Mairramer) [reply packages/flutter/test/widgets/form_test.dart]: Yes, now we can do it in 1 frame.

**Comment by nate-thegrate** [comment]
Unfortunately, my disliking toward certain aspects of the `Form` API is giving me some "analysis paralysis" as I consider how we might proceed with this PR.

@Mairramer thanks again for all the improvements you've made here! I'll probably be ready to re-engage sometime later this week.

**Comment by Mairramer** [comment]
> Unfortunately, my disliking toward certain aspects of the `Form` API is giving me some "analysis paralysis" as I consider how we might proceed with this PR.
> 
> @Mairramer thanks again for all the improvements you've made here! I'll probably be ready to re-engage sometime later this week.

I understand you. Over the weekend, I spent time reviewing several parts of the code that don't seem to follow the patterns we typically expect in Flutter.

File: packages/flutter/test/widgets/form_test.dart [hunk 14]
```diff
@@ -1457,4 +1457,38 @@ void main() {
...
+                  ),
+                ],
+              ),
+            ),
+          ),
+        )
+      )
+    );
+
+    await tester.pump();
```
Comment (justinmc) [inline packages/flutter/test/widgets/form_test.dart:1489]: It looks like this still takes 2 frames due to the addPostFrameCallback above? Ideally we wouldn't even need this pump here, only pumpWidget.

Comment (Mairramer) [reply packages/flutter/test/widgets/form_test.dart:1489]: I believe it used to work, but since I moved the business logic from the `Form` to the `FormField`, it no longer occurs.

**Review by nate-thegrate — COMMENTED** [review]
Thanks for your patience! I'm looking forward to getting this fix merged.

<br>

> I was analyzing several parts of the `Form` code that do not seem to have the quality standard that we expect from Flutter.

Amen to that. The widget wasn't poorly designed, but this file was created [8 years ago](https://github.com/flutter/flutter/pull/2850), and much has changed since then.

File: packages/flutter/lib/src/widgets/form.dart [hunk 15]
```diff
@@ -697,6 +686,25 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
...
+            validate();
+          }
+        });
+      case AutovalidateMode.onUnfocus:
+      case AutovalidateMode.onUserInteraction:
+      case AutovalidateMode.disabled:
+      case null:
+        break;
+    }
+  }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:706]: Thanks; this method looks to be in a good spot 👍

File: packages/flutter/lib/src/widgets/form.dart [hunk 16]
```diff
@@ -250,22 +251,10 @@ class FormState extends State<Form> {
...
     _fields.remove(field);
-    if (widget.autovalidateMode == AutovalidateMode.onUnfocus) {
-      field._focusNode.removeListener(()=> _updateField(field));
-    }
-  }
-
-  void _updateField(FormFieldState<dynamic> field) {
-    if (!field._focusNode.hasFocus) {
-      _validate();
-    }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/form.dart:268]: Since the `AutovalidateMode.onUnfocus` logic was removed below, would you be able to revert this section to its original state?

File: packages/flutter/lib/src/widgets/form.dart [hunk 17]
```diff
@@ -697,9 +687,36 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
...
+    switch (Form.maybeOf(context)?.widget.autovalidateMode) {
+      case AutovalidateMode.always:
+        WidgetsBinding.instance.addPostFrameCallback((_) {
+          // If the form is already validated, don't validate again.
+          if (widget.enabled && !hasError && !isValid) {
+            validate();
+          }
+        });
+      case AutovalidateMode.onUnfocus:
+        _focusNode.addListener(_updateField);
```
[the remark this answers is not in the document]
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart]: Looking at the code, I realized that I had mistakenly added this listener in this [PR](https://github.com/flutter/flutter/pull/140962). I can already check if the focus has been lost with the code below:
```
return Focus(
   canRequestFocus: false,
   skipTraversal: true,
   onFocusChange: (bool value) {
      if (!value) {
         setState(() {
            _validate();
        });
      }
    },
   focusNode: _focusNode,
   child: widget.builder(this),
);
```

File: packages/flutter/lib/src/widgets/form.dart (hunk 16 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/form.dart:268]: See https://github.com/flutter/flutter/pull/156708#discussion_r1811216557

File: packages/flutter/lib/src/widgets/form.dart (hunk 17 above)
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/form.dart]: Oh, awesome!

**Review by nate-thegrate — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by nate-thegrate** [comment]
FYI—per the [Tree hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#using-git) page, one way to fix Google testing could be to update via rebase rather than a merge commit.

Update with rebase

**Comment by justinmc** [comment]
Google tests seem to be failing because there are fields with `AutovalidateMode.always` that are now being displayed as invalid that weren't previously. Maybe these tests were just accidentally taking advantage of this bug and should use `.onuserInteraction` instead? I'll try to test this theory, but if anything else comes to mind let me know.

File: packages/flutter/test/widgets/form_test.dart (hunk 14 above)
Comment (justinmc) [inline packages/flutter/test/widgets/form_test.dart:1489]: I'm still not convinced that we can't get this into the correct state in the first frame. Can you see if you can get this test to pass after removing this `pump`?

I would think that when `_errorText` is assigned in `initState`, you could set its initial value to something like this:

```dart
widget.forceErrorText ?? widget.validator?.call(_value)
```

Would that work?

**Review by justinmc — COMMENTED** [review]
About the Google tests: Setting to .onUserInteraction fixes it. I've added a g3 fix. I want to clarify the process before I mark the Google tests as passing but I'll plan to do that Friday.

File: packages/flutter/test/widgets/form_test.dart (hunk 14 above)
Comment (nate-thegrate) [reply packages/flutter/test/widgets/form_test.dart:1489]: I believe the post-frame callback is the non-breaking way to do it, since the `validator` could potentially contain a `setState` call of the parent widget.

example: https://dartpad.dev/?id=62b1d1bce1cd79fa041135aab38d6d93

Comment (Mairramer) [reply packages/flutter/test/widgets/form_test.dart:1489]: > I believe the post-frame callback is the non-breaking way to do it, since the `validator` could potentially contain a `setState` call of the parent widget.
> 
> example: https://dartpad.dev/?id=62b1d1bce1cd79fa041135aab38d6d93

Exactly. The post-frame callback breaks this logic, because by removing it and running only this test, the `pump` becomes unnecessary.

Comment (justinmc) [reply packages/flutter/test/widgets/form_test.dart:1489]: Did you try it and it caused failures? The validator function sounds like something that shouldn't have side effects but maybe it's too late to make any changes like this if it's going to break everyone.

I tried removing the postFrameCallback but it still crashes if you call setState in `validator`.

<details>

<summary>Diff</summary>

```diff
diff --git a/packages/flutter/lib/src/widgets/form.dart b/packages/flutter/lib/src/widgets/form.dart
index 98c63fe884..0b1f90c1bd 100644
--- a/packages/flutter/lib/src/widgets/form.dart
+++ b/packages/flutter/lib/src/widgets/form.dart
@@ -550,7 +550,7 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
   late T? _value = widget.initialValue;
   // Marking it as late, so it can be registered
   // with the value provided by [forceErrorText].
-  late final RestorableStringN _errorText;
+  RestorableStringN? _errorText;
   final RestorableBool _hasInteractedByUser = RestorableBool(false);
   final FocusNode _focusNode = FocusNode();
 
@@ -564,10 +564,10 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
   /// This property is automatically updated when [validate] is called and the
   /// [FormField.validator] callback is invoked, or If [FormField.forceErrorText] is set
   /// directly to a non-null value.
-  String? get errorText => _errorText.value;
+  String? get errorText => _errorText!.value;
 
   /// True if this field has any validation errors.
-  bool get hasError => _errorText.value != null;
+  bool get hasError => _errorText!.value != null;
 
   /// Returns true if the user has modified the value of this field.
   ///
@@ -597,7 +597,7 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
     setState(() {
       _value = widget.initialValue;
       _hasInteractedByUser.value = false;
-      _errorText.value = null;
+      _errorText!.value = null;
     });
     Form.maybeOf(context)?._fieldDidChange();
   }
@@ -619,14 +619,14 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
 
   void _validate() {
     if (widget.forceErrorText != null) {
-      _errorText.value = widget.forceErrorText;
+      _errorText!.value = widget.forceErrorText;
       // Skip validating if error is forced.
       return;
     }
     if (widget.validator != null) {
-      _errorText.value = widget.validator!(_value);
+      _errorText!.value = widget.validator!(_value);
     } else {
-      _errorText.value = null;
+      _errorText!.value = null;
     }
   }
 
@@ -662,7 +662,7 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
 
   @override
   void restoreState(RestorationBucket? oldBucket, bool initialRestore) {
-    registerForRestoration(_errorText, 'error_text');
+    registerForRestoration(_errorText!, 'error_text');
     registerForRestoration(_hasInteractedByUser, 'has_interacted_by_user');
   }
 
@@ -672,23 +672,28 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
     super.deactivate();
   }
 
-  @override
-  void initState() {
-    super.initState();
-    _errorText = RestorableStringN(widget.forceErrorText);
-  }
-
   @override
   void didUpdateWidget(FormField<T> oldWidget) {
     super.didUpdateWidget(oldWidget);
     if (widget.forceErrorText != oldWidget.forceErrorText) {
-      _errorText.value = widget.forceErrorText;
+      _errorText!.value = widget.forceErrorText;
     }
   }
 
   @override
   void didChangeDependencies() {
+    final AutovalidateMode? autovalidateMode = Form.maybeOf(context)?.widget.autovalidateMode;
+    if (_errorText == null) {
+      if (autovalidateMode == AutovalidateMode.always) {
+        final String? errorText = widget.forceErrorText ?? widget.validator?.call(_value);
+        _errorText = RestorableStringN(errorText);
+      } else {
+        _errorText = RestorableStringN(widget.forceErrorText);
+      }
+    }
+
     super.didChangeDependencies();
+
     switch (Form.maybeOf(context)?.widget.autovalidateMode) {
       case AutovalidateMode.always:
         WidgetsBinding.instance.addPostFrameCallback((_) {
@@ -707,7 +712,7 @@ class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
 
   @override
   void dispose() {
-    _errorText.dispose();
+    _errorText!.dispose();
     _focusNode.dispose();
     _hasInteractedByUser.dispose();
     super.dispose();
diff --git a/packages/flutter/test/widgets/form_test.dart b/packages/flutter/test/widgets/form_test.dart
index 13c9ba3263..466506ebe5 100644
--- a/packages/flutter/test/widgets/form_test.dart
+++ b/packages/flutter/test/widgets/form_test.dart
@@ -1486,7 +1486,7 @@ void main() {
       )
     );
 
-    await tester.pump();
+    //await tester.pump();
 
     expect(find.text(errorText('foo')), findsOneWidget);
     expect(find.text(errorText('bar')), findsOneWidget);

```

</details>

Comment (Mairramer) [reply packages/flutter/test/widgets/form_test.dart:1489]: Sorry for the delay. I tried a few approaches as well, but they didn't work.😔

File: packages/flutter/test/widgets/form_test.dart [hunk 18]
```diff
@@ -1457,4 +1457,38 @@ void main() {
...
+                  TextFormField(
+                    initialValue: 'bar',
+                    validator: errorText,
+                  ),
+                ],
+              ),
+            ),
+          ),
+        )
+      )
```
Comment (justinmc) [inline packages/flutter/test/widgets/form_test.dart:1486]: Super nit: Trailing commas here.

File: packages/flutter/test/widgets/form_test.dart [hunk 19]
```diff
@@ -1457,4 +1457,38 @@ void main() {
 
     expect(focusNode2.hasFocus, isTrue);
   });
+
+  testWidgets('AutovalidateMode.always should validate on first build', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/widgets/form_test.dart:1461]: Nit: Actually the second build, right?

File: packages/flutter/test/widgets/form_test.dart (hunk 14 above)
Comment (justinmc) [reply packages/flutter/test/widgets/form_test.dart:1489]: Sounds like this is our best option then, thanks for checking!

Nit: Maybe add `expect`s above this pump to check that the error text does not yet appear, and explain?

```dart
    // The validation happens in a post frame callback, so the error
    // doesn't show up until the second frame.
    expect(find.text(errorText('foo')), findsNothing);
    expect(find.text(errorText('bar')), findsNothing);

    await tester.pump();

   ...
```

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Sorry for nitpicking this PR to death over the addPostFrameCallback, I just wanted to make sure there wasn't another option before we committed to that.

**Review by justinmc — APPROVED** [review]
Thanks for the changes, renewing my LGTM 👍 . The Google failure was one case of the error message not showing when it should have been, so I've approved the golden image change.

**Comment by stan-at-work** [comment]
Does this issue, fixes this bug currently present in v3.24.5.

The form for some reason triggers an setState when the underlying widgets are beeing build (for the first time i think).

---

```text
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for TextEditingController:
flutter: setState() or markNeedsBuild() called during build.
flutter: This Form widget cannot be marked as needing to build because the framework is already in the
flutter: process of building widgets. A widget can be marked as needing to be built during the build phase
flutter: only if one of its ancestors is currently building. This exception is allowed because the framework
flutter: builds parent widgets before children, which means a dirty descendant will always be built.
flutter: Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   Form-[LabeledGlobalKey<FormState>#9ba50]
flutter: The widget which was currently being built when the offending call was made was:
flutter:   CoreDropdown<CoreFieldType>
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure>
flutter: #1      Element.markNeedsBuild
flutter: #2      State.setState
flutter: #3      FormState._forceRebuild
flutter: #4      FormState._fieldDidChange
flutter: #5      FormFieldState.didChange
flutter: #6      _TextFormFieldState.didChange
flutter: #7      _TextFormFieldState._handleControllerChanged
flutter: #8      ChangeNotifier.notifyListeners
flutter: #9      ValueNotifier.value=
flutter: #10     TextEditingController.value=
flutter: #11     TextEditingController.text=
flutter: #12     CoreDropdownState.build
flutter: #13     StatefulElement.build
flutter: #14     ComponentElement.performRebuild
flutter: #15     StatefulElement.performRebuild
flutter: #16     Element.rebuild
flutter: #17     StatefulElement.update
flutter: #18     Element.updateChild
flutter: #19     ComponentElement.performRebuild
flutter: #20     Element.rebuild
flutter: #21     ProxyElement.update
flutter: #22     Element.updateChild
flutter: #23     Element.updateChildren
flutter: #24     MultiChildRenderObjectElement.update
flutter: #25     Element.updateChild
flutter: #26     ComponentElement.performRebuild
flutter: #27     Element.rebuild
flutter: #28     StatelessElement.update
flutter: #29     Element.updateChild
flutter: #30     ComponentElement.performRebuild
flutter: #31     StatefulElement.performRebuild
flutter: #32     Element.rebuild
flutter: #33     StatefulElement.update
flutter: #34     Element.updateChild
flutter: #35     ComponentElement.performRebuild
flutter: #36     StatefulElement.performRebuild
flutter: #37     Element.rebuild
flutter: #38     StatefulElement.update
flutter: #39     Element.updateChild
flutter: #40     ComponentElement.performRebuild
flutter: #41     StatefulElement.performRebuild
flutter: #42     Element.rebuild
flutter: #43     StatefulElement.update
flutter: #44     Element.updateChild
flutter: #45     ComponentElement.performRebuild
flutter: #46     StatefulElement.performRebuild
flutter: #47     Element.rebuild
flutter: #48     StatefulElement.update
flutter: #49     Element.updateChild
flutter: #50     ComponentElement.performRebuild
flutter: #51     StatefulElement.performRebuild
flutter: #52     Element.rebuild
flutter: #53     StatefulElement.update
flutter: #54     Element.updateChild
flutter: #55     ComponentElement.performRebuild
flutter: #56     StatefulElement.performRebuild
flutter: #57     Element.rebuild
flutter: #58     BuildScope._tryRebuild
flutter: #59     BuildScope._flushDirtyElements
flutter: #60     BuildOwner.buildScope
flutter: #61     WidgetsBinding.drawFrame
flutter: #62     RendererBinding._handlePersistentFrameCallback
flutter: #63     SchedulerBinding._invokeFrameCallback
flutter: #64     SchedulerBinding.handleDrawFrame
flutter: #65     SchedulerBinding._handleDrawFrame
flutter: #69     _invoke (dart:ui/hooks.dart:314:10)
flutter: #70     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
flutter: #71     _drawFrame (dart:ui/hooks.dart:283:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: The TextEditingController sending notification was:
flutter:   TextEditingController#d8dc9(TextEditingValue(text: ┤Lead├, selection: TextSelection.invalid,
flutter:   composing: TextRange(start: -1, end: -1)))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: setState() or markNeedsBuild() called during build.
```

**Comment by nate-thegrate** [comment]
@stan-at-work unfortunately I don't think so—this PR did have to deal with the same problem, but it was with regards to initializing the widget, not with `didUpdateWidget` calls.

**Comment by Mairramer** [comment]
@nate-thegrate @stan-at-work 
Today, I spent some time experimenting with the Form and tried refactoring the code. I explored two approaches: one using `ValueNotifier` with a `Mixin` and another using only a `Mixin`. In both implementations, I managed to perform validation during the first build without relying on `WidgetsBinding.instance.addPostFrameCallback`. It’s still not entirely clear to me, but it seems that the `RestorationMixin` is responsible for many of these issues, since it extends the `State` itself.

@nate-thegrate Do you think this could be related or is it just a coincidence?

**Comment by stan-at-work** [comment]
> @nate-thegrate @stan-at-work 
> 
> Today, I spent some time experimenting with the Form and tried refactoring the code. I explored two approaches: one using `ValueNotifier` with a `Mixin` and another using only a `Mixin`. In both implementations, I managed to perform validation during the first build without relying on `WidgetsBinding.instance.addPostFrameCallback`. It’s still not entirely clear to me, but it seems that the `RestorationMixin` is responsible for many of these issues, since it extends the `State` itself.
> 
> 
> 
> @nate-thegrate Do you think this could be related or is it just a coincidence?

Would you be able to share what you made ?

**Comment by Mairramer** [comment]
Here are some changes:
https://gist.github.com/Mairramer/0ccf3eb24750c9b1a9802d7efb1134f1

There's a lot of stuff in there that's just for testing purposes, as I'm trying to find these blind spots that cause errors in other widgets.

**Comment by stan-at-work** [comment]
> Here are some changes: https://gist.github.com/Mairramer/0ccf3eb24750c9b1a9802d7efb1134f1 I recovered from vscode history, it may be wrong in some parts.
> 
> There's a lot of stuff in there that's just for testing purposes, as I'm trying to find these blind spots that cause errors in other widgets.

Thanks
