### PR TITLE
Fix web test flakiness; enable web golden tests

### LINKED ISSUE #47003: Enable web golden tests
The tests fail with "Unknown error loading". For example:

```
02:03 +118 ~33 -1: compiling /tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart [E]                                                                                           
  Failed to load "/tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart": Unknown error loading http://localhost:43947/packages/flutter/material.ddc.js
```

Seen in the following, but I've seen it multiple times lately.

https://cirrus-ci.com/task/5055207964147712?command=main#L759
https://cirrus-ci.com/task/5899632894279680?command=main#L2370

/cc @jonahwilliams and @yjbanov who may know what's going on.

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

The fix is three-part:

- Only allow one test to load _and_ test at any point in time.
- Use a fresh Chrome instance for each test file.
- Increase Cirrus resources.

The first two changes only fix the "Unknown error loading" error, but not hanging tests. The resource increase also prevents hanging tests.

Other minor changes:

- Remove test batching. It's no longer necessary and it allows us to run all tests even when some fail rather than fail as soon as the first batch fails.
- Fix the `Chrome` class, which was using the wrong `Completer`.

## Related Issues

Fixes #47003

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 1.
Please triage them at https://flutter-gold.skia.org/search?issue=52789.

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart [hunk 1]
```diff
@@ -701,6 +678,9 @@ class BrowserManager {
     Uri url,
     SuiteConfiguration suiteConfig,
     Object message,
+    {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/test/flutter_web_platform.dart]: nit, `Object message, {`

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart [hunk 2]
```diff
@@ -726,29 +706,28 @@ class BrowserManager {
...
+      'id': suiteID,
+      'channel': suiteChannelID,
+    });
 
-      try {
-        controller = deserializeSuite(path, SuitePlatform(Runtime.chrome),
-            suiteConfig, await _environment, suiteChannel, message);
+    try {
+      controller = deserializeSuite(path, SuitePlatform(Runtime.chrome),
+          suiteConfig, await _environment, suiteChannel, message);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/test/flutter_web_platform.dart]:
```suggestion
        suiteConfig, await _environment, suiteChannel, message);
```

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 3]
```diff
@@ -262,13 +262,11 @@ class Chrome {
   final ChromeConnection chromeConnection;
   final Uri remoteDebuggerUri;
 
-  static Completer<Chrome> _currentCompleter = Completer<Chrome>();
-
-  Future<void> get onExit => _currentCompleter.future;
+  Future<int> get onExit => _process.exitCode;
 
   Future<void> close() async {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart]: Can this be tested somehow?

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 4]
```diff
@@ -262,13 +262,11 @@ class Chrome {
...
-    if (_currentCompleter.isCompleted) {
-      _currentCompleter = Completer<Chrome>();
+    if (ChromeLauncher._currentCompleter.isCompleted) {
```
Comment (angjieli) [inline packages/flutter_tools/lib/src/web/chrome.dart]: Use `ChromeLauncher.hasChromeInstance` instead?

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/test/flutter_web_platform.dart]: Done.

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart (hunk 2 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/test/flutter_web_platform.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 4 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 3.
Please triage them at https://flutter-gold.skia.org/search?issue=52789.

**Comment by angjieli** [comment]
LGTM

File: packages/flutter_tools/test/general.shard/web/chrome_test.dart [hunk 5]
```diff
@@ -61,29 +62,50 @@ void main() {
     resetChromeForTesting();
   });
 
-  test('can launch chrome and connect to the devtools', () async {
-    processManager.addCommand(const FakeCommand(
+  Future<Chrome> _testLaunchChrome(String userDataDir) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/test/general.shard/web/chrome_test.dart]: I would just leave this as public and hoist to the top level scope at the bottom of the file. It should not capture any of the locally defined values.

Comment (yjbanov) [reply packages/flutter_tools/test/general.shard/web/chrome_test.dart]: Since this is a convenience function, being able to access `processManager` and `chromeLauncher` is part of its value. It would be less convenient if these things had to be passed at each call site. Is there danger with capturing them?

Comment (yjbanov) [reply packages/flutter_tools/test/general.shard/web/chrome_test.dart]: BTW "capture" is probably not the right word. They are _in scope_. They are not captured in the closure sense.

Comment (yjbanov) [reply packages/flutter_tools/test/general.shard/web/chrome_test.dart]: Done though

File: packages/flutter_tools/test/general.shard/web/chrome_test.dart [hunk 6]
```diff
@@ -163,3 +167,21 @@ void main() {
 }
 
 class MockOperatingSystemUtils extends Mock implements OperatingSystemUtils {}
+
+Future<Chrome> testLaunchChrome(String userDataDir, FakeProcessManager processManager, ChromeLauncher chromeLauncher) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/test/general.shard/web/chrome_test.dart]: Thanks!

This is much simpler to read since it does not depend on the specific location in the test script

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by chingjun — APPROVED** [review]

**Comment by yjbanov** [comment]
Landing on red. The build breakage is a new devicelab test being debugged mid-flight.
