### PR TITLE
Fine tune the Y offset of OutlineInputBorder's floating label

### LINKED ISSUE #54028: Outlined TextField floating label is too low
internal b/153030038

The floating label for the outlined TextField widget is too low and doesn't match Material design, please see https://dartpad.dev/bf25d5a76c0bc8a318d5f83ff375bbf6 for the reproduction case.

Marking as critical as it is causing the app to fail MD review.

### PR DESCRIPTION
**Pull request by HansMuller**
InputDecorator: Ensure that the OutlineInputBorder's floating label is vertically centered relative to the center of the top edge of the outline.

Fixes https://github.com/flutter/flutter/issues/54028

This fix is temporarily "opt-in": the ThemeData `fixTextFieldOutlineLabel` enables the fix.

The  fixTextFieldOutlineLabel flag will be deprecated and its default value changed to true in a future version of Flutter.

In the image below, fixTextFieldOutlineLabel is false (the default) on the left, true on the right.

Screen Shot 2020-04-20 at 6 07 31 PM

### CODE REVIEW

File: packages/flutter/lib/src/material/theme_data.dart [hunk 1]
```diff
@@ -1316,6 +1336,7 @@ class ThemeData with Diagnosticable {
       dividerTheme: DividerThemeData.lerp(a.dividerTheme, b.dividerTheme, t),
       buttonBarTheme: ButtonBarThemeData.lerp(a.buttonBarTheme, b.buttonBarTheme, t),
       bottomNavigationBarTheme: BottomNavigationBarThemeData.lerp(a.bottomNavigationBarTheme, b.bottomNavigationBarTheme, t),
+      fixTextFieldOutlineLabel: t < 0.5 ? a.fixTextFieldOutlineLabel : b.fixTextFieldOutlineLabel,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/theme_data.dart:1339]: Sure you don't want to lerp the adjustment? :-) (just kidding)

**Review by gspencergoog — APPROVED** [review]
- [x] Step 1

32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
