### PR TITLE
Fix: Delay showing tooltip during page transition

### LINKED ISSUE #167359: PopupMenuButton asserts when rendering tooltip after navigating back using Cupertino tab layout
### Steps to reproduce

1. Install Flutter 3.27 with this commit applied (just a one line change): https://github.com/flutter/flutter/commit/4503f2f459c34d8ce5a7debc19c14457bb439900
2. Run the attached sample app on MacOS or iOS.
3. Click "Go to Second Page" button
4. Click the back button at top left, and don't move the cursor
5. App will assert as soon as the page transition completes if cursor is in position to invoke the PopupMenu's tooltip

Note 1:  If you don't apply the aforementioned commit, you will instead crash when attempting to use the PopupMenu after navigation.  That issue was fixed by the commit and that bug has been closed. 
Note 2: If you set the tooltip for the PopupMenu to empty string, the assert does not occur (see commented out code in example)

### Expected results

App doesn't crash/assert

### Actual results

App asserts when rendering the tooltip for the PopupMenu.  Top of call stack shown here:
_AssertionError._doThrowNew (flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/errors_patch.dart:63)
_AssertionError._throwNew (flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/errors_patch.dart:45)
RenderBox.size (flutter/packages/flutter/lib/src/rendering/box.dart:2251)
RenderFractionalTranslation.applyPaintTransform (flutter/packages/flutter/lib/src/rendering/proxy_box.dart:2974)
RenderObject.getTransformTo (flutter/packages/flutter/lib/src/rendering/object.dart:3520)
RenderBox.localToGlobal (flutter/packages/flutter/lib/src/rendering/box.dart:3082)
TooltipState._buildTooltipOverlay (flutter/packages/flutter/lib/src/material/tooltip.dart:793)
Builder.build (flutter/packages/flutter/lib/src/widgets/basic.dart:7818)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: const CupertinoHomeScaffold(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  void _handleMenuSelection(String value) {
    debugPrint('Menu selection: $value');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text('Home Page'),
        leading: PopupMenuButton<String>(
          icon: const Icon(Icons.more_vert),
          //tooltip: '', // empty tooltip prevents the crash
          onSelected: _handleMenuSelection,
          itemBuilder:
              (BuildContext context) => [
                const PopupMenuItem<String>(
                  value: 'settings',
                  child: Text('Settings'),
                ),
                const PopupMenuItem<String>(
                  value: 'about',
                  child: Text('About'),
                ),
              ],
        ),
      ),
      body: Center(
        child: TextButton(
          onPressed:
              () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const SimplePage(title: 'Second Page'),
                ),
              ),
          child: const Text('Go to Second Page'),
        ),
      ),
    );
  }
}

class SimplePage extends StatelessWidget {
  const SimplePage({super.key, required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: const Center(child: Text('Nothing to see here.')),
    );
  }
}

class CupertinoHomeScaffold extends StatefulWidget {
  const CupertinoHomeScaffold({super.key});

  @override
  CupertinoHomeScaffoldState createState() => CupertinoHomeScaffoldState();
}

class CupertinoHomeScaffoldState extends State<CupertinoHomeScaffold> {
  CupertinoTabController controller = CupertinoTabController();

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      controller: controller,
      tabBar: CupertinoTabBar(
        key: const Key(Keys.tabBar),
        items: TabItem.values.map((ti) => _buildItem(ti)).toList(),
        onTap:
            (index) => setState(() {
              controller.index = index;
            }),
      ),
      tabBuilder: (context, index) {
        final tabItem = TabItem.values[index];
        return CupertinoTabView(
          navigatorKey: navigatorKeys[tabItem],
          builder:
              (context) =>
                  tabItem == TabItem.incidents
                      ? const MyHomePage()
                      : const SimplePage(title: 'Responders'),
        );
      },
    );
  }

  BottomNavigationBarItem _buildItem(TabItem tabItem) {
    final itemData = TabItemData.allTabs[tabItem]!;
    final color =
        controller.index == tabItem.index ? Colors.indigo : Colors.grey;
    return BottomNavigationBarItem(
      icon: Icon(itemData.icon, color: color),
      label: itemData.title,
    );
  }
}

enum TabItem { incidents, responders }

class Keys {
  static const String tabBar = 'tabBar';
  static const String incidentsTab = 'incidentsTab';
  static const String respondersTab = 'respondersTab';
}

final Map<TabItem, GlobalKey<NavigatorState>> navigatorKeys = {
  TabItem.incidents: GlobalKey<NavigatorState>(),
  TabItem.responders: GlobalKey<NavigatorState>(),
};

class TabItemData {
  const TabItemData({
    required this.key,
    required this.title,
    required this.icon,
  });

  final String key;
  final String title;
  final IconData icon;

  static const Map<TabItem, TabItemData> allTabs = {
    TabItem.incidents: TabItemData(
      key: Keys.incidentsTab,
      title: 'Incidents',
      icon: Icons.work,
    ),
    TabItem.responders: TabItemData(
      key: Keys.respondersTab,
      title: 'Responders',
      icon: Icons.person,
    ),
  };
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 16.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Delay showing tooltip during page transition
fixes: #167359 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/tooltip.dart [hunk 1]
```diff
@@ -564,6 +564,13 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
       if (!_visible) {
         return;
       }
+      // Check if there's an ongoing route transition
+      final ModalRoute<dynamic>? route = ModalRoute.of(context);
+      if (route?.secondaryAnimation != null && route!.secondaryAnimation!.isAnimating) {
+        _timer?.cancel();
+        _timer = Timer(route.transitionDuration, show);
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/tooltip.dart:571]: Is it possible to listen to when the animation ends and start the timer then? The current way isn't compatible with cases where this happens halfway during the transition or simulation-based transition where there isn't a predefined duration.

Comment (rkishan516) [reply packages/flutter/lib/src/material/tooltip.dart:571]: Yaa, was thinking the same. but for some reason below written code doesn't fix the issue.
```dart
if (route?.secondaryAnimation != null && route!.secondaryAnimation!.isAnimating) {
   _timer?.cancel();
   void onAnimationDismiss(AnimationStatus status) {
        if (status == AnimationStatus.dismissed) {
           route.secondaryAnimation!.removeStatusListener(onAnimationDismiss);
           show();
       }
   }

    route.secondaryAnimation!.addStatusListener(onAnimationDismiss);
    return;
}
```

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/tooltip.dart:571]: In some cases the secondaryAnimation is swapped for a different one, so that may be why. The secondaryAnimation with the status listener is replaced.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/tooltip.dart:571]: Rather than putting the logic here, should we have the check happen in tandem with the `_visible` check for `_ExclusiveMouseRegion`? So it ignores all mouse events while the route transitions are in motion?

Comment (rkishan516) [reply packages/flutter/lib/src/material/tooltip.dart]: Pushed the change, everything looks good. Thanks.

File: packages/flutter/test/material/tooltip_test.dart [hunk 2]
```diff
@@ -3478,6 +3479,48 @@ void main() {
     );
     expect(tester.element(textAncestors.first).size, equals(tooltipConstraints.biggest));
   });
+
+  testWidgets('Tooltip does not show while transitioning from another page', (
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/tooltip_test.dart:3483]: Extreme nit, for this case I think it needs a link to the issue it is checking against.
```suggestion
  // This is a regression test for https://github.com/flutter/flutter/issues/167359.
  testWidgets('Tooltip does not show while transitioning from another page', (
```

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for making this fix. Just left one tiny nit.

File: packages/flutter/test/material/tooltip_test.dart (hunk 2 above)
Comment (rkishan516) [reply packages/flutter/test/material/tooltip_test.dart:3484]: Thanks for suggestion. Pushed the change.

**Review by Piinks — APPROVED** [review]
LGTM, thank you!
