### PR TITLE
Fix error resolution when a completer is already set

### LINKED ISSUE #80969: test/painting/image_provider_test.dart failing on Linux Web Framework tests
This is blocking the current Dart SDK roll. First seen on https://github.com/flutter/engine/pull/25687, which puts the window of commits that caused this as https://dart.googlesource.com/sdk.git/+log/debb4fc09ad2..ec6e6180269e

cc @yjbanov

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/80969

The test this modifies was never actually getting into the `FlutterError.onError` because of an assertion around `setCompleter`. An upcoming dart roll made the whole test blow up. This version now asserts that we get into `FlutterError.onError` as expected, and passes with the Dart revision to the way Zone error handling happens.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 1]
```diff
@@ -333,8 +333,10 @@ abstract class ImageProvider<T extends Object> {
       },
       (T? key, Object exception, StackTrace? stack) async {
         await null; // wait an event turn in case a listener has been added to the image stream.
-        final _ErrorImageCompleter imageCompleter = _ErrorImageCompleter();
-        stream.setCompleter(imageCompleter);
+        final ImageStreamCompleter imageCompleter = stream.completer ?? _ErrorImageCompleter();
+        if (stream.completer == null) {
+          stream.setCompleter(imageCompleter);
+        }
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/image_provider.dart:339]: Without this, we trip over an assertion error. The test used to be happy because Dart didn't bubble it up to the outter zone handler in the test, but we actually just stopped execution here and didn't do what we think we were doing.

See https://github.com/dart-lang/sdk/commit/88a351f3d2e675e203ce6452bc39f0e06e2a037c

**Review by jason-simmons — APPROVED** [review]
