### PR TITLE
Support BGRA textures in BlitCopyTextureToBufferCommandGLES::Encode and fix improper mapping of BGRA to RGBA in blit_command_gles and texture_gles

### LINKED ISSUE #182105: Fix broken opengles dart engine tests that crash with GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
Some opengles dart engine tests are currently skipped because they crash with the following error:
```
[ERROR:flutter/impeller/renderer/backend/gles/blit_command_gles.cc(79)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create a complete framebuffer: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
[FATAL:flutter/impeller/renderer/backend/gles/blit_pass_gles.cc(88)] Check failed: result. Must be able to encode GL commands without error.
```

These tests seem to pass when running with an unopt build (e.g. `host_debug_unopt_arm64`), and crash when running on a non-unopt build (e.g. `ci/host_debug_arm64_tests`).

The following tests have this behavior:
```
codec_test.dart
decode_image_from_pixels_sync_test.dart
encoding_test.dart
image_dispose_test.dart
image_resize_test.dart
```

### PR DESCRIPTION
**Pull request by b-luk**
Updates BlitCopyTextureToBufferCommandGLES::Encode to check for "GL_EXT_texture_format_BGRA8888", and call gl.ReadPixels with GL_BGRA_EXT if appropriate.

Also fixes an improper mapping of BGRA to RGBA in blit_command_gles and texture_gles. It now properly maps BGRA if BGRA is supported. If BGRA is not supported, it falls back to the existing behavior of using RGBA. I think this may be incorrect, but it's existing behavior so I'm not changing it.

This fixes codec_test.dart for opengles, which currently fails on linux.

Fixes #182105

## codec_test.dart failure

[codec_test.dart](https://github.com/flutter/flutter/blob/ba9a650befcc53f56db2bd86fe3cc278b3a788a1/engine/src/flutter/testing/dart/codec_test.dart) has many tests which calls `getNextFrame()` on a codec, and then calls `toByteData` on the resulting frame:
``` dart
    final Uint8List data = File(
      path.join('flutter', 'lib', 'ui', 'fixtures', 'four_frame_with_reuse.gif'),
    ).readAsBytesSync();
    final ui.Codec codec = await ui.instantiateImageCodec(data);

    // Capture the final frame of animation. If we have not composited
    // correctly, it will be clipped strangely.
    late ui.FrameInfo frameInfo;
    for (var i = 0; i < 4; i++) {
      frameInfo = await codec.getNextFrame();
    }
    codec.dispose();

    final ui.Image image = frameInfo.image;
    final ByteData imageData = (await image.toByteData(format: ui.ImageByteFormat.png))!;
```

This was causing a crash with the following error:
```
[ERROR:flutter/impeller/renderer/backend/gles/blit_command_gles.cc(343)] Break on 'ImpellerValidationBreak' to inspect point of failure: Only textures with pixel format RGBA are supported yet.
[FATAL:flutter/impeller/renderer/backend/gles/blit_pass_gles.cc(88)] Check failed: result. Must be able to encode GL commands without error.
```

## Cause

`getNextFrame()` converts an image frame into a bitmap. The bitmap generation is configured with the `SkImageInfo` here:
https://github.com/flutter/flutter/blob/ba9a650befcc53f56db2bd86fe3cc278b3a788a1/engine/src/flutter/lib/ui/painting/multi_frame_codec.cc#L65
The bitmap uses `kN32_SkColorType`. This is defined here: https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/include/core/SkColorType.h;l=145-149?q=kN32_SkColorType&ss=chromium. It is an alias that can be `kRGBA_8888_SkColorType` or `kBGRA_8888_SkColorType`, depending on the platform.

So the generated `DlImage` created by `getNextFrame()` is backed by a texture which can have a pixel format of either RGBA or BGRA.

When `toByteData()` is called on this image, opengles impeller uses `BlitCopyTextureToBufferCommandGLES::Encode` to convert the `DlImage`'s texture to byte data. If the texture has a BGRA pixel format, this fails:
https://github.com/flutter/flutter/blob/ba9a650befcc53f56db2bd86fe3cc278b3a788a1/engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc#L340-L345

On linux, including our CI linux tests, the pixel format is BGRA and codec_test.dart fails.

## Fix

This PR changes `BlitCopyTextureToBufferCommandGLES::Encode` to add a check for "GL_EXT_texture_format_BGRA8888" support. If it is supported, BGRA pixel format textures are accepted. These textures will be read with `gl.ReadPixels` using a format of `GL_BGRA_EXT` rather than `GL_RGBA`.

If "GL_EXT_texture_format_BGRA8888" is not supported, this may still result in a crash. This could potentially be fixed by converting BGRA images to RGBA. But that is outside the scope of this PR.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/gles/reactor_gles.cc [hunk 1]
```diff
@@ -201,7 +201,8 @@ bool ReactorGLES::RegisterCleanupCallback(const HandleGLES& handle,
 }
 
 HandleGLES ReactorGLES::CreateUntrackedHandle(HandleType type) const {
-  FML_DCHECK(CanReactOnCurrentThread());
+  [[maybe_unused]] bool can_react = CanReactOnCurrentThread();
+  FML_DCHECK(can_react);
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/backend/gles/reactor_gles.cc]: I'm not keen to accept this extra overhead.  Do you not need this after my PR that eliminates multithreaded tests?

**Review by gaaclarke — CHANGES_REQUESTED** [review]
Looks good for the most part except for the change to CreateUntrackedHandle, I have questions there.

File: engine/src/flutter/impeller/renderer/backend/gles/reactor_gles.cc (hunk 1 above)
Comment (b-luk) [reply engine/src/flutter/impeller/renderer/backend/gles/reactor_gles.cc]: We can keep the discussion around this to the other PR. This PR contains this change too, but only because this PR is based on top of that one.

**Comment by b-luk** [comment]
This doesn't pass on linux. codec_test has tests which check specific byte values of the output, which end up different because it's using BGRA. I'll convert this to a draft until I fix this.

**Review by gaaclarke — APPROVED** [review]
looks good to me, thanks b-luk!
