### PR TITLE
[flutter_conductor] fix git push mirror

### LINKED ISSUE #88069: [flutter_conductor] git push to mirror remote malformed
Currently, the conductor tries to push a local branch to the mirror remote via the command:

`git push <mirror remote name> <revision>:<feature branch name>`

However, git cannot resolve this if the feature branch name does not yet exist on the remote.

### PR DESCRIPTION
**Pull request by christopherfujino**
- Fixes https://github.com/flutter/flutter/issues/88069
- In generated PR description, prefixes engine commits with `flutter/engine@` so GitHub will auto-generate hyperlinks
- Updates framework and engine .ci.yaml enabled_branches with this release's candidate branch, part of https://github.com/flutter/flutter/issues/81491

### CODE REVIEW

File: dev/conductor/lib/repository.dart [hunk 1]
```diff
@@ -597,8 +611,19 @@ class FrameworkRepository extends Repository {
         .childFile('engine.version');
     assert(engineVersionFile.existsSync());
     final String oldEngine = engineVersionFile.readAsStringSync();
+    if (oldEngine.trim() == newEngine.trim()) {
+      stdio.printTrace(
+        'Tried to update the engine revision but version file is alread up to date at: $newEngine',
```
Comment (CaseyHillers) [inline dev/conductor/lib/repository.dart:616]:
```suggestion
        'Tried to update the engine revision but version file is already up to date at: $newEngine',
```

File: dev/conductor/lib/repository.dart [hunk 2]
```diff
@@ -766,3 +793,68 @@ class Checkouts {
   final ProcessManager processManager;
   final Stdio stdio;
 }
+
+class CiYaml {
```
Comment (CaseyHillers) [inline dev/conductor/lib/repository.dart:797]: What is the benefit to having conductor in the framework versus Cocoon?

Comment (CaseyHillers) [reply dev/conductor/lib/repository.dart:797]: This is preferable as enabled_branches is straight forward, but if for some reason in the future we need more advanced logic it should rely directly on the backend.

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

File: dev/conductor/lib/repository.dart (hunk 2 above)
Comment (christopherfujino) [reply dev/conductor/lib/repository.dart:797]: 1. the benefit for the conductor living in the framework is so that it's knowledge of the Flutter SDK is inherently versioned with the SDK. For example, it has a hard-coded list of binaries that live in the tool cache that should be codesigned: https://github.com/flutter/flutter/blob/master/dev/conductor/lib/codesign.dart#L137.
2. it wouldn't be too hard to hook up to the conductor the ability to run scripts from `cocoon/app_dart/bin`. However, if we started doing this, I'd probably want to start pinning a cocoon version, at the minimal for the benefit of the conductor. Or have something like a linearized flutter revision list.

Comment (CaseyHillers) [reply dev/conductor/lib/repository.dart:797]: 2. This is fine. If there's enough feature requests, we can refactor a more portable `package:ci_yaml` for us to pass around.

Comment (christopherfujino) [reply dev/conductor/lib/repository.dart:797]: Hopefully without any pub deps, as the framework transitive deps situation is already a pain.
