### PR TITLE
fix some DSS bugs

### LINKED ISSUE #112020: Cast Error thrown from DraggableScrollableSheet
b/247858428

Customer reporting error being thrown when providing a DraggableScrollableController to DraggableScrollableSheet.

I have not been able to reproduce this crash yet.
There is a notification listener that is swapping out the DraggableScrollableSheet when it reaches the fully expanded state, and it is in _onExtentReplaced where the `_attachedController!` is throwing.

https://github.com/flutter/flutter/blob/6e491d887007a307a02b808606f15a7924d9a548/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L196

This is the redacted stack trace from the customer:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building NotificationListener<DraggableScrollableNotification>:
Null check operator used on a null value

The relevant error-causing widget was:
  NotificationListener<DraggableScrollableNotification>
  NotificationListener ... **redacted** ...

When the exception was thrown, this was the stack:
#0      DraggableScrollableController._onExtentReplaced (package:[flutter/src/widgets/draggable_scrollable_sheet.dart:195]
#1      _DraggableScrollableSheetState._replaceExtent (package:[flutter/src/widgets/draggable_scrollable_sheet.dart:732]
#2      _DraggableScrollableSheetState.didUpdateWidget (package:[flutter/src/widgets/draggable_scrollable_sheet.dart:675]
#3      StatefulElement.update (package:[flutter/src/widgets/framework.dart:5069]
#4      Element.updateChild (package:[flutter/src/widgets/framework.dart:3590]
#5      RenderObjectElement.updateChildren (package:[flutter/src/widgets/framework.dart:5908]
... **redacted**
```

Here is the sample code I have been trying (unsuccessfully) to reproduce this crash with:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _controller = DraggableScrollableController();
  bool useExpanded = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('DraggableScrollableSheet'),
      ),
      body: NotificationListener<DraggableScrollableNotification>(
        onNotification: (scrollNotification) {
            if (scrollNotification.extent == scrollNotification.minExtent) {
              print('Fully closed');
              setState((){ useExpanded = false; });
            } else if (scrollNotification.extent == scrollNotification.maxExtent) {
              print('Fully expanded');
              setState((){ useExpanded = true; });
            }
            return true;
          },
        child: !useExpanded
        ? DraggableScrollableSheet(
          initialChildSize: 0.25,
          minChildSize: 0.25,
          controller: _controller,
          snap: true,
          snapSizes: const <double>[0.25, 1.0],
          builder: (BuildContext context, ScrollController scrollController) {
            return Container(
              color: Colors.red[100],
              child: ListView.builder(
                controller: scrollController,
                itemCount: 25,
                itemBuilder: (BuildContext context, int index) {
                  return ListTile(title: Text('Item $index'));
                },
              ),
            );
          },
        )
        : DraggableScrollableSheet(
          initialChildSize: 1,
          minChildSize: 0.25,
          controller: _controller,
          snap: true,
          snapSizes: const <double>[0.25, 1.0],
          builder: (BuildContext context, ScrollController scrollController) {
            return Container(
              color: Colors.blue[100],
              child: ListView.builder(
                controller: scrollController,
                itemCount: 25,
                itemBuilder: (BuildContext context, int index) {
                  return Container(height: 50, child: Text('Item $index'));
                },
              ),
            );
          },
        ),
      ),
    );
  }
}

```

@xu-baolin does anything jump out at you here?

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #112020 
This is a further improvement of #111445, and fixes two issues,

1. The new controller cannot be subscribed to;
2. The old extent will have memory leaks.

 CC @moffatman @Piinks

### CODE REVIEW

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 1]
```diff
@@ -719,9 +727,9 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
     _scrollController.extent = _extent;
     // If an external facing controller was provided, let it know that the
     // extent has been replaced.
-    if (widget.controller == oldWidget.controller) {
-      widget.controller?._onExtentReplaced(previousExtent);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:723]: Currently, the new controller is also related to the old extent, so we need to switch the callbacks to the new extent.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 2]
```diff
@@ -719,9 +727,9 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
...
-    }
+    widget.controller?._onExtentReplaced(previousExtent);
+    previousExtent.dispose();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:731]: Without this may cause some memory leaks.

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [hunk 3]
```diff
@@ -1516,6 +1516,8 @@ void main() {
   testWidgets('DraggableScrollableSheet controller can be changed', (WidgetTester tester) async {
     final DraggableScrollableController controller1 = DraggableScrollableController();
     final DraggableScrollableController controller2 = DraggableScrollableController();
+    final List<double> loggedSizes = <double>[];
```
Comment (moffatman) [inline packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1519]: Can we have two lists, to verify that the event is not sent to the wrong controller?

Comment (xu-baolin) [reply packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1519]: Actually, the old extent will never trigger an event but keep a reference for the `DraggableScrollableController`.

**Comment by moffatman** [comment]
Can we have a code sample to reproduce the failure, I don't understand how that could have happened, unless the SVG is relying on being rebuilt when only layout is changed? Which is an error in the SVG side.

**Comment by Piinks** [comment]
I am working on trying to get some sample code. The customer code is complex, I am trying to get as simple a repro as possible.

**Comment by Piinks** [comment]
The svg and semantics failures were a red herring.

The customer code takes a different path with these changes. I've been working on the customer code directly to see if I can resolve it on their end, and I think I have it. They are passing widget states around so I am thinking this is a bug in their code, I am chatting with them to see if we can resolve it internally and re-land the changes in #111445 along with this PR.

**Comment by moffatman** [comment]
Before #111010, you would get a rebuild every frame during drag. After that PR you should only get 1 build, at the beginning. It sounds like I guess their SVG was depending on a rebuild to update itself?

**Comment by xu-baolin** [comment]
> Before #111010, you would get a rebuild every frame during drag. After that PR you should only get 1 build, at the beginning. It sounds like I guess their SVG was depending on a rebuild to update itself?

Probably, could you help with reland
 #111010. I will reland #111145 today.

**Comment by moffatman** [comment]
@xu-baolin If you can combine with #111010, i would really appreciate it 😀

**Comment by moffatman** [comment]
OK, but this one contains #111445 already, though, right? So I don't need to reopen that one?

**Comment by xu-baolin** [comment]
Yes, could you help try to relanding #111010?

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/pull/112479 has landed 🎉

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:739]: Nice

**Review by Piinks — APPROVED** [review]
LGTM, although there are some merge conflicts to resolve. Thanks everyone for working to re-land all of these changes
