### PR TITLE
[Impeller] Use device property uniform aligment instead of conservative value of 256.

### LINKED ISSUE #132178: [Impeller] Make uniform buffer offset alignments dynamically calculated.
Today, the [offset alignments are hardcoded](https://github.com/flutter/engine/blob/29b117aa4192fbe1757d98ed37913675ff4390d3/impeller/core/platform.h#L14) and only really make sense for Metal. This must be made dynamic per platform and client rendering API. Without this, applications are susceptible to running into validation errors like:

```
E/flutter ( 7530): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure:
E/flutter ( 7530): --- Vulkan Debug Report  ----------------------------------------
E/flutter ( 7530): |                Severity: Error
E/flutter ( 7530): |                    Type: { Validation }
E/flutter ( 7530): |                 ID Name: VUID-VkWriteDescriptorSet-descriptorType-00327
E/flutter ( 7530): |               ID Number: -36706146
E/flutter ( 7530): |       Queue Breadcrumbs: [NONE]
E/flutter ( 7530): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter ( 7530): |         Related Objects: Device [12970367432599348128] [ImpellerDevice]
E/flutter ( 7530): |                 Trigger: Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00327 ] Object 0: handle = 0xb4000075c26123a0, name = ImpellerDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xfdcfe89e | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (0x340) must be a multiple of device limit minUniformBufferOffsetAlignment 0x100. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00327)
E/flutter ( 7530): -----------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/132178

Rather than 256, use the device limits which may be substantially less. Metal uses existing values and GLES still uses 256.

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]

File: engine/src/flutter/impeller/renderer/backend/gles/capabilities_gles.cc [hunk 1]
```diff
@@ -235,4 +235,8 @@ ISize CapabilitiesGLES::GetMaximumRenderPassAttachmentSize() const {
   return max_texture_size;
 }
 
+size_t CapabilitiesGLES::GetMinimumUniformAlignment() const {
+  return 256;
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/renderer/backend/gles/capabilities_gles.cc:239]: You probably meant to do this in a followup patch. But if not, the general idea is an ivar initialized only on ES 3.0 (where UBO use is possible) with the value of [`glGet*(GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT)`](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glGet.xhtml) and `1u` elsewhere since the uniform uploads are by copy with `glUniform*`.
