### PR TITLE
impeller: makes deferred display list images trash their display lists after they are realized

### LINKED ISSUE #138627: [desktop] toImageSync retains display list which can lead to surprising memory retention
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. run example
2. wait 40~60 to see memory leak on the *OS memory monitor* that is not seen in DevTools

### Actual results

All the PC memory get filled till system crash

### Code sample

I have created a public [GitHub project](https://github.com/alnitak/test_leak) as short as I could.
Some more info in the README.md

### Screenshots or Video

After about 40~60 seconds memory leak is starting growing till it reach 100%.
DevTools memory tab doesn't show memory leaks.

<details>
<summary>Screenshots</summary>

Screenshot from 2023-11-17 16-29-57

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on Manjaro Linux 6.1.62-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/deimos/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/deimos/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/deimos/Android/Sdk
    • ANDROID_SDK_ROOT = /home/deimos/Android/Sdk
    • Java binary at: /home/deimos/dev/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/deimos/dev/android-studio
    • Flutter plugin version 75.1.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.1.62-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Chromium 119.0.6045.159 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/138627

This stops ballooning recursive display_lists that can happen in animations.  The display list actually can be larger than the image so keeping the display list around is no benefit.  In rare cases this could make the memory size of backgrounded apps be larger but this keeps images made with toImageSync have the same semantics as toImage on impeller.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc [hunk 1]
```diff
@@ -123,25 +123,11 @@ DlDeferredImageGPUImpeller::ImageWrapper::ImageWrapper(
...
-DlDeferredImageGPUImpeller::ImageWrapper::~ImageWrapper() {
-  fml::TaskRunner::RunNowOrPostTask(
-      raster_task_runner_, [id = reinterpret_cast<uintptr_t>(this),
-                            texture_registry = std::move(texture_registry_)]() {
-        if (texture_registry) {
-          texture_registry->UnregisterContextListener(id);
-        }
-      });
-}
+DlDeferredImageGPUImpeller::ImageWrapper::~ImageWrapper() {}
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: nit: use `~ImageWrapper() = default`

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc [hunk 2]
```diff
@@ -151,36 +137,35 @@ void DlDeferredImageGPUImpeller::ImageWrapper::SnapshotDisplayList(
...
+            }
+            auto snapshot_delegate = wrapper->snapshot_delegate_;
+            if (!snapshot_delegate) {
+              return;
+            }
+
+            std::shared_ptr<TextureRegistry> texture_registry =
+                snapshot_delegate->GetTextureRegistry();
+            if (layer_tree) {
+              wrapper->display_list_ = layer_tree->Flatten(
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: With this change `ImageWrapper` should no longer need to hold `display_list_` as a member.

`SnapshotDisplayList` could take a `variant<DisplayList, LayerTree>` and move the argument into the raster thread task.  The display list will then be destructed when the task exits.

**Review by jason-simmons — COMMENTED** [review]
One potential issue is that this may result in usages of `toImageSync` that are safe when using Impeller but consume excessive resources on platforms that are still using Skia.  App developers will need to be aware of this as long as Skia remains in use.

@chinmaygarde

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: done, just passed them both in

**Comment by gaaclarke** [comment]
> One potential issue is that this may result in usages of `toImageSync` that are safe when using Impeller but consume excessive resources on platforms that are still using Skia. App developers will need to be aware of this as long as Skia remains in use.

I think that's fine because this isn't the only place this happens.  Impeller was created with the intention to be a renderer with better performance for Flutter's use case.  That means there are all sorts of usages that are supposed to be better on impeller than on skia.  We don't want logical changes, but performance changes are expected.

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc [hunk 3]
```diff
@@ -119,40 +121,27 @@ DlDeferredImageGPUImpeller::ImageWrapper::ImageWrapper(
...
-  texture_.reset();
-}
+void DlDeferredImageGPUImpeller::ImageWrapper::OnGrContextDestroyed() {}
 
 bool DlDeferredImageGPUImpeller::ImageWrapper::isTextureBacked() const {
   return texture_ && texture_->IsValid();
 }
 
 void DlDeferredImageGPUImpeller::ImageWrapper::SnapshotDisplayList(
+    sk_sp<DisplayList> display_list,
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: Declare this parameter as a `std::variant` to indicate that this takes either a `DisplayList` or a `LayerTree` but not both.

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h [hunk 4]
```diff
@@ -106,7 +111,8 @@ class DlDeferredImageGPUImpeller final : public DlImage {
     // thread task spawned by this method. After being flattened into a display
     // list, the image wrapper will be updated to hold this display list and the
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h]: Delete the part of this comment saying that the image wrapper will hold the display list.

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc [hunk 5]
```diff
@@ -163,17 +152,15 @@ void DlDeferredImageGPUImpeller::ImageWrapper::SnapshotDisplayList(
...
-            reinterpret_cast<uintptr_t>(wrapper.get()), weak_this);
-
+        std::shared_ptr<TextureRegistry> texture_registry =
+            snapshot_delegate->GetTextureRegistry();
         if (layer_tree) {
-          wrapper->display_list_ = layer_tree->Flatten(
+          display_list = layer_tree->Flatten(
               DlRect::MakeWH(wrapper->size_.width, wrapper->size_.height),
-              wrapper->texture_registry_);
+              texture_registry);
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: The `texture_registry` variable can be removed and `snapshot_delegate->GetTextureRegistry()` can be passed here

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller_unittests.cc [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+#include "gmock/gmock.h"
+#include "gtest/gtest.h"
+#include "impeller/core/texture_descriptor.h"
+#include "impeller/renderer/testing/mocks.h"
+
+namespace flutter {
+namespace testing {
+namespace {
+
+void PostTaskSync(const fml::RefPtr<fml::TaskRunner>& task_runner,
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller_unittests.cc]: Remove the local version of this function and use the one from `#include "flutter/testing/post_task_sync.h"`

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc [hunk 7]
```diff
@@ -119,40 +121,27 @@ DlDeferredImageGPUImpeller::ImageWrapper::ImageWrapper(
     fml::TaskRunnerAffineWeakPtr<SnapshotDelegate> snapshot_delegate,
     fml::RefPtr<fml::TaskRunner> raster_task_runner)
     : size_(size),
-      display_list_(std::move(display_list)),
```
Comment (jason-simmons) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc:122]: Remove the `display_list` parameter from the `ImageWrapper` constructor

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller_unittests.cc (hunk 6 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller_unittests.cc]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc (hunk 5 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc (hunk 7 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.cc:122]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h (hunk 4 above)
Comment (gaaclarke) [reply engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h]: done

File: engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h [hunk 8]
```diff
@@ -86,27 +93,24 @@ class DlDeferredImageGPUImpeller final : public DlImage {
...
 
-    // If a layer tree is provided, it will be flattened during the raster
-    // thread task spawned by this method. After being flattened into a display
-    // list, the image wrapper will be updated to hold this display list and the
-    // layer tree can be dropped.
-    void SnapshotDisplayList(std::unique_ptr<LayerTree> layer_tree = nullptr);
+    // If a layer tree is provided, it will be flattened into a display list
+    // during the raster thread task spawned by this method.
+    void SnapshotDisplayList(
+        std::variant<sk_sp<DisplayList>, std::unique_ptr<LayerTree>> content);
```
Comment (gaaclarke) [inline engine/src/flutter/lib/ui/painting/display_list_deferred_image_gpu_impeller.h:113]: Looking at this now, we probably should have just overloaded the constructor. Oh well, that was fun.

**Review by jason-simmons — APPROVED** [review]
