### PR TITLE
Fixes column text width calculation in CupertinoDatePicker

### LINKED ISSUE #110319: CupertinoDatePicker in Arabic showing months in wrong way
CupertinoDatePicker show us months in arabic wrong 

CupertinoDatePicker shows months in arabic not completed for example january showing it janua 
but in arabic. example in arabic "اغسطس"  showing it to "غسط"

snippet of the code:

`showCupertinoModalPopup(
        context: ctx,
        builder: (_) => Container(
          height: 190,
          color: const Color.fromARGB(255, 255, 255, 255),
          child: Column(
            children: [
              SizedBox(
                height: 180,
                child: CupertinoDatePicker(
                  mode: CupertinoDatePickerMode.date,
                  initialDateTime: DateTime.now(),
                    onDateTimeChanged: (value) {
                      debugPrint('value ==> $value');
                      setState(() {
                        _expiredDate = value.toLocal();
                      });
                    },

                ),
              ),
            ],
          ),
        ));`

### LINKED ISSUE #138305: [CupertinoDatePicker] Showing months incorrectly in pt-br
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just create an app with supportedLocales: const [Locale('pt', 'BR')], and use CupertinoDatePicker

### Expected results

I think that the expected result is the month word shown correctly, maybe we can calculate the size of the word instead of the length of the word.

### Actual results

Currently, CupertinoDatePicker is calculating the space of the month column based on the longestText. In pt-br the longer month is Fevereiro but Dezembro is larger in space because we have larger letters. With that, the CupertinoDatePicker is cutting the month word. Even if we set dateOrder mdy or dmy, the problem persists. 

Screenshot 2023-11-11 at 16 57 40

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes #138305 
Fixes #110319

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by Piinks** [comment]
Thank you for your contribution. This PR will need tests before we can review it. Thanks! If you are not sure how to write tests, the #hackers-new channel on our Discord is available for new contributors seeking guidance.

**Comment by MitchellGoodwin** [comment]
Another PR with a different implementation was filed here: #151142

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 1]
```diff
@@ -542,15 +563,16 @@ class CupertinoDatePicker extends StatefulWidget {
           final String month = standaloneMonth
               ? localizations.datePickerStandaloneMonth(i)
               : localizations.datePickerMonth(i);
-          if (longestText.length < month.length) {
-            longestText = month;
-          }
+          _updateLongestTexts(month, longestTexts);
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/date_picker.dart:566]: Probably better to run `_updateLongestTexts` once rather than every time through the loop. Make a list of strings of all the months then run it through once. That way we aren't making 12 SplayTreeSets unnecessarily.

File: packages/flutter/test/painting/text_painter_test.dart [hunk 2]
```diff
@@ -1740,3 +1788,19 @@ class MockCanvasWithDrawParagraph extends Fake implements Canvas {
     centerX = offset.dx + paragraph.width / 2;
   }
 }
+
+// Load the font used in the test.
+Future<void> _loadFont() async {
```
Comment (MitchellGoodwin) [inline packages/flutter/test/painting/text_painter_test.dart:1793]: @LongCatIsLooong how does this look for loading a different font from the test one? [Looks like this is what we recommend to do](https://github.com/flutter/flutter/blob/master/docs/contributing/testing/Flutter-Test-Fonts.md), but it feels flacky.

File: packages/flutter/test/painting/text_painter_test.dart [hunk 3]
```diff
@@ -1726,6 +1744,36 @@ void main() {
       areCreateAndDispose,
     );
   });
+
+  testWidgets('TextPainter computeWidth should return the longest width for the longest word with Material font', (WidgetTester tester) async {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:1748]: I'm not sure what this is verifying? `getWidestWord` seems to be a method defined in the test file?

Comment (LongCatIsLooong) [reply packages/flutter/test/painting/text_painter_test.dart:1748]: Also I'm not sure the material icons font has latin glyphs. If not then all these characters will be replaced by the `.notDef` glyph so `IIIII` and `WWWW` would just have the same width.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 4]
```diff
@@ -497,69 +498,83 @@ class CupertinoDatePicker extends StatefulWidget {
...
         style: _themeTextStyle(context),
-        text: longestText,
       ),
       textDirection: Directionality.of(context),
     );
   }
+
+  // Get maximum three texts from the date picker texts.
+  // This is used to get the longest words from the date picker texts.
+  static List<String> _getLongestTexts(List<String> longestTexts) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/date_picker.dart:571]: I'm no linguist, but this doesn't seem right:

1. Some characters in the localized text may have a length of 2 (instead of one) in UTF16: https://en.wikibooks.org/wiki/Unicode/Character_reference/10000-10FFF
2. why 3 specifically?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 5]
```diff
@@ -30,6 +30,7 @@ import 'text_span.dart';
 import 'text_style.dart';
 
 export 'dart:ui' show LineMetrics;
+
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:33]: remove extraneous line?

**Review by LongCatIsLooong — COMMENTED** [review]
I feel `_getColumnWidth` is a lost cause at this point. Would it be possible to switch to using [IntrinsicWidth](https://main-api.flutter.dev/flutter/widgets/IntrinsicWidth-class.html) for the column width?

**Comment by Mairramer** [comment]
@MitchellGoodwin @LongCatIsLooong I made some changes. One problem is that I need to add a new font to the artifacts (Tajawal). I did local tests with it.

**Comment by MitchellGoodwin** [comment]
> One problem is that I need to add a new font to the artifacts (Tajawal). I did local tests with it.

I think if we just tested against Portuguese, that would be sufficient. The problem is that text with longer displays than a word with more characters causes clipping, not those languages in particular. If local testing works I don't think it's worth adding to the artifacts.

@Mairramer did you try `IntrinsicWidth` per @LongCatIsLooong 's suggestion. I'm curious if that would work as well.

**Comment by Mairramer** [comment]
> suggestion. I'm curious if that would work as well.
I tested it but I was a little apprehensive. I will create another PR draft with these changes (When I recover the changes I had made), if necessary.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 6]
```diff
@@ -479,86 +479,91 @@ class CupertinoDatePicker extends StatefulWidget {
...
       ),
       textDirection: Directionality.of(context),
-    );
+    )..layout();
+    return textPainter.size.width;
+  }
+
+  // Helper function to find the maximum width from a list of strings.
+  double maxTextWidth(List<String> texts) {
+    return texts.map(measureTextWidth).reduce((double a, double b) => a > b ? a : b);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/date_picker.dart:504]: uber-nit: `.reduce(math.max)` for style points and readability?

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 7]
```diff
@@ -479,86 +479,91 @@ class CupertinoDatePicker extends StatefulWidget {
...
+static double _getColumnWidth(
+  _PickerColumnType columnType,
+  CupertinoLocalizations localizations,
+  BuildContext context,
+  bool showDayOfWeek, {
+  bool standaloneMonth = false,
+}) {
+  // Helper function to measure the width of a given text.
+  double measureTextWidth(String text) {
+    final TextPainter textPainter = TextPainter(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/date_picker.dart:492]: The text painter is not disposed. Consider using the static helper function in the original implementation.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 8]
```diff
@@ -479,86 +479,91 @@ class CupertinoDatePicker extends StatefulWidget {
...
+  // Helper function to find the maximum width from a list of strings.
+  double maxTextWidth(List<String> texts) {
+    return texts.map(measureTextWidth).reduce((double a, double b) => a > b ? a : b);
+  }
+
+  switch (columnType) {
+    case _PickerColumnType.date:
+      final List<String> dates = <String>[
+        for (int i = 1; i <= 12; i++)
+          localizations.datePickerMediumDate(DateTime(2018, i, 25))
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/date_picker.dart:511]: You have to find the longest date + month combination I think? Here the method is supposed to return the width of `year + month + day` right?

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 9]
```diff
@@ -2414,6 +2418,74 @@ void main() {
...
+        return Center(
+          child: CupertinoDatePicker(
+              mode: CupertinoDatePickerMode.monthYear,
+              onDateTimeChanged: (DateTime date) {},
+              initialDateTime: DateTime(2018, 11, 15)),
+        );
+      }),
+    ));
+
+    // pump twice required for loading localization
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/date_picker_test.dart:2451]: I'm curious as to why it takes 2 frames to load the localization?

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/date_picker.dart:492]: Or reuse the text painter

**Review by LongCatIsLooong — COMMENTED** [review]
Overall I'm ok with this approach, as long as it fixes the bug, and is not prohibitively slow (which I'm afraid it could be, does `_getColumnWidth` get called in every rebuild?).

So for the minute column alone, 60 paragraphs have to be shaped and laid out, that would be 60x slower than the original implementation.

File: packages/flutter/test/cupertino/date_picker_test.dart (hunk 9 above)
Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart]: This occurred because I was taking the measurements in each case and not at the end.

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 8 above)
Comment (Mairramer) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: Really. But I adjusted the logic again, to avoid errors.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 10]
```diff
@@ -479,86 +479,75 @@ class CupertinoDatePicker extends StatefulWidget {
...
+      longTexts.add(localizations.datePickerYear(2018));
+  }
 
-    assert(longestText != '', 'column type is not appropriate');
+  assert(longTexts.isNotEmpty, 'column type is not appropriate');
 
-    return TextPainter.computeMaxIntrinsicWidth(
+  final List<String> texts = (List<String>.from(longTexts)
+      ..sort((String a, String b) => b.length.compareTo(a.length)))
+      .take(4)
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/date_picker.dart:541]: Why 4 specifically?

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 11]
```diff
@@ -2414,6 +2418,72 @@ void main() {
 
     expect(find.byType(CupertinoPickerDefaultSelectionOverlay), findsExactly(4));
   });
+
+  testWidgets('CupertinoDatePicker month column width validation in Portuguese', (WidgetTester tester) async {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/date_picker_test.dart:2422]: This test can be a bit brittle. I would expose `_getColumnWidth` as visibleForTesting and test the implementation instead.

Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/date_picker_test.dart:2422]: or expose a test-only method to set the text in tests instead of depending on localization and the material font

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 10 above)
Comment (Mairramer) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: I considered that, on average, alphabetic and syllabic languages ​​tend to have 2-3 month names that are relatively long, while logographic and ideographic languages ​​also tend to have about 2 month names that are longer. Since abbreviations generally do not vary much in character count, I decided to select only 4 words for optimization.

I can't say for sure, but I think it's plausible.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: > tend to have about 2 month names that are longer

You can use a font with wide glyphs for certain code points. As a pathological example, I can make one character 5 times as wide as other characters, or make the advance of a character sequence much smaller with kerning or making it a ligature.

Comment (Mairramer) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: Okay, I'll try to do that.

**Comment by Piinks** [comment]
Hey @Mairramer it looks like this might need a rebase to fix the ci.yaml check

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 12]
```diff
@@ -487,78 +487,75 @@ class CupertinoDatePicker extends StatefulWidget {
...
-          }
+          longTexts.add(month);
         }
       case _PickerColumnType.year:
-        longestText = localizations.datePickerYear(2018);
+        longTexts.add(localizations.datePickerYear(2018));
     }
 
-    assert(longestText != '', 'column type is not appropriate');
+    assert(longTexts.isNotEmpty, 'column type is not appropriate');
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/date_picker.dart:537]: I'm not sure this is equivalent to the previous logic. If empty strings are repeatedly added to the list, wouldn't the list be non-empty?

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 13]
```diff
@@ -487,78 +487,75 @@ class CupertinoDatePicker extends StatefulWidget {
...
+          longTexts.add(dayOfMonth);
+          longestDayOfMonth = i;
         }
         if (showDayOfWeek) {
           for (int wd = 1; wd < DateTime.daysPerWeek; wd++) {
-            final String dayOfMonth = localizations.datePickerDayOfMonth(longestDayOfMonth, wd);
-            if (longestText.length < dayOfMonth.length) {
-              longestText = dayOfMonth;
-            }
+            final String dayOfMonth =
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/date_picker.dart:521]: Nit: Prefer avoiding line breaks after assignment operators: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#prefer-a-maximum-line-length-of-80-characters

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 14]
```diff
@@ -487,78 +487,75 @@ class CupertinoDatePicker extends StatefulWidget {
...
-    );
+    return getColumnWidth(texts: longTexts, context: context);
+  }
+
+  /// Returns the width of column in the picker.
+  ///
+  /// This method is intended for testing only. It calculates the width of the
+  /// widest column in the picker based on the provided list of texts and the
+  /// given [BuildContext].
+  @visibleForTesting
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/date_picker.dart:547]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-using-visiblefortesting

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 12 above)
Comment (Mairramer) [reply packages/flutter/lib/src/cupertino/date_picker.dart:537]: Oh yes, indeed.

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 14 above)
Comment (Mairramer) [reply packages/flutter/lib/src/cupertino/date_picker.dart:545]: In this case, I believe it is difficult to escape this. There are other ways, but this is the most concise.
I followed the recommendation in the comment https://github.com/flutter/flutter/pull/151128#discussion_r1735094255

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 15]
```diff
@@ -2414,6 +2414,50 @@ void main() {
...
+      if (textPainter.size.width > textPainter.size.height) {
+        largestWord = text;
+      }
+      return textPainter.size.width;
+    }
+
+    final double largestWidth = testWords.map(getColumnWidth).reduce((double a, double b) => a > b ? a : b);
+
+    // Get the width of the largest word in the testWords list.
+    final double testWidth =CupertinoDatePicker.getColumnWidth(texts: testWords, context: context);
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/date_picker_test.dart:2455]:
```suggestion
    final double testWidth = CupertinoDatePicker.getColumnWidth(texts: testWords, context: context);
```

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 16]
```diff
@@ -2414,6 +2414,50 @@ void main() {
 
     expect(find.byType(CupertinoPickerDefaultSelectionOverlay), findsExactly(4));
   });
+
+  testWidgets('CupertinoDatePicker getColumnWidth', (WidgetTester tester) async {
+    const List<String> testWords = <String>[
+      'aaaaaii',    // Narrow characters - 7 characters
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/date_picker_test.dart:2420]: All these characters should have the exact same advance: https://github.com/flutter/flutter/blob/master/docs/contributing/testing/Flutter-Test-Fonts.md#glyph-mapping

So I would expect 'aaaaaii' to have a larger width than `WWWWWW`.

Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/date_picker_test.dart:2420]: Consider using characters that are mapped to glyphs with <= 1 EM advance.

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 17]
```diff
@@ -2414,6 +2414,50 @@ void main() {
...
+
+    // Use CupertinoTheme to get the text style used in the picker.
+    final TextStyle textStyle = CupertinoTheme.of(context).textTheme.dateTimePickerTextStyle;
+
+    double getColumnWidth(String text) {
+      final TextPainter textPainter = TextPainter(
+        text: TextSpan(text: text, style: textStyle),
+        textDirection: TextDirection.ltr,
+      )..layout();
+      if (textPainter.size.width > textPainter.size.height) {
```
[the remark this answers is not in the document]
Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart:2446]: an error, which gave a false positive in the test.

File: packages/flutter/test/cupertino/date_picker_test.dart (hunk 16 above)
Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart]: Fixed. My test was giving false positive.

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 18]
```diff
@@ -2414,6 +2415,41 @@ void main() {
 
     expect(find.byType(CupertinoPickerDefaultSelectionOverlay), findsExactly(4));
   });
+
+  testWidgets('CupertinoDatePicker getColumnWidth', (WidgetTester tester) async {
+    const List<String> testWords = <String>[
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/date_picker_test.dart:2420]: What is this test verifying? I thought for this bug fix we want to verify that `CupertinoDatePicker.getColumnWidth` works correctly when text with fewer characters is actually longer than text with more characters?

Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/date_picker_test.dart:2420]: The test should fail without the patch. But it doesn't seem to be the case?

Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart:2425]: I have some doubts about this. I tried to check if the difference is caused by the automatically applied kerning, but I didn't find anything specific. After adding the Roboto font, I got the following results:
|Word   | Roboto (width) | CupertinoSystemDisplay (width) |
|-----------|------------------|----------------------------------|
| February  | 85.0             | 171.0                            |
| November  | 100.0            | 171.0                            |
| Fevereiro | 89.0             | 193.0                            |
| Novembro  | 100.0            | 171.0                            |



### LineMetrics 

| Field               | CupertinoSystemDisplay                        | Roboto                             |
|---------------------|--------------------------------------|---------------------------------------|
| **hardBreak**       | `true`                                | `true`                                 |
| **ascent**          | `15.75`                               | `19.482421875`                         |
| **descent**         | `5.25`                                | `5.126953125`                          |
| **unscaledAscent**  | `15.75`                               | `19.482421875`                         |
| **height**          | `21.0`                                | `25.0`                                 |
| **width**           | `85.5999984741211`                    | `36.852928161621094`                   |
| **left**            | `0.20000000298023224`                 | `0.20000000298023224`                  |
| **baseline**        | `15.75`                               | `19.873046875`                         |
| **lineNumber**      | `0`                                   | `0`                                    |

Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/date_picker_test.dart:2425]: In tests typically the test fonts are used, not the real fonts.

Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/date_picker_test.dart:2425]: I wouldn't recommend loading fonts from `flutterRoot.childFile(fs.path.join('bin', 'cache', 'artifacts', 'material_fonts', fontPath));`. The default test font has some characters with smaller x-advances. You can try those called "1/x Advance` glyphs.

Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart]: I believe I have now achieved the result I was hoping for.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 19]
```diff
@@ -2414,6 +2415,50 @@ void main() {
...
+
+    final double testWidth = CupertinoDatePicker.getColumnWidth(
+      texts: testWords,
+      context: context,
+      textStyle: textStyle,
+    );
+
+    expect(testWidth, equals(largestWidth));
+    expect(widths.indexOf(largestWidth), equals(1));
+  }, skip: isBrowser); // https://github.com/flutter/flutter/issues/39998
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/date_picker_test.dart:2461]: I think you just have to skip the html renderer in this case?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM modulo the test's skip condition

File: packages/flutter/test/cupertino/date_picker_test.dart (hunk 19 above)
Comment (Mairramer) [reply packages/flutter/test/cupertino/date_picker_test.dart]: Remnant of the old test. Solved.
