### PR TITLE
ListTile fix MinIntrinsicHeight calculation

### LINKED ISSUE #179377: `ListTile` intrinsic height incorrectly returns `minTileHeight` instead of actual content height
### Description

When `ListTileThemeData.minTileHeight` is set in the theme, `ListTile` reports its intrinsic height as the `minTileHeight` value rather than its actual content height. This causes a `RenderFlex overflow` when `ListTile` is used inside an `IntrinsicHeight` widget, because `IntrinsicHeight` constrains the layout to 35px while the actual `ListTile` content requires ~40px.

The `minTileHeight` property should act as a **minimum constraint**, not override the intrinsic height calculation. When content exceeds `minTileHeight`, the intrinsic height should reflect the actual content size.

### Steps to Reproduce

1. Set `ListTileThemeData(minTileHeight: 35)` in the app theme
2. Place a `ListTile` inside `Column → IntrinsicHeight → Row → Expanded → Column`
3. Run the app

### Expected Behavior

`IntrinsicHeight` calculates the true intrinsic height of `ListTile` (~40px) and no overflow occurs.

### Actual Behavior

`IntrinsicHeight` uses `minTileHeight` (35px) as the intrinsic height, causing a 5px overflow.

```
A RenderFlex overflowed by 5.0 pixels on the bottom.
constraints: BoxConstraints(w=600.0, 0.0<=h<=35.0)
size: Size(600.0, 35.0)
```

### Minimal Reproduction Code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        listTileTheme: ListTileThemeData(minTileHeight: 35),
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return const Material(
      type: MaterialType.transparency,
      child: Column(
        children: [
          IntrinsicHeight(
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    children: [ListTile(title: Text('item.label'))],
                  ),
                ),
                Expanded(
                  child: Column(
                    children: [ListTile(title: Text('item.label'))],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

### Flutter Doctor Output

```
[✓] Flutter (Channel stable, 3.38.3, on macOS 15.6 24G84 darwin-arm64 (Rosetta), locale en-AU)
    • Flutter version 3.38.3 on channel stable at /Users/eric/development/flutter
    • Framework revision 19074d12f7 (2025-11-20)
    • Engine revision 13e658725d
    • Dart version 3.10.1
    • DevTools version 2.51.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1)
[✓] Chrome - develop for the web
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

### Platform

Tested on Chrome (web)

### PR DESCRIPTION
**Pull request by RamonFarizel**
`computeMinIntrinsicHeight` was not taking into consideration the vertical padding.

Fix: https://github.com/flutter/flutter/issues/179377

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
This LGTM! Thank you for contributing! 💙

File: packages/flutter/lib/src/material/list_tile.dart [hunk 1]
```diff
@@ -1449,10 +1449,16 @@ class _RenderListTile extends RenderBox
...
   @override
   double computeMinIntrinsicHeight(double width) {
-    return math.max(
-      _targetTileHeight,
-      title.getMinIntrinsicHeight(width) + (subtitle?.getMinIntrinsicHeight(width) ?? 0.0),
-    );
+    final double titleMinHeight = title.getMinIntrinsicHeight(width);
+    final double? subtitleMinHeight = subtitle?.getMinIntrinsicHeight(width);
+
+    const topAndBottomPaddingMultiplier = 2;
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/list_tile.dart:1455]: Nit: I don't know that this variable needs to be defined, it seems obvious to me that padding will need to be applied both above and below the title + subtitle block.

**Review by victorsanni — APPROVED** [review]
