### PR TITLE
Fix gesture recognizer in selectable rich text should be focusable in…

### LINKED ISSUE #77219: SelectableText.rich() with VoiceOver does not allow user to focus on tappable links.
Same issue as https://github.com/flutter/flutter/issues/20643, except for the SelectableText.rich() widget. 

The TaggedText widget returns a RichText or SelectableText.rich() widget, based on if selectableText is set to true. In the case that it returns a RichText, the accessibility works as intended, but in the other case, the bug is exactly the same as the linked one: users cannot focus on the links in the text.

For instance: 
          TaggedText(
            selectableText: true,
            content: 'Example of string with <a href="#"> link </a>'
            onTapLink: someFunction (),
),

In this case navigating the app by voiceover does not allow the users to focus on the tappable link.

Internal: b/172313464

### PR DESCRIPTION
**Pull request by chunhtai**
… assistive technologies

This PR breaks rendereditable into multiple semantics node if its inline span contains gesture recognizer.

fixes https://github.com/flutter/flutter/issues/77219

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
This PR discard the selection and selection handle in semantics since our current framework cannot support selection across multiple semantics node.This is not needed in mobile which i have verified there isn't a way to set selection on selectable text in chrome using talkback/voiceover. We will need this for desktop eventually, but that support multiple widgets/semantics nodes selection is a bigger project.

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -938,15 +903,15 @@ class RenderParagraph extends RenderBox
...
+    for (final InlineSpanSemanticsInformation info in combineSemanticsInfo(_semanticsInfo!)) {
       final TextSelection selection = TextSelection(
         baseOffset: start,
         extentOffset: start + info.text.length,
       );
       start += info.text.length;
 
       if (info.isPlaceholder) {
-        // A placeholder span may have 0 to multple semantics nodes, we need
+        // A placeholder span may have 0 to multiple semantics nodes, we need
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/paragraph.dart:914]: 👍 👀

File: packages/flutter/lib/src/painting/inline_span.dart [hunk 2]
```diff
@@ -100,6 +100,42 @@ class InlineSpanSemanticsInformation {
   String toString() => '${objectRuntimeType(this, 'InlineSpanSemanticsInformation')}{text: $text, semanticsLabel: $semanticsLabel, recognizer: $recognizer}';
 }
 
+/// Combines _semanticsInfo entries where permissible.
+///
+/// Consecutive inline spans can be combined if their
+/// [InlineSpanSemanticsInformation.requiresOwnNode] return false.
+List<InlineSpanSemanticsInformation> combineSemanticsInfo(List<InlineSpanSemanticsInformation> infoList) {
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/inline_span.dart:107]: Has the logic here changed from the original _combineSemanticsInfo, or was it just moved?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -1474,10 +1475,29 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+
   @override
   void describeSemanticsConfiguration(SemanticsConfiguration config) {
     super.describeSemanticsConfiguration(config);
-
+    _semanticsInfo = _textPainter.text!.getSemanticsInformation();
+    if (_semanticsInfo!.any((InlineSpanSemanticsInformation info) => info.recognizer != null)) {
+      assert(readOnly && !obscureText);
+      // For Selectable rich text with recognizer, we need to create semantics
+      // node for each text fragments.
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:1495]: Nit: 

```diff
- we need to create semantics node for each text fragments.
+ we need to create a semantics node for each text fragment.
```

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -1507,6 +1527,87 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+      }
+      // Any of the text boxes may have had infinite dimensions.
+      // We shouldn't pass infinite dimensions up to the bridges.
+      rect = Rect.fromLTWH(
+        math.max(0.0, rect.left),
+        math.max(0.0, rect.top),
+        math.min(rect.width, constraints.maxWidth),
+        math.min(rect.height, constraints.maxHeight),
+      );
+      // round the current rectangle to make this API testable and add some
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:1566]: "round" => "Round"

File: packages/flutter/lib/src/rendering/editable.dart [hunk 5]
```diff
@@ -1507,6 +1527,87 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+      if (recognizer != null) {
+        if (recognizer is TapGestureRecognizer) {
+          if (recognizer.onTap != null) {
+            configuration.onTap = recognizer.onTap;
+            configuration.isLink = true;
+          }
+        } else if (recognizer is DoubleTapGestureRecognizer) {
+          if (recognizer.onDoubleTap != null) {
+            configuration.onTap = recognizer.onDoubleTap;
+            configuration.isLink = true;
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:1588]: Why is isLink true for double tap but not for long press?  Is there always a long press recognizer because that's how you select text?

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I admit I'm no expert on semantics.  Most of my comments are just nits and questions to help me follow this better.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 6]
```diff
@@ -1474,10 +1475,34 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+
   @override
   void describeSemanticsConfiguration(SemanticsConfiguration config) {
     super.describeSemanticsConfiguration(config);
-
+    _semanticsInfo = _textPainter.text!.getSemanticsInformation();
+    // TODO(chunhtai): the macOS does not provide a public API to support text
+    // selections across multiple semantics nodes. Remove this platform check
+    // once we can support it.
+    // https://github.com/flutter/flutter/issues/77957
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:1495]: I have to make a fairly ugly compromise which i think we don't have a choice at the moment.

Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1495]: It seems like this is the right choice because it would be a much bigger change to get it working like on native Mac, but let me know if I understand correctly:

So selecting some regular text and a link together would be an example of the problem, right?

Screen Shot 2021-03-11 at 12 26 06 PM

On most platforms, this situation can't happen, because they can't select text using a screen reader?  What happens on native Mac in this case?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1495]: Yes selecting regular text and link will be a problem

for screen reader in macOS, you use keyboard to change your accessibility focus. your mouse work as usual, so you can still select text and screen reader announce your selections. I am not entirely sure whether this is the same case for windows so I only disable macOS for now.

The native behavior is quite strange, it look as if it created a semantics object just for the selection. See the black box in the picture.

Screen Shot 2021-03-10 at 5 06 25 PM

I talked to the chromium team about how do they handle this. Their reply is they just uses bunch of private API, and the system will generate those highlight for you. We can't use those private API because it will result in app store rejection.

We can probably hack something in and create the semantics object on our own if there is a selection, but I would like to wait until we finish Windows/Linux part first to get the full picture.

Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1495]: Sounds good, thanks for the explanation!  I'm curious how Windows and Linux do this as well.  Maybe we can create something that works for all 3 instead of needing to exactly copy Windows.

**Review by justinmc — APPROVED** [review]
LGTM with the new changes 👍
