### PR TITLE
Stream logs from `devicectl` and `lldb`

### LINKED ISSUE #173365: [Xcode 26 beta 4/5] idevicesyslog is not streaming logs reliably
At least in Xcode 26 beta 4 and 5, `idevicesyslog` is not working reliably. It sometimes streams the logs and sometimes doesn't. 

`idevicesyslog` is used by Flutter to find the Dart VM url to connect to. However, Flutter also uses mDNS as a fallback for finding the Dart VM.

mDNS is also not reliable, however, especially on macOS 15 (https://github.com/flutter/flutter/issues/150131).

In addition, mDNS can't currently be used in Flutter's CI (https://github.com/flutter/flutter/issues/166843).

If both `idevicesyslog` and mDNS fail to find the Dart VM url, the Flutter CLI will hang

### PR DESCRIPTION
**Pull request by vashworth**
When debugging with `devicectl` and `lldb` (exclusive to Xcode 26+), stream logs from both processes instead of using `idevicesyslog`, which does not work with Xcode 26.

Fixes https://github.com/flutter/flutter/issues/173365.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 1]
```diff
@@ -57,12 +65,10 @@ class IOSCoreDeviceLauncher {
...
-    final bool installSuccess = await _coreDeviceControl.installApp(
-      deviceId: deviceId,
-      bundlePath: bundlePath,
-    );
-    if (!installSuccess) {
-      return installSuccess;
+    final (bool installStatus, IOSCoreDeviceInstallResult? installResult) = await _coreDeviceControl
+        .installApp(deviceId: deviceId, bundlePath: bundlePath);
+    if (!installStatus) {
+      return installStatus;
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart]: Nit: `return false`

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 2]
```diff
@@ -90,34 +96,47 @@ class IOSCoreDeviceLauncher {
...
       deviceId: deviceId,
       bundleId: bundleId,
       launchArguments: launchArguments,
       startStopped: true,
     );
 
-    if (launchResult == null || launchResult.outcome != 'success') {
-      return false;
+    if (!launchResult) {
+      return launchResult;
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart:116]: Ditto

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 3]
```diff
@@ -220,6 +239,10 @@ class IOSCoreDeviceLauncher {
       processToStop = processId;
     }
 
+    // Then kill the attached launch process first so it doesn't process any additional logs when you terminate the app
+    await coreDeviceLogForwarder.exit();
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart]: Nit: Do these need to be cleaned up in order? Using `Future.wait(...)` would probably be slightly more performant here.

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 4]
```diff
@@ -230,6 +253,35 @@ class IOSCoreDeviceLauncher {
   }
 }
 
+/// This class is used to forward logs from devicectl to any active listeners.
+class IOSCoreDeviceLogForwarder {
+  /// The `devicectl` process that launched the app and is streaming the logs.
+  Process? launchProcess;
+
+  final _streamController = StreamController<String>.broadcast();
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart:260]: Just verifying, but is there any chance that `logLines.listen(...)` would be invoked after `addLog(...)` is called? I just want to make sure we're not going to accidentally drop important logs before a listener is registered.

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 5]
```diff
@@ -560,11 +623,45 @@ class IOSCoreDeviceControl {
...
+    List<String> launchArguments = const <String>[],
+    bool startStopped = false,
+  }) async {
+    if (!_xcode.isDevicectlInstalled) {
+      _logger.printTrace('devicectl is not installed.');
+      return null;
+    }
+
+    final Directory tempDirectory = _fileSystem.systemTempDirectory.createTempSync('core_devices.');
+    final File output = tempDirectory.childFile('launch_results.json');
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart]: Ubernit: this can use cascades

```dart
final File output = tempDirectory.childFile('launch_results.json')..createSync();
```

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 6]
```diff
@@ -644,6 +827,68 @@ class IOSCoreDeviceControl {
...
   }
+
+  Future<List<Object?>> _listRunningProcesses({required String deviceId}) async {
+    if (!_xcode.isDevicectlInstalled) {
+      _logger.printTrace('devicectl is not installed.');
+      return <Object?>[];
+    }
+
+    final Directory tempDirectory = _fileSystem.systemTempDirectory.createTempSync('core_devices.');
+    final File output = tempDirectory.childFile('core_device_process_list.json');
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart]: Ditto

File: packages/flutter_tools/lib/src/ios/core_devices.dart [hunk 7]
```diff
@@ -644,6 +827,68 @@ class IOSCoreDeviceControl {
...
+      output.path,
+    ];
+
+    try {
+      await _processUtils.run(command, throwOnError: true);
+
+      final String stringOutput = output.readAsStringSync();
+
+      try {
+        final Object? decodeResult = (json.decode(stringOutput) as Map<String, Object?>)['result'];
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/core_devices.dart]: This can be rewritten with pattern deconstruction:

```dart
  if (json.decode(stringOutput) case <String, Object?>{
    'result': <String, Object?>{
      'runningProcesses': final List<Object?> decodedProcesses,
    },
  }) {
    return decodedProcesses;
  }
  _logger.printTrace('devicectl returned unexpected JSON response: $stringOutput');
  return <Object?>[];
```

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/ios/core_devices.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/core_devices.dart:260]: The listener is set up before the process that streams the logs is started

https://github.com/flutter/flutter/blob/358a5a7f3692542a777f6ae0175b5f82cc359697/packages/flutter_tools/lib/src/ios/devices.dart#L1006-L1015

I also tweaked a test to validate this, though
