### PR TITLE
TextField context menu should fade on scroll on mobile devices

### LINKED ISSUE #52425: Text selection menu should fade during scroll
## Steps to Reproduce

  1. Create a multiline TextField and fill it with more text than it can fit vertically, so that it allows scrolling.
  1. Long press to open the text selection menu.
  1. Scroll the field a bit.
  1. The menu should fade out during scrolling and then fade back in, but it doesn't!

Here is native Android and Flutter side by side (native iOS does the same thing as native Android).

| Native Android | Flutter targeting Android |
| ---- | ---- |
|  |  |

### LINKED ISSUE #52426: In a ListView, the text selection menu doesn't update its orientation during scrolling.
## Steps to Reproduce

  1. Create a long scrollable ListView with a TextField somewhere in the middle.
  1.  Long press the TextField to open the text selection menu. If it has enough room, it should appear above the field.
  1. Scroll the field up so that the menu no longer has enough room. It should redraw itself below the field, but it stays above.

| Native Android Chrome | Flutter |
| ---- | ---- |
| menu_flip | menu_flip_flutter |

### LINKED ISSUE #105804: Tooltip erroneously disappears when both selection handles are out of view, and erroneously stays visible when one selection handle is in view
Tooltip erroneously disappears when both selection handles are out of view, and erroneously stays visible when one selection handle is in view.

## Steps to Reproduce

1. create a text field
2. highlight enough words to fill the whole text field. 
3. Scroll until the tooltip is out of the region but one handle is out of view 
4. Scroll until both handles are out of view, but the tooltip is still in view.

```dart
class MyApp extends StatelessWidget {
  final textController =
      TextEditingController(text: lorem(words: 100, paragraphs: 4));

  MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          body: Center(
              child: FractionallySizedBox(
        widthFactor: 0.4,
        child: TextField(
          controller: textController,
        ),
      ))),
    );
  }
}

```

**Expected results:** 

on step 3: On iOS, it actually seems like when any scrolling is done with the tooltip up, the tooltip closes, regardless of if the region is still in the screen.
on step 4: the tooltip should stay up.

**Actual results:** 

on step 3: the tooltip stays up.
tooltip-oob

on step 4: the tooltip goes away. 
tooltip-ib

Part of an ongoing fix here: https://github.com/flutter/flutter/pull/105799 - just logging this issue for posterities sake.

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change affects Android and iOS devices using the TextField's context menu. After this change the context menu will fade out when scrolling the text and fade in when the scroll ends. 

If the scroll ends and the selection is outside of the view, then the toolbar will be scheduled to show in a future scroll end. This toolbar scheduling can be invalidated if the `TextEditingValue` changed anytime between the scheduling and when the toolbar is ready to be shown.

This change also fixes a regression where the TextField context menu would not fade when the selection handles where not visible.

When using the native browser context menu this behavior is not controlled by Flutter.

https://github.com/flutter/flutter/assets/948037/3f46bcbb-ba6f-456c-8473-e42919b9d572

Fixes #52425
Fixes #105804
Fixes #52426

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -4829,83 +4834,133 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
-                            selectionHeightStyle: widget.selectionHeightStyle,
-                            selectionWidthStyle: widget.selectionWidthStyle,
-                            paintCursorAboveText: widget.paintCursorAboveText,
-                            enableInteractiveSelection: widget._userSelectionEnabled,
-                            textSelectionDelegate: this,
-                            devicePixelRatio: _devicePixelRatio,
-                            promptRectRange: _currentPromptRectRange,
-                            promptRectColor: widget.autocorrectionTextRectColor,
-                            clipBehavior: widget.clipBehavior,
+                child: NotificationListener<ScrollNotification>(
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:4837]: iOS has the same behavior.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -3536,11 +3553,71 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    // A scheduled toolbar will only be shown if the editing state
+    // did not change between the time the toolbar was first
+    // scheduled to be shown to when it is ready to be shown.
+    if (notification is ScrollStartNotification) {
+      _toolbarVisibleAtScrollStart = _selectionOverlay != null && _selectionOverlay!.toolbarIsVisible;
+      if (_toolbarVisibleAtScrollStart) {
+        hideToolbar(false);
+      }
+    } else if (notification is ScrollEndNotification) {
+      final Rect paintBounds = renderEditable.paintBounds;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart:3596]: Does anyone know if `renderEditable.getTransformTo(null) == Matrix4.zero()` is an accurate way of telling if a render object is in the current viewport? From the documentation of `applyPaintTransform` which is called during `getTransformTo`, this sounds like it is accurate

```dart
Some RenderObjects will provide a zeroed out matrix in this method, indicating that the child should not paint anything or respond to hit tests currently. A parent may supply a non-zero matrix even though it does not paint its child currently, for example if the parent is a [RenderOffstage] with offstage set to true. In both of these cases, the parent must return false from [paintsChild].
```

and from `defaultApplyPaintTransform` which is called from `applyPaintTransform`.

```dart
  /// Applies the transform that would be applied when painting the given child
  /// to the given matrix.
  ///
  /// Render children whose [TextParentData.offset] is null zeros out the
  /// `transform` to indicate they're invisible thus should not be painted.
```

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3536,11 +3553,67 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+          if (_valueWhenShowToolbarOnScreenScheduled == _value) {
+            showToolbar();
+          }
+          _valueWhenShowToolbarOnScreenScheduled = null;
+        } else {
+          showToolbar();
+        }
+      } else if (_toolbarVisibleAtScrollStart) {
+        _showToolbarOnScreenScheduled = true;
+        _valueWhenShowToolbarOnScreenScheduled = _value;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3611]: You don't need the boolean since the extra bit can be represented by setting _valueWhenShowToolbarOnScreenScheduled to null?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3611]: Also this is a bit hard to read.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -3536,11 +3553,67 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    // if the selection endpoints are within the viewport at the
+    // end of the scroll. If not then we should schedule the
+    // toolbar to be shown when we scroll the selection back into
+    // view.
+    //
+    // A scheduled toolbar will only be shown if the editing state
+    // did not change between the time the toolbar was first
+    // scheduled to be shown to when it is ready to be shown.
+    if (notification is ScrollStartNotification) {
+      _toolbarVisibleAtScrollStart = _selectionOverlay != null && _selectionOverlay!.toolbarIsVisible;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3591]: nit:  `?.toolbarIsVisible ?? false`

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -3536,11 +3553,67 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      if (_toolbarVisibleAtScrollStart) {
+        hideToolbar(false);
+      }
+    } else if (notification is ScrollEndNotification) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3595]: do you need to enter the clause if toolbarVisibleAtScrollStart is false?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -2145,6 +2148,12 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   bool get _hasInputConnection => _textInputConnection?.attached ?? false;
 
   TextSelectionOverlay? _selectionOverlay;
+  TextEditingValue? _valueWhenShowToolbarOnScreenScheduled;
+  ScrollNotificationObserverState? _scrollNotificationObserver;
+  bool _toolbarVisibleAtScrollStart = false;
+  bool _showToolbarOnScreenScheduled = false;
+  bool _internalScrolling = false;
+  final bool _webContextMenuEnabled = kIsWeb && BrowserContextMenu.enabled;
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:2156]: Oh you're right, I can make this a getter.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -3536,11 +3553,67 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    // did not change between the time the toolbar was first
+    // scheduled to be shown to when it is ready to be shown.
+    if (notification is ScrollStartNotification) {
+      _toolbarVisibleAtScrollStart = _selectionOverlay != null && _selectionOverlay!.toolbarIsVisible;
+      if (_toolbarVisibleAtScrollStart) {
+        hideToolbar(false);
+      }
+    } else if (notification is ScrollEndNotification) {
+      final bool selectionIsVisible = renderEditable.selectionStartInViewport.value || renderEditable.selectionEndInViewport.value;
+      final bool renderEditableInView = renderEditable.getTransformTo(null) != Matrix4.zero();
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3597]: I had this question https://github.com/flutter/flutter/pull/138313#discussion_r1399803353 related to that. I think it may be in accurate after thinking some more about it, but what do you think?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3595]: Good point we do not. I can add a check.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: That makes sense. Thanks for the suggestion, should look cleaner now.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 8]
```diff
@@ -3536,11 +3552,81 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     }
   }
 
+  final bool _platformSupportsFadeOnScroll = switch (defaultTargetPlatform) {
+    TargetPlatform.android => true,
+    TargetPlatform.iOS => true,
+    TargetPlatform.fuchsia => false,
+    TargetPlatform.linux => false,
+    TargetPlatform.macOS => false,
+    TargetPlatform.windows => false,
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/editable_text.dart:3561]: Nit:
```suggestion
    TargetPlatform.android ||
    TargetPlatform.iOS => true,
    TargetPlatform.fuchsia ||
    TargetPlatform.linux ||
    TargetPlatform.macOS ||
    TargetPlatform.windows => false,
```

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 9]
```diff
@@ -3536,11 +3552,81 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+        return;
+      }
+      if (_valueWhenToolbarShowScheduled != _value) {
+        // Value has changed so we should invalidate any toolbar scheduling.
+        _valueWhenToolbarShowScheduled = null;
+        return;
+      }
+
+      final Rect renderEditableBounds = MatrixUtils.transformRect(renderEditable.getTransformTo(null), renderEditable.paintBounds);
+      final Rect viewportRect = _calculateViewportRect();
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/editable_text.dart:3619]: Is this the Viewport as in the scrollable RenderViewport rect?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 10]
```diff
@@ -3536,11 +3552,81 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
   }
 
+  void _handleContextMenuOnParentScroll(ScrollNotification notification) {
+    if (_internalScrolling) {
+      return;
+    }
+    _handleContextMenuOnScroll(notification);
+  }
+
+  Rect _calculateViewportRect() {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/editable_text.dart:3578]: If this is the scrollable RenderViewport, I think you could get the rect from RenderAbstractViewport.of(context)

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 11]
```diff
@@ -3536,11 +3552,81 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    //
+    // The selection and renderEditable need to be visible within the current
+    // viewport for the toolbar to show when scrolling ends. If they are not
+    // then the toolbar is shown when they are scrolled back into view, unless
+    // invalidated by a change in TextEditingValue.
+    if (notification is ScrollStartNotification) {
+      if (_valueWhenToolbarShowScheduled != null) {
+        return;
+      }
+      final bool toolbarIsVisible = _selectionOverlay?.toolbarIsVisible ?? false;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3602]: looks like `toolbarIsVisible` also accounts for the spellcheck popup.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 12]
```diff
@@ -4829,83 +4914,90 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
-                            paintCursorAboveText: widget.paintCursorAboveText,
-                            enableInteractiveSelection: widget._userSelectionEnabled,
-                            textSelectionDelegate: this,
-                            devicePixelRatio: _devicePixelRatio,
-                            promptRectRange: _currentPromptRectRange,
-                            promptRectColor: widget.autocorrectionTextRectColor,
-                            clipBehavior: widget.clipBehavior,
+                child: NotificationListener<ScrollNotification>(
+                  onNotification: (ScrollNotification notification) {
+                    _internalScrolling = true;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:4919]: Looks like `_internalScrolling` doesn't have to be an instance variable? Making it a parameter would make it slightly easier to understand imo, as the scope of the variable is smaller.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 13]
```diff
@@ -2800,6 +2808,10 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   void didChangeDependencies() {
     super.didChangeDependencies();
 
+    _scrollNotificationObserver?.removeListener(_handleContextMenuOnParentScroll);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:2811]: Every editable field in the app now needs to add itself as a listener. Can the logic be moved to the context menu or something (I think there was a singleton class since there can be at most one menu visible), or only add itself as the listener when the menu becomes visible?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 12 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:4919]: Also why do we need to distinguish internal / parent scrolling?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 13 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2811]: Also my understanding is this notifies listeners when **any** descendent scrolls, even when the scrolling scrollable and the active text field are in different subtrees. That probably should cause the toolbar to disappear as it is not scrolling at all.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 12 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:4933]: I decided to distinguish between internal/parent scrolling because when using only `ScrollNotificationObserver`, `EditableText` received internal scrolling updates too late and the context menu was hidden on `TextSelectionGestureDetector.onTapDown` which prevented the scroll logic from making the toolbar re-appear. `onTapDown` is dispatched even though the `TextSelectionGestureDetector` has not won the arena yet. This is due to the default behavior of `TapAndDragGestureRecognizer`, where it dispatches `onTapDown` after `kPressTimeout = 100ms` if no other recognizer has won the arena. When placing the `NotificationListener` as a direct parent of the internal `Scrollable` we are able to catch the `ScrollNotification` in time to beat the `kPressTimeout`.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 10 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3581]: My intention here was to get a rect that closest represents the visible portion of the flutter view. I want to know if the `RenderEditable` is visible on the screen. Would `RenderAbstractViewport.of(context)` still work if we have a TextField within a horizontal scrollable nested within a vertical scrollable?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 13 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2811]: The documentation states that: 

> Notifications bubble up through the tree, which means a given [NotificationListener](https://main-api.flutter.dev/flutter/widgets/NotificationListener-class.html) will receive notifications for all descendant [Scrollable](https://main-api.flutter.dev/flutter/widgets/Scrollable-class.html) widgets. To focus on notifications from the nearest [Scrollable](https://main-api.flutter.dev/flutter/widgets/Scrollable-class.html) descendant, check that the [depth](https://main-api.flutter.dev/flutter/widgets/ViewportNotificationMixin/depth.html) property of the notification is zero.

So I think that means only `Scrollable`s send notifications so you can do the more efficiently by going up the `Scrollable` tree instead (but you may want to avoid calling `Scrollable.of` since it establishes a dependency).

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 10 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/editable_text.dart:3581]: In that case you may have to bubble up through multiple viewports to find out. Maybe calling getOffsetToReveal for each viewport will work?

Check this out from showInViewport, this is the case where we determine, this is visible we don't need to make it visible. I don't think you need to do the things in the if clause here, it's jsut an example of how we determined it was visible:

https://github.com/flutter/flutter/blob/023e5addaa6e8e294a200cf754afaa1656f14aa6/packages/flutter/lib/src/rendering/viewport.dart#L1248-L1250

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 13 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/editable_text.dart:2811]: Yeah, in this case, you would likely not want to check notification depth and limit it to 0. The depth increases for each nested scrollable.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 10 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3595]: Thanks for the suggestion! Something like this works for me, but I realized `RenderAbstractViewport` doesn't take into account things like status bar or keyboard. In this case maybe the current implementation of calculating the approximate visible viewport rect might be more accurate, what do you think? 

```dart
  bool? _renderEditableIsVisible(ScrollNotification notification) {
    RenderAbstractViewport? closestViewport = RenderAbstractViewport.maybeOf(renderEditable);
    if (closestViewport == null) {
      return null;
    }
    while (closestViewport != null) {
      final RevealedOffset leadingEdgeOffset = closestViewport.getOffsetToReveal(renderEditable, 0.0);
      final RevealedOffset trailingEdgeOffset = closestViewport.getOffsetToReveal(renderEditable, 1.0);
      final double currentOffset = -notification.metrics.pixels;
      final RevealedOffset? targetOffset = RevealedOffset.clampOffset(
        leadingEdgeOffset: leadingEdgeOffset,
        trailingEdgeOffset: trailingEdgeOffset,
        currentOffset: currentOffset,
      );
      if (targetOffset != null) {
        // `descendant` is between leading and trailing edge and hence already
        //  fully shown on screen. No action necessary.
        return false;
      }
      closestViewport = RenderAbstractViewport.maybeOf(closestViewport.parent);
    }
    return true;
  }
```

Comment (Piinks) [reply packages/flutter/lib/src/widgets/editable_text.dart:3595]: SGTM! 🎉

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 12 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I was able to get rid of the `_internalScrolling` and the differentiation by just using `ScrollNotificationObserver`, however doing this makes `EditableText` unable to receive any scroll notifications unless it has a parent `ScrollNotificationObserver` (`Scaffold` has one but if someone doesn't use it they won't be able to take advantage of this feature). If we go with this route we should document these details somewhere. A pro of this solution is that we are able to conditionally listen for internal scrolling events (only listen when the toolbar is shown), versus `NotificationListener` where we do not have this control.

Using the previous combination of `NotificationListener` and `ScrollNotificationObserver` allows `EditableText` to still listen to its own internal scrollable notifications without a parent `ScrollNotificationObserver`. To listen to parent scroll events a user would need to place a `ScrollNotificationObserver` somewhere higher in the tree. I think if we go with this solution we need to document this detail somewhere. I can also remove the use of the local member `_internalScrolling` with this solution by checking if the notification context is the same as the internal scrollable context.

Maybe another option would be to place `ScrollNotificationObserver` even higher in the tree in the framework like `MaterialApp` or `WidgetsApp`? This would cover a larger range of users.

Curious to hear thoughts on this @LongCatIsLooong @Piinks

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Discussed some of this offline, but leaning towards using the combination of NotificationListener and ScrollNotificationObserver so EditableText can get this functionality for it's internal scrollable without having to place a ScrollNotificationObserver as a parent.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 14]
```diff
@@ -3550,9 +3567,104 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      return;
+    }
+    _handleContextMenuOnScroll(notification);
+  }
+
+  Rect _calculateViewportRect() {
+    final Size screenSize = MediaQuery.sizeOf(context);
+    final ui.FlutterView view = View.of(context);
+    final double obscuredVertical = (view.padding.top + view.padding.bottom + view.viewInsets.bottom) / view.devicePixelRatio;
+    final double obscuredHorizontal = (view.padding.left + view.padding.right) / view.devicePixelRatio;
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3601]: Do you have other plans to update the implementation here? Using the view dimensions is a bit strange, for example when the viewport is not fullscreen.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 15]
```diff
@@ -3550,9 +3567,104 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      return true;
+    }
+    return false;
+  }
+
+  void _handleContextMenuOnParentScroll(ScrollNotification notification) {
+    if (_isInternalScrollableNotification(notification.context)) {
+      return;
+    }
+    if (!_scrollableNotificationIsFromSameSubtree(notification.context)) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3591]: nit: the implementation of this check is relatively expensive. Consider doing other checks first (e.g., filtering out notifications that aren't start/end.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3601]: (Or you could move this to a different PR and always show the edit menu for now)

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 16]
```diff
@@ -3550,9 +3567,104 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    // viewport for the toolbar to show when scrolling ends. If they are not
+    // then the toolbar is shown when they are scrolled back into view, unless
+    // invalidated by a change in TextEditingValue.
+    if (notification is ScrollStartNotification) {
+      if (_valueWhenToolbarShowScheduled != null) {
+        return;
+      }
+      final bool toolbarIsVisible = _selectionOverlay?.toolbarIsVisible ?? false;
+      _valueWhenToolbarShowScheduled = toolbarIsVisible ? _value : null;
+      if (_valueWhenToolbarShowScheduled != null) {
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3694]: I think I can actually remove this check considering `_valueWhenToolbarShowScheduled` is only non-null when `toolbarIsVisible`.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3652]: I don't follow, do you mean when the textfield is inside a viewport that is not the fullscreen?

[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3652]: My thought with the logic here is:

`selectionIsVisible` tells us if the selection is visible within the `RenderEditable`.
`renderEditableBounds` is the `Rect` for the `RenderEditable`, if it `hasNaN` it is likely not laid out.
`viewportRect` attempts to calculate the device entire viewport with paddings for system overlays.
`renderEditableInView` checks whether the `viewportRect` and `renderEditableBounds` overlap, if they do then the `RenderEditable` should be visible within the device viewport.

The final check is `selectionIsVisible && renderEditableInView` which checks if the selection is visible in the `RenderEditable` and if the `RenderEditable` is visible within the device viewport.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3698]: Are you using `_selectionOverlay?.toolbarIsVisible` to tell whether `showToolbar` was called?

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 17]
```diff
@@ -164,6 +164,14 @@ class _CupertinoTextFieldSelectionGestureDetectorBuilder extends TextSelectionGe
 ///
 /// {@macro flutter.widgets.editableText.showCaretOnScreen}
 ///
+/// ## Scrolling Considerations
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_field.dart:167]: I think they are using 2 #'s from looking at the other `TextField/CupertinoTextField/EditableText` subsections.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3713]: I think it makes more sense to hide the overlay if the `RenderEditable` itself is not visible. This way the menu still adjusts to avoid the overlays if the text field is visible and hides it when its completely obscured to prevent the menu from overlapping with the system overlays. This seems consistent with the Android behavior.

Taking system overlays into account:
https://github.com/flutter/flutter/assets/948037/f45c9172-0815-4362-bcfd-01b4af02b2d6

Without taking system overlays into account:
https://github.com/flutter/flutter/assets/948037/4fe00dab-eccb-49fa-8627-ef5a2a65f8a3

Jetpack compose behavior:
https://github.com/flutter/flutter/assets/948037/76ca8bce-dc27-4e78-a8d3-4289b636c413

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3737]: Sorry missed this, I am using it to check if the text selection toolbar is visible. `toolbarIsVisible` does account for spellcheck popup, do you recommend I add a new API that would tell us if only the text selection toolbar is visible?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I think I can just use `!_selectionOverlay.spellCheckToolbarIsVisible` along with `toolbarIsVisible` to target the text selection toolbar.

**Comment by Renzo-Olivares** [comment]
A friendly bump

**Review by LongCatIsLooong — COMMENTED** [review]
Sorry looks like I forgot to press the submit review button.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3709]: I see the behavior makes sense to me. But the code seems to only check for system UI obstruction, that seems oddly specific. If the text field is obstructed by the outer scroll view would the menu also disappear?

**Review by LongCatIsLooong — COMMENTED** [review]
LGTM in general but the system UI obstruction check still seems oddly specific to me.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/lib/src/widgets/editable_text.dart:3709]: Isn't showOnScreen/showInViewport/or ensureVisible called as part of focusing on a text field and showing the context menu? If so, it should account for the case where a nested scroll view is scrolled out of view by the outer scroll view.

[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3714]: Yeah my implementation of trying to calculate the viewport rect didn't take into account for this case because the viewport is not always the devices fullscreen. I was able to fix this case by going back to your original suggestion @Piinks https://github.com/flutter/flutter/pull/138313#discussion_r1409994272 and bubbling through the viewports. I still think we should consider the calculated viewport rect for system overlays like the keyboard.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 18]
```diff
@@ -3613,9 +3642,152 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+
+  bool? _renderEditableInViewport(ScrollNotification notification) {
+    RenderAbstractViewport? closestViewport = RenderAbstractViewport.maybeOf(renderEditable);
+    if (closestViewport == null) {
+      return null;
+    }
+    while (closestViewport != null) {
+      final RevealedOffset leadingEdgeOffset = closestViewport.getOffsetToReveal(renderEditable, 0.0);
+      final RevealedOffset trailingEdgeOffset = closestViewport.getOffsetToReveal(renderEditable, 1.0);
+      final double currentOffset = notification.metrics.pixels;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3777]: This assumes the notification comes from the closest viewport?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good point, I have addressed this in https://github.com/flutter/flutter/pull/138313/commits/cae38b72b18848f837c43921eb7832a62a261223.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I landed on this approach https://github.com/flutter/flutter/pull/138313/commits/599beb3cf7d5ad1c3101740ea9aa2648018ff90d which checks if the `renderEditable.paintBounds` overlaps with the `viewport.paintBounds`, my previous approach I linked would hide the context menu when the `renderEditable` was even partially occluded. I verified this approach covers the cases we discussed.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 19]
```diff
@@ -3614,9 +3643,145 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+        _disposeScrollNotificationObserver();
+        return;
+      }
+
+      final Rect deviceRect = _calculateDeviceRect();
+      final bool selectionVisibleInEditable = renderEditable.selectionStartInViewport.value || renderEditable.selectionEndInViewport.value;
+      final Rect selectionBounds = MatrixUtils.transformRect(renderEditable.getTransformTo(null), _dataWhenToolbarShowScheduled!.selectionBounds);
+      final bool selectionOverlapsWithDeviceRect = !selectionBounds.hasNaN && deviceRect.overlaps(selectionBounds);
+
+      if (selectionVisibleInEditable && selectionOverlapsWithDeviceRect && (_selectionInViewport(selectionBounds) ?? true)) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3765]: Is this the only place _selectionInViewport gets called? If so the return type can be `bool`?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 20]
```diff
@@ -3614,9 +3643,145 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      if (_dataWhenToolbarShowScheduled!.value != _value) {
+        // Value has changed so we should invalidate any toolbar scheduling.
+        _dataWhenToolbarShowScheduled = null;
+        _disposeScrollNotificationObserver();
+        return;
+      }
+
+      final Rect deviceRect = _calculateDeviceRect();
+      final bool selectionVisibleInEditable = renderEditable.selectionStartInViewport.value || renderEditable.selectionEndInViewport.value;
+      final Rect selectionBounds = MatrixUtils.transformRect(renderEditable.getTransformTo(null), _dataWhenToolbarShowScheduled!.selectionBounds);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3762]: Is this similar to selectionVisibleInEditable? Why's selectionVisibleInEditable not enough?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3762]: Also why is selectionBounds computed when the scrolling starts instead of when it stops?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 21]
```diff
@@ -3614,9 +3643,145 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    }
+  }
+
+  bool? _selectionInViewport(Rect selectionBounds) {
+    RenderAbstractViewport? closestViewport = RenderAbstractViewport.maybeOf(renderEditable);
+    if (closestViewport == null) {
+      return null;
+    }
+    while (closestViewport != null) {
+      final Rect closestViewportBounds = MatrixUtils.transformRect(closestViewport.getTransformTo(null), closestViewport.paintBounds);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3778]: transforming both rects to the view coordinates seems to be a bit of an overkill? Maybe compare the rects in each viewport's coordinates until it reaches the topmost viewport?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 20 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3762]: `selectionVisibleInEditable` is not accurate enough because `renderEditable.selectionStartInViewport` and `renderEditable.selectionEndInViewport` only considers whether the selection is visible in `RenderEditable`s local coordinates. 

`selectionOverlapsWithDeviceRect` account for system overlays like the keyboard and system ui.

`_selectionInViewport` considers the `TextField` being in a `Scrollable`/ nested `Scrollable`s. This accounts for the case when the outer scroll view may occlude the `TextField` selection.

> Also why is selectionBounds computed when the scrolling starts instead of when it stops?

I compute the selection `Rect` during the scroll start, these are in local coordinates of the `RenderEditable` so they should not change on scroll. When the scroll ends I compute the transformed `Rect` for selectionBounds.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 21 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good point, i'll change that!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 20 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3762]: > these are in local coordinates of the RenderEditable so they should not change on scroll.

What's the advantage of doing this, over computing this on scroll end? You don't have to make this assumption if you do this on scroll end right?

> only considers whether the selection is visible in RenderEditables local coordinates.

Ah I see. Thanks for the explanation!

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 22]
```diff
@@ -3614,9 +3643,149 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    if (notification is ScrollStartNotification) {
+      if (_dataWhenToolbarShowScheduled != null) {
+        return;
+      }
+      final bool toolbarIsVisible = _selectionOverlay != null
+                                  && _selectionOverlay!.toolbarIsVisible
+                                  && !_selectionOverlay!.spellCheckToolbarIsVisible;
+      final Rect? selectionBounds = toolbarIsVisible ? renderEditable.getBoxesForSelection(_value.selection)
+                                           .map((TextBox box) => box.toRect())
+                                           .reduce((Rect result, Rect rect) => result.expandToInclude(rect)) : null;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3744]: reduce throws if the method returns an empty list. Would using the selection handle rects work (and it's only 2 rects instead of however many getBoxesForSelection returns)?

Also I'm a bit curious where we place the toolbar when the text is multiple screens long and you press ctrl-A.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 23]
```diff
@@ -3614,9 +3643,149 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      if (selectionVisibleInEditable
+         && selectionOverlapsWithDeviceRect
+         && _selectionInViewport(_dataWhenToolbarShowScheduled!.selectionBounds)) {
+        showToolbar();
+        _dataWhenToolbarShowScheduled = null;
+      }
+    }
+  }
+
+  bool _selectionInViewport(Rect selectionBounds) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3774]: nit: static method?

**Review by LongCatIsLooong — APPROVED** [review]
The approach LGTM.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 20 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3762]: By capturing on scroll start we only call `getBoxesForSelection` once, while if we capture on scroll end we call it every time while the toolbar has been scheduled to be shown.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 23 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:3778]: I think since this method uses the `renderEditable` it can't be made static.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 22 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good point, I did not think about the case where the selection is collapsed which would return an empty list. I think in that case we can use the local caret rect. I think using the selection handle rects would work, I started implementing it but it seemed to complicate the implementation some since we are now checking against a List<Rect> instead of a single Rect. I think for now its reasonable to use all the rects from `getBoxesForSelection` since we end up merging them into a single rect anyways.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart]: `getBoxesForSelection` can be expensive if there are many runs. But I think that can be addressed later.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 24]
```diff
@@ -3614,9 +3643,158 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+          showToolbar();
+          _dataWhenToolbarShowScheduled = null;
+        }
+      }, debugLabel: 'EditableText.scheduleToolbar');
+    }
+  }
+
+  bool _selectionInViewport(Rect selectionBounds) {
+    RenderAbstractViewport? closestViewport = RenderAbstractViewport.maybeOf(renderEditable);
+    if (closestViewport == null) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3785]: nit: I think this `if` is redundant?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 25]
```diff
@@ -3614,9 +3643,158 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      final bool toolbarIsVisible = _selectionOverlay != null
+                                  && _selectionOverlay!.toolbarIsVisible
+                                  && !_selectionOverlay!.spellCheckToolbarIsVisible;
+      final Rect? selectionBounds = toolbarIsVisible
+                                  ? _value.selection.isCollapsed
+                                      ? renderEditable.getLocalRectForCaret(_value.selection.extent)
+                                      : renderEditable.getBoxesForSelection(_value.selection)
+                                          .map((TextBox box) => box.toRect())
+                                          .reduce((Rect result, Rect rect) => result.expandToInclude(rect))
+                                  : null;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3748]: nit: put the simpler expression first?

Also even if the selection is not collapsed you can still get an empty list.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 26]
```diff
@@ -3614,9 +3643,158 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+        return;
+      }
+      if (_dataWhenToolbarShowScheduled!.value != _value) {
+        // Value has changed so we should invalidate any toolbar scheduling.
+        _dataWhenToolbarShowScheduled = null;
+        _disposeScrollNotificationObserver();
+        return;
+      }
+
+      SchedulerBinding.instance.addPostFrameCallback((Duration _) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3764]: Avoid scheduling this a second time in the same frame?
