### PR TITLE
`SelectableRegion` should not show flutter rendered context menu when web context menu is enabled

### LINKED ISSUE #175114: [PWA] Duplicate “Copy” action shown when SelectionArea wraps — double copy menu
### Steps to reproduce

1. Create a new Flutter app (flutter create).
2. Replace lib/main.dart with the snippet below.
3. Run on Web (PWA or plain web):
4. flutter run -d chrome
5. Select the text via mouse drag (or long-press on touch).
6. Observe the context/selection actions contain two “Copy” entries.

### Expected results

Only one “Copy” action appears in the selection controls / context menu.

### Actual results

Two “Copy” actions are shown for the same selection on PWA

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Scaffold(
      appBar: AppBar(title: const Text('ListView with SelectionArea')),
      body: ListView.builder(
        itemCount: 20,
        itemBuilder:
            (context, index) => SelectionArea(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  'Item ${index + 1}',
                  style: const TextStyle(fontSize: 18),
                ),
              ),
            ),
      ),
    ),
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Video demonstration PWA</summary>

https://github.com/user-attachments/assets/428111a7-10bd-4764-86f6-822970f3b6db

</details>

<details open>
<summary>Video demonstration IOS</summary>

https://github.com/user-attachments/assets/69b0d900-5e50-47d5-b1a7-f513fdb39529

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change fixes an issue where the flutter rendered menu would show up when ending a drag on a selection handle, even when the web context menu was enabled. This led to issues where both context menus would show up leading to a unfavorable experience.

Fixes #175114

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -1122,21 +1125,9 @@ class SelectableRegionState extends State<SelectableRegion>
     final bool draggingHandles =
         _selectionOverlay != null &&
         (_selectionOverlay!.isDraggingStartHandle || _selectionOverlay!.isDraggingEndHandle);
-    if (widget.selectionControls is! TextSelectionHandleControls) {
-      if (!draggingHandles) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1126]: Why this change, I think this may be code to handle custom context menu (although we shouldn't probably use runtimetype check to infer this)

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1126]: It ends up being the same before/after. The code to handle the context menu TextSelectionControls vs ContextMenuBuilder is in _showToolbar.

**Review by loic-sharma — APPROVED** [review]
LGTM!

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1126]: oh I see, sounds good then. Can you add a todo in the runtitmeType check in _showToolbar to refactor that?

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -408,6 +408,9 @@ class SelectableRegionState extends State<SelectableRegion>
   Orientation? _lastOrientation;
   SelectedContent? _lastSelectedContent;
 
+  /// Whether the native browser context menu is enabled.
+  bool get _webContextMenuEnabled => kIsWeb && BrowserContextMenu.enabled;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:412]: Ah same strategy used in EditableText. More evidence that having two separate implementations of text selection leads to bugs.

**Review by justinmc — APPROVED** [review]
LGTM 👍
