### PR TITLE
[flutter_tools] fix crash when IsolateRef returns sentinel

### LINKED ISSUE #50610: Tool crash: type 'Sentinel' is not a subtype of type 'Isolate' in type cast
```
2020-02-11T14:50:43.560797: stderr: type 'Sentinel' is not a subtype of type 'Isolate' in type cast
2020-02-11T14:50:43.561203: stderr: #0      FallbackDiscovery._attemptServiceConnection (package:flutter_tools/src/ios/fallback_discovery.dart:135:78)
stderr: <asynchronous suspension>
stderr: #1      FallbackDiscovery.discover (package:flutter_tools/src/ios
/fallback_discovery.dart:67:30)
stderr: #2      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:386:52)
```
[flutter_gallery_ios32__start_up_324e20d_2.log](https://github.com/flutter/flutter/files/4189079/flutter_gallery_ios32__start_up_324e20d_2.log)

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The IsolateRef might return a Sentinel if the backing Isolate was collected or doesn't exist due to some other error unknown to me.

Fixes https://github.com/flutter/flutter/issues/50610

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 1]
```diff
@@ -132,8 +132,12 @@ class FallbackDiscovery {
         final VmService vmService = await _vmServiceConnectUri(assumedWsUri.toString());
         final VM vm = await vmService.getVM();
         for (final IsolateRef isolateRefs in vm.isolates) {
-          final Isolate isolate = await vmService.getIsolate(isolateRefs.id) as Isolate;
-          final LibraryRef library = isolate.rootLib;
+          final dynamic isolateResponse = await vmService.getIsolate(isolateRefs.id);
+          if (isolateResponse is! Isolate) {
+            // Might have been a Sentinel. Try again later.
+            throw Exception();
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart]: Might be worth a better exception message?

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart]: Or a check that it is a Sentinel instead?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart]: Made check for Sentinel and added error message to expception

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart]: exception

**Review by jmagman — APPROVED** [review]
LGTM
