### PR TITLE
make CIPD url customizable using FLUTTER_STORAGE_BASE_URL

### LINKED ISSUE #92357: chrome-infra-packages.appspot.com is not accessible in China
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Web SDK...                                             32.7s
Downloading CanvasKit...                                          129.5s
Downloading CanvasKit...                                          131.1s

https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/1e8cK_8LOs0dz4lqd20LwTUYNqfu_4YL-dFG5yK1xXQC. Ensure
you have network connectivity and then try again.
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = chrome-infra-packages.appspot.com,
port = 443

```

I start upgrade flutter today and suddenly found flutter can not download assets from `chrome-infra-packages.appspot.com,`

this is **blocked by GFW in China**. please make an alterative url to download this.

### PR DESCRIPTION
**Pull request by yjbanov**
Allow customizing the base CIPD URL via `FLUTTER_STORAGE_BASE_URL` as follows:

- If `FLUTTER_STORAGE_BASE_URL` is not specified, use https://chrome-infra-packages.appspot.com/dl as the base CIPD URL.
- Otherwise, make the base CIPD URL `FLUTTER_STORAGE_BASE_URL/flutter_infra_release/cipd`

This way maintainers of Flutter SDK artifact mirrors can include some of the CIPD packages that are needed to build for some platforms. For example, this can be used to mirror the build of CanvasKit.

Fixes https://github.com/flutter/flutter/issues/92357

### CODE REVIEW

**Comment by AlexV525** [comment]
cc @chenglu

**Review by chenglu — APPROVED** [review]
LGTM, thanks for doing this! 👍👍

File: packages/flutter_tools/lib/src/cache.dart [hunk 1]
```diff
@@ -446,6 +446,29 @@ class Cache {
     return overrideUrl;
   }
 
+  String get cipdBaseUrl {
+    final String? overrideUrl = _platform.environment['FLUTTER_STORAGE_BASE_URL'];
+    if (overrideUrl == null) {
+      return 'https://chrome-infra-packages.appspot.com/dl';
```
Comment (AlexV525) [inline packages/flutter_tools/lib/src/cache.dart:452]: We already defined a hidden CIPD base URL here:
https://github.com/flutter/flutter/blob/6c1455a23ae53ec3a92be8f50a798d6c789b471f/packages/flutter_tools/lib/src/flutter_cache.dart#L578

Should we hard-code this again?

Comment (yjbanov) [reply packages/flutter_tools/lib/src/cache.dart:452]: I am removing this constant in this PR so that people do not accidentally use it in the future. Of course, the bar to make this mistake is still not very high (anyone can just create a new constant), but at least making it a local constant doesn't make it easily accessible. Actually, now that I think of it, I should probably leave a comment warning people about this.

Comment (AlexV525) [reply packages/flutter_tools/lib/src/cache.dart:452]: So it seems we should have a policy about this in the future? URLs can be easily introduced, but the mistake can be avoided most time with guidance.

Comment (yjbanov) [reply packages/flutter_tools/lib/src/cache.dart:452]: I'm not sure how to make a policy such that it's effective. A policy is just a document somewhere that someone has to read, preferably before they start making changes to the code. Maybe such document exists already, and I didn't read it. I would be more likely to read a comment in the code, although that's still not bullet proof.

I'll delegate to @christopherfujino, who is the tech lead for the tool, to decide if a policy can help here.

Comment (AlexV525) [reply packages/flutter_tools/lib/src/cache.dart:452]: Agreed with a lower priority, can other parts of this PR push forward? They are looking good so far.

**Review by AlexV525 — APPROVED** [review]

File: packages/flutter_tools/lib/src/cache.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/cache.dart:452]: I'll update a doc about it, but agreed, the "policy" can only be enforced in code review. We did not have a policy banning this before, because we had not considered the effect on users in China. AFAIK, the only previous usage of this CIPD hack was for Fuchsia-related assets, which I'm guessing did not have many/any Chinese users.
