### PR TITLE
Switch flutter_tools to use frontend_server for web compilation

### LINKED ISSUE #38797: [Flutter Web] Non-default entrypoint breaks run command
I've missed exact moment, when after upgrading flutter web is completely broken again
After running `flutter run -d chrome` I see only "Build application for the web..." in terminal and following error in JS console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:143 Uncaught Error: Script error for "main_web_entrypoint.dart.bootstrap"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```
Flutter Doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.1-pre.89, on Mac OS X 10.14.4 18E226, locale en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.37.0)
[✓] Connected device (4 available)

• No issues found!
```
UPD: with `--verbose` there is no errors as well. Actually reproduces only on one project, which I can't share

### LINKED ISSUE #40481: [WEB] RUN 'flutter run -d chrome' will prompt an error after first time to up the project.
I try to start a flutter-web project with command : `flutter run -d chrome`,it will process whole build work and start it with non-fatal error.
THEN I terminate the run command and re-run it, it will stop with an error while building the project.

image

Had to re-open the project IDE to run it.

### LINKED ISSUE #41544: WEB: "flutter run -d chrome" crashes when using package with protobuf in dependencies
I am playing with flutter web (master channel version **1.10.7-pre.70**) in vs code.

When my application **app_io** is using package **app_main**, which has **protobuf** reference in app_main/pubspec.yaml:
```
dependencies:
  protobuf:
```
than ```flutter run -d chrome``` crashes.

It is curious, that:
- **protobuf** is not used in **app_main** package code, just referenced in app_main/pubspec.yaml
- when I reference (or even use **protobuf** code) in **app_io** application, all is OK.

You can evoke an error in https://github.com/PavelPZ/protobuf_problem 
- uncomment **protobuf:** line in https://github.com/PavelPZ/protobuf_problem/blob/master/app_main/pubspec.yaml 
- run ```flutter run -d chrome``` again.
- following error raise:
```
flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _packageBuildConfig.<anonymous closure> (package:build_runner_core/src/package_graph/target_graph.dart:85:61)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      new BuildConfig.useDefault (package:build_config/src/build_config.dart:90:34)
#5      BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart:52:26)
<asynchronous suspension>
#6      _packageBuildConfig (package:build_runner_core/src/package_graph/target_graph.dart:90:30)
<asynchronous suspension>
#7      TargetGraph.forPackageGraph (package:build_runner_core/src/package_graph/target_graph.dart:37:17)
<asynchronous suspension>
#8      BuildOptions.create (package:build_runner_core/src/generate/options.dart:107:39)
<asynchronous suspension>
#9      BuildRunnerDaemonBuilder.create (package:build_runner/src/daemon/daemon_builder.dart:182:43)
<asynchronous suspension>
#10     DaemonCommand.run (package:build_runner/src/entrypoint/daemon.dart:83:48)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     run (package:build_runner/src/entrypoint/run.dart:24:31)
<asynchronous suspension>
#16     main (package:flutter_tools/src/build_runner/build_script.dart:200:28)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Building application for the web...                                24.7s
Failed to build application for the web.
```

### LINKED ISSUE #41951: Validate that the incremental_compiler improves the Flutter for Web workflow
This is currently blocked on implementing the prototype for integration of the dev_compiler with the incremental compiler. Once that is done, we should via some opt-in allow enabling or disabling the incremental compiler to validate that it improves performance of hot reload for the web.

there may be other benefits to adopting it, such as if we can improve browser reload speed by adopting the "legacy" module format, and allowing updating .packages on the fly.

Update: This has been implemented under a config flag, but still needs to be enabled by implementing some missing functionality (dwds and plugins)

### LINKED ISSUE #43639: Flutter web doesn't work with the `builders:` pubspec.yaml option
Root cause has already been diagnosed, see https://github.com/dart-lang/build/issues/2516.

Filing here for tracking purposes, feel free to close if you want to.

## Steps to Reproduce

1. Enable web config `flutter config --enable-web`
2. Add a builders key to your pubspec.yaml, for example:

```yaml
builders:
  json_serializable: any
```

3. Run with the chrome device `flutter run -d chrome`.

## Logs

```
[  +17 ms] executing: [/usr/local/google/home/jakemac/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] dd39f5f76438b8a9be35b6b12b4fa7baf93c6fd6
[        ] executing: [/usr/local/google/home/jakemac/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-273-gdd39f5f76
[   +8 ms] executing: [/usr/local/google/home/jakemac/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] jonah/web_compiler
[        ] executing: [/usr/local/google/home/jakemac/flutter/] git ls-remote --get-url jonah
[   +4 ms] Exit code 0 from: git ls-remote --get-url jonah
[        ] https://github.com/jonahwilliams/flutter.git
[  +10 ms] executing: [/usr/local/google/home/jakemac/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] jonah-hot-reload
[  +71 ms] executing: /usr/local/google/home/jakemac/android-sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /usr/local/google/home/jakemac/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +21 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +31 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +6 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +44 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[   +1 ms] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[  +29 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +2 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +27 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[        ] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[  +31 ms] Generating
/usr/local/google/home/jakemac/flutter/examples/flutter_gallery/android/app/src/main/java/io/flutter/plug
ins/GeneratedPluginRegistrant.java
[ +113 ms] starting build daemon...
[ +158 ms] Starting daemon...
[ +137 ms] Initializing inputs
[   +8 ms] Reading cached asset graph...
[  +89 ms] Reading cached asset graph completed, took 87ms

[ +180 ms] Checking for updates since last build...
[ +474 ms] Checking for updates since last build completed, took 474ms

[   +8 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 87ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 474ms
[  +27 ms] Setting up file watchers...
[        ] Setting up file watchers completed, took 3ms
[  +30 ms] starting build daemon... (completed in 1.1s)
[ +113 ms] About to build [lib, test]...
[   +6 ms] Running build...
[  +56 ms] Running build completed, took 24ms

[        ] Caching finalized dependency graph...
[  +11 ms] Caching finalized dependency graph completed, took 66ms

[   +3 ms] Succeeded after 95ms with 0 outputs (0 actions)

[  +20 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[ +298 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +1 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +10 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[        ] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[+5682 ms] Running Options: {--skip-build-script-check, --delete-conflicting-outputs,
--build-mode=BuildMode.Auto}
[        ] Requested Options: {--skip-build-script-check, --define,
flutter_tools:ddc=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:entrypoint=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:entrypoint=release=false, flutter_tools:entrypoint=profile=false,
flutter_tools:shell=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:shell=hasPlugins=false, flutter_tools:shell=initializePlatform=true,
--build-mode=BuildMode.Manual}
[   +7 ms] Building application for the web... (completed in 6.0s)
[   +2 ms] "flutter run" took 7,733ms.
Incompatible options with current running build daemon.

Please stop other flutter_tool instances running in this directory before starting a new instance with
these options.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildDaemonCreator.startBuildDaemon (package:flutter_tools/src/build_runner/web_fs.dart:575:7)
<asynchronous suspension>
#2      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:247:10)
<asynchronous suspension>
#3      ResidentWebRunner.run.<anonymous closure>
(package:flutter_tools/src/build_runner/resident_web_runner.dart:193:36)
<asynchronous suspension>
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:112:32)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1500:12)
#9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:110:3)
#10     ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:192:32)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:222:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main
(file:///usr/local/google/home/jakemac/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

### LINKED ISSUE #44552: Flutter web never connects to Chrome in debug mode
## Steps to Reproduce

I am trying to run a flutter web project using `flutter run -d chrome`. The project builds fine, but once it gets to `Attempting to connect to browser instance..` nothing happens. A Chrome window does open, but it is just a blank page and the browser instance is never connected (see below screenshot). It does look like there is a 404 error when it tries to reference `main.dart.js`. If I run `flutter run --release -d chrome` everything works just fine except I can't interactively debug and the code is all minified making it impossible to troubleshoot/debug.

image

**Target Platform: Web**
**Target OS version/browser: Windows Chrome Version 78.0.3904.97**
**Devices: Chrome**

## Logs

```
PS C:\Users\jonjon1123\StudioProjects\bowlr-admin> flutter run -d chrome --verbose
[  +25 ms] executing: [C:\Users\jonjon1123\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +111 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] e7073f9a1f5c40398f589ae45956b489b1f3ab10
[   +1 ms] executing: [C:\Users\jonjon1123\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +147 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.10.15-113-ge7073f9a1
[  +18 ms] executing: [C:\Users\jonjon1123\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +93 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [C:\Users\jonjon1123\flutter\] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +168 ms] executing: [C:\Users\jonjon1123\flutter\] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +143 ms] executing: C:\Users\jonjon1123\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] Exit code 0 from: C:\Users\jonjon1123\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +310 ms] Generating
C:\Users\jonjon1123\StudioProjects\bowlr-admin\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.ja
va
[ +323 ms] Launching lib\main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[+9878 ms] Starting daemon...
[ +183 ms] Initializing inputs
[  +13 ms] Reading cached asset graph...
[ +193 ms] Reading cached asset graph completed, took 189ms

[ +224 ms] Checking for updates since last build...
[ +578 ms] Checking for updates since last build completed, took 578ms

[   +9 ms] Initializing inputs
[   +3 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 189ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 578ms
[ +271 ms] Serving DevTools at http://127.0.0.1:52823

[ +817 ms] About to build [web]...
[  +12 ms] Running build...
[ +130 ms] Running build completed, took 55ms

[   +2 ms] Caching finalized dependency graph...
[  +13 ms] Caching finalized dependency graph completed, took 119ms

[   +5 ms] Succeeded after 183ms with 0 outputs (0 actions)

[  +15 ms] Building application for the web... (completed in 12.3s)
[   +1 ms] Attempting to connect to browser instance..
```

```
PS C:\Users\jonjon1123\StudioProjects\bowlr-admin> flutter doctor -v
[√] Flutter (Channel master, v1.10.16-pre.113, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
    • Flutter version 1.10.16-pre.113 at C:\Users\jonjon1123\flutter
    • Framework revision e7073f9a1f (25 hours ago), 2019-11-09 17:08:53 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\jonjon1123\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\jonjon1123\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

### LINKED ISSUE #44698: [web] build error: AssetNotFoundException
## Steps to Reproduce

1. Clone [pd4d10/highlight](https://github.com/pd4d10/highlight) repo's `debug` branch:
    `git clone --branch debug https://github.com/pd4d10/highlight.git`
2. Open it with VSCode and wait until dependencies installed
3. Start debugging (F5), which will launch `flutter_highlight/example/lib/main.dart`

It works correctly at iOS or Android devices. But if we select `chrome` as device it shows errors as follows:

```sh
AssetNotFoundException: flutter_highlight|lib/flutter_highlight.ddc.js
Error compiling dartdevc module:flutter_highlight|lib/flutter_highlight.ddc.js

packages/flutter_highlight/flutter_highlight.dart:95:30: Error: The getter 'highlight' isn't defined for the class 'HighlightView'.
 - 'HighlightView' is from 'package:flutter_highlight/flutter_highlight.dart' ('packages/flutter_highlight/flutter_highlight.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'highlight'.
          children: _convert(highlight.parse(source, language: language).nodes),
                             ^^^^^^^^^
```

Seems some `ddc.js` are not generated correctly.

**Target Platform:** macOS
**Target OS version/browser:** 10.15
**Devices:** Chrome 78.0.3904.87

## Logs

```
[        ] Running build...
[ +396 ms] Unable to read flutter_highlight|lib/flutter_highlight.ddc.js, check your console or the `.dart_tool/build/generated/flutter_highlight/lib/flutter_highlight.ddc.js.errors` log file.
[  +17 ms] AssetNotFoundException: flutter_highlight|lib/flutter_highlight.ddc.js
[   +1 ms] #0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:147:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           <asynchronous suspension>
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
           <asynchronous suspension>
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
           #5      Future.wait (dart:async/future.dart:391:26)
           #6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
           #7      _rootRun (dart:async/zone.dart:1124:13)
           #8      _CustomZone.run (dart:async/zone.dart:1021:19)
           #9      _runZoned (dart:async/zone.dart:1516:10)
           #10     runZoned (dart:async/zone.dart:1500:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           <asynchronous suspension>
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:478:19)
           #14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:476:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:434:22)
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:430:17)
           #20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:378:38)
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #22     Future.wait (dart:async/future.dart:391:26)
           #23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:377:36)
           <asynchronous suspension>
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:323:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:313:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           <asynchronous suspension>
           #30     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:270:26)
           <asynchronous suspension>
           #31     _rootRun (dart:async/zone.dart:1124:13)
           #32     _CustomZone.run (dart:async/zone.dart:1021:19)
           #33     _runZoned (dart:async/zone.dart:1516:10)
           #34     runZoned (dart:async/zone.dart:1500:12)
           #35     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:265:5)
           #36     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:212:24)
           <asynchronous suspension>
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56)
           #38     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           <asynchronous suspension>
           #39     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1132:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #52     _rootRunUnary (dart:async/zone.dart:1132:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #57     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #60     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
           #62     _rootRunUnary (dart:async/zone.dart:1132:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
           #71     _rootRunUnary (dart:async/zone.dart:1136:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[  +93 ms] Running build completed, took 464ms

[        ] Caching finalized dependency graph...
[   +4 ms] Caching finalized dependency graph completed, took 60ms

[   +2 ms] Error compiling dartdevc module:flutter_highlight|lib/flutter_highlight.ddc.js

           packages/flutter_highlight/flutter_highlight.dart:95:30: Error: The getter 'highlight' isn't defined for the class 'HighlightView'.
            - 'HighlightView' is from 'package:flutter_highlight/flutter_highlight.dart' ('packages/flutter_highlight/flutter_highlight.dart').
           Try correcting the name to the name of an existing getter, or defining a getter or field named 'highlight'.
                     children: _convert(highlight.parse(source, language: language).nodes),
                                        ^^^^^^^^^

[   +1 ms] Failed after 533ms
[  +15 ms] Building application for the web... (completed in 8.3s)
[   +1 ms] "flutter run" took 13,029ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:244:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:496:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:556:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:222:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///Users/z/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```

```

```
[✓] Flutter (Channel dev, v1.10.16, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.10.16 at /Users/z/github/flutter
    • Framework revision 798e4272a2 (5 天前), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/z/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • iPhone 11 Pro • 5E6E3EA5-220F-4737-897E-4CAB0043079E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome        • chrome                               • web-javascript • Google Chrome 78.0.3904.97
    • Web Server    • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

### LINKED ISSUE #45798: [web] FileSystemException: Cannot open file
Multiple dart.exe processes were started in the background When I run 'flutter run -d chrome', leading to an error: 

```
FileSystemException: Cannot open file, path =
'C: \ Users \ chenwanjin \ AppData \ Local \ Temp \ scratch_spaceada79580-1272-11ea-a949-c46516304869 \ packages \ flutter \ src \ gestures \ arena.ddc.js' (OS Error: Another program is using this file, The process is inaccessible.
, errno = 32).

```
Here is my terminal log:
<details>
  <summary>log 1</summary>

```
[  +17 ms] executing: [D:\install\flutter\] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cf37c2cd07a1d3ba296efff2dc75e19ba65e1665
[        ] executing: [D:\install\flutter\] git describe --match v*.*.* --first-parent --long   
--tags
[  +36 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13-0-gcf37c2cd0
[   +5 ms] executing: [D:\install\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [D:\install\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [D:\install\flutter\] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +79 ms] executing: D:\install\AndroidSDK\platform-tools\adb.exe devices -l
[  +40 ms] Exit code 0 from: D:\install\AndroidSDK\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping       
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.      
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.   
[ +114 ms] Generating
D:\project\flutter_web\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +89 ms] Launching lib\main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[+6561 ms] Starting daemon...
[ +111 ms] Initializing inputs
[   +9 ms] Reading cached asset graph...
[ +140 ms] Reading cached asset graph completed, took 138ms

[ +183 ms] Checking for updates since last build...
[ +432 ms] Checking for updates since last build completed, took 432ms

[   +7 ms] Initializing inputs
[  +18 ms] Reading cached asset graph...
[   +4 ms] Reading cached asset graph completed, took 138ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 432ms
[ +212 ms] Serving DevTools at http://127.0.0.1:49550

[ +705 ms] About to build [web]...
[   +6 ms] Running build...
[   +6 ms] Running build completed, took 63ms

[   +1 ms] Caching finalized dependency graph...
[   +4 ms] Caching finalized dependency graph completed, took 90ms

[  +12 ms] FileSystemException: Cannot open file, path =

'C:\Users\chenwanjin\AppData\Local\Temp\scratch_spaceada79580-1272-11ea-a949-c46516304869\packag           es\collection\src\canonicalized_map.ddc.js' (OS Error: 另一个程序正在使用此文件，进程
无法访问。
           , errno = 32)
[   +6 ms] #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
           #1      _rootRunUnary (dart:async/zone.dart:1134:38)
           #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #3      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
           #4      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:680:45)
           #5      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
           #6      Future._completeWithValue (dart:async/future_impl.dart:524:5)
           #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)           #8      _rootRun (dart:async/zone.dart:1126:13)
           #9      _CustomZone.run (dart:async/zone.dart:1023:19)
           #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
           #11     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:965:23)
           #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)  
           #15     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:175:5)

[  +31 ms] FileSystemException: Cannot open file, path =

'C:\Users\chenwanjin\AppData\Local\Temp\scratch_spaceada79580-1272-11ea-a949-c46516304869\packag           es\flutter\src\gestures\arena.ddc.js' (OS Error: 另一个程序正在使用此文件，进程无法访
问。
           , errno = 32)
[   +2 ms] #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
           #1      _rootRunUnary (dart:async/zone.dart:1134:38)
           #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #3      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
           #4      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:680:45)
           #5      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
           #6      Future._completeWithValue (dart:async/future_impl.dart:524:5)
           #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)           #8      _rootRun (dart:async/zone.dart:1126:13)
           #9      _CustomZone.run (dart:async/zone.dart:1023:19)
           #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
           #11     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:965:23)
           #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)  
           #15     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:175:5)

[  +18 ms] AssetNotFoundException: collection|lib/src/canonicalized_map.ddc.js
[   +9 ms] #0      bootstrapDdc
(package:build_web_compilers/src/dev_compiler_bootstrap.dart:147:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build
           (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21) 
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
           #5      Future.wait (dart:async/future.dart:393:26)
           #6      runBuilder.<anonymous closure>
           (package:build/src/generate/run_builder.dart:61:36)
           #7      _rootRun (dart:async/zone.dart:1126:13)
           #8      _CustomZone.run (dart:async/zone.dart:1023:19)
           #9      _runZoned (dart:async/zone.dart:1518:10)
           #10     runZoned (dart:async/zone.dart:1502:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous 
           closure> (package:build_runner_core/src/generate/build_impl.dart:478:19)
           #14     _NoOpBuilderActionTracker.trackStage
           (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:476:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:434:22)
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput
           (package:build_runner_core/src/generate/build_impl.dart:430:17)
           #20     _SingleBuild._runBuilder.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:378:38)
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
           #22     Future.wait (dart:async/future.dart:393:26)
           #23     _SingleBuild._runBuilder
           (package:build_runner_core/src/generate/build_impl.dart:377:36)
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:323:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase
           (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:319:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases
           (package:build_runner_core/src/generate/build_impl.dart:313:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)     
           #30     _SingleBuild._safeBuild.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:270:26)
           #31     _rootRun (dart:async/zone.dart:1126:13)
           #32     _CustomZone.run (dart:async/zone.dart:1023:19)
           #33     _runZoned (dart:async/zone.dart:1518:10)
           #34     runZoned (dart:async/zone.dart:1502:12)
           #35     _SingleBuild._safeBuild
           (package:build_runner_core/src/generate/build_impl.dart:265:5)
           #36     _SingleBuild.run
           (package:build_runner_core/src/generate/build_impl.dart:212:24)
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56) 
           #38     BuildRunnerDaemonBuilder.build
           (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           #39     Server._build.<anonymous closure>
           (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure>
           (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1134:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)  
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)        
           #48     _SyncStreamControllerDispatch._sendData
           (dart:async/stream_controller.dart:766:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure>
           (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #52     _rootRunUnary (dart:async/zone.dart:1134:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)  
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)        
           #57     _SinkTransformerStreamSubscription._add
           (dart:async/stream_transformers.dart:70:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd
           (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #60     _WebSocketProtocolTransformer.add
           (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData
           (dart:async/stream_transformers.dart:122:24)
           #62     _rootRunUnary (dart:async/zone.dart:1134:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)  
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)        
           #67     _SyncStreamControllerDispatch._sendData
           (dart:async/stream_controller.dart:766:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
           #71     _rootRunUnary (dart:async/zone.dart:1138:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)  
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)        
           #76     _SyncStreamControllerDispatch._sendData
           (dart:async/stream_controller.dart:766:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33) 
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)  
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)  
           #84     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:175:5)

[  +55 ms] Failed after 172ms
[  +20 ms] Building application for the web... (completed in 8.6s)
[   +6 ms] "flutter run" took 8,959ms.
Failed to build application for the Web.

```

</details>

<details>
  <summary>log 2</summary>

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DwdsResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:659:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)   
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)   
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)   
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)   
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#23     IosProject.isSwift (package:flutter_tools/src/project.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)   
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)   
#29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)       
#36     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5) 
```

</details>

And my flutter doctor log:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.12.13, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (2 available)

! Doctor found issues in 2 categories.
```

### LINKED ISSUE #46877: flutter web Unable to find modules because of main function in a helper class
## Steps to Reproduce

I have a time class which include a main method for testing purpose

```
void main() async {
  final ConfigModel result = await ConfigProvider()
      .getConfigs(ConfigRequest(accessCode: CONFIG_ACCESS_CODE));
  print(result.toJson());
}

```
**Target Platform:** Web

## Logs

```
[  +16 ms] Unable to find modules for some sources, this is usually the result of either a
           bad import, a missing dependency in a package (or possibly a dev_dependency
           needs to move to a real dependency), or a build failure (if importing a
           generated file).
           
           Please check the following imports:
           
           `import 'generated_plugin_registrant.dart';` from|lib/utils/time_web_entrypoint.dart at 5:1
```

```

[✓] Flutter (Channel master, v1.13.1-pre.99, on Mac OS X 10.15 19A602, locale en-US)
    • Flutter version 1.13.1-pre.99 at /Users//Development/flutter
    • Framework revision 354f80b84a (12 hours ago), 2019-12-11 16:36:03 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users//Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

## Expected

Android and iOS it works fine but in Web building, it makes a problem

### LINKED ISSUE #47115: [web] - Uncaught Assertion failed - Failing to load Generated JavaScript files - White Screen and error in console when running Flutter for Web app
Hi. I am able to fully build and run the flutter web app on my local using `flutter run -d chrome`.

The problem occurs **only** when I'm building the web app for release mode. I have tried everything that I can to resolve this... but without success. This is my last resort.

I've discovered that this happens because the built JavaScript files are failing to be loaded. When I look at the local (debug) build... I see that one of these files are getting loaded...

`http://localhost:57344/packages/SiyakhulaDevelopmentAcademy/main_web_entrypoint.ddc.js`

So my question is how do I get my release build to be able to successfully load the generated JavaScript files ???

Please help.

## Steps to Reproduce

1. ... `flutter channel beta` or `flutter channel dev` or `flutter channel master`
2. ... `flutter build web`
3. ... start server in `web` directory.

**Target OS version/browser: *Web*
**Devices: *chrome*

## Flutter Doctor

```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.10240], locale en-ZA)
    • Flutter version 1.12.13+hotfix.6 at C:\flutter
    • Framework revision 18cd7a3601 (5 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Marvin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

## Console Output

```
js_helper.dart:1342 Uncaught Assertion failed
    at Object.d (localhost:8080/main.dart.js:1744:3)
    at Object.U (localhost:8080/main.dart.js:1750:23)
    at localhost:8080/main.dart.js:7403:3
    at OT.a (localhost:8080/main.dart.js:2557:72)
    at OT.$2 (localhost:8080/main.dart.js:18265:23)
    at Object.ac (localhost:8080/main.dart.js:2544:20)
    at Object.w6 (localhost:8080/main.dart.js:7422:10)
    at localhost:8080/main.dart.js:42009:8
    at localhost:8080/main.dart.js:42004:55
    at dartProgram (localhost:8080/main.dart.js:42007:84)
```

## More Errors
```
Could not load content for org-dartlang-sdk:///sdk/lib/collection/iterable.dart : HTTP status code: 404
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Updates the implementation of the web runner to use the frontend server (previously, experimental incremental compiler config). This should improve compile times, as well as reduce some of the occurrences of crashes due to us embedding build_runner incorrectly.

Fixes https://github.com/flutter/flutter/issues/41951

### Closes

Fixes https://github.com/flutter/flutter/issues/49838
Fixes https://github.com/flutter/flutter/issues/49479
Fixes https://github.com/flutter/flutter/issues/49002
Fixes https://github.com/flutter/flutter/issues/48481
Fixes https://github.com/flutter/flutter/issues/47115
Fixes https://github.com/flutter/flutter/issues/46877
Fixes https://github.com/flutter/flutter/issues/44698
Fixes https://github.com/flutter/flutter/issues/44552
Fixes https://github.com/flutter/flutter/issues/43639
Fixes https://github.com/flutter/flutter/issues/41544
Fixes https://github.com/flutter/flutter/issues/40481
Fixes https://github.com/flutter/flutter/issues/38797
Fixes https://github.com/flutter/flutter/issues/45798

### Might help

https://github.com/flutter/flutter/issues/49103
https://github.com/flutter/flutter/issues/47732
https://github.com/flutter/flutter/issues/44459

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Sorry @zanderso

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 1]
```diff
@@ -44,18 +47,49 @@ class WebAssetServer {
...
+    String hostname,
+    int port,
+    UrlTunneller urlTunneller,
+    BuildMode buildMode,
+    bool enableDwds,
+  ) async {
     try {
       final InternetAddress address = (await InternetAddress.lookup(hostname)).first;
       final HttpServer httpServer = await HttpServer.bind(address, port);
       final Packages packages =
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: no newline after an '='

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 2]
```diff
@@ -44,18 +47,49 @@ class WebAssetServer {
...
-      return WebAssetServer(httpServer, packages, address,
-          onError: (dynamic error, StackTrace stackTrace) {
-        httpServer.close(force: true);
-        throwToolExit(
-            'Unhandled exception in web development server:\n$error\n$stackTrace');
-      });
+      final WebAssetServer server = WebAssetServer(httpServer, packages, address);
+
+      // In debug builds, spin up DWDS and the full asset server.
+      if (buildMode == BuildMode.debug) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: nit: flip the sense and unindent the larger part.

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 3]
```diff
@@ -80,97 +113,56 @@ class WebAssetServer {
...
-  Future<void> _handleRequest(HttpRequest request) async {
-    final HttpResponse response = request.response;
+  @visibleForTesting
+  Future<shelf.Response> handleRequest(shelf.Request request) async {
+    final Map<String, String> headers = <String, String>{};
     // If the response is `/`, then we are requesting the index file.
-    if (request.uri.path == '/') {
+    if (request.url.path == '/' || request.url.path.isEmpty) {
       final File indexFile = globals.fs.currentDirectory
           .childDirectory('web')
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: 2 space indent on continued line

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 4]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+    File file = globals.fs.file(globals.fs.currentDirectory.uri.resolve(path));
+    final List<String> segments = path.split('/');
+    if (segments.first.isEmpty) {
+      segments.removeAt(0);
+    }
+    // If both of the lookups above failed, the file might have been a package
+    // file which is signaled by a `/packages/<package>/<path>` request.
+    if (!file.existsSync() && segments.first == 'packages') {
+      file = globals.fs.file(_packages.resolve(Uri(
+          scheme: 'package', pathSegments: segments.skip(1))));
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: 2 space indent on continued line here and below

balance newlines for parens:
```dart
file = globals.fs.file(_packages.resolve(Uri(
  scheme: 'package', pathSegments: segments.skip(1),
)));
```

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 5]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+    // If this is a dart file, it must be on the local file system and is
+    // likely coming from a source map request. Attempt to look in the
+    // local filesystem for it, and return a 404 if it is not found. The tool
+    // doesn't currently consider the case of Dart files as assets.
+    File file = globals.fs.file(globals.fs.currentDirectory.uri.resolve(path));
+    final List<String> segments = path.split('/');
+    if (segments.first.isEmpty) {
+      segments.removeAt(0);
+    }
+    // If both of the lookups above failed, the file might have been a package
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: Both of what lookups above?

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 6]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+    // file which is signaled by a `/packages/<package>/<path>` request.
+    if (!file.existsSync() && segments.first == 'packages') {
+      file = globals.fs.file(_packages.resolve(Uri(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: Re-setting `file` made this method difficult to read for me. How about making a new local for each test?

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 7]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+  /// Connect and retrieve the [DebugConnection] for the current application.
+  ///
+  /// Only calls [AppConnection.runMain] on the subsequent connections.
+  Future<ConnectionResult> connect(bool useDebugExtension) {
+    final Completer<ConnectionResult> firstConnection = Completer<ConnectionResult>();
+    _connectedApps = dwds.connectedApps.listen((AppConnection appConnection) async {
+      final DebugConnection debugConnection = useDebugExtension
+        ? await (_cachedExtensionFuture ??= dwds.extensionDebugConnections.stream.first)
+        : await dwds.debugConnection(appConnection);
+      if (!firstConnection.isCompleted) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: nit: think positive

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 8]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+
+  Future<DebugConnection> _cachedExtensionFuture;
+  StreamSubscription<void> _connectedApps;
+
+  /// Connect and retrieve the [DebugConnection] for the current application.
+  ///
+  /// Only calls [AppConnection.runMain] on the subsequent connections.
+  Future<ConnectionResult> connect(bool useDebugExtension) {
+    final Completer<ConnectionResult> firstConnection = Completer<ConnectionResult>();
+    _connectedApps = dwds.connectedApps.listen((AppConnection appConnection) async {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: listen should generally have an `onError`

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 9]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+      final DebugConnection debugConnection = useDebugExtension
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: If this `listen` callback throws an exception it will be an unhandled exception.

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 10]
```diff
@@ -321,24 +411,27 @@ class WebDevFS implements DevFS {
...
+
     if (bundleFirstUpload) {
-      final String entrypoint = PackageUriMapper(mainPath, '.packages', null, null)
-        .map(mainPath)
-        ?.pathSegments?.join('/');
+      generator.addFileSystemRoot(outputDirectoryPath);
+      final String entrypoint = globals.fs.path.basename(mainPath);
       webAssetServer.writeFile('/manifest.json', '{"info":"manifest not generated in run mode."}');
       webAssetServer.writeFile('/flutter_service_worker.js', '// Service worker not loaded in run mode.');
       webAssetServer.writeFile(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: 2 space indent, paren style.

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 11]
```diff
@@ -435,3 +535,44 @@ String _filePathToUriFragment(String path) {
   }
   return path;
 }
+
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: extra newline

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 12]
```diff
@@ -4,6 +4,36 @@
 
 import 'package:meta/meta.dart';
 
+const String _currentDirectoryScript = r'''
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: A comment explaining the dark magic below could help a lot.

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 13]
```diff
@@ -4,6 +4,36 @@
...
+var _currentDirectory = (function () {
+  var _url;
+  var lines = new Error().stack.split('\n');
+  function lookupUrl() {
+    if (lines.length > 2) {
+      var match = lines[1].match(/^\s+at (.+):\d+:\d+$/);
+      // Chrome.
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: nit: move to previous line?

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 14]
```diff
@@ -56,7 +86,7 @@ window.\$hotReloadHook = function(modules) {
         if (reloadCount == modules.length) {
           require(["$entrypoint", "dart_sdk"], function(app, dart_sdk) {
             // See L81 below for an explanation.
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: L81 is actually above. That's probably not a good way to create permalinks to code.

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 15]
```diff
@@ -70,9 +100,79 @@ window.\$hotReloadHook = function(modules) {
...
+         }
+       });
+     },
+     getModuleLibraries: null, // set up by _initializeTools
+   };
+}
+let modulePaths = {};
+let customModulePaths = {};
+window.\$dartLoader.rootDirectories.push(window.location.origin + baseUrl);
+for (let moduleName of Object.getOwnPropertyNames(modulePaths)) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: What causes `modulePaths` to become non-empty between 3 lines above and this line?

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 16]
```diff
@@ -70,9 +100,79 @@ window.\$hotReloadHook = function(modules) {
...
+         if (typeof callback != 'undefined') {
+           callback();
+         }
+       });
+     },
+     getModuleLibraries: null, // set up by _initializeTools
+   };
+}
+let modulePaths = {};
+let customModulePaths = {};
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: This variable seems to be populated but never used.

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 17]
```diff
@@ -44,18 +47,49 @@ class WebAssetServer {
...
+          logWriter: (Level logLevel, String message) => globals.printTrace(message)
+        );
+        shelf.Pipeline pipeline = const shelf.Pipeline();
+        if (enableDwds) {
+          pipeline = pipeline.addMiddleware(dwds.middleware);
+        }
+        final shelf.Handler dwdsHandler = pipeline.addHandler(server.handleRequest);
+        final shelf.Cascade cascade = shelf.Cascade()
+          .add(dwds.handler)
+          .add(dwdsHandler);
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: Should this be behind `if (enableDwds)` too?

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 11 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 10 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 9 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Updated to forward the error through the completer

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 8 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 7 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Outdated, removed

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 18]
```diff
@@ -870,11 +658,11 @@ class _DwdsResidentWebRunner extends ResidentWebRunner {
         });
       }
     }
-    if (websocketUri != null) {
+     if (websocketUri != null) {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 19]
```diff
@@ -511,7 +537,7 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
       final Uri generatedImport = packageUriMapper.map(generatedPath);
 
       final String entrypoint = <String>[
-        'import "${packageUriMapper.map(main)}" as entrypoint;',
+        'import "${packageUriMapper.map(main) ?? 'file://$main'}" as entrypoint;',
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 20]
```diff
@@ -473,19 +494,24 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
     } finally {
       status.stop();
     }
+
     final String verb = fullRestart ? 'Restarted' : 'Reloaded';
     globals.printStatus('$verb application in ${getElapsedAsMilliseconds(timer.elapsed)}.');
-    if (!fullRestart) {
+
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 21]
```diff
@@ -442,27 +442,48 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
...
+      if (!deviceIsDebuggable) {
+        globals.printStatus('Recompile complete. Page requires refresh.');
+      } else if (fullRestart || !debuggingOptions.buildInfo.isDebug) {
         // On non-debug builds, a hard refresh is required to ensure the
         // up to date sources are loaded.
         await _wipConnection?.sendCommand('Page.reload', <String, Object>{
           'ignoreCache': !debuggingOptions.buildInfo.isDebug,
         });
-      } else {
+      }  else {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 22]
```diff
@@ -442,27 +442,48 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
       progressId: 'hot.restart',
     );
 
-    final UpdateFSReport report = await _updateDevFS(fullRestart: fullRestart);
-    if (report.success) {
-      device.generator.accept();
+    String reloadModules;
+    if (!debuggingOptions.buildInfo.isDebug) {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 23]
```diff
@@ -155,9 +138,12 @@ abstract class ResidentWebRunner extends ResidentRunner {
       return;
     }
     await _stdOutSub?.cancel();
-    await _webFs?.stop();
     await device.device.stopApp(null);
-    _generatedEntrypointDirectory?.deleteSync(recursive: true);
+    try {
+      _generatedEntrypointDirectory?.deleteSync(recursive: true);
+    } on FileSystemException {
+      // Best effort to clean up temp dirs.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 24]
```diff
@@ -0,0 +1,249 @@
...
+        }
+      },
+      buildMode: daemon.BuildMode.Manual,
+    );
+  }
+
+  /// Retrieve the asset server port for the current daemon.
+  int assetServerPort(Directory workingDirectory) {
+    final String portFilePath = globals.fs.path.join(daemon.daemonWorkspace(workingDirectory.path), '.asset_server_port');
+    return int.tryParse(globals.fs.file(portFilePath).readAsStringSync());
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Removed since this is no longer used

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 25]
```diff
@@ -0,0 +1,249 @@
...
+
+  Future<BuildDaemonClient> _connectClient(
+    String workingDirectory, {
+    bool release,
+    bool profile,
+    bool hasPlugins,
+    bool initializePlatform,
+    WebTestTargetManifest testTargets,
+  }) {
+    final String flutterToolsPackages = globals.fs.path.join(Cache.flutterRoot, 'packages', 'flutter_tools', '.packages');
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 26]
```diff
@@ -0,0 +1,249 @@
...
+        initializePlatform: initializePlatform,
+        testTargets: testTargets,
+      );
+      _registerBuildTargets(client, testTargets);
+      return client;
+    } on OptionsSkew {
+      throwToolExit(
+        'Incompatible options with current running build daemon.\n\n'
+        'Please stop other flutter_tool instances running in this directory '
+        'before starting a new instance with these options.');
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 27]
```diff
@@ -0,0 +1,249 @@
...
+      });
+      if (result.status == BuildStatus.failed) {
+        success = false;
+        break;
+      }
+      if (result.status == BuildStatus.succeeded) {
+        break;
+      }
+    }
+    if (success && testOutputDir != null) {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 28]
```diff
@@ -0,0 +1,249 @@
...
+          })
+          .toList(),
+      ),
+    );
+    client.startBuild();
+    bool success = true;
+    await for (final BuildResults results in client.buildResults) {
+      final BuildResult result = results.results.firstWhere((BuildResult result) {
+        return result.target == 'web';
+      });
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 29]
```diff
@@ -0,0 +1,249 @@
...
+    String projectName,
+    bool initializePlatform,
+  }) async {
+    // Create the .dart_tool directory if it doesn't exist.
+    projectDirectory
+      .childDirectory('.dart_tool')
+      .createSync();
+    final FlutterProject flutterProject = FlutterProject.fromDirectory(projectDirectory);
+    final bool hasWebPlugins = findPlugins(flutterProject)
+        .any((Plugin p) => p.platforms.containsKey(WebPlugin.kConfigKey));
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 30]
```diff
@@ -0,0 +1,249 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:async';
+
+import 'package:build_daemon/constants.dart' as daemon;
+import 'package:build_daemon/client.dart';
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 31]
```diff
@@ -0,0 +1,249 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 32]
```diff
@@ -80,97 +113,56 @@ class WebAssetServer {
...
+      return shelf.Response.notFound('');
     }
 
-    // TODO(jonahwilliams): better path normalization in frontend_server to remove
-    // this workaround.
-    String requestPath = request.uri.path;
-    if (requestPath.startsWith(_drivePath)) {
-      requestPath = requestPath.substring(3);
-    }
+    // NOTE: shelf removes trailing `/` for some reason.
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: nit: you mean the leading?

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 5 above)
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: nit: which two lookups is this referring to?

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 33]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
     }
     return modules;
   }
+
+  // Attempt to resolve `path` to a dart file.
+  File _resolveDartFile(String path) {
+    // If this is a dart file, it must be on the local file system and is
+    // likely coming from a source map request. Attempt to look in the
+    // local filesystem for it, and return a 404 if it is not found. The tool
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: Should the comment about 404 move somewhere else? This function cannot return 404.

File: packages/flutter_tools/lib/src/web/devfs_web.dart [hunk 34]
```diff
@@ -256,18 +247,110 @@ class WebAssetServer {
...
+  Future<ConnectionResult> connect(bool useDebugExtension) {
+    final Completer<ConnectionResult> firstConnection = Completer<ConnectionResult>();
+    _connectedApps = dwds.connectedApps.listen((AppConnection appConnection) async {
+      final DebugConnection debugConnection = useDebugExtension
+        ? await (_cachedExtensionFuture ??= dwds.extensionDebugConnections.stream.first)
+        : await dwds.debugConnection(appConnection);
+      if (!firstConnection.isCompleted) {
+        firstConnection.complete(ConnectionResult(appConnection, debugConnection));
+      } else {
+        appConnection.runMain();
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/web/devfs_web.dart]: nit: it's a bit strange to see a method called `connect` kick off the main.

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart [hunk 35]
```diff
@@ -157,18 +154,18 @@ void main() {
...
+  //   final Completer<DebugConnectionInfo> connectionInfoCompleter = Completer<DebugConnectionInfo>();
+  //   unawaited(residentWebRunner.run(
+  //     connectionInfoCompleter: connectionInfoCompleter,
+  //   ));
+  //   await connectionInfoCompleter.future;
 
-    expect(didSkipDwds, true);
-  }));
+  //   expect(didSkipDwds, true);
+  // }));
```
Comment (yjbanov) [inline packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: ditto

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart [hunk 36]
```diff
@@ -185,33 +182,33 @@ void main() {
...
+  //    unawaited(runner.run(
+  //     connectionInfoCompleter: connectionInfoCompleter,
+  //   ));
+  //   await connectionInfoCompleter.future;
+
+  //   // Check connect() was told to use the debug extension.
+  //   verify(mockWebFs.connect(true)).called(1);
+  //   // And ensure the debug services was started.
+  //   expect(testLogger.statusText, contains('Debug service listening on'));
+  // }));
```
Comment (yjbanov) [inline packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: ditto

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart [hunk 37]
```diff
@@ -839,12 +750,12 @@ void main() {
     onDone.complete();
 
     await result;
-    verify(mockWebFs.stop()).called(1);
+    // verify(mockWebFs.stop()).called(1);
```
Comment (yjbanov) [inline packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: Is this still needed?

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 38]
```diff
@@ -442,27 +442,48 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
...
+        await buildWeb(
+          flutterProject,
+          target,
+          debuggingOptions.buildInfo,
+          debuggingOptions.initializePlatform,
+          dartDefines,
+          false,
+        );
+      } on ToolExit {
+        return OperationResult(1, 'Failed to recompile application.');
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Yes, it will be printed as an error before the exit:

```
Launching lib/main.dart on Chrome in release mode...
Target dart2js failed: Exception: lib/main.dart:7:99:                   
Error: Expected ';' after this.
void main() => runApp(const Center(child: Text('Hello, world!', textDirection: TextDirection.ltr)))
                                                                                                  ^
lib/main.dart:8:1:
Error: Unexpected token ''.

Error: Compilation failed.


Compiling lib/main.dart for the Web...                              4.2s
Exception: Failed to compile application for the Web.

```

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: I updated this method to use different files and check+return instead of reassigning

File: packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart [hunk 39]
```diff
@@ -0,0 +1,249 @@
...
+    );
+    client.startBuild();
+    bool success = true;
+    await for (final BuildResults results in client.buildResults) {
+      final BuildResult result = results.results.firstWhere((BuildResult result) {
+        return result.target == 'web';
+      });
+      if (result.status == BuildStatus.failed) {
+        success = false;
+        break;
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_runner_compilation_delegate.dart]: In this particular case, we only want the first success

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 40]
```diff
@@ -442,27 +442,48 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
...
+        .join(',');
     }
-    final String modules = report.invalidatedModules
-      .map((String module) => '"$module"')
-      .join(',');
 
     try {
-      if (fullRestart || !debuggingOptions.buildInfo.isDebug) {
+      if (!deviceIsDebuggable) {
+        globals.printStatus('Recompile complete. Page requires refresh.');
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Lets leave this for now since it matches the current behavior

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart (hunk 37 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: Removed

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart (hunk 36 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: Removed

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart (hunk 35 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: Removed

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 34 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Its how we do --start-paused on the web. If we didn't want to pause we need to tell the "isolate" to start

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 33 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Updated comment

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 32 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: Done

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 17 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: No, we only need to disable the middleware, that is what hoists main and prevents the app from running

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 16 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: See above

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 15 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: This code and below is taken from BWC with some liberties... I'd feel more comfortable leaving it for now.

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 14 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Done

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 13 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Leaving to match original source

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 12 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Done

File: packages/flutter_tools/lib/src/compile.dart [hunk 41]
```diff
@@ -463,6 +463,9 @@ abstract class ResidentCompiler {
     List<String> dartDefines,
   }) = DefaultResidentCompiler;
 
+  // TODO(jonahwilliams): remove this hack.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/compile.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 18 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 42]
```diff
@@ -473,19 +494,24 @@ class _ExperimentalResidentWebRunner extends ResidentWebRunner {
     } finally {
       status.stop();
     }
+
     final String verb = fullRestart ? 'Restarted' : 'Reloaded';
     globals.printStatus('$verb application in ${getElapsedAsMilliseconds(timer.elapsed)}.');
-    if (!fullRestart) {
+
+
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 21 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 43]
```diff
@@ -52,19 +48,7 @@ class DwdsWebRunnerFactory extends WebRunnerFactory {
...
-        flutterProject: flutterProject,
-        debuggingOptions: debuggingOptions,
-        ipv6: ipv6,
-        stayResident: stayResident,
-        dartDefines: dartDefines,
-        // TODO(dantup): If this becomes default it may need to urlTunneller.
-      );
-    }
-    return _DwdsResidentWebRunner(
+    return _ExperimentalResidentWebRunner(
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Done

File: packages/flutter_tools/test/general.shard/resident_web_runner_test.dart [hunk 44]
```diff
@@ -85,36 +82,36 @@ void main() {
...
-    });
-    when(mockWebFs.recompile()).thenAnswer((Invocation _) {
-      return Future<bool>.value(false);
+    // when(mockWebFs.connect(any)).thenAnswer((Invocation _) async {
+    //   return ConnectionResult(mockAppConnection, mockDebugConnection);
+    // });
+    // when(mockWebFs.recompile()).thenAnswer((Invocation _) {
+    //   return Future<bool>.value(false);
+    // });
+    // when(mockWebFs.uri).thenReturn('http://localhost:8765/app/');
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/resident_web_runner_test.dart]: Removed

**Comment by jonahwilliams** [comment]
This currently doesn't work on windows, investigating...

**Comment by jonahwilliams** [comment]
Update to fix on windows, we no longer need to chop off `C:/` and friends from the source maps.

**Comment by jonahwilliams** [comment]
Ahh and the package update broke a bunch of stuff ....great

File: packages/flutter_tools/lib/src/web/devfs_web.dart (hunk 9 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/web/devfs_web.dart]: `onError` handles errors on the stream, but won't run if the listen callback throws.

**Review by zanderso — APPROVED** [review]
lgtm w/ small comment

**Comment by jonahwilliams** [comment]
I added another layer of try-catch

**Review by yjbanov — APPROVED** [review]
