### PR TITLE
Fix TwoDimensionalViewport's keep alive child not always removed (when no longer should be kept alive)

### LINKED ISSUE #138977: TableView: Hovering over an InkWell while scrolling fast causes exceptions.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using the provided code sample:
1. Run `flutter run -d macos` (`chrome` works too, or possibly any target where a mouse pointer is present).
2. Mouse over any of the purple widgets and keep the mouse pointer within its bounds.
3. Now scroll quickly across or down the list. (A trackpad may be required for this to produce the issue.)
4. Obverse that the cells stop rendering correctly and exceptions are logged to the console.

### Expected results

I would expect to be able to use `Inkwell` and similar widgets without any issues as in other scrollable widgets.

### Actual results

Scrolling over a large number of cells containing `InkWell` widgets in quick succession, while hovering over any of them, causes exceptions to be thrown.

After upgrading to Flutter v3.16.0, this issue started occurring.
I was not able to reproduce this issue in Flutter v3.13.9.
I was able to reproduce this on both macOS and in Chrome.

There are two exceptions that occur:
* `Null check operator used on a null value` when calling `RenderTableViewport#parentDataOf`.
* `The paint extent of the child has not been determined yet.` when checking if the cell is visible.

Thoughts:
* It seems this has something to do with the hover effect of `InkWell` when exiting the viewport before its next state is set.
* If the `InkWell`'s `onTap` is omitted in the provided example, no exceptions occur.

A workaround for now is to use `GestureDetector` and forgo ink feedback, but this is not an ideal user experience.

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Home'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TableView.builder(
        columnCount: 100,
        rowCount: 100,
        rowBuilder: (index) => const TableSpan(
          extent: FixedTableSpanExtent(100),
        ),
        columnBuilder: (index) => const TableSpan(
          extent: FixedTableSpanExtent(100),
        ),
        cellBuilder: (context, vicinity) => TableViewCell(
          child: SizedBox.expand(
            child: Padding(
              padding: const EdgeInsets.all(4),
              child: Material(
                color: Theme.of(context).colorScheme.secondaryContainer,
                borderRadius: BorderRadius.circular(8),
                clipBehavior: Clip.hardEdge,
                child: InkWell(
                  onTap: () {}, // <== Comment out to prevent exceptions.
                  child: Center(
                    child: Text("${vicinity.row} : ${vicinity.column}"),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/11034017/f317e9b9-e758-4da8-8ee7-0d98565d6c33

</details>

### Logs

<details><summary>Logs</summary>

```console

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY
╞═════════════════════════════════════════════════════════
The following _TypeError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was:
  TableViewport
  TableViewport:file:///Users/psengelke/.pub-cache/hosted/pub.dev/two_dimensional_scrollables-0.0
  .4/lib/src/table_view/table.dart:191:12

When the exception was thrown, this was the stack:
#0      RenderTableViewport.parentDataOf
(package:two_dimensional_scrollables/src/table_view/table.dart:332:23)
#1      RenderTwoDimensionalViewport.performLayout.<anonymous closure>.<anonymous closure>
(package:flutter/src/widgets/two_dimensional_viewport.dart:1264:17)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:451:13)
#3      Iterable.isEmpty (dart:core/iterable.dart:540:33)
#4      RenderTwoDimensionalViewport.performLayout.<anonymous closure>
(package:flutter/src/widgets/two_dimensional_viewport.dart:1265:10)
#5      RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:2657:59)
#6      PipelineOwner._enableMutationsToDirtySubtrees
(package:flutter/src/rendering/object.dart:1071:15)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#8      RenderTwoDimensionalViewport.performLayout
(package:flutter/src/widgets/two_dimensional_viewport.dart:1258:5)
#9      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#14     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:457:5)
#15     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1325:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#18     _invoke (dart:ui/hooks.dart:312:13)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#20     _drawFrame (dart:ui/hooks.dart:283:31)

The following RenderObject was being processed when the exception was fired:
RenderTableViewport#8bbee NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: TableViewport ← IgnorePointer-[GlobalKey#e889b] ← Semantics ← Listener ←
  _GestureSemantics
    ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#0335d] ← Listener ←
    _ScrollableScope ← _ScrollSemantics-[GlobalKey#aecc8] ←
    NotificationListener<ScrollMetricsNotification> ←
    _HorizontalInnerDimension-[LabeledGlobalKey<ScrollableState>#0fa42] ←
    IgnorePointer-[GlobalKey#f3c2c] ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=544.0)
  layer: OffsetLayer#63d26
  size: Size(800.0, 544.0)
This RenderObject had the following descendants (showing up to depth 5):
    (row: 6, column: 0): RenderRepaintBoundary#bf268
      child: RenderConstrainedBox#38520
        child: RenderPadding#f872e
          child: RenderPhysicalShape#fb3ba
            child: RenderCustomPaint#24868
    (row: 6, column: 1): RenderRepaintBoundary#3e879
      child: RenderConstrainedBox#69b0e
        child: RenderPadding#cf35b
          child: RenderPhysicalShape#53178
            child: RenderCustomPaint#4374b
    (row: 6, column: 2): RenderRepaintBoundary#4f98c
      child: RenderConstrainedBox#c688a
        child: RenderPadding#94d07
          child: RenderPhysicalShape#56753
            child: RenderCustomPaint#5fa30
    (row: 6, column: 3): RenderRepaintBoundary#b8ff1
      child: RenderConstrainedBox#96890
        child: RenderPadding#2cf42
          child: RenderPhysicalShape#6e988
            child: RenderCustomPaint#9c5c7
    (row: 6, column: 4): RenderRepaintBoundary#8a96b
      child: RenderConstrainedBox#cdd2d
        child: RenderPadding#ed307
          child: RenderPhysicalShape#20dcc
            child: RenderCustomPaint#37e5e
    ...(descendants list truncated after 25 lines)
═════════════════════════════════════════════════════════════════════════════════════════════════
═══

Another exception was thrown: Null check operator used on a null value


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 12.7.1 21G920 darwin-x64, locale en-ZA)
    • Flutter version 3.16.0 on channel stable at /Users/psengelke/fvm/versions/3.16.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (9 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/psengelke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/psengelke/Library/Android/sdk
    • Java binary at: /Users/psengelke/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/psengelke/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/psengelke/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.7.1 21G920 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gawi151**
- Fixes a child not removed from `_keepAliveBucket` when widget is no longer kept alive offscreen. Bug was triggering assert in performLayout.
- Adds test to cover the case from bug report

Fixes #138977

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by gawi151** [comment]
Hi, @Piinks Would be kind to review the fix?

File: packages/flutter/test/widgets/two_dimensional_utils.dart [hunk 1]
```diff
@@ -511,3 +511,39 @@ class TestParentDataWidget extends ParentDataWidget<TestExtendedParentData> {
...
+}
+
+class KeepAliveOnlyWhenHoveredState extends State<KeepAliveOnlyWhenHovered> with AutomaticKeepAliveClientMixin {
+  bool _hovered = false;
+
+  @override
+  bool get wantKeepAlive => _hovered;
+
+  @override
+  Widget build(BuildContext context) {
```
Comment (Piinks) [inline packages/flutter/test/widgets/two_dimensional_utils.dart:531]: Super clever!

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart [hunk 2]
```diff
@@ -731,6 +731,67 @@ void main() {
       );
     });
 
+    testWidgets('ensure keep alive widget is not hold onto when it no longer should be kept alive offscreen', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/two_dimensional_viewport_test.dart:734]:
```suggestion
    testWidgets('Ensure KeepAlive widget is not held onto when it no longer should be kept alive offscreen', (WidgetTester tester) async {
```

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart [hunk 3]
```diff
@@ -731,6 +731,67 @@ void main() {
...
+      // Should not trigger assert in RenderTwoDimensionalViewport.performLayout
+      // after child manager end layout. (https://github.com/flutter/flutter/issues/138977)
```
Comment (Piinks) [inline packages/flutter/test/widgets/two_dimensional_viewport_test.dart:736]:
```suggestion
      // Regression test for https://github.com/flutter/flutter/issues/138977
```

**Review by Piinks — APPROVED** [review]
LGTM with some nits, thank you for sending a PR!

File: packages/flutter/test/widgets/two_dimensional_utils.dart (hunk 1 above)
Comment (gawi151) [reply packages/flutter/test/widgets/two_dimensional_utils.dart:531]: Thx ;)

**Comment by gawi151** [comment]
@Piinks Thx for fixing wording for me ;)

**Comment by gawi151** [comment]
@Piinks, could you please assist with adding the auto-submit label to this PR? We would greatly appreciate your help in getting it merged promptly. It's crucial for us to have this included in the next bugfix release, as we are currently unable to upgrade beyond Flutter 3.13. Thank you for your support!

**Comment by Piinks** [comment]
This PR still needs one more review before it can be merged, I am working on getting that now.

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart [hunk 4]
```diff
@@ -731,6 +731,66 @@ void main() {
...
+      ));
+      await tester.pumpAndSettle();
+      expect(find.byKey(checkBoxKey), findsOneWidget);
+
+      // Scroll away, should not be kept alive (disposed).
+      verticalController.jumpTo(verticalController.position.maxScrollExtent);
+      await tester.pump();
+      expect(find.byKey(checkBoxKey), findsNothing);
+
+      // Bring back into view
```
Comment (justinmc) [inline packages/flutter/test/widgets/two_dimensional_viewport_test.dart:767]: Nit: Period here at the end.

**Review by justinmc — APPROVED** [review]
LGTM :+1:
