### PR TITLE
Drawer fix

### LINKED ISSUE #19704: The endDrawer can be dragged over the drawer
While attempting to implement "simultaneous left-and-right drawers" from #12686, I noticed that the endDrawer can be dragged over the drawer (but not vice versa) s.t. two drawers are simultaneously on the screen.

I have trouble realizing a case where the existing behavior would be useful. I suggest that one drawer's opening, should trigger the other to ignore gestures until the former's closing. At the very least, there should be a scaffold property to toggle between existing & suggested behavior, and the suggested behavior should be selected by default.

[Here](https://gist.github.com/blac3777/e3ad5279fd074f7e1fc9d9cd16cd1992) is a simple main.dart file to show the existing behavior.

### PR DESCRIPTION
**Pull request by jslavitz**
Fixes #19704

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 import 'package:flutter/foundation.dart';
 import 'package:flutter/widgets.dart';
+import 'package:flutter/material.dart';
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/drawer.dart]: import the appropriate source files from material (like below) instead of the entire lib. The circular import will break the docs shard

File: packages/flutter/lib/src/material/drawer.dart [hunk 2]
```diff
@@ -321,11 +337,15 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
   /// Typically called by [ScaffoldState.openDrawer].
   void open() {
     _controller.fling(velocity: 1.0);
+    if(widget.drawerCallback != null)
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/drawer.dart]: space between `if` and `(`, here and elsewhere

File: packages/flutter/lib/src/material/drawer.dart [hunk 3]
```diff
@@ -358,12 +378,12 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
       return new Align(
         alignment: _drawerOuterAlignment,
         child: new GestureDetector(
-          key: _gestureDetectorKey,
-          onHorizontalDragUpdate: _move,
-          onHorizontalDragEnd: _settle,
-          behavior: HitTestBehavior.translucent,
-          excludeFromSemantics: true,
-          child: new Container(width: _kEdgeDragWidth)
+            key: _gestureDetectorKey,
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/drawer.dart]: Revert unrelated change, here and elsewhere

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -1019,6 +1019,19 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
   /// Whether this scaffold has a non-null [Scaffold.endDrawer].
   bool get hasEndDrawer => widget.endDrawer != null;
 
+  bool _drawerOpened = false;
+  bool _endDrawerOpened = false;
+
+  void _drawerOpenedCallback(bool isOpened) {
+    _drawerOpened = isOpened;
+    setState(() {});
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/scaffold.dart]: For more idiomatic setState:

```
setState(() {
  _drawerOpened = isOpened;
});

```

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -1570,40 +1595,46 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
-        ),
-        _ScaffoldSlot.drawer,
-        // remove the side padding from the side we're not touching
-        removeLeftPadding: textDirection == TextDirection.rtl,
-        removeTopPadding: false,
-        removeRightPadding: textDirection == TextDirection.ltr,
-        removeBottomPadding: false,
-      );
+    if(!_endDrawerOpened) {
+      if (widget.drawer != null) {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/scaffold.dart]: Combine these if statements -
`if (widget.drawer != null && !_endDrawerOpened)`

File: packages/flutter/lib/src/material/scaffold.dart [hunk 6]
```diff
@@ -1570,40 +1595,46 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
-          child: widget.endDrawer,
-        ),
-        _ScaffoldSlot.endDrawer,
-        // remove the side padding from the side we're not touching
-        removeLeftPadding: textDirection == TextDirection.ltr,
-        removeTopPadding: false,
-        removeRightPadding: textDirection == TextDirection.rtl,
-        removeBottomPadding: false,
-      );
+    if (!_drawerOpened) {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/scaffold.dart]: Same here

File: packages/flutter/test/material/scaffold_test.dart [hunk 7]
```diff
@@ -969,6 +936,58 @@ void main() {
...
+    testWidgets('Dual Drawer Opening', (WidgetTester tester) async {
+      await tester.pumpWidget(
+        new MaterialApp(
+          home: new SafeArea(
+            left: false,
+            top: true,
+            right: false,
+            bottom: false,
+            child: new Scaffold(
+                endDrawer: new Drawer(
```
Comment (jonahwilliams) [inline packages/flutter/test/material/scaffold_test.dart]: ident by 2 lines

**Review by jonahwilliams — DISMISSED** [review]
Just a thought - maybe this is worth doing to avoid the assert. What if instead of not building one drawer when the other is opened - you changed the order in which they were built such that the open drawer is on top?

Might be a simple change that will still fix the issue without requiring an assert.

File: packages/flutter/lib/src/material/drawer.dart [hunk 8]
```diff
@@ -5,6 +5,8 @@
 import 'package:flutter/foundation.dart';
 import 'package:flutter/widgets.dart';
 
+import 'package:flutter/material.dart';
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/drawer.dart]: Don't forget to fix this import 📁

Comment (jslavitz) [reply packages/flutter/lib/src/material/drawer.dart]: But I get like 100 errors if I take it out... How do I know which specific files to include?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/drawer.dart]: On the auto import suggestion in intellij you should see an option that imports from '/material/src` - just pick those and then make them relative.

**Review by jonahwilliams — APPROVED** [review]

File: packages/flutter/lib/src/material/drawer.dart (hunk 8 above)
Comment (jslavitz) [reply packages/flutter/lib/src/material/drawer.dart]: Looks like I didn't need that import, must have not been filtering for the errors in the current file before.

**Comment by jonahwilliams** [comment]
@jslavitz This is good to submit

File: packages/flutter/lib/src/material/drawer.dart [hunk 9]
```diff
@@ -165,6 +169,7 @@ class DrawerController extends StatefulWidget {
     GlobalKey key,
     @required this.child,
     @required this.alignment,
+    this.drawerCallback,
```
Comment (Hixie) [inline packages/flutter/lib/src/material/drawer.dart]: this should be called `onFoo`, not `fooCallback`

File: packages/flutter/lib/src/material/drawer.dart [hunk 10]
```diff
@@ -180,6 +185,9 @@ class DrawerController extends StatefulWidget {
   /// close the drawer.
   final DrawerAlignment alignment;
 
+  /// Optional callback that is called when a [Drawer] is opened or closed.
+  final DrawerCallback drawerCallback;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/drawer.dart]: maybe `onDrawerChange` or some such.

Or maybe even better, have two callbacks, `onOpen` and `onClose`.

File: packages/flutter/test/material/scaffold_test.dart [hunk 11]
```diff
@@ -969,6 +936,93 @@ void main() {
       numNotificationsAtLastFrame = listenerState.numNotifications;
     });
 
+    testWidgets('Simultaneous drawers on either side', (WidgetTester tester) async {
```
Comment (Hixie) [inline packages/flutter/test/material/scaffold_test.dart]: why was this moved to the ScaffoldGeometry test section?

**Comment by Hixie** [comment]
This seems to have regressed the `stock_animation_close_first_frame_average` benchmark a little.

**Comment by jslavitz** [comment]
Where can I check out that benchmark? Maybe we could just do the set state using Future so that it doesn't get called on the first frame of the animation?

**Comment by Hixie** [comment]
I don't really understand what caused the regression. Nothing here looks like it should be slow.

https://flutter-dashboard.appspot.com/benchmarks.html has the results of the benchmarks
The benchmarks themselves are in `dev/devicelab`, there's a README there that explains how to run them locally.

**Comment by jslavitz** [comment]
So what benchmark am I looking at? The only thing I can figure is that the set state calls slowed it down? Outside of that, I agree, nothing should be causing performance issues.

**Comment by jonahwilliams** [comment]
@jslavitz lets look at them on Monday

**Comment by Hixie** [comment]
Did y'all come to any conclusion on this?
