### PR TITLE
EditableText should not allow horizontal scrolling on iOS

### LINKED ISSUE #25553: CupertinoTextField should not allow horizontal scrolling
If you have a `CupertinoTextField` and you write a lot of text in it, so it doesn't fit and you need to scroll the text, then if you scroll horizontally in the `CupertinoTextField` you can actually scroll to different positions of the text. This is not possible in native Cupertino widgets. If you try to do the same thing in a Swift/Obj-C iOS app then you will see it is not possible, you can do this only by dragging the marker selectors.

## Steps to Reproduce

Any `CupertinoTextField` is like this. This is not something specific to an isolated case.

## Logs
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-RO)
    • Flutter version 1.0.0 at /Users/tudor/dev/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Tudor’s iPhone 7 • 6c6f39c58d86256962f6a336f8ebef46f202225e • ios • iOS 12.1.2

• No issues found!
```

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #25553 

On iOS single-line TextFields are not scrollable with user input, for example a pan gesture to move the viewport. They can still be scrolled when the user drags the selection handles. Scrolling remains the same for multi-line TextFields. A user can override this by providing CupertinoTextField/TextField/EditableText with a custom `scrollPhysics`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -5923,6 +5928,19 @@ class _Editable extends MultiChildRenderObjectWidget {
   }
 }
 
+class _NeverUserScrollableScrollPhysics extends ScrollPhysics {
+  /// Creates scroll physics that does not let the user scroll, but allows for programatic scrolling.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:5932]: Nit: Maybe say that it does not let the user scroll "by dragging" or "by panning" to be more specific? Or maybe I'm being too pedantic.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -8634,6 +8634,82 @@ void main() {
     }),
   );
 
+  testWidgets(
+    'single-line field cannot be scroll with touch on iOS',
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:8638]: Nit "be scroll" => "be scrolled"

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -5584,7 +5584,12 @@ class EditableTextState extends State<EditableText>
                         excludeFromSemantics: true,
                         axisDirection: _isMultiline ? AxisDirection.down : AxisDirection.right,
                         controller: _scrollController,
-                        physics: widget.scrollPhysics,
+                        // On iOS a single-line TextField should not scroll.
+                        physics:
+                            widget.scrollPhysics ??
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:5589]: I'm glad this is overridable if the developer still wants to enabled scrolling :+1:

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -5584,7 +5584,12 @@ class EditableTextState extends State<EditableText>
                         excludeFromSemantics: true,
                         axisDirection: _isMultiline ? AxisDirection.down : AxisDirection.right,
                         controller: _scrollController,
-                        physics: widget.scrollPhysics,
+                        // On iOS a single-line TextField should not scroll.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:5587]: Good call explaining this.

**Review by justinmc — APPROVED** [review]
LGTM :+1: . Solid simple fix, we should have done something like this a long time ago.
