### PR TITLE
fix an issue with reloading when paused at a breakpoint

### LINKED ISSUE #969: hot reload doesn't work when stopped at a breakpoint
To reproduce:
  - create a new Flutter project
  - set a breakpoint at _counter++;
  - launch in debugger
  - press button to stop at breakpoint
  - press hot reload icon

At this point, a background task spins: "Intializing hot reload..." and that Flutter app is still frozen. Pressing "Resume Program" doesn't help.

A message is logged:
```
[ 984658]   WARN - o.flutter.run.daemon.DaemonApi - Flutter process returned an error: {"id":1,"error":"TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})"} 
```

Versions:
----

Flutter plugin at HEAD, 
```
$ flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 1d6a8249f8 (4 days ago) • 2017-04-27 13:34:48 -0700
Engine • revision c0f1e3b47b
Tools • Dart 1.23.0-dev.11.11
```

### PR DESCRIPTION
**Pull request by devoncarew**
- fix an issue with reloading when paused at a breakpoint; https://github.com/flutter/flutter/commit/71d80fbd3f788e8cf7c53c8d28100a24d6a1865e introduced a call to `refreshViews()`, which would never return if the isolate was paused
- fix https://github.com/flutter/flutter-intellij/issues/969

@tvolkert @a-siva

### CODE REVIEW

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 1]
```diff
@@ -563,6 +570,21 @@ class HotRunner extends ResidentRunner {
     );
   }
 
+  bool _isPaused() {
+    for (FlutterDevice device in flutterDevices) {
+      for (FlutterView view in device.views) {
+        if (view.uiIsolate != null) {
+          final ServiceEvent pauseEvent = view.uiIsolate.pauseEvent;
+          if (pauseEvent != null && pauseEvent.isPauseEvent) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/run_hot.dart]: Wouldn't `isPauseEvent` always be true for `view.uiIsolate.pauseEvent`?  Should we use an assert here instead of a condition on the `if`?

**Review by tvolkert — APPROVED** [review]
LGTM modulo the comment

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/run_hot.dart]: I think the name is a bit misleading - from the service protocol docs:
```
// The last pause event delivered to the isolate. If the isolate is
// running, this will be a resume event.
Event pauseEvent;
```

Comment (tvolkert) [inline packages/flutter_tools/lib/src/run_hot.dart]: Yuck....

Can you add a DartDoc comment to `vmservice.dart` so that gets capture on the flutter tools side as well?

Comment (devoncarew) [inline packages/flutter_tools/lib/src/run_hot.dart]: Sure, added some docs on the `pauseEvent` definition.

**Comment by tvolkert** [comment]
Thanks - LGTM
