### PR TITLE
Intercept error when iOS 18.4 crashes with JIT mode and give guided error

### LINKED ISSUE #164011: Print a guided error message when JIT fails
iOS 18.4 crashes in debug mode (see https://github.com/flutter/flutter/issues/163984). If we detect the crash, we should give a guided message with instructions to use profile or release mode or use a device < 18.4.

### PR DESCRIPTION
**Pull request by vashworth**
Adds listener to device logs during launch (before Dart VM is found) and check if iOS 18.4+ JIT crash log and give guided error message:

```
════════════════════════════════════════════════════════════════════════════════
A change to iOS has caused a temporary break in Flutter's debug mode on
physical devices.
See https://github.com/flutter/flutter/issues/163984 for details.

In the meantime, we recommend these temporary workarounds:

* When developing with a physical device, use one running iOS 18.3 or lower.
* Use a simulator for development rather than a physical device.
* If you must use a device updated to iOS 18.4+, use Flutter's release or
  profile mode via --release or --profile flags.
════════════════════════════════════════════════════════════════════════════════
```

Fixes https://github.com/flutter/flutter/issues/164011.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -39,6 +39,23 @@ import 'xcode_build_settings.dart';
...
+════════════════════════════════════════════════════════════════════════════════
+A change to iOS has caused a temporary break in Flutter's debug mode on
+physical devices.
+See https://github.com/flutter/flutter/issues/163984 for details.
+
+In the meantime, we recommend these temporary workarounds:
+
+* When developing with a physical device, use one running iOS 18.3 or lower.
+* Use a simulator for development rather than a physical device.
+* If you must use a device updated to iOS 18.4+, use Flutter's release or
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/devices.dart:55]: "iOS 18.4+" at the point this string is used do we know the iOS version the device is running, can we string interpolate the current version instead of hard-coding iOS 18.4 since we don't know what iOS version will actually land?
"If you must use a device updated to iOS 19, use Flutter's release or" ...

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 2]
```diff
@@ -39,6 +39,23 @@ import 'xcode_build_settings.dart';
...
+
+const String kJITCrashFailureInstructions = '''
+════════════════════════════════════════════════════════════════════════════════
+A change to iOS has caused a temporary break in Flutter's debug mode on
+physical devices.
+See https://github.com/flutter/flutter/issues/163984 for details.
+
+In the meantime, we recommend these temporary workarounds:
+
+* When developing with a physical device, use one running iOS 18.3 or lower.
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/ios/devices.dart:53]: This is better than nothing but likely too late since they've already upgraded. During betas, they'll have the ability to (painfully) return to 18.3, but once final is out and they stop signing 18.3 this will be too late.

Consider adding a TODO here to update this message as we learn more, and perhaps get more aggressive and publish a (smaller) warning even for those on earlier releases too.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

Thanks! This should help reduce dupe issue filings for now, but as noted, we may want to get more aggressive about adding a small warning for everyone using iOS physical devices.

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/devices.dart:54]: I think I'll file a Github issue to follow up rather than a TODO

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 3]
```diff
@@ -771,9 +796,40 @@ class IOSDevice extends Device {
...
+      app: package,
+      usingCISystem: debuggingOptions.usingCISystem,
+    );
+
+    final Stream<String> logStream = deviceLogReader.logLines;
+
+    final String deviceSdkVersion = await sdkNameAndVersion;
+
+    final StreamSubscription<String> errorListener = logStream.listen((String line) {
+      if (line.contains(kJITCrashFailureMessage)) {
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/devices.dart:825]: is the failure message the only thing in the crash log? or is there a better identifier (e.g. error code)?

**Review by hellohuanlin — APPROVED** [review]

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 2 above)
Comment (cbracken) [reply packages/flutter_tools/lib/src/ios/devices.dart:54]: sgtm! Could do both -- TODOs require a bug, and makes it easy to grep for the spot to fix later on.

**Review by jmagman — APPROVED** [review]
