### PR TITLE
Remove SHA1 check from AndroidDevice.isAppInstalled()

### LINKED ISSUE #8172: Recover from adb installation issues related to changed app signature
## Steps to Reproduce

1. Have a target Android device with some old app on it
1. Try to flutter run an app that has a different signature than the existing one

=> All kinds of unhappiness

Uninstalling the app, and then re-running resolved it, but we should be able to handle this / provide a better error.

```
mit-macbookpro2:hello_world mit$ flutter run -d 00ca05b380789730
Launching lib/main.dart on Nexus 5X in debug mode...
Running 'gradlew assembleDebug'...                    1.6s
Built app-debug.apk (21.8MB).
Installing android/app/build/outputs/apk/app.apk...
Failed to install android/app/build/outputs/apk/app.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.flutter.examples.HelloWorld signatures do not match the previously installed version; ignoring!]
Exception from flutter run: Exit code 1 from: /Users/mit/Library/Android/sdk/platform-tools/adb -s 00ca05b380789730 install -r android/app/build/outputs/apk/app.apk
package:flutter_tools/src/base/process.dart 241            _runWithLoggingSync
package:flutter_tools/src/base/process.dart 165            runCheckedSync
package:flutter_tools/src/android/android_device.dart 234  AndroidDevice.installApp
package:flutter_tools/src/android/android_device.dart 301  AndroidDevice.startApp.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/commands/build_apk.dart 620      buildApk.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/android/gradle.dart 247          buildGradleProjectV2.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 113            runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_tools/src/android/android_device.dart 386  AndroidDevice.startApp.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/commands/build_apk.dart 620      buildApk.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/android/gradle.dart 247          buildGradleProjectV2.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 113            runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/android/android_device.dart      AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 160                 HotRunner._run.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 184         ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                     HotRunner._run
package:flutter_tools/src/run_hot.dart 77                  HotRunner.run.<fn>
package:stack_trace                                        Chain.capture
package:flutter_tools/src/run_hot.dart 76                  HotRunner.run
package:flutter_tools/src/commands/run.dart 278            RunCommand.runCommand.<async>
```

### PR DESCRIPTION
**Pull request by jakobr-google**
The docs for isAppInstalled say 'check if a version of the given app is already installed', however the current code returns true only if it's the latest build that's installed.

This made sense in the past, when the use pattern was:

```dart
  if (!isAppInstalled(...)) installApp(...);
```

but now the usage is:

```dart
  if (isAppInstalled(...)) uninstallApp(...);
  installApp(...);
```

This has the probably unintended consequence that if you run `flutter install` or `flutter run` two times in a row with no source changes, the second invocation will uninstall the app, but the first invocation might not.

Removing the SHA1 check makes us always uninstall the app if it's installed.

Fixes #8172

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -196,10 +196,6 @@ class AndroidDevice extends Device {
     return '/data/local/tmp/sky.${app.id}.sha1';
   }
 
-  String _getDeviceApkSha1(ApplicationPackage app) {
-    return runCheckedSync(adbCommandForDevice(<String>['shell', 'cat', _getDeviceSha1Path(app)]));
-  }
-
   String _getSourceSha1(ApplicationPackage app) {
```
Comment (abarth) [inline packages/flutter_tools/lib/src/android/android_device.dart]: Is this function still used?

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
The performance of the original run is critical, because even when doing hot reload, you still go through that path often (e.g. any time you unplug your device, or any time we crash, which happens all too often still).

**Comment by jakobr-google** [comment]
Yeah, the problem is the current code doesn't work, as mentioned in the PR description. Specifically, if the current build of the app is already  installed, it will always uninstall and reinstall it. If the current build isn't installed, adb will remove the old and install the new (but only if the signatures match, hence #8172).

Running `adb uninstall` followed by `adb install` takes the same time as running `adb install -r`, at least on my system, so this specific PR doesn't make things slower.

I've filed #8295 to fix the SHA1 optimization.

File: packages/flutter_tools/lib/src/android/android_device.dart (hunk 1 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/android/android_device.dart]: Yep, to write the SHA1 to the device during install. And we'll want to use that again, but correctly this time - #8295.
