### PR TITLE
Fix simctl process exceptions not being caught

### LINKED ISSUE #39759: Throw tool exit when xcrun fails for bad plist
In dev/1.9.7:

When a plist file is not well-formatted, xcrun simctl install can fail. The tool should catch these failures and ask the user to fix the plist instead of propagating an unhandled exception. For example:

```
ProcessException: Process "/usr/bin/xcrun" exited abnormally:
...
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy ...
  Command: /usr/bin/xcrun simctl install [device id] .../example/build/ios/iphonesimulator/Runner.app
  | at runCheckedAsync | (process.dart:339 )
  | at <asynchronous gap> | (async )
  | at SimControl.install | (simulators.dart:145 )
  | at IOSSimulator._setupUpdatedApplicationBundle | (simulators.dart:435 )
  | at <asynchronous gap> | (async )
  | at IOSSimulator.startApp | (simulators.dart:338 )
  | at <asynchronous gap> | (async )
  | at FlutterDevice.runHot | (resident_runner.dart:378 )
...
```

/cc @christopherfujino @jmagman

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Fixes `simctl` process exceptions not being caught because an async call in a try/catch wasn't being awaited.

Also added direct injection to `IOSSimulatorUtils`, `SimControl` and `IOSSimulator` classes.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39759.

## Tests

Added tests to verify `SimControl` methods properly caught process exceptions and emitted tool exits. Also refactored many tests to directly inject dependencies to `IOSSimulatorUtils` and `SimControl` classes.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 1]
```diff
@@ -139,10 +164,10 @@ class SimControl {
     ]);
   }
 
-  Future<RunResult> install(String deviceId, String appPath) {
-    Future<RunResult> result;
+  Future<RunResult> install(String deviceId, String appPath) async {
+    RunResult result;
     try {
-      result = processUtils.run(
+      result = await _processUtils.run(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: The issue indicates that the user might be able to avoid the ProcessExceptions by fixing a plist file. Should the `throwToolExit` include that in the message?

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 2]
```diff
@@ -187,7 +212,7 @@ class SimControl {
 
   Future<void> takeScreenshot(String deviceId, String outputPath) async {
     try {
-      await processUtils.run(
+      await _processUtils.run(
         <String>[_xcrunPath, 'simctl', 'io', deviceId, 'screenshot', outputPath],
         throwOnError: true,
       );
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: I'm not sure failing to take a screenshot should throw a tool exit. Maybe it should just print an error and continue?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/simulators.dart]: Done.

File: packages/flutter_tools/lib/src/ios/simulators.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/ios/simulators.dart]: Done.

**Review by zanderso — APPROVED** [review]
