### PR TITLE
Throw StateError when implicitView is null on `wrapWithDefaultView`.

### LINKED ISSUE #153198: `Unexpected null value` error appears when running multiView on Flutter Web
### Steps to reproduce

Create new Flutter project on "stable" branch
Add flutter_bootstrap.js to web folder
Configure the engineInitializer to use multiViewEnabled: true
Run "flutter build web"
Run "flutter run -d chrome"

### Expected results

Example code completes without error, allows Flutter app to be loaded in a <div> with a subsequent runApp() call.

### Actual results

App experiences an uncaught exception when trying to call <app>.runApp() and crashes

### Code sample

<details open><summary>Code sample</summary>

```javascript
// flutter_bootstrap.js
{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
  onEntrypointLoaded: async function(engineInitializer) {
    const appRunner = await engineInitializer.initializeEngine({
      multiViewEnabled: true,
    });

    await appRunner.runApp();
  }
});
```

No changes to main.dart from initial project generation.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs
```console
When running in the Chrome Debugger:
This app is linked to the debug service: ws://127.0.0.1:49590/JGZRNP2PoDM=/ws
dom.dart:178 Rejecting promise with error: Unexpected null value.
DomConsoleExtension$124warn @ dom.dart:178
(anonymous) @ dom.dart:178
(anonymous) @ js_promise.dart:29
runUnary @ zone.dart:1661
handleError @ future_impl.dart:181
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ app_bootstrap.dart:56
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:578
runBinary @ zone.dart:1666
handleError @ future_impl.dart:178
handleError @ future_impl.dart:873
_propagateToListeners @ future_impl.dart:894
[_completeError] @ future_impl.dart:674
completeError @ async_patch.dart:496
_asyncRethrow @ async_patch.dart:562
(anonymous) @ initialization.dart:35
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
(anonymous) @ async_patch.dart:574
runUnary @ zone.dart:1661
handleValue @ future_impl.dart:163
handleValueCallback @ future_impl.dart:861
_propagateToListeners @ future_impl.dart:890
[_completeWithValue] @ future_impl.dart:666
(anonymous) @ future_impl.dart:736
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:179
Promise.then
_scheduleImmediateWithPromise @ async_patch.dart:178
_scheduleImmediate @ async_patch.dart:153
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1466
scheduleMicrotask @ zone.dart:1681
[_asyncCompleteWithValue] @ future_impl.dart:735
[_asyncComplete] @ future_impl.dart:695
complete @ async_patch.dart:484
_asyncReturn @ async_patch.dart:551
(anonymous) @ initialization.dart:234
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
initializeEngineUi @ initialization.dart:208
(anonymous) @ initialization.dart:39
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ initialization.dart:41
(anonymous) @ app_bootstrap.dart:57
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
(anonymous) @ app_bootstrap.dart:58
(anonymous) @ js_loader.dart:74
_callDartFunctionFast1 @ js_allow_interop_patch.dart:216
ret @ js_allow_interop_patch.dart:81
onEntrypointLoaded @ flutter_bootstrap.js:17
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298
flutter_bootstrap.js:19 Uncaught (in promise) null
onEntrypointLoaded @ flutter_bootstrap.js:19
await in onEntrypointLoaded
didCreateEngineInitializer @ flutter_bootstrap.js:1
(anonymous) @ initialization.dart:52
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
bootstrapEngine @ initialization.dart:27
(anonymous) @ web_entrypoint.dart:19
(anonymous) @ async_patch.dart:603
(anonymous) @ async_patch.dart:627
_asyncStartSync @ async_patch.dart:525
main$ @ web_entrypoint.dart:18
(anonymous) @ main_module.bootstrap.js:23
window.$dartRunMain @ main_module.bootstrap.js:22
(anonymous) @ unknown
runMain @ client.js:9894
(anonymous) @ client.js:26180
(anonymous) @ client.js:4009
call$2 @ client.js:12381
_asyncStartSync @ client.js:3973
$call$body$main__closure @ client.js:26196
call$1 @ client.js:26109
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_add$1 @ client.js:13600
_handleData$2 @ client.js:13663
_handleData$1 @ client.js:13626
(anonymous) @ client.js:1772
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
(anonymous) @ client.js:1827
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
_add$1 @ client.js:13267
_sendData$1 @ client.js:13112
add$1 @ client.js:12990
add$1 @ client.js:25284
call$1 @ client.js:25731
_rootRunUnary @ client.js:4397
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
_sendData$1 @ client.js:13321
perform$1 @ client.js:13502
call$0 @ client.js:13561
_rootRun @ client.js:4378
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_rootRun @ client.js:4382
run$1$1 @ client.js:13771
runGuarded$1 @ client.js:13714
call$0 @ client.js:13909
_microtaskLoop @ client.js:4241
_startMicrotaskLoop @ client.js:4247
call$1 @ client.js:12258
childList
call$1 @ client.js:12268
_scheduleAsyncCallback @ client.js:4261
_rootScheduleMicrotask @ client.js:4448
scheduleMicrotask$1 @ client.js:13826
scheduleMicrotask @ client.js:4302
schedule$1 @ client.js:13533
_addPending$1 @ client.js:13312
_sendData$1 @ client.js:13125
add$1 @ client.js:12990
call$1 @ client.js:25632
call$1 @ client.js:25548
_rootRunUnary @ client.js:4401
runUnary$2$2 @ client.js:13779
runUnaryGuarded$1$2 @ client.js:13726
call$1 @ client.js:13916
_callDartFunctionFast1 @ client.js:8307
(anonymous) @ client.js:8298

When running in a Dockerized container:
TypeError: Cannot read properties of null (reading 'toString')
    at Object.ajT (http://localhost:8080/main.dart.js:16971:3)
    at a04.$0 (http://localhost:8080/main.dart.js:51494:15)
    at http://localhost:8080/main.dart.js:28553:12
    at a_x.a (http://localhost:8080/main.dart.js:4181:63)
    at a_x.$2 (http://localhost:8080/main.dart.js:25737:14)
    at ZS.$1 (http://localhost:8080/main.dart.js:25731:21)
    at YH.VP (http://localhost:8080/main.dart.js:26317:33)
    at YH.vE (http://localhost:8080/main.dart.js:26320:13)
    at Xb.$0 (http://localhost:8080/main.dart.js:26077:11)
    at Object.mK (http://localhost:8080/main.dart.js:4276:39)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22621.3880], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\repos\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (10 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\244618\AppData\Local\Android\sdk
    • Platform android-34-ext10, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.91.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by ditman**
This PR tweaks `wrapWithDefaultView` (used by `runApp`) to raise a StateError with a legible error message when the `platformDispatcher.implicitView` is missing (for example, when enabling multi-view embedding on the web), instead of crashing with an unexpected `nullCheck` a few lines below.

* Before:
  Screenshot 2024-09-25 at 7 33 47 PM

* After:
  Screenshot 2024-09-26 at 5 01 49 PM

## Issues

* Fixes https://github.com/flutter/flutter/issues/153198

## Tests

Added a test to ensure the assertion is thrown when the `implicitView` is missing. Had to hack a little because I couldn't find any clean way of overriding the `implicitView`. The problem is that the flutter_test bindings [use `runApp` internally](https://github.com/flutter/flutter/blob/8925e1ffdfe880b06a8bc5877f017083d6652f5b/packages/flutter_test/lib/src/binding.dart#L1020) a couple of times, so I can only disable the implicitView inside the test body (and must re-enable it before returning). Not sure if it's the best way, but it seems to do the trick for this simple test case!

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -1229,6 +1229,12 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
   /// The `rootWidget` widget provided to this method must not already be
   /// wrapped in a [View].
   Widget wrapWithDefaultView(Widget rootWidget) {
+    assert(
+      platformDispatcher.implicitView != null,
+      'The implicitView is null. Cannot create a default View from `runApp`. '
+      'Try with `runWidget` instead.'
+      '${kIsWeb ? " See: https://docs.flutter.dev/platform-integration/web/embedding-flutter-web#embedded-mode":""}',
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/binding.dart:1236]: Should we make a to redirection link for this? This will allow us to ensure that we keep the link working even if we change the website’s structure

File: packages/flutter/lib/src/widgets/binding.dart [hunk 2]
```diff
@@ -1229,6 +1229,12 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
   /// The `rootWidget` widget provided to this method must not already be
   /// wrapped in a [View].
   Widget wrapWithDefaultView(Widget rootWidget) {
+    assert(
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/binding.dart:1232]: From my understanding, this error is caused by the user if they use our APIs incorrectly. Is `assert` the right thing to use here - I'd assume that should be for verifying our internal assumptions? Or should we use something like `throw FlutterError` instead?

File: packages/flutter/lib/src/widgets/binding.dart [hunk 3]
```diff
@@ -1229,6 +1229,12 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
...
+      platformDispatcher.implicitView != null,
+      'The implicitView is null. Cannot create a default View from `runApp`. '
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/binding.dart:1234]: This error uses jargon that most Flutter developers won't know. This might frustrate users.

Perhaps we should add more context? Maybe something like:

> `runApp` requires an implicit view.
>
> `runApp` renders the widget tree into a view provided by the platform,
> called the "implicit view". However, the platform did not provide an
> implicit view.
>
> Try using `runWidget` instead of `runApp`.
>
> See: https://flutter.dev/to/web-runwidget

File: packages/flutter/lib/src/widgets/binding.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/binding.dart:1232]: I guess the question is whether you want to terminate the app here in production or whether you want to keep running?

File: packages/flutter/test/widgets/multi_view_testing.dart [hunk 4]
```diff
@@ -31,3 +31,48 @@ class FakeView extends TestFlutterView {
...
+/// web when multi-view is enabled).
+///
+/// Because of how [testWidgets] uses `runApp` internally to manage the lifecycle
+/// of a test, the implicitView must be disabled/reenabled inside of the body of
+/// the [WidgetTesterCallback] under test. In practice: the implicitView is disabled
+/// in the first line of the test, and reenabled in the last.
+///
+/// See: multi_view_no_implicitView_binding_test.dart
+class NoImplicitViewWidgetsBinding extends AutomatedTestWidgetsFlutterBinding {
+  late final NoImplicitViewPlatformDispatcher _platformDispatcher = NoImplicitViewPlatformDispatcher(platformDispatcher: super.platformDispatcher);
```
Comment (justinmc) [inline packages/flutter/test/widgets/multi_view_testing.dart:66]: Why `late`?

**Review by justinmc — APPROVED** [review]
LGTM with nits.

I'm not familiar with multiview so I'm happy to defer to anyone else that might be, but I know @goderbauer is out for awhile. This looks good from my perspective though. Using `throwsA` to check the assertion seems fine.

Also it looks like there are failures.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/binding.dart:1232]: Yeah I think `assert` is probably wrong - at least it won't work when assert is disabled such as in production. I suggest `assert` be only used on errors due to wrong internal implementation. For user errors like this, we should throw errors.

> whether you want to terminate the app here in production or whether you want to keep running

Theoretically we might be able to create a default view on such errors and continue, but I think we shouldn't do it, because any configuration without an implicit view is highly expert-level and users have to explicitly specify so to run into this error.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/binding.dart:1234]: Since it's a public API, I think we should not assume it 100% comes from `runApp`. Maybe

> The app requested an implicit view, but none is found.
>
> This is likely because the app called `runApp` to start up, which expects the platform to provide a default view to render into ("the implicit view"), while the engine is configured to let the app handle view creation (which allows creating multiple views.) 
>
> Try using `runWidget` instead of `runApp`. See also https://flutter.dev/to/web-runwidget

File: packages/flutter/lib/src/widgets/binding.dart (hunk 2 above)
Comment (ditman) [reply packages/flutter/lib/src/widgets/binding.dart:1232]: Good point! I used assert to only throw while in development mode, but I agree it's silly, because this isn't recoverable and wouldn't work in production either. I'll `throw StateError` instead!

File: packages/flutter/lib/src/widgets/binding.dart (hunk 1 above)
Comment (ditman) [reply packages/flutter/lib/src/widgets/binding.dart:1236]: Yes, better, created a permalink for /to/web-multiview-runwidget here: https://github.com/flutter/website/pull/11196

File: packages/flutter/test/widgets/multi_view_testing.dart (hunk 4 above)
Comment (ditman) [reply packages/flutter/test/widgets/multi_view_testing.dart:66]: Good question!

It seems that `late` allows me to use `super` when initializing the value!

(I copied this pattern from elsewhere in tests, but it's a smart interaction between `late` and `super`, wow!)

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (ditman) [reply packages/flutter/lib/src/widgets/binding.dart]: @loic-sharma @dkwingsmt I ended up with something like this:

> The app is attempting to render into a default View that isn't available (`platformDispatcher.implicitView == null`).
> This is likely because the platform has multi-view mode enabled, but the app is calling `runApp` to render its root Widget.
> Try using `runWidget` instead of `runApp` to start your app. `runWidget` allows you to provide a `View` widget, without requiring a default on the platform.
> See: https://flutter.dev/to/web-multiview-runwidget

(Tried to use lingo closer to that in the [wrapWithDefaultView method docs](https://api.flutter.dev/flutter/widgets/WidgetsBinding/wrapWithDefaultView.html).)

File: packages/flutter/test/widgets/multi_view_testing.dart (hunk 4 above)
Comment (ditman) [reply packages/flutter/test/widgets/multi_view_testing.dart:66]: > I guess the question is whether you want to terminate the app here in production or whether you want to keep running?

Yeah, an assertion here doesn't make much sense, since this is an un-recoverable error!

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (loic-sharma) [reply packages/flutter/lib/src/widgets/binding.dart]: I slightly prefer Tong's wording.

Some context:

1. On desktop, the north star is that the app will call `runApp` even though there's no implicit view. `runApp` will know how to create a window to host the widget tree.
2. On desktop, you can have multiple views while also having an implicit view. Thus, on desktop you can call `runApp` even if you have multi-view mode enabled

What do y'all think about this? I tried to merge bits from all our messages :)

> The app requested an implicit view, but the platform doesn't have one.
> 
> This is likely because the app called `runApp` to render its root widget,
> which expects the platform to provide a default view to render into ("the implicit view").
> However, the platform likely has multi-view mode enabled, which does not create a default "implicit" view.
> 
> Try using `runWidget` instead of `runApp` to start your app. `runWidget` allows you to provide a `View` widget, without requiring a default view.
> See: https://flutter.dev/to/web-multiview-runwidget

Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/binding.dart]: Looks good!

I think checking it in wrapWithDefaultView is better than runApp since wrapWithDefaultView is also a public API and users can still call it incorrectly (which is a user error and you shouldn't assert on).

Comment (ditman) [reply packages/flutter/lib/src/widgets/binding.dart]: I'm happy with this too, I applied @loic-sharma's suggestion! If @dkwingsmt is happy, I'm happy too, let's `autosubmit` this  :P

Comment (ditman) [reply packages/flutter/lib/src/widgets/binding.dart]: > `runApp` will know how to create a window to host the widget tree.
> ...
> you can have multiple views while also having an implicit view

We need to discuss this elsewhere, I'm interested :P

**Review by loic-sharma — APPROVED** [review]
Error message looks good to me, thanks!

**Review by dkwingsmt — APPROVED** [review]
LGTM
