### PR TITLE
Fix WidgetApp.title documentation

### LINKED ISSUE #16031: MaterialApp.title doesn't affect iOS title
From the [Flutter docs on MaterialApp.title](https://docs.flutter.io/flutter/material/MaterialApp/title.html), this property is used to identify the app: 

> A one-line description used by the device to identify the app for the user.
>
> On Android the titles appear above the task manager's app snapshots which are displayed when the user presses the "recent apps" button. Similarly, on iOS the titles appear in the App Switcher when the user double presses the home button. 

On Android, this works as intended. But on iOS, the name used in the App Switcher is the name of the project, even when this property is set.

## Repo

1. From a command line, run `flutter create materialtitle`
2. In a code editor, edit `lib/main.dart` so that `MaterialApp.title` is initialized to `foobar`
3. Run `flutter run -d iPhone` to launch the app in a simulator
4. Press Command+Shift+H twice in quick succession to launch the App Switcher
5. Expected: App Switcher shows `foobar`. Actual: App Switcher shows `materialtitle`

## Environment
```
$ flutter doctor -v                                                      
[✓] Flutter (Channel master, v0.2.5-pre.57, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.5-pre.57 at /Users/timsneath/flutter
    • Framework revision c5288c7346 (2 hours ago), 2018-03-28 08:32:27 -0700
    • Engine revision dd6f46c485
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/timsneath/Library/Android/sdk
    • Android NDK at /Users/timsneath/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 7                  • 81F64B40-5DDD-45CF-A56E-E816369DA5CB • ios         • iOS 11.2 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by mklim**
Closes #16031

### CODE REVIEW

File: packages/flutter/lib/src/widgets/app.dart [hunk 1]
```diff
@@ -235,9 +235,8 @@ class WidgetsApp extends StatefulWidget {
   /// A one-line description used by the device to identify the app for the user.
   ///
   /// On Android the titles appear above the task manager's app snapshots which are
-  /// displayed when the user presses the "recent apps" button. Similarly, on
-  /// iOS the titles appear in the App Switcher when the user double presses the
-  /// home button.
+  /// displayed when the user presses the "recent apps" button. On iOS this
+  /// value cannot be used. The app's `Info.plist` is referred to instead.
```
Comment (chinmaygarde) [inline packages/flutter/lib/src/widgets/app.dart]: Maybe mention the key in the Info.plist that is read. I think it is the `CFBundleProductName`

**Review by chinmaygarde — APPROVED** [review]

File: packages/flutter/lib/src/widgets/app.dart (hunk 1 above)
Comment (mklim) [reply packages/flutter/lib/src/widgets/app.dart]: Updated. From what I can tell it's normally [`CFBundleDisplayName`](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-110725-TPXREF135), but falls back to [`CFBundleName`](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-109585) when that's unset.
