### PR TITLE
Remove device unlock from hostonly compile test

### LINKED ISSUE #100570: hello_world_ios__compile hostonly test fails when no iOS device is tethered
Test fails with no tethered device:
```
"reason": "Task failed: DeviceException: No connected physical iOS devices found."
```
However this test is only compiling the app, not running it, and should work without tethered devices.

The test is trying to unlock a tethered phone:
https://github.com/flutter/flutter/blob/5bc9340233b5c8e5d52ae9ae6b72b54f4585cc4c/dev/devicelab/lib/tasks/perf_tests.dart#L1267-L1268

https://github.com/flutter/flutter/issues/87508#issuecomment-1075422641

### PR DESCRIPTION
**Pull request by jmagman**
Reproduced locally, validates this test fails without an iOS device attached, and passes on this diff.
```
dart bin/run.dart -t hello_world_ios__compile
```
Fixes https://github.com/flutter/flutter/issues/100570

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/lib/tasks/perf_tests.dart [hunk 1]
```diff
@@ -1264,8 +1264,6 @@ class CompileTest {
 
   Future<TaskResult> run() async {
     return inDirectory<TaskResult>(testDirectory, () async {
-      final Device device = await devices.workingDevice;
-      await device.unlock();
```
Comment (keyonghan) [inline dev/devicelab/lib/tasks/perf_tests.dart:1268]: Do we also need to remove https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/hello_world_ios__compile.dart#L10

Comment (jmagman) [reply dev/devicelab/lib/tasks/perf_tests.dart:1268]: No, it's used to decide which device type to compile against.
https://github.com/flutter/flutter/blob/5bc9340233b5c8e5d52ae9ae6b72b54f4585cc4c/dev/devicelab/lib/tasks/perf_tests.dart#L1299

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/100571

File: dev/devicelab/lib/tasks/perf_tests.dart (hunk 1 above)
Comment (keyonghan) [reply dev/devicelab/lib/tasks/perf_tests.dart:1268]: Ah, I see.

BTW: are all perf tests not expected to have devices? I am wondering if any perf test needs a device and needs the `unlock` to avoid potential issues.

Comment (jmagman) [reply dev/devicelab/lib/tasks/perf_tests.dart:1268]: I think a lot of perf tests are expected to have a device.  This change only impacts `CompileTest` though, which I don't think should ever need a device.
```dart
/// Measures how long it takes to compile a Flutter app and how big the compiled
/// code is.
class CompileTest {
```

**Review by keyonghan — APPROVED** [review]
LGTM.

**Review by christopherfujino — APPROVED** [review]
nice catch, LGTM
