### PR TITLE
Fix cursor is not centered when cursorHeight is set (non-Apple platforms).

### LINKED ISSUE #143480: [Android] When setting a cursorHeight's value, the cursor position is too high
### Steps to reproduce

1. I made this TextFormField.. it uses cursor height, maybe has something to do with it:

```dart
TextFormField(
        controller: controller,
        onSaved: onSaved,
        textInputAction: TextInputAction.done,
        inputFormatters: formatter != null ? [formatter!] : null,
        keyboardType: numeric
            ? TextInputType.numberWithOptions(decimal: true)
            : TextInputType.text,
        cursorColor: AppTheme.darkLight,
        cursorHeight: 14,
        style: TextStyle(
          color: AppTheme.primaryColorDark,
          fontSize: 16,
        ),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: context.textTheme.labelLarge!.copyWith(
            color: AppTheme.darkLight,
            fontWeight: FontWeight.w400,
          ),
          contentPadding: EdgeInsets.only(bottom: 2.5, top: 12),
          enabledBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Color(0x0D000000), width: 1.5),
          ),
          focusedBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Color(0x0D000000), width: 1.5),
          ),
          suffixText: suffixText,
          suffixStyle: context.textTheme.labelMedium!.copyWith(
            color: AppTheme.darkLight,
            fontWeight: FontWeight.w400,
            fontSize: 13,
          ),
          hintText: hintText,
          hintStyle: TextStyle(color: Colors.grey, fontSize: 12),
        ),
        validator: validator,
        onTapOutside: (_) => context.scopeUnfocus(),
      ),
```
2. Use it on a samsung Galaxy s22 device.. 

### Expected results

Captura de Tela 2024-02-14 às 16 39 19

### Actual results

Captura de Tela 2024-02-14 às 16 39 57

### Code sample

<details open><summary>Code sample</summary>

```dart
TextFormField(
        controller: controller,
        onSaved: onSaved,
        textInputAction: TextInputAction.done,
        inputFormatters: formatter != null ? [formatter!] : null,
        keyboardType: numeric
            ? TextInputType.numberWithOptions(decimal: true)
            : TextInputType.text,
        cursorColor: AppTheme.darkLight,
        cursorHeight: 14,
        style: TextStyle(
          color: AppTheme.primaryColorDark,
          fontSize: 16,
        ),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: context.textTheme.labelLarge!.copyWith(
            color: AppTheme.darkLight,
            fontWeight: FontWeight.w400,
          ),
          contentPadding: EdgeInsets.only(bottom: 2.5, top: 12),
          enabledBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Color(0x0D000000), width: 1.5),
          ),
          focusedBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Color(0x0D000000), width: 1.5),
          ),
          suffixText: suffixText,
          suffixStyle: context.textTheme.labelMedium!.copyWith(
            color: AppTheme.darkLight,
            fontWeight: FontWeight.w400,
            fontSize: 13,
          ),
          hintText: hintText,
          hintStyle: TextStyle(color: Colors.grey, fontSize: 12),
        ),
        validator: validator,
        onTapOutside: (_) => context.scopeUnfocus(),
      );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale pt-BR)
    • Flutter version 3.16.9 on channel stable at /Users/danvilela/Code/Misc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • Daniel's iPhone 13 Pro (mobile) • 00008110-001A11283E38801E            • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro (mobile)          • C1C8AB6F-F631-4AF4-B90E-2D72CCE36136 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71
      darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome
      121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PRs fixes the cursor vertical position when a custom cursor height is set on non-Apple platforms (on Apple platforms the cursor is already centered) .

| Before | After |
|--------|--------|
| image | image | 

<details><summary>Code sample used for the screenshots (cursorHeight 18, font size 16, line height 2)</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      title: 'Flutter Demo',
      home: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: TextField(
          cursorHeight: 18,
          style: TextStyle(fontSize: 16, height: 2),
        ),
      ),
    );
  }
}
``` 

</details> 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/143480

## Tests

Adds 2 tests, updates 1.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_cursor_test.dart [hunk 1]
```diff
@@ -1236,7 +1236,7 @@ void main() {
       backgroundCursorColor: Colors.grey,
       controller: controller,
       focusNode: focusNode,
-      style: const TextStyle(),
+      style: const TextStyle(fontSize: 17),
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_cursor_test.dart:1239]: Why set this fontSize now?

**Review by justinmc — COMMENTED** [review]
I wonder why this was only done on Apple platforms before? I can't think of a reason why you wouldn't want this, though.

I see there are two goldens failures, but those look like an improvement if indeed no one wants a bottom aligned cursor. I've also run the Google tests, where there are probably more visual diff tests that will fail. I'll take a look at that and make sure there aren't any that look incorrect, otherwise this looks good.

**Comment by bleroux** [comment]
> I wonder why this was only done on Apple platforms before? I can't think of a reason why you wouldn't want this, though.

Centering the caret on Apple platforms was added in https://github.com/flutter/flutter/pull/31687 (at that time `cursorHeight` property did not exist). On Apple platforms because it was chosen to make the cursor bigger than `prefferedLineHeight` it was a nice idea to introduce centering logic. On Android, this same PR forced the cursor height to `_textPainter.getFullHeightForCaret` so the cursor did not need centering logic because it was admitted that the cursor height is the same as the editable height.
Custom `cursorHeight` was introduced later in https://github.com/flutter/flutter/pull/61714.
Unfortunately this PR added one test in` editable_text_cursor_test.dart` and that test restricted its target platforms to iOS and macOS. I’m not sure it was on purpose but it probably did not help to figure out that the centering behavior was missing on non Apple platforms.

File: packages/flutter/test/widgets/editable_text_cursor_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/widgets/editable_text_cursor_test.dart:1239]: Because otherwise this test is failing.
This test sets cursorHeight to 17 and did not set the font size (it defaults to 14). This is the case covered by the second test I added (cursorHeight bigger than font size).
In this case, because the cursor is bigger than the font size it will overflow the editable vertically. Before my PR the overflow was only on the bottom (the cursor was painted with a vertical position align to the top of the text and overflow on the bottom).
With my PR, when a cursorHeight is bigger than the font size, the cursor is centered so it overflows on the top and on the bottom).
I choose to change the fontSize in this test instead of changing the rect that it tested some lines later because I don't think that checking that the cursor did not overflow vertically was the goal of this test (and because I added a test for this particular case) .

**Comment by bleroux** [comment]
> I've also run the Google tests, where there are probably more visual diff tests that will fail. I'll take a look at that and make sure there aren't any that look incorrect, otherwise this looks good.

@justinmc
I rebased the PR, all checks are green but it seems that the 'Google testing' step did not run this time? Do you have to start it manually? (last week, I saw it failing on this PR, but it seems that there were some issues with CI).

File: packages/flutter/test/widgets/editable_text_cursor_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_cursor_test.dart:1239]: Thanks for the thorough explanation, I agree that this looks to be in line with the original intentions of this test :+1:

**Review by justinmc — COMMENTED** [review]
Thanks for explaining the history of the cursor centering. I've restarted the Google tests and it looks like they're working now.

**Comment by bleroux** [comment]
@justinmc
It looks like Google testing is failing consistently on this PR.
Thank you in advance for sharing any information abouth those failing tests :pray:

**Comment by justinmc** [comment]
I've approved the failing Google image diff tests. Actually what caused most of these to fail here was things like [bringIntoView](https://main-api.flutter.dev/flutter/widgets/EditableTextState/bringIntoView.html), which scrolls to a text position based on what the caret rect would be. Because we changed the position of the caret in this PR, the scroll position changed slightly whenever these kinds of things were used. Thanks to @LongCatIsLooong for figuring that out.

**Review by justinmc — APPROVED** [review]
LGTM 👍
