### PR TITLE
fix `getFullHeightForCaret` when strut is disabled.

### LINKED ISSUE #150638: TextPainter getFullHeightForCaret returns confusing values with nested TextSpans
### Steps to reproduce

Paste the following code snippet into dartpad.dev, main channel (Dart SDK 3.5.0-266.0.dev and Flutter SDK 3.23.0-13.0.pre.242):
```dart
import 'package:flutter/painting.dart';

void main() {
  final painter = TextPainter(
    text: TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: [
      TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
      TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
    ]),
    textDirection: TextDirection.ltr,
  );
  painter.layout();
  print(painter.getFullHeightForCaret(TextPosition(offset: 0), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 1), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 2), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 3), Rect.zero));
}
```

Click Run. Observe the printed output:
```
150
150
150
150
```

### Expected results

I expected to see the caret height change according to the style of the span "owning" the text position. For example, I might expect values more like:

```
150
150
37.5
75
```

because these correspond to the font size of the span directly preceding the offset. I think there could be a debate about whether the painter should look to the upstream or downstream span to retrieve the style, but either way I would not expect the caret height to be the same at all positions in this example.

### Actual results

Caret height reported as the same value, 150, for each offset in the text painter.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/painting.dart';

void main() {
  final painter = TextPainter(
    text: TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: [
      TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
      TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
    ]),
    textDirection: TextDirection.ltr,
  );
  painter.layout();
  print(painter.getFullHeightForCaret(TextPosition(offset: 0), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 1), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 2), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 3), Rect.zero));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Visual aid, the code snippet drawing to a canvas:

image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

n/a, test on dartpad.dev

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/150638

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/painting/text_painter_test.dart [hunk 1]
```diff
@@ -857,6 +857,26 @@ void main() {
       expect(caretOffset.dy, 0.0);
       painter.dispose();
     });
+
+    test('caret height reflects run height if strut is disabled', () {
+      const TextSpan span = TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: <InlineSpan>[
+        TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
+        TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
+      ]);
+      final TextPainter painter = TextPainter()
```
Comment (navaronbracke) [inline packages/flutter/test/painting/text_painter_test.dart:866]: You should probably dispose of the text painter?

**Review by justinmc — APPROVED** [review]
LGTM :+1:

**Review by goderbauer — APPROVED** [review]
LGTM
