### PR TITLE
Fix Date picker overlay colors aren't applied on selected state

### LINKED ISSUE #130586: Date picker overlay colors aren't applied on `MaterialState.selected` state.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Apply selected overlay color in `DatePickerTheme.dayOverlayColor` and  `DatePickerTheme.yearOverlayColor`
```dart
            if (states.contains(MaterialState.selected)) {
              return Colors.green;
            }
```

### Expected results

Screenshot 2023-07-14 at 18 46 42

### Actual results

Screenshot 2023-07-14 at 18 46 48

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        datePickerTheme: DatePickerThemeData(
          yearOverlayColor:
              MaterialStateProperty.resolveWith((Set<MaterialState> states) {
            print('yearOverlayColor.states: $states');
            if (states.contains(MaterialState.selected)) {
              return Colors.green;
            }
            return Colors.transparent;
          }),
          dayOverlayColor:
              MaterialStateProperty.resolveWith((Set<MaterialState> states) {
            print('dayOverlayColor.states: $states');

            if (states.contains(MaterialState.selected)) {
              return Colors.red;
            }
            return Colors.transparent;
          }),
        ),
        useMaterial3: true,
      ),
      home: Directionality(
        textDirection: TextDirection.ltr,
        child: Material(
          child: Center(
            child: DatePickerDialog(
              initialDate: DateTime(2023, DateTime.january, 25),
              firstDate: DateTime(2022),
              lastDate: DateTime(2024, DateTime.december, 31),
              currentDate: DateTime(2023, DateTime.january, 24),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.0-3.0.pre.64, on macOS 13.4.1 22F82 darwin-arm64, locale en-EE)
    ! Flutter version 3.13.0-3.0.pre.64 on channel [user-branch] at /Users/tahatesser/Code/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository git@github.com:TahaTesser/flutter.git is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 418d6a56f9 (5 hours ago), 2023-07-14 13:59:16 +0300
    • Engine revision 3a1b12a2fa
    • Dart version 3.1.0 (build 3.1.0-310.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use
      "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b829.16-10353782)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode-14.3.1.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b829.16-10353782)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes the DatePicker overlay colors for the selected days.
Before this PR, overlays were obscured by the selected day backgound.
This fix simply replaces a DecoratedBox with an Ink to make the overlays visible.
Combined with https://github.com/flutter/flutter/pull/159072 which fixes InkWell overlay color resolution related to the selected state, this PR fixes [Date picker overlay colors aren't applied on MaterialState.selected state](https://github.com/flutter/flutter/issues/130586).

Before, no overlay visible for the selected day when hovered, focused, or pressed:

https://github.com/user-attachments/assets/944d5035-68b2-40da-b606-3e8795229767

After, overlay is visible for the selected day when hovered, focused, or pressed (color change is slight as defined with M3 defaults):

https://github.com/user-attachments/assets/2627955b-f45a-465f-8eb0-21955ccd8c3e

## Related Issue

Fixes [Date picker overlay colors aren't applied on MaterialState.selected state](https://github.com/flutter/flutter/issues/130586).

## Tests

Adds 12 tests.
Updates several existing tests (those tests were looking for a `DecoratedBox`, make them look for an `Ink`).

### CODE REVIEW

File: packages/flutter/test/material/date_picker_theme_test.dart [hunk 1]
```diff
@@ -776,17 +775,25 @@ void main() {
       ),
     );
 
+    MaterialInkController findDayGridMaterial(WidgetTester tester) {
+      // All days are painted on the same Material widget.
+      // Use an arbitrary day to find this Material.
+      return Material.of(tester.element(find.text('17')));
+    }
```
Comment (nate-thegrate) [inline packages/flutter/test/material/date_picker_theme_test.dart:782]: ### 😍😍

This is wonderful, thank you

Comment (bleroux) [reply packages/flutter/test/material/date_picker_theme_test.dart:782]: Thanks!
It took me several hours to figure out that there is not one Material for each day. 
This was mainly because existing tests were carefully using the day they are interested in to look up the Material. It was ok, until I spent hours fixing one test where the circle painted for another day collides with the one I was interested in.
I created this utility function to save time for future contributors who will work on the date picker.

Comment (nate-thegrate) [reply packages/flutter/test/material/date_picker_theme_test.dart:782]: I have some mixed feelings about the Ink widget—it seems like it'd help performance by consolidating a bunch of widgets into a single ink controller, but it also has the tendency to [introduce jank](https://main-api.flutter.dev/flutter/material/Ink-class.html#limitations), and while it appears to work very similar to DecoratedBox, some things are super confusing for anyone who doesn't have a solid grasp of how painting on a Material works.

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Comment by bleroux** [comment]
Reason for revert: This PR depends on https://github.com/flutter/flutter/pull/159072 which was flagged as a perf regression in https://github.com/flutter/flutter/issues/159337. Reverting to see if the perf regression was real or not. See https://github.com/flutter/flutter/issues/159337#issuecomment-2504418480 for context.
