### PR TITLE
move resampler to handlePointerEvent and fix complex_layout_android__scroll_smoothness with PointerEvent

### LINKED ISSUE #66608: complex_layout_android__scroll_smoothness generates unexpected numbers
Unlike the numbers in https://github.com/flutter/flutter/pull/61998#issuecomment-682697104, the test is currently generating something like the following both in the device lab and in my local experiment.
```
Task result:
{
  "success": true,
  "data": {
    "janky_count_with_resampler_90Hz": 0.0,
    "average_abs_jerk_with_resampler_90Hz": 0.0,
    "dropped_frame_count_with_resampler_90Hz": 43,
    "janky_count_with_resampler_59Hz": 0.0,
    "average_abs_jerk_with_resampler_59Hz": 0.0,
    "dropped_frame_count_with_resampler_59Hz": 28,
    "janky_count_without_resampler_90Hz": 0.0,
    "average_abs_jerk_without_resampler_90Hz": 0.0,
    "dropped_frame_count_without_resampler_90Hz": 36,
    "janky_count_without_resampler_59Hz": 0.0,
    "average_abs_jerk_without_resampler_59Hz": 0.0,
    "dropped_frame_count_without_resampler_59Hz": 29
  },
  "benchmarkScoreKeys": [
    "janky_count_with_resampler_90Hz",
    "average_abs_jerk_with_resampler_90Hz",
    "dropped_frame_count_with_resampler_90Hz",
    "janky_count_with_resampler_59Hz",
    "average_abs_jerk_with_resampler_59Hz",
    "dropped_frame_count_with_resampler_59Hz",
    "janky_count_without_resampler_90Hz",
    "average_abs_jerk_without_resampler_90Hz",
    "dropped_frame_count_without_resampler_90Hz",
    "janky_count_without_resampler_59Hz",
    "average_abs_jerk_without_resampler_59Hz",
    "dropped_frame_count_without_resampler_59Hz"
  ]
}
```

The problem seems to happen after https://github.com/flutter/flutter/commit/a48e14308e41f75b6f63ee2549f4d597646b0dc4

See https://flutter-flutter-perf.skia.org/e/?begin=1599168329&end=1600967051&queries=sub_result%3Daverage_abs_jerk_with_resampler_59Hz%26sub_result%3Daverage_abs_jerk_without_resampler_59Hz%26test%3Dcomplex_layout_android__scroll_smoothness&requestType=0

### PR DESCRIPTION
**Pull request by CareF**
## Description

This is to move the resampling logic to `handlePointerEvent`, so that it's accessible to `WidgetTester`, as enabled by #64846. This also fixes #66608 and closes #66612 . 

In terms of fixing #66608, this is an alternative to #66611.  #66611 is more close to the solution before  #64846, so I suggest to land #66611 and observe for a couple of runs before merge this PR to see if the change makes some difference to the test result. 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by CareF** [comment]
No extra test is necessary because we already prepared that test that fit both current solution and previous one in #64424

File: packages/flutter/lib/src/gestures/binding.dart [hunk 1]
```diff
@@ -226,18 +221,20 @@ mixin GestureBinding on BindingBase implements HitTestable, HitTestDispatcher, H
...
-    // Stop resampler if resampling is not enabled. This is a no-op if
-    // resampling was never enabled.
-    _resampler.stop();
-
-    while (_pendingPointerEvents.isNotEmpty)
-      handlePointerEvent(_pendingPointerEvents.removeFirst());
+  /// to force resampler for triggering a resample operation.
+  ///
+  /// This should only be called when resampling is enabled.
+  void triggerResample() {
```
Comment (CareF) [inline packages/flutter/lib/src/gestures/binding.dart:235]: I'm still feeling this is a workaround, see also https://github.com/flutter/flutter/pull/60558#discussion_r496235528 
This is a public method because it's needed in `WidgetTester`.

Comment (dreveman) [reply packages/flutter/lib/src/gestures/binding.dart:235]: why is this needed in WidgetTester? If needed then maybe this is find but ideally the name would just be "sample()" instead of triggerResample.

Comment (CareF) [reply packages/flutter/lib/src/gestures/binding.dart:235]: > why is this needed in WidgetTester? If needed then maybe this is find but ideally the name would just be "sample()" instead of triggerResample.

Because `triggerResample` is called in `_flushPointerEventQueue`, which is before input injection in `WidgetTester`. `triggerResample` is in `_flushPointerEventQueue` because otherwise when `_pendingPointerEvents` is empty, we still need to call `_resampler.sample` for updated resampled event (see https://github.com/flutter/flutter/pull/60558#discussion_r496235528) @dreveman

Comment (CareF) [reply packages/flutter/lib/src/gestures/binding.dart:235]: As for the name, I'm feeling `binding.sample` is confusing because binding is not the subject of `sample`...

Comment (CareF) [reply packages/flutter/lib/src/gestures/binding.dart]: Thank to @liyuqian 's [comment](https://github.com/flutter/flutter/pull/60558/files/b7802f69f91e1b5466d6b5b58e98193160964ca5#r499014047) I realize this `triggerResample` is kind of duplicate with `_handleSampleTimeChanged`. `triggerResample` is removed in the new commit.

File: packages/flutter/lib/src/gestures/binding.dart [hunk 2]
```diff
@@ -389,14 +388,14 @@ mixin GestureBinding on BindingBase implements HitTestable, HitTestDispatcher, H
 
   void _handleSampleTimeChanged() {
     if (!locked) {
-      _flushPointerEventQueue();
+      _resampler.sample(samplingOffset);
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/binding.dart:391]: What if resamplingEnabled is false here? Should we stop the resampler instead then?

Comment (CareF) [reply packages/flutter/lib/src/gestures/binding.dart:391]: This can happen when resample was on but is turned off, and the logic should be to just discard the remaining events queued in the resampler? @dreveman

Comment (CareF) [reply packages/flutter/lib/src/gestures/binding.dart]: Updated. PTAL.

**Review by dreveman — APPROVED** [review]
lgtm

**Review by liyuqian — APPROVED** [review]
LGTM
