### PR TITLE
_SaltedKey solution to `ExpansionPanelList`

### LINKED ISSUE #11166: Expansion Panels in Tab View break due to global keys
## Steps to Reproduce
Create a tab view, filled with ExpansionPanelLists. 
This breaks, since ExpansionPanelList give their children ValueKeys based on their respective position in the children array (e.g. 0,2,4...). Expansion_panel.dart, line 147: `key: new ValueKey<int>(i * 2)` (i being the array-index). Since these are then being converted into _MergeableMaterialSliceKeys and therefor GlobalKeys in mergable_material.dart, one cannot "have" more than one expansion panel at a time. The index is being used to allow for an easier looping over the ListItems

Do you think this could be solved by passing an optional unique key to each ExpansionPanelList, which would then be passed through to _MergableMaterialSliceKeys and properly handled there instead of polluting the global namespace with very un-unique int-based Keys?

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new TabController(vsync: this, length: 2, initialIndex: 0);
  }

  ExpansionPanelList _getExpansionPanel(String body) {
    print(body);
    return new ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {},
      children: <ExpansionPanel>[
        new ExpansionPanel(
            body: new Text('Body'),
            isExpanded: true,
            headerBuilder: (BuildContext context, bool isExpanded) {
              return new Text(body);
            }),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text(widget.title)),
        body: new Column(
          children: ['one', 'two'].map(_getExpansionPanel).toList(),
        ));
  }
}
```

## Logs
```
I/flutter ( 1364): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1364): The following assertion was thrown building DefaultTextStyle(inherit: false; color:
I/flutter ( 1364): Color(0xdd000000); family: "Roboto"; size: 14.0; weight: 400; baseline: alphabetic):
I/flutter ( 1364): Multiple widgets used the same GlobalKey.
I/flutter ( 1364): The key _MergeableMaterialSliceKey([<0>]) was used by multiple widgets. The parents of those widgets
I/flutter ( 1364): were different widgets that both had the following description:
I/flutter ( 1364):   DefaultTextStyle(inherit: false; color: Color(0xdd000000); family: "Roboto"; size: 14.0; weight:
I/flutter ( 1364):   400; baseline: alphabetic)
I/flutter ( 1364): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter ( 1364): 
```

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/ben/Desktop/Dev/flutter/flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/ben/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • SM G920F • 05157df52d643b04 • android-arm • Android 7.0 (API 24)
```

### PR DESCRIPTION
**Pull request by Skylled**
_SaltedKey implementation courtesy of @Hixie
Tested and confirmed working. [Screenshot](https://i.imgur.com/DO2KWC5.png)
Fixes #11166

### CODE REVIEW

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 1]
```diff
@@ -70,5 +70,52 @@ void main() {
     expect(find.text('B'), findsOneWidget);
     box = tester.renderObject(find.byType(ExpansionPanelList));
     expect(box.size.height - oldHeight, greaterThanOrEqualTo(100.0)); // 100 + some margin
+
+    // multiple panel list test
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: you should put this in a separate testWidgets call, with this comment as the title of the test

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 2]
```diff
@@ -70,5 +70,52 @@ void main() {
...
+    await tester.pumpWidget(
+      new MaterialApp(
+        home: new ListView(
+          children: <ExpansionPanelList>[
+            new ExpansionPanelList(
+              expansionCallback: (int _index, bool _isExpanded){
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: trivial nit: space before `{`

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 3]
```diff
@@ -70,5 +70,52 @@ void main() {
...
+                index = _index;
+                isExpanded = _isExpanded;
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: since you don't actually interact with this widget, you can probably just leave the callback empty (or maybe omit it altogether?)

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 4]
```diff
@@ -70,5 +70,52 @@ void main() {
...
+              },
+              children: <ExpansionPanel>[
+                new ExpansionPanel(
+                  headerBuilder: (BuildContext context, bool isExpanded) {
+                    return new Text(isExpanded ? 'B': 'A');
+                  },
+                  body: const SizedBox(height:100.0),
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: minor style nit: space after `:`

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 5]
```diff
@@ -70,5 +70,52 @@ void main() {
...
+              },
+              children: <ExpansionPanel>[
+                new ExpansionPanel(
+                  headerBuilder: (BuildContext context, bool isExpanded){
+                    return new Text(isExpanded ? 'D': 'C');
+                  },
+                  body: const SizedBox(height:100.0),
+                  isExpanded: true,
+                ),
+              ],
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: same comments on this side

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 6]
```diff
@@ -70,5 +70,52 @@ void main() {
...
+            ),
+          ],
+        ),
+      ),
+    );
+    await tester.pump(const Duration(milliseconds: 200));
+
+    expect(find.text('A'), findsNothing);
+    expect(find.text('B'), findsOneWidget);
+    // Multiple panel lists scenario only fails when expanded
```
Comment (Hixie) [inline packages/flutter/test/material/expansion_panel_test.dart]: no need for this comment

**Comment by Hixie** [comment]
That test will be fine, just some minor tweaks needed before we land it. Thanks!

**Comment by Hixie** [comment]
@Skylled Thanks for your contribution, I'm going to land this as-is and if there's any more style nits we'll fix them in post.
