### PR TITLE
`CircularProgressIndicator` throws null exception

### LINKED ISSUE #163253: Flutter 3.29 Null check operator used on a null value with CircularProgressIndicator when value is null and year2023 property is true
First, I am confused about the year2023 property in Flutter 3.29. The [official release post](https://medium.com/flutter/whats-new-in-flutter-3-29-f90c380c2317) states that you can use the updated styling by setting year2023 to false. However, when I attempt to set it to false, I receive a warning message stating that 'year2023' is deprecated and shouldn't be used.

Image

### Steps to reproduce

when I try to use CircularProgressIndicator with value = null and year2023 = false, I get a null check operator error. 

```dart 

CircularProgressIndicator(value: null,year2023: false),
```

### Expected results

when I try to use CircularProgressIndicator with value = null and year2023 = false it should work like the old style

### Actual results

**A Null check operator crash ! .**

### Code sample

<details open><summary>Code sample</summary>

```dart
CircularProgressIndicator(value: null,year2023: false),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter (18629): Null check operator used on a null value
I/flutter (18629): #0      _CircularProgressIndicatorPainter.paint (package:flutter/src/material/progress_indicator.dart:607)
I/flutter (18629): #1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:593)
I/flutter (18629): #2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:641)
I/flutter (18629): #3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #5      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #8      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:81)
I/flutter (18629): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #14     _RenderListTile.paint.doPaint (package:flutter/src/material/list_tile.dart:1655)
I/flutter (18629): #15     _RenderListTile.paint (package:flutter/src/material/list_tile.dart:1659)
I/flutter (18629): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #18     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:81)
I/flutter (18629): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #21     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:81)
I/flutter (18629): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #39     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:81)
I/flutter (18629): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #43     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2343)
I/flutter (18629): #44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #49     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:81)
I/flutter (18629): #50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #53     PaintingContext.pushClipRect.<anonymous closure> (package:flutter/src/rendering/object.dart:576)
I/flutter (18629): #54     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:33)
I/flutter (18629): #55     ClipContext.clipRectAndPaint (package:flutter/src/painting/clip.dart:71)
I/flutter (18629): #56     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:576)
I/flutter (18629): #57     RenderClipRect.paint (package:flutter/src/rendering/proxy_box.dart:1576)
I/flutter (18629): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #62     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:175)
I/flutter (18629): #63     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:120)
I/flutter (18629): #64     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:271)
I/flutter (18629): #65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252)
I/flutter (18629): #66     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #69     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:741)
I/flutter (18629): #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #72     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:272)
I/flutter (18629): #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #75     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:773)
I/flutter (18629): #76     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:758)
I/flutter (18629): #77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #78     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:175)
I/flutter (18629): #79     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:120)
I/flutter (18629): #80     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:271)
I/flutter (18629): #81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252)
I/flutter (18629): #82     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #85     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #90     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #91     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
I/flutter (18629): #97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140)
I/flutter (18629): #98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3371)
I/flutter (18629): #99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:260)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale
    fr-XX)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by dbspoudel**
This PR adds a null check before accessing value, preventing errors caused by the null check operator used on null value.

Fixes #163253 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for your contribution! Could you please a test to verify this fix?

**Comment by dbspoudel** [comment]
> Thanks for your contribution! Could you please a test to verify this fix?

I've already added and pushed the test. Let me know if any further changes are needed. Thanks

**Comment by dbspoudel** [comment]
@TahaTesser could you please help me understand the failed check error and how to fix it?

File: packages/flutter/test/material/progress_indicator_theme_test.dart [hunk 1]
```diff
@@ -376,6 +376,28 @@ void main() {
...
+        ),
+      );
+
+      final SemanticsHandle handle = tester.ensureSemantics();
+      await tester.pumpWidget(
+        Theme(data: theme, child: const Center(child: CircularProgressIndicator())),
+      );
+
+      expect(tester.getSemantics(find.byType(CircularProgressIndicator)), matchesSemantics());
+      handle.dispose();
```
Comment (TahaTesser) [inline packages/flutter/test/material/progress_indicator_theme_test.dart:397]:
```suggestion
 expect(tester.takeException(), null);
```

The bug is related to null check exception but we're testing for semantics here instead. Please update the test to check for any exceptions, it should be null.

File: packages/flutter/test/material/progress_indicator_theme_test.dart [hunk 2]
```diff
@@ -376,6 +376,28 @@ void main() {
     );
   });
 
+
+  testWidgets(
+    'Legacy indeterminate CircularProgressIndicator renders with year2023 disabled and circularTrackColor is passed on theme',
```
Comment (TahaTesser) [inline packages/flutter/test/material/progress_indicator_theme_test.dart:381]:
```suggestion
    'CircularProgressIndicator.year2023 set to false and provided circularTrackColor does not throw exception`,
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/progress_indicator_theme_test.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/test/material/progress_indicator_theme_test.dart:396]: Please remove the suggested code in red here.

**Comment by dbspoudel** [comment]
@TahaTesser all requested changes have been made and pushed. Re-requesting your review. Thank you for your detailed guidance and continued support.

File: packages/flutter/test/material/progress_indicator_theme_test.dart [hunk 3]
```diff
@@ -376,6 +376,28 @@ void main() {
...
+    (WidgetTester tester) async {
+      const Color circularTrackColor = Color(0XFF0000FF);
+      final ThemeData theme = ThemeData(
+        progressIndicatorTheme: const ProgressIndicatorThemeData(
+          circularTrackColor: circularTrackColor,
+          year2023: false,
+        ),
+      );
+
+      final SemanticsHandle handle = tester.ensureSemantics();
```
Comment (TahaTesser) [inline packages/flutter/test/material/progress_indicator_theme_test.dart:390]:
```suggestion
```

File: packages/flutter/test/material/progress_indicator_theme_test.dart [hunk 4]
```diff
@@ -376,6 +376,28 @@ void main() {
...
+      await tester.pumpWidget(
+        Theme(data: theme, child: const Center(child: CircularProgressIndicator())),
+      );
+
+      expect(tester.getSemantics(find.byType(CircularProgressIndicator)), matchesSemantics());
+      handle.dispose();
```
Comment (TahaTesser) [inline packages/flutter/test/material/progress_indicator_theme_test.dart:396]:
```suggestion
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
We can do without these semantics lines.

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Review by bleroux — APPROVED** [review]
LGTM, thanks for the contribution :pray:

**Comment by TahaTesser** [comment]
@dbspoudel 
could you please push an empty commit to re-trigger tests? `git commit --allow-empty -m "Kick tests"`
