### PR TITLE
Null check logic for datatable.

### LINKED ISSUE #20076: DataTable issue - onSelectChanged called when null.
DataTables which do not provide cell onTap nor row onSelectChange throw an exception when a cell is tapped.

## Steps to Reproduce

Create a DataTable widget which does not define onTap() on its cells nor onSelectChanged on its rows.
Tap on a cell.

Here is a small demo project which demonstrates the issue (and a workaround - cells in the first column have the workaround applied).

https://gist.github.com/richgoldmd/e6bb39a561c457cf24194232903877e7

Workaround: provide an empty `onTap: () {}` for the DataCells. Side effect is unneeded inkWell effect.

**Proposed Solution:**
In data_table.dart, in the call to _buildDataCell(() replace
```
onSelectChanged: () => row.onSelectChanged(!row.selected),
```
with 
```
onSelectChanged: row.onSelectChanged == null ? null : () => row.onSelectChanged(!row.selected),
```

## Logs
```
[  +37 ms] [/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +1 ms] [/Development/flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +3 ms] [/Development/flutter/] git log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [/Development/flutter/] git log -n 1 --pretty=format:%ar
[  +18 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 weeks ago
[   +7 ms] [/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +72 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.5.1-0-gc7ea3ca
[+2743 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +221 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +243 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:11
[  +14 ms] idevice_id -h
[+1399 ms] /usr/bin/xcrun simctl list --json devices
[ +414 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +57 ms] ro.hardware = ranchu
[  +39 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[+1170 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +7 ms] Initializing gradle...
[   +7 ms] Using gradle from /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/gradlew.
[+1415 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +95 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +121 ms] /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/gradlew -v
[+1161 ms] 
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------
                   
                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
                   
                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                   OS:           Mac OS X 10.13.5 x86_64
[   +2 ms] Resolving dependencies...
[        ] [android/] /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/gradlew app:properties
[+2623 ms] :app:properties
                   
                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------
                   
                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@2449d436
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@32ee5c67
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@5cea49bd
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@63886011
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@90af032
                   buildDependents: task ':app:buildDependents'
                   buildDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app
                   buildFile: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/app/build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildOutputs: BaseVariantOutput container
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@49c78810
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@47ee8734
                   bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
                   bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
                   bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
                   bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
                   bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
                   bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
                   bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@67c6ff30
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: SoftwareComponentInternal set
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@3993189a
                   configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@4c6180b0
                   configurations: configuration container
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   consumeConfigAttr: task ':app:consumeConfigAttr'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@7f05692f
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
                   createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
                   createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@2f6a2680
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@e1cbc3f
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@4eb8d94c
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/distributions
                   distsDirName: distributions
                   docsDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@1aa09da5
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@7f05692f
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@6480f657
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@f9653bc
                   flutter: FlutterExtension_Decorated@7ec99bb
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@193f6156
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   layout: org.gradle.api.internal.file.DefaultProjectLayout@7aee0e68
                   libsDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@644be7e2
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@4758b93a
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@241ac12b
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@610a08c5
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@46c7ba87
                   name: app
                   normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@464d312f
                   objects: org.gradle.api.internal.model.DefaultObjectFactory@7d1eb119
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   platformAttrExtractor: task ':app:platformAttrExtractor'
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@4cdafac0
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@5776c038, com.android.build.gradle.api.AndroidBasePlugin@2af6a23f, org.gradle.language.base.plugins.LifecycleBasePlugin@288fa45f, org.gradle.api.plugins.BasePlugin@7504f475, org.gradle.api.plugins.ReportingBasePlugin@47b8a7fb, org.gradle.platform.base.plugins.ComponentBasePlugin@f02b58b, org.gradle.language.base.plugins.LanguageBasePlugin@d075cef, org.gradle.platform.base.plugins.BinaryBasePlugin@6cbda7e, org.gradle.api.plugins.JavaBasePlugin@2d6dc292, com.android.build.gradle.internal.coverage.JacocoPlugin@36969f2e, com.android.build.gradle.AppPlugin@1adf4f0b, FlutterPlugin@85db472]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareLintJar: task ':app:prepareLintJar'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@6480f657
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@4e491b08
                   projectDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@3c288873
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@13431290
                   properties: {...}
                   providers: org.gradle.api.internal.provider.DefaultProviderFactory@1adee5fc
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@854e6c2
                   reportsDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/reports
                   repositories: repository container
                   resolveConfigAttr: task ':app:resolveConfigAttr'
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@e432d9b
                   rootDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@76d04730
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@7d0c0ce8
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@52c1977d
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: SourceSet container
                   splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                   splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
                   splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                   splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@4758b93a
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: task set
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/reports/tests
                   testReportDirName: tests
                   testResultsDir: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/test-results
                   testResultsDirName: test-results
                   transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                   transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                   transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                   transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
                   transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                   transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                   transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                   transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                   transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                   transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                   transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   writeDebugApplicationId: task ':app:writeDebugApplicationId'
                   writeProfileApplicationId: task ':app:writeProfileApplicationId'
                   writeReleaseApplicationId: task ':app:writeReleaseApplicationId'
                   
                   BUILD SUCCESSFUL in 2s
                   1 actionable task: 1 executed
[ +155 ms] /Users/richardgoldstein/Library/Android/sdk/build-tools/28.0.0/aapt dump badging build/app/outputs/apk/app.apk
[  +46 ms] Exit code 0 from: /Users/richardgoldstein/Library/Android/sdk/build-tools/28.0.0/aapt dump badging build/app/outputs/apk/app.apk
[   +1 ms] package: name='md.richgoldstein.datatablebug' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'datatable_bug'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='datatable_bug' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='md.richgoldstein.datatablebug.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[  +23 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
[  +79 ms] Exit code 0 from: /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 logcat -v time -t 1
[        ] --------- beginning of main
           08-01 08:05:25.760 W/OpenGLRenderer( 2027): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
[   +4 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 logcat -v time
[ +711 ms] DependencyChecker: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/lib/main.dart is newer than 2018-08-01 07:49:58.519
[   +4 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb version
[  +16 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb
[   +5 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb start-server
[ +131 ms] Building APK
[  +26 ms] Running 'gradlew assembleDebug'...
[  +14 ms] [android/] /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/android/gradlew -Ptarget=/Users/richardgoldstein/AndroidStudioProjects/datatable_bug/lib/main.dart -Ppreview-dart-2=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1618 ms] :app:preBuild UP-TO-DATE
[  +19 ms] :app:preDebugBuild UP-TO-DATE
[  +13 ms] :app:compileDebugAidl UP-TO-DATE
[  +30 ms] :app:compileDebugRenderscript UP-TO-DATE
[  +61 ms] :app:flutterBuildX86Jar UP-TO-DATE
[   +1 ms] :app:checkDebugManifest UP-TO-DATE
[        ] :app:generateDebugBuildConfig UP-TO-DATE
[  +11 ms] :app:prepareLintJar UP-TO-DATE
[        ] :app:cleanMergeDebugAssets
[+8458 ms] :app:flutterBuildDebug
[        ] :app:mergeDebugShaders UP-TO-DATE
[   +5 ms] :app:compileDebugShaders UP-TO-DATE
[  +15 ms] :app:generateDebugAssets UP-TO-DATE
[  +79 ms] :app:mergeDebugAssets
[ +515 ms] :app:copyFlutterAssetsDebug
[  +11 ms] :app:generateDebugResValues UP-TO-DATE
[        ] :app:generateDebugResources UP-TO-DATE
[  +40 ms] :app:mergeDebugResources UP-TO-DATE
[   +7 ms] :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +11 ms] :app:processDebugManifest UP-TO-DATE
[        ] :app:splitsDiscoveryTaskDebug UP-TO-DATE
[  +16 ms] :app:processDebugResources UP-TO-DATE
[        ] :app:generateDebugSources UP-TO-DATE
[  +33 ms] :app:javaPreCompileDebug UP-TO-DATE
[  +32 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] :app:compileDebugNdk NO-SOURCE
[        ] :app:compileDebugSources UP-TO-DATE
[ +111 ms] :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +11 ms] :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[        ] :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[  +25 ms] :app:mergeDebugJniLibFolders UP-TO-DATE
[  +37 ms] :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[   +1 ms] :app:processDebugJavaRes NO-SOURCE
[  +53 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[  +18 ms] :app:validateSigningDebug
[+4971 ms] :app:packageDebug
[        ] :app:assembleDebug
[   +1 ms] BUILD SUCCESSFUL in 16s
[        ] 29 actionable tasks: 6 executed, 23 up-to-date
[ +519 ms] calculateSha: /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/build/app/outputs/apk/app.apk
[ +999 ms] Built build/app/outputs/apk/debug/app-debug.apk.
[   +4 ms] /Users/richardgoldstein/Library/Android/sdk/build-tools/28.0.0/aapt dump badging build/app/outputs/apk/app.apk
[  +26 ms] Exit code 0 from: /Users/richardgoldstein/Library/Android/sdk/build-tools/28.0.0/aapt dump badging build/app/outputs/apk/app.apk
[   +2 ms] package: name='md.richgoldstein.datatablebug' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'datatable_bug'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='datatable_bug' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='md.richgoldstein.datatablebug.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[   +4 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +1 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop md.richgoldstein.datatablebug
[+1351 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages md.richgoldstein.datatablebug
[ +293 ms] package:md.richgoldstein.datatablebug
[   +3 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.md.richgoldstein.datatablebug.sha1
[  +35 ms] b7ccbc267ae0680c671fe30859be3d4e7e5d3723
[   +1 ms] Installing APK.
[   +3 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb version
[  +26 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb
[   +1 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb start-server
[  +24 ms] Installing build/app/outputs/apk/app.apk...
[        ] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r build/app/outputs/apk/app.apk
[+2568 ms] Success
[   +5 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo -n 177daffd8af890017b74440e2ec3051d4972ec33 > /data/local/tmp/sky.md.richgoldstein.datatablebug.sha1
[ +125 ms] Android SDK built for x86 startApp
[   +3 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true md.richgoldstein.datatablebug/md.richgoldstein.datatablebug.MainActivity
[+1769 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=md.richgoldstein.datatablebug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+3856 ms] I/FlutterActivityDelegate(22198): onResume setting current activity to this
[ +432 ms] Observatory URL on device: http://127.0.0.1:39537/
[  +18 ms] /Users/richardgoldstein/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:8103 tcp:39537
[  +35 ms] Forwarded host port 8103 to device port 39537 for Observatory
[  +40 ms] Connecting to service protocol: http://127.0.0.1:8103/
[ +635 ms] Successfully connected to service protocol: http://127.0.0.1:8103/
[   +4 ms] getVM: {}
[  +20 ms] getIsolate: {isolateId: isolates/1051320087}
[   +5 ms] _flutter.listViews: {isolateId: isolates/1051320087}
[ +408 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] _createDevFS: {fsName: datatable_bug}
[ +285 ms] DevFS: Created new filesystem on the device (file:///data/user/0/md.richgoldstein.datatablebug/cache/datatable_bugDPRSYG/datatable_bug/)
[   +3 ms] Updating assets
[ +440 ms] Syncing files to device Android SDK built for x86...
[   +8 ms] DevFS: Starting sync from LocalDirectory: '/Users/richardgoldstein/AndroidStudioProjects/datatable_bug'
[        ] Scanning project files
[  +14 ms] Scanning package files
[ +245 ms] Scanning asset files
[   +1 ms] Scanning for deleted files
[  +15 ms] Compiling dart to kernel with 416 updated files
[  +16 ms] /Development/flutter/bin/cache/dart-sdk/bin/dart /Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages /Users/richardgoldstein/AndroidStudioProjects/datatable_bug/.packages --filesystem-scheme org-dartlang-root
[+1788 ms] D/        (22198): HostConnection::get() New Host Connection established 0xa029d9c0, tid 22250
[   +4 ms] D/EGL_emulation(22198): eglMakeCurrent: 0x9da6fe20: ver 2 0 (tinfo 0xa0283560)
[+6421 ms] I/flutter (22198): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +4 ms] I/flutter (22198): The following NoSuchMethodError was thrown while handling a gesture:
[   +2 ms] I/flutter (22198): The method 'call' was called on null.
[   +1 ms] I/flutter (22198): Receiver: null
[   +3 ms] I/flutter (22198): Tried calling: call(true)
[   +2 ms] I/flutter (22198): 
[        ] I/flutter (22198): When the exception was thrown, this was the stack:
[  +44 ms] I/flutter (22198): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
[   +1 ms] I/flutter (22198): #1      DataTable.build.<anonymous closure> (package:flutter/src/material/data_table.dart:583:38)
[        ] I/flutter (22198): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
[        ] I/flutter (22198): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
[        ] I/flutter (22198): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] I/flutter (22198): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] I/flutter (22198): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
[        ] I/flutter (22198): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] I/flutter (22198): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
[ +559 ms] I/flutter (22198): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] I/flutter (22198): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] I/flutter (22198): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] I/flutter (22198): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] I/flutter (22198): #13     _invoke1 (dart:ui/hooks.dart:134:13)
[        ] I/flutter (22198): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
[   +1 ms] I/flutter (22198): 
[        ] I/flutter (22198): Handler: onTap
[        ] I/flutter (22198): Recognizer:
[        ] I/flutter (22198):   TapGestureRecognizer#1ea96(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
[        ] I/flutter (22198):   Offset(271.9, 450.1), sent tap down)
[        ] I/flutter (22198): ════════════════════════════════════════════════════════════════════════════════════════════════════
[+1600 ms] Updating files
[+1086 ms] DevFS: Sync finished
[        ] Synced 0.8MB.
[  +12 ms] _flutter.listViews: {isolateId: isolates/1051320087}
[ +133 ms] Connected to _flutterView/0xa76b584c.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +7 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8103/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+10892 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/md.richgoldstein.datatablebug/cache/datatable_bugDPRSYG/datatable_bug/)
[        ] _deleteDevFS: {fsName: datatable_bug}
[   +7 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/md.richgoldstein.datatablebug/cache/datatable_bugDPRSYG/datatable_bug/)
[   +2 ms] ext.flutter.exit: {isolateId: isolates/1051320087}
[  +63 ms] Service protocol connection closed.
[  +39 ms] Application finished.
[  +93 ms] "flutter run" took 66,092ms.

```

```
Analyzing datatable_bug...                                       
No issues found! (ran in 2.9s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Development/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/richardgoldstein/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by kangwang1988**
Add null check logic for datatable.
This would fix: https://github.com/flutter/flutter/issues/20076

### CODE REVIEW

**Comment by xster** [comment]
Thanks. The fix seems sensible. Can you add a test to data_table_test.dart?

**Comment by kangwang1988** [comment]
@xster 
Got it. I will add them soon.

File: packages/flutter/test/material/data_table_test.dart [hunk 1]
```diff
@@ -210,4 +210,59 @@ void main() {
...
+                  ),
+                ],
+              ),
+            ],
+          ),
+        ),
+      ),
+    );
+    await tester.tap(find.text('Dessert').first);
+    expect(tester.takeException(), isNull);
```
Comment (xster) [inline packages/flutter/test/material/data_table_test.dart]: I think you have to tester.pump here to make it draw a frame

File: packages/flutter/test/material/data_table_test.dart [hunk 2]
```diff
@@ -210,4 +210,59 @@ void main() {
...
+                    Text('Lollipop'), // wraps
+                  ),
+                ],
+              ),
+            ],
+          ),
+        ),
+      ),
+    );
+    await tester.tap(find.text('Dessert').first);
```
Comment (xster) [inline packages/flutter/test/material/data_table_test.dart]: You don't have to say .first here

File: packages/flutter/test/material/data_table_test.dart [hunk 3]
```diff
@@ -210,4 +210,59 @@ void main() {
...
+                    Text('Lollipop'), // wraps
+                  ),
+                ],
+              ),
+            ],
+          ),
+        ),
+      ),
+    );
+    await tester.tap(find.text('Lollipop').first);
```
Comment (xster) [inline packages/flutter/test/material/data_table_test.dart]: ditto

**Review by xster — COMMENTED** [review]
LGTM. Thanks for adding tests

File: packages/flutter/test/material/data_table_test.dart (hunk 1 above)
Comment (kangwang1988) [reply packages/flutter/test/material/data_table_test.dart]:
```
testWidgets('DataTable column onSort test', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: DataTable(
            columns: const <DataColumn>[
              DataColumn(
                label: Text('Dessert'),
              ),
            ],
            rows: const <DataRow>[
              DataRow(
                cells: <DataCell>[
                  DataCell(
                    Text('Lollipop'), // wraps
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
    await tester.tap(find.text('Dessert'));
```
> testWidgets('DataTable column onSort test', (WidgetTester tester) async {
    await tester.pumpWidget(

I think I've called tester.pumpWidget here.

Comment (xster) [reply packages/flutter/test/material/data_table_test.dart]: It's not a big deal since the original bug was on the onTap but to be more strict, you'd ideally also draw a frame after tapping the column to let it draw the effect of sorting.

Comment (kangwang1988) [reply packages/flutter/test/material/data_table_test.dart]: Got it.
