### PR TITLE
fix: TabBar fontFamily inheritance with custom label styles

### LINKED ISSUE #127787: Changing fontFamily in whole app
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1-change app font family using theme   `ThemeData(
      brightness: Brightness.dark,
      fontFamily: "Any Font Famliy")`

### Expected results

All texts font family must be changed including Tabs, 

### Actual results

Tabs text Font Family  not changed

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.7.12 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\UserName\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Hussen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • SM A525F (mobile) • RZ8RC1VEPDF • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 113.0.1774.57

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix #127787

When `labelStyle` or `unselectedLabelStyle` is specified, the `defaults.labelStyle` is ignored.
Merge `defaults` to make `labelStyle` and `TabBarTheme.labelStyle` apply default text styles.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -312,14 +312,19 @@ class _TabStyle extends AnimatedWidget {
...
     // the same value of inherit. Force that to be inherit=true here.
-    final TextStyle selectedStyle = (labelStyle ?? tabBarTheme.labelStyle ?? defaults.labelStyle!)
-        .copyWith(inherit: true);
-    final TextStyle unselectedStyle =
-        (unselectedLabelStyle ??
-                tabBarTheme.unselectedLabelStyle ??
-                labelStyle ??
-                defaults.unselectedLabelStyle!)
-            .copyWith(inherit: true);
+    TextStyle? selectedStyle = labelStyle ?? tabBarTheme.labelStyle;
```
Comment (Harits19) [inline packages/flutter/lib/src/material/tabs.dart]: ### 💡 Suggestion

Consider extracting this logic into a reusable function to improve readability and reduce duplication:

```dart
TextStyle _resolveLabelStyle({
  required TextStyle? style,
  required TextStyle? themeStyle,
  required TextStyle defaultStyle,
}) {
  TextStyle? resolvedStyle = style ?? themeStyle;
  if (resolvedStyle == null || resolvedStyle.inherit) {
    resolvedStyle = defaultStyle.merge(resolvedStyle);
  }
  return resolvedStyle.copyWith(inherit: true);
}
```

Then use it like this:
```dart
final TextStyle unselectedStyle = _resolveLabelStyle(
  style: unselectedLabelStyle,
  themeStyle: tabBarTheme.unselectedLabelStyle,
  defaultStyle: defaults.unselectedLabelStyle!,
);

final TextStyle selectedStyle = _resolveLabelStyle(
  style: labelStyle,
  themeStyle: tabBarTheme.labelStyle,
  defaultStyle: defaults.labelStyle!,
);

```

File: packages/flutter/lib/src/material/tabs.dart [hunk 2]
```diff
@@ -312,14 +312,19 @@ class _TabStyle extends AnimatedWidget {
...
+    if (selectedStyle == null || selectedStyle.inherit) {
+      // Apply the font family specified in TextStyle from the theme.
+      selectedStyle = defaults.labelStyle!.merge(selectedStyle);
+    }
+    selectedStyle = selectedStyle.copyWith(inherit: true);
+
+    TextStyle? unselectedStyle = unselectedLabelStyle ?? tabBarTheme.unselectedLabelStyle;
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/tabs.dart]: Looks like if labelStyle is non-null, and unselectedLabelStyle and tabBarTheme.unselectedLabelStyle are null, then we should use labelStyle here. So:
```suggestion
    TextStyle? unselectedStyle = unselectedLabelStyle ?? tabBarTheme.unselectedLabelStyle ?? labelStyle;
```

File: packages/flutter/lib/src/material/tabs.dart [hunk 3]
```diff
@@ -312,14 +312,19 @@ class _TabStyle extends AnimatedWidget {
...
-    final TextStyle selectedStyle = (labelStyle ?? tabBarTheme.labelStyle ?? defaults.labelStyle!)
-        .copyWith(inherit: true);
-    final TextStyle unselectedStyle =
-        (unselectedLabelStyle ??
-                tabBarTheme.unselectedLabelStyle ??
-                labelStyle ??
-                defaults.unselectedLabelStyle!)
-            .copyWith(inherit: true);
+    TextStyle? selectedStyle = labelStyle ?? tabBarTheme.labelStyle;
+    if (selectedStyle == null || selectedStyle.inherit) {
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/tabs.dart]: Are these `if` checks necessary for readability? If `.inherit` is false than `.merge` should just return the textStyle unchanged.

**Review by MitchellGoodwin — COMMENTED** [review]
Thank you for submitting this change, I left some comments.

File: packages/flutter/lib/src/material/tabs.dart (hunk 3 above)
Comment (koji-1009) [reply packages/flutter/lib/src/material/tabs.dart]: https://github.com/flutter/flutter/blob/3.32.6/packages/flutter/lib/src/painting/text_style.dart#L1079-L1085

`merge` only looked at `other.inherit`. For this reason, I this that it is necessary to check `selectedStyle.inherit` and `unselectedStyle.inherit`.

File: packages/flutter/lib/src/material/tabs.dart (hunk 2 above)
Comment (koji-1009) [reply packages/flutter/lib/src/material/tabs.dart]: Thanks! And I fixed `TextStyle?` to `TextStyle` at [047a2bb](https://github.com/flutter/flutter/pull/171699/commits/047a2bbca4720cafb705dbc7ee00c97fadbfb656).

File: packages/flutter/lib/src/material/tabs.dart (hunk 3 above)
Comment (koji-1009) [reply packages/flutter/lib/src/material/tabs.dart]: After thinking about it for a while, I came up with the idea of changing the order of processing. How about this? [15b21d3](https://github.com/flutter/flutter/pull/171699/commits/15b21d39fc0f76efeca1cffac067fb23f17688fe)

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the fix.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thank you for your contribution:)!
