### PR TITLE
The Ink widget

### LINKED ISSUE #3782: InkWell and FlatButton do not ripple when inside a container with opaque background
## Steps to Reproduce

I have only tested this against an android emulator.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue
      ),
      home: new FlutterDemo()
    )
  );
}

class FlutterDemo extends StatelessWidget {

  Widget buttons(BoxDecoration decoration) {
    return new Container(
      decoration: decoration,
      child: new Row(
        children: [
          new FlatButton(
            child: new Text("FLAT BUTTON"),
            onPressed: () => null
          ),
          new InkWell(
            child: new Text("WELL"),
            onTap: () => null
          ),
          new RaisedButton(
            child: new Text("RAISED BUTTON"),
            onPressed: () => null
          )
        ]
      )
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Flutter Demo')
      ),
      body: new Column(
        children: [
          // INK DOES NOT SHOW
          buttons(new BoxDecoration(backgroundColor: Colors.yellow[100])),
          buttons(null),
          // INK DOES NOT SHOW
          buttons(new BoxDecoration(gradient: new LinearGradient(colors: [Colors.grey[100], Colors.grey[500]]))),
          buttons(new BoxDecoration(gradient: new LinearGradient(colors: [Colors.black26, Colors.grey[500]]))),
          buttons(new BoxDecoration(backgroundColor: Colors.white10))
        ]
      )
    );
  }
}

```

Note that the ripple does not appear on the FlatButton and InkWell for first and third rows (the ones that use opaque backgrounds). The ripple works fine on the raised button for all rows.
## Flutter Doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/drewwarren/flutter
    • Framework revision 5460e94488 (4 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/users/drewwarren/aswb-sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

No logs. Requires visual inspection.

### PR DESCRIPTION
**Pull request by Hixie**
This provides a way to draw colors, images, and general decorations on Material widgets, without interfering with InkWells that are further descendants of the widget.

This thus provides a cleaner way to solve the issue of FlatButtons and InkWells not working when placed over Image widgets than the old hack of introducing a transparency Material.

Fixes #3782.

Also, some fixes to documentation, and remove a redundant property on the Image widget.

### CODE REVIEW

File: packages/flutter/lib/src/material/material.dart [hunk 1]
```diff
@@ -91,10 +91,11 @@ abstract class MaterialInkController {
 /// of material cannot be printed beyond the bounds of the material.
 ///
 /// If the layout changes (e.g. because there's a list on the paper, and it's
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/material.dart]: paper?

File: packages/flutter/lib/src/material/ink_decoration.dart [hunk 2]
```diff
@@ -0,0 +1,356 @@
...
+
+import 'material.dart';
+
+/// A convenience widget for drawing images and other decorations on [Material]
+/// widgets, so that [InkWell] and [InkResponse] splashes will render over them.
+///
+/// Ink splashes and highlights, as rendered by [InkWell] and [InkResponse],
+/// draw on the actual underlying [Material], under whatever widgets are drawn
+/// over the material (such as [Text] and [Icon]s). If an opaque image is drawn
+/// over the [Material] (as with a [Container] or [DecoratedBox]), these ink
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_decoration.dart]: Container and DecoratedBox aren't necessarily opaque, so the unqualified parenthetical statement is a little confusing.

File: packages/flutter/lib/src/material/ink_decoration.dart [hunk 3]
```diff
@@ -0,0 +1,356 @@
...
+  /// Paints a decoration (which can be a simple color) on a [Material].
+  ///
+  /// The [height] and [width] values include the [padding].
+  ///
+  /// The `color` argument is a shorthand for `decoration: new
+  /// BoxDecoration(color: color)`, which means you cannot supply both a `color`
+  /// and a `decoration` argument. If you want to have both a `color` and a
+  /// `decoration`, you can pass the color as the `color` argument to the
+  /// `BoxDecoration`.
+  Ink({
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_decoration.dart]: This is a nice short name. It's also a bit of a misnomer if we're going to say that splashes and ripples are drawn with "ink". A longer more horrible but more apt name would be MaterialAncestorDecorator.

File: packages/flutter/lib/src/material/ink_decoration.dart [hunk 4]
```diff
@@ -0,0 +1,356 @@
...
+/// over the [Material] (as with a [Container] or [DecoratedBox]), these ink
+/// effects will not be visible, as they will be entirely obscured by the opaque
+/// graphics drawn above the [Material].
+///
+/// This widget draws the given [Decoration] directly on the [Material], in the
+/// same way that [InkWell] and [InkResponse] draw there. This allows the
+/// splashes to be drawn above the otherwise opaque graphics.
+///
+/// An alternative solution is to use a [MaterialType.transparency] material
+/// above the opaque graphics.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_decoration.dart]: ... because in that case ink well and ink response descendants will draw their splashes on the otherwise transparent material

File: packages/flutter/lib/src/material/ink_decoration.dart [hunk 5]
```diff
@@ -0,0 +1,356 @@
...
+  /// its [BoxDecoration.image] property set to the [new Ink] constructor. The
+  /// properties of the [DecorationImage] of that [BoxDecoration] are set
+  /// according to the arguments passed to this method.
+  ///
+  /// The `image` argument must not be null. The `alignment`, `repeat`, and
+  /// `matchTextDirection` arguments must not be null either, but they have
+  /// default values.
+  ///
+  /// See [paintImage] for a description of the meaning of these arguments.
+  Ink.image({
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_decoration.dart]: I don't think we want `DecoratedBox.image` and `Container.image`.

If we had `BoxDecoration.image` then one could just write new `Ink(decoration: new BoxDecoration.image(...))`

**Review by HansMuller — COMMENTED** [review]
I'm still working through this, just an update

File: packages/flutter/lib/src/material/ink_decoration.dart [hunk 6]
```diff
@@ -0,0 +1,356 @@
...
+/// widgets, so that [InkWell] and [InkResponse] splashes will render over them.
+///
+/// Ink splashes and highlights, as rendered by [InkWell] and [InkResponse],
+/// draw on the actual underlying [Material], under whatever widgets are drawn
+/// over the material (such as [Text] and [Icon]s). If an opaque image is drawn
+/// over the [Material] (as with a [Container] or [DecoratedBox]), these ink
+/// effects will not be visible, as they will be entirely obscured by the opaque
+/// graphics drawn above the [Material].
+///
+/// This widget draws the given [Decoration] directly on the [Material], in the
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_decoration.dart]: What happens when a Material widget has more than one Ink descendant?

File: packages/flutter/lib/src/material/material.dart [hunk 7]
```diff
@@ -91,10 +91,11 @@ abstract class MaterialInkController {
...
-/// been scrolled), a LayoutChangedNotification must be dispatched at the
-/// relevant subtree. (This in particular means that Transitions should not be
-/// placed inside Material.) Otherwise, in-progress ink features (e.g., ink
-/// splashes and ink highlights) won't move to account for the new layout.
+/// been scrolled), a [LayoutChangedNotification] must be dispatched at the
+/// relevant subtree. This in particular means that transitions (e..g.
+/// [SlideTransition]) should not be placed inside Material. Otherwise,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/material.dart]: Scaffold creates a Material widget, so don't most transitions occur "inside Material"?

File: packages/flutter/lib/src/widgets/image.dart [hunk 8]
```diff
@@ -110,6 +113,10 @@ class Image extends StatefulWidget {
   ///
   /// The [image], [alignment], [repeat], and [matchTextDirection] arguments
   /// must not be null.
+  ///
+  /// The [width] and [height] arguments should be specified. If they are not,
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/image.dart]: I think the advice we want to provide is: don't allow the layout to be defined by the image's actual size. Either constrain the size of the image or specify it explicitly with width and height.

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/ink_decoration.dart]: replaced with "maybe using a ..."

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/ink_decoration.dart]: done

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/ink_decoration.dart]: as we discussed, i agree that the name is a bit sketchy but i think we want this to be more attractive than Container or BoxDecoration or even Image.

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 5 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/ink_decoration.dart]: Why don't you think we want DecoratedBox.image and Container.image? I mean, I don't know if we do, but maybe we do, if this works out well here...

The problem with only having BoxDecoration.image is that it's still pretty verbose, c.f.:

```dart
  new Ink.image(
    image: new AssetImage('cat.jpeg'),
    fit: BoxFit.cover,
    width: 300.0,
    height: 200.0,
 )

  new Ink(
    decoration: new BoxDecoration.image(
      image: new AssetImage('cat.jpeg'),
      fit: BoxFit.cover,
    ),
    width: 300.0,
    height: 200.0,
 )
```

File: packages/flutter/lib/src/material/material.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/material.dart]: heh, i still think of it as "quantum paper"...

Comment (Hixie) [reply packages/flutter/lib/src/material/material.dart]: fixed -> material

File: packages/flutter/lib/src/material/material.dart (hunk 7 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/material.dart]: Yup. I clarified this a bit to say that it's specifically a problem if you move ink features around.

File: packages/flutter/lib/src/widgets/image.dart (hunk 8 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/image.dart]: How about this:
```
  /// Either the [width] and [height] arguments should be specified, or the                                                             
  /// widget should be placed in a context that sets tight layout constraints.                                                          
  /// Otherwise, the image dimensions will change as the image is loaded, which                                                         
  /// will result in ugly layout changes.                                                                                               ```

**Comment by Hixie** [comment]
Updated per comments, PTAL.

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 5 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/ink_decoration.dart]: IMHO we'd want `DecoratedBox.image` and `Container.image` constructors for the sake symmetry (because that makes the APIs easier to understand) and we wouldn't want `Ink.image`, et al because less API is more.

IMHO `BoxDecoration.image` balances the API weight than the other 3 constructors, but I defer to you.

**Comment by HansMuller** [comment]
LGTM. There's merging to be done because of the ripple changes (sorry).

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 5 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/ink_decoration.dart]: I think we might want DecoratedBox.image and Container.image, I just think we should see how Ink.image goes before doing it. :-)

**Comment by Hixie** [comment]
Merged. Will land on green. Thanks for the review.

File: packages/flutter/lib/src/material/ink_decoration.dart (hunk 5 above)
Comment (csshuai) [reply packages/flutter/lib/src/material/ink_decoration.dart]: [video_player](https://pub.flutter-io.cn/packages/video_player) provide a `Texture`, not a `Image`. 
Do you have a solution?
