### PR TITLE
Fixes renderparagraph crashes due to truncated semantics node

### LINKED ISSUE #88180: [A11y] RichText with overflow TextSpan crashes due to null check
## Steps to Reproduce

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      // Change width, height and maxLines for text to overflow in container.
      // Setting the width and height very large won't cause application
      // to crash, because all content is visible in container.
      home: MyHomeScreen(
        width: 48,
        height: 48,
        maxLines: 1,
      ),
    );
  }
}

class MyHomeScreen extends StatelessWidget {
  final double width;
  final double height;
  final int maxLines;

  /// Change the width, height and maxLines in order for the container
  /// text to overflow.
  MyHomeScreen({this.width = 24, this.height = 24, this.maxLines = 1});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Semantics', style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: Center(
        child: Container(
          color: Colors.amber[600],
          width: width,
          height: height,
          child: RichText(
            maxLines: maxLines,
            overflow: TextOverflow.ellipsis,
            text: TextSpan(children: _getSpans(context)),
          ),
        ),
      ),
    );
  }

  /// Generate the spans to be added to the RichText widget.
  /// When withTapGesture, addTextSpan and addWidgetSpan is true the application
  /// will crash when text is overflowing in the RichText parent widget.
  /// Removing the tapGesture removes the crash.
  List<InlineSpan> _getSpans(
      BuildContext context, {
        bool withTapGesture = true,
        bool addTextSpan = true,
        bool addWidgetSpan = true,
      }) {
    var spans = <InlineSpan>[];

    if (addTextSpan) {
      spans.add(TextSpan(
        text: 'This is a link',
        // Removing this semanticsLabel also removes the exception.
        semanticsLabel: 'link',
        recognizer: withTapGesture
            ? (TapGestureRecognizer()..onTap = () => _showSnackBar(context))
            : null,
      ));
    }

    if (addWidgetSpan) {
      spans.add(WidgetSpan(
        child: Text('Hello world!'),
      ));
    }

    return spans;
  }

  void _showSnackBar(BuildContext context) {
    final snackBar = SnackBar(content: Text('Link tapped'));
    ScaffoldMessenger.of(context).showSnackBar(snackBar);
  }
}
```

## Logs

<details>
<summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:939:52)
#1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3822:13)
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814:16)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814:16)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814:16)
#8      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3692:16)
#9      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2731:25)
#10     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080:16)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#16     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════


```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/88180

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -2832,6 +2832,7 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
                children.elementAt(childIndex).isTagged(PlaceholderSpanIndexSemanticsTag(placeholderIndex))) {
           final SemanticsNode childNode = children.elementAt(childIndex);
           final TextParentData parentData = child!.parentData! as TextParentData;
+          assert(parentData.scale != null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:2835]: render paragraph should never truncate because it is scrollable

File: packages/flutter/test/rendering/paragraph_test.dart [hunk 2]
```diff
@@ -702,7 +702,40 @@ void main() {
...
+      textScaleFactor: 1.0,
+      children: renderBoxes,
+      textDirection: TextDirection.ltr,
+    );
+    layout(paragraph, constraints: const BoxConstraints(maxWidth: screenWidth));
+    final SemanticsNode result = SemanticsNode();
+    final SemanticsNode truncatedChild = SemanticsNode();
+    truncatedChild.tags = <SemanticsTag>{const PlaceholderSpanIndexSemanticsTag(0)};
+    paragraph.assembleSemanticsNode(result, SemanticsConfiguration(), <SemanticsNode>[truncatedChild]);
+    // It should only contain the semantics node of the TextSpan
```
Comment (justinmc) [inline packages/flutter/test/rendering/paragraph_test.dart:730]: Nit: Period here.

**Review by justinmc — APPROVED** [review]
LGTM 👍
