### PR TITLE
Make `SemanticsNode.isMergedIntoParent` Readonly

### LINKED ISSUE #54665: TextSpan with recognizer in ListTile fails assertion
## Steps to Reproduce

```bash
$ flutter test <file.dart>
```

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets("ups ...", (WidgetTester tester) async {
    TextSpan w = TextSpan(
      text: 'foo',
      style: TextStyle(color: Colors.blueAccent, fontWeight: FontWeight.bold),
      recognizer: TapGestureRecognizer()
        ..onTap = () {
          // navigate to desired screen
        },
    );

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: SwitchListTile(
            title: RichText(
              text: w,
            ),
            value: false,
            onChanged: (_) {},
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();
  });
}
```
**Expected results:** 
Test succeeds.

**Actual results:** 
Test fails with the following error:
```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2626 pos 16: 'node.parent ==
null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
```

See flutter test in Logs for whole output!

<details>
  <summary>Logs</summary>

```
Testing started at 16:54 ...
/Users/xxxxxx/development/flutter/bin/flutter --no-color test --machine --plain-name "ups ..." test/widget/richtext_link_test.dart
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2626 pos 16: 'node.parent ==
null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2626:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1042:23)
#4      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:985:31)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#8      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:872:9)
#11     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#12     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:859:27)
#13     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:323:22)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#17     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:320:27)
#18     main.<anonymous closure> (file:///Users/xxxxxx77/coding-pers/glutyfree/frontend-flutter/test/widget/richtext_link_test.dart:16:18)
#20     main.<anonymous closure> (file:///Users/xxxxxx77/coding-pers/glutyfree/frontend-flutter/test/widget/richtext_link_test.dart:6:26)
#21     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:122:9)
#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
#38     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1066:17)
#40     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1054:35)
(elided 37 frames from class _AssertionError, class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: ups ...
```

Nothing to show, test is provided.
```
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-DE)
    • Flutter version 1.12.13+hotfix.9 at /Users/xxxxxx/development/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • F5B265ED-92AE-4C3E-BCBB-FB695B0CF5A2 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone 11 Pro Max         • 40A5CB14-4898-4953-B776-B83CAFFCC589 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/54665

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -2045,6 +2041,28 @@ class SemanticsNode with DiagnosticableTreeMixin {
     _children?.forEach(_redepthChild);
   }
 
+  void _updateChildMergeFlag(SemanticsNode child) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:2044]: Maybe add a `recursively` to this method name to indicate that it will also do so for the child's children (similarly to other methods like that that we have in the framework).

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 2]
```diff
@@ -3274,6 +3299,51 @@ class SemanticsOwner extends ChangeNotifier {
...
+      }
+
+      // The root node is allowed to be invisible when it has no children.
+      final SemanticsNode? rootSemanticsNode = this.rootSemanticsNode;
+      if (rootSemanticsNode != null) {
+        if (!rootSemanticsNode.mergeAllDescendantsIntoThisNode) {
+          rootSemanticsNode.visitChildren(findInvisibleNodes);
+        } else if (rootSemanticsNode.childrenCount > 0 && rootSemanticsNode.rect.isEmpty) {
+          invisibleNodes.add(rootSemanticsNode);
+        }
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3321]: Shouldn't the rootSemanticsNode also be considered invisible if it doesn't merge all descendants into it, has a childrenCount > 0, and an empty rect?

In other words, in the if branch, why is the rootNode not considered invisible if it has children and and empty rect?

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 3]
```diff
@@ -3274,6 +3299,51 @@ class SemanticsOwner extends ChangeNotifier {
 
   /// Update the semantics using [onSemanticsUpdate].
   void sendSemanticsUpdate() {
+    // Once the tree is up-to-date, verify that there's no invisible nodes in it.
+    assert(() {
+      final List<SemanticsNode> invisibleNodes = <SemanticsNode>[];
+      bool findInvisibleNodes(SemanticsNode rootNode) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/semantics/semantics.dart:3305]: Maybe rename the name rootNode to just node here? It gets a little confusing because this is not necessarily gonna be the root root node for every call?

**Review by goderbauer — APPROVED** [review]
LGTM
