### PR TITLE
InteractiveViewer onInteractionUpdate focalPoint

### LINKED ISSUE #63606: InteractiveViewer onInteractionUpdate returns the scene focal point instead of the point on the viewport
## Steps to Reproduce

1. Use `InteractiveViewer`
2. Use the `onInteractionUpdate` function
3. Compare the `onInteractionStart` localFocalPoint with the `onInteractionUpdate` localFocalPoint. It differs a lot while just moving 1 point around.

**Expected results:** 
`details.localFocalPoint` should be calculated the same way in `onInteractionUpdate` as in `onInteractionStart`

**Actual results:** 
It differs a lot more when zoomed in.

## Findings
The problem is in [this line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/interactive_viewer.dart#L747) where it already gets passed converted `toScene`.

In the `onInteractionStart` it get's passed [as is](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/interactive_viewer.dart#L722).

I think it should pass the `localFocalPoint` **as is** also in the `onInteractionUpdate` function. The dev can decide on himself whether to convert it to scene coordinates. Also the description of `onInteractionUpdate` says, that the coordinates are **viewport** coordinates which can be converted using `toScene`.

### LINKED ISSUE #66035: InteractiveViewer OnInteractionUpdate provides (0,0) coordinates when scrolling.
## Steps to Reproduce
Recently, a commit hit master that caused OnInteractionUpdate to be triggered when scrolling. This update provides (0,0) coordinates and breaks applications that rely on interaction updates for coordinate changes of objects within the page.
With the code below you will notice that taps on the screen provide the correct coordinates, but when scrolling, (0,0) is provided.

cc: @justinmc per https://github.com/flutter/flutter/pull/65432#issuecomment-693683213

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          // This is the theme of your application.
          //
          // Try running your application with "flutter run". You'll see the
          // application has a blue toolbar. Then, without quitting the app, try
          // changing the primarySwatch below to Colors.green and then invoke
          // "hot reload" (press "r" in the console where you ran "flutter run",
          // or simply save your changes to "hot reload" in a Flutter IDE).
          // Notice that the counter didn't reset back to zero; the application
          // is not restarted.
          primarySwatch: Colors.blue,
          // This makes the visual density adapt to the platform that you run
          // the app on. For desktop platforms, the controls will be smaller and
          // closer together (more dense) than on mobile platforms.
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home:  MyHomePage(title: 'Flutter Demo Home Page'),
        );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _rowCount = 5;
  int _columnCount = 5;
  bool _text = true;
  bool _color = true;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        title: Text("Column: $_columnCount\nRow: $_rowCount"),
        actions: [
          IconButton(
              icon: Icon(Icons.add),
              onPressed: () {
                setState(() {
                  _rowCount += 5;
                  _columnCount += 5;
                });
              }),
          IconButton(
              icon: Icon(Icons.format_paint),
              onPressed: () {
                setState(() {
                  _color = !_color;
                });
              }),
          IconButton(
              icon: Icon(Icons.text_fields),
              onPressed: () {
                setState(() {
                  _text = !_text;
                });
              })
        ],
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
      ),
      body: InteractiveViewer(
          scaleEnabled: true,
          panEnabled: true,
          constrained: false,
          onInteractionUpdate: (details) {
            print(details.localFocalPoint.toString());
          },
          child: Table(
            columnWidths: <int, TableColumnWidth>{
              for (int column = 0; column < _columnCount; column++)
                column: const FixedColumnWidth(300.0),
            },
            children: <TableRow>[
              for (int row = 0; row < _rowCount; row++)
                TableRow(
                  children: <Widget>[
                    for (int column = 0; column < _columnCount; column++)
                      Container(
                          child: _text
                              ? Text("Column: $_columnCount\nRow: $_rowCount")
                              : null,
                          height: 100,
                          color: _color
                              ? row % 2 + column % 2 == 1
                                  ? Colors.red.withOpacity(0.5)
                                  : Colors.green.withOpacity(0.5)
                              : null),
                  ],
                ),
            ],
          )),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.205, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.205 at C:\src\flutter
    • Framework revision 0220c3585c (24 hours ago), 2020-09-16 23:13:05 +0800
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\Miche\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
## Description

onInteractionUpdate was not passing `focalPoint` or `localFocalPoint` when using mouse scrolling. This was just an oversight when we implemented that event for mouse scrolling (https://github.com/flutter/flutter/pull/65313).

## Related Issues

Bug from https://github.com/flutter/flutter/pull/65313
Closes https://github.com/flutter/flutter/issues/66035
Closes https://github.com/flutter/flutter/issues/63606

## Tests

I added a check for focalPoint to an existing test.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 15 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/66065

File: packages/flutter/lib/src/widgets/interactive_viewer.dart [hunk 1]
```diff
@@ -924,6 +924,7 @@ class _InteractiveViewerState extends State<InteractiveViewer> with TickerProvid
       }
       if (widget.onInteractionUpdate != null) {
         widget.onInteractionUpdate!(ScaleUpdateDetails(
+          focalPoint: _transformationController!.toScene(event.localPosition),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/interactive_viewer.dart:927]: According to the documentation

> The coordinates returned in the details are viewport coordinates relative to the parent.

Is that correct?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:927]: No it's not, thanks for catching that!  I was just copying what I did for the other onInteractionUpdate, which is also wrong apparently.

I will change the code in both places so that the documentation is correct. I think that's best because the user can still convert to scene coordinates themselves using the same toScene method.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart]: Done.  I also updated a test to make sure this is covered.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart]: `onInteractionStart` should also use the viewport coordinate system according to the documentation? (`onInteractionStart` is called after updating the transform. Is that expected?) 

also nit: I think we can do `widget.onInteractionUpdate?.call(ScaleUpdateDetails(...))` instead?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart]: Oh yeah that too.  I've now made sure that all of the onInteraction* calls are using the coordinates of the event (not transformed to the scene) and that they are called after the controller has been updated.  That way the user can transform them to scene coordinates if they want by using the controller, but otherwise have the viewport coordinates.  That seems like the best approach to me.   I also wrote another test confirming that you can do this.

File: packages/flutter/lib/src/widgets/interactive_viewer.dart [hunk 2]
```diff
@@ -917,22 +909,21 @@ class _InteractiveViewerState extends State<InteractiveViewer> with TickerProvid
...
-          rotation: 0.0,
-          scale: scaleChange,
-          horizontalScale: 1.0,
-          verticalScale: 1.0,
-        ));
-      }
-      if (widget.onInteractionEnd != null) {
-        widget.onInteractionEnd!(ScaleEndDetails());
-      }
+      widget.onInteractionStart?.call(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/interactive_viewer.dart:912]: If the developer tries to access the transform in the `onInteractionStart`, are they supposed to see the updated transform, or the pre-scroll transform?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM!

File: packages/flutter/lib/src/widgets/interactive_viewer.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart]: Someone actually opened an issue for this (https://github.com/flutter/flutter/issues/63606). This PR should close that issue too now.

File: packages/flutter/lib/src/widgets/interactive_viewer.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart]: Good point, I updated the docs.  For start, the transformation shouldn't have changed, but for update/end, it should have changed.
