### PR TITLE
Correct menu position when menu is constrained

### LINKED ISSUE #142896: [Material] showMenu() assumes the popup has an unconstrained height when it positions the popup
## Steps to reproduce

Run the following app and click to open the popup menu:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: Scaffold(body: BugReport())));
}

class BugReport extends StatefulWidget {
  const BugReport({super.key});

  @override
  State<BugReport> createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  static const int _length = 50;

  List<PopupMenuEntry<int>> _buildItems(BuildContext context) {
    return List<PopupMenuEntry<int>>.generate(_length, (int index) {
      return PopupMenuItem<int>(value: index, child: Text('$index'));
    });
  }

  @override
  Widget build(BuildContext context) {
    final Size screenSize = MediaQuery.of(context).size;
    return Padding(
      padding: const EdgeInsets.all(50),
      child: Align(
        alignment: Alignment.bottomCenter,
        child: PopupMenuButton(
          itemBuilder: _buildItems,
          constraints: BoxConstraints(maxHeight: screenSize.height / 4),
          initialValue: _length - 1,
          child: const Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('Click here to open popup menu '),
              Icon(Icons.ads_click),
            ],
          ),
        ),
      ),
    );
  }
}
```

## Expected behavior

You expect the popup to appear over the popup menu button.

## Actual behavior

The popup appears at the top of the screen, far above the popup menu.

## Diagnosis

The following code block assumes the popup menu will be given its full height (lower down in this method, it calls `_fitInsideScreen`, but that simply truncates the size of the popup - it doesn't reposition it):

https://github.com/flutter/flutter/blob/f8a77225f360556322934a9a831ffc9c9f3125da/packages/flutter/lib/src/material/popup_menu.dart#L723-L732

## Test reproduction

Once fixed, this test should pass (as of this filing, the test fails):

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('PopupMenuButton properly positions a constrained-size popup', (WidgetTester tester) async {
    final Size windowSize = tester.view.physicalSize / tester.view.devicePixelRatio;
    const int length = 50;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(50),
            child: Align(
              alignment: Alignment.bottomCenter,
              child: PopupMenuButton<int>(
                itemBuilder: (BuildContext context) {
                  return List<PopupMenuEntry<int>>.generate(length, (int index) {
                    return PopupMenuItem<int>(value: index, child: Text('item #$index'));
                  });
                },
                constraints: BoxConstraints(maxHeight: windowSize.height / 3),
                popUpAnimationStyle: AnimationStyle.noAnimation,
                initialValue: length - 1,
                child: const Text('click here'),
              ),
            ),
          ),
        ),
      ),
    );
    await tester.tap(find.text('click here'));
    await tester.pump();

    // Set up finders and verify basic widget structure
    final Finder findButton = find.byType(PopupMenuButton<int>);
    final Finder findLastItem = find.text('item #49');
    final Finder findListBody = find.byType(ListBody);
    final Finder findListViewport = find.ancestor(
      of: findListBody,
      matching: find.byType(SingleChildScrollView),
    );
    expect(findButton, findsOne);
    expect(findLastItem, findsOne);
    expect(findListBody, findsOne);
    expect(findListViewport, findsOne);

    // The button and the list viewport should overlap
    final RenderBox button = tester.renderObject<RenderBox>(findButton);
    final Rect buttonBounds = button.localToGlobal(Offset.zero) & button.size;
    final RenderBox listViewport = tester.renderObject<RenderBox>(findListViewport);
    final Rect listViewportBounds = listViewport.localToGlobal(Offset.zero) & listViewport.size;
    expect(listViewportBounds.topLeft.dy, lessThanOrEqualTo(windowSize.height));
    expect(listViewportBounds.bottomRight.dy, lessThanOrEqualTo(windowSize.height));
    expect(listViewportBounds, overlaps(buttonBounds));
  });
}

Matcher overlaps(Rect other) => OverlapsMatcher(other);

class OverlapsMatcher extends Matcher {
  OverlapsMatcher(this.other);

  final Rect other;

  @override
  Description describe(Description description) {
    return description.add("<Rect that overlaps with $other>");
  }

  @override
  bool matches(Object? item, Map matchState) => item is Rect && item.overlaps(other);

  @override
  Description describeMismatch(dynamic item, Description mismatchDescription,
      Map matchState, bool verbose) {
    return mismatchDescription.add("does not overlap");
  }
}
```

## Related issues

1. https://github.com/flutter/flutter/issues/142895

## Flutter version

```
[✓] Flutter (Channel main, 3.20.0-1.0.pre.20, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
    • Flutter version 3.20.0-1.0.pre.20 on channel main at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f8a77225f3 (9 hours ago), 2024-02-04 14:28:18 +0000
    • Engine revision f34c658b96
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0
```

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #142896

The original code below is to always place the selected item above(overlap) the popup button so that the selected item can always be visible: https://github.com/flutter/flutter/blob/f8a77225f360556322934a9a831ffc9c9f3125da/packages/flutter/lib/src/material/popup_menu.dart#L723-L732

But when menu height is constrained and the menu itself is super long, the selected item still assumes there is enough space to push up all the items whose index is smaller than the selected index. As a result, every time when the menu is open, the calculation provides a different result to be the offset for the selected index,  and then with a constrained height, the menu looks jumping all over the place based on the different selected index.

https://github.com/flutter/flutter/assets/36861262/ad761f95-0ff5-4311-a81d-dac56df879c5

Even though the original calculation is to make the selected item visible when open the menu, the menu doesn't auto scroll and only expands itself as much as possible to show the selected one. In this case, if the screen it too small to show the selected item, we still cannot see it. This can be fixed by using `Scrollable.ensureVisible()`(#143118).

So we remove the calculation in this PR and the menu will always show up based on the top left of the anchor(button).

https://github.com/flutter/flutter/assets/36861262/03272f26-9440-4ac4-a701-9a0b41776ff9

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -718,18 +718,7 @@ class _PopupMenuRouteLayout extends SingleChildLayoutDelegate {
     // size: The size of the overlay.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/popup_menu.dart:718]: This block of comments should be moved down, below `// Find the ideal horizontal position`, since they aren't needed to explain the y computation.

**Review by HansMuller — APPROVED** [review]
This changes the behavior of menus that don't need to scroll: before we tried to put the selected item over the menu button, now we always align the bottom of the menu with the bottom of the button.  I think the original idea was that the button would look like it contained the selected item (when everything fit that is). I think this change is OK, although it may break some golden image tests.

**Comment by QuncCccccc** [comment]
> This changes the behavior of menus that don't need to scroll: before we tried to put the selected item over the menu button, now we always align the bottom of the menu with the bottom of the button. I think the original idea was that the button would look like it contained the selected item (when everything fit that is). I think this change is OK, although it may break some golden image tests.

Got it! Thanks a lot for the explanation! For next [PR](https://github.com/flutter/flutter/pull/143118) which implements the auto scroll, the scrolled item will always be scrolled to the top of the menu, and the top of the menu is aligned with the button. So probably it can feel similar to the original idea? But yes, this PR changes a lot of menu behaviors.

<details><summary>video demo</summary>

https://github.com/flutter/flutter/assets/36861262/0782ed76-0616-4892-925f-520073984e3a
</details>

**Comment by HansMuller** [comment]
I think the behavior shown in https://github.com/flutter/flutter/pull/143121#issuecomment-1933138597 is sufficiently close to the original (buggy) behavior and also to the original _intended_ behavior. It looks like the customer tests are OK with it. It may trip up some internal tests; we'll have to see after you land it.
