### PR TITLE
Send statusBarTouch events via dedicated messages

### LINKED ISSUE #175606: [iPadOS 26] Clicking the top edge of the screen is recognized twice
### Steps to reproduce

1. Run any Flutter app on iPad (iOS 26). (I couldn't reproduce on iPhone)
2. Change SystemUiMode to `immersive` by running `SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);`.
3. You might need to rotate the screen to apply `immersive` mode due to this issue.
#175520
4. Click the top edge of the screen, and you can notice that the click is recognized twice.

### Expected results

A single click should be recognized once.

### Actual results

A single click is recognized twice.

https://github.com/user-attachments/assets/fb48a0b0-ce38-419f-8894-d466c1f955b2

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _count = 0;

  @override
  void initState() {
    super.initState();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: GestureDetector(
          onTap: () {
            setState(() {
              _count++;
            });
          },
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: Colors.grey,
            alignment: Alignment.topCenter,
            child: Text(
              '$_count',
              style: const TextStyle(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.4, on macOS 26.0 25A354 darwin-arm64, locale en-KR) [243ms]
    • Flutter version 3.35.4 on channel stable at /Users/seunghyun/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d693b4b9db (2 days ago), 2025-09-16 14:27:41 +0000
    • Engine revision c298091351
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, no-enable-linux-desktop, no-enable-macos-desktop, no-enable-windows-desktop,
      enable-android, enable-ios, cli-animations, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [997ms]
    • Android SDK at /Users/seunghyun/Library/Android/Sdk
    • Emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/seunghyun/Library/Android/Sdk
    • Java binary at: /Users/seunghyun/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [625ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A324
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [18ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [18ms]
    • Android Studio at /Users/seunghyun/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.2) [17ms]
    • IntelliJ at /Users/seunghyun/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.101.1) [5ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.112.0

[✓] Connected device (5 available) [5.8s]
    • Seunghyun’s iPad (wireless) (mobile)         • 00008020-001B59413A83002E            • ios            • iOS 18.6.2
      22G100
    • iPhone 14 Pro (mobile)                       • 3794BC81-1DEA-4AF4-B5FA-3DA2FCF87C6F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-26-0 (simulator)
    • iPad Pro (11-inch) (4th generation) (mobile) • 36564CCB-3F65-4FBF-8956-495C518CA3DE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-26-0 (simulator)
    • iPad Pro (11-inch) (4th generation) (mobile) • 1E2A25BD-1080-47CF-82C6-831C4928805A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-6 (simulator)
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome
      140.0.7339.185

[✓] Network resources [352ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #177992: Overlays close immediately after opening on iPadOS 26.1
### Steps to reproduce

1. Launch the sample app below on an iPad device or simulator running iPadOS 26.1 (update Xcode to v26.1 to get the latest simulators).
2. Tap the hamburger icon to open the end drawer.
3. Observe that it closes immediately. Occasionally it will behave correctly and not close by itself.

### Expected results

The end drawer should remain open until the user actively dismisses it.

### Actual results

On iPadOS 26.1, the end drawer closes by itself just after opening.

On older iPadOS versions, including 26.0, it behaves correctly and stays open until dismissed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Scaffold.endDrawer].

void main() => runApp(const EndDrawerExampleApp());

class EndDrawerExampleApp extends StatelessWidget {
  const EndDrawerExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: EndDrawerExample());
  }
}

class EndDrawerExample extends StatefulWidget {
  const EndDrawerExample({super.key});

  @override
  State<EndDrawerExample> createState() => _EndDrawerExampleState();
}

class _EndDrawerExampleState extends State<EndDrawerExample> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  void _closeEndDrawer() {
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: const Text('Drawer Demo'),
      ),
      body: Center(
        child: Text('iOS 26.1 Drawer bug. Tap the hamburger icon to trigger'),
      ),
      endDrawer: Drawer(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('This is the Drawer'),
              ElevatedButton(
                onPressed: _closeEndDrawer,
                child: const Text('Close Drawer'),
              ),
            ],
          ),
        ),
      ),
      // Disable opening the end drawer with a swipe gesture.
      endDrawerEnableOpenDragGesture: false,
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPad Air 11-inch (M3) in debug mode...
Running Xcode build...
Xcode build done.                                           11.6s
Syncing files to device iPad Air 11-inch (M3)...                    32ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPad Air 11-inch (M3) is available at: http://127.0.0.1:51132/VZCG7b-IIPk=/
The Flutter DevTools debugger and profiler on iPad Air 11-inch (M3) is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51132/VZCG7b-IIPk=/

Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.7, on macOS 15.6.1 24G90 darwin-arm64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] VS Code (version 1.105.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Instead of using fake touch events. 

Before this patch `FlutterViewController` sends two fake touch events (down and up), at `(0, 0)` to the framework to signal that the status bar is tapped on iOS. The scaffold widget and the cupertino page scaffold widget set up gesture detectors to listen for these fake taps, and scroll the "primary" scrollable container to the top in response.

This messaging mechanism is sometimes ambiguous, as the framework may interpret that as a pair of regular pointer tap events (for instance in #177992 the modal barrier claims the tap gesture and as a result the modal barrier is dismissed by the fake touch events). This PR changes that to communicate the status bar tap event via a new system channel, and dispatch the events via `WidgetsBindingObserver`s in the framework.

See also https://github.com/flutter/flutter/issues/177992#issuecomment-3499913265

Fixes #177992, fixes #175606

It appears that UIKit also has access to the coordinates of the touch events to determine which scrollable view(s?) to dispatch the scroll to top event to.
```objc
  * frame #0: 0x00000001032f6520 UIPlayground.debug.dylib`MyScrollViewController.scrollViewShouldScrollToTop(scrollView=0x0000000106014800) at UIScrollView.swift:13:3
    frame #2: 0x00000001867c9300 UIKitCore`-[UIScrollView _scrollToTopIfPossible:] + 316
    frame #3: 0x00000001867c9604 UIKitCore`-[UIScrollView _scrollToTopFromTouchAtScreenLocation:resultHandler:] + 40
    frame #4: 0x0000000186299bbc UIKitCore`__71-[UIWindow _scrollToTopViewsUnderScreenPointIfNecessary:resultHandler:]_block_invoke.358 + 168
    frame #5: 0x000000018629981c UIKitCore`-[UIWindow _scrollToTopViewsUnderScreenPointIfNecessary:resultHandler:] + 1212
    frame #6: 0x000000018581ed8c UIKitCore`-[UIStatusBarManager _handleScrollToTopAtXPosition:] + 192
    frame #7: 0x000000018581eb60 UIKitCore`-[UIStatusBarManager handleTapAction:] + 60
```
Unfortunately that information is not available to user application. The iOS accessibility bridge currently does create dummy UIScrollViews for each scrollable in the accessibility tree so may be we can take advantage of that in the future.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -2849,6 +2857,20 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
     super.didChangeDependencies();
   }
 
+  @override
+  void deactivate() {
+    WidgetsBinding.instance.removeObserver(this);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/scaffold.dart:2862]: It is more robust (currently) to do this in `deactivate` instead of `dispose` in case the callback throws an exception. Now I think about it, the decision to only try to call `deactivate` instead of `dispose` when an Element throws an exception when mounting/unmounting seems a bit random.

File: packages/flutter/lib/src/cupertino/page_scaffold.dart [hunk 2]
```diff
@@ -89,10 +89,30 @@ class CupertinoPageScaffold extends StatefulWidget {
...
+  }
+
+  @override
+  void activate() {
+    super.activate();
+    WidgetsBinding.instance.addObserver(this);
+  }
+
+  @override
+  @override
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/cupertino/page_scaffold.dart:111]: double override

**Review by hellohuanlin — COMMENTED** [review]
For easier review and future reference, could you update your PR description to explain why the bug happens, and how it is fixed by your PR?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/scaffold.dart:2862]: Somewhat related: https://github.com/flutter/flutter/issues/180434, some tests were failing when addObserver/removeObserver were done in `initState` and `dispose`, because the WidgetsBindingObserver list is a singleton and doesn't reset between tests.

**Comment by LongCatIsLooong** [comment]
> > for instance in #177992 the modal barrier claims the tap gesture and as a result the modal barrier is dismissed by the fake touch events
> 
> In the video of the linked issue, user single-taps on the menu bar (rather than the status bar), why does it trigger the fake touch events?

I think it's the status bar touch area became taller on iOS 26.1 so it became easier to reproduce the issue. `-[UIStatusBarManager handleTapAction:]` was called so iOS treated that menu bar tap as a status bar tap.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -2787,6 +2785,9 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
     );
 
     _bottomSheetScrimAnimationController = AnimationController(vsync: this);
+    if (widget.primary) {
+      WidgetsBinding.instance.addObserver(this);
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/material/scaffold.dart:2789]: i assume this is the place where the scaffold listens to the status bar event? How does the scaffold eventually pipe this info to corresponding scroll view to actually perform the scrolling?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -2743,10 +2738,13 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
   // to the top. We implement this by looking up the primary scroll controller and
   // scrolling it to the top when tapped.
-  void _handleStatusBarTap() {
+  @override
+  void handleStatusBarTap() {
+    super.handleStatusBarTap();
+    assert(widget.primary);
     final ScrollController? primaryScrollController = PrimaryScrollController.maybeOf(context);
     if (primaryScrollController != null && primaryScrollController.hasClients) {
       primaryScrollController.animateTo(
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/material/scaffold.dart:2750]: is this the controller of a scroll view?

File: packages/flutter/lib/src/widgets/binding.dart [hunk 5]
```diff
@@ -152,6 +152,22 @@ abstract mixin class WidgetsBindingObserver {
   /// predictive back feature.
   void handleCancelBackGesture() {}
 
+  /// Called when the user taps the status bar on iOS, to scroll a scroll
+  /// view to the top.
+  ///
+  /// This event should usually only be handled by at most one scroll view, so
+  /// implementer(s) of this callback must coordinate to determine the most
+  /// suitable scroll view for handling this event.
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/widgets/binding.dart:160]: What will happen if we have 2 scroll views?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/scaffold.dart:2789]: Yes, this allows all `active` Scaffold widgets to listen for status bar event updates. Adding `this` to the observer list means the `handleStatusBarTap` method will be called when the widgets binding receives a status bar tap message from the status bar message channel.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/scaffold.dart:2750]: It's a `PrimaryScrollController`, which is a special kind of ScrollController that controls the scroll offset of [primary scroll views](https://main-api.flutter.dev/flutter/widgets/ScrollView/primary.html)

File: packages/flutter/lib/src/widgets/binding.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/binding.dart:160]: It's ok to scroll more than one (thus the "usually"), this part is more of a UX suggestion to tell the implementer that not every scroll view in the view hierarchy should respond to this, it's up to the app developer to determine which scroll view is more relevant. Unfortunately UIKit does not give us the x offset of the tap event so in general the developer should choose the most "prominent" scroll view currently on screen (so the scaffold implementation chooses the "primary" scroll view(s)).

File: packages/flutter/lib/src/material/scaffold.dart [hunk 6]
```diff
@@ -2743,10 +2738,13 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
 
   // iOS FEATURES - status bar tap, back gesture
 
-  // On iOS and macOS, if `primary` is true, tapping the status bar scrolls the app's primary scrollable
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/material/scaffold.dart:2746]: are we removing macOS scroll-to-top feature here? if so, can you explain it in PR description?

**Review by hellohuanlin — APPROVED** [review]
the overall change makes sense to me, with one question on macOS. Thanks for writing the scenario tests.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 6 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/scaffold.dart:2746]: I removed macOS from the comment because I looked at the macOS embedder and there doesn't seem to be anything that has to do with "scroll to top" or "fake touch" so I think the comment was not accurate. `NSScrollView` doesn't seem to have a shouldSrollToTop callback either: https://developer.apple.com/documentation/appkit/nsscrollview

**Comment by Predidit** [comment]
Sorry for the ping, but I was wondering if this PR will be included in the upcoming Flutter 3.38.9 hotfix? Thanks!

**Comment by LongCatIsLooong** [comment]
> Am I correct that this fix will land in stable in 3.44 in May 2026?

This has already been cherry-picked to the current stable (but you might want to wait for this week's stable hotfix since there was a [crash](https://github.com/flutter/flutter/issues/182233)).

**Comment by filiptammergard** [comment]
> > Am I correct that this fix will land in stable in 3.44 in May 2026?
> 
> 
> 
> This has already been cherry-picked to the current stable (but you might want to wait for this week's stable hotfix since there was a [crash](https://github.com/flutter/flutter/issues/182233)). 

Alright, nice. Does that mean it'll land in 3.41.3 like tomorrow?
