### PR TITLE
Fix timing issues in initialization of web resident runner

### LINKED ISSUE #40115: `flutter run -d chrome` is not logging print statements on initial run
Repro:
```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('Important logging info');
    return SizedBox.expand();
  }
}
```

When I run this with `flutter run -d chrome` I don't see `"Importing logging info."` in the output. However, it appears after I do a hot restart (by pressing `r`).

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Don't claim to be building an application while we're actually trying to connect to it. Ensure that we register stdout listeners before calling main, so that we catch all print statements.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40115
Makes failure easier to understand in https://github.com/flutter/flutter/issues/41336

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 1]
```diff
@@ -202,23 +214,25 @@ class ResidentWebRunner extends ResidentRunner {
     // Cleanup old subscriptions. These will throw if there isn't anything
     // listening, which is fine because that is what we want to ensure.
     try {
-      await _debugConnection?.vmService?.streamCancel('Stdout');
+      await _vmService?.streamCancel('Stdout');
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: What's the difference between `_vmService` being `null` and `supportsServiceProtocol` being `false`? I'm not exactly sure why we null-check here but not inside `if (supportsServiceProtocol)`.

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: I guess they're actually the same, I could collapse them into one check

**Review by harryterkelsen — APPROVED** [review]
