### PR TITLE
Fixed the text aspect ratio

### LINKED ISSUE #162348: [impeller] font rect's aren't maintaining their shape with uniform scales
## reproduction steps
```c++
namespace {
double GetAspectRatio(Rect rect) {
  return static_cast<double>(rect.GetWidth()) / rect.GetHeight();
}
}  // namespace

TEST_P(TextContentsTest, MaintainsShape) {
#ifndef FML_OS_MACOSX
  GTEST_SKIP() << "Results aren't stable across linux and macos.";
#endif

  std::shared_ptr<TextFrame> text_frame =
      MakeTextFrame("th", "ahem.ttf", /*font_size=*/50);

  std::shared_ptr<TypographerContext> context = TypographerContextSkia::Make();
  std::shared_ptr<GlyphAtlasContext> atlas_context =
      context->CreateGlyphAtlasContext(GlyphAtlas::Type::kAlphaBitmap);
  std::shared_ptr<HostBuffer> host_buffer = HostBuffer::Create(
      GetContext()->GetResourceAllocator(), GetContext()->GetIdleWaiter());
  ASSERT_TRUE(context && context->IsValid());
  for (int i = 0; i <= 1000; ++i) {
    Scalar font_scale = 0.440 + (i / 1000.0);
    Rect position_rect[2];
    Rect uv_rect[2];

    {
      GlyphAtlasPipeline::VertexShader::PerVertexData data[12];
      std::shared_ptr<GlyphAtlas> atlas =
          CreateGlyphAtlas(*GetContext(), context.get(), *host_buffer,
                           GlyphAtlas::Type::kAlphaBitmap, font_scale,
                           atlas_context, text_frame);
      ISize texture_size = atlas->GetTexture()->GetSize();

      TextContents::ComputeVertexData(
          data, text_frame, font_scale,
          /*entity_transform=*/Matrix::MakeScale({font_scale, font_scale, 1}),
          /*offset=*/Vector2(0, 0),
          /*glyph_properties=*/std::nullopt, atlas);
      position_rect[0] = PerVertexDataPositionToRect(data);
      uv_rect[0] = PerVertexDataUVToRect(data, texture_size);
      position_rect[1] = PerVertexDataPositionToRect(data + 6);
      uv_rect[1] = PerVertexDataUVToRect(data + 6, texture_size);
    }
    EXPECT_NEAR(GetAspectRatio(position_rect[1]), GetAspectRatio(uv_rect[1]), 0.001) << i;
  }
}
```

## observed result

This fails about 30% of the time.

## expected result

I expect the aspect ratio of the uv's to match the position vertices.  Otherwise weird glyphs might appear stretched or shrunk.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/162348

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
This seems to affect https://github.com/flutter/flutter/issues/162394 positively in the defined case, it doesn't completely eliminate it though.

**Comment by gaaclarke** [comment]
Here is animating 0.444x to 0.445x (on a branch that has the adjust uv change).  It's hard to compare with other gifs since the glyphs seem to actually be growing at this boundary after the change.  That's not incorrect considering we are scaling them up.

ezgif-56f3db5d5f1fb

**Comment by gaaclarke** [comment]
Putting this into review.  I'd like to see golden results but my day will probably end before we get them.

File: engine/src/flutter/impeller/entity/contents/text_contents_unittests.cc [hunk 1]
```diff
@@ -163,5 +166,48 @@ TEST_P(TextContentsTest, SimpleComputeVertexData2x) {
...
+      MakeTextFrame("th", "ahem.ttf", /*font_size=*/50);
+
+  std::shared_ptr<TypographerContext> context = TypographerContextSkia::Make();
+  std::shared_ptr<GlyphAtlasContext> atlas_context =
+      context->CreateGlyphAtlasContext(GlyphAtlas::Type::kAlphaBitmap);
+  std::shared_ptr<HostBuffer> host_buffer = HostBuffer::Create(
+      GetContext()->GetResourceAllocator(), GetContext()->GetIdleWaiter());
+  ASSERT_TRUE(context && context->IsValid());
+  for (int i = 0; i <= 1000; ++i) {
+    Scalar font_scale = 0.440 + (i / 1000.0);
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/entity/contents/text_contents_unittests.cc:184]: I wouldn't expect the font to maintain the same aspect ratio across larger scales, but across small values like you have here 0.5 -> 0.51 this test seems reasonable to me. 

Are the results unstable on non mac platforms?

**Review by jonahwilliams — APPROVED** [review]
LGTM w/ question

File: engine/src/flutter/impeller/entity/contents/text_contents_unittests.cc (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_contents_unittests.cc:180]: oh, right. I was thinking about between uvs across scales. This makes more sense 🤦

**Review by jonahwilliams — APPROVED** [review]
Still LGTM

**Comment by gaaclarke** [comment]
I can reproduce that flutter_tester failure locally.  There is one pixel difference when generating the textures for some reason (these images were scaled 3x and given a grey background):

## roboto
Roboto

## ahem
Ahem

**Comment by gaaclarke** [comment]
@jonahwilliams we had 2 options to fix this, remove the 0.5 offset or add non-square uv's to mimic what we used to do but keep the same aspect ratio.  I've opted to try out the first option after playing around with it.  I'm not seeing any negative with my testing.

## the second option
```c++
      Point uv_origin =
          (atlas_glyph_bounds.GetLeftTop() - Point(0.5, 0.5)) / atlas_size;
      // Since we are translating the UVs to cover the center of texels we will
      // expand the uv's to cover the last pixels, we don't add square pixels
      // though to maintain the same aspect ratio.
      Scalar inv_aspect_ratio = atlas_glyph_bounds.GetSize().height /
                                atlas_glyph_bounds.GetSize().width;
      Point uv_size =
          (atlas_glyph_bounds.GetSize() + Point(1, inv_aspect_ratio)) /
          atlas_size;
```

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
I didn't realize that Impeller was doing this kind of text stuff (thought it was still Skia), or is that a new thing?

**Comment by gaaclarke** [comment]
> I didn't realize that Impeller was doing this kind of text stuff (thought it was still Skia), or is that a new thing?

Funny should ask! I have a doc for you: https://docs.google.com/document/d/1Rulw_noQi0G8Glb47vk17uBbb6sySDxlQe-l-0kHn14/edit?tab=t.0#heading=h.lje1se38wqjf

TLDR: We use skia to draw glyphs into a texture then we draw geometry that samples from it.

**Comment by gaaclarke** [comment]
Nothing shows up as wrong on goldens.
