### PR TITLE
Web semantics: Fix email field selection/cursor by using type="text" + inputmode="email"

### LINKED ISSUE #173239: email type input misbehave on Flutter web
### Steps to reproduce

These are two separate bugs but reporting together as both concern the same input field type.

### Cursor wouldn't move when typing in
This looks like a regression, hadn't been noticed in previous versions. When changing to `keyboardType: TextInputType.text`, the issue is gone.

### Repositioning cursor into field that already has text triggers error:
`InvalidStateError: The input element's type ('email') does not support selection.`
<summary>Log entries</summary>
<details>

```console
dart://_internal/js_shared/lib/js_util_patch.dart 173:10            DomHTMLInputElement|setSelectionRange
org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart 1438:21                 DefaultTextEditingStrategy.setEditingState
org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart 1559:7                  DefaultTextEditingStrategy.enable
org-dartlang-sdk:///lib/_engine/engine/semantics/text_field.dart 81:11                        SemanticsTextEditingStrategy.activate
org-dartlang-sdk:///lib/_engine/engine/semantics/semantics.dart 2008:9                        SemanticsObject._updateRole
org-dartlang-sdk:///lib/_engine/engine/semantics/semantics.dart 1692:5                        EngineSemanticsOwner.updateSemantics
org-dartlang-sdk:///lib/_engine/engine/window.dart 109:15                                     RenderView.updateSemantics
../../../../../../flutter/packages/flutter/lib/src/semantics/semantics.dart 4246:5            SemanticsOwner.sendSemanticsUpdate
../../../../../../flutter/packages/flutter/lib/src/rendering/object.dart 1502:7               PipelineOwner.flushSemantics
../../../../../../flutter/packages/flutter/lib/src/rendering/object.dart 1504:9               PipelineOwner.flushSemantics
../../../../../../flutter/packages/flutter/lib/src/rendering/binding.dart 325:22              RendererBinding.rootPipelineOwner
../../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart 1242:13               _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
../../../../../../flutter/packages/flutter/lib/src/rendering/binding.dart 495:5               RendererBinding._handlePersistentFrameCallback
dart://_internal/js_runtime/lib/js_helper.dart 2621:9               Closure.cspForwardCall
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1438:7              SchedulerBinding._invokeFrameCallback
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1351:9              SchedulerBinding.handleDrawFrame
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1204:5              SchedulerBinding._handleDrawFrame
dart://_internal/js_runtime/lib/js_helper.dart 2610:9               Closure.cspForwardCall
org-dartlang-sdk:///lib/_engine/engine/platform_dispatcher.dart 1312:5                        invoke
org-dartlang-sdk:///lib/_engine/engine/platform_dispatcher.dart 255:5                         FrameService._renderFrame
dart://async/zone.dart 1546:12                                      _rootRunUnary
dart://async/zone.dart 1428:34                                      _CustomZone.runUnary
dart://_internal/js_runtime/lib/js_allow_interop_patch.dart 363:27  _callDartFunctionFast1
```

</details>

### Expected results

Cursor should follow typed in chars; there should be no error when returning focus to a prefilled field.

### Actual results

See above.

### Code sample

<details open><summary>Code sample</summary>

```dart
keyboardType: TextInputType.emailAddress
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
dart://_internal/js_shared/lib/js_util_patch.dart 173:10            DomHTMLInputElement|setSelectionRange
org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart 1438:21                 DefaultTextEditingStrategy.setEditingState
org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart 1559:7                  DefaultTextEditingStrategy.enable
org-dartlang-sdk:///lib/_engine/engine/semantics/text_field.dart 81:11                        SemanticsTextEditingStrategy.activate
org-dartlang-sdk:///lib/_engine/engine/semantics/semantics.dart 2008:9                        SemanticsObject._updateRole
org-dartlang-sdk:///lib/_engine/engine/semantics/semantics.dart 1692:5                        EngineSemanticsOwner.updateSemantics
org-dartlang-sdk:///lib/_engine/engine/window.dart 109:15                                     RenderView.updateSemantics
../../../../../../flutter/packages/flutter/lib/src/semantics/semantics.dart 4246:5            SemanticsOwner.sendSemanticsUpdate
../../../../../../flutter/packages/flutter/lib/src/rendering/object.dart 1502:7               PipelineOwner.flushSemantics
../../../../../../flutter/packages/flutter/lib/src/rendering/object.dart 1504:9               PipelineOwner.flushSemantics
../../../../../../flutter/packages/flutter/lib/src/rendering/binding.dart 325:22              RendererBinding.rootPipelineOwner
../../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart 1242:13               _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
../../../../../../flutter/packages/flutter/lib/src/rendering/binding.dart 495:5               RendererBinding._handlePersistentFrameCallback
dart://_internal/js_runtime/lib/js_helper.dart 2621:9               Closure.cspForwardCall
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1438:7              SchedulerBinding._invokeFrameCallback
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1351:9              SchedulerBinding.handleDrawFrame
../../../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart 1204:5              SchedulerBinding._handleDrawFrame
dart://_internal/js_runtime/lib/js_helper.dart 2610:9               Closure.cspForwardCall
org-dartlang-sdk:///lib/_engine/engine/platform_dispatcher.dart 1312:5                        invoke
org-dartlang-sdk:///lib/_engine/engine/platform_dispatcher.dart 255:5                         FrameService._renderFrame
dart://async/zone.dart 1546:12                                      _rootRunUnary
dart://async/zone.dart 1428:34                                      _CustomZone.runUnary
dart://_internal/js_runtime/lib/js_allow_interop_patch.dart 363:27  _callDartFunctionFast1

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.8, on macOS 15.3.2 24D81 darwin-arm64, locale en-US) [220ms]
  • Flutter version 3.32.8 on channel stable at /Users/ilija/flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision edada7c56e (10 days ago), 2025-07-25 14:08:03 +0000
  • Engine revision ef0cd00091
  • Dart version 3.8.1
  • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [807ms]
  • Android SDK at /Users/ilija/Library/Android/sdk
  • Platform android-36, build-tools 36.0.0
  • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
   This JDK is specified in your Flutter configuration.
   To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
  • Java version OpenJDK Runtime Environment Homebrew (build 17.0.14+0)
  • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [440ms]
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Build 16C5032a
  • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [7ms]
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] Connected device (2 available) [5.6s]
  • macOS (desktop) • macos • darwin-arm64  • macOS 15.3.2 24D81 darwin-arm64
  • Chrome (web)  • chrome • web-javascript • Google Chrome 134.0.6998.166

[✓] Network resources [321ms]
  • All expected network resources are available.

• No issues found!

[✓] Flutter (Channel stable, 3.32.8, on macOS 15.3.2 24D81 darwin-arm64, locale en-US) [220ms]
  • Flutter version 3.32.8 on channel stable at /Users/ilija/flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision edada7c56e (10 days ago), 2025-07-25 14:08:03 +0000
  • Engine revision ef0cd00091
  • Dart version 3.8.1
  • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [807ms]
  • Android SDK at /Users/ilija/Library/Android/sdk
  • Platform android-36, build-tools 36.0.0
  • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
   This JDK is specified in your Flutter configuration.
   To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
  • Java version OpenJDK Runtime Environment Homebrew (build 17.0.14+0)
  • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [440ms]
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Build 16C5032a
  • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [7ms]
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   :hammer: https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] Connected device (2 available) [5.6s]
  • macOS (desktop) • macos • darwin-arm64  • macOS 15.3.2 24D81 darwin-arm64
  • Chrome (web)  • chrome • web-javascript • Google Chrome 134.0.6998.166

[✓] Network resources [321ms]
  • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
**What/Why**
On Flutter Web with semantics enabled, <input type="email"> can reject selection APIs in some browsers, causing:
cursor to not advance while typing,
selection to fail (and selected text not deletable),
and, in some cases, InvalidStateError exceptions.
This PR updates the semantics editing element for email fields to keep selection/cursor APIs working while preserving email UX.

**How**
In engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart:
Use type="text" for SemanticsInputType.email
Add inputmode="email" (keeps email keyboard layout/hints)
Add autocomplete="email" (preserves autofill)
Add autocapitalize="none" (prevents unwanted capitalization)
Remove the attributes when not email
Rationale: type="text" avoids browser selection restrictions; inputmode="email" preserves the expected email keyboard; autofill and capitalization behavior is retained/optimized.

**Before/After**
Before the change
https://email-0923-before.web.app/
After the change
https://email-0923.web.app/

**Impact**
Cursor now advances correctly while typing in email fields under semantics.
Text can be selected and deleted normally.
Avoids InvalidStateError crashes with accessibility semantics enabled.

**Tests/Verification**
Manually verified on Chrome and safari:
Typing in email fields advances cursor correctly
Drag-select, double-click select, and Cmd/Ctrl+A work
Deleting selected text works
No exceptions thrown with semantics enabled
Autofill prompts continue to appear when saved emails are available.
Mobile keyboards (iOS/Android) show email-optimized layout via inputmode="email".

**Fixed issues**
Fixes flutter/flutter#173239

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart [hunk 1]
```diff
@@ -353,13 +353,26 @@ class SemanticTextField extends SemanticRole {
...
       };
+      input.type = resolvedType;
+      if (semanticsObject.inputType == ui.SemanticsInputType.email) {
+        input.setAttribute('inputmode', 'email');
+        input.setAttribute('autocapitalize', 'none');
+        input.autocomplete = 'email';
+      } else {
+        input.removeAttribute('inputmode');
+        input.removeAttribute('autocapitalize');
+      }
```
[the remark this answers is not in the document]
Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart]: Updated.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart [hunk 2]
```diff
@@ -353,13 +353,27 @@ class SemanticTextField extends SemanticRole {
     if (semanticsObject.flags.isObscured) {
       input.type = 'password';
     } else {
-      input.type = switch (semanticsObject.inputType) {
+      // For email inputs, prefer type="text" with inputmode="email" so that
+      // browsers keep selection APIs enabled while still providing email
+      // keyboards and hints. This avoids InvalidStateError and enables
+      // proper selection/cursor operations.
+      final String resolvedType = switch (semanticsObject.inputType) {
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart]: we should probably use the regular switch case instead of pattern match so that it is more clear what  `ui.SemanticsInputType.email` will do instead of separating them out to be another if else

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this! I left a minor suggestion.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart (hunk 2 above)
Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart]: Great suggestion. Updated.

**Review by mdebbar — APPROVED** [review]
Thanks for fixing this!

At some point in the future, we should unify this part of the semantics mode with the non-semantics mode that uses:
- https://github.com/flutter/flutter/blob/master/engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/input_type.dart
- and https://github.com/flutter/flutter/blob/master/engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/autofill_hint.dart
