### PR TITLE
don't break sheet's snap from physics

### LINKED ISSUE #169712: DraggableScrollableSheet with BouncingScrollPhysics, SliverList, and uneven child sizes behaves erratically
### Steps to reproduce

1. Run following code
2. Expand sheet and scroll to bottom
3. Fling down expecting sheet to snap to top
4. Repeat 2-3 until sheet misbehaves (see video, it either collapses altogether to the minHeight or bounces too much)

### Expected results

`DraggableScrollableSheet` behaves correctly - the same way one achieves applying workarounds (1) or (3) commend in the code below

### Actual results

`DraggableScrollableSheet` behaves incorrectly:
- either bounces too much (compare to the 2nd video)
- or collapses altogether, missing 0.5 height snap

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Material(child: TestPage()));
  }
}

class TestPage extends StatelessWidget {
  const TestPage({super.key});

  @override
  Widget build(BuildContext context) {
    final children = List<Widget>.generate(12, (_) {
      return Padding(
        padding: EdgeInsets.only(bottom: 10),
        child: Container(color: Colors.green, height: 100),
      );
    });
    // 1st workaround: removing this line 'fixes' the issue
    children.insert(0, Container(color: Colors.green, height: 100));

    return DraggableScrollableSheet(
      shouldCloseOnMinExtent: false,
      snap: true,
      snapAnimationDuration: const Duration(milliseconds: 220),
      snapSizes: [0.5],
      maxChildSize: 1,
      initialChildSize: 0.5,
      minChildSize: 0.2,
      builder: (context, scrollController) {
        return CustomScrollView(
          // 2nd workaround: removing BouncingScrollPhysics 'fixes' the issue
          physics: const BouncingScrollPhysics(),
          controller: scrollController,
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate((context, index) {
                return children[index];
              }, childCount: children.length),
            ),
            // 3rd workaround: replacing SliverList with this 'fixes' the issue
            // SliverToBoxAdapter(
            //   child: Column(children: children),
            // ),
          ],
        );
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/1ac3581a-4acd-44c3-a28f-9fe0f27fbf40

https://github.com/user-attachments/assets/ed0084fa-4af1-402c-b3f1-c02710ec301d

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.4.1 24E263 darwin-arm64, locale en) [275ms]
    • Flutter version 3.32.0 on channel stable at /Users/yauhen/fvm/versions/3.32.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (10 days ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1
    • Pub download mirror https://pub.dev

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [994ms]
    • Android SDK at /Users/yauhen/Library/Android/sdk/
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/yauhen/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [702ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.1) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (3 available) [5.9s]
    • Pixel 6 (mobile) • 24201FDF6008SA • android-arm64  • Android 15 (API 35)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [756ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by emakar**
Fixes https://github.com/flutter/flutter/issues/169712

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Comment by emakar** [comment]
added test as well

**Comment by justinmc** [comment]
@MitchellGoodwin From triage, tagged you for review, but let me know if you're not the right person.

**Comment by emakar** [comment]
@MitchellGoodwin Hi, could please take a look?

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [hunk 1]
```diff
@@ -1918,4 +1918,81 @@ void main() {
...
+        const Duration(milliseconds: 500),
+      );
+
+      await tester.fling(find.text('Item 2'), Offset(0, itemHeight), 500);
+      await tester.pumpFrames(
+        tester.widget(find.byType(MaterialApp)),
+        const Duration(milliseconds: 500),
+      );
+
+      expect(lastExtent, 1.0);
```
Comment (MitchellGoodwin) [inline packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1983]: This test just checks that the extent stays at max after these gestures. Looking at the issue linked, we should probably also check that the sheet is able to snap down to the `0.5` extent with a reasonable fling speed as well.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 2]
```diff
@@ -972,10 +972,13 @@ class _DraggableScrollableSheetScrollPosition extends ScrollPositionWithSingleCo
     _ballisticControllers.add(ballisticController);
 
     double lastPosition = extent.currentPixels;
+    final bool wasExpanded = extent.isAtMax;
     void tick() {
       final double delta = ballisticController.value - lastPosition;
       lastPosition = ballisticController.value;
-      extent.addPixelDelta(delta, context.notificationContext!);
+      if (!wasExpanded || !extent.snap) {
+        extent.addPixelDelta(delta, context.notificationContext!);
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: This feels like a bandaid. Theoretically `addPixelDelta` should not do anything if the gesture is in the upwards direction at the end of the extent, so if that's failing then the issue should be there. Also, it feels like this should not be blocked if going downwards.

**Review by MitchellGoodwin — COMMENTED** [review]
Apologies for the late review. I'm new to this area of the code, so it takes a bit to look at. You may need to walk me through some things if I am misunderstanding something.

That said, my understanding is that this weird behavior is caused by a list of widgets without a uniform size and the bouncing scroll physics. It looks like the calculations of the pixel height of the child is getting thrown off as the constraints dynamically change, which gets funky when this widget and the bouncing scroll physics are both trying to do weird things on overscroll. I'm not sure if this is enough of a fix for the underlying issue?

**Review by MitchellGoodwin — COMMENTED** [review]
Apologies for the late review. I'm new to this area of the code, so it takes a bit to look at. You may need to walk me through some things if I am misunderstanding something.

That said, my understanding is that this weird behavior is caused by a list of widgets without a uniform size and the bouncing scroll physics. It looks like the calculations of the pixel height of the child is getting thrown off as the constraints dynamically change, which gets funky when this widget and the bouncing scroll physics are both trying to do weird things on overscroll. I'm not sure if this is enough of a fix for the underlying issue?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (emakar) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: Yep, it's a crude bandaid indeed. I'm however not experienced in scroll physics and don't have much time to invest to the issue at the moment
I can add a disabled test and look for a solution later, wdyt?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: As in merge a disabled test? I don't think we've done that in the past. It would add dead code which is likely to cause confusion when future contributors are trying to gauge intent. 

I also don't have a ton of time at the moment to look into this issue, but it's very interesting so that's understandable. If you are unable to keep updating this PR, you can either close it and reopen it when you are able to have more time, or mark it as a draft if you want to keep going at it slowly. We typically will close PRs after a month of no response.

Comment (emakar) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: Ok, thanks, will try to dig deeper

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart (hunk 1 above)
Comment (emakar) [reply packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1983]: Not sure snapping to 0.5 is correct - non-bouncing physics clamps at 1.0

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (emakar) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: Well, your suggestion helped, I think
Can you take a look at new fix?

Comment (emakar) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: Closing issue as the code is reworked

**Comment by emakar** [comment]
@MitchellGoodwin gentle ping

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 3]
```diff
@@ -1185,6 +1185,10 @@ class _SnappingSimulation extends Simulation {
       return pixelSnapSizes.first;
     }
     final double nextSize = pixelSnapSizes[indexOfNextSize];
+    // If already snapped - keep this as target size
+    if (nextSize == position) {
+      return nextSize;
+    }
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:1191]: 👍 Nice and simple.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for taking the time to make this fix. I'll ask around for a second review.

**Review by Piinks — APPROVED** [review]
LGTM thanks!

**Comment by Piinks** [comment]
Rebasing since the bot will tell us to do that anyways before merging.
