### PR TITLE
[flutter_tools] fix iOS build inconsistencies and pipe through performance file

### LINKED ISSUE #56086: Running `flutter build ios` repeatedly never uses assemble cache
Running `flutter build ios` always shows:
```
[ +100 ms] aot_assembly_release: Complete
[   +7 ms] invalidated build due to missing files: /Users/m/Projects/test_pod_build_time/.dart_tool/flutter_build/af5a0e679ea53f3f76835a83d0ee9bb5/App
```
That file is indeed missing, I think it should be `flutter_build/af5a0e679ea53f3f76835a83d0ee9bb5/App.framework/App`?

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Ensure iOS and android builds can be correctly cached. Use the performance-measurement-file to verify that all targets were skipped on the second invocation. This is only run on the flutter_gallery build.

When plumbing the flag through I updated the xcode scripts to use the same environment variable logic as linux and windows to simplify the code. I also removed the custom `track-widget-creation` flag from build_appbundle in favor of the standard flag. This updated the default in safe/backwards compatible way.

Fixes https://github.com/flutter/flutter/issues/56086

### CODE REVIEW

File: packages/flutter_tools/bin/macos_assemble.sh [hunk 1]
```diff
@@ -62,26 +62,22 @@ ephemeral_dir="${SOURCE_ROOT}/Flutter/ephemeral"
...
     ${flutter_engine_flag}                                                  \
     ${local_engine_flag}                                                    \
     assemble                                                                \
+    ${performance_measurement_option}                                       \
     -dTargetPlatform=darwin-x64                                             \
     -dTargetFile="${target_path}"                                           \
     -dBuildMode="${build_mode}"                                             \
-    -dTreeShakeIcons="${icon_tree_shaker_flag}"                             \
-    -dDartObfuscation="${dart_obfuscation_flag}"                            \
+    -dTreeShakeIcons="${TREE_SHAKE_ICONS}"                                  \
```
Comment (jonahwilliams) [inline packages/flutter_tools/bin/macos_assemble.sh:79]: There is no need to conditionally set these flags, assemble just checks if `== true`, so an empty string if they are unset is fine.

File: dev/bots/test.dart [hunk 2]
```diff
@@ -332,9 +336,10 @@ Future<void> _runBuildTests() async {
 
 Future<void> _flutterBuildApk(String relativePathToApplication, {
   @required bool release,
+  bool verifyCaching = false,
```
Comment (christopherfujino) [inline dev/bots/test.dart:339]: do we currently ever invoke this without verifying?

File: packages/flutter_tools/lib/src/build_info.dart [hunk 3]
```diff
@@ -89,6 +90,13 @@ class BuildInfo {
   /// A list of Dart experiments.
   final List<String> dartExperiments;
 
+  /// The name of a file where flutter assemble will output performance
+  /// information in a JSON format.
+  ///
+  /// This is not considered a build inpit and will not force assemble to
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/build_info.dart:96]:
```suggestion
  /// This is not considered a build input and will not force assemble to
```

**Comment by jonahwilliams** [comment]
Hmm @christopherfujino your edit got applied as a gmail address

**Comment by jonahwilliams** [comment]
@googlebot I fixed it

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
The docs linux task did finish successfully
