### PR TITLE
Fix selection area causes small scrollables to bounce

### LINKED ISSUE #110917: Scroll crazy when SelectionArea + SingleChildScrollView
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Just select text.

Sep-04-2022 03-52-45

<details>
<summary>Code sample</summary>

```dart
Widget build(BuildContext context) {
    return const SelectionArea(
      child: Scaffold(
        body: Center(
          child: SizedBox(
            width: 100,
            height: 20,
            child: SingleChildScrollView(
              child: Text('adfadsfadfdasfadsfadsfadsfadsfadsfasdfadsf'),
            ),
          ),
        ),
      ),
    );
  }
```

</details>

<details>

```
Flutter 3.4.0-19.0.pre.63 • channel master • https://github.com/flutter/flutter.git
Framework • revision 81906fffda (11 hours ago) • 2022-09-03 04:06:18 -0400
Engine • revision 201fd14c71
Tools • Dart 2.19.0 (build 2.19.0-168.0.dev) • DevTools 2.17.0
```

</details>

@chunhtai

### PR DESCRIPTION
**Pull request by chunhtai**
The problem is that the Selection container of scrollable may pass rect larger than the scrollable to the auto scroller. The auto scroll attempt to scroll the scrollable to review the target rect, and it keep scrolling up and down to try to fit the target rect.

This pr fixes it by passing zero size rect to autoscroller instead.

fixes https://github.com/flutter/flutter/issues/110917
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -1000,23 +1005,27 @@ class EdgeDraggingAutoScroller {
...
-      }
-    } else {
-      if (proxyStart < viewportStart && scrollable.position.pixels > scrollable.position.minScrollExtent) {
-        overDrag = math.max(viewportStart - proxyStart, overDragMax);
-        newOffset = math.max(scrollable.position.minScrollExtent, scrollable.position.pixels -  overDrag);
-      } else if (proxyEnd > viewportEnd && scrollable.position.pixels < scrollable.position.maxScrollExtent) {
-        overDrag = math.max(proxyEnd - viewportEnd, overDragMax);
-        newOffset = math.min(scrollable.position.maxScrollExtent, scrollable.position.pixels + overDrag);
-      }
+    switch (_axisDirection) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/scrollable.dart:1008]: This is mainly a refactor, the only change is it used to use math.max to calculate overDrag which is incorrect.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 2]
```diff
@@ -1055,7 +1064,10 @@ class _ScrollableSelectionContainerDelegate extends MultiSelectableSelectionCont
     _position.addListener(_scheduleLayoutChange);
   }
 
-  static const double _kDefaultDragTargetSize = 200;
+  // Pointer drag is a single point, it should not have a size.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/scrollable.dart:1067]: This causes problem when the scrollable is less than 200

File: packages/flutter/test/widgets/scrollable_selection_test.dart [hunk 3]
```diff
@@ -150,6 +150,54 @@ void main() {
...
+    await gesture.up();
+
+    // Should not stuck if gesture is up.
+    bool hasError = false;
+    try {
+      await tester.pumpAndSettle(const Duration(seconds: 1));
+    } on FlutterError catch (_) {
+      hasError = true;
+    }
+    expect(hasError, isFalse);
```
Comment (justinmc) [inline packages/flutter/test/widgets/scrollable_selection_test.dart:198]: Could you use `takeException` here instead of the try/catch?

File: packages/flutter/test/widgets/scrollable_selection_test.dart [hunk 4]
```diff
@@ -125,7 +125,7 @@ void main() {
     expect(controller.offset, 0.0);
     double previousOffset = controller.offset;
 
-    await gesture.moveTo(tester.getBottomRight(find.byType(ListView)));
+    await gesture.moveTo(tester.getBottomRight(find.byType(ListView)) + const Offset(0, 20));
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/widgets/scrollable_selection_test.dart:128]: And below as well.

**Review by justinmc — APPROVED** [review]
LGTM 👍 with nits.

File: packages/flutter/test/widgets/scrollable_selection_test.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/test/widgets/scrollable_selection_test.dart:128]: Before you can start auto drag if the drag closer to the boundary(with in 100 pixels), it now need to drag pass the rect. Added comments to the tests.
