### PR TITLE
cacheWidth cacheHeight support for canvaskit on web

### LINKED ISSUE #88704: [web] canvaskit performance issue
## Details

1.  To reproduce: put scaled images in a Stack wrapped with an InteractiveViewer (see gist)
The problem is that the performance is fine on macOS desktop target, however on Chrome with canvaskit, the performance really suffers.
Test was done with `--release` and `--web-renderer canvaskit`

2. [Sample app](https://gist.github.com/laurensdewaele/a0e195837765f2d3f75924dfaa04177a)

4. [Video showcasing osx vs chrome](https://drive.google.com/file/d/1e0KCxD9pUFkFZuA_qKa0dE4vXZ_PG2WQ/view?usp=sharing)

**Target Platform: macOS / Web
**Target OS version/browser: 11.5.2 / 92

## Logs

<details>
<summary>Logs</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.188, on macOS 11.5.2 20G95 darwin-arm, locale en-BE)
    • Flutter version 2.5.0-7.0.pre.188 at /Users/laurens/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 369a0e2bc0 (65 minutes ago), 2021-08-23 09:17:04 -0400
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/laurens/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```
</details>

### PR DESCRIPTION
**Pull request by alanwutang11**
This PR is the framework side fix for adding`cacheWidth` and `cacheHeight` support to web canvaskit. 

Previously, `cacheWidth` and `cacheHeight` parameters for `Image.network` were not supported on the web. A fix to add support for canvaskit on the engine side was made here: https://github.com/flutter/engine/pull/38028 

This PR, along with the engine side fix, fixes: https://github.com/flutter/flutter/issues/88704

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+import 'dart:async';
+import 'dart:ui' as ui;
+
+import 'package:flutter/material.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:integration_test/integration_test.dart';
+
+
+class LoadTestImageProvider extends ImageProvider<Object> {
```
Comment (yjbanov) [inline dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:13]: I'm not sure this class is necessary. It's not passed to the `Image` widget as an actual provider. Instead, the test calls its `testLoad` method directly, which means the test could also call `image.image.loadBuffer` directly with the same effect.

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+      expect(cacheHeight, expectedCacheHeight);
+      expect(cacheWidth, expectedCacheWidth);
+      expect(allowUpscaling, false);
+      called = true;
+      return PaintingBinding.instance.instantiateImageCodecFromBuffer(buffer, cacheWidth: cacheWidth, cacheHeight: cacheHeight, allowUpscaling: allowUpscaling);
+    }
+
+    final ImageProvider resizeImage = image.image;
+    expect(image.image, isA<ResizeImage>());
+    expect(called, false);
```
Comment (yjbanov) [inline dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:61]: This expectation doesn't seem to have an effect. AFAICT the `decode` function hasn't been used for anything at this point, so it couldn't have been called. Maybe it should go below `testProvider.testLoad`? (I'm actually not sure when it's expected to be called)

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 3]
```diff
@@ -121,16 +118,18 @@ class NetworkImage
 
     // We use a different method when headers are set because the
     // `ui.webOnlyInstantiateImageCodecFromUrl` method is not capable of handling headers.
-    if (key.headers?.isNotEmpty ?? false) {
+    if (isCanvasKit || (key.headers?.isNotEmpty ?? false)) {
```
[the remark this answers is not in the document]
Comment (alanwutang11) [reply packages/flutter/lib/src/painting/_network_image_web.dart:121]: done

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart (hunk 1 above)
Comment (alanwutang11) [reply dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:13]: `image.image.loadBuffer` is a protected method, so `testLoad` was created as a workaround

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart (hunk 2 above)
Comment (alanwutang11) [reply dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:61]: Yea, on second thought, that check is not necessary. It might be fine to just check at the end if `called` has been flipped to true. It should be called with the `loadBuffer` call made by `testProvider.testLoad`.

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart (hunk 1 above)
Comment (yjbanov) [reply dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:13]: Ah, makes sense. Might be useful to leave a comment explaining this as it's not immediately obvious why this is necessary.

**Review by yjbanov — APPROVED** [review]
lgtm

File: dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart (hunk 1 above)
Comment (alanwutang11) [reply dev/integration_tests/web_e2e_tests/test_driver/cache_width_cache_height_integration.dart:13]: will do.
