### PR TITLE
[flutter_tools] switch dart defines to base64 to avoid windows control characters

### LINKED ISSUE #74705: Window Desktop --no-sound-null-safety Flag not working
Hello

i use `flutter run -d windows --no-sound-null-safety` to start my app.

First of all i can run `flutter run -d chrome --no-sound-null-safety` so the problem is the windows part.
On windows i get a build error
```
CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies [..projectpath\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): 
error MSB8066: Der benutzerdefinierte Build für "..projectpath\build\windows\CMakeFiles\f45350e4b9bdfbf055bf3e467fa8d732\flutter_windows.dll.rule;
..projectpath\build\windows\CMakeFiles\7c37d35deda4d5243c60a614dcf87275\flutter_assemble.rule" wurde mit dem Code 1 beendet. 
[..projectpath\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
```
I expect it to run as i use the --no-sound-null-safety-flag
Also there is no hint what the dependencie causing the error should be because `\flutter_assemble.vcxproj` makes not much sense for me.

I'm on `flutter channel dev 1.26.0-12.0.pre`, output of doctor, just in case:

```
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] Connected device (3 available)

• No issues found!
```

### LINKED ISSUE #75017: Build failures in window target not surfaced to tool
To repro `flutter create example` , migrate to null safety, then add an import and dependency on non-null safe code.

`flutter run -d windows` should fail, since it will detect the entrypoint as being migrated and default to sound mode. This happens, but we don't seem to notice or forward the error from cmake, so instead of existing with an error - we run whatever the previously built binary was.

### PR DESCRIPTION
**Pull request by jonahwilliams**
`=` gets escaped into `%3D` which seems to be tripping up cmake on windows since `%` is a control character. Switch to base64 encoding, since this does not have `%` nor `,` in the output character set.

This change is not trivially cherry pickable, and isn't tested on windows aside from my local, manual tests due to the planned CI work not being complete yet.

Fixes https://github.com/flutter/flutter/issues/75017
Fixes https://github.com/flutter/flutter/issues/74705

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I did also make various attempts to escape `%` with no success

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 1]
```diff
@@ -308,15 +308,8 @@ Future<void> buildGradleApp({
   if (target != null) {
     command.add('-Ptarget=$target');
   }
-  assert(buildInfo.trackWidgetCreation != null);
-  command.add('-Ptrack-widget-creation=${buildInfo.trackWidgetCreation}');
+  command.addAll(androidBuildInfo.buildInfo.toGradleConfig());
 
-  if (buildInfo.extraFrontEndOptions != null) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/gradle.dart:314]: To avoid future refactor breakage, I moved the logic for encoding the various build options into the build config, similar to how it is done for desktop. This changed a few of the expectations.

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 2]
```diff
@@ -611,18 +583,12 @@ Future<void> buildGradleAar({
   if (target != null && target.isNotEmpty) {
     command.add('-Ptarget=$target');
   }
-  if (buildInfo.splitDebugInfoPath != null) {
-    command.add('-Psplit-debug-info=${buildInfo.splitDebugInfoPath}');
-  }
-  if (buildInfo.treeShakeIcons) {
-    command.add('-Pfont-subset=true');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/gradle.dart:618]: Not a thing anymore.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/gradle.dart:618]: (its called tree-shake-icons)

File: packages/flutter_tools/lib/src/build_info.dart [hunk 3]
```diff
@@ -737,9 +766,32 @@ String getFuchsiaBuildDirectory() {
 /// These values are URI-encoded and then combined into a comma-separated string.
 const String kDartDefines = 'DartDefines';
 
-/// Encode a List of dart defines in a URI string.
+final Converter<String, String> _defineEncoder = utf8.encoder.fuse(base64.encoder);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_info.dart:769]: This is the meat of the change

**Review by zanderso — APPROVED** [review]
lgtm w/ question: was it ever expected that the encoded defines would need to be human readable?

**Comment by jonahwilliams** [comment]
> lgtm w/ question: was it ever expected that the encoded defines would need to be human readable?

No, not in the current format. If we wanted to make an earnest attempt to support that, I think the proper way would be to allow providing a file path which contained the dart defines in a simple format (not yaml), and then having the tool read that.

**Comment by shinayser** [comment]
Guys, this feature caused a lot of problems on Flutter 2.2. Many reports going out in every forum I ook of people complaining about codes breaking and stoped working on Android. Myself included:
https://github.com/flutter/flutter/issues/82865

### This is breaking change and should be reported for people that are updating to Flutter 2.2

**Comment by jonahwilliams** [comment]
@shinayser the gradle (or xcode) API is not considered stable and may change arbitrarily between versions. The top level `flutter` command --dart-define API did not change for this release

**Comment by shinayser** [comment]
> @shinayser the gradle (or xcode) API is not considered stable and may change arbitrarily between versions. The top level `flutter` command --dart-define API did not change for this release

So what is the recommended way of using this api, since it can break at any time?

**Comment by jonahwilliams** [comment]
I guess I don't understand your usecase,  does `flutter build apk/appbundle/aar --dart-defines=..` not work for you?

**Comment by jonahwilliams** [comment]
What is the advantage of specifying this in build.gradle?

**Comment by shinayser** [comment]
We need one of the `dart-define` values coming from our CI and that key is required by the third-part library to be passed in the AndroidManifest.

**Comment by jonahwilliams** [comment]
I still don't really understand what specifying all of these defines in the build.gradle buys you though. Whatever automation you're using to get these values could handle the android manifest and the flutter build command separately

**Comment by shinayser** [comment]
We capture the keys of the Faster (the third-aprt library) in the build.gradle and add them to the manifestPlaceholders:

```
if (project.hasProperty('dart-defines')) {
	dartEnvironmentVariables = project.property('dart-defines')
			.split(',')
			.collectEntries { entry ->
				def byteArray = Base64.getDecoder().decode(entry)
				def decodedString = new String(byteArray)
				def pair = decodedString.split('=')
				[(pair.first()): pair.last()]
			}
}

   defaultConfig {
        manifestPlaceholders = [FASTER_APP_KEY_ANDROID: dartEnvironmentVariables.FASTER_APP_KEY_ANDROID,
                                FASTER_APP_SECRET_ANDROID: dartEnvironmentVariables.FASTER_APP_SECRET_ANDROID
        ]
    }
```

Then, we add them to the manifest:

```
  <meta-data
                android:name="com.movile.faster.sdk.application_key"
                android:value="${FASTER_APP_KEY_ANDROID}" />

        <meta-data
                android:name="com.movile.faster.sdk.application_secret"
                android:value="${FASTER_APP_SECRET_ANDROID}" />
```

I don't understand your suggestiong but we are very open to hear a better strategy you could share with us

**Comment by jonahwilliams** [comment]
So you are using `flutter` to build the app, but then you have some additional steps in gradle to grab some of the defines and  stick them elsewhere in your build?

**Comment by shinayser** [comment]
Exactly. The app is fully written in Flutter, but we have a plugin that needs those setups in the manifest.

**Comment by jonahwilliams** [comment]
what if we provided an easy way to pass project configuration through the gradle? You might have to specify the value twice, but then you'd have an exact project key and wouldn't need to parse anything from defines?

**Comment by shinayser** [comment]
Interesting and sounds good! Just curious about the "specify value twice". What you mean by that? Got any idea in mind?

**Comment by jonahwilliams** [comment]
suppose you had a key=value pair, and you wanted to use it both as a dart-define and in your build.gradle:

`flutter build apk --dart-define=key=value --gradle-project=key=value` (flag name TBD)

then in your build.gradle:

```
def valueINeed;

if (project.hasProperty('key')) {
	valueINeed = project. property('key').somethingAsStringIMAfkRightNow()
	...
```

**Comment by shinayser** [comment]
Humm... this would workd but I am afraid that this duplication can be bad if a project has multiple other defines. There isn't a way to accessing the dart-defines just like you proposed?

**Comment by jonahwilliams** [comment]
The defines are only available in the gradle project as a pass through, and need to be encoded to account for escaping issues. I guess we could move the encoding to the invocation of the flutter task? That would leave them as plain text in the project config.

**Comment by jonahwilliams** [comment]
TBH I don't really like that solution because it wouldn't match the other platforms. We're definitely not going to move the encoding to the xcode project file

**Comment by shinayser** [comment]
> TBH I don't really like that solution because it wouldn't match the other platforms. We're definitely not going to move the encoding to the xcode project file

Yes definetly. To be honest, the way it is workign right now is working fine, but the problem is the change caused apps to break by simply upgrading to flutter 2.2. A clearer documentation of this is enough since it is a more rare case.

**Comment by shinayser** [comment]
> For your specific use-case, I think you should consider the `--gradle-project` feature. Yes it would be bad for 1000s of defines, but if you only need one or two...

Sure, in my usecase it works fine. I am just wondering for other projects. And  just like you said, this could scale porly for multiple platforms. like:

```
flutter build apk --dart-define=key=value --gradle-project=key=value --windows-project=key=value --linux-project=key=value --raspberryPi=key=value, etc, etc, etc
```

**Comment by jonahwilliams** [comment]
OK, lets not worry about other projects that may or may not exist then 😄

**Comment by shinayser** [comment]
Sure thing! My point is just that we already have a "generic way" of passing the arguments to all the platforms, via `dart-defines`.  I personally prefer things the scale well vs others that do not.

**Comment by jonahwilliams** [comment]
But again, dart-defines is **not** a generic way to do this, its just a way to set environment constants in dart.

**Comment by shinayser** [comment]
Humm... you saying that the dart-defines can't be accessed directly on all the platforms?

**Comment by jonahwilliams** [comment]
are you having problems passing configuration on the other platforms, or just on android?

**Comment by shinayser** [comment]
Nope! Only Android for now.

**Comment by shinayser** [comment]
Like I said, I am very satisfied with the current way of accessing them. Just had this fflutter 2.2 problem that caused us some headache since yesterday to find the root of the problem xD

**Comment by jonahwilliams** [comment]
then I don't really understand what your concern is with the solution I presented above is. I'm interested in helping find a better solution here, but you need to understand that the way you are using them isn't really supported and may arbitrarily break in the future.

**Comment by shinayser** [comment]
My concern was just the scalability of the proposal. But you have more knowledge of this subject than me, so if you think it is the best soluttion then I am fine with it too.

**Comment by jonahwilliams** [comment]
implemented in https://github.com/flutter/flutter/pull/82941
