### PR TITLE
Fix excessive rebuilds of DSS

### LINKED ISSUE #67219: DraggableScrollableSheet is rebuilding the screen while dragging
## Steps to Reproduce

DraggableScrollableSheet is rebuilding the screen while dragging the sheet and it is causing unnecessary flickers.

```dart
class MyPopUpSheet extends StatelessWidget {
  ScrollController _scrollController; //Needed for

  @override
  Widget build(BuildContext context) {
    return Material(
      child: DraggableScrollableSheet(
        initialChildSize: 0.4,
        minChildSize: 0.4,
        builder: (ctx, scrollController) {
          
         print('Rebuilding...');

          return CustomScrollView(
            controller: scrollController,
            slivers: [
              SliverToBoxAdapter(child: Container(Colors.deepOrange)),
              SliverToBoxAdapter(child: Container(Colors.red)),
              SliverToBoxAdapter(child: Container(Colors.green)),
            ],
          );
        },
      ),
    );
  }

```

**Expected results:** 
It shouldn't rebuild the widget while dragging the sheet.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.20.4 at /Users/username/Library/Application Support/fvm/versions/1.20.4
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 
[✓] Connected device (1 available)            
    • ONEPLUS A6000 (mobile) • 431e5315 • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

cc/ @TahaTesser

### PR DESCRIPTION
**Pull request by dnfield**
## Description

DraggableScrollableSheet internally ends up calling the builder function every time the sheet scrolls - this is really unfortunate when, for example, it contains a sizable ListView that gets rebuilt every time the sheet slides up or down one pixel.

To resolve this, move the call of the builder function to `didChangeDependencies` so it's only called when our position in the tree changes, and reuse the cached child in `build`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/67219

## Tests

Assert that the builder is only called once when dependencies do not change and the sheet is dragged.

This is not a breaking change.

### CODE REVIEW

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [hunk 1]
```diff
@@ -309,4 +309,34 @@ void main() {
...
+                ),
+              );
+            },
+          ),
+        ],
+      ),
+    ));
+    expect(buildCount, 1);
+    await tester.flingFrom(const Offset(0, 325), const Offset(0, -325), 200);
+    expect(buildCount, 1);
```
Comment (dnfield) [inline packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:338]: Before this change, the buildCount was coming out to 48.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 2]
```diff
@@ -317,13 +323,13 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
       }
       _extent._currentExtent.value = _extent.initialExtent;
     }
+    _child = widget.builder(context, _scrollController);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: What if the DraggableScrollableSheet is given a new `builder` during its lifetime?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: Unrelated: Looks like changes to `minChildSize` and `maxChildSize` are also not respected, which seems like another bug?

**Comment by goderbauer** [comment]
Conceptually, could you have the DraggableScrollableSheet build an intermediate widget that takes the prebuild child widget. The intermediate widget then contains the layoutbuilder and the logic to frequently rebuild, but since it is configured with a prebuild child, the child wouldn't build again?

Something like:

```dart
class DraggableScrollableSheet extends StatelessWidget {
  DraggableScrollableSheet(
  // ...
  this.builder,
  );

  // ..
  Widget build(BuildCOntext context) {
    return _Intermediate(
      //..
      child: builder(context),
    );
  }
```

_Intermediate is basically what DraggableScrollableSheet is today with a child instead of a builder param.

Only difficulty: We'd have to move ownership of the scroll controller out of the _Intermediate widget to this new DraggableScrollableSheet since the builder needs it as argument. That doesn't seem impossible, though?

**Comment by dnfield** [comment]
Can't I just update the child in `didUpdateWidget` and it shoul dbe fine?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: I think I can address this with `didUpdateWidget` - will push something momentarily.

**Comment by dnfield** [comment]
@goderbauer added some tests that failed based on your suggestion, fixed them with didUpdateWidget - nice catch on the min/max/initial extent too. PTAL.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 3]
```diff
@@ -317,13 +323,28 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
...
+  }
+
+  @override
+  void didUpdateWidget(DraggableScrollableSheet oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    if (oldWidget.builder != widget.builder) {
+      _child = widget.builder(context, _scrollController);
+    }
+
+    _extent = _DraggableSheetExtent(
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:336]: This is cheap to create, so it seems silly to check the min/max/initial sizes for changes.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: In this case, that's too much - so I'm trying to cache the output of that builder to avoid rebuilding it whenever the sheet is dragged up or down.

This is simlar to how we don't rebuild every child sliver when a listview scrolls.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 4]
```diff
@@ -317,13 +323,28 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
       }
       _extent._currentExtent.value = _extent.initialExtent;
     }
+    _child = widget.builder(context, _scrollController);
+  }
+
+  @override
+  void didUpdateWidget(DraggableScrollableSheet oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    if (oldWidget.builder != widget.builder) {
```
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:332]: Done

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:336]: Fixed

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 5]
```diff
@@ -288,17 +288,17 @@ class _DraggableSheetExtent {
 class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
   late _DraggableScrollableSheetScrollController _scrollController;
   late _DraggableSheetExtent _extent;
+  // The child only gets rebuilt when dependencies change. Otherwise, excessive
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:291]: nit: comment is out of date, also rebuilds on didUpdateWidget.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 6]
```diff
@@ -317,13 +317,30 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
       }
       _extent._currentExtent.value = _extent.initialExtent;
     }
+    _child = widget.builder(context, _scrollController);
+  }
+
+  @override
+  void didUpdateWidget(DraggableScrollableSheet oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    _child = widget.builder(context, _scrollController);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: Maybe add a quick comment here reminding us in the future why we have to call this unconditionally (and not just when builder changes)?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 7]
```diff
@@ -317,13 +317,30 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
...
+    _updateExtent();
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:327]: I think `_updateExtent` has to run before we execute the builder since it instantiates a new scrollController that's used by the builder?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:331]: Is this still true even with us now creating a new _scrollController as well, which will cause other widgets to move their listeners over to the new one?

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:320]: Sounds good.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:291]: Updated

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:327]: Done.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:326]: Done.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:331]: I think it's probably still fine

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by TutOsirisOm** [comment]
@dnfield With this change I'm getting inconsistent behavior between builds of my app. It works perfectly when first implementing but after a hot restart or full rebuild it doesn't work and only seems to register the scroll controller for the content inside the sheet. If I change the widget tree by for example adding a container around the DSS then it will work again just once, and again stop being draggable after any restarts or refreshes.

**Comment by dnfield** [comment]
Hmm. We probably need something for reassemble.

**Comment by dnfield** [comment]
@TutOsirisOm - if you add something like this does it work:

```diff
diff --git a/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart b/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart
index 9303c98c78..68fa9608c7 100644
--- a/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart
+++ b/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart
@@ -330,6 +330,16 @@ class _DraggableScrollableSheetState extends State<DraggableScrollableSheet> {
     _child = widget.builder(context, _scrollController);
   }
 
+  @override
+  void reassemble() {
+    super.reassemble();
+    _updateExtent();
+    // Call this unconditionally - the closure may not change even though it
+    // refers to things outside of its identity, e.g. a tearoff from state that
+    // has an `if (stateVariable)`.
+    _child = widget.builder(context, _scrollController);
+  }
+
   void _updateExtent() {
     _extent = _DraggableSheetExtent(
       minExtent: widget.minChildSize,
```

**Comment by Hixie** [comment]
Calling it from reassemble itself is probably sketchy (reassemble is called before the build phase). Better to do something like set _child to null and have the build method call the builder if it's null (`??=`), that way you know the timing is going to be appropriate.

**Comment by dnfield** [comment]
There's something strange going on here still.

**Comment by TutOsirisOm** [comment]
I'm going to mess around with this today. Any progress been made in the meantime?

**Comment by dnfield** [comment]
I started looking Friday afternoon but didn't make a lot of progress.  I can look more tomorrow if you dont get to it first

**Comment by TutOsirisOm** [comment]
@dnfield Can we move `_updateExtent()` from `didUpdateWidget()`? I'm honestly not entirely sure what calling it there is supposed to do. At least in my use case removing it made everything seemingly work as intended. I also tried moving it into `didChangeDependencies()` above setting the `_child `with no issues, but again not sure what case exactly I should be testing for.

**Comment by TutOsirisOm** [comment]
Any progress on this? I haven't yet noticed anything not working after the changes I mentioned above.

**Comment by dnfield** [comment]
I haven't had a chance to get back to this yet. Sorry. I may be able to today, but I have a couple other higher priority items to make progress on first.

**Comment by dnfield** [comment]
It is unlikely that I will be able to get to this. If we need to revert this change until we can fix this I think that's fine.

**Comment by dnfield** [comment]
Unlikely to get to it in the next two weeks I mean :)

**Comment by TutOsirisOm** [comment]
That's fine, in the meantime I'll look into it some more but as is the changes I made earlier are working as intended for me. :)

**Comment by gabrieldelorean** [comment]
Any progress on this?

**Comment by dnfield** [comment]
I have not had time to look at this again and am not sure when I'll get back to it. 

I still suspect something like this fix can work, but it needs to address hot restart issues as well as something wrong with how the scroll controller was or wasn't getting recreated.

**Comment by shubhamgupta71** [comment]
is this being worked on?
