### PR TITLE
Fix prepare package

### LINKED ISSUE #76894: Regression in pre-built SDK archives where pre-built cache is not present in prepackaged archives
Sometime between [2020-11-19](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Flutter%20Beta%20Packaging/32) and [2020-12-02](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Flutter%20Dev%20Packaging/112), Flutter's pre-built packages lost the pre-built cache in `//flutter/bin/cache`.

The command in question is `git clean -f -X **/.packages`. Compare the logs between https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863191936157903472/+/steps/prepare__create_and_publish_a_flutter_archive/0/stdout and https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8862007531499549568/+/steps/prepare__create_and_publish_a_flutter_archive/0/stdout

### PR DESCRIPTION
**Pull request by christopherfujino**
Fix bug where we were inadvertently deleting the entire `bin/cache` directory because two files contained in it matched the `git clean` file glob:

```
./bin/cache/dart-sdk/bin/resources/dartdoc/.packages
./bin/cache/dart-sdk/lib/_internal/js_runtime/.packages
```

fixes https://github.com/flutter/flutter/issues/76894

### CODE REVIEW

File: dev/bots/test/prepare_package_test.dart [hunk 1]
```diff
@@ -120,8 +120,8 @@ void main() {
           '$flutter create --template=app ${createBase}app': null,
           '$flutter create --template=package ${createBase}package': null,
           '$flutter create --template=plugin ${createBase}plugin': null,
-          'git clean -f -X **/.packages': null,
-          'git clean -f -X **/.dart_tool': null,
+          'git clean -f -x **/.packages': null,
+          'git clean -f -x **/.dart_tool': null,
```
Comment (gspencergoog) [inline dev/bots/test/prepare_package_test.dart:124]: I checked this locally, it appears that `-x` will not delete directories, even if you specify `-d` in addition, and adding `-X` in again will again delete the cache.

Comment (christopherfujino) [reply dev/bots/test/prepare_package_test.dart:124]: `¯\_(ツ)_/¯`

Comment (gspencergoog) [reply dev/bots/test/prepare_package_test.dart:124]: Ahh.  Try this instead:

```suggestion
          'git clean -f -x **/.dart_tool/': null,
```

File: dev/bots/prepare_package.dart [hunk 2]
```diff
@@ -370,9 +370,22 @@ class ArchiveCreator {
...
+      '**/.packages',
+    ]);
     /// Remove package_config files and any contents in .dart_tool
-    await _runGit(<String>['clean', '-f', '-X', '**/.dart_tool']);
+    await _runGit(<String>['clean', '-f', '-x', '**/.dart_tool']);
+
+    // Ensure the above commands do not clean out the cache
+    final Directory flutterCache = Directory(path.join(flutterRoot.absolute.path, 'bin', 'cache'));
+    if (!flutterCache.existsSync()) {
+      throw Exception('The flutter was not found at ${flutterCache.path}!');
```
Comment (jmagman) [inline dev/bots/prepare_package.dart:386]:
```suggestion
      throw Exception('The flutter cache was not found at ${flutterCache.path}!');
```

**Review by jmagman — APPROVED** [review]
LGTM with nit

File: dev/bots/test/prepare_package_test.dart (hunk 1 above)
Comment (gspencergoog) [reply dev/bots/test/prepare_package_test.dart:124]: Without the trailing "/" on the path, it doesn't look for directories.

Comment (jmagman) [reply dev/bots/test/prepare_package_test.dart:124]: Just `-x` worked on my machine:
```
$ git --version
git version 2.30.1.766.gb4fecdf3b7-goog
$ git clean -f -x **/.dart_tool             
Removing dev/automated_tests/.dart_tool/
Removing dev/benchmarks/complex_layout/.dart_tool/
...
```
and it did delete those directories.

File: dev/bots/prepare_package.dart (hunk 2 above)
Comment (christopherfujino) [reply dev/bots/prepare_package.dart:386]: done

File: dev/bots/test/prepare_package_test.dart (hunk 1 above)
Comment (gspencergoog) [reply dev/bots/test/prepare_package_test.dart:124]: Huh.  Was that on macOS or Linux?

I have `git version 2.30.1.766.gb4fecdf3b7-goog` too.

Comment (gspencergoog) [reply dev/bots/test/prepare_package_test.dart:124]: Because I get this.  Could be a platform difference.
```
$ git clean -n -x **/.dart_tool
$ git clean -n -x **/.dart_tool/
Would remove packages/flutter_tools/.dart_tool/
$ 
```

Comment (christopherfujino) [reply dev/bots/test/prepare_package_test.dart:124]: ahh sorry, I missed that this comment was about the `**/.dart_tool` line.

Comment (christopherfujino) [reply dev/bots/test/prepare_package_test.dart:124]: on linux i can confirm that `git clean -f -x **/.dart_tool` doesn't work, and `git clean -f -x -- **/.dart_tool/` DOES work.

Comment (christopherfujino) [reply dev/bots/test/prepare_package_test.dart]: updated with the slash at the end
