### PR TITLE
Hide InkWell hover highlight when an hovered InkWell is disabled

### LINKED ISSUE #117733: Inactive (onTap: null) ListTile keeps hover state until mouse out
https://user-images.githubusercontent.com/6051015/209817347-5831c484-56aa-4f5a-bdfd-cce2e86f7539.mov

## Steps to Reproduce
(I tried in web)
1. Execute `flutter run` on the code sample
2. Click on unselected item (and keep mouse cursor on it)

**Expected results:**
The ListTile immediately becomes inactive. Without any hover state and with its default background.

**Actual results:** 
The ListTile keeps some kind of hover state (with different background color) until mouse cursor leaves it.

By the way, mouse cursor type depends on active/inactive state of the ListTile and switches correctly.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: ['Title 1', 'Title 2']
              .asMap()
              .entries
              .map((entry) => ListTile(
                    title: Text(entry.value),
                    subtitle: Text(
                        entry.key == selectedIndex ? 'is selected' : 'sub'),
                    onTap: entry.key == selectedIndex
                        ? null
                        : () {
                            setState(() {
                              selectedIndex = entry.key;
                            });
                          },
                  ))
              .toList(),
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

When an `InkWell` is hovered and enabled, it shows an hover highlight.

**Before this PR:**
If the `InkWell` is disabled while being hovered, the hover highlight is displayed until the mouse exit.

**After this PR:**
If the `InkWell` is disabled while being hovered, the hover highlight is hidden.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/117733

## Implementation details

Removing the highlight as soon as the `InkWell` is disabled is not possible because it leads to `onHover` callback not being called at all or being call when it is not allowed (`onHover` callback often apply `setState`).

## Tests

Adds 1 test.
Updates 1 existing test.

### CODE REVIEW

File: packages/flutter/lib/src/material/ink_well.dart [hunk 1]
```diff
@@ -857,6 +857,15 @@ class _InkResponseState extends State<_InkResponseStateWidget>
       statesController.update(MaterialState.disabled, !enabled);
       if (!enabled) {
         statesController.update(MaterialState.pressed, false);
+        // Remove the existing hover highlight immediately when enabled is false.
+        // Do not rely on updateHighlight or InkHighlight.deactivate to not break
+        // the expected lifecycle which is updating _hovering when the mouse exit.
+        // Manually updating _hovering here or calling InkHighlight.deactivate
+        // will lead to onHover not being called or call when it is not allowed.
+        final InkHighlight? hoverHighLight = _highlights[_HighlightType.hover];
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_well.dart:865]:
```suggestion
        final InkHighlight? hoverHighlight = _highlights[_HighlightType.hover];
```
Since highlight is just one word.

File: packages/flutter/lib/src/material/ink_well.dart [hunk 2]
```diff
@@ -857,6 +857,15 @@ class _InkResponseState extends State<_InkResponseStateWidget>
...
+        if (hoverHighLight != null) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_well.dart:866]: This could be `hoverHighlight?.dispose()`

File: packages/flutter/lib/src/material/ink_well.dart [hunk 3]
```diff
@@ -857,6 +857,15 @@ class _InkResponseState extends State<_InkResponseStateWidget>
...
+          hoverHighLight.dispose();
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/ink_well.dart:867]: Are we potentially leaving a disposed InkHighlight in the _highlights table? When does this entry get safely cleared?

**Review by HansMuller — COMMENTED** [review]
The highlight management code in ink_well.dart is difficult to follow (as I'm sure you know). AFAICT something's not quite right here, however I could very well be misunderstanding the change.

**Comment by bleroux** [comment]
> The highlight management code in ink_well.dart is difficult to follow (as I'm sure you know). AFAICT something's not quite right here, however I could very well be misunderstanding the change.


Yes, highlights lifecycle is somewhat complex. We, Taha and I, spent some time discussing this during our internal review process. Simply calling `hoverHighlight.deactivate` would have been great but it’s not possible (existing tests were very helpful to understand why, but it is not straightforward to figure out, that’s why I added a long comment).

Part of the existing complexity is related to `dispose()` calling the `onRemoved` callback.
As you commented below, after calling `hoverHighlight.dispose()`, it seems that we are potentially leaving a disposed `InkHighlight` in the _highlights table but that’s not the case due to the `onRemoved` callback set to the following `handleInkRemove` inner function which takes care of removing the Highlight from the table : https://github.com/flutter/flutter/blob/7ddf42eae5ee9b9d770ce40aae362b0fc2ca1005/packages/flutter/lib/src/material/ink_well.dart#L889-L896  

This fix could be summarized as removing the current hover highlight and creating a new one with a transparent color. It feels somewhat hacky. I didn’t find another solution due to the hover highlight lifecycle expectations (`onHover` callback should be called when removing the highlight but can’t be called anywhere because `onHover` callbacks often call `setState`).

Going deeper on InkWell code was very interesting but I don’t have a strong opinion on merging or canceling this PR.

**Comment by HansMuller** [comment]
I'm going to LGTM this PR, because it fixes the corner case demonstrated in https://github.com/flutter/flutter/issues/117733, and it's not the only place where we've used Colors.transparent to cover up a deeper problem. 

If you and Taha wanted to propose a rewrite of InkWell et al., one that simplified the implementation without breaking anything, I'd be happy to review that.

**Review by HansMuller — APPROVED** [review]
LGTM
