### PR TITLE
Fixed issue with Hero Animations and BoxScrollViews in Scaffolds

### LINKED ISSUE #99084: Wrong positioning of `GridView` in Hero animations
## Steps to Reproduce
1. Run the below modified version of [the official `Hero` docs](https://docs.flutter.dev/cookbook/navigation/hero-animations#interactive-example).
1. Tap on the images to toggle/navigate between the two screens.

**Expected results:**
The `GridView` widget should smoothly animate from one screen to the other.

**Actual results:**
When animated, the `GridView` is incorrectly positioned on the screen, resulting in a visible jump right before the Hero animation finishes. (The bug is more visible when navigating to `MainScreen`, but it exists in both directions.)

## Code & Logs
<details>
<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const HeroApp());

class HeroApp extends StatelessWidget {
  const HeroApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Transition Demo',
      home: MainScreen(),
    );
  }
}

class MainScreen extends StatelessWidget {
  const MainScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Main Screen')),
      body: GestureDetector(
        onTap: () => Navigator.of(context).push(
          MaterialPageRoute(builder: (_) => const DetailScreen()),
        ),
        child: Hero(
          tag: 'imageHero',
          child: GridView.count(
            crossAxisCount: 3,
            shrinkWrap: true,
            children: [
              Image.network('https://picsum.photos/250?image=9'),
              Image.network('https://picsum.photos/250?image=9'),
            ],
          ),
        ),
      ),
    );
  }
}

class DetailScreen extends StatelessWidget {
  const DetailScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onTap: () => Navigator.pop(context),
        child: Hero(
          tag: 'imageHero',
          child: GridView.count(
            crossAxisCount: 3,
            shrinkWrap: true,
            children: [
              Image.network('https://picsum.photos/250?image=9'),
              Image.network('https://picsum.photos/250?image=9'),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
</details>

### PR DESCRIPTION
**Pull request by youssef-attia**
Fixed an issue where a jump would happen with Hero animations on mobile when the Hero child was a BoxScrollView and the destination page had a Scaffold with different layout (difference in AppBar, etc).

#99084
Before:
https://user-images.githubusercontent.com/16466991/172736468-d81b7e5a-8bb7-4627-bac6-2632b1e89a74.mov

After:
https://user-images.githubusercontent.com/16466991/172736486-93f08372-e8a0-4d12-b8a1-06ee791cc015.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 1]
```diff
@@ -137,7 +137,10 @@ enum HeroFlightDirection {
 /// is, by default, used to do the transition: when going from route A to route
 /// B, route B's hero's widget is placed over route A's hero's widget. If a
 /// [flightShuttleBuilder] is supplied, its output widget is shown during the
-/// flight transition instead.
+/// flight transition instead. If overriding [flightShuttleBuilder] leads to
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart:140]: Since you've added the transition of `MediaQuery`, is this new comment still needed?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 2]
```diff
@@ -998,7 +1001,32 @@ class HeroController extends NavigatorObserver {
     BuildContext toHeroContext,
   ) {
     final Hero toHero = toHeroContext.widget as Hero;
-    return toHero.child;
+    if (MediaQuery.maybeOf(toHeroContext) == null && MediaQuery.maybeOf(fromHeroContext) == null) {
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart:1004]: I understand that `MediaQueryData.padding` is the cause for the issue that this PR's fixing. But it feels a little too "particular" to me. Can there be other "contextual" state like `MediaQuery.padding` that needs this kind of transition? Is `MediaQueryData.padding` the special one?

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 1 above)
Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart:140]: This comment is because I added the transition for the default flightShuttleBuilder but the developer can override the shuttleBuilder so it may be important to let them know that they will need the same behavior in their version of the method if they are having the same issue.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart:1004]: I agree that it feels particular and was thinking of doing what you suggested but it seems that padding is the only attribute with reported issues on this behavior since there are many Layout elements that rely on padding but may have different padding values based on the MediaQuery of the context. I was going to try to make a transition between the MediaQueryData as a whole but there's no way to lerp between two whole MediaQueryData objects (maybe this behavior can be added in MediaQuery?). Otherwise, the addition is not very costly but fixes many issues that could arise similar to the original issue so it is worth adding. But if you have any further suggestions please let me know.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 3]
```diff
@@ -137,7 +137,10 @@ enum HeroFlightDirection {
 /// is, by default, used to do the transition: when going from route A to route
 /// B, route B's hero's widget is placed over route A's hero's widget. If a
 /// [flightShuttleBuilder] is supplied, its output widget is shown during the
-/// flight transition instead.
+/// flight transition instead. If overriding [flightShuttleBuilder] leads to
+/// gaps or jumps arising in the animation, try interpolating between
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/heroes.dart:141]: There could be other [InheritedWidget](https://master-api.flutter.dev/flutter/widgets/InheritedWidget-class.html)s (including custom/3rd party ones) other than `MediaQuery` that may cause contents in the `Hero` to have unexpected padding/changes appearance during the Hero animation. Instead of directly suggesting `MediaQuery` is the culprit I think adding a hint so that  developer are aware of the general problem with `InheritedWidget`s in a `Hero`, and maybe use MediaQuery as an example would be a bit more helpful.

maybe something along the lines of (rephrase as you see fit):

The flightShuttleBulder tree uses [InheritedWidget]s from the route the Hero animation starts from (I don't remember if this statement is true, could be the to route?)
If the widget tree in flightShuttleBuilder changes its geometry/appearance based on [InheritedWidget]s that's above the Hero widget tree, for example if both routes provide `MediaQuery` but with different paddings, you may see jumps/gaps. If you experience the problem, wrap the current flightShuttleBulder in a such inherited widget (and potentially interpolate the value provided by the inherited widget using the `animation` parameter. The default flightShuttleBulder is wrapped in a MediaQuery widget if only one navigator has padding or both navigator's `MediaQuery`s provide different paddings. 

Also you may want to add docs to [flightShuttleBulder] itself too.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 4]
```diff
@@ -998,7 +1001,32 @@ class HeroController extends NavigatorObserver {
...
-    return toHero.child;
+    if (MediaQuery.maybeOf(toHeroContext) == null && MediaQuery.maybeOf(fromHeroContext) == null) {
+      return toHero.child;
+    }
+    final MediaQueryData chosenMediaQueryData = MediaQuery.maybeOf(toHeroContext) ?? MediaQuery.of(fromHeroContext);
+
+    final EdgeInsets fromHeroPadding = MediaQuery.maybeOf(fromHeroContext)?.padding?? EdgeInsets.zero;
+    final EdgeInsets toHeroPadding = MediaQuery.maybeOf(toHeroContext)?.padding?? EdgeInsets.zero;
+
+
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/heroes.dart:1012]: nit: extraneous line here

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 5]
```diff
@@ -998,7 +1001,32 @@ class HeroController extends NavigatorObserver {
...
+    return AnimatedBuilder(
+        animation: animation,
+        builder: (BuildContext context, Widget? child) {
+          return MediaQuery(
+              data: chosenMediaQueryData.copyWith(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/heroes.dart:1017]: nit: indentation.

**Review by LongCatIsLooong — COMMENTED** [review]
This pull request needs tests.  See https://github.com/flutter/flutter/wiki/Tree-hygiene#tldr

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/heroes.dart:1004]: Unfortunately I don't think we'll be able to cover everything since people can introduce their own InheritedWidgets. Developers will have to provide their own flightShuttleBuilder implementation if a non-framework InheritedWidget is causing jumpy animation. According to https://master-api.flutter.dev/flutter/widgets/MediaQueryData-class.html there're a few other things other than padding that can cause problem but difference in padding seems to be the most common issue.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 6]
```diff
@@ -998,7 +1001,32 @@ class HeroController extends NavigatorObserver {
     BuildContext toHeroContext,
   ) {
     final Hero toHero = toHeroContext.widget as Hero;
-    return toHero.child;
+    if (MediaQuery.maybeOf(toHeroContext) == null && MediaQuery.maybeOf(fromHeroContext) == null) {
+      return toHero.child;
+    }
+    final MediaQueryData chosenMediaQueryData = MediaQuery.maybeOf(toHeroContext) ?? MediaQuery.of(fromHeroContext);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/heroes.dart:1007]: If `MediaQuery.maybeOf(toHeroContext)` is null then I feel we don't want to fallback to `MediaQuery.of(fromHeroContext)`?

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/heroes.dart:1004]: I'm leaning towards only doing this when both `MediaQuery` are not null. In theory there could be cases where the Hero subtree has a hard dependency on MediaQuery and should throw when there's no MediaQuery present in the tree. Adding a `MediaQuery` in this case would prevent the developer from getting the error.

In a real app you'll always have a `MediaQuery` if you use `WidgetsApp` so it doesn't really matter. But that could make the interpolation logic slightly easier to write.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 1 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart:140]: I think this line is better added to the documentation of `flightShuttleBuilder`, since it's only for people who overrides it. It might be even better to have an example app for it too (but that's beyond the scope of this PR.)

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 3 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart:141]: @LongCatIsLooong 's change make it much clearer. Although as I said, I think this is better moved to the doc of `flightShuttleBulder`. 

For the last sentence: "The default flightShuttleBulder is wrapped in a MediaQuery widget if only both navigators' MediaQuerys provide different paddings. " should be enough.

Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart:141]: Ok, if I understand https://github.com/flutter/flutter/pull/105654/files#r893811742 correctly, the jump will occur if the source tree and the target tree uses different custom `InheritedWidget` settings even without `flightShuttleBulder`. So I suggest (instead of moving) changing the doc starting " If a [flightShuttleBuilder] is supplied...“ into the follows:

However, if the hero uses information from `InheritedWidget`s, and the inherited data are different between the starting tree and the target tree, there will be an ugly jumping animation unless that data is properly interpolated. By default, `Hero` interpolates `MediaQuery`'s paddings. If your hero uses custom `InheritedWidget`s that see jumping animation, try to provide custom in-flight transition using `flightShuttleBuilder`.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart:1004]: I see.

I'm watching the video tutorial of `padding` and `viewPadding`. It seems that `padding.bottom` drops to 0 when a keyboard is raised. How does that affect our interpolation here? Can you try a `Hero` placed at the bottom of the screen and see what happens when the keyboard is raised?

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 6 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart:1007]: Yeah maybe we just don't do transition at all?

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart]: I agree. Defaulting empty `MediaQueryData` to the other can lead to confusing result.

Imagine there are 3 trees, A, B, and C. A and C has non-empty `MediaQueryData`, while B has none. A hero X flies from A to B, then from B to C. During the first flight, it uses a fixed padding from A, while during the second flight, it uses a fixed padding from C. This is a jumping animation. 

We might want to either default empty paddings to zero, or assert this situation.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 7]
```diff
@@ -139,6 +140,17 @@ enum HeroFlightDirection {
 /// [flightShuttleBuilder] is supplied, its output widget is shown during the
 /// flight transition instead.
 ///
+/// The flightShuttleBulder tree uses [InheritedWidget]s from the route the Hero
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart:143]:
```suggestion
/// The flightShuttleBuilder tree uses [InheritedWidget]s from the route the Hero
```

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 8]
```diff
@@ -208,6 +220,18 @@ class Hero extends StatefulWidget {
 
   /// Optional override to supply a widget that's shown during the hero's flight.
   ///
+  /// If overriding note the flightShuttleBulder tree uses [InheritedWidget]s
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart:223]: To reuse long documentations, you can use `@template` and `@macro`.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 9]
```diff
@@ -139,6 +140,17 @@ enum HeroFlightDirection {
 /// [flightShuttleBuilder] is supplied, its output widget is shown during the
 /// flight transition instead.
 ///
+/// The flightShuttleBulder tree uses [InheritedWidget]s from the route the Hero
+/// animation starts from. If the widget tree in [flightShuttleBuilder] changes
+/// its geometry/appearance based on [InheritedWidget]s that are above the Hero
+/// widget tree, for example if both routes provide [MediaQuery] but with
+/// different paddings, you may see jumps/gaps. If you experience this problem,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart]: We've solved this problem in this PR, right? Probably use another example, such as:

for example, if there's a custom `InheritedWidget` that provides a theme color and is uses within the hero widget,

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 6 above)
Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart]: Yes, I think skipping the transition when either MediaQuery is null might be the way to go.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 9 above)
Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart]: Yes, I've decided to switch the documentation strategy to what you suggested above.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart]: I believe just not doing a transition if either MediaQuery is wrong fixes the possibility of this issue, though correct me if I'm wrong.

[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/heroes.dart]: I'm leaning to asserting it. Reason:
- This is rare. The hero is transitioning from within a MediaQuery to out of it. The developer is doing something advanced but is doing it wrong, and it might be better to tell them.
- If we don't do transitions at all, this almost certainly leads to a jumping animation, which is another issue to be raised, investigated, and fixed in the future.

Comment (youssef-attia) [reply packages/flutter/lib/src/widgets/heroes.dart]: I tried adding a hero to the bottom of the page and the keyboard being raised does not cause an error with the interpolation. Since the padding.bottom drops to 0, the transition just interpolates between 0 and 0. Either combination of padding changes would not cause the transition to fail since the interpolation analyzes both MediaQuerys. Correct me if I'm wrong though.

**Review by LongCatIsLooong — COMMENTED** [review]
The code LGTM. I feel the documentation could be a bit more specific about what kind of inherited widgets developers should pay attention to.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 10]
```diff
@@ -135,9 +136,15 @@ enum HeroFlightDirection {
...
 /// hero in both locations be essentially identical. The widget of the *target*
 /// is, by default, used to do the transition: when going from route A to route
-/// B, route B's hero's widget is placed over route A's hero's widget. If a
-/// [flightShuttleBuilder] is supplied, its output widget is shown during the
-/// flight transition instead.
+/// B, route B's hero's widget is placed over route A's hero's widget. Additionally,
+/// if the [Hero] subtree changes appearance based on an [InheritedWidget] (such
+/// as [MediaQuery] or [Theme]), then the hero animation may have discontinuity
+/// at the start or the end of the animation because route A and route B provides
+/// different such [InheritedWidget]s. Consider providing a custom [flightShuttleBuilder]
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/heroes.dart:143]: Is this `Consider providing a custom [flightShuttleBuilder] to ensure smooth transitions" redundant?

**Review by dkwingsmt — APPROVED** [review]
