### PR TITLE
Tab labels incorrectly fade out

### LINKED ISSUE #4365: Tab labels are fading out, as if an ellipsis was present
The screenshot below is from the gallery Tabs demo. Paging through all of the tabs makes the problem go away.

tab_label

### PR DESCRIPTION
**Pull request by abarth**
Assigning to `size` called our intrinsic sizing functions re-entrantly, which
is a destructive operation on TextPainter. Ideally we'd made that a
non-destructive operation, but in the meantime we can fix the tab fading issue
by grabbing the text size before assigning to `size`.

Fixes #4365

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -148,15 +148,19 @@ class RenderParagraph extends RenderBox {
   @override
   void performLayout() {
     _layoutText(minWidth: constraints.minWidth, maxWidth: constraints.maxWidth);
-    size = constraints.constrain(_textPainter.size);
+    // We grab _textPainter.size here because assigning to `size` will trigger
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/paragraph.dart]: hmm, this is a problem. Can you file a bug on me to take a closer look at this?

Comment (abarth) [inline packages/flutter/lib/src/rendering/paragraph.dart]: Filed https://github.com/flutter/flutter/issues/4413
