### PR TITLE
Fix `NestedScrollView` inner position logic

### LINKED ISSUE #40740: NestedScrollView's use of PrimaryScrollController breaks when there are multiple inner ScrollPositions
Other instances of these issues we have seen reported:

- #62833
- #81619 
- #21868 
- #36419

----

Hello guys,
I wrote a very basic app that has a SliverAppBar and 3 tabs wrapped inside NestedScrollView.
Whenever I scrolling the list up and the app bar showing, all other scroll position is reset.

here's my code:
```Dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: NewsScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class NewsScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _NewsScreenState();
}

class _NewsScreenState extends State<NewsScreen> {
  final List<String> _tabs = <String>[
    "Featured",
    "Popular",
    "Latest",
  ];

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        body: DefaultTabController(
          length: _tabs.length,
          child: NestedScrollView(
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                SliverOverlapAbsorber(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  child: SliverSafeArea(
                    top: false,
                    bottom: Platform.isIOS ? false : true,
                    sliver: SliverAppBar(
                      title: Text('Tab Demo'),
                      floating: true,
                      pinned: true,
                      snap: true,
                      forceElevated: innerBoxIsScrolled,
                      bottom: TabBar(
                        tabs: _tabs
                            .map((String name) => Tab(text: name))
                            .toList(),
                      ),
                    ),
                  ),
                ),
              ];
            },
            body: TabBarView(
              children: _tabs.map((String name) {
                return SafeArea(
                  top: false,
                  bottom: false,
                  child: Builder(
                    builder: (BuildContext context) {
                      return NotificationListener<ScrollNotification>(
                        onNotification: (scrollNotification) {
                          return true;
                        },
                        child: CustomScrollView(
                          key: PageStorageKey<String>(name),
                          slivers: <Widget>[
                            SliverOverlapInjector(
                              handle: NestedScrollView
                                  .sliverOverlapAbsorberHandleFor(context),
                            ),
                            SliverPadding(
                              padding: const EdgeInsets.all(8.0),
                              sliver: SliverList(
                                delegate: SliverChildBuilderDelegate(
                                  (BuildContext context, int index) {
                                    return Column(
                                      children: <Widget>[
                                        Container(
                                          height: 150,
                                          width: double.infinity,
                                          color: Colors.blueGrey,
                                          child: Column(
                                            mainAxisAlignment:
                                                MainAxisAlignment.center,
                                            children: <Widget>[
                                              Text('$name $index')
                                            ],
                                          ),
                                        ),
                                        SizedBox(
                                          height: 8,
                                        )
                                      ],
                                    );
                                  },
                                  childCount: 30,
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
}
```

## Steps to Reproduce

- Featured -> Scroll down to 5 -> Change Tab Popular -> Scroll down to 7 -> Change Tab Latest -> Scroll up until app bar shown -> Change to other Tab. (*on both ios/android)

screenshot

- Featured -> Scroll down to 5 -> Change Tab Popular -> Scroll down to 7 -> Change Tab Latest -> Scroll down to 7 -> Change back to Tab Featured Scroll up to 4 -> Change to other Tab. (*on android only)

screenshot

*above will reset the scroll position of all tab bar view to 0

```
Analyzing cwbflutter...
No issues found! (ran in 4.8s)
```

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-MY)
    • Flutter version 1.9.1+hotfix.2 at C:\Users\LENOVO-Workstation\flutter
    • Framework revision 2d2a1ffec9 (11 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\LENOVO-Workstation\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\LENOVO-Workstation\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\LENOVO-Workstation\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by nate-thegrate**
closes #40740

<p align="center">
  NestedScrollController fix
</p>

<details> <summary><h4>Demo source code</h4> (click to expand)</summary>

(this is a slightly more concise version of the code sample from #40740)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(body: NewsScreen()),
    ),
  );
}

class NewsScreen extends StatelessWidget {
  const NewsScreen({super.key});

  static const List<String> _tabs = <String>['Featured', 'Popular', 'Latest'];

  static final List<Widget> _tabViews = <Widget>[
    for (final String name in _tabs)
      SafeArea(
        top: false,
        bottom: false,
        child: Builder(builder: (BuildContext context) {
          final handle = NestedScrollView.sliverOverlapAbsorberHandleFor(context);

          return NotificationListener<ScrollNotification>(
            onNotification: (ScrollNotification notification) => true,
            child: CustomScrollView(
              key: PageStorageKey<String>(name),
              slivers: <Widget>[
                SliverOverlapInjector(handle: handle),
                SliverPadding(
                  padding: const EdgeInsets.all(8.0),
                  sliver: SliverList(
                    delegate: SliverChildBuilderDelegate(
                      childCount: 30,
                      (BuildContext context, int index) => Container(
                        margin: const EdgeInsets.only(bottom: 8),
                        width: double.infinity,
                        height: 150,
                        color: const Color(0xFFB0A4C8),
                        alignment: Alignment.center,
                        child: Text(
                          '$name $index',
                          style: const TextStyle(fontWeight: FontWeight.w600),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        }),
      ),
  ];

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) => <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: SliverSafeArea(
              top: false,
              sliver: SliverAppBar(
                title: const Text('Tab Demo'),
                floating: true,
                pinned: true,
                snap: true,
                forceElevated: innerBoxIsScrolled,
                bottom: TabBar(
                  tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                ),
              ),
            ),
          ),
        ],
        body: TabBarView(children: _tabViews),
      ),
    );
  }
}
```

<br>

</details>

<br>

This bug can be traced to a return statement inside `_NestedScrollPosition`:

```dart
double applyClampedDragUpdate(double delta) {
  // ...
  return delta + offset;
}
```

Thanks to some quirks of floating-point arithmetic, `applyClampedDragUpdate` would sometimes return a tiny non-zero value, which ends up ruining one of the scroll coordinator's equality checks.

https://github.com/flutter/flutter/blob/8990ed6538592fc8aee63b0e137b7b52804a030f/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L658-L664

### CODE REVIEW

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 1]
```diff
@@ -1320,7 +1320,12 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
       forcePixels(actualNewPixels);
       didUpdateScrollPositionBy(offset);
     }
-    return delta + offset;
+
+    final double result = delta + offset;
+    if (result > -0.000001 && result < 0.000001) {
```
Comment (bleroux) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1325]: Not sure if it can be used here, maybe you can rely on `precisionErrorTolerance`:

```suggestion
    if (result.abs() < precisionErrorTolerance) {
```

Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1325]: I was hoping there was something like `precisionErrorTolerance`, thank you!

**Review by bleroux — APPROVED** [review]
LGTM! I'm not a scrolling expert, so up to you to seek another reviewer.

File: examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart [hunk 2]
```diff
@@ -41,4 +41,46 @@ void main() {
       lessThan(initialAppBarHeight),
     );
   });
+
+  testWidgets('Maintains scroll position of inactive tab', (WidgetTester tester) async {
```
Comment (victorsanni) [inline examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: I'm wondering why there is a test in examples and not one in lib/src? Imagining an unlikely future where someone throws out examples and the associated tests (because who cares about meagre examples anyways), couldn't this change be regressed?

Comment (nate-thegrate) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: I added the test here so that I could use `NestedScrollViewExampleApp()` instead of configuring the huge widget tree.

But this is a good point—and I think it'd be easy to just import the example to the lib/src test file. I'll go ahead and do that, thanks!

Comment (nate-thegrate) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: …well dang, it looks like importing an example into a flutter/test library currently isn't possible.

Moving the test wouldn't guarantee a lack of regressions; for example, https://github.com/flutter/flutter/pull/50831 changed a test's expected output, and then https://github.com/flutter/flutter/pull/149819 attempted to change it back.

Overall, I'm not sure exactly how relocating the test would affect the probability of regressions. It's not something I'm super worried about, though I'd be open to hearing other perspectives.

Comment (victorsanni) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: Isn't there a way to reproduce the bug in flutter/test directly? i.e strip the example down to the essentials causing the bug.

Comment (nate-thegrate) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: Yes, though it wouldn't be stripped down by much.

Comment (victorsanni) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: My suggestion in that case would be to configure the large widget tree in flutter/test, unfortunately. Just so that in the event that examples/ and packages/flutter are someday separated, the change isn't untested in packages/flutter. If that's not possible I wonder if there are any precedents, would also like to hear what others think.

Comment (victorsanni) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: Although I haven't looked into this example too deeply so maybe I am missing some important context.

Comment (nate-thegrate) [reply examples/api/test/widgets/nested_scroll_view/nested_scroll_view.0_test.dart:45]: > My suggestion in that case would be to configure the large widget tree in flutter/test, unfortunately. Just so that in the event that examples/ and packages/flutter are someday separated, the change isn't untested in packages/flutter.

Sounds good.

I really appreciate the feedback, have a great Halloween! 👻

**Comment by festelo** [comment]
Hey, I tried to run the example (with some modifications for easier testing on Windows) and noticed that the scroll position resets when scrolling up, is this expected?

ezgif-4-2f4e706114

Text version of the gif:
* Scroll to "Featured 11" (with finger or mouse wheel)
* Switch tab to "Popular"
* Scroll to "Popular 6"
* Switch tab to "Featured"
* Switch tab to "Popular"
* Scroll up to "Popular 4", _so the sliver app bar expands_
* Switch tab to "Popular"
* Scroll position is 0

<details>
  <summary>Code</summary>
```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        physics: const ClampingScrollPhysics(),
        scrollbars: false,
        dragDevices: {
          PointerDeviceKind.mouse,
          PointerDeviceKind.touch,
          PointerDeviceKind.stylus,
          PointerDeviceKind.unknown
        },
      ),
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: NewsScreen(),
      ),
    ),
  );
}

class NewsScreen extends StatelessWidget {
  const NewsScreen({super.key});

  static const List<String> _tabs = <String>['Featured', 'Popular', 'Latest'];

  static final List<Widget> _tabViews = <Widget>[
    for (final String name in _tabs)
      SafeArea(
        top: false,
        bottom: false,
        child: Builder(builder: (BuildContext context) {
          final handle =
              NestedScrollView.sliverOverlapAbsorberHandleFor(context);

          return NotificationListener<ScrollNotification>(
            onNotification: (ScrollNotification notification) => true,
            child: CustomScrollView(
              key: PageStorageKey<String>(name),
              slivers: <Widget>[
                SliverOverlapInjector(handle: handle),
                SliverPadding(
                  padding: const EdgeInsets.all(8.0),
                  sliver: SliverList(
                    delegate: SliverChildBuilderDelegate(
                      childCount: 30,
                      (BuildContext context, int index) => Container(
                        margin: const EdgeInsets.only(bottom: 8),
                        width: double.infinity,
                        height: 150,
                        color: const Color(0xFFB0A4C8),
                        alignment: Alignment.center,
                        child: Text(
                          '$name $index',
                          style: const TextStyle(fontWeight: FontWeight.w600),
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        }),
      ),
  ];

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) =>
            <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: SliverSafeArea(
              top: false,
              sliver: SliverAppBar(
                title: const Text('Tab Demo'),
                floating: true,
                pinned: true,
                snap: true,
                forceElevated: innerBoxIsScrolled,
                bottom: TabBar(
                  tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                ),
              ),
            ),
          ),
        ],
        body: TabBarView(children: _tabViews),
      ),
    );
  }
}
```
</details>

**Comment by nate-thegrate** [comment]
**_oh no_**

**Comment by nate-thegrate** [comment]
Well, I have good news: I copy-pasted your code sample and ran it against my branch, and it's working!

working tab demo

I'm not exactly sure what's causing the discrepancy, but I did verify that the test I added fails on master and passes on this branch, so it's most likely something on your end.

<br>

Also, quick side note—I believe a blank line would fix your code snippet's formatting:

````diff
<details>
  <summary>Code</summary>
+                        
```dart
import 'dart:ui';

````

**Comment by festelo** [comment]
> Also, quick side note—I believe a blank line would fix your code snippet's formatting:

Yep, already changed it. But TY anyway :)
And for working on such a long-standing issue, too.

> I'm not exactly sure what's causing the discrepancy, but I did verify that the test I added fails on master and passes on this branch, so it's most likely something on your end.

This particular issue may be not related directly to the PR, I'm not fully familiar with the context, sorry for this.
I did clone your branch for testing, but sure it can still be something on my end.
I can't reproduce it just by scrolling the list up, there's definitely another factor involved, but I haven't identified it yet.
However, following in precise the steps I described before always leads to this problem for me.

And I can confirm that your test passes for me too. 

Can you try to run this one?

<details>
  <summary>Code</summary>

```dart
  testWidgets('Maintains scroll position of inactive tab #2', (WidgetTester tester) async {
    await tester.pumpWidget(const example.NestedScrollViewExampleApp());

    final Finder finderItemAny = find.byType(ListTile, skipOffstage: false).first;
    final Finder finderItem11 = find.text('Item 11', skipOffstage: false);
    final Finder finderItem6 = find.text('Item 6', skipOffstage: false);
    final Finder finderItem4 = find.text('Item 4', skipOffstage: false);

    final Finder finderTab1 = find.text('Tab 1');
    final Finder finderTab2 = find.text('Tab 2');

    double getScrollPosition() {
      return Scrollable.of(tester.element(finderItemAny)).position.pixels;
    }

    expect(getScrollPosition(), 0.0);

    await tester.ensureVisible(finderItem11);
    await tester.pumpAndSettle();

    await tester.tap(finderTab2);
    await tester.pumpAndSettle();

    await tester.ensureVisible(finderItem6);
    await tester.pumpAndSettle();

    await tester.tap(finderTab1);
    await tester.pumpAndSettle();

    final tab1Position = getScrollPosition();

    await tester.tap(finderTab2);
    await tester.pumpAndSettle();

    // Without these two lines, the test passes
    await tester.ensureVisible(finderItem4);
    await tester.pumpAndSettle();

    await tester.tap(finderTab1);
    await tester.pumpAndSettle();

    expect(getScrollPosition(), tab1Position);
  });
```
</details>

If it works for you (or if it doesn't work for any other reason than being a bug) - i think we can wrap up this topic.

**Comment by nate-thegrate** [comment]
Thanks for sending that over—I can confirm that the test fails on this branch (and passes without those two lines).

I believe the reason for this is: calling `tester.ensureVisible(finderItem4)` causes it to scroll all the way to the top, i.e. `getScrollPosition()` returns `0`.

On this branch, scrolling one of the tabs up partway (so that the app bar becomes visible) maintains the scroll positions of each tab, but going all the way to the top of the scroll view will reset the scroll positions.

<details> <summary>Code</summary>

```dart
  testWidgets('Maintains scroll position of inactive tab #2', (WidgetTester tester) async {
    await tester.pumpWidget(const example.NestedScrollViewExampleApp());

    final Finder finderItemAny = find.byType(ListTile, skipOffstage: false).first;
    final Finder finderItem11 = find.text('Item 11', skipOffstage: false);
    final Finder finderItem6 = find.text('Item 6', skipOffstage: false);
    final Finder finderItem4 = find.text('Item 4', skipOffstage: false);

    final Finder finderTab1 = find.text('Tab 1');
    final Finder finderTab2 = find.text('Tab 2');

    double getScrollPosition() {
      return Scrollable.of(tester.element(finderItemAny)).position.pixels;
    }

    expect(getScrollPosition(), 0.0);

    await tester.ensureVisible(finderItem11);
    await tester.pumpAndSettle();

    await tester.tap(finderTab2);
    await tester.pumpAndSettle();

    await tester.ensureVisible(finderItem6);
    await tester.pumpAndSettle();

    await tester.tap(finderTab1);
    await tester.pumpAndSettle();

    final double tab1Position = getScrollPosition();

    await tester.tap(finderTab2);
    await tester.pumpAndSettle();
    expect(getScrollPosition(), 416);

    await tester.ensureVisible(finderItem4);
    await tester.pumpAndSettle();
    expect(getScrollPosition(), 0); // passes

    // await tester.tap(finderTab1);
    // await tester.pumpAndSettle();

    // expect(getScrollPosition(), tab1Position);
  });
```

</details>

Overall I feel this PR is a worthwhile change, though whether this is the ideal behavior is probably subjective, and I am still puzzled by the GIF from https://github.com/flutter/flutter/pull/157756#issuecomment-2452765496.

**Comment by festelo** [comment]
> I am still puzzled by the GIF from https://github.com/flutter/flutter/pull/157756#issuecomment-2452765496.

Quick update from my side: 
I can no longer reproduce this bug using swipe gestures. I'm not sure why, but I'm inclined to think you were right and it was some local issue. I'm sorry for taking your time. 
I'm still able to reproduce it when scrolling with the mouse wheel, although I think it might be a separate problem, I couldn't write any automatic tests that can catch it.

**Comment by nate-thegrate** [comment]
No problem, thanks for letting me know!

**Review by bleroux — APPROVED** [review]
LGTM! Great PR :+1:
