### PR TITLE
Run Xcode command lines tools in native ARM

### LINKED ISSUE #65133: "flutter build ios" fails on ARM macOS, ibtoold crashes compiling xcassets/storyboards
Flutter Gallery app does not build/run on the new macOS hardware for deploying to an iOS 13.6.1 device

<details> 
<summary>doctor -v</summary> 

```

asiva@sivas-mac gallery % /Users/asiva/flutter/bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.50, on macOS 11.0 20A5299w, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
``` 

</details> 

```
asiva@sivas-mac gallery % /Users/asiva/flutter/bin/flutter devices  
1 connected device:

iPhone (mobile) • 00008030-001C78E13EE3802E • ios • iOS 13.6.1
```

<details> 
<summary>logs</summary> 

```
asiva@sivas-mac gallery % /Users/asiva/flutter/bin/flutter run      
Launching lib/main.dart on iPhone in debug mode...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: A3HUGF6PH6
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.6s
Xcode build done.                                           34.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-09-02 16:16:15.703 xcodebuild[37765:3293286]  DTDeviceKit: deviceType from 00008030-001C78E13EE3802E was
    NULL
    2020-09-02 16:16:15.855 xcodebuild[37765:3293441]  DTDeviceKit: deviceType from 00008030-001C78E13EE3802E was
    NULL
    2020-09-02 16:16:15.855 xcodebuild[37765:3293441]  DTDeviceKit: deviceType from 00008030-001C78E13EE3802E was
    NULL
    ** BUILD FAILED **


Xcode's output:
↳
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:10: warning: double-quoted include
    "FlutterAppDelegate.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterAppDelegate.h"
             ^~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterAppDelegate.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:10:10: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:10: warning: double-quoted
    include "FlutterPlugin.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPlugin.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlugin.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:11:10: warning: double-quoted include
    "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:11:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterBinaryMessenger.h:10:10: warning:
    double-quoted include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:12:10: warning: double-quoted include
    "FlutterChannels.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterChannels.h"
             ^~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterChannels.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:12:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterChannels.h:8:10: warning: double-quoted
    include "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterChannels.h:9:10: warning: double-quoted
    include "FlutterCodecs.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterCodecs.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterCodecs.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:12:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterChannels.h:9:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterCodecs.h:9:10: warning: double-quoted include
    "FlutterMacros.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:13:10: warning: double-quoted include
    "FlutterCodecs.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterCodecs.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterCodecs.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:14:10: warning: double-quoted include
    "FlutterPlatformViews.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPlatformViews.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlatformViews.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:14:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlatformViews.h:10:9: warning: double-quoted
    include "FlutterCodecs.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #import "FlutterCodecs.h"
            ^~~~~~~~~~~~~~~~~
            <Flutter/FlutterCodecs.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlatformViews.h:11:9: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #import "FlutterMacros.h"
            ^~~~~~~~~~~~~~~~~
            <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:15:10: warning: double-quoted include
    "FlutterTexture.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterTexture.h"
             ^~~~~~~~~~~~~~~~~~
             <Flutter/FlutterTexture.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:8:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:15:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h:11:10: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:9:10: warning: double-quoted include
    "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:10:10: warning: double-quoted include
    "FlutterCallbackCache.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterCallbackCache.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterCallbackCache.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:10:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterCallbackCache.h:10:10: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:11:10: warning: double-quoted include
    "FlutterChannels.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterChannels.h"
             ^~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterChannels.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:12:10: warning: double-quoted include
    "FlutterCodecs.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterCodecs.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterCodecs.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:13:10: warning: double-quoted include
    "FlutterDartProject.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterDartProject.h"
             ^~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterDartProject.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:13:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterDartProject.h:10:10: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:14:10: warning: double-quoted include
    "FlutterEngine.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterEngine.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterEngine.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:14:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h:11:10: warning: double-quoted include
    "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h:12:10: warning: double-quoted include
    "FlutterDartProject.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterDartProject.h"
             ^~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterDartProject.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h:13:10: warning: double-quoted include
    "FlutterMacros.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h:14:10: warning: double-quoted include
    "FlutterPlugin.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterPlugin.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlugin.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h:15:10: warning: double-quoted include
    "FlutterTexture.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterTexture.h"
             ^~~~~~~~~~~~~~~~~~
             <Flutter/FlutterTexture.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:15:10: warning: double-quoted include
    "FlutterHeadlessDartRunner.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterHeadlessDartRunner.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterHeadlessDartRunner.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:15:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterHeadlessDartRunner.h:10:10: warning:
    double-quoted include "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterHeadlessDartRunner.h:11:10: warning:
    double-quoted include "FlutterDartProject.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterDartProject.h"
             ^~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterDartProject.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterHeadlessDartRunner.h:12:10: warning:
    double-quoted include "FlutterEngine.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterEngine.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterEngine.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterHeadlessDartRunner.h:13:10: warning:
    double-quoted include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:16:10: warning: double-quoted include
    "FlutterMacros.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:17:10: warning: double-quoted include
    "FlutterPlatformViews.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPlatformViews.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlatformViews.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:18:10: warning: double-quoted include
    "FlutterPlugin.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterPlugin.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlugin.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:19:10: warning: double-quoted include
    "FlutterPluginAppLifeCycleDelegate.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPluginAppLifeCycleDelegate.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterPluginAppLifeCycleDelegate.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:19:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h:8:10: warning:
    double-quoted include "FlutterPlugin.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPlugin.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlugin.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:20:10: warning: double-quoted include
    "FlutterTexture.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "FlutterTexture.h"
             ^~~~~~~~~~~~~~~~~~
             <Flutter/FlutterTexture.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:21:10: warning: double-quoted include
    "FlutterViewController.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterViewController.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterViewController.h>
    While building module 'Flutter' imported from /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/Flutter.h:21:
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:11:10: warning: double-quoted
    include "FlutterBinaryMessenger.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterBinaryMessenger.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterBinaryMessenger.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:12:10: warning: double-quoted
    include "FlutterDartProject.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterDartProject.h"
             ^~~~~~~~~~~~~~~~~~~~~~
             <Flutter/FlutterDartProject.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:13:10: warning: double-quoted
    include "FlutterEngine.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterEngine.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterEngine.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:14:10: warning: double-quoted
    include "FlutterMacros.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterMacros.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterMacros.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:15:10: warning: double-quoted
    include "FlutterPlugin.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterPlugin.h"
             ^~~~~~~~~~~~~~~~~
             <Flutter/FlutterPlugin.h>
    /Users/asiva/gallery/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h:16:10: warning: double-quoted
    include "FlutterTexture.h" in framework header, expected angle-bracketed instead
    [-Wquoted-include-in-framework-header]
    #include "FlutterTexture.h"
             ^~~~~~~~~~~~~~~~~~
             <Flutter/FlutterTexture.h>
    46 warnings generated.
    While building module 'package_info' imported from
    /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.m:8:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/build/ios/Debug-iphoneos/package_info/package_info.framework/Headers/package_info-umbrella.
    h:13:9: warning: double-quoted include "FLTPackageInfoPlugin.h" in framework header, expected angle-bracketed
    instead [-Wquoted-include-in-framework-header]
    #import "FLTPackageInfoPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~
            <package_info/FLTPackageInfoPlugin.h>
    1 warning generated.
    While building module 'path_provider' imported from
    /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.m:14:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/build/ios/Debug-iphoneos/path_provider/path_provider.framework/Headers/path_provider-umbrel
    la.h:13:9: warning: double-quoted include "FLTPathProviderPlugin.h" in framework header, expected
    angle-bracketed instead [-Wquoted-include-in-framework-header]
    #import "FLTPathProviderPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~
            <path_provider/FLTPathProviderPlugin.h>
    1 warning generated.
    While building module 'shared_preferences' imported from
    /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.m:20:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/build/ios/Debug-iphoneos/shared_preferences/shared_preferences.framework/Headers/shared_pre
    ferences-umbrella.h:13:9: warning: double-quoted include "FLTSharedPreferencesPlugin.h" in framework header,
    expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #import "FLTSharedPreferencesPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            <shared_preferences/FLTSharedPreferencesPlugin.h>
    1 warning generated.
    While building module 'url_launcher' imported from
    /Users/asiva/gallery/ios/Runner/GeneratedPluginRegistrant.m:26:
    In file included from <module-includes>:1:
    /Users/asiva/gallery/build/ios/Debug-iphoneos/url_launcher/url_launcher.framework/Headers/url_launcher-umbrella.
    h:13:9: warning: double-quoted include "FLTURLLauncherPlugin.h" in framework header, expected angle-bracketed
    instead [-Wquoted-include-in-framework-header]
    #import "FLTURLLauncherPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~
            <url_launcher/FLTURLLauncherPlugin.h>
    1 warning generated.
    50 warnings generated.
    2020-09-02 16:16:48.843 ibtoold[37948:3294595] [MT] IBPlatformTool: *** Failed to launch tool with description
    <IBCocoaTouchPlatformToolDescription: 0x7f9b19f2acd0> System content for IBCocoaTouchFramework-ElevenAndLater
    <IBScaleFactorDeviceTypeDescription: 0x7f9b19f2e230> scaleFactor=2x, renderMode.identifier=(null): Failed to
    find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7f9b19f2acd0> System
    content for IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7f9b19f2e230>
    scaleFactor=2x, renderMode.identifier=(null)'.
    Device type: IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)
    Sim runtime: (null)
    ** Please also include the output of `xcrun simctl list` and `xcode-select -p`.: Failed to find newest available
    Simulator runtime: No available runtime found from: [
        watchOS 7.0 (7.0 - 18R5368d) - com.apple.CoreSimulator.SimRuntime.watchOS-7-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The watchOS
        7.0 simulator runtime is not available." UserInfo={NSLocalizedDescription=The watchOS 7.0 simulator runtime
        is not available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software
        caused connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService:
        <dictionary: 0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
        tvOS 14.0 (14.0 - 18J5370e) - com.apple.CoreSimulator.SimRuntime.tvOS-14-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The tvOS
        14.0 simulator runtime is not available." UserInfo={NSLocalizedDescription=The tvOS 14.0 simulator runtime
        is not available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software
        caused connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService:
        <dictionary: 0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
        iOS 14.0 (14.0 - 18A5357e) - com.apple.CoreSimulator.SimRuntime.iOS-14-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The iOS 14.0
        simulator runtime is not available." UserInfo={NSLocalizedDescription=The iOS 14.0 simulator runtime is not
        available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software caused
        connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService: <dictionary:
        0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
    ] when matching for <IBCocoaTouchPlatformToolDescription: 0x7f9b19f2acd0> System content for
    IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7f9b19f2e230> scaleFactor=2x,
    renderMode.identifier=(null), idiom=<IBIPhoneIdiom: 0x7f9b19a0a7f0> runtime=<IBCocoaTouchTargetRuntime:
    0x7f9b164ac3a0>
    /* com.apple.ibtool.errors */
    /Users/asiva/gallery/ios/Runner/Base.lproj/Main.storyboard: error: Failed to find or create execution context
    for description '<IBCocoaTouchPlatformToolDescription: 0x7f9b19f2acd0> System content for
    IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7f9b19f2e230> scaleFactor=2x,
    renderMode.identifier=(null)'.
    Device type: IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)
    Sim runtime: (null)
    ** Please also include the output of `xcrun simctl list` and `xcode-select -p`.
        Underlying Errors:
            Description: Failed to find newest available Simulator runtime
            Underlying Errors:
                Description: No available runtime found from: [
        watchOS 7.0 (7.0 - 18R5368d) - com.apple.CoreSimulator.SimRuntime.watchOS-7-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The watchOS
        7.0 simulator runtime is not available." UserInfo={NSLocalizedDescription=The watchOS 7.0 simulator runtime
        is not available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software
        caused connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService:
        <dictionary: 0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
        tvOS 14.0 (14.0 - 18J5370e) - com.apple.CoreSimulator.SimRuntime.tvOS-14-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The tvOS
        14.0 simulator runtime is not available." UserInfo={NSLocalizedDescription=The tvOS 14.0 simulator runtime
        is not available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software
        caused connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService:
        <dictionary: 0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
        iOS 14.0 (14.0 - 18A5357e) - com.apple.CoreSimulator.SimRuntime.iOS-14-0 (unavailable, failed to open
        liblaunch_sim.dylib) ==> not available: Error Domain=com.apple.CoreSimulator.SimError Code=401 "The iOS 14.0
        simulator runtime is not available." UserInfo={NSLocalizedDescription=The iOS 14.0 simulator runtime is not
        available., NSUnderlyingError=0x7f9b19b88310 {Error Domain=NSPOSIXErrorDomain Code=53 "Software caused
        connection abort" UserInfo={NSLocalizedFailureReason=XPC error talking to SimLaunchHostService: <dictionary:
        0x7fff8ccd5a10> { count = 1, transaction: 0, voucher = 0x0, contents =
    	"XPCErrorDescription" => <string: 0x7fff8ccd5b78> { length = 18, contents = "Connection invalid" }
    }}}, NSLocalizedRecoverySuggestion=Unable to open liblaunch_sim.dylib.  Try reinstalling Xcode or the simulator
    runtime., NSLocalizedFailureReason=failed to open liblaunch_sim.dylib},
    ] when matching for <IBCocoaTouchPlatformToolDescription: 0x7f9b19f2acd0> System content for
    IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7f9b19f2e230> scaleFactor=2x,
    renderMode.identifier=(null), idiom=<IBIPhoneIdiom: 0x7f9b19a0a7f0> runtime=<IBCocoaTouchTargetRuntime:
    0x7f9b164ac3a0>
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.0.99. (in target 'url_launcher' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.0.99. (in target 'shared_preferences' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.0.99. (in target 'path_provider' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.0.99. (in target 'package_info' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')

Could not build the precompiled application for the device.

Error launching application on iPhone.

``` 

</details>

### PR DESCRIPTION
**Pull request by jmagman**
## Description

On macOS ARM machines run Xcode outside Rosetta without x86 translation by prepending commands with `arch -arm64`.

Only update the iOS `xcodebuild` code paths.  More research needed to see what changes `flutter build macos` needs.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/65133

## Tests
`xcrun runs natively on arm64` test, updated `xcrun` tests.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/os.dart [hunk 1]
```diff
@@ -303,8 +303,8 @@ class _MacOSUtils extends _PosixUtils {
     if (_hostPlatform == null) {
       final RunResult arm64Check =
           _processUtils.runSync(<String>['sysctl', 'hw.optional.arm64']);
-      // hw.optional.arm64 is unavailable on < macOS 11 and exits with 1, assume x86 on failure.
       // On arm64 stdout is "sysctl hw.optional.arm64: 1"
+      // On x86 hw.optional.arm64 is unavailable and exits with 1.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/os.dart:307]: I checked again, it exits 1 on x86 macOS 11, too.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 2]
```diff
@@ -260,28 +282,7 @@ class XCDevice {
     );
   }
 
-  bool get isInstalled => _xcode.isInstalledAndMeetsVersionCheck && xcdevicePath != null;
-
-  String _xcdevicePath;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/xcode.dart:265]: This check is overkill.  If Xcode and `xcrun` is installed, `xcdevice` is installed.

File: packages/flutter_tools/test/general.shard/macos/xcode_test.dart [hunk 3]
```diff
@@ -128,210 +116,270 @@ void main() {
...
+          when(mockXcodeProjectInterpreter.minorVersion).thenReturn(2);
+          when(mockXcodeProjectInterpreter.patchVersion).thenReturn(0);
 
-          expect(await xcode.sdkLocation(SdkType.macOS), sdkroot);
+          expect(xcode.isInstalledAndMeetsVersionCheck, isFalse);
           expect(fakeProcessManager.hasRemainingExpectations, isFalse);
         });
 
-        testWithoutContext('--show-sdk-path fails', () async {
+        testWithoutContext('xcrun runs natively on arm64', () {
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/macos/xcode_test.dart:255]: This test is new.

File: packages/flutter_tools/test/general.shard/macos/xcode_test.dart [hunk 4]
```diff
@@ -128,210 +116,270 @@ void main() {
     });
 
     group('Xcode', () {
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/macos/xcode_test.dart:118]: This section looks like a big change, but it's mostly whitespace due to the the new `group` indentation.  The changes in this file:
1. Remove `xcrun --find xcdevice` commands.
2. Use `FakePlatform` instead of `MockPlatform`.
3. Add the `sysctl` ARM check command where needed.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 5]
```diff
@@ -161,24 +170,37 @@ class Xcode {
     return false;
   }
 
+  List<String> xcrunCommand() {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/xcode.dart:173]: nit: doc comment please

**Review by christopherfujino — APPROVED** [review]
LGTM!

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart:173]: Done.

**Comment by jmagman** [comment]
@alexmarkley I know you've been offering to help out with ARM support.  If you are still willing, it would be awesome if you could to take this change for a test drive and see where else the `flutter` command line tool falls down when running against a physical iOS device...

**Comment by alexmarkley** [comment]
@jmagman thanks for tagging me! I will take a look later tonight.

**Comment by alexmarkley** [comment]
@jmagman first impressions. Ran `flutter upgrade` in `flutter channel master`. Here's the output of `flutter doctor -v`:

```
DTK:~ alex$ flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-19.0.pre.41, on macOS 11.0 20A5395g darwin-arm, locale en-US)
    • Flutter version 1.23.0-19.0.pre.41 at /Users/alex/Development/Flutter/flutter
    • Framework revision ed2a4809da (17 minutes ago), 2020-10-14 20:02:04 -0400
    • Engine revision ce75dda492
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


⣽Error executing simctl: 1
arch: posix_spawnp: xcrun: Bad CPU type in executable


[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5035g
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.0 20A5395g darwin-arm

! Doctor found issues in 3 categories.
DTK:~ alex$ 
```

Not sure what's going on with `simctl`. Running `xcrun simctl --help` yields:

```
DTK:~ alex$ xcrun simctl --help
usage: simctl [--set <path>] [--profiles <path>] <subcommand> ...
       simctl help [subcommand]
Command line utility to control the Simulator

For subcommands that require a <device> argument, you may specify a device UDID
or the special "booted" string which will cause simctl to pick a booted device.
If multiple devices are booted when the "booted" device is selected, simctl
will choose one of them.

Subcommands:
	create              Create a new device.
	clone               Clone an existing device.
	upgrade             Upgrade a device to a newer runtime.
	delete              Delete spcified devices, unavailable devices, or all devices.
	pair                Create a new watch and phone pair.
	unpair              Unpair a watch and phone pair.
	pair_activate       Set a given pair as active.
	erase               Erase a device's contents and settings.
	boot                Boot a device.
	shutdown            Shutdown a device.
	rename              Rename a device.
	getenv              Print an environment variable from a running device.
	openurl             Open a URL in a device.
	addmedia            Add photos, live photos, videos, or contacts to the library of a device.
	install             Install an app on a device.
	uninstall           Uninstall an app from a device.
	get_app_container   Print the path of the installed app's container
	install_app_data    Install an xcappdata package to a device, replacing the current contents of the container.
	launch              Launch an application by identifier on a device.
	terminate           Terminate an application by identifier on a device.
	spawn               Spawn a process by executing a given executable on a device.
	list                List available devices, device types, runtimes, or device pairs.
	icloud_sync         Trigger iCloud sync on a device.
	pbsync              Sync the pasteboard content from one pasteboard to another.
	pbcopy              Copy standard input onto the device pasteboard.
	pbpaste             Print the contents of the device's pasteboard to standard output.
	help                Prints the usage for a given subcommand.
	io                  Set up a device IO operation.
	diagnose            Collect diagnostic information and logs.
	logverbose          enable or disable verbose logging for a device
	status_bar          Set or clear status bar overrides
	ui                  Get or Set UI options
	push                Send a simulated push notification
	privacy             Grant, revoke, or reset privacy and permissions
	keychain            Manipulate a device's keychain
DTK:~ alex$ 
```

**Comment by alexmarkley** [comment]
Seems like the simctl issue is preventing flutter from detecting physical devices plugged into the machine. Flutter doctor reports "No devices available" and flutter run in a hello world project yields:

```
DTK:helloWorldThree alex$ flutter run
Error executing simctl: 1
arch: posix_spawnp: xcrun: Bad CPU type in executable


No supported devices connected.
DTK:helloWorldThree alex$ 
```

**Comment by alexmarkley** [comment]
@jmagman uh oh, this is tricky:

```
DTK:~ alex$ xcrun simctl --version
@(#)PROGRAM:simctl  PROJECT:CoreSimulator-732.18.0.2
DTK:~ alex$ /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl --version
@(#)PROGRAM:simctl  PROJECT:CoreSimulator-732.18.0.2
DTK:~ alex$ arch -arm64 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl
arch: posix_spawnp: /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl: Bad CPU type in executable
DTK:~ alex$ lipo -detailed_info /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl
DTK:~ alex$ file /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl: Bourne-Again shell script text executable, ASCII text
DTK:~ alex$ 
DTK:~ alex$ 
DTK:~ alex$ head -n 5 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/simctl
#!/bin/bash
DEVELOPER_USR_BIN_DIR=${0%/*}
DEVELOPER_USR_BIN_DIR=${DEVELOPER_USR_BIN_DIR%/local/bin}
DEVELOPER_USR_BIN_DIR=${DEVELOPER_USR_BIN_DIR%/bin}
DEVELOPER_USR_BIN_DIR=${DEVELOPER_USR_BIN_DIR}/bin
DTK:~ alex$ 
```

**Comment by alexmarkley** [comment]
Oh! @jmagman I think you want this:

```
DTK:~ alex$ arch -arm64e xcrun simctl --version
@(#)PROGRAM:simctl  PROJECT:CoreSimulator-732.18.0.2
DTK:~ alex$ 
```

As per this:

```
DTK:~ alex$ lipo -info /usr/bin/xcrun 
Architectures in the fat file: /usr/bin/xcrun are: x86_64 arm64e 
DTK:~ alex$ 
```

This leads to some interesting behavior like this (running inside of iTerm, which is running under Rosetta):

image

**Comment by jmagman** [comment]
Hm, I was trying to figure out where `arm64e` was needed... on my dtk it only worked with `-arm64` not `-arm64e`

On this commit `flutter run` works:
Screen Shot 2020-10-14 at 6 34 48 PM
and `flutter devices`:
Screen Shot 2020-10-14 at 6 35 57 PM

**Comment by alexmarkley** [comment]
@jmagman that is somewhat baffling. I am on Beta 10 as of this afternoon, I wonder if that could factor in somehow?

I assume Apple's intention in the long term is for the xcrun to spawn ARM processes because the caller is also an ARM process. I guess that's not going to be possible with Dart in the short term?

**Comment by alexmarkley** [comment]
@jmagman are you still running the image that it shipped with? https://betawiki.net/wiki/MacOS_Big_Sur_build_20A5299w

I noticed some pretty significant changes around Beta 7 and following, so maybe an update is in order. 😉
