### PR TITLE
[flutter_tools] Discover pubspec.yaml in parent directories

### LINKED ISSUE #48117: When looking for a pubpec.yaml, tool should also look up the filesystem
```
Error: No pubspec.yaml file found.
```
This message should not be needed if you're running the tool from the `lib` directory, or some other subdirectory of the Flutter project. We should just notice that there's a `pubspec.yaml` in a parent directory, and silently use that directory as the working directory.

### PR DESCRIPTION
**Pull request by jonahwilliams**
If there is no pubspec.yaml in the current directory, walk upwards until we either find one or run out of parents. 

Fixes https://github.com/flutter/flutter/issues/48117

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
I really like this idea, and I think that 99% of the time it would work just right.

I'm a bit worried about the 1% of the time where I have a random nested Flutter project and now don't know which pubspec I'm getting where I used to get an error that I was in the wrong directory.  Or if I (accidentally?) copy a pubspec.yaml into my `$HOME/src/` directory and all of the sudden the tool treats any folder under that as a flutter project.

**Comment by jonahwilliams** [comment]
I thought about that as well, but note that a failing `flutter run` would never irrecoverably alter the environment. I think the worst thing that could happen is an unclear error message.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -695,8 +696,15 @@ abstract class FlutterCommand extends Command<void> {
...
       // Don't expect a pubspec.yaml file if the user passed in an explicit .packages file path.
-      if (!globals.fs.isFileSync('pubspec.yaml')) {
-        throw ToolExit(userMessages.flutterNoPubspec);
+
+      // If there is no pubspec in the current directory, look in the parent
+      // until one can be found.
+      while (!globals.fs.isFileSync('pubspec.yaml')) {
+        final Directory nextCurrent = globals.fs.currentDirectory.parent;
+        if (nextCurrent == null || nextCurrent.path == globals.fs.currentDirectory.path) {
+          throw ToolExit(userMessages.flutterNoPubspec);
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Maybe we could add something in here about which directories we traversed and failed to find?

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 2]
```diff
@@ -695,8 +696,15 @@ abstract class FlutterCommand extends Command<void> {
...
+        }
+        globals.fs.currentDirectory = nextCurrent;
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: If this loop succeeds, it would probably help if we printed a status saying what directory we are using as the cwd.

Comment (dnfield) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Only if we are _not_ using the cwd we started with

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: We should not ever print non-actionable messages, see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#only-log-actionable-messages-to-the-console

Comment (dnfield) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: The action would be to change your cwd if something has gone wrong, right?

Comment (dnfield) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Imagine, for example, the following directory structures:

```
src/
  pubspec.yaml           // put here last week when I didn't trust git to not lose it on me
  flutter_app_1/
    pubspec.yaml
  java_app_1/
    // no pubspec.yaml
```

One day I do `flutter run` in `java_app_1` and to my surprise weird things happen. I would have found it really helpful to know that it was because the tool found a stray pubspec.yaml that I left laying around on my FS.

Alternatively, imagine I did `flutter run -t ../lib/main.dart` from the `android` directory. And imagine that, for some crazy reason, I have a `../../lib/main.dart` present in my filesystem.  The log message would have made it clearer which main.dart was actually getting used.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: It would change the cwd of the dart process, but nothing else is modified.

Comment (dnfield) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Won't the dart process at least potentially be resolving relative paths, such as the `-t` option to flutter run?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Sure, but those might be wrong anyway. At any rate, we're still strictly better than we were before:

1. flutter run  (in lib/): failed
2. flutter run --target=main.dart (in lib/): failed

After:

1. flutter run (in lib/): passed
2. flutter run --target=main.dart (in lib/): failed


If this leads to confusion, we can always tweak the error messaging

Comment (dnfield) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: What's the output of `flutter run --target=main.dart` in `lib/` with this patch?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Target file "main.dart" not found.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Okay, I'll back out my comment on non-actionable message :) . Like you suggested, we status log to the new CWD if it is updated, then the error message above is more interpretable

File: packages/flutter_tools/test/commands.shard/hermetic/run_test.dart [hunk 3]
```diff
@@ -125,6 +125,55 @@ void main() {
...
+      try {
+        await createTestCommandRunner(command).run(<String>[
+          'run',
+          '--fast-start',
+          '--no-pub',
+        ]);
+        fail('Expect exception');
+      } catch (e) {
+        expect(e, isInstanceOf<ToolExit>());
+        expect(e.toString(), contains('Target file "lib/main.dart" not found.'));
```
Comment (dnfield) [inline packages/flutter_tools/test/commands.shard/hermetic/run_test.dart]: should we also expect to find the log told us what directory we ended up in?  Or am I misunderstanding what this test is actually setting up?

**Review by dnfield — APPROVED** [review]
Lgtm
