### PR TITLE
Fix skipping golden comparator for CI environments

### LINKED ISSUE #145618: Local comparator was used on postsubmit CI for Linux coverage shard
Noticed in a failing build of Linux Coverage:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20coverage/2472/overview

```
04:18 +1335: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll vertically                                                             
No expectations provided by Skia Gold for test: widgets.overscroll_stretch.vertical.start.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/.
Validate image output found at file:///b/s/w/ir/x/w/flutter%20sdk/bin/cache/pkg/skia_goldens/packages/flutter/test/widgets/
No expectations provided by Skia Gold for test: widgets.overscroll_stretch.vertical.start.stretched.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/.
Validate image output found at file:///b/s/w/ir/x/w/flutter%20sdk/bin/cache/pkg/skia_goldens/packages/flutter/test/widgets/
No expectations provided by Skia Gold for test: widgets.overscroll_stretch.vertical.end.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/.
Validate image output found at file:///b/s/w/ir/x/w/flutter%20sdk/bin/cache/pkg/skia_goldens/packages/flutter/test/widgets/
No expectations provided by Skia Gold for test: widgets.overscroll_stretch.vertical.end.stretched.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/.
Validate image output found at file:///b/s/w/ir/x/w/flutter%20sdk/bin/cache/pkg/skia_goldens/packages/flutter/test/widgets/

04:19 +1336: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll vertically                                                             
04:19 +1336: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - vertical                                            
04:19 +1336: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - vertical                                            
No expectations provided by Skia Gold for test: widgets.overscroll_stretch.vertical.reverse.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/.
Validate image output found at file:///b/s/w/ir/x/w/flutter%20sdk/bin/cache/pkg/skia_goldens/packages/flutter/test/widgets/

04:19 +1337: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - vertical                                            
04:19 +1337: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - horizontal                                          
04:20 +1337: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - horizontal                                          
04:20 +1337: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - horizontal                                          
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following HttpException was thrown while running async test code:
Connection reset by peer, uri =
https://flutter-gold.skia.org/json/v2/latestpositivedigest/48600c06e6420453883bcc5383168c45

When the exception was thrown, this was the stack

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════

04:20 +1337 -1: /b/s/w/ir/x/w/flutter sdk/packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart: Stretch overscroll works in reverse - horizontal [E]                                   
  Test failed. See exception logs above.
  The test description was: Stretch overscroll works in reverse - horizontal
```

This means the wrong golden file comparator was selected for the testing environment. The local comparator was selected instead of the skipping one (this test shard does not execute golden file tests).

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/145618

The local file comparator was being used in post submit for the Linux coverage shard. This corrects it to choose the skipping comparator.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter_goldens/test/comparator_selection_test.dart [hunk 1]
```diff
@@ -60,18 +60,18 @@ void main() {
     expect(_testRecommendations(hasFlutterRoot: true, hasGold: true), _Comparator.local);
 
     // If we don't have gold but are on CI, we skip regardless.
-    expect(_testRecommendations(hasLuci: true), _Comparator.local); // TODO(ianh): this should be skip
```
Comment (justinmc) [inline packages/flutter_goldens/test/comparator_selection_test.dart:63]: Was this a TODO instead of immediately fixing it because of worries it would be a breaking change?

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter_goldens/test/comparator_selection_test.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter_goldens/test/comparator_selection_test.dart:63]: Yeah, exactly.

After we land this, it might be worth checking to see if everything is working as expected, as this change could I guess be part of the issue that led to the regression of #139549 (I mean, I can't see why it would, but then I can't see why _anything_ in that PR would, so...).

**Review by Hixie — APPROVED** [review]
LGTM

I recommend landing a change to the "inconsequential golden test" as part of this to verify that everything still works on main, but I'll leave that up to your decision.
