### PR TITLE
Fix bug with clicking `Copy` or `Select All` within contextMenu

### LINKED ISSUE #120080: [SelectionArea] Two weird behaves when clicking `Copy` or `Select All` in contextMenu
## `Copy` in contextMenu

the handlers disappear when clicking `Copy` in contextMenu

### Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Select some text.
3. Click `Copy` item in contextMenu

**Expected results:**  the selection overlay and handlers does not disappear.

**Actual results:**  the handlers disappear

See attached video below.

https://user-images.githubusercontent.com/15030386/216949402-369d9039-b8cb-465c-9262-1525e6e4e142.mp4

### Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Select some text.
3. Click `Select All` item in contextMenu

**Expected results:**  the handlers does not disappear.

**Actual results:**  the handlers disappear

See attached video below.

https://user-images.githubusercontent.com/15030386/216976904-f75b676f-6522-4bc6-96cf-9280fa809f19.mp4

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const SelectionArea(
        child: Text(
            'Text with content, Text with content,  Text with content,  Text with content,  Text with content,  Text with content,  Text with content,  Text with content,  Text with content,  Text with content,  Text with content, '),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.8.0-4.0.pre, on macOS 13.2 22D49 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.8.0-4.0.pre on channel master at /Users/zidong/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f5394a5c (26 hours ago), 2023-02-04 23:06:19 -0800
    • Engine revision 2a104cdfcd
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • Flutter download mirror http://flutter-storage.alibaba-inc.com/xianyu

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/zidong/Library/Android/sdk
    • Platform android-31, build-tools 33.0.1
    • ANDROID_HOME = /Users/zidong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • zidong  (mobile) • 00008101-001D18E93C91001E • ios            • iOS 15.3.1 19D52
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 13.2 22D49 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by acumen1005**
1. in iOS show the selection overlay and handlers  when clicking `Copy` or `Select All` .
2.  in Android clear the selection when clicking `Copy`, keep to show the selection and handlers when clicking `Select All`.

Fixes #120080 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -319,6 +319,10 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
   /// {@macro flutter.rendering.RenderEditable.lastSecondaryTapDownPosition}
   Offset? lastSecondaryTapDownPosition;
 
+  /// The current status of the selection overlay.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:322]:
```suggestion
  /// The [SelectionOverlay] that is currently visible on the screen.
  ///
  /// Can be null if there is no visible [SelectionOverlay].
```

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -888,6 +892,11 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
     await Clipboard.setData(ClipboardData(text: data.plainText));
   }
 
+  void _selectAll() {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:895]: Why create a new method since we already have selectAll public method.

It looks like the correct fix is to make that method to not hideToolbar ?

Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:895]: thanks for comments. 
> Why create a new method since we already have selectAll public method.

nice question! I have optimized the method, base selectAll public method.

> It looks like the correct fix is to make that method to not hideToolbar ?

more accurately, In iOS or Android, after clicking `selectAll`, the handlers(startHandleLayerLink and endHandleLayerLink) are not hidden

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 1 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:322]: done!

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 3]
```diff
@@ -987,11 +993,10 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
       selectionGeometry: _selectionDelegate.value,
       onCopy: () {
         _copy();
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:995]: In Android copy should clear the selection

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 4]
```diff
@@ -1707,6 +1708,97 @@ void main() {
...
+    expect(buttonItems.length, 2);
+    expect(buttonItems[0].type, ContextMenuButtonType.copy);
+
+    // press `Copy` item
+    buttonItems[0].onPressed.call();
+
+    final SelectableRegionState regionState = tester.state<SelectableRegionState>(find.byType(SelectableRegion));
+
+    // In Android copy should clear the selection
+    if (defaultTargetPlatform == TargetPlatform.android) {
```
Comment (chunhtai) [inline packages/flutter/test/widgets/selectable_region_test.dart:1746]: nit: use switch case.

We might as well test for all platform.

**Review by chunhtai — APPROVED** [review]

**Comment by chunhtai** [comment]
cc @hangyujin for secondary review

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 4 above)
Comment (acumen1005) [reply packages/flutter/test/widgets/selectable_region_test.dart]: done~

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 5]
```diff
@@ -987,11 +993,24 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
-        hideToolbar();
+
+        // in Android copy should clear the selection
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:997]: Capital letter at the start and period at the end.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 6]
```diff
@@ -987,11 +993,24 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+            break;
+          case TargetPlatform.iOS:
+            hideToolbar(false);
+            break;
+          case TargetPlatform.fuchsia:
+          case TargetPlatform.linux:
+          case TargetPlatform.macOS:
+          case TargetPlatform.windows:
+            break;
+        }
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1010]: All the non-iOS platforms also hide the toolbar, right?  I feel like this might break the behavior on those platforms, though I haven't actually tried it.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 7]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+          },
+          child: const Text('How are you?'),
+        ),
+      ),
+    );
+
+    final RenderParagraph paragraph1 = tester.renderObject<RenderParagraph>(find.descendant(of: find.text('How are you?'), matching: find.byType(RichText)));
+    final TestGesture gesture = await tester.startGesture(textOffsetToPosition(paragraph1, 6)); // at the 'r'
+    addTearDown(gesture.removePointer);
+    await tester.pump(const Duration(milliseconds: 500));
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1733]: Is it possible to use a `pumpAndSettle` here instead of an explicit duration?

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 8]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+    // `are` is selected.
+    expect(paragraph1.selections[0], const TextSelection(baseOffset: 4, extentOffset: 7));
+
+    expect(buttonItems.length, 2);
+    expect(buttonItems[0].type, ContextMenuButtonType.copy);
+
+    // press `Copy` item
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1740]: Capital letter at the start and period at the end here too.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 9]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+    buttonItems[0].onPressed.call();
+
+    final SelectableRegionState regionState = tester.state<SelectableRegionState>(find.byType(SelectableRegion));
+
+    // In Android copy should clear the selection
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1745]: Period here.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 10]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+    addTearDown(gesture.removePointer);
+    await tester.pump(const Duration(milliseconds: 500));
+    // `are` is selected.
+    expect(paragraph1.selections[0], const TextSelection(baseOffset: 4, extentOffset: 7));
+
+    expect(buttonItems.length, 2);
+    expect(buttonItems[0].type, ContextMenuButtonType.copy);
+
+    // press `Copy` item
+    buttonItems[0].onPressed.call();
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1741]: Nit: Any advantage to doing it this way versus actually tapping the button?: `await tester.tap(find.text('Copy'));`

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 11]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+    final TestGesture gesture = await tester.startGesture(textOffsetToPosition(paragraph1, 6)); // at the 'r'
+    addTearDown(gesture.removePointer);
+    await tester.pump(const Duration(milliseconds: 500));
+    // `are` is selected.
+    expect(paragraph1.selections[0], const TextSelection(baseOffset: 4, extentOffset: 7));
+
+    expect(buttonItems.length, 2);
+    expect(buttonItems[1].type, ContextMenuButtonType.selectAll);
+
+    // press `Select All` item
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1797]: Capital letter at the start and period at the end here too.

**Review by justinmc — COMMENTED** [review]
Thank you for fixing this!

I'm worried that desktop platforms might not be working correctly (see my comment below).  Otherwise I think this looks good.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1010]: thank you for your comment, I clarify the switch case, only hide the toolbar in iOS and hide the selection in Android,  but other desktop platform do nothing. 
```
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            _clearSelection();
            break;
          case TargetPlatform.iOS:
            hideToolbar(false);
            break;
          case TargetPlatform.fuchsia:
          case TargetPlatform.linux:
          case TargetPlatform.macOS:
          case TargetPlatform.windows:
            break;
        }
```

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 10 above)
Comment (acumen1005) [reply packages/flutter/test/widgets/selectable_region_test.dart:1741]: thank you, actually I want to test the blew callback

lib/src/widgets/selectable_region.dart#L994
```
  List<ContextMenuButtonItem> get contextMenuButtonItems {
    return SelectableRegion.getSelectableButtonItems(
      selectionGeometry: _selectionDelegate.value,
      onCopy: () {
        _copy();

        // In Android copy should clear the selection.
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            _clearSelection();
            break;
          case TargetPlatform.iOS:
            hideToolbar(false);
            break;
          case TargetPlatform.fuchsia:
          case TargetPlatform.linux:
          case TargetPlatform.macOS:
          case TargetPlatform.windows:
            break;
        }
      },
      onSelectAll: () {
        selectAll(SelectionChangedCause.toolbar);
      },
    );
  }
```

I tried to use `tester.tap(find.text('Copy'));`,it does call the blew function, but in this test case, I think I should test `contextMenuButtonItems` copy callback.

lib/src/widgets/selectable_region.dart#L1092
```
  @Deprecated(
    'Use `contextMenuBuilder` instead. '
    'This feature was deprecated after v3.3.0-0.5.pre.',
  )
  @override
  void copySelection(SelectionChangedCause cause) {
    _copy();
    _clearSelection();
  }
```

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 7 above)
Comment (acumen1005) [reply packages/flutter/test/widgets/selectable_region_test.dart:1733]: thank you for you comment, in my opinion, it need to wait for a new frame (gesture) after 500ms. just now I try to call `pumpAndSettle`, but it does't work.

**Comment by acumen1005** [comment]
> Thank you for fixing this!
> 
> I'm worried that desktop platforms might not be working correctly (see my comment below). Otherwise I think this looks good.

thank you for your comments, I replied these comments~

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: That looks right to me, thanks!

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 12]
```diff
@@ -988,11 +994,25 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+          case TargetPlatform.macOS:
+          case TargetPlatform.windows:
+            hideToolbar();
+            break;
+        }
       },
       onSelectAll: () {
-        selectAll();
-        hideToolbar();
+        selectAll(SelectionChangedCause.toolbar);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1015]: I think this also might depend on the platform.  With a quick test:

| Platform | Does it hide the toolbar after select all? |
| --- | --- |
| MacOS | Yes (on Iterm. I also tried Chrome and TextEdit, which had no "Select all" button) |
| Linux | Yes (on gEdit.  Chrome and Terminal didn't have "Select all") |
| Android | No |
| iOS | No |

So probably desktop platforms should hide the toolbar and mobile platforms should not?

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/test/widgets/selectable_region_test.dart:1733]: Oh I see, this is basically a long press, right?

Could you use [longPressAt](https://master-api.flutter.dev/flutter/flutter_test/WidgetController/longPressAt.html) instead of startGesture?

And you can probably use [kLongPressTimeout](https://master-api.flutter.dev/flutter/gestures/kLongPressTimeout-constant.html) instead of 500ms.

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/test/widgets/selectable_region_test.dart:1741]: Got it, I'm on board with that 👍

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 13]
```diff
@@ -1707,6 +1708,105 @@ void main() {
...
+        break;
+      case TargetPlatform.iOS:
+        expect(regionState.selectionOverlay, isNotNull);
+        expect(regionState.selectionOverlay?.startHandleLayerLink, isNotNull);
+        expect(regionState.selectionOverlay?.endHandleLayerLink, isNotNull);
+        break;
+      case TargetPlatform.linux:
+      case TargetPlatform.macOS:
+      case TargetPlatform.windows:
+      case TargetPlatform.fuchsia:
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_region_test.dart:1760]: Small nit: Maybe add a comment like `// Test doesn't run these platforms.` before the `break` here if you think it's useful.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: Oh also, would you mind adding a test that covers this behavior for desktop platforms?  That way we can catch things like this in the future.

**Review by justinmc — COMMENTED** [review]
Thank you for the fixes!  I think there's one more desktop behavior fix we can do here, plus some desktop tests (commented below).  Everything else looks good.

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 7 above)
Comment (acumen1005) [reply packages/flutter/test/widgets/selectable_region_test.dart:1733]: nice suggestion~

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 13 above)
Comment (acumen1005) [reply packages/flutter/test/widgets/selectable_region_test.dart:1760]: done～

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: there was not the desktop test cases before, and I find it's wired to call `hideToolbar();` in desktop platforms, below the test case fail. why handlers are not null in in desktop platforms?
```
    // In Android copy should clear the selection.
    switch(defaultTargetPlatform) {
      case TargetPlatform.android:
        expect(regionState.selectionOverlay, isNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNull);
        break;
      case TargetPlatform.iOS:
        expect(regionState.selectionOverlay, isNotNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNotNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNotNull);
        break;
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.fuchsia:
        expect(regionState.selectionOverlay, isNotNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNull);
        break;
    }
```

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 12 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: thank you for the informations, I fixed it~

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: of course, I would like to add tests, but now I have no idea to test start/end handlers in desktop platforms, would you give some advice? 

I tried the below code, but it doesn't work.
```
     // In Android copy should clear the selection.
    switch(defaultTargetPlatform) {
      case TargetPlatform.android:
        expect(regionState.selectionOverlay, isNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNull);
        break;
      case TargetPlatform.iOS:
        expect(regionState.selectionOverlay, isNotNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNotNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNotNull);
        break;
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.fuchsia:
        expect(regionState.selectionOverlay, isNotNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNull);
        break;
    }
```

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 14]
```diff
@@ -988,11 +994,37 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
       },
       onSelectAll: () {
-        selectAll();
-        hideToolbar();
+        switch (defaultTargetPlatform) {
+          case TargetPlatform.android:
+          case TargetPlatform.iOS:
+            selectAll(SelectionChangedCause.toolbar);
+            break;
+          case TargetPlatform.fuchsia:
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1020]: Also here move fuchsia up with android.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 15]
```diff
@@ -988,11 +994,37 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+
+        // In Android copy should clear the selection.
+        switch (defaultTargetPlatform) {
+          case TargetPlatform.android:
+            _clearSelection();
+            break;
+          case TargetPlatform.iOS:
+            hideToolbar(false);
+            break;
+          case TargetPlatform.fuchsia:
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1006]: Here I think we should move fuchsia up with android.  I think it's best for Fuchsia to match Android until we have some kind of spec for any different behavior for it.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: Don't worry about the handles for desktop, I think we just need to test the toolbar:

```dart
     // In Android copy should clear the selection.
    switch(defaultTargetPlatform) {
      case TargetPlatform.android:
        expect(regionState.selectionOverlay, isNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNull);
        break;
      case TargetPlatform.iOS:
        expect(regionState.selectionOverlay, isNotNull);
        expect(regionState.selectionOverlay?.startHandleLayerLink, isNotNull);
        expect(regionState.selectionOverlay?.endHandleLayerLink, isNotNull);
        break;
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.fuchsia:
        expect(regionState.selectionOverlay, isNotNull);
        break;
    }
```

**Review by justinmc — COMMENTED** [review]
I added a comment about the desktop test, let me know if it doesn't make sense.  I think that's the only thing needed before we can merge this.

Thanks for your quick responses here!

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1012]: done~

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 14 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: done~

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 15 above)
Comment (acumen1005) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: done~

**Comment by acumen1005** [comment]
> I added a comment about the desktop test, let me know if it doesn't make sense. I think that's the only thing needed before we can merge this.
> 
> Thanks for your quick responses here!

Thank you for giving me so much advice～

**Review by justinmc — APPROVED** [review]
LGTM :+1:
