### PR TITLE
Fix RangeMaintainingScrollPhysics

### LINKED ISSUE #60288: TabBarView offset when changing viewport from portrait to landscape
b/159737324

Commit 98bc176 introduced a strange bug that remained undiscovered until now. To reproduce, run the following demo for tabs:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}
```

- Select the last tab (this is important; this does not reproduce for any other tab).
- Switch orientation from portrait to landscape.

You will see that the content of the last tab is offset quite a bit. You can scroll to the left to get the content back.

@Hixie FYI.

### PR DESCRIPTION
**Pull request by Hixie**
It now uses the scroll metrics as they stood at the end of the last frame.

It previously used a weird combination of the old extents and the newish position, which led to some weird effects when the position had been changed in expectation of a viewport or content dimension change.

Fixes https://github.com/flutter/flutter/issues/60288 again.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer Would you mind reviewing this? It's the same patch as before plus an extra commit to fix review comments from the last PR.

**Comment by xu-baolin** [comment]
So did you figure out what causes the internal test failed at the first land?

**Comment by AlexV525** [comment]
Also resolves #63935 , #64899 ?

**Comment by Hixie** [comment]
@xu-baolin We're pretty sure those failures were because tests were assuming the incorrect behavior that has been in the tree for a while (they were all new tests).

File: packages/flutter/test/widgets/range_maintaining_scroll_physics_test.dart [hunk 1]
```diff
@@ -219,4 +220,101 @@ void main() {
...
+    await tester.tap(find.text('bike'));
+    await tester.pump();
+    await tester.pump(const Duration(seconds: 1));
+    final Rect bike1 = tester.getRect(find.byIcon(Icons.directions_bike));
+    await tester.pumpWidget(Padding(padding: EdgeInsets.zero, child: TabBarDemo()));
+    final Rect bike2 = tester.getRect(find.byIcon(Icons.directions_bike));
+    expect(bike2.center, bike1.shift(const Offset(100.0, 0.0)).center);
+  });
+
+  testWidgets('', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/range_maintaining_scroll_physics_test.dart:235]: This test has no name.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
+ 1 nit

File: packages/flutter/lib/src/widgets/debug.dart [hunk 2]
```diff
@@ -255,7 +255,7 @@ bool debugCheckHasMediaQuery(BuildContext context) {
 ///  * alternative: provide additional advice specific to the situation,
 ///    especially an alternative to providing a Directionality ancestor.
 ///    For example, "Alternatively, consider specifying the 'textDirection'
-///    argument.". Should be a funny punctuated sentence.
+///    argument.". Should be a fully punctuated sentence.
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/debug.dart:258]: WE DON'T HAVE FUN HERE.

Comment (Hixie) [reply packages/flutter/lib/src/widgets/debug.dart:258]: I seriously considered leaving the original or having it say "funny and fully" or something but...

File: packages/flutter/test/widgets/range_maintaining_scroll_physics_test.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/test/widgets/range_maintaining_scroll_physics_test.dart:235]: Ah yes, test names. One of the other features I'd just remove entirely if I were to create a new test framework. :-)

Fixed

**Comment by Rodiii** [comment]
Hi all, 
This PR crashed the pull_to_refresh plugin which possibly affects a huge amount of users (pub score 98%).

You can find a stackTrace / bug here:
https://github.com/peng8350/flutter_pulltorefresh/issues/352

The issue is in applyContentDimensions within scroll_position.dart. If I revert the function to the commit before this PR, the issue disappears.

Is there any chance to revert this change?

**Comment by AlexV525** [comment]
> Is there any chance to revert this change?

I think we don't revert a commit for a package, but you can try to fix it by making a PR to the package.

**Comment by Rodiii** [comment]
@AlexV525 Thanks for answering. Sorry, there has been a misunderstanding. I was not talking about the whole commit, I just meant the affected function.

Sure, I could just hand in a PR which reverts the function to before this commit. Anyhow, I guess this would brake the feature(s)/bugfixes @Hixie introduced with his PRs.

Anyhow, if I don't hear anything until tonight, I'll hand in a PR, as this issue just affects too many people.

**Comment by AlexV525** [comment]
> I just meant the affected function.

Because those commits you saw were squashed and merged as a single commit, there are no handy way to partially revert a commit inside them.

> Sure, I could just hand in a PR which reverts the function to before this commit. Anyhow, I guess this would brake the feature(s)/bugfixes @Hixie introduced with his PRs.

I suggest you land the PR in the package repo, because it did fix something but might be a breaking change for some packages. That require packages update too.

**Comment by Hixie** [comment]
Yeah, the right way to fix this is to fix the package. But in the future, the best thing is to have the package's tests submitted to the flutter/tests repository (https://github.com/flutter/tests), since we guarantee that we won't break tests submitted to that repo without first working with the package or application owner to migrate their code.

**Comment by Rodiii** [comment]
Hi all, Thanks for your responses. There are good news, the maintainer of pull_to_refresh just updated the library to support the most recent flutter revision. So there's no issue here anymore :-).
