### PR TITLE
[Flutter] Use the correct place for the system navigation bar color adjustment

### LINKED ISSUE #65626: Overstretching SliverAppBar causes navigation bar color to reset
## Steps to reproduce

Run the sample code provided and overscroll until the navigation bar turns black. Depending on screen size, you may need to keep your first finger always touching the screen and use a second finger to scroll. The color change is done when `SliverAppBar` size is ~50% of the screen.

## Sample code

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(SampleApp());

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    );
    return const MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          physics: BouncingScrollPhysics(),
          slivers: <Widget>[
            SliverAppBar(
              stretch: true,
            ),
            SliverFillRemaining(
              child: Placeholder(),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Expected results:** After overscrolling, navigation bar is still white

**Actual results:** Navigation bar is set to black

This was tested and reproduced on:

- Oneplus 5 running Android 10
- Pixel 3 XL running Android 11

<details>
  <summary>Logs</summary>

```
[ +231 ms] D/PhoneWindow( 7561): setNavigationBarColor: ffffffff
[+9886 ms] D/PhoneWindow( 7561): setNavigationBarColor: ff000000
```

```
Flutter 1.22.0-10.0.pre.137 • channel master • https://github.com/flutter/flutter.git
Framework • revision 37e2013774 (3 hours ago) • 2020-09-11 04:05:02 -0400
Engine • revision bdaac368f8
Tools • Dart 2.10.0 (build 2.10.0-115.0.dev)
```

</details>

### LINKED ISSUE #66429: Android - systemNavigationBarColor is taken from the incorrect place of the screen
## Steps to Reproduce

The example app is available here: [https://github.com/jacek-marchwicki/flutter-insets-bug2](https://github.com/jacek-marchwicki/flutter-insets-bug2)

Changes to the example project that are necessary to reproduce the issue: [https://github.com/jacek-marchwicki/flutter-insets-bug2/commit/74e17edc48c4045e29cfee6524e4f86f979be9f0](https://github.com/jacek-marchwicki/flutter-insets-bug2/commit/74e17edc48c4045e29cfee6524e4f86f979be9f0)

<details>
  <summary>
  Diff
  </summary>

Change in main.dart:
```dart
  @override
  Widget build(BuildContext context) {
    final style = SystemUiOverlayStyle.light;

    return Column(
      children: [
        Flexible(
          child: AnnotatedRegion<SystemUiOverlayStyle>(
            value: style.copyWith(
              statusBarColor: Colors.redAccent,
              systemNavigationBarColor: Colors.redAccent,
            ),
            child: Container(color: Colors.red),
          ),
        ),
        Flexible(
          child: AnnotatedRegion<SystemUiOverlayStyle>(
            value: SystemUiOverlayStyle.light.copyWith(
              statusBarColor: Colors.greenAccent,
              systemNavigationBarColor: Colors.greenAccent,
            ),
            child: Container(color: Colors.green),
          ),
        ),
        Flexible(
          child: AnnotatedRegion<SystemUiOverlayStyle>(
            value: style.copyWith(
              statusBarColor: Colors.blueAccent,
              systemNavigationBarColor: Colors.blueAccent,
            ),
            child: Container(color: Colors.blue),
          ),
        ),
      ],
    );
  }
```

```patch
Index: android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(revision d3362aabdefa74cc479fc50b8994f00b57b230a8)
+++ android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(date 1600790219000)
@@ -1,7 +1,17 @@
 package com.example.insetstest
 
+import android.graphics.Color
+import android.os.Build
+import android.view.View
 import io.flutter.embedding.android.FlutterActivity
 
-class MainActivity : FlutterActivity() {
-
+class MainActivity: FlutterActivity() {
+    override fun onWindowFocusChanged(hasFocus: Boolean) {
+        super.onWindowFocusChanged(hasFocus)
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
+            window.navigationBarColor = Color.TRANSPARENT
+            window.statusBarColor = Color.TRANSPARENT
+        }
+    }
 }

```
</details>

   1. We need to enable transparent navigation bar. According to (the Android documentation: https://developer.android.com/training/gestures/gesturenav) we need to set:
       ```kotlin
            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            window.navigationBarColor = Color.TRANSPARENT
            window.statusBarColor = Color.TRANSPARENT
       ```
      
  2. Let's split the screen with Column widget with three even containers with different background colors and all wrapped with UI AnnotatedRegion widget with `systemNavigationBarColor`. Every looks like this with different colors:
      ````dart
        Flexible(
          child: AnnotatedRegion<SystemUiOverlayStyle>(
            value: SystemUiOverlayStyle.light.copyWith(
              statusBarColor: Colors.greenAccent,
              systemNavigationBarColor: Colors.greenAccent,
            ),
            child: Container(color: Colors.green),
          ),
        ),
      ```
  3. Run the code on an Android device with API level >= 29

**Expected results:**
OS Navigation Bar background color should change to the color according to the lowest `AnnotatedRegion`.
**Actual results:**
OS Navigation Bar background color changes to the color according to the middle`AnnotatedRegion`.

| Actual result | Expected result |
|---|---|
| ![incorrect](https://user-images.githubusercontent.com/689211/93979434-9de52180-fd7d-11ea-8d17-6b03ca36f50b.png) | ![good](https://user-images.githubusercontent.com/689211/93979435-9f164e80-fd7d-11ea-9c52-14620ba58276.png) |

## Findings

Looks like I found the origin of the issue.

In flutter `view.dart`, lines 259-286 I see something like this:

```dart
    final Offset bottom = Offset(bounds.center.dx, bounds.center.dy - _window.padding.bottom / _window.devicePixelRatio);
    // ...
    SystemUiOverlayStyle lowerOverlayStyle;
    // ...
    lowerOverlayStyle = layer.find<SystemUiOverlayStyle>(bottom);
    // ...
    final SystemUiOverlayStyle overlayStyle = SystemUiOverlayStyle(
    // ...
      systemNavigationBarColor: lowerOverlayStyle?.systemNavigationBarColor,
    // ...
    );
    SystemChrome.setSystemUIOverlayStyle(overlayStyle);
```

So looks like the
Looks like `bounds.center.dy - _window.padding.bottom / _window.devicePixelRatio` is incorrect, because instead of `bounds.center` we should use `bounds.bottom`.

When I change the code to `bounds.bottom - 1.0 - _window.padding.bottom / _window.devicePixelRatio` the app behaves correctly.

Btw: I also think `/ _window.devicePixelRatio` isn't necessary here because everything is calculated in physical device pixels, so we don't need to adjust this value.

## Logs

<details>
  <summary>Logs</summary>

Probably useless, but `flutter run --verbose`:
[out.txt](https://github.com/flutter/flutter/files/5266310/out.txt)

Flutter Analyze:

```
Analyzing flutter-insets-bug2...                                        
No issues found! (ran in 7.4s)
```

Flutter doctor:

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.0 at /Users/jacek/bin/flutter
    • Framework revision 916c3ac648 (8 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jacek/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jacek/Library/Android/sdk
    • Java binary at: /Users/jacek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6823847/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.5.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 4.1)
    • Android Studio at /Users/jacek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6823847/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/jacek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jacek-marchwicki**
## Description
Use the correct place for the system navigation bar color adjustment 

Before the fix: the center of the screen were used to adjust navigation bar color.
After the fix: the center of the bottom navigation bar is used to adjust navigation bar color.

| Before | After the fix |
|---|---|
| incorrect | correct |

For more you can read the following issue: https://github.com/flutter/flutter/issues/66429

For example code that shows differences before and after the change you can use https://github.com/jacek-marchwicki/flutter-insets-bug2

Keep in mind, that `window.padding` isn't calculated correctly for translucent navigation bar on Android (issue: https://github.com/flutter/flutter/issues/63761) and this is not fixed by the PR.

If you have further questions related to this PR, I'm happy to try answering all of them.

## Related Issues

* Closes: https://github.com/flutter/flutter/issues/66429
* Closes: https://github.com/flutter/flutter/issues/65626

## Tests

I added the following tests:
* 'statusBarColor isn\'t set for unannotated view',
* 'statusBarColor is set for annotated view',
* 'statusBarColor isn\'t set when view covers less than half of the system status bar',
* 'statusBarColor is set when view covers more than half of tye system status bar',
* 'systemNavigationBarColor isn\'t set for non Android device',
* 'systemNavigationBarColor isn\'t set for unannotated view',
* 'systemNavigationBarColor is set for annotated view',
* 'systemNavigationBarColor isn\'t set when view covers less than half of navigation bar',
* 'systemNavigationBarColor is set when view covers more than half of navigation bar'

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`). *NOT NEED*
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR. (**I'll wait for the CI build to pass, because unchanged master branch analyze execution is failing on my computer. But I got success on stable branch**)
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

File: packages/flutter/lib/src/rendering/view.dart [hunk 1]
```diff
@@ -245,8 +245,16 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
 
   void _updateSystemChrome() {
     final Rect bounds = paintBounds;
-    final Offset top = Offset(bounds.center.dx, _window.padding.top / _window.devicePixelRatio);
-    final Offset bottom = Offset(bounds.center.dx, bounds.center.dy - _window.padding.bottom / _window.devicePixelRatio);
+    // center of the status bar
+    final Offset top = Offset(
+      bounds.center.dx,
+      _window.padding.top / 2.0,
```
Comment (jacek-marchwicki) [inline packages/flutter/lib/src/rendering/view.dart:251]: info: bottom padding shouldn't be divided by `_window.devicePixelRatio` because everywhere we use native pixels. We should just divide the top padding by two so we get the status bar center. 
Before this calculations worked correctly only on 2x screens.

File: packages/flutter/lib/src/rendering/view.dart [hunk 2]
```diff
@@ -245,8 +245,16 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
...
+    );
+    // center of the navigation bar
+    final Offset bottom = Offset(
+      bounds.center.dx,
+      bounds.bottom - 1.0 - _window.padding.bottom / 2.0,
```
Comment (jacek-marchwicki) [inline packages/flutter/lib/src/rendering/view.dart:256]: info: we need to subtract one pixel because for device 1024x1920, the bottom is 1920, but pixels are in `0..1919` range.

File: packages/flutter/test/rendering/view_chrome_style_test.dart [hunk 3]
```diff
@@ -0,0 +1,255 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+// @dart = 2.8
+import 'dart:ui';
+
+import 'package:flutter/foundation.dart';
```
Comment (jacek-marchwicki) [inline packages/flutter/test/rendering/view_chrome_style_test.dart:8]: info: I couldn't use `view_test.dart` file because `TestRenderingFlutterBinding` it is used there. Those tests uses `TestWidgetsFlutterBinding`. 
Different types of bindings can't be used in the same file.

**Comment by pedromassango** [comment]
Thanks for this PR. Does this PR also fixes the issues mentioned in https://github.com/flutter/flutter/issues/66429#issue-707148242?

**Comment by jacek-marchwicki** [comment]
@pedromassango yes it fixes the issue :)

**Comment by jacek-marchwicki** [comment]
I see some CI failures on this PR: 
* "Linux docs" failing - looks like not related to this PR issue `/b/s/w/ir/kitchen-checkout/flutter/recipe_modules/firebase/resources/firebase_deploy.sh: line 10: firebase: command not found`
* "flutter-build" failing - I can't get details at the build. It displays some flutter dashboard
* "flutter-gold" pending - it is still pending after 8 hours. Unfortunately, I can't get details here too :(

Can you guys help me solve those problems?

**Comment by pedromassango** [comment]
Those failing tests are probably unrelated to the changes so don’t worry about them. They will get fixed once the fix lands into master and you rebase your branch.

I would suggest you to verify and add then into Relates issues section so they will also get closed automatically. This avoid having opened issues that were fixed already.

**Comment by jacek-marchwicki** [comment]
⬆️  FYI: I've just rebased my change to the current master branch and now all tests passes! 
Unfortunately, I still see a lot of `flutter analyze` issues on my computer unrelated to the change.

**Comment by jonahwilliams** [comment]
Since you branched from master when there was an analysis failure, you'll need to pull in the fixes to your local branch. `git fetch upstream master` -> `git pull upstream master`

File: packages/flutter/test/rendering/view_chrome_style_test.dart [hunk 4]
```diff
@@ -0,0 +1,255 @@
...
+            Colors.blue,
+          );
+        },
+        variant: TargetPlatformVariant.only(TargetPlatform.android),
+      );
+    });
+  });
+}
+
+class MockWindowPadding implements WindowPadding {
```
Comment (jonahwilliams) [inline packages/flutter/test/rendering/view_chrome_style_test.dart:239]: nit: call this `FakeWindowPadding`, since `Mock_` is often used for classes which depend on `mockito`

File: packages/flutter/test/rendering/view_chrome_style_test.dart [hunk 5]
```diff
@@ -0,0 +1,255 @@
...
+        ..paddingTestValue = padding
+        ..devicePixelRatioTestValue = _devicePixelRatio
+        ..physicalSizeTestValue = const Size(
+          _deviceWidth * _devicePixelRatio,
+          _deviceHeight * _devicePixelRatio,
+        );
+    }
+
+    tearDown(() async {
+      SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle());
```
Comment (jonahwilliams) [inline packages/flutter/test/rendering/view_chrome_style_test.dart:42]: Not sure if this is necessary, doesn't each `testWidgets` get its own binding/render tree? @goderbauer

File: packages/flutter/test/rendering/view_chrome_style_test.dart [hunk 6]
```diff
@@ -0,0 +1,255 @@
...
+void main() {
+  group('SystemChrome - style', () {
+    const double _statusBarHeight = 25.0;
+    const double _navigationBarHeight = 54.0;
+    const double _deviceHeight = 960.0;
+    const double _deviceWidth = 480.0;
+    const double _devicePixelRatio = 2.0;
+
+    void setupTestDevice() {
+      final TestWidgetsFlutterBinding binding =
```
Comment (jonahwilliams) [inline packages/flutter/test/rendering/view_chrome_style_test.dart:23]: nit: formatting here is a bit awkward, its okay to go over 80 characters

File: packages/flutter/test/rendering/view_chrome_style_test.dart [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter/material.dart';
+import 'package:flutter/rendering.dart';
+import 'package:flutter/services.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
+  group('SystemChrome - style', () {
+    const double _statusBarHeight = 25.0;
```
Comment (jonahwilliams) [inline packages/flutter/test/rendering/view_chrome_style_test.dart:16]: you can make these public

File: packages/flutter/lib/src/rendering/view.dart [hunk 8]
```diff
@@ -245,8 +245,16 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
 
   void _updateSystemChrome() {
     final Rect bounds = paintBounds;
-    final Offset top = Offset(bounds.center.dx, _window.padding.top / _window.devicePixelRatio);
-    final Offset bottom = Offset(bounds.center.dx, bounds.center.dy - _window.padding.bottom / _window.devicePixelRatio);
+    // center of the status bar
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/view.dart:248]: Explanations make sense, could you leave a detailed comment in the code here?

File: packages/flutter/test/rendering/view_chrome_style_test.dart (hunk 5 above)
Comment (jacek-marchwicki) [reply packages/flutter/test/rendering/view_chrome_style_test.dart:42]: @jonahwilliams Looks like it's necessary, `testWidgets` doesn't clear those values by itself.

File: packages/flutter/test/rendering/view_chrome_style_test.dart (hunk 6 above)
Comment (jacek-marchwicki) [reply packages/flutter/test/rendering/view_chrome_style_test.dart:23]: Unfortunately, this is changed back to this format when executing `../../bin/flutter format`.

File: packages/flutter/lib/src/rendering/view.dart (hunk 8 above)
Comment (jacek-marchwicki) [reply packages/flutter/lib/src/rendering/view.dart]: Can you look at the updated?

File: packages/flutter/test/rendering/view_chrome_style_test.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter/test/rendering/view_chrome_style_test.dart:23]: The repo does not use flutter format

Comment (jacek-marchwicki) [reply packages/flutter/test/rendering/view_chrome_style_test.dart:23]: Oh... I see then I'll update this.

**Review by goderbauer — APPROVED** [review]
LGTM
