### PR TITLE
Fix NestedScrollView inner ballistic activity for 0 velocity

### LINKED ISSUE #17096: ListView inside a NestedScrollView skipping items while scrolling up
## Steps to Reproduce
1. scroll down to the bottom
2. scroll up
 -> the ListView will only finish the animation after skipping some items

Could this be a bug or is my usage of a ListView inside a NestedScrollView not correct?

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new MaterialApp(
            home: new DefaultTabController(
                length: 1,
                child: new Scaffold(
                    body: new NestedScrollView(
                        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                            return <Widget>[
                                new SliverAppBar(
                                    pinned: true,
                                    expandedHeight: 256.0,
                                    floating: true,
                                    bottom: new PreferredSize(
                                        preferredSize: new Size.fromHeight(30.0),
                                        child: new Container(
                                            height: 30.0,
                                            child: new TabBar(
                                                tabs: [ new Tab(child: new Text("First"))],
                                            ),
                                        ),
                                    ),
                                ),
                            ];
                        },
                        body: new TabBarView(
                            children: [
                                new ListView.builder(
                                    itemCount: 20,
                                    itemBuilder: (BuildContext context, int index) {
                                        return new ListTile(title: new Text("Item $index"));
                                    },
                                ),
                            ]
                        ),
                    ),
                ),
            )
        );
    }
}
```

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.3.6-pre.53, on Mac OS X 10.13.4 17E199, locale de-DE)
    • Flutter version 0.3.6-pre.53 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision cdbb2385f1 (50 minutes ago), 2018-04-29 10:47:34 -0700
    • Engine revision 613aae032f
    • Dart version 2.0.0-dev.50.0.flutter-cd0c4e4fe1

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/valauskasmodestas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b05)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.3317.48

[✓] Connected devices (2 available)
    • MViPhone • 423196df51b51b49d7d58cab29ea34e19f94fbe8 • ios • iOS 11.3
    • iPhone X • A1223CE9-152A-48EA-8C14-94C467CBF812     • ios • iOS 11.3 (simulator)
```

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR fixes how the inner ballistic scroll activity of a `NestedScrollView` is created when there is 0 velocity.
Prior to this change, it was possible in some cases for the scroll simulation to move in the wrong direction, giving the appearance that the `NestedScrollView` skipped or jumped up the list, rather than completing the overscroll simulation as expected. This is due to the fact that the `_NestedScrollCoordinator` specifically handled 0 velocity differently, and so the range information sent to the `BouncingScrollSimulation` did not correspond to the `_NestedScrollPosition`. 

This only presented when overscrolling at the end of the inner scrollable when using`BouncingScrollPhysics`.
Can be reproduced by 
- overscrolling and then holding momentarily before releasing, resulting in 0 velocity
- flinging into overscroll to trigger the inner ballistic activity, and then quickly tapping to create a secondary ballistic activity with 0 velocity

## Related Issues

Fixes #17096 

## Tests

I added the following tests:

Proper 0 velocity ballistics for overscrolling:
- overscroll, hold for 0 velocity, and release
- overscroll, release, tap for secondary ballistic at 0 velocity 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 1]
```diff
@@ -974,8 +973,7 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
         if (velocity > 0.0) {
           // shrinking
           extra = _outerPosition.minScrollExtent - _outerPosition.pixels;
-        } else {
-          assert(velocity < 0.0);
+        } else if (velocity < 0.0){
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:976]: nit: space before {

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 2]
```diff
@@ -929,7 +927,8 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
 
   _NestedScrollMetrics _getMetrics(_NestedScrollPosition innerPosition, double velocity) {
     assert(innerPosition != null);
-    double pixels, minRange, maxRange, correctionOffset, extra;
+    double pixels, minRange, maxRange, correctionOffset;
+    double extra = 0.0;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:931]: The first if branch below also assigns 0.0 to extra. Remove that?

**Review by goderbauer — APPROVED** [review]
LGTM
