### PR TITLE
Fix ExpandIcon color when ExpansionPanel.canTapOnHeader true (#147097)

### LINKED ISSUE #147097: ExpansionPanel expand/collapse icon appears disabled when ExpansionPanel.canTapOnHeader is true
### Steps to reproduce

Set ExpansionPanel.canTapOnHeader = true, ExpansionPanelList.expandIconColor will be ignored, and the IconButtonTheme.foregroundColor disabled state will instead be used.

[This issue](https://github.com/flutter/flutter/issues/138904) says it is working as intended because it "is grey because it is disabled when canTapOnHeader is true", however, it shouldn't appear disabled as it is an indication to the user that it is expandable, and even if that particular button is disabled, it should appear enabled since tapping there will perform the expand/collapse action. It is a visual-only bug.

### Expected results

ExpandIcon's color should be `expandIconColor` even when `canTapOnHeader` is true.

### Actual results

expandIconColor is not used if `canTapOnHeader` is true, and the iconButtonTheme.foregroundColor disabled state is used.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ExpansionPanelList].

void main() => runApp(const ExpansionPanelListExampleApp());

class ExpansionPanelListExampleApp extends StatelessWidget {
  const ExpansionPanelListExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ExpansionPanelList Sample')),
        body: const ExpansionPanelListExample(),
      ),
    );
  }
}

// stores ExpansionPanel state information
class Item {
  Item({
    required this.expandedValue,
    required this.headerValue,
    required this.value,
    required this.canTapOnHeader,
  });

  String expandedValue;
  String headerValue;
  int value;
  bool canTapOnHeader;
}

List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    bool canTapOnHeader = index > 3;
    return Item(
      headerValue: 'Panel $index canTapOnHeader=${canTapOnHeader.toString()}',
      expandedValue: 'This is item number $index',
      value: index,
      canTapOnHeader: canTapOnHeader,
    );
  });
}

class ExpansionPanelListExample extends StatefulWidget {
  const ExpansionPanelListExample({super.key});

  @override
  State<ExpansionPanelListExample> createState() =>
      _ExpansionPanelListExampleState();
}

class _ExpansionPanelListExampleState extends State<ExpansionPanelListExample> {
  final List<Item> _data = generateItems(8);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList.radio(
      children: _data.map<ExpansionPanelRadio>((Item item) {
        return ExpansionPanelRadio(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
          ),
          value: item.value,
          canTapOnHeader: item.canTapOnHeader,
        );
      }).toList(),
      expandIconColor: Colors.red,
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by benji-farquhar**
Fixes https://github.com/flutter/flutter/issues/147097. The expand/collapse icon should not be the disabled color when ExpansionPanel.canTapOnHeader is true because the ExpansionPanel is active, and we may want to keep the icon there as a visual indicator to the user that it is expandable/collapsable. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by TahaTesser** [comment]
Hi @BenjiFarquhar 
Does this fix https://github.com/flutter/flutter/issues/147097 using `IgnorePointer`?

Looks like this PR is failing some checks and missing test.

**Comment by BenjiFarquhar** [comment]
Hi @TahaTesser. Cheers for reviewing. Yeah, it fixes the issue, as the 'onPressed' is never null now,which is what was causing the disabled appearance.

Hmmm yeah, I figured the tests were failing due to something unrelated, and wasn't sure if I'd need a test for this as it would kinda be testing if 'IgnorePointer' works which would already be tested. Do you think it should have a test?

**Comment by TahaTesser** [comment]
>  Do you think it should have a test?

Yes please, bug fixes always need test(s).

**Comment by BenjiFarquhar** [comment]
@TahaTesser Do you mean a golden test?

**Comment by BenjiFarquhar** [comment]
@TahaTesser A widget test cannot verify the disabled color is not displayed, as  `ExpandIcon.color` always has the enabled color value even if it is not the displayed color due to onPressed being null. I can look into the trailing space issue soon.

**Comment by TahaTesser** [comment]
> @TahaTesser A widget test cannot verify the disabled color is not displayed, as `ExpandIcon.color` always has the enabled color value even if it is not the displayed color due to onPressed being null. I can look into the trailing space issue soon.

I can help you with writing test.  However, can you explain how this fixes the expand icon color when adding `IgnorePointer` widget? 

Running your code sample with the fix, i see no difference in the expand icon color.

Screenshot 2024-05-06 at 12 17 07

**Comment by BenjiFarquhar** [comment]
Cheers. I don't think you have my changes as I get this result:

Screenshot 2024-05-07 at 4 42 42 AM
Screenshot 2024-05-07 at 4 42 21 AM


I explained earlier how it works. The onPressed is never null anymore. We get the same effect of a null onPressed by ignoring the pointer, and since onPressed is never null, the color of the IconButton is always the enabled color.

**Comment by BenjiFarquhar** [comment]
@TahaTesser trailing space is fixed. Not sure why some tests (see test commands below) failed in the remote build, as they pass when I run them locally with:

```
flutter test material/app_test.dart                      
flutter test widgets/draggable_scrollable_sheet_test.dart
flutter test painting/star_border_test.dart 
```

Any idea why they failed in this build?

**Comment by TahaTesser** [comment]
There seems to be a bug on master which doesn't update code so i couldn't the changes from your change. I can confirm it works now.


> flutter test material/app_test.dart                      
> flutter test widgets/draggable_scrollable_sheet_test.dart
> flutter test painting/star_border_test.dart 

These test files are unrelated to this `ExpansionPanel`. Try running test on `expansion_panel_test.dart` file. There is a failure in "'Panel header has semantics, canTapOnHeader = true'" test.

I've updated your fix to mitigate the changing semantics and avoid adding `ignorePointer` when not necessary. 

We can assigned `widget.expandIconColor` to  `disabledColor` in the `ExpandIcon` when `canTapOnHeader`
```dart
        child: ExpandIcon(
          color: widget.expandIconColor,
          disabledColor: child.canTapOnHeader ? widget.expandIconColor : null,
          isExpanded: _isChildExpanded(index),
          padding: _kExpandIconPadding,
          onPressed: !child.canTapOnHeader
              ? (bool isExpanded) => _handlePressed(isExpanded, index)
              : null,
        ),
```

If you still need help testing the changes. let me know. This requires checking icon color when using `canTapOnHeader` prop.

**Comment by BenjiFarquhar** [comment]
@TahaTesser Thanks. I have implemented the changes with tests. Let me know if it requires any changes.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 1]
```diff
@@ -1947,4 +1947,59 @@ void main() {
...
+      ),
+    ));
+
+    await tester.tap(find.text('Panel 1'));
+    await tester.pumpAndSettle();
+
+    final ExpandIcon expandIcon = tester.widget(find.byType(ExpandIcon).first);
+    expect(expandIcon.disabledColor, isNot(expandIconColor));
+    expect(expandIcon.color, expandIconColor);
+  });
```
Comment (TahaTesser) [inline packages/flutter/test/material/expansion_panel_test.dart:2004]:
```suggestion
  testWidgets('ExpandIcon.disabledColor uses expandIconColor color when canTapOnHeader is true', (WidgetTester tester) async {
    const Color expandIconColor = Color(0xff0000ff);

    Widget buildWidget({ bool canTapOnHeader = false }) {
      return MaterialApp(
        home: SingleChildScrollView(
          child: ExpansionPanelList(
            expandIconColor: expandIconColor,
            children: <ExpansionPanel>[
              ExpansionPanel(
                canTapOnHeader: canTapOnHeader,
                headerBuilder: (BuildContext context, bool isExpanded) {
                  return const ListTile(title: Text('Panel'));
                },
                body: const ListTile(title: Text('Content for Panel')),
              ),
            ],
          ),
        ),
      );
    }

    await tester.pumpWidget(buildWidget());

    await tester.tap(find.text('Panel'));
    await tester.pumpAndSettle();

    ExpandIcon expandIcon = tester.widget(find.byType(ExpandIcon));
    expect(expandIcon.disabledColor, isNull);

    await tester.pumpWidget(buildWidget(canTapOnHeader: true));
    await tester.pumpAndSettle();

    expandIcon = tester.widget(find.byType(ExpandIcon));
    expect(expandIcon.disabledColor, expandIconColor);
  });
```

Great job with this test! We can consolidate the two tests and make it concise as well..

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Review by bleroux — APPROVED** [review]
LGTM!
