### PR TITLE
[ Device Lab ] Add regression testing for flutter/flutter#174952

### LINKED ISSUE #174952: Android tests flaking: "Task failed: Bad state: Too many elements"
There has been a recent change that is causing Android tests to flake frequently.

Image

## examples
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20new_gallery_impeller__transition_perf/6185/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20platform_channel_sample_test/9224/overview

## log

```
[2025-09-04 00:51:56.824797] [STDERR] Task failed: Bad state: Too many elements
[2025-09-04 00:51:56.824943] [STDERR] 
[2025-09-04 00:51:56.825004] [STDERR] Stack trace:
[2025-09-04 00:51:56.855300] [STDERR] dart:core                                                  Iterable.single
[2025-09-04 00:51:56.855376] [STDERR] package:flutter_devicelab/framework/devices.dart 689:73    AndroidDevice._getWakefulness
[2025-09-04 00:51:56.855408] [STDERR] ===== asynchronous gap ===========================
[2025-09-04 00:51:56.855434] [STDERR] dart:async                                                 _CustomZone.registerBinaryCallback
[2025-09-04 00:51:56.855456] [STDERR] package:flutter_devicelab/framework/framework.dart 309:28  _TaskRunner._performTask.<fn>
[2025-09-04 00:51:56.855481] [STDERR] package:stack_trace                                        Chain.capture
[2025-09-04 00:51:56.855501] [STDERR] package:flutter_devicelab/framework/framework.dart 307:11  _TaskRunner._performTask
[2025-09-04 00:51:56.855523] [STDERR] package:flutter_devicelab/framework/framework.dart 200:43  _TaskRunner.run
[2025-09-04 00:51:56.855542] [STDERR] 
[2025-09-04 00:51:56.858367] [STDOUT] Checking for reboot
```

### PR DESCRIPTION
**Pull request by bkonyi**
Also switches to using a regex group to match the device state instead of splitting the matched string on '='.

Fixes https://github.com/flutter/flutter/issues/174952

### CODE REVIEW

File: dev/devicelab/test/adb_test.dart [hunk 1]
```diff
@@ -325,19 +325,34 @@ class FakeDevice extends AndroidDevice {
   }
 
   static void pretendAwake() {
+    // Emit an integer value in addition to the state string to ensure only
+    // the state string is matched.
+    //
+    // Regression testing for https://github.com/flutter/flutter/issues/174952.
     output = '''
+      mWakefulness=1
```
Comment (gaaclarke) [inline dev/devicelab/test/adb_test.dart:335]: This is the sort of output we were getting that https://github.com/flutter/flutter/pull/174953 fixed?

**Review by gaaclarke — APPROVED** [review]
lgtm assuming those tests would fail without the presence of https://github.com/flutter/flutter/pull/174953

I think that's the case with my limited knowledge.

File: dev/devicelab/test/adb_test.dart (hunk 1 above)
Comment (bkonyi) [reply dev/devicelab/test/adb_test.dart:335]: Yep, there was two `mWakefulness` outputs for some reason: `mWakefulness=Awake` and `mWakefulness=1`.

**Comment by bkonyi** [comment]
> lgtm assuming those tests would fail without the presence of #174953
> 
> I think that's the case with my limited knowledge.

That's correct!
