### PR TITLE
Switch Material Design icons to using the iconfont

### LINKED ISSUE #994: Support Material Design icons as a web font
The Material Design icons are available as a web font in a small file (~50KB). This would provide fast, scalable Material Design icons that would be much easier to work with than the current system of bitmaps of different sizes.

### LINKED ISSUE #2009: material-design-icons typo results in huge backtrace
```
%cat flutter.yaml                                          [/src/flutter/examples/icons]
name: icons
material-design-icons:
  - name: content/add
  - name: action/accessible
  - name: action/account_balance
  - name: action/account_circle
```

```
flutter start                                             [/src/flutter/examples/icons]
Building APK...
Cannot find asset "action/drawable-mdpi/ic_accessible_white_18dp.png" in directory "/src/flutter/examples/icons/packages/material_design_icons/icons".
1
package:flutter_tools/src/flx.dart 194                            buildInTempDir.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 268                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/flx.dart 198                            buildInTempDir.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/flx.dart 268                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/flx.dart                                buildInTempDir
package:flutter_tools/src/commands/apk.dart 411                   buildAndroid.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/commands/apk.dart 260                   _findApkComponents.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/services.dart 39                        parseServiceConfigs.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/apk.dart                       buildAndroid
package:flutter_tools/src/commands/apk.dart 451                   buildAll.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/apk.dart                       buildAll
package:flutter_tools/src/commands/run.dart 156                   startApp.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       startApp
package:flutter_tools/src/commands/run.dart 107                   RunCommand.runInProject.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 36          FlutterCommand.downloadToolchain.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/toolchain.dart 56                       Toolchain.forConfigs.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/toolchain.dart 44                       _getCompilerPath.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/artifacts.dart 342                      ArtifactStore.getPath.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 51          FlutterCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.run
package:flutter_tools/src/commands/run.dart 84                    RunCommand.run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 43                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 203  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/executable.dart 72                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 65                          main.<async>
```

### LINKED ISSUE #2051: Atom Wish: manage flutter.yaml assets
Keeping a flutter.yaml file up to date is tedious and error prone.

Atom could recognize explicit asset or icon references in Icon, IconButton, AssetImage (etc) code and offer to update the flutter.yaml file.

Similarly It would be nice if there was a way to show which flutter.yaml entries corresponded to literal source code references.

It would be nice if a specialized flutter.yaml editor could display how much space each of the icons and images would occupy, what the total was, etc.

For the material-design-icons (this is the dream scenario) Atom could be bundle ALL of the icons for test runs and then detect which ones were actually loaded and base an automatically generated flutter.yaml file on that.

### LINKED ISSUE #2052: Atom Wish: help with browsing the Material Design icons, image assets
AFAIK the current best practice for selecting a Material Design icon and adding it to an app is to stare at https://design.google.com/icons/ for a while, then identify an icon by combining the name of the section that it's in with its URL. For example the icon at `https://storage.googleapis.com/material-icons/external-assets/v4/icons/zip/ic_3d_rotation_black_24dp.zip` in the `Action` section is `action/3d_rotation`.

It would be helpful if Atom provided a custom MD icon browser with narrowed views (there are  lot of icons), sorting (there are a LOT of icons), searching (ditto), and of course identifying the icons by asset name. Interactive linking from a flutter.yaml entry to an icon would be nice too.

In the same way, it would be helpful if one could point Atom's image asset browser at a package that contained images, and multi-resolution sets of images.

### LINKED ISSUE #2218: Flutter needs to stay in sync with Material Design's standard icons
The icons we're currently bundling with apps aren't up to date per the current MD spec.

The gallery "Menus" demo has run into this:
```
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'action/ic_visibility_black_24dp.png' does not exist.
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'content/ic_link_black_24dp.png' does not exist.
```

### LINKED ISSUE #2313: The Send icon from the code lab has horrific aliasing
It should look like this, but orange:

material-send-icon

Instead, it looks like this:

flutter-send-icon

Notice the warbly edges.

(See also #1831)

### PR DESCRIPTION
**Pull request by abarth**
Rather than managing all the Material Design icons manually, we now
manage them using an icon font. The icon font contains glyphs for each
icon in an efficient vector format.

This patch updates the FLX tooling to include the MaterialIcons font and
updates the Icon widget to use the font instead of asset images.

Fixes #2313
Fixes #2218
Fixes #2009
Fixes #994

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller @krisgiesing

**Comment by sethladd** [comment]
Very cool.

**Comment by HansMuller** [comment]
This (wonderful) PR should not be marked as fixing https://github.com/flutter/flutter/issues/2052 or https://github.com/flutter/flutter/issues/2051

File: examples/material_gallery/lib/demo/tabs_demo.dart [hunk 1]
```diff
@@ -5,29 +5,45 @@
...
+  final List<IconData> icons = <IconData>[
+    Icons.event,
+    Icons.home,
+    Icons.android,
+    Icons.alarm,
+    Icons.face,
+    Icons.language,
+  ];
+
+  final Map<IconData, String> labels = {
```
Comment (a14n) [inline examples/material_gallery/lib/demo/tabs_demo.dart]: `<IconData, String>{`

**Comment by a14n** [comment]
Great change

**Comment by abarth** [comment]
This shrinks the size of the Stocks FLX significantly:

 * Before: 1.0M (1066058)
 * After: 605K (619476)

File: examples/stocks/test/icon_color_test.dart [hunk 2]
```diff
@@ -44,19 +44,9 @@ void checkIconColor(WidgetTester tester, String label, Color color) {
...
-    expect(imageBox.color, isNull);
-  } else if (color == const Color(0xFF000000)) {
-    expect(match[1], equals('black'));
-    expect(imageBox.color, isNull);
-  } else {
-    expect(imageBox.color, equals(color));
-  }
+  Element asset = findElementOfExactWidgetTypeGoingDown(semantics, Icon);
+  Icon icon = asset.widget;
+  expect(icon.color, equals(color));
```
Comment (Hixie) [inline examples/stocks/test/icon_color_test.dart]: a strict conversion of this test would go further and look up the font colour of the underlying RenderParagraph

File: packages/flutter/lib/src/material/icons.dart [hunk 3]
```diff
@@ -0,0 +1,945 @@
+// Copyright 2015 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+class IconData {
+  const IconData(this.codePoint);
+  final int codePoint;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/icons.dart]: operator==, hashCode, toString

File: packages/flutter/lib/src/material/icons.dart [hunk 4]
```diff
@@ -0,0 +1,945 @@
+// Copyright 2015 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+class IconData {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/icons.dart]: Maybe rename this to IconGlyph? IconData made me think it might include e.g. color and bidi information (for those icons that reflect in rtl situations).

**Comment by Hixie** [comment]
lgtm
