### PR TITLE
Fix SnackBar clipping when it is floating due to FloatingActionButton positioning

### LINKED ISSUE #43716: Floating snackbar wrong placement
## Steps to Reproduce

Use the following `build` method to build a new route:

```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    backgroundColor: Colors.blue,
    body: Center(
      child: Builder(
        builder: (_context) => RaisedButton(
          child: Text('Press me!'),
          onPressed: () {
            Scaffold.of(_context).showSnackBar(
              SnackBar(
                content: Text('Wrong place!'),
                behavior: SnackBarBehavior.floating,
              ),
            );
          },
        ),
      ),
    ),
  );
}
```

When the `SnackBar` is shown, dismiss it slowly (swipe down). You can see it's cropped, seems like there's an extra `Scaffold` space that shouldn't be there.

Screenshot_20191029-122202 1
Screenshot_20191029-122211 1

**Target Platform:** Android
**Target OS version/browser:** 9
**Devices:** OnePlus 5

## Flutter doctor

```
[√] Flutter (Channel master, v1.10.15-pre.307, on Microsoft Windows [VersiÃ³n 10.0.18362.418], locale es-ES)
    • Flutter version 1.10.15-pre.307 at C:\src\flutter
    • Framework revision 2cedd559bb (7 hours ago), 2019-10-29 00:43:06 -0400
    • Engine revision 419f5d594a
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 e1fce75301)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • ONEPLUS A5000 • f2eb43ee • android-arm64 • Android 9 (API 28)

• No issues found!

```

### LINKED ISSUE #47202: Floating Snackbar has clipped shadow
## Steps to Reproduce

1. Create app with floating snackbar, for example https://gist.github.com/perclasson/8fbb4e1fdbe171e22a052eae3a3a963d as can be displayed in [DartPad](https://dartpad.dartlang.org/8fbb4e1fdbe171e22a052eae3a3a963d)
2. See the clipped shadow for the floating snackbar.

Example screenshot:
Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-17 at 10 34 47

## Logs

*flutter doctor -v*
```
[✓] Flutter (Channel master, v1.10.1-pre.1255, on Mac OS X 10.14.6 18G103, locale en-DE)
    • Flutter version 1.10.1-pre.1255 at /Users/perc/development/flutter
    • Framework revision e863bf89fb (23 hours ago), 2019-12-16 11:59:43 +0100
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)


[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Connected device (5 available)
    • iPhone 11 Pro Max  • 787077DE-9BAA-449A-B911-80F95A3FCD2A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • iPad Pro (11-inch) • 37D79AA2-C702-4833-9823-09EB6D40EA52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • macOS              • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome             • chrome                               • web-javascript • Google Chrome 79.0.3945.79
    • Web Server         • web-server                           • web-javascript • Flutter Tools

```

### PR DESCRIPTION
**Pull request by filaps**
### Bug cause
`Scaffold` always wraps a `FloatingActionButton`(`FAB`) in a private widget `_FloatingActionButtonTransition`, even if the `FAB` is null (to animate the appearance of the `FAB`).
Thus, `Scaffold` always has a `FAB` and calculates an area for it. Before calculating the position of the `SnackBar`, `Scaffold` verifies the area of `FAB` on `null`. If the area is not `null`, then `SnackBar` will be positioned above it. Since `FAB` and its area is never `null`, `SnackBar` is always on top (This bug works only for `SnackBar` with floating behavior)

### Solution
If the `FAB` is null, then `FloatingActionButtonArea` has a size equal to `Size.zero`. Consequently, if the size of `FloatingActionButtonArea` is zero, then `FAB` won't show and `SnackBar` will be laid out on top of the other content.

### Tests
This PR also adds tests to ensure that the `SnackBar` is positioned in the right places given the many configurations of `Scaffold`

## Related Issues
Fixes #47202
Fixes #43716

## Tests
This PR include parameterized test (to avoid two identical tests differing in one detail). But if it is not ok, i'll split them. 

I added the following tests:

- Snackbar Position (group test)
    - behavior is fixed and scaffold has no other elements 
    - behavior is floating and scaffold has no other elements
    - behavior is fixed and scaffold has bottom navigation bar
    - behavior is floating and scaffold has bottom navigation bar
    - behavior is fixed and scaffold has floating action button
    - behavior is floating and scaffold has floating action button
    - behavior is fixed and scaffold has FAB and bottom navigation bar
    - behavior is floating and scaffold has FAB and bottom navigation bar

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/test/material/scaffold_test.dart [hunk 1]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+        expect(snackBarBottomRight.dy, equals(bottomNavigationBarTopRight.dy));
+      });
+    }
+
+    testWidgets('behavior is fixed and scaffold has floating action button', (WidgetTester tester) async {
+      await tester.pumpWidget(
+        MaterialApp(home: Scaffold(
+          body: Container(),
+          floatingActionButton: FloatingActionButton(onPressed: () {},),
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]:
```suggestion
          floatingActionButton: FloatingActionButton(onPressed: () {}),
```

File: packages/flutter/test/material/scaffold_test.dart [hunk 2]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+      final Offset scaffoldBottomRight = tester.getBottomRight(find.byType(Scaffold));
+
+      expect(snackBarBottomRight.dy, equals(scaffoldBottomRight.dy));
+    });
+
+    testWidgets('behavior is floating and scaffold has floating action button', (WidgetTester tester) async {
+      await tester.pumpWidget(
+        MaterialApp(home: Scaffold(
+          body: Container(),
+          floatingActionButton: FloatingActionButton(onPressed: () {},),
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]:
```suggestion
          floatingActionButton: FloatingActionButton(onPressed: () {}),
```

File: packages/flutter/test/material/scaffold_test.dart [hunk 3]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+        ),
+        ),
+      );
+
+      final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+      scaffoldState.showSnackBar(const SnackBar(content: Text('Snackbar text'), behavior: SnackBarBehavior.floating,));
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]:
```suggestion
      scaffoldState.showSnackBar(
        const SnackBar(
          content: Text('Snackbar text'),
          behavior: SnackBarBehavior.floating,
        ),
      );
```

File: packages/flutter/test/material/scaffold_test.dart [hunk 4]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+      await tester.pump();
+
+      final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+      final Offset fabTopRight = tester.getTopRight(find.byType(FloatingActionButton));
+
+      expect(snackBarBottomRight.dy, equals(fabTopRight.dy));
+    });
+
+    testWidgets('behavior is fixed and scaffold has FAB and bottom navigation bar', (WidgetTester tester) async {
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]: Same comments as above regarding the title of the test and code indentation/style.

File: packages/flutter/test/material/scaffold_test.dart [hunk 5]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+      await tester.pump();
+
+      final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+      final Offset bottomNavigationBarTopRight = tester.getTopRight(find.byKey(boxKey));
+
+      expect(snackBarBottomRight.dy, equals(bottomNavigationBarTopRight.dy));
+    });
+
+    testWidgets('behavior is floating and scaffold has FAB and bottom navigation bar', (WidgetTester tester) async {
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]: Same comments as above regarding the title of the test and code indentation/style.

File: packages/flutter/test/material/scaffold_test.dart [hunk 6]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+        MaterialApp(home: Scaffold(
+          body: Container(),
+          bottomNavigationBar: SizedBox(key: boxKey, width: 800, height: 60),
+          floatingActionButton: FloatingActionButton(onPressed: () {},),
+        ),
+        ),
+      );
+
+      final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+      scaffoldState.showSnackBar(const SnackBar(content: Text('Snackbar text'), behavior: SnackBarBehavior.floating,));
```
Comment (shihaohong) [inline packages/flutter/test/material/scaffold_test.dart]:
```suggestion
      scaffoldState.showSnackBar(
        const SnackBar(
          content: Text('Snackbar text'),
          behavior: SnackBarBehavior.floating,
        ), 
      );
```

**Review by shihaohong — CHANGES_REQUESTED** [review]
Thank you for the submission! The implementation and the tests look great functionally. I think the most work that'll need to be done following up is that the code can be better formatted such that future readers of the code can easily understand what the intent behind the tests are. I made some higher level comments, but take a look at the [Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) when you're unsure on formatting.

**Comment by shihaohong** [comment]
I hope you don't mind, but I also edited your first comment to use GitHub markdown and clarify the title of the pull request if that's okay with you!

File: packages/flutter/test/material/scaffold_test.dart [hunk 7]
```diff
@@ -446,6 +446,139 @@ void main() {
     expect(didPressButton, isTrue);
   });
 
+  group('SnackBar position', () {
+    String getEnumStringValue(SnackBarBehavior behaviour) => behaviour.toString().split('.').last;
+
+    for (SnackBarBehavior behavior in SnackBarBehavior.values) {
+      final SnackBar snackBar = SnackBar(content: const Text('Snackbar text'), behavior: behavior);
+
+      testWidgets('behavior is ${getEnumStringValue(behavior)} and scaffold has no other elements',
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: There is one difference in the result string:
for `$behavior` the result is `"SnackBarBehavior.fixed"`;
for `getEnumStringValue(behavior)` the result is `"fixed"`.
But now i think this difference is not important. Therefore i will remove the function `getEnumStringValue` and will use  `$behavior` instead.

[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: I have added expected results in titles. Is it normal that new test titles have two lines?

File: packages/flutter/test/material/scaffold_test.dart [hunk 8]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+          final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+          scaffoldState.showSnackBar(snackBar);
+
+          await tester.pump();
+
+          final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+          final Offset scaffoldBottomRight = tester.getBottomRight(find.byType(Scaffold));
+
+          expect(snackBarBottomRight.dy, equals(scaffoldBottomRight.dy));
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: I have added a conditions for the left and right corner of snackBar in all new tests except tests with FAB and SnackBarBehavior.floating.

File: packages/flutter/test/material/scaffold_test.dart [hunk 9]
```diff
@@ -446,6 +446,139 @@ void main() {
     expect(didPressButton, isTrue);
   });
 
+  group('SnackBar position', () {
+    String getEnumStringValue(SnackBarBehavior behaviour) => behaviour.toString().split('.').last;
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: i removed this function  :)

File: packages/flutter/test/material/scaffold_test.dart [hunk 10]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+    for (SnackBarBehavior behavior in SnackBarBehavior.values) {
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Done.

File: packages/flutter/test/material/scaffold_test.dart [hunk 11]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+      final SnackBar snackBar = SnackBar(content: const Text('Snackbar text'), behavior: behavior);
+
+      testWidgets('behavior is ${getEnumStringValue(behavior)} and scaffold has no other elements',
+          (WidgetTester tester) async {
+          await tester.pumpWidget(
+            MaterialApp(home: Scaffold(
+              body: Container()
+            ),
+            ),
+          );
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 2 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 3 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 4 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 5 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 6 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/test/material/scaffold_test.dart]: I think that it's ok -- I find that it is difficult to come up with a title that fits in one line that is short enough to be within the 80-character guideline. Plus, I would not have to give up clarity in explaining my test this way

File: packages/flutter/test/material/scaffold_test.dart (hunk 1 above)
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart [hunk 12]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+      await tester.pumpWidget(
+        MaterialApp(home: Scaffold(
+          body: Container(),
+          floatingActionButton: FloatingActionButton(onPressed: () {},),
+        ),
+        ),
+      );
+
+      final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+      scaffoldState.showSnackBar(const SnackBar(content: Text('Snackbar text'), behavior: SnackBarBehavior.fixed,));
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart [hunk 13]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+      await tester.pump();
+
+      final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+      final Offset scaffoldBottomRight = tester.getBottomRight(find.byType(Scaffold));
+
+      expect(snackBarBottomRight.dy, equals(scaffoldBottomRight.dy));
+    });
+
+    testWidgets('behavior is floating and scaffold has floating action button', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart [hunk 14]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+        await tester.pump();
+
+        final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+        final Offset bottomNavigationBarTopRight = tester.getTopRight(find.byKey(boxKey));
+
+        expect(snackBarBottomRight.dy, equals(bottomNavigationBarTopRight.dy));
+      });
+    }
+
+    testWidgets('behavior is fixed and scaffold has floating action button', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

File: packages/flutter/test/material/scaffold_test.dart [hunk 15]
```diff
@@ -446,6 +446,139 @@ void main() {
...
+
+          await tester.pump();
+
+          final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+          final Offset scaffoldBottomRight = tester.getBottomRight(find.byType(Scaffold));
+
+          expect(snackBarBottomRight.dy, equals(scaffoldBottomRight.dy));
+        });
+
+      testWidgets('behavior is ${getEnumStringValue(behavior)} and scaffold has bottom navigation bar', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed.

**Review by shihaohong — COMMENTED** [review]
I just noticed that there is a `test/material/snack_bar_test.dart` file, and that it does include some positioning tests. You might want to take a look at the existing tests to ensure that you're not duplicating some tests and maybe look to see why the existing tests are not catching the clipping issue this PR fixes. 

Also, the tests you've written might actually belong in `snack_bar_test.dart` as well :) 

Sorry for not noticing this sooner! Let me know if you need any suggestions or help with this PR

**Comment by filaps** [comment]
> I just noticed that there is a `test/material/snack_bar_test.dart` file, and that it does include some positioning tests. You might want to take a look at the existing tests to ensure that you're not duplicating some tests and maybe look to see why the existing tests are not catching the clipping issue this PR fixes.
> 
> Also, the tests you've written might actually belong in `snack_bar_test.dart` as well :)
> 
> Sorry for not noticing this sooner! Let me know if you need any suggestions or help with this PR

Thank you for this notice.
I did not look `snak_bar_test.dart` carefully.
I was sure that testing the position of the elements is the responsibility of the scaffold, and so I thought that the tests should be in `scaffold_test.dart.` :)

Now i analyzed snackbar_test.dart:

I found 4 tests with SnackBar position which look like my tests:
1) `SnackBar is positioned above BottomNavigationBar`
2) `SnackBar should push FloatingActionButton above`
3) `Floating SnackBar is positioned above BottomNavigationBar`
4) `Floating SnackBar is positioned above FloatingActionButton`

**Test 1:** 
This test has a very complicated "expected" part:
```

    expect(textBottomLeft.dx - snackBarBottomLeft.dx, 24.0 + 10.0); // margin + left padding
    expect(snackBarBottomLeft.dy - textBottomLeft.dy, 17.0); // margin (with no bottom padding)
    expect(actionTextBottomLeft.dx - textBottomRight.dx, 24.0);
    expect(snackBarBottomRight.dx - actionTextBottomRight.dx, 24.0 + 30.0); // margin + right padding
    expect(snackBarBottomRight.dy - actionTextBottomRight.dy, 17.0); // margin (with no bottom padding)
```

In this case, the SnackBar position is calculated using the `content` of the SnackBar and the `action` of the SnackBar.
Moreover, there are many excess details in the test, such as the `BottomNavigationBar` widget (for example: in my case it is just a `SizedBox`), `GestureDetecter` and too detailed SnackBar.
The test has magic numbers. I spent a lot of time realizing what they mean
**Test 2:**
This test is good. It makes sure the button goes up when the SnackBar appears.
but it just check that `y position` of `FAB` more then `y position` of `SnackBar`.
i can improve the test by check the exact position of the FAB after the appearance of SnackBar.
**Test 3:**
This test should catch a bug, but it skips it.
`expect (snackBarBottomRight.dy - actionTextBottomRight.dy, 27.0)` This line checks that the distance between the `action` and the `SnackBar` border is `27`, but does not check at what `y position` of the `SnackBar` is now.
**Test 4:**
This is the correct test, but a lot of excess details in my opinion.
Its advantage is that it checks for padding, but I would move the checks for padding to a separate test.

In total:

- I think `test 1` should be replaced with my test (`'$behavior should align snackBar with the top of bottom navigation bar when Scaffold has no FloatingActionButton'`)
- Improve `test 2`
- `test 3` has all the same problems as `test 1`. I also suggest replacing it with my test.
- Remove excess details from the `test 4`.
- move all my tests (except  `${SnackBarBehavior.floating} should align snackBar with the top of FloatingActionButton'
      'when Scaffold has a FloatingActionButton'`) to `snack_bar_test.dart`
- maybe separate tests that check SnackBar position when Scaffold has a padding

**Comment by shihaohong** [comment]
> I was sure that testing the position of the elements is the responsibility of the scaffold, and so I thought that the tests should be in scaffold_test.dart. :)

That's okay, I had the same thoughts :) 

> **Test 1:** 
> This test has a very complicated "expected" part:
> ```
> 
>     expect(textBottomLeft.dx - snackBarBottomLeft.dx, 24.0 + 10.0); // margin + left padding
>     expect(snackBarBottomLeft.dy - textBottomLeft.dy, 17.0); // margin (with no bottom padding)
>     expect(actionTextBottomLeft.dx - textBottomRight.dx, 24.0);
>     expect(snackBarBottomRight.dx - actionTextBottomRight.dx, 24.0 + 30.0); // margin + right padding
>     expect(snackBarBottomRight.dy - actionTextBottomRight.dy, 17.0); // margin (with no bottom padding)
> ```
> 
> In this case, the SnackBar position is calculated using the `content` of the SnackBar and the `action` of the SnackBar.
> Moreover, there are many excess details in the test, such as the `BottomNavigationBar` widget (for example: in my case it is just a `SizedBox`), `GestureDetecter` and too detailed SnackBar.
> The test has magic numbers. I spent a lot of time realizing what they mean

Hmm, this seems to more so test the margins/padding between the edges of `SnackBar` and its contents. Perhaps keeping it and renaming the test would suffice?

> Test 2:
> This test is good. It makes sure the button goes up when the SnackBar appears.
> but it just check that y position of FAB more then y position of SnackBar.
> i can improve the test by check the exact position of the FAB after the appearance of SnackBar.
Sounds good! If it's an easy change to make, I'd welcome it :) 

> Test 3:
> This test should catch a bug, but it skips it.
> expect (snackBarBottomRight.dy - actionTextBottomRight.dy, 27.0) This line checks that the distance between the action and the SnackBar border is 27, but does not check at what y position of the SnackBar is now. (same problem in test 1)

Same comment as with test 1, let's keep the test for now and just rename it such that it's clear that it checks for margin/padding correctness.

> Test 4:
> This is the correct test, but a lot of excess details in my opinion.
> Its advantage is that it checks for padding, but I would move the checks for padding to a separate test.

Seems like a great idea! 

> In total:
> - I think test 1 should be replaced with my test ('$behavior should align snackBar with the top of bottom navigation bar when Scaffold has no FloatingActionButton')
> - Improve test 2
> - test 3 has all the same problems as test 1. I also suggest replacing it with my test.
> - Remove excess details from the test 4.
> - move all my tests (except ${SnackBarBehavior.floating} should align snackBar with the top of FloatingActionButton' 'when Scaffold has a FloatingActionButton') to snack_bar_test.dart
> maybe separate tests that check SnackBar position when Scaffold has a padding

I think for test 1, 3 and 4, what we could do is add your tests, and then trim out the margin/padding sections of the preexisting tests and make them into new tests. That way, we don't remove tests for expected padding, while incorporating your positioning tests.

Any idea why the original tests never caught the error case? Is it simply because that specific case was never tested?

File: packages/flutter/test/material/scaffold_test.dart [hunk 16]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+  group('SnackBar position', () {
+    for (final SnackBarBehavior behavior in SnackBarBehavior.values) {
+      final SnackBar snackBar = SnackBar(
+        content: const Text('Snackbar text'),
+        behavior: behavior,
+      );
+
+      testWidgets(
+        '$behavior should align snackBar with the bottom of Scaffold '
+        'when scaffold has no other elements',
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 17]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+          final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+          final Offset scaffoldBottomRight = tester.getBottomRight(find.byType(Scaffold));
+
+          expect(snackBarBottomRight, equals(scaffoldBottomRight));
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset scaffoldBottomLeft = tester.getBottomLeft(find.byType(Scaffold));
+
+          expect(snackBarBottomLeft, equals(scaffoldBottomLeft));
+      });
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed in all new tests

File: packages/flutter/test/material/scaffold_test.dart [hunk 18]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+      );
+
+      testWidgets(
+        '$behavior should align snackBar with the bottom of Scaffold '
+        'when scaffold has no other elements',
+        (WidgetTester tester) async {
+          await tester.pumpWidget(
+            MaterialApp(
+              home: Scaffold(
+                body: Container()
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 19]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+          final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+          final Offset bottomNavigationBarTopRight = tester.getTopRight(find.byKey(boxKey));
+
+          expect(snackBarBottomRight, equals(bottomNavigationBarTopRight));
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset bottomNavigationBarTopLeft = tester.getTopLeft(find.byKey(boxKey));
+
+          expect(snackBarBottomLeft, equals(bottomNavigationBarTopLeft));
+        });
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 20]
```diff
@@ -446,6 +446,203 @@ void main() {
...
 
+  group('SnackBar position', () {
+    for (final SnackBarBehavior behavior in SnackBarBehavior.values) {
+      final SnackBar snackBar = SnackBar(
+        content: const Text('Snackbar text'),
+        behavior: behavior,
+      );
+
+      testWidgets(
+        '$behavior should align snackBar with the bottom of Scaffold '
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 21]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+          expect(snackBarBottomRight, equals(scaffoldBottomRight));
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset scaffoldBottomLeft = tester.getBottomLeft(find.byType(Scaffold));
+
+          expect(snackBarBottomLeft, equals(scaffoldBottomLeft));
+      });
+
+      testWidgets(
+        '$behavior should align snackBar with the top of bottom navigation bar '
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 22]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset bottomNavigationBarTopLeft = tester.getTopLeft(find.byKey(boxKey));
+
+          expect(snackBarBottomLeft, equals(bottomNavigationBarTopLeft));
+        });
+    }
+
+    testWidgets(
+      '${SnackBarBehavior.fixed} should align snackBar with the bottom of Scaffold '
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 23]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+        expect(snackBarBottomRight, equals(scaffoldBottomRight));
+
+        final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+        final Offset scaffoldBottomLeft = tester.getBottomLeft(find.byType(Scaffold));
+
+        expect(snackBarBottomLeft, equals(scaffoldBottomLeft));
+    });
+
+    testWidgets(
+      '${SnackBarBehavior.floating} should align snackBar with the top of FloatingActionButton'
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 24]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+        await tester.pump();
+
+        final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+        final Offset fabTopRight = tester.getTopRight(find.byType(FloatingActionButton));
+
+        expect(snackBarBottomRight.dy, equals(fabTopRight.dy));
+    });
+
+    testWidgets(
+      '${SnackBarBehavior.fixed} should align snackBar with the top of BottomNavigationBar '
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

File: packages/flutter/test/material/scaffold_test.dart [hunk 25]
```diff
@@ -446,6 +446,203 @@ void main() {
...
+        expect(snackBarBottomRight, equals(bottomNavigationBarTopRight));
+
+        final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+        final Offset bottomNavigationBarTopLeft = tester.getTopLeft(find.byKey(boxKey));
+
+        expect(snackBarBottomLeft, equals(bottomNavigationBarTopLeft));
+    });
+
+    testWidgets(
+      '${SnackBarBehavior.floating} should align snackBar with the top of FloatingActionButton '
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/scaffold_test.dart]: Fixed

**Comment by filaps** [comment]
> Any idea why the original tests never caught the error case? Is it simply because that specific case was never tested?

yes, that's right.

> Perhaps keeping it and renaming the test would suffice?

Good idea, i agree!

> take out the margin/padding sections of the preexisting tests and make them into new tests.

I found a test with paddings of SnackBar. In my commit i just improved it by adding universal behavior and checking the leftBottom and rightBottom points of SnackBar.

File: packages/flutter/test/material/snack_bar_test.dart [hunk 26]
```diff
@@ -557,17 +561,19 @@ void main() {
...
     await tester.tap(find.text('X'));
     await tester.pump(); // start animation
     await tester.pump(const Duration(milliseconds: 750)); // Animation last frame.
 
-    final Offset snackBarTopCenter = tester.getCenter(find.byType(SnackBar));
-    final Offset floatingActionButtonBottomCenter = tester.getCenter(find.byType(FloatingActionButton));
+    final Offset snackBarTopRight = tester.getTopRight(find.byType(SnackBar));
+    final Offset fabBottomRight = tester.getBottomRight(find.byType(FloatingActionButton));
+
+    const int fabMargin = 16;
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
    // {{Describe wherever this value was derived from}}
    const int defaultFabPadding = 16;
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 27]
```diff
@@ -557,17 +561,19 @@ void main() {
       ),
     ));
 
-    final Offset floatingActionButtonOriginBottomCenter = tester.getCenter(find.byType(FloatingActionButton));
+    final Offset fabOriginBottomRight = tester.getBottomRight(find.byType(FloatingActionButton));
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: nit: I confused `origin` and `original` here, since `origin` can also be interpreted as the reference point of some coordinate system :) Maybe we can make this clearer this way:
```dart
    // Get the Rect of the FAB to compare after the SnackBar appears.
    final Offset originalFabRect = tester.getRect(find.byType(FloatingActionButton));
    
    // Code that makes SnackBar appear.
    
    // FAB should shift upwards after SnackBar appears.
    expect(originalFabRect.getBottomRight.dy > fabBottomRight.dy, true);
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 28]
```diff
@@ -557,17 +561,19 @@ void main() {
...
-    final Offset floatingActionButtonBottomCenter = tester.getCenter(find.byType(FloatingActionButton));
+    final Offset snackBarTopRight = tester.getTopRight(find.byType(SnackBar));
+    final Offset fabBottomRight = tester.getBottomRight(find.byType(FloatingActionButton));
+
+    const int fabMargin = 16;
 
-    expect(floatingActionButtonOriginBottomCenter.dy > floatingActionButtonBottomCenter.dy, true);
-    expect(snackBarTopCenter.dy > floatingActionButtonBottomCenter.dy, true);
+    expect(fabOriginBottomRight.dy > fabBottomRight.dy, true);
+    expect(snackBarTopRight.dy - fabMargin, equals(fabBottomRight.dy));
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
    // FAB should be positioned above the SnackBar by the default padding.
    expect(snackBarTopRight.dy - fabMargin, equals(fabBottomRight.dy));
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 29]
```diff
@@ -620,164 +626,65 @@ void main() {
...
-      home: MediaQuery(
-        data: const MediaQueryData(
-          padding: EdgeInsets.only(
-            left: 10.0,
-            top: 20.0,
-            right: 30.0,
-            bottom: 40.0,
-          ),
+  testWidgets(
+    'Indent between border and content of SnackBar when behavior is floating',
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
    'Custom padding between SnackBar and its contents when set to SnackBarBehavior.floating',
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 30]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+              home: Scaffold(
+                body: Container(),
+              ),
+            ),
+          );
+
+          final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+          scaffoldState.showSnackBar(snackBar);
+
+          await tester.pump();
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: You might want the SnackBar to fully animate out before checking the positions.
```suggestion
          await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 31]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+                body: Container(),
+                bottomNavigationBar: SizedBox(key: boxKey, width: 800, height: 60),
+              ),
+            ),
+          );
+
+          final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+          scaffoldState.showSnackBar(snackBar);
+
+          await tester.pump();
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: You might want the SnackBar to fully animate out before checking the positions.
```suggestion
          await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 32]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset bottomNavigationBarTopLeft = tester.getTopLeft(find.byKey(boxKey));
+
+          expect(snackBarBottomLeft, equals(bottomNavigationBarTopLeft));
+        },
+      );
+
+      testWidgets(
+        'padding of SnackBar with $behavior is not consumed by viewInsets',
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: If I remember correctly, `behavior` will result in text similar to `SnackBarBehavior.{behavior}`, so it shouldn't be necessary to specify SnackBar twice in the test names.
```suggestion
        'Padding of $behavior is not consumed by viewInsets',
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 33]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+          expect(snackBarBottomRight, equals(bottomNavigationBarTopRight));
+
+          final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
+          final Offset bottomNavigationBarTopLeft = tester.getTopLeft(find.byKey(boxKey));
+
+          expect(snackBarBottomLeft, equals(bottomNavigationBarTopLeft));
+        },
+      );
+
+      testWidgets(
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: Nice! This is better because it tests for all SnackBar cases.

File: packages/flutter/test/material/snack_bar_test.dart [hunk 34]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+                    ));
+                  },
+                  child: const Text('X'),
+                );
+              }
+            ),
+          ),
+        ));
+        await tester.tap(find.text('X'));
+        await tester.pump(); // start animation
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: I think this could just be 
```dart
        await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 35]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+        await tester.pump(const Duration(milliseconds: 750)); // Animation last frame.
+
+        final Offset snackBarBottomCenter = tester.getBottomLeft(find.byType(SnackBar));
+        final Offset floatingActionButtonTopCenter = tester.getTopLeft(
+          find.byType(FloatingActionButton));
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
          find.byType(FloatingActionButton),
        );
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 36]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+
+        // Since padding and margin is handled inside snackBarBox,
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: What is `snackBarBox`? If it's referring to the `RenderBox` of the SnackBar, maybe generalizing the term might be better:
```suggestion
        // Since padding between the SnackBar and the FAB is created by the SnackBar,
        // the bottom offset of the SnackBar should be equal to the top offset of the FAB.
```

Edit: I realized later that this piece was copy-pasted, but this is a good opportunity to clean this up :)

File: packages/flutter/test/material/snack_bar_test.dart [hunk 37]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+        // the bottom offset of snackbar should equal with top offset of FAB
+        expect(snackBarBottomCenter.dy == floatingActionButtonTopCenter.dy, true);
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: We could just do:
```suggestion
        expect(snackBarBottomCenter.dy, floatingActionButtonTopCenter.dy);
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 38]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+
+        final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+        scaffoldState.showSnackBar(
+          const SnackBar(
+            content: Text('SnackBar text'),
+            behavior: SnackBarBehavior.fixed,
+          ),
+        );
+
+        await tester.pump();
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
        await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 39]
```diff
@@ -1146,4 +1053,283 @@ void main() {
...
+
+        final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+        scaffoldState.showSnackBar(
+          const SnackBar(
+            content: Text('SnackBar text'),
+            behavior: SnackBarBehavior.floating,
+          ),
+        );
+
+        await tester.pump();
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
        await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

**Review by shihaohong — COMMENTED** [review]
This looks much better than it used to before, thanks again for doing all the refactor! 

The only bigger thing is tweaking some tests to fully animate the SnackBar instead of checking the positions of the SnackBar and the FAB only at the very beginning of the animation. Other than that, it's mostly code clarity.

**Comment by shihaohong** [comment]
Bonus points if you could get a screenshot with the fix and put it in the first comment of the issue. That helps 1) verify that the fix is as expected and 2) helps future maintainers of the code understand what the intent of this change was

File: packages/flutter/test/material/snack_bar_test.dart [hunk 40]
```diff
@@ -470,58 +470,62 @@ void main() {
...
-          ),
-        ),
-        child: Scaffold(
-          bottomNavigationBar: BottomNavigationBar(
-            items: const <BottomNavigationBarItem>[
-              BottomNavigationBarItem(icon: Icon(Icons.favorite), title: Text('Animutation')),
-              BottomNavigationBarItem(icon: Icon(Icons.block), title: Text('Zombo.com')),
-            ],
+  testWidgets(
+    'Indent between border and content of SnackBar when behavior is fixed',
```
[the remark this answers is not in the document]
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 26 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 27 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 28 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 29 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 30 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 31 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 32 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 34 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 35 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 36 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 37 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 38 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 39 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart (hunk 36 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed.

File: packages/flutter/test/material/snack_bar_test.dart [hunk 41]
```diff
@@ -557,70 +561,28 @@ void main() {
...
 
-    final Offset snackBarTopCenter = tester.getCenter(find.byType(SnackBar));
-    final Offset floatingActionButtonBottomCenter = tester.getCenter(find.byType(FloatingActionButton));
+    final Rect fabRect = tester.getRect(find.byType(FloatingActionButton));
 
-    expect(floatingActionButtonOriginBottomCenter.dy > floatingActionButtonBottomCenter.dy, true);
-    expect(snackBarTopCenter.dy > floatingActionButtonBottomCenter.dy, true);
-  });
+    // FAB should shift upwards after SnackBar appears.
+    expect(originalFabRect.center.dy > fabRect.center.dy, true);
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: Use [lessThan](https://master-api.flutter.dev/flutter/package-matcher_matcher/lessThan.html) matcher here:
```suggestion
    expect(fabRect.center.dy, lessThan(originalFabRect.center.dy));
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 42]
```diff
@@ -557,70 +561,28 @@ void main() {
...
-    await tester.pump(const Duration(milliseconds: 750)); // Animation last frame.
+    final Offset snackBarTopRight = tester.getTopRight(find.byType(SnackBar));
 
-    final Offset textBottomLeft = tester.getBottomLeft(find.text('I am a snack bar.'));
-    final Offset textBottomRight = tester.getBottomRight(find.text('I am a snack bar.'));
-    final Offset actionTextBottomLeft = tester.getBottomLeft(find.text('ACTION'));
-    final Offset actionTextBottomRight = tester.getBottomRight(find.text('ACTION'));
-    final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
-    final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+    // value was derived from floating_action_button_location.dart
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
    // FAB's surrounding padding is set to [kFloatingActionButtonMargin] in floating_action_button_location.dart byb default.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 43]
```diff
@@ -557,70 +561,28 @@ void main() {
...
+    const int defaultFabPadding = 16;
 
-    expect(textBottomLeft.dx - snackBarBottomLeft.dx, 31.0 + 10.0); // margin + left padding
-    expect(snackBarBottomLeft.dy - textBottomLeft.dy, 27.0); // margin (with no bottom padding)
-    expect(actionTextBottomLeft.dx - textBottomRight.dx, 16.0);
-    expect(snackBarBottomRight.dx - actionTextBottomRight.dx, 31.0 + 30.0); // margin + right padding
-    expect(snackBarBottomRight.dy - actionTextBottomRight.dy, 27.0); // margin (with no bottom padding)
-  }, skip: isBrowser);
+    // FAB should be positioned above the SnackBar by the default padding.
+    expect(snackBarTopRight.dy - defaultFabPadding, fabRect.bottomRight.dy);
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: the order is `expect(actual, expected)`, so since `fabRect` is the actual Rect, it should appear first
```suggestion
    expect(fabRect.bottomRight.dy, snackBarTopRight.dy - defaultFabPadding);
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 44]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+              home: Scaffold(
+                body: Container(),
+              ),
+            ),
+          );
+
+          final ScaffoldState scaffoldState = tester.state(find.byType(Scaffold));
+          scaffoldState.showSnackBar(snackBar);
+
+          await tester.pumpAndSettle(); //Have the SnackBar fully animate out.
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: nit 
```suggestion
          await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 45]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+                          content: const Text('I am a snack bar.'),
+                          duration: const Duration(seconds: 2),
+                          action: SnackBarAction(label: 'ACTION', onPressed: () {}),
+                          behavior: behavior,
+                        ),
+                      );
+                    },
+                    child: const Text('X'),
+                  );
+                }
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: nit:
```suggestion
                },
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 46]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+                  child: const Text('X'),
+                );
+              }
+            ),
+          ),
+        ));
+        await tester.tap(find.text('X'));
+        await tester.pumpAndSettle(); // Have the SnackBar fully animate out.
+
+        final Offset snackBarBottomCenter = tester.getBottomLeft(find.byType(SnackBar));
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
        final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 47]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+        final Offset floatingActionButtonTopCenter = tester.getTopLeft(
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
        final Offset floatingActionButtonTopLeft = tester.getTopLeft(
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 48]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+          find.byType(FloatingActionButton),
+        );
+
+        // Since padding between the SnackBar and the FAB is created by the SnackBar,
+        // the bottom offset of the SnackBar should be equal to the top offset of the FAB
+        expect(snackBarBottomCenter.dy, floatingActionButtonTopCenter.dy);
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
        expect(snackBarBottomLeft.dy, floatingActionButtonTopLeft.dy);
```

**Review by shihaohong — DISMISSED** [review]
Thank you for your patience, I was on vacation and am just getting back into the groove of things :) Pretty much good except for a few variable names in a test (they test the correct behavior though)

File: packages/flutter/test/material/snack_bar_test.dart (hunk 41 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 42 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 43 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 44 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 45 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 47 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 48 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart [hunk 49]
```diff
@@ -557,70 +561,28 @@ void main() {
...
-    await tester.pump(const Duration(milliseconds: 750)); // Animation last frame.
+    final Offset snackBarTopRight = tester.getTopRight(find.byType(SnackBar));
 
-    final Offset textBottomLeft = tester.getBottomLeft(find.text('I am a snack bar.'));
-    final Offset textBottomRight = tester.getBottomRight(find.text('I am a snack bar.'));
-    final Offset actionTextBottomLeft = tester.getBottomLeft(find.text('ACTION'));
-    final Offset actionTextBottomRight = tester.getBottomRight(find.text('ACTION'));
-    final Offset snackBarBottomLeft = tester.getBottomLeft(find.byType(SnackBar));
-    final Offset snackBarBottomRight = tester.getBottomRight(find.byType(SnackBar));
+    // FAB's surrounding padding is set to [kFloatingActionButtonMargin] in floating_action_button_location.dart byb default.
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]:
```suggestion
    // FAB's surrounding padding is set to [kFloatingActionButtonMargin] in floating_action_button_location.dart by default.
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 50]
```diff
@@ -1146,4 +1059,283 @@ void main() {
...
+                    Scaffold.of(context).showSnackBar(SnackBar(
+                      content: const Text('I am a snack bar.'),
+                      duration: const Duration(seconds: 2),
+                      action: SnackBarAction(label: 'ACTION', onPressed: () {}),
+                      behavior: SnackBarBehavior.floating,
+                    ));
+                  },
+                  child: const Text('X'),
+                );
+              }
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart]: nit
```suggestion
              },
```

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
All presubmit tests seem to be passing. Once the tree is green, this will be merged. 

Thank you so much for this contribution and for taking the time to address all feedback!

File: packages/flutter/test/material/snack_bar_test.dart (hunk 49 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

File: packages/flutter/test/material/snack_bar_test.dart (hunk 50 above)
Comment (filaps) [reply packages/flutter/test/material/snack_bar_test.dart]: Fixed

**Comment by filaps** [comment]
> All presubmit tests seem to be passing. Once the tree is green, this will be merged.
> 
> Thank you so much for this contribution and for taking the time to address all feedback!

Thank you for review, it was a pleasure to work with you!

**Comment by shihaohong** [comment]
The presubmit tests seem to have rerun for some reason and `build_tests-linux` is failing on a Gateway Timeout error (unrelated to your change)
