### PR TITLE
Fix `SegmentedButton` default size and default tappable size

### LINKED ISSUE #121493: Height of SegmentedButton does not match Material3 spec and cannot be changed
Internal: b/319434259

# SegmentedButton has wrong height

The Material3 specification gives a height of 40dp for Segmented buttons and a recommended TapTargetSize of 48dp. This cannot be achieved in Flutter since the minimumSize style-property does not affect the widget.
The correct minimumSize was actually set as a default in #120095 but is not honored.

## Expected results: 

A SegmentedButton with (visual) height of 40dp and TapTargetSize of 48dp can be achieved and is the default.

**Relevant Topic in the M3 Spec:** https://m3.material.io/components/segmented-buttons/specs#8e9a164f-1913-4a93-8214-585ce84a8c0f

Bildschirm­foto 2023-02-26 um 21 41 56

## Actual results: 

The minimumHeight of SegmentedButton cannot be changed and defaults to the MaterialTapTargetSize of 48dp.

SegmentedButton without and with minimumSize set (see provided Demo-Code):

grafik

## Issue demo code

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(useMaterial3: true),
      home: const Scaffold(
        body: Center(
          child: SegmentedButtonDemo(),
        ),
      ),
    );
  }
}

class SegmentedButtonDemo extends StatefulWidget {
  const SegmentedButtonDemo({super.key});

  @override
  State<SegmentedButtonDemo> createState() => _SegmentedButtonDemoState();
}

class _SegmentedButtonDemoState extends State<SegmentedButtonDemo> {
  int selectedValue = 1;

  void _onValueSelected(Set<int> value) {
    setState(() {
      selectedValue = value.first;
    });
  }

  List<ButtonSegment<int>> _buttonSegments() {
    return const [
      ButtonSegment(value: 1, label: Text('Hello')),
      ButtonSegment(value: 2, label: Text('World')),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceAround,
      children: [
        SegmentedButton(
          segments: _buttonSegments(),
          selected: {selectedValue},
          onSelectionChanged: _onValueSelected,
        ),
        SegmentedButton(
          style: ButtonStyle(
            minimumSize: MaterialStateProperty.all(const Size.fromHeight(40.0)),
          ),
          segments: _buttonSegments(),
          selected: {selectedValue},
          onSelectionChanged: _onValueSelected,
        )
      ],
    );
  }
}
```

</details>

## Used Flutter version

Channel master, 3.8.0-16.0.pre.55

<details>
<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 3.8.0-16.0.pre.55, on macOS 13.2.1 22D68 darwin-x64, locale de-DE)
    • Flutter version 3.8.0-16.0.pre.55 on channel master at /Users/wachter/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bdfe74fc4a (3 hours ago), 2023-02-26 13:16:23 -0500
    • Engine revision 0c040de0e6
    • Dart version 3.0.0 (build 3.0.0-272.0.dev)
    • DevTools version 2.22.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wachter/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/wachter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM G973F (mobile) • adb-RF8N21W2EKF-fhvdo5._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos                                         • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Web Server (web)  • web-server                                    • web-javascript • Flutter Tools

[✓] Network resources                
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by QuncCccccc**
fix https://github.com/flutter/flutter/issues/121493

`SegmentedButton` uses `TextButton` for each segments. When we have `MaterialTapTargetSize.padded` for `TextButton`, we make sure the minimum tap target size is 48.0( this value can be adjusted by visual density), even tough the actual button size is smaller. When `SegmentedButton` paints segments by using `MultiChildRenderObjectWidget`, it also includes the tap target size so the button that it actually draws always has the same height as the height of the tap target size.

To fix it, this PR firstly calculate the actual height of a text button in `SegmentedButton` class, then we can get the height delta if there is. Then the the value of (Segmented button render box height - the delta) would be the actual button size that we should see.

For now, we are not able to customize the min, max, fixed size in [`SegmentedButton` style](https://api.flutter.dev/flutter/material/SegmentedButton/style.html). So the standard button height is always 40 and can only be customized by `style.visualDensity` and `style.tapTargetSize`; `SegmentedButton` only simulates the `TextButton` behavior when `TextButton`'s height is its default value.

Screenshot 2024-01-25 at 11 45 42 AM

https://github.com/flutter/flutter/assets/36861262/15ca6034-e6e0-4cc6-8fe3-808b4bd6a920

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/segmented_button_test.dart [hunk 1]
```diff
@@ -813,6 +812,48 @@ void main() {
...
+    expect(theme.materialTapTargetSize, MaterialTapTargetSize.padded);
+
+    final Finder button = find.byType(SegmentedButton<int>);
+    expect(tester.getSize(button).height, 48.0);
+    expect(
+      find.byType(SegmentedButton<int>),
+      paints..rrect(
+        style: PaintingStyle.stroke,
+        strokeWidth: 1.0,
+        // Button border height is 43.5 - 4.5 + stoke width(1) = 40.
```
Comment (HansMuller) [inline packages/flutter/test/material/segmented_button_test.dart:852]: If 43.5 and 4.5 correspond to something can identify here, then best to include that info in the comment.

**Review by HansMuller — APPROVED** [review]
LGTM
