### PR TITLE
[ Tool ] Support upgrading to a new Flutter version pointing to the same revision as a previous version

### LINKED ISSUE #170679: Verify that `flutter upgrade` could handle a "new" release with an older commit
This is a **postmortem action item** to help decide how we'd fix a "bad release" in the future.

---

Imagine that we had pushed the contents of `3.32.2` as `3.32.4` to (temporarily) fix the broken release, `3.32.3`.

We are not sure if we _had_ done this, if it would have worked.

We could try experimenting, i.e. with a beta release, or otherwise perhaps try to mock/stub this happening locally (i.e. it's just `git`).

@jtmcdole Did you want to try this? If not let's assign it to @bkonyi - I have too many AIs (https://github.com/flutter/flutter/issues/170547, https://github.com/flutter/flutter/issues/170561, https://github.com/flutter/flutter/issues/170568) on my plate at the moment to take this up.

### PR DESCRIPTION
**Pull request by bkonyi**
In the case of a bad release, we should be able to release a new version of Flutter that points to the revision of the last good release.

This change updates the tool to not only compare framework revisions when determining if the current installation is up to date, and also updates the tag selection logic to pick the most recent version tag first.

Fixes https://github.com/flutter/flutter/issues/170679

### CODE REVIEW

File: packages/flutter_tools/lib/src/version.dart [hunk 1]
```diff
@@ -1032,12 +1032,13 @@ class GitTagVersion {
         _runGit('git fetch $flutterGit --tags -f', processUtils, workingDirectory);
       }
     }
-    // find all tags attached to the given [gitRef]
+    // find all tags attached to the given [gitRef]. These are returned in alphabetical order, so
```
Comment (jtmcdole) [inline packages/flutter_tools/lib/src/version.dart:1035]: non-blocking / future improvement:  We could sort by creation date. We'd still have to filter the list since it doesn't have "points-at"

```shell
git for-each-ref --sort=creatordate refs/tags
```

e.g. output:

```shell
...
b25305a8832cfc6ba632a7f87ad455e319dccce8 commit	refs/tags/3.32.1
8defaa71a77c16e8547abdbfad2053ce3a6e2d5b commit	refs/tags/3.32.2
5c1433509f997e9059d230942bdf83f1b88a179e commit	refs/tags/3.32.3
6fba2447e95c451518584c35e25f5433f14d888c commit	refs/tags/3.32.4
01fde956f0d13551843a44ae16eda7ca87478603 commit	refs/tags/3.34.0-0.0.pre
eb3ca2517147b765887a1f16115add47e4ddbb35 commit	refs/tags/3.34.0-0.1.pre
fcf2c11572af6f390246c056bc905eca609533a0 commit	refs/tags/3.32.5
```

**Review by jtmcdole — APPROVED** [review]
