### PR TITLE
Fix ensureVisible and default focus traversal for reversed scrollables

### LINKED ISSUE #128749: Default focus traversal does not work on reversed scrollables
Found while implementing ensureVisible for 2D

When focus is traversing a scrollable widget, Scrollable.ensureVisible is called to bring a newly focused node into view if it is not currently. This calls ScrollPosition.ensureVisible and then RenderViewport.getOffsetToReveal.
When the default focus request callback does this, it extrapolates the ScrollPositionAlignmentPolicy (where the node should be located when it comes into view) based on the directionality of the keyboard input. This does not however account for the actual axis direction of the scrollable. The focus callback does not actually know anything about the scrollable or if one exists (ensureVisible is a static method).

In the below case, the alignment policy was being set to keepVisibleAtStart, but in the case of a reversed scrollable, this should be flipped.

Expected:

https://github.com/flutter/flutter/assets/16964204/f820d734-7278-45ae-9c62-ab209ab7872f

Actual:

https://github.com/flutter/flutter/assets/16964204/d72ae73b-fdb5-4fed-be61-5d72d695f5eb

```dart
import 'dart:math' as math;
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const SimpleTest());
}

class SimpleTest extends StatelessWidget {
  const SimpleTest({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body:
            ListView(
              reverse: true,
              primary: true,
              children: List.generate(50, (int index) {
                return SizedBox(
                      height: 200.0,
                      width: 200.0,
                      child: Column(
                        children: [
                          Checkbox(value: false, onChanged: (value){}),
                          Text(index.toString()),
                        ],
                      ),
                    );
              })
            ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/128749

The ScrollPositionAlignmentPolicy does not account for AxisDirection, which meant default focus traversal of reversed scrollables did not work. The policy doesn't know about the axis direction, so this is corrected in the ScrollPosition where all the information is available before calling on the viewport for the new target scroll offset.

This fixes that by flipping the policy (unless explicit) so that focus traversal works.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 1]
```diff
@@ -757,6 +757,26 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+      ScrollPositionAlignmentPolicy.explicit => alignmentPolicy,
+      ScrollPositionAlignmentPolicy.keepVisibleAtEnd => ScrollPositionAlignmentPolicy.keepVisibleAtStart,
+      ScrollPositionAlignmentPolicy.keepVisibleAtStart => ScrollPositionAlignmentPolicy.keepVisibleAtEnd,
+    };
+  }
+
+  ScrollPositionAlignmentPolicy _applyAxisDirectionToAlignmentPolicy(ScrollPositionAlignmentPolicy alignmentPolicy) {
+    return switch (axisDirection) {
+      // Start and end alignments must account for axis direction.
+      // When focus is requested for example, it know the directionality of the
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:772]:
```suggestion
      // When focus is requested for example, it knows the directionality of the
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks for fixing that!
