### PR TITLE
fix checkLockAcquired: support re-entrant locking

### LINKED ISSUE #9262: If you have an old commit, you can't build flutter_gallery for Android
I'm on 249bbac362a1e2dec133a8772a1b90cacbd06fd9 (with one 6 month old commit on top).

## command

```
flutter build flx --target /src/flutter/examples/flutter_gallery/lib/main.dart --output-file /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/app.flx --snapshot /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/flx
```

## exception
```
StateError: Bad state: The current process does not own the lock for the cache directory. This is a bug in Flutter CLI tools.

#0      Cache.checkLockAcquired (package:flutter_tools/src/cache.dart:81)
#1      FlutterVersion._getLatestAvailableFlutterVersion (package:flutter_tools/src/version.dart:215)
<asynchronous suspension>
#2      FlutterVersion.checkFlutterVersionFreshness.newerFrameworkVersionAvailable (package:flutter_tools/src/version.dart:180)
<asynchronous suspension>
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:188)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#6      Future.Future.sync (dart:async/future.dart:208)
#7      CommandRunner.run (package:args/command_runner.dart:109)
#8      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#9      run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1465)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#18     main (file:///src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /src/flutter
    • Framework revision e3c7501c4d (6 months ago), 2016-10-19 16:17:55 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/eseidel/Library/Android/sdk
      but Android SDK not found at this location.

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 10  • R32CA05JT2E                          • android-arm • Android 5.1 (API 22)
    • iPhone 6s • FF0E5127-3490-4297-9313-C4776D7950D4 • ios         • iOS 10.0 (simulator)
```

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes #9262

### CODE REVIEW

File: packages/flutter_tools/lib/src/cache.dart [hunk 1]
```diff
@@ -77,7 +77,7 @@ class Cache {
   /// Checks if the current process owns the lock for the cache directory at
   /// this very moment; throws a [StateError] if it doesn't.
   static void checkLockAcquired() {
-    if (_lockEnabled && _lock == null) {
+    if (_lockEnabled && (_lock == null && platform.environment['FLUTTER_ALREADY_LOCKED'] != 'true')) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/cache.dart]: you have an extra set of `()` here than you need

**Comment by Hixie** [comment]
if you can figure out a way to test it, this is something i'd recommend testing.

other than that, assuming it works, LGTM.

File: packages/flutter_tools/lib/src/cache.dart (hunk 1 above)
Comment (yjbanov) [inline packages/flutter_tools/lib/src/cache.dart]: Done.

**Comment by yjbanov** [comment]
> if you can figure out a way to test it, this is something i'd recommend testing.

Added a test. PTAL.

File: packages/flutter_tools/test/src/cache_test.dart [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import 'context.dart';
+
+void main() {
+  group('$Cache.checkLockAcquired', () {
+    setUp(() {
+      Cache.enableLocking();
+    });
+
+    tearDown(() {
+      Cache.enableLocking();
```
Comment (Hixie) [inline packages/flutter_tools/test/src/cache_test.dart]: did you mean disable here?

**Comment by Hixie** [comment]
LGTM

File: packages/flutter_tools/test/src/cache_test.dart (hunk 2 above)
Comment (yjbanov) [inline packages/flutter_tools/test/src/cache_test.dart]: This is intentional. I want the tests to begin and end with enabled locking. The former for all tests in this group. The latter to prevent side-effects outside it. But the fact you had to ask tells me that this is not obvious. So I left a comment.
