### PR TITLE
Fix DropdownMenu escape key does not close the menu

### LINKED ISSUE #177993: DropdownMenu menu panel does not close when pressing ESC and requestFocusOnTap is false
### Steps to reproduce

1. Run the code sample.
2. Tap on the DropdownMenu to open the menu panel.
3. Press ESC key on a physical keyboard.

### Expected results

The menu panel closes.

### Actual results

The menu panel remains open.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const ReproApp());
}

final List<DropdownMenuEntry<int>> entries = List.generate(
  6,
  (int i) => DropdownMenuEntry(value: i * 200, label: '${i * 200}'),
);

class ReproApp extends StatelessWidget {
  const ReproApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(title: 'DropdownMenu ESC repro', home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: DropdownMenu(
          initialSelection: 500,
          dropdownMenuEntries: entries,
          requestFocusOnTap: false,
          textInputAction: TextInputAction.next,
          label: const Text('DropdownMenu'),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

Flutter (Channel master, 3.38.0-1.0.pre-409, on macOS 15.6.1 24G90 darwin-arm64, locale en-FR)
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes escape key not closing the menu when `DropdownMenu.requestFocusOnTap` is false.

## Related Issue

Fixes [DropdownMenu menu panel does not close when pressing ESC and requestFocusOnTap is false](https://github.com/flutter/flutter/issues/177993) 
Part of https://github.com/flutter/flutter/issues/123797
 
## Tests

- Adds 3 tests.
- Updates 2 non-related tests where I spotted some nits.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -4063,6 +4061,101 @@ void main() {
...
+      await tester.pump();
+      expect(findMenuPanel(), findsOne);
+
+      // Press ESC to close the menu.
+      await tester.sendKeyEvent(LogicalKeyboardKey.escape);
+      await tester.pump();
+      expect(findMenuPanel(), findsNothing);
+    },
+    variant: TargetPlatformVariant.all(),
+  );
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart]: I prefer to keep those tests self contained for readability and for future keyboard related test.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -4063,6 +4061,101 @@ void main() {
...
+      await tester.tap(find.byType(TextField));
+      await tester.pump();
+      expect(findMenuPanel(), findsOne);
+
+      // Press ESC to close the menu.
+      await tester.sendKeyEvent(LogicalKeyboardKey.escape);
+      await tester.pump();
+      expect(findMenuPanel(), findsNothing);
+    },
+    variant: TargetPlatformVariant.all(),
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_test.dart]: Nit: I think you shouldn't need TargetPlatformVariant.all for any of these tests, unless there's specifically platform-dependent stuff happening here. This will end up getting tested on all platforms by CI anyway.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 2 above)
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart]: I used TargetPlatformVariant.all() because those tests depends on DropdownMenu.requestFocusOnTap value which is platform dependent.

But you're right that this is not needed for the two first tests I added because in these tests DropdownMenu.requestFocusOnTap is explicitly set. I pushed a commit to remove TargetPlatformVariant.all() usage for these tests.
