### PR TITLE
Fix sliver geometry assert

### LINKED ISSUE #46871: CupertinoSliverRefreshControl generates: SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.
```
class Body extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      physics: BouncingScrollPhysics(),
      slivers: <Widget>[
        CupertinoSliverRefreshControl(
          onRefresh: () async {
            return Future<void>.delayed(
              Duration(milliseconds: 2000),
            );
          },
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return Container(
                height: 100,
                child: Text("index: $index"),
              );
            },
            childCount: 20,
          ),
        ),
      ],
    );
  }
}
```

When drag down very fast (fling down?), the above code generates the following error:

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.

The render object whose geometry violates the constraints is the following: _RenderCupertinoSliverRefresh#7a94c relayoutBoundary=up1 NEEDS-PAINT
The remainingPaintExtent is 369.3, but the paintExtent is 374.2.
The paintExtent must cause the child sliver to paint within the viewport, and so cannot exceed the remainingPaintExtent.
The relevant error-causing widget was
    CupertinoSliverRefreshControl 
lib\main.dart:30
When the exception was thrown, this was the stack
#0      RenderSliver.debugAssertDoesMeetConstraints.<anonymous closure> 
package:flutter/…/rendering/sliver.dart:1194
#1      RenderSliver.debugAssertDoesMeetConstraints 
package:flutter/…/rendering/sliver.dart:1208
#1      RenderSliver.debugAssertDoesMeetConstraints 
package:flutter/…/rendering/sliver.dart:1208
#2      RenderObject.layout.<anonymous closure> 
package:flutter/…/rendering/object.dart:1727
#3      RenderObject.layout 
package:flutter/…/rendering/object.dart:1729
#4      RenderViewportBase.layoutChildSequence 
package:flutter/…/rendering/viewport.dart:410
...
The following RenderObject was being processed when the exception was fired: _RenderCupertinoSliverRefresh#7a94c relayoutBoundary=up1 NEEDS-PAINT
RenderObject: _RenderCupertinoSliverRefresh#7a94c relayoutBoundary=up1 NEEDS-PAINT
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 369.3, overlap: -314.2, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 683.4, remainingCacheExtent: 619.3 cacheOrigin: 0.0 )
    geometry: SliverGeometry(scrollExtent: 60.0, paintExtent: 374.2, paintOrigin: -314.2, layoutExtent: 60.0, maxPaintExtent: 374.2, cacheExtent: 60.0)
        scrollExtent: 60.0
        paintExtent: 374.2
        paintOrigin: -314.2
        layoutExtent: 60.0
        maxPaintExtent: 374.2
        cacheExtent: 60.0
    child: _RenderLayoutBuilder#144f2 relayoutBoundary=up2 NEEDS-PAINT
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=411.4, 0.0<=h<=374.2)
        size: Size(411.4, 374.2)
        child: RenderPositionedBox#9538b relayoutBoundary=up3 NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0) (can use size)
            constraints: BoxConstraints(w=411.4, 0.0<=h<=374.2)
            size: Size(411.4, 374.2)
            alignment: bottomCenter
            textDirection: ltr
widthFactor: expand
            heightFactor: expand
            child: RenderPadding#5fe92 relayoutBoundary=up4 NEEDS-PAINT
                parentData: offset=Offset(191.7, 330.2) (can use size)
                constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=374.2)
                size: Size(28.0, 44.0)
                padding: EdgeInsets(0.0, 0.0, 0.0, 16.0)
                textDirection: ltr
                child: RenderOpacity#04a44 relayoutBoundary=up5 NEEDS-PAINT
                    parentData: offset=Offset(0.0, 0.0) (can use size)
                    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=358.2)
                    size: Size(28.0, 28.0)
                    opacity: 1.0
════════════════════════════════════════════════════════════════════════════════
```

flutter doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\Env\flutter
    • Framework revision 27321ebbad (33 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Env\Android\SDK
    • Java binary at: D:\Executable\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Executable\Android\AndroidStudio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

If you keep dragging a `Scrollable` with a top `CupertinoSliverRefreshControl` down, eventually it will assert incorrectly.
For `CupertinoSliverRefreshControl`s the paintOrigin can be a negative number with big absolute value so the bug is easily reproducible with it. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/46871

## Tests

I added the following tests:

- Does not crash when paintExtent > remainingPaintExtent

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_persistent_header.dart [hunk 1]
```diff
@@ -373,14 +373,15 @@ abstract class RenderSliverPinnedPersistentHeader extends RenderSliverPersistent
     final bool overlapsContent = constraints.overlap > 0.0;
     excludeFromSemanticsScrolling = overlapsContent || (constraints.scrollOffset > maxExtent - minExtent);
     layoutChild(constraints.scrollOffset, maxExtent, overlapsContent: overlapsContent);
-    final double layoutExtent = (maxExtent - constraints.scrollOffset).clamp(0.0, constraints.remainingPaintExtent) as double;
+    final double effectiveRemainingPaintExtent = math.max(0, constraints.remainingPaintExtent - constraints.overlap);
+    final double layoutExtent = (maxExtent - constraints.scrollOffset).clamp(0.0, effectiveRemainingPaintExtent);
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_persistent_header.dart]: in preparation for NNBD you'll have to keep the "as double" here.

File: packages/flutter/lib/src/rendering/sliver_persistent_header.dart [hunk 2]
```diff
@@ -373,14 +373,15 @@ abstract class RenderSliverPinnedPersistentHeader extends RenderSliverPersistent
     final bool overlapsContent = constraints.overlap > 0.0;
     excludeFromSemanticsScrolling = overlapsContent || (constraints.scrollOffset > maxExtent - minExtent);
     layoutChild(constraints.scrollOffset, maxExtent, overlapsContent: overlapsContent);
-    final double layoutExtent = (maxExtent - constraints.scrollOffset).clamp(0.0, constraints.remainingPaintExtent) as double;
+    final double effectiveRemainingPaintExtent = math.max(0, constraints.remainingPaintExtent - constraints.overlap);
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_persistent_header.dart]: Why do we need to reduce the paintExtent by the overlap?

AFAIK you can paint into the area that's overlapped by a previous sliver.

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/sliver_persistent_header.dart]: For future reference: because we set the paintOrigin below to overlap.

**Review by goderbauer — APPROVED** [review]
LGTM
