### PR TITLE
RenderViewport max layout cycles should depend on number of slivers

### LINKED ISSUE #144102: RenderViewport maxLayoutCycles should depend on number of slivers in viewport
In [super_sliver_list](https://superlistapp.github.io/super_sliver_list) we rely on `scrollOffsetCorrection` to account for the difference between estimated and actual extent. In some corner cases, for example when the viewport is initially scrolled to end, this may result in one correction per `SuperSliverList` during initial layout. 

The problem is that `RenderViewport` currently caps the maximum number of of layout cycles to 10, regardless of number of slivers. In case where there is a large amount of very short slivers, this may throw an exception, even though each sliver only requested at most one correction.

Ideally we'd want to track the number of correction requests per `Sliver`, but that's little bit difficult because slivers can be nested (i.e. `SliverMainAxisGroup`) and `SliverGeometry` propagated from child slivers does not carry the original sliver that requested the correction. 

Less ideal but much easier solution would be to replace `_maxLayoutCycles` with `_maxLayoutCyclesPerChild` and then multiply it with number of viewport children:

```dart
void performLayout() {
  ...
  final int maxLayoutCycles = _maxLayoutCyclesPerChild * childCount;
  ...
```
While not perfect, this would still be a significant improvement. We could potentially reduce the value of `_maxLayoutCyclesPerChild` from 10 because it will be multiplied by the amount of child slivers.

cc @Piinks

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/144102

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 1]
```diff
@@ -1399,7 +1399,7 @@ class RenderViewport extends RenderViewportBase<SliverPhysicalContainerParentDat
     return constraints.biggest;
   }
 
-  static const int _maxLayoutCycles = 10;
+  static const int _maxLayoutCyclesPerChild = 10;
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/viewport.dart:1402]: Should this be a little lower now that it is per child? Before a viewport with 3 sliver children would allow 10 passes, now it would be 30.

**Review by Piinks — COMMENTED** [review]
Hey @knopp! Thanks for the PR!

I don't recall why it is 10, and I tracked it all the way down to https://github.com/flutter/flutter/pull/7790, which did not give much insight either. :)
Maybe @Hixie knows.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (knopp) [reply packages/flutter/lib/src/rendering/viewport.dart:1402]: I don't think any reasonable sliver would need more than a handful of passes, the problem is that you can have nested slivers in [MultiSliver](https://pub.dev/documentation/sliver_tools/latest/sliver_tools/MultiSliver-class.html) or even `SliverMainAxisGroup` (but I don't think that one properly propagates `scrollOffsetCorrection`?) and we have no good way to count correction count per actual source sliver. For that we would probably need changes to `SliverGeometry`.

So lowering the `mainLayoutCycles` could potentially be breaking change for someone that has nested slivers.

More importantly I do think that the check is meant to detect pathological cases where the layout is stuck in a loop of corrections, and as such it does matter if it is 10 passes or 30? It will throw an exception anyway so it is not something that happens during regular layout pass.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart:1402]: SGTM, thanks for explaining your thinking here. :)

**Review by Piinks — COMMENTED** [review]
Flutter_LGTM

Is there an issue filed for SliverMainAxisGroup not handling the correction? We should follow up on that. :)

**Comment by knopp** [comment]
@Piinks, seems like maybe you still need to approve the PR? :)

I'll create issue for `SliverMainAxisGroup`.

**Review by Piinks — APPROVED** [review]
Oh sorry about that! I had that happen a couple times last week. 🙃
