### PR TITLE
Actually consume top padding in bottomsheet if scrollcontrolled

### LINKED ISSUE #39205: ModalBottomSheet with isScrollControlled doesn't respect SafeArea
## Steps to Reproduce

1. Create a modal bottom sheet with Scaffold as its child
2. Wrap the Scaffold into a SafeArea widget
3. Add a Text widget in Scaffold's body
4. Run the application on a device with notch
5. Open the modal bottom sheet and notice that the text is under the status bar

## Code example
```
import 'package:flutter/material.dart';

class ModalBottomSheet extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showModalBottomSheet(
              context: context,
              isScrollControlled: true,
              builder: (context) {
                return SafeArea(
                  child: Scaffold(
                    backgroundColor: Colors.black45,
                    body: Text(
                      'Text in safe area',
                      style: TextStyle(backgroundColor: Colors.red),
                    ),
                  ),
                );
              });
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

```

## Screenshots
Screen Shot 2019-08-25 at 12 44 39 PM

## Logs

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/user/flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xs Max             • 9C9C7B29-18A5-4D3A-8F53-CE6EB58C5411 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by Kavantix**
## Description

Currently `showModalBottomSheet` always removes the top padding from the `MediaQuery` since it would be 'consumed' since the bottomsheet wont span the entire height of the window.
This is however only correct if the sheet is not scroll controlled, because if it is scroll controlled then the bottomsheet will get a maximum size of the whole window again.
So this PR makes `showModalBottomSheet` actually consume the padding if the bottomsheet is scrollcontrolled.

## Related Issues

Fixes #39205

## Tests

I added the following tests:

- Updated the name of the old test to indicate that it should only happen if not scroll controlled
- Added a new test that checks that the bottomsheet is inset by the top padding

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

Not sure if this is considered a breaking, I don't think any tests will fail but anyone that is using a workaround like proposed in #39205 will get a double padding by this fix

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Kavantix** [comment]
Not sure if this is considered a breaking, I don't think any tests will fail but anyone that is using a workaround like proposed in #39205 will get a double padding by this fix

**Comment by Piinks** [comment]
> Not sure if this is considered a breaking, I don't think any tests will fail but anyone that is using a workaround like proposed in #39205 will get a double padding by this fix

This does not break any existing flutter or customer tests, so it does not appear to be breaking. :) Once approved, we can run it through google testing to be sure.

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 1]
```diff
@@ -567,6 +572,8 @@ class _BottomSheetSuspendedCurve extends ParametricCurve<double> {
 /// to have a bottom sheet that has a scrollable child such as a [ListView] or
 /// a [GridView] and have the bottom sheet be draggable, you should set this
 /// parameter to true.
+/// When this parameter is set to true the top of [BottomSheet] will be padded
```
Comment (Piinks) [inline packages/flutter/lib/src/material/bottom_sheet.dart:575]: This can be part of the same paragraph. Otherwise we usually put a line break in between paragraphs.
```suggestion
/// parameter to true. When this parameter is set to true the top of [BottomSheet] will be padded
```

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 2]
```diff
@@ -482,6 +482,11 @@ class _ModalBottomSheetRoute<T> extends PopupRoute<T> {
         enableDrag: enableDrag,
       ),
     );
+    if (isScrollControlled)
```
Comment (Piinks) [inline packages/flutter/lib/src/material/bottom_sheet.dart:485]: Instead of removing the padding and then adding it back, could line#474 above be 
```dart
removeTop: !isScrollControlled
```

Comment (Kavantix) [reply packages/flutter/lib/src/material/bottom_sheet.dart:485]: That would be an option although it does have a different effect.
With the version in this PR the padding is handled by the bottomsheet route.
If we would change it to remove top false for isScrollControlled than every user of the bottomsheet needs to account for it themselves (but only for the scroll controlled ones)

Comment (Piinks) [reply packages/flutter/lib/src/material/bottom_sheet.dart:485]: Ah I see, thank you for explaining!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thanks for the contribution!

**Comment by Piinks** [comment]
Triage note: I'm waiting on the google testing shard to start before applying the auto-merge label.

**Comment by Piinks** [comment]
@Kavantix it looks like this wasn't merged due to a tree closure, and now there are merge conflicts. Can you update this so we can land your change? Thank you!

**Comment by Kavantix** [comment]
@Piinks just rebased it on master
