### PR TITLE
[iOS] Add Live Text option to system context menu

### LINKED ISSUE #169781: OCR option not showing in native text field menu after Secure Paste M2 implementation
After the merge of the Secure Paste M2 milestone (tracked in #159013), the OCR (Text from Camera) option is no longer showing by default in the iOS native text field context menu.

Previously, the Flutter text editing menu supported OCR as discussed in [#96637](https://github.com/flutter/flutter/issues/96637). This functionality appears to be missing or unhooked after the secure paste implementation.

Expected Behavior:
When long-pressing on a TextField, iOS should show the "Text from Camera" (OCR) option as it did previously.

Actual Behavior:
The OCR option is not visible or accessible in the text field context menu on iOS.

Steps to Reproduce:

Use a TextField widget on iOS.

Long press to open the context menu.

Observe that the OCR option is missing.

Reference Issues/PRs:

Related implementation: [#140184](https://github.com/flutter/flutter/issues/140184)

Original OCR support discussion: [#96637](https://github.com/flutter/flutter/issues/96637)

Secure Paste Phase 2: [flutter/flutter#159013](https://github.com/flutter/flutter/pull/159013)

### PR DESCRIPTION
**Pull request by jingshao-code**
**Live Text (OCR) button disappeared from text field menus on iOS after the Secure Paste M2 update. This PR adds it back.**

**Fixes #169781**

Note: This is a draft PR for initial review. Still need to add tests or split to framework and engine

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by jingshao-code** [comment]
Hi @justinmc @hellohuanlin ,
Draft PR ready for initial review.
Note: CI failing on SDK analysis seems unrelated to my changes.

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 1]
```diff
@@ -414,5 +415,34 @@ final class IOSSystemContextMenuItemShare extends IOSSystemContextMenuItem with
...
+final class IOSSystemContextMenuItemLiveText extends IOSSystemContextMenuItem {
+  /// Creates an instance of [IOSSystemContextMenuItemLiveText].
+  const IOSSystemContextMenuItemLiveText();
+
+  @override
+  String get title => 'captureTextFromCamera';
+
+  @override
+  IOSSystemContextMenuItemData getData(WidgetsLocalizations localizations) {
+    return IOSSystemContextMenuItemDataLiveText(
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/system_context_menu.dart]: I think this should be const per the analyzer failure.

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 2]
```diff
@@ -414,5 +415,34 @@ final class IOSSystemContextMenuItemShare extends IOSSystemContextMenuItem with
...
+      title: 'Scan Text',
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/system_context_menu.dart]: This should be a localized string (when the PR is finalized).

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 3]
```diff
@@ -414,5 +415,34 @@ final class IOSSystemContextMenuItemShare extends IOSSystemContextMenuItem with
   }
 }
 
+/// Creates an instance of [IOSSystemContextMenuItem] for the
+/// system's built-in Live Text button.
+///
+/// Should only appear when the text field is not secure, has focus, and has
+/// no selection.
+///
+/// The title and action are both handled by the platform.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/system_context_menu.dart:422]: I guess the title will be similar to other buttons, not handled by the platform? See above for share:

```
/// The [title] is optional, but it must be specified before being sent to the
/// platform. Typically it should be set to
/// [WidgetsLocalizations.shareButtonLabel].
```

Where this would also need its own localized string, if we don't have one already.

File: packages/flutter/lib/src/services/text_input.dart [hunk 4]
```diff
@@ -3044,5 +3044,30 @@ final class IOSSystemContextMenuItemDataShare extends IOSSystemContextMenuItemDa
   }
 }
 
+/// A [IOSSystemContextMenuItemData] for the system's built-in Live Text
+/// (OCR) button.
+///
+/// This button is only available on iOS 15.0+ devices with camera support.
+///
+/// The title and action are both handled by the platform. The default title
+/// is "Scan Text" and is localized by the platform.
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart]: Similar to my other comment about the title, I think it won't be localized by the platform, but will be localized by the framework.

File: packages/flutter/lib/src/services/text_input.dart [hunk 5]
```diff
@@ -3044,5 +3044,30 @@ final class IOSSystemContextMenuItemDataShare extends IOSSystemContextMenuItemDa
...
+  @override
+  final String title;
+
+  @override
+  String get _jsonType => 'captureTextFromCamera';
+
+  @override
+  String toString() {
+    return 'IOSSystemContextMenuItemDataLiveText(title: $title)';
+  }
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart]: This should be debugFillProperties from Diagnosticable instead. Recently I ported the IOSSystemContextMenuItem subclasses to use Diagnosticable, I didn't realize I had missed these.

**Review by justinmc — COMMENTED** [review]
The approach looks good to me! Minus some small comments and missing tests.

I was struggling to build the engine with Xcode 26, so I wasn't able to try this locally for now. I'm going to go back to 16.4 and try again.

*Edit*: I was able to get this to run locally with Xcode 16.4, and everything worked as expected 👍 .

File: packages/flutter/lib/src/services/text_input.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/services/text_input.dart]: I put up a PR: https://github.com/flutter/flutter/pull/171028

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 6]
```diff
@@ -1314,6 +1322,14 @@ - (BOOL)canPerformAction:(SEL)action withSender:(id)sender {
     return [self textInRange:_selectedTextRange].length > 0;
   } else if (action == @selector(selectAll:)) {
     return self.hasText;
+  } else if (action == @selector(captureTextFromCamera:)) {
+    if (@available(iOS 15.0, *)) {
+      BOOL isSecure = self.isSecureTextEntry;
+      BOOL hasSelection = _selectedTextRange.empty;
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: 1. should it be `hasNoSelection`? 
2. why do we need to check this?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 7]
```diff
@@ -1345,6 +1361,14 @@ - (void)selectAll:(id)sender {
                                               toPosition:[self endOfDocument]]];
 }
 
+- (void)captureTextFromCamera:(id)sender {
+  if (@available(iOS 15.0, *)) {
+    if ([super respondsToSelector:@selector(captureTextFromCamera:)]) {
+      [super captureTextFromCamera:sender];
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: <s>No need to check resopndsToSelector - will be a no-op if it doesn't </s>

Can remove this whole method, because it's already defined in its superclass (UIResponder)

File: packages/flutter/lib/src/widgets/system_context_menu.dart (hunk 2 above)
Comment (hellohuanlin) [reply packages/flutter/lib/src/widgets/system_context_menu.dart]: I think we can pass in null title here - the native menu has it (similar to copy/paste/select actions, but different from lookup/share/search web actions)

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 6 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Can you double check the behavior on a native iOS app and see what's the condition of showing camera button?

**Review by hellohuanlin — COMMENTED** [review]
Reviewed the engine part

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 6 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Curious does the camera button require permission? If it does, worth checking the behavior when we deny the permission. Otherwise ignore this message.

File: packages/flutter/lib/src/widgets/system_context_menu.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/system_context_menu.dart]: Ah that's right. Sounds good to me.

File: packages/flutter/lib/src/widgets/system_context_menu.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/system_context_menu.dart:422]: Actually per @hellohuanlin's comment above (https://github.com/flutter/flutter/pull/170969#discussion_r2162355299), this should not localize the string in the framework.

File: packages/flutter/lib/src/services/text_input.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/services/text_input.dart]: I was wrong here, see https://github.com/flutter/flutter/pull/170969#discussion_r2162355299.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 6 above)
Comment (jingshao-code) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: > 1. should it be `hasNoSelection`?
> 2. why do we need to check this?

1. fixed to '`hasNoSelection'
2. About the checks:
I looked at how other actions work in the text field menu
- 'hasNoSelection': Live Text needs to insert
- 'isFocused': needed so text goes to the right field
- '!isSecure': I added this for security, but not sure if needed

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 8]
```diff
@@ -728,4 +728,25 @@ void main() {
...
+      const WidgetsLocalizations localizations = DefaultWidgetsLocalizations();
+      final IOSSystemContextMenuItemData data = item.getData(localizations);
+      expect(data, isA<IOSSystemContextMenuItemDataLiveText>());
+      expect((data as IOSSystemContextMenuItemDataLiveText).title, isNull);
+    },
+  );
+
+  test('IOSSystemContextMenuItemDataLiveText debugFillProperties', () {
+    const String? title = null;
+    const IOSSystemContextMenuItemDataLiveText item = IOSSystemContextMenuItemDataLiveText(title: title);
```
Comment (justinmc) [inline packages/flutter/test/widgets/system_context_menu_test.dart]: You're getting an analyzer failure here because `null` is the default value, so you don't need to pass it.

**Review by justinmc — COMMENTED** [review]
I left a comment about the analyzer failure, and there also seems to be a formatting failure in FlutterTextInputPluginTest.mm.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 6 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Discussed offline - we can simply return YES here. The logic is already done by the framework. 

We have checks for other selectors (e.g. copy/paste) because they can be triggered by keyboard shortcut.

Comment (jingshao-code) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Thanks for the offline discussion! I've simplified the implementation to just return YES in commit 9c7b184.

File: packages/flutter/test/widgets/system_context_menu_test.dart (hunk 8 above)
Comment (jingshao-code) [reply packages/flutter/test/widgets/system_context_menu_test.dart]: Fixed in 9c7b184! Removed the unnecessary null assignment.

**Comment by jingshao-code** [comment]
Fixed the failing test in bf114d6 - updated to match the simplified implementation.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 7 above)
Comment (jingshao-code) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Done in 4373b36! Removed the unnecessary method override.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm [hunk 9]
```diff
@@ -3869,4 +3869,22 @@ - (void)testInteractiveKeyboardShowKeyboardAndRemoveScreenshotAnimationIsReenabl
   [self waitForExpectations:@[ expectation ] timeout:10.0];
 }
 
+- (void)testCanPerformActionCaptureTextFromCamera {
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm]: 1. if you need to create a new test, please move it close to the context menu tests. 
2. Can you modify the existing test case related to context menu?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm [hunk 10]
```diff
@@ -3869,4 +3869,22 @@ - (void)testInteractiveKeyboardShowKeyboardAndRemoveScreenshotAnimationIsReenabl
...
+  if (@available(iOS 15.0, *)) {
+    NSDictionary* config = self.mutableTemplateCopy;
+    [self setClientId:123 configuration:config];
+    NSArray<FlutterTextInputView*>* inputFields = self.installedInputViews;
+    FlutterTextInputView* inputView = inputFields[0];
+
+    // Live Text is always available on iOS 15+ per framework logic
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm]: it isn't clear what this means to me. On framework logic, it's not always available

File: packages/flutter/lib/src/services/text_input.dart [hunk 11]
```diff
@@ -3062,5 +3062,32 @@ final class IOSSystemContextMenuItemDataShare extends IOSSystemContextMenuItemDa
...
+/// provided, the platform will use its default localized title.
+///
+/// See https://github.com/flutter/flutter/issues/169781
+final class IOSSystemContextMenuItemDataLiveText extends IOSSystemContextMenuItemData
+    with Diagnosticable {
+  /// Creates an instance of [IOSSystemContextMenuItemDataLiveText].
+  const IOSSystemContextMenuItemDataLiveText({this.title});
+
+  @override
+  final String? title;
```
Comment (hellohuanlin) [inline packages/flutter/lib/src/services/text_input.dart]: as discussed in my previous message, title isn't needed here. Please follow the example of copy/paste/select actions.

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 12]
```diff
@@ -728,4 +728,23 @@ void main() {
     expect(diagnosticsNodes.first.name, 'title');
     expect(diagnosticsNodes.first.value, title);
   });
+
+  test(
+    'can get the IOSSystemContextMenuItemData representation of an IOSSystemContextMenuItemLiveText',
```
Comment (hellohuanlin) [inline packages/flutter/test/widgets/system_context_menu_test.dart]: please move this test case closer to other similar tests

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm (hunk 10 above)
Comment (jingshao-code) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm]: I have removed this inaccurate comment. The framework does check the conditions before enabling Live Text.

File: packages/flutter/test/widgets/system_context_menu_test.dart (hunk 12 above)
Comment (jingshao-code) [reply packages/flutter/test/widgets/system_context_menu_test.dart]: Thanks for reviewing! All comments addressed:

- Moved tests next to similar tests
- No title parameter (follows copy/paste/select pattern)

**Review by hellohuanlin — APPROVED** [review]
Engine side LGTM. Please wait for @justinmc's framework side approval before landing it.

File: packages/flutter/lib/src/services/text_input.dart [hunk 13]
```diff
@@ -3062,5 +3062,34 @@ final class IOSSystemContextMenuItemDataShare extends IOSSystemContextMenuItemDa
   }
 }
 
+/// A [IOSSystemContextMenuItemData] for the system's built-in Live Text
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:3061]: "A" => "An"

File: packages/flutter/lib/src/services/text_input.dart [hunk 14]
```diff
@@ -3062,5 +3062,34 @@ final class IOSSystemContextMenuItemDataShare extends IOSSystemContextMenuItemDa
...
+  /// Creates an instance of [IOSSystemContextMenuItemDataLiveText].
+  const IOSSystemContextMenuItemDataLiveText();
+
+  @override
+  String get _jsonType => 'captureTextFromCamera';
+
+  @override
+  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
+    super.debugFillProperties(properties);
+  }
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart]: I guess now that there is no title here, Diagnosticable is not needed.

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 15]
```diff
@@ -699,6 +701,28 @@ void main() {
...
+      final IOSSystemContextMenuItemData data = item.getData(localizations);
+      expect(data, isA<IOSSystemContextMenuItemDataLiveText>());
+    },
+  );
+
+  test('IOSSystemContextMenuItemDataLiveText debugFillProperties', () {
+    const IOSSystemContextMenuItemDataLiveText item = IOSSystemContextMenuItemDataLiveText();
+    final List<DiagnosticsNode> diagnosticsNodes = item.toDiagnosticsNode().getProperties();
+    expect(diagnosticsNodes, hasLength(0));
+  });
```
Comment (justinmc) [inline packages/flutter/test/widgets/system_context_menu_test.dart]: Also this wouldn't be necessary anymore if you remove Diagnosticable from the class.

**Review by justinmc — COMMENTED** [review]
Some very small changes here, otherwise looks good.

File: packages/flutter/lib/src/services/text_input.dart (hunk 13 above)
Comment (jingshao-code) [reply packages/flutter/lib/src/services/text_input.dart:3061]: I noticed that all other `IOSSystemContextMenuItemData` subclasses in this file use "A" rather than "An" in their documentation. Should I keep it as "A" for consistency with the existing pattern, or would you prefer I change just this one to "An"?

Comment (justinmc) [reply packages/flutter/lib/src/services/text_input.dart:3061]: Whoops that must be my grammar mistake then 😅 

Would you be able to change all of them in a separate PR?

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/services/text_input.dart (hunk 13 above)
Comment (jingshao-code) [reply packages/flutter/lib/src/services/text_input.dart:3061]: Done! Created #172019 to fix all the grammar issues
