### PR TITLE
Reland "[null-safety] reland: migrate app side flutter driver to null-safety"

### LINKED ISSUE #67560: Flutter driver appears to be broken on web
This is causing tree closures on engine and plugins

/cc @jonahwilliams (because I think it might be related to your nullsafety PR)

@jason-simmons is bisecting right now AFAIK.

/cc @zanderso @liyuqian @yjbanov

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#67561

Fixes insertion of `null` string into message data which crashed integration with web driver. Adds unit test to cover

Fixes https://github.com/flutter/flutter/issues/67560

### CODE REVIEW

File: packages/flutter_driver/lib/src/common/request_data.dart [hunk 1]
```diff
@@ -26,7 +26,8 @@ class RequestData extends Command {
 
   @override
   Map<String, String> serialize() => super.serialize()..addAll(<String, String>{
-    'message': message,
+    if (message != null)
```
Comment (jonahwilliams) [inline packages/flutter_driver/lib/src/common/request_data.dart:29]: This is the fix

File: packages/flutter_driver/test/src/real_tests/request_data_test.dart [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+// found in the LICENSE file.
+
+// @dart = 2.8
+
+import 'package:flutter_driver/flutter_driver.dart';
+
+import '../../common.dart';
+
+void main() {
+  test('RequestData does not insert "null" string when no message is provided', () {
```
Comment (jonahwilliams) [inline packages/flutter_driver/test/src/real_tests/request_data_test.dart:12]: Unit test for this

File: packages/flutter_driver/lib/src/common/request_data.dart (hunk 1 above)
Comment (ditman) [reply packages/flutter_driver/lib/src/common/request_data.dart:29]: Ahhh, OK, I was misunderstanding the `!` because I wasn't seeing the != null around it; it's used to remove the `?` from the type of the variable. Cool beans!

**Review by ditman — APPROVED** [review]
Manually tested this on my local repro of #67560, it seems to do the trick!!

**Review by goderbauer — APPROVED** [review]
LGTM
