### PR TITLE
Fix visibility of web server device when Chrome is not available

### LINKED ISSUE #40814: flutter run -d server fails when Chrome not present
I'm in the process of attempting to run Flutter tooling alongside the VS Code in the Cloud product [code-server](https://github.com/cdr/code-server). I can install the `flutter` tooling, change to master, upgrade, and set the config to enable web, but then attempting to run just the server fails.

```bash
$ flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.4-pre.72, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.4-pre.72 at /home/coder/flutter
    • Framework revision 4c724b9b7d (2 hours ago), 2019-09-18 21:48:41 -0400
    • Engine revision 7f7250f476
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 cb80ea7ba9)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! CHROME_EXECUTABLE not set

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • unknown (unsupported)
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
$ flutter config
Configure Flutter settings.

[Elided help output - bjm]

Settings:
  enable-web: true

Analytics reporting is currently enabled.
$ flutter run -d server
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

### PR DESCRIPTION
**Pull request by DanTup**
This removes the requirement of finding Chrome for all web devices, but does check it before providing the Chrome device.

Fixes #40814.

### CODE REVIEW

**Comment by DanTup** [comment]
I pushed some changes to the workflow test to remove the assumption that it can't list devices if there's no Chrome - however I'm not sure if this is the best way to change it (it's not clear if returning true for some flags when `appliesToHostPlatform=false` is valid - it seems like others do, but it means `appliesToHostPlatform` always needs checking before making assumptions about the other capabilities).

File: packages/flutter_tools/lib/src/web/web_device.dart [hunk 1]
```diff
@@ -165,7 +166,8 @@ class WebDevices extends PollingDeviceDiscovery {
   @override
   Future<List<Device>> pollingGetDevices() async {
     return <Device>[
-      _webDevice,
+      if (_chromeIsAvailable)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/web_device.dart]: This seems reasonable

**Review by jonahwilliams — APPROVED** [review]
The flags on Workflow are a bit weird, I agree. This seems correct though, its similar to an Android device discoverer having a valid SDK but no connected device.

LGTM

**Comment by DanTup** [comment]
@jonahwilliams test failures were due to the tests relying on Chrome actually being on the underlying machine (because there were two checks - that we can find it, and that we can run it). I've pushed a change that moves `canFindChrome` onto `ChromeLauncher` so I could mock it in the tests - PTAL! 2c31a799414bac817f687efb171992716c68a49f

**Comment by DanTup** [comment]
@jonahwilliams I'm out the office shortly for a week so if you're happy with the extra change I pushed, feel free to merge in my absence (@domesticmouse may be happy having the fix to try out :-))

**Comment by DanTup** [comment]
@jonahwilliams ping! Still looking for confirmation of the changes I pushed (2c31a79) to resolve the test issues.

**Review by jonahwilliams — APPROVED** [review]
LGTM!
