### PR TITLE
Have `FocusManager` respond to app lifecycle state changes

### LINKED ISSUE #87061: Even if desktop app is inactive, the cursor is still blinking
If the textfield has acquired focus before the desktop app is inactive, the cursor will still blink when the app is inactived.

Since we don't offer to check if the app is active at the moment, we can't solve it for now.

@justinmc

### LINKED ISSUE #142929: `FocusManager` does not respond to changes in app lifecycle state
### Steps to reproduce

1. Open a Flutter app in Windows, MacOS, or Google Chrome
2. Click on a `TextField` (or any other widget that uses a `FocusNode`)
3. Click away from the window, and notice that the cursor doesn't stop blinking.

### Expected results

It doesn't matter whether I'm using Google Chrome, VS Code, Discord, or a Terminal window: any time a text cursor is blinking, it means that the characters I type will show up there.

And this isn't limited to text fields: if I repeatedly press `Tab` to navigate through a website, there's a visual indicator that goes away if I click away from the window, and it comes back if I click or `Alt+Tab` back into it.

### Actual results

Flutter apps do not follow this pattern.

### Code sample

```dart
Widget build(BuildContext context) {
  return TextField();
}
```

### Screenshots or Video

<details open>
<summary>GIF demonstration</summary>

Here's a recording of a Chrome window, as an example of how Flutter should behave:
focus node

</details>

I've already implemented a fix and have opened a pull request: #142930

### PR DESCRIPTION
**Pull request by nate-thegrate**
fixes #87061

It doesn't matter whether I'm using Google Chrome, VS Code, Discord, or a Terminal window: any time a text cursor is blinking, it means that the characters I type will show up there.

And this isn't limited to text fields: if I repeatedly press `Tab` to navigate through a website, there's a visual indicator that goes away if I click away from the window, and it comes back if I click or `Alt+Tab` back into it.

<details open>
<summary>Example (Chrome):</summary>

focus node

</details>

<details open>
<summary>This PR adds the same functionality to Flutter apps:</summary>

Flutter demo

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -1682,6 +1684,27 @@ class FocusManager with DiagnosticableTreeMixin, ChangeNotifier {
   // update.
   final Set<FocusNode> _dirtyNodes = <FocusNode>{};
 
+  // Stores the node that was focused before the app lifecycle changed.
+  // Will be restored as the primary focus once app is resumed.
```
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/focus_manager.dart:1688]: Thanks very much for catching this!

**Comment by nate-thegrate** [comment]
@gspencergoog the `FocusManager` class is updated, and I added a test to cover detaching a suspended node.

Thanks for your help, and let me know if we need anything else!

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 2]
```diff
@@ -1682,6 +1684,27 @@ class FocusManager with DiagnosticableTreeMixin, ChangeNotifier {
...
+      if (_suspendedNode != null) {
+        assert(_focusDebug(() => 'marking node $_suspendedNode to be focused'));
+        _markedForFocus = _suspendedNode;
+        _suspendedNode = null;
+        applyFocusChangesIfNeeded();
+      }
+    } else if (_primaryFocus != rootScope) {
+      assert(_focusDebug(() => 'suspending $_primaryFocus'));
+      _markedForFocus = rootScope;
+      _suspendedNode = _primaryFocus;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/focus_manager.dart:1703]: What should happen if something changes the focus while the app is not in "resumed" mode? (Imagine a timer being set to return focus to something at a later time.) Should setting the primary focus to something other than the `rootScope` modify the `_suspendedNode`, or should it clear it and set the primary focus?

Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/focus_manager.dart:1703]: That's a really good question. I'm not aware of an app that changes focus on a timer, so there probably isn't a precedent to follow.

But if a developer implements a feature that can change the focus without user input, it probably makes sense to just let it happen, i.e. null out the `_suspendedNode` and set the primary focus. I'll update this function accordingly.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart:1707]: Well, it doesn't have to be as simple as a timer, I was just thinking of the simplest way to describe the issue. For a more real-world case, Imagine a slide-in animation that sets the focus on a text field when the animation is done.  If you switch the focus away during the animation, this would also cause the same problem.

Your solution looks good, though.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart:1707]: One thing just occurred to me, though: we might not want to expose `didChangeAppLifecycleState` as a public function on the `FocusManager`, since it's not really something that should be called outside of the binding.  Perhaps it would be better aggregate instead of inherit here: create a private class that extends `WidgetsBindingObserver` and let the `FocusManager` have a private instance of that class.

Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/focus_manager.dart:1721]: done!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks for doing this!

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 3]
```diff
@@ -1446,6 +1446,16 @@ enum FocusHighlightStrategy {
   alwaysTraditional,
 }
 
+// By extending the WidgetsBindingObserver class,
+// we can add a listener object to FocusManager as a private member.
+class _AppLifecycleListener extends WidgetsBindingObserver {
+  _AppLifecycleListener(this.onLifecycleStateChanged);
+  final void Function(AppLifecycleState) onLifecycleStateChanged;
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/focus_manager.dart:1453]: Is Flutter's style to have an empty line between the constructor and member?

```suggestion
  _AppLifecycleListener(this.onLifecycleStateChanged);

  final void Function(AppLifecycleState) onLifecycleStateChanged;
```

**Review by loic-sharma — APPROVED** [review]
Thanks for the excellent contribution!

**Comment by nate-thegrate** [comment]
That's unfortunate to hear.

If the keyboard can trigger a lifecycle state change on some devices but not on others, hopefully that can get fixed soon.

I agree that for now it makes sense to revert this merge, or maybe add a platform check when activating the listener.

**Comment by gspencergoog** [comment]
I like the idea of a platform check more than just reverting it.  This is a good change for desktop platforms especially.

Let's wait and see what the team comes up with for a reproduction case so we can see what the extent of it is. So far it seems to be on specific mobile devices only. My suspicion is that there's an OEM onscreen keyboard that isn't coded similarly to other keyboards, and acts more like a separate app, causing a lifecycle change when it takes focus.
