### PR TITLE
fix install checks in flavors devicelab tests

### LINKED ISSUE #133713: devicelab test for `flutter install` with an invalid `--flavor` cannot fail
There is a check in flavors_test.dart that can never fail, even when it should. There are also similar checks in flavors_test_ios.dart and flavors_test_macos, but the rest of this text will focus on flavors_test.dart for the sake of brevity.

See https://github.com/flutter/flutter/blob/609fe35f1308c7dc9c52e671927862d0df787029/dev/devicelab/bin/tasks/flavors_test.dart#L17.

This block effectively contains captures two checks:

1. That `flutter install` and `flutter install --uninstall-only` works when `--flavor` is used ([code](https://github.com/flutter/flutter/blob/609fe35f1308c7dc9c52e671927862d0df787029/dev/devicelab/bin/tasks/flavors_test.dart#L18-L25)), and
2. That `flutter install` fails when given an invalid `--flavor` ([code](https://github.com/flutter/flutter/blob/609fe35f1308c7dc9c52e671927862d0df787029/dev/devicelab/bin/tasks/flavors_test.dart#L27-L38)) (and that the error message is useful).

In the second test, we return `TaskResult.failure('Should not succeed with bogus flavor');` if the check fails. However, this result isn't used. To demonstrate, you can move this can invert the condition of the `if` statement containing the `return TaskResult.failure` statement, and the test will still pass.

You can run the test locally from the `dev/devicelab` directory using this command:
```
../../bin/cache/dart-sdk/bin/dart bin/test_runner.dart test -t flavors_test
```
You may need to set `ANDROID_SDK_ROOT` before this. See dev/devicelab/README.md for more details.

Ideally, the fix would be to capture the return value of the `inDirectory` call and return that.

**Other issues:**
* `flavors_test` (meant for Android devices) doesn't test for the correct error string when trying to build with an invalid flavor (`--flavor bogus`). It [tests for Xcode output](https://github.com/flutter/flutter/blob/609fe35f1308c7dc9c52e671927862d0df787029/dev/devicelab/bin/tasks/flavors_test.dart#L35), which will never be found because the test isn't building for iOS or MacOS
* `flavors_test_ios` tests for Xcode output, but [it tests for an outdated string](https://github.com/flutter/flutter/blob/609fe35f1308c7dc9c52e671927862d0df787029/dev/devicelab/bin/tasks/flavors_test_ios.dart#L35C2-L35C2)

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #133713 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/flavors_test.dart [hunk 1]
```diff
@@ -32,12 +34,14 @@ Future<void> main() async {
...
+      if (!stderrString.contains('"build/app/outputs/flutter-apk/app-bogus-release.apk" does not exist.')) {
         print(stderrString);
         return TaskResult.failure('Should not succeed with bogus flavor');
       }
+
+      return TaskResult.success(null);
     });
 
-    return TaskResult.success(null);
+    return installTestsResult;
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/flavors_test.dart:45]: and this value gets validated by the runner? I checked out the code and looked at it, and was pretty confused.

File: dev/devicelab/bin/tasks/flavors_test.dart [hunk 2]
```diff
@@ -13,8 +13,9 @@ Future<void> main() async {
   await task(() async {
     await createFlavorsTest().call();
     await createIntegrationTestFlavorsTest().call();
-    // test install and uninstall of flavors app
-    await inDirectory('${flutterDirectory.path}/dev/integration_tests/flavors', () async {
+
+    final TaskResult installTestsResult = await inDirectory(
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/flavors_test.dart:17]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation

On the second line (18) here, the indent should just be 2 more than line 17, and then the start of the callback should be on a new line (19) indented the same as line 18, and then the rest of the callback body indented +2.

File: dev/devicelab/bin/tasks/flavors_test_ios.dart [hunk 3]
```diff
@@ -14,7 +14,8 @@ Future<void> main() async {
     await createFlavorsTest().call();
     await createIntegrationTestFlavorsTest().call();
     // test install and uninstall of flavors app
-    await inDirectory('${flutterDirectory.path}/dev/integration_tests/flavors', () async {
+    final TaskResult installTestsResult = await inDirectory(
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/flavors_test_ios.dart:17]: same feedback about formatting

File: dev/devicelab/bin/tasks/flavors_test_macos.dart [hunk 4]
```diff
@@ -14,7 +14,8 @@ Future<void> main() async {
     await createFlavorsTest().call();
     await createIntegrationTestFlavorsTest().call();
 
-    await inDirectory('${flutterDirectory.path}/dev/integration_tests/flavors', () async {
+    final TaskResult installTestsResult = await inDirectory(
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/flavors_test_macos.dart:17]: same nit about formatting

**Review by christopherfujino — COMMENTED** [review]
do you have led builds where these pass?

File: dev/devicelab/bin/tasks/flavors_test.dart (hunk 1 above)
Comment (andrewkolos) [reply dev/devicelab/bin/tasks/flavors_test.dart:45]: Great question. I looked the implementation myself and couldn't quickly figure it out either.

I want to say that validation happens, because I was able to get `Linux_android flavors_test` to fail at commit [9a022b4](https://github.com/flutter/flutter/pull/133719/commits/9a022b4776ef0414e6af984d783baeea5bcb7f15). See here: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/andrewkolos_google.com/c5ce156363a133d985cde403ae830dabf31bc43ffaecfa9fe0cd8d6f1dc5314e/+/build.proto?server=chromium-swarm.appspot.com. The task [completed successfully](https://chromium-swarm.appspot.com/task?id=646a44d8da33d310) after I fixed the stderr check in the following commit [6503967](https://github.com/flutter/flutter/pull/133719/commits/65039674a6f8c4162250063244d307c35a221132).

Comment (christopherfujino) [reply dev/devicelab/bin/tasks/flavors_test.dart:45]: sounds good to me

**Comment by andrewkolos** [comment]
> do you have led builds where these pass?

Oh yeah, forgot to add those. [`Linux_android flavors_test`](https://chromium-swarm.appspot.com/task?id=646a44d8da33d310). [`Mac_ios flavors_test_ios`](https://chromium-swarm.appspot.com/task?id=6466c0af85713910). I don't have anything for `Windows_android flavors_test` since we don't have try bots for that, but it should be functionality identical to `Linux_android flavors_test` as far as this change is concerned.

File: dev/devicelab/bin/tasks/flavors_test.dart (hunk 2 above)
Comment (andrewkolos) [reply dev/devicelab/bin/tasks/flavors_test.dart:17]: Agreed. It should be fixed now. Fun fact: I got the original formatting from `dart format`

**Review by christopherfujino — APPROVED** [review]
LGTM! Thanks for this yak shave

**Comment by vashworth** [comment]
@andrewkolos @christopherfujino I reverted this PR, it was failing `Windows_android flavors_test_win` in the tree

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20flavors_test_win/7438/overview

**Comment by christopherfujino** [comment]
> @andrewkolos @christopherfujino I reverted this PR, it was failing `Windows_android flavors_test_win` in the tree
> 
> https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20flavors_test_win/7438/overview

Thanks!
