### PR TITLE
Fix `IconButton` doesn't show `Tooltip` when hovering within the button area but outside the `Icon`

### LINKED ISSUE #153544: Tooltip is not shown consistently on entire IconButton
### Steps to reproduce

1. Add a tooltip message to IconButton using the `tooltip` property
2. Hover over the IconButton with the mouse
3. Observe that the tooltip is only shown when directly hovering the icon, not the entire tap area

### Expected results

The tooltip to be always visible when on any clickable area of the icon button.

### Actual results

The tooltip only shows when hovering the icon/content.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(colorSchemeSeed: Colors.blue),
      home: Scaffold(
        body: Center(
          child: IconButton.filled(
            icon: Icon(Icons.add),
            onPressed: () {},
            tooltip: "Tooltip",
          ),
        ),
      ),
    ),
  );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<table>
<tr>
<td>

image

</td>

<td>

image

</td>
</tr>
</table>

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.575, on Void Linux 6.6.46_1, locale en_US.UTF-8)
    • Flutter version 3.24.0-1.0.pre.575 on channel master at $HOME/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 593729165d (2 days ago), 2024-08-14 09:13:34 +0800
    • Engine revision 019f9e3f07
    • Dart version 3.6.0 (build 3.6.0-146.0.dev)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at $HOME/.local/lib/android-sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: $HOME/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.30.1
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2024.1)
    • Android Studio at $HOME/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at $HOME/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Void Linux 6.6.46_1
    • Chrome (web)    • chrome • web-javascript • Chromium 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
Fixes [Tooltip is not shown consistently on entire IconButton](https://github.com/flutter/flutter/issues/153544)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: Row(
            spacing: 20.0,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              IconButton(
                padding: const EdgeInsets.all(20.0),
                icon: const ColoredBox(
                  color: Color(0xFFFF0000),
                  child: Icon(Icons.add),
                ),
                onPressed: () {},
                tooltip: 'Tooltip',
              ),
              IconButton.filled(
                padding: const EdgeInsets.all(20.0),
                icon: const ColoredBox(
                  color: Color(0xFFFF0000),
                  child: Icon(Icons.add),
                ),
                onPressed: () {},
                tooltip: 'Tooltip',
              ),
              IconButton.filledTonal(
                padding: const EdgeInsets.all(20.0),
                icon: const ColoredBox(
                  color: Color(0xFFFF0000),
                  child: Icon(Icons.add),
                ),
                onPressed: () {},
                tooltip: 'Tooltip',
              ),
              IconButton.outlined(
                padding: const EdgeInsets.all(20.0),
                icon: const ColoredBox(
                  color: Color(0xFFFF0000),
                  child: Icon(Icons.add),
                ),
                onPressed: () {},
                tooltip: 'Tooltip',
              ),
            ],
          ),
        ),
      ),
    ),
  );
}
```

</details>

### Before (Hover outside the red box but within the `IconButton`)

Screenshot 2024-08-19 at 15 30 35

### Before (Hover outside the red box but within the `IconButton`)

Screenshot 2024-08-19 at 15 30 09

### Demo

https://github.com/user-attachments/assets/129eb8ee-e132-45c9-80b7-165486c02951

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/icon_button.dart [hunk 1]
```diff
@@ -719,23 +719,26 @@ class IconButton extends StatelessWidget {
...
         autofocus: autofocus,
         focusNode: focusNode,
         isSelected: isSelected,
         variant: _variant,
-        child: iconButton,
+        child: effectiveIcon,
       );
+
+      if (tooltip != null) {
+        iconButton = MergeSemantics(
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/icon_button.dart:733]: Just curious, why do we need to merge semantics here?

**Review by QuncCccccc — COMMENTED** [review]
Looks good to me! Just have one question:)

File: packages/flutter/lib/src/material/icon_button.dart (hunk 1 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/icon_button.dart:733]: I see! It seems because `ButtonStyleButton` creates a separate semantic node by using `container: true`, so when we use `Tooltip` to wrap the M3 `IconButton` which is a subclass of `ButtonStyleButton`, tooltip becomes another node instead of part of the semantic node of `IconButton`. This implementation is good for now because it seems other common buttons don't need tooltips now. If we have more tooltip requests for other ButtonStyleButtons, we can introduce tooltip property in `ButtonStyleButton` and pass it to all other subclasses, including `IconButton`:)

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks for the fix!

File: packages/flutter/lib/src/material/icon_button.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/icon_button.dart:733]: I agree! Fingers crossed MergedSemantics doesn't cause any regressions.

**Comment by TahaTesser** [comment]
@QuncCccccc 
It seems google testing is failing on this.

**Comment by QuncCccccc** [comment]
It seems related to the semantic tree, will take a look:)!

**Comment by QuncCccccc** [comment]
> @QuncCccccc It seems google testing is failing on this.

The internal failures are related to the semantics tree, if this fix breaks the internal google tests, it may also break other app tests. I'm thinking maybe we can introduce `String? tooltip` property in `ButtonStyleButton` class, if `widget.tooltip` is not null, then use a `Tooltip` to wrap `result`. Then `_SelectableIconButton` in `IconButton` can directly call super. The internal failures can pass with this fix change. What do you think:)?

**Comment by TahaTesser** [comment]
@QuncCccccc Great idea, I updated the PR with the new fix.

File: packages/flutter/lib/src/material/button_style_button.dart [hunk 2]
```diff
@@ -155,14 +157,20 @@ abstract class ButtonStyleButton extends StatefulWidget {
   /// Defaults to true.
   final bool? isSemanticButton;
 
+  /// {@macro flutter.material.ButtonStyleButton.iconAlignment}
+  final IconAlignment iconAlignment;
+
+  /// Text that describes the action that will occur when the button is pressed.
+  ///
+  /// This text is displayed when the user long-presses on the button and is
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/button_style_button.dart:165]: Just feel the original explanation is not super clear because the text will also get displayed when the button is on hovered on desktop platforms.

File: packages/flutter/test/material/icon_button_test.dart [hunk 3]
```diff
@@ -2954,6 +2959,39 @@ void main() {
       // No exception is thrown.
     });
   });
+
+  // This is a regression test for https://github.com/flutter/flutter/issues/153544.
+  testWidgets('Tooltip is drawn when hovering within IconButton area but outside the Icon tself', (WidgetTester tester) async {
```
Comment (QuncCccccc) [inline packages/flutter/test/material/icon_button_test.dart:2964]:
```suggestion
  testWidgets('Tooltip is drawn when hovering within IconButton area but outside the Icon itself', (WidgetTester tester) async {
```

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks!

File: packages/flutter/lib/src/material/button_style_button.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/button_style_button.dart]: Good point, i made some improvements. Also mentioned what happens if this parameter is `null`.

File: packages/flutter/lib/src/material/button_style_button.dart [hunk 4]
```diff
@@ -520,6 +531,13 @@ class _ButtonStyleState extends State<ButtonStyleButton> with TickerProviderStat
         minSize = Size.zero;
     }
 
+    if (widget.tooltip != null) {
+      result = Tooltip(
+        message: widget.tooltip,
+        child: result,
+      );
+    }
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/button_style_button.dart:539]: The G3 failure helps catch a corner case, with the current change(`Tooltip` is parent of `InkWell`), the extra tap area(the black area) doesn't work anymore.

<details><summary>Sample code</summary>

```dart

import 'package:flutter/material.dart';

/// Flutter code sample for [Dialog].

void main() => runApp(const DialogExampleApp());

class DialogExampleApp extends StatelessWidget {
  const DialogExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: DialogExample(),
      ),
    );
  }
}

class DialogExample extends StatelessWidget {
  const DialogExample({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: ColoredBox(
        color: Colors.black,
        child: BackButton(
          color: Colors.white,
          style: ButtonStyle(
            padding: WidgetStatePropertyAll<EdgeInsets>(EdgeInsets.all(20)),
            backgroundColor: WidgetStatePropertyAll<Color>(Colors.yellow)
          ),
        ),
      ),
    );
  }
}

```

</details>

<details><summary>Demo</summary>

https://github.com/user-attachments/assets/d20568b2-3a3a-44d8-9ec1-ffcc9d77689b

</details>

If we put tooltip inside of `InkWell`, tapping area works as expected. It's probably because of the way how tooltip treats its parent widget(I haven't dig too deep into this:)).

<details><summary>After fix</summary>

https://github.com/user-attachments/assets/e73f817a-126d-40de-ba2e-40845bfd5b3a

</details>

**Review by QuncCccccc — COMMENTED** [review]
I think we can put

```
    if (widget.tooltip != null) {
      effectiveChild = Tooltip(
        message: widget.tooltip,
        child: effectiveChild,
      );
    }
```
above the `result` widget so `InkWell` is tooltip's parent. And we can add a unit test for this corner case:)

File: packages/flutter/lib/src/material/button_style_button.dart (hunk 4 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/button_style_button.dart]: Thank you for taking a look! I updated the fix and added another test to catch this exact scenario within icon_button_test class

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/button_style_button.dart]: Sounds good! Feel free to land it whenever you are ready!
