### PR TITLE
Wrap dwds in async guard, only catch known error types

### LINKED ISSUE #696: WebSocketException: Connection to 'http://localhost:[...]/devtools/page/[...]#' was not upgraded to websocket
From Flutter tool crash logging on an invocation with flags `--no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart`

```
WebSocketException: WebSocketException: Connection to 'http://localhost:62678/devtools/page/2106B5DC2EE9DB2C3EAA7E7017C7FA42#' was not upgraded to websocket
  | at _WebSocketImpl.connect.<anonymous closure>.error | (websocket_impl.dart:1052 )
  | at _WebSocketImpl.connect.<anonymous closure> | (websocket_impl.dart:1061 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future.wait.<anonymous closure> | (future.dart:400 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:552 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```

/cc @jakemac53 @jonahwilliams

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Catch Exception and WebSocketException error types from an asyncGuard around dwds code. Rethrow on all other error types.

Fixes https://github.com/dart-lang/webdev/issues/696

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 1]
```diff
@@ -164,46 +166,55 @@ class ResidentWebRunner extends ResidentRunner {
...
+        appStartedCompleter?.complete();
+        return attach(
+          connectionInfoCompleter: connectionInfoCompleter,
+          appStartedCompleter: appStartedCompleter,
+        );
+      });
+      return result;
+    } on WebSocketException {
+      throwToolExit('Failed to connect to WebSocket.');
+    } on Exception catch (err) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Throw/catch a more specific exception type here to avoid burying things we'd still like to bubble up to crash logging.

**Review by zanderso — APPROVED** [review]
