### PR TITLE
Fix the losing of state when pushing opaque routes

### LINKED ISSUE #5283: Need startActivityForResult() equivalent on Flutter
On mobile, it is common for a state to persist over several screens. For instance, while filling out a form, you might want to invoke a new page asking for additional information then go back to the original form. To support this, we need two things:

- A mechanism to push a route to the navigator and get results from it.
- To save the state of the previous route so it can be revived upon user's return to the page.

### LINKED ISSUE #5378: OffStage has identity crisis.
OffStage has a parameter called offstage.

Is it two words or one?  It shouldn't be both.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/5283

Other changes in this patch:

Rename OffStage to Offstage.
Fixes https://github.com/flutter/flutter/issues/5378

Add a lot of docs.

Some minor punctuation and whitespace fixes.

### CODE REVIEW

**Comment by Hixie** [comment]
Closing until I figure out the failure.

File: packages/flutter/lib/src/widgets/debug.dart [hunk 1]
```diff
@@ -11,6 +11,11 @@ import 'table.dart';
 /// Log the dirty widgets that are built each frame.
 bool debugPrintRebuildDirtyWidgets = false;
 
+/// Log when widgets with global keys are deactivated and log when they get retaken.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/debug.dart]: when they're activated again?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
 /// this callback.
 typedef void ElementVisitor(Element element);
 
+/// A handle to the location of a widget in the widget tree.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: I'm really pleased to see this get documented!

File: packages/flutter/lib/src/widgets/framework.dart [hunk 3]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
+/// This class presents a set of methods that can be used from
+/// [StatelessWidget.build] methods and from methods on [State] objects.
+///
+/// [BuildContext] objects are passed to [WidgetBuilder] functions (such as
+/// [StatelessWidget.build]), and are available from the [State.context] member.
+/// Some static functions (e.g. [showDialog], [Theme.of], and so forth) also
+/// take build contexts so that they can act on behalf of the calling widget, or
+/// obtain data specifically for the given context.
+///
+/// Each widget has its own [BuildContext]. In particular, this means that
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: Maybe you should explain that the build method's BuildContext will become the ancestor of all of the widgets it creates.  That would help explain why Theme.of(X) fails to find a descendant of X.

I also wish that we weren't coy about the Element tree and the fact that BuildContext is a node in the Element tree which has-a Widget.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 4]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
+/// looks for the nearest enclosing [Theme] of the given build context. If a
+/// build method for a widget Q includes a [Theme] within its returned widget
+/// tree, and attempts to use [Theme.of] passing its own context, the build
+/// method for Q will not find that [Theme] object. It will instead find
+/// whatever [Theme] was an ancestor to the widget Q. If the build context for a
+/// subpart of the returned tree is needed, a [Builder] widget can be used: the
+/// build context passed to the [Builder.builder] callback will be that of the
+/// [Builder] itself.
+///
+/// For example, in the following snippet, the [ScaffoldState.showSnackBar]
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: I wish this wasn't necessary, https://github.com/flutter/flutter/issues/4581

File: packages/flutter/lib/src/widgets/framework.dart [hunk 5]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
+///     );
+///   }
+/// ```
+///
+/// The [BuildContext] for a particular widget can change location over time as
+/// the widget is moved around the tree. Because of this, values returned from
+/// the methods on this class should not be cached beyond the execution of a
+/// single synchronous function.
 abstract class BuildContext {
+  /// The current configuration of the widget to which this [BuildContext] belongs.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: It's a bit confusing to describe a widget as the current configuration of a widget.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 6]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
   Widget get widget;
+
+  /// The current [RenderObject] for the widget. If the widget is a
+  /// [RenderObjectWidget], this is the render object that the widget created
+  /// for itself. Otherwise, it is the render object of the first descendant
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: first ancestor?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 7]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
+  /// [RenderObjectWidget].
+  ///
+  /// This method will only return a valid result after the build phase is
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: The references to phases that follow are a little confusing since we haven't explained what all the phases are, how they're orchestrated, how a widget figures out what phase it's in, etc.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 8]
```diff
@@ -1163,17 +1185,205 @@ class _InactiveElements {
...
+  /// concrete [InheritedWidget] subclass, and registers this build context with
+  /// that widget such that when that widget changes (or a new widget of that
+  /// type is introduced, or the widget goes away), this build context is
+  /// rebuilt so that it can obtain new values from that widget.
+  ///
+  /// This is typically called implicitly from `of()` static methods, e.g.
+  /// [Theme.of].
+  ///
+  /// This is safe to call from build methods, layout and paint callbacks,
+  /// interaction event handlers (e.g. gesture callbacks), and so forth.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: Is this the place to explain that the method shouldn't be called from initState()  or a Widget constructor?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 9]
```diff
@@ -1394,12 +1604,19 @@ abstract class Element implements BuildContext {
     return result;
   }
 
-  /// This is used to verify that Element objects move through life in an orderly fashion.
+  /// This is used to verify that Element objects move through life in an
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: Public /// doc for a private field?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 10]
```diff
@@ -2620,27 +2855,33 @@ abstract class RenderObjectElement extends BuildableElement {
...
 ///
 /// Only root elements may have their owner set explicitly. All other
 /// elements inherit their owner from their parent.
 abstract class RootRenderObjectElement extends RenderObjectElement {
   RootRenderObjectElement(RenderObjectWidget widget): super(widget);
 
+  /// Set the owner of the element. The owner will be propagated to all the
+  /// descendants of this element.
+  ///
+  /// The owner is responsible for driving the build pipeline. Typically, xxxxx
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: xxxxxx?

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 11]
```diff
@@ -70,6 +87,27 @@ class OverlayEntry {
...
+  /// Whether this entry must be included in the tree even if there is a fully
+  /// [opaque] entry above it.
+  ///
+  /// By default, if there is an entirely [opaque] entry over this one, then this
+  /// one will not be included in the widget tree (in particular, stateful widgets
+  /// within the overlay entry will not be instantiated). To ensure that your
+  /// overlay entry is still built even if it is not visible, set [maintainState]
+  /// to true. This is more expensive, so should be done with care. In particular,
+  /// if widgets in an overlay entry with [maintainState] set to true repeatedly
+  /// call [setState], the user's battery will be drained unnecessarily.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/overlay.dart]: This would probably be a good place to provide a use case.

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 12]
```diff
@@ -277,3 +330,214 @@ class OverlayState extends State<Overlay> {
...
+  void update(_Theatre newWidget) {
+    super.update(newWidget);
+    assert(widget == newWidget);
+    _onstage = updateChild(_onstage, widget.onstage, _onstageSlot);
+    _offstage = updateChildren(_offstage, widget.offstage, detachedChildren: _detachedOffstageChildren);
+    _detachedOffstageChildren.clear();
+  }
+}
+
+/// A render object which lays out and paints one subtree while keeping a list
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/overlay.dart]: Public /// doc for a private class?

**Comment by HansMuller** [comment]
LGTM

File: packages/flutter/lib/src/widgets/debug.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/debug.dart]: done

File: packages/flutter/lib/src/widgets/framework.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: you're welcome!

File: packages/flutter/lib/src/widgets/framework.dart (hunk 3 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: > Maybe you should explain that the build method's BuildContext will become the ancestor of all of the widgets it creates. That would help explain why Theme.of(X) fails to find a descendant of X.

Explaining this isn't trivial, but done.

I've added a paragraph at the end of this block saying that build context are elements.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 5 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: replaced with "The current configuration of the [Element] that is this [BuildContext]"

File: packages/flutter/lib/src/widgets/framework.dart (hunk 6 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: pretty sure it's the first descendant.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 7 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: I've added a bunch of docs about this in the binding and pointed this to them.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 9 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: made it //

File: packages/flutter/lib/src/widgets/framework.dart (hunk 10 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: oops. Completed.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 11 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/overlay.dart]: done

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 12 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/overlay.dart]: made it //

**Comment by Hixie** [comment]
I updated a bunch of the docs. Will check in once Travis is ok with it unless more comments are posted by then. Thanks!
