### PR TITLE
Fix tooltip crash when route has secondary animation

### LINKED ISSUE #169741: RenderBox was not laid out: RenderFractionalTranslation#2c647 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
### Steps to reproduce

after upgrade flutter version to 3.32.1,i found some error about page route and AppBar of Scaffold.

### Expected results

steps:
1. use CupertinoPageRoute to Page2
2. use MaterialPageRoute to Page3
3. tap back button of AppBar on Page3, the error occurs

```text
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
RenderBox was not laid out: RenderFractionalTranslation#2c647 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2251 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

The relevant error-causing widget was: 
  AppBar AppBar:file:///D:/tempWorks/pro_iot_sports/lib/main.dart:61:15
```

### Actual results

.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'PageRouteErrorDemo',
      home: Page1(),
    );
  }
}

class Page1 extends StatefulWidget {
  const Page1({super.key});

  @override
  State<Page1> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page1'),
      ),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context).push(
              CupertinoPageRoute(
                builder: (context) => const Page2(),
              ),
            );
          },
          child: const Text('CupertinoPageRoute to Page2'),
        ),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  const Page2({super.key});

  @override
  State<Page2> createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page2'),
      ),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) {
                  return const Page3();
                },
              ),
            );
          },
          child: const Text('MaterialPageRoute to Page3'),
        ),
      ),
    );
  }
}

class Page3 extends StatefulWidget {
  const Page3({super.key});

  @override
  State<Page3> createState() => _Page3State();
}

class _Page3State extends State<Page3> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page3'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Center(
            child: Text(
              "now,click Top-Left button back to Page2, it will error\nbut click button below, it works fine",
            ),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
            child: const Text('Back to Page2'),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
RenderBox was not laid out: RenderFractionalTranslation#2c647 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2251 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

The relevant error-causing widget was: 
  AppBar AppBar:file:///D:/tempWorks/pro_iot_sports/lib/main.dart:61:15
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2251:12)
#3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:3081:42)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3633:25)
#5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:3094:39)
#6      TooltipState._buildTooltipOverlay (package:flutter/src/material/tooltip.dart:825:31)
#7      Builder.build (package:flutter/src/widgets/basic.dart:7919:48)
#8      StatelessElement.build (package:flutter/src/widgets/framework.dart:5781:49)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5715:15)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#11     StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#15     _OverlayPortalElement.update (package:flutter/src/widgets/overlay.dart:2258:21)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#20     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#29     ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#74     StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#78     StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#82     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#83     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
#85     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1240:21)
#86     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#87     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#88     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#89     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204:5)
#90     _invoke (dart:ui/hooks.dart:331:13)
#91     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444:5)
#92     _drawFrame (dart:ui/hooks.dart:303:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS D:\tempWorks\pro_iot_sports> flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.32.1, on Microsoft Windows [版本 10.0.22631.5335], locale zh-CN)
[√] Windows Version (11 专业版 64-bit, 23H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.2)
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Ultimate Edition (version 2025.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Consolidates [Fix the issue with Tooltip](https://github.com/flutter/flutter/pull/168546) and [Delay showing tooltip during page transition](https://github.com/flutter/flutter/pull/167614)

Fix [[Desktop] [Web] [Regression] [3.32] AppBar back - RenderBox was not laid out - TooltipState._buildTooltipOverlay](https://github.com/flutter/flutter/issues/169741)

### CODE REVIEW

File: packages/flutter/lib/src/material/tooltip.dart [hunk 1]
```diff
@@ -607,7 +608,7 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
 
   void _handlePointerDown(PointerDownEvent event) {
     assert(mounted);
-    if (!(ModalRoute.isCurrentOf(context) ?? true)) {
+    if (!(_route?.isCurrent ?? true) || (_route?.secondaryAnimation?.isAnimating ?? false)) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/tooltip.dart]: The secondaryAnimation is animating, meaning that the route is on its way out, so the tooltip shouldn't be interactive? Maybe consider leaving a comment explaining this if you think it's worth it. I guess you'd have to do that in all 3 places here.

File: packages/flutter/test/material/tooltip_test.dart [hunk 2]
```diff
@@ -3511,6 +3511,62 @@ void main() {
...
+
+      await tester.tap(find.text('Go to Second Page'));
+      await tester.pumpAndSettle();
+      await tester.tap(find.text('Go to Third Page'));
+      await tester.pumpAndSettle();
+
+      final TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse);
+      await gesture.addPointer();
+      await tester.tap(find.byType(BackButton));
+      await tester.pump(const Duration(milliseconds: 250));
```
Comment (justinmc) [inline packages/flutter/test/material/tooltip_test.dart]: This is supposed to be a fraction of the page transition right? Use [PageTransitionObserver.transitionDuration](https://main-api.flutter.dev/flutter/flutter_test/TransitionDurationObserver/transitionDuration.html). That way if the transition changes to be shorter than 250ms, this test will still work.

It's unlikely to be a problem but I was just dealing with this so I'm eager to use PageTransitionObserver :)

File: packages/flutter/test/material/tooltip_test.dart [hunk 3]
```diff
@@ -3511,6 +3511,62 @@ void main() {
...
+      await gesture.moveTo(tester.getCenter(find.text('World')));
+      await tester.pumpAndSettle();
+
+      expect(tester.takeException(), isNull);
```
Comment (justinmc) [inline packages/flutter/test/material/tooltip_test.dart:3573]: Is it worth it to also test that the tooltip is not visible? Up to you, it's possible that would unnecessarily make the test more brittle.

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: .

File: packages/flutter/lib/src/material/tooltip.dart (hunk 1 above)
Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: I'm curious to understand this too.

I think pulling this logic out as a small private helper method would be helpful in any case; and that'd make a good home for the comment.

File: packages/flutter/test/material/tooltip_test.dart [hunk 4]
```diff
@@ -3511,6 +3511,62 @@ void main() {
...
+              },
+            ),
+          ),
+        ),
+      );
+
+      await tester.tap(find.text('Go to Second Page'));
+      await tester.pumpAndSettle();
+      await tester.tap(find.text('Go to Third Page'));
+      await tester.pumpAndSettle();
```
Comment (justinmc) [inline packages/flutter/test/material/tooltip_test.dart]: Usually pumpAndSettle is not enough to pump through a page transition, though it appears to be working here. Maybe add `expect`s for text that's present on each page so you verify which page(s) are visible at any time.

File: packages/flutter/lib/src/material/tooltip.dart [hunk 5]
```diff
@@ -797,6 +798,7 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
   void didChangeDependencies() {
     super.didChangeDependencies();
     _visible = TooltipVisibility.of(context);
+    _route = ModalRoute.of(context);
```
Comment (gnprice) [inline packages/flutter/lib/src/material/tooltip.dart]: Is this eager fetching, and then stashing, of the ModalRoute part of the fix? Or is the fix all about the secondaryAnimation logic, and this part is just a refactor to make that convenient?

**Review by gnprice — COMMENTED** [review]
Thanks for fixing this!

File: packages/flutter/lib/src/material/tooltip.dart (hunk 1 above)
Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: (In particular, I think even just writing down a name for that helper function will be helpful for clarifying what this logic is meant to do.)

File: packages/flutter/lib/src/material/tooltip.dart (hunk 5 above)
Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: Just a refactor, the fix is just adding the secondaryAnimation logic

Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: Cool. As a nit, then, please mention that in the PR description (which becomes the Git commit message) ­— that's helpful for reading and understanding the change.

File: packages/flutter/lib/src/material/tooltip.dart [hunk 6]
```diff
@@ -606,9 +606,17 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
     }
   }
 
+  bool _isTooltipInteractive() {
+    final bool routeIsCurrent = _route?.isCurrent ?? false;
+    // If the route's secondary animation is animating, the route is on its way
+    // out. So, the tooltip should be non-interactive.
+    final bool routeIsAnimating = _route?.secondaryAnimation?.isAnimating ?? false;
```
Comment (gnprice) [inline packages/flutter/lib/src/material/tooltip.dart]: Very helpful, thanks!

File: packages/flutter/lib/src/material/tooltip.dart [hunk 7]
```diff
@@ -606,9 +606,17 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
...
+    return routeIsCurrent && !routeIsAnimating;
```
Comment (gnprice) [inline packages/flutter/lib/src/material/tooltip.dart]: If _route is null, then both branches of this fall back, but they end up doing so in opposite directions.

I think it'll probably be easiest to think through the logic if there's an `if (_route == null)` condition at the top that returns the desired result for that case. Then the rest can say `_route!` and not think about the null case.

Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: In particular it looks like this PR currently flips the answer that's used when the route is null. I'm not sure what the right answer for that is — but I'm also not sure if if that change was intended, because this logic is a bit hard to read for that case :slightly_smiling_face:

**Review by gnprice — APPROVED** [review]
Thanks! LGTM.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 7 above)
Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: (With your update, I believe it no longer flips the answer for when the route is null — instead that continues to be treated as meaning the tooltip should be interactive, as if all this logic weren't here. Which I think is the right answer.)

File: packages/flutter/lib/src/material/tooltip.dart [hunk 8]
```diff
@@ -605,9 +606,19 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
     }
   }
 
+  bool _isTooltipInteractive() {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/tooltip.dart]: Is this the right fix? Tooltip ideally should not know about route. This feels too specific and the problem may come up again in a different set up.

Comment (gnprice) [reply packages/flutter/lib/src/material/tooltip.dart]: Good question! I agree Tooltip ideally shouldn't know about Route. There's probably a cleaner solution by using some other abstraction.

The same comment applies already to the previous fix #168546, which this PR fixes a bug in.

Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: This is the core issue: https://github.com/flutter/flutter/issues/167359#issuecomment-2822116519. Basically the tooltip shouldn't be displayed mid-transition.

Tooltip uses OverlayPortal behind the scenes: https://github.com/flutter/flutter/blob/9f90740c2681ec15d27bcb576f948a7740e30a3a/packages/flutter/lib/src/material/tooltip.dart#L950

So maybe the deeper solution is to have OverlayPortal not show its overlaychild in the middle of a route transition? But is that always desired behavior? Or can we hide it behind a flag?

Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: I used the workaround in this PR previously in another [PR](https://github.com/flutter/flutter/pull/170186) for the `CupertinoContextMenu` overlay entry.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/tooltip.dart]: The root issue is that `RenderObject.getTransformTo` should not be called during build, it's unsafe even if in a LayoutBuilder.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/tooltip.dart]: #170186 feels okish to me because the framework doesn't have a lifecycle callback to tell an Element that they're going offstage. So you kinda have to make Route special there to get the signal that the text field is going offstage (hopefully we can introduce new APIs to avoid making this assumption, I think we get bitten by that a lot).

Comment (justinmc) [reply packages/flutter/lib/src/material/tooltip.dart]: Good point that Tooltip ideally shouldn't know about the route. Catching up here:

  * Is that the getTransformTo in OverlayPortal that you're referring to @LongCatIsLooong? [Maybe this](https://github.com/flutter/flutter/blob/e5b78fe6e5309da6ce49e94f9246ce4bad3b0ff2/packages/flutter/lib/src/widgets/overlay.dart#L2709)?
  * What is a better solution here?
    - Outgoing routes shouldn't be interactive at all? Maybe that's a bad user experience, not sure. Incoming routes definitely should be interactive. Does this bug happen on incoming routes too?
    - The getTransformTo in question should somehow wait until after layout is done?
    - This isn't something that OverlayPortal.overlayChildLayoutBuilder would help with is it?

Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: Confirmed, `OverlayPortal.overlayChildLayoutBuilder` fixes the issue. Thanks @LongCatIsLooong.

File: packages/flutter/test/material/tooltip_test.dart (hunk 3 above)
Comment (victorsanni) [reply packages/flutter/test/material/tooltip_test.dart:3573]: The difficulty is that there is still a tooltip but it is inactive, so it makes it more brittle. But the test already prevents a regression of this change anyways.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 8 above)
Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: I did a quick grep through the codebase, RawMenuAnchor also uses OverlayPortal and localToGlobal in its `buildOverlay` method, so this problem might occur there too. Maybe I can add a TODO to migrate to OverlayPortal.overlayChildLayoutBuilder.

File: packages/flutter/lib/src/material/tooltip.dart [hunk 9]
```diff
@@ -606,10 +606,6 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
   }
 
   void _handlePointerDown(PointerDownEvent event) {
-    assert(mounted);
-    if (!(ModalRoute.isCurrentOf(context) ?? true)) {
-      return;
-    }
```
Comment (justinmc) [inline packages/flutter/lib/src/material/tooltip.dart:612]: Nice that we don't need these anymore!

File: packages/flutter/lib/src/material/tooltip.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/tooltip.dart]: Yes good call, can you create an issue too?

**Review by justinmc — APPROVED** [review]
LGTM, this is a really simple fix now 👍

File: packages/flutter/lib/src/material/tooltip.dart (hunk 8 above)
Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart]: Filed https://github.com/flutter/flutter/issues/173440

**Review by LongCatIsLooong — APPROVED** [review]
