### PR TITLE
Fix web text field shortcuts

### LINKED ISSUE #79012: Left right arrow keys and space don't work in text fields
I can't use the left or right arrow keys to move the cursor in the debug console.

### PR DESCRIPTION
**Pull request by justinmc**
Originally when I introduced TextEditingActions in https://github.com/flutter/flutter/pull/75032, I broke my setup for text editing shortcuts.  This fixes it as originally intended, and gets arrow keys working in text fields again on web.

The plan is to introduce top-level Shortcuts in WidgetsApp for web, just like all other platforms, but web's shortcuts just do nothing and stop propagation.  Similar to the other TextEditingActions, these web shortcuts are only handled if an EditableText is currently focused.

This way, it's still possible to override this default behavior anywhere in the widget tree in between WidgetsApp and each EditableText.

Closes https://github.com/flutter/flutter/issues/79012
See also: https://github.com/flutter/flutter/pull/79051

### CODE REVIEW

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart [hunk 1]
```diff
@@ -72,7 +72,7 @@ class _DoNothingAndStopPropagationTextAction extends TextEditingAction<DoNothing
   _DoNothingAndStopPropagationTextAction();
 
   @override
-  bool consumesKey(Intent intent) => true;
+  bool consumesKey(Intent intent) => false;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/default_text_editing_actions.dart:75]: Shouldn't this change the name to `_DoNothingTextAction`, since it no longer stops propagation?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:75]: I thought the same thing, but look at the original DoNothingAndStopPropagation:

https://github.com/flutter/flutter/blob/f712fecde2e3105b6a2f604c86da86175444195d/packages/flutter/lib/src/widgets/app.dart#L1110

Is there a misnomer somewhere or are we misunderstanding what consumesKey means?

Comment (mdebbar) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:75]: My understanding is `consumesKey` has nothing to do with propagation. It's responsible for telling the engine whether the key event was handled or not.

Comment (mdebbar) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:75]: What stops the propagation is the fact that `DoNothingAndStopPropagationIntent` is, by default, attached to the `DoNothingAction`. But the `DoNothingAction` itself doesn't control propagation.

**Review by mdebbar — APPROVED** [review]
LGTM

**Comment by venkatd** [comment]
@justinmc @mdebbar thanks for getting this merged in and all that led up to it.

It was one of the biggest blockers to beta usage we had. Can confirm arrow keys can be overridden within text fields for our mentions and autocomplete widgets.
