### PR TITLE
Fix spell check throws when text contains regex reserved characters

### LINKED ISSUE #136032: FormatException: Nothing to repeat\b* Substituição\b. Error thrown building Widget-[GlobalKey#8460a].
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Unable to reproduce issue locally.
Issue has been reported from firebase_crashlytics.

### Expected results

Should not get this FormatException.

### Actual results

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FormatException: Nothing to repeat\b* Substituição\b. Error thrown building Widget-[GlobalKey#8460a].
#00 pc 0xce8af7 com.agendaboa.app (new _RegExp [regexp_patch.dart:149]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#01 pc 0x45976b com.agendaboa.app (_correctSpellCheckResults [regexp_patch.dart:15]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#02 pc 0x45824b com.agendaboa.app (buildTextSpanWithSpellCheckSuggestions [spell_check.dart:204]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#03 pc 0x4580c3 com.agendaboa.app (EditableTextState.buildTextSpan [editable_text.dart:4779]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#04 pc 0x9307b7 com.agendaboa.app (EditableTextState.build.<anonymous closure> [editable_text.dart:4674]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#05 pc 0x93a34f com.agendaboa.app (ScrollableState.build [scrollable.dart:966]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#06 pc 0xa0246b com.agendaboa.app (StatefulElement.build [framework.dart:5409]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#07 pc 0xd0996f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:5297]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#08 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#09 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#10 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#11 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#12 pc 0x4ba90f com.agendaboa.app (_InheritedNotifierElement.update [inherited_notifier.dart:107]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#13 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#14 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#15 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#16 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#17 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#18 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#19 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#20 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#21 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#22 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#23 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#24 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#25 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#26 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#27 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#28 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#29 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#30 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#31 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#32 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#33 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#34 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#35 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#36 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#37 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#38 pc 0x4ba147 com.agendaboa.app (SlottedRenderObjectElement._updateChildren [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#39 pc 0x4b9c83 com.agendaboa.app (SlottedRenderObjectElement.update [slotted_render_object_widget.dart:256]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#40 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#41 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#42 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#43 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#44 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#45 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#46 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#47 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#48 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#49 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#50 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#51 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#52 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#53 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#54 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#55 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#56 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#57 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#58 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#59 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#60 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#61 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#62 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#63 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#64 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#65 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#66 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#67 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#68 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#69 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#70 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#71 pc 0x4bae0b com.agendaboa.app (StatelessElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#72 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#73 pc 0x4b756f com.agendaboa.app (Element.updateChildren [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#74 pc 0x4b8b8f com.agendaboa.app (MultiChildRenderObjectElement.update [framework.dart:6594]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#75 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#76 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#77 pc 0x4bae0b com.agendaboa.app (StatelessElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#78 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#79 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#80 pc 0x4b756f com.agendaboa.app (Element.updateChildren [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#81 pc 0x4b8b8f com.agendaboa.app (MultiChildRenderObjectElement.update [framework.dart:6594]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#82 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#83 pc 0x4bad1b com.agendaboa.app (ProxyElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#84 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#85 pc 0x4bae0b com.agendaboa.app (StatelessElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#86 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#87 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#88 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#89 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#90 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#91 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#92 pc 0x4b756f com.agendaboa.app (Element.updateChildren [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#93 pc 0x4b8b8f com.agendaboa.app (MultiChildRenderObjectElement.update [framework.dart:6594]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#94 pc 0x4b8e0b com.agendaboa.app (SingleChildRenderObjectElement.update [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#95 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#96 pc 0x4bae0b com.agendaboa.app (StatelessElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#97 pc 0xd09c4f com.agendaboa.app (ComponentElement.performRebuild [framework.dart:3685]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#98 pc 0x4beb63 com.agendaboa.app (StatefulElement.performRebuild [framework.dart:5462]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
#99 pc 0x4baf6b com.agendaboa.app (StatefulElement.update [framework.dart:5016]) (BuildId: 5640f66f35ecd3d04067e263768afad7)
```

### Code sample

<details><summary>Code sample</summary>

```dart
TextFormField(
  textEditingController: TextEditingController,
  spellCheckConfigutation: SpellCheckConfiguration(
                spellCheckService: DefaultSpellCheckService()),
)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Screen Shot 2023-10-05 at 6 50 14 PM

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.7 21G816 darwin-x64, locale en-US)
    • Flutter version 3.13.6 on channel stable at /Users/appleapple/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.7 21G816 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes an issue related to the spell check implementation usage of Regex (searched text should be escaped).

## Related Issue

Fixes https://github.com/flutter/flutter/issues/136032.

## Tests

Adds 1 test.

### CODE REVIEW

File: packages/flutter/test/widgets/spell_check_test.dart [hunk 1]
```diff
@@ -353,4 +353,31 @@ void main() {
...
+      const TextEditingValue value = TextEditingValue(text: text);
+      const bool composingRegionOutOfRange = false;
+      const SpellCheckResults spellCheckResults = SpellCheckResults(
+        resultsText,
+        <SuggestionSpan>[
+          SuggestionSpan(TextRange(start: 7, end: 12), <String>['*rangesa']),
+        ],
+      );
+
+      buildTextSpanWithSpellCheckSuggestions(
```
Comment (camsim99) [inline packages/flutter/test/widgets/spell_check_test.dart:372]: Can we also test the output of this?

**Review by camsim99 — APPROVED** [review]
LGTM, just left a request for testing the spell check output in the test :)
