### PR TITLE
Avoid thinning frameworks in iOS extensions 

### LINKED ISSUE #60351: Must run flutter clean before building when iOS app has watch extension, Failed to extract arm64 for .../PlugIns/WatchApp.appex/Frameworks
## Problem
Must run `flutter clean` between every build (run/debug) when app includes a WKExtension.
Seems like flutter uses the same "active architecture" for Apple Watch as it does for iPhone.
That in turn causes flutter to try extract the wrong architecture when building app for debug/run on device.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a watch extension (https://flutter.dev/docs/development/platform-integration/apple-watch
3. Add a pod for your watch extension target (I use `pod 'EFQRCode/watchOS', '~> 5.1.6'`, but any pod will do)
4. Run your app on an iPhone or iOS simulator.
5. Stop debug/run session after app has installed and launched on device/simulator.
6. Again, run your app on an iPhone or iOS simulator.

**Expected results:** 
App launches.

**Actual results:** 
Build error.

<details>
  <summary>Logs</summary>

```
Flutter.framework/_CodeSignature/CodeResources
               sent 98388907 bytes  received 120 bytes  65592684.67 bytes/sec
               total size is 98376483  speedup is 1.00
               PATH/TO/BUILD/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
               PATH/TO/BUILD/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
               PATH/TO/BUILD/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
               fatal error: lipo: -extract arm64 specified but fat file: PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode does not contain that architecture
               Failed to extract arm64 for PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode. Running lipo -info:
               Architectures in the fat file: PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode are: armv7k arm64_32
               Command PhaseScriptExecution failed with a nonzero exit code
               note: Using new build system
               note: Building targets in parallel
               note: Planning build
               note: Constructing build description
```

```
```

```
```

```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.19.0-4.2.pre at /Users/ME/Documents/Development/FLUTTER_SDK/flutter
    • Framework revision 9b9b543d92 (4 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ME/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
```

</details>

### PR DESCRIPTION
**Pull request by jmagman**
Reland https://github.com/flutter/flutter/pull/64674
Always run the `pod install` fingerprint check if there is a `Podfile`, even if there are no Flutter plugins.

## Description

Watch extensions are embedded in iOS apps.  Avoid lipo'ing those frameworks to iOS architectures.  Stick to the app frameworks.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/60351

## Tests

Updated `ios_app_with_extensions_test` to include a watch framework.  Check the build succeeds, and that the watch extension frameworks have the expected watch architectures.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/cocoapod_utils.dart [hunk 1]
```diff
@@ -21,7 +21,7 @@ Future<void> processPodsIfNeeded(
   final FlutterProject project = xcodeProject.parent;
   // Ensure that the plugin list is up to date, since hasPlugins relies on it.
   await refreshPluginsList(project);
-  if (!(hasPlugins(project) || (project.isModule && xcodeProject.podfile.existsSync()))) {
+  if (!hasPlugins(project) && !xcodeProject.podfile.existsSync()) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/cocoapod_utils.dart:24]: This is the part that should fix the post-commit failure from https://github.com/flutter/flutter/pull/64674.
@xster What do you think about this?  Looks like the `project.isModule` caveat was added back in #21276.

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/macos/cocoapod_utils.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/macos/cocoapod_utils.dart:24]: nit. Maybe a comment to explain why we have to `pod install` even if it doesn't have plugins?

Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/cocoapod_utils.dart:27]: Good idea, done.

Comment (xster) [reply packages/flutter_tools/lib/src/macos/cocoapod_utils.dart:27]: I wish that original line could be DeMorgan rewritten 😂

That isModule part is definitely weird. I can see the argument for just generally not running pod install when there's only a user Podfile without plugin. Since at that point, it doesn't have much to do with Flutter's build pipeline. When a user changes his own Podfile, the user should run pod install themselves. Our customers did complain back in beta days about pod install always running for no changes and being slow. 

I can't think of why isModule + has Podfile means pod instead has to run. Removing isModule from this consideration altogether seems reasonable. "'Cause if you like it, then you shoulda put a test on it"

**Comment by zanderso** [comment]
What's the status of this PR?

**Comment by jmagman** [comment]
When I get back from vacation I am going to revert the changes to `cocoapod_utils.dart` based on @xster's feedback and update the integration test to pass (either add a Flutter plugin or run `pod install` manually)

File: packages/flutter_tools/lib/src/macos/cocoapod_utils.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/cocoapod_utils.dart]: I reverted this, and instead added a Flutter plugin to the integration test so the tool runs `pod install` for us and I don't need to call it manually.
