### PR TITLE
Fixed an issue with overflow exceptions with nested lists inside a reorderable list item.

### LINKED ISSUE #83224: ReorderableListView throws RenderFlex exception while dragging on latest stable and master
Hi, `ReorderableListView` widget shows a strange behavior while dragging a card with a nested `ListView` inside. It suddendly overflows, as you can see in the attached reproducible sample.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Reorderable cards',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Reorderable cards'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ReorderableListView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {
          return Container(
            key: ValueKey(index),
            child: Card(
              child: InkWell(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    ListTile(
                      title: Padding(
                        child: Text('Title'),
                        padding: const EdgeInsets.only(top: 8),
                      ),
                      subtitle: Text('Subtitle'),
                    ),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
                      child: ListView.builder(
                        shrinkWrap: true,
                        physics: ClampingScrollPhysics(),
                        itemCount: 3,
                        itemBuilder: (context, index) {
                          return Text('Other data');
                        },
                      ),
                    ),
                  ],
                ),
                onTap: () => null,
              ),
            ),
          );
        },
        onReorder: (oldIndex, newIndex) => null,
      ),
    );
  }
}
```

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Versione 10.0.19042.985], locale it-IT)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/Alessandro/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/Alessandro/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Alessandro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • LG H930 (mobile)            • LGH9308e11f266 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554  • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge           • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!
```

### PR DESCRIPTION
**Pull request by darrenaustin**
Fixes #83224.

The issue is caused by the nested list picking up the outer scaffold top padding when it is moved to the overlay. The parent `ReorderableList` normally deals with that so that any nested list views won't see the padding. However, when the item is moved to the overlay, it is now a top level list and picks up the padding which causes it to overflow the size of the list item.  This PR fixes this by removing any top padding from the  `MediaQueryData` that wraps the child.

Added a new test to ensure this doesn't break again.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -268,6 +268,60 @@ void main() {
     expect(getItemFadeTransition(), findsNothing);
   });
 
+  testWidgets('ReorderableList supports items with nested list views without throwing layout exception.', (WidgetTester tester) async {
+    await tester.pumpWidget(
```
Comment (Piinks) [inline packages/flutter/test/widgets/reorderable_list_test.dart:272]: Nit: Can you add one of those regression test for comments?

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
