### PR TITLE
Fix cursor outside of input width

### LINKED ISSUE #30302: Flutter TextField multiline fails to wrap when entering space on the Line
## Steps to Reproduce

First please take a look at this video: [Flutter Textfield Input Bug Video](https://www.youtube.com/watch?v=--vJVFL-kmg)

In this video, you can discover that when input some regular english characters in the end of the line, the text can be correctly wrapped into next line.

But when you enter space in the end of the line (as the later part of the video),  the text fails to wrap to the next line. And the input cursor just simply go outside of TextField box in the same line.

This is a simple demo, code as follow: 

```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text('input space in the following input field'),
            Text('to see if it can properly change line'),
            Container(
              height: 100, width: 200,
              color: Colors.indigo,
              child: TextField(
                style: TextStyle(color: Colors.white),
                keyboardType: TextInputType.multiline,
                maxLines: 3,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

Steps to reproduce:

1.  choose the blue box to select the TextField
2. Keep entering space
3. The problem will occur

Flutter analyze result as follow, no issues

```

Analyzing inputfield_no_change_line...                           
No issues found! (ran in 2.5s)

```

Flutter doctor as follow

```
[✓] Flutter (Channel faceu_dev_1.0.0, v1.0.1-pre.8, on Mac OS X 10.14.3 18D109, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/30302

By putting lots of spaces at the end of a line in a text input, it was possible to cause the cursor to overflow the width of the input.  See this video created by @WHATHELWHATHELWHATHEL : https://www.youtube.com/watch?v=--vJVFL-kmg

When this situation happens on native iOS and Android, the spaces are registered, but the cursor stops at the end of the top line:

This PR makes Flutter behave like native.

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller I'm worried that there might be a more robust place to put this kind of code since it's so simple.  Anything you can think of?  I originally tracked this down into the engine because I thought the engine shouldn't be giving a long line width when the line ends in spaces, but then I saw that natively they do keep track of the overflowing spaces, so I decided to keep all the engine code and just limit the cursor position in the framework.

What do you think?  I'll write some tests when I'm sure this is a valid solution.

**Comment by HansMuller** [comment]
@justinmc Never positioning the cursor past the end of a line (this solution) seems reasonable. Implementing the limit in the cursor positioning code seems reasonable too.

File: packages/flutter/test/material/text_field_test.dart [hunk 1]
```diff
@@ -426,6 +426,79 @@ void main() {
...
+    await skipPastScrollingAnimation(tester);
+    await tester.tapAt(textOffsetToPosition(tester, testValueSpaces.length));
+    await tester.pump();
+
+    final double inputWidth = findRenderEditable(tester).size.width;
+    final Offset cursorOffsetSpaces = findRenderEditable(tester).getLocalRectForCaret(
+      const TextPosition(offset: testValueSpaces.length),
+    ).bottomRight;
+
+    expect(cursorOffsetSpaces.dx, inputWidth - 1);
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart]: @HansMuller Any thoughts on this -1 here?  The width of the RenderEditable is 800 but the width of the TextPainter is 799.  Is my `min` code still right or is it off by 1?  Or should I find a way to get the width of the TextPainter instead of RenderEditable here?

Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Fixed with the constant `_kCaretGap` of length 1 pixel.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
I always forget to edit the squash commit message to something nice :disappointed:
