### PR TITLE
Fix some sizing bugs with multiline text controls.

### LINKED ISSUE #6329: multiline text fields scroll too high
You can scroll a multiline text field until the bottom line isn't visible. We should clamp the scroll region so that there is no empty space when the lines are all full.

### PR DESCRIPTION
**Pull request by mpcomplete**
1. Properly calculate text height. Previously we were applying
   constraints to the text height, which was incorrect when there was a min
   height. This resulted, for example, a caret that was way too tall.
2. Scrollable now caches container and content extents more often. This
   prevents rebuilds from clobbering the previously caculated sizes, fixing
   a bug where you could scroll beyond the end of text.

Fixes #6329

### CODE REVIEW

**Comment by mpcomplete** [comment]
I can't seem to write a test that repros these bugs. I can reliably repro them manually, but they don't occur. in the test framework.

**Comment by mpcomplete** [comment]
OK, I found the magic incantation to trigger the bug, and verified that this patch fixes it.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -513,6 +513,9 @@ class ScrollableState<T extends Scrollable> extends State<T> with SingleTickerPr
   /// If there are no in-progress scrolling physics, this function scrolls to
   /// the given offset instead.
   void didUpdateScrollBehavior(double newScrollOffset) {
+    _contentExtent = scrollBehavior.contentExtent;
+    _containerExtent = scrollBehavior.containerExtent;
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/scrollable.dart]: I guess this makes sense.  Probably should have @Hixie review though given that his head is more into scrolling at the moment.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/scrollable.dart]: @HansMuller is more familiar with this specific logic.

File: packages/flutter/test/widget/input_test.dart [hunk 2]
```diff
@@ -633,7 +633,11 @@ void main() {
     TestGesture gesture = await tester.startGesture(firstPos, pointer: 7);
     await tester.pump();
     await gesture.moveBy(new Offset(0.0, -1000.0));
-    await tester.pump();
+    await tester.pump(const Duration(seconds: 2));
+    // Wait and drag again to trigger https://github.com/flutter/flutter/issues/6329
+    // (No idea why this is necessary, but the bug wouldn't repro without it.)
```
Comment (Hixie) [inline packages/flutter/test/widget/input_test.dart]: Just file a bug describing how to trigger something manually, and point to this code saying that for some reason the test framework needs this to make it trigger. So long as the issue is clear enough about how to reproduce the difference, eventually I'll get around to investigating it.

Comment (mpcomplete) [inline packages/flutter/test/widget/input_test.dart]: The tricky part here is that it won't happen anymore with this fix. Or, presumably, with your changes to Scrollable. The only way to see that this is broken is running this code against the framework before this fix lands.

Comment (Hixie) [inline packages/flutter/test/widget/input_test.dart]: Can one can put a print somewhere in the code (even today's code) that shows a difference between the test and manual testing?

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 1 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scrollable.dart]: This is tricky. The variables you're updating were added in https://github.com/flutter/flutter/pull/5862

If you actually change the _contentExtent here then you'd need to setState(). But I believe that if you wrap the changes to _contentExtent and _containerExtent in setState() you'll trip over an assertion.

**Comment by mpcomplete** [comment]
Using maybeSetState. Ready for another look.

**Comment by HansMuller** [comment]
LGTM
