### PR TITLE
Adds fix for double comparison error

### LINKED ISSUE #23819: GridView / CustomScrollView randomly fails assert depending on childAspectRatio value and screen resolution
Since tickets with similar issues are already months (or over a year) old and still open, I'll post it as separate issue:

When using GridView or CustomScrollView, any childAspectRatio (besides 1.0) has a chance to trigger this problem, due to a double precision issue:

```
I/flutter ( 5004): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5004): The following assertion was thrown during performLayout():
I/flutter ( 5004): SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".
I/flutter ( 5004): The maxPaintExtent is 208.75000000000003, but the paintExtent is 208.75000000000006. Maybe you have
I/flutter ( 5004): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter ( 5004): functions, or the clamp() method, to the paintExtent? By definition, a sliver can't paint more than
I/flutter ( 5004): the maximum that it can paint!
I/flutter ( 5004): The RenderSliver that returned the offending geometry was:
I/flutter ( 5004):   RenderSliverGrid#3a956 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5004):   creator: SliverGrid ← SliverPadding ← ShrinkWrappingViewport ← _ScrollableScope ←
I/flutter ( 5004):   IgnorePointer-[GlobalKey#78fe7] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 5004):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ffd86] ←
I/flutter ( 5004):   _ScrollSemantics-[GlobalKey#59efa] ← RepaintBoundary ← CustomPaint ← ⋯
I/flutter ( 5004):   parentData: paintOffset=Offset(20.0, 20.0) (can use size)
I/flutter ( 5004):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 5004):   scrollOffset: 0.0, remainingPaintExtent: 492.0, crossAxisExtent: 344.0, crossAxisDirection:
I/flutter ( 5004):   AxisDirection.right, viewportMainAxisExtent: 512.0, remainingCacheExtent: 742.0 cacheOrigin: 0.0 )
I/flutter ( 5004):   geometry: SliverGeometry(scrollExtent: 208.8, paintExtent: 208.8, maxPaintExtent: 208.8,
I/flutter ( 5004):   hasVisualOverflow: true, cacheExtent: 208.8)
I/flutter ( 5004):   currently live children: 0 to 11
```

To be more specific:
`I/flutter ( 5004): The maxPaintExtent is 208.75000000000003, but the paintExtent is 208.75000000000006. Maybe you have`

```
return new CustomScrollView(
	slivers: <Widget>[
		new SliverPadding(
			padding: const EdgeInsets.all( 20.0 ),
			sliver: SliverGrid.count(
				crossAxisCount:   2,
				crossAxisSpacing: 10.0,
				childAspectRatio: 4.8,
				children:         items,
			),
		),
	],
);
```

Another example:
```
		return new GridView.count(
			crossAxisSpacing: 10.0,
			childAspectRatio: 4.8,
			crossAxisCount:   2,
			children:         items,
		);
```

This problem seems to depend on screen size, as it only appears on certain emulated devices and not on others.

Since the issue comes from sliver.dart, I can't do much from the outside:

```
if (maxPaintExtent < paintExtent) {
        verify(false,
          'The "maxPaintExtent" is less than the "paintExtent".\n' +
          _debugCompareFloats('maxPaintExtent', maxPaintExtent, 'paintExtent', paintExtent) +
          'By definition, a sliver can\'t paint more than the maximum that it can paint!'
        );
      }
```

There are a number similar issues still open, that seem to have the same cause:
https://github.com/flutter/flutter/issues/11079
https://github.com/flutter/flutter/issues/16086
https://github.com/flutter/flutter/pull/16126
https://github.com/flutter/flutter/issues/16125

If it's too difficult or time consuming to fix this issue properly right now, could the assert at least be turned into a warning instead? Right now the only "solution" for me is to guess the right number for `childAspectRatio` every time I test on a different device, as I can't seem to be able to predict the Sliver's behavior :)

```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/dev1/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/dev1/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/dev1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/dev1/android-studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jslavitz**
Fixes #23819 and related bugs.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 1]
```diff
@@ -686,7 +688,9 @@ class SliverGeometry extends Diagnosticable {
         );
       }
       verify(maxPaintExtent != null, 'The "maxPaintExtent" is null.');
-      if (maxPaintExtent < paintExtent) {
+      // If the paintExtent is slightly more than the maxPaintExtent, but the difference is still less
+      // than epsilon, we will not throw the assert below.
+      if (paintExtent - maxPaintExtent > _epsilon) {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/sliver.dart]: I would use the absolute difference to cover rounding errors on either side

**Review by jonahwilliams — APPROVED** [review]
LGTM
