### PR TITLE
Always use `--concurrency=1` for web tests.

### LINKED ISSUE #126178: Linux Web Framework tests flaky due to timeout interactions with loading the tests
We are seeing these kinds of failures a lot lately and it looks like the issue is that the Dart mechanism used to load all of the tests has a 12m timeout to load all of the tests that it was given, but we are blocking each test loaded by running the tests in it which means we reach the 12m timeout for loading before the test is done and well before the test has a CI timeout.

```
12:00 +133 ~2 -1: compiling /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/slivers_appbar_stretch_test.dart [E]                                                                                   
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/isolate_patch.dart 189:12      _RawReceivePort._handleMessage
  

To run this test again: /b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/slivers_appbar_stretch_test.dart -p chrome --plain-name 'compiling /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/slivers_appbar_stretch_test.dart'

[ Same failure message repeated for a dozen or more tests following this one ]
```

See Linux Web Framework tests log output: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781923893844814817/+/u/run_test.dart_for_web_tests_shard_and_subshard_4/test_stdout

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
This should fix https://github.com/flutter/flutter/issues/126178

When we don't pass a `--concurrency` flag to the test package, it uses a default based on the number of cores that are on the machine. However, the web test platform itself serializes all these requests anyway, which can lead to the test package timing out. This is because from the test package's perspective, it has already started the loading process on a number of suites which are simply waiting for other test suites to compile and run. The ones that wait the longest can run up against the test packages 12 minute timeout for loading a given suite, even though they haven't actually started to try to load.

Instead, we should always pass `--concurrency=1` to the test package so that it doesn't attempt to start loads concurrently in the first place.

### CODE REVIEW

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart [hunk 1]
```diff
@@ -441,13 +437,18 @@ class FlutterWebPlatform extends PlatformPlugin {
     if (_closed) {
       throw StateError('Load called on a closed FlutterWebPlatform');
     }
-    final PoolResource lockResource = await _suiteLock.request();
+
+    /// We only allow one test suite (typically one test file) to be loaded and
+    /// run at any given point in time. Loading more than one file at a time is
+    /// known to lead to flaky tests.
+    assert(_isLoadingSuite == false);
+    _isLoadingSuite = true;
```
Comment (flar) [inline packages/flutter_tools/lib/src/test/flutter_web_platform.dart:445]: What about a try/finally here?

**Review by flar — DISMISSED** [review]
LGTM

**Review by flar — COMMENTED** [review]
LGTM'd wrong PR...

**Review by zanderso — APPROVED** [review]
