### PR TITLE
Close the exit port used by the compute isolate utility function

### LINKED ISSUE #86470: compute function leaks memory | exitPort.close() not called
## Steps to Reproduce

1. Call `final myResult = await compute(_myGlobalFunction, myData);` function and then remove reference to the returned result. (execute few times)
2. Check `Memory` tab in Flutter DevTools.
3. Instances are not released from memory. (even if I wait longer or trigger GC)

**Expected results:** 

Instances are released from memory.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/franky/CODE/flutter-sdk
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/franky/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/franky/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • A920 (mobile)   • 0821085239 • android-arm    • Android 7.1.2 (API 25)
    • macOS (desktop) • macos      • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome     • web-javascript • Google Chrome 91.0.4472.114
    ! Error: iPad užívateľa Frantisek is not connected. Xcode will continue when iPad užívateľa Frantisek is connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

I looked into the code for `compute` function and found a solution. 
there are 3 `ReceivePort` instances created but only 2 of them are closed at the end.
```dart
  final ReceivePort resultPort = ReceivePort();
  final ReceivePort exitPort = ReceivePort();
  final ReceivePort errorPort = ReceivePort();
```
When I created an exact copy of the compute function and then added `exitPort.close();` it started working and instances are now properly released from memory.

Solution:
```dart
Future<R> compute<Q, R>(ComputeCallback<Q, R> callback, Q message,
    {String? debugLabel}) async {
  debugLabel ??= kReleaseMode ? 'compute' : callback.toString();
  final Flow flow = Flow.begin();
  Timeline.startSync('$debugLabel: start', flow: flow);
  final ReceivePort resultPort = ReceivePort();
  final ReceivePort exitPort = ReceivePort();
  final ReceivePort errorPort = ReceivePort();
  Timeline.finishSync();
  final Isolate isolate =
      await Isolate.spawn<_IsolateConfiguration<Q, FutureOr<R>>>(
    _spawn,
    _IsolateConfiguration<Q, FutureOr<R>>(
      callback,
      message,
      resultPort.sendPort,
      debugLabel,
      flow.id,
    ),
    errorsAreFatal: true,
    onExit: exitPort.sendPort,
    onError: errorPort.sendPort,
  );
  final Completer<R> result = Completer<R>();
  errorPort.listen((dynamic errorData) {
    assert(errorData is List<dynamic>);
    assert(errorData.length == 2);
    final Exception exception = Exception(errorData[0]);
    final StackTrace stack = StackTrace.fromString(errorData[1] as String);
    if (result.isCompleted) {
      Zone.current.handleUncaughtError(exception, stack);
    } else {
      result.completeError(exception, stack);
    }
  });
  exitPort.listen((dynamic exitData) {
    if (!result.isCompleted) {
      result
          .completeError(Exception('Isolate exited without result or error.'));
    }
  });
  resultPort.listen((dynamic resultData) {
    assert(resultData == null || resultData is R);
    if (!result.isCompleted) result.complete(resultData as R);
  });
  await result.future;
  Timeline.startSync('$debugLabel: end', flow: Flow.end(flow.id));
  resultPort.close();
  errorPort.close();
  exitPort.close(); // <----------- I added just this line
  isolate.kill();
  Timeline.finishSync();
  return result.future;
}
```

### PR DESCRIPTION
**Pull request by jason-simmons**
Receive ports are tracked in a static map within the Dart SDK until the
port is closed.  The map will hold references to handler closures,
which in turn may retain references to objects in the closure's context.

Fixes https://github.com/flutter/flutter/issues/86470

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
Looks good but needs a test

**Comment by jason-simmons** [comment]
Any suggestions on how to test this?

Ideally I'd like to force a GC and confirm that the isolate and the result object returned by `compute` have been finalized.  But Dart does not yet have the runtime services needed to verify that.

**Comment by dnfield** [comment]
I'm pretty sure if you directly import this file and call compute from a regular dart program it will hang. After this change it will exit normally

**Comment by jason-simmons** [comment]
That works.  Added a test that spawns a Dart script that calls `compute`.

File: packages/flutter/test/foundation/isolates_test.dart [hunk 1]
```diff
@@ -29,4 +33,23 @@ void main() {
...
+    const FileSystem fs = LocalFileSystem();
+    const Platform platform = LocalPlatform();
+    final String flutterRoot = platform.environment['FLUTTER_ROOT']!;
+    final String dartPath = fs.path.join(flutterRoot, 'bin', 'cache', 'dart-sdk', 'bin', 'dart');
+    final String packageRoot = fs.path.dirname(fs.path.fromUri(platform.script));
+    final String scriptPath = fs.path.join(packageRoot, 'test', 'foundation', '_compute_caller.dart');
+    final Future<ProcessResult> resultFuture = Process.run(dartPath, <String>[scriptPath]);
+    final ProcessResult? result = await Future.any(<Future<ProcessResult?>>[
+      resultFuture,
+      Future<ProcessResult?>.delayed(const Duration(seconds: 5), null),
```
Comment (dnfield) [inline packages/flutter/test/foundation/isolates_test.dart:50]: When CI is under heavy load this might not be enough time. I think this is probably a case where we want to time out faste rthan the test timeout, but it should probably be a few minutes to be safe rather than a few seconds. Then again, the style guide says to just not use timeouts like this so maybe we should just let the test timeout be it.

File: packages/flutter/test/foundation/_compute_caller.dart [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// A test script that invokes compute() to start an isolate.
```
Comment (dnfield) [inline packages/flutter/test/foundation/_compute_caller.dart:1]: Needs a license header.

File: packages/flutter/test/foundation/isolates_test.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/test/foundation/isolates_test.dart:50]: Actually I'm pretty sure we don't override the default tester timeout of 30s for these types of tests right now, which should be sufficient.

Comment (jason-simmons) [reply packages/flutter/test/foundation/isolates_test.dart]: done

File: packages/flutter/test/foundation/_compute_caller.dart (hunk 2 above)
Comment (jason-simmons) [reply packages/flutter/test/foundation/_compute_caller.dart:5]: done

**Review by dnfield — APPROVED** [review]
LGTM
