### PR TITLE
Fix stack trace parsing on non-debug builds; add e2e tests

### LINKED ISSUE #48909: Uncaught TypeError: Cannot read property '_match' of undefined
## Steps to Reproduce

Run a Flutter Web app that throws any exception using `--profile` or `--release`.

**Expected results:** 

The exception and stack trace should be printed to the console.

**Actual results:** 

```
main.dart.js:10219 Uncaught TypeError: Cannot read property '_match' of undefined
    at Object.StackFrame_fromStackTraceLine (main.dart.js:10219)
    at Object.FlutterError_defaultStackFilter (main.dart.js:19622)
    at Object.DiagnosticsStackTrace$ (main.dart.js:19658)
    at FlutterErrorDetails.debugFillProperties$1 (main.dart.js:43449)
    at _FlutterErrorDetailsNode.get$builder (main.dart.js:44766)
    at _FlutterErrorDetailsNode.get$builder (main.dart.js:43522)
    at _FlutterErrorDetailsNode.getProperties$0 (main.dart.js:44781)
    at TextTreeRenderer.render$4$parentConfiguration$prefixLineOne$prefixOtherLines (main.dart.js:44167)
    at TextTreeRenderer.render$1 (main.dart.js:44290)
    at Object.FlutterError_dumpErrorToConsole (main.dart.js:19610)
```

It looks like the format of dart2js StackTraces differs from DDC, so we are failing to match and throwing here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/stack_frame.dart#L85

In my example app, the line it is trying to match is `TypeError: Cannot perform Construct on a detached ArrayBuffer`.

We should fix StackTrace parsing for release mode.

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Fix stack trace parsing on non-debug builds; add e2e tests.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/48909

## Tests

I added the following tests:

`dev/integration_tests/web/lib/stack_trace.dart`, an integration test that checks our ability to parse stack traces in debug, profile, and release modes.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by yjbanov** [comment]
So every doesn't have to look at everything we can split the review into the following areas:

- @dnfield could check the stack trace parsing logic and the corresponding test.
- @jonahwilliams could check `flutter_tools` changes.
- @nturgut could check the browser launching changes (the code is now shared between benchmarks and the test).

File: packages/flutter/lib/src/foundation/stack_frame.dart [hunk 1]
```diff
@@ -120,6 +133,50 @@ class StackFrame {
...
   }
 
+  // Parses `line` as a stack frame in profile and release Web builds. If not
+  // recognized as a stack frame, returns null.
+  static StackFrame _parseWebNonDebugFrame(String line) {
+    // Non-debug builds do not point to dart code but compiled JavaScript, so
+    // line numbers are meaningless. We only attempt to parse the class and
+    // method name, which is more or less readable in profile builds, and
+    // minified in release builds.
+    final RegExp parser = RegExp(r'^\s*at ([^\s]+).*$');
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/foundation/stack_frame.dart]: Make this RegExp static

**Comment by yjbanov** [comment]
BTW, I'm still debugging these changes on Cirrus, but everything is passing on my local workstation so it should good enough for review.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 2]
```diff
@@ -173,6 +173,15 @@ abstract class FlutterCommand extends Command<void> {
         'when running on remote machines.',
       hide: hide,
     );
+    argParser.addFlag('web-run-headless',
+      defaultsTo: false,
+      help: 'Launches the browser in headless mode.',
+      hide: true,
+    );
+    argParser.addOption('web-browser-debug-port',
+      help: 'The debug port the browser should use. If not specified, a random port is selected.',
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Specify it is only for chrome devtools

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 3]
```diff
@@ -117,7 +117,7 @@ class ChromeLauncher {
       }
     }
 
-    final int port = await globals.os.findFreePort();
+    final int port = debugPort ?? await globals.os.findFreePort();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart]: Should be some existing tests for chrome, you'll want to verify that we use the right port in the launch command. I recomend something with FakeProcessManager.list(<FakeCommand>[...expected launch command])

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 2 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Is it always going to be Chrome-only? How about "on browsers that support it"? This option is hidden anyway. The expectation is that the user knows what they are doing.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Probably, I would still specify. This is documentation for the tools team too, someone who isn't experience on the web isn't going to known chrome devtools vs other browsers

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter/lib/src/foundation/stack_frame.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter/lib/src/foundation/stack_frame.dart]: Done.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 2 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done.

**Review by jonahwilliams — APPROVED** [review]
tools LGTM

**Review by dnfield — APPROVED** [review]
LGTM

File: dev/devicelab/lib/framework/browser.dart [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+    _isStopped = true;
+    _chromeProcess.kill();
+  }
+}
+
+String _findSystemChromeExecutable() {
+  // On some environments, such as the Dart HHH tester, Chrome resides in a
+  // non-standard location and is provided via the following environment
+  // variable.
+  final String envExecutable = io.Platform.environment['CHROME_EXECUTABLE'];
```
Comment (nturgut) [inline dev/devicelab/lib/framework/browser.dart]: note: since this only uses the version available on the system and on the engine we are running a pinned version, the results might be different. 

Can you add a printout saying which version of chrome is being used? (If it is easy to do)

Therefore if something fails unexpectedly we can also compare the versions by looking at the log.

**Review by nturgut — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Debug stack trace fix in https://github.com/flutter/flutter/pull/50680

File: dev/devicelab/lib/framework/browser.dart (hunk 4 above)
Comment (yjbanov) [reply dev/devicelab/lib/framework/browser.dart]: Good idea. Done.
