### PR TITLE
Fix DropdownMenu example RenderFlex overflowed error

### LINKED ISSUE #162506: DropdownMenu's example encounters layout error when being putted in small frame (docs page)
### Steps to reproduce

1. Open DropdownMenu docs page: https://api.flutter.dev/flutter/material/DropdownMenu-class.html (or even in its main docs: https://main-api.flutter.dev/flutter/material/DropdownMenu-class.html)
2. Click on Run button at the first/only example and observe RenderFlex overflowed error

This is also reproducible with following steps in local:
1. RunDropdownMenu sample code in web target
2. Open developer tab (F12) and toggle device toolbar
3. Scale app's window size to be smaller as demo video below

### Expected results

RenderFlex overflowed error should not appear

### Actual results

RenderFlex overflowed appears:
Image

### Code sample

<details open><summary>Code sample (original official example)</summary>

```dart
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';

// Flutter code sample for [DropdownMenu]s. The first dropdown menu
// has the default outlined border and demos using the
// [DropdownMenuEntry] style parameter to customize its appearance.
// The second dropdown menu customizes the appearance of the dropdown
// menu's text field with its [InputDecorationTheme] parameter.

void main() {
  runApp(const DropdownMenuExample());
}

typedef ColorEntry = DropdownMenuEntry<ColorLabel>;

// DropdownMenuEntry labels and values for the first dropdown menu.
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;

  static final List<ColorEntry> entries = UnmodifiableListView<ColorEntry>(
    values.map<ColorEntry>(
      (ColorLabel color) => ColorEntry(
        value: color,
        label: color.label,
        enabled: color.label != 'Grey',
        style: MenuItemButton.styleFrom(
          foregroundColor: color.color,
        ),
      ),
    ),
  );
}

typedef IconEntry = DropdownMenuEntry<IconLabel>;

// DropdownMenuEntry labels and values for the second dropdown menu.
enum IconLabel {
  smile('Smile', Icons.sentiment_satisfied_outlined),
  cloud('Cloud', Icons.cloud_outlined),
  brush('Brush', Icons.brush_outlined),
  heart('Heart', Icons.favorite);

  const IconLabel(this.label, this.icon);
  final String label;
  final IconData icon;

  static final List<IconEntry> entries = UnmodifiableListView<IconEntry>(
    values.map<IconEntry>(
      (IconLabel icon) => IconEntry(
        value: icon,
        label: icon.label,
        leadingIcon: Icon(icon.icon),
      ),
    ),
  );
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  final TextEditingController iconController = TextEditingController();
  ColorLabel? selectedColor;
  IconLabel? selectedIcon;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownMenu<ColorLabel>(
                      initialSelection: ColorLabel.green,
                      controller: colorController,
                      // requestFocusOnTap is enabled/disabled by platforms when it is null.
                      // On mobile platforms, this is false by default. Setting this to true will
                      // trigger focus request on the text field and virtual keyboard will appear
                      // afterward. On desktop platforms however, this defaults to true.
                      requestFocusOnTap: true,
                      label: const Text('Color'),
                      onSelected: (ColorLabel? color) {
                        setState(() {
                          selectedColor = color;
                        });
                      },
                      dropdownMenuEntries: ColorLabel.entries,
                    ),
                    const SizedBox(width: 24),
                    DropdownMenu<IconLabel>(
                      controller: iconController,
                      enableFilter: true,
                      requestFocusOnTap: true,
                      leadingIcon: const Icon(Icons.search),
                      label: const Text('Icon'),
                      inputDecorationTheme: const InputDecorationTheme(
                        filled: true,
                        contentPadding: EdgeInsets.symmetric(vertical: 5.0),
                      ),
                      onSelected: (IconLabel? icon) {
                        setState(() {
                          selectedIcon = icon;
                        });
                      },
                      dropdownMenuEntries: IconLabel.entries,
                    ),
                  ],
                ),
              ),
              if (selectedColor != null && selectedIcon != null)
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                        'You selected a ${selectedColor?.label} ${selectedIcon?.label}'),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 5),
                      child: Icon(
                        selectedIcon?.icon,
                        color: selectedColor?.color,
                      ),
                    )
                  ],
                )
              else
                const Text('Please select a color and an icon.')
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/91c82b7c-3449-4b65-9b7a-547030dd6536

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 69 pixels on the right.

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#016b0 relayoutBoundary=up4 OVERFLOWING:
  needs compositing
  creator: Row ← Padding ← Column ← MediaQuery ← Padding ← SafeArea ← KeyedSubtree-[GlobalKey#15c81] ←
    _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ←
    _ActionsScope ← ⋯
  parentData: offset=Offset(0.0, 20.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=265.0, 0.0<=h<=Infinity)
  size: Size(265.0, 48.0)
  direction: horizontal
  mainAxisAlignment: center
  mainAxisSize: max
  crossAxisAlignment: center
  textDirection: ltr
  verticalDirection: down
  spacing: 0.0
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.29.0-1.0.pre.193, on macOS 15.3 24D60 darwin-x64, locale en-VN) [3.6s]
    • Flutter version 3.29.0-1.0.pre.193 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 157f71d4ad (2 hours ago), 2025-01-31 18:14:54 +1100
    • Engine revision 157f71d4ad
    • Dart version 3.8.0 (build 3.8.0-24.0.dev)
    • DevTools version 2.42.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [8.3s]
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_SDK_ROOT = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [3.9s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [356ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3.1) [354ms]
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12771278-b631.28)

[✓] Android Studio (version 2024.2) [348ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] IntelliJ IDEA Community Edition (version 2024.2.3) [347ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.96.4) [51ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (2 available) [9.3s]
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.3 24D60 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 132.0.6834.160
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,906ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
Fix https://github.com/flutter/flutter/issues/162506

| before | after |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/91c82b7c-3449-4b65-9b7a-547030dd6536"/> | 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart [hunk 1]
```diff
@@ -70,4 +71,40 @@ void main() {
...
+    await tester.tap(menuSmile);
+    await tester.pumpAndSettle();
+
+    expect(find.text('You selected a Blue Smile'), findsOneWidget);
+
+    // resize the screen to small screen and make sure no overflowed error appears
+    tester.binding.window.physicalSizeTestValue = const Size(200, 160);
+    tester.binding.window.devicePixelRatioTestValue = 1.0;
+    addTearDown(tester.binding.window.clearPhysicalSizeTestValue);
+
```
Comment (PurplePolyhedron) [inline examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart:107]:
```suggestion
    await tester.pump();
```
Otherwise the widget will not update after the size change and this test would still pass without the fix.
Or perhaps change the size of window at the start of the test?

**Review by PurplePolyhedron — COMMENTED** [review]
Scrolling is a valid choice. I personally think wrapping could fit a small screen better, but the implementation is complex so it could take focus away from the `DropdownMenu` example.

File: examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart [hunk 2]
```diff
@@ -70,4 +71,40 @@ void main() {
...
+    expect(find.byType(RenderFlex), findsNothing);
```
[the remark this answers is not in the document]
Comment (bleroux) [reply examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart:108]: > find.byType can only find Widget, not RenderObject.

Good catch!

Instead of searching for a RenderFlex, consider testing if an exception was thrown:
```dart
    expect(tester.takeException(), null);
```

File: examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart [hunk 3]
```diff
@@ -70,4 +71,40 @@ void main() {
...
+    await tester.tap(iconMenu);
+    await tester.pumpAndSettle();
+    final Finder menuSmile = findMenuItem('Smile');
+    await tester.ensureVisible(menuSmile);
+    await tester.tap(menuSmile);
+    await tester.pumpAndSettle();
+
+    expect(find.text('You selected a Blue Smile'), findsOneWidget);
+
+    // resize the screen to small screen and make sure no overflowed error appears
```
Comment (bleroux) [inline examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart:103]:
```suggestion
    // Resize the screen to small screen and make sure no overflowed error appears.
```

File: examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart [hunk 4]
```diff
@@ -84,56 +84,64 @@ class _DropdownMenuExampleState extends State<DropdownMenuExample> {
...
+                    mainAxisSize: MainAxisSize.min,
+                    mainAxisAlignment: MainAxisAlignment.center,
+                    children: <Widget>[
+                      DropdownMenu<ColorLabel>(
+                        initialSelection: ColorLabel.green,
+                        controller: colorController,
+                        // requestFocusOnTap is enabled/disabled by platforms when it is null.
+                        // On mobile platforms, this is false by default. Setting this to true will
+                        // trigger focus request on the text field and virtual keyboard will appear
+                        // afterward. On desktop platforms however, this defaults to true.
```
Comment (TahaTesser) [inline examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart:99]:
```suggestion
                        // The default requestFocusOnTap value depends on the platform.
                        // On mobile, it defaults to false, and on desktop, it defaults to true. 
                        // Setting this to true will trigger a focus request on the text field, and
                        // the virtual keyboard will appear afterward.
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Rephrased this comment

File: examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart (hunk 1 above)
Comment (huycozy) [reply examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart:107]: > Or perhaps change the size of window at the start of the test?

Actually, there are two overflowed errors: one at DropdownMenu row, one at the output result row `You selected a`. Thus, I needed to produce all error by selecting dropdown value too.
 I need to put the resize section afterward because it can't select value in the 2nd dropdown if the window is too small. 

Anyway, thank you for your suggestion about `tester.pump()`.

File: examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (huycozy) [reply examples/api/test/material/dropdown_menu/dropdown_menu.0_test.dart:108]: Thank you guys. Bruno's suggestion is a good one here

File: examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart (hunk 4 above)
Comment (huycozy) [reply examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart:99]: Thank Taha! I am just wondering whether this should be updated here in this PR or better in a separate PR?

**Review by bleroux — APPROVED** [review]
LGTM!

**Review by TahaTesser — APPROVED** [review]
LGTM
