### PR TITLE
Wraps all `git` executions in a `Git(...).*`, use `*=noglob` on Windows

### LINKED ISSUE #74165: fatal: Needed a single revision - upgrade fails on Windows 10
## Steps to Reproduce

1. Download and unzip into a directory, e.g. D:\personal-dev\flutter
2. Set PATH env var to include flutter\bin, e.g. D:\personal-dev\flutter\bin
3. run flutter channel stable
```bash
D:\personal-dev\flutter>flutter channel stable
Downloading package sky_engine...                                   0.5s
Downloading flutter_patched_sdk tools...                            0.5s
Downloading flutter_patched_sdk_product tools...                    0.4s
Downloading windows-x64 tools...                                    0.9s
Downloading windows-x64/font-subset tools...                        0.1s
Switching to flutter channel 'stable'...
git: Already on 'stable'
git: Your branch is up to date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
```
4. run flutter upgrade
```bash
D:\personal-dev\flutter>flutter upgrade -v
[ +123 ms] executing: [D:\personal-dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +125 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 78910062997c3a836feee883712c241a5fd22983
[   +1 ms] executing: [D:\personal-dev\flutter/] git tag --points-at HEAD
[ +107 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.5
[  +20 ms] executing: [D:\personal-dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +84 ms] executing: [D:\personal-dev\flutter/] git tag --points-at HEAD
[ +102 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[   +3 ms] executing: [D:\personal-dev\flutter/] git fetch --tags
[+1604 ms] executing: [D:\personal-dev\flutter/] git rev-parse --verify @{u}
[  +87 ms] fatal: Needed a single revision
[  +11 ms] "flutter upgrade" took 1,831ms.
[   +5 ms] ProcessException: Process exited abnormally:
           fatal: Needed a single revision
             Command: git rev-parse --verify @{u}
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      UpgradeCommandRunner.fetchRemoteRevision (package:flutter_tools/src/commands/upgrade.dart:237:9)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:103:43)
           #3      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
           #4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #6      _rootRunUnary (dart:async/zone.dart:1198:47)
           #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #13     _rootRun (dart:async/zone.dart:1190:13)
           #14     _CustomZone.run (dart:async/zone.dart:1093:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +185 ms] ensureAnalyticsSent: 182ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
This seems to be a problem related to the stable git repo?

<details>

<summary>Logs</summary>

```bash
D:\personal-dev\flutter>flutter doctor -v
[✓] Flutter (Channel @u, 1.22.5, on Microsoft Windows [Version 10.0.19582.1001], locale en-CA)
    • Flutter version 1.22.5 at D:\personal-dev\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\bdillman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/74165.

The original issue called for, on Windows, telling `CYGWIN` to use `=noglob`, to work around some git operation errors that happen when using non-native Git. There ... was no great way to do this with the existing codebase without, IMO, adding lots of confusing code.

So, I refactored all the calls of:
- before: `processUtils.<method>(['git', ...args], ...params)` 
- after: `git.<method>([...args], ...params)`

... and implicitly add the new environment variables, if `Platform.isWindows`.

Did some minor test cleanup and process execution cleanup while I was at it.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -325,14 +329,14 @@ class UpgradeCommandRunner {
     String revision;
     try {
       // Fetch upstream branch's commits and tags
-      await globals.processUtils.run(
-        <String>['git', 'fetch', '--tags'],
+      await globals.git.run(
+        <String>['fetch', '--tags'],
```
Comment (chingjun) [inline packages/flutter_tools/lib/src/commands/upgrade.dart]: Nit: Remove the `<String>` to be consistent with the rest of the changes in this file. Same on line 339.

File: packages/flutter_tools/lib/src/git.dart [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+import 'base/platform.dart';
+import 'base/process.dart';
+import 'convert.dart';
+
+/// Wrapper around the command-line `git` executable on the host.
+interface class Git {
+  /// Creates a wrapper that executes `git` using [runProcessWith].
+  Git({
+    required Platform currentPlatform,
+    required ProcessUtils runProcessWith, //
```
Comment (chingjun) [inline packages/flutter_tools/lib/src/git.dart]: Remove the `//`?

File: packages/flutter_tools/lib/src/version.dart [hunk 3]
```diff
@@ -97,34 +99,40 @@ abstract class FlutterVersion {
...
 
-  FlutterVersion._({required SystemClock clock, required this.flutterRoot, required this.fs})
-    : _clock = clock;
+  FlutterVersion._({
+    required SystemClock clock,
+    required Git git,
+    required this.flutterRoot,
+    required this.fs,
+  }) : _clock = clock,
+       _gitExecutable = git;
```
Comment (chingjun) [inline packages/flutter_tools/lib/src/version.dart]: Any reason to call this `_gitExecutable` instead of `_git` like everywhere else?

**Review by chingjun — APPROVED** [review]
LGTM with minor nits.

File: packages/flutter_tools/lib/src/version.dart (hunk 3 above)
Comment (matanlurey) [reply packages/flutter_tools/lib/src/version.dart]: Changed!

File: packages/flutter_tools/lib/src/git.dart (hunk 2 above)
Comment (matanlurey) [reply packages/flutter_tools/lib/src/git.dart]: Done!
