### PR TITLE
Don't attempt to draw invisible overflow indicator

### LINKED ISSUE #12532: Column/Row shouldn't overflow assert if they are given a 0.0 size in their flex direction.
```
[00015.474] 06320.06345>  EXCEPTION CAUGHT BY RENDERING LIBRARY 
[00015.479] 06320.06345> The following message was thrown during layout:
[00015.479] 06320.06345> A horizontal RenderFlex overflowed by 64 pixels.
[00015.493] 06320.06345> 
[00015.493] 06320.06345> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[00015.493] 06320.06345> black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[00015.493] 06320.06345> Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[00015.493] 06320.06345> RenderFlex to fit within the available space instead of being sized to their natural size.
[00015.493] 06320.06345> This is considered an error condition because it indicates that there is content that cannot be
[00015.493] 06320.06345> seen. If the content is legitimately bigger than the available space, consider clipping it with a
[00015.493] 06320.06345> RectClip widget before putting it in the flex, or using a scrollable container rather than a Flex,
[00015.493] 06320.06345> for example using ListView.
[00015.493] 06320.06345> The specific RenderFlex in question is:
[00015.494] 06320.06345>   RenderFlex#22903 relayoutBoundary=up1 OVERFLOWING
[00015.494] 06320.06345>   creator: Row  Column  ScopedModelDescendant<NetstackModel>  _NetstackInfo  Padding  Container
[00015.494] 06320.06345>    PhysicalModel  Padding  Container  Align 
[00015.494] 06320.06345>   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#20e49]  Stack  
[00015.494] 06320.06345>   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
[00015.494] 06320.06345>   constraints: BoxConstraints(w=0.0, 0.0<=h<=Infinity)
[00015.494] 06320.06345>   size: Size(0.0, 16.0)
[00015.494] 06320.06345>   direction: horizontal
[00015.494] 06320.06345>   mainAxisAlignment: start
[00015.494] 06320.06345>   mainAxisSize: min
[00015.494] 06320.06345>   crossAxisAlignment: center
[00015.494] 06320.06345>   textDirection: ltr
[00015.494] 06320.06345>   verticalDirection: down
```

### PR DESCRIPTION
**Pull request by abarth**
If the flex is empty, there's no space in which to draw the overflow indicator,
so we shouldn't bother trying to draw it.

Fixes #12532

### CODE REVIEW

**Comment by Hixie** [comment]
I don't really understand why a flex with width 0.01px should dump a log message but a flex with width 0.0 should not.

**Comment by abarth** [comment]
> I don't really understand why a flex with width 0.01px should dump a log message but a flex with width 0.00 should not.

I'll give you two arguments:

1. The message exists to explain the debug drawing.  If the drawing is 100% invisible, then there's nothing to explains.
2. This message spams during startup because we often layout at 0x0 during startup.

**Comment by Hixie** [comment]
If the drawing is 100% invisible, then isn't that even more of a bug? It means we're wasting time doing building and layout that's pointless.

For the 0x0 startup, our previous position has been that we intentionally aren't fixing that because we want app authors to be able to handle a variety of app sizes, including changing size.

**Comment by abarth** [comment]
> If the drawing is 100% invisible, then isn't that even more of a bug? It means we're wasting time doing building and layout that's pointless.

At build time, we don't know what the size is going to be, so we can't cut off build.  We can't cut off layout because it has side-effect.  We could cut off the paint walk if you like.

> For the 0x0 startup, our previous position has been that we intentionally aren't fixing that because we want app authors to be able to handle a variety of app sizes, including changing size.

@apwilson says that his app doesn't support below a minimum size, which is reasonable because a different app would be selected for those cases (e.g., on a watch).

File: packages/flutter/lib/src/rendering/flex.dart [hunk 1]
```diff
@@ -975,6 +975,10 @@ class RenderFlex extends RenderBox with ContainerRenderObjectMixin<RenderBox, Fl
     context.pushClipRect(needsCompositing, offset, Offset.zero & size, defaultPaint);
 
     assert(() {
+      // There's no point in drawing the overflow indicator if we're empty.
+      if (size.isEmpty)
+        return true;
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/flex.dart]: As discussed at lunch, we should just do this at the top level (not even attempt to paint children in this case).

**Comment by abarth** [comment]
> As discussed at lunch, we should just do this at the top level (not even attempt to paint children in this case).

Done.  PTAL.

**Comment by Hixie** [comment]
I would probably have put the isEmpty check above the overflow<0 check, since if it's empty and you don't have overflow, you probably don't have anything to paint at all.

But either way, LGTM.

**Comment by abarth** [comment]
> I would probably have put the isEmpty check above the overflow<0 check,

I left it below as a premature optimization to avoid the isEmpty check in the common case where there isn't any overflow.
