### PR TITLE
[iOS] Do not hide selection handles when platform hides system context menu

### LINKED ISSUE #168636: [iOS] Selection handles sometimes disappear while quickly dragging in TextField/CupertinoTextField
### Steps to reproduce

1. Create a minimal Flutter app containing a single TextField/CupertinoTextField(see code below).

2. Type a few words, then double-tap to place the caret and bring up the selection handles.

3. Quickly drag either selection handle left ↔ right several times.

### Expected results

Selection handles should remain visible and track the user’s finger, even during very fast drags—matching native iOS behaviour.

### Actual results

While dragging at high speed, the selection handles (and the system-style context menu) vanish unexpectedly.
Text selection is lost until the user lifts their finger and double taps again.

---
I don´t know if it helps but, the disappearance originates in ServicesBinding._handlePlatformMessage:

```dart
// Called when the system dismisses the system context menu, such as when
// the user taps outside the menu…
case 'ContextMenu.onDismissSystemContextMenu':
  if (_systemContextMenuClient == null) {
    assert(false,
      'Platform sent onDismissSystemContextMenu when no SystemContextMenuClient was registered.');
    return;
  }
  _systemContextMenuClient!.handleSystemHide();
  _systemContextMenuClient = null;
  break;

```
According to the comment, this callback should fire only when the user taps outside the menu.
However, a fast drag gesture appears to be interpreted as such a tap, triggering handleSystemHide() and clearing _systemContextMenuClient, which in turn hides both the context menu and the selection handles.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
     return const CupertinoApp(
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text('TextField Selection Issue'),
        ),
        child: Center(
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 24),
            child: CupertinoTextField(),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Flutter App:

https://github.com/user-attachments/assets/350aba4f-ec4e-405d-a109-351c1576890b

Native iOS App:

https://github.com/user-attachments/assets/78694aca-9208-47fc-aafd-b0c1e6c116bb

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.32.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3bd718ee44 (10 days ago) • 2025-04-30 10:11:08 -0700
Engine • revision 453dd7174c (11 days ago) • 2025-04-29 21:15:41 -0700
Tools • Dart 3.8.0 (build 3.8.0-278.2.beta) • DevTools 2.45.1
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes an issue where selection handles would be hidden when the system hides the platform context menu on iOS.

Before:

https://github.com/user-attachments/assets/61afecd8-7558-41fb-bba3-74b6e8e47f13

After:

https://github.com/user-attachments/assets/0c6f83de-cb20-46ce-97d3-86d8873da3aa

Fixes #168636

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
There is another interesting issue I noticed with the system context menu while working on this PR.

On the framework side we have implemented toggling the selection toolbar when tapping on the current selection. This does not work with the system context menu as seen in the video in this PR's description, tapping the selection hides the toolbar but immediately shows it again after. This happens because first the system dismisses the platform context menu when the tap happens outside the context menu (tap on the selection), the framework then responds to this by hiding the context menu. The framework also then responds to the tap on the selection and tries to toggle the toolbar, this ends up bringing up the toolbar again. The expected behavior would have been for the tap on the selection to hide the toolbar and not reshow it until a subsequent tap. I'll open an issue for this, this PR only solves the selection handles being hidden.

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 1]
```diff
@@ -83,7 +83,7 @@ class SystemContextMenu extends StatefulWidget {
         ),
       ),
       items: items ?? getDefaultItems(editableTextState),
-      onSystemHide: editableTextState.hideToolbar,
+      onSystemHide: () => editableTextState.hideToolbar(false),
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/system_context_menu.dart:86]: Hm in hindsight it'd be nice if this was a named argument instead of a positional argument. It's hard to tell that boolean sets the handle visibility.

**Review by loic-sharma — APPROVED** [review]
Thanks for fixing this so quick! Also, great tests :)

File: packages/flutter/lib/src/widgets/system_context_menu.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/system_context_menu.dart:86]: Definitely agree with this. I kind of wish the hideToolbar method didn't do this at all and that there was a separate method to hide the handles, or that the method had a more appropriate name. SelectionOverlay and TextSelectionOverlay expose a hideHandles but we don't expose it at the editable text level.

**Comment by Renzo-Olivares** [comment]
Thanks for the review!
