### PR TITLE
Reset framesEnabled to default value at the end of each test

### LINKED ISSUE #141835: SchedulerBinding's framesEnabled state leaks between tests
### Steps to reproduce

In a widget test, calling `tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.paused);` in an earlier test may cause subsequent tests to fail because `tester.binding.framesEnabled` is not reset to true

When app lifecyclestate is paused, [`framesEnabled` is set to false](https://github.com/flutter/flutter/blob/70a4a5de7c646372770280817e1c2d9775b0b254/packages/flutter/lib/src/scheduler/binding.dart#L419-L421) but it is [not reset to initial value](https://github.com/flutter/flutter/blob/70a4a5de7c646372770280817e1c2d9775b0b254/packages/flutter/lib/src/scheduler/binding.dart#L397-L399) between tests

### Expected results

`tester.binding.framesEnabled` should be true at the start of every test

### Actual results

`tester.binding.framesEnabled` state can be false at the start of a test due to effects from previous unrelated tests

### Code sample

<details open><summary>Code sample</summary>

Test showing `framesEnabled` has leaky state:
```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  var lifecycleStateChanged = false;

  testWidgets('set app lifecycle state to paused', (tester) async {
    expect(tester.binding.framesEnabled, isTrue);

    tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.paused);
    lifecycleStateChanged = true;
  });

  testWidgets('framesEnabled should be true', (tester) async {
    // In case `testWidgets` runs out of order.
    expect(lifecycleStateChanged, isTrue);

    // Should pass but actually fails because of the previous test
    expect(tester.binding.framesEnabled, isTrue);
  });
}
```

----

Example of test that fails because of `framesEnabled` being false:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('set app lifecycle state to paused', (tester) async {
    tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.paused);
  });

  testWidgets('fails unless comment out previous test or uncomment line 10',
      (tester) async {
    // tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.resumed);
    await tester.createWidget(() => const SizedBox());
  });
}

extension WidgetTesterExtension on WidgetTester {
  Future<Widget> createWidget(Widget Function() builder) async {
    late Widget result;

    final testWidget = Builder(
      builder: (_) {
        result = builder();
        return result;
      },
    );

    await pumpWidget(testWidget);

    return result;
  }
}
```
Earlier test sets app lifecycle state to `paused` which causes `framesEnabled` to be false. This causes `await pumpWidget(testWidget)` in the subsequent test to not do anything which causes late Widget result to never be initialised, thus causing `LateInitializationError`

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
-
```

</details>

### PR DESCRIPTION
**Pull request by aizatazhar**
Reset `framesEnabled` to `true` at the end of each test as otherwise subsequent tests may fail when pumping a widget

Fixes #141835 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 1]
```diff
@@ -391,11 +391,12 @@ mixin SchedulerBinding on BindingBase {
   AppLifecycleState? get lifecycleState => _lifecycleState;
   AppLifecycleState? _lifecycleState;
 
-  /// Allows the test framework to reset the lifecycle state back to its
-  /// initial value.
+  /// Allows the test framework to reset the lifecycle state and framesEnabled
+  /// back to their initial values.
   @visibleForTesting
-  void resetLifecycleState() {
+  void clearState() {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/scheduler/binding.dart:397]: Maybe `resetInternalState`? Some future state might not be "cleared" when it is reset, it might be returned to an initial value instead.

Comment (aizatazhar) [reply packages/flutter/lib/src/scheduler/binding.dart]: Done!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by justinmc — APPROVED** [review]
LGTM :+1:
