### PR TITLE
Fix Listenable.merge to not leak

### LINKED ISSUE #25163: Listener leak when using Listenable.merge with an AnimationController
Example code looks something like this:

Widget:
```dart
final myAnimationController = AnimationController(...);

// in build: 
AnimatedBuilder(
  animation: Listenable.merge(
    <Listenable>[
      myAnimationController,
    ],
  ),
  builder: ... );
```

myAnimationController will get more and more listeners each time that AnimatedBuilder is added to the Widget tree and it will never go back down.

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/25163.

This also changes `animation/listener_helpers.dart` to be ok with multiple calls to `remove*Listener` for the same (already removed) listener to fix failing tests due to this change.

### CODE REVIEW

File: packages/flutter/test/foundation/change_notifier_test.dart [hunk 1]
```diff
@@ -180,21 +182,21 @@ void main() {
     log.clear();
   });
 
-  test('Can dispose merged notifier', () {
+  test('Can remove from merged notifier', () {
     final TestNotifier source1 = TestNotifier();
     final TestNotifier source2 = TestNotifier();
     final List<String> log = <String>[];
 
-    final ChangeNotifier merged = Listenable.merge(<Listenable>[source1, source2]);
```
Comment (Hixie) [inline packages/flutter/test/foundation/change_notifier_test.dart]: oh wow, it's scary that the analyzer didn't catch that

**Comment by Hixie** [comment]
LGTM
