### PR TITLE
[flutter_tools] use new output location for the apk

### LINKED ISSUE #13977: Flutter tooling should take heed of archivesBaseName
That property can be set by custom Gradle configuration, and will result in a "Gradle failed to produce an Android package" error.

See https://github.com/flutter/flutter/issues/11866#issuecomment-351951650

### LINKED ISSUE #29509: Rename apk when flutter build
Is there any way to change apk name instead of default app-debug.apk when run "flutter build apk --debug or --release"?

### LINKED ISSUE #44796: Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\Flutter_App\MYAPP\build, but the tool couldn't find it.
My flutter app not able to start after upgrade flutter version.

Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\Flutter_App\team37\build, but the tool couldn't find it.
Exited (sigterm)

[√] Flutter (Channel dev, v1.10.16, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
    • Flutter version 1.10.16 at C:\src\flutter
    • Framework revision 798e4272a2 (6 days ago), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

```
```

### LINKED ISSUE #52905: Bug with Flutter flavours when using multiple dimensions
## Steps to Reproduce

1. Run `$ flutter create flutter_bug`
2. Update the files as follows:

**`android/app/build.gradle`**
```
...
android {
    ...
    flavorDimensions "tenant", "environment"
    productFlavors {
        app1 {
            dimension "tenant"
            applicationId "uk.co.myapplication.app1"
        }

        app2 {
            dimension "tenant"
            applicationId "uk.co.myapplication.app2"
        }

        local {
            dimension "environment"
            resValue "string", "app_name", "Local"
        }

        staging {
            dimension "environment"
            resValue "string", "app_name", "Staging"
        }
    }
}
...
```

3. 

Next run the following commands:

```
$ flutter clean
$ flutter run --flavor="app1Local"
```

**Expected results:** The app to run without error on your device.

**Actual results:**

I get the following error:

```
[        ] BUILD SUCCESSFUL in 22s
[        ] 30 actionable tasks: 29 executed, 1 up-to-date
[ +363 ms] Running Gradle task 'assembleApp1LocalDebug'... (completed in 23.1s)
[   +9 ms] "flutter run" took 23,950ms.
Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\yahya\Documents\sandbox\flutter_bug\build, but the tool couldn't find it.
```

The bug seems to be here:
https://github.com/flutter/flutter/blob/c1112d3f7ea8452ea0069407de588987894def09/packages/flutter_tools/lib/src/android/gradle.dart#L98

It seems that it's looking for the file: `build/app/outputs/app1Local/debug/app-app1Local-debug.apk`.

However, the file that was actually created is: `build/app/outputs/app1Local/debug/app-app1-local-debug.apk`.

A fix will be much appreciated 👍 

<details>
  <summary>Logs</summary>

```
[        ] BUILD SUCCESSFUL in 22s
[        ] 30 actionable tasks: 29 executed, 1 up-to-date
[ +363 ms] Running Gradle task 'assembleApp1LocalDebug'... (completed in 23.1s)
[   +9 ms] "flutter run" took 23,950ms.
Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\yahya\Documents\sandbox\flutter_bug\build, but the tool couldn't find it.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:827:3)
#2      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
<asynchronous suspension>
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#26     AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#28     _rootRunUnary (dart:async/zone.dart:1134:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
Analyzing flutter_bug...
No issues found! (ran in 3.6s)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\yahya\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yahya\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\yahya\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\yahya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A15000054 • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

From https://github.com/flutter/flutter/pull/53718 , flutter.gradle will copy the output APK to a known location. Use this instead of attempting to guess the APK location.

Fixes https://github.com/flutter/flutter/issues/52905 
Fixes https://github.com/flutter/flutter/issues/29509
Fixes https://github.com/flutter/flutter/issues/13977
Fixes https://github.com/flutter/flutter/issues/44796

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 1]
```diff
@@ -35,11 +35,11 @@ Directory getApkDirectory(FlutterProject project) {
     ? project.android.buildDirectory
         .childDirectory('host')
         .childDirectory('outputs')
-        .childDirectory('apk')
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/gradle.dart:38]: This doesn't work because the flutter.gradle code added doesn't get hit in the event of a flutter module. Is this something we could fix in gradle, or do I need to keep the old APK logic around too?

Presumably since the module project is generated by us we could just change something in it to output the same as regular projects?

@blasten

Comment (blasten) [reply packages/flutter_tools/lib/src/android/gradle.dart:38]: yep. The `:flutter` project assigned to the module isn't the root project, which is what the plugin manipulates. That can be fixed though.

**Comment by jonahwilliams** [comment]
I updated the code to use the old location code for the module format

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 2]
```diff
@@ -815,7 +823,39 @@ Iterable<File> findApkFiles(
       fileExtension: '.apk',
     );
   }
-  return apks;
+  return apks.map((File file) => file.path);
```
Comment (blasten) [inline packages/flutter_tools/lib/src/android/gradle.dart:826]: This function could just become:

```dart
Iterable<String> findApkFilesModule(
  FlutterProject project,
  AndroidBuildInfo androidBuildInfo,
) {
   final Iterable<String> apkFileNames = _apkFilesFor(androidBuildInfo);
   final Directory apkDirectory = getApkDirectory(project);
   return apkFileNames.map((File file) => fs.path.join(apkDirectory.path, file.path));
}
```

Comment (blasten) [reply packages/flutter_tools/lib/src/android/gradle.dart:826]: oh nvm. This is for `build apk` in a module, right?

**Review by blasten — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/gradle.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/gradle.dart:826]: Yeah

**Comment by Im-Kevin** [comment]
When can this patch be updated to Stable
