### PR TITLE
Fix DropdownMenu does not rematch initialSelection when entries have changed

### LINKED ISSUE #155660: DropdownMenu.didUpdateWidget should re-match initialSelection when dropdownMenuEntries have changed
### Use case

In my use case, the ` DropdownMenu.dropdownMenuEntries` are asynchronously fetched from the database and assigned after the Future has been resolved. The `initialSelection`, however, has already been set in the first build cycle.

The problem lays in that in `DropdownMenu.didUpdateWidget()`, where the `initialSelection` is not matched again against the updated menu entries. See https://github.com/flutter/flutter/blob/9d42f826d71b1b9beb2d8c07bcdad731ba78968d/packages/flutter/lib/src/material/dropdown_menu.dart#L552-L557

This will lead to an empty field not showing the matching `initialSelection`, but yet showing a correct list of items in the dropdown. Quite confusing...

Finding out the cause after debugging, I use the following, hopefully temporary, workaround:
```
DropdownMenu<String>(
  initialSelection: items.isEmpty ? null : _selectedItem ?? widget.item,
  ... etc
)
```

### Proposal

I would like the `initialSelection` to be matched again against the new value set for `dropdownMenuEntries` as is done when the intialSelection has changed. See https://github.com/flutter/flutter/blob/9d42f826d71b1b9beb2d8c07bcdad731ba78968d/packages/flutter/lib/src/material/dropdown_menu.dart#L561-L569

IMHO this should be provided by Flutter directly.

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR makes DropdownMenu rematching the initialSelection when the entries are updated.
If the new entries contains one entry whose value matches `initialSelection` this entry's label is used to initialize the inner text field, if no entries matches `initialSelection` the text field is emptied.

## Related Issue

Fixes [DropdownMenu.didUpdateWidget should re-match initialSelection when dropdownMenuEntries have changed](https://github.com/flutter/flutter/issues/155660).

## Tests

Adds 3 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -577,6 +572,21 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
+  // Initialize the text field with the label associated to the entry
+  // whose value matches the initial selection.
+  // Empty the text field when no entry matches the initial selection.
+  void matchInitialSelection() {
+    final int index = filteredEntries.indexWhere((DropdownMenuEntry<T> entry) => entry.value == widget.initialSelection);
+    if (index != -1) {
+      _localTextEditingController?.value = TextEditingValue(
+        text: filteredEntries[index].label,
+        selection: TextSelection.collapsed(offset: filteredEntries[index].label.length),
+      );
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/dropdown_menu.dart:584]: Tiny nit—we could reduce the number of times the list is accessed:

```suggestion
      final String label = filteredEntries[index].label;
      _localTextEditingController?.value = TextEditingValue(
        text: label,
        selection: TextSelection.collapsed(offset: label.length),
      );
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -1974,6 +1974,135 @@ void main() {
     expect(itemMaterial.color, themeData.colorScheme.onSurface.withOpacity(0.12));
   });
 
+  testWidgets(
+    'When the initial selection matches a menu entry the text field should display the corresponding value',
```
Comment (nate-thegrate) [inline packages/flutter/test/material/dropdown_menu_test.dart:1978]:
```suggestion
    'When the initial selection matches a menu entry, the text field displays the corresponding value',
```

Just a personal preference – I like going for "declarative vibes" 😎

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -1974,6 +1974,135 @@ void main() {
...
+          }
+        ),
+      ));
+
+      expect(controller.text, TestMenu.mainMenu3.label);
+    },
+  );
+
+  testWidgets(
+    'When the initial selection does not match any menu entries the text field should be empty',
```
Comment (nate-thegrate) [inline packages/flutter/test/material/dropdown_menu_test.dart:2002]:
```suggestion
    'Text field is empty when the initial selection does not match any menu entries',
```

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 4]
```diff
@@ -577,6 +572,21 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       };
   }
 
+  // Initialize the text field with the label associated to the entry
+  // whose value matches the initial selection.
+  // Empty the text field when no entry matches the initial selection.
+  void matchInitialSelection() {
+    final int index = filteredEntries.indexWhere((DropdownMenuEntry<T> entry) => entry.value == widget.initialSelection);
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/dropdown_menu.dart:579]:
```suggestion
    final int index = filteredEntries.indexWhere(
      (DropdownMenuEntry<T> entry) => entry.value == widget.initialSelection,
    );
```

File: examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart [hunk 5]
```diff
@@ -123,10 +120,7 @@ class _DropdownMenuExampleState extends State<DropdownMenuExample> {
                     dropdownValue = value!;
                   });
                 },
-                dropdownMenuEntries:
-                    list.map<DropdownMenuEntry<String>>((String value) {
-                  return DropdownMenuEntry<String>(value: value, label: value);
-                }).toList(),
+                dropdownMenuEntries: menuEntries,
```
Comment (nate-thegrate) [inline examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart:123]: Thanks very much for the cleanup throughout this build method ❤️

File: examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart [hunk 6]
```diff
@@ -39,6 +39,9 @@ class _DropdownMenuExampleState extends State<DropdownMenuExample> {
   @override
   Widget build(BuildContext context) {
     final ColorScheme colorScheme = Theme.of(context).colorScheme;
+    final List<DropdownMenuEntry<String>> menuEntries = list.map<DropdownMenuEntry<String>>((String value) {
+      return DropdownMenuEntry<String>(value: value, label: value);
+    }).toList();
```
Comment (nate-thegrate) [inline examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart:44]:
```suggestion
  static final List<MenuEntry> menuEntries = UnmodifiableListView<MenuEntry>(
    list.map<MenuEntry>((String name) => MenuEntry(value: name, label: name)),
  );

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = ColorScheme.of(context);
```

**Review by nate-thegrate — COMMENTED** [review]
Looks phenomenal—thanks for the fix and the thorough testing!

A bunch of random suggestions, most of which are due to how `List<DropdownMenuEntry<T>>` has a tendency to make lines super long :)

File: examples/api/lib/material/dropdown_menu/dropdown_menu.1.dart [hunk 7]
```diff
@@ -36,6 +36,12 @@ class DropdownMenuExample extends StatefulWidget {
 
 class _DropdownMenuExampleState extends State<DropdownMenuExample> {
   String dropdownValue = list.first;
+  final List<DropdownMenuEntry<String>> menuEntries = list.map<DropdownMenuEntry<String>>((String value) {
+    return DropdownMenuEntry<String>(
+      value: value,
+      label: value
+    );
+  }).toList();
```
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply examples/api/lib/material/dropdown_menu/dropdown_menu.1.dart:44]: (Should probably note that hitting "commit suggestion" wouldn't work due to needing to add a typedef as well, apologies for that!)

File: examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart [hunk 8]
```diff
@@ -55,6 +55,29 @@ class _DropdownMenuExampleState extends State<DropdownMenuExample> {
...
+        label: color.label,
+        enabled: color.label != 'Grey',
+        style: MenuItemButton.styleFrom(
+          foregroundColor: color.color,
+        ),
+      );
+    }
+  ).toList();
+
+  final List<DropdownMenuEntry<IconLabel>> iconEntries = IconLabel.values.map<DropdownMenuEntry<IconLabel>>(
```
[the remark this answers is not in the document]
Comment (bleroux) [reply examples/api/lib/material/dropdown_menu/dropdown_menu.0.dart]: Great suggestion! :pray:

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: Nice! Typical case where I moved the existing code without reading it very closely :grin:

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 4 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: Not fond of this formatting. It reduces the long lines but the style guide explictly mention that going above 80 is preferrable when the result is more readable.
Nonetheless I applied it:
- because readability is somewhat subjective.
- I used the same formatting on a very recent PR.
- maybe we will get autoformat in the coming months (and subjectivity will be gone :smile: ).

File: examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart (hunk 6 above)
Comment (bleroux) [reply examples/api/lib/material/dropdown_menu/dropdown_menu.2.dart]: Good catch! The intention was to move it above the build like the other examples.

**Review by nate-thegrate — APPROVED** [review]
LGTM 👍

Fantastic improvements all-around, thank you!

**Comment by bleroux** [comment]
I will probably wait for https://github.com/flutter/flutter/pull/155252 to land (I will solve the conflicts on my side).

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 4 above)
Comment (davidhicks980) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: Not a reviewer but I came across this PR. I'm also not a fan of the indented closure formatting.  How would you both feel about something like:

```dart
TextEditingValue get _initialTextEditingValue {
    for (final entry in filteredEntries) {
      if (entry.value == widget.initialSelection) {
        return TextEditingValue(
          text: entry.label,
          selection: TextSelection.collapsed(offset: entry.label.length),
        );
      }
    }
    return TextEditingValue.empty;
  }
```
where `_localTextEditingController?.value = _initialTextEditingValue` is set in didUpdateWidget. It could also be a function rather than a getter.

I think the current function being a void 'match'-er rather than a setter made the purpose ambigious without viewing the implementation (or the comments).

That said, feel free to ignore this!
