### PR TITLE
Navigator.pop before PopupMenuItem onTap call

### LINKED ISSUE #127443: Can not showModalBottomSheet from Toolbar actions if using PopupMenuButton
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a simple Materal Themed application
2. Use Scaffold and give it an AppBar with `actions` property
3. Use the code in sample section to implement `AppBar`
3. Tap on the IconButton and you can see that the bottom sheet is going to appear
4. Tap on the PopupMenuButton and then tap on `SHOW` and nothing is going to happen.

### Expected results

Expected PopupMenuItem to show the bottom sheet

### Actual results

Bottom sheet is not showing but something odd is happening.
Try to put e Future delay before openning the bottomsheet:
```dart
                    Future.delayed(Duration(seconds: 2)).then((value) {
                      showModalBottomSheet(
                        context: context,
                        useSafeArea: true,
                        isScrollControlled: true,
                        shape: const RoundedRectangleBorder(
                            borderRadius: BorderRadius.vertical(top: Radius.circular(16))),
                        builder: (context) {
                          return const Placeholder();
                        },
                      );
                    });
```
Now it works!!!

### Code sample

<details><summary>Code sample</summary>

```dart
AppBar(
        title: const Text('Title'),
        actions: [
          IconButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  useSafeArea: true,
                  isScrollControlled: true,
                  shape: const RoundedRectangleBorder(
                      borderRadius: BorderRadius.vertical(top: Radius.circular(16))),
                  builder: (context) {
                    return const Placeholder();
                  },
                );
              },
              icon: Icon(Icons.close)),
          Builder(
            builder: (context) => PopupMenuButton(
              padding: EdgeInsets.zero,
              itemBuilder: (context) => [
                PopupMenuItem(
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  onTap: () {
                      showModalBottomSheet(
                        context: context,
                        useSafeArea: true,
                        isScrollControlled: true,
                        shape: const RoundedRectangleBorder(
                            borderRadius: BorderRadius.vertical(top: Radius.circular(16))),
                        builder: (context) {
                          return const Placeholder();
                        },
                      );
                  },
                  child: Text('SHOW'),
                ),
              ],
              child: const Padding(padding: EdgeInsets.all(16), child: Icon(Icons.more_vert)),
            ),
          ),
        ],
      )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\FlutterStable\flutter  
    • Upstream repository https://github.com/flutter/flutter.git            
    • Framework revision 84a1e904f4 (2 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9                                            
    • Dart version 3.0.0                                                    
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\AndroidSdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\MonoBit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 112.0.1722.39

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by mhbdev**
*The order of calling Navigator.pop and PopupMenuItem.onTap has been changed so before calling PopupMenuItem onTap method, PopupMenuBotton onSelect method is going to be called.*

*close #127443*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/popup_menu_test.dart [hunk 1]
```diff
@@ -3260,6 +3260,45 @@ void main() {
...
+          appBar: AppBar(
+            actions: <Widget>[
+              PopupMenuButton<int>(
+                onSelected: (int value) {
+                  orderList.add(value);
+                },
+                itemBuilder: (BuildContext context) => <PopupMenuItem<int>>[
+                  PopupMenuItem<int>(
+                    onTap: () {
+                      orderList.add(1);
```
Comment (chunhtai) [inline packages/flutter/test/material/popup_menu_test.dart:3279]: Why not make this test to show a modalbottomsheet and make sure it is correctly showed. That will be a more accurate test for the issue this pr is trying to solve.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 2]
```diff
@@ -339,9 +339,9 @@ class PopupMenuItemState<T, W extends PopupMenuItem<T>> extends State<W> {
   /// the menu route.
   @protected
   void handleTap() {
-    widget.onTap?.call();
-
     Navigator.pop<T>(context, widget.value);
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/popup_menu.dart:342]: Can you add a comment says
// Need to pop the navigator first in case onTap may push new route
// onto navigator.

Comment (mhbdev) [reply packages/flutter/lib/src/material/popup_menu.dart:342]: Yes ofc. I will do that tomorrow.

File: packages/flutter/test/material/popup_menu_test.dart (hunk 1 above)
Comment (mhbdev) [reply packages/flutter/test/material/popup_menu_test.dart:3279]: You right. I will change that.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
cc @QuncCccccc as secondary reviewer

**Review by QuncCccccc — APPROVED** [review]
LGTM. Nice improvement:) Thanks!

**Comment by QuncCccccc** [comment]
The Google testing is failed but seems it is not related to this PR change. @mhbdev Could you maybe rebase master to trigger the test again?

**Comment by mhbdev** [comment]
> The Google testing failed but seems it is not related to this PR change. @mhbdev Could you maybe rebase master to trigger the test again?

Hello there! I tried to rebase master but still the same issue happening. I have no clue why this is getting stuck. All checks have been passed before but now ...

**Comment by QuncCccccc** [comment]
> > The Google testing failed but seems it is not related to this PR change. @mhbdev Could you maybe rebase master to trigger the test again?
> 
> Hello there! I tried to rebase master but still the same issue happening. I have no clue why this is getting stuck. All checks have been passed before but now ...

The luci-flutter test is just showing the tree status and will be fixed later. Just checked the Google testing, looks like all tests have passed, so it might just need some time to change the pending status:) 

Thanks a lot for the help. The autosubmit label should be able to merge this change once the tree is green.

**Comment by mhbdev** [comment]
> > > The Google testing failed but seems it is not related to this PR change. @mhbdev Could you maybe rebase master to trigger the test again?
> > 
> > 
> > Hello there! I tried to rebase master but still the same issue happening. I have no clue why this is getting stuck. All checks have been passed before but now ...
> 
> The luci-flutter test is just showing the tree status and will be fixed later. Just checked the Google testing, looks like all tests have passed, so it might just need some time to change the pending status:)
> 
> Thanks a lot for the help. The autosubmit label should be able to merge this change once the tree is green.

Thank you for the explanation ☺️
