### PR TITLE
fix(scrollbar): Update padding type to EdgeInsetsGeometry

### LINKED ISSUE #167922: [Proposal]Change RawScrollbar's padding attribute to be EdgeInsetsGeometry instead of EdgeInsets
### Use case

Trying to have a directional edge geometry in RawScrollbar fails since it only accepts EdgeInsets and not EdgeInsetsGeometry meaning that EdgeInsetsDirectional isn't accepted.

### Proposal

Change it to EdgeInsetsGeometry? instead of EdgeInsets?

### PR DESCRIPTION
**Pull request by SalehTZ**
This PR enhances RTL support for the RawScrollbar widget by updating its padding type and adding comprehensive tests.

The changes include:
1. Updating RawScrollbar's `padding` parameter from `EdgeInsets` to `EdgeInsetsGeometry`
   - This change is non-breaking because `EdgeInsets` is a subclass of `EdgeInsetsGeometry`
   - Existing code using `EdgeInsets` will continue to work as before
   - Users can now optionally use `EdgeInsetsDirectional` for RTL support
2. Adding a test case that verifies scrollbar positioning with EdgeInsetsDirectional padding
3. Testing both overscroll and regular scroll scenarios with directional padding

These changes ensure that the scrollbar works correctly in both LTR and RTL layouts, improving accessibility and internationalization support.

Fixes: #167922

## Pre-launch Checklist

- [x] I read the [Contributor Guide](https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview) and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene](https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md) wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md), including [Features we expect every widget to implement](https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement).
- [x] I signed the [CLA](https://cla.developers.google.com/).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md).

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by victorsanni — APPROVED** [review]
LGTM! Thanks for this PR.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 1]
```diff
@@ -634,6 +631,12 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
     if (_lastAxisDirection == null || !_needPaint(_lastMetrics)) {
       return;
     }
+    assert(
+      textDirection != null,
+      'A TextDirection must be provided before a Scrollbar can be painted.',
+    );
+    _resolvedPadding = padding.resolve(textDirection);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: With this assert, it looks like `textDirection` is now effectively required?

Would it be possible to only resolve this if necessary, like if it's an EdgeInsetsGeometry and textDirection is non-null?

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 2]
```diff
@@ -95,7 +95,7 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
     Color trackBorderColor = const Color(0x00000000),
     TextDirection? textDirection,
     double thickness = _kScrollbarThickness,
-    EdgeInsets padding = EdgeInsets.zero,
+    EdgeInsetsGeometry padding = EdgeInsets.zero,
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scrollbar.dart:101]: Should it be disallowed to pass and EdgeInsetsGeometry (not EdgeInsets) and a null TextDirection? Maybe add an assertion and mention it in the docs if so.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 3]
```diff
@@ -290,9 +290,9 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
   ///
   /// Defaults to [EdgeInsets.zero]. Offsets from all four directions must be
   /// greater than or equal to zero.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scrollbar.dart:301]: Do you think it would be helpful to document that you can pass EdgeInsetsDirectional in order to support both LTR/RTL, or is that obvious?

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 4]
```diff
@@ -388,17 +388,19 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
   // - Scrollbar Details
 
   Rect? _trackRect;
+  late EdgeInsets _resolvedPadding;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: It seems dangerous that this could be accessed before the first `paint`. Would it be possible to resolve this before `paint`? Maybe even in the getter for `padding` or something?

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 5]
```diff
@@ -3567,4 +3567,68 @@ The provided ScrollController cannot be shared by multiple ScrollView widgets.''
     },
     variant: TargetPlatformVariant.desktop(),
   );
+
+  testWidgets('with EdgeInsetsDirectional', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/widgets/scrollbar_test.dart]: I think this could be a `test` instead of `testWidgets`.

**Review by justinmc — COMMENTED** [review]
Thank you again for helping Flutter have better RTL support!

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 1 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: It was previously on the line [556](https://github.com/flutter/flutter/pull/172056/files#diff-7ea53e627d4729db3a54ab440e8f6d2610cbfc44ac4f9718daef49b2b4645f2dL556).

Yeah that's a better idea.

What about setting default a value `TextDirection.ltr` to `textDirection` if no text direction was provided? Because right now `textDirection` is required anyways. see https://github.com/flutter/flutter/pull/172056/files#diff-7ea53e627d4729db3a54ab440e8f6d2610cbfc44ac4f9718daef49b2b4645f2dL556

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 3 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart:301]: While I think it's fairly obvious, it could still be helpful. I'll add it.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 2 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart:101]: I agree. Passing an `EdgeInsetsGeometry` without a `TextDirection` can definitely cause problems. An assertion makes sense, and adding a note in the docs would help avoid confusion.

Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart:101]: Also, that wouldn’t be a breaking change, since it currently uses `EdgeInsets`, which doesn’t require `textDirection`.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 4 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Yes that's possible. Also maybe in the setter of `padding` like:
```dart
EdgeInsetsGeometry get padding {
  _resolvedPadding = _padding.resolve(_textDirection);
  return _padding;
}
EdgeInsetsGeometry _padding;
set padding(EdgeInsetsGeometry value) {
  if (padding == value) {
    return;
  }

  _padding = value;
  _resolvedPadding = _padding.resolve(_textDirection);
  notifyListeners();
}
```

Even for `textDirection` like ( I'm not quite sure if this good):
```dart
TextDirection? get textDirection {
  _resolvedPadding = _padding.resolve(_textDirection);
  return _textDirection;
}

TextDirection? _textDirection;
set textDirection(TextDirection? value) {
  assert(value != null);
  if (textDirection == value) {
    return;
  }

  _textDirection = value;
  _resolvedPadding = _padding.resolve(_textDirection);
  notifyListeners();
}
```

Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Found another solution. 🎉

File: packages/flutter/test/widgets/scrollbar_test.dart (hunk 5 above)
Comment (SalehTZ) [reply packages/flutter/test/widgets/scrollbar_test.dart]: done.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 6]
```diff
@@ -190,6 +198,7 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
     }
 
     _textDirection = value;
+    _resolvedPadding = _padding.resolve(_textDirection);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scrollbar.dart:201]: It's possible that _textDirection is null and ~~`value`~~ `padding` is EdgeInsetsDirectional. Do we need another assert here similar to the one in the constructor?

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: What do you think about the developer experience for RTL users in the case where there is a default? If they pass an EdgeInsetsDirectional, do they want to be warned if there is no TextDirection or would they be ok with an LTR default?

I see this wouldn't be the only place where we default to LTR: https://github.com/flutter/flutter/blob/053c8a55f1e933ecd57e6cadcddf3bdd8b6c6b2c/packages/flutter/lib/src/services/text_input.dart#L1445

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: . I like your _resolvedPadding approach, thanks for fixing that.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 6 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart:201]: Hmm, I don't think `_textDirection` and `textDirection` could be null, and also the `value` here is a `TextDirection?`.

> Do we need another assert here similar to the one in the constructor?

We can make sure of this:
```dart
  set textDirection(TextDirection? value) {
    assert(value != null, 'A non-null textDirection must be provided.');
    assert(
      padding is! EdgeInsetsDirectional || value != null,
      'A non-null textDirection must be provided when using EdgeInsetsDirectional for padding.',
    );

    if (textDirection == value) {
      return;
    }

    _textDirection = value;
    _resolvedPadding = _padding.resolve(_textDirection);
    notifyListeners();
  }
```
----
But generally this `textDirection` is based on the Locale and/or Directionality of the App/Context. So it wouldn't be `null` and  `if the 'locale' is null then the system's locale value is used.` by default.
See: 
https://github.com/flutter/flutter/blob/dcae0c4ca0c3ee3317ed3198a2141184e949fb03/packages/flutter/lib/src/widgets/app.dart#L877-L884

See below for both Material and Cupertino:
https://github.com/flutter/flutter/blob/dcae0c4ca0c3ee3317ed3198a2141184e949fb03/packages/flutter/lib/src/material/scrollbar.dart#L351
https://github.com/flutter/flutter/blob/dcae0c4ca0c3ee3317ed3198a2141184e949fb03/packages/flutter/lib/src/cupertino/scrollbar.dart#L163

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 1 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: I think current approach is good for RTL users as well, they can change position of almost anything just by defining the `locale` parameter in `MaterialApp` or `CuppertinoApp`. I explained a bit about it [here](https://github.com/flutter/flutter/pull/172056#discussion_r2238870306).

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/scrollbar.dart:201]: Sorry I meant `padding` not `value`. And that makes sense, thanks for the explanation.

**Comment by justinmc** [comment]
@SalehTZ The test is an isolates test failure that must be a flake, I've seen it on another PR this morning. If it doesn't go green, can you try rebasing?
