### PR TITLE
🚀 Implements `globalPosition` and `localPosition` for `TapDragEndDetails`

### LINKED ISSUE #159961: `TapDragEndDetails` should contain positions
### Steps to reproduce

N/A

### Expected results

`TapUpDetails` and `DragEndDetails` all contain positions, so it is reasonable that this detail contains valid position info.

```dart
class TapDragEndDetails with Diagnosticable {
  /// Creates details for a [GestureTapDragEndCallback].
  TapDragEndDetails({
    this.velocity = Velocity.zero,
    this.primaryVelocity,
    required this.consecutiveTapCount,
    this.globalPosition = Offset.zero,
    Offset? localPosition,
  }) : assert(
         primaryVelocity == null
           || primaryVelocity == velocity.pixelsPerSecond.dx
           || primaryVelocity == velocity.pixelsPerSecond.dy,
       ),
       localPosition = localPosition ?? globalPosition;

  /// The velocity the pointer was moving when it stopped contacting the screen.
  ///
  /// Defaults to zero if not specified in the constructor.
  final Velocity velocity;

  /// The velocity the pointer was moving along the primary axis when it stopped
  /// contacting the screen, in logical pixels per second.
  ///
  /// If the [GestureTapDragEndCallback] is for a one-dimensional drag (e.g., a
  /// horizontal or vertical drag), then this value contains the component of
  /// [velocity] along the primary axis (e.g., horizontal or vertical,
  /// respectively). Otherwise, if the [GestureTapDragEndCallback] is for a
  /// two-dimensional drag (e.g., a pan), then this value is null.
  ///
  /// Defaults to null if not specified in the constructor.
  final double? primaryVelocity;

  /// If this tap is in a series of taps, then this value represents
  /// the number in the series this tap is.
  final int consecutiveTapCount;

  /// The pointer's global position when it triggered this update.
  ///
  /// See also:
  ///
  ///  * [localPosition], which is the [globalPosition] transformed to the
  ///    coordinate space of the event receiver.
  final Offset globalPosition;

  /// The local position in the coordinate system of the event receiver at
  /// which the pointer contacted the screen.
  ///
  /// Defaults to [globalPosition] if not specified in the constructor.
  final Offset localPosition;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty<Velocity>('velocity', velocity));
    properties.add(DiagnosticsProperty<double?>('primaryVelocity', primaryVelocity));
    properties.add(DiagnosticsProperty<int>('consecutiveTapCount', consecutiveTapCount));
    properties.add(DiagnosticsProperty<Offset>('globalPosition', globalPosition));
    properties.add(DiagnosticsProperty<Offset>('localPosition', localPosition));
  }
}
```

### Actual results

No positions were included in the detail.

```dart
class TapDragEndDetails with Diagnosticable {
  /// Creates details for a [GestureTapDragEndCallback].
  TapDragEndDetails({
    this.velocity = Velocity.zero,
    this.primaryVelocity,
    required this.consecutiveTapCount,
  }) : assert(
         primaryVelocity == null
           || primaryVelocity == velocity.pixelsPerSecond.dx
           || primaryVelocity == velocity.pixelsPerSecond.dy,
       );

  /// The velocity the pointer was moving when it stopped contacting the screen.
  ///
  /// Defaults to zero if not specified in the constructor.
  final Velocity velocity;

  /// The velocity the pointer was moving along the primary axis when it stopped
  /// contacting the screen, in logical pixels per second.
  ///
  /// If the [GestureTapDragEndCallback] is for a one-dimensional drag (e.g., a
  /// horizontal or vertical drag), then this value contains the component of
  /// [velocity] along the primary axis (e.g., horizontal or vertical,
  /// respectively). Otherwise, if the [GestureTapDragEndCallback] is for a
  /// two-dimensional drag (e.g., a pan), then this value is null.
  ///
  /// Defaults to null if not specified in the constructor.
  final double? primaryVelocity;

  /// If this tap is in a series of taps, then this value represents
  /// the number in the series this tap is.
  final int consecutiveTapCount;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty<Velocity>('velocity', velocity));
    properties.add(DiagnosticsProperty<double?>('primaryVelocity', primaryVelocity));
    properties.add(DiagnosticsProperty<int>('consecutiveTapCount', consecutiveTapCount));
  }
}
```

### Code sample

N/A

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel [user-branch], 3.27.0-1.0.pre.745, on Microsoft Windows [Version 10.0.22631.4460], locale en-US)
```

</details>

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves #159961

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 1]
```diff
@@ -1287,6 +1310,7 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
       invokeCallback<void>('onDragEnd', () => onDragEnd!(endDetails));
     }
 
+    _correctedPosition = null;
```
Comment (AlexV525) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1313]: This ensures that the corrected (dragged delta) only gets cleared after the end event has been dispatched.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 2]
```diff
@@ -1138,36 +1160,51 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
-      _correctedPosition = null;
+      final OffsetPair delta = _calculateDragUpdateDelta(event);
+      _updateCurrentPosition(delta);
+      _checkDragUpdate(event, corrected: _initialPosition + delta);
     }
   }
 
   void _checkDrag(PointerMoveEvent event) {
-    final Matrix4? localToGlobalTransform = event.transform == null ? null : Matrix4.tryInvert(event.transform!);
+    final Matrix4? localToGlobalTransform = event.transform != null ? Matrix4.tryInvert(event.transform!) : null;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1202]: nit: prefer the shorter result on the left if possible.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 3]
```diff
@@ -1138,36 +1160,51 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
     final Offset movedLocally = _getDeltaForDetails(event.localDelta);
     _globalDistanceMoved += PointerEvent.transformDeltaViaPositions(
       transform: localToGlobalTransform,
       untransformedDelta: movedLocally,
-      untransformedEndPosition: event.localPosition
+      untransformedEndPosition: event.localPosition,
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1207]: good catch!

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 2 above)
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1202]: Sorry you mean `? null : Matrix4` is preferred?

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 4]
```diff
@@ -1087,6 +1107,8 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
       _pastSlopTolerance = _pastSlopTolerance || _getGlobalDistance(event, _initialPosition) > computedSlop;
 
       if (_dragState == _DragState.accepted) {
+        final OffsetPair delta = _calculateDragUpdateDelta(event);
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: Is it necessary to calculate the drag update delta here? Can we use `event.position`, and `event.localPosition` directly instead?

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1202]: Yeah I think the original way this was written is preferred.

Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart]: Sure. Updated

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 4 above)
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: Not sure if the positions are valid for the details, but I'll double-check if your suggestion works.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: This looks like what `LongPressEndDetails` and `DragEndDetails` do for the most part.

Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: Further question about the transform: What is the initial idea about the transform calculation to the event?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: Are you referring to the logic in `_acceptDrag`?

Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: Yep, it used to be the only one that corrects the positions.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1110]: I think that one can remain. It's mainly to handle `DragStartBehavior` iirc.

Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart]: Done update

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 5]
```diff
@@ -1138,26 +1159,39 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
-      final Offset globalUpdateDelta = PointerEvent.transformDeltaViaPositions(
-        untransformedEndPosition: correctedLocalPosition,
-        untransformedDelta: event.localDelta,
-        transform: localToGlobal,
-      );
-      final OffsetPair updateDelta = OffsetPair(local: event.localDelta, global: globalUpdateDelta);
-      _correctedPosition = _initialPosition + updateDelta; // Only adds delta for down behaviour
-      _checkDragUpdate(event);
-      _correctedPosition = null;
+      if (_dragState == _DragState.accepted) {
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1190]: I think this case was originally only meant for cases when `DragStartBehavior.down` is set, see: https://github.com/flutter/flutter/blob/dd437c7a604ba2180ff6fba40f52613593af4f04/packages/flutter/lib/src/gestures/monodrag.dart#L775-L795 . When the behavior is set to `DragStartBehavior.down` we send a `start` event with the initial position from the down event and a `update` event with the delta since the down event vs when the behavior is set to `DragStartBehavior.start` we only send the `start` event with the initial position offset by the delta since the down event and no `update` event.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 6]
```diff
@@ -400,12 +403,28 @@ class TapDragEndDetails with Diagnosticable {
   /// the number in the series this tap is.
   final int consecutiveTapCount;
 
+  /// The pointer's global position when it triggered this update.
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:406]: nit: maybe this should say `The global position at which the pointer lifted from the screen.` similar to `LongPressEndDetails`.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 7]
```diff
@@ -400,12 +403,28 @@ class TapDragEndDetails with Diagnosticable {
...
+  ///
+  /// See also:
+  ///
+  ///  * [localPosition], which is the [globalPosition] transformed to the
+  ///    coordinate space of the event receiver.
+  final Offset globalPosition;
+
+  /// The local position in the coordinate system of the event receiver at
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:414]: nit: maybe this should say `The local position in the coordinate system of the event receiver at which the pointer lifted from the screen.`

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 6 above)
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:406]: Oh these are just copy-paste. Should I update them or keep them as previous?

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 8]
```diff
@@ -1138,26 +1159,39 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
   @override
   String get debugDescription => 'tap_and_drag';
 
+  /// Calculates the update delta from the given pointer event.
+  OffsetPair _calculateDragUpdateDelta(PointerEvent event) {
```
[the remark this answers is not in the document]
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1163]: Thanks for the catch. It used to have multiple callers and now remains one only.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart]: Added the assertion.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 9]
```diff
@@ -1139,25 +1160,35 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
       );
-      final OffsetPair updateDelta = OffsetPair(local: event.localDelta, global: globalUpdateDelta);
-      _correctedPosition = _initialPosition + updateDelta; // Only adds delta for down behaviour
-      _checkDragUpdate(event);
-      _correctedPosition = null;
+      final OffsetPair updateDelta = OffsetPair(
+        local: localDelta,
+        global: globalUpdateDelta,
+      );
+      _checkDragUpdate(event, corrected: _initialPosition + updateDelta);
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1191]: nit: I think we should add the comment back regarding only adding the delta for down behavior.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 10]
```diff
@@ -1139,25 +1160,35 @@ sealed class BaseTapAndDragGestureRecognizer extends OneSequenceGestureRecognize
...
+        global: event.delta,
+        local: event.localDelta,
+      );
+      _currentPosition = _initialPosition;
     }
     _checkDragStart(event);
-    if (event.localDelta != Offset.zero) {
-      final Matrix4? localToGlobal = event.transform != null ? Matrix4.tryInvert(event.transform!) : null;
-      final Offset correctedLocalPosition = _initialPosition.local + event.localDelta;
+    final Offset localDelta = event.localDelta;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:1177]: This should be `= _getDeltaForDetails(event.localDelta);`.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 6 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:406]: I'm leaning towards the updated version being more descriptive.

**Review by Renzo-Olivares — COMMENTED** [review]
Mostly LGTM, with some last small nits.

**Review by Renzo-Olivares — COMMENTED** [review]
Mostly LGTM, with some last small nits.

**Review by Renzo-Olivares — COMMENTED** [review]
Mostly LGTM, with some last small nits.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart (hunk 10 above)
Comment (AlexV525) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart]: It doesn't seem so. There is another calculation right below which will transform the delta. Updating this will lead to unexpected behavior such as the moving delta being shorter than expected. https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20framework_tests_impeller/16753/overview

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/gestures/tap_and_drag.dart:1178]: Thanks for catching that, let's leave it as is for now then.

File: packages/flutter/lib/src/gestures/tap_and_drag.dart [hunk 11]
```diff
@@ -400,12 +403,29 @@ class TapDragEndDetails with Diagnosticable {
   /// the number in the series this tap is.
   final int consecutiveTapCount;
 
+  /// The global position at which the pointer lifted from the screen.
+  /// Similar to [LongPressEndDetails].
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/gestures/tap_and_drag.dart:407]: You can remove the line mentioning `LongPressEndDetails`, sorry if that was unclear.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM modulo nits, thank you for your contribution!
