### PR TITLE
Respond to TextInputClient.reattach messages.

### LINKED ISSUE #35054: [Add2App] It's possible to lose the ability to input characters using the keyboard on Android
Using the new embedding API for Android to embed Flutter in an existing app, it is possible for the app to stop taking input from the keyboard.

The following simple Flutter module code will create a TextField.

1. Launch the Flutter module in the existing app
2. Start typing text in the field
3. With focus still in the field, background the app using the Home button
4. Come back to the app. Notice the focus is still in the field, but the keyboard is hidden (expected)
5. Select the field again and start typing. Notice text is not entered in the field.

The following is the code in the flutter module:

```
// Main app entry
void main() {
   runApp(MyApp());
}

class DefaultEmptyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: TextField(
              decoration: InputDecoration(
                  labelText: "Enter Text"
              ),
            )
        )
    );
  }
}

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      home: DefaultEmptyPage(),
    );
  }
}
```

The following exception occurs after coming back to the app and tapping in the text field:

```
2019-06-25 09:17:51.732 7330-7330/com.example.app E/MethodChannel#flutter/textinput: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:208)
        at io.flutter.plugin.editing.TextInputPlugin.access$400(TextInputPlugin.java:26)
        at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:66)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:76)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2019-06-25 09:17:51.775 7330-7471/com.example.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
    <asynchronous suspension>
    #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:424:36)
    <asynchronous suspension>
    #3      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:649:30)
    #4      EditableTextState._updateRemoteEditingValueIfNeeded (package:flutter/src/widgets/editable_text.dart:1093:26)
    #5      EditableTextState._didChangeTextEditingValue (package:flutter/src/widgets/editable_text.dart:1400:5)
    #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
    #7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
    #8      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:166:5)
    #9      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1211:23)
    #10     RenderEditable._handlePotentialSelectionChange (package:flutter/src/rendering/editable.dart:369:5)
    #11     RenderEditable.selectPositionAt (package:flutter/src/rendering/editable.dart:1416:9)
    #12     RenderEditable.selectPosition (package:flutter/src/rendering/editable.dart:1388:5)
    #13     _TextFieldState._handleSingleTapUp (package:flutter/src/material/text_field.dart:760:27)
    #14     _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:929:16)
    #15     TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:383:49)
    #16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
    #17     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:383:11)
    #18     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:332:7)
    #19     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #25     _rootRunUnary (dart:async/zone.dart:1136:13)
    #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #28     _invoke1 (dart:ui/hooks.dart:239:10)
    #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
2019-06-25 09:17:51.935 7330-7330/com.example.app D/FlutterView: sendViewportMetricsToFlutter()
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Companion to https://github.com/flutter/engine/pull/13474

When the new Android embedding detaches from the engine (e.g. because it goes to the background), it loses state related to text input client(s).

It's being updated to send this message to the framework so that the framework can reattach the text input client, and the keyboard can continue to work.

## Related Issues

This and the related engine PR will combine to resolve https://github.com/flutter/flutter/issues/35054

## Tests

I need to figure out how to test this. Testing will require some refactoring, I'm thinking at the very lease making `_TextInputClientHandler` `@visibleForTesting`, or figure out a way to have the test binding simulate a message coming from the engine for this.  For now I just want it up so reviewers of the engine side can see.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
This test is .. very ugly.  But it's a test.

File: packages/flutter/lib/src/services/text_input.dart [hunk 1]
```diff
@@ -849,12 +873,15 @@ class _TextInputClientHandler {
...
-        SystemChannels.textInput.invokeMethod<void>('TextInput.hide');
+        _channel.invokeMethod<void>('TextInput.hide');
     });
   }
 }
 
-final _TextInputClientHandler _clientHandler = _TextInputClientHandler();
+final TextInputClientHandler _clientHandler = TextInputClientHandler(
+  SystemChannels.textInput,
+  null,
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: Make this an optional parameter?

File: packages/flutter/lib/src/services/text_input.dart [hunk 2]
```diff
@@ -896,17 +923,24 @@ class TextInput {
   /// A client that no longer wishes to interact with the text input control
   /// should call [TextInputConnection.close] on the returned
   /// [TextInputConnection].
-  static TextInputConnection attach(TextInputClient client, TextInputConfiguration configuration) {
+  static TextInputConnection attach(TextInputClient client) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: This is a breaking change, no?

File: packages/flutter/lib/src/services/text_input.dart [hunk 3]
```diff
@@ -896,17 +923,24 @@ class TextInput {
...
-    assert(configuration != null);
-    assert(_debugEnsureInputActionWorksOnPlatform(configuration.inputAction));
     final TextInputConnection connection = TextInputConnection._(client);
     _clientHandler._currentConnection = connection;
-    SystemChannels.textInput.invokeMethod<void>(
+    _attach(_clientHandler, connection);
+    return connection;
+  }
+
+  static void _attach(TextInputClientHandler handler, TextInputConnection connection) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: There should probably be some documentation on what the difference between attach and _attach is.

File: packages/flutter/lib/src/services/text_input.dart [hunk 4]
```diff
@@ -650,6 +651,12 @@ abstract class TextInputClient {
 
   /// Updates the floating cursor position and state.
   void updateFloatingCursor(RawFloatingCursorPoint point);
+
+  /// Creates a [TextInputConfiguration] for this client.
+  ///
+  /// This configuration is requested when establishing or re-establishing the
+  /// connection between the [TextInput] and the engine.
+  TextInputConfiguration createConfiguration();
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: This also looks like a breaking change? Implementors/Subclasses of this class will have to implement a new method?

File: packages/flutter/lib/src/services/text_input.dart [hunk 5]
```diff
@@ -896,17 +923,24 @@ class TextInput {
...
     _clientHandler._currentConnection = connection;
-    SystemChannels.textInput.invokeMethod<void>(
+    _attach(_clientHandler, connection);
+    return connection;
+  }
+
+  static void _attach(TextInputClientHandler handler, TextInputConnection connection) {
+    assert(connection != null);
+    assert(connection._client != null);
+    final TextInputConfiguration configuration = connection._client.createConfiguration();
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: To make this less breaking: I wonder if we somehow could hold on to the configuration and just re-use it on re-attach?

File: packages/flutter/lib/src/services/text_input.dart [hunk 6]
```diff
@@ -805,17 +812,34 @@ RawFloatingCursorPoint _toTextPoint(FloatingCursorDragState state, Map<String, d
...
-    SystemChannels.textInput.setMethodCallHandler(_handleTextInputInvocation);
+/// A handler for the [SystemChannels.textInput] channel.
+///
+/// This class is used internally by the Flutter SDK and is only visible for
+/// testing.
+@visibleForTesting
+class TextInputClientHandler {
+  /// Creates a [TextInputClientHandler].
+  @visibleForTesting
+  TextInputClientHandler(this._channel, this._currentConnection) : assert(_channel != null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: The arguments are only there for testing, right? I wonder if we should default them to what we need them in production.

Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: I'm refactoring the test.

File: packages/flutter/lib/src/services/text_input.dart [hunk 7]
```diff
@@ -805,17 +812,34 @@ RawFloatingCursorPoint _toTextPoint(FloatingCursorDragState state, Map<String, d
...
+
   TextInputConnection _currentConnection;
 
   Future<dynamic> _handleTextInputInvocation(MethodCall methodCall) async {
     if (_currentConnection == null)
       return;
     final String method = methodCall.method;
+
+    // Reattach request needs to be handled regardless of the client ID.
+    if (method == 'TextInputClient.reattach') {
```
Comment (matthew-carroll) [inline packages/flutter/lib/src/services/text_input.dart]: Same question here as the engine side PR. Can we call this something like `requestExistingInputState` or `requestInputConfiguration` so that we can avoid implying a previous attachment and express the goal of the message?

**Review by goderbauer — COMMENTED** [review]
Some other notes:
* Do Android and Framework agree on the state of the text field after re-attach, i.e. with regards to the text that's present in the text field?
* Can you also double check that this doesn't break textfields that switch the keyboard (as we have seen with the previous attempt)?
* We need separate API for this and https://github.com/flutter/flutter/pull/43466? Or can we consolidate? (Maybe at least only do one breaking change announcement for both)

File: packages/flutter/lib/src/services/text_input.dart (hunk 7 above)
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: Can you also add the new message to the documentation in system_channels.dart

**Review by matthew-carroll — APPROVED** [review]
I'll defer to @goderbauer for the LGTM on this because I'm less familiar with the Dart side of input connections. But nothing jumps out at me.

File: packages/flutter/lib/src/services/text_input.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: I'm going to have to do that for the last editing value anyway.  I'm not opposed to it, just means we're passing more state around.  I think this API is cleaner even if breaking.  WDYT?

File: packages/flutter/lib/src/services/text_input.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Done

File: packages/flutter/lib/src/services/text_input.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Done

Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Done

File: packages/flutter/lib/src/services/system_channels.dart [hunk 8]
```diff
@@ -159,6 +159,11 @@ class SystemChannels {
   ///    second argument is a [String] consisting of the stringification of one
   ///    of the values of the [TextInputAction] enum.
   ///
+  ///  * `TextInputClient.requestExistingInputState`: The embedding may have
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/system_channels.dart]: Let's document what should happen if there's nothing to send.

File: packages/flutter/lib/src/services/text_input.dart [hunk 9]
```diff
@@ -930,4 +909,77 @@ class TextInput {
...
+  Future<dynamic> _handleTextInputInvocation(MethodCall methodCall) async {
+    if (_currentConnection == null)
+      return;
+    final String method = methodCall.method;
+
+    // Reattach request needs to be handled regardless of the client ID.
+    if (method == 'TextInputClient.requestExistingInputState') {
+      assert(_currentConnection._client != null);
+      _attach(_currentConnection);
+      if (_lastTextEditingValue != null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: Does it seem odd that we cache the lastTextEditingValue, but don't cache the configuration?

File: dev/integration_tests/codegen/android/.project [hunk 10]
```diff
@@ -1,17 +0,0 @@
-<?xml version="1.0" encoding="UTF-8"?>
```
Comment (goderbauer) [inline dev/integration_tests/codegen/android/.project]: Maybe revert this and clean it up in a separate PR, potentially by adding something to gitignore?

File: packages/flutter/lib/src/services/system_channels.dart (hunk 8 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/system_channels.dart]: Done

File: packages/flutter/lib/src/services/text_input.dart (hunk 9 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Just caching them all now. I think this is probably cleaner and it's no longer breaking.

File: dev/integration_tests/codegen/android/.project (hunk 10 above)
Comment (dnfield) [reply dev/integration_tests/codegen/android/.project]: Going to file a separate PR, this was unintentional.  Cleaned it up for now here.

File: packages/flutter/lib/src/services/text_input.dart [hunk 11]
```diff
@@ -930,4 +915,96 @@ class TextInput {
...
+
+  Future<dynamic> _handleTextInputInvocation(MethodCall methodCall) async {
+    if (_currentConnection == null)
+      return;
+    final String method = methodCall.method;
+
+    // Reattach request needs to be handled regardless of the client ID.
+    if (method == 'TextInputClient.requestExistingInputState') {
+      assert(_currentConnection._client != null);
+      _attach(_currentConnection, _currentConfiguration);
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: I was wondering here if _currentConfiguration could ever be null at this point. Maybe add an assert(_currentConfiguration != null) above this one, possibly with a comment saying that we always have a configuration if we have a connection?

File: packages/flutter/lib/src/services/text_input.dart [hunk 12]
```diff
@@ -930,4 +915,96 @@ class TextInput {
...
+  TextInputConnection _currentConnection;
+  TextInputConfiguration _currentConfiguration;
+  TextEditingValue _currentTextEditingValue;
+
+  Future<dynamic> _handleTextInputInvocation(MethodCall methodCall) async {
+    if (_currentConnection == null)
+      return;
+    final String method = methodCall.method;
+
+    // Reattach request needs to be handled regardless of the client ID.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_input.dart]: Update this comment? Since the method is no longer called "reattach"?

File: packages/flutter/test/services/text_input_test.dart [hunk 13]
```diff
@@ -2,13 +2,66 @@
...
 void main() {
   TestWidgetsFlutterBinding.ensureInitialized();
 
+  group('TextInput message channels', () {
+    FakeTextChannel fakeTextChannel;
+    FakeTextInputClient client;
+
+    setUp(() {
+      fakeTextChannel = FakeTextChannel((MethodCall call) async {
+        return;
```
Comment (goderbauer) [inline packages/flutter/test/services/text_input_test.dart]: nit: do you actually need the return? Just an empty body is not enough?

File: packages/flutter/test/services/text_input_test.dart [hunk 14]
```diff
@@ -2,13 +2,66 @@
...
+    });
+
+    tearDown(() {
+      TextInputConnection.debugResetId();
+      TextInput.setChannel(SystemChannels.textInput);
+    });
+
+    test('text input client handler responds to reattach with setClient', () async {
+      TextInput.attach(client, client.configuration);
+
```
Comment (goderbauer) [inline packages/flutter/test/services/text_input_test.dart]: Maybe expect here that there has been one method call to ensure that requestExistingInputState only calls setClient once and not twice.

File: packages/flutter/test/services/text_input_test.dart [hunk 15]
```diff
@@ -2,13 +2,66 @@
...
+        // From requestExistingInputState
+        MethodCall('TextInput.setClient', <dynamic>[1, client.configuration.toJson()]),
+      ]);
+    });
+
+    test('text input client handler responds to reattach with setClient and text state', () async {
+      final TextInputConnection connection = TextInput.attach(client, client.configuration);
+      const TextEditingValue editingState = TextEditingValue(text: 'foo');
+      connection.setEditingState(editingState);
+
```
Comment (goderbauer) [inline packages/flutter/test/services/text_input_test.dart]: Same here.

File: packages/flutter/test/services/text_input_test.dart [hunk 16]
```diff
@@ -90,3 +143,79 @@ void main() {
...
+  const FakeTextInputClient();
+
+  TextInputConfiguration get configuration => const TextInputConfiguration();
+
+  @override
+  void performAction(TextInputAction action) => throw UnimplementedError();
+
+  @override
+  void updateEditingValue(TextEditingValue value) => throw UnimplementedError();
+  @override
```
Comment (goderbauer) [inline packages/flutter/test/services/text_input_test.dart]: uber-nit: add an empty line above this one for constancy?

File: packages/flutter/test/services/text_input_test.dart [hunk 17]
```diff
@@ -90,3 +143,79 @@ void main() {
...
+    expect(outgoingCalls.length, calls.length);
+    bool hasError = false;
+    for (int i = 0; i < calls.length; i++) {
+      final ByteData outgoingData = codec.encodeMethodCall(outgoingCalls[i]);
+      final ByteData expectedData = codec.encodeMethodCall(calls[i]);
+      final String outgoingString = utf8.decode(outgoingData.buffer.asUint8List());
+      final String expectedString = utf8.decode(expectedData.buffer.asUint8List());
+
+      if (outgoingString != expectedString) {
+        print('''Index $i did not match:
```
Comment (goderbauer) [inline packages/flutter/test/services/text_input_test.dart]: This would format a little nicer as:

```dart
print(
    'Index $i did not match:\n'
    '  actual: ${outgoingCalls[i]}\n'
    '  expected: ${calls[i]}'
);
```

**Review by goderbauer — APPROVED** [review]
LGTM

I like that all the channel calls are now encapsulated in one object and not all over the place.

File: packages/flutter/lib/src/services/text_input.dart (hunk 11 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: We have an early return at line 926 if `_currentConfiguration == null`.

File: packages/flutter/lib/src/services/text_input.dart (hunk 12 above)
Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Done

File: packages/flutter/test/services/text_input_test.dart (hunk 13 above)
Comment (dnfield) [reply packages/flutter/test/services/text_input_test.dart]: I thought that would make the analyzer unhappy, I was wrong. Done

File: packages/flutter/test/services/text_input_test.dart (hunk 14 above)
Comment (dnfield) [reply packages/flutter/test/services/text_input_test.dart]: Done

File: packages/flutter/test/services/text_input_test.dart (hunk 15 above)
Comment (dnfield) [reply packages/flutter/test/services/text_input_test.dart]: Done

File: packages/flutter/test/services/text_input_test.dart (hunk 16 above)
Comment (dnfield) [reply packages/flutter/test/services/text_input_test.dart]: Done.

File: packages/flutter/test/services/text_input_test.dart (hunk 17 above)
Comment (dnfield) [reply packages/flutter/test/services/text_input_test.dart]: Agreed, done.

**Comment by dnfield** [comment]
This pull request is not suitable for automatic merging in its current state.

- Please resolve merge conflicts before re-applying this label.

**Review by nturgut — APPROVED** [review]
Thanks for the merge Dan!

File: packages/flutter/lib/src/services/text_input.dart [hunk 18]
```diff
@@ -946,4 +928,100 @@ class TextInput {
...
+
+    // The requestExistingInputState request needs to be handled regardless of
+    // the client ID, as long as we have a _currentConnection.
+    if (method == 'TextInputClient.requestExistingInputState') {
+      assert(_currentConnection._client != null);
+      _attach(_currentConnection, _currentConfiguration);
+      // This will be null if we've never had a call to [_setEditingState].
+      if (_currentTextEditingValue != null) {
+        _setEditingState(_currentTextEditingValue);
+      }
```
Comment (dnfield) [inline packages/flutter/lib/src/services/text_input.dart]: It turns out these lines never get called because of https://github.com/flutter/flutter/issues/47137 - see https://github.com/flutter/flutter/pull/47177

Comment (nturgut) [reply packages/flutter/lib/src/services/text_input.dart]: Quick question: in Android or in general?

In Flutter for Web, this is the main part that we are syncing the state from Framework to Platform. It works for the web engine so far.

Let's debug and try to see why it is not the case for Android.

Comment (dnfield) [reply packages/flutter/lib/src/services/text_input.dart]: Android is the only platform that would go down this codepath today.  It shouldn't be a problem for web.

See the linked PR for more details - I don't think this is a problem for web, but it is a problem for Android where the engine side loses state.
