### PR TITLE
when getting xcworkspace, exclude hidden files

### LINKED ISSUE #29052: Unable to load workspace '._Runner.xcworkspace'.
My app works in Android and when I start it in my simulator on a Mac it works.
When I want to validate the app, the **following error** is shown: 

> xcodebuild: error: Unable to load workspace '._Runner.xcworkspace'.
> 	Reason: Unknown.
> 

**Log file:**

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

String: Exit code 74 from: /usr/bin/env xcrun xcodebuild -configuration Release -quiet -workspace ._Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/*/Documents/Flutter/*/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p7/kz6k2ys17gv3rh8qpgfrddyr0000gn/T/flutter_build_log_pipe.iybtHz/pipe_to_stdout -showBuildSettings

```
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:353:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:284:10)
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:505:69)
<asynchronous suspension>
#3      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:79:43)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.1.6, on Mac OS X 10.13.6 17G4015, locale nl-BE)
    [32m•[39m Flutter version 1.1.6 at /Users/*/Flutter/flutter
    [32m•[39m Framework revision d8b57c2ab2 (9 weeks ago), 2019-01-07 09:42:35 -0800
    [32m•[39m Engine revision 7112b72cc2
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 2.0.0
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```
`

What can I do about it?

### PR DESCRIPTION
**Pull request by vashworth**
When getting the xcworkspace, exclude files that begin with `.`.

Fixes https://github.com/flutter/flutter/issues/29052.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 1]
```diff
@@ -326,6 +326,16 @@ class IosProject extends XcodeBasedProject {
     await _updateGeneratedXcodeConfigIfNeeded();
   }
 
+  String? xcworkspacePath() {
+    final List<FileSystemEntity> contents = hostAppRoot.listSync();
+    for (final FileSystemEntity entity in contents) {
+      if (globals.fs.path.extension(entity.path) == '.xcworkspace' && !globals.fs.path.basename(entity.path).startsWith('.')) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:332]: Add a comment here since it's a little strange, something like
```suggestion
      // On certain volume types there is sometimes a stray `._Runner.xcworkspace` file.
      // Find the first non-hidden xcworkspace.
      if (globals.fs.path.extension(entity.path) == '.xcworkspace' && !globals.fs.path.basename(entity.path).startsWith('.')) {
```

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:334]: Added in https://github.com/flutter/flutter/pull/114099/commits/c8af19f8b885eab084643322b756bede1c03f014.

File: packages/flutter_tools/test/general.shard/project_test.dart [hunk 2]
```diff
@@ -350,6 +350,14 @@ void main() {
         expect(versionInfo['build_number'],'3');
         expect(versionInfo['package_name'],'test');
       });
+      _testInMemory('gets xcworkspace path', () async {
```
[the remark this answers is not in the document]
Comment (vashworth) [reply packages/flutter_tools/test/general.shard/project_test.dart:353]: Added in https://github.com/flutter/flutter/pull/114099/commits/8a352430e15e6624b0d9c8632097d797272cea26.

**Review by jmagman — APPROVED** [review]
LGTM!

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 3]
```diff
@@ -326,6 +326,18 @@ class IosProject extends XcodeBasedProject {
     await _updateGeneratedXcodeConfigIfNeeded();
   }
 
+  String? xcworkspacePath() {
+    final List<FileSystemEntity> contents = hostAppRoot.listSync();
+    for (final FileSystemEntity entity in contents) {
+      // On certain volume types, there is sometimes a stray `._Runner.xcworkspace` file.
+      // Find the first non-hidden xcworkspace and return the path.
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/xcode_project.dart:333]: ignoring hidden files, are there sometimes multiple xcworkspace files here? If so, does it matter which we pick?

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:333]: I don't believe there should be other xcworkspace files. @jmagman What do you think?

Comment (jmagman) [reply packages/flutter_tools/lib/src/xcode_project.dart:333]: No, there shouldn't be.  And it was picking the first one found before this PR, and this still does the same.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 4]
```diff
@@ -326,6 +326,18 @@ class IosProject extends XcodeBasedProject {
     await _updateGeneratedXcodeConfigIfNeeded();
   }
 
+  String? xcworkspacePath() {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:329]: Return the `Directory?` instead of a `String`.

Actually looking at this again, this method already exists, so that's the spot that should be updated:

https://github.com/flutter/flutter/blob/9f5c6553bcbd53cc012869504a9c9d89c4133577/packages/flutter_tools/lib/src/xcode_project.dart#L50

That would also correct these, which are based off the `xcodeWorkspace` property.
https://github.com/flutter/flutter/blob/9f5c6553bcbd53cc012869504a9c9d89c4133577/packages/flutter_tools/lib/src/xcode_project.dart#L53-L56

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 5]
```diff
@@ -250,17 +250,14 @@ Future<XcodeBuildResult> buildXcodeProject({
...
-        '-scheme', scheme,
-        if (buildAction != XcodeBuildAction.archive) // dSYM files aren't copied to the archive if BUILD_DIR is set.
-          'BUILD_DIR=${globals.fs.path.absolute(getIosBuildDirectory())}',
-      ]);
-      break;
-    }
+  final String? workspacePath = app.project.xcworkspacePath();
+  if (workspacePath != null) {
+    buildCommands.addAll(<String>[
+      '-workspace', globals.fs.path.basename(workspacePath),
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:256]: Then here you can get the `.basename` off the `FileSystemEntity` instead of reparsing the string.

**Review by jmagman — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:329]: So just to make sure I understand. Instead of using `_hostAppProjectName`, which gets hardcoded as `Runner`, in the `xcodeWorkspace` getter do the loop logic to determine the xcworkspace?

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:329]: If yes, the `xcodeWorkspace` getter return a not-nullable Directory. Should I return like a fallback if the loop doesn't find it? Perhaps what it was originally `hostAppRoot.childDirectory('$_hostAppProjectName.xcworkspace');`?

Or do you think I should change it to return a nullable Directory and try and refactor the code that uses it? Maybe throw an error if it's not found?

In my opinion, a fallback doesn't really make sense because if the loop doesn't find anything, then there isn't a Runner.xcworkspace. But on the other hand, that's what it was originally.

Comment (jmagman) [reply packages/flutter_tools/lib/src/xcode_project.dart:329]: I wouldn't just throw an error here since it's up to the callsite what it needs the workspace for.  For example, in `XcodeBuildSystemMigration` it's being used to check if it exists, and if it doesn't it just skips the migration, and shouldn't error.

I glanced at the places it's used and I don't think it would be too difficult to change `xcodeWorkspace` to a nullable `Directory`.  Give it a shot and see if it makes sense.

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 5 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Updated in https://github.com/flutter/flutter/pull/114099/commits/1596b41ec707513c5f56150bfe088076b71be469.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Updated in https://github.com/flutter/flutter/pull/114099/commits/1596b41ec707513c5f56150bfe088076b71be469.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 6]
```diff
@@ -47,13 +47,23 @@ abstract class XcodeBasedProject extends FlutterProjectPlatform  {
           .childFile('contents.xcworkspacedata');
 
   /// The Xcode workspace (.xcworkspace directory) of the host app.
-  Directory get xcodeWorkspace => hostAppRoot.childDirectory('$_hostAppProjectName.xcworkspace');
+  Directory? get xcodeWorkspace {
+    final List<FileSystemEntity> contents = hostAppRoot.listSync();
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:51]:
```
[module_test_ios] [STDOUT] stderr: Oops; flutter has exited unexpectedly: "FileSystemException: Directory listing failed, path = '/Volumes/Work/s/w/ir/x/t/flutter_module_test.5aHfpx/hello/macos/' (OS Error: No such file or directory, errno = 2)".
[module_test_ios] [STDOUT] stderr: A crash report has been written to /Volumes/Work/s/w/ir/x/t/flutter_module_test.5aHfpx/hello/flutter_01.log.
```
I think this needs to check if `hostAppRoot.exists`

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:54]: Added in https://github.com/flutter/flutter/pull/114099/commits/0305e86d45c696fdc21513c51703cb757a163bc4.

File: packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart [hunk 7]
```diff
@@ -15,16 +15,16 @@ class XcodeBuildSystemMigration extends ProjectMigrator {
     super.logger,
   ) : _xcodeWorkspaceSharedSettings = project.xcodeWorkspaceSharedSettings;
 
-  final File _xcodeWorkspaceSharedSettings;
+  final File? _xcodeWorkspaceSharedSettings;
 
   @override
   void migrate() {
-    if (!_xcodeWorkspaceSharedSettings.existsSync()) {
+    if (_xcodeWorkspaceSharedSettings == null || !_xcodeWorkspaceSharedSettings!.existsSync()) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart:22]: Take advantage of dart type promotion by making a local to avoid the `!`s 
```suggestion
    final File? xcodeWorkspaceSharedSettings = _xcodeWorkspaceSharedSettings;
    if (xcodeWorkspaceSharedSettings == null || !xcodeWorkspaceSharedSettings.existsSync()) {
```
https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

File: packages/flutter_tools/lib/src/macos/build_macos.dart [hunk 8]
```diff
@@ -36,7 +36,8 @@ Future<void> buildMacOS({
   required bool verboseLogging,
   SizeAnalyzer? sizeAnalyzer,
 }) async {
-  if (!flutterProject.macos.xcodeWorkspace.existsSync()) {
+  final Directory? xcodeWorkspace = flutterProject.macos.xcodeWorkspace;
+  if (xcodeWorkspace == null || !xcodeWorkspace.existsSync()) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/build_macos.dart:40]: I think the `existsSync` is not necessary now?
```suggestion
  if (xcodeWorkspace == null) {
```

File: packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart (hunk 7 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart]: Fixed in https://github.com/flutter/flutter/pull/114099/commits/a89d933de8230270a0a5358c642335b2dd01dfa2.

File: packages/flutter_tools/lib/src/macos/build_macos.dart (hunk 8 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/build_macos.dart]: Fixed in https://github.com/flutter/flutter/pull/114099/commits/16e9dead270152baf07ac2ea35e8c9df3b49ef4f.

**Comment by jmagman** [comment]
```

01:09 +2429 ~4 -1: test/general.shard/ios/ios_device_start_nonprebuilt_test.dart: IOSDevice.startApp succeeds in release mode missing project info [E]                                                 
  FileSystemException: No such file or directory, path = 'ios/Runner.xcworkspace/xcshareddata' (OS Error: No such file or directory, errno = 2)
```

File: packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart [hunk 9]
```diff
@@ -20,7 +20,7 @@ class XcodeBuildSystemMigration extends ProjectMigrator {
   @override
   void migrate() {
     final File? xcodeWorkspaceSharedSettings = _xcodeWorkspaceSharedSettings;
-    if (xcodeWorkspaceSharedSettings == null || !xcodeWorkspaceSharedSettings.existsSync()) {
+    if (xcodeWorkspaceSharedSettings == null) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart:23]: Still need this one.

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart]: Ooh you're right, added it back in https://github.com/flutter/flutter/pull/114099/commits/224a5c40654121f40026004b915ca8a554527ae8.

File: packages/flutter_tools/test/general.shard/ios/ios_project_migration_test.dart [hunk 10]
```diff
@@ -1024,4 +1038,4 @@ class FakeIOSMigrator extends ProjectMigrator {
   String migrateLine(String line) {
     return line;
   }
-}
+}
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/ios/ios_project_migration_test.dart:1041]:
```
   info • Put a single newline at end of file • packages/flutter_tools/test/general.shard/ios/ios_project_migration_test.dart:1041:2 • eol_at_end_of_file

```

Comment (vashworth) [reply packages/flutter_tools/test/general.shard/ios/ios_project_migration_test.dart]: Fixed in https://github.com/flutter/flutter/pull/114099/commits/2637c23e341c698f44dfa6c79b78152b74ac33ea.

**Comment by christopherfujino** [comment]
Your Mac tool_tests_commands failure was fixed upstream, rebasing master from upstream should fix.

**Review by jmagman — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM, thanks so much for landing this fix!
