### PR TITLE
fix-huawei-imagereader-166481

### LINKED ISSUE #166481: Video player on Android 29 device does not play media
### Steps to reproduce

This is the same issue with [this](https://github.com/flutter/flutter/issues/154068). It is re-occurred in Flutter 3.29.2 and 3.31.0-1.0.pre.363.

Run simple example of video player app. Video player version is 2.9.5. Tested with impeller and skia, both not working.

### Expected results

Video is playing

### Actual results

Video not playing

### Code sample

<details open><summary>Code sample</summary>

Tested with impeller and skia, both not working.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/ExoPlayerImpl(12629): Init ff2837 [AndroidXMedia3/1.4.1] [HWSNE, SNE-LX1, HUAWEI, 29]
W/me.castify(12629): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
D/NetworkSecurityConfig(12629): No Network Security Config specified, using platform default
D/ProfileInstaller(12629): Installing profile for me.castify
W/VideoCapabilities(12629): Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities(12629): Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities(12629): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(12629): Unsupported profile 5 for video/mpeg2
I/chatty  (12629): uid=10212(me.castify) ExoPlayer:Playb identical 2 lines
I/VideoCapabilities(12629): Unsupported profile 5 for video/mpeg2
W/VideoCapabilities(12629): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(12629): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(12629): Unrecognized profile/level 32768/64 for video/mp4v-es
I/OMXClient(12629): IOmx service obtained
I/ACodec  (12629): In onAllocateComponent create compenent, codec name: OMX.hisi.video.decoder.avc
D/SurfaceUtils(12629): connecting to surface 0x7a01fc3010, reason connectToSurface
I/MediaCodec(12629): [OMX.hisi.video.decoder.avc] setting surface generation to 12932097
D/SurfaceUtils(12629): disconnecting from surface 0x7a01fc3010, reason connectToSurface(reconnect)
D/SurfaceUtils(12629): connecting to surface 0x7a01fc3010, reason connectToSurface(reconnect)
E/ACodec  (12629): [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) and dataspace 0x102
I/ACodec  (12629): onStart
I/HwExtendedUtils(12629): Set to window composer mode as 2
I/ACodec  (12629): gralloc usage: 0(OMX) => 0x2900(ACodec)
D/SurfaceUtils(12629): disconnecting from surface 0x7a01fc3010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(12629): connecting to surface 0x7a01fc3010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(12629): set up nativeWindow 0x7a01fc3010 for 222x480, color 0x30d, rotation 0, usage 0x2900
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 11 failed: -1010
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 10 failed: -1010
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 9 failed: -1010
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] Allocating 8 buffers from a native window of size 276480 on output port
W/Gralloc3(12629): allocator 3.x is not supported
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) and dataspace 0x103
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) and dataspace 0x103
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] Now handling output port settings change
I/ACodec  (12629): [OMX.hisi.video.decoder.avc] Output port now disabled.
I/HwExtendedUtils(12629): Set to window composer mode as 2
I/ACodec  (12629): gralloc usage: 0(OMX) => 0x2900(ACodec)
D/SurfaceUtils(12629): disconnecting from surface 0x7a01fc3010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(12629): connecting to surface 0x7a01fc3010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(12629): set up nativeWindow 0x7a01fc3010 for 224x480, color 0x30d, rotation 0, usage 0x2900
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 19 failed: -1010
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 18 failed: -1010
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 17 failed: -1010
W/ACodec  (12629): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 16 failed: -1010
E/ACodec  (12629): Failed to allocate output port buffers after port reconfiguration: (-1010)
E/ACodec  (12629): signalError(omxError 0x80001001, internalError -1010)
E/MediaCodec(12629): Codec reported err 0xfffffc0e, actionCode 0, while in state 6
E/ACodec  (12629): Error occurred while disabling the output port
D/SurfaceUtils(12629): disconnecting from surface 0x7a01fc3010, reason disconnectFromSurface
E/MediaCodecVideoRenderer(12629): Video codec error
E/MediaCodecVideoRenderer(12629):   java.lang.IllegalStateException
E/MediaCodecVideoRenderer(12629):       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/MediaCodecVideoRenderer(12629):       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:101)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1316)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/MediaCodecVideoRenderer(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/MediaCodecVideoRenderer(12629):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/MediaCodecVideoRenderer(12629):       at android.os.Looper.loop(Looper.java:219)
E/MediaCodecVideoRenderer(12629):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(12629): Playback error
E/ExoPlayerImplInternal(12629):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4015, 1540000, null, [222, 480, -1.0, ColorInfo(BT601, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(12629):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(12629):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(12629):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(12629):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal(12629):       ... 3 more
E/ExoPlayerImplInternal(12629):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(12629):       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/ExoPlayerImplInternal(12629):       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:101)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1316)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/ExoPlayerImplInternal(12629):       ... 6 more
E/ExoPlayerImplInternal(12629): Disable failed.
E/ExoPlayerImplInternal(12629):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(12629):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(12629):       at android.media.MediaCodec.flush(MediaCodec.java:2194)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
E/ExoPlayerImplInternal(12629):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
E/ExoPlayerImplInternal(12629):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(12629):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(12629):       at android.os.HandlerThread.run(HandlerThread.java:67)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.31.0-1.0.pre.363, on macOS 15.3.2 24D81 darwin-arm64, locale en-TR) [1,480ms]
    • Flutter version 3.31.0-1.0.pre.363 on channel main at /Users/bekirtaskin/Dev/fluttersdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a0b1b32534 (27 hours ago), 2025-04-01 12:33:23 -0400
    • Engine revision a0b1b32534
    • Dart version 3.8.0 (build 3.8.0-250.0.dev)
    • DevTools version 2.45.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [840ms]
    • Android SDK at /Users/bekirtaskin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [472ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] Connected device (4 available) [5.6s]
    • SNE LX1 (mobile)                   • HVYDU19313003053          • android-arm64  • Android 10 (API 29)
    • Bekir iPhone’u (wireless) (mobile) • 00008140-00161C69029B001C • ios            • iOS 18.4 22E240
    • macOS (desktop)                    • macos                     • darwin-arm64   • macOS 15.3.2 24D81 darwin-arm64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 134.0.6998.167

[✓] Network resources [792ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by serbandin**
Fixes video playback issues on Huawei devices running Android API level 29 or below by falling back to SurfaceTextureSurfaceProducer instead of ImageReaderSurfaceProducer.

### Problem
On certain Huawei devices with Android 10 (API 29), video playback fails when using ImageReaderSurfaceProducer. This is due to issues with AHB (Android Hardware Buffer) imports on these devices, similar to the Vulkan fallback already implemented in android_context_dynamic_impeller.cc. Fixes https://github.com/flutter/flutter/issues/166481

### Solution
Added a new JNI method shouldDisableImageReader() that detects Huawei devices by checking the ro.com.google.clientidbase system property for the value "android-huawei" when the API level is 29 or below. When this method returns true, FlutterRenderer.createSurfaceProducer() uses SurfaceTextureSurfaceProducer instead of ImageReaderSurfaceProducer, which resolves the video playback issue.

### Changes
FlutterJNI.java: Added shouldDisableImageReader() method and native bridge
platform_view_android_jni_impl.cc: Native implementation using __system_property_get() and android_get_device_api_level()
FlutterRenderer.java: Integration in createSurfaceProducer() condition (line 230)
FlutterRendererTest.java: Unit test for the new behavior

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java [hunk 1]
```diff
@@ -244,6 +244,18 @@ public boolean getIsSoftwareRenderingEnabled() {
     return nativeGetIsSoftwareRenderingEnabled();
   }
 
+  private native boolean nativeShouldDisableImageReader();
+
+  /**
+   * Checks if ImageReader should be disabled for this device.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java]: nit: can you link to the source for which ImageReader that is keyword that can lead to a lot of different types of code.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java [hunk 2]
```diff
@@ -244,6 +244,18 @@ public boolean getIsSoftwareRenderingEnabled() {
...
+   *
+   * <p>Returns true for Huawei devices on API level 29 or below due to known issues with
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java]: Other than than the bug is there any other source we can point to that says that imagereader is known to not work on huawei devices?

Comment (reidbaker) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java]: maybe https://github.com/bromite/bromite/issues/814

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java [hunk 3]
```diff
@@ -823,6 +823,23 @@ public void SurfaceTextureSurfaceProducerDoesNotCropOrRotate() {
...
+    // ImageReaderSurfaceProducer.
+    when(fakeFlutterJNI.shouldDisableImageReader()).thenReturn(true);
+
+    // Execute the behavior under test.
+    FlutterRenderer flutterRenderer = engineRule.getFlutterEngine().getRenderer();
+    TextureRegistry.SurfaceProducer producer = flutterRenderer.createSurfaceProducer();
+
+    // Verify behavior under test.
+    // SurfaceTextureSurfaceProducer handles crop and rotation, ImageReaderSurfaceProducer does not.
+    assertTrue(producer.handlesCropAndRotation());
```
Comment (gaaclarke) [inline engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java]: I'd prefer a more apropos assertion instead of relying on secondary information to test what you really want.

File: engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc [hunk 4]
```diff
@@ -552,6 +554,22 @@ static jboolean GetIsSoftwareRendering(JNIEnv* env, jobject jcaller) {
...
+  constexpr char kClientIdBaseProperty[] = "ro.com.google.clientidbase";
+
+  if (android_get_device_api_level() > kHuaweiMaxApiLevel) {
+    return false;
+  }
+
+  char property[PROP_VALUE_MAX];
+  __system_property_get(kClientIdBaseProperty, property);
+  return strcmp(property, kAndroidHuawei) == 0;
+}
```
Comment (gaaclarke) [inline engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc]: I don't believe there is any reason we have to use JNI for this.  I think this same test can be performed from java.

**Review by gaaclarke — COMMENTED** [review]
@reidbaker  I don't know about wether we want to disable the image reader or not on certain devices.  I'll let the Android team decide on that.  Ideally the linked issue should provide enough documentation.

I think we should avoid doing JNI here since the check can happen with the java apis.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java (hunk 2 above)
Comment (serbandin) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java]: There are a lot of old issue with Huawei not playing videos on api 29.
https://github.com/flutter/flutter/issues/156459 
https://github.com/flutter/flutter/issues/154068
Also here's an old PR that fixed it initially: https://github.com/flutter/engine/pull/54879
Seems to be related to the OMX.hisi.* Decoder. It happens on Kirin 710/970/980 from what I saw in the comments / tested myself.

File: engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc (hunk 4 above)
Comment (serbandin) [reply engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc]: a check like this in java would be better?

    return Build.VERSION.SDK_INT <= API_LEVELS.API_29
        && "HUAWEI".equalsIgnoreCase(Build.MANUFACTURER);

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc]: Yes, avoiding JNI is a win.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java [hunk 5]
```diff
@@ -63,6 +63,19 @@ public class FlutterRenderer implements TextureRegistry {
...
 
+  /**
+   * Returns true if this device has a known issue with {@link ImageReaderSurfaceProducer}.
+   *
+   * <p>Huawei devices on API 29 or below have {@link android.media.ImageReader} issues that cause
+   * video playback failures.
+   *
+   * @see <a href="https://github.com/flutter/flutter/issues/166481">#166481</a>
+   */
+  private static boolean hasImageReaderIssue() {
```
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java]: Small thing: I would prefer a name that is more specific to the issue at hand like `hasAndroidHardwareBufferDefect` or `requiresSurfaceTextureSurfaceProducer`.

File: engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc:1]: Are these changes still required?

**Review by camsim99 — COMMENTED** [review]
Looks good to me overall--just one nit and a question!

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java (hunk 1 above)
Comment (serbandin) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java]: done

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java (hunk 3 above)
Comment (serbandin) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java]: done

File: engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc
Comment (serbandin) [reply engine/src/flutter/shell/platform/android/platform_view_android_jni_impl.cc:1]: indeed not needed anymore

**Review by camsim99 — APPROVED** [review]
This approach LGTM thanks for the fixes!

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java [hunk 6]
```diff
@@ -823,6 +825,23 @@ public void SurfaceTextureSurfaceProducerDoesNotCropOrRotate() {
...
+    ShadowBuild.setManufacturer("HUAWEI");
+
+    // Execute the behavior under test.
+    FlutterRenderer flutterRenderer = engineRule.getFlutterEngine().getRenderer();
+    TextureRegistry.SurfaceProducer producer = flutterRenderer.createSurfaceProducer();
+
+    // Verify: Should return SurfaceTextureSurfaceProducer instead of ImageReaderSurfaceProducer.
+    assertTrue(
+        "Expected SurfaceTextureSurfaceProducer on Huawei API <= 29 due to HardwareBuffer defect causing video playback failures",
+        producer instanceof FlutterRenderer.SurfaceTextureSurfaceProducer);
```
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java]: Looks like you're missing an import

```sh
/b/s/w/ir/cache/builder/engine/src/flutter/shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java:842: error: cannot find symbol
          producer instanceof FlutterRenderer.SurfaceTextureSurfaceProducer);
                                             ^
    symbol:   class SurfaceTextureSurfaceProducer
    location: class FlutterRenderer
  1 error
```

**Review by gaaclarke — APPROVED** [review]
Changes looks good, the code is adequately tested.  I don't know if we can definitively know all the values of Build.MANUFACTURER to make sure we catch everything, but this is progress regardless.  I'll defer to the Android team as to wether they want the change or not (sounds like they do!)

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java [hunk 7]
```diff
@@ -63,6 +63,19 @@ public class FlutterRenderer implements TextureRegistry {
...
+  /**
+   * Returns true if this device has a known {@link android.hardware.HardwareBuffer} defect.
+   *
+   * <p>Huawei devices on API 29 or below have {@link android.media.ImageReader} issues that cause
+   * video playback failures due to defective HardwareBuffer implementations.
+   *
+   * @see <a href="https://github.com/flutter/flutter/issues/166481">#166481</a>
+   */
+  private static boolean hasAndroidHardwareBufferDefect() {
+    return Build.VERSION.SDK_INT <= API_LEVELS.API_29
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java:87]:
```suggestion
    // To test if some device should be added from this list app developers first should attempt to play a video and see a failure in the logs. 
    /// ```E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xfffffc0e)
    /// W/ACodec: [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 12 failed: -1010 E/MediaCodecVideoRenderer: Video codec error```
     /// Then try setting `FlutterRenderer.debugForceSurfaceProducerGlTextures = true` in an example app. 
    /// If the video plays then that is a strong signal that this method should be updated to include the tested device. 
    return Build.VERSION.SDK_INT <= API_LEVELS.API_29
```

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java [hunk 8]
```diff
@@ -63,6 +63,19 @@ public class FlutterRenderer implements TextureRegistry {
    */
   @VisibleForTesting public static boolean debugForceSurfaceProducerGlTextures = false;
 
+  /**
+   * Returns true if this device has a known {@link android.hardware.HardwareBuffer} defect.
+   *
+   * <p>Huawei devices on API 29 or below have {@link android.media.ImageReader} issues that cause
+   * video playback failures due to defective HardwareBuffer implementations.
+   *
+   * @see <a href="https://github.com/flutter/flutter/issues/166481">#166481</a>
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java]:
```suggestion
   * @see <a href="https://github.com/flutter/flutter/issues/166481">#166481</a>
   * See <a href="https://github.com/flutter/flutter/issues/156459">#156459</a>
   * See <a href="https://github.com/flutter/flutter/issues/154068">#154068</a>
   * See <a href="https://github.com/flutter/engine/pull/54879">engine pr #54879</a>
```

**Review by reidbaker — APPROVED** [review]
I added 2 suggestions if you like those accept and I can add autosubmit. If you have corrections or I am mistaken please let me know and add whatever you think is more correct.

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
I don't have a link handy but we are having an outage on our side. Don't worry about it and I will try to get this landed Monday after our outage is resolved. No action needed from you

**Comment by jeff-upscrolled** [comment]
Hello, this fix was merged to `master` 3 months ago, but still hasn't been added to the stable channel. It'd be useful to finalize this fix :)

**Comment by camsim99** [comment]
> Hello, this fix was merged to `master` 3 months ago, but still hasn't been added to the stable channel. It'd be useful to finalize this fix :)

This fix is in the latest stable, 3.44!

**Comment by reidbaker** [comment]
@jeff-upscrolled following the instructions here https://github.com/flutter/flutter/blob/master/docs/releases/Where's-my-commit.md that I linked in https://github.com/flutter/flutter/pull/181931#issuecomment-3967147168 I see the commit in the following flutter releases.
Screenshot 2026-05-22 at 1 57 05 PM
Which includes 3.44. According to https://docs.flutter.dev/install/archive 3.44 is live and stable. 

If you are using those versions of flutter and still are seeing this behavior please file an issue and let us know.
