### PR TITLE
Exception when selecting in TextField

### LINKED ISSUE #37046: Exception when selecting on TextField
## Steps to Reproduce

1. On iOS, press and hold on a TextField

## Logs

```[+8646 ms] flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown during performLayout():
[        ] flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1694 pos 18: 'debugDoingThisResize
[        ] flutter: || debugDoingThisLayout ||
[        ] flutter:                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not
[        ] flutter: true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1694:18)
[        ] flutter: #3      RenderBox.size (package:flutter/src/rendering/box.dart:1700:6)
[        ] flutter: #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2425:24)
[        ] flutter: #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2167:24)
[        ] flutter: #6      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2244:31)
[        ] flutter: #7      _ToolbarRenderBox.performLayout (package:flutter/src/cupertino/text_selection.dart:167:35)
[        ] flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] flutter: #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] flutter: #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
[        ] flutter: #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
[        ] flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
[        ] flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
[        ] flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
[        ] flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
[        ] flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
[        ] flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
[        ] flutter: #25     _invoke (dart:ui/hooks.dart:236:10)
[        ] flutter: #26     _drawFrame (dart:ui/hooks.dart:194:3)
[        ] flutter: (elided 5 frames from class _AssertionError and package dart:async)
[        ] flutter:
[        ] flutter: The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#3eb03 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
[        ] flutter:   needs compositing
[        ] flutter:   creator: CupertinoTextSelectionToolbar ← CompositedTransformFollower ← FadeTransition ←
[        ] flutter:     _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#f279e] ← Stack ← _Theatre ←
[        ] flutter:     Overlay-[LabeledGlobalKey<OverlayState>#d6d11] ← _FocusMarker ← Semantics ← FocusScope ←
[        ] flutter:     AbsorbPointer ← Listener ← ⋯
[        ] flutter:   parentData: <none> (can use size)
[        ] flutter:   constraints: BoxConstraints(w=414.0, h=736.0)
[        ] flutter:   size: Size(414.0, 736.0)
[        ] flutter: This RenderObject had the following descendants (showing up to depth 5):
[        ] flutter:     child: RenderDecoratedBox#7f472 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:       child: RenderFlex#e2bf8 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:         child 1: RenderSemanticsGestureHandler#46929 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:           child: RenderPointerListener#40223 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:             child: RenderSemanticsAnnotations#d9e45 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:         child 2: RenderConstrainedBox#bd267 relayoutBoundary=up3 NEEDS-PAINT
[        ] flutter:         child 3: RenderSemanticsGestureHandler#deb4a relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:           child: RenderPointerListener#54aae relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:             child: RenderSemanticsAnnotations#a5ece relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[   +2 ms] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
```

```Analyzing fingo_app...
No issues found! (ran in 4.7s)
```

```[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F203, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/robson/work/flutter
    • Framework revision 20e59316b8 (8 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/robson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7019

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Fingo’s iPhone • 48bb3178ff6a329c776e8ff9535fbc11b7e76ebf • ios • iOS 12.2

• No issues found!
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

In an app with nested Navigators, selecting text in a TextField caused an exception to be logged.  

This PR fixes it by removing the offending call to `globalToLocal`, which turns out to be unnecessary.  The coordinates relative to the selection menu are always equivalent to global coordinates, because the selection menu is in an Overlay covering the entire screen.  Even in situations where the containing Navigator does not cover the full screen, the Overlay still does.

## Related Issues

Closes https://github.com/flutter/flutter/issues/37046

## Tests

I added the following tests:

  * A test that renders an app with nested Navigators, shows the selection menu, and verifies that there were no exceptions.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 1]
```diff
@@ -164,15 +164,15 @@ class _ToolbarRenderBox extends RenderShiftedBox {
     child.layout(heightConstraint.enforce(enforcedConstraint), parentUsesSize: true,);
     final _ToolbarParentData childParentData = child.parentData;
 
-    final Offset localTopCenter = globalToLocal(Offset(_arrowTipX, _barTopY));
+    final Offset topCenter = Offset(_arrowTipX, _barTopY);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection.dart]: nit: `localTopCenter` was created so `_arrowTipX` and `_barTopY` can be converted to local coordinates. Now that it's no longer needed, removing the variable all together might make the code more readable.

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart]: Good call.
