### PR TITLE
Do not schedule animation if already at the target value

### LINKED ISSUE #11495: Scrollable TabBar ignores taps while transition is in progress
## Steps to reproduce
1. Open the gallery app
1. Enable slow animations in the hamburger menu
1. Go to the "Scrollable Tabs" demo
1. Click on the last tab.
1. While transition is in progress, tap on the first tab again

## Result
The last tap is ignored.

The reason for this is probably that the Scrollable introduces an IgnorePointer widget that is set to ignore while the animation is in progress.

### PR DESCRIPTION
**Pull request by goderbauer**
* Partially fixes https://github.com/flutter/flutter/issues/11495.
* Also includes a fix for Cupertino button to always run the tap animation even if the finger is immediately lifted from the screen (uncovered by a test failure).

### CODE REVIEW

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 1]
```diff
@@ -38,6 +38,10 @@ const Tolerance _kFlingTolerance = const Tolerance(
   distance: 0.01,
 );
 
+/// Don't start the animation if the target value is within this tolerance of
+/// the current value.
+const Tolerance _kAnimateToTolerance = const Tolerance();
```
Comment (Hixie) [inline packages/flutter/lib/src/animation/animation_controller.dart]: You want to get this from the ScrollPosition somehow. Maybe AnimationController should take a Tolerance that it then passes on to all its simulations, etc, and uses in animateTo; then you could just pass the ScrollPosition's tolerance through (I forget where exactly we store that, it might be on the ScrollPhysics).

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 2]
```diff
@@ -335,6 +339,14 @@ class AnimationController extends Animation<double>
       final double range = upperBound - lowerBound;
       final double remainingFraction = range.isFinite ? (target - _value).abs() / range : 1.0;
       simulationDuration = this.duration * remainingFraction;
+    } else if (target < _value + _kAnimateToTolerance.distance && target > _value - _kAnimateToTolerance.distance) {
```
Comment (Hixie) [inline packages/flutter/lib/src/animation/animation_controller.dart]: We have a method that wraps this expression, I think. `nearEqual` or some such.
(Might be worth putting it on Tolerance itself...)

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 3]
```diff
@@ -335,6 +339,14 @@ class AnimationController extends Animation<double>
...
+      // We are basically at the target, don't animate.
+      simulationDuration = Duration.ZERO;
+      if (target != _value) {
+        _internalSetValue(target);
+        notifyListeners();
+        target = _value;
+      }
     }
     stop();
     if (simulationDuration == Duration.ZERO) {
```
Comment (Hixie) [inline packages/flutter/lib/src/animation/animation_controller.dart]: _internalSetValue does the setting of _status as well (as the code below). We might want to refactor this to be clearer about setting this only once.

File: packages/flutter/lib/src/cupertino/button.dart [hunk 4]
```diff
@@ -146,16 +149,19 @@ class _CupertinoButtonState extends State<CupertinoButton> with SingleTickerProv
...
   }
 
-  void _handleTapCancel(PointerCancelEvent event) {
-    _animationController.animateTo(0.0, duration: kFadeInDuration);
+  Future<Null>  _handleTapCancel(PointerCancelEvent event) async {
+    await _lastAnimation;
+    _lastAnimation = _animationController.animateTo(0.0, duration: kFadeInDuration);
   }
 
   @override
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: the changes to CupertinoButton need a test

File: packages/flutter/test/animation/animation_controller_test.dart [hunk 5]
```diff
@@ -292,4 +292,30 @@ void main() {
...
+
+    final AnimationController controller = new AnimationController(
+      value: 0.5,
+      vsync: const TestVSync(),
+    )..addStatusListener(statusLog.add);
+
+    controller.animateTo(0.5, duration: const Duration(milliseconds: 100),);
+    expect(statusLog, equals(<AnimationStatus>[ AnimationStatus.completed ]));
+    expect(controller.value, equals(0.5));
+  });
```
Comment (Hixie) [inline packages/flutter/test/animation/animation_controller_test.dart]: please add tests for doing this that verify all the various combinations of doing this and verify that the state changes are as you would expect. For example, animateTo() while animating forward. animateTo() while animating backward. animateTo() the lowerBound. animateTo() the upper bound. And so on.

Comment (Hixie) [inline packages/flutter/test/animation/animation_controller_test.dart]: (the key here is not to verify that your code is correct, it's to verify that when i go in and refactor this randomly one day, i don't break the behaviour you intended.)

File: packages/flutter/lib/src/cupertino/button.dart [hunk 6]
```diff
@@ -146,16 +149,19 @@ class _CupertinoButtonState extends State<CupertinoButton> with SingleTickerProv
     _setTween();
   }
 
-  void _handleTapDown(PointerDownEvent event) {
-    _animationController.animateTo(1.0, duration: kFadeOutDuration);
+  Future<Null> _handleTapDown(PointerDownEvent event) async {
+    await _lastAnimation;
+    _lastAnimation = _animationController.animateTo(1.0, duration: kFadeOutDuration);
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: If you get multiple taps in a row, this will mess up, because you'll have multiple _handleTapDown methods in flight at once.

Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/button.dart]: How will this mess up? The first tap down will animate from 0.0 to 1.0. The next tap down (and all subsequent once) will animate from 1.0 to 1.0 (which is a no-op after this fix).

File: packages/flutter/lib/src/cupertino/button.dart (hunk 4 above)
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/button.dart]: As stated in the PR description: This change is a response to a failing test. We had a test that verified an animation was in progress when a tap down was immediately followed by a tap up.  This used to result in an animation from 0.0 to 0.0, so no animation at all (which this PR explicitly exposes). So either, we already have a test for this and the change her just adopts the implementation to what the test really expects or the test was incorrect and there shouldn't be an animation (looking at OEM widgets it seems like there should be an animation).

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 2 above)
Comment (goderbauer) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Done.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 3 above)
Comment (goderbauer) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Done.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 1 above)
Comment (goderbauer) [inline packages/flutter/lib/src/animation/animation_controller.dart]: That makes me wonder if we should remove the tolerance from the animation controller altogether  and check in the ScrollPosition's animateTo if we are asked to animate to roughly the same position we're already at. And if that's the case, just redirect to the ScrollPosition's jumpTo.

File: packages/flutter/lib/src/cupertino/button.dart (hunk 4 above)
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: aah, i see.

File: packages/flutter/lib/src/cupertino/button.dart (hunk 6 above)
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: imagine the user goes down-up-down-up-down.

The first down will start an animation to 1.0 (i assume you can `await null` with impunity?).
The next five callbacks all await that animation.
The animation ends at 1.0. The first callback to react is an up, it starts an animation to 0.0. Then the next callback starts an animation to 1.0 (which just stops the animation since it's already there), then the next one restarts it to 0.0, then we stop it again...

I guess it works, it just feels very wrong to be scheduling all these calls that stomp on each other.

Oh, also we need to check "mounted" after the await, in case the widget is gone and the controller has been disposed.

Also, we should fix this to use onTapDown/onTapUp/onTapCancel rather than a pointer listener.

Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/button.dart]: Refactored to ensure that we don't chain fade-in/fade-out animation sets. Also added the "mounted" check.

Furthermore, I tweaked the animation timing a little bit; for me, it looks closer to what iOS is doing and it also makes it much harder (impossible?) to trigger the edge cases where you get a down and up event while the previous up animation is still in progress.

The "fix" to use onTapDown/onTapUp/onTapCancel from a GestureDetector doesn't work well as it delays the firing of onTapDown by 100ms (`kPressTimeout`), which makes the button seem unresponsive.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 1 above)
Comment (goderbauer) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Refactored to what I said in my previous comment.

File: packages/flutter/lib/src/cupertino/button.dart (hunk 6 above)
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: That only happens when the tap might be disambiguated as something else though, right?

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/cupertino/button.dart (hunk 6 above)
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/button.dart]: Hm, in my limited testing (with a big value for the constant) it is always delaying the onTapDown call by `kPressTimeout`.

Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: That sounds like a bug...
