### PR TITLE
[skwasm] Fix clip rect occlusion rect calculation.

### LINKED ISSUE #59993: [wasm] Tooltip not rendered over an embedded iFrame
Tooltip rendered over the top of an iFrame (canvaskit renderer)
Image

Tooltip rendered over the top of an iFrame (wasm renderer) - **notice it is cutoff where the iFrame bound begins**
Image

Tooltip rendered over the top of a normal Flutter UI (wasm renderer):
Image

```
Flutter 3.28.0-2.0.pre.38764 • channel [user-branch] • unknown source
Framework • revision 90f926edc1 (11 days ago) • 2025-01-16 11:29:36 -0800
Engine • revision 90f926edc1
Tools • Dart 3.7.0 (build 3.7.0-323.0.dev) • DevTools 2.42.0
```

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
The clip region is always expressed in the global coordinates. Hence, we should do the intersection with the clip *after* transforming the rectangle to global coordinates.

This fixes https://github.com/dart-lang/sdk/issues/59993

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/keyboard_binding.dart [hunk 1]
```diff
@@ -9,7 +9,7 @@ import 'package:ui/ui.dart' as ui;
 import 'package:ui/ui_web/src/ui_web.dart' as ui_web;
 import 'package:web_locale_keymap/web_locale_keymap.dart' as locale_keymap;
 
-import '../engine.dart' show registerHotRestartListener;
+import '../engine.dart' show kDebugMode, registerHotRestartListener, renderer;
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/keyboard_binding.dart:12]:
```suggestion
import 'initialization.dart';
import 'renderer.dart';
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/layers.dart [hunk 2]
```diff
@@ -777,7 +956,7 @@ class PlatformViewStyling {
   final PlatformViewClip clip;
 
   ui.Rect mapLocalToGlobal(ui.Rect rect) {
-    return position.mapLocalToGlobal(rect.intersect(clip.outerRect));
+    return position.mapLocalToGlobal(rect).intersect(clip.outerRect);
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/layers.dart:959]: Is this the actual bug fix? I'm afraid it's hard to spot due to being buried between hundreds of unrelated changes. Would you consider splitting this into 2 PRs?

File: engine/src/flutter/lib/web_ui/dev/generate_scene_test.dart [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+ui.Picture drawPicture(ui.Rect bounds, ui.Color color) {
+  final recorder = ui.PictureRecorder();
+  final canvas = ui.Canvas(recorder);
+  canvas.drawRect(bounds, ui.Paint()..color = color);
+  return recorder.endRecording();
+}
+
+ui.Scene buildScene() {
+  final ui.SceneBuilder builder = ui.SceneBuilder();''');
+  emitCommands(rootLayer['commands'], '  ');
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/dev/generate_scene_test.dart:251]: Should we add a comment here saying these commands were generated from dumped info, etc?

**Review by mdebbar — APPROVED** [review]

File: engine/src/flutter/lib/web_ui/lib/src/engine/layers.dart (hunk 2 above)
Comment (eyebrowsoffire) [reply engine/src/flutter/lib/web_ui/lib/src/engine/layers.dart:959]: Yes, this is the bug fix. I'll try to split this up into two PRs.

**Review by mdebbar — APPROVED** [review]
Approving again. Thank you!
