### PR TITLE
Removed TBD translations for optional remainingTextFieldCharacterCounZero message

### LINKED ISSUE #136090: There are wrong de-CH translations in package/flutter-localization
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I found in [`MaterialLocalizationDe`](https://github.com/flutter/flutter/blob/420ec92e7274135b3611a0ab92f8645bd5504f5e/packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart#L6769) a translation "TBD" and some clear translation errors like there is no `ß` in de-CH

### Expected results

No TBD translations in German and no `ß` letters in de-CH.

### Actual results

There is a translation "TBD" which seems to be wrong. I also found wrong translations for de-CH (basically de-DE just in upper case) and some clear translation errors like there is no `ß` in de-CH

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/136090

### CODE REVIEW

File: packages/flutter_localizations/test/material/translations_test.dart [hunk 1]
```diff
@@ -56,6 +56,9 @@ void main() {
       expect(localizations.expandedHint, isNotNull);
       expect(localizations.refreshIndicatorSemanticLabel, isNotNull);
 
+      // Regression test for https://github.com/flutter/flutter/issues/136090
+      expect(localizations.remainingTextFieldCharacterCount(0), isNot(contains('TBD')));
```
Comment (goderbauer) [inline packages/flutter_localizations/test/material/translations_test.dart:60]: 😆

**Review by goderbauer — APPROVED** [review]
LGTM

Thank you!
