### PR TITLE
DatePicker noon/midnight overflow fix

### LINKED ISSUE #27755: CupertinoDatePicker in time mode gets confused around 12am/pm
## Steps to Reproduce

Cupertino DateTime picker is getting confused around AM and PM if use24hFormat is false.

1. When 12:XX PM is initial time, moving to 11:XX swaps to AM correctly and reports correct time, but moving to 1:XX swaps to AM. Just moving the minute value displays PM but reports as 0:XX instead of 12:XX.
2. When 1:XX PM is initial time, moving to back to 12:XX or forward to 2:XX swaps to AM instead of staying at PM.
3. When 0:XX is initial time, moving back to 11:XX swaps to PM, but moving back to 10:XX incorrectly swaps back to AM. Moving forward to 1:XX stays at AM, but moving forward to 2:XX incorrectly swaps to PM

The Flutter Gallery Pickers demo for Time and "Date and Time" display same behavior.

Also on iOS AM is displayed as "am", and PM as "pm"

Code:
```dart
TimeOfDay startTime = TimeOfDay.now();
await showCupertinoModalPopup(
        context: context,
        builder: (BuildContext context) {
          return _buildBottomPicker(
            CupertinoDatePicker(
              mode: CupertinoDatePickerMode.time,
              initialDateTime: new DateTime(date.year, date.month, date.day, startTime.hour, startTime.minute),
              onDateTimeChanged: (DateTime newDateTime) {
                //setState(() => time = newDateTime);
                time = new TimeOfDay(hour: newDateTime.hour, minute: newDateTime.minute);
              },
            ),
          );
        },
      );
```

## Logs

```
D:\VSProjects\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.2.0 at D:\VSProjects\flutter
    • Framework revision 06b979c4d5 (2 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jonny\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[!] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • HTC 0PJA10 • FA632YJ02378 • android-arm64 • Android 7.0 (API 24)
```

### PR DESCRIPTION
**Pull request by timtraversy**
Fixes https://github.com/flutter/flutter/issues/27755. When the Date Picker was scrolled from 12:XX PM to 12:YY PM, the new date was being reported as 0:YY AM. A similar error occurred for 12:XX AM TO 12:YY PM. This was because of an incorrect calculation:
```
selectedHour + selectedAmPm * 12 // If the hour is 12 PM, this becomes 24 PM, which is actually 0 AM.
```
This PR fixes that, and adds two tests for initial noon/midnight times.

### CODE REVIEW

**Comment by HansMuller** [comment]
Thank you for the analysis in #27755 and the fix!

The change LGTM, I'll land it when the build is green.

**Review by HansMuller — APPROVED** [review]
~~LGTM~~ Sorry about that. I don't think this is right when CupertinoDatePicker.use24hFormat is true.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 1]
```diff
@@ -448,7 +448,7 @@ class _CupertinoDatePickerDateTimeState extends State<CupertinoDatePicker> {
       date.year,
       date.month,
       date.day,
-      selectedHour + selectedAmPm * 12,
+      selectedHour % 12 + selectedAmPm * 12,
```
Comment (HansMuller) [inline packages/flutter/lib/src/cupertino/date_picker.dart]: If use24hFormat is true then selectedAmPm is 0 and the %12 isn't correct.

**Review by HansMuller — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 1 above)
Comment (timtraversy) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: `selectedAmPm * 12 + (widget.use24hFormat ? selectedHour : selectedHour % 12)`
Too long?

Comment (timtraversy) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: Actually this is a little clearer about intent:
`widget.use24hFormat ? selectedHour : selectedHour % 12 + selectedAmPm * 12`

Comment (HansMuller) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: That looks good. 

If there isn't another test that checks this, we'll need a new test that checks this logic in the 24hFormat case.  Not to prove that your change is correct (looks fine to me) but to defend against some future change introducing a regression.

**Review by HansMuller — APPROVED** [review]

**Review by HansMuller — APPROVED** [review]
Thanks for sticking with this!

LGTM. I will land the PR.

Once this PR has landed in the repo it will start running the final testing gauntlet. You can watch its status here: https://flutter-dashboard.appspot.com/build.html

**Comment by timtraversy** [comment]
Thanks for taking the time to review!
