### PR TITLE
Fix input mirroring in platform views when system language is RTL, and support is set in manifest.

### LINKED ISSUE #182823: [Android] PlatformView pointer events (tap & drag) are horizontally mirrored in RTL mode
### Steps to reproduce

[rtl_platform_view_gesture_demo.zip](https://github.com/user-attachments/files/25515921/rtl_platform_view_gesture_demo.zip)
 
1. Set the Android system language to an RTL language (e.g., Arabic).
2. Ensure android:supportsRtl="true" is set in AndroidManifest.xml.
3. Run the provided reproduction sample.
4. Click "click blue" area.
5. Try to drag or scroll the view from the blue area and observe the movement.

### Expected results

1. Click "click blue" area should display "click blue"
2. Dragging should move the content according to the finger's actual position.

### Actual results

1. The SnackBar displays "click red" (or the action associated with the mirrored horizontal position). This confirms that touch coordinates are being horizontally inverted before reaching the PlatformView.
2. Dragging is mirrored: Dragging on the mirrored position causes the WebView to move, confirming that the entire coordinate space is flipped.

### Code sample

<details open><summary>Code sample</summary>

```xml
<application
        android:label="rtl_platform_view_gesture_demo"
        android:name="${applicationName}"
        android:supportsRtl="true"
        android:icon="@mipmap/ic_launcher">
```

```dart
Row(
            mainAxisAlignment: .spaceAround,
            children: [
              SizedBox(
                width: 150,
                height: 150,
                child: Center(
                  child: InkWell(
                    onTap: () {
                      _showSnackBar('click blue');
                    },
                    child: Container(
                      width: 100,
                      height: 100,
                      color: Colors.blue,
                      child: const Center(
                        child: Text('click blue', style: TextStyle(color: Colors.white)),
                      ),
                    ),
                  ),
                ),
              ),
              Container(
                width: 150,
                height: 150,
                child: Stack(
                  children: [
                    Positioned.fill(child: WebViewWidget(controller: _controller)),
                    Center(
                      child: InkWell(
                        onTap: () {
                          _showSnackBar('click red');
                        },
                        child: Container(
                          width: 100,
                          height: 100,
                          alignment: AlignmentDirectional.center,
                          color: Colors.red,
                          child: Text('click red', style: TextStyle(color: Colors.white)),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/8283f1c0-ffab-442d-a244-2a5cf674a7aa)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.41.2, on macOS 15.6.1 24G90 darwin-arm64, locale zh-Hans-CN) [2.2s]
    • Flutter version 3.41.2 on channel stable at /Users/xq/fvm/versions/3.41.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90673a4eef (6 days ago), 2026-02-18 13:54:59 -0800
    • Engine revision 6c0baaebf7
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Flutter download mirror https://storage.flutter-io.cn
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [3.5s]
    • Android SDK at /Users/xq/Dev/SDK/Android/
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • ANDROID_HOME = /Users/xq/Dev/SDK/Android/
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 16.2) [3.4s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [6ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [6.3s]
    • sdk gphone16k arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)              • macos         • darwin-arm64   • macOS 15.6.1 24G90 darwin-arm64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 145.0.7632.75
    ! Device 1C27294610DA10TZ is not authorized.
      You might need to check your device for an authorization dialog.

[✓] Network resources [369ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

### PR DESCRIPTION
**Pull request by gmackall**
Fixes https://github.com/flutter/flutter/issues/182823

We use a [`FrameLayout`](https://developer.android.com/reference/android/widget/FrameLayout) to [wrap platform views](https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/mutatorsstack/FlutterMutatorView.java#L30). We construct new `FrameLayout.LayoutParams` and set them on the frame layout ([here](https://github.com/flutter/flutter/blob/758463261fabe1b37f2a4752bfc44a57e10c79b7/engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/mutatorsstack/FlutterMutatorView.java#L107), and a couple of other places). Because we don't specify a gravity, it defaults to [UNSPECIFIED_GRAVITY](https://developer.android.com/reference/android/widget/FrameLayout.LayoutParams#gravity), which is `Gravity.TOP | Gravity.START`. When a developer indicates that their app supports RTL (right-to-left) layouts (e.g. arabic), and the system language is set to one with an RTL layout, START becomes right https://developer.android.com/reference/android/view/Gravity#getAbsoluteGravity(int,%20int), and the view ends up thinking it is positioned relative to the right of the screen, even though we are controlling the drawing and putting it on the left.

Because we are handling the drawing, and all that matters is that flutter knows where the view is, we can just statically set the horizontal gravity to be left. Then flutter knows where to find the view and deliver the tap to it, whether we are in an RTL or LTR layout.

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java [hunk 1]
```diff
@@ -389,6 +391,10 @@ public void resize(
           final ViewGroup.LayoutParams viewWrapperLayoutParams = viewWrapper.getLayoutParams();
           viewWrapperLayoutParams.width = physicalWidth;
           viewWrapperLayoutParams.height = physicalHeight;
+          if (viewWrapperLayoutParams instanceof FrameLayout.LayoutParams) {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java:394]: This is kind of weird: the call to `FrameLayout.getLayoutParams` above returns a `ViewGroup.LayoutParams`, not a `FrameLayout.LayoutParams`. Then we immediately call our own `setLayoutParams` implementation:
https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewWrapper.java#L87
which takes a `FrameLayout.LayoutParams`, so we are always doing this cast which I am checking for. I could alternatively put this in the `setLayoutParams` method, but I'd prefer to keep the layout parameter configuration here in one place. But I acknowledge it looks weird... in my defense it's weird that android gives back a `ViewGroup.LayoutParams` in the first place...

File: dev/integration_tests/android_engine_test/test_driver/hcpp/rtl_mirror_main_test.dart [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+    nativeDriver = await AndroidNativeDriver.connect(flutterDriver);
+    await flutterDriver.waitUntilFirstFrameRasterized();
+  });
+
+  tearDownAll(() async {
+    await nativeDriver.close();
+    await flutterDriver.close();
+  });
+
+  test(
```
Comment (gmackall) [inline dev/integration_tests/android_engine_test/test_driver/hcpp/rtl_mirror_main_test.dart:26]: Neither taps delivered by `flutterDriver` or the `nativeDriver` extension repro the issue. Instead, this test requests the location of the blue box via flutter driver, and also requests pixel information, to calculate the location of the box and deliver a tab via adb to those physical coordinates.

File: dev/integration_tests/android_engine_test/lib/hcpp/rtl_mirror_main.dart [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+        // Blue Box (Flutter)
+        // In RTL, Row adds children from Right to Left.
+        // So this first child will be on the RIGHT.
+        InkWell(
+          key: const ValueKey('blue_box'),
+          onTap: () {
+            setState(() {
+              blueTapped = true;
+              _showSnackBar(context, 'click blue');
+            });
```
[the remark this answers is not in the document]
Comment (gmackall) [reply dev/integration_tests/android_engine_test/lib/hcpp/rtl_mirror_main.dart:74]: thanks gem I forgot to push the deletion

**Review by reidbaker — APPROVED** [review]
