### PR TITLE
Check for watch companion in build settings

### LINKED ISSUE #92294: Flutter build error after adding WatchOS target in Xcode Project
After adding watch Extention in ios/Runner.xcworkspace flutter run fails with below build error

### Steps to reproduce 

1. `flutter create watch_test`
2. `cd watch_test` & `flutter run` - App successfully launches in iOS simulator
3. Now open ios/Runner.xcworkspace and add new target as watch app extension for iOS app
4. `flutter run` will give error 

### Error log
note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    warning: duplicate output file '' on task: RegisterExecutionPolicyException /Users/raeeskattali/Downloads/w_test2/build/ios/Debug-iphonesimulator (in
    target 'watch' from project 'Runner

### Other details

- Tried on both stable & master branch
- WatchOS targets Supported Platforms is watchOS & Build Active Arch only YES
- Trying from M1 Macbook

Screen Shot 2021-10-21 at 4 53 27 PM

### PR DESCRIPTION
**Pull request by vashworth**
Add an additional check for watch companion by checking build settings of different schemes.

Fixes https://github.com/flutter/flutter/issues/92294.

Re-land of https://github.com/flutter/flutter/pull/113956.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart [hunk 1]
```diff
@@ -39,11 +39,9 @@ Future<void> main() async {
...
           options: <String>['ios', '--no-codesign', '--release', '--verbose'],
         );
-        if (!buildOutput.contains('Watch companion app found')) {
-          throw TaskResult.failure('Did not detect watch companion');
-        }
-        if (buildOutput.contains('-sdk iphoneos -destination')) {
-          throw TaskResult.failure('-sdk must be omitted for app with watch companion');
+        if (!buildOutput.contains('-destination generic/platform=watchOS')) {
+          print(buildOutput);
+          throw TaskResult.failure('Did not try to get watch build settings');
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:44]: I think you also need to delete the rest of this test, because the build won't actually succeed the `Runner.app` files won't exist.

Comment (vashworth) [reply dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:41]: Fixed in https://github.com/flutter/flutter/pull/114078/commits/df3951741ef47c486a7be950099153004e857c5c.

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart [hunk 2]
```diff
@@ -28,50 +27,21 @@ Future<void> main() async {
...
-        'Frameworks',
-        'Flutter.framework',
-        'Flutter',
-      );
-
-      checkDirectoryExists(appBundle);
-      await _checkFlutterFrameworkArchs(appFrameworkPath);
-      await _checkFlutterFrameworkArchs(flutterFrameworkPath);
-
       section('Clean build');
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:45]: Nit: this `clean` was pretty useless even before since the directory is removed right after this.  Can you remove it as well?

**Review by jmagman — COMMENTED** [review]
You should also add a note in the description that this is a re-land of https://github.com/flutter/flutter/pull/113956 so we can follow the GitHub paper trail in the future.

I'm not on my machine that's missing watch simulators today to test this.  How about removing `presubmit: false` from these tests:
https://github.com/flutter/flutter/blob/156c313219a21ac97ff84fe76743c35463ef0fdb/.ci.yaml#L3493-L3509

and then we'll see if the tests pass on this PR.  And if they do, you can revert that change since we rarely change this behavior and don't really need to run it on every PR.

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart (hunk 2 above)
Comment (vashworth) [reply dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart]: Removed in https://github.com/flutter/flutter/pull/114078/commits/da87b9eadf57dcacd0609165e52ab450bafcbdc6.

**Review by jmagman — APPROVED** [review]
This looks good.  Add the `bringup` key to .ci.yaml as suggested so we don't break the tree again, then we'll merge!

**Comment by jmagman** [comment]
> This looks good. Add the `bringup` key to .ci.yaml as suggested so we don't break the tree again, then we'll merge!

Correction: I meant remove `presubmit: false` https://github.com/flutter/flutter/pull/114078#pullrequestreview-1157380856

**Review by jmagman — APPROVED** [review]
Ah you already did this, and they passed.
https://ci.chromium.org/p/flutter/builders/try/Mac_arm64_ios%20ios_app_with_extensions_test/1
https://ci.chromium.org/p/flutter/builders/try/Mac_ios%20ios_app_with_extensions_test/1

LGTM!
