### PR TITLE
[ Tool ] Support Powershell v6+ to determine Windows version in `flutter doctor`

### LINKED ISSUE #156189: ProcessException: Failed to find "powershell" in the search path.         Command: powershell
### Steps to reproduce

flutter doctor -v

### Actual results

I get told:
```
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:87:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:674:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:673:12)
      #4      ProcessLister.getProcessesWithPath
      (package:flutter_tools/src/windows/windows_version_validator.dart:111:27)
      #5      WindowsVersionValidator._topazScan
      (package:flutter_tools/src/windows/windows_version_validator.dart:40:69)
      #6      WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:81:15)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:247:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1826:10)
      #12     runZonedGuarded (dart:async/zone.dart:1814:12)
      #13     runZoned (dart:async/zone.dart:1760:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:239:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:371:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>
```
      
     I think the problem is that powershell v7, the current version, has the main exe file as pwsh.exe, not powershell.exe

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
PS C:\Users\shawn\OneDrive\Documents\RWAFlutter\ridewealth_assistant> $env:PATH = "C:\Program Files\PowerShell\7;$env:PATH"; flutter doctor -v
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Users\shawn\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:87:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:674:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:673:12)
      #4      ProcessLister.getProcessesWithPath
      (package:flutter_tools/src/windows/windows_version_validator.dart:111:27)
      #5      WindowsVersionValidator._topazScan
      (package:flutter_tools/src/windows/windows_version_validator.dart:40:69)
      #6      WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:81:15)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:247:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1826:10)
      #12     runZonedGuarded (dart:async/zone.dart:1814:12)
      #13     runZoned (dart:async/zone.dart:1760:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:239:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:371:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\shawn\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\shawn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13763.5

[√] VS Code (version 1.94.0)
    • VS Code at C:\Users\shawn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] VS Code, 64-bit edition (version 1.87.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by bkonyi**
Powershell v6+ use the executable name `pwsh.exe` instead of `powershell.exe`. This change adds support for determining the Windows version on systems that solely use `pwsh.exe` and don't have `powershell.exe` on the `PATH`. 

Fixes #156189.

### CODE REVIEW

File: packages/flutter_tools/lib/src/windows/windows_version_validator.dart [hunk 1]
```diff
@@ -108,6 +108,11 @@ class ProcessLister {
 
   Future<ProcessResult> getProcessesWithPath() async {
     const String argument = 'Get-Process | Format-List Path';
-    return processManager.run(<String>['powershell', '-command', argument]);
+    const List<String> psArgs = <String>['-command', argument];
+    try {
+      return await processManager.run(<String>['powershell', ...psArgs]);
+    } on ProcessPackageExecutableNotFoundException {
+      return processManager.run(<String>['pwsh', ...psArgs]);
+    }
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/windows/windows_version_validator.dart:116]: This LGTM as-is, but I think there is a world where we can detect that powershell is unavailable (via `ProcessManager.canRun`) and then make the validator fail with a `ValidationResult.missing` that has a more specific message rather than throwing an exception on relying on higher-level error handling. (This is just an FYI; my hope is that this knowledge is useful for future work on validators).

However, this kind of situation is unlikely to happen again very often, and the error message generated in that case is still sufficient to figure out what's going wrong here—hence the LGTM.

File: packages/flutter_tools/test/general.shard/windows_version_validator_test.dart [hunk 2]
```diff
@@ -169,4 +171,75 @@ OS 版本:          10.0.22621 暂缺 Build 22621
...
+            stdout: 'pwsh',
+          ),
+        ],
+      ),
+    );
+
+    try {
+      final ProcessResult result = await processLister.getProcessesWithPath();
+      expect(result.stdout, 'pwsh');
+    // ignore: avoid_catches_without_on_clauses
```
Comment (andrewkolos) [inline packages/flutter_tools/test/general.shard/windows_version_validator_test.dart:203]: Is this line necessary?

File: packages/flutter_tools/test/general.shard/windows_version_validator_test.dart [hunk 3]
```diff
@@ -169,4 +171,75 @@ OS 版本:          10.0.22621 暂缺 Build 22621
...
+        ],
+      ),
+    );
+
+    try {
+      final ProcessResult result = await processLister.getProcessesWithPath();
+      fail('Should have thrown, but successfully ran ${result.stdout}');
+    } on ProcessPackageExecutableNotFoundException {
+      // Expected
+    // ignore: avoid_catches_without_on_clauses
```
Comment (andrewkolos) [inline packages/flutter_tools/test/general.shard/windows_version_validator_test.dart:240]: Is this line necessary? `flutter analyze` passes without it.

**Review by andrewkolos — APPROVED** [review]
LGTM with nits

File: packages/flutter_tools/test/general.shard/windows_version_validator_test.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/windows_version_validator_test.dart:240]: Then again, the `Linux analyze` check is failing; so me running `flutter analyze` locally is apparently not sufficient 🤪

File: packages/flutter_tools/lib/src/windows/windows_version_validator.dart (hunk 1 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/windows/windows_version_validator.dart]: That's a great point! I definitely just skipped past all the validation logic at the top of the file... :)

I've gone ahead and added a validation step and made more use of `ProcessManager.canRun` rather than attempting to run executables to determine whether or not they exist.

File: packages/flutter_tools/lib/src/windows/windows_version_validator.dart [hunk 4]
```diff
@@ -106,8 +119,22 @@ class ProcessLister {
...
     const String argument = 'Get-Process | Format-List Path';
-    return processManager.run(<String>['powershell', '-command', argument]);
+    const List<String> psArgs = <String>['-command', argument];
+    if (processManager.canRun(powershell)) {
+      return processManager.run(<String>[powershell, ...psArgs]);
+    }
+    if (processManager.canRun(pwsh)) {
+      return processManager.run(<String>[pwsh, ...psArgs]);
+    }
+    throw StateError('Failed to find $powershell or $pwsh on PATH!');
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/windows/windows_version_validator.dart:138]: Unless `!` is some notation I am not aware of, we shouldn't yell at the user (per the style guide, IIRC)

```suggestion
    throw StateError('Failed to find $powershell or $pwsh on PATH');
```

**Comment by andrewkolos** [comment]
LGTM
