### PR TITLE
Fix `fooTheme.of(context);` usage docs

### LINKED ISSUE #98401: Fix `fooTheme.of(context);` usage docs
Theme doc usage for some widgets has an incorrect return type.

### Actual Results
https://github.com/flutter/flutter/blob/19586569438afdc52fcc0ab7d95edeeb7a2d961f/packages/flutter/lib/src/material/text_button_theme.dart#L110

The following error is thrown:
`A value of type 'TextButtonThemeData' can't be assigned to a variable of type 'TextButtonTheme'.`

### Expected Results;
`   /// TextButtonThemeData theme = TextButtonTheme.of(context); `

### For referemce
https://github.com/flutter/flutter/blob/19586569438afdc52fcc0ab7d95edeeb7a2d961f/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart#L293

I've found the following widget theme docs have this issue problem
- `TextButtonTheme`
- `ElevatedButtonTheme`
- `OutlinedButtonTheme`
- `DrawerTheme`
- `NavigationBarTheme`
- `NavigationRailTheme`

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/98401

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/text_button_theme.dart [hunk 1]
```diff
@@ -107,7 +107,7 @@ class TextButtonTheme extends InheritedTheme {
   /// Typical usage is as follows:
   ///
   /// ```dart
-  /// TextButtonTheme theme = TextButtonTheme.of(context);
+  /// TextButtonThemData theme = TextButtonTheme.of(context);
```
Comment (r-mzy47) [inline packages/flutter/lib/src/material/text_button_theme.dart:110]: TextButtonThemeData

Comment (TahaTesser) [reply packages/flutter/lib/src/material/text_button_theme.dart]: Thanks!

**Review by HansMuller — APPROVED** [review]
LGTM - nice catch!
