### PR TITLE
fix a BottomSheet nullable issue

### LINKED ISSUE #89168: BottomSheet class has enableDrag default to true, but doesn't enforce assigning an AnimationController
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

Replace the `_incrementCounter()` method with

```[dart]
void _incrementCounter() {
    showModalBottomSheet(
        context: context,
        builder: (_) {
          return BottomSheet(
              onClosing: () {},
              builder: (_) => Container(
                    height: 200,
                    color: Colors.red,
                  ));
        });
  }
```

3. Run the app, click the FAB, perform a drag gesture on the appearing sheet. Console logs exceptions, caused by a call to `widget.animationController!` in the bottom sheet code even though there is no such controller.

Controller assignment should either be enforced by asserts and documented, or the `_dismissUnderway` getter should use a `?` null check instead of `!` requirement.

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _BottomSheetState._dismissUnderway (package:flutter/src/material/bottom_sheet.dart:193:58)
#1      _BottomSheetState._handleDragEnd (package:flutter/src/material/bottom_sheet.dart:208:9)
#2      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:473:47)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:473:5)
...
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#d2597
  debugOwner: GestureDetector
  start behavior: start
====================================================================================================
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\_\AppData\Local\Android\Sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\_\AppData\Local\Android\Sdk\
    • ANDROID_SDK_ROOT = C:\Users\_\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fix #89168

Do not crash when using BottomSheet directly although it is rarely used directly.

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 1]
```diff
@@ -216,14 +216,14 @@ class _BottomSheetState extends State<BottomSheet> {
 
   void _handleDragUpdate(DragUpdateDetails details) {
     assert(widget.enableDrag);
-    if (_dismissUnderway)
+    if (widget.animationController == null || _dismissUnderway)
```
Comment (Piinks) [inline packages/flutter/lib/src/material/bottom_sheet.dart:219]: I think we should also check against `BottomSheet.enableDrag` here. If that is true then it is broken by this change since the drag to dismiss will not work.

**Review by Piinks — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/bottom_sheet.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/bottom_sheet.dart:219]: enableDrag can't work well with null-controller. 

In fact, it is rarely used this widget directly, this patch just to avoid crashing.

Comment (Piinks) [reply packages/flutter/lib/src/material/bottom_sheet.dart:219]: True, it just swallows an error though that the developer should know about. If `enableDrag` is true, but the animation controller is not set, it should probably assert. Otherwise the drag functionality is broken and the developer won't even know it.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/bottom_sheet.dart:219]: That's right. I think some documents may also be needed here to explain the working mechanism of enableDrag.

If we use this widget directly and even we give a controller to it, the drag-to-dismiss isn't work!

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 2]
```diff
@@ -23,6 +23,26 @@ void main() {
     expect(dyDelta1, isNot(moreOrLessEquals(dyDelta2, epsilon: 0.1)));
   }
 
+  testWidgets('Do not crash when using BottomSheet directly', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/89168
+    await tester.pumpWidget(
+      MaterialApp(
+        home: BottomSheet(
```
Comment (xu-baolin) [inline packages/flutter/test/material/bottom_sheet_test.dart:30]: For this case, an assertion seems to be more breaking, right?

Comment (xu-baolin) [reply packages/flutter/test/material/bottom_sheet_test.dart:30]: Make sense, let's have a try. Hope it won't break things. This means that we do not support using this widget alone now(updating docs?). In fact, the function is also abnormal when using directly.

Comment (Piinks) [reply packages/flutter/test/material/bottom_sheet_test.dart:30]: I think it is ok to use alone, you just need to provide an animation controller in that case.  There is a static method fo creating one, `BottomSheet.createAnimationController`. The assertion could provide an error message that says something like that.

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 3]
```diff
@@ -215,14 +215,22 @@ class _BottomSheetState extends State<BottomSheet> {
   }
 
   void _handleDragUpdate(DragUpdateDetails details) {
-    assert(widget.enableDrag);
+    assert(
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/bottom_sheet.dart:218]: If I move this assertion to the 'BottomSheet''s constructor, it will break some tests.

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 4]
```diff
@@ -215,14 +215,22 @@ class _BottomSheetState extends State<BottomSheet> {
...
+      widget.enableDrag && widget.animationController != null,
+      "'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. "
+      "Use 'BottomSheet.createAnimationController' for creating one.",
```
Comment (Piinks) [inline packages/flutter/lib/src/material/bottom_sheet.dart:221]:
```suggestion
      "Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.",
```

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 5]
```diff
@@ -215,14 +215,22 @@ class _BottomSheetState extends State<BottomSheet> {
...
       return;
     widget.animationController!.value -= details.primaryDelta! / _childHeight;
   }
 
   void _handleDragEnd(DragEndDetails details) {
-    assert(widget.enableDrag);
+    assert(
+      widget.enableDrag && widget.animationController != null,
+      "'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. "
+      "Use 'BottomSheet.createAnimationController' for creating one.",
```
Comment (Piinks) [inline packages/flutter/lib/src/material/bottom_sheet.dart:232]: Same here

**Review by Piinks — APPROVED** [review]
LGTM with just a tweak to the error message. Thank you!

**Comment by xu-baolin** [comment]
> Filed https://github.com/flutter/flutter/issues/91576

Thanks:)
