### PR TITLE
showOnScreen doesn't trigger scroll if item is already fully on screen

### LINKED ISSUE #11663: showOnScreen / getOffsetToReveal doesn't take status bar into consideration
This is a problem for a11y. When an item is partly covered by the status bar and a11y focus is moved to it, Android issues a showOnScreen action, which is handled by [1]. It will currently calculate via [2] that the item needs to be aligned with the upper edge of the screen. This is incorrect. It should be aligned with the lower edge of the status bar. 

While this sounds like just a visual annoyance, it can actually cause a11y users to get stuck: When the list is scrolled all the way to the bottom, the showOnScreen action should scroll it down a little. Instead, we currently try to scroll up, but that's not possible as we are already at the end. The user needs to resort to two finger scrolling to get out of this situation. 

[1] https://github.com/flutter/flutter/blob/8f56f6fdd1c6b4586518b927623bc87341452b50/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L431
[2] https://github.com/flutter/flutter/blob/8f56f6fdd1c6b4586518b927623bc87341452b50/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L390

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/11663.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 1]
```diff
@@ -786,19 +786,17 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
...
-      // TODO(goderbauer): Don't scroll if it is already visible.
-      // TODO(goderbauer): Don't guess if we need to align at leading or trailing edge.
-      // Move viewport the smallest distance to bring [child] on screen.
       final double leadingEdgeOffset = getOffsetToReveal(child, 0.0);
       final double trailingEdgeOffset = getOffsetToReveal(child, 1.0);
       final double currentOffset = offset.pixels;
-      // TODO(goderbauer): Don't scroll if that puts us outside of viewport's bounds.
-      if ((currentOffset - leadingEdgeOffset).abs() < (currentOffset - trailingEdgeOffset).abs()) {
+
+      if (currentOffset > leadingEdgeOffset && currentOffset > trailingEdgeOffset) {
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/viewport.dart]: can you assert `leadingEdgeOffset <= trailingEdgeOffset`?

File: packages/flutter/lib/src/widgets/single_child_scroll_view.dart [hunk 2]
```diff
@@ -588,13 +588,13 @@ class _RenderSingleChildViewport extends RenderBox with RenderObjectWithChildMix
...
       final double leadingEdgeOffset = getOffsetToReveal(child, 0.0);
       final double trailingEdgeOffset = getOffsetToReveal(child, 1.0);
       final double currentOffset = offset.pixels;
-      if ((currentOffset - leadingEdgeOffset).abs() < (currentOffset - trailingEdgeOffset).abs()) {
+
+      if (currentOffset > leadingEdgeOffset && currentOffset > trailingEdgeOffset) {
         offset.jumpTo(leadingEdgeOffset);
-      } else {
+      } else if (currentOffset < leadingEdgeOffset && currentOffset < trailingEdgeOffset ) {
         offset.jumpTo(trailingEdgeOffset);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/single_child_scroll_view.dart]: any chance we can factor the common code into the base class?

File: packages/flutter/test/widgets/scrollable_semantics_test.dart [hunk 3]
```diff
@@ -399,6 +387,135 @@ void main() {
...
+    expect(scrollController.offset, kItemHeight / 2);
+
+    final int firstContainerId = tester.renderObject(find.byWidget(children[1])).debugSemantics.id;
+    tester.binding.pipelineOwner.semanticsOwner.performAction(firstContainerId, SemanticsAction.showOnScreen);
+    await tester.pumpAndSettle();
+
+    expect(scrollController.offset, kItemHeight / 2);
+
+    semantics.dispose();
+  });
```
Comment (Hixie) [inline packages/flutter/test/widgets/scrollable_semantics_test.dart]: we should test that this works with negative-scroll-offset children too

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/viewport.dart]: No, but I can guarantee it the other way around: `leadingEdgeOffset >= trailingEdgeOffset` :)

File: packages/flutter/lib/src/widgets/single_child_scroll_view.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/single_child_scroll_view.dart]: I've looked into doing that before and there is no good common ancestor for this...

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/viewport.dart]: (really? that's surprising)

in that case, assert that then simplify the expressions

File: packages/flutter/lib/src/widgets/single_child_scroll_view.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/single_child_scroll_view.dart]: create a common mixin (`RenderViewportShowOnScreenMixin`) or make a static method on some class (`RenderViewportBase.showChildInViewport` or some such) and use that.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/viewport.dart]: To get a list item to the leading edge (as opposed to the trailing edge) you have to scroll further, therefore `leadingEdgeOffset >= trailingEdgeOffset`, no?

Will simplify expression.

File: packages/flutter/lib/src/widgets/single_child_scroll_view.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/single_child_scroll_view.dart]: Mixin doesn't work (or gets awkward because of the super call in the method. I changed it to a static method.

File: packages/flutter/test/widgets/scrollable_semantics_test.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/scrollable_semantics_test.dart]: Good idea. Added.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/viewport.dart]: In a regular vertically scrolling list, the leading edge is above the trailing edge, so you get it first (lower scroll offset) than the trailing edge (higher scroll offset) unless I'm missing something?

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/viewport.dart]: To ensure that we talk about the same thing I have drawn up two diagrams: Both show a long scrollable list (on the left) that scrolls through the viewport window (on the right in yellow). 

In the first picture, the list item in question is shown at the leading edge of the viewport. I'd argue that the scrollOffset here is 600, which is called the `leadingEdgeOffset` in the code.

img-1935

Now, let's move the list item in question to the trailing edge of the viewport. I'd argue that in this picture the scrollOffset is 350, which is called the `trailingEdgeOffset` in the code.

img-1937

So, now I would argue that 600 > 350. And therefore (even though this is by now means a full mathematically proof), it seems that `leadingEdgeOffset >= trailingEdgeOffset` holds.

Comment (Hixie) [reply packages/flutter/lib/src/rendering/viewport.dart]: ah, yup, i was missing something. :-)

**Comment by Hixie** [comment]
LGTM
