### PR TITLE
Fix the first frame logic in tracing and driver

### LINKED ISSUE #31442: flutter driver tests need to know when the GPU thread finishes rendering the first frame
So we can trace the correct performance (first frame latency, worst frame after the first frame), and do the correct screenshot of the first frame.

Previously, it only knows the event when the UI thread finished preparing the first frame. That made us measure the wrong performance metrics, and take the wrong screenshots ([blank screens instead of the first frame](https://github.com/flutter/flutter/pull/30463)).

In order to implement this, we'll need to let UI thread and GPU thread communicate through VMService. Currently flutter_tools package has a VMService that flutter_drive could use but flutter_drive can't depend on flutter_tools. Hence we'll do a big yak shave to extract that VMService and put it in a common package that can be used by both flutter_tools and flutter_drive.

### PR DESCRIPTION
**Pull request by liyuqian**
This should fix https://github.com/flutter/flutter/issues/31442 and https://github.com/flutter/flutter/issues/34867

### CODE REVIEW

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -695,6 +702,24 @@ mixin WidgetsBinding on BindingBase, SchedulerBinding, GestureBinding, RendererB
...
     }());
+
+    if (_needToReportFirstFrame && _reportFirstFrame) {
+      assert(!_firstFrameCompleter.isCompleted);
+      // TODO(liyuqian): use a broadcast stream approach
+      final TimingsCallback oldCallback = WidgetsBinding.instance.window.onReportTimings;
+      WidgetsBinding.instance.window.onReportTimings = (List<FrameTiming> timings) {
+        if (!kReleaseMode) {
+          developer.Timeline.instantSync('Rasterized first useful frame');
+          developer.postEvent('Flutter.FirstFrame', <String, dynamic>{});
```
Comment (gaaclarke) [inline packages/flutter/lib/src/widgets/binding.dart]: Is this happening after the frame has been presented or rasterized?  The language of this PR is talking about rasterization but what I found out is that what I was really interested in is not when the frame was rasterized but when it was presented, which is a subtle difference.

**Review by gaaclarke — COMMENTED** [review]
I'm not familiar with the profiling code but it LGTM except for my comment.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 1 above)
Comment (liyuqian) [reply packages/flutter/lib/src/widgets/binding.dart]: I'll revise the language to make it clear that:
1. We're only waiting for rasterization
2. Usually, the time that a frame is rasterized is very close to the time that it gets presented. Specifically, rasterization is the last expensive phase of a frame that's still in Flutter's control.

**Comment by liyuqian** [comment]
Ping @Hixie and @goderbauer

File: dev/devicelab/manifest.yaml [hunk 2]
```diff
@@ -236,6 +236,7 @@ tasks:
     description: >
       Measures the startup time of the Complex Layout sample app on Android.
     stage: devicelab
+    flaky: true
```
Comment (goderbauer) [inline dev/devicelab/manifest.yaml]: Why mark so many as flaky? Isn't this just changing the behavior of only the transition test for now?

File: packages/flutter/lib/src/widgets/binding.dart [hunk 3]
```diff
@@ -695,6 +703,24 @@ mixin WidgetsBinding on BindingBase, SchedulerBinding, GestureBinding, RendererB
       debugBuildingDirtyElements = true;
       return true;
     }());
+
+    if (_needToReportFirstFrame && _reportFirstFrame) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/binding.dart]: Is there value in doing all of this in release mode? Or should this be guarded to only profile and debug mode?

**Review by goderbauer — COMMENTED** [review]
I don't have all the context to properly review this, maybe @Hixie can also take a look?

File: dev/devicelab/manifest.yaml (hunk 2 above)
Comment (liyuqian) [reply dev/devicelab/manifest.yaml]: Although this test doesn't wait for the first frame, the way that we measure the `start_up` time changes. Hence I marked all `start_up` tests to be flaky.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 3 above)
Comment (liyuqian) [reply packages/flutter/lib/src/widgets/binding.dart]: I added this to release mode so `_firstFrameCompleter` and thus `WidgetsBinding.firstFrameRasterized` is available in the release mode. It might be useful to handle the splash screen during add2app?

**Comment by liyuqian** [comment]
@goderbauer : do my answers solve your concerns?

**Review by dnfield — APPROVED** [review]
LGTM.

I'm hoping we can pretty quickly determine if this test actually causes flakes or not and either revert or mark as not flaky.

**Comment by liyuqian** [comment]
Adding @jonahwilliams as the reviewer as rebasing the PR to the head of master triggers the tool codecov tests.

Ping @goderbauer for the overall review. If there's no objection, I'll land this soon to start measuring our first frame latency correctly.

**Comment by dnfield** [comment]
You can ignore the codecov bot - it's not quite working.

**Comment by jonahwilliams** [comment]
It is correct in that the tools code here is not covered by tests. I think we've decided that its not the responsibility on contributors making small changes to rewrite the tools to be testable

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
For posterity, this was reverted because it was breaking Flutter devicelab tests

**Comment by Hixie** [comment]
@liyuqian Can we mark the previously existing tests non-flaky again and/or revert this PR? We can't be having these critical benchmarks be considered ok-to-break.

**Comment by liyuqian** [comment]
@Hixie : please see https://github.com/flutter/flutter/pull/37192#issuecomment-524665479
