### PR TITLE
Make AndroidView take gesture recognizer factories.

### LINKED ISSUE #21514: AndroidView crashes trying to re-set a gesture recognizer's team
When an AndroidView is rebuilt, and is handed the same gestureRecognizer instance it was handed on the previous build, it will try to re-set the gesture recognizer's team field, which fails an assertion and crashes.

Repro test case (can be run as part of widgets/platform_view_test.dart):
```dart
  testWidgets('AndroidView rebuilt with same gestureRecognizers', (WidgetTester tester) async {
    final FakePlatformViewsController viewsController = new FakePlatformViewsController(TargetPlatform.android);
    viewsController.registerViewType('webview');

    final AndroidView androidView = AndroidView(
      viewType: 'webview',
      gestureRecognizers: <OneSequenceGestureRecognizer>[ new EagerGestureRecognizer() ],
      layoutDirection: TextDirection.ltr,
    );

    await tester.pumpWidget(androidView);
    await tester.pumpWidget(const SizedBox.shrink());
    await tester.pumpWidget(androidView);
  });
```

This crashes with:
```
The following assertion was thrown building AndroidView(state: _AndroidViewState#e73f5):
'package:flutter/src/gestures/recognizer.dart': Failed assertion: line 196 pos 12: '_team == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      OneSequenceGestureRecognizer.team= (package:flutter/src/gestures/recognizer.dart:196:12)
#3      _AndroidViewGestureRecognizer.gestureRecognizers= (package:flutter/src/rendering/platform_view.dart:238:18)
#4      new _AndroidViewGestureRecognizer (package:flutter/src/rendering/platform_view.dart:213:10)
#5      RenderAndroidView.gestureRecognizers= (package:flutter/src/rendering/platform_view.dart:105:30)
#6      new RenderAndroidView (package:flutter/src/rendering/platform_view.dart:69:10)
#7      _AndroidPlatformView.createRenderObject (package:flutter/src/widgets/platform_view.dart:250:11)
#8      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4288:28)
...
```

I'm not sure what was the reason to forbid re-setting a `OneSequenceGestureRecognizer`'s team I would think it should be possible as long as the previous team is not currently participating in an arena. (@Hixie do you happen to know if there's some other reason to forbid changing a gesture recognizer's team I'm overlooking?)

### PR DESCRIPTION
**Pull request by amirh**
Before this PR AndroidView's gestureRecognizers field was a list of
gesture recognizers. This was problematic as when the widget was rebuilt
with the same gesture recognizer instances we would try to re-join the
recognizers to a gesture arena team and crash (as a OneSeqeunceGestureRecognizer
team can only be set once).

With this change, we instead take a set of factories.
This allows AndroidView to create the gesture recognizers just before
adding them to the team, and thus be sure that they are only added once to a
team.

The factories are identified by the type of the object they create, this
allows AndroidView to know when it is given an equivalent set of gesture
recognizer factories, and do nothing in that case.

Fixes #21514.

### CODE REVIEW

**Comment by amirh** [comment]
Matching changes to maps and webview in flutter/plugins#778

File: packages/flutter/lib/src/foundation/basic_types.dart [hunk 1]
```diff
@@ -280,3 +280,37 @@ class _LazyListIterator<E> implements Iterator<E> {
...
+/// A factory interface, that also reports the type of the created objects.
+///
+/// The equality of [Factory] object is determined solely by [Factory.type].
+class Factory<T> {
+  /// Creates a new factory.
+  ///
+  /// If `type` is null, [Factory.type] returns [T], else it returns `type`.
+  ///
+  /// The `constructor` parameter must not be null.
+  const Factory(this.constructor, {Type type})
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/basic_types.dart]: I'm concerned about the `type` argument, especially because (as far as I can tell) we have no way to verify that it's correct. When I saw this API, I thought "that's going to be a recipe for bugs", then I searched for "type:", and the first example in this PR is, as far as I can tell, an example of a bug.

I don't really understand why we need to override the `type` though? Isn't a `Factory< VerticalDragGestureRecognizer>` a subclass of `Factory<OneSequenceGestureRecognizer>` and thus capable of being put in the same `List<Factory<OneSequenceGestureRecognizer>>` list?

File: packages/flutter/lib/src/foundation/basic_types.dart [hunk 2]
```diff
@@ -280,3 +280,37 @@ class _LazyListIterator<E> implements Iterator<E> {
...
+      : assert(constructor != null),
+        _type = type;
+
+  /// Creates a new object of type T.
+  final ValueGetter<T> constructor;
+
+  final Type _type;
+  /// The type of the objects created by this factory.
+  Type get type => _type ?? T;
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/basic_types.dart]: nit: if we do keep this, the field should come after the getter

File: packages/flutter/lib/src/foundation/basic_types.dart [hunk 3]
```diff
@@ -280,3 +280,37 @@ class _LazyListIterator<E> implements Iterator<E> {
...
+
+  @override
+  bool operator ==(Object other) {
+    if (other is! Factory<T>) {
+      return false;
+    }
+    final Factory<T> typedOther = other;
+    return type == typedOther.type;
+  }
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/basic_types.dart]: it seems weird that two factories with different constructor would be `==`. Maybe have a separate method that compares factories for equivalence?

Comment (Hixie) [reply packages/flutter/lib/src/foundation/basic_types.dart]: (oh but i guess you need this so that they match in a set?)

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 4]
```diff
@@ -61,14 +61,14 @@ class RenderAndroidView extends RenderBox {
...
-    List<OneSequenceGestureRecognizer> gestureRecognizers = const <OneSequenceGestureRecognizer> [],
+    @required Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers,
   }) : assert(viewController != null),
        assert(hitTestBehavior != null),
        assert(gestureRecognizers != null),
        _viewController = viewController
   {
     _motionEventsDispatcher = new _MotionEventsDispatcher(globalToLocal, viewController);
-    this.gestureRecognizers = gestureRecognizers;
+    this.gestureRecognizers = gestureRecognizers ?? new Set<Factory<OneSequenceGestureRecognizer>>();
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: assuming you never mutate this set, i recommend using a static private so you can always point to the same default empty instance.

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 5]
```diff
@@ -94,13 +94,13 @@ class RenderAndroidView extends RenderBox {
...
   /// Which gestures should be forwarded to the Android view.
   ///
-  /// The gesture recognizers on this list participate in the gesture arena for each pointer
-  /// that was put down on the render box. If any of the recognizers on this list wins the
+  /// Gesture recognizers created by factories in this set participate in the gesture arena for each
+  /// pointer that was put down on the render box. If any of the recognizers on this list wins the
   /// gesture arena, the entire pointer event sequence starting from the pointer down event
   /// will be dispatched to the Android view.
-  set gestureRecognizers(List<OneSequenceGestureRecognizer> recognizers) {
+  set gestureRecognizers(Set<Factory<OneSequenceGestureRecognizer>> recognizers) {
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: the setter should be next to (immediately after) its field. Also, there should be a getter (never have a setter with no getter).

Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: I'd probably use `value` as the name of the parameter here, because it's confusing that "recognizers" is used to set "_gestureRecognizers".

Comment (Hixie) [reply packages/flutter/lib/src/rendering/platform_view.dart]: (as in, it's not immediately clear when reading the code which is the field and which is the incoming parameter)

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 6]
```diff
@@ -50,7 +50,7 @@ import 'framework.dart';
 class AndroidView extends StatefulWidget {
   /// Creates a widget that embeds an Android view.
   ///
-  /// The `viewType`, `hitTestBehavior`, and `gestureRecognizers` parameters must not be null.
+  /// The `viewType`, and `hitTestBehavior` parameters must not be null.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/platform_view.dart]: nit: first comma is now extraneous

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 7]
```diff
@@ -92,24 +91,26 @@ class AndroidView extends StatefulWidget {
...
   /// Which gestures should be forwarded to the Android view.
   ///
-  /// The gesture recognizers on this list participate in the gesture arena for each pointer
-  /// that was put down on the widget. If any of the recognizers on this list wins the
+  /// The gesture recognizers built by factories in this set participate in the gesture arena for
+  /// each pointer that was put down on the widget. If any of these recognizers win the
   /// gesture arena, the entire pointer event sequence starting from the pointer down event
   /// will be dispatched to the Android view.
   ///
+  /// When null an empty set of gesture recognizer factories is used, and a pointer event sequence
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/platform_view.dart]: strike "null"? or add "or"?

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 8]
```diff
@@ -92,24 +91,26 @@ class AndroidView extends StatefulWidget {
...
+  /// wil only be dispatched to the Android view if no other member of the arena claimed it.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/platform_view.dart]: wil -> will

also, this whole sentence makes no sense. maybe the "and" is extraneous?

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 9]
```diff
@@ -118,19 +119,25 @@ class AndroidView extends StatefulWidget {
   ///     height: 100.0,
   ///     child: AndroidView(
   ///       viewType: 'webview',
-  ///       gestureRecognizers: <OneSequenceGestureRecognizer>[ new VerticalDragGestureRecognizer() ],
+  ///       gestureRecognizers: <Factory<OneSequenceGestureRecognizer>> [
+  ///         new Factory<OneSequenceGestureRecognizer>(
+  ///           () => new EagerGestureRecognizer(),
+  ///           type: VerticalDragGestureRecognizer,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/platform_view.dart]: type doesn't match type returned by constructor

File: packages/flutter/test/widgets/platform_view_test.dart [hunk 10]
```diff
@@ -562,7 +563,12 @@ void main() {
             height: 100.0,
             child: AndroidView(
               viewType: 'webview',
-              gestureRecognizers: <OneSequenceGestureRecognizer> [new VerticalDragGestureRecognizer()],
+              gestureRecognizers: <Factory<OneSequenceGestureRecognizer>> [
+                new Factory<OneSequenceGestureRecognizer>(
+                  () => new VerticalDragGestureRecognizer(),
+                  type: VerticalDragGestureRecognizer,
```
Comment (Hixie) [inline packages/flutter/test/widgets/platform_view_test.dart]: if we could make the type argument be VerticalDragGestureRecognizer, then we wouldn't need to specify the type here.

File: packages/flutter/test/widgets/platform_view_test.dart [hunk 11]
```diff
@@ -705,4 +716,24 @@ void main() {
...
+  testWidgets('AndroidView rebuilt with same gestureRecognizers', (WidgetTester tester) async {
+    final FakePlatformViewsController viewsController = new FakePlatformViewsController(TargetPlatform.android);
+    viewsController.registerViewType('webview');
+
+    final AndroidView androidView = AndroidView(
+      viewType: 'webview',
+      gestureRecognizers: <Factory<OneSequenceGestureRecognizer>> [
+        new Factory<OneSequenceGestureRecognizer>(
+          () => new EagerGestureRecognizer(),
+          type: VerticalDragGestureRecognizer,
```
Comment (Hixie) [inline packages/flutter/test/widgets/platform_view_test.dart]: type doesn't match constructor.

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 6 above)
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: done

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 7 above)
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: Added a comma, does it make sense now?
(e.g when this is null, then an empty set is used)

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 8 above)
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: rephrased a bit, is it more clear now?

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 9 above)
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: removed type

File: packages/flutter/test/widgets/platform_view_test.dart (hunk 10 above)
Comment (amirh) [reply packages/flutter/test/widgets/platform_view_test.dart]: done

File: packages/flutter/test/widgets/platform_view_test.dart (hunk 11 above)
Comment (amirh) [reply packages/flutter/test/widgets/platform_view_test.dart]: removed type

**Review by amirh — COMMENTED** [review]
Thanks for the review, PTAL

File: packages/flutter/lib/src/foundation/basic_types.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/foundation/basic_types.dart]: this is a tough one, but i think the right call here is to use a map indexed by type, and to have the factories either not have a custom ==, or to have their custom == also compare the actual constructor.

I'm worried about the confusion that one day someone would have if they did:

```dart
  var a = Factory(() => 'a');
  var b = Factory(() => 'b');
  print(a == b); // true (!)
```

Comment (Hixie) [reply packages/flutter/lib/src/foundation/basic_types.dart]: ugh, but you really want it to be a set for the rest of the API...

Comment (Hixie) [reply packages/flutter/lib/src/foundation/basic_types.dart]: maybe the right solution here is to make this not be a general-purpose class and just have a class specific to this purpose, with a more specific name...

Comment (Hixie) [reply packages/flutter/lib/src/foundation/basic_types.dart]: or alternatively, still take a set, but then independently verify that the set only has one of each type, and match on type when the new set comes in?

**Comment by amirh** [comment]
Following offline discussion, removed the type based equality for factories, and added logic to compare the set of gesture recognizer types in the render object.

PTAL

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 12]
```diff
@@ -94,19 +97,43 @@ class RenderAndroidView extends RenderBox {
...
-    if (recognizers == _gestureRecognizer?.gestureRecognizers) {
+  ///
+  /// `gestureRecognizers` must not contain more than one factory with the same [Factory.type].
+  ///
+  /// Setting a new set of gesture recognizer factories with the same [Factory.type]s as the current
+  /// set is ignored.
+  ///
+  /// Setting a new set of gesture recognizer factories with different [Factory.type]s
+  /// (e.g `gestureRecognizers.map((f) => f.type).toSet()` is different, will reject any active
+  /// gesture arena.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: this last paragraph is confusing

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 13]
```diff
@@ -94,19 +97,43 @@ class RenderAndroidView extends RenderBox {
...
   /// gesture arena, the entire pointer event sequence starting from the pointer down event
   /// will be dispatched to the Android view.
-  set gestureRecognizers(List<OneSequenceGestureRecognizer> recognizers) {
-    assert(recognizers != null);
-    if (recognizers == _gestureRecognizer?.gestureRecognizers) {
+  ///
+  /// `gestureRecognizers` must not contain more than one factory with the same [Factory.type].
+  ///
+  /// Setting a new set of gesture recognizer factories with the same [Factory.type]s as the current
+  /// set is ignored.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: s/is ignored/has no effect, because the factories' constructors would have already been called with the previous set/.

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 14]
```diff
@@ -94,19 +97,43 @@ class RenderAndroidView extends RenderBox {
...
+      return true;
+    }
+    if (a == null ||  b == null) {
+      return false;
+    }
+    return setEquals(_factoriesTypeSet(a), _factoriesTypeSet(b));
+  }
+
+  static Set<Type> _factoriesTypeSet<T>(Set<Factory<T>> factories) =>
+      factories.map<Type>((Factory<T> factory) => factory.type).toSet();
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: i'm amused that you used => here (even though the whole thing doesn't fit on one line), but you used `{ }` for the Factory.toString method, even though that could easily fit on one line.

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 15]
```diff
@@ -211,8 +238,14 @@ class RenderAndroidView extends RenderBox {
...
-  _AndroidViewGestureRecognizer(this.dispatcher, List<OneSequenceGestureRecognizer> gestureRecognizers) {
-    this.gestureRecognizers = gestureRecognizers;
+  _AndroidViewGestureRecognizer(this.dispatcher, this.gestureRecognizerFactories) {
+    _gestureRecognizers = gestureRecognizerFactories
+        .map((Factory<OneSequenceGestureRecognizer> factory) => factory.constructor()).toSet();
+    team = GestureArenaTeam();
+    team.captain = this;
+    for (OneSequenceGestureRecognizer recognizer in _gestureRecognizers) {
+      recognizer.team = team;
+    }
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: you could reduce this to one loop:

```dart
team = GestureArenaTeam();
￼team.captain = this;
_g￼estureRecognizers = gestureRecognizerFactories.map(
  (Factory<OneSequenceGestureRecognizer> factory) {
    return factory.constructor()
      ..team = team;
  }
).toSet();
```

or:

```dart
team = GestureArenaTeam();
￼team.captain = this;
_gestureRecognizers ??= new Set<OneSequenceGestureRecognizer>();
_gestureRecognizers.clear();
for (Factory<OneSequenceGestureRecognizer> factory in gestureRecognizerFactories) {
  _gestureRecognizers.add(
    factory.constructor()
      ..team = team
  );
}
```

...or some such.

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 16]
```diff
@@ -160,7 +171,7 @@ class _AndroidViewState extends State<AndroidView> {
     return _AndroidPlatformView(
         controller: _controller,
         hitTestBehavior: widget.hitTestBehavior,
-        gestureRecognizers: widget.gestureRecognizers,
+        gestureRecognizers: widget.gestureRecognizers ?? Set<Factory<OneSequenceGestureRecognizer>>(),
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/platform_view.dart]: there's a lot of places in this PR where you either have defaults, or default from null, or whatever (sometimes with a constructor like here, sometimes with a precreated static variable, etc). It would be nice if there was only one place that needed to default, and on one side of that null was considered acceptable, and on the other side it was not.

File: packages/flutter/lib/src/rendering/platform_view.dart [hunk 17]
```diff
@@ -94,19 +97,43 @@ class RenderAndroidView extends RenderBox {
...
+  ///
+  /// `gestureRecognizers` must not contain more than one factory with the same [Factory.type].
+  ///
+  /// Setting a new set of gesture recognizer factories with the same [Factory.type]s as the current
+  /// set is ignored.
+  ///
+  /// Setting a new set of gesture recognizer factories with different [Factory.type]s
+  /// (e.g `gestureRecognizers.map((f) => f.type).toSet()` is different, will reject any active
+  /// gesture arena.
+  void setGestureRecognizers(Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers) {
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/platform_view.dart]: i recommend calling this updateGestureRecognizers so that people don't tell you it should be a setter.

File: packages/flutter/test/widgets/platform_view_test.dart [hunk 18]
```diff
@@ -562,7 +563,11 @@ void main() {
             height: 100.0,
             child: AndroidView(
               viewType: 'webview',
-              gestureRecognizers: <OneSequenceGestureRecognizer> [VerticalDragGestureRecognizer()],
+              gestureRecognizers: <Factory<OneSequenceGestureRecognizer>> [
```
Comment (Hixie) [inline packages/flutter/test/widgets/platform_view_test.dart]: here and elsewhere: extraneous space before `[`

**Comment by Hixie** [comment]
LGTM modulo changes

File: packages/flutter/lib/src/rendering/platform_view.dart (hunk 15 above)
Comment (amirh) [reply packages/flutter/lib/src/rendering/platform_view.dart]: done

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 19]
```diff
@@ -118,19 +119,29 @@ class AndroidView extends StatefulWidget {
   ///     height: 100.0,
   ///     child: AndroidView(
   ///       viewType: 'webview',
-  ///       gestureRecognizers: <OneSequenceGestureRecognizer>[ new VerticalDragGestureRecognizer() ],
+  ///       gestureRecognizers: <Factory<OneSequenceGestureRecognizer>> [
```
[the remark this answers is not in the document]
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: done

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 20]
```diff
@@ -118,19 +119,29 @@ class AndroidView extends StatefulWidget {
...
   /// ```
   ///
   /// An [AndroidView] can be configured to consume all pointers that were put down in its bounds
-  /// by passing an [EagerGestureRecognizer] in [gestureRecognizers]. [EagerGestureRecognizer] is a
-  /// special gesture recognizer that immediately claims the gesture after a pointer down event.
+  /// by passing a factory for an [EagerGestureRecognizer] in [gestureRecognizers].
+  /// [EagerGestureRecognizer] is a special gesture recognizer that immediately claims the gesture
+  /// after a pointer down event.
+  ///
+  /// `gestureRecognizers` must not contain more than one factory with the same [Factory.type].
```
[the remark this answers is not in the document]
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: done

File: packages/flutter/test/widgets/platform_view_test.dart (hunk 18 above)
Comment (amirh) [reply packages/flutter/test/widgets/platform_view_test.dart]: done

File: packages/flutter/lib/src/widgets/platform_view.dart (hunk 16 above)
Comment (amirh) [reply packages/flutter/lib/src/widgets/platform_view.dart]: Left this the only place that defaults for null, the classes downstream now require a non null value.

**Review by amirh — COMMENTED** [review]
Thanks for the thorough review!
