### PR TITLE
Ensure the flutter_gen project is correctly created as part of "flutter create"

### LINKED ISSUE #92437: Errors in new project created in VS Code
STEPS TO REPRODUCE:
1. I clean-installed VS Code on Linux and ran it.
2. I added the Flutter extension.
3. I chose to create a new project using the "skeleton" template in a new directory.
4. A prompt told me to press F5 to run it, so I did.

EXPECTED RESULTS
App runs, either on my attached Android device, or using Linux, or as a web app.

ACTUAL RESULTS
It immediately complained about build errors.

### PR DESCRIPTION
**Pull request by DanTup**
This fixes an issue where `flutter create` would not create the `flutter_gen` package at `.dart_tool/flutter_gen` resulting in analysis errors if you opened in an editor without first running `flutter pub get` (which does create the package) or some `flutter x` command (which also triggers creating the package).

More details in the comments from https://github.com/flutter/flutter/issues/92437#issuecomment-958920558 onwards.

There is one unexpected thing I had to change to make the test pass, which is related to the `pubspec.yaml` being created based on the current directory (which was not correct in the test, resulting in the `pubspec.yaml` being created in the wrong place). I'll add a comment to the specific code in the PR below.

Fixes #92437.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

@hixie @christopherfujino 

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 1]
```diff
@@ -1277,7 +1277,9 @@ class LocalizationsGenerator {
     // A pubspec.yaml file is required when using a synthetic package. If it does not
     // exist, create a blank one.
     if (useSyntheticPackage) {
-      final Directory syntheticPackageDirectory = _fs.directory(_defaultSyntheticPackagePath(_fs));
+      final Directory syntheticPackageDirectory = projectDirectory != null
+          ? projectDirectory!.childDirectory(_defaultSyntheticPackagePath(_fs))
+          : _fs.directory(_defaultSyntheticPackagePath(_fs));
```
Comment (DanTup) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:1282]: Without this change, this always created the `pubspec.yaml` using a relative path from the current directory (which when running the test, was the real `flutter_tools` folder, and not where the test project was being created). It felt like I should reuse `outputDirectory`, but that's set to a sub-folder of the package rather than the package root. Perhaps it's worth adding a `syntheticPackageDirectory` at the class level and moving this to the constructor alongside `outputDirectory`?

File: packages/flutter_tools/lib/src/commands/create_base.dart [hunk 2]
```diff
@@ -456,6 +459,27 @@ abstract class CreateBase extends FlutterCommand {
...
+        projectDir: project.directory,
+        generateDartPluginRegistry: true,
+      );
+
+      // Generate the l10n synthetic package that will be injected into the
+      // package_config in the call to pub.get() below.
+      await generateLocalizationsSyntheticPackage(
+        environment: environment,
+        buildSystem: globals.buildSystem,
+      );
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/create_base.dart:481]: I don't know this system that well, but can't we just call the same code that `flutter packages get` calls, rather than having to more or less duplicate it here?

Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/create_base.dart:481]: I'm also not too familiar with it. That code is inside `PackagesGetCommand`. I don't know if it's weird to create/call another command from inside this command. If so, we could perhaps make a function that does both the generation+pub get and call it from both.

As far as I can see, there aren't many differences in the `pub get` call (at least that can't be handled with some arguments), although the one in the `PackagesGetCommand` does also record timings - I'm not sure whether that should/shouldn't be included when it's being called by `create`.

@christopherfujino are you more familiar with this - do you have an opinion on the best way to share this?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:481]: No, not more familiar, I'm catching up with the source issue before I have an opinion...

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:481]: we can pull this out into a shared function, although, this is essentially a one line addition, of `await generateLocalizationsSyntheticPackage(...)`, it just looks longer because we're creating the `Environment` object on another line, which is forwarding a lot of globals. I think this code LGTM as is.

**Review by christopherfujino — APPROVED** [review]
LGTM
