### PR TITLE
[flutter_tools] Update to latest dwds APIs

### LINKED ISSUE #52193: [web]: [macOS] [VSCode] Debugging broken in 1.15.2 and later
flutter_web: 1.15.2
Chrome: 80.0.3987.122
macOS: Mojave 10.14.6
VSCode: 1.42.1

Ensure web is enabled 
Create a new project  (no changes required)
Set the breakpoint any where
Set the device to "Chrome (Web)" & Start debugging

Observation:
1. Chrome shows no page
2. Breakpoint (if any) not hit

Switch to flutter web 1.15.1
Open Same Project created above
Set the breakpoint any where
Set the device to "Chrome (Web)" & Start debugging

Observation:
1. Chrome loads page correctly
2. Breakpoint hit

### PR DESCRIPTION
**Pull request by jonahwilliams**
Update to latest dwds APIs, moving back to dwds driven hot restart and enabling future work on expression evaluation.

@grouma 
@annagrin 

Fixes https://github.com/flutter/flutter/issues/52193

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 1]
```diff
@@ -112,127 +51,33 @@ window.\$hotReloadHook = function(modules) {
...
-          if (url.endsWith('dart_sdk.js')) {
-            module = 'dart_sdk';
-          } else {
-            try {
-              module = '/packages' + url.split('packages')[1].split('.')[0] + '.dart';
-            } catch (e) {
-              return null;
-            }
-          }
+        var module = window.\$requireLoader.urlToModuleId.get(url)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: It looks like the dartLoader doesn't exist anymore - should I be using the requireLoader? Otherwise  I'm not sure exactly what this code should look like. I tried a few permutations but they all crash

Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: You shouldn't need either. You are correct that the `dartLoader` was removed and replaced with `reqruireLoader`. However, `package:dwds` now embeds the `requrieLoader` in the entry bootstrap. 

See here:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/handlers/injected_handler.dart#L74

And here:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/loaders/require.dart#L179

Let me know if removing this doesn't fix your problem.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Removing SGTM, but I don't see any handling of the `dartStackTraceUtility` in the new dwds code

Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: @jakemac53 said that logic was safe to remove. He can probably provide more context.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Another difference is that If I throw an unhandled exception, before the stackTraceMapper would first be called with a url like `http://localhost:53973/dart_sdk.js` that would be mapped to the module name `dart_sdk`. Now it's failing with `http://localhost:53973/something/dart_stack_trace_mapper.js` which might indicate something isn't getting set up correctly. Still investigating

Comment (jakemac53) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: The `dartStackTraceUtility` does still need to exist - it is used for mapping stack traces in the browser console.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: In this case, it sounds like I should be handling the initialization of `dartStackTraceUtility` and using the require loaded to get  the correct source map?

Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: That sounds about right. @jakemac53 should we include this in `package:dwds`?

Comment (jakemac53) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: I think it needs to be added by build_web_compilers - it has its own version. Flutter also i think has its own version.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Is there an equivalent to this line I need to do for the requireLoader?

https://github.com/dart-lang/build/blob/8c8ed2b52357b62971889ab2c8c26db2163c0080/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L366

I'm currrently using the following code:

```
  dart_sdk._isolate_helper.startRootIsolate(() => {}, []);
  if (window.\$dartStackTraceUtility && !window.\$dartStackTraceUtility.ready) {
    window.\$dartStackTraceUtility.ready = true;
    let dart = dart_sdk.dart;
    window.\$dartStackTraceUtility.setSourceMapProvider(function(url) {
      url = url.replace(window.\$dartUriBase, '');
      var module = window.\$requireLoader.urlToModuleId.get(url);
      if (!module) return;
      return dart.getSourceMap(url);
    });
  }
```

But I'm only get `url` from the stack trace mapper itself, which leads me to believe that I set it up incorrectly.

Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: There is not but I'm happy to add it to `package:dwds` somewhere here: https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/loaders/require.dart#L222

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Its not so much what API goes into dwds, there is a slight bug now since we use the stack trace mapper from the SDK. This expects there to be a field called `window.$dartLoader.rootDirectories`:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/web/stack_trace_mapper.dart#L39

All stack traces actually are crashing in the stack trace mapper now. I can work around by defining this in the bootstrap script myself

Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Ahh I see. I'm thinking we just duplicate `window.$dratLoader.rootDirectories` in the DWDS bootstrap for now and eventually clean up the SDK.

**Comment by jonahwilliams** [comment]
Everything seems to working for the most part, except the hot restarts are requesting more resources than necessary and doing full page reloads. I think I've misconfigured something with the modules/digests, but I'm not sure where

**Comment by jonahwilliams** [comment]
So far I've discovered that the special entrypoint in temp seems to be throwing off the module naming. It works a bit better if I stick `packages/packagename` in front of the module name. Still not reload correctly as client.js can't seem to match the right extension in the $requireLoader urlToModule

**Comment by grouma** [comment]
@annagrin has been running into similar issues while testing. Let's put this on hold for now and I'll dig through the issue with her.

**Comment by jonahwilliams** [comment]
It might help if we could relax the requirement to use either a multiroot scheme or a package scheme. That would at least simplify some of the paths used and server configuration.

File: packages/flutter_tools/lib/src/build_runner/devfs_web.dart [hunk 2]
```diff
@@ -91,7 +119,13 @@ class WebAssetServer implements AssetReader {
         },
         urlEncoder: urlTunneller,
         enableDebugging: true,
-        logWriter: (Level logLevel, String message) => globals.printTrace(message)
+        logWriter: (Level logLevel, String message) => globals.printTrace(message),
+        loadStrategy: RequireStrategy(
+          ReloadConfiguration.none,
+          'lib',
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_runner/devfs_web.dart]: unclear what this should be

File: packages/flutter_tools/lib/src/build_runner/devfs_web.dart [hunk 3]
```diff
@@ -41,12 +42,37 @@ import '../web/chrome.dart';
...
+      // We skip computing the digest by using the hashCode of the underlying buffer.
+      // Whenever a file is updated, the corresponding Uint8List.view it corresponds
+      // to will change.
+      final String moduleName = module.startsWith('/')
+        ? module.substring(1)
+        : module;
+      final String name = moduleName.replaceAll('.lib.js', '');
+      final String path = moduleName.replaceAll('.js', '');
+      _modules[name] = path;
+      _digests[name] = Random().nextInt(123).toString();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_runner/devfs_web.dart]: Will fix

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 4]
```diff
@@ -498,26 +495,25 @@ class _ResidentWebRunner extends ResidentWebRunner {
...
 
-    Duration transferMarker;
     try {
       if (!deviceIsDebuggable) {
         globals.printStatus('Recompile complete. Page requires refresh.');
-      } else if (!debuggingOptions.buildInfo.isDebug) {
+      } else if (isRunningDebug) {
+        try {
+          await _vmService.callMethod('hotRestart');
+        } catch (err) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Need to catch actual type

**Comment by jonahwilliams** [comment]
everything works now, and I ported some of the hot restart and debugger stepping tests to web

File: packages/flutter_tools/pubspec.yaml [hunk 5]
```diff
@@ -105,6 +103,12 @@ dev_dependencies:
   multi_server_socket: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
   node_preamble: 1.4.8 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
 
+dependency_overrides:
```
Comment (jonahwilliams) [inline packages/flutter_tools/pubspec.yaml]: Just need a publish and I can remove this and update packages

File: packages/flutter/test/widgets/binding_test.dart [hunk 6]
```diff
@@ -205,7 +205,7 @@ void main() {
     FlutterError.onError = oldHandler;
     const String toMatch = '...     Normal element mounting (';
     expect(toMatch.allMatches(filteredStack)?.length, 1);
-  });
+  }, skip: kIsWeb); // The `flutter run` and `flutter test` commands produce different output.
```
Comment (yjbanov) [inline packages/flutter/test/widgets/binding_test.dart]: This looks like a regression worth fixing.

File: packages/flutter_tools/lib/src/test/runner.dart [hunk 7]
```diff
@@ -190,7 +190,7 @@ class _FlutterTestRunnerImpl implements FlutterTestRunner {
 
       return exitCode;
     } finally {
-      globals.fs.currentDirectory = saved;
+      globals.fs.currentDirectory = saved.path;
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/test/runner.dart]: Type error

**Comment by jonahwilliams** [comment]
Its ready!

File: packages/flutter/test/foundation/stack_frame_test.dart [hunk 8]
```diff
@@ -218,34 +218,34 @@ const List<StackFrame> stackFrameNoColsFrames = <StackFrame>[
...
-object_test.dart 210:5                                                                performLayout
-package:dart-sdk/lib/async/future_impl.dart 140:18                                    handleValue
-package:dart-sdk/lib/async/future_impl.dart 682:44                                    handleValueCallback
-package:dart-sdk/lib/async/future_impl.dart 711:32                                    _propagateToListeners
-package:dart-sdk/lib/async/future_impl.dart 391:9                                     callback
-package:dart-sdk/lib/async/schedule_microtask.dart 43:11                              _microtaskLoop
-package:dart-sdk/lib/async/schedule_microtask.dart 52:5                               _startMicrotaskLoop
-package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15           <fn>''';
+dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
+package/assertions/main.dart 4:3                                              blah
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/test/foundation/stack_frame_test.dart]: Reverted

File: packages/flutter/test/widgets/binding_test.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter/test/widgets/binding_test.dart]: This is code is testing the output of flutter test, which is different than the output of flutter run. I tried to update the stack trace parsing to work better for flutter run, but instead I could revert all of the changes and leave that as a follow up - might be easier

File: dev/bots/test.dart [hunk 9]
```diff
@@ -718,6 +720,7 @@ Future<void> _pubRunTest(String workingDirectory, {
   bool useBuildRunner = false,
   String coverage,
   bq.TabledataResourceApi tableData,
+  bool forceSingleCore = false,
```
Comment (jonahwilliams) [inline dev/bots/test.dart]: Without this change, we would try to spin up multiple chrome instances and stall. I'm also suspicious that some of the previous flakes in integration tests were caused by having multiple flutter_tester shells active.

**Review by yjbanov — APPROVED** [review]
LGTM if LGT @grouma

File: dev/bots/test.dart [hunk 10]
```diff
@@ -278,11 +278,13 @@ Future<void> _runToolTests() async {
       final String suffix = Platform.isWindows && subshard == 'commands'
         ? 'permeable'
         : '';
+      final bool forceSingleCore = Platform.isLinux && subshard == 'integration';
```
Comment (zanderso) [inline dev/bots/test.dart]: Why only Linux? (Add a comment explaining)

File: dev/bots/test.dart (hunk 9 above)
Comment (zanderso) [reply dev/bots/test.dart]: This should go in a comment.

File: dev/bots/test.dart [hunk 11]
```diff
@@ -731,6 +734,11 @@ Future<void> _pubRunTest(String workingDirectory, {
   } else {
     cpus = 2; // Don't default to 1, otherwise we won't catch race conditions.
   }
+  // Integration tests that depend on external processes like chrome
```
Comment (zanderso) [inline dev/bots/test.dart]: Oh, nm. I see it here.

File: packages/flutter/lib/src/foundation/stack_frame.dart [hunk 12]
```diff
@@ -105,7 +105,7 @@ class StackFrame {
   static StackFrame _parseWebDebugFrame(String line) {
     final bool hasPackage = line.startsWith('package');
     final RegExp parser = hasPackage
-        ? RegExp(r'^(package:.+) (\d+):(\d+)\s+(.+)$')
+        ? RegExp(r'^(package.+) (\d+):(\d+)\s+(.+)$')
```
Comment (zanderso) [inline packages/flutter/lib/src/foundation/stack_frame.dart]: Consider adding a comment for this regexp. Separately, where would 'package' not be followed by ':' ?

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 13]
```diff
@@ -498,26 +494,21 @@ class _ResidentWebRunner extends ResidentWebRunner {
...
-        await _wipConnection?.debugger?.sendCommand(
-          'Runtime.evaluate', params: <String, Object>{
-            'expression': 'window.\$hotReloadHook([$reloadModules])',
-            'awaitPromise': true,
-            'returnByValue': true,
-          },
-        );
       }
+    } on Exception catch (err) {
+      globals.printError(err.toString());
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: If we can't give any more information here, and it will fail later regardless, should this just be a `printTrace()` ?

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 14]
```diff
@@ -498,26 +494,21 @@ class _ResidentWebRunner extends ResidentWebRunner {
...
+      return OperationResult(1, err.toString());
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Will including the `err.toString()` in the `OperationResult` case it to be printed twice?

File: packages/flutter_tools/lib/src/compile.dart [hunk 15]
```diff
@@ -656,6 +656,7 @@ class DefaultResidentCompiler implements ResidentCompiler {
       sdkRoot,
       '--incremental',
       '--target=$targetModel',
+      '--debugger-module-names',
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/compile.dart]: Are there any comments worth adding here about what this flag does?

File: dev/bots/test.dart (hunk 9 above)
Comment (grouma) [reply dev/bots/test.dart]: This is interesting. Do you not use the concurrency parameter of `package:test`?

File: packages/flutter_tools/lib/src/build_runner/devfs_web.dart [hunk 16]
```diff
@@ -382,7 +421,10 @@ class WebAssetServer implements AssetReader {
   }
 
   @override
-  Future<String> dartSourceContents(String serverPath) {
+  Future<String> dartSourceContents(String serverPath) async {
+    if (serverPath == null || serverPath.trim().isEmpty) {
```
Comment (grouma) [inline packages/flutter_tools/lib/src/build_runner/devfs_web.dart]: This is an interesting guard. Not that it's wrong by does `package:dwds` ever request null paths?

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 17]
```diff
@@ -69,34 +35,6 @@ requireEl.src = "$requireUrl";
 // This attribute tells require JS what to load as main (defined below).
 requireEl.setAttribute("data-main", "main_module.bootstrap");
 document.head.appendChild(requireEl);
-
-// Invoked by connected chrome debugger for hot reload/restart support.
-window.\$hotReloadHook = function(modules) {
```
Comment (grouma) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: Love this cleanup!

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 18]
```diff
@@ -112,127 +50,37 @@ window.\$hotReloadHook = function(modules) {
...
-              module = '/packages' + url.split('packages')[1].split('.')[0] + '.dart';
-            } catch (e) {
-              return null;
-            }
-          }
-        }
-        return dart.getSourceMap(module);
-      });
-  }
+  dart_sdk._isolate_helper.startRootIsolate(() => {}, []);
```
Comment (grouma) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: I'm not familiar with this. What is this for?

File: packages/flutter_tools/lib/src/web/bootstrap.dart [hunk 19]
```diff
@@ -112,127 +50,37 @@ window.\$hotReloadHook = function(modules) {
...
-  }
 
   /* MAIN_EXTENSION_MARKER */
   child.main();
-});
 
-// Require JS configuration.
-require.config({
-  waitSeconds: 0,
+window.\$dartLoader = {};
```
Comment (grouma) [inline packages/flutter_tools/lib/src/web/bootstrap.dart]: Is the dartLoader stuff required? Shouldn't be anymore.

File: packages/flutter_tools/test/integration.shard/debugger_stepping_web_test.dart [hunk 20]
```diff
@@ -0,0 +1,56 @@
...
+
+void main() {
+  Directory tempDirectory;
+  FlutterRunTestDriver flutter;
+
+  setUp(() {
+    tempDirectory = createResolvedTempDirectorySync('debugger_stepping_test.');
+  });
+
+  test('Web debugger can step over statements', () async {
```
Comment (grouma) [inline packages/flutter_tools/test/integration.shard/debugger_stepping_web_test.dart]: Nice.

**Review by grouma — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/devfs_web.dart (hunk 16 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/devfs_web.dart]: I noticed that devtools was requesting null paths before the change to the tracked library names. I will re-verify this

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 18 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: I think I copied this from the build_runner tooling, so its probably just a straggler. Will remove once I verify its not necessary

File: packages/flutter_tools/test/integration.shard/test_driver.dart [hunk 21]
```diff
@@ -105,7 +105,7 @@ abstract class FlutterTestDriver {
         .followedBy(arguments)
         .toList(),
       workingDirectory: _projectFolder.path,
-      environment: <String, String>{'FLUTTER_TEST': 'true'},
+      environment: <String, String>{'FLUTTER_TEST': 'true', 'FLUTTER_WEB': 'true'},
```
Comment (zanderso) [inline packages/flutter_tools/test/integration.shard/test_driver.dart]: Consider documenting here that this achieves the effect of `flutter config --enable-web`.

File: dev/bots/test.dart (hunk 9 above)
Comment (jonahwilliams) [reply dev/bots/test.dart]: We do, but by default it gets set to the number of cores that the bot has.

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 19 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: We still need this since we're using the stack trace mapper from the SDK, and that code unconditionally refers to these getters

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 18 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Not necessary removed

File: packages/flutter_tools/lib/src/build_runner/devfs_web.dart (hunk 16 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/devfs_web.dart]: Updated - we only get a null path when devtools tries to request the web-entrypoint file with the org-dartlang-app scheme. I made this check more specific, but we should probably fix/hide this file otherwise

File: packages/flutter/lib/src/foundation/stack_frame.dart (hunk 12 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/foundation/stack_frame.dart]: I filled a bug on it here with more details: https://github.com/flutter/flutter/issues/52685

File: dev/bots/test.dart (hunk 10 above)
Comment (jonahwilliams) [reply dev/bots/test.dart]: Added comment

File: packages/flutter_tools/lib/src/compile.dart (hunk 15 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/compile.dart]: Added a comment. This is a breaking change flag, so once all of the tooling is updated we can make it the default and remove

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 14 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: I've just updated here and above to be fatal errors, so we should print the message with a throwToolExit.

I can't think of a case where we hit a HotRestartException or WipError that we could recover from, so getting people out of the tool is likely better than getting stuck in a loop of prompting the user to "Try again after fixing the above error"

File: packages/flutter/lib/src/foundation/stack_frame.dart (hunk 12 above)
Comment (zanderso) [reply packages/flutter/lib/src/foundation/stack_frame.dart]: kk. Maybe link to that issue in a comment here.

File: packages/flutter_tools/test/integration.shard/test_driver.dart (hunk 21 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/integration.shard/test_driver.dart]: Done

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 13 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Commented below

File: packages/flutter_tools/lib/src/compile.dart (hunk 15 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/compile.dart]: Is there an issue we can link to for the migration?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/compile.dart]: Filled and linked https://github.com/flutter/flutter/issues/52693

File: packages/flutter/lib/src/foundation/stack_frame.dart (hunk 12 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/foundation/stack_frame.dart]: Done

File: packages/flutter_tools/lib/src/web/bootstrap.dart (hunk 19 above)
Comment (grouma) [reply packages/flutter_tools/lib/src/web/bootstrap.dart]: Oh yes. Hmmm. We should reconsider that at one point.

**Review by zanderso — APPROVED** [review]
lgtm. when this makes it to dev/, monitor crash logging for new crashers.
