### PR TITLE
Delete and Backspace shortcuts accept optional Shift modifier

### LINKED ISSUE #94880: Delete key does not work when shift is pressed
## Steps to Reproduce

On Android: 

1. Create a simple input: `TextFormField(obscureText: true)`
2. Insert any text whatsoever.
3. Press the shift key (caps) once (so it doesn't get stuck in uppercase, just for the next character), try deleting some text. The text does not change.

The behavior of native apps is to erase text and disable caps

On Mac Os/Windows: 
1. Create a simple input: `TextFormField()`
2. Press the shift key and try deleting the text. The text is not changed.

The native behavior of the platforms is to delete the text

On IOS works as expected. I didn't perform the test on linux

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on Mac OS X 10.15.7 19H1419
    darwin-x64, locale pt-BR)
    • Flutter version 2.8.0-3.2.pre at /Users/reni/Downloads/Programas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2901cd7208 (3 weeks ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/reni/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /Users/reni/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM M315F (mobile) • 192.168.0.107:5555 • android-arm64  • Android 11 (API
      30)
    • macOS (desktop)   • macos              • darwin-x64     • Mac OS X 10.15.7
      19H1419 darwin-x64
    • Chrome (web)      • chrome             • web-javascript • Google Chrome
      96.0.4664.93

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR changes Delete and Backspace related shortcuts in editable text so that they accept an optional shift modifier. For example, both `backspace` and `shift + backspace` now works as deleting backwards, while previously only `backspace` works.

To implement this, `SingleActivator` is changed so that all 4 modifier fields now have type `bool?` instead of `bool`. The extra "null" option means that this modifier is not checked. The default argument is still "false".

Tests are also added to check `backspace` and `shift + backspace` works in EditableText.

Fixes https://github.com/flutter/flutter/issues/94880.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 1]
```diff
@@ -161,12 +161,12 @@ class DefaultTextEditingShortcuts extends Shortcuts {
   // uses different modifier keys as the line/word modifer.
   static const Map<ShortcutActivator, Intent> _commonShortcuts = <ShortcutActivator, Intent>{
     // Delete Shortcuts.
-    SingleActivator(LogicalKeyboardKey.backspace): DeleteCharacterIntent(forward: false),
-    SingleActivator(LogicalKeyboardKey.backspace, control: true): DeleteToNextWordBoundaryIntent(forward: false),
-    SingleActivator(LogicalKeyboardKey.backspace, alt: true): DeleteToLineBreakIntent(forward: false),
-    SingleActivator(LogicalKeyboardKey.delete): DeleteCharacterIntent(forward: true),
-    SingleActivator(LogicalKeyboardKey.delete, control: true): DeleteToNextWordBoundaryIntent(forward: true),
-    SingleActivator(LogicalKeyboardKey.delete, alt: true): DeleteToLineBreakIntent(forward: true),
+    SingleActivator(LogicalKeyboardKey.backspace, shift: null): DeleteCharacterIntent(forward: false),
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:164]: Why can't you just do this?
```suggestion
    SingleActivator(LogicalKeyboardKey.backspace): DeleteCharacterIntent(forward: false),
    SingleActivator(LogicalKeyboardKey.backspace, shift: true): DeleteCharacterIntent(forward: false),
```

Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:164]: I'm concerned that there would be too many activators, both for performance and for maintainability. We're already seeing `shift?` for almost every modifier combination with delete or backspace.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:164]: But adding a tri-state for these complicates both the internal logic and developer reasoning about it. Have you actually seen a performance problem? Because the map is O(1) for lookup, and creating these entries should be very cheap, I wouldn't expect it to have an impact unless there were thousands of them.

**Comment by dkwingsmt** [comment]
@gspencergoog I've changed it to simply spreading more activators. Can you take another look?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Good that you were able to make a bunch of them `const`.

**Comment by augustozanellato** [comment]
When is this expected to land in a release (a beta release would be fine for me)?
At the moment it's a big blocker for the release of one of my projects.

**Comment by dkwingsmt** [comment]
@augustozanellato You can check out https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for our releasing policy :)
