### PR TITLE
`flutter upgrade` needed twice if sky_services dependencies change

### LINKED ISSUE #2953: `flutter upgrade` needed twice if sky_services dependencies change
## Steps to Reproduce

I just upgraded flutter and tried running my code in the Atom editor, but received this bug:

error: Unable to find Dart library 'packages/mojo_services/mojo/ui/view_containers.mojom.dart'.
Failed to run the Flutter compiler. Exit code: 1

Oops; flutter has exited unexpectedly: "1"

Not sure where the problem is, hello world example app is running fine. I also received the same bug on my Linux desktop.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 0eab5e6 (26 hours ago), engine revision f790903

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1

## Logs and Crash Reports

[flutter_01.log.zip](https://github.com/flutter/flutter/files/192282/flutter_01.log.zip)

### PR DESCRIPTION
**Pull request by abarth**
Now we run `flutter --version` to update our local cache of packages before
running `pub upgrade`, which reads from that cache.

Fixes #2953

### CODE REVIEW

**Comment by abarth** [comment]
@eseidelGoogle @devoncarew

**Comment by devoncarew** [comment]
lgtm!

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -43,6 +43,11 @@ class UpgradeCommand extends FlutterCommand {
     if (code != 0)
       return code;
 
+    // Causes us to update our locally cached packages.
+    code = await runCommandAndStreamOutput(<String>[
+      'bin/flutter', '--version'
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/upgrade.dart]: Should we have a flag in the shell script that avoids actually running the Dart part? Or just have all the update logic in a bash script separate from the "flutter" one, so that we can run that directly?

Comment (abarth) [inline packages/flutter_tools/lib/src/commands/upgrade.dart]: Yes, although in this case printing out the version actually makes sense because its showing you which version of flutter you've upgraded to.
