### PR TITLE
pure_android_host_apps/android_host_app_v2_embedding multiple gradle and AGP versions

### LINKED ISSUE #163750: Updating AGP and Gradle causes build_android_host_app_with_module_aar to fail which implies that customers would also be broken.
- Apply patch below. 
- from dev/devicelab run `dart bin/test_runner.dart test -t build_android_host_app_with_module_aar` 

Test fails with `"reason": "Failed to copy read-only asset file"` 
That failure comes from https://github.com/flutter/flutter/blob/e6c333b555b5be4d339ed27d24a364c2719993d4/dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart#L99
Looking in the `build` directory I do not see the read only file. 

```
diff --git a/dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart b/dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart
index 80a5b32276..539890e8a6 100644
--- a/dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart
+++ b/dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart
@@ -437,8 +437,7 @@ class ModuleTest {
 Future<void> main() async {
   await task(
     combine(<TaskFunction>[
-      ModuleTest(gradleVersion: '8.4').call,
-      ModuleTest(gradleVersion: '8.4-rc-3').call,
+      ModuleTest(gradleVersion: '8.10.2').call,
     ]),
   );
 }
diff --git a/dev/integration_tests/pure_android_host_apps/android_host_app_v2_embedding/build.gradle b/dev/integration_tests/pure_android_host_apps/android_host_app_v2_embedding/build.gradle
index 592d125fbc..8715e3234c 100644
--- a/dev/integration_tests/pure_android_host_apps/android_host_app_v2_embedding/build.gradle
+++ b/dev/integration_tests/pure_android_host_apps/android_host_app_v2_embedding/build.gradle
@@ -8,7 +8,7 @@ buildscript {
         mavenCentral()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:8.1.0'
+        classpath 'com.android.tools.build:gradle:8.8.1'
     }
 }
```

### PR DESCRIPTION
**Pull request by reidbaker**
Fixes #163750
Adds local.properties in any directory to the repo wide gitignore. 

Test changes to make the test easier to debug, specifically identifying the difference between a debug and release failure. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: dev/integration_tests/pure_android_host_apps/.gitignore [hunk 1]
```diff
@@ -1,2 +1 @@
-# Name for module used in integration test that should not be checked in.
```
Comment (gmackall) [inline dev/integration_tests/pure_android_host_apps/.gitignore:1]: Was this removal intentional? If so why remove?

File: dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart [hunk 2]
```diff
@@ -33,10 +34,14 @@ TaskFunction combine(List<TaskFunction> tasks) {
 /// Tests that the Flutter module project template works and supports
 /// adding Flutter to an existing Android app.
 class ModuleTest {
-  ModuleTest({this.gradleVersion = '7.6.3'});
+  ModuleTest({this.gradleVersion = '7.6.3', Version? agpVersion})
```
Comment (gmackall) [inline dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart:37]: is this not equivalent to

```dart
ModuleTest({this.gradleVersion = '7.6.3', this.agpVersion = Version(8, 3, 0)})
```
?

File: dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart [hunk 3]
```diff
@@ -247,6 +253,16 @@ class ModuleTest {
       section(propertyContent);
       await gradleWrapperProperties.writeAsString(propertyContent, flush: true);
 
+      // Modify AGP version to the passed in version.
+      // /Users/reidbaker/flutter-work/dev/integration_tests/pure_android_host_apps/android_host_app_v2_embedding/build.gradle
```
Comment (gmackall) [inline dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart:257]: Should we remove the part of the path here that is specific to your laptop?

File: dev/integration_tests/pure_android_host_apps/.gitignore (hunk 1 above)
Comment (reidbaker) [reply dev/integration_tests/pure_android_host_apps/.gitignore:1]: no I added it in 2 prs and this one did not have the description. Fixing

File: dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart (hunk 2 above)
Comment (reidbaker) [reply dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart:37]: It is not because "The default value of an optional parameter must be constant" and version is constructing an object and you can add const Version is not a const constructor .

Comment (gmackall) [reply dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart:37]: TIL

File: dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart (hunk 3 above)
Comment (reidbaker) [reply dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart]: done

File: dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart [hunk 4]
```diff
@@ -247,6 +253,15 @@ class ModuleTest {
...
       await gradleWrapperProperties.writeAsString(propertyContent, flush: true);
 
+      // Modify AGP version to the passed in version.
+      final File topBuildDotGradle = File(path.join(hostApp.path, 'build.gradle'));
+      String topBuildContent = await topBuildDotGradle.readAsString();
+      topBuildContent = topBuildContent.replaceFirst('REPLACEME', agpVersion.toString());
+      section(topBuildContent);
+      await topBuildDotGradle.writeAsString(topBuildContent, flush: true);
+
+      final bool greaterThanGradle83 = agpVersion.compareTo(Version(8, 3, 0)) >= 0;
```
Comment (gmackall) [inline dev/devicelab/bin/tasks/build_android_host_app_with_module_aar.dart:263]: nit: `greaterThanOrEqualToGradle83`, or change to be strictly `>`

**Review by gmackall — APPROVED** [review]
