### PR TITLE
ignore `prefer_final_parameters` in `generated_plugin_registrant` template

### LINKED ISSUE #101252: `prefer_final_parameters` lint error in `generated_plugin_registrant.dart`
## Steps to Reproduce

1. enable `prefer_final_parameters` in `analysis_options.yaml`:
    ```yaml
    linter:
        rules:
            prefer_final_parameters: true
    ```
2. run `dart analyze`

**Expected results:** 
no error, as it's a generated file that should never trigger any lint errors

either `final` should be added to the `registrar` parameter, or the rule should be ignored like the others

**Actual results:** 
```
   info - Prefer final for parameter declarations if they are not reassigned -
          lib\generated_plugin_registrant.dart:13:22 - prefer_final_parameters
```
<details>
<summary>Code sample</summary>

```dart
//
// Generated file. Do not edit.
//

// ignore_for_file: directives_ordering
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: depend_on_referenced_packages

import 'package:file_picker/_internal/file_picker_web.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  FilePickerWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}
```

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #101252 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by DetachHead** [comment]
seems i don't have access to the ci so i can't see why it's failing

image

**Comment by christopherfujino** [comment]
@DetachHead looks like you have a legitimate test failure:

```
00:26 +55 ~3 -1: test/analyze_sample_code_test.dart: Analyzes dart:ui code [E]                                                                                                                         
  Expected: contains all of [
              'In sample starting at dev/bots/test/analyze-sample-code-test-dart-ui/ui.dart:15:class MyStatelessWidget extends StatelessWidget {',
              '>>> error: Missing concrete implementation of \'StatelessWidget.build\' (non_abstract_class_inherits_abstract_member)',
              'In sample starting at dev/bots/test/analyze-sample-code-test-dart-ui/ui.dart:15:class MyStringBuffer {',
              '>>> error: Classes can\'t be declared inside other classes (class_in_class)'
            ]
    Actual: [
              'Unhandled exception:',
              'Cannot analyze dartdocs; unexpected error output:',
              '[Because analyze_sample_code depends on flutter_test from sdk which doesn\'t exist (the Flutter SDK is not available), version solving failed., , Flutter users should run `flutter pub get` instead of `dart pub get`., 10 issues found. (ran in 3.5s)]',
              '#0      SampleChecker._runAnalyzer (file:///opt/s/w/ir/x/w/flutter/dev/bots/analyze_sample_code.dart:817:7)',
              '#1      SampleChecker._analyze (file:///opt/s/w/ir/x/w/flutter/dev/bots/analyze_sample_code.dart:838:20)',
              '#2      SampleChecker.checkSamples (file:///opt/s/w/ir/x/w/flutter/dev/bots/analyze_sample_code.dart:402:24)',
              '<asynchronous suspension>',
              '#3      main (file:///opt/s/w/ir/x/w/flutter/dev/bots/analyze_sample_code.dart:147:18)',
              '<asynchronous suspension>',
              ''
            ]
     Which: has no match for 'In sample starting at dev/bots/test/analyze-sample-code-test-dart-ui/ui.dart:15:class MyStatelessWidget extends StatelessWidget {' at index 0 along with 3 other unmatched
  
  package:test_api                         expect
  test/analyze_sample_code_test.dart 59:5  main.<fn>
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20framework_tests_misc/17701/overview

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 1]
```diff
@@ -558,6 +558,7 @@ const String _dartPluginRegistryTemplate = '''
 // ignore_for_file: directives_ordering
 // ignore_for_file: lines_longer_than_80_chars
 // ignore_for_file: depend_on_referenced_packages
+// ignore_for_file: prefer_final_parameters
```
Comment (goderbauer) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:561]: Instead of adding this ignore let's just fix the actual warning by making `Registrar registrar` final in line 570.

**Comment by DetachHead** [comment]
@christopherfujino no idea what couldve caused that but it looks like all the tests are passing now after i applied @goderbauer's suggestion

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by Jasguerrero — APPROVED** [review]
LGTM
