### PR TITLE
Scrollable TabBar shows initialIndex

### LINKED ISSUE #9374: TabBar doesn't set a correct initial scroll position
## Steps to Reproduce
The TabBar is always initially scrolled to the left, even if the selected tab is far outside the right side of the screen.
Test case here: https://github.com/vlidholt/flutter_bugs/blob/master/lib/bug_tab_bar.dart

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f16e634e2e (3 weeks ago), 2017-03-26 11:52:44
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)

### PR DESCRIPTION
**Pull request by HansMuller**
If scrollable TabBar's TabController has a non-zero initialIndex: scroll the selected tab into view.

The scroll has to be done after the tab bar's initial layout, since scrollable tab widths vary and they're needed to compute the initial scroll offset.

Fixes: https://github.com/flutter/flutter/issues/9374

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -440,7 +440,8 @@ class TabBar extends StatefulWidget implements PreferredSizeWidget {
 }
 
 class _TabBarState extends State<TabBar> {
-  final ScrollController _scrollController = new ScrollController();
+  ScrollController _scrollController = new ScrollController();
```
Comment (abarth) [inline packages/flutter/lib/src/material/tabs.dart]: Why not file anymore?

Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: Oops, I didn't mean to remove the final qualifier. Thanks for pointing that out.

File: packages/flutter/lib/src/material/tabs.dart [hunk 2]
```diff
@@ -557,8 +558,18 @@ class _TabBarState extends State<TabBar> {
...
   }
 
+  // Called each time layout completes.
   void _saveTabOffsets(List<double> tabOffsets) {
     _indicatorPainter?.tabOffsets = tabOffsets;
+
+    if (!_completedInitialScroll) {
+      _completedInitialScroll = true;
+      if (widget.isScrollable && _currentIndex != 0) {
+        scheduleMicrotask(() {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: this is usually a bad sign...

File: packages/flutter/test/material/tabs_test.dart [hunk 3]
```diff
@@ -759,4 +759,32 @@ void main() {
     controller.index = 1;
     await tester.pump(const Duration(milliseconds: 300));
   });
+
+  testWidgets('Scrollabel TabBar with a non-zero TabController initialIndex', (WidgetTester tester) async {
```
Comment (Hixie) [inline packages/flutter/test/material/tabs_test.dart]: typo

File: packages/flutter/lib/src/material/tabs.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: can't we do this the same way we do it for page views?

Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: At this point, although layout of the TabBar's tabs is complete, the ScrollController's position.viewportDimension is still null.  So I've deferred doing the scroll until layout is finished, at which point the viewportDimension has been set.

If there's another way to get this to go, I'm all ears.

Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: PageView creates subclasses of ScrollController/ScrollPosition and appears to use ScrollPosition.correctPixels() to fixup the  scroll offset once the viewport dimensions are determined.  At least that's what appears to be going on. 

I'll try the correctPixels() approach.

File: packages/flutter/lib/src/material/tabs.dart [hunk 4]
```diff
@@ -662,6 +719,7 @@ class _TabBarState extends State<TabBar> {
     );
 
     if (widget.isScrollable) {
+      _scrollController = new _TabBarScrollController(this);
```
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: `??=` ?

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/material/tabs.dart (hunk 4 above)
Comment (HansMuller) [inline packages/flutter/lib/src/material/tabs.dart]: Good point, there's no need to do this more than once.
