### PR TITLE
[Re-Land] Implement focus traversal for desktop platforms.

### LINKED ISSUE #26704: crash on nested Navigator with GlobalKey
The following flutter project reproduces the issue. Run the project, press button "1", then press button "2".

  https://github.com/SteveAlexander/navigator_issue

When using two levels of nested Navigator, where they have GlobalKeys, on the second route pushed, the app crashes with the following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building FocusScope(dirty, state: _FocusScopeState#7e10a):
flutter: 'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 315 pos 12: 'child._parent
flutter: == null || child._parent == this': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      FocusScopeNode.setFirstFocus (package:flutter/src/widgets/focus_manager.dart:315:12)
flutter: #3      FocusScopeNode.reparentScopeIfNeeded (package:flutter/src/widgets/focus_manager.dart:338:7)
flutter: #4      _FocusScopeState.build (package:flutter/src/widgets/focus_scope.dart:104:28)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2943:38)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
etc.
```

The exception looks similar to https://github.com/flutter/flutter/issues/11719, but while that one is about TextFields, this one is specific to how Navigators interact with GlobalKeys.

The problem also looks similar to this old issue about nested focus scopes, fixed by @Hixie in 2015: https://github.com/flutter/flutter/pull/448

### LINKED ISSUE #30084: Focus based navigation needs to have the widget Rect.
In order to be able to perform focus-based navigation, it is necessary to know the size and location of widgets that might be traversed to.

This is a tracking issue for the breaking change needed to collect this information, in order to fix #1608.

Currently, `FocusScopeNode.reparentIfNeeded` takes only the `FocusNode` that it will reparent. In order to provide services needed for keyboard focus traversal, this method will need to provide a `BuildContext` in order to be able to measure its size and location when determining the next widget to traverse to.
We propose to break the `FocusScopeNode` API by changing it's signature from:
```dart
void reparentIfNeeded(FocusNode node);
```
to
```dart
void reparentIfNeeded(BuildContext context, FocusNode node);
```

To modify code to compile again after this change, you would need to add a context argument to the call.  Typically, this method is called from a build method in order to keep the focus tree up to date with the widget tree, so instead of calling:
```dart
FocusScope.of(context).reparentIfNeeded(focusNode);
```
You would instead call:
```dart
FocusScope.of(context).reparentIfNeeded(context, focusNode);
```

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This re-lands the Focus changes in #30040.  Correctness changes in routes.dart, and removes the automatic requesting of focus on reparent when there is no current focus, which caused undesirable selections.

## Related Issues

Addresses #11344, #1608, #13264, and #1678
Fixes #30084
Fixes #26704

### CODE REVIEW

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -68,330 +512,347 @@ class FocusNode extends ChangeNotifier {
...
+  ///
+  /// If the given [scope] is not yet a part of the focus tree, then add it to
+  /// the tree as a child of this scope. If it is already part of the focus
+  /// tree, the given scope must be a descendant of this scope.
+  void setFirstFocus(FocusScopeNode scope) {
+    assert(scope != null);
+    if (scope._parent == null) {
+      _reparent(scope);
+    }
+    assert(scope.ancestors.contains(this));
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: Shouldn't this get a big assert message like the other similar asserts?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 2]
```diff
@@ -592,12 +595,18 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
     if (widget.route.secondaryAnimation != null)
       animations.add(widget.route.secondaryAnimation);
     _listenable = Listenable.merge(animations);
+    if (widget.route.isCurrent) {
+      widget.route.navigator.focusScopeNode.setFirstFocus(focusScopeNode);
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/routes.dart]: According to https://docs.flutter.io/flutter/widgets/Route/navigator.html, a route's navigator can be null (here and below).

**Review by HansMuller — APPROVED** [review]
LGTM so long as route.navigator is guaranteed to be non-null for some reason or we use route?.navigator

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/routes.dart]: It can only be null if it hasn't been pushed yet, or if it has been disposed.

In this case `isCurrent` checks that the navigator isn't null, and in the case of `didPush` below, by definition it has been pushed, so it's probably OK as-is.  I'm happy to still add the ?'s if you think it would be better to do it defensively against a future change, but they're not needed as-is.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Done.
