### PR TITLE
Give guided message when project is not compatible with SwiftPM

### LINKED ISSUE #171921: Error message when Swift Package Manager isn't enabled should give the correct reason
When trying to build or run flutter pub commands I get the following error:
```
Plugin fused_location is only Swift Package Manager compatible. Try enabling Swift Package Manager by running "flutter config --enable-swift-package-manager" or remove the plugin as a dependency.
```

I have tried running `flutter config --enable-swift-package-manager` but it doesn't help.

I am running on MacOS 12.7.6.

```
[✓] Flutter (Channel stable, 3.32.5, on macOS 12.7.6 21H1320 darwin-x64, locale en-GB) [787ms]
    • Flutter version 3.32.5 on channel stable at /Users/avance/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcf2c11572 (2 weeks ago), 2025-06-24 11:44:07 -0700
    • Engine revision dd93de6fb1
    • Dart version 3.8.1
    • DevTools version 2.45.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [877ms]
    • Android SDK at /Users/avance/Library/Android/sdk
    ✗ cmdline-tools component is missing.
      Try installing or updating Android Studio.
      Alternatively, download the tools from https://developer.android.com/studio#command-line-tools-only and make sure to set the ANDROID_HOME environment variable.
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 14.2) [1,867ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [41ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2) [40ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.101.2) [37ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (2 available) [6.2s]
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 138.0.7204.100

[✓] Network resources [438ms]
    • All expected network resources are available.
```

I'm hoping its not the Xcode version causing the issue as I can't upgrade it on my Mac 🤞

### PR DESCRIPTION
**Pull request by vashworth**
Fixes https://github.com/flutter/flutter/issues/171921.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart [hunk 1]
```diff
@@ -186,12 +186,22 @@ class DarwinDependencyManagement {
...
+            '"flutter config --enable-swift-package-manager" or remove the '
+            'plugin as a dependency.',
+          );
+        } else {
+          throwToolExit(
+            'Plugin ${plugin.name} is only compatible with Swift Package Manager, but your '
+            'project does not currently support it. To support Swift Package Manager:\n'
+            '  - Ensure Xcode 15+ is being used '
+            '  - Enable Swift Package Manager feature by running '
+            '"flutter config --enable-swift-package-manager"',
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart:202]: Drive-by comment (@okorohelijah should still review): is this `else` for cases where `flutter config --enable-swift-package-manager` is already run?

File: packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart [hunk 2]
```diff
@@ -186,12 +186,22 @@ class DarwinDependencyManagement {
...
+            'Plugin ${plugin.name} is only compatible with Swift Package Manager. Try '
+            'enabling Swift Package Manager by running '
+            '"flutter config --enable-swift-package-manager" or remove the '
+            'plugin as a dependency.',
+          );
+        } else {
+          throwToolExit(
+            'Plugin ${plugin.name} is only compatible with Swift Package Manager, but your '
+            'project does not currently support it. To support Swift Package Manager:\n'
+            '  - Ensure Xcode 15+ is being used '
```
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart:200]: I think the error message could be misleading if the developer is working on a `flutter module` in which case spm isnt supported yet

**Review by okorohelijah — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart:202]: No, this is when the feature is disabled and the Xcode version is not compatible

File: packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart:200]: Modules are skipped before the method is called:

https://github.com/vashworth/flutter/blob/aeac9c73d8c5b448323b7cd2b015d0f52d4b8686/packages/flutter_tools/lib/src/macos/darwin_dependency_management.dart#L82-L95

**Review by okorohelijah — APPROVED** [review]
LGTM
