### PR TITLE
Assert for valid ScrollController in Scrollbar gestures

### LINKED ISSUE #81277: Error on scrollbar track tap when no controller attached
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  debugDefaultTargetPlatformOverride = TargetPlatform.iOS;
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  final ScrollController controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("Test app")),
        body: Scrollbar(
          child: ListView.builder(
            controller: controller,
            itemBuilder: (context, i) => ListTile(title: Text("Item $i")),
            itemCount: 1000,
          ),
        ),
      ),
    );
  }
}
```
3. Scroll the list, and while the scrollbar is visible, tap in the scrollbar track.

**Expected results:** No error.

**Actual results:** An error indicating that the scrollController is not attached to any scroll views.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.isNotEmpty'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      ScrollController.position
package:flutter/…/widgets/scroll_controller.dart:108
#3      RawScrollbarState._handleTrackTapDown
package:flutter/…/widgets/scrollbar.dart:1160
#4      TapGestureRecognizer.handleTapDown.<anonymous closure>
package:flutter/…/gestures/tap.dart:580
```

```
➜ flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-1.0.pre.102, on Linux, locale en_US.UTF-8)
    • Flutter version 2.3.0-1.0.pre.102 at /home/david/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 519c8e0649 (70 minutes ago), 2021-04-27 03:49:01 -0400
    • Engine revision dbd622cf0c
    • Dart version 2.14.0 (build 2.14.0-46.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /extra_drive/home/david/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /extra_drive/home/david/Android/Sdk
    • Java binary at: /home/david/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0
    • cmake version 3.19.7
    • ninja version 1.8.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.2)
    • Android Studio at /home/david/opt/android-studio
    • Flutter plugin version 52.2.2
    • Dart plugin version 202.8346
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • Linux (desktop)             • linux         • linux-x64   • Linux

• No issues found!
```

</details>

Other gestures in the scrollbar check for a valid scroll position before interacting with it, so I'd say we just need the same check in the track tap gesture.
https://github.com/flutter/flutter/blob/519c8e064956fbb93c7caa72cc6b8b017aafdc24/packages/flutter/lib/src/widgets/scrollbar.dart#L1077
https://github.com/flutter/flutter/blob/519c8e064956fbb93c7caa72cc6b8b017aafdc24/packages/flutter/lib/src/widgets/scrollbar.dart#L1104

### PR DESCRIPTION
**Pull request by davidmartos96**
Fixes #81277

This PR includes a check for scrollbar track taps when there is no scroll position available.
The check is the same as in the other scrollbar gestures:
https://github.com/flutter/flutter/blob/519c8e064956fbb93c7caa72cc6b8b017aafdc24/packages/flutter/lib/src/widgets/scrollbar.dart#L1103
https://github.com/flutter/flutter/blob/519c8e064956fbb93c7caa72cc6b8b017aafdc24/packages/flutter/lib/src/widgets/scrollbar.dart#L1125
https://github.com/flutter/flutter/blob/519c8e064956fbb93c7caa72cc6b8b017aafdc24/packages/flutter/lib/src/widgets/scrollbar.dart#L1145

I wasn't able to find similar tests for error situations with the other scrollbar gestures. This one in particular happens when we pass a scroll controller to a scroll view but not to the scrollbar. Edit: Added some tests

Kindly pinging @Piinks because these checks were added in the previous refactor of the scrollbar.dart file. 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by davidmartos96** [comment]
Update:
I've added the same null check in the CupertinoScrollbar thumb press gesture from @TahaTesser comment in https://github.com/flutter/flutter/issues/81277#issuecomment-827504645

This same check can also be found in the other CupertinoScrollbar gestures:
https://github.com/flutter/flutter/blob/f1ad5cd9ee2a1392fe95037a22894e487ffe2016/packages/flutter/lib/src/cupertino/scrollbar.dart#L175
https://github.com/flutter/flutter/blob/f1ad5cd9ee2a1392fe95037a22894e487ffe2016/packages/flutter/lib/src/cupertino/scrollbar.dart#L187

**Comment by tvolkert** [comment]
Thanks for the contribution!  Is there a test you can add that shows what issue this fixes (that would have failed before your patch)?

**Comment by davidmartos96** [comment]
@tvolkert I tried looking into related tests in the framework but I didn't find any. In fact, I removed the checks from all gestures in the scrollbar and tests were still passing.
I'm not sure how to test this situation in particular because it implies a first step of quickly moving the scrollbar so that it appears before doing the gesture that crashes. We cannot use the isAlways shown property here.

**Comment by davidmartos96** [comment]
@tvolkert I've added some tests.

**Review by Piinks — COMMENTED** [review]
Hi @davidmartos96 thank you for filing an issue **and** writing a PR for it! :) 

> This one in particular happens when we pass a scroll controller to a scroll view but not to the scrollbar.

This is the cause of the issue. You are seeing this error in your code because the `Scrollbar` is trying to use the `PrimaryScrollController`. It uses this `ScrollController` when one has not been provided. Since you have provided a `ScrollController` to the `ListView`, the Scrollbar and ListView are essentially detached. The Scrollbar still updates, since it listens to `ScrollNotifications` that bubble up, but when you try to interact with it, it is trying to use a different controller than the one your ListView actually has. 

Providing your ListView's ScrollController to the Scrollbar should resolve your issue, or if not needed, you can remove the scroll controller from the ListView. 

So, while this change prevents an exception from being thrown, it actually introduces a way for users to break their scrollbar without knowing why. I've updated the bug to reflect a need for better error messaging here, we recently added some in https://github.com/flutter/flutter/pull/77107 for `isAlwaysShown`, I think we could benefit from the same here too. :)

Would you like to update this PR to pursue that?

**Comment by davidmartos96** [comment]
@Piinks Thanks! Yes, I've ended up figuring out the cause. 
The problem here is that is not clear that the Scrollbar always needs a scroll controller to function correctly visually (without interaction).
On our 2 year old app we've been using scrollbars here and there, and when we needed a scroll controller, we only passed it to the listview and co.
Do you think is the fix (the early return) is still worthy to be included? I believe it is, given the similar checks that other gestures have and because it is an optional parameter that only affects the interactivity. In many cases one only wants to see the amount scrolled, which works fine even when using different controllers.
I don't really understand how the isAlwaysShown applies here. For this use case I don't mind for it to hide. Do you mean including an assert to prevent this kind of mistake from happening?

**Comment by davidmartos96** [comment]
It was only until now that we included a crash reporting tool that we found those errors on production code. We've never found those while developing all this time.

**Comment by Piinks** [comment]
> @Piinks Thanks! Yes, I've ended up figuring out the cause.
> The problem here is that is not clear that the Scrollbar always needs a scroll controller to function correctly visually (without interaction).

Visually, no it does not need a `ScrollController`, we actually used to assert that a scroll controller was always provided for interaction. We removed that to allow the `PrimaryScrollController` to be an option and remove some of the churn of always having to wire it up yourself.

This is because we wanted to support multiple options for the `Scrollbar`. You do not always have to provide a scroll controller to the scrollbar, but in this case you do. There are some examples and documentation updates that have not arrived to the stable branch yet, you can see the [master branch documentation here for Scrollbar](https://master-api.flutter.dev/flutter/material/Scrollbar-class.html), there is more under `RawScrollbar` and `CupertinoScrollbar` as well.

> On our 2 year old app we've been using scrollbars here and there, and when we needed a scroll controller, we only passed it to the listview and co.

We do have a new feature that recently landed that allows you to add a Scrollbar as part of the `ScrollBehavior`. This might be of benefit to your use case as  the ScrollBehavior handles setting everything up for you - including the ScrollController. There is a [migration guide available here to show you how to do this](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars) using `ScrollBehavior.buildScrollbar`. This could resolve your problem another way and never require you to wire up ScrollView/Scrollbar yourself. :)

> Do you think the fix (the early return) is still worthy to be included? I believe it is, given the similar checks that other gestures have and because it is an optional parameter that only affects the interactivity. In many cases one only wants to see the amount scrolled, which works fine even when using different controllers.

I do not think we want the early returns as it breaks the scrollbar without any explanation to the user.

> I don't really understand how the isAlwaysShown applies here. For this use case I don't mind for it to hide. Do you mean including an assert to prevent this kind of mistake from happening?

I don't think this is related to isAlwaysShown, the PR I linked was meant to illustrate the type of error messaging
we have been adding to help users identify this issue. I think we can take a similar approach/error message for this case that informs the user what scroll controller the scrollbar is trying to use.

**Comment by Piinks** [comment]
Something along the lines of 3 sounds good to me! Thank you for continuing to work on this and making the error messaging better! :)

You could probably take most of the error from the `isAlwaysShown` and put it in a method to reuse here and there.

**Comment by davidmartos96** [comment]
@Piinks I've updated the PR and tests with the suggestions

**Comment by davidmartos96** [comment]
I've been thinking a bit more about this. Do you think we should have this assertion check when building the scrollbar for the first time?. In the same place as the `isAlwaysShown` check, but unconditionally. https://github.com/flutter/flutter/blob/d27a942730fdddf5d2224c2c7ccee9f0f459cee2/packages/flutter/lib/src/widgets/scrollbar.dart#L955
Otherwise, even if the error is more explicit now, it will only be shown when using the thumb or the track gestures + an incorrect injection of the controller. That has low chances of being noticed while developing. 
I think it would be better if users notice that they have something wrong in the scrollbar as early as possible. I've been using them incorrectly for over 2 years without noticing :sweat_smile:  
What do you think?

**Comment by Piinks** [comment]
I think that sounds like a great idea! If RawScrollbar.interactive is true, we could definitely surface that error sooner for gestures. You can have a scrollbar that is not interactive, but isAlwaysShown, so I think those would be two separate checks still.

**Comment by davidmartos96** [comment]
> I think that sounds like a great idea!

@Piinks Great! I think it's ready for review now.

**Comment by davidmartos96** [comment]
I had to update how both scroll controllers from `CupertinoAlertDialog` y `CupertinoActionSheet` are passed to the scrollbar. Otherwise they are technically misconfigured because 2 scrollbars are using the `PrimaryScrollController` at the same time, which this PR warns now about. It's a bit of an edge case because those widgets usually don't need a scrollbar.

**Comment by davidmartos96** [comment]
@Piinks Any update on this?

File: packages/flutter/test/material/scrollbar_test.dart [hunk 1]
```diff
@@ -1051,8 +1051,9 @@ void main() {
           ),
           child: Scrollbar(
             controller: controller,
-            child: const SingleChildScrollView(
-              child: SizedBox(width: 4000.0, height: 4000.0),
+            child: SingleChildScrollView(
+              controller: controller,
+              child: const SizedBox(width: 4000.0, height: 4000.0),
```
Comment (Piinks) [inline packages/flutter/test/material/scrollbar_test.dart:1056]: NICE

**Review by Piinks — COMMENTED** [review]
Hey @davidmartos96, apologies for the delay. I've been away for a bit. Can you add tests for the changes to the Cupertino widgets you have made here?

File: packages/flutter/test/material/scrollbar_test.dart (hunk 1 above)
Comment (davidmartos96) [reply packages/flutter/test/material/scrollbar_test.dart:1056]: No problem! What kind of test are you thinking of? Actually, I had to add the small extra code so that the current Cupertino tests pass. Maybe the current tests are enough?

**Comment by davidmartos96** [comment]
I've included 2 tests that check that the controllers used internally are different because the primary one can't be attached to multiple scroll views at the same time.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you for the contribution!

**Comment by dnfield** [comment]
It looks like this PR introduced issues for flutter_gallery. For example, just running flutter_gallery ends up triggering asserts introduced by this PR now.

**Comment by dnfield** [comment]
I thould add that this seems to only happen on macOS desktop.

**Comment by davidmartos96** [comment]
@dnfield I've just tested the flutter_gallery on Linux and I also get the asserts. But I'd say it is a legitimate warning. If you disable the asserts you will notice that scrolling with a mouse press in the main scroll in the home screen doesn't work. 
From what I debugged that is because the PrimaryScrollController is being shared by multiple pieces of the UI at the same time, in particular: 
* The main scroll in the home page
* The scroll inside the settings
* Each of the 3 categories scrolls (Material, Cupertino and "Styles & Other")

The fact that it is such an "invisible" bug was the main reason I tried to improve the situation with this PR by warning about it. Everything works normally but it fails when interacting with the scrollbar either with the thumb on mobile or with the mouse on desktop.
Maybe @Piinks has some more information about this. The PR doesn't change the previous behavior, rather warns about the situation beforehand.

As an extra note, I think it will be great to further improve the message by including the location of the failing widget. In the case of the Flutter Gallery just in the home screen there are 5-6 active scrolls, so knowing which one is failing is very precious information.
I don't know who in the team has some expertise with how the Flutter errors and diagnostic nodes work so that the message can be improved. I asked on Discord the other day https://discord.com/channels/608014603317936148/608021234516754444/853999114018750484

**Comment by Piinks** [comment]
> scrolling with a mouse press in the main scroll in the home screen doesn't work.

Can you confirm if this means trying to drag the scrollable with the mouse pointer? That is most likely disabled by ScrollBehavior.dragDevices on desktop if that is the case. 

I'm filing a bug for this so we can discuss further, will link back in a sec

**Comment by Piinks** [comment]
Also just connecting discussions - this came up here: https://discord.com/channels/608014603317936148/608021234516754444/854798350246215751

**Comment by Piinks** [comment]
Let's follow-up here: https://github.com/flutter/gallery/issues/523

**Comment by davidmartos96** [comment]
> dragDevices

Yes, it is by dragging with the mouse pointer. Running the app on profile (no asserts) on Linux desktop will throw when dragging the thumb.

image

**Comment by nt4f04uNd** [comment]
Could you please also check out this related issue https://github.com/flutter/flutter/issues/84735

**Comment by Piinks** [comment]
> Could you please also check out this related issue #84735

Followed up there.
