### PR TITLE
Check cross imports test subfolders

### LINKED ISSUE #185464: (Test cross-imports) The cross imports checker does not verify cross imports in flutter/xyz directories
### Steps to reproduce

1. Open https://github.com/flutter/flutter/pull/185271
2. Notice that the contributor found violations in `flutter/test/gestures` or `flutter/test/painting`
3. The cross imports checker did not flag this, since it only checks `widgets` / `material` / `cupertino`

### Expected results

The cross imports checker should flag any violations of the `flutter/material` and `flutter/cupertino` imports, including in supporting framework code, such as `flutter/gestures` or `flutter/animation`

See https://github.com/flutter/flutter/issues/177415

### Actual results

The cross imports checker did not flag this.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.44.0-1.0.pre-210, on macOS 26.3.1 25D771280a darwin-arm64, locale en-US) [2.0s]
    ! Flutter version 3.44.0-1.0.pre-210 on channel [user-branch] at /Users/navaronbracke/Documents/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/setup.
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision 36e08d0607 (5 hours ago), 2026-04-23 00:11:27 -0400
    • Engine revision 36e08d0607
    • Dart version 3.13.0 (build 3.13.0-53.0.dev)
    • DevTools version 2.57.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, enable-swift-package-manager,
      omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration, enable-riscv64
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0) [1,452ms]
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Emulator version 36.4.9.0 (build_id 14788078) (CL:N/A)
    • Platform android-36.1, build-tools 36.1.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.9+-14787801-b1163.94)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.4.1) [971ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17E202
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [6ms]
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [6.8s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 26.3.1 25D771280a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 147.0.7727.103
    ! Error: Browsing on the local area network for RudyB. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [487ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR extends the tests cross imports check to also verify cross imports in `flutter/test` itself and its subdirectories. It now also validates `.dart` files, such as `flutter/test/gesture_utils.dart`, instead of only `_test.dart` files.

The underlying test was rewritten a bit to accomodate this.
The known cross imports have been rebaselined, to account for the new checks.

Currently the cross imports check does not validate subdirectories of `flutter/test/xyz` (for example `flutter/test/gestures/utils`), because at this time there are no such subdirectories, beyond directories inside `flutter/test` itself. 

Fixes https://github.com/flutter/flutter/issues/185464

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

If this change needs to override an active code freeze, provide a comment explaining why. The code freeze workflow can be overridden by code reviewers. See pinned issues for any active code freezes with guidance.

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 1]
```diff
@@ -14,61 +14,18 @@ import 'common.dart';
 
 void main() {
   late TestsCrossImportChecker checker;
-  late Directory testWidgetsDirectory;
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:17]: testWidget/testCupertino have moved and are now grouped with related directories to check

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 2]
```diff
@@ -254,3 +183,160 @@ Future<String> capture(AsyncVoidCallback callback, {bool shouldHaveErrors = fals
     return buffer.toString();
   }
 }
+
+File getFile(String filepath, Directory directory) {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:329]: This is moved from the function above

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 3]
```diff
@@ -254,3 +183,160 @@ Future<String> capture(AsyncVoidCallback callback, {bool shouldHaveErrors = fals
...
+void writeImport(File file, [String importString = "import 'package:flutter/material.dart';"]) {
+  file
+    ..createSync(recursive: true)
+    ..writeAsStringSync(importString);
+}
+
+/// Writes [importString] into the given [filePaths] in [inDirectory].
+///
+/// The default [importString] is `import 'package:flutter/material.dart';`.
+void writeImportInFiles(
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:354]: This is a refactor of the original for-loop, so that we can specify the directory / import string

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 4]
```diff
@@ -254,3 +183,160 @@ Future<String> capture(AsyncVoidCallback callback, {bool shouldHaveErrors = fals
...
+  String importString = "import 'package:flutter/material.dart';",
+}) {
+  for (final filepath in filePaths) {
+    writeImport(getFile(filepath, inDirectory), importString);
+  }
+}
+
+// A utility that keeps track of the directories under test,
+// to avoid having to late initialize them individually in `setUp()`.
+class _CrossImportsTestDirectories {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:366]: Since we now have a bunch more dirs to check, I opted to group this here

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 5]
```diff
@@ -254,3 +183,160 @@ Future<String> capture(AsyncVoidCallback callback, {bool shouldHaveErrors = fals
...
+  }
+}
+
+// A mapping of test cases for the cross imports checker.
+//
+// Each entry contains:
+// - a shortened directory name of the test folder for the library, without the `flutter/` prefix
+// - the name of the known cross imports list variable in `check_tests_cross_imports.dart` for that library
+// - the actual known cross imports list for that library
+// dart format off
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:482]: The max line length is 100, but this goes over that a little bit :/

I do like it formatted like this, though, but I can remove the `dart format` comment if requested

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 6]
```diff
@@ -14,61 +14,18 @@ import 'common.dart';
...
+        in checkerDirectories.knownFiles.entries) {
       for (final filepath in files) {
         if (excludes.contains(filepath)) {
           continue;
         }
         writeImport(getFile(filepath, directory));
       }
     }
-
-    for (final filepath in extraWidgetsImportingMaterial) {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:60]: This was moved out of this function and is now done by the tests themselves

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 7]
```diff
@@ -107,121 +62,95 @@ void main() {
     expect(success, isTrue);
   });
 
-  test('when not all widgets knowns have cross imports', () async {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:110]: This test and `when not all cupertino knowns have cross imports` are now the same test

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 8]
```diff
@@ -107,121 +62,95 @@ void main() {
...
-      '║ However, they now need to be removed from the',
-      '║ knownCupertinoCrossImports list in the script /dev/bots/check_tests_cross_imports.dart.',
-      '╚═══════════════════════════════════════════════════════════════════════════════',
-    ].join('\n');
-    expect(result, equals('$lines\n'));
-    expect(success, isFalse);
-  });
+      final String excludedSample = knownCrossImports.first;
 
-  test('unknown Widgets cross import of Material', () async {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:151]: This test and `unknown Widgets cross import of Cupertino`/ `unknown Cupertino cross importing Material` are now the same test, but with support for the other directories, and the test cases switch between "Material" and "Cupertino"

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 9]
```diff
@@ -107,121 +67,242 @@ void main() {
...
+              ]
+              .map((String line) {
+                return line.replaceAll('/', Platform.pathSeparator);
+              })
+              .join('\n');
+      expect(result, equals('$lines\n'));
+      expect(success, isFalse);
+    });
+
+    test('multiple unknown $libraryName cross imports of Material', () async {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:142]: We didn't actually validate the error messages for N+1

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 10]
```diff
@@ -107,121 +67,242 @@ void main() {
...
+              ]
+              .map((String line) {
+                return line.replaceAll('/', Platform.pathSeparator);
+              })
+              .join('\n');
+      expect(result, equals('$lines\n'));
+      expect(success, isFalse);
+    });
+
+    test('unknown $libraryName cross import of Material in non-test file', () async {
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:169]: This is a regression test for the updated file regex

File: dev/bots/check_tests_cross_imports.dart [hunk 11]
```diff
@@ -135,88 +136,164 @@ class TestsCrossImportChecker {
...
+  /// and `knownSchedulerCrossImports` corresponds to `flutter/test/scheduler`.
   // TODO(justinmc): Fix all of these tests so there are no cross imports.
   // See https://github.com/flutter/flutter/issues/177028.
+  static final Set<String> knownAnimationCrossImports = <String>{
+    'packages/flutter/test/animation/animation_sheet_test.dart',
+    'packages/flutter/test/animation/live_binding_test.dart',
+  };
   static final Set<String> knownCupertinoCrossImports = <String>{};
+  static final Set<String> knownDartCrossImports = <String>{};
+  static final Set<String> knownExamplesCrossImports = <String>{};
```
Comment (Piinks) [inline dev/bots/check_tests_cross_imports.dart:158]: Are these examples as in the api examples? I think cross imports might be ok there. We usually want examples to look nice and they can have a larger scope than just the enclosing library.

File: dev/bots/test/check_tests_cross_imports_test.dart (hunk 9 above)
Comment (Piinks) [reply dev/bots/test/check_tests_cross_imports_test.dart:142]: Good catch!

**Review by Piinks — DISMISSED** [review]
This LGTM - G recommended adding these additional regression tests:

<details> <summary> Regression tests </summary>

```dart
test('TestsCrossImportChecker ignores non-Dart files even if path contains .dart', () async {
    final fs = MemoryFileSystem();

    // Create a mock Flutter root and test directory
    final Directory flutterRoot = fs.directory('/flutter')..createSync();
    final Directory testsDir =
        flutterRoot.childDirectory('packages').childDirectory('flutter').childDirectory('test')
          ..createSync(recursive: true);

    // Create a directory that has '.dart' in its name
    final Directory specialDir = testsDir.childDirectory('widgets.dart_utils')..createSync();

    // Create a non-Dart file in that directory with a disallowed import
    // If the checker incorrectly matches this file, it will fail the check.
    final File nonDartFile = specialDir.childFile('README.txt')..createSync();
    nonDartFile.writeAsStringSync("import 'package:flutter/material.dart';");

    final checker = TestsCrossImportChecker(
      testsDirectory: testsDir,
      flutterRoot: flutterRoot,
      filesystem: fs,
    );

    // We don't need to 'capture' output here since we expect success (no errors printed)
    final bool success = checker.check();

    expect(
      success,
      isTrue,
      reason: 'The checker should have ignored README.txt despite the disallowed import.',
    );
  });

  test('TestsCrossImportChecker still catches disallowed imports in actual .dart files', () async {
    final fs = MemoryFileSystem();
    final Directory flutterRoot = fs.directory('/flutter')..createSync();
    final Directory testsDir =
        flutterRoot.childDirectory('packages').childDirectory('flutter').childDirectory('test')
          ..createSync(recursive: true);

    final Directory widgetsDir = testsDir.childDirectory('widgets')..createSync();
    final File testFile = widgetsDir.childFile('foo_test.dart')..createSync();
    testFile.writeAsStringSync("import 'package:flutter/material.dart';");

    final checker = TestsCrossImportChecker(
      testsDirectory: testsDir,
      flutterRoot: flutterRoot,
      filesystem: fs,
    );

    final bool success = checker.check();
    expect(
      success,
      isFalse,
      reason: 'The checker should have caught the disallowed import in a .dart file.',
    );
  });
```

</details>

File: dev/bots/check_tests_cross_imports.dart (hunk 11 above)
Comment (navaronbracke) [reply dev/bots/check_tests_cross_imports.dart:158]: I'm not sure what the context is for this directory, but it only contains this one: https://github.com/flutter/flutter/blob/master/packages/flutter/test/examples/sector_layout_test.dart

Comment (Piinks) [reply dev/bots/check_tests_cross_imports.dart:158]: Ah I missed that! All good then. What an odd test in there. :)

**Comment by navaronbracke** [comment]
The test `TestsCrossImportChecker still catches disallowed imports in actual .dart files` seems a bit redundant to me though, since the existing tests that verify the error output already cover that.

But I do agree about the other suggestions!

**Comment by navaronbracke** [comment]
Added the tests!

**Review by Piinks — DISMISSED** [review]
LGTM

**Review by AbdeMohlbi — DISMISSED** [review]

**Comment by navaronbracke** [comment]
Thanks to @AbdeMohlbi for pointing me in the direction of a subtle formatter bug regarding comments at the end of the  skip parameter (the formatter includes the comment for its line length check :/ )

I added a small `isCupertino(String libraryName)` function in the cross imports checker, to both deduplicate the argument for the `skip` parameter and keep the formatter happy.

Now dev/bots/analyze.dart no longer complains about missing test skip comments :)

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 12]
```diff
@@ -107,121 +67,262 @@ void main() {
...
+          '║ Huzzah! The following tests in $libraryName no longer contain cross imports!',
+          '║   $excludedSample',
+          '║ However, they now need to be removed from the',
+          '║ $knownCrossImportsListName list in the script /dev/bots/check_tests_cross_imports.dart.',
+          '╚═══════════════════════════════════════════════════════════════════════════════',
+        ].join('\n');
+        expect(result, equals('$lines\n'));
+        expect(success, isFalse);
+      },
+      skip: knownCrossImports.isEmpty, // [intended]: Nothing to log if there are no known imports
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:114]: I made this skip message a little shorter, to fit in the 100 characters limit

File: dev/bots/test/check_tests_cross_imports_test.dart [hunk 13]
```diff
@@ -107,121 +67,262 @@ void main() {
...
+                  '╚═══════════════════════════════════════════════════════════════════════════════',
+                ]
+                .map((String line) {
+                  return line.replaceAll('/', Platform.pathSeparator);
+                })
+                .join('\n');
+        expect(result, equals('$lines\n'));
+        expect(success, isFalse);
+      },
+      skip: isCupertino(libraryName), // [intended]: Cupertino can import itself
```
Comment (navaronbracke) [inline dev/bots/test/check_tests_cross_imports_test.dart:223]: This one and the others now use the utility to stay below the 100 characters for the formatter

**Comment by AbdeMohlbi** [comment]
@navaronbracke some tests are failing

**Comment by navaronbracke** [comment]
Ahhh, Windows path separators!

**Comment by navaronbracke** [comment]
There was a small mistake around the test expectation still. I'll do a dry run of the tests on my Windows machine, before stamping this with the CICD label again.

**Comment by navaronbracke** [comment]
Passes locally on my Windows machine now, so we can try this again.

**Review by Piinks — APPROVED** [review]
LGTM

**Review by AbdeMohlbi — APPROVED** [review]
Mask LGTM
