### PR TITLE
Fix HEIF decoding

### LINKED ISSUE #176407: HEIC image with vertical flip displays incorrectly via the Image widget (on Android 15 or lower) or outright fails (on Android 16)
### Steps to reproduce

1. Clone https://github.com/rajveermalviya/test_image_viewer
2. Run the app on iOS
3. Run the app on Android 15
4. Run the app on Android 16

### Expected results

On Android, regardless of the Android version, the image should be visible correctly as seen on iOS or the below provided screenshot.

<details><summary>Screenshot of macOS Preview app</summary>
<p>

Image

</p>
</details>

### Actual results

On iOS, the image is displayed correctly.

On Android 15 or lower the sample image fails silently, the Image widget displays the HEIC image without applying the vertical flip, which is specified in the EXIF.

On Android 16, the Image widget reports an "Could not decompress image" exception.

### Code sample

https://github.com/rajveermalviya/test_image_viewer

### Screenshots or Video

| iOS Simulator | Android 15 emulator | Android 16 emulator |
| - | - | - |
| Image | Image | Image |

### Logs

<details open><summary>Logs for Android 16 emulator</summary>

```console
$ flutter run
Resolving dependencies... 
Downloading packages... 
  characters 1.4.0 (1.4.1 available)
  material_color_utilities 0.11.1 (0.13.0 available)
Got dependencies!
2 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...                              7.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...          359ms
D/FlutterJNI( 4094): Beginning load of flutter...
D/FlutterJNI( 4094): flutter (null) was loaded normally!
I/flutter ( 4094): [IMPORTANT:flutter/shell/platform/android/android_context_gl_impeller.cc(104)] Using the Impeller rendering backend (OpenGLES).
Syncing files to device sdk gphone64 arm64...                       46ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 arm64 is available at: http://127.0.0.1:63676/mQrM9ihcFIQ=/
The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:63676/mQrM9ihcFIQ=/
I/WindowExtensionsImpl( 4094): Initializing Window Extensions, vendor API level=9, activity embedding enabled=true
I/st_image_viewer( 4094): Compiler allocated 5111KB to compile void android.view.ViewRootImpl.performTraversals()
D/CCodec  ( 4094): allocate(c2.android.hevc.decoder)
I/ApexCodecsLazy( 4094): Failed to load libcom.android.media.swcodec.apexcodecs.so: dlopen failed: library "libcom.android.media.swcodec.apexcodecs.so" not found
I/Codec2Client( 4094): Available Codec2 services: "default" "software"
I/CCodec  ( 4094): setting up 'default' as default (vendor) store
D/WindowLayoutComponentImpl( 4094): Register WindowLayoutInfoListener on Context=com.example.test_image_viewer.MainActivity@8fbd7c4, of which baseContext=android.app.ContextImpl@dd7962e
I/CCodec  ( 4094): Created component [c2.android.hevc.decoder] for [c2.android.hevc.decoder]
D/CCodecConfig( 4094): read media type: video/hevc
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): ignored struct field coded.color-format.locations
D/CCodecConfig( 4094): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig( 4094): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater( 4094): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is Dict {
D/CCodecConfig( 4094):   c2::u32 coded.pl.level = 24584
D/CCodecConfig( 4094):   c2::u32 coded.pl.profile = 24576
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 default.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 default.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 default.color.range = 0
D/CCodecConfig( 4094):   c2::u32 default.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 input.buffers.max-size.value = 2097152
D/CCodecConfig( 4094):   c2::u32 input.delay.value = 0
D/CCodecConfig( 4094):   string input.media-type.value = "video/hevc"
D/CCodecConfig( 4094):   c2::u32 output.delay.value = 8
D/CCodecConfig( 4094):   string output.media-type.value = "video/raw"
D/CCodecConfig( 4094):   c2::u32 raw.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.range = 2
D/CCodecConfig( 4094):   c2::u32 raw.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 raw.max-size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 320
D/CCodecConfig( 4094):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig( 4094):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig( 4094):   c2::i32 raw.rotation.value = 0
D/CCodecConfig( 4094):   c2::u32 raw.sar.height = 1
D/CCodecConfig( 4094):   c2::u32 raw.sar.width = 1
D/CCodecConfig( 4094):   c2::u32 raw.size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 320
D/CCodecConfig( 4094):   c2
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
E/MediaCodec( 4094): Media Quality Service not found.
D/CCodec  ( 4094): [c2.android.hevc.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 4094): no c2 equivalents for color-format
D/CCodecConfig( 4094): no c2 equivalents for flags
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
W/Codec2Client( 4094): query -- param skipped: index = 1107298332.
D/CCodec  ( 4094): client requested max input size 73985, which is smaller than what component recommended (2097152); overriding with component recommendation.
W/CCodec  ( 4094): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 4094): encoding statistics level = 0
D/CCodec  ( 4094): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t level = 65536
D/CCodec  ( 4094):   int32_t max-input-size = 2097152
D/CCodec  ( 4094):   string mime = "video/hevc"
D/CCodec  ( 4094):   int32_t profile = 1
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094): }
D/CCodec  ( 4094): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t android._color-format = 2135033992
D/CCodec  ( 4094):   int32_t android._video-scaling = 1
D/CCodec  ( 4094):   int32_t rotation-degrees = 0
D/CCodec  ( 4094):   int32_t color-standard = 0
D/CCodec  ( 4094):   int32_t color-range = 2
D/CCodec  ( 4094):   int32_t color-transfer = 0
D/CCodec  ( 4094):   int32_t sar-height = 1
D/CCodec  ( 4094):   int32_t sar-width = 1
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t max-height = 240
D/CCodec  ( 4094):   int32_t max-width = 320
D/CCodec  ( 4094):   string mime = "video/raw"
D/CCodec  ( 4094):   int32_t android._dataspace = 268435456
D/CCodec  ( 4094):   int32_t color-format = 2135033992
D/CCodec  ( 4094): }
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.max-size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
E/st_image_viewer( 4094): Failed to query component interface for required system resources: 6
W/Codec2Client( 4094): query -- param skipped: index = 1342179345.
W/Codec2Client( 4094): query -- param skipped: index = 2415921170.
W/Codec2Client( 4094): query -- param skipped: index = 1610614798.
D/C2Store ( 4094): Using DMABUF Heaps
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#634] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#634] Configured output block pool ids 1 => OK
I/DMABUFHEAPS( 4094): Using DMA-BUF heap named: system
D/CCodecConfig( 4094): c2 config diff is   c2::u32 output.delay.value = 0
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
D/Codec2-OutputBufferQueue( 4094): set max dequeue count 12 from update
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.color.matrix = 3
D/CCodecConfig( 4094):   c2::u32 raw.color.primaries = 8
D/CCodecConfig( 4094):   c2::u32 raw.color.range = 1
D/CCodecConfig( 4094):   c2::u32 raw.color.transfer = 3
D/CCodecConfig( 4094):   c2::u32 raw.crop.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.crop.left = 0
D/CCodecConfig( 4094):   c2::u32 raw.crop.top = 0
D/CCodecConfig( 4094):   c2::u32 raw.crop.width = 512
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:2D-BB-Output] popFromStashAndRegister: at 0us, output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers( 4094):   int32_t android._color-format = 2135033992
D/CCodecBuffers( 4094):   int32_t android._video-scaling = 1
D/CCodecBuffers( 4094):   int32_t rotation-degrees = 0
D/CCodecBuffers( 4094):   int32_t color-standard = 10
D/CCodecBuffers( 4094):   int32_t color-range = 1
D/CCodecBuffers( 4094):   int32_t color-transfer = 3
D/CCodecBuffers( 4094):   int32_t sar-height = 1
D/CCodecBuffers( 4094):   int32_t sar-width = 1
D/CCodecBuffers( 4094):   Rect crop(0, 0, 511, 511)
D/CCodecBuffers( 4094):   int32_t width = 512
D/CCodecBuffers( 4094):   int32_t height = 512
D/CCodecBuffers( 4094):   int32_t max-height = 512
D/CCodecBuffers( 4094):   int32_t max-width = 512
D/CCodecBuffers( 4094):   string mime = "video/raw"
D/CCodecBuffers( 4094):   int32_t android._dataspace = 147456000
D/CCodecBuffers( 4094):   int32_t color-format = 2135033992
D/CCodecBuffers( 4094): }
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:2D-BB-Output] updating image-data
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:2D-BB-Output] updating stride = 512, width: 512, height: 512
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:2D-BB-Output] updating vstride = 640
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/InsetsController( 4094): hide(ime(), fromIme=false)
I/ImeTracker( 4094): com.example.test_image_viewer:ec4382f: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:Output[N]] updating image-data
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:Output[N]] updating stride = 512, width: 512, height: 512
D/CCodecBuffers( 4094): [c2.android.hevc.decoder#634:Output[N]] updating vstride = 512
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/Codec2Buffer( 4094): ConstGraphicBlockBuffer::canCopy: wrapped ; buffer ref doesn't exist
D/CCodec  ( 4094): allocate(c2.android.hevc.decoder)
I/CCodec  ( 4094): setting up 'default' as default (vendor) store
I/CCodec  ( 4094): Created component [c2.android.hevc.decoder] for [c2.android.hevc.decoder]
D/CCodecConfig( 4094): read media type: video/hevc
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): ignored struct field coded.color-format.locations
D/CCodecConfig( 4094): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig( 4094): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater( 4094): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is Dict {
D/CCodecConfig( 4094):   c2::u32 coded.pl.level = 24584
D/CCodecConfig( 4094):   c2::u32 coded.pl.profile = 24576
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 default.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 default.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 default.color.range = 0
D/CCodecConfig( 4094):   c2::u32 default.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 input.buffers.max-size.value = 2097152
D/CCodecConfig( 4094):   c2::u32 input.delay.value = 0
D/CCodecConfig( 4094):   string input.media-type.value = "video/hevc"
D/CCodecConfig( 4094):   c2::u32 output.delay.value = 8
D/CCodecConfig( 4094):   string output.media-type.value = "video/raw"
D/CCodecConfig( 4094):   c2::u32 raw.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.range = 2
D/CCodecConfig( 4094):   c2::u32 raw.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 raw.max-size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 320
D/CCodecConfig( 4094):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig( 4094):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig( 4094):   c2::i32 raw.rotation.value = 0
D/CCodecConfig( 4094):   c2::u32 raw.sar.height = 1
D/CCodecConfig( 4094):   c2::u32 raw.sar.width = 1
D/CCodecConfig( 4094):   c2::u32 raw.size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 320
D/CCodecConfig( 4094):   c2
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
E/MediaCodec( 4094): Media Quality Service not found.
D/CCodec  ( 4094): [c2.android.hevc.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 4094): no c2 equivalents for color-format
D/CCodecConfig( 4094): no c2 equivalents for flags
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
W/Codec2Client( 4094): query -- param skipped: index = 1107298332.
D/CCodec  ( 4094): client requested max input size 9517, which is smaller than what component recommended (2097152); overriding with component recommendation.
W/CCodec  ( 4094): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 4094): encoding statistics level = 0
D/CCodec  ( 4094): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t level = 65536
D/CCodec  ( 4094):   int32_t max-input-size = 2097152
D/CCodec  ( 4094):   string mime = "video/hevc"
D/CCodec  ( 4094):   int32_t profile = 1
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094): }
D/CCodec  ( 4094): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t android._color-format = 2135033992
D/CCodec  ( 4094):   int32_t android._video-scaling = 1
D/CCodec  ( 4094):   int32_t rotation-degrees = 0
D/CCodec  ( 4094):   int32_t color-standard = 0
D/CCodec  ( 4094):   int32_t color-range = 2
D/CCodec  ( 4094):   int32_t color-transfer = 0
D/CCodec  ( 4094):   int32_t sar-height = 1
D/CCodec  ( 4094):   int32_t sar-width = 1
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t max-height = 240
D/CCodec  ( 4094):   int32_t max-width = 320
D/CCodec  ( 4094):   string mime = "video/raw"
D/CCodec  ( 4094):   int32_t android._dataspace = 268435456
D/CCodec  ( 4094):   int32_t color-format = 2135033992
D/CCodec  ( 4094): }
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.max-size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
E/st_image_viewer( 4094): Failed to query component interface for required system resources: 6
W/Codec2Client( 4094): query -- param skipped: index = 1342179345.
W/Codec2Client( 4094): query -- param skipped: index = 2415921170.
W/Codec2Client( 4094): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] Configured output block pool ids 1 => OK
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] work failed to complete: 14
E/MediaCodec( 4094): Codec reported err 0xe/14 (Unknown error -14), actionCode 0, while in state 6/STARTED
E/MediaCodec( 4094): Invalid to call at Released state; only valid in executing state
E/AMessage( 4094): trying to post a duplicate reply
E/NdkMediaCodec( 4094): untranslated sf error code: -38
E/MediaCodec( 4094): Invalid to call at Released state; only valid in executing state
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#485] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 4094): onLastStrongRef automatically unlinking death recipients
D/MediaCodecList( 4094): codecHandlesFormat: no format, so no extra checks
D/MediaCodecList( 4094): codecHandlesFormat: no format, so no extra checks
D/CCodec  ( 4094): allocate(c2.goldfish.hevc.decoder)
I/CCodec  ( 4094): setting up 'default' as default (vendor) store
I/CCodec  ( 4094): Created component [c2.goldfish.hevc.decoder] for [c2.goldfish.hevc.decoder]
D/CCodecConfig( 4094): read media type: video/hevc
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater( 4094): ignored struct field coded.color-format.locations
D/ReflectedParamUpdater( 4094): ignored struct field resources.needed.values
D/CCodecConfig( 4094): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig( 4094): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater( 4094): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is Dict {
D/CCodecConfig( 4094):   c2::u32 coded.pl.level = 24584
D/CCodecConfig( 4094):   c2::u32 coded.pl.profile = 24576
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig( 4094):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 default.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 default.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 default.color.range = 0
D/CCodecConfig( 4094):   c2::u32 default.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 input.buffers.max-size.value = 6291456
D/CCodecConfig( 4094):   c2::u32 input.delay.value = 0
D/CCodecConfig( 4094):   string input.media-type.value = "video/hevc"
D/CCodecConfig( 4094):   c2::u32 output.delay.value = 8
D/CCodecConfig( 4094):   string output.media-type.value = "video/raw"
D/CCodecConfig( 4094):   c2::u32 raw.color.matrix = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.primaries = 0
D/CCodecConfig( 4094):   c2::u32 raw.color.range = 2
D/CCodecConfig( 4094):   c2::u32 raw.color.transfer = 0
D/CCodecConfig( 4094):   c2::u32 raw.max-size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 320
D/CCodecConfig( 4094):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig( 4094):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig( 4094):   c2::i32 raw.rotation.value = 0
D/CCodecConfig( 4094):   c2::u32 raw.sar.height = 1
D/CCodecConfig( 4094):   c2::u32 raw.sar.width = 1
D/CCodecConfig( 4094):   c2::u32 raw.size.height = 240
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 320
D/CCodecConfig( 4094):   c2
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
E/MediaCodec( 4094): Media Quality Service not found.
D/CCodec  ( 4094): [c2.goldfish.hevc.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 4094): no c2 equivalents for color-format
D/CCodecConfig( 4094): no c2 equivalents for flags
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
W/Codec2Client( 4094): query -- param skipped: index = 1107298332.
D/CCodec  ( 4094): client requested max input size 9517, which is smaller than what component recommended (6291456); overriding with component recommendation.
W/CCodec  ( 4094): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 4094): encoding statistics level = 0
D/CCodec  ( 4094): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t level = 65536
D/CCodec  ( 4094):   int32_t max-input-size = 6291456
D/CCodec  ( 4094):   string mime = "video/hevc"
D/CCodec  ( 4094):   int32_t profile = 1
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094): }
D/CCodec  ( 4094): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 4094):   int32_t android._color-format = 2135033992
D/CCodec  ( 4094):   int32_t android._video-scaling = 1
D/CCodec  ( 4094):   int32_t rotation-degrees = 0
D/CCodec  ( 4094):   int32_t color-standard = 0
D/CCodec  ( 4094):   int32_t color-range = 2
D/CCodec  ( 4094):   int32_t color-transfer = 0
D/CCodec  ( 4094):   int32_t sar-height = 1
D/CCodec  ( 4094):   int32_t sar-width = 1
D/CCodec  ( 4094):   Rect crop(0, 0, 511, 511)
D/CCodec  ( 4094):   int32_t width = 512
D/CCodec  ( 4094):   int32_t height = 512
D/CCodec  ( 4094):   int32_t max-height = 240
D/CCodec  ( 4094):   int32_t max-width = 320
D/CCodec  ( 4094):   string mime = "video/raw"
D/CCodec  ( 4094):   int32_t android._dataspace = 268435456
D/CCodec  ( 4094):   int32_t color-format = 2135033992
D/CCodec  ( 4094): }
I/CCodecConfig( 4094): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4094): c2 config diff is   c2::u32 raw.max-size.height = 512
D/CCodecConfig( 4094):   c2::u32 raw.max-size.width = 512
W/ColorUtils( 4094): expected specified color aspects (2:0:0:0)
W/Codec2Client( 4094): query -- param skipped: index = 1342179345.
W/Codec2Client( 4094): query -- param skipped: index = 2415921170.
W/Codec2Client( 4094): query -- param skipped: index = 1610614798.
W/Codec2Client( 4094): query -- param skipped: index = 2684356609.
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] Configured output block pool ids 1 => OK
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] work failed to complete: 14
E/MediaCodec( 4094): Codec reported err 0xe/14 (Unknown error -14), actionCode 0, while in state 6/STARTED
E/MediaCodec( 4094): Pending dequeue output buffer request cancelled
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 4094): [c2.goldfish.hevc.decoder#485] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 4094): onLastStrongRef automatically unlinking death recipients
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#634] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 4094): [c2.android.hevc.decoder#634] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 4094): onLastStrongRef automatically unlinking death recipients
E/FlutterJNI( 4094): Failed to decode image
E/FlutterJNI( 4094): java.io.IOException: getPixels failed with error invalid input
E/FlutterJNI( 4094):    at android.graphics.ImageDecoder.nDecodeBitmap(Native Method)
E/FlutterJNI( 4094):    at android.graphics.ImageDecoder.decodeBitmapInternal(ImageDecoder.java:1676)
E/FlutterJNI( 4094):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1865)
E/FlutterJNI( 4094):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1850)
E/FlutterJNI( 4094):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:557)

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: Could not decompress image.

When the exception was thrown, this was the stack

Image provider: AssetImage(bundle: null, name: "assets/image.heic")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#87408(), name: "assets/image.heic",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

D/ProfileInstaller( 4094): Installing profile for com.example.test_image_viewer

Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.37.0-1.0.pre-175, on macOS 26.0.1 25A362 darwin-arm64, locale en-IN) [529ms]
    ! Flutter version 3.37.0-1.0.pre-175 on channel [user-branch] at /Users/rajveer/sdk/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 2e51c3f343 (2 weeks ago), 2025-09-17 16:20:45 -0700
    • Engine revision 2e51c3f343
    • Dart version 3.10.0 (build 3.10.0-213.0.dev)
    • DevTools version 2.50.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,425ms]
    • Android SDK at /Users/rajveer/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/rajveer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1) [1,044ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A400
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [6.2s]
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 16 (API 36) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 26.0.1 25A362 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 140.0.7339.214

[✓] Network resources [519ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by mboetger**
Fixing two HEIF decoding issues on Android:

API 36: ImageDecoder has a known issue decoding HEIF images with certain gain maps.  Image won't load. The workaround is to use BitmapFactory instead.

Pre-36: HEIF Flipping did not work.  Image is upside.

|  |Before | After |
|---|---|---|
| Api 36 | Screenshot_20251010_151132 | Screenshot_20251010_150551 |
| Pre Api 36 | Screenshot_20251010_150752 | Screenshot_20251010_150703 |

Fixes: #176407

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by mboetger** [comment]
@gmackall - I tried to get the flipping metadata a couple of different ways, but the Exif was the only one that worked.  I think that's fine as we have verification that flipping does not work pre-36.  And since we are applying it ourselves in 36, it's still fine. 

I've been told a fix is in the works, so I'm hoping things will work in 37.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+/** Reads EXIF metadata from an image. */
+@RequiresApi(io.flutter.Build.API_LEVELS.API_28)
+class ExifMetadataReader {
+  private static final String TAG = "ExifMetadataReader";
+
+  /**
+   * Reads the EXIF metadata from the given byte array and populates the provided {@link Metadata}
+   * object.
+   *
+   * @param bytes The byte array containing the image data.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java]: Can you expand on what formats of byte array data are accepted here?

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
+package io.flutter.embedding.engine.image;
+
+import android.graphics.Bitmap;
+import android.os.Build;
+import androidx.annotation.NonNull;
+import androidx.annotation.RequiresApi;
+import java.nio.ByteBuffer;
+
+interface FlutterImageDecoderImpl {
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java]: maybe it is just me but this naming feels weird. An *impl class that is not only not an implementation but a package private interface?

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+import android.graphics.BitmapFactory;
+import android.graphics.Matrix;
+import androidx.annotation.RequiresApi;
+import java.nio.ByteBuffer;
+
+/**
+ * An implementation of {@link FlutterImageDecoderImpl} that decodes HEIF images on API 36 using
+ * {@link BitmapFactory}.
+ *
+ * <p>There is a known bug for Android 36 where ImageDecoder will fail to retrieve HEIF images with
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java:17]: If possible link and externally visible version of the bug here.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplHeifPre36.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+import android.graphics.Bitmap;
+import androidx.annotation.RequiresApi;
+import io.flutter.Build;
+import java.nio.ByteBuffer;
+
+/**
+ * An implementation of {@link FlutterImageDecoderImpl} that decodes HEIF images on devices running
+ * Android versions prior to 36.
+ *
+ * <p>flipping (or mirroring) does not work Pre 36. Need to do it manually.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplHeifPre36.java]:
```suggestion
 * <p>flipping (or mirroring) from metadata does not work Pre 36. Need to do it manually.
```

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/Utils.java [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+  byte[] getBytes(@NonNull ByteBuffer buffer) {
+    byte[] bytes = new byte[buffer.remaining()];
+    buffer.get(bytes);
+    // Rewind the buffer so it can be used again.
+    buffer.rewind();
+    return bytes;
+  }
+
+  /**
+   * Returns whether the given EXIF orientation indicates a flip.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/Utils.java]:
```suggestion
   * Returns whether the given EXIF orientation indicates horizontal or vertical flip. 
```

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageUtils.java [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+   * @return True if the orientation is a flip case, false otherwise.
+   */
+  boolean isFlipCase(int orientation) {
+    switch (orientation) {
+      case ExifInterface.ORIENTATION_FLIP_HORIZONTAL: // 2
+      case ExifInterface.ORIENTATION_FLIP_VERTICAL: // 4
+      case ExifInterface.ORIENTATION_TRANSPOSE: // 5 (rotate 90 + flip H)
+      case ExifInterface.ORIENTATION_TRANSVERSE: // 7 (rotate 270 + flip H)
+        return true;
+      default:
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageUtils.java:54]: consider adding the other orientation values that are expected and also logging if an unexpected value is found.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+   * @param headerListener A listener to receive image header information.
+   * @return The decoded {@link Bitmap}, or null if decoding fails.
+   */
+  public static Bitmap decodeImage(
+      @NonNull ByteBuffer buffer, @NonNull HeaderListener headerListener) {
+    Metadata metadata = Metadata.create(buffer, headerListener);
+    FlutterImageDecoderImpl impl = null;
+    Utils utils = new Utils();
+    if (metadata.isHeif()) {
+      if (Build.VERSION.SDK_INT == io.flutter.Build.API_LEVELS.API_36) {
```
Comment (ash2moon) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java:49]: Any idea if this will continue to be an API 36 specific bug? Wondering if we should use >= instead or just wait for one more version to see what the pattern is.

**Review by reidbaker — COMMENTED** [review]
Have not reviewed tests yet

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderDefaultImpl.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+   * @return The decoded {@link Bitmap}, or null if decoding fails.
+   */
+  public Bitmap decodeImage(ByteBuffer buffer, Metadata metadata) {
+    ImageDecoder.Source source = ImageDecoder.createSource(buffer);
+    try {
+      return ImageDecoder.decodeBitmap(
+          source,
+          (decoder, info, src) -> {
+            // i.e. ARGB_8888
+            decoder.setTargetColorSpace(ColorSpace.get(ColorSpace.Named.SRGB));
```
Comment (ash2moon) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderDefaultImpl.java:48]: How do we know for sure all the images will be in SRGB color space? What happens if the input image is not SRGB? I saw that the previous code also assumed SRGB but it still feels kind of odd; maybe some additional documentation here?

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java [hunk 9]
```diff
@@ -0,0 +1,35 @@
+package io.flutter.embedding.engine.image;
+
+import android.media.ExifInterface;
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java:8]: Prefer the androidx variant of this instead. https://developer.android.com/jetpack/androidx/releases/exifinterface

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java (hunk 2 above)
Comment (gmackall) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java]: Agreed, an interface probably shouldn't be named impl right? Rather this could be `FlutterImageDecoder` and then we have a `BlahDefaultImpl` and a `BlahHeicPre36Impl`, etc.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplHeifPre36.java (hunk 4 above)
Comment (gmackall) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplHeifPre36.java]: Also nit but preference for full sentences in documentation in general, so something like "does not work Pre 36, so we need to do it manually." or similar

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java (hunk 7 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java:49]: I was told a fix is being worked on.  So I believe it will be fixed.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+   *
+   * @param buffer The {@link ByteBuffer} containing the encoded image.
+   * @param headerListener A listener to receive image header information.
+   * @return The decoded {@link Bitmap}, or null if decoding fails.
+   */
+  public static Bitmap decodeImage(
+      @NonNull ByteBuffer buffer, @NonNull HeaderListener headerListener) {
+    Metadata metadata = Metadata.create(buffer, headerListener);
+    FlutterImageDecoderImpl impl = null;
+    Utils utils = new Utils();
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java]: Instantiating and passing in the utils class to the constructors of the HEIC decoders seems a little odd to me. Every method in this class could be made static, couldn't it? And then we could just call the static methods without any instance.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/Utils.java [hunk 11]
```diff
@@ -0,0 +1,88 @@
+package io.flutter.embedding.engine.image;
+
+import android.graphics.Bitmap;
+import android.graphics.Matrix;
+import android.media.ExifInterface;
+import androidx.annotation.NonNull;
+import java.nio.ByteBuffer;
+
+/** Utility methods for image decoding. */
+class Utils {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/Utils.java]: Preference for naming this `ImageDecodingUtils`, or at least `ImageUtils`. 

I know the package path already contains `image`, but if we named every utils class utils within its own package it would make the IDE experience of typing the class name and letting the IDE auto add the import pretty awful (you'd have to scroll through to find your utils, inspecting each package name).

**Review by gmackall — COMMENTED** [review]
My main question is: do we know that the image flipping issue affects all HEIF images on api 36? Or is it only a subset? My concern would be that if this only affects a certain case of HEIF images that we might regress rotation of the unaffected set by double-rotating them (because it is based on EXIF). But if rotation is broken for all HEIF images than I think this approach makes sense.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java (hunk 10 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoder.java]: This was for testing.  I had it static initially.

**Comment by mboetger** [comment]
@gmackall 

> My main question is: do we know that the image flipping issue affects all HEIF images on api 36?

Flipping is only an issue pre 36. 

The flipping is not an issue on 36 - it will throw an exception trying parse the data.  The workaround for that (as advised by the codec team) is to just use BitmapFactory and handle the rotation/flipping ourselves.  It won't be double applied because BitmapFactory is not doing that - ImageDecoder would, but it throws an exception.  

It technically is a subset of images that will throw the exception - so we could try and then only fallback once an exception has been thrown.  It's only if the underlying codec cannot handle the incoming gainmap.  However, it's impossible with the tools at hand to know: 1.) if the codec can handle it and 2.) if the HEIC has the type of gainmap.  

We could take a dependency on an HEIC parsing library - and that would allow us to check for gainmaps - but we would still not know #1. But if we do add that dependency then we could use the HEIC info and not the EXIF.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java (hunk 9 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ExifMetadataReader.java:8]: Working on figuring out how to add this to our build/cipd.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java (hunk 3 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java:17]: There is no public bug - I asked. I also made sure to ask if it was ok to talk about the bug publicly and since Android 16 is open source it technically there for anyone to see if they know here to look

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderDefaultImpl.java (hunk 8 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderDefaultImpl.java:48]: This is for the output I believe: https://developer.android.com/reference/android/graphics/ImageDecoder#setTargetColorSpace(android.graphics.ColorSpace)

```
Specify the desired [ColorSpace](https://developer.android.com/reference/android/graphics/ColorSpace) for the output.
```

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageUtils.java (hunk 6 above)
Comment (mboetger) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageUtils.java:54]: There are a lot.  I would imagine any and all orientations are 'expected' as they are available for the metadata to set.

**Comment by mboetger** [comment]
> set? My concern would be that if this only affects a certain case of HEIF images that we might regress rotation of the unaffected

@gmackall - per offline convo I updated to only fallback if the default ImageDecoder call fails.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplDefault.java [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+import io.flutter.Log;
+import java.io.IOException;
+import java.nio.ByteBuffer;
+
+/**
+ * The default implementation of {@link ImageDecoder} that uses {@link
+ * android.graphics.ImageDecoder} to decode images.
+ */
+@RequiresApi(io.flutter.Build.API_LEVELS.API_28)
+class FlutterImageDecoderImplDefault implements ImageDecoder {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/FlutterImageDecoderImplDefault.java]: pretty nitpicky but I'd expect a `FooBarBazImpl` to implement a `FooBarBaz`, not a `BarBaz`. Maybe drop the flutter on the different strategies? Or make the interface `FlutterImageDecoderStrategy`, and the strategies can be called `FlutterImageDecoderStrategyDefaultImpl`, etc. Anyways, not a big deal.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java [hunk 13]
```diff
@@ -30,7 +29,17 @@ public FlutterImageDecoderImplHeifApi36(Utils utils) {
    * @return The decoded {@link Bitmap}, or null if decoding fails.
    */
   public Bitmap decodeImage(ByteBuffer buffer, Metadata metadata) {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifApi36Impl.java:36]: nit: I think this should have an `@Override`

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifPre36Impl.java [hunk 14]
```diff
@@ -0,0 +1,33 @@
...
+  }
+
+  /**
+   * Decodes an image from the given {@link ByteBuffer}.
+   *
+   * @param buffer The {@link ByteBuffer} containing the encoded image.
+   * @param metadata The metadata of the image.
+   * @return The decoded {@link Bitmap}, or null if decoding fails.
+   */
+  public Bitmap decodeImage(ByteBuffer buffer, Metadata metadata) {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/image/ImageDecoderHeifPre36Impl.java:35]: This should probably have an `@Override`

**Review by gmackall — APPROVED** [review]
lgtm

**Comment by mboetger** [comment]
Test are failing because gradle lock files are not updated - but running dev/tools/bin/generate_gradle_lockfiles.dart doesn't do anything :(

**Comment by mboetger** [comment]
@reidbaker - per our offline convo, removed the dep on androidx.exifinterface to try to get this in.  Filed #177071 and #177066 as follow-ups.

**Comment by reidbaker** [comment]
@mboetger you will still need to ignore the lint that warns you to use androidx
