### PR TITLE
Android treats link without URL semantics node as button

### LINKED ISSUE #172982: [Android][a11y] Widgets that set `Semantics.link` but not `Semantics.linkUrl` are not described as anything
### Steps to reproduce

Internal bug: b/435115601, client `huggsy`. I believe https://github.com/flutter/flutter/pull/162419 is the source of this regression.

1. Run the code sample below on an Android device
2. Turn on TalkBack
3. Navigate to the + button using TalkBack

### Expected results

The widget should be read as "Increment, link, double-tap to activate" or "Increment, button, double-tap to activate".

### Actual results

The widget is read as "Increment, double-tap to activate".

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: Center(
        child: Text(
          'Button tapped $_counter time${_counter == 1 ? '' : 's'}.',
          key: Key('CountText'),
        ),
      ),
      floatingActionButton: Semantics(
        container: true,
        link: true,
        label: 'Increment',
        child: Container(
          width: 48,
          height: 48,
          alignment: Alignment.center,
          child: InkWell(
            onTap: _incrementCounter,
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

N/A

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

N/A, Google internal client

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/172982

fixes it in the android side in case Android provide an API to denote link without URL in the future

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 1]
```diff
@@ -2504,6 +2504,19 @@ private boolean hadFlag(@NonNull Flag flag) {
...
+      if (hasFlag(Flag.IS_BUTTON)) {
+        return true;
+      }
+      if (linkUrl != null && !linkUrl.isEmpty()) {
+        // This will be represented as link through URLSpan.
+        return false;
+      }
+      // In Android, a link must be accompanied with a URL; otherwise,
+      // it should be treated as a button.
+      return hasFlag(Flag.IS_LINK);
```
Comment (ash2moon) [inline engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java]: Can we rephrase this comment to say:
"In Android, a link is treated as a button if and only if it does not have a URL"

**Review by ash2moon — APPROVED** [review]
