### PR TITLE
Use LLDB as the default debugging method for iOS 17+ and Xcode 26+

### LINKED ISSUE #133465: Long-term solution to replacing `ios-deploy`
Starting with Xcode 15 and iOS 17, `ios-deploy` no longer works on iOS 17+ physical devices and [sounds like ios-deploy will not be supporting it](https://github.com/ios-control/ios-deploy/issues/588#issuecomment-1667938056).

We added a workaround-like solution to fix https://github.com/flutter/flutter/issues/128531, but the solution is undesirable since it involves having Xcode open.

Xcode 15 did release a new tool called `devicectl`, which provide a lot of the functionality that Flutter requires. However, it's missing a key piece of being able to start a `debugserver` on the device, which is required for Flutter debug mode because `debugserver` [will ptrace the process](https://github.com/flutter/engine/blob/805162c18b32c8352c71d9e832a812fc40058020/runtime/ptrace_check.cc#L13-L16). This is required [due to the Dart VM being JIT and dependent on tracing](https://github.com/flutter/engine/pull/20980).

Ideally, Apple will provide a way to start a `debugserver` and connect with lldb through `devicectl`, but no sign of that yet as far as I know.

### LINKED ISSUE #144218: Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.
### 1. Set this environment: 

- Physical iPhone 14 Pro, iOS 17.3.1.1, Available storage 131.3 GB out of 256GB Capacity
- Xcode version 15.2 (15C500b)
- macOS Sonoma version 14.2.1 (23C71)
- Flutter Channel stable, 3.19.0
- Dart SDK version: 3.3.0 (stable)

### 3. Error:
```
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.
Could not run build/ios/iphoneos/Runner.app on 00008120-001A15C936A0C01E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.
```

### Expected results

The app should run on the iPhone with no issues.

**Note:**
- When I run the app from Xcode directly, the app runs.
- When I run the same app on a physical iPhone X, iOS 16.7.5, Available storage 114.19 GB out of 256GB Capacity it runs fine.
- When I build a new Flutter project and run the app, it runs just fine as well.

### Actual results
```
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxx
Xcode build done.                                           206.5s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.
Could not run build/ios/iphoneos/Runner.app on 00008120-001A15C936A0C01E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.
```
### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Screenshot 2024-02-27 at 13 04 36

Screenshot 2024-02-27 at 13 11 27
Screenshot 2024-02-27 at 13 11 39
</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ZR3QGWZA6A
Xcode build done.                                           206.5s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.
Could not run build/ios/iphoneos/Runner.app on 00008120-001A15C936A0C01E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
This PR introduces a new feature flag called `lldb-debugging`, which is turned on by default. When this feature is turned on, if deploying to a physical iOS 17+ device with Xcode 26+, it will use a mixture of `devicectl` and `lldb` to install, launch, and debug the app.

If LLDB fails, it will fallback to use Xcode automation. If LLDB times out, it will warn the user they may want to disable it. If LLDB is disabled, it will use Xcode automation.

This PR also adds analytics to track what deployment method is used and if it's successful.

Part 2 and 3 of https://github.com/flutter/flutter/issues/173416.

Fixes https://github.com/flutter/flutter/issues/144218. Fixes https://github.com/flutter/flutter/issues/133465.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/device.dart [hunk 1]
```diff
@@ -1212,13 +1211,7 @@ class DebuggingOptions {
       if (environmentType == EnvironmentType.simulator && dartFlags.isNotEmpty)
         '--dart-flags=$dartFlags',
       if (useTestFonts) '--use-test-fonts',
-      // Core Devices (iOS 17 devices) are debugged through Xcode so don't
-      // include these flags, which are used to check if the app was launched
-      // via Flutter CLI and `ios-deploy`.
-      if (debuggingEnabled && !isCoreDevice) ...<String>[
-        '--enable-checked-mode',
-        '--verify-entry-points',
-      ],
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/device.dart:1221]: This was specific to debugging through Xcode, so I moved it here:

https://github.com/flutter/flutter/blob/b02a1f431d5d7e597d1865458d712088fab0eadf/packages/flutter_tools/lib/src/ios/devices.dart#L1085-L1090

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 2]
```diff
@@ -908,98 +969,140 @@ class IOSDevice extends Device {
...
       // Launch app to device
-      final bool launchSuccess = await _coreDeviceControl.launchApp(
+      final IOSCoreDeviceLaunchResult? launchResult = await _coreDeviceControl.launchApp(
         deviceId: id,
         bundleId: package.id,
         launchArguments: launchArguments,
       );
+      final bool launchSuccess = launchResult != null && launchResult.outcome == 'success';
 
-      return launchSuccess;
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/ios/devices.dart:921]: The diff here sucks due to spacing. 

The changes made here:
* Updated returns to return a `bool` and a `IOSDeploymentMethod`
* If LLDB feature flag is enabled and Xcode 26+, use LLDB debugging
* Updated timeout warning message for Xcode debugging
* Filter out some arguments when Xcode debugging

Here's the function before:

https://github.com/flutter/flutter/blob/796c62bd76f8afaf741e3b8e7c1eb4c8bc24f2a4/packages/flutter_tools/lib/src/ios/devices.dart#L894-L1003

and after:

https://github.com/flutter/flutter/blob/261be4b4f670759c8d30b35223ef14ee7e018625/packages/flutter_tools/lib/src/ios/devices.dart#L955-L1106

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 3]
```diff
@@ -908,98 +969,140 @@ class IOSDevice extends Device {
...
-      final timer = Timer(discoveryTimeout ?? Duration(seconds: launchTimeout), () {
-        _logger.printError(
-          'Xcode is taking longer than expected to start debugging the app. '
-          'Ensure the project is opened in Xcode.',
+
+      // If it succeeds to launch with LLDB, return, otherwise continue on to
+      // try launching with Xcode.
+      if (launchSuccess) {
+        return (launchSuccess, IOSDeploymentMethod.coreDeviceWithLLDB);
+      } else {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/devices.dart:1005]: Ubernit: is this `else` necessary?

**Review by bkonyi — APPROVED** [review]
LGTM!
