### PR TITLE
Rebuild modal routes when the value of userGestureInProgress changes

### LINKED ISSUE #41024: Touch does not work after returning with edge swiping gesture of CupertinoPageRoute.
1. Run this.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(Root());

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: First());
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First'),
      ),
      body: Center(
        child: RaisedButton(
          child: const Text('Go To Second'),
          onPressed: () {
            Navigator.of(context).push(
              CupertinoPageRoute(
                builder: (BuildContext context) {
                  return Second();
                },
              ),
            );
          },
        ),
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second'),
      ),
      body: Container(),
    );
  }
}
```

2. Tap `Go To Second` button to go `Second` screen.

3. Pop `Second` screen with back button of appBar.

4. It's OK, no problem.

5. Tap `Go To Second` again.

6. Pop `Second` screen with edge swipe gesture.

7. You can see that the `Go To Second` button cannot be touched.

---

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.13.6 17G8030, locale ja-JP)
    • Flutter version 1.10.6-pre.29 at /buildroot/flutter
    • Framework revision 919cc97f6a (15 hours ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yuichi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.13.6 17G8030
    • Chrome                    • chrome        • web-javascript • Google Chrome 77.0.3865.90
    • Server                    • web           • web-javascript • Flutter Tools

• No issues found!
```

---

* It's no problem on the stable channel:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030, locale ja-JP)
    • Flutter version 1.9.1+hotfix.2 at /buildroot/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

* I have noticed that it will be possible to touch again when it is re-laid out by rotating the screen or other operation (by `ui.window.onMetricsChanged()` and so on) after the  swipe animation.

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/41024

The build has been red all day. So It might be possible to just land this PR  instead of reverting https://github.com/flutter/flutter/pull/41141 (and then relanding https://github.com/flutter/flutter/pull/40466 with the changes included here).

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -2185,10 +2185,25 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
     route.dispose();
   }
 
+  int _userGesturesInProgressCount = 0;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: Nit: I believe our style guide wants the field between the getter and setter.

**Review by goderbauer — APPROVED** [review]
LGTM
