### PR TITLE
Fix the inconsistency between the local state of the input and the engine state

### LINKED ISSUE #65059: TextField  cursor misalignment when keyboardType is multiline
## Steps to Reproduce

```
import 'package:flutter/material.dart';

class CreatePage extends StatefulWidget {
  // CreatePage({Key key, this.title}) : super(key: key);
  @override
  _CreatePageState createState() => _CreatePageState();
}

class _CreatePageState extends State<CreatePage> with AutomaticKeepAliveClientMixin{

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => false;

  @override
  initState() {
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Center(
      child: Container(
        color: Colors.amber,
        padding: EdgeInsets.all(8.0),
        child: TextField(
            keyboardType: TextInputType.multiline,
            maxLines: 4
        ),
      ),
    );
  }
}
```

 

**Expected results:**
input content insert into the newline

**Actual results:** 
input content insert into the previous cursor location
device-2020-09-01-165638 00_00_00-00_00_30
<details>
  <summary>Logs</summary>

```
PS D:\Workspace\AndroidStudio\flutter_fam> flutter run --verbose
[  +94 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git tag --contains HEAD
[ +165 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.2
[   +8 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe devices -l
[  +29 ms] List of devices attached
           R52N204XPRL            device product:wisdomwifizh model:SM_P200 device:wisdomwifi transport_id:1
[   +6 ms] D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell getprop
[  +96 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] Found plugin flutter_local_notifications at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_local_notifications-1.4.4+
4\
[  +13 ms] Found plugin path_provider_linux at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_linux-0.0.1+2\
[   +9 ms] Found plugin shared_preferences at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.10\
[   +2 ms] Found plugin shared_preferences_linux at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_linux-0.0.2+2\
[   +2 ms] Found plugin shared_preferences_macos at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_macos-0.0.1+10\
[   +3 ms] Found plugin shared_preferences_web at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_web-0.1.2+7\
[  +60 ms] Found plugin flutter_local_notifications at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_local_notifications-1.4.4+
4\
[   +8 ms] Found plugin path_provider_linux at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_linux-0.0.1+2\
[   +5 ms] Found plugin shared_preferences at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.10\
[   +3 ms] Found plugin shared_preferences_linux at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_linux-0.0.2+2\
[   +2 ms] Found plugin shared_preferences_macos at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_macos-0.0.1+10\
[   +2 ms] Found plugin shared_preferences_web at
D:\Programs\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_web-0.1.2+7\
[  +45 ms] Generating
D:\Workspace\AndroidStudio\flutter_fam\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +35 ms] ro.hardware = exynos7904
[        ] ro.build.characteristics = tablet
[  +49 ms] Starting incremental build...
[   +4 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +3 ms] Launching lib\main.dart on SM P200 in debug mode...
[   +4 ms] D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\SongFei\AppData\Local\Temp\flutter_tools.4ab5162b\flutter_tool.237b4b6e\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[   +8 ms] executing: D:\Programs\Android\SDK\build-tools\29.0.3\aapt dump xmltree
D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +13 ms] Exit code 0 from: D:\Programs\Android\SDK\build-tools\29.0.3\aapt dump xmltree
D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.lion.flutter.flutter_fam" (Raw: "com.lion.flutter.flutter_fam")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_fam" (Raw: "flutter_fam")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.lion.flutter.flutter_fam.MainActivity" (Raw:
                   "com.lion.flutter.flutter_fam.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell -x logcat -v time -t 1
[ +126 ms] Exit code 0 from: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           09-03 13:42:02.363 D/ConnectivityService( 4149): filterNetworkStateForUid() uid: 10147, pid: 2687,
           networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover:
           false, available: true, roaming: false]
[   +2 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell -x logcat -v time -t 1
[ +127 ms] Exit code 0 from: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           09-03 13:42:02.363 D/ConnectivityService( 4149): filterNetworkStateForUid() uid: 10147, pid: 2687,
           networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover:
           false, available: true, roaming: false]
[  +12 ms] <- compile package:flutter_fam/main.dart
[   +8 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe version
[  +18 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as D:\Programs\Android\SDK\platform-tools\adb.exe
[   +3 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe start-server
[  +22 ms] Building APK
[  +15 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from D:\Workspace\AndroidStudio\flutter_fam\android\gradlew.bat.
[   +1 ms] D:\Workspace\AndroidStudio\flutter_fam\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +9 ms] executing: D:\Programs\Android\AndroidStudio\jre\bin\java -version
[  +89 ms] Exit code 0 from: D:\Programs\Android\AndroidStudio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [D:\Workspace\AndroidStudio\flutter_fam\android/]
D:\Workspace\AndroidStudio\flutter_fam\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=D:\Workspace\AndroidStudio\flutter_fam\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3610 ms] > Task :app:compileFlutterBuildDebug
[   +3 ms] [  +95 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[   +1 ms] [  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] [        ] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git tag --contains HEAD
[   +1 ms] [ +166 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] [        ] 1.20.2
[        ] [   +8 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +1 ms] [  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git ls-remote --get-url origin
[   +1 ms] [  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [  +63 ms] executing: [D:\Programs\flutter_windows_1.20.2-stable\flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[   +1 ms] [  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +13 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +63 ms] Initializing file store
[        ] [   +2 ms] Done initializing file store
[        ] [  +30 ms] Skipping target: gen_localizations
[        ] [ +466 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[   +1 ms] [  +27 ms] D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\dart-sdk\bin\dart.exe
--disable-dart-dev
D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root D:\Programs\flutter_windows_1.20.2-stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
D:\Workspace\AndroidStudio\flutter_fam\.packages --output-dill
D:\Workspace\AndroidStudio\flutter_fam\.dart_tool\flutter_build\de45ec236a55153e3c8c5969ab6a26ce\app.dill --depfile
D:\Workspace\AndroidStudio\flutter_fam\.dart_tool\flutter_build\de45ec236a55153e3c8c5969ab6a26ce\kernel_snapshot.d
package:flutter_fam/main.dart
[+6027 ms] [+6365 ms] kernel_snapshot: Complete
[ +189 ms] [ +237 ms] debug_android_application: Starting due to {}
[ +410 ms] [ +349 ms] debug_android_application: Complete
[ +397 ms] [ +462 ms] Persisting file store
[   +1 ms] [  +14 ms] Done persisting file store
[  +94 ms] [  +17 ms] build succeeded.
[   +1 ms] [  +14 ms] "flutter assemble" took 8,076ms.
[   +1 ms] [   +2 ms] ensureAnalyticsSent: 0ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +104 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:preBuild UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :shared_preferences:preBuild UP-TO-DATE
[   +1 ms] > Task :shared_preferences:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :shared_preferences:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +81 ms] > Task :flutter_local_notifications:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :shared_preferences:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugShaders UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_local_notifications:packageDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +285 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_local_notifications:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:packageDebugResources UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :shared_preferences:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :flutter_local_notifications:checkDebugManifest
[   +2 ms] > Task :flutter_local_notifications:processDebugManifest UP-TO-DATE
[        ] > Task :shared_preferences:checkDebugManifest
[        ] > Task :shared_preferences:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[  +77 ms] > Task :flutter_local_notifications:parseDebugLibraryResources UP-TO-DATE
[   +2 ms] > Task :flutter_local_notifications:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :shared_preferences:parseDebugLibraryResources UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :flutter_local_notifications:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :shared_preferences:processDebugJavaRes NO-SOURCE
[ +187 ms] > Task :app:checkDebugDuplicateClasses
[   +1 ms] > Task :flutter_local_notifications:javaPreCompileDebug
[+1094 ms] > Task :flutter_local_notifications:compileDebugJavaWithJavac
[   +1 ms] > Task :flutter_local_notifications:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:bundleLibResDebug UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:createFullJarDebug UP-TO-DATE
[        ] > Task :shared_preferences:javaPreCompileDebug
[ +106 ms] > Task :shared_preferences:compileDebugJavaWithJavac
[   +1 ms] > Task :shared_preferences:bundleLibCompileDebug UP-TO-DATE
[+10190 ms] > Task :app:compileDebugKotlin
[   +1 ms] > Task :shared_preferences:bundleLibResDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :shared_preferences:createFullJarDebug UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug
[ +894 ms] > Task :app:compileDebugJavaWithJavac
[   +2 ms] > Task :app:compileDebugSources
[+1191 ms] > Task :app:transformClassesWithDexBuilderForDebug
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[ +107 ms] > Task :app:mergeDebugJavaResource
[   +2 ms] > Task :app:desugarDebugFileDependencies
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:mergeDebugJniLibFolders UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :shared_preferences:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :shared_preferences:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:extractDebugAnnotations
[   +3 ms] > Task :flutter_local_notifications:mergeDebugGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:prepareLintJarForPublish UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :flutter_local_notifications:bundleDebugAar UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugSources
[   +1 ms] > Task :flutter_local_notifications:assembleDebug
[  +68 ms] > Task :shared_preferences:extractDebugAnnotations
[   +2 ms] > Task :shared_preferences:mergeDebugGeneratedProguardFiles UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +1 ms] > Task :shared_preferences:prepareLintJarForPublish UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :shared_preferences:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :shared_preferences:bundleDebugAar UP-TO-DATE
[   +1 ms] > Task :shared_preferences:compileDebugSources
[   +1 ms] > Task :shared_preferences:assembleDebug
[+1088 ms] > Task :app:mergeExtDexDebug
[ +202 ms] > Task :app:mergeDebugNativeLibs
[ +587 ms] > Task :app:stripDebugDebugSymbols
[   +3 ms] > Task :app:mergeDexDebug
[+2605 ms] > Task :app:packageDebug
[  +68 ms] > Task :app:assembleDebug
[   +1 ms] BUILD SUCCESSFUL in 29s
[   +1 ms] 87 actionable tasks: 25 executed, 62 up-to-date
[ +527 ms] Running Gradle task 'assembleDebug'... (completed in 30.5s)
[  +35 ms] calculateSha: LocalDirectory: 'D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk'/app.apk
[  +32 ms] calculateSha: reading file took 31us
[ +421 ms] calculateSha: computing sha took 419us
[  +10 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +11 ms] executing: D:\Programs\Android\SDK\build-tools\29.0.3\aapt dump xmltree
D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +18 ms] Exit code 0 from: D:\Programs\Android\SDK\build-tools\29.0.3\aapt dump xmltree
D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.lion.flutter.flutter_fam" (Raw: "com.lion.flutter.flutter_fam")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_fam" (Raw: "flutter_fam")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.lion.flutter.flutter_fam.MainActivity" (Raw:
                   "com.lion.flutter.flutter_fam.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on SM P200.
[   +1 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell am force-stop
com.lion.flutter.flutter_fam
[ +139 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell pm list packages
com.lion.flutter.flutter_fam
[ +153 ms] package:com.lion.flutter.flutter_fam
[   +5 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell cat
/data/local/tmp/sky.com.lion.flutter.flutter_fam.sha1
[  +79 ms] d9224197287ea366ebfc5c605f363f29aff2f936
[   +2 ms] Installing APK.
[   +2 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe version
[  +17 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as D:\Programs\Android\SDK\platform-tools\adb.exe
[   +1 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe start-server
[  +17 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +1 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL install -t -r
D:\Workspace\AndroidStudio\flutter_fam\build\app\outputs\flutter-apk\app.apk
[+6549 ms] Performing Streamed Install
                    Success
[   +2 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 6.6s)
[   +2 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell echo -n
fd9c04e0223db2fc4c9199d8583a79ddfebac86b > /data/local/tmp/sky.com.lion.flutter.flutter_fam.sha1
[  +42 ms] SM P200 startApp
[   +3 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true
com.lion.flutter.flutter_fam/com.lion.flutter.flutter_fam.MainActivity
[ +260 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=com.lion.flutter.flutter_fam/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1908 ms] Observatory URL on device: http://127.0.0.1:40498/g1ATS-xGZFU=/
[   +2 ms] executing: D:\Programs\Android\SDK\platform-tools\adb.exe -s R52N204XPRL forward tcp:0 tcp:40498
[  +20 ms] 9044
[        ] Forwarded host port 9044 to device port 40498 for Observatory
[   +4 ms] Caching compiled dill
[  +23 ms] Connecting to service protocol: http://127.0.0.1:9044/g1ATS-xGZFU=/
[ +496 ms] Successfully connected to service protocol: http://127.0.0.1:9044/g1ATS-xGZFU=/
[   +2 ms] Waiting for SM P200 to report its views...
[  +11 ms] Waiting for SM P200 to report its views... (completed in 10ms)
[  +11 ms] DevFS: Creating new filesystem on the device (null)
[  +51 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.lion.flutter.flutter_fam/code_cache/flutter_famNSBCZS/flutter_fam/)
[   +3 ms] Updating assets
[  +85 ms] Syncing files to device SM P200...
[   +3 ms] Scanning asset files
[  +10 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:flutter_fam/main.dart ad8d22bf-72b9-4e74-9cfc-1087cb2ff913
[   +1 ms] <- ad8d22bf-72b9-4e74-9cfc-1087cb2ff913
[  +72 ms] Updating files
[ +273 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device SM P200... (completed in 363ms)
[   +1 ms] Synced 0.9MB.
[   +1 ms] <- accept
[  +10 ms] Connected to _flutterView/0x793fdba820.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on SM P200 is available at: http://127.0.0.1:9044/g1ATS-xGZFU=/

```

```
```

```
D:\Programs\flutter_windows_1.20.2-stable\flutter>flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale zh-CN)
    • Flutter version 1.20.2 at D:\Programs\flutter_windows_1.20.2-stable\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Programs\Android\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Programs\Android\SDK
    • Java binary at: D:\Programs\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Programs\Android\AndroidStudio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM P200 (mobile) • R52N204XPRL • android-arm64 • Android 10 (API 29)
```

</details>

### LINKED ISSUE #66036: On some devices, native keyboard cannot be closed with back button
Device: Samsung S8, S9
Branch: master

android native keyboard not able to close when we tab hide keyboard and back button in samsung devices with **master** branch. Works fine with **stable** branch. 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Keyboard Input')),
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```
```
flutter doctor
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0-10.0.pre.222, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.49.0)
[√] Connected device (3 available)
• No issues found!
```

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

See https://github.com/flutter/flutter/issues/65059#issuecomment-690254379 and https://github.com/flutter/flutter/issues/65059#issuecomment-690266733

@justinmc @GaryQian Please review, thank you guys very much:)

## Related Issues

Fixes #65059 

## Tests

See the change files.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2140,10 +2155,6 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       _value = _lastFormattedValue;
     }
 
-    // Always attempt to send the value. If the value has changed, then it will send,
-    // otherwise, it will short-circuit.
-    _updateRemoteEditingValueIfNeeded();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/editable_text.dart:2145]: This will be automatically called by the controller's notifier.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -4715,6 +4715,132 @@ void main() {
...
+        'selectionIsDirectional': false,
+        'composingBase': -1,
+        'composingExtent': -1,
+      }),
+    );
+
+    log.clear();
+
+    // Currently `_receivedRemoteTextEditingValue` equals 'I will be modified by the formatter.',
+    // setEditingState will be called when set the [controller.value] to `_receivedRemoteTextEditingValue` by local.
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:4824]: This is tricky, good call testing this case.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -1655,10 +1663,11 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       _stopCursorTimer(resetCharTicks: false);
       _startCursorTimer();
     }
+    _updateEditingValueInProgress = false;
   }
 
-  bool _isSelectionOnlyChange(TextEditingValue value) {
-    return value.text == _value.text && value.composing == _value.composing;
+  bool _isSelectionOnlyChanged(TextEditingValue value) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1669]: I think it should stay as "Change", as I understand it.  I think it meant like: "is selection the only change"

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -1655,10 +1663,11 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    return value.text == _value.text && value.composing == _value.composing && value.selection != _value.selection;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1670]: I'm not sure why the selection wasn't checked here in the first place.  This seems to make more sense.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -1642,8 +1646,12 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
         _obscureLatestCharIndex = _value.selection.baseOffset;
       }
     }
-
-    if (_isSelectionOnlyChange(value)) {
+    if (value == _value) {
+      // This is possible, for example, when the numeric keyboard is input,
+      // the engine will notify twice for the same value. Perhaps this is an issue.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1651]: Could you create an actual issue for this and link to it here?  I just want to make sure this has the chance to get looked at, in case it is a problem.  It doesn't make sense to me that the engine should notify twice for the numeric keyboard.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -1620,11 +1620,15 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   @override
   TextEditingValue get currentTextEditingValue => _value;
 
+  bool _updateEditingValueInProgress = false;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1623]: This PR really reminds me of this issue, which also deals with the asynchronous communication between the engine and framework: https://github.com/flutter/flutter/issues/61282

My solution there wasn't anything like this PR, but I think using this flag `_updateEditingValueInProgress` could maybe help us handle problems like that.

**Review by justinmc — COMMENTED** [review]
Thanks for investigating this issue!  This was not a simple problem.

Just a small naming change and a request for an issue to be created.

**Comment by LongCatIsLooong** [comment]
Thanks for the PR and the detailed explanation! This looks like an Android-specific issue, as I failed to reproduce this on iOS. The android input plugin seems to be not syncing back the editing state when there's a selection only change.  Maybe this bug needs to be fixed from the engine side (i.e., the android input plugin)?

**Comment by xu-baolin** [comment]
> Thanks for the PR and the detailed explanation! This looks like an Android-specific issue, as I failed to reproduce this on iOS. The android input plugin seems to be not syncing back the editing state when there's a selection only change. Maybe this bug needs to be fixed from the engine side (i.e., the android input plugin)?

I think this is a logic bug of the framework, we should always send changes to the engine when local changes, including iOS platform. 
Not only selection change,  the text change also will trigger the bug,also see the unit test.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:1651]: The track at #65811

**Comment by xu-baolin** [comment]
@justinmc  @LongCatIsLooong I also create an issue to track https://github.com/flutter/flutter/issues/65059#issuecomment-690266733

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Done.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:1672]: Do we still need this, with the changes made in line 1650 through 1656 (i.e., the additional case handling when `_value == value` )?

**Review by LongCatIsLooong — APPROVED** [review]
Ah I thought the text input platform plugin should send back the value until I unearthed https://github.com/flutter/engine/commit/600567ef152452ded9914aa6aa441ce8cc66b74b. Yeah you're right we shouldn't enforce the platform text input plugin to send back the value. Thank you!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:1672]: @LongCatIsLooong 
Yes, you are correct. But the name of this function is ambiguous, or change the name instead.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:1672]: It appears the method is only used here. You can get rid of it and use the expression instead (and maybe leave a comment that says if the change is selection only)

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good idea.
Done.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Thanks!

**Review by justinmc — APPROVED** [review]
LGTM, I think this is ready to merge when the tree is green.  Thanks so much for working on this!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: This should not remove, see #67892
