### PR TITLE
Fix and test SemanticsController.simulatedAccessibilityTraversal

### LINKED ISSUE #143173: Typos in flutter_test/lib/src/controller.dart
### Steps to reproduce

The function [simulatedAccessibilityTraversal] has deprecated the use of [start] and [end] in favor of [startNode] and [endNode], however, the latter parameters are not used to calculate the start and end index for the iteration:
https://github.com/flutter/flutter/blob/efd1d1f536ece87fc8c3437879f7f95f12e0d184/packages/flutter_test/lib/src/controller.dart#L267

This is forcing me to use the deprecated [start]/[end] parameters to filter the result.
 
other minor typos:
https://github.com/flutter/flutter/blob/efd1d1f536ece87fc8c3437879f7f95f12e0d184/packages/flutter_test/lib/src/controller.dart#L209
it should say "The start node... View of start node...", it says "The end node... View of end node..."

### Expected results

There should be in the code something like:
```dart
if (startNode != null) {
  startIndex = ...
}
if (endNode != null) {
  endIndex = ...
}
```

### Actual results

it only contains
```dart
if (start != null) ...
```

### Code sample

<details open><summary>Code sample</summary>

```dart
n/a
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
n/a
```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/143173

The `start` and `end` parameters of `SemanticsController.simulatedAccessibilityTraversal` were deprecated in https://github.com/flutter/flutter/issues/112413, but no tests were added that verified the new API. 😳

This change
- fixes a typo in an error message
- fixes the new `startNode` and `endNode` not being accounted for in setting the traversal range
- adds dart fixes for the deprecations
- adds tests for the new API that is meant to replace the deprecated one.
  - Filed https://github.com/flutter/flutter/issues/143405 to follow up on the new API not working in multiple views.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_test/lib/src/controller.dart [hunk 1]
```diff
@@ -197,18 +203,17 @@ class SemanticsController {
...
+    } else if (startNode != null) {
       final SemanticsOwner owner = startNode.evaluate().single.owner!;
       final RenderView renderView = _controller.binding.renderViews.firstWhere(
         (RenderView render) => render.owner!.semanticsOwner == owner,
       );
       startView = renderView.flutterView;
       if (view != null && startView != view) {
         throw StateError(
-          'The end node is not part of the provided view.\n'
+          'The start node is not part of the provided view.\n'
```
Comment (Piinks) [inline packages/flutter_test/lib/src/controller.dart:214]: This was the originally reported typo. 😆

File: packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart.expect [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+void main() {
+  // Generic reference variables.
+  finders.FinderBase<Element> theStart;
+  finders.FinderBase<Element> theEnd;
+
+  testWidgets('simulatedAccessibilityTraversal', (WidgetTester tester) async {
+    // Changes made in https://github.com/flutter/flutter/pull/143386
+    tester.semantics.simulatedAccessibilityTraversal();
+    tester.semantics.simulatedAccessibilityTraversal(startNode: theStart);
```
Comment (goderbauer) [inline packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart.expect:15]: Hm, this will not compile, though, because `startNode` expects a `FinderBase<SemanticsNode>`, but `theStart` is a `FinderBase<Element>`.

Is this intentionally a part-fix? I am not sure how helpful that is...

File: packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
+  // Generic reference variables.
+  finders.FinderBase<Element> theStart;
+  finders.FinderBase<Element> theEnd;
+
+  testWidgets('simulatedAccessibilityTraversal', (WidgetTester tester) async {
+    // Changes made in TBD
```
Comment (goderbauer) [inline packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart:13]: Reminder to fill this in.

**Review by goderbauer — APPROVED** [review]
Changes LGTM, just a question on how helpful the partial flutter fix is.

File: packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart.expect (hunk 2 above)
Comment (Piinks) [reply packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart.expect:15]: It is partial. I always prefer to provide when we can, because during the deprecation period, the analyzer will say "Use startNode instead."
But after we remove it, it will only say "This is undefined."

Having the dart fix here means they will at least have a hint in the latter scenario that says "Use startNode."

File: packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter_test/test_fixes/flutter_test/semantics_controller.dart:13]:
```suggestion
    // Changes made in https://github.com/flutter/flutter/pull/143386
```

Thanks!

**Comment by Piinks** [comment]
The Google testing shard keeps failing on an infra issue. Filed an internal bug, will follow up in the morning.

**Comment by Piinks** [comment]
Reason for revert: This broke a customer test.
