### PR TITLE
Fixed VirtualViewport child key assignment

### LINKED ISSUE #2830: Can't see last option in Gallery, Components list
The "Text Fields" option is hidden underneath the Android system buttons. I am on a Nexus 6P.

I can scroll up to see "Text Fields" but then the list animates back down. The last item I can see is "Tooltips".

### PR DESCRIPTION
**Pull request by HansMuller**
VirtualViewport children that lacked keys were all assigned the same null key.

Added an assert that verifies that all of the viewport's materialized children have unique keys.

Fixes https://github.com/flutter/flutter/issues/2830

### CODE REVIEW

File: packages/flutter/lib/src/widgets/debug.dart [hunk 1]
```diff
@@ -22,3 +24,21 @@ bool debugCheckHasMediaQuery(BuildContext context) {
   });
   return true;
 }
+
+bool debugHasDuplicateKeys(Widget parent, Iterable<Widget> children) {
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/debug.dart]: I'd wrap the body of this function in an assert to make sure it is used only in debug builds.  See debugCheckHasMediaQuery above for the pattern.

File: packages/flutter/lib/src/widgets/debug.dart [hunk 2]
```diff
@@ -22,3 +24,21 @@ bool debugCheckHasMediaQuery(BuildContext context) {
...
+  Set<Key> keySet = new HashSet<Key>();
+  for (Widget child in children) {
+    assert(child != null);
+    if (child.key == null)
+      continue; // when these nodes are reordered, we just reassign the data
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/debug.dart]: I'd skip this comment.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
this really should have a test :-)

**Comment by abarth** [comment]
Yeah, although in some sense the assert is the test.  With just the assert added, lots of tests fail.

**Comment by Hixie** [comment]
oh, that makes sense.
