### PR TITLE
Fix `todayBorder` todayBorder color is incorrectly overridden by `todayForegroundColor` in CalendarDatePicker

### LINKED ISSUE #177911: CalendarDatePicker: `todayBorder` color is incorrectly overridden by `todayForegroundColor`
### Steps to reproduce

1. Add into theme todayForegroundColor e.g Colors.black, and remove BorderSide(e.g null or empty BorderSide())
2. But material/calendar_date_picker.dart 1201:77 will use todayForegroundColor property instead
3. I think that every developer should have to decide, show on today's date border or not, if should - with specifying color in CalendarPickerData

### Expected results

CalendarDatePicker should use borderSide without copyWithing it.

### Actual results

CalendarDatePicker - overriding specified border color

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        datePickerTheme: DatePickerThemeData(
          todayBorder: BorderSide(color: Colors.red),
          todayForegroundColor: WidgetStateProperty.all(Colors.blue),
          todayBackgroundColor: WidgetStateProperty.all(Colors.white),
        ),
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: Scaffold(
        body: Center(
          child: CalendarDatePicker(
            initialDate: DateTime.now(),
            firstDate: DateTime(1900),
            lastDate: DateTime(2100),
            onDateChanged: (DateTime value) {},
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

Image

</details>

### Logs

<details open><summary>Logs</summary>

No logs
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
bug % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.4, on macOS 26.0 25A354 darwin-arm64, locale en-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] VS Code (version 1.105.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Abylaikhan’s iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
- Fix https://github.com/flutter/flutter/issues/177911
- In this PR:
    - Avoid auto-overriding border side color with `dayForegroundColor` when users specify an explicit border color
    - Improve `todayBorder` documentation to clarify cases can happen.
    - Add an opacity check: this is because if we don't respect/specify an explicit border color, we still need to keep enabled/disabled states (state-aware) that `dayForegroundColor` always does:

https://github.com/flutter/flutter/blob/de3f804590cea1e68065b93f4a0b55a7a451f233/packages/flutter/lib/src/material/date_picker_theme.dart#L1174

So we need a fallback compatibility here:

```dart
final bool hasCustomBorderColor =
        datePickerTheme.todayBorder != null && datePickerTheme.todayBorder?.color.opacity != 0.0;
    final BorderSide todayBorderSide = hasCustomBorderColor
        ? datePickerTheme.todayBorder!
        : (datePickerTheme.todayBorder ?? defaults.todayBorder!).copyWith(
            color: dayForegroundColor,
          );
```

- Added 3 tests in `calendar_date_picker_test.dart‎`.
- Update test data in `date_picker_theme_test.dart`: Updated todayBorder from `BorderSide(width: 3)` to `BorderSide(width: 3, color: Color(0x00000000))` to maintain backward compatible behavior in tests: after changing color to transparent, it should fall back to `todayForegroundColor`. This is because the test's real purpose was to verify theme properties work, and it was expecting foreground color (which is the bug reported).

<details open>
<summary>Demo</summary>

| Before | After |
| --------------- | --------------- |
 | 
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by huycozy** [comment]
Hi @dkwingsmt, would you mind taking a look at this? Thank you! :)

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 1]
```diff
@@ -1213,14 +1213,17 @@ class _DayState extends State<_Day> {
       (DatePickerThemeData? theme) => theme?.dayShape,
       states,
     )!;
+    final bool hasCustomBorderColor =
+        datePickerTheme.todayBorder != null && datePickerTheme.todayBorder?.color.opacity != 0.0;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/calendar_date_picker.dart]: Now that it is guaranteed non-null, this is clearer.
```suggestion
        datePickerTheme.todayBorder != null && datePickerTheme.todayBorder!.color.opacity != 0.0;
```

File: packages/flutter/lib/src/material/date_picker_theme.dart [hunk 2]
```diff
@@ -276,8 +276,10 @@ class DatePickerThemeData with Diagnosticable {
   /// [DatePickerDialog.currentDate] label in the grid of the date
   /// picker.
   ///
-  /// The border side's [BorderSide.color] is not used,
-  /// [todayForegroundColor] is used instead.
+  /// If the border side's [BorderSide.color] is transparent (has 0 opacity),
+  /// [todayForegroundColor] is used instead. Otherwise, the border's color
+  /// is used as specified. To omit the border entirely,
+  /// set [todayBorder} to {BorderSide.none}
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/date_picker_theme.dart]:
```suggestion
  /// set [todayBorder] to [BorderSide.none].
```

**Review by dkwingsmt — COMMENTED** [review]
Generally LGTM. But I still don't understand why the opacity check is needed. Can you explain in more details what kind of compatibility we're keeping here?

Also sorry for the late review!

**Comment by huycozy** [comment]
> But I still don't understand why the opacity check is needed. Can you explain in more details what kind of compatibility we're keeping here?

@dkwingsmt 
- Yes, using `opacity` is quite tricky here. However, it makes sense as I think border color is normally a non-transparent color when user defined, isn't it?
- This update keeps a fallback to `dayForegroundColor` to handle state properly, maintain old behavior and compatibility, as [dayForegroundColor](https://github.com/flutter/flutter/blob/590666c456aa3f105d8435619439d0abcb298204/packages/flutter/lib/src/material/date_picker_theme.dart#L1174) is state-aware color by default whilst [todayBorder](https://github.com/flutter/flutter/blob/f6e6539ed299a9e1f81c7781caa761ed53551ac6/packages/flutter/lib/src/material/date_picker_theme.dart#L1381) is not.
_In another/nature words: by default, if users don't specify a border color, it keeps using `dayForegroundColor`. Otherwise, respect user-provided color._

For example:

  | Border Color                    | Meaning              | Result                                                  |
  |---------------------------------|-----------------------------|-----------------------------------------------------------|
  | Color(0x00000000) (transparent) | "I have no preference"      | Use foreground color (state-aware) |
  | Color(0xffff0000) (red) | "I want this color" | Use red (user's explicit choice)                          |
- In case we want to update todayBorder to support state-aware, let's do it in another issue as it could be a breaking change?

**Comment by huycozy** [comment]
Hi @dkwingsmt, is this good to go forward?:)

**Review by dkwingsmt — APPROVED** [review]
LGTM. Great PR, thank you so much!
