### PR TITLE
[Impeller] cache for text shadows.

### LINKED ISSUE #164303: Segfault OOM when displaying Icon widgets with Shadows
### Steps to reproduce

1. Create a new flutter project on flutter 3.29.0 and use the code provided in `main.dart`. On my phone, after reaching around 600 to 1400 icons, the app crashes due to an out of memory segfault and it lags heavily up until then. Remove line 64: `shadows: [const Shadow(blurRadius: 4)],`, and there is no crash (i let it run up to 6000 easily with no shadows). I tested on a Z flip 6 running android 14 (oneui 6.1.1)

### Expected results

No crash

### Actual results

Crash

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _count = 200;

  @override
  void initState() {
    // TODO: implement initState
    Timer.periodic(Duration(seconds: 1), (_) {
      setState(() {
        _count += 50;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('~ $_count'),
            for (int x = 0; x < sqrt(_count); x++)
              Row(
                children: [
                  for (int y = 0; y < sqrt(_count); y++)
                    Icon(
                      shadows: [const Shadow(blurRadius: 4)],
                      Icons.bolt,
                      size: 14,
                      color: Colors.grey[300],
                    ),
                ],
              ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
W/Adreno-GSL(23604): <sharedmem_gpuobj_alloc:3544>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(23604): <gsl_memory_alloc_pure_64:3791>: ERROR: kgsl_sharedmem_alloc() failed! Allocation size: (16 KB); Flags: (0x890c2500)
F/libc    (23604): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c in tid 23670 (1.raster), pid 23604 (.segfault_icons)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/b6quew/b6q:14/UP1A.231005.007/F741U1UES2AYA7:user/release-keys'
Revision: '14'
ABI: 'arm64'
Processor: '7'
Timestamp: 2025-02-27 09:36:20.330140268-0600
Process uptime: 13s
Cmdline: com.example.segfault_icons
pid: 23604, tid: 23670, name: 1.raster  >>> com.example.segfault_icons <<<
uid: 10451
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x000000000000001c
Cause: null pointer dereference
    x0  00000000ffffffff  x1  0000000000000000  x2  0000007057b79c44  x3  0000006c3b4152b8
    x4  0000000000000248  x5  0000000013f61ace  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  00000000ffffffff  x9  000000000058017e  x10 0000000000000320  x11 0000000000000002
    x12 000000000000ea4c  x13 0000006c0d5afe24  x14 0000000000004000  x15 0000000000000000
    x16 0000000000000000  x17 0000007057ae0488  x18 0000006c140b8000  x19 b400006dd8e62250
    x20 0000000000000003  x21 0000000000000001  x22 0000000000000003  x23 00000000ffffffff
    x24 0000000000000000  x25 0000000000000001  x26 0000000000000000  x27 0000000000000000
    x28 b400006e15208fe0  x29 0000006c3b4153c0
    lr  0000006c0d54730c  sp  0000006c3b4153b0  pc  0000006c0d54724c  pst 0000000060001000
47 total frames
backtrace:
      #00 pc 00000000000d524c  /vendor/lib64/hw/vulkan.adreno.so (!!!0000!65bb4f16e1c4caf7a56f18c58bd23d!11e73fe00cb!+252) (BuildId: 78d1f327f7b2936485f1cd8cd2abd2b1)
      #01 pc 000000000010aa04  /vendor/lib64/hw/vulkan.adreno.so (!!!0000!5d51db99116934eb298ea0edb653cf!11e73fe00cb!+2228) (BuildId: 78d1f327f7b2936485f1cd8cd2abd2b1)
      #02 pc 000000000010921c  /vendor/lib64/hw/vulkan.adreno.so (!!!0000!803c04a83cada1864e63faf3eba95b!11e73fe00cb!+412) (BuildId: 78d1f327f7b2936485f1cd8cd2abd2b1)
      #03 pc 00000000000ff350  /vendor/lib64/hw/vulkan.adreno.so (!!!0000!a8a5578ec7eb449d8c8076f2948068!11e73fe00cb!+880) (BuildId: 78d1f327f7b2936485f1cd8cd2abd2b1)
      #04 pc 00000000000fd3b0  /vendor/lib64/hw/vulkan.adreno.so (qglinternal::vkCmdBeginRenderPass(VkCommandBuffer_T*, VkRenderPassBeginInfo const*, VkSubpassContents)+960) (BuildId: 78d1f327f7b2936485f1cd8cd2abd2b1)
      #05 pc 0000000000028428  /system/lib64/libvulkan.so (vulkan::api::(anonymous namespace)::CmdBeginRenderPass(VkCommandBuffer_T*, VkRenderPassBeginInfo const*, VkSubpassContents)+136) (BuildId: 9b06a1f4deaf795678bf690c75f1f9af)
      #06 pc 0000000002129b38  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #07 pc 0000000002110f34  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #08 pc 0000000001d921f8  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #09 pc 00000000020c82d8  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #10 pc 00000000020c8230  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #11 pc 00000000020d9c9c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #12 pc 00000000020d9480  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #13 pc 00000000020d7b3c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #14 pc 00000000020d7a20  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #15 pc 00000000020ebfec  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #16 pc 00000000020b5320  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #17 pc 00000000020b6674  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #18 pc 0000000001d6ddac  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #19 pc 00000000020baa7c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #20 pc 0000000001d6e4dc  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #21 pc 0000000001d6d864  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #22 pc 0000000001d6dcfc  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #23 pc 00000000020bbdc0  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #24 pc 00000000021bfa80  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #25 pc 000000000203730c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #26 pc 00000000020371ec  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #27 pc 0000000002037274  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #28 pc 000000000214a0e8  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #29 pc 0000000002149b9c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #30 pc 0000000002148a38  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #31 pc 000000000214940c  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #32 pc 000000000214afd4  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #33 pc 0000000002148ea8  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #34 pc 0000000002148c40  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #35 pc 0000000002157370  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #36 pc 0000000001d077dc  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #37 pc 0000000001d0d364  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #38 pc 0000000000018b70  /system/lib64/libutils.so (android::Looper::pollInner(int)+1252) (BuildId: a0e0ad47138267db6c479fc556e32d00)
      #39 pc 0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124) (BuildId: a0e0ad47138267db6c479fc556e32d00)
      #40 pc 000000000001a184  /system/lib64/libandroid.so (ALooper_pollOnce+104) (BuildId: eed5d73f8789bca316be244a36f12599)
      #41 pc 0000000001d0d2ec  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #42 pc 0000000001d07728  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #43 pc 0000000001d0b5d0  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #44 pc 0000000001d0b468  /data/app/~~9THvwvO-pgtz9Mao7HzQ9Q==/com.example.segfault_icons-8NcS66-EN2_Q9LyOS0wHiw==/lib/arm64/libflutter.so (BuildId: 816a1a1c92b262314abb1fe2e9ff814ce75bf278)
      #45 pc 00000000000c37b4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 37f537c2ba9dcbb262a0a68f41a21da4)
      #46 pc 000000000005d084  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 37f537c2ba9dcbb262a0a68f41a21da4)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on Arch Linux 6.13.4-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### LINKED ISSUE #165116: [Impeller] Text with shadows decreases performance when using Impeller
### Steps to reproduce

1. Run the example (I tested on pixel 6, honor x8b, realme c30, huawei matepad 11.5), debug/release not important
2. Will scroll through the list, everything is nice and smooth
3. Bring back the shadow in the sample -
 shadows: [
  Shadow(
    blurRadius: 8.0,
    color: Colors.black.withValues(alpha: 0.24),
    offset: Offset(2.0, 2.0),
  ),
],
4. Scroll through the list, noticeable performance degradation
5. Run the example with - flutter run --no-enable-impeller
6. Everything is fine and smooth when text is shadowed

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Color(0xff6750a4),
          brightness: Brightness.light,
          dynamicSchemeVariant: DynamicSchemeVariant.tonalSpot,
        ),

        useMaterial3: true,
      ),

      debugShowCheckedModeBanner: false,
      home: const MainScreen(),
    );
  }
}

class MainScreen extends StatefulWidget {
  const MainScreen({super.key});

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Main', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [const TestListView(), const SizedBox(height: 8)],
        ),
      ),
    );
  }
}

class TestListView extends StatefulWidget {
  const TestListView({super.key});

  @override
  State<TestListView> createState() => _TestListViewState();
}

class _TestListViewState extends State<TestListView> {
  final PageController _pageController = PageController(initialPage: 0);

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        GridView.builder(
          itemCount: 64,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          padding: EdgeInsets.symmetric(horizontal: 8.0),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            crossAxisSpacing: 12.0,
            mainAxisSpacing: 12.0,
            childAspectRatio: 1.0,
          ),
          itemBuilder: (context, index) {
            return Card(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16.0),
              ),
              clipBehavior: Clip.antiAlias,
              child: Stack(
                fit: StackFit.expand,
                children: [
                  Image.asset('assets/images/kitty.jpeg', fit: BoxFit.cover),
                  Padding(
                    padding: const EdgeInsets.all(18.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisSize: MainAxisSize.max,
                      children: [
                        Expanded(
                          child: Text(
                            'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
                            overflow: TextOverflow.fade,
                            style: Theme.of(
                              context,
                            ).textTheme.titleLarge?.copyWith(
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                              // shadows: [
                              //   Shadow(
                              //     blurRadius: 8.0,
                              //     color: Colors.black.withValues(alpha: 0.24),
                              //     offset: Offset(2.0, 2.0),
                              //   ),
                              // ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ],
    );
  }
}

```

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

pixel 6
honor x8b
realme c30
huawei matepad 11.5

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.1, on macOS 15.3.1 24D70 darwin-arm64, locale ru-RU) [1 296ms]
    • Flutter version 3.29.1 on channel stable at /Users/denis/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 09de023485 (13 days ago), 2025-02-28 13:44:05 -0800
    • Engine revision 871f65ac1b
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [7,9s]
    • Android SDK at /Users/denis/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [2,4s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [15ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [14ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.98.1) [13ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (6 available) [7,8s]
    • Pixel 6 (mobile)                   • 26101FDF60002Q            • android-arm64  • Android 15 (API 35)
    • iPad (Денис) (wireless) (mobile)   • 00008030-001600623E22202E • ios            • iOS 18.3.1 22D72
    • iPhone (Денис) (wireless) (mobile) • 00008101-001564E21861401E • ios            • iOS 18.3.1 22D72
    • macOS (desktop)                    • macos                     • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop)    • mac-designed-for-ipad     • darwin         • macOS 15.3.1 24D70 darwin-arm64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 134.0.6998.89

[✓] Network resources [1 085ms]
    • All expected network resources are available.
```

</details>

### Screenshots

<details open><summary>Screenshots</summary>

Impeller-Shadows
Image
Impeller-Without Shadows
Image
Without Impeller-Shadows
Image

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/164303
Fixes https://github.com/flutter/flutter/issues/165116

When rendering a text shadow, cache the resulting snapshot for at least one frame. Only attempts to content-aware hash for single glyphs (Icons). in other cases the exact layout may be different enough that its not worth trying to cache.

### CODE REVIEW

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+
+  TextShadowCache& operator=(const TextShadowCache&) = delete;
+
+  struct TextShadowCacheData {
+    Entity entity;
+    bool used_this_frame = true;
+    Matrix key_matrix;
+  };
+
+  std::unordered_map<TextShadowCacheKey,
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:104]: absl::flat_hash_map is recommended ( https://github.com/abseil/abseil-cpp/blob/bcf4bf315ab25075b51ad1bca9da351aa4579c00/absl/container/flat_hash_map.h#L27 )

File: engine/src/flutter/impeller/entity/render_target_cache.cc [hunk 2]
```diff
@@ -33,6 +35,17 @@ void RenderTargetCache::End() {
   render_target_data_.swap(retain);
 }
 
+void RenderTargetCache::Disable() {
+  cache_disabled_count_++;
+}
+
+void RenderTargetCache::Enable() {
+  if (cache_disabled_count_ == 0) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/render_target_cache.cc:43]:
```suggestion
  FML_DCHECK(cache_disabled_count_ > 0);
  if (cache_disabled_count_ == 0) {
```

File: engine/src/flutter/impeller/entity/render_target_cache.cc [hunk 3]
```diff
@@ -54,19 +67,22 @@ RenderTarget RenderTargetCache::CreateOffscreen(
...
-      ColorAttachment color0 =
-          render_target_data.render_target.GetColorAttachment(0);
-      std::optional<DepthAttachment> depth =
-          render_target_data.render_target.GetDepthAttachment();
-      std::shared_ptr<Texture> depth_tex = depth ? depth->texture : nullptr;
-      return RenderTargetAllocator::CreateOffscreen(
-          context, size, mip_count, label, color_attachment_config,
-          stencil_attachment_config, color0.texture, depth_tex);
+
+  if (cache_disabled_count_ == 0) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/render_target_cache.cc:71]:
```suggestion
  if (RenderCacheEnabled()) {
```

File: engine/src/flutter/impeller/entity/render_target_cache.cc [hunk 4]
```diff
@@ -107,20 +123,22 @@ RenderTarget RenderTargetCache::CreateOffscreenMSAA(
...
-      ColorAttachment color0 =
-          render_target_data.render_target.GetColorAttachment(0);
-      std::optional<DepthAttachment> depth =
-          render_target_data.render_target.GetDepthAttachment();
-      std::shared_ptr<Texture> depth_tex = depth ? depth->texture : nullptr;
-      return RenderTargetAllocator::CreateOffscreenMSAA(
-          context, size, mip_count, label, color_attachment_config,
-          stencil_attachment_config, color0.texture, color0.resolve_texture,
-          depth_tex);
+  if (cache_disabled_count_ == 0) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/render_target_cache.cc:126]:
```suggestion
  if (RenderCacheEnabled()) {
```

File: engine/src/flutter/impeller/renderer/render_target.h [hunk 5]
```diff
@@ -177,6 +177,12 @@ class RenderTargetAllocator {
       const std::shared_ptr<Texture>& existing_color_resolve_texture = nullptr,
       const std::shared_ptr<Texture>& existing_depth_stencil_texture = nullptr);
 
+  /// @brief Disable the cache until another call to enable.
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/renderer/render_target.h:180]: This docstring talks about a cache but there is no description of anything as a cache in `RenderTargetAllocator`.  The details of `RenderTargetCache` are creeping into its superclass.  Can't we just put this into the render cache directly?  When we call it we seem to know we have a RenderTargetCache (`renderer.GetRenderTargetCache()->Enable();`)

File: engine/src/flutter/impeller/typographer/text_frame.cc [hunk 6]
```diff
@@ -146,6 +146,17 @@ bool TextFrame::IsFrameComplete() const {
   return bound_values_.size() == run_size;
 }
 
+Font TextFrame::GetFont() const {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/typographer/text_frame.cc:149]: Should this return a `const Font&`?  I don't know how heavy those are.

File: engine/src/flutter/impeller/entity/contents/content_context.h [hunk 7]
```diff
@@ -294,6 +295,8 @@ class ContentContext {
   /// allocate their own device buffers.
   HostBuffer& GetTransientsBuffer() const { return *host_buffer_; }
 
+  TextShadowCache& GetTextShadowCache() const { return *text_shadow_cache_; }
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/content_context.h:298]: For the same reason we don't use const refs anywhere else on content_context, I can't make this return a const ref. If we want to go through at some point and make renderer not `const` I would be in favor of that.

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 8]
```diff
@@ -1467,6 +1467,48 @@ bool Canvas::Restore() {
...
+      /*p_max_basis=*/entity.GetTransform().GetMaxBasisLengthXY(),
+      /*p_identifier=*/identifier,
+      /*p_is_single_glyph=*/maybe_glyph.has_value(),
+      /*p_font=*/text_frame->GetFont(),
+      /*p_sigma=*/paint.mask_blur_descriptor->sigma);
+
+  std::optional<Entity> result = renderer_.GetTextShadowCache().Lookup(
+      renderer_, entity, filter, cache_key);
+  if (result.has_value()) {
+    AddRenderEntityToCurrentPass(result.value(), false);
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/canvas.cc]: Done

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 9]
```diff
@@ -1467,6 +1467,48 @@ bool Canvas::Restore() {
...
+  TextShadowCache::TextShadowCacheKey cache_key(
+      /*p_max_basis=*/entity.GetTransform().GetMaxBasisLengthXY(),
+      /*p_identifier=*/identifier,
+      /*p_is_single_glyph=*/maybe_glyph.has_value(),
+      /*p_font=*/text_frame->GetFont(),
+      /*p_sigma=*/paint.mask_blur_descriptor->sigma);
+
+  std::optional<Entity> result = renderer_.GetTextShadowCache().Lookup(
+      renderer_, entity, filter, cache_key);
+  if (result.has_value()) {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/canvas.cc:1506]: Yes. Fixed

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.cc [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+void TextShadowCache::MarkFrameEnd() {
+  std::vector<TextShadowCacheKey> to_remove;
+  for (auto& entry : entries_) {
+    if (!entry.second.used_this_frame) {
+      to_remove.push_back(entry.first);
+    }
+  }
+  for (const auto& key : to_remove) {
+    entries_.erase(key);
+  }
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.cc]: Neato. Though also see comment on absl

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h [hunk 11]
```diff
@@ -0,0 +1,113 @@
...
+
+  ~TextShadowCache() = default;
+
+  /// @brief A key to look up cached glyph textures.
+  struct TextShadowCacheKey {
+    Scalar max_basis;
+    int64_t identifier;
+    bool is_single_glyph;
+    Font font;
+    Sigma sigma;
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:43]: That wasn't ultimately the issue though. since we're given this as a floating point sigma and not rounding, it doesn't seem to me like we can convert to a rational unless we also round?

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:104]: I can switch this but unfortuately flat_hash_map (https://abseil.io/docs/cpp/guides/container)

> Guarantees an O(1) erase method by returning void instead of an iterator.

I think erasing invalidates the iterator so I can't do the optimization you asked for above. Which would you prefer.

File: engine/src/flutter/impeller/entity/render_target_cache.cc (hunk 2 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/render_target_cache.cc:48]: Done

File: engine/src/flutter/impeller/entity/render_target_cache.cc (hunk 3 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/render_target_cache.cc]: Done

File: engine/src/flutter/impeller/entity/render_target_cache.cc (hunk 4 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/render_target_cache.cc]: Done

File: engine/src/flutter/impeller/renderer/render_target.h (hunk 5 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/render_target.h:180]: It is leaky, that is true. That said, if there is no cache then there is no harm in calling enable/disable.

File: engine/src/flutter/impeller/typographer/text_frame.cc (hunk 6 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/typographer/text_frame.cc]: Done

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 12]
```diff
@@ -1467,6 +1467,50 @@ bool Canvas::Restore() {
...
+  //              https://github.com/flutter/flutter/issues/133297
+  std::shared_ptr<FilterContents> filter =
+      paint.mask_blur_descriptor->CreateMaskBlur(
+          FilterInput::Make(text_contents),
+          /*is_solid_color=*/true, GetCurrentTransform());
+
+  std::optional<Glyph> maybe_glyph = text_frame->AsSingleGlyph();
+  int64_t identifier = maybe_glyph.has_value()
+                           ? maybe_glyph.value().index
+                           : reinterpret_cast<int64_t>(text_frame.get());
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/display_list/canvas.cc:1496]: question for @gaaclarke : is this safe/reasonable? The goal is only caching the same text frame. An alternative approach would be to have an ID system somewhere

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:104]: If you use `absl::flat_hash_map`, you can use `absl::remove_if` to do this really easily.

Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:104]: Or `absl::erase_if` maybe in this case.

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h (hunk 11 above)
[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h:43]: > it doesn't seem to me like we can convert to a rational unless we also round?

I just noticed you aren't rounding sigma in your hash function.  You're going to have to do that because of the instability of floating point numbers.  You need to choose some resolution you care about.  You can put the round in the hash function but it's harder to work with since you can't easily query it in the debugger.  That's why I recommend the rational.

File: engine/src/flutter/impeller/renderer/render_target.h (hunk 5 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/renderer/render_target.h:180]: I think the names `RenderTargetAllocator::EnableCache` `RenderTargetAllocator::DisableCache` make more sense since you aren't disabling the allocator.

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 12 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc:1496]: I think so.  Worst case scenario is that the text_frame gets copied and you get a cache miss.  Since we have a std::shared_ptr to it I don't expect we'll copy it (but I wouldn't rule it out).

Doesn't the TextFrame have a font itself too?  It's weird that we hash on the identifier which represents a font and have the font separately.  Can the TextFrame be mutated?

Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/canvas.cc:1496]: Yeah hashing the font is for the "single glyph" optimization for Icons, but its unnecessary for the general text frame case.

File: engine/src/flutter/impeller/display_list/dl_dispatcher.cc [hunk 13]
```diff
@@ -1333,12 +1333,14 @@ std::shared_ptr<Texture> DisplayListToTexture(
   );
   const auto& [data, count] = collector.TakeBackdropData();
   impeller_dispatcher.SetBackdropData(data, count);
+  context.GetContentContext().GetTextShadowCache().MarkFrameStart();
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/dl_dispatcher.cc:1337]: Done

File: engine/src/flutter/impeller/display_list/dl_dispatcher.cc [hunk 14]
```diff
@@ -1366,11 +1368,13 @@ bool RenderToTarget(ContentContext& context,
   );
   const auto& [data, count] = collector.TakeBackdropData();
   impeller_dispatcher.SetBackdropData(data, count);
+  context.GetTextShadowCache().MarkFrameStart();
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/dl_dispatcher.cc:1374]: Done

File: engine/src/flutter/impeller/renderer/render_target.h (hunk 5 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/render_target.h]: Done

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.cc (hunk 10 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.cc]: Done

File: engine/src/flutter/impeller/entity/contents/text_shadow_cache.h (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_shadow_cache.h]: Done

**Review by gaaclarke — APPROVED** [review]
lgtm! thanks
