### PR TITLE
Correct InheritedTheme.captureAll() for multiple theme ancestors of the same type

### LINKED ISSUE #39087: InheritedTheme.captureAll() can fail when multiple theme ancestors of the same type exist
If two or more InheritedThemes of the same type are visible in both the "capture" and "wrap" contexts then InheritedTheme.captureAll() returns a widget that includes the wrong themes.

The following widget demos the problem. 

```
class DemoHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IconTheme(
        data: IconThemeData(color: Colors.blue),
        child: IconTheme(
          data: IconThemeData(size: 48, color: Colors.green),
          child: Center(
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Icon(Icons.add),
                Builder(
                  builder: (BuildContext context) {
                    return InheritedTheme.captureAll(context, Icon(Icons.add));
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
The result is this:
image

The result should be this:
image

The problem occurs because InheritedTheme.captureAll() "captures" both IconTheme widgets. The widget returned by InheritedTheme.captureAll() doesn't wrap its child with the inner green IconTheme because the identically same IconTheme is visible from the context it's built in. It does wrap its child with the outer blue IconTheme because it is not identical to the IconTheme that's visible form the context it's built in.

Assuming that inherited themes don't accumulate, i.e. that an inner theme completely shadows an outer one, InheritedTheme.captureAll() only needs to record the first theme of any one type.

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #39087

### CODE REVIEW

File: packages/flutter/lib/src/widgets/inherited_theme.dart [hunk 1]
```diff
@@ -114,10 +114,18 @@ abstract class InheritedTheme extends InheritedWidget {
     assert(context != null);
 
     final List<InheritedTheme> themes = <InheritedTheme>[];
+    final Set<Type> themeTypes = <Type>{};
     context.visitAncestorElements((Element ancestor) {
       if (ancestor is InheritedElement && ancestor.widget is InheritedTheme) {
         final InheritedTheme theme = ancestor.widget;
-        themes.add(theme);
+        final Type themeType = theme.runtimeType;
```
Comment (johnsonmh) [inline packages/flutter/lib/src/widgets/inherited_theme.dart]: Rather than only recording one theme of each type, could you instead pass `themes.reversed` to `_CaptureAll(...)` below? That way it's a slightly more accurate recreation of the "`Theme`" tree.

I highly doubt this ever happens, but if you had `Theme(child: IconTheme(child: Theme(...)))`, and the `IconTheme` called `Theme.of(context)`, we'd still want it to return the outer theme.

**Review by johnsonmh — APPROVED** [review]
LGTM!

**Review by darrenaustin — APPROVED** [review]
LGTM.

File: packages/flutter/lib/src/widgets/inherited_theme.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/inherited_theme.dart]: The theme wrapping does proceed inside-out (so to speak).  The source of the problem being fixed here was the InheritTheme wrap methods which look like:
```
  Widget wrap(BuildContext context, Widget child) {
    final IconTheme ancestorTheme = context.ancestorWidgetOfExactType(IconTheme);
    return identical(this, ancestorTheme) ? child : IconTheme(data: data, child: child);
  }
```
The identical test defends against the common case where the same inherited theme is visible in both the captureAll() and the wrap() contexts. When the same theme is visible in both contexts we don't bother wrapping a copy of the theme around the child. 

The source of the bug was the result of applying this test to an outer theme that was shadowed by an inner theme of the same type.  In that case the code was mistakenly wrapping the child with the outer theme because it wasn't identical to the inner one. Since the outer theme is shadowed by the inner one, we now just discard it in captureAll().

You're right that one could create an InheritedTheme whose build method created a dependency on the same type of theme. We definitely don't have"cascading" themes that work in this way although, currently we don't do anything to actively prevent it.
