### PR TITLE
`CupertinoPicker` new onChanged behaviour

### LINKED ISSUE #170201: `CupertinoPicker` should report item change only on scroll end
_This is a continuation of https://github.com/flutter/flutter/issues/169606_

### Steps to reproduce

Scroll the picker over multiple items.

### Expected results

Native picker only reports the change when the scroll settles.

### Actual results

onSelectedItemChanged is called every time a new item is scrolled over.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

/// Flutter code sample for [CupertinoPicker].

const double _kItemExtent = 32.0;
const List<String> _fruitNames = <String>[
  'Apple',
  'Mango',
  'Banana',
  'Orange',
  'Pineapple',
  'Strawberry',
];

void main() => runApp(const CupertinoPickerApp());

class CupertinoPickerApp extends StatelessWidget {
  const CupertinoPickerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(brightness: Brightness.light),
      home: CupertinoPickerExample(),
    );
  }
}

class CupertinoPickerExample extends StatefulWidget {
  const CupertinoPickerExample({super.key});

  @override
  State<CupertinoPickerExample> createState() => _CupertinoPickerExampleState();
}

class _CupertinoPickerExampleState extends State<CupertinoPickerExample> {
  int _selectedFruit = 0;

  // This shows a CupertinoModalPopup with a reasonable fixed height which hosts CupertinoPicker.
  void _showDialog(Widget child) {
    showCupertinoModalPopup<void>(
      context: context,
      builder:
          (BuildContext context) => Container(
            height: 216,
            padding: const EdgeInsets.only(top: 6.0),
            // The Bottom margin is provided to align the popup above the system navigation bar.
            margin: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
            // Provide a background color for the popup.
            color: CupertinoColors.systemBackground.resolveFrom(context),
            // Use a SafeArea widget to avoid system overlaps.
            child: SafeArea(top: false, child: child),
          ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(middle: Text('CupertinoPicker Sample')),
      child: DefaultTextStyle(
        style: TextStyle(color: CupertinoColors.label.resolveFrom(context), fontSize: 22.0),
        child: Center(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('Selected fruit: '),
              CupertinoButton(
                padding: EdgeInsets.zero,
                // Display a CupertinoPicker with list of fruits.
                onPressed:
                    () => _showDialog(
                      CupertinoPicker(
                        magnification: 1.22,
                        squeeze: 1.2,
                        useMagnifier: true,
                        itemExtent: _kItemExtent,
                        // This sets the initial item.
                        scrollController: FixedExtentScrollController(initialItem: _selectedFruit),
                        // This is called when selected item is changed.
                        onSelectedItemChanged: (int selectedItem) {
                          setState(() {
                            _selectedFruit = selectedItem;
                          });
                        },
                        children: List<Widget>.generate(_fruitNames.length, (int index) {
                          return Center(child: Text(_fruitNames[index]));
                        }),
                      ),
                    ),
                // This displays the selected fruit name.
                child: Text(_fruitNames[_selectedFruit], style: const TextStyle(fontSize: 22.0)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.33.0-1.0.pre.417, on macOS 15.5 24F74 darwin-arm64, locale en-GB) [8.3s]
    ! Flutter version 3.33.0-1.0.pre.417 on channel [user-branch] at /Users/alex/workspace/flutter_fork
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository https://github.com/flutter/flutter.git/ is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/flutter/flutter.git/ to dismiss this error.
    • Framework revision e9e989bef3 (5 hours ago), 2025-06-07 07:45:31 -0400
    • Engine revision e9e989bef3
    • Dart version 3.9.0 (build 3.9.0-211.0.dev)
    • DevTools version 2.48.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.1s]
    • Android SDK at /Users/alex/Library/Android/sdk
    • Emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.4) [1,360ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    ! CocoaPods 1.13.0 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [13ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2) [12ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.100.3) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.112.0

[✓] Connected device (3 available) [7.0s]
    • Alex’s iPhone (wireless) (mobile) • 00008130-001A310C0491401C            • ios          • iOS 18.5 22F76
    • iPhone 16 Pro (mobile)            • CA350618-1F12-428B-ABB3-9D688B09D1F4 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)                   • macos                                • darwin-arm64 • macOS 15.5 24F74 darwin-arm64

[✓] Network resources [856ms]
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

### PR DESCRIPTION
**Pull request by alex-medinsh**
This PR adds a new behaviour to `ListWheelScrollView` that allows to switch between reporting changes on scroll update or only on scroll end. 
`CupertinoPicker` now has a `changeReportingBehavior` param that forwards to `ListWheelScrollView`.

New behaviour is a breaking change if set as default, so I have added the `changeReportingBehavior` param to opt-in. My idea is that it can be marked as `Deprecated` immediately and then removed from `CupertinoPicker` later or we can just leave the param there and make it more customizable.

I am open to other ideas on how to land this without breaking clients.

Fixes https://github.com/flutter/flutter/issues/170201

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by alex-medinsh** [comment]
I might try to also make these changes for CupertinoDatePicker depending on how this one goes.

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 1]
```diff
@@ -89,6 +89,7 @@ class CupertinoPicker extends StatefulWidget {
     this.magnification = 1.0,
     this.scrollController,
     this.squeeze = _kSqueeze,
+    this.changeReportingBehavior = ChangeReportingBehavior.onScrollUpdate,
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/picker.dart:92]: Thanks for trying to land this with as little breakage as possible. I'm guessing having it default to onScrollUpdate is because of [this comment](https://github.com/flutter/flutter/issues/92644#issuecomment-1518148605)? Although since the goal is to match native we might have to just break directly. I'm not really sure how to proceed, @MitchellGoodwin what do you think?

Comment (alex-medinsh) [reply packages/flutter/lib/src/cupertino/picker.dart:92]: Haven't seen that comment, actually.

My hunch is that, even though the current behaviour is a "bug", some folks might have had some logic built around it, so I didn't want to outright break it. 

It's your call, I'm fine with any decision.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/picker.dart:92]: In my opinion, have it default to the non-breaking behavior, and call out that the default behavior is the other enum option in the documentation. When this reaches stable, we can recommend setting the enum to the right value to get native behavior, then if we change the default after that we'll have given warning, and we can possibly do a dart fix. Changing the functional behavior suddenly is a little dangerous, and easy to miss in communications.

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 2]
```diff
@@ -187,6 +189,12 @@ class CupertinoPicker extends StatefulWidget {
   /// Defaults to `1.45` to visually mimic iOS.
   final double squeeze;
 
+  /// The behavior of reporting the selected item index.
+  ///
+  /// This determines when the `onSelectedItemChanged` callback is called.
+  /// Defaults to [ChangeReportingBehavior.onScrollUpdate].
+  final ChangeReportingBehavior changeReportingBehavior;
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/picker.dart:200]: We should mention what the default native behavior is, and the current version of iOS.

File: packages/flutter/lib/src/cupertino/picker.dart (hunk 1 above)
Comment (alex-medinsh) [reply packages/flutter/lib/src/cupertino/picker.dart:92]: Since it is a new optional parameter, I am not sure that folks will notice a change in the documentation that doesn't force them to do something to acknowledge the new behaviour.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/picker.dart:92]: They might miss it, yes. But we can highlight it in the release blog and breaking change guides before it's made default to create some resources. Mentioning it in the docs is more for helping with a migration and future understanding, rather than informing the developers that a breaking change is happening.

**Comment by alex-medinsh** [comment]
@MitchellGoodwin am I understanding correctly that you are ok with landing this as-is and breaking in a later PR?

File: packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart [hunk 3]
```diff
@@ -748,17 +767,30 @@ class _ListWheelScrollViewState extends State<ListWheelScrollView> {
...
-        _lastReportedItemIndex = currentItemIndex;
-        final int trueIndex = widget.childDelegate.trueIndexOf(currentItemIndex);
-        widget.onSelectedItemChanged!(trueIndex);
+    if (widget.onSelectedItemChanged == null ||
+        notification.depth != 0 ||
+        notification.metrics is! FixedExtentMetrics) {
+      return false;
+    }
+
+    if (widget.changeReportingBehavior == ChangeReportingBehavior.onScrollEnd) {
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart]: Nit: prefer the check on the ChangeReportingBehavior enum to be a switch statement, rather than an if, else. It's more future proof if other options are added to the enum.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM with one nit. Thank you for the change!

**Comment by MitchellGoodwin** [comment]
> @MitchellGoodwin am I understanding correctly that you are ok with landing this as-is and breaking in a later PR?

Yup!

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 4]
```diff
@@ -187,6 +189,16 @@ class CupertinoPicker extends StatefulWidget {
   /// Defaults to `1.45` to visually mimic iOS.
   final double squeeze;
 
+  /// The behavior of reporting the selected item index.
+  ///
+  /// This determines when the `onSelectedItemChanged` callback is called.
+  ///
+  /// Native iOS 18 behavior is [ChangeReportingBehavior.onScrollEnd], which
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/picker.dart:196]: Should the version number be specified here? I don't think this was a behavior that changed with iOS 18. If the behavior was previously `onScrollUpdate` and changed to `onScrollEnd`, then we should call out the iOS version where that changed and add a '+' at the end ('Native iOS 14+ behavior'). Else, it could just be `Native iOS behavior` imo.

**Review by victorsanni — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart (hunk 3 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart]: +1

File: packages/flutter/lib/src/cupertino/picker.dart (hunk 4 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/picker.dart:196]: I think mentioning the version number is helpful for telling if it's out of date in the future. I think saying iOS 18 is sufficient. We could dig up when the change happened, but I'm not sure if it's necessary.

**Review by victorsanni — APPROVED** [review]
