### PR TITLE
Fixes `FadeInImage` to follow gapless playback

### LINKED ISSUE #94540: `FadeInImage` works unexpectedly
When changing the image while the app is running, `FadeInImage` seems to work unexpectedly. 

Steps to Reproduce: 
Run the sample code (tested on Android and Linux, master and stable branches).
1. A blue box appears, shortly later, it fades out and image 1 (mountains) fades in.
2. Click on the image. Image 1 disappears, nothing appears for a while. Then the blue box appears and quickly fades out, fading in image 2 (bird).
3. Click again. Image 2 disappears, and then (same as 2) occurs, fading in image 1.
4. Click again. Image 2 appears immediately.
5. Click again. (Same as 1) occurs.
6. Click again. (Same as 4) occurs. 
And then it loops between them.

Expected behavior:
1. Expected.
2. The blue box should be shown as a placeholder instead of nothing.
3. Since image 1 is cached now, there should not be any loading, it should appear immediately. But looking at the download speed in the top bar, it can be seen that image 1 is getting downloaded every time (same on Linux).
4. Expected
5. Same as 3
6. Expected

Video on OnePlus 7T running Android 11. Tested on Linux (details in flutter doctor) and got the same results.

https://user-images.githubusercontent.com/44755140/144480091-c72a99ec-38ec-434d-aedd-39b72223e4d8.mp4

<details>
<summary>sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool img = false;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        setState(() {
          img = !img;
        });
      },
      child: FadeInImage(
        placeholder: Image.network(
          'http://jacksonmetalroof.com/wp-content/uploads/2016/06/metal-roofing-color-gallery-blue-180x180.png',
        ).image,
        image: Image.network(
          img
              ? 'https://wallup.net/wp-content/uploads/2019/09/07/762373-postcard-paper-poster-advertising-vintage-retro-antique-christmas.jpg'
              : 'https://wallup.net/wp-content/uploads/2019/05/10/1003575-usa-parks-scenery-mountains-forests-california-clouds-kings-canyon-national-park-nature-wallpapers.jpg',
        ).image,
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on Pop!_OS 20.04 LTS 5.13.0-7620-generic,
    locale en_US.UTF-8)
    • Flutter version 2.5.0 at /home/werain/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/werain/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.1
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 20.04 LTS 5.13.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.45
```
</details>

### PR DESCRIPTION
**Pull request by werainkhatri**
`FadeInImage` does not follow [gapless playback](https://api.flutter.dev/flutter/widgets/Image/gaplessPlayback.html), even though it is documented in the last line of [its documentation](https://api.flutter.dev/flutter/widgets/FadeInImage-class.html).

This is a regression, caused in #33370.

Fixes #94540 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

## Bugs needed to be fixed:

- [ ] When using two images, as in the issue's code sample, one of them is not cached (the first one to be specific), while the other is.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 1]
```diff
@@ -486,31 +486,47 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
...
-      (dynamic value) => Tween<double>(begin: value as double),
-    ) as Tween<double>?;
-    _placeholderOpacity = visitor(
-      _placeholderOpacity,
-      widget.isTargetLoaded ? 0.0 : 1.0,
-      (dynamic value) => Tween<double>(begin: value as double),
-    ) as Tween<double>?;
+  void didUpdateWidget(_AnimatedFadeOutFadeIn oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    if(oldWidget.fadeInDuration + oldWidget.fadeOutDuration != duration) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:512]: nit: space after if

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 2]
```diff
@@ -486,31 +486,47 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
   _AnimatedFadeOutFadeInState createState() => _AnimatedFadeOutFadeInState();
 }
 
-class _AnimatedFadeOutFadeInState extends ImplicitlyAnimatedWidgetState<_AnimatedFadeOutFadeIn> {
-  Tween<double>? _targetOpacity;
-  Tween<double>? _placeholderOpacity;
+class _AnimatedFadeOutFadeInState extends State<_AnimatedFadeOutFadeIn> with SingleTickerProviderStateMixin<_AnimatedFadeOutFadeIn> {
+  late final AnimationController controller = AnimationController(
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:490]: all these properties should be private.

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 3]
```diff
@@ -486,31 +486,47 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
...
+    duration: duration,
+    debugLabel: kDebugMode ? widget.toStringShort() : null,
+    vsync: this,
+  );
+  late final Animation<double> animation = CurvedAnimation(parent: controller, curve: Curves.linear);
+  final Tween<double> _targetOpacity = Tween<double>(begin: 0.0, end: 1.0);
+  final Tween<double> _placeholderOpacity = Tween<double>(begin: 1.0, end: 0.0);
   Animation<double>? _targetOpacityAnimation;
   Animation<double>? _placeholderOpacityAnimation;
+  late Duration duration = widget.fadeOutDuration + widget.fadeInDuration;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:500]: why do you need a seperate duration field? Cann you just use controller.duration?

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 4]
```diff
@@ -486,31 +486,47 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
...
   }
 
   @override
+  void dispose() {
+    (animation as CurvedAnimation).dispose();
+    controller.dispose();
+    super.dispose();
+  }
+
   void didUpdateTweens() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:526]: Should be private if no longer an override

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 5]
```diff
@@ -486,31 +486,47 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
...
+    if(oldWidget.fadeInDuration + oldWidget.fadeOutDuration != duration) {
+      duration = widget.fadeInDuration + widget.fadeOutDuration;
+      controller.duration = duration;
+    }
+    didUpdateTweens();
   }
 
   @override
+  void dispose() {
+    (animation as CurvedAnimation).dispose();
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:521]: Just type animation property as CurvedAnimation to avoid the cast.

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 6]
```diff
@@ -530,24 +546,22 @@ class _AnimatedFadeOutFadeInState extends ImplicitlyAnimatedWidgetState<_Animate
...
-    if (!widget.isTargetLoaded && _isValid(_placeholderOpacity!) && _isValid(_targetOpacity!)) {
-      // Jump (don't fade) back to the placeholder image, so as to be ready
-      // for the full animation when the new target image becomes ready.
-      controller.value = controller.upperBound;
-    }
 
+    if (!widget.isTargetLoaded && isTargetLoaded)
+      controller.reset();
+
+    if(widget.isTargetLoaded)
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:557]: space after if

File: packages/flutter/test/widgets/fade_in_image_test.dart [hunk 7]
```diff
@@ -156,7 +156,66 @@ Future<void> main() async {
       expect(findFadeInImage(tester).target.opacity, 1);
     });
 
-    testWidgets('shows a cached image immediately when skipFadeOnSynchronousLoad=true', (WidgetTester tester) async {
+    testWidgets('re-animates updated uncached image', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/fade_in_image_test.dart:159]: This test appears to pass on master even without your change.

File: packages/flutter/test/widgets/fade_in_image_test.dart [hunk 8]
```diff
@@ -172,6 +231,30 @@ Future<void> main() async {
       expect(findFadeInImage(tester).target.opacity, 1);
     });
 
+    testWidgets('shows second cached image immediately', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/fade_in_image_test.dart:234]: Same with this one.

**Review by goderbauer — COMMENTED** [review]
It is not clear to me what this PR is trying to fix. Both provided test cases appear to be passing on master even without the change. Either the test cases are not covering the change or the existing implementation does already what the tests expect.

File: packages/flutter/test/widgets/fade_in_image_test.dart (hunk 7 above)
Comment (werainkhatri) [reply packages/flutter/test/widgets/fade_in_image_test.dart:159]: Improved this test. Now it fails on master, as when the image is changed to an uncached image, the placeholder isn't shown until the animation starts.

**Comment by goderbauer** [comment]
I looked at https://github.com/flutter/flutter/issues/94540 and I agree that FadeInImage is behaving strangely today when switching out the `image`. We actually documented what should happen if you do this in https://master-api.flutter.dev/flutter/widgets/FadeInImage-class.html:

> When either placeholder or image changes, this widget continues showing the previously loaded image (if any) until the new image provider provides a different image. This is known as "gapless playback" (see also Image.gaplessPlayback).

That used to be the behavior and something broke it. We should restore that behavior. However, as far as I can tell, this PR is not quite doing that. Instead, it is showing the placeholder again.

**Comment by goderbauer** [comment]
My suspicion is actually that the bug is on this line: https://github.com/flutter/flutter/blob/d063961dda02ee1488daf3e5b336bc64060f4691/packages/flutter/lib/src/widgets/fade_in_image.dart#L432

After we have loaded the target image for the first time, `isTargetLoaded ` is correctly switched to true. But when you replace it with a new image, it switches back to false to show the placeholder again. That's incorrect it should continue to show the target image.

**Comment by goderbauer** [comment]
These lines also look problematic for that:

https://github.com/flutter/flutter/blob/d063961dda02ee1488daf3e5b336bc64060f4691/packages/flutter/lib/src/widgets/fade_in_image.dart#L418-L421

Once we have loaded the target once, we shouldn't be resetting the animation, I think.

**Comment by goderbauer** [comment]
I actually suspect we broke this all the way back in https://github.com/flutter/flutter/pull/33370.

**Comment by werainkhatri** [comment]
> We actually documented what should happen if you do this in https://master-api.flutter.dev/flutter/widgets/FadeInImage-class.html:
>> When either placeholder or image changes, this widget continues showing the previously loaded image (if any) until the new image provider provides a different image. This is known as "gapless playback" (see also Image.gaplessPlayback).

I totally missed that. I understand now why `ImplicitAnimatedWidget` is the correct candidate. I'll try to go over the previous PR and fix this instead.

**Comment by werainkhatri** [comment]
> After we have loaded the target image for the first time, isTargetLoaded is correctly switched to true. But when you replace it with a new image, it switches back to false to show the placeholder again. That's incorrect it should continue to show the target image.

Does the new image fade in (fading out the old one)? Or does it replace it as soon as the new one is loaded?

**Comment by werainkhatri** [comment]
> After we have loaded the target image for the first time, isTargetLoaded is correctly switched to true. But when you replace it with a new image, it switches back to false to show the placeholder again. That's incorrect it should continue to show the target image.

Should the new image animate in (fading out the old one) or not?

**Comment by goderbauer** [comment]
What does `Image.gaplessPlayback` do by default? That's what we should do here as well.

**Comment by werainkhatri** [comment]
> What does `Image.gaplessPlayback` do by default? That's what we should do here as well.

It updates the image as soon as the new one loads. Will do the same here.

**Comment by werainkhatri** [comment]
I have fixed the playback bug, but can't seem to understand how to fix the other bug (stated in the issue and this PR's description).

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 9]
```diff
@@ -416,9 +412,24 @@ class _FadeInImageState extends State<FadeInImage> {
...
+          assert(_oldImage != null);
+          if (frame == null) {
+            // Target image is still loading.
+            return _oldImage!;
+          } else {
+            // Target image has loaded.
+            _oldImage = child;
+            return child;
+          }
+        } else if(frame != null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:429]: nit: space after if

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 10]
```diff
@@ -416,9 +412,24 @@ class _FadeInImageState extends State<FadeInImage> {
       fit: widget.fit,
       frameBuilder: (BuildContext context, Widget child, int? frame, bool wasSynchronouslyLoaded) {
         if (wasSynchronouslyLoaded) {
-          _resetAnimations();
+          _oldImage = child;
           return child;
         }
+        if (_imageAnimation.isCompleted) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:418]: Is all this necessary? I naively expected that we would just need an instance variable (e.g. `targetLoaded = false`) and set that to true the first time `frame != null`. Then on line 443, we just pass `targetLoaded` to `isTargetLoaded`.

Maybe I am missing something, though?

Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: 1. If you make the above-suggested change, run the sample code (attached in the issue), and you change the image (by clicking) a few times, after 4 changes (clicks) the view goes blank, and nothing will happen after any further clicks. This is because, after 3 clicks, the image changes to a loaded image, setting `wasSynchronouslyLoaded` to true, disposing `_AnimatedFadeOutFadeIn` and the animations. Now when the 4th click occurs, `_AnimatedFadeOutFadeIn` is rebuilt, resetting the opacity animations. This can be fixed by removing the `wasSynchronouslyLoaded` if statement, so that `_AnimatedFadeOutFadeIn` is never disposed.
2. IMO the `_AnimatedFadeOutFadeIn` widget should be added to the tree only when the actual fade-out-fade-in is required, and removed when not. The above change (along with point 1) will cause it to exist on the tree forever.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: It would be more performant by keeping the subtree the same, otherwise, they may be built from scratch

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: I can't reproduce the issue you mention after 4 clicks. This is the code i use

```dart
frameBuilder: (BuildContext context, Widget child, int? frame, bool wasSynchronouslyLoaded) {
        if (wasSynchronouslyLoaded) {
          _oldImage = child;
          return child;
        }
        if (frame != null) {
          // This is the first image.
          _oldImage = child;
        }
        return _AnimatedFadeOutFadeIn(
          target: child,
          targetProxyAnimation: _imageAnimation,
          placeholder: _image(
            image: widget.placeholder,
            errorBuilder: widget.placeholderErrorBuilder,
            opacity: _placeholderAnimation,
            fit: widget.placeholderFit ?? widget.fit,
          ),
          placeholderProxyAnimation: _placeholderAnimation,
          isTargetLoaded: _oldImage != null,
          fadeInDuration: widget.fadeInDuration,
          fadeOutDuration: widget.fadeOutDuration,
          fadeInCurve: widget.fadeInCurve,
          fadeOutCurve: widget.fadeOutCurve,
        );
      },
```

The issue with the current code is that after the image is faded in, it will cause a   an unnecessary rebuild to dispose _AnimatedFadeOutFadeIn and rebuild the image widget which is not ideal

Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: you'll be able to reproduce the issue with below:

> we would just need an instance variable (e.g. targetLoaded = false) and set that to true the first time frame != null. Then on line 443, we just pass targetLoaded to isTargetLoaded.

<details>
<summary>code</summary>

```dart
  // Widget? _oldImage;
  bool targetLoaded = false;
```
...
```dart
    Widget result = _image(
      image: widget.image,
      errorBuilder: widget.imageErrorBuilder,
      opacity: _imageAnimation,
      fit: widget.fit,
      frameBuilder: (BuildContext context, Widget child, int? frame, bool wasSynchronouslyLoaded) {
        if (wasSynchronouslyLoaded) {
          return child;
        }
        if (frame != null) {
          targetLoaded = true;
        }
        return _AnimatedFadeOutFadeIn(
          target: child,
          targetProxyAnimation: _imageAnimation,
          placeholder: _image(
            image: widget.placeholder,
            errorBuilder: widget.placeholderErrorBuilder,
            opacity: _placeholderAnimation,
            fit: widget.placeholderFit ?? widget.fit,
          ),
          placeholderProxyAnimation: _placeholderAnimation,
          isTargetLoaded: targetLoaded, // _oldImage != null
          fadeInDuration: widget.fadeInDuration,
          fadeOutDuration: widget.fadeOutDuration,
          fadeInCurve: widget.fadeInCurve,
          fadeOutCurve: widget.fadeOutCurve,
        );
      },
    );
```
</details>

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: > disposing _AnimatedFadeOutFadeIn and the animations. Now when the 4th click occurs, _AnimatedFadeOutFadeIn is rebuilt, resetting the opacity animations.

Wheere does the animations is disposed? It looks like we do need to reset the animation when the `wasSynchronouslyLoaded` is true to prepare for future rebuilds?

Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:418]: > Where does the animations is disposed?

my bad, animations are not disposed, just the widget.

> It looks like we do need to reset the animation when the wasSynchronouslyLoaded is true to prepare for future rebuilds?

As per gapless playback, there won't be any future animations. The old image will just be replaced by the new one after it is loaded.

**Comment by werainkhatri** [comment]
@chunhtai @goderbauer I have made some improvements to the code. Now, the `_AnimatedFadeInFadeOut` widget will never leave the tree (never dispose) and sync logic is passed on for it to handle internally.

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 11]
```diff
@@ -534,23 +537,14 @@ class _AnimatedFadeOutFadeInState extends ImplicitlyAnimatedWidgetState<_Animate
         weight: widget.fadeInDuration.inMilliseconds.toDouble(),
       ),
     ]));
-    if (!widget.isTargetLoaded && _isValid(_placeholderOpacity!) && _isValid(_targetOpacity!)) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:537]: why remove this logic?

File: packages/flutter/lib/src/widgets/fade_in_image.dart [hunk 12]
```diff
@@ -463,6 +459,7 @@ class _AnimatedFadeOutFadeIn extends ImplicitlyAnimatedWidget {
     required this.fadeOutCurve,
     required this.fadeInDuration,
     required this.fadeInCurve,
+    required this.wasSynchronouslyLoaded,
   }) : assert(target != null),
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/fade_in_image.dart:463]: maybe add an assert if wasSynchronouslyLoaded is true, isTargetLoaded must also be true

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:463]: assert(! wasSynchronouslyLoaded || isTargetLoaded)

**Review by chunhtai — COMMENTED** [review]
mostly looks good, left some comment on part of the code that is not clear to me

File: packages/flutter/lib/src/widgets/fade_in_image.dart (hunk 11 above)
Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:537]: as the comment suggests, this code jumps back to the placeholder image for the "new" target image.

i.e., `old image --[user changes the image]--> jump to placeholder --[wait for new image]--> fade in new image.`

but according to image gapless playback, the placeholder will never be shown again, the old image will act as a placeholder and the new image replace the old one w/o "fade in fade out".

File: packages/flutter/lib/src/widgets/fade_in_image.dart (hunk 12 above)
Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/fade_in_image.dart:463]: done

**Review by chunhtai — APPROVED** [review]
LGTM
