### PR TITLE
Embedded images and added variations to ListTile sample code

### LINKED ISSUE #10673: ListTile diagram

### LINKED ISSUE #28685: ListTile needs sample code showing how to replace it with Row when it doesn't quite fit the use case
`ListTile`'s leading widget doesn't appear properly centered. This seems to be a regression as it rendered properly before.

image

```
[✓] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: ListView(
            children: <Widget>[
              ListTile(
                title: Text("I'm a ListTile"),
                subtitle: Text('Look at the leading icon'),
                leading: Icon(Icons.info),
                trailing: Icon(Icons.launch),
              ),
            ],
          ),
        ),
      ),
    );
```

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Added new sample code with more variations of `ListTile`, as well as embedded images generated from https://github.com/flutter/assets-for-api-docs/pull/66

## Related Issues

Fixes https://github.com/flutter/flutter/issues/10673
Fixes https://github.com/flutter/flutter/issues/28685
Addresses https://github.com/flutter/flutter/issues/29549, where there is confusion on how to use `ListTile`s and finding alternatives to the widget.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/list_tile.dart [hunk 1]
```diff
@@ -181,12 +181,59 @@ enum ListTileControlAffinity {
 ///
 /// {@tool sample}
 ///
-/// Here is a simple tile with an icon and some text.
+/// This example contains the different ways that [ListTile]s can be used.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: Maybe: This example uses a [ListView] to demonstrate different configurations of [ListTile]s in [Card]s.

This example looks great BTW.

File: packages/flutter/lib/src/material/list_tile.dart [hunk 2]
```diff
@@ -247,6 +294,130 @@ enum ListTileControlAffinity {
 /// ```
 /// {@end-tool}
 ///
+/// If a ListTile is not what you are looking for, custom list items can be created
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: This would be a good place for a subheading. Like
```
/// ## The ListTile layout isn't exactly what I want
```

Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: It the way ListTile pads and positions it's elements isn't quite what you're looking for, it's easy to create ....

File: packages/flutter/lib/src/material/list_tile.dart [hunk 3]
```diff
@@ -247,6 +295,137 @@ enum ListTileControlAffinity {
 /// ```
 /// {@end-tool}
 ///
+/// ## The ListTile layout isn't exactly what I want
+///
+/// If the way ListTile pads and positions it's elements isn't quite what
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/list_tile.dart]: it’s -> its

File: packages/flutter/lib/src/material/list_tile.dart [hunk 4]
```diff
@@ -247,6 +295,137 @@ enum ListTileControlAffinity {
...
+/// you're looking for, it's easy to create custom list items can be created
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/list_tile.dart]: The sentence after the comma seems to have too many verbs (either “it’s easy to create...” or “... can be created”)

**Comment by shihaohong** [comment]
I'll be working on adding a few more examples to alternatives section so that users have a greater variety to select from.

**Comment by shihaohong** [comment]
Added a second custom list item and made adjustments to the original custom list item. Assets created through https://github.com/flutter/assets-for-api-docs/pull/68. Currently waiting on that to be reviewed and merged.

**Comment by shihaohong** [comment]
Screenshots have been merged, currently ready for review

File: packages/flutter/lib/src/material/list_tile.dart [hunk 5]
```diff
@@ -247,6 +295,301 @@ enum ListTileControlAffinity {
...
+///
+///   @override
+///   Widget build(BuildContext context) {
+///     return Padding(
+///       padding: const EdgeInsets.symmetric(vertical: 5.0),
+///       child: Row(
+///         crossAxisAlignment: CrossAxisAlignment.start,
+///         children: <Widget>[
+///           Expanded(
+///             child: thumbnail,
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/list_tile.dart]: here and below: `child` or `children` is usually the last argument in a constructor per convention.

**Review by goderbauer — APPROVED** [review]
LGTM

The assets look nice.

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by x4080** [comment]
Hi, @shihaohong 

Do you know why that list view scrolling cannot be as performance as native android ? I wondered since flutter is compiled and using SKIA like native android

Thanks (and sorry if this is not the place to ask)

**Comment by shihaohong** [comment]
Hi @x4080, I don't know if I have the answers to your question since I've never compared the two. How are you benchmarking and making the comparison? 

I can provide suggestions as to how to improve ListView performance:
1) Make sure you're testing performance in release mode, since debug mode will be slower. More information on [Flutter build modes here](https://flutter.dev/docs/testing/build-modes)
2) Also, specifying an [itemExtent](https://docs.flutter.io/flutter/widgets/ListView/itemExtent.html) could improve performance as well

Also, in the future, try to see if you can find answers on StackOverflow (or ask the question). Otherwise, there are a few more [community options](https://flutter.dev/community)

**Comment by x4080** [comment]
Thanks for the suggestions, yes i already use release mode
