### PR TITLE
Fix(ios): Remove arm64 exclusion to support Xcode 26 simulators

### LINKED ISSUE #176188: flutter run not working  on iOS 26 simulator
### Steps to reproduce

flutter run on a iOS 26 simulator 

### Expected results

run failed 

### Actual results

run with `flutter run`
```code 
Uncategorized (Xcode): Unable to find a destination matching the provided destination specifier:
                { id:6B4F9D28-C76C-4146-9527-E844395B4434 }

        Available destinations for the "Runner" scheme:
                { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006020-000221002EE8C01E, name:My Mac }
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
```

run with  Xcode 
```
iPhone 17 cannot run Runner.
Domain: IDEFoundationErrorDomain
Code: 3
Recovery Suggestion: Runner's architectures (Intel 64-bit) include none that iPhone 17 can execute (arm64).
User Info: {
    DVTErrorCreationDateKey = "2025-09-29 04:42:00 +0000";
}
--
iPhone 17 cannot run Runner.
Domain: IDEFoundationErrorDomain
Code: 3
Recovery Suggestion: Runner's architectures (Intel 64-bit) include none that iPhone 17 can execute (arm64).
--


System Information

macOS Version 26.0 (Build 25A354)
Xcode 26.0.1 (24229) (Build 17A400)
Timestamp: 2025-09-29T12:42:00+08:00
```

### Code sample

similar to #175410 
but I have only one iOS 26 runtime 
```console 
xcrun simctl list|grep Runtimes -A 5
== Runtimes ==
iOS 26.0 (26.0 - 23A343) - com.apple.CoreSimulator.SimRuntime.iOS-26-0
== Devices ==
-- iOS 26.0 --
    iPhone 17 Pro (2BC6EFDC-D316-4EB9-B576-B5E46A46C82D) (Shutdown) 
    iPhone 17 Pro Max (EDD1A1BD-EA03-46CB-8785-16CB495B3DAD) (Shutdown) 
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

Image

### Logs

<details open><summary>Logs</summary>

```console


[        ] Xcode build done.                                            0.8s
[  +13 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get build-results --path
/var/folders/4w/mfv05mx55b53pw8yntx90phw0000gn/T/flutter_tools.TGH0kJ/flutter_ios_build_temp_dirxnXFdX/temporary_xcresult_bundle --format
json
[  +45 ms] {
             "actionTitle" : "RunnerTests.xctest",
             "analyzerWarningCount" : 0,
             "analyzerWarnings" : [

             ],
             "destination" : {
               "architecture" : "",
               "deviceId" : "",
               "deviceName" : "",
               "modelName" : "",
               "osVersion" : "",
               "platform" : ""
             },
             "endTime" : 1759121038.194,
             "errorCount" : 1,
             "errors" : [
               {
                 "issueType" : "Uncategorized",
                 "message" : "Unable to find a destination matching the provided destination specifier:\n\t\t{
                 id:6B4F9D28-C76C-4146-9527-E844395B4434 }\n\n\tAvailable destinations for the \"Runner\" scheme:\n\t\t{ platform:macOS,
                 arch:arm64, variant:Designed for [iPad,iPhone], id:00006020-000221002EE8C01E, name:My Mac }\n\t\t{ platform:iOS,
                 id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }\n\t\t{ platform:iOS Simulator,
                 id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }"
               }
             ],
             "startTime" : 1759121038.194,
             "status" : "succeeded",
             "warningCount" : 0,
             "warnings" : [

             ]
           }
[   +2 ms] Failed to build iOS app
[        ] Uncategorized (Xcode): Unable to find a destination matching the provided destination specifier:
                        { id:6B4F9D28-C76C-4146-9527-E844395B4434 }
           
                Available destinations for the "Runner" scheme:
                        { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006020-000221002EE8C01E, name:My Mac }
                        { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                        { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator
Device }
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 17.
[ +481 ms] "flutter run" took 9,215ms.
[   +5 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 26.0
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 25A354
[        ] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] arm64
[  +33 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:897:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1559:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:487:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:422:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:101:11)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:102:3)
           <asynchronous suspension>
           
           
[        ] Running 3 shutdown hooks
[   +4 ms] Shutdown hooks comple
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.37.0-0.1.pre, on macOS 26.0 25A354 darwin-arm64, locale zh-Hans-CN) [408ms]
    • Flutter version 3.37.0-0.1.pre on channel beta at /Users/wesleyanhe/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 465e421f53 (12 days ago), 2025-09-16 18:55:17 +0000
    • Engine revision 286e592194
    • Dart version 3.10.0 (build 3.10.0-162.1.beta)
    • DevTools version 2.50.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging

[!] Android toolchain - develop for Android devices (Android SDK version 36.1.0-rc1) [820ms]
    • Android SDK at /Users/wesleyanhe/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    ✗ cmdline-tools component is missing.
      Try installing or updating Android Studio.
      Alternatively, download the tools from https://developer.android.com/studio#command-line-tools-only and make sure to set the
      ANDROID_HOME environment variable.
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1) [970ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17A400
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [9.9s]
    • iPhone 17 (mobile) • 6B4F9D28-C76C-4146-9527-E844395B4434 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-26-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 26.0 25A354 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 140.0.7339.208
    ! Error: Browsing on the local area network for 吴鲁豫. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for hwy ipad. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for hwy. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [2.0s]
    • All expected network resources are available.

! Doctor found issues in 1 category.```

</details>

### PR DESCRIPTION
**Pull request by okorohelijah**
With the release of Xcode 26, Apple has removed Rosetta support for the iOS 26 simulator. This causes builds to fail on Apple Silicon Macs if any plugin excludes the `arm64` simulator architecture.

This change introduces an early check during the pod install step to detect and abort the build if it finds a plugin configured to exclude the arm64 simulator architecture (via EXCLUDED_ARCHS or VALID_ARCHS).

## Testing

- Verified that the build is unsuccessful when `arm64` is excluded.
- If a plugin excludes arm64, an error is raised showing the plugin that caused it 

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*
Fixes #176188 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/bin/podhelper.rb [hunk 1]
```diff
@@ -65,12 +65,34 @@ def flutter_additional_ios_build_settings(target)
   # Bundles are com.apple.product-type.bundle, frameworks are com.apple.product-type.framework.
   target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
 
+  # Detect pod-level EXCLUDED_ARCHS for the simulator written to Target Support Files xcconfig.
+  support_files_dir = File.join('Pods', 'Target Support Files', target.name)
+  if Dir.exist?(support_files_dir)
+    Dir.glob(File.join(support_files_dir, '*.xcconfig')).each do |xcfile|
+      File.foreach(xcfile) do |line|
+        if line =~ /^\s*EXCLUDED_ARCHS\b/ && line.include?('arm64')
```
Comment (vashworth) [inline packages/flutter_tools/bin/podhelper.rb]: So I think we should limit this to only Xcode 26. Looks like you should be able to get the Xcode version from the `XCODE_VERSION_MAJOR` build setting.

File: packages/flutter_tools/bin/podhelper.rb [hunk 2]
```diff
@@ -65,12 +65,34 @@ def flutter_additional_ios_build_settings(target)
...
+          abort "The pod `#{target.name}` config in #{xcfile} excludes the arm64 simulator architecture.\n" \
```
Comment (vashworth) [inline packages/flutter_tools/bin/podhelper.rb]: Use `raise` instead of `abort`

Comment (vashworth) [reply packages/flutter_tools/bin/podhelper.rb]: Also, you want the warning to be more actionable for the app developer. The app developer shouldn't be editing the podspec or xcconfig. They also aren't using pods directly. They think of things in terms in plugins. Maybe something like 

"The plugin xxx is excluding the arm64 architecture, which is a requirement for Xcode 26. Please file an issue with the plugin to support arm64."

File: packages/flutter_tools/bin/podhelper.rb [hunk 3]
```diff
@@ -65,12 +65,34 @@ def flutter_additional_ios_build_settings(target)
...
+    end
+  end
+
   target.build_configurations.each do |build_configuration|
     # Build both x86_64 and arm64 simulator archs for all dependencies. If a single plugin does not support arm64 simulators,
     # the app and all frameworks will fall back to x86_64. Unfortunately that case is not detectable in this script.
     # Therefore all pods must have a x86_64 slice available, or linking a x86_64 app will fail.
     build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'NO' if build_configuration.type == :debug
 
+    # Xcode 16 and later require all simulator code to be built for arm64 on Apple Silicon Macs.
```
Comment (vashworth) [inline packages/flutter_tools/bin/podhelper.rb]: Xcode 16 requires this too? I thought it was just Xcode 26 since Xcode 26 doesn't include the x86 simulator anymore?

File: packages/flutter_tools/bin/podhelper.rb [hunk 4]
```diff
@@ -65,12 +65,34 @@ def flutter_additional_ios_build_settings(target)
...
+    # Starting with Xcode 26, Rosetta for simulators is no longer available.
+    excluded_simulator_archs = build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]']
+    if excluded_simulator_archs&.include?('arm64')
+      raise "The `#{target.name}` pod failed to build for simulator.\n" \
+        "It is not compatible with iOS 18 and later simulators on Apple Silicon Macs because it excludes the `arm64` simulator architecture.\n" \
```
Comment (vashworth) [inline packages/flutter_tools/bin/podhelper.rb]: Again, are we sure this is true for iOS 18?

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart [hunk 5]
```diff
@@ -1110,196 +1111,119 @@ Information about project "Runner":
...
-          ProcessManager: () => fakeProcessManager,
-          XcodeProjectInterpreter: () => xcodeProjectInterpreter,
-        },
-      );
+        final ProcessResult result = await fakeProcessManager.run(<String>[
+          'ruby',
+          '-e',
+          rubyScript,
+          podhelperPath,
+        ], workingDirectory: fs.path.join('ios'));
```
Comment (vashworth) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart]: This should be made into an integration test instead of a unit test. This test doesn't really verify your fix. Since you're using a `fakeProcessManager`, it doesn't actually run the `ruby` command or anything, it just returns the `stderr` from the `FakeCommand`.

See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/swift_package_manager_test.dart as an example

File: packages/flutter_tools/bin/podhelper.rb (hunk 3 above)
Comment (okorohelijah) [reply packages/flutter_tools/bin/podhelper.rb]: From my understanding, the arch of the simulator is dependent on the processor of the mac. Xcode 16+ requires all simulators to be built for arm64 but Xcode 26 just stopped supporting rosetta

Comment (vashworth) [reply packages/flutter_tools/bin/podhelper.rb]: Per offline conversation:

Xcode 16 requires arm64 but supported x86 through rosetta. Xcode 26 no longer supports rosetta for simulators.

I think this comment is a little misleading, though, because it makes you think that you can't use `EXCLUDED_ARCHS` on Xcode 16 too. I would make the comment confined to Xcode 26. The historical context of Xcode 16 isn't super relevant. 

I'd just have the comment say something like "Xcode 26 no longer allows you to build x86-only architecture for the simulator."

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 6]
```diff
@@ -475,32 +475,6 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
-    }
-
-    final XcodeProjectInterpreter? xcodeProjectInterpreter = globals.xcodeProjectInterpreter;
-    if (xcodeProjectInterpreter == null) {
-      // Xcode isn't installed, don't try to check.
-      return false;
-    }
-    final String? buildSettings = await xcodeProjectInterpreter.pluginsBuildSettingsOutput(
-      podXcodeProject,
-    );
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart:495]: Instead of checking for EXCLUDED_ARCHS in the podhelper, how about checking for it here?

If you look at the output of `buildSettings`, it returns all build settings from all targets with an output like this:

```
Build settings for action build and target Flutter:
    ACTION = build
    AD_HOC_CODE_SIGNING_ALLOWED = YES
    ...
    EXCLUDED_ARCHS = i386
    ...
Build settings for action build and target my_plugin:
    ACTION = build
    AD_HOC_CODE_SIGNING_ALLOWED = YES
    ...
    EXCLUDED_ARCHS = i386
    ...
```

You may be able to split it by `Build settings for action build and target` to be able to determine which target/plugin uses EXCLUDED_ARCHS. This way you can also easily check the Xcode version with `globals.xcode.currentVersion`

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 7]
```diff
@@ -475,30 +476,63 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+
+    for (final section in targetSections) {
+      if (section.trim().isEmpty) {
+        continue;
+      }
+      final Match? targetMatch = targetRegex.firstMatch(section);
+      if (targetMatch != null) {
+        final String currentTarget = targetMatch.group(1)!.trim();
+        if (excludedArchRegex.hasMatch(section)) {
+          if (!currentTarget.startsWith('Pods-')) {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: So there could be other non-plugin targets. Perhaps could check the name against the list of plugins? You should be able to get the list of plugins with `findPlugins`.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 8]
```diff
@@ -475,30 +476,63 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+            offendingPlugins.add(currentTarget);
+          }
+        }
+      }
+    }
+
+    if (offendingPlugins.isNotEmpty) {
+      if (offendingPlugins.length == 1) {
+        final String name = offendingPlugins.single;
+        throwToolExit(
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: Instead of exiting, let's print a warning. The "universal" version of Xcode 26 still allows you to use x86: https://github.com/flutter/flutter/issues/176188#issuecomment-3402191058

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 9]
```diff
@@ -475,30 +476,63 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
-    return buildSettings != null && !buildSettings.contains(RegExp('EXCLUDED_ARCHS.*arm64'));
+    if (buildSettings == null || buildSettings.isEmpty) {
+      return;
+    }
+
+    final offendingPlugins = <String>[];
+    final targetRegex = RegExp(r'Build settings for action build and target ([^:]+):');
+    final excludedArchRegex = RegExp(r'EXCLUDED_ARCHS\s*=\s*.*\barm64\b');
+
+    final List<String> targetSections = buildSettings.split(RegExp(r'\n\s*\n'));
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: Can you not split on `targetRegex` and then trim it? May be able to eliminate one level of regex

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 10]
```diff
@@ -475,30 +476,63 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
-    // See if any plugins or their dependencies exclude arm64 simulators
-    // as a valid architecture, usually because a binary is missing that slice.
-    // Example: EXCLUDED_ARCHS = arm64 i386
-    // NOT: EXCLUDED_ARCHS = i386
-    return buildSettings != null && !buildSettings.contains(RegExp('EXCLUDED_ARCHS.*arm64'));
+    if (buildSettings == null || buildSettings.isEmpty) {
+      return;
+    }
+
+    final offendingPlugins = <String>[];
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]:
```suggestion
    final pluginsExcludingArmArch = <String>[];
```

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 8 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/xcode_project.dart]: I didnt add the universal because I thought since developers are being discouraged from using x86. "Universal" might soon be discontinued also

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 11]
```diff
@@ -475,30 +476,72 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      final RegExpMatch? excludedMatch = excludedLine.firstMatch(settingsLine);
+      if (excludedMatch != null && currentTarget != null) {
+        if (!iosPluginTargetNames.contains(currentTarget)) {
+          continue;
+        }
+        final String rhs = excludedMatch.group(1)!.replaceAll(';', '').trim();
+        final Set<String> tokens = rhs.split(RegExp(r'\s+')).toSet();
+        if (tokens.contains('arm64')) {
+          pluginsExcludingArmArch.add(currentTarget);
+        }
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: What's the benefit of formatting and splitting the group? Isn't it enough to just check if it contains `arm64`?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 12]
```diff
@@ -475,30 +476,72 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      final String settingsLine = eachLine.trimRight();
+
+      final RegExpMatch? headerMatch = targetHeader.firstMatch(settingsLine);
+      if (headerMatch != null) {
+        currentTarget = headerMatch.group(1)!.trim();
+        continue;
+      }
+
+      final RegExpMatch? excludedMatch = excludedLine.firstMatch(settingsLine);
+      if (excludedMatch != null && currentTarget != null) {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: Regex is an expensive operation, avoid using it if you don't need to yet
```suggestion
      if (currentTarget == null) {
        continue;
      }
      final RegExpMatch? excludedMatch = excludedLine.firstMatch(settingsLine);
      if (excludedMatch != null) {
```

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 13]
```diff
@@ -475,30 +476,72 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      }
+    }
+
+    if (pluginsExcludingArmArch.isNotEmpty) {
+      final String list = pluginsExcludingArmArch.map((String n) => '  - $n').join('\n');
+
+      globals.logger.printWarning(
+        'The following plugins are excluding the arm64 architecture, which is a requirement for Xcode 26+:\n'
+        '$list\n'
+        'Consider installing the "Universal" Xcode or file an issue with the plugins to support arm64.',
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]:
```suggestion
        'The following plugin(s) are excluding the arm64 architecture, which is a requirement for Xcode 26+:\n'
        '$list\n'
        'Consider installing the "Universal" Xcode or file an issue with the plugin(s) to support arm64.',
```

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 14]
```diff
@@ -475,30 +476,72 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
   /// True if the app project uses Swift.
   bool get isSwift => appDelegateSwift.existsSync();
 
-  /// Do all plugins support arm64 simulators to run natively on an ARM Mac?
-  Future<bool> pluginsSupportArmSimulator() async {
+  /// Xcode 26 no longer allows you to build x86-only architecture for the simulator
+  Future<void> checkForPluginsExcludingArmSimulator() async {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart:482]: Make the description/name more indicative of the purpose and functionality of the method

```suggestion
  /// Prints a warning if a plugin is excluding the `arm64` architecture.
  /// 
  /// Xcode 26 no longer allows you to build x86-only architecture for the simulator.
  Future<void> warnIfPluginsExcludingArmArch() async {
```

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart
Comment (vashworth) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:1]: I'd also include a test when a non-plugin target excludes arm64

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 11 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/xcode_project.dart]: that would be a false positive for strings like 'arm64e'

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 15]
```diff
@@ -475,30 +476,84 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      final int equalsIndex = leftTrimmed.indexOf('=');
+      if (equalsIndex < 0) {
+        continue;
+      }
+      final String rhs = leftTrimmed.substring(equalsIndex + 1).replaceAll(';', ' ').trim();
+
+      final Iterable<String> tokens = rhs.split(RegExp(r'\s+')).where((t) => t.isNotEmpty);
+      if (tokens.contains('arm64')) {
+        pluginsExcludingArmArch.add(currentTarget);
+      }
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/xcode_project.dart]: Is there a reason we need to parse the string? Can't we just check if it contains `arm64`?

The string should look something like this, right?
```
    EXCLUDED_ARCHS = i386 arm64
```

So wouldn't something as simple as this work?
```dart
final String leftTrimmed = settingsLine.trimLeft();
if (leftTrimmed.startsWith('EXCLUDED_ARCHS') && leftTrimmed.contains('arm64')) {
  pluginsExcludingArmArch.add(currentTarget);
}
```

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: @okorohelijah says "if we  use .contain it could lead to a false positive for any variant of arm64(arm64e or arm64_32)"

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: I still think this logic can be simplified. For example, why is it replacing a `;`? 

Perhaps you could split on space, something like this?

```dart
  final String trimmed = settingsLine.trim();
  final List<String> splitSetting = trimmed.split(' ');
  if (splitSetting[0] == 'EXCLUDED_ARCHS' && splitSetting.contains('arm64')) {
    pluginsExcludingArmArch.add(currentTarget);
  }
```

Comment (okorohelijah) [reply packages/flutter_tools/lib/src/xcode_project.dart]: `'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386 arm64e'` would be a false positive 

We can’t rely on a raw contains('arm64') because it can match substrings like arm64e. We need an exact token match and splitting on space would fail for bracketed keys. 

> why is it replacing a ;

nit: I replaced `;` because it is not uncommon to see trailing punctuations in config files and just to make sure since we are looking for an exact match. 

What do you think?

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: > 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386 arm64e' would be a false positive

In the example provided, it wouldn't return a false positive because it's getting split into an array and when you use `contains` on an array, it's looking for an exact match.

I suggest adding a unit test for this case to test it out and verify

Comment (okorohelijah) [reply packages/flutter_tools/lib/src/xcode_project.dart]: i apologize you're right - i was looking at the first example you gave `leftTrimmed.startsWith('EXCLUDED_ARCHS') && leftTrimmed.contains('arm64'))`

**Review by vashworth — APPROVED** [review]
LGTM!
