### PR TITLE
Fix dropdown menu overscroll

### LINKED ISSUE #8266: Not clear which is selected in large dropdown
See gif, this is in the Buttons > Dropdown demo.
dropdowns mov

### PR DESCRIPTION
**Pull request by YeungKC**
Dropdown menus should never overscroll or display an overscroll indicator.
However, in some cases there is an overscroll.

before:

before

after:

https://user-images.githubusercontent.com/11473691/104105562-008d0980-52ea-11eb-832e-7a27f88acd9c.mp4

Add test: Dropdown menu scrolls to last item in long lists

close #8266

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by shihaohong** [comment]
Based on abarth's original comment, it sounds like the real fix here is to have "30" be centered, then as you overscroll less (scroll down), prevent overscrolling from that point onwards. This allows the user to figure out what they had selected before they open the dropdown menu.

**Comment by YeungKC** [comment]
On this point, I found from the comments
 
 > Dropdown menus should never overscroll or display an overscroll indicator

https://github.com/flutter/flutter/commit/eebe09d40272e6566d79c8343c9a1d7b5b4b55d2#diff- 396168708bffa1bed56dc9770e1a6c15ff93b20eed77ee6c6d043f9a301407f0R79

Maybe only @HansMuller  can help us.

**Comment by Hixie** [comment]
Yeah, the behaviour we want is for the selected row to appear exactly overlaid with the widget (no scrolling, but with an overscrolled scrollbar). Scrolling should be "one-way" until it's no longer overscrolled. Failing that the current behaviour is closer to the intent than this PR's behaviour (at least as depicted in the video above).

**Comment by HansMuller** [comment]
This seems like a reasonable improvement to me. It's odd that the menu currently appears overscrolled, only to immediately snap back.  However, the menu's scrollbar should appear, but it's not showing up in the "after" video?

**Comment by YeungKC** [comment]
Should the scrollbar always appear?

Also the original behavior is that if index 1 is selected there is no overscroll.

I would find it very strange to scroll in one direction, so I'd like to confirm.

**Comment by HansMuller** [comment]
If the menu's items don't fit - so the menu is scrollable - then the scrollbar should appear.

**Comment by YeungKC** [comment]
I agree, I will update scrollbar.

**Comment by YeungKC** [comment]
Now if the menu is slidable, the scrollbar will always be displayed. ready review.

@shihaohong

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -518,8 +527,9 @@ class _DropdownRoute<T> extends PopupRoute<_DropdownRouteResult<T>> {
     // shown - subsequently we leave the scroll offset where the user left
     // it. This scroll offset is only accurate for fixed height menu items
     // (the default).
+    final double maxScrollOffset = preferredMenuHeight - menuHeight;
     final double scrollOffset = preferredMenuHeight <= maxMenuHeight ? 0 :
-      math.max(0.0, selectedItemOffset - (buttonTop - menuTop));
+      math.min(math.max(0.0, selectedItemOffset - (buttonTop - menuTop)), maxScrollOffset);
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dropdown.dart:532]: This line is pretty confusing at first glance. I couldn't understand it without looking at the surrounding code. Maybe we could break this line and the previous line down into an if/else statement, as well as add some code comments:
```dart
double scrollOffset = 0;
// If all of the menu items will not fit within availableHeight then
// compute the scroll offset that will line the selected menu item up
// with the select item. This is only done when the menu is first
// shown - subsequently we leave the scroll offset where the user left
// it. This scroll offset is only accurate for fixed height menu items
// (the default).
if (preferredMenuHeight > maxMenuHeight) {
  // The offset should be zero if the selected item is in view at the beginning
  // of the menu. Otherwise, the scroll offset should center the item if possible.
  scrollOffset = math.max(0.0, selectedItemOffset - (buttonTop - menuTop));
  // If the selected item's scroll offset is greater than the maximum scroll offset, 
  // set it instead to the maximum allowed scroll offset.
  scrollOffset = math.min(scrollOffset, preferredMenuHeight - menuHeight);
}
```

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -288,12 +288,21 @@ class _DropdownMenuState<T> extends State<_DropdownMenu<T>> {
             textStyle: route.style,
             child: ScrollConfiguration(
               behavior: const _DropdownScrollBehavior(),
-              child: Scrollbar(
-                child: ListView(
-                  controller: widget.route.scrollController,
-                  padding: kMaterialListPadding,
-                  shrinkWrap: true,
-                  children: children,
+              child: PrimaryScrollController(
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dropdown.dart:291]: Is there a reason for the PrimaryScrollController instead of just passing the scroll controller into the Scrollbar? Nothing wrong with it, just curious about the choice here.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 3]
```diff
@@ -288,12 +288,21 @@ class _DropdownMenuState<T> extends State<_DropdownMenu<T>> {
...
+                    final bool isScrollable =  kMaterialListPadding.vertical + menuTotalHeight > constraints.maxHeight;
+                    return Scrollbar(
+                      isAlwaysShown: isScrollable,
+                      child: ListView(
+                        padding: kMaterialListPadding,
+                        shrinkWrap: true,
+                        children: children,
+                      ),
+                    );
+                  }
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dropdown.dart:305]: nit: trailing comma
```suggestion
                  },
```

File: packages/flutter/test/material/dropdown_test.dart [hunk 4]
```diff
@@ -991,6 +991,35 @@ void main() {
...
+
+    final ScrollController scrollController = PrimaryScrollController.of(tester.element(find.byType(ListView)))!;
+    // Make sure there is no overscroll
+    expect(scrollController.offset, scrollController.position.maxScrollExtent);
+
+    // Find the selected item in the scrollable dropdown list
+    final Finder menuItemFinder = find.byType(Scrollable);
+    final RenderBox menuItemContainer = tester.renderObject<RenderBox>(menuItemFinder);
+    final RenderBox selectedItem = tester.renderObject<RenderBox>(
+        find.descendant(of: menuItemFinder, matching: find.byKey(const ValueKey<String>('99'))));
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:1013]: clean up this line a little:
```suggestion
    final RenderBox selectedItem = tester.renderObject<RenderBox>(
      find.descendant(
        of: menuItemFinder,
        matching: find.byKey(const ValueKey<String>('99')),
      ),
    );
```

File: packages/flutter/test/material/dropdown_test.dart [hunk 5]
```diff
@@ -991,6 +991,35 @@ void main() {
...
+
+    // kMaterialListPadding.vertical is 8.
+    const Offset selectedItemOffset = Offset(0.0, -8.0);
+    expect(
+      selectedItem.size.bottomCenter(selectedItem.localToGlobal(Offset.zero)).dy,
+      equals(menuItemContainer.size.bottomCenter(menuItemContainer.localToGlobal(selectedItemOffset)).dy),
+    );
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:1020]: Comments and breaking down the lines a little more:
```suggestion
    // kMaterialListPadding.vertical is 8.
    const Offset menuPaddingOffset = Offset(0.0, -8.0);
    final Offset selectedItemOffset = selectedItem.localToGlobal(Offset.zero);
    final Offset menuItemContainerOffset = menuItemContainer.localToGlobal(menuPaddingOffset);
    // Selected item should be aligned to the bottom of the dropdown menu.
    expect(
      selectedItem.size.bottomCenter(selectedItemOffset).dy,
      equals(menuItemContainer.size.bottomCenter(menuItemContainerOffset).dy,
    );
```

File: packages/flutter/test/material/dropdown_test.dart [hunk 6]
```diff
@@ -2887,4 +2912,18 @@ void main() {
     expect(find.text('first').hitTestable(), findsNothing);
     expect(find.text('second').hitTestable(), findsNothing);
   });
+
+  testWidgets('Dropdown menu is scrollable, then should show scroll bar', (WidgetTester tester) async {
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:2916]:
```suggestion
  testWidgets('Dropdown menu should persistently show scrollbar if it is scrollable', (WidgetTester tester) async {
```

**Review by shihaohong — COMMENTED** [review]
The changes look good! Just some suggestions for making the code more readable.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/dropdown.dart:291]: Because both Scrollbar and ListView need to set controllers, it looks more intuitive to use PrimaryScrollController.

Comment (shihaohong) [reply packages/flutter/lib/src/material/dropdown.dart:291]: Makes sense, thanks!

File: packages/flutter/test/material/dropdown_test.dart [hunk 7]
```diff
@@ -991,6 +991,42 @@ void main() {
...
+
+    // kMaterialListPadding.vertical is 8.
+    const Offset menuPaddingOffset = Offset(0.0, -8.0);
+    final Offset selectedItemOffset = selectedItem.localToGlobal(Offset.zero);
+    final Offset menuItemContainerOffset = menuItemContainer.localToGlobal(menuPaddingOffset);
+    // Selected item should be aligned to the bottom of the dropdown menu.
+    expect(
+      selectedItem.size.bottomCenter(selectedItemOffset).dy,
+      equals(menuItemContainer.size.bottomCenter(menuItemContainerOffset).dy,
+    );
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:1027]: Actually, I just realized that the `equals` shouldn't be necessary
```suggestion
    expect(
      selectedItem.size.bottomCenter(selectedItemOffset).dy,
      menuItemContainer.size.bottomCenter(menuItemContainerOffset).dy,
    );
```

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (YeungKC) [reply packages/flutter/lib/src/material/dropdown.dart]: thx, done.

**Review by shihaohong — APPROVED** [review]
LGTM
