### PR TITLE
Provide flutter sdk kernel files to dwds launcher instead of dart ones

### LINKED ISSUE #101639: DartUri: Unresolved uri: dart:web_sql,  DartUri: Unresolved uri: dart:ui when running new app in Chrome on macOS
I just upgraded Flutter and I'm now getting these two messages when I launch a newly created skeleton app in Chrome on macOS.

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
This app is linked to the debug service: ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
Debug service listening on ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
```

It doesn't seem to affect anything yet, I just don't understand at what point it might cause problems, and if I need to do anything to resolve it.

I notice that this message appears unremarked in a few logs in other bug reports, eg [github search](https://github.com/flutter/flutter/issues?q=is%3Aissue+%22DartUri%3A+Unresolved+uri%3A+dart%3Aweb_sql%22+)

## Steps to Reproduce

1. Execute `flutter create testapp` to create a skeleton app.
2. Execute `flutter run` on the app

**Expected results:**
```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
Debug service listening on ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
```

**Actual results:** 
```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
This app is linked to the debug service: ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
Debug service listening on ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:52145[/P_jcIvp2bYw]()=[/ws]()
```

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```

> flutter analyze
Analyzing testapp...                                                    
No issues found! (ran in 2.0s)

```

```
> flutter doctor -v
[✓] Flutter (Channel beta, 2.12.0-4.2.pre, on macOS 12.3.1 21E258 darwin-arm,
    locale en-GB)
    • Flutter version 2.12.0-4.2.pre at /Users/michael/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c931b769b (11 days ago), 2022-03-29 10:49:29 -0500
    • Engine revision 486f4a749e
    • Dart version 2.17.0 (build 2.17.0-182.2.beta)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by annagrin**
Provide flutter SDK kernel files to dwds launcher instead of dart ones.

Flutter SDK adds libraries to the dart SDK kernel files. Passing flutter SDK will make those additional libraries available for expression compilation.

Closes: https://github.com/flutter/flutter/issues/101639

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart [hunk 1]
```diff
@@ -0,0 +1,46 @@
+// Copyright 2022 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+// @dart = 2.8
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:5]: Is there any blocker to making this null-safe?

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+class SdkWebConfigurationProvider extends SdkConfigurationProvider {
+  SdkWebConfigurationProvider();
+  SdkConfiguration _configuration;
+
+  /// Create and validate configuration matching the default SDK layout.
+  /// Create configuration matching the default SDK layout.
+  @override
+  Future<SdkConfiguration> get configuration async {
+    if (_configuration == null) {
+      final String sdkDir = globals.artifacts.getHostArtifact(HostArtifact.flutterWebSdk).path;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:25]: Could you pass in `artifacts` via the constructor, rather than grab it from globals? We are trying to reduce the overall use of globals in the tool codebase.

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart (hunk 1 above)
Comment (annagrin) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:5]: Yes, the imports from dwds.

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart (hunk 2 above)
Comment (annagrin) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:25]: I am not very familiar with flutter tools code, could you please point me to some code where I can get the artifacts in a approved way?

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:5]: Ahh, TIL. cool

File: packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:25]: Here's an example: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze_base.dart#L50

We'll still be using the same `globals.artifacts` instance that we provide when constructing this object in the tool, but by direct injecting it in the constructor it reduces the chance of a global instance leaking into our unit tests.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:25]: For example, I don't think you would need the `context.run()` in `packages/flutter_tools/test/web.shard/sdk_web_configuration_test.dart` if the test artifacts are passed in via the constructor

Comment (annagrin) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart:25]: got it, thanks!

Comment (annagrin) [reply packages/flutter_tools/lib/src/isolated/sdk_web_configuration.dart]: done!

File: packages/flutter_tools/test/web.shard/sdk_web_configuration_test.dart [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import 'package:flutter_tools/src/artifacts.dart';
+import 'package:flutter_tools/src/isolated/sdk_web_configuration.dart';
+
+import '../src/common.dart';
+
+void main() {
+  FileSystem fileSystem;
+
+  group('Flutter SDK configuration for web', () {
+    final SdkConfigurationProvider provider = SdkWebConfigurationProvider(Artifacts.test(fileSystem: fileSystem));
```
Comment (christopherfujino) [inline packages/flutter_tools/test/web.shard/sdk_web_configuration_test.dart:19]: nit: I think you should move this to the `setUp()` step, as you are passing `fileSystem` once, and before it's initialized, and it is used in multiple tests.

**Review by christopherfujino — APPROVED** [review]
LGTM with 1 nit about initializing provider in the test `setUp()`

File: packages/flutter_tools/test/web.shard/sdk_web_configuration_test.dart (hunk 3 above)
Comment (annagrin) [reply packages/flutter_tools/test/web.shard/sdk_web_configuration_test.dart]: done, thanks!

**Review by christopherfujino — APPROVED** [review]
Thanks so much for submitting this!
