### PR TITLE
Fix: Update CupertinoSheetRoute transition rounded corner

### LINKED ISSUE #163334: showCupertinoSheet keep rounded corners after closing
### Steps to reproduce

Show a `showCupertinoSheet` on iPhone SE (real or simulated) or any Android phone.

### Expected results

The app should be in the state where it was before the call.

### Actual results

This is the page before calling `showCupertinoSheet`:

Image

This is the sheet being displayed (ok):

Image

This is the page after I drag the sheet down (closing it). ** *Notice how the borders are rounded* ** (where it should be the same as the first screenshot). This happens on both Android and iOS.

Image

This image is from the iPhone SE simulator (iPhone SE have a square corner screen, same as some Androids, so, this bug possibly is not properly visualized in "normal" iPhones, iPads or Androids with rounded corners.

### Code sample

```
Future<T?> showModalSheet<T>({required WidgetBuilder builder}) async {
  if (defaultTargetPlatform == TargetPlatform.iOS) {
    return await showCupertinoSheet<T>(
      context: this,
      pageBuilder: (context) => Material(child: Builder(builder: builder)),
    );
  }

  return showModalBottomSheet<T>(
    context: this,
    useSafeArea: true,
    showDragHandle: true,
    builder: builder,
  );
}
```

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.1 24B83 darwin-x64, locale en-BR) [799ms]
    • Flutter version 3.29.0 on channel stable at /Users/jckodel/fvm/versions/3.29.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (4 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.7s]
    • Android SDK at /Users/jckodel/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,229ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [17ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1) [17ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.97.2) [16ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (4 available) [6.3s]
    • Júlio’s iPhone (mobile)             • 00008030-00092DD92168C02E            • ios            • iOS 18.1.1 22B91
    • iPhone SE (3rd generation) (mobile) • 45842E71-D9F0-4938-BDCD-65FD975B282B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 15.1 24B83 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 132.0.6834.160
    ! Error: Browsing on the local area network for iPad de -STUPID APPLE-. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [328ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Update CupertinoSheetRoute transition rounded corner
fixes: #163334 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 1]
```diff
@@ -221,10 +221,9 @@ class CupertinoSheetTransition extends StatefulWidget {
       reverseCurve: reverseCurve,
       parent: secondaryAnimation,
     );
-    final double deviceCornerRadius = MediaQuery.maybeViewPaddingOf(context)?.top ?? 0;
 
     final Animatable<BorderRadiusGeometry> decorationTween = Tween<BorderRadiusGeometry>(
-      begin: BorderRadius.circular(deviceCornerRadius),
+      begin: BorderRadius.circular(0),
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:226]: Ah, I was [looking into this issue too](https://github.com/flutter/flutter/issues/163334#issuecomment-2672298525).

This would fix phones with no rounded corners, but it would look not as smooth on phones with rounded corners. The "brute force" method I was thinking of was for the radius above, hard coding it to zero if the animation is at the beginning. This would likely be jumpy on screens without rounded corners, however, so it's not perfect either.

**Review by MitchellGoodwin — COMMENTED** [review]
Thank you for putting this PR together. I'm looking into this as well. Could you include videos of how these changes look when animating on a phone with this issue, and an iPhone with rounded corners?

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:226]: Yaa, correct. When i saw animation on iPhone SE, in the beginning it jump for flat to 20 and then comes down to 12. And going back was smooth but it retained that curve.

**Comment by rkishan516** [comment]
> Thank you for putting this PR together. I'm looking into this as well. Could you include videos of how these changes look when animating on a phone with this issue, and an iPhone with rounded corners?

Sure, I will capture a video and put in some time.

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 2]
```diff
@@ -221,10 +221,9 @@ class CupertinoSheetTransition extends StatefulWidget {
       reverseCurve: reverseCurve,
       parent: secondaryAnimation,
     );
-    final double deviceCornerRadius = MediaQuery.maybeViewPaddingOf(context)?.top ?? 0;
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:224]: Lets keep this since it lets us smoothly animate from rounded device corners. This is an approximation though, and from testing I think this is not quite right. Lowering it seems to smooth out the end of the transition. So I think this is better:
``` dart
final double deviceCornerRadius = (MediaQuery.maybeViewPaddingOf(context)?.top ?? 0) * .9;
```

Paired with that, we do not want the same transition if the device corner radius is too small. In these cases we want the transition to start from zero.

So I added:
``` dart
final bool roundedDeviceCorners = deviceCornerRadius > 20;
```

Combined with the `0.9` smoothing, this seems like a good cutoff. Roughly, it equals about double the targeted radius of `12`.

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 1 above)
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:226]:
``` dart
begin: BorderRadius.vertical(
  top: Radius.circular(roundedDeviceCorners ? deviceCornerRadius : 0)
),
```
So we can animate from zero for flat screens and use the smoother transition for rounded corners. We also should only apply the radius to the top of the view. The bottom is unnecessary.

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 3]
```diff
@@ -221,10 +221,9 @@ class CupertinoSheetTransition extends StatefulWidget {
...
 
     final Animatable<BorderRadiusGeometry> decorationTween = Tween<BorderRadiusGeometry>(
-      begin: BorderRadius.circular(deviceCornerRadius),
+      begin: BorderRadius.circular(0),
       end: BorderRadius.circular(12),
     );
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:229]: Below this, I think it's a good idea to change the radius transition to this:
``` dart
        AnimatedBuilder(
          animation: radiusAnimation,
          child: child,
          builder: (BuildContext context, Widget? child) {
            return ClipRRect(
              borderRadius:
                  !secondaryAnimation.isDismissed
                      ? radiusAnimation.value
                      : BorderRadius.circular(0),
              child: contrastedChild,
            );
          },
        ),
```
Switching back to zero here ensures the rounded corner does not stick around once the animation is finished. Without the `0.9` smoothing I was finding this caused the transition to jump on some screens. But that was a sign it wasn't finishing correctly.

**Review by MitchellGoodwin — COMMENTED** [review]
I've been trying different things, and I have a proposed solution. I've left some comments below with my reasoning. Let me know what you think.

**Comment by rkishan516** [comment]
> I've been trying different things, and I have a proposed solution. I've left some comments below with my reasoning. Let me know what you think.

Hmm, Interesting approach. I think once the top route will be popping, there might be jump in animation because of 

```dart
  borderRadius:
                  !secondaryAnimation.isDismissed
                      ? radiusAnimation.value
                      : BorderRadius.circular(0),
```
if that doesn't happen or if that is small enough that  it isn't noticeable then we are good. I will check some devices with this behaviour.

**Comment by MitchellGoodwin** [comment]
> if that doesn't happen or if that is small enough that it isn't noticeable then we are good. I will check some devices with this behaviour.
> 
> Edit :- Checked on few flat devices like Pixel 2 and iPhone SE, there is a jump at the end, but its very subtle.

To me, I think the jump is small enough to be acceptable for fixing the issue. If you're happy with this, I can approve this PR and get a second review.

**Comment by rkishan516** [comment]
> To me, I think the jump is small enough to be acceptable for fixing the issue. If you're happy with this, I can approve this PR and get a second review.

Sure, Until device corner radius is not available in media query, We can go with this.

**Comment by MaherSafadii** [comment]
thanks for the fix but the title seems misleading as it doesn't have anything to do with the CupertinoActionSheet but the CupertinoSheetRoute instead.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for fixing this.

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 4]
```diff
@@ -221,10 +221,14 @@ class CupertinoSheetTransition extends StatefulWidget {
       reverseCurve: reverseCurve,
       parent: secondaryAnimation,
     );
-    final double deviceCornerRadius = MediaQuery.maybeViewPaddingOf(context)?.top ?? 0;
+
+    final double deviceCornerRadius = (MediaQuery.maybeViewPaddingOf(context)?.top ?? 0) * .9;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/sheet.dart:225]: for these numbers, can you declare a const variable with descriptive name and use it here?

**Review by chunhtai — APPROVED** [review]
LGTM, but left some readability comments

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 4 above)
Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:225]: Sure
