### PR TITLE
Fix time picker period selector a11y touch targets

### LINKED ISSUE #168245: touch target size not up to a11y standards for DatePicker day period selector.
### Steps to reproduce

The "AM" and "PM" buttons in the TimePicker dialog have a hard coded height of 39 pt (see image below), which is smaller than the recommended touch target size (see [Android a11y guidelines](https://support.google.com/accessibility/android/answer/7101858?hl=en), for example)

Image

---

[This DartPad project](https://dartpad.dev/?id=bd8509ad498a4d44871c78e4c038e418) displays the TimePicker with the "AM" and "PM" buttons. Inspecting the buttons reveals their size. I believe [this](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/time_picker.dart#L3546) is the offending code, hardcoding a height of 80 pixels total for both buttons. 

### Expected results

The "AM" and "PM" buttons should each have a touch target size of at least 48x48 pixels. 

### Actual results

The "AM" and "PM" buttons each have a touch target height of 39 pixels only.

### Code sample

[<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
](https://dartpad.dev/?id=bd8509ad498a4d44871c78e4c038e418)

### Screenshots or Video

_No response_

### Flutter Doctor output

N/A

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes the TimePicker day period selector touch targets.

### Before

| Flutter | Google Agenda | Compose |
|--------|--------|--------|
| Image | Image | Image Image | 

### After

| Flutter | Google Agenda | Compose |
|--------|--------|--------|
|image | Image | Image Image | 

## Implementation choice

This PR implements two main changes:
- it expands the `_DayPeriodControl` bounds by reducing some existing spacing. Doing so the touch area of the AM/PM buttons can grow outside the day period container and respect the minimum interactive height.
- it changes the tree order to correctly sized the AM/PM buttons semantics. The solution here is somewhat tricky/hacky:
 
Because the semantics bounds are clipped by their ancestor, the PR changes the widget order:

Before, the order was `_DayPeriodControl` > `_DayPeriodInputPadding` > `Material` (with shape and clip) > `Row` (or Column depending on the orientation) > children [ `Semantics` > AM `InkWell`, `Semantics` > PM `InkWell` ]
(Which leads to the Semantics being clipped by the Material shape).

After, the order is `_DayPeriodControl` > `_DayPeriodInputPadding` > `Row` (or Column depending on the orientation) > children [ `Semantics` > `Material` (with shape and clip) > AM `InkWell`, `Semantics` > `Material` (with shape and clip) > PM `InkWell` ]

The difficulty here is that the `TimePickerThemeData.dayPeriodShape` is meant to be the shape for the whole day period container. In order to change the order, this PR has to set separetly the shapes of the AM and PM buttons. To do so it adds some logic to 'split' the shape in two parts. This is ok for the default shape but not possible for any shape, in that case the original shape will be use for both buttons which gives a different result than before this PR. This annoyance seems less a problem than having the default rendering not respecting a11y touch targets.

## Related Issue

Fixes [touch target size not up to a11y standards for DatePicker day period selector.](https://github.com/flutter/flutter/issues/168245)

## Tests

Adds 2 tests.
Updates 5 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/time_picker.dart [hunk 1]
```diff
@@ -248,22 +249,31 @@ class _TimePickerHeader extends StatelessWidget {
...
+    final RenderObjectWidget orientationSpecificHeader = switch (orientation) {
       Orientation.portrait => Column(
         crossAxisAlignment: CrossAxisAlignment.start,
         children: <Widget>[
           Padding(
             padding: EdgeInsetsDirectional.only(
-              bottom: _TimePickerModel.useMaterial3Of(context) ? 20 : 24,
+              bottom:
+                  (_TimePickerModel.useMaterial3Of(context) ? 20 : 24) -
+                  minInteractiveVerticalPadding / 2,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:270]: IIUC, the additional space we save here will be shared by both bottom, why do we divide it by 2?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 2]
```diff
@@ -306,7 +314,7 @@ class _TimePickerHeader extends StatelessWidget {
                       : VerticalDirection.down,
               mainAxisAlignment: MainAxisAlignment.center,
               crossAxisAlignment: CrossAxisAlignment.start,
-              spacing: 12,
+              spacing: math.max(0, 16 - minInteractiveVerticalPadding / 2),
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:313]: same

File: packages/flutter/lib/src/material/time_picker.dart [hunk 3]
```diff
@@ -650,50 +646,126 @@ class _DayPeriodControl extends StatelessWidget {
...
-              clipBehavior: Clip.antiAlias,
-              color: Colors.transparent,
-              shape: resolvedShape,
-              child: Column(
-                children: <Widget>[
-                  Expanded(child: amButton),
+            child: Column(
+              children: <Widget>[
+                Expanded(child: amButton),
+                if (showSeparator)
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]: why we conditionally show separator now?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 4]
```diff
@@ -650,50 +646,126 @@ class _DayPeriodControl extends StatelessWidget {
     }
 
     final Widget result;
+    bool showSeparator = true;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]:
```suggestion
    final bool hasRoundedBorder = resolvedShape is RoundedRectangleBorder && resolvedShape.borderRadius is BorderRadius
    bool showSeparator = !hasRoundedBorder;
```

File: packages/flutter/lib/src/material/time_picker.dart [hunk 5]
```diff
@@ -650,50 +646,126 @@ class _DayPeriodControl extends StatelessWidget {
...
+    // (Similarly to Google Agenda).
+    // To achieve this, instead of using a parent Material which clips
+    // the Semantics, each button should manage its own shape.
+    // The logic below "cuts" the given period selector shape in two parts,
+    // one for the AM button, the other for the PM button. Each sub-shape
+    // is obtained by removing some rounded corners from the original shape.
     switch (orientation) {
       case Orientation.portrait:
+        if (resolvedShape is RoundedRectangleBorder && resolvedShape.borderRadius is BorderRadius) {
+          showSeparator = false;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]:
```suggestion
        if (hasRoundedBorder) {
```

File: packages/flutter/lib/src/material/time_picker.dart [hunk 6]
```diff
@@ -650,50 +646,126 @@ class _DayPeriodControl extends StatelessWidget {
...
-                ],
-              ),
+                Expanded(child: pmButton),
+              ],
             ),
           ),
         );
       case Orientation.landscape:
+        if (resolvedShape is RoundedRectangleBorder && resolvedShape.borderRadius is BorderRadius) {
+          showSeparator = false;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]:
```suggestion
        if (hasRoundedBorder) {
```

File: packages/flutter/lib/src/material/time_picker.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/time_picker.dart]: Though I don't quite get why we only show separator when this condition is met

File: packages/flutter/lib/src/material/time_picker.dart [hunk 7]
```diff
@@ -728,21 +808,104 @@ class _AmPmButton extends StatelessWidget {
...
-        onTap: onPressed,
-        child: Semantics(
-          checked: selected,
-          inMutuallyExclusiveGroup: true,
-          button: true,
+    return _AmPmSemantics(
+      minSemanticHeight: kMinInteractiveDimension,
+      checked: selected,
+      alignment: semanticAlignment,
+      child: Material(
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]: Can you explain a bit why this is needed to expand the size of the button? Why would cliping at the parent row/ column prevent the child from expanding the size? Assuming children return big enough space for itself, parent material should not clip the space right?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 8]
```diff
@@ -248,22 +249,31 @@ class _TimePickerHeader extends StatelessWidget {
       context,
     ).timeOfDayFormat(alwaysUse24HourFormat: _TimePickerModel.use24HourFormatOf(context));
 
+    final _TimePickerDefaults defaultTheme = _TimePickerModel.defaultThemeOf(context);
+    final Orientation orientation = _TimePickerModel.orientationOf(context);
+    final double dayPeriodHeight =
+        orientation == Orientation.portrait
+            ? defaultTheme.dayPeriodPortraitSize.height
+            : defaultTheme.dayPeriodLandscapeSize.height;
+    final double minInteractiveVerticalPadding =
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]: are we sure only veritical space will be a problem?

File: packages/flutter/lib/src/material/time_picker.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart:270]: Because this space is the one between the header and the period selector. Half of the whole vertical padding applies to it.

image

File: packages/flutter/lib/src/material/time_picker.dart (hunk 3 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart]: Because with this fix two shapes are drawn. The bottom border of the AM button and the top border of the PM button replace the divider.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 4 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart]: > Though I don't quite get why we only show separator when this condition is met

The goal was to fallback to the previous rendering when it was not possible to cut the shape.
It's true that it might be better to always remove the separator and assume that the bottom of tha AM shape and the top of the PM shape will look as a Divider.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 8 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart]: With the default day period size (from M3 and M2), the horizontal space is greater than minInteractiveDimension so I focused only on the vertical space.
I'm not sure it would make sense for someone to change this default to something less than minInteractiveDimension and assuming the framework will keep making this accessible.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 7 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart]: Let me try to explain this current solution and why it is not as simple as I would like it to be. I'm very interested in this discussion. It would great to find out a better solution (mainly I would prefer to remove the logic which 'cuts' the shape).

> why this is needed to expand the size of the button? Why would cliping at the parent row/ column prevent the child from expanding the size? Assuming children return big enough space for itself, parent material should not clip the space right?

This `_AmPmSemantics` widget is not used to expand the size of the button, it is used to expand the semantics bounds.
The spec design requires that the visual size for each button is 40 in dial mode and 36 in input mode only.

For instance, see https://m3.material.io/components/time-pickers/specs#1cb56d62-0b4a-4db0-8620-215f2d0cfa69

image

To respect this visual size, the size of the buttons is restricted (line 758 below):

https://github.com/flutter/flutter/blob/7c5332fcadbb6eb91a724dfaf11d03ff3d1fe3e8/packages/flutter/lib/src/material/time_picker.dart#L757-L770

While writing this, I realize that now that this PR contains logic to cut the shape I can probably remove the _AmPmSemantics widget, remove the SizedBox line 757, and add some logic to add padding inside _AmPmButton. That way a usual Semantics widget could be use.
Let me verify this and push a commit. This will get us some reference to discuss further.

Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart]: I updated the PR to replace the _AmPmSemantics widget with a normal Semantics and adding some padding to get the inner Material properly sized.

I wonder if it would be possible to use a Stack to get rid of the logic which cuts the shape: one layer would contain the day period container and the InkWells, the second layer the Semantics, I don't know if it is possible. I will experiment and let you know.

**Comment by bleroux** [comment]
Convert to draft, as I will file 2 alternatives PRs for discussion.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 9]
```diff
@@ -728,15 +795,22 @@ class _AmPmButton extends StatelessWidget {
...
-          checked: selected,
-          inMutuallyExclusiveGroup: true,
-          button: true,
-          child: Center(child: Text(label, style: resolvedTextStyle, textScaler: buttonTextScaler)),
+    return Semantics(
+      checked: selected,
+      inMutuallyExclusiveGroup: true,
+      button: true,
+      child: Padding(
+        padding: padding,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:813]: Should we add a tap handler for the padded area?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 10]
```diff
@@ -650,51 +646,114 @@ class _DayPeriodControl extends StatelessWidget {
...
+
+        final Widget pmButton = _AmPmButton(
+          selected: pmSelected,
+          onPressed: () => _setPm(context),
+          label: materialLocalizations.postMeridiemAbbreviation,
+          padding: EdgeInsets.only(bottom: (minInteractiveSize.height - dayPeriodSize.height) / 2),
+          shape: pmShape,
+        );
+
         result = _DayPeriodInputPadding(
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]: Cans just return here directly

File: packages/flutter/lib/src/material/time_picker.dart [hunk 11]
```diff
@@ -650,51 +646,114 @@ class _DayPeriodControl extends StatelessWidget {
...
+          selected: pmSelected,
+          onPressed: () => _setPm(context),
+          label: materialLocalizations.postMeridiemAbbreviation,
+          padding: EdgeInsets.symmetric(
+            vertical: (minInteractiveSize.height - dayPeriodSize.height) / 2,
+          ),
+          shape: pmShape,
+        );
+
         result = _DayPeriodInputPadding(
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart]: same

**Review by chunhtai — COMMENTED** [review]
I think this PR overall LGTM, just some minor comment

File: packages/flutter/lib/src/material/time_picker.dart (hunk 9 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/time_picker.dart:813]: Managing tap events into the padded areas is already done by `_DayPeriodInputPadding`

**Comment by bleroux** [comment]
Resurrecting this PR, see https://github.com/flutter/flutter/pull/171437#discussion_r2274241670.
They were several changes in time picker files in the past two months. I resolved all the conflicts.

I still need some time to verify if more changes are needed.
Once done, I will mark this PR as 'Ready for review'.

**Comment by bleroux** [comment]
@chunhtai The PR is ready for review.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
Looks like there is a slight padding that shifted the entire clock widget by several pixel, which looks fines to me. cc @QuncCccccc Do you think that is ok?

**Comment by bleroux** [comment]
Thanks for the review 🙏 

> Looks like there is a slight padding that shifted the entire clock widget by several pixel, which looks fines to me.

I will have a look tomorrow at this slight unwanted padding, I think I fixed a very similar golden failure on https://github.com/flutter/flutter/pull/171437.

**Comment by QuncCccccc** [comment]
The golden diffs look very small, so I just triaged them. Waiting to check google testing result.
