### PR TITLE
[ Tool ] Don't try to reattach when attach target disappears

### LINKED ISSUE #156692: When connecting to device, `StateError: Bad sate: Stream has already been listened to`
Since 3.24.0

On 3.24.3, affects 1% of all clients that have reported a crash (current overall crash rate is ~1%)

Occurs on `flutter attach`

```
StateError: Bad state: Stream has already been listened to.
at _StreamController._subscribe(stream_controller.dart:686)
at _ControllerStream._createSubscription(stream_controller.dart:837)
at _StreamImpl.listen(stream_impl.dart:497)
at new _ForwardingStreamSubscription(stream_pipe.dart:114)
at _ForwardingStream._createSubscription(stream_pipe.dart:86)
at _ForwardingStream.listen(stream_pipe.dart:81)
at FlutterDevice.connect(resident_runner.dart:267)
at ResidentRunner.connectToServiceProtocol(resident_runner.dart:1404)
at HotRunner.attach(run_hot.dart:236)
at AttachCommand._attachToDevice(attach.dart:403)
at <asynchronous gap>(async)
at AttachCommand.runCommand(attach.dart:265)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1408)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:420)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:364)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:130)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at main(executable.dart:93)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by bkonyi**
Before this change, there was logic in `flutter attach` that would try and listen for a new application to attach to in the scenario the current target application disappeared. This behavior isn't documented, and has resulted in a `StateError` being thrown due to the VM service URIs stream being listened to multiple times.

This change removes this behavior, which also prevents the `StateError` from being thrown.

Fixes https://github.com/flutter/flutter/issues/156692, which is a top-10 crasher for the tool.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/attach.dart [hunk 1]
```diff
@@ -492,7 +397,69 @@ known, it can be explicitly provided to attach via the command-line, e.g.
           );
   }
 
-  Future<void> _validateArguments() async {}
```
Comment (jyameo) [inline packages/flutter_tools/lib/src/commands/attach.dart:495]: The `_validateArguments` method wasn't doing anything before it seems, so removing it makes sense. Just confirming that the intent here is not to include any argument validation logic here.

**Review by jyameo — APPROVED** [review]
LGTM!

File: packages/flutter_tools/lib/src/commands/attach.dart (hunk 1 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/commands/attach.dart:495]: Correct!
