### PR TITLE
Fix FlutterError.onError in debug mode

### LINKED ISSUE #44407: In debugging mode, flutterror.onerror will be overwritten?
Main function code

```dart
Future<Null> main() async {
  // This captures errors reported by the Flutter framework.
  FlutterError.onError = (FlutterErrorDetails details) async {
    if (isInDebugMode) {
      // In development mode simply print to console.
      FlutterError.dumpErrorToConsole(details);
    } else {
      // In production mode report to the application zone to report to
      // Sentry.
      Zone.current.handleUncaughtError(details.exception, details.stack);
    }
  };

  // This creates a [Zone] that contains the Flutter application and stablishes
  // an error handler that captures errors and reports them.
  //
  // Using a zone makes sure that as many errors as possible are captured,
  // including those thrown from [Timer]s, microtasks, I/O, and those forwarded
  // from the `FlutterError` handler.
  //
  // More about zones:
  //
  // - https://api.dartlang.org/stable/1.24.2/dart-async/Zone-class.html
  // - https://www.dartlang.org/articles/libraries/zones
  runZoned<Future<Null>>(() async {
    runApp(new CrashyApp());
  }, onError: (error, stackTrace) async {
    await _reportError(error, stackTrace);
  });
}
```

When debugging, I found that `runZoned` will call the `_registerBoolServiceExtension` function, overriding `FlutterError.onError`.

##### code show as below

path:   flutter\packages\flutter\lib\src\widgets\widget_inspector.dart

line:   964

```dart
_registerBoolServiceExtension(
      name: 'structuredErrors',
      getter: () async => FlutterError.onError == structuredExceptionHandler,
      setter: (bool value) {
        FlutterError.onError = value ? structuredExceptionHandler : defaultExceptionHandler;
        return Future<void>.value();
      },
    );
```

#### Question: After assigning a value to `FlutterError.onError`, how do I assign it a value to avoid being overwritten?

### LINKED ISSUE #47447: FlutterError.onError doesn't work
few days ago, i upgrade flutter version form 1.9(maybe 1.6) to 1.12

i used use `FlutterError.onError` and `runZoned` get some error logs,but today i find FlutterError.onError doesn't work. i'm not sure the reason is flutter upgrade.

here is my code(Simplified)
[testing errors](https://flutter.dev/docs/testing/errors)
```dart
import 'package:flutter/material.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) async {
    print('FlutterError.onError!!!');
    FlutterError.dumpErrorToConsole(details);
  };

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter error'),
        ),
        body: ListView(
          children: <Widget>[
            RaisedButton(
              onPressed: () {
                // throw error
                var tmp = {};
                return tmp['aa']['bb'];
              },
              child: Text('Text error'),
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.amber,
            )
          ],
        ),
      ),
    );
  }
}
```

when i click button `Text error` , console can't output `FlutterError.onError!!!`.

## Logs
`flutter doctor -v`
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\xxx\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\软件\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\软件\android studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • PBCM30 • 6306b2a1 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

Based on https://github.com/flutter/flutter/pull/52728

This pr added a test

## Related Issues

Fixes https://github.com/flutter/flutter/issues/47447
Fixes https://github.com/flutter/flutter/issues/44407

## Tests

I added the following tests:

"ext.flutter.inspector.structuredErrors still report error to original on error"

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chunhtai** [comment]
cc @jimmy-robert

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -958,8 +958,11 @@ mixin WidgetInspectorService {
 
     SchedulerBinding.instance.addPersistentFrameCallback(_onFrameStart);
 
-    final FlutterExceptionHandler structuredExceptionHandler = _reportError;
     final FlutterExceptionHandler defaultExceptionHandler = FlutterError.onError;
+    final FlutterExceptionHandler structuredExceptionHandler = (FlutterErrorDetails details) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:962]: @jacob314 continue from https://github.com/flutter/flutter/pull/52728/files#r397306440

I am not sure if i understand your suggestion. Can you explain a bit more?

File: packages/flutter/test/widgets/widget_inspector_structure_error_test.dart [hunk 2]
```diff
@@ -0,0 +1,51 @@
+import 'package:flutter/foundation.dart';
```
Comment (goderbauer) [inline packages/flutter/test/widgets/widget_inspector_structure_error_test.dart:1]: nit: missing license header (see failing cirrus analyzer check)

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 1 above)
Comment (jacob314) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:962]: what you could  do is only call the defaultExceptionHandler if it does not equal the default exception handler that just prints code to the console. 
The concern is that this change would otherwise make the workflow in the IDEs worse as errors would be printed twice. once in structured format and once dumped to the console as text.
That solution would still be imperfect but a larger fix would require more changes. For example, listening to the structured error output from flutter_tool

**Comment by chunhtai** [comment]
@jacob314 I tried a different approach, let me know what do you think.

File: packages/flutter/test/material/scaffold_test.dart [hunk 3]
```diff
@@ -1840,7 +1840,7 @@ void main() {
         final GlobalKey<ScaffoldState> key = GlobalKey<ScaffoldState>();
         const Key buttonKey = Key('button');
         final List<FlutterErrorDetails> errors = <FlutterErrorDetails>[];
-        FlutterError.onError = (FlutterErrorDetails error) => errors.add(error);
+        FlutterError.presentError = (FlutterErrorDetails error) => errors.add(error);
```
Comment (chunhtai) [inline packages/flutter/test/material/scaffold_test.dart:1843]: This is fairly sad change. The widget tree failed to tear down after this test probably because the widget tree is in a bad shape. The test was passing because it does not restore onError at the end of the test and the error was ignored.

**Review by jacob314 — COMMENTED** [review]
lgtm

@goderbauer may have suggestions for alternate names for presentError that would better align with the rest of the Flutter framework.
The behavior for the inspector is what I want.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 4]
```diff
@@ -725,7 +725,17 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
   ///
   /// Set this to null to silently catch and ignore errors. This is not
   /// recommended.
-  static FlutterExceptionHandler onError = dumpErrorToConsole;
+  static FlutterExceptionHandler onError = (FlutterErrorDetails details) => presentError(details);
```
Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:728]: could this just be

```suggestion
static FlutterExceptionHandler onError = presentError;
```

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 5]
```diff
@@ -725,7 +725,17 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
...
+
+  /// Called whenever the Flutter framework wants to present error to the users.
```
Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:730]: ... an error ...

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 6]
```diff
@@ -725,7 +725,17 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
...
+  ///
+  /// The default behavior is to call [dumpErrorToConsole].
+  ///
+  /// Plugins can override how an error to be presented to the users. For
```
Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:734]: ... an error is to be ... to the user.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 7]
```diff
@@ -725,7 +725,17 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
...
+  /// example, the structured errors service extension sets its own method when
+  /// the extension is enabled. If ypu want change how flutter responds to an
```
Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:736]: ypu -> you

Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:736]: ... want to change ...

Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:736]: flutter -> Flutter

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 8]
```diff
@@ -725,7 +725,17 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
...
+  /// error , use [onError] instead.
```
Comment (goderbauer) [inline packages/flutter/lib/src/foundation/assertions.dart:737]: remove extra space before ,

**Review by goderbauer — COMMENTED** [review]
The name seems fine.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/foundation/assertions.dart:728]: This is intentional. ```static FlutterExceptionHandler onError = presentError;``` will cause an issue
when other people override `presentError`. If someone do `Flutter.presentError = some other method`,  `flutter.onError` will still use the old `presentError` instead of the new one.

Comment (goderbauer) [reply packages/flutter/lib/src/foundation/assertions.dart:728]: Ah, makes sense.

**Review by goderbauer — APPROVED** [review]
