### PR TITLE
Fix scrolling in the  `Drawer` and `NavigationDrawer` triggers AppBar's scrolledUnderElevation

### LINKED ISSUE #120083: Elevation and scrollUnderElevation depends on scrolling in NavigationDrawer
#91605

https://user-images.githubusercontent.com/102767277/216998500-414e2bbf-d0ad-4c86-88ab-bb9333f6f885.mp4

```
import 'package:flutter/material.dart';
import 'package:dynamic_color/dynamic_color.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return DynamicColorBuilder(
      builder: (lightDynamic, darkDynamic) {
        return MaterialApp(
          title: 'Test AppBar',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            useMaterial3: true,
            brightness: Brightness.light,
            colorScheme: lightDynamic,
          ),
          darkTheme: ThemeData(
            useMaterial3: true,
            brightness: Brightness.dark,
            colorScheme: darkDynamic,
          ),
          home: IterableList(),
        );
      },
    );
  }
}

class IterableList extends StatelessWidget {
  const IterableList({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Small TopAppBar'),
        actions: [
          IconButton(onPressed: () {}, icon: Icon(Icons.favorite)),
          IconButton(onPressed: () {}, icon: Icon(Icons.favorite)),
        ],
        shape: Border.all(color: Colors.transparent),
        toolbarHeight: 64,
      ),
      drawer: MyNavigationDrawer(),
      body: ListView.builder(
        itemCount: 76,
        itemBuilder: (context, index) {
          return Padding(
            padding: EdgeInsets.only(left: 15, bottom: 6),
            child: Text(index.toString(), style: TextStyle(fontSize: 16)),
          );
        },
      ),
      floatingActionButton: FloatingActionButton.large(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}

class MyNavigationDrawer extends StatefulWidget {
  const MyNavigationDrawer({super.key});

  @override
  State<MyNavigationDrawer> createState() => _MyNavigationDrawerState();
}

class _MyNavigationDrawerState extends State<MyNavigationDrawer> {
  int selectedIndex = 0;

  void onDestinationSelected(int index) {
    setState(() {
      selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return NavigationDrawer(
      selectedIndex: selectedIndex,
      onDestinationSelected: onDestinationSelected,
      children: [
        /*Padding(
          padding: EdgeInsets.fromLTRB(28, 16, 16, 10),
          child: Text('Mail', style: Theme.of(context).textTheme.titleSmall),
        ),*/
        Padding(
          padding: EdgeInsets.only(left: 28),
          child: Text(
            'Navigation Drawer',
             style: GoogleFonts.manrope(
               fontWeight: FontWeight.w500,
               textStyle: Theme.of(context).textTheme.titleLarge,
               height: 3,
            ),
          ),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.token_outlined),
          selectedIcon: Icon(Icons.token),
          label: Text('Inbox'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.mail_outline),
          selectedIcon: Icon(Icons.mail),
          label: Text('OutBox'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.favorite_border_outlined),
          selectedIcon: Icon(Icons.favorite),
          label: Text('Favorites'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.delete_outline),
          selectedIcon: Icon(Icons.delete),
          label: Text('Trash'),
        ),
        Divider(indent: 28, endIndent: 28),
        Padding(
          padding: EdgeInsets.fromLTRB(28, 16, 16, 10),
          child: Text('Labels', style: Theme.of(context).textTheme.titleSmall),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.circle_outlined),
          label: Text('Label circle'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.change_history),
          label: Text('Label triagle'),
        ),
        NavigationDrawerDestination(
          icon: Icon(Icons.square_outlined),
          label: Text('Label square'),
        ),
        Divider(indent: 28, endIndent: 28),
        Center(
          child: TextButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: OutlinedButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: ElevatedButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton.tonal(
            onPressed: () {},
            child: Text('Navigation Drawer'),
          ),
        ),
        Center(
          child: FilledButton.tonalIcon(
            onPressed: () {},
            icon: Icon(Icons.replay_circle_filled_outlined),
            label: Text('Cards screen'),
          ),
        ),
      ],
    );
  }
}
```

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/120083

### Description
This PR fixes the unexpected scrolledUnderElevation trigger when scrolling in the  `Drawer` and `NavigationDrawer` .

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('AppBar'),
      ),
      drawer: const Drawer(
        child: ListWidget(),
      ),
      body: ListView(
        children: <Widget>[
          SizedBox(
            height: 2000,
            child: Align(
              alignment: Alignment.topCenter,
              child: Text(
                'Scroll down here',
                style: Theme.of(context).textTheme.displayLarge,
                textAlign: TextAlign.center,
              ),
            ),
          )
        ],
      ),
    );
  }
}

class ListWidget extends StatefulWidget {
  const ListWidget({super.key});

  @override
  State<ListWidget> createState() => _ListWidgetState();
}

class _ListWidgetState extends State<ListWidget> {
  ScrollNotificationObserverState? _scrollNotificationObserver;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _scrollNotificationObserver?.removeListener(_listener);
    _scrollNotificationObserver = ScrollNotificationObserver.maybeOf(context);
    _scrollNotificationObserver?.addListener(_listener);
  }

  void _listener(ScrollNotification notification) {
    print('NotificationListener: $notification');
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: 30,
      itemBuilder: (BuildContext context, int index) {
        return ListTile(
          title: Text('Item $index'),
        );
      },
    );
  }
}

``` 
	
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -260,17 +267,22 @@ class Drawer extends StatelessWidget {
...
-        child: Material(
-          color: backgroundColor ?? drawerTheme.backgroundColor ?? defaults.backgroundColor,
-          elevation: elevation ?? drawerTheme.elevation ?? defaults.elevation!,
-          shadowColor: shadowColor ?? drawerTheme.shadowColor ?? defaults.shadowColor,
-          surfaceTintColor: surfaceTintColor ?? drawerTheme.surfaceTintColor ?? defaults.surfaceTintColor,
-          shape: shape ?? (isDrawerStart
-            ? (drawerTheme.shape ?? defaults.shape)
-            : (drawerTheme.endShape ?? defaults.endShape)),
-          child: child,
+      child: NotificationListener<Notification>(
```
Comment (Piinks) [inline packages/flutter/lib/src/material/drawer.dart:270]: This does not feel right, the issue is coming from ScrollNotifications, and this feels a bit too broad.

> When wrapping an the Drawer or NavigationDrawer with own NotificationListener, allowNotifications can enable notification bubbling.

This feels like a foot gun for developers, because they can then reintroduce the issue if they do not stop the notification from bubbling up themselves.

Why not just add a ScrollNotificationObserver here and return true? If folks want to listen to notifications within the drawer, they can subscribe to the observer.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/drawer.dart:270]: That makes sense. I can revert the parameter. Thank you!

It only works when returning `true` with `Notification` for some reason. 
This doesn't work
```dart
      child: ScrollNotificationObserver(
        child: NotificationListener<ScrollNotification>(
          onNotification: (ScrollNotification notification) {
            return true;
          },
          child: ConstrainedBox(
```

This does 
```dart
      child: ScrollNotificationObserver(
        child: NotificationListener<Notification>(
          onNotification: (Notification notification) {
            return true;
          },
          child: ConstrainedBox(
```

Even tho AppBar is looking for scroll notification,  this is a weird.

File: packages/flutter/lib/src/material/drawer.dart [hunk 2]
```diff
@@ -260,17 +260,26 @@ class Drawer extends StatelessWidget {
...
-            ? (drawerTheme.shape ?? defaults.shape)
-            : (drawerTheme.endShape ?? defaults.endShape)),
-          child: child,
+      // This prevents notifications from being bubbled up
+      // to the Scaffold.
+      child: NotificationListener<Notification>(
+        onNotification: (Notification notification) {
+          return true;
+        },
+        child: ScrollNotificationObserver(
```
Comment (Piinks) [inline packages/flutter/lib/src/material/drawer.dart:269]: I think I know why just adding this did not work. ScrollNotificationObserver is where the notification is actually handled in the context of it bubbling further up the tree. It just returns false after passing the notification to the listeners:

https://github.com/flutter/flutter/blob/f6bc147c91805e7d5e17ce753b1958e19648a9bc/packages/flutter/lib/src/widgets/scroll_notification_observer.dart#L224-L227

It does not factor in whether any listener it passes the notification to wants to return true and stop the notification from continuing up the tree.

Do you think the ScrollNotificationObserver should include the return value from its listeners?

File: packages/flutter/lib/src/material/drawer.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/drawer.dart:265]: This still stops any and all notifications from leaving the Drawer. I cannot think of anything in particular that would break as a result of this... but I am not sure.
@HansMuller what do you think?

Comment (HansMuller) [reply packages/flutter/lib/src/material/drawer.dart:265]: I suppose in most cases this would be safe, since the Drawer is usually part of the Scaffold, and usually nothing above the drawer cares if the Drawer is scrolling. I haven't looked at the history of this PR however it seems like it would be safer if the Scaffold squelched scroll notifications from the Drawer, rather than the Drawer doing it. It would still sort-of fail in the oddball case where there are nested scaffolds and was expected that scroll notifications from the inner Scaffold's Drawer would case the outer Scaffold to scroll. That seems like a pretty unlikely use case.

I suppose what we really need here is a way to identify the source of the notification. The AppBar only cares if the body of the Scaffold is scrolling.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/drawer.dart:265]: > I suppose what we really need here is a way to identify the source of the notification. The AppBar only cares if the body of the Scaffold is scrolling.

Notifications could be from any nested children in the body and I don't know if there is a way to filter all notifications from the body. `ScrollNotificationObserver` seems to listen to all scroll notifications. 

Since the app bar should not care about the scrolling notifications from the drawer. 

What If we have a check like this inside the AppBar? This way we don't have squelched scroll notifications from the Drawers and AppBar can don't update `MaterialState.scrolledUnder` if the drawer is open. Wdyt?

```dart
  void _handleScrollNotification(ScrollNotification notification) {
    if (notification is ScrollUpdateNotification && widget.notificationPredicate(notification)) {
      final bool isAnyDrawerOpen = (notification.context?.findAncestorStateOfType<ScaffoldState>()?.isDrawerOpen ?? false)
        || (notification.context?.findAncestorStateOfType<ScaffoldState>()?.isEndDrawerOpen ?? false);
      // If any drawer is open, don't change the scrolledUnder state.
      if (!isAnyDrawerOpen) {
        final bool oldScrolledUnder = _scrolledUnder;
        final ScrollMetrics metrics = notification.metrics;
        switch (metrics.axisDirection) {
          case AxisDirection.up:
            // Scroll view is reversed
            _scrolledUnder = metrics.extentAfter > 0;
            break;
          case AxisDirection.down:
            _scrolledUnder = metrics.extentBefore > 0;
            break;
          case AxisDirection.right:
          case AxisDirection.left:
            // Scrolled under is only supported in the vertical axis, and should
            // not be altered based on horizontal notifications of the same
            // predicate since it could be a 2D scroller.
            break;
        }

        if (_scrolledUnder != oldScrolledUnder) {
          setState(() {
            // React to a change in MaterialState.scrolledUnder
          });
        }
      }
    }
  }
```

File: packages/flutter/lib/src/material/drawer.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/drawer.dart:269]: That's a great catch! I'm unsure if it could be an optional return or always return value from listeners.

File: packages/flutter/lib/src/material/drawer.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/drawer.dart:265]: > Notifications could be from any nested children in the body and I don't know if there is a way to filter all notifications from the body. ScrollNotificationObserver seems to listen to all scroll notifications.

ScrollNotification.context.findAncestorWidgetOfExactType could be used to write a predicate that returned true if the context was a descendant of the Scaffold's body (a predicate like Scaffold.isBodyDescendant(context)).

**Review by Piinks — APPROVED** [review]
Nice! LGTM!

**Comment by Hixie** [comment]
This apparently caused a regression: https://github.com/flutter/flutter/issues/123782

Would it make sense to revert this while the regression is being worked on?

**Comment by HansMuller** [comment]
@TahaTesser  - Since the claim in https://github.com/flutter/flutter/issues/123782 is that scrolling performance is diminished by 10% for essentially all scrolls within an app with an AppBar, then - yes - we should revert this PR and find a way to avoid the performance penalty.
