### PR TITLE
Prevent overlapping hero transitions from starting

### LINKED ISSUE #7203: Calling popAndPushNamed throws exception
If there's more than one route in the current stack and when popAndPushNamed is called(or calling pop and then push), the following exception will be thrown:

I/flutter ( 6710): NoSuchMethodError: The getter 'subtreeContext' was called on null.
I/flutter ( 6710): Receiver: null
I/flutter ( 6710): Tried calling: subtreeContext
I/flutter ( 6710): When the exception was thrown, this was the stack:
I/flutter ( 6710): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter ( 6710): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter ( 6710): #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:579)
I/flutter ( 6710): #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:653)
I/flutter ( 6710): #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:596)
I/flutter ( 6710): #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)

### PR DESCRIPTION
**Pull request by HansMuller**
Currently the HeroController's NavigatorObserver only supports one hero transition at a time.

We do need to enable running multiple overlapping hero transitions. See https://github.com/flutter/flutter/issues/5798.

This provisional change just quietly disables the second and subequent overlapping hero transitions so that Navigator operations like popAndPushNamed() will succeed.

Fixes: https://github.com/flutter/flutter/issues/7203

### CODE REVIEW

File: packages/flutter/test/widgets/navigator_test.dart [hunk 1]
```diff
@@ -209,4 +232,32 @@ void main() {
   //   await gesture.up();
   //   expect(log, equals(<String>['left']));
   // });
+
+  testWidgets('popAndPushNamed', (WidgetTester tester) async {
+    final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
+       '/': (BuildContext context) => new OnTapPage(id: '/', onTap: () { Navigator.pushNamed(context, '/A'); }),
```
Comment (abarth) [inline packages/flutter/test/widgets/navigator_test.dart]: bad indent

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
This basically disables hero animations in general any time the user taps routes faster than the transitions complete. Most of the hero code is all about supporting that specific case. I guess I'm fine with it but this certainly increases the priority of Heroes v2.

**Comment by HansMuller** [comment]
I've moved the _questsEnabled=true into _updateQuest(), where we clear the other state collected at didPush/didPop time.

**Comment by HansMuller** [comment]
Moving the _questsEnabled=true made it possible to restore the two page transition tests

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 2]
```diff
@@ -571,6 +573,7 @@ class HeroController extends NavigatorObserver {
   }
 
   void _updateQuest(Duration timeStamp) {
+    assert(!_questsEnabled);
     if (navigator == null) {
       // The navigator was removed before this end-of-frame callback was called.
       _clearPendingHeroQuest();
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: does this branch mean that if go down this branch, you'll never re-enable heroes even if you re-use the object?

**Comment by Hixie** [comment]
I don't really understand what this is doing, but with the caveat that it'll be revamped soon anyway, LGTM.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 2 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: If the Navigator is disposed before the Hero quest is set up, and then the existing HeroController is reused with a new Navigator, then yes.  I'll reset the _questsEnabled flag in _clearPendingRequests, it makes a bit more sense there.
