### PR TITLE
Move plugin injection to just after pub get

### LINKED ISSUE #11797: Avoid MissingPluginException by detecting that GeneratedPluginRegistrant is out of sync with pubspec.yaml
## Steps to Reproduce

- new flutter project
- add google sign in
- run on iOS

It worked before on iOS.

## Logs

```
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale nl-NL, channel master)
    • Flutter at /development/flutter
    • Framework revision f265301519 (2 days ago), 2017-08-25 17:21:46 -0700
    • Engine revision f5371156d2
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/theobouwman/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • iPhone 6 • 8BD274CA-B00F-46DB-82D6-F1ED0A312D05 • ios • iOS 10.3 (simulator)
```

### LINKED ISSUE #12752: Emit CocoaPods #include in Debug.xcconfig, Release.xcconfig
CocoaPods 1.3.1 emits the following warnings when the Pods-Runner xcconfig is included in `Generated.xcconfig`, rather than directly in `Debug.xcconfig` or `Release.xcconfig`:

```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
```

Ideally Debug.xcconfig should contain:
```
#include "../Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
```

And Release.xcconfig should contain:
```
#include "../Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
```

### LINKED ISSUE #13554: GeneratedPluginRegistrant should not be checked in
We currently check in GeneratedPluginRegistrant.java/.m/.h to make sure that our example can run from an IDE (Android Studio/xcode) without previously running `flutter run`.

Would be good, if these files would just get generated on the fly even when running from IDE so that we don't have to check in and maintain generated files in the repository.

This is a continuation of the discussion in https://github.com/flutter/flutter/pull/13500.

/cc @mit-mit @mravn-google

### PR DESCRIPTION
**Pull request by mravn-google**
Move injection of Flutter plugins from just before build to just after getting/updating pub packages.

Plugin injection here means
* writing the `.flutter-plugins` file
* writing the `GeneratedPluginRegistrant.(java|h|m)` files
* writing the iOS `Podfile`, if it doesn't exit
* adding `#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.xxx.xcconfig"` to `ios/Flutter/Xxx.xcconfig` files (cf. https://github.com/flutter/flutter/issues/12752).

**The intention** is to get us to a situation where upon initial project checkout or change to `pubspec.yaml`, the only step needed to get to a project buildable by platform-specific tooling is `flutter packages get`.

Discrepancies between `pubspec.yaml` and injected plugin files have caused usability problems (https://github.com/flutter/flutter/issues/11797). And we have been forced to check in the injected files as if they were source code (https://github.com/flutter/flutter/issues/13554) to make our project examples work out of the box.

Fixes #12752
Fixes #11797
Fixes #13554

### CODE REVIEW

File: packages/flutter_tools/lib/src/plugins.dart [hunk 1]
```diff
@@ -140,6 +140,7 @@ void _writeAndroidPluginRegistry(String directory, List<Plugin> plugins) {
   final Map<String, dynamic> context = <String, dynamic>{
     'plugins': androidPlugins,
   };
+  print('Here BB plugins');
```
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/plugins.dart]: :)

**Review by jakobr-google — COMMENTED** [review]
Concept LGTM!

**Comment by mravn-google** [comment]
@jakobr-google, @xster This PR is ready for code review.

File: packages/flutter_tools/lib/src/ios/cocoapods.dart [hunk 2]
```diff
@@ -99,39 +97,60 @@ class CocoaPods {
...
+      final String include = '#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.${mode
+          .toLowerCase()}.xcconfig"';
+      if (!content.contains(include))
+        file.writeAsStringSync('$include\n$content', flush: true);
+    }
   }
 
   // Check if you need to run pod install.
   // The pod install will run if any of below is true.
-  // 1. Any plugins changed (add/update/delete)
```
Comment (xster) [inline packages/flutter_tools/lib/src/ios/cocoapods.dart]: This is still true no?

File: packages/flutter_tools/lib/src/ios/cocoapods.dart [hunk 3]
```diff
@@ -60,13 +61,10 @@ class CocoaPods {
     // For backward compatibility with previously created Podfile only.
     @required String iosEngineDir,
     bool isSwift: false,
-    bool pluginOrFlutterPodChanged: true,
+    bool flutterPodChanged: true,
   }) async {
     if (await _checkPodCondition()) {
-      if (!fs.file(fs.path.join(appIosDir.path, 'Podfile')).existsSync()) {
```
Comment (xster) [inline packages/flutter_tools/lib/src/ios/cocoapods.dart]: I'm assuming this implies we've built in some knowledge here that `flutter run` will necessarily run `flutter packages get` before and will never have cases where `pod install` is run in a project that doesn't have a Podfile?

File: packages/flutter_tools/lib/src/plugins.dart [hunk 4]
```diff
@@ -224,17 +228,37 @@ class InjectPluginsResult{
...
-  if (fs.isDirectorySync(fs.path.join(directory, 'ios')))
-    _writeIOSPluginRegistry(directory, plugins);
-  return new InjectPluginsResult(hasPlugin: plugins.isNotEmpty, hasChanged: hasPluginsChanged);
+    _writeAndroidPluginRegistrant(directory, plugins);
+  if (fs.isDirectorySync(fs.path.join(directory, 'ios'))) {
+    _writeIOSPluginRegistrant(directory, plugins);
+    if (plugins.isNotEmpty)
+      const CocoaPods().setupPodfile(directory);
+    if (changed)
+      _ensurePodInstallIsExecutedOnNextIOSBuild(directory);
```
Comment (xster) [inline packages/flutter_tools/lib/src/plugins.dart]: Based on your PR description, wouldn't you want to run pod install here too? 

i.e. is the desired outcome that after `flutter packages get`, the user can just open Xcode and press run?

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 5]
```diff
@@ -254,26 +254,22 @@ Future<XcodeBuildResult> buildXcodeProject({
...
   await _addServicesToBundle(appDirectory);
-  final InjectPluginsResult injectPluginsResult = injectPlugins();
-  final bool hasFlutterPlugins = injectPluginsResult.hasPlugin;
   final String previousGeneratedXcconfig = readGeneratedXcconfig(app.appDirectory);
 
   updateXcodeGeneratedProperties(
     projectPath: fs.currentDirectory.path,
     buildInfo: buildInfo,
     target: target,
-    hasPlugins: hasFlutterPlugins,
```
Comment (xster) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Depending on if I understood the PR description intent correctly, it sounds like you want to move this call to `updateXcodeGeneratedProperties` to `flutter packages get` in a future PR too?

**Review by xster — COMMENTED** [review]
LGTM assuming this is PR 1 of many. Otherwise I may have some additional questions.

**Comment by xster** [comment]
Should we add some new gitignores too?

File: packages/flutter_tools/lib/src/plugins.dart (hunk 4 above)
Comment (xster) [reply packages/flutter_tools/lib/src/plugins.dart]: Can we also move this into the cocoapods.dart? To keep the encapsulation and discoverability clearer.

**Comment by mravn-google** [comment]
@xster There is a follow-up PR to remove generated files and update gitignore: #14697

File: packages/flutter_tools/lib/src/plugins.dart (hunk 4 above)
Comment (mravn-google) [reply packages/flutter_tools/lib/src/plugins.dart]: The intention of this PR is that `flutter packages get` brings the project into a state where platform-specific tooling works without `flutter xxx` help.

For **Android** that means Gradle builds work. Gradle nicely does both dependency resolution of non-pub packages and actual building.

The directly corresponding **iOS** situation is that Cocoapods+Xcode work. Doing `pod install` as part of `flutter packages get` would break this symmetry. That may be just an academic point, but we seem to have gone to great lengths to avoid doing `pod install` until there is no way around it (I assume because the pods repo is painful to download). If the user just wants to run her Flutter project on Android, `pod install` is not needed. We don't know the user's intention at `flutter packages get` time.

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 5 above)
Comment (mravn-google) [reply packages/flutter_tools/lib/src/ios/mac.dart]: I think you are right. I left that out because 1) it was not necessary on a newly created project, and 2) the properties include information like the build mode which is not available when we run `flutter packages get`.

But 1) is because `flutter create` generates the `Generated.xcconfig` file with some default settings along with a .gitignore entry that causes it not to be present on subsequent git checkout. And for 2) those default settings can be used during `flutter packages get` too.

File: packages/flutter_tools/lib/src/ios/cocoapods.dart (hunk 3 above)
Comment (mravn-google) [reply packages/flutter_tools/lib/src/ios/cocoapods.dart]: That's the idea. `flutter run` will automatically call `flutter packages get` if your `pubspec.yaml` file has changed relative to your `.packages` and/or `.pubspec.lock`. So you'll get a `Podfile` if your project needs it and you don't already have one; it just isn't done by our `buildXcodeProject` code path.

I guess I should add checks for those assumptions here.

File: packages/flutter_tools/lib/src/ios/cocoapods.dart (hunk 2 above)
Comment (mravn-google) [reply packages/flutter_tools/lib/src/ios/cocoapods.dart]: See item 3.

File: packages/flutter_tools/lib/src/plugins.dart (hunk 4 above)
Comment (mravn-google) [reply packages/flutter_tools/lib/src/plugins.dart]: Move into `cocoapods.dart`: good point, done.

**Comment by mravn-google** [comment]
@xster Thanks for the review. I've restructured some of the code to make the intention clearer. I also worked on improving test coverage. PTAL and let me know whether your concerns have been addressed by the changes and the comments above.

File: packages/flutter_tools/lib/src/ios/cocoapods.dart (hunk 3 above)
Comment (xster) [reply packages/flutter_tools/lib/src/ios/cocoapods.dart]: A check would be good to proof against future refactors by maintainers unaware of this contract.

File: packages/flutter_tools/lib/src/plugins.dart (hunk 4 above)
Comment (xster) [reply packages/flutter_tools/lib/src/plugins.dart]: SG

**Review by xster — APPROVED** [review]
LGTM
