### PR TITLE
Fix gets removedItem instead of its index

### LINKED ISSUE #105251: SliverAnimatedList doc example bug
[SliverAnimatedList code example](https://api.flutter.dev/flutter/widgets/SliverAnimatedList-class.html) has a bug, where on removal, CardWidget is built with index of an item instead of actual removed object. Though AnimatedList example doesn't contain one.
image
image

### PR DESCRIPTION
**Pull request by jehhxuxu**
fixes https://github.com/flutter/flutter/issues/105251

Fix gets removedItem instead of its index
Add sliver_animated_list.0_test.dart

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: examples/api/test/widgets/animated_list/sliver_animated_list.0_test.dart [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+      await tester.tap(find.text('Item 1'));
+      await tester.pumpAndSettle();
+      //add item at the top of the list
+      await tester.tap(find.byIcon(Icons.add_circle));
+      await tester.pumpAndSettle();
+      expect(find.text('Item 4'), findsOneWidget);
+
+      //remove Item 1 that was selected before
+      await tester.tap(find.byIcon(Icons.remove_circle));
+      //one frame ahead the Item 1 is still animating on the screen
```
Comment (TahaTesser) [inline examples/api/test/widgets/animated_list/sliver_animated_list.0_test.dart:35]:
```suggestion
      // Item animation is not completed. 
```

File: examples/api/test/widgets/animated_list/sliver_animated_list.0_test.dart [hunk 2]
```diff
@@ -0,0 +1,44 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/material.dart';
+import 'package:flutter_api_samples/widgets/animated_list/sliver_animated_list.0.dart'
+    as example;
```
Comment (TahaTesser) [inline examples/api/test/widgets/animated_list/sliver_animated_list.0_test.dart:7]:
```suggestion
import 'package:flutter_api_samples/widgets/animated_list/sliver_animated_list.0.dart' as example;
```

**Comment by TahaTesser** [comment]
@jehhxuxu 
Good job! Thank you for submitting the PR.
Just some fixes are needed.

**Comment by TahaTesser** [comment]
@Piinks 
Can we get a second review to land this?

**Review by TahaTesser — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
This is great! Welcome @jehhxuxu, thanks for contributing.

Flutter_LGTM
