### PR TITLE
Close the IntegrationTestTestDevice stream when the VM service shuts down

### LINKED ISSUE #89829: [integration_test]: Tests never complete after native crash
## Steps to Reproduce

1. Run `flutter create integration_test_native_crash`.
2. Run `flutter pub add --dev integration_test --sdk flutter`
3. Create folder `integration_test` and add file `native_crash_test.dart`:
```dart
import 'dart:ffi';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  
  testWidgets('cause native crash', (_) async {
    abort();
  });
}

void abort() {
  final process = DynamicLibrary.process();
  final abort =
      process.lookupFunction<Void Function(), void Function()>('abort');
  abort();
}
```
4. Run `flutter test integration_test/native_crash_test.dart`

**Expected results:**
The test command should fail and report that the test app exited unexpectedly. Optimally, a crash report is displayed.

**Actual results:**
The test command never completes.

<details>
  <summary>Logs</summary>

```
➜  integration_test_native_crash flutter test -v -d macos integration_test/native_crash_test.dart
[ +107 ms] executing: sysctl hw.optional.arm64
[  +23 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[  +20 ms] executing: [/Users/gabriel/lib/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] executing: [/Users/gabriel/lib/flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[ +102 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[  +20 ms] executing: [/Users/gabriel/lib/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/gabriel/lib/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +122 ms] executing: [/Users/gabriel/lib/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +7 ms] executing: sw_vers -productName
[  +29 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +27 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.5.2
[        ] executing: sw_vers -buildVersion
[  +22 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G95
[  +75 ms] Found 1 files which will be executed as Integration Tests.
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +85 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] Skipping pub get: version match.
[  +69 ms] Found plugin integration_test at /Users/gabriel/lib/flutter/packages/integration_test/
[ +123 ms] Found plugin integration_test at /Users/gabriel/lib/flutter/packages/integration_test/
[  +10 ms] Generating /Users/gabriel/Desktop/integration_test_native_crash/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +58 ms] executing: sysctl hw.optional.arm64
[  +42 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +2 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +5 ms] executing: xcrun xcodebuild -version
[ +502 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.5.1
           Build version 12E507
[ +226 ms] running test package with arguments: [-r, compact, --timeout, 30s, --concurrency=1, --chain-stack-traces, --,
/Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart]
00:00 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +240 ms] test 0: starting test /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart
[  +11 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/gabriel/Desktop/integration_test_native_crash
[   +2 ms] test 0: starting test device
[   +5 ms] test 0: awaiting connection to test device
[ +180 ms] Found plugin integration_test at /Users/gabriel/lib/flutter/packages/integration_test/
[  +25 ms] executing: which pod
[  +51 ms] executing: pod --version
00:01 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [+1328 ms] 1.10.1
[   +2 ms] Running pod install...
00:03 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [+1461 ms] Running pod install... (completed in 1,451ms)
[        ] CocoaPods' output:
           ↳
[        ]       Preparing
           
               Analyzing dependencies
           
               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
           
               Finding Podfile changes
                 - FlutterMacOS
           
               Fetching external sources
               -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
           
               Resolving dependencies of `Podfile`
                 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
           
               Comparing resolved specification to the sandbox manifest
                 - FlutterMacOS
           
               Downloading dependencies
           
               -> Using FlutterMacOS (1.0.0)
                 - Running pre install hooks
           
               Generating Pods project
                 - Creating Pods project
                 - Installing files into Pods project
                   - Adding source files
                   - Adding frameworks
                   - Adding libraries
                   - Adding resources
                   - Adding development pod helper files
                   - Linking headers
                 - Installing Pod Targets
                   - Installing target `FlutterMacOS` macOS 10.11
                 - Installing Aggregate Targets
                   - Installing target `Pods-Runner` macOS 10.11
                     - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
                     - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
                     - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
                     - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
                 - Generating deterministic UUIDs
                 - Stabilizing target UUIDs
                 - Running post install hooks
                   - Podfile
                 - Writing Xcode project file to `Pods/Pods.xcodeproj`
                 Cleaning up sandbox directory
           
               Integrating client project
           
               Integrating target `Pods-Runner` (`Runner.xcodeproj` project)
                 - Running post integrate hooks
                 - Writing Lockfile in `Podfile.lock`
                 - Writing Manifest in `Pods/Manifest.lock`
                 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
           
               -> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
           
[   +1 ms] Error output from CocoaPods:
           ↳
[   +9 ms] 
               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods
               integration to work at all, please either set the base configurations of the target `Runner` to `Target Support
               Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build
configuration
               (`Runner/Configs/AppInfo.xcconfig`).
           
               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods
               integration to work at all, please either set the base configurations of the target `Runner` to `Target Support
               Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build
               configuration (`Runner/Configs/AppInfo.xcconfig`).
           
               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods
               integration to work at all, please either set the base configurations of the target `Runner` to `Target Support
               Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build
               configuration (`Runner/Configs/AppInfo.xcconfig`).
           
[  +18 ms] executing: [/Users/gabriel/Desktop/integration_test_native_crash/macos/] xcrun xcodebuild -list -project Runner.xcodeproj
00:05 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [+2179 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list -project Runner.xcodeproj

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Information about project "Runner":
                        Targets:
                            Runner
                            Flutter Assemble

                        Build Configurations:
                            Debug
                            Release
                            Profile

                        If no build configuration is specified and -scheme is not passed then "Release" is used.

                        Schemes:
                            Flutter Assemble
                            Runner
[   +3 ms] Building macOS application...
[   +3 ms] executing: /usr/bin/env xcrun xcodebuild -workspace /Users/gabriel/Desktop/integration_test_native_crash/macos/Runner.xcworkspace -configuration
Debug -scheme Runner -derivedDataPath /Users/gabriel/Desktop/integration_test_native_crash/build/macos
OBJROOT=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
SYMROOT=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products VERBOSE_SCRIPT_LOGGING=YES COMPILER_INDEX_STORE_ENABLE=NO
00:06 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +730 ms] Command line invocation:
[   +1 ms]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace
/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner.xcworkspace -configuration Debug -scheme Runner -derivedDataPath
/Users/gabriel/Desktop/integration_test_native_crash/build/macos
OBJROOT=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
SYMROOT=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products VERBOSE_SCRIPT_LOGGING=YES COMPILER_INDEX_STORE_ENABLE=NO
[   +1 ms] User defaults from command line:
[        ]     IDEDerivedDataPathOverride = /Users/gabriel/Desktop/integration_test_native_crash/build/macos
[        ]     IDEPackageSupportUseBuiltinSCM = YES
[        ] Build settings from command line:
[        ]     COMPILER_INDEX_STORE_ENABLE = NO
[        ]     OBJROOT = /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     SYMROOT = /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     VERBOSE_SCRIPT_LOGGING = YES
[ +916 ms] note: Using new build system
[   +1 ms] note: Building targets in parallel
[  +15 ms] note: Planning build
00:07 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [  +87 ms] note: Analyzing workspace
[  +65 ms] note: Constructing build description
00:08 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [+1383 ms] note: Build preparation complete
[  +97 ms] WriteAuxiliaryFile /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-1136f8cdea46e94bbc64fc727eb739f1-resolved.xcfilelist (in target 'Flutter Assemble' from
project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     write-file /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-1136f8cdea46e94bbc64fc727eb739f1-resolved.xcfilelist
[  +11 ms] PhaseScriptExecution Run\ Script
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Script-33CC111E2044C6BF0003C045.sh (in target 'Flutter Assemble' from project 'Runner')
[   +1 ms]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export ACTION\=build
[        ]     export AD_HOC_CODE_SIGNING_ALLOWED\=YES
[        ]     export ALTERNATE_GROUP\=staff
[        ]     export ALTERNATE_MODE\=u+w,go-w,a+rX
[        ]     export ALTERNATE_OWNER\=gabriel
[        ]     export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
[        ]     export ALWAYS_SEARCH_USER_PATHS\=NO
[        ]     export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
[        ]     export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
[        ]     export APPLE_INTERNAL_DIR\=/AppleInternal
[        ]     export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
[        ]     export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
[        ]     export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
[        ]     export APPLICATION_EXTENSION_API_ONLY\=NO
[        ]     export APPLY_RULES_IN_COPY_FILES\=NO
[        ]     export APPLY_RULES_IN_COPY_HEADERS\=NO
[        ]     export ARCHS\=x86_64
[        ]     export ARCHS_STANDARD\=arm64\ x86_64
[        ]     export ARCHS_STANDARD_32_64_BIT\=arm64\ x86_64\ i386
[        ]     export ARCHS_STANDARD_32_BIT\=i386
[        ]     export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
[        ]     export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64
[        ]     export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
[        ]     export BITCODE_GENERATION_MODE\=marker
[        ]     export BUILD_ACTIVE_RESOURCES_ONLY\=NO
[        ]     export BUILD_COMPONENTS\=headers\ build
[        ]     export BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
[        ]     export BUILD_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export BUILD_STYLE\=
[        ]     export BUILD_VARIANTS\=normal
[        ]     export BUILT_PRODUCTS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export BUNDLE_CONTENTS_FOLDER_PATH\=Contents/
[        ]     export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
[        ]     export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
[        ]     export BUNDLE_EXECUTABLE_FOLDER_PATH\=Contents/MacOS
[        ]     export BUNDLE_FORMAT\=deep
[        ]     export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Contents/Frameworks
[        ]     export BUNDLE_PLUGINS_FOLDER_PATH\=Contents/PlugIns
[        ]     export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=Contents/PrivateHeaders
[   +2 ms]     export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Contents/Headers
[        ]     export CACHE_ROOT\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/C/com.apple.DeveloperTools/12.5.1-12E507/Xcode
[        ]     export CCHROOT\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/C/com.apple.DeveloperTools/12.5.1-12E507/Xcode
[        ]     export CHMOD\=/bin/chmod
[        ]     export CHOWN\=/usr/sbin/chown
[        ]     export CLANG_ANALYZER_NONNULL\=YES
[        ]     export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION\=YES_AGGRESSIVE
[        ]     export CLANG_CXX_LANGUAGE_STANDARD\=gnu++14
[        ]     export CLANG_CXX_LIBRARY\=libc++
[        ]     export CLANG_ENABLE_MODULES\=YES
[        ]     export CLANG_ENABLE_OBJC_ARC\=YES
[        ]     export
CLANG_MODULES_BUILD_SESSION_FILE\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex/Session.modulevalidation
[        ]     export CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY\=YES
[        ]     export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING\=YES
[   +2 ms]     export CLANG_WARN_BOOL_CONVERSION\=YES
[   +5 ms]     export CLANG_WARN_COMMA\=YES
[        ]     export CLANG_WARN_CONSTANT_CONVERSION\=YES
[        ]     export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS\=YES
[        ]     export CLANG_WARN_DIRECT_OBJC_ISA_USAGE\=YES_ERROR
[        ]     export CLANG_WARN_DOCUMENTATION_COMMENTS\=YES
[        ]     export CLANG_WARN_EMPTY_BODY\=YES
[        ]     export CLANG_WARN_ENUM_CONVERSION\=YES
[        ]     export CLANG_WARN_INFINITE_RECURSION\=YES
[        ]     export CLANG_WARN_INT_CONVERSION\=YES
[        ]     export CLANG_WARN_NON_LITERAL_NULL_CONVERSION\=YES
[        ]     export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF\=YES
[        ]     export CLANG_WARN_OBJC_LITERAL_CONVERSION\=YES
[        ]     export CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK\=YES
[        ]     export CLANG_WARN_OBJC_ROOT_CLASS\=YES_ERROR
[        ]     export CLANG_WARN_PRAGMA_PACK\=YES
[        ]     export CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER\=NO
[        ]     export CLANG_WARN_RANGE_LOOP_ANALYSIS\=YES
[        ]     export CLANG_WARN_STRICT_PROTOTYPES\=YES
[        ]     export CLANG_WARN_SUSPICIOUS_MOVE\=YES
[        ]     export CLANG_WARN_UNGUARDED_AVAILABILITY\=YES_AGGRESSIVE
[        ]     export CLANG_WARN_UNREACHABLE_CODE\=YES
[        ]     export CLANG_WARN__DUPLICATE_METHOD_MATCH\=YES
[   +2 ms]     export
CLASS_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/JavaClasses
[        ]     export CLEAN_PRECOMPS\=YES
[        ]     export CLONE_HEADERS\=NO
[        ]     export COCOAPODS_PARALLEL_CODE_SIGN\=true
[        ]     export CODESIGNING_FOLDER_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/
[        ]     export CODE_SIGNING_ALLOWED\=YES
[        ]     export CODE_SIGN_IDENTITY\=-
[        ]     export CODE_SIGN_IDENTITY_NO\=Apple\ Development
[        ]     export CODE_SIGN_IDENTITY_YES\=-
[        ]     export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
[        ]     export CODE_SIGN_STYLE\=Manual
[        ]     export COLOR_DIAGNOSTICS\=NO
[        ]     export COMBINE_HIDPI_IMAGES\=NO
[        ]     export COMPILER_INDEX_STORE_ENABLE\=NO
[        ]     export COMPOSITE_SDK_DIRS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/CompositeSDKs
[        ]     export COMPRESS_PNG_FILES\=NO
[        ]     export CONFIGURATION\=Debug
[        ]     export CONFIGURATION_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[   +2 ms]     export
CONFIGURATION_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug
[        ]     export COPYING_PRESERVES_HFS_DATA\=NO
[        ]     export COPY_HEADERS_RUN_UNIFDEF\=NO
[        ]     export COPY_PHASE_STRIP\=NO
[        ]     export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS\=YES
[        ]     export CP\=/bin/cp
[        ]     export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
[        ]     export CURRENT_ARCH\=undefined_arch
[        ]     export CURRENT_VARIANT\=normal
[        ]     export DART_DEFINES\=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ\=\=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl
[        ]     export DART_OBFUSCATION\=false
[        ]     export DEAD_CODE_STRIPPING\=NO
[        ]     export DEBUGGING_SYMBOLS\=YES
[   +2 ms]     export DEBUG_INFORMATION_FORMAT\=dwarf
[        ]     export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
[        ]     export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
[        ]     export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
[        ]     export DEFINES_MODULE\=NO
[        ]     export DEPLOYMENT_LOCATION\=NO
[        ]     export DEPLOYMENT_POSTPROCESSING\=NO
[        ]     export DEPLOYMENT_TARGET_CLANG_ENV_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_CLANG_FLAG_NAME\=mmacosx-version-min
[        ]     export DEPLOYMENT_TARGET_LD_ENV_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_LD_FLAG_NAME\=macosx_version_min
[        ]     export DEPLOYMENT_TARGET_SETTING_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_SUGGESTED_VALUES\=10.9\ 10.10\ 10.11\ 10.12\ 10.13\ 10.14\ 10.15\ 11.0\ 11.1\ 11.2\ 11.3
[        ]     export
DERIVED_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/DerivedSources
[        ]     export
DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/DerivedSources
[        ]     export
DERIVED_SOURCES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/DerivedSources
[   +2 ms]     export DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
[        ]     export DEVELOPER_FRAMEWORKS_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_FRAMEWORKS_DIR_QUOTED\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[   +3 ms]     export DEVELOPMENT_LANGUAGE\=en
[        ]     export DONT_GENERATE_INFOPLIST_FILE\=NO
[        ]     export DO_HEADER_SCANNING_IN_JAM\=NO
[        ]     export DSTROOT\=/tmp/Runner.dst
[        ]     export DT_TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export DWARF_DSYM_FILE_NAME\=.dSYM
[        ]     export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
[        ]     export DWARF_DSYM_FOLDER_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export EMBEDDED_CONTENT_CONTAINS_SWIFT\=NO
[        ]     export EMBEDDED_PROFILE_NAME\=embedded.provisionprofile
[        ]     export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE\=NO
[        ]     export ENABLE_BITCODE\=NO
[        ]     export ENABLE_DEFAULT_HEADER_SEARCH_PATHS\=YES
[        ]     export ENABLE_HARDENED_RUNTIME\=NO
[        ]     export ENABLE_HEADER_DEPENDENCIES\=YES
[        ]     export ENABLE_ON_DEMAND_RESOURCES\=NO
[        ]     export ENABLE_PREVIEWS\=NO
[   +2 ms]     export ENABLE_STRICT_OBJC_MSGSEND\=YES
[        ]     export ENABLE_TESTABILITY\=YES
[        ]     export ENABLE_TESTING_SEARCH_PATHS\=NO
[        ]     export ENTITLEMENTS_DESTINATION\=Signature
[        ]     export EXCLUDED_ARCHS\=arm64
[  +26 ms]     export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS\=.DS_Store\ .svn\ .git\ .hg\ CVS
[  +10 ms]     export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES\=\*.nib\ \*.lproj\ \*.framework\ \*.gch\ \*.xcode\*\ \*.xcassets\ \(\*\)\ .DS_Store\
CVS\ .svn\ .git\ .hg\ \*.pbproj\ \*.pbxproj
[   +6 ms]     export FILE_LIST\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects/LinkFileList
[   +1 ms]     export
FIXED_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/FixedFiles
[        ]     export FLUTTER_APPLICATION_PATH\=/Users/gabriel/Desktop/integration_test_native_crash
[        ]     export FLUTTER_BUILD_DIR\=build
[        ]     export FLUTTER_BUILD_NAME\=1.0.0
[        ]     export FLUTTER_BUILD_NUMBER\=1
[        ]     export FLUTTER_ROOT\=/Users/gabriel/lib/flutter
[        ]     export FLUTTER_TARGET\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/T/flutter_tools.OUYgiL/flutter_test_listener.b6bC2M/listener.dart
[        ]     export FRAMEWORK_VERSION\=A
[        ]     export GCC3_VERSION\=3.3
[        ]     export GCC_C_LANGUAGE_STANDARD\=gnu11
[        ]     export GCC_DYNAMIC_NO_PIC\=NO
[        ]     export GCC_NO_COMMON_BLOCKS\=YES
[        ]     export GCC_OPTIMIZATION_LEVEL\=0
[        ]     export GCC_PFE_FILE_C_DIALECTS\=c\ objective-c\ c++\ objective-c++
[        ]     export GCC_PREPROCESSOR_DEFINITIONS\=DEBUG\=1\ \ COCOAPODS\=1
[        ]     export GCC_TREAT_WARNINGS_AS_ERRORS\=NO
[        ]     export GCC_VERSION\=com.apple.compilers.llvm.clang.1_0
[   +1 ms]     export GCC_VERSION_IDENTIFIER\=com_apple_compilers_llvm_clang_1_0
[        ]     export GCC_WARN_64_TO_32_BIT_CONVERSION\=YES
[        ]     export GCC_WARN_ABOUT_RETURN_TYPE\=YES_ERROR
[        ]     export GCC_WARN_SHADOW\=YES
[        ]     export GCC_WARN_STRICT_SELECTOR_MATCH\=YES
[        ]     export GCC_WARN_UNDECLARED_SELECTOR\=YES
[        ]     export GCC_WARN_UNINITIALIZED_AUTOS\=YES_AGGRESSIVE
[        ]     export GCC_WARN_UNUSED_FUNCTION\=YES
[        ]     export GCC_WARN_UNUSED_VARIABLE\=YES
[        ]     export
GENERATED_MODULEMAP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/GeneratedModuleMaps
[        ]     export GENERATE_MASTER_OBJECT_FILE\=NO
[        ]     export GENERATE_PKGINFO_FILE\=NO
[        ]     export GENERATE_PROFILING_CODE\=NO
[        ]     export GENERATE_TEXT_BASED_STUBS\=NO
[        ]     export GID\=20
[        ]     export GROUP\=staff
[        ]     export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT\=YES
[        ]     export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES\=YES
[        ]     export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS\=YES
[        ]     export HEADERMAP_INCLUDES_PROJECT_HEADERS\=YES
[        ]     export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES\=YES
[        ]     export HEADERMAP_USES_VFS\=NO
[        ]     export HIDE_BITCODE_SYMBOLS\=YES
[        ]     export HOME\=/Users/gabriel
[        ]     export ICONV\=/usr/bin/iconv
[        ]     export INFOPLIST_EXPAND_BUILD_SETTINGS\=YES
[        ]     export INFOPLIST_OUTPUT_FORMAT\=same-as-input
[        ]     export INFOPLIST_PREPROCESS\=NO
[        ]     export INLINE_PRIVATE_FRAMEWORKS\=NO
[        ]     export INSTALLHDRS_COPY_PHASE\=NO
[        ]     export INSTALLHDRS_SCRIPT_PHASE\=NO
[        ]     export INSTALL_DIR\=/tmp/Runner.dst
[        ]     export INSTALL_GROUP\=staff
[        ]     export INSTALL_MODE_FLAG\=u+w,go-w,a+rX
[        ]     export INSTALL_OWNER\=gabriel
[        ]     export INSTALL_ROOT\=/tmp/Runner.dst
[        ]     export IOS_UNZIPPERED_TWIN_PREFIX_PATH\=/System/iOSSupport
[        ]     export IS_MACCATALYST\=NO
[        ]     export IS_UIKITFORMAC\=NO
[        ]     export JAVAC_DEFAULT_FLAGS\=-J-Xms64m\ -J-XX:NewSize\=4M\ -J-Dfile.encoding\=UTF8
[        ]     export JAVA_APP_STUB\=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
[        ]     export JAVA_ARCHIVE_CLASSES\=YES
[        ]     export JAVA_ARCHIVE_TYPE\=JAR
[        ]     export JAVA_COMPILER\=/usr/bin/javac
[        ]     export JAVA_FRAMEWORK_RESOURCES_DIRS\=Resources
[        ]     export JAVA_JAR_FLAGS\=cv
[        ]     export JAVA_SOURCE_SUBDIR\=.
[        ]     export JAVA_USE_DEPENDENCIES\=YES
[        ]     export JAVA_ZIP_FLAGS\=-urg
[        ]     export JIKES_DEFAULT_FLAGS\=+E\ +OLDCSO
[        ]     export KASAN_DEFAULT_CFLAGS\=-DKASAN\=1\ -fsanitize\=address\ -mllvm\ -asan-globals-live-support\ -mllvm\ -asan-force-dynamic-shadow
[        ]     export KEEP_PRIVATE_EXTERNS\=NO
[        ]     export
LD_DEPENDENCY_INFO_FILE\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects-normal/undefined_arch/Flutter\ Assemble_dependency_info.dat
[        ]     export LD_GENERATE_MAP_FILE\=NO
[        ]     export
LD_MAP_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Flutter\ Assemble-LinkMap-normal-undefined_arch.txt
[        ]     export LD_NO_PIE\=NO
[        ]     export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER\=YES
[        ]     export LD_RUNPATH_SEARCH_PATHS\=\ \'@executable_path/../Frameworks\'\ \'@loader_path/Frameworks\'
[        ]     export LEGACY_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
[        ]     export LEX\=lex
[        ]     export LIBRARY_DEXT_INSTALL_PATH\=/Library/DriverExtensions
[        ]     export LIBRARY_FLAG_NOSPACE\=YES
[        ]     export LIBRARY_KEXT_INSTALL_PATH\=/Library/Extensions
[        ]     export LINKER_DISPLAYS_MANGLED_NAMES\=NO
[        ]     export
LINK_FILE_LIST_normal_x86_64\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects-normal/x86_64/Flutter\ Assemble.LinkFileList
[        ]     export LINK_WITH_STANDARD_LIBRARIES\=YES
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION\=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_NO\=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_YES\=macos11.3
[        ]     export LLVM_TARGET_TRIPLE_VENDOR\=apple
[        ]     export LOCALIZATION_EXPORT_SUPPORTED\=YES
[        ]     export LOCALIZED_STRING_MACRO_NAMES\=NSLocalizedString\ CFCopyLocalizedString
[        ]     export LOCALIZED_STRING_SWIFTUI_SUPPORT\=YES
[        ]     export LOCAL_ADMIN_APPS_DIR\=/Applications/Utilities
[        ]     export LOCAL_APPS_DIR\=/Applications
[        ]     export LOCAL_DEVELOPER_DIR\=/Library/Developer
[        ]     export LOCAL_LIBRARY_DIR\=/Library
[        ]     export LOCROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[   +1 ms]     export LOCSYMROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export MACOSX_DEPLOYMENT_TARGET\=10.11
[        ]     export MAC_OS_X_PRODUCT_BUILD_VERSION\=20G95
[        ]     export MAC_OS_X_VERSION_ACTUAL\=110502
[        ]     export MAC_OS_X_VERSION_MAJOR\=110000
[        ]     export MAC_OS_X_VERSION_MINOR\=110500
[        ]     export METAL_LIBRARY_FILE_BASE\=default
[        ]     export METAL_LIBRARY_OUTPUT_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/
[        ]     export MODULE_CACHE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex
[        ]     export MTL_ENABLE_DEBUG_INFO\=YES
[        ]     export NATIVE_ARCH\=x86_64
[        ]     export NATIVE_ARCH_32_BIT\=i386
[        ]     export NATIVE_ARCH_64_BIT\=x86_64
[        ]     export NATIVE_ARCH_ACTUAL\=x86_64
[        ]     export NO_COMMON\=YES
[   +4 ms]     export
OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects
[        ]     export
OBJECT_FILE_DIR_normal\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects-normal
[   +1 ms]     export OBJROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export ONLY_ACTIVE_ARCH\=YES
[        ]     export OS\=MACOS
[        ]     export OSAC\=/usr/bin/osacompile
[        ]     export PACKAGE_CONFIG\=/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/package_config.json
[        ]     export PASCAL_STRINGS\=YES
[        ]     export
PATH\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefa
ult.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/De
veloper/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Content
s/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applic
ations/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/gabriel/.rbenv/shims:/Users/gabriel/google-cloud
-sdk/bin:/Users/gabriel/.nvm/versions/node/v12.18.4/bin:/Users/gabriel/Library/Android/sdk/tools/bin:/Users/gabriel/.pub-cache/bin:/Users/gabriel/lib/flutte
r/bin/cache/dart-sdk/bin:/Users/gabriel/lib/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Library
/Frameworks/Mono.framework/Versions/Current/Commands:/Users/gabriel/.cargo/bin
[   +4 ms]     export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES\=/usr/include\ /usr/local/include\ /System/Library/Frameworks\
/System/Library/PrivateFrameworks\ /Applications/Xcode.app/Contents/Developer/Headers\ /Applications/Xcode.app/Contents/Developer/SDKs\
/Applications/Xcode.app/Contents/Developer/Platforms
[        ]     export
PER_ARCH_OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects-normal/undefined_arch
[        ]     export
PER_VARIANT_OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/Objects-normal
[        ]     export
PKGINFO_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/PkgInfo
[        ]     export PLATFORM_DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export PLATFORM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export PLATFORM_DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export PLATFORM_DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export PLATFORM_DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export PLATFORM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
[        ]     export PLATFORM_DISPLAY_NAME\=macOS
[        ]     export PLATFORM_FAMILY_NAME\=macOS
[        ]     export PLATFORM_NAME\=macosx
[        ]     export PLATFORM_PREFERRED_ARCH\=x86_64
[        ]     export PLATFORM_PRODUCT_BUILD_VERSION\=12E507
[        ]     export PLIST_FILE_OUTPUT_FORMAT\=same-as-input
[        ]     export PODS_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export PODS_CONFIGURATION_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export PODS_PODFILE_DIR_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/macos/.
[        ]     export PODS_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Pods
[        ]     export
PODS_XCFRAMEWORKS_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/XCFrameworkIntermediates
[        ]     export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
[        ]     export
PRECOMP_DESTINATION_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/PrefixHeaders
[   +1 ms]     export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
[        ]     export PRODUCT_MODULE_NAME\=Flutter_Assemble
[        ]     export PRODUCT_NAME\=Flutter\ Assemble
[        ]     export PRODUCT_SETTINGS_PATH\=
[        ]     export PROFILING_CODE\=NO
[        ]     export PROJECT\=Runner
[        ]     export
PROJECT_DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/DerivedSources
[        ]     export PROJECT_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export PROJECT_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner.xcodeproj
[        ]     export PROJECT_NAME\=Runner
[        ]     export PROJECT_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build
[        ]     export PROJECT_TEMP_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS\=YES
[        ]     export REMOVE_CVS_FROM_RESOURCES\=YES
[        ]     export REMOVE_GIT_FROM_RESOURCES\=YES
[        ]     export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
[        ]     export REMOVE_HG_FROM_RESOURCES\=YES
[        ]     export REMOVE_SVN_FROM_RESOURCES\=YES
[        ]     export
REZ_COLLECTOR_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/ResourceManagerResources
[        ]     export
REZ_OBJECTS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/ResourceManagerResources/Objects
[        ]     export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
[        ]     export SCRIPT_INPUT_FILE_0\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Flutter/ephemeral/tripwire
[        ]     export SCRIPT_INPUT_FILE_COUNT\=1
[        ]     export
SCRIPT_INPUT_FILE_LIST_0\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/InputFileList-33CC111E2044C6BF0003C045-FlutterInputs-1136f8cdea46e94bbc64fc727eb739f1-resolved.xcfilelist
[        ]     export SCRIPT_INPUT_FILE_LIST_COUNT\=1
[        ]     export SCRIPT_OUTPUT_FILE_COUNT\=0
[        ]     export
SCRIPT_OUTPUT_FILE_LIST_0\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build/OutputFileList-33CC111E2044C6BF0003C045-FlutterOutputs-4dd0b4f448eac9e4163753a53e22f565-resolved.xcfilelist
[   +1 ms]     export SCRIPT_OUTPUT_FILE_LIST_COUNT\=1
[        ]     export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR_macosx\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR_macosx11_3\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_NAME\=macosx11.3
[        ]     export SDK_NAMES\=macosx11.3
[        ]     export SDK_PRODUCT_BUILD_VERSION\=20E214
[        ]     export SDK_VERSION\=11.3
[        ]     export SDK_VERSION_ACTUAL\=110300
[        ]     export SDK_VERSION_MAJOR\=110000
[        ]     export SDK_VERSION_MINOR\=110300
[        ]     export SED\=/usr/bin/sed
[        ]     export SEPARATE_STRIP\=NO
[        ]     export SEPARATE_SYMBOL_EDIT\=NO
[        ]     export SET_DIR_MODE_OWNER_GROUP\=YES
[        ]     export SET_FILE_MODE_OWNER_GROUP\=NO
[        ]     export SHALLOW_BUNDLE\=NO
[        ]     export SHARED_DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/DerivedSources
[        ]     export SHARED_PRECOMPS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/PrecompiledHeaders
[        ]     export SKIP_INSTALL\=YES
[        ]     export SOURCE_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export SRCROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export STRINGS_FILE_INFOPLIST_RENAME\=YES
[        ]     export STRINGS_FILE_OUTPUT_ENCODING\=UTF-16
[        ]     export STRIP_BITCODE_FROM_COPIED_FILES\=NO
[        ]     export STRIP_INSTALLED_PRODUCT\=YES
[        ]     export STRIP_PNG_TEXT\=NO
[        ]     export STRIP_STYLE\=all
[        ]     export STRIP_SWIFT_SYMBOLS\=YES
[        ]     export SUPPORTED_PLATFORMS\=macosx
[        ]     export SUPPORTS_TEXT_BASED_API\=NO
[        ]     export SWIFT_ACTIVE_COMPILATION_CONDITIONS\=DEBUG
[        ]     export SWIFT_OPTIMIZATION_LEVEL\=-Onone
[        ]     export SWIFT_PLATFORM_TARGET_PREFIX\=macos
[        ]     export
SWIFT_RESPONSE_FILE_PATH_normal_x86_64\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flut
ter\ Assemble.build/Objects-normal/x86_64/Flutter\ Assemble.SwiftFileList
[        ]     export SYMROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
[        ]     export SYSTEM_APPS_DIR\=/Applications
[        ]     export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
[        ]     export SYSTEM_DEMOS_DIR\=/Applications/Extras
[        ]     export SYSTEM_DEVELOPER_APPS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export SYSTEM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[   +1 ms]     export SYSTEM_DEVELOPER_DEMOS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
[        ]     export SYSTEM_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
[        ]     export SYSTEM_DEVELOPER_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library
[        ]     export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
[        ]     export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Java\ Tools
[        ]     export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Performance\ Tools
[        ]     export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
[        ]     export SYSTEM_DEVELOPER_TOOLS\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
[        ]     export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\
Library/releasenotes/DeveloperTools
[   +2 ms]     export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
[        ]     export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
[        ]     export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
[        ]     export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
[        ]     export SYSTEM_LIBRARY_DIR\=/System/Library
[        ]     export TAPI_VERIFY_MODE\=ErrorsOnly
[        ]     export TARGETNAME\=Flutter\ Assemble
[        ]     export TARGET_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export TARGET_NAME\=Flutter\ Assemble
[        ]     export
TARGET_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build
[        ]     export TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\
Assemble.build
[        ]     export
TEMP_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build
[        ]     export
TEMP_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\ Assemble.build
[        ]     export TEMP_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export TEST_FRAMEWORK_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
[        ]     export TEST_LIBRARY_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
[        ]     export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
[        ]     export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export TRACK_WIDGET_CREATION\=true
[   +1 ms]     export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
[        ]     export TREE_SHAKE_ICONS\=false
[        ]     export UID\=501
[        ]     export UNSTRIPPED_PRODUCT\=NO
[        ]     export USER\=gabriel
[        ]     export USER_APPS_DIR\=/Users/gabriel/Applications
[        ]     export USER_LIBRARY_DIR\=/Users/gabriel/Library
[        ]     export USE_DYNAMIC_NO_PIC\=YES
[        ]     export USE_HEADERMAP\=YES
[        ]     export USE_HEADER_SYMLINKS\=NO
[        ]     export USE_LLVM_TARGET_TRIPLES\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
[        ]     export USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES\=YES
[        ]     export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
[        ]     export VALIDATE_PRODUCT\=NO
[        ]     export VALIDATE_WORKSPACE\=YES_ERROR
[        ]     export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
[        ]     export VERBOSE_PBXCP\=NO
[        ]     export VERBOSE_SCRIPT_LOGGING\=YES
[        ]     export VERSION_INFO_BUILDER\=gabriel
[        ]     export VERSION_INFO_FILE\=Flutter\ Assemble_vers.c
[        ]     export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:Flutter\ Assemble\ \ PROJECT:Runner-\"
[        ]     export WARNING_CFLAGS\=-Wall\ -Wconditional-uninitialized\ -Wnullable-to-nonnull-conversion\ -Wmissing-method-return-type\
-Woverlength-strings
[        ]     export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
[   +1 ms]     export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
[        ]     export XCODE_PRODUCT_BUILD_VERSION\=12E507
[        ]     export XCODE_VERSION_ACTUAL\=1251
[        ]     export XCODE_VERSION_MAJOR\=1200
[        ]     export XCODE_VERSION_MINOR\=1250
[        ]     export XPCSERVICES_FOLDER_PATH\=/XPCServices
[        ]     export YACC\=yacc
[        ]     export _BOOL_\=NO
[        ]     export _BOOL_NO\=NO
[        ]     export _BOOL_YES\=YES
[        ]     export _DEVELOPMENT_TEAM_IS_EMPTY\=YES
[        ]     export _IS_EMPTY_\=YES
[        ]     export _MACOSX_DEPLOYMENT_TARGET_IS_EMPTY\=NO
[        ]     export arch\=undefined_arch
[        ]     export variant\=normal
[        ]     /bin/sh -c /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Flutter\\\
Assemble.build/Script-33CC111E2044C6BF0003C045.sh
[  +13 ms] ♦ /Users/gabriel/lib/flutter/bin/flutter --verbose assemble --no-version-check -dTargetPlatform=darwin -dDarwinArchs=x86_64
-dTargetFile=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/T/flutter_tools.OUYgiL/flutter_test_listener.b6bC2M/listener.dart -dBuildMode=debug
-dTreeShakeIcons=false -dDartObfuscation=false -dSplitDebugInfo= -dTrackWidgetCreation=true
--DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl --ExtraGenSnapshotOptions=
--ExtraFrontEndOptions= --build-inputs=/Users/gabriel/Desktop/integration_test_native_crash/macos/Flutter/ephemeral/FlutterInputs.xcfilelist
--build-outputs=/Users/gabriel/Desktop/integration_test_native_crash/macos/Flutter/ephemeral/FlutterOutputs.xcfilelist
--output=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug debug_macos_bundle_flutter_assets
00:09 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +430 ms] [ +100 ms] executing: sysctl hw.optional.arm64
[   +8 ms] [  +22 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +4 ms] [        ] sysctl: unknown oid 'hw.optional.arm64'
[  +12 ms] [  +16 ms] executing: [/Users/gabriel/lib/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] [  +13 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[   +2 ms] [   +1 ms] executing: [/Users/gabriel/lib/flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +43 ms] [  +46 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [        ] 2.5.0
[  +11 ms] [  +12 ms] executing: [/Users/gabriel/lib/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] [  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/gabriel/lib/flutter/] git ls-remote --get-url origin
[  +13 ms] [  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[  +83 ms] [  +84 ms] executing: [/Users/gabriel/lib/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[   +8 ms] [  +10 ms] executing: sw_vers -productName
[  +26 ms] [  +23 ms] Exit code 0 from: sw_vers -productName
[   +4 ms] [   +1 ms] macOS
[        ] [        ] executing: sw_vers -productVersion
[  +17 ms] [  +21 ms] Exit code 0 from: sw_vers -productVersion
[        ] [   +1 ms] 11.5.2
[        ] [        ] executing: sw_vers -buildVersion
[  +18 ms] [  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] [        ] 20G95
[  +59 ms] [  +59 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +99 ms] [ +107 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +6 ms] [   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +55 ms] [  +61 ms] Initializing file store
[  +33 ms] [  +33 ms] Skipping target: gen_localizations
[  +20 ms] [  +20 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/package_config_subset}
[   +7 ms] [   +6 ms] debug_macos_framework: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/gabriel/lib/flutter/packages/flutter_tools/lib/src/build_system/targets/macos.dart}
[  +12 ms] [  +11 ms] executing: sysctl hw.optional.arm64
[  +12 ms] [  +13 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] [        ] sysctl: unknown oid 'hw.optional.arm64'
[   +4 ms] [   +2 ms] executing: xcrun clang -x c
/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/flutter_build/c3e098c2973cda6ce7418ad257289c88/debug_app.cc -arch x86_64 -dynamiclib
-Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -o
/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/flutter_build/c3e098c2973cda6ce7418ad257289c88/App.framework/App
[  +10 ms] [  +12 ms] debug_unpack_macos: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/gabriel/lib/flutter/packages/flutter_tools/lib/src/build_system/targets/macos.dart,/Users/gabriel/lib/flutter/bin/internal/engine.version}
[  +47 ms] [  +46 ms] Skipping lipo for non-fat file
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/FlutterMacOS.framework/FlutterMacOS
[  +19 ms] [  +19 ms] debug_unpack_macos: Complete
00:10 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +354 ms] [ +354 ms] Found plugin integration_test at /Users/gabriel/lib/flutter/packages/integration_test/
[  +15 ms] [  +14 ms] gen_dart_plugin_registrant: Complete
[   +3 ms] [   +2 ms] kernel_snapshot: Starting due to {}
[  +11 ms] [  +13 ms] /Users/gabriel/lib/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/gabriel/lib/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/gabriel/lib/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -DINTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --packages /Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/package_config.json --output-dill
/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/flutter_build/c3e098c2973cda6ce7418ad257289c88/app.dill --depfile
/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/flutter_build/c3e098c2973cda6ce7418ad257289c88/kernel_snapshot.d
file:///var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/T/flutter_tools.OUYgiL/flutter_test_listener.b6bC2M/listener.dart
[ +197 ms] [ +164 ms] debug_macos_framework: Complete
00:20 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [+10216 ms] [+10249 ms] kernel_snapshot: Complete
00:21 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +859 ms] [ +858 ms] debug_macos_bundle_flutter_assets: Starting due to {}
[ +211 ms] [ +212 ms] debug_macos_bundle_flutter_assets: Complete
00:22 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +574 ms] [ +574 ms] Persisting file store
[  +12 ms] [  +11 ms] Done persisting file store
[  +11 ms] [  +12 ms] build succeeded.
[  +22 ms] [  +22 ms] "flutter assemble" took 12,854ms.
[  +99 ms] [  +99 ms] ensureAnalyticsSent: 86ms
[   +2 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[   +6 ms] [        ] exiting with code 0
[  +36 ms] ProcessProductPackaging ""
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash.a
pp.xcent (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     Entitlements:
[        ]     {
[        ]     "com.apple.security.app-sandbox" = 1;
[        ]     "com.apple.security.cs.allow-jit" = 1;
[        ]     "com.apple.security.get-task-allow" = 1;
[        ]     "com.apple.security.network.server" = 1;
[        ] }
[        ]     builtin-productPackagingUtility -entitlements -format xml -o
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash.a
pp.xcent
[  +17 ms] ProcessInfoPlistFile
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/Pods_Runner.framework/Versions/A/Resources/Info.plist
/Users/gabriel/Desktop/integration_test_native_crash/macos/Pods/Target\ Support\ Files/Pods-Runner/Pods-Runner-Info.plist (in target 'Pods-Runner' from
project 'Pods')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos/Pods
[        ]     builtin-infoPlistUtility /Users/gabriel/Desktop/integration_test_native_crash/macos/Pods/Target\ Support\
Files/Pods-Runner/Pods-Runner-Info.plist -producttype com.apple.product-type.framework -expandbuildsettings -platform macosx -o
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/Pods_Runner.framework/Versions/A/Resources/Info.plist
[  +13 ms] PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-1C58C8FEBE1FBAF2F64F1CE8
.sh (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     /bin/sh -c
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-1C58C8FEBE1FBAF2F64F1CE8
.sh
[  +32 ms] CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
[        ]     export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name
integration_test_native_crash -Onone -enable-batch-mode -enforce-exclusivity\=checked
@/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrat
ion_test_native_crash.SwiftFileList -DDEBUG -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -target
x86_64-apple-macos10.11 -g -module-cache-path /Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex -Xfrontend
-serialize-debugging-options -enable-testing -swift-version 5 -I /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -F
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -c -j4 -output-file-map
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Runner-Ou
tputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash.swiftmodule -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap -Xcc
-iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-g
enerated-files.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-own-target-headers.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/all-product-headers.yaml -Xcc
-iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-p
roject-headers.hmap -Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/include -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc
-DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -emit-objc-header -emit-objc-header-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash-Swift.h -working-directory /Users/gabriel/Desktop/integration_test_native_crash/macos
[  +65 ms] CompileSwift normal x86_64 /Users/gabriel/Desktop/integration_test_native_crash/macos/Flutter/GeneratedPluginRegistrant.swift (in target 'Runner'
from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c
/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner/MainFlutterWindow.swift
/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner/AppDelegate.swift -primary-file
/Users/gabriel/Desktop/integration_test_native_crash/macos/Flutter/GeneratedPluginRegistrant.swift -emit-module-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant\~partial.swiftmodule -emit-module-doc-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant\~partial.swiftdoc -emit-module-source-info-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant\~partial.swiftsourceinfo -serialize-diagnostics-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant.dia -emit-dependencies-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant.d -emit-reference-dependencies-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant.swiftdeps -target x86_64-apple-macos10.11 -enable-objc-interop -sdk
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -I
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -F
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -enable-testing -g -module-cache-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG
-serialize-debugging-options -Xcc -working-directory -Xcc /Users/gabriel/Desktop/integration_test_native_crash/macos -enable-anonymous-context-mangled-names
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap
-Xcc -iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-g
enerated-files.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-own-target-headers.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/all-product-headers.yaml -Xcc
-iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-p
roject-headers.hmap -Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/include -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc
-DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -target-sdk-version 11.3 -module-name integration_test_native_crash -o
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant.o
00:23 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +671 ms] MergeSwiftModule normal x86_64 (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -merge-modules -emit-module
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/MainFlutt
erWindow\~partial.swiftmodule
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/AppDelega
te\~partial.swiftmodule
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/Generated
PluginRegistrant\~partial.swiftmodule -parse-as-library -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-apple-macos10.11
-enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -I
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -F
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug -enable-testing -g -module-cache-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG
-serialize-debugging-options -Xcc -working-directory -Xcc /Users/gabriel/Desktop/integration_test_native_crash/macos -enable-anonymous-context-mangled-names
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/swift-overrides.hmap
-Xcc -iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-g
enerated-files.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-own-target-headers.hmap -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash
-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/all-product-headers.yaml -Xcc
-iquote -Xcc
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash-p
roject-headers.hmap -Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/include -Xcc
-I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources-normal/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources/x86_64
-Xcc -I/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSources -Xcc
-DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -target-sdk-version 11.3 -emit-module-doc-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash.swiftdoc -emit-module-source-info-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash.swiftsourceinfo -emit-objc-header-path
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash-Swift.h -module-name integration_test_native_crash -o
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/integrati
on_test_native_crash.swiftmodule
[ +241 ms] ProcessInfoPlistFile
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Info.plist
/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner/Info.plist (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     builtin-infoPlistUtility /Users/gabriel/Desktop/integration_test_native_crash/macos/Runner/Info.plist -producttype
com.apple.product-type.application -genpkginfo
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/PkgInfo
-expandbuildsettings -platform macosx -additionalcontentfile
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Base.lproj/MainMenu-PartialInfo
.plist -additionalcontentfile
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/assetcatalog_generated_info.pli
st -o /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Info.plist
[  +17 ms] PhaseScriptExecution Run\ Script
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-3399D490228B24CF009A79C7
.sh (in target 'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export ACTION\=build
[        ]     export AD_HOC_CODE_SIGNING_ALLOWED\=YES
[        ]     export ALTERNATE_GROUP\=staff
[        ]     export ALTERNATE_MODE\=u+w,go-w,a+rX
[        ]     export ALTERNATE_OWNER\=gabriel
[        ]     export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
[        ]     export ALWAYS_SEARCH_USER_PATHS\=NO
[        ]     export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
[        ]     export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
[        ]     export APPLE_INTERNAL_DIR\=/AppleInternal
[        ]     export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
[        ]     export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
[        ]     export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
[        ]     export APPLICATION_EXTENSION_API_ONLY\=NO
[        ]     export APPLY_RULES_IN_COPY_FILES\=NO
[        ]     export APPLY_RULES_IN_COPY_HEADERS\=NO
[   +1 ms]     export ARCHS\=x86_64
[        ]     export ARCHS_STANDARD\=arm64\ x86_64
[        ]     export ARCHS_STANDARD_32_64_BIT\=arm64\ x86_64\ i386
[        ]     export ARCHS_STANDARD_32_BIT\=i386
[        ]     export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
[        ]     export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64
[        ]     export ASSETCATALOG_COMPILER_APPICON_NAME\=AppIcon
[        ]     export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
[        ]     export BITCODE_GENERATION_MODE\=marker
[        ]     export BUILD_ACTIVE_RESOURCES_ONLY\=NO
[        ]     export BUILD_COMPONENTS\=headers\ build
[        ]     export BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
[        ]     export BUILD_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export BUILD_STYLE\=
[        ]     export BUILD_VARIANTS\=normal
[        ]     export BUILT_PRODUCTS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[   +1 ms]     export BUNDLE_CONTENTS_FOLDER_PATH\=Contents/
[        ]     export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
[        ]     export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
[        ]     export BUNDLE_EXECUTABLE_FOLDER_PATH\=Contents/MacOS
[        ]     export BUNDLE_FORMAT\=deep
[        ]     export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Contents/Frameworks
[        ]     export BUNDLE_PLUGINS_FOLDER_PATH\=Contents/PlugIns
[        ]     export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=Contents/PrivateHeaders
[        ]     export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Contents/Headers
[        ]     export CACHE_ROOT\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/C/com.apple.DeveloperTools/12.5.1-12E507/Xcode
[        ]     export CCHROOT\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/C/com.apple.DeveloperTools/12.5.1-12E507/Xcode
[        ]     export CHMOD\=/bin/chmod
[        ]     export CHOWN\=/usr/sbin/chown
[        ]     export CLANG_ANALYZER_NONNULL\=YES
[        ]     export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION\=YES_AGGRESSIVE
[        ]     export CLANG_CXX_LANGUAGE_STANDARD\=gnu++14
[        ]     export CLANG_CXX_LIBRARY\=libc++
[        ]     export CLANG_ENABLE_MODULES\=YES
[        ]     export CLANG_ENABLE_OBJC_ARC\=YES
[        ]     export
CLANG_MODULES_BUILD_SESSION_FILE\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex/Session.modulevalidation
[        ]     export CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY\=YES
[        ]     export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING\=YES
[        ]     export CLANG_WARN_BOOL_CONVERSION\=YES
[        ]     export CLANG_WARN_COMMA\=YES
[        ]     export CLANG_WARN_CONSTANT_CONVERSION\=YES
[        ]     export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS\=YES
[        ]     export CLANG_WARN_DIRECT_OBJC_ISA_USAGE\=YES_ERROR
[        ]     export CLANG_WARN_DOCUMENTATION_COMMENTS\=YES
[        ]     export CLANG_WARN_EMPTY_BODY\=YES
[        ]     export CLANG_WARN_ENUM_CONVERSION\=YES
[        ]     export CLANG_WARN_INFINITE_RECURSION\=YES
[        ]     export CLANG_WARN_INT_CONVERSION\=YES
[        ]     export CLANG_WARN_NON_LITERAL_NULL_CONVERSION\=YES
[        ]     export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF\=YES
[        ]     export CLANG_WARN_OBJC_LITERAL_CONVERSION\=YES
[   +6 ms]     export CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK\=YES
[        ]     export CLANG_WARN_OBJC_ROOT_CLASS\=YES_ERROR
[        ]     export CLANG_WARN_PRAGMA_PACK\=YES
[        ]     export CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER\=NO
[        ]     export CLANG_WARN_RANGE_LOOP_ANALYSIS\=YES
[        ]     export CLANG_WARN_STRICT_PROTOTYPES\=YES
[        ]     export CLANG_WARN_SUSPICIOUS_MOVE\=YES
[        ]     export CLANG_WARN_UNGUARDED_AVAILABILITY\=YES_AGGRESSIVE
[        ]     export CLANG_WARN_UNREACHABLE_CODE\=YES
[        ]     export CLANG_WARN__DUPLICATE_METHOD_MATCH\=YES
[        ]     export
CLASS_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/JavaClasses
[        ]     export CLEAN_PRECOMPS\=YES
[        ]     export CLONE_HEADERS\=NO
[        ]     export COCOAPODS_PARALLEL_CODE_SIGN\=true
[        ]     export
CODESIGNING_FOLDER_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app
[        ]     export CODE_SIGNING_ALLOWED\=YES
[        ]     export CODE_SIGN_ENTITLEMENTS\=Runner/DebugProfile.entitlements
[        ]     export CODE_SIGN_IDENTITY\=-
[        ]     export CODE_SIGN_IDENTITY_NO\=Apple\ Development
[        ]     export CODE_SIGN_IDENTITY_YES\=-
[        ]     export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
[        ]     export CODE_SIGN_STYLE\=Automatic
[        ]     export COLOR_DIAGNOSTICS\=NO
[        ]     export COMBINE_HIDPI_IMAGES\=YES
[        ]     export COMPILER_INDEX_STORE_ENABLE\=NO
[        ]     export COMPOSITE_SDK_DIRS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/CompositeSDKs
[        ]     export COMPRESS_PNG_FILES\=NO
[        ]     export CONFIGURATION\=Debug
[        ]     export CONFIGURATION_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export
CONFIGURATION_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug
[        ]     export CONTENTS_FOLDER_PATH\=integration_test_native_crash.app/Contents
[        ]     export CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_NO\=integration_test_native_crash.app/Contents
[        ]     export CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_YES\=integration_test_native_crash.app
[        ]     export COPYING_PRESERVES_HFS_DATA\=NO
[        ]     export COPY_HEADERS_RUN_UNIFDEF\=NO
[        ]     export COPY_PHASE_STRIP\=NO
[        ]     export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS\=YES
[        ]     export CP\=/bin/cp
[        ]     export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
[        ]     export CURRENT_ARCH\=undefined_arch
[        ]     export CURRENT_VARIANT\=normal
[        ]     export DART_DEFINES\=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ\=\=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl
[        ]     export DART_OBFUSCATION\=false
[        ]     export DEAD_CODE_STRIPPING\=NO
[        ]     export DEBUGGING_SYMBOLS\=YES
[        ]     export DEBUG_INFORMATION_FORMAT\=dwarf
[        ]     export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
[        ]     export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
[        ]     export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
[        ]     export DEFINES_MODULE\=NO
[        ]     export DEPLOYMENT_LOCATION\=NO
[        ]     export DEPLOYMENT_POSTPROCESSING\=NO
[        ]     export DEPLOYMENT_TARGET_CLANG_ENV_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_CLANG_FLAG_NAME\=mmacosx-version-min
[   +3 ms]     export DEPLOYMENT_TARGET_LD_ENV_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_LD_FLAG_NAME\=macosx_version_min
[        ]     export DEPLOYMENT_TARGET_SETTING_NAME\=MACOSX_DEPLOYMENT_TARGET
[        ]     export DEPLOYMENT_TARGET_SUGGESTED_VALUES\=10.9\ 10.10\ 10.11\ 10.12\ 10.13\ 10.14\ 10.15\ 11.0\ 11.1\ 11.2\ 11.3
[        ]     export
DERIVED_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSourc
es
[        ]     export
DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSource
s
[        ]     export
DERIVED_SOURCES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/DerivedSou
rces
[        ]     export DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
[        ]     export DEVELOPER_FRAMEWORKS_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_FRAMEWORKS_DIR_QUOTED\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
[        ]     export DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export DEVELOPMENT_LANGUAGE\=en
[        ]     export DOCUMENTATION_FOLDER_PATH\=integration_test_native_crash.app/Contents/Resources/en.lproj/Documentation
[        ]     export DONT_GENERATE_INFOPLIST_FILE\=NO
[        ]     export DO_HEADER_SCANNING_IN_JAM\=NO
[        ]     export DSTROOT\=/tmp/Runner.dst
[        ]     export DT_TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export DWARF_DSYM_FILE_NAME\=integration_test_native_crash.app.dSYM
[        ]     export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
[        ]     export DWARF_DSYM_FOLDER_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export EMBEDDED_CONTENT_CONTAINS_SWIFT\=NO
[        ]     export EMBEDDED_PROFILE_NAME\=embedded.provisionprofile
[        ]     export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE\=NO
[        ]     export ENABLE_BITCODE\=NO
[        ]     export ENABLE_DEFAULT_HEADER_SEARCH_PATHS\=YES
[        ]     export ENABLE_HARDENED_RUNTIME\=NO
[        ]     export ENABLE_HEADER_DEPENDENCIES\=YES
[        ]     export ENABLE_ON_DEMAND_RESOURCES\=NO
[        ]     export ENABLE_PREVIEWS\=NO
[        ]     export ENABLE_STRICT_OBJC_MSGSEND\=YES
[        ]     export ENABLE_TESTABILITY\=YES
[        ]     export ENABLE_TESTING_SEARCH_PATHS\=NO
[        ]     export ENTITLEMENTS_DESTINATION\=Signature
[        ]     export EXCLUDED_ARCHS\=arm64
[        ]     export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS\=.DS_Store\ .svn\ .git\ .hg\ CVS
[        ]     export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES\=\*.nib\ \*.lproj\ \*.framework\ \*.gch\ \*.xcode\*\ \*.xcassets\ \(\*\)\ .DS_Store\
CVS\ .svn\ .git\ .hg\ \*.pbproj\ \*.pbxproj
[        ]     export EXECUTABLES_FOLDER_PATH\=integration_test_native_crash.app/Contents/Executables
[        ]     export EXECUTABLE_FOLDER_PATH\=integration_test_native_crash.app/Contents/MacOS
[        ]     export EXECUTABLE_FOLDER_PATH_SHALLOW_BUNDLE_NO\=integration_test_native_crash.app/Contents/MacOS
[        ]     export EXECUTABLE_FOLDER_PATH_SHALLOW_BUNDLE_YES\=integration_test_native_crash.app/Contents
[        ]     export EXECUTABLE_NAME\=integration_test_native_crash
[        ]     export EXECUTABLE_PATH\=integration_test_native_crash.app/Contents/MacOS/integration_test_native_crash
[        ]     export EXPANDED_CODE_SIGN_IDENTITY\=-
[        ]     export EXPANDED_CODE_SIGN_IDENTITY_NAME\=-
[        ]     export
FILE_LIST\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects/LinkFileList
[        ]     export
FIXED_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/FixedFiles
[        ]     export FLUTTER_APPLICATION_PATH\=/Users/gabriel/Desktop/integration_test_native_crash
[        ]     export FLUTTER_BUILD_DIR\=build
[        ]     export FLUTTER_BUILD_NAME\=1.0.0
[        ]     export FLUTTER_BUILD_NUMBER\=1
[        ]     export FLUTTER_ROOT\=/Users/gabriel/lib/flutter
[        ]     export FLUTTER_TARGET\=/var/folders/mg/0337nkr97csd2gt4t0j61kb80000gn/T/flutter_tools.OUYgiL/flutter_test_listener.b6bC2M/listener.dart
[        ]     export FRAMEWORKS_FOLDER_PATH\=integration_test_native_crash.app/Contents/Frameworks
[        ]     export FRAMEWORK_FLAG_PREFIX\=-framework
[        ]     export FRAMEWORK_SEARCH_PATHS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug\ 
[        ]     export FRAMEWORK_VERSION\=A
[        ]     export FULL_PRODUCT_NAME\=integration_test_native_crash.app
[        ]     export GCC3_VERSION\=3.3
[        ]     export GCC_C_LANGUAGE_STANDARD\=gnu11
[        ]     export GCC_DYNAMIC_NO_PIC\=NO
[        ]     export GCC_INLINES_ARE_PRIVATE_EXTERN\=YES
[        ]     export GCC_NO_COMMON_BLOCKS\=YES
[        ]     export GCC_OPTIMIZATION_LEVEL\=0
[        ]     export GCC_PFE_FILE_C_DIALECTS\=c\ objective-c\ c++\ objective-c++
[        ]     export GCC_PREPROCESSOR_DEFINITIONS\=DEBUG\=1\ \ COCOAPODS\=1
[        ]     export GCC_SYMBOLS_PRIVATE_EXTERN\=NO
[        ]     export GCC_TREAT_WARNINGS_AS_ERRORS\=NO
[        ]     export GCC_VERSION\=com.apple.compilers.llvm.clang.1_0
[        ]     export GCC_VERSION_IDENTIFIER\=com_apple_compilers_llvm_clang_1_0
[        ]     export GCC_WARN_64_TO_32_BIT_CONVERSION\=YES
[        ]     export GCC_WARN_ABOUT_RETURN_TYPE\=YES_ERROR
[        ]     export GCC_WARN_SHADOW\=YES
[        ]     export GCC_WARN_STRICT_SELECTOR_MATCH\=YES
[        ]     export GCC_WARN_UNDECLARED_SELECTOR\=YES
[        ]     export GCC_WARN_UNINITIALIZED_AUTOS\=YES_AGGRESSIVE
[        ]     export GCC_WARN_UNUSED_FUNCTION\=YES
[        ]     export GCC_WARN_UNUSED_VARIABLE\=YES
[        ]     export
GENERATED_MODULEMAP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/GeneratedModuleMaps
[        ]     export GENERATE_MASTER_OBJECT_FILE\=NO
[        ]     export GENERATE_PKGINFO_FILE\=YES
[        ]     export GENERATE_PROFILING_CODE\=NO
[        ]     export GENERATE_TEXT_BASED_STUBS\=NO
[        ]     export GID\=20
[        ]     export GROUP\=staff
[        ]     export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT\=YES
[        ]     export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES\=YES
[        ]     export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS\=YES
[        ]     export HEADERMAP_INCLUDES_PROJECT_HEADERS\=YES
[        ]     export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES\=YES
[        ]     export HEADERMAP_USES_VFS\=NO
[        ]     export HEADER_SEARCH_PATHS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/include\ 
[        ]     export HIDE_BITCODE_SYMBOLS\=YES
[        ]     export HOME\=/Users/gabriel
[        ]     export ICONV\=/usr/bin/iconv
[        ]     export INFOPLIST_EXPAND_BUILD_SETTINGS\=YES
[        ]     export INFOPLIST_FILE\=Runner/Info.plist
[        ]     export INFOPLIST_OUTPUT_FORMAT\=same-as-input
[        ]     export INFOPLIST_PATH\=integration_test_native_crash.app/Contents/Info.plist
[        ]     export INFOPLIST_PREPROCESS\=NO
[        ]     export INFOSTRINGS_PATH\=integration_test_native_crash.app/Contents/Resources/en.lproj/InfoPlist.strings
[        ]     export INLINE_PRIVATE_FRAMEWORKS\=NO
[        ]     export INSTALLHDRS_COPY_PHASE\=NO
[        ]     export INSTALLHDRS_SCRIPT_PHASE\=NO
[        ]     export INSTALL_DIR\=/tmp/Runner.dst/Applications
[        ]     export INSTALL_GROUP\=staff
[        ]     export INSTALL_MODE_FLAG\=u+w,go-w,a+rX
[        ]     export INSTALL_OWNER\=gabriel
[        ]     export INSTALL_PATH\=/Applications
[        ]     export INSTALL_ROOT\=/tmp/Runner.dst
[        ]     export IOS_UNZIPPERED_TWIN_PREFIX_PATH\=/System/iOSSupport
[        ]     export IS_MACCATALYST\=NO
[        ]     export IS_UIKITFORMAC\=NO
[        ]     export JAVAC_DEFAULT_FLAGS\=-J-Xms64m\ -J-XX:NewSize\=4M\ -J-Dfile.encoding\=UTF8
[        ]     export JAVA_APP_STUB\=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
[        ]     export JAVA_ARCHIVE_CLASSES\=YES
[        ]     export JAVA_ARCHIVE_TYPE\=JAR
[        ]     export JAVA_COMPILER\=/usr/bin/javac
[        ]     export JAVA_FOLDER_PATH\=integration_test_native_crash.app/Contents/Resources/Java
[        ]     export JAVA_FRAMEWORK_RESOURCES_DIRS\=Resources
[        ]     export JAVA_JAR_FLAGS\=cv
[        ]     export JAVA_SOURCE_SUBDIR\=.
[        ]     export JAVA_USE_DEPENDENCIES\=YES
[        ]     export JAVA_ZIP_FLAGS\=-urg
[        ]     export JIKES_DEFAULT_FLAGS\=+E\ +OLDCSO
[        ]     export KASAN_DEFAULT_CFLAGS\=-DKASAN\=1\ -fsanitize\=address\ -mllvm\ -asan-globals-live-support\ -mllvm\ -asan-force-dynamic-shadow
[        ]     export KEEP_PRIVATE_EXTERNS\=NO
[        ]     export
LD_DEPENDENCY_INFO_FILE\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Object
s-normal/undefined_arch/integration_test_native_crash_dependency_info.dat
[        ]     export LD_GENERATE_MAP_FILE\=NO
[        ]     export
LD_MAP_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_t
est_native_crash-LinkMap-normal-undefined_arch.txt
[        ]     export LD_NO_PIE\=NO
[        ]     export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER\=YES
[        ]     export LD_RUNPATH_SEARCH_PATHS\=\ \'@executable_path/../Frameworks\'\ \'@loader_path/Frameworks\'\ @executable_path/../Frameworks
[        ]     export LD_RUNPATH_SEARCH_PATHS_YES\=@loader_path/../Frameworks
[        ]     export LEGACY_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
[        ]     export LEX\=lex
[        ]     export LIBRARY_DEXT_INSTALL_PATH\=/Library/DriverExtensions
[        ]     export LIBRARY_FLAG_NOSPACE\=YES
[        ]     export LIBRARY_FLAG_PREFIX\=-l
[        ]     export LIBRARY_KEXT_INSTALL_PATH\=/Library/Extensions
[   +2 ms]     export LIBRARY_SEARCH_PATHS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug\ 
[   +1 ms]     export LINKER_DISPLAYS_MANGLED_NAMES\=NO
[        ]     export
LINK_FILE_LIST_normal_x86_64\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/O
bjects-normal/x86_64/integration_test_native_crash.LinkFileList
[        ]     export LINK_WITH_STANDARD_LIBRARIES\=YES
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION\=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_NO\=macos10.11
[        ]     export LLVM_TARGET_TRIPLE_OS_VERSION_YES\=macos11.3
[        ]     export LLVM_TARGET_TRIPLE_VENDOR\=apple
[        ]     export LOCALIZATION_EXPORT_SUPPORTED\=YES
[        ]     export LOCALIZED_RESOURCES_FOLDER_PATH\=integration_test_native_crash.app/Contents/Resources/en.lproj
[        ]     export LOCALIZED_STRING_MACRO_NAMES\=NSLocalizedString\ CFCopyLocalizedString
[        ]     export LOCALIZED_STRING_SWIFTUI_SUPPORT\=YES
[        ]     export LOCAL_ADMIN_APPS_DIR\=/Applications/Utilities
[        ]     export LOCAL_APPS_DIR\=/Applications
[        ]     export LOCAL_DEVELOPER_DIR\=/Library/Developer
[        ]     export LOCAL_LIBRARY_DIR\=/Library
[        ]     export LOCROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export LOCSYMROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export MACH_O_TYPE\=mh_execute
[        ]     export MACOSX_DEPLOYMENT_TARGET\=10.11
[        ]     export MAC_OS_X_PRODUCT_BUILD_VERSION\=20G95
[        ]     export MAC_OS_X_VERSION_ACTUAL\=110502
[        ]     export MAC_OS_X_VERSION_MAJOR\=110000
[        ]     export MAC_OS_X_VERSION_MINOR\=110500
[        ]     export METAL_LIBRARY_FILE_BASE\=default
[        ]     export
METAL_LIBRARY_OUTPUT_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/R
esources
[        ]     export MODULES_FOLDER_PATH\=integration_test_native_crash.app/Contents/Modules
[        ]     export MODULE_CACHE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/ModuleCache.noindex
[        ]     export MTL_ENABLE_DEBUG_INFO\=YES
[        ]     export NATIVE_ARCH\=x86_64
[        ]     export NATIVE_ARCH_32_BIT\=i386
[        ]     export NATIVE_ARCH_64_BIT\=x86_64
[        ]     export NATIVE_ARCH_ACTUAL\=x86_64
[        ]     export NO_COMMON\=YES
[        ]     export
OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects
[        ]     export
OBJECT_FILE_DIR_normal\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects
-normal
[        ]     export OBJROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export ONLY_ACTIVE_ARCH\=YES
[        ]     export OS\=MACOS
[        ]     export OSAC\=/usr/bin/osacompile
[        ]     export PACKAGE_CONFIG\=/Users/gabriel/Desktop/integration_test_native_crash/.dart_tool/package_config.json
[        ]     export PACKAGE_TYPE\=com.apple.package-type.wrapper.application
[        ]     export PASCAL_STRINGS\=YES
[        ]     export
PATH\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefa
ult.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/De
veloper/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Content
s/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applic
ations/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/gabriel/.rbenv/shims:/Users/gabriel/google-cloud
-sdk/bin:/Users/gabriel/.nvm/versions/node/v12.18.4/bin:/Users/gabriel/Library/Android/sdk/tools/bin:/Users/gabriel/.pub-cache/bin:/Users/gabriel/lib/flutte
r/bin/cache/dart-sdk/bin:/Users/gabriel/lib/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Library
/Frameworks/Mono.framework/Versions/Current/Commands:/Users/gabriel/.cargo/bin
[   +2 ms]     export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES\=/usr/include\ /usr/local/include\ /System/Library/Frameworks\
/System/Library/PrivateFrameworks\ /Applications/Xcode.app/Contents/Developer/Headers\ /Applications/Xcode.app/Contents/Developer/SDKs\
/Applications/Xcode.app/Contents/Developer/Platforms
[        ]     export PBDEVELOPMENTPLIST_PATH\=integration_test_native_crash.app/Contents/pbdevelopment.plist
[        ]     export
PER_ARCH_OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objec
ts-normal/undefined_arch
[   +1 ms]     export
PER_VARIANT_OBJECT_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Ob
jects-normal
[   +1 ms]     export
PKGINFO_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/PkgInfo
[        ]     export PKGINFO_PATH\=integration_test_native_crash.app/Contents/PkgInfo
[        ]     export PLATFORM_DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export PLATFORM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export PLATFORM_DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
[        ]     export PLATFORM_DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
[        ]     export PLATFORM_DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export PLATFORM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
[        ]     export PLATFORM_DISPLAY_NAME\=macOS
[        ]     export PLATFORM_FAMILY_NAME\=macOS
[        ]     export PLATFORM_NAME\=macosx
[        ]     export PLATFORM_PREFERRED_ARCH\=x86_64
[        ]     export PLATFORM_PRODUCT_BUILD_VERSION\=12E507
[        ]     export PLIST_FILE_OUTPUT_FORMAT\=same-as-input
[        ]     export PLUGINS_FOLDER_PATH\=integration_test_native_crash.app/Contents/PlugIns
[        ]     export PODS_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export PODS_CONFIGURATION_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export PODS_PODFILE_DIR_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/macos/.
[        ]     export PODS_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Pods
[        ]     export
PODS_XCFRAMEWORKS_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/XCFrameworkIntermediates
[        ]     export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
[        ]     export
PRECOMP_DESTINATION_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Prefix
Headers
[        ]     export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
[        ]     export PRIVATE_HEADERS_FOLDER_PATH\=integration_test_native_crash.app/Contents/PrivateHeaders
[   +1 ms]     export PRODUCT_BUNDLE_IDENTIFIER\=com.example.integrationTestNativeCrash
[        ]     export PRODUCT_BUNDLE_PACKAGE_TYPE\=APPL
[        ]     export PRODUCT_COPYRIGHT\=Copyright\ ©\ 2021\ com.example.\ All\ rights\ reserved.
[        ]     export PRODUCT_MODULE_NAME\=integration_test_native_crash
[        ]     export PRODUCT_NAME\=integration_test_native_crash
[        ]     export PRODUCT_SETTINGS_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner/Info.plist
[        ]     export PRODUCT_TYPE\=com.apple.product-type.application
[        ]     export PROFILING_CODE\=NO
[        ]     export PROJECT\=Runner
[        ]     export
PROJECT_DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/DerivedSources
[        ]     export PROJECT_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export PROJECT_FILE_PATH\=/Users/gabriel/Desktop/integration_test_native_crash/macos/Runner.xcodeproj
[        ]     export PROJECT_NAME\=Runner
[        ]     export PROJECT_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build
[        ]     export PROJECT_TEMP_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export PUBLIC_HEADERS_FOLDER_PATH\=integration_test_native_crash.app/Contents/Headers
[   +2 ms]     export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS\=YES
[        ]     export REMOVE_CVS_FROM_RESOURCES\=YES
[        ]     export REMOVE_GIT_FROM_RESOURCES\=YES
[        ]     export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
[        ]     export REMOVE_HG_FROM_RESOURCES\=YES
[        ]     export REMOVE_SVN_FROM_RESOURCES\=YES
[        ]     export
REZ_COLLECTOR_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/ResourceMana
gerResources
[        ]     export
REZ_OBJECTS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/ResourceManage
rResources/Objects
[        ]     export REZ_SEARCH_PATHS\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug\ 
[        ]     export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
[        ]     export SCRIPTS_FOLDER_PATH\=integration_test_native_crash.app/Contents/Resources/Scripts
[        ]     export SCRIPT_INPUT_FILE_COUNT\=0
[        ]     export SCRIPT_INPUT_FILE_LIST_COUNT\=0
[        ]     export SCRIPT_OUTPUT_FILE_COUNT\=0
[        ]     export SCRIPT_OUTPUT_FILE_LIST_COUNT\=0
[        ]     export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR_macosx\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_DIR_macosx11_3\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
[        ]     export SDK_NAME\=macosx11.3
[        ]     export SDK_NAMES\=macosx11.3
[        ]     export SDK_PRODUCT_BUILD_VERSION\=20E214
[        ]     export SDK_VERSION\=11.3
[        ]     export SDK_VERSION_ACTUAL\=110300
[   +1 ms]     export SDK_VERSION_MAJOR\=110000
[        ]     export SDK_VERSION_MINOR\=110300
[        ]     export SED\=/usr/bin/sed
[        ]     export SEPARATE_STRIP\=NO
[        ]     export SEPARATE_SYMBOL_EDIT\=NO
[        ]     export SET_DIR_MODE_OWNER_GROUP\=YES
[        ]     export SET_FILE_MODE_OWNER_GROUP\=NO
[        ]     export SHALLOW_BUNDLE\=NO
[        ]     export SHALLOW_BUNDLE_PLATFORM\=NO
[        ]     export SHALLOW_BUNDLE_TRIPLE\=macos
[        ]     export SHALLOW_BUNDLE_ios_macabi\=NO
[        ]     export SHALLOW_BUNDLE_macos\=NO
[        ]     export SHARED_DERIVED_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/DerivedSources
[        ]     export SHARED_FRAMEWORKS_FOLDER_PATH\=integration_test_native_crash.app/Contents/SharedFrameworks
[        ]     export SHARED_PRECOMPS_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/PrecompiledHeaders
[        ]     export SHARED_SUPPORT_FOLDER_PATH\=integration_test_native_crash.app/Contents/SharedSupport
[        ]     export SKIP_INSTALL\=NO
[   +3 ms]     export SOURCE_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export SRCROOT\=/Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export STRINGS_FILE_INFOPLIST_RENAME\=YES
[        ]     export STRINGS_FILE_OUTPUT_ENCODING\=UTF-16
[        ]     export STRIP_BITCODE_FROM_COPIED_FILES\=NO
[        ]     export STRIP_INSTALLED_PRODUCT\=YES
[        ]     export STRIP_PNG_TEXT\=NO
[        ]     export STRIP_STYLE\=all
[        ]     export STRIP_SWIFT_SYMBOLS\=YES
[        ]     export SUPPORTED_PLATFORMS\=macosx
[        ]     export SUPPORTS_TEXT_BASED_API\=NO
[        ]     export SWIFT_ACTIVE_COMPILATION_CONDITIONS\=DEBUG
[        ]     export SWIFT_OPTIMIZATION_LEVEL\=-Onone
[        ]     export SWIFT_PLATFORM_TARGET_PREFIX\=macos
[        ]     export
SWIFT_RESPONSE_FILE_PATH_normal_x86_64\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runn
er.build/Objects-normal/x86_64/integration_test_native_crash.SwiftFileList
[        ]     export SWIFT_VERSION\=5.0
[        ]     export SYMROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products
[        ]     export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
[        ]     export SYSTEM_APPS_DIR\=/Applications
[        ]     export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
[        ]     export SYSTEM_DEMOS_DIR\=/Applications/Extras
[        ]     export SYSTEM_DEVELOPER_APPS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
[        ]     export SYSTEM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
[        ]     export SYSTEM_DEVELOPER_DEMOS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
[        ]     export SYSTEM_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
[        ]     export SYSTEM_DEVELOPER_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library
[        ]     export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
[        ]     export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Java\ Tools
[        ]     export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Performance\ Tools
[        ]     export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
[        ]     export SYSTEM_DEVELOPER_TOOLS\=/Applications/Xcode.app/Contents/Developer/Tools
[        ]     export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
[        ]     export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\
Library/releasenotes/DeveloperTools
[        ]     export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
[        ]     export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
[        ]     export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
[        ]     export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
[        ]     export SYSTEM_EXTENSIONS_FOLDER_PATH\=integration_test_native_crash.app/Contents/Library/SystemExtensions
[        ]     export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
[        ]     export SYSTEM_LIBRARY_DIR\=/System/Library
[        ]     export TAPI_VERIFY_MODE\=ErrorsOnly
[        ]     export TARGETNAME\=Runner
[        ]     export TARGET_BUILD_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug
[        ]     export TARGET_NAME\=Runner
[        ]     export
TARGET_TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export
TEMP_FILES_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export
TEMP_FILE_DIR\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build
[        ]     export TEMP_ROOT\=/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex
[        ]     export TEST_FRAMEWORK_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
[        ]     export TEST_LIBRARY_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
[        ]     export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
[        ]     export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
[        ]     export TRACK_WIDGET_CREATION\=true
[        ]     export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
[        ]     export TREE_SHAKE_ICONS\=false
[        ]     export UID\=501
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH\=integration_test_native_crash.app/Contents/Resources
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_NO\=integration_test_native_crash.app/Contents/Resources
[        ]     export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_YES\=integration_test_native_crash.app/Contents
[        ]     export UNSTRIPPED_PRODUCT\=NO
[        ]     export USER\=gabriel
[        ]     export USER_APPS_DIR\=/Users/gabriel/Applications
[        ]     export USER_LIBRARY_DIR\=/Users/gabriel/Library
[        ]     export USE_DYNAMIC_NO_PIC\=YES
[        ]     export USE_HEADERMAP\=YES
[        ]     export USE_HEADER_SYMLINKS\=NO
[        ]     export USE_LLVM_TARGET_TRIPLES\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
[        ]     export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
[        ]     export USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES\=YES
[        ]     export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
[        ]     export VALIDATE_PRODUCT\=NO
[        ]     export VALIDATE_WORKSPACE\=YES_ERROR
[        ]     export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
[        ]     export VERBOSE_PBXCP\=NO
[        ]     export VERBOSE_SCRIPT_LOGGING\=YES
[        ]     export VERSIONPLIST_PATH\=integration_test_native_crash.app/Contents/version.plist
[        ]     export VERSION_INFO_BUILDER\=gabriel
[        ]     export VERSION_INFO_FILE\=integration_test_native_crash_vers.c
[        ]     export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:integration_test_native_crash\ \ PROJECT:Runner-\"
[        ]     export WARNING_CFLAGS\=-Wall\ -Wconditional-uninitialized\ -Wnullable-to-nonnull-conversion\ -Wmissing-method-return-type\
-Woverlength-strings
[        ]     export WRAPPER_EXTENSION\=app
[        ]     export WRAPPER_NAME\=integration_test_native_crash.app
[        ]     export WRAPPER_SUFFIX\=.app
[        ]     export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
[        ]     export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
[        ]     export XCODE_PRODUCT_BUILD_VERSION\=12E507
[        ]     export XCODE_VERSION_ACTUAL\=1251
[        ]     export XCODE_VERSION_MAJOR\=1200
[        ]     export XCODE_VERSION_MINOR\=1250
[        ]     export XPCSERVICES_FOLDER_PATH\=integration_test_native_crash.app/Contents/XPCServices
[        ]     export YACC\=yacc
[        ]     export _BOOL_\=NO
[        ]     export _BOOL_NO\=NO
[        ]     export _BOOL_YES\=YES
[        ]     export _DEVELOPMENT_TEAM_IS_EMPTY\=YES
[        ]     export _IS_EMPTY_\=YES
[        ]     export _MACOSX_DEPLOYMENT_TARGET_IS_EMPTY\=NO
[        ]     export _WRAPPER_CONTENTS_DIR\=/Contents
[        ]     export _WRAPPER_CONTENTS_DIR_SHALLOW_BUNDLE_NO\=/Contents
[        ]     export _WRAPPER_PARENT_PATH\=/..
[        ]     export _WRAPPER_PARENT_PATH_SHALLOW_BUNDLE_NO\=/..
[        ]     export _WRAPPER_RESOURCES_DIR\=/Resources
[        ]     export _WRAPPER_RESOURCES_DIR_SHALLOW_BUNDLE_NO\=/Resources
[        ]     export arch\=undefined_arch
[        ]     export variant\=normal
[        ]     /bin/sh -c
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Script-3399D490228B24CF009A79C7
.sh
[   +3 ms] ♦ mkdir -p --
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks
[   +2 ms] ♦ rsync -av --delete --filter - .DS_Store /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/App.framework
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks
[  +12 ms] building file list ... done
[   +6 ms] deleting App.framework/Versions/A/_CodeSignature/CodeResources
[        ] deleting App.framework/Versions/A/_CodeSignature/
[   +1 ms] App.framework/Versions/A/
[        ] App.framework/Versions/A/App
[   +1 ms] App.framework/Versions/A/Resources/Info.plist
[        ] App.framework/Versions/A/Resources/flutter_assets/AssetManifest.json
[        ] App.framework/Versions/A/Resources/flutter_assets/FontManifest.json
[   +4 ms] App.framework/Versions/A/Resources/flutter_assets/NOTICES.Z
[   +6 ms] App.framework/Versions/A/Resources/flutter_assets/kernel_blob.bin
[ +233 ms] sent 40191940 bytes  received 158 bytes  80384196.00 bytes/sec
[        ] total size is 46527204  speedup is 1.16
[        ] ♦ rsync -av --delete --filter - .DS_Store --filter - Headers --filter - Modules
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/FlutterMacOS.framework
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/
00:24 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [  +18 ms] building file list ... done
[  +12 ms] FlutterMacOS.framework/Versions/A/
[        ] FlutterMacOS.framework/Versions/A/FlutterMacOS
[ +236 ms] FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources
[   +3 ms] sent 42890110 bytes  received 70 bytes  85780360.00 bytes/sec
[        ] total size is 43684807  speedup is 1.02
[   +1 ms] ♦ codesign --force --verbose --sign - --
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/App.framework/Ap
p
[ +561 ms]
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/App.framework/Ap
p: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter.app]
[  +10 ms] ♦ codesign --force --verbose --sign - --
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/FlutterMacOS.fra
mework/FlutterMacOS
[  +44 ms]
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/FlutterMacOS.fra
mework/FlutterMacOS: replacing existing signature
00:25 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +510 ms]
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Frameworks/FlutterMacOS.fra
mework/FlutterMacOS: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter-macos]
[  +11 ms] CodeSign /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app (in target
'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
[        ]     Signing Identity:     "-"
[        ]     /usr/bin/codesign --force --sign - --entitlements
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/integration_test_native_crash.a
pp.xcent --timestamp\=none /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app
[  +24 ms] /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app: replacing existing
signature
[  +77 ms] Validate /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app (in target
'Runner' from project 'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     builtin-validationUtility
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app -no-validate-extension
[   +1 ms] RegisterWithLaunchServices
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app (in target 'Runner' from project
'Runner')
[        ]     cd /Users/gabriel/Desktop/integration_test_native_crash/macos
[        ]     /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f
-R -trusted /Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app
[  +58 ms] ** BUILD SUCCEEDED **
[  +29 ms] Building macOS application... (completed in 20.3s)
[   +5 ms] executing: /usr/bin/plutil -convert json -o -
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Info.plist
[  +21 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/gabriel/Desktop/integration_test_native_crash/build/macos/Build/Products/Debug/integration_test_native_crash.app/Contents/Info.plist
[   +2 ms] {"CFBundleName":"integration_test_native_crash","DTXcode":"1251","DTSDKName":"macosx11.3","NSHumanReadableCopyright":"Copyright © 2021
com.example. All rights
reserved.","DTSDKBuild":"20E214","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"20G95","NSPrincipalClass":"NSApplication","CF
BundleIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"DTPlatformName":"macosx","CFBun
dleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"integration_test_native_crash","DTComp
iler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"com.example.integrationTestNativeCrash","DTPlatformVersion":"11.3","DTXcodeBuild":"12E507",
"LSMinimumSystemVersion":"10.11","DTPlatformBuild":"12E507"}
00:26 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +903 ms] Observatory URL on device: http://127.0.0.1:60820/plg6osCZB5A=/
[   +6 ms] test 0: Connecting to vm service
[  +13 ms] test 0: Observatory uri is available at http://127.0.0.1:60820/plg6osCZB5A=/
00:27 +0: loading /Users/gabriel/Desktop/integration_test_native_crash/integration_test/native_crash_test.dart                                             [ +481 ms] test 0: Finding the correct isolate with the integration test service extension
[ +127 ms] test 0: connected to test device, now awaiting test result
[   +1 ms] test 0: Waiting for test harness or tests to finish
00:53 +0: cause native crash                                                                                                                               
```

```
➜  integration_test_native_crash flutter analyze
Analyzing integration_test_native_crash...                              
No issues found! (ran in 2.2s)
```

```
➜  integration_test_native_crash flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-DE)
    • Flutter version 2.5.0 at /Users/gabriel/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gabriel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/gabriel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/gabriel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/gabriel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Users/gabriel/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/212.5080.55/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.53.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/89829

### CODE REVIEW

File: packages/flutter_tools/lib/src/test/integration_test_device.dart [hunk 1]
```diff
@@ -97,7 +97,14 @@ class IntegrationTestTestDevice implements TestDevice {
...
     });
 
-    unawaited(remoteMessages.pipe(controller.local.sink));
+    remoteMessages.listen(
+      (String s) => controller.local.sink.add(s),
+      onError: (Object error, StackTrace stack) => controller.local.sink.addError(error, stack),
+    );
+    unawaited(vmService.service.onDone.whenComplete(
+      () => controller.local.sink.close(),
+    ));
```
Comment (jiahaog) [inline packages/flutter_tools/lib/src/test/integration_test_device.dart:106]: nit: Can this be merged into the `remoteMessages.listen` above?

```dart
remoteMessages.listen(
  (String s) => controller.local.sink.add(s),
  onError: (Object error, StackTrace stack) => controller.local.sink.addError(error, stack),
  onDone: () => controller.local.sink.close(),
);
```

**Review by jiahaog — APPROVED** [review]
Thanks, LGTM!

File: packages/flutter_tools/lib/src/test/integration_test_device.dart (hunk 1 above)
Comment (jason-simmons) [reply packages/flutter_tools/lib/src/test/integration_test_device.dart:106]: The `remoteMessages` stream is not closed when the on-device process crashes.

That event appears to be signaled only by the VM service's `onDone`.
