### PR TITLE
Remove doc for --ignore-deprecation and check for pubspec before v1 embedding check

### LINKED ISSUE #96642: flutter channel shows incorrect Android embedding v2 warning
When I run `flutter channel stable` (for example) in my root user directory, I see the following warning:

> Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2.

This, however, makes no sense at all because my root user directory is **not** a Flutter project. It does, however, contain an `android` directory (which has nothing to do with the `android` directories you will find in Flutter projects).

## Steps to Reproduce

1. cd to a directory that contains a folder named `android`
2. `flutter channel stable` (or a different channel if you are already on stable)

<details><summary>Click to expand full logs</summary>

```
D:\>flutter channel stable
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  No `D:\android\AndroidManifest.xml` file
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Switching to flutter channel 'stable'...
```

</details>

## Proposal

Before checking if there is an `AndroidManifest.xml` in an `android` directory and if that directory exists, check if the working directory **is a Flutter project**.  

### Steps

1. Check if the current working directory is a Flutter project → check for a `pubspec.yaml` file.
2. Check if there is an `android` directory.
3. Check for the `AndroidManifest.xml` file.

Currently, step 2. is missing.

### PR DESCRIPTION
**Pull request by GaryQian**
Fixes https://github.com/flutter/flutter/issues/96642

Also removes the documentation for the `--ignore-deprecation` flag as we no longer want developers to ignore this warning. The flag still works and can be used, but developers will no longer see the suggestion to use it anymore.

The next step is to deprecate the `--ignore-deprecation` flag entirely to disable building for v1 embedding.

### CODE REVIEW

File: packages/flutter_tools/lib/src/project.dart [hunk 1]
```diff
@@ -599,14 +599,11 @@ class AndroidProject extends FlutterProjectPlatform {
 Warning
 ──────────────────────────────────────────────────────────────────────────────
 Your Flutter application is created using an older version of the Android
-embedding. It is being deprecated in favor of Android embedding v2. Follow the
-steps at
+embedding. It is being deprecated in favor of Android embedding v2. Migrate
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/project.dart:602]: Maybe "To migrate your project, follow the steps at" per [the recommendation against telling people to do something in the style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-the-passive-voice-recommend-do-not-require). (That's in the documentation section, but seems relevant here.)

**Review by stuartmorgan-g — APPROVED** [review]
LGTM
