### PR TITLE
Add AccessibilityFeatures to media query and fix Snackbar a11y behavior

### LINKED ISSUE #12436: Way to check if VoiceOver/TalkBack is on
Some customers want to be able to present a slightly different UI to a11y users. For that, they need to check if VoiceOver or TalkBack is used by the user.

Note: It is not enough to just check if a11y is turned on as on Android some apps turn this on to be able to read the screen content.

### LINKED ISSUE #16243: [a11y]: Snackbar should not disappear until the user takes an action when accessibility controls are turned on
In the Bottom App Bar demo, pressing the Floating Action Button shows a snackbar.  I noticed this while writing #16238

For this to be accessible to users with a screen reader or other accessibility feature turned on, the snackbar should remain on the screen until the user takes another action.

This should be a change we make at the Snackbar level.

@goderbauer

### PR DESCRIPTION
**Pull request by jonahwilliams**
- Exposes the information from window.AccessibilityFeatures through the Bindings/WidgetsBindingObserver/Widgets app infrastructure. This simply listens to window.onAccessibilityFeaturesUpdated similar to other window settings.

- This information is provided to MediaQuery in the WidgetsApp and works like other media query flags.

- Updates the implementation of the snackbar to conform to the a11y spec - disabling all animations and preventing timeouts for snackbars with actions. If talkback/voiceover is toggled when a snackbar is already being displayed, the new behavior takes over.

[x] Requires https://github.com/flutter/engine/pull/5740
[x] Requires https://github.com/flutter/engine/pull/5601 (for dismissing snackbar)

Fixes https://github.com/flutter/flutter/issues/12436
Fixes https://github.com/flutter/flutter/issues/16243

### CODE REVIEW

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 1]
```diff
@@ -183,6 +184,7 @@ class SnackBar extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
+    final bool removeAnimation = RendererBinding.instance.assistiveTechnologyEnabled;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/snack_bar.dart]: we should put this in the MediaQuery so you don't need to use the binding. Using the binding directly is bad for testability, among other things.

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/snack_bar.dart]: Moved this field to MediaQueryData and updated tests, PTAL

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 2]
```diff
@@ -213,8 +215,41 @@ class SnackBar extends StatelessWidget {
...
+      child: new Row(
+        children: children,
+        crossAxisAlignment: CrossAxisAlignment.center,
+      ),
+    );
+    snackbar = new Semantics(
+      container: true,
+      liveRegion: true,
+      onDismiss: () {
+        Scaffold.of(context).removeCurrentSnackBar(reason: SnackBarClosedReason.swipe);
```
Comment (Hixie) [inline packages/flutter/lib/src/material/snack_bar.dart]: we should either add a new SnackBarClosedReason value, or we should update the "swipe" value's documentation to cover this case.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 3]
```diff
@@ -120,6 +122,17 @@ class MediaQueryData {
...
 
+  /// Whether the user is using assitive technologies to interact with the
+  /// application.
+  ///
+  /// This includes screen readers such as TalkBack on Android and VoiceOVer
+  /// on iOS, as well as hardware switches, and more.
+  ///
+  /// See also:
+  ///
+  ///  * [Window.assistiveTechnologyEnabled], for the flag on the window.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/media_query.dart]: "for the flag on the window" is self-evident from the name. Maybe "which this attribute is based on", or something.

**Comment by Hixie** [comment]
"assistiveTechnologyEnabled" is a very broad flag. When you trigger the Google Assistant, it turns on accessibility briefly -- will this impact snackbars? Some people use tools that use the a11y APIs for unrelated reasons e.g. password autofill; will those impact snackbars?

Would it make more sense to trigger this from a "disable animations" setting?

The documentation for "assistiveTechnologyEnabled" doesn't say what exactly the flag should be used for. We should update that too, if we stick with this broad flag (instead of more narrowly-defined flags, like "disable animations" or some such).

**Comment by jonahwilliams** [comment]
@Hixie the currently corresponds to VoiceOver enabled on iOS and touchExplorationEnabled on Android, so it won't turn on just for a password manager.  Unfortunately there doesn't seem to be a way to say whether a given accessibility service changes the interaction model in a particular way - unless we were to know ahead of time all of the particular services.

File: packages/flutter/test/material/snack_bar_test.dart [hunk 4]
```diff
@@ -482,6 +482,47 @@ void main() {
...
+      expect(find.text('ACTION'), findsOneWidget);
+      // Snackbar doesn't close
+      await tester.pump(const Duration(seconds: 10));
+      expect(find.text('ACTION'), findsOneWidget);
+      await tester.tap(find.text('ACTION'));
+      await tester.pump();
+      // Snackbar closes immediately
+      expect(find.text('ACTION'), findsNothing);
+  });
+
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/test/material/snack_bar_test.dart]: I've added a test that demonstrates the new snackbar behavior - enabling talkback or voiceover when the snackbar is open will prevent it from closing via timeout. disabling talkback or voiceover again will cause the snackbar to timeout after at most its timeout duration.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -1162,12 +1162,18 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
     if (_snackBars.isEmpty || _snackBarController.status == AnimationStatus.dismissed)
       return;
+    final MediaQueryData mediaQuery = MediaQuery.of(context);
     final Completer<SnackBarClosedReason> completer = _snackBars.first._completer;
-    _snackBarController.reverse().then<void>((Null _) {
-      assert(mounted);
-      if (!completer.isCompleted)
-        completer.complete(reason);
-    });
+    if (mediaQuery.accessibleNavigation) {
```
Comment (amirh) [inline packages/flutter/lib/src/material/scaffold.dart]: nit: mention the accessible behavior in the method's Dartdoc.

Comment (amirh) [inline packages/flutter/lib/src/material/scaffold.dart]: Missing unit test for this scenario (hideCurrentSnackbar is called with/without accessibleNavigation).

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 6]
```diff
@@ -213,8 +218,41 @@ class SnackBar extends StatelessWidget {
...
+              opacity: fadeAnimation,
+              child: snackbar,
+            ),
+          ),
+        ),
+      ),
+    );
     return new ClipRect(
-      child: new AnimatedBuilder(
+      child: mediaQueryData.accessibleNavigation ? snackbar : new AnimatedBuilder(
```
Comment (amirh) [inline packages/flutter/lib/src/material/snack_bar.dart]: Just curious, do we not want the Material in the widget hierarchy in the accessibility case?
e.g when accessibility is on if someone is tapping with 2 fingers do we not want the same ink splashes?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 7]
```diff
@@ -1480,12 +1486,19 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
     if (_snackBars.isNotEmpty) {
       final ModalRoute<dynamic> route = ModalRoute.of(context);
       if (route == null || route.isCurrent) {
-        if (_snackBarController.isCompleted && _snackBarTimer == null)
-          _snackBarTimer = new Timer(_snackBars.first._widget.duration, () {
+        if (_snackBarController.isCompleted && _snackBarTimer == null) {
+          final SnackBar snackBar = _snackBars.first._widget;
+          _snackBarTimer = new Timer.periodic(snackBar.duration, (Timer timer) {
```
Comment (amirh) [inline packages/flutter/lib/src/material/scaffold.dart]: When the user turns off accessibility while the snackbar is showing we will get some inconsistent behavior - the time the snackbar will remain visible will be somewhat random between 0 to snackBar.duration.

What do you think about listening to the accessibility change again and then firing a timer?

**Review by amirh — COMMENTED** [review]
Good PR description! helped me get going with the review.

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/snack_bar.dart]: Not sure what you mean - the material is still in the tree. Ink splashes will only be disabled if animations are disabled (not done yet).

File: packages/flutter/lib/src/material/scaffold.dart (hunk 7 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/scaffold.dart]: It's not inconsistent, it's just undefined in the snackbar spec.

It's not a common use case to toggle TalkBack on and off while showing snackbars. This simplifies the implementation so we don't have to add/remove listeners on window.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/scaffold.dart]: Should be L522-523 of snack_bar_test.dart to cover the true case, other case is handled previously

Comment (amirh) [reply packages/flutter/lib/src/material/scaffold.dart]: right missed that.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 7 above)
Comment (amirh) [reply packages/flutter/lib/src/material/scaffold.dart]: I think that from the user's perspective it's inconsistent: you turn off accessibility and the snack bar might disappear immediately or after a few seconds.

But I agree it's not a very important edge case so ok to avoid complicating the code for that.

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 6 above)
Comment (amirh) [reply packages/flutter/lib/src/material/snack_bar.dart]: Oops, I misread the assignments above.

**Review by amirh — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Thanks for the review!

File: packages/flutter/lib/src/material/scaffold.dart (hunk 7 above)
Comment (Hixie) [reply packages/flutter/lib/src/material/scaffold.dart]: i don't think a periodic timer is a good idea here. we'd be waking the CPU regularly while accessibility is enabled, even though nothing is happening.

Comment (Hixie) [reply packages/flutter/lib/src/material/scaffold.dart]: please at a very minimum leave a TODO here saying that this will hurt battery for accessibility users.

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/scaffold.dart]: I've update this to use the didChangeDependencies lifecycle to close the snackbar if a11y is disabled - https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L1407.

Shouldn't have a significant effect on the battery?
