### PR TITLE
Expose toggle to textfield's opacity animation.

### LINKED ISSUE #59327: Blinking cursor should use less CPU
## Details

I noticed that this issue has been raised in regards to ios, but this is on macos and that issue is also locked now. https://github.com/flutter/flutter/issues/33833

Using an animated widget, such as TextField (when the cursor is blinking) causes cpu usage to remain steadily at 6-10% in the mac activity monitor. I'm on a 2019 15" MBP. Submitting the field (and therefore ending the animation) sees a return to 0% cpu usage.

To reproduce, just display a TextField.

As a side note, memory usage sits between 200-300MB for a relatively simple app. Loading larger widgets such as large amounts of text (not rich text) causes memory to spike as much as 50-70MB.

I'm on flutter master, but this issue occurs on every version I've tried.

**Target Platform:** 

MacOS

**Target OS version/browser:** 

Catalina 10.15.1 (19B88)

**Devices:** 

MacBook Pro

## Logs

```
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:40:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:49:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:58:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:63:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:68:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:77:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:86:20 • override_on_non_overriding_member
   info • The getter doesn't override an inherited getter • lib/bloc/active_requests_bloc.dart:93:20 • override_on_non_overriding_member
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: RequestModel.id • lib/bloc/models.dart:16:7 •
          must_be_immutable
   info • Close instances of `dart.core.Sink` • lib/header_bar.dart:12:9 • close_sinks
   info • Close instances of `dart.core.Sink` • lib/request_container.dart:36:9 • close_sinks
   info • Close instances of `dart.core.Sink` • lib/request_container.dart:111:9 • close_sinks

```

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.25, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.20.0-1.0.pre.25 at /Users/ben/.local/lib/flutter
    • Framework revision 3744b82d8c (17 hours ago), 2020-06-11 13:25:01 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.1 19B88

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by blquinn**
This exposes the toggle to cupertino/material textfield's opacity animation so that users can disable the cursor opacity animation if they choose to.

Sort of fixes https://github.com/flutter/flutter/issues/59327

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
Missing documentation for the new params:
```
dartdoc:stdout: Generating docs for library cupertino from package:flutter/cupertino.dart...
dartdoc:stderr:   error: undefined macro [flutter.widgets.editableText.cursorOpacityAnimates]
dartdoc:stderr:     from cupertino.CupertinoTextField.cursorOpacityAnimates: (file:///tmp/flutter%20sdk/packages/flutter/lib/src/cupertino/text_field.dart:666:14)
...
dartdoc:stderr:   error: undefined macro [flutter.widgets.editableText.cursorOpacityAnimates]
dartdoc:stderr:     from material.TextField.cursorOpacityAnimates: (file:///tmp/flutter%20sdk/packages/flutter/lib/src/material/text_field.dart:586:15)
```

**Comment by Blquinn** [comment]
@jmagman I've updated the docs. Not sure why that macro didn't work, but it's building now.

**Comment by gnprice** [comment]
The macro wasn't working because there wasn't a definition for it. If you'd like to use the handy macro feature in the docs, you can add a `@template` marker with the same syntax that's used on the neighboring field:
```dart
  /// {@template flutter.widgets.editableText.cursorRadius}
  /// How rounded the corners of the cursor should be.
  ///
  /// By default, the cursor has no radius.
  /// {@endtemplate}
  final Radius? cursorRadius;

  /// Whether the cursor will animate from fully transparent to fully opaque
  /// during each cursor blink.
  ///
  /// By default, the cursor opacity will animate on iOS platforms and will not
  /// animate on Android platforms.
  final bool cursorOpacityAnimates;
```

That `{@template` etc. syntax is what defines the meaning of `{@macro flutter.widgets.editableText.cursorRadius}`, and you can do the same thing to make it work the same way for `cursorOpacityAnimates`.

**Comment by Blquinn** [comment]
@gnprice Oh nice, thanks for the tip!

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -581,6 +582,13 @@ class TextField extends StatefulWidget {
   /// {@macro flutter.widgets.editableText.cursorRadius}
   final Radius? cursorRadius;
 
+  /// Whether the cursor will animate from fully transparent to fully opaque
+  /// during each cursor blink.
+  ///
+  /// By default, the cursor opacity will animate on iOS platforms and will not
+  /// animate on Android platforms.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart:589]: Can you use a macro/template here instead of duplicating this?  I see some discussion above about a macro not working before but let me know if you can't get it.

**Review by justinmc — COMMENTED** [review]
I'm on board with this.  Since cursorOpacityAnimates already exists on EditableText, I see no reason why we shouldn't expose it on TextField and CupertinoTextField.

Can you add tests for this?  I think you can simply add one for each of TextField and CupertinoTextField, and verify that underlying EditableText has the correct cursorOpacityAnimates value.

Also, have you verified that turning this off does indeed fix the CPU performance issue?  I see you commented on the issue with some hard numbers, were those taken from disabling and enabling this on EditableText?

**Comment by Blquinn** [comment]
@justinmc I've added the macro for the docs and added tests you suggested for material and cupertino. I have also manually verified that the toggle overrides the default platform value correctly on a linux computer and mac.

> Also, have you verified that turning this off does indeed fix the CPU performance issue? I see you commented on the issue with some hard numbers, were those taken from disabling and enabling this on EditableText?

Correct, I tested this by disabling/enabling the parameter in the text field examples. Nothing but the text field is present in the test app.

I have checked the CPU usage on multiple platforms (linux, macOS, iOS, windows) on physical devices, not emulators and in release mode. Each platform shows the same trend -- with the animation enabled I see a constant 10-16% cpu usage and with it disabled I see 0% cpu usage.

On desktop platforms I measured CPU using htop and the systems system monitor program. For iOS I used xCode's profiler/monitor thing.

**Review by justinmc — APPROVED** [review]
LGTM :+1:.  Thank you for the fixes!

**Comment by Blquinn** [comment]
@justinmc Sweet, thanks for the review! What exactly is the process for getting this merged?

**Review by werainkhatri — APPROVED** [review]
congrats on your first contribution!

blue flutter

**Comment by justinmc** [comment]
Sorry @Blquinn, the process was just to find a secondary reviewer, which @werainkhatri has been nice enough to provide.  Now this will merge automatically when the tree is green.

**Comment by Blquinn** [comment]
Awesome; no problem at all. Thank you both!

**Comment by gnprice** [comment]
The tree is green, but the "Google testing" check for this PR seems to have gotten stuck:
* #123289

One workaround is to update the PR so the check gets restarted. I'm not sure if there are other workarounds a Googler could apply.
