### PR TITLE
Fix initialization of time in repeat on AnimationController

### LINKED ISSUE #142885: `repeat` on `AnimationControlle` does not calculate initial value correctly
### Steps to reproduce

Example 1: Create an `AnimationController` like this:

```dart
controller = AnimationController(
        duration: const Duration(seconds: 2),
        vsync: this,
        lowerBound: 100,
        upperBound: 300);
controller.repeat();
```

Example 2: Create an `AnimationController` like this:

```dart
controller = AnimationController(
        duration: const Duration(seconds: 2),
        vsync: this,
        lowerBound: -100,
        upperBound: 200);
controller.repeat();
```

### Expected results

The first animation starts with the value 100 and the second starts with the value -100.

### Actual results

In the first example the animation starts with the value 200 and in the second example Flutter throws the following exception:

```
Assertion failed: file:///opt/flutter/packages/flutter/lib/src/animation/animation_controller.dart:889:12 _initialT >= 0.0 is not true
```

### Code sample

Here is a DartPad that shows both issues: https://dartpad.dev/?id=79b890fd2a994d6e3f5ac210f433e7d5

### Flutter Doctor output

Tested on the latest release and the latest main.

### PR DESCRIPTION
**Pull request by paldepind**
This PR fixes #142885.

The issue is that in `_RepeatingSimulation` the initial time is calculated as follows:

```
(initialValue / (max - min)) * (period.inMicroseconds / Duration.microsecondsPerSecond)
```

This calculation does not work in general. For instance, if `max` is 300, `min` is 100, and `initialValue` is 100 then `initialValue / (max - min)` is 1/2 when it should be 0

The current tests work by happenstance because the numbers used happen to work. To reveal the bug I've added some more tests similar to the existing ones but with different numbers.

A "side-effect" of the incorrect calculation is that if `initialValue` is 0, then the animation will always start from `min` no matter what. For instance, in one of the tests, an `AnimationController` with the value 0 is told to `repeat` between 0.5 and 1.0, and this starts the animation from 0.5. To preserve this behavior, and to more generally handle the case where the initial value is out of bounds, this PR clamps the initial value to be within the lower and upper bounds of the repetition.

Just for reference, this calculation was introduced at https://github.com/flutter/flutter/pull/25125.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
Fly-by comment from triage: Could you take a look at the failing "Linux analyze" check and fix whatever it is complaining about? Thanks.

**Comment by paldepind** [comment]
@goderbauer I've fixed the lint error.

File: packages/flutter/test/animation/animation_controller_test.dart [hunk 1]
```diff
@@ -769,6 +769,8 @@ void main() {
       final AnimationController controller = AnimationController(
         duration: const Duration(milliseconds: 100),
         value: 0.0,
+        lowerBound: -1,
+        upperBound: 3,
```
Comment (goderbauer) [inline packages/flutter/test/animation/animation_controller_test.dart:773]: Instead of changing an existing test case, could you add a new test case for this, please?

**Review by goderbauer — COMMENTED** [review]
Thanks for fixing this!

File: packages/flutter/test/animation/animation_controller_test.dart (hunk 1 above)
Comment (paldepind) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: Thanks for taking a look at the PR @goderbauer.

This existing test is supposed to test that min and max work as they should. However, it ends up only testing some _very_ special cases and therefore doesn't really work as intended. I therefore thought it would be better to add more cases to the existing test, instead of adding a new test and leaving the insufficient test unchanged.

That being said if you still prefer a new test then I'll update the PR with that 👍

Comment (goderbauer) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: We'd still want a test that tests `.repeat` when no lowerBound and upperBound is set (basically the old test). Therefore, I'd prefer a new test case for when lowerBound and upperBound are set.

Comment (paldepind) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: There is [another test](https://github.com/flutter/flutter/blob/535259ce132858c17c995f8444b3bf63cb01f1ac/packages/flutter/test/animation/animation_controller_test.dart#L716) that tests `repeat` when `lowerBound` and `upperBound` is not set.

In this test, setting `lowerBound` and `upperBound` do not make a difference. The values are only used when `min` and `max` are not given to `repeat` and they are given in all the `repeat` invocations in this test. I've only set `lowerBound` and `upperBound` since there is an assert that `max <= upperBound && min >= lowerBound` which would be violated otherwise.

The changed test tests strictly more than it did before. Please consider if you don't think that's better practice than leaving a broken test in place. If not I'll create a new separate test.

Comment (goderbauer) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: IMO, the test isn't broken. Doing what the test did before should still work after this change: you should still be able to call `repeat` with a `max`/`min` while the `AnimationController` has no `lowerBound`/`upperBound` configured. As far as I can tell, we lose test coverage for that case if we modify the test to give the `AnimationController` explicit bounds.

Comment (goderbauer) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: > I would say that the test is broken since it doesn't test what it claims to test.

My suggestion: Let's update the name of this test then so it matches what it really tests and leave it otherwise unchanged. Then, let's add a new test case for the behavior we want to test.

Comment (paldepind) [reply packages/flutter/test/animation/animation_controller_test.dart:773]: Sounds good. I'll update the PR :)

**Review by goderbauer — APPROVED** [review]
LGTM

Thank you for the fix!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by paldepind** [comment]
You're welcome. Thanks for reviewing.
