### PR TITLE
fix(ScrollAction): unsafe non-null assertion

### LINKED ISSUE #158063: `ScrollAction.invoke()` has an unsafe null-assert
```dart
if (primaryScrollController.position.context.notificationContext == null
    && Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!) == null) {
  // ...
}
```

If the `notificationContext` is null, then it will immediately be evaluated with a null-assert; should have been a `||` instead of `&&`.

### PR DESCRIPTION
**Pull request by kszczek**
This conditional most likely was meant to use `||` instead of `&&` operator to check if `notificationContext` is null OR if no Scrollable was found for this `notificationContext`. Using the AND operator instead causes the null assertion to fail when notificationContext is null, while also causing an assertion failure when notificationContext is not null, but no Scrollable is found for it. While at it, let's also deduplicate the Scrollable.maybeOf call.

This fix is purely speculative, I didn't encounter this error, but rather was reading the ScrollAction's source and stumbled upon this. ~~With that said I wasn't actually able to trigger this error condition, thus why there are no tests included with this PR, if anyone has ideas on how this could be triggered, I'll be happy to include such test cases.~~

fixes #158063

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable_helpers.dart [hunk 1]
```diff
@@ -460,17 +460,17 @@ class ScrollAction extends ContextAction<ScrollIntent> {
...
-          && Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!) == null) {
+      if (primaryScrollController.position.context.notificationContext != null) {
+        state = Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!);
+      }
+      if (state == null) {
         return;
       }
-      state = Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!);
     }
-    assert(state != null, '$ScrollAction was invoked on a context that has no scrollable parent');
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/scrollable_helpers.dart:469]: I agree it's a bit strange for this method to use a combination of `assert`s and early `return`s, rather than sticking with one or the other.

File: packages/flutter/lib/src/widgets/scrollable_helpers.dart [hunk 2]
```diff
@@ -460,17 +460,17 @@ class ScrollAction extends ContextAction<ScrollIntent> {
         return true;
       }());
 
-      if (primaryScrollController.position.context.notificationContext == null
-          && Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!) == null) {
+      if (primaryScrollController.position.context.notificationContext != null) {
+        state = Scrollable.maybeOf(primaryScrollController.position.context.notificationContext!);
+      }
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/widgets/scrollable_helpers.dart:465]: I think it'd be good to set a local variable here, to further reduce the amount of null-asserting.

```suggestion
      final BuildContext? notificationContext = primaryScrollController.position.context.notificationContext;
      if (notificationContext != null) {
        state = Scrollable.maybeOf(notificationContext);
      }
```

**Review by nate-thegrate — COMMENTED** [review]
Looks great!

Just 1 thing left: go to [scrollable_helpers_test.dart](https://github.com/kszczek/flutter/blob/fix-scroll-action-condition/packages/flutter/test/widgets/scrollable_helpers_test.dart) and add a test with something like
```dart
somethingThatShouldWork();
expect(tester.takeException(), isNull);
```

File: packages/flutter/lib/src/widgets/scrollable_helpers.dart (hunk 1 above)
Comment (kszczek) [reply packages/flutter/lib/src/widgets/scrollable_helpers.dart:469]: Yeah, this assert was also marked as unnecessary by the linter after applying the patch.

File: packages/flutter/lib/src/widgets/scrollable_helpers.dart (hunk 2 above)
Comment (kszczek) [reply packages/flutter/lib/src/widgets/scrollable_helpers.dart]: Done.

**Comment by kszczek** [comment]
Thanks for the review, I've addressed the code style issue and added the aforementioned test.

I've had to mock the `Scrollable.notificationContext` property though, because I couldn't find a way to make it null when the action is invoked. I don't think that's practically possible, as warranted by the fact that no user reported this issue.

File: packages/flutter/test/widgets/scrollable_helpers_test.dart [hunk 3]
```diff
@@ -590,4 +606,77 @@ void main() {
...
+    await tester.pumpAndSettle();
+    expect(controller.position.pixels, equals(0.0));
+    expect(
+      tester.getRect(find.byKey(const ValueKey<String>('Box 0'), skipOffstage: false)),
+      equals(const Rect.fromLTRB(0.0, 0.0, 800.0, 50.0)),
+    );
+
+    for (final LogicalKeyboardKey key in keys) {
+      // We exclude the modifier keys here for web testing since default web shortcuts
+      // do not use a modifier key with arrow keys for ScrollActions.
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/scrollable_helpers_test.dart:657]:
```suggestion
      // The default web shortcuts do not use a modifier key for ScrollActions.
```

File: packages/flutter/test/widgets/scrollable_helpers_test.dart [hunk 4]
```diff
@@ -590,4 +606,77 @@ void main() {
...
+      if (!kIsWeb && keysWithModifier.contains(key)) {
+        await tester.sendKeyDownEvent(modifierKey);
+      }
+
+      // Invoking the ScrollAction would previously lead to a type error caused by an
+      // unsafe non-null assertion on the notificationContext, let's make sure it
+      // doesn't happen anymore.
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/scrollable_helpers_test.dart:664]: Instead of describing the bug in the test code, we usually just add an issue link.

```suggestion
```

File: packages/flutter/test/widgets/scrollable_helpers_test.dart [hunk 5]
```diff
@@ -590,4 +606,77 @@ void main() {
     expect(find.text('The cape as red as blood'), findsOneWidget);
     expect(find.text('The hair as yellow as corn'), findsOneWidget);
   });
+
+  testWidgets('Invoking a ScrollAction when notificationContext is null does not cause an exception.', (WidgetTester tester) async {
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/scrollable_helpers_test.dart:610]:
```suggestion

  // Regression test for https://github.com/flutter/flutter/issues/158063.
  testWidgets('Invoking a ScrollAction when notificationContext is null does not cause an exception.', (WidgetTester tester) async {
```

I went ahead and made an issue so we can link it here:
- https://github.com/flutter/flutter/issues/158063

File: packages/flutter/test/widgets/scrollable_helpers_test.dart [hunk 6]
```diff
@@ -590,4 +606,77 @@ void main() {
...
+      // doesn't happen anymore.
+      await tester.sendKeyEvent(key);
+      expect(tester.takeException(), isNull);
+
+      if (!kIsWeb && keysWithModifier.contains(key)) {
+        await tester.sendKeyUpEvent(modifierKey);
+      }
+
+      // We expect the ScrollAction to not find any eligible scrollables, thus the
+      // scroll position should not change.
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/scrollable_helpers_test.dart:673]:
```suggestion
      // No scrollable is found, so the scroll position should not change.
```

**Review by nate-thegrate — APPROVED** [review]
LGTM, thanks for the well-structured test!

Perhaps if it's impossible for the `notificationContext` to be null, the getter should be updated to be non-nullable, but that's outside the scope of this PR.

<br>

I have a few tiny suggestions for the test comments (for brevity and to follow [style guidelines](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#use-the-passive-voice-recommend-do-not-require-never-say-things-are-simple)), so take a look when you get a chance :)

**Comment by kszczek** [comment]
All done!

**Comment by nate-thegrate** [comment]
Awesome, thanks @kszczek! We'll be able to merge once the PR has 2 approvals.

**Review by Piinks — COMMENTED** [review]
This LGTM. I was a little wary that we did not have an issue demonstrating this causing a problem, but it looks like a nice clean up.

From an offline chat with @nate-thegrate, the notification context can be null, it comes from the key for the gesture detector in ScrollableState: 
https://github.com/flutter/flutter/blob/793569f621f79119dd7cb2c82c403b5d52271946/packages/flutter/lib/src/widgets/scrollable.dart#L598

**Review by Piinks — APPROVED** [review]
