### PR TITLE
[Engine][Web] Fixed fallback font loading process

### LINKED ISSUE #165299: [WEB]Japanese punctuation and reading marks are misplaced.
### Steps to reproduce

1. Set up Flutter 3.29.
2. Set a long sentence in the text widget.
3. Display in Chrome.

### Expected results

`、` and `。` are just above the baseline as shown below.
The screenshots below show the results with Flutter 3.27.

Image

### Actual results

`、` and `。` are centered as follows

Image

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=3382819292297fa111b8b16cec047abd

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Text(
            '街の外れに位置する古びた図書館は、時代の流れから取り残されたように静かに佇んでいた。そこには古い本の匂いが漂い、訪れる人はまばらだった。だが、その図書館には誰も知らない秘密があった。\n'
            '\n'
            '毎晩、図書館が閉館すると、棚の奥にある古書がかすかに震え、表紙がゆっくりと開き始める。ページの間から淡い光が漏れ出し、その光に照らされて、小さな妖精たちが現れるのだった。彼らは本の中に宿る物語の守護者であり、物語が忘れられぬように毎晩語り合っていた。\n'
            '\n'
            'ある日、少年が偶然この秘密を見てしまった。彼は驚きのあまり声を失ったが、妖精たちは彼に優しく微笑みかけ、「君には僕らが見えるんだね」と話しかけた。その日から少年は毎晩図書館に通い、妖精たちから多くの物語を教わった。やがて少年は成長し、作家となり、図書館で聞いた物語を世界中に届けるようになった。',
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3 24D60 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.98.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/165299

Fixes a problem where the drawing does not render as expected if the value of `maxCodePointsCovered` is greater for an unsuitable language than for a font suitable for that language.

| before | after |
| :---:  | :---: |
|  |  |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]
It's always great to get the help of someone with a better understanding of the native language :)

Thank for contributing this fix!

File: engine/src/flutter/lib/web_ui/lib/src/engine/font_fallbacks.dart [hunk 1]
```diff
@@ -247,9 +247,27 @@ class FontFallbackManager {
   }
 
   NotoFont _selectFont(List<NotoFont> fonts) {
-    int maxCodePointsCovered = -1;
-    final List<NotoFont> bestFonts = <NotoFont>[];
     NotoFont? bestFont;
+    // Priority is given to fonts that match the languate
```
[the remark this answers is not in the document]
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/font_fallbacks.dart]: Thank you!

**Comment by mdebbar** [comment]
@koji-1009 here's the screenshot that was generated by the new golden test:

image

It looks like your "after" screenshot. Could you please confirm that it looks right so I can approve it?

**Comment by koji-1009** [comment]
@mdebbar 
Yes, that image is the expected result! Thank you!

File: engine/src/flutter/lib/web_ui/test/ui/fallback_fonts_golden_test.dart [hunk 2]
```diff
@@ -100,6 +103,41 @@ void testMain() {
       // TODO(hterkelsen): https://github.com/flutter/flutter/issues/71520
     });
 
+    test('will download Noto Sans JP if Japanease text is added in ja', () async {
```
Comment (harryterkelsen) [inline engine/src/flutter/lib/web_ui/test/ui/fallback_fonts_golden_test.dart]: nit: Japanease -> Japanese

**Review by harryterkelsen — APPROVED** [review]
LGTM with typo

File: engine/src/flutter/lib/web_ui/test/ui/fallback_fonts_golden_test.dart (hunk 2 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/test/ui/fallback_fonts_golden_test.dart]: Sorry! I fixed. [3786aba](https://github.com/flutter/flutter/pull/166212/commits/3786aba801c70ca7b34b71078eae53ebaa96b6c0)
