### PR TITLE
BorderTween.lerp supports null begin/end values

### LINKED ISSUE #71389: CupertinoNavigationBar crashes when setting border to null
Example main.dart:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Page 1"),
        border: null,
      ),
      child: Center(
        child: TextButton(
          child: Text("Next"),
          onPressed: () {
            Navigator.of(context)!.push<void>(CupertinoPageRoute(
              builder: (_) => Page2(),
              title: "Page 2",
            ));
          },
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Page 2"),
        border: null,
      ),
      child: Center(
        child: Text("Page 2"),
      ),
    );
  }
}
```

## Steps to Reproduce

1. Connect to iOS simulator and run app.
2. In the first screen, tap "Next"
3. In the second screen, tab "Back"

**Expected results:** No issues and animation works.

**Actual results:** App crashes, related to nnbd.

<details>
  <summary>Logs</summary>

```
The relevant error-causing widget was: 
  CupertinoApp file:///Users/may/Documents/project/me/test_navi/test_navi/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#0      BorderTween.lerp (package:flutter/src/widgets/implicit_animations.dart:157:54)
#1      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#2      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#3      _NavigationBarTransition.build.<anonymous closure> (package:flutter/src/cupertino/nav_bar.dart:1604:33)
#4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1528:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was: 
  CupertinoApp file:///Users/may/Documents/project/me/test_navi/test_navi/lib/main.dart:11:12

```
```
may@Tue test_navi % flutter analyze
Running "flutter pub get" in test_navi...                          490ms
Analyzing test_navi...                                                  
No issues found! (ran in 2.7s)
```
```
may@Tue ~ % flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64,
    locale en-VN)
    • Flutter version 1.24.0-10.2.pre at /Users/may/Library/Android/flutter
    • Framework revision 022b333a08 (11 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/may/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 6F6715B1-7A64-4D3E-A9C7-12CF410E119F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by HansMuller**
The existing BorderTween constructor doc said:
```dart
  /// The [begin] and [end] properties may be null; the null value
  /// is treated as having no border.
```
But the class's lerp() method assumed that both values were non-null.

Fixes https://github.com/flutter/flutter/issues/71389

### CODE REVIEW

**Review by xster — APPROVED** [review]

File: packages/flutter/lib/src/widgets/implicit_animations.dart [hunk 1]
```diff
@@ -152,7 +152,11 @@ class BorderTween extends Tween<Border> {
 
   /// Returns the value this variable has at the given animation clock value.
   @override
-  Border lerp(double t) => Border.lerp(begin, end, t)!;
+  Border? lerp(double t) {
+    if (begin == null || end == null)
+      return t < 0.5 ? begin : end;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/implicit_animations.dart:157]: @HansMuller Hey, Would like to ask why this is handled here instead of as follow:
```dart
Border? lerp(double t) => Border.lerp(begin, end, t);
```

Comment (HansMuller) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:157]: Good point, I think that would be simpler and clearer. Can you create a PR with the change?

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:157]: Ok

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:157]: update pr #79919
