### PR TITLE
[SwiftPM] Enable package resolution on xcodebuild commands

### LINKED ISSUE #185035: [SwiftPM] A resolved file is required when automatic dependency resolution is disabled
In https://github.com/flutter/flutter/pull/183747, we introduced some flags to try and speed up xcodebuild commands. However, looks like that fails if there is no Package.resolved yet.

```
xcodebuild: error: Could not resolve package dependencies:
  a resolved file is required when automatic dependency resolution is disabled and should be placed at
  /Users/vashworth/Development/experiment/flutter/swift_pm_add2app/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Pa
  ckage.resolved. Running resolver because requirements have changed.
```

### PR DESCRIPTION
**Pull request by vashworth**
Disabling it causes problems if it hasn't resolved before so let's just remove it. In actuality, it did not seem to improve build time anyways.

Fixes https://github.com/flutter/flutter/issues/185035.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

If this change needs to override an active code freeze, provide a comment explaining why. The code freeze workflow can be overridden by code reviewers. See pinned issues for any active code freezes with guidance.

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 1]
```diff
@@ -186,13 +186,14 @@ class XcodeProjectInterpreter {
   /// Using this method when running `xcodebuild` commands ensures that `xcrun` is used properly
   /// and that the Swift package cache is properly configured.
   ///
-  /// When [skipPackageResolution] is true, it uses arguments to attempt skipping any Swift package
-  /// resolution or updates. This should be false when running [prefetchSwiftPackages], so packages
-  /// should already be resolved, downloaded, and updated on subsquent `xcodebuild` commands.
+  /// When [skipPackageUpdatesAndValidation] is true, it uses arguments to attempt skipping any
+  /// Swift package updates and validation. This should be false when running
+  /// [prefetchSwiftPackages], so packages should already be resolved, downloaded, updated, and
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/xcodeproj.dart:191]: iirc from last PR this comment is incorrect (infinite recursion)? maybe move to `_xcodebuildProjectCommandArguments`? 

Maybe also rename `_xcodebuildProjectCommandArguments`? The naming here is a bit arbitrary (`xxxCommand` pre-fetches, but `xxxCommandArguments` doesn't pre-fetch)

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: I renamed and moved comments.

**Review by jmagman — APPROVED** [review]

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 2]
```diff
@@ -218,8 +218,7 @@ class XcodeProjectInterpreter {
       'xcodebuild',
       '-clonedSourcePackagesDirPath',
       cachePath,
-      if (skipPackageResolution) ...<String>[
-        '-disableAutomaticPackageResolution',
+      if (skipPackageUpdatesAndValidation) ...<String>[
         '-skipPackageUpdates',
         '-skipPackagePluginValidation',
         '-skipPackageSignatureValidation',
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/xcodeproj.dart:224]: Do these 3 help with saving the build time?

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart:224]: Yes, one of them does seem to help (although we're talking less than a second here). I have not narrowed down which.
