### PR TITLE
[flutter_tools] Use proper project name in templates

### LINKED ISSUE #96371: `flutter create` should create packages that follow brand guidelines
As a proper adjective, the first character of Flutter should be upper case when in:
- Pascal (upper camel-cased) contexts, e.g. "FlutterView", "TestWidgetsFlutterBinding"
- open compound words, e.g. "Flutter SDK", "Flutter value", "Flutter engine", "Flutter module",  "Flutter plugin", "Flutter package", "Flutter widgets"
- screaming contexts, e.g. "FLUTTER TEST FRAMEWORK", "FLUTTER_MY_APPLICATION_H_"
- places where a lower case letter would be technically inaccurate, e.g. "<Flutter/Flutter.h>"

The first character of "flutter" should be lower case when in:
- (lower) snake case contexts where underscores separate words such as Dart package names, e.g "flutter_test"
- (lower) camel cased contexts at the start or after "_", e.g. "flutterDir", "_flutterVersion"
- dash-case contexts, e.g. "flutter-intellij.jar", "flutter-facebook-auth"
- purely lower-cased contexts, e.g. "io.flutter.plugins.firebase.storage", "https://flutter.dev/"
- places where an upper case letter would be technically inaccurate, e.g. "flutter directory", "flutter repo", "flutter create", "flutter tool", "sdk: flutter"

Per [brand guidelines](https://docs.flutter.dev/brand), Flutter should not be used as a proper noun, though there are many (presumably allowed) exceptions within Flutter and its website, e.g "commitment to Flutter", "Flutter is an open source framework", "Flutter is supported and used by Google", "See how Google Pay uses Flutter", "Flutter is powered by Dart", "Install Flutter", "Announcing Flutter 2.8"

Although there is no brand guide, I expect that the same applies to both F's in FlutterFire: "flutterfire.git", "FlutterFire UI", "flutterfire_ui", etc.

Unfortunately, Flutter templates do not currently follow the rules above.

## Steps to Reproduce

`flutter create --template plugin`

**Expected results:** 

Code that is generated is consistent with the rules above.

**Actual results:** 

- "A new flutter plugin project." in pubspec.yaml and README.md.
- "The following section is specific to Flutter."
- "For help getting started with Flutter"
- "utility that Flutter provides"
- "The following section is specific to Flutter"

Issues from other templates:
- "Flutter needs it to communicate with the running application"
- "Flutter draws its first frame"

I would like to open a PR fixing this but am filing an issue first because I will need to reference an issue to open a PR. I think the change will be non-breaking and testing-exempt because it only affects documentation and package descriptions that are not generally tested, but note that it does affect Dart code where hard coded strings are located.

### PR DESCRIPTION
**Pull request by collinjackson**
- [x] Updates flutter_tools templates to generate files that properly use the project name
- [x] Updates apk_utils test function to deal with changes to templates

Cleaning up a few things while I'm here (reviewers, let me know if I should move these out to simplify the PR)
- [x] Updates help messages for flutter_tools to properly use the project name
- [x] Updates some places in the flutter_tools documentation to properly use the project name (non-exhaustively)

Fixes https://github.com/flutter/flutter/issues/96371

## Test plan

- [x] Presubmit tests pass (the ci.yaml one was stuck, but seems fine now)
- [x] Manually run the one devicelab test that is affected (gradle_plugin_light_apk_test). ~I am encountering an error "Could not find or load main class com.android.tools.apk.analyzer.ApkAnalyzerCli"  running it locally~. It passes locally.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this **PR is [test-exempt] (I think this is all documentation, but would be nice to get confirmation)**.
- [x] All existing and new tests are passing.

I tried running `flutter format` on `apk_utils.dart` but it changed the file too much, so I'm not planning on landing it.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -28,7 +28,7 @@ class UpgradeCommand extends FlutterCommand {
       ..addFlag(
         'force',
         abbr: 'f',
-        help: 'Force upgrade the flutter branch, potentially discarding local changes.',
+        help: 'Force upgrade the Flutter branch, potentially discarding local changes.',
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/commands/upgrade.dart:31]: Arguably `flutter` was correct here since it's the name of the repository? I could go either way.

File: packages/flutter_tools/templates/app/README.md.tmpl [hunk 2]
```diff
@@ -11,6 +11,6 @@ A few resources to get you started if this is your first Flutter project:
 - [Lab: Write your first Flutter app](https://flutter.dev/docs/get-started/codelab)
 - [Cookbook: Useful Flutter samples](https://flutter.dev/docs/cookbook)
 
-For help getting started with Flutter, view our
+For help getting started with Flutter development, view the
 [online documentation](https://flutter.dev/docs), which offers tutorials,
```
Comment (stuartmorgan) [inline packages/flutter_tools/templates/app/README.md.tmpl:15]: While you're right here, want to change this to `https://docs.flutter.dev`?

**Review by stuartmorgan-g — APPROVED** [review]
Sorry for the delay here, LGTM!

File: packages/flutter_tools/templates/app/README.md.tmpl (hunk 2 above)
Comment (collinjackson) [reply packages/flutter_tools/templates/app/README.md.tmpl]: Done.

**Comment by collinjackson** [comment]
I think this is ready to land, but we should probably confirm that the `gradle_plugin_light_apk_test` devicelab test is passing before landing. @stuartmorgan can I get your help on that? I wasn't able to run it locally, and even if it did pass locally it's not a guarantee that it would pass on CI.

**Comment by collinjackson** [comment]
@stuartmorgan Do you have any advice on how to resolve the customer_testing-linux test failures? It's hard for me to repro a golden failure because I don't have the same setup as the bots, and I'm having a hard time understanding how this PR affects argument decoders.

```
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following assertion was thrown while running async test code:
| Golden "goldens/argument_decoders_test.text.png": Pixel test failed, 0.10% diff detected.
| Failure feedback can be found at
| /tmp/flutter_customer_testing.flutter_packages.CZGIZR/tests/packages/rfw/test/failures
|
| When the exception was thrown, this was the stack:
| #0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:102:7)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
| ════════════════════════════════════════════════════════════════════════════════════════════════════
|
| 00:38 +57 -1: /tmp/flutter_customer_testing.flutter_packages.CZGIZR/tests/packages/rfw/test/argument_decoders_test.dart: golden checks [E]
|   Test failed. See exception logs above.
|   The test description was: golden checks
```

**Comment by stuartmorgan** [comment]
I'm just hitting this with one of my PRs. Based on some discussion in Discord, apparently the customer tests use the original branch point in some important way, so merging doesn't work and you have to instead rebase and force-push when this happens.

**Comment by collinjackson** [comment]
> I'm just hitting this with one of my PRs. Based on some discussion in Discord, apparently the customer tests use the original branch point in some important way, so merging doesn't work and you have to instead rebase and force-push when this happens.

Thanks! That fixed the customer tests. Perhaps we should document on the wiki somewhere that the bots require rebase/force-push rather than merging.

I'm now trying to figure out how to get the "Google testing" task to pass. It seems to be stuck in a "Pending" state. I can't manually re-run it, because the details link doesn't go to a publicly accessible URL. Any ideas? Should I try pushing the commits again?

**Comment by stuartmorgan** [comment]
> Perhaps we should document on the wiki somewhere that the bots require rebase/force-push rather than merging.

I filled an issue earlier today about fixing the script so merges work, but if I don't get to that soon we should definitely document it.

On the Google testing, my PR is in the same situation so I don't think pushing again will help. There may just be a backlog at the moment.
