### PR TITLE
Chip theme label style is merged with the provided label style

### LINKED ISSUE #70686: Chip label style doesn't inherit app theme font family
The issue only happens when providing custom properties to the chip's `labelStyle`. But for the case of overriding just the size or weight, the rest of the properties should be taken from the `ChipThemeData`.

## Steps to Reproduce

1. Provide a custom `fontFamily` to the app Theme.
2. Create a Chip with a custom `labelStyle` that changes the `fontSize`.

**Expected results:** 
The chip should use the font family from the app.

**Actual results:** 
The chip font family is null.

### Pull Request with a fix
#70687

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/david/fvm/versions/stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/david/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/david/Android/Sdk
    • Java binary at: /usr/lib64/jvm/java-1.8.0-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (IcedTea 3.17.0) (build
      1.8.0_272-b10 suse-2.1-x86_64)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android
      11 (API 30) (emulator)

```

</details>

### PR DESCRIPTION
**Pull request by davidmartos96**
## Description

When overriding certain properties to a `Chip`'s label style such as the font size or weight, the existing `ChipThemeData`'s label style is not being taken into account.
This is very noticeable when the app uses a different font family. The `ChipThemeData` has the correct font family, but when a `Chip` provides custom label style properties, the font family is not being used.

The PR makes use of the `TextStyle.merge` method to combine the provided label style with the global chip theme label style, which is not nullable.

## Related Issues

Fixes #70686

## Tests

I added a test with a check for this behavior.

## Without PR

image

## With PR

image

### Code for the sample above

https://github.com/flutter/flutter/issues/70686#issuecomment-728919982
(The font chosen here is for demonstration purposes, so that the comparison is more clear)

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/chip_test.dart [hunk 1]
```diff
@@ -1440,6 +1440,32 @@ void main() {
...
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildChip());
+
+    final TextStyle labelStyle = getLabelStyle(tester).style;
+
+    expect(labelStyle.fontFamily, 'MyFont');
```
Comment (pedromassangocode) [inline packages/flutter/test/material/chip_test.dart:1466]: Why not just:
`expect(getLabelStyle(tester).style.fontFamily, 'MyFont');`

Because the `labelStyle` is not going to be used anywhere else.

Comment (davidmartos96) [reply packages/flutter/test/material/chip_test.dart]: Yes, that makes the code a bit more concise. I've updated the PR.

File: packages/flutter/test/material/chip_test.dart [hunk 2]
```diff
@@ -1440,6 +1440,29 @@ void main() {
...
+          child: const Chip(
+            label: Text('Label'),
+            labelStyle: TextStyle(fontWeight: FontWeight.w200),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildChip());
+    expect(getLabelStyle(tester).style.fontFamily, 'MyFont');
```
Comment (chunhtai) [inline packages/flutter/test/material/chip_test.dart:1463]: can you also check the font weight is updated?

**Review by chunhtai — COMMENTED** [review]
LGTM, once the test is updated

File: packages/flutter/test/material/chip_test.dart (hunk 2 above)
Comment (davidmartos96) [reply packages/flutter/test/material/chip_test.dart]: @chunhtai I've updated the test

**Comment by chunhtai** [comment]
Hi @davidmartos96 can you rebase off latest master to fix the presubmit?

**Comment by davidmartos96** [comment]
@chunhtai Ok, just did so

**Review by chunhtai — APPROVED** [review]
LGTM
