### PR TITLE
Avoid NaN for shrinkwrapping viewports

### LINKED ISSUE #45866: [iOS] semantics - Failed assertion: line 1245 pos 12: 'value.isFinite'
When the exception was thrown, this was the stack: 
```
#2      SemanticsNode.rect= (package:flutter/src/semantics/semantics.dart:1245:12)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3588:11)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:137:32)
#6      ExpandIterator.moveNext (dart:_internal/iterable.dart:476:31)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
SemanticsNode#54(Rect.fromLTRB(0.0, 0.0, 280.7, 93.6), tags: [RenderViewport.twoPane]) (with SemanticsOwner#6fef9) tried to set a non-finite rect.
'package:flutter/src/semantics/semantics.dart':
Failed assertion: line 1245 pos 12: 'value.isFinite'

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.11.0, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

When using iOS scroll physics, we can get into a situation where the render viewport tries to subtract infinity from infinity, giving us a paint clip with `NaN` in it, which makes semantics unhappy.  This guards against that.

/cc @greatcallie

## Related Issues

fixes https://github.com/flutter/flutter/issues/45866

## Tests

I added the following tests:

Regression test for the case.  Without this change, this test throws an exception.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Greatcallie** [comment]
Cool. So how do I test it?

File: packages/flutter/test/rendering/viewport_test.dart [hunk 1]
```diff
@@ -1144,4 +1144,45 @@ void main() {
       '   its intrinsic dimensions.\n',
     );
   });
+
+  testWidgets('Handles Infinity - Infinity on iOS', (WidgetTester tester) async {
```
Comment (gaaclarke) [inline packages/flutter/test/rendering/viewport_test.dart]: Can you document how we end up with infinity - infinity?  It isn't clear to me how that is happening in the test.

File: packages/flutter/test/rendering/viewport_test.dart [hunk 2]
```diff
@@ -1144,4 +1144,45 @@ void main() {
...
+                  ),
+                ],
+              ),
+            ),
+          ],
+        ),
+      ),
+    );
+
+    expect(find.text('b'), findsOneWidget);
```
Comment (gaaclarke) [inline packages/flutter/test/rendering/viewport_test.dart]: A quick comment on how this is testing the math in the change too.

**Review by gaaclarke — APPROVED** [review]
Code looks good.  The test is a bit abstract, some documentation will help that.  Should we have a test that calls describeApproximatePaintClip directly too?

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 3]
```diff
@@ -510,11 +510,18 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
     }
 
     // Adjust the clip rect for this sliver by the overlap from the previous sliver.
+    final double startOfOverlap = child.constraints.viewportMainAxisExtent - child.constraints.remainingPaintExtent;
+    // We tried to subtract infinity from infinity and got NaN.
+    // This can happen when a RenderShrinkWrappingViewport is given infinite
+    // constraints.
+    if (startOfOverlap.isNaN) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/viewport.dart]: We should just check in the existing if above if child.constraints.viewportMainAxisExtent is infinite and then bail out there.

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 4]
```diff
@@ -510,11 +510,18 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
     }
 
     // Adjust the clip rect for this sliver by the overlap from the previous sliver.
+    final double startOfOverlap = child.constraints.viewportMainAxisExtent - child.constraints.remainingPaintExtent;
+    // We tried to subtract infinity from infinity and got NaN.
+    // This can happen when a RenderShrinkWrappingViewport is given infinite
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/viewport.dart]: Can you add a little more details here when this can happen? Somehwere along the lines: When a RenderShrinkWrappingViewport itself is inside another viewport it basically turns into a Column/Row, which has infinite space in the horizontal/vertical direction. This results in an infinite viewportMainAxisExtent. In that case, we can just return the size of the viewport (viewportClip) because the parent viewport will take care of the actual clipping.

File: packages/flutter/test/rendering/viewport_test.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/test/rendering/viewport_test.dart]: I've tried to add an explanation. Not sure if it's super clear but it's also touching on areas that are a bit tough to explain - I'm hoping @Hixie or @goderbauer can help fill that out if it's not clear enough

File: packages/flutter/test/rendering/viewport_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/rendering/viewport_test.dart]: I've added another test that more directly tests the method.  Leaving this one as well since we want it to work.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/viewport.dart]: Done

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 4 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/viewport.dart]: Tried to clarify a bit more  but before I saw this.  LMK if that works or if I should update further.

**Comment by dnfield** [comment]
@greatcaille if you view the instructions for pulling down this change you can test it  -or if you just update your local version of viewport.dart to match https://github.com/flutter/flutter/pull/46265/files#diff-4302a02cfc98c6e1745cc3ed2fed1b5cR516 it should start working for you.

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 5]
```diff
@@ -505,11 +505,18 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
   @override
   Rect describeApproximatePaintClip(RenderSliver child) {
     final Rect viewportClip = Offset.zero & size;
-    if (child.constraints.overlap == 0) {
+    // The child's viewportMainAxisExtent can be infinite when a
+    // RenderShrinkWrappingViewport is given infinite constraints.
+    //
+    // For example, a shrink wrapping render sliver may have infinite
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/viewport.dart]: I believe this is not correct. When the viewport has infinite constraints it does *not* scroll. It has infinite space to layout its children so there’s no need to scroll. Since it will not be scrolling there also will not be any overlap. 

At this point the viewport basically turns into a regular column/row (depending on orientation).

**Review by goderbauer — APPROVED** [review]
LGTM modulo some comments on the comments.

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 6]
```diff
@@ -505,11 +505,18 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
...
+    // constraints along the viewport's main axis but still end up scrollable
+    // because of its children. In such a case, even if the overlap is non-zero,
+    // we should just use the viewportClip - the start of the overlap is at
+    // double.infinity and so it is effectively meaningless.
+    if (child.constraints.overlap == 0 || !child.constraints.viewportMainAxisExtent.isFinite) {
       return viewportClip;
     }
 
-    // Adjust the clip rect for this sliver by the overlap from the previous sliver.
```
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/rendering/viewport.dart]: Adding this back, didn't mean to remove.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/viewport.dart]: It's not the viewport that has infinite constraints, it's the sliver (child).  Does that make things better?

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/viewport.dart]: I thought that the mainAxisExtent can only be infinite if the viewport itself also has infinite constraints and hence is not scrollable.

Comment (dnfield) [reply packages/flutter/lib/src/rendering/viewport.dart]: We talked offline and updated the comment a bit.  The real catch here is that the scroll physics can end up making this scroll just a little bit (e.g. bouncing scroll physics trying to move it up/down).

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Build status lies.  Landing this while I have a chance.
