### PR TITLE
fix(web_ui): use static whitelist for image codec tests

### LINKED ISSUE #182629: More systemically separate Flutter's image testing from Skia's images directory
### Help us understand the severity of this issue

- [x] breakage; unable to contribute or trigger builds will no workarounds
- [ ] inconvenient workarounds exist, but significant effort required
- [ ] needed for a Flutter team-wide priority (already agreed upon)
- [ ] nice-to-have; none of the above

### What do you need help with

The Skia CL https://skia-review.git.corp.google.com/c/skia/+/1138796 added a new resources/images/rgb24prof.bmp file.

Unfortunately, the Flutter Web tests (specifically codecs_test.dart) try to run through all the images in resources/images and decode them.

The new image, apparently, can't be decoded by Safari and is blocking the Skia roll into Flutter.

The two simplest things I can think of two prevent such blockages are to either have a separate directory of test images over in Flutter or allow-list the images Flutter consumes from within Skia's resources/images directory.

### PR DESCRIPTION
**Pull request by harryterkelsen**
The `codecs_test.dart` previously fetched all images from `/test_images/` dynamically. This caused flakiness when Skia added new images that were purposely undecodable or problematic for the Flutter web engine.

This change introduces a static whitelist of verified test images and removes the dynamic fetching logic. It also cleans up obsolete skip conditions for images that are no longer in the whitelist.

Fixes #182629

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart]: I think we should remove these too. WDYT?

**Review by mdebbar — APPROVED** [review]
LGTM

File: engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart
Comment (harryterkelsen) [reply engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart]: Yes, done

File: engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart [hunk 1]
```diff
@@ -147,10 +338,7 @@ Future<void> testMain() async {
         // This file causes Safari to crash with `EncodingError`.
         continue;
       }
-      if (testFile == 'b464333052.jpg') {
-        // This is an undecodable image used to test a Skia failure code path.
-        continue;
```
[the remark this answers is not in the document]
Comment (harryterkelsen) [reply engine/src/flutter/lib/web_ui/test/ui/codecs_test.dart:152]: Done
