### PR TITLE
Fix rotated image filter shader

### LINKED ISSUE #179918: imagefilter.shader broken when there's a rotation on ctm
## reproduction

<details>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_shaders/flutter_shaders.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Simple Shader Demo',
      theme: ThemeData(colorSchemeSeed: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool useImageFilter = false;
  double rotation = 0.0;
  ui.Image? image;

  @override
  void initState() {
    super.initState();
    _createImage();
  }

  Future<void> _createImage() async {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    final paint = Paint();

    // Draw a checkers pattern
    for (int i = 0; i < 2; i++) {
      for (int j = 0; j < 2; j++) {
        paint.color = (i + j) % 2 == 0 ? Colors.red : Colors.blue;
        canvas.drawRect(Rect.fromLTWH(i * 50.0, j * 50.0, 50.0, 50.0), paint);
      }
    }

    final picture = recorder.endRecording();
    final img = await picture.toImage(100, 100);
    setState(() {
      image = img;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Simple Shader Demo'),
        actions: [
          Row(
            children: [
              const Text('Use Paint.imageFilter'),
            ],
          ),
        ],
      ),
      body: image == null
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Row(
                        children: [
                          const Text('Filter:'),
                          Switch(
                            value: useImageFilter,
                            onChanged: (v) =>
                                setState(() => useImageFilter = v),
                          ),
                        ],
                      ),
                      Expanded(
                        child: Row(
                          children: [
                            const Text('Rot:'),
                            Expanded(
                              child: Slider(
                                value: rotation,
                                min: 0.0,
                                max: 6.28, // 2*PI approx
                                onChanged: (v) => setState(() => rotation = v),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                Expanded(
                  child: ShaderBuilder(
                    assetKey: 'shaders/gradient.frag',
                    (context, shader, child) => CustomPaint(
                      size: MediaQuery.of(context).size,
                      painter: ShaderPainter(
                        shader: shader,
                        useImageFilter: useImageFilter,
                        image: image!,
                        rotation: rotation,
                      ),
                    ),
                    child: const Center(child: CircularProgressIndicator()),
                  ),
                ),
              ],
            ),
    );
  }
}

class ShaderPainter extends CustomPainter {
  ShaderPainter({
    required this.shader,
    required this.useImageFilter,
    required this.image,
    required this.rotation,
  });

  final ui.FragmentShader shader;
  final bool useImageFilter;
  final ui.Image image;
  final double rotation;

  @override
  void paint(Canvas canvas, Size size) {
    shader.setFloat(0, 100); // resolution.x
    shader.setFloat(1, 100); // resolution.y

    final paint = Paint();

    canvas.translate(50, 50);
    canvas.rotate(rotation);
    canvas.translate(-50, -50);

    if (useImageFilter) {
      // Pass the shader as an ImageFilter.
      // The content drawn (the image) becomes the input texture for the shader.
      paint.imageFilter = ui.ImageFilter.shader(shader);
      canvas.drawImage(image, Offset.zero, paint);
    } else {
      // Bind the image explicitly to the shader's sampler 0
      shader.setImageSampler(0, image);
      paint.shader = shader;
      // Draw a rect filled with the shader (which samples the image)
      canvas.drawRect(Rect.fromLTWH(0, 0, 100, 100), paint);
    }
  }

  @override
  bool shouldRepaint(covariant ShaderPainter oldDelegate) {
    return oldDelegate.shader != shader ||
        oldDelegate.useImageFilter != useImageFilter ||
        oldDelegate.image != image ||
        oldDelegate.rotation != rotation;
  }
}

```

*gradient*
```glsl
#version 460 core

#include <flutter/runtime_effect.glsl>

precision mediump float;

uniform vec2 resolution;
uniform sampler2D uTexture;

out vec4 fragColor;

void main() {
  vec2 uv = FlutterFragCoord().xy / resolution;
  vec4 color = texture(uTexture, uv);
  
  // Transition to black based on X coordinate
  // 0.0 (left) = original color, 1.0 (right) = black
  vec3 finalColor = mix(color.rgb, vec3(0.0), uv.x);
  
  fragColor = vec4(finalColor, color.a);
}
```

*simple*
```glsl
#version 460 core

#include <flutter/runtime_effect.glsl>

precision mediump float;

uniform vec2 resolution;
out vec4 fragColor;

vec3 flutterBlue = vec3(5, 83, 177) / 255;
vec3 flutterNavy = vec3(4, 43, 89) / 255;
vec3 flutterSky = vec3(2, 125, 253) / 255;

void main() {
  vec2 st = FlutterFragCoord().xy / resolution.xy;

  vec3 color = vec3(0.0);
  vec3 percent = vec3((st.x + st.y) / 2);

  color =
      mix(mix(flutterSky, flutterBlue, percent * 2),
          mix(flutterBlue, flutterNavy, percent * 2 - 1), step(0.5, percent));

  fragColor = vec4(color, 1);
}
```

</details>

## observed (stable)

f6ff1529fd6d8af5f706051d9251ac9231c83407

https://github.com/user-attachments/assets/888210b9-3220-467a-b082-d3010ac703fe

## observed (main)

acdb2849c7e1d0a2cdf57d51e26cd58770e92023

https://github.com/user-attachments/assets/fe23c04a-668a-4d04-bf3d-efa5e10ddaa4

## expected

The imagefilter effect should rotate like it does on stable, but the rect should be sized to 100,100 at all times, like after when there is no rotation.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/179918

This blocks us from rerasterizing if there is a rotation on the imagefilter being drawn.  This restores the behavior before https://github.com/flutter/flutter/commit/c089837469a3676dd5dafe7886f6971aff2649c3 while keeping the golden introduced in that pr working.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc [hunk 1]
```diff
@@ -473,5 +473,56 @@ TEST_P(AiksTest, ClippedBackdropFilterWithShader) {
...
+
+  struct FragUniforms {
+    Size size;
+  } frag_uniforms = {.size = Size(size.width, size.height)};
+  auto uniform_data = std::make_shared<std::vector<uint8_t>>();
+  uniform_data->resize(sizeof(FragUniforms));
+  memcpy(uniform_data->data(), &frag_uniforms, sizeof(FragUniforms));
+
+  auto runtime_stages_result = OpenAssetAsRuntimeStage("gradient.frag.iplr");
+  ABSL_ASSERT_OK(runtime_stages_result);
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:488]: Super nit: would be nice to only have one variable with no `_result` suffix and use the dereference operator instead of `.value()`

**Review by walley892 — APPROVED** [review]
One extremely annoying comment

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:488]: ack, yea would be super annoying if used more than once.  putting that feedback in my pocket for next time
