### PR TITLE
Don't add empty OpacityLayer to the engine

### LINKED ISSUE #31517: Empty opacity crashes with debug_unopt engine
To reproduce, render `Opacity(opacity: 0.5, child: Container())` with `--local-engine=xxx_debug_unopt`. Fix incoming.

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/31517

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM.  I think there's potentially a Fuchsia FL-something open for this, I'll try to find it.

**Comment by dnfield** [comment]
Can we document this somehow?

It seems entirely reasonable to say the contract for Opacity is that it must have a child (to keep the layer tree smaller).  It may be difficult for consumers to discover that right now though, unless it's documented and I just missed it.

**Comment by liyuqian** [comment]
I'll add docs/comments to the `flutter::OpacityLayer` in the engine repo. It will be like "Don't push an Opacity layer with no children; painting an Opacity layer is very costly due to the saveLayer call".

@chinmaygarde : is there any other or better place for documenting the engine layers?

File: packages/flutter/lib/src/rendering/layer.dart [hunk 1]
```diff
@@ -1242,6 +1242,12 @@ class TransformLayer extends OffsetLayer {
 /// When debugging, setting [debugDisableOpacityLayers] to true will cause this
 /// layer to be skipped (directly replaced by its children). This can be helpful
 /// to track down the cause of performance problems.
+///
+// Try to avoid an [OpacityLayer] with no children. Painting an [OpacityLayer]
+// in the Flutter engine is very costly due to the creation of an offscreen
+// buffer and render target switches. If there's no child, having the
+// OpacityLayer or not has the same effect. If [OpacityLayer] has no child, its
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/layer.dart]: This seems off to me.  Why can't we make it cheap in the engine if there's no child?  E.g. if the engine gets an OpacityLayer with no layers, it's a no-op layer.

My understanding is that it's still beneficial to omit such layers from the engine side because it would (slightly) shrink the size of the layer tree and thus the real time it takes to traverse it.

Comment (liyuqian) [reply packages/flutter/lib/src/rendering/layer.dart]: Do you mean "Try to avoid an [OpacityLayer] with no children. Remove that layer if possible to save some tree walks." ?

I guess that we can make an empty OpacityLayer as a no-op in the engine. We're just not currently doing it, and instead doing FML_DCHECK the nonemptiness.

Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart]: I think it's fine for the contract to be `Don't send me an empty opacity layer`, but the explanation here makes me wonder why that is (e.g. why is it so easy to short-circuit it here and not in the engine?).  

Should we be pushing the short-circuiting even further up the call stack to the `pushLayer` call with opacity?  Should we add an assert to `OpacityLayer` that it has at least one child when it's pushed?

**Review by dnfield — COMMENTED** [review]
Would like to get further clarification before submitting this :)

File: packages/flutter/lib/src/rendering/layer.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart]: Talked offline - let's make this a doc comment (`///`) and your new text in there should be good.

**Comment by dnfield** [comment]
LGTM once doc is fixed.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 1 above)
Comment (liyuqian) [reply packages/flutter/lib/src/rendering/layer.dart]: Doc updated.

**Review by dnfield — APPROVED** [review]
