### PR TITLE
Fix intrinsic width of input decorator

### LINKED ISSUE #137937: TextField's intrinsic width isn't properly calculated when PrefixIcon or SuffixIcon are used
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Wrap a `TextField` with `IntrinsicWidth`.
2. Use `prefixIcon` or `suffixIcon`.
3. optional: use `suffix` so it is easier to tell the the input is too wide.

### Expected results

The `TextField` should be the correct width. When `suffix` is used, the suffix should be right next to the input's content.

### Actual results

The `TextField` is too wide. When `suffix` is used, the suffix has extra space between it and the input's content (as it does if you don't use `prefixIcon` or `suffixIcon`.

### Code sample

<details><summary>Code sample</summary>

[Example running in browser](https://zapp.run/edit/flutter-zz1q060bz1r0?entry=lib/main.dart&file=lib/main.dart)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App!!',
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: const MyHomePage(title: 'Flutter Example App'),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool showPrefixIcon = true;
  bool showPrefix = true;
  bool showSuffix = true;
  bool showSuffixIcon = true;
  TextEditingController textController =
      TextEditingController(text: "Input Text");

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
        padding: EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text('Show Prefix Icon', style: theme.textTheme.titleLarge),
                Checkbox(
                  value: showPrefixIcon,
                  onChanged: (value) => setState(() {
                    showPrefixIcon = value ?? false;
                  }),
                ),
              ],
            ),
            Row(
              children: [
                Text('Show Prefix', style: theme.textTheme.titleLarge),
                Checkbox(
                  value: showPrefix,
                  onChanged: (value) => setState(() {
                    showPrefix = value ?? false;
                  }),
                ),
              ],
            ),
            Row(
              children: [
                Text('Show Suffix', style: theme.textTheme.titleLarge),
                Checkbox(
                  value: showSuffix,
                  onChanged: (value) => setState(() {
                    showSuffix = value ?? false;
                  }),
                ),
              ],
            ),
            Row(
              children: [
                Text('Show Suffix Icon', style: theme.textTheme.titleLarge),
                Checkbox(
                  value: showSuffixIcon,
                  onChanged: (value) => setState(() {
                    showSuffixIcon = value ?? false;
                  }),
                ),
              ],
            ),
            IntrinsicWidth(
              child: TextField(
                controller: textController,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Input',
                  hintText: 'Input',
                  prefixIcon: showPrefixIcon ? Icon(Icons.add) : null,
                  prefix: showPrefix ? Text("\$") : null,
                  suffix: showSuffix ? Text("kg") : null,
                  suffixIcon: showSuffixIcon ? Icon(Icons.clear) : null,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Screenshot from 2023-11-06 21-57-07

Screenshot from 2023-11-06 21-57-14
bc6-799e-4b70-9adc-2113e24c50e2)
Screenshot from 2023-11-06 21-57-19
Screenshot from 2023-11-06 21-57-34

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.13.9, on Pop!_OS 22.04 LTS 6.5.6-76060506-generic, locale en_US.UTF-8)
    • Flutter version 3.13.9 on channel stable at /home/work/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/work/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.84.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Pop!_OS 22.04 LTS 6.5.6-76060506-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

### PR DESCRIPTION
**Pull request by neko-andrew**
Fix min intrinsic width of input decorator by removing left or right padding when `prefixIcon` or `suffixIcon` are used.

Fixes #137937.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by neko-andrew** [comment]
I'm unsure how to run a flutter app with my local changes so I can't get a screen shot of the fix.

**Comment by neko-andrew** [comment]
I would also like help on how I would write a test for this change.

**Comment by LongCatIsLooong** [comment]
> I would also like help on how I would write a test for this change.

I think you could check the location of the left-most component and the right-most component and see if the horizontal distance they cover is the same as the width `getMinIntrinsicWidth` reported.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -1224,13 +1224,13 @@ class _RenderDecoration extends RenderBox with SlottedContainerRenderObjectMixin
   @override
   double computeMinIntrinsicWidth(double height) {
     return _minWidth(icon, height)
-      + contentPadding.left
+      + (prefixIcon == null ? contentPadding.left : 0)
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:1227]: This doesn't look right when the writing direction is RTL?

Comment (neko-andrew) [reply packages/flutter/lib/src/material/input_decorator.dart]: Yeah you are correct. I have fixed this.

**Comment by neko-andrew** [comment]
I added a test which showed that I also had to fix the max intrinsic width.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -1224,25 +1224,25 @@ class _RenderDecoration extends RenderBox with SlottedContainerRenderObjectMixin
   @override
   double computeMinIntrinsicWidth(double height) {
     return _minWidth(icon, height)
-      + contentPadding.left
+      + (prefixIcon != null ? 0 : (textDirection == TextDirection.ltr ? contentPadding.left : contentPadding.right))
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/input_decorator.dart:1227]: nit: consider making `0` -> `0.0` per [style guidelines](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-double-literals-for-double-constants). Here and in other places in this PR.

**Review by Renzo-Olivares — APPROVED** [review]
Hi @neko-andrew, thanks for the contribution. This change LGTM just had a small nit. I also see similar logic to calculate the input width in `_layout`.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by neko-andrew** [comment]
Seems like "Google testing" failed. The details don't really provide any information. What does this mean?

**Comment by neko-andrew** [comment]
Can I get help with the failing "Google Testing"?

**Comment by LongCatIsLooong** [comment]
The golden changes LGTM.

**Comment by neko-andrew** [comment]
What is the process of getting these changes into a hot fix?
