### PR TITLE
Fixes the transition builder changing the Cupertino transition on Android.

### LINKED ISSUE #124850: Android app with CupertinoPageTransitionsBuilder() and MaterialPageRoute() can't use gesture way to back previous page with no error threw and stucked
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Set `theme` of `MaterialApp` as below:
```dart
@override
  Widget build(BuildContext context) {
    ThemeData theme = ThemeData(
      useMaterial3: true,
      pageTransitionsTheme: const PageTransitionsTheme(builders: {
        TargetPlatform.android: CupertinoPageTransitionsBuilder(),
      }),
    );

    return MaterialApp(
      theme: theme,
      home: const MercuriusSplashPage(),
    );
  }
```

2. Use `MaterialPageRoute` to change page:
```dart
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) => const MercuriusProfilePage(),
    ),
  );
```

3. At android device with 3-button nagivation bar, while using gesture way to back previous page, app stucks **with no error threw** and can't revice any more click event, you can only back previous page with back button in 3-button nagivation bar.

### Expected results

It's confused that it doesn't **throw a error** to figure out what happened. So I expect Flutter **throw a error** _or_ makes using gesture way to back previous page **work** at step1~2 situation.

### Actual results

4. At frist I change `platform` of `theme` as below, then the issues in step 3 disappered.
```dart
  ThemeData theme = ThemeData(
    useMaterial3: true,
    platform: TargetPlatform.iOS,
    pageTransitionsTheme: const PageTransitionsTheme(builders: {
      TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
    }),
  );
```
but it's not a good way abviousily.

5. Here's my resolution now:
- don't set `platform` and `pageTransitionsTheme` in theme
```dart
  ThemeData theme = ThemeData(
    useMaterial3: true,
  );
```
- change all `MaterialPageRoute` to `CupertinoPageRoute`
```dart
  Navigator.push(
    context,
    CupertinoPageRoute(
      builder: (context) => const MercuriusProfilePage(),
    ),
  );
```

6. Perfect!

### Code sample

<details><summary>Code sample(I write it in dartpad have no test in real device)</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        pageTransitionsTheme: const PageTransitionsTheme(builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
        }),
      ),
      home: const MyHomePage1(),
    );
  }
}

class MyHomePage1 extends StatelessWidget {

  const MyHomePage1({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('page1'),
      ),
      body: Center(
        child: TextButton(
          child: const Text('to page2'),
          onPressed:(){
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => const MyHomePage2(),
              ),
            );
          }
        )
      ),
    );
  }
}

class MyHomePage2 extends StatelessWidget {

  const MyHomePage2({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('page2'),
      ),
      body: const Center(
        child: Text('page2')
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.10, on Active code page: 65001

Microsoft Windows [版本 10.0.22621.1265], locale zh-CN)
    • Flutter version 3.7.10 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (10 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\28642\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\28642\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • V2055A (mobile)   • 30546631470061P • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows         • windows-x64    • Active code page: 65001

      Microsoft Windows [版本 10.0.22621.1265]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 111.0.5563.148
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 112.0.1722.39

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #124850.

Changes the fallback for the builder on Android. Before the error was from the platform being changed mid Cupertino transition to iOS. If a default builder wasn't set for iOS (which a developer developing only for Android might not), then it defaulted to the Zoom transition. Which changing the transition while on the fly caused issues.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 1]
```diff
@@ -755,12 +755,12 @@ class PageTransitionsTheme with Diagnosticable {
   ) {
     TargetPlatform platform = Theme.of(context).platform;
 
-    if (CupertinoRouteTransitionMixin.isPopGestureInProgress(route)) {
+    if (CupertinoRouteTransitionMixin.isPopGestureInProgress(route)) { // The trouble maker
       platform = TargetPlatform.iOS;
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:759]: @HansMuller seems like you added this logic in the original issue #21715. Outright removing it seems to fix the linked issue, but I'm assuming it covers an edge case I'm not thinking of?

With the code before in the case of this issue, if the theme did not define a builder for the iOS platform, it was defaulting to the zoom page transition, which I'm guessing didn't play nicely with the intended Cupertino page transitions set. The change below seems to fix it, but I'm tagging you to see if you remember what this code covers and if my fix would break that?

Comment (HansMuller) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:759]: I don't remember that hack (from https://github.com/flutter/flutter/pull/21715) however I guess it was possible to end up in a Cupertino pop transition even when the target platform is not iOS and the hack avoided switching to a different transition (based on the actual target platform). 

It looks like someone tried to remove the hack in July but that change had to be reverted due to failing internal tests: https://github.com/flutter/flutter/pull/114303. Plus the change in #114303 was slightly breaking, since it introduced an additional parameter in buildTransitions. That did seem like the right way to handle the problem.




If removing the 5-year-old hack doesn't cause any tests to fail, including all of the internal ones,

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 2]
```diff
@@ -765,14 +765,22 @@ class PageTransitionsTheme with Diagnosticable {
...
+    bool cupertinoTransitionInProgress = false;
 
     if (CupertinoRouteTransitionMixin.isPopGestureInProgress(route)) {
-      platform = TargetPlatform.iOS;
+      cupertinoTransitionInProgress = true;
+    }
+
+    PageTransitionsBuilder getTransitionBuilder() {
+      if (cupertinoTransitionInProgress) {
+        return const CupertinoPageTransitionsBuilder();
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:778]: Why are we forcing it to CupertinoPageTransitionsBuilder instead of looking up the iOS one in `builders` and only falling back to CupertinoPageTransitionsBuilder if there is none?

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 3]
```diff
@@ -765,14 +765,22 @@ class PageTransitionsTheme with Diagnosticable {
...
+      }
+      return builders[platform] ?? (platform == TargetPlatform.iOS ? const CupertinoPageTransitionsBuilder() : const ZoomPageTransitionsBuilder());
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:780]: nit: use switch/case for enums as per out style guide.

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 2 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:778]: I'm making the assumption that if a CupertinoPageTransition is in progress, than that's the builder we want to use. If it's not in progress, then we go to the builder, then the CupertinoPageTransitionsBuilder, depending on platform.

Comment (goderbauer) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:778]: I am not (yet) convinced that `CupertinoRouteTransitionMixin.isPopGestureInProgress(route)` returning true actually means there is a CupertinoPageTransition in progress. `CupertinoRouteTransitionMixin.isPopGestureInProgress` is implemented as `route.navigator.userGestureInProgress` - couldn't this also be set by any other custom transition? If one of those is used, we wouldn't want to change to `CupertinoPageTransitionsBuilder` mid-transition?

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 4]
```diff
@@ -765,14 +765,33 @@ class PageTransitionsTheme with Diagnosticable {
...
   ) {
-    TargetPlatform platform = Theme.of(context).platform;
+    final TargetPlatform platform = Theme.of(context).platform;
+
+    bool cupertinoTransitionInProgress = false;
 
     if (CupertinoRouteTransitionMixin.isPopGestureInProgress(route)) {
-      platform = TargetPlatform.iOS;
+      cupertinoTransitionInProgress = true;
+    }
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:774]: Could this be simplified to just

```suggestion
final bool cupertinoTransitionInProgress = CupertinoRouteTransitionMixin.isPopGestureInProgress(route);
```

**Comment by goderbauer** [comment]
(Analyzer is unhappy)

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 2 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:778]: I see what you are saying, but `CupertinoRouteTransitionMixin` is only added by `CupertinoPageTransitionsBuilder`. Previously it changed the platform to iOS, so theoretically we would have been getting other issues if it was changing the platform to iOS for anybody using neither `CupertinoPageTransitionsBuilder` nor `ZoomPageTransitionsBuilder`.

All that said, I only put in this logic with the boolean to cover whatever edge case setting the platform to iOS was covering before. However I have not been able to track down why it was there, and a previous PR that took this out entirely passed Google testing. I'm fine with just removing it and going straight to checking the `builders`.

Comment (goderbauer) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:774]: If nothing is breaking I would be in favor of taking this out.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: I was wrong, it does fail a test that changes the OS mid back gesture.

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 5]
```diff
@@ -771,8 +771,22 @@ class PageTransitionsTheme with Diagnosticable {
...
+        case TargetPlatform.fuchsia:
+        case TargetPlatform.windows:
+        case TargetPlatform.macOS:
+        case TargetPlatform.linux:
+          defaultBuilder = const ZoomPageTransitionsBuilder();
+      }
+      return builders[platform] ?? defaultBuilder;
+    }
+
+    final PageTransitionsBuilder matchingBuilder = getTransitionBuilder();
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:789]: With those fancy switch expressions this could probably simplify to something like:

```dart
final PageTransitionsBuilder matchingBuilder = builders[platform] ?? switch(platform) {
  TargetPlatform.iOS => const CupertinoPageTransitionsBuilder(),
  TargetPlatform.android || TargetPlatform.fuchsia || TargetPlatform.windows || TargetPlatform.macOS || TargetPlatform.linux => const ZoomPageTransitionsBuilder(),
}
```

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 6]
```diff
@@ -771,8 +771,22 @@ class PageTransitionsTheme with Diagnosticable {
       platform = TargetPlatform.iOS;
     }
 
-    final PageTransitionsBuilder matchingBuilder =
-      builders[platform] ?? const ZoomPageTransitionsBuilder();
+    PageTransitionsBuilder getTransitionBuilder() {
+      late PageTransitionsBuilder defaultBuilder;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:775]: late -> final. I think dart is smart enough here to figure out that the variable is never accessed before assignment.

**Review by goderbauer — APPROVED** [review]
LGTM
