### PR TITLE
[macOS] Use editing intents from engine

### LINKED ISSUE #85328: Can't navigate composing candidates list with arrow keys on Mac
When using composing keyboards on native Mac, the arrow keys can be used to navigate the composing tooltip.  In Flutter, the arrow keys continue to be intercepted by Flutter when the composing tooltip is visible, so it doesn't receive the keys.  We should not intercept the keys when composing is happening.

| Native Mac | Flutter Mac |
| --- | --- |
| text_edit_composing | text_edit_composing_flutter |

## Steps to reproduce

  1. Run any app with a text input, like the one given below, on a Mac.
  2. Set your keyboard to a composing keyboard, such as Chinese Pinyin.
  3. Type some text so that the composing tooltip appears, such as "ni".
  4. Attempt to navigate in the tooltip using the arrow keys.

Result: The cursor moves, not the selection in the composing tooltip.
Expected result: The selection in the composing tooltip moves.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by knopp**
| Before | After |
| --- | --- |
|Screenshot 2022-06-04 at 22 16 32|Screenshot 2022-06-04 at 22 16 59|

Fixes https://github.com/flutter/flutter/issues/85328

Requires https://github.com/flutter/engine/pull/33838 

This PR removes most of macOS specific text editing shortcut definitions and instead listens to appropriate selector messages from the engine, translating them into intents.

In order for text editing tests to work correctly, FlutterTester translates unhandled key events (only when `defaultTargetPlatform == macOS` and active text input) to selectors, similarly to how the engine would.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by knopp** [comment]
Couple of issues: 
1. We don't seem to have intents for PageUp and PageDown. Right now those are bounds to `ScrollToDocumentBoundaryIntent` and `ExpandSelectionToDocumentBoundaryIntent`, but that doesn't seem correct.
2. Escape key needs to be handled by the IME, which either hides the IME selection window or produces `cancelOperation` action if there is no IME selection window. We should probably have `CancelOperationIntent` for this that would be triggered by `cancelOperation` on macOS and escape key on other platforms / when not editing.

@LongCatIsLooong, @justinmc, any thoughts?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 1]
```diff
@@ -461,3 +487,78 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     );
   }
 }
+
+// These constants are based on NSStandardKeyBindingResponding method names
+final Map<String, Intent> _stringToIntent = <String, Intent>{
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: I have a WIP pull request before we went with the `isComposing` hack, it's a bit more ambitious than just sending Intents from macOS: https://github.com/flutter/flutter/pull/94961. I'm still not sure if it's a good idea to turn other commands into intents, we can give this a try first.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: The selector names are specific to iOS/macOS. The method call name `TextInputClient.performIntent` seems to be a little bit too generic for sending selector names to the framework. Or we could do the selector name -> Intent name translation in the engine.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 2]
```diff
@@ -461,3 +487,78 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+  'pageUpAndModifySelection': const ExpandSelectionToDocumentBoundaryIntent(forward: false),
+  'pageDownAndModifySelection': const ExpandSelectionToDocumentBoundaryIntent(forward: true),
+
+  // Escape when there's no IME selection
+  'cancelOperation': const DismissIntent(),
+};
+
+/// If this is a recognized editing intent name, performs the appropriate action.
+/// If the intent name is unknown, no action is invoked and `false` is returned.
+bool performEditingIntent(String intentName) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:547]: The function returns a `bool` but it doesn't seem to be used anywhere.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: I wasn't sure if this approach was viable, so I didn't want to spent time translating selectors to generic names. One approach would be to map selectors in engine into something more resembling intents that we have (ie. with collapse/forward attributes). I'll give it a try.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: Or we can rename `performIntent` to `performSelector`. Also it's a bit strange that the intents are sent via the focus system despite that we already have an established `TextInputConnection`.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 3]
```diff
@@ -258,6 +259,34 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+    // These keys should go to the IME when a field is focused, not to other
+    // Shortcuts.
+    const SingleActivator(LogicalKeyboardKey.arrowLeft): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.arrowRight): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.arrowUp): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.arrowDown): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.escape): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.space): const DoNothingAndStopPropagationTextIntent(),
+    const SingleActivator(LogicalKeyboardKey.enter): const DoNothingAndStopPropagationTextIntent(),
+    // The following key combinations have no effect on text editing on this
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:278]: What about all of the other shortcuts that were previously here for Mac, do you need DoNothingAndStopPropagationTextIntent for those too?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 4]
```diff
@@ -258,6 +259,34 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+    // platform:
+    //   * End
+    //   * Home
+    //   * Control + shift? + end
+    //   * Control + shift? + home
+    //   * Control + shift? + Z
+  };
+
+  // There is no complete documentation of iOS shortcuts. Use mac shortcuts for
+  // now.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:288]: This comment is no longer true.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: My gut says that the names sent from the engine should stay NSStandardKeyBindingResponding names.  I imagine a developer might want to handle a specific NSStandardKeyBindingResponding command and we don't want to hide that from them.  That's my thought.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 5]
```diff
@@ -461,3 +487,78 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     );
   }
 }
+
+// These constants are based on NSStandardKeyBindingResponding method names
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:491]: Nit: period

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 6]
```diff
@@ -461,3 +487,78 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+  'moveToEndOfDocument': const ExtendSelectionToDocumentBoundaryIntent(forward: true, collapseSelection: true),
+
+  'moveToLeftEndOfLineAndModifySelection': const ExtendSelectionToLineBreakIntent(forward: false, collapseSelection: false),
+  'moveToRightEndOfLineAndModifySelection': const ExtendSelectionToLineBreakIntent(forward: true, collapseSelection: false),
+  'moveToBeginningOfDocumentAndModifySelection': const ExtendSelectionToDocumentBoundaryIntent(forward: false, collapseSelection: false),
+  'moveToEndOfDocumentAndModifySelection': const ExtendSelectionToDocumentBoundaryIntent(forward: true, collapseSelection: false),
+
+  'transpose': const TransposeCharactersIntent(),
+
+  // TODO(knopp): Page Up/Down intents are missing
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:535]: I opened a PR for pageup/down in text editing here: https://github.com/flutter/flutter/pull/105497

**Review by justinmc — COMMENTED** [review]
This approach looks pretty straightfoward to me.  If @LongCatIsLooong is on board with doing this for now before something like https://github.com/flutter/flutter/pull/94961 then that sounds good to me.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:492]: > Or we can rename `performIntent` to `performSelector`. Also it's a bit strange that the intents are sent via the focus system despite that we already have an established `TextInputConnection`.

We had a discussion about this with @matthew-carroll and he made same point.  There could be `performSelector` method on TextInputClient, which could, if needed, translate it to an Intent and pass it to focus system. That way it would also be possible to handle actions that flutter text field is not interested in.

File: packages/flutter/lib/src/services/text_input.dart [hunk 7]
```diff
@@ -1126,6 +1126,10 @@ abstract class TextInputClient {
 
   /// Requests that the client remove the text placeholder.
   void removeTextPlaceholder() {}
+
+  /// Performs macOS specific selector from the NSStandardKeyBindingResponding
+  /// protocol.
+  void performSelector(String selectorName) {}
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:1132]: One more thing I just thought of: I want to make sure that this is something that we want to add to TextInputClient and not split out.  We've been having a bunch of discussion about this topic, see this design doc: https://docs.google.com/document/d/1OxDsf_eot7TlsRn57z-1_dGbvuqnMxO7QEGIAmOCZtA/edit

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 3 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:277]: We might need to. At very least those that are `_defaultAppleOsShortcuts`. Btw. I noticed now that there is a `ScrollIntent`. Not yet sure if it works for editing yet, but it seems like it should be returned for `PageUp/Down` selectors.

Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart]: I blocked all keys used to navigate IME popovers that are also declared in `_defaultAppleOsShortcuts`.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 8]
```diff
@@ -461,3 +483,68 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+  // TODO(knopp): Page Up/Down intents are missing (https://github.com/flutter/flutter/pull/105497)
+  'scrollPageUp:': const ScrollToDocumentBoundaryIntent(forward: false),
+  'scrollPageDown:': const ScrollToDocumentBoundaryIntent(forward: true),
+  'pageUpAndModifySelection': const ExpandSelectionToDocumentBoundaryIntent(forward: false),
+  'pageDownAndModifySelection:': const ExpandSelectionToDocumentBoundaryIntent(forward: true),
+
+  // Escape when there's no IME selection
+  'cancelOperation:': const DismissIntent(),
+  // Tab when there's no IME selection
+  'insertTab:': const NextFocusIntent(),
```
[the remark this answers is not in the document]
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:542]: Because that what would happen without this PR. The `NextFocusIntent` action has own shortcut (`_defaultShortcuts`) and default text editing shortcuts don't override this. With the exception of macO in this PR because we need to feed tab to `TextInputContext`.

Tab handling (and rendering) does need some wrong, but it feels like it is out of scope of this PR.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 9]
```diff
@@ -461,3 +483,68 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+  'insertBacktab:': const PreviousFocusIntent(),
+};
+
+/// Returns editing intent for selector from NSStandardKeyBindingResponding
+/// if the selector is recognized.
+Intent? intentForMacOSSelector(String selectorName) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:548]: nit: doesn't seem to need a separate function, maybe inline this?

File: packages/flutter_test/lib/src/event_simulation.dart [hunk 10]
```diff
@@ -902,8 +902,13 @@ Future<bool> simulateKeyDownEvent(
   String? platform,
   PhysicalKeyboardKey? physicalKey,
   String? character,
-}) {
-  return KeyEventSimulator.simulateKeyDownEvent(key, platform: platform, physicalKey: physicalKey, character: character);
+}) async {
+  final bool handled = await KeyEventSimulator.simulateKeyDownEvent(key, platform: platform, physicalKey: physicalKey, character: character);
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter_test/lib/src/event_simulation.dart:906]: I think we should just verify the selectors are handled correctly instead of trying to verify the key presses are handled correctly.

File: packages/flutter/lib/src/services/text_input.dart [hunk 11]
```diff
@@ -1125,6 +1125,10 @@ abstract class TextInputClient {
 
   /// Requests that the client remove the text placeholder.
   void removeTextPlaceholder() {}
+
+  /// Performs macOS specific selector from the NSStandardKeyBindingResponding
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/services/text_input.dart:1129]: If the app user has a custom selector defined in `DefaultKeyBinding.Dict`, the selector will be sent as-is to the framework right? So it's not necessarily from `NSStandardKeyBindingResponding`.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/text_input.dart:1129]: Also in `DefaultKeyBinding.Dict` you can remap a key to a selector + parameters. An example:
```
"~h" = ("insertText:", "hello word", "moveBackward:");
```

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/text_input.dart:1129]: Also using the current primary focus seems to be a reasonable default implementation.

File: packages/flutter_test/lib/src/event_simulation.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (knopp) [reply packages/flutter_test/lib/src/event_simulation.dart:906]: `TestWidgetsFlutterBinding.testTextInput` is not nullable. So if binding is `TestWidgetsFlutterBinding` the text input should be present. 

The purpose of this code is to turn unhandled key events into selectors, if text input is currently active, same way `FlutterTextInputPlugin` does it on macOS. There are no keyboard shortcuts defined for macOS anymore, everything is driven by selectors, so Flutter Tester must be able to simulate the environment, otherwise most text editing tests just fail on macOS.

That said, I don't know if `event_simulation` is the right place to do this.

File: packages/flutter/lib/src/services/text_input.dart (hunk 11 above)
Comment (knopp) [reply packages/flutter/lib/src/services/text_input.dart:1129]: I don't know if AppKit would delivery complete custom selectors to `doCommandBySelector:`. I can try it though.

`insertText:` is processed through `doCommandBySelector:` (and there is no argument other than selector there).

Comment (knopp) [reply packages/flutter/lib/src/services/text_input.dart:1129]: Nevermind, custom selectors are delivered. I'll update the comment.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/text_input.dart:1129]: Yeah I think it worked for me when I tried. But I didn't try a selector with a parameter list. The documentation I found didn't mention that either: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/TextDefaultsBindings/TextDefaultsBindings.html

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 9 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:489]: I made the table const and put it inside `intentForMacOSSelector`.

File: packages/flutter/lib/src/services/text_input.dart (hunk 11 above)
Comment (knopp) [reply packages/flutter/lib/src/services/text_input.dart]: Well, the signature of `doCommandBySelector:` only has one argument (the selector), so I don't see how parameters would work, but custom selectors certainly do.

File: packages/flutter/lib/src/services/text_input.dart [hunk 12]
```diff
@@ -1159,6 +1159,10 @@ abstract class TextInputClient {
 
   /// Requests that the client remove the text placeholder.
   void removeTextPlaceholder() {}
+
+  /// Performs macOS specific selector from the `NSStandardKeyBindingResponding`
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:1163]: "Performs the specified MacOS-specific selector..."

File: packages/flutter/lib/src/services/text_input.dart [hunk 13]
```diff
@@ -1159,6 +1159,10 @@ abstract class TextInputClient {
...
+  /// protocol or user specified selector from `DefaultKeyBinding.Dict`.
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:1164]: "protocol or the user-specified selector..."

File: packages/flutter/lib/src/services/text_input.dart [hunk 14]
```diff
@@ -1159,6 +1159,10 @@ abstract class TextInputClient {
...
+  void performSelector(String selectorName) {}
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_input.dart:1165]: Could this be more generic than text input?  Maybe it should have its own class instead of being a part of TextInputClient?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 15]
```diff
@@ -258,6 +259,30 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
   // platforms.
   static final Map<ShortcutActivator, Intent> _macShortcuts = <ShortcutActivator, Intent>{
+    const SingleActivator(LogicalKeyboardKey.keyX, meta: true): const CopySelectionTextIntent.cut(SelectionChangedCause.keyboard),
+    const SingleActivator(LogicalKeyboardKey.keyC, meta: true): CopySelectionTextIntent.copy,
+    const SingleActivator(LogicalKeyboardKey.keyV, meta: true): const PasteTextIntent(SelectionChangedCause.keyboard),
+    const SingleActivator(LogicalKeyboardKey.keyA, meta: true): const SelectAllTextIntent(SelectionChangedCause.keyboard),
+    const SingleActivator(LogicalKeyboardKey.keyZ, meta: true): const UndoTextIntent(SelectionChangedCause.keyboard),
+    const SingleActivator(LogicalKeyboardKey.keyZ, shift: true, meta: true): const RedoTextIntent(SelectionChangedCause.keyboard),
+
+    // On desktop these keys should go to the IME when a field is focused, not to other
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:269]: On all desktop platforms or only on Mac?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 16]
```diff
@@ -296,8 +321,8 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
 
     const SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true, meta: true): const ExpandSelectionToLineBreakIntent(forward: false),
     const SingleActivator(LogicalKeyboardKey.arrowRight, shift: true, meta: true): const ExpandSelectionToLineBreakIntent(forward: true),
-    const SingleActivator(LogicalKeyboardKey.arrowUp, shift: true, meta: true): const ExtendSelectionToDocumentBoundaryIntent(forward: false, collapseSelection: false),
-    const SingleActivator(LogicalKeyboardKey.arrowDown, shift: true, meta: true): const ExtendSelectionToDocumentBoundaryIntent(forward: true, collapseSelection: false),
+    const SingleActivator(LogicalKeyboardKey.arrowUp, shift: true, meta: true): const ExpandSelectionToDocumentBoundaryIntent(forward: false),
+    const SingleActivator(LogicalKeyboardKey.arrowDown, shift: true, meta: true): const ExpandSelectionToDocumentBoundaryIntent(forward: true),
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:325]: Why was `collapseSelection: false` removed?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 17]
```diff
@@ -461,3 +483,67 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     );
   }
 }
+
+/// Returns editing intent for selector from NSStandardKeyBindingResponding
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:487]: "Maps the selector from NSStandardKeyBindingResponding to the Intent if the selector is recognized."

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 18]
```diff
@@ -461,3 +483,67 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+    'scrollToBeginningOfDocument:': ScrollToDocumentBoundaryIntent(forward: false),
+    'scrollToEndOfDocument:': ScrollToDocumentBoundaryIntent(forward: true),
+
+    // TODO(knopp): Page Up/Down intents are missing (https://github.com/flutter/flutter/pull/105497)
+    'scrollPageUp:': ScrollToDocumentBoundaryIntent(forward: false),
+    'scrollPageDown:': ScrollToDocumentBoundaryIntent(forward: true),
+    'pageUpAndModifySelection': ExpandSelectionToDocumentBoundaryIntent(forward: false),
+    'pageDownAndModifySelection:': ExpandSelectionToDocumentBoundaryIntent(forward: true),
+
+    // Escape when there's no IME selection
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:542]: Period at the end.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:542]: By "no IME selection" do you mean no field is focused or no TextEditingValue.selection is collapsed?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 19]
```diff
@@ -461,3 +483,67 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
...
+    'cancelOperation:': DismissIntent(),
+    // Tab when there's no IME selection
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:544]: Period at the end.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 20]
```diff
@@ -461,3 +483,67 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     );
   }
 }
+
+/// Returns editing intent for selector from NSStandardKeyBindingResponding
+/// if the selector is recognized.
+Intent? intentForMacOSSelector(String selectorName) {
+  const Map<String, Intent> selectorToIntent = <String, Intent>{
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:490]: Nit: Should this map be declared outside of the method?  Maybe it doesn't matter.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 21]
```diff
@@ -3089,6 +3090,18 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     });
   }
 
+  @override
+  void performSelector(String selectorName) {
+    final Intent? intent = intentForMacOSSelector(selectorName);
+
+    if (intent != null) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3097]: Should we assert that the intent isn't null?  I'm thinking that somewhere at least a warning should be logged if no intent was found for the selector.  Or do we expect to be sent weird selectors from MacOS?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 22]
```diff
@@ -4240,7 +4253,16 @@ class _UpdateTextSelectionAction<T extends DirectionalCaretMovementIntent> exten
     }
 
     final _TextBoundary textBoundary = getTextBoundariesForIntent(intent);
-    final TextSelection textBoundarySelection = textBoundary.textEditingValue.selection;
+
+    // textBoundary selection is only updated after rebuild; If the text value is same,
+    // use selection from state which is more recent. This is necessary on macOS
+    // where alt+up sends moveBackward: and `moveToBeginningOfParagraph:` selectors at
+    // the same time.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:4260]: "`textBoundary`'s selection is only updated after rebuild; if the text is the same, use the selection from state, which is more recent. This is necessary on macOS where alt+up sends the `moveBackward:` and `moveToBeginningOfParagraph:` selectors at the same time."

**Review by justinmc — COMMENTED** [review]
Some more improvements here.  Thanks for following up on all this!

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 16 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:325]: Because on macOS the correct action is `ExpandSelectionToDocumentBoundaryIntent`, not `ExtendSelectionToDocumentBoundaryIntent`. And `ExpandSelectionToDocumentBoundaryIntent` has no `collapseSelection` property.

Note that cmd+shift+up on macOS is same as shift+home, they both result in `moveToBeginningOfDocumentAndModifySelection:` so the action needs to be same. shift+home already had the correct action (Expand).

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 18 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:542]: I meant the IME candidate selection popup. When there is a popup TextInputContext will eat the escape key (hiding the popup). If there is no popup, TextInputContext will produce `cancelOperation:` selector, which we map to `DismissIntent`.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 20 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:490]: I had it declared outside first and then was suggested to put it in the method (or I misunderstood the suggestion). I don't have strong feelings about this. If you do I can put it outside.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 21 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/editable_text.dart:3097]: Uses can define completely custom selectors in DefaultKeyBinding.Dict. Those will be passed along from TextInputContext. I'm not entirely sure what the point of it is, but it definitely shouldn't cause weird assertions.

File: packages/flutter/lib/src/services/text_input.dart (hunk 14 above)
Comment (knopp) [reply packages/flutter/lib/src/services/text_input.dart:1168]: The selector is sent from TextInputContext, which is only used through the TextInputClient.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 15 above)
Comment (knopp) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:269]: Only on Mac (the comment is inside _macShortcuts), but not on web on mac (hence "desktop").

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 20 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:490]: I don't, I'm happy with it inside :+1:

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 21 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3097]: Ah got it.  Agreed, we probably shouldn't warn/error in that case.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Probably should let @LongCatIsLooong give a final review as well.

File: packages/flutter_test/lib/src/test_text_input_key_handler.dart [hunk 23]
```diff
@@ -0,0 +1,158 @@
...
+      _shift = true;
+    } else if (key == LogicalKeyboardKey.alt ||
+        key == LogicalKeyboardKey.altLeft ||
+        key == LogicalKeyboardKey.altRight) {
+      _alt = true;
+    } else if (key == LogicalKeyboardKey.meta ||
+        key == LogicalKeyboardKey.metaLeft ||
+        key == LogicalKeyboardKey.metaRight) {
+      _meta = true;
+    } else {
```
Comment (dkwingsmt) [inline packages/flutter_test/lib/src/test_text_input_key_handler.dart:124]: Why no controls?

File: packages/flutter_test/lib/src/event_simulation.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter_test/lib/src/event_simulation.dart:906]: I think this process is reasonable. The entire test binding is to emulate a real device, and this new logic reflects our new model for the macOS system, which translates unhandled key events into selectors.

**Comment by dkwingsmt** [comment]
The change LGTM except for the one question.

File: packages/flutter_test/lib/src/test_text_input_key_handler.dart (hunk 23 above)
Comment (knopp) [reply packages/flutter_test/lib/src/test_text_input_key_handler.dart:124]: Seems like an oversight. Also this should have caught by tests. I'll look into this.

Comment (knopp) [reply packages/flutter_test/lib/src/test_text_input_key_handler.dart:238]: Indeed, control was missing :-/ The transpose test didn't fail, because, because Control+T did result in `transpose:` selector selector. The issue is that without checking for control Just `T` itself would result in `transpose:` as well. Fixed.

**Comment by dkwingsmt** [comment]
This PR will need https://github.com/flutter/engine/pull/33838 to be rolled into flutter/flutter to avoid breaking. This might take a few days.

**Comment by tgucio** [comment]
@dkwingsmt This should be aready in (https://github.com/flutter/flutter/pull/108602 merged).

**Comment by dkwingsmt** [comment]
@tgucio That was way faster than my past experience! Thanks for letting me know.

**Comment by dkwingsmt** [comment]
Is this PR ready to go? Shall we add auto-submit to it?

**Review by LongCatIsLooong — APPROVED** [review]
