### PR TITLE
Re-add the ability to return null in ListView.builder

### LINKED ISSUE #108705: Regression: ListView.builder's itemBuilder can no-longer return null since NNBD migration
It's a bit late to the party, since NNBD migration was done a long time ago.

But it seems that the migration process broke  ListView.builder's itemBuilder ability to return null;

## Steps to Reproduce

We used to be able to write the following:

```dart
ListView.builder(
  // no item count
  itemBuilder: (context, index) {
    if (condition) return null;
    return Item();
  }
)
```

**Expected results:**

Before NNBD migration, this code would render `Item()` until `condition` is true, at which point the list ends (similar to as it we reached the end of `itemCount`)

**Actual results:**

The code doesn't compile as `itemBuilder` doesn't allow returning `null` anymore.

___

Browsing through the git blames, it seems that this was removed by mistake.   
It probably didn't have a test and slipped through the review process because of the NNBD migration of `IndexedItemBuilder`. 

This issue https://github.com/flutter/flutter/issues/58371#issuecomment-638493007 in particular shows that returning null was a supported behavior.

Similarly, `SliverChildBuilderDelegate.build` (the delegate that implements `ListView.builder`) still allows returning `null`.
So returning `null` is still technically supported, just not with the `.builder` constructor

### PR DESCRIPTION
**Pull request by rrousselGit**
Fixes a possible regression during NNBD migration that removed the ability to return `null` in `ListView.builder`'s `itemBuilder`

fixes #108705

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
(from triage): Looks like some tests are failing on this, could you take a look and fix those up?

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 1]
```diff
@@ -1110,13 +1110,15 @@ class ListView extends BoxScrollView {
...
   /// or equal to zero and less than `itemCount`.
   ///
-  /// The `itemBuilder` should always return a non-null widget, and actually
-  /// create the widget instances when called. Avoid using a builder that
-  /// returns a previously-constructed widget; if the list view's children are
-  /// created in advance, or all at once when the [ListView] itself is created,
-  /// it is more efficient to use the [ListView] constructor. Even more
-  /// efficient, however, is to create the instances on demand using this
-  /// constructor's `itemBuilder` callback.
+  /// It is legal for `itemBuilder` to return `null`. If it does, [ListView]
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1113]: I am still not certain this is unintentional, especially since it is documented.

It was possible to return null in the past before null safety because there was no null safety.
It looks like GridView.builder also does not allow null.

**Comment by rrousselGit** [comment]
Thanks! Weird that Github action doesn't render them clearly. I'll look into it

File: packages/flutter/lib/src/widgets/scroll_view.dart (hunk 1 above)
Comment (rrousselGit) [reply packages/flutter/lib/src/widgets/scroll_view.dart:1113]: I've updated GridView.builder too, which I think has the same issue

Git says you wrote the documentation about this, so you're a far better source of truth than me.

But supporting null items is too simple to implement for it not to be voluntarily supported IMO.
This PR only modifies types after all. It doesn't modify logic in any way

Comment (rrousselGit) [reply packages/flutter/lib/src/widgets/scroll_view.dart:1113]: But considering this behavior is 2 years old now, it probably doesn't matter if it was intentional or not. Even if it was unintentionally removed, people don't seem to mind.

So maybe an alternate way of moving this forward would be to consider that this was never a feature to begin with, and to consider this PR a feature request.

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scroll_view.dart:1113]: Thanks! I am ok moving forward with this change based on our digging. It may be worth documenting the trade offs (or say, expected differences in behavior) of a `return null` strategy versus an item count.

Can you see if there are other cases of `IndexedItemBuilder` that need to be updated?

**Review by Piinks — COMMENTED** [review]
Thanks for the updates. So we have updated PageView, ListView, and GridView here, and it looks like AnimatedList, ReorderableList are confirmed not relevant.
It also looks like CupertinoTabScaffold specifies in the docs that tabBuilder cannot be null.

For the three cases that are changing to `NullableIndexedWidgetBuilder` can you add a templated doc that clarifies the behavior when using null to indicate the end of the list? The max scroll extent will not be accurate unless you are at the end of the list for example. This has caused confusion for a lot of folks in the past, so reintroducing this gives us a better chance to document it. :)

**Comment by rrousselGit** [comment]
Sorry, I missed your message!

I'll update the docs after the Flutter Vikings (1st of September).

**Comment by goderbauer** [comment]
(triage): @rrousselGit Do you have another chance to look at this now that Vikings is over?

**Comment by rrousselGit** [comment]
Oops, sorry for the delay. Done

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 2]
```diff
@@ -1110,13 +1110,21 @@ class ListView extends BoxScrollView {
...
-  /// created in advance, or all at once when the [ListView] itself is created,
-  /// it is more efficient to use the [ListView] constructor. Even more
-  /// efficient, however, is to create the instances on demand using this
-  /// constructor's `itemBuilder` callback.
+  /// {@template flutter.widgets.ListView.builder.itemBuilder}
+  /// It is legal for `itemBuilder` to return `null`. If it does, the scroll view
+  /// will stop calling `itemBuilder`, even if it has yet to reach `itemCount`.
+  /// By returning `null`, the max scroll extent will not be accurate
+  /// unless the user reaches the end of the scroll view. This can cause the
+  /// scrollbar to grow as the user scrolls.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1118]: Breadcrumbs would be helpful here:

```suggestion
  /// By returning `null`, the [ScrollPosition.maxScrollExtent] will not be accurate
  /// unless the user has reached the end of the [ScrollView]. This can also cause the
  /// [Scrollbar] to grow as the user scrolls.
```

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 3]
```diff
@@ -1110,13 +1110,21 @@ class ListView extends BoxScrollView {
...
+  /// If that is an issue, consider specifying `itemCount`.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1119]:
```suggestion
  /// For more accurate [ScrollMetrics], consider specifying `itemCount`.
```

**Review by Piinks — COMMENTED** [review]
This LGTM with nits, but it looks like CI is unhappy. Can you rebase with master to see if it resolves the failures?

File: packages/flutter/lib/src/widgets/page_view.dart [hunk 4]
```diff
@@ -675,6 +675,8 @@ class PageView extends StatefulWidget {
   /// [itemBuilder] will be called only with indices greater than or equal to
   /// zero and less than [itemCount].
   ///
+  /// {@template flutter.widgets.ListView.builder.itemBuilder}
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/page_view.dart:678]: This should be a `{@macro...` to embed the templated doc

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 5]
```diff
@@ -1114,13 +1114,21 @@ class ListView extends BoxScrollView {
...
+  /// For more accurate [ScrollMetrics], consider specifying `itemCount`.
+  /// {@endtemplate}
+  ///
+  /// The `itemBuilder` should always create the widget instances when called.
+  /// Avoid using a builder that returns a previously-constructed widget; if the
+  /// list view's children are created in advance, or all at once when the
+  /// [ListView] itself is created, it is more efficient to use the [ListView]
+  /// constructor. Even more efficient, however, is to create the instances on
+  /// demand using this constructor's `itemBuilder` callback.
   ///
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1132]: This needs an `/// {@endtemplate}`

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 6]
```diff
@@ -1742,6 +1752,8 @@ class GridView extends BoxScrollView {
   /// `itemBuilder` will be called only with indices greater than or equal to
   /// zero and less than `itemCount`.
   ///
+  /// {@template flutter.widgets.ListView.builder.itemBuilder}
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1755]: Same here re: @macro

**Review by Piinks — COMMENTED** [review]
Thanks for the updates! The docs test looks unhappy, but I've noted where the issues are below.

**Comment by rrousselGit** [comment]
Oh, my bad. Let me fix that

File: packages/flutter/lib/src/widgets/scroll_view.dart (hunk 5 above)
Comment (rrousselGit) [reply packages/flutter/lib/src/widgets/scroll_view.dart:1132]: There is one, it is in the paragraph above

This paragraph isn't part of the `@template`

**Comment by Piinks** [comment]
> Oh, my bad. Let me fix that

No worries, appeasing the CI gods can feel a bit tedious at times. Thanks for sticking with it!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by Piinks** [comment]
Ah we need a second reviewer, I'll seek one.

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 7]
```diff
@@ -1114,13 +1114,21 @@ class ListView extends BoxScrollView {
...
-  /// it is more efficient to use the [ListView] constructor. Even more
-  /// efficient, however, is to create the instances on demand using this
-  /// constructor's `itemBuilder` callback.
+  /// {@template flutter.widgets.ListView.builder.itemBuilder}
+  /// It is legal for `itemBuilder` to return `null`. If it does, the scroll view
+  /// will stop calling `itemBuilder`, even if it has yet to reach `itemCount`.
+  /// By returning `null`, the [ScrollPosition.maxScrollExtent] will not be accurate
+  /// unless the user has reached the end of the [ScrollView]. This can also cause the
+  /// [Scrollbar] to grow as the user scrolls.
+  /// For more accurate [ScrollMetrics], consider specifying `itemCount`.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/scroll_view.dart:1123]: Nit: Empty line of `///` above this.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/widgets/scroll_view.dart (hunk 7 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/scroll_view.dart:1123]:
```suggestion
  ///
  /// For more accurate [ScrollMetrics], consider specifying `itemCount`.
```

**Review by galiperkin — COMMENTED** [review]
Changes are reviewed. LGTM.
