### PR TITLE
[bugfix] SliverGeometry is not valid: The "layoutExtent" is negative

### LINKED ISSUE #39963: SliverGeometry is not valid: The "layoutExtent" is negative.
```
════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" is negative.

The RenderSliver that returned the offending geometry was: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...    scrollExtent: 0.0
...    hidden
...    layoutExtent: -56.0
...    maxPaintExtent: 56.0
...    hasVisualOverflow: true
...    cacheExtent: -56.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:711:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:720:13)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:745:6)
#3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1198:21)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1621:19)
...
The following RenderObject was being processed when the exception was fired: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...    scrollExtent: 0.0
...    hidden
...    layoutExtent: -56.0
...    maxPaintExtent: 56.0
...    hasVisualOverflow: true
...    cacheExtent: -56.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
RenderObject: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
    scrollExtent: 0.0
    hidden
    layoutExtent: -56.0
    maxPaintExtent: 56.0
    hasVisualOverflow: true
    cacheExtent: -56.0
  handle: SliverOverlapAbsorberHandle(56.0null)
...  child: _RenderSliverPinnedPersistentHeaderForWidgets#be3c6 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 56.0, hidden, maxPaintExtent: 56.0, hasVisualOverflow: true)
...      scrollExtent: 56.0
...      hidden
...      maxPaintExtent: 56.0
...      hasVisualOverflow: true
...    maxExtent: 56.0
...    child position: 0.0
...    child: RenderSemanticsAnnotations#9889a relayoutBoundary=up3
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...      semantics node: SemanticsNode#12
...        Rect.fromLTRB(0.0, 490.2, 414.0, 546.2)
...      semantic boundary
...      size: Size(414.0, 56.0)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#8e98d relayoutBoundary=up4
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...        size: Size(414.0, 56.0)
...        child: RenderPhysicalModel#72146 relayoutBoundary=up5
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...          size: Size(414.0, 56.0)
...          elevation: 0.0
...          color: Color(0xfff5f5f5)
...          shadowColor: Color(0xfff5f5f5)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" is negative.

When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:711:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:720:13)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:745:6)
#3      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:422:34)
#4      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
...
The following RenderObject was being processed when the exception was fired: RenderNestedScrollViewViewport#906a9 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=712.0)
...  layer: OffsetLayer#0d6db
...    offset: Offset(0.0, 0.0)
...  size: Size(414.0, 712.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: _NestedScrollPosition#2efd0(outer, offset: 0.0, range: 0.0..490.2, viewport: 712.0)
...  anchor: 0.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
RenderObject: RenderNestedScrollViewViewport#906a9 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=712.0)
  layer: OffsetLayer#0d6db
    offset: Offset(0.0, 0.0)
  size: Size(414.0, 712.0)
  axisDirection: down
  crossAxisDirection: right
  offset: _NestedScrollPosition#2efd0(outer, offset: 0.0, range: 0.0..490.2, viewport: 712.0)
  anchor: 0.0
  handle: SliverOverlapAbsorberHandle(56.0null)
...  center child: RenderSliverToBoxAdapter#60f53 relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 712.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 962.0 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 204.2, paintExtent: 204.2, maxPaintExtent: 204.2, cacheExtent: 204.2)
...      scrollExtent: 204.2
...      paintExtent: 204.2
...      maxPaintExtent: 204.2
...      cacheExtent: 204.2
...    child: RenderConstrainedBox#0b943 relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 204.2)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=204.2)
...      child: RenderStack#5f1a2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=204.2)
...        size: Size(414.0, 204.2)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        overflow: clip
...        child 1: _RenderScrollSemantics#c5882 relayoutBoundary=up1
...          needs compositing
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=204.2)
...          semantics node: SemanticsNode#33
...            Rect.fromLTRB(0.0, 0.0, 414.0, 204.2)
...          semantic boundary
...          size: Size(414.0, 204.2)
...        child 2: RenderPositionedBox#9d129 relayoutBoundary=up1 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=204.2)
...          size: Size(414.0, 204.2)
...          alignment: bottomCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
...  child 1: RenderSliverToBoxAdapter#c3d90 relayoutBoundary=up1
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 204.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 507.8, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 757.8 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 204.2, paintExtent: 204.2, maxPaintExtent: 204.2, cacheExtent: 204.2)
...      scrollExtent: 204.2
...      paintExtent: 204.2
...      maxPaintExtent: 204.2
...      cacheExtent: 204.2
...    child: RenderConstrainedBox#2c6c3 relayoutBoundary=up2
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 204.2)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=204.2)
...      child: _RenderScrollSemantics#66983
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=204.2)
...        semantics node: SemanticsNode#42
...          Rect.fromLTRB(0.0, 204.2, 414.0, 408.5)
...        semantic boundary
...        size: Size(414.0, 204.2)
...        child: RenderPointerListener#5c93c
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=204.2)
...          size: Size(414.0, 204.2)
...          behavior: deferToChild
...          listeners: signal
...  child 2: RenderSliverToBoxAdapter#8f0a6 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 408.5) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 303.5, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 553.5 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 176.6, paintExtent: 176.6, maxPaintExtent: 176.6, cacheExtent: 176.6)
...      scrollExtent: 176.6
...      paintExtent: 176.6
...      maxPaintExtent: 176.6
...      cacheExtent: 176.6
...    child: RenderConstrainedBox#fbf38 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 176.6)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=176.6)
...      child: RenderDecoratedBox#6fcb3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=176.6)
...        size: Size(414.0, 176.6)
...        decoration: BoxDecoration
...          color: Color(0xfff8f8f8)
...        configuration: ImageConfiguration(bundle: PlatformAssetBundle#bf5ca(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...        child: RenderFlex#8a473 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=176.6)
...          size: Size(414.0, 176.6)
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          verticalDirection: down
...  child 3: RenderSliverToBoxAdapter#ed741 relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 585.1) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 126.9, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 376.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 286.0, paintExtent: 126.9, maxPaintExtent: 286.0, hasVisualOverflow: true, cacheExtent: 286.0)
...      scrollExtent: 286.0
...      paintExtent: 126.9
...      maxPaintExtent: 286.0
...      hasVisualOverflow: true
...      cacheExtent: 286.0
...    child: RenderDecoratedBox#152d3 relayoutBoundary=up2
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 286.0)
...      decoration: BoxDecoration
...        color: Color(0xffffffff)
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#bf5ca(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...      child: RenderPadding#b6366 relayoutBoundary=up3
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...        size: Size(414.0, 286.0)
...        padding: EdgeInsets.zero
...        textDirection: ltr
...        child: RenderFlex#cd212 relayoutBoundary=up4
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...          size: Size(414.0, 286.0)
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          verticalDirection: down
...  child 4: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...      scrollExtent: 0.0
...      hidden
...      layoutExtent: -56.0
...      maxPaintExtent: 56.0
...      hasVisualOverflow: true
...      cacheExtent: -56.0
...    handle: SliverOverlapAbsorberHandle(56.0null)
...    child: _RenderSliverPinnedPersistentHeaderForWidgets#be3c6 relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...      geometry: SliverGeometry(scrollExtent: 56.0, hidden, maxPaintExtent: 56.0, hasVisualOverflow: true)
...        scrollExtent: 56.0
...        hidden
...        maxPaintExtent: 56.0
...        hasVisualOverflow: true
...      maxExtent: 56.0
...      child position: 0.0
...      child: RenderSemanticsAnnotations#9889a relayoutBoundary=up3
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...        semantics node: SemanticsNode#12
...          Rect.fromLTRB(0.0, 490.2, 414.0, 546.2)
...        semantic boundary
...        size: Size(414.0, 56.0)
...        child: RenderAnnotatedRegion<SystemUiOverlayStyle>#8e98d relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...          size: Size(414.0, 56.0)
...  child 5: RenderSliverFillRemaining#0231d relayoutBoundary=up1
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 221.8, overlap: 56.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 471.8 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 712.0, paintExtent: 221.8, maxPaintExtent: 221.8, cacheExtent: 221.8)
...      scrollExtent: 712.0
...      paintExtent: 221.8
...      maxPaintExtent: 221.8
...      cacheExtent: 221.8
...    child: _RenderScrollSemantics#f5037
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, h=221.8)
...      semantics node: SemanticsNode#8
...        Rect.fromLTRB(0.0, 546.2, 414.0, 712.0)
...      semantic boundary
...      size: Size(414.0, 221.8)
...      child: RenderPointerListener#da0c0
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=221.8)
...        size: Size(414.0, 221.8)
...        behavior: deferToChild
...        listeners: signal
...        child: RenderSemanticsGestureHandler#3504c
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=221.8)
...          size: Size(414.0, 221.8)
...          gestures: horizontal scroll
```

### PR DESCRIPTION
**Pull request by luckybilly**
## Description

related widgets:
- NestedScrollView
- SliverOverlapAbsorber

To reproduce the bug of issue,  please click this url: https://dartpad.dev/2630a061cf2632a1ffd6fb6c13c94e4c

try to change the value of `widgetCountBeforeSliverOverlapAbsorber` form `1` to `10`.
- 1: it works fine
- 10: got error message: `SliverGeometry is not valid: The "layoutExtent" is negative.`

## Related Issues

Fixes #39963

### CODE REVIEW

**Comment by luckybilly** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
@luckybilly Thanks for the contribution. In order to accept it, we require that all changes are tested. Can you add a test to your PR that ensures this never regresses in the future? Also, when you opened the PR you were asked to fill out a PR template that guided you through the requirements for a PR. Can you please fill out the entire template? Thanks.

/cc @Piinks for review.

**Review by Piinks — COMMENTED** [review]
Hi @luckybilly, Welcome! :tada: Thank you for the contribution! Please see @goderbauer's comments regarding getting this pull request ready for review.

I also noticed the bug you referenced is closed. I have re-opened it, but can you also provide context there for this change? The bug does not currently contain a reproduction of the crash, so if you are experiencing one, an example would help us determine if this is an appropriate fix for the problem.

**Comment by Piinks** [comment]
I just noticed the dartpad link. Thanks for that. I'll add it to the bug as well.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 1]
```diff
@@ -676,6 +676,13 @@ void main() {
     await gesture.up();
     debugDefaultTargetPlatformOverride = null;
   });
+
+
+  testWidgets('NestedScrollView and SliverOverlapAbsorber for PR #48947', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: Can you use a test name that is more descriptive of the bug rather than the PR number?

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 2]
```diff
@@ -692,3 +699,52 @@ class TestHeader extends SliverPersistentHeaderDelegate {
...
+          children: List<Widget>.generate(3, (_) => Container(
+            color: Colors.green[200],
+            height: 200,
+            margin: const EdgeInsets.all(20),
+          ),),
+        ),
+      ),
+    );
+  }
+}
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: Nit: there should be a newline at the end of the file

**Review by Piinks — COMMENTED** [review]
It looks like the analyzer is failing right now, can you address the concerns it found?

**Comment by luckybilly** [comment]
@Piinks The problems reported by the analyzer have been solved, thanks!

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 3]
```diff
@@ -692,3 +697,60 @@ class TestHeader extends SliverPersistentHeaderDelegate {
   @override
   bool shouldRebuild(TestHeader oldDelegate) => false;
 }
+
+class _TestLayoutExtentIsNegative extends StatelessWidget {
+
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: nit: remove extra whiteshace

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 4]
```diff
@@ -692,3 +697,60 @@ class TestHeader extends SliverPersistentHeaderDelegate {
...
+  Widget build(BuildContext context) {
+    return MaterialApp(
+      home: Scaffold(
+        appBar: AppBar(
+          title: const Text('Test'),
+        ),
+        body: NestedScrollView(
+          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
+            return <Widget>[
+              ...List<Widget>.generate(widgetCountBeforeSliverOverlapAbsorber, (_) => SliverToBoxAdapter(
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: nit: `=>` should only be used if the method fits on one line according to our style guide. Please change this to `{ }`

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 5]
```diff
@@ -692,3 +697,60 @@ class TestHeader extends SliverPersistentHeaderDelegate {
...
+                  ),
+                ),
+              )
+            ];
+          },
+          body: Container(
+            height: 2000,
+            margin: const EdgeInsets.only(top: 50),
+            child: ListView(
+              children: List<Widget>.generate(3, (_) => Container(
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: Same here.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 6]
```diff
@@ -676,6 +676,11 @@ void main() {
     await gesture.up();
     debugDefaultTargetPlatformOverride = null;
   });
+
+  testWidgets('NestedScrollView with SliverOverlapAbsorber in or out of the first screen', (WidgetTester tester) async {
+    await tester.pumpWidget(const _TestLayoutExtentIsNegative(1));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: Add `// Regression test for https://github.com/flutter/flutter/issues/39963.` above this line.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 7]
```diff
@@ -692,3 +697,60 @@ class TestHeader extends SliverPersistentHeaderDelegate {
...
+            return <Widget>[
+              ...List<Widget>.generate(widgetCountBeforeSliverOverlapAbsorber, (_) => SliverToBoxAdapter(
+                child: Container(
+                  color: Colors.red,
+                  height: 200,
+                  margin:const EdgeInsets.all(20),
+                ),
+              ),
+              ),
+              SliverOverlapAbsorber(
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart]: Is there an actual real-world use case for having a bunch of widget come before the SliverOverlapAbsorber?

Comment (luckybilly) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart]: I ran into this issue because I had TabBar & TabBarView at the bottom of my page for displaying different categories of goods, and many other widgets on top of them(e.g., horizontal ListView, AD banner, etc.)

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thank you for the contribution!
