### PR TITLE
Run secondary animation of previous route when using pushReplacement(…

### LINKED ISSUE #41680: Secondary animations should still run when using Navigator pushAndRemoveUntil() or pushReplacement()
My application makes use of TransitionRoute's secondaryAnimation to create a slide-on/slide-off effect for page navigation - the new route pushes the old one out of the way. However, when I wish to push a new "root" route using `pushAndRemoveUntil()`, the secondary animation of the previous head does not run. If pages are transparent, they will overlap.

This seems inconsistent with calling this action a "push...", as it does not have the same visual effect as a standard push(). The removing happens after the animation is complete, so it seems reasonable that the secondaryAnimation should run too.

## Steps to Reproduce

1. Use the following simplified route class:

```
class MyPageRoute<T> extends PageRouteBuilder<T> {
  IwPageRoute({
    WidgetBuilder bodyBuilder,
[main.dart.txt](https://github.com/flutter/flutter/files/3675564/main.dart.txt)


    RouteSettings settings,
  }) : super(
          pageBuilder: (context, animation, secondaryAnimation) => bodyBuilder(context),
          transitionsBuilder: (context, animation, secondaryAnimation, child) =>
            SlideTransition(
              position: Tween<Offset>(begin: Offset(1.0, 0), end: Offset.zero).animate(animation),
              child: SlideTransition(
                position: Tween<Offset>(begin: Offset.zero, end: Offset(-1.0, 0)).animate(secondaryAnimation),
                child: child),
            ),
          settings: settings,
        );
}
```
2. Push (`pushNamed`) a new route on top (both pages animate)
3. Push a new route to replace all others (only the new page animates)
`pushNamedAndRemoveUntil("name", (Route<dynamic> route) => false, arguments: arguments)`

(See attached example app)
[main.dart](https://github.com/flutter/flutter/files/3675616/main.dart.txt)

## Logs

The attached sample app produces no run-time logs

## Flutter Analyze

```
Analyzing example...                                                    
No issues found! (ran in 1.2s)
```

## Suggested resolution

I have found that adding the following at line  #1937 in navigator.dart (`pushAndRemoveUntil` after `newRoute.didChangeNext(null);`) resolves the issue for `pushAndRemoveUntil`. A similar fix would apply for `pushReplacement`:

```
if (precedingRoute != null) {
  precedingRoute.didChangeNext(newRoute);
}
```

## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Android/sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /opt/intellij/idea-IC-183.5912.21
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • I4213 • CQ3001V8FE • android-arm64 • Android 9 (API 28)

• No issues found!

```

### PR DESCRIPTION
**Pull request by joellurcook**
…) or pushAndRemoveUntil. Resolves #41680

## Description

Currently the navigator will not cause the secondary animation to run on the previous topmost route when using `pushReplacement()` or `pushAndRemoveUntil()`. This is inconsistent with the animation behaviour of a 'push', of which these methods are specific types.

This is a particular issue where a custom route transition is used, such as one that slides out the previous route as the new route slides in.

This PR ensures that the secondary animation of the previous topmost route is run.

## Related Issues

RESOLVED - Secondary animations should still run when using Navigator pushAndRemoveUntil() or pushReplacement() #41680

## Tests

I added the following tests:

In navigator_test.dart:
* replaceNamed triggers secondaryAnimation
* pushAndRemoveUntil triggers secondaryAnimation
* replaceNamed sets secondaryAnimation after transition with history change during transition

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR. 

The analyzer reports many problems on the master branch of flutter, unrelated to my PR.

- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). https://groups.google.com/forum/#!topic/flutter-announce/y0SvesRHlcE
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @joellurcook,
Welcome, and thank you for the contribution! 🎉 
It looks like there are a few issues here that are causing the pre-commit checks to fail:
> info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:96:19 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:96:28 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:96:39 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:99:26 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:99:35 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:99:46 • always_specify_types
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:99:66 • always_specify_types
   info • Prefer const with constant constructors • packages/flutter/test/widgets/navigator_test.dart:101:38 • prefer_const_constructors
   info • Prefer const with constant constructors • packages/flutter/test/widgets/navigator_test.dart:105:54 • prefer_const_constructors
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:478:16 • always_specify_types
  error • Missing type arguments for generic type 'SlideInOutPageRoute<dynamic>' • packages/flutter/test/widgets/navigator_test.dart:478:16 • implicit_dynamic_type
   info • Prefer final for variable declarations if they are not reassigned • packages/flutter/test/widgets/navigator_test.dart:482:12 • prefer_final_locals
   info • Prefer final for variable declarations if they are not reassigned • packages/flutter/test/widgets/navigator_test.dart:490:12 • prefer_final_locals
   info • Specify type annotations • packages/flutter/test/widgets/navigator_test.dart:518:16 • always_specify_types
  error • Missing type arguments for generic type 'SlideInOutPageRoute<dynamic>' • packages/flutter/test/widgets/navigator_test.dart:518:16 • implicit_dynamic_type
   info • Prefer final for variable declarations if they are not reassigned • packages/flutter/test/widgets/navigator_test.dart:522:12 • prefer_final_locals
   info • Prefer final for variable declarations if they are not reassigned • packages/flutter/test/widgets/navigator_test.dart:530:12 • prefer_final_locals

**Review by goderbauer — COMMENTED** [review]
This will be a subtile breaking change for people that relied on the fact that the animation doesn't run.

**Comment by Piinks** [comment]
> This will be a subtile breaking change for people that relied on the fact that the animation doesn't run.

Could this allow for perhaps the option to choose which behavior you would like? If so, you could leave the current behavior as the default, and it would not be breaking.

**Comment by joellurcook** [comment]
> > This will be a subtile breaking change for people that relied on the fact that the animation doesn't run.
> 
> Could this allow for perhaps the option to choose which behavior you would like? If so, you could leave the current behavior as the default, and it would not be breaking.

My concern with this is that it would be accepting broken behaviour as the default. Since these methods represent a 'push and...' transition, future developers should be able to expect a normal push animation and not be required to opt-in to it. Agreed that it might be a breaking change for some that opted to work around the problem rather than post a fix, but think default behaviour should be correct and favour future developers, in which case the break for the few may be necessary. Hopefully those that were relying on the broken feature should have accepted that it is likely to be fixed at some point in the future?

If we introduce optional behaviour, should this be unique to the 'push and...' operations? or for consistency should the `secondaryAnimation` be optional for other operations such as `push()` too? It feels contrary to the purpose of exposing the `secondaryAnimation` to transition builders to use if/as they see fit if there is an option somewhere else to determine if `secondaryAnimation` is just a dummy parameter - how would the transition builder know if it is a dummy and using it would have no effect? 

I'm happy to amend to introduce more functionality, just want to make sure we fix what is broken rather than treat it as an unintended feature.

**Comment by dellgreen** [comment]
if it is agreed that the expected default behaviour is currently broken, then if its made opt in (to not break current releases), provision should be made to change the default behaviour (i.e to opt out) with the next major iteration where breaking changes are would normally be allowed.

**Comment by joellurcook** [comment]
It is also unlikely that this will break anyone's code - if they are relying on the parameter having no effect, they would surely not be trying to use it. In which case, making the parameter they are not using live should make no difference.

**Comment by goderbauer** [comment]
I think it is reasonable to make this breaking change. In order to do so, please check the breaking change box in the PR description and follow the process linked from there.

File: packages/flutter/test/widgets/navigator_test.dart [hunk 1]
```diff
@@ -91,6 +91,24 @@ class OnTapPage extends StatelessWidget {
...
+    transitionsBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
+       return SlideTransition(
+      position: Tween<Offset>(begin: const Offset(1.0, 0), end: Offset.zero)
+          .animate(animation),
+      child: SlideTransition(
+          position:
+              Tween<Offset>(begin: Offset.zero, end: const Offset(-1.0, 0))
+                  .animate(secondaryAnimation),
+          child: child),
+    );},
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Nits: Looks like the style is a bit off here. Check out the wiki page [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo). 📖

File: packages/flutter/test/widgets/navigator_test.dart [hunk 2]
```diff
@@ -448,6 +466,91 @@ void main() {
     expect(find.text('B'), findsOneWidget);
   });
 
+  testWidgets('replaceNamed triggers secondaryAnimation', (WidgetTester tester) async {
+    final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
+      '/' : (BuildContext context) => OnTapPage(id: '/', onTap: () { Navigator.pushReplacementNamed(context, '/A'); }),
+      '/A': (BuildContext context) => OnTapPage(id: 'A', onTap: () { Navigator.pushReplacementNamed(context, '/B'); }),
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Style nit: These should be broken out to multi-line for readability.

File: packages/flutter/test/widgets/navigator_test.dart [hunk 3]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+      '/B': (BuildContext context) => const OnTapPage(id: 'B'),
+    };
+
+    await tester.pumpWidget(MaterialApp(
+      onGenerateRoute: (RouteSettings settings) {
+        return SlideInOutPageRoute<dynamic>(bodyBuilder: routes[settings.name]);
+      }));
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Nit: closing punctuation alignment should match opening - [link](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation)

File: packages/flutter/test/widgets/navigator_test.dart [hunk 4]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+      // routes: routes));
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Nit: Remove commented out code

File: packages/flutter/test/widgets/navigator_test.dart [hunk 5]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+    await tester.pumpAndSettle();
+    final Offset rootOffsetOriginal = tester.getTopLeft(find.text('/'));
+    await tester.tap(find.text('/')); // replaceNamed('/A')
+    // await tester.pumpAndSettle();
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Same here - remove commented out code

File: packages/flutter/test/widgets/navigator_test.dart [hunk 6]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+    final Offset rootOffset = tester.getTopLeft(find.text('/'));
+    expect(rootOffset.dx, lessThan(rootOffsetOriginal.dx));
+
+    Offset aOffsetOriginal = tester.getTopLeft(find.text('A'));
+    await tester.pumpAndSettle();
+    Offset aOffset = tester.getTopLeft(find.text('A'));
+    expect(aOffset.dx, lessThan(aOffsetOriginal.dx));
+
+    aOffsetOriginal = aOffset;
+    await tester.tap(find.text('A')); // replaceNamed('/B')
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: and here - remove commented out code

File: packages/flutter/test/widgets/navigator_test.dart [hunk 7]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+    expect(find.text('A'), isOnstage);
+    expect(find.text('B'), isOnstage);
+    aOffset = tester.getTopLeft(find.text('A'));
+    expect(aOffset.dx, lessThan(aOffsetOriginal.dx));
+  });
+
+  testWidgets('pushAndRemoveUntil triggers secondaryAnimation', (WidgetTester tester) async {
+    final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
+      '/' : (BuildContext context) => OnTapPage(id: '/', onTap: () { Navigator.pushNamed(context, '/A'); }),
+      '/A': (BuildContext context) => OnTapPage(id: 'A', onTap: () { Navigator.pushNamedAndRemoveUntil(context, '/B', (Route<dynamic> route) => false); }),
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Nit: Break out into multiple lines

File: packages/flutter/test/widgets/navigator_test.dart [hunk 8]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+      '/B': (BuildContext context) => const OnTapPage(id: 'B'),
+    };
+
+    await tester.pumpWidget(MaterialApp(
+      onGenerateRoute: (RouteSettings settings) {
+        return SlideInOutPageRoute<dynamic>(bodyBuilder: routes[settings.name]);
+      }));
+      // routes: routes));
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: remove commented out code

File: packages/flutter/test/widgets/navigator_test.dart [hunk 9]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+    await tester.pumpAndSettle();
+    final Offset rootOffsetOriginal = tester.getTopLeft(find.text('/'));
+    await tester.tap(find.text('/'));
+    // await tester.pumpAndSettle();
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: remove commented out code

File: packages/flutter/test/widgets/navigator_test.dart [hunk 10]
```diff
@@ -448,6 +466,91 @@ void main() {
...
+    final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{
+      '/' : (BuildContext context) => OnTapPage(id: '/', onTap: () { Navigator.pushNamed(context, '/A'); }),
+      '/A': (BuildContext context) => OnTapPage(id: 'A', onTap: () { Navigator.pushNamedAndRemoveUntil(context, '/B', (Route<dynamic> route) => false); }),
+      '/B': (BuildContext context) => const OnTapPage(id: 'B'),
+    };
+
+    await tester.pumpWidget(MaterialApp(
+      onGenerateRoute: (RouteSettings settings) {
+        return SlideInOutPageRoute<dynamic>(bodyBuilder: routes[settings.name]);
+      }));
```
Comment (Piinks) [inline packages/flutter/test/widgets/navigator_test.dart]: Nit: Closing punctuation alignment.

**Review by Piinks — COMMENTED** [review]
See some style nits below. This should be ok to land after the breaking change announcement ages a few more days. 👍

File: packages/flutter/test/widgets/navigator_test.dart (hunk 1 above)
Comment (joellurcook) [reply packages/flutter/test/widgets/navigator_test.dart]: Hopefully this one is resolved now - please let me know if still needs changes

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 11]
```diff
@@ -1881,19 +1881,19 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
     newRoute.install(_currentOverlayEntry);
     _history[index] = newRoute;
     newRoute.didPush().whenCompleteOrCancel(() {
-      // The old route's exit is not animated. We're assuming that the
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: This comment is still true. When the route is removed, that removal is not animated.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 12]
```diff
@@ -1881,19 +1881,19 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
-      // new route completely obscures the old one.
       if (mounted) {
         oldRoute
           ..didComplete(result ?? oldRoute.currentResult)
           ..dispose();
+        if (index > 0) {
+          _history[index - 1].didChangeNext(newRoute);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: When the push animation has completed, the route history may look differently and the index computed before the transition started may not be correct anymore.

Please add a test for this scenario as well to make sure that the correct routes are notified in this case.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 11 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/navigator.dart]: Maybe move the comment inside the if, though.

File: packages/flutter/test/widgets/navigator_test.dart [hunk 13]
```diff
@@ -91,6 +91,31 @@ class OnTapPage extends StatelessWidget {
   }
 }
 
+class SlideInOutPageRoute<T> extends PageRouteBuilder<T> {
+  SlideInOutPageRoute({WidgetBuilder bodyBuilder}) : super(
+    pageBuilder: (BuildContext context, Animation<double> animation,
+      Animation<double> secondaryAnimation) {
+        return bodyBuilder(context);
+      },
+    transitionsBuilder: (BuildContext context, Animation<double> animation,
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_test.dart]: formatting nit: just leave this on one line for easier readability.

File: packages/flutter/test/widgets/navigator_test.dart [hunk 14]
```diff
@@ -91,6 +91,31 @@ class OnTapPage extends StatelessWidget {
   }
 }
 
+class SlideInOutPageRoute<T> extends PageRouteBuilder<T> {
+  SlideInOutPageRoute({WidgetBuilder bodyBuilder}) : super(
+    pageBuilder: (BuildContext context, Animation<double> animation,
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_test.dart]: formatting nit: just leave this on one line for easier readability.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 12 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: I have made a change to remove the use of the index value, instead reusing reference to the relevant route itself.
However, I'm struggling to write a test for this - if I push a route during the replace animation, the index used previously is still correct (test won't fail before my amendment). If I try pop a route, the popped route will be the one that this PR affects (nothing left to test). Any suggestions?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/navigator.dart]: Could you use removeRoute [1] to remove something lower in the stack? That should change indexes.

[1] https://master-api.flutter.dev/flutter/widgets/NavigatorState/removeRoute.html

Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: That did it - thank you. I have added the test as requested. I also had to refrain from using pop() to test the secondaryAnimation states as pop() re-creates the animation proxies.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 15]
```diff
@@ -1881,19 +1881,23 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
     newRoute.didPush().whenCompleteOrCancel(() {
-      // The old route's exit is not animated. We're assuming that the
-      // new route completely obscures the old one.
       if (mounted) {
+        // The old route's exit is not animated. We're assuming that the
+        // new route completely obscures the old one.
         oldRoute
           ..didComplete(result ?? oldRoute.currentResult)
           ..dispose();
+        final int newIndex = _history.indexOf(newRoute);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: Is it guaranteed that newRoute is still in the history at this point? What happens if you pop it while the push animation is still ongoing? Would be good to have a test for this as well.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 16]
```diff
@@ -1881,19 +1881,23 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+        final Route<dynamic> precedingRoute = newIndex > 0 ? _history[newIndex - 1] : null;
+        if (precedingRoute != null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: This probably reads a little better as:

```dart
if (newIndex > 0) {
  final Route<dynamic> precedingRoute = _history[newIndex - 1];
  precedingRoute.didChangeNext(newRoute);
  newRoute.didChangePrevious(precedingRoute);
}
```

File: packages/flutter/test/widgets/navigator_test.dart [hunk 17]
```diff
@@ -448,6 +473,161 @@ void main() {
     expect(find.text('B'), findsOneWidget);
   });
 
+  testWidgets('replaceNamed sets secondaryAnimation after transition with history change during transition', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_test.dart]: This test doesn't do anything with replaceNamed?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 15 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: In that case, newIndex is -1 and no attempt is made to call didChangeNext or didChangePrevious on transition completion. This is made slightly clearer by your suggested amendment below.
I've added a test to reproduce this use case, mainly to ensure that no exception is created. I cannot easily test the (lack of) proxy of the removed newRoute animation to the preceding route's secondaryAnimation as on completion the newRoute animation is disposed. I'm happy to amend the test if you can think of a better approach.

File: packages/flutter/test/widgets/navigator_test.dart (hunk 17 above)
Comment (joellurcook) [reply packages/flutter/test/widgets/navigator_test.dart]: Apologies - that was poor naming of the tests. Changed to pushReplacement.

**Comment by joellurcook** [comment]
Update of the branch resulted in a failing test in routes_test.dart. Would appreciate any feedback on the addition to navigator to resolve the fail - both the replaced route and the preceding route secondary animations are now updated. This results in the preceding route secondaryAnimation being a TrainHoppingAnimation, required for when the preceding route is still visible when the replacement happens on the history head. Hopefully this is correct.

**Comment by goderbauer** [comment]
I don't fully understand you last comment. Seems like all tests are passing now?

**Comment by joellurcook** [comment]
Yes all tests passing now - hopefully nearly being able to get this on master.

To try explain my last comment better... if you have a stack A, on which you push B, then replace B with C (all before the B push animation is finished)...

Before the PR = A `secondaryAnimation` was updated (via a `TrainHoppingAnimation`) to proxy C `animation`, B was unaffected 

My original PR = B `secondaryAnimation` was updated to proxy C `animation`, A unaffected

Now = both. A `secondaryAnimation` proxies C `animation` (via `TrainHoppingAnimation`), AND B `secondaryAnimation` proxies C `animation`

Which seems right to me :)

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 18]
```diff
@@ -1883,19 +1883,26 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+          precedingRoute.didChangeNext(newRoute);
+          newRoute.didChangePrevious(precedingRoute);
+        }
       }
     });
     newRoute.didChangeNext(null);
+    oldRoute.didChangeNext(newRoute);
     if (index > 0) {
       _history[index - 1].didChangeNext(newRoute);
-      newRoute.didChangePrevious(_history[index - 1]);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: Why do we no longer need to notify previous?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 15 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: I am still not quite understand what is the use case this code is trying to cover. I also tried running the test without this part of code, and it is still passing. It seems like the test does not reproduce this use case.

**Comment by Piinks** [comment]
Our breaking change policy has been updated as of a few days ago. We'll need to make sure this follows the new policy before it can land. https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: Fair point, it could still have a previous notification - I'll add that back in, though the previous will now be `oldRoute` (the removing route), which is changed to the preceding route on completion of the push.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 15 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: When replacing a route, the 'previous' of the new route is initially the route being replaced. This should be changed once the push is complete, hence this code. The 'next' of the preceding route is also updated (though this is probably already set and unchanged a few lines down anyway). As per the discussion above, the new route may have been removed, so we check it is there first.

If you comment out the check, tests fail. If you break-point or add debug prints to the if-clause, the code is only run when appropriate. Changing the previous of  `newRoute` currently doesn't do much, and is therefore not easy to test, but it is correct to call it in case later developments make this action more important. Also note that the original code did not test  this action either - you could anyway have passed tests by removing it.

**Comment by joellurcook** [comment]
Hi @Piinks. I think the change to breaking change policy might actually help this PR. Based on discussion before, I believe this PR probably falls into this category now:

> Changes that don't break any tests and which, while technically breaking, are in our judgement unlikely to cause much trouble. We will pretend that such changes are not breaking changes and make them without any effort to prevent breakages.

The change doesn't brake any tests (all tests involved in this PR are entirely new) and is unlikely to create anyone any issues (only if you were using a secondaryAnimation parameter that you were relying on not being active).

What do you think?

**Comment by chunhtai** [comment]
We are currently working on a navigator refactoring. This issue will be fixed as part of the refactoring as well. We would suggest to wait for the refactoring to land instead.
This is the refactoring pr.
https://github.com/flutter/flutter/pull/44930/files

@joellurcook  Would you mind if we close this one now?

**Comment by joellurcook** [comment]
I don’t feel that simply closing this PR would be very pragmatic...

Whilst I welcome any further improvements, my PR is a minor fix to the existing system, and is ready to land and deliver benefit now. How confident are you that the redesign will land in the near future? Given how long my minor PR is taking to be approved, I worry how long a “major” redesign may take. Can we not land this PR and let it be replaced when you are ready? Resolving this issue is integral to our product.

It also seems good practice to me to integrate the new tests found in this PR ahead of any redesign, so that any new implementation is bound by them, and not just an intention to introduce the same functionality.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 15 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: I thought this case is covered by line 1904? where the index - 1 will be the new precedingRoute?
```dart
if (index > 0) {	  
      _history[index - 1].didChangeNext(newRoute);	
      newRoute.didChangePrevious(_history[index - 1])
}
```
or am i missing something?

File: packages/flutter/test/widgets/navigator_test.dart [hunk 19]
```diff
@@ -448,6 +473,207 @@ void main() {
...
+      }
+    ));
+    await tester.pumpAndSettle();
+    await tester.tap(find.text('/'));
+    await tester.pumpAndSettle();
+    await tester.tap(find.text('A'));
+    await tester.pumpAndSettle();
+    await tester.tap(find.text('B'));
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 200));
```
Comment (chunhtai) [inline packages/flutter/test/widgets/navigator_test.dart]: can you check the A's secondanimation.value equals to some expected value?

**Review by chunhtai — COMMENTED** [review]
Sorry for taking so long to get back to this pr. Although we can not guarantee when we will land the refactoring, we are currently actively working on that pr. And yes, I think it will be good to have these tests even though the code might end up being removed. My original intention was to inform you that the fix in this pr will likely being overwritten when the refactoring landed. However, you are still welcome to proceed with this pr if you are ok with above situation.

Note that even if you end up not proceeding with this pr, I will still like to cooperate the tests in this pr with my refactoring pr.

**Comment by goderbauer** [comment]
@chunhtai Can you verify that the tests from this PR pass on the Navigator refactoring?

**Comment by chunhtai** [comment]
> @chunhtai Can you verify that the tests from this PR pass on the Navigator refactoring?

yes, i have verified that

File: packages/flutter/test/widgets/navigator_test.dart (hunk 19 above)
Comment (joellurcook) [reply packages/flutter/test/widgets/navigator_test.dart]: Extra check added as requested.

As regards newIndex... it is possible that the index of the new route could change during the animation. Line ~1904 associates the preceding route with the new route at the point of pushing. Line ~1890 occurs after the animation and ensures that the new preceding route (if different) is similarly associated.
It is necessary to do the former if multiple push animations coincide, and the latter to ensure we finish in a valid state.

**Comment by joellurcook** [comment]
HI. I would prefer to continue with this PR. My driving concern is to get secondary animations working as quickly as possible so that I can use it in our product. If that means my code is overwritten shortly after, that's fine provided the functionality required by this PR's tests is still there.

File: packages/flutter/test/widgets/navigator_test.dart (hunk 19 above)
Comment (chunhtai) [reply packages/flutter/test/widgets/navigator_test.dart]: I see we have different behavior on whether we notify the route before or after transition. push/replace/pop/pushReplacement notify before the transition, while pushAndRemoveUntil notify after transition. This is problematic since it might notify the wrong route. This pr change pushReplacement and pushAndRemoveUntil to notify both before and after the transition which seems wrong since it will always double notify preceding route.
I believe the intention is to only notify before the transition begin. If index change after the transition, whoever trigger the change should re-notify the route correctly.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 15 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: We should only notify once, either before or after. Otherwise, we might notify the precedingRoute twice if the new precedingRoute and old precedingRoute happens to be the same

**Comment by goderbauer** [comment]
@joellurcook Looks like @chunhtai left some comments on the code. Do you still plan to get back to this?

**Comment by joellurcook** [comment]
@chunhtai yes, on review I agree that it is probably wrong to notify after the transition. Since `pushAndRemoveUntil()` already had the mechanism to notify after the transition, I carried it across into `pushReplacement()`. I was reluctant to remove it from `pushAndRemoveUntil() ` as I do not know why it was put there in the first place other than that it was part of a 'pushAndRemoveUntil() fix' (commit message). We require notification before to ensure secondary animations behave correctly, and I also believe subsequent actions should responsible for change notifications (no tests fail if it is removed)

I will therefore remove the 'after' notifications from both methods. @Piinks - looks like you might have introduced/edited the `pushAndRemoveUntil()`'s `didChangeNext() ` notification after the transition. Would you agree it is safe to remove? It's only a revert away if not.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 20]
```diff
@@ -1961,14 +1963,14 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
         }
-
-        if (newPrecedingRoute != null)
-          newPrecedingRoute.didChangeNext(newRoute);
       }
     });
 
     // Notify for newRoute
     newRoute.didChangeNext(null);
+    if (precedingRoute != null) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/navigator.dart]: This is actually undoing the changes from #35223. IIRC, the new route needs to finish pushing before we can notify the preceding route, which is why it is inside of `whenCompleteOrCancel`.

**Comment by Piinks** [comment]
> I will therefore remove the 'after' notifications from both methods. @Piinks - looks like you might have introduced/edited the `pushAndRemoveUntil()`'s `didChangeNext() ` notification after the transition. Would you agree it is safe to remove? It's only a revert away if not.

I am not certain it is safe to remove, as that fix addressed multiple bugs with hero and page transition animations. IIRC, the notifications were part of the issue. #35223

**Comment by Piinks** [comment]
Clicked wrong button. Sry. :P

**Review by Piinks — COMMENTED** [review]
> I will therefore remove the 'after' notifications from both methods. @Piinks - looks like you might have introduced/edited the `pushAndRemoveUntil()`'s `didChangeNext() ` notification after the transition. Would you agree it is safe to remove? It's only a revert away if not.

I am not certain it is safe to remove, as that fix addressed multiple bugs with hero and page transition animations. IIRC, the notifications were part of the issue. I may have some sample code that can verify this, which could certainly serve as a validation test going forward.

Also, the documentation would need to reflect this change, as it explains this notification process above: https://github.com/flutter/flutter/blob/3fe6668849b17bb657e9b7bb242d44a2db3afb55/packages/flutter/lib/src/widgets/navigator.dart#L1185-L1192

**Comment by Piinks** [comment]
I checked out your branch here and ran the reproduction cases from the bugs #35223 fixed. Everything looks okay to me, and all existing tests are passing. So I think this is okay.

For reference, here are some of the code samples I run:

this gist: https://gist.github.com/Alby-o/28819a330a3f9888e011bb5a61574fc2

and this snippet: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: <String, WidgetBuilder>{
        '/': (context) => HomePage(),
        '/2': (context) => SecondPage(),
        '/e': (context) => ErrorPage(),
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
        actions: <Widget>[
          FlatButton(
            child: Text('NEXT'),
            onPressed: () {
              Navigator.pushNamed(
                context,
                '/2',
              );
            }
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        // heroTag: null,
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen 2'),
        actions: <Widget>[
          FlatButton(
            child: Text('NEXT'),
            onPressed: () {
              Navigator.pushNamedAndRemoveUntil(
                context,
                '/e',
                ModalRoute.withName('/'),
              );
            }
          )
        ],
      ),
    );
  }
}

class ErrorPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Error Screen'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by joellurcook** [comment]
Thanks @Piinks. 
Not sure on the process or who gets to green-light this PR, but hopefully we are ready to land this soon?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: Let's revert this?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 21]
```diff
@@ -1883,19 +1883,21 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
     newRoute.install(_currentOverlayEntry);
     _history[index] = newRoute;
     newRoute.didPush().whenCompleteOrCancel(() {
-      // The old route's exit is not animated. We're assuming that the
-      // new route completely obscures the old one.
       if (mounted) {
+        // The old route's exit is not animated. We're assuming that the
+        // new route completely obscures the old one.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: can you revert this comment to move it to its original place?

File: packages/flutter/test/widgets/navigator_test.dart [hunk 22]
```diff
@@ -91,6 +91,31 @@ class OnTapPage extends StatelessWidget {
...
+              begin: Offset.zero,
+              end: const Offset(-1.0, 0),
+            ).animate(secondaryAnimation),
+            child: child,
+          ),
+        );
+      },
+  );
+
+  @override
```
Comment (chunhtai) [inline packages/flutter/test/widgets/navigator_test.dart]: This seems redundant?

**Review by chunhtai — COMMENTED** [review]
I left some nit, otherwise LGTM

File: packages/flutter/test/widgets/navigator_test.dart (hunk 22 above)
Comment (joellurcook) [reply packages/flutter/test/widgets/navigator_test.dart]: This is necessary to avoid an analyze error for accessing a protected member.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 21 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: Pushed commit moving this.

**Comment by joellurcook** [comment]
Apologies for the very slow reply - I have not been active at all over the holidays. I've moved the comment as requested. I have not made changes for the other two:

- The override is required to prevent an analyze error
- `newRoute.didChangePrevious(...)` is called at line 1895. Since there can be only one previous, I leave it pointing at the immediate route beneath it which is now animating. If you feel strongly that this is incorrect, please let me know.

File: packages/flutter/test/widgets/navigator_test.dart (hunk 22 above)
Comment (chunhtai) [reply packages/flutter/test/widgets/navigator_test.dart]: Oh I didn't notice this is protected member.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: In theory, we should call didChangePrevious  with oldRoute first and then call with _history[index - 1] after the transition. However, it is not possible with current navigator, and that is part of the reason why we are refactoring the navigator. I am more leaning toward keeping the original behavior and wait for the refactor to clean up to avoid introducing unexpected issue

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 23]
```diff
@@ -1892,10 +1892,12 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
       }
     });
     newRoute.didChangeNext(null);
+    newRoute.didChangePrevious(oldRoute);
+    oldRoute.didChangeNext(newRoute);
     if (index > 0) {
       _history[index - 1].didChangeNext(newRoute);
-      newRoute.didChangePrevious(_history[index - 1]);
     }
+
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: nit, extra blank line

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: Why is that not possible? I've pushed a commit doing exactly that. There clearly is not yet a consistent view on when to notify next/previous. For now, I have taken the view that we notify next/previous before a transition. And notify previous when we have removed items (after the transition) - leaving the newly pushed route in a state with correct next/previous. It may be that the new route has the same previous set twice, but surely the effect of that notification should be idempotent. As stated before, any following transition will re-notify as required anyway. This is no worse than the existing situation, and is not something we should keep changing as part of this PR.
I appreciate that you wish to focus on your own refactor, but I am working on a commercial project that requires this change and cannot afford to abandon this PR for one with a much less predictable time frame.

**Comment by joellurcook** [comment]
It would be really good to get some final decision on this PR now.

The time taken on this PR is astounding considering how relatively small the change is, and much of the discussion and minor amends are not directly related to the purpose of this PR (to run secondary animations of removed routes).

I am aware of the ongoing refactor, but see no reason why this change cannot be made now.

**Comment by joellurcook** [comment]
CLA fail... I do not know how to resolve this. I used github UI to fix a minor clash and the resulting merge commit seems to have caused this issue.
Please advise.

**Comment by joellurcook** [comment]
@googlebot I fixed it.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: Is there another issue that depends on this change (line 1899 didChangePrevious )? I thought the original issue about the secondary animation can be solved by line 1900 didChangeNext alone. I do agree the change on line 1900 is necessary, and this is an actual bug that we didn't notify didChangeNext on the old route before. However, I think we should add the ```newRoute.didChangePrevious(_history[index - 1]);``` back while removing line 1899 if there is no good reason to change it.

**Comment by Piinks** [comment]
Hey @joellurcook, I am not sure what exactly caused the CLA fail, I have often seen it happen when rebasing and another author gets added in. I usually pull the latest from master to update my branch and that cleans things up for me. 
If that doesn't resolve it for you, we can manually override the cla.

**Comment by Piinks** [comment]
> It would be really good to get some final decision on this PR now.
> 
> The time taken on this PR is astounding considering how relatively small the change is, and much of the discussion and minor amends are not directly related to the purpose of this PR (to run secondary animations of removed routes).

I am sorry this change has taken a while. Breaking changes typically undergo extra scrutiny before making them. In addition to the consideration needed around the larger refactor that is in progress and the holidays, this has taken a while. Thanks so much for sticking with it! This is not a trivial change, so thank you for putting in the work! Let's see if we can resolve the cla and I believe this should be ready to go.

**Review by chunhtai — COMMENTED** [review]
@joellurcook 
I also left a comment https://github.com/flutter/flutter/pull/42100/files#r364198505.

**Comment by Piinks** [comment]
> @joellurcook
> I also left a comment https://github.com/flutter/flutter/pull/42100/files#r364198505.

Oh! Good catch! I missed that scrolling through the history.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 18 above)
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: Agreed - have pushed a change to revert this

**Comment by joellurcook** [comment]
> I am sorry this change has taken a while. Breaking changes typically undergo extra scrutiny before making them. In addition to the consideration needed around the larger refactor that is in progress and the holidays, this has taken a while. Thanks so much for sticking with it! This is not a trivial change, so thank you for putting in the work! Let's see if we can resolve the cla and I believe this should be ready to go.

Thanks - appreciate that this needs to be right, just really feel this is ready to go. I have updated the PR with latest in master (`git fetch upstream; git pull upstream master`), but sadly no luck on resolving the CLA.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 24]
```diff
@@ -1889,9 +1889,14 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
         oldRoute
           ..didComplete(result ?? oldRoute.currentResult)
           ..dispose();
+        final int finalIndex = _history.indexOf(newRoute);
+        if (finalIndex > 0) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: This change seems to come back from the revert

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 25]
```diff
@@ -1961,14 +1966,19 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
             observer.didRemove(removedRoute, newPrecedingRoute);
           removedRoute.dispose();
         }
-
-        if (newPrecedingRoute != null)
-          newPrecedingRoute.didChangeNext(newRoute);
+      }
+      final int finalIndex = _history.indexOf(newRoute);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: same here?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 24 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: we are double notifying the new previous route, is this necessary given we already notifying pre transition in line 1902? Is there an issue depends on this change?

**Comment by Piinks** [comment]
> sadly no luck on resolving the CLA.

No worries! We can manually fix it when this is approved to land. :)

**Comment by joellurcook** [comment]
Unsurprisingly, I have lost track of the coming and goings of the notifications of previous/next throughout this PR, and apologies if I have placed back in what was originally agreed to be out and so on.

I think we currently agree that all notifications are correct at the onset of the transition, and that a new transition would always setup all the previous/next states as necessary.

The only issue left is what to do at the end of the transition. Since these are transitions specifically to push a route and then change the history behind it, it felt reasonable for the new route to complete the transition in a state where the change in its history is recognised. This is subject to the new route still existing, and that the history could have changed during the transition. I recognise that this final previous notification is not necessary to resolve the specific PR issue, it just felt right. 

If it will land the PR, I will happily remove lines 1892-1895 and 1970-1973, but to make sure this is the final commit, please can somebody make a definitive decision that they _shouldn't_ be there, or that they can remain. Either way passes all tests.

**Review by chunhtai — COMMENTED** [review]
If something has changed during the push transition, it will be on them to notify the routes. Currently in this pr we are notifying before(line 1902) and after(line 1894) which we should remove at least remove one of them. Otherwise, we will notify the new proceeding twice if nothing has changed. I would suggest we only notify before the transition because that is what other navigator apis other than pushAndRemoveUntil and pushReplacement do at the moment.

This will be the last thing before we can merge this pr.

**Comment by goderbauer** [comment]
Looks like this will also need to be rebased on master to make Cirrus happy.

**Comment by joellurcook** [comment]
I have remove the post-transition previous notifications and fetched upstream to hopefully fix up the CI issues.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 26]
```diff
@@ -1961,14 +1966,19 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+      if (finalIndex > 0) {
+        newRoute.didChangePrevious(_history[finalIndex - 1]);
       }
     });
 
     // Notify for newRoute
     newRoute.didChangeNext(null);
+    if (precedingRoute != null) {
+      newRoute.didChangePrevious(precedingRoute);
```
[the remark this answers is not in the document]
Comment (joellurcook) [reply packages/flutter/lib/src/widgets/navigator.dart]: I don't think so on this one. Even though the `precedingRoute` is being removed from the history, it is still there (and we want to animate it). Similarly, we need to set the `precedingRoute` next to `newRoute` despite `precedingRoute` being removed from the history. 
It would seem odd to me to if `precedingRoute` next must be `newRoute`, but `newRoute` previous is not `precedingRoute`.

**Comment by joellurcook** [comment]
Damn - still broken. Will this just be bad luck that I chose a time to update when the flutter build was broken?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 26 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart]: No one is notifying ```newPrecedingRoute.didChangeNext(newRoute);``` and  ```newRoute.didChangePrevious(newPrecedingRoute)``` in this method, we should make sure we have it here before the transition.

I can't see an immediately harm will do to notify  ```newRoute.didChangePrevious(precedingRoute);``` where we previously didn't. The only part in our code that depends on this is in CupertinoPageRoute where it use this notify to update the label of back button. As long as we call ```newRoute.didChangePrevious(newPrecedingRoute)``` after ```newRoute.didChangePrevious(precedingRoute);```, we should be fine in this case. The reason I brought this up is we will likely have to call this two notify back to back which seems weird to me. However, as you mentioned, it probably make more sense to notify ```newRoute.didChangePrevious(precedingRoute);``` to make thing more consistent. This also apply to pushReplacement, we should make sure pushReplacement and pushAndRemoveUntil are in sync

**Review by chunhtai — COMMENTED** [review]
The current build is green, can you try to rebase again and see if that fixes it?

**Comment by Piinks** [comment]
I've seen this versioning issue happen with old branches. I recently resolved this by locally using 
`git fetch upstream`
`git reset --soft upstream/master`
`git commit ... ` (recommit all changes)
`git push -f ...` (force push to remote branch)

This would reset the history of your commits though, and combine them all into the new commit. @dnfield thought this might be a pub issue?  It seems to be cropping up in more places.

**Comment by dnfield** [comment]
@jonahwilliams 

I'm fairly certain this is an issue with how the tool resolves the version.  It uses git tags and commit history to do it, and we're probably getting into a state here where it can't resolve the version correctly.  

See these lines:

```
 The current Flutter SDK version is 1.10.7-pre.130.

    | 

    | Because flutter_gallery depends on video_player_web >=0.1.1 which requires Flutter SDK version >=1.12.8 <2.0.0, version solving failed.
```

It should be saying the current flutter SDK version is 1.14.x-pre.something, not 1.10.7-pre.130.

**Comment by dnfield** [comment]
In the mean time, yes, redoing your git history should work around it.

**Comment by chunhtai** [comment]
@joellurcook I left a comment a while back. Would like to bump it up to get your attention :)

**Comment by joellurcook** [comment]
@chunhtai hi sorry, don't know how I missed that comment!
Good catch - I had forgotten about the Cupertino label. I don't think we can risk calling both back-to-back, though. This is fine for the situation where we have routes A-B-C and C replaces B - C label will end up indicating A, after very briefly indicating B. 
But what if C replaces A and B? in that case, C label will indicate B (`precedingRoute`), there is no `newPrecedingRoute`. The result is then a route pointing back to a route that doesn't exist. This isn't something we should fix after the transition either, as it should animate in with the correct value.
Therefore, I suggest that it is safe (and necessary) for both `precedingRoute` and `newPrecedingRoute` to have next pointing to `newRoute`, but that `newRoute` previous should only be set to the ultimate preceding route (if any).
It is confusing that B->C but A<-C, but think it is necessary. Hopefully you can clean up the terminology in the larger refactor.
Hope that all makes sense!

**Review by chunhtai — APPROVED** [review]
LGTM
