### PR TITLE
CupertinoContextMenu improvement

### LINKED ISSUE #70716: GestureDetector inside CupertinoContextMenu may trigger if the touch is released before CupertinoContextMenu completes transition
## Steps to Reproduce

1. Insert a `CupertinoContextMenu`.
2. Insert a `GestureDetector` inside of it.
3. Hold down the `CupertinoContextMenu` until it makes the _shrink_ animation and let go of the tap.

**Expected results:** 
One of them should be triggered.

**Actual results:** 
As seen on #52226, both of them are triggered at the same time.

<details>
  <summary>Logs</summary>

Not applicable.

```
Analyzing app_name...                                               
No issues found! (ran in 4.3s)
```

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale es-ES)
    • Flutter version 1.22.4 at /Users/carlosat/Desarrollador/flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/carlosat/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    ! Error: Apple TV is not paired with your computer. To use Apple TV with Xcode, unlock it and choose to trust this computer when prompted. (code -9)

! Doctor found issues in 1 category.
```
(By the way, the plugins are installed, I don't know why it keeps telling me they're not).

</details>

### PR DESCRIPTION
**Pull request by xhzq233**
Fixes #70716, #81057
Related ##52226

## Why the conflict

If we put a `TapGestureRecognizer` at `CupertinoContextMenu` 's subtree. 

For simplicity, we name the `TapGestureRecognizer` inside `CupertinoContextMenu` as **tg2**, the `TapGestureRecognizer` at `CupertinoContextMenu` 's subtree as **tg1**, and the press duration as **t1**.

When `kPressTimeout+_previewLongPressTimeout/2` (500ms) < **t1** < `kPressTimeout+_previewLongPressTimeout `(900ms), this moment

1. Although **tg2** was rejected, `_ContextMenuRoute` was still opened.

2.  And the onTap method of **tg1** is triggered

The problem is that the GestureRecognizer in this ContextMenu is TapGestureRecognizer instead of LongPressGestureRecognizer, and Tap does not claim to victory, but GestureArena selects the deepest Tap to win.

1. When **t1** is greater than 500ms, it means that it has passed `PrimaryPointerGestureRecognizer.deadline` plus half of the `openController`'s duration, means that `_ContextMenuRoute` is about to be opened. After `GestureArena` received pointer up event, **tg1** competed with **tg2**. The default "child-victory" worked, and the onTap of tg1 was called, so both were triggered.

2. When **t1** is less than 900ms, because route is opened at this time, and both will be rejected by arena.

## Solution

The reason is that `TapGestureRecognizer` will not declare victory by itself. Add the following code.

```dart

// call this when animation's value first reaches [_midpoint]

_tapGestureRecognizer.resolve(GestureDisposition.accepted);

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by xhzq233** [comment]
I'm not sure ask who to review my code. Can you please give me some help? @MitchellGoodwin

**Comment by MitchellGoodwin** [comment]
@xhzq233 it looks like the failing check has to do with a plugin that this PR should not be interacting with. Would you mind rebasing to the current master branch to see if that fixes the check?

**Comment by xhzq233** [comment]
> 

Merged. Now it has become a Windows build check error.= =

**Comment by MitchellGoodwin** [comment]
> Merged. Now it has become a Windows build check error.= =

Looks like there was some other issues. Another rebase to current master might work.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 1]
```diff
@@ -810,4 +811,71 @@ void main() {
...
+        ),
+      ),
+    ));
+
+    // Start a press on the child.
+    final TestGesture gesture = await tester.createGesture();
+    await gesture.down(tester.getCenter(find.byKey(const Key('container'))));
+    await tester.pump();
+    // simulate a press with specified duration
+    for (int i = 0; i < 100; i++) {
```
Comment (MitchellGoodwin) [inline packages/flutter/test/cupertino/context_menu_test.dart:855]: Did you try `await tester.pump(const Duration(milliseconds: pressDuration));` first? Is this for loop more consistent?

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 2]
```diff
@@ -810,4 +811,71 @@ void main() {
...
+      // simulate 100 frames
+      await tester.pump(pressDuration ~/ 100);
+    }
+    await gesture.up();
+    // await pushing route
+    await tester.pumpAndSettle();
+
+    // judge whether _ContextMenuRouteStatic present on the screen
+    final Finder static = find.byWidgetPredicate(
```
[the remark this answers is not in the document]
Comment (xhzq233) [reply packages/flutter/test/cupertino/context_menu_test.dart]: Done 👍🏻

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 1 above)
Comment (xhzq233) [reply packages/flutter/test/cupertino/context_menu_test.dart:855]: Yes, I tried it first. But `_openAnimation` won't reach midPoint since a `pump` only triggers one frame.

I need more frames to drive `_openAnimation` to reach the `midPoint`, so the route can be opened.

Comment (xhzq233) [reply packages/flutter/test/cupertino/context_menu_test.dart:855]: https://github.com/flutter/flutter/blob/2c71881f505b0dc0997e959b3ac37664d221fad8/packages/flutter_test/lib/src/widget_tester.dart#L704C3-L719C4

`pumpFrames` use the same methodology like this. And it will pump another widget.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for answering my questions and putting this together.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 3]
```diff
@@ -810,4 +811,71 @@ void main() {
       expect(right.dx, lessThan(left.dx));
     });
   });
+
+  testWidgets('Is gesture conflicts of ctx_menu resolved',
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:815]: Nit: What is ctx_menu?  Maybe change this to: `testWidgets('Conflicting gesture detectors',`

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 4]
```diff
@@ -810,4 +811,71 @@ void main() {
...
+      (WidgetTester tester) async {
+    int? onPointerDownTime;
+    int? onPointerUpTime;
+    bool insideTapTriggered = false;
+    // 500ms < duration < 900ms
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:820]: Nit: Maybe explain where these values come from here.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 5]
```diff
@@ -810,4 +811,71 @@ void main() {
...
+          ),
+        ),
+      ),
+    ));
+
+    // Start a press on the child.
+    final TestGesture gesture = await tester.createGesture();
+    await gesture.down(tester.getCenter(find.byKey(const Key('container'))));
+    await tester.pump();
+    // simulate a press with specified duration
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:854]: Nit: Capital letter at the beginning and period at the end of your comments here and below.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 6]
```diff
@@ -810,4 +811,71 @@ void main() {
...
+    await gesture.up();
+    // await pushing route
+    await tester.pumpAndSettle();
+
+    // judge whether _ContextMenuRouteStatic present on the screen
+    final Finder routeStatic = find.byWidgetPredicate(
+          (Widget w) => '${w.runtimeType}' == '_ContextMenuRouteStatic',
+    );
+    // can't present together
+    if (insideTapTriggered) {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:868]: Why is this an `if`, does it happen differently on different platforms?

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/cupertino/context_menu_test.dart:855]: Does it really matter that 100 frames need to be pumped, not just 1 frame over the same duration?  I wouldn't think that would affect the gesture.

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1:

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 6 above)
Comment (xhzq233) [reply packages/flutter/test/cupertino/context_menu_test.dart:871]: This is used to detect whether the click gesture is detected by `GestureDetector`, so there will be no difference between different platforms.

**Comment by xhzq233** [comment]
Done. It is my first time contributing to Flutter. Thank you for your review and guidance.

**Review by justinmc — APPROVED** [review]
Renewing my LGTM and merging.  Thanks for fixing this!
