### PR TITLE
fix(ListTileTheme): isThreeLine is missing.

### LINKED ISSUE #165453: [Material] ListTileThemeData value isThreeLine does not work
### Steps to reproduce

Run MaterialApp with ListTileThemeData config

### Expected results

isThreeLine: true

### Actual results

isThreeLine: false

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListTileTheme(
          data: ListTileTheme.of(context).copyWith(isThreeLine: true),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Card(
                child: ListTile(
                  leading: FlutterLogo(size: 72.0),
                  title: Text('Three-line ListTile Theme'),
                  subtitle: Text(
                    'A sufficiently long subtitle warrants three lines.',
                  ),
                  trailing: Icon(Icons.more_vert),
                ),
              ),
              Card(
                child: ListTile(
                  leading: FlutterLogo(size: 72.0),
                  title: Text('Three-line ListTile'),
                  subtitle: Text(
                    'A sufficiently long subtitle warrants three lines.',
                  ),
                  trailing: Icon(Icons.more_vert),
                  isThreeLine: true,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on Ubuntu 20.04.6 LTS 6.8.0-1021-azure, locale C.UTF-8) [172ms]
    • Flutter version 3.29.2 on channel stable at /home/codespace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Chrome - develop for the web [29ms]
    • CHROME_EXECUTABLE = /usr/bin/www-browser

[!] Flutter IDE Support (No supported IDEs installed) [17ms]
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available) [947ms]
    • Chrome (web) • chrome • web-javascript • Lynx Version 2.9.0dev.5 (27 Feb 2020)
      libwww-FM 2.14, SSL-MM 1.4.1, GNUTLS 3.6.13, ncurses 6.2.20200212(wide)
      Built on linux-gnu.

      Copyrights held by the Lynx Developers Group,
      the University of Kansas, CERN, and other contributors.
      Distributed under the GNU General Public License (Version 2).
      See https://lynx.invisible-island.net/ and the online help for more information.

[✓] Network resources [468ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by StanleyCocos**
fix: https://github.com/flutter/flutter/issues/165453

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by StanleyCocos** [comment]
Could you take some time to review this request? cc @TahaTesser

**Comment by TahaTesser** [comment]
> Could you take some time to review this request? cc @TahaTesser

Unfortunately, I'm quite occupied for a few weeks. This PR will be reviewed soon by the team during triage.

File: packages/flutter/test/material/list_tile_test.dart [hunk 1]
```diff
@@ -4361,6 +4361,138 @@ void main() {
...
+                  subtitle: const Text('A'),
+                ),
+              ],
+            ),
+          ),
+        ),
+      );
+    }
+
+    void testTowLine() {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/list_tile_test.dart:4405]:
```suggestion
    void testTwoLine() {
```

Comment (dkwingsmt) [reply packages/flutter/test/material/list_tile_test.dart:4405]: Shall we rename them to `expectTwoLine` and `expectThreeLine`? Fits English grammar better imo.

**Review by dkwingsmt — APPROVED** [review]
LGTM. I like how the test cases are written!

File: packages/flutter/test/material/list_tile_test.dart (hunk 1 above)
Comment (StanleyCocos) [reply packages/flutter/test/material/list_tile_test.dart]: Your suggestion was great. Thank you—I’ve already made the changes.

**Comment by StanleyCocos** [comment]
Would you mind helping me request a second review? I really appreciate it!   cc @dkwingsmt

**Comment by dkwingsmt** [comment]
Of course! I forgot about it since I was a bit busy today.

File: packages/flutter/lib/src/material/list_tile.dart [hunk 2]
```diff
@@ -482,7 +482,7 @@ class ListTile extends StatelessWidget {
   ///
   /// When using a [Text] widget for [title] and [subtitle], you can enforce
   /// line limits using [Text.maxLines].
-  final bool isThreeLine;
+  final bool? isThreeLine;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/list_tile.dart:485]: Can you add a sentence to the docs about what happens if this is null?

File: packages/flutter/lib/src/material/list_tile_theme.dart [hunk 3]
```diff
@@ -139,6 +140,9 @@ class ListTileThemeData with Diagnosticable {
   /// or [ExpansionTile.controlAffinity] or [SwitchListTile.controlAffinity] or [RadioListTile.controlAffinity].
   final ListTileControlAffinity? controlAffinity;
 
+  /// If specified, overrides the default value of [ListTile.isThreeLine]
```
Comment (justinmc) [inline packages/flutter/lib/src/material/list_tile_theme.dart:143]: Period at the end here.

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: . Thanks for the thorough tests.

**Comment by StanleyCocos** [comment]
Thank you all. I believe this PR is ready. If you have time, could you please help add a commit label? Much appreciated. @dkwingsmt @justinmc
