### PR TITLE
Exclude modal barrier Semantics in Drawer on Android

### LINKED ISSUE #39896: Dismissing drawer tapping the black overlay calls onTap on ListTile if Talkback is on
# Steps to Reproduce
Create a basic Scaffold with a drawer and a ListView as a child with some ListTile elements, enable Talkback on Android and double tap on the black overlay to dismiss the drawer.
OnTap of a ListTile is called.
Here's a simple demo https://gist.github.com/lorenzOliveto/a8766a55a8eb4b726b874f9b0540c06f
Tried on a Nexus 5X.

## Flutter doctor output

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale it-IT)
    • Flutter version 1.7.8+hotfix.4 at /Users/lorenzooliveto/Flutter/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lorenzooliveto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone di Lorenzo • 63e1defd8bca92bd059530106598ec853b3609ac • ios • iOS 13.1
    • iPhone Xs         • 58A5AE70-C88B-40F5-B64E-D3A884B4C30D     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by perclasson**
## Description

Right now the semantics of the modal barrier for Drawer is visible and accessible for Android even though that is not intended behavior. The way to close the Drawer is via the back button. This change makes sure the dismiss semantics barrier does not show up on Android.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39896

## Tests

I added the following tests:

"Dismissible ModalBarrier includes button in semantic tree on iOS" test/widgets/drawer_test.dart

"Dismissible ModalBarrier is hidden on Android (back button is used to dismiss)" test/widgets/drawer_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -542,18 +542,20 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
...
                   // On Android, the back button is used to dismiss a modal.
-                  excludeFromSemantics: platformHasBackButton,
-                  onTap: close,
-                  child: Semantics(
-                    label: MaterialLocalizations.of(context)?.modalBarrierDismissLabel,
-                    child: MouseRegion(
-                      opaque: true,
-                      child: Container( // The drawer's "scrim"
-                        color: _scrimColorTween.evaluate(_controller),
+                  excluding: defaultTargetPlatform == TargetPlatform.android,
```
Comment (rami-a) [inline packages/flutter/lib/src/material/drawer.dart]: I think this should still use `platformHasBackButton` since it exists already

File: packages/flutter/test/widgets/drawer_test.dart [hunk 2]
```diff
@@ -327,7 +327,13 @@ void main() {
     scaffoldKey.currentState.openDrawer();
     await tester.pump(const Duration(milliseconds: 100));
 
-    expect(semantics, includesNodeWith(actions: <SemanticsAction>[SemanticsAction.tap]));
+    expect(
```
Comment (rami-a) [inline packages/flutter/test/widgets/drawer_test.dart]: Split this into 2 statements like below.

**Review by rami-a — APPROVED** [review]

File: packages/flutter/lib/src/material/drawer.dart (hunk 1 above)
Comment (perclasson) [reply packages/flutter/lib/src/material/drawer.dart]: Yes. It's true. Done.

File: packages/flutter/test/widgets/drawer_test.dart (hunk 2 above)
Comment (perclasson) [reply packages/flutter/test/widgets/drawer_test.dart]: Done.

File: packages/flutter/lib/src/material/drawer.dart (hunk 1 above)
Comment (perclasson) [reply packages/flutter/lib/src/material/drawer.dart]: I agree. Done.

File: packages/flutter/test/widgets/drawer_test.dart (hunk 2 above)
Comment (perclasson) [reply packages/flutter/test/widgets/drawer_test.dart]: Will do, will make it more readable and understandable that I am just adding the Dismiss check as well.

**Review by HansMuller — APPROVED** [review]
LGTM
