### PR TITLE
fixes Show Week Day in CupertinoDatePicker with CupertinoDatePickerMo…

### LINKED ISSUE #120051: Show Week Day in CupertinoDatePicker with CupertinoDatePickerMode.date
## Use case

Currently CupertinoDatePicker widget on IOS does not show day of Week when CupertinoDatePickerMode is set to date.

In use case where we have to show date only but we also wants users to show what day they are selecting then CupertinoDatePicker widget with current features set fails to support showing day of week in `CupertinoDatePickerMode.date` mode.

CupertinoDatePickerMode has three modes: time, date and dateAndTime.

In `CupertinoDatePickerMode.date` CupertinoDatePicker widget does not show day of week at all and there is no way to show it.

## Proposal

There should be configurable option to show Day of week alongside day of month when CupertinoDatePickerMode is set to date.

### PR DESCRIPTION
**Pull request by sikandernoori**
*Show Week Day in CupertinoDatePicker with CupertinoDatePickerMode.date*

fixes #120051

### Sample

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by jmagman** [comment]
```
03:20 +4829 ~1: /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: date picker has expected day of week                                                                      
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "9" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart:1687:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart line 1687
The test description was:
  date picker has expected day of week
════════════════════════════════════════════════════════════════════════════════════════════════════

03:20 +4829 ~1 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: date picker has expected day of week [E]                                                               
  Test failed. See exception logs above.
  The test description was: date picker has expected day of week
```

**Comment by sikandernoori** [comment]
@jmagman test case fixed.

**Comment by MitchellGoodwin** [comment]
@sikandernoori I'll review once all the tests are passing. Some of the tests don't look like infastructure issues outside of this PR, but this one looks related:
```
The following assertion was thrown running a test:
The finder "zero widgets with text "26" (ignoring offstage widgets)" (used in a call to "drag()")
could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1236:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1175:12)
#2      WidgetController.drag (package:flutter_test/src/controller.dart:860:7)
#3      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/examples/api/test/cupertino/date_picker/cupertino_date_picker.0_test.dart:21:18)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Can change date, time and dateTime using CupertinoDatePicker
  ```

**Comment by sikandernoori** [comment]
@MitchellGoodwin failling test fixed.

**Comment by MitchellGoodwin** [comment]
@sikandernoori the infrastructure issues were fixed. Could you please rebase on the latest master branch to pick up the fixes?

**Comment by jmagman** [comment]
> @sikandernoori the infrastructure issues were fixed. Could you please rebase on the latest master branch to pick up the fixes?

FYI As of yesterday we turned on the ability for any flutter-hacker contributor to rebase with the "Update branch" button (probably most useful for infra issues like this one)
Screenshot 2023-02-23 at 10 40 50 AM

File: packages/flutter/lib/src/cupertino/localizations.dart [hunk 1]
```diff
@@ -292,7 +297,8 @@ class DefaultCupertinoLocalizations implements CupertinoLocalizations {
   /// function, rather than constructing this class directly.
   const DefaultCupertinoLocalizations();
 
-  static const List<String> _shortWeekdays = <String>[
+  ///Short version of days of week.
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/localizations.dart:300]: nit: need a space in front of Short

**Review by MitchellGoodwin — COMMENTED** [review]
Thank you for submitting this change. I left some mostly nit comments.

File: packages/flutter/lib/src/cupertino/localizations.dart (hunk 1 above)
Comment (sikandernoori) [reply packages/flutter/lib/src/cupertino/localizations.dart]: Fixed.

File: examples/api/lib/cupertino/date_picker/cupertino_date_picker.0.dart [hunk 2]
```diff
@@ -81,6 +81,8 @@ class _DatePickerExampleState extends State<DatePickerExample> {
                         initialDateTime: date,
                         mode: CupertinoDatePickerMode.date,
                         use24hFormat: true,
+                        // This shows daya of week alongside day of month
```
[the remark this answers is not in the document]
Comment (sikandernoori) [reply examples/api/lib/cupertino/date_picker/cupertino_date_picker.0.dart]: fixed

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 3]
```diff
@@ -443,10 +448,13 @@ class CupertinoDatePicker extends StatefulWidget {
...
-          final String dayOfMonth = localizations.datePickerDayOfMonth(i);
-          if (longestText.length < dayOfMonth.length) {
-            longestText = dayOfMonth;
+        final int lenght = showDayOfWeek ? DateTime.daysPerWeek : 2;
+        for (int wd = 1; wd < lenght; wd++) {
+          for (int i = 1; i <=31; i++) {
+            final String dayOfMonth = localizations.datePickerDayOfMonth(i, showDayOfWeek ? wd : null);
+            if (longestText.length < dayOfMonth.length) {
+              longestText = dayOfMonth;
+            }
```
[the remark this answers is not in the document]
Comment (sikandernoori) [reply packages/flutter/lib/src/cupertino/date_picker.dart:464]: refactored.

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 4]
```diff
@@ -443,10 +448,13 @@ class CupertinoDatePicker extends StatefulWidget {
             : localizations.postMeridiemAbbreviation;
         break;
       case _PickerColumnType.dayOfMonth:
-        for (int i = 1; i <=31; i++) {
-          final String dayOfMonth = localizations.datePickerDayOfMonth(i);
-          if (longestText.length < dayOfMonth.length) {
-            longestText = dayOfMonth;
+        final int lenght = showDayOfWeek ? DateTime.daysPerWeek : 2;
```
[the remark this answers is not in the document]
Comment (sikandernoori) [reply packages/flutter/lib/src/cupertino/date_picker.dart]: refactored

File: packages/flutter/lib/src/cupertino/localizations.dart [hunk 5]
```diff
@@ -82,12 +82,17 @@ abstract class CupertinoLocalizations {
   /// Day of month that is shown in [CupertinoDatePicker] spinner corresponding
   /// to the given day index.
   ///
+  /// if weekDay is provided then it will also show Day of week alongside day
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/localizations.dart:85]: nit: format to "If weekDay is provided then it will also show weekday name alongside the numerical day."

**Comment by MitchellGoodwin** [comment]
@sikandernoori I've left one more nit comment for the documentation, but other than that, this looks good to me.

File: packages/flutter/lib/src/cupertino/localizations.dart (hunk 5 above)
Comment (sikandernoori) [reply packages/flutter/lib/src/cupertino/localizations.dart]: Done.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for dealing with my nitpicking.

**Comment by sikandernoori** [comment]
> LGTM. Thank you for dealing with my nitpicking.

Happy to participate in quality work.

**Comment by MitchellGoodwin** [comment]
Oops, need another review. Let me ask around.

**Comment by sikandernoori** [comment]
> Oops, need another review. Let me ask around.

from bot description I believe 1 review is enough, you have to pass "approve" label first.

**Comment by MitchellGoodwin** [comment]
> from bot description I believe 1 review is enough, you have to pass "approve" label first.

No, it's because the PR has the "First-time contributor" label. Those need two reviews as a part of a security concern.

**Comment by sikandernoori** [comment]
> > from bot description I believe 1 review is enough, you have to pass "approve" label first.
> 
> No, it's because the PR has the "First-time contributor" label. Those need two reviews as a part of a security concern.

okay.

**Comment by jmagman** [comment]
Members of flutter-hackers access control group require one other flutter-hacker to approve.  If the author is not a member of the flutter-hackers, then two approvers are needed.
https://github.com/flutter/flutter/wiki/Contributor-access

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Welcome @sikandernoori, thanks for contributing!
