### PR TITLE
[flutter_tools] use flutter tool handler for dwds resources and precache tool pub dependencies

### LINKED ISSUE #53644: [flutter_tools] missing client.js file from dwds
## Steps to Reproduce
1. Run ```flutter config --enable-web```;
2. Create a new project with ```flutter create demo123```;
3. Delete all the contents in the ```/Users/zzd/flutter/.pub-cache``` folder;
    (Because they are caches, I think it is OK to delete at any time.)
4. Go to the project folder ```cd demo123``` and Run ```flutter pub get```;
5. Run ```flutter run -d chrome```;

## Logs
```
Last login: Wed Apr  1 17:28:40 on ttys000
zzd-mac-mini:~ zzd$ flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
zzd-mac-mini:~ zzd$ cd /Users/zzd/Desktop/test 
zzd-mac-mini:test zzd$ flutter create demo123
Creating project demo123...
  demo123/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  demo123/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  demo123/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  (created)
  demo123/ios/Runner/Info.plist (created)
  demo123/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  demo123/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  (created)
  demo123/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.pn
  g (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.pn
  g (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  (created)
  demo123/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  (created)
  demo123/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  demo123/ios/Runner/Base.lproj/Main.storyboard (created)
  demo123/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  (created)
  demo123/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChec
  ks.plist (created)
  demo123/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSetting
  s.xcsettings (created)
  demo123/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  demo123/ios/Flutter/Debug.xcconfig (created)
  demo123/ios/Flutter/Release.xcconfig (created)
  demo123/ios/Flutter/AppFrameworkInfo.plist (created)
  demo123/ios/.gitignore (created)
  demo123/test/widget_test.dart (created)
  demo123/demo123.iml (created)
  demo123/.gitignore (created)
  demo123/web/favicon.png (created)
  demo123/web/index.html (created)
  demo123/web/manifest.json (created)
  demo123/web/icons/Icon-192.png (created)
  demo123/web/icons/Icon-512.png (created)
  demo123/.metadata (created)
  demo123/android/app/src/profile/AndroidManifest.xml (created)
  demo123/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  demo123/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  demo123/android/app/src/main/res/drawable/launch_background.xml (created)
  demo123/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  demo123/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  demo123/android/app/src/main/res/values/styles.xml (created)
  demo123/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  demo123/android/app/src/main/AndroidManifest.xml (created)
  demo123/android/app/src/debug/AndroidManifest.xml (created)
  demo123/android/gradle/wrapper/gradle-wrapper.properties (created)
  demo123/android/gradle.properties (created)
  demo123/android/.gitignore (created)
  demo123/android/settings.gradle (created)
  demo123/android/app/build.gradle (created)
  demo123/android/app/src/main/kotlin/com/example/demo123/MainActivity.kt
  (created)
  demo123/android/build.gradle (created)
  demo123/android/demo123_android.iml (created)
  demo123/pubspec.yaml (created)
  demo123/README.md (created)
  demo123/ios/Runner/Runner-Bridging-Header.h (created)
  demo123/ios/Runner/AppDelegate.swift (created)
  demo123/ios/Runner.xcodeproj/project.pbxproj (created)
  demo123/lib/main.dart (created)
  demo123/.idea/runConfigurations/main_dart.xml (created)
  demo123/.idea/libraries/Flutter_for_Android.xml (created)
  demo123/.idea/libraries/Dart_SDK.xml (created)
  demo123/.idea/libraries/KotlinJavaRuntime.xml (created)
  demo123/.idea/modules.xml (created)
  demo123/.idea/workspace.xml (created)
Running "flutter pub get" in demo123...                             3.3s
Wrote 77 files.

All done!
[✓] Flutter: is fully installed. (Channel dev, v1.16.3, on Mac OS X 10.14.6
    18G1012, locale en-CN)
[✗] Android toolchain - develop for Android devices: is not installed.
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3.1)
[✓] Chrome - develop for the web: is fully installed.
[!] Android Studio: is not available. (not installed)
[✓] VS Code: is fully installed. (version 1.43.2)
[✓] Connected device: is fully installed. (2 available)

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd demo123
  $ flutter run

Your application code is in demo123/lib/main.dart.

zzd-mac-mini:test zzd$ cd /Users/zzd/flutter/.pub-cache 
zzd-mac-mini:.pub-cache zzd$ ls
_temp	hosted
zzd-mac-mini:.pub-cache zzd$ rm -rf _temp
zzd-mac-mini:.pub-cache zzd$ rm -rf hosted
zzd-mac-mini:.pub-cache zzd$ ls
zzd-mac-mini:.pub-cache zzd$ cd /Users/zzd/Desktop/test/demo123 
zzd-mac-mini:demo123 zzd$ flutter pub get
Running "flutter pub get" in demo123...                             3.6s
zzd-mac-mini:demo123 zzd$ flutter run -d chrome
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading Web SDK...                                              1.8s
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
18,358ms (!)                                       
ERROR - 2020-04-01 17:34:31.451774
GET /dwds/src/injected/client.js
Error thrown by handler.
FileSystemException: Cannot open file, path = '/Users/zzd/flutter/.pub-cache/hosted/pub.flutter-io.cn/dwds-3.0.0/lib/src/injected/client.js' (OS Error: No such file or directory, errno = 2)
dart:isolate  _RawReceivePortImpl._handleMessage

^Czzd-mac-mini:demo123 zzd$ 
```

## flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.14.6 18G1012, locale en-CN)
    • Flutter version 1.16.3 at /Users/zzd/flutter
    • Framework revision be3a4b37b3 (5 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (2 available)            
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.162
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

## Related to #52931

### LINKED ISSUE #65475: [tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.Receiver: nullTried calling: toFilePath()
## Command
```
flutter run --flavor dev -t lib/main_dev.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:36:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:211:21)
#3      ResidentRunner.launchDevTools (package:flutter_tools/src/resident_runner.dart:1195:33)
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1555:32)
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/elementary/.sdk/flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/elementary/.sdk/android
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Redmi 4A (mobile) • 192.168.43.178:7000 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+11
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 68587a0916366e9512a78df22c44163d041dd5f3
### Plugins
background_fetch-0.5.6
camera-0.5.8+5
device_info-0.4.2+7
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_crashlytics-0.1.4+1
firebase_messaging-6.0.16
flutter_image_compress-0.7.0
flutter_local_notifications-0.8.4+3
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-4.0.1
google_sign_in-4.5.3
google_sign_in_web-0.9.1+1
image_picker-0.6.7+7
location-3.0.2
location_web-1.0.0
package_info-0.4.3
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
permission_handler-5.0.1+1
searchable_dropdown-1.1.3
share-0.6.5
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1
url_launcher-4.2.0+3

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

If the tool is downloaded from a precompiled snapshot, or if the backing source files in the pub cache are deleted, the dwds debugging functionality will break as the client.js file cannot be located. Instead use the PackageConfig to verify that package location, downloading if it is missing.

Override the dwds middleware to avoid Isolate.resolvePackageUri

Fixes https://github.com/flutter/flutter/issues/53644
Fixes https://github.com/flutter/flutter/issues/65475

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Tested by the existing integration tests, though this does not directly cover the download-from-cloud storage workflow

**Comment by christopherfujino** [comment]
This change is good, but I'm still a little confused. Since this is happening in the wild, is anyone downloading pre-compiled tool snapshots? Or is it just that their pubcache is getting blown away? And my concern is that if we move to distributing the tool pre-compiled that there would be many more hacks like this we have to make. Is this a fix that should be upstreamed to `dwds`, or are pub packages allowed to assume they have access to assets in the pubcache?

**Comment by jonahwilliams** [comment]
> is anyone downloading pre-compiled tool snapshots

I think what is happening is that people that are new/starting out with flutter/web will download the beta branch. Try out the web and it will fail, while users that have flutter upgraded will not hit any issues.

The second issue of course is deleting the pub cache. Once the snapshot is created the package location is encoded into the snapshot based on what existed at the time. But the pub cache can be cleaned out/removed without disrupting the snapshot besides `Isolate.resolvePackageUri`.

Then there is that fact that `Isolate.resolvePackageUri` does not work at all in AOT mode.


I don't quite agree that this is hack, but its definitely very ad-hoc. What if instead of doing this as needed, I added a special universal cache artifact which guaranteed that the package config was valid and all package sources exist on disk? Then all the dwds handler would need to do is read the location from some artifact

**Comment by christopherfujino** [comment]
> I don't quite agree that this is hack, but its definitely very ad-hoc. What if instead of doing this as needed, I added a special universal cache artifact which guaranteed that the package config was valid and all package sources exist on disk? Then all the dwds handler would need to do is read the location from some artifact

Yeah, that's a great idea!

**Comment by christopherfujino** [comment]
> I think what is happening is that people that are new/starting out with flutter/web will download the beta branch. Try out the web and it will fail, while users that have flutter upgraded will not hit any issues.

Ahh yeah, that makes sense.

**Comment by jonahwilliams** [comment]
I really need to fix our initialization so that we compute the flutterRoot/version before doing anything else...

**Comment by jonahwilliams** [comment]
@christopherfujino its all working now!

File: packages/flutter_tools/lib/src/cache.dart [hunk 1]
```diff
@@ -128,6 +132,14 @@ class Cache {
         _artifacts.add(IosUsbArtifacts(artifactName, this));
       }
       _artifacts.add(FontSubsetArtifacts(this));
+      _artifacts.add(PubDependencies(
+        fileSystem: _fileSystem,
+        logger: _logger,
+        // flutter root and pub must be lazily to avoid initialization
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/cache.dart:138]:
```suggestion
        // flutter root and pub must be lazily-loaded to avoid initialization
```

File: packages/flutter_tools/lib/src/cache.dart [hunk 2]
```diff
@@ -434,7 +446,9 @@ class Cache {
     );
   }
 
-  bool isUpToDate() => _artifacts.every((ArtifactSet artifact) => artifact.isUpToDate());
+  FutureOr<bool> isUpToDate() async => (await Future.wait<bool>(<Future<bool>>[
+    ..._artifacts.map((ArtifactSet artifact) async => await artifact.isUpToDate()),
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/cache.dart:450]: This new version is pretty dense. Why do you need to destructure `...` the output of `.map()` here, I would assume that the `.map()` is returning a `List<Future<bool>>` already?

**Review by christopherfujino — APPROVED** [review]
LGTM, with a nit about a comment and a question.

File: packages/flutter_tools/lib/src/cache.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/cache.dart:450]: I had to do this because `FutureOr<bool>` is not a `Future<bool>`, so I can't pass it to Future.wait. I should just change to type signature to skip the FutureOr, then I can simplify this

File: packages/flutter_tools/lib/src/cache.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/cache.dart]: Done

File: packages/flutter_tools/lib/src/cache.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/cache.dart]: Ahh, that makes sense. Is `Future<bool>` a sub-type of `FutureOr<bool>`?
