### PR TITLE
URI-decode asset paths before writing them to the asset manifest

### LINKED ISSUE #21326: Assets with Space in file names loads only default resolution
## Steps to Reproduce
An asset with name "Comment filled.png" of different resolutions is set in directories as follows:

`assets/images/Comment filled.png`
`assets/images/1.5x/Comment filled.png`
`assets/images/2.0x/Comment filled.png`
`assets/images/3.0x/Comment filled.png`
`assets/images/4.0x/Comment filled.png`

`pubspec.yaml` loads `assets/images/Comment filled.png`

## What is observed?
This asset is always loaded from `assets/images/Comment filled.png`

## Expected
Asset `assets/images/4.0x/Comment filled.png` (or 3.0x) to be loaded on a FHD display

## Resolution
I tried changing the file name from `Comment filled.png` to `CommentFilled.png`. Now assets are loaded as per resolution.

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #21326

## Issue summary
Suppose an image asset contains a space in its filename (for example, `purple square.jpg`). Currently, when we look for the variant of this asset that best matches the current device-pixel ratio, we always choose the default variant even if on a high ratio device (3x, for example).

This happens because the asset manifest we create (`manifest` in the following code snippet) uses URI-encoded POSIX filepaths for its keys and values. When we perform lookups against the manifest, we use the asset's `keyName`, which is not URI-encoded. Therefore, the list of candidate variants will be considered empty and we will fall back to `keyName`, which is the default version of the asset.

https://github.com/flutter/flutter/blob/2adee31ce8b5256462d553dfb8bd613856cc2d94/packages/flutter/lib/src/painting/image_resolution.dart#L289-L293

This problem will happen to any file whose name contains a character that will be replaced by URI-encoding.

## Fix summary

When building the asset manifest, we URI-decode all keys and values.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/painting/image_resolution_test.dart [hunk 1]
```diff
@@ -152,6 +150,36 @@ void main() {
         expect(bundleKey.scale, 1.0);
       }));
     });
+
+    test('When the filename contains characters that must be URI-encoded', () {
```
Comment (christopherfujino) [inline packages/flutter/test/painting/image_resolution_test.dart:154]: Is this test hitting your change in the tool? Or is this verifying something else?

**Comment by christopherfujino** [comment]
I think to the fix the framework tests you'll have to rebase upstream, this was either fixed forward or reverted.

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart [hunk 2]
```diff
@@ -165,15 +163,17 @@ flutter:
       );
     });
 
-    testWithoutContext('Only images in folders named with device pixel ratios (e.g. 2x, 3.0x) should be considered as variants of other images', () async {
-      const String image = 'assets/image.jpg';
-      const String image2xVariant = 'assets/2x/image.jpg';
-      const String imageNonVariant = 'assets/notAVariant/image.jpg';
+    testWithoutContext('Variant detection works with windows-style filepaths', () async {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:166]: Aren't these posix/unix style paths?

File: packages/flutter_tools/lib/src/asset.dart [hunk 3]
```diff
@@ -644,7 +644,10 @@ class ManifestAssetBundle implements AssetBundle {
     final List<_Asset> sortedKeys = jsonEntries.keys.toList()
         ..sort((_Asset left, _Asset right) => left.entryUri.path.compareTo(right.entryUri.path));
     for (final _Asset main in sortedKeys) {
-      jsonObject[main.entryUri.path] = jsonEntries[main]!;
+      jsonObject[Uri.decodeFull(main.entryUri.path)] =
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/asset.dart:647]: Can you break this line into individual lines with named variables (to help readability) (please correct any var names that are wrong):

```dart
      final String decodedEntryUri = Uri.decodeFull(main.entryUri.path);
      final List<String> rawVariants = jsonEntries[main]!;
      final List<String> decodedVariants = rawVariants.map(Uri.decodeFull).toList();
      jsonObject[decodedEntryUri] = decodedVariants;
```

File: packages/flutter_tools/test/general.shard/asset_bundle_package_test.dart [hunk 4]
```diff
@@ -457,7 +457,7 @@ $assetsSection
     writeAssets('p/p/', assets);
     const String expectedAssetManifest =
         '{"packages/test_package/a/foo":["packages/test_package/a/foo"],'
-        '"packages/test_package/a/foo%5Bx%5D":["packages/test_package/a/foo%5Bx%5D"]}';
+        '"packages/test_package/a/foo[x]":["packages/test_package/a/foo[x]"]}';
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_package_test.dart:460]: can you also update this test to have explicit spaces?

File: packages/flutter/test/painting/image_resolution_test.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter/test/painting/image_resolution_test.dart:154]: Hmm. I think this is an artifact of a different approach I had earlier where I changed the variant lookup rather than the asset manifest itself. Though this test was effective at detecting the bug, I do think this would be more discoverable as a test against `asset.dart`, so I'll get it tested over there instead.

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:166]: Yeah, I think I went autopilot here. I'll get that fixed.

For context, I decided to consolidate the windows tests into one, so that we wouldn't have *N* duplicated tests.

File: packages/flutter_tools/lib/src/asset.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/asset.dart:647]: Good call. I was little overzealous in avoiding variables that are only used once.

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:195]: On second reading, I actually noticed that the test actually does use windows-style paths. Check out the use of `correctPathSeperators`

https://github.com/flutter/flutter/blob/9ace46137c4909effec401b49fb642e44d4cc15f/packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart#L180

However, this convo has pointed out that this is confusing, so I reversed the paradigm here, so-to-speak. By this I mean I declared the paths as windows paths and then convert them back to posix for the assertions.

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart [hunk 5]
```diff
@@ -194,46 +223,18 @@ flutter:
...
-      const String topLevelImage = 'assets/image.jpg';
-      const String secondLevelImage = 'assets/folder/secondLevel.jpg';
-      const String secondLevel2xVariant = 'assets/folder/2x/secondLevel.jpg';
-
-      final List<String> assets = <String>[
-        topLevelImage,
-        secondLevelImage,
-        secondLevel2xVariant
+      final List<String> expectedFooVariants = <String>[
+        withPosixPathSeparators(foo),
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:228]: Can we hard code the expectations, rather than processing them? It's difficult for me reading this code exactly what we're expecting the manifest to have.

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:228]: also on lines 232,233

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart [hunk 6]
```diff
@@ -135,12 +164,6 @@ flutter:
     late final Platform platform;
     late final FileSystem fs;
 
-    String correctPathSeparators(String path) {
-      // The in-memory file system is strict about slashes on Windows being the
-      // correct way. See https://github.com/google/file.dart/issues/112.
-      return path.replaceAll('/', fs.path.separator);
-    }
-
     setUpAll(() {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart:167]:
```suggestion
    setUp(() {
```

**Review by christopherfujino — APPROVED** [review]
Thanks for making this tricky change! LGTM (with the nit about setUpAll -> setUp)

File: packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart (hunk 6 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart]: Good observation. I actually thought I made this switch at some point, but apparently not 😆

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_variant_test.dart]: I feel that way all the time, either because: 1) I fixed something but forgot to commit; 2) I fixed something on a different branch; 3) I fixed some similar line, but forgot to apply the same fix to another function; 4) I've been staring at code too long and am imagining things.
