### PR TITLE
BottomNavigationBar: bug fix for dealing with animations with shifting tabs

### LINKED ISSUE #22226: Regression: bottom navigation bar color flooding animation is broken
## Steps to Reproduce

1. Create a skeleton app with the [Bottom Nav Bar demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/bottom_navigation_demo.dart) from the examples set to the home page.
2. [Expected](https://giphy.com/gifs/t8L2s82BwE2ITHuSob/html5) from the flutter gallery app currently in the Google App Store.
3. [Actual](https://giphy.com/gifs/A5NpYPpuS4viIyBzOk/html5) with source code from the flutter gallery compiled with the latest version in master channel.

## Logs

```
[  +59 ms] executing: [/Users/beckler/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/beckler/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/beckler/Documents/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/beckler/Documents/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d00b30ff8447821531b19c0549647157ddf041d6
[        ] executing: [/Users/beckler/Documents/flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 33 minutes ago
[   +1 ms] executing: [/Users/beckler/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +53 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.9.2-25-gd00b30ff8
[ +615 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/beckler/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           HT79D1A01855           device usb:4245815296X product:walleye model:Pixel_2 device:walleye transport_id:35
[  +20 ms] executing: idevice_id -h
[  +74 ms] /usr/bin/xcrun simctl list --json devices
[ +423 ms] Found plugin flutter_secure_storage at /Users/beckler/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2/
[ +157 ms] Found plugin flutter_secure_storage at /Users/beckler/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2/
[ +115 ms] /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell getprop
[ +131 ms] ro.hardware = walleye
[        ] ro.build.characteristics = nosdcard
[+1303 ms] Launching lib/main.dart on Pixel 2 in debug mode...
[  +48 ms] Initializing gradle...
[  +10 ms] Using gradle from /Users/beckler/Documents/dev/bugexample/android/gradlew.
[  +15 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +81 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +157 ms] executing: /Users/beckler/Documents/dev/bugexample/android/gradlew -v
[+1063 ms] 
           ------------------------------------------------------------
           Gradle 4.4
           ------------------------------------------------------------
           
           Build time:   2017-12-06 09:05:06 UTC
           Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82
           
           Groovy:       2.4.12
           Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
           JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
           OS:           Mac OS X 10.13.6 x86_64
[   +1 ms] Initializing gradle... (completed)
[   +1 ms] Resolving dependencies...
[        ] executing: [/Users/beckler/Documents/dev/bugexample/android/] /Users/beckler/Documents/dev/bugexample/android/gradlew app:properties
[+1452 ms] 
           ------------------------------------------------------------
           Project :app
           ------------------------------------------------------------
           
           allprojects: [project ':app']
           android: com.android.build.gradle.AppExtension_Decorated@6e1a26f2
           androidDependencies: task ':app:androidDependencies'
           ant: org.gradle.api.internal.project.DefaultAntBuilder@480df418
           antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@1643402b
           archivesBaseName: app
           artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@19913323
           asDynamicObject: DynamicObject for project ':app'
           assemble: task ':app:assemble'
           assembleAndroidTest: task ':app:assembleAndroidTest'
           assembleDebug: task ':app:assembleDebug'
           assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
           assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
           assembleDynamicProfile: task ':app:assembleDynamicProfile'
           assembleDynamicProfileUnitTest: task ':app:assembleDynamicProfileUnitTest'
           assembleDynamicRelease: task ':app:assembleDynamicRelease'
           assembleDynamicReleaseUnitTest: task ':app:assembleDynamicReleaseUnitTest'
           assembleProfile: task ':app:assembleProfile'
           assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
           assembleRelease: task ':app:assembleRelease'
           assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
           baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@2683ab55
           buildDependents: task ':app:buildDependents'
           buildDir: /Users/beckler/Documents/dev/bugexample/build/app
           buildFile: /Users/beckler/Documents/dev/bugexample/android/app/build.gradle
           buildNeeded: task ':app:buildNeeded'
           buildOutputs: BaseVariantOutput container
           buildPath: :
           buildScriptSource: org.gradle.groovy.scripts.TextResourceScriptSource@10936a9
           buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@d476cbb
           bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
           bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
           bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
           bundleAppClassesDynamicProfile: task ':app:bundleAppClassesDynamicProfile'
           bundleAppClassesDynamicProfileUnitTest: task ':app:bundleAppClassesDynamicProfileUnitTest'
           bundleAppClassesDynamicRelease: task ':app:bundleAppClassesDynamicRelease'
           bundleAppClassesDynamicReleaseUnitTest: task ':app:bundleAppClassesDynamicReleaseUnitTest'
           bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
           bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
           bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
           bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
           bundleDebugAndroidTestResources: task ':app:bundleDebugAndroidTestResources'
           bundleDebugResources: task ':app:bundleDebugResources'
           bundleDynamicProfileResources: task ':app:bundleDynamicProfileResources'
           bundleDynamicReleaseResources: task ':app:bundleDynamicReleaseResources'
           bundleProfileResources: task ':app:bundleProfileResources'
           bundleReleaseResources: task ':app:bundleReleaseResources'
           check: task ':app:check'
           checkDebugManifest: task ':app:checkDebugManifest'
           checkDynamicProfileManifest: task ':app:checkDynamicProfileManifest'
           checkDynamicReleaseManifest: task ':app:checkDynamicReleaseManifest'
           checkProfileManifest: task ':app:checkProfileManifest'
           checkReleaseManifest: task ':app:checkReleaseManifest'
           childProjects: {}
           class: class org.gradle.api.internal.project.DefaultProject_Decorated
           classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@1ddf4e1b
           cleanBuildCache: task ':app:cleanBuildCache'
           compileDebugAidl: task ':app:compileDebugAidl'
           compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
           compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
           compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
           compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
           compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
           compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
           compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
           compileDebugNdk: task ':app:compileDebugNdk'
           compileDebugRenderscript: task ':app:compileDebugRenderscript'
           compileDebugShaders: task ':app:compileDebugShaders'
           compileDebugSources: task ':app:compileDebugSources'
           compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
           compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
           compileDynamicProfileAidl: task ':app:compileDynamicProfileAidl'
           compileDynamicProfileJavaWithJavac: task ':app:compileDynamicProfileJavaWithJavac'
           compileDynamicProfileNdk: task ':app:compileDynamicProfileNdk'
           compileDynamicProfileRenderscript: task ':app:compileDynamicProfileRenderscript'
           compileDynamicProfileShaders: task ':app:compileDynamicProfileShaders'
           compileDynamicProfileSources: task ':app:compileDynamicProfileSources'
           compileDynamicProfileUnitTestJavaWithJavac: task ':app:compileDynamicProfileUnitTestJavaWithJavac'
           compileDynamicProfileUnitTestSources: task ':app:compileDynamicProfileUnitTestSources'
           compileDynamicReleaseAidl: task ':app:compileDynamicReleaseAidl'
           compileDynamicReleaseJavaWithJavac: task ':app:compileDynamicReleaseJavaWithJavac'
           compileDynamicReleaseNdk: task ':app:compileDynamicReleaseNdk'
           compileDynamicReleaseRenderscript: task ':app:compileDynamicReleaseRenderscript'
           compileDynamicReleaseShaders: task ':app:compileDynamicReleaseShaders'
           compileDynamicReleaseSources: task ':app:compileDynamicReleaseSources'
           compileDynamicReleaseUnitTestJavaWithJavac: task ':app:compileDynamicReleaseUnitTestJavaWithJavac'
           compileDynamicReleaseUnitTestSources: task ':app:compileDynamicReleaseUnitTestSources'
           compileLint: task ':app:compileLint'
           compileProfileAidl: task ':app:compileProfileAidl'
           compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
           compileProfileNdk: task ':app:compileProfileNdk'
           compileProfileRenderscript: task ':app:compileProfileRenderscript'
           compileProfileShaders: task ':app:compileProfileShaders'
           compileProfileSources: task ':app:compileProfileSources'
           compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
           compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
           compileReleaseAidl: task ':app:compileReleaseAidl'
           compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
           compileReleaseNdk: task ':app:compileReleaseNdk'
           compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
           compileReleaseShaders: task ':app:compileReleaseShaders'
           compileReleaseSources: task ':app:compileReleaseSources'
           compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
           compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
           components: SoftwareComponentInternal set
           configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@263d87f6
           configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@6ec951e6
           configurations: configuration container
           connectedAndroidTest: task ':app:connectedAndroidTest'
           connectedCheck: task ':app:connectedCheck'
           connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
           consumeConfigAttr: task ':app:consumeConfigAttr'
           convention: org.gradle.api.internal.plugins.DefaultConvention@58ddda30
           copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
           copyFlutterAssetsDynamicProfile: task ':app:copyFlutterAssetsDynamicProfile'
           copyFlutterAssetsDynamicRelease: task ':app:copyFlutterAssetsDynamicRelease'
           copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
           copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
           createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
           createDynamicProfileCompatibleScreenManifests: task ':app:createDynamicProfileCompatibleScreenManifests'
           createDynamicReleaseCompatibleScreenManifests: task ':app:createDynamicReleaseCompatibleScreenManifests'
           createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
           createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
           defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@3f15f8a6
           defaultTasks: []
           deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@755dda85
           dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@51bfe3a9
           depth: 1
           description: null
           deviceAndroidTest: task ':app:deviceAndroidTest'
           deviceCheck: task ':app:deviceCheck'
           displayName: project ':app'
           distsDir: /Users/beckler/Documents/dev/bugexample/build/app/distributions
           distsDirName: distributions
           docsDir: /Users/beckler/Documents/dev/bugexample/build/app/docs
           docsDirName: docs
           ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@6785bff4
           extensions: org.gradle.api.internal.plugins.DefaultConvention@58ddda30
           extractProguardFiles: task ':app:extractProguardFiles'
           fileOperations: org.gradle.api.internal.file.DefaultFileOperations@7745ab6a
           fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@6cd7def5
           flutter: FlutterExtension_Decorated@42dbda6d
           flutterBuildDebug: task ':app:flutterBuildDebug'
           flutterBuildDynamicProfile: task ':app:flutterBuildDynamicProfile'
           flutterBuildDynamicRelease: task ':app:flutterBuildDynamicRelease'
           flutterBuildProfile: task ':app:flutterBuildProfile'
           flutterBuildRelease: task ':app:flutterBuildRelease'
           flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
           generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
           generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
           generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
           generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
           generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
           generateDebugAssets: task ':app:generateDebugAssets'
           generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
           generateDebugResValues: task ':app:generateDebugResValues'
           generateDebugResources: task ':app:generateDebugResources'
           generateDebugSources: task ':app:generateDebugSources'
           generateDynamicProfileAssets: task ':app:generateDynamicProfileAssets'
           generateDynamicProfileBuildConfig: task ':app:generateDynamicProfileBuildConfig'
           generateDynamicProfileResValues: task ':app:generateDynamicProfileResValues'
           generateDynamicProfileResources: task ':app:generateDynamicProfileResources'
           generateDynamicProfileSources: task ':app:generateDynamicProfileSources'
           generateDynamicReleaseAssets: task ':app:generateDynamicReleaseAssets'
           generateDynamicReleaseBuildConfig: task ':app:generateDynamicReleaseBuildConfig'
           generateDynamicReleaseResValues: task ':app:generateDynamicReleaseResValues'
           generateDynamicReleaseResources: task ':app:generateDynamicReleaseResources'
           generateDynamicReleaseSources: task ':app:generateDynamicReleaseSources'
           generateProfileAssets: task ':app:generateProfileAssets'
           generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
           generateProfileResValues: task ':app:generateProfileResValues'
           generateProfileResources: task ':app:generateProfileResources'
           generateProfileSources: task ':app:generateProfileSources'
           generateReleaseAssets: task ':app:generateReleaseAssets'
           generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
           generateReleaseResValues: task ':app:generateReleaseResValues'
           generateReleaseResources: task ':app:generateReleaseResources'
           generateReleaseSources: task ':app:generateReleaseSources'
           gradle: build 'android'
           group: android
           identityPath: :app
           inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@8eba7dd
           installDebug: task ':app:installDebug'
           installDebugAndroidTest: task ':app:installDebugAndroidTest'
           installDynamicProfile: task ':app:installDynamicProfile'
           installDynamicRelease: task ':app:installDynamicRelease'
           installProfile: task ':app:installProfile'
           installRelease: task ':app:installRelease'
           javaPreCompileDebug: task ':app:javaPreCompileDebug'
           javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
           javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
           javaPreCompileDynamicProfile: task ':app:javaPreCompileDynamicProfile'
           javaPreCompileDynamicProfileUnitTest: task ':app:javaPreCompileDynamicProfileUnitTest'
           javaPreCompileDynamicRelease: task ':app:javaPreCompileDynamicRelease'
           javaPreCompileDynamicReleaseUnitTest: task ':app:javaPreCompileDynamicReleaseUnitTest'
           javaPreCompileProfile: task ':app:javaPreCompileProfile'
           javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
           javaPreCompileRelease: task ':app:javaPreCompileRelease'
           javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
           layout: org.gradle.api.internal.file.DefaultProjectLayout@52af5351
           libsDir: /Users/beckler/Documents/dev/bugexample/build/app/libs
           libsDirName: libs
           lint: task ':app:lint'
           lintDebug: task ':app:lintDebug'
           lintDynamicProfile: task ':app:lintDynamicProfile'
           lintDynamicRelease: task ':app:lintDynamicRelease'
           lintProfile: task ':app:lintProfile'
           lintRelease: task ':app:lintRelease'
           lintVitalRelease: task ':app:lintVitalRelease'
           logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@49b7b5a0
           logging: org.gradle.internal.logging.services.DefaultLoggingManager@5d1f87
           mainApkListPersistenceDebug: task ':app:mainApkListPersistenceDebug'
           mainApkListPersistenceDebugAndroidTest: task ':app:mainApkListPersistenceDebugAndroidTest'
           mainApkListPersistenceDynamicProfile: task ':app:mainApkListPersistenceDynamicProfile'
           mainApkListPersistenceDynamicRelease: task ':app:mainApkListPersistenceDynamicRelease'
           mainApkListPersistenceProfile: task ':app:mainApkListPersistenceProfile'
           mainApkListPersistenceRelease: task ':app:mainApkListPersistenceRelease'
           mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
           mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
           mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
           mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
           mergeDebugAssets: task ':app:mergeDebugAssets'
           mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
           mergeDebugResources: task ':app:mergeDebugResources'
           mergeDebugShaders: task ':app:mergeDebugShaders'
           mergeDynamicProfileAssets: task ':app:mergeDynamicProfileAssets'
           mergeDynamicProfileJniLibFolders: task ':app:mergeDynamicProfileJniLibFolders'
           mergeDynamicProfileResources: task ':app:mergeDynamicProfileResources'
           mergeDynamicProfileShaders: task ':app:mergeDynamicProfileShaders'
           mergeDynamicReleaseAssets: task ':app:mergeDynamicReleaseAssets'
           mergeDynamicReleaseJniLibFolders: task ':app:mergeDynamicReleaseJniLibFolders'
           mergeDynamicReleaseResources: task ':app:mergeDynamicReleaseResources'
           mergeDynamicReleaseShaders: task ':app:mergeDynamicReleaseShaders'
           mergeProfileAssets: task ':app:mergeProfileAssets'
           mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
           mergeProfileResources: task ':app:mergeProfileResources'
           mergeProfileShaders: task ':app:mergeProfileShaders'
           mergeReleaseAssets: task ':app:mergeReleaseAssets'
           mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
           mergeReleaseResources: task ':app:mergeReleaseResources'
           mergeReleaseShaders: task ':app:mergeReleaseShaders'
           mockableAndroidJar: task ':app:mockableAndroidJar'
           modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@1c49a553
           modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@2cd81b2a
           module: org.gradle.api.internal.artifacts.ProjectBackedModule@3767b9e8
           name: app
           normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@49493c48
           objects: org.gradle.api.internal.model.DefaultObjectFactory@61d4cbeb
           org.gradle.jvmargs: -Xmx1536M
           packageDebug: task ':app:packageDebug'
           packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
           packageDynamicProfile: task ':app:packageDynamicProfile'
           packageDynamicRelease: task ':app:packageDynamicRelease'
           packageProfile: task ':app:packageProfile'
           packageRelease: task ':app:packageRelease'
           parent: root project 'android'
           parentIdentifier: root project 'android'
           path: :app
           platformAttrExtractor: task ':app:platformAttrExtractor'
           pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@99d4171
           plugins: [org.gradle.api.plugins.HelpTasksPlugin@28da017a, com.android.build.gradle.api.AndroidBasePlugin@1d0c586b, org.gradle.language.base.plugins.LifecycleBasePlugin@7958d490, org.gradle.api.plugins.BasePlugin@449f44be, org.gradle.api.plugins.ReportingBasePlugin@391916e8, org.gradle.platform.base.plugins.ComponentBasePlugin@3b4bde03, org.gradle.language.base.plugins.LanguageBasePlugin@4a9421d4, org.gradle.platform.base.plugins.BinaryBasePlugin@16311bfe, org.gradle.api.plugins.JavaBasePlugin@5d5c6d35, com.android.build.gradle.AppPlugin@36db146e, FlutterPlugin@12028f8d]
           preBuild: task ':app:preBuild'
           preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
           preDebugBuild: task ':app:preDebugBuild'
           preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
           preDynamicProfileBuild: task ':app:preDynamicProfileBuild'
           preDynamicProfileUnitTestBuild: task ':app:preDynamicProfileUnitTestBuild'
           preDynamicReleaseBuild: task ':app:preDynamicReleaseBuild'
           preDynamicReleaseUnitTestBuild: task ':app:preDynamicReleaseUnitTestBuild'
           preProfileBuild: task ':app:preProfileBuild'
           preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
           preReleaseBuild: task ':app:preReleaseBuild'
           preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
           prepareLintJar: task ':app:prepareLintJar'
           preparePUBLISHED_DEXDebugAndroidTestForPublishing: task ':app:preparePUBLISHED_DEXDebugAndroidTestForPublishing'
           preparePUBLISHED_DEXDebugForPublishing: task ':app:preparePUBLISHED_DEXDebugForPublishing'
           preparePUBLISHED_DEXDynamicProfileForPublishing: task ':app:preparePUBLISHED_DEXDynamicProfileForPublishing'
           preparePUBLISHED_DEXDynamicReleaseForPublishing: task ':app:preparePUBLISHED_DEXDynamicReleaseForPublishing'
           preparePUBLISHED_DEXProfileForPublishing: task ':app:preparePUBLISHED_DEXProfileForPublishing'
           preparePUBLISHED_DEXReleaseForPublishing: task ':app:preparePUBLISHED_DEXReleaseForPublishing'
           preparePUBLISHED_JAVA_RESDebugAndroidTestForPublishing: task ':app:preparePUBLISHED_JAVA_RESDebugAndroidTestForPublishing'
           preparePUBLISHED_JAVA_RESDebugForPublishing: task ':app:preparePUBLISHED_JAVA_RESDebugForPublishing'
           preparePUBLISHED_JAVA_RESDynamicProfileForPublishing: task ':app:preparePUBLISHED_JAVA_RESDynamicProfileForPublishing'
           preparePUBLISHED_JAVA_RESDynamicReleaseForPublishing: task ':app:preparePUBLISHED_JAVA_RESDynamicReleaseForPublishing'
           preparePUBLISHED_JAVA_RESProfileForPublishing: task ':app:preparePUBLISHED_JAVA_RESProfileForPublishing'
           preparePUBLISHED_JAVA_RESReleaseForPublishing: task ':app:preparePUBLISHED_JAVA_RESReleaseForPublishing'
           preparePUBLISHED_NATIVE_LIBSDebugAndroidTestForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSDebugAndroidTestForPublishing'
           preparePUBLISHED_NATIVE_LIBSDebugForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSDebugForPublishing'
           preparePUBLISHED_NATIVE_LIBSDynamicProfileForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSDynamicProfileForPublishing'
           preparePUBLISHED_NATIVE_LIBSDynamicReleaseForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSDynamicReleaseForPublishing'
           preparePUBLISHED_NATIVE_LIBSProfileForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSProfileForPublishing'
           preparePUBLISHED_NATIVE_LIBSReleaseForPublishing: task ':app:preparePUBLISHED_NATIVE_LIBSReleaseForPublishing'
           processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
           processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
           processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
           processDebugJavaRes: task ':app:processDebugJavaRes'
           processDebugManifest: task ':app:processDebugManifest'
           processDebugResources: task ':app:processDebugResources'
           processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
           processDynamicProfileJavaRes: task ':app:processDynamicProfileJavaRes'
           processDynamicProfileManifest: task ':app:processDynamicProfileManifest'
           processDynamicProfileResources: task ':app:processDynamicProfileResources'
           processDynamicProfileUnitTestJavaRes: task ':app:processDynamicProfileUnitTestJavaRes'
           processDynamicReleaseJavaRes: task ':app:processDynamicReleaseJavaRes'
           processDynamicReleaseManifest: task ':app:processDynamicReleaseManifest'
           processDynamicReleaseResources: task ':app:processDynamicReleaseResources'
           processDynamicReleaseUnitTestJavaRes: task ':app:processDynamicReleaseUnitTestJavaRes'
           processOperations: org.gradle.api.internal.file.DefaultFileOperations@7745ab6a
           processProfileJavaRes: task ':app:processProfileJavaRes'
           processProfileManifest: task ':app:processProfileManifest'
           processProfileResources: task ':app:processProfileResources'
           processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
           processReleaseJavaRes: task ':app:processReleaseJavaRes'
           processReleaseManifest: task ':app:processReleaseManifest'
           processReleaseResources: task ':app:processReleaseResources'
           processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
           project: project ':app'
           projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@58af0e2c
           projectDir: /Users/beckler/Documents/dev/bugexample/android/app
           projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
           projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@5884c20d
           projectPath: :app
           projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@1fc8d165
           properties: {...}
           providers: org.gradle.api.internal.provider.DefaultProviderFactory@5179d3fc
           reportBuildArtifactsDebug: task ':app:reportBuildArtifactsDebug'
           reportBuildArtifactsDynamicProfile: task ':app:reportBuildArtifactsDynamicProfile'
           reportBuildArtifactsDynamicRelease: task ':app:reportBuildArtifactsDynamicRelease'
           reportBuildArtifactsProfile: task ':app:reportBuildArtifactsProfile'
           reportBuildArtifactsRelease: task ':app:reportBuildArtifactsRelease'
           reporting: org.gradle.api.reporting.ReportingExtension_Decorated@7c3d9d24
           reportsDir: /Users/beckler/Documents/dev/bugexample/build/app/reports
           repositories: repository container
           resolveConfigAttr: task ':app:resolveConfigAttr'
           resourceLoader: org.gradle.internal.resource.transfer.DefaultUriTextResourceLoader@5c4332e1
           resources: org.gradle.api.internal.resources.DefaultResourceHandler@22a907ce
           rootDir: /Users/beckler/Documents/dev/bugexample/android
           rootProject: root project 'android'
           script: false
           scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@7b33b907
           scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@6bf7cff8
           serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@2e663c5d
           services: ProjectScopeServices
           signingReport: task ':app:signingReport'
           sourceCompatibility: 1.8
           sourceSets: SourceSet container
           splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
           splitsDiscoveryTaskDynamicProfile: task ':app:splitsDiscoveryTaskDynamicProfile'
           splitsDiscoveryTaskDynamicRelease: task ':app:splitsDiscoveryTaskDynamicRelease'
           splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
           splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
           standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@5d1f87
           state: project state 'EXECUTED'
           status: integration
           subprojects: []
           targetCompatibility: 1.8
           tasks: task set
           test: task ':app:test'
           testDebugUnitTest: task ':app:testDebugUnitTest'
           testDynamicProfileUnitTest: task ':app:testDynamicProfileUnitTest'
           testDynamicReleaseUnitTest: task ':app:testDynamicReleaseUnitTest'
           testProfileUnitTest: task ':app:testProfileUnitTest'
           testReleaseUnitTest: task ':app:testReleaseUnitTest'
           testReportDir: /Users/beckler/Documents/dev/bugexample/build/app/reports/tests
           testReportDirName: tests
           testResultsDir: /Users/beckler/Documents/dev/bugexample/build/app/test-results
           testResultsDirName: test-results
           transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
           transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
           transformClassesWithDexBuilderForDynamicProfile: task ':app:transformClassesWithDexBuilderForDynamicProfile'
           transformClassesWithDexBuilderForDynamicRelease: task ':app:transformClassesWithDexBuilderForDynamicRelease'
           transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
           transformClassesWithDexBuilderForRelease: task ':app:transformClassesWithDexBuilderForRelease'
           transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
           transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
           transformDexArchiveWithDexMergerForDynamicProfile: task ':app:transformDexArchiveWithDexMergerForDynamicProfile'
           transformDexArchiveWithDexMergerForDynamicRelease: task ':app:transformDexArchiveWithDexMergerForDynamicRelease'
           transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
           transformDexArchiveWithDexMergerForRelease: task ':app:transformDexArchiveWithDexMergerForRelease'
           transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
           transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
           transformDexArchiveWithExternalLibsDexMergerForDynamicProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForDynamicProfile'
           transformDexArchiveWithExternalLibsDexMergerForDynamicRelease: task ':app:transformDexArchiveWithExternalLibsDexMergerForDynamicRelease'
           transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
           transformDexArchiveWithExternalLibsDexMergerForRelease: task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'
           transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
           transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
           transformNativeLibsWithMergeJniLibsForDynamicProfile: task ':app:transformNativeLibsWithMergeJniLibsForDynamicProfile'
           transformNativeLibsWithMergeJniLibsForDynamicRelease: task ':app:transformNativeLibsWithMergeJniLibsForDynamicRelease'
           transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
           transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
           transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
           transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
           transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
           transformResourcesWithMergeJavaResForDynamicProfile: task ':app:transformResourcesWithMergeJavaResForDynamicProfile'
           transformResourcesWithMergeJavaResForDynamicProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForDynamicProfileUnitTest'
           transformResourcesWithMergeJavaResForDynamicRelease: task ':app:transformResourcesWithMergeJavaResForDynamicRelease'
           transformResourcesWithMergeJavaResForDynamicReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForDynamicReleaseUnitTest'
           transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
           transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
           transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
           transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
           uninstallAll: task ':app:uninstallAll'
           uninstallDebug: task ':app:uninstallDebug'
           uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
           uninstallDynamicProfile: task ':app:uninstallDynamicProfile'
           uninstallDynamicRelease: task ':app:uninstallDynamicRelease'
           uninstallProfile: task ':app:uninstallProfile'
           uninstallRelease: task ':app:uninstallRelease'
           validateSigningDebug: task ':app:validateSigningDebug'
           validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
           validateSigningDynamicProfile: task ':app:validateSigningDynamicProfile'
           validateSigningDynamicRelease: task ':app:validateSigningDynamicRelease'
           validateSigningProfile: task ':app:validateSigningProfile'
           validateSigningRelease: task ':app:validateSigningRelease'
           version: unspecified
           writeDebugApplicationId: task ':app:writeDebugApplicationId'
           writeDynamicProfileApplicationId: task ':app:writeDynamicProfileApplicationId'
           writeDynamicReleaseApplicationId: task ':app:writeDynamicReleaseApplicationId'
           writeProfileApplicationId: task ':app:writeProfileApplicationId'
           writeReleaseApplicationId: task ':app:writeReleaseApplicationId'
           1 actionable task: 1 executed
[   +6 ms] Resolving dependencies... (completed)
[   +3 ms] executing: /Users/beckler/Library/Android/sdk/build-tools/27.0.3/aapt dump xmltree /Users/beckler/Documents/dev/bugexample/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +65 ms] Exit code 0 from: /Users/beckler/Library/Android/sdk/build-tools/27.0.3/aapt dump xmltree /Users/beckler/Documents/dev/bugexample/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: package="com.beckler.bugexample" (Raw: "com.beckler.bugexample")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x12
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=24)
                 A: android:label(0x01010001)="bugexample" (Raw: "bugexample")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:allowBackup(0x01010280)=(type 0x12)0xffffffff
                 E: activity (line=30)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.beckler.bugexample.MainActivity" (Raw: "com.beckler.bugexample.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=44)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=48)
                     E: action (line=49)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=51)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[  +10 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell -x logcat -v time -t 1
[  +88 ms] Exit code 0 from: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           09-24 14:56:42.089 E/QtiImsExtUtils( 2006): isCarrierConfigEnabled bundle is null
[   +7 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell -x logcat -v time
[ +664 ms] DependencyChecker: nothing is modified after 2018-09-24 14:39:37.236.
[   +4 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb version
[  +19 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as /Users/beckler/Library/Android/sdk/platform-tools/adb
[   +6 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb start-server
[  +15 ms] Building APK
[  +15 ms] Gradle task 'assembleDebug'...
[   +3 ms] executing: [/Users/beckler/Documents/dev/bugexample/android/] /Users/beckler/Documents/dev/bugexample/android/gradlew -Pverbose=true -Ptarget=/Users/beckler/Documents/dev/bugexample/lib/main.dart -Ptarget-platform=android-arm64 assembleDebug
[+2514 ms] [  +14 ms] executing: [/Users/beckler/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] [  +68 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/Users/beckler/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [   +1 ms] master
[        ] [        ] executing: [/Users/beckler/Documents/flutter/] git ls-remote --get-url origin
[  +11 ms] [  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[  +10 ms] [   +1 ms] executing: [/Users/beckler/Documents/flutter/] git log -n 1 --pretty=format:%H
[  +10 ms] [  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] [        ] d00b30ff8447821531b19c0549647157ddf041d6
[        ] [        ] executing: [/Users/beckler/Documents/flutter/] git log -n 1 --pretty=format:%ar
[  +22 ms] [  +18 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] [        ] 34 minutes ago
[        ] [   +1 ms] executing: [/Users/beckler/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] [  +49 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v0.9.2-25-gd00b30ff8
[ +437 ms] [ +434 ms] Found plugin flutter_secure_storage at /Users/beckler/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2/
[ +159 ms] [ +163 ms] Found plugin flutter_secure_storage at /Users/beckler/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2/
[ +824 ms] [ +828 ms] Skipping kernel compilation. Fingerprint match.
[ +368 ms] [ +359 ms] Building bundle
[        ] [   +3 ms] Writing asset files to /Users/beckler/Documents/dev/bugexample/build/app/intermediates/flutter/debug/flutter_assets
[ +200 ms] [ +207 ms] Wrote /Users/beckler/Documents/dev/bugexample/build/app/intermediates/flutter/debug/flutter_assets
[  +26 ms] [  +16 ms] "flutter bundle" took 1,813ms.
[ +851 ms] 55 actionable tasks: 4 executed, 51 up-to-date
[ +425 ms] Gradle task 'assembleDebug'... (completed)
[ +351 ms] calculateSha: LocalDirectory: '/Users/beckler/Documents/dev/bugexample/build/app/outputs/apk'/app.apk
[ +697 ms] Built build/app/outputs/apk/debug/app-debug.apk.
[   +1 ms] executing: /Users/beckler/Library/Android/sdk/build-tools/27.0.3/aapt dump xmltree /Users/beckler/Documents/dev/bugexample/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +16 ms] Exit code 0 from: /Users/beckler/Library/Android/sdk/build-tools/27.0.3/aapt dump xmltree /Users/beckler/Documents/dev/bugexample/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: package="com.beckler.bugexample" (Raw: "com.beckler.bugexample")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x12
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=24)
                 A: android:label(0x01010001)="bugexample" (Raw: "bugexample")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:allowBackup(0x01010280)=(type 0x12)0xffffffff
                 E: activity (line=30)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.beckler.bugexample.MainActivity" (Raw: "com.beckler.bugexample.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=44)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=48)
                     E: action (line=49)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=51)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +1 ms] Stopping app 'app.apk' on Pixel 2.
[        ] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell am force-stop com.beckler.bugexample
[ +130 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell pm list packages com.beckler.bugexample
[  +86 ms] package:com.beckler.bugexample
[   +7 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell cat /data/local/tmp/sky.com.beckler.bugexample.sha1
[  +98 ms] c63ddac561f925e94b06d980b3aae8cc6363fdea
[   +2 ms] Latest build already installed.
[        ] Pixel 2 startApp
[   +2 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.beckler.bugexample/com.beckler.bugexample.MainActivity
[ +134 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.beckler.bugexample/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +334 ms] Observatory URL on device: http://127.0.0.1:37029/
[   +2 ms] executing: /Users/beckler/Library/Android/sdk/platform-tools/adb -s HT79D1A01855 forward tcp:0 tcp:37029
[  +14 ms] 57036
[        ] Forwarded host port 57036 to device port 37029 for Observatory
[   +6 ms] Connecting to service protocol: http://127.0.0.1:57036/
[ +307 ms] Successfully connected to service protocol: http://127.0.0.1:57036/
[   +6 ms] getVM: {}
[  +20 ms] getIsolate: {isolateId: isolates/169184686}
[   +7 ms] _flutter.listViews: {isolateId: isolates/169184686}
[  +87 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] _createDevFS: {fsName: bugexample}
[  +31 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.beckler.bugexample/cache/bugexampleWTEMPB/bugexample/)
[   +3 ms] Updating assets
[ +319 ms] Syncing files to device Pixel 2...
[   +3 ms] DevFS: Starting sync from LocalDirectory: '/Users/beckler/Documents/dev/bugexample'
[        ] Scanning project files
[   +7 ms] Scanning package files
[ +181 ms] Scanning asset files
[   +1 ms] Scanning for deleted files
[  +14 ms] Compiling dart to kernel with 441 updated files
[   +7 ms] /Users/beckler/Documents/flutter/bin/cache/dart-sdk/bin/dart /Users/beckler/Documents/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/beckler/Documents/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages /Users/beckler/Documents/dev/bugexample/.packages --filesystem-scheme org-dartlang-root
[+2013 ms] Updating files
[ +178 ms] DevFS: Sync finished
[        ] Syncing files to device Pixel 2... (completed)
[        ] Synced 0.8MB.
[   +2 ms] _flutter.listViews: {isolateId: isolates/169184686}
[   +9 ms] Connected to _flutterView/0x7077a28f98.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Pixel 2 is available at: http://127.0.0.1:57036/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

```
Analyzing bugexample...                                          
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel master, v0.9.3-pre.25, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.3-pre.25 at /Users/beckler/Documents/flutter
    • Framework revision d00b30ff84 (21 minutes ago), 2018-09-24 14:23:33 -0400
    • Engine revision f4aadb11cf
    • Dart version 2.1.0-dev.5.0.flutter-654c4babc8

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/beckler/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Pixel 2 • HT79D1A01855 • android-arm64 • Android 9 (API 28)

• No issues found!
```

### PR DESCRIPTION
**Pull request by beckler**
Should fix #22226.

Code introduced in #20890 caused a regression that broke color flooding animations in a `BottomNavigationBar` that has `BottomNavigationBarType.shifting`.

The original issue (#19653) dealt with background color changes not occurring until another tab was selected. The result is that the background color instantly changes whenever the state changes **and** when the widget changes, instead of allowing a new widget to animate the background color change.

Here's what it currently looks like: [Actual](https://giphy.com/gifs/A5NpYPpuS4viIyBzOk/html5)
Here's what it should look like: [Expected](https://giphy.com/gifs/t8L2s82BwE2ITHuSob/html5)

Note: I may need some advice on how to test this.

### CODE REVIEW

**Review by mklim — CHANGES_REQUESTED** [review]
Thank you for your contribution!

This code LGTM but should be tested before it's merged. Unfortunately I think the only way to check the animation is to [write a golden file test](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter) to verify different keyframes as the animation is playing. That's going to be involved because it will require committing the screenshots to the goldens repo halfway through. You'll need to make a second PR at that point to commit the images.

No worries if you don't think you can get around to updating this PR. Eventually a Flutter maintainer will be able to pick this up and add in the test instead.

**Comment by tvolkert** [comment]
@beckler, do you anticipate being able to add a test for this as @mklim describes?

**Comment by beckler** [comment]
@tvolkert So I spent a small amount of time looking into this, and while it actually looks quite easy to write the tests, I was unsure how to create the screenshots after looking in the goldens repo.

**Comment by tvolkert** [comment]
@beckler our processes need some work here (we're scoping out what it'd take to have a dedicated storage, visualization, and approvals solution for golden files).  In the meantime,  https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter has the details (look for the `--update-goldens` reference), scrappy as they are.

The Cliffs Notes version is:
1. You write the test assuming the golden file is there
1. You run the test with the `--update-goldens` flag, which will create the missing golden file.
1. You navigate to `$FLUTTER_ROOT/bin/cache/pkg/goldens` and discover that it's actually a nested Git clone of the `flutter/goldens` GitHub repository -- with pending changes (namely, the newly created golden file).
1. You land those changes via a separate commit to the `flutter/goldens` GitHub repository (send a separate PR and @ mention me).
1. You update the `bin/internal/goldens.version` in this PR to reference the newly created commit you just landed in the other repo.

I apologize for the rigamarole -- like I said, we're looking into what it'd take to improve that process.

**Comment by beckler** [comment]
@tvolkert Ahhh, okay. I think I see how this works now. I'll spin up a Linux VM and take a shot at it tonight.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 1]
```diff
@@ -782,6 +782,57 @@ void main() {
...
+            );
+          },
+        ),
+      ),
+    );
+
+    await tester.tap(find.text('Green'));
+
+    for (int pump = 0; pump < 8; pump++) {
+      await tester.pump(const Duration(milliseconds: 30));
```
Comment (tvolkert) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart]: afaik you shouldn't need the duration in this call to `pump()` - does the test fail without it?

**Review by tvolkert — COMMENTED** [review]
LGTM.  Leaving the approval to @HansMuller

**Comment by tvolkert** [comment]
FYI, I merged the PR on the goldens repo, so your commit hash is `ffe7e5ceaeccaa7c9419ec44eff96c31f4fc2601`

**Review by HansMuller — APPROVED** [review]
This is a nice improvement to the shifting BottomNavigationBar animation. Well done!

LGTM

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 1 above)
Comment (beckler) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart]: So `.pumpAndSettle()` has a default duration of 100ms, but `.pump()` doesn't have a default duration. Whenever I did it without defining a duration, all the goldens generated were the same image, and they were all the first frame. So it seems that without a duration, the animation never occurs because it loops through them all instantly and never tests past the first frame.

**Comment by tvolkert** [comment]
You'll need to update https://github.com/flutter/flutter/blob/master/bin/internal/goldens.version in this PR as well to point to `ffe7e5ceaeccaa7c9419ec44eff96c31f4fc2601` in order for the tests to pass

**Comment by beckler** [comment]
Hey @tvolkert, it looks like the images I initially uploaded were actually generated from macOS, so I created another PR with images generated from linux. flutter/goldens#21

I also updated the test to skip on non-linux platforms.

**Comment by tvolkert** [comment]
Thanks!  I merged it in the goldens repo -- commit hash `8c478bbaf27447f3d612959705b305e7d1293526`
