### PR TITLE
Prepare images for tests individually to enable clean up of cache.

### LINKED ISSUE #149288: imageCache.clear() in tear down of one test causes usage after disposal in other test.
I tried to fix leaks in a test by adding imageCache.clear to its tear down , but it broke other test.

Steps:
1. Find the test ['DecoratedBox handles loading images'](https://github.com/flutter/flutter/blob/697d99fae8b3f5c99fc86d1750204bfd6fb58ce8/packages/flutter/test/widgets/box_decoration_test.dart#L40)
2. Add line `addTearDown(imageCache.clear);` somewhere to it
3. Run `flutter test test/widgets/box_decoration_test.dart`
4. See next test failed with usage of image after disposal on `await tester.idle();`

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/149288

### CODE REVIEW

File: packages/flutter/test/widgets/box_decoration_test.dart [hunk 1]
```diff
@@ -27,20 +32,25 @@ class TestImageProvider extends ImageProvider<TestImageProvider> {
...
   AutomatedTestWidgetsFlutterBinding();
-  TestImageProvider.image = await decodeImageFromList(Uint8List.fromList(kTransparentImage));
+  await TestImageProvider.prepareImages(2);
 
-  testWidgets('DecoratedBox handles loading images',
-  // TODO(polina-c): dispose ImageStreamCompleterHandle, https://github.com/flutter/flutter/issues/145599 [leaks-to-clean]
-  experimentalLeakTesting: LeakTesting.settings.withIgnoredAll(),
-  (WidgetTester tester) async {
+  testWidgets('DecoratedBox handles loading images', (WidgetTester tester) async {
+    addTearDown(imageCache.clear);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/box_decoration_test.dart:53]: It is a bit of a smell that you have to manually clear the cache in tests. The cache should be more or less transparent.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/box_decoration_test.dart (hunk 1 above)
Comment (polina-c) [reply packages/flutter/test/widgets/box_decoration_test.dart:53]: I would say it is more for test isolation, than for functionality. The cache is transparent for functionality.
