### PR TITLE
Detach debugger when VM connection fails on iOS

### LINKED ISSUE #68035: Devicelab failure: timed out waiting for app to launch
For example:

```
2020-10-13T09:43:33.468252: stdout: [ +268 ms] [100%] Connecting to remote debug server
stdout: [        ] -------------------------
2020-10-13T09:43:33.505865: stdout: [  +37 ms] (lldb) command source -s 0 '/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'
stdout: [        ] Executing commands in '/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'.
2020-10-13T09:43:33.505961: stdout: [        ] (lldb)     platform select remote-ios --sysroot '/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols'
2020-10-13T09:43:33.506096: stdout: [        ]   Platform: remote-ios
stdout: [        ]  Connected: no
2020-10-13T09:43:33.506262: stdout: [        ]   SDK Path: "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols"
2020-10-13T09:43:33.506327: stdout: [        ] (lldb)     target create "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos/Runner.app"
2020-10-13T09:43:36.760753: stdout: [+3254 ms] Current executable set to '/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos/Runner.app' (arm64).
stdout: [        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B/Runner.app"
2020-10-13T09:43:36.974998: stdout: [ +214 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:62737"
2020-10-13T09:43:36.975311: stdout: [        ] (lldb)     script fruitstrap_output_path=""
2020-10-13T09:43:36.975794: stdout: [        ] (lldb)     script fruitstrap_error_path=""
2020-10-13T09:43:36.976224: stdout: [        ] (lldb)     target modules search-paths add /usr "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/usr" /System "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/System" "/private/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B" "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos" "/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B" "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos" /Developer "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/Developer"
2020-10-13T09:43:36.990976: stdout: [  +14 ms] (lldb)     command script import "/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.py"
2020-10-13T09:43:36.995190: stdout: [   +4 ms] (lldb)     command script add -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.connect_command connect
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.run_command run
2020-10-13T09:43:36.995296: stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.autoexit_command autoexit
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.safequit_command safequit
2020-10-13T09:43:36.995347: stdout: [        ] (lldb)     connect
2020-10-13T09:43:37.025240: stdout: [  +29 ms] (lldb)     run
2020-10-13T09:44:07.054785: stdout: [+30030 ms] error: process launch failed: timed out waiting for app to launch
2020-10-13T09:44:07.054899: stderr: [        ] Could not run build/ios/iphoneos/Runner.app on 87b7be763fbf79fb324179b431f26198d2338da2.
2020-10-13T09:44:07.054953: stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
2020-10-13T09:44:07.055108: stderr: [        ]   open ios/Runner.xcworkspace
2020-10-13T09:44:07.055470: stdout: [        ] Installing and launching... (completed in 38.5s)
2020-10-13T09:44:07.059515: stdout: [   +4 ms] "flutter drive" took 54,621ms.
2020-10-13T09:44:07.064924: stderr: [   +5 ms] Application failed to start. Will not run test. Quitting.
2020-10-13T09:44:07.065435: stderr: [        ] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:244:9)
```

Many questions:

- What actual process here is failing?
- do we know some possible reasons?
- Would retrying work, or is this a "phone in a bad state" problem?

@xster @jmagman

### PR DESCRIPTION
**Pull request by jmagman**
## Description
When the debugger attaches but the tool cannot connect to the VM service (for any reason), detach the debugger before failing.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/68035

## Tests

Added a detach test.  I know this is mock heavy but the code path is hard to test... We can reinvestigate with all our other mocks once we know what our limitations are in null safety land.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 1]
```diff
@@ -412,6 +415,13 @@ Error launching app. Try launching from within Xcode via:
     open ios/Runner.xcworkspace
 
 Your Xcode version may be too old for your iOS version.
+═══════════════════════════════════════════════════════════════════════════════════''',
+        emphasis: true);
+  } else if (stdout.contains(processLaunchFailedError)) {
+    logger.printError('''
+═══════════════════════════════════════════════════════════════════════════════════
+Could not attach the debugger.
+Try uninstalling the app from your device and retrying.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:424]: @jonahwilliams Added this after your LGTM.

**Comment by jmagman** [comment]
Landing to green the tree.  We can wordsmith that warning message later.
