### PR TITLE
Relands Fix FlutterError.onError in debug mode

### LINKED ISSUE #47447: FlutterError.onError doesn't work
few days ago, i upgrade flutter version form 1.9(maybe 1.6) to 1.12

i used use `FlutterError.onError` and `runZoned` get some error logs,but today i find FlutterError.onError doesn't work. i'm not sure the reason is flutter upgrade.

here is my code(Simplified)
[testing errors](https://flutter.dev/docs/testing/errors)
```dart
import 'package:flutter/material.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) async {
    print('FlutterError.onError!!!');
    FlutterError.dumpErrorToConsole(details);
  };

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter error'),
        ),
        body: ListView(
          children: <Widget>[
            RaisedButton(
              onPressed: () {
                // throw error
                var tmp = {};
                return tmp['aa']['bb'];
              },
              child: Text('Text error'),
            ),
            Container(
              width: 100,
              height: 100,
              color: Colors.amber,
            )
          ],
        ),
      ),
    );
  }
}
```

when i click button `Text error` , console can't output `FlutterError.onError!!!`.

## Logs
`flutter doctor -v`
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\xxx\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\软件\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\软件\android studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • PBCM30 • 6306b2a1 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

Previous PR change the way that the testWidgets intercepts error. It was a bad decision, and i updated it in this pr.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/47447

## Tests

I added the following tests:

See files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 1]
```diff
@@ -2276,11 +2276,11 @@ class TestWidgetInspectorService extends Object with WidgetInspectorService {
       );
     }, skip: isBrowser);
 
-    testWidgets('ext.flutter.inspector.structuredErrors', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/widgets/widget_inspector_test.dart:2279]: I have to change this part because the testWidget overrides the onError directly which is essential to make sure present error is called. I think this change is fine because the structure error should only be applicable in non widget test environment.

Comment (chunhtai) [reply packages/flutter/test/widgets/widget_inspector_test.dart:2279]: I previously attempt to make testWidget overrides presentError as well, but it was a bad idea because it will bleed a lot of error catching logic into the next test. Furthermore, it does not make sense for testWidget to override the presentError because it is not changing the way the error is **presenting** to user. It is changing the way how framework **handling** the error.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jacob314** [comment]
lgtm
