### PR TITLE
Fix `ResizeImage` documentation

### LINKED ISSUE #136508: ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels
```
      return LayoutBuilder(builder: (context, constraints) {
        return Image(
            image: ResizeImage(
          FileImage(File(pathRefImage)),
          width:
              (constraints.maxWidth * MediaQuery.of(context).devicePixelRatio)
                  .toInt(),
        ));
```

### Proposal

ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels

### PR DESCRIPTION
**Pull request by nate-thegrate**
Whoever reviewed the documentation changes in #154212 neglected to double-check that the information was accurate (it was me who did this).

Fixes #136508

### CODE REVIEW

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 1]
```diff
@@ -1194,19 +1194,16 @@ enum ResizeImagePolicy {
 /// Instructs Flutter to decode the image at the specified dimensions
 /// instead of at its native size.
 ///
-/// The [width] and [height] parameters refer to logical pixels.
-///
-/// Logical pixels have roughly the same visual size across devices, whereas
-/// physical pixels correspond to actual device hardware.
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/painting/image_provider.dart:1200]: This sentence (which was [written by me](https://github.com/flutter/flutter/pull/154212#discussion_r1735434443)) is unnecessarily confusing, since an unconstrained `ResizeImage`'s scaling to match logical pixels means that by default, it doesn't match the resolution of the actual device hardware.

**Review by victorsanni — APPROVED** [review]

**Comment by nate-thegrate** [comment]
Much appreciated 🫡
