### PR TITLE
Fix Linux numpad shortcuts on web

### LINKED ISSUE #148447: [Linux][Web]: Bug while pressing Numeric Keypad keys on web with Flutter last stable version
### Steps to reproduce

Use the numeric keypad with any EditableText widget

### Expected results

Numbers should be correctly entered in the field, instead an error is thrown.
This only happens with digits from the numeric keypad.

### Actual results

```
The following assertion was thrown during a platform message callback:
Assertion failed:
file:///home/something/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart:505:16
!_pressedKeys.containsKey(event.physicalKey)
"A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this
occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
was the event: KeyDownEvent#ea691(physicalKey: PhysicalKeyboardKey#70059(usbHidUsage:
\"0x00070059\", debugName: \"Numpad 1\"), logicalKey: LogicalKeyboardKey#00cb9(keyId:
\"0x200000231\", keyLabel: \"Numpad 1\", debugName: \"Numpad 1\"), character: \"1\", timeStamp:
0:02:48.590899)"

```
### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on Ubuntu 23.10 6.5.0-35-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /home/florian/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (7 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/florian/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/florian/Android/Sdk
    • Java binary at: /home/florian/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /home/florian/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.89.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.207

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PRs fixes a Web issue on Linux related to numpad keys.
In https://github.com/flutter/flutter/pull/145464, I introduced numpad shortcuts for Linux. These shortcuts work well on a desktop Linux application but they broke the Linux+Web numpad logic.

When I added these shortcuts, I expected them to not be active on Web (because I knew that on Web, those shortcuts are handled by the browser). But there is a trick: text editing shortcuts are still defined on Web but they are disabled at the editable text level so one can use them in components that are not `EditableText` (see https://github.com/flutter/flutter/pull/103377).
In this PR, I used the same approach than for other text editing shortcuts: when on web associate those shortcuts to the `DoNothingAndStopPropagationTextIntent` intent.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/148447.

## Tests

Updates 2 tests.
Adds 2 tests.

### CODE REVIEW

File: packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart [hunk 1]
```diff
@@ -664,7 +664,77 @@ void main() {
...
+
+      await tester.enterText(find.byType(EditableText), 'Flutter');
+      expect(controller.selection.end, 7);
+
+      await sendKeyCombination(tester, const SingleActivator(LogicalKeyboardKey.numpad4));
+      // Verify the cursor moved to the left (numpad4).
+      expect(controller.selection.end, 6);
+    },
+      variant: TargetPlatformVariant.only(TargetPlatform.linux),
+      skip: kIsWeb); // [intended] Non-web test.
```
Comment (justinmc) [inline packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart:699]: Nit: Typically I'd see the closing parenthesis on the next line. Here and below.

**Review by justinmc — APPROVED** [review]
LGTM :+1: . Tricky catch. Thanks for the thorough tests.

File: packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart]: I did it on purpose because the analyzer was failing and complaining about `skip` requiring a comment.
I tried various format and that one was ok.
After seeing your comment, I had a closer look to the analyzer failure and, base on https://github.com/flutter/flutter/wiki/Tree-hygiene#skipped-tests, I figured out that the lint is about having an URL or [intended] in the comment, knowing this I was able to update the PR with a proper formatting.

**Comment by bhuphathi** [comment]
"Thanks, @bleroux  This is helpful."

File: packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/widgets/default_text_editing_shortcuts_test.dart]: Ah cool, thank you!

**Comment by m3c-fnicola** [comment]
Will this be cherry-picked to the stable branch? Our product currently depends on this fix as many of our users rely on numpad functionality, and we're experiencing a significant blockage due to this issue. We might need to downgrade to a previous stable version of Flutter that does not have this problem.

Thanks for your assistance!

**Comment by bleroux** [comment]
@m3c-fnicola You might be interested in https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-Cherrypick-Process.md#how-do-i-request-a-cherry-pick
