### PR TITLE
Fix: Remove attach target on deactivation of widget from overlay portal controller

### LINKED ISSUE #164376: OverlayPortal: Failed to attach OverlayPortalController to _OverlayPortalState on page resize
### Steps to reproduce

Just use two `OverlayPortals` which are new builded by parent widget, e.g. on resize like the `Switchy` widget does.
Tested it with web on Flutter 3.29.0 and 3.22.3, same result.

### Expected results

Controller is not attached anymore to old state so on rebuild it can be used again.

### Actual results

Exception on rebuild.

### Code sample

<details open><summary>Code sample</summary>

```dart
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final OverlayPortalController overlayPortalController = OverlayPortalController();

  final OverlayPortalController overlayPortalControllerSecond = OverlayPortalController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SingleChildScrollView(
        child: Switchy(
          children: [
            PortaledWidget(controller: overlayPortalController),
            PortaledWidget(controller: overlayPortalControllerSecond),
          ],
        ),
      ),
    );
  }
}

class Switchy extends StatelessWidget {
  final List<Widget> children;

  const Switchy({super.key, required this.children});

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.sizeOf(context);

    if (size.width < 800) {
      return Column(children: children);
    }
    return Row(children: children);
  }
}

class PortaledWidget extends StatelessWidget {
  final OverlayPortalController controller;

  const PortaledWidget({super.key, required this.controller});

  @override
  Widget build(BuildContext context) {
    return OverlayPortal(
      controller: controller,
      overlayChildBuilder: (context) => ElevatedButton(
        onPressed: () => controller.hide(),
        child: const Text('cancel'),
      ),
      child: ElevatedButton.icon(onPressed: () => controller.show(), label: const Icon(Icons.home)),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/def05c63-4328-4563-8478-999508371d57)

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building PortaledWidget:
Assertion failed:
file:///Users/bs000ucwu/flutter/3.29.0/packages/flutter/lib/src/widgets/overlay.dart:1881:7
overlay.dart:1881
controller._attachTarget == null || controller._attachTarget == this
"Failed to attach OverlayPortalController to _OverlayPortalState#73413(lifecycle state: created). It
is already attached to _OverlayPortalState#d6d85."

The relevant error-causing widget was:
  PortaledWidget PortaledWidget:file:///Users/bs000ucwu/flutter_test_project/lib/main.dart:25:13

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 307:3     throw_
errors.dart:307
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39               assertFailed
profile.dart:117
packages/flutter/src/widgets/overlay.dart 1881:71                               [_setupController]
overlay.dart:1881
packages/flutter/src/widgets/overlay.dart 1876:5                                initState
overlay.dart:1876
packages/flutter/src/widgets/framework.dart 5860:55                             [_firstBuild]
framework.dart:5860
packages/flutter/src/widgets/framework.dart 5709:5                              mount
framework.dart:5709
packages/flutter/src/widgets/framework.dart 4555:15                             inflateWidget
framework.dart:4555
packages/flutter/src/widgets/framework.dart 4020:18                             updateChild
framework.dart:4020
packages/flutter/src/widgets/framework.dart 5756:16                             performRebuild
framework.dart:5756
packages/flutter/src/widgets/framework.dart 5445:7                              rebuild
framework.dart:5445
packages/flutter/src/widgets/framework.dart 5715:5                              [_firstBuild]
framework.dart:5715
packages/flutter/src/widgets/framework.dart 5709:5                              mount
framework.dart:5709
packages/flutter/src/widgets/framework.dart 4555:15                             inflateWidget
framework.dart:4555
packages/flutter/src/widgets/framework.dart 7178:36                             inflateWidget
framework.dart:7178
packages/flutter/src/widgets/framework.dart 7194:32                             mount
framework.dart:7194
packages/flutter/src/widgets/framework.dart 4555:15                             inflateWidget
framework.dart:4555
packages/flutter/src/widgets/framework.dart 4014:20                             updateChild
framework.dart:4014
packages/flutter/src/widgets/framework.dart 5756:16                             performRebuild
framework.dart:5756
packages/flutter/src/widgets/framework.dart 5445:7                              rebuild
framework.dart:5445
packages/flutter/src/widgets/framework.dart 2704:14                             [_tryRebuild]
framework.dart:2704
packages/flutter/src/widgets/framework.dart 2762:11                             [_flushDirtyElements]
framework.dart:2762
packages/flutter/src/widgets/framework.dart 3066:17                             buildScope
framework.dart:3066
packages/flutter/src/widgets/binding.dart 1229:9                                drawFrame
binding.dart:1229
packages/flutter/src/rendering/binding.dart 482:5                               [_handlePersistentFrameCallback]
binding.dart:482
packages/flutter/src/scheduler/binding.dart 1442:7                              [_invokeFrameCallback]
binding.dart:1442
packages/flutter/src/scheduler/binding.dart 1355:9                              handleDrawFrame
binding.dart:1355
packages/flutter/src/scheduler/binding.dart 1208:5                              [_handleDrawFrame]
binding.dart:1208
lib/_engine/engine/platform_dispatcher.dart 1347:5                              invoke
platform_dispatcher.dart:1347
lib/_engine/engine/platform_dispatcher.dart 301:5                               invokeOnDrawFrame
platform_dispatcher.dart:301
lib/_engine/engine/initialization.dart 190:36                                   <fn>
initialization.dart:190
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27  _callDartFunctionFast1
js_allow_interop_patch.dart:224

════════════════════════════════════════════════════════════════════════════════════════════════════
9
Another exception was thrown: Assertion failed: file:///Users/bs000ucwu/flutter/3.29.0/packages/flutter/lib/src/widgets/overlay.dart:1881:7
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Remove attach target on deactivation of widget from overlay portal controller
fixes: #164376 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @rkishan516 thank you for sending a PR!
It looks like this is failing many tests, and lacks tests itself. Can you take a look?
Thanks!

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 1]
```diff
@@ -1886,13 +1886,20 @@ class _OverlayPortalState extends State<OverlayPortal> {
...
       _setupController(widget.controller);
+    } else if (widget.controller._attachTarget == null) {
+      _setupController(widget.controller);
     }
   }
 
   @override
-  void dispose() {
-    assert(widget.controller._attachTarget == this);
+  void deactivate() {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/overlay.dart:1895]: If the `OverlayPortal` is reparented, the `_attachTarget` has to be restored right? Also could you add a test for this?

Comment (rkishan516) [reply packages/flutter/lib/src/widgets/overlay.dart:1956]: Sure

Comment (rkishan516) [reply packages/flutter/lib/src/widgets/overlay.dart:1956]: I have pushed the required change.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/overlay.dart:1956]: It should probably happen in `activate` instead of `didUpdateWidget`.

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 2]
```diff
@@ -1947,13 +1947,20 @@ class _OverlayPortalState extends State<OverlayPortal> {
...
+    super.deactivate();
+    assert(widget.controller._attachTarget == null || widget.controller._attachTarget == this);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/overlay.dart:1958]: I think the assert here should be `assert(widget.controller._attachTarget == this)`?

**Review by LongCatIsLooong — COMMENTED** [review]
Detaching the controller from the state when it's deactivated makes sense to me. 

However this would create a new corner case: when the state is deactivated, we don't want the developer to call `show` or `hide` on the associated controller because the state the controller attaches to may not rebuild.  I think that can happen if you cache the OverlayPortal and gives it a global key.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/lib/src/widgets/overlay.dart:1956]: Yaa, that will be correct. Let me do the change.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 2 above)
Comment (rkishan516) [reply packages/flutter/lib/src/widgets/overlay.dart:1958]: Yes, that should be the case but when reattaching with global key, it was causing failures.
But i think since we are moving reattach in `activate` method, this can be removed.

**Comment by rkishan516** [comment]
> Detaching the controller from the state when it's deactivated makes sense to me.
> 
> However this would create a new corner case: when the state is deactivated, we don't want the developer to call `show` or `hide` on the associated controller because the state the controller attaches to may not rebuild. I think that can happen if you cache the OverlayPortal and gives it a global key.

I will write a test for this and check.

**Comment by rkishan516** [comment]
> > Detaching the controller from the state when it's deactivated makes sense to me.
> > However this would create a new corner case: when the state is deactivated, we don't want the developer to call `show` or `hide` on the associated controller because the state the controller attaches to may not rebuild. I think that can happen if you cache the OverlayPortal and gives it a global key.
> 
> I will write a test for this and check.

I have added the test, we don't need to call `show` method again after `reactivation`.

**Comment by LongCatIsLooong** [comment]
It seems there's a leak in one of the new tests. Maybe one of the OverlayEntries were not disposed at the end of the test?

**Comment by LongCatIsLooong** [comment]
I think setting `_attatchTarget` to null when the Element is deactivated could change the behavior in some corner cases, and what we want to fix is just the assert in `_setupController`. Can fix the asserts by:
 
- In the `_setupController` assert, if the attached state is not [Element.debugIsActive](https://main-api.flutter.dev/flutter/widgets/Element/debugIsActive.html), then we could allow the re-attach, 
- assert in `State.activate` that `_attachTarget == this`

**Comment by rkishan516** [comment]
> It seems there's a leak in one of the new tests. Maybe one of the OverlayEntries were not disposed at the end of the test?

Even after disposing overlay entries, its showing leak.

**Comment by LongCatIsLooong** [comment]
> in release

The issue won't happen in release builds. The crash is caused by an assert.

**Comment by LongCatIsLooong** [comment]
> > It seems there's a leak in one of the new tests. Maybe one of the OverlayEntries were not disposed at the end of the test?
> 
> Even after disposing overlay entries, its showing leak.

The relevant error messages were:
```
     Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/flutter/flutter/blob/main/docs/contributing/testing/Leak-tracking.md
            notDisposed:
              total: 4
              objects:
                ValueNotifier<_OverlayEntryWidgetState?>:
                  test: attachTarget is restored after reparenting
                  identityHashCode: 933371839
                OverlayEntry:
                  test: attachTarget is restored after reparenting
                  identityHashCode: 947575411
                ValueNotifier<_OverlayEntryWidgetState?>:
                  test: attachTarget is restored after reparenting
                  identityHashCode: 51179505
                OverlayEntry:
                  test: attachTarget is restored after reparenting
                  identityHashCode: 662836894
```

**Comment by rkishan516** [comment]
> > in release
> 
> The issue won't happen in release builds. The crash is caused by an assert.

Okay, then I will do the change in `_setupController`.

File: packages/flutter/test/widgets/overlay_portal_test.dart [hunk 3]
```diff
@@ -1365,6 +1365,200 @@ void main() {
...
+                ),
+              ],
+            );
+          },
+        ),
+      ),
+    );
+
+    // Move to second overlay
+    setState(() {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/overlay_portal_test.dart:1554]: I suspect when the `StatefulBuilder` rebuilds, the builder callback will be called a second time, creating new OverlayEntries so in the test 4 OverlayEntries were created but only 2 were disposed.

Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1554]: Yaa, I need to give GlobalKey to `Overlay` widgets such that they also maintain themself until test is completed.

Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1558]: Even after adding global key, tests are failing

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1558]: Global keys don't prevent rebuilds. Can you try creating the OverlayEntries at the start of the test, (and make them final), to make sure only two OverlayEntries are created in the test?

Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1558]: Sure, and yaa even i was doing it wrongly with global keys. But yaa let me do the change.

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 4]
```diff
@@ -1920,7 +1920,9 @@ class _OverlayPortalState extends State<OverlayPortal> {
 
   void _setupController(OverlayPortalController controller) {
     assert(
-      controller._attachTarget == null || controller._attachTarget == this,
+      controller._attachTarget == null ||
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/overlay.dart:1923]: nit: looks like the first check is also covered by the 3rd check? If so can we remove the first line?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thank you for fixing this!

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 4 above)
Comment (rkishan516) [reply packages/flutter/lib/src/widgets/overlay.dart:1923]: Sure, Let me push the change.

File: packages/flutter/test/widgets/overlay_portal_test.dart [hunk 5]
```diff
@@ -1365,6 +1365,191 @@ void main() {
...
+    );
+
+    await tester.pumpWidget(
+      Directionality(
+        textDirection: TextDirection.ltr,
+        child: Overlay(
+          initialEntries: <OverlayEntry>[
+            overlayEntry1 = _buildOverlayEntry(
+              (BuildContext context) => OverlayPortal(
+                controller: controller1,
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/overlay_portal_test.dart:1410]: @QuncCccccc pointed out the widget tree didn't seem to have changed in the second `pump`.

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1410]: Also it looks like 4 OverlyEntries are created in this test but only 2 are disposed in the tear down process, like in the other test.

File: packages/flutter/test/widgets/overlay_portal_test.dart [hunk 6]
```diff
@@ -1365,6 +1365,191 @@ void main() {
...
+                controller: controller2,
+                overlayChildBuilder: (BuildContext context) => const Placeholder(),
+              ),
+            ),
+          ],
+        ),
+      ),
+    );
+
+    await tester.pumpWidget(
```
Comment (QuncCccccc) [inline packages/flutter/test/widgets/overlay_portal_test.dart:1403]: This pumpWidget seems is identical with the one above. Is this intended? Should we update the controllers?

File: packages/flutter/test/widgets/overlay_portal_test.dart (hunk 5 above)
Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1410]: Ohh yes, I think here same change should be done, that overlay entries should be created and then passed to `Overlay`. Let me push that change.

File: packages/flutter/test/widgets/overlay_portal_test.dart (hunk 6 above)
Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart:1403]: No, the controller for both should swap with each other.

File: packages/flutter/test/widgets/overlay_portal_test.dart (hunk 5 above)
Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart]: @LongCatIsLooong I have made this test more simpler. Where at first there is only 1 entry which is being replaced after `pump` by another one.

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/overlay_portal_test.dart]: Thank you! Also I think the `attachTarget == this` check it `dispose` is probably no longer necessary?

**Review by QuncCccccc — APPROVED** [review]
LGTM once we address @LongCatIsLooong's [comment](https://github.com/flutter/flutter/pull/164439#discussion_r2012843129)! Thank you for the fix:)

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 7]
```diff
@@ -1950,6 +1951,12 @@ class _OverlayPortalState extends State<OverlayPortal> {
...
 
+  @override
+  void activate() {
+    assert(widget.controller._attachTarget == this);
+    super.activate();
+  }
+
   @override
   void dispose() {
     assert(widget.controller._attachTarget == this);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/widgets/overlay.dart:1962]:
```suggestion
```

File: packages/flutter/test/widgets/overlay_portal_test.dart (hunk 5 above)
Comment (rkishan516) [reply packages/flutter/test/widgets/overlay_portal_test.dart]: I have pushed the change. Actually thank you, for helping quite a lot.

**Comment by LongCatIsLooong** [comment]
Merging. Thank you for your patience!
