### PR TITLE
Fix NavigatorBar lacks visual feedback

### LINKED ISSUE #163871: NavigationBar lacks visual feedback when focused using keyboard on any platform, or when touched on mobile devices
### Steps to reproduce

1. Create an app that uses `NavigationBar`
2. Touch, hover, or focus on the different destinations

### Expected results

All destinations, including the selected destination, should give visual feedback when touched, focused, or hovered.

### Actual results

Unselected destinations have appropriate visual feedback, but the selected destination doesn't.

### Code sample

<details open><summary>Code sample</summary>

Note: this is directly copied from https://api.flutter.dev/flutter/material/NavigationBar-class.html

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [NavigationBar].

void main() => runApp(const NavigationBarApp());

class NavigationBarApp extends StatelessWidget {
  const NavigationBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: NavigationExample());
  }
}

class NavigationExample extends StatefulWidget {
  const NavigationExample({super.key});

  @override
  State<NavigationExample> createState() => _NavigationExampleState();
}

class _NavigationExampleState extends State<NavigationExample> {
  int currentPageIndex = 0;
  NavigationDestinationLabelBehavior labelBehavior = NavigationDestinationLabelBehavior.alwaysShow;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        labelBehavior: labelBehavior,
        selectedIndex: currentPageIndex,
        onDestinationSelected: (int index) {
          setState(() {
            currentPageIndex = index;
          });
        },
        destinations: const <Widget>[
          NavigationDestination(icon: Icon(Icons.explore), label: 'Explore'),
          NavigationDestination(icon: Icon(Icons.commute), label: 'Commute'),
          NavigationDestination(
            selectedIcon: Icon(Icons.bookmark),
            icon: Icon(Icons.bookmark_border),
            label: 'Saved',
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Label behavior: ${labelBehavior.name}'),
            const SizedBox(height: 10),
            OverflowBar(
              spacing: 10.0,
              overflowAlignment: OverflowBarAlignment.center,
              overflowSpacing: 10.0,
              children: <Widget>[
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.alwaysShow;
                    });
                  },
                  child: const Text('alwaysShow'),
                ),
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.onlyShowSelected;
                    });
                  },
                  child: const Text('onlyShowSelected'),
                ),
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.alwaysHide;
                    });
                  },
                  child: const Text('alwaysHide'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Compare hovering the unselected tab: 

Image

versus the selected tab:

Image

Note that the tooltip isn't sufficient because that won't show up for focus or touch feedback use cases.

</details>

### Logs

<details open><summary>Logs</summary>

N/A

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

N/A, Google-internal client

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes NavigationBar lacking visual feedback on the active destination indicator.

This is a reland of https://github.com/flutter/flutter/pull/164484 which was reverted in https://github.com/flutter/flutter/pull/169497.
After investigation, I narrowed down the regression introduced in https://github.com/flutter/flutter/pull/164484 to the usage of a RepaintBoundary.
I added one test to verify that the regression which led to the revert of https://github.com/flutter/flutter/pull/164484 is no more reproducible.

### Before:

The navigation indicator does not change color when hovered or focused:

https://github.com/user-attachments/assets/a1e67dee-4a38-4711-ba90-bdcd9bed3226

### After:

The navigation indicator color changes (slightly darker):

https://github.com/user-attachments/assets/1b1cc335-2cf4-4c41-9c53-696537707c72

## Related Issue

Fixes [NavigationBar lacks visual feedback when focused or hovered](https://github.com/flutter/flutter/issues/163871) 

## Tests

- Updates several helper functions which are used by several tests.
- Updates several test: adding an Ink widget changes the coordinates used in several tests because these coordinates are now relative to the Ink offset.
- Add one test to check that active destination moves to the correct destination (that was not the case after https://github.com/flutter/flutter/pull/164484). This new test is a golden test.

### CODE REVIEW

File: packages/flutter/lib/src/material/navigation_bar.dart [hunk 1]
```diff
@@ -927,15 +926,12 @@ class _NavigationBarDestinationLayout extends StatelessWidget {
           children: <Widget>[
             LayoutId(
               id: _NavigationDestinationLayoutDelegate.iconId,
-              child: RepaintBoundary(key: iconKey, child: icon),
+              // The key is used by the _IndicatorInkWell to query the icon position.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/navigation_bar.dart:929]: Thanks for explaining.

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by bleroux** [comment]
@justinmc If you get a chance, thank you to have a look at the Google testing failures.
Probably the same than the previous PR, see https://github.com/flutter/flutter/pull/164484#pullrequestreview-2680027770 where you mentioned the failures were expected.

**Comment by bleroux** [comment]
@victorsanni In case you have the bandwidth to look at the Google failures. This PR is a reland of https://github.com/flutter/flutter/pull/164484. There were some Google failures for the first PRs but they were expected as the tests were capturing the wrong behavior (no overlay/splash), so the failure here are probably the same.

**Review by justinmc — APPROVED** [review]
Sorry for the delay here. The Google test failures were a few imperceptible pixel changes in a bottom nav bar that seems reasonable to changing the widget tree a little bit like this.
