### PR TITLE
Use directory exists instead of path.dirname

### LINKED ISSUE #110027: `flutter pub get` should warn if the target directory does not exist
## Use case

The names `flutter pub add` and `flutter pub get` are confusing. Incorrectly using the `flutter pub get` command to install a package produces output that appears to be successful.

For example, imagine a user attempts to install `go_router` incorrectly using the `get` subcommand:

```
PS C:\Code\my_project> flutter pub get go_router
Running "flutter pub get" in ....                                  509ms
```

This output misleads the user into thinking `go_router` was installed.

## Proposal

The `get` subcommand should warn if the target directory does not exist. For example:

```
PS C:\Code\my_project> flutter pub get go_router
Warning: Could not find target directory 'go_router'. If you meant to install a package, use 'flutter pub add'.
Running "flutter pub get" in ....                                  509ms
```

/cc @sigurdm @jonasfj @szakarias

### PR DESCRIPTION
**Pull request by Jasguerrero**
Fixes: #110027
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_aar.dart [hunk 1]
```diff
@@ -155,6 +155,8 @@ class BuildAarCommand extends BuildSubCommand {
     if (remainingArguments.isEmpty) {
       return FlutterProject.current();
     }
-    return FlutterProject.fromDirectory(globals.fs.directory(findProjectRoot(globals.fs, remainingArguments.first)));
+    String? projectRoot = findProjectRoot(globals.fs, remainingArguments.first);
+    projectRoot ??= '.';
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/build_aar.dart:159]: Why was this needed? I would think this would be equivalent to passing null and then having `findProjectRoot` fall back to `fileSystem.currentDirectory.path`.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:159]: oh wait, never mind, this handling a null return from `findProjectRoot`. Although, if `findProjectRoot` returns null, doesn't that mean the current working directory is NOT a valid project?

File: packages/flutter_tools/lib/src/base/os.dart [hunk 2]
```diff
@@ -594,11 +594,11 @@ String? findProjectRoot(FileSystem fileSystem, [ String? directory ]) {
...
       return directory;
     }
-    final String parent = fileSystem.path.dirname(directory);
-    if (directory == parent) {
+    final Directory currentDirectory = fileSystem.directory(directory);
+    if (!currentDirectory.existsSync() || currentDirectory.parent.path == currentDirectory.path) {
       return null;
     }
-    directory = parent;
+    directory = currentDirectory.parent.path;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/os.dart:601]: why don't we just loop over a Directory, rather than casting back and forth from a String <-> Directory? Also, when we instantiate Directory, we should use:

```dart
Directory current = fileSystem.currentDirectory.absolute;
```

Right now this doesn't handle `flutter pub get .` if the current working directory is a sub-directory of the root.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/os.dart:601]: This version for me handles `.` in a sub-directory:

```
String? findProjectRoot(FileSystem fileSystem, [ String? directory ]) {
  const String kProjectRootSentinel = 'pubspec.yaml';
  directory ??= fileSystem.currentDirectory.path;
  Directory current = fileSystem.directory(directory).absolute;
  while (true) {
    if (current.childFile(kProjectRootSentinel).existsSync()) {
      return current.path;
    }

    if (!current.existsSync() || current.parent.path == current.path) {
      return null;
    }
    current = current.parent;
  }
}
```

File: packages/flutter_tools/lib/src/commands/build_aar.dart (hunk 1 above)
Comment (Jasguerrero) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:159]: This was to make https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L213 pass but after more debugging found out that `build aar` is passing `/path/lib/main.dart' to `findProjectRoot` that with my change when doing the `directory.existsSync` fails and returned a null, the correct behavior is to get the directory in which `main.dart` lives or throw a tool exit if `/path/lib/main.dart` does not exists which currently just falls back to the current directory because of `fileSystem.path.dirname(directory)`

File: packages/flutter_tools/lib/src/commands/build_aar.dart [hunk 3]
```diff
@@ -155,6 +155,21 @@ class BuildAarCommand extends BuildSubCommand {
     if (remainingArguments.isEmpty) {
       return FlutterProject.current();
     }
-    return FlutterProject.fromDirectory(globals.fs.directory(findProjectRoot(globals.fs, remainingArguments.first)));
+    final File mainFile = globals.fs.file(remainingArguments.first);
+    final String path;
+    if (!mainFile.existsSync()) {
+      final Directory pathProject = globals.fs.directory(remainingArguments.first);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/build_aar.dart:161]: Should we handle if the user passes the path to a file?

Comment (Jasguerrero) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:161]: This is handling both cases, file and directory

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:161]: won't `fs.directory(remainingArguments.first)` crash if passed the path to a file?

Comment (Jasguerrero) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:161]: It doesn't but this is only called after checking if mainFile doesn't exist. It first checks if the provided path is a File and then a directory if they both are not found on your file system it throws a tool exit

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/build_aar.dart:161]: Ahh I see, I forgot that constructing an invalid File or Directory is completely allowed. LGTM

File: packages/flutter_tools/test/commands.shard/hermetic/pub_get_test.dart [hunk 4]
```diff
@@ -114,6 +114,22 @@ void main() {
...
 
+  testUsingContext('pub get throws error on missing directory', () async {
+    final PackagesGetCommand command = PackagesGetCommand('get', false);
+    final CommandRunner<void> commandRunner = createTestCommandRunner(command);
+
+    try {
+      await commandRunner.run(<String>['get', 'missing_dir']);
+      fail('expected an exception');
+    } on Exception catch (e) {
+      expect(e.toString().contains('Expected to find project root in missing_dir'), true);
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/pub_get_test.dart:125]: nit, use contains matcher to get a better failure message if/when it fails:

```suggestion
      expect(e.toString(), contains('Expected to find project root in missing_dir'));
```

File: packages/flutter_tools/lib/src/commands/build_aar.dart [hunk 5]
```diff
@@ -155,6 +155,21 @@ class BuildAarCommand extends BuildSubCommand {
...
+      if (!pathProject.existsSync()) {
+        throwToolExit('${remainingArguments.first} does not exists');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/build_aar.dart:163]:
```suggestion
        throwToolExit('${remainingArguments.first} does not exist');
```

File: packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart [hunk 6]
```diff
@@ -230,6 +230,30 @@ void main() {
...
 
+    group('throws throwsToolExit', () {
+      testUsingContext('main.dart not found', () async {
+        await expectLater(() async {
+          await runBuildAarCommand(
+            'missing_project',
+            arguments: <String>['--no-pub'],
+          );
+        }, throwsToolExit(
+          message: 'main.dart does not exists',
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart:241]: nit update when correcting grammar on the throwToolExist string

**Review by christopherfujino — APPROVED** [review]
Some minor nits, but otherwise LGTM
