### PR TITLE
MaterialBanner alignment fixes and improvements

### LINKED ISSUE #73563: MaterialBanner Button Alignment Incorrect on Overflow
If a `MaterialBanner` has a number of buttons with large text, or too many buttons to show in a single row, it renders them vertically. However, the button alignment is to the left and not to the right, as per the [Material Design spec](https://material.io/components/banners#anatomy).

Expected:

image

Actual:

image

[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-GB)
    • Flutter version 1.25.0-8.1.pre at C:\Users\softwyer\Programs\flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\softwyer\Programs\android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\softwyer\AppData\Local\\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\softwyer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • SM A405FN (mobile) • 10.8.200.136:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

### PR DESCRIPTION
**Pull request by xu-baolin**
This change adds a new property `overflowAlignment` to `MaterialBanner` to control the alignment of the [actions] when the [actions] laid out in a column.

I also change the default behavior to [OverflowBarAlignment.end] to respect the material spec.
See also https://material.io/components/banners#anatomy

Fixes #73563

### CODE REVIEW

File: packages/flutter/lib/src/material/banner.dart [hunk 1]
```diff
@@ -50,6 +50,10 @@ import 'theme.dart';
 /// Otherwise, the [actions] will be placed below the [content]. Use
 /// [forceActionsBelow] to override this behavior.
 ///
+/// If the [actions] placed below the [content], they will be laid out in a row
+/// unless there isn't sufficient room to display, in which case they are laid out
+/// in a column instead.
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/banner.dart:55]:
```suggestion
/// If the [actions] is placed below the [content], they will be laid out in a row.
/// If there isn't sufficient room to display everything, they are laid out
/// in a column instead.
```

**Review by shihaohong — APPROVED** [review]
LGTM, although I worry that updating the default overflow alignment behavior for `MaterialBanner` might be a breaking change.

**Comment by xu-baolin** [comment]
> LGTM, although I worry that updating the default overflow alignment behavior for `MaterialBanner` might be a breaking change.

This is true. If it breaks something, revert it and figure out a solution. :)

**Comment by xu-baolin** [comment]
The tree seems to be abnormal. Many test cases are in the queue for a timeout, waiting for the tree to normal.
