### PR TITLE
RTL caret position

### LINKED ISSUE #58669: TextField cursor position changes when rotate screen
## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.17.0 at /Users/hsul4n/Developer/flutter
    • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hsul4n/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0
 
[✓] Connected device (1 available)            
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

## Example
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                TextFormField(
                  autofocus: true,
                  decoration: InputDecoration(
                    labelText: 'Phone Number',
                  ),
                  inputFormatters: <TextInputFormatter>[
                    WhitelistingTextInputFormatter.digitsOnly,
                  ],
                  keyboardType: TextInputType.number,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

Here a screenshot
Screenshot_٢٠٢٠٠٦٠٤-١١٤٣٤١
and when rotate
Screenshot_٢٠٢٠٠٦٠٤-١١٤٣٥٩

### LINKED ISSUE #58712: Misplaced cursor when resizing `TextField`
## Steps to Reproduce

1. Run a flutter app with a resizable `TextField`.
2. Write something in the `TextField`, then resize it.

**Expected results:** 
The cursor gets placed exactly at the point of the text it was before.

**Actual results:** 
The cursor stays in the same position of the screen it was before.

ezgif com-resize (1)

You can easily reproduce the described behavior with this snippet:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Home(),
      ),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final controller = TextEditingController(text: 'foo bar ' * 20);
  var withTrailingWidget = false;

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Row(children: [
        Expanded(child: TextField(controller: controller, maxLines: 4)),
        if (withTrailingWidget) Icon(Icons.android)
      ]),
      RaisedButton(
        child: Text('Toggle trailing widget'),
        onPressed: () {
          setState(() => withTrailingWidget = !withTrailingWidget);
        },
      ),
    ]);
  }
}
```

<details>
  <summary>Logs</summary>

```
[  +15 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5f21edf8b66e31a39133177319414395cc5b5f48
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +178 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.2
[   +5 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +31 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:5
[   +5 ms] C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +35 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +182 ms] Generating C:\Users\hugoc\IdeaProjects\Flutter\buster\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +15 ms] ro.hardware = ranchu
[   +8 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +13 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +6 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true
--output-dill C:\Users\hugoc\AppData\Local\Temp\flutter_tool.f2c77b25-a69a-11ea-90a2-4cedfb76621a\app.dill --packages C:\Users\hugoc\IdeaProjects\Flutter\buster\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[   +9 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +12 ms] Exit code 0 from: C:\Users\hugoc\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="dev.hugopassos.buster" (Raw: "dev.hugopassos.buster")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw: "android.permission.RECEIVE_BOOT_COMPLETED")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw: "android.permission.RECORD_AUDIO")
               E: application (line=19)
                 A: android:label(0x01010001)="buster" (Raw: "buster")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=25)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="dev.hugopassos.buster.MainActivity" (Raw: "dev.hugopassos.buster.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=39)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=43)
                     E: action (line=44)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=46)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +5 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +51 ms] Exit code 0 from: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           06-04 19:38:21.331 E/GnssHAL_GnssInterface( 1789): gnssSvStatusCb: b: input svInfo.flags is 8
[  +10 ms] <- compile package:buster/main.dart
[   +6 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +22 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +27 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from C:\Users\hugoc\IdeaProjects\Flutter\buster\android\gradlew.bat.
[   +1 ms] C:\Users\hugoc\IdeaProjects\Flutter\buster\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +6 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +83 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [C:\Users\hugoc\IdeaProjects\Flutter\buster\android/] C:\Users\hugoc\IdeaProjects\Flutter\buster\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\hugoc\IdeaProjects\Flutter\buster\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1512 ms] > Configure project :app
[   +1 ms] Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inconsistent location 'C:\Users\hugoc\AppData\Local\Android\sdk\.temp\PackageOperation02' (Expected 'C:\Users\hugoc\AppData\Local\Android\sdk\extras\intel\Hardware_Accelerated_Execution_Manager')
[        ] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[        ] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[        ] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[  +90 ms] > Transform kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.21) with JetifyTransform
[   +1 ms] > Transform kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21) with JetifyTransform
[        ] > Transform annotations.jar (org.jetbrains:annotations:13.0) with JetifyTransform
[        ] > Transform kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.21) with IdentityTransform
[        ] > Transform annotations.jar (org.jetbrains:annotations:13.0) with IdentityTransform
[        ] > Transform kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21) with IdentityTransform
[        ] > Transform collection.jar (androidx.collection:collection:1.1.0) with JetifyTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with JetifyTransform
[        ] > Transform collection.jar (androidx.collection:collection:1.1.0) with IdentityTransform
[        ] > Transform annotation.jar (androidx.annotation:annotation:1.1.0) with JetifyTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with JetifyTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with ExtractAarTransform
[        ] > Transform annotation.jar (androidx.annotation:annotation:1.1.0) with IdentityTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with JetifyTransform
[        ] > Transform lifecycle-common.jar (androidx.lifecycle:lifecycle-common:2.2.0) with JetifyTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with ExtractAarTransform
[        ] > Transform lifecycle-common.jar (androidx.lifecycle:lifecycle-common:2.2.0) with IdentityTransform
[   +1 ms] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with JetifyTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with ExtractAarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with JetifyTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with ExtractAarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with JetifyTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with ExtractAarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with JetifyTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with ExtractAarTransform
[   +1 ms] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with ExtractAarTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarCompileClassesTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarCompileClassesTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with JetifyTransform
[   +1 ms] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarCompileClassesTransform
[   +1 ms] > Transform core-common.jar (androidx.arch.core:core-common:2.1.0) with JetifyTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with ExtractAarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with JetifyTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with JetifyTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarCompileClassesTransform
[        ] > Transform kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21) with JetifyTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with ExtractAarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarCompileClassesTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with ExtractAarTransform
[        ] > Transform core-common.jar (androidx.arch.core:core-common:2.1.0) with IdentityTransform
[   +1 ms] > Transform kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21) with IdentityTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with JetifyTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with JetifyTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with ExtractAarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with ExtractAarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarCompileClassesTransform
[   +1 ms] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarCompileClassesTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform x86_debug.jar (io.flutter:x86_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with JetifyTransform
[   +1 ms] > Transform x86_debug.jar (io.flutter:x86_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[   +2 ms] > Transform x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with JetifyTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[   +1 ms] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with JetifyTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarCompileClassesTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarCompileClassesTransform
[   +1 ms] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[   +2 ms] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarCompileClassesTransform
[   +2 ms] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with ExtractAarTransform
[        ] > Transform flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with JetifyTransform
[   +3 ms] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarCompileClassesTransform
[  +39 ms] > Transform lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.2.0) with JetifyTransform
[   +1 ms] > Transform core.aar (androidx.core:core:1.1.0) with AarCompileClassesTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[+1996 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +14 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 5f21edf8b66e31a39133177319414395cc5b5f48
[        ] [        ] executing: [C:\flutter/] git tag --contains HEAD
[        ] [ +180 ms] Exit code 0 from: git tag --contains HEAD
[        ] [        ] 1.17.2
[        ] [   +5 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[        ] [  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +70 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +10 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +46 ms] Initializing file store
[        ] [  +23 ms] Done initializing file store
[  +73 ms] [+1005 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +8 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages C:\Users\hugoc\IdeaProjects\Flutter\buster\.packages
--output-dill C:\Users\hugoc\IdeaProjects\Flutter\buster\.dart_tool\flutter_build\2f23e1041a1e745f6b3ac721bdac59d8\app.dill --depfile C:\Users\hugoc\IdeaProjects\Flutter\buster\.dart_tool\flutter_build\2f23e1041a1e745f6b3ac721bdac59d8\kernel_snapshot.d package:buster/main.dart
[+4099 ms] [+4173 ms] kernel_snapshot: Complete
[ +501 ms] [ +430 ms] debug_android_application: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.outputMissing}
[  +98 ms] [ +134 ms] debug_android_application: Complete
[  +99 ms] [ +105 ms] Persisting file store
[        ] [   +5 ms] Done persisting file store
[        ] [   +2 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 6.003ms.
[ +199 ms] > Transform lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.2.0) with IdentityTransform
[        ] > Transform flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarCompileClassesTransform
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[   +1 ms] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with LibrarySymbolTableTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with LibrarySymbolTableTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with LibrarySymbolTableTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with LibrarySymbolTableTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with LibrarySymbolTableTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with LibrarySymbolTableTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with LibrarySymbolTableTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with LibrarySymbolTableTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with LibrarySymbolTableTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with LibrarySymbolTableTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with LibrarySymbolTableTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with LibrarySymbolTableTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with LibrarySymbolTableTransform
[        ] > Transform aapt2-windows.jar (com.android.tools.build:aapt2:3.3.2-5309881) with Aapt2Extractor
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +165 ms] > Task :app:copyFlutterAssetsDebug
[  +98 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:writeDebugApplicationId UP-TO-DATE
[        ] > Task :app:processDebugGoogleServices
[        ] Parsing json file: C:\Users\hugoc\IdeaProjects\Flutter\buster\android\app\google-services.json
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[        ] > Task :app:generateDebugSources
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugNdk NO-SOURCE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[  +86 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[        ] > Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[        ] > Transform annotations.jar (org.jetbrains:annotations:13.0) with IdentityTransform
[        ] > Transform kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21) with IdentityTransform
[        ] > Transform annotation.jar (androidx.annotation:annotation:1.1.0) with IdentityTransform
[        ] > Transform kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.21) with IdentityTransform
[        ] > Transform collection.jar (androidx.collection:collection:1.1.0) with IdentityTransform
[        ] > Transform core-common.jar (androidx.arch.core:core-common:2.1.0) with IdentityTransform
[        ] > Transform lifecycle-common.jar (androidx.lifecycle:lifecycle-common:2.2.0) with IdentityTransform
[        ] > Transform lifecycle-viewmodel.aar (androidx.lifecycle:lifecycle-viewmodel:2.1.0) with AarTransform
[        ] > Transform core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
[   +1 ms] > Transform versionedparcelable.aar (androidx.versionedparcelable:versionedparcelable:1.1.0) with AarTransform
[        ] > Transform lifecycle-livedata-core.aar (androidx.lifecycle:lifecycle-livedata-core:2.0.0) with AarTransform
[        ] > Transform lifecycle-livedata.aar (androidx.lifecycle:lifecycle-livedata:2.0.0) with AarTransform
[        ] > Transform savedstate.aar (androidx.savedstate:savedstate:1.0.0) with AarTransform
[        ] > Transform lifecycle-runtime.aar (androidx.lifecycle:lifecycle-runtime:2.2.0) with AarTransform
[        ] > Transform core.aar (androidx.core:core:1.1.0) with AarTransform
[        ] > Transform customview.aar (androidx.customview:customview:1.0.0) with AarTransform
[        ] > Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
[        ] > Transform viewpager.aar (androidx.viewpager:viewpager:1.0.0) with AarTransform
[        ] > Transform lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.2.0) with IdentityTransform
[        ] > Transform kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21) with IdentityTransform
[        ] > Transform activity.aar (androidx.activity:activity:1.0.0) with AarTransform
[        ] > Transform fragment.aar (androidx.fragment:fragment:1.1.0) with AarTransform
[        ] > Transform x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[        ] > Transform x86_debug.jar (io.flutter:x86_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[        ] > Transform flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-b851c718295a896918dc93cb1ff14f2f895a1b90) with IdentityTransform
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[+2572 ms] > Task :app:packageDebug
[ +126 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 11s
[        ] 33 actionable tasks: 7 executed, 26 up-to-date
[ +363 ms] Running Gradle task 'assembleDebug'... (completed in 12,4s)
[  +21 ms] calculateSha: LocalDirectory: 'C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk'/app.apk
[  +46 ms] calculateSha: reading file took 45us
[ +434 ms] calculateSha: computing sha took 433us
[   +3 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +2 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +11 ms] Exit code 0 from: C:\Users\hugoc\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="dev.hugopassos.buster" (Raw: "dev.hugopassos.buster")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw: "android.permission.RECEIVE_BOOT_COMPLETED")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw: "android.permission.RECORD_AUDIO")
               E: application (line=19)
                 A: android:label(0x01010001)="buster" (Raw: "buster")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=25)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="dev.hugopassos.buster.MainActivity" (Raw: "dev.hugopassos.buster.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=39)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=43)
                     E: action (line=44)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=46)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +1 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop dev.hugopassos.buster
[  +44 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages dev.hugopassos.buster
[  +41 ms] Installing APK.
[   +1 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +18 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe
[        ] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +19 ms] Installing build\app\outputs\apk\app.apk...
[        ] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r C:\Users\hugoc\IdeaProjects\Flutter\buster\build\app\outputs\apk\app.apk
[ +926 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\apk\app.apk... (completed in 0,9s)
[   +2 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell echo -n 1c8eac98620ad7191ce0ccd2aece66d168a12d55 > /data/local/tmp/sky.dev.hugopassos.buster.sha1
[  +37 ms] Android SDK built for x86 startApp
[   +3 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
dev.hugopassos.buster/dev.hugopassos.buster.MainActivity
[ +466 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=dev.hugopassos.buster/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1033 ms] Observatory URL on device: http://127.0.0.1:43545/Uh-wg0Rexic=/
[   +1 ms] executing: C:\Users\hugoc\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:43545
[  +20 ms] 53937
[        ] Forwarded host port 53937 to device port 43545 for Observatory
[   +7 ms] Connecting to service protocol: http://127.0.0.1:53937/Uh-wg0Rexic=/
[ +263 ms] Successfully connected to service protocol: http://127.0.0.1:53937/Uh-wg0Rexic=/
[   +2 ms] Sending to VM service: getVM({})
[   +8 ms] Result: {type: VM, name: vm, architectureBits: 32, hostCPU: Virtual CPU, operatingSystem: android, targetCPU: ia32, version: 2.8.3 (stable) (Tue May 26 18:39:38 2020 +0200) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 8276, startT...
[   +3 ms] Sending to VM service: getIsolate({isolateId: isolates/2330465143089991})
[   +2 ms] Sending to VM service: _flutter.listViews({})
[  +12 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xcadd1390, isolate: {type: @Isolate, fixedId: true, id: isolates/2330465143089991, name: main.dart$main-2330465143089991, number: 2330465143089991}}]}
[   +4 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: buster})
[  +25 ms] W/gopassos.buste( 8276): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
[        ] W/gopassos.buste( 8276): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
[        ] W/gopassos.buste( 8276): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
[        ] W/gopassos.buste( 8276): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
[  +10 ms] D/HostConnection( 8276): HostConnection::get() New Host Connection established 0xe1e50190, tid 8302
[   +1 ms] D/HostConnection( 8276): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings
ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +3 ms] W/OpenGLRenderer( 8276): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[   +2 ms] D/HostConnection( 8276): HostConnection::get() New Host Connection established 0xe1e503c0, tid 8307
[   +6 ms] D/HostConnection( 8276): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings
ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +1 ms] D/eglCodecCommon( 8276): setVertexArrayObject: set vao to 0 (0) 0 0
[        ] D/EGL_emulation( 8276): eglCreateContext: 0xe1e1a2a0: maj 2 min 0 rcv 2
[  +27 ms] D/eglCodecCommon( 8276): setVertexArrayObject: set vao to 0 (0) 0 0
[        ] D/EGL_emulation( 8276): eglCreateContext: 0xe1e1a3c0: maj 2 min 0 rcv 2
[  +20 ms] D/EGL_emulation( 8276): eglMakeCurrent: 0xe1e1a2a0: ver 2 0 (tinfo 0xe1e0f860)
[  +24 ms] W/Gralloc3( 8276): mapper 3.x is not supported
[   +2 ms] Result: {type: FileSystem, name: buster, uri: file:///data/user/0/dev.hugopassos.buster/code_cache/busterJDDDIS/buster/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/dev.hugopassos.buster/code_cache/busterJDDDIS/buster/)
[   +1 ms] Updating assets
[ +102 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:buster/main.dart 27ba4699-1eeb-4391-8fd0-e140b37b857d
[        ] <- 27ba4699-1eeb-4391-8fd0-e140b37b857d
[        ] D/HostConnection( 8276): createUnique: call
[        ] D/HostConnection( 8276): createUnique: call
[        ] D/HostConnection( 8276): HostConnection::get() New Host Connection established 0xe1e50410, tid 8307
[   +1 ms] D/HostConnection( 8276): HostConnection::get() New Host Connection established 0xde913df0, tid 8302
[        ] D/HostConnection( 8276): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings
ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +1 ms] D/HostConnection( 8276): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings
ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +1 ms] D/eglCodecCommon( 8276): allocate: Ask for block of size 0x1000
[        ] D/eglCodecCommon( 8276): allocate: ioctl allocate returned offset 0x3ff706000 size 0x2000
[        ] D/eglCodecCommon( 8276): allocate: Ask for block of size 0x1000
[        ] D/eglCodecCommon( 8276): allocate: ioctl allocate returned offset 0x3ffff6000 size 0x2000
[   +2 ms] D/EGL_emulation( 8276): eglMakeCurrent: 0xe1e1a3c0: ver 2 0 (tinfo 0xe1e0f7d0)
[  +13 ms] Result: {type: Isolate, id: isolates/2330465143089991, name: main, number: 2330465143089991, _originNumber: 2330465143089991, startTime: 1591299517908, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 3, avgCollectionPeriodMillis...
[  +19 ms] Updating files
[ +970 ms] D/EGL_emulation( 8276): eglMakeCurrent: 0xe1e1a2a0: ver 2 0 (tinfo 0xe1e0f860)
[  +41 ms] D/eglCodecCommon( 8276): setVertexArrayObject: set vao to 0 (0) 1 0
[   +7 ms] I/OpenGLRenderer( 8276): Davey! duration=1292ms; Flags=1, IntendedVsync=7200767936463, Vsync=7200767936463, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=7200768401700, AnimationStart=7200768482000, PerformTraversalsStart=7200768528300, DrawStart=7202014320400,
SyncQueued=7202014961100, SyncStart=7202016613300, IssueDrawCommandsStart=7202018125400, SwapBuffers=7202033090000, FrameCompleted=7202062222100, DequeueBufferDuration=9862000, QueueBufferDuration=312000,
[        ] I/Choreographer( 8276): Skipped 76 frames!  The application may be doing too much work on its main thread.
[  +37 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 1.109ms)
[        ] Synced 13.2MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xcadd1390, isolate: {type: @Isolate, fixedId: true, id: isolates/2330465143089991, name: main.dart$main-2330465143089991, number: 2330465143089991}}]}
[        ] <- accept
[        ] Connected to _flutterView/0xcadd1390.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:53937/Uh-wg0Rexic=/
[ +951 ms] D/EGL_emulation( 8276): eglMakeCurrent: 0xe1e1a3c0: ver 2 0 (tinfo 0xe1e0f7d0)
[   +5 ms] D/eglCodecCommon( 8276): setVertexArrayObject: set vao to 0 (0) 1 0
```

```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [versÃ£o 10.0.18362.836], locale pt-BR)
    • Flutter version 1.17.2 at C:\flutter
    • Framework revision 5f21edf8b6 (7 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hugoc\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (3 available)
    • SM G970F                  • RX8MB0KPY7W   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86   • Android 8.1.0 (API 27) (emulator)
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
## Description

This fixes a bug where the caret would be incorrectly positioned after a change in the width of the input.

## Related Issues

Closes https://github.com/flutter/flutter/issues/58712
Closes https://github.com/flutter/flutter/issues/58669

## Tests

I added the following tests:

  * Test that the cursor remains in the same position before and after a change in width.

## Breaking Change

None

### CODE REVIEW

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -784,18 +784,20 @@ class TextPainter {
...
 
-  // Holds the TextPosition and caretPrototype the last caret metrics were
-  // computed with. When new values are passed in, we recompute the caret metrics.
-  // only as necessary.
+  // Holds the TextPosition and caretPrototype and width of the TextPainter that
+  // the last caret metrics were computed with. When new values are passed in,
+  // we recompute the caret metrics only as necessary.
   TextPosition _previousCaretPosition;
   Rect _previousCaretPrototype;
+  double _previousWidth;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:792]: I wonder if the caret metrics cache should just be invalidated whenever the text painter has to relayout and its width cache misses?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:792]: not too familiar with the text painter code, just asking because `TextPainter.markNeedsLayout` seems to invalidate the caret metrics cache.

Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart]: Something like this 554a544?

I like the idea, it seems to make a lot more sense and reduce the need for more state.  Let me get a double check from @HansMuller that it seems like a valid idea.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -7963,4 +7962,63 @@ void main() {
...
+    await tester.enterText(find.byType(TextField), '12345');
+    await tester.pump();
+    editable = findRenderEditable(tester);
+    cursorRight = editable.getLocalRectForCaret(
+      TextPosition(offset: controller.value.text.length),
+    ).topRight.dx;
+    inputWidth = editable.size.width;
+    expect(cursorRight, inputWidth - kCaretGap);
+
+    // Since increasing the width of the input moves it right edge further to
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/text_field_test.dart:8009]: nit: "moves its right edge"

**Review by LongCatIsLooong — APPROVED** [review]
:+1:

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/painting/text_painter.dart]: Sounds reasonable to me.
