### PR TITLE
Modified DataRow to be disabled when onSelectChanged is not set

### LINKED ISSUE #74022: [proposal] provide a way to prevent DataRow to receive focus
i have a DataTable and added textfield in each cell. i have two columns and three rows . when i press tabkey its not working properly or when i use up and down arrow key it not work properly

### LINKED ISSUE #79800: DataTable DataRow without onSelectChange still receives hover visuals on web
## Steps to Reproduce

1. Run `flutter create bug_datatable`.
2. Update the files as follows: 

<details>
<summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('DataTable hover bug'),
      ),
      body: Center(
        child: DataTable(
          columns: [
            DataColumn(label: Text('Col 1')),
            DataColumn(label: Text('Col 2')),
          ],
          rows: [
            DataRow(cells: [
              DataCell(Text('Hello')),
              DataCell(Text('world')),
            ]),
            DataRow(cells: [
              DataCell(Text('Bug')),
              DataCell(Text('report')),
            ]),
            DataRow(cells: [
              DataCell(Text('GitHub')),
              DataCell(Text('issue')),
            ]),
          ],
        ),
      ),
    );
  }
}
```
</details>

3. `flutter run -d chrome`
4. hover with mouse cursor over the data rows
5. click on one of the data rows, eg. Hello world.

**Expected results:**
I expect that the mouse cursor should not indicate that the rows can be clicked and there should not be any inkWell-effect if you click on them.

Reason: Since the DataRow does not have onSelectChange set, there is no action when user clicks on a row.  

**Actual results:** 
There is an on hoover effect with changed mouse pointer and when you click a row there is an inkWell effect. 

https://user-images.githubusercontent.com/4630670/113607959-2d7f5d00-964a-11eb-8838-3fb9aba1bd52.mp4

<details>
  <summary>Logs</summary>

```
Analyzing bug_datatable...
No issues found! (ran in 10.7s)
```

```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.867], locale sv-SE)
    • Flutter version 2.0.4 at C:\Users\Leif\Programmering\Libraries\flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Leif\Programmering\Android\android-sdks
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 32-bit edition (version 1.54.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by chinmoy12c**
DataRow receives focus even when onSelectChanged is null. This change enables the user to override this behavior and prevent DataRow to receive focus by default.

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes: #79800 
Fixes: #74022

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/data_table_test.dart [hunk 1]
```diff
@@ -1629,4 +1629,39 @@ void main() {
       _customHorizontalMargin,
     );
   });
+
+  testWidgets('DataRow does not receive focus by default', (WidgetTester tester) async {
```
Comment (gspencergoog) [inline packages/flutter/test/material/data_table_test.dart:1633]: This really has nothing to do with focus, it has to do with being enabled/disabled.  It really should say something like "DataRow is disabled when `onSelectChanged` is not set" or something similar.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Please correct the test description, and then this is ready to go.
