### PR TITLE
Mark routes as opaque when added without animation

### LINKED ISSUE #38038: [Tooling] MaterialApp Navigator stack appears as children in the widget tree
## Steps to Reproduce

Made a 2 min video of how this affects us in particular. When using the select widget tools, widgets from the back layers get selected.
https://www.youtube.com/watch?v=067oK-kWi2s

1. Is this expected behaviour
2. If not, then what might be causing this, also how to get around this problem?

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

Prior to this change TransitionRoutes that were added without animation would not properly mark their first OverlayEntry as opaque. This means Flutter was rendering Routes that weren't visible (and those invisible Routes also showed up in the inspector and confused people there). This happened most prominently when the initial routes where added because those always skip their entrance animation. 

This change now properly marks the OverlayEntrys of those routes as opaque.

It also modifies OverlayEntry.opaque to allow modifying the opaqueness before the entry is added to an overlay.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/38038.

## Tests

I added the following tests:

* OverlayEntry.opaque can be changed when OverlayEntry is not part of an Overlay (yet)
* OverlayEntry of topmost initial route is marked as opaque
* OverlayEntry of topmost route is set to opaque after Push
* OverlayEntry of topmost route is set to opaque after Replace

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/heroes_test.dart [hunk 1]
```diff
@@ -1754,7 +1754,7 @@ Future<void> main() async {
       routes: routes,
       initialRoute: '/two',
     ));
-    expect(find.text('two'), findsOneWidget);
+    expect(tester.takeException(), isNull);
```
Comment (dnfield) [inline packages/flutter/test/widgets/heroes_test.dart]: This LGTM.  This was the actual intent of the test at the time - I probably either mistook which route actually had which widget, or was just doing this to make sure we didn't fire an assert.

Would it be worth testing here `expect(find.text('two'), findsNothing)` and `expect(find.text('three'), findsOneWidget)`?

Also, should we be worried about this breaking internal tests that relied on this behavior?

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 2]
```diff
@@ -86,8 +86,7 @@ class OverlayEntry {
     if (_opaque == value)
       return;
     _opaque = value;
-    assert(_overlay != null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/overlay.dart]: I think this change make sense, but how didn't we encounter this case prior to this change?

File: packages/flutter/test/widgets/heroes_test.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/heroes_test.dart]: Added those expects.

I think we just have to update those tests then. They are relying on a bug. Doing so is easy, see some of the other tests in this PR that I had to update.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/overlay.dart]: We were only modified the opaqueness after the OverlayEntry was added to the Overlay (or when constructing the OverlayEntry by passing the opaque parameter in the constructor).

File: packages/flutter/test/widgets/overlay_test.dart [hunk 3]
```diff
@@ -657,4 +657,45 @@ void main() {
...
+
+    expect(find.byKey(root), findsOneWidget);
+
+    final OverlayEntry newEntry = OverlayEntry(
+      builder: (BuildContext context) {
+        return Container(key: top);
+      },
+    );
+    expect(newEntry.opaque, isFalse);
+    newEntry.opaque = true; // Does neither trigger an assert nor throw.
```
Comment (chunhtai) [inline packages/flutter/test/widgets/overlay_test.dart]: instead of adding comment, we can use expect(tester.takeException(), isNull);

**Review by chunhtai — APPROVED** [review]
LGTM, with some nit
