### PR TITLE
Fix: TextField can inherit `errorStyle` from `InputDecorationTheme`.

### LINKED ISSUE #140607: `TextField` error state cursor color does not make use of `Theme.of(context).inputDecorationTheme`
### Steps to reproduce

1. Run the code sample
2. Click on either `TextField`s to show the cursor
3. Notice the difference in the color of the cursors

### Expected results

The color of the cursors in both example should have been the same green.

### Actual results

The color of the first `TextField` is the default MD3 error color, while the color of the second `TextField` is the expected `Colors.green`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const _errorStyle = TextStyle(color: Colors.green);

var _themeData = ThemeData(
  inputDecorationTheme: const InputDecorationTheme(
    errorStyle: _errorStyle,
  ),
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: _themeData, // setting errorStyle "globally"
      home: Scaffold(
        body: ListView(
          children: const [
            TextField(decoration: InputDecoration(
              errorText: "Some error here"
            )),
            TextField(decoration: InputDecoration(
              errorStyle: _errorStyle, // setting errorStyle "locally"
              errorText: "Some error here"
            )),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3803], locale en-150)
    • Flutter version 3.16.5 on channel stable at D:\not_important_programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\UserName\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19045.3803]

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Previously `TextField`s error `cursorColor` was being derived without taking into account any `InputDecorationTheme` defaults. This change respects `InputDecorationTheme` defaults when deriving the error `cursorColor`.

Fixes #140607

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
 
   bool get _hasError => widget.decoration?.errorText != null || widget.decoration?.error != null || _hasIntrinsicError;
 
-  Color get _errorColor => widget.cursorErrorColor ?? widget.decoration?.errorStyle?.color ?? Theme.of(context).colorScheme.error;
+  Color get _errorColor => widget.cursorErrorColor ?? _getEffectiveDecoration().errorStyle?.color ?? Theme.of(context).colorScheme.error;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart:1003]: I wonder if there's anywhere else that should be using _getEffectiveDecoration instead of widget.decoration?

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/material/text_field.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/text_field.dart:1003]: I checked this out and didn't see anything else that stood out. Other uses like accessing `enabled`, `counterText`, `errorText` or `hintText` are okay because those are not inherited from an `InputDecorationTheme`.
