### PR TITLE
Various docs easy fixes

### LINKED ISSUE #10776: Some feedback on InkResponse API docs
Something like this might help:

InkResponse does two things when responding to a tap:

* It starts to animate and grow a _highlight_ from the center of the widget (or, is this the child?). This is the "highlight" circle in the below screenshots.

* It starts to animate and grow a _splash_ from the tap down location. This is the "splash" circle in the below screenshots.

The highlight will grow to the size of _________________. The splash will grow to the size of ___________.

Then, another suggestion is to split the top image into two screenshots, and put the explanatory text before each screenshot.

Specifically:

"The following diagram .... [then show the diagram]. In contrast, here's a diagram that shows ... [then show the second diagram]."

### PR DESCRIPTION
**Pull request by Hixie**
cc @sethladd 

Fixes #10776, #10766, #10683, and out-of-band feedback.

### CODE REVIEW

File: packages/flutter/lib/src/material/ink_well.dart [hunk 1]
```diff
@@ -85,31 +107,76 @@ class InkResponse extends StatefulWidget {
...
+  /// being highlighted.
   ///
   /// The value passed to the callback is true if this part of the material has
   /// become highlighted and false if this part of the material has stopped
   /// being highlighted.
   final ValueChanged<bool> onHighlightChanged;
 
   /// Whether this ink response should be clipped its bounds.
+  ///
+  /// This flag also controls whether the splash migrates to the center of the
```
Comment (sethladd) [inline packages/flutter/lib/src/material/ink_well.dart]: oh! Glad you indicated this :)

**Comment by sethladd** [comment]
These are great, thank you!

**Review by sethladd — APPROVED** [review]
lgtm
