### PR TITLE
EditableText.bringIntoView calls showOnScreen

### LINKED ISSUE #55547: TextField TextSelection Toolbar scrolling bug when inside ListView
## Steps to Reproduce
**1. Run `flutter create bug`.**
**2. Update the files as follows:**
```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textSelectionHandleColor: Colors.red,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Bug(title: 'TEXT SELECTION BUG'),
    );
  }
}

class Bug extends StatelessWidget {
  final String title;

  Bug({this.title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: Text(title),
        ),
        bottomNavigationBar: BottomAppBar(
          child: Container(
            padding: EdgeInsets.all(12.0),
            margin: MediaQuery.of(context).viewInsets,
            color: Theme.of(context).accentColor,
            child: Text(
              "THIS IS BOTTOM APP BAR",
              textAlign: TextAlign.center,
              style: Theme.of(context)
                  .textTheme
                  .subtitle1
                  .copyWith(color: Colors.white),
            ),
          ),
        ),
        body: ListView(
          children: [
            Padding(
              padding: EdgeInsets.all(18.0),
              child: TextField(
                maxLines: null,
                style: Theme.of(context).textTheme.headline6,
                decoration: InputDecoration.collapsed(
                  hintText: 'Write something here...',
                ),
              ),
            ),
          ],
        ));
  }
}

```

3. Step to produce bug:
-         Paste a very long text
-         Do some text selection ( Select all or try to move the Text Selection Handle )

### Video example explaining this bug: [Video](https://youtu.be/llH8qWTaaNU)

**Expected results:** Edge Scrolling works like using **TextField** without **ListView Widget**

**Actual results:** Edge Scrolling broken when using **TextField** inside **ListView Widget**

### `flutter doctor -v` result:

```

[✓] Flutter (Channel master, v1.18.0-7.0.pre.58, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-7.0.pre.58 at /home/v4vendetta/flutter
    • Framework revision e0c63cd35e (7 hours ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/v4vendetta/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/v4vendetta/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/v4vendetta/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • Redmi Note 7              • dd14c9d       • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

- Call `showOnScreen` in `EditableText.bringIntoView`, so it works in a viewport
- Prevent `Editable` implicit scrolling if enforced by the scroll physics 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/55547

## Tests

I added the following tests:

- bringIntoView brings the caret into view when in a viewport
- bringIntoView does nothing if the physics prohibits implicit scrolling

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -1487,45 +1487,57 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    double additionalOffset;
+    Offset unitOffset;
+
+    if (!_isMultiline) {
+      additionalOffset = rect.width >= editableSize.width
+        // Center `rect` if it's oversized.
+        ? editableSize.width / 2 - rect.center.dx
+        // Valid additional offsets range from (rect.right - size.width)
+        // to (rect.left). Pick the closest one if out of range.
+        : 0.0.clamp(rect.right - editableSize.width, rect.left) as double;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:1513]: Cool way of doing this that I haven't seen before 👍

**Review by justinmc — APPROVED** [review]
LGTM, thanks for fixing this!  I checked out the code and it worked for me, I couldn't break it.

**Review by goderbauer — APPROVED** [review]
LGTM
