### PR TITLE
Default add-to-app xcode_backend script to be verbose

### LINKED ISSUE #70329: Running add-to-app host on a simulator with a profile or release Flutter fails `Command PhaseScriptExecution failed with a nonzero exit code` with no details
I'm unable to build my add-to-app project for iOS.  The added build phase script fails with the following error:

```
/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
```

contents of flutter_export_environment.sh
```
#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/aaclarke/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=.packages"
```

<details>

<summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.91, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-2.0.pre.91 at /Users/aaclarke/dev/flutter
    • Framework revision cb5865d86c (3 weeks ago), 2020-10-20 09:50:31 -0700
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183

• No issues found!
```

</details>

<details>

<summary>failure log</summary>

```
PhaseScriptExecution [CP-User]\ Run\ Flutter\ Build\ double_engine\ Script /Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Script-003F7D6999A39C7046A9F596.sh (in target 'DoubleEngine' from project 'DoubleEngine')
    cd /Users/aaclarke/dev/DoubleEngine
    export ACTION=build
    export AD_HOC_CODE_SIGNING_ALLOWED=YES
    export ALTERNATE_GROUP=primarygroup
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=aaclarke
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
    export ALWAYS_SEARCH_USER_PATHS=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export APPLY_RULES_IN_COPY_HEADERS=NO
    export ARCHS=x86_64
    export ARCHS_STANDARD=x86_64
    export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
    export ARCHS_STANDARD_32_BIT=i386
    export ARCHS_STANDARD_64_BIT=x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
    export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
    export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
    export ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME=AccentColor
    export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
    export AppIdentifierPrefix=5B6X25244C.
    export BITCODE_GENERATION_MODE=marker
    export BUILD_ACTIVE_RESOURCES_ONLY=YES
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products
    export BUILD_LIBRARY_FOR_DISTRIBUTION=NO
    export BUILD_ROOT=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator
    export BUNDLE_CONTENTS_FOLDER_PATH_deep=Contents/
    export BUNDLE_EXECUTABLE_FOLDER_NAME_deep=MacOS
    export BUNDLE_FORMAT=shallow
    export BUNDLE_FRAMEWORKS_FOLDER_PATH=Frameworks
    export BUNDLE_PLUGINS_FOLDER_PATH=PlugIns
    export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH=PrivateHeaders
    export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH=Headers
    export CACHE_ROOT=/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/C/com.apple.DeveloperTools/11.5-11E608c/Xcode
    export CCHROOT=/var/folders/2y/72984f4n0r7fskhjt3qctglw00915v/C/com.apple.DeveloperTools/11.5-11E608c/Xcode
    export CHMOD=/bin/chmod
    export CHOWN=/usr/sbin/chown
    export CLANG_ANALYZER_NONNULL=YES
    export CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION=YES_AGGRESSIVE
    export CLANG_CXX_LANGUAGE_STANDARD=gnu++14
    export CLANG_CXX_LIBRARY=libc++
    export CLANG_ENABLE_MODULES=YES
    export CLANG_ENABLE_OBJC_ARC=YES
    export CLANG_ENABLE_OBJC_WEAK=YES
    export CLANG_MODULES_BUILD_SESSION_FILE=/Users/aaclarke/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
    export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
    export CLANG_WARN_BOOL_CONVERSION=YES
    export CLANG_WARN_COMMA=YES
    export CLANG_WARN_CONSTANT_CONVERSION=YES
    export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
    export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
    export CLANG_WARN_DOCUMENTATION_COMMENTS=YES
    export CLANG_WARN_EMPTY_BODY=YES
    export CLANG_WARN_ENUM_CONVERSION=YES
    export CLANG_WARN_INFINITE_RECURSION=YES
    export CLANG_WARN_INT_CONVERSION=YES
    export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
    export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
    export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
    export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
    export CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=YES
    export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
    export CLANG_WARN_STRICT_PROTOTYPES=YES
    export CLANG_WARN_SUSPICIOUS_MOVE=YES
    export CLANG_WARN_UNGUARDED_AVAILABILITY=YES_AGGRESSIVE
    export CLANG_WARN_UNREACHABLE_CODE=YES
    export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
    export CLASS_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/JavaClasses
    export CLEAN_PRECOMPS=YES
    export CLONE_HEADERS=NO
    export CODESIGNING_FOLDER_PATH=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator/DoubleEngine.app
    export CODE_SIGNING_ALLOWED=YES
    export CODE_SIGNING_REQUIRED=YES
    export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
    export CODE_SIGN_IDENTITY=-
    export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
    export CODE_SIGN_STYLE=Automatic
    export COLOR_DIAGNOSTICS=NO
    export COMBINE_HIDPI_IMAGES=NO
    export COMPILER_INDEX_STORE_ENABLE=Default
    export COMPOSITE_SDK_DIRS=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/CompositeSDKs
    export COMPRESS_PNG_FILES=YES
    export CONFIGURATION=Profile
    export CONFIGURATION_BUILD_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator
    export CONFIGURATION_TEMP_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator
    export CONTENTS_FOLDER_PATH=DoubleEngine.app
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_HEADERS_RUN_UNIFDEF=NO
    export COPY_PHASE_STRIP=NO
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
    export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
    export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
    export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk
    export CORRESPONDING_DEVICE_SDK_NAME=iphoneos13.5
    export CP=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export CURRENT_ARCH=undefined_arch
    export CURRENT_VARIANT=normal
    export DEAD_CODE_STRIPPING=YES
    export DEBUGGING_SYMBOLS=YES
    export DEBUG_INFORMATION_FORMAT=dwarf-with-dsym
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
    export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
    export DEPLOYMENT_TARGET_LD_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_LD_FLAG_NAME=ios_simulator_version_min
    export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2 13.3 13.4 13.5"
    export DERIVED_FILES_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/DerivedSources
    export DERIVED_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/DerivedSources
    export DERIVED_SOURCES_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=en
    export DEVELOPMENT_TEAM=5B6X25244C
    export DOCUMENTATION_FOLDER_PATH=DoubleEngine.app/en.lproj/Documentation
    export DONT_GENERATE_INFOPLIST_FILE=NO
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/DoubleEngine.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=DoubleEngine.app.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator
    export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
    export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
    export ENABLE_BITCODE=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
    export ENABLE_HARDENED_RUNTIME=NO
    export ENABLE_HEADER_DEPENDENCIES=YES
    export ENABLE_NS_ASSERTIONS=NO
    export ENABLE_ON_DEMAND_RESOURCES=YES
    export ENABLE_PREVIEWS=NO
    export ENABLE_STRICT_OBJC_MSGSEND=YES
    export ENABLE_TESTABILITY=NO
    export ENABLE_TESTING_SEARCH_PATHS=NO
    export ENTITLEMENTS_DESTINATION=__entitlements
    export ENTITLEMENTS_REQUIRED=YES
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
    export EXECUTABLES_FOLDER_PATH=DoubleEngine.app/Executables
    export EXECUTABLE_FOLDER_PATH=DoubleEngine.app
    export EXECUTABLE_NAME=DoubleEngine
    export EXECUTABLE_PATH=DoubleEngine.app/DoubleEngine
    export EXPANDED_CODE_SIGN_IDENTITY=-
    export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
    export FILE_LIST=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects/LinkFileList
    export FIXED_FILES_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/FixedFiles
    export FRAMEWORKS_FOLDER_PATH=DoubleEngine.app/Frameworks
    export FRAMEWORK_FLAG_PREFIX=-framework
    export FRAMEWORK_SEARCH_PATHS="/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator  "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter" "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter/engine""
    export FRAMEWORK_VERSION=A
    export FULL_PRODUCT_NAME=DoubleEngine.app
    export GCC3_VERSION=3.3
    export GCC_C_LANGUAGE_STANDARD=gnu11
    export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
    export GCC_NO_COMMON_BLOCKS=YES
    export GCC_OBJC_LEGACY_DISPATCH=YES
    export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
    export GCC_PREPROCESSOR_DEFINITIONS=" COCOAPODS=1"
    export GCC_SYMBOLS_PRIVATE_EXTERN=YES
    export GCC_TREAT_WARNINGS_AS_ERRORS=NO
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
    export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
    export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
    export GCC_WARN_UNDECLARED_SELECTOR=YES
    export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
    export GCC_WARN_UNUSED_FUNCTION=YES
    export GCC_WARN_UNUSED_VARIABLE=YES
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=YES
    export GENERATE_PROFILING_CODE=NO
    export GENERATE_TEXT_BASED_STUBS=NO
    export GID=89939
    export GROUP=primarygroup
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HEADER_SEARCH_PATHS="/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator/include  "/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public" "/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public/FlutterPluginRegistrant""
    export HIDE_BITCODE_SYMBOLS=YES
    export HOME=/Users/aaclarke
    export ICONV=/usr/bin/iconv
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_FILE=DoubleEngine/Info.plist
    export INFOPLIST_OUTPUT_FORMAT=binary
    export INFOPLIST_PATH=DoubleEngine.app/Info.plist
    export INFOPLIST_PREPROCESS=NO
    export INFOSTRINGS_PATH=DoubleEngine.app/en.lproj/InfoPlist.strings
    export INLINE_PRIVATE_FRAMEWORKS=NO
    export INSTALLHDRS_COPY_PHASE=NO
    export INSTALLHDRS_SCRIPT_PHASE=NO
    export INSTALL_DIR=/tmp/DoubleEngine.dst/Applications
    export INSTALL_GROUP=primarygroup
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER=aaclarke
    export INSTALL_PATH=/Applications
    export INSTALL_ROOT=/tmp/DoubleEngine.dst
    export IPHONEOS_DEPLOYMENT_TARGET=13.0
    export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FOLDER_PATH=DoubleEngine.app/Java
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal/undefined_arch/DoubleEngine_dependency_info.dat
    export LD_ENTITLEMENTS_SECTION=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/DoubleEngine.app-Simulated.xcent
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/DoubleEngine-LinkMap-normal-undefined_arch.txt
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LD_RUNPATH_SEARCH_PATHS=" '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks"
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LEX=lex
    export LIBRARY_DEXT_INSTALL_PATH=/Library/DriverExtensions
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_FLAG_PREFIX=-l
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LIBRARY_SEARCH_PATHS="/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator  "/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator/FlutterPluginRegistrant""
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_FILE_LIST_normal_x86_64=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal/x86_64/DoubleEngine.LinkFileList
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LLVM_TARGET_TRIPLE_OS_VERSION=ios13.0
    export LLVM_TARGET_TRIPLE_SUFFIX=-simulator
    export LLVM_TARGET_TRIPLE_VENDOR=apple
    export LOCALIZED_RESOURCES_FOLDER_PATH=DoubleEngine.app/en.lproj
    export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFCopyLocalizedString"
    export LOCALIZED_STRING_SWIFTUI_SUPPORT=YES
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export LOCROOT=/Users/aaclarke/dev/DoubleEngine
    export LOCSYMROOT=/Users/aaclarke/dev/DoubleEngine
    export MACH_O_TYPE=mh_execute
    export MAC_OS_X_PRODUCT_BUILD_VERSION=19H2
    export MAC_OS_X_VERSION_ACTUAL=101507
    export MAC_OS_X_VERSION_MAJOR=101500
    export MAC_OS_X_VERSION_MINOR=1507
    export METAL_LIBRARY_FILE_BASE=default
    export METAL_LIBRARY_OUTPUT_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator/DoubleEngine.app
    export MODULES_FOLDER_PATH=DoubleEngine.app/Modules
    export MODULE_CACHE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
    export MTL_ENABLE_DEBUG_INFO=NO
    export MTL_FAST_MATH=YES
    export NATIVE_ARCH=x86_64
    export NATIVE_ARCH_32_BIT=i386
    export NATIVE_ARCH_64_BIT=x86_64
    export NATIVE_ARCH_ACTUAL=x86_64
    export NO_COMMON=YES
    export OBJC_ABI_VERSION=2
    export OBJECT_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects
    export OBJECT_FILE_DIR_normal=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal
    export OBJROOT=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex
    export ONLY_ACTIVE_ARCH=NO
    export OS=MACOS
    export OSAC=/usr/bin/osacompile
    export OTHER_CFLAGS=" -fmodule-map-file="/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public/FlutterPluginRegistrant/FlutterPluginRegistrant.modulemap" -isystem "/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public" -iframework "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter/engine" -iframework "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter""
    export OTHER_CPLUSPLUSFLAGS=" -fmodule-map-file="/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public/FlutterPluginRegistrant/FlutterPluginRegistrant.modulemap" -isystem "/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public" -iframework "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter/engine" -iframework "/Users/aaclarke/dev/DoubleEngine/Pods/../DoubleEngine/double_engine/.ios/Flutter""
    export OTHER_LDFLAGS=" -ObjC -l"FlutterPluginRegistrant" -framework "App" -framework "Flutter""
    export OTHER_SWIFT_FLAGS=" -D COCOAPODS -Xcc -fmodule-map-file="/Users/aaclarke/dev/DoubleEngine/Pods/Headers/Public/FlutterPluginRegistrant/FlutterPluginRegistrant.modulemap""
    export PACKAGE_TYPE=com.apple.package-type.wrapper.application
    export PASCAL_STRINGS=YES
    export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
    export PBDEVELOPMENTPLIST_PATH=DoubleEngine.app/pbdevelopment.plist
    export PER_ARCH_OBJECT_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal/undefined_arch
    export PER_VARIANT_OBJECT_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal
    export PKGINFO_FILE_PATH=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/PkgInfo
    export PKGINFO_PATH=DoubleEngine.app/PkgInfo
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
    export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
    export PLATFORM_DISPLAY_NAME="iOS Simulator"
    export PLATFORM_FAMILY_NAME=iOS
    export PLATFORM_NAME=iphonesimulator
    export PLATFORM_PREFERRED_ARCH=x86_64
    export PLATFORM_PRODUCT_BUILD_VERSION=17F65
    export PLIST_FILE_OUTPUT_FORMAT=binary
    export PLUGINS_FOLDER_PATH=DoubleEngine.app/PlugIns
    export PODS_BUILD_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products
    export PODS_CONFIGURATION_BUILD_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator
    export PODS_PODFILE_DIR_PATH=/Users/aaclarke/dev/DoubleEngine/.
    export PODS_ROOT=/Users/aaclarke/dev/DoubleEngine/Pods
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRIVATE_HEADERS_FOLDER_PATH=DoubleEngine.app/PrivateHeaders
    export PRODUCT_BUNDLE_IDENTIFIER=dev.flutter.DoubleEngine
    export PRODUCT_BUNDLE_PACKAGE_TYPE=APPL
    export PRODUCT_MODULE_NAME=DoubleEngine
    export PRODUCT_NAME=DoubleEngine
    export PRODUCT_SETTINGS_PATH=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/Info.plist
    export PRODUCT_TYPE=com.apple.product-type.application
    export PROFILING_CODE=NO
    export PROJECT=DoubleEngine
    export PROJECT_DERIVED_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/DerivedSources
    export PROJECT_DIR=/Users/aaclarke/dev/DoubleEngine
    export PROJECT_FILE_PATH=/Users/aaclarke/dev/DoubleEngine/DoubleEngine.xcodeproj
    export PROJECT_NAME=DoubleEngine
    export PROJECT_TEMP_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build
    export PROJECT_TEMP_ROOT=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex
    export PUBLIC_HEADERS_FOLDER_PATH=DoubleEngine.app/Headers
    export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export REZ_COLLECTOR_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/ResourceManagerResources
    export REZ_OBJECTS_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/ResourceManagerResources/Objects
    export REZ_SEARCH_PATHS="/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator "
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SCRIPTS_FOLDER_PATH=DoubleEngine.app/Scripts
    export SCRIPT_INPUT_FILE_0=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.metadata
    export SCRIPT_INPUT_FILE_1=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/App.framework/App
    export SCRIPT_INPUT_FILE_2=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/engine/Flutter.framework/Flutter
    export SCRIPT_INPUT_FILE_3=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/flutter_export_environment.sh
    export SCRIPT_INPUT_FILE_COUNT=4
    export SCRIPT_INPUT_FILE_LIST_COUNT=0
    export SCRIPT_OUTPUT_FILE_COUNT=0
    export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk
    export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk
    export SDK_DIR_iphonesimulator13_5=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk
    export SDK_NAME=iphonesimulator13.5
    export SDK_NAMES=iphonesimulator13.5
    export SDK_PRODUCT_BUILD_VERSION=17F65
    export SDK_VERSION=13.5
    export SDK_VERSION_ACTUAL=130500
    export SDK_VERSION_MAJOR=130000
    export SDK_VERSION_MINOR=500
    export SED=/usr/bin/sed
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SET_DIR_MODE_OWNER_GROUP=YES
    export SET_FILE_MODE_OWNER_GROUP=NO
    export SHALLOW_BUNDLE=YES
    export SHARED_DERIVED_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator/DerivedSources
    export SHARED_FRAMEWORKS_FOLDER_PATH=DoubleEngine.app/SharedFrameworks
    export SHARED_PRECOMPS_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/PrecompiledHeaders
    export SHARED_SUPPORT_FOLDER_PATH=DoubleEngine.app/SharedSupport
    export SKIP_INSTALL=NO
    export SOURCE_ROOT=/Users/aaclarke/dev/DoubleEngine
    export SRCROOT=/Users/aaclarke/dev/DoubleEngine
    export STRINGS_FILE_OUTPUT_ENCODING=binary
    export STRIP_BITCODE_FROM_COPIED_FILES=NO
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_STYLE=all
    export STRIP_SWIFT_SYMBOLS=YES
    export SUPPORTED_DEVICE_FAMILIES=1,2
    export SUPPORTED_PLATFORMS="iphoneos iphonesimulator"
    export SUPPORTS_TEXT_BASED_API=NO
    export SWIFT_PLATFORM_TARGET_PREFIX=ios
    export SWIFT_RESPONSE_FILE_PATH_normal_x86_64=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Objects-normal/x86_64/DoubleEngine.SwiftFileList
    export SYMROOT=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TAPI_VERIFY_MODE=ErrorsOnly
    export TARGETED_DEVICE_FAMILY=1,2
    export TARGETNAME=DoubleEngine
    export TARGET_BUILD_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Products/Profile-iphonesimulator
    export TARGET_DEVICE_IDENTIFIER=7E4F8CFC-1B42-4AD6-92CC-5467A1103005
    export TARGET_DEVICE_MODEL=iPhone12,8
    export TARGET_DEVICE_OS_VERSION=13.5
    export TARGET_NAME=DoubleEngine
    export TARGET_TEMP_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build
    export TEMP_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build
    export TEMP_FILES_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build
    export TEMP_FILE_DIR=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build
    export TEMP_ROOT=/Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex
    export TEST_FRAMEWORK_SEARCH_PATHS=" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks"
    export TEST_LIBRARY_SEARCH_PATHS=" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib"
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export TeamIdentifierPrefix=5B6X25244C.
    export UID=296123
    export UNLOCALIZED_RESOURCES_FOLDER_PATH=DoubleEngine.app
    export UNSTRIPPED_PRODUCT=NO
    export USER=aaclarke
    export USER_APPS_DIR=/Users/aaclarke/Applications
    export USER_LIBRARY_DIR=/Users/aaclarke/Library
    export USE_DYNAMIC_NO_PIC=YES
    export USE_HEADERMAP=YES
    export USE_HEADER_SYMLINKS=NO
    export USE_LLVM_TARGET_TRIPLES=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_CLANG=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_LD=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_TAPI=YES
    export USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES=YES
    export VALIDATE_DEVELOPMENT_ASSET_PATHS=YES_ERROR
    export VALIDATE_PRODUCT=YES
    export VALIDATE_WORKSPACE=YES_ERROR
    export VALID_ARCHS="i386 x86_64"
    export VERBOSE_PBXCP=NO
    export VERSIONPLIST_PATH=DoubleEngine.app/version.plist
    export VERSION_INFO_BUILDER=aaclarke
    export VERSION_INFO_FILE=DoubleEngine_vers.c
    export VERSION_INFO_STRING=""@(#)PROGRAM:DoubleEngine  PROJECT:DoubleEngine-""
    export WRAPPER_EXTENSION=app
    export WRAPPER_NAME=DoubleEngine.app
    export WRAPPER_SUFFIX=.app
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=11E608c
    export XCODE_VERSION_ACTUAL=1150
    export XCODE_VERSION_MAJOR=1100
    export XCODE_VERSION_MINOR=1150
    export XPCSERVICES_FOLDER_PATH=DoubleEngine.app/XPCServices
    export YACC=yacc
    export arch=undefined_arch
    export variant=normal
    /bin/sh -c /Users/aaclarke/Library/Developer/Xcode/DerivedData/DoubleEngine-bjiehxhomkvpoffnvczpaadeqsfv/Build/Intermediates.noindex/DoubleEngine.build/Profile-iphonesimulator/DoubleEngine.build/Script-003F7D6999A39C7046A9F596.sh

/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

Command PhaseScriptExecution failed with a nonzero exit code
```

</details>

Steps taken to remedy:
1) `flutter build ios` in module
1) `pod install`

cc @jmagman

### PR DESCRIPTION
**Pull request by jmagman**
## Description

There's no `flutter run --verbose` available for host add-to-app to see why `assemble` failed.  Until we can emit better, more focused error messages, default to making the script run in verbose mode so it can be seen in the Xcode build logs.
This matches macOS app behavior.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/70329

## Tests

create_test

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart [hunk 1]
```diff
@@ -110,6 +110,7 @@ void _updateGeneratedEnvironmentVariablesScript({
   for (final String line in xcodeBuildSettings) {
     localsBuffer.writeln('export "$line"');
   }
```
Comment (xster) [inline packages/flutter_tools/lib/src/ios/xcodeproj.dart:112]: can we add a comment or rename the private method to make it harder to accidentally refactor the normal flow to use this script and get verbose? e.g. make the verbose <-> script <-> add-to-app linkage more explicit?

**Review by xster — APPROVED** [review]

File: packages/flutter_tools/lib/src/ios/xcodeproj.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart:112]: You're right, I can move this to a more explicit add-to-app spot.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/xcodeproj.dart]: Moved it into the pod script phase.

File: dev/devicelab/bin/tasks/module_test_ios.dart [hunk 2]
```diff
@@ -315,7 +315,7 @@ Future<void> main() async {
             'Host',
             '-configuration',
             'Debug',
-            'ARCHS=i386', // i386 is not supported in Debug mode.
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/module_test_ios.dart:318]: This was actually failing in CocoaPods before the Flutter script could run.

**Comment by jmagman** [comment]
@xster Does this still LGT[u]? I rewrote it.

**Review by xster — COMMENTED** [review]
Still LGTM
