### PR TITLE
Disable blinking cursor when `EditableText.showCursor` is false

### LINKED ISSUE #108187: Focused TextField in readOnly state emits continuous Frame Events
Hey Flutter Team -

I have identified what seems to be an issue related to a _focused_ `readOnly: true` TextField.

What's happening is the TextField in this state emits a continuous stream of Frame Events reflecting similar behavior to that of a `readOnly: false` TextField where the cursor animates in and out.

Your help would be very much appreciated.

Thanks!

### Steps to reproduce

1. Clone the demo repository here: https://github.com/mack-at-pieces/flutter_text_field
2. Run the demo app in profile mode using the command `flutter run -d macos --profile`.
3. Open the Flutter DevTools debugger and profiler at the link provided by the command output
4. Navigate to the running demo app and tap to bring into focus.
5. At this point, the Frame Chart is idle and no events are occurring.
6. Next, tap the TextField to bring focus as if you are going to input a value.
7. Observe the Frame Chart and you will now see a continuous stream of events being emitted. This represents that of a `readOnly: false` TextField where the cursor animates in and out.

### Demo
https://github.com/mack-at-pieces/flutter_text_field

### Target Platform
macOS

_I did not attempt to reproduce this on Windows, Linux, iOS, or Android, however I believe this problem may still be present on those platforms as well_

### Target OS version/browser
macOS Monterey Version 12.0.1

### Devices
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Max
Memory: 64 GB

## Logs

<details>
<summary>Logs</summary>

```
mackmyers@Macks-MacBook-Pro flutter_text_field % flutter analyze
Analyzing flutter_text_field...                                         
No issues found! (ran in 0.9s)
```

```
mackmyers@Macks-MacBook-Pro flutter_text_field % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.0.1 21A559 darwin-arm (Rosetta), locale en-US)
    • Flutter version 3.0.5 at /Users/mackmyers/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mackmyers/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.3
    • Dart plugin version 213.7371

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/108187

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM :+1:, this is will probably save a lot of unnecessary CPU in the world.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 1]
```diff
@@ -505,34 +505,6 @@ void main() {
     expect(findRenderEditable(tester).textHeightBehavior, textHeightBehavior);
   });
 
-  testWidgets('Cursor blinks when showCursor is true', (WidgetTester tester) async {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/selectable_text_test.dart:508]: @chunhtai this change would make SelectableText lose its blinking cursor, does that sound ok to you?

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/selectable_text_test.dart]: Changed to showCusor now the tests are passing.

File: packages/flutter/test/widgets/editable_text_cursor_test.dart [hunk 2]
```diff
@@ -771,6 +771,54 @@ void main() {
     await checkCursorBlinking();
   });
 
+  testWidgets('Turning readOnly on stops the cursor', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/108187 .
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_cursor_test.dart:775]: Nit: Extra space before the period here.  Or maybe that's fine to distinguish the URL...

**Review by justinmc — APPROVED** [review]
Renewing my LGTM with the changes :+1:

File: packages/flutter/test/widgets/editable_text_cursor_test.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_cursor_test.dart:775]: Yeah when I click the URL in vscode I think it would bring me to a nonexistent page if the space is removed. It's valid in URLs I think.

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_cursor_test.dart]: Well I forgot to update the name of the test. Removed the space and updated the test name.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -2610,12 +2610,11 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     final bool newTickerEnabled = TickerMode.of(context);
     if (_tickersEnabled != newTickerEnabled) {
       _tickersEnabled = newTickerEnabled;
-      if (_tickersEnabled && _cursorActive) {
+      final bool needsBlinkingCursor = _hasFocus && _value.selection.isCollapsed && widget.showCursor;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:2613]: Consider moving this into a getter also why not move _tickersEnabled into this bool like the one below does

**Review by chunhtai — APPROVED** [review]
LGTM, just some nits
