### PR TITLE
Make artifact downloading more robust for flaky networks

### LINKED ISSUE #13693: "flutter doctor" always downloads package from start no matter previous downloaded or not.
I setup flutter environment on my MacBook via "flutter doctor" under slow and unstable network . It took hours to download all packages, darwin, android, and IOS. When I re-ran "flutter doctor" after network broke, all previous downloaded packages would be downloaded again and took another a few hours. and network broke again. I was stuck in this step many times. I'm wondering is that possible to check downloaded packages before trigger new download for flutter setup?

## Steps to Reproduce
1. Install flutter to new box.
2. Run ```flutter doctor``` to setup environment.
3. Wait for a few packages downloading and disconnect network before all packages download complete.
4. Run ```flutter doctor``` to setup environment again.
5. Existing packages were downloaded again. Wait for a few packages downloading and disconnect network before all packages download complete.
6. Repeat step 4 and 5. Flutter always downloads package from 1st one no matter it was downloaded previously or not.

I know the 3rd steps wasn't real but remember that I'm in **slow and unstable network** facility and my network broke frequently. Therefore, I used disconnect to simulate unstable network.

## Logs
No log since issue was on flutter setup.

## Flutter Doctor
$: flutter doctor
Downloading package sky_engine...                    22.7s
Downloading common tools...                          168.3s
Downloading darwin-x64 tools...                      730.0s
Downloading darwin-x64 tools...                      1113.7s
Downloading android-arm-profile/darwin-x64 tools...  97.8s
Downloading android-arm-release/darwin-x64 tools...  84.4s
Downloading android-x86 tools...                     474.9s
Downloading android-x64 tools...                     478.0s
Downloading android-arm tools...                     280.2s
Downloading android-arm-profile tools...             201.9s
Downloading android-arm-release tools...             169.0s
Downloading ios tools...                                  
Download failed -- attempting retry 1 in 1 second...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 55793
Crash report written to /Users/user/flutter/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #13693.  Trap all exceptions during the transfer since download errors can cause a variety of exceptions, not just IOException.  Cache individual downloaded files of `CachedArtifact` in a "downloads" directory under bin/cache until the entire `CachedArtifact` is up to date, and use gzip/zip checksums to detect partial or corrupt downloads.
 
This seems to handle a variety of unexpected conditions well, like control-Cing in the middle of precache and restarting it.  The broader catch should prevent the crash reported in #13693, though since I'm missing the crash report that's not totally proven.

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/net.dart [hunk 1]
```diff
@@ -57,7 +57,8 @@ Future<List<int>> _attempt(Uri url) async {
     final BytesBuilder responseBody = new BytesBuilder(copy: false);
     await response.forEach(responseBody.add);
     return responseBody.takeBytes();
-  } on IOException catch (error) {
+  } catch (error) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/base/net.dart]: I would rather we just listed all the known possible exceptions explicitly. Several times so far we've had cases where we have a bug but we swallow all the exceptions somewhere and so miss the bug, because we end up swallowing an ArgumentError or AssertionError or whatnot.

**Comment by Hixie** [comment]
LGTM except for the one comment, though @tvolkert and @goderbauer may be better reviewers.

File: packages/flutter_tools/lib/src/base/net.dart (hunk 1 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/base/net.dart]: +1

File: packages/flutter_tools/lib/src/base/os.dart [hunk 2]
```diff
@@ -178,6 +190,16 @@ class _WindowsUtils extends OperatingSystemUtils {
     _unpackArchive(archive, targetDirectory);
   }
 
+  @override
+  bool verifyZip(File zipFile) {
+    try {
+      new ZipDecoder().decodeBytes(zipFile.readAsBytesSync(), verify: true);
+    } catch (ArchiveException) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/base/os.dart]: `on ArchiveException catch (_)`

File: packages/flutter_tools/lib/src/base/os.dart [hunk 3]
```diff
@@ -186,6 +208,16 @@ class _WindowsUtils extends OperatingSystemUtils {
     _unpackArchive(archive, targetDirectory);
   }
 
+  @override
+  bool verifyGzip(File gzipFile) {
+    try {
+      new GZipDecoder().decodeBytes(gzipFile.readAsBytesSync(), verify: true);
+    } catch (ArchiveException) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/base/os.dart]: And here

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
AppVeyor's complaining about a window's error with the filename substitutions.

**Comment by jcollins-g** [comment]
PTAL; Windows problems fixed.  I'd like to merge the tgz/zip handling between Windows and Linux to make that easier to debug but that's another PR.

**Comment by tvolkert** [comment]
LGTM
