### PR TITLE
Fix InkWell ripple visible on right click when not expected

### LINKED ISSUE #124328: [Bug Report][Desktop] Ink ripple is being displayed on right click (since Flutter 3.9.x)
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. **Right click** on the "Hello, world!" placed inside an `InkWell`.
3. The ink ripple effect is observed.
4. The right click ink ripple effect is not seen on on Flutter 3.7.x (`stable`), but it is now seen on Flutter 3.9.x (`master`).
5. The issue is not just limited to `InkWell`, but `PopupMenuButton`s, `ListTile`s, `TextButton`s etc. & more.

I use right-click event to show context menu on various surfaces.
A redundant ripple due to right-click on surface makes the operation confusing.

**Expected results:**

No ink ripple on right click.

**Actual results:**

Ink ripple on right click.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: InkWell(
            onTap: () {},
            child: Container(
              width: 128.0,
              height: 64.0,
              alignment: Alignment.center,
              child: const Text('Hello, world!'),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing Release...
No issues found! (ran in 0.6s)
```

```
[✓] Flutter (Channel master, 3.9.0-15.0.pre.1, on Microsoft Windows [Version 10.0.22621.1265], locale en-GB)
    • Flutter version 3.9.0-15.0.pre.1 on channel master at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 92857dd0e6 (2 weeks ago), 2023-03-22 05:04:15 -0400
    • Engine revision c266826b24
    • Dart version 3.0.0 (build 3.0.0-348.0.dev)
    • DevTools version 2.22.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Hitesh\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[!] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.69.2)
    • VS Code at C:\Users\Hitesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.61.20230301

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR removes the splash effect when no secondary button callbacks are defined. 

`InkWell` defines several useful callbacks related to the secondary button.
When no secondary button callbacks are defined the splash effect should not be visible.

## Implementation choice

This PR does not remove the splash effect when at least one of the secondary button callbacks is defined (this behavior was proposed in https://github.com/flutter/flutter/pull/119058#pullrequestreview-1269813844).

Maybe we should consider if showing a splash effect for the secondary button is an expected behavior (and decide to remove it or make it configurable) ? A possible use case is an InkWell which defines both primary button callbacks and secondary button callbacks, where the primary button is used to execute an action and the secondary button to show a popup menu, in this case, it might be a better UX choice to not show the splash effect for the secondary button.
@Renzo-Olivares @justinmc 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/124328

## Tests

Adds 1 test.

### CODE REVIEW

**Review by Renzo-Olivares — APPROVED** [review]
This LGTM thanks for fixing this!

In regards to not having the splash show when a pop up menu is activated by the secondary button I think I would still expect some visual indication that the button has been tapped. I don't see a reason why this should not be customizable though.

File: packages/flutter/lib/src/material/ink_well.dart [hunk 1]
```diff
@@ -1214,17 +1214,26 @@ class _InkResponseState extends State<_InkResponseStateWidget>
...
+
+  bool _secondaryButtonEnabled(_InkResponseStateWidget widget) {
+    return widget.onSecondaryTap != null
       || widget.onSecondaryTapUp != null
       || widget.onSecondaryTapDown != null;
   }
 
   bool get enabled => isWidgetEnabled(widget);
+  bool get primaryButtonEnabled => _primaryButtonEnabled(widget);
+  bool get secondaryButtonEnabled => _secondaryButtonEnabled(widget);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/ink_well.dart:1236]: What's the reason for making these public?  I'm not against it I just want to make sure we don't expose new APIs that could be private.

**Review by justinmc — APPROVED** [review]
LGTM with one question.

I'm not sure if there is anything in the spec about this, but not showing the ripple when there is no secondary handler sounds like the right thing to do to me :+1:

File: packages/flutter/lib/src/material/ink_well.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/ink_well.dart]: I think there is no good reason and that these accessors should be private, good catch!
I have updated the PR accordingly.
