### PR TITLE
Handle Cupertino back gesture interrupted by Navigator push

### LINKED ISSUE #27334: Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
## Steps to Reproduce

gif

Video: https://i.imgur.com/A85IETe.mp4

1. Install Flutter Gallery on iOS simulator
2. Open and close any sample using the swipe mechanism
3. After a few successful swipes pick up the pace of opening and closing the sample
4. Crashes

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 218 pos 12:
flutter: '!_transitionCompleter.isCompleted'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute.didPopNext (package:flutter/src/widgets/routes.dart:218:12)
flutter: #3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1944:23)
flutter: #4      _CupertinoBackGestureController._handleStatusChanged (package:flutter/src/cupertino/route.dart:651:17)
flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:192:19)
flutter: #6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:736:7)
flutter: #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:752:5)
flutter: #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
flutter: #11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
flutter: #17     _invoke1 (dart:ui/hooks.dart:203:10)
flutter: #18     _beginFrame (dart:ui/hooks.dart:156:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#f0974(⏮ 0.000; paused; DISPOSED; for
flutter:   MaterialPageRoute<dynamic>(/cupertino/alert))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1507 pos 12: '!_debugLocked': is not true.

```

```
Analyzing flutter_gallery...
No issues found! (ran in 5.6s)
```

```
[✓] Flutter (Channel master, v1.2.1-pre.50, on Mac OS X 10.14.2, locale en-US)
    • Flutter version 1.2.1-pre.50 at /Users/droidery/flutter
    • Framework revision dbd1b317ff (76 minutes ago), 2019-01-30 21:31:44 -0500
    • Engine revision 15f2b92cce
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 71bee8f05e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.2

[✓] Connected device (1 available)
    • iPhone SE • 58F34A3E-1576-453E-B1B4-3DCB22E1FEDD • ios • iOS 12.1 (simulator)
```

Might be related to https://github.com/flutter/flutter/issues/27333 but error message and reproduction steps are difference.

### LINKED ISSUE #28728: Severe navigator fail on iOS (swipe back) since newest stable upgrade
See video for demonstration:
https://youtu.be/cwzUr5-vN_M

Severe issue since the new stable upgrade (1day ago). Reproducible on any tap-able item, when simple using navigator.push to get to a new screen on iOS. Just tap on an item and swipe back via iOS gesture, then quickly tap the item again. New screen is shortly opened, then closed. Sometimes, this error message pops up:
https://github.com/flutter/flutter/issues/28058

### PR DESCRIPTION
**Pull request by HansMuller**
Previously, if a new route was pushed before the iOS "back-swipe" dismiss animation was finished then the `_CupertinoBackGestureController` would mistakenly pop the new route when the animation actually did finish. 

Fixes https://github.com/flutter/flutter/issues/28728
Fixes https://github.com/flutter/flutter/issues/27334

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/route.dart [hunk 1]
```diff
@@ -579,6 +580,7 @@ class _CupertinoBackGestureController<T> {
     @required this.navigator,
     @required this.controller,
     @required this.onEnded,
+    @required this.route,
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: since this is private, we can just make it take route (and make it impossible for future maintainers to accidentally give in disjoint instances of these 3 things).

File: packages/flutter/lib/src/widgets/routes.dart [hunk 2]
```diff
@@ -151,11 +151,11 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
           overlayEntries.first.opaque = false;
         break;
       case AnimationStatus.dismissed:
-        // We might still be the current route if a subclass is controlling the
+        // We might still be an active route if a subclass is controlling the
         // the transition and hits the dismissed status. For example, the iOS
         // back gesture drives this animation to the dismissed status before
-        // popping the navigator.
-        if (!isCurrent) {
+        // removing the route.
```
Comment (xster) [inline packages/flutter/lib/src/widgets/routes.dart]: Add that it itself is responsible for disposing the route and we don't have to do it here.

File: packages/flutter/test/cupertino/route_test.dart [hunk 3]
```diff
@@ -253,4 +254,65 @@ void main() {
...
+
+    await tester.tap(find.text('push'));
+    await tester.pumpAndSettle();
+    expect(find.text('route'), findsOneWidget);
+    expect(find.text('push'), findsNothing);
+
+    gesture = await tester.startGesture(const Offset(5, 300));
+    await gesture.moveBy(const Offset(400, 0)); // drag halfway
+    await gesture.up();
+    await tester.pump(const Duration(milliseconds: 275)); // partially dismiss "route"
```
Comment (xster) [inline packages/flutter/test/cupertino/route_test.dart]: Is this right? Looking at droppedPageForwardAnimationTime and droppedPageBackAnimationTime, it seems like it's a bit more complicated than that.

File: packages/flutter/test/cupertino/route_test.dart [hunk 4]
```diff
@@ -253,4 +254,65 @@ void main() {
...
+    expect(find.text('route'), findsOneWidget);
```
Comment (xster) [inline packages/flutter/test/cupertino/route_test.dart]: assert where 'route' and 'push' are so if someone refactors the droppedPageForwardAnimationTime/droppedPageBackAnimationTime in the future, we don't accidentally just finish running the whole animation and end up not testing anything here.

File: packages/flutter/lib/src/cupertino/route.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/cupertino/route.dart]: Good idea, done.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/routes.dart]: Done.

File: packages/flutter/test/cupertino/route_test.dart (hunk 3 above)
Comment (HansMuller) [reply packages/flutter/test/cupertino/route_test.dart]: I verified that the test is doing the right thing by watching it execute and making sure that (without the fix) it failed exactly as was reported.

File: packages/flutter/test/cupertino/route_test.dart (hunk 4 above)
Comment (HansMuller) [reply packages/flutter/test/cupertino/route_test.dart]: OK, added checks for this.

**Comment by xster** [comment]
LGTM

File: packages/flutter/test/cupertino/route_test.dart (hunk 3 above)
Comment (xster) [reply packages/flutter/test/cupertino/route_test.dart]: It's not a big deal, I just meant this animation isn't driven by MaterialPageTransition times. It's driven by https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/route.dart#L628. It still works. It's just not 75% as written above. I'll clean this up a bit in the next PR.

File: packages/flutter/lib/src/cupertino/route.dart [hunk 5]
```diff
@@ -652,14 +647,14 @@ class _CupertinoBackGestureController<T> {
     }
     _animating = false;
     if (status == AnimationStatus.dismissed)
-      navigator.pop<T>(); // this will cause the route to get disposed, which will dispose us
+      route.navigator.removeRoute(route); // this will cause the route to get disposed, which will dispose us
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: Turns out this has a subtle (untested :()problem. This will dispose the route first which means by the time the controller is disposed, the route's reference to the navigator is gone already and we can't call didStopUserGesture. Breaks a few uncommon APIs on the NavigatorObserver. I'll fix it in a next pr.

Comment (1AlexFix1) [reply packages/flutter/lib/src/cupertino/route.dart]: Of course, I don’t understand how it all works, but this change caused this problem #29596, I added
route.navigator.pop ();
instead
route.navigator.removeRoute (route);
At first glance, everything works, but what this leads to, I cannot say) you know better

Comment (xster) [reply packages/flutter/lib/src/cupertino/route.dart]: Thanks so much for digging through this @1AlexFix1, I think you're right in that this would break existing NavigatorObserver.didPop. 

@HansMuller, let's chat about this next week. Though I'm not sure what is the right solution. Since didPop() actually returns the route that was popped whereas pop() doesn't let you specify which route was popped, this API asymmetry might be the root of the issue.
