### PR TITLE
[Material] Time picker semantics updates

### LINKED ISSUE #66062: Time Picker has screen reader issues on web
After reviewing the time picker on web with a screen reader, a few issues were noticed:

- For the hour/minute controls, I hear "min 0, max 2" even though the number, e.g. an hour, is set to "7" (ChromeOS only)
- When selecting "AM" vs "PM", they are neither reported as "buttons" or as "selected" to reflect their selection state (both macOS and ChromeOS) - The [time picker code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/time_picker.dart#L561) currently marks these as "selected" but not as "buttons" so part of this is expected and a bug.
  - Note: I also noticed a lack of "selected" being spoken for other widgets such as `ToggleButtons`
- In "text input mode", text fields do not have accessibility labels

#Steps to Reproduce

1. Run the flutter gallery (or any app with the time picker) on web (both macOS and chromeOS were tested)
2. Enable screen reader
3. Observe that certain time picker elements are not read out correctly (see above for details)

**Expected results:** Correct screen reader experience

**Actual results:**  Partial screen reader experience

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.3, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (4 available)
```

### PR DESCRIPTION
**Pull request by rami-a**
## Description

Updates the semantics of the time picker based on a11y feedback and to allow for a consistent experience on web, iOS, and Android.
- AM/PM buttons to behave like radio buttons
- hour/minute controls have their hint and label combined so that web verbalizes this correctly
- Update text fields to correctly verbalize on web

## Related Issues

Closes #66062

## Tests

I added the following tests:

- Updated existing am/pm semantics test
- Updated existing hour/minute semantics tests

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by johnsonmh — APPROVED** [review]

**Review by clocksmith — APPROVED** [review]

File: packages/flutter/lib/src/material/time_picker.dart [hunk 1]
```diff
@@ -1673,8 +1674,11 @@ class _HourMinuteTextFieldState extends State<_HourMinuteTextField> {
     // If screen reader is in use, make the hint text say hours/minutes.
     // Otherwise, remove the hint text when focused because the centered cursor
     // appears odd above the hint text.
-    final String? hintText = MediaQuery.of(context)!.accessibleNavigation
-        ? widget.semanticHintText
+    //
+    // TODO(rami-a): Once https://github.com/flutter/flutter/issues/67571 is
+    // resolved, remove the window check for semantics being enabled on web.
+    final String? hintText = MediaQuery.of(context)!.accessibleNavigation || ui.window.semanticsEnabled
+    ? widget.semanticHintText
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/time_picker.dart:1681]: indentation is off here

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/time_picker.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/lib/src/material/time_picker.dart]: fixed
