### PR TITLE
fix: SelectableText should handle focus changes

### LINKED ISSUE #103725: SelectableText Widget Web & Desktop Allows Multiple Highlights
## Steps to Reproduce

1. Execute `flutter create selectableWidget` with 3.0 installed
2. Modify `main.dart` to use `SelectableText()` widgets instead of `Text()` and add an additional `SelectableText()` widget
3. Execute `flutter run` on the new selectableWidget flutter project 
2. Highlight one `SelectableText()` widget, and then highlight a different `SelectableText()` widget

**Expected results:** 
I expected after highlighting the second `SelectableText()` widget that the first one would unhighlight. This is typical web/desktop app behavior that majority of users are trained to expect.
flutter_website_test_example

**Actual results:** 
Each additional highlight does **NOT** de highlight the previous selection, meaning every individual `SelectableText()` widget can be highlighted at the same time.
flutter_selectable_text_example

It's very likely this isn't a bug and is the expected way how `SelectableText()` is intended to work. But it goes against the expected behavior of how the user interacts with text on the web or desktop applications and is pretty confusing/jarring.

As far as I know `SelectableText()` widget is the only way to allow users to highlight and copy the text in an application. If I'm incorrect and there is another way please feel free to post a solution.
<details>

<summary>Code sample</summary>
```


<!--
      Please create a minimal reproducible sample that shows the problem
      and attach it below between the lines with the backticks.

      To create it you can use `flutter create bug` command and update the `main.dart` file.

      Alternatively, you can use https://dartpad.dev/
      which is capable of creating and running small Flutter apps.

      Without this we will unlikely be able to progress on the issue, and because of that
      we regretfully will have to close it.
-->

```dart
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const SelectableText(
              'You have pushed the button this many times:',
            ),
            const SelectableText(
              'More selectable text',
            ),
            SelectableText(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
@prest ➜  version3  flutter analyze
Analyzing version3...
No issues found! (ran in 2.5s)
```

```
[✓] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.25115.1000], locale en-US)
    • Flutter version 3.0.0 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (4 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\prest\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\prest\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] VS Code (version 1.68.0-insider)
    • VS Code at C:\Users\prest\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Pixel 4 XL (mobile) • 9B071FFBA003B1 • android-arm64  • Android 12 (API 32)
    • Windows (desktop)   • windows        • windows-x64    • Microsoft Windows [Version 10.0.25115.1000]
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 101.0.1210.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### LINKED ISSUE #117573: SelectableText doesn't follow focus logic
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Select one region of text
3. select the other region of text 

**Expected results:** 

 The first region of text would be unselected

**Actual results:** 
 
Both remain selected even though unfocus is called

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late FocusNode nodeReg1;
  late FocusNode nodeReg2;

  @override
  initState() {
    nodeReg1 = FocusNode();
    nodeReg2 = FocusNode();

    nodeReg1.addListener(() {
      if (nodeReg1.hasFocus) {
        nodeReg2.unfocus();
      }
    });
    nodeReg2.addListener(() {
      if (nodeReg2.hasFocus) {
        nodeReg1.unfocus();
      }
    });

    super.initState();
  }

  @override
  void dispose() {
    nodeReg1.dispose();
    nodeReg2.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Center(
                child: SelectableText(
              "This is the first region",
              focusNode: nodeReg1,
              autofocus: true,
            )),
            Center(
                child: SelectableText(
              "This is the second region",
              focusNode: nodeReg2,
              autofocus: true,
            )),
          ],
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing flutter_min...                                                
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/user/LocalFrameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] VS Code (version 1.68.1)
    • VS Code at /Volumes/Ventura/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change updates the behavior of `SelectableText`, to clear its selection when it loses focus and the application is currently running. This fixes the behavior where you may have multiple active highlights if you have `SelectableText` along with other "selectable" widgets such as `TextField`, or `Text` widgets under a `SelectionArea`.

If the application is in the background, for example when another window is focused, the selection should be retained so when a user returns to the application it is still there.

This change also updates the behavior of selection on macOS, single tap up, previously it was selecting the word edge closest to the tapped position, the correct behavior on native is to select the precise position. This was causing `onSelectionChanged` to be called twice, once for tap down (sets the precise tapped position, handled by logic in `TextSelectionGestureDetector`), and a second time for single tap up (moves the cursor to closest word edge, handled by logic in `_SelectableTextSelectionGestureDetectorBuilder`). This type of selection inconsistency is related to this issue https://github.com/flutter/flutter/issues/129726, I plan to look into this further in a separate PR.

Fixes #117573
Fixes #103725 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 1]
```diff
@@ -620,6 +628,20 @@ class _SelectableTextState extends State<SelectableText> implements TextSelectio
...
+  void _handleFocusChanged() {
+    if (!_effectiveFocusNode.hasFocus
+        && SchedulerBinding.instance.lifecycleState == AppLifecycleState.resumed) {
+      // We should only clear the selection when this SelectableText loses
+      // focus while the application is currently running. It is possible
+      // that the application is not currently running, for example on desktop
+      // platforms, clicking on a different window switches the focus to
+      // the new window causing the Flutter application to go inactive. In this
+      // case we want to retain the selection so it remains when we return to
+      // the Flutter application.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/selectable_text.dart:640]: So @gspencergoog when the application is backgrounded, any focused FocusNode loses focus? Just making sure that's how it works and is intended.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 2]
```diff
@@ -1475,6 +1475,59 @@ void main() {
...
+    expect(controllerA.selection, TextRange.empty);
+    expect(controllerB.selection, const TextSelection.collapsed(offset: 0));
+
+    // Setting the app lifecycle state to AppLifecycleState.inactive to simulate
+    // a lose of window focus. Selection should remain the same.
+    await setAppLifecycleState(AppLifecycleState.inactive);
+    await tester.pumpAndSettle();
+    expect(controllerA.selection, TextRange.empty);
+    expect(controllerB.selection, const TextSelection.collapsed(offset: 0));
+  }, variant: TargetPlatformVariant.all());
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:1529]: Is it worth adding `.all` here instead of just omitting it? You do have a `switch` on the platform above, but maybe I think it doesn't affect this particular test.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 3]
```diff
@@ -3265,7 +3400,7 @@ void main() {
 
       expectCupertinoSelectionToolbar();
     },
-    variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS,  TargetPlatform.macOS }),
+    variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.macOS }),
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:3403]: Good catch

**Review by justinmc — APPROVED** [review]
LGTM 👍 

It seems a little weird that we have to check the lifecycle state when the focus changes, but if that's how Flutter's focus works then I guess that's what you have to do.

**Comment by justinmc** [comment]
I think you need to merge master into this branch to fix the Google test failure.

File: packages/flutter/lib/src/material/selectable_text.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/selectable_text.dart:640]: For more context on this, as of https://github.com/flutter/flutter/pull/142930, the `FocusManager` responds to app lifecycle changes.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/widgets/selectable_text_test.dart:1529]: I'm okay with either, but I usually lean towards `.all` if possible, and not platform specific, for more test coverage. What do you think?

File: packages/flutter/lib/src/material/selectable_text.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/selectable_text.dart:640]: This looks correct to me then, thanks for the context 👍
