### PR TITLE
[Impeller] ensure that OpenGL "flipped" textures do not leak via texture readback.

### LINKED ISSUE #142641: [Impeller] perform golden texture flip on the GPU
In https://github.com/flutter/engine/pull/50146 OpenGLES goldens were introduced, but the OpenGLES renderer holds textures with the Y flipped.  In order to account for this we flip the textures upside down on the CPU before writing the png files.  In theory that flipping should be able to be performed by the blit pass for better performance.

In Vulkans case the destination rect for the blit can have negative y coordinates, which should flip the texture.

### LINKED ISSUE #163315: [Impeller] GLES y axis adjustment can leak out of renderer when data is readback.
### Steps to reproduce

I was following a different [issue](https://github.com/flutter/flutter/issues/161304) with Impeller and Google Maps on PowerVR devices.
And saw it was merged into master, so I checked it out.
The map is now drawn correctly, but for some reason all my markers are flipped on the X-axis.

Sample code from: [GoogleMapsFlutter package](https://pub.dev/packages/google_maps_flutter), but with a custom maker from an Icon.
(See code sample below)

Device information which I used:

- Productname: Galaxy Tab Active3
- model: SM-T575
- Versie One UI: 5.1.1
- Android-versie: 13

### Expected results

See Video (Google Maps Marker with Impeller disabled)

Marker is drawn correctly.

### Actual results

See video (Google Maps Marker with Impeller enabled)

Marker is drawn flipped on the x-axis.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Google Maps Impeller'),
      ),
      body: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();
  final Set<Marker> _markers = <Marker>{};

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        markers: _markers,
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _createMarker,
        label: const Text('Create marker and show!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _createMarker() async {
    final markerGenerator = MarkerIconGenerator(45.0);
    final iconBitmap = await markerGenerator.createBitmapDescriptorFromIconData(
      Icons.local_shipping,
      Colors.black,
      Colors.red,
      Colors.white,
    );
    final marker = Marker(
      markerId: MarkerId('1'),
      position: LatLng(
        _kLake.target.latitude,
        _kLake.target.longitude,
      ),
      infoWindow: InfoWindow(
        title: 'The lake',
      ),
      icon: iconBitmap,
    );
    setState(() {
      _markers.clear();
      _markers.add(marker);
    });
    final GoogleMapController controller = await _controller.future;
    await controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

class MarkerIconGenerator {
  final double _markerSize;
  late double _circleStrokeWidth;
  late double _circleOffset;
  late double _outlineCircleWidth;
  late double _fillCircleWidth;
  late double _iconSize;
  late double _iconOffset;

  MarkerIconGenerator(this._markerSize) {
    // Calculate marker dimensions
    _circleStrokeWidth = _markerSize / 10.0;
    _circleOffset = _markerSize / 2;
    _outlineCircleWidth = _circleOffset - (_circleStrokeWidth / 2);
    _fillCircleWidth = _markerSize / 2;
    final outlineCircleInnerWidth = _markerSize - (2 * _circleStrokeWidth);
    _iconSize = sqrt(pow(outlineCircleInnerWidth, 2) / 2);
    final rectDiagonal = sqrt(2 * pow(_markerSize, 2));
    final circleDistanceToCorners =
        (rectDiagonal - outlineCircleInnerWidth) / 2;
    _iconOffset = sqrt(pow(circleDistanceToCorners, 2) / 2);
  }

  /// Creates a BitmapDescriptor from an IconData
  Future<BitmapDescriptor> createBitmapDescriptorFromIconData(
    IconData iconData,
    Color iconColor,
    Color circleColor,
    Color backgroundColor,
  ) async {
    final pictureRecorder = PictureRecorder();
    final canvas = Canvas(pictureRecorder);

    _paintCircleFill(canvas, backgroundColor);
    _paintCircleStroke(canvas, circleColor);
    _paintIcon(canvas, iconColor, iconData);

    final picture = pictureRecorder.endRecording();
    final image = await picture.toImage(
      _markerSize.round(),
      _markerSize.round(),
    );

    final bytes = await image.toByteData(format: ImageByteFormat.png);
    if (bytes == null) {
      return BitmapDescriptor.defaultMarker;
    }
    return BitmapDescriptor.bytes(bytes.buffer.asUint8List());
  }

  /// Paints the icon background
  void _paintCircleFill(Canvas canvas, Color color) {
    final paint = Paint()
      ..style = PaintingStyle.fill
      ..color = color;
    canvas.drawCircle(
      Offset(_circleOffset, _circleOffset),
      _fillCircleWidth,
      paint,
    );
  }

  /// Paints a circle around the icon
  void _paintCircleStroke(Canvas canvas, Color color) {
    final paint = Paint()
      ..style = PaintingStyle.stroke
      ..color = color
      ..strokeWidth = _circleStrokeWidth;
    canvas.drawCircle(
      Offset(_circleOffset, _circleOffset),
      _outlineCircleWidth,
      paint,
    );
  }

  /// Paints the icon
  void _paintIcon(Canvas canvas, Color color, IconData iconData) {
    final textPainter = TextPainter(textDirection: TextDirection.ltr);
    textPainter.text = TextSpan(
        text: String.fromCharCode(iconData.codePoint),
        style: TextStyle(
          letterSpacing: 0.0,
          fontSize: _iconSize,
          fontFamily: iconData.fontFamily,
          package: iconData.fontPackage,
          color: color,
        ));
    textPainter.layout();
    textPainter.paint(canvas, Offset(_iconOffset, _iconOffset));
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Google Maps Marker with Impeller disabled</summary>

https://github.com/user-attachments/assets/3a86b250-ee65-4e3a-851d-d85e4847ecdc

</details>

<details>
<summary>Google Maps Marker with Impeller enabled</summary>

https://github.com/user-attachments/assets/60996d19-f731-40a1-92e6-ab5a6f68096d

</details>

### Logs

<details><summary>Logs</summary>

```console
[+6746 ms] I/google_maps_bug(32165): Background concurrent copying GC freed 19MB AllocSpace bytes, 215(15MB) LOS objects, 49% free, 15MB/31MB, paused 563us,108us total 168.614ms
[   +3 ms] D/OpenGLRenderer(32165): setSurface called with nullptr
[+1362 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +23 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +19 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +7 ms] E/libEGL  (32165): call to OpenGL ES API with no current context (logged once per thread)
[  +11 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +19 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +6 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +13 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +8 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +4 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +5 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +4 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +6 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +4 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +5 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +7 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +5 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +8 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +8 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +6 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +9 ms] W/JavaCronetEngine(32165): using the fallback Cronet Engine implementation. Performance will suffer and many HTTP client features, including caching, will not work.
[   +7 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +15 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +7 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +6 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +7 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +5 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +15 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +11 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +12 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +13 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +2 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +4 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +11 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +9 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +7 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +4 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[  +12 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[   +3 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +4 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +6 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +18 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +14 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +15 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +16 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(32165): updateAcquireFence: Did not find frame.
[ +411 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[   +1 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[ +108 ms] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.
[        ] W/ProxyAndroidLoggerBackend(32165): Too many Flogger logs received before configuration. Dropping old logs.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.30.0-1.0.pre.175, on Microsoft Windows [Version 10.0.26100.3194], locale nl-BE) [5,5s]
    • Flutter version 3.30.0-1.0.pre.175 on channel master at C:\Data\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60a7716159 (9 hours ago), 2025-02-14 02:11:04 -0500
    • Engine revision 60a7716159
    • Dart version 3.8.0 (build 3.8.0-91.0.dev)
    • DevTools version 2.43.0

[√] Windows Version (11 Pro 64-bit, 24H2, 2009) [3,3s]

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2,4s]
    • Android SDK at C:\Users\Jimmy Szeles\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[√] Chrome - develop for the web [295ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4) [294ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2) [16ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[√] VS Code (version 1.97.2) [15ms]
    • VS Code at C:\Users\Jimmy Szeles\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.104.0

[√] Connected device (4 available) [410ms]
    • SM T575 (mobile)  • R52W1036EXD • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.26100.3194]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 132.0.6834.160
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 133.0.3065.59

[√] Network resources [1.640ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #163521: Screenshot & Shader Effects result in flipped output on certain android devices (v3.29.0)
### Steps to reproduce

In version 3.29.0, a screenshot or applying a shader on some Android devices results in a vertically flipped output.

#### Option 1: Screenshot
1. Use the minimal example below to capture the image with `RenderRepaintBoundary`.
2. Test it using the Android emulator “Pixel Pro 8” — the image will appear flipped.
3. Test it on another device like the “Galaxy S10” — the result will not be flipped.

#### Option 2: Shader
1. Set up a simple shader for a specific area and apply it to the `BackdropFilter`.
2. Test it using the Android emulator “Pixel Pro 8 API 35” — the image will appear flipped.
3. Test it on another device like the “Galaxy S10” — the result will not be flipped.

FYI: If you want to test option 2 without setting up the shader and related configurations, you can use my package, [pro_image_editor: ^8.3.1](https://pub.dev/packages/pro_image_editor). Simply open the paint editor, select pixelate mode, and draw an area—you'll immediately notice that the Y-axis is flipped.

### Expected results

The result should not be vertical flipped on any device.

### Actual results

The image is vertical flipped on a few devices. In my tests, this issue occurred on "Pixel Pro 8" and "Nexus 10". However, a user reported in my package [here](https://github.com/hm21/pro_image_editor/issues/361#issuecomment-2658527362) that additional devices are also affected.

>Affected devices:
Moto G54
Moto G55
Moto G Pure
Oppo F19 Pro
Galaxy Tab 7 Lite

>Non affected devices:
HTC 10
Infinix Hot 11s
Samsung A06
Xiaomi Redmi Note 13
Xiaomi Redmi Pad Pro

### Code sample

<details open><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  final _repaintKey = GlobalKey();

  Uint8List? _bytes;

  Future<ui.Image> _getDartUiImage() async {
    RenderObject? findRenderObject =
        _repaintKey.currentContext?.findRenderObject();

    RenderRepaintBoundary boundary = findRenderObject as RenderRepaintBoundary;

    return await boundary.toImage(
      pixelRatio: MediaQuery.devicePixelRatioOf(context),
    );
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Expanded(
              child: RepaintBoundary(
                key: _repaintKey,
                child: Image.network(
                  'https://picsum.photos/id/230/2000',
                ),
              ),
            ),
            Expanded(
              child: _bytes != null
                  ? Image.memory(_bytes!)
                  : const Center(
                      child: Text(
                        'Press "Capture Image"',
                        style: TextStyle(color: Colors.red),
                      ),
                    ),
            )
          ],
        ),
      ),
      persistentFooterButtons: [
        FilledButton(
          onPressed: () async {
            var image = await _getDartUiImage();
            var bytes = await image.toByteData(format: ui.ImageByteFormat.png);
            _bytes = bytes!.buffer.asUint8List();
            setState(() {});
          },
          child: const Text('Capture Image'),
        ), 
      ],
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

## Result on devices that vertically flip the output
| Capture Image | Shader |
|----------|----------|
| Test1 | Test2 |

## Expected result
| Capture Image | Shader |
|----------|----------|
| Test3 |Test4 |

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale de-CH) [1’103ms]
    • Flutter version 3.29.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (7 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[√] Windows Version (11 Home 64-bit, 24H2, 2009) [6.3s]

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [8.2s]
    • Android SDK at C:\Users\AlexF\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\AlexF\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\AlexF\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web [210ms]
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.0) [207ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33414.496
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2023.2) [44ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.3) [42ms]
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.97.2) [41ms]
    • VS Code at C:\Users\AlexF\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.104.0

[√] Connected device (4 available) [1’194ms]
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.26100.3194]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 132.0.6834.197
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 132.0.2957.127

[√] Network resources [1’547ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/163315
Fixes https://github.com/flutter/flutter/issues/163521
Fixes https://github.com/flutter/flutter/issues/142641

OpenGL has an inverted coordinate system (bottom left is zero) compared to Metal/Vulkan (top left is zero). We handle this by rendering things upside down on OpenGL. Unfortunately this can leak out of the renderer via readback (toImage), so we need to make sure to undo the inversion.

This is not performed for the "TextureCoordinateSystem::kUploadFromHost" state as that indicates the texture is already "right side up".

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc [hunk 1]
```diff
@@ -328,10 +330,29 @@ bool BlitCopyTextureToBufferCommandGLES::Encode(
...
+        switch (coord_system) {
+          case TextureCoordinateSystem::kUploadFromHost:
+            gl.ReadPixels(source_region.GetX(), source_region.GetY(),
+                          source_region.GetWidth(), source_region.GetHeight(),
+                          GL_RGBA, GL_UNSIGNED_BYTE, data + destination_offset);
+            break;
+          case TextureCoordinateSystem::kRenderToTexture:
+            // The texture is upside down, and must be inverted when copying
+            // byte data out.
+            size_t offset = destination_offset;
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:345]: I have nothing to provide as evidence for this other than perhaps an irrational fear that multiple calls to `ReadPixels` will make some driver do the most insane thing possible. But can we read in one shot and then flip the image in place after instead?

Iterate over the rows picking two from each end and `std::swap_ranges` on each perhaps.

**Review by chinmaygarde — APPROVED** [review]
A suggestion to use just one call to use ReadPixels with an inplace swap to avoid potential driver shenanigans. Perhaps its pinning memory weirdly.

OTOH, feel free to ignore. ReadPixels is slow either way.

File: engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:345]: This is a reasonable fear, but I also doubt my ability to correctly use std::swap_ranges so it might be 6 of 1 and half a dozen of another...

Comment (chinmaygarde) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:345]:
```c++
static void FlipImage(uint8_t* buffer,
                      size_t width,
                      size_t height,
                      size_t stride) {
  if (buffer == nullptr || stride == 0) {
    return;
  }

  const auto byte_width = width * stride;

  for (size_t top = 0; top < height; top++) {
    size_t bottom = height - top - 1;
    if (top >= bottom) {
      break;
    }
    auto* top_row = buffer + byte_width * top;
    auto* bottom_row = buffer + byte_width * bottom;
    std::swap_ranges(top_row, top_row + byte_width, bottom_row);
  }
}
```

Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:345]: Will update the PR to use this.

File: engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc [hunk 2]
```diff
@@ -328,10 +353,22 @@ bool BlitCopyTextureToBufferCommandGLES::Encode(
...
         gl.ReadPixels(source_region.GetX(), source_region.GetY(),
                       source_region.GetWidth(), source_region.GetHeight(),
                       GL_RGBA, GL_UNSIGNED_BYTE, data + destination_offset);
+        switch (coord_system) {
+          case TextureCoordinateSystem::kUploadFromHost:
+            break;
+          case TextureCoordinateSystem::kRenderToTexture:
+            // The texture is upside down, and must be inverted when copying
+            // byte data out.
+            FlipImage(data + destination_offset, 4, source_region.GetHeight(),
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:369]: These arguments aren't right. The stride goes last.

Comment (chinmaygarde) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:369]: Oh, lol. The order doesn't matter since its its multiplied. Anyway, not how I meant the arguments would be interpreted 🙃

Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc:369]: oops... 


But thanks to associativity it is mathematically equivalent 😆

Comment (jonahwilliams) [reply engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles.cc]: Fixed
