### PR TITLE
_DefaultTabControllerState should dispose all created TabContoller instances. [prod-leak-fix]

### LINKED ISSUE #136607: Memory Leak: _DefaultTabControllerState doesn't dispose created TabController.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`_DefaultTabControllerState` does not dispose `TabController` after creating a new one with `_copyWith`.

Test to reveal the leak:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

void main() {
  testWidgetsWithLeakTracking(
    'DefaultTabController leak',
    (WidgetTester tester) async {
      final Key key = UniqueKey();

      Widget buildTabs(List<String> tabs) {
        return MaterialApp(
          home: Scaffold(
            body: DefaultTabController(
              key: key,
              length: tabs.length,
              child: TabBar(
                tabs: tabs.map<Widget>((String tab) => Tab(text: tab)).toList(),
              ),
            ),
          ),
        );
      }

      await tester.pumpWidget(buildTabs(<String>['A']));
      await tester.pump();
      await tester.pumpWidget(buildTabs(<String>['A', 'B']));
    },
  );
}
```

<details><summary>Test output</summary>

```console
✓ DefaultTabController leak
Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
          notDisposed:
            total: 1
            objects:
              TabController:
                test: DefaultTabController leak
                identityHashCode: 694584574
          
          

package:matcher                                                  expect
expect
widget_tester.dart:458
_tearDownTestingWithLeakTracking
test_widgets.dart:82
===== asynchronous gap ===========================
dart:async                                                       _CustomZone.registerBinaryCallback
configureLeakTrackingTearDown.<fn>
test_widgets.dart:59
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.842, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.842 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision b00216b320 (4 hours ago), 2023-10-15 10:25:12 -0400
    • Engine revision f8eb68b115
    • Dart version 3.3.0 (build 3.3.0-27.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
### Description
- Fixes https://github.com/flutter/flutter/issues/136607

### Tests
- Updates `material/tabs_test.dart` to use `testWidgetsWithLeakTracking`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by ksokolovskyi** [comment]
cc @polina-c

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 1]
```diff
@@ -142,6 +145,10 @@ class TabController extends ChangeNotifier {
   ///
   /// When [DefaultTabController.length] is updated, this method is called to
   /// create a new [TabController] without creating a new [AnimationController].
+  ///
+  /// This instance of [TabController] must not be used anymore and has to be
+  /// disposed since [AnimationController] was injected into the new
+  /// [TabController].
```
Comment (polina-c) [inline packages/flutter/lib/src/material/tab_controller.dart:151]: Is this true? May be it is up to invoker if the instance can be used or not?

Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/tab_controller.dart:151]: To be honest, usage of the `TabController` after the removal of `AnimationController` from it (after the call of `_copyWith`)  is impossible because we have several “bang operators” which will throw:
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/material/tab_controller.dart#L152
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/material/tab_controller.dart#L200
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/material/tab_controller.dart#L210
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/material/tab_controller.dart#L263
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/material/tab_controller.dart#L270

File: packages/flutter/lib/src/material/tab_controller.dart [hunk 2]
```diff
@@ -485,21 +494,25 @@ class _DefaultTabControllerState extends State<DefaultTabController> with Single
...
-      _controller = _controller._copyWith(
+      final TabController newController = _controller._copyWith(
         length: widget.length,
         animationDuration: widget.animationDuration,
         index: newIndex,
         previousIndex: previousIndex,
       );
+      _controller.dispose();
+      _controller = newController;
     }
```
Comment (polina-c) [inline packages/flutter/lib/src/material/tab_controller.dart:506]: How about making it more readable:
```
TabController newController = _controller;

if (oldWidget.length != widget.length) {
  newController = newController._copyWith...
}

if (oldWidget.animationDuration != widget.animationDuration) {
  newController = newController._copyWith...
}

if (newController != _controller) {
  _controller.dispose();
  _controller = newController;
  _animationController = null;
}

```

Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/tab_controller.dart:506]: @polina-c, thanks a lot for your suggestion, it looks much cleaner. But if we do it in such a way, then we will lose the reference to the first new `TabController` if the `length` and `animationDuration` are changed at the same time.

Comment (polina-c) [reply packages/flutter/lib/src/material/tab_controller.dart:506]: Really? Both `_copyWith` are invoked for `newController`, not for `_controller`. so, nothing is lost.

Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/tab_controller.dart:506]: Maybe I am missing something, but here is how I see the flow in case both `length` and `animationDuration` was updated:

```dart
// newController = TabController0
TabController newController = _controller;

if (oldWidget.length != widget.length) {
  // newController = TabController1
  newController = newController._copyWith...
}

if (oldWidget.animationDuration != widget.animationDuration) {
  // newController = TabController2
  newController = newController._copyWith...
}

if (newController != _controller) {
  _controller._animationController = null;
  // TabController0.dispose()
  _controller.dispose();
  // _controller = TabController2
  _controller = newController;

 // TabController1 is lost
}
```

Comment (polina-c) [reply packages/flutter/lib/src/material/tab_controller.dart:506]: Oh, I see now.
You are right.
Thanks for explanation.

Then the only question is about `_animationController = null;`:
1. Why we need it? Old controller is not referenced and is disposed, so what's the point to null _animationController?
2. If it is needed, (1) it does not seem `_copyWith` is right method to do it and (2) there should be comment that explains why it is needed.

Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/tab_controller.dart:506]: Thanks for the review.

Under the hood, `_copyWith` transfers `AnimationController` from one `TabController` to another. 
```dart
  /// Creates a new [TabController] with `index`, `previousIndex`, `length`, and
  /// `animationDuration` if they are non-null.
  ///
  /// This method is used by [DefaultTabController].
  ///
  /// When [DefaultTabController.length] is updated, this method is called to
  /// create a new [TabController] without creating a new [AnimationController].
  TabController _copyWith({
  ...
  }) {
   ...
    return TabController._(
      ...
      animationController: _animationController,
      ....
    );
  }
```

In `dispose` method of the `TabController` we have disposal of the `AnimationController`. 

```dart
  @override
  void dispose() {
    _animationController?.dispose();
    _animationController = null;
    super.dispose();
  }
```

We can't hold the same `AnimationController` in both `TabController`s because it will cause double disposal in the future. So, to not dispose recently injected `AnimationController` in the old `TabController`, we need to null it. It will be disposed in the new `TabController` in the future.

This explains why I added nulling of the `_animationController` in the `_copyWith` method and added this comment:
```  
  /// This instance of [TabController] must not be used anymore and has to be
  /// disposed since [AnimationController] was injected into the new
  /// [TabController].
```

What can you suggest to improve or change?

Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/tab_controller.dart:512]: Great suggestion, thanks!
Pushed the new version.

**Review by polina-c — APPROVED** [review]
