### PR TITLE
Keep the selection after 'Copy' pressed on iOS.

### LINKED ISSUE #72124: Missing selection area of the text after copy text in Flutter on IOS
## Steps to Reproduce
1. Select text or Select all text (only on IOS)
2. Copy text
3. The selection of text is missing but on the native IOS apps selection is remain.

CupertinoTextField also not working as IOS component.

Video with the problem https://drive.google.com/file/d/1JWJ_xsYNQPgBpbEynoPTPW5YekrUGQha/view?usp=sharing

### PR DESCRIPTION
**Pull request by justinmc**
Previously, Flutter hid the toolbar and collapsed the selection after "Copy" was pressed in the text selection toolbar.  On native iOS though, the handles should stay visible and the selection should remain.

https://user-images.githubusercontent.com/389558/108416129-23f97d00-71e3-11eb-8828-d4ce833aa549.mov

Fixes https://github.com/flutter/flutter/issues/72124

### CODE REVIEW

File: packages/flutter/lib/src/services/text_input.dart [hunk 1]
```diff
@@ -774,7 +774,7 @@ abstract class TextSelectionDelegate {
   set textEditingValue(TextEditingValue value);
 
   /// Hides the text selection toolbar.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/services/text_input.dart:776]: nit: documentation of the optional parameter.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 2]
```diff
@@ -309,6 +310,19 @@ class CupertinoTextSelectionControls extends TextSelectionControls {
...
+  void handleCopy(TextSelectionDelegate delegate, ClipboardStatusNotifier? clipboardStatus) {
+    final TextEditingValue value = delegate.textEditingValue;
+    Clipboard.setData(ClipboardData(
+      text: value.selection.textInside(value.text),
+    ));
+    clipboardStatus?.update();
+    delegate.bringIntoView(delegate.textEditingValue.selection.extent);
+    // Hide the toolbar, but maintain the existing selection and keep the
+    // handles on the screen.
+    delegate.hideToolbar(true);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection.dart:324]: I think ideally this should depend on what platform it is, since the material "copy" should have the same behavior on iOS.

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart]: That's a good point.  I can get rid of this handleCopy override entirely then, and just put the switch statement in the main handleCopy for all platforms.

File: packages/flutter/lib/src/services/text_input.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/services/text_input.dart:776]: Good call, I think this was a bit confusing overall.  I added a bunch of comments to make this more clear, and I renamed the parameter from handlesOnly to hideHandles.
