### PR TITLE
CupertinoTabScaffold crash fix

### LINKED ISSUE #33455: CupertinoTabScaffold crashes when I add more tabs to it and switch to the last tab
#### Expected: the below test should pass
```dart
      final List<int> tabsPainted = <int>[];
      final CupertinoTabController controller = CupertinoTabController(initialIndex: 0);

      await tester.pumpWidget(
        CupertinoApp(
          home: CupertinoTabScaffold(
            tabBar: CupertinoTabBar(
              items: List<BottomNavigationBarItem>.generate(10, tabGenerator),
            ),
            controller: controller,
            tabBuilder: (BuildContext context, int index) {
              return CustomPaint(
                child: Text('Page ${index + 1}'),
                painter: TestCallbackPainter(
                  onPaint: () { tabsPainted.add(index); }
                ),
              );
            }
          ),
        )
      );

      expect(tabsPainted, <int> [0]);

      await tester.pumpWidget(
        CupertinoApp(
          home: CupertinoTabScaffold(
            tabBar: CupertinoTabBar(
              items: List<BottomNavigationBarItem>.generate(20, tabGenerator),
            ),
            controller: controller,
            tabBuilder:
            (BuildContext context, int index) {
              return CustomPaint(
                child: Text('Page ${index + 1}'),
                painter: TestCallbackPainter(
                  onPaint: () { tabsPainted.add(index); }
                ),
              );
            }
          ),
        )
      );

      expect(tabsPainted, <int> [0, 0]);

      await tester.tap(find.text('Tab 19'));
      await tester.pump();

      // Tapping the tabs should still work.
      expect(tabsPainted, <int>[0, 0, 18]);
```
#### Actual: throws a RangeError

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

- Fix index out of range
- Advise against changing tabs in the docs

## Related Issues

Fixes #33455

## Tests

I added the following tests:

- Adding a new tab does not crash the app

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 1]
```diff
@@ -533,6 +533,62 @@ void main() {
     expect(find.text('Page 4', skipOffstage: false), findsNothing);
   });
 
+  // Regression test for #33455
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: Please use https://github.com/flutter/flutter/issues/33455

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 2]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+              painter: TestCallbackPainter(
+                onPaint: () { tabsPainted.add(index); }
+              ),
+            );
+          }
+        ),
+      )
+    );
+
+    expect(tabsPainted, <int> [0]);
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: `const <int>[0]` here and below

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 3]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+    // Increase the num of tabs to 20.
+    await tester.pumpWidget(
+      CupertinoApp(
+        home: CupertinoTabScaffold(
+          tabBar: CupertinoTabBar(
+            items: List<BottomNavigationBarItem>.generate(20, tabGenerator),
+          ),
+          controller: controller,
+          tabBuilder:
+          (BuildContext context, int index) {
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: The parameter list and opening brace can go on the previous line (same as earlier)

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 4]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+            return CustomPaint(
+              child: Text('Page ${index + 1}'),
+              painter: TestCallbackPainter(
+                onPaint: () { tabsPainted.add(index); }
+              ),
+            );
+          }
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: add a trailing comma

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 5]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+          ),
+          controller: controller,
+          tabBuilder: (BuildContext context, int index) {
+            return CustomPaint(
+              child: Text('Page ${index + 1}'),
+              painter: TestCallbackPainter(
+                onPaint: () { tabsPainted.add(index); }
+              ),
+            );
+          }
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: add a trailing comma

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 6]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+          (BuildContext context, int index) {
+            return CustomPaint(
+              child: Text('Page ${index + 1}'),
+              painter: TestCallbackPainter(
+                onPaint: () { tabsPainted.add(index); }
+              ),
+            );
+          }
+        ),
+      )
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: trailing comma

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 7]
```diff
@@ -533,6 +533,62 @@ void main() {
...
+          tabBuilder: (BuildContext context, int index) {
+            return CustomPaint(
+              child: Text('Page ${index + 1}'),
+              painter: TestCallbackPainter(
+                onPaint: () { tabsPainted.add(index); }
+              ),
+            );
+          }
+        ),
+      )
```
Comment (HansMuller) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: trailing comma

**Review by HansMuller — APPROVED** [review]
LGTM
