### PR TITLE
Include metadata in GitHub crash template

### LINKED ISSUE #52981: Include metadata channel, version, project type in tool crash GitHub template
Parse project `.metadata` and include in crash GitHub template.  Framework revision will be particularly interesting for debugging project migration failures.

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Add .metadata type/creation channel/creation version to GitHub crash template.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/52981

## Tests

github_template_test
flutter_project_metadata_test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Comment by jmagman** [comment]
@zanderso most of this is moving context stuff to globals and constructor dependency injection for tests.  I can split into two PRs if you prefer.

File: packages/flutter_tools/lib/src/flutter_project_metadata.dart [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+  /// ephemeral .ios and .android directories that can be updated automatically.
+  module,
+  /// This is a Flutter Dart package project. It doesn't have any native
+  /// components, only Dart.
+  package,
+  /// This is a native plugin project.
+  plugin,
+}
+
+extension FlutterProjectTypeExtension on FlutterProjectType {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/flutter_project_metadata.dart]: Oh, fancy!

File: packages/flutter_tools/test/general.shard/github_template_test.dart [hunk 2]
```diff
@@ -46,27 +57,34 @@ void main() {
...
       const String exception = 'failing to succeed!!!';
       const String doctorText = ' [✓] Flutter (Channel report';
-      FileSystem fs;
 
       setUp(() async {
         stackTrace = StackTrace.fromString('trace');
-        fs = MemoryFileSystem();
       });
 
       testUsingContext('shortened', () async {
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/github_template_test.dart]: Can these be changed to `testWithoutContext`?

File: packages/flutter_tools/lib/src/flutter_project_metadata.dart [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+
+  String get versionChannel => _versionValue('channel');
+  String get versionRevision => _versionValue('revision');
+
+  FlutterProjectType get projectType {
+    final dynamic projectTypeYaml = _metadataValue('project_type');
+    if (projectTypeYaml is String) {
+      return stringToProjectType(projectTypeYaml);
+    } else {
+      _logger.printTrace('.metadata project_type version is malformed.');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/flutter_project_metadata.dart]: These used to be `throwToolExit`, what will happen now?

File: packages/flutter_tools/test/general.shard/github_template_test.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/github_template_test.dart]: Unfortunately no, building the `FlutterProject` and manifest parsing is still rife with `context`s.

File: packages/flutter_tools/lib/src/flutter_project_metadata.dart (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: Recreating the project with missing metadata won't work. create_tests that fail:
- `Will create an app project if non-empty non-project directory exists without .metadata`
- `cannot create a project if non-empty non-project directory exists with .metadata` will throw the wrong toolExit.

Comment (zanderso) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: What will happen if someone corrupts their .metadata file? Will the tool throw a ToolExit or send a report to crash logging?

Comment (jmagman) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: Let me move the throws back into the create command.  We don't want it to throw when it's generating a crash report.

Comment (jmagman) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: #### Before this change getting the project type
If the .metadata is present but not a Yaml map:
- throws "pubspec.yaml is malformed." (yes, pubspec, not metadata).

If project_type isn't a String:
- throws ".metadata is malformed."

#### After this change
If .metadata is malformed, either not a Yaml map or project_type isn't a String:
   - Checks for the presence of directories to tell only if it's an app.  If it's an app, carry on with template reconstruction
   - If those directories are missing, throw "'Sorry, unable to detect the type of project to recreate. Try creating a fresh project and migrating your existing code to the new project manually."

I think the second behavior is actually better:
1. It doesn't have the misleading "pubspec" message
2. ".metadata is malformed" is a pretty lame message and doesn't tell the user what to do.
3. If it can figure out the project type, it does.
4. If it can't, it gives an actually useful recovery message.

What do you think?

Comment (zanderso) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: That sounds good to me.

Comment (zanderso) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: Is the "Sorry, unable to detect..." error message in this PR, or is it pre-existing?

Comment (jmagman) [reply packages/flutter_tools/lib/src/flutter_project_metadata.dart]: Sorry should have noted, it's pre-existing.
https://github.com/flutter/flutter/blob/685e9d1e47d80bd3bd22d97e1774fa264930434c/packages/flutter_tools/lib/src/commands/create.dart#L294

Updated:
#### Before this change getting the project type
If the .metadata is present but not a Yaml map:
- throws "pubspec.yaml is malformed." (yes, pubspec, not metadata).

If project_type isn't a String:
- throws ".metadata is malformed."

If the .metadata isn't present and the directories don't indicate it's an app:
- throw "'Sorry, unable to detect the type of project to recreate. Try creating a fresh project and migrating your existing code to the new project manually."

**Review by zanderso — APPROVED** [review]
