### PR TITLE
Text should still be centered when search bar height is less than 48

### LINKED ISSUE #127092: SearchBar does not align text vertically
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a SearchBar widget
2. Make its height 40 points, which is less than the default (via `constraints: const BoxConstraints(minHeight: 40, maxHeight: 40)`)

### Expected results

Nicely looking search field with everything centered vertically.

Screenshots from my actual application:

This is how it looks with the default height of 56, which is what I would expect:
image

### Actual results

image

Note how the icon is positioned correctly. It's just the text.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SearchBar Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
            flexibleSpace: const SearchBar(
          leading: Icon(Icons.search, size: 20),
          hintText: 'Search',
          constraints: BoxConstraints(minHeight: 40, maxHeight: 40),
        )),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2965], locale en-AT)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.26)
[!] Android Studio (not installed)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #127092

This fix can solve the alignment issue in `SearchBar` but we still need to investigate the root cause for the `TextField`. The 
text baseline of `TextField` doesn't change when the height is less than 48 and greater than 40. The problem should be related to the `minContainerHeight` which is 48 by default but the `contentHeight` has become smaller than this min value already. Setting `isDense`/`isCollapsed` to true gives the `minContainerHeight` a smaller number which is 0.0: https://github.com/flutter/flutter/blob/ff33555b239de4c17e7149db17eb70bcf5dee215/packages/flutter/lib/src/material/input_decorator.dart#L1086

Since [`isDense`](https://github.com/flutter/flutter/blob/ff33555b239de4c17e7149db17eb70bcf5dee215/packages/flutter/lib/src/material/input_decorator.dart#L3907) is used for the case where the text field has less vertical space, I just use this property in SearchBar.

https://github.com/flutter/flutter/assets/36861262/6ddc8e90-1b47-4dd5-9a57-59b86cafec6d

This is a demo to show the text baseline that doesn't change when we set the text field height under 48.
https://github.com/flutter/flutter/assets/36861262/ce2ee815-f1f5-493a-930e-0540a627bec8

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 1]
```diff
@@ -1248,7 +1248,11 @@ class _SearchBarState extends State<SearchBar> {
                           enabledBorder: InputBorder.none,
                           border: InputBorder.none,
                           focusedBorder: InputBorder.none,
-                          contentPadding: const EdgeInsets.symmetric(vertical: 12.0),
+                          contentPadding: EdgeInsets.zero,
+
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/search_anchor.dart:1252]:
```suggestion
```

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 2]
```diff
@@ -1248,7 +1248,11 @@ class _SearchBarState extends State<SearchBar> {
...
+                          // Setting `isDense` to true to allow the text field height to be
+                          // smaller than 48.0
+                          isDense: true,
```
Comment (justinmc) [inline packages/flutter/lib/src/material/search_anchor.dart:1255]: Does setting isDense to true affect anything else that you don't want it to affect?  I think you might also be able to get the same effect by setting `expands` to true instead.  Maybe that will create other problems though haha.  Whatever works is fine.

File: packages/flutter/test/material/search_anchor_test.dart [hunk 3]
```diff
@@ -708,6 +708,29 @@ void main() {
     expect(helperText.style?.color, focusedColor);
   });
 
+  // regression test for https://github.com/flutter/flutter/issues/127092.
```
Comment (justinmc) [inline packages/flutter/test/material/search_anchor_test.dart:711]: Nit: Capital R at the start here.

**Review by TahaTesser — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

I gave another possible option for working around this, but it should be fine either way.

**Review by HansMuller — APPROVED** [review]
Clever workaround! LGTM

File: packages/flutter/lib/src/material/search_anchor.dart (hunk 2 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/search_anchor.dart:1255]: Because currently the `TextField` in `SearchBar` is only allowed to have input text and hint text, it doesn't have any other properties like perfix/prefixIcon/suffix/label/..., so I think using `isDense` should be safe:).
