### PR TITLE
Fix: Update DelegatedTransition animation parameter correctly

### LINKED ISSUE #163389: showModalBottomSheet partially disappears after pushing new route while using FadeForwardsPageTransitionsBuilder
### Steps to reproduce

1. Show a bottom sheet using `showModalBottomSheet()`.
2. While the sheet is open, push a new route (tested using `go_router`): `await context.push('myRoute');`
3. As page transition begins you can see the bottom sheet disappear, but the overlay behind it remains.
4. After popping the route back to the screen with the bottom sheet, only the tinted overlay is visible. On iOS there is no way to escape this. On Android, pressing the device back button causes the bottom sheet to momentarily appear before closing.
5. Using the previous `ZoomPageTransitionsBuilder`, the navigation works as expected.

Reproduced on Android emulator API 35, SM-G981V, iPhone 11.

### Expected results

The bottom sheet should not partially disappear, but remain visible while the route is pushing, and be visible when the pushed route pops.

### Actual results

The bottom sheet partially disappears, leaving the overlay behind.

### Code sample

https://github.com/jt274/modal_page_transition_issue

<details open><summary>Code sample</summary>

```dart
showModalBottomSheet<void>(
    context: context,
    builder: (BuildContext context) {
      return CupertinoButton(onPressed: () async {
          await context.push('myRoute');
      },
    child: const Text('Tap Me'));
});
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3037], locale en-US)
[√] Windows Version (11 Pro 64-bit, 24H2, 2009)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.10.0)
[√] Android Studio (version 2024.3)
[√] VS Code (version 1.96.4)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Update DelegatedTransition animation parameter correctly
fixes: #163389 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by MitchellGoodwin — COMMENTED** [review]
Thank you for the fix. Code LGTM. This will need a regression test though. You can probably just wrap a widget with `FadeForwardsPageTransitionsBuilder.delegatedTransition` and supply a secondary animation, then ensure it is reacting to changes to that animation.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the fix.

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 1]
```diff
@@ -229,6 +229,98 @@ void main() {
...
+            },
+          ),
+        );
+
+        final RenderAnimatedOpacity? renderOpacity =
+            tester
+                .element(find.byType(SizedBox))
+                .findAncestorRenderObjectOfType<RenderAnimatedOpacity>();
+
+        // Since secondary animation is forward, transition will be reverse between duration 0 to 0.25
```
Comment (justinmc) [inline packages/flutter/test/material/page_transitions_theme_test.dart:266]: Nit: Period at the end.

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 2]
```diff
@@ -229,6 +229,98 @@ void main() {
...
+            },
+          ),
+        );
+
+        final RenderAnimatedOpacity? renderOpacity =
+            tester
+                .element(find.byType(SizedBox))
+                .findAncestorRenderObjectOfType<RenderAnimatedOpacity>();
+
+        // Since secondary animation is reverse, transition will be forward between duration 0.75 to 1.0
```
Comment (justinmc) [inline packages/flutter/test/material/page_transitions_theme_test.dart:311]: Same missing period here.

**Review by justinmc — APPROVED** [review]
LGTM 👍. Good catch. Thanks for your PRs recently.

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 3]
```diff
@@ -229,6 +229,98 @@ void main() {
...
+            },
+          ),
+        );
+
+        final RenderAnimatedOpacity? renderOpacity =
+            tester
+                .element(find.byType(SizedBox))
+                .findAncestorRenderObjectOfType<RenderAnimatedOpacity>();
+
+        // Since secondary animation is reverse, transition will be forward between duration 0.75 to 1.0 .
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/page_transitions_theme_test.dart:311]:
```suggestion
        // Since secondary animation is reverse, transition will be forward between duration 0.75 to 1.0.
```

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 4]
```diff
@@ -229,6 +229,98 @@ void main() {
...
+            },
+          ),
+        );
+
+        final RenderAnimatedOpacity? renderOpacity =
+            tester
+                .element(find.byType(SizedBox))
+                .findAncestorRenderObjectOfType<RenderAnimatedOpacity>();
+
+        // Since secondary animation is forward, transition will be reverse between duration 0 to 0.25 .
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/page_transitions_theme_test.dart:266]:
```suggestion
        // Since secondary animation is forward, transition will be reverse between duration 0 to 0.25.
```
