### PR TITLE
`NestedScrollView`'s outer scrollable jumping with `BouncingScrollPhysics` due to `double` precision errors

### LINKED ISSUE #136199: NestedScrollView scrolls inner view without scrolling outer view
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Example reproduction for Android:

1. Start with the code from the [first NestedScrollView example](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html).
2. Set the physics of both the NestedScrollView and the nested CustomScrollView to BouncingScrollPhysics() (not necessary on iOS where it is the default).
3. Drag the finger down on the screen, holding, then flick it up. The bug does not get triggered every time, it takes some tries.

### Expected results

When flicking up the inner scroll content should first scroll back to it's zero scroll position, then the outer scroll view should scroll to its maximum scroll position before the inner scroll view starts scrolling.

### Actual results

The inner scroll view is scrolled without the outer scroll view getting scrolled. When I then subsequently scroll a little further down the outer scroll view gets scrolled and then the inner scroll view continues scrolling.

### Code sample

Note the code sample could potentially me more minimal but I preferred to start from the example code and make the minimal changes necessary to reproduce.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [NestedScrollView].

void main() => runApp(const NestedScrollViewExampleApp());

class NestedScrollViewExampleApp extends StatelessWidget {
  const NestedScrollViewExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: NestedScrollViewExample(),
    );
  }
}

class NestedScrollViewExample extends StatelessWidget {
  const NestedScrollViewExample({super.key});

  @override
  Widget build(BuildContext context) {
    final List<String> tabs = <String>['Tab 1', 'Tab 2'];
    return DefaultTabController(
      length: tabs.length, // This is the number of tabs.
      child: Scaffold(
        body: NestedScrollView(
          physics: const BouncingScrollPhysics(),
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            // These are the slivers that show up in the "outer" scroll view.
            return <Widget>[
              SliverOverlapAbsorber(
                // This widget takes the overlapping behavior of the SliverAppBar,
                // and redirects it to the SliverOverlapInjector below. If it is
                // missing, then it is possible for the nested "inner" scroll view
                // below to end up under the SliverAppBar even when the inner
                // scroll view thinks it has not been scrolled.
                // This is not necessary if the "headerSliverBuilder" only builds
                // widgets that do not overlap the next sliver.
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title:
                      const Text('Books'), // This is the title in the app bar.
                  pinned: true,
                  expandedHeight: 150.0,
                  // The "forceElevated" property causes the SliverAppBar to show
                  // a shadow. The "innerBoxIsScrolled" parameter is true when the
                  // inner scroll view is scrolled beyond its "zero" point, i.e.
                  // when it appears to be scrolled below the SliverAppBar.
                  // Without this, there are cases where the shadow would appear
                  // or not appear inappropriately, because the SliverAppBar is
                  // not actually aware of the precise position of the inner
                  // scroll views.
                  forceElevated: innerBoxIsScrolled,
                  bottom: TabBar(
                    // These are the widgets to put in each tab in the tab bar.
                    tabs: tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            // These are the contents of the tab views, below the tabs.
            children: tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Builder(
                  // This Builder is needed to provide a BuildContext that is
                  // "inside" the NestedScrollView, so that
                  // sliverOverlapAbsorberHandleFor() can find the
                  // NestedScrollView.
                  builder: (BuildContext context) {
                    return CustomScrollView(
                      physics: const BouncingScrollPhysics(),
                      // The "controller" and "primary" members should be left
                      // unset, so that the NestedScrollView can control this
                      // inner scroll view.
                      // If the "controller" property is set, then this scroll
                      // view will not be associated with the NestedScrollView.
                      // The PageStorageKey should be unique to this ScrollView;
                      // it allows the list to remember its scroll position when
                      // the tab view is not on the screen.
                      key: PageStorageKey<String>(name),
                      slivers: <Widget>[
                        SliverOverlapInjector(
                          // This is the flip side of the SliverOverlapAbsorber
                          // above.
                          handle:
                              NestedScrollView.sliverOverlapAbsorberHandleFor(
                                  context),
                        ),
                        SliverPadding(
                          padding: const EdgeInsets.all(8.0),
                          // In this example, the inner scroll view has
                          // fixed-height list items, hence the use of
                          // SliverFixedExtentList. However, one could use any
                          // sliver widget here, e.g. SliverList or SliverGrid.
                          sliver: SliverFixedExtentList(
                            // The items in this example are fixed to 48 pixels
                            // high. This matches the Material Design spec for
                            // ListTile widgets.
                            itemExtent: 48.0,
                            delegate: SliverChildBuilderDelegate(
                              (BuildContext context, int index) {
                                // This builder is called for each child.
                                // In this example, we just number each list item.
                                return ListTile(
                                  tileColor: Colors.blue.shade100,
                                  title: Text('Item $index'),
                                );
                              },
                              // The childCount of the SliverChildBuilderDelegate
                              // specifies how many children this inner list
                              // has. In this example, each tab has a list of
                              // exactly 30 items, but this is arbitrary.
                              childCount: 30,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/3683599/18620c03-6110-4a33-8a9c-72c0b68f0285

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-AU)
    • Flutter version 3.13.6 on channel stable at /Users/rorystephenson/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (13 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rorystephenson/sdk/android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/rorystephenson/sdk/android
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • ONEPLUS A6000 (mobile)  • 2ed743fb                             • android-arm64  • Android 11 (API 30)
    • iPhone 15 Plus (mobile) • D3649EE4-B818-4DA5-A5BB-DA903E38636C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Michal-MK**
This PR fixes scrolling issues with `NestedScrollView` using the `BouncingScrollPhysics`. In one of the steps of the calculation, we can reach a state where the position of the inner scrollable is set to a `double` value that falls within `precisionErrorTolerance` of `0` but we were using `==` with `0` rather than checking for a precision. My posts in the linked issue show the current behavior, and how I reached to conclusion (the code in this PR). This PR only addresses the "jumping" of the outer scrollable.  

Fixes #136199

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

I have not finished a test for this since I have never done so and therefore have 0 experience writing tests in Flutter, so any help there would be appreciated. I am also not sure how to test double precision errors in general. I did run all the nested_scroll_view_tests.dart locally and there are no failures.

### CODE REVIEW

**Comment by goderbauer** [comment]
@Michal-MK thanks for the contribution. Looks like this PR is failing some checks. Can you please take a look and fix those up? Thanks!

**Comment by Michal-MK** [comment]
@goderbauer I can decode the Linux Analyze check, which is clear to me, I have a TODO in tests, but the issue is I do not know how to write tests for this fix. For the other 6 failing checks I have no idea what the output is trying to tell me. I looked at the "undestading a LUCI build failure", but that to me appears to describe something else.

```
â��05:52:02â�� Test failed.
â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��â��
For your convenience, the error messages reported above are repeated here:
  ð���  ð���  
```

**Comment by Michal-MK** [comment]
Apart from tree-status all tests should pass, I'll wait and see if a test for this will be needed/asked for.

**Review by Piinks — COMMENTED** [review]
Thanks for the contribution @Michal-MK!
This will need a test to verify it works as expected, and to prevent us from accidentally undoing this in the future. :)

**Comment by Michal-MK** [comment]
Okay so I tried something, the issue is that I do not fully understand the test as I just while(true)'d until a set of inputs caused the `if` to be hit with the faulty values. Then I searched for a place where the wrong value would appear, and it appeared in the outer scrollable's controller.

I replaced another `== 0` check that may render the first one obsolete, and added a test that will fail if the outer scroll controller's listener is called. Since that is the place I found manifests the precision error to the user.

image

This is the output before the fix.
After the fix it does not trigger the outer controller's callback:

image

All other tests in NestedScrollView pass.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 1]
```diff
@@ -212,6 +212,65 @@ void main() {
     expect(context.clipBehavior, equals(Clip.antiAlias));
   });
 
+  testWidgets('NestedScrollView always scrolls outer scrollable first, (double precision errors, #136199)', (WidgetTester tester) async {
+    final Key innerKey = UniqueKey();
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:216]:
```suggestion
  testWidgetsWithLeakTracking('NestedScrollView always scrolls outer scrollable first', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/136199
    final Key innerKey = UniqueKey();
```

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 2]
```diff
@@ -212,6 +212,65 @@ void main() {
...
+            ),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(build());
+
+    outerController.addListener(() {
+      assert(false); // We do not want this to be called.
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:266]: Why? The outer should scroll before the inner, why would the outer not scroll?

**Review by Piinks — COMMENTED** [review]
Hey @Michal-MK welcome. Thanks for contributing!

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 2 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:266]: The way I understand the test is that we have:
`tester.drag(find.byKey(innerKey), const Offset(0, 2000));`

Which means dragging the finger down the screen (I believe). So we are immediately overscrolling and triggering the dampening effect of the spring. The total height is 300 + 64 + 800 from the individual components. 1164 < 2000. So we have technically 836 units to work with.

`tester.fling(find.byKey(innerKey), const Offset(0, -600), 2000);`

After that we immediately fling the finger up the screen. My understanding is that the total distance will be 600 units up and the 2000 just affects how quickly the 600 will happen.

Which equals 836 - 600 = 236. So we still have 236 units to spare before the outer scrollable should start scrolling. What does not fly is the spring does not actually "stretch" to 836 visually, but I have no idea how that is implemented. If this description makes sense I will add it to the test itself, but there is a possibility it is nonsense and I just do not understand what I wrote ;).

Comment (Piinks) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:267]: Hmm, it may be easier to understand if you add checks on what the actual position is before and after each gesture. What is the value of position.pixels for the outer and inner each time? For the nested scroll view in general, the inner should not scroll before the outer has fully scrolled to its end.

If we are dragging down first, overscrolling the outer, then flinging up, I would expect the outer to consume some of the distance flinging up before the inner receives any.

**Review by Piinks — COMMENTED** [review]
@Michal-MK thanks for the update. It looks like there are a lot of failing tests currently, can you take a look?

**Comment by Michal-MK** [comment]
Tests are failing randomly, as noted here: https://github.com/flutter/flutter/pull/138319#issuecomment-1813239714. No idea how to decode the output. I just merged current master into it and it worked again. That was the case even before I added my test so i do not know what is causing it.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:267]: > the outer is not being overscrolled

Ah right I see. The inner is using bouncing scroll physics. Yup. So the inner overscrolls at the top, but then when the test flings the inner up, I expect the outer to consume some of the distance before the inner does.

> Since we are not supposed to assign a scroll controller to the inner scrollview I do not have output from that.

The inner scroll controller is accessible through the inner key you have created in the test.

Can you add checks that validate the inner and outer positions at each step to the test?

Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:274]: Alright, I added more asserts to the test, I did not find a way to obtain the controller from the previous setup so I just borrowed someone else's solution :). The outer scrollable does not move, it may be surprising but it's true (according to the `expect()` and the `.addListener()`)

**Comment by Michal-MK** [comment]
So it seems that Linux web_canvaskit_tests_4 and Linux web_tests_0 are now failing consistently, but their output is still illegible: â��â��â��â��â��â��â��â��â�

**Comment by Michal-MK** [comment]
After spending more time with it I did find the tiny "show more details" button. There I finally got the actual output. Hmm why is GitHub's so broken then...? I modified the test to hopefully pass the two failing cases.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 3]
```diff
@@ -212,6 +212,110 @@ void main() {
...
+    expect(outer.offset, 0.0);
+    expect(inner.offset, 0.0);
+
+    outerController.addListener(() {
+      fail('Outer controller should not be scrolling'); // This should never be called
+    });
+
+    await tester.drag(find.byKey(innerKey), const Offset(0, 2000)); // Over-scroll the inner Scrollable to the bottom
+
+    const double endPosition = -1974.0862087158384;
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:279]: Rather than this complicated value, you could use the `greaterThan`, `moreOrLessEquals`, etc tools that `flutter_test` provides.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 4]
```diff
@@ -212,6 +212,110 @@ void main() {
...
+    expect(outer.offset, 0.0);
+    expect(inner.offset, endPosition + 600);
+
+    await tester.pump(nextFrame);
+
+    // Assert positions after pump
+    expect(outer.offset, 0.0);
+    expect(inner.offset, endPosition + 600);
+
+    // Since there is a difference between scrolling on devices and the web absolute values are not checked...
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:298]: I am not sure I follow here. What was the failure this is working around?

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 5]
```diff
@@ -212,6 +212,110 @@ void main() {
...
+      await tester.pump(nextFrame);
+      expect(inner.offset, greaterThanOrEqualTo(currentOffset));
+      expect(outer.offset, 0.0);
+
+      currentOffset = inner.offset;
+    }
+
+    // Assert positions returned to/stayed at 0.0
+    expect(outer.offset, 0.0);
+    expect(inner.offset, 0.0);
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:316]: If you end with a `await tester.pumpAndSettle()` we can see where it actually ends as the fling comes to a rest. Can you add that?

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 6]
```diff
@@ -212,6 +212,110 @@ void main() {
...
+
+    // Assert positions after fling
+    expect(outer.offset, 0.0);
+    expect(inner.offset, endPosition + 600);
+
+    await tester.pump(nextFrame);
+
+    // Assert positions after pump
+    expect(outer.offset, 0.0);
+    expect(inner.offset, endPosition + 600);
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:296]: Thank you for adding these checks! I much better understand what is happening here. The fling is consuming only the overscrolled portion of the inner scrollable for the whole test. 👍

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 3 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:279]: Since. we are essentially testing a double precision error, I included the exact value the controller had after the drag, but I can change it.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 4 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:298]: Before I had concrete values at each step, as seen in this [commit](https://github.com/flutter/flutter/pull/138319/commits/7dd10eac04067f5b53d4df5b7a0ef1bca846d74b), I then rewrote it since tests on Web were failing due to the controller reporting different values than seen on native platforms. I can remove the comment if that is intended.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 5 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:316]: Will do.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 6 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:296]: 👍

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 3 above)
Comment (Michal-MK) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:279]: On a second thought I like how the math adds up, because later in the code I do: endValue + 600 which would then not work... If I used `moreOrLessEquals` the delta would have to be really big. I could do `moreOrLessEquals(-2000, delta: 100.0)` sicne 2000 is the drag parameter, but I do not like how vague that becomes.

Comment (Piinks) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:279]: Ok! We should probably add some context at least in a comment for future wonderers. Style guide has recommendations: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-mysterious-and-magical-numbers-that-lack-a-clear-derivation

**Review by Piinks — COMMENTED** [review]
This change looks good, with added context in the test for that value. I will be OOO on vacation after today, so if you would not like to wait, another reviewer can be requested on the Discord. This change will need two approvals. Thanks!

**Review by Piinks — APPROVED** [review]
Thanks for the update @Michal-MK, and happy new year! This LGTM!

**Comment by Michal-MK** [comment]
Happy new year to you and all of the Flutter team. Awesome framework, glad I could contribute. :)

**Comment by Michal-MK** [comment]
@Piinks  Is there something on my part that needs doing? The "Google testing" test is now running for more than 5 days, is that intended?

**Comment by Piinks** [comment]
This still needs a second review, but I have rebased it to kick the Google testing shard. 👍 
Following up on the second review in https://discord.com/channels/608014603317936148/804482791517192273/1193960740856545290

**Comment by Piinks** [comment]
Hmm, I was not able to rebase since there is a merge conflict. Can you rebase with the master branch @Michal-MK?

**Comment by Michal-MK** [comment]
Struggling with the rebase, give me a minute :)

**Comment by Michal-MK** [comment]
So, I finally won agains git rebase, unfortunately, the bot added some people for review, that was not intentional. @Piinks I do not see the Discord channel and I have not found any info on how to enable it on what is publicly available.

**Comment by Piinks** [comment]
Thanks for rebasing! Looks like that channel is restricted to contributors with commit access (members of flutter-hackers): https://github.com/flutter/flutter/wiki/Contributor-access

Sorry for sharing something inaccessible. The channel is for seeking reviewers, so it should get picked up soon. 👍

**Review by goderbauer — APPROVED** [review]
secondary LGTM
