### PR TITLE
make `--dart-define` override redundant values in `--dart-define-from-file`

### LINKED ISSUE #130604: `--dart-define` doesn't override values passed with `--dart-define-from-file`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an empty project and `cd` into it

    ```
    flutter create example --platforms android --empty
    ```

1. Create a `defines.json` file in the project root:

    ```bash
    echo '{"FIRST_KEY": "FIRST_VALUE"}' > defines.json
    ```

1. Modify `lib/main.dart` to display the dart defines provided to the program:

    ```dart
    import 'package:flutter/material.dart';
    
    void main() {
      runApp(const MainApp());
    }
    
    class MainApp extends StatelessWidget {
      const MainApp({super.key});
    
      @override
      Widget build(BuildContext context) {
        return const MaterialApp(
          home: Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text('Hello World!'),
                  Text('FIRST_KEY=${const String.fromEnvironment('FIRST_KEY')}'),
                  Text('SECOND_KEY=${const String.fromEnvironment('SECOND_KEY')}'),
                ],
              ),
            ),
          ),
        );
      }
    }
    ```

1. Run the program, passing both `--dart-define-from-file` and `--dart-define` options. 

    > Use case: I have many dart defines in my JSON config file, but I want to override one of these values, e.g. for debugging purposes.

    ```
    flutter run \
      --dart-define-from-file defines.json \
      --dart-define 'FIRST_KEY=you just got overridden' \
      --dart-define 'SECOND_KEY=SECOND_VALUE'
    ```

### Expected results

Screenshot 2023-07-14 at 8 43 41 PM

### Actual results

Screenshot 2023-07-14 at 8 41 19 PM

### Code sample

`N/A` / provided above

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-PL)
    • Flutter version 3.10.5 on channel stable at /Users/bartek/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bartek/androidsdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bartek/androidsdk
    • Java binary at: /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/bartek/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #130604 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -1351,14 +1351,14 @@ abstract class FlutterCommand extends Command<void> {
...
 
-    if (argParser.options.containsKey(FlutterOptions.kDartDefinesOption)) {
-      dartDefines.addAll(stringsArg(FlutterOptions.kDartDefinesOption));
-    }
-
     defineConfigJsonMap.forEach((String key, Object? value) {
       dartDefines.add('$key=$value');
     });
 
+    if (argParser.options.containsKey(FlutterOptions.kDartDefinesOption)) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:1358]: can we document in the help text the precedence for these two?

File: packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart [hunk 2]
```diff
@@ -559,6 +559,42 @@ void main() {
...
+    ]);
+
+  }, overrides: <Type, Generator>{
+    BuildSystem: () => TestBuildSystem.all(BuildResult(success: true),
+            (Target target, Environment environment) {
+          expect(
+            _decodeDartDefines(environment),
+            containsAllInOrder(const <String>[
+              'MY_VALUE=VALUE_FROM_ENV_FILE',
+              'MY_VALUE=VALUE_FROM_COMMAND',
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart:590]: so if the dart vm sees these, the second entry will override the first?

Comment (andrewkolos) [reply packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart:590]: Yeah, I tested this on MacOS using the repro steps (I should have pushed my repro project, but I accidentally `git clean`ed it out of existence).

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart:1358]: Good idea.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart:1359]: Done. Also updated some error text, so that we don't yell at the user.

File: packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart:590]: I would have liked to write a more sound test for this, but I am not sure we can do this without actually doing a real build.

Alternatively, we _could_ implement parsing on `--dart-define` rebuild our own string that removes redundant entries, but this would be nontrivial.

Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/permeable/build_bundle_test.dart:590]: yeah, if that's non-trivial this is fine. just wanted to make sure i was understanding correctly.

**Review by christopherfujino — APPROVED** [review]
LGTM
