### PR TITLE
Forward missing pub commands

### LINKED ISSUE #9301: Map `pub run` to `flutter package run` command or similar
https://flutter.io/setup-macos/

Currently in documentation there is an info to export PATH:
```
export PATH=$HOME/flutter/bin:$PATH
```
By doing that you do not export path to Dart SDK and you are not able to use `pub run` command which is used by some of the tools like `Intl`.

It would be nice to also export Dart SDK which is downloaded with Flutter:
```
export PATH=$HOME/flutter/bin:$PATH
export PATH=$HOME/flutter/bin/cache/dart-sdk/bin/:$PATH
```

### LINKED ISSUE #13360: 'pub run' with flutter tool requires redundant 'pub' on the command line
@franzsilva wrote a cool tool for managing launcher icons, and packaged it as a pub package. Apparently, using the flutter tool, a user can't run the script without typing "pub" twice.

For example: `flutter pub pub run flutter_launcher_icons:main`

We're wondering if the following could work instead: `flutter pub run flutter_launcher_icons:main`

Comment: https://github.com/franzsilva/flutter_launcher_icons/issues/4#issuecomment-349454015

### LINKED ISSUE #21898: flutter packages pub --version prints flutter version instead of pub version
Similarly `flutter packages pub --help` does not print pub's help.

### LINKED ISSUE #27911: error message displayed when trying to run 'flutter packages pub global activate <tool>'
When trying to use the pub global activate via the flutter packages pub pass-through, I see an error:

```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

However, the `pub global activate` does not require a pubspec; it can be run from anywhere.

I believe the `PackagesPassthroughCommand` class in commands/packages.dart should be updated tp not require a pubspec.

### LINKED ISSUE #28292: Make it easier to run pub global commands through flutter tools.
Currently we would require`flutter packages pub global activate devtool`. We should support something like:

- `flutter pub activate devtool`?

Maybe we could shorten the API a bit for the global commands,

- `flutter activate devtool` ?

### PR DESCRIPTION
**Pull request by mit-mit**
## Description

Currently `flutter` supports just two pub subcommands:

1. `flutter packages get` -> `pub get`
1. `flutter packages upgrade` -> `pub upgrade`

This adds forwards for the following missing pub commands:

1. `flutter packages downgrade` -> `pub downgrade`, the opposite of upgrade
1. `flutter packages publish` -> `pub publish` to support publishing a plugin
1. `flutter packages deps` -> `pub deps` to show package dependencies
1. `flutter packages run` -> `pub run` to support running executables, e.g. for package:intl
1. `flutter packages cache` -> `pub cache` to manage the pub cache contents
1. `flutter packages version` -> `pub version` to see the pub version
1. `flutter packages uploader` -> `pub uploader` to manage [package uploaders](https://www.dartlang.org/tools/pub/cmd/pub-uploader)
1. `flutter packages global` -> `pub global`: pub global commands

## Related Issues

Fixes https://github.com/flutter/flutter/issues/27911
Fixes https://github.com/flutter/flutter/issues/9301
Fixes https://github.com/flutter/flutter/issues/13360
Fixes https://github.com/flutter/flutter/issues/21898
Fixes https://github.com/flutter/flutter/issues/28292

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @devoncarew, I'm missing tests, I think. How do those usually work the `flutter packages`?

**Comment by mit-mit** [comment]
Sample output:

* `-h`:
```
$ flutter pub -h
Commands for managing Flutter packages.

Usage: flutter packages <subcommand> [arguments]
-h, --help    Print this usage information.

Available subcommands:
  cache       Work with the Pub system cache.
  deps        Print package dependencies.
  downgrade   Downgrade packages in a Flutter project.
  get         Get packages in a Flutter project.
  global      Work with Pub global packages.
  pub         Pass the remaining arguments to Dart's "pub" tool.
  publish     Publish the current package to pub.dartlang.org.
  run         Run an executable from a package.
  test        Run the "test" package.
  upgrade     Upgrade packages in a Flutter project.
  uploader    Manage uploaders for a package on pub.dartlang.org.
  version     Print Pub version.
```

* `global`:
```
$ flutter pub global activate stagehand
Package stagehand is currently active at version 3.2.0.
```

**Comment by devoncarew** [comment]
@mit-mit, since we're adding so many new `pub` forwarding commands, do we generally want these exposed as `flutter packages ...` or `flutter pub ...`?

Also adding @jonahwilliams as a reviewer.

File: packages/flutter_tools/lib/src/commands/packages.dart [hunk 1]
```diff
@@ -124,6 +132,36 @@ class PackagesTestCommand extends FlutterCommand {
   }
 }
 
+class PackagesForwardCommand extends FlutterCommand {
+  PackagesForwardCommand(this._commandName, this._description, {bool requiresPubspec = false}) {
+    if (requiresPubspec)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/packages.dart]: It looks like the if statement here has no body.

```suggestion
    if (requiresPubspec) {
      requiresPubspecYaml();
    }
```

**Comment by devoncarew** [comment]
re: testing, the existing `flutter packages` tests are at `/flutter/packages/flutter_tools/test/commands/packages_test.dart`.

File: packages/flutter_tools/lib/src/commands/packages.dart (hunk 1 above)
Comment (mit-mit) [reply packages/flutter_tools/lib/src/commands/packages.dart]: Fixed

**Comment by mit-mit** [comment]
> @mit-mit, since we're adding so many new `pub` forwarding commands, do we generally want these exposed as `flutter packages ...` or `flutter pub ...`?

We already have an alias in place, so you can already run either `flutter packages xxx` or `flutter pub xxx`. Per recent PM discussion, once we launch the new `pub.dev` site, we would like to move all Dart development to use the `pub` nomenclature, so I'll be creating a new PR here and over in flutter/website to change the docs to use `flutter pub`.

**Comment by mit-mit** [comment]
cc @kevmoo, I don't fully understand the voodoo magic for analytics over in `pub.dart` -- can you see if the one-liner I added is sufficient?

https://github.com/flutter/flutter/blob/7996d7ac176079b27e62c8ef2c316bd665658058/packages/flutter_tools/lib/src/dart/pub.dart#L44

File: packages/flutter_tools/lib/src/dart/pub.dart [hunk 2]
```diff
@@ -41,6 +41,7 @@ class PubContext {
   static final PubContext interactive = PubContext._(<String>['interactive']);
   static final PubContext pubGet = PubContext._(<String>['get']);
   static final PubContext pubUpgrade = PubContext._(<String>['upgrade']);
+  static final PubContext pubForward = PubContext._(<String>['forward']);
```
Comment (kevmoo) [inline packages/flutter_tools/lib/src/dart/pub.dart]: should be fine. This is how we track what a user ran if the command ends up hitting the server.

Comment (mit-mit) [reply packages/flutter_tools/lib/src/dart/pub.dart]: Great, thanks!

**Comment by mit-mit** [comment]
I've added tests. They are passing locally, but fail on CI. Any tips?

```
est/commands/packages_test.dart: packages test/pub uploader [E]                                                                                                                     
  Expected: an object with length of <2>
    Actual: ['/tmp/flutter sdk/bin/cache/dart-sdk/bin/pub', '--trace', 'uploader']
     Which: has length of <3>
```

**Comment by mit-mit** [comment]
cc @jonahwilliams any tips on the test question above?

**Comment by jonahwilliams** [comment]
Are you running the test with pub or build_runner? CI uses pub run build_runner test

**Comment by mit-mit** [comment]
I think so:

```
$ flutter pub run build_runner test --  test/commands/packages_test.dart
...
00:19 +15: All tests passed!
```

**Review by jonahwilliams — APPROVED** [review]
LGTM
