### PR TITLE
Fix - TalkBack does not announce list information

### LINKED ISSUE #168651: [Google3 Bug]: Android Talkback does not read "1 of 4" or similar indexes of items for any of the children of the `ListView` even with the use of `IndexedSemantics`
### Help us understand the severity of this issue

- [ ] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [x] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

1. Run the flutter application on android device
2. Start android Talkback
3. Swipe horizontally to allow Android talkback read through the Text widgets on the screen.

### Expected results

With the use of IndexedSemantics, Android Talkback should have read:
"1 of 4, Title 1"
"2 of 4, Title 2",
"3 of 4, Title 3",
"4 of 4, Title 4"

### Actual results

The following is read out by Talkback:
"Title 1"
"Title 2"
"Title 3"
"Title 4"

### Code sample

<details open><summary>Code sample</summary>
In the `bug_repro` project (created via `flutter create ~/Desktop/bug_repro`),
Replace the `build` method of `_MyHomePageState` with the following code:

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView(
          addSemanticIndexes: false,
          semanticChildCount: 4,
          physics: NeverScrollableScrollPhysics(),
          children: [
            IndexedSemantics(index: 0, child: Text('title 1')),
            IndexedSemantics(index: 1, child: Text('title 2')),
            IndexedSemantics(index: 2, child: Text('title 3')),
            IndexedSemantics(index: 3, child: Text('title 4')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      )
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0d3d1b93-8514-4db2-8f7e-7dc0b8f77516

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale en) [2.2s]
    • Flutter version 3.29.3 on channel stable at /Users/bhagrawal/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.3s]
    • Android SDK at /Users/bhagrawal/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 16.0) [1,204ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.0) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (4 available) [6.4s]
    • Pixel 6a (mobile)               • 29121JEGR04412        • android-arm64  • Android 15 (API 35)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.4.1 24E263
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.4.1 24E263
      darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 136.0.7103.93
    ! Error: Browsing on the local area network for GBA iPhone12 202404. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Bhuvnesh’s Apple Watch. Ensure the device is unlocked and
      discoverable via Bluetooth. (code -27)

[✓] Network resources [478ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

b/418696524

### PR DESCRIPTION
**Pull request by jwlilly**
Updating AccessibilityBridge.java and AccessibilityBridgeTest.java to include `AccessibilityNodeInfo.CollectionItemInfo` to get TalkBack to announce item indexes for ListViews. 

- Updated the logic for adding CollectionInfo to add when the scrollChildren count is greater than 1. This is an attempt to exclude something like a SingleChildScrollView from getting CollectionInfo added. The only semantics info we can rely on from Android is the hasImplicitScrolling and the number of scrollChildren. 
- Added logic for adding the CollectionItemInfo to ListView children. It first checks to see if the parent node qualifies for CollectionInfo and then adds the CollectionItemInfo to the child view. The index values come from the `childrenInTraversalOrder`. We aren't currently passing the indexedSemantics into the SemanticsNode. Once those values are available, this can be made more robust. 

The following video includes the new changes with a ListView

https://github.com/user-attachments/assets/b9bf1b80-9f29-40e2-8f33-a08919554b7e

This video includes the logic with a SingleChildScrollView (no list announcements as expected)

https://github.com/user-attachments/assets/8fe4dd24-cc5a-4a6b-b4b0-0f371fea20df

Fixes #168651 - This is a minimal fix. A full fix would be to pass the indexedSemantics to the SemanticsNode in Android and build the list with those values. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java [hunk 1]
```diff
@@ -2071,6 +2072,49 @@ public void itAddsClickActionToSliderNodeInfo() {
...
+    childNode1.label = "Test 1";
+    TestSemanticsNode childNode2 = new TestSemanticsNode();
+    childNode2.id = 2;
+    childNode2.label = "Test 2";
+    parentTestSemanticsNode.addChild(childNode1);
+    parentTestSemanticsNode.addChild(childNode2);
+    TestSemanticsUpdate testSemanticsUpdate = parentTestSemanticsNode.toUpdate();
+    testSemanticsUpdate.sendUpdateToBridge(accessibilityBridge);
+    AccessibilityNodeInfo nodeInfo = accessibilityBridge.createAccessibilityNodeInfo(1);
+    assertNotNull(nodeInfo.getCollectionItemInfo());
```
Comment (ash2moon) [inline engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]: Could you please add a little more testing context on what exactly this collectionItemInfo is supposed to contain?

Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]: Good call! I added additional checks to make sure CollectionInfo and CollectionItemInfo had the correct values which made me find a logic bug that I also fixed.

**Comment by chinmaygarde** [comment]
This might be ready for another review.

**Review by ash2moon — APPROVED** [review]

**Comment by chinmaygarde** [comment]
At least one of the failures is unrelated and a fix for it is pending in https://github.com/flutter/flutter/pull/175794. But there are more failures that look related.

**Comment by chinmaygarde** [comment]
The failures look related to the golden images as expected. They'll need to be patched to make forward progress.

**Comment by jwlilly** [comment]
> The failures look related to the golden images as expected. They'll need to be patched to make forward progress.

Is that something I need to do? Or do I just need to hang out for now?

**Comment by chinmaygarde** [comment]
This is good to go. May I add the autosubmit tag?

**Comment by jwlilly** [comment]
> This is good to go. May I add the autosubmit tag?

Sure, that's fine with me

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 2]
```diff
@@ -891,59 +898,82 @@ public AccessibilityNodeInfo createAccessibilityNodeInfo(int virtualViewId) {
         || semanticsNode.hasAction(Action.SCROLL_RIGHT)
         || semanticsNode.hasAction(Action.SCROLL_DOWN)) {
       result.setScrollable(true);
-
       // This tells Android's a11y to send scroll events when reaching the end of
       // the visible viewport of a scrollable, unless the node itself does not
       // allow implicit scrolling - then we leave the className as view.View.
```
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java:917]: Nit: Does this refer to line 900? If so, can we move this above that line?

**Review by camsim99 — COMMENTED** [review]
> This is a minimal fix. A full fix would be to pass the indexedSemantics to the SemanticsNode in Android and build the list with those values.

At a high level this fix seems fair to me but may I ask why not go with the full fix first? I assume it's something along the lines of the effort not being worth the value but just want to confirm!

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java (hunk 2 above)
Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java:917]: Yep! Just moved it

**Comment by jwlilly** [comment]
> > This is a minimal fix. A full fix would be to pass the indexedSemantics to the SemanticsNode in Android and build the list with those values.
> 
> At a high level this fix seems fair to me but may I ask why not go with the full fix first? I assume it's something along the lines of the effort not being worth the value but just want to confirm!

I chatted with @chunhtai on discord while I was working on this. A full fix would be to pass the IndexedSemantics values into the semantics object and pass those to Android. But we figured that would be a lot heavier of a lift and would tackle that later. For now a minimum solution of inferring the index based on the children from the semantics seemed like a good route to go with.

**Review by camsim99 — APPROVED** [review]
Gotcha thanks for letting me know. LGTM!

**Comment by jwlilly** [comment]
@camsim99 finally getting successful checks if you'd like to add autosubmit back

edit: well everything was passing. Now there's a tree-status issue

**Comment by chingjun** [comment]
@jwlilly Reason for revert: This PR calls the constructor of `AccessibilityNodeInfo.CollectionInfo`, which is added in API 30, without the API version guard. It broke some internal tests that are running on API 29 and below.

**Comment by jwlilly** [comment]
> @jwlilly Reason for revert: This PR calls the constructor of `AccessibilityNodeInfo.CollectionInfo`, which is added in API 30, without the API version guard. It broke some internal tests that are running on API 29 and below.

No worries. I didn't even think about that scenario. I'll make some updates and do a PR. Probably won't be able to get to it until next week
