### PR TITLE
Include initial offset when using PlatformViewSurface

### LINKED ISSUE #580: Ads placed in ListView is getting impression before they appear on the screen in Flutter 3
Hi, I originally posted this here https://github.com/googleads/googleads-mobile-flutter/issues/269#issuecomment-1059741368, before the new Android PlatformView implementation was merged with the stable channel, but this issue is now in Flutter 3 stable channel.

With the new Android PlatformView implementation, banner placed in `ListView` is getting impression before it appears on the screen.
This conflicts with Admob policy. (https://support.google.com/admob/answer/3269069?hl=en)
In the previous version, getting impression only when the first pixel of banner is seen on the screen.

This is a critical issue, apps using this plugin with Flutter 3 can be banned by Admob, because technically you are creating fake impressions with this implementation.

## Steps to Reproduce

To reproduce, try this example code with Flutter 3, plugin version doesn't matter.
```dart
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 15,
        itemBuilder: (context, index) {
          if (index != 0 && index % 5 == 0) {
            return const _BannerAd();
          }

          return Container(
            height: 200,
            color: Color((Random().nextDouble() * 0xFFFFFF).toInt())
                .withOpacity(1),
          );
        },
      ),
    );
  }
}

class _BannerAd extends StatefulWidget {
  const _BannerAd({Key? key}) : super(key: key);

  @override
  _BannerAdState createState() => _BannerAdState();
}

class _BannerAdState extends State<_BannerAd>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  late BannerAd myBanner;

  @override
  void initState() {
    super.initState();
    myBanner = BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (ad) => print('Ad loaded.'),
        onAdFailedToLoad: (ad, error) {
          ad.dispose();
          print('Ad failed to load .');
        },
        onAdOpened: (ad) => print('Ad opened.'),
        onAdClosed: (ad) => print('Ad closed.'),
        onAdImpression: (ad) => print('Ad impression.'),
      ),
    )..load();
  }

  @override
  void dispose() {
    myBanner.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return Container(
      width: myBanner.size.width.toDouble(),
      height: myBanner.size.height.toDouble(),
      margin: const EdgeInsets.all(20),
      alignment: Alignment.center,
      child: AdWidget(ad: myBanner),
    );
  }
}
```

**Expected results:** Ads placed in the ListView should get impression when they appear on the screen.

**Actual results:** All ads in ListView are simultaneously get impression when the ListView is built.

### PR DESCRIPTION
**Pull request by bparrishMines**
For TLHC (Texture Layer Hybrid Composition), the create request is expecting a `left` and a `top` parameter on the engine side:

https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformViewsChannel.java#L117

AFAICT, there is never any `top` or `left` parameters passed from the framework when creating a platform view:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_views.dart#L1186

Therefore, the creation requests default to position `(0, 0)` and the Android View hierarchy thinks the PlatformView is onscreen for the [initial render](https://github.com/flutter/engine/blob/25133f15440dc71d596efbd3b1d7fff54d0213d8/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L578) since it is added to the FlutterView (but not drawn). Note that later a PlatformViewsChannel call is made to the [offset method](https://github.com/flutter/engine/blob/25133f15440dc71d596efbd3b1d7fff54d0213d8/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L283) to set the top and left margin positions. 

This PR makes the create call wait for the initial position of the platform view before it is made.

Should fix https://github.com/googleads/googleads-mobile-flutter/issues/580

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/platform_view.dart [hunk 1]
```diff
@@ -1204,7 +1205,9 @@ class _PlatformViewPlaceholderBox extends RenderConstrainedBox {
   @override
   void performLayout() {
     super.performLayout();
-    onLayout(size);
+    SchedulerBinding.instance.addPostFrameCallback((_) {
```
Comment (stuartmorgan) [inline packages/flutter/lib/src/widgets/platform_view.dart:1208]: Could you add a comment explaining why it's deferred a frame?

**Review by stuartmorgan-g — APPROVED** [review]
LGTM (with one comment nit), thanks for digging into this!
