### PR TITLE
Use relative path for reloadedSourcesUri and reloaded modules

### LINKED ISSUE #184060: reloaded_sources.json is returning incorrect src url in response
### Steps to reproduce

1. Run `flutter run -d web-server` behind a reverse proxy with a domain. e.g. `example.com`
2. Open the URL in browser. This would be `example.com`, not `localhost:<port>`.
3. Hot Reload.
4. The loaded web app makes a request to `reloaded_sources.json` endpoint. 
5. Inspect the response.

`reloaded_sources.json` returns following

```dart
[{
    "src": "http://localhost:15488/packages/my_flutter_app/main.dart.lib.js",
    "module": "packages/my_flutter_app/main.dart",
    "libraries": ["package:my_flutter_app/main.dart"]
}]
```
Notice that the `src` param returns a full url which points to `localhost`. This is very problematic as this breaks reverse proxies and URLs used for it.

> Note: There is a tracking issue #179406 where `reloaded_sources.json` is being requested on a localhost URL too but I was able to get past it with an script but then got hit with this.

### Expected results

`src` should return the relative path only excluding the host and port. The host and port then should be reconstructed on the client based on the loaded URL in the browser.

### Actual results

`src` contains full URL that points to localhost which breaks reverse proxies.

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter create . --platforms=web
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.41.5, on macOS 26.3.1 25D771280a darwin-arm64, locale en-IN) [1,486ms]
    • Flutter version 3.41.5 on channel stable at /Users/birjuvachhani/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2c9eb20739 (2 days ago), 2026-03-17 16:14:01 -0700
    • Engine revision 052f31d115
    • Dart version 3.11.3
    • DevTools version 2.54.2
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, enable-custom-devices, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0) [10.4s]
    • Android SDK at /Users/birjuvachhani/Library/Android/sdk
    • Emulator version 36.4.10.0 (build_id 15004761) (CL:N/A)
    • Platform android-36, build-tools 36.1.0
    • ANDROID_HOME = /Users/birjuvachhani/Library/Android/sdk
    • Java binary at: /usr/bin/java
      This JDK was found in the system PATH.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version Java(TM) SE Runtime Environment (build 21.0.9+7-LTS-338)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.3) [4.9s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17C529
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [5ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [10.1s]
    • Birju’s iPhone (wireless) (mobile)  • 00008110-000E35A83A82401E • ios            • iOS 26.3.1 23D8133
    • Jemini’s iPhone (wireless) (mobile) • 00008110-001E6D5C34C0A01E • ios            • iOS 26.3.1 23D8133
    • macOS (desktop)                     • macos                     • darwin-arm64   • macOS 26.3.1 25D771280a darwin-arm64
    • Chrome (web)                        • chrome                    • web-javascript • Google Chrome 146.0.7680.81

[✓] Network resources [1,286ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by srujzs**
Fixes https://github.com/flutter/flutter/issues/184060

The app may be opened in a separate domain than the server. Therefore, we need to provide relative paths/URIs to the root instead of including the server URI.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/web_asset_server.dart [hunk 1]
```diff
@@ -358,10 +358,9 @@ class WebAssetServer implements AssetReader {
                   canaryFeatures: canaryFeatures,
                 ),
                 packageConfigPath: buildInfo.packageConfigPath,
-                reloadedSourcesUri: server._baseUri.replace(
-                  pathSegments: List<String>.from(server._baseUri.pathSegments)
-                    ..add(_reloadedSourcesFileName),
-                ),
+                // Use relative path for module so the app can still find it
+                // even if it's in a different domain than the server.
```
[the remark this answers is not in the document]
Comment (srujzs) [reply packages/flutter_tools/lib/src/isolated/web_asset_server.dart]: Done.

File: packages/flutter_tools/lib/src/isolated/web_asset_server.dart [hunk 2]
```diff
@@ -150,9 +149,10 @@ class WebAssetServer implements AssetReader {
             as Map<String, dynamic>,
       );
       final List<String> libraries = metadata.libraries.keys.toList();
-      final moduleUri = '$baseUri/$module';
       moduleToLibrary.add(<String, Object>{
-        'src': moduleUri,
+        // Use relative path for module so the app can still find it even if
+        // it's in a different domain than the server.
+        'src': module,
         'module': metadata.name,
```
Comment (nshahan) [inline packages/flutter_tools/lib/src/isolated/web_asset_server.dart]: Would it make sense to rename the `module` local variable so that these mappings don't look like a mistake?

File: packages/flutter_tools/lib/src/isolated/web_asset_server.dart [hunk 3]
```diff
@@ -122,9 +122,8 @@ class WebAssetServer implements AssetReader {
   /// hot reload, writes a file that contains a list of objects each with three
   /// fields:
   ///
-  /// `src`: A string that corresponds to the file path containing a DDC library
-  /// bundle. To support embedded libraries, the path should include the
-  /// `baseUri` of the web server.
+  /// `src`: A string that corresponds to the relative file path containing a
+  /// DDC library bundle.
```
Comment (nshahan) [inline packages/flutter_tools/lib/src/isolated/web_asset_server.dart]: What are the paths relative to?

**Review by nshahan — COMMENTED** [review]
Do you think it would be beneficial to have a regression test that makes expectations of the `'src'` values that appear in the reloaded_sources.json?

File: packages/flutter_tools/lib/src/isolated/web_asset_server.dart (hunk 2 above)
Comment (srujzs) [reply packages/flutter_tools/lib/src/isolated/web_asset_server.dart]: Done.

File: packages/flutter_tools/lib/src/isolated/web_asset_server.dart (hunk 3 above)
Comment (srujzs) [reply packages/flutter_tools/lib/src/isolated/web_asset_server.dart]: The app's base URL, I modified the comment to be more clear.

**Comment by srujzs** [comment]
> Do you think it would be beneficial to have a regression test that makes expectations of the 'src' values that appear in the reloaded_sources.json?

I'm trying out a test that dynamically finds the IP and using that for the hostname and seeing if the bots like it.

**Comment by srujzs** [comment]
Okay, it looks like the bots are happy now (or they were in my last upload). Maybe they were timing out because of the additional hot reload integration test, but it doesn't explain why unrelated bots were timing out.

I tried to test this by dynamically fetching the current IP and forcing that as the hostname, but the test passes even without the changes, so I ended up going with a unit test that checks that the paths are as expected. Most of the test is just code from other tests to set up the `WebDevFS`, but additional code is added to use DDC library bundle assets and emit a valid module metadata.

I also changed the reloaded_sources.json `src` field to add back a `/` at the beginning because the parsed scripts controller in DWDS compares the reloaded sources with the normalized parsed paths, and so it needs that `/`.

This should be ready to review.

File: packages/flutter_tools/test/general.shard/web/devfs_web_test.dart [hunk 4]
```diff
@@ -1803,6 +1805,150 @@ const config = {
...
+      expect(reloadedSources, isNotNull);
+      expect(json.decode(utf8.decode(reloadedSources!)), [
+        {
+          // The paths within `reloadedSources` should be relative with a root
+          // prefix.
+          'src': '/a.lib.js',
+          'module': 'a.lib.js',
+          'libraries': ['dart:b'],
+        },
+      ]);
```
Comment (nshahan) [inline packages/flutter_tools/test/general.shard/web/devfs_web_test.dart:1964]: It kinda feels like this expectation is missing files that should appear in subdirectories relative to some "app root" location.  That is, were not just expecting a 'src' that contains no directories, but if there are directories in the path they should be relative.

Maybe we should have an import that comes from a subdirectory so we can see two paths here, one with the main at a root, and then some subdirectory relative to it?

**Review by nshahan — DISMISSED** [review]
Thanks again for working on this. LGTM with one question about the test.

File: packages/flutter_tools/test/general.shard/web/devfs_web_test.dart (hunk 4 above)
Comment (srujzs) [reply packages/flutter_tools/test/general.shard/web/devfs_web_test.dart:1964]: The new test case should do what I *think* you're asking where the module path is in a subdirectory. The root here is where the `main.dart` file is for the test (`lib`).

Comment (srujzs) [reply packages/flutter_tools/test/general.shard/web/devfs_web_test.dart:1964]: Okay, I modified the test to do one reload only but with two modules instead.

**Review by nshahan — APPROVED** [review]
Yeah, I like this version of the test more. Thanks!
