### PR TITLE
[tool] make `ErrorHandlingFileSystem.deleteIfExists` catch error code 3 (`ERROR_PATH_NOT_FOUND` on Windows)

### LINKED ISSUE #150736: [tool] consider making `ErrorHandlingFileSystem.deleteIfExists` catch system error code `ERROR_PATH_NOT_FOUND` (3) on Windows
Discovered while investigating https://github.com/flutter/flutter/issues/137168. As of writing this, I believe that resolving this issue is prerequisite to solving that one.

Consider https://github.com/flutter/flutter/issues/137168. The crashing exception here is `PathNotFoundException: PathNotFoundException: Deletion failed, path = 'D:\<project dir path>\windows\flutter\ephemeral\.plugin_symlinks' (OS Error: The system cannot find the path specified.
, errno = 3)`. However, if we look at the code that threw this, we notice that it confirms the existence of the directory before it tries to delete it.

https://github.com/flutter/flutter/blob/99c7e9f088569bfedfe609c2260cad8f2bcbcb23/packages/flutter_tools/lib/src/flutter_plugins.dart#L1039-L1042

Barring some more complex bug in the tool or Dart's filesystem abstractions, this strongly suggests that something happened to this directory in the time between the tool checking for its existence and trying to delete it.

While it could be argued that this `deleteSync` call should be replaced a `ErrorHandlingFileSystem.deleteIfExists` call, this still would not be sufficient to prevent the crash, because `deleteIfExists` will still throw if it encounters `ERROR_PATH_NOT_FOUND`:

https://github.com/flutter/flutter/blob/fda9ecfef76b57ae459675fdf262342a77c2c6ba/packages/flutter_tools/lib/src/base/error_handling_io.dart#L75-L87

Notice that if the error code is not `kSystemCannotFindFile`, we will `rethrow`. Here is the definition of this constant:

https://github.com/flutter/flutter/blob/fda9ecfef76b57ae459675fdf262342a77c2c6ba/packages/flutter_tools/lib/src/base/error_handling_io.dart#L24-L26

We should augment `deleteIfExists` to not `rethrow` in the presence of `ERROR_PATH_NOT_FOUND` on Windows.

### PR DESCRIPTION
**Pull request by andrewkolos**
Resolves https://github.com/flutter/flutter/issues/150736

FYI I plan to cherry-pick this

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 1]
```diff
@@ -82,7 +86,11 @@ class ErrorHandlingFileSystem extends ForwardingFileSystem {
       // Certain error codes indicate the file could not be found. It could have
       // been deleted by a different program while the tool was running.
       // if it still exists, the file likely exists on a read-only volume.
-      if (err.osError?.errorCode != kSystemCannotFindFile || _noExitOnFailure) {
+      // This check will falsely match "3/ESRCH: No such process" on Linux/macOS,
+      // but this should be fine since this code should never come up here.
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:90]: If this is a bit too smelly for your tastes, please read https://github.com/flutter/flutter/issues/150736#issuecomment-2187593847

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:90]: Why do you say "this code should never come up here"? Are you saying that we should never hit a "no such process" error on unix-like operating systems when calling `deleteIfExists`?

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:90]: (We talked about this in-person. I'm commenting here for posterity's sake). Yes, that's my hope. I'm assuming 3/ESRCH is never set by a file op. I'm assuming this code is used by Linux utilities that act on processes rather than files.
