### PR TITLE
Include -isysroot -arch and -miphoneos-version-min when creating dummy module App.framework

### LINKED ISSUE #1004: multiple_flutters_ios crashes when run on iOS device
I tried to build and run the `multiple_flutters_ios` example located in https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters/multiple_flutters_ios on my iOS device following the instructions given in the readme (using master of flutter @ https://github.com/flutter/flutter/commit/39c5d2fa0a9836014bf8e2bde6842edbb767df56):

```
cd ../multiple_flutters_module
flutter pub get
cd -
pod install
open MultipleFluttersIos.xcworkspace
# (build and run)
```

When running the app with xcode, it crashes with the following error:

```
Library not loaded: @rpath/App.framework/App
  Referenced from: /private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/MultipleFluttersIos
  Reason: tried: '/usr/lib/swift/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/usr/lib/swift/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/87326E6C-36A4-4235-B2CA-25AFC260B730/MultipleFluttersIos.app/Frameworks/App.framework/App' (no such file), '/System/Library/Frameworks/App.framework/App' (no such file)
```

Looks like the bundle that xcode produces for the app does not include the AOT compiled dart code for the app (App.framework).

### PR DESCRIPTION
**Pull request by jmagman**
These extra flags create a framework that can be recognized by CocoaPods, so it knows to embed App.framework later after Flutter creates it.

Add `otool` test, which is passing: https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios/11940

Fixes https://github.com/flutter/samples/issues/1004

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/module_test_ios.dart [hunk 1]
```diff
@@ -267,6 +270,14 @@ dependencies:
           throw TaskResult.failure('Building host app Podfile.lock does not contain expected pods');
         }
 
+        // Just running "pod install" should create a fake App.framework so CocoaPods recognizes
+        // it as a framework that needs to be embedded, before Flutter actually creates it.
+        checkFileExists(dummyAppFramework.path);
+        final String? version = await minPhoneOSVersion(dummyAppFramework.path);
+        if (version != '9.0') {
+          throw TaskResult.failure('Minimum version set to $version, expected 9.0');
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/module_test_ios.dart:278]: This test correctly fails on master without the additional flag:
```
Task result:
{
  "success": false,
  "reason": "Minimum version set to null, expected 9.0"
}
```

**Comment by Hixie** [comment]
test-exempt: is a test

**Review by christopherfujino — APPROVED** [review]
LGTM
