### PR TITLE
Invalidate `pod install` output if `.flutter-plugins-dependencies` content changes.

### LINKED ISSUE #162399: [SwiftPM] Plugin not found right after adding
### Steps to reproduce

Using Flutter 3.27.1, Xcode 16.2, iOS Simulator 18.2:

1. Create a SwiftPM plugin:

   ```
   flutter config --enable-swift-package-manager
   flutter create --template=plugin --platforms=ios plugin_a
   ```

2. Create a SwiftPM app:

   ```
   flutter config --enable-swift-package-manager
   flutter create my_app
   cd my_app
   flutter build ios --config-only
   ```

3. Open project in Xcode

   1. Open the app's `ios/Runner.xcworkspace` using Xcode

4. Modify `my_app/pubspec.yaml` to depend on the plugin:

   ```diff
     dependencies:
   +   plugin_a:
   +     path: ../plugin_a
   ```

5. Start iOS simulator 18.2
6. Run the app:

```
flutter run
```

### Expected results

I expect plugin_a to be found. I suspect this is a caching issue that's cause by having the project open in Xcode while also running from the command line, but we should look into it more.

### Actual results

```
           ComputeTargetDependencyGraph
           note: Building targets in dependency order
           note: Target dependency graph (3 targets)
               Target 'Runner' in project 'Runner'
                   ➜ Explicit dependency on target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
               Target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
                   ➜ Explicit dependency on target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
               Target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage' (no dependencies)

...

GeneratedPluginRegistrant.m:12:9: error: Module 'plugin_a' not found (in target 'Runner' from project 'Runner')
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### LINKED ISSUE #163272: Flags `--explicit-package-dependencies` and `--enable-swift-package-manager` collide
You can reproduce this in the [`swift_package_manager_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/swift_package_manager_test.dart) integration test.

First, opt-in to `--explicit-package-dependencies`:

```sh
flutter config --explicit-package-dependencies
```

Then, run the integration test. All of the tests fail, so just picking one is quite a bit faster to iterate on:

```sh
$ cd packages/tools
$ dart test test/integration.shard/swift_package_manager_test.dart -n "Swift Package Manager integration for ios with objc"

...

  stderr: 
  [  +15 ms] Parse Issue (Xcode): Module 'ios_objc_cocoapods_plugin' not found
             /var/folders/qw/qw_3qd1x4kz5w975jhdq4k58007b7h/T/swift_package_manager_enabled.1xqwz9/ios_objc_spm_app/ios/Runner/GeneratedPluginRegistrant.m:17:8
```

`GeneratedPluginRegistrant.m` looks like this:

```objc
//
//  Generated file. Do not edit.
//

// clang-format off

#import "GeneratedPluginRegistrant.h"

#if __has_include(<integration_test/IntegrationTestPlugin.h>)
#import <integration_test/IntegrationTestPlugin.h>
#else
@import integration_test;
#endif

#if __has_include(<ios_objc_cocoapods_plugin/IosObjcCocoapodsPlugin.h>)
#import <ios_objc_cocoapods_plugin/IosObjcCocoapodsPlugin.h>
#else
@import ios_objc_cocoapods_plugin;
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [IntegrationTestPlugin registerWithRegistrar:[registry registrarForPlugin:@"IntegrationTestPlugin"]];
  [IosObjcCocoapodsPlugin registerWithRegistrar:[registry registrarForPlugin:@"IosObjcCocoapodsPlugin"]];
}

@end
```

In the test project, there are no dev-only dependencies:

```yaml
# pubspec.yaml

dependencies:
  ios_objc_cocoapods_plugin:
    path: /var/folders/qw/qw_3qd1x4kz5w975jhdq4k58007b7h/T/swift_package_manager_enabled.1xqwz9/ios_objc_cocoapods_plugin
  integration_test:
    path: /Users/matanl/Developer/flutter/packages/integration_test
```

And indeed, none of them are detected as dev:

```json
# .flutter-plugins-dependencies

{
  "info": "This is a generated file; do not edit or check into version control.",
  "plugins": {
    "ios": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": false
      },
      {
        "name": "ios_objc_cocoapods_plugin",
        "path": "/var/folders/qw/qw_3qd1x4kz5w975jhdq4k58007b7h/T/swift_package_manager_enabled.1xqwz9/ios_objc_cocoapods_plugin/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": false
      }
    ],
    "android": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": false
      }
    ],
    "macos": [],
    "linux": [],
    "windows": [],
    "web": []
  },
  "dependencyGraph": [
    {
      "name": "integration_test",
      "dependencies": []
    },
    {
      "name": "ios_objc_cocoapods_plugin",
      "dependencies": []
    }
  ],
  "date_created": "2025-02-13 16:08:11.766458",
  "version": "3.30.0-1.0.pre.163",
  "swift_package_manager_enabled": {
    "ios": true,
    "macos": false
  }
}
```

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/162399.
Closes https://github.com/flutter/flutter/issues/163272.

`refreshPluginsList` is commonly called in iOS/macOS apps, more times than you expect (and load bearing); https://github.com/flutter/flutter/issues/157391.

With `--explicit-package-dependencies`, we no longer write (or compare) the output of `.flutter-plugins`. The iOS/macOS workflows required `pod install` output to be invalidated when plugins when change, but the logic that was being used to see if plugins changed _only_ worked for the `.flutter-plugins` file format.

In the original code:

```txt
# oldPluginsFileStringContent
{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"integration_test","path":"/Users/matanl/Developer/flutter/packages/integration_test/","native_build":true,"dependencies":[],"dev_dependency":false},{"name":"ios_objc_cocoapods_plugin","path":"/var/folders/qw/qw_3qd1x4kz5w975jhdq4k58007b7h/T/swift_package_manager_enabled.XrEWXS/ios_objc_cocoapods_plugin/","native_build":true,"dependencies":[],"dev_dependency":false}],"android":[{"name":"integration_test","path":"/Users/matanl/Developer/flutter/packages/integration_test/","native_build":true,"dependencies":[],"dev_dependency":false}],"macos":[],"linux":[],"windows":[],"web":[]},"dependencyGraph":[{"name":"integration_test","dependencies":[]},{"name":"ios_objc_cocoapods_plugin","dependencies":[]}],"date_created":"2025-02-13 17:01:11.023097","version":"3.30.0-1.0.pre.163","swift_package_manager_enabled":{"ios":true,"macos":false}}

# pluginsMap
{ios: [{name: integration_test, path: /Users/matanl/Developer/flutter/packages/integration_test/, native_build: true, dependencies: [], dev_dependency: false}, {name: ios_objc_cocoapods_plugin, path: /var/folders/qw/qw_3qd1x4kz5w975jhdq4k58007b7h/T/swift_package_manager_enabled.XrEWXS/ios_objc_cocoapods_plugin/, native_build: true, dependencies: [], dev_dependency: false}], android: [{name: integration_test, path: /Users/matanl/Developer/flutter/packages/integration_test/, native_build: true, dependencies: [], dev_dependency: false}], macos: [], linux: [], windows: [], web: []}
```

As you can see, `pluginsChanged = oldPluginsFileStringContent.contains(pluginsMap.toString());` was _always_ `false`, but we never knew because we'd always just fall back to using the `.flutter-plugins` content comparison (which always worked). 

I added a test as well.

This also appears to fix https://github.com/flutter/flutter/issues/162399.

/cc @jmagman @jonahwilliams

### CODE REVIEW

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 1]
```diff
@@ -244,7 +244,15 @@ bool _writeFlutterPluginsList(
   final String? oldPluginsFileStringContent = _readFileContent(pluginsFile);
   bool pluginsChanged = true;
   if (oldPluginsFileStringContent != null) {
-    pluginsChanged = oldPluginsFileStringContent.contains(pluginsMap.toString());
+    Object? decodedJson;
+    try {
+      decodedJson = jsonDecode(oldPluginsFileStringContent);
+      if (decodedJson is Map<String, Object?>) {
+        final String jsonOfNewPluginsMap = jsonEncode(pluginsMap);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:251]: should we like ... sort it?

Comment (matanlurey) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:251]: In theory it is sorted here:

https://github.com/flutter/flutter/blob/9ffdd3a0ecfa94b94a2fa856fc94e4fcbb2f50c6/packages/flutter_tools/lib/src/flutter_plugins.dart#L1107-L1108

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:251]: good enough for me

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by matanlurey** [comment]
I will be OOO tomorrow, so folk can feel free to take over this PR/make changes to it if they want it submitted before Tuesday.

File: packages/flutter_tools/test/general.shard/plugins_test.dart [hunk 2]
```diff
@@ -628,6 +632,78 @@ dependencies:
...
+        },
+        overrides: <Type, Generator>{
+          CocoaPods: () => cocoaPods,
+          FileSystem: () => fs,
+          ProcessManager: () => FakeProcessManager.any(),
+          SystemClock: () => systemClock,
+          FlutterVersion: () => flutterVersion,
+          Pub: FakePubWithPrimedDeps.new,
+          // TODO(matanlurey): Remove as part of https://github.com/flutter/flutter/issues/160257.
+          // Not necessary, you can observe this bug by calling `generateLegacyPlugins: false`,
```
Comment (loic-sharma) [inline packages/flutter_tools/test/general.shard/plugins_test.dart:700]: Silly nitpick: consider adding links to https://github.com/flutter/flutter/issues/162399 and https://github.com/flutter/flutter/issues/163272 as we'll forget what "this bug" was :)

**Review by loic-sharma — APPROVED** [review]
Good catch, nice fix, excellent test 🚀

**Review by vashworth — APPROVED** [review]
