### PR TITLE
Document that SearchDelegate.buildResults can be called multiple time…

### LINKED ISSUE #26759: Document that SearchDelegate.buildResults can be called multiple times
## Steps to Reproduce

Edit the buildResults function in search_demo.dart in flutter gallery
```dart
  int count = 0;
  @override
  Widget buildResults(BuildContext context) {
    final int searched = int.tryParse(query);
    if (searched == null || !_data.contains(searched)) {
      return Center(
        child: Text(
          '"$query"\n is not a valid integer between 0 and 100,000.\nTry again.',
          textAlign: TextAlign.center,
        ),
      );
    }
    count += 1;
    print('count: $count');
    return ListView(
      children: <Widget>[
        _ResultCard(
          title: 'This integer',
          integer: searched,
          searchDelegate: this,
        ),
        _ResultCard(
          title: 'Next integer',
          integer: searched + 1,
          searchDelegate: this,
        ),
        _ResultCard(
          title: 'Previous integer',
          integer: searched - 1,
          searchDelegate: this,
        ),
      ],
    );
  }
```
Then run the flutter gallery example app and go to the material/search_demo page, search for any number. You can see that added print statement is called twice:
```bash
[+6761 ms] I/flutter (10784): count: 1
[  +35 ms] I/flutter (10784): count: 2
```

## Logs

```
```

```
```

[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /usr/local/google/home/jiexinguo/flutter/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/google/home/jiexinguo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /usr/local/google/home/jiexinguo/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /usr/local/google/home/jiexinguo/Android/android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.

```
```

### PR DESCRIPTION
**Pull request by guojiex**
Document that SearchDelegate.buildResults can be called multiple times, to avoid confusion.

Fixed https://github.com/flutter/flutter/issues/26759.

### CODE REVIEW

**Comment by guojiex** [comment]
build test fail because helloworld build failed?

Failed to install the following Android SDK packages as some licences have not been accepted.

https://cirrus-ci.com/task/6048976371449856

```bash
[   +4 ms] Resolving dependencies... (completed)
[   +3 ms] * Error running Gradle:
           ProcessException: Process "/tmp/flutter sdk/examples/hello_world/android/gradlew" exited abnormally:
           Starting a Gradle Daemon (subsequent builds will be faster)
           > Configure project :app
           Checking the license for package Android SDK Build-Tools 28.0.3 in /opt/android_sdk/licenses
           Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
           Checking the license for package Android SDK Platform 27 in /opt/android_sdk/licenses
           Warning: License for package Android SDK Platform 27 not accepted.
           FAILURE: Build failed with an exception.
           * Where:
           Build file '/tmp/flutter sdk/examples/hello_world/android/build.gradle' line: 24
           * What went wrong:
           A problem occurred evaluating root project 'android'.
           > A problem occurred configuring project ':app'.
              > Failed to install the following Android SDK packages as some licences have not been accepted.
                   platforms;android-27 Android SDK Platform 27
                   build-tools;28.0.3 Android SDK Build-Tools 28.0.3
                To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
                Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
                Using Android SDK: /opt/android_sdk
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           * Get more help at https://help.gradle.org
           BUILD FAILED in 29s
             Command: /tmp/flutter sdk/examples/hello_world/android/gradlew app:properties
```

**Comment by guojiex** [comment]
Since the checks are all passed, can someone merge my pull request? Thanks!

File: examples/flutter_gallery/lib/demo/material/search_demo.dart [hunk 1]
```diff
@@ -133,6 +133,12 @@ class _SearchDemoState extends State<SearchDemo> {
   }
 }
 
+/// [SearchDelegate.buildResults] might be called multiple times. Please cache
+/// the search result if you don't want to call search backend multiple times
+/// on the same query.
+/// See:
```
Comment (HansMuller) [inline examples/flutter_gallery/lib/demo/material/search_demo.dart]: We usually don't include issue references like this in doc comments.

File: packages/flutter/lib/src/material/search.dart [hunk 2]
```diff
@@ -108,6 +108,13 @@ abstract class SearchDelegate<T> {
   /// The current value of [query] can be used to determine what the user
   /// searched for.
   ///
+  /// Note that this method might be called multiple times just like any other
+  /// build function in Flutter. Please cache the search results if you don't
+  /// want to call search backend multiple times on the same query.
+  /// See:
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/search.dart]: We usually don't include issue references like this in API doc comments.

File: packages/flutter/lib/src/material/search.dart [hunk 3]
```diff
@@ -108,6 +108,13 @@ abstract class SearchDelegate<T> {
   /// The current value of [query] can be used to determine what the user
   /// searched for.
   ///
+  /// Note that this method might be called multiple times just like any other
+  /// build function in Flutter. Please cache the search results if you don't
+  /// want to call search backend multiple times on the same query.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/search.dart]: A computationally expensive [buildResults] method might not contact a "search backend" (network service). We can only suggest caching here, since exactly what to cache and when will depend on the app. How about this:

This method might be applied more than once to the same query. If your [buildResults] method is computationally expensive, you may want to cache the search results for one or more queries.

File: examples/flutter_gallery/lib/demo/material/search_demo.dart [hunk 4]
```diff
@@ -133,6 +133,12 @@ class _SearchDemoState extends State<SearchDemo> {
   }
 }
 
+/// [SearchDelegate.buildResults] might be called multiple times. Please cache
```
Comment (HansMuller) [inline examples/flutter_gallery/lib/demo/material/search_demo.dart]: There's no need to reproduce the API doc in the demo.

**Review by HansMuller — CHANGES_REQUESTED** [review]
Thanks for your contribution and my apologies for the length of time it has taken to review it.

File: examples/flutter_gallery/lib/demo/material/search_demo.dart (hunk 1 above)
Comment (guojiex) [reply examples/flutter_gallery/lib/demo/material/search_demo.dart]: Removed.

File: packages/flutter/lib/src/material/search.dart (hunk 2 above)
Comment (guojiex) [reply packages/flutter/lib/src/material/search.dart]: Done.

File: packages/flutter/lib/src/material/search.dart (hunk 3 above)
Comment (guojiex) [reply packages/flutter/lib/src/material/search.dart]: Done.

File: examples/flutter_gallery/lib/demo/material/search_demo.dart (hunk 4 above)
Comment (guojiex) [reply examples/flutter_gallery/lib/demo/material/search_demo.dart]: Removed.

**Review by HansMuller — APPROVED** [review]

**Comment by HansMuller** [comment]
LGTM, thanks for the contribution! Once the preliminary tests have passed I will land this PR.

Once the PR has landed in the repo it will start running the final testing gauntlet. You can watch its status here: https://flutter-dashboard.appspot.com/build.html
