### PR TITLE
Fix SelectionArea select-word edge cases

### LINKED ISSUE #132821: A Positioned FilledButton make the Text inside a Stack unselectable
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Upgrade to flutter 3.13. 
Run the code sample on chrome, try selecting the text in the ListView.

### Expected results

The text should be selectable.

### Actual results

The text is not selectable until I removed the `Filledbutton` and hot restart.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return SelectionArea(
      child: Scaffold(
        body: Stack(
          children: [
            ListView.builder(
              itemCount: 999,
              itemBuilder: (BuildContext context, int index) {
                return Text(index.toString());
              },
            ),
            Positioned(
              left: 0,
              right: 0,
              bottom: 0,
              child: FilledButton(
                onPressed: () {},
                child: const Text('Press'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d
    darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change fixes issues with screen order comparison logic when rects are encompassed within each other. This was causing issues when trying to select text that includes inline `WidgetSpan`s inside of a `SelectionArea`.

* Adds `boundingBoxes` to `Selectable` for a more precise hit testing region.

Fixes #132821
Fixes updating selection edge by word boundary when widget spans are involved.
Fixes crash when sending select word selection event to an unselectable element.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -1717,23 +1754,29 @@ class _SelectableFragment with Selectable, ChangeNotifier implements TextLayoutM
...
+      return SelectionResult.forward;
+    }
 
     final TextPosition position = paragraph.getPositionForOffset(paragraph.globalToLocal(globalPosition));
     if (_positionIsWithinCurrentSelection(position) && _textSelectionStart != _textSelectionEnd) {
       return SelectionResult.end;
     }
     final _WordBoundaryRecord wordBoundary = _getWordBoundaryAtPosition(position);
-    if (wordBoundary.wordStart.offset < range.start && wordBoundary.wordEnd.offset < range.start) {
+    if (wordBoundary.wordStart.offset < range.start && wordBoundary.wordEnd.offset <= range.start) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/rendering/paragraph.dart:1769]: This change was made to handle the case when `SelectWordSelectionEvent` is dispatched with a position that is on a placeholder in the text. In this case `_getWordBoundaryAtPosition` may return the range of the placeholder which touches the edges of the selectable fragments range.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -2367,6 +2372,7 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
       final SelectionResult childResult = dispatchSelectionEventToChild(child, event);
       switch (childResult) {
         case SelectionResult.next:
+        case SelectionResult.forward:
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/selectable_region.dart:2375]: `SelectionResult.forward` is not returned by any of the edge update events at the moment so I choose to handle them here. I could also throw an unimplemented error here instead.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 3]
```diff
@@ -1843,13 +1843,13 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
   /// Returns positive if a is lower, negative if a is higher, 0 if their
   /// order can't be determine solely by their vertical position.
   static int _compareVertically(Rect a, Rect b) {
+    if ((a.top - b.top).abs() > _kSelectableVerticalComparingThreshold) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1846]: I noticed that on single-line text, the selectable fragment rects provided by `RenderParagraph` do not encompass each other even when split by `WidgetSpan`s. From my observation only on multi-line text is there some potential for encompassing rects.

This led me to move the rect top comparison first so that we don't immediately defer to horizontal comparison on multi-line text. Before this change we would immediately defer to horizontal comparison which is a little unreliable for encompassing rects that begin at the same `Offset`.

File: packages/flutter/lib/src/rendering/selection.dart [hunk 4]
```diff
@@ -53,6 +53,9 @@ enum SelectionResult {
   /// [SelectAllSelectionEvent], [ClearSelectionEvent], and
   /// [SelectWordSelectionEvent].
   none,
+  /// The selection may begin in this [Selectable], further selection should
+  /// continue to next [Selectable] in screen order.
+  forward,
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/rendering/selection.dart:58]: Still working on these docs.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1849]: This new logic fails on a single line text widget with a widget span, where the widget span has a greater height than the line.

File: packages/flutter/lib/src/rendering/selection.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/selection.dart:58]: What's the difference between next and forward?

**Review by chunhtai — COMMENTED** [review]
I wonder if there is a better way. The current proposed solution creates a special case handling between render paragraph and widget span.

An alternative I was thinking, but I am not sure if this will work or not is to let Selectable to return mutliple rects that covers exact text. In this case the first fragment will not contain the selectionWord position in the first place. However, this make it harder to calculate screen order.

File: packages/flutter/lib/src/rendering/selection.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/selection.dart:58]: I wanted to handle these two scenarios:
1. A paragraph is broken by a `WidgetSpan`, we are in the `Selectable` containing the first half of the paragraph before the `WidgetSpan` so walk to the next selectable to continue searching for the complete paragraph. In this case the delegate should set the `currentSelectionStartIndex` and continue walking through the selectable tree.
2. The paragraph range comes after the range contained by the `Selectable` so walk to the next selectable. In this case we continue walking through the selectable tree but the delegate should not set `currentSelectionStartIndex`.

I wanted some way to tell the delegate that the selection begins in the receiver of the event and we should continue walking through the selectable tree to find the rest of the selection. 

From the documentation of `SelectionResult.next`
`There is nothing left to select forward in this Selectable, and further selection should extend to the next Selectable in screen order.`
it sounds like it would be appropriate in this case, but then that would make `currentSelectionStartIndex` inaccurate since there is no way to differentiate between the two scenarios.

**Comment by Renzo-Olivares** [comment]
> I wonder if there is a better way. The current proposed solution creates a special case handling between render paragraph and widget span.
> 
> An alternative I was thinking, but I am not sure if this will work or not is to let Selectable to return mutliple rects that covers exact text. In this case the first fragment will not contain the selectionWord position in the first place. However, this make it harder to calculate screen order.

I'm also not the biggest fan of this proposal, but wanted to get the ball rolling.

Thanks for the suggestion, I think having the `Selectable` return multiple rects would work out. It would make calculating screen order more difficult but what if a `Selectable` provides the all encompassing `Rect` used to calculate screen order (what we have now), and provides some optional granular `Rect`s that can be used to more precisely detect if a position actually landed in a `Selectable`. From my testing this approach would work but it might make some logic O(n^2) if we are iterating through the selectable list and then iterating through the optional provided rects of the selectable. What do you think?

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 5]
```diff
@@ -277,6 +277,7 @@ class RenderParagraph extends RenderBox with ContainerRenderObjectMixin<RenderBo
     List<RenderBox>? children,
     Color? selectionColor,
     SelectionRegistrar? registrar,
+    bool? isInlineWidget,
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/paragraph.dart:280]: Yeah that makes sense. I think I'll try a different approach.

File: packages/flutter/lib/src/widgets/text.dart [hunk 6]
```diff
@@ -438,6 +438,7 @@ class Text extends StatelessWidget {
     this.textWidthBasis,
     this.textHeightBehavior,
     this.selectionColor,
+    this.isInlineWidget,
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text.dart:441]: The user would be responsible for this, but I think I will try a different approach.

**Comment by chunhtai** [comment]
> Thanks for the suggestion, I think having the `Selectable` return multiple rects would work out. It would make calculating screen order more difficult but what if a `Selectable` provides the all encompassing `Rect` used to calculate screen order (what we have now), and provides some optional granular `Rect`s that can be used to more precisely detect if a position actually landed in a `Selectable`. From my testing this approach would work but it might make some logic O(n^2) if we are iterating through the selectable list and then iterating through the optional provided rects of the selectable. What do you think?

I think the selectable should only provide granular rects to make the api cleaner, it will then be the sort algorithm to combine these rects for sorting.

The other alternative I can think of is to wrap text widget to be a selection container by itself. within the selection container, you can have more explicit control over selectable fragment ordering and event handling.

**Comment by Renzo-Olivares** [comment]
Hi @chunhtai apologies for the delay on this one. I went with adding the granular rects, mostly because I think we should have the precise region that covers the `Selectable` instead of a close approximation. Let me know what you think.

File: examples/api/lib/material/selectable_region/selectable_region.0.dart [hunk 7]
```diff
@@ -115,6 +115,16 @@ class _RenderSelectableAdapter extends RenderProxyBox with Selectable, Selection
 
   // Selectable APIs.
 
+  @override
+  List<Rect> get boundingBoxes => _boundingBoxes;
+  final List<Rect> _boundingBoxes = <Rect>[];
+
+  @override
+  Size computeDryLayout(BoxConstraints constraints) {
+    _boundingBoxes.add(Rect.fromLTWH(0.0, 0.0, constraints.maxWidth, constraints.maxHeight));
```
Comment (Renzo-Olivares) [inline examples/api/lib/material/selectable_region/selectable_region.0.dart:124]: Is this the best way to set the `boundingBox`?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 8]
```diff
@@ -1863,19 +1872,10 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
   static int _compareHorizontally(Rect a, Rect b) {
     // a encloses b.
     if (a.left - b.left < precisionErrorTolerance && a.right - b.right > - precisionErrorTolerance) {
-      // b ends before a.
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1866]: I added these in https://github.com/flutter/flutter/pull/127478 , but looking at them again I don't think they make sense. If a is encompassed by b then we can assume a is higher since it started before b. If b is encompassed by a then we can assume b is higher since it started before a.

File: examples/api/lib/material/selectable_region/selectable_region.0.dart [hunk 9]
```diff
@@ -115,6 +115,9 @@ class _RenderSelectableAdapter extends RenderProxyBox with Selectable, Selection
 
   // Selectable APIs.
 
+  @override
+  List<Rect> get boundingBoxes => <Rect>[paintBounds];
```
Comment (Renzo-Olivares) [inline examples/api/lib/material/selectable_region/selectable_region.0.dart:119]: Is this the best way to set the `boundingBox`? Or should it be based on the `size` `Rect.fromLTWH(0.0, 0.0, size.width, size.height)`?

File: packages/flutter/lib/src/rendering/selection.dart [hunk 10]
```diff
@@ -142,6 +142,10 @@ mixin Selectable implements SelectionHandler {
   /// The size of this [Selectable].
   Size get size;
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/selection.dart:143]: Is this still neededed if we we use boundingBoxes to locate the selectable?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 11]
```diff
@@ -1817,6 +1817,14 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
     _updateHandleLayersAndOwners();
   }
 
+  Rect _getBoundingBox(Selectable selectable) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1820]: If we merge before sorting, wouldn't we run into corner cases like before?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1820]: I realized this is probably come from my previous suggestions. I am not sure what the right answer is.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1820]: I think merging before sorting is okay, the corner cases we were running into were mostly due to some invalid logic I added into the logic that compares selectables, so the selectables were out of order. See https://github.com/flutter/flutter/pull/136920#discussion_r1419482870 .

Another issue was that even when the selectables are in order we would still hit selectables that did not actually contain the tapped global position. boundingBoxes solves this by giving us the precise rects to check against versus an all encompassing rect that we had before.

Take `Text before widgetspan [SelectableWidgetSpan] Text after widgetspan`.

We want to select something in `Text after widgetspan`.
 
SelectableA: `Text before widgetspan`
SelectableB: `[SelectableWidgetSpan]`
SelectableC: `Text after widgetspan`
Order: [SelectableA, SelectableB, SelectableC]

SelectableA's rect would encompass SelectableB and SelectableC. So a tap on either of those Selectables will always hit SelectableA first.

In the example above we would still hit SelectableA, and SelectableB before hitting SelectableC. SelectableA would return SelectionResult.next as expected, but the following SelectableB would not contain the global position at all so the iteration would stop there and never reach SelectableC. 

By iterating through the boundingBoxes we will now only hit SelectableC.

File: packages/flutter/lib/src/rendering/selection.dart (hunk 10 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/selection.dart:143]: The only reason I can think of for keeping this is that it is a nice convenience for the user to get the size of the Selectable without merging their own boxes. In the framework I think there's only one more usage of it, but that can be replaced by merging the boxes and getting the size. I'm leaning more towards keeping it, but don't feel strongly either way. What do you think?

File: examples/api/lib/material/selectable_region/selectable_region.0.dart (hunk 9 above)
Comment (chunhtai) [reply examples/api/lib/material/selectable_region/selectable_region.0.dart:119]: this looks fine

File: packages/flutter/lib/src/rendering/selection.dart (hunk 10 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/selection.dart:143]: I don't have strong preference as well. I am ok if we keep it for now. There is another project to implement search feature that may require more refactoring on the renderparagraph, we can decide whether we want to keep this field when we do that.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 11 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1820]: > SelectableA's rect would encompass SelectableB and SelectableC. So a tap on either of those Selectables will always hit SelectableA first.

How so? is the `Text before widgetspan` got broken into two lines?

**Review by chunhtai — APPROVED** [review]
LGTM just nits and some questions.

Another alternative I can think of without breaking changes are to break each sentence in between new lines into semantics fragment. This way you won't have cases where a selectable is complete encompassed another.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 11 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1820]: Oh yeah sorry forgot that detail. The example only makes sense if `Text before widgetspan` is on two lines.

We wouldn't run into this issue in the case where all Selectable fragments are on the same line because they do not overlap.

**Comment by Renzo-Olivares** [comment]
> LGTM just nits and some questions.
> 
> Another alternative I can think of without breaking changes are to break each sentence in between new lines into semantics fragment. This way you won't have cases where a selectable is complete encompassed another.

That sounds like it could work, but I think we would also have to do it for soft wraps and new lines if I understand correctly since sometimes a line will not end of a new line. I'm not sure we have a way to detect soft wraps?

I think I'm leaning towards `boundingBoxes` since it is a more general solution that applies to any `Selectable`, where the alternative would be private to `RenderParagraph`.

**Comment by chunhtai** [comment]
> That sounds like it could work, but I think we would also have to do it for soft wraps and new lines if I understand correctly since sometimes a line will not end of a new line. I'm not sure we have a way to detect soft wraps?
> 
> I think I'm leaning towards `boundingBoxes` since it is a more general solution that applies to any `Selectable`, where the alternative would be private to `RenderParagraph`.

Right, I forgot there isn't a good API to get softwrap and ellipsis. current approach lgtm then
