### PR TITLE
Fix the breaking of multi-code-unit characters in obscure mode

### LINKED ISSUE #122381: [macOS][desktop]: Deleting emojis from textfield with obscured text causes crash
### Steps to Reproduce
1. Execute `flutter run` on the code sample
2. focus the text field -> cursor is blinking in the text field
3. write an emoji
   a. Open the Emoji & symbols popup  
image
   b. Select an emoji and click it
image
   c. the text field now contains 2 obscuring characters and blinking cursor after them
4. press back-space key to delete from the 

**Expected results:** the characters are deleted from the text field

**Actual results:** app crashes

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
        home: Scaffold(body: TextField(obscureText: true)));
  }
}
```

</details>

<details>
  <summary>Crash log</summary>

```
2023-03-10 09:45:11.420 flutter_testing[38778:1183562] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid JSON message, decoding failed'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a37b43e8 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a32feea8 objc_exception_throw + 60
	2   Foundation                          0x00000001a46f7910 -[NSCalendarDate initWithCoder:] + 0
	3   FlutterMacOS                        0x0000000107e3c51c -[FlutterJSONMessageCodec decode:] + 540
	4   FlutterMacOS                        0x0000000107e3cc54 -[FlutterJSONMethodCodec decodeMethodCall:] + 112
	5   FlutterMacOS                        0x0000000107e3a670 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 80
	6   FlutterMacOS                        0x00000001071821dc -[FlutterEngine engineCallbackOnPlatformMessage:] + 424
	7   FlutterMacOS                        0x0000000107a58bb0 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZ23FlutterEngineInitializeE4$_30NS_9allocatorIS2_EEFvNS_10unique_ptrIN7flutter15PlatformMessageENS_14default_deleteIS7_EEEEEEclEOSA_ + 132
	8   FlutterMacOS                        0x0000000107a683f4 _ZN7flutter20PlatformViewEmbedder21HandlePlatformMessageENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 76
	9   FlutterMacOS                        0x0000000107a68e54 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter20PlatformViewEmbedder30EmbedderPlatformMessageHandler21HandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14default_deleteIS9_EEEEEUlvE_EENS_9allocatorISE_EEFvvEEclEv + 80
	10  FlutterMacOS                        0x0000000107a65568 _ZN7flutter18EmbedderTaskRunner8PostTaskEy + 616
	11  FlutterMacOS                        0x0000000107a4d50c FlutterEngineRunTask + 48
	12  FlutterMacOS                        0x00000001071844d4 -[FlutterEngine runTaskOnEmbedder:] + 56
	13  FlutterMacOS                        0x0000000107184690 __60-[FlutterEngine postMainThreadTask:targetTimeInNanoseconds:]_block_invoke + 64
	14  libdispatch.dylib                   0x00000001a34d09dc _dispatch_call_block_and_release + 32
	15  libdispatch.dylib                   0x00000001a34d2504 _dispatch_client_callout + 20
	16  libdispatch.dylib                   0x00000001a34e0d1c _dispatch_main_queue_drain + 928
	17  libdispatch.dylib                   0x00000001a34e096c _dispatch_main_queue_callback_4CF + 44
	18  CoreFoundation                      0x00000001a377ad40 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
	19  CoreFoundation                      0x00000001a37387c0 __CFRunLoopRun + 2036
	20  CoreFoundation                      0x00000001a3737878 CFRunLoopRunSpecific + 612
	21  HIToolbox                           0x00000001ace17fa0 RunCurrentEventLoopInMode + 292
	22  HIToolbox                           0x00000001ace17de4 ReceiveNextEventCommon + 672
	23  HIToolbox                           0x00000001ace17b2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
	24  AppKit                              0x00000001a69bd84c _DPSNextEvent + 632
	25  AppKit                              0x00000001a69bc9dc -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
	26  AppKit                              0x00000001a69b0e0c -[NSApplication run] + 464
	27  AppKit                              0x00000001a6988250 NSApplicationMain + 880
	28  flutter_testing                     0x00000001043df958 main + 12
	29  dyld                                0x00000001a332fe50 start + 2544
)
libc++abi: terminating with uncaught exception of type NSException
Lost connection to device.
```
</details>
<details>

<summary>Reproduced on</summary>

```
[✓] Flutter (Channel main, 3.9.0-1.0.pre.145, on macOS 13.2.1 22D68 darwin-arm64, locale en-SE)
```
```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-SE)
```
Cannot reproduce on Android.
</details>

<details>
<summary>Screen recording showing the issue</summary>

https://user-images.githubusercontent.com/1954891/224268456-a9de35c5-6572-4e0e-9163-3ab83fb331bd.mp4
</details>

### PR DESCRIPTION
**Pull request by justinmc**
This PR changes the character boundary behavior of obscured fields to be based on code points instead of code units.

So it used to be possible to traverse and delete obscured text inside of code points (and breaking a code point like that would cause a crash):

output2

But now moving the cursor and deleting is based on code points:

output1

### Native behavior

Native iOS deletes part of the emoji, native Mac deletes the whole emoji.  See https://github.com/flutter/flutter/issues/122381#issuecomment-1482042620.  So it's unclear what the desired behavior should actually be.

### Resources

Fixes https://github.com/flutter/flutter/issues/122381

I thought this might not fix the case where a broken emoji is directly pasted into the field, but it seems to work by trying this:  �‍👩‍👦‍👦

CC @LongCatIsLooong

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
It makes sense to me that we should remove the entire emoji when pressing delete since I'm not sure what a user would expect if only a portion of it is deleted in a password field. I do wonder why `_CodeUnitBoundary` was used vs `CharacterBoundary` in the case on an `obscure` field maybe there are some cases where it is needed. Looking at the failing tests it looks like this causes some unexpected changes.

**Comment by LongCatIsLooong** [comment]
This is a bit concerning that the whole emoji gets deleted, other people would easily be able to tell there are zwjs in the password. I think the problem isn't with "complex" characters, the crash is likely caused by surrogate pairs being broken up and the crash happens because it isn't valid encoding.

**Comment by justinmc** [comment]
Taking a look to see if I can turn this PR around, I'll make a decision on it by EOD today.

**Comment by justinmc** [comment]
I forgot about this PR, but I played around with it today and I think I have a solution.  Will put this in draft mode and open it for review soon.

**Comment by justinmc** [comment]
Sorry this PR's history got messed up by the autoroller somehow...  I've fixed it now.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM with some small nits, also looks like some tests are failing

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -5076,21 +5076,87 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+    // [a|a]b
+    // a[b|b]
+    return surroundingCodeUnits.runes.length == 1;
+  }
+
   @override
-  int getLeadingTextBoundaryAt(int position) => position.clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getLeadingTextBoundaryAt(int position) {
+    if (position > _text.length) {
+      // Nonsense.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5126]: I put it there on purpose at the time, but looking back I guess it's actually pretty useless as a comment haha.  I'll remove it.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -5076,21 +5076,87 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+    // [a|b]c
+    // [a|a]b
+    // a[b|b]
+    return surroundingCodeUnits.runes.length == 1;
+  }
+
   @override
-  int getLeadingTextBoundaryAt(int position) => position.clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getLeadingTextBoundaryAt(int position) {
+    if (position > _text.length) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Yup good call.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -5076,21 +5076,79 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+///  * [CharacterBoundary], which is a [TextBoundary] like this class, but whose
+///    boundaries are graphemes instead of code points.
+class _CodePointBoundary extends TextBoundary {
+  const _CodePointBoundary(this._text);
 
   final String _text;
 
+  // Returns true if the given position falls in the middle of a single code
+  // point in _text.
+  bool _breaksCodePoint(int position) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5105]: Looks like this function tests whether `position` points to a low surrogate? If that's the case maybe name it as such. Also it's probably easier to just `return _text[position] & 0xFC00 == 0xDC00`.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -5076,21 +5076,79 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+    // [a|b]c
+    // [a|a]b
+    // a[b|b]
+    return surroundingCodeUnits.runes.length == 1;
+  }
+
   @override
-  int getLeadingTextBoundaryAt(int position) => position.clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getLeadingTextBoundaryAt(int position) {
+    if (position > _text.length || position < 0) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5125]: If position == _text.length looks like this is going to throw.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: The documentation promises to return the closest index <= `position` that points to the start of a code point. So when position > _text.length it is supposed to return `getLeadingAt(_text.length - 1)`.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5105]: It also requires that the following code unit is a high surrogate.  So in other words, it returns true if `position` is in the middle of a surrogate pair.

I'm changing it to this, let me know what you think:

```dart
  // Returns true if the given position falls in the center of a surrogate pair.
  bool _breaksSurrogatePair(int position) {
    assert(position > 0 && position < _text.length && _text.length > 1);
    return _text.codeUnitAt(position) & 0xFC00 == 0xDC00
        && _text.codeUnitAt(position + 1) & 0xFC00 == 0xD800;
  }
```

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good catch.  I think I've cleaned up these edge cases in [b4c9c47](https://github.com/flutter/flutter/pull/123366/commits/b4c9c4758fcd70d037c5a1646f99595e56da2fdc) now.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart]: In UTF16 encoding a surrogate pair has exactly 2 code units, a high surrogate followed by a low surrogate. Otherwise it's an encoding error. I think you meant to check if `position` points to a low surrogate?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -5076,21 +5076,69 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+  bool _breaksSurrogatePair(int position) {
+    assert(position > 0 && position < _text.length && _text.length > 1);
+    return _text.codeUnitAt(position) & 0xFC00 == 0xDC00
+        && _text.codeUnitAt(position + 1) & 0xFC00 == 0xD800;
+  }
+
   @override
-  int getLeadingTextBoundaryAt(int position) => position.clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getLeadingTextBoundaryAt(int position) {
+    final int validatedPosition = math.min(math.max(position, 0), _text.length);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5112]: for `position < 0` it needs to return `null` since there won't be any index that is less than or equal to `position` and points to a code point start position.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:5112]: Maybe something like this:
```dart
    return switch (position) {
      < 0                              => null,
      _ when position >= _text.length  => getLeadingTextBoundaryAt(_text.length - 1),
      _ when _isLowSurrogate(position) => position - 1,
      _                                => position,
    };
```
iirc it's guaranteed that `_text` isn't a malformed utf16 string

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Whoops yes, I had that backwards and I was using `position` incorrectly.  I've fixed it and the tests seem to pass now.

I also reused this same low/high surrogate logic from TextPainter by making two methods public.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I added the `null` cases and cleaned it up a bit.  I really wanted to include the cool new pattern matching but ended up going with `if`s haha.

I just tried using `tester.enterText` to enter `👨‍|👩‍�` and it called getLeadingTextBoundaryAt with the malformed string, so I left the handling in for mismatched surrogates.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -5076,21 +5076,76 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+        && TextPainter.isLowSurrogate(_text.codeUnitAt(position));
+  }
+
   @override
-  int getLeadingTextBoundaryAt(int position) => position.clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getLeadingTextBoundaryAt(int position) {
+    if (position < 0) {
+      return null;
+    }
+    if (position == 0) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5115]: Looks like when `position == 0` it's always going to return 0 even when the text is empty?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -5076,21 +5076,76 @@ class _ScribblePlaceholder extends WidgetSpan {
...
+      return 0;
+    }
+    if (position >= _text.length) {
+      return _text.length;
+    }
+    if (_text.length <= 1) {
+      return position;
+    }
+
+    return _breaksSurrogatePair(position)
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5125]: If `position` points to a high surrogate the method should return `position`?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: Yes.  If `position` points to a high surrogate then _breaksSurrogatePair will return false, and `position` will be returned.  This is correct because `position` is always a code point boundary when it points to a high surrogate.

Let me know if I have anything wrong there.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5115]: Good point, I guess we should be returning null when the text is empty?  I've pushed a commit to do that for both leading/trailing.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 8]
```diff
@@ -991,17 +991,27 @@ class TextPainter {
...
-  static bool _isHighSurrogate(int value) {
+  /// Returns true iff the given value is a valid UTF-16 high (first) surrogate.
+  /// The value must be a UTF-16 code unit, meaning it must be in the range
+  /// 0x0000-0xFFFF.
+  ///
+  /// See also:
+  ///   * https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF
+  ///   * [isLowSurrogate], which checks the same thing for low (second)
+  /// surrogates.
+  static bool isHighSurrogate(int value) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:1002]: nit: maybe assert `value` is in the correct range?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: Ah I see _breaksSurrogatePair also checks for `position - 1`. It's probably not necessary since the program would have crashed before getting here if the string isn't valid UTF16. That would simplify the logic in this method too.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 9]
```diff
@@ -5076,21 +5076,76 @@ class _ScribblePlaceholder extends WidgetSpan {
...
   @override
-  int getTrailingTextBoundaryAt(int position) => (position + 1).clamp(0, _text.length); // ignore_clamp_double_lint
+  int? getTrailingTextBoundaryAt(int position) {
+    if (position >= _text.length) {
+      return null;
+    }
+    if (position < 0) {
+      return 0;
+    }
+    if (position == _text.length - 1) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:5138]: By defninition, if the last code unit is a low surrogate then `getTrailingTextBoundaryAt(_text.length - 1)` should return null?

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart:1002]: I just tried this on your suggestion, but then realized that there were a million test failures.  I think these methods check lots of code units that are not necessarily surrogates.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: It seems possible to get here with a malformed string, at least in some cases.  I added a malformed string test that seems to pass on linux, let's see if it passes on other platforms.  Also, I can paste a malformed string (`👨‍👩‍�`) into the app on Linux without a crash.

Maybe we should be checking for this kind of thing somewhere.

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 8 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:1002]: sorry I meant valid UTF16 code range 0x0 – 0xFFFFF

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5138]: I thought it was right as-is, but let me know if I'm misunderstanding.  An example would be the string `'👨'`, a valid surrogate pair, where the last code unit is a low surrogate.  If `position` is in the center of that surrogate pair, then the trailing boundary is at the end of the string, right?

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart:1002]: Ohh agreed, I'll do that!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: oh interesting. Do you mind adding a test case for that?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 9 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:5138]: This method should return the next start index of a code point AFTER `position`. There's nothing after the last code unit so `null` should be returned?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5138]: We talked offline and decided that it is possible to return `_text.length` here.  I've updated the docs to explicitly state this in [754a3b0](https://github.com/flutter/flutter/pull/123366/commits/754a3b01d9706ab6c0a0840155f6b7a9829d664c).

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:5125]: Here's my test ("when inserting a malformed string"): https://github.com/flutter/flutter/pull/123366/files#diff-37dc3ce295078607fe561c83f2ae43fd77eb7b6aead39e5ed57d7fa9cf7525d7R16315

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 10]
```diff
@@ -16091,6 +16091,284 @@ testWidgets('Floating cursor ending with selection', (WidgetTester tester) async
...
+          ),
+          style: textStyle,
+          cursorColor: cursorColor,
+          selectionControls: materialTextSelectionControls,
+        ),
+      ),
+    );
+
+    await tester.tap(find.byType(EditableText));
+    await tester.enterText(find.byType(EditableText), '👨‍👩‍�');
```
Comment (LongCatIsLooong) [inline packages/flutter/test/widgets/editable_text_test.dart:16337]: could you add a comment to explain what code unit is this? I can't really copy that since it's rendered as `0xFFFD`

Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_test.dart:16337]: Also what happens if there's a sequence of high surrogates or low surrogates?

Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_test.dart]: Good call.  In [cacb4fc](https://github.com/flutter/flutter/pull/123366/commits/cacb4fc463d1452fb3fbda1867349d558f6a722a) I've replaced these crazy characters with their `\u` equivalents and left comments about where they come from.  I also added two tests, one with a series of high surrogates and one with a series of low surrogates.

**Review by LongCatIsLooong — APPROVED** [review]
