### PR TITLE
Change network image URL in doc

### LINKED ISSUE #25092: PNG link in our API doc is not working
The following app shows no image:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://github.com/flutter/flutter_gallery_assets/raw/master/lib/products/backpack.png',
        ),
      ),
    );
  }
}
```
while its JPG counterpart works fine:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://github.com/flutter/website/blob/master/src/_includes/code/layout/lakes/images/lake.jpg?raw=true',
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by liyuqian**
This fixes https://github.com/flutter/flutter/issues/25092

### CODE REVIEW

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -170,7 +170,7 @@ class Directionality extends InheritedWidget {
 ///
 /// ```dart
 /// Image.network(
-///   'https://github.com/flutter/flutter_gallery_assets/raw/master/lib/products/backpack.png',
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/basic.dart]: I'd rather not redirect this to the website: it's structure can change, and then this link will be broken. Can you use an image that's in the assets-for-api-docs repo instead, like maybe [this one](
https://github.com/flutter/assets-for-api-docs/blob/master/packages/diagrams/assets/blend_mode_destination.jpeg?raw=true)?

Also, what's the reason for this change?

**Review by gspencergoog — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/widgets/basic.dart (hunk 1 above)
Comment (liyuqian) [reply packages/flutter/lib/src/widgets/basic.dart]: Sure, done.

**Review by gspencergoog — APPROVED** [review]

**Comment by liyuqian** [comment]
The docs failure is bogus. I've rerun the docs test and I got two successful docs tests: 
image

I've no idea why the new successful tests won't overwrite the old failure.
