### PR TITLE
Changes to initialDate for CalendarDatePicker should update the state.

### LINKED ISSUE #64040: Not possible to update selected date from another source then the CalendarDatePicker
Hi, I'm trying to use a CalendarDatePicker in combination with buttons that have a predefined date on them. The date that is selected is stored in the state of the widget that has the CalendarDatePicker as its child. When the CalendarDatePicker updates its date by the user tapping a date, the variable outside gets updated. But if the user taps one of the buttons with a predefined date on it, the CalendarDatePicker does not get the updated value. I created this previous issue #60981, where the currentDate field was added. This allows you to update the current date and not the selected date which I need to be able to update using input outside of the CalendarDatePicker

## Steps to Reproduce

1. Start a new clean flutter project
2. Replace main.dart with code from below.
3. Run the app and use buttons to change the date.

**Expected results:**
I would expect the selected date in the CalendarDatePicker to update when tapping one of the buttons under it.

**Actual results:**
The CalendarDatePicker only updates its selected date when the user taps a date in the CalendarDatePicker widget.

<details>
<summary><b>flutter doctor -v</b></summary>
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\gaute.haugen\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\gaute.haugen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM G975F (mobile) • R58M16BWQWR • android-arm64 • Android 10 (API 29)

• No issues found!
</details>

<details>
<summary><b>Code</b></summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var date = DateTime.now().toUtc();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          CalendarDatePicker(
            initialDate: date ?? DateTime.now(),
            firstDate: DateTime(1970, 1, 1),
            lastDate: DateTime(2099, 31, 12),
            onDateChanged: (DateTime value) {  },
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.arrow_back),
                onPressed: () {
                  setState(() {
                    date = date.add(Duration(days: -1));
                  });
                },
              ),
              IconButton(
                icon: Icon(Icons.arrow_forward),
                onPressed: () {
                  setState(() {
                    date = date.add(Duration(days: 1));
                  });
                },
              )
            ],
          ),
          Text('Current date: ${date.toString()}'),
        ],
      )
    );
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

If the `initialDate` parameter of `CalendarDatePicker()` changes as the results of actions outside the picker, the new selected date and displayed month won't be updated. This PR fixes that.

## Related Issues

Fixes: #64040

## Tests

I added a new test to check for this API specifically.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them?

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/pickers/calendar_date_picker.dart [hunk 1]
```diff
@@ -169,9 +170,19 @@ class _CalendarDatePickerState extends State<CalendarDatePicker> {
     _selectedDate = widget.initialDate;
   }
 
+  @override
+  void didUpdateWidget(CalendarDatePicker oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    _mode = widget.initialCalendarMode;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/pickers/calendar_date_picker.dart:176]: It would be a little safer to factor this into _initWidgetState()

File: packages/flutter/lib/src/material/pickers/calendar_date_picker.dart [hunk 2]
```diff
@@ -169,9 +170,19 @@ class _CalendarDatePickerState extends State<CalendarDatePicker> {
...
+    _currentDisplayedMonthDate = DateTime(widget.initialDate.year, widget.initialDate.month);
+    _selectedDate = widget.initialDate;
+  }
+
   @override
   void didChangeDependencies() {
     super.didChangeDependencies();
+    assert(debugCheckHasMaterial(context));
+    assert(debugCheckHasMaterialLocalizations(context));
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/pickers/calendar_date_picker.dart:185]: Also `debugCheckHasDirectionality`? Here and below

**Review by HansMuller — APPROVED** [review]
LGTM
