### PR TITLE
Move embedding and linking Flutter frameworks into the tool

### LINKED ISSUE #32454: flutter build ios failing: ld: framework not found App
## Steps to Reproduce

I am running:

```
flutter build ios --release
```

Until recently, this worked. However, something is now broken and I'm having trouble identifying what. I have been trying to get Crashlytics working and I suspect it is related but it's unclear how.

## Logs

I have run a build with `--verbose` and have uploaded as a zip [here](https://github.com/flutter/flutter/files/3164674/build_log.zip) (output was too much for gist). I have redacted only the application name from the log.

This appears at several points in the log:
```
ld: framework not found App
```

But I suspect there is an underlying problem causing that.

`flutter doctor -v` output:
```
[✓] Flutter (Channel master, v1.5.9-pre.196, on Mac OS X 10.14.4 18E226, locale en-AU)
    • Flutter version 1.5.9-pre.196 at /Users/kent/Repository/flutter
    • Framework revision 9c77e8e8a0 (6 hours ago), 2019-05-09 12:43:51 -0700
    • Engine revision 644db5a49c
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.0

[✓] Connected device (1 available)
    • iPad • e9621f25ae14a6b0a4ad7d3eb0600bd2454564c0 • ios • iOS 12.1.4

! Doctor found issues in 1 category.
```
If you're wondering why I'm on `master`, it's because I've been going through hell trying to get an iOS build to actually complete without hanging/timeouts. That is now fixed on `master` so I'm there reluctantly until it makes its way into `dev` and beyond.

### LINKED ISSUE #50568: [App.framework] Linked and embedded framework 'App.framework' was built for iOS/iOS Simulator
## Steps to Reproduce

1. Prepare application for running
2. Run `flutter run` or `flutter run --debug`
3. Build fails

### Terminal Output

Screen Shot 2020-02-11 at 9 28 03 AM

### flutter doctor -v

```bash
➜ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.4 19E224g, locale en-CA)
    • Flutter version 1.12.13+hotfix.7 at /Users/jagandeepbrar/Development/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jagandeepbrar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.4, Build version 11N111s
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 8 Plus • 934E82BE-9245-43CC-8A33-9E17C8806E78 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

## Notes

This appears to have started since upgrading to Catalina 10.15.4 beta with Xcode 13.4 beta, which also updated Simulator to 13.4 (921.4).

The application compiles and runs correctly on a physically attached device, but no simulators of any devices can pass this stage.

EDIT: Just attempted both Flutter beta and dev channels, and the same error occurs after rebuilding the tools and running `flutter clean` in the project root.

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Xcode 11.4 changed its behavior to require linked and embedded frameworks (App.framework and Flutter.framework) to have the right architecture BEFORE the Flutter script can run.  So building against the simulator would work, then the next time building against a real device it would just fail:
```
Linked and embedded framework 'App.framework' was built for iOS Simulator
```
and vice versa from real device to simulator:
```
Linked and embedded framework 'App.framework' was built for iOS
```

### Observations
1. App.framework doesn't need to be linked since there are no symbols.
1. It would be better to push the linker and embedding logic down in the tool so we have more control.  For example, we could distribute a `Flutter.xcframework` and link on that without a breaking change.  Or name `App.framework` uniquely to support different add-to-app modules. Or we could move more things from xcode_backend into the tool.  Or we could update search paths to point directly to the right build mode engine artifacts directory without copying `Flutter.framework` into the project.
1. We keep needing to change the Xcode project file template (https://github.com/flutter/flutter/pull/33684, so many more examples).
1. Ideally this migration could be versioned, see https://github.com/flutter/flutter/issues/40460.  However this migration looks safe: there are unique identifiers!
1. Since it's not versioned, the migrator will run on every `flutter build ios`/`flutter run`!  However these migrations are really fast when there's no changes to make.

### Changes
- Remove App.framework and Flutter.framework link step in template build phase.
- Add `OTHER_LDFLAGS=$(inherited) -framework Flutter` to Generated.xcconfig and remove Flutter.framework from linking build phase (no need add for `App` since there are no symbols).
- Remove App.framework and Flutter.framework from the framework embedding build phase.
- Add migrators to do this automatically based on the Xcode identifiers.  I confirmed these are the original template identifiers (first Flutter.framework was #4820 and App.framework was #8971).
- Add error message and temporary workaround instructions in case the migration failed:
```
 Your Xcode project requires migration. See https://github.com/flutter/flutter/issues/50568 for details.
 
 You can temporarily work around this issue by running:
  rm -rf ios/Flutter/App.framework
```
- Run the `SHARD=build_tests` and let all the examples migrate.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/50568
Fixes https://github.com/flutter/flutter/issues/32454

## Tests

ios_project_migration_test, updated xcodeproj_test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/bin/xcode_backend.sh [hunk 1]
```diff
@@ -296,13 +296,17 @@ EmbedFlutterFrameworks() {
   RunCommand cp -Rv -- "${flutter_ios_engine_folder}/Flutter.framework" "${xcode_frameworks_dir}/"
 
   # Sign the binaries we moved.
-  local identity="${EXPANDED_CODE_SIGN_IDENTITY_NAME:-$CODE_SIGN_IDENTITY}"
-  if [[ -n "$identity" && "$identity" != "\"\"" ]]; then
-    RunCommand codesign --force --verbose --sign "${identity}" -- "${xcode_frameworks_dir}/App.framework/App"
-    RunCommand codesign --force --verbose --sign "${identity}" -- "${xcode_frameworks_dir}/Flutter.framework/Flutter"
+  if [[ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]]; then
```
Comment (jmagman) [inline packages/flutter_tools/bin/xcode_backend.sh]: EXPANDED_CODE_SIGN_IDENTITY is more correct.

**Comment by evolvesoft-marwan** [comment]
I just ran into this issue. Was working with Android simulators for 10 days no issue, had to download and make space for Xcode 11.4-beta only to run into issue with error:

Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 424AXR4DHW
Xcode build done.                                            5.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    error: Building for iOS, but the linked and embedded framework 'App.framework' was built for iOS Simulator. (in target 'Runner' from project 'Runner')
Could not build the precompiled application for the device.

Error launching application on iPhone.
Exited (sigterm)

When will the patch for flutter be ready? Rough estimates?

Many thanks

**Comment by jmagman** [comment]
@evolvesoft-marwan we're working on it and don't have an estimate.  Hiding your comment to avoid noise on the review.

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -449,6 +453,20 @@ Future<void> diagnoseXcodeBuildFailure(XcodeBuildResult result) async {
...
   }
 
+  // Building for iOS Simulator, but the linked and embedded framework 'App.framework' was built for iOS.
+  // or
+  // Building for iOS, but the linked and embedded framework 'App.framework' was built for iOS Simulator.
+  if (result.stdout?.contains('Building for iOS') == true
+      && result.stdout?.contains('but the linked and embedded framework') == true
+      && result.stdout?.contains('was built for iOS') == true) {
+    globals.printError('');
+    globals.printError('Your Xcode project requires migration. See https://github.com/flutter/flutter/issues/50568 for details.');
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart]: This link is temporary.  I will write wiki or website instructions and update this link.

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+      }
+      if (line.contains('install! \'cocoapods\', :disable_input_output_paths => true')) {
+        return null;
+      }
+
+      return line;
+    });
+  }
+
+  void _processFileLines(File file, _ProjectFileLineProcessor processLine) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: Since this is a private member with a private typedef, I would instead do the function type inline:

```
void _processFileLines(File file, String Function(String) processLine)
```

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+  IOSProjectMigration(IosProject project, Logger logger) :
+        _xcodeProjectInfoFile = project.xcodeProjectInfoFile,
+        _podfile = project.podfile,
+        _logger = logger;
+
+  final File _xcodeProjectInfoFile;
+  final File _podfile;
+  final Logger _logger;
+
+  void run() {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: consider a better name, like `migrateProject` et cetera

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+// found in the LICENSE file.
+
+import '../base/file_system.dart';
+import '../base/logger.dart';
+import '../project.dart';
+
+// Return null if line should be deleted.
+typedef _ProjectFileLineProcessor = String Function(String line);
+
+class IOSProjectMigration {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: I would add some contextual top level information about why this class exists

**Review by jonahwilliams — COMMENTED** [review]
Follow up questions:

1. Did you use the flutter tool to migrate the examples in repo?

2. Do we need to make a similar change to the macOS project structure? If so, that doesn't need to be done now but it would be nice to have an issue for it.

3. Is there an issue filled for adding this information to the web site?

Re: migration time - I think this is okay provided that we're not overwriting the file if it isn't necessary. It doesn't look like this is the case in your code.

**Comment by jmagman** [comment]
> Follow up questions:
> 
> 1. Did you use the flutter tool to migrate the examples in repo?

Yes, all examples and tests were migrated by running `flutter build ios` in the right directory (or letting integration tests do it for me).

> 2. Do we need to make a similar change to the macOS project structure? If so, that doesn't need to be done now but it would be nice to have an issue for it.

I think it may be a good idea to do the same pattern for macOS for the future-proofing xcframework / App.framework rename reasons I mentioned in the "Observations" section.  However there's no immediate need to do this since Mac won't hit https://github.com/flutter/flutter/issues/50568 (there is no simulator, frameworks always have the x86 architectures, no thinning happens).  I would defer to @stuartmorgan on the necessity and/or timing of that change.

> 3. Is there an issue filled for adding this information to the web site?

https://github.com/flutter/website/issues/3741

> Re: migration time - I think this is okay provided that we're not overwriting the file if it isn't necessary. It doesn't look like this is the case in your code.

No, it doesn't overwrite the file unless there's a change.  See the "skipped if nothing to upgrade" `ios_project_migration_test` unit test.

**Comment by jonahwilliams** [comment]
Even if its not necessary, it would be nice to keep the macOS and iOS projects as similar as possible.

**Comment by jmagman** [comment]
Oh another thing: this migration will prevent users from downgrading Flutter versions to before this change since `OTHER_LDFLAGS` won't exist in past Generated.xcconfigs... I'm not quite sure how to help with that...

I could change the script build phase to first run embed, then run thin, since that's all the new `embed_and_thin` is doing.  `embed_and_thin` doesn't exist on past Flutter versions, but `embed` and `thin` do.

**Comment by jonahwilliams** [comment]
I would recommend that if you modify the project files, to take the old sources and save them as "*.old". Then the documentation on the website/wiki can explain how to restore the project by renaming them

File: examples/platform_view/ios/Runner.xcodeproj/project.pbxproj [hunk 6]
```diff
@@ -234,9 +222,12 @@
 			files = (
 			);
 			inputPaths = (
+				"${PODS_ROOT}/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh",
+				"${PODS_ROOT}/../Flutter/Flutter.framework",
 			);
 			name = "[CP] Embed Pods Frameworks";
 			outputPaths = (
+				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Flutter.framework",
```
Comment (stuartmorgan) [inline examples/platform_view/ios/Runner.xcodeproj/project.pbxproj]: Why do only some of the projects have these input/output path changes?

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+      const String thinBinaryScript = 'xcode_backend.sh\\" thin';
+      if (line.contains(thinBinaryScript)) {
+        return line.replaceFirst(thinBinaryScript, 'xcode_backend.sh\\" embed_and_thin');
+      }
+
+      return line;
+    });
+  }
+
+  void _migratePodfile() {
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: Breadcrumb for later reference: I think we can use this to fix https://github.com/flutter/flutter/issues/39659

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+    _migratePodfile();
+  }
+
+  void _migrateXcodeProjectInfoFile() {
+    if (!_xcodeProjectInfoFile.existsSync()) {
+      _logger.printTrace('Xcode project not found, skipping migration');
+      return;
+    }
+
+    _processFileLines(_xcodeProjectInfoFile, (String line) {
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: I'm looking at this class and thinking about what happens when we want to add a second migration for something else later; it seems like it'll become very hard to maintain/understand pretty quickly.

I think it would be helpful to design this up front so that instead of a single processor, it uses an array of processors. That way we can encapsulate each conceptual migration and keep them all from bleeding together over time. It would also mean we could run individual ones selectively (see later comment). I don't think it would add too much complexity, and it would make the next migration much easier to add in a maintainable way (vs us always deciding that it's not bad enough to refactor *this* time, but maybe next time...)

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 9]
```diff
@@ -91,6 +92,9 @@ Future<XcodeBuildResult> buildXcodeProject({
     return XcodeBuildResult(success: false);
   }
 
+  final IOSProjectMigration migration = IOSProjectMigration(app.project, globals.logger);
+  migration.migrate();
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/ios/mac.dart]: Couldn't we pretty easily use the `.metadata` file to keep track of migrations that we've done (say, with a UUID for each completed migration)?

In addition to efficiency over time, it also means that we won't accidentally fight users. E.g., if someone had their own unrelated reasons that they needed `disable_input_output_paths` in their podspec, they'd have a really bad time if we re-run on every build.

**Review by stuartmorgan-g — COMMENTED** [review]
It terms of the general approach to managing the framework, this looks good to me! And capturing from offline discussion, it has the added bonus that it should make it pretty easy to solve the debug/profile/release problem with `assemble` that @jonahwilliams had encountered previously, since we won't be bound by Xcode's limitation of needing a single known path to the Flutter framework.

My comments are actually about the specifics of we do the migration, rather than the end result.

File: examples/platform_view/ios/Runner.xcodeproj/project.pbxproj (hunk 6 above)
Comment (jmagman) [reply examples/platform_view/ios/Runner.xcodeproj/project.pbxproj]: CocoaPods adds this in their scripting, so it's present in apps that have iOS platform code in their plugins.

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart (hunk 7 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: I would love to move most of that logic into a Ruby helper script in the project (like xcode_backend) so it never has to be upgraded again https://github.com/flutter/flutter/issues/45197

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 9 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart]: I really wish we could wait until https://docs.google.com/document/d/1fPnpUI6gXE9PkNWuFoAW20m_sQ87ZSC1rrn_D7fxBvs/edit?ts=5e58625e#heading=h.pub7jnop54q0 was in place and use that instead of having a bunch of one-off migrators fighting each other... but we can't wait in this case.

File: examples/platform_view/ios/Runner.xcodeproj/project.pbxproj (hunk 6 above)
Comment (jmagman) [reply examples/platform_view/ios/Runner.xcodeproj/project.pbxproj]: (so projects that have Podfiles)

**Comment by jmagman** [comment]
I am going to remove the Podfile migration.  It's really a nice-to-have for performance, and as @stuartmorgan pointed out, there might be a legit reason for the user to want that behavior.  I'll keep the change to the template so new projects don't contain the hack and can take advantage of CocoaPod's caching.

@jonahwilliams I am not going to make a copy of the changed file to be rolled back.  I'm pretty confident that the identifier and script changes are conservative enough, and that's what source control is for.  And wouldn't ya know, there's precedent: https://github.com/flutter/flutter/pull/13011

**Comment by jmagman** [comment]
And documenting this change will be very critical, it looks like the migrator missed removing App.framework in complex_layout because https://github.com/flutter/flutter/pull/8974 following migration instructions in https://github.com/flutter/flutter/pull/8971, which had people manually add the framework, and thus we don't know their identifiers...

**Comment by jonahwilliams** [comment]
Yeah you're right on the version control front

**Comment by jonahwilliams** [comment]
For #8971, I'm going to guess that the vast majority of current flutter applications were not created pre 1.0

File: packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+      }
+
+      return line;
+    });
+
+    if (migrationFailure) {
+      // Print scary message if the user is on Xcode 11.4 or greater, or if Xcode isn't installed.
+      final bool xcodeIsInstalled = _xcode.isInstalled;
+      if(!xcodeIsInstalled || (_xcode.majorVersion > 11 || (_xcode.majorVersion == 11 && _xcode.minorVersion >= 4))) {
+        logger.printError('Your Xcode project requires migration. See https://github.com/flutter/flutter/issues/50568 for details.');
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart]: Migration fails in `complex_layout` since it was created pre 1.0 and was manually migrated with https://github.com/flutter/flutter/pull/8971.
```
complex_layout$ flutter build ios
Building flutter tool...
Running "flutter pub get" in complex_layout...                      0.5s
Building com.yourcompany.complexLayout for device (ios-release)...
Upgrading project.pbxproj
Your Xcode project requires migration. See https://github.com/flutter/flutter/issues/50568 for details.
Encountered error while building for device.
```

File: packages/flutter_tools/lib/src/ios/ios_project_migration.dart (hunk 8 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_project_migration.dart]: Done.

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 9 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart]: Since I removed the `disable_input_output_paths` change, I didn't implement migration versioning, but it really is a good idea.  I'd like to split it out into it's own change as part of the wider `flutter migrate` effort.  For now it's running on every run like https://github.com/flutter/flutter/pull/13011.

**Comment by jmagman** [comment]
Ready for review!

File: packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart (hunk 10 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart]: Consider adding an analytics event for a failed migration.

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 11]
```diff
@@ -87,6 +89,16 @@ Future<XcodeBuildResult> buildXcodeProject({
     return XcodeBuildResult(success: false);
   }
 
+  final List<IOSMigrator> migrators = <IOSMigrator>[
+    RemoveFrameworkLinkAndEmbeddingMigration(app.project, globals.logger, globals.xcode)
+  ];
+
+  for(final IOSMigrator migrator in migrators) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/mac.dart]:
```suggestion
  for (final IOSMigrator migrator in migrators) {
```

File: packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart [hunk 12]
```diff
@@ -0,0 +1,56 @@
...
+/// iOS project is generated from a template on Flutter project creation.
+/// Sometimes (due to behavior changes in Xcode, CocoaPods, etc) these files need to be altered
+/// from the original template.
+class IOSMigrator {
+  IOSMigrator(this.logger);
+
+  @protected
+  final Logger logger;
+
+  /// Returns success of migration. Skipped migrations should return true.
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart]: nit: word-smiting

```suggestion
  /// Returns whether migration was successful or was skipped.
```

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart (hunk 10 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/migrations/remove_framework_link_and_embedding_migration.dart]: https://github.com/flutter/flutter/issues/51817

File: packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+
+import 'package:meta/meta.dart';
+
+import '../../base/file_system.dart';
+import '../../base/logger.dart';
+
+/// iOS project is generated from a template on Flutter project creation.
+/// Sometimes (due to behavior changes in Xcode, CocoaPods, etc) these files need to be altered
+/// from the original template.
+class IOSMigrator {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart]: This would be a bit more idiomatic as an abstract base class
```dart
abstract class IOSMigrator {
  final Logger logger;

  bool migrate();

  String processLine(String line);

  void processFileLines(File file)  {
    // as before.
  }
}

// You can chain them together:
class IOSMigration {
  IOSMigration(this.migrators);

  final List<IOSMigrator> migrators;

  void run() {
    for (final IOSMigrator migrator in migrators) {
      if (!migrator.migrate()) {
        // This class would encapsulate logic for aborting/rolling-back the transaction.
      }
    } 
  }
}
```

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart]: Followup in https://github.com/flutter/flutter/pull/51879.

**Comment by cbracken** [comment]
This patch appears to have increased the `hello_world_ios__compile bytesrelease_size_bytes` from 8537475 bytes to 164814091 bytes.

image
