### PR TITLE
Generate only requested platform directories on create

### LINKED ISSUE #60023: [flutter_tools] [Project.ensureReadyForPlatformSpecificTooling] should be better documented
The `checkProjects` parameter is confusing. By looking at the name, it is hard to figure out what it does.
We should add some documentation to explain what this parameter does. If there is a better name we can give to this parameter, we should also do that.

### LINKED ISSUE #67346: flutter create --platforms web creates incorrect error
1. flutter create will immediately cause a warning about the old embedding
2. web support is supposed to be on the beta channel only, yet it is included in the `flutter create --help` output:

```
    --platforms                The platforms supported by this project. This argument only works when the --template is set to app or plugin. Platform folders (e.g. android/) will be generated in the target project. When adding platforms to a plugin project, the
                               pubspec.yaml will be updated with the requested platform. Adding desktop platforms requires the corresponding desktop config setting to be enabled.
                               [ios (default), android (default), windows (default), linux (default), macos (default), web (default)]
```
Either the help sections needs to be clearer, or it should not contain the `web` option.

## Steps to Reproduce

1. `flutter create -t app --platforms web flt_web_test`

## Logs

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

[flutter_create.log](https://github.com/flutter/flutter/files/5329953/flutter_create.log)

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.0 at /Users/ened/dev/flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (1 available)            
    • SebXr (mobile) • 000XXXX-xXXXXXXX • ios • iOS 14.0.1

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

The `android` (and `ios`) directories are incorrectly created during the plugin registrant generation step.  After a `flutter create` the only thing in `android` is `GeneratedPluginRegistrant.java` and the only thing in `ios` is `GeneratedPluginRegistrant.{h,m}`.
https://github.com/flutter/flutter/blob/345188d40e576ffb6c97fee60446af58b8c9965a/packages/flutter_tools/lib/src/project.dart#L860-L862
is guarded by a check if the `android` directory exists (it did, but only contained `GeneratedPluginRegistrant.java`) and returned `v1` because the app manifest didn't exist, and caused a confusing warning.

Avoid creating platform directories during the plugin registrant generation step, which bypasses the Android embedding version warning.

- For `flutter create -t app`, generate the directories/plugins only for the requested platforms.  
- For other commands that regenerate various files (plugins, create missing template files, etc), only do so in existing platform directories.
- Replace the `checkProject` concept by explicitly requesting platforms based on user flags, existing directories, and whether features are on, as appropriate.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/67346
Fixes https://github.com/flutter/flutter/issues/60023

Related:
https://github.com/flutter/flutter/pull/31342
https://github.com/flutter/flutter/pull/59507

## Tests

Added `--platform` app create tests.  Update existing plugin, project, cocoapods tests which already exercise these code paths.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/plugins.dart [hunk 1]
```diff
@@ -1145,11 +1145,12 @@ void _createPlatformPluginSymlinks(Directory symlinkDirectory, List<dynamic> pla
 /// Rewrites the `.flutter-plugins` file of [project] based on the plugin
 /// dependencies declared in `pubspec.yaml`.
 ///
-/// If `checkProjects` is true, then plugins are only injected into directories
-/// which already exist.
-///
 /// Assumes `pub get` has been executed since last change to `pubspec.yaml`.
-Future<void> refreshPluginsList(FlutterProject project, {bool checkProjects = false}) async {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/plugins.dart:1152]: `checkProjects` was never actually passed in, so was always `false`.

File: packages/flutter_tools/lib/src/commands/create.dart [hunk 2]
```diff
@@ -680,7 +687,15 @@ https://flutter.dev/docs/development/packages-and-plugins/developing-packages#pl
...
       );
-      await project.ensureReadyForPlatformSpecificTooling(checkProjects: pluginExampleApp);
+
+      await project.generateInitialPlatformSpecificTooling(
+        androidPlatform: templateContext['android'] as bool ?? false,
+        iosPlatform: templateContext['ios'] as bool ?? false,
+        linuxPlatform: templateContext['linux'] as bool ?? false,
+        macOSPlatform: templateContext['macos'] as bool ?? false,
+        windowsPlatform: templateContext['windows'] as bool ?? false,
+        webPlatform: templateContext['web'] as bool ?? false,
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/create.dart:697]: These templateContext values are only true if the corresponding feature is on.
https://github.com/flutter/flutter/blob/73301a35a22824edff155836461747d8e04d448d/packages/flutter_tools/lib/src/commands/create.dart#L423-L426

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 3]
```diff
@@ -672,75 +672,157 @@ void main() {
...
+    expect(projectDir.childDirectory('linux').existsSync(), false);
+    expect(projectDir.childDirectory('macos').existsSync(), false);
+    expect(projectDir.childDirectory('windows').existsSync(), false);
+    expect(projectDir.childDirectory('web').existsSync(), false);
   }, overrides: <Type, Generator>{
-    FeatureFlags: () => TestFeatureFlags(isLinuxEnabled: true),
+    FeatureFlags: () => TestFeatureFlags(),
   });
 
-  testUsingContext('app does not include Linux by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:680]: Moved to `app does not include desktop or web by default`

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 4]
```diff
@@ -672,75 +672,157 @@ void main() {
...
+    validatePubspecForPlugin(projectDir: projectDir.absolute.path, expectedPlatforms: const <String>[
+      'linux',
+    ], pluginClass: 'FlutterProjectPlugin',
+    unexpectedPlatforms: <String>['some_platform']);
   }, overrides: <Type, Generator>{
-    FeatureFlags: () => TestFeatureFlags(isLinuxEnabled: false),
+    FeatureFlags: () => TestFeatureFlags(isLinuxEnabled: true),
   });
 
-  testUsingContext('app does not include macOS by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:731]: Moved to `app does not include desktop or web by default`

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 5]
```diff
@@ -813,21 +915,6 @@ void main() {
     FeatureFlags: () => TestFeatureFlags(isWindowsEnabled: true),
   });
 
-  testUsingContext('app does not include Windows by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:816]: Moved to `app does not include desktop or web by default`

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 6]
```diff
@@ -672,75 +672,157 @@ void main() {
...
+    expect(projectDir.childDirectory('android').existsSync(), false);
+    expect(projectDir.childDirectory('ios').existsSync(), false);
+    expect(projectDir.childDirectory('windows').existsSync(), false);
+    expect(projectDir.childDirectory('macos').existsSync(), false);
+    expect(projectDir.childDirectory('web').existsSync(), false);
   }, overrides: <Type, Generator>{
     FeatureFlags: () => TestFeatureFlags(isLinuxEnabled: true),
   });
 
-  testUsingContext('plugin does not include Linux by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:715]: Moved to `plugin does not include desktop or web by default`

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 7]
```diff
@@ -763,22 +869,6 @@ void main() {
     FeatureFlags: () => TestFeatureFlags(isMacOSEnabled: true),
   });
 
-  testUsingContext('plugin does not include macOS by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:766]: Moved to `plugin does not include desktop or web by default`

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 8]
```diff
@@ -848,20 +959,31 @@ void main() {
     FeatureFlags: () => TestFeatureFlags(isWindowsEnabled: true),
   });
 
-  testUsingContext('plugin does not include Windows by default', () async {
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:851]: Moved to `plugin does not include desktop or web by default`

File: packages/flutter_tools/lib/src/project.dart [hunk 9]
```diff
@@ -229,38 +229,64 @@ class FlutterProject {
...
+  /// Re-generates project files necessary to make Gradle builds work on Android
+  /// and CocoaPods+Xcode work on iOS, for app and module projects only.
+  ///
+  /// Will not create project platform directories if they do not already exist.
+  Future<void> regeneratePlatformSpecificTooling() async {
+    return ensureReadyForPlatformSpecificTooling(
+      androidPlatform: android.existsSync(),
+      iosPlatform: ios.existsSync(),
+      // TODO(stuartmorgan): Revisit the conditions here once the plans for handling
+      // desktop in existing projects are in place.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/project.dart:241]: @stuartmorgan I moved the TODOs scattered around to reexamine the logic to this spot.  Let me know if you want it somewhere else, or need it reworded.

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 10]
```diff
@@ -672,75 +672,157 @@ void main() {
...
 
     final CreateCommand command = CreateCommand();
     final CommandRunner<void> runner = createTestCommandRunner(command);
 
-    await runner.run(<String>['create', '--no-pub', projectDir.path]);
+    await runner.run(
+        <String>['create', '--no-pub', '--template=plugin', projectDir.path]);
 
-    expect(projectDir.childDirectory('linux').childFile('CMakeLists.txt').existsSync(), false);
+    expect(projectDir.childDirectory('linux').existsSync(), false);
```
Comment (jonahwilliams) [inline packages/flutter_tools/test/commands.shard/permeable/create_test.dart:695]: FYI: this isn't used consistently but you can use `exists` or `isNot(exists)` from `package:file_testing`

File: packages/flutter_tools/lib/src/project.dart [hunk 11]
```diff
@@ -229,38 +229,64 @@ class FlutterProject {
     return manifest;
   }
 
+  /// Re-generates project files necessary to make Gradle builds work on Android
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/project.dart:232]: Is this comment misleading now? it also re-generates for desktop+web projects if they exist

**Review by jonahwilliams — COMMENTED** [review]
Only small nits, seems like a good change.


Why were we getting the warning about the android embedding though? even if the project wasn't there or was partially created, we should probably default to not showing a warning

**Comment by jmagman** [comment]
> Why were we getting the warning about the android embedding though? even if the project wasn't there or was partially created, we should probably default to not showing a warning

Before this PR the `android` (and `ios` directories) were incorrectly created during the plugin registrant generation step.  After a `flutter create` the only thing in `android` was `GeneratedPluginRegistrant.java` and the only thing in `ios` was `GeneratedPluginRegistrant.{h,m}`.
https://github.com/flutter/flutter/blob/345188d40e576ffb6c97fee60446af58b8c9965a/packages/flutter_tools/lib/src/project.dart#L860-L862
is guarded by a check if the `android` directory exists (it did, but only contained `GeneratedPluginRegistrant.java`) and returned `v1` because the app manifest didn't exist.

After this PR, the `android` directory is not created during the during the plugin registrant generation step, so the embedding version is never checked.

**Review by jonahwilliams — APPROVED** [review]
LGTM with nits

File: packages/flutter_tools/lib/src/project.dart (hunk 11 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/project.dart:232]: Good call, reworded.

**Review by cyanglaz — APPROVED** [review]
LGTM!

File: packages/flutter_tools/lib/src/project.dart (hunk 9 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/project.dart:241]: The TODO was really about figuring out what `checkProjects` was for and why we would ever want the `checkProjects = false` behavior since it seemed really bizarre, so it looks like this PR obsoletes it. But I can clean it up later.
