### PR TITLE
Fix _LazyWidgetProvider indexing, move Ali Connors

### LINKED ISSUE #2572: Date picker crashes when scrolling the months
To reproduce: run the date picker gallery demo, scroll the date picker's month view.

```
I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
I/flutter : The following exception was raised during performLayout():
I/flutter : RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
I/flutter : The following RenderObject was being processed when the exception was fired:
I/flutter : RenderList NEEDS-LAYOUT
I/flutter : This RenderObject had the following owner:
I/flutter : LazyListViewport ← Listener ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey 575382864] ← ScrollableLazyList ← MonthPicker ← ConstrainedBox ← Container ← Column ← ⋯
...
```

### PR DESCRIPTION
**Pull request by HansMuller**
Added a link to the flexible appbar demo to the Components demo section.

Fixes https://github.com/flutter/flutter/issues/2572

### CODE REVIEW

File: packages/flutter/lib/src/widgets/virtual_viewport.dart [hunk 1]
```diff
@@ -296,8 +296,5 @@ class _LazyWidgetProvider extends _WidgetProvider {
   }
 
   @override
-  Widget getChild(int i) {
-    int n = _length ?? _widgets.length;
-    return _widgets[(i % n).abs()];
-  }
+  Widget getChild(int i) => _widgets[i - _base];
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/virtual_viewport.dart]: What about when itemsWrap is true?  I guess that's the itemBuilder's problem?

**Comment by abarth** [comment]
LGTM

Please add a test for the _LazyWidgetProvider part.

**Comment by abarth** [comment]
Thanks!
