### PR TITLE
[flutter_tools] fix missing cmake

### LINKED ISSUE #88897: ProcessException: Failed to find "cmake" in the search path
Version: beta/2.5.0-5.2.pre
Command: `flutter build linux --release`

```
Thread 0 main threadProcessPackageException: ProcessException: Failed to find "cmake" in the search path.  Command: cmake 
at LocalProcessManager.start(local_process_manager.dart:58)
at ErrorHandlingProcessManager.start.<anonymous closure>(error_handling_io.dart:691)
at _run(error_handling_io.dart:567)
at ErrorHandlingProcessManager.start(error_handling_io.dart:690)
at _DefaultProcessUtils.start(process.dart:425)
at _DefaultProcessUtils.stream(process.dart:444)
at _runCmake(build_linux.dart:127)
at <asynchronous gap>(async)
at buildLinux(build_linux.dart:75)
at <asynchronous gap>(async)
at BuildLinuxCommand.runCommand(build_linux.dart:88)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1125)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:288)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:236)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:92)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/88897

Previously we were calling cmake and catching `ArgumentError` for the case where cmake was not installed. However, per #88897, it was actually throwing a `ProcessException`. Instead, explicitly check `processManager.canRun('cmake')` (rather than catching all `ProcessException`s), and if it is not runnable give the user the same `UserMessage` the doctor validator would.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]

File: packages/flutter_tools/lib/src/linux/build_linux.dart [hunk 1]
```diff
@@ -124,6 +124,9 @@ Future<void> _runCmake(String buildModeName, Directory sourceDir, Directory buil
   final bool needCrossBuildOptionsForArm64 = needCrossBuild
       && targetPlatform == TargetPlatform.linux_arm64;
   int result;
+  if (!globals.processManager.canRun('cmake')) {
+    throwToolExit(globals.userMessages.cmakeMissing);
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/linux/build_linux.dart:128]: Do you want to remove the `on ArgumentError` block? Or at least make it throw the same thing?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/linux/build_linux.dart:128]: good thinking

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/linux/build_linux.dart:128]: I removed the catch, as I'm assuming if we get an `ArgumentError` that means it's a tool bug.

Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/linux/build_linux.dart:128]: You can tell I wrote this code when I was less familiar with Dart. Otherwise the fact that I was catching an `Error` type in the first place would have been a big red flag that the code was wrong...
