### PR TITLE
Mac cmd + shift + left/right

### LINKED ISSUE #93883: Mac cmd + shift + arrow expand behavior
On Mac, cmd + shift + arrow left/right should expand the selection to the beginning/end of the current line, not pivot it.  Here's a recording of Flutter's current incorrect behavior and then the correct native TextEdit:

https://user-images.githubusercontent.com/389558/142479140-85a94b11-2fe9-44dc-a14d-5337c4199b2e.mov

This used to work before.  @LongCatIsLooong I believe your PR https://github.com/flutter/flutter/pull/90684 accidentally removed this behavior.  Sorry I should have caught it in code review or at least had a test to catch it.

### Steps to reproduce

  1. Run any app with any sort of text field with some text in it (example app below).
  2. Click to place the cursor somewhere in the middle of a line.
  3. Press cmd + shift + left arrow to select to the start of the line.
  4. Press cmd + shift + right arrow to select to the end of the line.

Expected behavior: The selection expands to include the entire line.
Actual behavior: The selection pivots to only include the original click point to the end of the line.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final TextEditingController _controller = TextEditingController(
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            children: <Widget>[
              TextField(
                controller: _controller,
                maxLines: 3,
                decoration: InputDecoration(
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(0.5),
                    gapPadding: 0.0,
                  ),
                  labelText: 'I am a label',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
Command + shift + left/right arrow should expand to the beginning/end of the line, not extend or pivot like other platforms.

Mac single line
```
words |words words
=>
words |words words|
<=
|words words words|
```

Other platforms single line
```
words |words words
=>
words |words words|
<=
|words |words words
```

Mac multi line
```
words |words words
words |words words
=>
words |words words
words words words|
<=
|words words words
words words words|
```

Mac single line
```
words |words words
=>
words |words words|
<=
|words words words|
```

Other platforms multi line
```
words |words words
words |words words
=>
words |words words
words words words|
<=
|words words words
|words words words
```

Fixes https://github.com/flutter/flutter/issues/93883#issuecomment-988744744

### CODE REVIEW

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 1]
```diff
@@ -307,8 +307,8 @@ class DefaultTextEditingShortcuts extends Shortcuts {
     const SingleActivator(LogicalKeyboardKey.arrowUp, meta: true): const ExtendSelectionToDocumentBoundaryIntent(forward: false, collapseSelection: true),
     const SingleActivator(LogicalKeyboardKey.arrowDown, meta: true): const ExtendSelectionToDocumentBoundaryIntent(forward: true, collapseSelection: true),
 
-    const SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true, meta: true): const ExtendSelectionToLineBreakIntent(forward: false, collapseSelection: false),
-    const SingleActivator(LogicalKeyboardKey.arrowRight, shift: true, meta: true): const ExtendSelectionToLineBreakIntent(forward: true, collapseSelection: false),
+    const SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true, meta: true): const ExtendSelectionToLineBreakIntent(forward: false, collapseSelection: false, expand: true),
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:310]: @LongCatIsLooong What do you think of adding this expand parameter here, or would it be better to do something like creating an all new intent?

File: packages/flutter/lib/src/widgets/text_editing_intents.dart [hunk 2]
```diff
@@ -65,10 +65,22 @@ abstract class DirectionalCaretMovementIntent extends DirectionalTextEditingInte
...
   ) : assert(!collapseSelection || !collapseAtReversal),
       super(forward);
 
+  /// Whether to expand an uncollapsed selection or extend it.
+  ///
+  /// When set to false, the selection will extend, meaning that the base will
+  /// be held in place while the extent is moved.
+  ///
+  /// When set to true, the selection will expand, meaning that the selection
+  /// will grow by moving either the base or the extent.
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart:81]: Also maybe say this is typically only for macOS?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3643,14 +3643,28 @@ class _UpdateTextSelectionAction<T extends DirectionalCaretMovementIntent> exten
...
     final TextPosition newExtent = intent.forward
-      ? textBoundary.getTrailingTextBoundaryAt(extent)
-      : textBoundary.getLeadingTextBoundaryAt(extent);
+      ? textBoundary.getTrailingTextBoundaryAt(position)
+      : textBoundary.getLeadingTextBoundaryAt(position);
 
-    final TextSelection newSelection = collapseSelection
-      ? TextSelection.fromPosition(newExtent)
-      : textBoundarySelection.extendTo(newExtent);
+    late final TextSelection newSelection;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3660]: unnecessary `late`?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -3643,14 +3643,28 @@ class _UpdateTextSelectionAction<T extends DirectionalCaretMovementIntent> exten
...
+    if (collapseSelection) {
+      newSelection = TextSelection.fromPosition(newExtent);
+    } else {
+      newSelection = intent.expand
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3664]: I tried this and it seems macos does not move the extent when it expands the selection? cmd+shift+-> and then press -> the cursor moves to 1 character to the right from its original position.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:310]: Seems reasonable, but I would slightly prefer having a different intent since `collapseSelection` and `expand` can't both be true and currently it relies on a run time assert.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM with nits

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I think I've got this right now, the behavior might have changed since you tested it.  Here's what I'm testing that seems to match with TextEdit:

  * With cursor in the middle of the line, cmd + left.  Left end is the extent.
  * With cursor in the middle of the line, cmd + right.  Right end is the extent.
  * With cursor in the middle of the line, cmd + left then cmd + right.  Left end is the extent.
  * With cursor in the middle of the line, cmd + right then cmd + left.  Right end is the extent.
  * With an RTL selection in the middle of the line, cmd + left.  Left end is the extent.
  * With an RTL selection in the middle of the line, cmd + right.  Left end is the extent.
  * With an LTR selection in the middle of the line, cmd + right.  Right end is the extent.
  * With an LTR selection in the middle of the line, cmd + left.  Right end is the extent.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I just added tests for all of these cases too.  By "testing" in the previous comment I meant manually trying myself vs. TextEdit.

File: packages/flutter/lib/src/widgets/text_editing_intents.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart]: This exact comment was removed because I created a separate Intent.  I made sure that Intent's comments were clear and I added a line about MacOS there.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -3643,14 +3643,28 @@ class _UpdateTextSelectionAction<T extends DirectionalCaretMovementIntent> exten
       );
     }
 
-    final TextPosition extent = textBoundarySelection.extent;
+    late final TextPosition position;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Undone with refactoring to use a new Intent.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Undone with refactoring to use a new Intent.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart]: I've created a new Intent as a subclass of DirectionalTextEditingIntent and I think it worked out cleaner 👍 .
