### PR TITLE
Make flutter_driver be usable from a null-safe app

### LINKED ISSUE #75168: Builds breaking with obscure NNBD stack trace
Recent Framework builds have been breaking and the logs show this error and stack trace in them:

```
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original error: type '() => Null' is not a subtype of type '(() => FutureOr<Map<String, dynamic>>)?' of 'onTimeout'
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original stack trace:
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #0      Future.timeout (dart:async/future_impl.dart)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #1      _warnIfSlow (package:flutter_driver/src/driver/vmservice_driver.dart:633:6)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #2      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:315:25)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #3      FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:187:34)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #4      VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:232:40)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   <asynchronous suspension>
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #5      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
```

It would appear that an NNBD assertion is failing.

### PR DESCRIPTION
**Pull request by goderbauer**
Prior to this change, attempting to use flutter_driver from a null-safe app/test would result in exceptions:

```
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original error: type '() => Null' is not a subtype of type '(() => FutureOr<Map<String, dynamic>>)?' of 'onTimeout'
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original stack trace:
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #0      Future.timeout (dart:async/future_impl.dart)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #1      _warnIfSlow (package:flutter_driver/src/driver/vmservice_driver.dart:633:6)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #2      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:315:25)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #3      FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:187:34)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #4      VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:232:40)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   <asynchronous suspension>
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #5      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
```

This PR fixes those.

We had tests guarding against these kinds of failures, but it turns out that those tests weren't running on CI. CI only executes those tests of the flutter_driver package located in the `test/src/real_test` and `test/src/web_test` directory. This PR also moves all existing tests into those directories and adds a test to ensure that we do not accidentally add tests outside of those directories.

Fixes https://github.com/flutter/flutter/issues/75168.

### CODE REVIEW

File: packages/flutter_driver/test/src/real_tests/test_organisation_test.dart [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'dart:io';
+
+import 'package:flutter_test/flutter_test.dart';
+import 'package:path/path.dart' as p;
+
+void main() {
+  // On CI we only execute the tests in the `test/src/real_test` and
```
Comment (dnfield) [inline packages/flutter_driver/test/src/real_tests/test_organisation_test.dart:11]: Should we just move this to dev/bots/test.dart?

**Review by dnfield — APPROVED** [review]
Change LGTM, location of organization test is a nit

File: packages/flutter_driver/test/src/real_tests/test_organisation_test.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter_driver/test/src/real_tests/test_organisation_test.dart:11]: I think this is a better location for the test because I will see it fail during local development when messing up the organisation and doing a `flutter test`. Moving it to the bots script means I'll only learn about it during presubmit. I prefer to be notified as early as possible (and before sending something out for review).
