### PR TITLE
Ensure cupertino time picker positions hours and minutes correctly for RTL

### LINKED ISSUE #63337: Cupertino dat picker in rtl language
Cupertino date picker has wrong positions in rtl direction
Screenshot_٢٠٢٠٠٨٠٩-١٨٠٨٥٤

It has to be 
(am or pm)  hours  minutes date
Not
 (am or pm)  minutes hours date
Or we need an order property for positions

### PR DESCRIPTION
**Pull request by rami-a**
## Description

This change ensures that hours stays to the left of minutes even when the locale is RTL for the Cupertino time picker.

## Related Issues

Fixes #63337

## Tests

I added the following tests:

- Test to check the position of the hours relative to the minutes in RTL

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by clocksmith — APPROVED** [review]

**Review by johnsonmh — APPROVED** [review]

File: packages/flutter/lib/src/cupertino/date_picker.dart [hunk 1]
```diff
@@ -948,9 +948,15 @@ class _CupertinoDatePickerDateTimeState extends State<CupertinoDatePicker> {
       _getEstimatedColumnWidth(_PickerColumnType.hour),
       _getEstimatedColumnWidth(_PickerColumnType.minute),
     ];
+
+    // Swap the hours and minutes if RTL to ensure they are in the correct position.
+    final bool isRtl = Directionality.of(context) == TextDirection.rtl;
```
Comment (HansMuller) [inline packages/flutter/lib/src/cupertino/date_picker.dart:953]: There's nothing wrong with this but personally, I'd write:
```dart
final List<_ColumnBuilder> pickerBuilders = Directionality.of(context) == TextDirection.rtl
  ? <_ColumnBuilder>[_buildMinutePicker, _buildHourPicker]
  : <_ColumnBuilder>[_buildHourPicker, _buildMinutePicker];

```

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/cupertino/date_picker.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/lib/src/cupertino/date_picker.dart:953]: Yeah I agree, this is cleaner
