### PR TITLE
`AutomatedTestWidgetsFlutterBinding.pump` provides wrong pump time stamp, probably because of forgetting the precision

### LINKED ISSUE #112610: `AutomatedTestWidgetsFlutterBinding.pump` should match engine frame precision
Companion issue fixed by #112609. Please see PR for description :)

_Copied from PR_

The fix is just one line:

image

I have `git blame` and find the bug exist since the first version 7yr ago, and no special comments about why this is introduced so I guess it is but not feature.

IMHO the bug may be written like, the programmer wants to convert DateTime (the `clock.now()`) into a Duration. But then it is forgotten that both are microseconds precision instead of milliseconds precision, and the milliseconds approach is used.

### PR DESCRIPTION
**Pull request by fzyzcjy**
The fix is just one line:

image

I have `git blame` and find the bug exist since the first version 7yr ago, and no special comments about why this is introduced so I guess it is but not feature.

IMHO the bug may be written like, the programmer wants to convert DateTime (the `clock.now()`) into a Duration. But then it is forgotten that both are microseconds precision instead of milliseconds precision, and the milliseconds approach is used.

*List which issues are fixed by this PR. You must list at least one issue.*
Close #112610

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

---

p.s. test fails with old code, confirming that the test is effective.

image
image

### CODE REVIEW

File: packages/flutter_test/lib/src/binding.dart [hunk 1]
```diff
@@ -1077,6 +1077,10 @@ class AutomatedTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
   @override
   int get microtaskCount => _currentFakeAsync!.microtaskCount;
 
+  /// In order to let animation get accurate time information during [pump],
+  /// set the flag to true. The default value is false for compatibility.
+  bool accuratePump = false;
+
```
Comment (pdblasi-google) [inline packages/flutter_test/lib/src/binding.dart:1083]: Is this because of the test failures in your earlier commits?

From what I can tell, one of those failures would be expected (the `widget_tester_test.dart "pumping pumpFrames"` test), and the other test is a customer test that I think is reasonable to make a change to or temporarily disable. I'll have to follow up with some people on whether the customer test change is acceptable or not.

If getting a change to the customer test is reasonable, I'd much prefer we get rid of this flag, as it doesn't actual do anything _except_ keep backwards compatibility for something we've pretty thoroughly determined is a bug.

Comment (pdblasi-google) [reply packages/flutter_test/lib/src/binding.dart:1083]: I'll followup again on Monday, but I'm hoping we can fix the failing customer test to prevent needing to add this flag.

Comment (fzyzcjy) [reply packages/flutter_test/lib/src/binding.dart:1083]: Yes, I add that flag because CI fails by widget_tester_test.dart and a consumer-test.

> and the other test is a customer test that I think is reasonable to make a change to or temporarily disable. I'll have to follow up with some people on whether the customer test change is acceptable or not.

Take your time :)

> If getting a change to the customer test is reasonable, I'd much prefer we get rid of this flag, as it doesn't actual do anything except keep backwards compatibility for something we've pretty thoroughly determined is a bug.

Totally agree! I also want to remove the flag

Comment (pdblasi-google) [reply packages/flutter_test/lib/src/binding.dart:1083]: Apologies for the delay, but I've reached out to the owner of the customer test that's failing and we think we can get a fix in the test that's compatible with this change without the flag. I'll work on getting that test fix in, while I'm doing that could you:

1) Remove the `accuratePump` flag
2) Fix the test in the `widget_tester_test.dart` file that was failing

After we get those failing tests cleared up, this should be good to go!

Comment (pdblasi-google) [reply packages/flutter_test/lib/src/binding.dart:1083]: Alright, the customer test should be fixed now. I tested it with the microsecond change locally to verify that the customer test works before _and_ after this change.

Comment (fzyzcjy) [reply packages/flutter_test/lib/src/binding.dart]: Thanks :) Code done, waiting for CI

**Comment by fzyzcjy** [comment]
```
| 00:15 +36: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.RNUBSQ/tests/packages/animations/test/open_container_test.dart: Container closes - Fade (by default)
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: 1.0 (±1e-10)
|   Actual: <0.9999833333333332>
|    Which: 0.9999833333333332 is not in the range of 1.0 (±1e-10).
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure> (file:///b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.RNUBSQ/tests/packages/animations/test/open_container_test.dart:273:7)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
|
| This was caught by the test expectation on the following line:
|   file:///b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.RNUBSQ/tests/packages/animations/test/open_container_test.dart line 273
| The test description was:
|   Container closes - Fade (by default)
| ════════════════════════════════════════════════════════════════════════════════════════════════════
|
| 00:15 +37 -1: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.RNUBSQ/tests/packages/animations/test/fade_scale_transition_test.dart: FadeScaleTransitionConfiguration builds a new route
| 00:15 +37 -1: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.RNUBSQ/tests/packages/animations/test/open_container_test.dart: Container closes - Fade (by default) [E]
|   Test failed. See exception logs above.
|   The test description was: Container closes - Fade (by default)
```

**Comment by fzyzcjy** [comment]
@pdblasi-google I guess maybe need to update the custom testing configurations to point to the latest tests?

**Comment by pdblasi-google** [comment]
@fzyzcjy Yup, you called it. Apologies, I forgot to point the flutter/tests repo to the latest tests. PR is up for that now, I'll ping here when it goes through.

**Review by pdblasi-google — APPROVED** [review]
Alright, customer tests are passing, golden files that were affected by the precision change have been triaged and updated, and the code itself looks good to me!

I appreciate your patience working through the tests and everything. I'll pass it off to someone else for another review, and you should be good to go! Good find!

**Comment by fzyzcjy** [comment]
Thanks and 🎉 !

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by CaseyHillers** [comment]
@fzyzcjy @goderbauer this is a breaking change. Can a migration guide be written on how developers can migrate their code with this change? I'm not sure what's needed on my end as a developer, and my animation tests are now very flaky.

**Comment by fzyzcjy** [comment]
@CaseyHillers 

> Can a migration guide be written on how developers can migrate their code with this change? ...and my animation tests are now very flaky.

Could you please share some flaky test minimal reproducible samples? IMHO this should not make any problem

**Comment by CaseyHillers** [comment]
Here's an example now that is flaky:

```dart
      await tester.pumpWidget(myAnimatedWidget);
      await tester.pumpAndSettle();

      await tester.sendSelectEvent();

      await tester.pumpFrames(scene, Duration(milliseconds: 100));
      await expectLater(
          find.byType(MyAnimatedWidget),
          matchesGoldenFile(
              'animated_widget'));
```

The resulting goldens are changing. When I change `pumpFrames` to microseconds, I am still seeing the same flakiness. I'm unsure if it's because the earlier clocks are still in millisecond mode.

**Comment by CaseyHillers** [comment]
My animated widgets are just an animated builder that has a custom animation controller. @goderbauer or @pdblasi-google can help with reproducing the issue here.

My understanding is I need to change every possible clock to be in microseconds instead of milliseconds. This seems to be a breaking change for any other customers, and I'm having a difficult time tracking all the various clocks in my codebase.

I haven't found the discord threads, but I wonder if this is something that should be in the framework. There could be a tester field added for high precision or this can be added directly to your package. I assume most Flutter tests aren't needing high precision, and this is going to cause a lot of pain once it's in beta/stable.

**Comment by fzyzcjy** [comment]
@CaseyHillers 

> I need to change every possible clock to be in microseconds instead of milliseconds

Btw I am curious why a clock can in milliseconds in codebase - `clock` package, `Duration`, DateTime, etc are all in microseconds.

> I haven't found the discord threads, but I wonder if this is something that should be in the framework. There could be a tester field added for high precision or this can be added directly to your package. I assume most Flutter tests aren't needing high precision, and this is going to cause a lot of pain once it's in beta/stable.

I agree that an alternative solution is to use a bool flag to enable high-accuracy (I have done that indeed - https://github.com/flutter/flutter/pull/112609/commits/e0b5882b87bc8fe025d55d626ec663c8587522b7).

**Comment by CaseyHillers** [comment]
> I agree that an alternative solution is to use a bool flag to enable high-accuracy (I have done that indeed - https://github.com/flutter/flutter/commit/e0b5882b87bc8fe025d55d626ec663c8587522b7).

Thanks, that sounds like it would work for me! Are there plans to upstream that change?

**Comment by fzyzcjy** [comment]
@CaseyHillers I am ok with that, just not sure what other reviewers think? If you guys are OK I will PR it.

**Comment by fzyzcjy** [comment]
Here is the PR: https://github.com/flutter/flutter/pull/113433

**Comment by fzyzcjy** [comment]
@CaseyHillers Here is the PR: https://github.com/flutter/flutter/pull/113433
