### PR TITLE
fix a RenderSliverFixedExtentBoxAdaptor Exception 

### LINKED ISSUE #72292: Exception on RenderSliverFixedExtentBoxAdaptor.performLayout after device orientation change
This code uses ListView.builder to display a list of items. When running on portrait or landscape it runs correctly covering the entire screen. When I change the device orientation from while running the app, an exception occurs and the items keep the previous width.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update main.dart to code below

### Updated code sample
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

class ItemModel {
  String date;
  String description;

  ItemModel({this.date, this.description});
}

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<ItemModel> items = List<ItemModel>();

  void initState() {
    super.initState();
    for (int i = 1; i <= 30; i++) {
      items.add(ItemModel(date: 'December', description: 'Item $i'));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          const SizedBox(height: 10),
          Expanded(
            child: buildMain(),
          ),
        ],
      ),
    );
  }

  Widget buildMain() {
    return SingleChildScrollView(
      child: Container(
        margin: EdgeInsets.symmetric(horizontal: 10),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            SizedBox(height: 10),
            _buildListView(),
          ],
        ),
      ),
    );
  }

  Widget _buildListView() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          Container(
            padding: EdgeInsets.only(bottom: 5),
            child: Row(
              children: <Widget>[
                Text(
                  'Previous Balance: 0.00',
                  overflow: TextOverflow.fade,
                  softWrap: false,
                ),
              ],
            ),
          ),
          ListView.builder(
            scrollDirection: Axis.vertical,
            shrinkWrap: true,
            physics: ScrollPhysics(),
            itemExtent: 35,
            itemCount: items.length + 1,
            itemBuilder: (context, index) {
              if (index == 0) {
                // return the header
                return Container(
                  height: 30,
                  child: Row(
                    children: <Widget>[
                      Container(
                        width: 80,
                        padding: EdgeInsets.all(4),
                        child: Text(
                          'Date',
                        ),
                      ),
                      Expanded(
                        child: Container(
                          padding: EdgeInsets.all(4),
                          color: Colors.green,
                          child: Text(
                            'Description',
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              }
              index -= 1;
              return Container(
                height: 30,
                child: Row(
                  children: <Widget>[
                    Container(
                      width: 80,
                      padding: EdgeInsets.all(4),
                      child: Text(
                        items[index].date,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        padding: EdgeInsets.all(4),
                        child: Text(
                          items[index].description,
                        ),
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    );
  }
}

``` 

</details>

3. Set emulator to auto-rotate
4. Run app
5. Change orientation to landscape

**Expected results:** 
Display items covering entire screen on landscape

**Actual results:** 
Items have same width on landscape as in portrait and an exception message is shown on log

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was: 
  ListView file:///C:/Dev/Sample/bug/lib/main.dart:129:16
When the exception was thrown, this was the stack: 
#0      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:190:76)
#1      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#2      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132:12)
#3      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)

```

```
```

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.4 at C:\DevTools\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mauricio\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\DevTools\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\DevTools\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

This bug can reproduce when `fixed extent ListView` under `SingleChildScrollView`

When under a `SingleChildScrollView`, the `constraints.remainingCacheExtent` is infinity and the `targetLastIndex` wil be null.
We can just skip the trailing children's garbage collection because all of the children will be adopted.

## Minimal Sample(Hot reload will trigger the bug)
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: ListView.builder(
          shrinkWrap: true,
          itemExtent: 35,
          itemCount: 1,
          itemBuilder: (context, index) {
            return Text('I love Flutter.');
          },
        ),
      ),
    );
  }
}

```

## Related Issues

Fixes #72292

## Tests

I added the following tests:

See files.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart [hunk 1]
```diff
@@ -195,7 +195,7 @@ abstract class RenderSliverFixedExtentBoxAdaptor extends RenderSliverMultiBoxAda
 
     if (firstChild != null) {
       final int leadingGarbage = _calculateLeadingGarbage(firstIndex);
-      final int trailingGarbage = _calculateTrailingGarbage(targetLastIndex!);
+      final int trailingGarbage = _calculateTrailingGarbage(targetLastIndex);
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart:198]: lets pull the null check out, and keep the function signature the same.
```dart
final int trailingGarbage = targetLastIndex != null ? _calculateTrailingGarbage(targetLastIndex) : 0;
```

**Review by chunhtai — APPROVED** [review]
LGTM, modulo nits
