### PR TITLE
Size CupertinoTextSelectionToolbar to children

### LINKED ISSUE #132819: TextField selection truncated in Chinese
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

main.dart

```dart
MaterialApp.(
  localizationsDelegates: const <LocalizationsDelegate<Object>>[
    GlobalWidgetsLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ],
  localeResolutionCallback: (locale, supportedLocales) => locale,
)
```

pubspec.yaml
``` yaml
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

### Expected results

display Chinese normally under `Pixel 7 API 34`

image

### Actual results

cannot display Chinese normally under `Iphone14 Pro Max` `iOS 16.6`

fe8ffefd-1adc-4f39-9689-b88edcc0332b

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
    • Flutter version 3.13.0 on channel stable at C:\Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\95646\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Apps\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Apps\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Apps\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.2134]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.203
```

</details>

### LINKED ISSUE #133140: Clipped text in CupertinoTextSelectionToolbar children
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter create cupertino_selection_toolbar
2. Paste the provided example code
3. flutter run

### Expected results

Text isn't clipped in the toolbar

### Actual results

Text clipped in the toolbar at the bottom. Note that the same text when wrapped in `CupertinoTextSelectionToolbarButton.text` only is displayed correctly.

image

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoTextSelectionToolbarButton.text(
              onPressed: () {},
              text: 'Lorem ipsum',
            ),
            CupertinoTextSelectionToolbarButton.text(
              onPressed: () {},
              text: '这是黑体',
            ),
            CupertinoTextSelectionToolbarButton.text(
              onPressed: () {},
              text: 'ក្ក្ដីថ្លៃថ្នូ'
            ),
            SizedBox(
              width: 450.0,
              height: 200.0,
              child: CupertinoTextSelectionToolbar(
                anchorAbove: Offset.zero,
                anchorBelow: Offset.zero,
                children: <Widget>[
                  CupertinoTextSelectionToolbarButton.text(
                    onPressed: () {},
                    text: 'Lorem ipsum',
                  ),
                  CupertinoTextSelectionToolbarButton.text(
                    onPressed: () {},
                    text: '这是黑体',
                  ),
                  CupertinoTextSelectionToolbarButton.text(
                    onPressed: () {},
                    text: 'ក្ក្ដីថ្លៃថ្នូ'
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel master, 3.14.0-9.0.pre.52, on macOS 13.4.1 22F770820d darwin-arm64, locale en-ES)
    • Flutter version 3.14.0-9.0.pre.52 on channel master at /Users/tgucio/Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4bbcb780a6 (8 hours ago), 2023-08-23 00:53:44 -0400
    • Engine revision 7d56840865
    • Dart version 3.2.0 (build 3.2.0-97.0.dev)
    • DevTools version 2.26.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
% 
```

</details>

### PR DESCRIPTION
**Pull request by tgucio**
Fixes https://github.com/flutter/flutter/issues/133140, https://github.com/flutter/flutter/issues/132819, https://github.com/flutter/flutter/issues/69847

Before             |  After
:-------------------------:|:-------------------------:
before  |  after

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 1]
```diff
@@ -14,19 +14,22 @@ import 'text_selection_toolbar_button.dart';
 import 'theme.dart';
 
 // Values extracted from https://developer.apple.com/design/resources/.
-// The height of the toolbar, including the arrow.
-const double _kToolbarHeight = 45.0;
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:18]: I've always wanted to get rid of the hard coded height if possible :+1:

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 2]
```diff
@@ -14,19 +14,22 @@ import 'text_selection_toolbar_button.dart';
...
 const double _kToolbarContentDistance = 8.0;
+
+// The size of the arrow button to navigate between pages.
 const Size _kToolbarArrowSize = Size(14.0, 7.0);
 
 // Minimal padding from tip of the selection toolbar arrow to horizontal edges of the
 // screen. Eyeballed value.
 const double _kArrowScreenPadding = 26.0;
 
-// Values extracted from https://developer.apple.com/design/resources/.
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:28]: Can you keep this comment or is there a reason to remove it?

**Review by justinmc — COMMENTED** [review]
Thanks for working on this, it's a big problem for people!

Some things I see in the screenshot in https://github.com/flutter/flutter/pull/133386#issuecomment-1701292684:

  1. The right arrow seems to not be vertically aligned.
  2. The shadow above the toolbar is missing.  I checked and native (iOS 14) does have a shadow above.
  3. The toolbar background looks darker.

What happens if the text in the toolbar is very big, or you use the Thai (I think) text from https://github.com/flutter/flutter/issues/133140?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 2 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:28]: The same comment appears above - I separated it by one line so it's clearer it refers to all the constants.

**Comment by tgucio** [comment]
@justinmc 

> 1. The right arrow seems to not be vertically aligned.
> 2. The shadow above the toolbar is missing.  I checked and native (iOS 14) does have a shadow above.
> 3. The toolbar background looks darker.
> 
> What happens if the text in the toolbar is very big, or you use the Thai (I think) text from #133140?

1. This should be corrected now: a bit tricky as it requires a re-layout of the nav buttons when children have larger height.
2. Yes, this did look differently. I reverted from using `canvas.drawShadow()` to mimicking what `DecoratedBox()` would draw for a shadow. Should be close enough now.
3. I think this effect was caused by the very little shadow on top. The button colours are defined in the button widget I guess.

I've added before and after screenshots that show both above and below toolbar alighnments.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 3]
```diff
@@ -526,9 +548,13 @@ class _CupertinoTextSelectionToolbarContentState extends State<_CupertinoTextSel
...
 
     return IgnorePointer(
-      child: Center(
-        // If widthFactor is not set to 0, the button is given unbounded width.
-        widthFactor: 0,
+      // Use Align with widthFactor and heightFactor of 1.0 so
+      // _CupertinoTextSelectionToolbarItems can get the natural size
+      // of the buttons and then expand vertically as needed i.e. if children
+      // have higher height than that.
+      child: Align(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:555]: nit: use `Center` instead so it's more obvious the child will be centered?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 4]
```diff
@@ -14,19 +14,22 @@ import 'text_selection_toolbar_button.dart';
...
 
 // Values extracted from https://developer.apple.com/design/resources/.
-// The height of the toolbar, including the arrow.
-const double _kToolbarHeight = 45.0;
+
 // Vertical distance between the tip of the arrow and the line of text the arrow
 // is pointing to. The value used here is eyeballed.
 const double _kToolbarContentDistance = 8.0;
+
+// The size of the arrow button to navigate between pages.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:22]: I thought this is the arrow that `_clipPath` uses to create the arrow that points to the current selection?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:28]: Many other constants here are eyeballed so I think it will be good to keep the provenance per constant, or per constant group.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 5]
```diff
@@ -296,55 +291,61 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
...
+      isAbove ? -_kToolbarArrowSize.height : 0.0,
     );
     size = Size(
       child!.size.width,
       child!.size.height - _kToolbarArrowSize.height,
     );
   }
 
+  // Returns the RRect inside which the child is painted.
+  RRect _shapeRRect() {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:314]: nit:  make this a getter instead like `isAbove`?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 6]
```diff
@@ -354,11 +355,31 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
     }
 
     final BoxParentData childParentData = child!.parentData! as BoxParentData;
+
+    final RRect rrect = _shapeRRect();
+    final Path clipPath = _clipPath(rrect);
+
+    // If configured, paint the shadow beneath the shape.
+    if (_shadowColor != null) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:363]: What's the difference between this and using BoxDecoration?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 7]
```diff
@@ -979,6 +1008,21 @@ class _RenderCupertinoTextSelectionToolbarItems extends RenderBox with Container
       }
     });
 
+    // If needed, re-layout slotted children using max. child height to allow
+    // the back/next buttons to be centered vertically.
+    if (greatestHeight > _backButton!.size.height) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1013]: Since the menu items are usually text, I think the children here should be baseline-aligned by default? Then this second layout pass is probably no longer needed.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 8]
```diff
@@ -139,21 +147,8 @@ class CupertinoTextSelectionToolbar extends StatelessWidget {
...
-            color: CupertinoColors.black.withOpacity(0.2),
-            blurRadius: 15.0,
-            offset: Offset(
-              0.0,
-              isAbove ? 0.0 : _kToolbarArrowSize.height,
-            ),
-          ),
-        ],
+      decoration: const BoxDecoration(
+        borderRadius: BorderRadius.all(_kToolbarBorderRadius),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:151]: Do we still need the border radius here? It will be clipped after the toolbar is painted right?

**Comment by LongCatIsLooong** [comment]
IIRC in SkParagraph the line height is computed from font metrics instead of glyph (cluster) metrics so stacking diacritics shouldn't make lines taller.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 2 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:28]: I'll keep comments per constant.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 4 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:22]: Ah, you're right there.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 6 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:365]: The problem with using `BoxDecoration` to draw shadows was that you had to know upfront whether the toolbar would come above or below the anchor to apply a vertical offset. This worked with const toolbar height but not now we size it to the children.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 7 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1015]: IMHO the toolbar should be child type agnostic (e.g. in iOS we already have the LiveText button which uses CustomPaint).

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1015]: In that case center aligning sounds like a better option than top aligning the children? Looks nicer when one child is significantly taller.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 8 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:154]: Yeah, this can go - we're not drawing any borders here.

**Comment by tgucio** [comment]
@LongCatIsLooong @justinmc this should be ready for another review.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 9]
```diff
@@ -366,26 +360,30 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
...
+
+    final double centerX = childParentData.offset.dx + child.size.width / 2;
+    final double arrowXOffsetFromCenter = localAnchor.dx - centerX;
+    final double arrowTipX = child.size.width / 2 + arrowXOffsetFromCenter;
 
     // Draw the path clockwise, starting from the beginning side of the arrow.
-    if (_isAbove) {
+    if (isAbove) {
+      final double arrowBaseY = child.size.height - _kToolbarArrowSize.height;
+      final double arrowTipY = child.size.height;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:373]: Looks like the path is now described in `child`'s coordinates? If so could you update the comment before this method?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 10]
```diff
@@ -395,12 +393,34 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
...
+        blurRadius: 15.0,
+      );
+      final RRect shadowRRect = RRect.fromLTRBR(
+        rrect.left,
+        rrect.top,
+        rrect.right,
+        rrect.bottom + _kToolbarArrowSize.height,
+        _kToolbarBorderRadius,
+      ).shift(offset + childParentData.offset + boxShadow.offset);
+      context.canvas.drawRRect(shadowRRect, boxShadow.toPaint());
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:415]: have you tried `Canvas.drawShadow`? According to the documentation it's more efficient.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 11]
```diff
@@ -950,8 +988,10 @@ class _RenderCupertinoTextSelectionToolbarItems extends RenderBox with Container
     _backButton!.layout(constraints.loosen(), parentUsesSize: true);
     _nextButton!.layout(constraints.loosen(), parentUsesSize: true);
 
-    final double subsequentPageButtonsWidth =
-        _backButton!.size.width + _nextButton!.size.width;
+    // Require the children to have at least the height of the nav buttons.
+    final double minHeight = clampDouble(constraints.minHeight, _backButton!.size.height, _nextButton!.size.height);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:992]: Do we still need `minHeight` now that we're vertically centering them?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 12]
```diff
@@ -1021,15 +1059,24 @@ class _RenderCupertinoTextSelectionToolbarItems extends RenderBox with Container
       }
     });
 
+    // Re-layout the children using max. child height to allow them to be centered vertically.
+    visitChildren((RenderObject renderObjectChild) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1063]: We should avoid doing a second layout pass if possible. Do these children all have to have the exact same height? To center them vertically could you just adjust their y offsets instead of doing a second layout pass and enforcing `greatestHeight`?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1063]: Also unless `visitChildren` is overridden it doesn't visit the back button and the next button right? Do they need to readjust their heights too?

Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1063]: Yes, we need to adjust the children height so the whole button area is painted using another shade during tap - see the screenshot [here](https://github.com/flutter/flutter/pull/133386#discussion_r1331144856) (the bottom toolbar). `visitChildren` also visits the back/next buttons: they're added as render object children (and called "slotted" children) and their heigh is adjusted.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 13]
```diff
@@ -252,68 +237,81 @@ class _CupertinoTextSelectionToolbarShape extends SingleChildRenderObjectWidget
...
     final RenderBox? child = this.child;
     if (child == null) {
       return;
     }
 
-    // The child is tall enough to have the arrow clipped out of it on both sides
-    // top and bottom. Since _kToolbarHeight includes the height of one arrow, the
-    // total height that the child is given is that plus one more arrow height.
-    // The extra height on the opposite side of the arrow will be clipped out. By
+    final BoxConstraints enforcedConstraint = constraints.loosen();
```
[the remark this answers is not in the document]
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:288]: I'd say this is something for another PR.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 14]
```diff
@@ -366,26 +360,30 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
...
-    final Offset localAnchor = globalToLocal(_anchor);
-    final double arrowTipX = clampDouble(
-      localAnchor.dx,
-      _kToolbarBorderRadius.x + _kToolbarArrowSize.width / 2,
-      size.width - _kToolbarArrowSize.width / 2 - _kToolbarBorderRadius.x,
-    );
+    final BoxParentData childParentData = child.parentData! as BoxParentData;
+    final Offset localAnchor = globalToLocal(isAbove ? _anchorAbove : _anchorBelow);
+
+    final double centerX = childParentData.offset.dx + child.size.width / 2;
```
[the remark this answers is not in the document]
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:366]: The 0.0 dx comes from another method (`performLayout()`) so I think it's better to leave it this way in (unlikely) case someone changes something.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 10 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:415]: I did and it looked horrible :). Didn't repaint in some cases after tapping buttons.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 11 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart]: Good point there. I was able to remove this.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 15]
```diff
@@ -366,26 +360,30 @@ class _RenderCupertinoTextSelectionToolbarShape extends RenderShiftedBox {
       return path..addRRect(rrect);
     }
 
-    final Offset localAnchor = globalToLocal(_anchor);
-    final double arrowTipX = clampDouble(
```
[the remark this answers is not in the document]
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:370]: I definitely changed it back by accident. Restoring (and thanks for catching).

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 12 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1061]: Ah ok that's unfortunate. Instead of  `RenderObject.layout`, usually `getMaxIntrinsicHeight` is used to do this kind of speculative layout. 

the back/next buttons seem to be added to the parent via `adoptChild`. This doesn't add them to the linked list of children that `visitChildren` traverses.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 13 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:288]: It was reverted in this patch. Could you add that back if that doesn't break the new layout of the toolbar?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 12 above)
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1061]: The `visitChildren` method is overriden though:
```dart
  @override
  void visitChildren(RenderObjectVisitor visitor) {
    // Visit the slotted children.
    if (_backButton != null) {
      visitor(_backButton!);
    }
    if (_nextButton != null) {
      visitor(_nextButton!);
    }
    // Visit the list children.
    super.visitChildren(visitor);
  }
```

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart (hunk 13 above)
[the remark this answers is not in the document]
Comment (tgucio) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:288]: Ah, ok - I removed it because the name `heightConstraint` suggested it was height only but indeed it enforced `minWidth` too. Will restore `minWidth`.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 16]
```diff
@@ -946,66 +986,71 @@ class _RenderCupertinoTextSelectionToolbarItems extends RenderBox with Container
...
         paginationButtonsWidth = _backButton!.size.width + _nextButton!.size.width;
         child.layout(
-          BoxConstraints.loose(Size(
-            firstPageWidth - paginationButtonsWidth,
-            constraints.maxHeight,
-          )),
+          BoxConstraints(
+            maxWidth: firstPageWidth - paginationButtonsWidth,
+            minHeight: greatestHeight,
+            maxHeight: constraints.maxHeight,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1052]: Should we use a tight height constraint here?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 17]
```diff
@@ -946,66 +986,71 @@ class _RenderCupertinoTextSelectionToolbarItems extends RenderBox with Container
...
+      }
+    });
+
     // Layout slotted children.
-    _backButton!.layout(constraints.loosen(), parentUsesSize: true);
-    _nextButton!.layout(constraints.loosen(), parentUsesSize: true);
+    final BoxConstraints slottedConstraints = BoxConstraints(
+      maxWidth: constraints.maxWidth,
+      minHeight: greatestHeight,
+      maxHeight: constraints.maxHeight,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:1003]: Sorry miss this part in the previous review. Should the height constraint here be updated too?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM modulo the height constraints for back/next button. Thanks for fixing this!
