### PR TITLE
handleSelectWord in MultiSelectableSelectionContainerDelegate should handle rects inside of rects

### LINKED ISSUE #127076: _SelectableFragment _handleSelectWord assert failed
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. select 'FlutterCandies'
2. right click with mouse

 

### Expected results

no error, toolbar show

### Actual results

assert error 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: SelectionArea(
        child: Text.rich(TextSpan(children: <InlineSpan>[
          TextSpan(
            text:
                '[love]Extended text help you to build rich text quickly. any special text you will have with extended text. '
                'It\'s my pleasure to invite you to join  ',
          ),
          WidgetSpan(child: SizedBox.shrink()),
          TextSpan(
            text: 'FlutterCandies',
            style: TextStyle(fontSize: 16),
          ),
          WidgetSpan(child: SizedBox.shrink()),
          TextSpan(
            text: ' if you want to improve flutter .[love]'
                'if you meet any problem, please let me know @zmtzawqlp .[sun_glasses]',
          ),
        ])),
      )),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/16477333/89e2df2d-27a9-4913-b977-4ecc45696e54

</details>

### Logs

<details><summary>Logs</summary>

```console
The following assertion was thrown while handling a gesture:
'package:flutter/src/rendering/paragraph.dart': Failed assertion: line 1512 pos 12: 'word.start >= range.start && word.end <= range.end': is not true.
paragraph.dart:1512
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _SelectableFragment._handleSelectWord
paragraph.dart:1512
#3      _SelectableFragment.dispatchSelectionEvent
paragraph.dart:1401
#4      MultiSelectableSelectionContainerDelegate.dispatchSelectionEventToChild
selectable_region.dart:2068
#5      _SelectableRegionContainerDelegate.dispatchSelectionEventToChild
selectable_region.dart:1393
#6      MultiSelectableSelectionContainerDelegate.handleSelectWord
selectable_region.dart:1882
#7      _SelectableRegionContainerDelegate.handleSelectWord
selectable_region.dart:1334
#8      MultiSelectableSelectionContainerDelegate.dispatchSelectionEvent
selectable_region.dart:2029
#9      _SelectionContainerState.dispatchSelectionEvent
selection_container.dart:186
#10     SelectableRegionState._selectWordAt
selectable_region.dart:863
#11     SelectableRegionState._handleRightClickDown
selectable_region.dart:494
#12     TapGestureRecognizer.handleTapDown.<anonymous closure>
tap.dart:630
#13     GestureRecognizer.invokeCallback
recognizer.dart:275
#14     TapGestureRecognizer.handleTapDown
tap.dart:630
#15     BaseTapGestureRecognizer._checkDown
tap.dart:302
#16     BaseTapGestureRecognizer.acceptGesture
tap.dart:279
#17     GestureArenaManager._resolveByDefault
arena.dart:268
#18     GestureArenaManager._tryToResolveArena.<anonymous closure>
arena.dart:248
(elided 4 frames from class _AssertionError and dart:async)
Handler: "onSecondaryTapDown"
Recognizer: TapGestureRecognizer#8f0dd
    debugOwner: SelectableRegionState#db27a
    state: possible
    button: 2
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.0 on channel stable at /Users/zmtzawqlp/Documents/flutter/3.10.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zmtzawqlp/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/zmtzawqlp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 12E31781-40FE-4E3D-8D33-40C1A1E49BAD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #127076

Sometimes a `Selectable`s rect may contain another `Selectable`s rect within it. In the case of `handleSelectWord` when choosing which `Selectable` to dispatch the `SelectionEvent` to, the event would be dispatched to the wrong `Selectable` causing an assertion error to be thrown. 

Screenshot 2023-05-24 at 2 46 13 AM

In the picture above the red outline shows the rect of a two-line piece of text. And the blue rect shows the rect of a piece of text that is on the second line of the two-line piece of text, but has been separated into its own rect for some case, for example when `TextSpan`s are separated by a `WidgetSpan`.

We should check if the text layout of the selectable that has been dispatched the SelectionEvent contains the word, if not then return `SelectionResult.next`, and continue to look through the list of selectables.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -1892,7 +1923,15 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
       final Rect localRect = Rect.fromLTWH(0, 0, selectables[index].size.width, selectables[index].size.height);
       final Matrix4 transform = selectables[index].getTransformTo(null);
       final Rect globalRect = MatrixUtils.transformRect(transform, localRect);
-      if (globalRect.contains(event.globalPosition)) {
+      final List<Rect> rectsInside = _selectableContains(selectables[index], selectables);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1926]: Is this making this O(n^2) instead of O(n) before?  Not sure if this is a bottle neck at all, just pointing it out.

**Review by justinmc — APPROVED** [review]
LGTM but maybe give @chunhtai a chance to take a look too.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1926]: Yeah this would be O(n^2) now. I couldn't think of a re-factor for the current solution that would make this O(n). @chunhtai do you have any thoughts on this?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1926]: I am not sure if this is the right fix. I though we may run into the same problem even if the inner selectable is not completely contained by the outer one?

In the example 
image
It seems to me the right behavior is that if the selectword at the inside of inner selectable, the outer box should return SelectionResult.next because it should have known the coordinate is outside its actual text layout.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: That makes a lot of sense! That makes the solution a lot simpler and keeps this O(n). Thanks for the input!

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Good call @chunhtai, this way seems a lot better.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -1894,7 +1894,10 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
       final Rect globalRect = MatrixUtils.transformRect(transform, localRect);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1894]: Since we change the selectword contract that it should return next/prev we also need to update handleSelectWord to return pre/next. i.e. if all selectable return next. or if the selectable return prev.

Also should probably assert if a selectable return prev, it must be the first in the selectables.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1895]: I think I understand why this is needed but for clarification purposes can you confirm my assumptions. We need to update `handleSelectWord` to return `next/prev` because before this change it only return `none/end`. `none` if the word was not selected given the list of selectables managed by the container delegate. And `end` if the word was selected selected given the list of `selectables`.

Now since select word can return `next/prev`, `handleSelectWord` should be updated to also do this in the following cases:
(1) return `next` when the last `SelectionResult` is next
(2) return `prev` when the last `SelectionResult` is prev

Is this correct?

`Also should probably assert if a selectable return prev, it must be the first in the selectables.`
- Not sure I completely understand why for this.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1895]: > none if the word was not selected given the list of selectables managed by the container delegate. And end if the word was selected selected given the list of selectables.

This is correct prior to this change, though the return value was never used so it doesn't really matter what value is return.

> Now since select word can return next/prev, handleSelectWord should be updated to also do this in the following cases:
(1) return next when the last SelectionResult is next
(2) return prev when the last SelectionResult is prev

(2) is incorrect, handleSelectWord should only return prev if the *first* selectionResult return prev.

 > Is this correct?

yes this is correct and it is necessary because this selectionContainer can be a child selectable of another container, and it can also have the overlap issue with another selectable.

> Not sure I completely understand why for this.

Nvm I think i was wrong, it is possible a selectable that is not the first selectable.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1895]: Thank you for the clarification, I think I got it!

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 3]
```diff
@@ -1888,13 +1888,17 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
+    SelectionResult? lastSelectionResult;
     for (int index = 0; index < selectables.length; index += 1) {
       final Rect localRect = Rect.fromLTWH(0, 0, selectables[index].size.width, selectables[index].size.height);
       final Matrix4 transform = selectables[index].getTransformTo(null);
       final Rect globalRect = MatrixUtils.transformRect(transform, localRect);
       if (globalRect.contains(event.globalPosition)) {
         final SelectionGeometry existingGeometry = selectables[index].value;
-        dispatchSelectionEventToChild(selectables[index], event);
+        lastSelectionResult = dispatchSelectionEventToChild(selectables[index], event);
+        if (lastSelectionResult == SelectionResult.previous || lastSelectionResult == SelectionResult.next) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1899]: This seems weird, it should stop as soon as dispatchSelectionEventToChild does not return next.

imagine this case

in sequential order

selectable1 -> next (continue)
selectable2 -> next (continue)
selectable3 -> prev  (should stop)

this meant the selectword land in between selectable 2 and 3, one of them should be set to the currentSelectionStartIndex and currentSelectionEndIndex, I don't think it matter which one.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 4]
```diff
@@ -1906,6 +1910,11 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
         return SelectionResult.end;
       }
     }
+    if (lastSelectionResult == SelectionResult.next) {
+      return SelectionResult.next;
+    } else if (lastSelectionResult == SelectionResult.previous) {
+      return SelectionResult.previous;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1916]: This doesn't look right. consider these cases, assuming 5 child

1.
selectable 1 -> skipped (continue)
selectable 2 -> next  (continue)
selectable 3 -> next  (continue)
selectable 4 -> prev  (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 3 or 4
should return SelectionResult.end

2.
selectable 1 -> skipped (continue)
selectable 2 -> prev  (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end

3.
selectable 1 -> prev  (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 1
should return SelectionResult.prev

4.
selectable 1 -> skip  (continue)
selectable 2 -> next  (continue)
selectable 3 -> end  (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 3
should return SelectionResult.end

5.
selectable 1 -> skip  (continue)
selectable 2 -> next  (continue)
selectable 3 -> skip  (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end

6.
selectable 1 -> skip  (continue)
selectable 2 -> skip  (continue)
selectable 3 -> skip  (continue)
selectable 4 -> next  (continue)
selectable 5 -> next  (at the end)

currentSelectionStartIndex/currentSelectionEndIndex : 5
should return SelectionResult.next

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1899]: That makes sense, but is this assuming that the selectables are in order of how the text is visually laid out?

Trying something like the following code, and the first selectable in the list is `Hello world this is some long text that goes\non two lines`. The second selectable is `Word`, and the third selectable is `Word Word2`.

If I change it to stop as soon as `dispatchSelectionEventToChild` does not return `next` then I get the following.

In sequential order this happens.

selectable1 -> prev (should stop)
currentSelectionStartIndex/currentSelectionEndIndex : null
should return SelectionResult.prev

Is this expected? Trying to right click `Word` at the beginning of the text fails since we never reach it.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: SelectionArea(
            child: Text.rich(
              TextSpan(
                children: <InlineSpan>[
                  TextSpan(text: 'Word'),
                  WidgetSpan(child: SizedBox.shrink()),
                  TextSpan(text: ' Hello world this is some long text that goes\non two lines.'),
                  WidgetSpan(child: SizedBox.shrink()),
                  TextSpan(text: 'Word'),
                  TextSpan(text: ' Word2'),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1899]: > the selectables are in order of how the text is visually laid out?

they should be. I think the issue you encounter was a bug that the function to calculate screen order does not do well when the rect overlaps.
https://github.com/flutter/flutter/blob/764f4cc8c273b82316a221694ff522effd9d1138/packages/flutter/lib/src/widgets/selectable_region.dart#L1635

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 5]
```diff
@@ -1903,9 +1916,12 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
             .forEach((Selectable target) => dispatchSelectionEventToChild(target, const ClearSelectionEvent()));
           currentSelectionStartIndex = currentSelectionEndIndex = index;
         }
-        return SelectionResult.end;
+        return lastSelectionResult;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1919]: oops, I forgot to press send for my previous review. I will repaste here

This doesn't look right. consider these cases, assuming 5 child, skip means the selectword point is not in the rect

1.
selectable 1 -> skipped (continue)
selectable 2 -> next (continue)
selectable 3 -> next (continue)
selectable 4 -> prev (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 3 or 4
should return SelectionResult.end

2.
selectable 1 -> skipped (continue)
selectable 2 -> prev (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end

3.
selectable 1 -> prev (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : null
should return SelectionResult.prev

4.
selectable 1 -> skip (continue)
selectable 2 -> next (continue)
selectable 3 -> end (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 3
should return SelectionResult.end

5.
selectable 1 -> skip (continue)
selectable 2 -> next (continue)
selectable 3 -> skip (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end

6.
selectable 1 -> skip (continue)
selectable 2 -> skip (continue)
selectable 3 -> skip (continue)
selectable 4 -> next (continue)
selectable 5 -> next (at the end)

currentSelectionStartIndex/currentSelectionEndIndex : null
should return SelectionResult.next

7.
selectable 1 -> skip (continue)
selectable 2 -> skip (continue)
selectable 3 -> skip (continue)
selectable 4 -> skip (continue)
selectable 5 -> skip (at the end)

currentSelectionStartIndex/currentSelectionEndIndex : null
should probably return SelectionResult.next

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 6]
```diff
@@ -1903,9 +1916,12 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
       }
     }
+    if (lastSelectionResult == SelectionResult.next) {
+      return SelectionResult.next;
+    }
     return SelectionResult.none;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1925]: This method should never return none

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: You're right, think it should be fixed now. But I'm a bit unsure about this case

```
5.
selectable 1 -> skip (continue)
selectable 2 -> next (continue)
selectable 3 -> skip (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end
```

Why does it stop at the last skip?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: This assume all selectable after 3 are skipped. If not, it is likely a bug in sorting screen order. I am actually not sure whether this should return next or end, but I can't think of a case returning end would be a problem.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: I see, so what this case means is that in a given list of `selectables` a `next` was reported but it was not followed by a `prev`/or `end` that would indicate the word is inside of the list of `selectables`? Why in this case then do we still have to set the currentSelectionStartIndex/currentSelectionEndIndex : 2, when that might not be where the word is? Thank you for explaining.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: If we return `end`, we have to give a currentSelectionStartIndex/currentSelectionEndIndex. If we return `next`, we should not set currentSelectionStartIndex/currentSelectionEndIndex.

After I thought about it more, I think we should return `end` to short-circuit the logic. Otherwise the `select world` logic would need to go through every selectable in the subtree. to figure out whether the position has hit any selectables.

There are two mechanism in play here: the `rect` and `selection result`. In theory, we don't need `rect`, and we can completely rely on `selection result`. The `rect` is here so that we can trim the search tree. If we were to return `next` in this kind of un-decided case, we might as well remove the `rect` check completely.

That also reminding me I was wrong on a previous case. These two case should be the following

5.
selectable 1 -> skip (continue)
selectable 2 -> next (continue)
selectable 3 -> skip (stop here)

currentSelectionStartIndex/currentSelectionEndIndex : 2
should return SelectionResult.end

7
selectable 1 -> skip (continue)
selectable 2 -> skip (continue)
selectable 3 -> skip (continue)
selectable 4 -> skip (continue)
selectable 5 -> skip (at the end)

currentSelectionStartIndex/currentSelectionEndIndex : null
should return SelectionResult.end

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: basically, 

if the first selection return prev, this method return prev
if the [n...length-1] return next, this method return next
else return SelectionResult.end.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 7]
```diff
@@ -1904,9 +1923,15 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
         return SelectionResult.end;
+      } else {
+        if (lastSelectionResult == SelectionResult.next) {
+          currentSelectionStartIndex = currentSelectionEndIndex = index - 1;
+          return SelectionResult.end;
+        }
       }
     }
-    return SelectionResult.none;
+    assert(lastSelectionResult == null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1933]: This could be null if every selectable is skipped?

**Review by chunhtai — APPROVED** [review]
LGTM, just one concern about the assert being to strict

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 7 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1933]: oh sorry I read the assert wrong. Yes this is correct.
