### PR TITLE
Fix CarouselView crashes when initlal viewportDimension is 0.0

### LINKED ISSUE #160679: `CarouselView` throws `AssertionError` when parent size is 0
### Steps to reproduce

1. Run the code sample
2. Note that there is an error in the console

### Expected results

`CarouselView` should not throw when parent size is 0.

### Actual results

`CarouselView` throws an `AssertionError` when parent size is 0.

The documentation for the `itemExtent` property mentions that _the item extent should not exceed the available space that the carousel view occupies to ensure at least one item is fully visible_. However, the same error is thrown when both the `SizedBox` and `itemExtent` is set to 0. I would also argue that the widget should gracefully handle having 0 size since this can happen indirectly through the parent widget size.

Additionally, an `UnsupportedError` (`Unsupported operation: Infinity or NaN toInt`) is thrown when the `SizedBox` size is set to 100 and `itemExtent` is set to 0.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox(
          width: 0,
          child: CarouselView(
            itemExtent: 100,
            children: [
              Container(
                color: Colors.red,
                width: 100,
                height: 100,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                           14.2s
Connecting to VM Service at ws://127.0.0.1:64008/DOq4En-aJYE=/ws
Connected to the VM Service.

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1515 pos 12: 'correctedOffset.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    CarouselView CarouselView

When the exception was thrown, this was the stack:
#2      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1515:12)
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1467:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#17     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:393:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:293:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:180:12)
#22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1118:7)
#23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:249:7)
#24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:419:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1483:11)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#37     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:62:11)
#38     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:646:43)
#39     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:673:12)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#52     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3750:13)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#56     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1076:13)
#57     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1422:9)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#66     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:574:11)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#82     RenderView.performLayout (package:flutter/src/rendering/view.dart:294:12)
#83     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2548:7)
#84     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1112:18)
#85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1125:15)
#86     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:617:23)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1231:13)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:483:5)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1355:9)
#91     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1064:9)
#92     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:873:16)
#96     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderViewport#74279 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=0.0, 0.0<=h<=852.0)
    size: Size(0.0, 852.0)
    axisDirection: right
    crossAxisDirection: down
    offset: _CarouselPosition#7e9dc(offset: NaN, range: null..null, viewport: 0.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a8b19, ScrollDirection.idle)
    anchor: 0.0
    center child: _RenderSliverFixedExtentCarousel#5c1a8 NEEDS-LAYOUT NEEDS-PAINT
        parentData: paintOffset=Offset(0.0, 0.0)
        constraints: MISSING
        geometry: null
        no children current live
RenderObject: RenderViewport#74279 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=0.0, 0.0<=h<=852.0)
    size: Size(0.0, 852.0)
    axisDirection: right
    crossAxisDirection: down
    offset: _CarouselPosition#7e9dc(offset: NaN, range: null..null, viewport: 0.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a8b19, ScrollDirection.idle)
    anchor: 0.0
    center child: _RenderSliverFixedExtentCarousel#5c1a8 NEEDS-LAYOUT NEEDS-PAINT
        parentData: paintOffset=Offset(0.0, 0.0)
        constraints: MISSING
        geometry: null
        no children current live
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.28.0-2.0.pre.38555, on macOS 14.4.1 23E224 darwin-arm64, locale en-SE)
    • Flutter version 3.28.0-2.0.pre.38555 on channel main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 181f4244b4 (3 hours ago), 2024-12-20 18:46:55 +0100
    • Engine revision 181f4244b4
    • Dart version 3.7.0 (build 3.7.0-266.0.dev)
    • DevTools version 2.41.0
```

</details>

### LINKED ISSUE #163436: CarouselView throws "Unsupported operation: Infinity or NaN toInt" on android
### Steps to reproduce

1. Run the samle code in release mode (not in debug)

### Expected results

Code works as expected and displays the image.

### Actual results

Nothing is displayed an this error is thrown:

```sh
I/flutter (18167): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/flutter (18167): Unsupported operation: Infinity or NaN toInt
I/flutter (18167): #0      RenderObject.constraints (package:flutter/src/rendering/object.dart)
I/flutter (18167): #1      RenderSliver.constraints (package:flutter/src/rendering/sliver.dart:1311)
I/flutter (18167): #2      _RenderSliverFixedExtentCarousel.getMinChildIndexForScrollOffset (package:flutter/src/material/carousel.dart:676)
I/flutter (18167): #3      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:302)
I/flutter (18167): #4      _RenderSliverFixedExtentCarousel.performLayout (package:flutter/src/material/carousel.dart:631)
I/flutter (18167): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #6      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:608)
I/flutter (18167): #7      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1576)
I/flutter (18167): #8      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1467)
I/flutter (18167): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #25     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1483)
I/flutter (18167): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #27     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:392)
I/flutter (18167): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #29     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:180)
I/flutter (18167): #30     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1118)
I/flutter (18167): #31     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:249)
I/flutter (18167): #32     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:419)
I/flutter (18167): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #37     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1483)
I/flutter (18167): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #58     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3750)
I/flutter (18167): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #62     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1076)
I/flutter (18167): #63     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1422)
I/flutter (18167): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
I/flutter (18167): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:2715)
I/flutter (18167): #83     RenderView.performLayout (package:flutter/src/rendering/view.dart:294)
I/flutter (18167): #84     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2548)
I/flutter (18167): #85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1112)
I/flutter (18167): #86     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1125)
I/flutter (18167): #87     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:616)
I/flutter (18167): #88     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1231)
I/flutter (18167): #89     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:482)
I/flutter (18167): #90     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442)
I/flutter (18167): #91     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1355)
I/flutter (18167): #92     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1064)
I/flutter (18167): #93     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:873)
I/flutter (18167): #97     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194)
I/flutter (18167): (elided 3 frames from class _Timer and dart:async-patch)
I/flutter (18167): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (18167): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (18167): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CarouselView(
          itemExtent: double.infinity,
          children: [
            Image.network(
              'https://avatars.githubusercontent.com/u/14101776?s=200&v=4',
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

[logs.txt](https://github.com/user-attachments/files/18816187/logs.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.2 24C101 darwin-x64, locale de-DE) [1.124ms]
    • Flutter version 3.29.0 on channel stable at /Users/huynh/.asdf/installs/flutter/3.29.0-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (vor 6 Tagen), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [3,6s]
    • Android SDK at /Users/huynh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/huynh/Library/Android/sdk
    • Java binary at: /Users/huynh/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [4,0s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [211ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [210ms]
    • Android Studio at /Users/huynh/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.3) [207ms]
    • IntelliJ at /Users/huynh/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23654.44

[✓] Connected device (3 available) [7,2s]
    • 2203129G (mobile) • 723c1722 • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos    • darwin-x64     • macOS 15.2 24C101 darwin-x64
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 133.0.6943.98

[✓] Network resources [381ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes CarouselView crashes due to viewportDimension being 0.0.
 
At startup, a warm-up frame can be produced before the Flutter engine has reported the
initial view metrics. As a result, the first frame can be produced with a size of zero. In the context of CarouselView this leads to some problems mainly related to division by zero.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/163436
Fixes https://github.com/flutter/flutter/issues/160679

## Tests

Adds 5 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/carousel.dart [hunk 1]
```diff
@@ -1500,7 +1500,8 @@ class _CarouselPosition extends ScrollPositionWithSingleContext implements _Caro
     } else {
       item = getItemFromPixels(oldPixels, oldViewportDimensions ?? viewportDimension);
     }
-    final double newPixels = getPixelsFromItem(item, flexWeights, itemExtent);
+    final double newPixels =
+        (viewportDimension == 0.0) ? 0.0 : getPixelsFromItem(item, flexWeights, itemExtent);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/carousel.dart:1504]: Can we move this check in `getPixelsFromItem` so that we can remove the change in line 1408 as well? Just think it would be better if we move the logic into one method.

File: packages/flutter/lib/src/material/carousel.dart [hunk 2]
```diff
@@ -503,7 +503,7 @@ class _CarouselViewState extends State<CarouselView> {
           Axis.vertical => constraints.maxHeight,
         };
         _itemExtent =
-            _itemExtent == null ? _itemExtent : clampDouble(_itemExtent!, 0, mainAxisExtent);
+            widget.itemExtent == null ? null : clampDouble(widget.itemExtent!, 0, mainAxisExtent);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/carousel.dart:506]: Just curious, why do we want to have this change here?

**Review by QuncCccccc — APPROVED** [review]
Nice fix. LGTM. Thanks for adding so many test cases!

I think Carousel.weight might also need to be fixed, but it's okay to fix it in a separate PR!

File: packages/flutter/lib/src/material/carousel.dart (hunk 2 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/carousel.dart:506]: Not obvious, but in fact it is crucial to fix this issue.
Without this change, when the viewport dimension is zero at first, _itemExtent is clamped to 0. Later when the viewport gets the final dimension, the old code `clampDouble(_itemExtent!, 0, mainAxisExtent); `still returns 0.0 and never check again the original widget.itemExtent value.
This is covered by the test named "itemExtent is applied when viewport dimension is updated".

File: packages/flutter/lib/src/material/carousel.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/carousel.dart]: Great call! PR updated 🙏

File: packages/flutter/lib/src/material/carousel.dart (hunk 2 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/carousel.dart:506]: Ah nice catch! Thanks for the explanation!
