### PR TITLE
`showModalBottomSheet` should not dispose the controller provided by user

### LINKED ISSUE #87592: Failed assertion: line 455 pos 7: '_ticker != null'  in showModalBottomSheet
It works as expected if I don't provide my animation controller which I provide only to decrease the default appearing time of the bottom  sheet. 
## Steps to Reproduce
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: HomePage(),
    ));

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  HomePageWithState createState() => HomePageWithState();
}

class HomePageWithState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  AnimationController controller;
  @override
  void initState() {
    super.initState();
    controller = BottomSheet.createAnimationController(this);
    controller.duration = Duration(seconds: 1);
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test Detection"),
      ),
      body: Column(
        children: [
          Center(
            child: GestureDetector(
              onTap: () {
                showModalBottomSheet(
                    context: context,
                    transitionAnimationController: controller,
                    builder: (context) {
                      return Container(
                        color: Colors.purple,
                        child: Container(
                          height: 335,
                          padding: EdgeInsets.all(20),
                          child: SingleChildScrollView(
                            physics: BouncingScrollPhysics(),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                SizedBox(
                                  height: 20,
                                ),
                              ],
                            ),
                          ),
                        ),
                      );
                    });
              },
              child: Container(
                height: 250,
                color: Colors.green,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Expected results:** 
Should show bottom sheet on Tap. 
**Actual results:** 
Works only first time then I get this error 
```
The following assertion was thrown while handling a gesture:
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 455 pos 7: '_ticker != null'

```
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
This is an enhanced patch of #72541 that introduces the `transitionAnimationController` of the `showModalBottomSheet` parameter.

We should not take over the controller provided by the user, all of the framework Widgets follow this principle.

Fixes #87592

### CODE REVIEW

**Comment by xu-baolin** [comment]
CC @Piinks @shihaohong

**Comment by xu-baolin** [comment]
Also, I found a controller leaking by the framework #87708

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 1]
```diff
@@ -626,7 +631,8 @@ class _BottomSheetSuspendedCurve extends ParametricCurve<double> {
 /// for more details).
 ///
 /// The [transitionAnimationController] controls the bottom sheet's entrance and
-/// exit animations if provided.
+/// exit animations if provided. It's up to the owner of the controller to call
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_sheet.dart:634]: wordsmithing: It's up to the owner of the controller to call [AnimationController.dispose] when the controller is no longer needed.

Please apply this (trivial) update elsewhere.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -2794,6 +2794,10 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
   /// [ModalRoute] and a back button is added to the app bar of the [Scaffold]
   /// that closes the bottom sheet.
   ///
+  /// The [transitionAnimationController] controls the bottom sheet's entrance and
+  /// exit animations if provided. It's up to the owner of the controller to call
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart:2798]: It's not necessary to say "if provided" here

File: packages/flutter/lib/src/widgets/routes.dart [hunk 3]
```diff
@@ -149,9 +149,20 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
   Animation<double>? get secondaryAnimation => _secondaryAnimation;
   final ProxyAnimation _secondaryAnimation = ProxyAnimation(kAlwaysDismissedAnimation);
 
+  /// Whether to takeover the [controller] created by [createAnimationController].
+  ///
+  /// If true, this route is responsible for the disposal of the controller.
+  /// If false, the controller should be disposed by whoever owned it.
+  ///
+  /// It defaults to `true`.
+  bool shouldTakeoverAnimationController = true;
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/routes.dart:158]: It might be clearer to call this variable `willDisposeAnimationController`

File: packages/flutter/lib/src/widgets/routes.dart [hunk 4]
```diff
@@ -149,9 +149,20 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
   Animation<double>? get secondaryAnimation => _secondaryAnimation;
   final ProxyAnimation _secondaryAnimation = ProxyAnimation(kAlwaysDismissedAnimation);
 
+  /// Whether to takeover the [controller] created by [createAnimationController].
+  ///
+  /// If true, this route is responsible for the disposal of the controller.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/routes.dart:154]: If true, this route will call [AnimationController.dispose] when the controller is no longer needed.

I think that's all you need to say here.

File: packages/flutter/lib/src/widgets/routes.dart [hunk 5]
```diff
@@ -149,9 +149,20 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+  /// If false, the controller should be disposed by whoever owned it.
+  ///
+  /// It defaults to `true`.
+  bool shouldTakeoverAnimationController = true;
+
   /// Called to create the animation controller that will drive the transitions to
   /// this route from the previous one, and back to the previous route from this
   /// one.
+  ///
+  /// The returned controller will be disposed by [dispose] if the
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/routes.dart:164]: by [dispose] => with [AnimationController.dispose]

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 6]
```diff
@@ -771,6 +771,68 @@ void main() {
     expect(find.text('BottomSheet'), findsNothing);
   });
 
+  testWidgets('the framework do not takeover the transitionAnimationController provided by user.', (WidgetTester tester) async {
```
Comment (HansMuller) [inline packages/flutter/test/material/bottom_sheet_test.dart:774]: takeover => dispose

I understand what you mean by "takeover" however it doesn't hurt to be a little more explicit

Comment (HansMuller) [reply packages/flutter/test/material/bottom_sheet_test.dart:774]: Please insert:
```
// Regression test for https://github.com/flutter/flutter/issues/87708
```

**Review by HansMuller — COMMENTED** [review]
This looks good. Just suggesting some simple wordsmithing

**Review by HansMuller — APPROVED** [review]
LGTM
