### PR TITLE
runApp inside onPressed throws an exception

### LINKED ISSUE #4341: Exception logged calling runApp a second time from clicking a button
## Steps to Reproduce

Sorry I have not taken the time to make a minimal reproduction case. For now I will just describe how to produce it. Everything appears to function fine so this isn't urgent.

1. create a material app that has a button (RaisedButton in my case).
2. make the onPressed of the button call runApp on a second materal app.
3. run the app (ios simulator in my case). Press and hold the button for a second then release.
4. everything appears okay, the second app is started and you no longer see the first app, but an exception is logged.
```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 40 pos 12:
'_routeMap.containsKey(pointer)' is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      PointerRouter.removeRoute (package:flutter/src/gestures/pointer_router.dart:40:12)
#2      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:117:43)
#3      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:133:7)
#4      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:205:5)
#5      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#6      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#7      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:115:19)
#8      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:93:22)
#9      BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:70:5)
#10     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:42:7)
#11     _dispatchPointerPacket (file:///b/build/slave/Mac_Engine/build/src/out/ios_debug_sim/gen/sky/bindings/hooks.dart:43)
Event:
  PointerUpEvent(Point(79.0, 131.0))
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
client (sign-in)$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 5245d3889d (7 minutes ago), engine revision a943c732d5

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.12

```

### PR DESCRIPTION
**Pull request by abarth**
We were trying to unregister the pointer route twice. Now we only unregister it
once.

Fixes #4341

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

File: packages/flutter/test/widget/run_app_test.dart [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+      new Material(
+        child: new RaisedButton(
+          onPressed: () {
+            runApp(new Center(child: new Text('Done')));
+          },
+          child: new Text('GO')
+        )
+      )
+    );
+    await tester.tap(find.text('GO'));
```
Comment (Hixie) [inline packages/flutter/test/widget/run_app_test.dart]: should check that you see the text Done now

**Comment by Hixie** [comment]
LGTM
