### PR TITLE
EditableText action handlers swallow errors

### LINKED ISSUE #16941: TextInput onChanged handler swallows exceptions
In the counter demo, changing this code:

```dart
  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that
      // something has changed in this State, which causes it to rerun
      // the build method below so that the display can reflect the
      // updated values. If we changed _counter without calling
      // setState(), then the build method would not be called again,
      // and so nothing would appear to happen.
      _counter++;
      int.parse('fhfh');
    });
  }
```

throws an exception:

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following FormatException was thrown while handling a gesture:
flutter: Invalid radix-10 number
flutter: fhfh
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:131:5)
flutter: #1      int._parse (dart:core/runtime/libintegers_patch.dart:105:14)
flutter: #2      int.parse (dart:core/runtime/libintegers_patch.dart:62:12)
flutter: #3      _MyHomePageState._incrementCounter.<anonymous closure> (file:///Users/mehmetf/flutter/mehmetf/flutter/examples/hello_world/lib/main.dart:60:11)
flutter: #4      State.setState (package:flutter/src/widgets/framework.dart:1117:30)
```

as expected. It prevents the setState from completing which means the UI is broken (but not in an obvious way). If we override the `onError`, we can handle this just fine.

The `TextInput` is much worse though:

```dart
          new TextField(
            keyboardType: TextInputType.number,
            onChanged: (val) => setState(() => _counter = int.parse(val)),
          ),
```

silently fails when val is not a numeric value (e.g. if the user puts a decimal point via the numeric keyboard). Due to its TextEditController keeping internal state, the text field updates as expected. There is also no exception printed in the log nor any call to onError.

### LINKED ISSUE #65980: EditableText.onSubmitted silently absorbs thrown errors
This error shows up with a `TextField` given an `onSubmitted` or a `TextFormField` given an `onFormSubmitted`. When an error is thrown within the passed method, the error is silently discarded. This appears to be from the [`MethodChannel._handleAsMethodCall`](https://github.com/flutter/flutter/blob/fba99f6cf9a14512e461e3122c8ddfaa25394e89/packages/flutter/lib/src/services/platform_channel.dart#L429) try/catch that wraps the error in a platform message. Details are in [this StackOverflow answer](https://stackoverflow.com/a/63928767/1255873).

To reproduce:

```dart
import 'package:flutter/material.dart';

void main() => runApp(Test());

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            textInputAction: TextInputAction.next,
            onSubmitted: (_) {
              print('before error');
              throw Exception('danger will robinson');
              print('after error');
            },
          ),
        ),
      ),
    );
  }
}
```

When the text in the field is submitted (by tapping the next button on the device keyboard for mobile or pressing the enter key for web/desktop), the log outputs the following:

```
flutter: before error
```

Result of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/*****/Library/Flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/*****/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • Dev iPhone (mobile) • 65301ff37867fe1b1ef12a5793125d88c193d473 • ios • iOS 13.7

• No issues found!
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Currently, any errors that happen in an onSubmitted handler on EditableText are swallowed silently.  This seems to be due to a high level try/catch on messages from the engine.

My solution is to wrap the calls to onSubmitted and other callbacks in a try/catch and report the error if I get one.  Errors in the users' callbacks will be logged on the console like normal, but any errors internal the Flutter caused my an engine message will be sent back to the engine.

## Related Issues

Closes https://github.com/flutter/flutter/issues/65980
Closes https://github.com/flutter/flutter/issues/16941

## Tests

I added the following tests:

  * Test that each type of callback can throw an error.

### CODE REVIEW

File: packages/flutter/lib/src/services/platform_channel.dart [hunk 1]
```diff
@@ -437,7 +437,8 @@ class MethodChannel {
     } on MissingPluginException {
       return null;
     } catch (e) {
-      return codec.encodeErrorEnvelope(code: 'error', message: e.toString(), details: null);
+      codec.encodeErrorEnvelope(code: 'error', message: e.toString(), details: null);
+      rethrow;
```
Comment (justinmc) [inline packages/flutter/lib/src/services/platform_channel.dart:441]: @goderbauer I could use a quick preliminary review from you when you have time.

What do you think about this solution?  Any idea if we were purposely swallowing all of these errors here for some reason, or what the intention was?

Also, if this is a valid solution, why isn't my test below able to test this exception?

Comment (goderbauer) [reply packages/flutter/lib/src/services/platform_channel.dart:441]: We are not really swallowing them. We are sending the error back to the native side, so it can be dealt with there, is my understanding.

Why do you need to rethrow the error here? And aren't these just the errors of the user-provided `handler`? If you really want to catch them, could you just have a try-catch in your `handler`?

Comment (justinmc) [reply packages/flutter/lib/src/services/platform_channel.dart:441]: I just wrote this PR as a quick exploration of #65980, so I don't have a strong opinion, but I'd argue that:

  * Users don't want or expect errors that happen in their callback code to be hidden from them.
  * Updating the docs to inform users that they need to wrap all action callbacks in a try/catch if they want to be informed of errors is a possibility, but that's not an ideal developer experience, and I expect that users would continue to be confused by this behavior.
  * I'm not familiar with this code or error handling in the engine, but I would think that the Flutter framework wants to be informed of its own errors that happen as a result of these messages.

Or maybe I don't understand this problem fully. Are the errors that get sent to the engine logged somewhere that the user has access to? Maybe it's different in production mode?

Comment (goderbauer) [reply packages/flutter/lib/src/services/platform_channel.dart:441]: I see, thanks for the additional context. Indeed, it doesn't make sense to send errors that happen during the user-provided `onSubmit` back to the engine. Can we just wrap the location where we call `onSubmit` in a try-catch and then report a FlutterError from the catch block? E.g. here:

https://github.com/flutter/flutter/blob/e45157fc08c90ab896988f61ea7c8cb95c95f96e/packages/flutter/lib/src/widgets/editable_text.dart#L1825-L1826

We use this pattern in other places as well where we call user-provided callbacks, example:

https://github.com/flutter/flutter/blob/e45157fc08c90ab896988f61ea7c8cb95c95f96e/packages/flutter/lib/src/animation/listener_helpers.dart#L134-L145

Comment (justinmc) [reply packages/flutter/lib/src/services/platform_channel.dart:441]: Yes thanks for the tip, I'll do that!  I was unaware we already were using this sort of pattern.  Will mention you when I'm done.

**Comment by justinmc** [comment]
@goderbauer Ready for re-review, thanks!

Coincidentally, I also discovered that https://github.com/flutter/flutter/issues/66106 is affected by these "swallowed" errors.  In that repro case, the following line fails due to `context` being unexpectedly null:

https://github.com/flutter/flutter/blob/371667ec94b19f31ea48884ac53314625b7b3b4f/packages/flutter/lib/src/widgets/editable_text.dart#L1815

The result is as the author of the issue describes: onSubmitted isn't called.  Under the hood though, an error is happening that the developer is unaware of.

This PR won't affect https://github.com/flutter/flutter/issues/66106 because the error happens outside of the callback.  Is that correct behavior?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -5776,6 +5776,122 @@ void main() {
...
+      await tester.tapAt(topLeft + const Offset(0.0, 5.0));
+      await tester.pump();
+
+      // Modify the selection and expect an exception.
+      final EditableTextState state = tester.state<EditableTextState>(find.byType(EditableText));
+      state.updateEditingValue(const TextEditingValue(
+        text: 'Foo bar',
+        selection: TextSelection(baseOffset: 0, extentOffset: 3),
+      ));
+      expect(tester.takeException(), isNotNull);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/editable_text_test.dart:5810]: There's an `isFlutterError` matcher, that seems appropriate here.

Bonus points for also checking that the exception message contains some of the text we are expecting here to ensure that this is actually the exception we want (and not some other random exception).

Comment (goderbauer) [reply packages/flutter/test/widgets/editable_text_test.dart:5810]: (same below)

**Review by goderbauer — APPROVED** [review]
LGTM with some comments about the tests.
