### PR TITLE
Fix DropdownButtonFormField icon not vertically centered

### LINKED ISSUE #157074: DropdownButtonFormField arrow icon is misaligned vertically
### Steps to reproduce

1. Run sample
2. Observe dropdown icon is aligned to where the content would be instead of the field as a whole

### Expected results

The dropdown icon should be vertically centered within the form field.

### Actual results

The dropdown icon is centered vertically relative to the selected content.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
              child: SizedBox(
                width: 200,
                child: DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: InputDecoration(
                    labelText: 'Label text',
                  ),
                  items: [
                    DropdownMenuItem(
                      value: 'selected',
                      child: Text('Selected item'),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Flutter:
image

M3 Design:
Material 3 dropdown phases design

</details>

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.27.0-1.0.pre.87, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
    ! Flutter version 3.27.0-1.0.pre.87 on channel [user-branch] at C:\Users\bscho\.puro\envs\master\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Warning: `flutter` on your path resolves to C:\Users\bscho\.puro\envs\stable\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\bscho\.puro\envs\master\flutter. Consider adding       
      C:\Users\bscho\.puro\envs\master\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\bscho\.puro\envs\stable\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\bscho\.puro\envs\master\flutter. Consider adding
      C:\Users\bscho\.puro\envs\master\flutter\bin to the front of your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 9bb056822e (62 minutes ago), 2024-10-16 22:52:18 -0400
    • Engine revision e2188ee9ab
    • Dart version 3.6.0 (build 3.6.0-334.2.beta)
    • DevTools version 2.40.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\bscho\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35312.102
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\bscho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.89

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `DropdownButtonFormField` suffix icon vertical alignment when `DropdownButtonFormField.inputDecoration` is provided without a hint text.

### Before:

The dropdown icon is misaligned vertically:

image

### After:

The dropdown icon is aligned vertically:

image

## Related Issue

Fixes [DropdownButtonFormField arrow icon is misaligned vertically](https://github.com/flutter/flutter/issues/157074) 

## Tests

Adds 1 test.

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
It's really good that https://github.com/flutter/flutter/pull/159975 simplified the solution here.

LGTM but let's see if the Google tests pass.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -1609,7 +1610,12 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
     // visible only for filled dropdown button, see:
     // https://m2.material.io/components/menus#dropdown-menu
     if (widget._inputDecoration != null) {
-      InputDecoration effectiveDecoration = widget._inputDecoration!;
+      InputDecoration effectiveDecoration = widget._inputDecoration!.copyWith(
+        // Override the suffix icon constraints to allow the
+        // icon alignment to match the regular dropdown button.
+        suffixIconConstraints: const BoxConstraints(minWidth: 40.0),
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown.dart:1616]: It looks like there are some Google failures where some text that used to fit inside of the dropdown no longer fits, as if the horizontal space available in the field has been reduced. Is that due to this minWidth constraints change? Is that horizontal space change intentional?

Comment (bleroux) [reply packages/flutter/lib/src/material/dropdown.dart]: Oh, interesting!

> as if the horizontal space available in the field has been reduced

I don't remember why we choose to set the minWidth to 40.0. Maybe something from a previous version of the PR.
I updated the PR to set minWidth to 24.0. But it won't be enough to get the same available horizontal space for the input compared to before this PR. 

The reason is that for InputDecoration there is 4.0 default gap between the input and the suffixIcon.
Previous version of the DropdownButtonFormField did not rely on InputDecoration.suffixIcon so it was not impacted by this gap.

I added an experimental commit to this PR to make it possible to remove this gap. This will not be the final solution, it is only a temporary commit to see if it helps with the Google testing failures.

Comment (bleroux) [reply packages/flutter/lib/src/material/dropdown.dart]: @justinmc Are there many Google testing failures now?
The PR is in an experimental state (see my previous comment). The number and the kind of Google testing failures will determine how to proceed there. Thanks for having a look when you will get bandwidth (no hurry there).

Comment (justinmc) [reply packages/flutter/lib/src/material/dropdown.dart]: I don't see any failures of the sort that I mentioned, where text no longer fits. In fact, I see some case where more text now fits than did before. However, the suffix is very close to the right edge now.

Sorry I missed this notification, feel free to ping me if I disappear again :)

**Comment by bleroux** [comment]
Many thanks for the feedback 🙏 .
Based on https://github.com/flutter/flutter/pull/163205#discussion_r2049746555. I will mark this PR as draft, file a separate PR to make the inputDecoration prefix and suffix gaps configurable. And then come back to this PR. Especially trying to understand in which cases "the suffix is very close to the right edge now".

**Comment by justinmc** [comment]
Here's what I meant by the suffix icon being close to the right side:

| The master branch | Your screenshot of this PR in the description | This PR currently |
| --- | --- | --- |
| Screenshot 2025-04-18 at 11 23 33 AM | 412859218-b5704453-66a3-4cb2-97ff-bef556bff377 | Screenshot 2025-04-18 at 11 22 13 AM |

You can see in the PR currently the suffix icon is further to the right than it was before you changed the PR.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
              child: SizedBox(
                width: 200,
                child: DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: InputDecoration(
                    fillColor: Colors.blueGrey.withOpacity(0.2),
                    filled: true,
                    labelText: 'Label text',
                  ),
                  items: [
                    DropdownMenuItem(
                      value: 'selected',
                      child: Text('Selected item'),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by bleroux** [comment]
Wow, thanks a lot for providing this sample and the screenshot.
For the moment, I'm surprised that the screenshot in my PR description did not match the result you got. I will try to find why there is such a discrepancy (maybe related to another InputDecoration parameter or maybe related to the platform used to run the sample). Anyway, thanks a lot for providing these very useful feedback 🙏

**Comment by bleroux** [comment]
@justinmc I updated the PR based on your last [comment](https://github.com/flutter/flutter/pull/163205#issuecomment-2815983185) and our discussion on https://github.com/flutter/flutter/pull/167558#issuecomment-2829544119

It turned out that the fix, in order to compute the correct suffixIconConstraints, should take into account if the input decoration is filled or outlined.

Because for a filled or outlined decoration the right padding is directly provided by the constraints added to the suffix icon, for instance constraints on mobile are 48x48 which means a left and right padding of 12.0. (FYI, on desktop it is be 8.0 because the suffixIconConstraints is 40x40, this is probably not intended as from the M3 spec, visual density usually applies only on the vertical direction, I will check that and file an issue if needed). 

I updated the fix accordingly. Let me know how it goes with the Google tests.

And let me try to explain the layout:

### Before the fix

DropdownButtonFormField was positioning the icon by setting the input decoration content to a Row containing both the selected item label and the icon (24x24).

For a filled or outlined decoration, the horizontal layout was: leftPadding (16.0) | selected item label | icon (24.0) | rightPadding (16.0). 
(16.0 padding since very recently because it is due to https://github.com/flutter/flutter/pull/162157, before it was 12.0).

For a non-filled and non-outlined decoration, it was: leftPadding (0.0) | selected item label | icon (24.0) | rightPadding (0.0)

### With the fix

DropdownButtonFormField is positioning the icon by setting the input decoration suffixIcon and suffixIconConstraints.

For a filled or outlined decoration, the horizontal layout is: leftPadding (16.0) | selected item label | suffixIconGap (4.0) | icon (24.0) | rightPadding (12.0). 
Here the right padding is 12.0 and this is the compliant padding from the M3 spec: when there is no suffix icon right padding should be 16.0, when the is a suffixIcon it should be 12.0). 
This means that, with the fix, the content's width is the same as before this fix. The difference is the icon moving by 4.0 pixel to the right (which will restore its position as before https://github.com/flutter/flutter/pull/162157).

For a non-filled and non-outlined decoration, it is: leftPadding (0.0) | selected item label | icon (24.0) | suffixIconGap (4.0) | rightPadding (0.0)
Here the difference will be the content width being reduced by 4.0 pixel and the icon should be at the same horizontal position.


Here is combined screenshot to illustrate this. The top 3 fields showcase the fix, the bottom ones were captured without the fix:

image

<details><summary>Code sample for the screenshot</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  final bool filled = true;
  static const List<DropdownMenuItem<String>> items = [
    DropdownMenuItem(value: 'selected', child: Text('Selected item')),
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 200,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              spacing: 4.0,
              children: [
                DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: const InputDecoration(labelText: 'Raw'),
                  // Before https://github.com/flutter/flutter/pull/163205, width could be 176.
                  selectedItemBuilder:
                      (context) => [Container(height: 24, width: 172, color: Colors.amber)],
                  items: items,
                ),
                DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: const InputDecoration(labelText: 'Filled', filled: true),
                  selectedItemBuilder:
                      (context) => [Container(height: 24, width: 144, color: Colors.amber)],
                  items: items,
                ),
                DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: const InputDecoration(
                    labelText: 'Outlined',
                    border: OutlineInputBorder(),
                  ),
                  selectedItemBuilder:
                      (context) => [Container(height: 24, width: 144, color: Colors.amber)],
                  items: items,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

``` 
</details>

**Comment by justinmc** [comment]
Nice, I ran it locally and confirmed that the layout seems to be correct as you explained. The Google test check has disappeared though, let me try re-adding it.

**Review by justinmc — COMMENTED** [review]
I'm still seeing a horizontal change in the position of the suffix icon with this PR, I think that's not intentional because I don't see a horizontal change in the comparison image that you posted above in https://github.com/flutter/flutter/pull/163205#issuecomment-2830584566, right? I think this is happening only in outlined inputs. Repro code below.

Otherwise all of the other Google test failures look expected (the arrow moved slightly vertically).

| Before this PR | After this PR |
| --- | --- |
|  | |

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
              child: SizedBox(
                width: 200,
                child: DropdownButtonFormField<String>(
                  onChanged: (_) {},
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'Label text',
                  ),
                  items: [
                    DropdownMenuItem(
                      value: 'selected',
                      child: Text('Selected item'),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

**Review by justinmc — APPROVED** [review]
Renewing my LGTM :+1: . I reviewed all Google test failures and they are expected. There was some trouble with Frob but it's working now, this can be autosubmitted.
