### PR TITLE
Disposes test restoration manager when accessed by bindings

### LINKED ISSUE #169119: Leak memory in tests when dragging a `SingleChildScrollView`
### Steps to reproduce

1. `flutter test` on the sample code

### Expected results

The tests should pass

### Actual results

The test are failing because of a `TestRestorationManager` and a `RestorationBucket` are not disposed

### Code sample

<details open><summary>Code sample</summary>

You can also checkout https://github.com/ValentinVignal/flutter_app_stable/tree/leak-memory/single-child-scrollable

```dart
# test/flutter_test_config.dart
import 'dart:async';

import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

Future<void> testExecutable(FutureOr<void> Function() testFunction) async {
  LeakTesting.enable();
  await testFunction();
}

```

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [for (var i = 0; i < 100; i++) Text('Item $i')],
          ),
        ),
      ),
    );
  }
}

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(MyWidget());

    expect(find.text('Item 0').hitTestable(), findsOne);
    expect(find.text('Item 50').hitTestable(), findsNothing);

    await tester.drag(
      find.byType(SingleChildScrollView),
      const Offset(0, -200),
    );

    await tester.pump();

    expect(find.text('Item 0').hitTestable(), findsNothing);
    expect(find.text('Item 30').hitTestable(), findsOne);
  });
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
00:03 +1 -1: (tearDownAll) [E]                                                                                                                                                                            
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/leak_tracking/TROUBLESHOOT.md
            notDisposed:
              total: 2
              objects:
                TestRestorationManager:
                  test: Counter increments smoke test
                  identityHashCode: 77264436
                RestorationBucket:
                  test: Counter increments smoke test
                  identityHashCode: 208072902
            
            
  
  package:matcher                                              expect
  package:leak_tracker_testing/src/leak_testing.dart 69:24     LeakTesting.collectedLeaksReporter.<fn>
  package:leak_tracker_flutter_testing/src/testing.dart 72:37  maybeTearDownLeakTrackingForAll
  ===== asynchronous gap ===========================
  dart:async                                                   _CustomZone.registerBinaryCallback
  package:flutter_test/src/test_compat.dart 302:3              _tearDownForTestFile
  

To run this test again: /Users/valentinvignal/development/flutter/bin/cache/dart-sdk/bin/dart test /Users/valentinvignal/Projects/flutter_app_stable/test/widget_test.dart -p vm --plain-name '(tearDownAll)'
00:03 +1 -1: Some tests failed.  
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-x64, locale en-US) [915ms]
    • Flutter version 3.29.3 on channel stable at /Users/valentinvignal/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (6 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [3.7s]
    • Android SDK at /Users/valentinvignal/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/valentinvignal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0) [4.0s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ✗ Unable to get list of installed Simulator runtimes.
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [29ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [28ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.100.2) [25ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [6.7s]
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.4.1 24E263 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [452ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by hgraceb**
Fixes #169119

## Details

The error caused by drag is due to the reference to `ServicesBinding.instance.restorationManager` in the `ScrollableState.saveOffset` method.

https://github.com/flutter/flutter/blob/018897e3f12c5783fb025bcbd92515a69d4d5c32/packages/flutter/lib/src/widgets/scrollable.dart#L648-L656

The TestWidgetsFlutterBinding now only cleans up the `restorationManager` when `reset` is called. Therefore, we need to find an appropriate place to clean up the `restorationManager`.

https://github.com/flutter/flutter/blob/018897e3f12c5783fb025bcbd92515a69d4d5c32/packages/flutter_test/lib/src/binding.dart#L239-L263

https://github.com/flutter/flutter/blob/018897e3f12c5783fb025bcbd92515a69d4d5c32/packages/flutter_test/lib/src/widget_tester.dart#L188-L193

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thank you!

File: packages/flutter_test/test/widget_tester_leaks_free_test.dart [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/services.dart';
+import 'package:flutter/widgets.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';
+
+void main() {
+  LeakTesting.enable(); // Enable leak testing and use default collectedLeaksReporter.
```
Comment (dkwingsmt) [inline packages/flutter_test/test/widget_tester_leaks_free_test.dart:11]: Do we really need this statement? Leak testing isn't enabled unless the `LEAK_TRACKING` flag is set, but this is done for a reason. All Flutter unit tests are currently configured with leak tracking in this way, and I don't see a reason why `WidgetTester` needs special treatment.

And if this is removed, shall we move this test to `widget_tester_test.dart`?

File: packages/flutter_test/test/widget_tester_leaks_free_test.dart [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+  // Regression test for https://github.com/flutter/flutter/issues/169119.
+  testWidgets('Disposes test restoration manager when accessed by bindings', (
```
Comment (dkwingsmt) [inline packages/flutter_test/test/widget_tester_leaks_free_test.dart]: The following test name seems clearer to me
```suggestion
  testWidgets('Does not leak if restorationManager is accessed', (
```

File: packages/flutter_test/test/widget_tester_leaks_free_test.dart (hunk 1 above)
Comment (hgraceb) [reply packages/flutter_test/test/widget_tester_leaks_free_test.dart:11]: I tried removing this piece of code, and I also temporarily commented out this patch by https://github.com/flutter/flutter/pull/176519/commits/3dabca1687c52a80805b59b4d331b2dc072f6269, but all the tests passed. So it might still need to be explicitly enabled in the code? Or did I miss something?

I found two parts in the existing code that might be related. One is the section that reads the `LEAK_TRACKING` flag, but this is part of `flutter`, and there is no similar handling under `flutter_test`.

https://github.com/flutter/flutter/blob/255b46490ada3c10656eaa7b56552a911b52fd3e/packages/flutter/test/flutter_test_config.dart#L15-L29

The other is the code that tests for memory leaks under `flutter_test`, but it uses a custom `collectedLeaksReporter`, which is also one of the reasons I created a new file to write the test code.

https://github.com/flutter/flutter/blob/255b46490ada3c10656eaa7b56552a911b52fd3e/packages/flutter_test/test/widget_tester_leaks_test.dart#L23-L33

Comment (dkwingsmt) [reply packages/flutter_test/test/widget_tester_leaks_free_test.dart:11]: Yeah. I've tested locally and you're right. Let me ask around and see what's the best approach. Thank you for you detailed reply!

File: packages/flutter_test/lib/src/binding.dart [hunk 3]
```diff
@@ -1067,6 +1067,8 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
         Container(key: UniqueKey(), child: _postTestMessage),
       ); // Unmount any remaining widgets.
       await pump();
+      // _restorationManager?.dispose();
+      // _restorationManager = null;
```
Comment (justinmc) [inline packages/flutter_test/lib/src/binding.dart]: @hgraceb Looks like you accidentally pushed a commit that comments some things out?

Comment (hgraceb) [reply packages/flutter_test/lib/src/binding.dart]: @justinmc That was to verify the issue mentioned in https://github.com/flutter/flutter/pull/176519#discussion_r2418573748. I'm not sure if the results are completely consistent between local and CI. I have reverted it.

**Comment by dkwingsmt** [comment]
I've filed a PR https://github.com/flutter/flutter/pull/176992 that adds CI tasks to test leak tracking for `flutter_test`. Let's wait until that PR is decided.

**Review by victorsanni — APPROVED** [review]

**Review by victorsanni — COMMENTED** [review]
The Google testing failure is caused by this [failing test](https://github.com/flutter/packages/blob/2d4f8ef103362266c3e1b3710c25d4298358d8d6/packages/go_router/test/extra_codec_test.dart#L55) in go_router.

**Comment by justinmc** [comment]
@hgraceb Any thoughts on what should be done about the failing go_router test? Is that something that this PR could work around?

**Comment by hgraceb** [comment]
@victorsanni @justinmc @ValentinVignal 

The modifications in the `go_router` PR at [#7456](https://github.com/flutter/packages/pull/7546/files#diff-cadb5f44a1e75aa2a6e8a28c017283db7218cafdd8e170731db9aa655e2ec22aR77) are preventing the current PR from being merged.

From my understanding, the changes in [#7456](https://github.com/flutter/packages/pull/7546/files#diff-cadb5f44a1e75aa2a6e8a28c017283db7218cafdd8e170731db9aa655e2ec22aR77) and my current modifications are equivalent; both aim to address the leakage issue with `TestWidgetsFlutterBinding.restorationManager` after enabling leak testing. However, the changes in [#7456](https://github.com/flutter/packages/pull/7546/files#diff-cadb5f44a1e75aa2a6e8a28c017283db7218cafdd8e170731db9aa655e2ec22aR77) seem more like a temporary patch.

I believe the changes in `go_router` should be reverted, and after merging the current PR, the effect would remain the same as before. However, if I submit a separate PR for `go_router` now, both tests will fail; they will only pass if changes are made on both sides simultaneously. 

Does anyone have good suggestions on how to proceed?

**Comment by ValentinVignal** [comment]
1. Revert the unwanted changes in go_router + disable leak memory testing for those specific tests, for example using:
```dart
  testWidgets(
    'Date formatting test',
    (WidgetTester tester) async {},
    experimentalLeakTesting: LeakTesting.settings.withIgnored(
      classes: const ['TestRestorationManager'],
    ),
  );
```

and add a TODO to remove it when go_router's minimum flutter version includes this PR

2. Merge this PR
3. Remove the ignore part in go_router when the minimum version of flutter includes this fix.
```dart
experimentalLeakTesting: LeakTesting.settings.withIgnored(
      classes: const ['TestRestorationManager'],
    ),
```


What do you think of that?

**Comment by hgraceb** [comment]
@ValentinVignal This sounds great, I submitted a PR: https://github.com/flutter/packages/pull/10276.
