### PR TITLE
Double double tap toggles instead of error

### LINKED ISSUE #33740: Assertion '_toolbar == null' failure in TextField double-tap
## Steps to Reproduce
We received this error stack trace from a crash report.

## Logs
```
Thread 0 main thread_AssertionError: 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 357 pos 12: '_toolbar == null': is not true.
at _AssertionError._doThrowNew	(errors_patch.dart:40 )
at _AssertionError._throwNew	(errors_patch.dart:36 )
at TextSelectionOverlay.showToolbar	(text_selection.dart:357 )
at EditableTextState.showToolbar	(editable_text.dart:1393 )
at _TextFieldState._handleDoubleTapDown	(text_field.dart:800 )
at _TextSelectionGestureDetectorState._handleTapDown	(text_selection.dart:821 )
at TapGestureRecognizer._checkDown.<anonymous closure>	(tap.dart:328 )
at GestureRecognizer.invokeCallback	(recognizer.dart:181 )
at TapGestureRecognizer._checkDown	(tap.dart:328 )
at TapGestureRecognizer.didExceedDeadlineWithEvent	(tap.dart:292 )
at PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure>	(recognizer.dart:429 )
at _rootRun	(zone.dart:1120 )
at _CustomZone.run	(zone.dart:1021 )
at _CustomZone.runGuarded	(zone.dart:923 )
at _CustomZone.bindCallbackGuarded.<anonymous closure>	(zone.dart:963 )
at _rootRun	(zone.dart:1124 )
at _CustomZone.run	(zone.dart:1021 )
at _CustomZone.bindCallback.<anonymous closure>	(zone.dart:947 )
at Timer._createTimer.<anonymous closure>	(timer_patch.dart:21 )
at _Timer._runTimers	(timer_impl.dart:382 )
at _Timer._handleMessage	(timer_impl.dart:416 )
at _RawReceivePortImpl._handleMessage	(isolate_patch.dart:171 )
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

An error was being logged when the user double tapped twice on an empty part of a TextField.  This was because we would attempt to show the selection toolbar when it already was being shown.

This PR solves this by toggling the selection menu instead.  On native Android, it looks like a double tap doesn't show the selection menu at all.  As we continue to work on matching native behavior for text editing we should implement that behavior, but for now this seems logical and prevents an error.

doubledouble

## Related Issues

Closes https://github.com/flutter/flutter/issues/33740

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -721,8 +721,9 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
         from: details.globalPosition,
         cause: SelectionChangedCause.forcePress,
       );
-      if (_shouldShowSelectionToolbar)
+      if (_shouldShowSelectionToolbar) {
         _editableTextKey.currentState.showToolbar();
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_field.dart]: Would 2 long presses trigger the bug, i.e. should this be toggleToolbar?

Comment (justinmc) [reply packages/flutter/lib/src/material/text_field.dart]: Yes, good catch!

**Review by HansMuller — APPROVED** [review]
LGTM
