### PR TITLE
[gen_l10n] Warn users when placeholder types are converted to 'num' when using pluralization

### LINKED ISSUE #98868: [[gen_l10n]]: Pluralization in arb files is not producing expected output
## Steps to Reproduce

I'm on Flutter 2.10.1

Run `flutter gen-l10n` with this arb file:

```json
// lib/l10n/source.arb
{
 "@@locale": "en",
 "consentActiveTools1": "{{count}, plural, =0{No active services} =1{One active service} other{{count} active services}}",
    "@consentActiveTools1": {
        "description": "Count of active services",
        "placeholders": {
            "count": {
                "type": "int"
            }
        }
    },
    "consentActiveTools2": "{count, plural, =0{No active services} =1{One active service} other{{count} active services}}",
    "@consentActiveTools2": {
        "description": "Count of active services",
        "placeholders": {
            "count": {
                "type": "int"
            }
        }
    },
    "consentActiveTools3": "{count,plural, =0{No active services}=1{One active service}other{{count} active services}}",
    "@consentActiveTools3": {
        "description": "Count of active services",
        "placeholders": {
            "count": {}
        }
    },
    "consentActiveTools": "{{count},plural, =0{No active services}=1{One active service}other{{count} active services}}",
    "@consentActiveTools": {
        "description": "Count of active services",
        "placeholders": {
            "count": {
                "type": "int"
            }
        }
    }
}
```

and this `l10n.yml`

```yml
arb-dir: lib/l10n
template-arb-file: source.arb
output-localization-file: app_localizations.dart
synthetic-package: true
output-class: AppLocalizations
nullable-getter: false
```

**Expected results:** 

I would expect all the examples above to result in the following code:

```dart
@override
String consentActiveTools(int count) {
  return intl.Intl.pluralLogic(
    count,
    locale: localeName,
    zero: 'No active services',
    one: 'One active service',
    other: '$count active services',
  );
}
```

**Actual results:** 

However, I don't get the expected result for any of the examples.

```dart
  @override
  String consentActiveTools1(int count) {
    return '{$count, plural, =0{No active services} =1{One active service} other{$count active services}}';
  }

  @override
  String consentActiveTools2(num count) {
    return intl.Intl.pluralLogic(
      count,
      locale: localeName,
      zero: 'No active services',
      one: 'One active service',
      other: '$count active services',
    );
  }

  @override
  String consentActiveTools3(num count) {
    return intl.Intl.pluralLogic(
      count,
      locale: localeName,
      zero: 'No active services',
      one: 'One active service',
      other: '$count active services',
    );
  }

  @override
  String consentActiveTools(int count) {
    return '{$count,plural, =0{No active services}=1{One active service}other{$count active services}}';
  }
```

-----

On Flutter 2.8.1 I would get the expected code with the following arb content:
```json
{
    "consentActiveTools": "{count, plural, =0{No active services} =1{One active service} other{{count} active services}}",
    "@consentActiveTools": {
        "description": "Count of active services",
        "placeholders": {
            "count": {}
        }
    }
}
```

Please let me know if there's anything left which you need to figure this out.

### PR DESCRIPTION
**Pull request by thkim1011**
See title. This PR refactors logging so that the logger is saved as an instance variable of the `LocalizationsGenerator` class, and adds a warning when there is a pluralization placeholder whose type isn't num.

Fixes #98868

Tested locally:
```
Multiple devices found:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm (Rosetta)
Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Placeholders for plurals are automatically converted to type 'num'.
Placeholders for plurals are automatically converted to type 'num'.
Running "flutter pub get" in i18n_test...                          698ms
```
I didn't think I needed to add tests here since there's really no change other than logging.

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
You can ask @Hixie for a "test exemption" however it might be simplest to just include one.

**Comment by thkim1011** [comment]
Hey @HansMuller, I just made the change you recommended, added a test (turns out testing logs are not too bad), and fixed up the rest of the tests that were affected by changing the `LocalizationsGenerator` constructor.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 1]
```diff
@@ -1141,6 +1148,16 @@ class LocalizationsGenerator {
       );
     });
 
+    // Warn users when placeholder types are overrided to 'num'.
+    for (final Message message in messages) {
+      if (message.isPlural) {
+        final Placeholder countPlaceholder = message.getCountPlaceholder();
+        if (countPlaceholder.type != null && countPlaceholder.type != 'num') {
+          logger.printWarning("Placeholders for plurals are automatically converted to type 'num'.");
```
[the remark this answers is not in the document]
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart]: Fixed!

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 2]
```diff
@@ -1141,6 +1148,22 @@ class LocalizationsGenerator {
       );
     });
 
+    // Warn users when placeholder types are overrided to 'num'.
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:1151]: This comment probably isn't necessary; at the moment it doesn't describe the entire block.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 3]
```diff
@@ -1141,6 +1148,22 @@ class LocalizationsGenerator {
...
+    for (final Message message in messages) {
+      if (message.isPlural) {
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:1153]: These tests/warnings are great.

**Review by HansMuller — APPROVED** [review]
The bots noticed some trailing spaces. Other than that and a trivial point about a comment, this is ready to land.
