### PR TITLE
Fix GestureDetector long press callback handling

### LINKED ISSUE #62895: onLongPress and onSecondaryLongPress cannot be used together in a Gesture Detector
## Steps to Reproduce

See the following DartPad and run it: https://dartpad.dev/b9360fd9b3c93ae8125af4992b3decf6

**Expected results:** long pressing `Hello, World!` should show a snack bar.

**Actual results:** only secondary long pressing it shows a snack bar. If I remove the `onSecondaryLongPress` callback, the `onLongPress` works again.

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

Supplying any secondary long press callback to `GestureDetector` would currently override **any** primary long press callback.  
This PR simply fixes this.

cc @dkwingsmt 

## Related Issues

* Fixes #62895

## Tests

I added the following tests:

* Regression test for the fix.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/gesture_detector.dart [hunk 1]
```diff
@@ -702,8 +702,7 @@ class GestureDetector extends StatelessWidget {
   Widget build(BuildContext context) {
     final Map<Type, GestureRecognizerFactory> gestures = <Type, GestureRecognizerFactory>{};
 
-    if (
-      onTapDown != null ||
+    if (onTapDown != null ||
       onTapUp != null ||
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/gesture_detector.dart:706]: nit: Indent the other lines so that they're aligned with the first line

**Review by dkwingsmt — APPROVED** [review]
LGTM except for a nit formatting issue

File: packages/flutter/lib/src/widgets/gesture_detector.dart (hunk 1 above)
Comment (creativecreatorormaybenot) [reply packages/flutter/lib/src/widgets/gesture_detector.dart]: Thanks, fixed 🙂
