### PR TITLE
Fix lack of ancestor notification when a focus node is unfocused.

### LINKED ISSUE #43497: onFocusChange not called for FocusScopeNode when losing focus via unfocus()
## Steps to Reproduce

Suppose you have the following stateful widget that wraps some `TextField`s with a `FocusScope`:

```
class FormState extends State<MyForm> {
  FocusScopeNode _focusScopeNode;

  @override
  void initState() {
    super.initState();
    _focusScopeNode = FocusScopeNode();
  }

  @override
  void dispose() {
    _focusScopeNode.dispose();
    super.dispose();
  }

  void _onFocusChange(bool hasFocus) {
    print('hasFocus changed to $hasFocus');
  }

  void clearFocus() {
    print(_focusScopeNode.hasFocus);
    _focusScopeNode.focusedChild.unfocus();
    Future.microtask(() {
      print(_focusScopeNode.hasFocus);
    });
  }
  
  @override
  Widget build(BuildContext context) {
    return FocusScope(
      node: _focusScopeNode,
      onFocusChange: _onFocusChange,
      child: Column(
        children: <Widget>[...],
      ),
    );
  }
}
```

Tapping into a `TextField` correctly calls on `onFocusChange` and prints `focus has changed to true`.
However, when i manually clear the focus using `_focusScopeNode.focusedChild.unfocus()`, `onFocusChange` is not called again. To verify that the `FocusScopeNode` really loses its focus, i added some print statements and a microtask, which confirms that `_focusScopeNode.hasFocus` is true before calling `unfocus()` on the focused child and false after.

**Target Platform: Android**
**Target OS version/browser: Android 10**
**Devices: Pixel 3**

## Flutter Doctor

```
[√] Flutter (Channel master, v1.10.7-pre.99, on Microsoft Windows [Version 10.0.18362.418], locale de-DE)
    • Flutter version 1.10.7-pre.99 at C:\Flutter
    • Framework revision 2de1e4f4a1 (3 weeks ago), 2019-09-30 22:05:53 -0400
    • Engine revision 4981512815
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 692230b484)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\babo\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\babo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Pixel 3 • 89CX083RU • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This fixes a problem when unfocusing focus nodes where the ancestor focus nodes and scopes don't receive notification that a child was unfocused.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/43497

## Tests

- Added a bunch more tests that make sure that ancestors are all notified when focus changes in a variety of situations.

## Breaking Change

- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by gspencergoog** [comment]
cc @krisgiesing

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -1374,22 +1373,57 @@ class FocusManager with DiagnosticableTreeMixin {
   // The set of nodes that need to notify their listeners of changes at the next
   // update.
   final Set<FocusNode> _dirtyNodes = <FocusNode>{};
+  FocusNode _unfocusedNode;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: I don't fully understand what the purpose of this property is.

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 2]
```diff
@@ -745,4 +745,134 @@ void main() {
     await tester.pump();
     expect(parent1.focusedChild, equals(child2));
   });
+  testWidgets('Ancestors get notified exactly as often as needed if focused child changes focus.', (WidgetTester tester) async {
+    bool topFocus;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/focus_manager_test.dart]: It feels odd that in the test below not having focus is represented as this variable either being null or false. Unless there's a reason for the null/false distinction, should these just be initialized to false?

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: I added a comment, but it's the node that is marked to be unfocused the next time the focus changes are applied.

File: packages/flutter/test/widgets/focus_manager_test.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/focus_manager_test.dart]: There is a reason: `null` means that the notification callback was never called. False means that it was called, but the associated node was set to "not focused".  I wanted to test to make sure that 1) the callback was called, and 2) that it was called with the expected value.  In addition, I wanted to make sure that it was not called more than once per `pump`, so I added the `*Notify` counts.

I suppose I could initialize this to false, and just use the notification count to make sure it was called, if that's clearer.

Comment (goderbauer) [reply packages/flutter/test/widgets/focus_manager_test.dart]: Oh, yeah, I thought that's what the counts were for... I think that would make this a little clearer.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 3]
```diff
@@ -705,18 +705,17 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
 
   // Marks the node as dirty, meaning that it needs to notify listeners of a
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: This comment seems outdated as nothing is marked as dirty anymore?

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: I see. I think this has an unfortunate name then. From the name I got that this node has already been unfocused. Instead it's more future looking: This is the node that will get unfocused. I wonder if we can get a better name. (The comment already helps).

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 4]
```diff
@@ -1371,25 +1370,64 @@ class FocusManager with DiagnosticableTreeMixin {
...
     if (_primaryFocus == node || _nextFocus == node) {
-      if (_primaryFocus == node) {
-        _primaryFocus = null;
-      }
       if (_nextFocus == node) {
         _nextFocus = null;
       }
-      _dirtyNodes.add(node);
+      if (_primaryFocus == node) {
+        _unfocusedNode = node;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: What if unfocused is already set to something else? If that can't happen, maybe assert its null before setting it here?

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Hmm. I *think* it can' only either be null, or whatever `_primaryFocus` is. I'll add an assert and see.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 3 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Updated the comment and added some more context.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: OK, I renamed this to `_markedForUnfocus`, and I also renamed `_nextFocus` to `_markedForFocus`.

File: packages/flutter/test/widgets/focus_manager_test.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/focus_manager_test.dart]: OK, I set the bools all to false, and rely on the counts to make sure it was called the right number of times.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 5]
```diff
@@ -664,15 +664,15 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
...
     assert(focusPrevious != null);
-    if (!hasFocus && (_manager != null && _manager._nextFocus != this)) {
+    if (!hasFocus && (_manager == null || _manager._markedForFocus != this)) {
       return;
     }
     if (!hasPrimaryFocus) {
       // If we are in the focus chain, but not the primary focus, then unfocus
       // the primary instead.
       _manager?.primaryFocus?.unfocus(focusPrevious: focusPrevious);
     }
```
Comment (Quijx) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: Maybe not entirely related to this issue, but why is `_manager?.primaryFocus?.unfocus(focusPrevious: focusPrevious);` called when `hasFocus` is `true` and `hasPrimaryFocus` is `false`? The doc of `unfocus` states:
> Has no effect on nodes that return true from [hasFocus], but false from [hasPrimaryFocus].

Either the doc or the implementation seems to be wrong.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 6]
```diff
@@ -1378,41 +1380,79 @@ class FocusManager with DiagnosticableTreeMixin, ChangeNotifier implements Diagn
...
-        _nextFocus = null;
+      if (_primaryFocus == node) {
+        assert(_markedForUnfocus == null);
+        _markedForUnfocus = node;
       }
-      _dirtyNodes.add(node);
       _markNeedsUpdate();
-    }
-    assert(_focusDebug('Unfocused node $node:', <String>['primary focus is $_primaryFocus', 'next focus will be $_nextFocus']));
+     }
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: uber-nit: indentation seems off here. Remove one space?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 5 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Looks like the docs are wrong.  Thanks for pointing this out!

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 6 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Fixed.
