### PR TITLE
[WillPopScope] handle new route if moved from one navigator to another

### LINKED ISSUE #89133: [WillPopScope] throws assertion if widget moved to another navigator with saving state
I create responsibility widget for displaying pages on large screen in two containers, left and right. on small screens pages merged in one navigator. if page have **WillPopScope** widget, after moving pages to another navigator throws assertion below.  for prevent lose state of page, page wrapped to **KeyedSubtree**
```dart
KeyedSubtree(key: _key, child: builder.call(context));
```
WillPopScope widget keep reference on router, but widget moving to another location in tree, and actual router in tree widget is different in new navigator.

https://github.com/flutter/flutter/blob/2512ecd9f66c573cc91cb59248610ec41876f3ff/packages/flutter/lib/src/widgets/will_pop_scope.dart#L73

https://github.com/flutter/flutter/blob/2512ecd9f66c573cc91cb59248610ec41876f3ff/packages/flutter/lib/src/widgets/will_pop_scope.dart#L88

<details>
  <summary>Sample code</summary>

```dart


import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MaterialApp(
    title: 'Demo',
    home: MyNavigator(),
  ));
}

class MyNavigator extends StatefulWidget {
  const MyNavigator({Key? key}) : super(key: key);

  @override
  _MyNavigatorState createState() => _MyNavigatorState();
}

class _MyNavigatorState extends State<MyNavigator> {
  final List<Page<dynamic>> _rightPages = <Page<dynamic>>[
    _SimplePage(
      key: UniqueKey(),
      builder: (BuildContext context) {
        return const TestPage(
          title: 'left page',
          color: Colors.blue,
        );
      },
    )
  ];

  final List<Page<dynamic>> _leftPages = <Page<dynamic>>[
    _SimplePage(
      key: UniqueKey(),
      builder: (BuildContext context) {
        return const TestPage(
          title: 'right page',
          color: Colors.yellow,
        );
      },
    )
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          if (constraints.maxWidth < 500) {
            return _buildNavigator(_rightPages + _leftPages);
          }
          return Row(
            children: <Widget>[
              Container(
                color: Colors.red,
                width: 300,
                child: _buildNavigator(_rightPages),
              ),
              Expanded(child: _buildNavigator(_leftPages)),
            ],
          );
        },
      ),
    );
  }

  Widget _buildNavigator(List<Page<dynamic>> pages) {
    return Navigator(
      pages: pages,
      onPopPage: (Route<dynamic> route, dynamic result) {
        if (!route.didPop(result)) {
          return false;
        }
        return true;
      },
    );
  }
}

class _SimplePage extends Page<dynamic> {
  _SimplePage({
    required this.builder,
    required LocalKey key,
  })  : _key = GlobalKey(),
        super(key: key);

  final WidgetBuilder builder;
  final GlobalKey<dynamic> _key;

  @override
  Route<dynamic> createRoute(BuildContext context) {
    return MaterialPageRoute<dynamic>(
        settings: this,
        builder: (BuildContext context) {
          return KeyedSubtree(key: _key, child: builder.call(context));
        });
  }
}

class TestPage extends StatefulWidget {
  const TestPage({
    Key? key,
    required this.title,
    required this.color,
  }) : super(key: key);

  final String title;
  final Color color;

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<TestPage> {
  int timestamp = 0;

  @override
  void initState() {
    timestamp = DateTime.now().millisecondsSinceEpoch;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return true;
      },
      child: Scaffold(
        backgroundColor: widget.color,
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Text(timestamp.toString()),
        ),
      ),
    );
  }

  @override
  void dispose() {
    print('dispose: $timestamp');
    super.dispose();
  }
}
  ```
</details>

## Steps to Reproduce

1. Run `flutter create bug`.
2. Delete everything in main.dart and paste the above:
3. run on any desktop
4. resize window to small size

**Expected results:** 
not Failed assertion, displaying two pages in the vertical containers or single page

**Actual results:** 
```dart
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 135 pos 12: '_route == ModalRoute.of(context)': is not true.
```

**flutter doctor:**
```dart
    [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ru)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
  ```

### PR DESCRIPTION
**Pull request by ivk1800**
fixed https://github.com/flutter/flutter/issues/89133

Navigator 2 allow access to pages stack and we can change it as wish. for example we can move pages to another location in tree, my case it is responsible ui, witch adaptive for large and small screens. but WillPopScope keep reference for route and not handle new location in tree. it is pr fixed it

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/will_pop_scope.dart [hunk 1]
```diff
@@ -85,13 +85,19 @@ class _WillPopScopeState extends State<WillPopScope> {
   @override
   void didUpdateWidget(WillPopScope oldWidget) {
     super.didUpdateWidget(oldWidget);
-    assert(_route == ModalRoute.of(context));
-    if (widget.onWillPop != oldWidget.onWillPop && _route != null) {
+    final ModalRoute<dynamic>? actualRoute = ModalRoute.of(context);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/will_pop_scope.dart:88]: Checking the route should be done in didChangeDependencies

**Review by chunhtai — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/widgets/will_pop_scope.dart (hunk 1 above)
Comment (ivk1800) [reply packages/flutter/lib/src/widgets/will_pop_scope.dart]: @chunhtai can you please make review? and help with failed checks?

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
@ivk1800 Sorry for the late reply, I was out last month.

cirrus seems unhappy, the build must pass before this can be merged

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/89226

**Comment by ivk1800** [comment]
@chunhtai hi, all checks is green, ready for merge?
