### PR TITLE
Fix key events interception by RadioGroup when no Radio is focused.

### LINKED ISSUE #175511: RadioGroup intercepts space key events preventing text input in nested TextField/EditableText widgets
## Summary
In Flutter 3.35.3, the new `RadioGroup` widget intercepts space key events, preventing space characters from being entered in `TextField` or `EditableText` widgets nested within the `RadioGroup`.

## Platform
- **Platform**: Web
- **Flutter Version**: 3.35.3 (introduced with RadioGroup widget)
- **Browser**: Chrome, Firefox (likely all browsers)

## Steps to Reproduce
1. Create a `RadioGroup` containing `Radio` widgets and a `TextField`
2. Run on Flutter Web
3. Select a radio option and focus the `TextField`
4. Try typing space characters
5. Observe that spaces are ignored while other characters work fine

## Expected Behavior
Space characters should be inserted into the `TextField` just like any other character.

## Actual Behavior
Space key presses are consumed by the `RadioGroup` widget and never reach the `TextField`.

## Code Sample
```dart
RadioGroup<TestOption>(
  groupValue: _selectedOption,
  onChanged: (value) => setState(() => _selectedOption = value!),
  child: Column(
    children: [
      ListTile(
        title: Text('Text Input Option'),
        leading: Radio<TestOption>(value: TestOption.textInput),
      ),
      if (_selectedOption == TestOption.textInput)
        TextField(
          // Space key input is ignored here
          decoration: InputDecoration(hintText: 'Spaces ignored...'),
        ),
    ],
  ),
)
```

## Root Cause
The `RadioGroup` widget defines a space key shortcut that intercepts all space key events within its widget tree. In the Flutter source code (`radio_group.dart` lines 94 and 118-132), `RadioGroup` registers this shortcut:

```dart
const SingleActivator(LogicalKeyboardKey.space): VoidCallbackIntent(_toggleFocusedRadio),
```

The `_toggleFocusedRadio()` method:
1. Finds the currently focused radio button
2. If the radio isn't selected, selects it by calling `onChanged(radio.radioValue)`
3. If the radio supports tristate and is already selected, deselects it by calling `onChanged(null)`

This shortcut mechanism consumes space key events before they can bubble down to nested `TextField` or `EditableText` widgets, preventing space characters from being entered in text inputs that are children of the `RadioGroup`.

**Source Reference**: Flutter SDK `radio_group.dart` at `/packages/flutter/lib/src/widgets/radio_group.dart:94`

## Workaround
Use the deprecated individual `Radio` properties (`groupValue`, `onChanged`) instead of `RadioGroup`:

```dart
// Instead of RadioGroup, use individual Radio widgets
Radio<TestOption>(
  value: TestOption.textInput,
  groupValue: _selectedOption,  // deprecated but functional
  onChanged: (value) => setState(() => _selectedOption = value!),
)
```

## Impact
This breaks common UI patterns where radio buttons control the visibility/behavior of text input fields, which is a standard form design pattern.

## Reproduction Project

[flutter_radiogroup_bug_repro.zip](https://github.com/user-attachments/files/22384923/flutter_radiogroup_bug_repro.zip)

Complete reproduction case can be created following the code sample above.

**Test Instructions:**
1. Create a Flutter web app with the code sample
2. Run `flutter run -d chrome`
3. Select "Text Input Option" radio button
4. Try typing spaces in the text field - they will be ignored
5. Compare behavior outside RadioGroup - spaces work there

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/175511

### Description

- Fixes key events interception by `RadioGroup` when no `Radio` is focused.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/radio_group.dart [hunk 1]
```diff
@@ -215,6 +224,24 @@ class _RadioGroupState<T> extends State<RadioGroup<T>> implements RadioGroupRegi
...
+
+  final _RadioGroupState<T> state;
+
+  @override
+  KeyEventResult handleKeypress(BuildContext context, KeyEvent event) {
+    final bool hasFocusedRadio = state._radios.any(
+      (RadioClient<T> radio) => radio.focusNode.hasFocus,
+    );
+    if (!hasFocusedRadio) {
+      // Ignore the event if no radio is focused.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/radio_group.dart]: This comment is not useful, maybe give example why this can be a problem

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this, just left a minor suggestion

File: packages/flutter/lib/src/widgets/radio_group.dart (hunk 1 above)
Comment (ksokolovskyi) [reply packages/flutter/lib/src/widgets/radio_group.dart]: Thanks for the review. I added some more details to the comment. 

```
// Ignore the event if no radio is focused. This prevents this handler
// from unintentionally consuming an event meant for a non-radio widget
// that currently has focus.
```

Do you like it, or do you have any suggestions?

File: packages/flutter/lib/src/widgets/radio_group.dart [hunk 2]
```diff
@@ -95,6 +95,9 @@ class _RadioGroupState<T> extends State<RadioGroup<T>> implements RadioGroupRegi
     const SingleActivator(LogicalKeyboardKey.space): VoidCallbackIntent(_toggleFocusedRadio),
   };
 
+  late final _RadioGroupShortcutManager<T> _radioGroupShortcutManager =
+      _RadioGroupShortcutManager<T>(shortcuts: _radioGroupShortcuts, state: this);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/radio_group.dart:99]: No need for `late` if it's assigned here, right?

File: packages/flutter/lib/src/widgets/radio_group.dart [hunk 3]
```diff
@@ -215,6 +224,26 @@ class _RadioGroupState<T> extends State<RadioGroup<T>> implements RadioGroupRegi
...
 }
 
+class _RadioGroupShortcutManager<T> extends ShortcutManager {
+  _RadioGroupShortcutManager({required super.shortcuts, required this.state});
+
+  final _RadioGroupState<T> state;
+
+  @override
+  KeyEventResult handleKeypress(BuildContext context, KeyEvent event) {
+    final bool hasFocusedRadio = state._radios.any(
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/radio_group.dart]: Nit: I would change the name to `radioHasFocus`. The current name made me think it would be an instance of a radio or something.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/widgets/radio_group.dart (hunk 2 above)
Comment (ksokolovskyi) [reply packages/flutter/lib/src/widgets/radio_group.dart:99]: Unfortunately, we are forced to use `late` as, although the assignment comes next, we use `late _radioGroupShortcuts` and `this`.

File: packages/flutter/lib/src/widgets/radio_group.dart (hunk 3 above)
Comment (ksokolovskyi) [reply packages/flutter/lib/src/widgets/radio_group.dart]: Thanks a lot for your review!
I updated the name in the latest commit as you suggested.
