### PR TITLE
Driver vm service

### LINKED ISSUE #31813: No such method: streamNotify
After adding logic to catch previously swallowed exceptions in json_rpc_2, we're now seeing this exception thrown in devicelab and google3 tests.  

```dart
JSON-RPC error -32601 (method not found): Unknown method "streamNotify".
#0      Server._tryFallbacks._tryNext (package:json_rpc_2/src/server.dart:272:9)
<asynchronous suspension>
#1      Server._tryFallbacks (package:json_rpc_2/src/server.dart:284:20)
```

I suspect this is a timing issue where something is trying to call that method before we've registered it - it gets registered in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L113

### PR DESCRIPTION
**Pull request by dnfield**
Migrates package:flutter_driver to use package:vm_service.

This will be needed to eventually completely migrate flutter_driver to null safety. To that end, I've also rewritten the tests to not use mockito.

Part of https://github.com/flutter/flutter/issues/37499

Fixes #31813 since package:vm_service is now in charge of that behavior.

### CODE REVIEW

File: packages/flutter_driver/test/flutter_driver_test.dart [hunk 1]
```diff
@@ -204,482 +154,281 @@ void main() {
...
+        expect(fakeClient.commandLog, <String>[
+          'ext.flutter.driver {command: tap, timeout: $_kSerializedTestTimeout, finderType: BySemanticsLabel, label: ^foo, isRegExp: true}',
+        ]);
       });
     });
 
     group('tap', () {
       test('requires a target reference', () async {
-        expect(driver.tap(null), throwsDriverError);
+        expect(driver.tap(null), throwsAssertionError);
```
Comment (dnfield) [inline packages/flutter_driver/test/flutter_driver_test.dart:182]: Several of these changed and I'm not entirely sure why.

I'm not super concerned about it though, since before long we'll be migrating this to NNBD and this test will just go away anyway.

Comment (dnfield) [reply packages/flutter_driver/test/flutter_driver_test.dart:182]: (The test and the entire class of error will change)

File: dev/integration_tests/flutter_gallery/pubspec.yaml [hunk 2]
```diff
@@ -37,7 +37,7 @@ dependencies:
   typed_data: 1.3.0-nullsafety.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
   url_launcher_linux: 0.0.1+1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
   url_launcher_macos: 0.0.1+8 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
-  url_launcher_platform_interface: 1.0.8 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
+  url_launcher_platform_interface: 1.0.9 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
```
Comment (jonahwilliams) [inline dev/integration_tests/flutter_gallery/pubspec.yaml:40]: Doesn't this version need to be pinned?

**Review by jonahwilliams — COMMENTED** [review]
This is great

We don't really test drive on presubmit though, the unit tests are trivial. To make sure this can land without being reverted I would validate several devicelab tests locally.

Separately, you may need to investigate google3

File: dev/integration_tests/flutter_gallery/pubspec.yaml (hunk 2 above)
Comment (dnfield) [reply dev/integration_tests/flutter_gallery/pubspec.yaml:40]: I do not know, @mdebbar or @ditman may know what's going on there. I'm assuming by the time the tree is open again that will be resolved.

**Comment by dnfield** [comment]
I did run some local driver tests that worked, and a handful of devicelab tests as well.

I need to get this through a FRoB run as well, but posting this is a step towards that.

File: dev/integration_tests/flutter_gallery/pubspec.yaml (hunk 2 above)
Comment (mdebbar) [reply dev/integration_tests/flutter_gallery/pubspec.yaml:40]: [This PR](https://github.com/flutter/plugins/pull/3155) will fix this issue. I'm working now on getting it green so I can land it.

Comment (ditman) [reply dev/integration_tests/flutter_gallery/pubspec.yaml:40]: Closing the loop here: Mouad [published](https://pub.dev/packages/url_launcher_web/changelog#015) the fix for the build issue. Apologies for the breakage!

**Comment by jcollins-g** [comment]
dartdoc crash tracking at https://github.com/dart-lang/dartdoc/issues/2402

File: packages/flutter_driver/test/flutter_driver_test.dart [hunk 3]
```diff
@@ -1213,31 +804,191 @@ String _checkAndEncode(dynamic script) {
...
+      'timeOriginMicros': 0,
+      'timeExtentMicros': 999999,
+    }),
+  };
+
+  @override
+  Future<vms.Timeline> getVMTimeline({int timeOriginMicros, int timeExtentMicros}) async {
+    connectionLog.add('getVMTimeline $timeOriginMicros $timeExtentMicros');
+    final vms.Timeline timeline = timelineResponses[timeOriginMicros ?? 1];
+    assert(timeline != null, 'Missing entry in timelineResponses[$timeOriginMicros]');
```
Comment (bkonyi) [inline packages/flutter_driver/test/flutter_driver_test.dart:960]: Do we run with assertions enabled in tests? If we're not sure, maybe it's safer to just throw here.

**Review by bkonyi — APPROVED** [review]
`package:vm_service_client` is dead! Long live `package:vm_service`!

File: packages/flutter_driver/test/flutter_driver_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter_driver/test/flutter_driver_test.dart:960]: Assertions are enabled for tests, yes.

**Comment by dnfield** [comment]
I'm still working through testing this internally, requires a few hoops to get vm_service visibility for flutter_driver in the monorepo.

**Comment by dnfield** [comment]
Internal runs are failing because of unrelated changes related to NNBD. I'll wait until that's cleaned up internally and try to re-run the tests.

**Comment by jcollins-g** [comment]
> dartdoc crash tracking at [dart-lang/dartdoc#2402](https://github.com/dart-lang/dartdoc/issues/2402)

https://github.com/flutter/flutter/pull/68791 will fix this for Flutter.

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 4]
```diff
@@ -86,76 +83,56 @@ class VMServiceFlutterDriver extends FlutterDriver {
...
+        final vms.Response result = await client.setFlag('pause_isolates_on_start', 'false');
+        if (result == null || result.type != 'Success') {
           _log('setFlag failure: $result');
         }
       } catch (e) {
         _log('Failed to set pause_isolates_on_start=false, proceeding. Error: $e');
       }
 
-      return isolate.resume().catchError((dynamic e) {
+      return await client.resume(isolate.id).catchError((dynamic e) {
```
Comment (jonahwilliams) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:128]: `return await` is pointless

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 5]
```diff
@@ -86,76 +83,56 @@ class VMServiceFlutterDriver extends FlutterDriver {
...
         const int vmMustBePausedCode = 101;
-        if (e is rpc.RpcException && e.code == vmMustBePausedCode) {
+        if (e is vms.RPCError && e.code == vmMustBePausedCode) {
           // No biggie; something else must have resumed the isolate
           _log(
               'Attempted to resume an already resumed isolate. This may happen '
-                  'when we lose a race with another tool (usually a debugger) that '
-                  'is connected to the same isolate.'
+              'when we lose a race with another tool (usually a debugger) that '
```
Comment (jonahwilliams) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:134]: nit while you are here: no "we"

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 6]
```diff
@@ -169,10 +146,12 @@ class VMServiceFlutterDriver extends FlutterDriver {
     /// Looks at the list of loaded extensions for the current [isolateRef], as
     /// well as the stream of added extensions.
     Future<void> waitForServiceExtension() async {
-      final Future<void> extensionAlreadyAdded = isolateRef
-        .loadRunnable()
-        .then((VMIsolate isolate) async {
-          if (isolate.extensionRpcs.contains(_flutterExtensionMethodName)) {
+      await client.streamListen(vms.EventStreams.kIsolate);
```
Comment (jonahwilliams) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:149]: this will throw an exception if the stream has already been subscribed to

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 7]
```diff
@@ -551,10 +495,7 @@ class VMServiceFlutterDriver extends FlutterDriver {
   @override
   Future<void> forceGC() async {
     try {
-      await _peer
-          .sendRequest(_collectAllGarbageMethodName, <String, String>{
-        'isolateId': 'isolates/${_appIsolate.numberAsString}',
-      });
+      await _serviceClient.callMethod(_collectAllGarbageMethodName, isolateId: _appIsolate.id);
```
Comment (jonahwilliams) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:498]: I believe this method is deprecated and no longer does anything

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/vmservice_driver.dart:134]: Done

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart (hunk 4 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/vmservice_driver.dart:128]: Done

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/vmservice_driver.dart:149]: This would be unexpected, since we unsubscribe at the end of this method.

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/vmservice_driver.dart:498]: We're "not supposed" to use it, but it does work. It's not guaranteed to do anything but it normally works well enough.

We can't remove this - it's used in many of our benchmarks to reduce flakiness.

**Comment by dnfield** [comment]
This will be blocked until a resolution to https://github.com/dart-lang/sdk/issues/43898 is rolled into google.

**Comment by jonahwilliams** [comment]
It should be possible to construct your own websocket for driver, see vmservice.dart in the flutter tool

**Comment by dnfield** [comment]
Ahhh ok, cool. I can try that.

**Comment by dnfield** [comment]
This patch is now passing internally, with some additional updates at cl/338576267 to cover new dependency changes and some internal usages of API that isn't available anymore (specifically, not using the vm_service_client API that we used to expose through this lib).

**Comment by dnfield** [comment]
@renyou  -why doesn't FROB let me apply a G3Fix to this PR? It's approved by bkonyi.

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 8]
```diff
@@ -92,53 +91,55 @@ abstract class FlutterDriver {
...
   /// running on `dartVmServiceUrl`.
   ///
-  /// `fuchsiaModuleTarget` specifies the pattern for determining which mod to
-  /// control. When running on a Fuchsia device, either this or the environment
-  /// variable `FUCHSIA_MODULE_TARGET` must be set (the environment variable is
-  /// treated as a substring pattern). This field will be ignored if
+  /// The `fuchsiaModuleTarget` parameter specifies the pattern for determining
+  /// which mod to control. When running on a Fuchsia device, either this or the
+  /// environment variable `FUCHSIA_MODULE_TARGET` must be set (the environment
+  /// variable is treated as a substring pattern). This field will be ignored if
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart:131]: Should we also say that this parameter is ignored on non-Fuchsia devices?

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 9]
```diff
@@ -92,53 +91,55 @@ abstract class FlutterDriver {
...
-  /// [WebSocket] connection. This is only used for [VMServiceFlutterDriver]
-  /// connections.
+  /// The `headers` parameter optionally specifies HTTP headers to be included
+  /// in the [WebSocket] connection. This is only used for
+  /// [VMServiceFlutterDriver] connections.
   ///
-  /// `browser` specifies which FlutterDriver implementation to use. If not
-  /// speicifed or set to false, [VMServiceFlutterDriver] implementation
-  /// will be used. Otherwise, [WebFlutterDriver] implementation will be used.
+  /// The `browser` parameter specifies which FlutterDriver implementation to
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart:139]: I'm failing to find the `browser` parameter this part is talking about :thinking:

File: packages/flutter_driver/lib/src/driver/vmservice_driver.dart [hunk 10]
```diff
@@ -111,68 +107,50 @@ class VMServiceFlutterDriver extends FlutterDriver {
...
-    //
-    // See: https://github.com/dart-lang/vm_service_client/issues/4
-    if (isolate.pauseEvent is! VMPauseStartEvent &&
-        isolate.pauseEvent is! VMPauseExitEvent &&
-        isolate.pauseEvent is! VMPauseBreakpointEvent &&
-        isolate.pauseEvent is! VMPauseExceptionEvent &&
-        isolate.pauseEvent is! VMPauseInterruptedEvent &&
-        isolate.pauseEvent is! VMResumeEvent) {
-      isolate = await isolateRef.loadRunnable();
+    if (isolate.pauseEvent.kind == vms.EventKind.kNone) {
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/vmservice_driver.dart:120]: \o/

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 9 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/driver.dart:139]: Looks like someone removed that and forgot to remove the docs. Removing this block.

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 8 above)
Comment (dnfield) [reply packages/flutter_driver/lib/src/driver/driver.dart:131]: Done

File: dev/integration_tests/ui/test_driver/license_check_test.dart [hunk 11]
```diff
@@ -57,40 +51,3 @@ void main() {
     });
   });
 }
-
-/// Workaround for isolates being paused by driver tests.
-/// https://github.com/flutter/flutter/issues/24703
-class IsolatesWorkaround {
```
[the remark this answers is not in the document]
Comment (dnfield) [reply dev/integration_tests/ui/test_driver/license_check_test.dart:63]: This was actually fixed by a different patch, but became apparent in this one because it's trying to use API the driver no longer exposes :)

**Comment by dnfield** [comment]
Note to self or anyone else looking at this due to a devicelab failure:

I did not run _all_ devicelab tests. We should feel free to aggressively revert this if it's causing devicelab failures. That said, if we need to revert we should ideally do so before it rolls into google3, as that will complicate reverts.

**Review by jonahwilliams — APPROVED** [review]
LGTM ship it

**Comment by dnfield** [comment]
All tests that CI should be able to catch are passing - will watch devicelab.
