### PR TITLE
[ios][tools]do not log "bonjour not found" at all (unless verbose)

### LINKED ISSUE #172627: [Xcode 26 beta 4] Xcode reports `Could not extract value, error: No value at that key path or invalid key path` for some keys when running on iOS
### Steps to reproduce

1. Use Xcode 26 beta 4
2. Create a new flutter app on either stable, beta or master
3. Run the app on iOS

### Expected results

Xcode doesn't report missing keys in the logs

### Actual results

Xcode reports missing keys in the logs. The app still launches, however, sometimes I cannot debug the app. After the application launches, the app just closes with this message. 

```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:64581/WJVUsMFhG58=/
HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:64581/WJVUsMFhG58=/ws
```

I tested on iOS 18.6 and iOS 26 and on both devices, I see the message in the logs section below. (Error added below for brevity). 

The error goes away when I add the respective entitlements. I tested with this by adding the  `NSLocalNetworkUsageDescription` key and the error went away. I didn't test `NSBonjourServices` (this I believe is an array, and I wasn't sure which options would apply in our case). However, I believe when we add the right options for the `NSBonjourServices`, the error should go away . This does not happen with Xcode 26 beta 3. 

When running on the stable channel, the error is not surfaced in `flutter run`. It is surfaced when you run `flutter run -v`. 

```
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSBonjourServices
error: /Users/deanli/projects/QA-Manual/creation/beta4/build/ios/Debug-iphoneos/Runner.app/Info.plist: Could
not extract value, error: No value at that key path or invalid key path: NSLocalNetworkUsageDescription
```

### Code sample

The counter app should suffice for this (added below)

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

N/A

### Logs

[ios26.log](https://github.com/user-attachments/files/21384437/ios26.log)

[ios18_6.log](https://github.com/user-attachments/files/21384440/ios18_6.log)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.7, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [824ms]
    • Flutter version 3.32.7 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7b523b356 (7 days ago), 2025-07-15 17:03:46 -0700
    • Engine revision 39d6d6e699
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.5s]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [1,523ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [13ms]
    • Android Studio at /Users/deanli/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.102.1) [11ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (4 available) [12.6s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [2.2s]
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.33.0-1.0.pre-1078, on macOS 26.0 25A5316i darwin-arm64, locale en-US) [3.3s]
    • Flutter version 3.33.0-1.0.pre-1078 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision afba7d75b3 (7 hours ago), 2025-07-23 14:04:50 +1200
    • Engine revision afba7d75b3
    • Dart version 3.10.0 (build 3.10.0-15.0.dev)
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [1,462ms]
    • Android SDK at /Users/deanli/Library/Android/sdk
    • Emulator version 36.1.8.0 (build_id 13784423) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Users/deanli/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.0) [980ms]
    • Xcode at /Applications/Xcode-26.0.0-Beta.4.app/Contents/Developer
    • Build 17A5285i
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [5ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6.2s]
    • iPhone 16 Pro Max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 26.0 23A5297i
    • Nexus (wireless) (mobile)             • 00008020-001875E83A38002E • ios            • iOS 18.5 22F76
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 26.0 25A5316i darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 138.0.7204.159
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [831ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by hellohuanlin**
The previous PR https://github.com/flutter/flutter/pull/172913 avoids compilation error by not having the "error: " prefix. However, it's still very confusing to have "key not found" printed out in the terminal (either stderr or stdout), despite that it doesn't cause compilation error anymore. 

This PR introduces a new flag "skipErrorLog" which skips logging the `stderr` if set to true. We set it for plist extraction, because "not having bonjour key" should be one of the expected "normal" states

<s> We don't want to pipe it to `stdout` either, because it would be confusing too. I figured people would still file issue if they see it in terminal, even if it's a completely normal state. But not a strong opinion, so let me know if you disagree. </s>

However, under verbose mode, we would pipe it to `stdout`. This will be consistent with our previous behavior before macOS 26.

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

Fixes https://github.com/flutter/flutter/issues/172627

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 1]
```diff
@@ -426,14 +429,12 @@ class Context {
...
-      '-extract',
-      'NSBonjourServices',
-      'xml1',
-      '-o',
-      '-',
-      builtProductsPlist,
-    ], allowFail: true);
+    ProcessResult result = runSync(
+      'plutil',
+      <String>['-extract', 'NSBonjourServices', 'xml1', '-o', '-', builtProductsPlist],
```
Comment (hellohuanlin) [inline packages/flutter_tools/bin/xcode_backend.dart:448]: this is by `dart format` after i added the new parameter

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 2]
```diff
@@ -458,14 +459,12 @@ class Context {
...
-      '-extract',
-      'NSLocalNetworkUsageDescription',
-      'xml1',
-      '-o',
-      '-',
-      builtProductsPlist,
-    ], allowFail: true);
+    result = runSync(
+      'plutil',
+      <String>['-extract', 'NSLocalNetworkUsageDescription', 'xml1', '-o', '-', builtProductsPlist],
```
Comment (hellohuanlin) [inline packages/flutter_tools/bin/xcode_backend.dart:479]: this is by `dart format` after i added the new parameter

File: packages/flutter_tools/test/general.shard/xcode_backend_test.dart [hunk 3]
```diff
@@ -439,74 +442,76 @@ void main() {
...
       )..run();
-      expect(context.stderr, isNot(contains('error: ')));
+      expect(context.stderr, isNot(startsWith('error: ')));
+      expect(context.stderr, isNot(contains(plutilErrorMessage)));
+      expect(context.stdout, isNot(contains(plutilErrorMessage)));
     });
 
-    test(
-      'Missing NSLocalNetworkUsageDescription in Info.plist should not fail Xcode compilation',
-      () {
```
Comment (hellohuanlin) [inline packages/flutter_tools/test/general.shard/xcode_backend_test.dart:447]: hmmm, i suspect something is going on to my formatter (likely char limit per line setting is different on my IDE). let me double check. in the mean time, converting to draft

**Comment by hellohuanlin** [comment]
i should probably CP this too

File: packages/flutter_tools/test/general.shard/xcode_backend_test.dart (hunk 3 above)
Comment (hellohuanlin) [reply packages/flutter_tools/test/general.shard/xcode_backend_test.dart:447]: i suspect the old code was formatted with the old format rule of 80 characters line length, and my code triggered reformat with new rule of 100 characters line length.

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 4]
```diff
@@ -120,11 +121,13 @@ class Context {
       print((result.stdout as String).trim());
     }
     final String resultStderr = result.stderr.toString().trim();
-    if (resultStderr.isNotEmpty) {
+    // If skipErrorLog flag is set, do not log stderr of the process.
+    // An example is on macOS 26, plutil reports NSBonjourServices key not found
+    // via stderr (rather than stdout on older macOS), and logging the message
+    // would be confusing (for either stdout or stderr), since not having the
+    // key is one of the expected states.
+    if (!skipErrorLog && resultStderr.isNotEmpty) {
```
Comment (vashworth) [inline packages/flutter_tools/bin/xcode_backend.dart]: I think we still want these logs to show if in verbose mode. The way this is now, they won't show in verbose.

I think what you'll want to do is that is `skipErrorLog` is true, don't write it to `streamOutput` or `echoError`. Unless we're in verbose mode, then do write it to `echoError`.

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart]: @vashworth my understanding: 

First of all, we don't want to show the message in `non-verbose` mode for sure, since not having the key is an expected state (also the most common state). We don't want to scream this out in almost every `flutter run`. I think we already agree on that. 

Secondly, no matter `verbose` or not, we shouldn't `echoError`, since semantically speaking, to our bonjour logic, not having the key is not an error, but one of the expected states - definitely not an error. 

Now the question is, under `verbose` mode, do we want to pipe the `stderr` message to `stdout`? I am leaning towards not to do so, because it's still very confusing to see `"Could not extract value, error: No value at that key path or invalid key path: NSBonjourServices"`, which clearly reads like stderr, not stdout (I suspect apple probably also thinks it's weird to be in stdout, so they moved it to stderr on macOS 26). Though this is not a strong opinion (51%-ish), so if you insist, I am open to pipe it to stdout under verbose mode. The new code will look something like: 

```
    // ...
    if (resultStderr.isNotEmpty) {
      // ...

      if (skipErrorLog) {
        // Even if we skip error, we still want to pipe it to stdout under verbose mode.
        if (verbose) {
          echo(errorOutput.toString());
        }
      } else {
        echoError(errorOutput.toString());
      }

```

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart]: ^ actually, thinking about the 3rd point more, piping it to stdout under verbose mode is probably fine, since we were printing that string already before macOS 26 (i.e. piping to stdout would make it consistent with our previous behavior before macOS 26)

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 5]
```diff
@@ -104,12 +104,20 @@ class Context {
...
   ///
-  /// Will throw [Exception] if the exit code is not 0.
+  /// @param bin The command to run.
+  /// @param args Args to pass into the command.
+  /// @param verbose Verbose mode.
+  /// @param allowFail If set, will not throw exceptions or result in xcode failure.
+  /// @param skipErrorLog If set, will skip stderr in non-verbose mode, and pipe
+  ///     stderr to stdout in verbose mode.
+  /// @param workingDirectory The current working directory to run the command.
+  /// @throws [Exception] if the exit code is not 0.
```
Comment (vashworth) [inline packages/flutter_tools/bin/xcode_backend.dart]: `@param` and `@throws` isn't really supported in Dart.

If you want to give definitions to arguments, you can use brackets to refer to arguments: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#leave-breadcrumbs-in-the-comments

For example
```dart
  /// Run given command ([bin]) in a synchronous subprocess.
  ///
  /// If [allowFail] is true, an exception will not be thrown even if the process returns a 
  /// non-zero exit code. Also, `error:` will not be prefixed to the output to prevent Xcode 
  /// complication failures.
  /// 
  /// If [skipErrorLog] is true, `stderr` from the process will not be output unless in [verbose] 
  /// mode. If in [verbose], pipes `stderr` to `stdout`.
  /// 
  /// Will throw [Exception] if the exit code is not 0.
```

**Review by vashworth — APPROVED** [review]
@hellohuanlin LGTM after you update the comment

File: packages/flutter_tools/bin/xcode_backend.dart (hunk 5 above)
Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart]: oof, gemini isn't a good excuse - i should've double checked.

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 6]
```diff
@@ -122,15 +130,22 @@ class Context {
...
         errorOutput.write('error: ');
       }
       errorOutput.write(resultStderr);
-      echoError(errorOutput.toString());
+      if (skipErrorLog) {
+        // Pipe stderr to stdout under verbose mode.
+        // An example is on macOS 26, plutil reports NSBonjourServices key not found
+        // via stderr (rather than stdout on older macOS), and logging the message
+        // in stderr would be confusing, since not having the key is one of the expected states.
+        if (verbose) {
```
Comment (jmagman) [inline packages/flutter_tools/bin/xcode_backend.dart:143]: I'd prefer to always log errorOutput in verbose mode, even in the Bonjour case. There may be other errors that command generates that we will want to see to triage.

Comment (hellohuanlin) [reply packages/flutter_tools/bin/xcode_backend.dart:143]: @jmagman yes in verbose mode, all will be logged. The logic is: 

```
skipErrorLog { // true for bonjour
  if verbose {
    log to stdout ("key not found" shouldn't be an "error" or "warning" - rather one of the expected states)
  } else {
    do not log
  }
} else { // don't change for other features
  log to stderr
}
```

Comment (jmagman) [reply packages/flutter_tools/bin/xcode_backend.dart:143]: Ah gotcha, I can't read.

**Comment by hellohuanlin** [comment]
Sorry I have to revert this one.

**Comment by hellohuanlin** [comment]
Reason for revert: didn't work
