### PR TITLE
In `flutter doctor -v`, when JRE is too out-of-date to run `sdkmanager`, print a helpful error message

### LINKED ISSUE #138132: flutter doctor --android-licenses fails on Command-line Tools 11.0
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install v11 cmdline-tools
2. Try to run flutter doctor --android-licenses
3. Catch an error

### Actual results

This command works only with cmdline-tools v8, with rename folder to latest

https://stackoverflow.com/questions/76882205/error-linkageerror-occurred-while-loading-main-class-com-android-sdklib-tool-sd

### Logs

<details>
<summary>Logs</summary>

```console
PS C:\Users\username> flutter doctor --android-licenses -v
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
        java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Android sdkmanager tool was found, but failed to run
(C:\Users\salty\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:406:9)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:26)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale ru-RU)
    • Flutter version 3.13.9 on channel stable at C:\Users\salty\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\salty\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\salty\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.25)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33423.256
    • Windows 10 SDK version 10.0.19041.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.84.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.44

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

### PR DESCRIPTION
**Pull request by andrewkolos**
Closes https://github.com/flutter/flutter/issues/138132. See this issue for more information.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_workflow.dart [hunk 1]
```diff
@@ -389,12 +389,15 @@ class AndroidLicenseValidator extends DoctorValidator {
         ),
       );
 
+      final Stream<List<int>> stderrBroadcast = process.stderr.asBroadcastStream();
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_workflow.dart:392]: using a broadcast stream worries me (because debugging stream issues is not easy). what about instead if you make a custom listener for `process.stderr` that both forwards data to `_stdio.stderr` and adds it to `stderrLines`?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:392]: I cannot submit a code suggestion for a block this big, but this passes locally for me:

```dart
      try {
        final StreamSubscription<List<int>> stderrSub = process.stderr.listen((List<int> bytes) {
          _stdio.stderr.add(bytes);
          stderrLines.add(utf8.decoder.convert(bytes));
        });
        await Future.wait<void>(<Future<void>>[
          _stdio.addStdoutStream(process.stdout),
          stderrSub.asFuture<void>(),
        ]);
        await stderrSub.cancel();
      } on Exception catch (err, stack) {

```

File: packages/flutter_tools/lib/src/android/android_workflow.dart [hunk 2]
```diff
@@ -426,4 +425,32 @@ class AndroidLicenseValidator extends DoctorValidator {
...
   }
+
+  String messageForSdkManagerError(
+    Java java,
+    AndroidSdk androidSdk,
+    List<String> androidSdkStderr,
+    int exitCode,
+    Platform platform,
+  ) {
+    final String sdkManagerPath = androidSdk.sdkManagerPath ?? '';
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_workflow.dart:436]: shouldn't the error message be different if `androidSdk.sdkManagerPath == null`?

File: packages/flutter_tools/lib/src/android/android_workflow.dart [hunk 3]
```diff
@@ -426,4 +425,32 @@ class AndroidLicenseValidator extends DoctorValidator {
...
+
+    final bool failedDueToJdkIncompatibility = androidSdkStderr.join().contains(
+      RegExp(r'.*java\.lang\.UnsupportedClassVersionError.*SdkManagerCli '
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_workflow.dart:440]: nit, the `.*` at the start and end are redundant.

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:437]: I think this is a good find, but I have a slightly different take on it. This function takes an `exitCode`, which implies that we were able to run `sdkmanager`. In this case, `androidSdk.sdkManagePath` should never be null, so I think we should instead add a non-null assertion here (or have the caller make the assertion on the path and just pass that in instead of the entire `AndroidSdk` object).

File: packages/flutter_tools/lib/src/android/android_workflow.dart [hunk 4]
```diff
@@ -426,4 +425,32 @@ class AndroidLicenseValidator extends DoctorValidator {
...
+
+    if (failedDueToJdkIncompatibility) {
+      return 'Android sdkmanager tool was found, but failed to run ($sdkManagerPath): "exited code $exitCode".\n'
+        'It appears the version of the Java binary used (${java.binaryPath}) is '
+        'too out-of-date and is incompatible with the Android sdkmanager tool.\n'
+        'If the Java binary came bundled with Android Studio, consider updating '
+        'your installation of Android studio. Alternatively, you can uninstall '
+        'the Android SDK command-line tools and install an earlier version. ';
+    }
+    throwToolExit(_userMessages.androidCannotRunSdkManager(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_workflow.dart:451]: i think this function is overloaded with several tasks, which are not obvious from its name. I think `messageForSdkManagerError()` should just be responsible for interpolating values into the message string. I would recommend lifting the other logic into the call site around line 409.

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: Addressed in [57add0c](https://github.com/flutter/flutter/pull/138762/commits/57add0c0351c5291653afcffee5630e5055224ff)

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: I commited my own take on this at the same time you sent this. Feel free to take a look. I know very little about Dart `Stream`s, so I don't know what's idiomatic here.

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 4 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:451]: Ah, I'm sorry. Originally, I went back and forth between having this function throw a tool exit or  just generating the message and letting the caller throw. Looks like I left this in an in-between state.

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:437]: >  This function takes an exitCode, which implies that we were able to run sdkmanager. In this case, androidSdk.sdkManagePath should never be null

I agree. So I think we should either do a `!`, in which case we will get an obvious _TypeError in crash reporting if we're wrong, or handle it with a different error message. But I think the former is probably desirable, as we would want to know if that is the case.

And when you say "non-null assertion", if you mean `!` I agree. If you mean `assert(androidSdk.sdkManager != null);`, I think asserts are kind of an anti pattern in the tool, since it makes us think we have an assurance but only if we cover that code path with unit tests.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:437]: > And when you say "non-null assertion", if you mean `!` I agree.

Yeah, there's a bit of unfortunate ambiguity in the naming here. I did mean `!` (null-assertion operator). It's good to learn more about your opinion on `assert`s, though.

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: your's is cleaner, LGTM

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:437]: sounds good!

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart:451]: > Ah, I'm sorry the headache reading this code probably caused.

it's all good. i've submitted worse that i've marked "ready for review"

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: I've changed this function to not throw a `ToolExit` (it just returns the error message). Commit: [make messageForSdkManagerError private](https://github.com/flutter/flutter/pull/138762/commits/face2518c1d652d0aaaf2d9b0f7dacd14d29efea)

> `messageForSdkManagerError()` should just be responsible for interpolating values into the message string. I would recommend lifting the other logic into the call site around line 409.

If by "other logic" you mean the conditional logic to choose what string to build, I'm not sure I agree. `runLicense` manager already has a decent length and amount of conditional logic going on, and I don't want to add another layer of depth (which also has a bunch of noisy string interpolation) to it. I'm happy to reconsider if you can clarify or make a code suggestion

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: this lgtm

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by andrewkolos** [comment]
> LGTM

Thanks! I appreciate the good level of scrutiny you put into this review

**Comment by christopherfujino** [comment]
> > LGTM
> 
> Thanks! I appreciate the good level of scrutiny you put into this review

that's a charitable way to put it :)
