### PR TITLE
Fix text field selection toolbar under Opacity

### LINKED ISSUE #30587: TextField inside Opacity has wrong selection Leader/Follower transformation
Here's a screenshot:
flutter_22

It can be reproduced by:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: Text('Opacity TextField')),
        body: Center(
          child: Container(
            width: 100,
            height: 100,
            child: Opacity(
              opacity: 0.5,
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```

https://github.com/flutter/flutter/issues/30586 inspired me to discover this bug but that issue has nothing to do with this bug (i.e., this bug exists before https://github.com/flutter/engine/pull/8362)

### PR DESCRIPTION
**Pull request by liyuqian**
## Description

As we've introduced offset to the Opacity layer, we have to override
`applyTransform` to make Leader/FollowerLayer work correctly.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/30587

Together with https://github.com/flutter/engine/pull/8585,
this test will also exercise test against
https://github.com/flutter/flutter/issues/30586.

## Tests

I added the following tests:
* text field selection toolbar renders correctly inside opacity

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by liyuqian** [comment]
WIP, the test won't pass until
1. We fixed #30587
2. We uploaded the golden file.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 1]
```diff
@@ -1279,6 +1279,13 @@ class OpacityLayer extends ContainerLayer {
     }
   }
 
+  @override
+  void applyTransform(Layer child, Matrix4 transform) {
+    assert(child != null);
+    assert(transform != null);
+    transform.multiply(Matrix4.translationValues(offset.dx, offset.dy, 0.0));
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/layer.dart]: there's a Matrix4.translate method, which would make this more efficient

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -380,6 +381,58 @@ void main() {
...
+    // (This is true even if we provide selection parameter to the TextEditingValue above.)
+    final EditableTextState state = tester.state<EditableTextState>(find.byType(EditableText));
+    state.renderEditable.selectWordsInRange(from: const Offset(0, 0), cause: SelectionChangedCause.tap);
+    await tester.pump();
+
+    expect(state.showToolbar(), true);
+    await tester.pump();
+
+    // This is needed for the AnimatedOpacity to turn from 0 to 1 so the toolbar is visible.
+    await tester.pumpAndSettle();
```
Comment (Hixie) [inline packages/flutter/test/material/text_field_test.dart]: it's more efficient to just pump once with the required amount of time to skip the animation

Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: I've removed all the previous pumps. However, I couldn't change this `pumpAndSettle` to even `pump(Duration(seconds: 100))` to pass the test. It'll pass with `await tester.pump(); await tester.pump(Duration(seconds: 1));` though. Is this a bug or an expected behavior?

Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: I've also added the first `pump` back in the newest patch. Otherwise, the "COPY/CUT/PASTE" will appear in a different order which causes a golden image mismatch (see attached images). Is this also an expected behavior?
text_field_opacity_test 0 0
text_field_opacity_test 0 0 original

**Comment by liyuqian** [comment]
Ping...

File: packages/flutter/lib/src/rendering/layer.dart [hunk 3]
```diff
@@ -1279,6 +1279,13 @@ class OpacityLayer extends ContainerLayer {
     }
   }
 
+  @override
+  void applyTransform(Layer child, Matrix4 transform) {
+    assert(child != null);
+    assert(transform != null);
+    transform.translate(offset.dx, offset.dy);
+  }
+
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/layer.dart]: fyi @goderbauer

File: packages/flutter/test/material/text_field_test.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/test/material/text_field_test.dart]: No idea why the order would change...

Comment (Hixie) [reply packages/flutter/test/material/text_field_test.dart]: looks like you still have pumpAndSettle?

Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: Yes, I'll either need this `pumpAndSettle`, or `await tester.pump(); await tester.pump(Duration(seconds: 1));` as mentioned in https://github.com/flutter/flutter/pull/31097/files#r276410094. Do you want me to change to `await tester.pump(); await tester.pump(Duration(seconds: 1));`?

Comment (Hixie) [reply packages/flutter/test/material/text_field_test.dart]: it's significantly preferred to use pump than pumpAndSettle, because pumpAndSettle will mask regressions.

Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: Changed to `pump`.

Comment (dnfield) [reply packages/flutter/test/material/text_field_test.dart]: One suggestion is to capture the return value of `pumpAndSettle` and `expect` the result of it (or expect that it's less than some sane value).

Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: I guess the regression that @Hixie mentioned is about the regression in seconds (e.g., the animation should finish in 1 second but a regression made it 10 seconds). I'm not sure if the return value of `pumpAndSettle` would catch that. What's your thought, @Hixie ?

Comment (Hixie) [reply packages/flutter/test/material/text_field_test.dart]: The return value would catch it but it's more likely that someone fixing it will just change the number and it's more likely that a reviewer will fail to notice that.

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -380,6 +381,57 @@ void main() {
...
+
+    // Sanity check that the toolbar widget exists.
+    expect(find.text('PASTE'), findsOneWidget);
+
+    await expectLater(
+      // The toolbar exists in the Overlay above the MaterialApp.
+      find.byType(Overlay),
+      matchesGoldenFile('text_field_opacity_test.0.0.png'),
+    );
+  }, skip: !Platform.isLinux);
```
Comment (goderbauer) [inline packages/flutter/test/material/text_field_test.dart]: Do you really want to skip the entire test on all non-linux platforms? Or just the golden check? In the later, I'd recommend putting the skip on "expectLater". (It looks like everything else should also work on other platforms?)

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (liyuqian) [reply packages/flutter/test/material/text_field_test.dart]: Good catch! Fixed.

**Comment by jonahwilliams** [comment]
This is breaking several devicelab tasks, and failing a golden check. Do these need to be updated, or were they unexpected?  cc @liyuqian
