### PR TITLE
Scale selection handles for rich text on iOS

### LINKED ISSUE #79303: [iOS] Selection handles do not scale with the font size
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const title = 'code sample';
    return MaterialApp(
      title: title,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Home(),
      ),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SingleChildScrollView(
        child: Theme(
          data: ThemeData(
            textSelectionTheme: TextSelectionThemeData(selectionColor: Colors.red),
          ),
          child: SelectableText.rich(
            TextSpan(
              children: [
                TextSpan(text: ' ',
                  style: TextStyle(
                    fontSize: 110.0,
                  ),
                ),
                TextSpan(text: ' ',
                  style: TextStyle(
                    backgroundColor: Colors.green,
                    fontSize: 110.0,
                  ),
                ),
                TextSpan(text: ' ',
                  style: TextStyle(
                    backgroundColor: Colors.red,
                    fontSize: 110.0,
                  ),
                ),
                TextSpan(text: 'Word',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 110.0,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

1. in iOS, long press to select the word

image

expect: the selection handles should scale with the font size.
actual: they do not.

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
## Description
Check out the [design doc](https://docs.google.com/document/d/1XuvdYUzZQAxCLYT2H1DNtOi1s6fGmFE-cgmweaijfe4/edit?usp=sharing) for more details.

On iOS the selection handles should scale with the font size for rich text. The value used in calculating the handle anchor and handle size is `widget.renderObject.preferredLineHeight`. The value `preferredLineHeight` is defined as not always being the height of every line of the given text. On iOS we want the `preferredLineHeight` to pertain to the current selection so the handles can scale. To achieve this I calculate two new values `startHandleRect` and `endHandleRect` using the `renderObjects` `getRectForComposingRange`. These new values are then used to calculate the handle anchor and handle size depending on the `TextSelectionHandleType`.

Before|After
---|---
Screen Shot 2021-07-07 at 1 07 02 PM|Screen Shot 2021-07-07 at 1 06 38 PM

## Related Issues
Fixes #79303

## Tests
I added the following tests:
* cupertino/text_selection_test.dart
  * Widget test to verify selection handles scale correctly when selection height style is `BoxHeightStyle.tight` (this is the default).
  * Widget test to verify selection handle scale correctly when selection height style is `BoxHeightStyle.max`.

Updated goldens:
* material/text_field_test.dart TextSelectionStyle 1

Before|After
---|---
material text_field_golden TextSelectionStyle 1_masterImage|material text_field_golden TextSelectionStyle 1_testImage

* material/text_field_test.dart TextSelectionStyle 2

Before|After
---|---
material text_field_golden TextSelectionStyle 2_masterImage|material text_field_golden TextSelectionStyle 2_testImage

The selection endpoints have shifted down to match the selection style. This is expected.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 21.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 23.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 24.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 26.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 28.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 29.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 1]
```diff
@@ -588,4 +618,167 @@ void main() {
...
+      of: find.byType(Overlay),
+      matching: find.byType(CustomPaint),
+    ));
+
+    // The handle height is determined by the formula:
+    // textLineHeight + _kSelectionHandleRadius * 2 - _kSelectionHandleOverlap .
+    // The text line height will be the value of the fontSize, of the largest word on the line.
+    // The constant _kSelectionHandleRadius has the value of 6.
+    // The constant _kSelectionHandleOverlap has the value of 1.5.
+    // In the case of the start handle, which is located on the word 'def',
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_selection_test.dart:776]: Nit: Maybe mention that in this case, the textLineHeight is the same for both handle locations because of BoxHeightStyle.max.

**Review by justinmc — APPROVED** [review]
LGTM as long as the goldens pass 👍

**Comment by justinmc** [comment]
Looking at your before/after images up in the description, I think the position of the "Copy" button probably needs to be updated too (in another PR).  Can you create an issue for that if that's right?

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 32.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 33.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 34.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 35.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 36.
View them at https://flutter-gold.skia.org/cl/github/85789

**Review by justinmc — APPROVED** [review]
Changes for the goldens LGTM, no more hardcoded offsets 👍

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 38.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by Renzo-Olivares** [comment]
`Linux web_tests_3` currently failing because there is no "Select All" found in `text_field_test` `Text Selection Style 2`.

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 40.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 41.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 42.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 43.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 44.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -824,9 +824,22 @@ class _TextSelectionHandleOverlayState
...
+    // On some platforms we may want to calculate the start and end handles
+    // separately so they scale for the selected content.
+    //
+    // For the start handle we compute the rectangles that encompass the beginning
+    // of the selection.
+    //
+    // For the end handle we compute the rectangles that encompass the end of
+    // the selection.
+    final Rect? startHandleRect = widget.renderObject.getRectForComposingRange(TextRange(start: widget.selection.start, end: widget.selection.start + 1));
+    final Rect? endHandleRect = widget.renderObject.getRectForComposingRange(TextRange(start: widget.selection.end, end: widget.selection.end - 1));
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:836]: `getRectForComposingRange` returns null when (this probably needs better documentation):
- the range is invalid
- the range isCollapsed
- the range does not include a full cluster (see the code comment here: https://github.com/flutter/flutter/blob/f71ceb77fe41e569c546ecd41d1b982ce2d0a0f2/packages/flutter/lib/src/painting/text_painter.dart#L702).

So when the range does not include a full cluster this defaults to the preferred line height which could be very different from the glyph height in some cases? But your test is passing. Let me look at how `GetRectsForRange` works.

Additionally if the text is empty I'm not sure what should `getRectForComposingRange(TextRange(start: 0, end: 1))` return since the range is OOB. I think we should do a proper boundary check instead of relying on undefined behavior.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:836]:
```cpp
      for (const GlyphPosition& gp : run.positions) {
        if (gp.code_units.start >= start && gp.code_units.end <= end) {
          left = std::min(left, static_cast<SkScalar>(gp.x_pos.start));
          right = std::max(right, static_cast<SkScalar>(gp.x_pos.end));
        } else if (gp.code_units.end == end) {
          // Calculate left and right when we are at
          // the last position of a combining character.
          glyph_length = (gp.code_units.end - gp.code_units.start) - 1;
          if (gp.code_units.start ==
              std::max<size_t>(0, (start - glyph_length))) {
            left = std::min(left, static_cast<SkScalar>(gp.x_pos.start));
            right = std::max(right, static_cast<SkScalar>(gp.x_pos.end));
          }
        }
      }
```

It looks like if the start handle is aligned with the family emoji it won't have the correct height?

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 3]
```diff
@@ -588,4 +618,249 @@ void main() {
...
+      of: find.byType(Overlay),
+      matching: find.byType(CustomPaint),
+    ));
+
+    // The handle height is determined by the formula:
+    // textLineHeight + _kSelectionHandleRadius * 2 - _kSelectionHandleOverlap .
+    // The text line height will be the value of the fontSize.
+    // The constant _kSelectionHandleRadius has the value of 6.
+    // The constant _kSelectionHandleOverlap has the value of 1.5.
+    // In the case of the end handle, which is located on the grapheme cluster '👨‍👩‍👦',
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/text_selection_test.dart:858]: Thanks for the detailed explanation!

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 45.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:836]: Oh I missed this behavior in my test. Currently the test selects 'def 👨‍👩‍👦 ' with the start handle at the 'd' and ending handle at the end of the grapheme cluster. 

Screen Shot 2021-07-15 at 1 15 59 PM

The behavior you describe is what I see. At the beginning of the family emoji we don't have the correct height (preferredLineHeight is used in this case), and at the end we do have the correct height.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:836]: I agree we should add a boundary check in `getRectForComposingRange` to make sure the range is valid for the current text.

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 47.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart]: With the latest commit, I've gotten around this issue by getting the rectangles for the range of first/last full grapheme cluster of the given selection instead of only the first/last character of a given selection.

tight|max
---|---
Screen Shot 2021-07-15 at 7 23 42 PM|Screen Shot 2021-07-15 at 7 24 34 PM

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 49.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 52.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 53.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 54.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 56.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 57.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 58.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 59.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 4]
```diff
@@ -824,9 +825,41 @@ class _TextSelectionHandleOverlayState
...
+      // The call to selectedGraphemes.characters.first/last will throw a state
+      // error if the given string is empty, so fall back to first/last character
+      // range in this case.
+      //
+      // The call to widget.selection.textInside(text) will return a RangeError
+      // for a collapsed selection, fall back to this case when that happens.
+      firstSelectedGraphemeExtent = 1;
+      lastSelectedGraphemeExtent = 1;
+    }else{
+      final String selectedGraphemes = widget.selection.textInside(text);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:850]: This may crash: `widget.renderObject.text` represents the text rendered **last frame**, and `widget.selection` represents the selection to render **this frame**. There's a chance the selection indices are OOB for `text` here.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 5]
```diff
@@ -824,9 +825,41 @@ class _TextSelectionHandleOverlayState
...
+      firstSelectedGraphemeExtent = selectedGraphemes.characters.first.length;
+      lastSelectedGraphemeExtent = selectedGraphemes.characters.last.length;
+    }
+
+    final Rect? startHandleRect = widget.renderObject.getRectForComposingRange(TextRange(start: widget.selection.start, end: widget.selection.start + firstSelectedGraphemeExtent));
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:855]: nit: Could you add an assert here that makes sure the `Rect` isn't null when the grapheme extent is greater than 0?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:850]: I'd say we stick to either the text & selection from the last frame or the current frame. The former probably makes more sense since we're relying on the text layout metrics here anyway (calling `getRectForComposingRange`). @justinmc what does the text selection menu do in general for something like this?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:855]: When the selection only contains a trailing/leading new line character might be another interesting edge case to check, as the returned box may be as high as 2 lines.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:850]: The toolbar is based off of the RenderEditable (see [here](https://github.com/flutter/flutter/blob/e9c1c1627adc424cf3dc78ef3994e457e041503f/packages/flutter/lib/src/widgets/editable_text.dart#L2173)) so I believe everything it's using is based off of the previous frame, and I'd agree that we should do the same here too.

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 6]
```diff
@@ -80,6 +83,33 @@ void main() {
     return button.pressedOpacity! < 1.0;
   }
 
+  // Returns the first RenderEditable.
+  RenderEditable findRenderEditable(WidgetTester tester) {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_selection_test.dart:87]: At some point I tried to move stuff like this into utils files so that they could be shared.  Could you use this one here?
https://github.com/flutter/flutter/blob/e9c1c1627adc424cf3dc78ef3994e457e041503f/packages/flutter/test/widgets/editable_text_utils.dart#L11

File: packages/flutter/test/material/text_field_test.dart [hunk 7]
```diff
@@ -833,13 +833,28 @@ void main() {
...
-    await tester.tapAt(textfieldStart + const Offset(100.0, 107.0));
-    await tester.pump(const Duration(milliseconds: 300));
+    await tester.tapAt(textOffsetToPosition(tester, index));
+    await tester.pumpAndSettle();
+    expect(editableTextState.selectionOverlay!.handlesAreVisible, isTrue);
+    expect(controller.selection.baseOffset, 0);
+    expect(controller.selection.extentOffset, 7);
+
+    // Use toolbar to select all text.
+    if(isContextMenuProvidedByPlatform){
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:849]:
```suggestion
    if (isContextMenuProvidedByPlatform) {
```

File: packages/flutter/test/material/text_field_test.dart [hunk 8]
```diff
@@ -833,13 +833,28 @@ void main() {
...
+      controller.selection = TextSelection(baseOffset: 0, extentOffset: controller.text.length);
+      expect(controller.selection.extentOffset, controller.text.length);
+    }else {
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:852]:
```suggestion
    } else {
```

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 9]
```diff
@@ -247,28 +247,38 @@ class CupertinoTextSelectionControls extends TextSelectionControls {
...
+    final Widget customPaint = CustomPaint(
+      painter: _TextSelectionHandlePainter(CupertinoTheme.of(context).primaryColor),
     );
 
     // [buildHandle]'s widget is positioned at the selection cursor's bottom
     // baseline. We transform the handle such that the SizedBox is superimposed
     // on top of the text selection endpoints.
     switch (type) {
       case TextSelectionHandleType.left:
+        desiredSize = getHandleSize(startGlyphHeight);
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/text_selection.dart:270]: Just want to double check that this still works in RTL mode (the left handle still corresponds to the "start" glyph height.

**Review by justinmc — COMMENTED** [review]
Just some nits except for https://github.com/flutter/flutter/pull/85789#discussion_r672479411, which @LongCatIsLooong pointed out.

File: packages/flutter/test/cupertino/text_selection_test.dart (hunk 6 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_selection_test.dart:87]: sure thing!

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 60.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 61.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:850]: Good to know! I agree the text & selection should both come from the same source, I'll make the changes to use the ones from the last frame.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 9 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_selection.dart:270]: Good catch, i'll try this out.

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 62.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 63.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 9 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_selection.dart:270]: https://github.com/flutter/flutter/issues/86763 Opened up a new issue. The start handle is broken only on iOS when switching text direction to RTL, it is unrelated to this change though I was able to reproduce on master.

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 65.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 66.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 67.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 10]
```diff
@@ -824,9 +825,46 @@ class _TextSelectionHandleOverlayState
...
+    // For the start handle we compute the rectangles that encompass the range
+    // of the first full selected grapheme cluster at the beginning of the selection.
+    //
+    // For the end handle we compute the rectangles that encompass the range
+    // of the last full selected grapheme cluster at the end of the selection.
+    final InlineSpan span = widget.renderObject.text!;
+    final String text = span.toPlainText();
+    final int firstSelectedGraphemeExtent;
+    final int lastSelectedGraphemeExtent;
+    if (text.isEmpty || widget.renderObject.selection == null || !widget.renderObject.selection!.isValid || widget.renderObject.selection!.isCollapsed) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:840]: nit: this expression is getting a bit too long. Maybe make selection a local variable, and that way you can promote it to non-null.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 11]
```diff
@@ -824,9 +825,46 @@ class _TextSelectionHandleOverlayState
...
+      final String selectedGraphemes = widget.renderObject.selection!.textInside(text);
+      firstSelectedGraphemeExtent = selectedGraphemes.characters.first.length;
+      lastSelectedGraphemeExtent = selectedGraphemes.characters.last.length;
+    }
+
+    final Rect? startHandleRect = widget.renderObject.getRectForComposingRange(TextRange(start: widget.selection.start, end: widget.selection.start + firstSelectedGraphemeExtent));
+    final Rect? endHandleRect = widget.renderObject.getRectForComposingRange(TextRange(start: widget.selection.end - lastSelectedGraphemeExtent, end: widget.selection.end));
+
+    if (firstSelectedGraphemeExtent > 0 && widget.selection.isValid && !widget.selection.isCollapsed)
+      assert(startHandleRect != null);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:859]: nit: move the expression in the if statement into the assert.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 10 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:840]: if the text is empty the selection is guaranteed to be collapsed/invalid I think?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 12]
```diff
@@ -824,9 +825,46 @@ class _TextSelectionHandleOverlayState
...
+      // range in this case.
+      //
+      // The call to widget.selection.textInside(text) will return a RangeError
+      // for a collapsed selection, fall back to this case when that happens.
+      firstSelectedGraphemeExtent = 0;
+      lastSelectedGraphemeExtent = 0;
+    } else {
+      final String selectedGraphemes = widget.renderObject.selection!.textInside(text);
+      firstSelectedGraphemeExtent = selectedGraphemes.characters.first.length;
+      lastSelectedGraphemeExtent = selectedGraphemes.characters.last.length;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:852]: nit: maybe assert both extents are `<= selection.length`?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM with nits. Thanks for testing out and addressing the edge cases!

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 10 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:840]: Yeah I think that makes sense if both the selection and text belong to the last frame.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 11 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:861]: I think we only want to assert the startHandleRect and endHandleRect is not null when our graphemeExtent is greater than 0 and we confirm our current selection is valid. 

If we assert startHandleRect and endHandleRect even when our selection was invalid then the entire assertion will fail. If the selection was invalid, it is expected start/end handle rects to be null.

```dart
assert(firstSelectedGraphemeExtent > 0 && widget.selection.isValid && !widget.selection.isCollapsed && startHandleRect != null);
assert(lastSelectedGraphemeExtent > 0 && widget.selection.isValid && !widget.selection.isCollapsed && endHandleRect != null);
```

I tried something along the lines above, and received a lot of test failures.

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 68.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 69.
View them at https://flutter-gold.skia.org/cl/github/85789

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 70.
View them at https://flutter-gold.skia.org/cl/github/85789

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 11 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:862]: ```assert(firstSelectedGraphemeExtent > 0 && widget.selection.isValid && !widget.selection.isCollapsed && startHandleRect != null);``` is not identical to the original logic with the `if`. It should be more of a `||` than `&&` right?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:862]:
```dart
assert(firstSelectedGraphemeExtent > 0 || widget.selection.isValid || !widget.selection.isCollapsed || startHandleRect != null);
assert(lastSelectedGraphemeExtent > 0 || widget.selection.isValid || !widget.selection.isCollapsed || endHandleRect != null);
```

Hmm did you mean something like this then? Though I admit I don't really follow this logic, can you elaborate?

The original logic said "if our selectedGraphemeExtent is greater than 0 AND our selection is valid AND the selection is not collapsed THEN assert that handle is not null"

so in our new logic should we "assert that our selectedGraphemeExtent is 0, the selection is not valid, and the selection is collapsed OR handle is not null"?

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 126.
View them at https://flutter-gold.skia.org/cl/github/85789
