### PR TITLE
`SelectableRegion` should use flutter rendered menu on the web for Android and iOS

### LINKED ISSUE #151468: SelectionArea does not show properly the context menu on web on mobile devices
### Steps to reproduce

Run the code below on the web on a real android or iOS device using `flutter run -d web-server --web-port=8080 --web-hostname 0.0.0.0`

### Expected results

The Context menu should appear right away and be near the text.

### Actual results

We have different results depending on the platform.

On Android, the context menu only shows when we start to change the text selection, not when we select the text for the first time:

https://github.com/flutter/flutter/assets/9378033/cf3fdb56-bd0b-4ce0-82db-1bcdfaf199c3

On iOS, we have the same issue, but we also have a weird Share menu in a top left context menu appearing when we first start to select the text:

https://github.com/flutter/flutter/assets/9378033/417b7d57-a2b7-404d-9dc6-428630291354

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SelectionArea(
          child: Center(
            child: Text('Selectable text'),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1.1 23B81 darwin-arm64, locale fr-FR)
    • Flutter version 3.22.2 on channel stable at /Users/romain.rastel/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/romain.rastel/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode-15.0.1.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • IN2023 (mobile)                 • 87950fce                  • android-arm64  • Android 13 (API 33)
    • iPhone (mobile)                 • 00008030-000139323E86402E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change updates the default context menu when using `SelectionArea`/`SelectableRegion` on Android or iOS web.

Previously: the native browser menu would be used.
After this change: the flutter rendered context menu is used.

Fixes https://github.com/flutter/flutter/issues/151468

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/selection_area_test.dart [hunk 1]
```diff
@@ -130,6 +130,50 @@ void main() {
...
+    // for Android and iOS is re-enabled.
+    // See: https://github.com/flutter/flutter/issues/177123.
+    // [intended] Android and iOS use the flutter rendered menu on the web.
+    skip:
+        !kIsWeb ||
+        !<TargetPlatform>{
+          TargetPlatform.android,
+          TargetPlatform.iOS,
+        }.contains(defaultTargetPlatform),
+  );
```
Comment (loic-sharma) [inline packages/flutter/test/material/selection_area_test.dart:175]: Is there an easy way to add a similar test to the `SelectableRegion` layer too? I don't feel strongly about this, feel free to skip (or add this test in a follow-up PR).

**Comment by loic-sharma** [comment]
After this PR lands, consider adding a breaking change notice to the website here: https://docs.flutter.dev/release/breaking-changes#not-yet-released-to-stable

**Review by loic-sharma — APPROVED** [review]
LGTM!

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/test/material/selection_area_test.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/selection_area_test.dart:175]: Added one.

**Review by mdebbar — APPROVED** [review]
LGTM. Thank you Renzo!

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -303,18 +303,21 @@ class SelectableRegion extends StatefulWidget {
...
+          TargetPlatform.android => selectionGeometry.status == SelectionStatus.uncollapsed,
+          TargetPlatform.macOS ||
+          TargetPlatform.fuchsia ||
+          TargetPlatform.linux ||
+          TargetPlatform.windows => false,
+          // TODO(bleroux): the share button should be shown on iOS but the share
+          // functionality requires some changes on the engine side because, on iPad,
+          // it needs an anchor for the popup.
+          // See: https://github.com/flutter/flutter/issues/141775.
+          TargetPlatform.iOS => false,
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:319]: Nit: I think you should do either all of these as `||` ors, or you should assign all of them to `=> false` individually, but don't mix both like it is now.

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/test/material/selection_area_test.dart (hunk 1 above)
Comment (loic-sharma) [reply packages/flutter/test/material/selection_area_test.dart:175]: Awesome! :D

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:319]: I'll leave that as is for now since this code was originally like this. I want to keep the changes in this PR to only be the necessary ones to update the default to flutter rendered menus.
