### PR TITLE
Fix androidSdk NPE

### LINKED ISSUE #46888: `flutter build apk` crashes when the Android SDK can't be found
In `stable/1.12.13+hotfix.5` from crash logging:

```
NoSuchMethodError: The method 'reinitialize' was called on null.
Receiver: null
Tried calling: reinitialize()
  | at Object.noSuchMethod | (object_patch.dart:53 )
  | at _AndroidBuilderImpl.buildApk | (android_builder.dart:105 )
  | at <asynchronous gap> | (async )
  | at BuildApkCommand.runCommand | (build_apk.dart:106 )
  | at FlutterCommand.verifyThenRunCommand | (flutter_command.dart:615 )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:73 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:139 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:680 )
  | at Future._propagateToListeners | (future_impl.dart:709 )
  | at Future._completeWithValue | (future_impl.dart:524 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:554 )
  | at _rootRun | (zone.dart:1126 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _CustomZone.runGuarded | (zone.dart:925 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:965 )
  | at _microtaskLoop | (schedule_microtask.dart:43 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:52 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:118 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:175 )
```

It looks like the `build apk` command may need to declare that it needs the Android SDK here:

https://github.com/flutter/flutter/blob/354f80b84a9b30ec3b49d8fed81bce772a1bc8e8/packages/flutter_tools/lib/src/commands/build_apk.dart#L47

and/or do an explicit cache update at the top of its `runCommand()`.

### LINKED ISSUE #47121: [tool_crash] NoSuchMethodError: The method 'reinitialize' was called on null.Receiver: nullTried calling: reinitialize()
## Command
  ```
  flutter build apk
  ```

  ## Logs
  ```bash
  NoSuchMethodError: NoSuchMethodError: The method 'reinitialize' was called on null.
Receiver: null
Tried calling: reinitialize()
  ```

  ```bash
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:109:18)
<asynchronous suspension>
#2      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:26)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  ```
  ```bash
  [✓] Flutter (Channel master, v1.13.3-pre.23, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.13.3-pre.23 at /Users/ferguson/flutter
    • Framework revision c06bf6503a (2 days ago), 2019-12-13 17:42:35 -0500
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11  • 45BAA160-124F-4DCC-854A-478B62DED189 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins

```yaml
google_maps_flutter
image_picker
shared_preferences
url_launcher
```

### PR DESCRIPTION
**Pull request by blasten**
## Description

`androidSdk` can be `null`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/47121
Fixes https://github.com/flutter/flutter/issues/46888

## Tests

I added the following tests: Unit test. I tried to put the test under the `androidSdk` group and had to refactor the "validateSdkWellFormed() not called, sdk reinitialized" test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by zanderso** [comment]
Also: https://github.com/flutter/flutter/issues/46888

I'm a bit confused. From the crash in that issue, It looks like `androidSdk` can be null in commands like `flutter build apk` where we need to have an Android SDK for the command to work. `androidSdk` can be null when `AndroidSdk.locateAndroidSdk()` returns null: https://github.com/flutter/flutter/blob/86982e195ec9f2ac48eb7ed75c5fec8d86fd84cb/packages/flutter_tools/lib/src/android/android_sdk.dart#L303

In commands where we need it, how about checking very early on that `androidSdk` is non-null and throwing a tool exit directing users to run the doctor?

**Comment by blasten** [comment]
@zanderso as discussed offline, the check is now in the top call.

File: packages/flutter_tools/lib/src/commands/config.dart [hunk 1]
```diff
@@ -173,7 +173,7 @@ class ConfigCommand extends FlutterCommand {
       results['android-studio-dir'] = androidStudio.directory;
     }
     if (results['android-sdk'] == null && androidSdk != null) {
-      results['android-sdk'] = androidSdk.directory;
+      results['android-sdk'] = androidSdk?.directory;
```
[the remark this answers is not in the document]
Comment (blasten) [reply packages/flutter_tools/lib/src/commands/config.dart]: done.

File: packages/flutter_tools/test/general.shard/commands/build_aar_test.dart [hunk 2]
```diff
@@ -90,18 +89,14 @@ void main() {
...
-    FileSystem memoryFileSystem;
 
     setUp(() {
       mockUsage = MockUsage();
       when(mockUsage.isFirstRun).thenReturn(true);
 
-      memoryFileSystem = MemoryFileSystem();
-      tempDir = memoryFileSystem.systemTempDirectory.createTempSync('flutter_tools_packages_test.');
-      memoryFileSystem.currentDirectory = tempDir;
+      tempDir = fs.systemTempDirectory.createTempSync('flutter_tools_packages_test.');
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/commands/build_aar_test.dart]: Was there a problem with the `MemoryFileSystem` ?

Comment (blasten) [reply packages/flutter_tools/test/general.shard/commands/build_aar_test.dart]: It was overriding a parent `tempDir` property. We use `FakeFlutterProjectFactory(tempDir)` in many places to generate a project. It would be good if a project could be generated using the `MemoryFileSystem` without manually adding this boilerplate.

**Review by zanderso — APPROVED** [review]
lgtm w/ question: where does the check happen on a `flutter run`?

**Comment by blasten** [comment]
@zanderso https://github.com/flutter/flutter/blob/354f80b84a9b30ec3b49d8fed81bce772a1bc8e8/packages/flutter_tools/lib/src/android/gradle_utils.dart#L237
