### PR TITLE
Document that TooltipTriggerMode has no impact on hovering

### LINKED ISSUE #113310: Tooltip TooltipTriggerMode.manual is ignored in Windows on a mouse hover event
## Steps to reproduce ##
1.  Wrap a widget in a Tooltip with triggerMode: TooltipTriggerMode.manual.
2. Run the app in windows.
3. Hover over the widget.
4. Tooltip is shown.

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR updates `TooltipTriggerMode` documentation to mention it has no impact on hovering and to emphasize `Tooltip.waitDuration`.

## Motivation: 
- @gspencergoog following comment https://github.com/flutter/flutter/issues/107036#issuecomment-1178024207 
- https://github.com/flutter/flutter/issues/113310

## Related Issue

Fixes https://github.com/flutter/flutter/issues/113310

## Tests

Test exempt (documentation only).

### CODE REVIEW

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 1]
```diff
@@ -299,6 +299,15 @@ class TooltipTheme extends InheritedTheme {
 
 /// The method of interaction that will trigger a tooltip.
 /// Used in [Tooltip.triggerMode] and [TooltipThemeData.triggerMode].
+///
+/// On desktop, a tooltip will be shown when a pointer hovers it
+/// whatever the value of trigger mode is.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/tooltip_theme.dart:304]:
```suggestion
/// On desktop, a tooltip will be shown as soon as a pointer hovers over 
/// the widget, regardless of the value of [Tooltip.triggerMode].
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks for the PR!
