### PR TITLE
🐛 Treat empty ARB content as empty map when decoding

### LINKED ISSUE #128932: [gen-l10n] Should not parse empty arb files as JSON content
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter create bug`
2. Integrate l10n as suggested.
3. Add `format: true` to `l10n.yaml`.
4. Create an empty arb file without any content in it (totally empty not even with `{}`).
5. Run `flutter gen-l10n`.

### Expected results

Only the generated dart files should be formatted.

### Actual results

l10n files except the untranslated message file are formatted.

### Code sample

<details><summary>Code sample</summary>

```yaml
synthetic-package: false
arb-dir: lib/src
format: true
output-dir: lib/src/gen
output-localization-file: app_localizations.dart
template-arb-file: l10n_en.arb
untranslated-messages-file: lib/src/gen/localizations_untranslated.json
```

</details>

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console
Because l10n.yaml exists, the options defined there will be used instead.                                                                                                                                                                                
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


The arb file X:\Coding\Garages\packages\l10n\lib/src\l10n_zh.arb has the following formatting issue: 
FormatException: Unexpected end of input (at character 1)

^
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.5 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (33 hours ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

### PR DESCRIPTION
**Pull request by AlexV525**
Fixes #128932.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 1]
```diff
@@ -569,10 +569,14 @@ class Message {
 // Represents the contents of one ARB file.
 class AppResourceBundle {
   factory AppResourceBundle(File file) {
-    // Assuming that the caller has verified that the file exists and is readable.
```
Comment (thkim1011) [inline packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:572]: I think we should keep this comment, just put it above the factory constructor declaration.

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 2]
```diff
@@ -657,20 +661,23 @@ class AppResourceBundleCollection {
     final RegExp filenameRE = RegExp(r'(\w+)\.arb$');
     final Map<LocaleInfo, AppResourceBundle> localeToBundle = <LocaleInfo, AppResourceBundle>{};
     final Map<String, List<LocaleInfo>> languageToLocales = <String, List<LocaleInfo>>{};
-    final List<File> files = directory.listSync().whereType<File>().toList()..sort(sortFilesByPath);
+    final List<File> files = directory
+        .listSync()
+        .whereType<File>()
+        .where((File e) => filenameRE.hasMatch(e.path))
+        .toList()
+      ..sort(sortFilesByPath);
```
Comment (thkim1011) [inline packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:669]: There are some spacing issues here and we should also add a comment to clarify why we need sort.
```suggestion
    // We require the list of files to be sorted so that "languageToLocales[bundle.locale.languageCode]"
    // is not null by the time we handle locales with country codes.
    final List<File> files = directory
      .listSync()
      .whereType<File>()
      .where((File e) => filenameRE.hasMatch(e.path))
      .toList()
      ..sort(sortFilesByPath);
```

File: packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart [hunk 3]
```diff
@@ -501,4 +502,10 @@ format: true
       throwsToolExit(message: 'Unexpected positional argument "false".')
     );
   });
+
+  testWithoutContext('Empty ARB can be parsed without FormatException', () {
+    final File arbFile = fileSystem.file(fileSystem.path.join('lib', 'l10n', 'app_en.arb'))
+      ..createSync(recursive: true);
+    expect(AppResourceBundle(arbFile), isA<AppResourceBundle>());
+  });
```
Comment (thkim1011) [inline packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart:510]: Can we also write a more end-to-end test that calls the `gen-l10n` command on an empty `app_en.arb` file. I think we should expect it to run without errors.

**Review by thkim1011 — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart (hunk 2 above)
Comment (AlexV525) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:669]: The spacing should be correct, you may run `dart format` to check the result.

File: packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart (hunk 3 above)
Comment (AlexV525) [reply packages/flutter_tools/test/commands.shard/hermetic/generate_localizations_test.dart]: Sure, added a new test and made them as a new group.

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart (hunk 2 above)
Comment (AlexV525) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:673]: Comments are added.

Comment (Piinks) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:673]: > you may run dart format to check the result.

Hi @AlexV525, thanks for contributing. The flutter/flutter repo does not use `dart format`. The formatting used in this repo is covered in detail in the [flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo).

Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:673]: > The spacing should be correct, you may run `dart format` to check the result.

As @Piinks said, flutter doesn't use `dart format` and typically we have no instance of extra four space indents following a line. Two space indenting each line after the `files` variable declaration is what we usually do.

Comment (AlexV525) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart]: For the record, these are what I've found in the repo:
https://github.com/flutter/flutter/blob/f8afcd5aa01b3ae6c55cb6e4c9fa4171e27a92f6/packages/flutter_tools/lib/src/web/compile.dart#L237-L240
https://github.com/flutter/flutter/blob/f8afcd5aa01b3ae6c55cb6e4c9fa4171e27a92f6/packages/flutter_tools/lib/src/base/analyze_size.dart#L326-L327

Our style guide wasn't specific about how cascade notations should indent after instance callers. For me, regardless of `dart format`, it makes me quickly identify what variable the cascade is targeting.

Though I don't have a strong opinion about this, but if we suggest this, we should put it into the style guide too.

Updated.

**Review by thkim1011 — APPROVED** [review]
LGTM.
