### PR TITLE
Fix MediaQuery.paddingOf

### LINKED ISSUE #116842: MediaQuery.paddingOf does not rebuild when value changes
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press on a text field to open the keyboard
3. In the console, the value of paddingOf(context) was output 1 time, although this value should change during the keyboard animation.
4. If the useMediaQueryOf in _HomeState is set to true (Restart the App after this) and you then click on a text field you will see the output several times in the console.

**Expected results:** 
MediaQuery.paddingOf(context) should rebuild if the value changes.

**Actual results:** 
MediaQuery.paddingOf(context) does not rebuild if the value changes.

@moffatman 

<details>
<summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
      showPerformanceOverlay: true,
    );
  }
}

class Home extends StatelessWidget {
  bool useMediaQueryOf = false;

  @override
  Widget build(BuildContext context) {
    if (useMediaQueryOf) {
      print(MediaQuery.of(context).padding);
    } else {
      print(MediaQuery.paddingOf(context));
    }

    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemBuilder: (_, ndx) {
          return TextField();
        },
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.7.0-4.0.pre.62, on macOS 12.6 21G115 darwin-arm64, locale en-US)
    • Flutter version 3.7.0-4.0.pre.62 on channel master at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be5c389e6c (23 hours ago), 2022-12-09 20:52:32 -0500
    • Engine revision faae28965a
    • Dart version 3.0.0 (build 3.0.0-3.0.dev)
    • DevTools version 2.20.0
```

</details>

### PR DESCRIPTION
**Pull request by moffatman**
`_MediaQueryAspect.padding` was omitted in `updateShouldNotifyDependent`. I changed it now to a switch-case to avoid missing cases. Switch-case also should be faster as it's expected only to have a few dependencies, so we can avoid comparing all fields.

Adding the new test identified that `MediaQueryData.systemGestureInsets` was never being compared properly. 

Fixes #116842

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 1]
```diff
@@ -1282,23 +1284,103 @@ class MediaQuery extends InheritedModel<_MediaQueryAspect> {
...
-        || (data.invertColors != oldWidget.data.invertColors && dependencies.contains(_MediaQueryAspect.invertColors))
-        || (data.highContrast != oldWidget.data.highContrast && dependencies.contains(_MediaQueryAspect.highContrast))
-        || (data.disableAnimations != oldWidget.data.disableAnimations && dependencies.contains(_MediaQueryAspect.disableAnimations))
-        || (data.boldText != oldWidget.data.boldText && dependencies.contains(_MediaQueryAspect.boldText))
-        || (data.navigationMode != oldWidget.data.navigationMode && dependencies.contains(_MediaQueryAspect.navigationMode))
-        || (data.gestureSettings != oldWidget.data.gestureSettings && dependencies.contains(_MediaQueryAspect.gestureSettings))
-        || (data.displayFeatures != oldWidget.data.displayFeatures && dependencies.contains(_MediaQueryAspect.displayFeatures));
+    for (final Object dependency in dependencies) {
+      if (dependency is _MediaQueryAspect) {
+        switch (dependency) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/media_query.dart:1289]: switch/case is a nice improvement!

**Review by goderbauer — APPROVED** [review]
Nice catch! Thanks for the fix!

LGTM
