### PR TITLE
Fix LinearProgressIndicator track painting.

### LINKED ISSUE #164538: Need another update to `LinearProgressIndicator`
https://m3.material.io/components/progress-indicators/guidelines#52941353-14e2-4c24-9d40-ce2806dcd836

In Material Design, both determinate and indeterminate processes have gap between indicator and track, but in flutter, indeterminate one don't have gap and `trackGap` can not add gap to it when `year2023` flag is set to false.

### LINKED ISSUE #173096: Material 3 LinearProgressIndicator paints track outside of bounds.
### Steps to reproduce

1. Display `LinearProgressIndicator` widget on screen
2. Set `trackGap` to a value higher than the default (e.g., 20) _(this is not necessary, but it helps to see the issue)_ 
3. Set `value` to any number in the range [0.96, 0.99]

### Expected results

LinearProgressIndicator doesn't paint the track outside of bounds.

### Actual results

LinearProgressIndicator paints the track outside of bounds.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final _value = ValueNotifier(0.0);

  @override
  void dispose() {
    _value.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Directionality(
          textDirection: TextDirection.ltr,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              spacing: 20,
              children: [
                ValueListenableBuilder(
                  valueListenable: _value,
                  builder: (context, value, child) {
                    return LinearProgressIndicator(
                      year2023: false,
                      value: value,
                      trackGap: 20,
                    );
                  },
                ),
                ValueListenableBuilder(
                  valueListenable: _value,
                  builder: (context, value, child) {
                    return Slider(
                      value: value,
                      onChanged: (value) => _value.value = value,
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/fc32e811-eb50-42db-824f-fea3f12d8ac8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.33.0-1.0.pre-1201, on macOS 15.5 24F74 darwin-arm64, locale en-US) [2.7s]
    • Flutter version 3.33.0-1.0.pre-1201 on channel master at /Users/ksokolovskyi/development/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 5f6fbe2275 (27 hours ago), 2025-07-30 22:21:26 -0700
    • Engine revision 5f6fbe2275
    • Dart version 3.10.0 (build 3.10.0-49.0.dev)
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [4.2s]
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [1,764ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [5.9s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 138.0.7204.184

[✓] Network resources [1,442ms]
    • All expected network resources are available.
```

</details>

### LINKED ISSUE #173153: LinearProgressIndicator track gap remains when value is 0 and year2023 is false
### Steps to reproduce

run the code sample

### Expected results

NO track gap

### Actual results

track gap remains

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget _indicator(double value) {
    return Column(
      spacing: 2,
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          'value: $value',
          style: const TextStyle(fontSize: 16),
        ),
        LinearProgressIndicator(
          value: value,
          year2023: false,
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          width: 255,
          child: Column(
            spacing: 10,
            mainAxisSize: MainAxisSize.min,
            children: [
              _indicator(0.5),
              _indicator(0.0),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/164538
Fixes https://github.com/flutter/flutter/issues/173096
Fixes https://github.com/flutter/flutter/issues/173153

### Description
- Adds support for `trackGap` in indeterminate `LinearProgressIndicator`
- Fixes track painting outside of `LinearProgressIndicator` bounds when `trackGap` is greater than zero
- Fixes `LinearProgressIndicator` track gap painting when `value` is 0
- Adds golden tests

_[androidx.compose.material3](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/ProgressIndicator.kt) and [material-components-android](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/progressindicator/LinearDrawingDelegate.java) implementations were used as a reference._

<table>
   <thead>
      <tr>
         <th>Before</th>
         <th>After</th>
      </tr>
   </thead>
   <tbody>
      <td colspan="2" align="center">Determinate (regular)</code></td>
      </tr>
      <tr>
         <td>before</td>
         <td>after</td>
      </tr>
      <td colspan="2" align="center">Determinate (<code>trackGap: 20</code>)</td>
      <tr>
         <td>before</td>
         <td>after</td>
      </tr>
      <tr>
         <td colspan="2" align="center">Indeterminate (regular)</code></td>
      </tr>
      <tr>
         <td>before</td>
         <td>after</td>
      </tr>
      <tr>
         <td colspan="2" align="center">Indeterminate (<code>trackGap: 20</code>)</td>
      </tr>
      <tr>
         <td>before</td>
         <td>after</td>
      </tr>
   </tbody>
</table>

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 1]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
 
-    void drawActiveIndicator(double x, double width) {
-      if (width <= 0.0) {
-        return;
+    if (effectiveValue != null) {
+      final double trackStartFraction = trackGapFraction > 0
+          ? effectiveValue + math.min(effectiveValue, trackGapFraction)
+          : 0;
+
+      // Draw the track.
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart]:
```suggestion
      // Only draw the track when there is still space.
```
just nit, I'm trying to understand the painting logic here. So just wanted to add some more comments to help understand:)

**Review by QuncCccccc — COMMENTED** [review]
I haven't finished my review but thank you so much for your contribution. Overall it looks good! Will take another look! The golden tests look great!

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 2]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
+      return;
     }
 
-    // Draw the active indicator.
-    if (value != null) {
-      drawActiveIndicator(0.0, clampDouble(value!, 0.0, 1.0) * size.width);
-    } else {
-      final double x1 = size.width * line1Tail.transform(animationValue);
-      final double width1 = size.width * line1Head.transform(animationValue) - x1;
+    final double firstLineHead = line1Head.transform(animationValue);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart:270]: Might worth to add a comment to clarify that with `TextDirection.ltr`, the `firstLineHead` is the right endpoint of the first line and `firstLineTail` is the left endpoint of the first line. I thought the head means the left, and tail means the right and so had a hard time understanding the logic:) So just wanted to put some comments to avoid any confusion.

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 3]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
+    final double firstLineTail = line1Tail.transform(animationValue);
+    final double secondLineHead = line2Head.transform(animationValue);
+    final double secondLineTail = line2Tail.transform(animationValue);
+
+    // Draw the track before line 1.
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart]: Should this be drawing the track after line 1? Or to be more accurate, we can say it's drawing the track on the right side of line 1.

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 4]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
+    if (firstLineHead < 1 - trackGapFraction) {
+      final double trackStartFraction = firstLineHead > 0
+          ? firstLineHead + math.min(firstLineHead, trackGapFraction)
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart]: `math.min(firstLineHead, trackGapFraction)` is used in several places. I think it would be better if we create a method and call the method when we want to calculate the gap fraction, or, we add a comment for each use case of `math.min(...)`, just for better understanding and easier to maintain.

Something like:
```dart'
// This is to get the "lerped" track gap fraction so that when the currentValue is smaller than the `trackGapFraction`, the returned value is growing as the currentValue, up to `trackGapFraction`.
double calculateTrackGapFraction(double currentValue, double trackGapFraction ) {
    return math.min(currentValue, trackGapFraction);
}
```

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 5]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
+      drawLinearIndicator(
+        startFraction: firstLineTail,
+        endFraction: firstLineHead,
+        color: valueColor,
+      );
+    }
 
-      final double x2 = size.width * line2Tail.transform(animationValue);
-      final double width2 = size.width * line2Head.transform(animationValue) - x2;
+    // Draw the track between line 1 and line 2.
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart]:
```suggestion
    // Draw the track between line 1 and line 2. Assuming `TextDirection.ltr`, this track shows up on the left side of line 1.
```

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 6]
```diff
@@ -183,87 +183,122 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
 
-    // Draw the active indicator.
-    if (value != null) {
-      drawActiveIndicator(0.0, clampDouble(value!, 0.0, 1.0) * size.width);
-    } else {
-      final double x1 = size.width * line1Tail.transform(animationValue);
-      final double width1 = size.width * line1Head.transform(animationValue) - x1;
+    final double firstLineHead = line1Head.transform(animationValue);
+    final double firstLineTail = line1Tail.transform(animationValue);
+    final double secondLineHead = line2Head.transform(animationValue);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart:272]: Also for secondLine, might be better if we can add a brief comment.

**Comment by ksokolovskyi** [comment]
Hi @QuncCccccc, thanks a lot for your review and suggestions! I added a number of comments to help understand the code. Could you please take a look again when you have time?

**Comment by ksokolovskyi** [comment]
@QuncCccccc, I noticed that the Android `material-components` implementation of the progress indicator handles the effective `trackGap` differently. In that version, the `trackGap` gradually increases until progress reaches 1%, after which it remains at its full length ([Source 1](https://github.com/material-components/material-components-android/blob/c30c2d8056bc9b12bd118f0fe55744198ac3738c/lib/java/com/google/android/material/progressindicator/DeterminateDrawable.java#L340-L349), [Source 2](https://github.com/material-components/material-components-android/blob/c30c2d8056bc9b12bd118f0fe55744198ac3738c/lib/java/com/google/android/material/progressindicator/LinearDrawingDelegate.java#L228-L232)).

Below is the comparison of the two approaches with a `trackGap: 20`. The top one is from the `Compose` (the one which is used in this PR), and the bottom one is from the Android `material-components` library.

https://github.com/user-attachments/assets/81ff5157-a7ec-4a32-b243-fe4b2addf159

The code for the new approach:

```dart
double getEffectiveTrackGapFraction(double currentValue, double trackGapFraction) {
  // If the progress is less than 1%, the gap will be proportional to the
  // progress. So that, it draws a full track at 0%.
  const double kGapRampDownThreshold = 0.01;

  return trackGapFraction *
      clampDouble(currentValue, 0, kGapRampDownThreshold) /
      kGapRampDownThreshold;
}
```

Given this difference in the effective `trackGap` calculation, should we align with the Android implementation, or use a Compose one?

**Comment by QuncCccccc** [comment]
I think both are fine. We can use the current algorithm as is because I think usually the gap is small and we can barely detect the difference during animation.

_Update_: I just talked with @TahaTesser who implemented the updated LinearProgressIndicator. Since overall the Android material-components repo are more reliable and usually have faster updates from newer Material specs, keeping the original calculation (material-components) would be a better option.

File: packages/flutter/lib/src/material/progress_indicator.dart (hunk 5 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/progress_indicator.dart]: Seems this comment was resolved directly. Adding some more explanation would be helpful for later maintenance:)

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thank for your fix:) Add this comment here again in case it's missed:) https://github.com/flutter/flutter/pull/173108#issuecomment-3221531686

**Comment by ksokolovskyi** [comment]
@QuncCccccc, sorry for the spam, I messed up a bit with git.

I updated the effective `trackGap` calculation to be exactly as in the Android `material-components` library. This will probably update the goldens again. Could you please give this PR another look?

File: packages/flutter/lib/src/material/progress_indicator.dart (hunk 5 above)
Comment (ksokolovskyi) [reply packages/flutter/lib/src/material/progress_indicator.dart]: Thanks, indeed, I missed this one.

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 7]
```diff
@@ -183,87 +187,142 @@ class _LinearProgressIndicatorPainter extends CustomPainter {
...
       };
       canvas.drawCircle(position, radius, indicatorPaint);
     }
 
-    // Draw the stop indicator.
-    if (value != null && stopIndicatorRadius != null && stopIndicatorRadius! > 0) {
-      drawStopIndicator();
+    // Calculates a track gap fraction that is scaled proportionally to a given
+    // value.
+    // This is used to smoothly transition the track gap's size, preventing it
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/progress_indicator.dart]: maybe
```suggestion
    // This is used for a smooth transition of the track gap's size, preventing it
```

**Review by QuncCccccc — APPROVED** [review]
LGTM.

**Comment by ksokolovskyi** [comment]
@QuncCccccc thanks a lot for your review and suggestions!

**Comment by ksokolovskyi** [comment]
@QuncCccccc I don't see `Google Testing` in checks, and not sure why it wasn't run after the master branch merge. Today morning, `Google Testing` was failing in this PR, so in case there are any issues with the tree, we need to revert this PR.

**Comment by QuncCccccc** [comment]
Oh thank for letting me know! For this kind of change, we probably should only submit it after Google testing has passed next time. 

> not sure why it wasn't run after the master branch merge.

Yeah, the google testing sometimes just don't start testing. Might need to try to re-trigger it by rebasing with master.
