### PR TITLE
Fix text selection toolbar alignment for RTL languages

### LINKED ISSUE #59306: Material text selection menu wrong item order in RTL
When the text direction is RTL, the material text selection menu item are still LTR.

### Native android:

| LTR | Forced RTL |
|---|---|
|Screenshot_1591936926 | Screenshot_1591937039|

### PR DESCRIPTION
**Pull request by SalehTZ**
**Fix text selection toolbar alignment for RTL (right-to-left) languages**

This PR updates the Material text selection toolbar to properly support right-to-left (RTL) layouts. Previously, the toolbar and its buttons did not align or order correctly when using RTL text direction, leading to a broken or confusing user experience for RTL languages.

**Summary of changes:**
- Refactored layout logic in `text_selection_toolbar.dart` to handle RTL and LTR directions for both horizontal and overflow (vertical) arrangements.
- Updated padding logic in `text_selection_toolbar_text_button.dart` to use `EdgeInsetsDirectional`, ensuring correct padding for both text directions.
- Added new widget tests to verify that:
  - Toolbar items are ordered right-to-left in RTL contexts.
  - The overflow menu behaves correctly in RTL, showing items in the correct order and position.

**Before:**  
- Toolbar items and overflow menus did not respect RTL layout, resulting in misaligned or reversed button order.
- Padding was inconsistent in RTL.
<details>
<summary>Before Screenshots</summary>

| LTR Not Expanded | LTR Expanded | RTL Not Expanded | RTL Expanded |
|---|---|---|---|
| before_ltr_non_expanded jpg | before_ltr_expanded jpg | before_rtl_non_expanded | before_rtl_expanded |

</details>

**After:**  
- Toolbar items and overflow menus are correctly ordered and aligned for RTL.
- Button padding is now directionally correct.

<details>
<summary>After Screenshots</summary>

| LTR Not Expanded | LTR Expanded | RTL Not Expanded | RTL Expanded |
|---|---|---|---|
| after_ltr_non_expanded | after_ltr_expanded | after_rtl_not_expanded | after_rtl_expanded |

</details>

This improves the usability and accessibility of text selection controls for users of RTL languages.

Fixes #59306 

---

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart [hunk 1]
```diff
@@ -81,21 +81,24 @@ class TextSelectionToolbarTextButton extends StatelessWidget {
   ///
   /// Standard Material [TextSelectionToolbar]s have buttons with different
   /// padding depending on their position in the toolbar.
-  static EdgeInsets getPadding(int index, int total) {
+  static EdgeInsetsGeometry getPadding(int index, int total) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart:84]: I've started the Google tests on this PR just to make sure this doesn't break anyone.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 2]
```diff
@@ -513,57 +536,145 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
-        return;
+    if (!overflowOpen) {
+      // Horizontal layout
+      final List<RenderBox> paintedContentItems = <RenderBox>[];
+      bool navButtonIsPainted = false;
+
+      double totalHorizontalWidth = 0;
+      double maxHorizontalHeight = 0;
+
+      // First pass: calculate dimensions and collect items
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: Nit: Add a period at the end of these comments here and below.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 3]
```diff
@@ -513,57 +536,145 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
+
+        // Position content items from right to left
+        double rightEdge = totalHorizontalWidth;
+        for (final RenderBox item in paintedContentItems) {
+          rightEdge -= item.size.width;
+          final ToolbarItemsParentData itemParentData = item.parentData! as ToolbarItemsParentData;
+          itemParentData.offset = Offset(rightEdge, 0.0);
+        }
+      } else {
+        if (isRtl) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: It looks to me like this boolean can't be true here? I think the `else` above is the case where isRtl is false, and this whole `if` block is duplicated and can be removed.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 4]
```diff
@@ -513,57 +536,145 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
-      i++;
-
-      final RenderBox child = renderObjectChild as RenderBox;
-      final ToolbarItemsParentData childParentData = child.parentData! as ToolbarItemsParentData;
+    final bool isRtl = textDirection == TextDirection.rtl;
 
-      // Handle placing the navigation button after iterating all children.
-      if (renderObjectChild == navButton) {
-        return;
+    if (!overflowOpen) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: Would it be useful to split the layout when overflowOpen true/false into two separate methods in order to reduce some of the nested conditionals in this method? I find it somewhat hard to read (though it is harder to read on GitHub than in the IDE).

File: packages/flutter/test/material/text_selection_toolbar_test.dart [hunk 5]
```diff
@@ -352,4 +353,101 @@ void main() {
...
+              anchorAbove: const Offset(50.0, 100.0),
+              anchorBelow: const Offset(50.0, 200.0),
+              children: children,
+            ),
+          ),
+        ),
+      ),
+    );
+
+    // Verify all items are visible
```
Comment (justinmc) [inline packages/flutter/test/material/text_selection_toolbar_test.dart]: Periods at the ends of these comments as well.

File: packages/flutter/test/material/text_selection_toolbar_test.dart [hunk 6]
```diff
@@ -352,4 +353,101 @@ void main() {
...
+              (Element e) =>
+                  tester.getRect(find.byElementPredicate((Element element) => element == e)),
+            )
+            .toList();
+
+    // In RTL, items should be ordered right-to-left
+    for (int i = 0; i < itemRects.length - 1; i++) {
+      expect(
+        itemRects[i].left,
+        equals(itemRects[i + 1].right),
```
Comment (justinmc) [inline packages/flutter/test/material/text_selection_toolbar_test.dart]: Is the order of itemRects guaranteed to be the order that they appear in the UI?

You could also `find.text('$i')` and make sure that it's right next to `find.text('${i + 1}')`.

**Review by justinmc — COMMENTED** [review]
Thank you so much for stepping in to fix this. This is a high quality PR fixing what must be a very annoying for RTL users. I appreciate the screenshots too.

The comments below are mostly small stuff, overall this looks good.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 3 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: My bad, You're absolutely right, fix on the way.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 2 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: Done.

File: packages/flutter/test/material/text_selection_toolbar_test.dart (hunk 5 above)
Comment (SalehTZ) [reply packages/flutter/test/material/text_selection_toolbar_test.dart]: Done.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 4 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: Yeah that's true, I'm refactoring it. Much cleaner now 😅

**Comment by SalehTZ** [comment]
@justinmc  Is it good to add this line to `hitTestChildren` method?

```dart
// Don't hit test children aren't shown.
if (!childParentData.shouldPaint) {
    return false;
}
```

result be like:

```dart
  // Include the parent data offset in the hit test.
  @override
  bool hitTestChildren(BoxHitTestResult result, {required Offset position}) {
    // The x, y parameters have the top left of the node's box as the origin.
    final ToolbarItemsParentData childParentData = child!.parentData! as ToolbarItemsParentData;

    // Don't hit test children aren't shown.
    if (!childParentData.shouldPaint) {
      return false;
    }

    return result.addWithPaintOffset(
      offset: childParentData.offset,
      position: position,
      hitTest: (BoxHitTestResult result, Offset transformed) {
        assert(transformed == position - childParentData.offset);
        return child!.hitTest(result, position: transformed);
      },
    );
  }
```

File: packages/flutter/test/material/text_selection_toolbar_test.dart (hunk 6 above)
Comment (SalehTZ) [reply packages/flutter/test/material/text_selection_toolbar_test.dart]: for `find.text('$i')` we should pass a child to `TestBox` widget as well. That's doable (not a breaking change) but IDK if that's necessary.

With small change in `TestBox`, I can tweak the test a little bit (double check rightEdges) to be like below, is this more reliable?

<details>
<summary>Details</summary>

```dart
testWidgets('items are ordered right-to-left in RTL', (WidgetTester tester) async {
    const int itemCount = 3;
    final List<Widget> children = List<Widget>.generate(
      itemCount,
      (int i) => TestBox(key: ValueKey<String>('item_$i'), child: Text('$i')),
    );

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Directionality(
            textDirection: TextDirection.rtl,
            child: TextSelectionToolbar(
              anchorAbove: const Offset(50.0, 100.0),
              anchorBelow: const Offset(50.0, 200.0),
              children: children,
            ),
          ),
        ),
      ),
    );

    // Verify all items are visible.
    expect(find.byType(TestBox), findsNWidgets(itemCount));

    // Find all text widgets by their content and get their positions.
    final List<Rect> textRects = List<Rect>.generate(
      itemCount,
      (int i) => tester.getRect(find.text('$i')),
    );

    // In RTL, items should be in reverse order (2, 1, 0).
    // So item 2 should be rightmost, then 1, then 0.
    for (int i = 0; i < itemCount - 1; i++) {
      final Rect current = textRects[i];
      final Rect next = textRects[i + 1];

      // In RTL, each item should be to the left of the previous one.
      expect(
        next.right,
        lessThanOrEqualTo(current.left),
        reason: 'In RTL, item ${i + 1} should be to the left of item $i',
      );
    }

    // Verify the visual order by checking the rightmost position.
    final List<double> rightEdges = textRects.map((Rect r) => r.right).toList();
    final List<double> sortedRightEdges = List<double>.from(rightEdges)
      ..sort((double a, double b) => b.compareTo(a));
    expect(
      rightEdges,
      equals(sortedRightEdges),
      reason: 'Items should be ordered right-to-left in RTL',
    );
  });
  
```
</details>

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 7]
```diff
@@ -510,63 +533,138 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
+    final bool isRtl = textDirection == TextDirection.rtl;
+
+    final List<RenderBox> paintedContentItems = <RenderBox>[];
+    bool navButtonIsPainted = false;
+
+    double totalHorizontalWidth = 0;
+    double maxHorizontalHeight = 0;
+
+    // First pass: calculate dimensions and collect items.
+    int childIdx = 0;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: Nit: `childIndex` to avoid abbreviations per the styleguide: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-abbreviations

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 8]
```diff
@@ -510,63 +533,138 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
+    RenderBox? current = firstChild;
+    while (current != null) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: Why not use visitChildren?

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 9]
```diff
@@ -510,63 +533,138 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
-      final ToolbarItemsParentData childParentData = child.parentData! as ToolbarItemsParentData;
+    // Position items based on text direction.
+    double currentX = 0.0;
 
-      // Handle placing the navigation button after iterating all children.
-      if (renderObjectChild == navButton) {
-        return;
+    if (isRtl) {
+      // In RTL, we want the nav button on the left and items right-aligned.
+      if (navButtonIsPainted) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: I think you could also use `_lastIndexThatFits >= 0` and get rid of navButtonIsPainted.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 10]
```diff
@@ -510,63 +533,138 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox
...
+        currentX += navButton.size.width;
       }
 
-      // There is no need to place children that won't be painted.
-      if (!_shouldPaintChild(renderObjectChild, i)) {
-        childParentData.shouldPaint = false;
-        return;
+      // Position content items from right to left.
+      double rightEdge = totalHorizontalWidth;
+      for (final RenderBox item in paintedContentItems) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart]: Would it end up any cleaner if there was only a single loop over the children in this method? The fact that the children are looped over twice gives a little bit of pause here. I realize it's not going to matter very much for performance, though.

File: packages/flutter/test/material/text_selection_toolbar_test.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/test/material/text_selection_toolbar_test.dart]: Good call! This way satisfies me :+1:

File: packages/flutter/test/material/text_selection_toolbar_test.dart [hunk 11]
```diff
@@ -352,4 +353,111 @@ void main() {
...
+    expect(find.byType(TestBox), findsNWidgets(itemCount));
+
+    // Find all text widgets by their content and get their positions.
+    final List<Rect> textRects = List<Rect>.generate(
+      itemCount,
+      (int i) => tester.getRect(find.text('$i')),
+    );
+
+    // In RTL, items should be in reverse order (2, 1, 0).
+    // So item 2 should be rightmost, then 1, then 0.
```
Comment (justinmc) [inline packages/flutter/test/material/text_selection_toolbar_test.dart]: Do you mean that item 2 should be leftmost?

**Review by justinmc — COMMENTED** [review]
Let's see what happens with CI, hopefully when you update the PR it will go green.

About your hitTestChildren question in https://github.com/flutter/flutter/pull/169854#issuecomment-2951746574. Is that the hitTestChildren in _TextSelectionToolbarTrailingEdgeAlignRenderBox? Yeah good optimization, I say add it.

**Comment by SalehTZ** [comment]
> Let's see what happens with CI, hopefully when you update the PR it will go green.
> 
> About your hitTestChildren question in [#169854 (comment)](https://github.com/flutter/flutter/pull/169854#issuecomment-2951746574). Is that the hitTestChildren in _TextSelectionToolbarTrailingEdgeAlignRenderBox? Yeah good optimization, I say add it.


Yes it is, I forgot to mention the class 😁. Then i'll add and test it.

Edit: unfortunately it causes tests mentioned below to fail:
- `Overflowed menu expands children horizontally`
- `puts children in an overflow menu if they overflow`
- `puts children in an overflow menu if they overflow in RTL `

with this common message:

> The following assertion was thrown running a test:
> Finder specifies a widget that would not receive pointer events.
> A call to tap() with finder "Found 1 widget with widget matching predicate descending from widget
> with type "MaterialApp": [
>   _TextSelectionToolbarOverflowButton-[<StandardComponentType.moreButton>],
> ]" derived an Offset (Offset(732.0, 70.0)) that would not hit test on the specified widget.
> Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot
> receive pointer events.

If its priority isn't high, I'll work on this later and create a separate issue and PR for it.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 7 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: done

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 9 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: hmm, I'll check it 🤔

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 8 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: done

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 9 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: I think we could also use `_shouldPaintChild(navButton, 0)`, am I right?

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 10 above)
Comment (SalehTZ) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: Yeah, that's a fair point. I went back and forth on that too. I ended up sticking with two loops because it felt cleaner to read. And like you said, performance isn't really an issue (specially for a small toolbar), so I figured it was a good trade-off for making it more straightforward.

for the `for` loops inside `if (isRtl) {} else {}` it would be something like this:
```dart
double currentX = 0.0;
double rightEdge = isRtl ? totalWidth : 0.0;

for (final RenderBox item in contentItems) {
  final itemParentData = item.parentData! as ToolbarItemsParentData;
  if (isRtl) {
    rightEdge -= item.size.width;
    itemParentData.offset = Offset(rightEdge, 0.0);
  } else {
    itemParentData.offset = Offset(currentX, 0.0);
    currentX += item.size.width;
  }
}
```

but I think in general the only potential micro-optimization would be to use a `for` loop with manual sibling traversal instead of `visitChildren` to avoid the function call overhead, but the difference would be negligible and not worth the reduced readability.

File: packages/flutter/test/material/text_selection_toolbar_test.dart (hunk 11 above)
Comment (SalehTZ) [reply packages/flutter/test/material/text_selection_toolbar_test.dart]: Yes exactly. Fixed

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: That makes sense, I agree and it's more readable so I say keep it as-is. Thanks for thoroughly investigating that.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: Yeah either way is fine with me.

**Review by justinmc — APPROVED** [review]
LGTM if Google tests pass :+1: . Thanks for jumping in to help with RTL. It's a bit of a blindspot for me unfortunately.

 > (https://github.com/flutter/flutter/pull/169854#issuecomment-2957641023) If its priority isn't high, I'll work on this later and create a separate issue and PR for it.

Sounds good. I didn't expect a change of behavior from that optimization so I must have misread it. Makes sense to do it in a separate PR.

**Comment by SalehTZ** [comment]
Thanks Justin, That's an honor to work on Flutter, I'll be contributing more in the future, especially on RTL. So count on me for RTL issues ✌🏻😃

File: packages/flutter/test/material/text_selection_toolbar_test.dart [hunk 12]
```diff
@@ -352,4 +353,111 @@ void main() {
...
+    final List<double> sortedRightEdges = List<double>.from(rightEdges)
+      ..sort((double a, double b) => b.compareTo(a));
+    expect(
+      rightEdges,
+      equals(sortedRightEdges),
+      reason: 'Items should be ordered right-to-left in RTL',
+    );
+  });
+
+  testWidgets('puts children in an overflow menu if they overflow in RTL', (
```
Comment (victorsanni) [inline packages/flutter/test/material/text_selection_toolbar_test.dart:413]: This test passes on `master`, but I'm assuming it is just making sure overflow menu works anyways in RTL (outside of this PR)?

**Review by victorsanni — APPROVED** [review]
Hi @SalehTZ, thanks for the PR, it looks really good. The detailed PR header with the screenshots make it easier to follow and review as well. Great work!

File: packages/flutter/test/material/text_selection_toolbar_test.dart (hunk 12 above)
Comment (SalehTZ) [reply packages/flutter/test/material/text_selection_toolbar_test.dart:413]: It is exactly like a test written before `that checks if they overflow` :

```82		testWidgets('puts children in an overflow menu if they overflow', (WidgetTester tester) async {```

but the difference is within this line:
`423            textDirection: TextDirection.rtl, // this makes the difference.`

**Comment by SalehTZ** [comment]
Thank you guys, you guys are awesome and your words meant so much to me 😍
