### PR TITLE
 [152588] Fix Scrollable being too eager to respond to pointer signals

### LINKED ISSUE #152588: Scroll "back" on web causes browser back action (unless perfectly horizontal)
https://main-api.flutter.dev/flutter/material/CarouselView-class.html

If you navigate to this page from somewhere else and try to scroll the carousel view BACK you have to slide perfectly horizontally. Any deviation and you start the mac "back" action in the browser.

Look at https://dartpad.dev/?run=true&sample_id=material.CarouselView.2&channel=main

Flutter 3.24.0-1.0.pre.214

https://github.com/user-attachments/assets/13cc05ce-5bbb-4302-9c5b-7fa196090491

I thought it was related to https://github.com/flutter/flutter/issues/143276#issuecomment-2251606907 – but I'm being told...not

### PR DESCRIPTION
**Pull request by O-Hannonen**
## This PR
- Fixes #152588

### Root cause
The bug was introduced in PR #145500, which fixed issue #139263 by ensuring that the Web engine knows when a scroll event is not handled by Flutter. This allows the browser to perform default actions like page scrolling or back/forward navigation. Without this, Flutter might "swallow" events it doesn't use, leading to a "dead" feel on the web.

### Why reverting is safe and won't regress Issue #139263
Reverting the manual `respond(true)` calls in Scrollable is safe because `PointerSignalResolver` (the centralized mediator for these events) already has the logic to notify the engine. More specifically, `PointerSignalResolver.resolve` calls `event.respond(allowPlatformDefault: true)` if and only if no widget in the hit-test tree registered interest in the event.

Moving this responsibility back to the `PointerSignalResolver` ensures that:
1. If **_any_** widget handles the event: It registers with the resolver, and `respond(true)` is **_not called_**.
2. If **_no_** widget handles the event: No one registers, and the resolver **_calls_** `respond(true)` at the end of the dispatch cycle.

The current bug exists because `Scrollable` was trying to be too helpful by calling `respond(true)` based only on its local state, which overrides any handling done by other widgets in the hierarchy.

### Testing and verifying

A new regression test was created that highlight how the respond calls should work in nested `Scrollable` elements. 

The "fallback" nature of `PointerSignalResolver` is already 
1. documented in `pointer_signal_resolver.dart`:
```dart
  void resolve(PointerSignalEvent event) {
    if (_firstRegisteredCallback == null) {
      assert(_currentEvent == null);
      // Nothing in the framework/app wants to handle the `event`. Allow the
      // platform to trigger any default native actions.
      event.respond(allowPlatformDefault: true);
      return;
    }
    // ... handles the registered callback ...
  }

```
2. tested in `pointer_signal_resolver_test.dart`:
```dart
  test('Resolving with no entries should notify engine of no-op', () {
    var allowedPlatformDefault = false;
    final tester = PointerSignalTester();
    tester.event = PointerScrollEvent(
      onRespond: ({required bool allowPlatformDefault}) {
        allowedPlatformDefault = allowPlatformDefault;
      },
    );
    tester.resolver.resolve(tester.event);
    expect(
      allowedPlatformDefault,
      isTrue,
      reason: 'Should have called respond with allowPlatformDefault: true',
    );
  });

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/scrollable_test.dart [hunk 1]
```diff
@@ -1785,6 +1786,67 @@ void main() {
     await tester.pumpAndSettle();
     expect(getScrollOffset(tester), 200);
   });
+
+  testWidgets(
+    'Diagonal scroll in nested scrollables: horizontal handles, vertical at edge should NOT call respond(true)',
+    (WidgetTester tester) async {
+      // Regression test for https://github.com/flutter/flutter/issues/152588
+      final verticalController = ScrollController();
```
Comment (Piinks) [inline packages/flutter/test/widgets/scrollable_test.dart:1734]: Adding addTearDown to clean these up should resolve the leaks failure: 
02:24 +4752 ~117 -1: C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/scrollable_test.dart: (tearDownAll) [E]
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/flutter/flutter/blob/main/docs/contributing/testing/Leak-tracking.md
            notDisposed:
              total: 2
              objects:
                ScrollController:
                  test: Diagonal scroll in nested scrollables: horizontal handles, vertical at edge should NOT call respond(true)
                  identityHashCode: 767463196
                ScrollController:
                  test: Diagonal scroll in nested scrollables: horizontal handles, vertical at edge should NOT call respond(true)
                  identityHashCode: 3248425
            
            
  
  package:matcher                                              expect
  package:leak_tracker_testing/src/leak_testing.dart 69:24     LeakTesting.collectedLeaksReporter.<fn>
  package:leak_tracker_flutter_testing/src/testing.dart 74:37  maybeTearDownLeakTrackingForAll
  ===== asynchronous gap ===========================
  dart:async                                                   _CustomZone.registerBinaryCallback
  package:flutter_test/src/test_compat.dart 302:3              _tearDownForTestFile

**Review by Piinks — COMMENTED** [review]
Thank you for this!

**Review by Piinks — DISMISSED** [review]
This LGTM, thank you again!

**Review by AbdeMohlbi — DISMISSED** [review]
LGTM

**Comment by Piinks** [comment]
Hey @O-Hannonen it looks like this ran into an issue with testing, can you rebase with the tip of tree?

**Review by jtmcdole — DISMISSED** [review]
I dont' know what's going on - but "files changed 189" is bad.

File: packages/flutter/test/widgets/scrollable_test.dart [hunk 2]
```diff
@@ -5,9 +5,10 @@
 import 'dart:ui' as ui;
 
 import 'package:flutter/foundation.dart';
+import 'package:flutter/gestures.dart';
+import 'package:flutter/material.dart';
```
Comment (Piinks) [inline packages/flutter/test/widgets/scrollable_test.dart]: We're actively trying to remove dependencies on material from widgets as we are preparing to remove material from the framework. Can you update the test to not depend on material and remove this import?

**Review by Piinks — APPROVED** [review]
LGTM thank you!

**Review by AbdeMohlbi — APPROVED** [review]
