### PR TITLE
[flutter_tools] support iOS and macOS with split-debug-info and tree-shake-icons

### LINKED ISSUE #48726: Enable stripped AOT snapshots via tool feature
Enabling a stripped AOT snapshot with `--strip --dwarf-stack-traces --save-debugging-info=something.so.debug` will reduce the code size, at the cost of requiring a second file to map stack traces.

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Plumbs the split-debug-info flag though iOS and macOS now that we're on assemble. Updates the flag logic so that an empty string is interpreted as asking for unsplit. This simplifies the logic of passing the flag through bash.

Fixes https://github.com/flutter/flutter/issues/48726

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/build_macos.dart [hunk 1]
```diff
@@ -85,8 +85,6 @@ Future<void> buildMacOS({
       'OBJROOT=${globals.fs.path.join(flutterBuildDir.absolute.path, 'Build', 'Intermediates.noindex')}',
       'SYMROOT=${globals.fs.path.join(flutterBuildDir.absolute.path, 'Build', 'Products')}',
       'COMPILER_INDEX_STORE_ENABLE=NO',
-      if (buildInfo.treeShakeIcons)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/build_macos.dart]: @dnfield I don't think this is needed since its otherwise in the generated xcconfig

Comment (dnfield) [reply packages/flutter_tools/lib/src/macos/build_macos.dart]: That sounds right - did you test it locally?

Building flutter gallery with this option should result in a smaller MaterialIcons-Regular.ttf file (something like 13 kb instead of 100+kb).

**Review by dnfield — APPROVED** [review]
LGTM assuming the font subsetting still works locally.

File: packages/flutter_tools/test/general.shard/base/build_test.dart [hunk 2]
```diff
@@ -715,6 +715,39 @@ void main() {
       ]);
     }, overrides: contextOverrides);
 
+    testUsingContext('builds shared library for android-arm without dwarf stack traces due to empty string', () async {
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/base/build_test.dart]: Is this the right test?

Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/base/build_test.dart]: Its checking that `splitDebugInfo: ''` doesn't introduce dwarf-stack-traces

**Review by zanderso — APPROVED** [review]

File: packages/flutter_tools/lib/src/macos/build_macos.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/macos/build_macos.dart]: Now it actually works - the flag name was out of date in the invocations
