### PR TITLE
Set Max Height for ListTile trailing and leading widgets

### LINKED ISSUE #28765: ListTile "leading" parameter stopped working
Before the update, I had a ListView with a set of ListTiles that rendered an image on the left side of each tile with the "leading" parameter and a title on the right using the "title" parameter. Now, the image is stretched across the entire tile, and the title value is not displayed on the screen.

## Steps to Reproduce

Here is my code. The products variable contains a list of maps with the following structure:
"image" : (name of image file in assets folder)
"title": title of item

import 'package:flutter/material.dart';

class ProductListPage extends StatelessWidget{

  final List<Map<String, dynamic>> products;

  ProductListPage (this.products);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) {
        return ListTile(
          leading: Image.asset(products[index]['image']),
          title: Text(products[index]['title']),
          // title: Text('test')
        );
      },
      itemCount: products.length,
    );
  }
}
Attached screen shots show how the program ran before and after the version 1.2 upgrade.

afterupgrade
beforeupgrade

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Updates ListTile to have a maximum height for leading and trailing icons, preventing them from stretching longer than the height of the ListTile widget. Widget height constraints follow the [material spec](https://material.io/design/components/lists.html#anatomy). ~This involves updating a previous test, as the test allowed the CircleAvatar widget to grow to a height larger than allowed by the Material spec. In particular, it's for when ListTile has `dense` set to `true` and subtitle set to `null`~

## Related Issues

Fixes https://github.com/flutter/flutter/issues/28765

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
My implementation is currently failing due to conflicts between my implementation and accessibility requirements.

Accessibility requirement: "Tappable objects should be at least Size(48.0, 48.0)". 
Material spec-following implementation: The leading/trailing widgets are set such that there is an 8 pixel-wide padding on top and bottom of the widget, causing the widget to be 32-40px tall for one-line ListTiles. 

Currently working on what the best step moving forward would be.

cc/ @HansMuller

File: packages/flutter/lib/src/material/list_tile.dart [hunk 1]
```diff
@@ -164,6 +164,12 @@ enum ListTileControlAffinity {
 /// and to ensure that [subtitle] doesn't wrap (if [isThreeLine] is false) or
 /// wraps to two lines (if it is true).
 ///
+/// Leading and trailing widgets will be constrained in height according to
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: The heights of the [leading] and [trailing] widgets are constrained according to ..

File: packages/flutter/lib/src/material/list_tile.dart [hunk 2]
```diff
@@ -199,6 +205,43 @@ enum ListTileControlAffinity {
 /// ```
 /// {@end-tool}
 ///
+/// For accessibility purposes, tappable leading and trailing widgets have to
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: To be accessible, tappable ...

File: packages/flutter/lib/src/material/list_tile.dart [hunk 3]
```diff
@@ -199,6 +205,43 @@ enum ListTileControlAffinity {
...
+/// be at least 48x48px in size. However, to adhere with Material spec,
+/// trailing/leading widgets in one-line ListTiles should visually be at
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: [leading] and [trailing]

File: packages/flutter/lib/src/material/list_tile.dart [hunk 4]
```diff
@@ -199,6 +205,43 @@ enum ListTileControlAffinity {
 /// ```
 /// {@end-tool}
 ///
+/// For accessibility purposes, tappable leading and trailing widgets have to
+/// be at least 48x48px in size. However, to adhere with Material spec,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: I think it would actually be clearer to leave out the "px" unit here and below. All of our dimensions are in logical pixel units and we generally don't include "px".

File: packages/flutter/lib/src/material/list_tile.dart [hunk 5]
```diff
@@ -199,6 +205,43 @@ enum ListTileControlAffinity {
...
+/// trailing/leading widgets in one-line ListTiles should visually be at
+/// most 32px (dense: true) or 40px (dense: false) in height, which may
+/// conflict with the accessibility requirement.
+///
+/// For this reason, ListTile is implemented such that the height of leading
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: We're only referring to one-line ListTiles here, right?

File: packages/flutter/lib/src/material/list_tile.dart [hunk 6]
```diff
@@ -199,6 +205,43 @@ enum ListTileControlAffinity {
...
+///   leading: GestureDetector(
+///     // allows background to be tappable
+///     behavior: HitTestBehavior.translucent,
+///     onTap: () {},
+///     child: Container(
+///       // 48x48 box that is tappable
+///       width: 48,
+///       height: 48,
+///       child: Padding(
+///         // creates an avatar that visually adheres to Material
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: Creates a 32x32 avatar per the Material spec.

File: packages/flutter/lib/src/material/list_tile.dart [hunk 7]
```diff
@@ -935,7 +969,10 @@ class _RenderListTile extends RenderBox {
     final bool isOneLine = !isThreeLine && !hasSubtitle;
 
     final BoxConstraints maxIconHeightConstraint = BoxConstraints(
-      maxHeight: _maxIconHeight,
+      // One-line trailing and leading widget sizing does not follow
+      // Material specifications, but this sizing required to adhere
+      // to accessibility requirements for smallest tappable widget.
+      maxHeight: isDense ? 48.0 : 56.0,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/list_tile.dart]: Is this constraint really only applied for one-line leading/trailing widgets?

**Review by HansMuller — COMMENTED** [review]
This looks good, mostly just some minor wordsmithing. One technical question: are we constraining the max size of leading/trailing icons for 2 or 3 line list tiles?

File: packages/flutter/lib/src/material/list_tile.dart (hunk 5 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/list_tile.dart]: Yes! I'll add that clarification

File: packages/flutter/lib/src/material/list_tile.dart (hunk 7 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/list_tile.dart]: The constraint is applied to all types of ListTile widgets, but only one-line leading/trailing widgets will not include the Material spec padding included in its constraint, whereas the heights of two- and three-line ListTile widgets will be appropriately constrained to include Material spec padding

Comment (shihaohong) [reply packages/flutter/lib/src/material/list_tile.dart]: A concern I may have is that this implementation could be confusing if the documentation isn't properly inspected. I'm wondering if there is some alternative approach that we could take to make the API cleaner

**Comment by shihaohong** [comment]
@HansMuller The 2- and 3-line ListTile are also being constrained. They're being constrained based on the Material spec (height + padding), whereas a workaround has to be made for the 1-line ListTile to pass accessibility, so it is only being constrained by height.

File: packages/flutter/lib/src/material/list_tile.dart (hunk 7 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/list_tile.dart]: I think what you've done in this PR is pretty good given the difficulty of satisfying  material's visual constraints and the accessibility constraints.

**Comment by shihaohong** [comment]
After discussion with @HansMuller, we've decided to stay with this implementation of ListTile after considering other options. We believe this approach provides the user with the most flexibility with how to position and describe `leading` and `trailing` widgets. Otherwise, the recommendation would be for users to create their own widgets to suit their own needs instead of using `ListTile`.

Once @HansMuller approves, I'll merge this PR.

**Review by HansMuller — APPROVED** [review]
LGTM
