### PR TITLE
Fixed for DropdownButton crashing when a style was used that didn't include a fontSize

### LINKED ISSUE #33425: The following ArgumentError was thrown building DropdownButton<String>(dirty, dependencies: flutter: [_LocalizationsScope-[GlobalKey#5a1bc], Directionality, _InheritedTheme], state: flutter: _DropdownButtonState<String>#b0432): flutter: Invalid argument(s)
## Steps to Reproduce

1. I am trying to implement a DropDownButton and facing an issue when i set isDense Property to true. 

Here is the code snippet 

```
TextStyle _statusTextStyle = TextStyle(color: Colors.white);
  String _statusValue = '1';
  bool isDraft = true;

  Widget _statusUpdate() {
    return Theme(
        data: ThemeData(canvasColor: colorNonProfit),
        child: Container(
          width: 100,
          child: DropdownButton<String>(
          underline: Container(),
          style: TextStyle(color: colorTextDark),
          items: [
            DropdownMenuItem(
              value: "1",
              child: Text(
                "draft",
                style: _statusTextStyle,
              ),
            ),
            DropdownMenuItem(
              value: "2",
              child: Text(
                "active",
                style: _statusTextStyle,
              ),
            ),
          ],
          disabledHint: Text('draft'),
          isDense: true,
          onChanged: (value) {
                  setState(() {
                    _statusValue = value;
                  });
                },
          value: _statusValue,
        ),
      ),
    );
  }
```

## Logs

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown building DropdownButton<String>(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#5a1bc], Directionality, _InheritedTheme], state:
flutter: _DropdownButtonState<String>#b0432):
flutter: Invalid argument(s)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      max (dart:math-patch/math_patch.dart:50:18)
flutter: #1      _DropdownButtonState._denseButtonHeight (package:flutter/src/material/dropdown.dart:798:12)
flutter: #2      _DropdownButtonState.build (package:flutter/src/material/dropdown.dart:879:34)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #38     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #39     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #47     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #53     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #54     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #58     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #62     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #70     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #88     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #95     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #105    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #115    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #127    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #129    _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:199:15)
flutter: #130    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
flutter: #131    _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:198:11)
flutter: #132    __RenderSliverPinnedPersistentHeaderForWidgets&_RenderSliverPinnedPersistentHeader&_RenderSliverPersistentHeaderForWidgetsMixin.updateChild (package:flutter/src/widgets/sliver_persistent_header.dart:266:14)
flutter: #133    RenderSliverPersistentHeader.layoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_persistent_header.dart:126:9)
flutter: #134    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
flutter: #135    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
flutter: #136    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
flutter: #137    RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:124:7)
flutter: #138    RenderSliverPinnedPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:294:5)
Reloaded 18 of 758 libraries in 1,229ms.
flutter: #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #140    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
flutter: #141    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
flutter: #142    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
flutter: #143    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #144    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #145    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #146    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #147    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #148    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #149    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #150    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #151    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #152    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #153    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #154    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #155    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #156    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
flutter: #157    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
flutter: #158    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
flutter: #159    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
flutter: #160    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #161    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #162    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #163    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #164    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
flutter: #165    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #166    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #167    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #168    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #169    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #170    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #171    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #172    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #173    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #174    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #175    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #176    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #177    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #178    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #179    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #180    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #181    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #182    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #183    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #184    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #185    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3015:13)
flutter: #186    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #187    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #188    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #189    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #190    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #191    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #192    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #193    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #194    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #195    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #196    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #197    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #198    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #199    RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
flutter: #200    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
flutter: #201    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
flutter: #202    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
flutter: #203    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #204    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #205    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #206    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #207    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #209    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #210    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #211    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-PK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!

```

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

If the `style` parameter to a `DropdownButton` didn't specify a `fontSize` we weren't falling back and using the `fontSize` from the theme's subhead. This PR fixes that and adds a test for it.

## Related Issues

Fixes: #33425

## Tests

I added a test to ensure we don't crash with this configuration.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -795,7 +795,8 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
   // Similarly, we don't reduce the height of the button so much that its icon
   // would be clipped.
   double get _denseButtonHeight {
-    return math.max(_textStyle.fontSize, math.max(widget.iconSize, _kDenseButtonHeight));
+    final double fontSize = _textStyle.fontSize ?? Theme.of(context).textTheme.subhead.fontSize;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/dropdown.dart]: This might be a little clearer as: `... widget.style.fontSize ?? Theme.of(context)...`

**Review by HansMuller — APPROVED** [review]
LGTM
