### PR TITLE
Try to clarify that you need a Material for an IconButton.

### LINKED ISSUE #2369: Poor error message UX on a exception in the widget library
There's a few UX problems with the result of running the code below:

- It's a 620 line log output, which scrolls by too fast to really see
- I can't tell if it's a bug in my code or in the framework (I'm guessing the framework?)
- There's no indication as to how to recover from this occurrence, or what to do next

### Steps to Reproduce
Run:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: "Flutter Demo",
      routes: <String, RouteBuilder>{
        '/': (RouteArguments args) => new FlutterDemo()
      }
    )
  );
}

class FlutterDemo extends StatefulComponent {
  @override
  State createState() => new FlutterDemoState();
}

class FlutterDemoState extends State {
  int counter = 0;

  void incrementCounter() {
    setState(() {
      counter++;
    });
  }

  Widget build(BuildContext context) {

    return new Container(
      decoration: new BoxDecoration(
        backgroundColor: Colors.blue[500]
      ),
      child: new Row(
        children: [
          new IconButton(icon: 'navigation/menu'),
          new Flexible(),
          new IconButton(icon: 'action/search'),
        ]
      )
    );
  }
}
```

On Nexus 6

### Flutter Version
Atom 1.4.1, flutter plugin 0.2.1, running on macos.

### Logs
```
[Android] I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
[Android] I/flutter : Exception caught while building InkResponse
[Android] I/flutter : Missing Material widget.
[Android] I/flutter : InkResponse needs to be placed inside a Material widget. Ownership chain:
[Android] I/flutter : InkResponse ← IconButton ← Row ← DecoratedBox ← Container ← FlutterDemo ← _ModalScopeStatus ← PageStorage-[GlobalKey 113625532] ← Opacity ← Transform ← ⋯
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      debugCheckHasMaterial.<anonymous closure> (packages/flutter/src/material/debug.dart:14)
[Android] I/flutter : #1      debugCheckHasMaterial (packages/flutter/src/material/debug.dart:11)
[Android] I/flutter : #2      _InkResponseState.build (packages/flutter/src/material/ink_well.dart:144)
[Android] I/flutter : #3      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1196)
[Android] I/flutter : #4      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #5      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #6      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #7      ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #8      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #9      Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #10     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #11     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #12     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #13     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #14     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #15     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #16     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #17     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #18     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #19     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #20     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #21     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #22     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #23     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #24     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #25     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #26     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #27     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #28     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #29     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #30     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #31     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #32     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #36     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #37     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #38     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #39     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #40     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #41     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #42     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #43     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #44     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #45     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #46     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #47     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #48     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #49     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #50     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #51     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #52     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #53     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #54     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #55     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #56     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #57     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #58     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #59     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #60     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #61     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #62     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #63     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #64     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #65     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #66     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #67     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #68     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #69     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #70     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #71     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #72     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #73     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #74     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #75     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #76     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #77     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #78     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #79     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #80     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #81     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #82     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #83     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #84     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #85     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #86     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #87     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #88     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #89     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #90     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #91     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #92     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #93     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #94     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #95     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #96     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #97     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #98     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #99     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #100    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #101    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #102    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #103    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #104    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #105    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #106    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #107    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #108    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #109    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #110    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #111    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #112    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #113    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #114    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #115    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #116    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #117    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #118    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #119    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #120    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #121    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #122    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #123    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #124    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #125    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #126    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #127    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #128    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #129    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #130    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #131    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #132    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #133    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #134    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #135    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #136    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #137    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #138    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #139    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #140    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #141    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #142    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #143    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #144    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #145    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #146    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #147    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #148    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #149    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #150    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #151    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #152    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #153    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #154    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #155    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #156    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #157    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #158    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #159    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #160    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #161    OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #162    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #163    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #164    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #165    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #166    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #167    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #168    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #169    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #170    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #171    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #172    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #173    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #174    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #175    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #176    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #177    RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:239)
[Android] I/flutter : #178    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:205)
[Android] I/flutter : #179    BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1070)
[Android] I/flutter : #180    RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:202)
[Android] I/flutter : #181    WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:159)
[Android] I/flutter : #182    runApp (packages/flutter/src/widgets/binding.dart:166)
[Android] I/flutter : #183    main (/Users/lukechurch/GitRepos/caligo/lib/main.dart:4)
[Android] I/flutter : #184    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[Android] I/flutter : #185    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[Android] I/flutter : ------------------------------------------------------------------------
[Android] I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
[Android] I/flutter : Exception caught while building Flexible(flex: 1)
[Android] I/flutter : A build function returned null. Build functions must never return null.
[Android] I/flutter : The offending widget is: Flexible(flex: 1)
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      ComponentElement.performRebuild.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1199)
[Android] I/flutter : #1      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1197)
[Android] I/flutter : #2      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #3      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #4      ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #5      ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1380)
[Android] I/flutter : #6      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #7      MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #8      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #9      Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #10     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #11     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #12     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #13     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #14     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #15     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #16     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #17     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #18     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #19     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #20     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #21     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #22     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #23     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #24     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #25     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #26     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #27     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #28     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #29     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #30     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #31     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #32     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #33     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #34     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #35     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #36     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #37     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #38     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #39     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #40     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #41     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #42     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #43     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #44     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #45     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #46     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #47     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #48     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #49     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #50     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #51     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #52     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #53     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #54     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #55     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #56     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #57     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #58     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #59     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #60     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #61     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #62     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #63     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #64     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #65     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #66     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #67     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #68     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #69     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #70     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #71     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #72     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #73     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #74     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #75     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #76     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #77     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #78     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #79     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #80     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #81     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #82     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #83     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #84     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #85     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #86     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #87     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #88     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #89     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #90     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #91     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #92     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #93     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #94     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #95     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #96     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #97     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #98     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #99     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #100    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #101    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #102    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #103    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #104    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #105    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #106    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #107    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #108    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #109    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #110    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #111    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #112    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #113    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #114    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #115    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #116    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #117    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #118    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #119    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #120    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #121    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #122    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #123    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #124    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #125    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #126    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #127    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #128    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #129    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #130    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #131    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #132    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #133    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #134    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #135    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #136    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #137    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #138    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #139    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #140    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #141    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #142    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #143    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #144    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #145    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #146    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #147    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #148    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #149    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #150    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #151    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #152    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #153    OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #154    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #155    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #156    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #157    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #158    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #159    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #160    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #161    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #162    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #163    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #164    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #165    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #166    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #167    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #168    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #169    RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:239)
[Android] I/flutter : #170    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:205)
[Android] I/flutter : #171    BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1070)
[Android] I/flutter : #172    RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:202)
[Android] I/flutter : #173    WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:159)
[Android] I/flutter : #174    runApp (packages/flutter/src/widgets/binding.dart:166)
[Android] I/flutter : #175    main (/Users/lukechurch/GitRepos/caligo/lib/main.dart:4)
[Android] I/flutter : #176    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[Android] I/flutter : #177    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[Android] I/flutter : ------------------------------------------------------------------------
[Android] I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
[Android] I/flutter : Exception caught while building InkResponse
[Android] I/flutter : Missing Material widget.
[Android] I/flutter : InkResponse needs to be placed inside a Material widget. Ownership chain:
[Android] I/flutter : InkResponse ← IconButton ← Row ← DecoratedBox ← Container ← FlutterDemo ← _ModalScopeStatus ← PageStorage-[GlobalKey 113625532] ← Opacity ← Transform ← ⋯
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      debugCheckHasMaterial.<anonymous closure> (packages/flutter/src/material/debug.dart:14)
[Android] I/flutter : #1      debugCheckHasMaterial (packages/flutter/src/material/debug.dart:11)
[Android] I/flutter : #2      _InkResponseState.build (packages/flutter/src/material/ink_well.dart:144)
[Android] I/flutter : #3      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1196)
[Android] I/flutter : #4      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #5      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #6      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #7      ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #8      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #9      Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #10     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #11     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #12     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #13     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #14     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #15     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #16     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #17     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #18     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #19     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #20     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #21     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #22     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #23     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #24     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #25     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #26     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #27     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #28     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #29     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #30     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #31     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #32     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #36     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #37     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #38     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #39     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #40     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #41     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #42     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #43     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #44     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #45     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #46     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #47     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #48     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #49     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #50     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #51     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #52     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #53     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #54     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #55     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #56     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #57     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #58     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #59     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #60     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #61     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #62     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #63     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #64     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #65     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #66     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #67     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #68     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #69     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #70     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #71     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #72     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #73     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #74     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #75     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #76     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #77     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #78     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #79     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #80     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #81     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #82     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #83     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #84     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #85     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #86     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #87     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #88     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #89     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #90     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #91     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #92     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #93     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #94     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1820)
[Android] I/flutter : #95     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #96     Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #97     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #98     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #99     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #100    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #101    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #102    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #103    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #104    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #105    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #106    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #107    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #108    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #109    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #110    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #111    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #112    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #113    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #114    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #115    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #116    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #117    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #118    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #119    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #120    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #121    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #122    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #123    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #124    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #125    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #126    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #127    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #128    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #129    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #130    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #131    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #132    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #133    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #134    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #135    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #136    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #137    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #138    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #139    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #140    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #141    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #142    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #143    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #144    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #145    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #146    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #147    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #148    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #149    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #150    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #151    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #152    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #153    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #154    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #155    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #156    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #157    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #158    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #159    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #160    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #161    OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1741)
[Android] I/flutter : #162    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #163    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #164    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #165    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #166    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #167    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #168    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #169    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #170    ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1216)
[Android] I/flutter : #171    BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1137)
[Android] I/flutter : #172    ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1183)
[Android] I/flutter : #173    StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1284)
[Android] I/flutter : #174    ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1178)
[Android] I/flutter : #175    Element._inflateWidget (packages/flutter/src/widgets/framework.dart:831)
[Android] I/flutter : #176    Element.updateChild (packages/flutter/src/widgets/framework.dart:709)
[Android] I/flutter : #177    RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:239)
[Android] I/flutter : #178    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:205)
[Android] I/flutter : #179    BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1070)
[Android] I/flutter : #180    RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:202)
[Android] I/flutter : #181    WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:159)
[Android] I/flutter : #182    runApp (packages/flutter/src/widgets/binding.dart:166)
[Android] I/flutter : #183    main (/Users/lukechurch/GitRepos/caligo/lib/main.dart:4)
[Android] I/flutter : #184    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[Android] I/flutter : #185    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[Android] I/flutter : ------------------------------------------------------------------------
[Android] I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
[Android] I/flutter : The following exception was raised during performLayout():
[Android] I/flutter : BoxConstraints has a negative minimum width.
[Android] I/flutter : BoxConstraints(w=-411.4, 0.0<=h<=Infinity; NOT NORMALIZED)
[Android] I/flutter : The following RenderObject was being processed when the exception was fired:
[Android] I/flutter : RenderFlex NEEDS-LAYOUT OVERFLOWING
[Android] I/flutter : This RenderObject had the following owner:
[Android] I/flutter : Row ← DecoratedBox ← Container ← FlutterDemo ← _ModalScopeStatus ← PageStorage-[GlobalKey 113625532] ← Opacity ← Transform ← _MaterialPageTransition ← IgnorePointer ← ⋯
[Android] I/flutter : This RenderObject had the following descendants (showing up to depth 5):
[Android] I/flutter :   RenderErrorBox
[Android] I/flutter :   RenderErrorBox
[Android] I/flutter :   RenderErrorBox
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      BoxConstraints.debugAssertIsNormalized.<anonymous closure> (packages/flutter/src/rendering/box.dart:298)
[Android] I/flutter : #1      BoxConstraints.debugAssertIsNormalized (packages/flutter/src/rendering/box.dart:294)
[Android] I/flutter : #2      BoxConstraints.constrainHeight (packages/flutter/src/rendering/box.dart:175)
[Android] I/flutter : #3      RenderErrorBox.getMaxIntrinsicHeight (packages/flutter/src/rendering/error.dart:28)
[Android] I/flutter : #4      RenderFlex._getIntrinsicSize (packages/flutter/src/rendering/flex.dart:255)
[Android] I/flutter : #5      RenderFlex.getMinIntrinsicHeight (packages/flutter/src/rendering/flex.dart:296)
[Android] I/flutter : #6      RenderBox.debugAssertDoesMeetConstraints (packages/flutter/src/rendering/box.dart:650)
[Android] I/flutter : #7      RenderBox.size=.<anonymous closure> (packages/flutter/src/rendering/box.dart:502)
[Android] I/flutter : #8      RenderBox.size= (packages/flutter/src/rendering/box.dart:502)
[Android] I/flutter : #9      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:447)
[Android] I/flutter : #10     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #11     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #12     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #13     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #14     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #15     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #16     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #17     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #18     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #19     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #20     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #21     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #22     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #23     RenderStackBase.performLayout (packages/flutter/src/rendering/stack.dart:310)
[Android] I/flutter : #24     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #25     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
[Android] I/flutter : #26     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
[Android] I/flutter : #27     RenderView.performLayout (packages/flutter/src/rendering/view.dart:96)
[Android] I/flutter : #28     RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:944)
[Android] I/flutter : #29     RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:922)
[Android] I/flutter : #30     BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
[Android] I/flutter : #31     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:95)
[Android] I/flutter : #32     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:160)
[Android] I/flutter : #33     runApp (packages/flutter/src/widgets/binding.dart:166)
[Android] I/flutter : #34     main (/Users/lukechurch/GitRepos/caligo/lib/main.dart:4)
[Android] I/flutter : #35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[Android] I/flutter : #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[Android] I/flutter : ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/2369

### CODE REVIEW

File: packages/flutter/lib/src/material/debug.dart [hunk 1]
```diff
@@ -12,8 +12,15 @@ bool debugCheckHasMaterial(BuildContext context) {
     if (context.widget is! Material && context.ancestorWidgetOfExactType(Material) == null) {
       Element element = context;
       throw new WidgetError(
-        'Missing Material widget.',
-        '${context.widget} needs to be placed inside a Material widget. Ownership chain:\n${element.debugGetOwnershipChain(10)}'
+        'No Material widget found.\n'
+        '${context.widget} widgets require a Material widget ancestor.\n'
+        'In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter\'s material library, '
+        'that material is represented by the Material widget. It is the Material widget that render ink splashes, for instance. '
```
Comment (abarth) [inline packages/flutter/lib/src/material/debug.dart]: s/render/renders/

**Comment by abarth** [comment]
LGTM
