### PR TITLE
Reland "Fix `Chip.shape`'s side is not used when provided in Material 3"

### LINKED ISSUE #132922: Chip border side color not working in Material3
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. set useMaterial3 true in MaterialAPP.
2. run app.

### Expected results

The chip border color will show different colors when the developer changes the border color.

### Actual results

Nothing to change when using material 3.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        chipTheme: const ChipThemeData(
          // shape: RoundedRectangleBorder(
          //   /// not work with material 3
          //   side: BorderSide(color: Colors.red),
          //   borderRadius: BorderRadius.all(Radius.circular(12)),
          // ),
        ),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body:  const Center(
        child: Chip(
          shape:RoundedRectangleBorder(
            /// not work with material 3
            side: BorderSide(color: Colors.red),
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
          label: Text('Chip'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

截圖 2023-08-21 上午9 22 10

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:63331/kya-Zvn4LRw=/ws
Syncing files to device sdk gphone64 arm64...
I/ample.untitled1( 7023): Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
W/Parcel  ( 7023): Expecting binder but got null!
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale zh-Hant-TW)
    • Flutter version 3.13.0 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (5 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chien/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/chien/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [Chip border side color not working in Material3](https://github.com/flutter/flutter/issues/132922)
Relands https://github.com/flutter/flutter/pull/132941 with an updated fix and a regression test.

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Chips'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            const RawChip(
              shape: RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: BorderSide(color: Colors.red),
              label: Text('RawChip'),
            ),
            const Chip(
              shape: RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: BorderSide(color: Colors.red),
              label: Text('Chip'),
            ),
            ActionChip(
              shape: const RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: const BorderSide(color: Colors.red),
              label: const Text('ActionChip'),
              onPressed: () {},
            ),
            FilterChip(
              shape: const RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: const BorderSide(color: Colors.red),
              label: const Text('FilterChip'),
              onSelected: (value) {},
            ),
            ChoiceChip(
              shape: const RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: const BorderSide(color: Colors.red),
              label: const Text('ChoiceChip'),
              selected: false,
              onSelected: (value) {},
            ),
            InputChip(
              shape: const RoundedRectangleBorder(
                side: BorderSide(color: Colors.amber),
              ),
              side: const BorderSide(color: Colors.red),
              label: const Text('InputChip'),
              onSelected: (value) {},
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

 

 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/chip.dart [hunk 1]
```diff
@@ -992,13 +992,21 @@ class _RawChipState extends State<RawChip> with MaterialStateMixin, TickerProvid
...
+      // TODO(tahatesser): Remove this fallback when Material 2 is deprecated.
       ?? const StadiumBorder();
-    return resolvedShape.copyWith(side: resolvedSide);
+    // If the side is provided, shape uses the provided side.
+    if (resolvedSide != null) {
+      return resolvedShape.copyWith(side: resolvedSide);
+    }
+    // If the side is not provided and the shape's side is not [BorderSide.none],
+    // then the shape's side is used. Otherwise, the default side is used.
+    return resolvedShape.side != BorderSide.none
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/chip.dart:1007]: So if I want to specify a shape with no border, then I need to specify both the `shape` and the `side` (as BorderSide.none) because specifying a shape with `BorderSide.none` will cause us to use the default side. I guess that's OK, since the OutlinedBorder classes use `BorderSide.none` by default. It's a little confusing.  A separate PR that clarified this in the API doc might help.

**Comment by HansMuller** [comment]
@TahaTesser 

This PR is failing the SuperEditor presubmit test. On the face of it, it doesn't seem related to the change here. On the other hand the failure is consistent.

```
 | 00:34 +1234: C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/supereditor_scrolling_test.dart: SuperEditor scrolling within an ancestor Scrollable respects horizontal scrolling inside a TabBar (on iOS)
 | 00:34 +1234: C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/text_entry/links_test.dart: SuperEditor link editing > does not expand the link when inserting before the link (on iOS)
 | ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
 | The following TestFailure was thrown running a test:
 | Expected: given Document has equivalent content to the given markdown
 |   Actual: <Instance of 'MutableDocument'>
 |    Which: is different.
 |           Expected: Go to [www ...
 |             Actual: [www.googl ...
 |                     ^
 |            Differ at offset 0
 |
 | When the exception was thrown, this was the stack:
 | #4      main.<anonymous closure>.<anonymous closure> (file:///C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/text_entry/links_test.dart:154:7)
 | <asynchronous suspension>
 | #5      testWidgetsOnIos.<anonymous closure> (file:///C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/test_tools.dart:424:7)
 | <asynchronous suspension>
 | #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
 | <asynchronous suspension>
 | #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1012:5)
 | <asynchronous suspension>
 | <asynchronous suspension>
 | (elided one frame from package:stack_trace)
 |
 | This was caught by the test expectation on the following line:
 |   file:///C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/text_entry/links_test.dart line 154
 | The test description was:
 |   does not expand the link when inserting before the link (on iOS)
 | ════════════════════════════════════════════════════════════════════════════════════════════════════
 | 00:34 +1234 -1: C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/supereditor_scrolling_test.dart: SuperEditor scrolling within an ancestor Scrollable respects horizontal scrolling inside a TabBar (on iOS)
 | 00:34 +1234 -1: C:/b/s/w/ir/x/t/flutter_customer_testing.super_editor.70898aa8/tests/super_editor/test/super_editor/text_entry/links_test.dart: SuperEditor link editing > does not expand the link when inserting before the link (on iOS) [E]
 |   Test failed. See exception logs above.
 |   The test description was: does not expand the link when inserting before the link (on iOS)
```

**Comment by TahaTesser** [comment]
> @TahaTesser
> 
> This PR is failing the SuperEditor presubmit test. On the face of it, it doesn't seem related to the change here.

Thanks! I will try running this with `flutter/test` repo locally to confirm.

**Comment by TahaTesser** [comment]
This indeed looks like an outside issue. I see this failure in other PRs. 
For instance https://github.com/flutter/flutter/pull/133965/checks?check_run_id=16464555245

**Comment by TahaTesser** [comment]
blocked by https://github.com/flutter/flutter/issues/134043

**Comment by HansMuller** [comment]
Hopefully to be unblocked by https://github.com/flutter/tests/pull/294

**Comment by HansMuller** [comment]
The current list of 5000 failures appear to be unrelated to this PR. Checking with the Flutter rollers ...
