### PR TITLE
Fix issue with account drawer header arrow rotating when setState is called

### LINKED ISSUE #25801: UserAccountsDrawerHeader initial direction of details arrow is inconsistent
The `UserAccountsDrawerHeader` details arrow initial direction is inconsistent. If I tap the hamburger menu to open a drawer with the header, the arrow appears pointing down. But if I drag to open the drawer, the arrow points up.

I think the problem was introduced in https://github.com/flutter/flutter/pull/24023. You can also observe the arrow rotating direction as the drawer drags open and close (might want to slow down animations to really see this). 

```
[✓] Flutter (Channel google3, vnull, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision 7a88fbc5fd (6 days ago), 2018-12-20T00:00:00.000
    • Engine revision dbdb5e6f8c
    • Dart version f9ebf21297

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

```

### PR DESCRIPTION
**Pull request by rami-a**
## Description

The UserAccountsDrawerHeader had a bug with the arrow rotating whenever setState was called on its parent. This change makes sure that we check that the state actually changed before allowing the animation to trigger.

## Related Issues

Fixes #25801 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 1]
```diff
@@ -32,11 +60,17 @@ Future<void> pumpTestWidget(
...
           child: Center(
             child: UserAccountsDrawerHeader(
-              onDetailsPressed: withOnDetailsPressedHandler ? () { } : null,
-              currentAccountPicture: const ExcludeSemantics(
-                child: CircleAvatar(
-                  key: avatarA,
-                  child: Text('A'),
+              onDetailsPressed: widget.withOnDetailsPressedHandler ? () { } : null,
+              currentAccountPicture: ExcludeSemantics(
+                child: GestureDetector(
```
Comment (johnsonmh) [inline packages/flutter/test/material/user_accounts_drawer_header_test.dart]: Since all you're trying to do is have `setState` called, I think it would be more clear to wrap your test widget in a [StatefulBuilder](https://docs.flutter.io/flutter/widgets/StatefulBuilder-class.html), store the setState method and then call it directly from your test.

See [this example](https://github.com/flutter/flutter/blob/0fb84e96c79df2fe7efeaeb06fbd1c2b53f4a84b/packages/flutter/test/material/will_pop_test.dart#L277), which I think is similar enough to what you want to do.

This will also make it so that you don't have to refactor `TestWidget` into a `StatefulWidget`.

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 2]
```diff
@@ -139,6 +173,28 @@ void main() {
...
+    // Icon is right side up.
+    expect(transformWidget.transform.getRotation()[0], 1.0);
+    expect(transformWidget.transform.getRotation()[4], 1.0);
+
+    await tester.tap(find.byKey(gestureKey));
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 10));
+    expect(tester.hasRunningAnimations, isFalse);
+
+    await tester.pumpAndSettle();
```
Comment (johnsonmh) [inline packages/flutter/test/material/user_accounts_drawer_header_test.dart]: then this call here would be to the `StateSetter`.

**Review by johnsonmh — COMMENTED** [review]
Nice fix!

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 3]
```diff
@@ -139,6 +173,28 @@ void main() {
...
+  testWidgets('UserAccountsDrawerHeader icon does not rotate for setState', (WidgetTester tester) async {
+    await pumpTestWidget(tester);
+    Transform transformWidget = tester.firstWidget(find.byType(Transform));
+
+    // Icon is right side up.
+    expect(transformWidget.transform.getRotation()[0], 1.0);
+    expect(transformWidget.transform.getRotation()[4], 1.0);
+
+    await tester.tap(find.byKey(gestureKey));
+    await tester.pump();
```
[the remark this answers is not in the document]
Comment (rami-a) [reply packages/flutter/test/material/user_accounts_drawer_header_test.dart]: done

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 4]
```diff
@@ -139,6 +173,28 @@ void main() {
...
+    await tester.pump(const Duration(milliseconds: 10));
+    expect(tester.hasRunningAnimations, isFalse);
+
+    await tester.pumpAndSettle();
+    await tester.pump();
```
[the remark this answers is not in the document]
Comment (rami-a) [reply packages/flutter/test/material/user_accounts_drawer_header_test.dart]: done

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 5]
```diff
@@ -139,6 +173,28 @@ void main() {
     expect(transformWidget.transform.getRotation()[4], 1.0);
   });
 
+  testWidgets('UserAccountsDrawerHeader icon does not rotate for setState', (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (rami-a) [reply packages/flutter/test/material/user_accounts_drawer_header_test.dart]: done

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/test/material/user_accounts_drawer_header_test.dart]: done

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart (hunk 2 above)
Comment (rami-a) [reply packages/flutter/test/material/user_accounts_drawer_header_test.dart]: done

**Review by johnsonmh — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM
