### PR TITLE
[web] Fix onTextScaleFactorChanged not getting called.

### LINKED ISSUE #178238: initial textScaleFactor on app first run is wrong
### Steps to reproduce

1. Set your Chrome > settings > appearance > font size to Large.
2. `flutter create test_web_font_scaling --platforms=web`
3. Copy example: https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeTextScaleFactor.html
4. Fix late init error in example.
5. `flutter run --release`
6. Copy the URL in your chrome a few times in a new tab until the "Current scale factor" is not updated.

### Expected results

Should show "Current scale factor: 1.25" 

### Actual results

Shows "Current scale factor: 1" 

### Code sample

<details open><summary>Reproducible sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(const MaterialApp(home: TextScaleFactorReactor()));
}

class TextScaleFactorReactor extends StatefulWidget {
  const TextScaleFactorReactor({super.key});

  @override
  State<TextScaleFactorReactor> createState() => _TextScaleFactorReactorState();
}

class _TextScaleFactorReactorState extends State<TextScaleFactorReactor>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  double _lastTextScaleFactor =
      WidgetsBinding.instance.platformDispatcher.textScaleFactor;

  @override
  void didChangeTextScaleFactor() {
    setState(() {
      _lastTextScaleFactor =
          WidgetsBinding.instance.platformDispatcher.textScaleFactor;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Text('Current scale factor: $_lastTextScaleFactor');
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots</summary>
1.
Update font size to Large:
Image

2.
Open new tab in normal chrome until the text scale is not updated:
Image

3.
Press refresh:
Image
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.35.7, on Ubuntu 25.10 6.17.0-6-generic, locale en_US.UTF-8) [42ms]
    • Flutter version 3.35.7 on channel stable at /A/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adc9010625 (3 weeks ago), 2025-10-21 14:16:03 -0400
    • Engine revision 035316565a
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, no-enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-lldb-debugging

[✓] Chrome - develop for the web [13ms]
    • Chrome at google-chrome

[✓] Connected device (3 available) [212ms]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 142.0.7444.134

[✓] Network resources [334ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #178271: [web] `onTextScaleFactorChanged` not firing?
_(Internal issue: b/457959782)_

### Steps to reproduce

I'd expect this app to update the text scale factor as I change Font settings in Chrome:

* Run the provided `main.dart` in Chrome
* In a separate tab, go to "Customize fonts" in the Chrome settings, and change the "Font size" slider (by default it should be at 16), make it larger. The larger, the more apparent the issue.
  * (Observe that this immediately scale any non-flutter website)

### Expected results

* The demo app I posted, should update the displayed value of the text scale factor, and its font should adapt to the new size

### Actual results

* The text scale factor remains fixed at whatever was when the app first started.

(Note that reloading updates the value, so the value is computed correctly, it seems to just be the `onTextScaleFactorChanged` callback not firing)

### Code sample

<details open><summary>main.dart</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _textScaleFactor = PlatformDispatcher.instance.textScaleFactor;

  @override
  void initState() {
    super.initState();
    // This is not firing as browser settings are updated!
    PlatformDispatcher.instance.onTextScaleFactorChanged = (() {
      setState(() {
        _textScaleFactor = PlatformDispatcher.instance.textScaleFactor;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: .center,
          children: [
            const Text('The current textScaleFactor is:'),
            Text(
              '$_textScaleFactor',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

n/a

</details>

### Logs

<details open><summary>Logs</summary>

n/a

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[!] Flutter (Channel master, 3.38.0-1.0.pre-475, on Debian GNU/Linux rodete 6.16.9-1rodete1-amd64, locale en_US.UTF-8) [792ms]
    • Flutter version 3.38.0-1.0.pre-475 on channel master at /work/flutter/flutter
    ! Upstream repository git@github.com:ditman/flutter-flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:ditman/flutter-flutter.git to dismiss this error.
    • Framework revision f892a5a3cc (4 hours ago), 2025-11-10 14:35:58 -0500
    • Engine revision f892a5a3cc
    • Dart version 3.11.0 (build 3.11.0-114.0.dev)
    • DevTools version 2.52.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets,
      omit-legacy-version-file, enable-lldb-debugging
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

...

[✓] Connected device (2 available) [136ms]
    • Chrome (web)    • chrome • web-javascript • Google Chrome 142.0.7444.134
```

</details>

### LINKED ISSUE #178856: [web] Changing text size in runtime causes abnormal `lineHeightScaleFactorOverride` values.
### Steps to reproduce

1. Switch to `master`
2. Run the provided example
3. Change the browser's `Font size` setting while the app is running
4. Observe the abnormal `lineHeightScaleFactorOverride` value

### Expected results

The `lineHeightScaleFactorOverride` value doesn't have to change when the user changes the font size.

### Actual results

The `lineHeightScaleFactorOverride` value changes to abnormal when the user changes the font size.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Screen(),
    );
  }
}

class Screen extends StatefulWidget {
  const Screen({super.key});

  @override
  State<Screen> createState() => _ScreenState();
}

class _ScreenState extends State<Screen> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            spacing: 10,
            children: [
              Builder(
                builder: (context) {
                  print(
                    'lineHeightScaleFactorOverride: ${MediaQuery.maybeLineHeightScaleFactorOverrideOf(context)}',
                  );
                  final scale = MediaQuery.textScalerOf(context).scale(1);

                  return Text(
                    'Scale ${scale.toStringAsFixed(3)}',
                    style: TextStyle(fontSize: 30),
                    textAlign: TextAlign.center,
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/61beea31-06b4-4927-8974-b214754015fc

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.39.0-1.0.pre-205, on macOS 15.6.1 24G90 darwin-arm64, locale en-US) [210ms]
    ! Flutter version 3.39.0-1.0.pre-205 on channel [user-branch] at /Users/ksokolovskyi/development/flutter_master
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 3d01bf9a53 (18 hours ago), 2025-11-19 17:01:25 +0100
    • Engine revision de4be4f389
    • Dart version 3.11.0 (build 3.11.0-150.0.dev)
    • DevTools version 2.52.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [993ms]
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [754ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [5.9s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.6.1 24G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 142.0.7444.176

[✓] Network resources [305ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/178856
Fixes https://github.com/flutter/flutter/issues/178271
Fixes https://github.com/flutter/flutter/issues/178238

### Description

- Fixes an issue in `lineHeightScaleFactorOverride` calculation, causing it to have abnormal values.
- Integrates text scale factor update into recently added `_addTypographySettingsObserver`. The `ResizeObserver` on the typography probe element is getting notified each time the font size changes, because it leads to the element's size change.
- Removes `DomMutationObserver` previously used for font size observations.
- Adds/Updates tests to verify the fixes.

| BEFORE | AFTER |
| - | - |
| <video src="https://github.com/user-attachments/assets/f62fb3c6-63e1-447f-b4ef-8f22ad944a0a"/> | <video src="https://github.com/user-attachments/assets/c220dd30-89d9-4f76-a43f-b908a940fafb"/> |

### Demo

https://flutter-text-scale-factor.web.app

<details closed><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Screen(),
    );
  }
}

class Screen extends StatefulWidget {
  const Screen({super.key});

  @override
  State<Screen> createState() => _ScreenState();
}

class _ScreenState extends State<Screen> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            spacing: 10,
            children: [
              Builder(
                builder: (context) {
                  print(
                    'lineHeightScaleFactorOverride: ${MediaQuery.maybeLineHeightScaleFactorOverrideOf(context)}',
                  );
                  final scale = MediaQuery.textScalerOf(context).scale(1);

                  return Text(
                    'Scale ${scale.toStringAsFixed(3)}',
                    style: TextStyle(
                      fontSize: 30,
                      backgroundColor: Colors.grey.shade200,
                    ),
                    textAlign: TextAlign.center,
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart [hunk 1]
```diff
@@ -1051,6 +1003,16 @@ class EnginePlatformDispatcher extends ui.PlatformDispatcher {
   DomResizeObserver? _typographySettingsObserver;
   DomElement? _typographyMeasurementElement;
 
+  /// Updates [textScaleFactor] and returns true if [textScaleFactor] changed.
+  /// If not then returns false.
+  bool _updateTextScaleFactor(double value) {
+    if (configuration.lineHeightScaleFactorOverride != value) {
+      configuration = configuration.apply(textScaleFactor: value);
+      return true;
+    }
```
[the remark this answers is not in the document]
Comment (ksokolovskyi) [reply engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart]: Oops, copy-paste error from my side. Thanks, Gemini!

File: engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart [hunk 2]
```diff
@@ -1171,12 +1138,22 @@ class EnginePlatformDispatcher extends ui.PlatformDispatcher {
...
 
-      if (computedLineHeightScaleFactorChanged ||
+      final bool metricsChanged =
+          computedLineHeightScaleFactorChanged ||
           computedLetterSpacingChanged ||
           computedWordSpacingChanged ||
-          computedParagraphSpacingChanged) {
+          computedParagraphSpacingChanged;
+
+      if (computedTextScaleFactorChanged || metricsChanged) {
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart]: nit: maybe we can reduce nesting here and return early if nothing changed.

```dart
if (!computedTextScaleFactorChanged && !metricsChanged) {
	return;
}

invokeOnPlatformConfigurationChanged();

if (computedTextScaleFactorChanged) {
  invokeOnTextScaleFactorChanged();
}

if (metricsChanged) {
  invokeOnMetricsChanged();
}
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart [hunk 3]
```diff
@@ -1126,14 +1089,16 @@ class EnginePlatformDispatcher extends ui.PlatformDispatcher {
...
         _typographyMeasurementElement!,
         'line-height',
       )?.toDouble();
       final double? fontSize = parseFontSize(_typographyMeasurementElement!)?.toDouble();
-      final double? computedLineHeightScaleFactor = fontSize != null && lineHeight != null
+      final double computedLineHeightScaleFactor =
+          fontSize != null && lineHeight != null && lineHeight != spacingDefault
           ? lineHeight / fontSize
-          : null;
+          : defaultLineHeightFactor;
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher.dart]: can this remain `null`?

File: engine/src/flutter/lib/web_ui/test/engine/platform_dispatcher/platform_dispatcher_test.dart [hunk 4]
```diff
@@ -289,18 +298,18 @@ void testMain() {
       };
 
       root.style.fontSize = '20px';
-      await Future<void>.delayed(Duration.zero);
+      await waitForResizeObserver();
       expect(root.style.fontSize, '20px');
       expect(isCalled, isTrue);
-      expect(ui.PlatformDispatcher.instance.textScaleFactor, findBrowserTextScaleFactor());
+      expect(ui.PlatformDispatcher.instance.textScaleFactor, 1.25);
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/test/engine/platform_dispatcher/platform_dispatcher_test.dart]: I think it would be useful to add a comment regarding how this value was calculated, `fontSize/ rootFontSize`.

**Review by Renzo-Olivares — COMMENTED** [review]
@ksokolovskyi thank you for the fixes and clean up! I left a few comments but mostly looks good to me.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM, modulo any feedback from @mdebbar.  Thank you for the contribution!

**Review by mdebbar — APPROVED** [review]
Looks great, thank you for the fixes!
