### PR TITLE
Hide autocomplete menu on select.

### LINKED ISSUE #99749: Autocomplete does not dismiss overlay on selection
The bug happens when you use autocomplete, and the user fills in the same value as  what is recommended and the user clicks on the recommended value, if it is the same as the filled value, it will not dismiss the overlay.

## Steps to Reproduce

This bug is on any Autocomplete widget
Even on the Api.flutter.dev
1. Go to https://api.flutter.dev/flutter/material/Autocomplete-class.html
2. Run the first example.
3. in the input field type in 'aardvark'
4. click on the recommended answer that is the same

**Expected results:** 
The expected result is the overlay to dismiss.

**Actual results:** 
Overlay stays, and nothing happens, the material splash happens, but it does not close the overlay.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
- fixes #99749

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 1]
```diff
@@ -389,12 +396,27 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+        _floatingOptionsUpdateScheduled = true;
+        SchedulerBinding.instance.addPostFrameCallback((Duration timeStamp) {
+          _floatingOptionsUpdateScheduled = false;
+          _updateOverlay();
+        });
+      }
+      return;
+    }
+
+    _floatingOptions?.remove();
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:417]: Good call pulling this out of the conditionals.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 2]
```diff
@@ -389,12 +396,27 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
 
+  void _updateActions() {
+    _setActionsEnabled(_focusNode.hasFocus && _selection == null && _options.isNotEmpty);
+  }
+
+  bool _floatingOptionsUpdateScheduled = false;
   // Hide or show the options overlay, if needed.
   void _updateOverlay() {
-    _setActionsEnabled(_focusNode.hasFocus && _selection == null && _options.isNotEmpty);
+    if (SchedulerBinding.instance.schedulerPhase == SchedulerPhase.persistentCallbacks) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:406]: So the problem was that _updateOverlay was called on a tap callback, in the persistentCallbacks phase, and so the OverlayEntry was updated for the previous frame?

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:406]: No tap callbacks should never be called in persistent callbacks.
The problem was if the text isn't changed by the tap, it's not going to call `_updateOverlay` so that `shouldShowOptions` gets re-evaluated. 
This is just a small change to make sure the caller of `_updateOverlay` doesn't have to know whether it's safe to do an overlay update right away or it has to schedule an update.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:406]: Got it, sounds good.
