### PR TITLE
[web] - Fix broken `TextField` in semantics mode when it's a sibling of `Navigator`

### LINKED ISSUE #129324: [Web] Unable to type in TextField when ensureSemantics is enabled for accessibility
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run this sample code below you will not be able to type in the text field.  Comment out the 

`SemanticsBinding.instance.ensureSemantics();`

And you will be able to type in the text field.

### Expected results

Be able to type in TextField

### Actual results

Cannot type in TextField

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// Flutter code sample for [EditableText.onChanged].

void main() {
  runApp(const OnChangedExampleApp());
  SemanticsBinding.instance.ensureSemantics();
  }

class OnChangedExampleApp extends StatelessWidget {
  const OnChangedExampleApp({super.key});


  static Route<dynamic> onGenerateRoutes() {
    return MaterialPageRoute(
          builder: (_) => const Center()
        );
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: OnChangedExample(),
    );
  }
}

class OnChangedExample extends StatefulWidget {
  const OnChangedExample({super.key});

  @override
  State<OnChangedExample> createState() => _OnChangedExampleState();
}

class _OnChangedExampleState extends State<OnChangedExample> {
  final TextEditingController _controller = TextEditingController();

  final _navigator = GlobalKey<NavigatorState>();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
          mainAxisSize: MainAxisSize.max,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextField(
          onTap: (){
            print('Tap me');
          },
          autofocus: false,
        ),
            Expanded(
              child: Stack(
                children: [
                  Positioned.fill(
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              Expanded(
                                child: 
                                Navigator(
                                  key: _navigator,
                                  initialRoute: '/',
                                  onGenerateRoute: (settings) =>
                                      OnChangedExampleApp.onGenerateRoutes(),
                                )
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    ! Flutter version 3.10.3 on channel unknown at /Users/john/tools/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f92f44110e (3 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/john/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/john/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chromium.app/Contents/MacOS/Chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Chromium 115.0.5789.0

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by htoor3**
When a `TextField` is rendered before a `Navigator`, it breaks in semantics mode.  This is because the framework generates the incorrect semantics tree (excludes the TextField) and when that tree gets sent to the engine, we don't get the signal to create the corresponding `<input>` element.

This happens for a few reasons:
* `ModalBarrier` uses `BlockSemantics` to drop the semantics of routes beneath the current route in `Navigator`
* `ModalBarrier` mistakenly recognizes the widget outside of the `Navigator` to be its sibling
*  So we end up dropping the semantics node of the `TextField` rendered before it. 

The fix is to let `Navigator` generate a semantics node so that `ModalBarrier` doesn't mistakenly think widgets outside of `Navigator` are its siblings.  

`Navigator` doesn't currently do this, which causes all the nodes generated from its widget subtree to be directly attached to the parent semantics node above `Navigator` - since this is also the parent of `TextField`, it considers them siblings. 

Fixes https://github.com/flutter/flutter/issues/129324

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -5542,10 +5542,14 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
                 includeSemantics: false,
                 child: UnmanagedRestorationScope(
                   bucket: bucket,
-                  child: Overlay(
-                    key: _overlayKey,
-                    clipBehavior: widget.clipBehavior,
-                    initialEntries: overlay == null ?  _allRouteOverlayEntries.toList(growable: false) : const <OverlayEntry>[],
+                  child: Semantics(
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart:5545]: Can you add a comment to explain why this is needed?

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
(triage): @htoor3 do you still have plans to submit this? Looks like its breaking some tests on CI.

**Comment by htoor3** [comment]
> (triage): @htoor3 do you still have plans to submit this? Looks like its breaking some tests on CI.

yes, still have plans to submit this.  Need to update a quite a few semantic tests since we're adding the `Semantic` node to `Navigator`. Will get to this today!

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 1 above)
Comment (htoor3) [reply packages/flutter/lib/src/widgets/navigator.dart:5574]: This has been added, let me know if the comment works.  

There are also a lot of tests (100+) this breaks because this introduces a slight change to the semantics tree.  I don't think there's a way to automatically update the snapshot of the tree across all of them, so I'm working my way through updating these tests manually, which is taking quite a while.

**Comment by htoor3** [comment]
@chunhtai re-requesting a review on this - I've updated semantic tree diff tests.  Let me know if this is good to land!

**Comment by htoor3** [comment]
@goderbauer is there someone on the framework side that can give this a +1 since @chunhtai is out? @chunhtai had approved this a few weeks back, but I just wanted a reapproval due to the gap. The only thing updated since his approval was the updated semantics tree tests.

File: packages/flutter/test/cupertino/dialog_test.dart [hunk 2]
```diff
@@ -201,40 +201,44 @@ void main() {
...
+                                  ],
                                 ),
                               ],
                             ),
                           ],
                         ),
-                      ],
-                    ),
+                      ]
+                    )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/cupertino/dialog_test.dart:241]: nit: consider adding trailing commas

File: packages/flutter/test/material/app_bar_test.dart [hunk 3]
```diff
@@ -2369,42 +2369,46 @@ void main() {
...
-                          TestSemantics(
-                            label: 'Bottom',
-                            textDirection: TextDirection.ltr,
                           ),
                         ],
                       ),
-                    ],
-                  ),
+                    ]
+                  )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/app_bar_test.dart:2411]: nit: should add trailing commas.

File: packages/flutter/test/material/app_bar_test.dart [hunk 4]
```diff
@@ -2456,47 +2460,51 @@ void main() {
...
-                                textDirection: TextDirection.rtl,
                               ),
                             ],
                           ),
                         ],
                       ),
-                    ],
-                  ),
+                    ]
+                  )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/app_bar_test.dart:2507]: nit: should add trailing commas

File: packages/flutter/test/semantics/traversal_order_test.dart [hunk 5]
```diff
@@ -39,57 +39,59 @@ void main() {
...
+                        textDirection: TextDirection.ltr,
+                      ),
+                      TestSemantics(
+                        id: 13,
+                        label: '2 - 2',
+                        textDirection: TextDirection.ltr,
+                      ),
+                    ],
+                  ),
+                ])
```
Comment (Renzo-Olivares) [inline packages/flutter/test/semantics/traversal_order_test.dart:94]: nit: consider putting the bracket and parentheses on their own lines with trailing commas.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 6]
```diff
@@ -243,29 +243,34 @@ void main() {
...
                             ],
-                            actions: <SemanticsAction>[SemanticsAction.tap],
-                            label: 'Button',
-                            textDirection: TextDirection.ltr,
                           ),
-                        ],
-                      ),
+
+                        ]
+                      )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:273]: nit: consider removing empty new line and adding trailing commas.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 7]
```diff
@@ -2735,29 +2735,34 @@ void main() {
...
-                              label: 'B\nTab 2 of 2',
-                              textDirection: TextDirection.ltr,
                             ),
                           ],
                         ),
-                      ],
-                    ),
+
+                      ]
+                    )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart:2765]: nit: consider removing empty new line and adding trailing commas.

File: packages/flutter/test/material/flexible_space_bar_test.dart [hunk 8]
```diff
@@ -214,85 +214,91 @@ void main() {
...
-
-                          ],
-                        ),
                       ],
                     ),
-                  ],
-                ),
+
+                  ]
+                )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/flexible_space_bar_test.dart:301]: nit: consider removing empty new line and adding trailing commas.

File: packages/flutter/test/material/app_bar_test.dart [hunk 9]
```diff
@@ -2594,34 +2606,38 @@ void main() {
...
                             ],
                           ),
-                          TestSemantics(
-                            flags: <SemanticsFlag>[SemanticsFlag.hasImplicitScrolling],
-                          ),
                         ],
                       ),
                     ],
-                  ),
+                  )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/app_bar_test.dart:2640]: nit: trailing comma.

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 10]
```diff
@@ -839,27 +839,31 @@ void main() {
...
+                      ],
+                      children: <TestSemantics>[
+                        TestSemantics(
+                          label: 'BottomSheet',
+                          textDirection: TextDirection.ltr,
+                        ),
+                      ],
                     ),
-                  ],
+                  ]
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/bottom_sheet_test.dart:857]: nit: trailing comma.

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 11]
```diff
@@ -1011,32 +1015,36 @@ void main() {
...
+                            TestSemantics(
+                              label: 'BottomSheet',
+                              textDirection: TextDirection.ltr,
+                            ),
+                          ],
                         ),
                       ],
                     ),
-                  ],
+                  ]
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/bottom_sheet_test.dart:1038]: nit: trailing comma.

File: packages/flutter/test/widgets/simple_semantics_test.dart [hunk 12]
```diff
@@ -63,17 +63,23 @@ void main() {
...
+                          textDirection: TextDirection.ltr,
+                          rect: const Rect.fromLTRB(0.0, 0.0, 10.0, 10.0),
+                          transform: Matrix4.translationValues(395.0, 295.0, 0.0),
+                        ),
+                      ],
                     ),
-                  ],
-                ),
+                  ]
+                )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/simple_semantics_test.dart:82]: nit: trailing commas.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 13]
```diff
@@ -4577,18 +4577,22 @@ void main() {
...
+                              textDirection: TextDirection.ltr,
+                            ),
                           ],
-                          value: expectedValue,
-                          textDirection: TextDirection.ltr,
                         ),
-                      ],
-                    ),
+                      ]
+                    )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_test.dart:4595]: nit: trailing commas, here and elsewhere in this file.

File: packages/flutter/test/material/user_accounts_drawer_header_test.dart [hunk 14]
```diff
@@ -525,35 +525,39 @@ void main() {
...
+                                  textDirection: TextDirection.ltr,
+                                ),
+                              ],
                             ),
                           ],
                         ),
-                      ],
-                    ),
+                      ]
+                    )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/user_accounts_drawer_header_test.dart:560]: nit: trailing commas, here and elsewhere in this file.

File: packages/flutter/test/material/tooltip_theme_test.dart [hunk 15]
```diff
@@ -1243,15 +1243,19 @@ void main() {
...
+                          tooltip: 'Foo',
+                          label: 'Bar',
+                          textDirection: TextDirection.ltr,
+                        ),
+                      ],
                     ),
-                  ],
-                ),
+                  ]
+                )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/tooltip_theme_test.dart:1258]: nit: trailing commas, here and elsewhere in this file.

File: packages/flutter/test/material/tooltip_test.dart [hunk 16]
```diff
@@ -2130,15 +2130,19 @@ void main() {
...
+                          tooltip: 'Foo',
+                          label: 'Bar',
+                          textDirection: TextDirection.ltr,
+                        ),
+                      ],
                     ),
-                  ],
-                ),
+                  ]
+                )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/tooltip_test.dart:2145]: nit: trailing commas, here and elsewhere in this file.

File: packages/flutter/test/material/navigation_rail_test.dart [hunk 17]
```diff
@@ -5428,41 +5428,45 @@ TestSemantics _expectedSemantics() {
...
-                    textDirection: TextDirection.ltr,
-                  ),
-                  TestSemantics(
-                    label: 'body',
-                    textDirection: TextDirection.ltr,
-                  ),
-                ],
-              ),
+                ]
+              )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/navigation_rail_test.dart:5469]: nit: trailing commas.

File: packages/flutter/test/material/menu_anchor_test.dart [hunk 18]
```diff
@@ -3355,48 +3355,54 @@ void main() {
...
-                                    actions: <SemanticsAction>[SemanticsAction.tap],
                                   ),
                                 ],
                               ),
                             ],
                           ),
-                        ],
-                      ),
+                        ]
+                      )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/menu_anchor_test.dart]: nit: trailing commas, here and elsewhere in this file.

File: packages/flutter/test/material/dropdown_test.dart [hunk 19]
```diff
@@ -1330,65 +1330,76 @@ void main() {
...
-              ],
-            ),
+                TestSemantics(
+                  actions: <SemanticsAction>[SemanticsAction.tap, SemanticsAction.dismiss],
+                  label: 'Dismiss',
+                  textDirection: TextDirection.ltr,
+                  children: <TestSemantics>[]
+                )
+              ]
+            )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/dropdown_test.dart:1399]: nit: trailing commas.

File: packages/flutter/test/material/dropdown_test.dart [hunk 20]
```diff
@@ -1330,65 +1330,76 @@ void main() {
...
           ],
         ),
-      ],
+      ]
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/dropdown_test.dart:1402]: nit: trailing comma.

File: packages/flutter/test/material/chip_test.dart [hunk 21]
```diff
@@ -3005,21 +3013,25 @@ void main() {
...
+                                  SemanticsFlag.isFocusable,
+                                ],
+                                actions: <SemanticsAction>[SemanticsAction.tap],
+                              ),
                             ],
-                            actions: <SemanticsAction>[SemanticsAction.tap],
                           ),
                         ],
-                      ),
+                      )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/chip_test.dart:3034]: nit: trailing comma.

File: packages/flutter/test/material/slider_test.dart [hunk 22]
```diff
@@ -1451,28 +1476,33 @@ void main() {
...
+                            ),
                           ],
-                          value: '50%',
-                          increasedValue: '55%',
-                          decreasedValue: '45%',
-                          textDirection: TextDirection.ltr,
                         ),
                       ],
-                    ),
+                    )
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/slider_test.dart:1505]: nit: trailing comma.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Comment by Jasguerrero** [comment]
Reverting, PR breaking google testing b/322136071
