### PR TITLE
`_TapStatusTrackerMixin` should wait until the next `PointerDownEvent` before resetting its state when the tap timer has elapsed

### LINKED ISSUE #129161: TextField that embedded in the GestureDetector can't be selected
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a textfield and wrap it into the gesture detector.

### Expected results

the textfield can be selected and updated.

### Actual results

can't select the text

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            GestureDetector(
              onTap: () {
                print('single tap');
              },
              onDoubleTap: () {
                print('double tap');
              },
              // this textfield can't be selected
              child: TextField(
                controller: TextEditingController()..text = 'Initial Text',
              ),
            ),
            // this textfield can be selected
            TextField(
              controller: TextEditingController()..text = 'Initial Text',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.10.1, on macOS 13.0 22A5358e darwin-arm64, locale en-CN)
    ! Flutter version 3.10.1 on channel unknown at /Users/lucas.xu/Desktop/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
`_TapStatusTrackerMixin` used by `BaseTapAndDragGestureRecognizer` should wait until the next tap down before resetting its state when the `_consecutiveTapTimer` times out. This is because `BaseTapAndDragGestureRecognizer` may not have fired its tap down/tap up event before the state has been reset preventing it from firing the tap down/tap up callbacks at all because `currentDown` and `currentUp` are reset to `null`.

Fixes #129161 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart [hunk 1]
```diff
@@ -533,12 +533,16 @@ mixin _TapStatusTrackerMixin on OneSequenceGestureRecognizer {
...
   Timer? _consecutiveTapTimer;
   Offset? _lastTapOffset;
+  bool _consecutiveTapTimerHasElapsed = false;
 
   // When tracking a tap, the [consecutiveTapCount] is incremented if the given tap
   // falls under the tolerance specifications and reset to 1 if not.
   @override
   void addAllowedPointer(PointerDownEvent event) {
     super.addAllowedPointer(event);
+    if (_consecutiveTapTimerHasElapsed) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart:543]: Could you look at the timer instead to get rid of the boolean?  Something like this:

```dart
if (_consecutiveTapTimer != null && !_consecutiveTapTimer.isActive) {
```

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -2147,6 +2147,52 @@ void main() {
...
+
+    final Offset ePos = textOffsetToPosition(tester, testValue.indexOf('e'));
+    final Offset gPos = textOffsetToPosition(tester, testValue.indexOf('g'));
+
+    final TestGesture gesture = await tester.startGesture(ePos, kind: PointerDeviceKind.mouse);
+    await tester.pump();
+    await gesture.up();
+    // This is to allow the GestureArena to decide a winner between TapGestureRecognizer,
+    // DoubleTapGestureRecognizer, and BaseTapAndDragGestureRecognizer.
+    await tester.pumpAndSettle(const Duration(milliseconds: 300));
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2181]: Is there a constant to use here instead of 300?  kDoubleTapTimeout?

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Maybe you can get rid of the boolean you added though, I left a comment.

File: packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart:543]: That works!
