### PR TITLE
Make host app test actually test host app

### LINKED ISSUE #24124: podhelper.rb doesn't work if framework_dir is a relative path
https://github.com/flutter/flutter/blob/ffa8a1ebe8af7cf85b9eea4d58db47d2f52b3560/packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb#L71 doesn't work is framework_dir is a relative path.

### PR DESCRIPTION
**Pull request by dnfield**
This is _not_ the full Add2App test, but rather something I noticed/rememebred when going to work on that.

The `module_test_ios` test was never fully wired up to actually embed the module into a host app and try to build it.  This fixes that.

In the course of wiring this up, I discovered https://github.com/flutter/flutter/issues/24124 - this fixes that as well.  It also fixes an issue where `xcode_backend.sh` would try to sign things even if the signing variables indicated we shouldn't be (this does not generate a signed app).

/cc @mravn just FYI in case there's anything obvious being missed here.  

Fixes #24124

### CODE REVIEW

File: dev/devicelab/bin/tasks/module_test_ios.dart [hunk 1]
```diff
@@ -127,11 +131,53 @@ Future<void> main() async {
       if (!editableHostAppBuilt) {
         return TaskResult.failure('Failed to build editable host .app');
       }
+
+      section('Add to existing iOS app');
+
+      final Directory hostApp =
+          Directory(path.join(tempDir.path, 'hello_host_app'));
```
Comment (cbracken) [inline dev/devicelab/bin/tasks/module_test_ios.dart]: nit: bring this up onto the previous line.

File: dev/devicelab/bin/tasks/module_test_ios.dart [hunk 2]
```diff
@@ -127,11 +131,53 @@ Future<void> main() async {
...
+      mkdir(hostApp);
+      recursiveCopy(
+        Directory(path.join(
+            flutterDirectory.path, 'dev', 'integration_tests', 'ios_host_app')),
```
Comment (cbracken) [inline dev/devicelab/bin/tasks/module_test_ios.dart]: Same here.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm
