### PR TITLE
Adapt xcresult parser for Xcode 16 changes

### LINKED ISSUE #151502: `xcresulttool get object` is deprecated in Xcode 16, replace with `xcresulttool get test-results`
During a verbose Flutter iOS build on Xcode 16 beta 3 I see:
```
/usr/bin/arch -arm64e xcrun xcresulttool get --path /var/folders/fm/wjzsj_z95ydgn4khxqgbtqx000mfq2/T/flutter_tools.PkqAFW/flutter_ios_build_temp_dirFAy4yP/temporary_xcresult_bundle --format json
[ +856 ms] Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
                    Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
                      See 'xcresulttool get object --help' for more information.
```

Introduced in https://github.com/flutter/flutter/pull/92604 to get the Xcode build failure data
https://github.com/flutter/flutter/blob/a99042e10292337e8e40c0009c5796278dd716d3/packages/flutter_tools/lib/src/ios/xcresult.dart#L47-L53

```
$ xcrun xcresulttool get object --help
OVERVIEW: Get Result Bundle Object. This subcommand is deprecated and will be removed in a future release, consider using `xcresulttool get test-report` instead.
```
 `xcresulttool get test-report` doesn't exist, I assume it's a typo for `test-results`:
```
OVERVIEW: Get test results data.

USAGE: xcresulttool get test-results <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  summary                 Get test report summary.
  tests                   Get all tests from test report.
  test-details            Get detailed information about the test.
  activities              Get the activity trees for the specified test. If the test has more than one run, the activity trees for each run will be included.
  insights                Get test report insights.

  See 'xcresulttool help get test-results <subcommand>' for detailed help.
```

### PR DESCRIPTION
**Pull request by okorohelijah**
This PR updates the iOS build process to support breaking changes in Xcode 16's xcresulttool. The xcresulttool get command, which Flutter uses to parse native build issues, is deprecated and replaced by the new xcresulttool get build-results command. This new command also introduces a completely new, flatter JSON output format.

To address this while maintaining backwards compatibility, this change introduces a two-part solution:
- The XCResultGenerator now detects the Xcode version and conditionally calls the appropriate command (get build-results for Xcode 16+ and get for older versions).
- The XCResult parser has been refactored to be "bilingual," meaning it can intelligently detect the JSON structure and parse both the old (nested) and new (flat) formats correctly.
- This ensures that native iOS build errors and warnings continue to be correctly parsed and displayed to the user on all supported Xcode versions.

Fixes #151502 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 1]
```diff
@@ -361,7 +428,38 @@ bool _shouldDiscardIssue({
...
+    }
+    if (!discard) {
+      issues.add(resultIssue);
+    }
+  }
+  return issues;
+}
+
+/// [OLD] Renamed helper to parse issues from the old (pre-Xcode 16) format.
+List<XCResultIssue> _parseIssuesFromOldFormat({
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/xcresult.dart]: "Old format" probably isn't a good name, as they may add a new format next release, then this would be "old old" 🙂 . How about _parseIssuesFromXcode15Format

File: packages/flutter_tools/test/general.shard/ios/xcresult_test.dart [hunk 2]
```diff
@@ -50,39 +68,77 @@ void main() {
...
-    final fakeProcessManager = FakeProcessManager.list(<FakeCommand>[
-      kWhichSysctlCommand,
-      kx64CheckCommand,
-    ]);
-    final xcode = Xcode.test(
+  required String resultJson,
+  int exitCode = 0,
+  String stderr = '',
+  // Default to an OLD version of Xcode.
+  // This ensures existing tests that don't specify a version still test the old code path.
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/ios/xcresult_test.dart]: A reader of this test won't know what "old code path" is referencing. Be explicit.

**Comment by LouiseHsu** [comment]
Could you run `dart format .` on your branch? :)

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 1 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: Done.

File: packages/flutter_tools/test/general.shard/ios/xcresult_test.dart (hunk 2 above)
Comment (okorohelijah) [reply packages/flutter_tools/test/general.shard/ios/xcresult_test.dart]: Done.

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 3]
```diff
@@ -40,30 +40,37 @@ class XCResultGenerator {
...
-      // See https://github.com/flutter/flutter/issues/151502
-      if (xcodeVersion != null && xcodeVersion >= Version(16, 0, 0)) '--legacy',
-      '--path',
-      resultPath,
-      '--format',
-      'json',
-    ]);
+    final bool useNewCommand = xcodeVersion != null && xcodeVersion >= Version(16, 0, 0);
+
+    // Base command for xcrun
```
Comment (LouiseHsu) [inline packages/flutter_tools/lib/src/ios/xcresult.dart]: I feel like a lot of these comments are a little bit extraneous or too obvious. For example, if you named have `command` be named `baseCommand` and you could skip this comment. Could you go through this pr and clean up the comments a little?

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 4]
```diff
@@ -40,30 +40,37 @@ class XCResultGenerator {
...
+    if (useNewCommand) {
+      // For Xcode 16+, the 'get' command requires a specific subcommand.
+      // 'build-results' is the correct choice for parsing compilation/build errors.
+      command.addAll(<String>['get', 'build-results', '--path', resultPath, '--format', 'json']);
+    } else {
+      // For older versions of Xcode, the original 'get' command works directly.
+      command.addAll(<String>['get', '--path', resultPath, '--format', 'json']);
+    }
+
+    // Run the constructed command.
```
Comment (LouiseHsu) [inline packages/flutter_tools/lib/src/ios/xcresult.dart]: For example, this comment can also be removed -  the actual code makes it obvious its running a command.

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 5]
```diff
@@ -361,7 +421,38 @@ bool _shouldDiscardIssue({
...
+      if (_shouldDiscardIssue(issue: resultIssue, discarder: discarder)) {
+        discard = true;
+        break;
+      }
+    }
+    if (!discard) {
+      issues.add(resultIssue);
+    }
+  }
+  return issues;
```
Comment (LouiseHsu) [inline packages/flutter_tools/lib/src/ios/xcresult.dart]: This is great! You don't have to do this,  but I prefer `where` and `map` when editing collections b/c I feel like it's easier to read. 

eg.
```
  return jsonList
      .whereType<Map<String, Object?>>() 
      .map((issueJson) => XCResultIssue.fromNewFormat( 
          type: type,
          issueJson: issueJson)
      .where((issue) { 
        final shouldDiscard = issueDiscarders.any(
          (discarder) => _shouldDiscardIssue(issue: issue, discarder: discarder),
        );
        return !shouldDiscard;
      })
)
```
Thats mostly pseudo code but something like that?

File: packages/flutter_tools/test/general.shard/ios/xcresult_test.dart [hunk 6]
```diff
@@ -68,13 +89,14 @@ void main() {
       ),
     );
     fakeProcessManager.addCommands(<FakeCommand>[
-      setUpFakeXCResultGetCommand(
+      // Use the new, refactored command setup.
```
Comment (LouiseHsu) [inline packages/flutter_tools/test/general.shard/ios/xcresult_test.dart]: This comment also - imagine reading this comment 2 years down the line. It's no longer new or refactored at that point.

**Review by LouiseHsu — CHANGES_REQUESTED** [review]
Looks good! I have some nits tho.

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 5 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: Makes sense!

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 4 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: done

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 3 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: done

Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart:45]: done

File: packages/flutter_tools/test/general.shard/ios/xcresult_test.dart (hunk 6 above)
Comment (okorohelijah) [reply packages/flutter_tools/test/general.shard/ios/xcresult_test.dart]: that makes sense! done!

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 3 above)
Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: Could you go through the rest of your changes in this PR and make sure _all_ the comments are relevant or add context?
So for example here
https://github.com/flutter/flutter/pull/172596/files#diff-a5b73a108d75e3c2478c7e3951fcd29a14f9f0812e69eab84d3586249b5798d3R78

This comment doesnt add any new context or elaboration to the line below it, because it's made obvious that a XCResult object is being returned already.

Or
https://github.com/flutter/flutter/pull/172596/files#diff-c42f814e6b695d19b050afe377bf041ab936b27f6a1aae54235fa321e956a4faR109
This comment isn't needed because every other test case in this file also sets up the generator

This comment you added is an example of a useful comment, because it's adding context you wouldn't otherwise have from just reading the code
https://github.com/flutter/flutter/pull/172596/files#diff-a5b73a108d75e3c2478c7e3951fcd29a14f9f0812e69eab84d3586249b5798d3R49-R50

It's really great that you're being diligent with adding comments but I think too many redundant comments add visual clutter and make the code a bit harder to read :)

**Review by LouiseHsu — APPROVED** [review]
LGTM! To merge, you just add the `autosubmit` tag to this PR - it'll automatically merge your PR once the tree is open :)

File: packages/flutter_tools/lib/src/ios/xcresult.dart (hunk 3 above)
Comment (okorohelijah) [reply packages/flutter_tools/lib/src/ios/xcresult.dart]: I think i have a better understanding. Thank you!

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 7]
```diff
@@ -80,40 +85,71 @@ class XCResult {
   }) {
     final issues = <XCResultIssue>[];
 
-    final Object? issuesMap = resultJson['issues'];
-    if (issuesMap == null || issuesMap is! Map<String, Object?>) {
-      return XCResult.failed(errorMessage: 'xcresult parser: Failed to parse the issues map.');
-    }
+    /// Detect which xcresult JSON format is being used to ensure backwards compatibility.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/xcresult.dart:88]: For future reference, `///` is for API documentation to be consumed publically for someone reading a class, method, etc, `//` is for comments like this which are a note about what the code is doing.
https://dart.dev/language/comments

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 8]
```diff
@@ -80,40 +85,71 @@ class XCResult {
...
+    ///
+    /// Xcode 16 introduced a new `get build-results` command with a flatter JSON structure.
+    /// Older versions use the original `get` command with a deeply nested structure.
+    /// We differentiate them by checking for the presence of top-level 'errors' or 'warnings'
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/xcresult.dart:92]: This doesn't seem like a robust way to figure out the format. Can you instead use `--schema-version`?

File: packages/flutter_tools/lib/src/ios/xcresult.dart [hunk 9]
```diff
@@ -80,40 +85,71 @@ class XCResult {
...
+    /// keys, which are unique to the modern format.
 
-    final Object? errorSummaries = issuesMap['errorSummaries'];
-    if (errorSummaries is Map<String, Object?>) {
+    if (resultJson.containsKey('errors') || resultJson.containsKey('warnings')) {
       issues.addAll(
-        _parseIssuesFromIssueSummariesJson(
+        _parseIssuesFromNewFormat(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/xcresult.dart:97]: "New" format isn't a good name. What happens when the next format comes around?

**Review by jmagman — COMMENTED** [review]
Sorry I didn't get to this review before you merged.
