### PR TITLE
Properly cleans up routes [prod-leak-fix]

### LINKED ISSUE #126100: Fix non-disposed ValueNotifier<_OverlayEntryWidgetState?> memory leak
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/about_test.dart 
2. Convert testWidgets to testWidgetsWithLeakTracking
3. Run the tests

Parent issue: https://github.com/flutter/devtools/issues/3951

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/126100

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 1]
```diff
@@ -849,40 +849,48 @@ class HeroController extends NavigatorObserver {
     HeroFlightDirection flightType,
     bool isUserGestureTransition,
   ) {
-    if (toRoute != fromRoute && toRoute is PageRoute<dynamic> && fromRoute is PageRoute<dynamic>) {
-      final PageRoute<dynamic> from = fromRoute;
-      final PageRoute<dynamic> to = toRoute;
+    if (toRoute == fromRoute) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart:852]: this just refactor the if condition to return early instead of nested condition.

the real functional change is in line 889 where it check for whether the route is still active before actually do the fly.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 2]
```diff
@@ -3073,7 +3073,16 @@ class _RouteEntry extends RouteTransitionRecord {
...
             assert(route.overlayEntries.every((OverlayEntry e) => !e.mounted));
-            route.dispose();
+            // This is a listener callback of one of the overlayEntries in this
+            // route. Disposing the route also disposes its overlayEntries and
+            // violates the rule that a change notifier can't be disposed during
+            // its notifying callback.
+            //
+            // Use a microtask to ensure the overlayEntries have finished
+            // notifying their listeners before disposing.
+            scheduleMicrotask(() {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart:3083]: I am actually run into a dead end here.

This microtask causes issue where navigator.dispose expects all route are disposed. I think we may need a way to clean up the entry out of term while destroying all the resource other than the entry's changenotifier.

**Comment by goderbauer** [comment]
Looks like many checks are failing. is that related to this change?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 3]
```diff
@@ -849,40 +849,48 @@ class HeroController extends NavigatorObserver {
...
+      return;
+    }
+    if (toRoute is! PageRoute<dynamic> || fromRoute is! PageRoute<dynamic>) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/heroes.dart:855]: can you combine this with the previous if?

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 4]
```diff
@@ -214,7 +214,9 @@ class OverlayEntry implements Listenable {
   /// This method should only be called by the object's owner.
   void dispose() {
     assert(!_disposedByOwner);
-    assert(_overlay == null, 'An OverlayEntry must first be removed from the Overlay before dispose is called.');
+    // In case the owner of this Overlay
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/overlay.dart:217]: this comment seems to be incomplete?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 5]
```diff
@@ -3596,6 +3605,9 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
     _updateHeroController(null);
     focusNode.dispose();
     for (final _RouteEntry entry in _history) {
+      // for (final OverlayEntry overlayEntry in entry.route.overlayEntries) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3608]: What about this commented out code?

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/overlay.dart:217]: sorry about this, I should have turn this into draft. The mounted state was because if the owner of this overlay entry is above the overlay widget. It is possible the entry will be disposed without the owner to have a chance to remove the entry. This is because the dispose starts from the child.

what the parent would know is the entry's notify the parent it has been disposed.

Things can be even worse if the entry is under another opaque entry and does not maintain state. In this case, owner won't even know the entry is disposed because it was never built

File: packages/flutter/test/widgets/routes_test.dart [hunk 6]
```diff
@@ -401,7 +401,7 @@ void main() {
       ],
     );
     await tester.pumpWidget(Container());
-    expect(results, equals(<String>['A: dispose', 'b: dispose']));
+    expect(results, equals(<String>['b: dispose', 'A: dispose']));
```
Comment (chunhtai) [inline packages/flutter/test/widgets/routes_test.dart:404]: I think this is more correct as it disposed the top most route first.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/overlay.dart]: never mind If i try really hard, i can still solve this problem

**Comment by chunhtai** [comment]
Several things makes this pr difficult than I think.

Some systems like HeroController have been operated on disposed Route, and they were somehow able to do that because we didn't properly clean up the route

There are also some logic to make sure the Route's dispose needs to wait for its subtree is properly disposed. This because the subtree may be using something like route's animationcontroller.

Therefore a notifier is introduced in overlayentry to let owner to listen for subtree disposal, but the problem with such logic is that you can't dispose the overlayentry when the notifer notify about the subtree disposal because of the changenotifier doesn't allow calling dispose during listener call back. This was previous ok because the route dispose doesn't properly clean up the overlay entry. Thus, I added a microtask to make sure the listener callback is done before disposing the route.

This created another issue that if a navigator is disposed, it expects all route to dispose. Because some of the dispose was scheduled in a microtask, the navigator won't be able to dispose. Therefore, I added a new lifecycle state called disposing. Navigator will keep track of routes in this state and will force these routes to dispose if Navigator itself is about to be disposed. This is ok because we know the subtree of the route must have been disposed already and we can safely clean up the route at this point

**Comment by chunhtai** [comment]
a friendly bump

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 7]
```diff
@@ -2821,6 +2822,8 @@ enum _RouteLifecycle {
   removing, // we are waiting for subsequent routes to be done animating, then will switch to dispose
   // routes that are completely removed from the navigator and overlay.
   dispose, // we will dispose the route momentarily
+  disposing, // The entry is waiting for its subtree to disposed first. It should
+             // be in stored in the _entryWaitingForSubTreeDisposal
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:2826]: subtree = widget subtree? Maybe a little clearer:

"The entry is waiting for its widget subtree to be disposed first. It is stored in _entryWaitingForSubTreeDisposal while awaiting that."

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 8]
```diff
@@ -3047,9 +3050,15 @@ class _RouteEntry extends RouteTransitionRecord {
...
   }
 
-  void dispose() {
+  void forcedDispose() {
     assert(currentState.index < _RouteLifecycle.disposed.index);
     currentState = _RouteLifecycle.disposed;
+    route.dispose();
+  }
+
+  void dispose() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3059]: Maybe leave a comment here or on forcedDispose explaining the difference...

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/navigator.dart:3059]: e.g. "dispose" waits for all overlayEntries to be unmounted before disposing the route.

**Review by goderbauer — APPROVED** [review]
LGTM
