### PR TITLE
Fix `ListTile` theme shape in a drawer

### LINKED ISSUE #106303: ListTileTheme not respected in a scaffold's drawer option
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click the menu button on the top left cornet to open the drawer
3. Look at the shape of the `ListTile`

**Expected results:** 
I expected the shape of the ListTile in the `drawer` parameter of the Scaffold, to be the same as the one in the `body` of the scaffold, as I **specifically** set 
`style: ListTileStyle.list`

and **NOT**

`style: ListTileStyle.drawer`

**Actual results:** 

Rectangular `ListTile` shape.
The `TextStyle` seems to be respected in the same `style` parameter of the ListTile but not the shape.
So now I'm forced to redefine the shape parameter in every ListTile inside the drawer parameter of the scaffold

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
        hoverColor: Colors.black.withOpacity(0.1),
        scrollbarTheme: const ScrollbarThemeData(mainAxisMargin: 16),
        listTileTheme: ListTileThemeData(
          selectedTileColor: Colors.blue.withOpacity(.3),
          selectedColor: Theme.of(context).textTheme.bodyMedium!.color,
          style: ListTileStyle.list,
          shape: const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(
              Radius.circular(16),
            ),
          ),
        ),
      ),
      home: Scaffold(
        drawer: const Padding(
          padding: EdgeInsets.all(8.0),
          child: MyDrawerWidget(),
        ),
        appBar: AppBar(title: const Text(_title)),
        body: const Padding(
          padding: EdgeInsets.all(8.0),
          child: MyDrawerWidget(),
        ),
      ),
    );
  }
}

class MyDrawerWidget extends StatefulWidget {
  const MyDrawerWidget({Key? key}) : super(key: key);

  @override
  State<MyDrawerWidget> createState() => _MyDrawerWidgetState();
}

class _MyDrawerWidgetState extends State<MyDrawerWidget> {
  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: Column(
        children: [
          ListTile(
            style: ListTileStyle.list,
            selected: true,
            title: const Text('Home'),
            onTap: () {},
          ),
          ListTile(
            style: ListTileStyle.list,
            title: const Text('Contact'),
            onTap: () {},
          )
        ],
      ),
    );
  }
}

```

</details>

**Note**: This seems similar to this issue https://github.com/flutter/flutter/issues/67371 but it was neither specific nor followed-up by the commentors.

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/106303

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/list_tile.dart [hunk 1]
```diff
@@ -759,7 +759,7 @@ class ListTile extends StatelessWidget {
       ?? MaterialStateMouseCursor.clickable.resolve(states);
 
     return InkWell(
-      customBorder: shape ?? tileTheme.shape,
+      customBorder: shape ?? tileTheme.shape ?? theme.listTileTheme.shape,
```
Comment (darrenaustin) [inline packages/flutter/lib/src/material/list_tile.dart:762]: This would make the `ListTileTheme` handle the outer `ThemeData` settings differently than other widgets. The overall `ThemeData.listTileTheme` is already taken into account in `ListTileThemeData.of`.

The problem here appears to be the fact that `Drawer` wraps its child in a `ListThemeData` that overrides the text style:

https://github.com/flutter/flutter/blob/332c22f3912be26e6adf9c0908f6d469495e6010/packages/flutter/lib/src/material/drawer.dart#L667-L670

Which causes the outer ThemeData entry to be ignored for things like shape when inside a Drawer. 

To be more consistent with the rest of the way themes are handled, I think a better way to handle this would be to have the Drawer wrap its child with `ListThemeData.merge` so that it only overrides the style parameter of whatever the current surrounding theme is.

**Review by darrenaustin — CHANGES_REQUESTED** [review]
@TahaTesser thanks for the fix. The approach you use here would make the ListTile handle its theme data differently than all the other widgets. I have a suggestion below that I think would be a better fix for this.

File: packages/flutter/lib/src/material/list_tile.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/list_tile.dart]: That makes sense, thank you for this feedback!

**Review by darrenaustin — CHANGES_REQUESTED** [review]
Just one minor change, and I think we are good to go. Thx.

**Review by darrenaustin — APPROVED** [review]
LGTM. Thx!
