### PR TITLE
Download platform artifacts from assemble if needed

### LINKED ISSUE #68475: Invalid argument(s): Cannot find executable for E:\software\Android\flutter_windows_1.22.2-stable\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot."
## Steps to Reproduce

1. Download project from `https://github.com/zhaopingfu/FlutterReleaseCrash`.
2. Open project `flutter_crash_module`,  open terminal and exec command `flutter pub get`.
3. Open project `FlutterReleaseCrash`,  open terminal and exec command `./gradlew clean && ./gradlew assembleRelease --stacktrace`.

**Expected results:** 

Build successful.

**Actual results:** 

```
Invalid argument(s): Cannot find executable for E:\software\Android\flutter_windows_1.22.2-stable\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot."
```

<details>
  <summary>Logs</summary>

```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --quiet assemble --depfile C:\Users\13081\Desktop\FlutterReleaseCrash\flutter_crash_module\.android\Flutter\build\intermediates\flutter\release/flutter_build.d --output C:\Users\13081\Desktop\FlutterReleaseCrash\flutter_crash_module\.android\Flutter\build\intermediates\flutter\release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64

## exception

ArgumentError: Invalid argument(s): Cannot find executable for E:\software\Android\flutter_windows_1.22.2-stable\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:248:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
<asynchronous suspension>
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#17     Future.wait (dart:async/future.dart:406:26)
#18     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:739:45)
#19     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#20     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN)
    • Flutter version 1.22.2 at E:\software\Android\flutter_windows_1.22.2-stable\flutter
    • Framework revision 84f3d28555 (3 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\software\Android\android_sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\software\Android\android_sdk
    • Java binary at: E:\software\Android\AndroidStudio4.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\software\Android\AndroidStudio4.0
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\software\Android\AndroidStudio4.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • SM G9730 (mobile) • R28M31LGZFJ • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
</details>

### PR DESCRIPTION
**Pull request by jmagman**
Download missing target platform artifacts when run from `flutter assemble -dTargetPlatform`.  This isn't needed from `flutter build` or `flutter run`, but is if the user upgrades, then tries to run from Xcode or Gradle.

From Xcode we can see it work:
```
Showing Recent Messages
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +10 ms] Downloading ios tools...
[ +371 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/20375cebcf3584a23e424e8a722806f77702fa85/ios/artifacts.zip md5 hash: /OZ8Zg+JOPPP+hpcLdYAFQ==
...
```

Fixes https://github.com/flutter/flutter/issues/68475
I KNOW there was an iOS version of this issue but now I can't find it, but I've hit this problems with engine/dart mismatches myself.

### CODE REVIEW

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -1374,31 +1374,10 @@ mixin DeviceBasedDevelopmentArtifacts on FlutterCommand {
   }
 }
 
-/// A mixin which applies an implementation of [requiredArtifacts] that only
-/// downloads artifacts corresponding to a target device.
-mixin TargetPlatformBasedDevelopmentArtifacts on FlutterCommand {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:1379]: Dead as of #70898

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart:1379]: nice

**Review by jonahwilliams — APPROVED** [review]
LGTM!

File: packages/flutter_tools/lib/src/commands/assemble.dart [hunk 2]
```diff
@@ -158,6 +157,21 @@ class AssembleCommand extends FlutterCommand {
...
+  @override
+  Future<Set<DevelopmentArtifact>> get requiredArtifacts async {
+    final String platform = environment.defines[kTargetPlatform];
+    if (platform == null) {
+      return super.requiredArtifacts;
+    }
+
+    final TargetPlatform targetPlatform = getTargetPlatformForName(platform);
+    final DevelopmentArtifact artifact = artifactFromTargetPlatform(targetPlatform);
+    if (artifact != null) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/assemble.dart:169]: actually, this includes universal right?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/assemble.dart:169]: (I think the default required artifacts is empty)

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/assemble.dart:169]: oh wait, nvm it does

Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/assemble.dart:169]: Yeah universal doesn't need to be explicitly returned, it always gets downloaded.

Thanks @christopherfujino for the breadcrumb #45267
https://github.com/flutter/flutter/blob/a7f7687a2e207cfc87146fb27ab7ab507228cf63/packages/flutter_tools/lib/src/cache.dart#L78-L80
