### PR TITLE
Fixed TimeOfDay.hourOfPeriod for the noon and midnight cases.

### LINKED ISSUE #60592: Possible bug in TimeOfDay
When the instance of TimesOfDay is initiated according to 24 hours clock with hour:0, minutes: X (doesn't matter), it should contain the value 12 in hourOfPeriod (which should correlate to 12 in 12 hours clock). Currently it still shows 0.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

### PR DESCRIPTION
**Pull request by darrenaustin**
The current `TimeOfDay.hourOfPeriod` returns 0 for both noon and midnight. While it may be argued that technically these are the 0th hour of the period, the common use case is that these should be 12.

This PR fixes this and adds a test to verify that it returns the right value for any hour.

Fixes: #60592, #72480

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/time.dart [hunk 1]
```diff
@@ -92,7 +92,7 @@ class TimeOfDay {
   DayPeriod get period => hour < hoursPerPeriod ? DayPeriod.am : DayPeriod.pm;
 
   /// Which hour of the current period (e.g., am or pm) this time is.
-  int get hourOfPeriod => hour - periodOffset;
+  int get hourOfPeriod => hour == 0 || hour == 12 ? 12 : hour - periodOffset;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/time.dart:95]: Is it worthwhile to document that behavior in the doc comment above?

**Review by goderbauer — APPROVED** [review]
LGTM
