### PR TITLE
[flutter_tools] fix flutter create --offline

### LINKED ISSUE #96286: Cannot flutter create when offline
# Without flag 

## Repro steps

1. Download a stable macOS build from the releases page: https://docs.flutter.dev/development/tools/sdk/releases

2. Go offline (turn off wifi and anyther other network connection)

3. Extract the downloaded zip (e.g. ~/tmp/flutter)

4. Open a terminal, and run `~/tmp/flutter/bin/flutter create app1`

## Actual result

The command hangs:

```
mit-macbookpro4:tmp mit$ ./flutter/bin/flutter create app2
Running "flutter pub get" in flutter_tools...                          ⢿
```

If you run it with verbose, you can see it's failing trying to get to pub:
https://gist.github.com/mit-mit/17d8f6c21f8970fb6b9dba9e0f24c4cb

## Expected result

The command doesn't hang. We should probably detect that we're offline and pass the --offline flag? Looks like that might be tracked in https://github.com/flutter/flutter/issues/15717

# With flag 

## Repro steps

1. Download a stable macOS build from the releases page: https://docs.flutter.dev/development/tools/sdk/releases

2. Go offline (turn off wifi and anyther other network connection)

3. Extract the downloaded zip (e.g. ~/tmp/flutter)

4. Open a terminal, and run `~/tmp/flutter/bin/flutter create --offline app1`

## Actual result

The command fails trying to download some pub packages ([full log file](https://gist.github.com/mit-mit/5839997c24d6feba0174f36f095d0ba6)):

```
mit-macbookpro4:tmp mit$ ./flutter/bin/flutter --verbose create --offline foobar
...
[ +105 ms] MSG : Resolving dependencies...
[  +76 ms] SLVR: fact: flutter_tools is 0.0.0
...
[ +175 ms] MSG : Resolving dependencies...
...
[        ] SLVR: fact: flutter_tools depends on test 1.17.12
...
[  +13 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/test.
[  +18 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/test
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: DDBCDF1B-745B-4417-B0A9-ABE58D1EF131
[        ]     | X-Pub-Environment: flutter_cli:get
[        ]     | user-agent: Dart pub 2.15.1
[  +91 ms] IO  : HTTP error:
[        ]     | SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: nodename nor servname provided, or not known, errno = 8)

```

## Expected result

The command doesn't hang. 

Are the dependencies of the flutter tool not expected to be pre-populated into the cache? It looks like it doesn't have test 1.17.2:

```
mit-macbookpro4:pub.dartlang.org mit$ pwd
/Users/mit/tmp/flutter/.pub-cache/hosted/pub.dartlang.org

mit-macbookpro4:pub.dartlang.org mit$ ls -l | grep test
drwx------@  7 mit  primarygroup  224 Dec 16 20:31 file_testing-3.0.0
drwx------@ 14 mit  primarygroup  448 Dec 16 20:31 test-1.17.12
drwx------@ 10 mit  primarygroup  320 Dec 16 20:31 test_api-0.4.3
drwx------@  8 mit  primarygroup  256 Dec 16 20:31 test_core-0.4.2
```

### PR DESCRIPTION
**Pull request by Jasguerrero**
Fixes: https://github.com/flutter/flutter/issues/96286

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by christopherfujino** [comment]
For testing, I would recommend adding a new test to test/commands.shard/hermetic/create_usage_test.dart and use the FakeProcessManager and FakeCommand like: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/hermetic/build_ios_test.dart#L122

File: packages/flutter_tools/lib/src/cache.dart [hunk 1]
```diff
@@ -665,7 +665,7 @@ class Cache {
   }
 
   /// Update the cache to contain all `requiredArtifacts`.
-  Future<void> updateAll(Set<DevelopmentArtifact> requiredArtifacts) async {
+  Future<void> updateAll(Set<DevelopmentArtifact> requiredArtifacts, [bool offline = false]) async {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/cache.dart:668]: for these optional parameters can you use named parameters instead?

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 2]
```diff
@@ -1290,8 +1290,15 @@ abstract class FlutterCommand extends Command<void> {
     if (shouldUpdateCache) {
       // First always update universal artifacts, as some of these (e.g.
       // ios-deploy on macOS) are required to determine `requiredArtifacts`.
-      await globals.cache.updateAll(<DevelopmentArtifact>{DevelopmentArtifact.universal});
-      await globals.cache.updateAll(await requiredArtifacts);
+      bool offline;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:1293]:
```suggestion
      final bool offline = argParser.options.containsKey('offline') ? boolArg('offline') : false;
```

File: packages/flutter_tools/test/commands.shard/hermetic/create_usage_test.dart [hunk 3]
```diff
@@ -9,17 +9,50 @@ import 'package:flutter_tools/src/base/file_system.dart';
...
+    bool generateSyntheticPackage = false,
+    String flutterRootOverride,
+    bool checkUpToDate = false,
+    bool shouldSkipThirdPartyGenerator = true,
+    bool printProgress = true,
+  }) async {
+    fs.directory(directory).childFile('.packages').createSync();
+    if (offline == true){
+      calledGetOffline += 1;
+    }
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/create_usage_test.dart:45]: style nit. `else` should be on this line, after `}`

**Review by christopherfujino — APPROVED** [review]
LGTM
