### PR TITLE
Resolve Cupertino textstyle in MaterialBasedCupertinoThemeData

### LINKED ISSUE #146864: In dark mode, the CupertinoTextField cannot display text colors
### Steps to reproduce

In dark mode, the CupertinoTextField cannot display text colors

### Expected results

In dark mode, the CupertinoTextField cannot display text colors

### Actual results

In dark mode, the CupertinoTextField cannot display text colors

### Code sample

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        //  深色模式
        colorScheme: const ColorScheme.dark(),
      ),
      themeMode: ThemeMode.dark,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoTextField(),
          ],
        ),
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

*

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #146864. The overridden resolve was keeping the Cupertino text styles from resolving their dynamic colors depending on the theme brightness when in a MaterialApp in most cases. I *believe* that this was to keep values from the Material theme from changing, but as far as I can tell that shouldn't affect anything in the current state and that is 6 year old code. Waiting to see if tests make me a liar.

Update: tests made me a liar.

Before (text should be showing):
Screenshot 2025-04-22 at 1 58 53 PM

After:
Screenshot 2025-04-22 at 1 59 16 PM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
Google testing failure is caused by an internal bug. b/416512380

File: packages/flutter/lib/src/material/theme_data.dart [hunk 1]
```diff
@@ -2986,11 +2986,14 @@ class MaterialBasedCupertinoThemeData extends CupertinoThemeData {
 
   @override
   CupertinoThemeData resolveFrom(BuildContext context) {
-    // Only the cupertino override theme part will be resolved.
+    // Only the cupertino override theme part will be resolved, as well as the
+    // default text theme.
     // If the color comes from the material theme it's not resolved.
+    final NoDefaultCupertinoThemeData cupertinoOverrideThemeWithTextTheme = _cupertinoOverrideTheme
+        .copyWith(textTheme: textTheme);
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/theme_data.dart:2993]: I'm a little confused here. Doesn't `textTheme` already come from the `_cupertinoOverrideTheme`?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/material/theme_data.dart:2993]: '_cupertinoOverrideTheme' by default has a textTheme of `null`, but the getter textTheme returns a default textTheme if the theme doesn't have one set. So if this isn't done, a textTheme of `null` is resolved, instead of the actual default.

**Review by victorsanni — APPROVED** [review]
LGTM. I wonder if this can also arise with the other getters in `CupertinoThemeData`. Or maybe not a problem there.

**Comment by MitchellGoodwin** [comment]
> LGTM. I wonder if this can also arise with the other getters in `CupertinoThemeData`. Or maybe not a problem there.

It's not a problem with those. All of those are expected to fallback to a Material value if not provided, so they don't need to be resolved, or they are provided a value that will be resolved if able. `textTheme` is the only one that will default to a Cupertino value if not provided.
