### PR TITLE
Fix `flutter build ipa --export-method` not accepting `enterprise` flag

### LINKED ISSUE #153000: "Encountered invalid export-method input." when running `flutter build ipa --export-method enterprise` using Flutter 3.24
### Steps to reproduce

1. Make sure currently using Flutter 3.24
2. run `flutter create sample`
3. cd sample
4. run `flutter build ipa --export-method enterprise` with a valid enterprise apple id

### Expected results

Successfully builds `.xcarchive` and `.ipa` in `build/ios/ipa`

### Actual results

`Runner.xrarchive` successfully built but the message `Encountered invalid export-method input.` was displayed (see screenshot below).

### Code sample

Following the steps above using Flutter 3.24. 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details open><summary>Logs</summary>

Since build and archive was successful, only the error part is pasted.

```console]
...
           [!] App Settings Validation
[        ]     • Version Number: 1.0.0
[        ]     • Build Number: 1
[        ]     • Display Name: Sample
[        ]     • Deployment Target: 12.0
[        ]     • Bundle Identifier: com.example.another.sample.project
[        ]     ! Your application still contains the default "com.example" bundle identifier.
[        ] 
           [!] App Icon and Launch Image Assets Validation
[        ]     ! App icon is set to the default placeholder icon. Replace with unique icons.
[        ]     ! Launch image is set to the default placeholder icon. Replace with unique launch image.
[        ] 
           To update the settings, please refer to https://flutter.dev/to/ios-deploy
           
[   +1 ms] "flutter ipa" took 24,656ms.
[   +1 ms] Encountered invalid export-method input.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BuildIOSArchiveCommand._getVersionAppropriateExportMethod (package:flutter_tools/src/commands/build_ios.dart:596:13)
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:471:22)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[        ] Running 2 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/akmalismail/Documents/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/akmalismail/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89
    ! Error: Browsing on the local area network for Akmal’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by LouiseHsu**
When implementing the fix for https://github.com/flutter/flutter/issues/149369, I missed accounting for the `enterprise` flag for `flutter build ipa` 😬

Fixes https://github.com/flutter/flutter/issues/153000

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 1]
```diff
@@ -599,6 +599,8 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
             return 'release-testing';
           case 'development':
             return 'debugging';
+          case 'enterprise':
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:602]: Instead of throwing can the default fall through to returning the `method`, since I think the args are already enforcing it's in the list? That was we doing have to update this to add new non deprecated methods.

Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:602]: oh yes good point

**Review by jmagman — APPROVED** [review]
