### PR TITLE
Fix decorated box

### LINKED ISSUE #179801: DecoratedSliver inconsistency with pinned header or reversed Scrollable
### Steps to reproduce

1. Create a pinned header wrapped with `DecoratedSliver` in a `CustomScrollView` with `physics` set to BouncingScrollPhysics()
2. Scroll down (or up if CustomScrollView)
3. Try overscroll to test decoration stretch.

### Expected results

The `DecoratedSliver` should always wrap the headers.

### Actual results

Decoration is messy.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Padding(
      padding: const EdgeInsets.symmetric(horizontal: 64.0),
      child: CustomScrollView(
        reverse: true,
        physics: const BouncingScrollPhysics(),
        slivers: <Widget>[
          const _DecoratedSliver(
            isEnabled: true,
            // Here a simple SliverAppBar is used to demonstrate a pinned header sliver.
            sliver: SliverAppBar(
              pinned: true,
              stretch: true,
              expandedHeight: 100.0,
              surfaceTintColor: Colors.transparent,
              backgroundColor: Colors.transparent,
              flexibleSpace: FlexibleSpaceBar(title: Text('My header')),
            ),
          ),
          const _DecoratedSliver(
            sliver: PinnedHeaderSliver(child: ListTile(title: Text('A pinned header sliver'))),
          ),
          _DecoratedSliver(
            sliver: SliverMainAxisGroup(
              slivers: [
                PinnedHeaderSliver(
                  child: SizedBox(height: 150, child: const Center(child: Text('A SliverToBoxAdapter'))),
                ),
                SliverList.builder(
                  itemBuilder: (BuildContext context, int index) => ListTile(title: Text('Item $index')),
                  itemCount: 50,
                ),
              ],
            ),
          ),
        ],
      ),
    ),
  );
}

class _DecoratedSliver extends StatelessWidget {
  const _DecoratedSliver({this.isEnabled = true, required this.sliver});

  final bool isEnabled;
  final Widget sliver;

  @override
  Widget build(BuildContext context) => isEnabled
      ? DecoratedSliver(
          decoration: BoxDecoration(
            border: Border.all(),
            borderRadius: BorderRadius.circular(8),
            gradient: const LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Colors.blue, Colors.purple],
            ),
          ),
          sliver: sliver,
        )
      : sliver;
}
```

</details>

### Screenshots or Video

<details open>

Try with `reverse` true or false.

<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/632ef6f0-0be0-429f-bdb5-402ce6938d6c

`CustomScrollView.reverse` set to `true`

https://github.com/user-attachments/assets/92d251b0-f29d-4e2f-af39-c8de2df2469e

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.40.0-1.0.pre-145, on macOS 26.1 25B78 darwin-arm64, locale fr-FR) [2,7s]
    • Flutter version 3.40.0-1.0.pre-145 on channel master at /Users/emmanuel_lefebvre/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e1aa82352 (88 minutes ago), 2025-12-12 11:32:22 -0500
    • Engine revision 2c6cd4a98d
    • Dart version 3.11.0 (build 3.11.0-235.0.dev)
    • DevTools version 2.53.0
    • Pub download mirror https://artifact.socrate.vsct.fr/artifactory/api/pub/all-pub
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [2,4s]
    • Android SDK at /Users/emmanuel_lefebvre/Library/Android/sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [2,1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [6ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [7,3s]
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 26.1 25B78 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 143.0.7499.110

[✓] Network resources [717ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by zemanux**
Fix #179801

`RenderSliver.getMaxPaintRect` was moved up to `RenderSliver` as it is also needed for PR #179003, the logic was therefore duplicated here.

(The widget labeled `A SliverToBoxAdapter` is actually a `PinnedHeaderSliver`) 

https://github.com/user-attachments/assets/c94b25a2-c156-4d77-a5ed-3059a91044b3

https://github.com/user-attachments/assets/815fa522-1144-4a61-aab8-488942d4a50e

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/decorated_sliver.dart [hunk 1]
```diff
@@ -96,26 +95,12 @@ class RenderDecoratedSliver extends RenderProxySliver {
...
-        Offset(-constraints.scrollOffset, 0.0),
-      ),
-      Axis.vertical => (
-        Size(constraints.crossAxisExtent, cappedMainAxisExtent),
-        Offset(0.0, -constraints.scrollOffset),
-      ),
-    };
-    offset += (child!.parentData! as SliverPhysicalParentData).paintOffset;
+
+    final Rect paintRect = getMaxPaintRect();
```
[the remark this answers is not in the document]
Comment (zemanux) [reply packages/flutter/lib/src/rendering/decorated_sliver.dart:99]: Done.

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 2]
```diff
@@ -1735,6 +1735,60 @@ abstract class RenderSliver extends RenderObject {
...
+        rect.bottom,
+      ),
+      AxisDirection.up => Rect.fromLTRB(
+        rect.left,
+        paintExtent - rect.bottom,
+        rect.right,
+        paintExtent - rect.top,
+      ),
+    };
+  }
```
[the remark this answers is not in the document]
Comment (zemanux) [reply packages/flutter/lib/src/rendering/sliver.dart:1789]: Done.

File: packages/flutter/test/widgets/decorated_sliver_test.dart [hunk 3]
```diff
@@ -267,7 +267,7 @@ void main() {
     expect(
       find.byKey(key),
       paints..rect(
-        rect: const Offset(0.5, -199.5) & const Size(99, 499),
```
Comment (zemanux) [inline packages/flutter/test/widgets/decorated_sliver_test.dart:270]: Previous tests show wrong direction. It has been fixed.

**Review by Piinks — COMMENTED** [review]
> RenderSliver.getMaxPaintRect was moved up to RenderSliver 

Can you open this as a separate PR? Since both changes need it, it would be good to ensure that sticks first and does not cause any unexpected issues.

Thank you for your contributions! I noticed more than one in my queue 🙂 - they are all truly appreciated. I may not be able to finish reviewing them all before the holidays as I am getting into OOO time. I appreciate your patience, and I hope you have a wonderful holiday!

**Comment by Piinks** [comment]
Thanks for separating out the change to ad the method to RenderSliver. I will hold off on reviewing this and https://github.com/flutter/flutter/pull/179003 until the dependent change, https://github.com/flutter/flutter/pull/180074, is ready. :)

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for your patience. 🙏  I was unexpectedly away. I will seek a second reviewer so we can get this in!

File: packages/flutter/test/widgets/decorated_sliver_test.dart [hunk 4]
```diff
@@ -504,6 +504,109 @@ void main() {
       );
     },
   );
+
```
Comment (AbdeMohlbi) [inline packages/flutter/test/widgets/decorated_sliver_test.dart:507]: @zemanux can we add `// Regression test for https://github.com/flutter/flutter/issues/issueNumber` to have the same format across test files , thank u.

**Review by AbdeMohlbi — APPROVED** [review]
LGTM , with one small nit

File: packages/flutter/test/widgets/decorated_sliver_test.dart (hunk 4 above)
Comment (zemanux) [reply packages/flutter/test/widgets/decorated_sliver_test.dart:507]: Done

Comment (AbdeMohlbi) [reply packages/flutter/test/widgets/decorated_sliver_test.dart:507]: ok let's ship this change then
