### PR TITLE
Fix lerping for `NavigationRailThemeData` icon themes

### LINKED ISSUE #118618: `NavigationRail` icons' color does not lerp properly
As seen in the M3 sample app

https://user-images.githubusercontent.com/6655696/212924251-f9714db3-879e-43b9-a5c6-3f5587b63ed0.mov

### PR DESCRIPTION
**Pull request by guidezpl**
Pending a improvements to `NavigationRail` to bring it in line with `NavigationBar` and `NavigationDrawer`, this fixes a lerping issue.

Unlike other `lerp` methods, `IconThemeData.lerp` always returns an `IconThemeData`, which is fine for individual `Icon`s. However, when `Icon`s are used inside other components, the null case should be accounted for to avoid getting unexpected default `Icon` colors.

Fixes https://github.com/flutter/flutter/issues/118618

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/navigation_rail_theme.dart [hunk 1]
```diff
@@ -151,8 +151,10 @@ class NavigationRailThemeData with Diagnosticable {
       elevation: lerpDouble(a?.elevation, b?.elevation, t),
       unselectedLabelTextStyle: TextStyle.lerp(a?.unselectedLabelTextStyle, b?.unselectedLabelTextStyle, t),
       selectedLabelTextStyle: TextStyle.lerp(a?.selectedLabelTextStyle, b?.selectedLabelTextStyle, t),
-      unselectedIconTheme: IconThemeData.lerp(a?.unselectedIconTheme, b?.unselectedIconTheme, t),
-      selectedIconTheme: IconThemeData.lerp(a?.selectedIconTheme, b?.selectedIconTheme, t),
+      unselectedIconTheme: a?.unselectedIconTheme == null && b?.unselectedIconTheme == null
+        ? null : IconThemeData.lerp(a?.unselectedIconTheme, b?.unselectedIconTheme, t),
+      selectedIconTheme: a?.unselectedIconTheme == null && b?.unselectedIconTheme == null
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/navigation_rail_theme.dart:156]: Should here be `a?.selectedIconTheme == null && b?.selectedIconTheme == null`?

Comment (guidezpl) [reply packages/flutter/lib/src/material/navigation_rail_theme.dart:156]: yes, good catch!

**Review by QuncCccccc — APPROVED** [review]
LGTM
