### PR TITLE
Gesture recognizer cleanup

### LINKED ISSUE #81883: PrimaryPointerGestureRecognizer doesn't properly reset its state
## Issue

`PrimaryPointerGestureRecognizer` has a `_gestureAccepted` field:

https://github.com/flutter/flutter/blob/7f1d1414cc5f0b0317272ced49a9c0b44e5c3af8/packages/flutter/lib/src/gestures/recognizer.dart#L450-L452

It uses the value of this field in its calculations of whether or not a pointer event has passed the slop tolerance:

https://github.com/flutter/flutter/blob/7f1d1414cc5f0b0317272ced49a9c0b44e5c3af8/packages/flutter/lib/src/gestures/recognizer.dart#L478-L485

The problem is: it only ever sets this field to true when the gesture is accepted -- it never sets it back to false.

## Test case

Given the info above, we can construct the following test case that fails:

```dart
class IndefiniteGestureRecognizer extends GestureRecognizer {
  @override
  void addAllowedPointer(PointerDownEvent event) {
    GestureBinding.instance!.gestureArena.add(event.pointer, this);
  }

  @override
  void acceptGesture(int pointer) { }

  @override
  void rejectGesture(int pointer) { }

  @override
  String get debugDescription => 'Unresolving';
}

class TestPrimaryPointerGestureRecognizer<T extends PointerEvent> extends PrimaryPointerGestureRecognizer {
  TestPrimaryPointerGestureRecognizer(
    this.resolution, {
    this.onAcceptGesture,
    this.onRejectGesture,
    double? preAcceptSlopTolerance,
    double? postAcceptSlopTolerance,
  }) : super(
    preAcceptSlopTolerance: preAcceptSlopTolerance,
    postAcceptSlopTolerance: postAcceptSlopTolerance,
  );

  final GestureDisposition resolution;
  final VoidCallback? onAcceptGesture;
  final VoidCallback? onRejectGesture;

  @override
  void acceptGesture(int pointer) {
    super.acceptGesture(pointer);
    if (onAcceptGesture != null) {
      onAcceptGesture!();
    }
  }

  @override
  void rejectGesture(int pointer) {
    super.rejectGesture(pointer);
    if (onRejectGesture != null) {
      onRejectGesture!();
    }
  }

  @override
  void handlePrimaryPointer(PointerEvent event) {
    if (event is T) {
      resolve(resolution);
    }
  }

  @override
  String get debugDescription => 'TestPrimaryPointer';
}

const PointerDownEvent down = PointerDownEvent(
  pointer: 5,
  position: Offset(10, 10),
);

const PointerMoveEvent move = PointerMoveEvent(
  pointer: 5,
  position: Offset(15, 15),
);

const PointerUpEvent up = PointerUpEvent(
  pointer: 5,
  position: Offset(15, 15),
);

const PointerDownEvent down2 = PointerDownEvent(
  pointer: 6,
  position: Offset(10, 10),
);

const PointerMoveEvent move2 = PointerMoveEvent(
  pointer: 6,
  position: Offset(100, 200),
);

const PointerUpEvent up2 = PointerUpEvent(
  pointer: 6,
  position: Offset(100, 200),
);

void main() {
  setUp(ensureGestureBinding);

  testGesture('works properly when recycled', (GestureTester tester) {
    final List<String> resolutions = <String>[];
    final IndefiniteGestureRecognizer indefinite = IndefiniteGestureRecognizer();
    final TestPrimaryPointerGestureRecognizer<PointerUpEvent> accepting = TestPrimaryPointerGestureRecognizer<PointerUpEvent>(
      GestureDisposition.accepted,
      preAcceptSlopTolerance: 15,
      postAcceptSlopTolerance: 1000,
      onAcceptGesture: () => resolutions.add('accepted'),
      onRejectGesture: () => resolutions.add('rejected'),
    );

    // Send one complete pointer sequence
    indefinite.addPointer(down);
    accepting.addPointer(down);
    tester.closeArena(5);
    tester.async.flushMicrotasks();
    tester.route(down);
    tester.route(up);
    expect(resolutions, <String>['accepted']);
    resolutions.clear();

    // Send a follow-on sequence that breaks preAcceptSlopTolerance
    indefinite.addPointer(down2);
    accepting.addPointer(down2);
    tester.closeArena(6);
    tester.async.flushMicrotasks();
    tester.route(down2);
    tester.route(move2);
    expect(resolutions, <String>['rejected']);
    tester.route(up2);
    expect(resolutions, <String>['rejected']);
  });
}
```

### PR DESCRIPTION
**Pull request by tvolkert**
1) Make OneSequenceGestureRecognizer.addAllowedPointer()
   call startTrackingPointer(), and change subclasses to
   call super.addAllowedPointer() in place of manually
   calling startTrackingPointer().
2) Fix addAllowedPointer overrides to take PointerDownEvent
   where some were taking PointerEvent.
3) Add API documentation to OneSequenceGestureRecognizer
4) Make the following fields in OneSequenceGestureRecognizer
   private with public getters instead of publicly writable:
   `state`, `primaryPointer`, and `initialPosition`.
5) Clean up gesture recognizer state in
   OneSequenceGestureRecognizer.didStopTrackingLastPointer.
6) Added OffsetPair equals/hashCode

Fixes https://github.com/flutter/flutter/issues/81883

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by tvolkert** [comment]
Blocked on the trees going green (https://github.com/flutter/flutter/issues/81837)

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 1]
```diff
@@ -615,6 +656,14 @@ class OffsetPair {
     );
   }
 
+  @override
+  bool operator ==(Object other) {
+    return other is OffsetPair && other.local == local && other.global == global;
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart:661]: see style guide for template for == methods

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 2]
```diff
@@ -570,6 +610,7 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
 /// Usually, the [global] [Offset] is in the coordinate space of the screen
 /// after conversion to logical pixels and the [local] offset is the same
 /// [Offset], but transformed to a local coordinate space.
+@immutable
 class OffsetPair {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart:614]: making this a class with `==` seems dangerous, because one of the values is generated from the other using floating point math that may or may not give you precisely the same results each time.

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 3]
```diff
@@ -230,11 +230,32 @@ abstract class OneSequenceGestureRecognizer extends GestureRecognizer {
...
   void handleNonAllowedPointer(PointerDownEvent event) {
     resolve(GestureDisposition.rejected);
   }
 
   /// Called when a pointer event is routed to this recognizer.
+  ///
+  /// This will be called for every pointer event while the pointer is being
+  /// tracked. Typically, this recognizer will start tracking the pointer in
+  /// [addAllowedPointer], which means that [handleEvent] will be called
+  /// starting with the [PointerDownEvent].
```
Comment (goderbauer) [inline packages/flutter/lib/src/gestures/recognizer.dart:249]: maybe clarify: this PointerDownEvent represents the same event that was initially given to addAllowedPointer?

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 4]
```diff
@@ -501,7 +536,8 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
   /// Override to be notified when [deadline] is exceeded.
   ///
   /// You must override this method or [didExceedDeadlineWithEvent] if you
-  /// supply a [deadline].
+  /// supply a [deadline]. Subclasses that override this method should _not_
```
[the remark this answers is not in the document]
Comment (tvolkert) [reply packages/flutter/lib/src/gestures/recognizer.dart]: Done

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 5]
```diff
@@ -511,7 +547,8 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
   /// gesture.
   ///
   /// You must override this method or [didExceedDeadline] if you supply a
-  /// [deadline].
+  /// [deadline]. Subclasses that override this method should _not_ call
```
[the remark this answers is not in the document]
Comment (tvolkert) [reply packages/flutter/lib/src/gestures/recognizer.dart]: Done

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 6]
```diff
@@ -439,13 +465,22 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
...
   /// See [GestureRecognizerState] for a description of the states.
-  GestureRecognizerState state = GestureRecognizerState.ready;
+  GestureRecognizerState get state => _state;
+  GestureRecognizerState _state = GestureRecognizerState.ready;
 
   /// The ID of the primary pointer this recognizer is tracking.
-  int? primaryPointer;
+  ///
+  /// If this recognizer is no longer tracking any pointers, this field holds
+  /// the ID of the primary pointer this recognizer was most recently tracking.
```
[the remark this answers is not in the document]
Comment (tvolkert) [reply packages/flutter/lib/src/gestures/recognizer.dart:474]: This is needed so the recognizer knows what pointer it was tracking when the arena resolves -- which can often be after we've stopped tracking the pointer.  For example, if the arena was being held (imagine a double-tap recognizer is also in the arena, and we need to wait until that rejects the gesture to know that we've won).

I added extra comments to try to explain this.

**Comment by tvolkert** [comment]
@goderbauer PTAL

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 7]
```diff
@@ -466,13 +492,27 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
...
+  /// This enables the recognizer to know which pointer is was most recently
```
Comment (goderbauer) [inline packages/flutter/lib/src/gestures/recognizer.dart:502]: typo: is -> it?

**Review by goderbauer — APPROVED** [review]
LGTM after typo fix :)
