### PR TITLE
Fix: Update sheet route bottom padding with top padding

### LINKED ISSUE #163572: Weird SnackBar behavior in CupertinoSheet
### Steps to reproduce

There is a very weird behavior when showing a `SnackBar` from inside the new `CupertinoSheet`. The snackbar appears to be truncated.
I also noticed that if the `showCupertinoSheet` is called from a `Scaffold`, when the `SnackBar` is on screen(truncated) and we long press anywhere on the sheet, the `SnackBar` is fully shown as long as we don't release the press. 

If the widget where `showCupertinoSheet` is called doesn't have a `Scaffold`, the `SnackBar` is only truncated.

Since it appears it's two bugs (not sure if they are related) I will provide two reproduction steps:

### Steps to reproduce Bug 1
1. Run sample app
2. Press "Show CupertinoSheet" button
3. Press "Show SnackBar" button inside the sheet
4. SnackBar appears but mostly truncated

### Steps to reproduce Bug 2
1. Long press anywhere on the sheet while SnackBar is visible but truncated
2. SnackBar appears normally
3. Release long press
4. SnackBar goes back to being mostly truncated

When using `showModalBottomSheet`, the SnackBar behaves normally.

Reproducible on iPhone Simulator, real physical iPhone. Didn't tried it on Android

### Expected results

I expect the SnackBar to appear normally like in any other bottom sheet.

### Actual results

SnackBar is truncated.
SnackBar reacts to long press anywhere on the sheet and becomes fully visible (**Only when `showCupertinoSheet` is called from a widget that contains a `Scaffold`**

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final scaffoldKey = GlobalKey<ScaffoldMessengerState>();

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scaffoldMessengerKey: scaffoldKey,
      home: const TestHome(),
    );
  }
}

class TestHome extends StatefulWidget {
  const TestHome({super.key});

  @override
  State<TestHome> createState() => _TestHomeState();
}

class _TestHomeState extends State<TestHome> {
  void _onShowCupertinoSheet() {
    showCupertinoSheet(
      context: context,
      pageBuilder: (context) => MySheet("CupertinoSheet"),
    );
  }

  void _onShowModalBottomSheet() {
    showModalBottomSheet(
      context: context,
      builder: (context) => MySheet("ModalBottomSheet"),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            FilledButton(
              onPressed: _onShowCupertinoSheet,
              child: Text("Show CupertinoSheet"),
            ),
            FilledButton(
              onPressed: _onShowModalBottomSheet,
              child: Text("Show ModalBottomSheet"),
            ),
          ],
        ),
      ),
    );
  }
}

class MySheet extends StatelessWidget {
  const MySheet(this.showing, {super.key});
  final String showing;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text("Showing $showing"),
            FilledButton(
              onPressed: () {
                scaffoldKey.currentState?.showSnackBar(
                  SnackBar(
                    content: Text("SnackBar"),
                    backgroundColor: Colors.red,
                  ),
                );
              },
              child: Text("Show SnackBar"),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/eeeb57f3-c172-4fa2-971b-822431251bb7

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-US) [1,282ms]
    • Flutter version 3.29.0 on channel stable at /Users/jamilsaadeh/Documents/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (8 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4) [4.2s]
    • Android SDK at /Users/jamilsaadeh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,106ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [10ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [10ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.97.2) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (4 available) [11.6s]
    • iPhone 16 (mobile)              • 965615FC-8FBE-49A7-8B99-081DCE7F5247 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3.1 24D70 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 133.0.6943.99
    ! Error: Browsing on the local area network for J.S. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [328ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #164087: `CupertinoSheetRoute` content extends beyond screen & affects hero animation
### Steps to reproduce

1. Copy and paste the example code below, which is a minimally modified version of the official example from the [Flutter documentation](https://api.flutter.dev/flutter/cupertino/CupertinoSheetRoute-class.html).
2. Tap the “Open Bottom Sheet” button.
3. Notice that the FlutterLogo widget is not fully visible.
4. (Optional) Uncomment the “Scroll Example” or “Hero Example” to observe the same issue in different scenarios.

I tested this using the Pixel 8 Pro emulator on Android and encountered the same issue on other platforms, including Windows and the web (Chrome).

### Expected results

The entire content of the `CupertinoSheetRoute` should be fully visible.

### Actual results

- The bottom of the `CupertinoSheetRoute` extends beyond the screen, and the height of the portion outside the screen varies, likely due to changes in the device height. 
- Interestingly, the hero animation also seems to be affected by this issue, as shown in the video below—the widget makes a sudden jump after the animation is complete.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

/// Flutter code sample for [CupertinoSheetRoute].

void main() {
  runApp(const CupertinoSheetApp());
}

class CupertinoSheetApp extends StatelessWidget {
  const CupertinoSheetApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(brightness: Brightness.light),
      title: 'Cupertino Sheet',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Sheet Example'),
        automaticBackgroundVisibility: false,
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoButton.filled(
              onPressed: () {
                Navigator.of(context).push(
                  CupertinoSheetRoute<void>(
                    builder: (BuildContext context) => const _SheetScaffold(),
                  ),
                );
              },
              child: const Text('Open Bottom Sheet'),
            ),
          ],
        ),
      ),
    );
  }
}

class _SheetScaffold extends StatelessWidget {
  const _SheetScaffold();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          GestureDetector(onTap: () {
            if (CupertinoSheetRoute.hasParentSheet(context)) {
              CupertinoSheetRoute.popSheet(context);
            } else {
              Navigator.pop(context);
            }
          }),
          Container(
            clipBehavior: Clip.hardEdge,
            width: double.infinity,
            decoration: BoxDecoration(
              color: Theme.of(context).cardColor,
              borderRadius: const BorderRadius.vertical(
                top: Radius.circular(12),
              ),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withAlpha(80),
                  spreadRadius: 10,
                  blurRadius: 10,
                  offset: const Offset(0, 7),
                ),
              ],
            ),
            child: const FlutterLogo(size: 200),
          ),
        ],
      ),
    );

    /*
    TODO: Scroll example
    Test with `CupertinoPageScaffold` but same result:
     
    return CupertinoPageScaffold(
      child: Scrollbar(
        thumbVisibility: true,
        trackVisibility: true,
        child: ListView.builder(
          physics: const ClampingScrollPhysics(),
          itemCount: 7,
          itemBuilder: (context, index) {
            return Container(
              color: Colors.amber,
              child: const FlutterLogo(size: 200),
            );
          },
        ),
      ),
    );
 */
    /* 
    TODO: Hero example
    return CupertinoPageScaffold(
      child: Center(
        child: GestureDetector(
          onTap: () {
            Navigator.push(
              context,
              CupertinoPageRoute(
                builder: (_) {
                  return const CupertinoPageScaffold(
                    navigationBar: CupertinoNavigationBar(
                      automaticBackgroundVisibility: false,
                    ),
                    child: SafeArea(
                      child: Align(
                        alignment: Alignment.topCenter,
                        child: Hero(
                          tag: 'test',
                          child: FlutterLogo(size: 200),
                        ),
                      ),
                    ),
                  );
                },
              ),
            );
          },
          child: const Hero(
            tag: 'test',
            child: FlutterLogo(size: 200),
          ),
        ),
      ),
    );
     */
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/d6587077-67d1-4288-94f2-116ac2dc2e38

https://github.com/user-attachments/assets/b1bd2d3d-a571-4320-b55a-6a6446ffdd64

https://github.com/user-attachments/assets/6e2660c5-3000-4529-bb83-ecc559733e6a

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale de-CH) [791ms]
    • Flutter version 3.29.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (2 weeks ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[√] Windows Version (11 Home 64-bit, 24H2, 2009) [5.1s]

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [4.6s]
    • Android SDK at C:\Users\AlexF\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\AlexF\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\AlexF\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web [171ms]
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.0) [169ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33414.496
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.3) [38ms]
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.97.2) [36ms]
    • VS Code at C:\Users\AlexF\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.104.0

[√] Connected device (3 available) [622ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.3194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 133.0.6943.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 132.0.2957.127

[√] Network resources [642ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Update sheet route bottom padding with top padding
fixes: #163572 
fixes: #164087 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 1]
```diff
@@ -494,16 +494,19 @@ class CupertinoSheetRoute<T> extends PageRoute<T> with _CupertinoSheetRouteTrans
...
       removeTop: true,
       removeBottom: true,
       child: Padding(
-        padding: EdgeInsets.only(bottom: bottomPadding),
-        child: CupertinoUserInterfaceLevel(
-          data: CupertinoUserInterfaceLevelData.elevated,
-          child: _CupertinoSheetScope(child: builder(context)),
+        padding: EdgeInsets.only(top: topPadding),
+        child: ClipRRect(
+          borderRadius: const BorderRadius.vertical(top: Radius.circular(12)),
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:505]: I think this makes the ClipRRect usage in the build method and  of CupertinoSheetTransition and _coverSheetSecondaryTransition right? Can we remove those?

**Review by MitchellGoodwin — COMMENTED** [review]
LGTM, just one question about removing duplicate code.

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:505]: Correct me if i am wrong but any `ClipRRect` above `Padding` will add padding first then Clip the child. But here we want to Clip first and then add padding right.

Because any ClipRRect above this will just clip the transparent part which is remaining at top after padding.

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/sheet.dart:505]: Apologies, I had a typo in my comment that I think made things confusing.

Currently the rounded corners are added by two `ClipRRect`s in CupertinoSheetTransition, [here](https://github.com/flutter/flutter/blob/a0b1b3253416b1f19e3f105b596eb6e4c5813ef4/packages/flutter/lib/src/cupertino/sheet.dart#L426C9-L426C26) and [here](https://github.com/flutter/flutter/blob/a0b1b3253416b1f19e3f105b596eb6e4c5813ef4/packages/flutter/lib/src/cupertino/sheet.dart#L443), which both wrap around this code. With the ClipRRect being added here, I think it makes those unneeded?

Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:505]: Yes, make sense. Pushing the change.

Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:499]: Have pushed the required change. Please have a look.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for putting this together!

**Review by justinmc — APPROVED** [review]
LGTM 👍 . Google testing is red but it looks like an infra problem. I've rerun it.
