### PR TITLE
Fixing assumption that baseStyle is a complete style.

### LINKED ISSUE #12832: If you give TextField a TextStyle with only the color set, badness ensues
```
[00052.874] 03959.03982>  EXCEPTION CAUGHT BY WIDGETS LIBRARY 
[00052.881] 03959.03982> The following NoSuchMethodError was thrown building InputDecorator(decoration: InputDecoration(),
[00052.881] 03959.03982> baseStyle: TextStyle(inherit: true, color: Color(0xffffffff)), isFocused: false, isEmpty: true,
[00052.881] 03959.03982> dirty):
[00052.881] 03959.03982> The method '*' was called on null.
[00052.881] 03959.03982> Receiver: null
[00052.881] 03959.03982> Tried calling: *(1.0)
[00052.886] 03959.03982> 
[00052.886] 03959.03982> When the exception was thrown, this was the stack:
[00052.890] 03959.03982> #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
[00052.890] 03959.03982> #1      InputDecorator.build (package:flutter/src/material/input_decorator.dart:483)
[00052.890] 03959.03982> #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3627)
[00052.890] 03959.03982> #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572)
[00052.890] 03959.03982> #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3473)
```

### PR DESCRIPTION
**Pull request by gspencergoog**
This fixes the assumption that InputDecorator had where it expected baseStyle to be a complete style.  Now it merges the baseStyle with the subhead style instead of substituting it entirely.

This fixes #12832.

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -472,16 +472,14 @@ class InputDecorator extends StatelessWidget {
 
     final Color activeColor = _getActiveColor(themeData);
 
-    final TextStyle baseStyle = this.baseStyle ?? themeData.textTheme.subhead;
+    final TextStyle baseStyle = themeData.textTheme.subhead.merge(this.baseStyle);
```
Comment (yjbanov) [inline packages/flutter/lib/src/material/input_decorator.dart]: Have you checked if `floatingLabelStyle.fontSize` can hit the same issue?

**Review by yjbanov — COMMENTED** [review]
Test?

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/input_decorator.dart]: Yes, fixed.

**Comment by gspencergoog** [comment]
Sorry, I was a little premature with sending this off for review before.  I think it's ready now.

I've added tests, and I decided that pretty much anywhere we use a style, it should be merged from a default style instead of being used bare.  They can set inherit to false on the style if needed, and the merge will become a replace.

**Comment by yjbanov** [comment]
> They can set inherit to false on the style if needed, and the merge will become a replace.

Yeah, they'd have to know what they are doing if they explicitly set the `inherit` flag.

lgtm

**if LGT Travis**
