### PR TITLE
Fix small TabBar inconsistencies

### LINKED ISSUE #20886: TabBar does not follow Material Spec, small inconsistencies
Take this screenshot of a scrollable `TabBar` in a `Scaffold` (I added some padding around to make things clearer):

There are 2 small inconsistencies:

1) Tab indicator is 1px smaller than the enclosing tab, on each side:

grafik

This is even more evident when you increase the `indicatorWeight`:

grafik

2) Tabs not aligned with `AppBar` title. The Material spec says that the padding of tabs should be 16 units, but in Flutter `kTabLabelPadding` is set to 12.0:

grafik

Flutter version: Latest master

### PR DESCRIPTION
**Pull request by sir-boformer**
Fixes #20886 

For reference, [here](https://material.io/design/components/tabs.html?image=https%3A%2F%2Fstorage.googleapis.com%2Fspec-host-backup%2Fmio-design%252Fassets%252F16CdW8EmEfI6c803pdGoHJNiqXWg5Aqlw%252Ftabs-spec-cell-minwidth.png#spec) are the material specs for tabs (with the 16 unit padding).

This is how my example app looks like with the fixes (dark border is intentional):

before|after
---------------|------------------
 |

### CODE REVIEW

File: packages/flutter/lib/src/material/tab_indicator.dart [hunk 1]
```diff
@@ -90,6 +90,7 @@ class _UnderlinePainter extends BoxPainter {
     final Rect rect = offset & configuration.size;
     final TextDirection textDirection = configuration.textDirection;
     final Rect indicator = _indicatorRectFor(rect, textDirection).deflate(borderSide.width / 2.0);
-    canvas.drawLine(indicator.bottomLeft, indicator.bottomRight, borderSide.toPaint());
+    final Paint paint = borderSide.toPaint()..strokeCap=StrokeCap.square;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tab_indicator.dart]: strokeCap = StrokeCap.square;

File: packages/flutter/test/material/tabs_test.dart [hunk 2]
```diff
@@ -1277,8 +1277,8 @@ void main() {
   testWidgets('Overflowing RTL tab bar', (WidgetTester tester) async {
     final List<Widget> tabs = new List<Widget>.filled(100,
       // For convenience padded width of each tab will equal 100:
-      // 76 + kTabLabelPadding.horizontal(24)
-      new SizedBox(key: new UniqueKey(), width: 76.0, height: 40.0),
+      // 68 + kTabLabelPadding.horizontal(32)
```
Comment (HansMuller) [inline packages/flutter/test/material/tabs_test.dart]: This test depends extensively on the "width of each tab will equal 100", per line 1279. It would be best to restore that invariant and make sure everything still works without changing the other dimensions around.

**Comment by HansMuller** [comment]
This looks like a good change; we certainly want to match the latest material spec. However it will break tests that depend on screenshots or on tab bar layouts.  It would help to provide before and after tab bar screenshots in the description, to make it clear what is going to change.

**Comment by sir-boformer** [comment]
@HansMuller There is now a before-after comparison in the PR description, and fixed the small formatting issue.

With the slight changes I made to account for the changed padding, all tests are running through. I think there are no tests depending on screenshots of a `TabBar`.

File: packages/flutter/test/material/tabs_test.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/test/material/tabs_test.dart]: Sorry about that. Apparently I can't add :-)

**Comment by HansMuller** [comment]
LGTM

Thanks for this contribution! I will land it.
