### PR TITLE
Fix front layer can be tapped through bug on gallery

### LINKED ISSUE #17180: AbsorbPointer's hitTest should only absorb if tap is inside it
Otherwise it creates the very confusing behaviour where in a row, if there are 2 items side by side and the last item is an AbsorbPointer (because defaultHitTestChildren checks from the last to first children), the first item is not tappable even though the first item is tapped. 

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L2851

cc @Hixie in case there are scenarios where we want this behaviour that I'm missing.

### PR DESCRIPTION
**Pull request by xster**
Also fixes #17180 where AbsorbPointer also blocks its siblings.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -2848,7 +2848,9 @@ class RenderAbsorbPointer extends RenderProxyBox {
 
   @override
   bool hitTest(HitTestResult result, { Offset position }) {
-    return absorbing ? true : super.hitTest(result, position: position);
+    return absorbing && size.contains(position)
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: This might be slightly clearer as:
```
return absorbing ? size.contains(position) : super.hitTest(...)
```

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 1 above)
Comment (xster) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: Indeed

**Comment by xster** [comment]
@fkorotkov thanks for following up. No worries. Our AppVeyor hasn't caught up anyway so no harm done there :)
