### PR TITLE
Block should work inside LazyBlock

### LINKED ISSUE #3534: Assertion failure while rendering Block inside LazyBlock item.
I didn't spend time isolating the problem. We were seeing an error during layout:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/framework.dart': Failed assertion: line 877: 'owner == null ||
!owner._debugStateLocked' is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
The following RenderObject was being processed when the exception was fired:
  RenderViewport relayoutSubtreeRoot=up7 NEEDS-LAYOUT
This RenderObject had the following creator information:
  Viewport ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey 366690234] ←
  ScrollableViewport ← Block ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ←
  ⋯
This RenderObject had the following descendants (showing up to depth 5):
  RenderBlock relayoutSubtreeRoot=up8
    RenderParagraph relayoutSubtreeRoot=up9
    RenderConstrainedBox relayoutSubtreeRoot=up9
      RenderConstrainedBox
    RenderImage relayoutSubtreeRoot=up9
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      Element.visitChildElements (package:flutter/src/widgets/framework.dart:877)
#2      RawGestureDetectorState.replaceGestureRecognizers (package:flutter/src/widgets/gesture_detector.dart:356)
#3      ScrollableState.updateGestureDetector (package:flutter/src/widgets/scrollable.dart:578)
#4      _ScrollableViewportState._handlePaintOffsetUpdateNeeded (package:flutter/src/widgets/scrollable.dart:712)
#5      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:298)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#7      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#9      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#11     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#13     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:160)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#17     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#19     _LazyBlockElement._layout.<anonymous closure> (package:flutter/src/widgets/lazy_block.dart:592)
#20     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:725)
#21     _LazyBlockElement._layout (package:flutter/src/widgets/lazy_block.dart:483)
#22     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1348)
#23     _RenderLazyBlock.performLayout (package:flutter/src/widgets/lazy_block.dart:376)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#25     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#27     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#29     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#31     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#33     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#35     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#37     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#39     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#41     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#43     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#45     RenderStackBase.performLayout (package:flutter/src/rendering/stack.dart:320)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#47     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
#49     RenderView.performLayout (package:flutter/src/rendering/view.dart:100)
#50     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1146)
#51     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:727)
#52     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:135)
#53     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:177)
#54     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._runApp (package:flutter/src/widgets/binding.dart:193)
#55     runApp (package:flutter/src/widgets/binding.dart:207)
```
our widget tree looked something like:
Toplevel-widget
             |
       ChildView
             |
       LazyBlock
     /       |      \
  Block Block Block
    / \      /   \     /  \
  Image Image Image

The crash went away when I replaced `Block` with `Column`.

### PR DESCRIPTION
**Pull request by abarth**
Previously we were locking down the state even when calling layout in
LazyBlock. Now we lock only when building children. Making this work well
involved moving the catch out of lockState and into the few callers who
actually wanted it.

Fixes #3534

### CODE REVIEW

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -723,8 +723,6 @@ class BuildOwner {
     });
     try {
       callback();
-    } catch (e, stack) {
-      _debugReportException(context, e, stack);
     } finally {
       assert(() {
         _debugStateLockLevel -= 1;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: we should probably check at some point whether the compiler is clever enough to elide the exception handling for finally blocks that end up empty

**Comment by Hixie** [comment]
LGTM
