### PR TITLE
Provide more useful error message if a non-compliant DAP tool (or user) sends bad input to DAP server

### LINKED ISSUE #99734: [tool_crash] StateError: Bad state: No element while running `flutter debug-adapter`
Command
```
flutter debug-adapter
```

Steps to Reproduce
1. ...
2. ...
3. ...

Logs
StateError: Bad state: No element
```
%230      ListMixin.firstWhere (dart:collection/list.dart:167:5)
%231      PacketTransformer._parseHeaders (package:dds/src/dap/protocol_stream_transformers.dart:94:17)
%232      PacketTransformer.bind.<anonymous closure>.<anonymous closure> (package:dds/src/dap/protocol_stream_transformers.dart:40:25)
%233      _rootRunUnary (dart:async/zone.dart:1434:47)
%234      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%235      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%236      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%237      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
%238      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
%239      _ExpandStream._handleData (dart:async/stream_pipe.dart:233:14)
%2310     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
%2311     _rootRunUnary (dart:async/zone.dart:1434:47)
%2312     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%2313     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%2314     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%2315     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
%2316     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
%2317     _StreamController._add (dart:async/stream_controller.dart:648:7)
%2318     _StreamController.add (dart:async/stream_controller.dart:596:5)
%2319     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
%2320     _rootRunUnary (dart:async/zone.dart:1442:13)
%2321     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
%2322     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
%2323     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
%2324     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [version 10.0.19044.1526], locale fr-CA)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\HP Probook\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools
```

### PR DESCRIPTION
**Pull request by DanTup**
This fixes https://github.com/flutter/flutter/issues/99734 which was a crash if `flutter debug-adapter` is run and then invalid DAP protocol messages were sent (perhaps from a non-compliant tool, or a user that discovered this command and is running it interactively).

Invalid message now result in a message printed before the real exception:

> Input could not be parsed as a Debug Adapter Protocol message.
> The "flutter debug-adapter" command is intended for use by tooling that communicates using the Debug Adapter Protocol.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/debug_adapter.dart [hunk 1]
```diff
@@ -59,6 +59,14 @@ class DebugAdapterCommand extends FlutterCommand {
       ipv6: ipv6 ?? false,
       enableDds: enableDds,
       test: boolArgDeprecated('test'),
+      onError: (Object? e) {
+        globals.stdio.stderrWrite(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/debug_adapter.dart:63]: Can this be `globals.printError()`?

File: packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart [hunk 2]
```diff
@@ -28,6 +28,7 @@ class FlutterDebugAdapter extends DartDebugAdapter<FlutterLaunchRequestArguments
     bool enableDds = true,
     super.enableAuthCodes,
     super.logger,
+    super.onError,
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart:31]: Out of curiosity, what happens after the callback runs?

File: packages/flutter_tools/lib/src/commands/debug_adapter.dart (hunk 1 above)
Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/debug_adapter.dart:63]: Yep, that seems to work, pushed!

**Review by christopherfujino — APPROVED** [review]
LGTM!

**Comment by DanTup** [comment]
Thanks! Is the Google-testing bot stuck, or is it just slow/have a backlog?

**Comment by christopherfujino** [comment]
> Thanks! Is the Google-testing bot stuck, or is it just slow/have a backlog?

Must be the latter, it's running now
