### PR TITLE
Fix some Focus related documentation typos

### LINKED ISSUE #118572: FocusTraversalPolicy.findLastFocus documentation typo
`FocusTraversalPolicy.findLastFocus` documentation contains a typo where the `previous` function is described as moving the focus "to the **next** node" instead of "the **previous** node".

### PR DESCRIPTION
**Pull request by bleroux**
## Description

While learning more the inner workings of the focus management, I spotted some minor typos on this great documentation. Also fixed some formatting nits in tests source code.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/118572

## Tests

Documentation only PR.

### CODE REVIEW

File: packages/flutter/test/widgets/focus_traversal_test.dart [hunk 1]
```diff
@@ -1474,7 +1474,7 @@ void main() {
       /// Layout is:
       ///           [0, 1]
       ///    [0, 0] [    ] [0, 2]
-      ///    [  1,  0 ] [1, 1] [1, 2]
+      ///    [1, 0] [1, 1] [1, 2]
```
Comment (gspencergoog) [inline packages/flutter/test/widgets/focus_traversal_test.dart:1477]: Actually, that was intentional, to show that the button wasn't the same size as the one above it.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks!

File: packages/flutter/test/widgets/focus_traversal_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/widgets/focus_traversal_test.dart:1477]: Ah ok, let me restore this before merging. :sweat_smile:
