### PR TITLE
Stream logging from attached debugger on iOS

### LINKED ISSUE #19196: Flutter Run fails without error on iOS if Info.plist is missing needed capability
## Steps to Reproduce

1. Clone [this repo](https://github.com/timsneath/flutter_contacts/tree/3ac445f3a95782feed4bc17884328a7143120c49)
2. From the `flutter_contacts/cupertino_app` directory, run `flutter run`
3. Command fails with the following message:
```
Launching lib/main.dart on Tim's iPhone X in debug mode...
Found saved certificate choice "iPhone Developer: Tim Sneath (968GPAAC8N)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Tim Sneath (968GPAAC8N)"
Starting Xcode build...
 ├─Assembling Flutter resources...                    2.5s
 └─Compiling, linking and signing...                  6.7s
Xcode build done.                                           10.7s
Installing and launching...                                 11.9s
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1025/ws
```
4. Add the following to `iOS/Runner/Info.plist`:
```xml
    <key>NSContactsUsageDescription</key>
    <string>This app requires Contacts access to function properly.</string>
```
5. Run `flutter run` again. Command now completes and application executes 

## Expected Result
Flutter should pass through an error message from Xcode rather than simply bailing. The lack of an error message means that it's hard to know where to start looking. 

## Logs
```
[✓] Flutter (Channel master, v0.5.7-pre.82, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.7-pre.82 at /Users/timsneath/flutter
    • Framework revision 236acb5219 (3 hours ago), 2018-07-09 18:55:23 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/timsneath/Library/Android/sdk
    • Android NDK at /Users/timsneath/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.15.0

[✓] Connected devices (1 available)
    • Tim's iPhone X • 1761195f19f63ed83be7780d8ec49e9d8cbba59f • ios • iOS 11.4.1

• No issues found!
```

### LINKED ISSUE #44717: No exceptions logged before runApp on iOS devices
Exceptions that occur before runApp() are not printed to log on iOS devices. Works in simulator.

Related: https://github.com/flutter/flutter/issues/41133

Reproduce:

```
void main() {
  throw Exception('an error happened here');
  runApp(MyApp());
}
```

Result is a frozen app and nothing in the logs.

```
[✓] Flutter (Channel master, v1.10.16-pre.98, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.10.16-pre.98 at /Users/james/Development/flutter
    • Framework revision 03ac37af08 (2 hours ago), 2019-11-08 12:47:26 -0800
    • Engine revision 5f5713e339
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Virgo • 00008030-000848D11EF0802E • ios • iOS 13.2.2

! Doctor found issues in 1 category.
```

### LINKED ISSUE #44718: Logs not printed on iOS devices on build
Logs are not printed on first build on iOS devices. Works in simulator.

Related: https://github.com/flutter/flutter/issues/41133

Reproduce:

```
void main() {
  print("here's a message");
  print("here's a second message");
  runApp(MyApp());
}
```

```
➜  testproject flutter run       
Launching lib/main.dart on Virgo in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           7.3s
 └─Compiling, linking and signing...                         7.2s
Xcode build done.                                           15.9s
Installing and launching...                                        24.7s
Syncing files to device Virgo...                                        
 4,509ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Virgo is available at: http://127.0.0.1:1033/uK9tw0PQzw8=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Performing hot restart...                                              ⣻
flutter: here's a message
flutter: here's a second message
        
Restarted application in 966ms.
```

```
[✓] Flutter (Channel master, v1.10.16-pre.98, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.10.16-pre.98 at /Users/james/Development/flutter
    • Framework revision 03ac37af08 (2 hours ago), 2019-11-08 12:47:26 -0800
    • Engine revision 5f5713e339
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Virgo • 00008030-000848D11EF0802E • ios • iOS 13.2.2

! Doctor found issues in 1 category.
```

### LINKED ISSUE #54781: Get iOS observatory URL and pre-VM connection logs from attached debugger
The engine logs the observatory URL, but for a real iOS device [that log is no longer accessible from the attached host](https://github.com/flutter/flutter/issues/41133), so there's a series of mDNS/other fallbacks in place to try to detect and then guess this port.

`ios-deploy` uses lldb to launch the app on an iOS device, and could be configured to remain attached to read logs from the process, including the observatory logs, launch exceptions, or anything printed before the VM is connected.

### PR DESCRIPTION
**Pull request by jmagman**
## Description

As of iOS 13, the host can't directly read the device logs from the host.  https://github.com/flutter/flutter/pull/43915 connected to the VM observatory and read the log lines from the logging services.

On `flutter run` and `flutter drive` (not `attach` in this PR), instead of waiting to attach to the observatory, instead launch the app with the debugger and _stay attached_ to stream in the logs from `lldb`.  See https://github.com/flutter/flutter/issues/54781#issuecomment-613675256 for details.  This should also reduce devicelab flakes.

This will give the tool access to:
- The observatory port log line
- Full native crash backtraces, including crashes on launch before the engine starts
-  dart `print()`
- dart `stderr.writeln`, other I/O sinks
- native logging (`os_log`, `asserts` etc)
- Engine logs (may need follow up work to filter out the verbose category)

### Notes
- Keep the VM service connection for `flutter attach`.  A follow up PR could attach the debugger in that scenario as well (without re-launching), and then the VM connection can be removed.
- Keep the syslog connection for <iOS 13.  I wasn't able to get this working on my iOS 9.3.6 test device, so don't regress it.  If I can get that working, we can also remove `idevicesyslog`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44717
Fixes https://github.com/flutter/flutter/issues/44718
Fixes https://github.com/flutter/flutter/issues/54781

https://github.com/flutter/flutter/issues/39240 (fixes `run`/`drive`, not `attach`)
https://github.com/flutter/flutter/issues/58078 (fixes `run`/`drive`, not `attach`)

Mitigate https://github.com/flutter/flutter/issues/46705 (`run`/`drive`, not `attach`)
Will allow us to turn off mDNS fallback for `drive` on CI to solve iOS 14 issue https://github.com/flutter/flutter/issues/65207

Note to self: check if this fixes https://github.com/flutter/flutter/issues/19196

## Tests

- ios_deploy_tests
- ios_device_logger_tests
- ios_device_start_prebuilt_tests

Follow up with logging integration tests so this stops regressing.

Also, manually tested:
- Detaching doesn't stop the app.
- `ios-deploy` processes aren't leaking

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 1]
```diff
@@ -82,50 +82,50 @@ class FallbackDiscovery {
     }
 
     try {
-      final Uri result = await _mDnsObservatoryDiscovery.getObservatoryUri(
-        packageId,
-        device,
-        usesIpv6: usesIpv6,
-        hostVmservicePort: hostVmservicePort,
-      );
+      final Uri result = await _protocolDiscovery.uri;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:85]: The change in this method is switching the order of fallbacks, which confused `git`.  Now it first tries log scanning, and only if that fails, falls back to mDNS discovery.

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 2]
```diff
@@ -82,50 +82,50 @@ class FallbackDiscovery {
...
       if (result != null) {
         UsageEvent(
           _kEventName,
-          'mdns-success',
+          'log-success',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:89]: I renamed `fallback-success` and `fallback-failure` to `log-success` and `log-failure`.  Do we care about usage data continuity?  If so, I can change the names back.

File: packages/flutter_tools/lib/src/protocol_discovery.dart [hunk 3]
```diff
@@ -240,10 +240,13 @@ StreamTransformer<S, S> _throttle<S>({
...
         latestLine = value;
 
+        final bool isFirstMessage = lastExecution == null;
         final int currentTime = DateTime.now().millisecondsSinceEpoch;
         lastExecution ??= currentTime;
         final int remainingTime = currentTime - lastExecution;
-        final int nextExecutionTime = remainingTime > waitDuration.inMilliseconds
+
+        // Always send the first event immediately.
+        final int nextExecutionTime = isFirstMessage || remainingTime > waitDuration.inMilliseconds
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/protocol_discovery.dart:249]: This was previously waiting and buffering for `duration` before sending the first message.  The observatory URL was discovered faster than 200 ms in my tests, so let's not wait to process it.

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:89]: Not really, change away

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 4]
```diff
@@ -169,30 +211,193 @@ class IOSDeploy {
...
+      final StreamSubscription<String> stdoutSubscription = _iosDeployProcess.stdout
+          .transform<String>(utf8.decoder)
+          .transform<String>(const LineSplitter())
+          .listen((String line) {
+        _monitorIOSDeployFailure(line, _logger);
+
+        // (lldb)     run
+        // success
+        // 2020-09-15 13:42:25.185474-0700 Runner[477:181141] flutter: Observatory listening on http://127.0.0.1:57782/
+        if (line == '(lldb)     run') {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:279]: this might deserve a const, with a doc describing where you found it.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 5]
```diff
@@ -169,30 +211,193 @@ class IOSDeploy {
...
+    @required List<String> launchCommand,
+    @required Map<String, String> iosDeployEnv,
+    StreamController<String> debuggerOutput,
+  }) : _processUtils = processUtils,
+        _logger = logger,
+        _launchCommand = launchCommand,
+        _iosDeployEnv = iosDeployEnv,
+        _debuggerOutput = debuggerOutput ?? StreamController<String>.broadcast();
+
+  factory IOSDeployDebugger.test({
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:231]: nit: maybe describe what parts are hard-coded for testing

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:89]: The events were only added to understand the severity of the issues around this that we were seeing. Please feel free to modify the events into whatever is useful for this new way of doing things, including adding new ones if needed.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 6]
```diff
@@ -169,30 +211,193 @@ class IOSDeploy {
...
+        if (!debuggerCompleter.isCompleted) {
+          debuggerCompleter.complete(false);
+        }
+        _iosDeployProcess = null;
+      }));
+    } on ProcessException catch (exception, stackTrace) {
+      _logger.printTrace('ios-deploy failed: $exception');
+      _debuggerAttached = false;
+      _debuggerOutput.addError(exception, stackTrace);
+    } on ArgumentError catch (exception, stackTrace) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:347]: This will fail if ios-deploy is missing right? should we catch the error or let it crash here and solve the problem elsewhere? i.e. startup checks

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 7]
```diff
@@ -82,50 +82,50 @@ class FallbackDiscovery {
...
       if (result != null) {
         UsageEvent(
           _kEventName,
-          'fallback-success',
+          'mdns-success',
           flutterUsage: _flutterUsage,
         ).send();
         return result;
       }
-    } on ArgumentError {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:119]: Can this not happen anymore?

**Review by jonahwilliams — COMMENTED** [review]
If this is successful should we remove the mDNS fallback entirely? Could we also remove the provisioning logic for the mDNS permissions?

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 5 above)
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:231]: Can a test only visibility annotation go here?

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 4 above)
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:279]: Is there any way to make this test and the test for 'success' more resilient to changes in output from lldb? Maybe ignore whitespace or unexpected lines between here and 'success'?

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 8]
```diff
@@ -169,30 +211,193 @@ class IOSDeploy {
...
+        }
+
+        if (line.contains('error: process launch failed')) {
+          // Timed out waiting for the app to launch.
+          _debuggerAttached = false;
+          _logger.printTrace(line);
+          debuggerCompleter.complete(false);
+          return;
+        }
+        if (!debuggerAttached) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:308]: Oh, okay. The very next line after the lldb run line doesn't have to be 'success'. We'll wait until it is. Consider updating the comment above.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart [hunk 9]
```diff
@@ -169,30 +211,193 @@ class IOSDeploy {
...
+          .transform<String>(utf8.decoder)
+          .transform<String>(const LineSplitter())
+          .listen((String line) {
+        _logger.printTrace(line);
+      });
+      unawaited(_iosDeployProcess.exitCode.then((int status) {
+        _logger.printTrace('ios-deploy exited with code $exitCode');
+        _debuggerAttached = false;
+        unawaited(stdoutSubscription.cancel());
+        unawaited(stderrSubscription.cancel());
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/ios_deploy.dart:332]: Does ios-deploy have anything interesting on its stderr when it exits with an error?

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 7 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:119]: This change is swapping the order fallbacks.  Before it was trying mDNS and then log scanning, but now it's trying log scanning first.  The reordering confused the diff, this `ArgumentError` was just moved.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:119]: It's https://github.com/flutter/flutter/pull/66092/commits/e91e25e01ffa596f7e60c861b435a9c672a9a29e#diff-e0fb4f81676c3d33cb1796b5f126a4fdR94 now.

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:89]: 👍

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:231]: Good call.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 9 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:332]: Some stuff:
https://github.com/ios-control/ios-deploy/blob/master/src/ios-deploy/ios-deploy.m#L1741
Though nothing that's probably actionable to the developer.  It's being `printTrace`d a few lines above this.
https://github.com/flutter/flutter/pull/66092/files/e91e25e01ffa596f7e60c861b435a9c672a9a29e#diff-8d108d6a887a4f5b74f7c7d77003e795R326

They seem to put actionable errors to `stdout` (see `_monitorIOSDeployFailure` parsing below, which existed before this PR).

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:279]: `run` is coming from [ios-deploy](https://github.com/ios-control/ios-deploy/blob/master/src/ios-deploy/ios-deploy.m#L51), and `success` is coming from lldb.  I will make this a regex to handle whitespace differences.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 8 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:308]: It does have to be "success" (`lldbRunCalled ` logic where it's being set to false if the next line isn't "success"), unless I have a bug in here.

Maybe I should change this to fail if the next line isn't "success" so it doesn't hang forever on something unexpected instead of special-casing "error: process launch failed" (and example of a non-success next line).

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 6 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:347]: I think we already have those checks in place with the stamp/artifact download logic, since `ios-deploy` is an artifact we ship ourselves `idevicesyslog`.  Unlike the Xcode tooling where we do lots of install checks.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 8 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:308]: Ah, okay. I misread the code. My suggestion for a cleanup would be to structure this explicitly as a state machine, with an enum setting out explicitly what the states are, and a big comment explaining what/when the transitions are.

That might also make testing this code easier. I think I see below that the error paths in here could use some coverage.

File: packages/flutter_tools/test/general.shard/ios/ios_deploy_test.dart [hunk 10]
```diff
@@ -21,50 +26,205 @@ void main () {
...
+
+      setUp(() {
+        logger = BufferLogger.test();
+      });
+
+      testWithoutContext('debugger attached', () async {
+        final FakeProcessManager processManager = FakeProcessManager.list(<FakeCommand>[
+          const FakeCommand(
+            command: <String>['ios-deploy'],
+            stdout: '(lldb)     run\r\nsuccess\r\nLog on attach1\r\n\r\nLog on attach2\r\n\r\n\r\n\r\nPROCESS_STOPPED\r\nLog after process exit',
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/ios/ios_deploy_test.dart:81]: Test failure modes on unexpected stdout.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:243]: Done.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart:243]: Done.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart]: Done.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart]: Added more comments and tests.

File: packages/flutter_tools/lib/src/ios/ios_deploy.dart (hunk 8 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/ios_deploy.dart]: Added an enum, hopefully it's clearer now.

File: packages/flutter_tools/test/general.shard/ios/ios_deploy_test.dart (hunk 10 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/ios/ios_deploy_test.dart]: Done.

**Review by jonahwilliams — APPROVED** [review]
LGTM if LG to @zanderso

**Comment by jmagman** [comment]
> If this is successful should we remove the mDNS fallback entirely? Could we also remove the provisioning logic for the mDNS permissions?

It's still used in the `attach` case, would need to trickiness like[ interrupting the app and printing the observatory URL](https://github.com/flutter/flutter/issues/54781#issuecomment-613675256) to get it on attach (there's probably a more elegant way to do this? I don't know how to detect from an app when a debugger attaches, only how to tell if it's launched with the debugger attached).

However it will allow us to remove the mDNS permission for `flutter drive`, which would solve https://github.com/flutter/flutter/issues/65207.

**Review by zanderso — APPROVED** [review]
lgtm

**Comment by jmagman** [comment]
Merging on red, hopefully this will deflake things (after a few reverts no doubt)
