### PR TITLE
[web] Fix SemanticsService.announce not working inside dialogs

### LINKED ISSUE #179076: [Web] SemanticsService.sendAnnouncement is not working inside a dialog
### Steps to reproduce

1. Open a flutter dialog
2. On a button click inside the dialog call  SemanticsService.sendAnnouncement

### Expected results

Screen reader announces the message

### Actual results

The message is not announced

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Semantics Announce ',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyWidget(),
    );
  }
}

/// Run this file:
/// flutter run -t lib/main.dart

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  void showAlertDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext dialogContext) {
        return AlertDialog(
          title: const Text('Confirmation'),
          content: const Text('Are you sure you want to proceed?'),
          actions: <Widget>[
            Row(
              children: [
                TextButton(
                  onPressed: () => _announce(dialogContext),
                  child: const Text('Announce'),
                ),
                TextButton(
                  child: const Text('OK'),
                  onPressed: () {
                    Navigator.of(dialogContext).pop();
                  },
                ),
              ],
            ),
          ],
        );
      },
    );
  }

  void showSimpleDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext dialogContext) {
        return SimpleDialog(
          title: const Text('Choose an option'),
          children: <Widget>[
            SimpleDialogOption(
              onPressed: () => _announce(dialogContext),
              child: const Text('Announce'),
            ),
            SimpleDialogOption(
              onPressed: () {
                Navigator.pop(dialogContext, 'Option 2');
              },
              child: const Text('Close'),
            ),
          ],
        );
      },
    );
  }

  void showCustomDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext dialogContext) {
        return Dialog(
          child: Container(
            padding: const EdgeInsets.all(20),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                const Text('This is a custom dialog!'),
                ElevatedButton(
                  onPressed: () => _announce(dialogContext),
                  child: const Text('Announce'),
                ),
                ElevatedButton(
                  onPressed: () {
                    Navigator.of(dialogContext).pop();
                  },
                  child: const Text('Close'),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  void _announce(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await Future.delayed(const Duration(milliseconds: 1000));
      SemanticsService.sendAnnouncement(
        View.of(context),
        'Hello world',
        TextDirection.ltr,
      );
      print('=================== Hello world Announced');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Dialog Semantics Announce'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(50),
        child: Column(
          children: [
            ElevatedButton(
              child: const Text('Announce'),
              onPressed: () => _announce(context),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              child: const Text('Alert Dialog'),
              onPressed: () => showAlertDialog(context),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              child: const Text('Simple Dialog'),
              onPressed: () => showSimpleDialog(context),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              child: const Text('Custom Dialog'),
              onPressed: () => showCustomDialog(context),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
user@mac-macmini test-app % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.38.2, on macOS 15.6 24G84 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Fixes #179076

**Solution**
When a modal dialog is present, temporarily move the existing aria-live element inside the modal dialog before making the announcement, then move it back afterward. A small delay is also added to allow VoiceOver to finish reading the button's accessible name first.

**Demo**
Before (bug): https://flutter-demo-03-before.web.app
After (fix): https://flutter-demo-03-after.web.app

**Testing**
Enable VoiceOver (Cmd+F5 on macOS)
Open a dialog and click the "Announce" button
Verify the announcement is spoken after the button label

**Next step**
Filing a follow-up issue for: Adding a delay parameter to SemanticsService.announce() API for developers who need custom delays for long button labels

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/accessibility.dart [hunk 1]
```diff
@@ -87,14 +98,48 @@ class AccessibilityAnnouncements {
...
     // See the doc-comment for [_appendSpace] for the rationale.
-    messageElement.text = _appendSpace ? '$message\u00A0' : message;
+    final messageText = _appendSpace ? '$message\u00A0' : message;
     _appendSpace = !_appendSpace;
-    ariaLiveElement.append(messageElement);
-    Timer(liveMessageDuration, () => messageElement.remove());
+
+    Timer(announcementDelay, () {
+      ariaLiveElement.text = messageText;
+    });
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/accessibility.dart]: I'm not sure that I fully understand this delay. I would think that when we receive a request to announce something, we should announce it immediately.

Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/accessibility.dart]: When a user clicks a button that triggers an announcement, voiceOver immediately starts reading the button's accessible name (for example, "Announce, button"). If we set the aria-live text immediately, VoiceOver tries to announce it at the same time. VoiceOver gets confused and drops one of the announcements (usually the aria-live one).The 500ms delay gives VoiceOver time to finish reading the button label before we inject the announcement text.

Without delay:
User clicks "Announce" button
VoiceOver: "Announce, button" ← aria-live update happens here, gets dropped
(silence - announcement lost)

With delay:
User clicks "Announce" button
VoiceOver: "Announce, button"
(500ms pause)
VoiceOver: "Your announcement message"

Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/accessibility.dart]: I did some investigation and it turns out we do not need the 500ms delay value.

**Investigation:** Through systematic testing with different delay values (500ms → 100ms → 50ms → 20ms → 10ms → 5ms → 1ms → 0ms), I discovered:

1. 0ms (synchronous):  Doesn't work - VoiceOver doesn't announce

2. Duration.zero with Timer: Works - VoiceOver announces correctly

**Root Cause:** VoiceOver needs the aria-live text to be set in a different event loop tick than the button click. Setting it synchronously interferes with VoiceOver's internal speech queue processing.

**Fix:** Use Timer(Duration.zero, ...) to defer setting the announcement text to the next event loop iteration.
 This provides the minimum necessary delay.  

Please check https://flutter-demo-03-after.web.app/

**Review by mdebbar — APPROVED** [review]
LGTM
