### PR TITLE
Fix license page rtl

### LINKED ISSUE #113916: License list position has bug in RTL lateral LicensePage
## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Increase the width of the window so that the LicensePage is in lateral mode.

**Actual results:**
ss1

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'RTL License Page',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Directionality(
        textDirection: TextDirection.rtl,
        child: LicensePage(),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```

[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\###\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\###\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

### PR DESCRIPTION
**Pull request by jehhxuxu**
fixes #113916

Description
- Fix the position of the package list on RTL direction.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Comment by jehhxuxu** [comment]
@TahaTesser can you please review?

File: packages/flutter/test/material/about_test.dart [hunk 1]
```diff
@@ -1006,6 +1006,102 @@ void main() {
...
+      ),
+    );
+
+    // If the layout width is less than 840.0 pixels, nested layout is
+    // used which positions license page title at the top center.
+    Offset titleOffset = tester.getCenter(find.text(title));
+    expect(titleOffset, Offset(narrowSize.width / 2, 92.0));
+
+    // Configure a wide window to show the lateral UI.
+    await tester.binding.setSurfaceSize(wideSize);
```
Comment (werainkhatri) [inline packages/flutter/test/material/about_test.dart:1037]: the checks are failing because you're setting the surface size to `wideSize` but not resetting it back to default. either reset it at the end of the test or swap the default and wide size sub-tests so that the overall test ends with default size.

do the same for the rtl test too.

File: packages/flutter/test/material/about_test.dart [hunk 2]
```diff
@@ -1006,6 +1006,102 @@ void main() {
...
+            child: LicensePage(),
+          ),
+        ),
+      ),
+    );
+
+    // If the layout width is less than 840.0 pixels, nested layout is
+    // used which positions license page title at the top center.
+    Offset titleOffset = tester.getCenter(find.text(title));
+    expect(titleOffset, Offset(narrowSize.width / 2, 92.0));
```
Comment (werainkhatri) [inline packages/flutter/test/material/about_test.dart:1034]: you can add a license to the registry (checkout other tests in the same file) and confirm if the listview is in the correct position too.

File: packages/flutter/test/material/about_test.dart [hunk 3]
```diff
@@ -1006,6 +1006,102 @@ void main() {
     expect(tester.takeException().toString(), 'Exception: Injected failure');
     expect(find.text('Exception: Injected failure'), findsOneWidget);
   });
+
+  testWidgets('LicensePage master view layout position - ltr', (WidgetTester tester) async {
+    const TextDirection textDirection = TextDirection.ltr;
+    const Size narrowSize = Size(800.0, 600.0);
```
Comment (werainkhatri) [inline packages/flutter/test/material/about_test.dart:1012]: nit: `defaultSize`. 800x600 is the default and not narrow.

**Review by werainkhatri — COMMENTED** [review]
thank you for your contribution!

just a few suggestions, will approve it post that.

File: packages/flutter/lib/src/material/about.dart [hunk 4]
```diff
@@ -1396,7 +1397,10 @@ class _MasterDetailScaffoldState extends State<_MasterDetailScaffold>
               ),
             ),
           ),
-          body: _masterPanel(context),
+          body: Align(
```
Comment (tgucio) [inline packages/flutter/lib/src/material/about.dart:1400]: I think this can be simplified and the `directionality` variable removed:

```
          child: Align(
            alignment: AlignmentDirectional.centerStart,
```

File: packages/flutter/test/material/about_test.dart [hunk 5]
```diff
@@ -1006,6 +1006,128 @@ void main() {
...
+        title: title,
+        home: Scaffold(
+          body: Directionality(
+            textDirection: textDirection,
+            child: LicensePage(),
+          ),
+        ),
+      ),
+    );
+    // To finish the FakeTimer
```
Comment (tgucio) [inline packages/flutter/test/material/about_test.dart:1057]: Nit: add newline before for consistency with the RTL test. Also add full stop after the comment (and other comments below).

**Review by tgucio — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/about.dart (hunk 4 above)
Comment (jehhxuxu) [reply packages/flutter/lib/src/material/about.dart:1399]: I didn't know that, awesome

**Review by tgucio — APPROVED** [review]
LGTM

**Comment by tgucio** [comment]
Looks like @werainkhatri's comments have been addressed but I'll wait for approval before merging.

**Review by werainkhatri — APPROVED** [review]
thanks for your contribution!

sorry for the delay. will wait in case @gspencergoog has come comments.

blue flutter

**Review by gspencergoog — APPROVED** [review]
Thanks for the thorough tests!
