### PR TITLE
Fix InputDecorator label padding

### LINKED ISSUE #173341: Label padding is wrong for InputDecorator with prefixIcon and/or suffixIcon
### Steps to reproduce

1. Run the code sample
2. Observe the width differences

### Expected results

For InputDecorator, when the label (yellow box) appears within the input, its width should be the same as the content width (green box).
For TextField (which relies on InputDecorator), the label text (second TextField) and the content text (first TextField) should have the same width.

Image

### Actual results

The label width is smaller than the content width because some extra padding is added.

Image

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const InputDecorationLabelPaddingIssue());

class InputDecorationLabelPaddingIssue extends StatelessWidget {
  const InputDecorationLabelPaddingIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(visualDensity: VisualDensity.standard),
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 250,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              spacing: 4.0,
              children: <Widget>[
                const Text('InputDecorator'),
                InputDecorator(
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    suffixIcon: Icon(Icons.align_horizontal_left_sharp),
                    prefixIcon: Icon(Icons.align_horizontal_right_sharp),
                  ),
                  child: Container(width: 200, height: 24, color: Colors.green),
                ),
                InputDecorator(
                  isEmpty: true,
                  decoration: InputDecoration(
                    // The InputDecorator is empty so the label is used as hint.
                    label: Container(width: 200, height: 24, color: Colors.amber),
                    border: const OutlineInputBorder(),
                    suffixIcon: const Icon(Icons.align_horizontal_left_sharp),
                    prefixIcon: const Icon(Icons.align_horizontal_right_sharp),
                  ),
                ),
                const SizedBox(height: 4.0),
                const Text('TextField'),
                TextField(
                  controller: TextEditingController(text: '012345678901234'),
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    suffixIcon: Icon(Icons.align_horizontal_left_sharp),
                    prefixIcon: Icon(Icons.align_horizontal_right_sharp),
                  ),
                ),
                const TextField(
                  decoration: InputDecoration(
                    // The InputDecorator is empty so the label is used as hint.
                    labelText: '012345678901234',
                    border: OutlineInputBorder(),
                    suffixIcon: Icon(Icons.align_horizontal_left_sharp),
                    prefixIcon: Icon(Icons.align_horizontal_right_sharp),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel master, 3.33.0-1.0.pre-1299, on Ubuntu 24.04.2 LTS 6.8.0-71-generic, locale fr_FR.UTF-8)
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes the label padding for an InputDecorator with prefixIcon and/or suffixIcon.

# Before

The label was shorter than the available space because `InputDecoration.contentPadding.horizontal` was applied even when `prefixIcon` and `suffixIcon` were defined. The icons width replaces the corresponding `contentPadding`, so both should not be used at the same time to compute the available space.

image

# After

The label takes all the available space.

image

## Related Issue

Fixes [Label padding is wrong for InputDecorator with prefixIcon and/or suffixIcon ](https://github.com/flutter/flutter/issues/173341)

## Tests

Adds 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -1404,16 +1404,16 @@ class _RenderDropdownMenuBody extends RenderBox
         child = childParentData.nextSibling;
         continue;
       }
-      final double maxIntrinsicWidth = child.getMinIntrinsicWidth(height);
+      final double minIntrinsicWidth = child.getMinIntrinsicWidth(height);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:1407]: Very suspicious naming here, good catch.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -1018,9 +1018,8 @@ class _RenderDecoration extends RenderBox
         constraints.maxWidth -
             (decoration.inputGap * 2 +
                 iconWidth +
-                contentPadding.horizontal +
-                prefixIconSize.width +
-                suffixIconSpace),
+                (prefixIcon == null ? contentPadding.start : prefixIconSize.width) +
+                (suffixIcon == null ? contentPadding.end : suffixIconSpace)),
```
Comment (justinmc) [inline packages/flutter/lib/src/material/input_decorator.dart:1023]: Makes sense.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 3]
```diff
@@ -2951,6 +2951,71 @@ void main() {
...
+            filled: true,
+            label: largeLabel,
+            suffixIcon: Icon(Icons.align_horizontal_left_sharp),
+            prefixIcon: Icon(Icons.align_horizontal_right_sharp),
+          ),
+        ),
+      );
+
+      // When suffixIcon and/or prefixIcon are set, the corresponding horizontal
+      // padding is 52 (48 for the icon + 4 input gap based on M3 spec).
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:2997]: Thanks for explaining the details here.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I've started the Google tests in case this breaks anything, but I'd expect there to only be acceptable image diff test breakages if so.

**Comment by bleroux** [comment]
> I've started the Google tests in case this breaks anything, but I'd expect there to only be acceptable image diff test breakages if so.

@justinmc Looks like there are some Google tests failures :sweat_smile: 
Let me know if some look suspicious. :crossed_fingers:

**Comment by justinmc** [comment]
One thing that might be a bug:

| master | fix_input_decorator_hint_padding |
| --- | --- |
| label_width_master | label_padding_pr |


In some image diffs, when the label is floating, I see that the outline has lost its top-right corner. This only seems to happen when there is a suffix present.

Otherwise the majority of image diff breakages seem to be clear improvements, so that part is great.

<details>

<summary>Repro code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Center(
        child: Padding(
          padding: EdgeInsetsGeometry.symmetric(horizontal: 500.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const <Widget>[
              TextField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText:
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                  suffixIcon: Icon(Icons.clear),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by bleroux** [comment]
@justinmc Thanks for the breakage description and the nice repro. :pray: 

I updated the PR with a small fix for this problem.
I also updated one existing test which was failing due to rounding error. When using a MaterialApp, the rounding does not appear and the test is easier to debug because text metrics are similar to M3 spec (using a MaterialApp sets proper fonts).

**Comment by justinmc** [comment]
Thanks! I've rerun the Google tests.

**Review by justinmc — APPROVED** [review]
All failing tests look like improvements now, let's land it! Thanks for fixing the border length failures.

**Comment by rydmike** [comment]
Nice and thanks @bleroux! I have a use case that has been affected by this issue (using fixed amount of chars with both leading and trailing icon) and I had to make the field longer than it really needed to be to displays all chars. I always wondered what caused it, but never reported it. Now I know and that the fix is on the way. Awesome work as always, thanks 💙 😃
