### PR TITLE
Fixing constraints.precedingScrollExtent passed to SliverPadding child

### LINKED ISSUE #49195: SliverPadding doesn't update precedingScrollExtent
The constraints passed by `RenderSliverEdgeInsetsPadding` to its child don't have `precedingScrollExtent` updated to include the `beforePadding`.

Silly example that shows the problem, trying to show exactly three boxes on the screen with some padding at the top:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Buzz());
}

class Buzz extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverPadding(
          padding: EdgeInsets.all(32),
          sliver: SliverGrid(
            gridDelegate: BuzzDelegate(),
            delegate: SliverChildBuilderDelegate(
              (context, i) => Container(color: Colors.red, alignment: Alignment.center, child: Placeholder()),
              childCount: 6
            ),
          ),
        ),
      ],
    );
  }
}

class BuzzDelegate extends SliverGridDelegate {
  @override
  SliverGridLayout getLayout(SliverConstraints constraints) {
    final mainAxisStride = (constraints.viewportMainAxisExtent - constraints.precedingScrollExtent) / 3;
    return SliverGridRegularTileLayout(
      mainAxisStride: mainAxisStride,
      childMainAxisExtent: mainAxisStride,
      crossAxisCount: 1,
      childCrossAxisExtent: constraints.crossAxisExtent,
      crossAxisStride: constraints.crossAxisExtent,
      reverseCrossAxis: false,
    );
  }

  @override
  bool shouldRelayout(SliverGridDelegate oldDelegate) => true;
}
```

Result:
Screenshot 2020-01-23 at 11 11 02

Observe that the third box is partially cut of, while I expect it to just fit on the screen.

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.12.13+hotfix.5 at .../dev/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

### PR DESCRIPTION
**Pull request by Piinks**
## Description

The `SliverConstraints` passed by `RenderSliverEdgeInsetsPadding` to its `child` aren't updating `precedingScrollExtent` any `beforePadding`. This becomes apparent when the `precedingScrollExtent` is used by the child in its layout path, like in the example provided in #49195, and also `SliverFillRemaining`. This PR fixes that and adds a regression test. 

## Related Issues

Fixes #49195

## Tests

I added the following tests:

SliverPadding updates precedingScrollExtent with beforePadding.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/slivers_padding_test.dart [hunk 1]
```diff
@@ -423,4 +424,31 @@ void main() {
       const Rect.fromLTRB(0.0, -200.0, 800.0, 200.0),
     );
   });
+
+  testWidgets('SliverPadding includes preceding padding in the precedingScrollExtent provided to child', (WidgetTester tester) async {
+    final GlobalKey key = GlobalKey();
```
Comment (Piinks) [inline packages/flutter/test/widgets/slivers_padding_test.dart]:
```suggestion
    // Regression test for https://github.com/flutter/flutter/issues/49195
    final GlobalKey key = GlobalKey();
```

**Review by spkersten — APPROVED** [review]

**Comment by spkersten** [comment]
Thanks for fixing this (and writing the tests)!

File: packages/flutter/test/widgets/slivers_padding_test.dart [hunk 2]
```diff
@@ -423,4 +424,32 @@ void main() {
       const Rect.fromLTRB(0.0, -200.0, 800.0, 200.0),
     );
   });
+
+  testWidgets('SliverPadding includes preceding padding in the precedingScrollExtent provided to child', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/49195
+    final GlobalKey key = GlobalKey();
```
Comment (goderbauer) [inline packages/flutter/test/widgets/slivers_padding_test.dart]: This could just be a UniqueKey instead of a (more expensive) GlobalKey.

File: packages/flutter/test/widgets/slivers_padding_test.dart [hunk 3]
```diff
@@ -423,4 +424,32 @@ void main() {
...
+            )
+          ),
+        ]
+      ),
+    ));
+    await tester.pump();
+
+    expect(
+      tester.renderObject<RenderBox>(find.byKey(key)).size.height,
+      equals(570),
```
Comment (goderbauer) [inline packages/flutter/test/widgets/slivers_padding_test.dart]: Can you add a comment why this has to be 570? (as per style guide avoid magic numbers)

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/slivers_padding_test.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/test/widgets/slivers_padding_test.dart]: Sure thing! :)

Comment (Piinks) [reply packages/flutter/test/widgets/slivers_padding_test.dart]: Let me know if this makes better sense now.

Comment (goderbauer) [reply packages/flutter/test/widgets/slivers_padding_test.dart]: Wonderful. I would have also expected something shorter, like:

```
// height of viewport - top padding = 600 - 30 = 570.
```

:)

Comment (Piinks) [reply packages/flutter/test/widgets/slivers_padding_test.dart]: Yeah. It's a bit --verbose. 😆
