### PR TITLE
Fix focus switching when changing tabs in CupertinoTabScaffold

### LINKED ISSUE #12397: TextField does not work with multiple Navigator
## Steps to Reproduce

- Tap the TextField and enter text.
- Change tab to `Right`
- Tap the TextField and enter text.
- Change tab to `Left`
- Tap the TextField
  - Android sim: Keyboard does not open, text selection works.
  - iOS sim: Can not focus to the TextField.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(new MaterialApp(
    home: new CupertinoTabScaffold(
      tabBar: new CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          new BottomNavigationBarItem(
            icon: new Icon(Icons.directions_car),
            title: new Text('Left'),
          ),
          new BottomNavigationBarItem(
            icon: new Icon(Icons.directions_railway),
            title: new Text('Right'),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return new MaterialApp(
          home: new Scaffold(
            appBar: new AppBar(
              title: new Text(index == 0 ? 'Left' : 'Right'),
            ),
            body: new Container(
              child: new TextField(),
            ),
          ),
        );
      },
    ),
  ));
}
```

When using CupertinoTabBar and BottomNavigationBar, multiple Navigators often required for each tabs to push pages.

In the example, I use MaterialApp because it includes Navigator.

## Logs

No exception.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 7bfa3c5676 (31 hours ago), 2017-10-02 17:32:00 -0700
    • Engine revision e3404b81a5
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34
```

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/12397

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/tab_scaffold.dart [hunk 1]
```diff
@@ -218,15 +218,29 @@ class _TabView extends StatefulWidget {
...
+  void dispose() {
+    for (FocusScopeNode focusScopeNode in tabFocusNodes) {
+      focusScopeNode.detach();
+    }
+    super.dispose();
   }
 
   @override
   Widget build(BuildContext context) {
+    FocusScope.of(context).setFirstFocus(tabFocusNodes[widget.currentTabIndex]);
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/tab_scaffold.dart]: It seems a bit weird to be calling this from build; for example during hot reload every one of these is going to fire and try to grab the focus.

File: packages/flutter/lib/src/cupertino/tab_scaffold.dart [hunk 2]
```diff
@@ -218,15 +218,29 @@ class _TabView extends StatefulWidget {
...
   List<Widget> tabs;
+  List<FocusScopeNode> tabFocusNodes;
 
   @override
   void initState() {
     super.initState();
     tabs = new List<Widget>(widget.tabNumber);
+    tabFocusNodes = new List<FocusScopeNode>.generate(
+      widget.tabNumber,
+      (_) => new FocusScopeNode(),
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/tab_scaffold.dart]: we should give the type and name of the argument here, so that people browsing the code don't have to look it up

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 3]
```diff
@@ -119,6 +120,47 @@ void main() {
...
+
+    expect(focusNodes[0].hasFocus, isFalse);
+    expect(focusNodes[1].hasFocus, isTrue);
+
+    await tester.tap(find.text('Tab 1'));
+    await tester.pump();
+
+    expect(focusNodes[0].hasFocus, isTrue);
+    expect(focusNodes[1].hasFocus, isFalse);
+  });
```
Comment (Hixie) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: do we expect the focus to remain where it had been when you have two text fields in two different tabs and you switch from one tab, then switch to the other tab? that might be something worth testing here too

File: packages/flutter/test/cupertino/tab_scaffold_test.dart [hunk 4]
```diff
@@ -119,6 +120,47 @@ void main() {
...
 }
```
Comment (Hixie) [inline packages/flutter/test/cupertino/tab_scaffold_test.dart]: another thing worth testing would be what happens if there's a text field outside the tab bar view, and it has the focus, then you switch tabs, does the tab bar view grab the focus or does it stay with the text field outside the tab bar view? It should not change.

Comment (xster) [reply packages/flutter/test/cupertino/tab_scaffold_test.dart]: I may not be understanding the focus mechanism correctly but I tried it in a test in https://github.com/xster/flutter-test/blob/master/t75_navigator_focus/lib/main.dart with the focusing mechanism as is. 

It seems like we don't have a way to yield and give focus diagonally up and across the tree. Once a scope's child node is set to have first focus, I don't see an easy way to signal to relinquish its own or its parents' first focus position to a sibling or parents' siblings. 

I may not be understanding correctly. We can chat in person.

File: packages/flutter/test/cupertino/tab_scaffold_test.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/test/cupertino/tab_scaffold_test.dart]: it's definitely possible in flutter though, right?

File: packages/flutter/test/cupertino/tab_scaffold_test.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/test/cupertino/tab_scaffold_test.dart]: I meant a case where the UI is like this:

```
+-----------+
| Field0    |
|+---------+|
||_T1_| T2 ||
|+---------+|
|| Field1  ||
||         ||
|+---------+|
+-----------+
```

Field0 is a focusable field outside the tabs; there's two tabs, in each one there's a focusable field.

Tap on Field0, it takes focus, keyboard comes up; switch to Tab 2 (which shows Field2), does the focus remain in Field0?

File: packages/flutter/test/cupertino/tab_scaffold_test.dart (hunk 3 above)
Comment (xster) [reply packages/flutter/test/cupertino/tab_scaffold_test.dart]: Seems like on Android the focus isn't lost when dismissing the keyboard to reveal the tab bar. 

The described scenario works. Added a test.

File: packages/flutter/test/cupertino/tab_scaffold_test.dart (hunk 4 above)
Comment (xster) [reply packages/flutter/test/cupertino/tab_scaffold_test.dart]: Chatted with Adam. The existing API doesn't support requesting focus across one layer of ancestry. Left #14792 to augment the API.

File: packages/flutter/lib/src/cupertino/tab_scaffold.dart [hunk 5]
```diff
@@ -199,8 +199,8 @@ class _CupertinoTabScaffoldState extends State<CupertinoTabScaffold> {
 
 /// An widget laying out multiple tabs with only one active tab being built
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/tab_scaffold.dart]: I know this isn't you comment, but change "An widget" to "A widget".

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/cupertino/tab_scaffold.dart (hunk 5 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/tab_scaffold.dart]: Done. Thanks.
