### PR TITLE
Fix TabBar.image does not render at initialIndex for the first time

### LINKED ISSUE #59143: Tabbar.image does not render at initialIndex for the first time
✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
未命名

```
TabBar(
                    labelColor: Theme.of(context).accentColor,
                    unselectedLabelColor: Theme.of(context).hintColor,
                    indicatorSize: TabBarIndicatorSize.label,
                    indicator: BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage('assets/618.png'),
                        fit: BoxFit.cover,
                      ),
                    ),
                    isScrollable: true,
                    tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                  ),
```

### PR DESCRIPTION
**Pull request by huycozy**
- Fix https://github.com/flutter/flutter/issues/59143
- The investigation is at https://github.com/flutter/flutter/issues/59143#issuecomment-3626318406
- Describe the fix: 
    - Make `_IndicatorPainter` listen to both the controller animation and a new painter notifier triggered when the indicator image finishes fetching.
    - Added some regression tests

<details open>
<summary>Demo</summary>

| before | after |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/10bb68f7-1c65-422b-b87f-c2b2dd602e70"/> | <video src="https://github.com/user-attachments/assets/bd5a9d8a-97c8-4a8d-ba43-44242f50ec94"/>

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -462,8 +462,51 @@ class _DividerPainter extends CustomPainter {
...
+      dividerHeight: dividerHeight,
+      showDivider: showDivider,
+      devicePixelRatio: devicePixelRatio,
+      indicatorAnimation: indicatorAnimation,
+      textDirection: textDirection,
+      repaint: _IndicatorPainterNotifier(),
+    );
+  }
+
+  _IndicatorPainter._({
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/tabs.dart:521]: Comment somewhere why this double constructor design is needed.

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thank you so much for the investigation and fix!

File: packages/flutter/lib/src/material/tabs.dart (hunk 1 above)
Comment (huycozy) [reply packages/flutter/lib/src/material/tabs.dart:521]: Make sense. I added a comment to the constructor to explain this.
