### PR TITLE
[flutter_tools] Allow providing dart-defines to Android, iOS, macOS builds

### LINKED ISSUE #44483: Plumb "DartDefines` through gradle and xcode
As of https://github.com/flutter/flutter/pull/44083 we'll have a concept of "DartDefines" that provides `-D` options to the underlying Dart compiler. However, this option doesn't work when building through gradle and xcode.

/cc @jonahwilliams

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Allows providing arbitrary String, bool, int, or double constants to all dart applications in run/build/drive mode. Refactors code that used `BuildMode` + additional arguments to instead only use `BuildInfo`, which is a more complete collection of the current configuration.

Adds a devicelab test that runs with a String.fromEnvironment provided by a define.

Removes dead code from simulator run logic

Fixes https://github.com/flutter/flutter/issues/44483

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 1]
```diff
@@ -120,17 +120,17 @@ class BuildIOSFrameworkCommand extends BuildSubCommand {
 
   FlutterProject _project;
 
-  List<BuildMode> get buildModes {
-    final List<BuildMode> buildModes = <BuildMode>[];
+  List<BuildInfo> get buildInfos {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Rather than plumb through empty dart defines list, I updated most of build framework to operate on BuildInfo instead of BuildMode

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 2]
```diff
@@ -420,20 +417,13 @@ class IOSSimulator extends Device {
   }
 
   Future<void> _setupUpdatedApplicationBundle(covariant BuildableIOSApp app, BuildInfo buildInfo, String mainPath) async {
-    await sideloadUpdatedAssetsForInstalledApplicationBundle(buildInfo, mainPath);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: This doesn't appear to do anything

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 3]
```diff
@@ -510,7 +506,7 @@ abstract class FlutterCommand extends Command<void> {
 
     String extraFrontEndOptions =
         argParser.options.containsKey(FlutterOptions.kExtraFrontEndOptions)
-            ? stringArg(FlutterOptions.kExtraFrontEndOptions)
+            ? stringsArg(FlutterOptions.kExtraFrontEndOptions)?.join(',')
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: It looks like these arguments are not tested or specified correctly, still working on what they should actually be. Tempted to remove for now

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: FYI @jmagman

File: packages/flutter_tools/lib/src/build_info.dart [hunk 4]
```diff
@@ -46,10 +47,10 @@ class BuildInfo {
   final bool trackWidgetCreation;
 
   /// Extra command-line options for front-end.
-  final String extraFrontEndOptions;
+  final List<String> extraFrontEndOptions;
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_info.dart]: These don't seem to be used anywhere, but fixing them is out of scope for this change. Using `getBuildInfo` in more commands revealed that the types of the argument + these values did not always match up. Some commands had specified this as a multi-option, but that returns a List<String> so I tweaked the build info to keep it in that format

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 5]
```diff
@@ -322,6 +323,9 @@ Future<void> buildGradleApp({
   if (androidBuildInfo.shrink) {
     command.add('-Pshrink=true');
   }
+  if (androidBuildInfo.buildInfo.dartDefines?.isNotEmpty ?? false) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/android/gradle.dart]: Wondering if checking for null could mask a bug. I tried to make it so that `dartDefines` is not null for commands that accept it. There's even a check like this: https://github.com/flutter/flutter/blob/1ba4f1f509202f3d2ec16f053edcbe2df6b7107e/packages/flutter_tools/lib/src/commands/daemon.dart#L93

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 6]
```diff
@@ -48,7 +48,7 @@ class BuildIOSFrameworkCommand extends BuildSubCommand {
     usesTargetOption();
     usesFlavorOption();
     usesPubOption();
-    usesDartDefines();
+    usesDartDefinesOption();
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: nit: the option is "dart-define" not "dart-defines", so maybe `usesDartDefineOption`?

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 7]
```diff
@@ -438,7 +438,7 @@ end
         bitcode: true,
         reportTimings: false,
         iosBuildArchs: <DarwinArch>[DarwinArch.armv7, DarwinArch.arm64],
-        dartDefines: dartDefines,
+        dartDefines: stringsArg('dart-define'),
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Why not take `BuildInfo` and extract dart defines out of it?

File: packages/flutter_tools/lib/src/android/gradle.dart (hunk 5 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/android/gradle.dart]: Ah, nvm, I see now that you are changing this below.

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_info.dart [hunk 8]
```diff
@@ -14,7 +14,7 @@ class BuildInfo {
   const BuildInfo(
     this.mode,
     this.flavor, {
-    this.trackWidgetCreation = false,
+    this.trackWidgetCreation = true,
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/build_info.dart]: What's the reason for flipping the default? Can this just be required so that we're sure no call sites get flipped by accident?

File: packages/flutter_tools/lib/src/build_info.dart (hunk 4 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/build_info.dart]: Are the Dart defines a special case of front end options? Or do they go different places?

File: packages/flutter_tools/lib/src/ios/simulators.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/simulators.dart]: Who wrote it? Can we ask?

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 9]
```diff
@@ -336,20 +337,16 @@ abstract class FlutterCommand extends Command<void> {
         valueHelp: 'x.y.z');
   }
 
-  void usesDartDefines() {
+  void usesDartDefinesOption() {
     argParser.addMultiOption(
-      'dart-define',
+      FlutterOptions.kDartDefinesOption,
       help: 'Passed to the Dart compiler building this application as a -D flag.\n'
             'Values supported by this option are compiler implementation specific.\n'
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Is this true?

Should we note somewhere that the environment values are treated by the compiler as constants for the purposes of dead-code elimination, etc.?

File: packages/flutter_tools/lib/src/ios/simulators.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/simulators.dart]: I lost the thread around https://github.com/flutter/flutter/pull/14016 . It seems like it was used pre-Dart 2 to prepare the FLX bundle, and has persisted since then

File: packages/flutter_tools/lib/src/build_info.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_info.dart]: Kind of, we currently need to handle them different for dart2js builds so sticking them in the same list is not really an advantage. Furthermore, the extraFrontEndOptions and extraGenSnapshotOptions are actually broken and don't go anywhere for now.

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Fixed

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart (hunk 7 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios_framework.dart]: Done

File: packages/flutter_tools/lib/src/build_info.dart (hunk 8 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_info.dart]: Switched it back, this was unrelated

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 9 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart]: Updated the description

File: dev/devicelab/lib/tasks/defines_task.dart [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+
+Future<TaskResult> runDartDefinesTask() async {
+  final Device device = await devices.workingDevice;
+  await device.unlock();
+  final String deviceId = device.deviceId;
+  final Directory testDirectory = dir('${flutterDirectory.path}/dev/integration_tests/ui');
+  await inDirectory<void>(testDirectory, () async {
+    await flutter('packages', options: <String>['get']);
+
+    await flutter('drive', options: <String>['--verbose', '-d', deviceId, '--dart-define=test.value=ExampleValue', 'lib/defines.dart']);
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply dev/devicelab/lib/tasks/defines_task.dart]: Fixed

**Review by zanderso — APPROVED** [review]
