### PR TITLE
No image shader caching in default shader warm-up

### LINKED ISSUE #29172: complex_layout_scroll_perf__memory regressed
The following complex_layout_scroll_perf__memory benchamrks regressed:

* start-max
* end-max

The regression started with https://github.com/flutter/flutter/commit/c63dcf3bcd73bc9de270a9bb8fdc6efd12a4456a.

/cc @liyuqian

### PR DESCRIPTION
**Pull request by liyuqian**
## Description

It turns out that no matter how small the image is, too much memory will
be used. Hence remove the image shader caching and let the client
implement itself based on needs.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/29172

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/painting/shader_warm_up.dart [hunk 1]
```diff
@@ -182,29 +182,7 @@ class DefaultShaderWarmUp extends ShaderWarmUp {
...
-      canvas.translate(80.0, 0.0);
-      canvas.drawImageRect(image, srcRect, ui.Rect.fromLTWH(20.0, 20.0, imageWidth * 0.6, imageWidth * 0.6), paints[0]);
-      canvas.translate(80.0, 0.0);
-      canvas.drawImageRect(image, srcRect, ui.Rect.fromLTWH(10.0, 10.0, imageWidth * 1.5, imageWidth * 1.5), paints[0]);
-      canvas.restore();
-      completer.complete();
-    });
-
-    return completer.future;
+    // No asynchronous work in the default shader warm-up yet.
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/shader_warm_up.dart]: Is this work that clients would have to repeat?  If so, would it make sense to just guard this with a bool that defaults to false?

Comment (dnfield) [reply packages/flutter/lib/src/painting/shader_warm_up.dart]: Ah I see.  It would probably make more sense to just provide another subclass that extends this one and adds the ImageShader stuff. Of course that doesn't need to be done for this PR to land, more asking for curiosity

Comment (dnfield) [reply packages/flutter/lib/src/painting/shader_warm_up.dart]: (You now have an unused import for typed_data though)

Comment (liyuqian) [reply packages/flutter/lib/src/painting/shader_warm_up.dart]: Yes, I'm currently creating a custom ShaderWarmUp for our internal client for the image shaders. I'll make sure that our internal client is Ok with this before landing it :)

File: packages/flutter/lib/src/painting/shader_warm_up.dart [hunk 2]
```diff
@@ -182,29 +182,7 @@ class DefaultShaderWarmUp extends ShaderWarmUp {
...
+    return Future<void>.value(null);
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/painting/shader_warm_up.dart]: Instead of explicitly creating a Future at thend, add an `async` to the method declaration. Then the future will be created automatically.

Comment (liyuqian) [reply packages/flutter/lib/src/painting/shader_warm_up.dart]: Done. Thanks!
