### PR TITLE
Fix documentation for InputDecoration.focusColor

### LINKED ISSUE #109847: InputDecoration's focusColor is no longer used with TextFormField, but that is not mentioned in documentation
Hello!

According to the [current documentation](https://api.flutter.dev/flutter/material/InputDecoration/focusColor.html):
```
/// By default the [focusColor] is based on the current [Theme].
  ///
  /// The decoration's container is the area which is filled if [filled] is
  /// true and bordered per the [border]. It's the area adjacent to
  /// [icon] and above the widgets that contain [helperText],
  /// [errorText], and [counterText].
```

As I have found it was removed from from UI rendering of TextFormField/TextField and now it is not working with these widgets. It would be very nice to mention that in the documentation.

Now it's not obvious, that it's useless to assign focusColor for TextFormField/TextField and it takes time to find out why it doesn't work.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This updates the `InputDecoration`'s documentation to clarify what happens with `focusColor`.

I also cleaned up a few other things in the documentation while I had the patient open.

## Related Issues
 - Fixes https://github.com/flutter/flutter/issues/109847

## Tests
 - Documentation only.

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -2663,7 +2663,7 @@ class InputDecoration {
   /// When the [InputDecoration.labelText] is on top of the input field, the
   /// text uses the [labelStyle] instead.
   ///
-  /// If [floatingLabelStyle] is a [MaterialStateTextStyle], then the effective
+  /// If `floatingLabelStyle` is a [MaterialStateTextStyle], then the effective
```
Comment (darrenaustin) [inline packages/flutter/lib/src/material/input_decorator.dart:2666]: Is this is common pattern to use quotes for the currently described parameter instead of the link?

**Review by darrenaustin — APPROVED** [review]
LGTM. Thx.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/input_decorator.dart:2666]: Yes. https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#dartdoc-specific-requirements

Comment (darrenaustin) [reply packages/flutter/lib/src/material/input_decorator.dart:2666]: TIL, thx!
