### PR TITLE
Change text selection (or cursor position) via a11y

### LINKED ISSUE #13469: a11y: "Move cursor to beginning/end" doesn't work
On Android these actions are pre-populated in the local context menu (swipe up and left), but currently don't work.

### PR DESCRIPTION
**Pull request by goderbauer**
Rolls engine to 7c34dfafc9acece1a9438f206bfbb0a9bedba3bf.

Fixes flutter/flutter#13469.

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -3399,6 +3401,24 @@ class RenderSemanticsAnnotations extends RenderProxyBox {
       markNeedsSemanticsUpdate();
   }
 
+  /// The handler for [SemanticsActio.setSelection].
```
Comment (yjbanov) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: typo: SemanticsActio

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 2]
```diff
@@ -3399,6 +3401,24 @@ class RenderSemanticsAnnotations extends RenderProxyBox {
...
+  ///
+  /// This handler is invoked when the user either wants to change the currently
+  /// selected text in a text field or change the position of the cursor.
+  ///
+  /// TalkBack users can trigger this handler by selecting "Move cursor to
+  /// beginning/end" or "Select all" from the Local Context Menu.
```
Comment (yjbanov) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: nit: why capitalize "local context menu"?

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 3]
```diff
@@ -3399,6 +3401,24 @@ class RenderSemanticsAnnotations extends RenderProxyBox {
...
+  SetSelectionHandler get onSetSelection => _onSetSelection;
+  SetSelectionHandler _onSetSelection;
+  set onSetSelection(SetSelectionHandler handler) {
+    if (_onSetSelection == handler)
+      return;
+    final bool hadValue = _onSetSelection != null;
+    _onSetSelection = handler;
+    if ((handler != null) != hadValue)
```
Comment (yjbanov) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: nit: I'd create a variable `final bool hasValue = handler != null;` so the `if` expression is more clear.

**Review by yjbanov — APPROVED** [review]

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: Done. Also fixed in another file.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: Changed to lower-case.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: I left this one as is for now because all the other setters for the various handlers in this file follow the same pattern.
