### PR TITLE
Have android validator suggest ANDROID_SDK_ROOT instead of deprecated ANDROID_HOME

### LINKED ISSUE #39301: Doctor message mentiones deprecated ANDROID_HOME environment variable
## Steps to Reproduce

1. Install the Android SDK in a custom location.
2. Forget to set the `ANDROID_SDK_ROOT` environment variable.
3. Run `flutter doctor`.
4. It prints that `ANDROID_HOME` should be set. But that is [deprecated](https://developer.android.com/studio/command-line/variables.html) and `ANDROID_SDK_ROOT` should be set instead.

Note: Flutter already uses `ANDROID_SDK_ROOT` (since #25221). So it's just the doctor message that needs to be updated.

## Logs

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale de-AT)
    • Flutter version 1.7.8+hotfix.4 at C:\Android\flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

The `ANDROID_HOME` env var is deprecated (though we still check for it), and `ANDROID_SDK_ROOT` is preferred, though the doctor will currently recommending setting the former. This PR changes it to the latter, adds a test for it, and refactors the `AndroidValidator` class to use direct dependency injection (rather than context).

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39301

## Tests

I added the following tests:

* Added a new test verifying the correct env variable is suggested by the `AndroidValidator`
* Refactored `AndroidValidator` and all tests to use direct dependency injection

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by christopherfujino** [comment]
looks like I broke `test/general.shard/android/gradle_test.dart: gradle build do not crash if there is no Android SDK`

File: packages/flutter_tools/lib/src/android/android_workflow.dart [hunk 1]
```diff
@@ -108,72 +146,79 @@ class AndroidValidator extends DoctorValidator {
...
-        final String androidHomeDir = globals.platform.environment[kAndroidHome];
-        messages.add(ValidationMessage.error(userMessages.androidBadSdkDir(kAndroidHome, androidHomeDir)));
+      if (_platform.environment.containsKey(kAndroidHome)) {
+        final String androidHomeDir = _platform.environment[kAndroidHome];
+        messages.add(ValidationMessage.error(_userMessages.androidBadSdkDir(kAndroidHome, androidHomeDir)));
       } else {
-        messages.add(ValidationMessage.error(userMessages.androidMissingSdkInstructions(kAndroidHome)));
+        // Instruct user to set [kAndroidSdkRoot] and not deprecated [kAndroidHome]
+        // See https://github.com/flutter/flutter/issues/39301
+        messages.add(ValidationMessage.error(_userMessages.androidMissingSdkInstructions(kAndroidSdkRoot)));
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_workflow.dart]: This is the actual fix. The rest is context refactoring.

File: packages/flutter_tools/lib/src/android/android_sdk.dart [hunk 2]
```diff
@@ -549,20 +551,25 @@ class AndroidSdk {
   }
 
   /// First try Java bundled with Android Studio, then sniff JAVA_HOME, then fallback to PATH.
-  static String findJavaBinary() {
-    if (android_studio.javaPath != null) {
-      return globals.fs.path.join(android_studio.javaPath, 'bin', 'java');
+  static String findJavaBinary({
+    @required AndroidStudio androidStudio,
+    @required FileSystem fs,
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_sdk.dart]: I would use `fileSystem` as the parameter name instead of `fs` so that we don't accidentally confuse it with the global value

File: packages/flutter_tools/lib/src/android/android_sdk.dart [hunk 3]
```diff
@@ -549,20 +551,25 @@ class AndroidSdk {
...
+    @required OperatingSystemUtils os,
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_sdk.dart]: Same here with `os` -> `operatingSystemUtils`

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: Should we want people if they've set ANDROID_HOME instead of ANDROID_SDK_ROOT?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: I don't think it's necessary? According to the [original fix](https://github.com/flutter/flutter/pull/25221), we still check `ANDROID_HOME` because the SDK still does https://developer.android.com/studio/command-line/variables.

File: packages/flutter_tools/lib/src/android/android_sdk.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_sdk.dart]: done

File: packages/flutter_tools/lib/src/android/android_sdk.dart (hunk 3 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/android_sdk.dart]: done

File: packages/flutter_tools/lib/src/android/android_workflow.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/android_workflow.dart]: SGTM

**Review by jonahwilliams — APPROVED** [review]
Could you make the fileSystem and operatingSystemUtil renames across the diff?

Otherwise LGTM

**Comment by zanderso** [comment]
Commenting to link to https://github.com/flutter/flutter/issues/47161
