### PR TITLE
Dispose OverlayEntry in TooltipState. [prod-leak-fix]

### LINKED ISSUE #117063: ValueNotifier is not disposed by tooltip.
To repro, attach leak_tracker to the counter app.

```
flutter --version
Flutter 3.7.0-7.0.pre.8 • channel master • git@github.com:polina-c/flutter.git
Framework • revision cd9a439c35 (20 hours ago) • 2022-12-13 14:40:48 -0500
Engine • revision 9872cc7add
Tools • Dart 3.0.0 (build 3.0.0-19.0.dev) • DevTools 2.20.0
```

```
# For memory leaks troubleshooting tips see
# https://github.com/dart-lang/leak_tracker

not-disposed:
  total: 1
  objects:
    ValueNotifier<bool>:
      identityHashCode: 16539540
      context:
        start: >
          #0      ObjectTracker.startTracking (package:leak_tracker/src/_object_tracker.dart:63:64)
          #1      dispatchObjectEvent (package:leak_tracker/src/_dispatcher.dart:38:19)
          #2      dispatchObjectEvent (package:leak_tracker/src/leak_tracker.dart:71:14)
          #3      main.<anonymous closure> (package:leak_tracker_minimal_flutter_example/main.dart:12:43)
          #4      MemoryAllocations.dispatchObjectEvent (package:flutter/src/foundation/memory_allocations.dart:238:23)
          #5      MemoryAllocations.dispatchObjectCreated (package:flutter/src/foundation/memory_allocations.dart:272:5)
          #6      new ValueNotifier (package:flutter/src/foundation/change_notifier.dart:473:34)
          #7      new OverlayEntry (package:flutter/src/widgets/overlay.dart:138:52)
          #8      TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:608:14)
          #9      TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:552:5)
          #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
          #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
          #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
          #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

### PR DESCRIPTION
**Pull request by polina-c**
Part of the leak_tracker adoption plan: https://github.com/flutter/devtools/issues/3951

[freshest leak tracker README.md](https://github.com/dart-lang/leak_tracker/blob/e4edef3cfd431f8c438e6353194da0eba197e118/README.md)

Fixes: https://github.com/flutter/flutter/issues/117063

The test failures are time-outs, and pass locally, so it seems to be flakiness.

### CODE REVIEW

**Comment by polina-c** [comment]
Tests fail with message `Correct file names in gen_defaults.dart...`
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8794342412604377249/+/u/Analyze/analyze/test_stdout

**Comment by polina-c** [comment]
The test that fails, passes for me locally, for macos:
```
flutter test test/gestures/gesture_binding_resample_event_test.dart 
```
However, I failed to pass the parameter '-p chrome', that may be necessary to repro the failure.

**Comment by goderbauer** [comment]
I restarted the checks just to see if it maybe was just a flake.

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 1]
```diff
@@ -0,0 +1,47 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:1]: Why the `_` in the file name? Can we just rename that to `leak_tracking.dart`? Similarly to how we have `packages/flutter/test/widgets/semantics_tester.dart`, `packages/flutter/test/rendering/mock_canvas.dart` and other internal test utils?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+import 'package:leak_tracker/leak_tracker.dart';
+
+/// Wrapper for [withLeakTracking] with Flutter specific functionality.
+///
+/// 1. Listens to [MemoryAllocations] events.
+/// 2. Uses `tester.runAsync` for leak detection if [tester] is provided.
+///
+/// Copied from `psckage:leak_tracker/test/test_infra/flutter_helpers.dart`.
+///
+/// The method is not combined with [testWodgets], because the combining will
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:16]: typo:

```suggestion
/// The method is not combined with [testWidgets], because the combining will
```

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+import 'package:flutter/foundation.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:leak_tracker/leak_tracker.dart';
+
+/// Wrapper for [withLeakTracking] with Flutter specific functionality.
+///
+/// 1. Listens to [MemoryAllocations] events.
+/// 2. Uses `tester.runAsync` for leak detection if [tester] is provided.
+///
+/// Copied from `psckage:leak_tracker/test/test_infra/flutter_helpers.dart`.
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:14]: This shouldn't really be part of the doc comment, its more of an implementation detail.

Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:14]: This shouldn't really be part of the doc comment, its more of an implementation detail.

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 4]
```diff
@@ -0,0 +1,47 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:leak_tracker/leak_tracker.dart';
+
+/// Wrapper for [withLeakTracking] with Flutter specific functionality.
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:9]: The doc comment could be a little more comprehensive. Questions I have after reading this that I wish would be answered:
* What does this do on a high-level? What's the benefit of using this?
* How am I expected to use this function? 
* How do I make sure there are no leaks? 
* What happens if there are leaks detected?
* What is the Flutter specific functionality mentioned in the first sentence?
* What do all the method parameters mean? What should I pass in?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:14]: Also, typo in `psckage`

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+///
+/// The method is not combined with [testWodgets], because the combining will
+/// impact VSCode's ability to recognize tests.
+Future<void> withFlutterLeakTracking(
+  DartAsyncCallback callback, {
+  required WidgetTester? tester,
+  StackTraceCollectionConfig stackTraceCollectionConfig =
+      const StackTraceCollectionConfig(),
+  Duration? timeoutForFinalGarbageCollection,
+  void Function(Leaks foundLeaks)? leaksObtainer,
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:24]: per style guide, please use a typedef for this.

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+/// 1. Listens to [MemoryAllocations] events.
+/// 2. Uses `tester.runAsync` for leak detection if [tester] is provided.
+///
+/// Copied from `psckage:leak_tracker/test/test_infra/flutter_helpers.dart`.
+///
+/// The method is not combined with [testWodgets], because the combining will
+/// impact VSCode's ability to recognize tests.
+Future<void> withFlutterLeakTracking(
+  DartAsyncCallback callback, {
+  required WidgetTester? tester,
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:20]: Document: What does it mean to pass in null for the tester?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+///
+/// 1. Listens to [MemoryAllocations] events.
+/// 2. Uses `tester.runAsync` for leak detection if [tester] is provided.
+///
+/// Copied from `psckage:leak_tracker/test/test_infra/flutter_helpers.dart`.
+///
+/// The method is not combined with [testWodgets], because the combining will
+/// impact VSCode's ability to recognize tests.
+Future<void> withFlutterLeakTracking(
+  DartAsyncCallback callback, {
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:19]: DartAsyncCallback -> AsyncCallback to use Flutter's terminology here?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+  required WidgetTester? tester,
+  StackTraceCollectionConfig stackTraceCollectionConfig =
+      const StackTraceCollectionConfig(),
+  Duration? timeoutForFinalGarbageCollection,
+  void Function(Leaks foundLeaks)? leaksObtainer,
+}) async {
+  void flutterEventToLeakTracker(ObjectEvent event) =>
+      dispatchObjectEvent(event.toMap());
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:27]: per style guide: leave this on one line or don't use `=>` shorthand

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+      timeoutForFinalGarbageCollection: timeoutForFinalGarbageCollection,
+    );
+    if (leaksObtainer != null) {
+      leaksObtainer(leaks);
+    }
+    expect(leaks, isLeakFree);
+  } finally {
+    MemoryAllocations.instance.removeListener(flutterEventToLeakTracker);
+  }
+}
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:47]: Should this method be wrapped in `TestAsyncUtils.guard` (like `WidgetTester.pumpWidget` and friends)?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart [hunk 10]
```diff
@@ -0,0 +1,47 @@
...
+}) async {
+  void flutterEventToLeakTracker(ObjectEvent event) =>
+      dispatchObjectEvent(event.toMap());
+  MemoryAllocations.instance.addListener(flutterEventToLeakTracker);
+  final AsyncCodeRunner asyncCodeRunner = tester == null
+      ? (DartAsyncCallback action) async => action()
+      : (DartAsyncCallback action) async => tester.runAsync(action);
+  try {
+    final Leaks leaks = await withLeakTracking(
+      () async => callback(),
```
Comment (goderbauer) [inline packages/flutter/test/foundation/_with_flutter_leak_tracking.dart:34]: nit: do you need the extra closure here? Couldn't this just be

```suggestion
      callback,
```

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 4 above)
Comment (polina-c) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: Linked documentation in leak_tracker that partially covers the questions.
Can you approve: https://github.com/dart-lang/leak_tracker/pull/39

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 6 above)
Comment (polina-c) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: if you are not usi

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 7 above)
Comment (polina-c) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: It is defined in dart code. Flutter definition cannot be referenced. Do you suggest to cast callback before passing to dart method?

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 9 above)
Comment (polina-c) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: I reviewed documentation for this method, but it is not very clear what's the point. This line is sync. What is the danger?

Comment (goderbauer) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: Wrapping the entire body of withFlutterLeakTracking in that method would enforce that people have to await this method. If they don't and they start another async operation, an exception is thrown. Which I think is what we want?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/foundation/_with_flutter_leak_tracking.dart (hunk 9 above)
Comment (polina-c) [reply packages/flutter/test/foundation/_with_flutter_leak_tracking.dart]: done
