### PR TITLE
Tapping a ScrollView during overscroll got it stuck.

### LINKED ISSUE #8476: iOS Overscroll can get stuck
## Steps to Reproduce

On iOS:
1. Open the *Colors* demo in the gallery.
2. Scroll the view down until overscroll starts.
3. Let go and quickly (before the overscroll bounces back) tap the whitespace below the overscrolled view.

The view gets stuck overscrolled.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/8476

More detailed list of changes in this patch:

* Replaced the didTouch special logic with more generic logic that
  uses Activities instead. Now instead when you tap down the
  Scrollable calls `hold()` which begins a HoldScrollActivity which is
  a hybrid of DragScrollActivity and IdleScrollActivity and can be
  canceled. When you let go, it gets canceled and that goes ballistic.

* Make DragGestureRecognizer more aggressive about grabbing pointers,
  otherwise a second pointer in a situation with competing horizontal
  and vertical recognizers always gets taken by the other one.

* Fixed the _GestureSemantics widget to call the "down" callbacks so
  that it follows the same pattern as "real" interactions.

* Added tests for the above.

* Added a hashCode to ScrollActivity.toString (and subclasses).

* Added a toString to ScrollDragController, and include it in
  DragScrollActivity's toString.

* s/coorindator/coordinator/

* Add a comment in DragStartDetails to distinguish it from the
  otherwise identical DragDownDetails, so we're not tempted to merge
  them.

### CODE REVIEW

**Comment by abarth** [comment]
"a hybrid of DragStartDetails and IdleScrollActivity" ?

**Comment by Hixie** [comment]
DragScrollActivity and IdleScrollActivity, sorry

**Comment by Hixie** [comment]
(fixed message)

File: packages/flutter/lib/src/widgets/scroll_activity.dart [hunk 1]
```diff
@@ -149,6 +149,56 @@ class IdleScrollActivity extends ScrollActivity {
...
+///
+/// For the purposes of [ScrollNotification]s, this activity does not constitute
+/// scrolling, and does not prevent the user from interacting with the contents
+/// of the [Scrollable] (unlike when a drag has begun or there is a scroll
+/// animation underway).
+class HoldScrollActivity extends ScrollActivity implements ScrollHoldController {
+  /// Creates a scroll activity that does nothing.
+  HoldScrollActivity({
+    @required ScrollActivityDelegate delegate,
+    this.onHoldCanceled,
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/scroll_activity.dart]: For dragging, we put this callback on the controller rather than the activity.  Putting it on the activity looks cleaner.  I wonder if we can do that for dragging too.

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/widgets/scroll_activity.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/scroll_activity.dart]: In the drag case they have different lifetimes, unfortunately.
