### PR TITLE
Autocomplete Options Width

### LINKED ISSUE #78746: Autocomplete widget goes out of screen from right side
https://api.flutter.dev/flutter/material/Autocomplete-class.html

From the code on flutter doc, If you add padding to `AutocompleteBasicExample()` widget the autocomplete box goes outside the screen from the right side.

Untitled

Same issue In emulator

### LINKED ISSUE #92851: Proposal to add Option for RTL in _AutocompleteOptions
Currently, when using the Autocomplete widget, the autocomplete options are aligned to the left-hand side (even when wrapped in a Directionality), unless you explicitly use the optionsViewBuilder parameter to build your own right-aligned autocomplete option widget.
I think this can easily be fixed on [this line in src/material/autocomplete.dart](https://github.com/flutter/flutter/blob/2382b4c046623da0cfe9cc1cafc4ad8ea1b161e7/packages/flutter/lib/src/material/autocomplete.dart#L155)
Thanks so much!

### LINKED ISSUE #147483: `AutoComplete` `OptionsViewOpenDirection.up` positions does not work when custom `optionsViewBuilder` being passed
### Steps to reproduce

1. Copy & pasting the provided code
2. Then running the app

### Expected results

Even we use pass the custom options it should work normally.

### Actual results

Custom options does not show up. While `optionsViewBuilder` does get invoked. Added the print statement confirms that.

If we comment the below code the Custom Options does seems works normally as it open down.
```dart
optionsViewOpenDirection: OptionsViewOpenDirection.up,
```

### Code sample
<details open><summary></summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Autocomplete].

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                  'Type below to autocomplete the following possible results: ${AutocompleteBasicExample._kOptions}.'),
              const AutocompleteBasicExample(),
            ],
          ),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsViewOpenDirection: OptionsViewOpenDirection.up,
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
      optionsViewBuilder: (
        context,
        onSelected,
        options,
      ) {
        print(options.length);
        return CustomOptionsList(
          displayStringForOption: (prediction) {
            return prediction;
          },
        );
      },
    );
  }
}

class CustomOptionsList extends StatelessWidget {
  const CustomOptionsList({
    super.key,
    required this.displayStringForOption,
  });

  final String Function(String) displayStringForOption;

  @override
  Widget build(BuildContext context) {
    return Align(
        alignment: Alignment.topLeft,
        child: Material(
            elevation: 4,
            borderRadius: BorderRadius.circular(8),
            child: ConstrainedBox(
              constraints: const BoxConstraints(
                maxHeight: 200,
              ),
              child: ListView.builder(
                itemCount: AutocompleteBasicExample._kOptions.length,
                itemBuilder: (BuildContext context, int index) {
                  final String option =
                      AutocompleteBasicExample._kOptions[index];
                  return ListTile(
                    title: Text(displayStringForOption(option)),
                  );
                },
              ),
            )));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel beta, 3.22.0-0.3.pre, on Microsoft Windows [Version 10.0.22631.3447], locale en-IN)
    • Flutter version 3.22.0-0.3.pre on channel beta at C:\Users\harsh\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\harsh\fvm\versions\beta\bin\flutter, which is not inside your current Flutter SDK checkout at
      C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\harsh\fvm\versions\beta\bin\dart, which is not inside your current Flutter SDK checkout at
      C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87b652410d (4 days ago), 2024-04-23 21:41:18 -0500
    • Engine revision b4bfd45986
    • Dart version 3.4.0 (build 3.4.0-282.3.beta)
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\harsh\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.88.1)
    • VS Code at C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (1 available)
    • vivo 1907 (mobile) • 8TBYBE6H7H55USFE • android-arm64 • Android 12 (API 31)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### LINKED ISSUE #153274: OptionsViewOpenDirection.up in (Raw)AutoComplete makes the autocomplete list disappear.
### Steps to reproduce

The issue was already addressed (and purportedly resolved) in #138773, but is still reproducible in the exact same way with the latest stable flutter version, even in the online editor. I will add the same reproduction because the issue still persists.

1. Go to https://api.flutter.dev/flutter/material/Autocomplete-class.html
2. In any of the code samples, add optionsViewOpenDirection: OptionsViewOpenDirection.up, to the Autocomplete widget and click Run.
3. Type 'a' in the text field
4. No options show up
5. Change OptionsViewOpenDirection.up to OptionsViewOpenDirection.down, click Run again and type 'a' in the text field. It works.

### Expected results

The list with options appears above the textfield

### Actual results

Nothing appears

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [RawAutocomplete].

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('RawAutocomplete Basic'),
        ),
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _options = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return RawAutocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        return _options.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      fieldViewBuilder: (
        BuildContext context,
        TextEditingController textEditingController,
        FocusNode focusNode,
        VoidCallback onFieldSubmitted,
      ) {
        return TextFormField(
          controller: textEditingController,
          focusNode: focusNode,
          onFieldSubmitted: (String value) {
            onFieldSubmitted();
          },
        );
      },
      optionsViewOpenDirection: OptionsViewOpenDirection.up,
      optionsViewBuilder: (
        BuildContext context,
        AutocompleteOnSelected<String> onSelected,
        Iterable<String> options,
      ) {
        return Align(
          alignment: Alignment.topLeft,
          child: Material(
            elevation: 4.0,
            child: SizedBox(
              height: 200.0,
              child: ListView.builder(
                padding: const EdgeInsets.all(8.0),
                itemCount: options.length,
                itemBuilder: (BuildContext context, int index) {
                  final String option = options.elementAt(index);
                  return GestureDetector(
                    onTap: () {
                      onSelected(option);
                    },
                    child: ListTile(
                      title: Text(option),
                    ),
                  );
                },
              ),
            ),
          ),
        );
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-BE)
    • Flutter version 3.24.0 on channel stable at /Users/ghijs/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ghijs/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode 15.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • iPhone 15 (mobile)              • 5E510911-C117-479B-93E4-3F8281DA7A19 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-17-4
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 14.4.1 23E224 darwin-arm64
    ! Device emulator-5562 is offline.

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
| Problem | Before | After |
| --- | --- | --- |
| Width | Screenshot 2024-02-09 at 1 29 09 PM | Screenshot 2024-02-09 at 1 23 59 PM  |
| Overflow | Screenshot from 2024-06-07 13-39-45 | Screenshot from 2024-06-07 13-38-26  |

Fixes https://github.com/flutter/flutter/issues/78746
Fixes https://github.com/flutter/flutter/issues/92851
Part of https://github.com/flutter/flutter/issues/101620
Fixes https://github.com/flutter/flutter/issues/147483
Fixes https://github.com/flutter/flutter/issues/153274
Part of Google b/317115348
Fixes optionsViewOpenDirection not working, mentioned in https://github.com/flutter/flutter/pull/143249#issuecomment-2036191457.

### Requirements

 * [x] By default, the width of the options matches the width of the field.
 * [x] Options can be aligned to the start or end for LTR/RTL languages.
 * [x] The optionsViewOpenDirection parameter is respected.
 * [x] If the options would vertically exceed the top or bottom of the screen, they reposition themselves to fit on the screen while covering the field. At least enough to tap an option. This has accessibility implications, because sometimes an Autocomplete near the edge of a narrow screen can be unusable.
 * [x] If the Autocomplete is in a ScrollView, then the options move along with the field during scrolling.
 * [x] When the field moves or resizes, the options position and size change to match. Even if the field is animated.
 * [ ] The options layout updates on the same frame that the field layout changes.

It's probably not possible to check all of these boxes so we'll probably need to compromise.

 #### Tools that I've used to try to achieve this

 * LayoutBuilder to provide the field constraints[^1].
 * Looking up layout information of a widget via GlobalKey.
 * CompositedTransformFollower/Target.
 * CustomSingleChildLayout.

[^1]: Originally this didn't work due to a bug when using LayoutBuilder with OverlayPortal (https://github.com/flutter/flutter/pull/147856). That has now been fixed.

### CODE REVIEW

**Comment by justinmc** [comment]
@LongCatIsLooong Would something like this work in OverlayPortal? Or maybe better, `_optionsLayerLink.leaderSize.width`?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 1]
```diff
@@ -438,7 +438,20 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
         child: AutocompleteHighlightedOption(
           highlightIndexNotifier: _highlightedOptionIndex,
           child: Builder(
-            builder: (BuildContext context) => widget.optionsViewBuilder(context, _select, _options),
+            builder: (BuildContext context) {
+              final Widget options = widget.optionsViewBuilder(context, _select, _options);
+              final RenderBox? fieldRenderBox = _fieldKey.currentContext?.findRenderObject() as RenderBox?;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:443]: Is it guaranteed at this point that the render object is already laid out?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I was hoping you would know :) This method is the overlayChildBuilder of an OverlayPortal, and _fieldKey is in the `child` of the same OverlayPortal.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: If the sizing rule (`BoxConstraints` => `Size`) is known (in other words the child is sized by the parent) I think you could use a layout builder as the ancestor of the text field to get the size of the text field. Otherwise I think it's a bit trickier.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Done and it seems to work, thanks.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 2]
```diff
@@ -438,7 +440,16 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
           highlightIndexNotifier: _highlightedOptionIndex,
           child: Builder(
-            builder: (BuildContext context) => widget.optionsViewBuilder(context, _select, _options),
+            builder: (BuildContext context) {
+              return UnconstrainedBox(
+                constrainedAxis: Axis.vertical,
+                alignment: Alignment.topLeft,
+                child: SizedBox(
+                  width: _fieldBoxConstraints.maxWidth,
+                  child: widget.optionsViewBuilder(context, _select, _options),
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:449]: Question: Should I add a flag for this, or even pass the Size to the optionsViewBuilder and make users include the UnconstrainedBox and SizedBox? I figure most users do want this width-matching behavior, which is why I made it mandatory, but it could be a breaking change for some...

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 3]
```diff
@@ -300,10 +300,12 @@ class RawAutocomplete<T extends Object> extends StatefulWidget {
 }
 
 class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>> {
-  final GlobalKey _fieldKey = GlobalKey();
   final LayerLink _optionsLayerLink = LayerLink();
   final OverlayPortalController _optionsViewController = OverlayPortalController(debugLabel: '_RawAutocompleteState');
 
+  // The box constraints that the field was last built with.
+  late BoxConstraints _fieldBoxConstraints;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:307]: I'm surprised that no test caught this, but I think this will crash if the autocomplete widget is not in a layout builder. The `_fieldBoxConstraints` variable won't be assigned until the layout phase. 

As a workaround, putting the widget that takes that BoxConstraints in a layout builder will defer the evaluation of the late variable to the layout phase.

Overlay portal always lays out the `child` branch before the `overlayChild` branch so I think this should be safe (but I think the trick makes enough assumptions about layout builder's implementation and overlayportal's implementation, to merit throughout comments/testing)

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 4]
```diff
@@ -438,7 +440,16 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
         child: AutocompleteHighlightedOption(
           highlightIndexNotifier: _highlightedOptionIndex,
           child: Builder(
-            builder: (BuildContext context) => widget.optionsViewBuilder(context, _select, _options),
+            builder: (BuildContext context) {
+              return UnconstrainedBox(
+                constrainedAxis: Axis.vertical,
+                alignment: Alignment.topLeft,
```
Comment (gnprice) [inline packages/flutter/lib/src/widgets/autocomplete.dart:446]:
```suggestion
                alignment: followerAlignment,
```

This makes it vary properly with `optionsViewOpenDirection` and the ambient text direction.

(I think the vertical alignment doesn't affect anything because `constrainedAxis` means the heights should match anyway, so `optionsViewOpenDirection` would actually behave correctly anyway. RTL layout would be affected, though, whenever this alignment comes into play.)

**Review by gnprice — COMMENTED** [review]
Neat! Glad to see this.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: Here's my attempt: https://github.com/flutter/flutter/pull/143249/commits/49f98d6a00f9bae613c1c823f421177011c09519. Can you take a look at that and tell me if it's possible to get OverlayPortal to build `overlayChildBuilder` in the same frame as it builds `child`? I wasn't able to reproduce it, though I get what you're saying and it is worrying.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Good catch!

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:456]: Thanks for the analysis, I'm on board with this. I'll leave this as-is but add a TODO with a link to this thread if/when someone starts asking for it.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: Ah that probably doesn't work since the focus callback won't get called until the next microtask flush. If it's guaranteed that the options view won't show the same frame the field view shows, that should be safe (but `_fieldBoxConstraints` will still have a one frame delay).

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: Ok got it, I've removed the LayoutBuilder, the test, and adjusted my comments. I will keep an eye out though in case anyone runs into this.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: I think the layout builder is probably still needed. If the text field gets a set of different input constraints, then this variable is going to change, but nothing is telling the menu to resize if it's already open?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: Well I guess OverlayPortal needs a new constructor that takes a `overlayChildLayoutBuilder` which gives you the size of the child before you build the overlay child.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 5]
```diff
@@ -437,8 +439,23 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
       child: TextFieldTapRegion(
         child: AutocompleteHighlightedOption(
           highlightIndexNotifier: _highlightedOptionIndex,
-          child: Builder(
-            builder: (BuildContext context) => widget.optionsViewBuilder(context, _select, _options),
+          child: UnconstrainedBox(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:442]: Why the UnconstrainedBox? The overlay should be large enough to accommodate the menu I think?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:307]: (Because the text field itself may change size, e.g., when there's an animation that resizes it)

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:444]: Without that the width of the SizedBox is not respected and the options are always full width. I think being in an Overlay gives it weird constraints.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 6]
```diff
@@ -452,6 +465,9 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
                                                  ?? (_internalTextEditingController = TextEditingController.fromValue(widget.initialValue));
     initialController.addListener(_onChangedField);
     widget.focusNode?.addListener(_updateOptionsViewVisibility);
+    if (widget.focusNode?.hasFocus ?? false) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:468]: Is this still needed?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 7]
```diff
@@ -493,24 +509,83 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-              child: CompositedTransformTarget(
-                link: _optionsLayerLink,
-                child: fieldView,
+        // This LayoutBuilder ensures that _fieldBoxConstraints is assigned
+        // because its builder isn't called until the layout phase, and
+        // because OverlayPortal lays out its child before its
+        // overlayChildBuilder.
+        child: LayoutBuilder(
+          builder: (BuildContext context, BoxConstraints boxConstraints) {
+            _fieldBoxConstraints.value = boxConstraints;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:518]: If the input field has `textWidthBasis = TextWidthBasis.longestLine` (in which case the text field is not going to take the full available width) does this work still?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 8]
```diff
@@ -493,24 +509,83 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-        child: Container(
-          key: _fieldKey,
-          child: Shortcuts(
-            shortcuts: _shortcuts,
-            child: Actions(
-              actions: _actionMap,
-              child: CompositedTransformTarget(
-                link: _optionsLayerLink,
-                child: fieldView,
+        // This LayoutBuilder ensures that _fieldBoxConstraints is assigned
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:512]: If the options view is also in a layout builder I don't think the post-frame callback is needed?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:444]: That doesn't seem to work because of the CompositedTransformFollower widget. Without that Positioned does work like you said.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:444]: `Positioned` has to be placed as the root of the overlay child. I think the problem is the overlay is giving the overlay child tight constraints.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: No, good catch.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:509]: I get the "setState called during build" error if I remove it.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:515]: You're right, and this comment is making me realize that what we're doing here isn't matching the width of the field necessarily, it's just matching the width of the constraints given to the field. Here's a screenshot of your idea where yellow is the Autocomplete and blue is the EditableText:

Screenshot from 2024-02-28 15-59-18

It doesn't even need to be anything as fancy as TextWidthBasis; if you just hardcode the width of the field to something other than the constraints, then it's the same kind of result:

Screenshot from 2024-02-28 16-11-46

However, I think that's kind of the best that we can do. If users are sizing their text field in a weird way and they want the options to match that width, they'll need to look up its width using a GlobalKey and a post frame callback. Most people are probably doing that today without this PR.

My best guess is that giving the same constraints as the Autocomplete is probably what most users will want and expect.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Ah that worked, thanks.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Actually, with Positioned it was completely unconstrained in both directions, which caused layout errors in the options builder. I changed it to use ConstraintsTransformBox to just loosen the constraints in both directions, what do you think of that?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 8 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I think in that case the setState isn't necessary either. If the overlay portal and its child get a different BoxConstraints, the overlay child will relayout too. And the layout builder will rebuild. I think that happens in the same frame so it would work better than using a post frame callback.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Hmm it doesn't seem to work when I remove that. When the constraints change, the LayoutBuilder in OverlayPortal.child is called with the new constraints, but the overlayChildBuilder is not called.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Talked offline: I should try setting the width at the Positioned widget instead of below in a SizedBox.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 9]
```diff
@@ -491,18 +468,118 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+      OptionsViewOpenDirection.down => AlignmentDirectional.topStart,
+    }.resolve(textDirection);
+    final Alignment targetAnchor = switch (widget.openDirection) {
+      OptionsViewOpenDirection.up => AlignmentDirectional.topStart,
+      OptionsViewOpenDirection.down => AlignmentDirectional.bottomStart,
+    }.resolve(textDirection);
+
+    return Positioned(
+      width: widget.fieldBoxConstraints.value.maxWidth,
+      // TODO(justinmc): If I don't give a height, height constraints are
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:562]: IIRC the Overlay does not give its children unbounded constraints (it should at least be bounded by the physical size of the screen). Do you mean a tight height constraint or a loose height constraint?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:562]: Loose: 0.0<=h<=Infinity

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:562]: Without the Positioned widget the constraints are tight to the size of the screen.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:562]: Ahhh I see, for positioned children it's not bounded. But why didn't the options view child no like `0.0<=h<=Infinity`? Because it's using `Align` so it doesn't know how to vertically align with infinite amount of vertical space?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Thanks, that seems to work!

[The test that failed](https://github.com/flutter/flutter/blob/52961f761f80f602375dd8b7f3f08335d4166c66/packages/flutter/test/widgets/autocomplete_test.dart#L132) has a ListView in the optionsViewBuilder, which I think was the problem.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 8 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I was wrong about using a layout builder. If `child` gets a different set of constraints, the layout builder callback will be called with the new constraints. But overlay child is laid out using the Overlay's constraints so its layout builder won't be called.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 10]
```diff
@@ -491,18 +468,117 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
                           ?? const SizedBox.shrink();
     return OverlayPortal.targetsRootOverlay(
       controller: _optionsViewController,
-      overlayChildBuilder: _buildOptionsView,
+      overlayChildBuilder: (BuildContext context) {
+        return _OptionsView<T>(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:472]: Use a `ValueListenableBuilder` instead?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:472]: also consider adding an assert to verify the constraints is not unbounded.

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Thanks, I forgot ValueListenableBuilder was a thing. Much cleaner.

**Comment by justinmc** [comment]
I've tracked down the bug from the failing Google tests. Disposing the field's TextEditingController at the time that an option is selected results in:

```
The following assertion was thrown building RawGestureDetector(state:
RawGestureDetectorState#6436d(gestures: [tap, long press, tap and pan], excludeFromSemantics: true,
behavior: translucent)):
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.
```

The bug happens like this:

 1. An option is tapped, and the TextEditingController is modified with the new selected value.
 2. TextFormField calls setState due to the changed controller.
 3. The controller is disposed.
 4. TextFormField builds with the disposed controller.

The cause is the LayoutBuilder added in this PR. It delays the build until after the controller has been disposed but before it's been replaced.

I think the question is: Is this something that should work, or should we discourage messing with the controller like this? @LongCatIsLooong 

<details>

<summary>Full error</summary>

```
The following assertion was thrown building RawGestureDetector(state:
RawGestureDetectorState#6436d(gestures: [tap, long press, tap and pan], excludeFromSemantics: true,
behavior: translucent)):
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.

The relevant error-causing widget was:
  TextFormField
  TextFormField:file:///usr/local/google/home/jmccandless/Projects/issues/sandbox/lib/main.dart:57:16

When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:271:27)
#3      _MergingListenable.addListener (package:flutter/src/foundation/change_notifier.dart:499:14)
#4      _AnimatedState.didUpdateWidget (package:flutter/src/widgets/transitions.dart:118:25)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5659:55)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#17     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1021:21)
#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1388:15)
#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#50     _invoke (dart:ui/hooks.dart:312:13)
#51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#52     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>

<summary>Repro code </summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Padding(
                padding: EdgeInsets.symmetric(horizontal: 32.0),
                child: _MyAutocomplete(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _MyAutocomplete extends StatefulWidget {
  const _MyAutocomplete();

  @override
  State<_MyAutocomplete> createState() => _MyAutocompleteState();
}

class _MyAutocompleteState extends State<_MyAutocomplete> {
  final FocusNode focusNode = FocusNode();
  TextEditingController controller = TextEditingController(text: 'First text');

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return RawAutocomplete<String>(
      textEditingController: controller,
      focusNode: focusNode,
      fieldViewBuilder: (BuildContext buildContext, TextEditingController controller, FocusNode focusNode, VoidCallback onSubmitted) {
        debugPrint('fieldviewbuilder ${controller.isDisposed}');
        // TODO(justinmc): This must be TFF to reproduce, not TF, because TFF
        // listens to the controller and rebuilds if it changes.
        return TextFormField(
          controller: controller,
          focusNode: focusNode,
          onFieldSubmitted: (String value) => onSubmitted(),
        );
      },
      optionsViewBuilder: (BuildContext context, AutocompleteOnSelected<String> onSelected, Iterable<String> options) {
        return Column(
          children: <Widget>[
            ...options.map((String option) {
              return TextButton(
                onPressed: () {
                  onSelected(option);
                },
                child: Text(option),
              );
            }),
          ],
        );
      },
      optionsBuilder: (TextEditingValue textEditingValue) {
        return _kOptions;
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
        setState(() {
          controller.dispose();
          controller = TextEditingController(text: 'Last text');
        });
      },
    );
  }
}
```

</details>

**Comment by LongCatIsLooong** [comment]
Ah interesting. Sounds like the fieldViewBuilder does need to be in a LayoutBuilder?

**Comment by LongCatIsLooong** [comment]
> 3. The controller is disposed.
4. TextFormField builds with the disposed controller.
 
So the onSelect callback is called between, say, frame `n` and `n + 1`, and the controller is disposed,  then when we build the widget tree for frame `n + 1`:

`_MyAutocompleteState` should rebuild first, which rebuilds `RawAutocomplete`, and `RawAutocomplete`'s state should be using the new controller now. What am I missing?

**Comment by wmadden** [comment]
Any progress here? The Autocomplete widget isn't really usable as it is

**Comment by wmadden** [comment]
Incidentally, and I suppose this should be a separate bug ticket, the Autocomplete `optionsViewOpenDirection: OptionsViewOpenDirection.up` doesn't function at all because the options list is positioned way off the screen. Because of the same issue with the OverlayEntry.

You can reproduce using the live example on the Autocomplete docs page, just set `optionsViewOpenDirection` to up: https://api.flutter.dev/flutter/material/Autocomplete-class.html

**Comment by justinmc** [comment]
@wmadden You're right about the OptionsViewOpenDirection bug, can you open a separate issue? I'll investigate if this fix is related to whatever we should do to fix that bug too.

About your proposed solution, I believe it won't update the options when the size of the field changes. Also, using a GlobalKey to get the size of another widget requires that you wait until that widget has been laid out, so I think they would still be 1 frame delayed from each other (maybe not a terrible problem).

**Comment by justinmc** [comment]
I was just walking through this error with @LongCatIsLooong and wanted to post a summary of why it happens. Run the repro code and select an option, and this is the process of the bug happening:

 [1.](https://github.com/flutter/flutter/blob/4d1161b5912b200d3e57dbd7c4161b2a6b321d7b/packages/flutter/lib/src/widgets/autocomplete.dart#L386) RawAutocomplete updates the field's TextEditingController to the selected string.
 [2.](https://github.com/flutter/flutter/blob/4d1161b5912b200d3e57dbd7c4161b2a6b321d7b/packages/flutter/lib/src/widgets/autocomplete.dart#L390) It calls onSelected, which calls the repro code and disposes the controller:

```dart
setState(() {
  controller.dispose();
  controller = TextEditingController(text: 'Last text');
});
```

 [3.](https://github.com/flutter/flutter/blob/4d1161b5912b200d3e57dbd7c4161b2a6b321d7b/packages/flutter/lib/src/material/text_form_field.dart#L397) TextFormField, which has a listener on the disposed controller, causes itself to rebuild.

 [4.](https://github.com/flutter/flutter/blob/4d1161b5912b200d3e57dbd7c4161b2a6b321d7b/packages/flutter/lib/src/material/text_field.dart#L1535) When the underlying TextField also rebuilds, it ends up trying to add a listener on the disposed controller, which is what ultimately triggers the error in the stack trace.

**Comment by wmadden** [comment]
@justinmc I [opened a new issue](https://github.com/flutter/flutter/issues/146376) reporting the broken direction behavior ✅ 

> About your proposed solution, I believe it won't update the options when the size of the field changes. Also, using a GlobalKey to get the size of another widget requires that you wait until that widget has been laid out, so I think they would still be 1 frame delayed from each other (maybe not a terrible problem).

I'll defer to your judgement here - I'm sure you know more about this than I do. But in what real-world scenario would the TextField _not_ already be laid out by the time the menu is being drawn?

I noticed the `MenuAnchor` implementation uses a very different implementation to the `Autocomplete`. It doesn't use the `LayerLink` to position the menu, instead providing its own `CustomSingleChildLayoutDelegate`. As a result, it's capable of measuring the available space between the edges of the overlay layer and the edges of the anchor widget - something the AutoComplete layout logic currently lacks completely.

It looks like the AutoComplete's layout logic is missing a lot of edge cases - like opening upwards (:D), and like providing constraining the list widget's size to the available space. The Flutter team probably ought to consider a more complete solution and ideally it should share some layout logic with MenuAnchor since they're doing exactly the same thing.

I know this isn't directly helpful to solving your problem, but I hope it helps nonetheless :)

**Comment by justinmc** [comment]
Here is a repro case that has nothing to do with Autocomplete, to get to the root of the bug. I'm not sure if there is a bug that should be fixed here, or if Autocomplete should just work around it.

<details>

<summary>Repro code without Autocomplete</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            MyParentWidget(),
          ],
        ),
      ),
    );
  }
}

class MyParentWidget extends StatelessWidget {
  MyParentWidget({
    super.key,
  });

  final ValueNotifier<String> notifier = ValueNotifier<String>('one');

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        MyChildWidget(notifier: notifier),
        TextButton(
          onPressed: () {
            // When the value is changed, MyChildWidget is going to schedule a
            // build.
            notifier.value = 'two';
            // But then the notifier is disposed, so when MyChildWidget builds,
            // it will be building with a disposed notifier.
            notifier.dispose();
          },
          child: const Text('Click to cause bug'),
        ),
      ],
    );
  }
}

class MyChildWidget extends StatefulWidget {
  const MyChildWidget ({
    super.key,
    required this.notifier,
  });

  final ValueNotifier<String> notifier;

  @override
  State<MyChildWidget> createState() => _MyChildWidgetState();
}

class _MyChildWidgetState extends State<MyChildWidget> {
  int _numberOfTimesNotifierHasNotified = 0;

  @override
  void initState() {
    super.initState();

    widget.notifier.addListener(_handleNotifierChange);
  }

  @override
  void didUpdateWidget(MyChildWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.notifier != oldWidget.notifier) {
      oldWidget.notifier.removeListener(_handleNotifierChange);
      widget.notifier.addListener(_handleNotifierChange);
    }
  }

  @override
  void dispose() {
    widget.notifier.removeListener(_handleNotifierChange);
    super.dispose();
  }

  _handleNotifierChange() {
    setState(() {
      _numberOfTimesNotifierHasNotified += 1;
    });
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      // Listenable.merge will add a listener to widget.notifier, which is not
      // allowed on a disposed ValueNotifier.
      animation: Listenable.merge(<Listenable>[ widget.notifier ]),
      builder: (BuildContext context, Widget? child) {
        return Text('notifier is: ${widget.notifier.value} and has notified this many times: $_numberOfTimesNotifierHasNotified');
      },
    );
  }
}
```

</details>

**Comment by justinmc** [comment]
This PR is blocked on https://github.com/flutter/flutter/pull/147856. It's probably not worth it for me to find a workaround if that PR can be merged in the near future.

**Comment by justinmc** [comment]
The error mentioned in https://github.com/flutter/flutter/pull/143249#issuecomment-1992468754 seems to be fixed after https://github.com/flutter/flutter/issues/146379 was merged (using the LayoutBuilder approach). I'm hoping that the Google tests will work now, once I get this PR cleaned up.

**Comment by justinmc** [comment]
Looks like the Google test failure is legit. I've messed up the height of the options in some cases. I will try to reproduce it locally and do something to not cause that.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 11]
```diff
@@ -493,22 +506,124 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+    required this.fieldKey,
+    required Size? fieldSize,
+    required this.optionsViewOpenDirection,
+    required this.overlayContext,
+    required TextDirection? textDirection,
+  }) : fieldSize = fieldSize ?? Size.zero,
+       textDirection = textDirection ?? TextDirection.ltr;
+
+  /// The constraints of the field in [RawAutocomplete.fieldViewBuilder].
+  final BoxConstraints fieldBoxConstraints;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:543]: Why are the constraints still needed if you know the size of the field?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 12]
```diff
@@ -493,22 +506,124 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-          key: _fieldKey,
-          child: Shortcuts(
-            shortcuts: _shortcuts,
-            child: Actions(
-              actions: _actionMap,
-              child: CompositedTransformTarget(
-                link: _optionsLayerLink,
+        child: LayoutBuilder(
+          builder: (BuildContext context, BoxConstraints boxConstraints) {
+            assert(boxConstraints.hasBoundedWidth);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:511]: Are there guarantees that the incoming max width will be finite?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 13]
```diff
@@ -493,22 +506,124 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+  @override
+  Offset getPositionForChild(Size size, Size childSize) {
+    final Offset fieldOffset = _fieldOffset;
+    return Offset(
+      switch (textDirection) {
+        TextDirection.ltr => fieldOffset.dx,
+        TextDirection.rtl => fieldOffset.dx + fieldSize.width - childSize.width,
+      },
+      clampDouble(
+        switch (optionsViewOpenDirection) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:608]: nit: break up the big expression?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 14]
```diff
@@ -493,22 +506,124 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+        },
+        0.0,
+        max(0.0, size.height - childSize.height),
       ),
     );
   }
+
+  @override
+  bool shouldRelayout(_OptionsLayoutDelegate oldDelegate) {
+    // This class depends on the position of the field (_fieldOffset) in order
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:620]: That sounds like you should use `CompositeTransformFollower`?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 15]
```diff
@@ -419,29 +427,34 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-        child: AutocompleteHighlightedOption(
-          highlightIndexNotifier: _highlightedOptionIndex,
-          child: Builder(
-            builder: (BuildContext context) => widget.optionsViewBuilder(context, _select, _options),
+    return ValueListenableBuilder<BoxConstraints>(
+      valueListenable: _fieldBoxConstraints,
+      builder: (BuildContext context, BoxConstraints constraints, Widget? child) {
+        final RenderBox? fieldRenderBox = _fieldKey.currentContext?.findRenderObject() as RenderBox?;
+
+        return CustomSingleChildLayout(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:435]: The layout algorithm is basically:

 * The options should fit below or above the field.
 * If that space is smaller than a minimum value, the options should position themselves such that they don't extend beyond the edge of the screen even if they overlap the field.

It seemed to work pretty well with CustomSingleChildLayout. I just tried to refactor it to do the same thing with CompositedTransformFollower + Positioned + ConstrainedBoxes etc. and I'm struggling to get the constraints right. CompositedTransformFollower changes the constraints when I use followerAnchor.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 16]
```diff
@@ -300,8 +304,12 @@ class RawAutocomplete<T extends Object> extends StatefulWidget {
 }
 
 class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>> {
-  final GlobalKey _fieldKey = GlobalKey();
-  final LayerLink _optionsLayerLink = LayerLink();
+  final GlobalKey _fieldKey = GlobalKey(debugLabel: kReleaseMode ? null : 'AutocompleteFieldView');
+
+  // The box constraints that the field was last built with.
+  final ValueNotifier<BoxConstraints> _fieldBoxConstraints =
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:310]: Thank you for saving me from bugging @polina-c with another leak :blush:

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 12 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:511]: Not sure why I added that... I'll remove it and keep an eye out for problems with width.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 14 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:620]: See https://github.com/flutter/flutter/pull/143249#discussion_r1649449912

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 11 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:543]: You're right it's probably better to just make these constraints match the width of the field rather than the field's width constraints, I'll do that.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 15 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:435]: What if the widget is in a scrollview? The options view won't scroll with the text field in that case I think?

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:435]: Ah you're right. I'll try again with CompositedTransformFollower or maybe some combination of the two.

**Comment by justinmc** [comment]
Moving to draft until I have time to return to this.

**Comment by victorsanni** [comment]
The test `when field scrolled offscreen, options are hidden` passes on mobile but fails on desktop and web. I played around with DropdownMenu on web and macOS and realized that scrolling actions (with trackpad, mouse wheel, scrollbar) immediately close the options menu (but not on mobile in tests). So, in tests, if the options view is open, scrolled offscreen, and scrolled back until visible, it would still be open on mobile but not on desktop.

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 17]
```diff
@@ -2219,19 +2219,17 @@ void main() {
...
     expect(find.byKey(fieldKey), findsOneWidget);
-    expect(find.byKey(optionsKey), findsOneWidget);
 
-    // Jump to the end. Both are hidden again.
+    // Jump to the end. The field is hidden again.
     scrollController.jumpTo(2000.0);
     await tester.pumpAndSettle();
 
     expect(find.byKey(fieldKey), findsNothing);
-    expect(find.byKey(optionsKey), findsNothing);
```
Comment (gnprice) [inline packages/flutter/test/widgets/autocomplete_test.dart]: This makes the test less informative than it was. I see the reasoning at https://github.com/flutter/flutter/pull/143249#issuecomment-2415354930 ; but on mobile, we still want to make sure that the options get hidden, not only the field. With this line gone, the test wouldn't catch a regression where that stopped happening.

This also makes these last two checks incongruous with the rest of this test case, which consistently checks visibility of both the field and the options. That raises an eyebrow for anyone reading the test — they should figure something is up and wonder what it is.

I think a good solution for the issue described in that comment would be to have the options-are-visible check above be conditioned on defaultTargetPlatform, instead of being deleted, and to leave this options-are-hidden check in place.

(Alternatively, a good solution is to just leave this draft PR in the state that Justin left it in. It's been a complicated area, and there are still changes he'll need to make that are bigger than this test case. It's fine and normal that a draft PR has some tests failing.)

Comment (victorsanni) [reply packages/flutter/test/widgets/autocomplete_test.dart]: I agree. I was considering making it conditional, but I left the comment to get others opinions on it.

I'm taking over the PR from @justinmc to drive it to completion.

Comment (gnprice) [reply packages/flutter/test/widgets/autocomplete_test.dart]: Sounds good. Glad to hear you'll be getting the PR finished!

**Comment by victorsanni** [comment]
These are my findings from investigating the customer testing failures.

- When the tests run, the options view opens upwards, showing the right options.
- When any option is tapped, a warning that the widget at that offset cannot be hit-tested is thrown.
- Changing the underlying `RawAutocomplete`'s `optionsViewOpenDirection` to `.down` instead of the current `.up` makes it so that the options view opens downwards instead of upwards, but no warning is thrown and the tests all pass.

@gnprice @justinmc @LongCatIsLooong do you have any insights as to why this is happening w.r.t the changes in this PR?

**Comment by victorsanni** [comment]
> These are my findings from investigating the customer testing failures.
> 
> * When the tests run, the options view opens upwards, showing the right options.
> * When any option is tapped, a warning that the widget at that offset cannot be hit-tested is thrown.
> * Changing the underlying `RawAutocomplete`'s `optionsViewOpenDirection` to `.down` instead of the current `.up` makes it so that the options view opens downwards instead of upwards, but no warning is thrown and the tests all pass.


I can also reproduce this in the RawAutocomplete tests. Take the test `tapping on an option selects it` in `RawAutocomplete`, wrap the RawAutocomplete in a Center, and change its optionsViewOpenDirection to .up, and the test fails even though there is as much space above the field as below.

<details>
<summary>Sample code</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  const List<String> kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
    'dingo',
    'elephant',
    'flamingo',
    'goose',
    'hippopotamus',
    'iguana',
    'jaguar',
    'koala',
    'lemur',
    'mouse',
    'northern white rhinoceros',
  ];

  testWidgets('tapping on an option selects it', (WidgetTester tester) async {
    final GlobalKey fieldKey = GlobalKey();
    final GlobalKey optionsKey = GlobalKey();
    late Iterable<String> lastOptions;
    late FocusNode focusNode;
    late TextEditingController textEditingController;

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Column(
            children: [
              Container(height: 100),
              RawAutocomplete<String>(
                optionsViewOpenDirection: OptionsViewOpenDirection.up,
                optionsBuilder: (TextEditingValue textEditingValue) {
                  return kOptions.where((String option) {
                    return option.contains(textEditingValue.text.toLowerCase());
                  });
                },
                fieldViewBuilder: (BuildContext context, TextEditingController fieldTextEditingController, FocusNode fieldFocusNode, VoidCallback onFieldSubmitted) {
                  focusNode = fieldFocusNode;
                  textEditingController = fieldTextEditingController;
                  return TextField(
                    key: fieldKey,
                    focusNode: focusNode,
                    controller: textEditingController,
                  );
                },
                optionsViewBuilder: (BuildContext context, AutocompleteOnSelected<String> onSelected, Iterable<String> options) {
                  lastOptions = options;
                  return Material(
                    elevation: 4.0,
                    child: ListView.builder(
                      key: optionsKey,
                      padding: const EdgeInsets.all(8.0),
                      itemCount: options.length,
                      itemBuilder: (BuildContext context, int index) {
                        final String option = options.elementAt(index);
                        return GestureDetector(
                          onTap: () {
                            onSelected(option);
                          },
                          child: ListTile(
                            title: Text(option),
                          ),
                        );
                      },
                    ),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );

    // The field is always rendered, but the options are not unless needed.
    expect(find.byKey(fieldKey), findsOneWidget);
    expect(find.byKey(optionsKey), findsNothing);

    // Tap on the text field to open the options.
    await tester.tap(find.byKey(fieldKey));
    await tester.pump();
    expect(find.byKey(optionsKey), findsOneWidget);
    expect(lastOptions.length, kOptions.length);

    await tester.tap(find.text(kOptions[2]));
    await tester.pump();

    expect(find.byKey(optionsKey), findsNothing);

    expect(textEditingController.text, equals(kOptions[2]));
  });
}
```

</details>

**Comment by dikatok** [comment]
@justinmc Hey, are you still working on this PR? I am fixing a similar issue in which the suggestion overlay overflows behind the soft keyboard, and apparently I can use it to fix the width issue as well. Would you mind taking a look at the PR when it is up?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 18]
```diff
@@ -302,8 +308,14 @@ class RawAutocomplete<T extends Object> extends StatefulWidget {
 }
 
 class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>> {
-  final GlobalKey _fieldKey = GlobalKey();
   final LayerLink _optionsLayerLink = LayerLink();
+  final GlobalKey _fieldKey = GlobalKey(debugLabel: kReleaseMode ? null : 'AutocompleteFieldView');
+
+  // TODO(justinmc): Maybe no longer needed?
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/autocomplete.dart:314]: Should this comment be removed?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 19]
```diff
@@ -302,8 +308,14 @@ class RawAutocomplete<T extends Object> extends StatefulWidget {
...
+  // The box constraints that the field was last built with.
+  final ValueNotifier<BoxConstraints> _fieldBoxConstraints =
+      ValueNotifier<BoxConstraints>(const BoxConstraints());
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/autocomplete.dart:317]:
```suggestion
  final ValueNotifier<BoxConstraints> _fieldBoxConstraints = ValueNotifier<BoxConstraints>(const BoxConstraints());
```

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 20]
```diff
@@ -620,21 +815,71 @@ void main() {
...
       alignment = Alignment.topCenter;
     });
     await tester.pump();
-    fieldOffset = tester.getTopLeft(find.byKey(fieldKey));
-    final Offset optionsOffsetOpen = tester.getTopLeft(find.byKey(optionsKey));
-    expect(optionsOffsetOpen.dy, isNot(equals(optionsOffset.dy)));
-    expect(optionsOffsetOpen.dy, fieldOffset.dy + fieldSize.height);
+    final Offset fieldOffsetFrame1 = tester.getTopLeft(find.byKey(fieldKey));
+    final Offset optionsTopLeftOpenFrame1 = tester.getTopLeft(find.byKey(optionsKey));
+    // TODO(justinmc): The options don't move when alignment changes like this :(
```
Comment (victorsanni) [inline packages/flutter/test/widgets/autocomplete_test.dart:831]: Is this comment still applicable?

**Review by victorsanni — APPROVED** [review]

**Comment by victorsanni** [comment]
Google testing image diffs are expected.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 18 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:314]: It looks like the value of _fieldBoxConstraints is never read, but maybe it's still needed to trigger a rebuild in the options view when the field layout changes? Can you try removing it and see if it breaks anything?

File: packages/flutter/test/widgets/autocomplete_test.dart (hunk 20 above)
Comment (justinmc) [reply packages/flutter/test/widgets/autocomplete_test.dart:831]: It looks like this test passes, so the comment can be removed :+1:

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 21]
```diff
@@ -489,10 +621,67 @@ void main() {
         ),
       );
       await tester.showKeyboard(find.byType(TextField));
+      await tester.pump();
       expect(tester.getTopLeft(find.byType(TextField)),
         offsetMoreOrLessEquals(tester.getBottomLeft(find.text('a'))));
     });
 
+    for (final OptionsViewOpenDirection direction in OptionsViewOpenDirection.values) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/widgets/autocomplete_test.dart:629]: Probably ok as-is after reading through all of this but up to you.

**Review by justinmc — COMMENTED** [review]
LGTM with nits :+1: (it won't let me actually approve my own PR). Thank you for helping me out with this PR! The Google failures look like just a handful of acceptable goldens right?

It looks to me like all of the requirements in the PR description are met and tested, except that the options render 1 frame late. I think that is a good compromise to make. Can you double confirm that all of those cases work and have a test?

**Comment by justinmc** [comment]
@LongCatIsLooong Could you re-review this since you reviewed it before?

**Comment by victorsanni** [comment]
> The Google failures look like just a handful of acceptable goldens right?

And some failing tests for which I have prepared a fix.

> It looks to me like all of the requirements in the PR description are met and tested, except that the options render 1 frame late. I think that is a good compromise to make. Can you double confirm that all of those cases work and have a test?

Yep, confirmed. And is why I've checked the applicable boxes in the PR description.

**Review by gnprice — COMMENTED** [review]
Thanks @victorsanni for picking this up and driving it forward again!

I've read through the whole diff in lib/; comments below.

I still have hope that we can solve this without the one-frame delay. But if the idea below doesn't work, I agree that's an acceptable compromise.

Other than that the comments are mostly some areas I think can be made clearer, and one or two edge cases that may be buggy.

**Comment by gnprice** [comment]
Looking back at the (updated) description: that is a long list of fixed issues! :tada: 

Does this really fix #101620? As I understand it, in a situation like https://github.com/flutter/flutter/issues/101620#issuecomment-1286576417 this would just cause the options view to be very small so it fits below the field; and if the field were still closer to the bottom then it would give the options view a minimal height and let it obscure the field in order to stay on the screen.

But what that issue is asking for is that in that situation the `Autocomplete` would automatically detect that the field is (a lot) closer to the bottom than to the top and would place the options above the field, where there's plenty of room for them. IIUC this PR doesn't do that (which is fine — it's doing plenty as it is!), so should leave that issue open.

**Comment by nate-thegrate** [comment]
> (@nate-thegrate re [#143249 (comment)](https://github.com/flutter/flutter/pull/143249#event-15290736523) : what I learned at [#143249 (comment)](https://github.com/flutter/flutter/pull/143249#discussion_r1853414759) makes a good example of why for a PR with a complex history like this one it's helpful to push only new commits on top, merging from main when needed, instead of rebasing and force-pushing. Though I see our docs at https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#using-git recommend the opposite ¯\\\_(ツ)\_/¯ )

Good to know! My understanding has been that Google Testing behaves differently based on which commits from master are present in the PR's branch and can have a hard time understanding merge commits, i.e. we should rebase when it fails.

Does anyone understand why Google Testing is passing for this PR? Perhaps we could update the [Tree Hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#using-git) page based on new info.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 22]
```diff
@@ -526,6 +640,87 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+      OptionsViewOpenDirection.down => origin + fieldSize!.height,
+      OptionsViewOpenDirection.up => origin - childSize.height,
+    };
+    final double maxDy = max(origin, origin + size.height - childSize.height - fieldOffset!.dy);
+    return Offset(
+      switch (textDirection) {
+        TextDirection.ltr => 0.0,
+        TextDirection.rtl => fieldSize!.width - childSize.width,
+      },
+      clampDouble(dy, origin - fieldOffset!.dy, maxDy),
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: In the first case (`.up` open direction):

> what if childSize.height is bigger than size.height itself?

In the `.up` open direction, the value of childSize.height is clamped to `fieldOffset.dy`, and the value of `size.height` is clamped to `constraints.maxHeight` (I think), so childSize.height < size.height.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 23]
```diff
@@ -526,6 +640,87 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+      // The field width may be zero if this is a split RawAutocomplete with no
+      // field of its own. In that case, don't change the constraints width.
+      maxWidth: fieldSize!.width == 0.0 ? constraints.maxWidth : fieldSize!.width,
+      maxHeight: switch (optionsViewOpenDirection) {
+        OptionsViewOpenDirection.down => max(
+          min(kMinInteractiveDimension, constraints.maxHeight),
+          constraints.maxHeight - fieldOffset!.dy - fieldSize!.height,
+        ),
+        OptionsViewOpenDirection.up => max(kMinInteractiveDimension, fieldOffset!.dy),
+      },
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:685]: > Or can the region that this overlay is operating in be potentially only part of the space that the global coordinate system covers?

I'm thinking of a case where this might be true, but nothing comes to mind.

> If the latter is possible, I think we should be able to fix it by passing an appropriate ancestor parameter to localToGlobal.

Is it okay to use the Overlay renderbox as the ancestor? Since that is the only common ancestor of the field and options view that we can access?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 24]
```diff
@@ -526,6 +640,87 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+  // Positions the child above/below the field and aligned with the left/right
+  // side based on text direction.
+  @override
+  Offset getPositionForChild(Size size, Size childSize) {
+    // shouldRelayout prevents this from being called if fieldOffset or
+    // fieldSize are invalid.
+    assert(fieldSize != null && fieldSize!.isFinite);
+    assert(fieldOffset != null && fieldOffset!.isFinite);
+
+    final double origin = size.height / 2 - fieldSize!.height / 2;
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I see. Does this fully solve that problem, though? What if the options list is tall, like more than half the height of the screen — will that cause the top of the list to extend up beyond the bounds of the parent?

Conversely, if the open direction is .down, it seems like this would cause a tall options list to extend down beyond the bounds of the parent, so that the items in the bottom half of the list couldn't be hit.

I think an alternate solution would be to have the `targetAnchor` and `followerAnchor` depend on the open direction, similar to how they do in main.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 25]
```diff
@@ -302,8 +309,12 @@ class RawAutocomplete<T extends Object> extends StatefulWidget {
 }
 
 class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>> {
-  final GlobalKey _fieldKey = GlobalKey();
   final LayerLink _optionsLayerLink = LayerLink();
+  final GlobalKey _fieldKey = GlobalKey(debugLabel: kReleaseMode ? null : 'AutocompleteFieldView');
+
+  // The box constraints that the field was last built with.
+  final ValueNotifier<BoxConstraints> _fieldBoxConstraints = ValueNotifier<BoxConstraints>(const BoxConstraints());
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I think both those steps are right, and what's needed is just to propagate the new type a bit further, following the type errors. This passes the analyzer:
```diff
--- packages/flutter/lib/src/widgets/autocomplete.dart
+++ packages/flutter/lib/src/widgets/autocomplete.dart
@@ -314,3 +314,3 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
   /// The box constraints that the field was last built with.
-  final ValueNotifier<BoxConstraints> _fieldBoxConstraints = ValueNotifier<BoxConstraints>(const BoxConstraints());
+  final ValueNotifier<BoxConstraints?> _fieldBoxConstraints = ValueNotifier<BoxConstraints?>(null);
 
@@ -446,5 +446,5 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
   Widget _buildOptionsView(BuildContext context) {
-    return ValueListenableBuilder<BoxConstraints>(
+    return ValueListenableBuilder<BoxConstraints?>(
       valueListenable: _fieldBoxConstraints,
-      builder: (BuildContext context, BoxConstraints constraints, Widget? child) {
+      builder: (BuildContext context, BoxConstraints? constraints, Widget? child) {
         return _RawAutocompleteOptions(
```

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 26]
```diff
@@ -508,16 +512,126 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+    return CompositedTransformFollower(
+      link: widget.optionsLayerLink,
+      targetAnchor: Alignment.centerLeft,
+      followerAnchor: Alignment.centerLeft,
+      // When the field goes offscreen, don't show the options.
+      showWhenUnlinked: false,
+      child: CustomSingleChildLayout(
+        delegate: _OptionsLayoutDelegate(
+          fieldSize: widget.optionsLayerLink.leaderSize,
+          fieldOffset: fieldOffset,
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Hmm. Is that from using the RenderBox's `size` getter directly? What if the layout delegate gets passed the `LayerLink`, and looks at `leaderSize` on that, the same way the current revision does in the build method?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 24 above)
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: > I see. Does this fully solve that problem, though? What if the options list is tall, like more than half the height of the screen — will that cause the top of the list to extend up beyond the bounds of the parent?

Yes, this is true. When I place the field at the top edge of the viewport and add a long list of options, latter options aren't hit-tested.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 22 above)
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: The revised version is indeed much clearer!

> what if `childSize.height` is bigger than `size.height` itself? I think that's currently possible in this version.

Specifically it looks like this can happen if `size.height` (which is the same as the `constraints.maxHeight` seen by `getConstraintsForChild`) is less than kMinInteractiveDimension. See my comment at https://github.com/flutter/flutter/pull/143249#discussion_r1853367043 .

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 27]
```diff
@@ -526,6 +640,87 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+    final double dy = switch (optionsViewOpenDirection) {
+      OptionsViewOpenDirection.down => origin + fieldSize!.height,
+      OptionsViewOpenDirection.up => origin - childSize.height,
+    };
+    final double maxDy = max(origin, origin + size.height - childSize.height - fieldOffset!.dy);
+    return Offset(
+      switch (textDirection) {
+        TextDirection.ltr => 0.0,
+        TextDirection.rtl => fieldSize!.width - childSize.width,
+      },
```
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart:704]: Well, do we need `fieldOffset` at all? The options get aligned to the field vertically by the same mechanism that aligns them horizontally:
```dart
    return CompositedTransformFollower(
      link: widget.optionsLayerLink,
      targetAnchor: Alignment.centerLeft,
      followerAnchor: Alignment.centerLeft,
```

So if that alignment already guarantees how this render object's coordinate system will relate to the field, then we shouldn't need `fieldOffset` at all. (The centering means that the y-offset will depend on `size` and `fieldSize`, but we have those and indeed the current version of the PR already does that calculation.)

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 23 above)
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart:684]: > to use the Overlay renderbox as the ancestor? Since that is the only common ancestor of the field and options view that we can access?

Using a known common ancestor like that sounds great.

The offset we get will then be relative to the Overlay's coordinate system. So we're assuming that that's the same coordinate system this render box is working in, modulo any adjustments we make explicitly like `verticalOffset`. That sounds right but I haven't looked into Overlay and OverlayPortal enough to be confident of it.


> Or can the region that this overlay is operating in be potentially only part of the space that the global coordinate system covers?

It looks like the one place within the framework that constructs an Overlay is in the Navigator build method.

So I think this sort of situation can happen if there's a Navigator that doesn't occupy the whole screen (or more precisely, whole `View`). This could happen if for some reason someone makes a WidgetsApp that's only part of the screen. There are also a couple of other spots that make a Navigator, like TabView, and it seems entirely reasonable that someone could have a TabView that's only part of the screen; or someone could use Navigator for a custom thing and have it not occupy the whole screen.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 26 above)
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Will try that. Although the API docs for LayerLink.leaderSize does not look encouraging:

```
  /// Generally this should be set by the [RenderObject] that paints on the
  /// registered [LeaderLayer] (for instance a [RenderLeaderLayer] that shares
  /// this link with its followers). This size may be outdated before and during
  /// layout.
```

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:714]: As we are no longer centering, do we still need `fieldOffset`?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 24 above)
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: This is fixed now! The follower is always anchored to the top left of the target, but in the `.up` open direction its bottom left is anchored while in the `.down` direction its top left is anchored.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 26 above)
[the remark this answers is not in the document]
Comment (gnprice) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I think that's fine — it should be set by the leader (the RenderLeaderLayer) during its own layout, which should happen before the follower's layout.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 28]
```diff
@@ -508,16 +511,130 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+
+  // Get the field offset if the field's position changes when its layer tree
+  // is composited, which occurs for example if the field is in a scroll view.
+  Offset _getFieldOffset() {
+    final RenderBox? fieldRenderBox = widget.fieldKey.currentContext?.findRenderObject() as RenderBox?;
+    final RenderBox? overlay = Overlay.of(widget.overlayContext).context.findRenderObject() as RenderBox?;
+    return fieldRenderBox?.localToGlobal(Offset.zero, ancestor: overlay) ?? Offset.zero;
+  }
+
+  void _onLeaderComposition(Layer leaderLayer) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:579]: Since we are already doing delayed layout using composite callbacks, can we remove the `CompositedTransformFollower`?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 29]
```diff
@@ -508,16 +511,130 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+  Widget build(BuildContext context) {
+    return CompositedTransformFollower(
+      link: widget.optionsLayerLink,
+      followerAnchor: switch (widget.optionsViewOpenDirection) {
+        OptionsViewOpenDirection.up => Alignment.bottomLeft,
+        OptionsViewOpenDirection.down => Alignment.topLeft,
+      },
+      // When the field goes offscreen, don't show the options.
+      showWhenUnlinked: false,
+      child: CustomSingleChildLayout(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:624]: Is the CustomSingleChildLayout needed? This is on an Overlay where you can use `Positioned` I think?

**Review by LongCatIsLooong — COMMENTED** [review]
Now that I think about it, you may not need the post frame callback for retrieving the size of the RenderBox produced by `OverlayPortal.child`: I think you might be able to get the render box using a global key and access the size from within a `LayoutBuilder`?

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 28 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:579]: I think so. You can compute the offset in the composition callback and adjust that in the next frame (I think this change is already doing that?).

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:579]: (following from offline) Keeping the `CompositedTransformFollower` since we want the options to strictly follow the field.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 30]
```diff
@@ -526,6 +643,96 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+      switch (textDirection) {
+        TextDirection.ltr => 0.0,
+        TextDirection.rtl => fieldSize!.width - childSize.width,
+      },
+      switch (optionsViewOpenDirection) {
+        OptionsViewOpenDirection.down => min(
+          fieldSize!.height,
+          size.height - childSize.height - fieldOffset!.dy,
+        ),
+        OptionsViewOpenDirection.up => size.height - min(childSize.height, fieldOffset!.dy),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:718]: why's the size still relevant for `.up`?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 31]
```diff
@@ -526,6 +643,96 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+  // Positions the child above/below the field and aligned with the left/right
+  // side based on text direction.
+  @override
+  Offset getPositionForChild(Size size, Size childSize) {
+    // shouldRelayout prevents this from being called if fieldOffset or
+    // fieldSize are invalid.
+    assert(fieldSize != null && fieldSize!.isFinite);
+    assert(fieldOffset != null && fieldOffset!.isFinite);
+
+    return Offset(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:708]: Break up the large expression for readability.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 32]
```diff
@@ -526,6 +643,96 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+  }
+
+  // Positions the child above/below the field and aligned with the left/right
+  // side based on text direction.
+  @override
+  Offset getPositionForChild(Size size, Size childSize) {
+    // shouldRelayout prevents this from being called if fieldOffset or
+    // fieldSize are invalid.
+    assert(fieldSize != null && fieldSize!.isFinite);
+    assert(fieldOffset != null && fieldOffset!.isFinite);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:706]: Consider checking this in the constructor.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:706]: Also why are they types nullable when there are non-null runtime checks everywhere?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 33]
```diff
@@ -508,16 +511,130 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+
+class _RawAutocompleteOptionsState extends State<_RawAutocompleteOptions> {
+  VoidCallback? removeCompositionCallback;
+  Offset fieldOffset = Offset.zero;
+
+  // Get the field offset if the field's position changes when its layer tree
+  // is composited, which occurs for example if the field is in a scroll view.
+  Offset _getFieldOffset() {
+    final RenderBox? fieldRenderBox = widget.fieldKey.currentContext?.findRenderObject() as RenderBox?;
+    final RenderBox? overlay = Overlay.of(widget.overlayContext).context.findRenderObject() as RenderBox?;
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:575]: It's only useful to pass the appropriate overlay ancestor to the localToGlobal function as per this comment: https://github.com/flutter/flutter/pull/143249#discussion_r1853367165

Do you think the tradeoff for the edge case in this comment: https://github.com/flutter/flutter/pull/143249#discussion_r1857517176 is worth the expense?

[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:575]: We'll see if this is prohibitively expensive (probably not on most devices). If it is then we can revert / fix-forward.

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 34]
```diff
@@ -185,20 +204,386 @@ void main() {
...
+      expect(find.byKey(fieldKey), findsOneWidget);
+      expect(find.byKey(optionsKey), findsOneWidget);
+
+      switch (openDirection) {
+        case OptionsViewOpenDirection.up:
+          // Options are positioned as high as possible while still fitting on
+          // the screen.
+          expect(find.byType(InkWell), findsNWidgets(1));
+          final Size optionsSize = tester.getSize(find.byKey(optionsKey));
+          expect(optionsSize.height, kMinInteractiveDimension);
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/test/widgets/autocomplete_test.dart:447]: For clamping to `kMinInteractiveDimension`, isn't `.down` tested from line 404 and `.up` tested here?

**Comment by victorsanni** [comment]
Seems like this is ready to merge... unless there are any objections? @gnprice @justinmc @LongCatIsLooong

**Review by justinmc — COMMENTED** [review]
LGTM 👍 (though I can't actually approve since I partially authored this PR). Thanks everyone for all of the great feedback on this PR and @victorsanni for putting together the final solution.

Did you verify that b/317115348 is fixed with this change?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 35]
```diff
@@ -508,16 +511,130 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
           key: _fieldKey,
-          child: Shortcuts(
-            shortcuts: _shortcuts,
-            child: Actions(
-              actions: _actionMap,
-              child: CompositedTransformTarget(
-                link: _optionsLayerLink,
-                child: fieldView,
+          builder: (BuildContext context, BoxConstraints constraints) {
+            // A post frame callback is used to get the field constraints so
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:517]: This doesn't really explain why the post frame callback is added right? Can you expand this a bit?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 36]
```diff
@@ -526,6 +643,84 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
+class _RawAutocompleteOptionsLayoutDelegate extends SingleChildLayoutDelegate {
+  _RawAutocompleteOptionsLayoutDelegate({
+    required this.fieldSize,
+    required this.fieldOffset,
+    required this.optionsViewOpenDirection,
+    required TextDirection? textDirection,
+  }) : textDirection = textDirection ?? TextDirection.ltr;
+
+  /// The size of the field in [RawAutocomplete.fieldViewBuilder].
+  final Size? fieldSize;
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:656]: `fieldSize` is null when `optionsLayerLink.leaderSize` is null. But I wonder what circumstances would cause this to happen.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 35 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: Is this more descriptive?

```
            // The options view is not in the same subtree as the field view, so
            // when the field constraints change, the options view can't be
            // rebuilt in the same frame.
```

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: Uhh could you remind me what error messages you would get, if this does not happen in a post frame callback?

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: Not an error, just a no-op, when the field changes width the options remains the same as before unless you hot reload.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: I mean if you update _fieldBoxConstraints without the post frame callback.

**Comment by justinmc** [comment]
> > (@nate-thegrate re [#143249 (comment)](https://github.com/flutter/flutter/pull/143249#event-15290736523) : what I learned at [#143249 (comment)](https://github.com/flutter/flutter/pull/143249#discussion_r1853414759) makes a good example of why for a PR with a complex history like this one it's helpful to push only new commits on top, merging from main when needed, instead of rebasing and force-pushing. Though I see our docs at https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#using-git recommend the opposite ¯\_(ツ)_/¯ )
> 
> Good to know! My understanding has been that Google Testing behaves differently based on which commits from master are present in the PR's branch and can have a hard time understanding merge commits, i.e. we should rebase when it fails.
> 
> Does anyone understand why Google Testing is passing for this PR? Perhaps we could update the [Tree Hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#using-git) page based on new info.

Google Testing is passing because @victorsanni approved all of the visual diff test changes.

I asked around about merge commits:

  * There is probably still a possibility that merge commits could confuse customer_testing (and maybe also Google testing?).
  * This would manifest as a false fail and not a false pass. So if your tests pass then they really pass, if they fail then it could be because it's confused by your merge commits. "we should rebase when it fails" as @nate-thegrate said above.
  * Lots of contributors continue to use merge commits in spite of this, including myself for the reasons give by @gnprice above.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 35 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: The error is:

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for
ValueNotifier<BoxConstraints?>:
setState() or markNeedsBuild() called during build.
This ValueListenableBuilder<BoxConstraints?> widget cannot be marked as needing to build because the
framework is already in the process of building widgets. A widget can be marked as needing to be
built during the build phase only if one of its ancestors is currently building. This exception is
allowed because the framework builds parent widgets before children, which means a dirty descendant
will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  ValueListenableBuilder<BoxConstraints?>
The widget which was currently being built when the offending call was made was:
  LayoutBuilder-[GlobalKey#f01c8]

```

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: In this case, can you move the layout builder up such that it is the parent of the OverlayPortal, and see if the error still persists?

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart:517]: The error doesn't persist, but tests that change the width of the field and expect the options width to also change fail. For instance, the test "options width matches field width after rebuilding".

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 37]
```diff
@@ -510,15 +510,8 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-        // The options view is not in the same subtree as the field view, so
-        // when the field constraints change, the options view isn't rebuilt
-        // in the same frame.
-        SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
-          if (!mounted) {
-            return;
-          }
-          _fieldBoxConstraints.value = constraints;
-        });
+        // TODO(victorsanni): Also track the field's layout so that the options view maintains the same width as the field if its constraints remain unchanged.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:513]: Can you create an issue if you are not planning to address the issue in a few days?

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 38]
```diff
@@ -613,32 +606,38 @@ class _RawAutocompleteOptionsState extends State<_RawAutocompleteOptions> {
...
+          link: widget.optionsLayerLink,
+          followerAnchor: switch (widget.optionsViewOpenDirection) {
+            OptionsViewOpenDirection.up => Alignment.bottomLeft,
+            OptionsViewOpenDirection.down => Alignment.topLeft,
+          },
+          // When the field goes offscreen, don't show the options.
+          showWhenUnlinked: false,
+          child: CustomSingleChildLayout(
+            delegate: _RawAutocompleteOptionsLayoutDelegate(
+              fieldSize: widget.optionsLayerLink.leaderSize!,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/autocomplete.dart:623]: Actually I think you probably don't need the layout builder. The size of the field needs to be evaluated when the options view does layout, so doing that in LayoutDelegate's implementation should be fine.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 37 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I'm not sure if this is an issue anymore.

Consider this sample app where the field is wrapped with an `AnimatedBuilder` to animate its width independently:

<details>
<summary>Sample code</summary>

```dart

import 'package:flutter/material.dart';

/// Flutter code sample for [Autocomplete].

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                  'Type below to autocomplete the following possible results: ${AutocompleteBasicExample._kOptions}.'),
              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 32.0),
                child: AutocompleteBasicExample(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatefulWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  State<AutocompleteBasicExample> createState() =>
      _AutocompleteBasicExampleState();
}

class _AutocompleteBasicExampleState extends State<AutocompleteBasicExample>
    with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 10),
    vsync: this,
  )..repeat();

  TextEditingController textEditingController = TextEditingController();
  final FocusNode focusNode = FocusNode();

  bool disposedController = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RawAutocomplete<String>(
      focusNode: focusNode,
      textEditingController: textEditingController,
      fieldViewBuilder: (BuildContext buildContext,
          TextEditingController controller,
          FocusNode focusNode,
          VoidCallback onSubmitted) {
        return AnimatedBuilder(
          animation: _controller,
          child: TextField(
            controller: controller,
            focusNode: focusNode,
            onSubmitted: (String value) => onSubmitted(),
          ),
          builder: (BuildContext context, Widget? child) {
            return SizedBox(
              width: 500 * _controller.value,
              child: child,
            );
          },
        );
      },
      optionsViewBuilder: (BuildContext context,
          AutocompleteOnSelected<String> onSelected, Iterable<String> options) {
        return Align(
          alignment: Alignment.topLeft,
          child: Material(
            elevation: 4.0,
            child: SizedBox(
              height: 200.0,
              child: ListView.builder(
                padding: const EdgeInsets.all(8.0),
                itemCount: options.length,
                itemBuilder: (BuildContext context, int index) {
                  final String option = options.elementAt(index);
                  return GestureDetector(
                    onTap: () {
                      onSelected(option);
                    },
                    child: ListTile(
                      title: Text(option),
                    ),
                  );
                },
              ),
            ),
          ),
        );
      },
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return AutocompleteBasicExample._kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}


```

</details>

The options view still expands with the field even when it doesn't have any details of the animation:


https://github.com/user-attachments/assets/b7aa0187-1e1c-497e-9e75-a847c0d63c69

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: So what's causing the options view to relayout? The `setState` in the composition callback?

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Yes. I added print statements, the constraints aren't changing but the field offset in the x-axis is changing so it triggers the rebuild in the composition callback.

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I think we can remove `_fieldBoxConstraints` and the `ValueListenableBuilder` entirely.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Also this will introduce an one frame delay when the width of the field changes.

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: > That doesn't sound reliable. What if the field offset remains the same?

That's true. Looking at it again it doesn't seem like the composition callback is what is causing the options to maintain the same width as the field.

I wrapped the entire `RawAutocomplete` widget in an `Align` and set its alignment to `.centerLeft`, so that changing the width of the field would not cause `fieldOffset` to change. However, even though `fieldOffset` remains the same, the options width still matches the field width when it changes without delay.

> So what's causing the options view to relayout?

Maybe something in the CompositedTransformTarget/Follower then? Although I don't think any of this is a blocker for this PR as everything works but we just don't know why.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: Can you add a few print statements to see if [this line](https://github.com/flutter/flutter/blob/ad4a1212dc37bc55ec523432a96e9e5856bc274a/packages/flutter/lib/src/widgets/overlay.dart#L2414) is causing the options view to redo its layout? If it is, then I guess we don't need to monitor the field constraints at all?

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: The line is called when I change the field width only and hot reload. Does that mean it is causing the options view to relayout?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: > The line is called when I change the field width only and hot reload. Does that mean it is causing the options view to relayout?

I think that's all we wanted to monitor since we want to keep the options view's width in sync with the field view? If this works I think we can remove the part that tries to get the field constraints.

**Comment by dikatok** [comment]
Hey guys, any plans to wrap this PR up? Would love to re-start my PR based on the final changes.

**Comment by maheshj01** [comment]
This PR deserves a bow 🙇 🚀

**Comment by jacobsimionato** [comment]
Reason for revert: Blocking google3 roll as this broke some google3 tests - see b/390128156

These tests are easy to fix forward, but I'll roll this back to unblock the roll without waiting for review of the fix forward.
