### PR TITLE
Drag gesture recognizer accepts all pointers when any pointer is accepted

### LINKED ISSUE #82784: Drag gesture crashes when one of the 2 pointers wins by default and is then released
Internal issue [b/180346177](b/180346177).

The drag gesture might crash under the following situation:

```dart
  testGesture('Does not crash when one of the 2 pointers wins by default and is then released', (GestureTester tester) {
    bool didStartDrag = false;
    final HorizontalDragGestureRecognizer drag = HorizontalDragGestureRecognizer()
      ..onStart = (_) { didStartDrag = true; }
      ..onEnd = (DragEndDetails details) {} // Crash triggers at onEnd.
      ..dragStartBehavior = DragStartBehavior.down;
    final TapGestureRecognizer tap = TapGestureRecognizer()..onTap = () {};
    final TapGestureRecognizer tap2 = TapGestureRecognizer()..onTap = () {};

    // The pointer1 is caught by drag and tap.
    final TestPointer pointer1 = TestPointer(5);
    final PointerDownEvent down1 = pointer1.down(const Offset(10.0, 10.0));
    drag.addPointer(down1);
    tap.addPointer(down1);
    tester.closeArena(pointer1.pointer);
    tester.route(down1);

    // The pointer2 is caught by drag and tap2.
    final TestPointer pointer2 = TestPointer(6);
    final PointerDownEvent down2 = pointer2.down(const Offset(10.0, 10.0));
    drag.addPointer(down2);
    tap2.addPointer(down2);
    tester.closeArena(pointer2.pointer);
    tester.route(down2);

    // The tap is disposed, leaving drag pointer1's default winner.
    tap.dispose();

    // Wait for microtasks to finish, during which drag claims victory.
    tester.async.elapse(const Duration(milliseconds: 1));
    expect(didStartDrag, true);

    // The pointer1 is released, leaving pointer2 drag's only pointer.
    tester.route(pointer1.up());

    drag.dispose();

    // Passes if no crashes here.

    tap2.dispose();
  });
```

Stacktrace:
<details>
Stable Signature - _CastError at DragGestureRecognizer._checkEnd at package:flutter/src/gestures/monodrag.dart-22868c70
Stack Trace:
at DragGestureRecognizer._checkEnd (monodrag.dart:439 )
at DragGestureRecognizer.didStopTrackingLastPointer (monodrag.dart:379 )
at OneSequenceGestureRecognizer.stopTrackingPointer (recognizer.dart:342 )
at DragGestureRecognizer._giveUpPointer (monodrag.dart:388 )
at DragGestureRecognizer.rejectGesture (monodrag.dart:363 )
at GestureArenaManager._resolve (arena.dart:214 )
at GestureArenaEntry.resolve (arena.dart:53 )
at OneSequenceGestureRecognizer.resolve (recognizer.dart:261 )
at OneSequenceGestureRecognizer.dispose (recognizer.dart:278 )
at DragGestureRecognizer.dispose (monodrag.dart:479 )
at RawGestureDetectorState._syncAll (gesture_detector.dart:1197 )
at RawGestureDetectorState.replaceGestureRecognizers (gesture_detector.dart:1139 )
at ScrollableState.setCanDrag (scrollable.dart:552 )
at ScrollPosition.applyContentDimensions (scroll_position_with_single_context.dart:105 )
at RenderViewport.performLayout (viewport.dart:1484 )
at RenderObject._layoutWithoutResize (object.dart:1634 )
at PipelineOwner.flushLayout (object.dart:884 )
at RendererBinding.drawFrame (binding.dart:454 )
at WidgetsBinding.drawFrame (binding.dart:900 )
at RendererBinding._handlePersistentFrameCallback (binding.dart:320 )
at SchedulerBinding._invokeFrameCallback (binding.dart:1144 )
at SchedulerBinding.handleDrawFrame (binding.dart:1082 )
at SchedulerBinding._handleDrawFrame (binding.dart:998 )
at _rootRun (zone.dart:1186 )
at _CustomZone.run (zone.dart:1090 )
at _CustomZone.runGuarded (zone.dart:994 )
at _invoke (hooks.dart:157 )
at PlatformDispatcher._drawFrame (platform_dispatcher.dart:253 )
at _drawFrame (hooks.dart:120 )
</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
Drag gesture recognizer now accepts all pointers when any pointer is accepted. This is useful when the accepted pointer is accepted by default, i.e. when all other arena memebers has quit (been disposed).

Fixes https://github.com/flutter/flutter/issues/82784.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/gestures/drag_test.dart [hunk 1]
```diff
@@ -1440,4 +1440,48 @@ void main() {
...
+    drag.addPointer(down2);
+    tap2.addPointer(down2);
+    tester.closeArena(pointer2.pointer);
+    tester.route(down2);
+
+    // The tap is disposed, leaving drag the default winner.
+    tap.dispose();
+
+    // Wait for microtasks to finish, during which drag claims victory.
+    tester.async.elapse(const Duration(milliseconds: 1));
```
Comment (goderbauer) [inline packages/flutter/test/gestures/drag_test.dart:1475]: `tester.async.flushMicrotasks()` ? Or do you actually need time to pass?

**Review by goderbauer — APPROVED** [review]
LGTM

Thanks for hunting that down! 👍
