### PR TITLE
[Web][Engine] Fix composingBaseOffset and composingExtentOffset value when input japanese text

### LINKED ISSUE #159671: [Web] Composing Japanese letters disappear when shifting converting area
### Steps to reproduce

1. launch an app with `TextField` on web platform
2. type some letters in Hiragana, Japanese.
3. before committing (by hitting the Enter key), hit the Space key to convert them to Kanji.
4. press Shift and hit the left arrow key twice
5. composing Hiragana letters disappear

### Expected results

The composing Hiragana letters don't disappear, and the composing area would shift respecting the arrow key hit.

### Actual results

All the composing Hiragana letters disappear.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() => runApp(const MainApp());

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(32),
          child: Container(
            width: double.infinity,
            color: Colors.white,
            child: const Padding(
              padding: EdgeInsets.all(16),
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/50f5c200-8e3d-4ff1-9457-3c08224d8be6

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.3.1 23D60 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.94.2)
[✓] VS Code (version 1.61.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/159671

When entering Japanese text and operating `shift + ← || → || ↑ || ↓` while composing a character, `setSelectionRange` set (0,0) and the composing text is disappeared. For this reason, disable shit + arrow text shortcuts on web platform.

### Movie

fixed

https://github.com/user-attachments/assets/ad0bd199-92a5-4e1f-9f26-0c23981c013d

master branch

https://github.com/user-attachments/assets/934f256e-189b-4916-bb91-a49be60f17b3

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by mdebbar — COMMENTED** [review]
Thank you for contributing a fix to this issue!

The test should go into this file: `engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart`. This file has many tests that do various things that you can copy from.

Here's how the test could look like:
1. Create a text field using the `showKeyboard` helper.
2. Set `composingText` to a non-null value.
3. Send a `TextInput.setEditingState`.
4. Expect the selection change hasn't been applied using `checkInputEditingState`.

These are some tests that may be relevant / similar to what you'll be writing:
- https://github.com/flutter/flutter/blob/e0676b47c7550ecdc0f0c4fa759201449b2c5f23/engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart#L1761
- https://github.com/flutter/flutter/blob/e0676b47c7550ecdc0f0c4fa759201449b2c5f23/engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart#L544
- https://github.com/flutter/flutter/blob/e0676b47c7550ecdc0f0c4fa759201449b2c5f23/engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart#L689-L696

I hope this helps. Let me know if you have any more questions.

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 1]
```diff
@@ -1943,6 +1943,126 @@ Future<void> testMain() async {
       hideKeyboard();
     });
 
+    test('Supports composition changes with shift arrow selection in Japanese IME', () {
+      final HybridTextEditing testTextEditing = HybridTextEditing();
+      final GlobalTextEditingStrategySpy editingStrategy = GlobalTextEditingStrategySpy(
+        testTextEditing,
+      );
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:1950]: There's already an instance of `HybridTextEditing` being created for each test in `setUp`.

Also, I don't think you need a `GlobalTextEditingStrategySpy`. A simple `DefaultTextEditingStrategy` should work.
```suggestion
      final DefaultTextEditingStrategy editingStrategy = DefaultTextEditingStrategy(textEditing);
```

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 2]
```diff
@@ -1943,6 +1943,126 @@ Future<void> testMain() async {
...
+          const MethodCall('TextInput.setEditingState', <String, dynamic>{
+            'text': 'へんかん',
+            'selectionBase': 4,
+            'selectionExtent': 4,
+            'composingBase': 0,
+            'composingExtent': 4,
+          }),
+        ),
+      );
+      checkInputEditingState(textEditing!.strategy.domElement, 'へんかん', 4, 4);
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:1965]: In all these checks, the numbers match what was sent in `selectionBase` and `selectionExtent`. So it's not achieving the goal of the test which is to verify that selection wasn't updated on the DOM element.

To test this, you want to send some random numbers in `selectionBase` and `selectionExtent`, then check that the DOM element's selection hasn't changed to those random numbers.

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 3]
```diff
@@ -1943,6 +1943,126 @@ Future<void> testMain() async {
...
+      showKeyboard(inputType: 'text');
+      editingStrategy.composingText = 'へんかん';
+      sendFrameworkMessage(
+        codec.encodeMethodCall(
+          const MethodCall('TextInput.setEditingState', <String, dynamic>{
+            'text': 'へんかん',
+            'selectionBase': 4,
+            'selectionExtent': 4,
+            'composingBase': 0,
+            'composingExtent': 4,
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:1961]: Does Flutter always send `composingBase` and `composingExtent` when the user is composing text? If yes, then we don't really need the new `isComposing` boolean, right? We can simply check for the presence of `composingBase` and/or `composingExtent` inside `EditingState.applyToDomElement`.

**Comment by koji-1009** [comment]
Sorry. I misunderstood that I needed to simulate the movement of Japanese IMEs. A test has been added to confirm this added process. Thank you for your support.

**Review by mdebbar — APPROVED** [review]
LGTM! Thanks for contributing the fix!

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 4]
```diff
@@ -960,18 +960,25 @@ class EditingState {
   /// elements can have their text selection range set. Attempting to set
   /// selection range on a non-focused element will cause it to request focus.
   ///
+  /// If text is in the composing state, the composing range is not updated by
+  /// [isComposing] being `true`.
```
Comment (koji-1009) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:964]:
```suggestion
  /// [updateSelection] being `true`.
```

**Review by Renzo-Olivares — COMMENTED** [review]
Thank you for your contribution and patience @koji-1009. I'm not sure if the selection being updated while composing is the root cause of the issue here. 

When logging myself I see a few things,

1. Sometimes the composing range cannot be determined in cases where the selection extent becomes smaller than the composing text extent. 
2. The framework is sending an update to the engine when we press shift + arrow key right/left.

I think `2` is important here because we want all text editing shortcuts to be handled natively on the web, so the framework shouldn't be sending this update when `shift + arrow key right/left` is pressed. I think `1` is less important since it doesn't interfere with the native webs composition, since composing range does not exist in native web and is not applied to the dom element, right now it is only used by the framework to draw the composing underline (should be a separate issue).

I think the fix for this should be in the framework, we can add the `shift + arrow left/right` to the web disabling shortcuts here https://github.com/flutter/flutter/blob/296df33be866d0cd8387524e288d9b280e725795/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L878 .

```dart
  const SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true):
      const DoNothingAndStopPropagationTextIntent(),
  const SingleActivator(LogicalKeyboardKey.arrowRight, shift: true):
      const DoNothingAndStopPropagationTextIntent(),
```

I tried this out and it seems to match the behavior I am observing in html's native `TextArea`.

**Review by koji-1009 — COMMENTED** [review]
@Renzo-Olivares 
Thanks also for clarifying the root cause!

Because I hadn't noticed `_webDisablingTextShortcuts`, I thought it was correct not to call `setSelectionRange` while converting with the (Japanese) IME. It certainly seems to be a more suitable modification for flutter web to deal with on the framework side.

Adding 4 patterns, left and right, up and down, seems to solve the problem. Would the fix be to add a commit to this PR, or would it be better to open another PR?

---

Thank you so much for your support. I really appreciate it.

**Comment by Renzo-Olivares** [comment]
@koji-1009, Doing it in this PR sounds good to me.

**Comment by Renzo-Olivares** [comment]
Looks like the failing test were because we previously moved these shortcuts to be handled by the framework to fix some issues related to scrolling, see https://github.com/flutter/flutter/pull/117217 and https://github.com/flutter/flutter/pull/114264. In that case i'm not sure we want to add them back to the disabling shortcuts since it would break those features again. We might want to do this another way since I noticed shortcuts like page down/page up/home/end are also behaving differently then native while composing.

**Comment by koji-1009** [comment]
OK, I'll investigate.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart [hunk 5]
```diff
@@ -81,7 +81,12 @@ mixin CompositionAwareMixin {
     final int composingBase = editingState.extentOffset! - composingText!.length;
 
     if (composingBase < 0) {
```
Comment (koji-1009) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:83]: About this case.

When we type Japanese, we may enter this if statement. For example, if you type “こんにちは” and then use shift + ← or → to change the range, we get the following log output.

code

```dart
  EditingState determineCompositionState(EditingState editingState) {
    print(
      'editingState = $editingState, composingText = $composingText, composingText length = ${composingText?.length}',
    );
```

log

```
editingState = EditingState("", base:0, extent:0, composingBase:-1, composingExtent:-1), composingText = null, composingText length = null
editingState = EditingState("k", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText = k, composingText length = 1
editingState = EditingState("k", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText = k, composingText length = 1
editingState = EditingState("こ", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText = こ, composingText length = 1
editingState = EditingState("こ", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText = こ, composingText length = 1
editingState = EditingState("こn", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText = こn, composingText length = 2
editingState = EditingState("こn", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText = こn, composingText length = 2
editingState = EditingState("こん", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText = こん, composingText length = 2
editingState = EditingState("こん", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText = こん, composingText length = 2
editingState = EditingState("こんn", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText = こんn, composingText length = 3
editingState = EditingState("こんn", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText = こんn, composingText length = 3
editingState = EditingState("こんに", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに, composingText length = 3
editingState = EditingState("こんに", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに, composingText length = 3
editingState = EditingState("こんにt", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText = こんにt, composingText length = 4
editingState = EditingState("こんにt", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText = こんにt, composingText length = 4
editingState = EditingState("こんにち", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText = こんにち, composingText length = 4
editingState = EditingState("こんにち", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText = こんにち, composingText length = 4
editingState = EditingState("こんにちh", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちh, composingText length = 5
editingState = EditingState("こんにちh", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちh, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:0, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:0, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに血は, composingText length = 5
editingState = EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに血は, composingText length = 5
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("こんにちは", base:0, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:0, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("こんにちは", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText = null, composingText length = null
```

If `composingText` is non-null, text is in composing. However, the previous process could not determine that composing is in progress because `composingBase` and `composingExtent` are `-1`.

This change will allow the framework to be notified that composing is in progress.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 6]
```diff
@@ -904,10 +902,10 @@ class EditingState {
   final String? text;
```
Comment (koji-1009) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:903]: `baseOffset` and `extentOffset` are never set to null.

```dart
  EditingState({
    this.text,
    int? baseOffset,
    int? extentOffset,
    this.composingBaseOffset = -1,
    this.composingExtentOffset = -1,
  }) : // Don't allow negative numbers.
       baseOffset = math.max(0, baseOffset ?? 0),
       // Don't allow negative numbers.
       extentOffset = math.max(0, extentOffset ?? 0);
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart [hunk 7]
```diff
@@ -74,14 +74,19 @@ mixin CompositionAwareMixin {
...
 
-    final int composingBase = editingState.extentOffset! - composingText!.length;
+    final int composingBase = editingState.extentOffset - composingText!.length;
 
     if (composingBase < 0) {
-      return editingState;
+      // The length of the input string is set to the length of the composing string.
+      // This is a workaround for the case where the japanese IME is used.
+      return editingState.copyWith(
+        composingBaseOffset: editingState.baseOffset,
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:87]: Is this accurate when composing? I would expect the `editing.baseOffset` and `editing.extentOffset` to be collapsed while composing text, and only becomes uncollapsed when pressing shift + <-/->.

File: engine/src/flutter/lib/web_ui/test/engine/composition_test.dart [hunk 8]
```diff
@@ -147,12 +137,14 @@ Future<void> testMain() async {
...
-        const String composingText = 'composeMe';
+        const String composingText = '今日は';
 
         final EditingState editingState = EditingState(
-          text: 'Test',
+          text: '今日は',
           baseOffset: 0,
-          extentOffset: 4,
+          extentOffset: 2,
+          composingBaseOffset: 0,
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/test/engine/composition_test.dart:146]: I think the composing range here should actually be `(0,3)` since it should cover the full length of the `composingText`.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 7 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:87]: https://github.com/flutter/flutter/pull/161593#discussion_r2050596612
The log output of Japanese conversions, for example, will have the following.

```
editingState = EditingState("こんにちは", base:0, extent:5, composingBase:-1, composingExtent:-1), composingText = こんにちは, composingText length = 5
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1), composingText = 今日は, composingText length = 3
editingState = EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに血は, composingText length = 5
editingState = EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText = こんに血は, composingText length = 5
```

It seems that the “number of conversion blocks” rather than the “string length” is reflected in the extent during Japanese conversion, thinking from the log. From “こんにちは”, shift + ← becomes “今日は”. This is two blocks of “今日” and “は”.　Then shift + ←, becoms "こんに血は". This is three blocks of "こんに" and "血" and "は".

In the current implementation, if we “update the conversion range” during composing, it can no longer be determined that composing is in progress. As a result, `setSelectRange` is updated with (0,0) and the character being input cleared.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:83]: I think we should try printing this log after this line https://github.com/flutter/flutter/blob/c0c12a759eb5bb07d10d5a4b6c26da22b4f1a03f/engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1483 

printing at the top of `determineCompositionState` would mean the composition range has not been determined yet.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:87]: Replied in https://github.com/flutter/flutter/pull/161593#discussion_r2060722882, this will get us more accurate logs.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 5 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:83]: I added `print` code, and test it.

```dart
    EditingState newEditingState = EditingState.fromDomElement(activeDomElement);
    newEditingState = determineCompositionState(newEditingState);
    print('newEditingState: $newEditingState');
```

Input "こんにちは" and compose it , then press shit + ←.

main branch

```
newEditingState: EditingState("", base:0, extent:0, composingBase:-1, composingExtent:-1)
newEditingState: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こ", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こ", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こn", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こn", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こんn", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんn", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんに", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんに", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんにt", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにt", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにち", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにち", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにちh", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちh", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちは", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちは", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("今日は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("今日は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1)
newEditingState: EditingState("今日は", base:0, extent:2, composingBase:-1, composingExtent:-1)
newEditingState: EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1)
newEditingState: EditingState("こんに血は", base:0, extent:3, composingBase:-1, composingExtent:-1)
newEditingState: EditingState("", base:0, extent:0, composingBase:0, composingExtent:0)
newEditingState: EditingState("", base:0, extent:0, composingBase:-1, composingExtent:-1)
```

fix/web_composing_range

```
newEditingState: EditingState("", base:0, extent:0, composingBase:0, composingExtent:0)
newEditingState: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こ", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こ", base:1, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("こn", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こn", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こんい", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんい", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん", base:2, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こんn", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんn", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんに", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんに", base:3, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんにt", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにt", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにち", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにち", base:4, extent:4, composingBase:0, composingExtent:4)
newEditingState: EditingState("こんにちh", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちh", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちは", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("こんにちは", base:5, extent:5, composingBase:0, composingExtent:5)
newEditingState: EditingState("今日は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("今日は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("今日は", base:0, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("今日は", base:0, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こんに血は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こんに血は", base:0, extent:3, composingBase:0, composingExtent:3)
newEditingState: EditingState("こん日は", base:0, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("こん日は", base:0, extent:2, composingBase:0, composingExtent:2)
newEditingState: EditingState("子ん日は", base:0, extent:1, composingBase:0, composingExtent:1)
newEditingState: EditingState("子ん日は", base:0, extent:1, composingBase:0, composingExtent:1)
```

We can infer from the logs and logic that the problem is caused by cases where the composing text is longer than the extent.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 7 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:87]: Sorry. There is an incorrect comment above.

If we press shift + arrow key, the area of the character to be converted is changed. For example, if we composing “今日は”, base=0 extent=2 when ‘今日’ is selected, then pressing arrow right selects “は” and base=2 extent=3.
The current implementation does not work as expected when there is a 3-character composing text “今日は” and the “今日” part is selected.

**Comment by Renzo-Olivares** [comment]
Thank you for your patience on this one @koji-1009 i'll be taking a look this week.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: I think the composing range calculation is not accurate here. `textLength < composingTextLength` returns `true` during all steps of composing `今日は`. This causes the composing range to be collapsed throughout all the steps, but it should be uncollapsed as noted by the blue-underline under the composing text. The composing range should cover the entire composing text.

One thing I noticed (without any changes) is that while the selection is collapsed and we are composing, the composing range is calculated accurately. It's only when the selection becomes uncollapsed through pressing shift + arrow does the composing range calculation become inaccurate. I think we can handle this case with the code below. When pressing shift + arrow we never escape the original composing range so we can leverage it to calculate the composing range.

```dart
final int composingBase;
final int composingExtent;

if (editingState.baseOffset != editingState.extentOffset) {
  composingBase = editingState.baseOffset;
  composingExtent = editingState.baseOffset + composingText!.length;
} else {
  composingBase = editingState.extentOffset - composingText!.length;
  composingExtent = composingBase + composingText!.length;
}

......

return editingState.copyWith(
  composingBaseOffset: composingBase,
  composingExtentOffset: composingExtent,
);
```

Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: The Japanese IME can compose sentences as well as words. The following video and logs have been added to `determineCompositionState` in the main branch.

```dart
  EditingState determineCompositionState(EditingState editingState) {
    print('editingState: $editingState, composingText: $composingText');
```

<details>

<summary>log</summary>

```
editingState: EditingState("", base:0, extent:0, composingBase:-1, composingExtent:-1), composingText: null
editingState: EditingState("k", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText: k
editingState: EditingState("k", base:1, extent:1, composingBase:-1, composingExtent:-1), composingText: k
editingState: EditingState("ky", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText: ky
editingState: EditingState("ky", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText: ky
editingState: EditingState("きょ", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText: きょ
editingState: EditingState("きょ", base:2, extent:2, composingBase:-1, composingExtent:-1), composingText: きょ
editingState: EditingState("きょう", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText: きょう
editingState: EditingState("きょう", base:3, extent:3, composingBase:-1, composingExtent:-1), composingText: きょう
editingState: EditingState("きょうh", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText: きょうh
editingState: EditingState("きょうh", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText: きょうh
editingState: EditingState("きょうは", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText: きょうは
editingState: EditingState("きょうは", base:4, extent:4, composingBase:-1, composingExtent:-1), composingText: きょうは
editingState: EditingState("きょうはs", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText: きょうはs
editingState: EditingState("きょうはs", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText: きょうはs
editingState: EditingState("きょうはさ", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText: きょうはさ
editingState: EditingState("きょうはさ", base:5, extent:5, composingBase:-1, composingExtent:-1), composingText: きょうはさ
editingState: EditingState("きょうはさm", base:6, extent:6, composingBase:-1, composingExtent:-1), composingText: きょうはさm
editingState: EditingState("きょうはさm", base:6, extent:6, composingBase:-1, composingExtent:-1), composingText: きょうはさm
editingState: EditingState("きょうはさむ", base:6, extent:6, composingBase:-1, composingExtent:-1), composingText: きょうはさむ
editingState: EditingState("きょうはさむ", base:6, extent:6, composingBase:-1, composingExtent:-1), composingText: きょうはさむ
editingState: EditingState("きょうはさむい", base:7, extent:7, composingBase:-1, composingExtent:-1), composingText: きょうはさむい
editingState: EditingState("きょうはさむい", base:7, extent:7, composingBase:-1, composingExtent:-1), composingText: きょうはさむい
editingState: EditingState("きょうはさむいn", base:8, extent:8, composingBase:-1, composingExtent:-1), composingText: きょうはさむいn
editingState: EditingState("きょうはさむいn", base:8, extent:8, composingBase:-1, composingExtent:-1), composingText: きょうはさむいn
editingState: EditingState("きょうはさむいの", base:8, extent:8, composingBase:-1, composingExtent:-1), composingText: きょうはさむいの
editingState: EditingState("きょうはさむいの", base:8, extent:8, composingBase:-1, composingExtent:-1), composingText: きょうはさむいの
editingState: EditingState("きょうはさむいのd", base:9, extent:9, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのd
editingState: EditingState("きょうはさむいのd", base:9, extent:9, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのd
editingState: EditingState("きょうはさむいので", base:9, extent:9, composingBase:-1, composingExtent:-1), composingText: きょうはさむいので
editingState: EditingState("きょうはさむいので", base:9, extent:9, composingBase:-1, composingExtent:-1), composingText: きょうはさむいので
editingState: EditingState("きょうはさむいのでk", base:10, extent:10, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでk
editingState: EditingState("きょうはさむいのでk", base:10, extent:10, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでk
editingState: EditingState("きょうはさむいのでこ", base:10, extent:10, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこ
editingState: EditingState("きょうはさむいのでこ", base:10, extent:10, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこ
editingState: EditingState("きょうはさむいのでこー", base:11, extent:11, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこー
editingState: EditingState("きょうはさむいのでこー", base:11, extent:11, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこー
editingState: EditingState("きょうはさむいのでこーt", base:12, extent:12, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーt
editingState: EditingState("きょうはさむいのでこーt", base:12, extent:12, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーt
editingState: EditingState("きょうはさむいのでこーと", base:12, extent:12, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーと
editingState: EditingState("きょうはさむいのでこーと", base:12, extent:12, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーと
editingState: EditingState("きょうはさむいのでこーとw", base:13, extent:13, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとw
editingState: EditingState("きょうはさむいのでこーとw", base:13, extent:13, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとw
editingState: EditingState("きょうはさむいのでこーとを", base:13, extent:13, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとを
editingState: EditingState("きょうはさむいのでこーとを", base:13, extent:13, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとを
editingState: EditingState("きょうはさむいのでこーとをk", base:14, extent:14, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをk
editingState: EditingState("きょうはさむいのでこーとをk", base:14, extent:14, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをk
editingState: EditingState("きょうはさむいのでこーとをき", base:14, extent:14, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをき
editingState: EditingState("きょうはさむいのでこーとをき", base:14, extent:14, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをき
editingState: EditingState("きょうはさむいのでこーとをきm", base:15, extent:15, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきm
editingState: EditingState("きょうはさむいのでこーとをきm", base:15, extent:15, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきm
editingState: EditingState("きょうはさむいのでこーとをきま", base:15, extent:15, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきま
editingState: EditingState("きょうはさむいのでこーとをきま", base:15, extent:15, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきま
editingState: EditingState("きょうはさむいのでこーとをきまs", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきまs
editingState: EditingState("きょうはさむいのでこーとをきまs", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきまs
editingState: EditingState("きょうはさむいのでこーとをきまし", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきまし
editingState: EditingState("きょうはさむいのでこーとをきまし", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: きょうはさむいのでこーとをきまし
editingState: EditingState("きょうはさむいのでこーとをきましt", base:17, extent:17, composingBase:-1, composingExtent:-1), composingText:
きょうはさむいのでこーとをきましt
editingState: EditingState("きょうはさむいのでこーとをきましt", base:17, extent:17, composingBase:-1, composingExtent:-1), composingText:
きょうはさむいのでこーとをきましt
editingState: EditingState("きょうはさむいのでこーとをきました", base:17, extent:17, composingBase:-1, composingExtent:-1), composingText:
きょうはさむいのでこーとをきました
editingState: EditingState("きょうはさむいのでこーとをきました", base:17, extent:17, composingBase:-1, composingExtent:-1), composingText:
きょうはさむいのでこーとをきました
editingState: EditingState("今日は寒いのでコートを着ました", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText: 今日は寒いのでコートを着ました
editingState: EditingState("今日は寒いのでコートを着ました", base:0, extent:3, composingBase:-1, composingExtent:-1), composingText: 今日は寒いのでコートを着ました
editingState: EditingState("今日は寒いのでコートを着ました", base:3, extent:7, composingBase:-1, composingExtent:-1), composingText: 今日は寒いのでコートを着ました
editingState: EditingState("今日は寒いのでコートを着ました", base:3, extent:7, composingBase:-1, composingExtent:-1), composingText: 今日は寒いのでコートを着ました
editingState: EditingState("今日はさむいのでコートを着ました", base:3, extent:8, composingBase:-1, composingExtent:-1), composingText: 今日はさむいのでコートを着ました
editingState: EditingState("今日はさむいのでコートを着ました", base:3, extent:8, composingBase:-1, composingExtent:-1), composingText: 今日はさむいのでコートを着ました
editingState: EditingState("今日は寒いの出コートを着ました", base:3, extent:7, composingBase:-1, composingExtent:-1), composingText: 今日は寒いの出コートを着ました
editingState: EditingState("今日は寒いの出コートを着ました", base:3, extent:7, composingBase:-1, composingExtent:-1), composingText: 今日は寒いの出コートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:3, extent:8, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:3, extent:8, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでこーとを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでこーとを着ました
editingState: EditingState("今日はサムイのでこーとを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでこーとを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:8, extent:12, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートをきました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートをきました
editingState: EditingState("今日はサムイのでコートをきました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートをきました
editingState: EditingState("今日はサムイのでコートを着ました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートを着ました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートを着ました
editingState: EditingState("今日はサムイのでコートをきました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートをきました
editingState: EditingState("今日はサムイのでコートをきました", base:12, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートをきました
editingState: EditingState("今日はサムイのでコートをきました", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: 今日はサムイのでコートをきました
editingState: EditingState("今日はサムイのでコートをきました", base:16, extent:16, composingBase:-1, composingExtent:-1), composingText: null
```

</details>

https://github.com/user-attachments/assets/05e8914d-5290-4791-8b58-39066df73e1d

"今日は寒いのでコートを着ました" is a 16-character text, but while converting "寒いので" base=3 and extent=7. So, composingExtent is 19. In the video example, if composingExtent were to become larger than 16, would that cause other problems?

Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: Good point that would definitely cause issues, i'll try to investigate this further and post an update with my findings.

Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: What if we save the state of the `composingBase` before the selection became uncollapsed and use that as our `composingBase`? We can set the saved `composingBase` to `null` in `_handleCompositionEnd`. Then we just add the length of the `composingText` to the `composingBase` to calculate our `composingExtent`. Let me know if that makes sense/ works.

Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: In a native web text area while composing the sentence in your video does the entire text stay underlined? Or does the underline disappear at certain points?

Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart:86]: I tested native input element. The underline is shown.

https://github.com/user-attachments/assets/0d4f68b4-112d-4ccb-8983-2f80baeaf3f7

And I tested following fix. The behavior when entering Japanese seems to be good!

```dart
  int? composingBase;

  void _handleCompositionStart(DomEvent event) {
    composingText = null;
    composingBase = null;
  }

  void _handleCompositionUpdate(DomEvent event) {
    if (event.isA<DomCompositionEvent>()) {
      composingText = (event as DomCompositionEvent).data;
    }
  }

  void _handleCompositionEnd(DomEvent event) {
    composingText = null;
    composingBase = null;
  }

  EditingState determineCompositionState(EditingState editingState) {
    if (composingText == null) {
      return editingState;
    }

    composingBase ??= editingState.extentOffset - composingText!.length;
    if (composingBase! < 0) {
      return editingState;
    }

    return editingState.copyWith(
      composingBaseOffset: composingBase,
      composingExtentOffset: composingBase! + composingText!.length,
    );
  }
```

https://github.com/user-attachments/assets/395c9316-5cbc-4bc1-8da6-ae9f1d12f7a8

File: engine/src/flutter/lib/web_ui/test/engine/composition_test.dart [hunk 9]
```diff
@@ -210,6 +210,35 @@ Future<void> testMain() async {
...
+        final _MockWithCompositionAwareMixin mockWithCompositionAwareMixin =
+            _MockWithCompositionAwareMixin();
+        mockWithCompositionAwareMixin.composingText = composingText;
+
+        expect(
+          mockWithCompositionAwareMixin.determineCompositionState(editingState),
+          editingState.copyWith(composingBaseOffset: 0, composingExtentOffset: 8),
+        );
+
+        editingState = editingState.copyWith(text: '今日は', baseOffset: 0, extentOffset: 3);
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/test/engine/composition_test.dart:228]: I think here we should set the `composingText` to `'今日は'` and not the editingState.text. If not then the composing range will not be contained within the text length.

File: engine/src/flutter/lib/web_ui/test/engine/composition_test.dart [hunk 10]
```diff
@@ -210,6 +210,35 @@ Future<void> testMain() async {
...
+
+        expect(
+          mockWithCompositionAwareMixin.determineCompositionState(editingState),
+          editingState.copyWith(composingBaseOffset: 0, composingExtentOffset: 8),
+        );
+
+        editingState = editingState.copyWith(text: '寒い日', baseOffset: 3, extentOffset: 6);
```
Comment (Renzo-Olivares) [inline engine/src/flutter/lib/web_ui/test/engine/composition_test.dart:235]: Here we should also set the `composingText` instead of the `editingState.text`.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart]: Glad to hear that worked out!

File: engine/src/flutter/lib/web_ui/test/engine/composition_test.dart (hunk 9 above)
Comment (koji-1009) [reply engine/src/flutter/lib/web_ui/test/engine/composition_test.dart]: Sorry, I fixed. [9e8f7fd](https://github.com/flutter/flutter/pull/161593/commits/9e8f7fdc877ea7bbd90c258c14bc0d4bfd4ef539)

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 11]
```diff
@@ -6484,7 +6484,13 @@ class _UpdateTextSelectionAction<T extends DirectionalCaretMovementIntent>
   }
 
   @override
-  bool get isActionEnabled => state._value.selection.isValid;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart:6487]: I think we might want to do the same with the below intents. I noticed that when composing the field does not scroll in reaction to these intents in a native multi-line text area. Do you observe the same?

```dart
    ScrollToDocumentBoundaryIntent: _makeOverridable(
      CallbackAction<ScrollToDocumentBoundaryIntent>(onInvoke: _scrollToDocumentBoundary),
    ),
    ScrollIntent: CallbackAction<ScrollIntent>(onInvoke: _scroll),
```

we can do that by extending `CallbackAction`, maybe something like:

```
class _WebComposingDisablingCallbackAction<T extends Intent> extends CallbackAction<T> { }
```

Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart:6487]: Using the macOS “ことえり” IME, I typed Japanese in the TextArea. I then pressed `fn key` + `arrow left` and `fn key` + `arrow right` to send home and end events.

https://github.com/user-attachments/assets/b21bd533-3f8a-4a21-a5d5-d570e5b628eb

Is the operation captured on video the operation we should be checking?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:6487]: Thank you for checking that, yes `fn key + arrow left` and `fn key + arrow right`, and also `fn key + arrow up` and `fn key + arrow down`.

My simple example below it seems to do nothing for `fn key + arrow left/right`, and goes through the composing menu when doing `fn key + arrow up/down`.

https://github.com/user-attachments/assets/f020509a-6e12-426f-9bb1-73080279ccc3

In your example it looks like if the composing spreads across multiple lines then the shortcuts will actually scroll?

Comment (koji-1009) [reply packages/flutter/lib/src/widgets/editable_text.dart:6487]: Supoort `home key` (fn + arrow left) and `end key` (fn + arrow right). [79d5ed8](https://github.com/flutter/flutter/pull/161593/commits/79d5ed803d8c36338d8acfba03b843655e32957d)

However, `pageUp key` (fn + arrow up) and `pageDown key` (fn + arrow down) would also require modification of `app.dart`. The current implementation does not determine whether or not composing is in progress and cannot be handled by simply modifying `editable_text.dart`.

https://github.com/flutter/flutter/pull/105497
https://github.com/flutter/flutter/pull/107602

https://github.com/flutter/flutter/blob/78a2a3fa675572fe55b2aa47e2ff1317baf30d03/packages/flutter/lib/src/widgets/app.dart#L1896-L1899

---

I understand that it should be fixed, but is it possible to separate the PR? https://github.com/flutter/flutter/issues/159671 is an important issue for Japanese IMEs. Compared to the shift + arrow left/right problem, the pageUp/pageDown problem has a smaller impact...

**Comment by kevmoo** [comment]
Should we try to update the branch and see if google testing goes green?

**Comment by koji-1009** [comment]
@kevmoo
Thanks for the suggestion! I've merged the `master` branch and re-ran the tests, but Google testing is still timing out. Is there anything else I can do?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/editable_text.dart:6485]: Separating this into a separate PR sounds good to me! Thank you for looking into that.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 12]
```diff
@@ -6562,7 +6571,28 @@ class _UpdateTextSelectionVerticallyAction<T extends DirectionalCaretMovementInt
...
+  bool get isActionEnabled {
+    if (kIsWeb && state.widget.selectionEnabled && state._value.composing.isValid) {
+      return false;
+    }
+
+    return state._value.selection.isValid;
+  }
+}
+
+class _WebComposingDisabllingPageBoundaryAction<T extends Intent> extends CallbackAction<T> {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart:6583]: nit: should be `_WebComposingDisablingDocumentBoundaryAction`.

File: packages/flutter/test/widgets/editable_text_shortcuts_test.dart [hunk 13]
```diff
@@ -2864,4 +2864,164 @@ void main() {
       );
     });
   }, skip: !kIsWeb); // [intended] specific tests target web.
+
+  group(
+    'Web does not accept',
+    () {
+      testWidgets('character modifier + arrowLeft in compposing', (WidgetTester tester) async {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_shortcuts_test.dart:2871]: nit: `compposing` -> `composing` here and elsewhere in this file.

**Comment by Renzo-Olivares** [comment]
@koji-1009 I would try the following to rebase:

```
git fetch upstream
git rebase upstream/master
```

**Review by Renzo-Olivares — APPROVED** [review]
LGTM pending Google testing

**Comment by koji-1009** [comment]
Hmmm, should I squash commits to be a single commit?

**Comment by kevmoo** [comment]
@koji-1009 – no need. We will squash when we land.

In general, it's nice to avoid doing the big rebase/squash beforehand so it doesn't mess up review history thing.

**Comment by koji-1009** [comment]
Passed Google testing. https://github.com/flutter/flutter/runs/43343144250

**Comment by kevmoo** [comment]
I think we finally got green here. All good @mdebbar ? if so, please approve and add `auto-sumbit`

**Review by mdebbar — APPROVED** [review]
