### PR TITLE
[web] close input connection when window/iframe loses focus

### LINKED ISSUE #155265: Textfield with FocusNode Rendered within an iFrame on Web Refuses to Lose Focus
### Steps to reproduce

1. Create a flutter app with the following `main.dart` file (this is just a hello world flutter app that contains a textfield along with a focusnode):
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  // Declare the FocusNode
  late FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    // Initialize the FocusNode
    _focusNode = FocusNode();
  }

  @override
  void dispose() {
    // Dispose of the FocusNode
    _focusNode.dispose();
    super.dispose();
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 20), // Add spacing
            // Add the TextField widget
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40.0),
              child: TextField(
                focusNode: _focusNode,
                decoration: const InputDecoration(
                  labelText: 'Enter text',
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _incrementCounter();
          // Request focus when the button is pressed
          _focusNode.requestFocus();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

2. Build the app with `flutter build web`
3. Run this dart file to statically serve the flutter web application on port 3000:

```dart
import 'package:shelf/shelf_io.dart' as io;
import 'package:shelf_plus/shelf_plus.dart' show Pipeline;
import 'package:shelf_static/shelf_static.dart';
import 'package:shelf/shelf.dart';

Map<String, String> corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': '*',
};

Middleware cors = createMiddleware(responseHandler: (response) {
  return response.change(headers: corsHeaders);
}, requestHandler: (request) {
  if (request.method == 'OPTIONS') {
    return Response.ok(null, headers: corsHeaders);
  }
  return null;
});

void main() async {
  Pipeline pipeline = Pipeline();

  // pipeline = pipeline.addMiddleware(shelf.logRequests());
  pipeline = pipeline.addMiddleware(cors);

  var server = await io.serve(
    pipeline.addHandler(createStaticHandler('build/web', defaultDocument: 'index.html')),
    'localhost',
    3000,
    poweredByHeader: '',
  );

  /// This will remove default headers from the server.
  server.defaultResponseHeaders.removeAll('X-Frame-Options');
  // server.defaultResponseHeaders.add('X-Frame-Options', 'null');
}
```

4. open this html file in your browser (this simply opens up an iframe to localhost:3000)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iframe Example</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        iframe {
            width: 50vw; /* 50% of the viewport width */
            height: 100vh; /* 100% of the viewport height */
            border: none; /* Remove default border */
        }
    </style>
</head>
<body>
	<input placeholder="normal browser text input">
    <iframe src="http://localhost:3000"></iframe>
</body>
</html>
```

5. click on the flutter app's `TextField` input widget
6. Attempt to click on the browser input with the placeholder 'normal browser text input'
7. The flutter TextField will momentarily lose focus, to only request it again, making it impossible to type into the other normal text input without clicking outside of the TextField in the flutter application

### Expected results

I would expect that if you click outside of an iFrame that is a flutter web application, a focused TextField should properly lose focus

### Actual results

The Flutter TextField does not lose focus until you click outside of the TextField within the flutter application

### Code sample

<details open><summary>Code sample</summary>

I provided the code sample earlier
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/80a4d81b-90a2-4ebe-8be3-19acf8eec048

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
[✓] VS Code (version 1.93.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/155265

This includes 2 fixes:

* When the window/iframe loses focus, close the text input connection instead of grabbing the focus again.
* Do not enable semantics using the placeholder when moving focus using the "Tab" key.

Bonus: remove the no longer necessary `ViewFocusBinding.isEnabled` (doesn't fix any issues, just a clean-up).

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart [hunk 1]
```diff
@@ -79,6 +79,15 @@ abstract class SemanticsEnabler {
   /// Or if the received [DomEvent] is suitable/enough for enabling the
   /// semantics. See [tryEnableSemantics].
   bool shouldEnableSemantics(DomEvent event) {
+    // Simply tabbing into the placeholder element should not cause semantics
+    // to be enabled. The user should actually click on the placeholder.
+    if (event.isA<DomKeyboardEvent>()) {
+      event as DomKeyboardEvent;
+      if (event.key == 'Tab') {
+        return true;
+      }
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart:88]: I don't understand this comment, it says "simply by tabbing should not cause semantics to be enabled" but then it returns true if event.key is 'Tab'?

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 2]
```diff
@@ -1537,8 +1537,24 @@ abstract class DefaultTextEditingStrategy
...
+    } else if (_viewForElement(willGainFocusElement) == activeDomElementView) {
+      // If the focus stays within the same FlutterView, ensure the focus stays
+      // on the input element.
+      // WARNING: the motivation/reasoning behind this remains murky. It's
+      // unclear why, if the browser wants to remove focus from the input, we
+      // must insist that it stays on the element. This could lead to different
+      // elements/widgets fighting over who gets the focus, or resist to user's
+      // request to move focus elsewhere, which can be super-annoying UX. We
+      // should reevaluate what it is we're trying to do here. Perhaps there's a
+      // bette way.
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1557]:
```suggestion
      // better way.
```

Comment (ditman) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1557]: Also this WARNING should probably be a TODO with an associated issue?

File: engine/src/flutter/lib/web_ui/test/engine/semantics/semantics_helper_test.dart [hunk 3]
```diff
@@ -64,6 +64,24 @@ void testMain() {
       }
     });
 
+    test('Tab key should not enable semantics', () async {
+      final testSemanticsEnabler = FakeSemanticsEnabler();
+
+      // Tab should not enable semantics
+      {
+        final event = createDomKeyboardEvent('keydown', <String, Object>{'key': 'Tab'});
+        expect(testSemanticsEnabler.shouldEnableSemantics(event), isTrue);
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/test/engine/semantics/semantics_helper_test.dart:73]: "Tab should not enable semantics" -> expect(shouldEnableSemantics, isTrue)

Massively confused by this API :P

File: engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart [hunk 4]
```diff
@@ -5,20 +5,13 @@
...
 
 /// Tracks the [FlutterView]s focus changes.
 final class ViewFocusBinding {
   ViewFocusBinding(this._viewManager, this._onViewFocusChange);
 
-  /// Whether [FlutterView] focus changes will be reported and performed.
-  ///
-  /// DO NOT rely on this bit as it will go away soon. You're warned :)!
-  @visibleForTesting
-  static bool isEnabled = true;
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart:20]: I remember @tugorez having either an open PR for this, or an issue that should be marked as "fixed"/closed by this PR.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart (hunk 1 above)
Comment (ditman) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart:88]: This looks like a fix for a different issue, please list it in the "Fixes" of the description of this PR?

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 5]
```diff
@@ -1537,8 +1537,24 @@ abstract class DefaultTextEditingStrategy
...
-    if (willGainFocusElement == null ||
-        _viewForElement(willGainFocusElement) == activeDomElementView) {
+    if (willGainFocusElement == null) {
+      // If the element to gain focus is reported as `null`, it means that the
+      // window/iframe that Flutter runs in is losing focus. In this case, the
+      // engine signals to the framework to close the text input connection,
+      // allowing the focus to move elsewhere.
+      //
+      // This is fixing https://github.com/flutter/flutter/issues/155265.
+      textEditing.sendTextConnectionClosedToFrameworkIfAny();
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1547]: (This fix, LGTM!)

**Review by ditman — COMMENTED** [review]
This PR seems to be fixing 3 different problems/issues. Please make its description a little bit nicer, if you're planning on landing this! :

(And don't block on anything I've said :P)

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart (hunk 1 above)
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics_helper.dart:88]: The name of the method - `shouldEnableSemantics` - is misleading. `true` return value means "yes, forward the event to the framework; do not consume it". I plan to do some renaming, but not in this PR. The reason I included it in this PR is because as I was testing focus functionality I noticed that stumbling upon the placeholder threw off focus management because it enabled semantics and completely changed the DOM structure. With this fix I can cleanly leave and re-enter the iframe that hosts the Flutter app.

File: engine/src/flutter/lib/web_ui/test/engine/semantics/semantics_helper_test.dart (hunk 3 above)
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/test/engine/semantics/semantics_helper_test.dart:73]: I know! Me too.

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 6]
```diff
@@ -610,31 +610,61 @@ Future<void> testMain() async {
...
+        if (isSafari) {
+          // In Safari the web engine does not respond to blur, so there's no
+          // expectation that the input element keep focus.
+          expect(domDocument.activeElement, flutterView.dom.rootElement);
+        } else if (isFirefox) {
+          // This is a mysterious behavior in Firefox. Even though the engine does
+          // call <input>.focus() the browser doesn't move focus to the target
+          // element. This only happens in the test harness. When testing
+          // manually, Firefox happily moves focus to the input element.
+          expect(domDocument.activeElement, flutterView.dom.rootElement);
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:660]: Well, at least it behaves the same as Safari :P

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 7]
```diff
@@ -1535,8 +1535,25 @@ abstract class DefaultTextEditingStrategy
...
+    } else if (_viewForElement(willGainFocusElement) == activeDomElementView) {
+      // If the focus stays within the same FlutterView, ensure the focus stays
+      // on the input element.
+
+      // TODO(166857): the motivation/reasoning behind this remains murky.
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1550]: Please, follow [the style guide](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-checking-in-comments-that-ask-questions) for flutter TODOs:

> TODOs should include the string TODO in all caps, followed by the GitHub username of the person with the best context about the problem referenced by the TODO in parentheses. A TODO is not a commitment that the person referenced will fix the problem, it is intended to be the person with enough context to explain the problem. Thus, when you create a TODO, it is almost always your username that is given.

```suggestion
      // TODO(yjbanov): Make text input less grabby. See: https://github.com/flutter/flutter/issues/166857
      // The motivation/reasoning behind whay this is needed is murky.
```

File: engine/src/flutter/lib/web_ui/test/common/spy.dart [hunk 8]
```diff
@@ -37,16 +50,23 @@ class PlatformMessagesSpy {
...
+
   /// Start spying on platform messages.
   ///
   /// This is typically called inside a test's `setUp` callback.
   void setUp() {
     assert(!_isActive);
     _callback = (String channel, ByteData? data, PlatformMessageResponseCallback? callback) {
-      messages.add(PlatformMessage(channel, const JSONMethodCodec().decodeMethodCall(data)));
+      if (channel == 'flutter/lifecycle') {
+        strings.add(PlatformStringMessage(channel, const StringCodec().decodeMessage(data!)));
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/test/common/spy.dart:66]: Are we even using the `strings` anywhere in tests? Or is this to be able to listen to all channels, even `flutter/lifecycle`?

**Review by ditman — APPROVED** [review]
LGTM! Please fix the TODO to comply with the Flutter styleguide though!

**Comment by yjbanov** [comment]
@ksokolovskyi Thanks for the heads up! I'll test this scenario.

**Comment by mdebbar** [comment]
I'm taking over this PR.

@ksokolovskyi I think I fixed the issue you encountered. Would you mind checking again please?

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 9]
```diff
@@ -170,7 +170,10 @@ void _insertEditingElementInView(DomElement element, int viewId) {
     view != null,
     'Could not find View with id $viewId. This should never happen, please file a bug!',
   );
-  view!.dom.textEditingHost.append(element);
+  final host = view!.dom.textEditingHost;
+  if (!host.contains(element)) {
+    host.append(element);
+  }
```
Comment (ditman) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:176]: Oh, this prevents blurs because the element gets "moved" in the DOM when already inserted? I think this deserves a small comment so it doesn't get "optimized" in the future :P

**Comment by ksokolovskyi** [comment]
> I'm taking over this PR.
> 
> @ksokolovskyi I think I fixed the issue you encountered. Would you mind checking again please?

Hi @mdebbar, I was not able to reproduce the issue on Chrome, Safari, and Firefox. Thanks for the fix!

**Comment by kevmoo** [comment]
@ksokolovskyi – thank you SO MUCH for following along closely and verifying!

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart (hunk 9 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:176]: Exactly. Yes a comment is in order.
