### PR TITLE
Floating `SnackBar` should always float above the bottom widgets

### LINKED ISSUE #136162: SnackBarBehavior.floating works improperly with FloatingActionButtonLocation.endContained and M3 theme
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use Material 3 theming;
2. Create a view with `Scaffold` containing a `BottomAppBar` on the `bottomNavigationBar` attribute;
3. Have a FAB with `FloatingActionButtonLocation.endContained` on the same `Scaffold`;
4. Display a `SnackBar` with the `floating` behaviour;
5. `SnackBar` doesn't look floating.

### Expected results

`SnackBar` is expected to look like the screenshot 

Floating SnackBar

### Actual results

`SnackBar` does not look floating and seems to touch the `BottomAppBar`

Wrong Floating SnackBar

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorSchemeSeed: Colors.green,
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.endContained,
      bottomNavigationBar: const BottomAppBar(),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Content'),
                behavior: SnackBarBehavior.floating,
              ),
            );
          },
          child: const Text('Show SnackBar'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

Same screenshots from above for side-by-side comparison 
<details>
<summary>Screenshots / Video demonstration</summary>

| Right looking SnackBar | Wrong looking SnackBar |
|--------|--------|
| Floating SnackBar | Wrong Floating SnackBar | 

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output (stable)</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2283], locale en-CA)
    • Flutter version 3.13.6 on channel stable at C:\Users\Caio\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (12 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Caio\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at C:\Users\Caio\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #136162

This PR is to fix the floating `SnackBar` issue so that when the top of the bottom bar is higher than the top of the FAB, the snack bar will still float and not be clipped.

| Before fix | After fix |
|--------|--------|
| Screenshot 2023-10-11 at 1 54 30 PM | Screenshot 2023-10-11 at 1 54 52 PM
 | 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/snack_bar_test.dart [hunk 1]
```diff
@@ -2262,6 +2262,44 @@ void main() {
       },
     );
 
+    testWidgetsWithLeakTracking(
+      '${SnackBarBehavior.floating} should align SnackBar with the top of Scaffold '
```
Comment (HansMuller) [inline packages/flutter/test/material/snack_bar_test.dart:2266]: I think you mean: 

```suggestion
      '${SnackBarBehavior.floating} should align SnackBar with the top of BottomNavigationBar  '
```

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/material/snack_bar_test.dart (hunk 1 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/snack_bar_test.dart]: Ah right! Thanks for pointing this out.
