### PR TITLE
Include more details in the Red Box of Doom

### LINKED ISSUE #472: Display error number/cause/description when rendering red screen/widget (ErrorWidget)
If the framework encounters an error, it renders solid red. It might help us, and our developers, if we also displayed some hints as to what the error was.

The request is to display some sort of error number (which we can look up in the code), or if we have more space, display the cause of the error, on top of the red.

Then, users can report this error number or error message in bug reports.

Thanks!

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/472

### CODE REVIEW

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -1017,7 +1017,15 @@ abstract class Element<T extends Widget> implements BuildContext {
 }
 
 class ErrorWidget extends LeafRenderObjectWidget {
-  RenderBox createRenderObject() => new RenderErrorBox();
+  ErrorWidget(Object exception) : message = _stringify(exception), super(key: new GlobalKey());
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: Why new GlobalKey ?

Comment (abarth) [inline packages/flutter/lib/src/widgets/framework.dart]: If you're just trying to force this to not sync with the previous widget, you can create a new ObjectKey(new Object()).  That's less likely to cause problems if, for example, the global key table is corrupt.

**Comment by abarth** [comment]
LGTM

Can you usually see the text of the error?  I guess it comes out in the log too.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: Oh, yeah, good call.

And yes, the idea here is to make sure we never sync with it. (In part because I intentionally don't implement the updateRenderObject protocol here, and the RenderErrorBox is immutable.)

File: packages/flutter/lib/src/rendering/error.dart [hunk 2]
```diff
@@ -36,8 +77,36 @@ class RenderErrorBox extends RenderBox {
...
+
+  /// The text style to use when painting [RenderErrorBox] objects.
+  static ui.TextStyle textStyle = new ui.TextStyle(
+    color: const Color(0xFFFFFF00),
+    fontFamily: 'monospace',
+    fontSize: 7.0
+  );
+
+  /// The paragraph style to use when painting [RenderErrorBox] objects.
+  static ui.ParagraphStyle paragraphStyle = new ui.ParagraphStyle(
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/error.dart]: const

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: (I used a `UniqueKey`.)

File: packages/flutter/lib/src/rendering/error.dart [hunk 3]
```diff
@@ -36,8 +77,36 @@ class RenderErrorBox extends RenderBox {
     size = constraints.constrain(const Size(_kMaxWidth, _kMaxHeight));
   }
 
+  /// The color to use when painting the background of [RenderErrorBox] objects.
+  static Color backgroundColor = const Color(0xF0900000);
+
+  /// The text style to use when painting [RenderErrorBox] objects.
+  static ui.TextStyle textStyle = new ui.TextStyle(
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/error.dart]: We'll be able to make them const constructable once Dart has const functions.

File: packages/flutter/lib/src/rendering/error.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/error.dart]: ui.ParagraphStyle isn't const-constructable either.

File: packages/flutter_test/lib/src/widget_tester.dart [hunk 4]
```diff
@@ -78,7 +78,7 @@ class WidgetTester extends Instrumentation {
       super(binding: _SteppedWidgetFlutterBinding.ensureInitialized()) {
     timeDilation = 1.0;
     ui.window.onBeginFrame = null;
-    runApp(new ErrorWidget()); // flush out the last build entirely
+    runApp(new Container(key: new UniqueKey())); // flush out the last build entirely
```
Comment (Hixie) [inline packages/flutter_test/lib/src/widget_tester.dart]: i changed this one to a UniqueKey too.

**Comment by Hixie** [comment]
I tried making a toolbar blow up and I could read the error. Whether it's readable in any particular case will depend on how big the box is.
