### PR TITLE
fix reorderable_list drop animation

### LINKED ISSUE #138994: ReorderableListView animates incorrectly when items have different heights
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a `ReorderableListView` where one item has a different height.
2. Try dragging the elements around.
3. Certain elements will animate to the wrong ending location.

### Expected results

For the boxes to animate towards their actual final position.

### Actual results

In the video below, notice how the pink and cyan boxes drift upwards before snapping to their correct location.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final colors = [
    Colors.red,
    Colors.blue,
    Colors.green,
    Colors.orange,
    Colors.purple,
    Colors.pink,
    Colors.cyan
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('ReorderableListView'),
      ),
      body: ReorderableListView(
        children: colors
            .map((color) => Box(
                  key: ValueKey(color),
                  color: color,
                ))
            .toList(),
        onReorder: (int oldIndex, int newIndex) {
          if (newIndex > oldIndex) newIndex--;
          setState(() {
            final color = colors.removeAt(oldIndex);
            colors.insert(newIndex, color);
          });
        },
      ),
    );
  }
}

class Box extends StatelessWidget {
  final Color color;
  final bool big;

  Box({super.key, required this.color}) : big = color == Colors.green;

  Widget build(BuildContext context) {
    return Container(
      height: big ? 100 : 20,
      margin: EdgeInsets.all(1.0),
      color: color,
    );
  }
}
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/29797357/640b2897-4eeb-4ac9-b525-60da64eb46a7

</details>

### Logs

<details><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/riley/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (9 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.5 22G74 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
This PR fixes reorderable_list drop animation.

Fixes #138994 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -802,40 +802,29 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
...
-      return;
-    }
     setState(() {
-      if (_insertIndex == item.index) {
-        _finalDropPosition = _itemOffsetAt(_insertIndex! + (_reverse ? 1 : 0));
-      } else if (_insertIndex! < widget.itemCount - 1) {
-        // Find the location of the item we want to insert before
-        _finalDropPosition = _itemOffsetAt(_insertIndex!);
+      if (_reverse) {
+        if (_insertIndex! == item.index) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:807]: Since this same case is repeated below on 819 in the following else, can this instead be reworked to contain the `_insertIndex! == item.index` case outside of whether or not it is reversed? Might be easier to follow then

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 2]
```diff
@@ -974,9 +963,9 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
     return Rect.fromLTWH(origin.dx, origin.dy, _dragInfo!.itemSize.width, _dragInfo!.itemSize.height);
   }
 
-  Offset _itemOffsetAt(int index) {
-    final RenderBox itemRenderBox =  _items[index]!.context.findRenderObject()! as RenderBox;
-    return itemRenderBox.localToGlobal(Offset.zero);
+  Offset _itemOffsetAt(int index, {bool extent = false}) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:966]: What does `extent` here represent?

**Review by Piinks — COMMENTED** [review]
Hey @yiiim thanks for contributing a fix!

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 1 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:807]: The handling of `_insertIndex! == item.index` is different depending on the value of `_reverse`. In the case where `_reverse` is true, we offset the item's own extent, but in the case where `_reverse` is false, we don't need to do this. Therefore, it's not possible to take this case out of the _reverse condition. I believe the current implementation is the most straightforward way to handle these different scenarios.

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 2 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:966]: The `extent` parameter in the `_itemOffsetAt` function determines which corner of the item's geometry we are interested in. If `extent` is `true`, we return the 'end' corner of the item - the bottom right corner for vertical scrolling and the top right corner for horizontal scrolling. If `extent` is `false`, we return the 'start' corner of the item - the top left corner for both vertical and horizontal scrolling. This allows us to calculate the offset of the item in the list based on its position and size.

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:807]: I still find the code very difficult to follow. The prior implementation incorporated reverse in the if clauses or when making the function calls. It is hard to tell what has actually changed here.

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:966]: Thank you for explaining! Maybe we should just pass in the correct geometry rather than a bool. I think that would be easier for maintainers to follow.

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 1 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: Got it, I fixed some code, please continue the review

**Comment by yiiim** [comment]
@Piinks Hi, Are you still continuing the review?

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 3]
```diff
@@ -1405,6 +1406,83 @@ void main() {
       await tester.pumpAndSettle();
     },
   );
+
+  testWidgetsWithLeakTracking('Tests the correctness of the drop animation in various scenarios', (WidgetTester tester) async {
+    late Size screenSize;
```
Comment (Piinks) [inline packages/flutter/test/widgets/reorderable_list_test.dart:1411]:
```suggestion
  testWidgetsWithLeakTracking('Tests the correctness of the drop animation in various scenarios', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/138994
    late Size screenSize;
```

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for contributing

**Review by HansMuller — APPROVED** [review]
LGTM
