### PR TITLE
[Widget Inspector] Fix missing cupertino icon in on-device inspector

### LINKED ISSUE #168846: [Widget Inspector] New on-device button missing icon if Flutter app doesn't depend on `cupertino_icons`
While working on https://github.com/flutter/flutter/pull/167677, I unwittingly tested the changes only on apps  had a dependency on `cupertino_icons`. 

If an app does not have a dependency on `cupertino_icons`, then the new on-device inspector button (which uses the `CupertinoIcon.cursor_rays` icon) displays a `[?]`. 

I believe we need to add an explicit dependency on `cupertino_icons` to `package:flutter` to be able to use it in the on-device inspector. 

### What the button looks like for apps not importing `cupertino_icons`:

Image

### What the button is supposed to look like:

Image

### PR DESCRIPTION
**Pull request by elliette**
Resolves https://github.com/flutter/flutter/issues/168846

This is a follow-up to https://github.com/flutter/flutter/pull/167677. For apps that do not import `package:cupertino_icons`, the new on-device button's icon shows up as a `[?]`.

This fix:
* adds an explicit dependency on `package:cupertino_icons` to the framework
* imports `CupertinoIcons` into `lib/src/widgets/app.dart` 

*Note: For some reason, adding the import to `packages/flutter/lib/src/material/app.dart` and `packages/flutter/lib/src/cupertino/app.dart` did not resolve the issue. That's why I've added it to `lib/src/widgets/app.dart`, even though it's not actually used in that file.*

**Let me know if this is acceptable!** (cc @Piinks) I'm guessing we might not want to add a dependency on `cupertino_icons` to the Framework (this might even be breaking change?) so if not, it might make sense to use a different icon for the on-device inspector. Thanks!

### CODE REVIEW

File: packages/flutter/lib/src/widgets/app.dart [hunk 1]
```diff
@@ -12,6 +12,8 @@ library;
 
 import 'dart:collection' show HashMap;
 
+// ignore: unused_import, required for the Widget Inspector's on-device button.
+import 'package:flutter/cupertino.dart' show CupertinoIcons;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/app.dart:16]: Importing cupertino into the widgets library is layer violation and I don't think the analyzer script is going to like this.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/app.dart:16]: Uhm I don't see the symbols imported from `CupertinoIcons` being used anywhere. Does it work without this import?

Comment (elliette) [reply packages/flutter/lib/src/widgets/app.dart:16]: Unfortunately no, that's why I added this note to the PR:

> For some reason, adding the import to packages/flutter/lib/src/material/app.dart and packages/flutter/lib/src/cupertino/app.dart did not resolve the issue. That's why I've added it to lib/src/widgets/app.dart, even though it's not actually used in that file.

I first tried adding the import to where we are actually using the icon (in the two files mentioned above) however despite that change I was still seeing the `[?]` instead of the icon. I do not understand why though 😕

**Review by Piinks — CHANGES_REQUESTED** [review]
> * adds an explicit dependency on package:cupertino_icons to the framework
> * imports CupertinoIcons into lib/src/widgets/app.dart

These are not things we can do. Is there another solution we can explore?

File: packages/flutter/lib/src/widgets/app.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/app.dart:16]: You tested in debug mode (so no icon tree shaking) right? In that case I don't know off the top of my head. I'll try to debug this.

**Comment by Piinks** [comment]
> Add a png asset to the framework that we could be used for the on-device button

We need to avoid checking in binary assets in this repository.

> Use a Material icon for the on-device button

If we need to import it into the widgets layer, we run into the same issue. The widgets layer and below cannot establish a dependency on a higher design level.

What about using unicode characters for a generic icon?
We did this in TreeSliver to manage these constraints: https://github.com/flutter/flutter/blob/606bb06c0fbf5899a93e47e31a254de7f2aee5a7/packages/flutter/lib/src/widgets/sliver_tree.dart#L576

**Comment by elliette** [comment]
Importing `cupertino_icons` into `lib/src/material/app.dart` and `lib/src/cupertino/app.dart` actually does work (thank you@LongCatIsLooong for pointing that out! I'm guessing there was some user error on my part that made it seem it wasn't working) However, I'm guessing this still isn't possible due to the direct dependency on `cupertino_icons` in the framework's pubspec, is that correct @Piinks ?

> If we need to import it into the widgets layer, we run into the same issue. The widgets layer and below cannot establish a dependency on a higher design level.

Fortunately, we wouldn't be importing this directly into the widgets layer, the Material and Cupertino styled on-device buttons are defined in `packages/flutter/lib/src/material/app.dart ` and `packages/flutter/lib/src/cupertino/app.dart`, and then "imported" into the widgets layer via these button builders: https://github.com/flutter/flutter/blob/606bb06c0fbf5899a93e47e31a254de7f2aee5a7/packages/flutter/lib/src/widgets/app.dart#L1044-L1065

**Comment by Piinks** [comment]
I am wary of adding cupertino_icons as a dependency to the framework. The framework needs to separate itself from design, not integrate more with it. I understand the cupertino icons are aesthetically pleasing, but I don't think that justifies adding themas a dependency for this one feature.

**Comment by elliette** [comment]
> I am wary of adding cupertino_icons as a dependency to the framework. The framework needs to separate itself from design, not integrate more with it. I understand the cupertino icons are aesthetically pleasing, but I don't think that justifies adding them as a dependency for this one feature.

Got it! I've updated the PR to use a Material icon and remove the dependency of `cupertino_icons`. This does mean we are now importing the Material icons into `lib/src/cupertino/app.dart`, let me know if this is okay. 

Here is what it looks like now:

Material-themed app
Screenshot 2025-05-14 at 4 00 34 PM

Cupertino-themed app
Screenshot 2025-05-14 at 4 01 45 PM

**Review by kenzieschmoll — APPROVED** [review]

**Comment by elliette** [comment]
Switched to a generic unicode symbol for both Material and Cupertino per @Piinks original suggestion 😅  Thanks for your patience with all the back-and-forth! This should be ready for review now. 

Material app:
Screenshot 2025-05-15 at 10 22 55 AM

Cupertino app:
Screenshot 2025-05-15 at 10 05 40 AM

**Review by Piinks — APPROVED** [review]
Ah thank you! So glad unicode had some good options.
LGTM
