### PR TITLE
Date picker layout exceptions

### LINKED ISSUE #21383: DatePicker dialog overflows on large screen
Hi, i have an issue with the datepicker dialog on a BLU STUDIO G2 with a large screen, the dialog bottom is overflowed by 39 pixels, so the "Accept" and "Cancel" button are inaccessible.

## Steps to Reproduce

On my code:

**My theme:**

```dart
final ThemeData mainTheme = new ThemeData(
  brightness: Brightness.dark,
  primaryColor: Colors.white,
  accentColor: Colors.lightBlue,
  splashColor: Colors.lightBlue,
  textTheme: TextTheme(
    headline: TextStyle(color: Colors.black),
    subhead: TextStyle(color: Colors.white70),
    body1: TextStyle(color: Colors.white),
    caption: TextStyle(color: Colors.blue),
  ),
  primaryTextTheme: TextTheme(
    headline: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
    subhead: TextStyle(color: Colors.black54, fontStyle: FontStyle.italic),
    body1: TextStyle(color: Colors.black),
    body2: TextStyle(color: Colors.white),
    display2: TextStyle(color: Colors.black54),
    display3: TextStyle(color: Colors.black),
  ),
);
```

**The DatePicker:**

```
final DateTime picked = await showDatePicker(
        context: context,
        initialDate: selectedDate,
        firstDate: selectedDate,
        lastDate: new DateTime(2101)
    );
```

## Logs
```
I/flutter (22738): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22738): The following message was thrown during layout:
I/flutter (22738): A RenderFlex overflowed by 39 pixels on the bottom.
I/flutter (22738): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter (22738): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (22738): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (22738): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (22738): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter (22738): This is considered an error condition because it indicates that there is content that cannot be
I/flutter (22738): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter (22738): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter (22738): like a ListView.
I/flutter (22738): The specific RenderFlex in question is:
I/flutter (22738):   RenderFlex#e5936 relayoutBoundary=up7 OVERFLOWING
I/flutter (22738):   creator: Column ← SizedBox ← LayoutBuilder ← OrientationBuilder ← DefaultTextStyle ←
I/flutter (22738):   AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#65434 ink renderer] ←
I/flutter (22738):   NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape
I/flutter (22738):   ← _MaterialInterior ← ⋯
I/flutter (22738):   parentData: <none> (can use size)
I/flutter (22738):   constraints: BoxConstraints(w=240.0, 0.0<=h<=449.3)
I/flutter (22738):   size: Size(240.0, 449.3)
I/flutter (22738):   direction: vertical
I/flutter (22738):   mainAxisAlignment: start
I/flutter (22738):   mainAxisSize: min
I/flutter (22738):   crossAxisAlignment: stretch
I/flutter (22738):   verticalDirection: down
I/flutter (22738): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (22738): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
## Flutter Doctor
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.15063], locale en-US)
   • Flutter version 0.5.1 at C:\flutter
   • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
   • Engine revision 1ed25ca7b7
   • Dart version 2.0.0-dev.58.0.flutter-f981f09760
                                                                                                                                                                            [
!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
   • Android SDK at F:\sdk
   • Android NDK location not configured (optional; useful for native profiling support)
   • Platform android-27, build-tools 27.0.3
   • ANDROID_HOME = F:\sdk
   • Java binary at: C:\Program Files\JetBrains\Android Studio 3.0\jre\bin\java
   • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)                                                                                                 
   X Android license status unknown.
                                                                                                                                                                            [
√] Android Studio (version 3.0)
  • Android Studio at C:\Program Files\Android\Android Studio
  • Flutter plugin version 22.2.1
  • Dart plugin version 171.4424
  • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
                                                                                                                                                                           [√
[√] Android Studio (version 3.0)
   • Android Studio at C:\Program Files\JetBrains\Android Studio 3.0
   • Flutter plugin version 22.2.1
   • Dart plugin version 171.4424
   • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)
                                                                                                                                                                            [
!] IntelliJ IDEA Ultimate Edition (version 2017.2)
   • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.2                                                                                                            
   X Flutter plugin not installed; this adds Flutter specific functionality.                                                                                                
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

## Pictures:
blu studio g2 version de android 6 0
device-2018-09-03-214820

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

This PR addresses several layout issues with the Material Date Picker when displaying on smaller sized devices or with an increased text scale factor. It removes several hard coded sizes that were causing the layouts to overflow. This change will lead to some awkward layouts with scrolling the month grid vertically, but it should no longer throw overflow exceptions. We will address smaller layouts more fully in a future update.

### Example of layout fixes

Before/After on a Pixel with Large Text scale selected:

Before After Pixel Large Text

Before/After on a Pixel with a Chinese locale:

Before After Pixel Chinese

Before/After on a small display (320x521) with Large Text scale selected:

Before After Small Display Large Text

## Related Issues

Fixes: #21383, #20171, #19744, #17745

## Tests

I added the following tests:

- A group of device configuration tests that will try to bring up the date picker in various sized screens, orientations and text scale factors.

- A group of device configuration tests to the flutter_localizations tests to bring up the date picker in various locales that were having issues with layout.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/date_picker.dart [hunk 1]
```diff
@@ -682,7 +676,6 @@ class _MonthPickerState extends State<MonthPicker> with SingleTickerProviderStat
   @override
   Widget build(BuildContext context) {
     return SizedBox(
-      width: _kMonthPickerPortraitWidth,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/date_picker.dart]: Looking at this through the github review microsope ... it seems odd to configure the height of the MonthPicker with _kMaxDayPickerHeight. If that's intentional, maybe a comment that explains why.

File: packages/flutter/test/material/date_picker_test.dart [hunk 2]
```diff
@@ -774,3 +777,70 @@ void _tests() {
     expect(tester.getBottomLeft(find.text('OK')).dx, 800 - ltrOkRight);
   });
 }
+
+void _screenConfigTests() {
+
+  const Size kPixel1Portrait = Size(1070, 1770);
```
Comment (HansMuller) [inline packages/flutter/test/material/date_picker_test.dart]: A comment about these sizes, like what they're based on, why we chose them, would be helpful.

File: packages/flutter/test/material/date_picker_test.dart [hunk 3]
```diff
@@ -774,3 +777,70 @@ void _tests() {
     expect(tester.getBottomLeft(find.text('OK')).dx, 800 - ltrOkRight);
   });
 }
+
+void _screenConfigTests() {
+
```
Comment (HansMuller) [inline packages/flutter/test/material/date_picker_test.dart]: Please insert a comment (probably several) like this here:
```
// Regression test for https://github.com/flutter/flutter/issues/21383
```

Or, if it makes more sense, in the specific `testWidgets` tests.

File: packages/flutter/test/material/date_picker_test.dart [hunk 4]
```diff
@@ -774,3 +777,70 @@ void _tests() {
...
+          },
+        ),
+      ),
+    );
+    await tester.tap(find.text('X'));
+    await tester.pumpAndSettle();
+  }
+
+  testWidgets('display on Pixel1 - portrait', (WidgetTester tester) async {
+    await _showPicker(tester, kPixel1Portrait);
```
Comment (HansMuller) [inline packages/flutter/test/material/date_picker_test.dart]: These tests are verifying that we don't assert. Just to make that clear it would be good to append:
```
 expect(tester.takeException(), isNull);
```

File: packages/flutter_localizations/test/date_picker_test.dart [hunk 5]
```diff
@@ -223,6 +223,59 @@ void main() {
 
     await tester.tap(find.text('ANNULER'));
   });
+
+  group('screen configurations', () {
```
Comment (HansMuller) [inline packages/flutter_localizations/test/date_picker_test.dart]: What these tests have in common seems to be that we're varying locale?

File: packages/flutter_localizations/test/date_picker_test.dart [hunk 6]
```diff
@@ -223,6 +223,59 @@ void main() {
...
+
+    const Size kPixel1Portrait = Size(1070, 1770);
+    const Size kPixel1Landscape = Size(1770, 1070);
+    Future<void> _showPicker(WidgetTester tester, Locale locale, Size size) async {
```
Comment (HansMuller) [inline packages/flutter_localizations/test/date_picker_test.dart]: add a blank line here?

File: packages/flutter_localizations/test/date_picker_test.dart [hunk 7]
```diff
@@ -223,6 +223,59 @@ void main() {
 
     await tester.tap(find.text('ANNULER'));
   });
+
+  group('screen configurations', () {
+
+    const Size kPixel1Portrait = Size(1070, 1770);
```
Comment (HansMuller) [inline packages/flutter_localizations/test/date_picker_test.dart]: As before, maybe there's something to say about the sizes

**Review by HansMuller — COMMENTED** [review]
This looks good, just some minor feedback. 

It would be helpful if the issue's description included a few before/after screenshots that illustrated the layout changes.

File: packages/flutter/lib/src/material/date_picker.dart [hunk 8]
```diff
@@ -493,6 +486,7 @@ class DayPicker extends StatelessWidget {
             child: GridView.custom(
               gridDelegate: _kDayPickerGridDelegate,
               childrenDelegate: SliverChildListDelegate(labels, addRepaintBoundaries: false),
+              padding: EdgeInsets.zero,
```
[the remark this answers is not in the document]
Comment (darrenaustin) [reply packages/flutter/lib/src/material/date_picker.dart]: I don't think so, as this GridView is embedded in a PageView.builder which puts the dialog header above it. If this padding isn't set to zero, by default there is an unneeded gap at the top of the grid, which will make it more likely that it will need to scroll on smaller screens.

File: packages/flutter/lib/src/material/date_picker.dart (hunk 1 above)
Comment (darrenaustin) [reply packages/flutter/lib/src/material/date_picker.dart]: Yeah, this is a bit weird. The MonthPicker just wraps the DayPicker with horizontal navigation to switch months. I added a comment that hopefully makes this easier to follow.

File: packages/flutter/test/material/date_picker_test.dart (hunk 2 above)
Comment (darrenaustin) [reply packages/flutter/test/material/date_picker_test.dart]: Just pushed a fix that renamed them and commented them with hopefully better descriptions.

File: packages/flutter/test/material/date_picker_test.dart (hunk 3 above)
Comment (darrenaustin) [reply packages/flutter/test/material/date_picker_test.dart]: Done.

File: packages/flutter/test/material/date_picker_test.dart (hunk 4 above)
Comment (darrenaustin) [reply packages/flutter/test/material/date_picker_test.dart]: Nice suggestion. I have added this to all the tests.

File: packages/flutter_localizations/test/date_picker_test.dart (hunk 5 above)
Comment (darrenaustin) [reply packages/flutter_localizations/test/date_picker_test.dart]: I renamed this group to "locale fonts don't overflow layout". Couldn't think of a better description. Let me know if you have one :).

File: packages/flutter_localizations/test/date_picker_test.dart (hunk 6 above)
Comment (darrenaustin) [reply packages/flutter_localizations/test/date_picker_test.dart]: Done.

File: packages/flutter_localizations/test/date_picker_test.dart (hunk 7 above)
Comment (darrenaustin) [reply packages/flutter_localizations/test/date_picker_test.dart]: Done.

**Review by HansMuller — APPROVED** [review]
LGTM
