### PR TITLE
Fix Hit Tests in RenderEditable when Scrolled

### LINKED ISSUE #81038: TextField Hit Tests broken when Scrolled
## Bug

Here is a visualization of the bug:

https://user-images.githubusercontent.com/19204050/115869141-fde39980-a42c-11eb-9555-0441da9a5586.mp4

You can see that I set up `TextSpan`s using [`TextSpan.recognizer`](https://api.flutter.dev/flutter/painting/TextSpan/recognizer.html) and the newly added `TextSpan.onMousEnter` (see https://github.com/flutter/flutter/pull/77754 cc @dkwingsmt).

When the `TextField` is **not scrolled**, the hit detection works correctly. But as soon as it is scrolled, the hit detection is broken.

### Details

If you pay close attention, you will notice that the **hit tests** are _**not transformed**_. That is, the hit events are still dispatched as if the `TextField` was not scrolled. This means the "TextSpan" `onMouseEnter` is triggered where the text span **would have been** if the enclosing `TextField` was not scrolled.

## Steps to Reproduce

1. `flutter channel dev`
2. `flutter upgrade -f`
3. `flutter create bug`
4. `cd bug`
5. Replace `lib/main.dart` with this:

<details><summary>Click to expand main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: SizedBox(
          width: 300,
          height: 100,
          child: ColoredBox(
            color: Colors.grey[400]!,
            child: TextField(
              controller: _FooController(),
              maxLines: null,
              expands: true,
              readOnly: true,
            ),
          ),
        ),
      ),
    ),
  ));
}

class _FooController extends TextEditingController {
  _FooController() : super(text: '''
This is a very long example text, where only the first word will be highlighted.

On hovering the first "This", you should see a print in the console, which will
also report the position that the hit event was captured at.

After scrolling, you will still see the same hit event in the console in the
top-left corner, even though the first "This" has been scrolled out-of-view.

Consequently, hit tests seem to not be transformed in TextField's that are
scrolled (bug).
''');

  @override
  TextSpan buildTextSpan(
      {required BuildContext context,
      TextStyle? style,
      required bool withComposing}) {
    return TextSpan(
      style: style,
      children: [
        TextSpan(
          text: text.substring(0, 4),
          onEnter: (_) {
            print('${_.localPosition} ${DateTime.now()}');
          },
          style: TextStyle(
            backgroundColor: Theme.of(context).colorScheme.primary,
          ),
        ),
        TextSpan(
          text: text.substring(4),
        ),
      ],
    );
  }
}

```

</details>

6. `flutter run -d chrome --web-renderer canvaskit`
7. Hover over the first `"This"` → see a log in the console
8. Scroll the text field, so `"This"` is out of view.
9. Hover over where the first "This" **was** befire → log is still in the console → **_BUG_**

Here is the demo:

https://user-images.githubusercontent.com/19204050/115871707-6da75380-a430-11eb-9837-129b26416df2.mp4

You can see "This" is long out-of-view, but the hit test is still triggered.

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
This fixes `hitTestChildren` in `RenderEditable` by respecting the scroll `offset` (`_paintOffset` for applying the scroll axis).

Before, hit tests were broken when the `EditableText`/`TextField` was scrolled.

### Issues

Fixes #81038.

### Tests

The first test case I added was passing before (making sure that my change does not make that fail) and the latter two test cases were failing before.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
The change looks good to me. Could you create a `RenderEditable` with a non-zero offset, and call `hitTest` on it to see if the method is doing the right thing? It's probably the easiest to follow the example of tests in "test/rendering/editable_test.dart"

**Comment by creativecreatorormaybenot** [comment]
@LongCatIsLooong Thanks for the hint. I am working on the tests and will probably have them ready in a few 👍

**Comment by creativecreatorormaybenot** [comment]
I added the test cases 👍 Note that the first test case I added was passing before (making sure that my change does not make that fail) and the latter two test cases were failing before.

File: packages/flutter/test/rendering/editable_test.dart [hunk 1]
```diff
@@ -3330,6 +3331,137 @@ void main() {
...
+          ),
+        );
+        layout(editable, constraints: BoxConstraints.loose(const Size(500.0, 500.0)));
+        // Prepare for painting after layout.
+        pumpFrame(phase: EnginePhase.compositingBits);
+
+        final BoxHitTestResult result = BoxHitTestResult();
+        // At x=5, we should hit "B" as we are scrolled to the left by 5
+        // pixels.
+        editable.hitTest(result, position: const Offset(5.0, 0));
```
Comment (LongCatIsLooong) [inline packages/flutter/test/rendering/editable_test.dart:3458]: 5.0 is right on the boundary and can go either way. This may have to do with the web test failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8849033682682636208/+/steps/run_test.dart_for_web_tests_shard_and_subshard_3/0/logs/stdout/0. Could you try 6 or something instead?

Comment (creativecreatorormaybenot) [reply packages/flutter/test/rendering/editable_test.dart]: Sure, I had it at `5.1` first but it felt somehwhat arbitrary. But it does make sense to use a safe value 👍

**Review by LongCatIsLooong — APPROVED** [review]
