### PR TITLE
[Android] Actually remove dev dependencies from release builds

### LINKED ISSUE #160407: `flutter config --explicit-package-dependencies` breaks `flutter build apk`
Looking at the failures still being flagged in https://github.com/flutter/flutter/pull/160289, I see a trend where `flutter build apk` (which implicitly is release mode) causes the `integration_test` package itself to fail to be built ([example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8728333052554778833/+/u/run_plugin_dependencies_test/stdout)); I'm guessing that when we short-circuit the build, we're still leaving artifacts that `integration_test` is depended on, but not in a way that compilation succeeds.

Reproduces at HEAD:

```sh
# Opt-in to the feature
flutter config --explicit-package-dependencies

# Create an Android plugin
flutter create plugin_a --template=plugin --platforms=android

# Try to build the example app for the plugin
cd plugin_a/example
flutter build apk
```

By opting-out again (`flutter config --no-explicit-package-dependencies`) the build succeeds.

Interestingly, the [integration test for this feature](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart) _does_ do a `flutter build apk --release`, so I'm guessing this has something to do with how `integration_test` imports and uses the Android embedder (i.e. `import io.flutter.embedding.android.FlutterActivity` and like), and the default (empty) plugin template does not - we should add a regression test as part of fixing this.

---

Some potentially useful bits:

<details>

<summary>With the flag enabled, <code>.flutter-plugins-dependencies</code> looks like this</summary>

```json
{
  "info": "This is a generated file; do not edit or check into version control.",
  "plugins": {
    "ios": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": true
      }
    ],
    "android": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": true
      },
      {
        "name": "plugin_a",
        "path": "/private/tmp/flutter.tmp/plugin_a/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": false
      }
    ],
    "macos": [],
    "linux": [],
    "windows": [],
    "web": []
  },
  "dependencyGraph": [
    {
      "name": "integration_test",
      "dependencies": []
    },
    {
      "name": "plugin_a",
      "dependencies": []
    }
  ],
  "date_created": "2024-12-16 20:52:06.884223",
  "version": "3.28.0-1.0.pre.157",
  "swift_package_manager_enabled": {
    "ios": false,
    "macos": false
  }
}
```

</details>

<details>

<summary>Here is what <code>plugin_a/pubspec.yaml</code> looks like</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter

  plugin_a:
    # When depending on this package from a real application you should use:
    #   plugin_a: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
```

</details>

I assume it's further work required in `flutter.groovy`: https://github.com/flutter/flutter/blob/27ef1967b09e32971075bae06309f742625f7237/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L764-L829

### PR DESCRIPTION
**Pull request by camsim99**
Revises https://github.com/flutter/flutter/pull/158026 to fix https://github.com/flutter/flutter/issues/160407.

Makes a number of fixes:

- Fixes Groovy logic that attempted to remove dev dependencies from release builds to use `<buildType>Api` versus `api` and loop to configure the project dependencies per build type
- Adds back dependency on embedding to plugin projects since this is needed regardless (the plugin may not be included in a particularly typed build but it still needs it for where it's included)
- Fixes integration test to throw and error upon failure, check right APK for the release build it's testing, and configure the flag need for `.flutter-plugin-dependencies` to mark plugins as dev dependencies as expected
- Uses @matanlurey's [patch](https://github.com/flutter/flutter/issues/160407#issuecomment-2547546038) to remove dev dependency from the `GeneratedPluginRegistrant` in release mode

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -1907,7 +1907,10 @@ Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
         // The preview device does not currently support any plugins.
         allowedPlugins = PreviewDevice.supportedPubPlugins;
       }
-      await project.regeneratePlatformSpecificTooling(allowedPlugins: allowedPlugins);
+      await project.regeneratePlatformSpecificTooling(
+        allowedPlugins: allowedPlugins,
+        releaseMode: getBuildMode().isRelease,
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:1912]: We want to provide this only when the feature flag`--explicit-package-dependencies` is enabled, otherwise we'll start stripping plugin registrations.

File: packages/flutter_tools/lib/src/flutter_plugins.dart
Comment (matanlurey) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:1]: After looking at this again, there is no reason to only strip for Android.

We should remove the plugins from the list for _all_ platforms if release is `true` (which itself is guarded behind the feature flag), instead of filtering down at the Android level (my original prototype was Android-specific as I was just debugging).

If you want to do this as a follow-up, add a TODO and file a GH issue - that's OK with me.

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy [hunk 2]
```diff
@@ -737,17 +737,29 @@ class FlutterPlugin implements Plugin<Project> {
...
-            if (flutterBuildMode != "release" || !pluginObject.dev_dependency) {
-                // Only add dependency on dev dependencies in non-release builds.
-                project.dependencies {
-                    api(pluginProject)
+        project.android.buildTypes {
+            // Add profile build type since it may not already exist.
+            profile {
+                initWith(debug)
+                if (it.hasProperty("matchingFallbacks")) {
+                    matchingFallbacks = ["debug", "release"]
```
Comment (camsim99) [inline packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:745]: I'm not 100% confident on this. TLDR is that the profile mode has to exist in order for us to specify `profileApi`, but typically it's defined after this method is called. I added it redundantly here to make sure it exists before. I left the other one because I assume it needs it for the case where there are no plugins, but I'll double check.

**Review by matanlurey — CHANGES_REQUESTED** [review]
In general looks good, one required change and one change _or_ TODO, your choice.

File: packages/flutter_tools/lib/src/flutter_plugins.dart
Comment (camsim99) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:1]: I'll opt for the TODO to make sure this gets landed, but quick question: wouldn't this be problematic for platforms that are not actually removing the dev dependencies in release mode?

Comment (matanlurey) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:1]: I don't think so - it would just be _insufficient_.

That is, imagine you have a plugin called `SuperTestPlugin`. Currently we generate something like:

```java
GeneratedPluginRegistrar() {
  addPlugin(com.foo.bar.SuperTestPlugin());
}
```

If this is a _dev_-dependency plugin, and it's in release mode, that plugin won't exist, so we generate:

```java
GeneratedPluginRegistrar() {}
```

... and the code you have elsewhere in this PR additionally ensures the code doesn't ship in the release build.

Now imagine we're on say, iOS. We'd still generate:

```swift
GeneratedPluginRegistrar() {}
```

... but still ship it in the release build, it just wouldn't be operative.

In other words, that change would correctly not _add_ the plugin at runtime, but we would still have more work to do on other platforms (i.e. iOS), /cc @cbracken, to exclude it from the build. So I don't think it would be problematic - just rather incomplete - but also less confusing I think?

Comment (camsim99) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:1]: Ok ok I see. I'll file an issue.

Comment (camsim99) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:1]: https://github.com/flutter/flutter/issues/161348, linked in the code

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy (hunk 2 above)
Comment (matanlurey) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:745]: If you intend to double check before submitting, ACK, otherwise let's add a TODO/GH issue as well before submitting.

**Review by matanlurey — APPROVED** [review]
LGTM, 1 more question that can be ACK'd or TODOd.

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy (hunk 2 above)
Comment (camsim99) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:745]: oh ack! I checked. I think based on how other things are written in the plugin, this should be fine.

Comment (camsim99) [reply packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:745]: Had an idea to slightly clean this up so gonna do that before this lands

**Comment by camsim99** [comment]
The `Linux gradle_plugin_light_apk_tests` is a legit failure that means this fix requires more work. We need to make sure the plugin dependency is added to for any custom build type a developer may specify to land this.

**Comment by matanlurey** [comment]
> We need to make sure the plugin dependency is added to for any custom build type a developer may specify to land this.

Can you expand on that? What is a "custom build type", you mean something other than debug/profile/release?

**Comment by camsim99** [comment]
> Can you expand on that? What is a "custom build type", you mean something other than debug/profile/release?

Yeah. The test that is failing uses a custom `local` build type:

https://github.com/flutter/flutter/blob/3fbabb89f6b2c1c2fd59d9f01b02159610ae28a0/dev/devicelab/bin/tasks/gradle_plugin_light_apk_test.dart#L160-L187

I _believe_ what's happening is that we are not including the plugin dependency for the `local` build type. Though, the error doesn't immediately point to that:

```
e: file:///private/var/folders/v1/wpg85hbs16qd5b_x1c_l6nj400vh_3/T/flutter_devicelab_gradle_plugin_test.rIz5Zq/hello/android/app/src/main/kotlin/com/example/hello/MainActivity.kt:3:8 Unresolved reference: io
e: file:///private/var/folders/v1/wpg85hbs16qd5b_x1c_l6nj400vh_3/T/flutter_devicelab_gradle_plugin_test.rIz5Zq/hello/android/app/src/main/kotlin/com/example/hello/MainActivity.kt:5:22 Unresolved reference: FlutterActivity
```

**Comment by camsim99** [comment]
I just tested my theory by including the plugin dependency for all build types and the test passed.

**Comment by matanlurey** [comment]
I see.

In my _head_ we could say if the release is not _explicitly_ "debug" (or "profile"), it is a release-like build. That has a smaller chance of being a breaking change, that is, all that will happen is _exactly_ what happens today (no plugins are removed). It does have the downside of meaning if they _want_ to take advantage of this feature, they'd need to rename the build.

It does mean we'd need (eventually) maybe I way for users to declare "this release should be treated as release mode", but given that there are other bits of the tool that differentiate debug/profile/release, I don't think this is a high priority. WDUT?

**Comment by camsim99** [comment]
Hmm I'm not sure I quite understand what you're saying.

To clarify, we have to find a way to declare plugin dependencies of type `<custom build type>Api` for the project, otherwise custom build types won't even compile. We theoretically should just be able to query the build types and use reflection (ew) to do this I think? Right now, I'm trying to ensure that the Flutter Gradle plugin even knows of the custom build type because when my logic is called, it does not know about the `local` build type that the test creates, for instance.

Are you referencing the idea of excluding dependencies for certain build types? I'm having trouble finding a way to exclude dependencies from a particular build type versus include versus [include them for a particular build type](https://developer.android.com/build/build-variants#dependencies), so I don't think it's supported.

**Comment by matanlurey** [comment]
> To clarify, we have to find a way to declare plugin dependencies of type `<custom build type>Api` for the project

Oh jeez, I totally misunderstood.

How does it work today? That is, why couldn't the logic for these custom build types be the same as it is now?

**Comment by camsim99** [comment]
Right now, we just use `api` which applies the plugin as a dependency for all build types.

> Are you referencing the idea of excluding dependencies for certain build types? I'm having trouble finding a way to exclude dependencies from a particular build type versus include versus [include them for a particular build type](https://developer.android.com/build/build-variants#dependencies), so I don't think it's supported.

I don't think there's a way for us to keep `api` and exclude dev dependencies for one build type. I'll keep searching for workarounds though!

**Comment by matanlurey** [comment]
Hmm, I'm guessing something like this doesn't make sense:

<https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.artifacts/-module-dependency/exclude.html>

Some pseudo code ... or something like this?

```gradle
project.afterEvaluate { // Ensure this runs after build types are defined
    android.buildTypes.all { buildType ->
        // Add plugin dependency for all build types except release if it's a dev dependency
        if (!pluginObject.dev_dependency || buildType.name != 'release') {
            project.dependencies.add("${buildType.name}Api", pluginProject)
        }
    }
}
```

**Comment by camsim99** [comment]
This is actually what I was thinking! But the `project.afterEvaluate { // Ensure this runs after build types are defined` piece is what I was missing because I was trying to find where the plugin would recognize all build types. I'll try that out!

**Comment by matanlurey** [comment]
Works for me!

**Review by matanlurey — APPROVED** [review]
re-LGTM most recent changes.
