### PR TITLE
[Windows] Use dark title bar on dark system theme

### LINKED ISSUE #107926: Dark theme in Windows 10 has a light title bar
## Steps to Reproduce

1. Change Windows theme to Dark Mode.
2. Create a new Flutter project.
3. Use the demo app but change one line to use Dark Mode:
`theme: ThemeData.dark(),`
4. Start the demo app and notice that the title bar is light:
image

Shouldn't the title bar also be dark, since the Windows theme is in dark mode? Microsoft has written about this here https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications but I am wondering if this is something Flutter can do?

**Expected results:** 
Title bar is expected to be dark.

**Actual results:** 
Title bar is light.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by loic-sharma**
This is a redo of https://github.com/flutter/flutter/pull/110615 as [the `windows_startup_test` failed](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20windows_startup_test/61/overview). This makes the test pass even if the machine does not support dark mode: https://github.com/flutter/flutter/pull/111042/commits/662a714fb369881536209aaf332bf4906c570a35.

This was tested by:

1. Enabling `windows_startup_test` in presubmit temporarily and [verifying it passed](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20windows_startup_test/2/steps).
2. Running the test locally on a Windows 11 machine that supports dark mode
3. Running the test locally on a Windows 7 machine that does not support dark mode

## Original description

Ideally, the app should follow the system theme:

1. **App is aware of the system theme** - The app and its window frame should be able to detect whether the system theme is in dark mode
1. **React to system changes** - If you switch your system theme to dark mode, the app and its window frame should also be able to switch

This change makes Flutter apps have a dark title bar if Windows's theme is set to dark mode. This does nothing on older versions of Windows - like Windows 7 - that don't support dark mode.

Making the app's content follow the system theme will be fixed in subsequent changes and is tracked by https://github.com/flutter/flutter/issues/110700

Fixes https://github.com/flutter/flutter/issues/107926

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp [hunk 1]
```diff
@@ -50,11 +64,44 @@ bool FlutterWindow::OnCreate() {
...
+      } else if (method == "isAppDarkModeEnabled") {
+        BOOL enabled;
+        HRESULT hr = DwmGetWindowAttribute(GetHandle(),
+                                           DWMWA_USE_IMMERSIVE_DARK_MODE,
+                                           &enabled, sizeof(enabled));
+        if (SUCCEEDED(hr)) {
+          result->Success((bool)enabled);
+        } else if (hr == E_INVALIDARG) {
+          // Fallback if the operating system doesn't support dark mode.
+          result->Success(false);
```
Comment (loic-sharma) [inline dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp:83]: This is part of the fix. See: https://github.com/flutter/flutter/commit/662a714fb369881536209aaf332bf4906c570a35

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp [hunk 2]
```diff
@@ -50,11 +64,44 @@ bool FlutterWindow::OnCreate() {
...
+                                  kGetPreferredBrightnessRegValue,
+                                  RRF_RT_REG_DWORD, nullptr, &data, &data_size);
+
+        if (status == ERROR_SUCCESS) {
+          // Preferred brightness is 0 if dark mode is enabled,
+          // otherwise non-zero.
+          result->Success(data == 0);
+        } else if (status == ERROR_FILE_NOT_FOUND) {
+          // Fallback if the operating system doesn't support dark mode.
+          result->Success(false);
```
Comment (loic-sharma) [inline dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp:101]: This is part of the fix. See: https://github.com/flutter/flutter/commit/662a714fb369881536209aaf332bf4906c570a35

**Comment by a-wallen** [comment]
```yaml
  - name: Windows windows_startup_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]
      tags: >
        ["devicelab", "hostonly"]
      task_name: windows_startup_test
```

I didn't notice this when `windows_startup_test` landed initially, but we might want to rename the target. It looks like all `start_up` tests are benchmarks that measure the time to the first frame. `windows_startup_test` is a "driver test" if I'm not mistaken.

**Review by a-wallen — APPROVED** [review]
The approach mentioned in the PR description to validate your solution LGTM. 🤞 that the tree isn't red on postsubmit again...

File: dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt [hunk 3]
```diff
@@ -33,6 +33,7 @@ target_compile_definitions(${BINARY_NAME} PRIVATE "NOMINMAX")
 # Add dependency libraries and include directories. Add any application-specific
 # dependencies here.
 target_link_libraries(${BINARY_NAME} PRIVATE flutter flutter_wrapper_app)
+target_link_libraries(${BINARY_NAME} PRIVATE "dwmapi.lib")
```
Comment (cbracken) [inline dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt:36]: I'm assuming we've verified this is available on Win7?

File: dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp [hunk 4]
```diff
@@ -4,14 +4,28 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp:27]: Here and in the template/other examples: document these constants for users and future-you.

File: dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp [hunk 5]
```diff
@@ -251,3 +271,17 @@ bool Win32Window::OnCreate() {
 void Win32Window::OnDestroy() {
   // No-op; provided for subclasses.
 }
+
+void Win32Window::UpdateTheme(HWND const window) {
+  DWORD light_mode;
+  DWORD light_mode_size = sizeof(light_mode);
+  LONG result = RegGetValue(HKEY_CURRENT_USER, kGetPreferredBrightnessRegKey,
```
Comment (cbracken) [inline dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp:278]: Here and in the template/other examples: `LSTATUS result = ...`

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp [hunk 6]
```diff
@@ -7,11 +7,25 @@
...
+/// Redefined in case the developer's machine has a Windows SDK older than
+/// version 10.0.22000.0.
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp:27]: Same notes re documentation, LRESULT.

File: dev/integration_tests/windows_startup_test/windows/runner/win32_window.cpp [hunk 7]
```diff
@@ -4,14 +4,28 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline dev/integration_tests/windows_startup_test/windows/runner/win32_window.cpp:27]: Same notes re documentation, LRESULT.

File: dev/manual_tests/windows/runner/win32_window.cpp [hunk 8]
```diff
@@ -4,14 +4,28 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline dev/manual_tests/windows/runner/win32_window.cpp:27]: Same notes re documentation, LRESULT.

File: examples/hello_world/windows/runner/win32_window.cpp [hunk 9]
```diff
@@ -4,14 +4,28 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline examples/hello_world/windows/runner/win32_window.cpp:27]: Same notes re documentation, LRESULT.

File: examples/platform_channel/windows/runner/win32_window.cpp [hunk 10]
```diff
@@ -4,14 +4,28 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline examples/platform_channel/windows/runner/win32_window.cpp:27]: Same notes re documentation, LRESULT.

File: packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp [hunk 11]
```diff
@@ -1,13 +1,27 @@
...
+/// See: https://docs.microsoft.com/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
+#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
+#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
+#endif
+
 constexpr const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW";
 
+constexpr const wchar_t kGetPreferredBrightnessRegKey[] =
+  L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
+constexpr const wchar_t kGetPreferredBrightnessRegValue[] = L"AppsUseLightTheme";
```
Comment (cbracken) [inline packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp:23]: Same notes re documentation, LRESULT.

**Review by cbracken — APPROVED** [review]

File: dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt (hunk 3 above)
Comment (loic-sharma) [reply dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt:36]: Yup. I tested this builds & runs on Windows 7.

Comment (loic-sharma) [reply dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt:36]: FYI the original PR was reverted because the integration test crashed if the machine didn't support dark mode. The feature itself worked as expected though.

Comment (cbracken) [reply dev/integration_tests/flutter_gallery/windows/runner/CMakeLists.txt:36]: Awesome - now that you mention Vista I think I looked this up on the last PR and remember seeing it mentioned that it was introduced with Vista. Sounds good! Thanks.

File: dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp (hunk 4 above)
Comment (loic-sharma) [reply dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp:31]: Added a comment, let me know if you have feedback on it!

File: dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp (hunk 5 above)
Comment (loic-sharma) [reply dev/integration_tests/flutter_gallery/windows/runner/win32_window.cpp]: Good catch, fixed!

File: dev/integration_tests/windows_startup_test/windows/runner/win32_window.cpp (hunk 7 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/windows/runner/win32_window.cpp:31]: Fixed

File: dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp (hunk 6 above)
Comment (loic-sharma) [reply dev/integration_tests/windows_startup_test/windows/runner/flutter_window.cpp:31]: Fixed

File: examples/hello_world/windows/runner/win32_window.cpp (hunk 9 above)
Comment (loic-sharma) [reply examples/hello_world/windows/runner/win32_window.cpp:31]: Fixed

File: examples/platform_channel/windows/runner/win32_window.cpp (hunk 10 above)
Comment (loic-sharma) [reply examples/platform_channel/windows/runner/win32_window.cpp:31]: Fixed

File: packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp (hunk 11 above)
Comment (loic-sharma) [reply packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp:27]: Fixed

File: dev/manual_tests/windows/runner/win32_window.cpp (hunk 8 above)
Comment (loic-sharma) [reply dev/manual_tests/windows/runner/win32_window.cpp:31]: Fixed

**Comment by loic-sharma** [comment]
@a-wallen Apologies, I missed your comment about the test's name! Personally, I think `windows_startup_test` is different enough from `xyz__start_up` to clear up any confusion. That said, I don't feel super strongly about this so let me know if you have a better name in mind!

**Review by a-wallen — APPROVED** [review]
I could throw out some ideas, but you're right. LGTM.
