### PR TITLE
Fix a large number of Drawer bugs

### LINKED ISSUE #90: Drawer should open using swipe-from-side
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Jul 17, 2015 at 16:14 GMT_
_Originally opened as https://github.com/flutter/engine/issues/79_

----

_From @eseidelGoogle on June 10, 2015 18:27_

Code is here:
https://github.com/domokit/mojo/blob/master/sky/sdk/lib/framework/components2/drawer.dart

_Copied from original issue: domokit/mojo#232_

### LINKED ISSUE #187: Drawers and popup menus are no longer stateful
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 21:22 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1528_

----

e.g. the card_collection.dart demo's drawer's checkboxes don't check when you tap them.

### LINKED ISSUE #192: Cannot stop Drawer from being popped
<a href="https://github.com/abarth"></img></a> **Issue by [abarth](https://github.com/abarth)**
_Thursday Oct 08, 2015 at 17:16 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1539_

----

When the Drawer is popped off the stack using the navigator (e.g., the hardware back button), there's no way of catching it with your finger to stop it from exiting.

### LINKED ISSUE #194: Exiting drawer is on top of incoming new route
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Oct 08, 2015 at 19:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1547_

----

e.g. open the settings page in the stocks demo app. The drawer should be under the settings age, but it's over it.

### LINKED ISSUE #604: setState might not update the widgets in showDrawer
Sorry if this is sparse on details. I mainly want to determine if there is a bug with `showDrawer` or with the way I attempted to use it.

Yesterday, I attempted to use `showDrawer` with the 7be58b1 alpha branch of Flutter. The drawer appeared/dismissed correctly, and the widgets I put in the drawer were correct.

Unfortunately, I noticed that no matter how I attempted to change the state of what was drawn in the drawer, it would not re-render. In my case, I tried to put a `Switch` inside a `DrawerItem` to toggle debug mode for my app. I did confirm that the state did actually change, which led me to think that Flutter has a bug.

I was following the Stocks demo app quite closely, which uses a Drawer to toggle the user's market sentiment (`Optimistic` vs `Pessimistic`). However, I was assuming that the app's behavior would match the [Sky Demo](https://play.google.com/store/apps/details?id=org.domokit.sky.demo) app in the Google Play Store. I only just realized that this app is actually 3 months old (last update August 25), so it is very possible that in that time, the Stocks example does not function as it did before.

I am currently unable to try running these examples (though I have found the [instructions](https://github.com/flutter/flutter/tree/4b03a9eec899659e4770e5ec88e365afbac0916b/examples)), so if someone else can run the Stocks app and determine whether the Optimistic/Pessimistic radio buttons update the drawer menu or not, that would be very helpful.

Otherwise, I will look into this more after the break.

### PR DESCRIPTION
**Pull request by abarth**
This patch restructures how we handle drawer. The drawer is now a child of the
Scaffold, which wraps the Drawer in a DrawerController. The DrawerController
manages the interaction with the navigator as well as the edge swiping. The
DrawerController's state machine is driven almost entirely off its Performance,
which it now owns completely.

Fixes #90
Fixes #187
Fixes #192
Fixes #194
Fixes #604

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -100,6 +117,14 @@ class Scaffold extends StatefulComponent {
 
 class ScaffoldState extends State<Scaffold> {
 
+  // DRAWER API
+
+  final GlobalKey<DrawerControllerState> _drawerKey = new GlobalKey<DrawerControllerState>();
+
+  void openDrawer() {
+    _drawerKey.currentState?.open();
```
Comment (Hixie) [inline packages/flutter/lib/src/material/scaffold.dart]: I think you should assert that you have one, rather than silently doing nothing if you don't.

**Comment by Hixie** [comment]
LGTM.

#187 is only fixed for Drawers, not popup menus. Filed #698 for the popup menu case. Filed #699 for the hamburger menu logic.
