### PR TITLE
AspectRatio should attempt to fit its height

### LINKED ISSUE #2620: Behavior of AspectRatio class is unexpected
The AspectRatio class always infers the height from the width (see _applyAspectRatio). This can result in a height that can't fit within the constraints. When this happens, I expected that the behavior would invert to inferring width from height.

In my test, the parent box was 400 wide and 100 high. I expected the result size to be 100x100, but the actual result was 400x400 (with an aspect ratio of 1.0).

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: 335354d958f13d24229919c6782f78ef310099e9 (2 days ago)
Engine:    8514a14911269e405784ca90ba082407d260fbf3
```

### PR DESCRIPTION
**Pull request by abarth**
If there's not enough height for the given aspect ratio, we now try to see if
using the height to infer the width will fit the given constraints. The
algorithm we use is similar to the one we use for RenderImage.

Fixes #2620

### CODE REVIEW

**Comment by abarth** [comment]
@jimbeveridge @Hixie

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -359,8 +361,11 @@ class RenderFractionallySizedBox extends RenderProxyBox {
 ///
 /// In that same situation, if the aspect ratio is 0.5, we'll also select a
 /// width of 100.0 (still the biggest allowed) and we'll attempt to use a height
-/// of 200.0. Unfortunately, that violates the constraints and we'll end up with
-/// a height of 100.0 instead.
+/// of 200.0. Unfortunately, that violates the constraints because the child can
+/// be at most 100.0 pixels tall. The render object will then take that value
+/// and apply the aspect ratio again to obtain a width of 50.0. That width is
+/// permitted by the constraints and the child receives a width of 50.0 and a
+/// height of 100.0.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: But what if it isn't? Continue the story!

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 2]
```diff
@@ -345,12 +345,14 @@ class RenderFractionallySizedBox extends RenderProxyBox {
...
-/// The width of this render object is the largest width permited by the layout
+/// The render object first tries the largest width permited by the layout
 /// constraints. The height of the render object is determined by applying the
 /// given aspect ratio to the width, expressed as a ratio of width to height.
-/// For example, a 16:9 width:height aspect ratio would have a value of 16.0/9.0.
+/// For example, a 16:9 width:height aspect ratio would have a value of
+/// 16.0/9.0. If the maximum width is infinite, the initial width is determined
+/// by applying the aspect ratio to the maximum height.
 ///
 /// For example, given an aspect ratio of 2.0 and layout constraints that
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: Two blocks of text in a row start with "For example". Put a newline before the first one. For the second one, replace "For example" with "Now consider a second example:" or some such.

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 3]
```diff
@@ -383,28 +388,82 @@ class RenderAspectRatio extends RenderProxyBox {
...
   Size _applyAspectRatio(BoxConstraints constraints) {
     assert(constraints.debugAssertIsNormalized);
-    double width = constraints.constrainWidth();
-    double height = constraints.constrainHeight(width / _aspectRatio);
-    return new Size(width, height);
-  }
+    assert(() {
+      if (!constraints.hasBoundedWidth && !constraints.hasBoundedHeight) {
+        throw new RenderingError(
+          'This $runtimeType was given an aspect ratio of $aspectRatio but was given '
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: Make the first line be a relatively short "error message" followed by a `\n`. e.g.:
```
'$runtimeType has unbounded constraints.\n'
```

File: packages/flutter/lib/src/widgets/basic.dart [hunk 4]
```diff
@@ -702,16 +702,34 @@ class OffStage extends OneChildRenderObjectWidget {
...
+/// 0.0 and 100.0, we'll select a width of 100.0 (the biggest allowed) and a
+/// height of 50.0 (to match the aspect ratio).
+///
+/// In that same situation, if the aspect ratio is 0.5, we'll also select a
+/// width of 100.0 (still the biggest allowed) and we'll attempt to use a height
+/// of 200.0. Unfortunately, that violates the constraints because the child can
+/// be at most 100.0 pixels tall. The widget will then take that value
+/// and apply the aspect ratio again to obtain a width of 50.0. That width is
+/// permitted by the constraints and the child receives a width of 50.0 and a
+/// height of 100.0.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/basic.dart]: update this when you update the other

**Comment by Hixie** [comment]
lgtm
