### PR TITLE
Stop TextFields from wobbling within scrollables

### LINKED ISSUE #20485: scrollview wobbles when text entered into TextField
The scroll view wobbles when I type into a TextField that is held inside it.

## Steps to Reproduce

1. Clone https://github.com/SteveAlexander/flutter_soft_keyboard_bug
2. Run it on an iPhone X or simulator
3. Notice the scrolling wobbles as you type

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.9-pre.17, on Mac OS X 10.13.6 17G2208, locale en-GB)
    • Flutter version 0.5.9-pre.17 at /Users/steve/code/flutter
    • Framework revision 5d8771d18d (16 hours ago), 2018-08-10 21:18:10 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 1E0393AA-EF50-42AA-A244-3279599BE2C1 • ios • iOS 11.4 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/20485,  #12274

There is an explanation of the problem here https://github.com/flutter/flutter/issues/20485#issuecomment-436010296

Added `ScrollPosition.moveTo()` which optionally clamps its offset before calling `animateTo()` or `jumpTo()`.  The `moveTo` method is actually defined by `ViewportOffset` (ScrollPosition's superclass) however that method doesn't have enough information to clamp the scroll offset. Ideally `ViewportOffset.moveTo()` would be abstract (like the other ViewportOffset methods). It has a concrete implementation for the (unlikely) sake of existing ViewportOffset subclasses.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 1]
```diff
@@ -562,6 +562,26 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+    Curve curve,
+    bool clamp = true,
+  }) {
+    assert(to != null);
+    assert(clamp != null);
+
+    if (clamp)
+      to = to.clamp(minScrollExtent, maxScrollExtent);
+
+    if (duration == null || duration == Duration.zero) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/scroll_position.dart]: could the next few lines be replaced by `super.moveTo(...)`?

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 2]
```diff
@@ -562,6 +562,26 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   @override
   void jumpTo(double value);
 
+  @override
+  Future<void> moveTo(double to, {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/scroll_position.dart]: We should probably provide a new doc comment for this method, otherwise dartdocs will show the dartdoc of the superclass, which would incorrectly claim that `clamp` is ignored?

**Review by goderbauer — APPROVED** [review]
LGTM with 2 nits.

I believe this also fixes a similar problem during a11y scrolling: https://github.com/flutter/flutter/issues/12274

File: packages/flutter/lib/src/widgets/scroll_position.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/scroll_position.dart]: The super class does say
>  .. but subclasses like [ScrollPosition] handle it by adjusting [to] to prevent over or under scrolling

But you're right, it would clearer if there was new doc here.

File: packages/flutter/lib/src/widgets/scroll_position.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/scroll_position.dart]: Good point, yes.

**Comment by MobilyteApps** [comment]
Its still not working on my end. Tried all the solutions on my end but none of the point seems to be working
