### PR TITLE
[flutter_conductor] fix initialref to explicitly include remote name

### LINKED ISSUE #96425: [flutter_conductor] `conductor start` fails to checkout repos if mirror AND upstream both contain candidate branch
For example:

```
Cloning engine from git@github.com:flutter/engine.git to /Users/kevinjchisholm/release/flutter_conductor_checkouts/engine...
Exception on command "checkout flutter-2.8-candidate.16": Command "git checkout flutter-2.8-candidate.16" failed in directory "/Users/username/release/flutter_conductor_checkouts/engine" to Checking out initialRef flutter-2.8-candidate.16. Git exited with error code 128.
stderr from git:
14:18:07.924944 git.c:458               trace: built-in: git checkout flutter-2.8-candidate.16
hint: If you meant to check out a remote tracking branch on, e.g. 'origin',
hint: you can do so by fully qualifying the name with the --track option:
hint:
hint:     git checkout --track origin/<name>
hint:
hint: If you'd like to always have checkouts of an ambiguous <name> prefer
hint: one remote, e.g. the 'origin' remote, consider setting
hint: checkout.defaultRemote=origin in your config.
fatal: 'flutter-2.8-candidate.16' matched multiple (2) remote tracking branches
```

### LINKED ISSUE #96437: [flutter_conductor] conductor no longer needs to add candidate branch to .ci.yaml
This is no longer needed after https://github.com/flutter/cocoon/pull/1468

https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/repository.dart#L862

### PR DESCRIPTION
**Pull request by christopherfujino**
When cloning the framework and engine repos as part of the `conductor start` flow, explicitly checkout the candidate branch from the `upstream` remote, in case both the upstream AND mirror repo have the branch and then git cannot disambiguate.

Fixes https://github.com/flutter/flutter/issues/96425

Remove code to have the conductor update .ci.yaml with the candidate branch name; this is no longer needed after https://github.com/flutter/cocoon/pull/1468

Fixes https://github.com/flutter/flutter/issues/96437

### CODE REVIEW

File: dev/conductor/core/lib/src/start.dart [hunk 1]
```diff
@@ -235,7 +235,7 @@ class StartContext extends Context {
   }) : git = Git(processManager),
   engine = EngineRepository(
     checkouts,
-    initialRef: candidateBranch,
+    initialRef: 'upstream/$candidateBranch',
```
Comment (godofredoc) [inline dev/conductor/core/lib/src/start.dart:238]: Will we get an error during the checkout if the branch already exists in the fork?

Comment (christopherfujino) [reply dev/conductor/core/lib/src/start.dart:238]: By namespacing by the remote name, git will disregard the fork's branches. if you *only* provide the branch name, git will check all remotes and find which has the branch in question.

Comment (godofredoc) [reply dev/conductor/core/lib/src/start.dart:238]: Awesome, thanks for the explanation.

**Review by godofredoc — APPROVED** [review]
