### PR TITLE
Fixed changing supportedLocales fails to update the locale

### LINKED ISSUE #117210: WidgetsApp: Changing supportedLocales fails to update the locale
When providing `supportedLocales` to a WidgetsApp (in this case, a MaterialApp), it doesn't update the internal `_locale` field in `didUpdateWidget`.

The workaround is to provide a specific locale via the `locale` field. (as to be seen on line 23)

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press button on page
3. Observe that the text above the button doesn't change.
4. Uncomment workaround in line 23 and try again.

**Expected results:** Text respectively the Locale (`_locale` in WidgetsApp) changes.

**Actual results:** `_locale` in WidgetsApp is still the same, nothing changes.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Locale> supportedLocales = [const Locale("de")];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      // Workaround: Overrides the _locale from WidgetsApp
      // locale: supportedLocales[0],
      supportedLocales: supportedLocales,
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
      routes: {
        '/': (context) => MyHomePage(onPress: () {
              setState(() {
                supportedLocales = [const Locale("en")];
              });
            }),
      },
      initialRoute: "/",
    );
  }
}

class MyHomePage extends StatelessWidget {
  final VoidCallback onPress;

  const MyHomePage({super.key, required this.onPress});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Flutter Demo Home Page")),
      body: Center(
        child: Column(
          children: [
            Text("Current locale: ${Localizations.localeOf(context)}"),
            ElevatedButton(
              onPressed: () => onPress.call(),
              child: const Text("Press me to change locale"),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on Manjaro Linux 6.0.11-1-MANJARO, locale de_AT.UTF-8)
    • Flutter version 3.3.9 on channel stable at /home/shamader/tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (vor 3 Wochen), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /mnt/Daten/tools/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/shamader/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✗] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/shamader/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335
    • Flutter plugin version 71.1.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /home/shamader/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/221.6008.13.2211.9301383
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.2)
    • Android Studio at /home/shamader/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-2/222.4345.14.2221.9321504
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (4 available)
    • SM T500 (mobile)    • R9AR800H8RK      • android-arm64  • Android 12 (API 31)
    • M2103K19PG (mobile) • xwcm955djrrslnpj • android-arm64  • Android 12 (API 31)
    • Linux (desktop)     • linux            • linux-x64      • Manjaro Linux 6.0.11-1-MANJARO
    • Chrome (web)        • chrome           • web-javascript • Chromium 108.0.5359.94 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

## Missing statement location

WidgetsApp Code which is missing an update statement taking `supportedLocales` into account.

https://github.com/flutter/flutter/blob/da7b8327e484f2ce036244bff4880bb771dd636c/packages/flutter/lib/src/widgets/app.dart#L1335-L1347

### PR DESCRIPTION
**Pull request by shivanuj13**
Recompute the resolved locale in LocalizationsResolver.update(...) and notify listeners
only when the resolved locale actually changes. Previously, updating WidgetsApp.supportedLocales
did not always propagate to the app locale because the resolver did not re-resolve and
notify listeners. This change fixes that bug and adds unit tests.

Fixes [https://github.com/flutter/flutter/issues/117210](https://github.com/flutter/flutter/issues/117210)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/widgets/localizations_test.dart [hunk 1]
```diff
@@ -105,6 +105,50 @@ void main() {
 
     expect(Localizations.maybeLocaleOf(contextKey.currentContext!), isNull);
   });
+  testWidgets('LocalizationsResolver.update notifies listeners when supportedLocales changes', (
```
Comment (victorsanni) [inline packages/flutter/test/widgets/localizations_test.dart:109]:
```suggestion
  
  testWidgets('LocalizationsResolver.update notifies listeners when supportedLocales changes', (
```

File: packages/flutter/lib/src/widgets/localizations.dart [hunk 2]
```diff
@@ -810,6 +810,17 @@ class LocalizationsResolver extends ChangeNotifier with WidgetsBindingObserver {
...
     _localizationsDelegates = localizationsDelegates;
     _supportedLocales = supportedLocales;
+
+    // Recompute the resolved locale from the current settings and notify
+    // listeners only if the resolved locale changed.
+    final Locale newLocale = _resolveLocales(
+      WidgetsBinding.instance.platformDispatcher.locales,
+      _supportedLocales,
+    );
+    if (newLocale != _resolvedLocale) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: Maybe we can share code with `didChangeLocales`?

**Review by victorsanni — COMMENTED** [review]
Can you run `dart format packages/flutter/test/widgets/localizations_test.dart` to fix the `Linux analyze` failure?

File: packages/flutter/lib/src/widgets/localizations.dart (hunk 2 above)
Comment (shivanuj13) [reply packages/flutter/lib/src/widgets/localizations.dart]: refactored the code to reuse this in `didChangeLocals` as well.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/widgets/localizations.dart [hunk 3]
```diff
@@ -810,6 +810,7 @@ class LocalizationsResolver extends ChangeNotifier with WidgetsBindingObserver {
     _localeResolutionCallback = localeResolutionCallback;
     _localizationsDelegates = localizationsDelegates;
     _supportedLocales = supportedLocales;
+    _updateResolvedLocale(WidgetsBinding.instance.platformDispatcher.locales);
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: I took a look at the google testing failures. It's happening because `LocalizationsResolver.update` is called needlessly (whenever `WidgetsApp.didUpdateWidget` changes). `LocalizationsResolver.update` should be called only when `WidgetsApp` `LocalizationsResolver` properties change.

Comment (shivanuj13) [reply packages/flutter/lib/src/widgets/localizations.dart]: Thanks for point out the issue. i have added checks to invoke ` _updateResolvedLocale(WidgetsBinding.instance.platformDispatcher.locales);`.

File: packages/flutter/lib/src/widgets/localizations.dart [hunk 4]
```diff
@@ -809,7 +809,12 @@ class LocalizationsResolver extends ChangeNotifier with WidgetsBindingObserver {
     _localeListResolutionCallback = localeListResolutionCallback;
     _localeResolutionCallback = localeResolutionCallback;
     _localizationsDelegates = localizationsDelegates;
-    _supportedLocales = supportedLocales;
+    // check if supportedLocales changed
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: Comments should use proper grammar. See the documentation for `update` above.

File: packages/flutter/lib/src/widgets/localizations.dart [hunk 5]
```diff
@@ -809,7 +809,12 @@ class LocalizationsResolver extends ChangeNotifier with WidgetsBindingObserver {
...
+    // and only re-resolve if it did
+    if (supportedLocales != _supportedLocales) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: What if `supportedLocales` remains unchanged but something else in this method did? Would that cause problems?

File: packages/flutter/lib/src/widgets/localizations.dart [hunk 6]
```diff
@@ -868,7 +873,17 @@ class LocalizationsResolver extends ChangeNotifier with WidgetsBindingObserver {
 
   @override
   void didChangeLocales(List<Locale>? locales) {
-    final Locale newLocale = _resolveLocales(locales, supportedLocales);
+    _updateResolvedLocale(locales);
+  }
+
+  /// Recompute the resolved locale based on [preferredLocales] and
+  /// [supportedLocales], update [_resolvedLocale], and notify listeners
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: Referencing private vars in (potentially if the method is made public) public documentation might lead to problems in the future. Is there a way to reference `_resolvedLocale` without calling it directly (e.g "update the resolved locale", "update the internal cache" or some variant of the above) or just omit it completely.

**Review by victorsanni — COMMENTED** [review]
I'm wondering if in `widgets/app.dart` we should only call `update` if any localization properties change, or if that is needless since it's mostly a parameter passthrough. Any thoughts?

File: packages/flutter/lib/src/widgets/localizations.dart (hunk 5 above)
Comment (shivanuj13) [reply packages/flutter/lib/src/widgets/localizations.dart]: since we have added checks in `widget/app.dart`. we don't this this check anymore.

**Review by victorsanni — APPROVED** [review]

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thanks for contributing!

**Comment by victorsanni** [comment]
Same google testing failures as before... I'm surprised https://github.com/flutter/flutter/pull/178526/commits/74e8c5d70b188c00827b1874c616055e26590ed3 passed google testing but the latest commit doesn't.

File: packages/flutter/lib/src/widgets/localizations.dart (hunk 3 above)
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/localizations.dart]: This code block from your previous commit will fix the Google testing:

```suggestion
    if (_supportedLocales != supportedLocales) {
      _updateResolvedLocale(WidgetsBinding.instance.platformDispatcher.locales);
      _supportedLocales = supportedLocales;
    }
```

Can we add a test for this? The fact that Google testing triggers it and we don't is an indication we should probably test for it here.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/widgets/localizations.dart (hunk 3 above)
Comment (shivanuj13) [reply packages/flutter/lib/src/widgets/localizations.dart]: I think i have already aded a test that verify `LocalizationsResolver` does not notify if supportedLocales is unchanged. do we need to add a test for any other specific case?
