### PR TITLE
Fix TransformLayer with perspective transform

### LINKED ISSUE #45789: Respect transformation for MouseRegion on Web
Hello. I tried to create widget with behaviour like [this](https://gijsroge.github.io/tilt.js/):

I created this widget but faced with bug: MouseRegion doent't respect transfomation.

## Steps to Reproduce

1. Run web app in chrome 
2. Try to move mouse around right bottom corner of rect and see shaking/bug,

**Target Platform:** Web
**Target OS version/browser:** Chrome Version 78.0.3904.108 (Official Build) (64-bit)
**Devices:** Mac Pro 2018 ( MacOS 10.15.1 (19B88) )

## Code to reproduce

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: PerspectivePage()));

class PerspectivePage extends StatefulWidget {
  @override
  _PerspectivePageState createState() => _PerspectivePageState();
}

class _PerspectivePageState extends State<PerspectivePage> {
  GlobalKey _mouseRegionKey = GlobalKey();

  Size containerSize = Size(300, 300);

  double rotateX = 0;
  double rotateY = 0;

  double maxTilt = 0.5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _body(),
    );
  }

  Widget _body() {
    final matrix = Matrix4.identity()
      ..setEntry(3, 2, 0.0025)
      ..rotateX(rotateX)
      ..rotateY(rotateY);

    return Center(
      child: Container(
        color: Colors.green,
        child: Transform(
          transform: matrix,
          alignment: FractionalOffset.center,
          child: MouseRegion(
            key: _mouseRegionKey,
            onEnter: (event) {
              print("onEnter");
            },
            onExit: (event) {
              final pos = getLocalPosition(event);
              print("onExit: $pos");
              setState(() {
                rotateX = 0;
                rotateY = 0;
              });
            },
            onHover: _onHover,
            child: Container(
              width: containerSize.width,
              height: containerSize.height,
              color: Colors.deepOrange.withOpacity(0.4),
            ),
          ),
        ),
      ),
    );
  }

  Offset getLocalPosition(PointerEvent event) {
    final RenderBox renderBoxRed =
        _mouseRegionKey.currentContext.findRenderObject();
    final widgetPosition = renderBoxRed.localToGlobal(Offset.zero);

    final localPosition =
        event.localPosition.translate(-widgetPosition.dx, -widgetPosition.dy);
    return localPosition;
  }

  void _onHover(PointerHoverEvent event) {
    final position = getLocalPosition(event);
    print("onHover: $position");

    final percentageX = position.dx / containerSize.width;
    final percentageY = position.dy / containerSize.height;

    final tiltX = ((maxTilt / 2) - ((percentageX) * maxTilt));
    final tiltY = (((percentageY) * maxTilt) - (maxTilt / 2));

    setState(() {
      rotateX = -tiltY;
      rotateY = -tiltX;
    });
  }
}

```

## Logs

```
[  +25 ms] executing: [/Users/sanekyy/Programs/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 459c7fb884d9234c45b353087e0ec8a33dde90d1
[        ] executing: [/Users/sanekyy/Programs/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +59 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.15-0-g459c7fb88
[   +6 ms] executing: [/Users/sanekyy/Programs/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/sanekyy/Programs/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [/Users/sanekyy/Programs/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +5 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +32 ms] executing: /Users/sanekyy/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/sanekyy/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +10 ms] executing: /Users/sanekyy/Programs/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +45 ms] executing: /usr/bin/xcode-select --print-path
[   +6 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +471 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 11.2.1
           Build version 11B500
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +113 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +256 ms] Generating /Users/sanekyy/Projects/optimist.dev/gohere/admin/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +31 ms] executing: [/Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner.xcodeproj -target Runner -showBuildSettings
[        ] executing: [/Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner.xcodeproj -target Runner -showBuildSettings
[+1733 ms] Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = sanekyy
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               APPLY_RULES_IN_COPY_HEADERS = NO
               ARCHS = armv7 arm64
               ARCHS_STANDARD = armv7 arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               BUILD_LIBRARY_FOR_DISTRIBUTION = NO
               BUILD_ROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos
               CACHE_ROOT = /var/folders/hx/klmbwq7j3wx1kzz491c_dt_00000gp/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CCHROOT = /var/folders/hx/klmbwq7j3wx1kzz491c_dt_00000gp/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Release
               CONFIGURATION_BUILD_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.2
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2
               DERIVED_FILES_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DONT_GENERATE_INFOPLIST_FILE = NO
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HARDENED_RUNTIME = NO
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_NS_ASSERTIONS = NO
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_DESTINATION = Signature
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.0.0
               FLUTTER_BUILD_NUMBER = 1
               FLUTTER_FRAMEWORK_DIR = /Users/sanekyy/Programs/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/sanekyy/Programs/flutter
               FLUTTER_TARGET = lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_SYMBOLS_PRIVATE_EXTERN = YES
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/sanekyy
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = sanekyy
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 = 
               LINK_FILE_LIST_normal_armv7 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_OS_VERSION = ios8.0
               LLVM_TARGET_TRIPLE_VENDOR = apple
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
               LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 19B88
               MAC_OS_X_VERSION_ACTUAL = 101501
               MAC_OS_X_VERSION_MAJOR = 101500
               MAC_OS_X_VERSION_MINOR = 1501
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos/Runner.app
               MODULES_FOLDER_PATH = Runner.app/Modules
               MODULE_CACHE_DIR = /Users/sanekyy/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = NO
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               ONLY_ACTIVE_ARCH = NO
               OS = MACOS
               OSAC = /usr/bin/osacompile
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sanekyy/Programs/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sanekyy/Programs/flutter/bin:/Users/sanekyy/Programs/flutter/.pub-cache/bin:/Users/sanekyy/Programs/flutter/bin/cache/dart-sdk/bin:/Users/sanekyy/Library/Android/sdk/platform-tools
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 17B102
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.example.admin
               PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/DerivedSources
               PROJECT_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios
               PROJECT_FILE_PATH = /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build
               PROJECT_TEMP_ROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_DIR_iphoneos13_2 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_NAME = iphoneos13.2
               SDK_NAMES = iphoneos13.2
               SDK_PRODUCT_BUILD_VERSION = 17B102
               SDK_VERSION = 13.2
               SDK_VERSION_ACTUAL = 130200
               SDK_VERSION_MAJOR = 130000
               SDK_VERSION_MINOR = 200
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/SharedPrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios
               SRCROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphoneos
               SUPPORTS_MACCATALYST = NO
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_COMPILATION_MODE = wholemodule
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -O
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_VERSION = 4.0
               SYMROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Release-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_ROOT = /Users/sanekyy/Projects/optimist.dev/gohere/admin/build/ios
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               UID = 502
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = sanekyy
               USER_APPS_DIR = /Users/sanekyy/Applications
               USER_LIBRARY_DIR = /Users/sanekyy/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               USE_LLVM_TARGET_TRIPLES = YES
               USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
               USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
               USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
               VALIDATE_PRODUCT = YES
               VALIDATE_WORKSPACE = NO
               VALID_ARCHS = arm64 arm64e armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = sanekyy
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 11B500
               XCODE_VERSION_ACTUAL = 1121
               XCODE_VERSION_MAJOR = 1100
               XCODE_VERSION_MINOR = 1120
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal
[  +62 ms] Launching lib/main.dart on Chrome in debug mode...
Building application for the web...
[+7257 ms] Starting daemon...
[ +179 ms] Initializing inputs
[  +10 ms] Reading cached asset graph...
[ +219 ms] Reading cached asset graph completed, took 217ms

[ +202 ms] Checking for updates since last build...
[+1030 ms] Checking for updates since last build completed, took 1.0s

[   +9 ms] Initializing inputs
[   +2 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 217ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 1.0s
[ +134 ms] Serving DevTools at http://127.0.0.1:62014

[+1125 ms] About to build [web]...
[   +3 ms] Running build...
[ +187 ms] Running build completed, took 82ms

[        ] Caching finalized dependency graph...
[   +6 ms] Caching finalized dependency graph completed, took 132ms

[  +15 ms] Succeeded after 233ms with 0 outputs (0 actions)

Attempting to connect to browser instance..
[+2206 ms] Debug service listening on ws://127.0.0.1:62043/h9boOJNuztY=

[ +257 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                 Status code: 404

                 Headers:
                 {
             "date": "Thu, 28 Nov 2019 21:42:46 GMT",
             "content-length": "9",
             "x-frame-options": "SAMEORIGIN",
             "content-type": "text/plain; charset=utf-8",
             "x-xss-protection": "1; mode=block",
             "x-content-type-options": "nosniff",
             "server": "dart:io with Shelf",
             "via": "1.1 shelf_proxy"
           }

                 Content:
                 Not Found}

[  +22 ms] Debug service listening on ws://127.0.0.1:62043/h9boOJNuztY=
[  +27 ms] WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.
[+1864 ms] onEnter
[   +1 ms] onHover: Offset(0.6, 10.3)
[  +13 ms] onHover: Offset(28.1, 27.8)
[        ] onHover: Offset(28.6, 28.1)
[  +16 ms] onHover: Offset(25.5, 27.1)
[   +1 ms] onHover: Offset(26.0, 27.4)
[  +16 ms] onHover: Offset(26.9, 27.8)
[        ] onHover: Offset(27.1, 28.1)
[  +16 ms] onHover: Offset(27.5, 28.3)
[        ] onHover: Offset(27.8, 28.6)
[  +15 ms] onHover: Offset(28.3, 28.8)
[        ] onHover: Offset(28.8, 29.1)
[  +15 ms] onHover: Offset(29.0, 29.3)
[        ] onHover: Offset(29.5, 29.6)
[  +16 ms] onHover: Offset(30.0, 29.8)
[        ] onHover: Offset(30.6, 29.8)
[  +15 ms] onHover: Offset(30.7, 30.0)
[   +1 ms] onHover: Offset(31.3, 30.3)
[  +15 ms] onHover: Offset(31.4, 30.3)
[        ] onHover: Offset(31.7, 30.3)
[  +16 ms] onHover: Offset(31.9, 30.2)
[        ] onHover: Offset(32.2, 30.2)
[  +15 ms] onHover: Offset(32.1, 30.5)
[        ] onHover: Offset(32.4, 30.5)
[  +15 ms] onHover: Offset(32.6, 30.4)
[        ] onHover: Offset(32.9, 30.4)
[  +15 ms] onHover: Offset(33.1, 30.4)
[  +16 ms] onHover: Offset(33.3, 30.4)
[        ] onHover: Offset(33.6, 30.4)
[ +173 ms] onHover: Offset(33.1, 30.4)
[   +9 ms] onHover: Offset(32.6, 29.8)
[  +17 ms] onHover: Offset(32.0, 28.9)
[   +1 ms] onHover: Offset(31.4, 28.3)
[  +13 ms] onHover: Offset(31.1, 27.5)
[        ] onHover: Offset(30.4, 26.5)
[  +15 ms] onHover: Offset(29.7, 25.6)
[        ] onHover: Offset(29.1, 24.6)
[  +15 ms] onHover: Offset(29.1, 24.1)
[        ] onHover: Offset(28.5, 23.5)
[  +17 ms] onHover: Offset(28.0, 22.6)
[        ] onHover: Offset(27.8, 22.0)
[  +15 ms] onHover: Offset(27.4, 21.5)
[        ] onHover: Offset(27.1, 20.9)
[  +16 ms] onHover: Offset(26.7, 20.4)
[        ] onHover: Offset(26.1, 19.8)
[        ] onHover: Offset(25.6, 19.2)
[  +18 ms] onHover: Offset(25.6, 18.7)
[        ] onHover: Offset(24.6, 17.7)
[  +12 ms] onHover: Offset(24.2, 17.2)
[        ] onHover: Offset(23.7, 16.6)
[  +18 ms] onHover: Offset(22.8, 15.6)
[        ] onHover: Offset(22.2, 15.0)
[  +13 ms] onHover: Offset(21.6, 14.5)
[        ] onHover: Offset(21.0, 13.9)
[  +16 ms] onHover: Offset(20.6, 13.4)
[        ] onHover: Offset(19.7, 12.7)
[  +16 ms] onHover: Offset(19.3, 12.2)
[        ] onHover: Offset(18.4, 11.6)
[  +16 ms] onHover: Offset(18.0, 11.0)
[        ] onHover: Offset(17.5, 10.5)
[  +16 ms] onHover: Offset(17.4, 9.9)
[        ] onHover: Offset(16.8, 9.6)
[  +17 ms] onHover: Offset(16.4, 9.1)
[        ] onHover: Offset(16.1, 8.8)
[  +14 ms] onHover: Offset(16.0, 8.6)
[        ] onHover: Offset(15.7, 8.6)
[  +16 ms] onHover: Offset(15.5, 8.3)
[  +16 ms] onHover: Offset(15.3, 8.1)
[  +16 ms] onHover: Offset(15.1, 8.1)
[        ] onHover: Offset(14.5, 7.8)
[  +16 ms] onHover: Offset(14.3, 7.8)
[        ] onHover: Offset(14.1, 7.6)
[  +16 ms] onHover: Offset(13.6, 7.3)
[        ] onHover: Offset(13.3, 7.3)
[  +16 ms] onHover: Offset(12.8, 7.1)
[        ] onHover: Offset(12.2, 6.8)
[  +15 ms] onHover: Offset(12.1, 6.5)
[        ] onHover: Offset(11.8, 6.5)
[  +16 ms] onHover: Offset(11.6, 6.6)
[        ] onHover: Offset(11.4, 6.3)
[  +15 ms] onHover: Offset(11.2, 6.3)
[  +36 ms] onHover: Offset(10.9, 6.3)
[  +13 ms] onHover: Offset(10.7, 6.3)
[  +16 ms] onHover: Offset(10.5, 6.1)
[        ] onHover: Offset(9.9, 5.8)
[        ] onHover: Offset(9.6, 5.8)
[  +14 ms] onHover: Offset(9.5, 5.6)
[        ] onHover: Offset(8.9, 5.3)
[  +16 ms] onHover: Offset(8.8, 5.0)
[        ] onHover: Offset(8.5, 4.8)
[  +14 ms] onHover: Offset(8.0, 4.5)
[        ] onHover: Offset(7.7, 4.2)
[  +16 ms] onHover: Offset(7.6, 4.0)
[        ] onHover: Offset(7.0, 3.7)
[  +16 ms] onHover: Offset(6.9, 3.7)
[        ] onHover: Offset(6.6, 3.5)
[  +15 ms] onHover: Offset(6.4, 3.2)
[        ] onHover: Offset(6.1, 3.2)
[  +16 ms] onHover: Offset(5.9, 3.0)
[        ] onHover: Offset(5.7, 2.7)
[  +17 ms] onHover: Offset(5.5, 2.5)
[        ] onHover: Offset(5.2, 2.5)
[  +15 ms] onHover: Offset(5.0, 2.2)
[        ] onHover: Offset(4.8, 1.9)
[  +16 ms] onHover: Offset(4.6, 2.0)
[        ] onHover: Offset(4.3, 1.7)
[  +15 ms] onHover: Offset(4.1, 1.4)
[        ] onHover: Offset(3.9, 1.2)
[  +16 ms] onHover: Offset(3.7, 1.2)
[        ] onHover: Offset(3.4, 0.9)
[        ] onHover: Offset(2.8, 0.6)
[  +15 ms] onHover: Offset(2.7, 0.4)
[        ] onHover: Offset(2.4, 0.1)
[  +15 ms] onHover: Offset(2.3, -0.1)
[        ] onHover: Offset(2.0, -0.4)
[  +16 ms] onHover: Offset(1.5, -0.7)
[        ] onHover: Offset(1.2, -1.2)
[  +16 ms] onHover: Offset(0.8, -1.5)
[        ] onHover: Offset(0.5, -2.1)
[  +15 ms] onHover: Offset(0.1, -2.4)
[        ] onHover: Offset(-0.2, -2.9)
[  +16 ms] onHover: Offset(-0.3, -3.2)
[        ] onHover: Offset(-0.9, -3.5)
[  +15 ms] onHover: Offset(-1.1, -4.0)
[        ] onHover: Offset(-1.3, -4.3)
[  +15 ms] onHover: Offset(-1.5, -4.6)
[        ] onHover: Offset(-1.7, -4.8)
[  +16 ms] onHover: Offset(-1.9, -5.1)
[        ] onHover: Offset(-2.2, -5.3)
[  +16 ms] onHover: Offset(-2.3, -5.6)
[        ] onHover: Offset(-2.6, -5.6)
[        ] onHover: Offset(-2.9, -5.9)
[  +16 ms] onHover: Offset(-3.0, -6.1)
[  +96 ms] onHover: Offset(-3.0, -6.3)
[  +19 ms] onHover: Offset(-3.2, -6.4)
[  +34 ms] onHover: Offset(-3.7, -6.8)
[        ] onHover: Offset(-4.3, -7.4)
[  +14 ms] onHover: Offset(-4.4, -8.0)
[        ] onHover: Offset(-5.0, -8.9)
[        ] onHover: Offset(-5.6, -9.9)
[  +15 ms] onHover: Offset(-5.8, -10.5)
[        ] onHover: Offset(-6.4, -11.4)
[  +16 ms] onHover: Offset(-6.8, -12.4)
[        ] onHover: Offset(-7.5, -13.3)
[  +16 ms] onHover: Offset(-7.8, -14.0)
[        ] onHover: Offset(-8.0, -14.5)
[  +14 ms] onHover: Offset(-8.2, -15.1)
[        ] onHover: Offset(-8.7, -15.7)
[  +16 ms] onHover: Offset(-8.8, -16.3)
[        ] onHover: Offset(-9.4, -16.9)
[  +16 ms] onHover: Offset(-9.5, -17.5)
[        ] onHover: Offset(-9.8, -17.8)
[  +16 ms] onHover: Offset(-9.9, -18.4)
[        ] onHover: Offset(-10.2, -18.9)
[  +16 ms] onHover: Offset(-10.6, -19.6)
[        ] onHover: Offset(-10.9, -20.1)
[  +15 ms] onHover: Offset(-11.0, -20.7)
[        ] onHover: Offset(-11.3, -21.3)
[  +15 ms] onHover: Offset(-11.4, -21.6)
[        ] onHover: Offset(-12.0, -22.2)
[  +16 ms] onHover: Offset(-12.1, -22.8)
[        ] onHover: Offset(-12.4, -23.1)
[        ] onHover: Offset(-12.7, -23.6)
[  +14 ms] onHover: Offset(-12.8, -24.3)
[  +17 ms] onHover: Offset(-12.9, -24.6)
[        ] onHover: Offset(-13.2, -24.8)
[        ] onHover: Offset(-13.5, -25.1)
[  +15 ms] onHover: Offset(-13.6, -25.4)
[        ] onHover: Offset(-13.9, -25.6)
[  +15 ms] onHover: Offset(-14.0, -25.9)
[        ] onHover: Offset(-14.0, -26.2)
[  +15 ms] onHover: Offset(-14.2, -26.5)
[  +16 ms] onHover: Offset(-14.4, -26.5)
[        ] onHover: Offset(-14.4, -26.7)
[  +46 ms] onHover: Offset(-14.6, -26.7)
[  +46 ms] onHover: Offset(-14.8, -26.7)
[  +41 ms] onHover: Offset(-15.1, -26.7)
[  +15 ms] onHover: Offset(-15.3, -26.7)
[  +17 ms] onHover: Offset(-15.6, -27.0)
[        ] onHover: Offset(-16.1, -27.0)
[  +16 ms] onHover: Offset(-16.3, -27.2)
[        ] onHover: Offset(-16.9, -27.8)
[  +15 ms] onHover: Offset(-17.0, -28.1)
[        ] onHover: Offset(-17.6, -28.7)
[  +16 ms] onHover: Offset(-18.0, -29.0)
[        ] onHover: Offset(-19.0, -29.6)
[  +16 ms] onHover: Offset(-19.4, -30.2)
[        ] onHover: Offset(-20.4, -31.2)
[  +16 ms] onHover: Offset(-20.7, -31.9)
[        ] onHover: Offset(-21.6, -32.5)
[  +16 ms] onHover: Offset(-22.5, -33.6)
[        ] onHover: Offset(-23.0, -34.1)
[  +15 ms] onHover: Offset(-23.8, -35.2)
[        ] onHover: Offset(-24.4, -35.8)
[        ] onHover: Offset(-24.9, -36.4)
[  +14 ms] onHover: Offset(-25.1, -37.1)
[        ] onHover: Offset(-25.7, -37.6)
[  +16 ms] onHover: Offset(-26.1, -38.3)
[        ] onHover: Offset(-26.7, -38.6)
[  +16 ms] onHover: Offset(-26.8, -39.2)
[        ] onHover: Offset(-27.1, -39.4)
[  +16 ms] onHover: Offset(-27.2, -39.5)
[        ] onHover: Offset(-27.5, -39.8)
[  +16 ms] onHover: Offset(-27.7, -40.0)
[        ] onHover: Offset(-27.9, -40.3)
[  +16 ms] onHover: Offset(-28.1, -40.6)
[  +15 ms] onHover: Offset(-28.3, -40.6)
[        ] onHover: Offset(-28.3, -40.8)
[  +16 ms] onHover: Offset(-28.5, -41.1)
[        ] onHover: Offset(-28.8, -41.1)
[  +16 ms] onHover: Offset(-28.7, -41.4)
[        ] onHover: Offset(-29.0, -41.7)
[  +16 ms] onHover: Offset(-29.2, -42.0)
[  +16 ms] onHover: Offset(-29.4, -42.2)
[        ] onHover: Offset(-29.6, -42.5)
[  +16 ms] onHover: Offset(-29.6, -42.8)
[        ] onHover: Offset(-29.8, -43.0)
[        ] onHover: Offset(-30.1, -43.3)
[  +16 ms] onHover: Offset(-30.2, -43.6)
[        ] onExit: Offset(-30.5, -44.2)
[+1801 ms] onEnter
[   +1 ms] onHover: Offset(299.7, 142.5)
[        ] onHover: Offset(299.5, 142.5)
[  +13 ms] onExit: Offset(282.9, 131.1)
[  +17 ms] onEnter
[        ] onHover: Offset(298.4, 143.0)
[        ] onHover: Offset(298.1, 143.0)
[  +14 ms] onExit: Offset(281.6, 131.6)
[  +16 ms] onEnter
[        ] onHover: Offset(297.0, 143.6)
[        ] onHover: Offset(296.8, 143.6)
[  +15 ms] onExit: Offset(280.4, 131.9)
[  +16 ms] onEnter
[        ] onHover: Offset(296.3, 143.6)
[        ] onHover: Offset(296.0, 143.6)
[  +16 ms] onExit: Offset(280.0, 132.2)
[  +15 ms] onEnter
[        ] onHover: Offset(295.8, 143.8)
[  +15 ms] onExit: Offset(279.5, 132.2)
[  +17 ms] onEnter
[        ] onHover: Offset(294.7, 143.8)
[        ] onHover: Offset(294.1, 143.8)
[  +15 ms] onExit: Offset(277.8, 132.4)
[  +16 ms] onEnter
[        ] onHover: Offset(292.4, 143.8)
[        ] onHover: Offset(292.1, 143.8)
[  +15 ms] onExit: Offset(276.3, 132.5)
[  +16 ms] onEnter
[        ] onHover: Offset(291.3, 143.8)
[  +16 ms] onExit: Offset(275.7, 132.6)
[ +242 ms] onEnter
[        ] onHover: Offset(291.3, 143.8)
[  +24 ms] onExit: Offset(276.2, 132.6)
[  +15 ms] onEnter
[        ] onHover: Offset(293.3, 143.8)
[        ] onHover: Offset(294.7, 143.8)
[  +16 ms] onExit: Offset(280.2, 132.3)
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.12.15, on Mac OS X 10.15.1 19B88, locale en-RU)
    • Flutter version 1.12.15 at /Users/sanekyy/Programs/flutter
    • Framework revision 459c7fb884 (2 days ago), 2019-11-26 17:04:51 +0000
    • Engine revision e136d637a8
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sanekyy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/sanekyy/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.58

[!] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR fixes the algorithm of `TransformLayer` when perspective is involved. The resulting vector of the algorithm should be normalized with `result[3]`, the homogeneous component, which would become non-1.0 in this situation.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/45789

## Tests

I added the following tests:

- TransformLayer.findAllAnnotations correctly transforms with perspective

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/layer.dart [hunk 1]
```diff
@@ -1657,7 +1657,7 @@ class TransformLayer extends OffsetLayer {
       return null;
     final Vector4 vector = Vector4(localPosition.dx, localPosition.dy, 0.0, 1.0);
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart]: Any reason we can't just use `MatrixUtils.transformPoint` here instead of re-implementing the transform logic here?

Comment (dkwingsmt) [reply packages/flutter/lib/src/rendering/layer.dart]: It was like this before me, but the method looks valid. Fixed.

**Review by goderbauer — APPROVED** [review]
LGTM
