### PR TITLE
[flutter_test/integration_test] added setSurfaceSize test coverage

### LINKED ISSUE #82557: [integration_test] HitTest regression with setSurfaceSize
👋

We have a particular use case for `integration_test` where we use `IntegrationTestWidgetsFlutterBinding.setSurfaceSize` in order to simplify scrolling and include more content for the purpose of screenshot reviews.  It seems that `WidgetTester.tap` was working before with `setSurfaceSize`, but now misses.

In Flutter 1.22.6, in combination with `flutter/plugins/integration_test` - this works well.
In Flutter 2.0.6 up to 2.3.0, using `flutter/packages/integration_test` - it appears to have regressed.

I have updated the test case `Test Integration binding setSurfaceSize works` for the two package variants:
* [For the now deprecated, Flutter 1.22.6 variant](https://github.com/prefanatic/plugins/commit/24339d55d177443711c417dfc57f8c2a964bc37b) - this test passes.
* [For the current, Flutter-mainline variant](https://github.com/prefanatic/flutter/commit/fd883f54a817463f5e2e99c16faf328446b0094d) - this test fails.

The test case is equivalent across both, but separate to highlight the regression at some point post 1.22.6.

I've created a small project to help facilitate `git bisect` in discovering where this regression occurred.  [The project can be seen here](https://github.com/prefanatic/integration_test_bisect).  The following bisect parameters were used:

```
git bisect start HEAD 13860a7d23c564ec9ff38a44661d21160c3f7b1e
git bisect run dart ..\integration_test_bisect\tool\integration_test_bisect.dart
```
_HEAD in this case refers to afb98eaec6d9db01630c240f449916b04307e735_

The bisect keyed into a48e14308e41f75b6f63ee2549f4d597646b0dc4 as the source of this particular test failure.  PR https://github.com/flutter/flutter/pull/64846.

I hope this isn't frowned upon, but @dkwingsmt & @goderbauer for pings.

____ 
The following indicates the breakpoint for Flutter 1.22.6, which shows an appropriate hit test transform in a [scaled state](https://github.com/prefanatic/plugins/commit/24339d55d177443711c417dfc57f8c2a964bc37b#diff-55ae4f805fdd2fccacd1a2ccc27832991c80e3f1626c52aa9a336bc40d8956c2R85):
flutter_1 22 6

The following indicates the breakpoint for Flutter 2.3.0-2.0.pre.206, which seems to show a double-transformed hit test result, for the same test case:
flutter_2 3 0

Removing the implementation for `_LiveTestRenderView.hitTest` allows the test to pass on mainline, but given the complexities, and that `_LiveTestRenderView.hitTest` is utilized for more than just `integration_test`, I'm not certain this is the correct approach.

### PR DESCRIPTION
**Pull request by prefanatic**
This PR includes an updated test case for `integration_test` and a new test case for `flutter_test` to ensure that hit tests transform properly when using `setSurfaceSize`, for both the `IntegrationTestWidgetsFlutterBinding` and `LiveTestWidgetsFlutterBinding` bindings.

Aims to resolve https://github.com/flutter/flutter/issues/82557

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by prefanatic** [comment]
@googlebot I signed it!

File: packages/flutter_test/lib/src/binding.dart [hunk 1]
```diff
@@ -1784,15 +1784,6 @@ class _LiveTestRenderView extends RenderView {
     onNeedPaint();
   }
 
-  @override
-  bool hitTest(HitTestResult result, { required Offset position }) {
-    final Matrix4 transform = configuration.toHitTestMatrix();
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/binding.dart:1789]: Removing this seems to break the logic where you can just `flutter run` a test, tap on the screen and it would tell you potential finders for widgets that are under your finger. (Looks like we don't have a test for that behavior, though 😞.) Maybe the transform logic has to move to a place where it only triggers for real pointer events and not for test-simulated ones?

/cc @dkwingsmt since the PR author bisected that this broke with https://github.com/flutter/flutter/pull/64846, which changed how test-simulated and real pointer events are routed in tests.

Comment (dkwingsmt) [reply packages/flutter_test/lib/src/binding.dart:1789]: I'm adding a unit test for the behavior you described and let's see if we can fix this issue without breaking it.

File: packages/integration_test/test/binding_test.dart [hunk 2]
```diff
@@ -44,7 +44,19 @@ Future<void> main() async {
     });
 
     testWidgets('setSurfaceSize works', (WidgetTester tester) async {
-      await tester.pumpWidget(const MaterialApp(home: Center(child: Text('Test'))));
+      int invocations = 0;
```
[the remark this answers is not in the document]
Comment (prefanatic) [reply packages/integration_test/test/binding_test.dart:47]: Thanks for the review - I've decoupled the focused `hitTesting works when using setSurfaceSize` out from the existing `setSurfaceSize works`, and have applied this to both the `integration_test` suite and `flutter_test` suite.

**Comment by dkwingsmt** [comment]
I've added some unit tests for the features that we were afraid of breaking. Can you sync with master and see if all tests pass?

File: packages/flutter_test/lib/src/binding.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter_test/lib/src/binding.dart:1789]: I believe the tests where added in https://github.com/flutter/flutter/pull/83337. @prefanatic Can you rebase this PR to the latest master and see if this is breaking anything?

Comment (prefanatic) [reply packages/flutter_test/lib/src/binding.dart:1780]: @goderbauer Thanks, I've rebased the PR and pushed, looks green.

**Comment by prefanatic** [comment]
@goderbauer Sorry, just getting back around to this --

I'm hoping you can help clear things up for me, trying to study how these pointer events are dispatched.  It's clear that removing `hitTest` from `_LiveTestRenderView` may not be the solution, as it does indeed continue to break the "Some possible finders" hints when running tests under `flutter run`.  

The tests added in #83337 cover "Some possible finders" but not under a `setSurfaceSize` case.  When applying `setSurfaceSize` to these tests, they fail - presumably in a similar fashion to tests added in this PR.

From what I can see, the coordinates from finders determined by `getCenter -> _getElementPoint` are eagerly transformed with the correct scale in mind, through `RenderBox.localToGlobal()`.  For hit testing under `setSurfaceSize`, this already transformed `Offset` eventually passes through `_LiveTestRenderView.hitTest` which does another transformation.  This results in tapping on the wrong spot, and warning about a missed hit.

Now, for "Some possible finders", the pointer event does not seem to be transformed until `_LiveTestRenderView.hitTest`, thus the breakage with the original fix.

I _think_ my direction here should be to ensure that pointer events that drive "Some possible finders" should not rely on `_LiveTestRenderView.hitTest` for  transformation?  In general, `_LiveTestRenderView.hitTest` also causes problems with `warnIfMissed` on taps, as a similar double-transform occurs, where the result of `localToGlobal` is sent to `hitTest`.

**Comment by goderbauer** [comment]
> I think my direction here should be to ensure that pointer events that drive "Some possible finders" should not rely on _LiveTestRenderView.hitTest for transformation?

That sounds like a good direction, yes. Alternatively, we could remove the eager transformation of coordinates from finders, but that would probably mess up running tests under the regular `TestWidgetsFlutterBinding` and require more adjustments there.

> The tests added in #83337 cover "Some possible finders" but not under a setSurfaceSize case. When applying setSurfaceSize to these tests, they fail - presumably in a similar fashion to tests added in this PR.

@dkwingsmt Was experimenting with a test for this scenario in https://github.com/flutter/flutter/pull/86449 (see "Should show event indicator for pointer events with setSurfaceSize" test) and also discovered that those are failing. Can you add that test case to this PR as well so we can make sure it gets fixed with whatever approach we come up with? Thanks!

**Comment by dkwingsmt** [comment]
https://github.com/flutter/flutter/pull/86449 is almost complete and should fix many problems with live tests and `setSurfaceSize`. Can you take a look if your original problems persist? Also if you'd like we can still merge this PR for the additional tests.

**Comment by goderbauer** [comment]
> Also if you'd like we can still merge this PR for the additional tests.

Yes, let's keep this tests to ensure we have good test coverage.

**Comment by prefanatic** [comment]
Thank you both!  With #86449, the original issue is resolved and the test cases in this PR pass.

I've restructured this PR to represent only the added test coverage.

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/82712

**Review by goderbauer — APPROVED** [review]
LGTM once https://github.com/flutter/flutter/pull/86449 is merged and these tests pass

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Now that #86449 is merged, can you update with master and convert this PR out of draft?

**Comment by skia-gold** [comment]
Gold has detected about 35 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/82712

**Comment by goderbauer** [comment]
@prefanatic Can you try rebasing this PR again to get the gold check to pass? Thanks!
