### PR TITLE
Disable Dropdown menu search during keyboard navigation

### LINKED ISSUE #151878: DropdownMenu throws RangeError when both filter and search are enabled in latest beta and master.
### Steps to reproduce

1. Create a DropdownMenu and set both enableFilter and enableSearch to true.
2. Start typing in the TextFiled, and **make sure one of the remaining filtered items is highlighted**. (Enter "b" for code sample)
3. Once the item is highlighted, enter anything that would cause all remaining entries to be filtered. (Enter "a" for code sample)

### Expected results

No errors or exceptions are thrown.

### Actual results

 DropdownMenu throws a RangeError.

Seems to be caused by https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown_menu.dart#L607 when entries is empty.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

// DropdownMenuEntry labels and values for the first dropdown menu.
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  ColorLabel? selectedColor;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: DropdownMenu<ColorLabel>(
            enableFilter: true,
            enableSearch: true,
            controller: colorController,
            requestFocusOnTap: true,
            label: const Text('Color'),
            onSelected: (ColorLabel? color) {
              setState(() {
                selectedColor = color;
              });
            },
            dropdownMenuEntries: ColorLabel.values
                .map<DropdownMenuEntry<ColorLabel>>((ColorLabel color) {
              return DropdownMenuEntry<ColorLabel>(
                value: color,
                label: color.label,
                enabled: color.label != 'Grey',
                style: MenuItemButton.styleFrom(
                  foregroundColor: color.color,
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/fccdfac2-a5bf-445f-aae8-2d6e507527c8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Microsoft Windows [版本 10.0.22631.3880], locale zh-TW)
    • Flutter version 3.23.0-0.1.pre on channel beta at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (6 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\rd1-9\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\rd1-9\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at C:\Users\rd1-9\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #152375: [DropdownMenu] keyboard Navigation broken when `searchCallback` is provided and some entry contains other entry
### Steps to reproduce

Create a dropdown menu with some entry labels that contains other entry labels, with `searchCallback` provided.

Similar to https://github.com/flutter/flutter/issues/147253, but only when a `searchCallback` is provided.
Because the fix (https://github.com/flutter/flutter/pull/147294) was on the default search function.

### Expected results

Arrow key can navigate

### Actual results

Down arrow key cannot navigate to second item

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: DropdownMenu<int>(
          searchCallback: (List<DropdownMenuEntry<int>> entries, String query) {
            if (query.isEmpty) {
              return null;
            }
            final int index = entries.indexWhere(
              (DropdownMenuEntry<int> entry) => entry.label.contains(query),
            );

            return index != -1 ? index : null;
          },
          dropdownMenuEntries: const <DropdownMenuEntry<int>>[
            DropdownMenuEntry<int>(value: 0, label: 'ABC'),
            DropdownMenuEntry<int>(value: 1, label: 'AB'),
            DropdownMenuEntry<int>(value: 2, label: 'ABCD'),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.293, on macOS 14.5 23F79 darwin-arm64, locale en-AU)
    • Flutter version 3.24.0-1.0.pre.293 on channel master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ccd51a7f58 (2 hours ago), 2024-07-26 21:18:26 +0800
    • Engine revision 8714b54a87
    • Dart version 3.6.0 (build 3.6.0-83.0.dev)
    • DevTools version 2.37.1
```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
fixes https://github.com/flutter/flutter/issues/152375

PR https://github.com/flutter/flutter/pull/147294 fix keyboard navigation issue https://github.com/flutter/flutter/issues/147253 by prioritising current selection in default search.

This revert PR https://github.com/flutter/flutter/pull/147294 and fix the issue by disabling `DropdownMenu` search during keyboard navigation instead.

also fixes https://github.com/flutter/flutter/issues/151878 as it is a regression caused by PR https://github.com/flutter/flutter/pull/147294.

Reason for reverting https://github.com/flutter/flutter/pull/147294 : it doesn't fix the keyboard navigation issue if a custom searchCallback(Issue https://github.com/flutter/flutter/issues/152375) is provided, and "prioritising current selection" is ambiguous for a custom searchCallback, so it would be tricky to have searchCallback behave the same way as the default search. Additionally the original search function was agnostic about the state of `DropdownMenu` other than the entry value type, might be good to keep it that way unless needed. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -489,6 +489,7 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
   late List<GlobalKey> buttonItemKeys;
   final MenuController _controller = MenuController();
   late bool _enableFilter;
+  late bool _enableSearch;
   late List<DropdownMenuEntry<T>> filteredEntries;
   List<Widget>? _initialMenu;
   int? currentHighlight;
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/dropdown_menu.dart:495]: One thing that could improve readability here would be to initialize the `late` variables at the declaration site, rather than inside `initState()`.

```dart
late List<GlobalKey> buttonItemKeys = List<GlobalKey>.generate(filteredEntries.length, (int index) => GlobalKey());
final MenuController _controller = MenuController();
late bool _enableFilter = widget.enableFilter;
late bool _enableSearch = widget.enableSearch;
late List<DropdownMenuEntry<T>> filteredEntries = widget.dropdownMenuEntries;
List<Widget>? _initialMenu;
int? currentHighlight;
double? leadingPadding;
late bool _menuHasEnabledItem = filteredEntries.any((DropdownMenuEntry<T> entry) => entry.enabled);
TextEditingController? _localTextEditingController;
```

(Additionally, `_localTextEditingController` could be refactored into a `late` non-nullable field, but that would involve many other changes and might best be saved for its own PR.)

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -865,31 +944,49 @@ void main() {
...
-    );
-    item2material = tester.widget<Material>(button2Material);
-    expect(item2material.color, themeData.colorScheme.onSurface.withOpacity(0.12));
-  }, variant: TargetPlatformVariant.desktop());
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
+    await tester.pumpAndSettle();
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
+    await tester.pumpAndSettle();
+    await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
+    await tester.pumpAndSettle();
```
Comment (nate-thegrate) [inline packages/flutter/test/material/dropdown_menu_test.dart:983]: My understanding is that another test in this file was used to create this one, so I think it's probably fine to leave it as-is.

That being said, the [style guide](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-using-pumpandsettle) recommends against using `pumpAndSettle`. If you're able to switch out those calls for something else, that'd be awesome.

**Review by nate-thegrate — APPROVED** [review]

**Review by nate-thegrate — COMMENTED** [review]
Thanks for fixing this!

I made an optional suggestion; feel free to take a look and implement it if you'd like :)

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 2 above)
Comment (nate-thegrate) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Looks great now, thanks!

**Review by QuncCccccc — COMMENTED** [review]
Thanks so much for the contribution! Just left one question.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 3]
```diff
@@ -611,9 +614,6 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
     if (searchText.isEmpty) {
       return null;
     }
-    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
-      return currentHighlight;
-    }
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:616]: Just a question, why do we remove this block of code? I remember this part is added to fix the keyboard navigation: https://github.com/flutter/flutter/pull/147294.

Comment (PurplePolyhedron) [reply packages/flutter/lib/src/material/dropdown_menu.dart:616]: https://github.com/flutter/flutter/pull/147294  only works on the default search, so the bug still exist when a custom search callback is provided. I used another method to fix the issue which doesn't rely on the search function, and this code is no longer needed. 

The main reason for reverting https://github.com/flutter/flutter/pull/147294 was to keep default search consistent with `searchCallback` where it doesn't have direct access to `currentHighlight`. And since we don't know the match condition of a custom `searchCallback`, we cannot implement "prioritising current selection" for a `searchCallback`, the only way to keep it consistent is to remove the feature. Also I think the original intent of search is to be agnostic about the state of `DropdownMenu`.

However prioritising current selection is a bit more intuitive, and now https://github.com/flutter/flutter/pull/147294 has landed in stable, I am no longer sure removing the feature is correct, since it also affect the behaviour of the search.

**Comment by PurplePolyhedron** [comment]
Solving merge conflict. I closed it by mistake.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks for the fix:)
