### PR TITLE
remove --start-paused flag by default and set useDwdsWebSocketConnect…

### LINKED ISSUE #60289: Web hot reload breaks app when running as Web Server (-d web-server)
### Steps to reproduce

1. Create an empty Flutter project
2. Run `flutter run -d web-server --web-experimental-hot-reload`

Notice that the served Flutter application fails to load and just renders a blank screen.

**Failure Case**

Running `flutter run -d web-server --web-experimental-hot-reload` and opening relevant localhost (http://localhost:53392):

Image

**WAI Cases**

Running `flutter run -d web-server` and opening relevant localhost (http://localhost:53392):

Image

Running `flutter run -d chrome --web-experimental-hot-reload`:

Image

### Code sample

N/A (always breaks regardless of app details)

### Flutter version

**Flutter version observing the above behavior.**
```
Flutter 3.30.0-1.0.pre.520 • channel master • https://github.com/flutter/flutter.git
Framework • revision a7e276a20d (2 days ago) • 2025-03-07 18:43:08 -0800
Engine • revision a7e276a20d (2 days ago) • 2025-03-07 18:43:08 -0800
Tools • Dart 3.8.0 (build 3.8.0-149.0.dev) • DevTools 2.43.0
```

_Side note: I tried upgrading to the latest version on `master` and running on chrome (with hot reload) but that failed entirely. I won't file another ticket as I'm guessing it will be fixed soon, but just in case here's the Flutter version for that:_
```
Flutter 3.30.0-1.0.pre.525 • channel master • https://github.com/flutter/flutter.git
Framework • revision 93c8ed0775 (60 minutes ago) • 2025-03-09 12:36:24 -0400
Engine • revision 93c8ed0775 (60 minutes ago) • 2025-03-09 12:36:24 -0400
Tools • Dart 3.8.0 (build 3.8.0-149.0.dev) • DevTools 2.43.0
```

_Second side note: This is extremely impressive work and such a major value add to the Flutter community! Congrats to all involved! 🎉_

### PR DESCRIPTION
**Pull request by jyameo**
- Removed --start-paused flag by default and set useDwdsWebSocketConnection in DWDS 
- Updated logic for adding middleware and generating loadindicator
- Revert changes in https://github.com/flutter/flutter/pull/170610/

Related to https://github.com/dart-lang/webdev/issues/2605.
Fixes https://github.com/dart-lang/sdk/issues/60289. 

Sibling PR in DWDS: https://github.com/dart-lang/webdev/pull/2629
This PR will need to be submitted before this one. The pubspec must be updated with a new release of DWDS after the changes are submitted

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 1]
```diff
@@ -1079,20 +1075,22 @@ class WebDevFS implements DevFS {
         '// Service worker not loaded in run mode.',
       );
       webAssetServer.writeFile('version.json', FlutterProject.current().getVersionInfo());
+      final bool shouldEnabledLoadIndicator =
```
Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart]: I believe this should be the same as `shouldEnableMiddleware`. As long as the injected client is there, we can use the loading indicator because that is what sends the event to turn it off.

Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart]: nit: `ShouldEnableLoadIndicator`

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart [hunk 2]
```diff
@@ -303,6 +303,27 @@ Please provide a valid TCP port (an integer between 0 and 65535, inclusive).
...
+                .map((Device d) => d.id)
+                .toSet() ??
+            <String>{};
+
+        // If no web devices are connected, or the specified device does not support full debugging (ie. web-server),
+        // we should use DWDS WebSocket connection instead of Chrome-based connection. If no device is specified,
+        // we fall back to the default Chrome connection.
+        final bool useDwdsWebSocketConnection =
+            supportedWebDeviceIds.isEmpty ||
+            !supportedWebDeviceIds.contains(globals.deviceManager?.specifiedDeviceId ?? 'chrome');
```
Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: nit: `GoogleChromeDevice.kChromeDeviceId` instead of `chrome`

Comment (nshahan) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: This logic falling back on chrome here is still slightly confusing to me. Is this effectively the same as:

```
final bool useDwdsWebSocketConnection =
     supportedWebDeviceIds.isEmpty ||
     (globals.deviceManager?.specifiedDeviceId != null &&
     !supportedWebDeviceIds.contains(globals.deviceManager!.specifiedDeviceId!));
```

Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: You're right, it's quite similar. The main difference is that I'm also handling the case where no device is specified at all. That probably won’t happen in practice since `flutter run` typically defaults to Chrome, but in the rare case where `globals.deviceManager?.specifiedDeviceId` is null, I fall back to Chrome as if the user ran `flutter -d chrome`.

That said, I see how this could be confusing. Your version is cleaner and makes more sense. If `globals.deviceManager?.specifiedDeviceId == null`, we can just set `useDwdsWebSocketConnection` to false and skip the fallback logic. I'll make the change now

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 3]
```diff
@@ -1080,22 +1090,23 @@ class WebDevFS implements DevFS {
         '// Service worker not loaded in run mode.',
       );
       webAssetServer.writeFile('version.json', FlutterProject.current().getVersionInfo());
-      final bool shouldEnabledLoadIndicator =
-          globals.deviceManager?.specifiedDeviceId != WebServerDevice.kWebServerDeviceId;
+      final bool shouldEnableLoadIndicator =
+          globals.deviceManager?.specifiedDeviceId == GoogleChromeDevice.kChromeDeviceId ||
```
Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart]: I'm thinking this assignment could just be `shouldEnableMiddleware` instead. I'd also add a comment explaining why the value is what it is e.g. `// Load indicator is only turned off when the injected client is added.`

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart [hunk 4]
```diff
@@ -318,11 +318,12 @@ Please provide a valid TCP port (an integer between 0 and 65535, inclusive).
             <String>{};
 
         // If no web devices are connected, or the specified device does not support full debugging (ie. web-server),
-        // we should use DWDS WebSocket connection instead of Chrome-based connection. If no device is specified,
-        // we fall back to the default Chrome connection.
+        // we should use DWDS WebSocket connection instead of Chrome-based connection.
+
         final bool useDwdsWebSocketConnection =
             supportedWebDeviceIds.isEmpty ||
```
Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: Maybe the logic here would be more obvious if we renamed this to something like `nonWebServerDeviceIds`?

**Review by srujzs — APPROVED** [review]

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 1 above)
Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart]: I changed this to shouldEnableMiddleware but I had to recompute the value here as the previously created `shouldEnableMiddleware` variable is not in scope. hope that's okay?

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 3 above)
Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart]: I changed this to shouldEnableMiddleware but I had to recompute the value here as the previously created shouldEnableMiddleware variable is not in scope. hope that's okay?

Comment (srujzs) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart]: Ah yeah that's fine. Another option is making it a getter in `WebDevFS` and then passing it to `WebAssetServer.start` to avoid the double compute.

**Review by nshahan — APPROVED** [review]
Landing this along with the changes in DWDS should fix https://github.com/dart-lang/sdk/issues/60289? If so feel free to link with the description so it closes.

LGTM.

**Comment by jyameo** [comment]
> Landing this along with the changes in DWDS should fix [dart-lang/sdk#60289](https://github.com/dart-lang/sdk/issues/60289)? If so feel free to link with the description so it closes.
> 
> LGTM.

Yes, that's right. I did a bunch of test locally and it should fix the issue above. However, it would be great if you can run some test as well to validate that all the various path (Amd vs DDLibraryBundle, Chome vs web-server) work as expected and make sure we didn't miss something. @nshahan @srujzs Thank you

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 3 above)
Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart]: I updated the code to use a getter to avoid the double compute

**Comment by srujzs** [comment]
Tried it out locally and it looks like AMD vs DDC library bundle/web-server (with Chrome/Safari/Firefox) vs Chrome all work correctly! LGTM!

**Comment by jyameo** [comment]
@bkonyi Hey Ben, I'm seeing some CI failures related to `test/integration.shard/widget_preview_test.dart`: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8711802314632568497/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_9_9/stdout


It seems the test `flutter widget-preview start: can connect to an existing DTD instance` is timing out. Have you seen this failure before and do you have more context on what could be causing this?

**Comment by jyameo** [comment]
@nshahan @srujzs: I updated the logic for `useDwdsWebSocketConnection` and `shouldEnableMiddleware` to use local device information instead of `globals.deviceManager?.specifiedDeviceId`, which can be null when running in subprocess contexts (e.g., `widget_preview_test`). Now it uses `chromiumLauncher != null` and `device!.device is ChromiumDevice` for more reliable device detection. This should fix the test that was broken @nshahan @srujzs  Does this make sense to you? 

Also I am no longer able to test the `DdcLibraryBundle + Webserver` path for some reason.... Is there a flag I should be using? I tried with `--web-experimental-hot-reload` but doesn't look like it's using the DdcLibraryBundle anymore as the value of `ddcmodulesystem` is false with or without the flag.... can you please confirm if there is a way to test this configuration with my latest changes to make sure it's still working as expected?

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart [hunk 5]
```diff
@@ -317,13 +317,11 @@ Please provide a valid TCP port (an integer between 0 and 65535, inclusive).
...
-        // If no web devices are connected, or the specified device does not support full debugging (ie. web-server),
-        // we should use DWDS WebSocket connection instead of Chrome-based connection.
-
+        // Use Chrome-based connection only if we have a connected ChromiumDevice
+        // Otherwise, use DWDS WebSocket connection
         final bool useDwdsWebSocketConnection =
-            nonWebServerConnectedDeviceIds.isEmpty ||
-            (globals.deviceManager?.specifiedDeviceId != null &&
-                !nonWebServerConnectedDeviceIds.contains(globals.deviceManager!.specifiedDeviceId));
+            !(device!.device is ChromiumDevice &&
```
Comment (srujzs) [inline packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: I think we can just check if `_chromiumLauncher != null` here as well as its assigned above?

**Review by srujzs — APPROVED** [review]
I think that sounds okay generally, but I'm not sure how `device.device` and `globals.DeviceManager` differ.

I believe you'll need to revert Nick's changes in https://github.com/flutter/flutter/pull/170610/commits (which always uses AMD when using web-server) in this PR.

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart (hunk 5 above)
Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: updated code to use _chromiumLauncher! Thanks

Comment (jyameo) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: Also reverted Nick's changes and tested locally that all configs are working

Comment (nshahan) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart]: @stuartmorgan-g This change fixes the issues and reverts the workaround I landed for the `-d web-server` issue you ran into.

**Comment by quyenlv-unicloud** [comment]
~~Sorry I not understand, this MR lead to issue https://github.com/flutter/flutter/issues/171221, when run web-server it not wait click Dart Debug Extension so can not debug when run web-server.
Issue resolved by 3.34.0-0.1.pre but happen again at 3.35.0-0.0.pre.
My question is will https://github.com/flutter/flutter/pull/171648 resolve issue https://github.com/flutter/flutter/issues/171221 again and can debug when run web-server?~~

my mistake, It is behavior change/known issue, I will wait release and check later.
before: start web-server > blank page > click Extension > load > debug
now: start web-server > load > click Extension > debug

**Comment by bkonyi** [comment]
@jyameo are you familiar with the issue @quyenlv-unicloud is referring to?

**Comment by jyameo** [comment]
> Sorry I not understand, this MR lead to issue #171221, when run web-server it not wait click Dart Debug Extension so can not debug when run web-server. Issue resolved by 3.34.0-0.1.pre but happen again at 3.35.0-0.0.pre. My question is will #171648 resolve issue #171221 again and can debug when run web-server?

@quyenlv-unicloud It sounds like what you're experiencing might be a separate issue from the one originally tracked here. Could you please create a new issue and include the specific steps to reproduce the problem you're seeing when running the web server? This will help us investigate it properly and track it independently.
