### PR TITLE
[ Cocoon ] Wait for task results to be received by the task runner before shutting down the task process

### LINKED ISSUE #155475: integration tests failing with "(-32000) Service connection disposed"
I believe that this is the root cause of https://github.com/flutter/flutter/issues/153578, which was that MANY integration tests in the flutter/packages repo were timing out. After I landed https://github.com/flutter/flutter/pull/154970, these should no longer time out, and I found https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8736798859005867345/+/u/Run_package_tests/drive_examples/stdout, which from the stacktrace would have timed out before my change.

```
00:39 +16 ~1 -1: loading /Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart [E]                                   
  ext.flutter.integrationTest: (-32000) Service connection disposed
  package:vm_service/src/vm_service.dart 261:34                      new _OutstandingRequest
  package:vm_service/src/vm_service.dart 1778:25                     VmService._call.<fn>
  package:vm_service/src/vm_service.dart 1790:8                      VmService._call
  package:vm_service/src/vm_service.dart 1729:14                     VmService.callServiceExtension
  package:flutter_tools/src/test/integration_test_device.dart 98:25  IntegrationTestTestDevice.start.<fn>
  dart:async/zone.dart 1422:47                                       _rootRunUnary
  dart:async/zone.dart 1324:19                                       _CustomZone.runUnary
  dart:async/zone.dart 1233:7                                        _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 366:11                                 _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 297:7                                  _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 777:19                           _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 651:7                            _StreamController._add
  dart:async/stream_controller.dart 606:5                            _StreamController.add
  dart:async/zone.dart 1422:47                                       _rootRunUnary
  dart:async/zone.dart 1324:19                                       _CustomZone.runUnary
  dart:async/zone.dart 1233:7                                        _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 366:11                                 _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 542:14                                 _DelayedData.perform
  dart:async/stream_impl.dart 647:11                                 _PendingEvents.handleNext
  dart:async/stream_impl.dart 618:7                                  _PendingEvents.schedule.<fn>
  dart:async/zone.dart 1406:47                                       _rootRun
  dart:async/zone.dart 1317:19                                       _CustomZone.run
  dart:async/zone.dart 1225:7                                        _CustomZone.runGuarded
  dart:async/zone.dart 1265:23                                       _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1414:13                                       _rootRun
  dart:async/zone.dart 1317:19                                       _CustomZone.run
  dart:async/zone.dart 1225:7                                        _CustomZone.runGuarded
  dart:async/zone.dart 1265:23                                       _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 40:21                           _microtaskLoop
  dart:async/schedule_microtask.dart 49:5                            _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                       _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                          _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                           _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12                       _RawReceivePort._handleMessage
```

I'm also seeing this in a lot of devicelab tests in the flutter/flutter repo:

- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8736499130357881889/+/u/run_new_gallery__transition_perf/stdout
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8736262697040472033/+/u/run_gradle_plugin_fat_apk_test/stdout
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8736260054150681217/+/u/run_draw_vertices_perf_opengles__timeline_summary/stdout

### PR DESCRIPTION
**Pull request by bkonyi**
Prior to this fix, `_TaskRunner.run` would immediately cleanup the keep-alive port once the task completed, which would result in the isolate shutting down as soon as the task result was returned from `ext.cocoonRunTask` callback in the form of a
`ServiceExtensionResponse`. Since the service extension response is processed by the service isolate, it was possible for the VM to start shutting down before the service isolate could send the task result data back to the task runner.

This change introduces a new service extension,
`ext.cocoonTaskResultReceived`, that the task runner invokes after it receives the task result from `ext.cocoonRunTask`, notifying the task process that it can close the keep-alive port and shutdown.

Fixes https://github.com/flutter/flutter/issues/155475

### CODE REVIEW

File: dev/devicelab/lib/framework/runner.dart [hunk 1]
```diff
@@ -301,37 +308,23 @@ Future<ConnectionResult> _connectToRunnerIsolate(Uri vmServiceUri) async {
...
+    required VmService service,
+    required String isolateId,
+  }) async {
+  try {
+    await service.callServiceExtension(
+      'ext.cocoonTaskResultReceived',
+      isolateId: isolateId,
+    );
+  } on RPCError {
+    // The target VM may shutdown before the response is received.
```
Comment (jmagman) [inline dev/devicelab/lib/framework/runner.dart:321]: Should we log? Or is that expected to happen often?

File: dev/devicelab/test/runner_test.dart [hunk 2]
```diff
@@ -40,5 +41,31 @@ void main() {
       expect(printLog[0], 'Consistently failed across all 3 executions.');
       expect(printLog[1], 'flaky: false');
     });
+
+    test('Regression test for https://github.com/flutter/flutter/issues/155475.', () async {
```
Comment (jmagman) [inline dev/devicelab/test/runner_test.dart:45]: nit: I think usually we don't name tests after the GitHub issue, but instead what the test is actually checking for.  Doesn't matter that much though.

File: dev/devicelab/lib/framework/runner.dart (hunk 1 above)
Comment (bkonyi) [reply dev/devicelab/lib/framework/runner.dart:321]: I don't think it's worth logging since there's not really anything actionable here and we're not losing any state. This error will be thrown at the same frequency we've been seeing in https://github.com/flutter/flutter/issues/155475 as it's fundamentally the same issue, just in a location where the error can be safely ignored.

File: dev/devicelab/test/runner_test.dart (hunk 2 above)
Comment (bkonyi) [reply dev/devicelab/test/runner_test.dart]: Done!

**Review by jmagman — APPROVED** [review]
Thank you!
