### PR TITLE
Fix expanded DropdownMenu panel is shorter than text field

### LINKED ISSUE #172680: DropdownMenu children is shorter than the TextField when it expands to full-screen width
### Steps to reproduce

1. Set `expandedInsets: EdgeInsets.zero,` and make the `DropdownMenu` fully expands to the screen width.
2. Open menu

### Expected results

The item width should be equal to the width of the text field.

### Actual results

The item width is shorter.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: DropdownMenu<int>(
            expandedInsets: EdgeInsets.zero,
            dropdownMenuEntries: <DropdownMenuEntry<int>>[
              DropdownMenuEntry<int>(value: 0, label: 'hhh'),
            ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes DropdownMenu menu panel being shorter than the TextField when it expands to full-screen width.

## Before

The menu panel is shorter than the text field:

image

## After

The menu panel expands as close as possible to the edge similarly to the text field.

image

## Code sample

<details><summary>Code sample for recordings</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: DropdownMenu<int>(
          expandedInsets: EdgeInsets.zero,
          dropdownMenuEntries: <DropdownMenuEntry<int>>[
            DropdownMenuEntry<int>(value: 0, label: 'Flutter'),
          ],
        ),
      ),
    );
  }
}


``` 
</details> 

## Implementation details

MenuAnchor automatically adds a default padding, see https://github.com/flutter/flutter/blob/2c21273bfde5da921df512034f30ff7fd042db97/packages/flutter/lib/src/material/menu_anchor.dart#L81-L82

This PR add a property to menu anchor to expose the view padding.
DropdownMenu sets this padding to EdgeInsets.zero to opt-out from the default 8 padding.

## Related Issue

Fixes [DropdownMenu children is shorter than the TextField when it expands to full-screen width](https://github.com/flutter/flutter/issues/172680)

## Tests

Adds 2 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -318,6 +319,11 @@ class MenuAnchor extends StatefulWidget {
   /// to rebuild this child when those change.
   final Widget? child;
 
+  /// The padding between the edge of the safe area and the menu panel.
+  ///
+  /// Defaults to EdgeInsets.all(8).
+  final EdgeInsetsGeometry? viewPadding;
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/menu_anchor.dart]: nit: I know viewPadding has been used in _Submenu, but for a public API, I just feel this name is a bit confusing. It sounds like this is the same as MenuStyle.padding. How about reservedPadding? Please let me know if there are more name proposals!

**Review by QuncCccccc — APPROVED** [review]
NICE fix! Thank you! LGTM.

File: packages/flutter/lib/src/material/menu_anchor.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/menu_anchor.dart]: `reservedPadding` seems great to me!
I will push a commit asap.
