### PR TITLE
Fix TextField intrinsic width when hint is not visible

### LINKED ISSUE #93337: [TextField] The computation of the intrinsic width of a TextField should include the hint width only when visible
Currently, when a `TextField` has decoration with an hint text, the width of this hint element is always integrated into the computation of the intrinsic width of the `TextField` widget, even if this hint is not displayed (= when the `TextField` text is not empty). This do not really make sense. As a consequence of this, when wrapping a `TextField` with an hint into an `IntrinsicWidth` widget or when setting a `suffixText` decoration to the `TextField`, the result is not the one you would expect as the minimal width of the text field would be constrained by the hint width. 
This should be fixed by integrating the width of the hint text into the computation of the `TextField` intrinsic width only when its text is empty (=when the hint is actually displayed).

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR changes the TextField intrinsic width computation for non-empty TextField. 

Before:

When a TextField is non-empty, the intrinsic width can't be smaller than the hint width:

image

After:

The width does not depend on the hint when the TextField is non empty.

image

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: Center(
          child: IntrinsicWidth(
            child: TextField(
              decoration: InputDecoration(
                filled: true,
                hintText: 'Moderately long hint text',
              ),
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

## Related Issue

Fixes [[TextField] The computation of the intrinsic width of a TextField should include the hint width only when visible](https://github.com/flutter/flutter/issues/93337)

## Tests

Adds 2 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -651,8 +655,7 @@ class _Decoration {
     prefixIcon,
     suffixIcon,
     helperError,
-    counter,
-    container,
+    Object.hash(counter, container),
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/input_decorator.dart:658]: Oh dang—I guess that 1 extra field puts the class over the max argument count for `Object.hash()`.

Perhaps `Object.hashAll()` could be used here instead, though I really don't know whether that would make it better or worse (I'm sure the change in performance would be negligible).

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -586,6 +587,7 @@ class _Decoration {
   final _InputBorderGap borderGap;
   final bool alignLabelWithHint;
   final bool? isDense;
+  final bool? isEmpty;
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/input_decorator.dart:590]: Could we make this non-nullable?

```suggestion
  final bool isEmpty;
```

File: packages/flutter/test/material/input_decorator_test.dart
Comment (nate-thegrate) [inline packages/flutter/test/material/input_decorator_test.dart:1]: The tests you added look phenomenal, as per usual 👍

**Review by nate-thegrate — COMMENTED** [review]
Thanks for the PR, looks like a fantastic improvement overall.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:658]: Similar code in the framework use nested `object.hash` (and its 20 parameters :smile:) that's why I use it.
`Object.hashAll` is used when there is already an iterable available. I don't think moving long hash logic to hashAll() will improve the readability.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 2 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:590]: Yes, good catch!

**Review by nate-thegrate — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by bleroux** [comment]
@justinmc When you have some bandwidth, thank you for having a look at these Google testing failures.

This PR changes the default intrinsic width computation (ignoring the hint width when the field is not empty). Maybe we should consider introducing a new property to control this behavior?

**Review by justinmc — COMMENTED** [review]
The code looks good, minus the Google failures. I see three categories of failures:

  1. Expected visual diff changes where a field becomes less wide.
  2. Unexpected visual diff changes in the vertical size of a field.
  3. Unexpected changes in a displayed value in some tests (maybe caused by a misclick due to layout problems from the previous point).

I think I can reproduce the problem from point 2:

<details>

<summary>Example code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 100.0),
            child: const IntrinsicWidth(
              child: TextField(
                maxLines: null,
                decoration: InputDecoration(
                  filled: true,
                  hintText: 'Moderately long hint text',
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>


https://github.com/user-attachments/assets/cae52a17-b92a-4a4f-b3d1-a0eda8a80ee3

**Comment by justinmc** [comment]
Yeah I think I agree with the idea of adding a parameter. The difference is big enough to warrant one, and I do imagine some people might still prefer the old way.

With a parameter, do you plan for it to work like it was when I reviewed it above? With the current state of the PR, it seems like it might affect the height of normal fields too, by looking at the failing Google tests.

**Comment by bleroux** [comment]
> With a parameter, do you plan for it to work like it was when I reviewed it above? 

No because the height issue was bad

I updated the PR to demonstrate what this parameter solution could be.
The point is to replace the `maintainHintHeight` with a parameter that control both height and width, I proposed `maintainHintSize`. This parameter defaults to true to keep the current behavior (text field size can't be less than hint size).
When set to false, the hint will be ignored for both height and width computation when it is not visible (aka when the field is not empty).

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -2699,7 +2724,12 @@ class InputDecoration {
     this.hintTextDirection,
     this.hintMaxLines,
     this.hintFadeDuration,
+    @Deprecated(
+      'Use maintainHintSize instead. '
+      'This feature was deprecated after v3.28.0-2.0.pre.',
+    )
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/input_decorator.dart:2730]: We should probably have another sentence here, per the [deprecation policy](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#deprecations).

**Review by nate-thegrate — APPROVED** [review]
LGTM with 1 small nit. Thanks again for doing this!

**Review by justinmc — APPROVED** [review]
LGTM :+1:. All comments are nits. I tried it out and it works great. I definitely agree that adding the parameter is the right move.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 4]
```diff
@@ -4029,6 +4084,7 @@ class InputDecoration {
       if (hintMaxLines != null) 'hintMaxLines: "$hintMaxLines"',
       if (hintFadeDuration != null) 'hintFadeDuration: "$hintFadeDuration"',
       if (!maintainHintHeight) 'maintainHintHeight: false',
+      if (!maintainHintSize) 'maintainHintSize: false',
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:4087]: Interesting! I checked and the reason is that this toString implementation was designed to only output fields that don't use their default value. This pattern (hardcoding the non-default boolean value) was introduced in the early days, see https://github.com/flutter/flutter/pull/9119. I think it is ok to keep it as-is for this PR and we might decide to change the whole toString at one point.

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/input_decorator.dart:4106]: Got it, thanks for the investigation!

**Comment by TiberioZ** [comment]
Is this fixed bug works with CupertinoTextField ? I've tried and it seems not working, maybe I'm doing it wrong...

const IntrinsicWidth(
     child: CupertinoTextField(
              placeholder: "search",
     ),
)

**Comment by bleroux** [comment]
@TiberioZ
This fix applies to InputDecorator which is not used by CupertinoTextField.
If you want a similar feature for the CupertinoTextField, thank you to create a new issue.
