### PR TITLE
Fix ios black screen during splash screen if widget binding initializ…

### LINKED ISSUE #39494: WidgetsFlutterBinding.ensureInitialized() takes down splash screen too early.
In https://github.com/flutter/flutter/pull/38464 we changed it to require a call to `WidgetsFlutterBinding.ensureInitialized` before your runApp if you want to access method channels. Unfortunately, this means that the native splash screen gets taken down too early and a black screen is shown. Repro-case:

```dart
import 'package:flutter/material.dart';
import 'dart:async';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Timer(Duration(seconds: 10), () {
    runApp(Placeholder());
  });
}
```

(Instead of running a timer, a real app may wait for data from the native side before calling runApp).

### PR DESCRIPTION
**Pull request by chunhtai**
…ed before runapp

## Description

When ios engine starts up, it will send semantics enable message to framework if the binding has been initialized. Framework will schedule a new frame to make sure the semantics tree gets sent to the engine. This makes engine thinks the framework is ready to produce frame and takes down the splash screen.

This pr make sure scheduler binding only schedule frame when widget binding think it is ready by overriding the frameEnabled getter.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39494

## Tests

I added the following tests:

"The frames will only be enabled after runApp has bootstrapped the app"

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 4.
Please triage them at https://flutter-gold.skia.org/search?issue=52913.

**Comment by chunhtai** [comment]
apparently it broke all the tests, I will add a WIP label

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -907,6 +907,11 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
   Element get renderViewElement => _renderViewElement;
   Element _renderViewElement;
 
+  bool _appHasBootStapped = false;
+
+  @override
+  bool get framesEnabled => super.framesEnabled && _appHasBootStapped;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/binding.dart]: "BootStapped" isn't english... what did you mean? :-)

Comment (Hixie) [reply packages/flutter/lib/src/widgets/binding.dart]: maybe "rootWidgetAttached"?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart]: I misspelled bootstrapped. but your suggestion may be better. will update

**Comment by chunhtai** [comment]
ready for review

File: packages/flutter/lib/src/widgets/binding.dart [hunk 2]
```diff
@@ -907,6 +907,11 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
   Element get renderViewElement => _renderViewElement;
   Element _renderViewElement;
 
+  bool _rootWidgetAttached = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/binding.dart]: We already have https://master-api.flutter.dev/flutter/widgets/WidgetsBinding/isRootWidgetAttached.html, what's the difference between isRootWidgetAttached and _rootWidgetAttached?

File: packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+import 'dart:typed_data';
+
+import 'package:flutter/scheduler.dart';
+import 'package:flutter/services.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:flutter/widgets.dart';
+
+void main() {
+  test('The frames will only be enabled after runApp attaches the root widget', () async {
+    final WidgetsFlutterBinding binding = WidgetsFlutterBinding.ensureInitialized() as WidgetsFlutterBinding;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart]: Why does this need to be casted to a WidgetsFlutterBinding? `ensureInitialized` returns a WidgetsBinding, which should give you access to everything you may want to call.

File: packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+    expect(SchedulerBinding.instance.framesEnabled, isFalse);
+    // Framework starts with detached statue. Sends resumed signal to enable frame.
```
Comment (goderbauer) [inline packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart]: statue? Do you mean state?

File: packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart [hunk 5]
```diff
@@ -0,0 +1,23 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
```
Comment (goderbauer) [inline packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart]: It would also be good to have an actual regression test for the issue, e.g. that calling `scheduleInitialSemantics` before a root widget is attached doesn't cause frames to pump.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart]: I see, the name is confusing. I cannot use isRootWidgetAttached because it schedules the first frame during attaching the root widget, the frames should be enabled before that.

File: packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart]: I copied from the other test. will update

File: packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart (hunk 5 above)
Comment (chunhtai) [reply packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart]: sounds good, let me try.

File: packages/flutter/lib/src/widgets/binding.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart]: I actually have some question about https://github.com/flutter/flutter/pull/40105. What is the issue behind this pr?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/binding.dart]: `isRootWidgetAttached` is just a getter. How does it schedule a frame?

> I actually have some question about #40105. What is the issue behind this pr?

The issue is described in the PR's description. What's your question?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart]: >After the change in #39535 we were only scheduling the first frame on accident as a side-effect of the warm-up frame (SchedulerBinding. scheduleWarmUpFrame awaits SchedulerBinding.endOfFrame, which implicitly schedules a frame)

I know it is a fact, but what problem will it cause if we keep this behavior?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/binding.dart]: Everything will continue to work as before because the warmup frame schedules the first frame as a side effect. However, if we ever were to remove the warmup frame, things would start to break. Therefore, we decided to make scheduling the first frame more explicit.

**Comment by chunhtai** [comment]
ready for review @goderbauer

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/binding.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/binding.dart]: fwiw you ended up going with a different name -- i'm fine with either, just wanted to mention it since you said above that you like the specific name i'd suggested.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/binding.dart]: The rootWidgetAttached will confuse with the existing https://api.flutter.dev/flutter/widgets/WidgetsBinding/isRootWidgetAttached.html. This field actually need to be set to true right before attaching the root widget. That is why i change the name.
