### PR TITLE
Change flutter_tools tests to run via pub

### LINKED ISSUE #7941: Is flutter_tools/test/all.dart still needed?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/all.dart

It has a comment at the top which says it's only needed due to
https://github.com/dart-lang/test/issues/327

That's resolved.  So I'm not sure if the comment is wrong (and it's still needed for other reasons, like coverage?) or if it can be deleted.

### PR DESCRIPTION
**Pull request by tvolkert**
`all.dart` is no longer needed. Furthermore, it causes tests to
be skipped, or to silently fail to run anything.

Fixes #7941

### CODE REVIEW

**Comment by tvolkert** [comment]
@Hixie

File: packages/flutter_tools/lib/src/base/process_manager.dart [hunk 1]
```diff
@@ -13,9 +13,12 @@ import 'file_system.dart';
 import 'process.dart';
 
 const String _kRecordingType = 'process';
+const ProcessManager _kLocalProcessManager = const LocalProcessManager();
 
 /// The active process manager.
-ProcessManager get processManager => context[ProcessManager];
+ProcessManager get processManager => context == null
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/base/process_manager.dart]: nit: we prefer `{ return ... }` over `=>` for multiline expressions.

File: packages/flutter_tools/test/analyze_continuously_test.dart [hunk 2]
```diff
@@ -58,15 +58,17 @@ void main() {
...
+    });
 
     await server.start();
     await onDone;
 
     expect(errorCount, 2);
   }, overrides: <Type, Generator>{
     OperatingSystemUtils: () => os
-  });
+  }, skip: true /* TODO(tvolkert): fix and enable */);
```
Comment (Hixie) [inline packages/flutter_tools/test/analyze_continuously_test.dart]: what's the failure?

File: packages/flutter_tools/test/test_test.dart [hunk 3]
```diff
@@ -43,16 +48,29 @@ Future<Null> _testFile(String testName, int wantedExitCode, String workingDirect
...
+
+  while (_testExclusionLock != null)
+    await _testExclusionLock;
+
+  ProcessResult exec;
+  final Completer<Null> testExclusionCompleter = new Completer<Null>();
+  _testExclusionLock = testExclusionCompleter.future;
+  try {
+    exec = await Process.run(
+        fs.path.join(dartSdkPath, 'bin', 'dart'),
```
Comment (Hixie) [inline packages/flutter_tools/test/test_test.dart]: nit: indent by 2

File: packages/flutter_tools/test/src/ios/ios_workflow_test.dart [hunk 4]
```diff
@@ -123,7 +123,8 @@ void main() {
       when(xcode.eulaSigned).thenReturn(true);
       final ValidationResult result = await new IOSWorkflowTestTarget().validate();
       expect(result.type, ValidationType.installed);
-    }, overrides: <Type, Generator>{ Xcode: () => xcode });
+    }, overrides: <Type, Generator>{ Xcode: () => xcode },
+        skip: true /* TODO(tvolkert): fix and enable */);
```
Comment (Hixie) [inline packages/flutter_tools/test/src/ios/ios_workflow_test.dart]: cc @chinmaygarde

**Comment by Hixie** [comment]
LGTM

File: packages/flutter_tools/test/analyze_continuously_test.dart (hunk 2 above)
Comment (tvolkert) [inline packages/flutter_tools/test/analyze_continuously_test.dart]: `expect(errorCount, 2)` -- there's only one error.  I figured investigating in a follow-on change made sense since this change at least enables a bunch of test files that were previously being skipped (such as this file).

File: packages/flutter_tools/test/src/ios/ios_workflow_test.dart (hunk 4 above)
Comment (tvolkert) [inline packages/flutter_tools/test/src/ios/ios_workflow_test.dart]: The validation type is `partial` (not `installed`, as expected).  Presumably this is because this test was another one that wasn't being run, and we've added validation requirements since the test was written.
