### PR TITLE
ShowCaretOnScreen is correctly scheduled within a SliverMainAxisGroup

### LINKED ISSUE #135407: SliverMainAxisGroup's childScrollOffset method not overridden
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code below
2. Taps on the second blue tile

### Expected results

The second blue tile should be at the top of the screen

simulator_screenshot_D1FDDB18-3582-4BD9-93B5-57E15CAE2088

### Actual results

The first blue tile is at the top of the screen

simulator_screenshot_4EA8BEBA-5B20-4816-933E-8FC207F9D0E3

I think it's because the `childScrollOffset` method of `SliverMainAxisGroup` is not overridden, therefore it always returns 0.0.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyHome()));
}

class MyHome extends StatelessWidget {
  const MyHome({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: CustomScrollView(
        slivers: [
          Tile(color: Colors.green),
          Tile(color: Colors.greenAccent),
          Tile(color: Colors.green),
          Tile(color: Colors.greenAccent),
          Tile(color: Colors.green),
          Tile(color: Colors.greenAccent),
          SliverMainAxisGroup(slivers: [
            Tile(color: Colors.blue),
            Tile(color: Colors.lightBlueAccent),
            Tile(color: Colors.blue),
            Tile(color: Colors.lightBlueAccent),
            Tile(color: Colors.blue),
            Tile(color: Colors.lightBlueAccent),
          ]),
          Tile(color: Colors.yellow),
          Tile(color: Colors.yellowAccent),
          Tile(color: Colors.yellow),
          Tile(color: Colors.yellowAccent),
          Tile(color: Colors.yellow),
          Tile(color: Colors.yellowAccent),
        ],
      ),
    );
  }
}

class Tile extends StatelessWidget {
  const Tile({
    super.key,
    required this.color,
  });

  final Color color;

  @override
  Widget build(BuildContext context) {
    return SliverToBoxAdapter(
      child: GestureDetector(
        onTap: () {
          Scrollable.ensureVisible(context);
        },
        child: SizedBox(
          height: 100,
          child: ColoredBox(
            color: color,
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
</details>

### Logs

<details><summary>Logs</summary>
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 12.5.1 21G83 darwin-arm64, locale fr-FR)
    • Flutter version 3.13.2 on channel stable at /Users/xxx/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (5 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-14.0.0.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • IN2023 (mobile)            • 87950fce                             • android-arm64  • Android 13 (API 33)
    • iPhone 13 Pro Max (mobile) • F7BD4E2B-91F5-47DA-9594-0D808C2C260C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #141577: TextField and TextFormField in SliverMainAxisGroup scroll the screen up when in focus
### Steps to reproduce

1. Create a Custom ScrollView and put a TextField in it at such a distance that you need to scroll the screen down to it. 
2. Click, highlight, or change something inside the TextField

### Expected results

Changing data inside a textfield

### Actual results

Changing data inside a textfield + screen will scroll up on every change

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverMainAxisGroup(
            slivers: [
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.blue,
                  height: 500,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.red,
                  height: 500,
                ),
              ),
              const SliverToBoxAdapter(child: TextField()),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.green,
                  height: 500,
                ),
              ),
            ],
          )
        ],
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/66907532/67a92ecf-d596-42ed-9d38-54c0fd32e937

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
molchanovia@Air-Igor Projects % flutter doctor -v


[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale
    ru-RU)
    • Flutter version 3.16.7 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.13.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (4 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/molchanovia/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/molchanovia/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/molchanovia/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.81.20231227

[✓] Connected device (1 available)
    • iPhone 15 (mobile) • 99881AD8-A92E-4FFF-B463-BFCA1D46274C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes #141577 
Fixes #135407

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 1]
```diff
@@ -1245,7 +1245,7 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
       trailingEdgeOffset: trailingEdgeOffset,
       currentOffset: currentOffset,
     );
-    if (targetOffset == null) {
+    if (targetOffset == null || !targetOffset.offset.isFinite) {
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/viewport.dart:1248]: I think the viewport should not require a change here, since the issue lies in the sliver.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart:1248]: Would the comment below here still be accurate with this change?

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 2]
```diff
@@ -206,6 +206,30 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
+    final GrowthDirection growthDirection = constraints.growthDirection;
+    switch (growthDirection) {
+      case GrowthDirection.forward:
+        double childScrollOffset = 0.0;
+        RenderSliver? current = childBefore(child as RenderSliver);
+        while (current != null) {
+          childScrollOffset += current.geometry!.scrollExtent;
+          current = childBefore(current);
+        }
+        return childScrollOffset;
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_group.dart:221]: Should this value be available through the childMainAxisPosition method that already exists?

**Review by Piinks — COMMENTED** [review]
Hey @yiiim thanks for contributing! I wonder, would overriding showOnScreen for RenderSliverMainAxisGroup be the right approach here?

File: packages/flutter/lib/src/rendering/sliver_group.dart (hunk 2 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/sliver_group.dart:221]: It might not work, `childMainAxisPosition` is calculated by `calculatePaintOffset`, which may not be accurate for invisible elements.

**Comment by yiiim** [comment]
> Hey @yiiim thanks for contributing! I wonder, would overriding showOnScreen for RenderSliverMainAxisGroup be the right approach here?

I disagree, `RenderSliverMainAxisGroup` needs to return the correct value for `childScrollOffset` instead of 0.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart]: Can you share an example of that? An infinitely long sliver that precedes a text field would mean the text field is absolutely inaccessible.

File: packages/flutter/lib/src/rendering/sliver_group.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_group.dart:221]: Ah I see, thanks for clarifying

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 3]
```diff
@@ -1253,6 +1253,7 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
       return MatrixUtils.transformRect(transform, rect ?? descendant.paintBounds);
     }
 
+    assert(targetOffset.offset.isFinite);
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/viewport.dart:1256]: Is this assertion necessary?

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart:1256]: I ask because I wonder what this scenario is, and if we can catch it sooner in a place that would provide better context to the user in an error message to help debug. :)

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart]:
```dart
import 'package:flutter/material.dart';

FocusNode focusNode = FocusNode();
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverMainAxisGroup(
              slivers: [
                SliverList.builder(
                  itemBuilder: (context, index) {
                    return Container(
                      height: 44,
                    );
                  },
                ),
                SliverToBoxAdapter(
                  child: TextField(
                    focusNode: focusNode,
                  ),
                ),
              ],
            ),
          ],
        ),
        floatingActionButton: IconButton(
          onPressed: focusNode.requestFocus,
          icon: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```
Like this.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 3 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart:1256]: Unfortunately, there is no better place to assert, and useful debugging messages cannot be provided here.

**Comment by yiiim** [comment]
May also solve #135407.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart:1256]: Should the SliverMainAxisGroup assert its children have a finite extent if there are more children expected to follow in the group? That seems a better place to assert from. The issue would be coming from the group, not the whole viewport, which would probably be harder to debug.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart]: Thanks! Yes, this would be a case where I would expect the SliverMainAxisGroup to assert because the infinite sliver does not allow the following sliver in the group to be seen. It is an issue in the group rather than the viewport.

**Review by Piinks — COMMENTED** [review]
> May also solve https://github.com/flutter/flutter/issues/135407.

Can you verify if it does? If it does, we should add a test here that calls the method.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart]: Do you mean to assert in the `childScrollOffset` method of `SliverMainAxisGroup`? `childScrollOffset` returning Infinite should be the correct behavior. As I mentioned before, this is not just a problem with `SliverMainAxisGroup`. In the code above, crashes will occur even if we do not use `SliverMainAxisGroup` and put the sliver directly in the `CustomScrollView`. I will remove the assertion, it introduces some complex issues that may not be within the scope of this PR.

**Comment by yiiim** [comment]
I have verified that it can fix #135407 and added tests for it.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 1 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart]: I have submitted a new issue for it. #143047.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart]: > Do you mean to assert in the childScrollOffset method of SliverMainAxisGroup?

No, probably in RenderSliverMainAxisGroup.performLayout. It is not valid for a child of the group to have an infinite extent if there is another child following behind it. You would never be able to scroll to that following child.

Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart]: Thanks! If the assertion is in `RenderSliverMainAxisGroup.performLayout`, then does `RenderViewportBase.layoutChildSequence` also need an assertion? It might not be appropriate to do this in this PR. Also, since English is not my native language, I might not be very good at providing debug messages. Could you please do this?

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart]: > Could you please do this?

Do you mean you would like to abandon this PR?

I can help with the error message from here on Github if you would like to add the assertion to RenderSliverMainAxisGroup.performLayout. :)

I don't think we should add the assertion to the viewport, since this issue is specific to the SliverMainAxisGroup. That is the issue we are trying to fix. If we have a case that supports adding it in the viewport, we should file a separate bug and PR so we can understand what that scenario is.

Comment (yiiim) [reply packages/flutter/lib/src/rendering/viewport.dart]: I'm very sorry, my translation may have caused some misunderstandings. I've added an assertion, please continue with the review.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/viewport.dart]: No apologies needed. Thank you for continuing to work on this! :)

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 4]
```diff
@@ -257,6 +281,15 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
       offset += childLayoutGeometry.scrollExtent;
       maxPaintExtent += child.geometry!.maxPaintExtent;
       child = childAfter(child);
+      assert(() {
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_group.dart:284]: This is excellent!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
