### PR TITLE
Tell image listeners if they are being called synchronously by the Im…

### LINKED ISSUE #4937: Exception in Image Resource Service
Easy reproduce is to run my app then switch to a different app and then back.  Upon switching back I get this exception 100% of the time.

```
14:35:29.920: I/flutter : ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
14:35:29.923: I/flutter : The following assertion was thrown by a synchronously-called image listener:
14:35:29.926: I/flutter : 'package:flutter/src/rendering/object.dart': Failed assertion: line 1725: 'owner == null ||
14:35:29.928: I/flutter : !owner.debugDoingPaint' is not true.
14:35:29.933: I/flutter : When the exception was thrown, this was the stack:
14:35:29.953: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
14:35:29.956: I/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
14:35:29.959: I/flutter : #2      RenderObject.markNeedsPaint (package:flutter/src/rendering/object.dart:1725)
14:35:29.962: I/flutter : #3      _BoxDecorationPainter._imageListener (package:flutter/src/painting/box_painter.dart:1426)
14:35:29.965: I/flutter : #4      ImageStreamCompleter.addListener (package:flutter/src/services/image_stream.dart:161)
14:35:29.968: I/flutter : #5      ImageStream.addListener (package:flutter/src/services/image_stream.dart:96)
14:35:29.970: I/flutter : #6      _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_painter.dart:1405)
14:35:29.972: I/flutter : #7      _BoxDecorationPainter.paint (package:flutter/src/painting/box_painter.dart:1445)
14:35:29.975: I/flutter : #8      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1176)
14:35:29.977: I/flutter : #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1806)
14:35:29.980: I/flutter : #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:101)
14:35:29.983: I/flutter : #11     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:1434)
14:35:29.985: I/flutter : #12     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:407)
14:35:29.988: I/flutter : #13     RenderStack.paint (package:flutter/src/rendering/stack.dart:415)
14:35:29.990: I/flutter : #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1806)
14:35:29.993: I/flutter : #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:101)
14:35:29.996: I/flutter : #16     <redacted>.paint (<redacted>:30)
14:35:29.999: I/flutter : #17     <redacted>.paint.<anonymous closure> (<redacted>:366)
```

### PR DESCRIPTION
**Pull request by jason-simmons**
…ageStream

Image listeners installed in paint handlers need to know whether the listener
is being called during the paint.

Fixes https://github.com/flutter/flutter/issues/4937

### CODE REVIEW

**Comment by jason-simmons** [comment]
@Hixie

**Comment by abarth** [comment]
@Hixie

File: packages/flutter/lib/src/painting/box_painter.dart [hunk 1]
```diff
@@ -1421,12 +1421,14 @@ class _BoxDecorationPainter extends BoxPainter {
...
 
-  void _imageListener(ImageInfo value) {
+  void _imageListener(ImageInfo value, bool synchronousCall) {
     if (_image == value)
       return;
     _image = value;
-    assert(onChanged != null);
-    onChanged();
+    if (!synchronousCall) {
+      assert(onChanged != null);
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/box_painter.dart]: i'd put the assert outside the if statement. it's an invariant that should always be true.

File: packages/flutter/lib/src/services/image_stream.dart [hunk 2]
```diff
@@ -47,7 +47,7 @@ class ImageInfo {
 /// Signature for callbacks reporting that an image is available.
 ///
 /// Used by [ImageStream].
```
Comment (Hixie) [inline packages/flutter/lib/src/services/image_stream.dart]: add a comment regarding synchronousCall to the docs.

File: packages/flutter/lib/src/services/image_stream.dart [hunk 3]
```diff
@@ -154,11 +154,14 @@ class ImageStreamCompleter {
   /// Adds a listener callback that is called whenever a concrete [ImageInfo]
   /// object is available. If a concrete image is already available, this object
   /// will call the listener synchronously.
+  /// The listener will be passed a flag indicating whether a synchronous call
```
Comment (Hixie) [inline packages/flutter/lib/src/services/image_stream.dart]: add a blank line above the new paragraph so that it does an actual paragraph.

also, super trivial nit: only one space after periods in dartdocs.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
This is great. Thanks for fixing this.

**Comment by Hixie** [comment]
Can you add a test to make sure that the original bug is fixed? (#4937)

File: packages/flutter/lib/src/painting/box_painter.dart (hunk 1 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/painting/box_painter.dart]: done

File: packages/flutter/lib/src/services/image_stream.dart (hunk 2 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/services/image_stream.dart]: done

File: packages/flutter/lib/src/services/image_stream.dart (hunk 3 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/services/image_stream.dart]: done

**Comment by jason-simmons** [comment]
Added a test.  PTAL.
