### PR TITLE
Fix ListWheelScrollView gestures and paint coordinates in tests

### LINKED ISSUE #38803: ListWheelScrollView children do not respond on gesture (onTap) events
## Steps to Reproduce

Hi! Here is my widget that uses `ListWheelScrollView` with `FixedExtentScrollController`:

```dart
import 'package:flutter/material.dart';

class LetterWheel extends StatefulWidget {
  const LetterWheel({Key key}) : super(key: key);

  @override
  _LetterWheelState createState() => _LetterWheelState();
}

class _LetterWheelState extends State<LetterWheel> {
  FixedExtentScrollController scrollController;

  @override
  void initState() {
    scrollController = FixedExtentScrollController();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListWheelScrollView(
      controller: scrollController,
      physics: const FixedExtentScrollPhysics(),
      itemExtent: 110,
      children: ['A', 'B', 'C', 'D', 'E', 'F', 'G']
          .map(
            (letter) => Container(
              margin: const EdgeInsets.all(10),
              height: 90,
              color: Colors.yellow,
              child: GestureDetector(
                onTap: () => print('Letter "$letter" is pressed.'),
                child: Center(
                  child: Text(
                    letter,
                    style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
            ),
          )
          .toList(),
    );
  }
}
```

**Expected result:** When the list item is tapped the message is printed to the console.

**Actual result:** When the list item is tapped nothing happens.

Here is my `flutter doctor -v` output:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-UA)
    • Flutter version 1.7.8+hotfix.3 at /Users/mkofan/Software/flutter
    • Framework revision b712a172f9 (6 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/mkofan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```

### LINKED ISSUE #121343: [Tests] ListWheelScrollView tester.getCenter returns incorrect children coordiantes
## Steps to Reproduce

Noticed this while I was writing a test to https://github.com/flutter/flutter/issues/38803 in my PR https://github.com/flutter/flutter/pull/121342

1. Execute `flutter test` on the code sample

**Expected results:** Test passes

**Actual results:** Test fails

<details>
<summary>Error output</summary>

```

Warning: A call to tap() with finder "exactly one widget with text "0" (ignoring offstage widgets): Text("0", dependencies: [MediaQuery])" derived an Offset (Offset(7.0, 300.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderParagraph#955f5 relayoutBoundary=up4
The hit test result at that offset is: HitTestResult(RenderPointerListener#b4b34@Offset(7.0, 300.0), RenderSemanticsGestureHandler#dbbd4@Offset(7.0, 300.0), RenderPointerListener#de626@Offset(7.0, 300.0), _RenderScrollSemantics#00b39@Offset(7.0, 300.0), RenderRepaintBoundary#83856@Offset(7.0, 300.0), RenderCustomPaint#e79c5@Offset(7.0, 300.0), RenderRepaintBoundary#0fa46@Offset(7.0, 300.0), HitTestEntry<HitTestTarget>#6e126(RenderView#00100), HitTestEntry<HitTestTarget>#09be3(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1290:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1175:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:18)
#3      main.<anonymous closure> (file:///Users/nt4f04und/dev/prj/app/test/widget_test.dart:27:12)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Guarded function conflict.
You must use "await" with all Future-returning test APIs.
The guarded method "tapAt" from class WidgetController was called from
file:///Users/nt4f04und/dev/prj/app/test/widget_test.dart on line 27.
Then, the "expect" function was called from
file:///Users/nt4f04und/dev/prj/app/test/widget_test.dart on line 28.
The first method (WidgetController.tapAt) had not yet finished executing at the time that the second
function (expect) was called. Since both are guarded, and the second was not a nested call inside
the first, the first must complete its execution before the second can be called. Typically, this is
achieved by putting an "await" statement in front of the call to the first.
If you are confident that all test APIs are being called using "await", and this expect() call is
not being called at the top level but is itself being called from some sort of callback registered
before the tapAt method was called, then consider using expectSync() instead.

When the first method (WidgetController.tapAt) was called, this was the stack:
#0      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:54)
#1      WidgetController.tapAt (package:flutter_test/src/controller.dart:509:27)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:12)
#3      main.<anonymous closure> (file:///Users/nt4f04und/dev/prj/app/test/widget_test.dart:27:12)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

When the exception was thrown, this was the stack:
#0      TestAsyncUtils.guardSync (package:flutter_test/src/test_async_utils.dart:273:5)
#1      expect (package:flutter_test/src/widget_tester.dart:458:18)
#2      main.<anonymous closure> (file:///Users/nt4f04und/dev/prj/app/test/widget_test.dart:28:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  ListWheelScrollView allows taps for on its children
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: ListWheelScrollView allows taps for on its children

✖ ListWheelScrollView allows taps for on its children
Exited (1)

```

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('ListWheelScrollView allows taps for on its children', (WidgetTester tester) async {
    final List<int> children = List<int>.generate(100, (int index) => index);
    final List<int> tappedChildren = <int>[];

    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: ListWheelScrollView(
          itemExtent: 100,
          children: children
              .map((int index) => GestureDetector(
                    key: ValueKey<int>(index),
                    onTap: () {
                      tappedChildren.add(index);
                    },
                    child: Text(index.toString()),
                  ))
              .toList(),
        ),
      ),
    );

    tester.tap(find.text(children.first.toString()));
    expect(tappedChildren, [children.first]);
  });
}
```

</details>

As we can see from the error, it finds the widget, but apparently the `tester.getCenter` function, which is used inside the widget returns incorrect location of the widget, seemengly without accounting for the transform applied by the scroll view.

It doesn't prevent from hit testing, taps and other gesture to be working correctly both in tests and in real enviroment (when user performs them), but it makes it difficult to write consitent tests for gestures on children of ListWheelScrollView.

<details>
  <summary>Logs</summary>

```
[!] Flutter (Channel unknown, 3.8.0-15.0.pre.26, on macOS 12.0.1 21A559 darwin-x64, locale ru-RU)
    ! Flutter version 3.8.0-15.0.pre.26 on channel unknown at /Users/nt4f04und/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 19b2aa14c0 (3 hours ago), 2023-02-23 09:03:39 -0500
    • Engine revision c87028288a
    • Dart version 3.0.0 (build 3.0.0-266.0.dev)
    • DevTools version 2.22.1
    • Pub download mirror https://pub.dartlang.org
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/nt4f04und/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)             • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (3rd generation) (mobile) • D4DF8A02-4DAA-40CF-9774-AF505CB3520B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by nt4f04uNd**
Fixes https://github.com/flutter/flutter/issues/38803
Fixes https://github.com/flutter/flutter/issues/121343

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 1]
```diff
@@ -55,6 +56,12 @@ class ListWheelParentData extends ContainerBoxParentData<RenderBox> {
   ///
   /// This must be maintained by the [ListWheelChildManager].
   int? index;
+
+  /// Transform applied to this child during painting.
+  ///
+  /// Can be used to find the local bounds of this child in the viewport,
+  /// and then use it, for example, in hit testing.
+  Matrix4? transform;
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:64]: For the docs, when would this be null?

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 2]
```diff
@@ -1031,7 +1046,35 @@ class RenderListWheelViewport
...
+  bool hitTestChildren(BoxHitTestResult result, { required Offset position }) {
+    RenderBox? child = lastChild;
+    while (child != null) {
+      final ListWheelParentData childParentData = child.parentData! as ListWheelParentData;
+      final Matrix4? transform = childParentData.transform;
+      final bool isHit = result.addWithPaintTransform(
+        transform: transform,
+        position: position,
+        hitTest: (BoxHitTestResult result, Offset transformed) {
+          assert(() {
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:1058]: Can you add error messages for the different cases in this assertion?

**Review by Piinks — COMMENTED** [review]
Wow! This is awesome, thank you for fixing such a highly requested feature!

**Comment by goderbauer** [comment]
(triage) @nt4f04uNd Do you still have plans to follow up on the feedback given above?

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart (hunk 1 above)
Comment (nt4f04uNd) [reply packages/flutter/lib/src/rendering/list_wheel_viewport.dart:69]: From what it seems, never. Added docs and assertions to ensure that.

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart (hunk 2 above)
Comment (nt4f04uNd) [reply packages/flutter/lib/src/rendering/list_wheel_viewport.dart:1085]: Added

**Comment by nt4f04uNd** [comment]
Updated. I'm sorry this took a while.

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 3]
```diff
@@ -592,14 +592,26 @@ void main() {
       );
     });
 
-    testWidgets('width of wheel in background does not increase at large widths', (WidgetTester tester) async {
+    testWidgets('wheel does not bend outwards', (WidgetTester tester) async {
```
Comment (nt4f04uNd) [inline packages/flutter/test/cupertino/date_picker_test.dart:595]: This test also didn't work properly because of the bug https://github.com/flutter/flutter/issues/121343

Values were:
1
decemberX = 250
octoberX = 250

2
decemberX = 218.5
octoberX = 218.5

So the distance in both cases was zero

In actuality these values were

262.6779112246874
250.75842555233146
distance 11.919485672355961

232.8608197943362
219.35910151060554
distance = 13.501718283730668

File: packages/flutter/lib/src/rendering/list_wheel_viewport.dart [hunk 4]
```diff
@@ -1037,9 +1037,9 @@ class RenderListWheelViewport
   static bool _debugAssertValidPaintTransform(ListWheelParentData parentData) {
     if (parentData.transform == null) {
       throw FlutterError(
-        'Children paint transform happened to be null. \n'
+        'Child paint transform happened to be null. \n'
         '$RenderListWheelViewport normally paints all of the children it has laid out. \n'
-        'Did you forget to update the $ListWheelParentData.transform during the paint() call?. \n'
+        'Did you forget to update the $ListWheelParentData.transform during the paint() call? \n'
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/list_wheel_viewport.dart:1042]: At first I thought, what an interesting error message, but TIL we have a couple of error messages like this. Nice!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thank you!
