### PR TITLE
Dart registrant location

### LINKED ISSUE #107845: Regression in hotReloadDevFSSyncMilliseconds
On the change here https://github.com/flutter/flutter/pull/107617, SkiaPerf is reporting a regression in hotReloadDevFSSyncMilliseconds: https://flutter-flutter-perf.skia.org/e/?begin=1657909086&end=1657930327&keys=Xcafc8d4bc6b7c42aa4e266575cbf4916&num_commits=50&request_type=1&xbaroffset=29895

@chingjun @christopherfujino

### PR DESCRIPTION
**Pull request by chingjun**
This relands https://github.com/flutter/flutter/pull/107617, with additional fix that fixes https://github.com/flutter/flutter/issues/107845.

The fix is placed in a separate commit in this PR for easier review.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/compile.dart [hunk 1]
```diff
@@ -276,6 +276,13 @@ class KernelCompiler {
         ? buildDir?.parent.childFile('dart_plugin_registrant.dart')
         : null;
 
+    String? dartPluginRegistrantUri;
+    if (dartPluginRegistrant != null && dartPluginRegistrant.existsSync()) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/compile.dart:280]: What does it mean if `dartPluginRegistrant != null` but it doesn't exist?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/compile.dart:280]: ahh, thanks

**Review by christopherfujino — APPROVED** [review]
LGTM
