### PR TITLE
Place the transform and its children within the RenderFlow's opacity layer

### LINKED ISSUE #15037: Opacity in FlowPaintingContext has a binary behaviour, rather than a range
## Steps to Reproduce

Create a Flow layout and corresponding FlowDelegate. Implement the paintChildren method:

```
  @override
  void paintChildren(FlowPaintingContext context) {
      context.paintChild(i,
          transform:  new Matrix4(
              1.0, 0.0, 0.0, 0.0,
              0.0, 1.0, 0.0, 0.0,
              0.0, 0.0, 1.0, 0.0,
              0.0, 0.0, 0.0, 1.0),
          opacity: 1.0
      );
}
```
Vary the opacity. All non-zero opacity values give full opacity as if opacity is set to 1.0. A zero value gives full transparency.

## Flutter Doctor

√] Flutter (Channel dev, v0.1.6, on Microsoft Windows [Version 10.0.15063], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2017.2)

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/15037

### CODE REVIEW

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
Oh wow, that's a subtle bug... I wonder what we can do to systematically avoid this kind of thing in the future.

**Comment by Hixie** [comment]
Test?

**Comment by Hixie** [comment]
LGTM but needs a test.

**Comment by jason-simmons** [comment]
Added a test - PTAL

File: packages/flutter/test/widgets/flow_test.dart [hunk 1]
```diff
@@ -28,6 +29,22 @@ class TestFlowDelegate extends FlowDelegate {
...
+
+  @override
+  void paintChildren(FlowPaintingContext context) {
+    for (int i = 0; i < context.childCount; ++i) {
+      context.paintChild(i, opacity: opacity);
+    }
+  }
+
+  @override
+  bool shouldRepaint(TestFlowDelegate oldDelegate) => true;
```
Comment (Hixie) [inline packages/flutter/test/widgets/flow_test.dart]: technically (just in case anyone copies and pastes this code, it doesn't matter for your purposes) this should be `opacity != oldDelegate.opacity`.

File: packages/flutter/test/widgets/flow_test.dart [hunk 2]
```diff
@@ -82,4 +99,23 @@ void main() {
...
+      )
+    );
+    ContainerLayer layer = RendererBinding.instance.renderView.debugLayer;
+    while (layer != null && !(layer is OpacityLayer))
+      layer = layer.firstChild;
+    expect(layer, const isInstanceOf<OpacityLayer>());
+    final OpacityLayer opacityLayer = layer;
+    expect(opacityLayer.alpha, equals(opacity * 255));
+    expect(layer.firstChild, const isInstanceOf<TransformLayer>());
+  });
```
Comment (Hixie) [inline packages/flutter/test/widgets/flow_test.dart]: looks good. for completeness' sake, let's also have the opposite test (when opacity == 1.0), just to be sure.

(I assume this test fails without your fix?)

**Comment by Hixie** [comment]
LGTM, but travis is angry.

File: packages/flutter/test/widgets/flow_test.dart (hunk 1 above)
Comment (jason-simmons) [reply packages/flutter/test/widgets/flow_test.dart]: done

File: packages/flutter/test/widgets/flow_test.dart (hunk 2 above)
Comment (jason-simmons) [reply packages/flutter/test/widgets/flow_test.dart]: The code works the same for all opacity values.  The bug was making the layers affected by opacity siblings of the opacity layer, when they should have been children of the opacity layer.

The malformed tree wasn't noticeable when opacity is 1.0 because the opacity layer would not have affected rendering.
