### PR TITLE
Reland "Fix Slider semantics node size" with some changes 

### LINKED ISSUE #114225: `Slider` and `RangeSlider` thumb accessibility issues
### Description
#### 1. The entire `Slider` is focused instead of just the thumb. 

The focus window should only follow the thumb while keeping the ability to tap anywhere on the slider to change value.
(this especially becomes problematic with `RangeSlider`)

| Flutter | Android |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/198578617-56b85c4d-4f43-4eed-9c80-0d9b8f7ccbd5.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198578513-f64acb71-8c5b-482a-a866-857d68d81084.jpg" /> |




#### 2. `RangeSider` focus window is divided in half despite range thumb locations instead of just the range thumbs.

1. Focus window takes half the size regardless of the thumb location
2. If both range thumbs are located on one side of the slider, the focus window is still shown on the otherwise side, in an empty slider area.
3. Focus windows should be on the range thumbs





| Flutter | Android |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/198580896-39585afc-d587-4488-8549-b250d3266522.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198580902-fa0442c7-8b00-495e-b4d5-35c1679b6948.jpg" /> |
| <img src="https://user-images.githubusercontent.com/48603081/198580960-c67da866-3fef-42a2-9263-8bb9149d70a2.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198580968-b4f1dc50-4a43-44e5-b0a7-55322d81a34e.jpg" /> |

### PR DESCRIPTION
**Pull request by hannah-hyj**
This is a reland of  a old PR https://github.com/flutter/flutter/pull/115285 with some changes: 
1. the node has onFocusAction 
2. update tests to reflect the semantics tree changes.  
3. the `semantics` and `paint()` reuse the _calcThumbCenter function. in the formly reverted PR https://github.com/flutter/flutter/pull/115285 the semantics only get the value of the thumbcenter after it's updated in paint() , I think it's what caused the g3 test failures in g3 and caused the revert.  

The semantics tree changes was caused because the semantics node was higher than the overlay before, and after the PR, the semantics node is formed as a leaf node and not merged with the overlay node, the extra overlay node won't change user experience but it will change some test result, 

fixes https://github.com/flutter/flutter/issues/114225

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_test/test/controller_test.dart [hunk 1]
```diff
@@ -1250,7 +1250,7 @@ void main() {
         await tester.pumpAndSettle();
 
         expect(invoked, isTrue);
-        expect(tester.semantics.find(find.byType(Slider)).value, equals(expected));
+        expect(sliderFinder.evaluate().single.value, equals(expected));
```
[the remark this answers is not in the document]
Comment (hannah-hyj) [reply packages/flutter_test/test/controller_test.dart]: bad bot,  sliderFinder.evaluate().single returns a semantics node not a element

File: packages/flutter/lib/src/material/slider.dart [hunk 2]
```diff
@@ -1906,26 +1899,78 @@ class _RenderSlider extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  }
+
+  @override
+  void assembleSemanticsNode(
+    SemanticsNode node,
+    SemanticsConfiguration config,
+    Iterable<SemanticsNode> children,
+  ) {
+    node.rect = Rect.fromCenter(
+      center: _semanticThumbCenter,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/slider.dart:1940]: We will also need to make sure the thumb's render object itself is big enough, not just the semantics node.

Comment (hannah-hyj) [reply packages/flutter/lib/src/material/slider.dart:1940]: Do you mean we need to make the thumb size 48*48? 

I don't think that's necessary,  because in non-a11y mode, 
the whole slider is interactive and you can start dragging the thumb even if you didn't clicked on the thumb. so the interactive is definitely larger than 48*48

**Review by chunhtai — APPROVED** [review]
LGTM
