### PR TITLE
Fix Chip delete button semantic bounds

### LINKED ISSUE #94098: Chip delete button tap target does not meet platform recommended tap target size
Reopening #42455 `Chip delete button tap target is too small.` 

## Steps to Reproduce

1. Add `androidTapTargetGuideline` test case to `packages/flutter/test/material/chip_test.dart`. See code below.
    ```dart
      testWidgets('delete button tap target complies with minimum tap target guideline', (WidgetTester tester) async {
        final SemanticsHandle handle = tester.ensureSemantics();
        final UniqueKey deleteKey = UniqueKey();
        await tester.pumpWidget(
          _wrapForChip(
            child: Column(
              children: <Widget>[
                Chip(
                  label: const Text('Label'),
                  deleteIcon: Icon(Icons.delete, key: deleteKey),
                  onDeleted: () { },
                ),
              ],
            ),
          ),
        );

        await expectLater(tester, meetsGuideline(androidTapTargetGuideline));

        handle.dispose();
      });
    ```
2.  Execute `cd packages/flutter` and `flutter test flutter/test/material/chip_test.dart` 

**Expected results:** 
- All tests pass

**Actual results:** 
- `delete button tap target complies with minimum tap target guideline [E]` fails with 
    ```
    Expected: Tappable objects should be at least Size(48.0, 48.0)
    Actual: <Instance of 'WidgetTester'>
    Which: SemanticsNode#5(Rect.fromLTRB(90.0, 12.0, 114.0, 36.0), actions: [tap], flags: [isButton,
  isFocusable], label: "Delete", textDirection: ltr): expected tap target size of at least Size(48.0,
  48.0), but found Size(24.0, 24.0)
            See also: https://support.google.com/accessibility/android/answer/7101858?hl=en
    ```

<details><summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel unknown, 2.6.0-12.0.pre.805, on Debian GNU/Linux rodete 5.10.46-5rodete1-amd64, locale en_US.utf8)
    • Flutter version 2.6.0-12.0.pre.805 at /usr/local/google/home/abalov/flutter
    • Upstream repository unknown
    • Framework revision aee9ade8e3 (60 minutes ago), 2021-11-23 04:03:03 -0500
    • Engine revision f4cb61cefc
    • Dart version 2.16.0 (build 2.16.0-36.0.dev)
    • DevTools version 2.8.0

```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes Chip's delete icon semantic tap target.
Chip implementation extends the hit area of the delete icon but it did not expand the semantic bounds.

### Before

image

### After

image

## Related Issue

Fixes [Chip delete button tap target does not meet platform recommended tap target size](https://github.com/flutter/flutter/issues/94098)

## Tests

Adds 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/material/chip.dart [hunk 1]
```diff
@@ -2425,6 +2424,31 @@ bool _hitIsOnDeleteIcon({
...
+    super.describeSemanticsConfiguration(config);
+    config.isSemanticBoundary = true;
+    config.isButton = true;
+  }
+
+  @override
+  Rect get semanticBounds => Rect.fromCenter(
+    center: paintBounds.center,
+    width: kMinInteractiveDimension,
+    height: kMinInteractiveDimension,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/chip.dart:2448]: It is not always this though, based on the MaterialTapTargetSize and VisualDensity, it could be a different rect correct?

File: packages/flutter/lib/src/material/chip.dart [hunk 2]
```diff
@@ -2425,6 +2424,31 @@ bool _hitIsOnDeleteIcon({
...
+  void describeSemanticsConfiguration(SemanticsConfiguration config) {
+    super.describeSemanticsConfiguration(config);
+    config.isSemanticBoundary = true;
+    config.isButton = true;
+  }
+
+  @override
+  Rect get semanticBounds => Rect.fromCenter(
+    center: paintBounds.center,
+    width: kMinInteractiveDimension,
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/chip.dart:2447]: Good point, thanks. :pray: 
Do you mean math.max instead of math.min? (using the paint size when it is larger than kMinInteractiveDimension).

File: packages/flutter/lib/src/material/chip.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/chip.dart]: I hesitated on this because it is not clear from the Material spec that the tap target size should change based on visual density.
But you're right: it is preferable to follow what is done in most of the Flutter Material widget.

I updated he PR, using the same logic than several Flutter widgets (radio, checkbox). Which means tap target size defaults to:
- 48x48 on mobile
- 32x32 on desktop

For reference, see https://github.com/flutter/flutter/blob/c02d22d8ad39cdf4e0a16750784e8d475c9f038e/packages/flutter/lib/src/material/checkbox.dart#L519-L529

File: packages/flutter/lib/src/material/chip.dart [hunk 3]
```diff
@@ -1290,9 +1290,17 @@ class _RawChipState extends State<RawChip> with TickerProviderStateMixin<RawChip
         chipTheme.iconTheme?.size ??
         theme.chipTheme.iconTheme?.size ??
         _ChipDefaultsM3(context, widget.isEnabled).iconTheme!.size!;
-    return Semantics(
-      container: true,
-      button: true,
+
```
Comment (Piinks) [inline packages/flutter/lib/src/material/chip.dart:1293]: Just after we actually call _buildDeleteIcon, some similar logic is used. we should ensure the semantic size is consistent, since it is also used for custom hit testing. This is why the hit test area is ok with the right tap target size and visual density, but the semantic bounds did not reflect that. 
The constraints that are similarly computed are down near the use of _ChipRedirectingHitDetectionWidget. Maybe we can consolidate the similar logic to compute before we call _buildDeleteIcon, and just pass the size to the method?

File: packages/flutter/test/material/chip_test.dart [hunk 4]
```diff
@@ -6167,6 +6167,96 @@ void main() {
       SystemMouseCursors.forbidden,
     );
   });
+
```
Comment (Piinks) [inline packages/flutter/test/material/chip_test.dart:6170]: To ensure the custom hit test and the semantic bounds match up and we haven't regressed anything, can you add a test where the delete button is larger than 48x48 - if that is possible? I am less familiar with this widget, and it is surprisingly complex. :)

File: packages/flutter/lib/src/material/chip.dart [hunk 5]
```diff
@@ -2425,6 +2433,55 @@ bool _hitIsOnDeleteIcon({
   };
 }
 
+class _DeleteButtonSemantic extends SingleChildRenderObjectWidget {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/chip.dart:2436]: nit: should probably name something like ensureMinSemanticsSize

File: packages/flutter/lib/src/material/chip.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/chip.dart]: actually nvm, there is a clause in WCAG as well
https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum
and the lower bound is also 24. we should be fine here

File: packages/flutter/test/material/chip_test.dart (hunk 4 above)
Comment (bleroux) [reply packages/flutter/test/material/chip_test.dart:6170]: I will try, but I'm not confident for the moment that we can get the hit test and semantics bounds always matching (the calculation for the hit logic area is complex. Looking at the history, It looks like Greg tried hard to get a logic that fits most of the use cases and that it was not an easy task). Let me experiment and share my findings.

> 'Delete button semantic tap target can be larger than the minimum interactive dimension' - if that is possible?

Yes, it is possible, for instance by increasing the label font size and the icon size (I did it in one of the test I added in the second commit for this PR). I will also try to see the effect of increasing text scaling.

File: packages/flutter/lib/src/material/chip.dart (hunk 3 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/chip.dart:1293]: I looked more closely at the current hit area logic and at the M3 Chip specification (this is the first time I work on the Chip widget :sweat_smile: ).

From the specification (see https://m3.material.io/components/chips/specs#1dcff1cb-22f5-41da-809e-6c85b467cff1):

image

And in the table below the diagram:

image


From the current Chip implementation:
- the default height of the hit target area is correct: 48dp on mobile (the visual height of the Chip is 32 which is compliant and the total height is expanded to 48 due to _ChipRedirectingHitDetectionWidget).
- the default width of the hit target area is not correct: 36dp on mobile. It seems the motivation for that was to avoid that the tap area of the delete icon overflows over the label area. 

If we don't a fix where the hit target area and the semantic area are not exactly the same (this PR), it means that the current Chip implementation should be fixed by:
- extending the default hit area to overflows over the label
- extending the default hit area to overflows out of the Chip right border. This seems to be expected from the M3 spec because the center of the delete icon is at 17 pixels from the Chip right border (iconWidth / 2 + iconRightPadding = 18/2 + 8). So the hit area should overflows by 7 pixels outside of the Chip border to comply with the 48x48 tap area.

I can work on this. I expect the second change (extending the hit area outside the Chip border) to break several existing tests and Google tests (as that the default chip width on mobile will be larger than now).

Comment (Piinks) [reply packages/flutter/lib/src/material/chip.dart:1293]: Ah ok! Thank you for explaining and digging in to this!

**Review by Piinks — APPROVED** [review]
LGTM with the nit from @chunhtai regarding the name. Thank you!

File: packages/flutter/lib/src/material/chip.dart (hunk 5 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/chip.dart:2436]: _EnsureMinSemanticsSize*

Comment (Piinks) [reply packages/flutter/lib/src/material/chip.dart:2436]: Maybe we should consider (separately) if this would be a useful wrapper widget in the core framework.

Comment (bleroux) [reply packages/flutter/lib/src/material/chip.dart]: > Maybe we should consider (separately) if this would be a useful wrapper widget in the core framework.

Interesting discussion!

A wrapper widget which manages the interactive minimum size for both hit testing and Semantics (to get them correct and in sync) might be useful.
It somewhat already exists as a private class named `_InputPadding` which is duplicated in by button_style_button.dart and toggle_buttons.dart.

About `_EnsureMinSemanticSize`, I'm not sure it is something we want to promote because it does not ensure that the Semantics area bounds are in synch with the hit area bounds. It is useful in the Chip context because it would be a breaking change to modify now the hit area bounds (as it will require to add padding on the left side of every InputChip with a delete icon, and then maybe to all chpis because otherwise developers would have to compensate for this padding specifically for some chips and not for others).

**Comment by Piinks** [comment]
Updated the google test to passing, it was a screenshot of semantic bounds. :)

File: packages/flutter/lib/src/material/chip.dart [hunk 6]
```diff
@@ -2425,6 +2433,55 @@ bool _hitIsOnDeleteIcon({
...
+  _RenderEnsureMinSemanticsSize(this._semanticSize, [RenderBox? child]) : super(child);
+
+  Size get semanticSize => _semanticSize;
+  Size _semanticSize;
+  set semanticSize(Size value) {
+    if (_semanticSize == value) {
+      return;
+    }
+    _semanticSize = value;
+    markNeedsLayout();
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/chip.dart:2465]:
```suggestion
    markNeedsSemanticsUpdate();
```

**Review by chunhtai — APPROVED** [review]
LGTM, except one minor optimization

**Comment by Piinks** [comment]
Thanks @chunhtai! Committed.
