### PR TITLE
[web] Detect scrollable semantics nodes more reliably

### LINKED ISSUE #154741: [Web] - Broken TextField in Semantics mode when using ListView and Scaffold’s AppBar on mobile browsers
### Steps to reproduce

1. Run a web app with ensureSemantics enabled on a mobile device
2. Render a TextField or two in a ListView inside a Scaffold with an AppBar
3. Attempt to tap on a TextField

### Expected results

The mobile keyboard should come up and stay up

### Actual results

The mobile keyboard comes up and closes again very quickly making it impossible to enter text.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  WidgetsFlutterBinding.ensureInitialized().ensureSemantics();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.only(top: 40),
          child: SizedBox(
            width: 300,
            //The ListView can be substituted for a SingleChildScrollView with a Column and the issue still persists.
            child: ListView(
              children: [
                const TextField(
                  decoration: InputDecoration(
                    hintText: 'Prefix',
                    suffixIcon: Icon(Icons.abc),
                  ),
                ),
                const SizedBox(height: 30),
                const TextField(
                  decoration: InputDecoration(
                    hintText: 'First Name',
                    suffixIcon: Icon(Icons.abc),
                  ),
                ),
                const SizedBox(height: 30),
                const TextField(
                  decoration: InputDecoration(
                    hintText: 'Last Name',
                    suffixIcon: Icon(Icons.abc),
                  ),
                ),
                const SizedBox(height: 30),
                FilledButton(
                  onPressed: () {},
                  child: const Text('Submit'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/rona/Sites/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by mdebbar**
When a text field is inside a scrollable, and the virtual keyboard shows up, it (sometimes) makes the scrollable semantics node have a 0 extent. In that case, the scrollable node has no scroll actions attached. In the web engine, we detect that as a change of roles (from scrollable to generic) which causes a DOM mutation above the text field, so the browser shifts focus to the `<body>`.

In order to avoid this bug, this PR changes how we detect a scrollable node by checking for the [`hasImplicitScrolling`](https://api.flutter.dev/flutter/dart-ui/SemanticsFlag/hasImplicitScrolling-constant.html) flag.

Fixes https://github.com/flutter/flutter/issues/154741

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 1]
```diff
@@ -234,20 +234,16 @@ class SemanticScrollable extends SemanticRole {
...
         // We use "hidden" instead of "scroll" so that the browser does
         // not "steal" pointer events. Flutter gesture recognizers need
         // all pointer events in order to recognize gestures correctly.
-        if (semanticsObject.isVerticalScrollContainer) {
-          element.style.overflowY = 'hidden';
-        } else {
-          assert(semanticsObject.isHorizontalScrollContainer);
-          element.style.overflowX = 'hidden';
-        }
+        element.style.overflow = 'hidden';
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:246]: When gesture mode flips from browser to pointer events, this will result in `overflowY == 'scroll'` and `overflow == 'hidden'`. Is that a good state to be in?

The vice versa situation (flipping back to browser gesture mode) seems equally questionable.

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:246]: Tried in a jsfiddle, the following:
```javascript
element.style.overflow = 'hidden';
element.style.overflowY = 'scroll';
```
it results in the element having `overflowY: scroll` and `overflowX: hidden`.

But in order to avoid this whole situation, we can just always do:
```dart
element.style.removeProperty('overflow');
```
whenever the gesture mode is changed. WDYT?

File: engine/src/flutter/lib/ui/semantics.dart [hunk 2]
```diff
@@ -1051,7 +1051,7 @@ abstract class SemanticsUpdateBuilder {
   ///
   /// For scrollable nodes `scrollPosition` describes the current scroll
   /// position in logical pixel. `scrollExtentMax` and `scrollExtentMin`
-  /// describe the maximum and minimum in-rage values that `scrollPosition` can
+  /// describe the maximum and minimum in-range values that `scrollPosition` can
```
Comment (chunhtai) [inline engine/src/flutter/lib/ui/semantics.dart:1054]: lol, nice catch

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart [hunk 3]
```diff
@@ -1356,7 +1356,14 @@ class SemanticsObject {
...
 
   /// Whether this object represents a scrollable area in any direction.
-  bool get isScrollContainer => isVerticalScrollContainer || isHorizontalScrollContainer;
+  ///
+  /// When the scrollable container has no scroll extent, it won't have any scroll actions, but
+  /// it's still a scrollable container. In this case, we need to use the implicit scrolling flag
+  /// to check for scrollability.
+  bool get isScrollContainer =>
+      hasFlag(ui.SemanticsFlag.hasImplicitScrolling) ||
+      isVerticalScrollContainer ||
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:1365]: I will expect if either `isVerticalScrollContainer` or `isHorizontalScrollContainer` is true, the hasImplicitScrolling must also be true. so I think we can just check hasImplicitScrolling should be enough

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart]: Done!

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 1 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:248]: Done!

Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:248]: In that case, I think when we're setting `overflow` we should remove `overflowX/Y`?

**Review by yjbanov — APPROVED** [review]
lgtm

**Review by chunhtai — APPROVED** [review]
LGTM
