### PR TITLE
Do not dispose CupertinoSheetTransition animation on update and throw ticker error

### LINKED ISSUE #179337: CupertinoSheetTransitionState creates multiple tickers / AnimationController dispose does not free tickers.
### Steps to reproduce

When a CupertinoSheet updates (didUpdateWidget) it tries to dispose and re-create the animation. Since its using a SingleTickerProvider it fails to recreate the controller. The dispose method of an animation controller does not reset the TickerProvider. 

https://github.com/flutter/flutter/blob/14063cfd0bc16ca959698fa2017bfc146803549a/packages/flutter/lib/src/cupertino/sheet.dart#L395

Unsure which behaviour would be intended. 

I would  intuitively expect that I can re-use a ticker provider if I dispose the ticker correctly. So I would even go as far as saying the sheet implementation is sound, the ticker provider createTicker method could use a check to see if the previously created ticker was disposed.

### Expected results

The animation is disposed correctly and recreated.

### Actual results

Error occurs.

### Code sample

I frankensteined this sample code to verify disposing an animation controller does not reset the provider mixin. 

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Counter Application',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(colorSchemeSeed: Colors.blue),
      home: const CounterScreen(title: 'Counter Screen'),
    );
  }
}

class CounterScreen extends StatefulWidget {
  final String title;

  const CounterScreen({super.key, required this.title});

  @override
  State<CounterScreen> createState() => _CounterScreenState();
}

class _CounterScreenState extends State<CounterScreen> with SingleTickerProviderStateMixin {
  int _counter = 0;
  late AnimationController _animationController;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    );
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }


  /// Disposes the current [AnimationController] and creates a new one,
  /// vsynced to this [_CounterScreenState].
  void _disposeAndRecreateAnimationController() {
    _animationController.dispose(); // Dispose the existing controller
    _animationController = AnimationController(
      vsync: this, // Re-initialize with vsync to this
      duration: const Duration(milliseconds: 500),
    );
    
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    // A simple scale animation for the icon to demonstrate the controller is working
    final Animation<double> scaleAnimation = Tween<double>(begin: 1.0, end: 1.2).animate(
      CurvedAnimation(
        parent: _animationController,
        curve: Curves.easeOut,
      ),
    );

    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _disposeAndRecreateAnimationController,
              child: const Text('Reset Animation Controller'),
            ),
            const SizedBox(height: 20),
            // Display an icon that animates when _incrementCounter or _disposeAndRecreateAnimationController is called
            AnimatedBuilder(
              animation: _animationController,
              builder: (context, child) {
                return Transform.scale(
                  scale: scaleAnimation.value,
                  child: const Icon(Icons.fingerprint, size: 50, color: Colors.blue),
                );
              },
            ),
          ],
        ),
      ),
      
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
_CupertinoSheetTransitionState is a SingleTickerProviderStateMixin but multiple tickers were created.
A SingleTickerProviderStateMixin can only be used as a TickerProvider once.
If a State is used for multiple AnimationController objects, or if it is passed to other objects and those objects might use it more than one time in total, then instead of mixing in a SingleTickerProviderStateMixin, use a regular TickerProviderStateMixin.

The relevant error-causing widget was:
    LayoutBuilder LayoutBuilder:file:///Users/.../lib/src/modal/modal.dart:312:12

When the exception was thrown, this was the stack:
#0      SingleTickerProviderStateMixin.createTicker.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:201:7)
ticker_provider.dart:201
#1      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:214:6)
ticker_provider.dart:214
#2      new AnimationController (package:flutter/src/animation/animation_controller.dart:257:21)
animation_controller.dart:257
#3      _CupertinoSheetTransitionState._setupAnimation (package:flutter/src/cupertino/sheet.dart:417:30)
sheet.dart:417
#4      _CupertinoSheetTransitionState.didUpdateWidget (package:flutter/src/cupertino/sheet.dart:396:7)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.38.1, on macOS 26.2 25C5037j darwin-arm64, locale en-US) [503ms]
    • Flutter version 3.38.1 on channel stable at /Users/.../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b45fa18946 (3 weeks ago), 2025-11-12 22:09:06 -0600
    • Engine revision b5990e5ccc
    • Dart version 3.10.0
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets,
      omit-legacy-version-file, enable-lldb-debugging

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,840ms]
    • Android SDK at /Users/.../Library/Android/Sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/.../Library/Android/Sdk
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.15+0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 26.0) [1,258ms]
    • Xcode at /Applications/Xcode-26.0.0.app/Contents/Developer
    • Build 17A324
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [6ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #179337 by moving the disposal of an animation controller outside of the didUpdate method flow. It was unnecessary to rebuild this controller on update, and was originally put there to follow the pattern of the other animations. However, unlike the other animations, this one is not chained to animations from outside of the transition's place in the tree, and was throwing exceptions from the ticker mixin in some cases.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/cupertino/sheet_test.dart [hunk 1]
```diff
@@ -1905,4 +1905,38 @@ void main() {
...
+        secondaryRouteAnimation: secondaryAnimation,
+        topGap: 0.08,
+        linearTransition: false,
+        child: const SizedBox(height: 100, width: 100),
+      ),
+    );
+
+    final newAnimation = AnimationController(vsync: const TestVSync());
+
+    // Should not throw an exception.
```
Comment (navaronbracke) [inline packages/flutter/test/cupertino/sheet_test.dart:1926]: Drive by nit, we can probably assert this with `expect(tester.takeException(), isNull);`
since otherwise this would throw an `AssertionError` ?

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 2]
```diff
@@ -431,10 +436,6 @@ class _CupertinoSheetTransitionState extends State<CupertinoSheetTransition>
       reverseCurve: Curves.easeInToLinear,
       parent: widget.secondaryRouteAnimation,
     );
-    _stretchDragController = AnimationController(
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/sheet.dart:434]: should we do a _stretchDragController.reset() here?

File: packages/flutter/test/cupertino/sheet_test.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/test/cupertino/sheet_test.dart:1926]: +1

**Review by chunhtai — APPROVED** [review]
LGTM, except for minor comments

File: packages/flutter/lib/src/cupertino/sheet.dart (hunk 2 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/sheet.dart:434]: I don't think so. I don't see a need to reseting the value and casing the jump on this update flow. I'd think we would want to hold the old status and value if it's non-zero.
