### PR TITLE
Scaffold Drawer pull out area fix for notched devices

### LINKED ISSUE #14649: endDrawer is difficult to trigger when iPhone X notch is present (landscape mode)
## Steps to Reproduce

in iPhone X with an app with an endDrawer on the left side...

- turn the phone into landscape mode
- attempt to open the left drawer by swiping from the left

User has to swipe above or below the notch - can no longer just swipe left.

It seems like the swipe area to trigger the drawer needs to stick out past the notch, instead of being flush to the phone's left edge.

Are there any recommended solutions or adjustments for this yet?

### PR DESCRIPTION
**Pull request by jslavitz**
Fixes #14649.

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -375,6 +377,10 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
   }
 
   Widget _buildDrawer(BuildContext context) {
+    double dragAreaWidth = widget.alignment == DrawerAlignment.start ?
```
Comment (xster) [inline packages/flutter/lib/src/material/drawer.dart]: You need to run this through text directionality to get left or right no?

**Comment by xster** [comment]
LGTM. Make sure to deal with RTL and add a test for it.

**Comment by xster** [comment]
LGTM
