### PR TITLE
Fix SliverPadding dropping the chain on scrollOffsetCorrection propagation

### LINKED ISSUE #14141: Listview flashing when image comes into view
I am seeing an issue where the screen is flashing when I scroll an image into view.   I am seeing this on an iPhone 5s running 11.2.2 and on a Nexus 5X running 7.1.2.  

It does seem to only affect certain images, though I can't say exactly what it is about them that causes it to happen.  I have attached an image to this issue that demonstrates the issue.

Here is a video of it happening: https://www.youtube.com/watch?v=Y3KUKsrq7os

A sample image to use that causes the issue: 
image

The `main.dart` code to use to see the issue:
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new ListView(
        children: <Widget>[
          _child(),
          new Container(
            height: 500.0,
            color: Colors.red,
          ),
          new Container(
            height: 500.0,
            color: Colors.green,
          ),
          new Container(
            height: 500.0,
            color: Colors.blue,
          ),
          new Container(
            height: 500.0,
            color: Colors.yellow,
          ),
        ],
      ),
    );
  }

  Widget _child() {
    return new Padding(
      padding: const EdgeInsets.only(
        left: 12.0,
        right: 12.0,
        top: 5.0,
        bottom: 10.0,
      ),
      child: new Image.asset(
        "assets/images/pngtest0.png",
      ),
    );
  }
}
```

## Steps to Reproduce

- Create a new flutter project, add the image above to your assets/pubspec.yaml
- Use the code above in main.dart
- Scroll to bottom of the list, then scroll back to the top.
- See flash

## Logs
There was nothing logged after the project began running

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 0e903d9544 (2 days ago), 2018-01-15 09:43:01 -0500
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Nexus 5X           • 0106bcc49c8ca3eb                         • android-arm • Android 7.1.2 (API 25)
    • iPhone             • a343cf06739643813928707a674dd1ae905fa75d • ios         • iOS 11.2.2

```

### PR DESCRIPTION
**Pull request by xster**
Fixes #14141

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 1]
```diff
@@ -520,6 +520,9 @@ class SliverGeometry extends Diagnosticable {
   /// If this is non-zero after [RenderSliver.performLayout] returns, the scroll
   /// offset will be adjusted by the parent and then the entire layout of the
   /// parent will be rerun.
+  ///
+  /// If a parent does not consume this value by making layout corrections,
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver.dart]: I think you're referring to the parent (not an ancestor) as in the previous paragraph. So "the parent" instead of "a parent".

By "must be propagated up it its own" I think you mean: must be propagated up to its own.

This comment implies some things I don't understand:
- What does it mean for the parent to consume the scrollOffsetCorrection
- What does "its own [SliverGeometry]" refer to?

If this stuff wouldn't be obvious to someone reading more of the sliver docs, it would be helpful to explain things a little more here.

**Review by HansMuller — APPROVED** [review]
LGTM, just a little feedback about the scrollOffsetCorrection doc.

File: packages/flutter/lib/src/rendering/sliver.dart (hunk 1 above)
Comment (xster) [reply packages/flutter/lib/src/rendering/sliver.dart]: Reworded this section.
