### PR TITLE
Setup channels during IntegrationTest registration on iOS

### LINKED ISSUE #91668: [integration_test] Plugin not registered unless running via XCTest
So as the title says, the integration_test native plugin is not being correctly registered unless running tests via XCTest, like when running via `flutter drive`.

This unfortunately breaks use cases like automatic taking screenshots via https://github.com/mmcc007/screenshots for instance.

I've tracked the issue down to a fix in https://github.com/flutter/plugins/pull/2465.

Changing `IntegrationTestPlugin.m:registerWithRegistrar` to the code below fixes the issue and seems to make things work, but I am assuming might bring back the XCTest init issue the PR tried to fix originally.

```objective-c
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
    [[IntegrationTestPlugin instance] setupChannels:registrar.messenger];
}
```

@gaaclarke, can you take a look / any idea on what should be done here?

## Steps to Reproduce

1. `flutter drive --target=integration_test/main_test.dart --driver=test_driver/integration_test.dart`

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
      as IntegrationTestWidgetsFlutterBinding;

  testWidgets("main test", (WidgetTester tester) async {
    await binding.takeScreenshot(name);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown running a test:
flutter: MissingPluginException(No implementation found for method captureScreenshot on channel
flutter: plugins.flutter.io/integration_test)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
flutter: <asynchronous suspension>
flutter: #1      IOCallbackManager.takeScreenshot (package:integration_test/_callback_io.dart:108:9)
flutter: <asynchronous suspension>
flutter: #2      IntegrationTestWidgetsFlutterBinding.takeScreenshot (package:integration_test/integration_test.dart:180:9)
flutter: <asynchronous suspension>
flutter: #3      screenshot (file:///Users/dev/mobile/integration_test/main_test.dart:139:3)
flutter: <asynchronous suspension>
flutter: #4      main.<anonymous closure> (file:///Users/dev/mobile/integration_test/main_test.dart:26:5)
flutter: <asynchronous suspension>
flutter: #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:172:15)
flutter: <asynchronous suspension>
flutter: #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:803:5)
flutter: <asynchronous suspension>
flutter:
flutter: The test description was:
flutter:   main test
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.240, on macOS 11.4 20F71 darwin-x64, locale en-PT)
    • Flutter version 2.6.0-12.0.pre.240 at /Users/joao/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46a52d03bd (5 days ago), 2021-10-07 08:52:09 -0700
    • Engine revision e914da14f1
    • Dart version 2.15.0 (build 2.15.0-178.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 1714BBB8-050B-4C2D-B118-456B827FFC2C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 94.0.4606.71

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by jmagman**
Allow iOS integration_tests to run from `flutter drive` and not just Xcode.

From https://github.com/flutter/flutter/issues/91668#issuecomment-1454200234
> I wasn't able to get the originally reported stuck runloop from #48601 to reproduce, even when I totally reverted [flutter/plugins#2465](https://github.com/flutter/plugins/pull/2465). I also validated [flutter/plugins#2514](https://github.com/flutter/plugins/pull/2514) passes when it's reverted.
> 
> Talked to @gaaclarke and we suspect some precondition for the original bug have been resolved... somewhere. This code was moved from flutter/plugins to the SDK, making bisecting this tricky, and probably not worth it if I can't reproduce it from Xcode or the command line at all with either a static or dynamic linked integration_test. So let's try re-adding the `+registerWithRegistrar` channel setup removed in #48601.

Reverts https://github.com/flutter/plugins/pull/2465 (not a clean revert but essentially the same thing).

Fixes https://github.com/flutter/flutter/issues/91668
Closes https://github.com/flutter/flutter/pull/116539

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/integration_test/ios/Classes/IntegrationTestPlugin.h [hunk 1]
```diff
@@ -22,9 +22,7 @@ NS_ASSUME_NONNULL_BEGIN
 @property (copy, readonly) NSDictionary<NSString *, UIImage *> *capturedScreenshotsByName;
 
 /** Fetches the singleton instance of the plugin. */
-+ (IntegrationTestPlugin *)instance;
-
-- (void)setupChannels:(id<FlutterBinaryMessenger>)binaryMessenger;
++ (instancetype)instance;
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/IntegrationTestPlugin.h:25]: Made this `instancetype`, that wasn't part of the revert.

File: packages/integration_test/ios/Classes/IntegrationTestPlugin.m [hunk 2]
```diff
@@ -45,19 +45,9 @@ - (instancetype)init {
...
-- (void)setupChannels:(id<FlutterBinaryMessenger>)binaryMessenger {
-  FlutterMethodChannel *channel =
-  [FlutterMethodChannel methodChannelWithName:kIntegrationTestPluginChannel
-                              binaryMessenger:binaryMessenger];
-  [channel setMethodCallHandler:^(FlutterMethodCall *call, FlutterResult result) {
-    [self handleMethodCall:call result:result];
-  }];
+  FlutterMethodChannel *channel = [FlutterMethodChannel methodChannelWithName:kIntegrationTestPluginChannel
+                                                              binaryMessenger:registrar.messenger];
+  [registrar addMethodCallDelegate:[self instance] channel:channel];
```
Comment (pdblasi-google) [inline packages/integration_test/ios/Classes/IntegrationTestPlugin.m:50]: For future archeologists: The `addMethodCallDelegate` does the `setMethodCallHandler` logic that was originally used, so this is semantically the same as the previous `setMethodCallHandler` call.

**Review by pdblasi-google — APPROVED** [review]
LGTM!

**Comment by zubriktomas** [comment]
@pdblasi-google Hello, could you please tell me when do you expect this fix to be part of what future release?

**Comment by pdblasi-google** [comment]
@zubriktomas

From the [release process docs](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) this is already available in the `master` channel and may be in `beta` as well. I'm not personally sure when it'll be a part of a `stable` release, but it should be in either the next stable or the one after that.
