### PR TITLE
Use aria-hidden attribute for platform view accessibility on web

### LINKED ISSUE #171948: [google_maps_flutter][accessibility][web]:  GoogleMap announced by screenreader despite wrapping with `ExcludeSemantics`
### Steps to reproduce

1. Add GoogleMap under an ExcludeSemantics component.
2. Run flutter on Android, Web or iOS
3. Start TalkBack/VoiceOver
4. Move the focus on map

### Expected results

The screen reader should not be able to focus the Google Map widget.

### Actual results

Google Map can still be focused/selected by the screen reader, and it reads all the things in the maps (markers, compass, map footer, etc..)

### Code sample

<details open><summary>Code sample</summary>

```dart

ExcludeSemantics(
    child: GoogleMap(
        ...
    ),
);
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Use aria-hidden attribute for platform view accessibility on web

Before change:
https://map-1023-before.web.app/

After change:
https://map-1023-after.web.app/

Fixes #171948.

Note: When a descendant element receives focus (for example, a marker), the browser automatically overrides aria-hidden. This behavior is correct and expected for accessibility compliance.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/platform_view.dart [hunk 1]
```diff
@@ -40,9 +41,16 @@ class SemanticPlatformView extends SemanticRole {
     super.update();
 
     if (semanticsObject.isPlatformView) {
+      final int platformViewId = semanticsObject.platformViewId;
+
       if (semanticsObject.isPlatformViewIdDirty) {
-        setAttribute('aria-owns', getPlatformViewDomId(semanticsObject.platformViewId));
+        setAttribute('aria-owns', getPlatformViewDomId(platformViewId));
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/platform_view.dart:52]: Should we also remove `aria-owns` when `isHidden` is true?

**Review by mdebbar — APPROVED** [review]
Looks good to me!

**Review by chunhtai — APPROVED** [review]
LGTM
