### PR TITLE
Delay Route disposal until OverlayEntries are unmounted

### LINKED ISSUE #63984: Cupertino Back swipe gesture causing null-unsafe operations
Internal: b/164920328

We have no small repro for this unfortunately.

Two crash reports started coming in from apps that have switched to null-safe code:

```
Thread 0 main thread CRASHED_CastError: Null check operator used on a null value
at AnimationController.stop(animation_controller.dart:747)
at AnimationController._animateToInternal(animation_controller.dart:581)
at AnimationController.animateTo(animation_controller.dart:518)
at _CupertinoBackGestureController.dragEnd(route.dart:773)
at _CupertinoBackGestureDetectorState._handleDragEnd(route.dart:657)
at DragGestureRecognizer._checkEnd.<anonymous closure>(monodrag.dart:440)
at GestureRecognizer.invokeCallback(recognizer.dart:183)
at DragGestureRecognizer._checkEnd(monodrag.dart:440)
at DragGestureRecognizer.didStopTrackingLastPointer(monodrag.dart:349)
at OneSequenceGestureRecognizer.stopTrackingPointer(recognizer.dart:342)
at DragGestureRecognizer._giveUpPointer(monodrag.dart:358)
at DragGestureRecognizer.handleEvent(monodrag.dart:282)
at PointerRouter._dispatch(pointer_router.dart:77)
at PointerRouter._dispatchEventToRoutes.<anonymous closure>(pointer_router.dart:122)
at _LinkedHashMapMixin.forEach(compact_hash.dart:377)
at PointerRouter._dispatchEventToRoutes(pointer_router.dart:120)
at PointerRouter.route(pointer_router.dart:106)
at GestureBinding.handleEvent(binding.dart:219)
at GestureBinding.dispatchEvent(binding.dart:199)
at GestureBinding._handlePointerEvent(binding.dart:157)
at GestureBinding._flushPointerEventQueue(binding.dart:103)
```

and

```
Thread 0 main thread CRASHED_CastError: Null check operator used on a null value
at DragGestureRecognizer.acceptGesture(monodrag.dart:294)
at GestureArenaManager.sweep(arena.dart:157)
at GestureBinding.handleEvent(binding.dart:223)
at GestureBinding.dispatchEvent(binding.dart:199)
at GestureBinding._handlePointerEvent(binding.dart:157)
at GestureBinding._flushPointerEventQueue(binding.dart:103)
at GestureBinding._handlePointerDataPacket(binding.dart:87)
at _rootRunUnary(zone.dart:1206)
at _CustomZone.runUnary(zone.dart:1100)
at _CustomZone.runUnaryGuarded(zone.dart:1005)
at _invoke1(hooks.dart:267)
at _dispatchPointerDataPacket(hooks.dart:176)
```

It seems like gesture handlers are using certain objects beyond their useful lifecycle.

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

This PR changes the Navigator to only dispose a Route after all its OverlayEntries have been disposed.

_The following description of the problem was written by @dkwingsmt, who initially debugged the issue. Thank you!_

This fixes #63984. The issue is caused by programmatically popping a route while the back swipe is in progress (fingers held), which leads to the following series of event:

* A route is popped and disposed. During the disposal,
  * Its animation controller is disposed.
  * A PointerCancelEvent is synthesized for the active pointer.
* The disposal of the route should trigger the navigator to rebuild, removing all dependents of the controller, but this does not come until the widget tree is rebuilt in the next frame.
* Before the next frame, the cancel event is dispatched.
    * The drag gesture recognizer (which is not disposed until the next frame) receives the cancel event and starts to dispatch ending callbacks. The callback starts some animation, only to find the controller of the Route disposed, triggering assertion error.

The resources of a Route (e.g. the controller) must be held until after the widget tree of the route is disposed since widgets in the tree may hold on to resources of the Route. Therefore this PR no longer disposes the route entry synchronously from within _flushHistoryUpdates, but waits until all its overlay entries are disposed.

Some logic of _HeroFlight is also tweaked to fix a few test breakages. This is caused by a condition which skips Hero's end-flight operations when there are any on-going gestures, introduced by #58024. This was not an issue because the fromRoute.navigator had been null at that point, passing the condition unintentionally, which is exposed now that the lifecycle of fromRoute is extended. The _HeroFlight now postpones the operations until the gestures are cleared.

## Related Issues

Fixes #63984.

## Tests

I added the following tests:

* a test encoding the sequence of events described in #63984

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/routes_test.dart [hunk 1]
```diff
@@ -105,6 +105,7 @@ Future<void> runNavigatorTest(
 ) async {
   expect(host, isNotNull);
   test();
+  await tester.pump();
```
Comment (dkwingsmt) [inline packages/flutter/test/widgets/routes_test.dart:108]: Would you like to use the changes here https://github.com/flutter/flutter/pull/68202/files#diff-694c7fe05eeca16e2ac5a7051e747cf5ff00a4108a64053b934aa38b61b0e072R105 so that it's clearer when each lines are called?

File: packages/flutter/lib/src/widgets/overlay.dart [hunk 2]
```diff
@@ -51,7 +51,7 @@ import 'ticker_provider.dart';
 ///  * [OverlayState]
 ///  * [WidgetsApp]
 ///  * [MaterialApp]
-class OverlayEntry {
+class OverlayEntry extends ChangeNotifier {
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/overlay.dart:54]: Add to documentation: 
```dart
/// [OverlayEntry] is a [ChangeNotifier] that notifies when the widget built by [builder] is mounted or unmounted,
/// whose exact state can be queried by [mounted].
```

**Review by dkwingsmt — CHANGES_REQUESTED** [review]
A few suggestions

File: packages/flutter/test/widgets/routes_test.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/routes_test.dart]: Done.

File: packages/flutter/lib/src/widgets/overlay.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/overlay.dart:58]: Done.

**Comment by goderbauer** [comment]
@dkwingsmt addressed all comments and removed the Draft status from this PR. It's ready for review!

**Review by dkwingsmt — APPROVED** [review]
LGTM
