### PR TITLE
[Windows] Use ANGLE blit extension on GLES 2.0

### LINKED ISSUE #169178: Windows Flutter apps crash silently on some machines after 3.27.4
### Steps to reproduce

Create a new Flutter app:

1-
`flutter create test_app`
Build the Windows executable:

2-
`cd test_app`  

3-
`flutter build windows`

Run the generated executable on multiple Windows machines:

Machines with Flutter version 3.27.4 and below → app works normally.

Machines with Flutter 3.29.0 and above → app may crash immediately on some computers without showing a window or error.

### Expected results

The app should open and display the counter UI on all machines, as it does on version 3.27.4 and below.

### Actual results

On Flutter 3.29.4:

On some Windows machines, the app crashes silently on launch (nothing appears).

No error logs are shown.

This happens even with the default counter app generated by flutter create.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple)),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(backgroundColor: Theme.of(context).colorScheme.inversePrimary, title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text('$_counter', style: Theme.of(context).textTheme.headlineMedium),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(onPressed: _incrementCounter, tooltip: 'Increment', child: const Icon(Icons.add)),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary> Video demonstration</summary>

[[Click for watch]](https://www.loom.com/share/1044cdecfee24f8fa9d06844f2b4b432?sid=863dd35f-fac6-4b85-a532-9ee7e437434d)

</details>

### Logs

<details open><summary>Logs</summary>
I used Process Monitor (Procmon) to capture detailed logs on Windows during app launch. The logs show the differences in behavior between Flutter 3.27.4 (working) and 3.29.0+ (failing on some machines). I've attached the .PML files to help with further analysis.

# Flutter 3.27.4 (working):

[3_27_4.zip](https://github.com/user-attachments/files/20358303/3_27_4.zip)

# Flutter 3.29.3 (crashing on some machines):

[3_29_3.zip](https://github.com/user-attachments/files/20358307/3_29_3.zip)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.3, on Microsoft Windows [versÆo 10.0.26100.4061], locale pt-BR)
[✓] Windows Version (Windows 11 or higher, 24H2, 2009)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.5)
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.100.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

[3_27_4.zip](https://github.com/user-attachments/files/20358327/3_27_4.zip)
[3_29_3.zip](https://github.com/user-attachments/files/20358328/3_29_3.zip)

```

</details>

### PR DESCRIPTION
**Pull request by loic-sharma**
This updates Flutter Windows to fall back to [`glBlitFramebufferANGLE`](https://github.com/google/angle/blob/main/extensions/ANGLE_framebuffer_blit.txt) if `glBlitFramebuffer` is not available. This makes Flutter Windows work on devices where ANGLE supports only GLES 2.0.

Fixes: https://github.com/flutter/flutter/issues/169178

### Background

ANGLE only implements GLES 2.0 on some Windows 10+ machines ([1](https://github.com/flutter/flutter/issues/169178#issuecomment-2943735504), [2](https://github.com/flutter/flutter/issues/169178#issuecomment-2944096179)). 

Flutter Windows 3.27.4 and lower was using `glBlitFramebuffer` on GLES 2.0 devices, even though that requires GLES 3.0. This magically worked though, thanks to ANGLE.

However in 3.29.0, Impeller was updated to not resolve GLES 3.0 procs on GLES 2.0: https://github.com/flutter/engine/pull/56636. This caused Flutter Windows to crash on GLES 2.0 devices since it was calling `glBlitFramebuffer`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/gles/proc_table_gles.cc [hunk 1]
```diff
@@ -141,6 +141,10 @@ ProcTableGLES::ProcTableGLES(  // NOLINT(google-readability-function-size)
     DiscardFramebufferEXT.Reset();
   }
 
+  if (!description_->HasExtension("GL_ANGLE_framebuffer_blit")) {
+    BlitFramebufferANGLE.Reset();
+  }
```
Comment (loic-sharma) [inline engine/src/flutter/impeller/renderer/backend/gles/proc_table_gles.cc:146]: I considered only loading this proc if we detect ANGLE, however, the `GL_VERSION` for the affected devices are `2.0.0`, which causes `DescriptionGLES::IsANGLE` to return `false`.

**Review by jonahwilliams — APPROVED** [review]
LGTM
