### PR TITLE
Fix an issue that semantics on TextField is not updated when changing obscureText

### LINKED ISSUE #99763: [Android]Semantics on TextField is not updated when changing obscureText to false
Given a `TextField` widget, if `obscureText` is initialy to `true`, and then changed to `false`, semantics is not properly updated: TalkBack still reads "bullets" instead of the input characters.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Enter "hello" in the text field
3. Tap the "Disable obscure" button
4. Activate TalkBack
5. Select the text field

**Expected results:**
TalkBack says: "hello"

**Actual results:**
TalkBack says: "5 bullets"
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const ObscureApp());
}

class ObscureApp extends StatelessWidget {
  const ObscureApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Obscure semantics bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _obscureText = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(obscureText: _obscureText),
            ElevatedButton(
              onPressed: () async {
                setState(() {
                  _obscureText = false;
                });
              },
              child: Text('Disable obscure'),
            ),
            ElevatedButton(
              onPressed: () async {
                setState(() {
                  _obscureText = true;
                });
              },
              child: Text('Enable obscure'),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[  +42 ms] List of devices attached
           192.168.1.16:5555      device product:sunfish model:Pixel_4a device:sunfish transport_id:1
[   +6 ms] /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell getprop
[ +187 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +80 ms] Skipping pub get: version match.
[ +125 ms] Generating /Users/jeremie_yardin/Dev/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +57 ms] ro.hardware = sunfish
[        ] ro.build.characteristics = nosdcard
[  +39 ms] Initializing file store
[  +13 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/jeremie_yardin/Dev/bug/.dart_tool/package_config_subset}
[  +25 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib/main.dart on Pixel 4a in debug mode...
[   +5 ms] /Users/jeremie_yardin/fvm/versions/2.8.1/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/jeremie_yardin/fvm/versions/2.8.1/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/jeremie_yardin/fvm/versions/2.8.1/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/1w/myj5p9f16bv50h5bzvpn6q6c7klt4p/T/flutter_tools.EpRNRE/flutter_tool.DIPQtv/app.dill --packages /Users/jeremie_yardin/Dev/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +10 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/build-tools/32.0.0/aapt dump xmltree /Users/jeremie_yardin/Dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +34 ms] Exit code 0 from: /Users/jeremie_yardin/Library/Android/sdk/build-tools/32.0.0/aapt dump xmltree /Users/jeremie_yardin/Dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell -x logcat -v time -t 1
[  +21 ms] <- compile package:bug/main.dart
[  +76 ms] --------- beginning of main
           03-08 15:43:08.708 I/System.out(11958): yyy - had to retry with delay
[  +22 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb version
[  +28 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb start-server
[  +20 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from /Users/jeremie_yardin/Dev/bug/android/gradlew.
[  +78 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +11 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio2020.3","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.vendor.name":"Google","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-203.7717.56.2031.7935034","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"2020.3","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network volume.","CFBundleGetInfoString":"Android Studio 2020.3, build AI-203.7717.56.2031.7935034. Copyright JetBrains s.r.o., (c) 2000-2021","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a removable volume."}
[   +2 ms] executing: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
[  +91 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7281165, mixed mode)
[   +1 ms] executing: [/Users/jeremie_yardin/Dev/bug/android/] /Users/jeremie_yardin/Dev/bug/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=/Users/jeremie_yardin/Dev/bug/lib/main.dart -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2021 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +91 ms] executing: sysctl hw.optional.arm64
[        ] [  +16 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] [        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] [   +6 ms] executing: [/Users/jeremie_yardin/fvm/versions/2.8.1/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +15 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [        ] executing: [/Users/jeremie_yardin/fvm/versions/2.8.1/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [  +21 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] [        ] 2.8.1
[        ] [   +7 ms] executing: [/Users/jeremie_yardin/fvm/versions/2.8.1/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/jeremie_yardin/fvm/versions/2.8.1/] git ls-remote --get-url origin
[        ] [  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +58 ms] executing: [/Users/jeremie_yardin/fvm/versions/2.8.1/] git rev-parse --abbrev-ref HEAD
[        ] [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [   +5 ms] executing: sw_vers -productName
[        ] [  +12 ms] Exit code 0 from: sw_vers -productName
[        ] [        ] macOS
[        ] [        ] executing: sw_vers -productVersion
[        ] [  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] [        ] 12.2.1
[        ] [        ] executing: sw_vers -buildVersion
[        ] [  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] [        ] 21D62
[        ] [  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +86 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +39 ms] Initializing file store
[        ] [   +6 ms] Done initializing file store
[        ] [  +36 ms] Skipping target: gen_localizations
[        ] [  +10 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +503 ms] Skipping target: kernel_snapshot
[        ] [ +271 ms] Skipping target: debug_android_application
[        ] [        ] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[   +2 ms] [  +11 ms] "flutter assemble" took 1 001ms.
[        ] [ +105 ms] ensureAnalyticsSent: 101ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +62 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +195 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +105 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +96 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +71 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 3s
[        ] 32 actionable tasks: 5 executed, 27 up-to-date
[ +385 ms] Running Gradle task 'assembleDebug'... (completed in 4,6s)
[  +57 ms] calculateSha: LocalDirectory: '/Users/jeremie_yardin/Dev/bug/build/app/outputs/flutter-apk'/app.apk
[ +544 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +2 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/build-tools/32.0.0/aapt dump xmltree /Users/jeremie_yardin/Dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +14 ms] Exit code 0 from: /Users/jeremie_yardin/Library/Android/sdk/build-tools/32.0.0/aapt dump xmltree /Users/jeremie_yardin/Dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on Pixel 4a.
[        ] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell am force-stop com.example.bug
[ +130 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell pm list packages com.example.bug
[  +54 ms] package:com.example.bug
[   +1 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +54 ms] d93347c49db61e660599931cdae4d2d69c6613c6
[   +1 ms] Latest build already installed.
[        ] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell -x logcat -v time -t 1
[  +61 ms] --------- beginning of main
           03-08 15:43:15.523 W/EuiccGoogle(23052): [100] EuiccServiceImpl.onGetEuiccProfileInfoList: slotId=-1. No eUICC is active. Return null.
[   +9 ms] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[  +76 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +444 ms] Observatory URL on device: http://127.0.0.1:42441/pIM5zLh4MUg=/
[        ] executing: /Users/jeremie_yardin/Library/Android/sdk/platform-tools/adb -s 192.168.1.16:5555 forward tcp:0 tcp:42441
[  +14 ms] 59233
[        ] Forwarded host port 59233 to device port 42441 for Observatory
[   +6 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://127.0.0.1:59233/pIM5zLh4MUg=/
[ +236 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59233/pIM5zLh4MUg=/.
[ +286 ms] DDS is listening at http://127.0.0.1:59238/f0UU6pIFL-U=/.
[  +57 ms] Successfully connected to service protocol: http://127.0.0.1:59233/pIM5zLh4MUg=/
[  +77 ms] DevFS: Creating new filesystem on the device (null)
[  +37 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugQMDXBJ/bug/)
[   +1 ms] Updating assets
[  +62 ms] Syncing files to device Pixel 4a...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:bug/main.dart 5a048f7d-179e-4c0c-978c-9e7ee320cf58
[        ] <- 5a048f7d-179e-4c0c-978c-9e7ee320cf58
[  +57 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 4a... (completed in 61ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +14 ms] Connected to _flutterView/0xb40000738e062630.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Pixel 4a is available at: http://127.0.0.1:59238/f0UU6pIFL-U=/
[ +792 ms] The Flutter DevTools debugger and profiler on Pixel 4a is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:59238/f0UU6pIFL-U=/
[+2364 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F....ID 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +6 ms] W/IInputConnectionWrapper(12980): beginBatchEdit on inactive InputConnection
[        ] W/IInputConnectionWrapper(12980): getTextBeforeCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(12980): getTextAfterCursor on inactive InputConnection
[        ] W/IInputConnectionWrapper(12980): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(12980): endBatchEdit on inactive InputConnection
[  +33 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[  +24 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[+1077 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F...... 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +6 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[ +380 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F...... 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +6 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[ +233 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F...... 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +6 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[ +168 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F...... 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +8 ms] D/InsetsController(12980): show(ime(), fromIme=true)
[ +276 ms] D/InputMethodManager(12980): showSoftInput() view=io.flutter.embedding.android.FlutterView{40e91f8 VFED..... .F...... 0,0-1080,2208 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +7 ms] D/InsetsController(12980): show(ime(), fromIme=true)

```

```
Analyzing bug...                                                

   info • Prefer declaring const constructors on `@immutable` classes • lib/main.dart:24:3 • prefer_const_constructors_in_immutables
   info • Prefer const with constant constructors • lib/main.dart:52:22 • prefer_const_constructors

2 issues found. (ran in 1.8s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/jeremie_yardin/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jeremie_yardin/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/jeremie_yardin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Pixel 4a (mobile) • 192.168.1.16:5555 • android-arm64 • Android 12 (API 31)
```

</details>

### PR DESCRIPTION
**Pull request by hannah-hyj**
fixed: #99763

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Change looks good, but we need a test to make sure it does not regress.

**Comment by hangyujin** [comment]
Test added

File: packages/flutter/test/material/text_field_test.dart [hunk 1]
```diff
@@ -6086,6 +6086,45 @@ void main() {
     semantics.dispose();
   });
 
+  // Regressing test for https://github.com/flutter/flutter/issues/99763
+  testWidgets('Update textField semantics when obscureText changes', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:6090]: This test seems to pass even without the change. It may not capture the right situation?

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -11786,3 +11825,44 @@ void main() {
...
 }
+
+/// Simple test app for testing the obscure text.
+class _ObscureTextTestWidget extends StatefulWidget {
+   const _ObscureTextTestWidget({ required this.controller,
+   });
+
+  final TextEditingController controller;
+  @override
+  _ObscureTextTestWidgetState createState() =>
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:11836]: you can keep this in one line.

File: packages/flutter/test/material/text_field_test.dart [hunk 3]
```diff
@@ -11786,3 +11825,44 @@ void main() {
...
+      _ObscureTextTestWidgetState();
+}
+
+class _ObscureTextTestWidgetState extends State<_ObscureTextTestWidget> {
+
+  bool _obscureText= false;
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:11842]:
```suggestion
  bool _obscureText = false;
```

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -11786,3 +11825,44 @@ void main() {
...
+  @override
+  Widget build(BuildContext context) {
+    return MaterialApp(
+      home: Scaffold(
+        body: Builder(
+          builder: (_) {
+            return Column(
+              children: <Widget>[
+                TextField(
+                    obscureText:_obscureText,
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:11852]:
```suggestion
                    obscureText: _obscureText,
```

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -11786,3 +11825,44 @@ void main() {
     }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.macOS }));
   });
 }
+
+/// Simple test app for testing the obscure text.
+class _ObscureTextTestWidget extends StatefulWidget {
+   const _ObscureTextTestWidget({ required this.controller,
+   });
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:11832]: either the constructor to be a single line or the parameters need to be in a separate line

File: packages/flutter/test/material/text_field_test.dart [hunk 6]
```diff
@@ -11786,3 +11825,44 @@ void main() {
     }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.macOS }));
   });
 }
+
+/// Simple test app for testing the obscure text.
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart:11829]:
```suggestion
/// A Simple widget for testing the obscure text.
```

File: packages/flutter/test/material/text_field_test.dart (hunk 1 above)
Comment (hangyujin) [reply packages/flutter/test/material/text_field_test.dart:6090]: Sorry, updated test, it should capture the change now

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
not sure why the build failed, maybe try to rebase off master branch and see if it works
