### PR TITLE
[Impeller] remove overriding of sampler mode to decal.

### LINKED ISSUE #165788: [Impeller] Image with non-null color creates gaps between tiles when using ImageRepeat.repeat
### Steps to reproduce

When using Impeller (tested on both Android and iOS), the `Image` widget draws a gap between tiles when `repeat: ImageRepeat.repeat` is set and `color` has a non-null value.

### Expected results

I expect the tiles to have no gaps between them, as it is with Skia rendering

### Actual results

Impeller draws gaps between repeated tiles

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(
    Container(
      color: Colors.black,
      child: Image.network(
        'https://github.com/user-attachments/assets/944042c5-7da3-42d4-bf41-539910899708',
        repeat: ImageRepeat.repeat,
        color: Colors.green,
      ),
    )
  );
}
```

Test tile image:
Image
</details>

### Screenshots or Video

<details open>
<summary>Screenshots</summary>

`color: null`
Image

`color: Colors.green`
Image

`color: Colors.green` with Impeller disabled
Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.2 24C101 darwin-arm64, locale en-US) [323ms]
    • Flutter version 3.29.2 on channel stable at /Users/apan1000/.asdf/installs/flutter/3.29.2-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (11 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [977ms]
    • Android SDK at /Users/apan1000/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/apan1000/Library/Android/sdk
    • Java binary at: /Users/apan1000/Applications/Android Studio Meerkat 2024.3.1.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [646ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [10ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [10ms]
    • Android Studio at /Users/apan1000/Applications/Android Studio Meerkat 2024.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.98.2) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (4 available) [5.7s]
    • iPhone 16 Pro (mobile)          • 40E1924C-839D-4118-ABA4-1FDDB32A05C0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-2
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 134.0.6998.118

[✓] Network resources [220ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/165788

We can't remember why we did this.

### CODE REVIEW

File: engine/src/flutter/impeller/entity/contents/filters/blend_filter_contents.cc [hunk 1]
```diff
@@ -840,7 +820,7 @@ std::optional<Entity> BlendFilterContents::CreateFramebufferAdvancedBlend(
       VS::FrameInfo frame_info;
       FS::FragInfo frag_info;
 
-      auto src_sampler_descriptor = SamplerDescriptor{};
+      SamplerDescriptor src_sampler_descriptor = SamplerDescriptor{};
       if (renderer.GetDeviceCapabilities().SupportsDecalSamplerAddressMode()) {
         src_sampler_descriptor.width_address_mode = SamplerAddressMode::kDecal;
```
Comment (jason-simmons) [inline engine/src/flutter/impeller/entity/contents/filters/blend_filter_contents.cc:825]: Should this also be removed?

Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/filters/blend_filter_contents.cc]: Changed this to use the snapshot descriptor, unless we didn't use a snapshot then it just uses a default descriptor.

**Review by jason-simmons — APPROVED** [review]
