### PR TITLE
Fix iOS selectWordEdge doesn't account for affinity

### LINKED ISSUE #115702: Upon tapping a TextField, the cursor appears on left side of text if text is exactly one character long
## Steps to Reproduce

1. Enter **EXACTLY** one character into the TextField 
2. Press enter to unfocus the TextField 
3. Tap on the Textfield to give it focus 

**Expected results:** The cursor appears in the TextField on the right side of the text.

**Actual results:** The cursor appears in the TextField on the left side of the text. Note that if there are two or more characters, the cursor appears on the right side of the text.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({super.key, required this.title});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
          child: TextField(
        decoration: InputDecoration(
          border: OutlineInputBorder(),
          hintText: 'Enter a search term',
        ),
      )),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel master, 3.4.0-29.0.pre.55, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-29.0.pre.55 on channel master at /Users/benjaminfarquhar/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d98b0c9c7c (9 weeks ago), 2022-09-20 23:35:24 -0400
    • Engine revision 38fef0572f
    • Dart version 2.19.0 (build 2.19.0-223.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/benjaminfarquhar/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (5 available)
    • iPhone 14 (mobile)                             • AFAF79C5-E179-4196-BA64-D1B207492B8B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • iPhone 14 Pro (mobile)                         • 7C18494E-7E52-482C-B49F-31495FA29DE0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • C23FED79-28C8-4B6C-BD33-A8E6F19CF770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/26356162/202866138-a0389d3c-389f-4a15-af3e-a55430578b67.mp4

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/115702

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -2149,7 +2149,8 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
     final TextPosition position = _textPainter.getPositionForOffset(globalToLocal(_lastTapDownPosition! - _paintOffset));
     final TextRange word = _textPainter.getWordBoundary(position);
     late TextSelection newSelection;
-    if (position.offset - word.start <= 1) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:2152]: Not entirely sure why the original logic check for <= 1. I tested native iOS and it looks like you need to click at the very beginning of the word to move the caret to start, so I think the  change matches the native behavior.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. But this method doesn't handle multi-code-unit characters or bidi so I think we should probably just deprecate it. The behavior seems to be specific to ios gestures I guess it should be implemented there.

**Comment by chunhtai** [comment]
> LGTM. But this method doesn't handle multi-code-unit characters or bidi so I think we should probably just deprecate it. The behavior seems to be specific to ios gestures I guess it should be implemented there.

For multi code unit, the getPositionForOffset should return a position that respects grapheme cluster. same for biditext I think.
