### PR TITLE
Various Input and Focus fixes

### LINKED ISSUE #181: Focus.at() should give better feedback when there's two focusable widgets
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 05, 2015 at 21:18 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1494_

----

Right now Focus.at() defaults to returning true if there's no scope, which is intentional to make it easier to write trivial apps with a single focusable widget. But it means that when you add a second one, things break in unobvious ways. We should catch that case and assert with a useful message.

### LINKED ISSUE #189: Input grabs focus too aggressively
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 21:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1530_

----

It should use gestures to decide when to grab focus, probably when a Tap gesture commits (possibly before onTap, but certainly not when you might still scroll).

You can see this if you put a bunch of input fields in a list and scroll the list. Every time you scroll, you focus a new widget.

### LINKED ISSUE #236: Focus.moveTo, Focus.moveScopeTo only need one argument
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 27, 2015 at 16:00 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1824_

----

We should just get the widget (second argument) from the context (first argument).

### PR DESCRIPTION
**Pull request by Hixie**
Require a Key on Input.

Simplify the API for Focus.at() and Focus.moveTo().
Fixes #236.
This will require an e-mail to flutter-dev.

Make Input grab focus onTap not onPointerDown.
Fixes #189.

Complain when you use Focus.at() with two different GlobalKeys that
are both in the tree at the same time.
Fixes #181.

Add dartdocs for Focus.moveTo() and Focus.moveScopeTo().

### CODE REVIEW

File: packages/flutter/lib/src/material/input.dart [hunk 1]
```diff
@@ -118,7 +120,7 @@ class InputState extends ScrollableState<Input> {
       scrollOffset: scrollOffsetVector
     ));
 
-    return new Listener(
+    return new GestureDetector(
       child: new SizeObserver(
```
Comment (abarth) [inline packages/flutter/lib/src/material/input.dart]: By convention, we put the child argument last.

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/material/input.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/material/input.dart]: fixed
