### PR TITLE
[Web] Ensure that NetworkImage does not crash when disposed between frames

### LINKED ISSUE #164990: Web NetworkImage crash due to listener disposal issues
### Steps to reproduce

Internal bug: b/398223109

I don't have a repro, but I do have a stack trace and I believe I know what's going on.

### Expected results

NetworkImage usage on web doesn't crash

### Actual results

NetworkImage usage on web crashes with

```
StateError
  at Bad state: Stream has been disposed.
)
  at An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
)
  at To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
)
  at throwExpression	(js_helper.dart?cl=728715823: 1255)
  at ImageStreamCompleter.setImage	(image_stream.dart?cl=728715823: 720)
  at _ForwardingImageStreamCompleter.<anonymous function>.<anonymous function>	(_network_image_web.dart?cl=728715823: 332)
  at nA.c_P	(main.dart.js: 90404)
  at ImageStreamCompleter.setImage	(image_stream.dart?cl=728715823: 767)
  at MultiFrameImageStreamCompleter._emitFrame	(image_stream.dart?cl=728715823: 1136)
  at MultiFrameImageStreamCompleter._handleAppFrame	(image_stream.dart?cl=728715823: 1064)
  at Closure.cspForwardCall	(js_helper.dart?cl=728715823: 2353)
  at SchedulerBinding._invokeFrameCallback	(binding.dart?cl=728715823: 1442)
  at SchedulerBinding.handleBeginFrame.<anonymous function>	(binding.dart?cl=728715823: 1273)
```

This was caused by https://github.com/flutter/flutter/pull/157755. The implementation of `_ForwardingImageStreamCompleter` is problematic. The delegate `ImageStreamCompleter` can't and won't be disposed until its listeners have been removed explicitly. The correct implementation is something like:

```dart
class _ForwardingImageStreamCompleter extends ImageStreamCompleter {
  _ForwardingImageStreamCompleter(
    this.task, {
    InformationCollector? informationCollector,
    String? debugLabel,
  }) {
    this.debugLabel = debugLabel;
    task.then(
      (ImageStreamCompleter value) {
        resolved = true;
        if (_disposed) {
          // Add a listener since the delegate completer won't dispose if it never
          // had a listener.
          final listener = ImageStreamListener((_, _) {});
          value.addListener(listener);
          value.removeListener(listener);
          value.maybeDispose();
          return;
        }
        completer = value;
        completer.addListener(listener);
      },
      onError: (Object error, StackTrace stack) {
        reportError(
          context: ErrorDescription('resolving an image stream completer'),
          exception: error,
          stack: stack,
          informationCollector: informationCollector,
          silent: true,
        );
      },
    );
  }

  final Future<ImageStreamCompleter> task;
  bool resolved = false;
  late final ImageStreamCompleter completer;

  bool _disposed = false;

  late final listener = ImageStreamListener(
    (ImageInfo image, bool synchronousCall) {
      setImage(image);
    },
    onChunk: (ImageChunkEvent event) {
      reportImageChunkEvent(event);
    },
    onError: (Object exception, StackTrace? stackTrace) {
      reportError(exception: exception, stack: stackTrace);
    },
  );

  @override
  void onDisposed() {
    if (resolved) {
      completer.removeListener(listener);
    }
    _disposed = true;
    super.onDisposed();
  }
}
```

### Code sample

Code sample: N/A

### Screenshots or Video

Screenshots / Video demonstration: N/A

### Logs

Logs: N/A

### Flutter Doctor output

Doctor output: N/A (Google internal client)

### PR DESCRIPTION
**Pull request by dkwingsmt**
Fix https://github.com/flutter/flutter/issues/164990. The reason that caused the bug was explained under that issue.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 1]
```diff
@@ -91,13 +91,8 @@ class NetworkImage extends image_provider.ImageProvider<image_provider.NetworkIm
...
     image_provider.DecoderBufferCallback decode,
   ) {
-    // Ownership of this controller is handed off to [_loadAsync]; it is that
-    // method's responsibility to close the controller's stream when the image
-    // has been loaded or an error is thrown.
-    final StreamController<ImageChunkEvent> chunkEvents = StreamController<ImageChunkEvent>();
-
     return _ForwardingImageStreamCompleter(
-      _loadAsync(key as NetworkImage, decode, chunkEvents),
+      _loadAsync(key as NetworkImage, decode),
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/painting/_network_image_web.dart:95]: `chunkEvents` is removed because it is not used anywhere.

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 2]
```diff
@@ -566,6 +563,33 @@ abstract class ImageProvider<T extends Object> {
     }
   }
 
+  /// Calls through to [PaintingBinding.instantiateImageCodecWithSize] from
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/painting/image_provider.dart:566]: The doc is copied from `PaintingBinding.instantiateImageCodecWithSize`.

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 3]
```diff
@@ -287,25 +272,14 @@ class _ForwardingImageStreamCompleter extends ImageStreamCompleter {
         if (_disposed) {
           // Add a listener since the delegate completer won't dispose if it never
           // had a listener.
-          value.addListener(ImageStreamListener((_, _) {}));
+          final ImageStreamListener listener = ImageStreamListener((_, _) {});
+          value.addListener(listener);
+          value.removeListener(listener);
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:277]: If it improves the situation, let's start with this, but there's some smell about having to add + remove a listener before disposing of it.

**Review by yjbanov — APPROVED** [review]
lgtm

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 4]
```diff
@@ -566,6 +563,33 @@ abstract class ImageProvider<T extends Object> {
...
+  /// that specifies only one of `width` and `height` with the other remaining
+  /// null, in which case the omitted dimension will be scaled to maintain the
+  /// aspect ratio of the original dimensions. When both are null or omitted,
+  /// the image will be decoded at its native resolution (as will be the case if
+  /// the [getTargetSize] parameter is omitted).
+  @protected
+  Future<ui.Codec> instantiateImageCodecWithSize(
+    ui.ImmutableBuffer buffer, {
+    ui.TargetImageSizeCallback? getTargetSize,
+  }) {
```
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/painting/image_provider.dart]: That's perfect! Thank you so much. I've implemented this great idea.

File: packages/flutter/lib/src/painting/_network_image_web.dart (hunk 3 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/painting/_network_image_web.dart]: I agree. I added a new method `markHadListener` to bypass this check. What do you think of this approach?

Comment (dkwingsmt) [reply packages/flutter/lib/src/painting/_network_image_web.dart]: With discussion we've solved this issue by removing this check. https://github.com/flutter/flutter/pull/166797
