### PR TITLE
Avoid retaining routes when subscriptions are cleared

### LINKED ISSUE #88073: Memory leak on RouteObserver
Step 1 -> Tap push
Step 2 -> Tap pop
 
Wrong -> `MaterialPageRoute` not be released after pop the PageB

Test Code:
```dart
          import 'package:flutter/material.dart';
          void main() {
            runApp(MyApp());
          }


          class MyApp extends StatelessWidget {
            // This widget is the root of your application.
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                title: 'Flutter Demo',
                navigatorObservers: [observer],
                theme: ThemeData(
                  primarySwatch: Colors.blue,
                ),
                home: PageA(),
              );
            }
          }
          
          RouteObserver<PageRoute> observer = RouteObserver<PageRoute>();
          
          class PageA extends StatefulWidget {
            @override
            _PageAState createState() => _PageAState();
          }
          
          class _PageAState extends State<PageA> {
            int index = 0;
          
            @override
            Widget build(BuildContext context) {
              return Center(
                child: TextButton(
                  style: ButtonStyle(
                    backgroundColor: MaterialStateProperty.all(Colors.red),
                    padding: MaterialStateProperty.all(EdgeInsets.zero),
                    shape: MaterialStateProperty.all(const StadiumBorder()),
                  ),
                  onPressed: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        settings: RouteSettings(name: 'PageB', arguments: index),
                        builder: (context) {
                          return PageB();
                        },
                      ),
                    );
                  },
                  child: Container(
                    width: 200.0,
                    height: 50.0,
                    alignment: Alignment.center,
                    child: Text(
                      'Push',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 17.5,
                      ),
                    ),
                  ),
                ),
              );
            }
          }
          
          class PageB extends StatefulWidget {
            @override
            _PageBState createState() => _PageBState();
          }
          
          class _PageBState extends State<PageB> with RouteAware {
            @override
            void dispose() {
              observer.unsubscribe(this);
              super.dispose();
            }
          
            @override
            void didChangeDependencies() {
              super.didChangeDependencies();
              observer.subscribe(this, ModalRoute.of(context));
            }
          
            @override
            Widget build(BuildContext context) {
              return Center(
                child: TextButton(
                  style: ButtonStyle(
                    backgroundColor: MaterialStateProperty.all(Colors.red),
                    padding: MaterialStateProperty.all(EdgeInsets.zero),
                    shape: MaterialStateProperty.all(const StadiumBorder()),
                  ),
                  onPressed: () {
                    Navigator.of(context).maybePop();
                  },
                  child: Container(
                    width: 200.0,
                    height: 50.0,
                    alignment: Alignment.center,
                    child: Text(
                      'Pop',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 17.5,
                      ),
                    ),
                  ),
                ),
              );
            }
          
            @override
            void didPopNext() {}
          
            @override
            void didPush() {}
          
            @override
            void didPop() {}
          
            @override
            void didPushNext() {}
          }

```

memory-leak-capture

My solution

In this file -> `packages\flutter\lib\src\widgets\routes.dart`

```dart
           void unsubscribe(RouteAware routeAware) {
                assert(routeAware != null);
               for (final R route in _listeners.keys) {
                    final Set<RouteAware>? subscribers = _listeners[route];
                    subscribers?.remove(routeAware);
               }
          **__listeners.removeWhere((key, value) => value.isEmpty);_**
  }
```

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/88073

Avoids retaining a reference to a route that has no more observers.

/cc @jchenx2

### CODE REVIEW

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -1733,6 +1733,18 @@ abstract class PopupRoute<T> extends ModalRoute<T> {
 class RouteObserver<R extends Route<dynamic>> extends NavigatorObserver {
   final Map<R, Set<RouteAware>> _listeners = <R, Set<RouteAware>>{};
 
+  /// Whether this observer is managing changes for the specified route.
+  ///
+  /// If asserts are disabled, this method will throw an exception.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:1738]: @visibleForTest ?

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this

File: packages/flutter/lib/src/widgets/routes.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/routes.dart:1738]: Done

**Review by goderbauer — APPROVED** [review]
LGTM
