### PR TITLE
Fix crasher in DragableScrollableSheet when controller is animating and switching widgets

### LINKED ISSUE #125709: Crash in DraggableScrollableController.animateTo
b/279930163

Customer reports a crash happening with this stack trace:

```
flutter: The following _TypeError was thrown while notifying listeners for AnimationController:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      DraggableScrollableController.animateTo.<anonymous closure> (package:flutter/src/widgets/draggable_scrollable_sheet.dart:135:26)
flutter: #1      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
flutter: #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:830:5)
flutter: #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
flutter: #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
flutter: #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1141:11)
flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
flutter: #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1139:17)
flutter: #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:5)
flutter: #9      _invoke1 (dart:ui/hooks.dart:158:13)
flutter: #10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
flutter: #11     _beginFrame (dart:ui/hooks.dart:101:31)
```

I have not been able to reproduce the issue.

In the customer app, the scroll controller is shared across two different DraggableScrollableSheets that are switched out as they expand and collapse. 
There is a button at the top of the sheet that triggers the `_controller.animateTo` in order to collapse and expand it.
There is also a change in the sheets' extents happening in response to scroll notifications that are listening to the sheet.

Similar to https://github.com/flutter/flutter/issues/112020

### PR DESCRIPTION
**Pull request by dnfield**
We were failing to dispose of animation controllers created by `animateTo` when `didUpdateWidget` happens and we null out the `_attachedController`. This would cause the listener added here to fail on a null assertion:

https://github.com/flutter/flutter/blob/fef41cfce0e3582907f6846cf2385470bb17ecd1/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L135

Without the code change, the test ends up throwing exceptions related to that line. I don't have a great way to verify what this does visually though, hoping for help on that from internal customer.

b/279930163

See cl/527868355 as well.

Fixes https://github.com/flutter/flutter/issues/125709

### CODE REVIEW

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [hunk 1]
```diff
@@ -1404,22 +1404,21 @@ void main() {
     await tester.pumpWidget(boilerplate);
     expect(controller.isAttached, true);
     expect(controller.size, isNotNull);
-    });
+  });
```
Comment (dnfield) [inline packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1407]: (I was looking at these tests initially - no actually changes here, just fixing the whitespace)

File: packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart [hunk 2]
```diff
@@ -1636,4 +1635,59 @@ void main() {
...
+            },
+          ),
+        ),
+      ),
+    ));
+    expect(controller1.isAttached, true);
+    expect(controller2.isAttached, false);
+
+
+    controller1.animateTo(0.5, curve: Curves.linear, duration: const Duration(milliseconds: 200));
```
Comment (dnfield) [inline packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart:1677]: This is the key difference between the test above this one - in the test above, `jumpTo` is called instead of `animateTo`. `jumpTo` doesn't have any ongoing state/actions between the `didUpdateWidget`, whereas `animateTo` does.

**Review by Piinks — APPROVED** [review]
This LGTM. Thank you for finding this!
