### PR TITLE
Fix: Ensure CupertinoAlertDialog divider spans full width and resolve

### LINKED ISSUE #158522: Cupertino dialog horizontal divider is not showing correctly in dark mode
Regression introduced by #150410

The horizontal divider that separates the body of the Cupertino dialog from the actions is not correctly picking up the right color in dark mode, so it appears darker than it should. The dividers between different actions are showing up correctly.

As shown here:
381261821-fb9eecf3-659a-4fdf-974
The left image is a native dialog, the right is a CupertinoAlertDialog on master.

More details [here](https://github.com/flutter/flutter/pull/157218#issuecomment-2466747739).

### PR DESCRIPTION
**Pull request by dev-lup**
Fix: Ensure CupertinoAlertDialog divider spans full width and resolves divider color (#158522)

The `_Divider` in CupertinoAlertDialog did not span the full width and the `dividerColor` was not resolved correctly. This fix uses a `SizedBox` with `double.infinity` as the width for the divider and ensures that the `dividerColor` is properly applied.

Fixes #158522

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by Piinks** [comment]
Hey @dev-lup, thanks for the contribution! There are some failing checks here, can you take a look?

**Comment by Piinks** [comment]
This will also need a test, and a signed CLA, please see the bot comments above.

**Comment by dev-lup** [comment]
hi @Piinks , I signed the CLA, will write the test and let you know, thanks for reply

**Comment by dev-lup** [comment]
hi @Piinks, I pushed test as well, I checked the failing tests but could not able to understand them, please check if you can guide me through.

**Comment by dkwingsmt** [comment]
The customer test failure should have nothing to do with your PR and updating to the latest main should likely solve it.

There are some format issues. Can you run the autoformatter? https://docs.flutter.dev/tools/formatting

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you for investigating!

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 1]
```diff
@@ -407,7 +407,9 @@ class _CupertinoAlertDialogState extends State<CupertinoAlertDialog> {
             top: contentSection,
             bottom: Column(
               children: <Widget>[
-                _Divider(dividerColor: dividerColor, hiddenColor: backgroundColor, hidden: false),
+                SizedBox(
+                width: double.infinity,
+                child: _Divider(dividerColor: dividerColor, hiddenColor: backgroundColor, hidden: false)),
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/dialog.dart:412]: It seems to me we should either fix this in divider directly, or we need to update the _Divider's doc to mention the parent still needs to pass down a reasonable constraint.  I preferred the former, but I am ok with either since this is private class.

Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/dialog.dart:412]: edit looks like we do mentioned that in doc. so LGTM then

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
looks like there are some format error, can you run formatter on the code? or just turn on auto format

**Comment by dev-lup** [comment]
on running auto format it changes more them my code.

**Comment by dkwingsmt** [comment]
Can you check out the "Linux analyse" details and check out the errors?

**Comment by dev-lup** [comment]
something like this is failing, can you tell me what may went wrong. 
Command: dart --enable-asserts /b/s/w/ir/x/w/flutter/dev/bots/analyze.dart
Command exited with exit code 1 but expected zero exit code.

**Comment by dkwingsmt** [comment]
If you click into the details you should see the following: (I've copied it out for you)
```

                                                                                                    
Found 2 Dart files which were formatted incorrectly.
To fix, run `dart format packages/flutter/test/cupertino/dialog_test.dart packages/flutter/lib/src/cupertino/dialog.dart` or:

git apply <<DONE
diff --git a/packages/flutter/test/cupertino/dialog_test.dart b/packages/flutter/test/cupertino/dialog_test.dart
index 4013d0d126..0000000000 100644
--- a/packages/flutter/test/cupertino/dialog_test.dart
+++ b/packages/flutter/test/cupertino/dialog_test.dart
@@ -1989,12 +1989,14 @@ void main() {
     );
   });
 
-  testWidgets('CupertinoAlertDialog divider spans full width and applies color', (WidgetTester tester) async {
-      const double kCupertinoDialogWidth = 270.0;
-      const double kDividerThickness = 0.3;
-      const Size expectedSize = Size(kCupertinoDialogWidth, kDividerThickness);
+  testWidgets('CupertinoAlertDialog divider spans full width and applies color', (
+    WidgetTester tester,
+  ) async {
+    const double kCupertinoDialogWidth = 270.0;
+    const double kDividerThickness = 0.3;
+    const Size expectedSize = Size(kCupertinoDialogWidth, kDividerThickness);
 
-      await tester.pumpWidget(
+    await tester.pumpWidget(
       CupertinoApp(
         home: MediaQuery(
           data: const MediaQueryData(platformBrightness: Brightness.dark),
@@ -2016,16 +2018,17 @@ void main() {
 
     final Finder decoratedBoxFinder = find.byType(DecoratedBox);
 
-    expect(decoratedBoxFinder, findsAny, reason:  'There should exist at least one DecoratedBox');
+    expect(decoratedBoxFinder, findsAny, reason: 'There should exist at least one DecoratedBox');
 
-    final Iterable<Element> elements = decoratedBoxFinder.evaluate().where(
-      (Element decoratedBoxElement) {
-        final DecoratedBox decoratedBox = decoratedBoxElement.widget as DecoratedBox;
-        return (decoratedBox.decoration is BoxDecoration?) && (decoratedBox.decoration as BoxDecoration?)?.color ==
-                CupertinoDynamicColor.resolve(
-                    CupertinoColors.separator, decoratedBoxElement) &&  tester.getSize(find.byWidget(decoratedBox)) == expectedSize;
-      },
-    );
+    final Iterable<Element> elements = decoratedBoxFinder.evaluate().where((
+      Element decoratedBoxElement,
+    ) {
+      final DecoratedBox decoratedBox = decoratedBoxElement.widget as DecoratedBox;
+      return (decoratedBox.decoration is BoxDecoration?) &&
+          (decoratedBox.decoration as BoxDecoration?)?.color ==
+              CupertinoDynamicColor.resolve(CupertinoColors.separator, decoratedBoxElement) &&
+          tester.getSize(find.byWidget(decoratedBox)) == expectedSize;
+    });
 
     expect(elements.length, 1, reason: 'No DecoratedBox matches the specified criteria.');
   });
@@ -2188,3 +2191,4 @@ class LegacyAction extends StatelessWidget {
     );
   }
 }
diff --git a/packages/flutter/lib/src/cupertino/dialog.dart b/packages/flutter/lib/src/cupertino/dialog.dart
index 94b2d305b5..0000000000 100644
--- a/packages/flutter/lib/src/cupertino/dialog.dart
+++ b/packages/flutter/lib/src/cupertino/dialog.dart
@@ -408,8 +408,13 @@ class _CupertinoAlertDialogState extends State<CupertinoAlertDialog> {
             bottom: Column(
               children: <Widget>[
                 SizedBox(
-                width: double.infinity,
-                child: _Divider(dividerColor: dividerColor, hiddenColor: backgroundColor, hidden: false)),
+                  width: double.infinity,
+                  child: _Divider(
+                    dividerColor: dividerColor,
+                    hiddenColor: backgroundColor,
+                    hidden: false,
+                  ),
+                ),
                 Flexible(child: scrolledActionsSection),
               ],
             ),
@@ -2590,3 +2595,4 @@ class _RenderPriorityColumn extends RenderFlex {
     return (topChildHeight: 0, bottomChildHeight: maxHeight);
   }
 }
DONE

╔═╡ERROR #1╞════════════════════════════════════════════════════════════════════
║ Command: bin/cache/dart-sdk/bin/dart --enable-asserts /b/s/w/ir/x/w/flutter/dev/tools/bin/format.dart
║ Command exited with exit code 1 but expected zero exit code.
║ Working directory: /b/s/w/ir/x/w/flutter
╚═══════════════════════════════════════════════════════════════════════════════
▌20:12:28▐ Analyzing code in the framework with the following rules:
 * No "double.clamp"
 * No "Stopwatch"
 * RenderBox subclass intrinsic calculation best practices
 * Add "@protected" to public State subtypes
▌20:14:10▐ Analyzing code in the test folder with the following rules:
 * No "Stopwatch"
▌20:15:37▐ Analyzing code in the tool with the following rules:
 * Avoid "Future.catchError" and "Future.onError"
▌20:16:37▐ Executable allowlist...
▌20:16:37▐ Dart analysis (with --watch)...
RUNNING: cd .; bin/flutter analyze --flutter-repo --watch --benchmark
workingDirectory: /b/s/w/ir/x/w/flutter, executable: /b/s/w/ir/x/w/flutter/bin/flutter, arguments: [analyze, --flutter-repo, --watch, --benchmark]
Analyzing Flutter repository...                                    21.3s

```

**Comment by dev-lup** [comment]
thanks for helping me, but on running 

dart format packages/flutter/test/cupertino/dialog_test.dart packages/flutter/lib/src/cupertino/dialog.dart

its changing more code then I am expecting. 

I am attaching git diff for you to check. 
[log.txt](https://github.com/user-attachments/files/18652407/log.txt)

**Comment by dkwingsmt** [comment]
Sorry, I'm not sure either. Haven't used the autoformatter much since the autoformating change. Can you manually edit the files or pick the files from the git changes?

**Comment by dev-lup** [comment]
I can try formatting the code according to the formatter. 

Thanks

**Comment by Piinks** [comment]
Hey @dev-lup thanks for the update! It looks like the formatter still needs to be run here. Can you take a look?

**Comment by dev-lup** [comment]
Hi @Piinks i tried running formatter but it changed most of the file, i not sure if i should push that for changes it did on dart format you can check my above comment with log.txt, 

Please let me know if there any solution 

Thanks

**Comment by dkwingsmt** [comment]
I've edited the files by running `dart format` locally.

**Comment by dev-lup** [comment]
thanks @dkwingsmt I appreciate your help, can you tell me what would went wrong on my side ?

**Comment by dkwingsmt** [comment]
Sorry I know little about the tools :(   Honestly I often just brute force and do them by hand when I encounter similar issues. Doesn't take long anyway.

Could it be that your `dart` is a different binary? Can you check the path of your `dart` and `flutter` executables?

**Comment by dev-lup** [comment]
@dkwingsmt I checked my binary indeed it was not correctly configured, now its working great, thanks for the help
