### PR TITLE
Fix BottomNavigationBarItem label overflow

### LINKED ISSUE #112163: BottomNavigationBarItem label overflow with BottomNavigationBarLandscapeLayout.linear
Steps to Reproduce:

Watch the video and open the attached code:

[flutter_bug_overflow.zip](https://github.com/flutter/flutter/files/9624441/flutter_bug_overflow.zip)
[bandicam 2022-09-22 16-11-47-271 .zip](https://github.com/flutter/flutter/files/9624483/bandicam.2022-09-22.16-11-47-271.zip)

Expected results:
no overflow message

Actual results:
overflow message

flutter doctor:
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version
    6.1.7601], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows
      development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload,
      including all of its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.70.0)
[√] Connected device (2 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by sharmashashi**
This PR wraps the `label` with `IntrinsicWidth` and then `Flexible` which allows DefaulTextStyle `TextOverflow.ellipsis` to work. Wrapping `label` directly with `Flexible` brings more space between `icon` and `label`. `IntrinsicWidth` fixes this by giving reasonable width.

Fixes #112163

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 1]
```diff
@@ -605,7 +605,11 @@ class _Tile extends StatelessWidget {
         heightFactor: 1,
         child: Row(
           mainAxisSize: MainAxisSize.min,
-          children: <Widget>[icon, const SizedBox(width: 8), label],
+          children: <Widget>[
+            icon,
+            const SizedBox(width: 8),
+            Flexible(child: IntrinsicWidth(child: label))
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:611]: A comment that explains what this unusual combination of widgets is for would be helpful here.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 2]
```diff
@@ -2488,6 +2488,52 @@ void main() {
...
+
+  testWidgets('BottomNavigationBar linear landscape layout label RenderFlex overflow',(WidgetTester tester) async {
+    tester.binding.window.physicalSizeTestValue = const Size(540, 340);
+
+    await tester.pumpWidget(
+      MaterialApp(
+        home: Builder(
+          builder: (BuildContext context) {
+            return Scaffold(
+                bottomNavigationBar: BottomNavigationBar(
```
Comment (HansMuller) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart:2500]: The two-space indentation needs to be fixed up here.
```dart
          builder: (BuildContext context) {
            return Scaffold(
                bottomNavigationBar: BottomNavigationBar(
                   type: BottomNavigationBarType.fixed,
                   landscapeLayout: BottomNavigationBarLandscapeLayout.linear,
                  ...
```

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 3]
```diff
@@ -2488,6 +2488,52 @@ void main() {
     expect(tester.getRect(find.byKey(icon0)), const Rect.fromLTRB(104.0, 562.0, 204.0, 582.0));
     expect(tester.getRect(find.byKey(icon1)), const Rect.fromLTRB(504.0, 562.0, 604.0, 582.0));
   });
+
+  testWidgets('BottomNavigationBar linear landscape layout label RenderFlex overflow',(WidgetTester tester) async {
+    tester.binding.window.physicalSizeTestValue = const Size(540, 340);
```
Comment (HansMuller) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart:2493]: Please insert a comment here:
```dart
Regression test for https://github.com/flutter/flutter/issues/112163
```

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 4]
```diff
@@ -2488,6 +2488,52 @@ void main() {
...
+                  backgroundColor: Colors.grey,
+                  tooltip: '',
+                ),
+              ],
+            ));
+          },
+        ),
+      ),
+    );
+
```
Comment (HansMuller) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart:2534]: Shouldn't this test be verifying that the expected ellipsis suffixes have appeared?

**Review by HansMuller — COMMENTED** [review]
This looks OK, assuming that it doesn't break any existing layouts. Running a large internal test suite now to check.

**Comment by HansMuller** [comment]
I've checked this against the internal tests, see (google internal link) cl/513379794. All appears to be well.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 1 above)
Comment (sharmashashi) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:611]: Okay. So defining what `Flexible` and `IntrinsicWidth` does for the `label` would be fine, right?

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 4 above)
Comment (sharmashashi) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart:2534]: I am not sure because the ellipsis was already applied, should we verify that the `overflow` property is `TextOverflow.ellipsis`? Can you please guide me with this?

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:625]: It's pretty obvious what `<Widget>[icon, const SizedBox(width: 8), label]` means however it's not obvious what wrapping `label` in Flexible and IntrinsicWidth widgets is intended to accomplish in the new version. Which is to say, "yes" :-)

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart:2500]: It looks like line 2500 still needs to be backed up two spaces.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 4 above)
Comment (HansMuller) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart:2534]: I think you need to verify that the "..." suffix actually appears as expected.

**Review by HansMuller — COMMENTED** [review]
Sorry, I lost track of this one. In addition to the feedback, it looks like there are analyzer failures to fix up.

You can check for analyzer errors locally with `flutter analyze --flutter-repo`

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 4 above)
Comment (sharmashashi) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart:2536]: I don't know how to verify that. I have looked into it and couldn't find any way except golden test. The current test verifies that there will be no render overflow. I am kind of stuck here.

**Comment by HansMuller** [comment]
I asked around and it turns out it actually is difficult to programmatically verify that the ellipsis has been included at the end of text. So in this case creating a golden image test is warranted.  See [Writing a golden file test for package:flutter](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter).

Looks like the presubmit bots have some issues as well.

**Comment by goderbauer** [comment]
(triage) @sharmashashi Do you still have plans to come back to this and address the feedback given above?

**Comment by sharmashashi** [comment]
> (triage) @sharmashashi Do you still have plans to come back to this and address the feedback given above?

Yes, I do. I will look into this within a week and let know if I can continue with the golden test.

**Comment by sharmashashi** [comment]
@HansMuller I write the golden test. I read the guide on creating the new golden file test but I did not understand how to include golden(s) in PR description as stated `The reviewer should also verify your golden image(s), so make sure to include the golden(s) in your PR description.`
I was also reading the conversation from an old [PR](https://github.com/flutter/flutter/pull/22264). I was wondering if [these steps](https://github.com/flutter/flutter/pull/22264#issuecomment-435256933) are still being followed.

**Review by HansMuller — APPROVED** [review]
LGTM. Thanks for sorting out how to write a golden file test!

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!
