### PR TITLE
Elide tree walks

### LINKED ISSUE #9329: Stack frame filtering should collapse long tree walks
It feels like a simple message saying "Failed host lookup: 'd3rt1990lpmkn.cloudfront.net' (OS Error: Non-recoverable error, errno = -4)"  "Can't load image"

would be sufficient.  The stack trace doesn't add much of value.

```
[00094.792] 18313.18355>  EXCEPTION CAUGHT BY SERVICES 
[00094.796] 18313.18355> The following SocketException was thrown resolving a single-frame image stream:
[00094.796] 18313.18355> Failed host lookup: 'd3rt1990lpmkn.cloudfront.net' (OS Error: Non-recoverable error, errno = -4)
[00094.811] 18313.18355> 
[00094.811] 18313.18355> When the exception was thrown, this was the stack:
[00094.820] 18313.18355> #0      IOClient.send (package:http/src/io_client.dart:30)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #2      BaseClient.get (package:http/src/base_client.dart:34)
[00094.820] 18313.18355> #3      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:342)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #4      NetworkImage.load (package:flutter/src/services/image_provider.dart:328)
[00094.820] 18313.18355> #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)
[00094.821] 18313.18355> #6      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)
[00094.821] 18313.18355> #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)
[00094.821] 18313.18355> #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
[00094.821] 18313.18355> #9      ImageProvider.resolve (package:flutter/src/services/image_provider.dart:167)
[00094.821] 18313.18355> #10     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:259)
[00094.821] 18313.18355> #11     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:241)
[00094.821] 18313.18355> #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3193)
[00094.821] 18313.18355> #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.821] 18313.18355> #23     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.821] 18313.18355> #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.821] 18313.18355> #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.821] 18313.18355> #32     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.821] 18313.18355> #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.821] 18313.18355> #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4121)
[00094.821] 18313.18355> #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #46     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3195)
[00094.822] 18313.18355> #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #53     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #62     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #77     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.823] 18313.18355> #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.823] 18313.18355> #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.823] 18313.18355> #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #83     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.823] 18313.18355> #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.823] 18313.18355> #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.823] 18313.18355> #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #93     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #94     ProxyElement.update (package:flutter/src/widgets/framework.dart:3325)
[00094.823] 18313.18355> #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #96     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3751)
[00094.823] 18313.18355> #97     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4131)
[00094.823] 18313.18355> #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #101    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:507)
[00094.823] 18313.18355> #102    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:480)
[00094.823] 18313.18355> #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #104    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3751)
[00094.823] 18313.18355> #105    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4131)
[00094.823] 18313.18355> #106    ViewportElement.update (package:flutter/src/widgets/viewport.dart:83)
[00094.823] 18313.18355> #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #115    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #125    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #126    StatelessElement.update (package:flutter/src/widgets/framework.dart:3139)
[00094.824] 18313.18355> #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #129    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #133    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #137    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #138    StatelessElement.update (package:flutter/src/widgets/framework.dart:3139)
[00094.824] 18313.18355> #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #145    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #146    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1866)
[00094.824] 18313.18355> #147    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:353)
[00094.824] 18313.18355> #148    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
[00094.824] 18313.18355> #149    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645)
[00094.824] 18313.18355> #150    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580)
[00094.824] 18313.18355> #151    _beginFrame (file:///Users/freiling/workspace/fuchsia/flutter/lib/ui/hooks.dart:83)
[00094.827] 18313.18355> 
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Elides repetitive tree walking related frames from stack traces in Flutter.

For example, a stack trace resulting from a bad deeply nested widget now prints out 29 lines instead of over 300.

I'm not sure if we want to have a debug flag for disabling this - I personally have never cared about how many tree walks happened when debugging framework issues though.  /cc @chunhtai @Piinks @goderbauer  for feedback on that.

@Hixie @a14n @zanderso @jonahwilliams  probably have thoughts on this too.

## Related Issues

Fixes #9329 

## Tests

I added the following tests:

Test asserting defaultStackFilter filters a huge ugly stack down.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -683,6 +687,16 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
         skipped.add('class ${frameLine.className}');
       } else if (filteredPackages.contains(frameLine.packageScheme + ':' + frameLine.package)) {
         skipped.add('package ${frameLine.packageScheme == 'dart' ? 'dart:' : ''}${frameLine.package}');
+      } else if (frameLine.packageScheme == 'package' && frameLine.package == 'flutter') {
+        if (visited.add('flutter/${frameLine.packagePath}:${frameLine.line}:${frameLine.column}')) {
+          if (skippedFromFlutterCount > 0) {
+            result.add('(elided $skippedFromFlutterCount frame${skippedFromFlutterCount == 1 ? '' : 's'} from package:flutter)');
```
Comment (zanderso) [inline packages/flutter/lib/src/foundation/assertions.dart]: Maybe: 'elided 2 revisited frames ...' or something similar so that there's some explanation of what was left out.

**Comment by dnfield** [comment]
@InMatrix  - what do you think of this?

@DanTup @jacob314 @devoncarew  - will this negatively impact IDEs?

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: Talked offline.  We should figure out what the best thing for a user is here.  It might just be chopping the stack N frames of flutter code after user code.

**Comment by dnfield** [comment]
Stack traces from the framework generally have this shape:

1. Top few frames are Dart code for throwing the exception. We already elide these.
2. The next few frames are either user code or Flutter code that called into Dart to throw.
3. If the previous frames were flutter code, these frames are user code.
4. Lots of frames of flutter code with the shape of `*Element.mount` followed by several lines of build related logic followed by another `*Element.mount`, repeated down to the root element.
5. Attaching to the tree frames
6. Timer related frames from Dart
7. ReceivePortImpl frame from Dart.

We could probably safely omit all Flutter frames after the first `mount` call we find.

**Comment by dnfield** [comment]
Eliding everything after the first mount would look something like:

```
I/flutter ( 4364): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4364): The following assertion was thrown building Builder(dirty):
I/flutter ( 4364): A non-null String must be provided to a Text widget.
I/flutter ( 4364): 'package:flutter/src/widgets/text.dart':
I/flutter ( 4364): Failed assertion: line 287 pos 10: 'data != null'
I/flutter ( 4364): 
I/flutter ( 4364): The relevant error-causing widget was:
I/flutter ( 4364):   Builder file:///Users/dnfield/src/flutter_projects/assertions/lib/main.dart:5:10
I/flutter ( 4364): 
I/flutter ( 4364): When the exception was thrown, this was the stack:
I/flutter ( 4364): #2      new Text (package:flutter/src/widgets/text.dart:287:10)
I/flutter ( 4364): #3      blah.<anonymous closure> (package:assertions/main.dart:7:20)
I/flutter ( 4364): #4      Builder.build (package:flutter/src/widgets/basic.dart:6825:41)
I/flutter ( 4364): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4371:28)
I/flutter ( 4364): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)
I/flutter ( 4364): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)
I/flutter ( 4364): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)
I/flutter ( 4364): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)
I/flutter ( 4364): #452    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter ( 4364): #453    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter ( 4364): #454    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter ( 4364): (elided 444 frames from class _AssertionError, package dart:async, package dart:async-patch, and package flutter)
I/flutter ( 4364): 
I/flutter ( 4364): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zanderso** [comment]
Supposing that `mount` is the right cut-off point, this approach sgtm.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (jacob314) [reply packages/flutter/lib/src/foundation/assertions.dart]: Would IDE users ever want to expand out the elided frames? If so, it could be worth it to expose the elided frames with enough structure that IDEs can expose expanding out the elided frames.

The ideal solution would be that an IDE received this data with enough structure to expand and collapse blocks of elided frames if requested by an IDE user who wants to see the elided frames.

I do like placing the logic of what frames should start out elided in package:flutter instead of having intellij, devtools, and VSCode create their own logic about what frames to elide when displaying flutter error messages.
It would be even better if consistent frame black boxing was also applied to stack traces displayed by IDEs but that would be a hard problem to solve.

Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: I personally don't think it's ever useful to see all of these frames.  Or, if it is, it's so rare that it's worth just instrumenting the code differently in the framework by hand.

Do the IDEs use the defaultStackFilter, or do they replace it?

Comment (jacob314) [reply packages/flutter/lib/src/foundation/assertions.dart]: IDEs currently use defaultStackFilter. If eliding frames gets aggressive enough that users sometimes need to see the frames, we could revisit.

**Comment by dnfield** [comment]
This breaks some tests that are asserting against error messgaes - I'll update the tests if there's consensus that this is a good approach.

**Comment by Hixie** [comment]
It's a bit more subtle than the discussion above suggests.

It's not only Flutter code in these iterations. For example, users can create their own Elements or RenderObjects and then their code will be present in these loops. It's critical that users be able to see this information when debugging their own logic.

The iterations are not perfectly repeated. For example, some widgets have custom elements, and they might have their own mounting logic. When you're doing layout, every node has its own performLayout method. Thus every one out of every 3 or 4 frames is actually subtly different in a potentially useful way. I've definitely often made use of this information.

What we could do is recognize specific patterns (building, mounting, unmounting widgets; layout or paint of render objects; semantics; etc) and replace the relevant parts of the stack with a clean description of what's happening, e.g. "laying out render objects: RenderStack (stack.dart:302), RenderDecoratedBox (proxy_box.dart:201), RenderFlex (flex.dart:585), RenderFlex (flex.dart:585)" or something.

File: packages/flutter/test/foundation/assertions_test.dart [hunk 2]
```diff
@@ -428,4 +428,367 @@ void main() {
...
+        '#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4414:27)',
+        '#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)',
+        '#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)',
+        '#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)',
+        '#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4461:11)',
+        '#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)',
+        '#348    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)',
+        '#349    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)',
+        '#350    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)',
+        '(elided 330 frames from package flutter)'
```
Comment (Hixie) [inline packages/flutter/test/foundation/assertions_test.dart]: here in particular i think we are eliding way too much valuable information. It'd be better if between `#9` and `#348` we said something like "Inflated 28 elements". Even more than that though, because consider frames `#21` or `#60` for example, notice how those are different from the rest of the pattern.

I definitely wouldn't elide frames `#333` to `#339` inclusive. I think on the other hand we _should_ elide `#348` to `#350`, that we don't is just an oversight in the current code.

BTW we should make these tests verify the output on real stacks generated by the test, because we want to catch future regressions where Dart or the Flutter framework change structure and the logic here bitrots again.

Comment (dnfield) [reply packages/flutter/test/foundation/assertions_test.dart]: I don't think we can properly handle user code this way, but if it's a custom widget we wouldn't omit it here because that would live outside of package:flutter.

Part of the problem is a stack trace line just doesn't give us enough information (particularly on web, where we don't even get the class name). What might be possible is iterating from the bottom up until we hit a mount call from framework.dart, then group those together until we get to the one before we hit user code (and repeat if there's a custom element in user code).

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (DanTup) [reply packages/flutter/lib/src/foundation/assertions.dart]: If people need to debug something tricky there's always the option of adding breakpoints/break-on-all-exceptions where they'd get the full stack in the debugging tools.

In VS Code we do collapse multiple frames from SDKs that one (eg. "<105 frames from Flutter SDK>") but you can click-to-expand.

I suspect few people would miss these frames being removed from here (in VS Code at least) if they're still there in the debugger call stack.

Comment (Hixie) [reply packages/flutter/lib/src/foundation/assertions.dart]: Debuggers are more or less useless when debugging this code, because stepping through what we do even for a single frame takes hours. Stack inspection and printf-debugging is really the only reasonable way I've found to debug errors deep in the framework.

File: packages/flutter/test/foundation/assertions_test.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/test/foundation/assertions_test.dart]: It's fine if we do a bad job on Web because Web doesn't give us enough yet. We should aim for doing the best we can on each platform we support, and not get tied down by the least common denominator.

Comment (Hixie) [reply packages/flutter/test/foundation/assertions_test.dart]: we could have pattern matchers for specific stack patterns we know about. if we do that, then there should be a way for these patterns to get registered by the bindings, so that each layer can register its own matchers.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (DanTup) [reply packages/flutter/lib/src/foundation/assertions.dart]: Ah, fair enough! I thought break-on-all-exceptions would break you in a good place but I've really no experience trying to debug these sorts of issues so I'll defer to the experts :-)

Jacob's original idea sounds good though - if all stack frames are provided to the IDE in a structured way with flags on which ones are reasonable to elide, then for IDEs that have an easy way to collapse them (but still make them accessible - similar to VS Code's call stack), that might be best of both worlds (for locations where interaction isn't possible, the whole list could be shown, or have a user preference - similar to how we let users device whether to have Framework libraries debuggable or not).

Comment (Hixie) [reply packages/flutter/lib/src/foundation/assertions.dart]: Generally the stack traces I'm trying to divine from are on GitHub, no IDEs in sight. :-)

**Comment by dnfield** [comment]
@hixie I think the stack you're thinking of is different from what I'm used to seeing.  Probably a throw during layout?

In any case, I tried just cleaning up the `mount` loops like this:

```
#2      new Text (package:flutter/src/widgets/text.dart:287:10)
#3      _MyHomePageState.build (package:assertions/main.dart:100:15)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4414:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4461:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)
#10+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#13+5   ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#19+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#22+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#25+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#32+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#35+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#38+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#45+5   ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#51+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#58+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#61+5   ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#67+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#70+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#77+5   ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#83+2   SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#86+5   ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#92+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#99+6   ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#106+1  MultiChildRenderObjectElement: mount -> inflateWidget
#108+9  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget -> mount -> updateChild -> inflateWidget
#118+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#124+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#127+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#134+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#137+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#140+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#146+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#153+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#159+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#165+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#171+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#177+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#183+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#189+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#196+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#202+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#208+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#211+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#217+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#223+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#229+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#235+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#241+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#244+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#251+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#257+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#264+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#270+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#276+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#282+2  SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#285+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#291+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#298+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#305+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#312+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#318+6  ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#325+5  ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#331    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3070:12)
#333    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1054:16)
#334    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1025:5)
#335    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:17)
#336    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2494:19)
#337    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:967:13)
#338    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:848:7)
#339    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:830:7)
(elided 3 frames from dart:isolate-patch)
```

But it's still looking too verbose to me.

**Comment by dnfield** [comment]
The significant difference being that _all_ of these calls are coming from the same file and the same two or three generic framework elements - so nothing nice about "oh, this one was for a stack, this one was for a row" etc.

**Comment by InMatrix** [comment]
For the specific error example @dnfield showed earlier in this PR, nothing in the stack is useful or necessary for the user to debug the error. If the lines above the stack are not enough for the user to understand the error, the user is more likely to google the error message than digging through the stack. 

```
I/flutter ( 4364): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4364): The following assertion was thrown building Builder(dirty):
I/flutter ( 4364): A non-null String must be provided to a Text widget.
I/flutter ( 4364): 'package:flutter/src/widgets/text.dart':
I/flutter ( 4364): Failed assertion: line 287 pos 10: 'data != null'
I/flutter ( 4364): 
I/flutter ( 4364): The relevant error-causing widget was:
I/flutter ( 4364):   Builder file:///Users/dnfield/src/flutter_projects/assertions/lib/main.dart:5:10
I/flutter ( 4364): 
I/flutter ( 4364): When the exception was thrown, this was the stack:
I/flutter ( 4364): #2      new Text (package:flutter/src/widgets/text.dart:287:10)
I/flutter ( 4364): #3      blah.<anonymous closure> (package:assertions/main.dart:7:20)
I/flutter ( 4364): #4      Builder.build (package:flutter/src/widgets/basic.dart:6825:41)
I/flutter ( 4364): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4371:28)
I/flutter ( 4364): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)
I/flutter ( 4364): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)
I/flutter ( 4364): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)
I/flutter ( 4364): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)
I/flutter ( 4364): #452    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter ( 4364): #453    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter ( 4364): #454    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter ( 4364): (elided 444 frames from class _AssertionError, package dart:async, package dart:async-patch, and package flutter)
I/flutter ( 4364): 
I/flutter ( 4364): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

It would be helpful to use an example where the stack actually has information the user will need to debug the error.

**Comment by dnfield** [comment]
Perhaps rather than dumping the full Flutter stack, we should dump the truncated stack (just the first few frames in Flutter land), and then some kind of helpful summary of the current state of render/element/layer/semantics tree stuff?

**Comment by Hixie** [comment]
> For the specific error example @dnfield showed earlier in this PR, nothing in the stack is useful or necessary for the user to debug the error.

Sure, but how can we distinguish those from cases where they _are_ necessary?


> But it's still looking too verbose to me.

Can we collapse identical lines in that stack too?

**Comment by Hixie** [comment]
e.g.:
```
#2      new Text (package:flutter/src/widgets/text.dart:287:10)
#3      _MyHomePageState.build (package:assertions/main.dart:100:15)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4414:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4461:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)
#10     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#13     ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#19     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget (x2)
#25     ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#32     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget (x2)
#38     ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#45     ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#51     ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#58     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#61     ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#67     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#70     ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#77     ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#83     SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#86     ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#92     ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x2)
#106    MultiChildRenderObjectElement: mount -> inflateWidget
#108    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget -> mount -> updateChild -> inflateWidget
#118    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#124    SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#127    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#134    SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget (x2)
#140    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#146    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#153    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x6)
#189    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#196    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x2)
#208    SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#211    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x5)
#241    SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#244    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#251    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#257    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#264    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x3)
#282    SingleChildRenderObjectElement: mount -> updateChild -> inflateWidget
#285    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#291    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget (x3)
#312    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#318    ComponentElement: mount -> _firstBuild -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#325    ComponentElement: mount -> _firstBuild -> rebuild -> performRebuild -> updateChild -> inflateWidget
#331    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3070:12)
#333    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1054:16)
#334    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1025:5)
#335    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:17)
#336    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2494:19)
#337    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:967:13)
#338    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:848:7)
#339    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:830:7)
```

Though I just noticed that where this says ComponentElement it should really say either StatefulElement or StatelessElement, to be more useful...

**Comment by Hixie** [comment]
If you recognized those lines as matching the "mounting elements" patterns (see my earlier suggestion for defined pattern matchers), you could go further:

e.g.:
```
#2      new Text (package:flutter/src/widgets/text.dart:287:10)
#3      _MyHomePageState.build (package:assertions/main.dart:100:15)
#4      Normal mounting of elements (StatefulElement, StatelessElement, SingleChildRenderObjectElement)
#331    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3070:12)
#333    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1054:16)
#334    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1025:5)
#335    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:17)
#336    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2494:19)
#337    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:967:13)
#338    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:848:7)
#339    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:830:7)
```

**Comment by Hixie** [comment]
Or maybe 
```
#4      Normal mounting of 35 elements
```
(or whatever the count is, I didn't actually count it.)

If there was a special element involved, then it would still show its stack because it wouldn't match the pattern.

**Comment by Hixie** [comment]
> @Hixie I think the stack you're thinking of is different from what I'm used to seeing. Probably a throw during layout?

Layout has similar patterns and similar needs, sure. Paint, also. The widget framework has a number of different cases where there's tree iteration that has patterns we could recognize, like the one you've listed here but also things like exceptions during parent data application, global key activation, dependency changes, etc.

**Comment by InMatrix** [comment]
> Sure, but how can we distinguish those from cases where they are necessary?

I'm genuinely curious about the cases when information in the stack is necessary. Without anyone in the thread presenting such as case, it makes whoever hasn't experienced such cases themselves very difficult to participate in this discussion and be convinced that the final resolution is reasonable (i.e., striking a good balance between cost and benefit).

**Comment by dnfield** [comment]
I like @hixie's idea of having various bindings register stack recognition routines.  I think that could get us something more useful here without completely truncating the stack.

**Comment by jacob314** [comment]
Fyi @kenzieschmol, @bkonyi.
The stack recognition routines suggested would also be extremely useful for the [Dart DevTools timeline flame charts](https://flutter.dev/docs/development/tools/devtools/timeline#flame-chart). The flame charts for Flutter apps currently have a lot of visual clutter due to the same repetitive stack trace patterns.

To integrate into the flame chart display it would probably be simpler to expose registering the stack recognition routines in `dart:developer` rather than `package:flutter`. This would also have the lower priority benefit of enabling future usage any time VSCode or IntelliJ show stack traces.

**Comment by Hixie** [comment]
@InMatrix For example at home I'm experimenting with a library which introduces a bunch of new RenderObject subclasses and corresponding widgets, as well as a different set of subclasses of RenderObjectElement. When I messed up my logic in my RenderObjectElement subclass, I had to figure out exactly what was going wrong by studying the stacks I was getting.

Similarly we were recently debugging an issue with GlobalKey reparenting, where the precise order of activate/deactivate/etc matters to figuring out what's wrong.

**Comment by dnfield** [comment]
Here's another attempt.

This one adds logic to WidgetsBinding to register a special stack filtering method on defaultStackFilter.

It takes several patterns of common element tree walk operations (but only if they occur in package:flutter) and elides them down to a line like:

```
...     Normal mounting of N elements (M frames).
```

so:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder(dirty):    
flutter: A non-null String must be provided to a Text widget.           
flutter: 'package:flutter/src/widgets/text.dart':                       
flutter: Failed assertion: line 287 pos 10: 'data != null'              
flutter:                                                                
flutter: The relevant error-causing widget was:                         
flutter:   Builder file:///Users/dnfield/src/flutter_projects/assertions/lib/main.dart:5:10
flutter:                                                                
flutter: When the exception was thrown, this was the stack:             
flutter: #2      new Text (package:flutter/src/widgets/text.dart:287:10)
flutter: #3      blah.<anonymous closure> (package:assertions/main.dart:7:20)
flutter: #4      Builder.build (package:flutter/src/widgets/basic.dart:6825:41)
flutter: #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4371:28)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4303:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4027:5)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4286:5)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4281:5)
flutter: ...     Normal mounting of 1 element (7 frames).               
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
flutter: #17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5634:32)
flutter: ...     Normal mounting of 4 elements (23 frames).             
flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
flutter: #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5634:32)
flutter: ...     Normal mounting of 17 elements (96 frames).            
flutter: #137    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5634:32)
flutter: ...     Normal mounting of 18 elements (100 frames).           
flutter: #237    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5634:32)
flutter: #238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3276:14)
flutter: #239    Element.updateChild (package:flutter/src/widgets/framework.dart:3070:12)
flutter: #240    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:591:16)
flutter: ...     Normal mounting of 38 elements (222 frames).           
flutter: #462    Element.updateChild (package:flutter/src/widgets/framework.dart:3070:12)
flutter: #463    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1162:16)
flutter: #464    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1133:5)
flutter: #465    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1076:17)
flutter: #466    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2494:19)
flutter: #467    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1075:13)
flutter: #468    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:956:7)
flutter: #469    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:938:7)
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:                                                                
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderFlex overflowed by 99512 pixels on the bottom.
```

We could write similar routines for other tree walks.

**Comment by jacob314** [comment]
> This approach doesn't quite work for web and I'm not sure how to do that without refering to line/column numbers, which will be pretty fragile :(

Can you provide some details on what is breaking on the web? We fully control how Dart displays stack traces on the web (for example: it isn't depending on the browser sourcemap implementation) so if something needs to be changed on the web to provide a more uniform experience we can change it.

**Comment by dnfield** [comment]
I fixed it up for web a bit, but it's special cased right now.

The problem on web is we don't get class names in the stack traces - we only get method names.  We also get method names in brackets if they're private.

We also don't get frame line numbers, but that's not a huge deal.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 3]
```diff
@@ -20,6 +20,96 @@ typedef DiagnosticPropertiesTransformer = Iterable<DiagnosticsNode> Function(Ite
...
+    @required this.method,
+    @required this.packagePath,
+  }) : assert(className != null),
+       assert(method != null),
+       assert(packagePath != null);
+
+  /// The class name for the method.
+  ///
+  /// On web, this is ignored, since class names are not available. Top level
+  /// methods should use the empty string.
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/assertions.dart]: the second sentence here sounds like it relates to the first which confused me at first...

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 4]
```diff
@@ -20,6 +20,96 @@ typedef DiagnosticPropertiesTransformer = Iterable<DiagnosticsNode> Function(Ite
...
+  /// On web, private methods are wrapped with `[]`.
+  final String method;
+
+  /// The relative path to the file for this method and class.
+  ///
+  /// This is required for disambiguation.
+  final String packagePath;
+
+  @override
+  String toString() {
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/assertions.dart]: toString is usually used for debugging, maybe we should have a different method for this? I'm imagining a world where we automatically strip toStrings in release builds. We'd presumably still want this to work there, right?

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 5]
```diff
@@ -20,6 +20,96 @@ typedef DiagnosticPropertiesTransformer = Iterable<DiagnosticsNode> Function(Ite
...
+  final String replacement;
+
+  /// Checks whether the sublist of [StackFrame]s provided matches the [frames].
+  bool matchesFrames(List<StackFrame> stackFrames) {
+    if (stackFrames.length != numFrames) {
+      return false;
+    }
+    final String Function(StackFrame) mappingFunction = kIsWeb
+      ? (StackFrame frame) => '${frame.packagePath}: ${frame.method.startsWith('_') ? '[' + frame.method + ']' : frame.method}'
+      : (StackFrame frame) => '${frame.packagePath}: ${frame.className}.${frame.method}';
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/assertions.dart]: can we implement this by passing the StackFrame to PartialStackFrame and asking if it matches? That way we'd avoid all the string manipulation.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 6]
```diff
@@ -20,6 +20,96 @@ typedef DiagnosticPropertiesTransformer = Iterable<DiagnosticsNode> Function(Ite
...
+/// replacement string for matches.
+///
+/// See also:
+///
+///   * [FlutterError.addDefaultStackFilter], a method to register additional
+///     stack filters for [FlutterError.defaultStackFilter].
+///   * [StackFrame], a class that can help with parsing stack frames.
+///   * [PartialStackFrame], a class that helps match partial method information
+///     to a stack frame.
+class SubStackFilter {
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/assertions.dart]: would it make sense to have a mechanism whereby you can match frames more elaborately, e.g. by implementing your own matchFrames?

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: Done.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: Split this up to clarify.

**Review by dnfield — COMMENTED** [review]
In case it's not clear - I'm only adding these in debug mode right now, with the assumption being that it's easy to work around anything this might hide by instrumenting debug code, but harder if you get a random stack trace in the wild.

File: packages/flutter/lib/src/widgets/binding.dart [hunk 7]
```diff
@@ -265,6 +271,84 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
...
+    const PartialStackFrame elementUpdateChild = PartialStackFrame(className: 'Element', method: 'updateChild', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame elementRebuild = PartialStackFrame(className: 'Element', method: 'rebuild', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame componentElementPerformRebuild = PartialStackFrame(className: 'ComponentElement', method: 'performRebuild', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame componentElementFristBuild = PartialStackFrame(className: 'ComponentElement', method: '_firstBuild', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame componentElementMount = PartialStackFrame(className: 'ComponentElement', method: 'mount', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame statefulElementFristBuild = PartialStackFrame(className: 'StatefulElement', method: '_firstBuild', packagePath: 'src/widgets/framework.dart');
+    const PartialStackFrame singleChildMount = PartialStackFrame(className: 'SingleChildRenderObjectElement', method: 'mount', packagePath: 'src/widgets/framework.dart');
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/binding.dart]: nit: it would be nice if these filters could include package:flutter in the package path to eliminate the small chance of false positives.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 8]
```diff
@@ -20,6 +20,110 @@ typedef DiagnosticPropertiesTransformer = Iterable<DiagnosticsNode> Function(Ite
...
+  /// The class name for the method.
+  ///
+  /// On web, this is ignored, since class names are not available.
+  ///
+  /// On all platforms, top level methods should use the empty string.
+  final String className;
+
+  /// The method name for this frame line.
+  ///
+  /// On web, private methods are wrapped with `[]`.
```
Comment (jacob314) [inline packages/flutter/lib/src/foundation/assertions.dart]: Maybe reference https://github.com/dart-lang/sdk/issues/40117 here

**Review by jacob314 — COMMENTED** [review]
lgtm

File: packages/flutter/lib/src/widgets/binding.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/binding.dart]: Done

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 8 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: Done

**Comment by dnfield** [comment]
I'm going to land this on green - @hixie if any concerns remain we can continue to iterate on it.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 6 above)
Comment (Hixie) [reply packages/flutter/lib/src/foundation/assertions.dart]: I wouldn't want my subclass to have to carry around the `frames` and `numFrames` and `replacement` members that are all just part of this one's implementation, though...

Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: Ahh. I can fix that.

Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart]: See latest commit.

Although it no longer tells you how many elements were elided - I could probably make that still work but it seems more complicated than its worth at this point.

**Comment by goderbauer** [comment]
Looks like Cirrus is unhappy on this one now.

**Comment by dnfield** [comment]
Should be fixed on latest commit.  I forgot to update the regex string in a test.
