### PR TITLE
Handle backspace edgecase in trailing whitespace formatter.

### LINKED ISSUE #56149: Backspace/delete not working at word boundary after mixing RTL/LTR text
Extracted from https://github.com/flutter/flutter/issues/22627

As reported by @FlutterIODev:

> Now when you write Arabic words and try to delete them, everything works fine, but if you tried to write English words then try to delete them flutter will be stuck after deleting one word and will never respond to the delete button from the keyboard.
> 
> The problem appears on a physical device as well as on the Android emulator.
> 
> The following [video](https://drive.google.com/open?id=1HBtWoRbv90puAelCSiK1TgtssZrs24GN) describes the problem.
> 
> # Flutter Version
> ```
> [√] Flutter: is fully installed. (Channel master, v1.18.0-9.0.pre.14, on Microsoft Windows [Version 10.0.17763.805],
>     locale en-US)
> [√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.1)
> [√] Chrome - develop for the web: is fully installed.
> [√] Android Studio: is fully installed. (version 3.5)
> [√] IntelliJ IDEA Community Edition: is fully installed. (version 2019.1)
> [√] VS Code: is fully installed. (version 1.44.2)
> [√] Connected device: is fully installed. (3 available)
> ```
> 
> # Sample Code
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_localizations/flutter_localizations.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       localizationsDelegates: [
>         GlobalMaterialLocalizations.delegate,
>         GlobalWidgetsLocalizations.delegate,
>       ],
>       supportedLocales: [Locale("ar")],
>       locale: Locale("ar"),
>       home: Scaffold(
>         appBar: AppBar(),
>         body: Padding(
>           padding: EdgeInsets.all(8),
>           child: TextField(),
>         ),
>       ),
>     );
>   }
> }
> ```

Things to note:

- Works fine in just one language
- If languages are mixed, even erasing and typing in one language again prevents this from working.

### PR DESCRIPTION
**Pull request by GaryQian**
## Description

When appending a directionality codepoint, backspace sometimes deletes the directionality instead of the space, which is then added back on by the formatter.

This PR detects this and deletes the actual trailing whitespace as well as the directionality character.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/56149

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM 👍

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2571,9 +2571,12 @@ class _WhitespaceDirectionalityFormatter extends TextInputFormatter {
         composingEnd -= outputCodepoints.length < composingEnd ? 1 : 0;
       }
 
+     final bool isBackspace = oldValue.text.runes.length - newValue.text.runes.length == 1 && isDirectionalityMarker(oldValue.text.runes.last);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart:2574]: nit line length

**Review by xster — APPROVED** [review]
LGTM
