### PR TITLE
[Impeller] handle shader ordering bug on macOS.

### LINKED ISSUE #165740: Shader is not rendered when using Impeller engine.
### Steps to reproduce

1. Clone the following repo: https://github.com/ksokolovskyi/paper_liquid_metal_logo
2. Run the app on MacOS with `--enable-impeller` parameter
3. See the shader is not rendered (tested on Flutter v3.29.1 and latest master)

### Expected results

The shader is rendered correctly (the screenshot is made with the Skia engine selected)
Image

### Actual results

The shader is not rendered (the screenshot is made with the Impeller engine selected)
Image

### Code sample

The code can be found in the following repository: https://github.com/ksokolovskyi/paper_liquid_metal_logo

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.1, on macOS 15.3.2 24D81 darwin-arm64, locale en-US) [267ms]
    • Flutter version 3.29.1 on channel stable at /Users/ksokolovskyi/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 09de023485 (3 weeks ago), 2025-02-28 13:44:05 -0800
    • Engine revision 871f65ac1b
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [916ms]
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [521ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.98.2) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (3 available) [5.7s]
    • macOS (desktop)                         • macos                     • darwin-arm64   • macOS 15.3.2 24D81
      darwin-arm64
    • Mac Designed for iPad (desktop)         • mac-designed-for-ipad     • darwin         • macOS 15.3.2 24D81
      darwin-arm64
    • Chrome (web)                            • chrome                    • web-javascript • Google Chrome 134.0.6998.89

[✓] Network resources [3.2s]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/165740

if a user declares interleaved `float` and `sampler2D` uniforms, then we can screw up the binding order.

This only manifests on platforms where we don't combine all float/scalar uniform values into a single struct. We should probably start doing that for metal, but refactoring there is out of scope for this patch.

I enabled a large number of skipped tests we probably should have turned on by now. oops.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
actually I need to check https://github.com/flutter/flutter/issues/150324 this one too.

File: engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc [hunk 1]
```diff
@@ -233,25 +234,37 @@ bool RuntimeEffectContents::Render(const ContentContext& renderer,
...
   BindFragmentCallback bind_callback = [this, &renderer,
                                         &context](RenderPass& pass) {
-    size_t minimum_sampler_index = 100000000;
     size_t buffer_index = 0;
     size_t buffer_offset = 0;
-
+    size_t sampler_location = 0;
+    size_t buffer_location = 0;
+
+    // uniforms are ordered in the IPLR according to their
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/runtime_effect_contents.cc:242]:
```suggestion
    // Uniforms are ordered in the IPLR according to their
```

**Review by gaaclarke — APPROVED** [review]
LGTM!
