### PR TITLE
Set [InputDecoration.floatingLabelBehavior] default to null

### LINKED ISSUE #70625: FloatingLabelBehaviour not being inherited from InputDecorationTheme
While using TextFields in pone of my apps, I found that even if I set FloatingLabelBehaviour to something in InputDecorationTheme inside the ThemeData, this made no affect on the FloatingLabelBehaviour of any TextField. I had to set the FloatingLabelBehaviour in each TextField individually. 

While investigating the code I came accross the contructor for InputDecoration where it said : 
`this.floatingLabelBehavior = FloatingLabelBehavior.auto,`
and later while applying defaults 
`floatingLabelBehavior: floatingLabelBehavior ?? theme.floatingLabelBehavior,`
It seems obvious that since floatingLabelBehaviour is never set to null. The behaviour from theme would never be used!

Is this intentional? Or a bug? I am not sure.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Copy the code from [this gist](https://gist.github.com/emem365/45c9fc9e0581f654e7951301844e87ae) to main.dart
3. Run `flutter run`

**Expected results:** 
 Expected was that once I set floatingLabelBehaviour in InputDecorationTheme, all TextFields would follow that unless otherwise specified in the widget.

**Actual results:** 

The TextField seems to be set default  to FloatingLabelBehaviour.auto regardless of whether you set something in InputDecorationTheme.

ezgif com-gif-maker

I dont think run logs are necessary for this, as no crash or anything of that sort occur. The bug (If this is not intentional) lies in the code as mentioned above.

flutter --version :
```
Flutter 1.24.0-8.0.pre.252 • channel master • https://github.com/flutter/flutter.git
Framework • revision bf2c9dfc05 (2 days ago) • 2020-11-14 22:38:02 -0500
Engine • revision 3e77d854a7
Tools • Dart 2.12.0 (build 2.12.0-45.0.dev)
```

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

This change set `InputDecoration` constructor's `[InputDecoration.floatingLabelBehavior]` default to null so that `floatingLabelBehavior` can be inherited from `InputDecorationTheme`.

`floatingLabelBehavior` was introduced by #46115, I reviewed the PR again, and I think given a non-null default value is not needed because `InputDecorationTheme.floatingLabelBehavior` has a default value of `FloatingLabelBehavior.auto`.

### Sample Code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        inputDecorationTheme: const InputDecorationTheme(
          floatingLabelBehavior: FloatingLabelBehavior.always,
        ),
      ),
      home: Scaffold(
        body: const TextField(
          decoration: InputDecoration(
            labelText: 'Label',
          ),
        ),
      ),
    );
  }
}
```

@justinmc please review, thanks :)

## Related Issues

Fixes #70625

## Tests

I added the following tests:

See files.

### CODE REVIEW

**Comment by xu-baolin** [comment]
@justinmc I'm sorry to disturb you,  Congratulations on the new addition to your family. : )

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -2744,8 +2744,6 @@ class InputDecoration {
   ///
   /// When [FloatingLabelBehavior.never] the label will always appear in an empty
   /// field in place of the content.
-  ///
-  /// Defaults to [FloatingLabelBehavior.auto].
```
Comment (justinmc) [inline packages/flutter/lib/src/material/input_decorator.dart:2748]: Could you add this line to the InputDecorationTheme where this template is used?  Since there, it does default to auto.

Also here, outside of the template, maybe specify that the theme will be used:

"If null, [InputDecorationTheme.floatingLabelBehavior] will be used."

**Review by justinmc — COMMENTED** [review]
Thanks so much!  Mom and baby are doing great and I'm back to working on Flutter :)

This PR looks great, I just have one suggestion for improving the docs a bit.  Then this should be good to merge.

**Review by justinmc — APPROVED** [review]
LGTM 👍  Thanks for the change.  This can be merged when the tree is green.
