### PR TITLE
Preserving SafeArea : Part 2

### LINKED ISSUE #29941: Bottom notch (iPhone X) not avoided by SafeArea when the Keyboard is open
## Steps to Reproduce

The padding added by a SafeArea or calculated with a MediaQuery, correctly takes the bottom notch of an iPhone X style phone into account when the keyboard is closed.

But if the keyboard is open when the `Scaffold` have its parameter `resizeToAvoidBottomInset` set to `false`, the height of the bottom notch is not taken into account in the SafeArea, making the whole page shift down the size of the bottom notch. 

I think the correct behavior for SafeArea/MediaQuery should be to still have a `padding.bottom` value the height of the notch to avoid inconsistency of the total available height depending on the keyboard state.

Example project:
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(
          title: TextField(),
        ),
        body: Column(children: <Widget>[
          Expanded(child: Container(color: Colors.white,),),
          Expanded(child: Container(color: Colors.red,),)
        ],),
      ),
    );
  }
}
```

When clicking on the TextField to open the keyboard, the whole content of the Scaffold body will shift down since the SafeArea is not compensating for the notch anymore.

## Logs

Flutter doctor:

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-JP)
    • Flutter version 1.3.8 at /Users/guillaume/flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/guillaume/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • iPhone 6  • 1F54E7BF-0551-4AEB-9CD8-F63C502A842A • ios • iOS 12.1 (simulator)
    • iPhone XS • 46D10895-1001-4801-9F7A-D65659B06914 • ios • iOS 12.1 (simulator)

• No issues found!

```

### PR DESCRIPTION
**Pull request by Piinks**
## Description

Follow-up to https://github.com/flutter/engine/pull/8848 and #33999
This PR addresses the issue of a layout incorrectly shifting as a result of the bottom `padding`  being consumed by an obstruction (i.e. a software keyboard). 
This error presented in: 

#### resizeToAvoidBottomInsets: false
 BottomNavigationBar, SnackBar and PersistentFooter buttons affected. 
An automatic flag has been added to the Scaffold class, `maintainBottomViewPadding`,  that will follow the viewPadding of these elements when the viewInsets consumes bottom padding. 

### SafeArea
An optional flag has been added, `maintainBottomViewPadding`, to determine if viewPadding should be used over padding when there is an obstruction on the screen. In most cases, the current behavior is desirable, so is the default behavior. When the appearance of a software keyboard causes a layout shift, setting this to true will prevent that change.

### Other cases
`CupertinoTabScaffold` and `CupertinoPageScaffold` both have the resizeToAvoidBottomInsets property, but do not produce this bug. Tests have been added to prevent possible occurrence.
In Scaffold, the FloatingActionButton and BottomSheet were unaffected by layout shifts, and tests have been added for these cases as well.

## Related Issues

Fixes #29941 

## Tests

- In `cupertino/tab_scaffold_test.dart`
  - Tab contents bottom padding are not consumed by viewInsets when resizeToAvoidBottomInset overridden
- In `cupertino/scaffold.test`
  - Contents bottom padding are not consumed by viewInsets when resizeToAvoidBottomInset overridden
- In `material/scaffold_test.dart`
  - Scaffold BottomNavigationBar bottom padding is not consumed by viewInsets.
  - Persistent bottom buttons bottom padding is not consumed by viewInsets
  - BottomSheet bottom padding is not consumed by viewInsets
  - Floating Action Button bottom padding not consumed by viewInsets
- In `material/snack_bar_test.dart`
  - SnackBar bottom padding is not consumed by viewInsets
- In `widgets/safe_area_test.dart`
  - group: SafeArea maintains bottom viewPadding when specified for consumed bottom padding
    - SafeArea alone
    - SafeArea with nested Scaffold

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -1891,6 +1892,12 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
     if (removeBottomInset)
       data = data.removeViewInsets(removeBottom: true);
 
+    if(maintainBottomViewPadding && data.viewInsets != EdgeInsets.zero){
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: nit: space after if and before {

File: packages/flutter/lib/src/widgets/safe_area.dart [hunk 2]
```diff
@@ -81,7 +91,12 @@ class SafeArea extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     assert(debugCheckHasMediaQuery(context));
-    final EdgeInsets padding = MediaQuery.of(context).padding;
+    final MediaQueryData data = MediaQuery.of(context);
+    EdgeInsets padding = data.padding;
+    // Bottom padding has been consumed - i.e. by the keyboard
+    if(data.padding.bottom == 0.0 && data.viewInsets.bottom != 0.0 && maintainBottomViewPadding)
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/safe_area.dart]: nit: space after if

File: packages/flutter/lib/src/widgets/safe_area.dart [hunk 3]
```diff
@@ -70,6 +71,15 @@ class SafeArea extends StatelessWidget {
   /// The greater of the minimum insets and the media padding will be applied.
   final EdgeInsets minimum;
 
+  /// Specifies whether the [SafeArea] should maintain the [viewPadding] instead
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/safe_area.dart]: While technically correct, it's hard to understand what this sentence means...

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/safe_area.dart]: Maybe you can expand the paragraph at the bottom a little more to explain what it means that that padding is maintained, e.g. that content doesn't suddenly drop just because the keyboard popped up.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: should this only check that viewInsets.bottom is not zero? (In other words: why should a top viewInsets change the bottom padding?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -2097,6 +2103,7 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
         removeTopPadding: true,
         removeRightPadding: false,
         removeBottomPadding: false,
+        maintainBottomViewPadding: !_resizeToAvoidBottomInset,
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Is the navigation bar really the only place affected?

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart]: I was only able to reproduce the bug in this case. After chatting offline I'm going to check:

- SnackBar
- PersistentFooterButtons
- BottomSheet
- Floating Action Button

once more and write tests to include them.

File: packages/flutter/lib/src/widgets/safe_area.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/safe_area.dart]: I've updated this. Is the paragraph below a better explanation?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/safe_area.dart]: That's better. I like it. Maybe add at the end that setting this to true will avoid the UI shift to be extra explicit.

File: packages/flutter/lib/src/widgets/safe_area.dart [hunk 5]
```diff
@@ -81,7 +94,12 @@ class SafeArea extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     assert(debugCheckHasMediaQuery(context));
-    final EdgeInsets padding = MediaQuery.of(context).padding;
+    final MediaQueryData data = MediaQuery.of(context);
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/safe_area.dart]: How about

```
final EdgeInsets padding = maintainBottomViewPadding ? MediaQuery.of(context).padding : MediaQuery.of(context).viewPadding;
```

**Review by dnfield — APPROVED** [review]
LGTM modulo nit.  Feel free to take it or leave it :)
