### PR TITLE
Fixing a memory leak in About box/dialog overlays

### LINKED ISSUE #130354: memory leak: widgets/app.dart/defaultActions holds disposed objects from being GCed
Fragment of retaining path:

```
package:flutter/src/widgets/app.dart/defaultActions
                    dart.collection/_Map:[InstanceRef id: classes/4623/types/0, kind: Type,
identityHashCode: 530049589, classRef: [ClassRef id: classes/48, name: _Type, library: [LibraryRef
id: libraries/@0150898, name: dart.core, uri: dart:core]]]
                    package:flutter/src/widgets/actions.dart/VoidCallbackAction:_listeners@816441002
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
```

Full retaining path:
- [text_selection_theme_test.dart](https://github.com/flutter/flutter/pull/130470/files#diff-a51acb1b87685a6fa1520eb71c6220d53497d91214eed21df21e48ae01e3291c):
    failure1: https://github.com/polina-c/spikes/blob/master/notes/failures/2023-July-11/about_test-1.txt
    failure2: https://github.com/polina-c/spikes/blob/master/notes/failures/2023-July-11/about_test-2.txt

- [date_range_picker_test.dart](https://github.com/flutter/flutter/pull/130470/files#diff-daafe520ad7b264ccdc29cb250ad06a0f235dd442f5b2031c8dcb77cb8b5dd20): 
    https://github.com/polina-c/spikes/blob/master/notes/failures/2023-July-13/date_range_picker.txt

To repro, remove leakTrackingTestConfig from packages/flutter/test/material/about_test.dart and see the modified tests failing.

To see retaining path, set:

```
leakTrackingTestConfig: LeakTrackingTestConfig.retainingPath(),
```

and then click 'Debug' for the test in VSCode

PR that marks the issue: https://github.com/flutter/flutter/pull/130470

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

Fix three memory leaks detected by `about_test.dart`, but were really in the `Route` and `OverlayEntry` classes.

## Related Issues
 - Fixes https://github.com/flutter/flutter/issues/130354

## Tests
 - Updates about_test.dart to not ignore the leaks anymore.

### CODE REVIEW

**Review by polina-c — DISMISSED** [review]

**Comment by polina-c** [comment]
@gspencergoog , can you check the fix is align with the recommendation: https://github.com/dart-lang/leak_tracker/pull/97

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -454,7 +454,8 @@ abstract class Route<T> {
   @protected
   void dispose() {
     _navigator = null;
-    _restorationScopeId.dispose();
+    _restorationScopeId!.dispose();
+    _restorationScopeId = null;
```
Comment (polina-c) [inline packages/flutter/lib/src/widgets/navigator.dart:458]: I realized this is anti-pattern to release reference inside dispose. See the updated documentation.

**Review by polina-c — APPROVED** [review]

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/navigator.dart:458]: In this case, the owner of the `Route` (which is really a subclass: `MaterialPageRoute`) is the `Navigator`, where it exists in a list of routes until it is popped and disposed.  There's nothing to null out on the `Navigator`, since it's stored in a list.

**Comment by gspencergoog** [comment]
@polina-c So, is this an OK solution now?  The leak detector no longer shows a leak.  If this solution is "hiding" the leak, then I'm not sure how to prevent the leak without nulling it out in dispose, and I'll need some guidance on how to do that.

**Comment by polina-c** [comment]
> @polina-c So, is this an OK solution now? The leak detector no longer shows a leak. If this solution is "hiding" the leak, then I'm not sure how to prevent the leak without nulling it out in dispose, and I'll need some guidance on how to do that.



> @polina-c So, is this an OK solution now? The leak detector no longer shows a leak. If this solution is "hiding" the leak, then I'm not sure how to prevent the leak without nulling it out in dispose, and I'll need some guidance on how to do that.

How about removing nulling out for _restorationScopeId in disposal and see if leak still disappears. If it does not, I will help with investigation.

**Comment by gspencergoog** [comment]
> How about removing nulling out for _restorationScopeId in disposal and see if leak still disappears? If it does not, I will help with investigation.

Removing the nulling out of the `_restorationScopeId` in `dispose` still results in a leak.

Here are the logs:
```
Exception has occurred.
TestFailure (Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
          notGCed:
            total: 1
            objects:
              ValueNotifier<String?>:
                identityHashCode: 76486441
                context:
                  start: >
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:112:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:272:5)
                    #7______new_ValueNotifier_(package:flutter/src/foundation/change_notifier.dart:508:34)
                    #8______new_Route_(package:flutter/src/widgets/navigator.dart:171:54)
                    #9______new_OverlayRoute_(package:flutter/src/widgets/routes.dart)
                    #10_____new_TransitionRoute_(package:flutter/src/widgets/routes.dart)
                    #11_____new__ModalRoute&TransitionRoute&LocalHistoryRoute_(package:flutter/src/widgets/routes.dart)
                    #12_____new_ModalRoute_(package:flutter/src/widgets/routes.dart)
                    #13_____new_PageRoute_(package:flutter/src/widgets/pages.dart)
                    #14_____new__MaterialPageRoute&PageRoute&MaterialRouteTransitionMixin_(package:flutter/src/material/page.dart)
                    #15_____new_MaterialPageRoute_(package:flutter/src/material/page.dart)
                    #16______MasterDetailFlowState._detailPageRoute_(package:flutter/src/material/about.dart:1230:12)
                    #17______MasterDetailFlowState._nestedUI.<anonymous_closure>_(package:flutter/src/material/about.dart:1204:22)
                    #18_____NavigatorState._routeNamed_(package:flutter/src/widgets/navigator.dart:4221:47)
                    #19_____NavigatorState.pushNamed_(package:flutter/src/widgets/navigator.dart:4280:21)
                    #20______MasterDetailFlowState.openDetailPage_(package:flutter/src/material/about.dart:1150:35)
                    #21______MasterDetailFlowProxy.openDetailPage_(package:flutter/src/material/about.dart:1115:19)
                    #22______PackagesViewState._packagesList.<anonymous_closure>.<anonymous_closure>_(package:flutter/src/material/about.dart:650:43)
                    #23______InkResponseState.handleTap_(package:flutter/src/material/ink_well.dart:1154:21)
                    #24_____GestureRecognizer.invokeCallback_(package:flutter/src/gestures/recognizer.dart:275:24)
                    #25_____TapGestureRecognizer.handleTapUp_(package:flutter/src/gestures/tap.dart:654:11)
                    #26_____BaseTapGestureRecognizer._checkUp_(package:flutter/src/gestures/tap.dart:311:5)
                    #27_____BaseTapGestureRecognizer.acceptGesture_(package:flutter/src/gestures/tap.dart:281:7)
                    #28_____GestureArenaManager.sweep_(package:flutter/src/gestures/arena.dart:167:27)
                    #29_____GestureBinding.handleEvent_(package:flutter/src/gestures/binding.dart:492:20)
                    #30_____GestureBinding.dispatchEvent_(package:flutter/src/gestures/binding.dart:468:22)
                    #31_____RendererBinding.dispatchEvent_(package:flutter/src/rendering/binding.dart:439:11)
                    #32_____GestureBinding._handlePointerEventImmediately_(package:flutter/src/gestures/binding.dart:413:7)
                    #33_____GestureBinding.handlePointerEvent_(package:flutter/src/gestures/binding.dart:376:5)
                    #34_____TestWidgetsFlutterBinding.handlePointerEventForSource.<anonymous_closure>_(package:flutter_test/src/binding.dart:652:42)
                    #35_____TestWidgetsFlutterBinding.withPointerEventSource_(package:flutter_test/src/binding.dart:662:11)
                    #36_____TestWidgetsFlutterBinding.handlePointerEventForSource_(package:flutter_test/src/binding.dart:652:5)
                    #37_____WidgetTester.sendEventToBinding.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:840:15)
                    #38______rootRun_(dart:async/zone.dart:1399:13)
                    #39______CustomZone.run_(dart:async/zone.dart:1301:19)
                    #40_____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #41_____WidgetTester.sendEventToBinding_(package:flutter_test/src/widget_tester.dart:839:27)
                    #42_____TestGesture.up.<anonymous_closure>_(package:flutter_test/src/test_pointer.dart:550:26)
                    #43______rootRun_(dart:async/zone.dart:1399:13)
                    #44______CustomZone.run_(dart:async/zone.dart:1301:19)
                    #45_____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #46_____TestGesture.up_(package:flutter_test/src/test_pointer.dart:543:27)
                    #47_____WidgetController.tapAt.<anonymous_closure>_(package:flutter_test/src/controller.dart:611:21)
                    <asynchronous_suspension>
                    #48_____TestAsyncUtils.guard.<anonymous_closure>_(package:flutter_test/src/test_async_utils.dart:114:7)
                    <asynchronous_suspension>
                    #49_____main.<anonymous_closure>_(file:///Users/gspencer/code/flutter/packages/flutter/test/material/about_test.dart:273:5)
                    <asynchronous_suspension>
                    #50_____withLeakTracking_(package:leak_tracker/src/leak_tracking/orchestration.dart:93:5)
                    <asynchronous_suspension>
                    #51______withFlutterLeakTracking.<anonymous_closure>_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:120:21)
                    <asynchronous_suspension>
                    #52_____TestAsyncUtils.guard.<anonymous_closure>_(package:flutter_test/src/test_async_utils.dart:114:7)
                    <asynchronous_suspension>
                    #53_____testWidgetsWithLeakTracking.wrappedCallback_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:60:5)
                    <asynchronous_suspension>
                    #54_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:165:15)
                    <asynchronous_suspension>
                    #55_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1008:5)
                    <asynchronous_suspension>
                    #56_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                    <asynchronous_suspension>
                  disposal: >
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:112:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations.dispatchObjectDisposed_(package:flutter/src/foundation/memory_allocations.dart:286:5)
                    #7______ChangeNotifier.dispose_(package:flutter/src/foundation/change_notifier.dart:357:34)
                    #8______Route.dispose_(package:flutter/src/widgets/navigator.dart:457:25)
                    #9______OverlayRoute.dispose_(package:flutter/src/widgets/routes.dart:91:11)
                    #10_____TransitionRoute.dispose_(package:flutter/src/widgets/routes.dart:489:11)
                    #11______RouteEntry.forcedDispose_(package:flutter/src/widgets/navigator.dart:3066:11)
                    #12______RouteEntry.dispose.<anonymous_closure>.<anonymous_closure>_(package:flutter/src/widgets/navigator.dart:3121:13)
                    #13_____StackZoneSpecification._run_(package:stack_trace/src/stack_zone_specification.dart:207:15)
                    #14_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:48)
                    #15______rootRun_(dart:async/zone.dart:1391:47)
                    #16______CustomZone.run_(dart:async/zone.dart:1301:19)
                    #17______CustomZone.runGuarded_(dart:async/zone.dart:1209:7)
                    #18______CustomZone.bindCallbackGuarded.<anonymous_closure>_(dart:async/zone.dart:1249:23)
                    #19_____FakeAsync.flushMicrotasks_(package:fake_async/fake_async.dart:197:32)
                    #20_____AutomatedTestWidgetsFlutterBinding.pump.<anonymous_closure>_(package:flutter_test/src/binding.dart:1261:26)
                    #21______rootRun_(dart:async/zone.dart:1399:13)
                    #22______CustomZone.run_(dart:async/zone.dart:1301:19)
                    #23_____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #24_____AutomatedTestWidgetsFlutterBinding.pump_(package:flutter_test/src/binding.dart:1246:27)
                    #25_____WidgetTester.pumpAndSettle.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:692:23)
                    <asynchronous_suspension>
                    #26_____TestAsyncUtils.guard.<anonymous_closure>_(package:flutter_test/src/test_async_utils.dart:114:7)
                    <asynchronous_suspension>
                    #27_____main.<anonymous_closure>_(file:///Users/gspencer/code/flutter/packages/flutter/test/material/about_test.dart:279:5)
                    <asynchronous_suspension>
                    #28_____withLeakTracking_(package:leak_tracker/src/leak_tracking/orchestration.dart:93:5)
                    <asynchronous_suspension>
                    #29______withFlutterLeakTracking.<anonymous_closure>_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:120:21)
                    <asynchronous_suspension>
                    #30_____TestAsyncUtils.guard.<anonymous_closure>_(package:flutter_test/src/test_async_utils.dart:114:7)
                    <asynchronous_suspension>
                    #31_____testWidgetsWithLeakTracking.wrappedCallback_(file:///Users/gspencer/code/flutter/packages/flutter/test/foundation/leak_tracking.dart:60:5)
                    <asynchronous_suspension>
                    #32_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:165:15)
                    <asynchronous_suspension>
                    #33_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1008:5)
                    <asynchronous_suspension>
                    #34_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                    <asynchronous_suspension>
                  path: >
                    References that retain the object from garbage collection.
                    package:flutter/src/widgets/app.dart/defaultActions
                    dart.collection/_Map:[InstanceRef id: classes/4650/types/0, kind: Type, identityHashCode: 3113980454, classRef: [ClassRef id: classes/48, name: _Type, library: [LibraryRef id: libraries/@0150898, name: dart.core, uri: dart:core]]]
                    package:flutter/src/widgets/actions.dart/VoidCallbackAction:_listeners@819441002
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:0
                    dart.core/_Closure (in _handleActionChanged):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/actions.dart/_ActionsState:listenedActions
                    dart.collection/_Set:data_
                    dart.core/_List:6
                    package:flutter/src/widgets/actions.dart/_OverridableContextAction:lookupContext
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:5
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/widgets/navigator.dart/NavigatorState:userGestureInProgressNotifier
                    package:flutter/src/foundation/change_notifier.dart/ValueNotifier:_listeners@429329750
                    dart.core/_List:0
                    dart.core/_Closure (in _handleChange):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/transitions.dart/_AnimatedState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/material/about.dart/_LicensePageState:selectedId
                    package:flutter/src/foundation/change_notifier.dart/ValueNotifier:_listeners@429329750
                    dart.core/_List:0
                    dart.core/_Closure (in _valueChanged):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/value_listenable_builder.dart/_ValueListenableBuilderState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/material/material.dart/_MaterialState:_tickerModeNotifier@793311458
                    package:flutter/src/foundation/change_notifier.dart/ValueNotifier:_listeners@429329750
                    dart.core/_List:12
                    dart.core/_Closure (in _updateTicker):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/implicit_animations.dart/_AnimatedDefaultTextStyleState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/MultiChildRenderObjectElement:_renderObject@345042623
                    package:flutter/src/rendering/paragraph.dart/RenderParagraph:_relayoutBoundary@360266271
                    package:flutter/src/rendering/viewport.dart/RenderViewport:_offset@743057554
                    package:flutter/src/widgets/scroll_position_with_single_context.dart/ScrollPositionWithSingleContext:context
                    package:flutter/src/widgets/scrollable.dart/ScrollableState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/widgets/overscroll_indicator.dart/_StretchingOverscrollIndicatorState:_stretchController@926442496
                    package:flutter/src/widgets/overscroll_indicator.dart/_StretchController:_listeners@429329750
                    dart.core/_List:0
                    dart.core/_Closure (in _handleChange):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/transitions.dart/_AnimatedState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/notification_listener.dart/_NotificationElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/viewport.dart/_ViewportElement:_children@345042623
                    dart.core/_List:0
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/inherited_model.dart/InheritedModelElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:31
                    dart.collection/_HashMapEntry:next
                    dart.collection/_HashMapEntry:next
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/inherited_model.dart/InheritedModelElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:7
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/MultiChildRenderObjectElement:_dependencies@345042623
                    dart.collection/_HashSet:_buckets@3220832
                    dart.core/_List:6
                    dart.collection/_HashSetEntry:key
                    package:flutter/src/widgets/basic.dart/_UbiquitousInheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/material/scaffold.dart/ScaffoldMessengerState:_scaffolds@603420462
                    dart.collection/_Set:data_
                    dart.core/_List:2
                    package:flutter/src/material/scaffold.dart/ScaffoldState:_floatingActionButtonVisibilityController@603420462
                    package:flutter/src/animation/animation_controller.dart/AnimationController:_statusListeners@373091803
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:2
                    dart.core/_Closure (in _maybeNotifyStatusListeners):_context@0150898
                    @Context:0
                    package:flutter/src/animation/animations.dart/AnimationMin:first
                    package:flutter/src/material/floating_action_button_location.dart/_AnimationSwap:_statusListeners@373091803
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:1
                    dart.core/_Closure (in _maybeNotifyStatusListeners):_context@0150898
                    @Context:0
                    package:flutter/src/animation/animations.dart/AnimationMin:next
                    package:flutter/src/animation/animations.dart/CurvedAnimation:parent
                    package:flutter/src/animation/animation_controller.dart/AnimationController:_ticker@370066280
                    package:flutter/src/widgets/ticker_provider.dart/_WidgetTicker:_creator@793311458
                    package:flutter/src/material/scaffold.dart/_FloatingActionButtonTransitionState:_currentRotationAnimation@603420462
                    package:flutter/src/animation/animations.dart/TrainHoppingAnimation:_listeners@373091803
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:0
                    dart.core/_Closure (in _handleChange):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/transitions.dart/_AnimatedState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_renderObject@345042623
                    package:flutter/src/rendering/proxy_box.dart/RenderTransform:_relayoutBoundary@360266271
                    package:flutter/src/rendering/custom_layout.dart/RenderCustomMultiChildLayoutBox:_lastChild@360266271
                    package:flutter/src/rendering/stack.dart/RenderStack:debugCreator
                    package:flutter/src/widgets/framework.dart/DebugCreator:element
                    package:flutter/src/widgets/framework.dart/MultiChildRenderObjectElement:_ancestorRenderObjectElement@345042623
                    package:flutter/src/widgets/framework.dart/MultiChildRenderObjectElement:_children@345042623
                    dart.core/_List:1
                    package:flutter/src/widgets/framework.dart/ParentDataElement:_child@345042623
                    package:flutter/src/widgets/inherited_model.dart/InheritedModelElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:3
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatelessElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/inherited_model.dart/InheritedModelElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:1
                    dart.collection/_HashMapEntry:next
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/material/ink_well.dart/_InkResponseState:_actionMap@561059085
                    dart.collection/_Map:[InstanceRef id: classes/4656/types/0, kind: Type, identityHashCode: 3491188443, classRef: [ClassRef id: classes/48, name: _Type, library: [LibraryRef id: libraries/@0150898, name: dart.core, uri: dart:core]]]
                    package:flutter/src/widgets/actions.dart/CallbackAction:_listeners@819441002
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:0
                    dart.core/_Closure (in _handleActionChanged):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/actions.dart/_ActionsState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/InheritedElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/widgets/focus_scope.dart/_FocusState:_internalNode@834492240
                    package:flutter/src/widgets/focus_manager.dart/FocusNode:_parent@833042876
                    package:flutter/src/widgets/focus_manager.dart/FocusScopeNode:_parent@833042876
                    package:flutter/src/widgets/focus_manager.dart/FocusNode:_children@833042876
                    dart.core/_GrowableList:0
                    package:flutter/src/widgets/focus_manager.dart/FocusScopeNode:_children@833042876
                    dart.core/_GrowableList:1
                    package:flutter/src/widgets/focus_manager.dart/FocusNode:_ancestors@833042876
                    dart.core/_GrowableList:11
                    package:flutter/src/widgets/focus_manager.dart/FocusNode:_context@833042876
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/inherited_notifier.dart/_InheritedNotifierElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:6
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/inherited_notifier.dart/_InheritedNotifierElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:0
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/inherited_notifier.dart/_InheritedNotifierElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:0
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/inherited_notifier.dart/_InheritedNotifierElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:3
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/inherited_notifier.dart/_InheritedNotifierElement:_dependents@345042623
                    dart.collection/_HashMap:_buckets@3220832
                    dart.core/_List:4
                    dart.collection/_HashMapEntry:key
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_renderObject@345042623
                    package:flutter/src/rendering/proxy_box.dart/RenderSemanticsAnnotations:_child@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderPointerListener:_child@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderAbsorbPointer:_child@360266271
                    package:flutter/src/widgets/overlay.dart/_RenderTheater:_lastChild@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderSemanticsAnnotations:_child@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderOffstage:_child@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderSemanticsAnnotations:_child@360266271
                    package:flutter/src/rendering/proxy_box.dart/RenderRepaintBoundary:_child@360266271
                    package:flutter/src/widgets/snapshot_widget.dart/_RenderSnapshotWidget:_painter@823188970
                    package:flutter/src/material/page_transitions_theme.dart/_ZoomEnterTransitionPainter:animation
                    package:flutter/src/animation/animations.dart/ProxyAnimation:_statusListeners@373091803
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:0
                    dart.core/_Closure (in onAnimationStatusChange):_context@0150898
                    @Context:0
                    package:flutter/src/material/page_transitions_theme.dart/_ZoomEnterTransitionState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/SingleChildRenderObjectElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/material/page_transitions_theme.dart/_ZoomExitTransitionState:delegate
                    package:flutter/src/material/page_transitions_theme.dart/_ZoomExitTransitionPainter:animation
                    package:flutter/src/animation/animations.dart/ProxyAnimation:_parent@371411118
                    package:flutter/src/animation/animations.dart/ReverseAnimation:parent
                    package:flutter/src/animation/animations.dart/ProxyAnimation:_parent@371411118
                    package:flutter/src/animation/animation_controller.dart/AnimationController:_statusListeners@373091803
                    package:flutter/src/foundation/observer_list.dart/ObserverList:_list@441023516
                    dart.core/_GrowableList:0
                    dart.core/_Closure (in _handleStatusChanged):_context@0150898
                    @Context:0
                    package:flutter/src/material/page.dart/MaterialPageRoute:_modalScope@799188637
                    package:flutter/src/widgets/overlay.dart/OverlayEntry:_overlay@863319124
                    package:flutter/src/widgets/overlay.dart/OverlayState:_element@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/overlay.dart/_TheaterElement:_children@345042623
                    dart.core/_List:1
                    package:flutter/src/widgets/framework.dart/StatefulElement:_child@345042623
                    package:flutter/src/widgets/framework.dart/StatefulElement:_state@345042623
                    package:flutter/src/widgets/ticker_provider.dart/_TickerModeState:_effectiveMode@793311458
                    package:flutter/src/foundation/change_notifier.dart/ValueNotifier:_listeners@429329750
                    dart.core/_List:0
                    dart.core/_Closure (in _updateTickers):_context@0150898
                    @Context:0
                    package:flutter/src/widgets/navigator.dart/NavigatorState:_history@31124995
                    dart.core/_GrowableList:0
                    package:flutter/src/widgets/navigator.dart/_RouteEntry:lastAnnouncedPoppedNextRoute
                    package:flutter/src/material/page.dart/MaterialPageRoute:_restorationScopeId@31124995
                    package:flutter/src/foundation/change_notifier.dart/ValueNotifier
          
          
)
```

**Comment by polina-c** [comment]
Thanks! 
This means reverence to `MaterialPageRoute` where the method `dispose` is located (see the tail of the retaining path), is never released. Can it be released?

**Comment by gspencergoog** [comment]
> This means reverence to MaterialPageRoute where the method dispose is located (see the tail of the retaining path), is never released. Can it be released?

The leak does indeed seem to involve [`_RouteEntry.lastAnnouncedPoppedNextRoute`](https://github.com/gspencergoog/flutter/blob/about_leak/packages/flutter/lib/src/widgets/navigator.dart#L2869): when I remove that variable entirely (along with its functionality), the leak goes away.

I tried converting it to nullable and nulling it in [`_RouteEntry.dispose`](https://github.com/gspencergoog/flutter/blob/about_leak/packages/flutter/lib/src/widgets/navigator.dart#L3076) (really in [`_RouteEntry.forcedDispose`](https://github.com/gspencergoog/flutter/blob/about_leak/packages/flutter/lib/src/widgets/navigator.dart#L3063), which is called from the `dispose`), but that doesn't prevent the leak. I also tried keeping it non-nullable and just setting it back to its initial value in dispose, which still leaked a `MaterialPageRoute`, which is not the type of the initial value.  If I try and call `dispose` on the leaked object (`lastAnnouncedPoppedNextRoute`), then it leaks two instances of the ID instead of one, which is confusing to me.

Any other ideas?

**Comment by polina-c** [comment]
`_RouteEntry.lastAnnouncedPoppedNextRoute` should be nulled before or at the same time with disposal of `lastAnnouncedPoppedNextRoute`, not parent's disposal. 
It seems some other object owns and disposes lastAnnouncedPoppedNextRoute. 

Will it make sense for lastAnnouncedPoppedNextRoute to be converted to WeakRef, so that it can be garbage collected when it is not needed to other objects?

**Comment by gspencergoog** [comment]
> Will it make sense for lastAnnouncedPoppedNextRoute to be converted to WeakRef, so that it can be garbage collected when it is not needed to other objects?

Yes, I think that would make sense.  If I read the code right, it doesn't really own the object, it's just using it to compare to a later result.

Converting it to a `WeakReference<Route<dynamic>>` indeed causes the leak to be fixed.

**Comment by gspencergoog** [comment]
Yeah, I'm still looking at the Google failures.  They are very cryptic, and only occur on three tests. I would be tempted to say that they are unrelated, but they do include a reference to one of the classes I modified, so it's likely that there is a connection, I just can't see it yet.

**Comment by gspencergoog** [comment]
_Sigh._  I can't use a `WeakReference` because the version of Firefox that is used in Google testing doesn't support `WeakRef`, and that is what `WeakReference` is instantiated as in JavaScript.

@polina-c Any other suggestions for the `_RouteEntry` leak?

**Comment by polina-c** [comment]
> _Sigh._ I can't use a `WeakReference` because the version of Firefox that is used in Google testing doesn't support `WeakRef`, and that is what `WeakReference` is instantiated as in JavaScript.
> 
> @polina-c Any other suggestions for the `_RouteEntry` leak?

Wow! This means WeakReference cannot be used in Flutter Framework at all, right? Is there bug for it? 

There are options how we can move forward the fix:
1. Return to original option to null the reference in dispose. This will mean the leak will still exist, but it will be smaller and for now will not be detected. It will get detected when I add leak tracking instrumentation for routs, and I will need to deal with this issue.
2. Null the reference at the moment of disposal of lastAnnouncedPoppedNextRoute. The tricky part is how to detect it.
3. Instead of storing link to lastAnnouncedPoppedNextRoute, is it possible to store some string or int id of the route? 

First option is simple, two others are tricky, but better. If you do not see possibility for 2 or 3, let' go with 1.

Thank you for investigation!

**Comment by polina-c** [comment]
Just had chat with @jacob314 . He suggested the fix may be simple: WeakReference should convert to noop for Firefox.
@sigmundch , can you help to navigate it?

**Comment by jacob314** [comment]
@yjbanov what is the oldest version of FireFox we are trying to support with Flutter Web?
FireFox has supported WeakRef since July 2020 (version 79). If we want to support that old a version of FireFox with FlutterWeb then I agree we should add a polyfill to the Dart core libraries for WeakRef that is a no-op. If not, we should update our test lab to use a newer version of FireFox.
References:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79

**Comment by sigmundch** [comment]
That was exactly going to be my suggestion @jacob314 

The [flutter supported platforms doc](https://docs.flutter.dev/reference/supported-platforms) indicates that our support starts from FF 99+. Internally some apps do support FF 85, so I think it would be fair to bump it at least to FF 85, but could be as far as FF 99.

In the past, due to issues with Geckodriver, our team did something similar and bumped from FF 63 to FF 72. At that point in time FF 72 was the min version supported for flutter web, which is why I think we are using 72 on those tests at the moment. See cl/456802232.

**Comment by polina-c** [comment]
Thanks.
flutter/contrib/cached_network_image/BUILD is already at 114

Bumped hello_flutter: cl/551925539

**Comment by polina-c** [comment]
CL got blocked by stacktrace parsing issue in Flutter: https://github.com/flutter/flutter/issues/131627

**Comment by polina-c** [comment]
Issue for debug mode in Firefox: https://github.com/flutter/flutter/issues/132439
