### PR TITLE
Fix ZoomPageTransitionsBuilder hardcoded fill color

### LINKED ISSUE #115275: ZoomPageTransitionsBuilder black flickering on top
I noticed a black area that shows up for a short amount of time on navigation.

https://user-images.githubusercontent.com/26410357/201684926-58cc5521-c3cc-47e4-8c59-a9bdcadcd4a0.mov

Shouldn't it be the default scaffold color that is visible while the navigation is in progress or something similar?

### LINKED ISSUE #116127: Android zoom page transition display scrim in an odd position when there are nested navigators.
Run on Android and tab between PageOne and PageTwo, notice the scrim darkens the screen in an unexpected manner. [b/260364434](https://b.corp.google.com/260364434)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MainPage(),
    );
  }
}

class MainPage extends StatelessWidget {
  final navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          Expanded(
            child: Navigator(
              key: navigatorKey,
              onGenerateRoute: (route) => MaterialPageRoute(
                    settings: route,
                    builder: (context) => PageOne(),
                  ),
            ),
          ),
          BottomNavigationBar(navigatorKey)
        ],
      ),
    );
  }
}

class BottomNavigationBar extends StatelessWidget {
  final GlobalKey<NavigatorState> navigatorKey;

  BottomNavigationBar(this.navigatorKey) : assert(navigatorKey != null);

  Future<void> push(Route route) {
    return navigatorKey.currentState!.push(route);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blue,
      child: ButtonBar(
        alignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          TextButton(
            child: Text("PageOne", style: TextStyle(color: Colors.red)),
            onPressed: () {
              push(MaterialPageRoute(builder: (context) => PageOne()));
            },
          ),
          TextButton(
            child: Text("PageTwo", style: TextStyle(color: Colors.red)),
            onPressed: () {
              push(MaterialPageRoute(builder: (context) => PageTwo()));
            },
          )
        ],
      ),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Text("Page One"),
          TextButton(
            onPressed: (){
              Navigator.of(context).pop();
            },
            child: Text("Pop"),
          ),
        ],
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Text("Page Two"),
          TextButton(
            onPressed: (){
              Navigator.of(context).pop();
            },
            child: Text("Pop"),
          ),
        ],
      ),
    );
  }
}
```

### LINKED ISSUE #126682: [go_router] ShellRoute transition flickers dark when you switch between routes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run [shell_route_example](https://github.com/flutter/packages/blob/main/packages/go_router_builder/example/lib/shell_route_example.dart), or any example that has a `ShellRoute`.
2. Navigate between routes (in this example a `BottomNavigationBar`).
3. Watch the screen flickering and status bar adapting.

Running on a Xiaomi Redmi 9S Android 12 in dark mode.
In normal routes `GoRoute` this problem does not seems to happen.

### Expected results

No flickering.

### Actual results

When we navigate between routes the screen flickers dark.
Even worse this makes status bar re-render white and black.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'shell_route_example.g.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  App({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router,
      );

  final GoRouter _router = GoRouter(
    routes: $appRoutes,
    initialLocation: '/foo',
  );
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('foo')),
      );
}

@TypedShellRoute<MyShellRouteData>(
  routes: <TypedRoute<RouteData>>[
    TypedGoRoute<FooRouteData>(path: '/foo'),
    TypedGoRoute<BarRouteData>(path: '/bar'),
  ],
)
class MyShellRouteData extends ShellRouteData {
  const MyShellRouteData();

  @override
  Widget builder(
    BuildContext context,
    GoRouterState state,
    Widget navigator,
  ) {
    return MyShellRouteScreen(child: navigator);
  }
}

class FooRouteData extends GoRouteData {
  const FooRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const FooScreen();
  }
}

class BarRouteData extends GoRouteData {
  const BarRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const BarScreen();
  }
}

class MyShellRouteScreen extends StatelessWidget {
  const MyShellRouteScreen({required this.child, super.key});

  final Widget child;

  int getCurrentIndex(BuildContext context) {
    final String location = GoRouter.of(context).location;
    if (location == '/bar') {
      return 1;
    }
    return 0;
  }

  @override
  Widget build(BuildContext context) {
    final int currentIndex = getCurrentIndex(context);
    return Scaffold(
      body: child,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: currentIndex,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Foo',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Bar',
          ),
        ],
        onTap: (int index) {
          switch (index) {
            case 0:
              const FooRouteData().go(context);
              break;
            case 1:
              const BarRouteData().go(context);
              break;
          }
        },
      ),
    );
  }
}

class FooScreen extends StatelessWidget {
  const FooScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Text('Foo');
  }
}

class BarScreen extends StatelessWidget {
  const BarScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Text('Bar');
  }
}

@TypedGoRoute<LoginRoute>(path: '/login')
class LoginRoute extends GoRouteData {
  const LoginRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const LoginScreen();
}

class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Text('Login');
  }
}
```

</details>

### Screenshots or Video

Video demonstration

https://github.com/flutter/flutter/assets/43851289/5ab8b373-f5a8-4e7b-b998-642eafa4f5a7

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale pt-PT)
    • Flutter version 3.10.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at C:\Users\Eu\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33130.400
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.77.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.65.20230510

[√] Connected device (4 available)
    • Redmi Note 9S (mobile) • 14f27be • android-arm64  • Android 12 (API 31)
    • Windows (desktop)      • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)           • chrome  • web-javascript • unknown
    • Edge (web)             • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by dy0gu**
Fixes: #115275
Fixes: #116127
Fixes: #126682

Continuing on: #139078 (Credits to @LowLevelSubmarine for his initial work!)

When using `ZoomPageTransitionsBuilder`, which is the default for `ThemeData` with a `MaterialApp`, dark edges would show around the exiting page that was being zoomed out in the background. Other times, a scrim (what looked like a slightly transparent dark overlay over the page) would appear. 

After some experimenting it was concluded that, in the first case, this was because both pages don't fully fill the enclosing scaffold area during the transition and the color for filling the remaining space was set hard coded as `Colors.black`. The second case (scrim) happens when navigating from a page with an enclosing scaffold to a nested one, without a scaffold, unlike the first case that happens when both pages have a (different) enclosing scaffold, except this time it would be the hard coded color covering the page with a slight opacity reduction.

### Changes

- Replaced the hard coded color for transition filling with the current `ThemeData.colorScheme.surface`

- Added a RenderBox based test to verify the correct color is being used in the transition.

## Preview

**Before, notice the dark outline flash when navigating to the first page and the scrim when navigating to the second:**

https://github.com/user-attachments/assets/b4cc8658-1008-49f4-8553-abd5fcc72989

**After, using the theme relative color (in this case the default white) to replace the hard coded value:**

https://github.com/user-attachments/assets/b70f42d2-6246-4964-99d1-34ff8051ab06

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation.
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 1]
```diff
@@ -270,6 +270,7 @@ class _ZoomPageTransition extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
+    final Color backgroundColor = Theme.of(context).canvasColor;
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:273]: Why `canvasColor` over `primaryColor` or `scaffoldBackgroundColor`?

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 2]
```diff
@@ -519,4 +524,108 @@ void main() {
...
+          theme: ThemeData(
+            canvasColor: const Color.fromARGB(255, 255, 0, 0),
+            primarySwatch: Colors.blue,
+          ),
+          routes: routes,
+        ),
+      ),
+    );
+
+    // Verify initial page
```
Comment (victorsanni) [inline packages/flutter/test/material/page_transitions_theme_test.dart:595]: Nit: All comments should end in a period.

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 1 above)
Comment (dy0gu) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:273]: Great question!

I never considered `primaryColor` because I see it as a color with a much more "major"  role that the other options which could lead to harder migration for people with existing transitions impacted by this change.

I did however consider changing it to `scaffoldBackgroundColor` as they serve very similiar purposes and are more obscure properties but ended up keeping the `canvasColor`. However, it's a change I would totally go for if anyone else has the same opinion.

File: packages/flutter/test/material/page_transitions_theme_test.dart (hunk 2 above)
Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart:595]: I was under the impression that comments ending with a period were only for public facing documentation, I even looked at the other comments in the file and saw some without. Can you confirm they are indeed supposed to use periods?

Comment (victorsanni) [reply packages/flutter/test/material/page_transitions_theme_test.dart:595]: I should have mentioned it's an uber nit. It's especially important in public documentation, but should probably also be used for non-public comments too: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#leave-breadcrumbs-in-the-comments, https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#use-correct-grammar

Although I would agree there isn't a style guide example for regular comments per se.

Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart:595]: Sounds good, will change 👍

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 3]
```diff
@@ -519,4 +524,108 @@ void main() {
...
+
+    // Pump till animation is half-way through
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds:75));
+
+    // Use golden file to check canvas color presence
+    await expectLater(
+      find.byType(RepaintBoundary).first,
+      matchesGoldenFile('page_transitions_theme.zoom_page_canvas.scaffolded.png'),
+    );
```
Comment (bleroux) [inline packages/flutter/test/material/page_transitions_theme_test.dart:610]: As you might know, golden tests are a pain:
- they can be broken by changes not related to this particular test (for instance typography changes).
- the golden infrastructure is sometimes difficult to work with.

We should try to replace those golden tests with something such as:
```dart
    final RenderBox renderBox = ** query the right render box **;
    expect(renderBox, paints..rect(color: expectedColor));
```

Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart:610]: Makes sense, I'll try to do them using `RenderBox`!

By the way, would you be willing to give your opinion on changing the use of `canvasColor` to `scaffoldBackgroundColor` as discussed above? If two maintainers agree it's a better choice I can get everything out of the way in one sitting.

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:273]: Yes very good point.
After discussing with @TahaTesser, he mentionned that `scaffoldBackgroundColor` will be deprecated, see https://github.com/flutter/flutter/issues/91772.
One can also notice that `canvasColor` is also part of this list. After reading https://github.com/flutter/flutter/pull/116350, I think we should code with `colorScheme.background`.

Comment (dy0gu) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:273]: Will do!

Comment (dy0gu) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:273]: Just a quick note, I'm going to use `colorScheme.surface` as `colorScheme.background` is also deprecated:

image

https://api.flutter.dev/flutter/material/ColorScheme/background.html

File: packages/flutter/test/material/page_transitions_theme_test.dart (hunk 3 above)
Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart]: All done, thanks for the suggestion, had no idea you could query `RenderBox ` like that. It even ends up looking much more clean and readable that using golden files!

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 4]
```diff
@@ -519,4 +519,109 @@ void main() {
...
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds:125));
+
+    // Verify that the render box is painting the right color for non-scaffolded pages.
+    final RenderBox nonScaffoldedRenderBox = tester.firstRenderObject<RenderBox>(find.byType(RepaintBoundary));
+    // Expect the color to be at exactly 59.6% opacity at this time.
+    expect(nonScaffoldedRenderBox, paints..rect(color: themeTestSurfaceColor.withOpacity(0.596)));
+
+    await tester.pumpAndSettle();
+
```
Comment (bleroux) [inline packages/flutter/test/material/page_transitions_theme_test.dart:625]: Small nit, Consider removing this empty line.

**Review by bleroux — APPROVED** [review]
LGTM! with a very minor nit.
Thanks for your work.

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 5]
```diff
@@ -519,4 +519,108 @@ void main() {
...
+    // Pump till animation is half-way through.
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds:125));
+
+    // Verify that the render box is painting the right color for non-scaffolded pages.
+    final RenderBox nonScaffoldedRenderBox = tester.firstRenderObject<RenderBox>(find.byType(RepaintBoundary));
+    // Expect the color to be at exactly 59.6% opacity at this time.
+    expect(nonScaffoldedRenderBox, paints..rect(color: themeTestSurfaceColor.withOpacity(0.596)));
+
+    await tester.pumpAndSettle();
```
Comment (victorsanni) [inline packages/flutter/test/material/page_transitions_theme_test.dart:624]: is this `pumpAndSettle` necessary? Just making sure you've considered that.

File: packages/flutter/test/material/page_transitions_theme_test.dart [hunk 6]
```diff
@@ -519,4 +519,108 @@ void main() {
...
+  }, variant: TargetPlatformVariant.only(TargetPlatform.android));
```
Comment (victorsanni) [inline packages/flutter/test/material/page_transitions_theme_test.dart:625]: Is the target platform being Android required? Just confirming there aren't any other platforms this issue occurs in.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/material/page_transitions_theme_test.dart (hunk 5 above)
Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart:624]: Not strictly, I just saw some other tests doing it and liked the fact that it leaves the test in a completely "finished" state. In fact, I should probably check for the correct text on the last page after the settle too. That or we can just remove it if you want 👍

File: packages/flutter/test/material/page_transitions_theme_test.dart (hunk 6 above)
Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart:625]: I also experienced it on the Web along with Android, can't speak for IOS or native desktop. 

I guess I set it to Android because it's the default for Material theme, but I'll go ahead and change it to all since any platform can call material transitions.

Comment (dy0gu) [reply packages/flutter/test/material/page_transitions_theme_test.dart]: I'm now forcing all platforms to use ZoomPageTransitionsBuilder in the app and testing on all of them. Let me know if you think it's overkill!

**Comment by dy0gu** [comment]
Hey! Any updates on what is still needed for this to get merged?

**Comment by victorsanni** [comment]
> Hey! Any updates on what is still needed for this to get merged?

Some google tests are failing. I am working to get it merged.

**Review by MitchellGoodwin — COMMENTED** [review]
There's another PR that seems to be fixing the same issue at #152815.

A question I have: is there a case were somebody may want a different color for the background/scrim than what comes from the theme? The other PR has an argument for the builder itself, so that can be set in the PageTransitionsTheme separate from the other color in the theme. So it might be good to add a parameter to ZoomTransitionBuilder similar to the other PR. But going further, would there be a need to set a different color for different pages in an app? I don't think wrapping different pages with a new theme would work.

**Comment by dy0gu** [comment]
> There's another PR that seems to be fixing the same issue at #152815.
> 
> A question I have: is there a case were somebody may want a different color for the background/scrim than what comes from the theme? The other PR has an argument for the builder itself, so that can be set in the PageTransitionsTheme separate from the other color in the theme. So it might be good to add a parameter to ZoomTransitionBuilder similar to the other PR. But going further, would there be a need to set a different color for different pages in an app? I don't think wrapping different pages with a new theme would work.

Just took a peek over there, you're right, they seem to be doing the same. I'm all for more customization so I actually like the approach of it being a parameter. I would, however, keep the color we chose here as the default if none is passed.

I saw they are struggling with testing the change, I don't believe it is worth keeping both PRs so that PR  should copy my test and add the color discussed here as the default or I add the ZoomPageBuilder parameter on this PR, if we are to keep their idea. Both are fine by me, let me know what you think.

**Comment by MitchellGoodwin** [comment]
I think after thinking about it more, let's get this PR merged as is, and the other PR can build on top of it.

The other case I mentioned can wait to see if it actually becomes an issue.

**Comment by victorsanni** [comment]
For the Google testing failures, I reached out to both scuba owners, and they've approved updating the scubas with the changes in this PR. So we can go ahead and merge this PR irrespective of those failures.

**Review by MitchellGoodwin — APPROVED** [review]

**Comment by walidwalid23** [comment]
Hello I am currently facing the same Issue on latest Flutter version 3.24.2, when is this merge expected to be reflected in flutter? thank you

**Comment by MitchellGoodwin** [comment]
> Hello I am currently facing the same Issue on latest Flutter version 3.24.2, when is this merge expected to be reflected in flutter? thank you

While it's available on master now, it will be in the next major stable build.

**Comment by dingshaohua-com** [comment]
> Hello I am currently facing the same Issue on latest Flutter version 3.24.2, when is this merge expected to be reflected in flutter? thank you

try lasted version，like [v3.27.1](https://storage.flutter-io.cn/flutter_infra_release/releases/stable/macos/flutter_macos_3.27.1-stable.zip) is okey
