### PR TITLE
Text Editing Movement Keys via Shortcuts

### LINKED ISSUE #76121: In a TextField HOME and END keys do not work on platform Windows
## Steps to Reproduce

When pressing physical keyboard keys HOME or END in a TextField on **platform Windows**, the cursor does not move anywhere.

### Consider this example

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Text Edit',
      home: _TextFieldExample(),
    );
  }
}

class _TextFieldExample extends StatefulWidget {
  @override
  _TextFieldExampleState createState() => _TextFieldExampleState();
}

class _TextFieldExampleState extends State<_TextFieldExample> {
  final FocusNode _focusNode = FocusNode();
  final TextEditingController _textController = TextEditingController();

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SizedBox(
              width: 400,
              child: TextField(
                controller: _textController,
                focusNode: _focusNode,
                decoration: InputDecoration(
                  hintText: 'Write something, then press HOME and END key',
                  border: const OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Expected results

* HOME pressed  -> **Expect:** Cursor moves to first char position when there is some text in the field.
* END pressed  -> **Expect:** Cursor moves to last char position when there is some text in the field.

### Actual results

* HOME pressed -> **Actual:** Cursor does not move anywhere.
* END pressed -> **Actual:** Cursor does not move anywhere.

### Tested on

**Platform WINDOWS**
Channel master, 1.27.0-2.0.pre.103 : **FAIL**
Channel dev, 1.27.0-1.0.pre : **FAIL**

**Platform WEB**
Channel master, 1.27.0-2.0.pre.103 : **OK**
Channel dev, 1.27.0-1.0.pre : **OK**
Channel beta, 1.26.0-17.5.pre: **OK**

Works **OK on Web**, but **FAILS on Windows**.

This issue should also be tested on platforms **macOS** and **Linux** to ensure it does not appear on them as well.
**EDIT:** 
Based on Twitter feedback it works OK on **macOS**: https://twitter.com/tomgilder/status/1361730262791557121?s=20

----

### Disclaimer
Platform **Windows** is not ready and only on **dev channel** (alpha), but as it moves closer to being more ready, issues like these will eventually need to be resolved. 

<details>
  <summary>Flutter DOCTOR</summary>

```

[√] Flutter (Channel master, 1.27.0-2.0.pre.103, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.27.0-2.0.pre.103 at C:\Users\mryds\fvm\versions\master
    • Framework revision f49956598b (10 hours ago), 2021-02-16 00:56:06 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (5 available)
    • Nexus 7 (mobile)  • 0a99f5e8    • android-arm    • Android 6.0.1 (API 23)
    • SM T510 (mobile)  • R52N906MLAV • android-arm    • Android 10 (API 29)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

```
</details>

### PR DESCRIPTION
**Pull request by justinmc**
This is the first PR to start migrating text editing to use Actions.  See the [design doc](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#) for the entire plan.

This PR focuses only on the arrow keys, including all modifier keys, but it also establishes the pattern for handling all keyboard, mouse, and touch events for text editing.

### Example

This example shows how to use an additional Shortcuts widget to override some default text editing keyboard shortcuts to have new behavior. Instead of moving the cursor, alt + up/down will change the focused widget.  See the [docs](https://master-api.flutter.dev/flutter/widgets/DefaultTextEditingShortcuts-class.html) for more examples.

```dart
@override
Widget build(BuildContext context) {
  // If using WidgetsApp or its descendents MaterialApp or CupertinoApp,
  // then DefaultTextEditingShortcuts is already being inserted into the
  // widget tree.
  return DefaultTextEditingShortcuts(
    child: Center(
      child: Shortcuts(
        shortcuts: const <ShortcutActivator, Intent>{
          SingleActivator(LogicalKeyboardKey.arrowDown, alt: true): NextFocusIntent(),
          SingleActivator(LogicalKeyboardKey.arrowUp, alt: true): PreviousFocusIntent(),
        },
        child: Column(
          children: const <Widget>[
            TextField(
              decoration: InputDecoration(
                hintText: 'alt + down moves to the next field.',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'And alt + up moves to the previous.',
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
```

### Issues

Partial fix for https://github.com/flutter/flutter/issues/75004.
Closes https://github.com/flutter/flutter/issues/76121

### Tests

  * Test that it's possible to remap a shortcut to a different shortcut's Intent.
  *  Test that's possible to write a custom Action to completely change a text editing Intent's behavior.
  * Update RenderEditable tests that relied on the keyboard and have them call new methods instead.

### Breaking changes
None.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+/// An [Action] related to editing text.
+///
+/// If an [EditableText] is currently focused, the given [onInvoke] callback
+/// will be called with the [EditableTextState]. If not, then [isEnabled] will
+/// be false and [onInvoke] will not be called.
+///
+/// The focused [EditableText] must have a [Key]. This is handled automatically
+/// by built-in text editing widgets like [TextField], [CupertinoTextField],
+/// and [SelectableText], but for custom usage of [EditableText], it is
+/// necessary to explicitly pass in a key.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:24]: Any concern about this?

I needed a way to get the EditableTextState and RenderEditable from the actions.  The way I chose to do it was by looking at the primaryFocus.  See the `_editableTextState` getter below.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 2]
```diff
@@ -0,0 +1,584 @@
...
+
+  /// The child [Widget] of TextEditingActions.
+  final Widget child;
+
+  /// The actions to be merged with the default text editing actions.
+  ///
+  /// The default text editing actions will override any conflicting keys in
+  /// additionalActions. To override the default text editing actions, use an
+  /// [Actions] Widget in the tree below this Widget.
+  final Map<Type, Action<Intent>> additionalActions;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:99]: I'm interested to know thoughts on this.  Instead of having this parameter, I could just use an additional Actions widget in widgets/app.dart.

**Comment by venkatd** [comment]
@justinmc want to confirm that, if merged, this would allow us to override the arrow keys in shortcuts. We have the following code for a `ChatMessageComposer` widget which wraps a TextField. At the highest level, we've got the following shortcuts:

```dart
    return FocusableActionDetector(
      shortcuts: {
        LogicalKeySet(LogicalKeyboardKey.arrowDown):
            const ListViewSelectionIntent(ListViewSelectionOption.next),
        LogicalKeySet(LogicalKeyboardKey.arrowUp):
            const ListViewSelectionIntent(ListViewSelectionOption.prev),
        LogicalKeySet(LogicalKeyboardKey.tab):
            const ListViewSelectionIntent(ListViewSelectionOption.select),
        LogicalKeySet(LogicalKeyboardKey.enter):
            const ChatComposerIntent(ChatComposerAction.send),
      },
...
```

And our UI when mentioning a user looks like this:
image

The tab key seems to work fine but the up/down arrow default handling isn't suppressed. Whenever a mention ListView is visible, we'd want the up/down arrow keys only to navigate the selected item.

Thanks!

**Comment by justinmc** [comment]
@venkatd Yes that's exactly what this PR would enable!  Currently movement keys (and some others) are handled in a RawKeyListener inside of RenderEditable, which is why your code above can't override their behavior.  In this PR I'm deleting the movement code in that RawKeyListener and moving it to Shortcuts.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+  /// Must not be null.
+  @protected
+  final _OnInvokeTextEditingCallback<T> onInvoke;
+
+  @override
+  Object? invoke(covariant T intent) {
+    // _editableTextState shouldn't be null because isEnabled will return false
+    // and invoke shouldn't be called if so.
+    assert(_editableTextState != null);
+    return onInvoke(intent, _editableTextState!);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:64]: Are we ok with passing EditableTextState to onInvoke here?  I also tried instead setting it as a property on the intent here, but it seemed like that wouldn't work for multiple invocations since Intents are immutable.  Any better way to do this?

**Comment by venkatd** [comment]
@justinmc that's great! This is going to be a pretty high value add for our product:

- Various dropdowns with autocomplete that require arrow key traversal of the options
- Mentions of users and other entities
- Shortcut heavy chat composer

Was trying various hacks to override this stuff like saving/reverting cursor positions, but seems like it's worth waiting for this and swapping over to the dev branch when it's ready.

Subscribing...

**Comment by justinmc** [comment]
@venkatd For autocomplete, also take a look at the new [Autocomplete](https://github.com/flutter/flutter/pull/73753) widget which is getting keyboard shortcuts thanks to @shihaohong.

**Comment by shihaohong** [comment]
@venkatd Once I have a PR ready for it, I can cc/ you in on it so you can give it a go and provide some feedback if you like!

**Comment by venkatd** [comment]
Thanks @justinmc !

@shihaohong sounds good! Our current use case may be slightly different because we have very custom needs for our chat message composer. This includes:

- Detecting when users type types in natural language
- Switching on type (@ to mention users and # to mention tasks)

The ideal use case for us is allowing us to compose some of the hard parts like:
- Responding to text editor changes and shortcut keys to update a ValueNotifer to build our search results by hand
- Anchoring a floating widget relative to a target widget that updates in response to those changes. Can inject these same results into this floating widget. For our chat composer, this widget needs to be anchored topLeft-bottomLeft with the widget of the composer.

I think we do have some situations that could make use of a drop-in autocomplete replacement but several may call for custom code. Either way happy to jump in when it's ready and explain where it may may not fit our use case so you can decide if what we need is out of scope.

**Comment by Quijx** [comment]
I am having an issue where I have a `TextField` inside of an `FocusableActionDetector` which detects the Ctrl-A shortcut. However when the `TextField` is focused an I press Ctrl-A, all text is selected and the action is invoked. But the `TextField` should consume the shortcut and the action should only be invoked if the `FocusableActionDetector` or some child that does not have an action for `Ctrl-A` is focused.

Does this PR implicitly resolve that issue?

**Comment by venkatd** [comment]
@Quijx I'm not 100% aware of the details, but it's related.

You can take a look at this file to see what hardcoded keys are being converted to shortcuts:
https://github.com/flutter/flutter/pull/75032/files#diff-96d0621673d5a812dcd257740948d72ed9fb1a31f1ea06df54617a265e926bda

Anything that's converted to a shortcut can be overridden. I don't see Ctrl-A in this PR, but I'm sure it'll either be added here or in a future PR. Once it's in there, you should be able to override the default OS behavior.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_actions.dart:41]: Same question for TextEditingShortcuts.additionalShortcuts as well.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 4]
```diff
@@ -4114,8 +4119,8 @@ void main() {
       selection,
       equals(
         const TextSelection(
-          baseOffset: 20,
-          extentOffset: 55,
+          baseOffset: 0,
+          extentOffset: 72,
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:4123]: This test appeared to be incorrect based on my observations on Mac.  It moves the uppermost offset, not necessarily the extent.

On Windows and Ubuntu, I observed that this key combination did nothing, but I left Flutter's behavior alone, which is to do the same thing as Mac.  I'll keep this in mind as we continue to work on desktop text editing and will consider getting rid of these shortcuts.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:24]: I had to add a `key` param to some EditableText tests below because of this.

File: packages/flutter/lib/src/widgets/app.dart [hunk 5]
```diff
@@ -1624,17 +1626,19 @@ class _WidgetsAppState extends State<WidgetsApp> with WidgetsBindingObserver {
...
-            policy: ReadingOrderTraversalPolicy(),
-            child: _MediaQueryFromWindow(
-              child: Localizations(
-                locale: appLocale,
-                delegates: _localizationsDelegates.toList(),
-                child: title,
+        shortcuts: widget.shortcuts ?? WidgetsApp.defaultShortcuts,
+        child: TextEditingShortcuts(
+          child: TextEditingActions(
+            additionalActions: widget.actions ?? WidgetsApp.defaultActions,
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/app.dart:1633]: Thoughts on the additionalActions approach here?

We need to think about what the user expects to happen when they pass in `shortcuts` and `actions`.  Previously these didn't override any text editing behavior because that was handled separately.

The two nested Shortcuts widgets here (one inside of TextEditingShortcuts) can't be combined because some text editing shortcuts bubble up to the upper widget when no EditableText is focused.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 6]
```diff
@@ -742,178 +738,804 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     return 0;
   }
 
-  void _handleMovement(
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:745]: To explain this diff: The `_handleMovement` method has been removed and is now split into all of the separate methods below.

**Comment by justinmc** [comment]
@Quijx +1 to what @venkatd said.  Control-A is not in this PR but I plan to add it to TextEditingShortcuts in the next PR, as soon as I get buy-in here on this approach.  Currently it is handled [here](https://github.com/flutter/flutter/blob/7711c1ef8f478c03d12d72f790c625a194cc93b9/packages/flutter/lib/src/rendering/editable.dart#L921) in a RawKey listener, which is why it's not affected by Shortcuts.

File: packages/flutter/lib/src/widgets/text_editing_shortcuts.dart [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+/// This default behavior can be overridden by placing a [Shortcuts] widget
+/// lower in the widget tree than this. See [TextEditingActions] for an example
+/// of remapping a text editing [Intent] to a custom [Action].
+///
+/// {@tool snippet}
+///
+/// This example shows how to use an additional [Shortcuts] widget to override
+/// the left arrow key [Intent] and map it to the right arrow key instead.
+///
+/// If
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_shortcuts.dart:24]: nit: something's missing here

File: packages/flutter/lib/src/widgets/text_editing_intents.dart [hunk 8]
```diff
@@ -0,0 +1,145 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'actions.dart';
+
+/// An [Intent] representing the default text editing behavior for the current
+/// platform for the alt + arrow down key event.
+class AltArrowDownTextIntent extends Intent {}
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_intents.dart:9]: The naming seems odd, don't we usually name intents after what they do, not after what key triggers them? e.g. ScrollIntent, ActivateIntent, and so on...

File: packages/flutter/lib/src/widgets/text_editing_shortcuts.dart [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+///   text: "Try using the keyboard's arrow keys and notice that left moves right.",
+/// );
+///
+/// @override
+/// Widget build(BuildContext context) {
+///   return Scaffold(
+///     body: Center(
+///       child: Shortcuts(
+///         shortcuts: <LogicalKeySet, Intent>{
+///           LogicalKeySet(LogicalKeyboardKey.arrowLeft): ArrowRightTextIntent(),
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_shortcuts.dart:37]: re: my naming comment from above, would this be clearer as:

```suggestion
///           LogicalKeySet(LogicalKeyboardKey.arrowLeft): MoveCursorForwardTextIntent(),
```

File: packages/flutter/lib/src/widgets/text_editing_shortcuts.dart [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+/// }
+/// ```
+/// {@end-tool}
+///
+/// See also:
+///
+///  * [TextEditingActions], which contains all of the [Action]s that respond
+///    to the [Intent]s in these shortcuts with the default text editing
+///    behavior.
+class TextEditingShortcuts extends StatelessWidget {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_shortcuts.dart:54]: Should this have "default" in the name?

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+import 'editable_text.dart';
+import 'focus_manager.dart';
+import 'framework.dart';
+
+// Similar to CallbackAction's OnInvokeCallback, but includes EditableTextState.
+typedef _OnInvokeTextEditingCallback<T extends Intent> = Object? Function(T intent, EditableTextState editableTextState);
+
+/// An [Action] related to editing text.
+///
+/// If an [EditableText] is currently focused, then _editableTextState will be
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:17]: nit: public doc shouldn't reference private fields.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+/// set and the given [onInvoke] callback will be called with it. If not, then
+/// [isEnabled] will be false and [onInvoke] will not be called.
+///
+/// The focused [EditableText] must have a [Key]. This is handled automatically
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:21]: Is any Key sufficient?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:21]: Actually, from the code below it looks like you'll need a global key?

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+  Object? invoke(covariant T intent) {
+    // _editableTextState shouldn't be null because isEnabled will return false
+    // and invoke shouldn't be called if so.
+    assert(_editableTextState != null);
+    return onInvoke(intent, _editableTextState!);
+  }
+
+  @override
+  bool isEnabled(Intent intent) {
+    return !kIsWeb && _editableTextState != null;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:68]: Probably worthwhile to have a quick comment here why these are never enabled on the web.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 14]
```diff
@@ -0,0 +1,70 @@
...
+  ///
+  /// The [onInvoke] parameter must not be null.
+  TextEditingAction({required this.onInvoke}) : assert(onInvoke != null);
+
+  EditableTextState? get _editableTextState {
+    // If an EditableText is not focused, then ignore this action.
+    if (primaryFocus?.context?.widget is! EditableText) {
+      return null;
+    }
+    final EditableText editableText = primaryFocus!.context!.widget as EditableText;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:41]: if `context.widget is EditableText` then `(context as StatefulElement).state` must be the EditableTextState. So technically, you wouldn't need a key, I think.

The `is type` checks do seem a little iffy here, though... Do we already have an established pattern somewhere for only doing an action if focus is on a particular widget?

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 15]
```diff
@@ -0,0 +1,70 @@
...
+  }
+
+  /// The callback to be called when invoked.
+  ///
+  /// If an EditableText is not focused, then isEnabled will be false, and this
+  /// will not be invoked.
+  ///
+  /// Must not be null.
+  @protected
+  final _OnInvokeTextEditingCallback<T> onInvoke;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:56]: Should _OnInvokeTextEditingCallback be public then since a public member is typed with this?

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:24]: left a comment about this below.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 16]
```diff
@@ -0,0 +1,558 @@
...
+///   );
+/// }
+/// ```
+/// {@end-tool}
+///
+/// See also:
+///
+///   * [TextEditingShortcuts], which maps keyboard keys to many of the
+///     [Intent]s that are handled here.
+class TextEditingActions extends StatelessWidget {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:58]: Should this have "default" in the name?

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 17]
```diff
@@ -0,0 +1,558 @@
...
+
+  /// The child [Widget] of TextEditingActions.
+  final Widget child;
+
+  /// The actions to be merged with the default text editing actions.
+  ///
+  /// The default text editing actions will override any conflicting keys in
+  /// additionalActions. To override the default text editing actions, use an
+  /// [Actions] Widget in the tree below this Widget.
+  final Map<Type, Action<Intent>> additionalActions;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:75]: Is it important to have this feature in this widget? You could achieve the same via composition by using an Actions widget as a child, no?

File: packages/flutter/test/rendering/editable_test.dart [hunk 18]
```diff
@@ -409,58 +409,6 @@ void main() {
     expect(editable, paintsExactlyCountTimes(#drawRect, 1));
   });
 
-  test('ignore key event from web platform', () async {
```
Comment (goderbauer) [inline packages/flutter/test/rendering/editable_test.dart:412]: Do we still have tests to verify this? Or why is this no longer needed?

File: packages/flutter/lib/src/widgets/app.dart (hunk 5 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/app.dart:1633]: I found the `additionalActions` strange (as commented on in the other file).

If you pass in shortcuts and actions here, I would expect them to override the defaults from TextEditingShortcuts and TextEditingActions. Could we just use a nested Action widget?

**Review by goderbauer — COMMENTED** [review]
I haven't reviewed everything yet, just some comments from a first read-through to get familiar with the PR.

File: packages/flutter/lib/src/widgets/text_editing_intents.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart:9]: I have a bit about this in the [design doc's open questions](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#heading=h.dy33bukwh2dy).  I seem to be alone in preferring this kind of naming so I'm going to investigate changing it starting with the actions.

For the intents, my main point is that I'd like the visual text editing widgets to be ignorant of how text editing works.  This doesn't really affect these keyboard intents, but I'm also going to invoke intents from the visual text editing widgets like `Actions.invoke<SingleTapUpTextIntent>`.  If the intent is named for what it does and/or the widget decides which intent to invoke based on the platform or other things, then it's affecting business logic.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart:9]: If I change just the actions naming, this is the result: https://github.com/justinmc/flutter/blob/text-editing-refactor-action-names/packages/flutter/lib/src/widgets/text_editing_actions.dart

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 19]
```diff
@@ -0,0 +1,70 @@
...
+    if (editableText.key == null
+        || (editableText.key! as GlobalKey).currentState == null) {
+      return null;
+    }
+    return (editableText.key! as GlobalKey).currentState! as EditableTextState;
+  }
+
+  /// The callback to be called when invoked.
+  ///
+  /// If an EditableText is not focused, then isEnabled will be false, and this
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:51]: Should explain that "an EditableText" means the [primaryFocus] widget, if `primaryFocus.context.widget` is an EditableText widget.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 20]
```diff
@@ -0,0 +1,70 @@
...
+/// The focused [EditableText] must have a [Key]. This is handled automatically
+/// by built-in text editing widgets like [TextField], [CupertinoTextField],
+/// and [SelectableText], but for custom usage of [EditableText], it is
+/// necessary to explicitly pass in a key.
+///
+/// See also:
+///
+///  * [CallbackAction], which is a similar Action type but unrelated to text
+///    editing.
+class TextEditingAction<T extends Intent> extends Action<T> {
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:30]: It might make sense to make TextAction a ContextAction, since eventually I think we're going to need to discover if the _current window_ has the focus (that's an EditableText) rather than just checking primaryFocus, which I assume will correspond to all of the app's windows.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 3 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:63]: I think this make sense. Calling this method "onInvoke" doesn't seem right though, since it implies that it's a notification, rather than the action itself. Could call it invokeTextAction().

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 21]
```diff
@@ -0,0 +1,558 @@
...
+///
+/// See also:
+///
+///   * [TextEditingShortcuts], which maps keyboard keys to many of the
+///     [Intent]s that are handled here.
+class TextEditingActions extends StatelessWidget {
+  /// Creates an instance of TextEditingActions.
+  TextEditingActions({
+    Key? key,
+    Map<Type, Action<Intent>>? additionalActions,
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:62]: I thought that additional actions were to be contributed by additional Actions widgets. This seems odd.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 22]
```diff
@@ -0,0 +1,558 @@
...
+///   text: "Try using the keyboard's arrow keys and notice that left moves right.",
+/// );
+///
+/// @override
+/// Widget build(BuildContext context) {
+///   return Scaffold(
+///     body: Center(
+///       child: Actions(
+///         actions: <Type, Action<Intent>>{
+///           ArrowLeftTextIntent: TextEditingAction<ArrowLeftTextIntent>(
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:38]: Surely we can come up with a more compelling example than this.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart [hunk 23]
```diff
@@ -0,0 +1,558 @@
...
+  final Widget child;
+
+  /// The actions to be merged with the default text editing actions.
+  ///
+  /// The default text editing actions will override any conflicting keys in
+  /// additionalActions. To override the default text editing actions, use an
+  /// [Actions] Widget in the tree below this Widget.
+  final Map<Type, Action<Intent>> additionalActions;
+
+  static final TextEditingAction<AltArrowDownTextIntent> _altArrowDownTextAction = TextEditingAction<AltArrowDownTextIntent>(
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/text_editing_actions.dart:77]: By making the actions simply map one-to-one to intents, which in turn, just map to keys, I think we're discarding most of the value of the key-to-action lookup system. Why bother with intents?

File: packages/flutter/test/rendering/editable_test.dart [hunk 24]
```diff
@@ -783,15 +732,15 @@ void main() {
     editable.selection = const TextSelection.collapsed(offset: 0);
     pumpFrame();
 
-    await simulateKeyDownEvent(LogicalKeyboardKey.arrowRight, platform: 'android');
-    await simulateKeyUpEvent(LogicalKeyboardKey.arrowRight, platform: 'android');
+    editable.moveSelectionRight(SelectionChangedCause.keyboard);
     expect(currentSelection.isCollapsed, true);
     expect(currentSelection.baseOffset, 1);
+    editable.selection = currentSelection;
```
Comment (YeungKC) [inline packages/flutter/test/rendering/editable_test.dart:738]: I think this line of code is redundant because it does not need to reset the selection.

File: packages/flutter/test/rendering/editable_test.dart [hunk 25]
```diff
@@ -783,15 +732,15 @@ void main() {
     editable.selection = const TextSelection.collapsed(offset: 0);
     pumpFrame();
 
-    await simulateKeyDownEvent(LogicalKeyboardKey.arrowRight, platform: 'android');
-    await simulateKeyUpEvent(LogicalKeyboardKey.arrowRight, platform: 'android');
+    editable.moveSelectionRight(SelectionChangedCause.keyboard);
```
Comment (YeungKC) [inline packages/flutter/test/rendering/editable_test.dart:735]: I don't quite understand why we need to change this line? As I understand it we should be testing from the keyboard event instead of calling editable.moveSelectionRightFoo directly.

File: packages/flutter/test/widgets/editable_text_cursor_test.dart [hunk 26]
```diff
@@ -328,6 +328,7 @@ void main() {
     final TextEditingController controller = TextEditingController(text: testText);
     final Widget widget = MaterialApp(
       home: EditableText(
+        key: GlobalKey(),
```
Comment (YeungKC) [inline packages/flutter/test/widgets/editable_text_cursor_test.dart:331]: Why do we need to add this line? It doesn't look like it's being used?

File: packages/flutter/lib/src/widgets/text_editing_actions.dart (hunk 23 above)
Comment (venkatd) [reply packages/flutter/lib/src/widgets/text_editing_actions.dart:77]: I may be missing some nuance of the architecture, but wouldn't it be ideal to name intents based on the intent of the user?

For example ctrl+backspace may be the shortcut while the intent is delete line. Or shift+left may be the shortcut while the intent is extend selection left.

Then depending on the platform, we'd have different shortcut-intent mappings.

File: packages/flutter/lib/src/widgets/app.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/app.dart]: I've updated this to follow the behavior below.  Let me know if it sounds good.

  * Passing `actions` gets rid of all default actions and all text editing actions.
    - Not just actions with conflicting keys.  So even if you just pass a Map with one action in it, NO default actions and NO text editing actions will be registered, just that one that was passed in.
    - This is how it worked before this PR too, just without any text editing actions.
 * Same with shortcuts.
 * additionalActions was removed in favor of nested Actions widgets.

Here is the commit with the relevant code: https://github.com/flutter/flutter/pull/75032/commits/5a7f658319e200702ca17d4c0d62c52b4a98e153

File: packages/flutter/lib/src/widgets/text_editing_intents.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart]: A bunch of us met and decided on a hybrid approach.  The [open questions](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#heading=h.dy33bukwh2dy) section has been updated with a detailed explanation.

File: packages/flutter/lib/src/widgets/text_editing_shortcuts.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_shortcuts.dart:36]: Yeah that seems to be right about RTL.  I've kept all naming related to left and right, so this one is: `MoveSelectionRightTextIntent`.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart (hunk 17 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_actions.dart]: Discussion about this here: https://github.com/flutter/flutter/pull/75032#discussion_r575595911

File: packages/flutter/lib/src/rendering/editable.dart [hunk 27]
```diff
@@ -742,178 +738,804 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    return _getTextPositionVertical(offset, verticalOffset);
+  }
+
+  /// Keeping the current baseOffset fixed, move the extentOffset down by one
+  /// line.
+  ///
+  /// See also:
+  ///
+  ///   * [extendSelectionUp]
+  void extendSelectionDown(SelectionChangedCause cause) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:981]: Good catch, there was an assertion before.  I think I'll add the assertion back to each of these public methods.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 12 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:21]: Yes, I'll update the docs.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 20 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:30]: Good call, that will probably save me a breaking change in the future 👍

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 14 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:41]: The DirectionalFocusIntent seems to do it the same way.  CC @gspencergoog 

https://github.com/flutter/flutter/blob/f49956598b2a44cedcb70bd8c4b6b7ef5dc54d43/packages/flutter/lib/src/widgets/focus_traversal.dart#L1946

I'll take your suggestion of not using the key for now.

File: packages/flutter/test/widgets/editable_text_cursor_test.dart (hunk 26 above)
Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_cursor_test.dart:331]: See the discussion at https://github.com/flutter/flutter/pull/75032/files#r570529343

It seems like it's not needed anymore, so I'll remove it and the other places where I added GlobalKeys in the tests.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 14 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:41]: That usage in the `DirectionFocusIntent` was a workaround for before we had the ability to override key bindings, and the ignoreTextFields field will probably be deprecated now that we can. The `is` check was iffy at the time, but was the only solution we could think of.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 15 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:56]: Yes, good call.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:63]: I'm inheriting onInvoke from Action.  Should I leave onInvoke unimplemented and create a new invokeTextAction method?

File: packages/flutter/lib/src/widgets/text_editing_actions.dart (hunk 16 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_actions.dart:25]: Yeah you're right, since that's what this is: just Actions with the default text editing actions in it.  I'll prepend "Default" to this and also to TextEditingShortcuts.

File: packages/flutter/test/rendering/editable_test.dart (hunk 18 above)
Comment (justinmc) [reply packages/flutter/test/rendering/editable_test.dart:412]: I removed this because RenderEditable no longer handles key events at all.  Now that I look at this again though, it's probably useful to test that web doesn't trigger the text editing actions.  I'll bring this back in a way that covers that.

File: packages/flutter/test/rendering/editable_test.dart (hunk 25 above)
Comment (justinmc) [reply packages/flutter/test/rendering/editable_test.dart:735]: RenderEditable no longer has this keyboard handling, so if I use simulateKeyDownEvent etc., then it won't be affected.

At a higher level, Shortcuts will receive the keyboard event, which will call TextEditingActions, which will call RenderEditable's moveSelectionRight.  In editable_text_test.dart there are tests that cover keyboard events causing changes in selection at a high level like this.  Here, I think it's only necessary to test these methods directly.

If I was writing these tests from scratch I probably would organize them differently, though...

File: packages/flutter/test/rendering/editable_test.dart (hunk 24 above)
Comment (justinmc) [reply packages/flutter/test/rendering/editable_test.dart:738]: It will actually fail without this line.  The reason is that RenderEditable relies on EditableText to set the TextEditingController's selection when RenderEditableCalls onSelectionChanged.  So because I'm rendering a raw RenderEditable by itself here, I need to update the selection manually.

I'll add a comment about this because it is very confusing.  It took me awhile to figure this out while working on these tests.

File: packages/flutter/test/rendering/editable_test.dart (hunk 18 above)
Comment (justinmc) [reply packages/flutter/test/rendering/editable_test.dart:412]: It's now in EditableText's test, modified a bit.

File: packages/flutter/lib/src/widgets/text_editing_actions.dart (hunk 21 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_actions.dart]: I've fixed this by using nested Shortcuts and Actions widgets in widgets/app.dart and getting rid of additionalActions.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 28]
```diff
@@ -7183,6 +7183,63 @@ void main() {
 
     // On web, using keyboard for selection is handled by the browser.
   }, skip: kIsWeb);
+
+  testWidgets('ignore key event from web platform', (WidgetTester tester) async {
```
Comment (venkatd) [inline packages/flutter/test/widgets/editable_text_test.dart:7187]: @justinmc what's the reason that the key event should be ignored on the web platform?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 29]
```diff
@@ -0,0 +1,381 @@
...
+///           ],
+///         ),
+///       ),
+///     ),
+///   );
+/// }
+/// ```
+/// {@end-tool}
+///
+/// {@tool snippet}
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: @gspencergoog Examples like this won't work on web.  Does Shortcuts just not work at all on web?  Is there anything I can do to reduce this divergence in this PR?

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 28 above)
Comment (justinmc) [reply packages/flutter/test/widgets/editable_text_test.dart:7187]: Flutter web lets the browser handle text editing, so it doesn't listen to any of these things.

This could be a problem for users that add their own Intents or Shortcuts now that I think about it.  I've added a comment at https://github.com/flutter/flutter/pull/75032#discussion_r577779699 to discuss more.

**Comment by justinmc** [comment]
Ready for re-review.  Thanks to everyone for taking a look.  Some stuff to look at:

  * The biggest change is that Actions, and Intents triggered by Shortcuts, are named for what they do now. See https://github.com/flutter/flutter/pull/75032/files#diff-a7ab0a5db9b1cb96f1d25b62073b4d8bbbe0f4dfa56578bede557c528cd0c121.
  * Are we ok with the current lack of support on web?  See https://github.com/flutter/flutter/pull/75032#discussion_r577779699.
  * Is there a nice way that I can document all shortcuts?  I can just put them into the docs for TextEditingShortcuts, but I worry that the docs will get out of sync with the code.  The real source of truth are the maps like `_androidShortcuts`, etc., but these are private.
  * @HansMuller A question on your onInvoke naming suggestion: https://github.com/flutter/flutter/pull/75032/files#r577129035

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 29 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: Since you force-pushed, I can't see what example you're referring to (GitHub just says it "looked everywhere" for the changes). Shortcuts definitely should be working on the web.  For instance, [this example](https://master-api.flutter.dev/flutter/widgets/Shortcuts-class.html#widgets.Shortcuts.1) works in Dartpad.

Comment (venkatd) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: @justinmc @gspencergoog I think this is in reference to Shortcuts in the context of Text Editing. Can confirm that shortcuts work fine throughout our web app. We're using them quite a bit.

However, I'm not sure if it would be possible to override TextEditing shortcuts on web?

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 30]
```diff
@@ -0,0 +1,64 @@
...
+///    editing.
+class TextEditingAction<T extends Intent> extends ContextAction<T> {
+  /// A constructor for a [TextEditingAction].
+  ///
+  /// The [onInvoke] parameter must not be null.
+  TextEditingAction({ required this.onInvoke }) : assert(onInvoke != null);
+
+  EditableTextState? get _editableTextState {
+    // If an EditableText is not focused, then ignore this action.
+    if (primaryFocus?.context?.widget is! EditableText) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:34]: This is tying TextEditingAction tightly to EditableText. If somebody would want to implement their own EditableText, they'd have to re-implement all actions as well. Could we decouple this by defining an TextEditingActionExecutor interface (maybe better name needed) that defines the methods a TextEditingAction can operate on? EditableTextState would then implement that interface.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 31]
```diff
@@ -0,0 +1,64 @@
...
+///
+/// If an [EditableText] is currently focused, then it will be passed to the
+/// given [onInvoke] callback. If not, then [isEnabled] will be false and
+/// [onInvoke] will not be called.
+///
+/// See also:
+///
+///  * [CallbackAction], which is a similar Action type but unrelated to text
+///    editing.
+class TextEditingAction<T extends Intent> extends ContextAction<T> {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:26]: Wondering: Should this just be an abstract class that you need to extend to implement the abstract onInvoke method?

(not feeling super strongly about this, though)

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart [hunk 32]
```diff
@@ -0,0 +1,243 @@
...
+  /// Creates an instance of DefaultTextEditingActions.
+  const DefaultTextEditingActions({
+    Key? key,
+    required this.child,
+  }) : super(key: key);
+
+  /// The child [Widget] of DefaultTextEditingActions.
+  final Widget child;
+
+  static final TextEditingAction<ExpandSelectionLeftByLineTextIntent> _expandSelectionLeftByLineAction = TextEditingAction<ExpandSelectionLeftByLineTextIntent>(
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/default_text_editing_actions.dart:35]: These are all private, so if I don't want to use all the defaults, I have to reimplement these?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 33]
```diff
@@ -742,178 +738,849 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
 
-  void _handleMovement(
-    LogicalKeyboardKey key, {
-    required bool wordModifier,
-    required bool lineModifier,
-    required bool shift,
-  }){
-    if (wordModifier && lineModifier) {
-      // If both modifiers are down, nothing happens on any of the platforms.
+  static TextSelection _moveGivenSelectionLeft(TextSelection selection, String text) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/editable.dart:741]: _moveGivenSelectionRight has a nice little top-level comment, that would probably be useful here as well.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 34]
```diff
@@ -742,178 +738,849 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  TextPosition _getTextPositionBelow(int offset) {
+    // The caret offset gives a location in the upper left hand corner of
+    // the caret so the middle of the line above is a half line above that
+    // point and the line below is 1.5 lines below that point.
+    final double preferredLineHeight = _textPainter.preferredLineHeight;
+    final double verticalOffset = 1.5 * preferredLineHeight;
+    return _getTextPositionVertical(offset, verticalOffset);
+  }
+
+  /// Keeping the current baseOffset fixed, move the extentOffset down by one
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/editable.dart:975]: nit: are baseOffset and extentOffset properties can we link them to their API docs by putting them in []?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 35]
```diff
@@ -742,178 +738,849 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  /// line.
+  ///
+  /// See also:
+  ///
+  ///   * [extendSelectionUp]
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/editable.dart:980]: nit: add a quick sentence about why I should "also see" there.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 34 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/editable.dart:975]: (this is also true for the doc comments below)

File: packages/flutter/lib/src/rendering/editable.dart (hunk 35 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/editable.dart:980]: (and elsewhere)

File: packages/flutter/lib/src/rendering/editable.dart [hunk 36]
```diff
@@ -742,178 +738,849 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  void extendSelectionDown(SelectionChangedCause cause) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/editable.dart:981]: nit: can we document the parameter?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 37]
```diff
@@ -742,178 +738,849 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    } else {
+      nextSelection = selection!.copyWith(
+        extentOffset: selectedLine.baseOffset,
+      );
+    }
+
+    _updateSelection(nextSelection, cause);
+  }
+
+  /// Keeping the current baseOffset fixed, move the extentOffset left.
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/editable.dart:1102]: left -> right?

File: packages/flutter/test/rendering/editable_test.dart (hunk 25 above)
Comment (YeungKC) [reply packages/flutter/test/rendering/editable_test.dart:735]: Oh, right, sorry I misunderstood.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:981]: Oh then we would have to store `_cursorResetLocation` somewhere else.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 38]
```diff
@@ -742,178 +738,864 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+
+    _updateSelection(nextSelection, cause);
+  }
+
+  /// Extend the current selection to the previous start of a word.
+  ///
+  /// See also:
+  ///
+  ///   * [extendSelectionRightByWord]
+  void extendSelectionLeftByWord(SelectionChangedCause cause, [bool includeWhitespace = true]) {
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1270]: Oh I just realized the parameter name `includeWhitespace` is shown in IDEs when you autocomplete, I thought it would be just the type.

File: packages/flutter/lib/src/widgets/app.dart [hunk 39]
```diff
@@ -1621,26 +1623,53 @@ class _WidgetsAppState extends State<WidgetsApp> with WidgetsBindingObserver {
...
+      child: _MediaQueryFromWindow(
+        child: Localizations(
+          locale: appLocale,
+          delegates: _localizationsDelegates.toList(),
+          child: title,
         ),
       ),
     );
+
+    // Passing actions or shortcuts gets rid of all default actions or shortcuts
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/app.dart:1637]: See the comments we had about this above: https://github.com/flutter/flutter/pull/75032#discussion_r575595911

I thought you were arguing for it to be this way when you said, "If you pass in shortcuts and actions here, I would expect them to override the defaults from TextEditingShortcuts and TextEditingActions."

I'm not opinionated.  I don't understand why someone would pass in `actions` or `shortcuts` when they should probably be using Actions/Shortcuts widgets instead.  Maybe it's easier if they want to remove all default behavior?

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/app.dart:1637]: Actually, I'm getting opinionated now that I look at the docs.  There is an [example](https://github.com/flutter/flutter/blob/2951363dc83c0f7ed164aa95c8af772631a96835/packages/flutter/lib/src/widgets/app.dart#L866) of adding one shortcut to the default shortcuts.  In that case the user wouldn't expect to also lose all text editing shortcuts.  So I'm going to revert this back to what I original had, but let me know what your thoughts are.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 40]
```diff
@@ -0,0 +1,388 @@
...
+    LogicalKeySet(LogicalKeyboardKey.arrowUp): MoveSelectionUpTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.arrowLeft):  MoveSelectionLeftByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.arrowRight):  MoveSelectionRightByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowLeft):  ExtendSelectionLeftByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowRight):  ExtendSelectionRightByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowDown): ExtendSelectionDownTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowLeft): ExtendSelectionLeftTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowRight): ExtendSelectionRightTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowUp): ExtendSelectionUpTextIntent(),
+    // End is not handled by this platform.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:174]: It means that Android doesn't do anything natively.  Maybe this is better: "End does nothing on this platform."

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:174]: I went with this for now: "End has no effect on text editing on this platform."

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 30 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:53]: That's a good catch, thanks.  I called it TextEditingActionTarget and tried to do it like this: fb6970b

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 31 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart]: I actually really liked this idea so I went for it in e24610a.  I didn't like committing to a new signature of onInvoke, and this lets me get rid of it altogether.  I think it will be more flexible this way.

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart (hunk 32 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart]: The main reason that I'm hesitant is just because I worry that I'll end up changing something with the API before I finish all of the other text editing actions.  How about if I leave them private for now and plan to make them public later when everything is finalized?

File: packages/flutter/lib/src/rendering/editable.dart (hunk 38 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1317]: I added a bit in the docs about it anyway.  It does affect some of these methods in interesting ways that I should document.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 41]
```diff
@@ -742,178 +738,864 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    assert(selection != null);
+
+    if (selection!.extentOffset == 0) {
+      return;
+    }
+    if (!selectionEnabled) {
+      return moveSelectionToStart(cause);
+    }
+
+    final int lowerOffset = math.max(0, math.max(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1261]: I mean lower as in its physical position in the field.  That's really confusing now that I think about it...  I'll change it to firstOffset and lastOffset (replacing upperOffset and lowerOffset, respectively).

File: packages/flutter/lib/src/rendering/editable.dart [hunk 42]
```diff
@@ -742,178 +738,864 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+
+  /// Extend the current selection to the start of extentOffset's line.
+  ///
+  /// Uses baseOffset as a pivot point and doesn't change it. If extentOffset is
+  /// right of baseOffset, then collapses the selection.
+  ///
+  /// See also:
+  ///
+  ///   * [extendSelectionRightByLine]
+  ///   * [expandSelectionRightByLine]
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart]: One is "extend" and one is "expand".  I'm adding some detail to these so it will be obvious that they're different.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 43]
```diff
@@ -742,178 +738,864 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  void extendSelectionLeftByLine(SelectionChangedCause cause) {
+    assert(selection != null);
+
+    if (!selectionEnabled) {
+      return moveSelectionLeftByLine(cause);
+    }
+
+    final int startPoint = previousCharacter(selection!.extentOffset, _plainText, false);
+    final TextSelection selectedLine = _selectLineAtOffset(TextPosition(offset: startPoint));
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1111]: I strongly agree!  These methods existed before this PR, but I didn't like the names.  It's really hard to understand when and where there are side effects in this class, which is why I was trying to do some of this work in static methods.  I'll change the names.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 44]
```diff
@@ -742,178 +738,864 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+
+    late TextSelection nextSelection;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:1113]: Great catch 👍

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 45]
```diff
@@ -0,0 +1,64 @@
...
+  /// If an EditableText is not focused and available at
+  /// `primaryFocus.context.widget`, then isEnabled will be false, and this will
+  /// not be invoked.
+  ///
+  /// Must not be null.
+  @protected
+  final OnInvokeTextEditingCallback<T> onInvoke;
+
+  @override
+  Object? invoke(covariant T intent, [BuildContext? context]) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart]: This is irrelevant due to refactoring related to this comment: https://github.com/flutter/flutter/pull/75032#discussion_r577877921

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 29 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: Playing with that example, it seems like if I add a TextField to the page, it will swallow all keyboard Shortcuts when it has focus.  This appears to be specific to web, because if I try invoking a keyboard shortcut on Mac running master with a TextField focused, it works.

This is going to be a problem for the reasons mentioned by @venkatd.  Also, @shihaohong will likely run into problems with this when trying to create keyboard shortcuts for Autocomplete.  I'll try to get an opinion from someone working on web.

**Comment by justinmc** [comment]
@LongCatIsLooong RE https://github.com/flutter/flutter/pull/75032#discussion_r580704225, currently I'm asserting that the selection isn't null in all of these render editable methods.  Is that alright since https://github.com/flutter/flutter/issues/76573 seems to indicate that a null/invalid selection should be impossible long term, or should I just do nothing?

Also about your comments above on exposing TextSelection and changing it elsewhere (https://github.com/flutter/flutter/pull/75032#discussion_r580770371), I'm on board with the sentiment but I also am not quite sure how this should look.  I think this class does too many things right now.  It would be great if we could just have functions that take the needed metrics (selection and TextPainter?) and then return the new selection.  I'll keep thinking about how we can do this as we go forward.

I'll think about doing something like you mentioned in https://github.com/flutter/flutter/pull/75032#discussion_r580765707 as well as we go forward.  Originally I was happy to get away from the _handleMovement method, which was like hundreds of lines long and hard to understand, but this broken up way of doing things is repeating some code here and there.

**Comment by LongCatIsLooong** [comment]
Yeah I'll try to address https://github.com/flutter/flutter/pull/75032#discussion_r580704225 separately.

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart (hunk 32 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart]: Another thing I realized is that since I give the specific intent type for the type parameter (in this case ExpandSelectionLeftByLineTextIntent), these could not be used by any other Intent.  I could change the type parameter to just Intent to get around that.

**Comment by justinmc** [comment]
Ready for re-review.  The biggest changes this time are:

  * [TextEditingActionTarget](https://github.com/flutter/flutter/pull/75032/files#diff-b14445f823d598a72b4823a9663ee7b3a3d4fcbe074ccc712848608e56faf798R20) decouples TextEditingAction from EditableText.
  * [TextEditingAction](https://github.com/flutter/flutter/pull/75032/files#diff-b14445f823d598a72b4823a9663ee7b3a3d4fcbe074ccc712848608e56faf798R46) is now an abstract class and the [actions all implement it](https://github.com/flutter/flutter/pull/75032/files#diff-a7ab0a5db9b1cb96f1d25b62073b4d8bbbe0f4dfa56578bede557c528cd0c121R113).
  * Passing actions/shortcuts to WidgetsApp [doesn't affect](https://github.com/flutter/flutter/pull/75032/files#diff-f629b31e1aaf7209877c14f88326284538c1279b6bcf4859e3d4daebc889bef4R1636) the DefaultTextEditingActions/Shortcuts, they must be overridden with Actions/Shortcuts widgets.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 29 above)
Comment (venkatd) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: @justinmc in our Flutter web app *only* keyboard Shortcuts that are used by the TextField are swallowed. For example `LogicalKeyboardKey.arrowDown` and `LogicalKeyboardKey.up` are swallowed while `LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.keyJ)` are properly handled even when a TextField is focused.

Meanwhile I can confirm that when running a MacOS build, everything works perfectly.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: @mdebbar Do you know why/how web is swallowing Shortcuts when a text field is focused?

I'm worried that this PR is going to make web into a special case for handling keyboard events and wanted to run this by you to see what I can do.

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 118.
View them at https://flutter-gold.skia.org/cl/github/75032

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 121.
View them at https://flutter-gold.skia.org/cl/github/75032

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 30 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:51]: looks like this still needs to be replaced with a proper type check to match the down cast below?

File: packages/flutter/lib/src/widgets/text_editing_intents.dart [hunk 46]
```diff
@@ -0,0 +1,125 @@
...
+/// An [Intent] to expand the selection left to the start/end of the current
+/// line.
+///
+/// {@template flutter.widgets.TextEditingIntents.seeAlso}
+/// See also:
+///
+///   * [DefaultTextEditingActions], which responds to this [Intent].
+///   * [DefaultTextEditingShortcuts], which triggers this [Intent].
+/// {@endtemplate}
+class ExpandSelectionLeftByLineTextIntent extends Intent {}
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart:16]: I was able to add const constructors to all of these Intents, great suggestion.  It didn't seem to work for TextEditingAction because ContextAction and Action have no const constructor.

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 123.
View them at https://flutter-gold.skia.org/cl/github/75032

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 124.
View them at https://flutter-gold.skia.org/cl/github/75032

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 125.
View them at https://flutter-gold.skia.org/cl/github/75032

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 47]
```diff
@@ -0,0 +1,63 @@
...
+/// See also:
+///
+///  * [CallbackAction], which is a similar Action type but unrelated to text
+///    editing.
+abstract class TextEditingAction<T extends Intent> extends ContextAction<T> {
+  /// Returns the currently focused [TextEditingAction], if any.
+  @protected
+  TextEditingActionTarget? get textEditingActionTarget {
+    // If a TextEditingActionTarget is not focused, then ignore this action.
+    if ((primaryFocus!.context! as StatefulElement).state is! TextEditingActionTarget) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:51]: is it safe to use `!` on `primaryFocus`, or assuming the context is a `StatefulElement`?

**Review by LongCatIsLooong — COMMENTED** [review]
@mdebbar according to your comments in https://github.com/flutter/flutter/pull/52661:

> The reason we decided to let the browser handle all key events for us is because it's difficult to hardcode the handling of all keys.

With this new scheme, would it be possible to move key handling to the framework if we have comprehensive shortcuts (https://github.com/flutter/flutter/blob/9d018ef7985c22a0a17e544ca184a07a39c3bd5c/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart)?

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 48]
```diff
@@ -0,0 +1,388 @@
...
+    // Home has no effect on text editing on this platform.
+    // Meta + arrow left has no effect on text editing on this platform.
+    // Meta + arrow right has no effect on text editing on this platform.
+    // Meta + arrow up has no effect on text editing on this platform.
+    // Meta + shift + arrow down has no effect on text editing on this platform.
+    // Meta + shift + arrow left has no effect on text editing on this platform.
+    // Meta + shift + arrow right has no effect on text editing on this platform.
+    // Meta + shift + arrow up has no effect on text editing on this platform.
+    // Shift + end has no effect on text editing on this platform.
+    // Shift + home has no effect on text editing on this platform.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:220]: Do <kbd>pageUp</kbd> and <kbd>pageDown</kbd> do anything special in a text field? They currently seem to be mapped to a `ScrollIntent`.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 29 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: Here's a Dartpad showing what I mean: https://dartpad.dartlang.org/b17b1acce8bb9d3f9951981a93f80084?null_safety=true

On web, the Shortcut is ignored.  Nothing is logged, and the cursor moves like normal.  If you copy this code and run it locally, you'll see that when the left arrow is pressed, the cursor doesn't move, and the print statement is logged.

File: packages/flutter/lib/src/widgets/text_editing_action.dart (hunk 47 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:51]: Oh thanks!  I messed this up when I refactored it.  Pushing a fix.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 48 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:220]: Good call, I created a separate issue for that: https://github.com/flutter/flutter/issues/77611

It looks like on Mac it should scroll the TextField without moving the cursor.  On Flutter right now it will scroll an enclosing ListView but it won't scroll the TextField.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 29 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:57]: Discussed this offline and our solution is here: 00c03ad

Web will explicitly ignore all of these text editing shortcuts and allow them to be handled by the web engine.  However, it's possible to override these by using a Shortcuts widget placed anywhere in the widget tree.

@shihaohong This is good news for keyboard shortcuts for Autocomplete on web.  If you just use a Shortcuts widget like normal, it should work identically on the web.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 49]
```diff
@@ -0,0 +1,429 @@
...
+    LogicalKeySet(LogicalKeyboardKey.arrowUp): const MoveSelectionUpTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.arrowLeft): const MoveSelectionLeftByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.arrowRight): const MoveSelectionRightByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowLeft): const ExtendSelectionLeftByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowRight): const ExtendSelectionRightByWordTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowDown): const ExtendSelectionDownTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowLeft): const ExtendSelectionLeftTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowRight): const ExtendSelectionRightTextIntent(),
+    LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.arrowUp): const ExtendSelectionUpTextIntent(),
+    // End has no effect on text editing on this platform.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:174]: nit: To avoid a little duplication (and to make this easier to read), could this be rephrased as:

```
// The following key combinations have no effect on text edition on this platform:
//  * Home
//  * Mata + arrow down
//  ...
```

File: packages/flutter/lib/src/widgets/app.dart [hunk 50]
```diff
@@ -910,6 +915,8 @@ class WidgetsApp extends StatefulWidget {
   /// the [actions] for this app. You may also add to the bindings, or override
   /// specific bindings for a widget subtree, by adding your own [Actions]
   /// widget.
+  ///
+  /// Passing this will not replace [DefaultTextEditingActions].
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/app.dart:919]: For shortcuts, the default text editing shortcuts need to be placed inside the defaultShortcuts because they need able to fall through to the defaultShortcuts when an EditableText isn't focused.  I'll make actions do the same thing and update the docs to match.

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart [hunk 51]
```diff
@@ -0,0 +1,264 @@
...
+  /// Creates an instance of DefaultTextEditingActions.
+  const DefaultTextEditingActions({
+    Key? key,
+    required this.child,
+  }) : super(key: key);
+
+  /// The child [Widget] of DefaultTextEditingActions.
+  final Widget child;
+
+  // TODO(justinmc): Put Actions here that are triggered directly, not by
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:34]: Yeah good call, I was getting carried away with how this will work in the future.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 52]
```diff
@@ -0,0 +1,429 @@
...
+///
+/// {@tool snippet}
+///
+/// This example shows how to use an additional [Shortcuts] widget to override
+/// some default text editing keyboard shortcuts to have new behavior. Instead
+/// of moving the cursor, alt + up/down will instead change the focused widget.
+///
+/// ```dart
+/// @override
+/// Widget build(BuildContext context) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:28]: Good catch.  It's included automatically in WidgetsApp, but I should show it for the sake of this example.

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 53]
```diff
@@ -0,0 +1,429 @@
...
+///       ),
+///     ),
+///   );
+/// }
+/// ```
+/// {@end-tool}
+///
+/// {@tool snippet}
+///
+/// This example shows how to use an additional [Shortcuts] widget to override
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:59]: The first example shows remapping some shortcuts to existing Intents.  The second example shows creating totally custom Intents and Actions.  I've updated the description to try to make the distinction more clear.

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 54]
```diff
@@ -0,0 +1,65 @@
...
+import 'framework.dart';
+
+/// An implementor of this must be focused for a [TextEditingAction] to be
+/// enabled.
+///
+/// See also:
+///
+///   * [EditableText], which implements this and is the most typical target of
+///     a TextEditingAction.
+abstract class TextEditingActionTarget {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_action.dart:22]: Ah I see what you mean.  I like this idea, but do you mind if I punt on it until I've converted more stuff to actions?  I'm still not fully certain on the long-term role of EditableText and RenderEditable.  I might even want to create a separate class from both of these that would implement all of this text editing API instead of RenderEditable.

That would be a breaking change, but it's probably unavoidable.

**Comment by justinmc** [comment]
@LongCatIsLooong @goderbauer Updated with your suggestions and ready for re-review, thanks!

File: packages/flutter/lib/src/widgets/text_editing_action.dart [hunk 55]
```diff
@@ -0,0 +1,68 @@
...
+    if (primaryFocus?.context == null
+        || primaryFocus!.context! is! StatefulElement
+        || ((primaryFocus!.context! as StatefulElement).state is! TextEditingActionTarget)) {
+      return null;
+    }
+    return (primaryFocus!.context! as StatefulElement).state as TextEditingActionTarget;
+  }
+
+  @override
+  bool isEnabled(Intent intent) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_editing_action.dart:63]: super nit: 
```suggestion
  bool isEnabled(T intent) {
```

**Review by LongCatIsLooong — APPROVED** [review]
LGTM :tada:

**Comment by TimWhiting** [comment]
Would #77512 be in scope for this?

**Comment by justinmc** [comment]
@TimWhiting I think that's not in scope for this PR, but thanks for bringing it to my attention.  The Shortcuts approach for that might be viable, but we should figure out exactly how the behavior should work.  Let's continue the discussion on https://github.com/flutter/flutter/issues/77512.

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart [hunk 56]
```diff
@@ -0,0 +1,240 @@
...
+    MoveSelectionRightTextIntent: _MoveSelectionRightTextAction(),
+    MoveSelectionToEndTextIntent: _MoveSelectionToEndTextAction(),
+    MoveSelectionToStartTextIntent: _MoveSelectionToStartTextAction(),
+    MoveSelectionUpTextIntent: _MoveSelectionUpTextAction(),
+  };
+
+  @override
+  Widget build(BuildContext context) {
+    return Actions(
+      actions: <Type, Action<Intent>>{
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:67]: Yeah, I had a big setup for handling other types of actions that I deleted.  I'll simplify to just _shortcutActions for now.

File: packages/flutter/lib/src/widgets/default_text_editing_actions.dart [hunk 57]
```diff
@@ -0,0 +1,240 @@
...
+/// This default behavior can be overridden by placing an [Actions] widget lower
+/// in the widget tree than this. See [DefaultTextEditingShortcuts] for an example of
+/// remapping keyboard keys to an existing text editing [Intent].
+///
+/// See also:
+///
+///   * [DefaultTextEditingShortcuts], which maps keyboard keys to many of the
+///     [Intent]s that are handled here.
+///   * [WidgetsApp], which creates a DefaultTextEditingShortcuts.
+class DefaultTextEditingActions extends StatelessWidget {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/default_text_editing_actions.dart:25]: Yes, and it saves a good amount of lines of code.  Thanks for the suggestion.  Same for Shortcuts as you mentioned below.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by venkatd** [comment]
@justinmc thanks for all the work on this PR! Love where things are headed with customizability of text editing.

Inability to override shortcuts in a TextField has been a blocker for releasing a Flutter web app to production. Does this PR apply to Flutter web? If not, maybe I can create a separate issue to discuss the use case?

**Comment by justinmc** [comment]
@venkatd No problem, thank you for the reviews on this!

I think everything should work as expected with web. See this thread above: https://github.com/flutter/flutter/pull/75032#discussion_r577779699

So using a Shortcuts widget will allow you to intercept key events like up-arrow before they go to the web engine, just like they will also be intercepted on other platforms before being handled by the framework.  This is important for us too, like for @shihaohong who is working on keyboard controls for Autocomplete now.

If something doesn't work as expected let me know, though.  I think Autocomplete will be the first use of this in the framework itself and it's not finished yet.

**Comment by venkatd** [comment]
@justinmc great to hear! Will give the master branch a try this week.
