### PR TITLE
Explain how to use `flutter channel`.

### LINKED ISSUE #152274: flutter channel help says it can list channels, but apparently doesn't show how to do that
### Steps to reproduce

Run `flutter channel -h`

### Expected results

Show an option for how to list channels.

Something like:

```
sethladd-macbookpro:first_ios_app sethladd$ flutter channel -h
List or switch Flutter channels.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional diagnostic
                            information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --enable-analytics      Enable telemetry reporting each time a flutter or dart command runs.
    --disable-analytics     Disable telemetry reporting each time a flutter or dart command runs, until it is re-enabled.
    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.

Usage: flutter channel [<channel-name>]
-h, --help                    Print this usage information.
-l, --list                        List all available channels.
    --[no-]cache-artifacts    After switching channels, download all required binary artifacts. This is the equivalent of running "flutter
                              precache" with the "--all-platforms" flag.
                              (defaults to on)
```

Note the `-l` and `--list` as explicit option to do the listing.

### Actual results

```
sethladd-macbookpro:first_ios_app sethladd$ flutter channel -h
List or switch Flutter channels.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional diagnostic
                            information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --enable-analytics      Enable telemetry reporting each time a flutter or dart command runs.
    --disable-analytics     Disable telemetry reporting each time a flutter or dart command runs, until it is re-enabled.
    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.

Usage: flutter channel [<channel-name>]
-h, --help                    Print this usage information.
    --[no-]cache-artifacts    After switching channels, download all required binary artifacts. This is the equivalent of running "flutter
                              precache" with the "--all-platforms" flag.
                              (defaults to on)
```

Note how the above says "List or switch FLutter channels".

Maybe I missed it, but I didn't find an option to list the channels. I see `-h` and `--no-cache-artifacts`, and an option to specify a channel-name

But nothing to list channels?

### Code sample

n/a

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

n/a but if it's useful, here's the version:

Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (3 months ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/152274.

I ran into https://github.com/flutter/flutter/issues/152274 myself, so seemed like an easy fix.

### CODE REVIEW

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Formatting :p

File: packages/flutter_tools/lib/src/commands/channel.dart [hunk 1]
```diff
@@ -29,13 +29,21 @@ class ChannelCommand extends FlutterCommand {
...
+  String get name => 'channel';
 
   @override
-  final String description = 'List or switch Flutter channels.';
+  String get description => 'List or switch Flutter channels.\n'
+      '\n'
+      'Common commands:\n'
+      '\n'
+      ' flutter channel\n'
+      '   List Flutter channels\n'
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/commands/channel.dart:40]:
```suggestion
      '   List Flutter channels.\n'
```

**Review by andrewkolos — APPROVED** [review]
LGTM

**Comment by andrewkolos** [comment]
YAYYYY 🎉 🎉 🎉 🎉
