### PR TITLE
Fix InteractiveViewer minScale bug

### LINKED ISSUE #65304: InteractiveViewer ignore scale settings when using with small child
## Steps to Reproduce

1. Run `flutter create bug`.
2. replace MyHomePage in main.dart

```
class MyHomePage extends StatelessWidget {
  MyHomePage({String title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('InteractiveViewer test'),
        ),
        body: InteractiveViewer(
          constrained: false,
          minScale: 1,
          maxScale: 1,
          child: SizedBox(
            width: 300,
            height: 300,
            child: DecoratedBox(
              decoration: BoxDecoration(color: Colors.red),
            ),
          ),
        ));
  }
}
```
 
3. run.
4. zoom in the red rectangle area

**Expected results:** 
>          minScale: 1,
>          maxScale: 1,

**Actual results:** 

The issue occurs in latest master, beta and dev channel. testing platform is Android and Web.

thanks,

### PR DESCRIPTION
**Pull request by justinmc**
## Description

When a child was smaller than the viewport, InteractiveViewer could sometimes enforce a minimum scale that was outside of the provided min/max. This was in order to prevent viewing outside of the boundary.  This PR covers this edge case so that the min/max scale can't be exceeded.

## Related Issues

Closes https://github.com/flutter/flutter/issues/65304

## Tests

I added the following tests:

  * Try to pinch to zoom in the case that was popping to full screen before, and check that the scale doesn't change at all.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/interactive_viewer.dart [hunk 1]
```diff
@@ -660,7 +660,8 @@ class _InteractiveViewerState extends State<InteractiveViewer> with TickerProvid
       _viewport.width / _boundaryRect.width,
       _viewport.height / _boundaryRect.height,
     );
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/interactive_viewer.dart:662]: Is `minScale` the max scale allowed?

if `_boundaryRect.size` `(10, 10)` and the viewport's size is `(100, 200)`, then `minScale` is going to be 20 right? Anything above 20 is going to make the child exceed the size of the viewport in both dimensions.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:662]: This minScale is the minimum scale allowed, but maybe my comment in the code above this is confusing.

The boundary is defined as being positioned on the child, and it scales with the child.  In your example of a 10,10 boundary, let's say that the child is also of size 10,10.  So here's your example with an orange child and a yellow viewport:

| scale | 1.0 | 10.0 | 20.0 |
| -- | -- | -- | -- |
|           | Screen Shot 2020-09-10 at 9 37 20 AM | Screen Shot 2020-09-10 at 9 37 02 AM | Screen Shot 2020-09-10 at 9 37 40 AM |

The purpose of this minScale is to prevent the viewport from exposing anything beyond the boundary. In other words, in this example it's trying to cover up all the yellow using the orange child.  It is not trying to prevent the child from growing beyond the size of the viewport, that's fine.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:662]: Ah I see. Thanks for the explanation! In that case would it be possible to move the logic in the if clause to before clamping? Then the function would be roughly
```dart
    final double currentScale = _transformationController.value.getMaxScaleOnAxis();
    final double totalScale = math.max(currentScale * scale, math.max(_viewport.width / _boundaryRect.width, _viewport.height / _boundaryRect.height));  
    final double clampedTotalScale = totalScale.clamp(widget.minScale, widget.maxScale);
    final double clampedScale = clampedTotalScale / currentScale;
    return matrix.clone()..scale(clampedScale);
```

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/lib/src/widgets/interactive_viewer.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:662]: Yes that looks much better, thanks!

**Comment by MichealReed** [comment]
@justinmc I'm seeing a strange new behavior after upgrading to the latest master commit. Every time I scroll now, a tap down event is triggered for 0,0. Do you know which of the recent commits could be responsible? It seems to be rooted in InteractiveViewer.

**Comment by justinmc** [comment]
@MichaelReed This one makes me suspicious: https://github.com/flutter/flutter/pull/65313

Thanks for letting me know about this.  Could you open a new issue for this with code to reproduce it?

**Comment by MichealReed** [comment]
https://github.com/flutter/flutter/issues/66035 submitted! Thanks for taking a look.
