### PR TITLE
[ios][engine] Fix keyboard flicker when switching text fields

### LINKED ISSUE #180842: iOS 18.x ,TextField next focus keyboard disappears and appears again
### Steps to reproduce

run the sample on iPhone 10, and just use the submit on keyboard to focus next field.
### Expected results

keyboard staying visible, like on android, or IOS before..

### Actual results

keyboard disappears and appears again

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SingleChildScrollView(
            child: Padding(
              padding: EdgeInsets.only(left: 20, right: 20),
              child: Column(
                children: [
                  CupertinoTextField(
                    textInputAction: .next,                    
                  ),
                  TextField(
                    textInputAction: .next,
                    decoration: InputDecoration(label: Text('Field A')),
                  ),
                  TextField(
                    textInputAction: .next,
                    decoration: InputDecoration(label: Text('Field B')),
                  ),
                  TextField(
                    textInputAction: .next,
                    decoration: InputDecoration(label: Text('Field C')),
                  ),
                  TextField(
                    textInputAction: .done,
                    decoration: InputDecoration(label: Text('Field D')),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<video src="https://github.com/user-attachments/assets/082e12f1-ed7b-43b7-a1b6-44d79c6a12ed" width=400/>
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
renanyoy@macbook ~ % flutter doctor -v
[✓] Flutter (Channel main, 3.40.0-1.0.pre-526, on macOS 15.7.3 24G419 darwin-arm64, locale en-FR) [1,508ms]
    • Flutter version 3.40.0-1.0.pre-526 on channel main at /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 81c1cdf898 (2 hours ago), 2026-01-12 05:30:22 -0500
    • Engine revision 81c1cdf898
    • Dart version 3.12.0 (build 3.12.0-14.0.dev)
    • DevTools version 2.54.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-native-assets, enable-swift-package-manager, omit-legacy-version-file, enable-lldb-debugging,
      enable-uiscene-migration, enable-riscv64

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [2.1s]
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Emulator version 36.3.10.0 (build_id 14472402) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.2) [1,211ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17C52
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [6ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (5 available) [6.4s]
    • Pixel 6 (mobile)                     • 19291FDF60092F                           • android-arm64  • Android 16 (API 36)
    • iPad de Loïc (2) (wireless) (mobile) • 923212e1640b8f2365131adbc59295a12c2ed4a9 • ios            • iOS 18.7.3 22H217
    • iPhone (mobile)                      • 00008020-000640992209002E                • ios            • iOS 18.7.2 22H124
    • macOS (desktop)                      • macos                                    • darwin-arm64   • macOS 15.7.3 24G419
      darwin-arm64
    • Chrome (web)                         • chrome                                   • web-javascript • Google Chrome
      143.0.7499.193

[✓] Network resources [483ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/180842

The issue was caused by https://github.com/flutter/flutter/pull/173598.

When there is a single TextField, the MethodChannel calls are as follows:

```
handleMethodCall: TextInput.setClient
handleMethodCall: TextInput.setEditableSizeAndTransform
handleMethodCall: TextInput.setMarkedTextRect
handleMethodCall: TextInput.setCaretRect
handleMethodCall: TextInput.setStyle
handleMethodCall: TextInput.setEditingState
handleMethodCall: TextInput.show
handleMethodCall: TextInput.requestAutofill
handleMethodCall: TextInput.clearClient
handleMethodCall: TextInput.hide
```

However, when there are two TextFields, the calls become:

```
handleMethodCall: TextInput.setClient
handleMethodCall: TextInput.setEditableSizeAndTransform
handleMethodCall: TextInput.setMarkedTextRect
handleMethodCall: TextInput.setCaretRect
handleMethodCall: TextInput.setStyle
handleMethodCall: TextInput.setEditingState
handleMethodCall: TextInput.show
handleMethodCall: TextInput.requestAutofill
handleMethodCall: TextInput.clearClient
handleMethodCall: TextInput.setClient
handleMethodCall: TextInput.setEditableSizeAndTransform
handleMethodCall: TextInput.setMarkedTextRect
handleMethodCall: TextInput.setCaretRect
handleMethodCall: TextInput.setStyle
handleMethodCall: TextInput.setEditingState
handleMethodCall: TextInput.show
handleMethodCall: TextInput.requestAutofill
handleMethodCall: TextInput.clearClient
handleMethodCall: TextInput.hide
```

In the multi-field case, `clearTextInputClient` is called before `setTextInputClient` for the next field. Calling `removeFromSuperview` during `clearTextInputClient` causes the keyboard to briefly dismiss and reappear (flicker).

This PR defers the `removeFromSuperview` call from `clearTextInputClient` to `hideTextInput`, using a pending flag (`_pendingInputViewRemoval`). The input view is removed only after `resignFirstResponder` dismisses the keyboard. `showTextInput` resets the flag to prevent stale flags from causing unintended removal when switching fields.

For autofill contexts, a separate flag (`_pendingAutofillRemoval`) defers removal to `triggerAutofillSave`, preserving the existing autofill save behavior.

https://github.com/user-attachments/assets/751dd6b9-cfc0-401c-a924-c359ae5bc179

https://github.com/user-attachments/assets/cb0831e4-4312-46be-b40e-03df939ad2d5

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 1]
```diff
@@ -3112,12 +3130,26 @@ - (void)clearTextInputClient {
...
+      [_activeView removeFromSuperview];
+      [_inputHider removeFromSuperview];
+    }
   } else {
-    // If _autofillContext is not empty, triggerAutofillSave will be called to clean up the views.
-    _pendingInputHiderRemoval = YES;
+    // Autofill context exists: removal will be performed in triggerAutofillSave,
+    // which is called by finishAutofillContext to save autofill entries.
+    _pendingAutofillRemoval = YES;
   }
```
[the remark this answers is not in the document]
Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:3163]: [14165a3](https://github.com/flutter/flutter/pull/182661/commits/14165a35b209820c825478061a3166da579240d1)

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm [hunk 2]
```diff
@@ -69,7 +69,8 @@ @interface FlutterTextInputPlugin ()
 @property(nonatomic, readonly) UIView* keyboardView;
 @property(nonatomic, assign) UIView* cachedFirstResponder;
 @property(nonatomic, readonly) CGRect keyboardRect;
-@property(nonatomic, readonly) BOOL pendingInputHiderRemoval;
+@property(nonatomic, readonly) BOOL pendingAutofillRemoval;
```
Comment (LongCatIsLooong) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm]: could you add a short comment here to explain what these two flags are for?

e.g.,
``` 
/// Wether the client disconnected without sending a hideText message
/// in which case the text input plugin defers removeFromSuperview 
/// call to prevent flickering when switching to a different text field.
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 3]
```diff
@@ -2822,6 +2824,11 @@ - (void)startLiveTextInput {
 - (void)showTextInput {
   _activeView.viewResponder = _viewResponder;
   [self addToInputParentViewIfNeeded:_activeView];
+
+  // Reset pending removal flag to prevent stale flags from a previous
```
Comment (LongCatIsLooong) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Since the flag is set to YES in clearClient I'd think the flag at least has to be reset to NO in setClient just for them to be symmetric.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm [hunk 4]
```diff
@@ -69,7 +69,8 @@ @interface FlutterTextInputPlugin ()
...
+@property(nonatomic, readonly) BOOL pendingInputViewRemoval;
```
Comment (LongCatIsLooong) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:73]: could you add a short comment here to explain what these two flags are for?

e.g.,
``` 
/// Wether the client disconnected without sending a hideText message.
///
/// This can indicate that the focus is being switched to a different
/// text field and to prevent flickering the removeFromSuperview
/// call should be delayed.
```

**Comment by LongCatIsLooong** [comment]
@loic-sharma IMO this should be safe to cherrypick as long as all custom text input clients, when unfocusing, send a `hide` event (where the deferred view removal happens) immediately after `clearClient` event like `EditableTextState` does. 

If a custom text input client doesn't follow that convention and did not send `hide`, the native text input view may stay in the view hierarchy for an extra while but that should be fine too since those views were not removed from the view hierarchy prior to https://github.com/flutter/flutter/pull/173598/changes

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 3 above)
Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Thank you for the review. Updated in a2291f3.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm (hunk 4 above)
Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:73]: Sure, added a comment in a2291f3.

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:73]: Whoops sorry I didn't realize this was the test instead of the interface declaration. Could you move the comments to the other file?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm (hunk 4 above)
Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:73]: Of course! I did 5f94b7080b1cc6bb443869bec9fb7d40d29bc9cc .

**Review by loic-sharma — APPROVED** [review]
Thanks for fixing this!

This LGTM but I'm not that familiar with iOS's text input plugin lifecycle. @hellohuanlin please feel free to review as well :)
