### PR TITLE
MenuAnchor hover traversal fixes

### LINKED ISSUE #150910: [material/menu_anchor.dart] Switching between hover focus and directional focus leads to incorrect focus order.
### Steps to reproduce

1. Run sample
2. Hover cursor on item 3. 
3. Press down arrow key until you reach the bottom of the menu. 
4. Move cursor off item 3 then back on item 3. 
5. Press the up arrow key.
6. Observe focus position.

### Expected results

Focus should move to item 2.

### Actual results

Focus moves to item 8. I believe this is because the focus scope data is not being invalidated. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const Bug());


// Reproduce: hover cursor on item 3. Press down arrow key until you reach the
// bottom of the menu. Move cursor off item 3 then back on item 3. Press up
// arrow key.
class Bug extends StatelessWidget {
  const Bug({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme:
          ThemeData(colorSchemeSeed: Colors.blue, brightness: Brightness.dark),
      home: const BugApp(),
    );
  }
}

class BugApp extends StatefulWidget {
  const BugApp({
    super.key,
  });

  @override
  State<BugApp> createState() => _BugAppState();
}

class _BugAppState extends State<BugApp> {
  FocusNode focusNode = FocusNode();
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            MenuAnchor(
              childFocusNode: focusNode,
              builder: (BuildContext context,  MenuController controller, Widget? child) {
                return TextButton(
                  focusNode: focusNode,
                  onPressed: () {
                    if (controller.isOpen) {
                      controller.close();
                    } else {
                      controller.open();
                    }
                  },
                  child: const Text('Open'),
                );
              },
              menuChildren: <Widget>[
                for (int i = 0; i < 10; i++)
                  MenuItemButton(
                    child: Text('Item $i'),
                    onPressed: () {},
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/59215665/6abb881e-9edf-4d44-9137-18ecfc431334

</details>

### Logs

<details open><summary>Logs</summary>

```console
None applicable
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.350, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.350 on channel master at /Users/davidhicks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a52e266b79 (9 hours ago), 2024-06-26 14:59:56 -0700
    • Engine revision 1d5e3cc55a
    • Dart version 3.5.0 (build 3.5.0-299.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #150911: [material/menu_anchor.dart] Hovering over menu item affects scrolling and focus order.
### Steps to reproduce

1. Run sample
2. Scroll to item 50
3. Hover over item 50 and remove your hand from the mousepad.
4. Move focus upwards using directional keys until scrolling occurs.

### Expected results

The hovered menu item should not regain focus on scroll. Traversal should continue from the item that was focused before scrolling.

### Actual results

The hovered menu item regains focus on scroll. 

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const Bug());


// Reproduce: hover cursor on item 3. Press down arrow key until you reach the
// bottom of the menu. Move cursor off item 3 then back on item 3. Press up
// arrow key.
class Bug extends StatelessWidget {
  const Bug({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme:
          ThemeData(colorSchemeSeed: Colors.blue, brightness: Brightness.dark),
      home: const BugApp(),
    );
  }
}

class BugApp extends StatefulWidget {
  const BugApp({
    super.key,
  });

  @override
  State<BugApp> createState() => _BugAppState();
}

class _BugAppState extends State<BugApp> {
  FocusNode focusNode = FocusNode();
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
             MenuAnchor(
              childFocusNode: focusNode,
              builder: (context, controller, child) {
                return TextButton(
                  focusNode: focusNode,
                  onPressed: () {
                    if (controller.isOpen) {
                      controller.close();
                    } else {
                      controller.open();
                    }
                  },
                  child: Text('Open'),
                );
              },
              menuChildren: [
                for(var i = 0; i < 100; i++)
                  MenuItemButton(
                    child: Text('Item $i'),
                    onPressed: () {},
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/59215665/67a7d9f3-2bde-4485-8cfc-5f881550bf13

</details>

### Logs

<details open><summary>Logs</summary>

```console
No applicable logs
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.350, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.350 on channel master at /Users/davidhicks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a52e266b79 (9 hours ago), 2024-06-26 14:59:56 -0700
    • Engine revision 1d5e3cc55a
    • Dart version 3.5.0 (build 3.5.0-299.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by davidhicks980**
Fixes https://github.com/flutter/flutter/issues/150910 and https://github.com/flutter/flutter/issues/150911. 

https://github.com/flutter/flutter/issues/150910 is fixed by invalidating the focus scope whenever a hover occurs. I'm interested to hear of better fixes -- it feels a bit extreme to invalidate the focus scope so often.

https://github.com/flutter/flutter/issues/150911 is fixed by replacing TextButton.onHover with MouseRegion.onHover and MouseRegion.onExit. The issue appears to be that MouseRegion.onEnter is called on scroll, whereas MouseRegion.onHover is not. I'm not confident this is a great solution, so please let me know if you all have any suggestions!

@Piinks @dkwingsmt 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by davidhicks980** [comment]
Update: I reached out on the devtools Discord regarding this error.

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -2006,13 +2043,22 @@ class _SubmenuButtonState extends State<SubmenuButton> {
           ),
         );
 
-        if (_enabled && _platformSupportsAccelerators) {
-          return MenuAcceleratorCallbackBinding(
-            onInvoke: () => toggleShowMenu(context),
-            hasSubmenu: true,
+        if (_enabled) {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/menu_anchor.dart:2046]: Maybe invert this and just return child here if !_enabled. Simplifies the later logic.

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 2]
```diff
@@ -1176,11 +1184,29 @@ class _MenuItemButtonState extends State<MenuItemButton> {
...
+    if (!_isHovered) {
+      _isHovered = true;
+      widget.onHover?.call(true);
+      if (widget.requestFocusOnHover) {
+        assert(_debugMenuInfo('Requesting focus for $_focusNode from hover'));
+        _focusNode.requestFocus();
+
+        // Without invalidating the focus policy, switching to directional focus
+        // may not originate at this node.
+        FocusTraversalGroup.of(context).invalidateScopeData(
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/menu_anchor.dart:1206]: This isn't all bad.  The default implementation is a no-op, and if directional traversal hasn't happened, then it's empty anyhow. The main use of the scope data is to keep the previous nodes that have been visited since the last invalidation so that when you traverse one direction and reverse, that it takes the same path on the way back as it did on the way there (to avoid hysteresis). Since menus kind of only have one path here, it's probably not going to matter if you nuke that information.

**Comment by davidhicks980** [comment]
Update: Issue appears to be fixed -- should be ready to merge.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
