### PR TITLE
Use AppBar.systemOverlayStyle to style system navigation bar

### LINKED ISSUE #104410: systemNavigationBarColor not honoured on Android
## Steps to Reproduce

1. Execute `flutter run` on the code sample using an Android Emulator API 31 

**Expected results:** Navigation bar should be green

**Actual results:** Navigation bar is black

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        appBarTheme: AppBarTheme(
          systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(
            systemNavigationBarColor: Colors.green,
          ),
        ),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

`AppBar.systemOverlayStyle` exposes properties to set system navigation bar style.
Those properties are not applied because the `AnnotatedRegion` created by an AppBar is on the top of the screen and RenderView does not use the annotated region on the top to style the system navigation bar.

To set the system navigation bar style, Flutter developers should create a second AnnotatedRegion on the bottom of the screen. This is not intuitive as system navigation properties are available when setting `AppBar.systemOverlayStyle` and this is not convenient, as explained [<ins>in this comment</ins>](https://github.com/flutter/flutter/issues/100027#issuecomment-1077697819).

This PR updates how `RenderView` creates a system overlay style.
Before, it looked up for a top annotated region to style the status bar and a bottom annotated region to style the system navigation bar.
After, if only one of the top or the bottom annotated region is found, it will be used to style the status bar and the system navigation bar. If both are found, it will work as before.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/104410

## Tests

Adds 1 test in material/app_bar_test.dart
Adds 3 tests in rendering/view_chrome_style_test.dart

### CODE REVIEW

**Comment by rydmike** [comment]
Would be nice if this could merged. 
ping @darrenaustin  😄 💙

**Comment by rydmike** [comment]
Would still be nice to get this reviewed and merged, ping @darrenaustin @HansMuller 😄

File: packages/flutter/lib/src/rendering/view.dart [hunk 1]
```diff
@@ -293,9 +298,11 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
     final SystemUiOverlayStyle? upperOverlayStyle = layer!.find<SystemUiOverlayStyle>(top);
     // Only android has a customizable system navigation bar.
     SystemUiOverlayStyle? lowerOverlayStyle;
+    bool isAndroid = false;
```
Comment (a-wallen) [inline packages/flutter/lib/src/rendering/view.dart:301]: This becomes convenient later in the code. Instead of assigning it in the switch statement, I suggest that we assign it with 
```dart
bool isAndroid = defaultTargetPlatform == TargetPlatform.android;
```

File: packages/flutter/lib/src/rendering/view.dart [hunk 2]
```diff
@@ -304,20 +311,40 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
...
+        systemNavigationBarColor: lowerOverlayStyle.systemNavigationBarColor,
+        systemNavigationBarDividerColor: lowerOverlayStyle.systemNavigationBarDividerColor,
+        systemNavigationBarIconBrightness: lowerOverlayStyle.systemNavigationBarIconBrightness,
+        systemNavigationBarContrastEnforced: lowerOverlayStyle.systemNavigationBarContrastEnforced,
       );
       SystemChrome.setSystemUIOverlayStyle(overlayStyle);
+      return;
     }
+    // If only one of upper or bottom overlay style is not null, it provides all properties
+    // System navigation bar should be set only in Android.
```
Comment (a-wallen) [inline packages/flutter/lib/src/rendering/view.dart:335]: Move the `isAndroid` initialization here, as this is where it becomes relevant.

**Comment by a-wallen** [comment]
@bleroux I just want to let you know that I'm still looking at this. There seem to be a lot of issues regarding the system navigation bar. I'm wondering if I could get your help gathering all of those issues into one place so that we can see what issues people are having and whether or not these changes are the best solution for a majority of cases. Feel free to message me on Discord (a-wallen)

**Comment by bleroux** [comment]
@a-wallen 
Many thanks for your feedback. It’s a complex area so collecting issues related to the system navigation bar is a great way to make progress. For the moment, we can start to list those related issues here (by editing this comment and the list below) and see where it leads us.

My first take is that several issues are related to different Android SDK versions and also Android `SystemUIMode` (immersive, edgeToEdge,...). And to get further complication some of those issues are device specific.

My second take is that Flutter gives two options to configure the system navigation bar:
- An imperative way using `SystemChrome`
- A declarative way (which relies on `AnnotatedRegion` and calling the imperative API on every frame). It was Introduced by the following PR: https://github.com/flutter/flutter/pull/17672 (design described here https://github.com/flutter/flutter/issues/4630#issuecomment-371324100).

My PR targets the declarative way and it could be considered as a developer experience improvement. Rydmike described this in a very thorough comment: https://github.com/flutter/flutter/issues/100027#issuecomment-1077697819.

As a starting point, I classified several issues I found using this two categories (imperative vs declarative):

### Imperative 
- https://github.com/flutter/flutter/issues/108855
- https://github.com/flutter/flutter/issues/89774 (great summary of edgeToEdge limitations depending on Android version).
- https://github.com/flutter/flutter/issues/90098 (lot of good information. Closed because it was splitted in two separate actionable issues: https://github.com/flutter/flutter/issues/105714 and https://github.com/flutter/flutter/issues/105716
- https://github.com/flutter/flutter/issues/95403 (edgeToEdge and device specific)
- https://github.com/flutter/flutter/issues/108855 (device specific)
- https://github.com/flutter/flutter/issues/59130 (which seems to be a misunderstanding related to an imperative call overridden by the implicit addition of AnnotatedRegion when there is an AppBar).

### Declarative
- https://github.com/flutter/flutter/issues/100027 (with many insights from rydmike about what could be done to improve the documentation, partially fixed by https://github.com/flutter/engine/pull/32167)
- https://github.com/flutter/flutter/issues/76384 (fixed by https://github.com/flutter/engine/pull/32167)
- https://github.com/flutter/flutter/issues/54029 (iOS)
- https://github.com/flutter/flutter/issues/104410 (where I commented https://github.com/flutter/flutter/issues/104410#issuecomment-1137224408  after analyzing various issues and leads me to this PR)
- https://github.com/flutter/flutter/issues/21265 (onResume issue where the proposed solution was to switch to the declarative way, but people seems to be confused by AppBar overridden their values, see https://github.com/flutter/flutter/issues/21265#issuecomment-579402863)
- https://github.com/flutter/flutter/issues/39132 (seems to be the same confusion)

**Comment by a-wallen** [comment]
@bleroux I'm going to follow up on your comment, but before I do I think that we should make an issue called `SystemNavigationBar APIs are confusing`. If this gets merged, the Github bot will lock this thread. I'd rather have an issue where there can be a conversation around this issue. If enough people give a 👍 on that issue, the team will focus more of their attention to making the API easier to use.

File: packages/flutter/lib/src/rendering/view.dart [hunk 3]
```diff
@@ -303,20 +308,42 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
...
     }
-    // If there are no overlay styles in the UI don't bother updating.
-    if (upperOverlayStyle != null || lowerOverlayStyle != null) {
+    // If there are no overlay style in the UI don't bother updating.
+    if (upperOverlayStyle == null && lowerOverlayStyle == null) {
+      return;
+    }
+
+    // If both are not null, the upper provides the status bar properties and the lower provides
+    // the system navigation bar properties.
```
Comment (a-wallen) [inline packages/flutter/lib/src/rendering/view.dart:317]: Readability: Could you provide a brief explanation for why we do this?

File: packages/flutter/lib/src/services/system_chrome.dart [hunk 4]
```diff
@@ -558,7 +558,8 @@ class SystemChrome {
   /// it can be hit-tested by the framework. On every frame, the framework will
   /// hit-test and select the annotated region it finds under the status and
   /// navigation bar and synthesize them into a single style. This can be used
-  /// to configure the system styles when an app bar is not used.
+  /// to configure the system styles when an app bar is not used. When an app
+  /// bar is used an annotated region is automatically created.
```
Comment (a-wallen) [inline packages/flutter/lib/src/services/system_chrome.dart:562]: Explain the combinations behind this. What happens when I set the system style _and_ there's an AppBar.

**Review by a-wallen — COMMENTED** [review]
I'm up to speed now, but still not sure that we want this change. For the most part things seem to be working as intended, but are poorly documented.

File: packages/flutter/lib/src/rendering/view.dart (hunk 3 above)
Comment (bleroux) [reply packages/flutter/lib/src/rendering/view.dart:317]: > Readability: Could you provide a brief explanation for why we do this?

Sorry, do you mean by updating this comment in `view.dart` or by commenting here on Github?

**Comment by bleroux** [comment]
> I'm up to speed now, but still not sure that we want this change. For the most part things seem to be working as intended, but are poorly documented.

IMHO, while improving the documentation will help, it won't make the API less "frustrating" as describe [<ins>in this comment</ins>](https://github.com/flutter/flutter/issues/100027#issuecomment-1077697819). 

The same comment from @rydmike also explains why it could make sense to argue against this change (but also why this change would be preferable :smile: ) :
_"One could argue that this makes sense, since we are defining things for an AppBar that does not really have anything to do with the system navigation bar. On the other hand the properties are there, if they have no impact, they should not exists at all in the used AppBar "systemOverlayStyle" config class. Or at the least it is should be very clearly documented that they have no impact and that you have to set them via an AnnotatedRegion. But why not let them work also via the AppBar?"_

I fully agree that "updating the code" vs "updating the documentation" is a valid concern. So before pursuing work on this PR, a decision should be taken.

**Comment by a-wallen** [comment]
> it won't make the API less "frustrating" as describe in this comment.

Yes, it is frustrating! 

If it were me, I would want this change, but my opinion doesn't scale to the MANY users that we have 😅. 

I asked for a second review by @Piinks during our triage meeting yesterday, she might have better insight. Hopefully we can move things forward that way. And, I agree that you should not put in effort until we've made a decision about this change.

**Review by Piinks — COMMENTED** [review]
As far as I know, the AppBar intentionally only applies to the status bar (and not the navigation bar) because the AppBar renders into the status bar area. I think the intention is that since the user can set the AppBar to be any color, it will set the status bar overlay style to avoid the status bar time, date etc from being obscured.

Assuming the same style should be applied to the navigation bar gives me pause. There may not be a navigation bar, or the user may be using edge to edge. This could result in the navigation buttons not being visible to the user.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 5]
```diff
@@ -883,7 +883,13 @@ class _AppBarState extends State<AppBar> {
     final SystemUiOverlayStyle style = brightness == Brightness.dark
       ? SystemUiOverlayStyle.light
       : SystemUiOverlayStyle.dark;
-    return style.copyWith(statusBarColor: backgroundColor);
+    // For backward compatibility, create an overlay style without system navigation bar settings.
+    return SystemUiOverlayStyle(
+      statusBarColor: style.statusBarColor,
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/app_bar.dart:888]: Good catch! If we pursue work on this PR, I will also try to find why this bug does not break any tests.

**Comment by bleroux** [comment]
Hey @Piinks!

> Assuming the same style should be applied to the navigation bar gives me pause. There may not be a navigation bar, or the user may be using edge to edge. This could result in the navigation buttons not being visible to the user.

Maybe I misread your comment, but this PR only aims to apply `AppBar.systemOverlayStyle.systemNavigationBarColor` property (and similar navigation bar properties) when the user sets them (from your comment, I understand that you fears that this PR is applying some `AppBar.systemOverlayStyle` status bar related properties to the navigation bar or tried to compute default values, really sorry if I misread). 

For the moment, we get issues filed by users who tried code similar to :
```dart
      appBar: AppBar(
        systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(
          systemNavigationBarColor: Colors.green, // ignored
        ),
      ),
```

As those properties are ignored it leads to frustration (users assume it should work because those properties are documented in `SystemUiOverlayStyle` and exposed when using completion). And the solution is not obvious, see <ins>https://github.com/flutter/flutter/issues/104410#issuecomment-1139585569</ins> (which is the discussion that leads me to this PR).

If `AppBar.systemOverlayStyle` is a bad place to set them, ideally, those properties should not be exposed (but this will probably be a breaking change as it might mean changing `AppBar.systemOverlayStyle` type).

This PR aims to apply those properties without introducing a breaking change and without overriding the values set in a bottom `AnnotatedRegion` (when there is one).

I wrote this PR some months ago, maybe there are bugs in it (you already find one :smile:) or maybe the code is not aligned with the goal I had in mind, but before pursuing work, we (@a-wallen and I) reached the conclusion that a decision should be made on agreeing or not that the goal of this PR is a valid concern.

**Comment by Piinks** [comment]
Hey @bleroux thank you for the additional context! I think this change is ok to make (modulo that one bug 😉 ), we should double check that it is not breaking though. If you would, can you fix the background color, then I'll run this through some extra testing internally to see if anything breaks. 👍

File: packages/flutter/lib/src/rendering/view.dart [hunk 6]
```diff
@@ -112,6 +112,11 @@ class RenderView extends RenderObject with RenderObjectWithChildMixin<RenderBox>
   /// and the hit-test result from the bottom of the screen provides the system
   /// nav bar settings.
   ///
+  /// If there is no AnnotatedRegionLayer on the bottom, the hit-test result
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/rendering/view.dart]: Done

File: packages/flutter/lib/src/material/app_bar.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/app_bar.dart]: I fixed this bug and I added a test as there was no existing test covering this (it is somewhat new because the 'backgroundColor' parameter is non-null only when using Material 3). 
Thanks a lot for spotting this!

**Comment by bleroux** [comment]
@Piinks Great! 
I have updated the PR (and add one test, see my comment above).

> I'll run this through some extra testing internally to see if anything breaks

:crossed_fingers: :crossed_fingers: :smile:

**Comment by Piinks** [comment]
Tests are running, will circle back with results.

**Comment by Piinks** [comment]
Tests passed!

File: packages/flutter/lib/src/rendering/view.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/view.dart:317]: I think here in `view.dart`, although the comments explaining `top` and `bottom` above are helpful. Maybe just providing an example of why there would be more than one, an upper and a lower?

File: packages/flutter/lib/src/services/system_chrome.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/services/system_chrome.dart:562]: +1

**Review by Piinks — APPROVED** [review]
LGTM-stamp
