### PR TITLE
Scroll text fields when the caret moves outside the viewport

### LINKED ISSUE #9923: Single line TextField does not scroll as you type
Most apps have it such that if you are typing into a textfield, and your input exceeds the size of the view, it will scroll so that you can continue to see what you are typing.  This doesn't happen with the TextField widget.

## Steps to Reproduce

Setup a single line TextField, then type into it until the content exceeds the size of the widget.  

Also, this is currently happening in the flutter gallery app that is in the play store, version flutter-gallery-bv8-rc000, within the Text fields demo.

Edit: Tested with most recent flutter code as well, and issue is still seen.

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/9923

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -25,6 +25,11 @@ final String _kZeroWidthSpace = new String.fromCharCode(0x200B);
 /// Used by [RenderEditable.onSelectionChanged].
 typedef void SelectionChangedHandler(TextSelection selection, RenderEditable renderObject, bool longPress);
 
+/// Signature for the callback that reports when the caret location changes.
+///
+/// Used by [RenderEditable.onCaretChanged].
+typedef void CaretChangedHandler(Rect caretRect);
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: FWIW, `ValueChanged<Rect>` is the same signature. (It's fine to keep this though. We often have redundant typedefs, especially in cases where we can then hook more documentation to them.)

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -89,6 +95,11 @@ class RenderEditable extends RenderBox {
 
   double _textLayoutLastWidth;
 
+  /// Called when the caret location changes.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/editable.dart]: We should mention here that this is called during the paint phase.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -445,6 +445,19 @@ class EditableTextState extends State<EditableText> implements TextInputClient {
...
 
+  bool _textChangedSinceLastCaretUpdate = false;
+
+  void _handleCaretChanged(Rect caretRect) {
+    // If the caret location has changed due to an update to the text or
+    // selection, then scroll the caret into view.
+    if (_textChangedSinceLastCaretUpdate) {
+      _textChangedSinceLastCaretUpdate = false;
+      scheduleMicrotask(() {
+        _scrollController.jumpTo(_getScrollOffsetForCaret(caretRect));
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Can we make this an animateTo() ?

If we make it jumpTo(), then we're going to have a one-frame delay where we'll always first show the text field overflowing, then we'll shift it into view. If we use animateTo(), then we'll be smoothly scrolling the text field the whole time.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/editable_text.dart]: (If we want to use jumpTo and not animate, then the approach here is wrong; we should be testing for the caret being out of view during the animation phase, then changing the scroll offset then, so that we never paint it with the overflow.)

**Comment by Hixie** [comment]
test?

**Comment by jason-simmons** [comment]
Updated based on feedback, plus a test - PTAL

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -445,6 +445,21 @@ class EditableTextState extends State<EditableText> implements TextInputClient {
...
+  bool _textChangedSinceLastCaretUpdate = false;
+
+  void _handleCaretChanged(Rect caretRect) {
+    // If the caret location has changed due to an update to the text or
+    // selection, then scroll the caret into view.
+    if (_textChangedSinceLastCaretUpdate) {
+      _textChangedSinceLastCaretUpdate = false;
+      _scrollController.animateTo(
+        _getScrollOffsetForCaret(caretRect),
+        curve: Curves.linear,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Let's try `Curves.fastOutSlowIn` and see how it feels. That's the usual material curve.

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -112,6 +112,7 @@ void main() {
         expect(textFieldValue, equals(testValue));
 
         await tester.pumpWidget(builder());
+        await tester.pump(const Duration(milliseconds: 200));
```
Comment (Hixie) [inline packages/flutter/test/material/text_field_test.dart]: if it's not too much of a pain, can you add "// skip past the scrolling animation" or some such to these? it'll make it easier to figure out why we're pumping randomly when debugging these tests in the future.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/widgets/editable_text.dart]: done

File: packages/flutter/test/material/text_field_test.dart (hunk 5 above)
Comment (jason-simmons) [inline packages/flutter/test/material/text_field_test.dart]: done

**Comment by abarth** [comment]
So, if you rotate the phone and that causes the text field to change size and makes the caret invisible, we don't want to scroll it into view?

**Comment by jason-simmons** [comment]
The textChangedSinceLastCaretUpdate check is needed to allow users to move the caret out of view intentionally with a scroll gesture.

With this change, after a rotation the scrollable viewport will reset to offset zero, but if you type a character the viewport will then scroll to the current caret location.  We could add something that sets the initial viewport offset to include the caret after rotation.

**Comment by Hixie** [comment]
Why does it reset to zero? I would have expected it to not change scroll position at all.

**Comment by jason-simmons** [comment]
Weird - in some initial testing I thought I saw the field resetting to the leftmost position, but now it looks like it's retaining the offset after a rotation.  If the field has gone from wider to narrower, then the caret might be outside the viewport post-rotation.

**Comment by abarth** [comment]
Yes, makes sense.  Another way to do this is have the text-changed handler schedule a post-frame callback to check the cursor position.  During the post-frame callback, you can set the scroll position directly (using jumpTo) rather than using an animation.  I think that might be slightly cleaner.  (Sorry for sending you down the wrong path initially.)

**Comment by Hixie** [comment]
I don't think you want to do anything in a post-frame callback. That would lead to the problem I describe above where you see one frame wrong before it shifts, which looks amateurish. We should either compute the right answer before layout, or we should animate (as per this patch).

**Comment by abarth** [comment]
There are some subtle bugs with this patch:

1. If the text value changes (e.g., if the composing rejoin changes), we'll arm the _textChangedSinceLastCaretUpdate bool, but we won't get a _handleCaretChanged because the caret rect doesn't change.
2. If the caret rect later changes for some other reason (e.g., the phone rotates and the layout changes), normally we won't scroll the cursor into view but because of (1) we now will.

I think it would be reasonable to land this patch and file a bug about this remaining (much less severe) issue.

LGTM
