### PR TITLE
Fix Xcode 15 build failure due to DT_TOOLCHAIN_DIR

### LINKED ISSUE #132755: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS
Test `Mac build_ios_framework_module_test` fails on Xcode 15 beta 6 and macOS 13.5.

https://logs.chromium.org/logs/flutter/led/vashworth_google.com/04e485a0b152a0720f5e561266f7a6e4fb64fc76227fcacc95b67486ae2771e7/+/u/run_build_ios_framework_module_test/test_stdout

Looks like Cocoapods already has a fix in ([Issue](https://github.com/CocoaPods/CocoaPods/issues/12012), [Fix](https://github.com/CocoaPods/CocoaPods/pull/12009)). We're either going to need to upgrade Cocoapods or do our own fix.

### PR DESCRIPTION
**Pull request by vashworth**
Starting in Xcode 15, when building macOS, DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS or LIBRARY_SEARCH_PATHS. `xcodebuild` error message recommend using TOOLCHAIN_DIR instead.

Since Xcode 15 isn't in CI, I tested it in a one-off `led` test:
* [Pre-fix failure](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/vashworth_google.com/04e485a0b152a0720f5e561266f7a6e4fb64fc76227fcacc95b67486ae2771e7/+/build.proto)
* [Post-fix success](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/vashworth_google.com/d454a3e181e1a97692bdc1fcc197738fe04e4acf1cb20026fd040fd78513f3b0/+/build.proto)

Fixes https://github.com/flutter/flutter/issues/132755.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/migrations/cocoapods_toolchain_directory_migration.dart [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    for (final FileSystemEntity file in files) {
+      if (file.basename.endsWith('xcconfig') && file is File) {
+        processFileLines(file);
+      }
+    }
+  }
+
+  @override
+  String? migrateLine(String line) {
+    if (line.startsWith('LD_RUNPATH_SEARCH_PATHS') || line.startsWith('LIBRARY_SEARCH_PATHS')) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/migrations/cocoapods_toolchain_directory_migration.dart:53]: will this always be at the start of the line, or might there be leading whitespace?

**Review by christopherfujino — APPROVED** [review]
One question about whether the pattern matching should allow leading whitespace, otherwise LGTM

File: packages/flutter_tools/lib/src/migrations/cocoapods_toolchain_directory_migration.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/migrations/cocoapods_toolchain_directory_migration.dart]: It's a Cocoapods-generated file, so it shouldn't have leading whitespace. I added a change to trim it out before comparison anyways, just in case/future-proofing

**Comment by lukaszciastko** [comment]
I tried this fix, but I am still getting this error using latest Flutter stable and Xcode 15 in an existing project.

**Comment by vashworth** [comment]
> I tried this fix, but I am still getting this error using latest Flutter beta and Xcode 15 in an existing project.

@lukaszciastko Could you please file a issue describing your error and include reproducible steps?

**Comment by lukaszciastko** [comment]
> > I tried this fix, but I am still getting this error using latest Flutter beta and Xcode 15 in an existing project.
> 
> @lukaszciastko Could you please file a issue describing your error and include reproducible steps?

The issue is exactly the same. Your fix doesn't work for my app, but it works when I create a new app. Having said that, none of the workarounds people are suggesting on the Internet have worked for me. I don't think I can include reproducible steps, because I don't know myself what causes it and an empty app works. I can see someone else mentioned here they are also having this issue with the latest Flutter: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1729216133. I guess all I can do is keep investigating...
