### PR TITLE
📝 Added tests for toString to increase coverage

### LINKED ISSUE #82232: Add `toString` tests to increase coverage
Add `toString` tests for `NetworkAssetBundle`, `MethodCall`, `PlatformException`, `MissingPluginException`, `AndroidPointerProperties`, `AndroidPointerCoords` and `AndroidMotionEvent`.

### PR DESCRIPTION
**Pull request by werainkhatri**
Added toString tests for `NetworkAssetBundle`, `MethodCall`, `PlatformException`, `MissingPluginException`, `AndroidPointerProperties`, `AndroidPointerCoords`,  `AndroidMotionEvent` and `SystemUiOverlayStyle`.

Fixes #82232 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/services/platform_views_test.dart [hunk 1]
```diff
@@ -300,4 +300,46 @@ void main() {
       );
     });
   });
+
+  test('toString works as intended', () async {
+    const AndroidPointerProperties androidPointerProperties = AndroidPointerProperties(id: 0, toolType: 0);
+    const androidPointerCoords =
+    AndroidPointerCoords(orientation: 0.0, pressure: 0.0, size: 0.0, toolMajor: 0.0, toolMinor: 0.0, touchMajor: 0.0, touchMinor: 0.0, x: 0.0, y: 0.0);
+    final AndroidMotionEvent androidMotionEvent = AndroidMotionEvent(
+        downTime: 0,
```
Comment (jonahwilliams) [inline packages/flutter/test/services/platform_views_test.dart:309]: use 2 space indent here

File: packages/flutter/test/services/platform_views_test.dart [hunk 2]
```diff
@@ -300,4 +300,46 @@ void main() {
...
+        yPrecision: 0.0,
+        deviceId: 0,
+        edgeFlags: 0,
+        source: 0,
+        flags: 0,
+        motionEventId: 0
+    );
+
+    expect(androidPointerProperties.toString(), 'AndroidPointerProperties(id: 0, toolType: 0)');
+    expect(androidPointerCoords.toString(),
```
Comment (jonahwilliams) [inline packages/flutter/test/services/platform_views_test.dart:327]: same here and elsewhere

**Review by jonahwilliams — APPROVED** [review]
LGTM
