### PR TITLE
fix RangeSlider, with no overlayShape shifts to the left

### LINKED ISSUE #125467: RangeSlider, with no overlayShape shifts to the left ,There is a problem with width calculation
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

RangeSlider drawn out of bounds 
image

### Expected results

image

### Actual results

image

### Code sample

<details><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  double singleValue = 0;
  RangeValues rangeValue = RangeValues(0, 10);

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: SliderTheme(
        data: SliderThemeData(
          overlayShape: SliderComponentShape.noOverlay,
        ),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Slider(
                  value: singleValue,
                  min: 0,
                  max: 100,
                  onChanged: (value) {
                    setState(() {
                      singleValue = value;
                    });
                  }),
              RangeSlider(
                  values: rangeValue,
                  min: 0,
                  max: 100,
                  onChanged: (value) {
                    setState(() {
                      rangeValue = value;
                    });
                  })
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by arvinwli**
fixes  https://github.com/flutter/flutter/issues/125467

--------------------------

fix RectangularRangeSliderTrackShape and RoundedRectRangeSliderTrackShape. These two RangeSliderTrackShape do not take into account the width of RangeThumbShape. If the width of RangeThumbShape is larger than the width of OverlayShape, the RangeSlider will be drawn out of bounds and the display will not meet expectations. And the Slider trackShape calculation logic is in line with expectations, the modified reference BaseSliderTrackShape here, write a new BaseRangeSliderTrackShape

**BaseSliderTrackShape takes the width of the thumbShape into account when calculating 。left As follows**
image
**But RoundedRectRangeSliderTrackShape did not consider rangeThumbShape RoundedRectRangeSliderTrackShape width, as follows**
image
**Therefore, the modification plan is:**
- Create BaseRangeSliderTrackShape reference BaseSliderTrackShape getPreferredRect**
- The core modification is to consider the width of rangeThumbShape when calculating the left of RangeSliderTrackShape

image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/slider_theme_test.dart [hunk 1]
```diff
@@ -1430,6 +1430,51 @@ void main() {
...
+    );
+
+    // The track rectangle begins at 10 pixels from the left of the screen and ends 10 pixels from the right
+    // (790 pixels from the left). The main check here it that the track itself should be centered on
+    // the 800 pixel-wide screen.
+    expect(
+      material,
+      paints
+      // active track RRect. Starts 10 pixels from left of screen.
+        ..rrect(rrect: RRect.fromLTRBAndCorners(
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_theme_test.dart:1452]:
```suggestion
        // active track RRect. Starts 10 pixels from left of screen.
        ..rrect(rrect: RRect.fromLTRBAndCorners(
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for the PR! This looks good to me with some format fixes

**Comment by arvinwli** [comment]
@TahaTesser Thanks for these  format fixes. I have commit submitted these fixes

**Review by TahaTesser — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Review by werainkhatri — APPROVED** [review]
LGTM! thanks for your contribution! nice work creating the mixin.

TIL dart supports writing a mixins to override inherited methods. wow.

**Comment by TahaTesser** [comment]
Looks like even tho the tree is green, `autosubmit` doesn't merge the PR. Similar to this [case](https://github.com/flutter/flutter/pull/125599#issuecomment-1525387603)

**Comment by Piinks** [comment]
Strange! What a stubborn bot. Merging!
