### PR TITLE
Segmented control quick double tap fix

### LINKED ISSUE #43414: CupertinoSegmentedControl not working when tap and then quick long press
will stop work when tap and then long press the segment control

[CupertinoSegmentedControl](https://github.com/flutter/flutter/blob/3a3939a7fab6e2db7615d71643a8794d103a3e7f/packages/flutter/lib/src/cupertino/segmented_control.dart#L336)

```dart
if (currentKey != widget.groupValue && currentKey == _pressedKey) {
      widget.onValueChanged(currentKey);
      _pressedKey = null;
    }
```
need to reset `_pressedKey = null;` in any condition

```dart
if (currentKey != widget.groupValue && currentKey == _pressedKey) {
      widget.onValueChanged(currentKey);
    }
_pressedKey = null;
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

This is a quick fix for the issue where double tapping `CupertinoSegmentedControl` breaks its internal state. The bug is quite hard to reproduce since it requires the second tap to land before the widget gets a chance to update (i.e., after `setState` but before the next build/layout phase). 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/43414

## Tests

I added the following tests:

- Quick double tap doesn't break the internal state

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/cupertino/segmented_control_test.dart [hunk 1]
```diff
@@ -1384,6 +1384,47 @@ void main() {
...
+        },
+      ),
+    );
+
+    await tester.tap(find.text('B'));
+    // sharedValue has been updated but widget.groupValue is not.
+    expect(sharedValue, 1);
+
+    // Land the second tap before the widget gets a chance to rebuild.
+    final TestGesture secondTap = await tester.startGesture(tester.getCenter(find.text('B')));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/segmented_control_test.dart]: Is there a reason that the second tap has to be `startGesture` instead of `tap`?   Is this way faster?

**Review by justinmc — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/segmented_control_test.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/cupertino/segmented_control_test.dart]: The sequence of events that leads to this bug is: 

- The first tap finishes, `setState` gets called in the user callback.
- The tap down event of the second tap happens
- The segmented control gets rebuild with the new `groupValue`
- The tap up event of the second tap happens.

The test basically follows these steps so the second tap had to be broken up into a tap down and a tap up event.

Comment (justinmc) [reply packages/flutter/test/cupertino/segmented_control_test.dart]: Got it, thanks for the explanation.

**Review by HansMuller — APPROVED** [review]
LGTM too
