### PR TITLE
Make AppContext immutable and race-free

### LINKED ISSUE #15352: AppContext is prone to races
### Problem

https://github.com/flutter/flutter/blob/7d1ceb408022f807b84ac93c340b3f5170f8b237/packages/flutter_tools/lib/src/base/context.dart#L74-L79

That code is designed to say "while the callback is running in this context, set up the Zone pointer such that it can properly traverse the context hierarchy."  However, there's a flaw in that logic, which is that code triggered by that callback may still be run after the `await method()` completes.

* There could have been an unintentional unawaited future within `method()`.
* There could have been a `Future.then()` call within `method()`, where we intentionally don't wait for the body of the `then()` to complete.
* We could have created a stream listener that's still responding to events after `method()` completes.

In these types of cases, we'll have already mutated the `AppContext._zone` pointer after `await method()` returns, and when the async code in question runs after that point, its zone pointer will be invalid (causing it to skip the parent zone), and it'll be unable to lookup proper `AppContext` values.

Practically speaking, this is likely the cause of issues such as https://github.com/flutter/flutter/issues/14636

### Proposed Solution

We should make `AppContext` immutable.  Proposed API:

```dart
/// Generates an [AppContext] value.
typedef dynamic Generator();

/// The current [AppContext], as determined by the [Zone] hierarchy.
///
/// This will be the first context found as we scan up the zone hierarchy, or
/// the "root" context if a context cannot be found in the hierarchy. The root
/// context will not have any values associated with it.
AppContext get context;

/// A lookup table (mapping types to values) and an implied scope, in which
/// code is run.
///
/// [AppContext] is used to define a singleton injection context for code that
/// is run within it. Each time you call [run], a child context (and a new
/// scope) is created.
///
/// Child contexts are created and run using zones. To read more about how
/// zones work, see https://www.dartlang.org/articles/libraries/zones.
class AppContext {
  /// Gets the value associated with the specified [type], or `null` if no
  /// such value has been associated.
  dynamic operator[](Type type);

  /// Runs [method] in a child context and returns the value.
  ///
  /// If [overrides] is specified, the child context will include the associated
  /// type mappings, overriding any conflicting mappings in this (the parent)
  /// context.
  ///
  /// If [fallbacks] is specified, the child context will include the associated
  /// type mappings only for those types not already contained in this (the
  /// parent) context.
  ///
  /// If [name] is specified, the child context will be assigned the given name.
  /// This is useful for debugging purposes and is analogous to naming a thread
  /// in Java.
  ///
  /// If [onError] is specified, the zone is considered an error zone. All
  /// uncaught errors (synchronous or asynchronous) in the zone are caught and
  /// handled by the callback.
  FutureOr<dynamic> run({
    @required FutureOr<dynamic> method(),
    Map<Type, dynamic> overrides,
    Map<Type, Generator> fallbacks,
    String name,
    ZoneBinaryCallback<dynamic, dynamic, StackTrace> onError,
  });
}
```

### PR DESCRIPTION
**Pull request by tvolkert**
This updates AppContext per the recommendations in #15352

Fixes #15352

### CODE REVIEW

**Comment by tvolkert** [comment]
@yjbanov @Hixie I committed this in steps to make it easier to review.  I recommend viewing one commit at a time.

File: packages/flutter_tools/lib/src/context_runner.dart [hunk 1]
```diff
@@ -2,40 +2,73 @@
...
-    context.putIfAbsent(FileSystem, () => const LocalFileSystem());
-    context.putIfAbsent(ProcessManager, () => const LocalProcessManager());
-    context.putIfAbsent(Logger, () => new StdoutLogger());
-    context.putIfAbsent(Cache, () => new Cache());
-    context.putIfAbsent(Config, () => new Config());
-    context.putIfAbsent(OperatingSystemUtils, () => new OperatingSystemUtils());
-    context.putIfAbsent(Usage, () => new DisabledUsage());
-    return runner(args);
-  });
+T runInContext<T>(
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/context_runner.dart]: I recommend making this return `Future<T>`.

This is because otherwise if you ever consider adding any async code here, and you create a Completer<T>, you won't be able to complete it, because passing a Future to a Completer unwraps the future and causes a type error.

File: packages/flutter_tools/lib/src/base/context.dart [hunk 2]
```diff
@@ -3,79 +3,186 @@
...
+  ContextDependencyCycleException._(this.cycle);
+
+  /// The dependency cycle (last item depends on first item).
+  final List<Type> cycle;
+
+  @override
+  String toString() {
+    final StringBuffer buf = new StringBuffer('Dependency cycle detected: ');
+    buf.write(cycle.join(' -> '));
+    return buf.toString();
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/base/context.dart]: nit: this is the same as: `=> 'Dependency cycle detected: ${cycle.join(' -> ')}'`

File: packages/flutter_tools/lib/src/context_runner.dart (hunk 1 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/context_runner.dart]: Done

File: packages/flutter_tools/test/base/context_test.dart [hunk 3]
```diff
@@ -2,100 +2,260 @@
...
+                  return context[String];
+                },
+                fallbacks: <Type, Generator>{
+                  String: () => 'child',
+                },
+              );
+            },
+          );
+          expect(called, isTrue);
+          expect(value, 'child');
```
Comment (yjbanov) [inline packages/flutter_tools/test/base/context_test.dart]: Did you mean to put `called = true` into a parent generator? I can't tell which check shows that the parent was consulted.

File: packages/flutter_tools/lib/src/context_runner.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/context_runner.dart]: Or perhaps `FutureOr<T>`?

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

File: packages/flutter_tools/test/base/context_test.dart (hunk 3 above)
Comment (tvolkert) [reply packages/flutter_tools/test/base/context_test.dart]: No, this just exists to make sure that `context.run` didn't skip the body entirely.  I originally had a "parent consulted" check, but that can't work, because if the parent is consulted, it means it had a generator, so the fallback would never be consulted...

File: packages/flutter_tools/lib/src/context_runner.dart (hunk 1 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/context_runner.dart]: No, `runner` had to be made `FutureOr<T>`, but this now definitely returns `Future<T>`

File: packages/flutter_tools/test/base/context_test.dart (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/test/base/context_test.dart]: Ah, got it. I was confused by the test description. I thought the test somehow tracked when the fallbacks are consulted relative to the parent.

**Review by yjbanov — APPROVED** [review]

**Comment by Hixie** [comment]
This mostly seems fine but I'm still a bit concerned that you sometimes run with a type that's a `Future<x>`. I think I would just always use async, that way it's always consistent about what you're doing.

The problem with sometimes expecting a `Future<x>` is that if you ever need to wrap it in something async, it's going to try to unpack the value, which will be a source of weird bugs.

Also sometimes you don't type the call to `run<T>`.

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/pull/16034

**Comment by aam** [comment]
This seems to have broken running flutter with local engine:
```
flutter run -v --local-engine android_debug_unopt_x86

## exception

ArgumentError: Invalid argument(s): join(null, "../engine/src"): part 0 was null, but part 1 was not.

#0      _validateArgList (package:path/src/context.dart:1088:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      FlutterCommandRunner._findEnginePath (package:flutter_tools/src/runner/flutter_command_runner.dart:327:51)
```

Reason for the failure is that now we use `Cache.flutterRoot` in `_findEnginePath` before it had a chance to get initialized `Cache.flutterRoot = fs.path.normalize(fs.path.absolute(flutterRoot));`

**Comment by tvolkert** [comment]
@aam, fixed in https://github.com/flutter/flutter/pull/16057
