### PR TITLE
Fix abstract_method_smoke_test flakiness

### LINKED ISSUE #42349: Android Firebase Test Lab run is flaky because PlatformException(error, Neither user 10218 nor current process has android.permission.WAKE_LOCK., null)
This seems to be extremely flaky and numerous runs have run into the same. An example is the [engine roll](https://cirrus-ci.com/build/flutter/flutter/85cc31319a5c445a5714a3031413567826c56f7e)  which failed on the [release_smoke_tests](https://cirrus-ci.com/task/5683028134723584) because of a [test lab run whose dashboard is here](https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/7537779313191336608).

### PR DESCRIPTION
**Pull request by mklim**
## Description

The flake appears to be coming from the Google Maps plugin. This test
just needs a platform view plugin without the interface method
implemented in general, not Maps specifically.  Update it here to avoid
the issue in Maps until that's fixed.

Create a very simple platform view implementation that exercises this
potential bug in order to create a minimal test case with less risk of
causing second order issues like depending on any kind of full package
would cause.

## Related Issues

Fixes #42349
See also #42451

## Tests

- Updated abstract_method_smoke_test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM!

**Review by blasten — APPROVED** [review]

**Comment by mklim** [comment]
Hmm. Is there a way to tell the analyzer to ignore an "invalid" dependency? I'm deliberately using an outdated version of `webview_flutter` because that's the version of the package that would cause this test to go red without the fix. I know normally you can use `ignore: ` for analyzer lints, but I'm having trouble finding the right name for this one.

**Comment by mklim** [comment]
OK, updated the test to use a simple custom platform view instead of relying on a plugin at all. @blasten and @dnfield please take a look at the latest patches when you have a minute, the PR has changed a bit since last LGTM.

File: dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt [hunk 1]
```diff
@@ -1,35 +1,61 @@
...
-  }
+class MainActivity : FlutterActivity() {
+    class SimplePlatformView(context: Context) : PlatformView {
+        private val view: View = View(context)
+
+        init {
+            view.setBackgroundColor(Color.CYAN)
+        }
+
+        override fun dispose() {}
```
Comment (blasten) [inline dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt]: not sure if the empty `dispose()` is needed, but just in case.

**Comment by blasten** [comment]
LGTM. Thanks for the effort to track this down :)

File: dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt (hunk 1 above)
Comment (mklim) [reply dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt]: Hard to tell in Kotlin, but the original class is a Java interface so it's still needed here.

**Review by dnfield — APPROVED** [review]
