### PR TITLE
Fix canpop logic to be more robust

### LINKED ISSUE #73956: CupertinoNavigationBar crashes when pressing back button
## Steps to Reproduce
<details>
<summary>code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Page 1'),
      ),
      child: Center(
        child: TextButton(
          child: Text("Next"),
          onPressed: () {
            Navigator.of(context).push<void>(
              CupertinoPageRoute(
                builder: (BuildContext context) => Page2(),
                title: "Page 2",
              ),
            );
          },
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Page 2"),
      ),
      child: Center(
        child: Text("Page 2"),
      ),
    );
  }
}


void main() {
  runApp(CupertinoApp(home: Page1()));
}

```

</details>

1. press next to go to page 2

2. press back button on nav bar

## Logs

<details>
<summary>Logs</summary>

```
The following assertion was thrown building CupertinoNavigationBarBackButton(dirty, dependencies:
[_ModalScopeStatus]):
CupertinoNavigationBarBackButton should only be used in routes that can be popped
'package:flutter/src/cupertino/nav_bar.dart':
Failed assertion: line 1366 pos 9: 'currentRoute?.canPop == true'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  CupertinoNavigationBar file:///Users/chtai/apps/test1/lib/main.dart:32:22


```

```
```

</details>

This is a regression introduced in https://github.com/flutter/flutter/pull/71944

### PR DESCRIPTION
**Pull request by chunhtai**
As title

Fixes https://github.com/flutter/flutter/issues/73956

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -483,6 +480,29 @@ abstract class Route<T> {
...
+      assert(e != null);
+      if (e!.route == this)
+        return true;
+      if (_RouteEntry.isPresentPredicate(e)) {
+        seenActiveRoute = true;
+        return true;
+      }
+      return false;
+    }
+    _navigator!._history.cast<_RouteEntry?>().firstWhere(
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/navigator.dart:499]: This is OK, although a for loop might have been simpler.

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM
