### PR TITLE
Fixes macOS App.framework not being codesigned or find framework

### LINKED ISSUE #181056: Flutter/Packages "Mac_arm64 macos_platform_tests master" codesign failure
### Help us understand the severity of this issue

- [x] breakage; unable to contribute or trigger builds will no workarounds
- [ ] inconvenient workarounds exist, but significant effort required
- [ ] needed for a Flutter team-wide priority (already agreed upon)
- [ ] nice-to-have; none of the above

### What do you need help with

The codesign task in the "Mac_arm64 macos_platform_tests master" test for packages is crashing or failing in some way. I'm not sure why. 

https://github.com/flutter/packages/pull/10809/checks?check_run_id=60503052136

This is preventing the flutter -> packages roller from landing

### PR DESCRIPTION
**Pull request by vashworth**
When SwiftPM is enabled, it doesn't embed/codesign the Flutter framework via Flutter tooling since it's now handled by Xcode. There was a bug in this, though, which prevented the App.framework from being codesigned. This PR fixes that.

Fixes https://github.com/flutter/flutter/issues/181056.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/swift_package_manager.dart [hunk 1]
```diff
@@ -279,7 +281,7 @@ class SwiftPackageManager {
     );
     if (frameworkLink.existsSync()) {
       frameworkLink.updateSync('./${buildMode.uppercaseName}/$frameworkName.xcframework');
-    } else {
+    } else if (createIfNotFound) {
```
Comment (vashworth) [inline packages/flutter_tools/lib/src/macos/swift_package_manager.dart:284]: This was added because I ran into an issue when debugging locally where `UnpackMacOS` (which embeds the FlutterMacOS framework) was being skipped despite the FlutterFramework package not existing. This was because we check to see if the directory exists to determine if Flutter should be copying/codesigning the FlutterMacOS framework:

https://github.com/flutter/flutter/blob/6c50f5605d5e0e02e75c1840b454a3c462c7c15a/packages/flutter_tools/lib/src/build_system/targets/macos.dart#L46-L58

https://github.com/flutter/flutter/blob/6c50f5605d5e0e02e75c1840b454a3c462c7c15a/packages/flutter_tools/bin/xcode_backend.dart#L357-L364

And the directory was being created by `updateFlutterFrameworkSymlink` because SwiftPM was enabled

https://github.com/flutter/flutter/blob/6c50f5605d5e0e02e75c1840b454a3c462c7c15a/packages/flutter_tools/lib/src/macos/build_macos.dart#L156-L162

However, the FlutterFramework swift package was not created because there were no SwiftPM plugins

https://github.com/flutter/flutter/blob/6c50f5605d5e0e02e75c1840b454a3c462c7c15a/packages/flutter_tools/lib/src/macos/swift_package_manager.dart#L68-L75

**Comment by vashworth** [comment]
> Thank you! Can we add the roll on this pr to make sure it resolves the issue?

How do I do that?

**Review by tarrinneal — APPROVED** [review]
Nevermind, I'm in the wrong repo! No rolling necessary.
