### PR TITLE
Fix text input actions in DropdownMenu.

### LINKED ISSUE #177009: [DropdownMenu] Keyboard not closing when clicking on `done` with `requestFocusOnTap: true` on mobiles
### Steps to reproduce

1. Run the code example below on a mobile device (iOS or Android)
2. Write something in the Textfield -> done -> Keyboard closes
3. Write something in the Drowdown field -> done -> Keybaord should close, but does not

Tipp: to enable the virtual keyboard on iOS simulator hit: I/O -> keyboard -> Toggle Software Keyboard

### Expected results

The keyboard should close when clicking on done.

### Actual results

The keyboard keeps open when clicking on done.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

class DropdownMenuExample extends StatelessWidget {
  const DropdownMenuExample({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(colorSchemeSeed: Colors.green),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            spacing: 20,
            children: [
              TextField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'TextField can close keyboard',
                ),
              ),
              DropdownMenu<String>(
                label: Text('Dropdown with filter cannot close keyboard'),
                initialSelection: 'green',
                requestFocusOnTap: true,
                onSelected: (String? color) {},
                dropdownMenuEntries: [
                  DropdownMenuEntry(value: 'red', label: 'red'),
                  DropdownMenuEntry(value: 'green', label: 'green'),
                  DropdownMenuEntry(value: 'blue', label: 'blue')
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.6, on macOS 15.7 24G222 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.1.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/177009

### Description

- Moves `MenuButton` submit logic from `onEditingComplete` to `onSubmitted` to allow `TextField` to handle the `textInputAction` logic
- Wraps each item into `ExcludeFocus` to enable proper `TextInputAction.previous` handling. If we don't wrap each child in `ExcludeFocus`, then focus will be moved to one of them, which is not the expected behavior for `TextInputAction.previous`.

| BEFORE | AFTER |
| - | - |
| <video alt="before" src="https://github.com/user-attachments/assets/a50d41de-7e54-409b-bf81-80dfb1db132f" /> | <video alt="after" src="https://github.com/user-attachments/assets/152e47e6-d774-481c-8478-af526b5f6749" /> |

<details closed><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final FocusNode _previousFocusNode = FocusNode(debugLabel: 'previous');
  final FocusNode _textFieldFocusNode = FocusNode(debugLabel: 'textField');
  final FocusNode _nextFocusNode = FocusNode(debugLabel: 'next');

  @override
  void dispose() {
    _previousFocusNode.dispose();
    _textFieldFocusNode.dispose();
    _nextFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(colorSchemeSeed: Colors.green),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            spacing: 20,
            children: [
              TextField(
                focusNode: _previousFocusNode,
                textInputAction: TextInputAction.next,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Previous TextField',
                ),
              ),
              DropdownMenu<String>(
                label: Text('Dropdown with filter cannot close keyboard'),
                initialSelection: 'green',
                focusNode: _textFieldFocusNode,
                requestFocusOnTap: true,
                showTrailingIcon: false,
                textInputAction: TextInputAction.next,
                onSelected: (String? color) {
                  print('SELECTED $color');
                },
                dropdownMenuEntries: [
                  DropdownMenuEntry(value: 'red', label: 'red'),
                  DropdownMenuEntry(value: 'green', label: 'green'),
                  DropdownMenuEntry(value: 'blue', label: 'blue'),
                ],
              ),
              TextField(
                focusNode: _nextFocusNode,
                textInputAction: TextInputAction.done,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Next TextField',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

There is still one behavior I would like to discuss. When the `showTrailingIcon: true` and `textInputAction: TextInputAction.previous` are used, the focus moves not to the previous field but to the `IconButton`. If we wrap the `IconButton` with `ExcludeFocus`, then this is fixed, but I am not sure whether this is the correct way to proceed.

| TextInputAction.previous and no ExcludeFocus on IconButton | TextInputAction.previous and ExcludeFocus on IconButton |
| - | - |
| <video alt="before" src="https://github.com/user-attachments/assets/76c90dcf-3ea1-492f-8e67-7e987b08c2ff" /> | <video alt="after" src="https://github.com/user-attachments/assets/2a1600a2-e308-430e-a12f-acdc06cbf81c" /> |

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -4877,6 +4877,95 @@ void main() {
     await tester.pump();
     expect(find.byType(MenuItemButton), findsWidgets);
   });
+
+  // The variants to test in the focus handling test.
+  final ValueVariant<TextInputAction> focusVariants = ValueVariant<TextInputAction>(
+    TextInputAction.values.toSet(),
+  );
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_test.dart:4973]: I can't believe I never knew you could do this for stuff other than the platform. So many unnecessary for loops around my tests. TIL.

**Review by justinmc — APPROVED** [review]
LGTM as long as the Google tests pass 👍 . Maybe @bleroux should take a look as well?

Thanks for making sure this works as expected for all the different TextInputActions.

**Review by bleroux — APPROVED** [review]
LGTM!
