### PR TITLE
TabView fails to update tab contents

### LINKED ISSUE #1134: Stocks app is starting up with the tab view being empty and not draggable.
I haven't checked, but it feels like maybe the list is not filling the whole space?

cc @abarth, @HansMuller

### LINKED ISSUE #1168: Stocks is starting up blank.
It seems like it's not updating the list or something.

### PR DESCRIPTION
**Pull request by abarth**
When the TabView widget's children change, we don't change the children
we give to the PageViewport because we fail to update _items. This patch
watches didChangeConfig and updates _items appropriately.

Fixes #1134
Fixes #1168

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -817,28 +823,40 @@ class _TabBarViewState extends PageableListState<TabBarView> implements TabBarSe
     _selection = null;
   }
 
-  void _updateItems(int first, int second, [int third]) {
+  void _updateItemsWithChildren(int first, int second, [int third]) {
```
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: _updateItemsFromChildren? With makes it sound like you're updating both or something.

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/material/tabs.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter/lib/src/material/tabs.dart]: Yeah.
