### PR TITLE
Scale high-pixel-ratio images with BoxFit.none/BoxFit.scaleDown correctly

### LINKED ISSUE #18682: BoxFit.none does not take into account image scale, images always pixelated and scaled incorrectly
My application provides 3 background image variants (1.0x, 2.0x, 3.0x) with a size of 48x48 which are used as repeatable background images, for example:

```dart
new Container(
  width: 200.0
  height: 200.0,
  decoration: new BoxDecoration(
    image: new DecorationImage(
      image: new AssetImage('images/test.png'),
      repeat: ImageRepeat.repeat,
      fit: BoxFit.none,
    ),
  ),
)
```
`BoxFit.none` is used to keep the original size of the image (48x48 units)

Depending on the device pixel ratio, Flutter chooses the correct image variant (3.0x in the screenshot) so that the images are sharp even on high resolution displays.

The problem is that the painting logic does not take into account the scale of the image, it just makes them bigger. For example, on a 3.0x device, the 3.0x image variant (which has a real pixel size of 144x144) is scaled up to a size of 144x144 units, which equals 432x432 real pixels = **a blurry pixel mess**.

This is a serious bug which makes the image variant system unusable.

The bug also occurs when `BoxFit.none` or `BoxFit.scaleDown` are used in a regular `Image.asset `widget:

```dart
new Image.asset(
  'images/test.png',
  height: 200.0,
  fit: BoxFit.none,
  repeat: ImageRepeat.repeat,
)
```

-----
Example application (boxfit branch): https://github.com/sir-boformer/flutter_image_bugs/tree/boxfit

Current Behavior: | Expected Behavior:
------------ | -------------
 |

### PR DESCRIPTION
**Pull request by sir-boformer**
Fixes  #18682.

`paintImage` is used to paint `BoxDecoration` background images and `Image` widgets. This PR adds a new `scale` parameter so that the method can take into account the image scale (how many image pixels equal one logical pixel) so that 2.0x/3.0x variants are rendered correctly.

### CODE REVIEW

File: packages/flutter/test/painting/decoration_test.dart [hunk 1]
```diff
@@ -347,4 +347,171 @@ void main() {
     expect(Decoration.lerp(const FlutterLogoDecoration(), const BoxDecoration(), 0.75), isInstanceOf<BoxDecoration>()); // ignore: CONST_EVAL_THROWS_EXCEPTION
     expect(Decoration.lerp(const FlutterLogoDecoration(), const BoxDecoration(), 1.0), isInstanceOf<BoxDecoration>()); // ignore: CONST_EVAL_THROWS_EXCEPTION
   });
+
+  test('paintImage BoxFit.none scale test', () {
+    for (double scale = 1.0; scale <= 4.0; scale += 1.0) {
+      final TestCanvas canvas = new TestCanvas(<Invocation>[]);
+
+      final Rect outputRect = Rect.fromLTWH(30.0, 30.0, 250.0, 250.0);
```
Comment (Hixie) [inline packages/flutter/test/painting/decoration_test.dart]: nit: Please use `new` for a few more days while we await having a lint to remove all `new`s at once. (We want to be consistent in the meantime.)

**Comment by Hixie** [comment]
This looks great. Thanks for your contribution! If you could make the tiny fix mentioned, we can land it! Thanks!

**Comment by sir-boformer** [comment]
@Hixie `new` keywords added

**Comment by sir-boformer** [comment]
@Hixie This has been here for a while. Can you merge it? I'm afraid that if you deicide to remove all `new` keywords, merging will become a lot more difficult.

**Comment by Hixie** [comment]
Yup! Sorry about the delay!

**Comment by Hixie** [comment]
(Just need to wait for the tree to be green. Looks like we've had some bad commits recently.)

**Comment by Hixie** [comment]
Thanks for your contribution!
