### PR TITLE
Cupertino nav bar transitions between routes

### LINKED ISSUE #20818: Hero animation within CupertinoTabScaffold not working
## Steps to Reproduce

```dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new WillPopScope(
      // Prevent swipe popping of this page. Use explicit exit buttons only.
      onWillPop: () => new Future<bool>.value(true),
      child: new CupertinoTabScaffold(
        tabBar: new CupertinoTabBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.home),
              title: Text('Hero'),
            ),
            BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.home),
              title: Text('Dummy'),
            )
          ],
        ),
        tabBuilder: (BuildContext context, int index) {
          return new DefaultTextStyle(
            style: const TextStyle(
              fontFamily: '.SF UI Text',
              fontSize: 17.0,
              color: CupertinoColors.black,
            ),
            child: new CupertinoTabView(
              builder: (BuildContext context) {
                switch (index) {
                  case 0:
                    return CupertinoPageScaffold(
                      child: new Center(
                        child: Hero(
                          tag: 'hero_image',
                          child: GestureDetector(
                            onTap: () {
                              Navigator.of(context).push(new CupertinoPageRoute(
                                builder: (BuildContext context) => new HeroPage(),
                              ));
                            },
                            child: Image.network(
                                'https://cdn-images-1.medium.com/fit/c/320/320/0*R1JRCwpVruJCSxJ_.'),
                          ),
                        ),
                      ),
                    );
                    break;
                  case 1:
                    return CupertinoPageScaffold(
                      child: new Center(
                        child: Text("2")
                      ),
                    );
                    break;
                  default:
                }
              },
            ),
          );
        },
      ),
    );
  }
}

class HeroPage extends StatelessWidget {
  HeroPage();

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return CupertinoPageScaffold(
      child: Padding(
        padding: EdgeInsets.all(10.0),
        child: Hero(
          tag: 'hero_image',
          child: Image.network(
              'https://cdn-images-1.medium.com/fit/c/320/320/0*R1JRCwpVruJCSxJ_.'),
        ),
      ),
    );
  }
}

```
## Logs
```
Nothing in the logs
```

```
```

```
[✓] Flutter (Channel master, v0.5.9-pre.84, on Mac OS X 10.13.6 17G65, locale en-ZA)
    • Flutter version 0.5.9-pre.84 at /Users/calvinmuller/iStreet/Mobile/FlutterMastre
    • Framework revision 3ae5ecebea (27 hours ago), 2018-08-19 06:25:00 -0400
    • Engine revision 03f8ba51e3
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • iPhone X • 2F58DD45-8972-49C0-8136-7AE1B1917B7D • ios • iOS 11.4 (simulator)

! Doctor found issues in 1 category.

```

### LINKED ISSUE #20939: Hero throws exception with CupertinoTabScaffold
## Steps to Reproduce

1. tap `Next as Page`
2. tap `Next as Dialog`

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

const imageUrl = "https://flutter.io/images/flutter-mark-square-100.png";

void main() {
  runApp(new MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new CupertinoTabScaffold(
      tabBar: new CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          const BottomNavigationBarItem(
            icon: const Icon(Icons.home),
            title: const Text("Left"),
          ),
          const BottomNavigationBarItem(
            icon: const Icon(Icons.gesture),
            title: const Text("Right"),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return new MaterialApp(
          home: new Builder(
            builder: (BuildContext context) {
              return new Scaffold(
                appBar: new AppBar(title: const Text("RootPage")),
                body: Column(
                  children: <Widget>[
                    new Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: new RaisedButton(
                        onPressed: () {
                          Navigator.push(context, new CupertinoPageRoute(
                            builder: (BuildContext context) {
                              return new NextPage();
                            },
                          ));
                        },
                        child: const Text("Next as Page"),
                      ),
                    ),
                    new Hero(
                      tag: "hero",
                      child: new Image.network(imageUrl),
                    ),
                  ],
                ),
              );
            },
          ),
        );
      },
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(title: const Text("NextPage")),
      body: Column(
        children: <Widget>[
          new Padding(
            padding: const EdgeInsets.all(8.0),
            child: new Hero(
              tag: "hero",
              child: new Image.network(imageUrl),
            ),
          ),
          new RaisedButton(
            onPressed: () {
              Navigator.of(context, rootNavigator: true).push(new CupertinoPageRoute(
                fullscreenDialog: true,
                builder: (BuildContext context) {
                  return new NextPage();
                },
              ));
            },
            child: const Text("Next as Dialog"),
          ),
        ],
      ),
    );
  }
}
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
flutter: must have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: hero
flutter: Here is the subtree for one of the offending heroes:
flutter: # Hero(tag: hero, state: _HeroState#717bd)
flutter: # └KeyedSubtree-[GlobalKey#cd8bb]
flutter: #  └Image(image: NetworkImage("https://flutter.io/images/flutter-mark-square-100.png", scale: 1.0), alignment: center, state: _ImageState#bd112(stream: ImageStream#5217a(MultiFrameImageStreamCompleter#1b3df, [100×100] @ 1.0x, 2 listeners), pixels: null))
flutter: #   └RawImage(image: null, alignment: center, renderObject: RenderImage#e6d28 relayoutBoundary=up2)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:130:13)
flutter: #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:140:10)
flutter: #2      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #4      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #8      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #42     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #54     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #72     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #79     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #81     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #82     _TheatreElement.visitChildren (package:flutter/src/widgets/overlay.dart:468:16)
flutter: #83     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #85     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #87     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #89     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #91     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #93     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #95     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #97     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #99     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #100    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #101    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #103    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #105    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #107    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #109    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #111    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #112    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #113    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #115    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #117    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #119    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #121    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #123    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #125    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #126    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #127    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #129    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #131    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #133    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #134    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #135    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #137    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #138    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #139    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #140    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #141    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #142    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #143    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #145    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #147    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #148    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #149    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #150    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #151    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #153    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #154    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #155    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #156    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #157    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #158    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #159    Element.visitChildElements (package:flutter/src/widgets/framework.dart:2642:5)
flutter: #160    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:146:13)
flutter: #161    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:510:53)
flutter: #162    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
flutter: #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #164    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
flutter: #165    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #166    _invoke (dart:ui/hooks.dart:120:13)
flutter: #167    _drawFrame (dart:ui/hooks.dart:109:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale ja-JP)
    • Flutter version 0.5.1 at /Applications/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

### PR DESCRIPTION
**Pull request by xster**
#9446
Fixes #20818
Fixes #20939

Diff bases on top of #19637

Kapture 2020-02-17 at 23 23 38

Changes: 

- Moved all inner component creation logic between the standard and sliver versions into a single class
- Instead of a complex custom render object that knows how to place and decorate all things at all times, keep the transition code extremely dumb and anchor it based on actual logic in static time layout to keep the code more maintainable. 
- Scenario variants are at https://docs.google.com/document/d/1-NdvdLnWw2Dbbutc2Ja1hkvUXbf3rsL9O8dQ_6eW4PI
- Randomized scenario test at https://github.com/xster/flutter-test/tree/master/t104_nav_bar_transition_combinations
- Heroes now take additional builders for customizing what to build in mid-flight, change the 'shuttle' in mid flight during a divert, and what to build as replacements for the original Heroes' anchor spots during the flight.

Next PR:

- Back swipes (needs more routing code refactors)
- RTL transitions

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 1]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
 );
 
+// There's a single tag for all instances of navigation bars because they can
+// all transition between each other (per Navigator) via Hero transitions.
+const _HeroTag _heroTag = _HeroTag();
+
+class _HeroTag {
+  const _HeroTag();
+  // This class exists because the Gallery smoke test wants all widgets from
+  // debugDumpApp() to have a toString();
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: It's not because the test exists that the class exists, it's because we want the user to be able to determine what the tag is.

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 2]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
+  @override
+  String toString() => "Cupertino navigation bars' Hero tag";
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: I think this might be mildly clearer as "Hero tag for Cupertino navigation bars" or just "Navigation bar hero" or some such. The possessive apostrophe is grammatically perfect but will look confusing in tree dumps.

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 3]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
+  );
+}
+
+/// Returns `child` wrapped with background and a bottom border if background color
+/// is opaque. Otherwise, also blur with [BackdropFilter].
+Widget _wrapWithBackground({
+  Border border,
+  Color backgroundColor,
+  Widget child,
+  bool annotate = true,
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: nit: "annotate" doesn't convey what exactly the annotation does. Maybe `affectSystemUi` or some such?

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 4]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
+
+  if (backgroundColor.alpha == 0xFF)
+    return childWithBackground;
+
+  return new ClipRect(
+    child: new BackdropFilter(
+      filter: new ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
+      child: childWithBackground,
+    ),
+  );
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: clips and backdrop filters are expensive :-(

cc @liyuqian in case you have any ideas for how else to do this

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 5]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
+}
+
+// Whether the current route supports nav bar hero transitions from or to.
+bool _isTransitionable(BuildContext context) {
+  final ModalRoute<dynamic> route = ModalRoute.of(context);
+
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: there's only two lines in this function, it's not clear to me that we gain much from a blank line between them :-P
(up to you)

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 6]
```diff
@@ -50,6 +63,76 @@ const TextStyle _kLargeTitleTextStyle = TextStyle(
...
+  // Fullscreen dialogs never transitions its nav bar with other push-style
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: its -> their

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 4 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: We had this conversation in the diffbase :D
https://github.com/flutter/flutter/pull/19637#pullrequestreview-142598550

I just moved stuff around.

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 7]
```diff
@@ -150,18 +313,67 @@ class CupertinoNavigationBar extends StatelessWidget implements ObstructingPrefe
...
+        padding: widget.padding,
+      ),
+    );
+
+    if (!widget.transitionBetweenRoutes || !_isTransitionable(context)) {
+      return navBar;
+    }
+
+    return new Hero(
+      tag: _heroTag,
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: We should follow the pattern of `FloatingActionButton.heroTag` to allow people to have multiple nav bars at once.

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 4 above)
Comment (liyuqian) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Clipping rect should be fairly cheap as long as the rect is axis-aligned. You can also set `clipBehavior = Clip.hardEdge` to further reduce the performance overhead. I wouldn't expect such a clip rect to become a performance bottleneck.

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 8]
```diff
@@ -192,27 +404,46 @@ class CupertinoNavigationBar extends StatelessWidget implements ObstructingPrefe
...
 ///
+/// The [largeTitle] widget will automatically be a title text from the current
+/// route if none is provided and [automaticallyImplyTitle] is true (true by
+/// default).
+///
+/// When [transitionBetweenRoutes] is true, this navigation bar will transition
+/// on top of the routes instead of inside it if the route being transitioned
+/// to also has a [CupertinoNavigationBar] or a [CupertinoSliverNavigationBar]
+/// with [transitionBetweenRoutes] set to true. If [transitionBetweenRoutes] is
+/// true, none of the [Widget] parameters can contain a key in its subtree since
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: "none of" is plural, "its" is singular, so `its subtree->`their subtrees` or some such.

Comment (Hixie) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: presumably this should say GlobalKey, not just key

Comment (Hixie) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: that is, "a key" -> "any [GlobalKey]s"

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 9]
```diff
@@ -192,27 +404,46 @@ class CupertinoNavigationBar extends StatelessWidget implements ObstructingPrefe
...
+/// that widget will exist in multiple places in the tree simultaneously.
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: that -> those

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 7 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Umm, interesting. Sure

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 10]
```diff
@@ -192,27 +404,46 @@ class CupertinoNavigationBar extends StatelessWidget implements ObstructingPrefe
...
     this.padding,
     this.actionsForegroundColor = CupertinoColors.activeBlue,
-  }) : assert(largeTitle != null),
-       assert(automaticallyImplyLeading != null),
+    this.transitionBetweenRoutes = true,
+  }) : assert(automaticallyImplyLeading != null),
+       assert(automaticallyImplyTitle != null),
+       assert(
+         automaticallyImplyTitle == true || largeTitle != null,
+         'A largeTitle must be provided. Otherwise, automaticallyImplyTitle '
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: The first sentence here seems to be shown to be a lie by the second. :-)

Cosider something like "No largeTitle has been provided but automaticallyImplyTitle is false.\nEither provide a largeTitle or set automaticallyImplyTitle to true."

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 11]
```diff
@@ -229,21 +460,34 @@ class CupertinoSliverNavigationBar extends StatelessWidget {
   /// any [GlobalKey]s, and that it not rely on maintaining state (for example,
   /// animations will not survive the transition from one location to the other,
   /// and may in fact be visible in two places at once during the transition).
+  ///
+  /// If null and [automaticallyImplyTitle] is true, an appropriate [Text]
+  /// title will be created if the current route is a [CupertinoPageRoute] and
+  /// has a `title`.
+  ///
+  /// This parameter must either be non-null or [automaticallyImplyTitle] must
+  /// be true and the route has a title.
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: "This parameter must either be non-null or the route must have a title ([...]) and [automaticallyImplyTitle] must be true."
where "[...]" is a cross-reference to the relevant thing in CupertinoPageRoute or wherever.

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 10 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: lol, sorry, dumb phrasing. Fixing

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 12]
```diff
@@ -253,277 +497,113 @@ class CupertinoSliverNavigationBar extends StatelessWidget {
...
-        trailing: trailing,
-        padding: padding,
-        border: border,
-        backgroundColor: backgroundColor,
-        actionsForegroundColor: actionsForegroundColor,
-      ),
-    );
+  _CupertinoSliverNavigationBarState createState() {
+    return new _CupertinoSliverNavigationBarState();
   }
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: prefer one-liner for createState

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 13]
```diff
@@ -602,17 +693,1401 @@ class _CupertinoLargeTitleNavigationBarSliverDelegate
         ],
       ),
     );
+
+    if (!transitionBetweenRoutes || !_isTransitionable(context)) {
+      return navBar;
+    }
+
+    return new Hero(
+      tag: _heroTag,
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: as above

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 14]
```diff
@@ -602,17 +693,1401 @@ class _CupertinoLargeTitleNavigationBarSliverDelegate
...
+@immutable
+class _NavigationBarStaticComponentsKeys {
+  _NavigationBarStaticComponentsKeys()
+      : navBarBoxKey = new GlobalKey(),
+        leadingKey = new GlobalKey(),
+        backChevronKey = new GlobalKey(),
+        backLabelKey = new GlobalKey(),
+        middleKey = new GlobalKey(),
+        trailingKey = new GlobalKey(),
+        largeTitleKey = new GlobalKey();
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: consider passing a `debugLabel` to each of these

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 15]
```diff
@@ -602,17 +693,1401 @@ class _CupertinoLargeTitleNavigationBarSliverDelegate
...
+    }
+
+    final Widget largeTitleContent = userLargeTitle ?? _derivedTitle(
+      automaticallyImplyTitle: automaticImplyTitle,
+      currentRoute: route,
+    );
+
+    assert(
+      largeTitleContent != null,
+      'largeTitle was not provided and there was no title from the route',
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: nit: end error messages with a period.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 16]
```diff
@@ -20,11 +20,36 @@ import 'transitions.dart';
...
+  /// If no custom [HeroFlightShuttleBuilder] is supplied, the top route's
+  /// [Hero] child is shown in flight.
+  push,
+
+  /// A flight triggered by a route pop.
+  ///
+  /// The animation goes from 1 to 0.
+  ///
+  /// If no custom [HeroFlightShuttleBuilder] is supplied, the bottom route's
+  /// [Hero] child is shown in flight.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: before we showed the top route's hero, is this an intentional change?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 17]
```diff
@@ -115,6 +142,25 @@ class Hero extends StatefulWidget {
...
+  ///
+  /// If none is provided, the destination route's Hero child is shown in-flight
+  /// by default.
+  final HeroFlightShuttleBuilder flightShuttleBuilder;
+
+  /// Placeholder widget left in place as the Hero's child once the flight takes off.
+  ///
+  /// By default, an empty SizedBox keeping the Hero child's original size is
+  /// left in place once the Hero shuttle has taken flight.
+  final TransitionBuilder launchPadBuilder;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: launchPadBuilder is cute but not very intuitive.

We should either:

1. Rename launchPadBuilder and flightShuttleBuilder (e.g. to placeholderBuilder and animationBuilder), or

2. Add an animated diagram to the Hero widget class that shows (in the same style as the AppBar diagram) all the various components of a Hero animation, along with their names.

I don't mind which we do. We'll want to do number 2 eventually anyway. If you like the cute terms and want to keep them, please work with @gspencergoog to make sure we have clear documentation including the aforementioned animated labeled diagram.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 18]
```diff
@@ -539,4 +620,15 @@ class HeroController extends NavigatorObserver {
...
+  static final HeroFlightShuttleBuilder _defaultHeroFlightShuttleBuilder = (
+    BuildContext flightContext,
+    Animation<double> animation,
+    HeroFlightDirection flightDirection,
+    BuildContext fromHeroContext,
+    BuildContext toHeroContext,
+  ) {
+    final Hero toHero = toHeroContext.widget;
+    return toHero.child;
+  };
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: we should make sure this is exactly what we used to do before (i can't tell from the code if this is a change from what we did before, but the documentation you added earlier says that it is).

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 19]
```diff
@@ -539,4 +620,15 @@ class HeroController extends NavigatorObserver {
...
 }
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/heroes.dart]: regardless of whether you rename the new fields or create a diagram, please make sure to add significant documentation to this class to explain everything that's going on. Given the changes here, the class docs shouldn't have remained the same. :-)

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 20]
```diff
@@ -1684,8 +1687,10 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
       newRoute.didChangeNext(null);
     }
-    if (index > 0)
+    if (index > 0) {
       _history[index - 1].didChangeNext(newRoute);
+      newRoute.didChangePrevious(_history[index - 1]);
+    }
     for (NavigatorObserver observer in widget.observers)
       observer.didReplace(newRoute: newRoute, oldRoute: oldRoute);
     oldRoute.dispose();
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/navigator.dart]: since this is technically a breaking change (albeit one that should only make things better), please go through the breaking change process as documented on the design principles page.

File: packages/flutter/lib/src/widgets/transitions.dart [hunk 21]
```diff
@@ -672,6 +673,64 @@ class AlignTransition extends AnimatedWidget {
...
+    return new DefaultTextStyle(
+      style: style.value,
+      textAlign: textAlign,
+      softWrap: softWrap,
+      overflow: overflow,
+      maxLines: maxLines,
+      child: child,
+    );
+  }
+}
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/transitions.dart]: i love that this PR is adding fundamental types like DefaultTextStyleTransition and BorderTween. It takes me back to the old days of Flutter where every PR was adding fundamental things. :-)

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 18 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/heroes.dart]: (i find it concerning that no tests broke as a result of this change)

**Comment by Hixie** [comment]
Summary of comments:
 * Go through breaking change process for the Navigator changes
 * Rename new hero features or create animated diagram for new Hero features
 * Add docs to Hero about new features and how they work with old features
 * Various other nits.

Modulo the above,
LGTM

**Review by xster — COMMENTED** [review]
Thanks for the big review. 

@Hixie you ok with me announcing the breaking navigation observer change and submitting https://github.com/flutter/flutter/pull/19637 first? 

I'd like to keep the PR and commit history steps smaller if possible.

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 4 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: @liyuqian: does hardEdge help performance further if the rect is already axis-aligned? Otherwise I'd be cautious to 'reduce fidelity' then add another API for users to boost it back if they put the nav bar in a rotate or some such.

Comment (Hixie) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: I think it's fine to do that. It's what we've done pretty much everywhere else for similar things now.

Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: ah ya, you're right. I didn't see the refactor PR. It's like all over the place now...
ok, will do

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 19 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/heroes.dart]: Changed the class dartdoc

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 17 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/heroes.dart]: launchPadBuilder was a bit farcical. I'm keeping flightShuttleBuilder though since there's already so many animations going on (the route animation, the rect tween animation etc) and since we're already using the wording flight, it'd make sense to establish relationship of this particular animation with respect to the flight (i.e. being the thing that's taking the flight).

File: packages/flutter/lib/src/widgets/sliver_persistent_header.dart [hunk 22]
```diff
@@ -188,6 +188,7 @@ class _SliverPersistentHeaderElement extends RenderObjectElement {
 
   @override
   void performRebuild() {
+    super.performRebuild();
```
Comment (xster) [inline packages/flutter/lib/src/widgets/sliver_persistent_header.dart]: @HansMuller can you check if this is right? I'm surprised it didn't need to call super since the element's dirty bit is never removed during rebuild.

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 4 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Unfortunately I had to revert this since it causes a number of graphical bugs. For instance, having a hardEdge clip would cause other clips (hardEdge or not) on the same page to no longer appear. 

It also causes https://github.com/flutter/flutter/issues/21095.

I'll create reduced test cases and file bugs for those issues separately.
