### PR TITLE
Make tests more hermetic.

### LINKED ISSUE #8761: Port scanning in flutter tools is not mockable
We currently [make a static call](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/os.dart#L184) to `ServerSocket.bind()` in order to determine whether a given port is available for use.  This method of port scanning is not test friendly, and in fact is causing flutter tools tests to fail locally[1] for most developers (but succeed on Travis).

[1] Most often seen in the replay test:

```
>>> RUNNING in ^[[36mpackages/flutter_tools^[[0m: ^[[33mbin/cache/dart-sdk/bin/pub run test^[[0m
00:07 ^[[32m+83^[[0m: test/replay/osx/simulator_application_binary_test.dart: runsWithoutError^[[0m                
ProcessException: No matching invocation found
 Command: /usr/bin/xcrun simctl launch AA8FFDB0-593A-44E4-A927-8E49A138BDA5 io.flutter.HelloFlutter --enable-dart-profiling --enable-checked-mode --observatory-port=8102 --diagnostic-port=8105
Error running application on iPhone 6s.

00:07 ^[[32m+84^[[0m^[[31m -1^[[0m: test/replay/osx/simulator_application_binary_test.dart: runsWithoutError^[[0m             
 Expected: throws (an instance of ProcessExit and satisfies function)
   Actual: <Instance of '_Future'>
    Which: threw ProcessExit:<ProcessExit: 2>
           stack package:flutter_tools/src/base/io.dart 93:5                  setExitFunctionForTests.<fn>
                 package:flutter_tools/executable.dart 318:11                 _exit.<fn>
                 ===== asynchronous gap ===========================
```

### PR DESCRIPTION
**Pull request by tvolkert**
1. Add `PortScanner` abstraction so that we don't do actual port scanning
   in tests.
2. Don't change the real `cwd` of the isolate during tests, as it affects
   all tests, not just the current running test.

Fixes #8761

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

File: packages/flutter_tools/lib/src/base/port_scanner.dart [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+      if (await isPortAvailable(port))
+        return port;
+      iterationCount++;
+    }
+
+    return findAvailablePort();
+  }
+}
+
+class LocalPortScanner extends PortScanner {
```
Comment (johnmccutchan) [inline packages/flutter_tools/lib/src/base/port_scanner.dart]: Local -> Host ?

**Review by johnmccutchan — APPROVED** [review]

File: packages/flutter_tools/lib/src/base/port_scanner.dart [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+  const HostPortScanner();
+
+  @override
+  Future<bool> isPortAvailable(int port) async {
+    try {
+      // TODO(ianh): This is super racy.
+      final ServerSocket socket = await ServerSocket.bind(InternetAddress.LOOPBACK_IP_V4, port);
+      await socket.close();
+      return true;
+    } catch (error) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/base/port_scanner.dart]: I know this is old code you're just moving, but: please don't catch all errors. Only catch the errors that you want to swallow, and leave the rest. Otherwise, we'll hide crashes. For example, suppose bind() asserts that port shouldn't be 0, but we're passing 0 in. We'll catch the assert and never hear about it.

See https://github.com/flutter/flutter/issues/8742.
