### PR TITLE
Fix IconButton.color overrided by IconButtomTheme

### LINKED ISSUE #174472: SnackBar closeIconColor does not respect widget override
### Steps to reproduce

1. Create a Flutter app with a snack bar theme, specifying a close icon color
2. Also add an icon button theme, with an icon color
3. Create a `SnackBar` widget, observe the close icon color being the icon button theme
4. Create a `SnackBar` widget and override `closeIconColor`, and observe the color being the icon button theme

### Expected results

In all cases the `closeIconColor` for the `SnackBar` widget should override any and all theme colors.

In my opinion also, the snack bar theme's `closeIconColor` should take precedent over the more generic icon button theme, but I could see a case for either way here.

### Actual results

The icon button theme color is used for the close icon color of the `SnackBar`, regardless of widget field overrides or snack bar theme.

### Code sample

<details open><summary>Code sample</summary>

See the `SnackBar` text for what I believe should be the actual behavior vs expected behavior.

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SnackBarDemo());

class SnackBarDemo extends StatelessWidget {
  const SnackBarDemo({super.key});

  @override
  Widget build(BuildContext context) {
    final light = ThemeData.light();

    return MaterialApp(
      title: 'SnackBar Demo',
      theme: light.copyWith(
        snackBarTheme: light.snackBarTheme.copyWith(
          showCloseIcon: true,
          closeIconColor: Colors.blue,
        ),
        iconButtonTheme: IconButtonThemeData(
          style: ButtonStyle(
            iconColor: WidgetStateColor.fromMap({
              WidgetState.any: Colors.purple,
            }),
          ),
        ),
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('SnackBar Demo')),
        body: const SnackBarPage(),
      ),
    );
  }
}

class SnackBarPage extends StatelessWidget {
  const SnackBarPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(
            onPressed: () {
              final snackBar = SnackBar(
                content: const Text(
                  'Snackbar should be Colors.blue (theme), but is Colors.purple',
                ),
              );
              ScaffoldMessenger.of(context).showSnackBar(snackBar);
            },
            child: const Text('Button 1'),
          ),
          ElevatedButton(
            onPressed: () {
              final snackBar = SnackBar(
                closeIconColor: Colors.green,
                content: const Text(
                  'Snackbar should be Colors.green (widget override), but is Colors.purple',
                ),
              );
              ScaffoldMessenger.of(context).showSnackBar(snackBar);
            },
            child: const Text('Button 2'),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Pressing "Button 1" from the example above:
Image

Pressing "Button 2" from the example above:
Image

</details>

### Logs

<details open><summary>Logs</summary>

```console

[  +16 ms] Unable to locate an Android SDK.
[   +2 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] Skipping pub get: version match.
[  +62 ms] Skipping generating web_plugin_registrant.dart because it is up-to-date.
[  +13 ms] Generating /home/[USERNAME]/Projects/temp/application_announce/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +2 ms] Skipping generating GeneratedPluginRegistrant.java because it is up-to-date.
[   +1 ms] Skipping generating generated_plugin_registrant.h because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.cc because it is up-to-date.
[        ] Skipping generating generated_plugins.cmake because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.h because it is up-to-date.
[        ] Skipping generating generated_plugin_registrant.cc because it is up-to-date.
[        ] Skipping generating generated_plugins.cmake because it is up-to-date.
[        ] Skipping generating GeneratedPluginRegistrant.h because it is up-to-date.
[        ] Skipping generating GeneratedPluginRegistrant.m because it is up-to-date.
[        ] Skipping generating GeneratedPluginRegistrant.swift because it is up-to-date.
[  +24 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/[USERNAME]/Projects/temp/application_announce/.dart_tool/package_config.json}
[  +15 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +2 ms] /home/[USERNAME]/fvm/versions/3.35.2/bin/cache/dart-sdk/bin/dartaotruntime /home/[USERNAME]/fvm/versions/3.35.2/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /home/[USERNAME]/fvm/versions/3.35.2/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_VERSION=3.35.2 -DFLUTTER_CHANNEL=stable -DFLUTTER_GIT_URL=https://github.com/flutter/flutter.git -DFLUTTER_FRAMEWORK_REVISION=05db968908 -DFLUTTER_ENGINE_REVISION=a8bfdfc394 -DFLUTTER_DART_VERSION=3.9.0 --output-dill /tmp/flutter_tools.LYPKDZ/flutter_tool.RUJSMB/app.dill --packages /home/[USERNAME]/Projects/temp/application_announce/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/7b274049f380fd19360a9716927098ae.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +13 ms] Building Linux application...
[  +10 ms] <- compile package:application_announce/main.dart
[   +2 ms] executing: [/home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/[USERNAME]/Projects/temp/application_announce/linux
[  +75 ms] -- Configuring done (0.1s)
[   +4 ms] -- Generating done (0.0s)
[ +117 ms] -- Build files have been written to: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug
[   +4 ms] executing: ninja -C /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug install
[  +65 ms] ninja: Entering directory `/home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug'
[+1445 ms] [1/5] Generating /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/[USERNAME]/Projects/temp/application_announce/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[        ] [  +19 ms] Unable to locate an Android SDK.
[        ] [   +2 ms] executing: uname -m
[        ] [   +3 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +26 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterEngineStamp' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +10 ms] Initializing file store
[        ] [   +6 ms] Done initializing file store
[        ] [  +26 ms] Skipping target: gen_dart_plugin_registrant
[        ] [   +2 ms] Skipping target: dart_build
[        ] [ +619 ms] Skipping target: unpack_linux
[        ] [        ] Skipping target: gen_localizations
[        ] [   +1 ms] Skipping target: install_code_assets
[        ] [ +231 ms] Skipping target: kernel_snapshot_program
[        ] [ +155 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +8 ms] build succeeded.
[        ] [        ] "flutter assemble" took 1,104ms.
[        ] [  +11 ms] Running 1 shutdown hook
[        ] [   +1 ms] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] [1/2] Install the project...
[        ] -- Install configuration: "Debug"
[   +4 ms] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/application_announce
[        ] -- Set non-toolchain portion of runtime path of "/home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/application_announce" to "$ORIGIN/lib"
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +98 ms] -- Up-to-date: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/lib
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/NativeAssetsManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +47 ms] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +2 ms] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/[USERNAME]/Projects/temp/application_announce/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +11 ms] Building Linux application... (completed in 1,897ms)
[   +1 ms] ✓ Built build/linux/x64/debug/bundle/application_announce
[ +138 ms] Gdk-Message: 16:33:20.835: Unable to load  from the cursor theme
[  +59 ms] VM Service URL on device: http://127.0.0.1:45163/5RnXtuJSDY4=/
[   +3 ms] Caching compiled dill
[  +54 ms] Connecting to service protocol: http://127.0.0.1:45163/5RnXtuJSDY4=/
[ +105 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:45163/5RnXtuJSDY4=/.
[ +111 ms] Successfully connected to service protocol: http://127.0.0.1:45163/5RnXtuJSDY4=/
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[   +7 ms] DevFS: Created new filesystem on the device (file:///tmp/application_announceSRCXUJ/application_announce/)
[   +1 ms] Updating assets
[  +62 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:application_announce/main.dart 349da770-f68a-4bf7-a384-726b8e1b3b88
[        ] <- 349da770-f68a-4bf7-a384-726b8e1b3b88
[        ] Bundle processing done.
[  +45 ms] Updating files.
[        ] Pending asset builds completed. Writing dirty entries.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 49ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x63d5ef4defa0.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on Linux is available at: http://127.0.0.1:37281/5vs2mOy1C3M=/
[ +210 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:37281/5vs2mOy1C3M=/
[+5698 ms] DevFS: Deleting filesystem on the device (file:///tmp/application_announceSRCXUJ/application_announce/)
[   +3 ms] DevFS: Deleted filesystem on the device (file:///tmp/application_announceSRCXUJ/application_announce/)
[  +14 ms] Application finished.
[   +1 ms] "flutter run" took 8,660ms.
[   +1 ms] Running 3 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] Service protocol connection closed.
[        ] exiting with code 0

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.2, on Ubuntu 24.04.3 LTS 6.14.0-27-generic, locale en_US.UTF-8) [26ms]
    • Flutter version 3.35.2 on channel stable at /home/[USERNAME]/fvm/versions/3.35.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05db968908 (28 hours ago), 2025-08-25 10:21:35 -0700
    • Engine revision a8bfdfc394
    • Dart version 3.9.0
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-lldb-debugging

[✗] Android toolchain - develop for Android devices [17ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome) [8ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop [133ms]
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    ! Unable to access driver information using 'eglinfo'.
      It is likely available from your distribution (e.g.: apt install mesa-utils)

[!] Android Studio (not installed) [6ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] VS Code (version 1.103.0) [6ms]
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.116.0

[✓] Connected device (1 available) [18ms]
    • Linux (desktop) • linux • linux-x64 • Ubuntu 24.04.3 LTS 6.14.0-27-generic

[✓] Network resources [287ms]
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

### LINKED ISSUE #174511: IconButton.color is overidden by IconButtonTheme
### Steps to reproduce

1. Run the code sample
2. Observe the icon button color

### Expected results

The icon is green according to `IconButton.color` property

Image

### Actual results

The icon is purple according to the ambient `IconButtonTheme`, despite `IconButton.color` being set to green.

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const IconButtonDemo());

class IconButtonDemo extends StatelessWidget {
  const IconButtonDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        iconButtonTheme: const IconButtonThemeData(
          style: ButtonStyle(iconColor: WidgetStateColor.fromMap({WidgetState.any: Colors.purple})),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: IconButton(
            onPressed: () {},
            icon: const Icon(Icons.build_circle, size: 64),
            color: Colors.green,
          ),
        ),
      ),
    );
  }
}


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel [user-branch], 3.36.0-1.0.pre-286, on Ubuntu 24.04.2 LTS 6.8.0-78-generic, locale fr_FR.UTF-8)
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes IconButton icon color resolution. 

## Before

The IconButton.color property does not take precedence over the ambient `IconButtonTheme`

## After

The IconButton.color property overrides the ambient `IconButtonTheme`.

## Related Issue

Fixes [SnackBar closeIconColor does not respect widget override](https://github.com/flutter/flutter/issues/174472)
Fixes [IconButton.color is overidden by IconButtonTheme](https://github.com/flutter/flutter/issues/174511)  

## Tests

Adds 1 test.

### CODE REVIEW

**Review by victorsanni — APPROVED** [review]
LGTM. Thanks for the change.

**Comment by victorsanni** [comment]
Google testing failures seem legitimate.

**Comment by bleroux** [comment]
@victorsanni Thanks for the review :pray: 
Can you share some details about the Google tests failures?
Are they related to IconButtons only or to other button types? If the later I can probably narrow my fix.

File: packages/flutter/lib/src/material/button_style_button.dart [hunk 1]
```diff
@@ -394,8 +394,8 @@ class _ButtonStyleState extends State<ButtonStyleButton> with TickerProviderStat
 
     Color? effectiveIconColor() {
       return widgetStyle?.iconColor?.resolve(statesController.value) ??
-          themeStyle?.iconColor?.resolve(statesController.value) ??
           widgetStyle?.foregroundColor?.resolve(statesController.value) ??
+          themeStyle?.iconColor?.resolve(statesController.value) ??
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/button_style_button.dart]: is it possible to make widgetStyle.iconColor grab IconButton.color? That should help with the google failures.

Comment (victorsanni) [reply packages/flutter/lib/src/material/button_style_button.dart]: instead of changing the order for resolving these colors.

Comment (victorsanni) [reply packages/flutter/lib/src/material/button_style_button.dart]: I found https://github.com/flutter/flutter/issues/163126 and https://github.com/flutter/flutter/pull/162880/files#r1952065274

Comment (bleroux) [reply packages/flutter/lib/src/material/button_style_button.dart]: > is it possible to make widgetStyle.iconColor grab IconButton.color?

Thanks for the suggestion, I updated the PR to restrict the code change to IconButton.
Let see how it goes with Google tests now :crossed_fingers:

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/material/icon_button.dart [hunk 2]
```diff
@@ -652,6 +652,7 @@ class IconButton extends StatelessWidget {
     Color? focusColor,
     Color? hoverColor,
     Color? highlightColor,
+    Color? iconColor,
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/icon_button.dart]: This seems will be a duplicate api with foregroundColor.

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/icon_button.dart]: Should we just add documentation for ButtonStyle.iconColor? We can mention this is used for common buttons like Elevated, Filled, FilledTonal, Outlined, and Text buttons. For IconButton, use foregroundColor.

Comment (bleroux) [reply packages/flutter/lib/src/material/icon_button.dart]: You mean discouraging users from doing the following?

```dart
        iconButtonTheme: const IconButtonThemeData(
          style: ButtonStyle(iconColor: WidgetStateColor.fromMap({WidgetState.any: Colors.purple})),
        ),
```

It seems counterintuitive that iconColor does not apply to the icon color. Documentation will help but it would be more user friendly if iconColor applies to the IconButton icon.
Let me know if we go to the documentation only change or if we try to get the Google tests green.

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/icon_button.dart]: > You mean discouraging users from doing the following?

No, sorry for the confusion. I mean for IconButton.styleFrom method, we already have a foregroundColor, so I really think it's unnecessary to introduce another one. For ButtonStyle, you are definitely right:)! The icon color should respect ButtonStyle.iconColor.

The priority for these color-related properties are:
IconButton.style -> IconButton.color -> IconButtonTheme.style -> default style

This is my understanding for the issue. When IconButton.color is not null, its value is passed to `adjustedStyle.foregroundColor` in `IconButton`, and will merge with `IconButton.style`. So after the [merge](https://github.com/flutter/flutter/blob/d438f2e52741f027ab11fb4e0c45b666d0a621c5/packages/flutter/lib/src/material/icon_button.dart#L745), this `adjustedStyle` will be passed to `ButtonStyleButton.widgetStyle`. But because in ButtonStyleButton, **theme** iconColor has higher priority then **widget** foregroundColor, so the issue happened. This priority order makes sense to common buttons but not for `IconButton`.

One solution I can think of is: after the merge in IconButton, if `adjustedStyle.iconColor` is still null, we should copy `adjustedStyle.foregroundColor` into `adjustedStyle.iconColor`. Like:

```dart
      // This is the original implementation to merge styles
      if (style != null) {
        adjustedStyle = style!.merge(adjustedStyle);
      }
      // Add following
      if (adjustedStyle.iconColor == null) {
        adjustedStyle = adjustedStyle.copyWith(iconColor: adjustedStyle.foregroundColor);
      }
```

Sorry for the message wall! Currently this PR change will cause a problem, when we add both IconButton.style(foregroundColor: xxx) and IconButton.color, IconButton.style is not respected. Like:

```dart
IconButton(
    style: IconButton.styleFrom(foregroundColor: Colors.blue),
    onPressed: () {},
    icon: const Icon(Icons.settings_outlined, size: 64),
    color: Colors.green,
),
```

Comment (bleroux) [reply packages/flutter/lib/src/material/icon_button.dart]: Many thanks for the clarification 🙏 

I agree with your solution which relies on `ButtonStyle.copyWith(iconColor`. I did not realized that `iconColor` was a valid `copyWith` parameter, I started with `IconButton.styleFrom` which does not have the iconColor parameter (see https://github.com/flutter/flutter/issues/163126) and quickly jump to another way.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thank you for the fix!
