### PR TITLE
[gen_l10n] When localizing a message, prefer placeholder definitions defined by the current locale rather than the template locale

### LINKED ISSUE #116716: Bug: Custom Dateformats always use english locale
## Description
When using placeholder for DateTimes with custom formatting, flutter always uses the custom format from english.

## Steps to Reproduce

1. Setup Localization as per [official docs](https://docs.flutter.dev/development/accessibility-and-localization/internationalization)
2. Fill localization with custom date formats:
```
// app_en.arb
{
	"date": "{date}",
	"@date": {
		"placeholders": {
			"date": {
				"type": "DateTime",
				"format": "MM/dd/yyyy",
				"isCustomDateFormat": "true"
			}
		}
	}
}
```

```
// app_de.arb
{
	"date": "{date}",
	"@date": {
		"placeholders": {
			"date": {
				"type": "DateTime",
				"format": "dd.MM.yyyy",
				"isCustomDateFormat": "true"
			}
		}
	}
}
```
3. run `flutter gen-l10n`
4. Look into the generated code for de_locale: .dart_tool/flutter_gen/gen_l10n/app_localization_de.dart

**Expected results:**
I expect the generated format to be **dd.MM.yyyy**
```
  String date(DateTime date) {
    final intl.DateFormat dateDateFormat = intl.DateFormat('dd.MM.yyyy', localeName);
    final String dateString = dateDateFormat.format(date);

    return '$dateString';
  }
```

**Actual results:**
But the generated format is **MM/dd/yyyy**
```
  String date(DateTime date) {
    final intl.DateFormat dateDateFormat = intl.DateFormat('MM/dd/yyyy', localeName);
    final String dateString = dateDateFormat.format(date);

    return '$dateString';
  }
```

### LINKED ISSUE #153457: date formats and number formats always use template arb
### Steps to reproduce

Similar to #116716, but without `isCustomDateFormat`.

**app_en.arb**

```json
{
  "@@locale": "en",
  "large": "N:{number}",
  "@large": {
    "placeholders": {
      "number": {
        "type": "int",
        "format": "compact"
      }
    }
  },
  "spring": "S:{springStartDate}",
  "@spring": {
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "MMMd"
      }
    }
  }
}
```

**app_ja.arb**

```json
{
  "@@locale": "ja",
  "large": "数:{number}",
  "@large": {
    "placeholders": {
      "number": {
        "type": "int",
        "format": "compactLong"
      }
    }
  },
  "spring": "春:{springStartDate}",
  "@spring": {
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "MMMMd"
      }
    }
  }
}
```

### Expected results

**app_localizations_ja.dart**

```dart
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Japanese (`ja`).
class AppLocalizationsJa extends AppLocalizations {
  AppLocalizationsJa([String locale = 'ja']) : super(locale);

  @override
  String large(int number) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.compactLong(
      locale: localeName,
      
    );
    final String numberString = numberNumberFormat.format(number);

    return '数:$numberString';
  }

  @override
  String spring(DateTime springStartDate) {
    final intl.DateFormat springStartDateDateFormat = intl.DateFormat.MMMMd(localeName);
    final String springStartDateString = springStartDateDateFormat.format(springStartDate);

    return '春:$springStartDateString';
  }
}
```

### Actual results

**app_localizations_ja.dart**

```dart
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Japanese (`ja`).
class AppLocalizationsJa extends AppLocalizations {
  AppLocalizationsJa([String locale = 'ja']) : super(locale);

  @override
  String large(int number) {
    final intl.NumberFormat numberNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String numberString = numberNumberFormat.format(number);

    return '数:$numberString';
  }

  @override
  String spring(DateTime springStartDate) {
    final intl.DateFormat springStartDateDateFormat = intl.DateFormat.MMMd(localeName);
    final String springStartDateString = springStartDateDateFormat.format(springStartDate);

    return '春:$springStartDateString';
  }
}
```

### Code sample

<details open><summary>Code sample</summary>

**app_en.arb**

```json
{
  "@@locale": "en",
  "large": "N:{number}",
  "@large": {
    "placeholders": {
      "number": {
        "type": "int",
        "format": "compact"
      }
    }
  },
  "spring": "S:{springStartDate}",
  "@spring": {
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "MMMd"
      }
    }
  }
}
```

**app_ja.arb**

```json
{
  "@@locale": "ja",
  "large": "数:{number}",
  "@large": {
    "placeholders": {
      "number": {
        "type": "int",
        "format": "compactLong"
      }
    }
  },
  "spring": "春:{springStartDate}",
  "@spring": {
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "MMMMd"
      }
    }
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale ja-JP)
    • Flutter version 3.24.0 on channel stable at /Users/kzrnm/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kzrnm/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by kzrnm**
- Fixes #153457
- Fixes #116716

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 1]
```diff
@@ -345,6 +345,7 @@ class Message {
       value = _value(templateBundle.resources, resourceId),
       description = _description(templateBundle.resources, resourceId, isResourceAttributeRequired),
       placeholders = _placeholders(templateBundle.resources, resourceId, isResourceAttributeRequired),
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:347]: should we rename `placeholders` to `templatePlaceholders` to better differentiate between it and `localePlaceholders`?

**Comment by andrewkolos** [comment]
Should https://github.com/flutter/flutter/blob/b364c07c1fa6241dfc4c7cb427837f54dff0e4b9/packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart#L397 be updated to also consider placeholder definitions from non-template arb files?

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart (hunk 1 above)
Comment (kzrnm) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart]: I renamed it.

**Comment by kzrnm** [comment]
@andrewkolos
I added support for cases where `format` is defined only in non-template and vice versa.

https://github.com/flutter/flutter/blob/d01e119f9cb95ec9f02319de1e8f933b0755edff/packages/flutter_tools/test/general.shard/generate_localizations_test.dart#L2683-L2759

There are two changes that accompany this change.

1. Always import package:intl/intl.dart
It is cumbersome to determine if it is necessary to import intl for each locale, so I changed it to always import it.
2. Compatibility Check
I added compatibility checks that will generate an error if a method is generated that is incompatible with the template. I am not a native English speaker, so if the error message is unnatural, please suggest a better fix.
https://github.com/flutter/flutter/blob/d01e119f9cb95ec9f02319de1e8f933b0755edff/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L131-L142

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 2]
```diff
@@ -123,23 +123,36 @@ String _syntheticL10nPackagePath(FileSystem fileSystem) => fileSystem.path.join(
...
-  return message.placeholders.values.map((Placeholder placeholder) {
+List<String> generateMethodParameters(Message message, LocaleInfo? locale, bool useNamedParameters) {
+
+  // check the compatibility of template placeholders and locale placeholders.
+  final Map<String, Placeholder>? localePlaceholders = message.localePlaceholders[locale];
+
+  return message.templatePlaceholders.entries.map((MapEntry<String, Placeholder> e) {
+    final Placeholder placeholder = e.value;
+    final String? localePlaceholderType = localePlaceholders?[e.key]?.type;
+    if (localePlaceholderType != null && placeholder.type != localePlaceholderType) {
```
[the remark this answers is not in the document]
Comment (kzrnm) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart:134]: I would like to make the type explicit in this pull request. I think it would be better to loosen the type constraint in another pull request if necessary.

[the remark this answers is not in the document]
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart:134]: Right, i'm saying that I _want_ the type check to be strict, so I always want the type in the template ARB and the other ARBs to always match.

```suggestion
    if (placeholder.type != localePlaceholderType) {
```

**Comment by bkonyi** [comment]
@kzrnm, FYI it looks like some checks are failing now.

File: packages/flutter_tools/lib/src/localizations/gen_l10n_templates.dart [hunk 3]
```diff
@@ -171,7 +171,8 @@ const String dateVariableTemplate = '''
     String @(varName) = intl.DateFormat.@(formatType)(localeName).format(@(argument));''';
 
 const String classFileTemplate = '''
-@(header)@(requiresIntlImport)import '@(fileName)';
+@(header)import 'package:intl/intl.dart' as intl;
```
[the remark this answers is not in the document]
Comment (kzrnm) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_templates.dart]: I understand. I have committed the fix.

**Review by andrewkolos — APPROVED** [review]
LGTM. I will find a second reviewer soon.

(I also just restarted the Google testing check)

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 4]
```diff
@@ -123,23 +123,36 @@ String _syntheticL10nPackagePath(FileSystem fileSystem) => fileSystem.path.join(
...
+List<String> generateMethodParameters(Message message, LocaleInfo? locale, bool useNamedParameters) {
+
+  // Check the compatibility of template placeholders and locale placeholders.
+  final Map<String, Placeholder>? localePlaceholders = message.localePlaceholders[locale];
+
+  return message.templatePlaceholders.entries.map((MapEntry<String, Placeholder> e) {
+    final Placeholder placeholder = e.value;
+    final Placeholder? localePlaceholder = localePlaceholders?[e.key];
+    if (localePlaceholder != null && placeholder.type != localePlaceholder.type) {
+      throw L10nException(
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:135]: Note for second reviewer:

This change _could_[^1] break peoples' builds. Consider

```json
// app_en.arb
{
  "@@locale": "en",
  "springBegins": "Spring begins on {springStartDate}",
  "@springBegins": {
    "description": "The first day of spring",
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "MMMMd"
      }
    }
}
```

and
```json
// app_ja.arb
{
  "@@locale": "ja",
  "springBegins": "春が始まるのは{springStartDate}",
  "@springBegins": {
    "description": "The first day of spring",
    "placeholders": {
      "springStartDate": {
        "type": "int", // Type change.
        "format": "compactCurrency"
      }
    }
  },
```

Then, trying to regenerate localization code will result in a failure:

```
Generating synthetic localizations package failed with 1 error:

Error: The placeholder, springStartDate, has its "type" resource attribute set to the "int" type in locale "ja", but it is "DateTime" in the template placeholders. For
compatibility with template placeholders, change the "type" attribute to "DateTime".
```

I think this failing the build makes sense here, and I believe there's no pre-existing behavior for users to be dependent on here (the `springStartDate` placeholder in the `ja` locale would have been silently ignored, hence this PR). I'm content with this landing without a breaking change announcement.

[^1]: And therefore _will_ 🙃

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 5]
```diff
@@ -123,23 +123,36 @@ String _syntheticL10nPackagePath(FileSystem fileSystem) => fileSystem.path.join(
...
+          'The placeholder, ${placeholder.name}, has its "type" resource attribute set to '
+          'the "${localePlaceholder.type}" type in locale "$locale", but it is "${placeholder.type}" '
+          'in the template placeholders. For compatibility with template placeholders, change '
+          'the "type" attribute to "${placeholder.type}".');
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:139]: Nitpick: I think `placeholders` should be in its singular form here:

```suggestion
          'The placeholder, ${placeholder.name}, has its "type" resource attribute set to '
          'the "${localePlaceholder.type}" type in locale "$locale", but it is "${placeholder.type}" '
          'in the template placeholder. For compatibility with template placeholder, change '
          'the "type" attribute to "${placeholder.type}".');
```

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart (hunk 4 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart:135]: I think that's reasonable.

**Review by bkonyi — APPROVED** [review]
LGTM! Thanks for the contribution. I'll land this when the checks pass.
