### PR TITLE
Make FutureBuilder handle SynchronousFuture correctly, reland SynchronousFuture usage in test assets

### LINKED ISSUE #115171: FutureBuilder is broken with `SynchronousFuture`s.
Will add repro momentarily, cause of rollback in https://github.com/flutter/flutter/pull/115156

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/115171

Allows reland of https://github.com/flutter/flutter/pull/115156

### CODE REVIEW

File: packages/flutter/test/widgets/async_test.dart [hunk 1]
```diff
@@ -87,6 +88,20 @@ void main() {
     });
   });
   group('FutureBuilder', () {
+    testWidgets('gives expected snapshot with SynchronousFuture', (WidgetTester tester) async {
+      final SynchronousFuture<String> future = SynchronousFuture<String>('flutter');
+      await tester.pumpWidget(FutureBuilder<String>(
+        future: future,
+        builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
+          expect(snapshot.connectionState, ConnectionState.done);
```
Comment (dnfield) [inline packages/flutter/test/widgets/async_test.dart:96]: Before this patch, this expectation failed (it would say ConnectionState.waiting and never get called back again because the `then` block got called synchronously).

**Review by jonahwilliams — APPROVED** [review]
LGTM
