### PR TITLE
FlutterDriver: allow customizing timeouts using a multiplier

### LINKED ISSUE #14732: Integration test timeout on headless android emulator
## Steps to Reproduce

1. Create a headless android emulator
2. Create the flutter sample project
3. Create a simple integration test to tap the plus button 4 or so times
4. Run flutter drive.
5. Times out upon the second tap.
Expected: integration should pass as running this exact same test on a non-headless emulator works perfectly fine.

## Logs

Using device Android SDK built for x86.
Starting application: test_driver/simple.dart
Initializing gradle...                                0.7s
Resolving dependencies...                             0.6s
Installing build/app/outputs/apk/app.apk...           3.2s
Running 'gradlew assembleDebug'...                    1.1s
Built build/app/outputs/apk/debug/app-debug.apk (24.6MB).
I/flutter ( 6838): Observatory listening on http://127.0.0.1:42659/
I/FlutterActivityDelegate( 6838): onResume setting current activity to this
00:00 +0: groupTest (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8118/
[trace] FlutterDriver: Looking for the isolate
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: groupTest test tap
tap 1
tap 2
00:06 +0 -1: groupTest test tap [E]
  DriverError: Error in Flutter application: Timeout while executing tap: TimeoutException after 0:00:05.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168)
  <asynchronous suspension>
  #1      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370)
  <asynchronous suspension>
  #2      _runExtension (dart:developer-patch/dart:developer/developer.dart:85)
  
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver/driver.dart 342:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                _Completer.completeError
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart 319:68          FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 368:11          FlutterDriver.tap
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:flutter_driver/src/driver/driver.dart 367:73          FlutterDriver.tap
  test_driver/simple_test.dart 28:22                            main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  test_driver/simple_test.dart 23:31                            main.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                 Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 247:23                  Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 247:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/declarer.dart 143:66                 Declarer.test.<fn>
  package:test/src/backend/invoker.dart 404:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 403:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 367           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 164        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 172                                    new Future
  package:test/src/backend/invoker.dart 403:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 390:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 390:9                   Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 444:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 389:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 388:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 200                                    new Future.microtask.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 376           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 164        _RawReceivePortImpl._handleMessage
  
00:06 +0 -1: groupTest (tearDownAll)
00:06 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:376)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
Stopping application instance.
Driver tests failed: 255

### LINKED ISSUE #23857: Flutter drive: Cannot set timeout on GetHealth command
I am using the default counter app to set-up integration testing on TravisCI. I am running the android emulator on linux and the ios simulator on mac. The default integration test passes on mac/ios/simulator but fails on linux/android/emulator. 

The android emulator is getting a timeout on the driver's GetHealth command when running on Travis (no hardware acceleration, graphics in software). The weird thing is [tests](https://travis-ci.org/brianegan/flutter_architecture_samples/builds/448189417) from other projects are getting past this health check and completing successfully (when timeouts added where permitted). But when I run the default counter app integration test it times out on the GetHealth command. 

This is the test:
```dart
void main() {
  group('end-to-end test', () {
    FlutterDriver driver;
    final timeout = Duration(seconds: 20);

    setUpAll(() async {
      // Connect to a running Flutter application instance.
      driver = await FlutterDriver.connect(
        isolateReadyTimeout: timeout,
        printCommunication: true,
      );
    });

    tearDownAll(() async {
      if (driver != null) driver.close();
    });

    test('tap on the floating action button; verify counter', () async {
      // Finds the floating action button (fab) to tap on
      SerializableFinder fab = find.byTooltip('Increment');

      // Wait for the floating action button to appear
      await driver.waitFor(fab, timeout: timeout);

      // Tap on the fab
      await driver.tap(fab, timeout: timeout);

      // Wait for text to change to the desired value
      await driver.waitFor(find.text('1'), timeout: timeout);
    });
  });
}
```
and the resulting timeout:
```
[   +2 ms]   DriverError: Failed to fulfill GetHealth: Flutter application not responding
[        ]   Original error: TimeoutException after 0:00:07.500000: Future not completed
```

Here is the same [line](https://travis-ci.org/mmcc007/flutter_app/jobs/449653236#L3218) in the build on travis.

I tried increasing timeouts wherever I could, but the GetHealth time out is unaffected.
Is there a way to fix this? I suspect it would pass if I could add a timeout to GetHealth, but there might be another way.

```
[✓] Flutter (Channel unknown, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/travis/build/mmcc007/flutter_app/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.
[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
[✓] Connected devices (1 available)
    • sdk phone armv7 • emulator-5554 • android-arm • Android 5.1.1 (API 22) (emulator)
! Doctor found issues in 1 category.
```

Here is the complete source code:
https://github.com/mmcc007/flutter_app/tree/f2738cfd44802e51ab2d47c0824b096ab57617f8
and the build on travis showing it working on ios but failing on android:
https://travis-ci.org/mmcc007/flutter_app/builds/449653234

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes #14732
Fixes #23857

### CODE REVIEW

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 1]
```diff
@@ -61,25 +61,38 @@ enum TimelineStream {
...
+/// See also:
+///
+///  * [FlutterDriver.timeoutMultiplier], which multiplies all command timeouts by this number.
+double connectionTimeoutMultiplier = _kDefaultTimeoutMultiplier;
+
+const double _kDefaultTimeoutMultiplier = 1.0;
+
 /// Default timeout for short-running RPCs.
-const Duration _kShortTimeout = Duration(seconds: 5);
+Duration _kShortTimeout(double multiplier) => const Duration(seconds: 5) * multiplier;
```
Comment (gspencergoog) [inline packages/flutter_driver/lib/src/driver/driver.dart]: Shouldn't these now be named `_shortTimeout`, etc.?  They're no longer const variables, and because of their names, I would be surprised to find that these took arguments.

Comment (yjbanov) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Good point! Which is also why I don't like the "k" prefixes and supported the move from `SCREAMING_CAPS_CONSTANTS` to `lowerCaseConstants` :)

**Comment by yjbanov** [comment]
Friendly ping.

**Review by gspencergoog — APPROVED** [review]

**Comment by Hixie** [comment]
Sorry I missed this PR, I just ran into it since it conflicted with one of my branches. I am planning on just out-and-out removing most of these timeouts, because they are basically just race conditions. Let me know if that's a problem.

**Comment by yjbanov** [comment]
Eliminating race conditions would be great! Most timeouts are not about working around race conditions though. They are there to deal with the fundamental issue of driver tests running code on more than one device simultaneously. When one device asks another device for something the other device is totally free to never respond.

However, there are some timeouts that are about race conditions. For example, when waiting for the app to boot up the best method I could think of at the time was to wait for it, then time out if it didn't in a reasonable amount of time.
