### PR TITLE
Fix `MenuItemButton` overflow

### LINKED ISSUE #129439: MenuItemButton does not constrain its child
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the attached code and then make the window too narrow for the button.

### Expected results

A menu item button with text that overflows with ellipsis.

### Actual results

Layout error that the content of the button overflows its parent.

image

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MenuItemButton Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Center(
        child: SizedBox(
          width: 300,
          child: MenuItemButton(
            child: const Text(
              'dsfljsadlkfjskfdljsaldkfjklsdsdaflajflkdjflsfjlaskdjfdadlkfksfljds',
              overflow: TextOverflow.ellipsis,
              maxLines: 1,
              softWrap: false,
            ),
            onPressed: () {},
          ),
        ),
      ),
    );
  }
}
```

The problem is the two nested Rows in the _MenuItemLabel, according to the widget inspector:

image

Note how the outer Row has the right constraint, while the inner one is unconstrained.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Ubuntu 23.04 6.2.0-23-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your
      PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

### LINKED ISSUE #140596: DropdownMenuEntry Text Overflow when width of DropdownMenu is not specified
### Steps to reproduce

1. Use dartpad here: https://api.flutter.dev/flutter/material/DropdownMenu-class.html 
2. Replace `width: 300` to `expandedInsets: EdgeInsets.zero`
3. The text in `DropdownMenuEntry` overflow

### Expected results

The text in `DropdownMenuEntry` should not overflow

### Actual results

The text in `DropdownMenuEntry` overflow

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for the [DropdownMenuEntry] `labelWidget` property.

enum ColorItem {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Yellow', Colors.yellow),
  grey('Grey', Colors.grey);

  const ColorItem(this.label, this.color);
  final String label;
  final Color color;
}

class DropdownMenuEntryLabelWidgetExample extends StatefulWidget {
  const DropdownMenuEntryLabelWidgetExample({super.key});

  @override
  State<DropdownMenuEntryLabelWidgetExample> createState() =>
      _DropdownMenuEntryLabelWidgetExampleState();
}

class _DropdownMenuEntryLabelWidgetExampleState
    extends State<DropdownMenuEntryLabelWidgetExample> {
  late final TextEditingController controller;

  @override
  void initState() {
    super.initState();
    controller = TextEditingController();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Created by Google Bard from 'create a lyrical phrase of about 25 words that begins with "is a color"'.
    const String longText =
        'is a color that sings of hope, A hue that shines like gold. It is the color of dreams, A shade that never grows old.';

    return Scaffold(
      body: Center(
        child: DropdownMenu<ColorItem>(
          expandedInsets: EdgeInsets.zero,
          controller: controller,
          initialSelection: ColorItem.green,
          label: const Text('Color'),
          onSelected: (ColorItem? color) {
            print('Selected $color');
          },
          dropdownMenuEntries: ColorItem.values
              .map<DropdownMenuEntry<ColorItem>>((ColorItem item) {
            final String labelText = '${item.label} $longText\n';
            return DropdownMenuEntry<ColorItem>(
              value: item,
              label: labelText,
              // Try commenting the labelWidget out or changing
              // the labelWidget's Text parameters.
              labelWidget: Text(
                labelText,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}

class DropdownMenuEntryLabelWidgetExampleApp extends StatelessWidget {
  const DropdownMenuEntryLabelWidgetExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: DropdownMenuEntryLabelWidgetExample(),
    );
  }
}

void main() {
  runApp(const DropdownMenuEntryLabelWidgetExampleApp());
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.2861], locale en-US)
    • Flutter version 3.16.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (5 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\maich\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\maich\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.8.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.8.34316.72
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Users\maich\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Users\maich\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at C:\Users\maich\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.2861]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.111
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.91

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [MenuItemButton does not constrain its child](https://github.com/flutter/flutter/issues/129439)
fixes [DropdownMenuEntry Text Overflow when width of DropdownMenu is not specified](https://github.com/flutter/flutter/issues/140596)

### Description

- This PR continues the fix from https://github.com/flutter/flutter/pull/141314#issuecomment-1945804640 and adds controlled widths for the `MenuBar` children to fix the unbounded width issue which blocked the PR earlier. (Widgets  with non-zero flex value cannot be laid out in a horizontal scroll view which is created by `MenuBar` widget)
- Added tests coverage.
- Added documentation.

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  MenuController menuController = MenuController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              DropdownMenu<int>(
                expandedInsets: EdgeInsets.zero,
                dropdownMenuEntries: <DropdownMenuEntry<int>>[
                  DropdownMenuEntry<int>(
                    value: 0,
                    label:
                        'This is a long text that is multiplied by 10. ' * 10,
                    style: const ButtonStyle(
                      textStyle: MaterialStatePropertyAll(
                        TextStyle(overflow: TextOverflow.ellipsis),
                      ),
                    ),
                  ),
                ],
              ),
              SizedBox(
                width: 200,
                child: MenuItemButton(
                  onPressed: () {},
                  leadingIcon: const Icon(Icons.menu),
                  trailingIcon: const Icon(Icons.arrow_forward_ios),
                  child: const Text(
                    'This is a very long text that will wrap to the multiple lines.',
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
              // MenuBar(
              //   children: [
              //     MenuItemButton(
              //       onPressed: () {

              //       },
              //       child: Text('Short Text Menu'),
              //     ),
              //     MenuItemButton(
              //       onPressed: () {},
              //       child: Text('Very very very very very long text menu'),
              //     ),
              //   ],
              // ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Before

before

### After
after

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -923,6 +924,15 @@ class MenuItemButton extends StatefulWidget {
...
   final bool closeOnActivate;
 
+  /// The direction in which the menu item expands.
+  ///
+  /// If [menuDirection] is [Axis.vertical], the menu will be expanded vertically.
+  /// If [menuDirection] is [Axis.horizontal], then the menu  will be
+  /// expanded horizontally.
+  ///
+  /// Defaults to [Axis.vertical].
+  final Axis menuDirection;
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/menu_anchor.dart:934]: Thanks for your continued help with the fix! I'm actually thinking about the property name. Based on the doc and the name, it feels like setting `menuDirection: Axis.vertical` can control the menu to make it show up vertically. Not sure if that can cause any confusion. 

I'm now actually thinking maybe we don't need to add an extra property here. In `_MenuItemButtonState`, we can have a 

```dart
  _MenuAnchorState? get _anchor => _MenuAnchorState._maybeOf(context);
```

then we can just use `_anchor._orientation` to get the menu direction information(vertical or horizontal). Do you think if this makes sense?

Comment (TahaTesser) [reply packages/flutter/lib/src/material/menu_anchor.dart:934]: When writing test for this property,  I did write comments to make it clear how this property is adjusted for the layout to flex in certain direction.

```dart
      // Test a long MenuItemButton in an unconstrained layout with vertical menuDirection.
      await tester.pumpWidget(buildMenuButton(menuDirection: Axis.vertical));
      expect(tester.getSize(find.byType(MenuItemButton)), const Size(800.0, 48.0));

      // Test a long MenuItemButton in an unconstrained layout with horizontal menuDirection.
      await tester.pumpWidget(buildMenuButton(menuDirection: Axis.horizontal));
      expect(tester.getSize(find.byType(MenuItemButton)), const Size(800.0, 48.0));

      // Test a long MenuItemButton in a constrained layout with vertical menuDirection.
      await tester.pumpWidget(buildMenuButton(menuDirection: Axis.vertical, constrainedLayout: true));
      expect(tester.getSize(find.byType(MenuItemButton)), const Size(200.0, 120.0));

      // Test a long MenuItemButton in a constrained layout with horizontal menuDirection.
      await tester.pumpWidget(buildMenuButton(menuDirection: Axis.horizontal, constrainedLayout: true));
      expect(tester.getSize(find.byType(MenuItemButton)), const Size(200.0, 48.0));
      // This should throw an error.
      final AssertionError exception = tester.takeException() as AssertionError;
      expect(exception, isAssertionError);
```

You're absolutely right we need to make clear for the users to avoid confusion.

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/menu_anchor.dart:934]: > The _anchor._orientation is null when MenuItemButton is used directly.

I see! You are right. I'm thinking about 3 options. One is still getting the direction from anchor, but we need to explicitly mention in the doc that these buttons are just used for menus; Other use cases might cause overflow. Because I'm not sure whether *menu*ItemButton should be used without any menu involved🤣. 

The second option is just to give a better property name, `menuFlexDirection` is a good one, I'm also thinking about a boolean `allowHorizontalExpansion` or something else. If the button is placed on a vertical menu, it is false and we do clip to avoid overflow; if it is placed on a horizontal menu, we should allow the expansion. But for this option, it is still a breaking change for `MenuBar`s if they already use `MenuItemButton`. The default property value will cause exception and users need to explicitly assign a value to `menuFlexDirection`.

The third one is to combine the first two. We still expose this property, but if anchor is not null, the anchor direction should override the property to avoid breaking change.🙂 Let me know which one is preferred!

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/menu_anchor.dart:934]: Please also let me know if I missed any other PR review!🙂 Thanks a lot!

**Comment by TahaTesser** [comment]
This is failing HTML tests for some reason which didn't fail earlier.

 I was busy updating others today, i will finish updating this by tomorrow.

**Comment by QuncCccccc** [comment]
> This is failing HTML tests for some reason which didn't fail earlier.
> 
> I was busy updating others today, i will finish updating this by tomorrow.

I see! Please take your time! As for the web tests, it looks like https://github.com/flutter/flutter/pull/142804 also has a similar web failure and the failure is also about `computeDryLayout`🧐

**Comment by TahaTesser** [comment]
I tried running cavaskit tests locally, they pass. Something off with HTML renderer and computeDryLayout.

**Comment by TahaTesser** [comment]
> This is failing HTML tests for some reason which didn't fail earlier.

Since this wasn't failing a couple of weeks ago (before my vacation), so I decided to investigated the cause. 

HTML renderer tests are failing due after https://github.com/flutter/flutter/pull/144577. 
I can confirm this PR passes HTML tests before https://github.com/flutter/flutter/pull/144577

**Comment by LongCatIsLooong** [comment]
The HTML render probably doesn't handle FP errors while doing line breaks. In that failing test, the input max width is `225.59999999999994` px and the intrinsic width of the text is `225.59999999999997` px, so the html renderer broke the text into 2 lines. Could you file an issue if there isn't one already, and skip that test if the HTML renderer is in use? Or you can change the font size / letterspacing used in the test so the width of the text becomes an integer.

File: packages/flutter/lib/src/material/menu_anchor.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/menu_anchor.dart]: I've changed the name and condition where `_anchor` orientational can override the property. This implemented the third option you suggest.
https://github.com/flutter/flutter/pull/143932/commits/01006f3a90802f32558345af2f98e893ddaa1b3f

Please let me know what do you think.

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the fix!

**Comment by TahaTesser** [comment]
@QuncCccccc 
This seems to be failing Google testing.

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 2]
```diff
@@ -923,6 +924,18 @@ class MenuItemButton extends StatefulWidget {
...
+  ///
+  /// If the menu item button is created by the [MenuAnchor] or [MenuBar], then
+  /// this property is ignored.
+  ///
+  /// If [menuFlexDirection] is [Axis.vertical], the menu will be expanded vertically.
+  /// If [menuFlexDirection] is [Axis.horizontal], then the menu  will be
+  /// expanded horizontally.
+  ///
+  /// Defaults to [Axis.vertical].
+  final Axis menuFlexDirection;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/menu_anchor.dart:937]: How about `overflowDirection` or `overflowAxis` as a name?  This one isn't great: it has menu, which is redundant, and Flex which might indicate a `Flex` widget or just being "flexible", which this isn't.

**Comment by QuncCccccc** [comment]
> @QuncCccccc This seems to be failing Google testing.

This seems because when the button is used in a `Row`, with its default setting, it will still throw exception.

**Comment by TahaTesser** [comment]
> > @QuncCccccc This seems to be failing Google testing.
> 
> This seems because when the button is used in a `Row`, with its default setting(Axis.vertical), it will still throw exception.

This looks like an expected error given the layout. We want menu item button with vertical direction to take maximum available width (e.g. in `DropdownMenu` or `MenuAnchor`) but this wouldn't work when `MenuItemButton` is placed in a layout infinite width such as `Row`. 

The user have wrap the widget `MenuItemButton` with `Expanded` widget or `Flexible` widget for the non-zero flex or provide a fixed width using a `SizedBox` or `ConstrainedBox`.  

Screenshot 2024-03-28 at 15 04 42

**Comment by QuncCccccc** [comment]
> > > @QuncCccccc This seems to be failing Google testing.
> > 
> > 
> > This seems because when the button is used in a `Row`, with its default setting(Axis.vertical), it will still throw exception.
> 
> This looks like an expected error given the layout. We want menu item button with vertical direction to take maximum available width (e.g. in `DropdownMenu` or `MenuAnchor`) but this wouldn't work when `MenuItemButton` is placed in a layout infinite width such as `Row`.
> 
> The user have wrap the widget `MenuItemButton` with `Expanded` widget or `Flexible` widget for the non-zero flex or provide a fixed width using a `SizedBox` or `ConstrainedBox`.
> 
> Screenshot 2024-03-28 at 15 04 42

Yes, you are right. For the default setting, I'm thinking if we should set the default value to be `Axis.horizontal` because that would be the original implementation and should not break the existing apps. And if users need to fix the overflow issue, `overflowAxis` should be set to `Axis.vertical`. WDYT:) ?

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 3]
```diff
@@ -923,6 +924,18 @@ class MenuItemButton extends StatefulWidget {
   /// {@endtemplate}
   final bool closeOnActivate;
 
+  /// The direction in which the menu item expands.
+  ///
+  /// If the menu item button is created by the [MenuAnchor] or [MenuBar], then
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/menu_anchor.dart:929]: The `MenuItemButton` not really created by them, but it can appear as their child. Might want to reword this.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
> For the default setting, I'm thinking whether we should set the default value to be Axis.horizontal because that would be the original implementation and should not break the existing apps. And if users need to fix the overflow issue, overflowAxis should be set to Axis.vertical. WDYT:) ?

Sounds good to me.

File: packages/flutter/lib/src/material/menu_anchor.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/menu_anchor.dart:929]: Good point!

**Comment by TahaTesser** [comment]
@QuncCccccc 
Thank you for all the support, it wouldn't have been possible to land this without you.
