### PR TITLE
Fix ScrollPosition.isScrollingNotifier.value for pointer scrolling

### LINKED ISSUE #75591: ScrollPosition.isScrollingNotifier returns false when using scroll-wheel and two-finger gesture in trackpad
I have only tried this on a mac device, as a mac app and a web app. When using the trackpad to scroll a view, the  `ScrollPosition.isScrollingNotifier`
returns false.
If I scroll by clicking and dragging it, the notifier returns true. 

At least on macos, the default way of scrolling into views is using the two-finger gesture. If you click and drag inside a native app, this one does not scroll, but a Flutter app does.

## Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyListView()));
}
class MyListView extends StatefulWidget {
  @override
  _MyListViewState createState() => _MyListViewState();
}

class _MyListViewState extends State<MyListView> {
  final ScrollController controller = ScrollController();

  @override
  void initState() {
    controller.addListener(() {
      // always prints "scrolling = true"
      print('scrolling = ${controller.position.isScrollingNotifier.value}');
    });
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: ListView.builder(
      controller: controller,
      itemCount: 20,
      itemBuilder: (BuildContext context, int index) {
        return ListTile( 
          title: Text('$index'),
        );
      },
    ),
    );
  }
}
```

```
Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-ES)
```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/75591

The value of the `isScrollingNotifier` was not being set before `forcePixels` was called - which is when the listeners are notified. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 1]
```diff
@@ -810,8 +810,6 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   ///
   /// This method is very similar to [jumpTo], but [pointerScroll] will
   /// update the [ScrollDirection].
-  ///
-  // TODO(YeungKC): Support trackpad scroll, https://github.com/flutter/flutter/issues/23604.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:814]: I removed this while I was here since this issue is closed now. :)

**Review by pdblasi-google — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM :+1:
