### PR TITLE
start and stop chromedriver once per sub-shard; do not wait for it to quit

### LINKED ISSUE #69421: Flake in long running web integration tests: connection reset by peer
```
▌17:30:00▐ ELAPSED TIME: 3min 27.271s for ../../../bin/flutter drive --dart-define=FLUTTER_WEB_USE_SKIA=true --driver=test_driver/transitions_perf_e2e_test.dart --target=test_driver/transitions_perf_e2e.dart --browser-name=chrome -d web-server --profile in dev/integration_tests/flutter_gallery
Integration test passed.
Unhandled exception:
OS Error: Connection reset by peer, errno = 104
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864995775464176832/+/steps/run_test.dart_for_web_long_running_tests_shard_and_subshard_1/0/stdout

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Start one shared instance of chromedriver and quit it at the end. This removes the need to check for driver connection at the end of the test, which seems to be leaving sockets that are not fully closed.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/69421

### CODE REVIEW

File: dev/bots/test.dart [hunk 1]
```diff
@@ -879,11 +870,8 @@ Future<void> _stopChromeDriver() async {
   if (_chromeDriver == null) {
     return;
   }
+  print('Stopping chromedriver');
   _chromeDriver.process.kill();
-  while (await _isChromeDriverRunning()) {
```
Comment (yjbanov) [inline dev/bots/test.dart:883]: My assumption is that pinging the chromedriver while it's shutting down is what's triggering the issue in the client socket implementation, so removing the need to wait for chromedriver to shut down should also :crossed_fingers: fix the flakiness.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Review by jonahwilliams — APPROVED** [review]
Still LGTM

**Review by nturgut — APPROVED** [review]

File: dev/bots/test.dart [hunk 2]
```diff
@@ -816,8 +816,10 @@ Future<void> _runWebLongRunningTests() async {
     () => _runGalleryE2eWebTest('profile', canvasKit: true),
     () => _runGalleryE2eWebTest('release'),
     () => _runGalleryE2eWebTest('release', canvasKit: true),
-  ].map(_withChromeDriver).toList();
+  ];
+  await _ensureChromeDriverIsRunning();
   await _selectIndexedSubshard(tests, kWebLongRunningTestShardCount);
```
Comment (nturgut) [inline dev/bots/test.dart:821]: Suggestion:Shall we add a comment explaining why we shutdown?

Comment (yjbanov) [reply dev/bots/test.dart:821]: I'm not sure? All our tests try to shutdown processes they start. It's like `tearDown`. If you can think of something that would explain something special about chromedriver, I'd be happy to add it. LMK.
