### PR TITLE
Fixed scrollable TabBar flashing

### LINKED ISSUE #8590: Flutter Gallery scrollable tabs demo: tabbar flashes
Paging to the left and right causes the tabbar to flash.

Here's a video:  https://youtu.be/DCjwaN9C27M

### LINKED ISSUE #8658: Snapping janking with tab underlines in public Flutter app
Took a movie here: https://youtu.be/eRbYeuPh_Gs

From this public app: https://play.google.com/store/apps/details?id=com.starheightmedia.intallinn

Please notice the underlines of the tabs as I swipe back and forth. They seem to snap into place, with a very abrupt animation.

We would like to see smooth animation of the tab titles and underlines.

### PR DESCRIPTION
**Pull request by HansMuller**
Eliminated the repaint flashing that occurred on tab bar drags and flings.

Changing the tab label drag highlighting: the tab labels change now opacity during the drag.

Fixes: https://github.com/flutter/flutter/issues/8658
Fixes: https://github.com/flutter/flutter/issues/8590

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -509,20 +525,22 @@ class _TabBarState extends State<TabBar> {
...
+    if (!_controller.indexIsChanging && config.isScrollable) {
+      // Sync the TabBar's scroll position with the TabBarView's PageView.
+      _currentIndex = _controller.index;
       _scrollToControllerValue();
     }
   }
 
+  void _handleTabControllerTick() {
+    setState(() {
+      // Rebuild the tabs after the possiby animated index change
```
Comment (Hixie) [inline packages/flutter/lib/src/material/tabs.dart]: typo

**Comment by Hixie** [comment]
fancy. LGTM.
