### PR TITLE
[web] Fix assertion thrown when hot restarting during animation

### LINKED ISSUE #140684: bug: a few hot restarts cause a canvaskit failure
### Steps to reproduce

1. Open example in VSCode, chose web platform
2. Set a breakpoint on line that calls runApp
3. Debug
4. Then the breakpoint is hit, click hot restart a few times

Issues related:

https://github.com/flutter/flutter/issues/90236

### Expected results

Not error when make hot reload

### Actual results

The app is freezed and show a error in console. The dialog of "Flutter: Hot reloading" not close.

Captura de pantalla 2023-12-27 a la(s) 10 25 48 p m

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Debug service listening on ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Connecting to VM Service at ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Restarted application in 1,307ms.
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 89:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

</details>

In some case show this error to

```console
Restarted application in 2,200ms.
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 89:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2 23C64 darwin-arm64, locale es-US)
    • Flutter version 3.16.5 on channel stable at /Users/yeikel/fvm/versions/3.16.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (hace 8 días), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/yeikel/Library/Android/sdk/
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/yeikel/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2020.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.
```

</details>

### LINKED ISSUE #175260: CircularProgressIndicator and other animation controllers on Flutter Web throws infinite !isDisposed exceptions after hot restart (regression in Flutter 3.35 / Dart 3.9)
### Steps to reproduce

After upgrading to Flutter 3.35.3 stable with Dart 3.9.2, hot restarting a web app that contains a CircularProgressIndicator causes an infinite stream of exceptions:

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

This continues endlessly until the browser tab is refreshed.

This did not occur on earlier Flutter versions (≤3.32.x). It appears to be a regression in how the web engine handles active tickers across hot restart.

Steps to Reproduce:

Create a new Flutter project.

Replace main.dart with the code below.

Run in Chrome (flutter run -d chrome).

Perform a hot restart in Android Studio or from the terminal.

Observe the infinite !isDisposed spam in the console.

Does not reproduce on Android or iOS — only Flutter Web.

Other animation-driven widgets (custom AnimationController, AnimatedBuilder) can cause similar errors if active during hot restart.

This is new; it worked fine in earlier stable releases.

### Expected results

Hot restart should cleanly reset the app state without leaving behind any tickers or animation frames.

### Actual results

Hot restart leaves the CircularProgressIndicator’s ticker running, causing an infinite stream of !isDisposed exceptions. Same with pulseExample

### Code sample

<details open><summary>Code sample Progress Indicator</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: CircularProgressIndicator(), // culprit
        ),
      ),
    );
  }
}
```

</details>

<details open><summary>Code sample Another animationController</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: PulseExample(),
        ),
      ),
    );
  }
}

class PulseExample extends StatefulWidget {
  const PulseExample({super.key});

  @override
  State<PulseExample> createState() => _PulseExampleState();
}

class _PulseExampleState extends State<PulseExample>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(vsync: this, duration: const Duration(seconds: 1));
    _scale = Tween<double>(begin: 1.0, end: 1.5).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeInOut),
    );
    _loop();
  }

  Future<void> _loop() async {
    while (mounted) {
      await _controller.forward();
      await _controller.reverse();
    }
  }

  @override
  void dispose() {
    _controller.stop();
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _scale,
      builder: (_, child) =>
          Transform.scale(scale: _scale.value, child: child),
      child: const Icon(Icons.favorite, size: 64, color: Colors.red),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================
Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.35.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a402d9a437 (8 days ago) • 2025-09-03 14:54:31 -0700
Engine • hash 672c59cfa87c8070c20ba2cd1a6c2a1baf5cf08b (revision ddf47dd3ff) (8 days ago) • 2025-09-03 20:02:13.000Z
Tools • Dart 3.9.2 • DevTools 2.48.0
PS C:\Users\hanne\AndroidStudioProjects\hot_restart_with_material_app_router> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.35.3, on Microsoft Windows [Version 10.0.26100.6584], locale en-GB)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.99.3)
[√] Connected device (3 available)
    ! Device Z5P7WG7TJJTCR4PZ is offline.
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by mdebbar**
Fixes https://github.com/flutter/flutter/issues/140684
Fixes https://github.com/flutter/flutter/issues/175260

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart [hunk 1]
```diff
@@ -98,6 +105,18 @@ class FrameService {
...
+      if (_isDisposed) {
+        // Skip this animation frame because the instance has been disposed, meaning there was a
+        // hot restart performed. During a hot restart, Dart automatically cancels timers and
+        // microtasks, but animation frames are requested directly from the browser which isn't
+        // aware of hot restarts, and that leads to problems.
+        //
+        // See:
+        // - https://github.com/flutter/flutter/issues/175260
+        // - https://github.com/flutter/flutter/issues/140684#issuecomment-3251179364
+        return;
```
Comment (nshahan) [inline engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart:117]: Is there some cleanup that should also be done so this FrameService can eventually be garbage collected or will it stay alive, silently skipping all frames from now on?

**Review by nshahan — APPROVED** [review]
Thanks for taking a look at this!

File: engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart (hunk 1 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart:117]: IIUC, what was happening before this PR is both generations kept pumping frames. The old generation is supposed to die out after the hot restart, but (unlike timers and microtasks) this callback/closure isn't cleaned up so it calls into the old generation code keeping it alive.

This `return;` is short-circuiting the code that's keeping the old generation alive.

I can't confirm everything I said, it's just my understanding based on observation and vague understanding. The one thing I confirmed is by adding a `print` right before the `return;`, that print is only executed once for each hot restart.

The code in `_dispose` also clears `FrameService._instance` forcing the next frame to create a new instance. The old `FrameService` instance becomes an orphan and is GC'd normally by the browser I presume.

Comment (nshahan) [reply engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart:117]: My understanding here is vague as well but that makes sense. Glad to hear we only hit that short circuiting return once. Thanks!
