### PR TITLE
[flutter_tools] expand Regexp log match to include more AndroidRuntime failures

### LINKED ISSUE #56937: Show AndroidRuntime crashes from invalid AndroidManifest.xml in logs
The APK can fail to launch if the package name for the main activity is incorrect. This log seems to be filtered out, making the crash non-obvious. Instead the flutter tool hangs on "Waiting for observatory..." 

To reproduce this, `flutter create`  a new project and apply the following diff:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.foobar">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
---           android:name="io.flutter.app.FlutterApplication"
+++        android:name="io.flutter.app.FlutterApplication2"
        android:label="foobar"
        android:icon="@mipmap/ic_launcher">
        <activity
```

The resulting crash from logcat:

```
05-11 12:41:51.849  9709  9709 D AndroidRuntime: Shutting down VM
05-11 12:41:51.850  9709  9709 E AndroidRuntime: FATAL EXCEPTION: main
05-11 12:41:51.850  9709  9709 E AndroidRuntime: Process: com.example.foobar, PID: 9709
05-11 12:41:51.850  9709  9709 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application io.flutter.app.FlutterApplication2: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.FlutterApplication2" on path: DexPathList[[zip file "/data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/lib/arm64, /data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1226)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-11 12:41:51.850  9709  9709 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.FlutterApplication2" on path: DexPathList[[zip file "/data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/lib/arm64, /data/app/com.example.foobar-jjAiPTSBxSHLbAR1O2qlvQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1155)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
05-11 12:41:51.850  9709  9709 E AndroidRuntime:        ... 9 more
05-11 12:41:51.853  1412  6080 W ActivityTaskManager:   Force finishing activity com.example.foobar/.MainActivity
05-11 12:41:51.856  1412  9759 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/56937

The format of AndroidRuntime exceptions is different, either on certain devices or when the application crashes due to an incorrectly name application name

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -1019,6 +1020,7 @@ class AdbLogReader extends DeviceLogReader {
     }
     final Match timeMatch = AndroidDevice._timeRegExp.firstMatch(line);
     if (timeMatch == null || line.length == timeMatch.end) {
+      _acceptedLastLine = false;
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_device.dart:1023]: Without this change its really hard to stop the log reader with mocked output from just passing everything though

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by jmagman — APPROVED** [review]
LGTM
