### PR TITLE
Fixed the issue that Slider's secondaryTrackValue is not updated.

### LINKED ISSUE #163971: Slider doesn't repaint on secondaryTrackValue update.
### Steps to reproduce

1. Create a `Slider` with zero `secondaryTrackValue` and any button.
2. Schedule updating the value of `secondaryTrackValue` and don't touch the screen until updating fires.

### Expected results

3. The slider repaints.

### Actual results

3. The slider doesn't show the new `secondaryTrackValue`.
4. Hover the button and see repainting of the slider.

The setter `_RenderSlider.secondaryTrackValue` should call `markNeedsPaint` instead of `markNeedsSemanticsUpdate`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Slider].

void main() => runApp(const SliderApp());

class SliderApp extends StatelessWidget {
  const SliderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: SliderExample());
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double _currentSliderPrimaryValue = 0.0;
  double _currentSliderSecondaryValue = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Slider')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Slider(
            value: _currentSliderPrimaryValue,
            secondaryTrackValue: _currentSliderSecondaryValue,
            label: _currentSliderPrimaryValue.round().toString(),
            onChanged: (double value) {
              setState(() {
                _currentSliderPrimaryValue = value;
              });
            },
          ),
          ElevatedButton(
            onPressed: () {
              Future.delayed(const Duration(seconds: 1), () {
                setState(() => _currentSliderSecondaryValue = 0.2);
              });
            },
            child: Text('Update secondary value'),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/fc9c543c-d616-4197-b042-ef3bd80061c7

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes: #163971

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -5179,4 +5231,36 @@ void main() {
...
+
+    await tester.pumpWidget(buildSlider(null));
+    await tester.pumpAndSettle();
+    expect(log.last, isNull);
+    await tester.pumpWidget(buildSlider(0.2));
+    await tester.pumpAndSettle();
+    expect(log.last, const Offset(174.4, 300.0));
+    await tester.pumpWidget(buildSlider(0.5));
+    await tester.pumpAndSettle();
+    expect(log.last, const Offset(400.0, 300.0));
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:5264]:
```suggestion
    await tester.pumpWidget(buildSlider(null));
    await tester.pumpAndSettle();
    expect(log.last, isNull);

    await tester.pumpWidget(buildSlider(0.2));
    await tester.pumpAndSettle();
    expect(log.last, const Offset(174.4, 300.0));

    await tester.pumpWidget(buildSlider(0.5));
    await tester.pumpAndSettle();
    expect(log.last, const Offset(400.0, 300.0));
```

Just for better readability

File: packages/flutter/test/material/slider_test.dart [hunk 2]
```diff
@@ -16,6 +16,58 @@ import 'package:flutter_test/flutter_test.dart';
 
 import '../widgets/semantics_tester.dart';
 
+/// A [RoundedRectSliderTrackShape] that logs its paint.
+class LoggingRoundedRectSliderTrackShape extends RoundedRectSliderTrackShape {
+  LoggingRoundedRectSliderTrackShape({this.secondaryOffsetLog});
+  final List<Offset?>? secondaryOffsetLog;
+  @override
+  Rect getPreferredRect({
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:24]:
```suggestion
  final List<Offset?>? secondaryOffsetLog;

  @override
  Rect getPreferredRect({
```

**Review by TahaTesser — APPROVED** [review]
LGTM! With minor nits

File: packages/flutter/test/material/slider_test.dart [hunk 3]
```diff
@@ -5179,4 +5232,38 @@ void main() {
     await gesture.up();
     await tester.pumpAndSettle();
   });
+
+  testWidgets('secondaryTrackValue updates correctly', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/slider_test.dart:5236]: Nit: Consider elaborating on "correctlly".

**Review by justinmc — APPROVED** [review]
LGTM with a nit 👍
